### PR TITLE
AMDGPU: Expand flat atomics that may access private memory

### PR DESCRIPTION
**Pull request by arsenm**
If the runtime flat address resolves to a scratch address,
64-bit atomics do not work correctly. Insert a runtime address
space check (which is quite likely to be uniform) and select between
the non-atomic and real atomic cases.

Consider noalias.addrspace metadata and avoid this expansion when
possible (we also need to consider it to avoid infinitely expanding
after adding the predication code).

### CODE REVIEW

**Comment by arsenm** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109407?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#109408** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109408?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#109407** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109407?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#109406** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109406?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#102599** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/102599?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#102461** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/102461?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 2 other dependent PRs ([#102462](https://github.com/llvm/llvm-project/pull/102462) <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/102462?utm_source=stack-comment-icon" target="_blank">Graphite</a>, [#103938](https://github.com/llvm/llvm-project/pull/103938) <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/103938?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by rampitec** [comment]
Is it legal and defined behavior to target private memory with an atomic?

**Comment by arsenm** [comment]
> Is it legal and defined behavior to target private memory with an atomic?

In the IR it would have to be, and this is the expected behavior in OpenMP and C++. It's UB in OpenCL, and UB in CUDA/HIP for old style atomics, but defined for new std::atomic style cases

**Comment by rampitec** [comment]
> > Is it legal and defined behavior to target private memory with an atomic?
> 
> In the IR it would have to be, and this is the expected behavior in OpenMP and C++. It's UB in OpenCL, and UB in CUDA/HIP for old style atomics, but defined for new std::atomic style cases

Is there a plan that OpenCL and HIP FE will produce noalias metadata to avoid the expansion?

**Comment by arsenm** [comment]
> Is there a plan that OpenCL and HIP FE will produce noalias metadata to avoid the expansion?

That's #102462 (although I think it needs refinement to avoid setting it in the std::atomic case)

**Review by rampitec — APPROVED** [review]
Thanks. Can this be landed after https://github.com/llvm/llvm-project/pull/102462?

**Comment by arsenm** [comment]
> Thanks. Can this be landed after #102462?

That was the plan

**Comment by arsenm** [comment]
### Merge activity

* **Oct 31, 11:07 AM EDT**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/109407).

**Pull request merged**
