### PR TITLE
Revert 112e49b38150b8bfdef01434309d1b05204193e4 due to a miscompile

### PR DESCRIPTION
**Pull request by alexfh**
- Revert "[DAGCombiner] Transform `(icmp eq/ne (and X,C0),(shift X,C1))` to use rotate or to getter constants." - causes a miscompile, see https://github.com/llvm/llvm-project/commit/112e49b38150b8bfdef01434309d1b05204193e4#commitcomment-131943923
- Revert "[X86] Fix gcc warning about mix of enumeral and non-enumeral types. NFC", which fixes a compiler warning in the commit above

### CODE REVIEW

**Comment by alexfh** [comment]
Given no objections and no alternative solutions so far and that this is a real correctness problem, I'm going to move forward with the revert.

**Comment by RKSimon** [comment]
@alexfh Hadn't @goldsteinn identified that #71489 was the fix to the underlying issue? Did that patch address the miscompiles you were seeing?

**Comment by RKSimon** [comment]
I'm not asking you to re-revert this - just wanting to ensure we track this properly for them to be re-committed.

**Comment by alexfh** [comment]
> @alexfh Hadn't @goldsteinn identified that #71489 was the fix to the underlying issue? Did that patch address the miscompiles you were seeing?

I haven't seen https://github.com/llvm/llvm-project/pull/71489 in particular in relation to https://github.com/llvm/llvm-project/commit/112e49b38150b8bfdef01434309d1b05204193e4. I can check whether the patch fixes the miscompile we see.

**Comment by alexfh** [comment]
@RKSimon The proposed fix in #71489 claims to address #71330, which is caused by a different commit - 0289dad538fa2fdc1a82a26f5d19f94fbd20d949. I've verified that it doesn't fix the miscompile introduced in 112e49b38150b8bfdef01434309d1b05204193e4. Thus, the revert here is still necessary.

**Comment by RKSimon** [comment]
Oops - sorry about that - that'll teach me for trying to use the sodding github app to keep track of everything!

**Comment by goldsteinn** [comment]
Thank you for reverting. Looking into the issue.

**Comment by goldsteinn** [comment]
Okay appears the impl is using the wrong type size somewhere
The transform taking place is:
From:
```
t24: i1 = setcc t19, t22, setne:ch
  t19: i32 = and t3, Constant:i32<7>
    t3: i32 = truncate t2
      t2: i64,ch = CopyFromReg t0, Register:i64 %1
        t0: ch,glue = EntryToken
  t22: i32 = srl t3, Constant:i8<5>
```
To:
```
t33: i1 = setcc t32, t30, setne:ch
  t32: i32 = and t3, Constant:i32<-32>
    t3: i32 = truncate t2
      t2: i64,ch = CopyFromReg t0, Register:i64 %1
        t0: ch,glue = EntryToken
  t30: i32 = shl t3, Constant:i8<5>
```

Which is correct for i8, not i32 though.

**Comment by goldsteinn** [comment]
The following seems to be the fix:
```
-        bool CanTransform =
-            IsRotate ||
-            (*ShiftCAmt == (~*AndCMask).popcount() && ShiftOpc == ISD::SHL
-                 ? (~*AndCMask).isMask()
-                 : AndCMask->isMask());
+        bool CanTransform = IsRotate;
+        if (!CanTransform) {
+          // Check that mask and shift compliment eachother
+          CanTransform = *ShiftCAmt == (~*AndCMask).popcount();
+          // Check that we are comparing all bits
+          CanTransform &= (*ShiftCAmt + AndCMask->popcount()) == NumBits;
+          // Check that the and mask is correct for the shift
+          CanTransform &=
+              ShiftOpc == ISD::SHL ? (~*AndCMask).isMask() : AndCMask->isMask();
+        }
```

Will post patch for recommit shortly.

**Comment by goldsteinn** [comment]
PR with fix at: #71729

**Pull request merged**
