### PR TITLE
[lldb-dap] Fix a race during shutdown

### PR DESCRIPTION
**Pull request by labath**
lldb-dap was setting a flag which was meant to shut it down as soon as it sent a terminated event. The problem with this flag is two-fold:
- as far as I can tell (definitely not an expert here), there's no justification for this in the protocol spec. The only way I found to shut the server down was to send it a disconnect request.
- the flag did not actually work most of the time, because it's only checked between requests so nothing will happen if the server starts listening for a new request before a different thread manages to send the terminated event. And since the next request is usually the disconnect request, everything will operate normally.

The combination of these two things meant that the issue was largely unnoticable, except for rare flaky test failures, which happened when the handler thread was too slow, and checked the flag after it has already been said. This caused the test suite to complain as it did not get a response to the disconnect request. This situation could be s(t)imulated by adding a sleep to the and of the main loop, which delayed the flag check, and caused the DAP tests to fail reliably.

This patch changes the shutdown condition to only trigger when the disconnect request has been received. Since the flag can now only be set from the handler thread, it no longer needs to be atomic.

### CODE REVIEW

**Comment by labath** [comment]
https://lab.llvm.org/buildbot/#/builders/68/builds/73871 is an example of such a failure.

**Review by walter-erquinigo — APPROVED** [review]
This all makes sense to me. Thank you!

**Review by clayborg — COMMENTED** [review]
I can't remember: does terminate come before disconnecting? Or is it the other way around?

**Comment by labath** [comment]
> I can't remember: does terminate come before disconnecting? Or is it the other way around?

Disconnect docs say "The disconnect request asks the debug adapter to disconnect from the debuggee (thus ending the debug session) and then to shut down itself (the debug adapter).", so it has to be the last request. The terminate just terminates the debuggee and, if the client&server support it, the debuggee can be restarted after that.

**Review by clayborg — APPROVED** [review]
Sounds good, thanks for the clarification.

**Comment by kusmour** [comment]
> > I can't remember: does terminate come before disconnecting? Or is it the other way around?
> 
> Disconnect docs say "The disconnect request asks the debug adapter to disconnect from the debuggee (thus ending the debug session) and then to shut down itself (the debug adapter).", so it has to be the last request. The terminate just terminates the debuggee and, if the client&server support it, the debuggee can be restarted after that.

This patch resulted in terminated event being sent twice for every session. One from `exited` event one from `disconnect` request. Before this patch the behavior was:
- Debuggee program exits
DAP msg: exited event --> terminated event --> disconnect request --> disconnect response
- User initiated stop debugging
DAP msg: disconnect request --> exited event --> terminated event --> disconnect response

Now
- Debuggee program exits
DAP msg: exited event --> terminated event --> disconnect request --> terminated event --> disconnect response
- User initiated stop debugging
DAP msg: disconnect request --> exited event --> terminated event --> disconnect response --> terminated event

(Also not sure why the terminated event comes after disconnect response in the second scenario)

**Comment by labath** [comment]
Ah yes, of course, I've kept the mutex thinking that its sufficient to make it run only once, but of course that's only true if the critical section actually contains a "run once" check. I'll create a patch for that tomorrow. Feel free to revert in the mean time if this is blocking something.

**Pull request merged**
