### PR TITLE
[Serialization] Read the initializer for interesting static variables before consuming it

### LINKED ISSUE #91418: [clang][PCH] Initialization order issue after change to lazy initializer loading
After commit [bc73ef0031](https://github.com/llvm/llvm-project/commit/bc73ef0031b50f7443615fef614fb4ecaaa4bd11) we see an incorrect initialization order with the attached code. This occurs with PCH use only.

With a vanilla native clang with the above commit on Ubuntu 22.04:

clang -fmath-errno -o t.pch -x c++-header t.h
clang -fmath-errno -S t.cpp -include-pch t.pch
clang -o t t.s -lm
./t

we get the expected

p:0.225000
a:7.589466
b:1.633843
A:7.589466 7.589466 7.589466 7.589466
B:1.633843 1.633843 1.633843 1.633843

But with

clang -fno-math-errno -o t.pch -x c++-header t.h
clang -fno-math-errno -S t.cpp -include-pch t.pch
clang -o t t.s -lm
./t

we get 

p:0.225000
a:7.589466
b:1.633843
A:0.000000 0.000000 0.000000 0.000000
B:0.000000 0.000000 0.000000 0.000000

Looking at the code the vectors 'A' and 'B' are initialized before 'a' and 'b' in the failing example.
[init.zip](https://github.com/llvm/llvm-project/files/15242786/init.zip)

### PR DESCRIPTION
**Pull request by ChuanqiXu9**
Close https://github.com/llvm/llvm-project/issues/91418

Since we load the variable's initializers lazily, it'd be problematic if the initializers dependent on each other. So here we try to load the initializers of static variables to make sure they are passed to code generator by order. If we read any thing interesting, we would consume that before emitting the current declaration.

### CODE REVIEW

**Comment by ChuanqiXu9** [comment]
@JonasToth @redstar @uweigand @Everybody0523 

Hi, this patch previously failed on  clang-s390x-linux. I guess it is a pattern mismatch  failure but I can't reproduce it. I am not sure if I found the wrong person. I find you from the SystemZ's group. I want to ask if you can verify the patch can pass on that platform? And if not, could you provide the generated pattern so that I can try to match it?

**Comment by uweigand** [comment]
I'm not seeing any failures with this patch on s390x with the regular check-all and check-openmp tests.  Do you have a link to the failures you were seeing in the past (was that on the build bot?)?

**Comment by redstar** [comment]
The lines you are trying to match are:

```
  call void @_Z6MakeVRffff(ptr dead_on_unwind writable sret(<4 x float>) align 16 %tmp, float noundef %0, float noundef %1, float noundef %2, float noundef %3)
  %4 = load <4 x float>, ptr %tmp, align 16
  store <4 x float> %4, ptr @_ZN21VectorSinConstantsSSE1AE, align 16
```

I am not sure what is the best way to integrate that into the patterns.

**Comment by ChuanqiXu9** [comment]
> I can reproduce the failure. The problem is that the CHECK line
> 
> ```
> // CHECK: [[A_CALL:%[a-zA-Z0-9]+]] = call{{.*}}@_Z6MakeVRffff(
> ```
> 
> assumes that a value is returned. On SystemZ, the return value is passed as `sret` argument, and the function itself returns `void`, so the pattern does not match.

Oh, thanks! I never heard that before. I guess I don't need to check the call since what I need to check is the order the variable get initialized.

I'll try to land this after the build bot gets green.

**Pull request merged**
