### PR TITLE
[Clang] Implement P2864R2 Remove Deprecated Arithmetic Conversion on…

### PR DESCRIPTION
**Pull request by cor3ntin**
… Enumerations

https://isocpp.org/files/papers/P2864R2.pdf

### CODE REVIEW

**Review by AaronBallman — APPROVED** [review]
LGTM -- I'm a bit worried about breaking working code, but the user has to explicitly opt into C++26 mode and so it's only slightly unreasonable for them to have to change their previously correct, working code because of this. I say we leave it as an error, but if users complain about this being too strict, we can relax it to be a warning that defaults to an error or just leave it deprecated and support it forever.

**Comment by dyung** [comment]
@cor3ntin Your commit seems to be causing 2 test failures in the clang-tools-extra tests, can you try to fix them or revert if you need time to investigate?

https://lab.llvm.org/buildbot/#/builders/139/builds/54467

**Comment by cor3ntin** [comment]
@PiotrZSL You beat me to it, thanks a lot!

**Comment by PiotrZSL** [comment]
Actually that is more like a quick fix, we can live with it. More proper way would be simply to split those tests into pre-c++20 and universal.

**Pull request merged**
