### PR TITLE
[dsymutil] Fix whitespace issues and typo in HelpText.

### PR DESCRIPTION
**Pull request by rjmansfield**

### CODE REVIEW

**Comment by zimirza** [comment]
Wouldn't removing the whitespaces combine the words? I think these are string concatenation.

**Comment by rjmansfield** [comment]
I believe you're reading the diff backwards.

**Comment by zimirza** [comment]
Yes, you are correct. Sorry about that.

**Review by JDevlieghere — APPROVED** [review]

**Comment by rjmansfield** [comment]
Could someone with commit access merge on my behalf? Thanks.

**Pull request merged**
