### PR TITLE
[lldb] Use system c++ lib for LLDB STL tests

### PR DESCRIPTION
**Pull request by zeroomega**
This change partially reverts #112357 to avoid test failures on machines which do not have gcc installed.

Test run: https://ci.chromium.org/ui/p/fuchsia/builders/toolchain.ci.shadow/lldb-linux-x64/b8733897350805827393/overview

### CODE REVIEW

**Review by Michael137 — COMMENTED** [review]
I believe we need to just remove all the USE_ variables. The PR that broke your bots was itself motivated by a breakage due to USE_SYSTEM_STDLIB

**Comment by zeroomega** [comment]
> I believe we need to just remove all the USE_ variables. The PR that broke your bots was itself motivated by a breakage due to USE_SYSTEM_STDLIB

Done.
Test run in progress: https://ci.chromium.org/b/8733895290278713505

**Comment by zeroomega** [comment]
The patch passed all presubmit tests.
Can I get a approval to land it?

**Review by Michael137 — APPROVED** [review]
LGTM thx!

**Pull request merged**
