### PR TITLE
[RISCV] Make M imply Zmmul

### PR DESCRIPTION
**Pull request by jacquesguan**
According to the spec, M implies Zmmul.

### CODE REVIEW

**Comment by topperc** [comment]
We intentionally didn't do this because it makes LLVM not work with binutils that doesn't know about Zmmul. Maybe enough time has  passed that it is no longer an issue?

**Comment by jacquesguan** [comment]
> We intentionally didn't do this because it makes LLVM not work with binutils that doesn't know about Zmmul. Maybe enough time has passed that it is no longer an issue?

Since Zmmul was ratified at june 2022, I think it's OK to update it now.

**Review by topperc — APPROVED** [review]
LGTM

**Comment by preames** [comment]
Given the concern about breaking configurations w/no-integrated-as and older binutils, can someone summarize here which versions of binutils are known to work/not work after this change?  This will likely become the key search result for such breakage, and having it well documented for users seems critical.

**Pull request merged**
