### PR TITLE
[AArch64] Add ZIP and UZP shuffle costs.

### PR DESCRIPTION
**Pull request by davemgreen**
This adds some costs for the shuffle instructions that should be lowered to zip1/zip2/uzp1/uzp2 instructions.

### CODE REVIEW

**Review by SamTebbs33 — APPROVED** [review]
LGTM.

**Comment by davemgreen** [comment]
Thanks

**Comment by sjoerdmeijer** [comment]
Just a question about performance: did you measure any perf improvements/regressions?

**Comment by davemgreen** [comment]
Hello. Yes it fixed some regressions from #87510, in a similar way to #87934. Do you have any cases where it is causing problems?

**Comment by sjoerdmeijer** [comment]
> Hello. Yes it fixed some regressions from #87510, in a similar way to #87934. Do you have any cases where it is causing problems?

Ok, that's great. I don't have any specific cases, it was just a curiousity because shuffle vectors has caused us some pain and was wondering if making them cheaper (at least some variants) would lead to any surprises.

This also LGTM, let's see how this behaves.

**Pull request merged**
