### PR TITLE
[flang] Allow assumed-shape element pass to dummy arg with ignore_tkr

### PR DESCRIPTION
**Pull request by tblah**
This is allowed by gfortran and ifort with `![GCC|DEC]$ ATTRIBUTES NO_ARG_CHECK`

### CODE REVIEW

**Comment by tblah** [comment]
I'm not sure if `'r'` is the right specifier for this, maybe there should be a new one?

**Review by klausler — COMMENTED** [review]
I don't think that 'R' is the right letter to use here.  It's not about rank, it's about storage sequence association with a potentially non-contiguous object.  Besides assumed-shape arrays, you probably also want to allow non-`CONTIGUOUS` pointers.

**Comment by tblah** [comment]
Thanks for the review. I repurposed the (previously legacy) `ignore_tkr(c)`.

**Comment by klausler** [comment]
> Thanks for the review. I repurposed the (previously legacy) `ignore_tkr(c)`.

That might conflict with legacy codes still being compiled by nvfortran.  I'll check.

**Comment by klausler** [comment]
> > Thanks for the review. I repurposed the (previously legacy) `ignore_tkr(c)`.
> 
> That might conflict with legacy codes still being compiled by nvfortran. I'll check.

The legacy meaning of `C` is your interpretation here, so I think it's okay.

**Comment by tblah** [comment]
@klausler thanks for checking my use of `C`.

As `C` is okay, is there anything blocking merging this patch?

**Review by klausler — APPROVED** [review]
Ship it with my thanks.

**Pull request merged**
