### PR TITLE
Revert "Set ObjectFile's assignment operator to also be deleted like its copy constructor"

### PR DESCRIPTION
**Pull request by fsfod**
Reverts llvm/llvm-project#92942

### CODE REVIEW

**Review by dyung — APPROVED** [review]
lgtm.

Did you see the comment I left in the original review?

**Comment by fsfod** [comment]
yes, i just thought this was was quickest way to unbeak the build.

**Comment by dyung** [comment]
Are you able to submit the revert or do you need it submitted for you?

**Comment by fsfod** [comment]
i need it submitted

**Pull request merged**
