### PR TITLE
[clang][NFC] Replace TypeAlignment with alignof(T)

### PR DESCRIPTION
**Pull request by Endilll**
This patch replaces usages of `TypeAlignment` with `alignof(T)`, where `T` is type that will be created in allocated storage with placement-new. This is now possible, because `alignof` reports the correct alignment for `Type` and classes derived from it after #68377 was merged.

While preparing #68377 I verified via `static_assert` that there are no mismatches of alignment between `TypeAlignment` and alignment of types derived from `Type`, so no changes are expected to codegen.

### CODE REVIEW

**Comment by cor3ntin** [comment]
Should we remove `TypeAlignment` then ? I don't see it used anywhere else

**Comment by Endilll** [comment]
It's in our public headers, and downstream users were supposed to rely on it, because `alignof` for `Type` and all its derived types reported the wrong value. So while I agree with you, I lean towards it being a breaking change which should be handled appropriately.

**Comment by cor3ntin** [comment]
I'm not sure we care (the api is not meant to be stable  - that's why we have a c wrapper) but  @AaronBallman should weight on that

**Comment by AaronBallman** [comment]
> I'm not sure we care (the api is not meant to be stable - that's why we have a c wrapper) but @AaronBallman should weight on that

Basically none of our internal C++ APIs have a stability guarantee, so we're free to refactor as we see fit. In this case, I don't see much danger to removing `TypeAlignment` if it's no longer being used.

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Review by cor3ntin — APPROVED** [review]

**Pull request merged**
