### PR TITLE
Add -fkeep-system-includes modifier for -E

### PR DESCRIPTION
**Pull request by pogo59**
This option will cause -E to preserve the #include directives
for system headers, rather than expanding them into the output.
This can greatly reduce the volume of preprocessed source text 
in a test case, making test case reduction simpler.

Note that -fkeep-system-includes is not always appropriate. For
example, if the problem you want to reproduce is induced by a
system header file, it's better to expand those headers fully.
If your source defines symbols that influence the content of a
system header (e.g., _POSIX_SOURCE) then -E will eliminate the
definition, potentially changing the meaning of the preprocessed
source. If you use -isystem to point to non-system headers, for
example to suppress warnings in third-party software, those will
not be expanded and might make the preprocessed source less useful
as a test case.

### CODE REVIEW

**Comment by jrtc27** [comment]
Its limitations, i.e. how in various cases it can break or change correct code, need to be documented somewhere alongside the option (ideally a disclaimer in --help's output and a longer explanation in the rendered documentation).

**Comment by pogo59** [comment]
@jrtc27 I've beefed up the help text some. I'm unable to find any "rendered documentation" for `-E` and friends; if you can point me to it, I'd be happy to add the new option there.

**Comment by jrtc27** [comment]
I mean places like https://clang.llvm.org/docs/ClangCommandLineReference.html and https://clang.llvm.org/docs/UsersManual.html#command-line-options.

**Comment by jrtc27** [comment]
Oh and https://clang.llvm.org/docs/CommandGuide/clang.html.

**Comment by pogo59** [comment]
Aha! Thank you. I should have found that third one in my searches, although it doesn't really describe the options that affect `-E` mode. The first link does, somewhat, and seems like the right place to add this new option. I'll have a go at that.

**Comment by pogo59** [comment]
> The first link does, somewhat, and seems like the right place to add this new option. I'll have a go at that.

Well, that one appears to be generated from the Options.td file, and simply includes the help text, so in effect I've already done that. :)

UsersManual.html doesn't have a preprocessor options section at all, and I think it's outside the scope of this patch to add one.

clang.html (actually CommandGuide/clang.rst) doesn't really talk about the other `-E` affecting options, but at least it has a subsection about preprocessor options, so I'll see what I can do there.

**Comment by pogo59** [comment]
Also added a release note.

**Comment by pogo59** [comment]
Ping @erichkeane were you willing to approve both this and #67613?

**Review by erichkeane — COMMENTED** [review]
This too fails the formatter.  That said, I have no comments, though preprocessing isn't my place of expertise.  Most of the changes are pretty mild though, and the approach of just replacing the output file with a null-OS seems appropriate.  Fix the formatting, and I'll accept, but please give others (Aaron in particular) time to take a look before committing.

**Comment by pogo59** [comment]
Many of the clang-format complaints on this one are from the first commit, which I wanted to make as minimalist as possible. I believe I didn't make the file any _less_ conformant in that commit. :)  I will fix the others.

**Review by erichkeane — APPROVED** [review]

**Comment by pogo59** [comment]
Something got screwed up when I tried to squash all but the first commit together. I put it back together manually. The NFC commit was pushed as 9500616, the functional stuff squashed and committed as 71d83bb.

**Pull request closed without merging**
