### PR TITLE
[AArch64]  Add initial support for FUJITSU-MONAKA

### PR DESCRIPTION
**Pull request by kinoshita-fj**
FUJITSU-MONAKA is a CPU we are currently developing.

This is the slides for the CPU: https://www.fujitsu.com/downloads/SUPER/topics/isc24/next-arm-based-processor-fujitsu-monaka-and-its-software-ecosystem.pdf

### CODE REVIEW

**Comment by kinoshita-fj** [comment]
@davemgreen @sjoerdmeijer

**Comment by davemgreen** [comment]
Did you prefer this to be `-mcpu=fujitsu-monaka` or `-mcpu=monaka`?

Can you rebase - the sve2aes feature has been reworked #114293.

**Review by jthackray — APPROVED** [review]
LGTM

**Comment by kinoshita-fj** [comment]
I prefer `-mcpu=fujitsu-monaka`. I want to include `fujitsu` because `FUJITSU-MONAKA` is the official name.

I fixed the issues related to sve2aes.

**Comment by davemgreen** [comment]
> I prefer `-mcpu=fujitsu-monaka`. I want to include `fujitsu` because `FUJITSU-MONAKA` is the official name.
> 
> I fixed the issues related to sve2aes.

Sounds good, either sounds OK to me. LGTM

**Review by davemgreen — APPROVED** [review]

**Comment by davemgreen** [comment]
We never know who does and doesn't have commit access. Let us know if you are happy and want us to hit submit. Thanks.

**Pull request merged**
