### PR TITLE
[mlir][Vector] NFC - Fix doc generation

### PR DESCRIPTION
**Pull request by nicolasvasilache**

### CODE REVIEW

**Comment by nicolasvasilache** [comment]
I verified that `cat build/tools/mlir/docs/Dialects/Vector.md`  now gets populated with the ops when using `cmake --target mlir-doc` but I am unclear if this is properly linked in the website.

Does anyone know how to test that or are we essentially flying blind until we get it right ?

**Comment by c-rhodes** [comment]
> I verified that `cat build/tools/mlir/docs/Dialects/Vector.md` now gets populated with the ops when using `cmake --target mlir-doc` but I am unclear if this is properly linked in the website.

Fix makes sense to me, Vector.md includes auto-generated VectorOps.md and the ops are being generated there again.

> 
> Does anyone know how to test that or are we essentially flying blind until we get it right ?

It's documented here https://github.com/llvm/mlir-www/blob/main/README.md but it's a bit of a process.

**Review by c-rhodes — APPROVED** [review]
LGTM cheers

**Comment by MacDue** [comment]
This seems not to have worked https://mlir.llvm.org/docs/Dialects/Vector/ is still missing all the op docs.

**Pull request merged**
