### PR TITLE
[Clang][Sema] Make UnresolvedLookupExprs in class scope explicit specializations instantiation dependent

### LINKED ISSUE #99873: [clang][trunk] UNREACHABLE executed: Unexpected placeholder builtin type! Derived from source of UnrealEngine 5.4.3.
Compiler explorer link: https://godbolt.org/z/Yv6c67x6x

Source to reproduce issue:
```
struct S {
  int Value;
};

template <int I> class C {
public:
  template <typename T> T F() { return T(); }
  template <> S F() { return {F<decltype(S::Value)>()}; }
};

template class C<0>;
```
Stack dump:
```
<source>:8:31: error: cannot compile this l-value expression yet
    8 |   template <> S F() { return {F<decltype(S::Value)>()}; }
      |                               ^~~~~~~~~~~~~~~~~~~~~
Unexpected placeholder builtin type!
UNREACHABLE executed at /root/llvm-project/clang/lib/CodeGen/CodeGenTypes.cpp:601!
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics <source>
1.	<source>:11:20: current parser token ';'
2.	<source>:8:17: instantiating function definition 'C<0>::F<S>'
3.	<source>:8:17: LLVM IR generation of declaration 'C<0>::F'
4.	<source>:8:17: Generating code for declaration 'C<0>::F'
 #0 0x0000000003a6d508 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3a6d508)
 #1 0x0000000003a6b1fc llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3a6b1fc)
 #2 0x00000000039b4d48 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x000078f768c42520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x000078f768c969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #5 0x000078f768c42476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #6 0x000078f768c287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #7 0x00000000039c067a (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x39c067a)
 #8 0x0000000003f00364 clang::CodeGen::CodeGenTypes::ConvertType(clang::QualType) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3f00364)
 #9 0x00000000041d7ad0 clang::CodeGen::CodeGenFunction::EmitUnsupportedLValue(clang::Expr const*, char const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x41d7ad0)
#10 0x00000000041f3045 clang::CodeGen::CodeGenFunction::EmitLValueHelper(clang::Expr const*, clang::CodeGen::KnownNonNull_t) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x41f3045)
#11 0x00000000041f3b51 clang::CodeGen::CodeGenFunction::EmitLValue(clang::Expr const*, clang::CodeGen::KnownNonNull_t) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x41f3b51)
#12 0x0000000004204c20 clang::CodeGen::CodeGenFunction::EmitCallee(clang::Expr const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4204c20)
#13 0x00000000042050f5 clang::CodeGen::CodeGenFunction::EmitCallExpr(clang::CallExpr const*, clang::CodeGen::ReturnValueSlot) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x42050f5)
#14 0x0000000004255f82 (anonymous namespace)::ScalarExprEmitter::VisitCallExpr(clang::CallExpr const*) CGExprScalar.cpp:0:0
#15 0x000000000424c700 clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::Visit(clang::Stmt*) CGExprScalar.cpp:0:0
#16 0x000000000424e6cb (anonymous namespace)::ScalarExprEmitter::Visit(clang::Expr*) CGExprScalar.cpp:0:0
#17 0x0000000004250aed (anonymous namespace)::ScalarExprEmitter::VisitInitListExpr(clang::InitListExpr*) CGExprScalar.cpp:0:0
#18 0x000000000424ccf4 clang::StmtVisitorBase<std::add_pointer, (anonymous namespace)::ScalarExprEmitter, llvm::Value*>::Visit(clang::Stmt*) CGExprScalar.cpp:0:0
#19 0x00000000042523dc clang::CodeGen::CodeGenFunction::EmitScalarExpr(clang::Expr const*, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x42523dc)
#20 0x00000000041dc81e clang::CodeGen::CodeGenFunction::EmitAnyExpr(clang::Expr const*, clang::CodeGen::AggValueSlot, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x41dc81e)
#21 0x0000000003dc529b clang::CodeGen::CodeGenFunction::EmitReturnStmt(clang::ReturnStmt const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3dc529b)
#22 0x0000000003dcceb4 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3dcceb4)
#23 0x0000000003dd49a4 clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3dd49a4)
#24 0x0000000003e3b68e clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::Stmt const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e3b68e)
#25 0x0000000003e5023d clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e5023d)
#26 0x0000000003eb0562 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3eb0562)
#27 0x0000000003eab475 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3eab475)
#28 0x0000000003eaba1b clang::CodeGen::CodeGenModule::EmitGlobal(clang::GlobalDecl) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3eaba1b)
#29 0x0000000003eb5dc3 clang::CodeGen::CodeGenModule::EmitTopLevelDecl(clang::Decl*) (.part.0) CodeGenModule.cpp:0:0
#30 0x000000000437ccd6 (anonymous namespace)::CodeGeneratorImpl::HandleTopLevelDecl(clang::DeclGroupRef) ModuleBuilder.cpp:0:0
#31 0x000000000436d238 clang::BackendConsumer::HandleTopLevelDecl(clang::DeclGroupRef) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x436d238)
#32 0x000000000716adea clang::Sema::InstantiateFunctionDefinition(clang::SourceLocation, clang::FunctionDecl*, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x716adea)
#33 0x00000000070f3b17 clang::Sema::InstantiateClassMembers(clang::SourceLocation, clang::CXXRecordDecl*, clang::MultiLevelTemplateArgumentList const&, clang::TemplateSpecializationKind) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x70f3b17)
#34 0x00000000070f40e1 clang::Sema::InstantiateClassTemplateSpecializationMembers(clang::SourceLocation, clang::ClassTemplateSpecializationDecl*, clang::TemplateSpecializationKind) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x70f40e1)
#35 0x0000000006f1e4d2 clang::Sema::ActOnExplicitInstantiation(clang::Scope*, clang::SourceLocation, clang::SourceLocation, unsigned int, clang::SourceLocation, clang::CXXScopeSpec const&, clang::OpaquePtr<clang::TemplateName>, clang::SourceLocation, clang::SourceLocation, llvm::MutableArrayRef<clang::ParsedTemplateArgument>, clang::SourceLocation, clang::ParsedAttributesView const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6f1e4d2)
#36 0x00000000064bbb6a clang::Parser::ParseClassSpecifier(clang::tok::TokenKind, clang::SourceLocation, clang::DeclSpec&, clang::Parser::ParsedTemplateInfo&, clang::AccessSpecifier, bool, clang::Parser::DeclSpecContext, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x64bbb6a)
#37 0x0000000006490e31 clang::Parser::ParseDeclarationSpecifiers(clang::DeclSpec&, clang::Parser::ParsedTemplateInfo&, clang::AccessSpecifier, clang::Parser::DeclSpecContext, clang::Parser::LateParsedAttrList*, clang::ImplicitTypenameContext) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6490e31)
#38 0x0000000006555c0a clang::Parser::ParseDeclarationAfterTemplate(clang::DeclaratorContext, clang::Parser::ParsedTemplateInfo&, clang::ParsingDeclRAIIObject&, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6555c0a)
#39 0x0000000006556726 clang::Parser::ParseExplicitInstantiation(clang::DeclaratorContext, clang::SourceLocation, clang::SourceLocation, clang::SourceLocation&, clang::ParsedAttributes&, clang::AccessSpecifier) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6556726)
#40 0x0000000006563638 clang::Parser::ParseDeclarationStartingWithTemplate(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6563638)
#41 0x0000000006497aa3 clang::Parser::ParseDeclaration(clang::DeclaratorContext, clang::SourceLocation&, clang::ParsedAttributes&, clang::ParsedAttributes&, clang::SourceLocation*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6497aa3)
#42 0x0000000006455bb1 clang::Parser::ParseExternalDeclaration(clang::ParsedAttributes&, clang::ParsedAttributes&, clang::ParsingDeclSpec*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6455bb1)
#43 0x0000000006456a6f clang::Parser::ParseTopLevelDecl(clang::OpaquePtr<clang::DeclGroupRef>&, clang::Sema::ModuleImportState&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6456a6f)
#44 0x0000000006448b2a clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6448b2a)
#45 0x000000000437a818 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x437a818)
#46 0x00000000046056d9 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x46056d9)
#47 0x000000000458a34e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x458a34e)
#48 0x00000000046eea8e clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x46eea8e)
#49 0x0000000000c80b1f cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc80b1f)
#50 0x0000000000c79caa ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#51 0x00000000043bdf79 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#52 0x00000000039b51f4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x39b51f4)
#53 0x00000000043be56f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#54 0x0000000004383fd5 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4383fd5)
#55 0x0000000004384a3d clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4384a3d)
#56 0x000000000438c445 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x438c445)
#57 0x0000000000c7de55 clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc7de55)
#58 0x0000000000b537b4 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xb537b4)
#59 0x000078f768c29d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#60 0x000078f768c29e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#61 0x0000000000c7975e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xc7975e)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

### PR DESCRIPTION
**Pull request by sdkrystian**
Fixes #99873. Still needs tests.

### CODE REVIEW

**Review by zyn0217 — APPROVED** [review]
I think this makes sense. Thanks so much for the prompt fix.

For tests, I think we can just dump & validate the AST for the specialization, WDYT?

**Comment by sdkrystian** [comment]
> For tests, I think we can just dump & validate the AST for the specialization, WDYT?

Sounds reasonable, I'll do that.

**Comment by cor3ntin** [comment]
- Can we get rid of the whitespace only changes?
- Can we maybe introduce an enum, it's a lot of booleans that will be easy to mix. Maybe passing `ExprDependence` would be reasonable here

**Comment by sdkrystian** [comment]
> Can we get rid of the whitespace only changes?

@cor3ntin I have my editor configured to remove trailing whitespace on save. I'll just merge a commit to `main` that removes the trailing whitespace.

> Can we maybe introduce an enum, it's a lot of booleans that will be easy to mix. Maybe passing ExprDependence would be reasonable here

This sounds more like an unrelated refactoring change. I'm going to hold off on doing that in this patch.

**Comment by cor3ntin** [comment]
> This sounds more like an unrelated refactoring change. I'm going to hold off on doing that in this patch.
With this change, some of modified functions get multiple boolean back to back and we are for some of them at 11+ parameters. I think some cleanup would be in order
WDYT @AaronBallman ?

**Review by mizvekov — COMMENTED** [review]
I agree that the issue with many parameters is pre-existing.

So you add a new flag to the UnresolvedLookupExpr which just forwards to the same flag in the base class OverloadExpr.

OverloadExpr already suffers, even worse, from this problem of too many parameters and too many bools.

So I don't mind doing this cleanup in another patch.

**Comment by AaronBallman** [comment]
> > This sounds more like an unrelated refactoring change. I'm going to hold off on doing that in this patch.
> > With this change, some of modified functions get multiple boolean back to back and we are for some of them at 11+ parameters. I think some cleanup would be in order
> > WDYT @AaronBallman ?

Yeah, this did increase our tech debt slightly, so I think a cleanup is definitely needed around here. Given that this patch already landed, I'm fine with it being done as a follow-up, but I'd like that follow-up to happen sooner rather than later so we don't leave the cleanup for the next person to come along and deal with. In the future, I think it would be better to do the cleanup as an NFC change when a reviewer asks for it, then land additional changes on top of the cleaned up code (obviously this is also situational and there may be times when other approaches make more sense).

**Pull request merged**
