### PR TITLE
AMDGPU: Fix assertion on load of vector of pointers

### LINKED ISSUE #110433: [AMDGPU] Assertion hit in `infer-address-spaces` on vector of pointers
The following code hits an assertion, without assertions enabled it works fine https://godbolt.org/z/8nEzfPWEb.

### PR DESCRIPTION
**Pull request by arsenm**
Fix InferAddressSpaces asserting on a load of a vector of flat
pointers.

Fixes #110433

### CODE REVIEW

**Comment by arsenm** [comment]
* **#110436** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/110436?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by jhuber6 — APPROVED** [review]
Thanks for the fix.

**Comment by shiltian** [comment]
test?

**Comment by arsenm** [comment]
> test?

forgot to git add

**Pull request merged**
