### PR TITLE
[RISCV] Fix typo in UserGuides.rst. NFC

### PR DESCRIPTION
**Pull request by 4vtomat**

### CODE REVIEW

**Review by wangpc-pp — APPROVED** [review]

**Review by topperc — APPROVED** [review]
LGTM

**Review by asb — APPROVED** [review]
Do feel free to just directly commit simple fixes like this (and good catch!).

**Comment by 4vtomat** [comment]
> Do feel free to just directly commit simple fixes like this (and good catch!).

Do you mean commit without. an PR?

**Comment by asb** [comment]
> > Do feel free to just directly commit simple fixes like this (and good catch!).
> 
> Do you mean commit without a PR?

Yes, this is allowed in cases like this per the code review policy https://llvm.org/docs/CodeReview.html#must-code-be-reviewed-prior-to-being-committed

**Pull request merged**
