### PR TITLE
[LLVM] Clang format cleanups.

### PR DESCRIPTION
**Pull request by cmtice**
Cleaning up clang format issues on some files before making another change. All the changes in this CL came directly from running 'clang-format -i' on these files. No other changes are included here.

### CODE REVIEW

**Review by jh7370 — COMMENTED** [review]
So the changes look fine to me in principle. However, I'm worried this patch is running foul of the comment in the coding standards about large-scale reformatting:

> Our long term goal is for the entire codebase to follow the convention, but we explicitly do not want patches that do large-scale reformatting of existing code. On the other hand, it is reasonable to rename the methods of a class if you’re about to change it in some other way.

I suspect that your proposed next change won't touch most of the code you're proposing modifying. Am I correct?

https://discourse.llvm.org/t/rfc-clang-format-all-the-things/76614/35 discusses the situation a bit more and proposals around mass-reformatting, with the view to getting the codebase clean.

**Comment by cmtice** [comment]
James, you are correct, most of these changes are not directly in the code I am planning to refactor. But they are in the files containing the code I want to update.  I have found out the hard way that github insists that all files in your github pull request must pass its clang format tests whether or not the code that violates the clang format is code that you've actually modified.  Furthermore, when trying to deal with this github requirement, I've found that code reviewers don't like my mixing clang-format fixups with my other code changes.

I would *love* to change this painful github workflow, but I don't have the authority to do so.

**Comment by felipepiovezan** [comment]
> whether or not the code that violates the clang format is code that you've actually modified. 

I believe this used to happen early on, but this should not be the case anymore. I'd propose we give it a try again and document when clang-format fails so that we can prove or disprove this claim.

**Comment by MaskRay** [comment]
Instead of `clang-format -i` which formats the whole file, we usually specify `-lines` to restrict the formatting to the modified region. Then, usually there is no bulk formatting is needed at all.

See `clang/tools/clang-format/git-clang-format`

**Comment by cmtice** [comment]
Ok, the consensus is that this  is not needed and/or is the wrong approach. I'll see if I can make things work without it, using the suggestions given.

Thank you for the suggestions and advice.

**Pull request closed without merging**
