### PR TITLE
[MC] Make UseAssemblerInfoForParsing mostly true

### LINKED ISSUE #62520: Label differences not treated as absolute expressions in C __asm blocks even though they are in .s files
```
.text
start:
  nop
end:
.if (end - start) == 0
.err
.endif

```

compiles when saved as a .s file. But when the same is put into a .c file as:

__asm(
".text\n"
"start:\n"
"  nop\n"
"end:\n"
".if (end - start) == 0\n"
".err\n"
".endif\n"
);

it fails with `error: expected absolute expression`.  Gcc succeeds with both examples. https://github.com/llvm/llvm-project/issues/53728 is probably related.

### PR DESCRIPTION
**Pull request by MaskRay**
Commit 6c0665e22174d474050e85ca367424f6e02476be
(https://reviews.llvm.org/D45164) enabled certain constant expression
evaluation for `MCObjectStreamer` at parse time (e.g. `.if` directives,
see llvm/test/MC/AsmParser/assembler-expressions.s).

`getUseAssemblerInfoForParsing` was added to make `clang -c` handling
inline assembly similar to `MCAsmStreamer` (e.g. `llvm-mc -filetype=asm`),
where such expression folding (related to
`AttemptToFoldSymbolOffsetDifference`) is unavailable.

I believe this is overly conservative. We can make some parse-time
expression folding work for `clang -c` even if `clang -S` would still
report an error, a MCAsmStreamer issue (we cannot print `.if`
directives) that should not restrict the functionality of
MCObjectStreamer.

```
% cat b.cc
asm(R"(
.pushsection .text,"ax"
.globl _start; _start: ret
.if . -_start == 1
  ret
.endif
.popsection
)");
% gcc -S b.cc && gcc -c b.cc
% clang -S -fno-integrated-as b.cc     # succeeded

% clang -c b.cc     # succeeded with this patch
% clang -S b.cc     # still failed
<inline asm>:4:5: error: expected absolute expression
    4 | .if . -_start == 1
      |     ^
1 error generated.
```

Close #62520
Link: https://discourse.llvm.org/t/rfc-clang-assembly-object-equivalence-for-files-with-inline-assembly/78841

### CODE REVIEW

**Review by smithp35 — COMMENTED** [review]
The code-changes look good, what I'm less sure about is whether this is the right thing to do unconditionally. 

A few months ago I would likely to have said this wouldn't matter that much as most people don't use `-S` in there build systems so any failures are likely to have been of minor incovenience. However we recently encountered a customer using `-save-temps` on their main build, which produces assembly and then re-assembles it; in our case there was a problem with describing the target to the assembler so that step failed.

With this in mind I'm a bit reluctant to say that this wouldn't affect anyone's use case.

This could be worth a RFC on Discourse to see if there is wider support or just apathy?

**Comment by MaskRay** [comment]
This PR will address a Linux kernel need.
https://lore.kernel.org/all/CAFP8O3JkgQsH-4Lmr2W_teuvLjOCPi1htr9r3CO1O0yLyw=Azg@mail.gmail.com/

The code already assembles with `clang -S -fno-integrated-as` and `gcc -c`,
and this patch is to make `clang -c` work by removeing an unnecessary restriction in MCObjectStreamer.

I plan on making separate, more nuanced changes to MCAsmStreamer in the future,
(https://github.com/llvm/llvm-project/issues/62520#issuecomment-2096643143),
but I believe it is not worth holding back the MCObjectStreamer improvement.

Do you think this description is clear? I can create a Discourse post, but given the specific nature and subtlety of integrated assemblers, there might be limited general interest.

BTW: `clang -c -save-temps` using an `.s` immediate file and MCAsmStreamer 
inherently has some differences with `clang -c` using MCObjectStreamer.
For example, I've fixed a debug info issue https://github.com/llvm/llvm-project/pull/75022
and some clangDriver stuff I forget now.

**Comment by smithp35** [comment]
Thanks for the additional context. My main concern is that we're undoing the consensus of https://reviews.llvm.org/D45164 which if I've understood the comments properly was "There is a reasonable expectation that compiled (not assembled) code should be identical, or at least as close to the assembly output.

I'm not hugely concerned about that personally as I don't think there are any written guarantees and I come from a background of a toolchain that didn't come close to that (assembler output was disassembled from object file), however there were some strong opinions on the original change.

Do we have any strong opinions from the other reviewers?

If there is a RFC I suggest that it would be entitled something like "[RFC] Clang assembly/object equivalence for files with inline assembly". If it is worded in such a way that this is needed for the kernel and we want to check for community input then if there is no response then we can go ahead.

**Comment by MaskRay** [comment]
> Thanks for the additional context. My main concern is that we're undoing the consensus of [reviews.llvm.org/D45164](https://reviews.llvm.org/D45164) which if I've understood the comments properly was "There is a reasonable expectation that compiled (not assembled) code should be identical, or at least as close to the assembly output.
> 
> I'm not hugely concerned about that personally as I don't think there are any written guarantees and I come from a background of a toolchain that didn't come close to that (assembler output was disassembled from object file), however there were some strong opinions on the original change.
> 
> Do we have any strong opinions from the other reviewers?
> 
> If there is a RFC I suggest that it would be entitled something like "[RFC] Clang assembly/object equivalence for files with inline assembly". If it is worded in such a way that this is needed for the kernel and we want to check for community input then if there is no response then we can go ahead.

Thanks for the suggestion. I created https://discourse.llvm.org/t/rfc-clang-assembly-object-equivalence-for-files-with-inline-assembly/78841

**Comment by MaskRay** [comment]
> > Thanks for the additional context. My main concern is that we're undoing the consensus of [reviews.llvm.org/D45164](https://reviews.llvm.org/D45164) which if I've understood the comments properly was "There is a reasonable expectation that compiled (not assembled) code should be identical, or at least as close to the assembly output.
> > I'm not hugely concerned about that personally as I don't think there are any written guarantees and I come from a background of a toolchain that didn't come close to that (assembler output was disassembled from object file), however there were some strong opinions on the original change.
> > Do we have any strong opinions from the other reviewers?
> > If there is a RFC I suggest that it would be entitled something like "[RFC] Clang assembly/object equivalence for files with inline assembly". If it is worded in such a way that this is needed for the kernel and we want to check for community input then if there is no response then we can go ahead.
> 
> Thanks for the suggestion. I created [discourse.llvm.org/t/rfc-clang-assembly-object-equivalence-for-files-with-inline-assembly/78841](https://discourse.llvm.org/t/rfc-clang-assembly-object-equivalence-for-files-with-inline-assembly/78841)

So far there has only been one reply from @efriedma-quic . Shall we go ahead?

> I care less about error messages than outright miscompiles.

We don't have miscompiles, just the difference in whether a `.if` construct can be assembled.

**Review by smithp35 — APPROVED** [review]
I think it is reasonable to proceed given the RFC and the response.

**Comment by kparzysz** [comment]
It's still used:
```
/work/kparzysz/git/llvm.org/mlir/lib/Target/LLVM/ROCDL/Target.cpp: In member function ‘std::optional<llvm::SmallVector<char, 0> > mlir::ROCDL::SerializeGPUModuleBase::assembleIsa(llvm::StringRef)’:
/work/kparzysz/git/llvm.org/mlir/lib/Target/LLVM/ROCDL/Target.cpp:302:15: error:
 ‘class llvm::MCStreamer’ has no member named ‘setUseAssemblerInfoForParsing’
  302 |   mcStreamer->setUseAssemblerInfoForParsing(true);
      |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by arsenm** [comment]
> It's still used:
> 
> ```
> /work/kparzysz/git/llvm.org/mlir/lib/Target/LLVM/ROCDL/Target.cpp: In member function ‘std::optional<llvm::SmallVector<char, 0> > mlir::ROCDL::SerializeGPUModuleBase::assembleIsa(llvm::StringRef)’:
> /work/kparzysz/git/llvm.org/mlir/lib/Target/LLVM/ROCDL/Target.cpp:302:15: error:
>  ‘class llvm::MCStreamer’ has no member named ‘setUseAssemblerInfoForParsing’
>   302 |   mcStreamer->setUseAssemblerInfoForParsing(true);
>       |               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> ```

But why? I don't know what business MLIR could possibly have touching this, for AMDGPU of all things

**Comment by kparzysz** [comment]
> But why? I don't know what business MLIR could possibly have touching this, for AMDGPU of all things

I don't know why, but my build is failing now.

**Comment by kparzysz** [comment]
Problem solved in 29c2475f215110d9e6b3955d5eb2832b3f719c2f.

**Comment by MaskRay** [comment]
Removing `getUseAssemblerInfoForParsing` would make MCDwarfFrameEmitter::Emit (for .eh_frame FDE) slow (~4% compile time regression for sqlite3.c amalgamation) due to expensive `AttemptToFoldSymbolOffsetDifference`. For now, make `UseAssemblerInfoForParsing` false in MCDwarfFrameEmitter::Emit.

**Comment by nikic** [comment]
@MaskRay It looks like the new version still causes large compile-time regressions for sqlite3 debug builds: http://llvm-compile-time-tracker.com/compare.php?from=7529fe2e92e79eef22a528a7168e4dd777d6e9bd&to=9500a5d02e23f9b43294e5f662ac099f8989c0e4&stat=instructions:u It's smaller than before (2% instead of 4%) but still there.

**Comment by MaskRay** [comment]
> @MaskRay It looks like the new version still causes large compile-time regressions for sqlite3 debug builds: http://llvm-compile-time-tracker.com/compare.php?from=7529fe2e92e79eef22a528a7168e4dd777d6e9bd&to=9500a5d02e23f9b43294e5f662ac099f8989c0e4&stat=instructions:u It's smaller than before (2% instead of 4%) but still there.

Thanks for the report. 245491a9f384e4c53421196533c2a2b693efaf8d should fix the regression.

---

Related to the poor performance of MCAssembler based constant folding
(see `bool MCExpr::evaluateAsAbsolute(int64_t &Res, const MCAssembler *Asm) const` and
`AttemptToFoldSymbolOffsetDifference`),
commit 9500a5d02e23f9b43294e5f662ac099f8989c0e4 caused -O0 -g compile time regression.

9500a5d02e23f9b43294e5f662ac099f8989c0e4 special cased .eh_frame FDE emitting. We need a special case for .debug_* emitting as well to mitigate the rest regression.

---

The MCAssembler based constant folding strategy should be improved to remove the two special cases.

**Comment by gulfemsavrun** [comment]
We started seeing a build time regression in our Clang toolchain builders on Mac, and I bisected to this commit:

1) Build step took 1.7 hours in the last build before
https://luci-milo.appspot.com/ui/p/fuchsia/builders/prod/clang-mac-x64/b8747439072851399889/overview

2) Build step took 2.5 hours in the first build after
https://luci-milo.appspot.com/ui/p/fuchsia/builders/prod/clang-mac-x64/b8747425464531858929/overview

**Comment by MaskRay** [comment]
> We started seeing a build time regression in our Clang toolchain builders on Mac, and I bisected to this commit:
> 
> 1. Build step took 1.7 hours in the last build before (clang -> build)
>    [luci-milo.appspot.com/ui/p/fuchsia/builders/prod/clang-mac-x64/b8747439072851399889/overview](https://luci-milo.appspot.com/ui/p/fuchsia/builders/prod/clang-mac-x64/b8747439072851399889/overview)
> 2. Build step took 2.5 hours in the first build after (clang -> build)
>    [luci-milo.appspot.com/ui/p/fuchsia/builders/prod/clang-mac-x64/b8747425464531858929/overview](https://luci-milo.appspot.com/ui/p/fuchsia/builders/prod/clang-mac-x64/b8747425464531858929/overview)

@gulfemsavrun  
Commit 245491a9f384e4c53421196533c2a2b693efaf8d (`[MC] Disable MCAssembler based constant folding for DwarfDebug`; independent of this patch) should have fixed the compile time regression. Might be worth testing the commit before and at 245491a9f384e4c53421196533c2a2b693efaf8d to see the time decrease.

**Comment by gulfemsavrun** [comment]
> @gulfemsavrun Commit [245491a](https://github.com/llvm/llvm-project/commit/245491a9f384e4c53421196533c2a2b693efaf8d) (`[MC] Disable MCAssembler based constant folding for DwarfDebug`; independent of this patch) should have fixed the compile time regression. Might be worth testing the commit before and at [245491a](https://github.com/llvm/llvm-project/commit/245491a9f384e4c53421196533c2a2b693efaf8d) to see the time decrease.
@MaskRay I already checked with that patch, and we still have the same issue. We see this issue in llvm ToT. For example, this is a run from today:
https://luci-milo.appspot.com/ui/p/fuchsia/builders/prod/clang-mac-x64/b8746512510687347537/overview

**Comment by gulfemsavrun** [comment]
> > > @gulfemsavrun Commit [245491a](https://github.com/llvm/llvm-project/commit/245491a9f384e4c53421196533c2a2b693efaf8d) (`[MC] Disable MCAssembler based constant folding for DwarfDebug`; independent of this patch) should have fixed the compile time regression. Might be worth testing the commit before and at [245491a](https://github.com/llvm/llvm-project/commit/245491a9f384e4c53421196533c2a2b693efaf8d) to see the time decrease.
> > 
> > 
> > @MaskRay I already checked with that patch, and we still have the same issue. We see this issue in llvm ToT. For example, this is a run from today: [luci-milo.appspot.com/ui/p/fuchsia/builders/prod/clang-mac-x64/b8746512510687347537/overview](https://luci-milo.appspot.com/ui/p/fuchsia/builders/prod/clang-mac-x64/b8746512510687347537/overview)
> 
> This change exposed a latent performance issue (primarily due to -O1 or above + -g) in https://reviews.llvm.org/D153096 , which should be properly fixed by [b06e736](https://github.com/llvm/llvm-project/commit/b06e736982a3568fe2bcea8688550f9e393b7450) (just landed). Can you verify?
> 
> [245491a](https://github.com/llvm/llvm-project/commit/245491a9f384e4c53421196533c2a2b693efaf8d) was a workaround, but I believe it effectively addressed the performance issue, and I am unable to detect compile time regression. I am curious if you can find a source file that demonstrates a slowdown with [245491a](https://github.com/llvm/llvm-project/commit/245491a9f384e4c53421196533c2a2b693efaf8d) applied. The `AttemptToFoldSymbolOffsetDifference` function is likely related.
> 
> (The aforementioned commits modify different files and are independent.)

We build with Full LTO, and linking takes much longer with this patch. For example,  building `bin/lldb-server` takes almost 2.5x longer time now.
1) Before
```
bin/lldb-server: 9 min 18 seconds
```
2) After
```
bin/lldb-server: 22 min 24 seconds
```

Is there a specific source file or binary that might be interesting to look at so I can provide more information?

**Pull request merged**
