### PR TITLE
[ASan][test] Enable ASan tests on SPARC

### PR DESCRIPTION
**Pull request by rorth**
With PR #107223 and PR #107403, ASan testing can be enabled on SPARC.  This patch does so, 32-bit only on both Solaris and Linux.  There is no 64-bit support even in GCC.

Apart from the obvious CMake changes, this patch includes a couple of testcase adjustments necessary for SPARC:
- In `asan_oob_test.cpp`, the `OOB_int` subtest needs to be disabled: it performs unaligned accesses that cannot work on a strict-alignment target like SPARC.
- `asan_test.cpp` needs to disable subtests that depend on support for `__builtin_setjmp` and `__builtin_longjmp`.
- `zero_page_pc.cpp` reports `0x5` as the faulting address on access to `0x4`.  I don't really know why, but it's consistent between Solaris and Linux.

Tested on `sparcv9-sun-solaris2.11` and `sparc64-unknown-linux-gnu`.

### CODE REVIEW

**Comment by rorth** [comment]
TBH, I'm wary of the suggested `clang-format` changes, at least some of which are inconsistent with the rest of files.

**Review by vitalybuka — APPROVED** [review]

**Comment by rorth** [comment]
@ebotcazou, any insight on the stage of 64-bit SPARC ASan support in `clang` and `gcc`?

**Comment by ebotcazou** [comment]
I think that my last try was https://gcc.gnu.org/legacy-ml/gcc-patches/2019-03/msg00478.html

**Comment by rorth** [comment]
This patch is ready to go once PR #107223 is in.

**Comment by brad0** [comment]
@rorth Ping.

**Pull request merged**
