### PR TITLE
[AArch64][TargetParser] Add mcpu alias for Microsoft Azure Cobalt 100.

### PR DESCRIPTION
**Pull request by labrinea**
With a690e86 we added -mcpu/mtune=native support to handle the Microsoft Azure Cobalt 100 CPU as a Neoverse N2. This patch adds a CPU alias in TargetParser to maintain compatibility with GCC.

### CODE REVIEW

**Comment by davemgreen** [comment]
It looks like this needs to update testAArch64CPUArchList too. Otherwise it LGTM

**Review by DavidSpickett — APPROVED** [review]
```
/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-r6v66-1/llvm-project/github-pull-requests/llvm/unittests/TargetParser/TargetParserTest.cpp:1662: Failure
Expected equality of these values:
  List.size()
    Which is: 68
  NumAArch64CPUArchs
    Which is: 67
```
Needs fixing, but otherwise LGTM.

**Review by davemgreen — APPROVED** [review]
Thanks. LGTM too.

**Pull request merged**
