### PR TITLE
[profile] Fix bounds checks in profile merging

### PR DESCRIPTION
**Pull request by nikic**
These bounds checks work on the result of the pointer addition -- but the pointer addition already asserts that no overflow may occur, so the checks are optimized away after #118472. Avoid this by performing the addition in a way that permits overflow.

### CODE REVIEW

**Review by chapuni — APPROVED** [review]
Looks good. Please wait for another opinion.

For bound-free arithmetic, shall we cast to uintptr_t, ultimately?

**Comment by nikic** [comment]
> For bound-free arithmetic, shall we cast to uintptr_t, ultimately?

I'm not sure I get what you mean here -- are you suggesting we should do everything in uintptr rather than const char and then only cast to a pointer type when doing accesses?

**Comment by vitalybuka** [comment]
I will apply both patches and validate in about 1h

**Review by vitalybuka — APPROVED** [review]
The patch fixes the crash caused by #118472

**Comment by ellishg** [comment]
> > For bound-free arithmetic, shall we cast to uintptr_t, ultimately?
> 
> I'm not sure I get what you mean here -- are you suggesting we should do everything in uintptr rather than const char and then only cast to a pointer type when doing accesses?

I agree with @chapuni, it seems cleaner to make the type of `SrcBitmapStart` (and similar variables) `uintptr_t` in the first place.

**Comment by nikic** [comment]
I've created a followup to switch most of the arithmetic to uintptr_t here: https://github.com/llvm/llvm-project/pull/118944

**Pull request merged**
