### PR TITLE
[ELF] Make shouldAddProvideSym return values consistent when demoted to Undefined

### PR DESCRIPTION
**Pull request by MaskRay**
Case: `PROVIDE(f1 = bar);` when both `f1` and `bar` are in separate
sections that would be discarded by GC.

Due to `demoteDefined`, `shouldAddProvideSym(f1)` may initially return
false (when Defined) and then return true (been demoted to Undefined).

```
addScriptReferencedSymbolsToSymTable
  shouldAddProvideSym(f1): false
  // the RHS (bar) is not added to `referencedSymbols` and may be GCed
declareSymbols
  shouldAddProvideSym(f1): false
markLive
demoteSymbolsAndComputeIsPreemptible
  // demoted f1 to Undefined
processSymbolAssignments
  addSymbol
    shouldAddProvideSym(f1): true
```

The inconsistency can cause `cmd->expression()` in `addSymbol` to be
evaluated, leading to `symbol not found: bar` errors (since `bar` in the
RHS is not in `referencedSymbols` and is GCed) (#111478).

Fix this by adding a `sym->isUsedInRegularObj` condition, making
`shouldAddProvideSym(f1)` values consistent. In addition, we need a
`sym->exportDynamic` condition to keep provide-shared.s working.

Fixes: ebb326a51fec37b5a47e5702e8ea157cd4f835cd

### CODE REVIEW

**Review by smithp35 — APPROVED** [review]
LGTM. One small suggestion for the comment.

**Comment by MaskRay** [comment]
Thanks for the review and comment suggestion. Adopted

**Comment by aeubanks** [comment]
hi, I've bisected an lld crash to this PR, reproducer tar is in https://crbug.com/373447237 if you could take a look

**Comment by MaskRay** [comment]
> hi, I've bisected an lld crash to this PR, reproducer tar is in https://crbug.com/373447237 if you could take a look

This is a -shared link that uses `PROVIDE(linker_script_start_of_text = ...)` with references only from LLVM bitcode files.
The current `PROVIDE` mechanism cannot easily support both #111478 and https://crbug.com/373447237 .

As a workaround, you can remove `PROVIDE` or add `-u`

```
% ~/Stable/bin/ld.lld @response.txt -y linker_script_start_of_text -u linker_script_start_of_text
<internal>: reference to linker_script_start_of_text
repos/chromium/src/out/clang/obj/base/libbase.a(base/anchor_functions.o): reference to linker_script_start_of_text
<internal>: definition of linker_script_start_of_text
repos/chromium/src/out/clang/obj/base/libfast_float_fast_int_test__library.so.lto.libbase.a(anchor_functions.o at 1277214).o: reference to linker_script_start_of_text
repos/chromium/src/base/android/library_loader/anchor_functions.lds:6: definition of linker_script_start_of_text
```

**Comment by aeubanks** [comment]
#112386 fixes the crash, so we don't need a workaround?

**Comment by MaskRay** [comment]
> #112386 fixes the crash, so we don't need a workaround?

Not needed:)

**Pull request merged**
