### PR TITLE
[OpenMP] Fix task state and taskteams for serial teams

### LINKED ISSUE #50602: Assertion triggered when a serialized parallel region is after a detached task
|  |  |
| --- | --- |
| Bugzilla Link | [51258](https://llvm.org/bz51258) |
| Version | unspecified |
| OS | All |
| Blocks | llvm/llvm-project#49160, llvm/llvm-project#53081  |

## Extended Description 
The reproducer is every simple:
```
#include <omp.h>

int main(int argc, char *argv[]) {
#pragma omp parallel
  {
    omp_event_handle_t event;
    int a = 0;

#pragma omp task shared(a) detach(event)
    { a = 1; }

#pragma omp parallel
    { a = 2; }

#pragma omp taskwait
  }
  return 0;
}
```
Please ignore that the detached task is never fulfilled, because it is not the point. If it is executed with env `OMP_NUM_THREADS=1`, then an assertion is triggered.
```
Assertion failure at kmp_runtime.cpp(1114): serial_team->t.t_task_team[this_thr->th.th_task_state] == __null.
OMP: Error #&#8203;13: Assertion failure at kmp_runtime.cpp(1114).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see https://bugs.llvm.org/.
```
Basically, `__kmp_serialized_parallel` assumes that the corresponding task team should be nullptr. However, if a detached task is encountered before, the task team will be setup in `__kmp_task_alloc`.

### LINKED ISSUE #69368: Assertion fail at kmp_runtime.cpp for omp teams distribute parallel for if
The following code fails on an assert
```
int main() {
  int a[2];
  int attempt = 0;

#pragma omp parallel for
  for (int i = 0; i < 2; i++) {
    a[i] = 2;
  }

#pragma omp teams distribute parallel for if(attempt >= 2) 
  for (int i = 0; i < 2; i++) {
    a[i] = 1;
  }
  return 0;
}
```
As
```
Assertion failure at kmp_runtime.cpp(1149): this_thr->th.th_task_team == this_thr->th.th_team->t.t_task_team[this_thr->th.th_task_state].
OMP: Error #13: Assertion failure at kmp_runtime.cpp(1149).
OMP: Hint Please submit a bug report with this message, compile and run commands used, and machine configuration info including native compiler and operating system versions. Faster response will be obtained by including all program sources. For information on submitting this issue, please see https://github.com/llvm/llvm-project/issues/.
Aborted
```
When LLVM is built as:
```
  cmake -G Ninja -S ${PROJROOT}/llvm-project/llvm -B ../ \
    -DLLVM_ENABLE_PROJECTS=clang;compiler-rt;clang-tools-extra;lld;openmp \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_BUILD_TYPE=RelWithDebInfo
```
but not if it is built as:
```
  cmake -G Ninja -S ${PROJROOT}/llvm-project/llvm -B ../ \
    -DLLVM_ENABLE_PROJECTS=clang;compiler-rt;clang-tools-extra;lld;openmp \
    -DLLVM_ENABLE_ASSERTIONS=ON \
    -DCMAKE_C_COMPILER=clang \
    -DCMAKE_CXX_COMPILER=clang++ \
    -DCMAKE_BUILD_TYPE=Release 
```

### LINKED ISSUE #69733: [OpenMP] th_task_team inconsistency caught by a debug assert.
```cpp
#include <omp.h>
int main()
{
  #pragma omp parallel num_threads(1)
  {
    #pragma omp parallel num_threads(1)
    {
      omp_event_handle_t ev;
      #pragma omp task detach(ev)
      { }
      omp_fulfill_event(ev);
    }
  }
}
```
`clang -fopenmp t1.c -o t1  && ./t1`
```
Assertion failure at kmp_runtime.cpp(2459): master_th->th.th_task_team == team->t.t_task_team[master_th->th.th_task_state].
OMP: Error #13: Assertion failure at kmp_runtime.cpp(2459).
```

I've hit this assert when compiling with a debug build. In upstream

### LINKED ISSUE #79416: [OpenMP RT] Assert hit after second teams with different parallel size
```c
// clang -fopenmp t1.c -o t1 && ./t1
#include <stdio.h>
void run(int teams, int th) {
  #pragma omp teams num_teams(teams)
  #pragma omp parallel num_threads(th)
  #pragma omp task
  {}

}
int main() {
  fprintf(stderr, "run(1, 2)\n");
  run(1, 2);
  fprintf(stderr, "run(1, 3)\n");
  run(1, 3);
}
```
With the runtime in debug I get `Assertion failure at kmp_tasking.cpp(3664): nthreads == this_thr->th.th_team->t.t_nproc.`. I guess there is something messing up once you change the parallel size in the second team.

### PR DESCRIPTION
**Pull request by jpeyton52**
* Serial teams now use a stack (similar to dispatch buffers)
* Serial teams always use `t_task_team[0]` as the task team and the second pointer is a next pointer for the stack

`t_task_team[1]` is interpreted as a stack of task teams where each level is a nested level

```
 inner serial team                   outer serial team
[ t_task_team[0] ] -> (task_team)    [ t_task_team[0] ] -> (task_team)
[ next           ] ----------------> [ next           ] -> ...
```

* Remove the task state memo stack from thread structure.
* Instead of a thread-private stack, use team structure to store th_task_state of the primary thread. When coming out of a parallel, restore the primary thread's task state. The new field in the team structure doesn't cause sizeof(team) to change and is in the cache line which is only read/written by the primary thread.

Fixes: #50602
Fixes: #69368
Fixes: #69733
Fixes: #79416

### CODE REVIEW

**Review by jhuber6 — APPROVED** [review]
Looks fine from my perspective, but I'm not the foremost expert on `libomp.so` so take that with a grain of salt.

**Review by shiltian — APPROVED** [review]
LGTM. Finally we have this issue sorted out (hopefully)!

**Comment by shiltian** [comment]
@jpeyton52 I think this can also fix https://github.com/llvm/llvm-project/issues/81488. If yes, you can also close it once this is merged.

**Comment by jpeyton52** [comment]
Centralized the task team initialization code in its own static inline function. 
Removed some `nth == 1` debug assert assumptions because with the `#pragma omp teams` construct, the reserved team which is eventually used in a nested `#pragma omp parallel` region can only contain one thread.
Re-wrote some tests to also try hidden helpers as well as detached tasks. 
This PR should be merged on top of #87309

**Pull request merged**
