### PR TITLE
[CodeGen] Apply 'nofree' to 'this' pointer argument.

### PR DESCRIPTION
**Pull request by zengdage**
As I known, 'this' pointer argument can't be changed in c++ instance method, and it always pointer to the current object itself, so maybe need to add 'readonly' attribute to it.

### CODE REVIEW

**Review by ChuanqiXu9 — APPROVED** [review]
Sounds good to me and I add another few reviewers to take another look.

**Review by nikic — CHANGES_REQUESTED** [review]
I'm very confused. `readonly` means that the memory behind `this` cannot be changed, not that the pointer cannot be changed.

**Comment by zengdage** [comment]
Sorry, I misunderstand the 'readonly' meaning. So this pr is wrong.

**Comment by nikic** [comment]
> > I'm very confused. `readonly` means that the memory behind `this` cannot be changed, not that the pointer cannot be changed.
> 
> Out of curiosity, it looks not same in https://llvm.org/docs/LangRef.html:
> 
> > This attribute indicates that the function does not write through this pointer argument, even though it may write to the memory that the pointer points to.
> > If a function writes to a readonly pointer argument, the behavior is undefined.
> 
> My understanding for ` it may write to the memory that the pointer points to.` is what you said. Or do we need to update the document?

The distinction in LangRef is about a write through the pointer vs a write through an alias of the pointer to the same memory. Only the former is forbidden.

**Comment by zengdage** [comment]
@nikic @ChuanqiXu9 I am sorry to bother you again. Do you think the attribute 'nofree' should be added to 'this' pointer argument  in c++ instance method ?  I think the 'this' pointer pointed to current object and it's life time is guaranteed to be longer than the instance method's lifetime.  If can, we can add `hasNoFreeAttr` check for 'Argument' case in `Value::canBeFreed`.

**Comment by zengdage** [comment]
> No, this is not legal either. Doing something like `delete this` inside a method is not (generally) UB

I got it, thank you.

**Pull request closed without merging**
