### PR TITLE
[TSAN] add support for riscv64

### PR DESCRIPTION
**Pull request by hiraditya**
Implements for sv39 and sv48 VMA layout.

Userspace only has access to the bottom half of vma range. The top half is used by kernel. There is no dedicated vsyscall or heap segment.
PIE program is allocated to start at TASK_SIZE/3*2. Maximum ASLR is ARCH_MMAP_RND_BITS_MAX+PAGE_SHIFT=24+12=36 Loader, vdso and other libraries are allocated below stack from the top.

Also change RestoreAddr to use 4 bits to accommodate MappingRiscv64_48

Reviewed by: MaskRay, dvyukov, asb, StephenFan, luismarques, jrtc27, hiraditya, vitalybuka

Differential Revision: https://reviews.llvm.org/D145214

D145214 was reverted because one file was missing in the latest commit. Luckily the file was there in the previous commit, probably the author missed uploading that file with latest commit.

### CODE REVIEW

**Review by zeroomega — APPROVED** [review]
LGTM.
Please solve the code-formatting issues complaint by the bots.

**Comment by MaskRay** [comment]
The review context is on https://reviews.llvm.org/D145214 . Moving it here just causes more confusion. 

@alexfanqi is the author of the patch and they can drive a reland.

**Review by MaskRay — CHANGES_REQUESTED** [review]
https://reviews.llvm.org/D145214#4653647

**Comment by hiraditya** [comment]
> The review context is on https://reviews.llvm.org/D145214 . Moving it here just causes more confusion.
> 
> @alexfanqi is the author of the patch and they can drive a reland.

Can you elaborate what is confusing? The patch was already reviewed and accepted. I'm waiting on the author to reply back but I posted here for it to be tested. @alexfanqi asked me to land the patch last time (https://reviews.llvm.org/D145214#4650928)

**Comment by alexfanqi** [comment]
Sorry. It took some time to reply. Since newer linux kernel supports sv57 and sv48, I tested this again with latest qemu and 6.6 kernel, by passing `-cpu rv64,sv48=on` to qemu.

I missed a little piece here for sv48,

Also to note, if we want to support sv57, we could directly copy the aarch64_48 scheme and append 8 bits to its addresses. That gives the maximum application space, a horrific ~2^24 tera byte.

I asked @hiraditya to land for me. Thanks for the help to drive the reland.

**Review by alexfanqi — CHANGES_REQUESTED** [review]
I missed a little piece for sv48 here
```
--- a/compiler-rt/lib/sanitizer_common/sanitizer_platform.h
+++ b/compiler-rt/lib/sanitizer_common/sanitizer_platform.h
@@ -303,7 +303,7 @@
 #    define SANITIZER_MMAP_RANGE_SIZE FIRST_32_SECOND_64(1ULL << 32, 1ULL << 40)
 #  endif
 #elif SANITIZER_RISCV64
-#  define SANITIZER_MMAP_RANGE_SIZE FIRST_32_SECOND_64(1ULL << 32, 1ULL << 38)
+#  define SANITIZER_MMAP_RANGE_SIZE FIRST_32_SECOND_64(1ULL << 32, 1ULL << 47)
 #elif defined(__aarch64__)
 #  if SANITIZER_APPLE
 #    if SANITIZER_OSX || SANITIZER_IOSSIM
```

**Review by alexfanqi — APPROVED** [review]

**Comment by MaskRay** [comment]
> > The review context is on [reviews.llvm.org/D145214](https://reviews.llvm.org/D145214) . Moving it here just causes more confusion.
> > @alexfanqi is the author of the patch and they can drive a reland.
> 
> Can you elaborate what is confusing? The patch was already reviewed and accepted. I'm waiting on the author to reply back but I posted here for it to be tested. @alexfanqi asked me to land the patch last time ([reviews.llvm.org/D145214#4650928](https://reviews.llvm.org/D145214#4650928))

The patch is just a reland of https://reviews.llvm.org/D145214 . AIUI this pull request does not add anything on top of that, but the main author of commit 46cb8d9a325233ac11ed5e90367c43774294d87e is now you with a Co-authored-by: tag attributing Alex Fan. That's what you got when you posted the pull request and merged the pull request via the web UI, instead of letting Alex Fan post the patch here.

**Comment by hiraditya** [comment]
Ah that's unfortunate.; sorry about that. In my local copy of git log (before merging)

```
commit 5b85613483861b3734edf9c94be390f2b3b0dd2a (HEAD -> riscv_tsan)
Author: Alex Fan <alex.fan.q@gmail.com>
Date:   Fri Oct 6 12:32:38 2023 -0700
```

so i thought github would respect that.

**Pull request merged**
