### PR TITLE
Reland "[NVPTX] Add folding for cvt.rn.bf16x2.f32"

### PR DESCRIPTION
**Pull request by AlexMaclean**
Reland https://github.com/llvm/llvm-project/pull/116109.

Fixes issue where operands were flipped. 

Per the PTX spec, a mov instruction packs the first operand as low, and the second operand as high:
> ```
> // pack two 16-bit elements into .b32
> d = a.x | (a.y << 16)
> ```
On the other hand cvt.rn.f16x2.f32 instructions take high, than low operands:
> For .f16x2 and .bf16x2 instruction type, two inputs a and b of .f32 type are converted into .f16 or .bf16 type and the converted values are packed in the destination register d, such that the value converted from input a is stored in the upper half of d and the value converted from input b is stored in the lower half of d

### CODE REVIEW

**Review by Artem-B — APPROVED** [review]
Looks like flipped args between LLVM and PTX is a common failure pattern.
We should probably switch argument names from `a/b` to `hi/lo` where bit order matters or `e0/e1` for vectors to make it a bit easier catching such issues early next time. It's not fool-proof but would at least give a hint where particular argument is supposed to be placed.

**Review by justinfargnoli — APPROVED** [review]

**Comment by AlexMaclean** [comment]
> Looks like flipped args between LLVM and PTX is a common failure pattern. We should probably switch argument names from `a/b` to `hi/lo` where bit order matters or `e0/e1` for vectors to make it a bit easier catching such issues early next time. It's not fool-proof but would at least give a hint where particular argument is supposed to be placed.

Yea, inconsistent argument ordering in PTX does make things tricky. I've switched the patterns in this MR to use `lo` and `hi` as you suggested.

**Comment by Artem-B** [comment]
> Yea, inconsistent argument ordering in PTX does make things tricky. I've switched the patterns in this MR to use `lo` and `hi` as you suggested.

Tests could use the same treatment -- without looking up the docs for nvvm intrinsics it's hard to tell where a/b or f1/f2 are supposed to end up in the instruction arguments. While now I can be confident that the tablegen pattern is correct, I still would have hard time telling if the test patterns check what we want them to check.

**Review by Artem-B — APPROVED** [review]

**Comment by AlexMaclean** [comment]
@tomnatan30 would it be possible to confirm on your end that this latest iteration no longer causes issues?

**Pull request merged**
