### PR TITLE
[tsan] Refine fstat{,64} interceptors on GLIBC

### PR DESCRIPTION
**Pull request by wangleiat**
Without this patch, `DEADLYSIGNAL` will occur on some architectures.
```
ThreadSanitizer:DEADLYSIGNAL
==752233==ERROR: ThreadSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7ffffbdfe080 sp 0x7ffffbdfe010 T752233)
==752233==Hint: pc points to the zero page.
==752233==The signal is caused by a READ memory access.
==752233==Hint: address points to the zero page.
```
The reason is that ports introduced in Glibc 2.33 and later will not have the opportunity to implement the `__fxstat{,64}` interfaces.
For example:
- LoongArch - Glibc version 2.36
```
GLIBC_2.36 fstat F
GLIBC_2.36 fstat64 F
```

- RISC-V variants (RISCV_ABI_XLEN == 32 && (RISCV_ABI_FLEN == 64 || RISCV_ABI_FLEN == 0) - Glibc version 2.33
```
GLIBC_2.33 fstat F
GLIBC_2.33 fstat64 F
```

### CODE REVIEW

**Comment by SixWeining** [comment]
Add @lixing-star who reported this issue to us.

**Comment by MaskRay** [comment]
> Without this patch, use-of-uninitialized value will occur on those architectures, which are supported by Glibc since version 2.33. Because they have no opportunity to implement the __fxstat{,64} interfaces.

"those architectures" are not clear. I assume it includes LoongArch (base version 2.36) and some RISC-V variants (`sysdeps/unix/sysv/linux/riscv/shlib-versions`)

This description needs rewording. I think there may be a difference if a glibc port has a base version >= 2.33. https://maskray.me/blog/2022-05-29-glibc#buildabi-versions.h

**Comment by vitalybuka** [comment]
use-of-uninitialized is MSAN, but the patch is TSAN only?

**Comment by wangleiat** [comment]
> > Without this patch, use-of-uninitialized value will occur on those architectures, which are supported by Glibc since version 2.33. Because they have no opportunity to implement the __fxstat{,64} interfaces.
> 
> "those architectures" are not clear. I assume they include LoongArch (base version 2.36) and some RISC-V variants (`sysdeps/unix/sysv/linux/riscv/shlib-versions`)
> 
> This description needs rewording. I think there may be a difference if a glibc port has a base version >= 2.33. https://maskray.me/blog/2022-05-29-glibc#buildabi-versions.h
> 
> Can you describe what `f*stat` symbols your glibc port defines?

Thank you very much for your blog; I've learned a lot from it. I've attempted to modify the commit message using my limited English vocabulary.

**Comment by wangleiat** [comment]
> use-of-uninitialized is MSAN, but the patch is TSAN only?

I apologize for my inadequate English description causing inconvenience. My intention was that on systems where __fxstat{,64} is not implemented, interception would result in calling an empty function.

**Comment by wangleiat** [comment]
> Add @lixing-star who reported this issue to us.

Add @abner-chenc  The original issue discoverer.

**Comment by MaskRay** [comment]
I think we should refine the interceptor conditions and use the correct symbols. I am writing a patch to properly fix this.

**Comment by MaskRay** [comment]
The interceptors should now use `__fxstat{,64}` compatibility symbols. Sent #86625 to additionally simplify the code a bit.

**Pull request closed without merging**
