### PR TITLE
Fix error: name 'maybe' is not defined

### PR DESCRIPTION
**Pull request by cpiaseque**

### CODE REVIEW

**Comment by kirillpyasecky** [comment]
ping

**Comment by kirillpyasecky** [comment]
Ping

**Comment by kirillpyasecky** [comment]
@rupprecht

**Comment by kirillpyasecky** [comment]
@keith

**Review by keith — APPROVED** [review]
thanks!

**Comment by keith** [comment]
ah i should have changed the commit message here, in the future it's best to prefix these with `[bazel]` for easier log reading

**Pull request merged**
