### PR TITLE
[MLIR][RISCV] Add VCIX dialect to LLVMIR target conversion

### PR DESCRIPTION
**Pull request by nikolaypanchenko**
The changeset adds new dialect to support VCIX intrinsics of `XSfvcp` extension to allow MLIR users to interact with co-processors that are compatible with that extension.

Source: https://www.sifive.com/document-file/sifive-vector-coprocessor-interface-vcix-software

### CODE REVIEW

**Comment by Dinistro** [comment]
Is there some kind of an RFC that discusses the design of this PR? 
This is a very large PR that will be difficult to review when it includes multiple things. I suggest to consider splitting the PR into one that introduces the dialect, one introducing the vector lowering, and adding target support.

**Comment by joker-eph** [comment]
There is an RFC: https://discourse.llvm.org/t/rfc-vcix-dialect/75498

**Comment by nikolaypanchenko** [comment]
I split the original changeset into 3 pieces as @Dinistro recommended: [1](https://github.com/llvm/llvm-project/pull/74780), [2](https://github.com/llvm/llvm-project/pull/74781) and 3 is this PR itself

**Comment by nikolaypanchenko** [comment]
It has been suggested to avoid introduction of a new dialect for now. Closing that PR

**Pull request closed without merging**
