### PR TITLE
[CLANG][NFC] Modify test cases to suit assigned default sysroot path

### PR DESCRIPTION
**Pull request by Yunzezhu94**
When using cmake with option -DDEFAULT_SYSROOT, a default sysroot path is assigned. 
However, some test cases use a relative path to indicate sysroot path, but the path goes wrong with default sysroot path assigned. 
This patch modified test cases to make them use correct sysroot path.

### CODE REVIEW

**Comment by brad0** [comment]
@MaskRay Wasn't it you that mentioned this?

**Comment by Yunzezhu94** [comment]
Gentle Ping.

**Comment by MaskRay** [comment]
> @MaskRay Wasn't it you that mentioned this?

Yes. I hoped that we could deprecated `DEFAULT_SYSROOT`: https://reviews.llvm.org/D158218 , but the relative `DEFAULT_SYSROOT` does not have a good replacement.

**Comment by Yunzezhu94** [comment]
> > @MaskRay Wasn't it you that mentioned this?
> 
> Yes. I hoped that we could deprecated `DEFAULT_SYSROOT`: https://reviews.llvm.org/D158218 , but the relative `DEFAULT_SYSROOT` does not have a good replacement.

I think since relative DEFAULT_SYSROOT still works, modify these cases is helpful to cross compile developers. And this commit could be delete when DEFAULT_SYSROOT get deprecated.

**Comment by Yunzezhu94** [comment]
Gentle Ping.

**Comment by Yunzezhu94** [comment]
Gentle Ping.

**Pull request closed without merging**
