### PR TITLE
[DWARFLinker][DWARFLinkerParallel][NFC] Refactor DWARFLinker&DWARFLinkerParallel to have a common library.

### PR DESCRIPTION
**Pull request by avl-llvm**
This creates DWARFLinkerBase library which shares code between DWARFLinker and DWARFLinkerParallel. Now AddressesMap, DWARFFile, IndexedValuesMap are shared between DWARFLinker implementations.

### CODE REVIEW

**Comment by felipepiovezan** [comment]
High level questions:

1. Is this change NFC, or is there some important change reviewers need to be mindful?
2. I see some methods are now virtual when they weren't before and some (Strting)switch statements have increased in the number of cases they handle. Have you had a chance to double check neither of those is affecting the performance of the linker?

**Comment by avl-llvm** [comment]
> High level questions:
> 
>     1. Is this change NFC, or is there some important change reviewers need to be mindful?

This is NFC.

> 
>     2. I see some methods are now virtual when they weren't before and some (String)switch statements have increased in the number of cases they handle. Have you had a chance to double check neither of those is affecting the performance of the linker?

I did not check performance as changed things do not look like they can noticeably affect performance. But I will check and show results.

**Comment by avl-llvm** [comment]
>     2. I see some methods are now virtual when they weren't before and some (String)switch statements have increased in the number of cases they handle. Have you had a chance to double check neither of those is affecting the performance of the linker?

I measured performance impact of this patch and it does not introduce any noticeable change. Anyway, I replaced String switch with an integral switch as integral switch should be faster.

**Comment by avl-llvm** [comment]
friendly ping.

**Comment by felipepiovezan** [comment]
> friendly ping.

I think the challenge here is that this change looks like it's just moving files around, but in reality there are behavior differences mixed in the middle. To give you an example, when I look at the diff there are a bunch of APIs change that are pretty difficult to look at and say "this is trivially the same as before":

For example:

```
void emitDwarfDebugRangeListFragment(const CompileUnit &Unit,
                                        const AddressRanges &LinkedRanges,
                                        PatchLocation Patch,
                                        DebugDieValuePool &AddrPool) override;
```

Became

```
  /// Emit debug ranges(.debug_ranges, .debug_rnglists) fragment.
   void emitDwarfDebugRangeListFragment(const CompileUnit &Unit,
                                        const AddressRanges &LinkedRanges,
                                        PatchLocation Patch,
                                        IndexedValuesMap<uint64_t> &AddrPool);
```

Another example:

```
  std::unique_ptr<DwarfStreamer> TheDwarfEmitter;
```

Became:

```
  DwarfStreamer *OutDwarfStreamer = nullptr;
```

Without having to do a lot of back-and-forth between the 1300 lines added and 1500 lines deleted, I'm not sure how to review this type of change.

My suggestion would be to try a more piece-wise approach, otherwise you will probably get a "LGTM" that in reality is more like "I couldn't really check this but let's merge it".

**Comment by avl-llvm** [comment]
> > friendly ping.
> 
> I think the challenge here is that this change looks like it's just moving files around, but in reality there are behavior differences mixed in the middle. To give you an example, when I look at the diff there are a bunch of APIs change that are pretty difficult to look at and say "this is trivially the same as before":
> 
> For example:
> 
> ```
> void emitDwarfDebugRangeListFragment(const CompileUnit &Unit,
>                                         const AddressRanges &LinkedRanges,
>                                         PatchLocation Patch,
>                                         DebugDieValuePool &AddrPool) override;
> ```
> 
> Became
> 
> ```
>   /// Emit debug ranges(.debug_ranges, .debug_rnglists) fragment.
>    void emitDwarfDebugRangeListFragment(const CompileUnit &Unit,
>                                         const AddressRanges &LinkedRanges,
>                                         PatchLocation Patch,
>                                         IndexedValuesMap<uint64_t> &AddrPool);
> ```
> 
> Another example:
> 
> ```
>   std::unique_ptr<DwarfStreamer> TheDwarfEmitter;
> ```
> 
> Became:
> 
> ```
>   DwarfStreamer *OutDwarfStreamer = nullptr;
> ```
> 
> Without having to do a lot of back-and-forth between the 1300 lines added and 1500 lines deleted, I'm not sure how to review this type of change.
> 
> My suggestion would be to try a more piece-wise approach, otherwise you will probably get a "LGTM" that in reality is more like "I couldn't really check this but let's merge it".

Ok, I will split it to smaller changes.

**Comment by avl-llvm** [comment]
This pull request are fully covered by :

https://github.com/llvm/llvm-project/pull/75925
https://github.com/llvm/llvm-project/pull/77437
https://github.com/llvm/llvm-project/pull/77604
https://github.com/llvm/llvm-project/pull/77932

Thus I am closing it.

**Pull request closed without merging**
