### PR TITLE
[CodeGen][NewPM] Use verify-each option in npm tests (NFC).

### PR DESCRIPTION
**Pull request by cdevadas**

### CODE REVIEW

**Comment by cdevadas** [comment]
* **#107373** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/107373?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @cdevadas and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by pravinjagtap — APPROVED** [review]
So we should not be using `-verify-machineinstrs` with NPM ? `-verify-each` verifies both input and output ?

**Review by arsenm — COMMENTED** [review]
I don't think this should just be thrown on any test. I would expect this to be the default in EXPENSIVE_CHECKS builds, and not be required clutter. 

Also, it should be pointless with a single pass run. The default should always be verify final MIR output

**Comment by cdevadas** [comment]
This isn't really important at this point. Closing it.

**Pull request closed without merging**
