### PR TITLE
[RA] Don't split a register generated from another split

### PR DESCRIPTION
**Pull request by weiguozhi**
Split a register generated from another split usually doesn't bring us too much benefit. It may also cause dead loop as pr67188 shows if the heuristic cost always satisfy the split condition. So prevent such splitting.

It fixed pr67188.

### CODE REVIEW

**Comment by danilaml** [comment]
Looks good to me. Maybe add a short comment to explain why we bail out early in this case.

**Comment by weiguozhi** [comment]
> Looks good to me. Maybe add a short comment to explain why we bail out early in this case.

I copied the comment from splitAroundRegion which is for the same purpose.

**Review by danilaml — APPROVED** [review]
LGTM. Not an RA expert, but the sooner we fix the hang the better.

**Review by qcolombet — APPROVED** [review]
Nice catch!
The infinite looping was one of my fear for doing that outside of the regular splitting heuristic.
I should have caught this.

Anyhow thanks for the fix.

**Pull request merged**
