### PR TITLE
[BOLT] Add NamedRegionTimer to inferStaleProfile

### PR DESCRIPTION
**Pull request by shawbyoung**
Add a NamedRegionTimer to measure the time spent in inferStaleProfile.

### CODE REVIEW

**Review by aaupov — CHANGES_REQUESTED** [review]

**Review by aaupov — APPROVED** [review]
Looks good now. Thanks!

**Comment by nico** [comment]
This is a dependency cycle: lib/Rewrite depends on lib/Profile, but now Profile also depends on the cl::opt defined in Rewrite.

If you want to do something like this PR, you have to move the definition of this cl::opt to Profile.

**Comment by nico** [comment]
ProfileTests probably fails to link after this change, and the right fix is _not_ to make it depend on Rewrite, but to fix the layering violation. If it takes a while, consider reverting while you work on the fix.

**Comment by aaupov** [comment]
> This is a dependency cycle: lib/Rewrite depends on lib/Profile, but now Profile also depends on the cl::opt defined in Rewrite.
> 
> If you want to do something like this PR, you have to move the definition of this cl::opt to Profile.

Thanks for spotting. Should've tested the shared build as well. Let me revert and we'll reland.

**Pull request merged**
