### PR TITLE
Populate the llvm::GlobalVariable ELF section, with the attribute from the ObjectAttrs 

### PR DESCRIPTION
**Pull request by Renaud-K**

### CODE REVIEW

**Comment by Renaud-K** [comment]
Populating it would only happen downstream, so I am not sure how we would write a test for it.

**Comment by clementval** [comment]
> Populating it would only happen downstream, so I am not sure how we would write a test for it.

Maybe you can add smth here `mlir/test/Target/LLVMIR/gpu.mlir` with  a pre-populated section.

**Comment by clementval** [comment]
> I see. Nice.

Thanks Renaud! This look good to me.

**Review by krzysz00 — APPROVED** [review]
Approved, thanks!

**Review by clementval — APPROVED** [review]

**Pull request merged**
