### PR TITLE
Reland the reland "[PGO][GlobalValue][LTO]In GlobalValues::getGlobalIdentifier, use semicolon as delimiter for local-linkage varibles. "  

### PR DESCRIPTION
**Pull request by mingmingl-llvm**
Simplify the compiler-rt test to make it more general for different platforms, and use `*DAG` matchers for lines that may be emitted out-of-order.
- The compiler-rt  test passed on a Windows machine. Previously name matchers don't work for MSVC mangling (https://lab.llvm.org/buildbot/#/builders/127/builds/59907)
- `*DAG` matchers fixed the error in https://lab.llvm.org/buildbot/#/builders/94/builds/17924

This is the second reland and fixed errors caught in first reland (https://github.com/llvm/llvm-project/pull/75860)

**Original commit message**
Commit fe05193 (phab D156569), IRPGO names uses format `[<filepath>;]<linkage-name>` while prior format is `[<filepath>:<mangled-name>`. The format change would break the use case demonstrated in (updated)
`llvm/test/Transforms/PGOProfile/thinlto_indirect_call_promotion.ll` and `compiler-rt/test/profile/instrprof-thinlto-indirect-call-promotion.cpp`

This patch changes `GlobalValues::getGlobalIdentifer` to use the semicolon.

To elaborate on the scenario how things break without this PR
1. IRPGO raw profiles stores (compressed) IRPGO names of functions in one section, and per-function profile data in another section. The [NameRef](https://github.com/llvm/llvm-project/blob/fc715e4cd942612a091097339841733757b53824/compiler-rt/include/profile/InstrProfData.inc#L72) field in per-function profile data is the MD5 hash of IRPGO names.
2. When raw profiles are converted to indexed format profiles, the profiled address is [mapped](https://github.com/llvm/llvm-project/blob/fc715e4cd942612a091097339841733757b53824/llvm/lib/ProfileData/InstrProf.cpp#L876-L885) to the MD5 hash of the callee.
3. In `pgo-instr-use` thin-lto prelink pipeline, MD5 hash of IRPGO names will be [annotated](https://github.com/llvm/llvm-project/blob/fc715e4cd942612a091097339841733757b53824/llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp#L1707) as value profiles, and used to import indirect-call-prom candidates. If the annotated MD5 hash is computed from the new format while import uses the prior format, the callee cannot be imported.

* `compiler-rt/test/profile/instrprof-thinlto-indirect-call-promotion.cpp` is added to have an end-to-end test.
* `llvm/test/Transforms/PGOProfile/thinlto_indirect_call_promotion.ll` is updated to have better test coverage from another aspect (as runtime tests are more sensitive to the environment and may be skipped by some contributors)

### CODE REVIEW

**Comment by minglotus-6** [comment]
The diff of this reland compared with the 1st reland is clearer in this commit (https://github.com/llvm/llvm-project/pull/75954/commits/cca510e569e9325ec089974e006eb2a8e2d0a2a7)

**Comment by minglotus-6** [comment]
I'll go ahead and push it since the diff is test only.

**Comment by vitalybuka** [comment]
It fails here 
https://lab.llvm.org/buildbot/#/builders/18/builds/13216

**Comment by minglotus-6** [comment]
> It fails here https://lab.llvm.org/buildbot/#/builders/18/builds/13216

thanks for the report. I marked the two relevant tests as `UNSUPPORTED` in [commit 85525f8](https://github.com/llvm/llvm-project/commit/85525f8fb6740a4cc117b00a238c85bda4ea01bf).

Will need to investigate and re-enable them after getting access to ppc machine from [gcc farm](https://gcc.gnu.org/wiki/CompileFarm)

**Comment by minglotus-6** [comment]
I'm seeing spurious failures from big-endian systems. I'll revert and investigate a fix.

**Comment by minglotus-6** [comment]
> I'm seeing spurious failures from big-endian systems. I'll revert and investigate a fix.

I ended up sending a fix forward in https://github.com/llvm/llvm-project/pull/76001 . Will monitor the build-bots.

**Comment by minglotus-6** [comment]
And pushed https://github.com/llvm/llvm-project/pull/76005 to require 64-bit systems for IR test. Raw profile reader swaps byte orders properly so `REQUIRES: host-byteorder-little-endian` looks actually unnecessary but will keep it fwiw for now.

I feel sorry for dance around but figured fix forwards of test requirements is much faster than getting various machines and setting up environments there.. Will monitor the build-bots .

**Pull request merged**
