### PR TITLE
[libclang/python] Fix `get_exception_specification_kind`

### PR DESCRIPTION
**Pull request by DeinAlptraum**
Fix a bug with `get_exception_specification_kind`. The function did not work before. Also add a test that confirms that it works now.

### CODE REVIEW

**Comment by DeinAlptraum** [comment]
@Endilll I found another bug on the way, so here's a fix+test. Does this need a release note under `Python Binding Changes`?

**Comment by Endilll** [comment]
> @Endilll I found another bug on the way, so here's a fix+test. Does this need a release note under `Python Binding Changes`?

Yes, the general approach is that every change should come with a test and a release note.

On a different note, I wonder if there's a way to prevent this kind of bugs. Seems quite unfortunate that our python binding might not work because of something this silly.

**Comment by DeinAlptraum** [comment]
I can't think of any more genereal approach that prevents this sort of problem. Type checking would help with this (e.g. giving an error when an unknown attribute is called on an object) though it wouldn't have worked in this specific case... otherwise nothing to do but add more tests I guess.

**Review by Endilll — APPROVED** [review]

**Comment by DeinAlptraum** [comment]
Could you merge this for me?

On related note, do you think my contributions would count for "a track record of submitting high quality patches", i.e. should I apply for commit access?

**Comment by Endilll** [comment]
> On related note, do you think my contributions would count for "a track record of submitting high quality patches", i.e. should I apply for commit access?

To this end, I consider you eligible, as I mentioned offline yesterday.

**Pull request merged**
