### PR TITLE
[CMake] Fix DynamicLibraryTests exports symbol when plugins are enabled

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Exporting symbols from tools directory never worked with
`LLVM_EXPORT_SYMBOLS_FOR_PLUGINS=On`. When that options is on, only
symbols from the static library is linked is exported due to the export
symbols computation script. DynamicLibraryTests needs to export a symbol
from the tools/executable directory, so update it to use export list
instead.

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
Second attempt to fix: https://lab.llvm.org/buildbot/#/builders/64/builds/643/steps/6/logs/FAIL__LLVM-Unit__DynamicLibraryTests_DynamicLibrar

I have no idea how that used to work on AIX builder though.

**Comment by qiongsiwu** [comment]
I tested this change on AIX and `DynamicLibraryTests` is passing.

**Review by jakeegan — APPROVED** [review]

**Comment by cachemeifyoucan** [comment]
I guess sanitizer build needs to export more symbols :( Might need to revert again. Need to think a better solution.

**Comment by cachemeifyoucan** [comment]
I reverted. @jakeegan @qiongsiwu I might need some help to figure out why currently it fails on AIX to figure out a fix.

Specifically, what is the difference made by https://github.com/llvm/llvm-project/pull/102671 this patch? Does it generate a different export file on AIX and how is it different?

That might also help me to understand how the PR mentioned above can break seemingly unrelated tests.

**Comment by cachemeifyoucan** [comment]
Ah, actually previous try at: https://github.com/llvm/llvm-project/pull/102671 actually works and the failure was due to: https://github.com/llvm/llvm-project/issues/102858

ASAN made the other tests failed by pushing some symbols out of range. Now it is marked as unsupported on ASAN, let me get back the old fix.

**Comment by cachemeifyoucan** [comment]
Reland previous fix as 2596464dcd7563cb4f54ef794334fa87438cc324

**Pull request merged**
