### PR TITLE
[flang][debug] Support fir.vector type.

### PR DESCRIPTION
**Pull request by abidh**
This PR converts the `fir.vector<>` to `DICompositeTypeAttr(DW_TAG_array_type)` with `vector` flag set.

### CODE REVIEW

**Review by jeanPerier — COMMENTED** [review]
Looks good from a FIR pass point of view. I have little experience on using vector type extensions in Fortran and what the dwarf for it should be. So. I rather wait to see if someone with knowledge about vector types and dwarf can review.

**Comment by kkwli** [comment]
With `!fir.vector<4:i32>`, `ptype` or `whatis` in gdb gives `type = integer (4)`. I am wondering if we can give a more accurate name to the type, say "vector integer (4)". It is in fact a vector of integer(4). Maybe something like:

```
 <1><64>: Abbrev Number: 4 (DW_TAG_array_type)
    <65>   DW_AT_sibling     : 0x82
    <6d>   DW_AT_name        : (indirect string, offset: 0x61): vector integer (4)
    <75>   DW_AT_type        : 0x59
    <7d>   DW_AT_GNU_vector  : 1
```

**Comment by abidh** [comment]
> With `!fir.vector<4:i32>`, `ptype` or `whatis` in gdb gives `type = integer (4)`. I am wondering if we can give a more accurate name to the type, say "vector integer (4)". It is in fact a vector of integer(4). Maybe something like:
> 
> ```
>  <1><64>: Abbrev Number: 4 (DW_TAG_array_type)
>     <65>   DW_AT_sibling     : 0x82
>     <6d>   DW_AT_name        : (indirect string, offset: 0x61): vector integer (4)
>     <75>   DW_AT_type        : 0x59
>     <7d>   DW_AT_GNU_vector  : 1
> ```

I have updated the name of the type as suggested.

**Review by kkwli — APPROVED** [review]
LG
Thanks

**Pull request merged**
