### PR TITLE
[clang-format] Add a new style for the clang-format source code

### PR DESCRIPTION
**Pull request by owenca**

### CODE REVIEW

**Comment by owenca** [comment]
I don't want to "advertise" this new style in the documentation but am willing to be overruled by the majority.

**Review by HazardyKnusperkeks — APPROVED** [review]
What is your goal with that style?

**Comment by owenca** [comment]
> What is your goal with that style?

It was actually your [idea](https://reviews.llvm.org/D153208#4431239). 😉

**Comment by rymiel** [comment]
> I don't want to "advertise" this new style in the documentation but am willing to be overruled by the majority.

But you added it to the help text?

(I'm fine with this being undocumented)

**Review by rymiel — APPROVED** [review]

**Comment by owenca** [comment]
I was wondering myself. Will undo it before merging.

**Comment by HazardyKnusperkeks** [comment]
> > What is your goal with that style?
> 
> It was actually your [idea](https://reviews.llvm.org/D153208#4431239). 😉

I know, but I thought the thought was dropped. :)

So the intent is to use it on our `.clang-format` files?

**Comment by owenca** [comment]
Yep. Each file will contain only `BasedOnStyle: clang-format`.

**Comment by alexey-utkin** [comment]
Where is the documentation for the value? CLion reports `clang-format`  option as an error by the reason. No doc, no schema rule.

**Comment by HazardyKnusperkeks** [comment]
> Where is the documentation for the value? CLion reports `clang-format` option as an error by the reason. No doc, no schema rule.

There:
> I don't want to "advertise" this new style in the documentation but am willing to be overruled by the majority.

There is none, on purpose.

**Comment by mydeveloperday** [comment]
> Where is the documentation for the value? CLion reports `clang-format` option as an error by the reason. No doc, no schema rule.

Personally, I'm not a fan of CLion enough to care! especially following JetBrains slating of clang-format:  (thanks for doing that at a massive public C++ forum without contacting us), their content even questionable as to its accuracy. 

https://www.youtube.com/watch?v=NnQraMtpvws
https://blog.jetbrains.com/clion/2023/12/a-clangformat-story-and-the-third-clion-nova-update/

Maybe they can try contributing rather than complaining.

**Pull request merged**
