### PR TITLE
[clang] Emit constraint intrinsics for arc and hyperbolic trig clang builtins

### PR DESCRIPTION
**Pull request by farzonl**
## Change(s)
- `Builtins.td` - Add f16 support for libm arc and hyperbolic trig functions
- `CGBuiltin.cpp` - Emit constraint intrinsics for trig clang builtins

## History
This change is part of an implementation of https://github.com/llvm/llvm-project/issues/87367's investigation on supporting IEEE math operations as intrinsics. Which was discussed in this RFC:
https://discourse.llvm.org/t/rfc-all-the-math-intrinsics/78294

This change adds wasm lowering cases for `acos`, `asin`, `atan`, `cosh`, `sinh`, and `tanh`.

https://github.com/llvm/llvm-project/issues/70079
https://github.com/llvm/llvm-project/issues/70080
https://github.com/llvm/llvm-project/issues/70081
https://github.com/llvm/llvm-project/issues/70083
https://github.com/llvm/llvm-project/issues/70084
https://github.com/llvm/llvm-project/issues/95966

## Precursor PR(s)

Note this PR needs Merge after:
- #98937
- #98755

### CODE REVIEW

**Review by efriedma-quic — APPROVED** [review]
LGTM

**Comment by alanzhao1** [comment]
We (Chrome) are seeing linker failures on our x86 Windows builds due to this PR: https://crbug.com/355455678

```
[12702/86218] LINK glmark2_wgl.exe glmark2_wgl.exe.pdb
..\..\third_party\llvm-build\Release+Asserts\bin\lld-link.exe /OUT:./glmark2_wgl.exe /nologo -libpath:..\..\third_party\llvm-build\Release+Asserts\lib\clang\20\lib\windows /winsysroot:../../third_party/depot_tools/win_toolchain/vs_files/7393122652 /MACHINE:X86 /PDB:./glmark2_wgl.exe.pdb @./glmark2_wgl.exe.rsp
lld-link: error: undefined symbol: _asinf
>>> referenced by .\..\..\third_party\angle\third_party\glmark2\src\src\model.cpp:266
>>>               obj/third_party/angle/third_party/glmark2/glmark2_common_gl/model.obj:(public: void __thiscall Model::calculate_texcoords(void))
>>> referenced by .\..\..\third_party\angle\third_party\glmark2\src\src\model.cpp:267
>>>               obj/third_party/angle/third_party/glmark2/glmark2_common_gl/model.obj:(public: void __thiscall Model::calculate_texcoords(void))

lld-link: error: undefined symbol: _atanf
>>> referenced by .\..\..\third_party\angle\third_party\glmark2\src\src\scene-build.cpp:179
>>>               obj/third_party/angle/third_party/glmark2/glmark2_common_gl/scene-build.obj:(public: virtual bool __thiscall SceneBuild::setup(void))
>>> referenced by .\..\..\third_party\angle\third_party\glmark2\src\src\scene-refract.cpp:382
>>>               obj/third_party/angle/third_party/glmark2/glmark2_common_gl/scene-refract.obj:(public: bool __thiscall RefractPrivate::setup(class std::__Cr::map<class std::__Cr::basic_string<char, struct std::__Cr::char_traits<char>, class std::__Cr::allocator<char>>, struct Scene::Option, struct std::__Cr::less<class std::__Cr::basic_string<char, struct std::__Cr::char_traits<char>, class std::__Cr::allocator<char>>>, class std::__Cr::allocator<struct std::__Cr::pair<class std::__Cr::basic_string<char, struct std::__Cr::char_traits<char>, class std::__Cr::allocator<char>> const, struct Scene::Option>>> &))
>>> referenced by .\..\..\third_party\angle\third_party\glmark2\src\src\scene-shading.cpp:250
>>>               obj/third_party/angle/third_party/glmark2/glmark2_common_gl/scene-shading.obj:(public: virtual bool __thiscall SceneShading::setup(void))
>>> referenced 2 more times
exit=1
error: 1 steps failed
```

**Comment by efriedma-quic** [comment]
Right, asinf doesn't exist on Windows (see llvm/lib/Analysis/TargetLibraryInfo.cpp).  We probably need code to promote calls to llvm.asin.f32 to 64-bit.  Not sure how hard it would be to revert this... probably easier to fix forward if we can do that quickly.

We'll need a fix for the regression for the 19 branch.

**Comment by farzonl** [comment]
> Right, asinf doesn't exist on Windows (see llvm/lib/Analysis/TargetLibraryInfo.cpp). We probably need code to promote calls to llvm.asin.f32 to 64-bit. Not sure how hard it would be to revert this... probably easier to fix forward if we can do that quickly.
> 
> We'll need a fix for the regression for the 19 branch.

I see that  promoting seems like it could work, but it is also disabled for f80\f128:
https://github.com/llvm/llvm-project/blob/39e192b379362e9e645427631c35450d55ed517d/llvm/lib/Analysis/TargetLibraryInfo.cpp#L322C5-L324C39

How should we handle that case?

**Comment by farzonl** [comment]
> We (Chrome) are seeing linker failures on our x86 Windows builds due to this PR: https://crbug.com/355455678
> 
> ```
> [12702/86218] LINK glmark2_wgl.exe glmark2_wgl.exe.pdb
> ..\..\third_party\llvm-build\Release+Asserts\bin\lld-link.exe /OUT:./glmark2_wgl.exe /nologo -libpath:..\..\third_party\llvm-build\Release+Asserts\lib\clang\20\lib\windows /winsysroot:../../third_party/depot_tools/win_toolchain/vs_files/7393122652 /MACHINE:X86 /PDB:./glmark2_wgl.exe.pdb @./glmark2_wgl.exe.rsp
> lld-link: error: undefined symbol: _asinf
> >>> referenced by .\..\..\third_party\angle\third_party\glmark2\src\src\model.cpp:266
> >>>               obj/third_party/angle/third_party/glmark2/glmark2_common_gl/model.obj:(public: void __thiscall Model::calculate_texcoords(void))
> >>> referenced by .\..\..\third_party\angle\third_party\glmark2\src\src\model.cpp:267
> >>>               obj/third_party/angle/third_party/glmark2/glmark2_common_gl/model.obj:(public: void __thiscall Model::calculate_texcoords(void))
> 
> lld-link: error: undefined symbol: _atanf
> >>> referenced by .\..\..\third_party\angle\third_party\glmark2\src\src\scene-build.cpp:179
> >>>               obj/third_party/angle/third_party/glmark2/glmark2_common_gl/scene-build.obj:(public: virtual bool __thiscall SceneBuild::setup(void))
> >>> referenced by .\..\..\third_party\angle\third_party\glmark2\src\src\scene-refract.cpp:382
> >>>               obj/third_party/angle/third_party/glmark2/glmark2_common_gl/scene-refract.obj:(public: bool __thiscall RefractPrivate::setup(class std::__Cr::map<class std::__Cr::basic_string<char, struct std::__Cr::char_traits<char>, class std::__Cr::allocator<char>>, struct Scene::Option, struct std::__Cr::less<class std::__Cr::basic_string<char, struct std::__Cr::char_traits<char>, class std::__Cr::allocator<char>>>, class std::__Cr::allocator<struct std::__Cr::pair<class std::__Cr::basic_string<char, struct std::__Cr::char_traits<char>, class std::__Cr::allocator<char>> const, struct Scene::Option>>> &))
> >>> referenced by .\..\..\third_party\angle\third_party\glmark2\src\src\scene-shading.cpp:250
> >>>               obj/third_party/angle/third_party/glmark2/glmark2_common_gl/scene-shading.obj:(public: virtual bool __thiscall SceneShading::setup(void))
> >>> referenced 2 more times
> exit=1
> error: 1 steps failed
> ```

I'm preparing a fix, building it now  should be up in the next 20-30 minutes. Thanks for reporting this issue!

**Comment by farzonl** [comment]
@alanzhao1 @efriedma-quic It should be fixed now by #101268 if you role the clang build to latest.

**Comment by alanzhao1** [comment]
> @alanzhao1 @efriedma-quic It should be fixed now by #101268 if you role the clang build to latest.

Confirmed. Thanks!

**Pull request merged**
