### PR TITLE
Reland "[InstCombine] Extend `foldICmpBinOp` to `add`-like `or`"

### PR DESCRIPTION
**Pull request by mgudim**
The original PR had a typo which was causing a bug.

### CODE REVIEW

**Comment by mgudim** [comment]
@nikic See the last commit for the bug fix.

**Comment by nikic** [comment]
@mgudim Can you please also add a test for the bug fix?

**Comment by mgudim** [comment]
> @mgudim Can you please also add a test for the bug fix?

Yes, sorry I was about to do that.

**Comment by mgudim** [comment]
> @mgudim Can you please also add a test for the bug fix?

Done. See last commit.

**Review by nikic — APPROVED** [review]
LGTM

**Pull request merged**
