### PR TITLE
[msan] Reduces overhead of #113200, by 10%

### PR DESCRIPTION
**Pull request by vitalybuka**
CTMark #113200 size overhead was 5.3%, now it's 4.7%.

The patch affects only signed integers.

https://alive2.llvm.org/ce/z/Lv5hyi

* The patch replaces code which extracted sign bit,
maximized/minimized it, then packed it back, with
simple sign bit flip. The another way to think about
transformation is as a subtraction of MIN_SINT from
A/B. Then we map MIN_SINT to 0, 0 to -MIN_SINT, and
MAX_SINT to MAX_UINT.

* Then to maximize/minimize A/B we don't need
to extract sign bit, we can apply shadow the
same way as to other bits.

* After sign bit flip, we had to switch to unsigned
version of the predicates.

* After change above  getHighestPossibleValue/getLowestPossibleValue
became very similar, so we can combine into a single function.

* Because the function does sign bit flip and
requires unsigned predicates used for returned values,
there is no point in keeping it as a member of class,
to hide, we switch to function local lambda.

### CODE REVIEW

**Comment by fmayer** [comment]
`#TODO`?

**Comment by vitalybuka** [comment]
> `#TODO`?

Yes,  base PR only was not upload yet.

**Comment by fmayer** [comment]
Please explain in commit message what the change does

**Comment by vitalybuka** [comment]
> Please explain in commit message what the change does

Done

**Review by fmayer — APPROVED** [review]

**Review by eugenis — APPROVED** [review]
Seems correct to me.

**Review by cjappl — APPROVED** [review]
LGTM

**Pull request merged**
