### PR TITLE
[DebugInfo] Allow DISubrange/DIGenericSubrange without count/upperBound.

### PR DESCRIPTION
**Pull request by abidh**
Due to the current order of metadata in DISubprgram, `Type` is processed before `Unit` by the Verifier. This can cause a race and 
 use of garbage data. Consider the following code:

```
int test(int a[][5])
{
    return a[0][2];
}
```

when compiled with clang, the control reaches `Verifier::visitDISubrange` first with `CurrentSourceLang` still equal to dwarf::DW_LANG_lo_user (32768). The `Verifier::visitDICompileUnit` which sets the value of `CurrentSourceLang` is reached later. So `Verifier::visitDISubrange` ends up using a wrong value of `CurrentSourceLang`.

This behavior does not effect C like language much but is a problem for Fortran. There is special processing in `Verifier::visitDISubrange` when `CurrentSourceLang` is Fortran. With this problem, that special handling is missed and verifier fails for any code that has Fortran's assumed size array in a global subroutine.

To fix this, I have swapped the position of `Type` and `Unit`. They were already adjacent so it does not require changing position of anything else.

### CODE REVIEW

**Comment by jmorse** [comment]
As far as I understand this patch, it's swapping which field of a DISubprogram the data is stored in, and all the accessors are updated, so this patch should be transparent to any code using the accessors.

Thus, surely the problem is caused by code that directly accesses the fields of DISubprogram and is exposed to their ordering -- shouldn't such code instead examine fields in a logical manner rather than the order of storage?

**Comment by abidh** [comment]
> As far as I understand this patch, it's swapping which field of a DISubprogram the data is stored in, and all the accessors are updated, so this patch should be transparent to any code using the accessors.
> 
> Thus, surely the problem is caused by code that directly accesses the fields of DISubprogram and is exposed to their ordering -- shouldn't such code instead examine fields in a logical manner rather than the order of storage?

The caller here is `Verifier::visitMDNode`. It does not directly access the fields of `DISubprogram`. That code does not even know it is processing `DISubprogram`. It is processing the fields of an `MDNode` in order they are returned by the MDNode.operands().

**Comment by abidh** [comment]
> Most curious; my understanding of `Verifier::visitMDNode` [0] is that it should be calling out into visitDISubprogram by switching on the metadata ID -- do you have a reproducer for the behaviour you're observing? It sounds like something is broken, but if it's fixed by re-ordering fields then there's something even bigger that's broken lurking under the surface.
> 
> [0]
> 
> https://github.com/llvm/llvm-project/blob/6481dc57612671ebe77fe9c34214fba94e1b3b27/llvm/lib/IR/Verifier.cpp#L1058

Problem comes from the loop a few lines below [0]. It calls the visitMDNode on operands in order. You can reproduce it using following code. 

```
int test(int a[][5])
{
    return a[0][2];
}
```
You will see that control reaches `Verifier::visitDISubrange` first with `CurrentSourceLang` still equal to `dwarf::DW_LANG_lo_user (32768)`. The `Verifier::visitDICompileUnit` which sets the value of `CurrentSourceLang` will be called later.


[0] https://github.com/llvm/llvm-project/blob/6481dc57612671ebe77fe9c34214fba94e1b3b27/llvm/lib/IR/Verifier.cpp#L1063

**Comment by jmorse** [comment]
Aaaaahhh, I get it now, thanks for bearing with me -- I see that the `Verifier` class has a `CurrentSourceLang` field that gets populated while exploring the metadata tree, and visiting the Unit before the Type in a subprogram ensures that `CurrentSourceLang` gets set before further exploration occurs.

I still feel flipping the order of fields is fixing the symptom rather than the cause -- stepping back a bit, by having state in the Verifier object we're implicitly requiring metadata to be explored in a particular order. This patch will fix one incorrect order, but there might be other incorrect orders or it might expose more.

Instead: how about setting CurrentSourceLang in `visitDISubprogram` instead, skipping that behaviour if the Unit appears to be invalid. Whenever we visit a subprogram, we're about to visit a collection of variables, types and other entities that may depend on the source language, and verifying a `Function` independently is a fairly common use-case IMHO. This also avoids relying on an implementation detail of the DISubprogram class layout.

I get the feeling that the state in `Verifier` will cause trouble in LTO contexts where there are multiple compile units in a `Module`, but I'm not familiar enough with metadata in LTO contexts to give an opinion.

**Comment by abidh** [comment]
> Aaaaahhh, I get it now, thanks for bearing with me -- I see that the `Verifier` class has a `CurrentSourceLang` field that gets populated while exploring the metadata tree, and visiting the Unit before the Type in a subprogram ensures that `CurrentSourceLang` gets set before further exploration occurs.
> 
> I still feel flipping the order of fields is fixing the symptom rather than the cause -- stepping back a bit, by having state in the Verifier object we're implicitly requiring metadata to be explored in a particular order. This patch will fix one incorrect order, but there might be other incorrect orders or it might expose more.
> 
> Instead: how about setting CurrentSourceLang in `visitDISubprogram` instead, skipping that behaviour if the Unit appears to be invalid. Whenever we visit a subprogram, we're about to visit a collection of variables, types and other entities that may depend on the source language, and verifying a `Function` independently is a fairly common use-case IMHO. This also avoids relying on an implementation detail of the DISubprogram class layout.
> 
> I get the feeling that the state in `Verifier` will cause trouble in LTO contexts where there are multiple compile units in a `Module`, but I'm not familiar enough with metadata in LTO contexts to give an opinion.

Thanks for taking a look. Setting `CurrentSourceLang` in `visitDISubprogram` is a good suggestion. I have changed the PR to use it. If it looks ok then I will update the heading and description of the PR accordingly.

**Comment by jmorse** [comment]
In principle this LGTM, perhaps other reviewers could chime in though. In an ideal world we'd have a test that ensures this behaviour continues to be present, is there an LLVM-IR input from flang that triggers the previous error, and that we can have in the LLVM DebugInfo test suite?

**Comment by dwblaikie** [comment]
> In principle this LGTM, perhaps other reviewers could chime in though.

Yeah, bit janky - I don't totally object.

But alternatively: Could we remove the use/need for CurrentSourceLang? Guess it was added for fortran support, but perhaps we should've gone the toher way and weakened the checks? Just don't check for count/upperbound at all? (in visitDISubrange) 

Presumably LLVM can produce whatever DWARF we do for Fortran given such info, and do that for C++ too - even if it's incorrect for C++, maybe we move that to just be up to the IR generator to get that right?

**Comment by abidh** [comment]
> > In principle this LGTM, perhaps other reviewers could chime in though.
> 
> Yeah, bit janky - I don't totally object.
> 
> But alternatively: Could we remove the use/need for CurrentSourceLang? Guess it was added for fortran support, but perhaps we should've gone the toher way and weakened the checks? Just don't check for count/upperbound at all? (in visitDISubrange)
> 
> Presumably LLVM can produce whatever DWARF we do for Fortran given such info, and do that for C++ too - even if it's incorrect for C++, maybe we move that to just be up to the IR generator to get that right?

I did a bit of digging and it seems that those checks for count/upperBound were added for Fortran's allocatable array in https://reviews.llvm.org/D80197. Later they had to be modified for Fortran's assumed size arrays in https://reviews.llvm.org/D87500. So the checks were added for a Fortran feature and later had to be disabled for Fortran. Removing/weakening them seems reasonable to me. Please let me know if you prefer this solution.

**Comment by dwblaikie** [comment]
Yeah, lets weaken the verification here - if LLVM's DWARF generation can succeed (not crash), I think that's all we should care about. If someone makes a DISubrange with an upper bound lower than the lower bound (implicit or explicit) - *shrug* garbage in, garbage out. I don't think it's worth trying to save them from themselves with the IR verifier.

**Comment by dwblaikie** [comment]
(might be worth checking where the earlier version of the check was (before fortran - looks like it just checked the upper bound was >= 0) - and if the author is still around, cc them on this in case they want to protest that checking that is really important or something)

**Comment by abidh** [comment]
> (might be worth checking where the earlier version of the check was (before fortran - looks like it just checked the upper bound was >= 0) - and if the author is still around, cc them on this in case they want to protest that checking that is really important or something)

I have removed the check that Subrange/GenericSubrange must contain count or upper bound. I have also removed `CurrentSourceLang` and updated the tests accordingly.

From your comments, I guess that you also wanted to remove the `count >= -1` check. I have left it there for now. AsmParser catches the case if you give it a file with `count < -1`. I thought that similar check should stay on the Verifier too. The `count >= -1` check was added by @dexonsmith in 53855f05d315ccfbdc14d0ef2230b008a8e44adc.

**Comment by dwblaikie** [comment]
Yeah... @alokkrsharma in case they've got thoughts on this issue/changes...

**Comment by dwblaikie** [comment]
This change will need test coverage - it might be worth keeping the existing tests around and turning them into code generation tests, to check we can generate DWARF even when we violate these verifier checks? 
And we'll need a new test for the intended functionality that motivated you to look into this issue in the first place? (the missing language code/incorrect bounds checking issue? Though I realize it's sort of a non-issue once there's no bounds checking at all anyway... )

**Comment by abidh** [comment]
> This change will need test coverage - it might be worth keeping the existing tests around and turning them into code generation tests, to check we can generate DWARF even when we violate these verifier checks? And we'll need a new test for the intended functionality that motivated you to look into this issue in the first place? (the missing language code/incorrect bounds checking issue? Though I realize it's sort of a non-issue once there's no bounds checking at all anyway... )

I have added a test that checks that debug info is generated correctly when these conditions are violated. The test covers the original motivating case that compilation does not fail for things like `!DISubrange()`.

**Comment by alokkrsharma** [comment]
> Yeah... @alokkrsharma in case they've got thoughts on this issue/changes...

I'll have a look and get back on this. Thanks.

**Comment by alokkrsharma** [comment]
This LGTM.

Initially (Before enhancements for the Fortran debugging) Verifier had a restriction for DISubrange to have count as REQUIRED field. As languages do have default values for lowerBound, count explicitly gives number of elements and upper bound can be calculated (upper - lower +1).
We have relaxed this restriction for the first time due to the need of the Fortran language where upperBound is used more naturally and if needed count can be calculated. Now DISubrange should either have count or upperBound.
This restriction further relaxed again for the Fortran assumed size array where for last dimension count/upper bound can be absent.

Removing restriction completely in place of relaxing would make any language (like Fortran) with prosperous arrays happy. I agree with the point that back-end should have common/minimum restrictions which applies to all the languages, any extra restriction should be moved to respective front-ends if needed. Thanks.

**Review by jmorse — APPROVED** [review]
LGTM; please leave a day or two before landing so that other reviewers can chip in.

**Comment by abidh** [comment]
I am going to modify test to have `; REQUIRES: x86_64-linux` as other related fortran tests do.

**Pull request merged**
