### PR TITLE
Fix error message when regalloc eviction advisor analysis could not be created

### PR DESCRIPTION
**Pull request by hiraditya**

### CODE REVIEW

**Review by mtrofin — APPROVED** [review]
lgtm, thanks!

**Comment by pcc** [comment]
Maybe also remove the words "Using default"? It's an error, the compiler isn't going to "use" anything.

**Comment by boomanaiden154** [comment]
> Maybe also remove the words "Using default"? It's an error, the compiler isn't going to "use" anything.

It's an error, but not an error that causes an exit, as the state is still fine to continue on from. The variable comes from https://github.com/hiraditya/llvm-project/blob/0175a1e4d33720ed7e827b3db5a36f88bdd790a3/llvm/lib/CodeGen/RegAllocEvictionAdvisor.cpp#L93. If the user requests an ML analysis and it can't be created (eg due to the user not building with the ML stuff enabled), `NotAsRequested` is set to true, and the default advisor is constructed. Everything still works with the default advisor, it's just not what the user requested.

**Comment by pcc** [comment]
I think you're referring to an atypical case where a program prints an error and continues anyway. By default I would expect programs to fail if they encounter an error, and it's confusing to have the error message assume otherwise. It's fine if the error message doesn't say exactly what happened if the user passed some "ignore all errors" flag.

**Comment by boomanaiden154** [comment]
Yes, it is an atypical case. It very much depends on the type of error on whether or not the program exits. I'm not currently understanding your point about it being confusing if the error message assumes otherwise. The program does continue, doing exactly what is said in the error message. I'm also not sure what sort of "ignore all errors" flag would even be useful to suppress this message.

**Comment by pcc** [comment]
Yes, technically the program does continue but my point is that won't matter to the user because the output file will not be generated if the program is implemented correctly. By "ignore all errors" flag I mean something like the `--noinhibit-exec` passed to lld, which would convert errors to warnings where possible. I'm not sure if this error would actually be converted to a warning by that flag, though.

**Comment by boomanaiden154** [comment]
Why would the output file not be generated correctly? I think at this point it's just a difference in interpretation over what `emitError` should do. It doesn't exit the program, it simply outputs to STDOUT/STDERR that an error occurred, and then the program continues on as normal (with the default eviction advisor in this case).

**Pull request merged**
