### PR TITLE
[mlir-tblgen] Fix bug in emitEnumDoc

### PR DESCRIPTION
**Pull request by mdehling**
Fixes a crash (assertion failure) in `mlir-tblgen -emit-enum-doc` caused by calling `EnumAttr()` for the wrong type of `Record *`: `EnumAttr` rather than `EnumAttrInfo` as asserted.

Compare the corresponding line in `emitDialectDoc()`:
https://github.com/llvm/llvm-project/blob/0ad6be1927f89cef09aa5d0fb244873f687997c9/mlir/tools/mlir-tblgen/OpDocGen.cpp#L532

### CODE REVIEW

**Comment by mdehling** [comment]
Pinging @nikic @antiagainst @kuhar since you were reviewers for another recent `mlir-tblgen` pr.  Could one of you have a quick look at this?

**Review by kuhar — COMMENTED** [review]
How can we reproduce this crash?

**Comment by mdehling** [comment]
Thank you for taking the time.

To reproduce, run for example:
```
$ mlir-tblgen -gen-enum-doc mlir/include/mlir/Dialect/Linalg/IR/LinalgBase.td -I mlir/include
mlir-tblgen: /home/m.dehling/llvm-project/mlir/lib/TableGen/Attribute.cpp:169: mlir::tblgen::EnumAttr::EnumAttr(const llvm::Record *): Assertion `isSubClassOf("EnumAttrInfo") && "must be subclass of TableGen 'EnumAttr' class"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: ./build/bin/mlir-tblgen -gen-enum-doc mlir/include/mlir/Dialect/Linalg/IR/LinalgBase.td -I mlir/include
Stack dump without symbol names (ensure you have llvm-symbolizer in your PATH or set the environment var `LLVM_SYMBOLIZER_PATH` to point to it):
0  mlir-tblgen 0x000055f9b588a907
1  mlir-tblgen 0x000055f9b5888b40
2  mlir-tblgen 0x000055f9b588af9a
3  libc.so.6   0x00007fbc60c66520
4  libc.so.6   0x00007fbc60cba9fc pthread_kill + 300
5  libc.so.6   0x00007fbc60c66476 raise + 22
6  libc.so.6   0x00007fbc60c4c7f3 abort + 211
7  libc.so.6   0x00007fbc60c4c71b
8  libc.so.6   0x00007fbc60c5de96
9  mlir-tblgen 0x000055f9b58e44f5
10 mlir-tblgen 0x000055f9b57e993c
11 mlir-tblgen 0x000055f9b58c2d76
12 mlir-tblgen 0x000055f9b58c5836
13 mlir-tblgen 0x000055f9b58c258f
14 libc.so.6   0x00007fbc60c4dd90
15 libc.so.6   0x00007fbc60c4de40 __libc_start_main + 128
16 mlir-tblgen 0x000055f9b5744355
Aborted (core dumped)
```

You will notice the assertion error doesn't match the condition checked.

**Review by kuhar — APPROVED** [review]
LGTM.

Thanks for the repro, it does fix the crash.

**Pull request merged**
