### PR TITLE
[Analysis] Fix null ptr dereference when using WriteGraph without branch probability info

### PR DESCRIPTION
**Pull request by TylerNowicki**
The call to  'CFGInfo->getBPI()->getEdgeProbability(Node, SuccBB);' fails when BPI is not provided. In this case we can give up and not print any edge attributes.

### CODE REVIEW

**Comment by aeubanks** [comment]
can you add a test for this?

**Comment by TylerNowicki** [comment]
> can you add a test for this?

Done

**Review by aeubanks — APPROVED** [review]
I would have preferred an opt test, but looking at the places that construct `DOTFuncInfo`, they seem to always pass BFI, so lgtm

**Comment by TylerNowicki** [comment]
The call to 'CFGInfo->getBPI()->getEdgeProbability(Node, SuccBB);' fails when BPI is not provided. This caused WriteGraph to fail, even though it should support null BPI. This patch makes getEdgeAttribute give up if BPI is not present.

**Comment by TylerNowicki** [comment]
I am trying to figure out how to run the above failures locally, but I am not able to see how to do it. Do you know how to reproduce these errors @aeubanks ?

**Comment by aeubanks** [comment]
the failures seem unrelated

**Pull request merged**
