### PR TITLE
[win/asan] GetInstructionSize: Fix `41 81 7c ...` to return 9.

### PR DESCRIPTION
**Pull request by bernhardu**
Trying to populate the recently added test for GetInstructionSize I stumbled over this.
gdb and bddisasm have the opinion this instruction is 9 bytes.
Also lldb shows this:
```
(lldb) disassemble --bytes --start-address 0x0000555555556004 --end-address 0x0000555555556024
    0x555555556004: 41 81 7b 73 74 75 76 77     cmpl   $0x77767574, 0x73(%r11)   ; imm = 0x77767574 
    0x55555555600c: 41 81 7c 73 74 75 76 77 78  cmpl   $0x78777675, 0x74(%r11,%rsi,2) ; imm = 0x78777675 
    0x555555556015: 41 81 7d 73 74 75 76 77     cmpl   $0x77767574, 0x73(%r13)   ; imm = 0x77767574 
    0x55555555601d: 00 00                       addb   %al, (%rax)
```

There is also a handy tool in llvm to directly feed in the byte sequence - `41 81 7c` also uses 9 bytes here:
```
$ echo -n -e "0x41, 0x81, 0x7b, 0x73, 0x74, 0x75, 0x76, 0x77, 0x90" | ./llvm/build/bin/llvm-mc --disassemble --show-encoding
        .text
        cmpl    $2004252020, 115(%r11)          # encoding: [0x41,0x81,0x7b,0x73,0x74,0x75,0x76,0x77]
                                        # imm = 0x77767574
        nop                                     # encoding: [0x90]
$ echo -n -e "0x41, 0x81, 0x7c, 0x73, 0x74, 0x75, 0x76, 0x77, 0x78, 0x90" | ./llvm/build/bin/llvm-mc --disassemble --show-encoding
        .text
        cmpl    $2021095029, 116(%r11,%rsi,2)   # encoding: [0x41,0x81,0x7c,0x73,0x74,0x75,0x76,0x77,0x78]
                                        # imm = 0x78777675
        nop                                     # encoding: [0x90]
```

### CODE REVIEW

**Comment by bernhardu** [comment]
@zmodem Thanks for the other reviews and merges, may I ask for another review of this one?

**Review by zmodem — APPROVED** [review]
lgtm

**Comment by bernhardu** [comment]
I would like to change this PR to include the addition of a test line.
But this would need to go in #118204 first, so I hope it is ok if I change this to Draft?

**Comment by bernhardu** [comment]
v2:
- Rebased to current git

v3:
- Added the test line.

**Review by zmodem — APPROVED** [review]
lgtm

Would you like me to hit the "merge" button?

**Comment by bernhardu** [comment]
> Would you like me to hit the "merge" button?
Thanks for reviewing, if there are no more concerns about the change, yes, please.

**Pull request merged**
