### PR TITLE
[Support] Remove terminfo dependency

### LINKED ISSUE #53294: llvm-config does not respect LLVM_ENABLE_TERMINFO
When building LLVM without terminfo support by passing `-DLLVM_ENABLE_TERMINFO=OFF` to CMake, the `llvm-config` executable fails to link because the CMakeLists.txt for `llvm-config` does not check `LLVM_ENABLE_TERMINFO`, but passes `-ltinfo` in the link arguments **regardless of whether or not the option is set**. Build output looks as follows:

```
[1/1] Linking CXX executable bin/llvm-config
FAILED: bin/llvm-config 
: && /usr/sbin/aarch64-linux-gnu-g++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wmisleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG -Wl,-rpath-link,/home/user/llvm-target-build/NATIVE/./lib  -Wl,-O3 -Wl,--gc-sections tools/llvm-config/CMakeFiles/llvm-config.dir/llvm-config.cpp.o -o bin/llvm-config  -Wl,-rpath,"\$ORIGIN/../lib"  lib/libLLVMSupport.a  -lpthread  -lrt  -ldl  -lpthread  -lm  -ltinfo  lib/libLLVMDemangle.a && :
/usr/lib/gcc/aarch64-linux-gnu/10.2.0/../../../../aarch64-linux-gnu/bin/ld: cannot find -ltinfo
collect2: error: ld returned 1 exit status
ninja: build stopped: subcommand failed.
```

Expected behaviour is the same as all the other parts of the system that respect `LLVM_ENABLE_TERMINFO`, i.e. that `-ltinfo` should not be passed as a link flag in the linking command. What is actually happening is that in the CMakeLists.txt for `llvm-config` the link line is assembled by adding in **all** the libraries from `LLVM_SYSTEM_LIBS`. However, if `LLVM_ENABLE_TERMINFO` is false, `-ltinfo` should be **removed** from the linked libraries.

This problem crops up whenever LLVM is being cross-compiled and a target version of libtinfo is not available. Without a fix, LLVM cannot be cross-compiled without first cross-compiling ncurses for the target platform and providing a custom linking environment for the build, which seems like exactly the problem `LLVM_ENABLE_TERMINFO` exists to prevent.

### LINKED ISSUE #75490: Release builds dynamically linked to missing libtinfo.so.5
Possibly related to #17276.

E.g. https://github.com/llvm/llvm-project/releases/download/llvmorg-15.0.6/clang+llvm-15.0.6-x86_64-linux-gnu-ubuntu-18.04.tar.xz

This library is [not present by default](https://packages.ubuntu.com/search?keywords=libtinfo) on current Ubuntu systems, even though it was present in the past.

I'm not sure what the right answer is here:
 - document the non-current libraries users (e.g. Bazel toolchains, nix recipes, actual people) have to install to use clang
 - build clang in a more hermetic fashion, with no dynamic dependencies outside those LSB mandates
 - [piss off the one person in Google again](https://reviews.llvm.org/D42274#1076895).
 - something else

### PR DESCRIPTION
**Pull request by aaronmondal**
The terminfo dependency introduces a significant nonhermeticity into the build. It doesn't respect `--no-undefined-version` meaning that it's not a dependency that can be built with Clang 17+. This forces maintainers of source-based distributions to implement patches or ignore linker errors.

Remove it to reduce the closure size and improve portability of LLVM-based tools. Users can still use command line arguments to toggle color support expliticly.

Fixes #75490
Closes #53294 #23355

### CODE REVIEW

**Comment by keith** [comment]
looks like the .bazelrc still has mentions of this

**Comment by JDevlieghere** [comment]
No objections in the context of LLDB. We don't use terminfo directly (although I think editline does, but that isn't affected by this) and if we want the TUI we depend on curses anyway.

**Review by MaskRay — APPROVED** [review]

**Review by petrhosek — APPROVED** [review]

**Comment by gulfemsavrun** [comment]
We started seeing the following issue after this patch in our Clang toolchain builders: 
```
1448/1517](45) Linking CXX executable unittests/LineEditor/LineEditorTests
FAILED: unittests/LineEditor/LineEditorTests 
: && /b/s/w/ir/x/w/cipd/bin/clang++ --sysroot=/b/s/w/ir/x/w/cipd/linux -stdlib=libc++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -ffat-lto-objects -ffile-prefix-map=/b/s/w/ir/x/w/llvm_build=../llvm-llvm-project -ffile-prefix-map=/b/s/w/ir/x/w/llvm-llvm-project/= -no-canonical-prefixes -O3 -DNDEBUG -static-libstdc++ -stdlib=libc++ -static-libstdc++ -fuse-ld=lld -Wl,--color-diagnostics -ffat-lto-objects    -Wl,--gc-sections unittests/LineEditor/CMakeFiles/LineEditorTests.dir/LineEditor.cpp.o -o unittests/LineEditor/LineEditorTests  lib/libLLVMLineEditor.a  lib/libLLVMSupport.a  lib/libLLVMSupport.a  -lpthread  lib/libllvm_gtest_main.a  lib/libllvm_gtest.a  -lpthread  /b/s/w/ir/x/w/libedit_install/lib/libedit.a  lib/libLLVMSupport.a  -lrt  -ldl  -lpthread  -lm  /b/s/w/ir/x/w/zlib_install_target/lib/libz.a  /b/s/w/ir/x/w/zstd_install/lib/libzstd.a  -pthread  lib/libLLVMDemangle.a  -lpthread && :
ld.lld: error: undefined symbol: tgetent
>>> referenced by terminal.c
>>>               terminal.o:(terminal_set) in archive /b/s/w/ir/x/w/libedit_install/lib/libedit.a
```
https://logs.chromium.org/logs/fuchsia/buildbucket/cr-buildbucket/8747030306803673361/+/u/clang/test/stdout

**Comment by aaronmondal** [comment]
@gulfemsavrun The file `terminal.c` that is causing this linker error is not in LLVM but in `libedit`. The configure step doesn't find `libedit`:

```
Not searching for unused variables given on the command line.
-- Could NOT find LibEdit (missing: LibEdit_INCLUDE_DIRS LibEdit_LIBRARIES) 
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- Could NOT find zstd (missing: zstd_LIBRARY zstd_INCLUDE_DIR) 
-- Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR) 
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 

...

-- Could NOT find LibEdit (missing: LibEdit_INCLUDE_DIRS LibEdit_LIBRARIES) 
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- Could NOT find zstd (missing: zstd_LIBRARY zstd_INCLUDE_DIR) 
-- Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR) 
-- Could NOT find CURL (missing: CURL_LIBRARY CURL_INCLUDE_DIR) 

...

-- Building with -fPIC
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Using libunwind testing configuration: /b/s/w/ir/x/w/llvm-llvm-project/libunwind/test/configs/llvm-libunwind-static.cfg.in
-- Failed to locate sphinx-build executable (missing: SPHINX_EXECUTABLE) 
-- Using libc++abi testing configuration: /b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/test/configs/llvm-libc++abi-static.cfg.in
-- Using libc++ testing configuration: /b/s/w/ir/x/w/llvm-llvm-project/libcxx/test/configs/llvm-libc++-static.cfg.in
-- Could NOT find LibEdit (missing: LibEdit_INCLUDE_DIRS LibEdit_LIBRARIES) 
-- Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
-- Could NOT find zstd (missing: zstd_LIBRARY zstd_INCLUDE_DIR) 
-- Could NOT find LibXml2 (missing: LIBXML2_LIBRARY LIBXML2_INCLUDE_DIR) 
```

My guess is that some other mechanism is adding `libedit` into this build with an explicit `-ledit` flag instead of using `pkgconfig`. This causing the `/usr/lib64/pkgconfig/libedit.pc` (or similar) file to be ignored. That file should contain a line like `Libs.private: -ltinfo` if it's a `libedit` that was configured to depend on `tinfo`.

```
FAILED: unittests/LineEditor/LineEditorTests 
: && /b/s/w/ir/x/w/cipd/bin/clang++ --sysroot=/b/s/w/ir/x/w/cipd/linux -stdlib=libc++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -ffat-lto-objects -ffile-prefix-map=/b/s/w/ir/x/w/llvm_build=../llvm-llvm-project -ffile-prefix-map=/b/s/w/ir/x/w/llvm-llvm-project/= -no-canonical-prefixes -O3 -DNDEBUG -static-libstdc++ -stdlib=libc++ -static-libstdc++ -fuse-ld=lld -Wl,--color-diagnostics -ffat-lto-objects    -Wl,--gc-sections unittests/LineEditor/CMakeFiles/LineEditorTests.dir/LineEditor.cpp.o -o unittests/LineEditor/LineEditorTests  lib/libLLVMLineEditor.a  lib/libLLVMSupport.a  lib/libLLVMSupport.a  -lpthread  lib/libllvm_gtest_main.a  lib/libllvm_gtest.a  -lpthread  /b/s/w/ir/x/w/libedit_install/lib/libedit.a  lib/libLLVMSupport.a  -lrt  -ldl  -lpthread  -lm  /b/s/w/ir/x/w/zlib_install_target/lib/libz.a  /b/s/w/ir/x/w/zstd_install/lib/libzstd.a  -pthread  lib/libLLVMDemangle.a  -lpthread && :
ld.lld: error: undefined symbol: tgetent
>>> referenced by terminal.c
>>>               terminal.o:(terminal_set) in archive /b/s/w/ir/x/w/libedit_install/lib/libedit.a

ld.lld: error: undefined symbol: tgetflag
>>> referenced by terminal.c
>>>               terminal.o:(terminal_set) in archive /b/s/w/ir/x/w/libedit_install/lib/libedit.a
>>> referenced by terminal.c
>>>               terminal.o:(terminal_set) in archive /b/s/w/ir/x/w/libedit_install/lib/libedit.a
>>> referenced by terminal.c
>>>               terminal.o:(terminal_set) in archive /b/s/w/ir/x/w/libedit_install/lib/libedit.a
>>> referenced 3 more times

ld.lld: error: undefined symbol: tgetnum
>>> referenced by terminal.c
>>>               terminal.o:(terminal_set) in archive /b/s/w/ir/x/w/libedit_install/lib/libedit.a
>>> referenced by terminal.c
>>>               terminal.o:(terminal_set) in archive /b/s/w/ir/x/w/libedit_install/lib/libedit.a

ld.lld: error: undefined symbol: tgetstr
>>> referenced by terminal.c
>>>               terminal.o:(terminal_set) in archive /b/s/w/ir/x/w/libedit_install/lib/libedit.a
>>> referenced by terminal.c
>>>               terminal.o:(terminal_echotc) in archive /b/s/w/ir/x/w/libedit_install/lib/libedit.a

ld.lld: error: undefined symbol: tputs
>>> referenced by terminal.c
>>>               terminal.o:(terminal_move_to_line) in archive /b/s/w/ir/x/w/libedit_install/lib/libedit.a
>>> referenced by terminal.c
>>>               terminal.o:(terminal_move_to_line) in archive /b/s/w/ir/x/w/libedit_install/lib/libedit.a
>>> referenced by terminal.c
>>>               terminal.o:(terminal_move_to_char) in archive /b/s/w/ir/x/w/libedit_install/lib/libedit.a
>>> referenced 16 more times

ld.lld: error: undefined symbol: tgoto
>>> referenced by terminal.c
>>>               terminal.o:(terminal_move_to_line) in archive /b/s/w/ir/x/w/libedit_install/lib/libedit.a
>>> referenced by terminal.c
>>>               terminal.o:(terminal_move_to_char) in archive /b/s/w/ir/x/w/libedit_install/lib/libedit.a
>>> referenced by terminal.c
>>>               terminal.o:(terminal_move_to_char) in archive /b/s/w/ir/x/w/libedit_install/lib/libedit.a
>>> referenced 5 more times
```

If this setup doesn't make use of `pkgconfig` the way to fix this would be to either use a `libedit` that doesn't depend on `tinfo`, or to add `tinfo` as a dependency to the `libedit_install` target. In both cases this would be configuration outside of the LLVM build graph.

The previous `tinfo` dependency in LLVM hid this misconfiguration and happened to satisfy the `libedit` setup by chance.

**Comment by gulfemsavrun** [comment]
Ok, thanks for your analysis @aaronmondal!

**Comment by mysterymath** [comment]
I did some brief investigation on our end. The pkg-config file for libedit includes a private dependency on libncurses, which provides the terminfo functions. The issue here seems to be one uncovered in LLVM's FindLibEdit.cmake. We're building against a static libedit, but that doesn't use the LibEdit_STATIC_LIBRARIES variable that would be aware of the private dependency of libedit on libncurses. We build everything as statically as we can, which is probably why we're the first to notice. @petrhosek mentioned that we've had to deal with similar concerns with ZSTD.

I'll take a look at seeing if there's a straightforward to update FindLibEdit.cmake to handle this case.

**Comment by jimingham** [comment]
This patch has been causing the Darwin bots on GreenDragon to fail consistently since it was submitted.

The problem is that the lldb/unitest/EditLine needs setupterm which comes from libcurses.dylib.  However that was finding its way into this build line for this test, it's no longer doing so on Darwin, so the test fails to compile.  I can fix this by adding `curses` explicitly to the LINK_LIBS for this directory, but that's clearly the wrong way to do it.  I thought LLDB_CURSES_LIBS would be the right thing, but at present that's empty.

The file that uses this setupterm is in Host code (not part of this test) but the flags for building LLDB.framework are correct.  This seems to be specific to this unit test.

**Comment by JDevlieghere** [comment]
`LLDB_CURSES_LIBS` is scoped to lldbCore, which the EditLine unit test isn't linking. If its also necessary in Host, then we should hoist it up and link both libraries against it.

Anyway, that also means my initial assessment was wrong. I looked for the header include but the code in our editline wrapper forward declares `setupterm` which explains why I missed it. Maybe we should reconsider? Anyway, if I cannot figure this out in the next hour or so, I think we should revert this to get our bots green again.

**Comment by Michael137** [comment]
I'm going to revert this for now until since the bots have been red for a while now

**Comment by bernhardkaindl** [comment]
@JDevlieghere, you wrote:

> No objections in the context of LLDB. We don't use terminfo directly (although I think editline does, but that isn't affected by this) and if we want the TUI we depend on curses anyway.

You truly use `libtinfo` directly in LLDB: 
```py
# git grep define_key
lldb/source/Core/IOHandlerCursesGUI.cpp:    define_key("\033[Z", KEY_SHIFT_TAB);
lldb/source/Core/IOHandlerCursesGUI.cpp:    define_key("\033\015", KEY_ALT_ENTER);
# git grep stdscr
lldb/source/Core/IOHandlerCursesGUI.cpp:          ::touchwin(stdscr);
lldb/source/Core/IOHandlerCursesGUI.cpp:      ::touchwin(stdscr);
lldb/source/Core/IOHandlerCursesGUI.cpp:    ::keypad(stdscr, TRUE);
lldb/source/Core/IOHandlerCursesGUI.cpp:      m_window_sp = std::make_shared<Window>("main", stdscr, false);
lldb/source/Core/IOHandlerCursesGUI.cpp:    touchwin(stdscr);
lldb/source/Core/IOHandlerCursesGUI.cpp:      touchwin(stdscr);
lldb/source/Core/IOHandlerCursesGUI.cpp:      touchwin(stdscr);
lldb/source/Core/IOHandlerCursesGUI.cpp:      touchwin(stdscr);
```

```py
# nm -D /usr/lib/x86_64-linux-gnu/libtinfo.so |grep stdscr
00000000000318e0 B stdscr@@NCURSES6_TINFO_5.0.19991023

# grep define_key /usr/lib/x86_64-linux-gnu/lib{ncurses,tinfo}.*
grep: /usr/lib/x86_64-linux-gnu/libtinfo.a: binary file matches
grep: /usr/lib/x86_64-linux-gnu/libtinfo.so: binary file matches
grep: /usr/lib/x86_64-linux-gnu/libtinfo.so.5: binary file matches
grep: /usr/lib/x86_64-linux-gnu/libtinfo.so.5.9: binary file matches
grep: /usr/lib/x86_64-linux-gnu/libtinfo.so.6: binary file matches
grep: /usr/lib/x86_64-linux-gnu/libtinfo.so.6.3: binary file matches
```

When not adding `libtinfo` into the link directly on a https://github.com/spack/spack build using gcc-11.4.0/binutils-2.42, with ncurses-6.5, I'm getting undefined references to those.

**Comment by JDevlieghere** [comment]
What I said was that, to the best of my knowledge, we don't have places in LLDB that rely on `terminfo` but not on `ncruses`. I think that statement still holds true. The assumption behind it was that `ncurses` provides a superset of the functionality provided by `terminfo`. At least on macOS, `ncruses` exports `stdscr` and `define_key`. What you're showing, that doesn't appear to be the case on your platform. It would be reasonable to special case that and link `terminfo` if not all symbols are provided by `ncurses`.

**Comment by bernhardkaindl** [comment]
Thanks @JDevlieghere! Could you add this special case?

The authoritatively established and supported way to link with `ncurses` on most Linux platforms would be to use `pkg-config --libs ncurses` to the `LDFLAGS` for `ncurses` for the given compile target.

**Comment by JDevlieghere** [comment]
> Thanks @JDevlieghere! Could you add this special case?

I'm happy to help but I wouldn't feel comfortable making such a change without being able to reproduce and test it. 
 
> The authoritatively established and supported way to link with `ncurses` on most Linux platforms would be to use `pkg-config --libs ncurses` to the `LDFLAGS` for `ncurses` for the given compile target.

I'm confused, I thought the problem was that we are linking `ncurses` and that's not sufficient because it doesn't export all the symbols. Wouldn't the fix consist of linking `terminfo`, in addition to `ncurses` on the platform you're observing this on? I presume this isn't an issue on all Linux systems as we have bots running Ubuntu that do not have this issue.

**Comment by davide-q** [comment]
Is there a way to revert and rework this PR to avoid issue #101368 which this PR introduced?

**Comment by bernhardkaindl** [comment]
@davide-q: The patch linked from this comment avoids this issue https://github.com/llvm/llvm-project/issues/101368:
https://github.com/spack/spack/pull/46504#issuecomment-2372520318

**Pull request merged**
