### PR TITLE
[TypeProf][InstrFDO]Omit vtable symbols in indexed profiles by default

### PR DESCRIPTION
**Pull request by mingmingl-llvm**
- The indexed iFDO profiles contains compressed vtable names for `llvm-profdata show --show-vtables` debugging usage. An optimized build doesn't need it (and [doesn't decompress the blob](https://github.com/llvm/llvm-project/blob/eac925fb81f26342811ad1765e8f9919628e2254/llvm/include/llvm/ProfileData/InstrProfReader.h#L696-L699)) since optimized binary has the source code and IR to find vtable symbols.
- The motivation is to avoid increasing profile size when it's not necessary.
-  This doesn't change the indexed profile format and thereby doesn't need a version change.

### CODE REVIEW

**Comment by teresajohnson** [comment]
> The indexed iFDO profiles contains compressed vtable names

To clarify, are we currently including both compressed and uncompressed vtable names in the indexed profiles?

**Review by david-xl — COMMENTED** [review]
How much overhead does it add to the indexed profile?

**Comment by minglotus-6** [comment]
> > The indexed iFDO profiles contains compressed vtable names
> 
> To clarify, are we currently including both compressed and uncompressed vtable names in the indexed profiles?

Not really. Either zlib-compressed or non-compressed vtable names are stored, depending on  `compression::zlib::isAvailable` return value around these lines (https://github.com/llvm/llvm-project/blob/fef144cebb378f550ef098d370316554d647f625/llvm/lib/ProfileData/InstrProfWriter.cpp#L809-L814).

`InstrProfWriter::writeVTableNames` ([source](https://github.com/llvm/llvm-project/blob/fef144cebb378f550ef098d370316554d647f625/llvm/lib/ProfileData/InstrProfWriter.cpp#L804C7-L804C12)) will write the vtable payload in the following format
1) length of the payload ([source](https://github.com/llvm/llvm-project/blob/fef144cebb378f550ef098d370316554d647f625/llvm/lib/ProfileData/InstrProfWriter.cpp#L816C18-L819))
2) one `std::string` named `CompressedVTableNames` ([source](https://github.com/llvm/llvm-project/blob/fef144cebb378f550ef098d370316554d647f625/llvm/lib/ProfileData/InstrProfWriter.cpp#L819)).
3) padding ([source](https://github.com/llvm/llvm-project/blob/fef144cebb378f550ef098d370316554d647f625/llvm/lib/ProfileData/InstrProfWriter.cpp#L825-L830); this mostly follow the binary-id [section](https://github.com/llvm/llvm-project/blob/fef144cebb378f550ef098d370316554d647f625/llvm/lib/ProfileData/InstrProfWriter.cpp#L941-L944))

 With this change `--keep-vtable-symbols=true`, the CompressedVTableNames is empty, length is zero and there is no padding. But the indexed profile format remains unchanged.

**Comment by minglotus-6** [comment]
> How much overhead does it add to the indexed profile?

I have a raw profile at hand for a search binary with large ELF size. Its raw profile size is 507M. 

* With `--keep-vtable-symbol=true`, indexed profile `profile.profdata` is 901M.
* With `--keep-vtable-symbol=false`, indexed profie `profile.profdata` is 893M.

So this is ~8M out of ~900M; but something nice to have (e.g., for deployment, and for faster indexed profile generation).

p.s. I'm doing a wider range of testing for `--enable-vtable-value-profiling` so could gather profile size diff for other binaries as a side work.

**Comment by minglotus-6** [comment]
> To clarify, are we currently including both compressed and uncompressed vtable names in the indexed profiles?

I forgot to mention that `LLVM_ENABLE_ZLIB` is by default enabled if zlib is found (https://llvm.org/docs/CMake.html). Our internal toolchains turns this option on and generated compressed names. 

I have seen `DLLVM_ENABLE_ZLIB=0` on some buildbots. IR tests need to `requires: zlib` to be [unsupported](https://llvm.org/docs/CommandGuide/lit.html#test-status-results) on those buildbots.

**Review by david-xl — COMMENTED** [review]
Perhaps make the option default to true initially?

**Comment by teresajohnson** [comment]
> To clarify, are we currently including both compressed and uncompressed vtable names in the indexed profiles?

Nevermind, I misunderstood. We have either compressed or uncompressed names - and with this change we won't emit either (iiuc).

> > How much overhead does it add to the indexed profile?
> 
> I have a raw profile at hand for a search binary with large ELF size. Its raw profile size is 507M.
> 
> * With `--keep-vtable-symbol=true`, indexed profile `profile.profdata` is 901M.
> * With `--keep-vtable-symbol=false`, indexed profie `profile.profdata` is 893M.
> 
> So this is ~8M out of ~900M; but something nice to have (e.g., for deployment, and for faster indexed profile generation).

That's a fairly small decrease, but otoh I don't see a big downside since the names are there in the raw profile which is often available.

**Review by teresajohnson — APPROVED** [review]
lgtm but see if @david-xl still has concerns

**Comment by david-xl** [comment]
no real concerns.

**Review by david-xl — APPROVED** [review]

**Comment by minglotus-6** [comment]
> Perhaps make the option default to true initially?

Hmm, I'm hoping build tools or profile processing tools can pick up `--keep-vtable-symbols=false` naturally to save the need to update them individually. Let me know if there is a scenario or example we'd prefer to override the option in separate changes!
*  With `--keep-vtable-symbols=false`,  there won't be issues when merging old profiles (generated before this change) and new profiles (generated with this change).

> and with this change we won't emit either (iiuc).

Correct!

> That's a fairly small decrease, but otoh I don't see a big downside since the names are there in the raw profile which is often available.

I gathered profiles from 4 other binaries. The decrease is smaller than 1% across binaries.

|binary  |Diff|profile size before (in MB)|profile size after (in MB)|
|--------|----|---------------------------|--------------------------|
|search1 |0.8%|337                        |334                       |
|search2 |0.9%|330                        |327                       |
|database|0.5%|256.7                      |255.3                     |
|network |0.6%|98.4                       |97.8                      |

**Comment by minglotus-6** [comment]
>  Let me know if there is a scenario or example we'd prefer to override the option in separate changes!

I'm going to land this change with `--keep-vtable-symbols=false` after the following tests

With prior released `llvm-profdata` as `cli1`, `llvm-profdata` built with this PR as `cli2`.
* Use`cli2` to generated profiles and use `cli1` to consume (merge, show, overlap) them.
* Use `cli1` to generate profiles and use `cli2` to consume them.

Both ways things work.

**Pull request merged**
