### PR TITLE
[SHT_LLVM_BB_ADDR_MAP] Deprecate SHT_LLVM_BB_ADDR_MAP versions 0 and 1.

### PR DESCRIPTION
**Pull request by rlavaee**
Old versions are stale (more than 9 months old) and can be deprecated from tools and codegen.

### CODE REVIEW

**Review by jh7370 — COMMENTED** [review]
I'll admit to not knowing how this code is used in anger, but it seems wrong to me to drop reading support of the section such that llvm-readobj can't read it anymore, especially as 9 months isn't actually all that long a period of time in my experience (we have codebases containing prebuilt binaries that are many years old, for example). There's also a difference between deprecating and dropping support entirely too, in my mind (the former is more of an announcement that support will be removed in the future). Is the old code causing a real maintenance issue?

**Comment by red1bluelost** [comment]
I think we should either emit a warning or return error when provided an old version so that its easier to tell the reason decode fails or gives an unexpected result.

**Comment by rlavaee** [comment]
> I'll admit to not knowing how this code is used in anger, but it seems wrong to me to drop reading support of the section such that llvm-readobj can't read it anymore, especially as 9 months isn't actually all that long a period of time in my experience (we have codebases containing prebuilt binaries that are many years old, for example). There's also a difference between deprecating and dropping support entirely too, in my mind (the former is more of an announcement that support will be removed in the future). Is the old code causing a real maintenance issue?

I see your concern. For instance debug info requires a much longer support since it's needed to run the binary under gdb.
However, BB_ADDR_MAP is currently only used for profiling, which is only needed during the build. We actually plan to have a 6 month deprecation period to reduce the tech-debt.

**Review by red1bluelost — APPROVED** [review]
LGTM. Thanks for adding the errors. I'm okay with deprecating fully but I wouldn't be opposed to keeping around the decoding for a bit longer if we emit a deprecation warning that it isn't actively unit tested and will be dropped in the future.

**Comment by rlavaee** [comment]
> LGTM. Thanks for adding the errors. I'm okay with deprecating fully but I wouldn't be opposed to keeping around the decoding for a bit longer if we emit a deprecation warning that it isn't actively unit tested and will be dropped in the future.

Thanks for the review. After further consideration, we planned to postpone this deprecation. Please proceed on your PRs. Sorry for the disruption.

**Pull request closed without merging**
