### PR TITLE
[TableGen] Avoid repeated hash lookups (NFC)

### PR DESCRIPTION
**Pull request by kazutakahirata**

### CODE REVIEW

**Review by mshockwave — APPROVED** [review]

**Comment by mshockwave** [comment]
Your patch nerd-sniped me because with your change, _technically_ `InstResults` will store a different value -- the original destination register rather than the one that comes after -- upon running into collision key, since `I.error(...)` won't bail out from the execution. However, I think even the flow won't stop right away with this ill-formed tree pattern instance, it will eventually top at the type inference stage that follows.

**Comment by kazutakahirata** [comment]
> Your patch nerd-sniped me because with your change, _technically_ `InstResults` will store a different value -- the original destination register rather than the one that comes after -- upon running into collision key, since `I.error(...)` won't bail out from the execution. However, I think even the flow won't stop right away with this ill-formed tree pattern instance, it will eventually top at the type inference stage that follows.

Good point!  Let me use `insert_or_assign` instead.  I don't want to introduce subtlety here.

**Comment by kazutakahirata** [comment]
@mshockwave I've updated the patch.  Please take a look.  Thanks!

**Review by mshockwave — APPROVED** [review]
Much better, thanks

**Pull request merged**
