### PR TITLE
[clang] Implement CWG2398 provisional TTP matching to class templates

### PR DESCRIPTION
**Pull request by mizvekov**
This solves some ambuguity introduced in P0522 regarding how template template parameters are partially ordered, and should reduce the negative impact of enabling `-frelaxed-template-template-args` by default.

When performing template argument deduction, we extend the provisional wording introduced in https://github.com/llvm/llvm-project/pull/89807 so it also covers deduction of class templates.

Given the following example:
```C++
template <class T1, class T2 = float> struct A;
template <class T3> struct B;

template <template <class T4> class TT1, class T5> struct B<TT1<T5>>;   // #1
template <class T6, class T7>                      struct B<A<T6, T7>>; // #2

template struct B<A<int>>;
```
Prior to P0522, `#2` was picked. Afterwards, this became ambiguous. This patch restores the pre-P0522 behavior, `#2` is picked again.

This has the beneficial side effect of making the following code valid:
```C++
template<class T, class U> struct A {};
A<int, float> v;
template<template<class> class TT> void f(TT<int>);

// OK: TT picks 'float' as the default argument for the second parameter.
void g() { f(v); }
```

---

Since this changes provisional implementation of CWG2398 which has not been released yet, and already contains a changelog entry, we don't provide a changelog entry here.

### CODE REVIEW

**Review by erichkeane — APPROVED** [review]
Seems reasonable, lgtm.

**Comment by jyknight** [comment]
Heads up: this commit has triggered some weird errors for a compile, but only when clang header modules are enabled. A std::vector, that's built through a large amount of template gunk that definitely involves template template parameter matching, ends up failing vector's "Allocator::value_type must be same type as value_type" static assertion -- the vector's allocator's value_type seems to be some unrelated type. But, only when modules are enabled.

That seems to _probably_ indicate a bug in this commit (presumably related to AST serialization or deserialization?), but I don't have a test-case, and, that's harder to get for issues that only arise with modules enabled...

If this very vague and unhelpful description makes you think "oh, I see where the problem likely is!", then great! But, otherwise, I'll see if I can create a test case...

**Comment by dcci** [comment]
I am seeing something similar in vector (without modules). I'm reducing a test case now.

**Comment by dcci** [comment]
Example error while I reduce:

```
fbcode/third-party-buck/platform010/build/libgcc/include/c++/trunk/bits/stl_vector.h:404:21: error: static assertion failed due to requirement 'is_same<std::basic_string<char, std::char_traits<char>, std::allocator<char>>, quic::Interval<unsigned long, 1>>::value': std::vector must have the same value_type as its allocator
  404 |       static_assert(is_same<typename _Alloc::value_type, _Tp>::value,
      |                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
buck-out/v2/gen/fbcode/21eca57c08ba71f9/quic/common/__interval_set__/buck-headers/quic/common/IntervalSet.h:61:29: note: in instantiation of template class 'std::vector<quic::Interval<unsigned long>>' requested here
   61 | class IntervalSet : private Container<Interval<T, Unit>> {
      |                             ^
buck-out/v2/gen/fbcode/21eca57c08ba71f9/quic/state/__quic_state_machine__/buck-headers/quic/state/QuicStreamManager.h:79:41: note: in instantiation of template class 'quic::IntervalSet<unsigned long, 1, std::vector>' requested here
   79 |   IntervalSet<StreamId, 1, std::vector> streams_;
      |                                         ^
```

**Comment by mizvekov** [comment]
Thanks for the heads up, this does look like a problem. I am reverting it for now.

**Comment by mizvekov** [comment]
> Heads up: this commit has triggered some weird errors for a compile, but only when clang header modules are enabled. 
> That seems to _probably_ indicate a bug in this commit (presumably related to AST serialization or deserialization?), but I don't have a test-case, and, that's harder to get for issues that only arise with modules enabled...

Thanks for the heads-up, James.

Indeed, and it's not only modules, our tooling for reducing test cases is getting less and less effective.

**Comment by mizvekov** [comment]
I figured a reproducer based on your hints:

```C++
template<class T, class U> struct A {};

template<template<class> class TT> auto f(TT<int> a) { return a; }

A<int, float> v1;
A<int, double> v2;

using X = decltype(f(v1));
using Y = decltype(f(v2));
```

Fails with:
```
t.cc:9:20: error: no matching function for call to 'f'
    9 | using Y = decltype(f(v2));
      |                    ^
t.cc:3:41: note: candidate template ignored: deduced type 'A<[...], (default) float>' of 1st parameter does not match adjusted type 'A<[...], double>' of argument [with TT = A]
    3 | template<template<class> class TT> auto f(TT<int> a) { return a; }
      |                                         ^
```

This shows we are not properly canonicalizing the synthesized template declaration.

The problem does not show up with class template partial specializations due to a pre-existing issue, but otherwise this was an oversight on my part.

No need to keep reducing on your end, I already have enough to go with.

**Pull request merged**
