### PR TITLE
[NFC][llvm][support] rename INFINITY in regcomp

### PR DESCRIPTION
**Pull request by daltenty**
since C23 this macro is defined by float.h, which clang implements in it's float.h since #96659 landed.

However, regcomp.c in LLVMSupport happened to define it's own macro with that name, leading to problems when bootstrapping. This change renames the offending macro.

### CODE REVIEW

**Review by xingxue-ibm — APPROVED** [review]
LGTM, thanks!

**Comment by daltenty** [comment]
> ⚠️ C/C++ code formatter, clang-format found issues in your code. ⚠️
> 

This file is from an external source and doesn't follow the clang-format rules, so after some discussion I'm going to ignore this.

**Comment by daltenty** [comment]
The original https://github.com/llvm/llvm-project/pull/96659 is in release/19.x so this is presumable an issue there as well.

/cherry-pick 899f648

**Pull request merged**
