### PR TITLE
[lld] Add ability to have OUTPUT_FORMAT(binary) in linker script for ld.lld

### LINKED ISSUE #87891: Linker script `OUTPUT_FORMAT` command does not support `binary` option
# Background

The `OUTPUT_FORMAT` linker script [command](https://sourceware.org/binutils/docs/ld/Format-Commands.html) is equivalent to the `--oformat` command-line option.

[D23769](https://reviews.llvm.org/D23769) implemented support for `--oformat binary`, which is used for embedded devices that do not support standard executable container formats like ELF.

# Problem

It appears that D23769 only updated the command-line driver and did not update the linker script [parser implementation](https://github.com/llvm/llvm-project/blob/b88a1dd6c75754ace4abe18c8ea16a019f7b5529/lld/ELF/ScriptParser.cpp#L457-L487). So the linker script command `OUTPUT_FORMAT(binary)` is currently unrecognized.

# Proposed Solution

As far as I can tell, the change to the parser implementation should be trivial: check for the special value `"binary"` and set `config->oFormatBinary = true`.

### PR DESCRIPTION
**Pull request by droptopx**
This fixes #87891.

### CODE REVIEW

**Comment by droptopx** [comment]
Hang on while I fix the unintended automatic formatting.

**Comment by droptopx** [comment]
Should be good now!

**Comment by MaskRay** [comment]
This needs a test in `oformat-binary.s`. A different `OUTPUT_FORMAT` might change `oFormatBinary` to false.

**Comment by droptopx** [comment]
> This needs a test in `oformat-binary.s`. A different `OUTPUT_FORMAT` might change `oFormatBinary` to false.

Okay, I want to write test(s) for this but I'm not sure what we need to be testing for here. Why would we want to test for the behaviors of `OUTPUT_FORMAT`s other than `binary`? This PR only changes the behavior of `OUTPUT_FORMAT(binary)`.

Is the test for the case where there are more than one `OUTPUT_FORMAT` directives present in a single file? Does that even make sense for a linker script?

**Comment by MaskRay** [comment]
> > This needs a test in `oformat-binary.s`. A different `OUTPUT_FORMAT` might change `oFormatBinary` to false.
> 
> Okay, I want to write test(s) for this but I'm not sure what we need to be testing for here. Why would we want to test for the behaviors of `OUTPUT_FORMAT`s other than `binary`? This PR only changes the behavior of `OUTPUT_FORMAT(binary)`.
> 
> Is the test for the case where there are more than one `OUTPUT_FORMAT` directives present in a linker script? Does that even make sense for a linker script?

We want to test the behavior when more than one `OUTPUT_FORMAT` command is specified and the interaction with `--oformat=binary` (and when an ELF OUTPUT_FORMAT is specified).

After closer inspection of GNU ld's behavior, I think we probably should  ignore extra OUTPUT_FORMAT commands. #98837

**Comment by droptopx** [comment]
Closing as #98837 has been merged. Thanks.

**Pull request closed without merging**
