### PR TITLE
Reland "mlir/Presburger/MPInt: move into llvm/ADT"

### PR DESCRIPTION
**Pull request by artagnon**
Change: remove guards on debug-printing, to allow Release builds without LLVM_ENABLE_DUMP to pass.

MPInt is an arbitrary-precision integer library that builds on top of APInt, and has a fast-path when the number fits within 64 bits. It was originally written for the Presburger library in MLIR, but seems useful to the LLVM project in general, independently of the Presburger library or MLIR. Hence, move it into LLVM/ADT under the name DynamicAPInt.

This patch is part of a project to move the Presburger library into LLVM.

### CODE REVIEW

**Review by nikic — APPROVED** [review]
LGTM, assuming the removal of the LLVM_ENABLE_DUMP guard is the only substantive change.

**Comment by artagnon** [comment]
FWIW, I tested the original patch on release build, but LLVM_ENABLE_DUMP is apparently an independent option now.

**Review by makslevental — APPROVED** [review]
Builds [passed](https://github.com/makslevental/mlir-wheels/actions/runs/9484934418) (the wasm32 build there has `LLVM_ENABLE_ASSERTIONS=OFF`; the fails there are red herrings).

**Comment by artagnon** [comment]
Thanks for checking. I feel much more confident about landing this big patch now.

**Pull request merged**
