### PR TITLE
[libc++] Properly guard std::filesystem with >= C++17

### PR DESCRIPTION
**Pull request by ldionne**
<filesystem> is a C++17 addition. In C++11 and C++14 modes, we actually have all the code for <filesystem> but it is hidden behind a non-inline namespace __fs so it is not accessible. Instead of doing this unusual dance, just guard the code for filesystem behind a classic C++17 check like we normally do.

### CODE REVIEW

**Comment by philnik777** [comment]
According to https://sourcegraph.com/search?q=context:global+std::__fs::filesystem+-file:__config&patternType=standard&sm=0&groupBy=repo it looks like this hasn't been used a lot, but it's not like nobody ever used this. Maybe we should deprecate things for one release?

**Comment by ldionne** [comment]
@EricWF You probably have more context here?

**Review by EricWF — APPROVED** [review]

**Comment by EricWF** [comment]
I believe this was to allow C++17 symbols to appear when C++17 wasn't always available. I'm fine getting rid of it without deprecation. 

Let's not teach people to touch our private parts.

**Comment by ldionne** [comment]
Note that I'm going to ignore the formatting changes cause I feel they just create confusion if I include them in this patch.

**Review by philnik777 — APPROVED** [review]
Since you both think it's fine to do this without deprecation this is also fine by me. It's always nice to simplify the library a bit.

**Comment by ldionne** [comment]
I considered the risk of breakage here some more, and we're not removing the `std::__fs::filesystem` namespace (since that would be ABI-breaking). So most of these code examples would still work even after this patch, but not if they were trying to use filesystem in C++14. Given that mainline Clang is now using C++17 by default, I think this is unlikely to bite that many people.

**Pull request merged**
