### PR TITLE
[RISCV] Graduate Zicond to non-experimental

### PR DESCRIPTION
**Pull request by asb**
The Zicond extension was ratified in the last few months, with no changes that affect the LLVM implementation. Although there's surely more tuning that could be done about when to select Zicond or not, there are no known correctness issues. Therefore, we should mark support as non-experimental.

### CODE REVIEW

**Comment by wangpc-pp** [comment]
Should we backport this to llvm 18?

**Comment by asb** [comment]
> Should we backport this to llvm 18?

I'd be inclined to do so if there are no objections.

**Review by wangpc-pp — APPROVED** [review]
LGTM.

**Review by preames — APPROVED** [review]
LGTM as well.

**Pull request merged**
