### PR TITLE
[mlir][python] Fix attribute registration in ir.py

### PR DESCRIPTION
**Pull request by eospadov**
This PR fixes attribute registration for `SI8Attr` and `UI8Attr` in `ir.py`.

### CODE REVIEW

**Comment by makslevental** [comment]
I guess you were calling these directly and getting tricked?

**Comment by eospadov** [comment]
> I guess you were calling these directly and getting tricked? Because otherwise this doesn't actually change/fix anything for you?

Yeah and they also happen to break mypy checks since they're re-defining the same function.

**Review by makslevental — APPROVED** [review]
LGTM

**Comment by makslevental** [comment]
Do you have merge permissions? If not I can merge when it's ready.

**Comment by eospadov** [comment]
> Do you have merge permissions? If not I can merge when it's ready.

I do not, please go ahead and merge it @makslevental, thank you!

**Pull request merged**
