### PR TITLE
[OpenMP][USM] Introduces -fopenmp-force-usm flag

### PR DESCRIPTION
**Pull request by jplehr**
This flag forces the compiler to generate code for OpenMP target regions as if the user specified the #pragma omp requires unified_shared_memory in each source file.

The option does not have a -fno-* friend since OpenMP requires the unified_shared_memory clause to be present in all source files. Since this flag does no harm if the clause is present, it can be used in conjunction. My understanding is that USM should not be turned off selectively, hence, no -fno- version.

In favor of https://github.com/llvm/llvm-project/pull/75468, sorry for the noise and confusion.

### CODE REVIEW

**Review by jhuber6 — COMMENTED** [review]
Needs a test. There should be some difference in codegen we can key off of.

**Comment by jplehr** [comment]
Is the approach taken in this approach acceptable as opposed to the header solution I put up earlier?

**Comment by jhuber6** [comment]
> Is the approach taken in this approach acceptable as opposed to the header solution I put up earlier?

Yes, it's pretty much exactly what I had in mind from my suggestion in the last PR. Thanks.

**Comment by jplehr** [comment]
> > Is the approach taken in this approach acceptable as opposed to the header solution I put up earlier?
> 
> Yes, it's pretty much exactly what I had in mind from my suggestion in the last PR. Thanks.

Perfect. I'll go ahead and add lit and runtime tests.

**Comment by jdoerfert** [comment]
Documentation missing as well.

**Comment by jplehr** [comment]
While I add some documentation, I'd appreciate feedback especially on the lit side of things. I would very much like to rename the pretty happy tripple-X workaround for substitution debugging into something sane.

**Review by jhuber6 — APPROVED** [review]

**Comment by jplehr** [comment]
> Automatic zero-copy doesn't work on some of the bbot's. I will have to land this once the lit test harness extension in #77851 re-lands.

Having your work landed would be very helpful indeed.

**Comment by jplehr** [comment]
I just realized that I need to update the clang lit tests, so this is *not ready to land*, but I don't see a button to indicate that.

**Pull request merged**
