### PR TITLE
[NFC][mlir][emitc] fix misspelling in description of emitc.global

### PR DESCRIPTION
**Pull request by EtoAndruwa**
Missing `!` before `emitc.global` was added in the `EmitC.td`.

### CODE REVIEW

**Comment by EtoAndruwa** [comment]
It seems that something wrong in parser of emitc.global due to:

**Comment by EtoAndruwa** [comment]
> It seems that something is wrong in the parser of emitc.global due to:
> 
> > error: expected '>'
> > emitc.global @x : !emitc.array<2xf32> = dense<0.0, 2.0>

Wrong usage of `dense` here. Right example of usage is:
```
emitc.global @myglobal : !emitc.array<2xf32> = dense<4.000000e+00>
// CPP-DEFAULT: float myglobal[2] = {4.000000000e+00f, 4.000000000e+00f};
// CPP-DECLTOP: float myglobal[2] = {4.000000000e+00f, 4.000000000e+00f};
```

**Comment by EtoAndruwa** [comment]
> > It seems that something is wrong in the parser of emitc.global due to:
> > > error: expected '>'
> > > emitc.global @x : !emitc.array<2xf32> = dense<0.0, 2.0>
> 
> Wrong usage of `dense` here. Right example of usage is:
> 
> ```
> emitc.global @myglobal : !emitc.array<2xf32> = dense<4.000000e+00>
> // CPP-DEFAULT: float myglobal[2] = {4.000000000e+00f, 4.000000000e+00f};
> // CPP-DECLTOP: float myglobal[2] = {4.000000000e+00f, 4.000000000e+00f};
> ```

I guess author wanted to get something like:
```
int32_t global_array[3] = {0, 1, 2};
```
Therefore, the right version will be:
```
emitc.global @global_array : !emitc.array<3xi32> = dense<[0, 1, 2]>
```

**Review by simon-camp — APPROVED** [review]
Thanks!

**Review by marbre — APPROVED** [review]
Thanks!

**Pull request merged**
