### PR TITLE
[GlobalISel][AArch64] Legalize G_SPLAT_VECTOR

### PR DESCRIPTION
**Pull request by tschuett**
{nxv8s16, s16} fails to select.
{nxv16s8, s8} no patterns available.

### CODE REVIEW

**Review by davemgreen — COMMENTED** [review]
Could you make sure there is some proper .ll testing too?

**Comment by tschuett** [comment]
For nxv16i8, I could not find patterns.

**Comment by davemgreen** [comment]
Oh I see - it is related to the legal types in SDAG, and the i8/i16 being promoted to i32. We usually have to widen the variable in regbankselect / pre-select, to make sure the patterns can trigger. The other option might be to do it during legalization, but that might not handle h/b fp registers correctly.

Could you change the tests to something that won't eventually turn into another instruction (addimm in this case)? Either by changing the opcode (although that still feels more complex than it needs to be) or just returning the splat value. We will have to start going through extract_elements and adding combines so more will work properly and we can rely on better tests.

**Comment by tschuett** [comment]
This pattern looks fine to select `{nxv8s16, s16} `, but it fails:
```
 def : Pat<(nxv8f16 (splat_vector (f16 FPR16:$src))),
            (DUP_ZZI_H (INSERT_SUBREG (IMPLICIT_DEF), FPR16:$src, hsub), 0)>;
```

**Comment by tschuett** [comment]
For legalization of G_SPLAT_VECTOR, the tests are sufficient. When we add combines, we can extend the tests.

**Review by arsenm — APPROVED** [review]

**Review by davemgreen — COMMENTED** [review]
The tests should still be updated to just return a splat.

**Review by davemgreen — APPROVED** [review]
Thanks for the new tests. LGTM

**Comment by tschuett** [comment]
The mir tests fail in CI, but locally they work.

**Pull request merged**
