### PR TITLE
[aarch64] Add hyperbolic and arc trig intrinsic lowering

### PR DESCRIPTION
**Pull request by farzonl**
## The change(s)
- `VecFuncs.def`: define intrinsic to  sleef/armpl mapping
- `LegalizerHelper.cpp`: add missing `fewerElementsVector` handling for the new trig intrinsics
- `AArch64ISelLowering.cpp`: Add arch64 specializations for lowering like neon instructions
- `AArch64LegalizerInfo.cpp`: Legalize the new trig intrinsics. aarch64 has specail legalization requirments in `AArch64LegalizerInfo.cpp`. If we redirect the clang builtin without handling this we will break the aarch64 compiler

## History
This change is part of an implementation of https://github.com/llvm/llvm-project/issues/87367's investigation on supporting IEEE math operations as intrinsics.
Which was discussed in this RFC:
https://discourse.llvm.org/t/rfc-all-the-math-intrinsics/78294

This change adds wasm lowering cases for `acos`, `asin`, `atan`, `cosh`, `sinh`, and `tanh`.

https://github.com/llvm/llvm-project/issues/70079
https://github.com/llvm/llvm-project/issues/70080
https://github.com/llvm/llvm-project/issues/70081
https://github.com/llvm/llvm-project/issues/70083
https://github.com/llvm/llvm-project/issues/70084
https://github.com/llvm/llvm-project/issues/95966

## Why is aarch64 needed
The last step is to redirect the `acos`, `asin`, `atan`, `cosh`, `sinh`, and `tanh` to  emit the intrinsic. We  can't emit the intrinsic without the intrinsics becoming legal for aarch64 in `AArch64LegalizerInfo.cpp`

### CODE REVIEW

**Comment by farzonl** [comment]
@davemgreen @paschalis-mpeis If you have some time to review, I would appreciate it. Thanks in advance!

**Review by paschalis-mpeis — COMMENTED** [review]
Hey @farzonl ,

Unfortunately I cannot have a strong opinion on Global ISel contributions.

#### Regarding sources I've modified in the past
The below look OK to me:
- additions to `VecFuncs.def`
- all `replace-with-veclib-*`
- LoopVectorize `veclib-intrinsic-calls.ll`

I verified the existence of the symbols used in sources and test files on ArmPL and SLEEF libraries (see list at the bottom).

---

#### Regarding the rest of the sources and tests:
They also look reasonable and similar to existing sources, but I cannot vouch for them.

BTW in `GlobalISel/arm64-irtranslator.ll` other functions have variants for double as well for scalable vectors (float and double). Why this isn't the case for the newly added functions as well?


---

#### Symbos verified in libraries:
```bash
# ARMPL
armpl_vacosq_f64
armpl_vacosq_f32
armpl_svacos_f64_x
armpl_svacos_f32_x

armpl_vasinq_f64
armpl_vasinq_f32
armpl_svasin_f64_x
armpl_svasin_f32_x

armpl_vatanq_f64
armpl_vatanq_f32
armpl_svatan_f64_x
armpl_svatan_f32_x

armpl_vcoshq_f64
armpl_vcoshq_f32
armpl_svcosh_f64_x
armpl_svcosh_f32_x

armpl_vsinhq_f64
armpl_vsinhq_f32
armpl_svsinh_f64_x
armpl_svsinh_f32_x

armpl_vtanhq_f64
armpl_vtanhq_f32
armpl_svtanh_f64_x
armpl_svtanh_f32_x

# SLEEF
## Sleef scalable:
_ZGVsMxv_acos
_ZGVsMxv_acosf

_ZGVsMxv_asin
_ZGVsMxv_asinf

_ZGVsMxv_atan
_ZGVsMxv_atanf

_ZGVsMxv_cosh
_ZGVsMxv_coshf

_ZGVsMxv_sinh
_ZGVsMxv_sinhf

_ZGVsMxv_tanh
_ZGVsMxv_tanhf

## Sleef vector:
_ZGVnN2v_acos
_ZGVnN4v_acosf

_ZGVnN2v_asin
_ZGVnN4v_asinf

_ZGVnN2v_atan
_ZGVnN4v_atanf

_ZGVnN2v_cosh
_ZGVnN4v_coshf

_ZGVnN2v_sinh
_ZGVnN4v_sinhf

_ZGVnN2v_tanh
_ZGVnN4v_tanhf
```

**Comment by farzonl** [comment]
> #### Regarding the rest of the sources and tests:
> They also look reasonable and similar to existing sources, but I cannot vouch for them.
> 
> BTW in `GlobalISel/arm64-irtranslator.ll` other functions have variants for double as well for scalable vectors (float and double). Why this isn't the case for the newly added functions as well?
> 
> #### Symbos verified in libraries:

In  `VecFuncs.def` I only added ARMPL  and SLEEF intrinsic apis if there was an equivalent libcall one that already existed. I'm going for parrity with what existed.

**Review by davemgreen — APPROVED** [review]
The GISel change LGTM. Thanks

**Review by paschalis-mpeis — APPROVED** [review]

**Comment by farzonl** [comment]
Thank you!

**Pull request merged**
