### PR TITLE
[TableGen] Sort matchables depending on predicates.

### PR DESCRIPTION
**Pull request by AlfieRichardsArm**
This change adds alphabetical sorting for matchables in Asm Matching.

There are several cases of matchables that are unambiguous except for different features, for example the Arm Thumb ADC instruction which has multiple ambiguous aliases with different feature sets (see the test failures of https://github.com/llvm/llvm-project/pull/83436 for this failure). 

For Arm especially the order of matching determines the order of the diagnostics produced which can cause unreliable test failures.

### CODE REVIEW

**Comment by AlfieRichardsArm** [comment]
@atanasyan I see you are a contributor to the MIPS backend. This changes the encodings of 2 test cases for MIPS as a different encoding is chosen. Is this okay?

**Comment by kosarev** [comment]
I think adding (another) by-name ordering for matchables is not a good idea. Renaming things should not cause functional changes. I would rather welcome introducing proper means of communicating the intention/expectation of some matchables to be tried before others instead of complicating the situation further by employing ad-hoc workarounds.

Did you try `HasPositionOrder` of the `Instruction` TableGen class?

**Comment by s-barannikov** [comment]
We need to figure out the real cause of non-deterministic behavior rather than masking it, so that we are not surprised in the future when it triggers again in a different place. Usually, such behavior is the consequence of using unstable keys (e.g., pointers) in hashtables.
Can you compare two versions of ARMGenAsmMatcher.inc that cause different behavior? This should help localize the issue.

**Comment by AlfieRichardsArm** [comment]
Yeah I agree the issue is probably actually the sort not being the same on the different builds. And youre right I think relying on the names is a bad idea.

> Can you compare two versions of ARMGenAsmMatcher.inc that cause different behavior? 
I agree I think the real issue is why has this non-determinism creaped in that wasn't here previously. I will have a look at trying to compare these on Monday. It is quite frustrating to debug as it doesn't reliably repreoduce  on my machine.

> Did you try `HasPositionOrder` of the Instruction `TableGen` class?
Ah I hadn't considered this. This would work well. I will abandon this patch and use that if the sort can't be figured out.

**Comment by kosarev** [comment]
> I agree I think the real issue is why has this non-determinism creaped in that wasn't here previously. I will have a look at trying to compare these on Monday. It is quite frustrating to debug as it doesn't reliably repreoduce on my machine.

In AMDGPU we had this kind of ambiguity sitting there for quite a while without noticing: https://github.com/llvm/llvm-project/issues/69256. Wouldn't be surprised if it's the same with other backends.

**Comment by AlfieRichardsArm** [comment]
I'm getting access to a windows machine so I will try work out whats going on.

**Comment by AlfieRichardsArm** [comment]
@s-barannikov here are the versions of the same commit (b1aef251d1a1b25abb36d1f3d6e48e9de22e7513) on windows vs Linux Ubuntu 22.02. I intend to do some investigation as to where this has come.
[ASMComp.zip](https://github.com/llvm/llvm-project/files/14586716/ASMComp.zip)

**Comment by AlfieRichardsArm** [comment]
@s-barannikov I found the bug, its an embarassing one for me unfortunately, Im uploading a new patch to https://github.com/llvm/llvm-project/pull/83587 shortly. I will also be abandoning this PR as it is unnecessary for my change. 

I do think its a bit of an issue how many matchables aren't comparable right now even though they are functionally distinct and think there is an argument for something like this patch in the future, though as @kosarev points out, it should not be based off names.

**Pull request closed without merging**
