### PR TITLE
[Interp] Mark the test unsupported with Asan

### PR DESCRIPTION
**Pull request by vitalybuka**
It's very flaky recently.

10 bulds are OK, then 3 failed:
https://lab.llvm.org/buildbot/#/builders/52/builds/1524
https://lab.llvm.org/buildbot/#/builders/52/builds/1525
https://lab.llvm.org/buildbot/#/builders/52/builds/1526
then 3 OK
https://lab.llvm.org/buildbot/#/builders/52/builds/1531
https://lab.llvm.org/buildbot/#/builders/52/builds/1532
then 2 green again

We need to stop to spam blame list by disabling the test,
and investigate later if Asan is valuable for the test.

Issue #102858

### CODE REVIEW

**Comment by hahnjo** [comment]
Quick question for my understanding: With `spr` we don't get meaningful commit messages anymore? That's quite unfortunate...

**Comment by vitalybuka** [comment]
> Quick question for my understanding: With `spr` we don't get meaningful commit messages anymore? That's quite unfortunate...

Can you please clarify?

**Review by thurstond — APPROVED** [review]

**Review by yronglin — APPROVED** [review]
LGTM

**Comment by hahnjo** [comment]
> > Quick question for my understanding: With `spr` we don't get meaningful commit messages anymore? That's quite unfortunate...
> 
> Can you please clarify?

The commit messages in this PR are `initial version` and `Update const.cpp`, which is totally useless if I came across this in `git log`. I meanwhile remembered that the policy in LLVM is to squash-and-merge, so I guess you can supply a more useful message at that point, but I would still argue that the history deserves better than what is currently in this PR.

**Comment by vitalybuka** [comment]
@hahnjo I believe I explained "Update const.cpp" issue.
So I am going to merge as the that continue to sporadically brake.

**Pull request merged**
