### PR TITLE
[clang][dataflow] Collect local variables referenced within a functio…

### PR DESCRIPTION
**Pull request by bazuzi**
…n/statement.

We don't need these for the same in-tree purposes as the other sets, i.e. for making sure we model these Decls that are declared outside the function, but we have an out-of-tree use for these sets that would benefit from this simple addition and would avoid duplicating so much of this code.

### CODE REVIEW

**Comment by ymand** [comment]
Should we make this flag controlled? Or is the idea that analyses can simply ignore the new `Locals` field?

**Comment by bazuzi** [comment]
The new `Locals` field can be, and is by default, ignored, as the existing uses iterate individually through each of the sets in `ReferencedDecls`.

**Comment by martinboehme** [comment]
> Looks good, but please add a test. Thanks!

+1 on both counts.

**Comment by bazuzi** [comment]
Added a test.

**Review by ymand — APPROVED** [review]

**Pull request merged**
