### PR TITLE
[Clang][RISCV][RVV Intrinsic] Fix codegen redundant intrinsic names

### PR DESCRIPTION
**Pull request by circYuan**
This patch avoids adding redundant vcreate_v intrinsics to the RISCV IntrinsicList.
Since vcreate_v uses LFixedLog2LMUL, I believe we can simply set Log2LMUL to the smallest value (-3) to prevent the creation of redundant vcreate_v instances with the same intrinsic name and prototype in the IntrinsicList when clang creates it.

### CODE REVIEW

**Comment by 4vtomat** [comment]
Since it only reduces about 160 of 54100 intrinsics generated, I have no opinion on this, just left the final decision to others~
But if this PR is finally decided to be merged, please add some comments around the code you added to explain, thanks!

**Review by topperc — APPROVED** [review]
LGTM

**Comment by topperc** [comment]
@circYuan do you need me to commit this for you?

**Comment by circYuan** [comment]
Hi @4vtomat,
thanks for the comment, I have added the comments in the code.

Hi @topperc ,
Yes, please help me commit the patch after the new commit has been checked, many thanks!

**Review by 4vtomat — APPROVED** [review]
Thanks, LGTM~

**Pull request merged**
