### PR TITLE
[SandboxIR][NFC] Move Value class into a separate file

### PR DESCRIPTION
**Pull request by vporpo**

### CODE REVIEW

**Comment by vporpo** [comment]
Rebased.

**Comment by Sterling-Augustine** [comment]
Buildbot failure is real. Probably needs some forward declarations for MSVC like those at the top of Type.h.

Once the build issues are resolved, looks good.

**Comment by vporpo** [comment]
Ah yes, last failure was some other issue. Let me take a look.

**Comment by vporpo** [comment]
I forward declared all classes in the header file and added an `#include <sstream>` in `Value.cpp`. Let's see if it passes.

**Comment by vporpo** [comment]
OK the windows build succeeded :)

**Review by Sterling-Augustine — APPROVED** [review]

**Pull request merged**
