### PR TITLE
[libc++][Android] Disable Android ABI list checking

### PR DESCRIPTION
**Pull request by rprichard**
Issue: https://github.com/llvm/llvm-project/issues/69270

### CODE REVIEW

**Comment by rprichard** [comment]
It wasn't quite clear to me if we should have these ABI lists for Android, so I thought we might leave them out for the moment, https://github.com/llvm/llvm-project/pull/69272#issuecomment-1771823598.

**Comment by ldionne** [comment]
@rprichard I kinda lost track here, but can you please make sure to cross-reference any Phabricator review from the PRs and vice-versa, and also abandon any Phabricator review that you are moving to github PRs?

**Comment by ldionne** [comment]
> It wasn't quite clear to me if we should have these ABI lists for Android, so I thought we might leave them out for the moment, [#69272 (comment)](https://github.com/llvm/llvm-project/pull/69272#issuecomment-1771823598).

You folks want to be ABI stable or not? If you want to be ABI stable, then you should have these ABI lists.

**Comment by rprichard** [comment]
> @rprichard I kinda lost track here, but can you please make sure to cross-reference any Phabricator review from the PRs and vice-versa, and also abandon any Phabricator review that you are moving to github PRs?

Sorry about that. The GitHub commits/PRs all referenced Phabricator reviews where it made sense. Two Phabricator reviews were closed when the PRs merged, and one was still open, so I abandoned it.

 - https://reviews.llvm.org/D139147 (closed)
 - https://reviews.llvm.org/D155271 (closed)
 - https://reviews.llvm.org/D155341 (abandoned)

**Comment by ldionne** [comment]
It's all good, no worries -- I just wanted to make sure but I appreciate that you already took care of everything!

**Review by EricWF — APPROVED** [review]

**Comment by EricWF** [comment]
@ldionne Sorry about the lack of cross references between the old and new patches. That was partially my doing.

This LGTM. Merging.

**Comment by ldionne** [comment]
@EricWF I don't mind the cross references, but please be careful when you merge, we had a discussion started above (https://github.com/llvm/llvm-project/pull/69666#issuecomment-1771930909). I suspect that Android actually does want the ABI testing.

**Pull request merged**
