### PR TITLE
[TargetTransformInfo] Remove `getFlatAddressSpace`

### PR DESCRIPTION
**Pull request by shiltian**
This has been moved to `DataLayout`.

### CODE REVIEW

**Comment by shiltian** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/108787?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#108787** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/108787?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#108786** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/108786?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shiltian and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by arsenm** [comment]
Needs RFC

**Comment by shiltian** [comment]
RFC: https://discourse.llvm.org/t/nfc-remove-getflataddressspace-from-targettransforminfo/81263

**Comment by shiltian** [comment]
The dependent PR has been closed.

**Pull request closed without merging**
