### PR TITLE
[SelectionDAG] NFC: Add target hooks to enable vector coercion in CopyToReg / CopyFromReg

### PR DESCRIPTION
**Pull request by jrbyrnes**
In cases where we are copying vectors across basic block boundaries, we will emit CopyToReg / CopyFromReg pairs. For non-legal vector types, we typically scalarize and legalize each scalar, then emit a CopyTo / CopyFrom for each scalar. However, in some cases, we may be able to pack the vector into fewer registers. As an example, AMDGPU can pack a v4i8 into a single register by treating it as an i32 (rather than four registers, of each type i16). 

This NFC patch introduces the target hooks to implement such functionality.

### CODE REVIEW

**Comment by RKSimon** [comment]
When we get to lowering we see:
```
Type-legalized selection DAG: %bb.0 'f:entry'
SelectionDAG has 15 nodes:
  t0: ch,glue = EntryToken
              t2: i64,ch = CopyFromReg t0, Register:i64 %0
            t5: i32,ch = load<(load (s32) from %ir.b)> t0, t2, undef:i64
          t22: v8i32 = BUILD_VECTOR t5, undef:i32, undef:i32, undef:i32, undef:i32, undef:i32, undef:i32, undef:i32
        t18: v32i8 = bitcast t22
      t19: v32i8 = vector_shuffle<0,0,0,0,0,0,0,0,1,1,1,1,1,1,1,1,2,2,2,2,2,2,2,2,3,3,3,3,3,3,3,3> t18, undef:v32i8
    t12: v4i64 = bitcast t19
  t15: ch,glue = CopyToReg t0, Register:v4i64 $ymm0, t12
  t16: ch = X86ISD::RET_GLUE t15, TargetConstant:i32<0>, Register:v4i64 $ymm0, t15:1
```

**Review by arsenm — COMMENTED** [review]
We might be better off just writing an IR pass to pre-optimize these to legal integers

**Comment by jrbyrnes** [comment]
> We might be better off just writing an IR pass to pre-optimize these to legal integers

I'll look into the details of this

**Comment by jrbyrnes** [comment]
For a demonstration of the issue -- 
https://godbolt.org/z/Y7MhcjGE8

**Comment by arsenm** [comment]
> > We might be better off just writing an IR pass to pre-optimize these to legal integers
> 
> I'll look into the details of this

And by IR pass I mean AMDGPUCodeGenPrepare

**Comment by arsenm** [comment]
Is this still needed?

**Comment by jrbyrnes** [comment]
Abandoning in favor of https://github.com/llvm/llvm-project/pull/66838

**Pull request closed without merging**
