### PR TITLE
Revert "Actually disable the module generation tests."

### PR DESCRIPTION
**Pull request by EricWF**
This reverts commit 0bbada93a559b604797fe57978f3eca5e41edaeb.

The update of Clang in the CI broke due to the new LLVM version naming. It needs to look for the clang 18.1 package instead of 18. Since it couldn't find 18 it used 17 as fallback. This gives ODR violations which caused the output for the module test to be wrong. (It didn't crash which would be a lot more obvious to debug.)

The clang-tidy selection was fixed by https://github.com/llvm/llvm-project/pull/81362. That patch also makes clang-19 work with clang-tidy-19 out of the box.

The time-out have not been addressed; that is a CI issue and not an issue with this test. They run in 200-ish s so they are slow but far below the 1500s threshold. (Due to a dependency in this test it can't be split in multiple tests.)

### CODE REVIEW

**Review by mordante — APPROVED** [review]
Thanks LGTM!

I've manually verified the module test runs and passes with the C++26 build again.

**Comment by philnik777** [comment]
Why is it working again?

**Comment by mordante** [comment]
> Why is it working again?

The update of Clang in the CI broke due to the new LLVM version naming. It needs to look for the clang 18.1 package instead of 18. Since it couldn't find 18 it used 17 as fallback. This gives ODR violations which caused the output for the module test to be wrong. (It didn't crash which would be a lot more obvious to debug.)

The clang-tidy selection was fixed by https://github.com/llvm/llvm-project/pull/81362. That patch also makes clang-19 work with clang-tidy-19 out of the box.

The time-out have not been addressed; that is a CI issue and not an issue with this test. They run in 200-ish s so they are slow but far below the 1500s threshold. (Due to a dependency in this test it can't be split in multiple tests.)

**Comment by philnik777** [comment]
Ah OK. Thanks for the explanation. @EricWF could you put a shortened version into the commit message?

**Pull request merged**
