### PR TITLE
[AArch64] Fix scheduling model issue #96394

### PR DESCRIPTION
**Pull request by david-arm**
The NeoverseZeroMove predicate assumes that the first operand is always an immediate, which isn't always true. For example, it could be a stack offset, etc. This patch fixes that by checking if the operand is an immediate first.

### CODE REVIEW

**Comment by davemgreen** [comment]
Is it possible to add a quick test to make sure we don't hit the same thing again? Otherwise it LGTM

**Comment by david-arm** [comment]
> Is it possible to add a quick test to make sure we don't hit the same thing again? Otherwise it LGTM

Done! I've tried to add the simplest mir file test I could think of and verified it crashes without this patch.

**Review by davemgreen — APPROVED** [review]
Thanks, LGTM

**Review by rj-jesus — APPROVED** [review]
Thanks for fixing this, LGTM!

**Pull request merged**
