### PR TITLE
[libc][arm] add more math.h entrypoints

### PR DESCRIPTION
**Pull request by nickdesaulniers**
In particular, we have internal customers that would like to use nanf and
scalbnf.

The differences between various entrypoint files can be checked via:

    $ comm -3 <(grep libc\.src path/to/entrypoints.txt | sort) \
       <(grep libc\.src path/to/other/entrypoints.txt | sort)

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
oh, I should probably add these to the baremetal targets as well?

**Review by lntue — COMMENTED** [review]
Can you also update the availability in the math status page at https://github.com/llvm/llvm-project/blob/main/libc/docs/math/index.rst#L111 ?

Thanks,

**Comment by nickdesaulniers** [comment]
Testing this on the buildbot itself, I observe the following error during cmake configuration. Any idea what I'm missing?
```
CMake Error at /llvm/ndesaulniers/llvm-project/libc/cmake/modules/LLVMLibCObjectRules.cmake:672 (add_library):
  Cannot find source file:

    dummy_srcs
Call Stack (most recent call first):
  /llvm/ndesaulniers/llvm-project/libc/cmake/modules/LLVMLibCObjectRules.cmake:802 (create_entrypoint_object)
  /llvm/ndesaulniers/llvm-project/libc/cmake/modules/LLVMLibCObjectRules.cmake:880 (expand_flags_for_entrypoint_object)
  /llvm/ndesaulniers/llvm-project/libc/src/math/CMakeLists.txt:48 (add_entrypoint_object)
  /llvm/ndesaulniers/llvm-project/libc/src/math/CMakeLists.txt:85 (add_math_entrypoint_object)


CMake Error: CMake can not determine linker language for target: libc.src.math.cos.__internal__
CMake Error: CMake can not determine linker language for target: libc.src.math.cos
CMake Error: CMake can not determine linker language for target: libc.src.math.sin.__internal__
CMake Error: CMake can not determine linker language for target: libc.src.math.sin
CMake Error: CMake can not determine linker language for target: libc.src.math.tan.__internal__
CMake Error: CMake can not determine linker language for target: libc.src.math.tan
...
```

**Comment by nickdesaulniers** [comment]
ah, looks like we don't have implementations in libc/src/math/generic/ for `cos`, `sin`, and `tan`.

**Comment by nickdesaulniers** [comment]
> ah, looks like we don't have implementations in libc/src/math/generic/ for cos, sin, and tan. I can comment these out for now, and work on implementations.

With those commented out, the ninja target `libc-math-unittests` passes on the 32b arm build bot.

**Comment by nickdesaulniers** [comment]
> Can you also update the availability in the math status page at https://github.com/llvm/llvm-project/blob/main/libc/docs/math/index.rst#L111 ?

done in https://github.com/llvm/llvm-project/pull/77839/commits/c1fd723d6fb1e26eb25e35a8a707c9526d4869da PTAL

> oh, I should probably add these to the baremetal targets as well?

TODO

**Review by lntue — APPROVED** [review]

**Pull request merged**
