### PR TITLE
[RISCV] Support rv{32, 64}e in the compiler builtins

### PR DESCRIPTION
**Pull request by xermicus**
Register spills (save/restore) in RISC-V embedded work differently because there are less registers and different stack alignment.

[GCC equivalent ](https://github.com/gcc-mirror/gcc/blob/master/libgcc/config/riscv/save-restore.S#L298C16-L336)

Follow up from #76777.

CC @koute @wangpc-pp

### CODE REVIEW

**Review by wangpc-pp — APPROVED** [review]
LGTM.
@koute Do you have any comments?

**Review by koute — APPROVED** [review]
@xermicus Thanks for the PR! I was meaning to do this myself but it ended up being on the backburner. (:

LGTM

**Review by kito-cheng — APPROVED** [review]
LGTM :)

**Comment by xermicus** [comment]
@wangpc-pp thanks for merging! Should this be backported to `release/18.x`?

**Comment by wangpc-pp** [comment]
> @wangpc-pp thanks for merging! Should this be backported to `release/18.x`?

Yeah, I think so! We have supported RVE in 18.x, but it isn't fully supported without this change.

**Comment by xermicus** [comment]
Excellent! I agree

**Pull request merged**
