### PR TITLE
[clang] Make sure the same UsingType is searched and inserted

### PR DESCRIPTION
**Pull request by apolloww**
When creating a new UsingType, the underlying type may change if it is a declaration. This creates an inconsistency between the type searched and type created. Update member and non-member Profile functions so that they return the same ID.

### CODE REVIEW

**Comment by apolloww** [comment]
We saw a huge build speed regression from internal codebase when migrating to clang-17 triggered by this issue. The search for the same `UsingType` always ends up with "not found" and the folding set `UsingTypes` contains lots of duplicated notes.  

This is a quick fix I come up with. Feel free to propose a better one because I don't work in clang front end often. If it looks good, I'll try to add a test case.

**Comment by mizvekov** [comment]
The change is correct. The problem is subtle though. It comes from the difference in behavior between the member and non-member Profile functions.

I think we could do better instead with a change which makes it harder to trip on this.

I think a simplification like this should work (untested):
```
diff --git a/clang/include/clang/AST/Type.h b/clang/include/clang/AST/Type.h
index ea425791fc97..3d411051084c 100644
--- a/clang/include/clang/AST/Type.h
+++ b/clang/include/clang/AST/Type.h
@@ -4729,13 +4729,12 @@ public:
   bool typeMatchesDecl() const { return !UsingBits.hasTypeDifferentFromDecl; }

   void Profile(llvm::FoldingSetNodeID &ID) {
-    Profile(ID, Found, typeMatchesDecl() ? QualType() : getUnderlyingType());
+    Profile(ID, Found, getUnderlyingType());
   }
   static void Profile(llvm::FoldingSetNodeID &ID, const UsingShadowDecl *Found,
                       QualType Underlying) {
     ID.AddPointer(Found);
-    if (!Underlying.isNull())
-      Underlying.Profile(ID);
+    Underlying.Profile(ID);
   }
   static bool classof(const Type *T) { return T->getTypeClass() == Using; }
 };
```

**Comment by apolloww** [comment]
> The change is correct. The problem is subtle though. It comes from the difference in behavior between the member and non-member Profile functions.
> 
> I think we could do better instead with a change which makes it harder to trip on this.
> 
> I think a simplification like this should work (untested):
> 
> ```
> diff --git a/clang/include/clang/AST/Type.h b/clang/include/clang/AST/Type.h
> index ea425791fc97..3d411051084c 100644
> --- a/clang/include/clang/AST/Type.h
> +++ b/clang/include/clang/AST/Type.h
> @@ -4729,13 +4729,12 @@ public:
>    bool typeMatchesDecl() const { return !UsingBits.hasTypeDifferentFromDecl; }
> 
>    void Profile(llvm::FoldingSetNodeID &ID) {
> -    Profile(ID, Found, typeMatchesDecl() ? QualType() : getUnderlyingType());
> +    Profile(ID, Found, getUnderlyingType());
>    }
>    static void Profile(llvm::FoldingSetNodeID &ID, const UsingShadowDecl *Found,
>                        QualType Underlying) {
>      ID.AddPointer(Found);
> -    if (!Underlying.isNull())
> -      Underlying.Profile(ID);
> +    Underlying.Profile(ID);
>    }
>    static bool classof(const Type *T) { return T->getTypeClass() == Using; }
>  };
> ```

Thanks. This works and looks better.

**Comment by mizvekov** [comment]
> Wonder what test should I add here. This only affects the content of the internal folding set so we always create new types but result is still correct.

One possibility is doing an AST test, there are some examples in there that show how you can test two different AST nodes have the same address.

The best here would be some kind of performance regression test. We don't have anything like that per-se in the test suite unfortunately.
But if you can isolate a good test case, you can make it a normal regression test, which with the fix is still within CI limits of time and space, but which pushes much farther out without the fix. This would not be without precedent, there already exists tests like that.

**Comment by apolloww** [comment]
Thanks. Added test case.

**Comment by mizvekov** [comment]
LGTM.

Thanks!

**Review by mizvekov — APPROVED** [review]

**Pull request merged**
