### PR TITLE
[SystemZ] Remove high inlining threshold multiplier.

### PR DESCRIPTION
**Pull request by JonPsson1**
Due to recently reported problems with having the inlining threshold multiplier set fairly high (x3), this patch attempts to address the regressions seen after removing it.

- The imagick regression needs continued activation of the existing handling for callees where an argument is used as a memcpy source. So with the multiplier set to 1, this gets a greater increment and the functions are still inlined.

- perl: I found two functions that needed inlining that both access the same global many times which the caller also does. It seemed like a reasonable heuristic for inlining which was added after some various experiments.

- povray: There is an important function which is accessing an Alloca of the caller multiple times. A similar heuristic is added for this case as with the global variables.

Results:

I tried this with both a multiplier of x1, and also x2. It seems that over all benchmarks, patch with x2 multplier gives best performance, but patch with x1 multiplier is still better than main with 2x multiplier.

```
Code size
Multiplier vs x3 (main)        main/x2         main/x1  patch/x2      patch/x1

./i500.perlbench_r      	 -7.4%   	-14.6%	   -6.2%   	-13.4%
./i505.mcf_r            	 +0.0%    	 +0.0%	   +0.0%    	 +0.0%
./i523.xalancbmk_r      	 -6.6%   	-11.1%	   -5.3%   	-10.5%
./i531.deepsjeng_r      	 +0.1%   	 -2.8%	   +0.1%   	 -2.8%
./i502.gcc_r            	 -5.4%   	-13.6%	   -3.4%   	-12.6%
./i520.omnetpp_r        	 -4.0%   	 -9.7%	   -2.7%   	 -8.7%
./i525.x264_r           	 -3.8%   	-12.3%	   +2.9%   	 -8.5%
./i541.leela_r          	 -1.0%   	 -9.1%	  +15.7%  	 +6.2%  *
./i557.xz_r             	 -3.1%   	 -6.2%	   -1.6%   	 -4.6%
./f507.cactuBSSN_r      	 -1.4%   	 -3.3%	   -0.7%   	 -2.9%
./f508.namd_r           	-21.8%  	-25.2%	  -21.8%  	-25.2%
./f510.parest_r         	 -3.4%   	-10.2%	   +3.1%   	 -8.8%
./f511.povray_r         	-12.5%  	-16.2%	   -5.9%   	-14.0%
./f519.lbm_r            	 +0.0%   	 +0.0%	   +0.0%   	 +0.0%
./f521.wrf_r            	 -0.0%   	 -0.2%	   -0.0%   	 -0.2%
./f526.blender_r        	 -2.5%   	 -6.5%	   -1.4%   	 -6.1%
./f527.cam4_r           	 -0.0%   	 -0.1%	   +0.0%   	 -0.1%
./f538.imagick_r        	 -2.0%   	 -5.2%	   -1.8%   	 -4.7%
./f544.nab_r            	 -6.1%   	-13.4%	   -4.9%   	-13.4%
```
Looks mostly the same with the patch applied, but leela is gaining in code size.

```
Runtime vs x3 (main)           main/x2          main/x1  patch/x2     patch/x1

f538.imagick_r                     +9%              +9%        -             -       
i500.perlbench_r                   +2%              +6%      +2%           +2%
f511.povray_r                        -              +4%      -1%         +0.5%       
f526.blender_r                     +2%              +4%      +3%           +2%
i541.leela_r                     +0.5%              +2%        -         +2.5%
i505.mcf_r                       -2.5%              -1%    -2.5%           -1%
...
```

Regarding the reported compiler regression, adjusting the multiplier still works also with the
patch applied (similar numbers as seen before w/out patch):

```
Patch, with InliningThresholdMultiplier = 1:

/usr/bin/time -v ./bin/opt -mtriple=systemz-unknown -mcpu=z16 -O3 -disable-output ./bad-42752cbe095.bc
        User time (seconds): 4.84
        Maximum resident set size (kbytes): 128208
        Average resident set size (kbytes): 0

Patch, with InliningThresholdMultiplier = 2:

/usr/bin/time -v ./bin/opt -mtriple=systemz-unknown -mcpu=z16 -O3 -disable-output ./bad-42752cbe095.bc
        User time (seconds): 9.35
        Maximum resident set size (kbytes): 160492
        Average resident set size (kbytes): 0

```

### CODE REVIEW

**Comment by JonPsson1** [comment]
Continuing from #94612

**Comment by JonPsson1** [comment]
Tried patch/x2 (see table above), with adjustments for accesses (GV/Alloca) of 500 instead of 1000, which was similar in performance as with 1000, except that the big code increase in leela nearly all went away.

**Comment by JonPsson1** [comment]
Rebase and finalization in the direction of removing the multiplier entirely.

**Comment by uweigand** [comment]
This LGTM and should be OK to commit with the formatting issues fixed (and ideally we've have re-confirmed the performance results).

**Review by uweigand — APPROVED** [review]
LGTM

**Pull request merged**
