### PR TITLE
[libc++][NFC] Replace _LIBCPP_NORETURN and TEST_NORETURN with [[noreturn]]

### PR DESCRIPTION
**Pull request by philnik777**
`[[__noreturn__]]` is now always available, so we can simply use the attribute directly instead of through a macro.

### CODE REVIEW

**Comment by ldionne** [comment]
Do you still want to pursue this?

**Comment by philnik777** [comment]
Yes, but it has to wait until AppleClang supports attributes in C++03.

**Review by EricWF — APPROVED** [review]

**Comment by EricWF** [comment]
> Yes, but it has to wait until AppleClang supports attributes in C++03.

When will that happen?

**Comment by philnik777** [comment]
With the next AppleClang release in September or so.

**Pull request merged**
