### PR TITLE
Don't build MLIRExecutionEngineShared on Windows

### PR DESCRIPTION
**Pull request by Zentrik**
It doesn't currently build on windows, see https://github.com/llvm/llvm-project/issues/106859.

### CODE REVIEW

**Comment by Zentrik** [comment]
@mstorsjo does this look good to you?

**Comment by giordano** [comment]
Gentle bump to get this reviewed :slightly_smiling_face:

**Comment by Dinistro** [comment]
Sorry for not getting back to you, this was somehow lost in my notifications. This seems reasonable, but maybe add acomment that the underlying issue is unclear.

**Comment by Zentrik** [comment]
Done, if you're happy with this could you merge it as well (I don't have commit rights)

**Comment by Dinistro** [comment]
> Gentle bump to get this reviewed 🙂

Please request review in the future. I did not get any notification on this until you guys pinged me explicitly.

**Review by Dinistro — APPROVED** [review]
LGTM as a workaround.

**Comment by Zentrik** [comment]
> Please request review in the future. I did not get any notification on this until you guys pinged me explicitly.

Unfortunately, I don't seem to have those rights either but no worries.

**Pull request merged**
