### PR TITLE
[llvm] Remove the Legacy PM Hello example

### PR DESCRIPTION
**Pull request by banach-space**
The Legacy PM was deprecated for the optimization pipeline in LLVM 14
[1] (the support was removed altogether in the following release). This
patch removes the original Hello example that was introduced to
illustrate the Legacy PM. The Hello example no longer works and hence is
deleted. The corresponding documentation is also removed.

Note, Hello example for the new PM is located in
  * llvm/lib/Transforms/Utils/HelloWorld.cpp
  
and documented in
  * WritingAnLLVMNewPMPass.rst.

[1] https://releases.llvm.org/14.0.0/docs/ReleaseNotes.html#changes-to-the-llvm-ir

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
You also need to remove the use of this pass (for testing purposes) from clang-tools-extra.

**Comment by banach-space** [comment]
> You also need to remove the use of this pass (for testing purposes) from clang-tools-extra.

Done, thanks!

I don't understand why CI still fails:
```bash
Total Discovered Tests: 60135
--
  | Skipped          :    15 (0.02%)
  | Unsupported      :  1005 (1.67%)
  | Passed           : 58946 (98.02%)
  | Expectedly Failed:   169 (0.28%)
  | ninja: build stopped: cannot make progress due to previous errors.
  | + show-stats
  | + mkdir -p artifacts
  | + ccache --print-stats
  | 🚨 Error: The command exited with status 1
```

Can you see the actual failure? Looks like all tests passed, right?

**Comment by dtcxzyw** [comment]
> > You also need to remove the use of this pass (for testing purposes) from clang-tools-extra.
> 
> Done, thanks!
> 
> I don't understand why CI still fails:
> 
> ```shell
> Total Discovered Tests: 60135
> --
>   | Skipped          :    15 (0.02%)
>   | Unsupported      :  1005 (1.67%)
>   | Passed           : 58946 (98.02%)
>   | Expectedly Failed:   169 (0.28%)
>   | ninja: build stopped: cannot make progress due to previous errors.
>   | + show-stats
>   | + mkdir -p artifacts
>   | + ccache --print-stats
>   | 🚨 Error: The command exited with status 1
> ```
> 
> Can you see the actual failure? Looks like all tests passed, right?

It is caused by libc/lldb test failures. Don't worry :)

**Review by nikic — APPROVED** [review]
LGTM

**Pull request merged**
