### PR TITLE
[AArch64] Enable cmp + csel fusion for Neoverse V2

### PR DESCRIPTION
**Pull request by mingmingl-llvm**
According to _4.11 instruction fusion section_ in Neoverse V2 software optimization guide [1], neoverse v2 fuses the following patterns
1. CMP/CMN (immediate) + B.cond
2. CMP/CMN (register) + B.cond
3. CMP + CSEL
4. CMP + CSET

LLVM supports `cmp + csel` at this [place](https://github.com/llvm/llvm-project/blob/3d361b225fe89ce1d8c93639f27d689082bd8dad/llvm/lib/Target/AArch64/AArch64MacroFusion.cpp#L468-L469), so enabled it for neoverse v2.

Pattern 1 is tracked in https://github.com/llvm/llvm-project/pull/90608.

[1] https://developer.arm.com/documentation/pjdoc466751330-593177/latest/

### CODE REVIEW

**Comment by dc03-work** [comment]
Related: https://github.com/llvm/llvm-project/pull/90608

**Comment by minglotus-6** [comment]
> Related: #90608

thanks for the pointer! I updated this PR to `cmp + csel`  and will discuss `cmp + bcc` in https://github.com/llvm/llvm-project/pull/90608

**Comment by minglotus-6** [comment]
Adding a few more reviewers from https://github.com/llvm/llvm-project/pull/90608

One colleague and I are planning to run some microbenchmarks (including https://github.com/google/fleetbench) and one internal service (with FDO on) to evaluate both `cmp + csel` and `cmp + bcc` (already tracked in https://github.com/llvm/llvm-project/pull/90608). Meanwhile, please let us know if there are known reasons that `cmp + csel` isn't enabled in the first place, thanks!

**Comment by davemgreen** [comment]
> One colleague and I are planning to run some microbenchmarks (including https://github.com/google/fleetbench) and one internal service (with FDO on) to evaluate both cmp + csel and cmp + bcc (already tracked in https://github.com/llvm/llvm-project/pull/90608). Meanwhile, please let us know if there are known reasons that cmp + csel isn't enabled in the first place, thanks!

I would be interested in any benchmark results you get. Yes I believe the reasons are much the same as #90608 - this makes a lot of sense on paper but sometimes LLVM's implementation of fusion is a bit too strong and can lead to problems in practice. Or it might just be noise.

Can you add a test case of some sort too?

**Comment by minglotus-6** [comment]
Overdue update:
1. Perf testing for this change gives small (<0.5%) ups and downs over multiple benchmarks, and looks mostly noise since run-to-run variance is high (with or without [random interleaved](https://github.com/google/benchmark/blob/main/docs/random_interleaving.md) the benchmark instances). Repeating the test flow for `cmp + bcc` pattern (enabled in https://github.com/llvm/llvm-project/pull/90608) does give ~1% ~ 2% improvements for [compression](https://github.com/llvm/llvm-project/pull/90608) and pretty significant (~up to 17%) wins for libc workload.
2. I didn't have bandwidth to track down how often compiler fusion kicked in. Luckily another colleague studied op fusion patterns using DynamoRIO memtraces. The traces are from real jobs or spec, and the study shows `cmp+bcc` pattern more common than `cmp + csel` pattern.

I'll close this PR for now.

**Pull request closed without merging**
