### PR TITLE
[libc] Allow time conversions to compile on bare metal

### LINKED ISSUE #85556: `src/time/time_utils.h` unconditionally uses `EOVERFLOW`
Including `time.h` entrypoints such as `asctime`, `gmtime` or `mktime` results in a compile error:
```
In file included from /usr/local/google/home/phosek/llvm/llvm-project/libc/src/time/asctime.cpp:11:
/usr/local/google/home/phosek/llvm/llvm-project/libc/src/time/time_utils.h:94:16: error: use of undeclared identifier 'EOVERFLOW'                                                                                    
   94 |   libc_errno = EOVERFLOW;                                                                                                                                                                                    
      |                ^                                                                                  
1 error generated.
```
This is because `src/time/time_utils.h` [unconditionally uses `EOVERFLOW`](https://github.com/llvm/llvm-project/blob/89b7b3b9952210fbd9bd0db95385bfed69ffc7a3/libc/src/time/time_utils.h#L94) which is only defined in POSIX and not in C standard, but we're trying to avoid including POSIX in baremetal environments. More generally, I don't think that functions defined by the C standard should have unconditional dependencies on POSIX.

CC @michaelrj-google

### PR DESCRIPTION
**Pull request by statham-arm**
The `<time.h>` functions `asctime`, `gmtime`, `mktime` and their `_r` variants are purely computational functions which convert between well defined time representations and/or strings. There's no reason these shouldn't be available in bare-metal builds of the library as well as hosted ones: even if the library has no way to find out the time in POSIX format, it might still see POSIX-style `time_t` values in input data (e.g. network protocols) and need to interpret them.

The only obstacle to this was that the `out_of_range()` helper function set `errno` to `EOVERFLOW`, which fails in a bare-metal build because the extra POSIX error values aren't defined, including `EOVERFLOW`. So I've made that assignment conditional on `EOVERFLOW` being defined.

-------------------------

Fixes https://github.com/llvm/llvm-project/issues/85556

### CODE REVIEW

**Comment by petrhosek** [comment]
Can you also include these in the `riscv` baremetal entrypoints? Can you include "fixes #85556" in the description?

**Comment by statham-arm** [comment]
> Can you also include these in the `riscv` baremetal entrypoints?

Done, in the followup commit I just pushed.

> Can you include "fixes #85556" in the description?

I can try, but I don't think I've had to do that before in this repository! In Github repos that don't enforce squash-and-merge, I'd do it by force-pushing the PR branch. But here I don't know whether I need to do that, or if editing the PR description is enough. If you know which of those will work, please let me know. Otherwise I'll do my best, and manually close the bug afterwards if it doesn't do the right thing.

**Comment by petrhosek** [comment]
> > Can you also include these in the `riscv` baremetal entrypoints?
> 
> Done, in the followup commit I just pushed.
> 
> > Can you include "fixes #85556" in the description?
> 
> I can try, but I don't think I've had to do that before in this repository! In Github repos that don't enforce squash-and-merge, I'd do it by force-pushing the PR branch. But here I don't know whether I need to do that, or if editing the PR description is enough. If you know which of those will work, please let me know. Otherwise I'll do my best, and manually close the bug afterwards if it doesn't do the right thing.

You can just add it to the PR description, GitHub will pick it up.

**Review by petrhosek — APPROVED** [review]

**Review by michaelrj-google — APPROVED** [review]
LGTM

**Comment by SchrodingerZhu** [comment]
I have added issue link for you. Feel free to adjust in any way you want.

**Pull request merged**
