### PR TITLE
[RISCV][ISel] Remove redundant vmerge for vwsub(u).wv.

### PR DESCRIPTION
**Pull request by sun-jacobi**
Extend #78403 and #80079 to support `vwsub.wv` and `vwsubu.wv`.

## Code
```
define <8 x i64> @vwsub_wv_mask_v8i32(<8 x i32> %x, <8 x i64> %y) {
    %mask = icmp slt <8 x i32> %x, <i32 42, i32 42, i32 42, i32 42, i32 42, i32 42, i32 42, i32 42>
    %a = select <8 x i1> %mask, <8 x i32> %x, <8 x i32> zeroinitializer
    %sa = sext <8 x i32> %a to <8 x i64>
    %ret = sub <8 x i64> %y, %sa
    ret <8 x i64> %ret
}
```

## Before this patch
[Compiler Explorer](https://godbolt.org/z/qh31f5WWa)
```
vwsub_wv_mask_v8i32:
        li      a0, 42
        vsetivli        zero, 8, e32, m2, ta, ma
        vmslt.vx        v0, v8, a0
        vmv.v.i v10, 0
        vmerge.vvm      v16, v10, v8, v0
        vwsub.wv        v8, v12, v16
        ret
```

## After this patch
```
vwsub_wv_mask_v8i32:
        li a0, 42
        vsetivli zero, 8, e32, m2, ta, ma
        vmslt.vx v0, v8, a0
        vsetvli zero, zero, e32, m2, tu, mu
        vwsub.wv v12, v12, v8, v0.t
        vmv4r.v v8, v12
        ret
```

### CODE REVIEW

**Review by lukel97 — APPROVED** [review]
LGTM. For a future patch, could we generalize this with `llvm::isNeutralConstant` so we can handle vwmul too?

**Comment by sun-jacobi** [comment]
> LGTM. For a future patch, could we generalize this with `llvm::isNeutralConstant` so we can handle vwmul too?

Sound great! Thank you.

**Comment by topperc** [comment]
> LGTM. For a future patch, could we generalize this with `llvm::isNeutralConstant` so we can handle vwmul too?

Isn't this patch for .wv instructions? There is no vwmul.wv.

**Comment by sun-jacobi** [comment]
> > LGTM. For a future patch, could we generalize this with `llvm::isNeutralConstant` so we can handle vwmul too?
> 
> Isn't this patch for .wv instructions? There is no vwmul.wv.

oops, you are right. Thanks

**Pull request merged**
