### PR TITLE
[X86, CodeGen] Add a pattern in PreprocessISelDAG.

### LINKED ISSUE #85681: [CodeGen] x86_64 unable to select `X86ISD::VSHLV`/`X86ISD::VSRLV` on v32i1
# Reproduction

https://godbolt.org/z/d4YWMP6cT

Same problem with emeraldrapids, sapphirerapids, or znver4.

@phoebewang Is this a bug or misuse? If it is a bug, I can help fix it.

### PR DESCRIPTION
**Pull request by DataCorrupted**
`%c = shl <X x i1> %a, %b -> %c = %a`
As discussed in #85681, this pattern is added to avoid cannot selection error. Since shift one is either identical or UB, we consider it as identical and replace all uses of %c with %a.

Tests for shl, ashr, lshr are added.
This fixes #85681.

### CODE REVIEW

**Comment by topperc** [comment]
Why not do this in generic DAGCombine?

**Comment by RKSimon** [comment]
SimplifyShift would be the best place to handle this.

I had almost finished a patch for this, why didn't you assign the ticket?

**Comment by DataCorrupted** [comment]
> SimplifyShift would be the best place to handle this.
> 
> I had almost finished a patch for this, why didn't you assign the ticket?

Cool, thanks! I just assigned it to you. Shall I close this PR?

**Comment by DataCorrupted** [comment]
> Why not do this in generic DAGCombine?
> 
> Or in getNode. I think we already special case i1 vectors for some operations.
> 
> Or make shifts of vXi1 vectors Expand which will cause them to scalarize.

I didn't want to deal with (potential) side effects on other arch, they can be messy if many tests changed :(
But now that @RKSimon is on it, we should have things fixed in generic DAGCombine soon.

**Comment by DataCorrupted** [comment]
> why didn't you assign the ticket?

Oh, you mean assign it in the issue... I missed that, I'm pretty new to this GitHub workflow, will do in the future.

**Pull request closed without merging**
