### PR TITLE
[InstCombine] Update BranchProbabilityAnalysis cache result

### PR DESCRIPTION
**Pull request by HaohaiWen**
InstCombine may invert branch condition and profile metadata. In such
case, BranchProbabilityAnalysis should also be updated.

### CODE REVIEW

**Comment by HaohaiWen** [comment]
Add test in #86469

**Review by williamweixiao — APPROVED** [review]
LGTM.

**Review by nikic — CHANGES_REQUESTED** [review]
The change InstCombine does to the CFG is trivial -- can we update the analysis instead?

**Comment by WenleiHe** [comment]
> > The change InstCombine does to the CFG is trivial -- can we update the analysis instead?
> 
> I'm afraid that's not easy... We many need to check & update cached BranchProbabilityAnalysis in all callsite of BranchInst.swapSuccessors() or similar operation on SwitchInst, JumpTable...

Can we use `swapSuccEdgesProbabilities` of BPI to update for inverted branches? There aren't many callsites for `swapSuccessors`

**Comment by HaohaiWen** [comment]
> > > The change InstCombine does to the CFG is trivial -- can we update the analysis instead?
> > 
> > 
> > I'm afraid that's not easy... We many need to check & update cached BranchProbabilityAnalysis in all callsite of BranchInst.swapSuccessors() or similar operation on SwitchInst, JumpTable...
> 
> Can we use `swapSuccEdgesProbabilities` of BPI to update for inverted branches? There aren't many callsites for `swapSuccessors`

Yes we can, also swapValue for SelectInst. There're may be some places where setSuccessor was used and we may need to update them all....

**Review by nikic — APPROVED** [review]
LG

**Pull request merged**
