### PR TITLE
[AArch64] - cannot build from release/18.x

### PR DESCRIPTION
**Pull request by catull**
Ran into the same problem reported in the mailing list at https://www.mail-archive.com/llvm-bugs@lists.llvm.org/msg73342.html.

The PR fixes the build.

### CODE REVIEW

**Review by lntue — APPROVED** [review]

**Comment by overmighty** [comment]
We could just cherry-pick commit be8b2d1ea54f964603b89ab9d4dfad26afebb347 instead.

**Comment by overmighty** [comment]
I'm not familiar with backporting fixes to release branches. I think LLVM has some special infrastructure for this where we can make a bot account open a PR for us.

**Comment by catull** [comment]
@overmighty I am not so sure @MosheBerman's fix does it.

You need both values for `large_value` and `small_value` further down, this is line 164 and 165.

As for the other change, don't you need to preserve the control and status words ?

**Comment by overmighty** [comment]
The only difference I see between your PR and be8b2d1ea54f964603b89ab9d4dfad26afebb347 is that you moved the `static_cast`s into new variables instead of having them inside the `FEnv` function calls directly. It should be functionally identical.

**Comment by catull** [comment]
> The only difference I see between your PR and [be8b2d1](https://github.com/llvm/llvm-project/commit/be8b2d1ea54f964603b89ab9d4dfad26afebb347) is that you moved the `static_cast`s into new variables instead of having them inside the `FEnv` function calls directly. It should be functionally identical.

I misinterpreted the diff; you are right.
My next commit closes the gap.

**Comment by tru** [comment]
Hi! 18.x release is done and we don't accept any additional patches for that branch.  Please test if this works as expected on LLVM 19.x

**Pull request closed without merging**
