### PR TITLE
[RISCV] Add support for experimental Zimop extension

### PR DESCRIPTION
**Pull request by JivanH**
This implements experimental support for the Zimop extension as specified here:
https://github.com/riscv/riscv-isa-manual/blob/main/src/zimop.adoc.

This change adds intrinsics of mop.r.[n] and mop.rr.[n] instructions for Zimop extension based on 
https://github.com/riscv-non-isa/riscv-c-api-doc/blob/master/riscv-c-api.md.

### CODE REVIEW

**Comment by JivanH** [comment]
@topperc 
@asb 
@michaelmaitland 
@wangpc-pp

**Comment by dtcxzyw** [comment]
I guess you should split it into patch series.
+ [ ] MC support (and docs)
+ [ ] Sched support
+ [ ] ISel support
+ [ ] Builtin intrinsic support in clang

**Comment by wangpc-pp** [comment]
Please reorginize the patch as @dtcxzyw suggested. :-)

I didn't notice this extension before, so I may not be asking the right question here: These MOPs can be redefined, then, are we able to schedule them in compiler? Becase we don't know the cost of MOPs if we don't know how MOPs are used. For example, MOPs can be redefined as simple ALU instructions, or, it can be instructions with large cost like DIV/REM. I don't know how to model it now, but I don't think defining Sched resources for MOPs is the right way.

**Comment by wangpc-pp** [comment]
> Please reorganize the patch as @dtcxzyw suggested. :-)
> 
> I didn't notice this extension before, so I may not be asking the right question here: These MOPs can be redefined, then, are we able to schedule them in compiler? Becase we don't know the cost of MOPs if we don't know how MOPs are used. For example, MOPs can be redefined as simple ALU instructions, or, it can be instructions with large cost like DIV/REM. I don't know how to model it now, but I don't think defining Sched resources for MOPs is the right way.

Just checked similar extensions in ARM (like AUT, PAC, BTI, etc.), these extensions are defined in NOP encoding space and their schedule resources will be overrided by `InstRW`.

**Comment by JivanH** [comment]
@dtcxzyw @wangpc-pp 

Thank you for your review and suggestions. Will do as you suggested and will send the patch series.

**Comment by topperc** [comment]
What is the use case for someone to write the maybe ops directly? Wouldn't you program to the extensions built on top of them like Zicfiss?

**Pull request closed without merging**
