### PR TITLE
[docs] Add a section on AI-generated content to the developer policy

### PR DESCRIPTION
**Pull request by rnk**
Governments around the world are starting to require labelling for AI-generated content, and some LLVM stakeholders have asked if LLVM contains AI-generated content. Defining a policy on the use of AI tools allows us to answer that question affirmatively, one way of the other.

The policy proposed here allows the use of AI tools in LLVM contributions, flowing from the idea that any contribution is fine regardless of how it is made, as long as the contributor has the right to license it under the project license.

I will post an RFC on this topic on Discourse before merging this so we can gather input beyond the reviewers I've listed here.

### CODE REVIEW

**Comment by rengolin** [comment]
Concise and precise. +1 from me.

**Comment by lattner** [comment]
This LGTM (with some discussion to confirm there are not important objections), thank you so much for driving this Reid!

**Comment by joker-eph** [comment]
LGTM, thanks.

**Review by searlmc1 — COMMENTED** [review]
"... are permitted to to use..."

minor typo: 'to' is repeated

**Review by lattner — APPROVED** [review]

**Comment by saiislam** [comment]
@rnk any plans to merge this PR, or take the discourse discussion to a conclusion?

**Comment by rnk** [comment]
My reading of the RFC is that most folks are in favor of a liberal policy on AI tool use as covered in this policy, but there was a lot of feedback that folks want to discourage low-effort AI-assisted contributions. This wouldn't be policy, just guidance, but there were several voices calling for it, and that's what's been blocking me from merging this as is.

---

I added a paragraph, PTAL

**Review by maflcko — APPROVED** [review]

**Pull request merged**
