### PR TITLE
[AArch64,ELF] Restrict MOVZ/MOVK to non-PIC large code model

### PR DESCRIPTION
**Pull request by MaskRay**
There is no PIC support for -mcmodel=large
(https://github.com/ARM-software/abi-aa/blob/main/sysvabi64/sysvabi64.rst)
and Clang recently rejects -mcmodel= with PIC (#70262).

The current backend code assumes that the large code model is non-PIC.
This patch adds `!getTargetMachine().isPositionIndependent()` conditions
to clarify that the support is non-PIC only. In addition, add some tests
as change detectors in case PIC large code model is supported in the
future.

If other front-ends/JITs use the large code model with PIC, they will
get small code model code sequence, instead of potentially-incorrect
MOVZ/MOVK sequence, which is only suitable for non-PIC. The sequence
will cause text relocations using ELF linkers.

(The small code model code sequence is usually sufficient as ADRP+ADD or
ADRP+LDR targets [-2**32,2**32), which has a doubled range of x86-64
R_X86_64_REX_GOTPCRELX/R_X86_64_PC32 [-2**32,2**32).)

### CODE REVIEW

**Comment by smithp35** [comment]
Doesn't this effectively make -mcmodel=large equivalent to -mcmodel=small when -fpie is used? I'm a bit nervous about this as it might lead people to believe that -mcmodel=large is working until their program breaks.

Personally I'd prefer an error message like GNU for now as it is marked as unsupported in the ABI https://github.com/ARM-software/abi-aa/blob/main/sysvabi64/sysvabi64.rst#implementation-of-code-models

One thought I had about code-models and PIC/PIE was to force all global data accesses through the GOT, this would mean that although the GOT would have to be within 4 GiB of the code, global data accessed via the GOT could be anywhere within the address space. Whether that should be called large-code model or something else I don't know. I'm not sure that making a PC-relative offset from a sequence of MOVW using (R_<CLS>_MOVW_PREL_G0) to the GOT really helps for most programs.

**Comment by MaskRay** [comment]
> Doesn't this effectively make -mcmodel=large equivalent to -mcmodel=small when -fpie is used? I'm a bit nervous about this as it might lead people to believe that -mcmodel=large is working until their program breaks.

Yes. The change is primarily about clarification: the large code model support in `lib/Target/AArch64` is no-pic only. The `isPositionIndependent` conditions serve as a document that the PIC large code model needs to do something different.

If there are JIT-style workloads using large code model, this change will force them to use the correct static relocation model instead of relying on a possibly wrong PIC relocation model.

> Personally I'd prefer an error message like GNU for now as it is marked as unsupported in the ABI [ARM-software/abi-aa@`main`/sysvabi64/sysvabi64.rst#implementation-of-code-models](https://github.com/ARM-software/abi-aa/blob/main/sysvabi64/sysvabi64.rst?rgh-link-date=2023-10-25T14%3A38%3A00Z#implementation-of-code-models)

I was uncertain whether Clang Driver should reject it and the description currently says
"The PIC large code model is largely undefined in toolchains, but Clang doesn't reject -fpic -mcmodel=large as GCC does.".

Thanks for the opinion. I will sent a patch to reject `-fpic -mcmodel=large` for AArch64 on top of #53402

> One thought I had about code-models and PIC/PIE was to force all global data accesses through the GOT, this would mean that although the GOT would have to be within 4 GiB of the code, global data accessed via the GOT could be anywhere within the address space. Whether that should be called large-code model or something else I don't know. I'm not sure that making a PC-relative offset from a sequence of MOVW using (R__MOVW_PREL_G0) to the GOT really helps for most programs.

Using GOT is Power's choice: https://maskray.me/blog/2023-05-14-relocation-overflow-and-code-models

Personally I think reusing small code model should be fine for an extended period of time as

> For data references from code, x86-64 uses R_X86_64_REX_GOTPCRELX/R_X86_64_PC32 relocations, which have a smaller range [-2**31,2**31). In contrast, AArch64 employs R_AARCH64_ADR_PREL_PG_HI21 relocations, which has a doubled range of [-2**32,2**32). This larger range makes it unlikely for AArch64 to encounter relocation overflow issues before the binary becomes excessively oversized for x86-64.

**Review by smithp35 — COMMENTED** [review]
IIUC this isn't necessarily needed for Clang now that https://github.com/llvm/llvm-project/pull/70262 has landed, but there may be other front-ends/JITs that could in theory try and use position independence and the large code-model.

Can you update the comment to mention https://github.com/llvm/llvm-project/pull/70262 . Will also need to change "but Clang doesn't reject -fpic -mcmodel=large as GCC does"

Code changes look reasonable to me.

**Comment by MaskRay** [comment]
Rebase (no code change other than formatting).

Reword the description to mention https://github.com/llvm/llvm-project/pull/70262 and clarify that

> This patch adds !getTargetMachine().isPositionIndependent() conditions to clarify that the support is non-PIC only. In addition, add some tests as change detectors in case PIC large code model is supported in the future.

**Review by smithp35 — APPROVED** [review]
Thanks for the changes. LGTM.

**Pull request merged**
