### PR TITLE
[IR] Fix typo in trunc nuw semantics; NFC

### PR DESCRIPTION
**Pull request by programmerjake**

### CODE REVIEW

**Comment by programmerjake** [comment]
@goldsteinn should I amend the commit title to include [IR]?

**Comment by goldsteinn** [comment]
> @goldsteinn should I amend the commit title to include [IR]?

No need (didn't see it was already merged)

**Comment by programmerjake** [comment]
> > @goldsteinn should I amend the commit title to include [IR]?
> 
> No need (didn't see it was already merged)

afaict this hasn't been merged yet, not sure what you mean by that...

**Comment by goldsteinn** [comment]
> > > @goldsteinn should I amend the commit title to include [IR]?
> > 
> > 
> > No need (didn't see it was already merged)
> 
> afaict this hasn't been merged yet, not sure what you mean by that...

hehe, yeah saw the merged tag on the PR you linked.

Yeah change the commit message.

**Review by arsenm — APPROVED** [review]

**Review by elhewaty — APPROVED** [review]
LGTM, thanks.

**Pull request merged**
