### PR TITLE
Fix CMake dependencies on mlir-linalg-ods-yaml-gen

### PR DESCRIPTION
**Pull request by RoboTux**
Fix a number of dependencies issue to build mlir-linalg-ods-yaml-gen
host binary which make a cross-build using the Make generator fail.
Namely:

- do not use binary path for the custom target created when
  LLVM_USE_HOST_TOOLS is true;
- use target name instead of name of variable holding the target name
  for add_custom_target and set_target_properties in setup_host_tool();
- remove dependency on target defined in different directory in
  add_linalg_ods_yaml_gen() since add_custom_target DEPENDS can only be
  used on "files and outputs of custom commands created with
  add_custom_command() command calls in the same directory";
- remove unneeded dependency on ${MLIR_LINALG_ODS_YAML_GEN_EXE}, the
  target dependency will ensure the binary will be built.

Note that we keep using ${MLIR_LINALG_ODS_YAML_GEN_EXE} in the COMMAND
rather than use ${MLIR_LINALG_ODS_YAML_GEN_TARGET} because when
LLVM_NATIVE_TOOL_DIR is used the latter is an empty string.

Testing-wise, all three codepaths in get_host_tool_path() were tested
with both GNU Make and Ninja generators:
- cross-compiling with LLVM_NATIVE_TOOL_DIR checks the if path;
- cross-compiling without LLVM_NATIVE_TOOL_DIR checks the elseif path;
- native build without LLVM_NATIVE_TOOL_DIR checks the else path.

### CODE REVIEW

**Comment by RoboTux** [comment]
Just a small update over https://github.com/llvm/llvm-project/pull/111973 with cache variable becoming normal variable.

**Comment by RoboTux** [comment]
CI failure appears unrelated:

> + ccache --print-stats
> 🚨 Error: The command exited with status 1

**Comment by RoboTux** [comment]
Ping?

**Review by joker-eph — APPROVED** [review]

**Comment by joker-eph** [comment]
I just reverted, seeing how many bots are broken here this seemed like straightforward.

**Comment by RoboTux** [comment]
> I just reverted, seeing how many bots are broken here this seemed like straightforward.

Indeed, thanks. That's very odd, previous version didn't break bots and the only difference is the variable no longer being a cache variable but the variable being cache meant incremental builds across the commit was not possible. Sorry about that, I'll figure out what went wrong.

**Comment by RoboTux** [comment]
New version in https://github.com/llvm/llvm-project/pull/113565

**Pull request merged**
