### PR TITLE
[unittests] Add missing includes

### PR DESCRIPTION
**Pull request by zeroomega**
There are missing include and using in TextStubTests and AsmPrinterDwarfTest and they causes build failures when using vanilla GoogleTest v1.14.0. This patch fixes this issue.

### CODE REVIEW

**Comment by zeroomega** [comment]
First time try Github pull request workflow. I hope I done it correctly.

I have a working draft GoogleTest v1.14.0 roll locally when building/testing LLVM under Linux x64. I still need to clean up the code a bit and validate on a few more platforms before I submit it for review.

The `"llvm/ADT/SmallString.h"` was included in LLVM's patch to GTest header, so it was implicitly included by the test when using LLVM's GTest fork. This causes problem when using a relatively vanilla  GTest.

The missing "using testing::DoAll" is a bit puzzling. I am not sure why the build passed without it currently. It causes build failure when using GTest v1.14.0 and I think we should add it.

**Review by pogo59 — CHANGES_REQUESTED** [review]
I see only two places that use DoAll in llvm/unittests, and the other one has the `using` clause, so it makes sense to have it here.

TextStubHelpers.h looks like it doesn't use SmallString, so that include should go in the files where it's actually needed.

**Comment by zeroomega** [comment]
> I see only two places that use DoAll in llvm/unittests, and the other one has the `using` clause, so it makes sense to have it here.
> 
> TextStubHelpers.h looks like it doesn't use SmallString, so that include should go in the files where it's actually needed.

The SmallString is used in files from `TextStubV1Tests.cpp` to `TextStubV5Tests.cpp` under the same directory of `TextStubHelpers.h`, for example: https://github.com/llvm/llvm-project/blob/main/llvm/unittests/TextAPI/TextStubV1Tests.cpp . So I think it may be better to add the missing header in the `TextStubHelpers.h`, which is shared across these unit tests.

**Review by pogo59 — APPROVED** [review]
Hmmm normally the project prefers to minimize dependencies, pushing them down into .cpp files rather than up into .h files. But I see that MemoryBuffer.h is included by TextStubHelpers.h even though it's not used there, so in this case I accept that it's reasonable to put SmallString in the .h file.

LGTM

**Review by petrhosek — APPROVED** [review]

**Pull request merged**
