### PR TITLE
[libc++] Activate -Warray-zero when building

### PR DESCRIPTION
**Pull request by serge-sans-paille**

### CODE REVIEW

**Review by ldionne — APPROVED** [review]
LGTM assuming green CI

**Comment by serge-sans-paille** [comment]
> LGTM assuming green CI

As green as a clover!

**Comment by philnik777** [comment]
Is there a reason we don't implement this for the test suite?

**Comment by serge-sans-paille** [comment]
Just being slow and cautious :-) Let's move on!

**Pull request merged**
