### PR TITLE
[AMDGPU] Still set up the two SGPRs for queue ptr even it is COV5

### PR DESCRIPTION
**Pull request by shiltian**

### CODE REVIEW

**Comment by shiltian** [comment]
* **#103490** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/103490?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shiltian and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by arsenm — COMMENTED** [review]
I think the intrinsic should be interpreted as the user SGPR value. There is already a representation for load from implicit argument pointer, and we don't need 2 ways of doing that.

**Comment by shiltian** [comment]
> There is already a representation for load from implicit argument pointer, and we don't need 2 ways of doing that.

Which is the representation for loading queue ptr from implicit kernel argument?

**Comment by shiltian** [comment]
That is an indirect way doing that.

What this patch is doing can allow us not to set `.hidden_queue_ptr` unnecessarily. Currently we set it when the function attribute `amdgpu-no-queue-ptr` is absent even for GFX9+ with COV5+. Since we already handle the use of queue pointer for aperture base and trap handling correctly based on COV, it is supposed to safely not set it. However, we still do it. That is probably based on the assumption that a function can call the intrinsic, since we lower it to read the SGPR in any case. If we can lower it to implicit kernel argument for COV5+, we can safely drop `.hidden_queue_ptr` for COV5+.

**Comment by kerbowa** [comment]
> That is an indirect way doing that.
> 
> What this patch is doing can allow us not to set `.hidden_queue_ptr` unnecessarily. Currently we set it when the function attribute `amdgpu-no-queue-ptr` is absent even for GFX9+ with COV5+. Since we already handle the use of queue pointer for aperture base and trap handling correctly based on COV, it is supposed to safely not set it. However, we still do it. That is probably based on the assumption that a function can call the intrinsic, since we lower it to read the SGPR in any case. If we can lower it to implicit kernel argument for COV5+, we can safely drop `.hidden_queue_ptr` for COV5+.

What do you mean by .hidden_queue_ptr, the preloaded SGPR pair? That should be set with the KD field ENABLE_SGPR_QUEUE_PTR.

Currently the lowering for this is totally broken even without this patch. There is an explicit check for COV5 for whether to allocate SGPRs for the queue_ptr and we are not allocating anything. So we load from some random incorrect SGPRs as far as I can tell.

**Review by kerbowa — COMMENTED** [review]
It looks like the intention of @changpeng's COv5 patches was that we should never allocate or access the user SGPR queue_ptr. https://github.com/llvm/llvm-project/blob/f3ca3ef4fca1c3f1b81278bc3823a791fb5efe2b/llvm/lib/Target/AMDGPU/SIISelLowering.cpp#L2413

Otherwise if we go with Matt's suggestion to make the intrinsic mean the preloaded SGPR then the allocation needs to be fixed.

**Comment by changpeng** [comment]
> It looks like the intention of @changpeng's COv5 patches was that we should never allocate or access the user SGPR queue_ptr.
> 
> https://github.com/llvm/llvm-project/blob/f3ca3ef4fca1c3f1b81278bc3823a791fb5efe2b/llvm/lib/Target/AMDGPU/SIISelLowering.cpp#L2413
> 
> Otherwise if we go with Matt's suggestion to make the intrinsic mean the preloaded SGPR then the allocation needs to be fixed.

Right. We should only use the implicitarg field for queue_ptr for cov5. I do remember I have to update many LIT tests due to less sgpr usage.

**Comment by arsenm** [comment]
> That is an indirect way doing that.
> 

Yes, that's my point, it's redundant. 

> What this patch is doing can allow us not to set `.hidden_queue_ptr` unnecessarily. Currently we set it when the function attribute `amdgpu-no-queue-ptr` is absent even for GFX9+ with COV5+. 


> Right. We should only use the implicitarg field for queue_ptr for cov5. I do remember I have to update many LIT tests due to less sgpr usage.

But you still can use the queue pointer, it's not gone. The logic should be able to differentiate should not use queue pointer and queue pointer does not exist

**Comment by shiltian** [comment]
> But you still can use the queue pointer, it's not gone. The logic should be able to differentiate should not use queue pointer and queue pointer does not exist

But the thing is, the queue pointer (the two SGPRs) are never set in COV5. If you still want to use them, you basically have to revert many patches that @changpeng has done.

**Comment by changpeng** [comment]
> 
> But the thing is, the two SGPRs are never set in COV5. If you still want to use them, you basically have to revert those patches that @changpeng has done to disable allocation of the two SGPRs completely in COV5.
COV5 introduced a queue_ptr field in implicit kernarg, and there is no reason to allocate SGPRs. For gfx9+, the doc implies that queue_ptr field does not exist. However, the intrinsic has to return the queue_ptr. (My first impression is that the intrinsic is no longer needed, and should never be invoked). Suppose we have to keep this intrinsic, I would suggest we update the doc to say so that queue_ptr field is still needed when intrinsic call exists.

**Comment by arsenm** [comment]
> But the thing is, the two SGPRs are never set in COV5. If you still want to use them, you basically have to revert those patches that @changpeng has done to disable allocation of the two SGPRs completely in COV5.

Yes. It is still possible to use the queue pointer. You could still want to use the queue pointer as a preloaded argument.

**Comment by shiltian** [comment]
Let me try to make things clear here. The current situation (without this patch) is:

- The intrinsic is lowered to read `s[6:7]`, no matter what GFX and COV. This assumes `s[6:7]` has the value, which means the kernel descriptor needs to be set, no matter what GFX and COV.
- @changpeng's previous patches removed the setup of the kernel descriptor for COV5+. This means if the builtin/intrinsic is used, it is completely broken right now.

Given this, there are two approaches to fix this.

1. Change the lowering of the intrinsic to make it align with @changpeng's patches, that lower the intrinsic to reading from implicit kernel argument. This is what this patch is trying to do.
2. No matter what COV is, `s[6:7]` needs to be set, as long as the builtin/intrinsic is used (explicitly or implicitly). This is what @arsenm is proposing.

Let's compare the two approaches.

For 1, we can safely assume `s[6:7]` will never need to be set up for queue pointer for COV5+, no matter of the existence of the function attribute `amdgpu-no-queue-ptr`, which means no matter whether the optimization is on or off, and no matter whether the optimization can add the function attribute (such as an indirect function call that can't be resolved at compile time), we always have the two SGPRs available for other use.

For 2, we need to revert some changes by @changpeng that set the kernel descriptor if the intrinsic is used explicitly or implicitly. By "implicitly" I mean when at compile time we can't resolve an indirect function call such that we need to assume the intrinsic might be used. This means, even for COV5+, if the optimization is off, or the optimization can't work as expected, we lose the two SGPRs, no matter whether they are really used or not.

IMHO, I don't see the win of 2. It might follow the "convention" that an intrinsic needs to read from registers, but we have so many intrinsics that don't read from register. The reason it read from register in the past is there is no other way.

Did I misunderstand anything here? @arsenm @kerbowa @changpeng

**Comment by arsenm** [comment]
My expectation is for cov5, llvm.amdgcn.queue.ptr would not be used in the first place. If it were used, I would expect it to enable the same user SGPR input as it always did. Lowering it to the load from implicit argument is a strange midpoint that should not occur in real code. 

> IMHO, I don't see the win of 2

 Multiple representations of the same thing are bad. When we detect uses of implicit argument pointers, now we have an extra special case to consider. 

So I would just revert the changes that broke the queue pointer intrinsic.

**Comment by shiltian** [comment]
I'm still working on updating test cases. This is WIP.

**Review by arsenm — APPROVED** [review]
lgtm with the tests all updated

**Comment by shiltian** [comment]
Close this one. Will do it in https://github.com/llvm/llvm-project/pull/112403.

**Pull request closed without merging**
