### PR TITLE
[clang-format] Fix clang-format-buffer--buffer-encoding test

### PR DESCRIPTION
**Pull request by darkfeline**
Broken by https://github.com/llvm/llvm-project/commit/625841c3be4dbaab089c01217726a2906f3a8103

### CODE REVIEW

**Comment by darkfeline** [comment]
@HazardyKnusperkeks @owenca @sam-mccall tagging some people based on git history; apologies if you aren't the right person

**Comment by owenca** [comment]
Please give a more descriptive title.

**Comment by darkfeline** [comment]
> Please give a more descriptive title.

Sorry about that, done

**Comment by dklimkin** [comment]
Hi darkfeline,

Sorry I didn't see your PR and merged #106398 earlier. Please consider closing this one.

**Pull request closed without merging**
