### PR TITLE
[AArch64][Clang] Implement ACLE rintn intrinsics

### PR DESCRIPTION
**Pull request by Blue-Dot**
This patch adds support for two missing ACLE intrinsics for floating point round with ties to even:

- rintn
- rintnf

These are specified in ACLE section 8.6: [https://arm-software.github.io/acle/main/acle.html#floating-point-data-processing-intrinsics]

Change-Id: I951971ad5a3fd3822efdf8cbae22918c31eef28a

### CODE REVIEW

**Review by davemgreen — COMMENTED** [review]
Could this use __builtin_roundeven directly, avoiding the need for __builtin_arm_rintnf?

**Comment by vhscampos** [comment]
Just a nit, but please add a tag to the commit message, like "[Clang][AArch64]".

**Comment by Blue-Dot** [comment]
Thank you both for your comments. I've simplified the patch by using the llvm intrinsic that you suggested David, thanks! 

In trying to fix the commit message, I messed up my git history, hence the force-pushes above to try to fix it. Hopefully the couple of commits make sense. In retrospect, I should have used `git commit --fixup`. Sorry for any confusion with that!

**Review by davemgreen — APPROVED** [review]
Thanks. LGTM

**Pull request merged**
