### PR TITLE
[PAC][AArch64] Support init/fini array signing

### LINKED ISSUE #83800: [PAC][ELF] Implement signed ctor / dtor calls
Downstream commit: https://github.com/access-softek/llvm-project/commit/4fb933cc2d3629905a7ddf56ae96276484371a3d

### PR DESCRIPTION
**Pull request by kovdan01**
If both `-fptrauth-init-fini` and `-fptrauth-calls` are passed, sign function pointers in `llvm.global_ctors` and `llvm.global_dtors` with constant discriminator 0xD9D4 (`ptrauth_string_discriminator("init_fini")`). Additionally, if `-fptrauth-init-fini-address-discrimination` is passed, address discrimination is used for signing (otherwise, just constant discriminator is used).

For address discrimination, we use it's special form since uses of `llvm.global_{c|d}tors` are disallowed (see `Verifier::visitGlobalVariable`) and we can't emit `getelementptr` expressions referencing these special arrays. A signed ctor/dtor pointer with special address discrimination applied looks like the following:

```
ptr ptrauth (ptr @foo, i32 0, i64 55764, ptr inttoptr (i64 1 to ptr))
```

### CODE REVIEW

**Comment by asl** [comment]
Can we have LLVM IR test as well?

**Comment by kovdan01** [comment]
> Can we have LLVM IR test as well?

I've added llvm/test/CodeGen/AArch64/ptrauth-init-fini.ll, thanks for suggestion.

**Comment by kovdan01** [comment]
The PR no longer depends on #96477. For signed ctors/dtors we now have special address discrimination handling so we don't need to use self-references to `llvm.global_{c|d}tors` with giant `getelementptr` expressions - such references are disallowed and, as discussed in #96477, allowing them just for ptrauth purposes has significant drawbacks.

Instead, just use `ptr inttoptr (i64 1 to ptr)`, like this:

```
@llvm.global_ctors = appending global [1 x { i32, ptr, ptr }] [{ i32, ptr, ptr } { i32 65535, ptr ptrauth (ptr @foo, i32 0, i64 55764, ptr inttoptr (i64 1 to ptr)), ptr null }]
```

This is the same approach which is used in Apple's downstream for coroutines, and we share some code with that - see https://github.com/ahmedbougacha/llvm-project/commit/2a5528ea2cb223fca0b47f0a4833bbb938cf0748. Also tagging @ahmedbougacha.

**Comment by kovdan01** [comment]
Would be glad to see feedback on the changes from those who are interested.

**Comment by kovdan01** [comment]
Ping: would be glad to see feedback on the changes from those who are interested.

**Comment by kovdan01** [comment]
Ping: would be glad to see feedback on the changes from those who are interested.

**Comment by kovdan01** [comment]
Ping: would be glad to see feedback on the changes from those who are interested.

**Comment by kovdan01** [comment]
Ping: would be glad to see feedback on the changes from those who are interested.

**Comment by kovdan01** [comment]
Ping: this PR blocks merging already approved #96159 (see https://github.com/llvm/llvm-project/pull/96159#issuecomment-2211411440), which transitively also blocks merging already approved dependent #96164.

Would be glad to see feedback on the changes from those who are interested.

**Review by DanielKristofKiss — APPROVED** [review]
LGTM.

**Comment by piotrAMD** [comment]
I am getting build errors with gcc. Any ideas?
```
llvm-project/compiler-rt/lib/builtins/crtbegin.c:11:18: error: missing binary operator before token "("
     11 | #if __has_feature(ptrauth_init_fini)
        |                  ^
llvm-project/compiler-rt/lib/builtins/crtbegin.c:53:18: error: missing binary operator before token "("
     53 | #if __has_feature(ptrauth_init_fini)
        |                  ^
llvm-project/compiler-rt/lib/builtins/crtbegin.c:124:18: error: missing binary operator before token "("
    124 | #if __has_feature(ptrauth_init_fini)
    
```

**Comment by kovdan01** [comment]
@piotrAMD It looks like that `__has_feature` preprocessor directive support was implemented in gcc only in 2023: https://github.com/gcc-mirror/gcc/commit/06280a906cb3dc80cf5e07cf3335b758848d488d

Thanks for reporting. I suppose we can just surround this chunk of code with `#ifdef __clang__`. I'll open corresponding PR shortly.

**Comment by kovdan01** [comment]
@piotrAMD Submitted #102154 with a fix. Could you please check if it resolves the issue for you?

**Comment by piotrAMD** [comment]
Thanks for the quick fix, but apparently the fix was already submitted in 41b83ca559c402d238e303c0ac233180d60dcd57 - I wasn't aware of that.

**Comment by efriedma-quic** [comment]
There's some followup discussion suggesting a different IR representation at https://github.com/llvm/llvm-project/pull/102199#discussion_r1706094411 .

**Pull request merged**
