### PR TITLE
[SDag] Fold saddo[_carry] with bitwise-not argument to ssubo[_carry]

### PR DESCRIPTION
**Pull request by s-barannikov**
Fold `(saddo (not a), 1)` to `(ssubo 0, a)` and
`(saddo_carry (not a), b, c)` to `(ssubo_carry b, a, !c)`.

Proof: https://alive2.llvm.org/ce/z/Lj49YM

This is the same as https://reviews.llvm.org/D46505 and
https://reviews.llvm.org/D59208, but for signed opcodes.

### CODE REVIEW

**Comment by RKSimon** [comment]
Please can you add Alive2 links

**Comment by s-barannikov** [comment]
> Please can you add Alive2 links

I've updated the description. Should I also change the commit message?

**Comment by RKSimon** [comment]
> > Please can you add Alive2 links
> 
> I've updated the description. Should I also change the commit message?

Yes, the alive2 links should be in the final git commit message.

**Comment by s-barannikov** [comment]
For the second live example I had to add --disable-undef-input because otherwise I get this: https://alive2.llvm.org/ce/z/QoHVCH
I'm not sure this it is OK.

**Review by nikic — APPROVED** [review]
LGTM

**Comment by RKSimon** [comment]
Needing "--disable-undef-input" can usually be addressed with freeze nodes on the inputs: https://alive2.llvm.org/ce/z/tiDhDv (had to reduce type size to get alive2 to complete).

CC @nikic who might have some thoughts

**Comment by nikic** [comment]
I think this is just a proof artifact. In terms of actual SDAG nodes, we aren't increasing use counts, so freeze should not be necessary.

**Review by RKSimon — APPROVED** [review]
OK - it matches the existing ADD variants

LGTM - cheers

**Pull request merged**
