### PR TITLE
[ORC][Runtime] Enhancing ELF Platform with Push-Request Model for Initializers

### PR DESCRIPTION
**Pull request by SahilPatidar**
With the help of @lhames, this PR introduces a push-request model to manage list initializers in the runtime state for each `JITDylib`, similar to how `MachO` and `COFF` handle it. Previously, the ELF runtime lacked the ability to register, deregister, or retain initializers, causing issues when re-running `dlopen`. Initializers were erased after `rt_getInitializers` was used.

To address this, we introduce `__orc_rt_elfnix_register_init_sections` and `__orc_rt_elfnix_register_jitdylib` (and corresponding deregister functions). This model allows the runtime to request the push of initializers for the `JITDylib`, with the platform handling this via a record method. Additionally, we leverage `MachO`'s `RecordSectionsTracker` to store initializers, ensuring only newly updated initializers are executed using `processNewSections`, improving the runtime's efficiency and reliability.

### CODE REVIEW

**Comment by SahilPatidar** [comment]
@lhames  If I add `if (!IsBootstrapping)` around `addDSOHandleSupportPasses` and `registerInitSections` in `modifyConfig`, it works as well, so there's no need to track anything. However, we'll have to add this code; otherwise, it will give an "unrecognized header" error while registering initializers. If you think this approach is correct, I'll remove the tracking.

```cpp
ELFNixPlatformRuntimeState::PerJITDylibState *
ELFNixPlatformRuntimeState::getJITDylibStateByHeaderAddr(void *DSOHandle) {
  auto I = JDStates.find(DSOHandle);
  if (I == JDStates.end()) {
    I = JDStates.insert(std::make_pair(DSOHandle, JITDylibState())).first;
    I->second.Header = DSOHandle;
  }
  return &I->second;
}
```

If we don't do this, then we can't add the deregister call in `addDSOHandleSupportPasses` and `registerInitSections`.

**Review by lhames — APPROVED** [review]
Sorry for the delayed review. LGTM. Thanks @SahilPatidar!

**Comment by lhames** [comment]
Side note: `RecordSectionTracker` should probably get its own header, rather than going into `common.h`, but that's not a blocker to landing this. :)

**Comment by SahilPatidar** [comment]
@lhames  I will create a new header for this.

**Pull request merged**
