### PR TITLE
[BasicBlockSections] Using MBBSectionID as DenseMap key

### PR DESCRIPTION
**Pull request by HaohaiWen**
getSectionIDNum may return same value for two different MBBSectionID.
e.g. A Cold type MBBSectionID with number 2 and a Default type
MBBSectionID with number 0 get same value 2 from getSectionIDNum. This
may lead to overwrite of MBBSectionRanges.  Using MBBSectionID itself
as DenseMap key is better choice.

### CODE REVIEW

**Review by williamweixiao — APPROVED** [review]
LGTM. Thanks for fixing this bug!

**Comment by HaohaiWen** [comment]
I'd like to merge it if no any objection.

**Comment by rlavaee** [comment]
Sorry, I was OOO and didn't get a chance to look at this. You mention that `A Cold type MBBSectionID with number 0 and a Default type MBBSectionID with number 2 get same value 2 from getSectionIDNum`, but I think the former will get 0 and the will get 2.  Am I missing anything?

**Comment by HaohaiWen** [comment]
> Sorry, I was OOO and didn't get a chance to look at this. You mention that `A Cold type MBBSectionID with number 0 and a Default type MBBSectionID with number 2 get same value 2 from getSectionIDNum`, but I think the former will get 0 and the will get 2. Am I missing anything?

Oh sorry. It's typo...
```
It should be
A Cold type MBBSectionID with number 2 and a Default type MBBSectionID with number 0 get same value 2 from getSectionIDNum
```

**Pull request merged**
