### PR TITLE
[libc++] Add "using-if-exists" to timespec_get in modules

### PR DESCRIPTION
**Pull request by domin144**
Picolibc does not provide timespec_get function. Adding "using-if-exists" attribute fixes the modules.

This is a follow up patch for https://github.com/llvm/llvm-project/pull/78580

### CODE REVIEW

**Comment by domin144** [comment]
After rebasing the patch I re-run the tests and realized the test is skipped now. Not sure why, and if this is intentional.
Still, I propose the patch as is, as this fixed the tests when they were run.

**Comment by domin144** [comment]
Ok, I can see not, that the module tests have to be enabled with `set(LIBCXX_ENABLE_STD_MODULES ON CACHE BOOL "")` in `Armv7M-picolibc.cmake`.
I tried it, but found, that a more recent version of cmake and ninja is required than those provided with ubuntu 22.04. With those updated, the tests pass.
I checked the logs of the buildkite run and I can see the picolibc tests are run with older versions of cmake and ninja. I am not enabling the module tests in `Armv7M-picolibc.cmake` for now.

**Comment by mordante** [comment]
> Ok, I can see, that now the module tests have to be enabled with `set(LIBCXX_ENABLE_STD_MODULES ON CACHE BOOL "")` in `Armv7M-picolibc.cmake`. I tried it, but found, that a more recent version of cmake and ninja is required than those provided with ubuntu 22.04. With those updated, the tests pass. I checked the logs of the buildkite run and I can see the picolibc tests are run with older versions of cmake and ninja. I am not enabling the module tests in `Armv7M-picolibc.cmake` for now.

The patches to make modules work with older CMake versions have been reverted. I expect I can reland that patch soon. After that you can rebase this patch on main again and we can test it again.

**Comment by mordante** [comment]
I've just relanded the dependencies for this patch. Could you rebase this patch to see whether the CI is green?

**Comment by domin144** [comment]
Thanks for an update. I rebased and I can see the picolibc tests passed.

**Review by mordante — APPROVED** [review]
Thanks! Great to see Picolib working for modules! Since we're getting close the branching I'll directly merge the patch.

**Pull request merged**
