### PR TITLE
[AMDGPU] Update EXECZ retention in SIPreEmitPeephole for GFX10/12

### PR DESCRIPTION
**Pull request by perlfu**
The check to maintain EXECZ branches only checks S_WAITCNT.
Add handling for new waitcnt instructions in GFX10 and GFX12.

### CODE REVIEW

**Comment by jayfoad** [comment]
> Update EXECZ retention in SIPreEmitPeephole for GFX11/12

I don't think any of this was new in GFX11 was it? But you could perhaps add s_wait_event as another wait-y thing, which _was_ new in GFX11.

**Comment by jayfoad** [comment]
> Also add code to retain uniform jumps over barrier instructions.

This seems like it should be a separate patch. Is it required for correctness? Why hasn't it caused problems before?

**Comment by perlfu** [comment]
> > Update EXECZ retention in SIPreEmitPeephole for GFX11/12
> 
> I don't think any of this was new in GFX11 was it? But you could perhaps add s_wait_event as another wait-y thing, which _was_ new in GFX11.

Yes my bad, I really meant GFX10/GFX12 as we didn't add any coverage of S_WAITCNT_(VSCNT|EXPCNT|VMCNT|LGKMCNT) with GFX10.

I was unsure whether to add s_wait_event, but probably.

**Comment by perlfu** [comment]
> > Also add code to retain uniform jumps over barrier instructions.
> 
> This seems like it should be a separate patch. Is it required for correctness? Why hasn't it caused problems before?

Can separate these.  I don't think we commonly generate code that jumps a barrier, because it would create potential problems if some waves did not follow the same decisions across a workgroup.  And/or our blocks with s_barrier are usually above the threshold.
But I think the risk of generating something where this matters maybe higher with newer barrier operations on GFX12.

**Comment by jayfoad** [comment]
> > > Also add code to retain uniform jumps over barrier instructions.
> > 
> > This seems like it should be a separate patch. Is it required for correctness? Why hasn't it caused problems before?
> 
> Can separate these. I don't think we commonly generate code that jumps a barrier, because it would create potential problems if some waves did not follow the same decisions across a workgroup. And/or our blocks with s_barrier are usually above the threshold. But I think the risk of generating something where this matters maybe higher with newer barrier operations on GFX12.

So should barrier operations be included in `hasUnwantedEffectsWhenEXECEmpty`? I've never understood precisely what that function is for.

**Comment by perlfu** [comment]
- Remove barrier related code.
- Relabel this as GFX10/GFX12 as that is the focus.

**Review by jayfoad — APPROVED** [review]

**Pull request merged**
