### PR TITLE
[release/19.x][libc++] Adjust the version of __cpp_lib_ranges in C++20 mode

### PR DESCRIPTION
**Pull request by ldionne**
This is a (very partial) cherry-pick of #101715 to fix this oversight in the LLVM 19 release.

### CODE REVIEW

**Comment by tru** [comment]
Many CI failures here as well. Can you check @ldionne ?

**Comment by frederick-vs-ja** [comment]
I guess 6f6422f4a2b8647a59936c131e50a79906d89510 and cdd608b8f0ce090b3568238387df368751bdbb5d should also be cherry-picked. @tru @ldionne

**Comment by ldionne** [comment]
@tru Our CI is currently super unstable, that's the failures. We've been without CI for roughly the past week. We're working on it.

**Comment by ldionne** [comment]
> I guess [6f6422f](https://github.com/llvm/llvm-project/commit/6f6422f4a2b8647a59936c131e50a79906d89510) and [cdd608b](https://github.com/llvm/llvm-project/commit/cdd608b8f0ce090b3568238387df368751bdbb5d) should also be cherry-picked. @tru @ldionne

This is now https://github.com/llvm/llvm-project/pull/110259

**Comment by frederick-vs-ja** [comment]
@ldionne I force-pushed the branch for resolving conflicts with #109291. Please double-check the changes.

**Review by ldionne — COMMENTED** [review]
LGTM thanks!

**Pull request merged**
