### PR TITLE
[SPIRV][DX] Share one test between backends

### PR DESCRIPTION
**Pull request by Keenuts**
One big issue with DirectXShaderCompiler was test coverage: DXIL and SPIR-V backends had their own tests. When a bug was found in one, the other wasn't always checked. This lead to unequal support of HLSL for both backends. We'd like to avoid those issues here, hence the test-sharing.

By default, all the tests in this folder are marked as requiring DirectX. But as SPIR-V support grows, each test drop this requirement, and check the SPIR-V behavior.

I would have preferred to mark new tests as XFAIL for SPIR-V by default, so we could differentiate real unsupported tests (as SPIR-V has no equivalent), from newly added tests. But the way LIT is built, I don't think this is possible.

### CODE REVIEW

**Comment by Keenuts** [comment]
The buildkite failure seems to be related to the quoting of the `- *_result.json`. Seems unrelated to this change.

**Comment by llvm-beanz** [comment]
I don't think this is the right approach for test sharing. These tests all specifically test code in the DirectX backend, they aren't the kinds of tests that should be shared with the SPIR-V backend.

**Comment by bogner** [comment]
Would it make the most sense to have a place like `test/Frontend/HLSL/` (to match `lib/Frontend/HLSL` - though there isn't such a directory yet)? This would provide a common place for HLSL specific constructs like numthreads and resources at least.

**Comment by Keenuts** [comment]
> Would it make the most sense to have a place like `test/Frontend/HLSL/` (to match `lib/Frontend/HLSL` - though there isn't such a directory yet)? This would provide a common place for HLSL specific constructs like numthreads and resources at least.

Yes, this makes sense. I don't know what the broader community will think of having frontend-specific tests here, but I do agree it would make sense.

**Review by bogner — APPROVED** [review]
This looks good to me. @llvm-beanz are you happy with this approach?

**Review by llvm-beanz — APPROVED** [review]
LGTM. At some point we'll want to expand the list of supported targets, but we can think about that later.

**Comment by Keenuts** [comment]
Thanks!
Added @michalpaszkowski on the SPIR-V side.

**Review by michalpaszkowski — APPROVED** [review]
Thanks @Keenuts for working on this! LGTM!

**Comment by Keenuts** [comment]
rebased on main for merge

**Comment by Keenuts** [comment]
One failure on presubmit: python formatting. From the logs it's a bad argument, infra related (https://github.com/llvm/llvm-project/actions/runs/6259826929/job/16996615363?pr=65975).
Unrelated.

**Pull request merged**
