### PR TITLE
[clang-tidy] fix incorrect argument names in documentation for ExtraArgs and ExtraArgsBefore

### PR DESCRIPTION
**Pull request by float3**

### CODE REVIEW

**Comment by nicovank** [comment]
Sync with [ClangTidyMain.cpp](https://github.com/llvm/llvm-project/blob/d36836de0183b9b1939cc679d153e3b313e55c76/clang-tools-extra/clang-tidy/tool/ClangTidyMain.cpp#L57-L58)?

https://github.com/llvm/llvm-project/blob/d36836de0183b9b1939cc679d153e3b313e55c76/clang-tools-extra/clang-tidy/tool/ClangTidyMain.cpp#L57-L58

**Comment by float3** [comment]
I adjusted headerfilterregex as well as per https://github.com/llvm/llvm-project/pull/111405

**Review by nicovank — APPROVED** [review]
LGTM, thanks!

**Review by carlosgalvezp — APPROVED** [review]
LGTM!

**Pull request merged**
