### PR TITLE
[clang][analyzer] Support 'fflush' in the StdLibraryFunctionsChecker

### PR DESCRIPTION
**Pull request by benshi001**

### CODE REVIEW

**Review by NagyDonat — APPROVED** [review]
Looks good to me, my only nitpick is that perhaps you could use more descriptive test names instead of using `_0` and `_1` suffixes.

Also, perhaps wait a bit (until next year ;) ) before merging this to give other reviewers a chance to look at it.

**Comment by steakhal** [comment]
please also update the release notes

**Comment by benshi001** [comment]
> Looks good to me, my only nitpick is that perhaps you could use more descriptive test names instead of using `_0` and `_1` suffixes.
> 
> Also, perhaps wait a bit (until next year ;) ) before merging this to give other reviewers a chance to look at it.

Thanks for your suggestion. I have renamed the test functions to more meaningful names.

**Comment by benshi001** [comment]
> ~please also update the release notes~ EDIT: Done.

Thanks for your support!

**Comment by DonatNagyE** [comment]
Thanks for updating the test names. I think it's safe to merge this now (as @steakhal also had an opportunity to look at it).

**Review by steakhal — APPROVED** [review]
LGTM

**Comment by benshi001** [comment]
Thanks for your help. Happy new year!

**Pull request merged**
