### PR TITLE
[SelectOpt] Don't convert constant selects to branches.

### PR DESCRIPTION
**Pull request by davemgreen**
Selects that choose between two constants will be less profitable to turn into branches, especially if the constants can be folded somehow into the surrounding instructions. They will also be cost modelled in a way that can make them over-optimistically converted to branches, as neither branch will have a latency depth but the constants still need to be materialized.

This patch disabled selectopt for selects with two constant branches. It is currently in the target independent part, as it sounds generic, but I could move it into AArch64 if needed.

### CODE REVIEW

**Comment by sapostolakis** [comment]
Makes sense to specialize for constant values but the condition cost also matters.   
With a select the condition is on the critical path, while with a branch computing the condition is not blocking the instruction. 
Enabling it in a target-independent manner makes sense but a bit worried about any potential downsides. 
Was this change motivated by performance diff on some workload/microbenchmark?

**Comment by davemgreen** [comment]
> Makes sense to specialize for constant values but the condition cost also matters. With a select the condition is on the critical path, while with a branch computing the condition is not blocking the instruction. Enabling it in a target-independent manner makes sense but a bit worried about any potential downsides. Was this change motivated by performance diff on some workload/microbenchmark?

Hi. Yeah we found a case where performance was getting worse. I think the new test case captures what was happening, although the real example is a little more complex and had two selects in the loop.

The places where I've seen selectopt really help is where there are cross iteration dependency chains through the select, and a huge dependency chain gets created for the select version that is broken by converting it to a branch. Or if less instruction can be executed thanks to moving instructions into the then/else branch. If both the operands of the select are constant (or I guess loop invariant might be more accurate?) then the same long chains can't happen and the out of order engine should be fine working through the independent iterations. The branch has a higher chance of slowing things down if it gets mis-predicted.

That is my hope at least. I ran some benchmarks and they performed OK overall, giving a 0.8% improvement in geomean for the benchmarks that changed over llvm-test-suite + various version of spec + some other internal benchmarks which all run at the same time. But SelectOpt is going to be relatively noisy as it depends so heavily on the predictability of the branch and how well the branch predictor manages to behave.

**Comment by sapostolakis** [comment]
Yeah I agree that this is reasonable when considering the value operands and does not miss out on any of the core opportunities of selectopt. I still think the select condition cost might play a role in the cost model, but I see that in your test case and probably in your motivating example the condition was actually expensive and still the select was the optimal choice. I also remember that a heuristic that I tried that focused on the condition was not profitable. So, overall, the proposed change sounds reasonable.

I tested this change on an internal Google macrobenchmark for x86 and the performance was neutral, so I am okay with landing this change, given your observed gains and lack of indication of regressions.

**Review by sapostolakis — APPROVED** [review]

**Comment by davemgreen** [comment]
Thanks for checking. Let us know if this does cause any problems and we can adjust it as needed.

**Pull request merged**
