### PR TITLE
[clang][driver][clang-cl] Fix unused argument warning for `/std:c++20` for precompiled module inputs to `clang-cl`

### PR DESCRIPTION
**Pull request by sharadhr**
Manual PR to backport #99300.

### CODE REVIEW

**Comment by sharadhr** [comment]
@ChuanqiXu9, is there anything else that needs to be done here? There's a merge conflict; I could resolve that.

**Comment by ChuanqiXu9** [comment]
> @ChuanqiXu9, is there anything else that needs to be done here? There's a merge conflict; I could resolve that.

If there is merge conflict, we need to resolve it. For the merge request, we need to wait for the release manager to have a time to look at this. Maybe due to we forgot to mention this belongs to 19.x. CC @tru  manually.

**Comment by tru** [comment]
This PR is pretty messy: Several commits instead of a single that can be cherry-picked, merge commit that makes it harder to cherry-pick and squash.

Please update the PR to contain a single commit that fixes the issue and doesn't contain any merge commits, then I can merge it easily.

Thanks.

**Comment by sharadhr** [comment]
@tru, thanks for the feedback; I hope this is better.

**Comment by tru** [comment]
Looks much better. I'll merge it later.

**Pull request merged**
