### PR TITLE
[Clang][Sema] Earlier type checking for builtin unary operators

### PR DESCRIPTION
**Pull request by sdkrystian**
Currently, clang postpones all semantic analysis of unary operators with operands of pointer/pointer to member/array/function type until instantiation whenever that type is dependent (e.g. `T*` where `T` is a type template parameter). Consequently, the uninstantiated AST nodes all have the type `ASTContext::DependentTy` (which, for the purposes of #90152, is undesirable as that type may be the current instantiation! (e.g. `*this`)) 

This patch moves the point at which we perform semantic analysis for such expression to be prior to instantiation.

### CODE REVIEW

**Review by erichkeane — APPROVED** [review]
This needs a release note, likely in the 'potentially breaking changes'.  Projects are filled with code that is not ever instantiated, and Clang's aggressive instantiation can be a problem.

Else, LGTM.

**Review by shafik — COMMENTED** [review]
So this seems to apply to member pointer types, pointer types, arrays and function types but I don't see coverage for the full set of paths in the tests. Can we please add more testing.

Erich also expressed some concern about breaking existing code due to eager instantiation. Can we make sure try to cover any change in behavior in the tests so reviewers can get a better idea of impact.

**Comment by sdkrystian** [comment]
@erichkeane Release note added

**Review by erichkeane — COMMENTED** [review]
I'm still OK with this, but @shafik : Please ensure this has the test coverage you asked for.

**Comment by sdkrystian** [comment]
Yup, working on it :)

**Comment by sdkrystian** [comment]
@shafik More tests added

**Comment by sdkrystian** [comment]
Ping @shafik

**Review by shafik — APPROVED** [review]
Thank you for the additional test coverage, LGTM

**Comment by erichkeane** [comment]
> @erichkeane Since I addressed @shafik's comments, it this good to be merged?

Yep, go for it!

**Comment by sdkrystian** [comment]
This seems to [break something](https://lab.llvm.org/buildbot/#/builders/121/builds/41631) in LLVM... investigating

**Comment by erichkeane** [comment]
This is unfortunately one of the cases where if you can't fix it 'quickly', a revert is necessary, as it breaks the build.

**Comment by sdkrystian** [comment]
Reverted in #92149

**Comment by MaskRay** [comment]
> This seems to [break something](https://lab.llvm.org/buildbot/#/builders/121/builds/41631) in LLVM... investigating

I've also noticed a stage-2-build issue. 

```
      llvm::any_of(LHS->users(),
                    [&](auto *U) {
                      return U != I &&
                             !(U->hasOneUser() && *U->users().begin() == I);
                    }) ||
```

```
llvm/lib/Transforms/Scalar/NaryReassociate.cpp:610:32: error: comparison of distinct pointer types ('auto *' and 'Instruction *')
  610 |                       return U != I &&
      |                              ~ ^  ~
```

**Comment by sdkrystian** [comment]
Well this took forever to reduce:
```cpp
template<typename T>
struct A;

template<typename T>
bool operator==(const A<T>&, const A<T>&);

template<typename>
void f(int *x)
{
    [&](auto *y) { return x == y; };
}

void g()
{
    f<int>(nullptr);
}
```
We initially build a `CXXOperatorCallExpr` during parsing for the comparison, but `TreeTransform` prematurely rebuilds it as a builtin binary operator when `f` is instantiated.

**Comment by erichkeane** [comment]
> Well this took forever to reduce:
> 
> ```c++
> template<typename T>
> struct A;
> 
> template<typename T>
> bool operator==(const A<T>&, const A<T>&);
> 
> template<typename>
> void f(int *x)
> {
>     [&](auto *y) { return x == y; };
> }
> 
> void g()
> {
>     f<int>(nullptr);
> }
> ```
> 
> We initially build a `CXXOperatorCallExpr` during parsing for the comparison, but `TreeTransform` prematurely rebuilds it as a builtin binary operator when `f` is instantiated.

Yeah, unfortunately that is a limitation of Clang, we still don't correctly implement the instantiation of Lambdas.  We do so 'greedily', in a way that the standard doesn't allow.  We eventually need to delay ALL instantiation until the actual first full instantiation of the lambda.

That said, in this case I'm surprised that we don't skip that diagnostic based on the RHS (in your repro) being dependent.  THAT would probably fix this case at least.

**Comment by sdkrystian** [comment]
The issue seems to be that `TreeTransform::RebuildCXXOperatorCallExpr` relies on `isOverloadableType` to always be true for dependent types

**Comment by shafik** [comment]
You reapplied this here: https://github.com/llvm/llvm-project/commit/1595988ee6f9732e7ea79928af8a470ad5ef7dbe

but it has caused a regression: https://github.com/llvm/llvm-project/issues/97646

**Pull request merged**
