### PR TITLE
[libc++] Use char_traits::copy while inserting when possible

### PR DESCRIPTION
**Pull request by philnik777**
This reduces the number of asm lines from 707 to 519 for this snippet:
```c++
auto test(std::string& str, const char* begin, const char* end) {
  str.insert(str.begin(), begin, end);
}
```
While that's not a performance metric, I've never seen a use of `memcpy` result in a performance regression for any realistic usage.

### CODE REVIEW

**Comment by EricWF** [comment]
What effect does this have on the benchmarks? 
If we're getting the optimization, I would expect this to be observable.


Also, was the lines of assembly in a debug or optimized build configurations?

**Comment by philnik777** [comment]
> What effect does this have on the benchmarks? If we're getting the optimization, I would expect this to be observable.
> 
> Also, was the lines of assembly in a debug or optimized build configurations?

AFAICT we don't have any benchmarks for `string::insert`. The asm was for an optimized build. Here you can see why the difference is so significant: https://godbolt.org/z/bs938GKfY

**Comment by ldionne** [comment]
The optimization makes sense to me, however `string::insert` says:

> Inserts characters from the range `[first, last)` before the element (if any) pointed by `pos`, as if by `insert(pos - begin(), basic_string(first, last, get_allocator()))`

I read this as saying that it's fine to insert a substring of the string into the string. Something like this:

```
std::string s = "0123456789";
auto first = s.begin();
auto last = s.end();
s.insert(s.begin() + 3, first, last);
assert(s == "01201234567893456789");
```

Godbolt: https://godbolt.org/z/33znr65oT

So I don't think we can perform this optimization, at least not without checking for overlap in the input range first.

**Review by ldionne — APPROVED** [review]
LGTM w/ nit comment.

**Pull request merged**
