### PR TITLE
[lldb][test] Apply @expectedFailureAll/@skipIf early for debug_info tests

### PR DESCRIPTION
**Pull request by rupprecht**
The @expectedFailureAll and @skipIf decorators will mark the test case as xfail/skip if _all_ conditions passed in match, including debug_info.
* If debug_info is not one of the matching conditions, we can immediately evaluate the check and decide if it should be decorated.
* If debug_info *is* present as a match condition, we need to defer whether or not to decorate until when the `LLDBTestCaseFactory` metaclass expands the test case into its potential variants. This is still early enough that the standard `unittest` framework will recognize the test as xfail/skip by the time the test actually runs.

TestDecorators exhibits the edge cases more thoroughly. With the exception of `@expectedFailureIf` (added by this commit), all those test cases pass prior to this commit.

This is a followup to 212a60ec37322f853e91e171b305479b1abff2f2.

### CODE REVIEW

**Comment by rupprecht** [comment]
> * This is still early enough that the standard `unittest` framework will recognize the test as xfail/skip by the time the test actually runs.

I did a little bit more research, turns out this is not a difference between unittest and unittest2, but rather just something we have in our ancient, vendored copy of unittest2.

Our copy of `unittest2` originates from 2010 in 73258830f391047d9ee9ae4a07fd8ced4d7cf0a9, and has never undergone a version upgrade AFAICT. Two commits, both applied Mar 20, 2013, implement some features for `subTest` in both `unittest` and `unittest2` for https://bugs.python.org/issue16997:
- https://github.com/python/cpython/commit/c9b3ef2df06818f055e555c1d23e3ff2d5bf2d74
- https://hg.python.org/unittest2/rev/0daffa9ee7c1

The important part of that diff is it stops raising `_ExpectedFailure` and starts just setting `__unittest_expecting_failure__` on the test method. The full discussion on that is https://bugs.python.org/issue16997, especially starting around [msg183450](https://bugs.python.org/issue16997#msg183450)

**Comment by rupprecht** [comment]
ping :)

**Comment by adrian-prantl** [comment]
Is this a performance optimization or a function al change?

**Comment by rupprecht** [comment]
> Is this a performance optimization or a function al change?

Neither. This should only affect tests, and the set of tests we skip/mark as xfail should not change, we just generally know about it earlier in the test setup.

**Comment by adrian-prantl** [comment]
SGTM, maybe wait one more day for @JDevlieghere to chime in.

**Review by JDevlieghere — APPROVED** [review]

**Pull request merged**
