### PR TITLE
[NFC] Rename Option parsing related files from OptXYZ -> OptionXYZ

### PR DESCRIPTION
**Pull request by jurahul**
Rename option parsing related files from OptXYZ -> OptionXYZ, since Opt could be confused with optimization and Opt as a short hand for Option is not really that smaller to warrant its use.

### CODE REVIEW

**Comment by jurahul** [comment]
@JDevlieghere @cyndyishida @topperc gentle ping. It's mostly mechanical.

**Comment by JDevlieghere** [comment]
The change itself seems fine but I'm not super convinced that the motivation is worth the churn. All these files live under the "Option" library and therefore it's (IMHO) clear that Opt is short for Option. 

Is this addressing code review feedback or a real issue where the two got confused, or addressing more of a hypothetical concern?

**Comment by jurahul** [comment]
more of a hypothetical concern at this point. It's also making file names under Option consistent, in the sense that we have `Option.h` and `Option.cpp` but `OptTable.h` `OptSpecifier.h` and `OptTable.cpp`

**Comment by dwblaikie** [comment]
Yeah, I think given how wide the change is and the speculative nature of the harm - probably best to abandon this for now. We can pick it up again if more folks speak up/more evidence is presented that it's problematic.

**Comment by jurahul** [comment]
Sounds good. thanks.

**Pull request closed without merging**
