### PR TITLE
Clang-format coroutine files ahead of refactoring

### PR DESCRIPTION
**Pull request by TylerNowicki**
To clean things up before refactoring apply clang-format changes to the coroutine sources. The files in lib/Transforms/Coroutines deviated from clang-format in a number of places.

### CODE REVIEW

**Comment by yuxuanchen1997** [comment]
Do you mind just do the refactoring that you are thinking of? You can format your change only without formatting entire files.

**Comment by TylerNowicki** [comment]
> Do you mind just do the refactoring that you are thinking of? You can format your change only without formatting entire files.

My thinking was that when moving code clang-format on the refactoring patches would result in code changes and maybe that is not great to do. Perhaps that is okay though, I am new to working on this so I will follow your advice.

btw, my intent is to make it easier for other users of llvm/transforms/coroutines (not just c++20). I'm sure you already noticed issues with the current design. To support swift it was necessary to add some code to the mid-level passes, but now all users will see and run the swift specific code. This will not scale as more users need specific behavior for things like spilling and remat. I plan to make some more significant changes that are likely not desirable for c++20 or swift. So to prepare for this I will refactor coroutines in a way that will make it possible for other users to use their own code without affecting the c++20 user.

**Comment by yuxuanchen1997** [comment]
> My thinking was that when moving code running clang-format on the refactoring patches would result in code changes and maybe that is not great to do. 

I usually just run this to format code strictly contained within my patch. 
```
git diff -U0 --no-color HEAD^ | python3 clang/tools/clang-format/clang-format-diff.py -i -p1
```
Many of us prefer to ignore preexisting formatting issues simply because there are too many such changes. There are repo-wide efforts to make things clang-format clean but turned out to be difficult. 

> I am new to working on this so I will follow your advice.

Welcome! I have been working on this for only about half a year. I have also done prior refactoring for `CoroSplit` and `CoroElide`. I agree things aren't in the best shape and the different ABIs can be very confusing and I totally understand the urge to just make things a bit more understandable. 

One thing I noticed during my refactoring: The philosophy differs quite a lot in this space from C++ to Swift. As far as I can tell, the coro stack is not trying to hide Swift semantics, while it's not the case for C++. There are even specific callouts that says, "this is meaningless for C++, but we do it anyway to keep the middle end clean of C++ semantics."

**Comment by ChuanqiXu9** [comment]
Generally we don't do such things since it will make git blaming harder.

**Pull request closed without merging**
