### PR TITLE
[analyzer] Move alpha checker EnumCastOutOfRange to optin

### PR DESCRIPTION
**Pull request by NagyDonat**
The checker EnumCastOutOfRange verifies the (helpful, but not standard-mandated) design rule that integer to enum casts should not produce values that don't have a corresponding enumerator. As it was improved and cleaned up by recent changes, this commit renames it from `alpha.cplusplus.EnumCastOutOfRange` to `optin.core.EnumCastOutOfRange` to reflect that it's no longer alpha quality.

As this checker handles a basic language feature (which is also present in plain C), I moved it to a "core" subpackage within "optin".

In addition to the renaming, this commit cleans up the documentation in `checkers.rst` and adds the new example code to a test file to ensure that it's indeed producing the behavior claimend in the documentation.

### CODE REVIEW

**Comment by gamesh411** [comment]
| OpenSource Project name | New Reports | Reports Lost | Evaluation of reports |
|--------|--------|--------|--------|
| memcached_1.6.8 | [New reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=memcached_1.6.8_baseline&newcheck=memcached_1.6.8_with_enum_cast&is-unique=on&diff-mode=New) | [Lost reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=memcached_1.6.8_baseline&newcheck=memcached_1.6.8_with_enum_cast&is-unique=on&diff-mode=Resolved) | no reports |
| tmux_2.6 | [New reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=tmux_2.6_baseline&newcheck=tmux_2.6_with_enum_cast&is-unique=on&diff-mode=New) | [Lost reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=tmux_2.6_baseline&newcheck=tmux_2.6_with_enum_cast&is-unique=on&diff-mode=Resolved) | no reports |
| curl_curl-7_66_0 | [New reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=curl_curl-7_66_0_baseline&newcheck=curl_curl-7_66_0_with_enum_cast&is-unique=on&diff-mode=New) | [Lost reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=curl_curl-7_66_0_baseline&newcheck=curl_curl-7_66_0_with_enum_cast&is-unique=on&diff-mode=Resolved) | 18 reports, all seem valid, even if some of them are just plain ugly macro expansion-wrapped madness |
| twin_v0.8.1 | [New reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=twin_v0.8.1_baseline&newcheck=twin_v0.8.1_with_enum_cast&is-unique=on&diff-mode=New) | [Lost reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=twin_v0.8.1_baseline&newcheck=twin_v0.8.1_with_enum_cast&is-unique=on&diff-mode=Resolved) | 2 reports, 1 is flag type usage, so this project would want NOT want to opt into this checker
| vim_v8.2.1920 | [New reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=vim_v8.2.1920_baseline&newcheck=vim_v8.2.1920_with_enum_cast&is-unique=on&diff-mode=New) | [Lost reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=vim_v8.2.1920_baseline&newcheck=vim_v8.2.1920_with_enum_cast&is-unique=on&diff-mode=Resolved) | 29 reports, valid, but not really useful for this project |
| openssl_openssl-3.0.0 | [New reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=openssl_openssl-3.0.0-alpha7_baseline&newcheck=openssl_openssl-3.0.0-alpha7_with_enum_cast&is-unique=on&diff-mode=New) | [Lost reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=openssl_openssl-3.0.0-alpha7_baseline&newcheck=openssl_openssl-3.0.0-alpha7_with_enum_cast&is-unique=on&diff-mode=Resolved) | no reports |
| sqlite_version-3.33.0 | [New reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=sqlite_version-3.33.0_baseline&newcheck=sqlite_version-3.33.0_with_enum_cast&is-unique=on&diff-mode=New) | [Lost reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=sqlite_version-3.33.0_baseline&newcheck=sqlite_version-3.33.0_with_enum_cast&is-unique=on&diff-mode=Resolved) | no reports |
| ffmpeg_n4.3.1 | [New reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=ffmpeg_n4.3.1_baseline&newcheck=ffmpeg_n4.3.1_with_enum_cast&is-unique=on&diff-mode=New) | [Lost reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=ffmpeg_n4.3.1_baseline&newcheck=ffmpeg_n4.3.1_with_enum_cast&is-unique=on&diff-mode=Resolved) | 39 reports, not really useful or understandable |
| postgres_REL_13_0 | [New reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=postgres_REL_13_0_baseline&newcheck=postgres_REL_13_0_with_enum_cast&is-unique=on&diff-mode=New) | [Lost reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=postgres_REL_13_0_baseline&newcheck=postgres_REL_13_0_with_enum_cast&is-unique=on&diff-mode=Resolved) | 16 reports, they valid from the coding style enforcing POV |
| tinyxml2_8.0.0 | [New reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=tinyxml2_8.0.0_baseline&newcheck=tinyxml2_8.0.0_with_enum_cast&is-unique=on&diff-mode=New) | [Lost reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=tinyxml2_8.0.0_baseline&newcheck=tinyxml2_8.0.0_with_enum_cast&is-unique=on&diff-mode=Resolved) | no reports |
| libwebm_libwebm-1.0.0.27 | [New reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=libwebm_libwebm-1.0.0.27_baseline&newcheck=libwebm_libwebm-1.0.0.27_with_enum_cast&is-unique=on&diff-mode=New) | [Lost reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=libwebm_libwebm-1.0.0.27_baseline&newcheck=libwebm_libwebm-1.0.0.27_with_enum_cast&is-unique=on&diff-mode=Resolved) | no reports |
| xerces_v3.2.3 | [New reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=xerces_v3.2.3_baseline&newcheck=xerces_v3.2.3_with_enum_cast&is-unique=on&diff-mode=New) | [Lost reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=xerces_v3.2.3_baseline&newcheck=xerces_v3.2.3_with_enum_cast&is-unique=on&diff-mode=Resolved) | 2 reports, not enough context in the bugpath to meaningfully evaluate correctness |
| bitcoin_v0.20.1 | [New reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=bitcoin_v0.20.1_baseline&newcheck=bitcoin_v0.20.1_with_enum_cast&is-unique=on&diff-mode=New) | [Lost reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=bitcoin_v0.20.1_baseline&newcheck=bitcoin_v0.20.1_with_enum_cast&is-unique=on&diff-mode=Resolved) | 3 reports, flag style usage, not relevant |
| protobuf_v3.13.0 | [New reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=protobuf_v3.13.0_baseline&newcheck=protobuf_v3.13.0_with_enum_cast&is-unique=on&diff-mode=New) | [Lost reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=protobuf_v3.13.0_baseline&newcheck=protobuf_v3.13.0_with_enum_cast&is-unique=on&diff-mode=Resolved) | 6 reports at least 2 of them seem valid issues if the code is not properly handling 0 valued enums (I guess this is not the case, but still, these are meaningful findings for developers) |

**Review by gamesh411 — APPROVED** [review]

**Comment by DonatNagyE** [comment]
Before merging this PR, the diagnostics of the EnumCast checker should be updated to mention the name of the `enum` type in question. @gamesh411 could you create a PR that implements this improvement (as we discussed)?

**Comment by haoNoQ** [comment]
> Before merging this PR, the diagnostics of the EnumCast checker should be updated to mention the name of the `enum` type in question. @gamesh411 could you create a PR that implements this improvement (as we discussed)?

Yes, it should call out the enum, call out the value, and then *track* the value (with `trackExpressionValue()`) in order to explain where it's coming from and why we think it's out of range.

**Comment by Xazax-hun** [comment]
How well does this check work with bitwise enums? 

People often write code like:
```
enum AnimalFlags
{
    HasClaws   = 1,
    CanFly     = 2,
    EatsFish   = 4,
    Endangered = 8
};

AnimalFlags operator|(AnimalFlags a, AnimalFlags b)
{
    return static_cast<AnimalFlags>(static_cast<int>(a) | static_cast<int>(b));
}

auto flags = HasClaws | CanFly;
```

Would this warning emit false positives for these patterns? If yes, can/should we suppress them?

**Comment by DonatNagyE** [comment]
@Xazax-hun This checker doesn't accept the use of bitwise enums (like the one in your example), so projects that use bitwise enums should not enable this checker. (Perhaps this limitation should be mentioned in the docs? @gamesh411)

It would be possible to write a more complex checker that recognizes and accepts enums that are used as flags; but I'm not sure that it's a good investment of developer-hours and I think that the current simple&stupid checker is already useful for some projects.

**Comment by steakhal** [comment]
> (Force pushed the branch because I wanted to rebase it onto a recent main and fix the merge conflicts. Is there a better workflow than this?)

I think git also offers conflict resolution for `git merge origin/main`. It should put the resolution into the merge commit.
That being said, I usually just do the rebase/resolve approach and force-push; only after all conversations are resolved and I don't expect anyone reviewing at the time. But yea, a merge commit should be the way for GitHub AFAIK.

**Comment by DonatNagyE** [comment]
> > Before merging this PR, the diagnostics of the EnumCast checker should be updated to mention the name of the `enum` type in question. @gamesh411 could you create a PR that implements this improvement (as we discussed)?
> 
> Yes, it should call out the enum, call out the value, and then _track_ the value (with `trackExpressionValue()`) in order to explain where it's coming from and why we think it's out of range.

These suggestions were mostly implemented in https://github.com/llvm/llvm-project/pull/68191/ , I created PR https://github.com/llvm/llvm-project/pull/74503 to implement the last missing part ("call out the value").

**Comment by DonatNagyE** [comment]
PR https://github.com/llvm/llvm-project/pull/74503 was merged, so I think all the review comments are addressed. @haoNoQ @Xazax-hun What do you think about merging this?

**Comment by Xazax-hun** [comment]
I am a bit concerned about the bad user experience with bitwise enums, but I think that is probably OK since this is an optin check. That being said, I think:
* It would be easy to address this, there is already a clang tidy check for bitwise enums, the heuristics to recognize them could be reused from there and used to suppress bogus warnings.
* As long as this limitation is documented, I am happy to get this merged as is.

**Comment by DonatNagyE** [comment]
The limitation is emphasized in the documentation, and I also added a `TODO` comment that mentions it in the source code.

I'll merge this change as it is now (because I don't want to leave it open for even more time), but @whisperity is interested in this "bitflag enum" case and he'll address these issues when he'll have time for it (in January?).

**Comment by Xazax-hun** [comment]
Sounds good!

**Review by Xazax-hun — APPROVED** [review]

**Comment by nico** [comment]
This breaks check-clang everywhere, e.g.:

https://lab.llvm.org/buildbot/#/builders/139/builds/55404
http://45.33.8.238/linux/125647/step_7.txt

Please take a look and revert for now if it takes a while to fix. (Also, please run tests before committing.)

**Comment by DonatNagyE** [comment]
The issue was really trivial to fix, I created a PR for it: https://github.com/llvm/llvm-project/pull/75216

Sorry for breaking check-clang, I _did_ ran the tests before pressing merge on the github GUI, but I forgot to consider that the GUI button _rebases_ the commit onto the current main tip before merging it, and while the testcase was passing locally, it started to fail when it was rebased onto a version that contained https://github.com/llvm/llvm-project/pull/74503 (which was also added by me).

**Pull request merged**
