### PR TITLE
[llvm][TypeSize] Fix addition/subtraction in TypeSize.

### PR DESCRIPTION
**Pull request by sdesmalen-arm**
It seems TypeSize is currently broken in the sense that:

  TypeSize::Fixed(4) + TypeSize::Scalable(4) => TypeSize::Fixed(8)

without failing its assert that explicitly tests for this case:

  assert(LHS.Scalable == RHS.Scalable && ...);

The reason this fails is that `Scalable` is a static method of class TypeSize,
and LHS and RHS are both objects of class TypeSize. So this is evaluating
if the pointer to the function Scalable == the pointer to the function Scalable,
which is always true because LHS and RHS have the same class.

This patch fixes the issue by renaming `TypeSize::Scalable` ->
`TypeSize::getScalable`, as well as `TypeSize::Fixed` to `TypeSize::getFixed`,
so that it no longer clashes with the variable in FixedOrScalableQuantity.

The new methods now also better match the coding standard, which specifies that:
* Variable names should be nouns (as they represent state)
* Function names should be verb phrases (as they represent actions)

### CODE REVIEW

**Comment by gchatelet** [comment]
Thx for the PR. Can we rename the `Scalable` variable as a separate change?

**Comment by paulwalker-arm** [comment]
Strictly speaking, based on the coding standard the function naming is wrong rather than the variable?

**Comment by sdesmalen-arm** [comment]
@gchatelet I've split out the new feature (adding any value to zero-initialized TypeSize) into a separate PR #72994.
@paulwalker-arm I'm happy to rename the name of TypeSize::Scalable -> TypeSize::getScalable (or something) if there is consensus on the name, but I'd prefer do that in a separate NFC patch.

**Comment by gchatelet** [comment]
The static functions renaming is going to produce a lot of noise but I guess this is too late already...
Shall we revert to keep the change minimal? @nikic @paulwalker-arm WDYT ?

**Review by paulwalker-arm — APPROVED** [review]
It looks like there's a code formatter issue with the MLIR change but otherwise this looks good to me.

**Comment by gchatelet** [comment]
> > The static functions renaming is going to produce a lot of noise but I guess this is too late already... Shall we revert to keep the change minimal? @nikic @paulwalker-arm WDYT ?
> 
> For my money the functions were originally named correctly and then erroneously changed to (a) diverge from the coding standard, and (b) unknowingly introduced a bug caused by the new naming. For both reasons I'm happy to revert to the original naming via this patch.

That would be [my patch](https://reviews.llvm.org/D140263) indeed. Let's revert to the original naming via this patch.

**Review by gchatelet — APPROVED** [review]

**Comment by sdesmalen-arm** [comment]
Thanks @paulwalker-arm @gchatelet!

**Pull request merged**
