### PR TITLE
[X86] With large code model, put functions into .ltext with large section flag

### PR DESCRIPTION
**Pull request by aeubanks**
So that when mixing small and large text, large text stays out of the way of the rest of the binary.

This is useful for mixing precompiled small code model object files and built-from-source large code model binaries so that the the text sections don't get merged.

### CODE REVIEW

**Comment by aeubanks** [comment]
still need to resolve the conversation in https://github.com/llvm/llvm-project/pull/70358, just putting up codegen side of this

**Review by MaskRay — APPROVED** [review]

**Comment by MaskRay** [comment]
On the linker side (I am mostly nervous about), you can use a linker script fragment for the experiment  https://sourceware.org/binutils/docs/ld/Miscellaneous-Commands.html#index-INSERT

On the compiler side, I think we may need something like this. Some JIT large code model users may hard code the `.text` section name and the change could cause them a trouble, so an opt-out option may be needed.

**Comment by aeubanks** [comment]
@lhames are you aware of any issues with hardcoding the `.text` section name?

**Review by rnk — APPROVED** [review]
I think it would be reasonable to move forward and shake out any hidden JIT dependencies on large `.text` sections.

**Comment by aeubanks** [comment]
sounds good, we can revert if anything shows up

**Comment by lhames** [comment]
@aeubanks JIT clients can look up sections by name (and we don't really give them a more structured way to identify sections) so it's possible that some clients are hard-coding searches for `.text`. As far as I know no in-tree code does that though. The risk seems low, and the fix is easy. I think it's reasonable to leave this in-tree and see what (if anything) shakes out.

**Pull request merged**
