### PR TITLE
[InstCombine] Fold `(X & C1) - (X & C2) --> X & (C1 ^ C2)` if `(C1 & C2) == C2`

### PR DESCRIPTION
**Pull request by fengfeng09**
if (C1 & C2) == C2 then (X & C1) - (X & C2) --> X & (C1 ^ C2)

Alive2: https://alive2.llvm.org/ce/z/JvQU8w

### CODE REVIEW

**Comment by dtcxzyw** [comment]
Please read https://llvm.org/docs/InstCombineContributorGuide.html and
+ Provide alive2 proofs
+ Adjust the PR title

**Comment by fengfeng09** [comment]
@dtcxzyw Updated.

**Review by dtcxzyw — APPROVED** [review]
LGTM. Please wait for additional approval from other reviewers.

**Review by nikic — APPROVED** [review]
LGTM

**Pull request merged**
