### PR TITLE
[Clang] Ignore assumptions with side effects at compile time

### LINKED ISSUE #85519: `[[assume(++a)]]` warns that the side-effects will be discarded, but they are not discarded at compile time
```c++
constexpr int a() {
  int a = 0;
  [[assume(++a)]];
  return a;
}
static_assert(a() == 1);

#include <iostream>

int main() {
  std::cout << a() << "\n";
}
```

This code prints `0`, even though the `static_assert` doesn't fail. Clang does print a warning about the side-effects of `++a` being discarded, but that is not true at compile time.

CC @Sirraide

### PR DESCRIPTION
**Pull request by Sirraide**
Fixes #85519.

### CODE REVIEW

**Review by shafik — COMMENTED** [review]
This is not really an NFC change so you should have waited for an approval. This LGTM

**Comment by Sirraide** [comment]
> This is not really an NFC change so you should have waited for an approval.

Yeah, that’s something I wasn’t sure about in this particular case: The code that was causing the problem was added and merged in by me earlier this week, so I figured it was fine (and this seemed like an ‘obvious’ fix seeing as this is what we’re also checking for in codegen), but I can wait for approval next time if a situation like this comes up again.

**Comment by tbaederr** [comment]
Is it expected that a failed assumption with side effects does not result in an error?

```c++
constexpr bool f(int &a) {

    a = 10;
    return false;
}

constexpr int c() {
    int a = 0;
    [[assume(f(a))]];

    return a;
}
static_assert(c() == 0);
```

**Comment by Sirraide** [comment]
> Is it expected that a failed assumption with side effects does not result in an error?

Yes, because it can’t evaluate the assumption without causing side effects, so the assumption isn’t checked at all; I’ve thought about this a bit too, but unless there’s already some way to evaluate an expression at compile time w/o causing any side-effects (neither at runtime nor at compile time), then this is probably the best we can do.

As an aside, GCC also checks assumptions at compile time, and it too ignores assumptions that might have side effects at compile time.

**Comment by Sirraide** [comment]
The standard also says that ‘The expression is not evaluated’ [[dcl.attr.assume]](https://eel.is/c++draft/dcl.attr.assume#sentence-3), so we can only really get away with evaluating it by the as-if rule iff it has no side-effects, so this is just bringing compile-time in line with what we’ve already decided to do in codegen.

**Comment by AaronBallman** [comment]
I think this is also https://eel.is/c++draft/expr.const#6.4, the note is a bit more clear than the standard wording.

**Review by AaronBallman — COMMENTED** [review]
LGTM as well.

**Comment by Sirraide** [comment]
> I think this is also https://eel.is/c++draft/expr.const#6.4, the note is a bit more clear than the standard wording.

That’s also a good point; I sort of forgot about that one. 

Either way, I’ll wait for a review next time seeing as this was perhaps not that ‘obvious’ of a change as I had originally thought.

**Pull request merged**
