### PR TITLE
Reland "[clang] Add nuw attribute to GEPs (#105496)"

### PR DESCRIPTION
**Pull request by hazzlim**
Add nuw attribute to inbounds GEPs where the expression used to form the GEP is an addition of unsigned indices.

Relands #105496, which was reverted because it exposed a miscompilation arising from #98608. This is now fixed by #106512.

### CODE REVIEW

**Review by nikic — APPROVED** [review]
LG if CI is happy.

**Comment by hazzlim** [comment]
Nice - CI seems happy, so I plan to land this later today if no objections.

**Comment by zeux** [comment]
This change leads to a miscompilation; I've extracted a somewhat minimal repro case from the referenced issue above, in the comment: https://github.com/zeux/pugixml/issues/629#issuecomment-2346839855

The code, when compiled with `-O2 -g` by latest clang on Linux/X64, generates the following assembly after the call to `printf` in `get_valid_length`:

```
->  0x555555561270 <+192>: movzx  eax, byte ptr [-0x1]
```

... which, as you can imagine, results in a sigsegv :) This seems to be architecture independent as it initially reproduced in Wasm and also confirmed on Arm.

I *believe* that all accesses in this code are in-bounds and no overflow/underflow happens. The code is silent with `-fsanitize=integer,undefined` when using clang 18.

**Comment by zeux** [comment]
Here's a slightly smaller reproducer that just reads one element from the array. Similarly, this crashes because the compiler generates a load from an absolute `-1` address. The crash is after the first `printf` call in this case during the computation of the argument to the second `printf` call. (the code is fairly non-sensical in this revision, but maybe it helps to analyze this!).

```c++
#include <stdio.h>
#include <stdint.h>
#include <string.h>

class xml_buffered_writer
{
public:
	xml_buffered_writer(): bufsize(0)
	{
	}

	__attribute__((noinline))
	void write_string(const char* data)
	{
		// write the part of the string that fits in the buffer
		size_t offset = bufsize;

		while (*data && offset < bufcapacity)
			buffer[offset++] = *data++;

		// write the rest
		if (offset < bufcapacity)
		{
			bufsize = offset;
		}
		else
		{
			// backtrack a bit if we have split the codepoint
			size_t length = offset - bufsize;
			const char* data_back = data - length;
			printf("length %d\n", int(length));
			printf("last char %c\n", data_back[length-1]);

			bufsize = offset;
		}
	}

	enum
	{
		bufcapacity = 16
	};

	char buffer[bufcapacity];
	size_t bufsize;
};

int main()
{
	xml_buffered_writer writer;
	writer.write_string("abcdefghijklmnopqrstuvwxyz");
	printf("\n");
}
```

**Comment by efriedma-quic** [comment]
Reproduced: https://godbolt.org/z/G4jrhdjef .  Looks like an instcombine bug.

**Comment by nikic** [comment]
Should be fixed by https://github.com/llvm/llvm-project/commit/940f89255e4a3982d94dad57837e8e658092af78.

**Comment by zeux** [comment]
Confirming this fixes the original problem on the larger codebase, thanks!

**Comment by efriedma-quic** [comment]
> Should be fixed by https://github.com/llvm/llvm-project/commit/940f89255e4a3982d94dad57837e8e658092af78.

I quickly glanced through the other uses of setIsInBounds in LLVM; the one in CodeGenPrepare seems suspicious.

**Comment by sbc100** [comment]
I bisecting this emscripten (wasm32-unknown-emscripten) miscompile to this PR: https://github.com/emscripten-core/emscripten/issues/22794.

It looks like llvm is generating a load with a negative office (which is not supported under wasm).   There is a reproducer in that but and I used the following commend to detect the bad load:

```
$ clang++ --target=wasm32-unknown-emscripten -std=c++20 -O2 -c 3.1.71_temps/GltfImporter.ii && wasm-objdump -d GltfImporter.o | grep i64.load.*4294967280
 01c4a3: 29 02 f0 ff ff ff 0f       |               i64.load 2 4294967280
```

Here you can see an i64.load instruction with an offset of 4294967280 (which is -16 interpreted as an unsigned int).

**Comment by nikic** [comment]
@sbc100 That wasm is not necessarily a miscompile, it may be UB in the source program, if it uses a negative number in an *unsigned* variable to index an array. Is the affected code clean under ubsan? (See https://github.com/llvm/llvm-project/issues/108770 for a similar report that was due to UB.)

**Comment by sbc100** [comment]
I used `wasm-reduce` on the `.ll` file and it looks like you were correct.  The result was:

```
target datalayout = "e-m:e-p:32:32-p10:8:8-p20:8:8-i64:64-f128:64-n32:64-S128-ni:1:10:20"
target triple = "wasm32-unknown-emscripten"                                         
                                                                                    
define void @_ZN6Magnum5Trade12GltfImporter6doMeshEjj(ptr %agg.tmp4.i.i.i.i.i) personality ptr null {
entry:                                                                           
  %0 = load i64, ptr inttoptr (i32 -16 to ptr), align 4                          
  store i64 %0, ptr %agg.tmp4.i.i.i.i.i, align 8                                 
  ret void                                                                       
}                                                                                
                                                                                 
; uselistorder directives                                                        
uselistorder ptr null, { 1, 2, 0 }  
```

It looks like there is a -16 to ptr cast in there.  I've ask the reported to try running with `-fsanitize=undefined` and `-fsanitize=address`.  Do you think those will catch this kind of thing?

**Comment by efriedma-quic** [comment]
ubsan pointer overflow check should catch issues in the source code, I think.  If that doesn't work, maybe try opt-bisect-limit to see if it turns up anything useful.

**Pull request merged**
