### PR TITLE
Change check for embedded llvm version number to a regex to make test more flexible.

### PR DESCRIPTION
**Pull request by dyung**
This test started to fail when LLVM created the release/18.x branch and the main branch subsequently had the version number increased from 18 to 19.

I investigated this failure (it was blocking our internal automation) and discovered that the CHECK statement on line 27 seemed to have the compiler version number (1800) encoded in octal that it was checking for. I don't know if this is something that explicitly needs to be checked, so I am leaving it in, but it should be more flexible so the test doesn't fail anytime the version number is changed. To accomplish that, I changed the check for the 4-digit version number to be a regex.

I originally updated this test for the 18->19 transition in a01195ff5cc3d7fd084743b1f47007645bb385f4. This change makes the CHECK line more flexible so it doesn't need to be continually updated.

### CODE REVIEW

**Comment by tstellar** [comment]
It would probably be better just to remove this check.  I don't know why we would need to check the compiler version in the test.

**Comment by dyung** [comment]
> It would probably be better just to remove this check. I don't know why we would need to check the compiler version in the test.

I agree, but if we do need to keep the check, we should at least make it a regex. Or if the version should match something else, then the test should be rewritten to do that.

**Review by tstellar — APPROVED** [review]
Let's merge this now, because this test is failing on the release branch and blocking the release.  We can always clean up the test and remove the  version check in a  later commit.

**Review by ysyeda — APPROVED** [review]
LGTM, thanks

**Comment by dyung** [comment]
@tstellar what is the process for getting commits included on the release branch? Should I open another PR with this change against the release/18.x branch?

**Comment by tstellar** [comment]
> @tstellar what is the process for getting commits included on the release branch? Should I open another PR with this change against the release/18.x branch?

Yes, you can do that.

**Pull request merged**
