### PR TITLE
[SPIR-V] Fix legalize info for G_BITREVERSE

### PR DESCRIPTION
**Pull request by VyacheslavLevytskyy**
This PR fixes legalize info for G_BITREVERSE.

### CODE REVIEW

**Comment by tschuett** [comment]
Drive by nit: Why where there no test changes, when you touched the legalizer?

**Comment by farzonl** [comment]
I think there HLSL should have a `reversebits` test that might be affected by this change, can you confirm?

**Comment by tschuett** [comment]
It originated from https://reviews.llvm.org/D116464, which is a *huge* patch with no tests.

**Review by michalpaszkowski — APPROVED** [review]

**Comment by VyacheslavLevytskyy** [comment]
Failed CI builds are not related to the PR content.

**Pull request merged**
