### PR TITLE
Place strdup in the unix.cstring.NullArg list

### PR DESCRIPTION
**Pull request by fawdlstty**
https://godbolt.org/z/17hs1ojYj

### CODE REVIEW

**Comment by steakhal** [comment]
In the gcc's stadlib, strdup is already marked as `__attribute__ ((__nonnull__ (1))`, which is checked by `core.NonNullParamChecker`. The bug is [caught](https://godbolt.org/z/3fbrx4jT1), as of today.

I don't think there is anything to be done here.

**Comment by steakhal** [comment]
FYI the compiler explorer link you shared does not invoke the static analyzer.

**Comment by fawdlstty** [comment]
@steakhal Hello, thank you for taking the time to review my pr, I'm just trying to complete the documentation, Just a simple typo. should I close?

ref: <https://clang.llvm.org/docs/analyzer/checkers.html#unix-cstring-nullarg-c>

**Comment by steakhal** [comment]
> @steakhal Hello, thank you for taking the time to review my pr, I'm just trying to complete the documentation, Just a simple typo. should I close?
> 
> ref: https://clang.llvm.org/docs/analyzer/checkers.html#unix-cstring-nullarg-c

I looked at the checkers.td, to find out what checker implements the `unix.cstring.NullArg`. It seems like it is done checked by `clang/lib/StaticAnalyzer/Checkers/CStringChecker.cpp`, and in that file I can't see a reference to `"strdup"` or `"wcsdup"`. This implies to me that the checker does not cover any of these functions, hence they are not missing from the docs.

Did I miss something?

**Comment by fawdlstty** [comment]
@steakhal Sorry, I didn't know there was a static checker. I think it should be noted in the documentation for functions whose arguments cannot be 0. May I should check these two functions in the static checker or if I should turn off the pr?

**Pull request closed without merging**
