### PR TITLE
[Sema] Use underlying type of scoped enum for -Wformat diagnostics

### PR DESCRIPTION
**Pull request by smeenai**
Right now, `-Wformat` for a scoped enum will suggest a cast based on the
format specifier being used. This can lead to incorrect results, e.g.
attempting to format a scoped enum with `%s` would suggest casting to
`char *` instead of fixing the specifier. Change the logic to treat the
scoped enum's underlying type as the intended type to be printed, and
suggest format specifier changes and casts based on that.

### CODE REVIEW

**Comment by smeenai** [comment]
Ping.

**Review by cjdb — COMMENTED** [review]
Thanks for working on this, it seems like an important fix. Would you mind updating the release notes please? I'll approve afterwards.

**Comment by smeenai** [comment]
I updated the release notes. I was planning to ask for a pick into 17, but I'll just tweak the release notes for the pick and modify the Clang 18 release notes afterwards if it's accepted.

**Review by cjdb — APPROVED** [review]
LGTM, thanks! Do you require assistance committing?

**Comment by smeenai** [comment]
I have commit access. Thanks for the review!

**Pull request merged**
