### PR TITLE
workflows/release-binaries: Remove .git/config file from artifacts

### PR DESCRIPTION
**Pull request by tstellar**
The .git/config file contains an auth token that can be leaked if the .git directory is included in a workflow artifact.

### CODE REVIEW

**Review by boomanaiden154 — APPROVED** [review]
Did you come across this from the article or was there some scanner involved here?

I'm assuming the token by default won't have a large amount of permissions though and should be ephemeral?

Speaking of that, do we want to tack on a
```yaml
permissions:
  contents: read
```

at the top?

**Comment by tstellar** [comment]
> Did you come across this from the article or was there some scanner involved here?

It's from the article linked in the comment.

> I'm assuming the token by default won't have a large amount of permissions though and should be ephemeral?
> 

The called workflow inherits the caller permissions, so the tokens should be read-only and only usable while the workflow is running. 

> Speaking of that, do we want to tack on a
> 
> ```yaml
> permissions:
>   contents: read
> ```

I'm not sure if the composite actions support top-level permissions, but I'll try it.

**Comment by boomanaiden154** [comment]
> I'm not sure if the composite actions support top-level permissions, but I'll try it.

Ah, it's an action. I did not realize that.

**Review by tru — APPROVED** [review]
LGTM

**Pull request merged**
