### PR TITLE
[mlir][linalg][transform] Rename {masked_vectorize => vectorize => vectorize_children_and...}.

### PR DESCRIPTION
**Pull request by ingomueller-net**
This PR renames the vectorization transform ops as follows:

* `structured.masked_vectorize` => `structured.vectorize`. This reflects the fact that since [recently](https://reviews.llvm.org/D157774) the op can also handle the unmasked case.
* `structured.vectorize` => `structured.vectorize_children_and_applies_patterns`. This reflects the fact that the op does not just vectorize the given payload op but all vectorizable children contained in it, and applies patterns before and after for preparation and clean-up.

This rename was discussed first [here](https://reviews.llvm.org/D157774).

The PR also adapts and cleans ups the tablegen description of the `VectorizeChildrenAndApplyPatternsOp` (formerly `VectorizeOp`).

TODO:
- [x] Agree on new name for the old `VectorizeOp`. (Not everybody seemed happy with `VectorizeChildrenOp`.)
- [x] Rename test files.

### CODE REVIEW

**Comment by ingomueller-net** [comment]
@banach-space, you  [said](https://reviews.llvm.org/D157774#4646902):

> Not sure about `VectorizeChildren` - that op does quite a bit more than plain vectorization.

Do you have a suggestion? I don't fully understand what the op does...

**Comment by banach-space** [comment]
> @banach-space, you [said](https://reviews.llvm.org/D157774#4646902):
> 
> > Not sure about `VectorizeChildren` - that op does quite a bit more than plain vectorization.
> 
> Do you have a suggestion? I don't fully understand what the op does...

It would be great to get input from folks who worked on this originally (perhaps @nicolasvasilache or @dcaballe). My suggestion would be: `VectorizeAndApplyPatterns`.

**Comment by nicolasvasilache** [comment]
Let's call it `VectorizeChildrenAndApplyPatterns` for now. 
This op should be retired and replaced by only masked_vectorize followed by the proper apply_patterns now that it is possible to do so.

**Comment by ingomueller-net** [comment]
I have just applied @nicolasvasilache's suggestion and clean up the title and description of the PR. If we adopt this suggestion, then there are no further changes I plan to make. I'll wait for further opinions on the name a bit more, though, in case there is more discussion required.

**Review by nicolasvasilache — APPROVED** [review]

**Comment by ftynse** [comment]
This needs a PSA/refactoring notice. Scripts that were relying on function-wide vectorization now stopped working for no good reason.

**Comment by ingomueller-net** [comment]
> This needs a PSA/refactoring notice. Scripts that were relying on function-wide vectorization now stopped working for no good reason.

Thanks for making we aware of this, @ftynse! What's the bar for a change to require such an announcement? Some of my previous commits also have the potential to break existing code (adding a mix-in with fewer parameters means that existing constructor calls stop working). Is it because IR/assembly is involved?

**Comment by ftynse** [comment]
IMO, small changes like adding parameters is fine to just land. So are simple renamings. Those are rather obvious to detect and fix by simply reading the log of recent commits. What makes this stand out is that it reuses the name for an almost completely different operation. Imagine changing `scf.for` to become a "while" loop while retaining the name, this sounds extreme but conceptually close here.

**Pull request merged**
