### PR TITLE
[Clang][Sema] Revert changes to operator= lookup in templated classes from #91498, #90999, and #90152

### PR DESCRIPTION
**Pull request by sdkrystian**
This reverts changes in #91498, #90999, and #90152 which make `operator=` dependent wherever the current class is templated.

### CODE REVIEW

**Review by erichkeane — APPROVED** [review]
This reverts the problematic parts of the previous patch too, right?  If so, LGTM.

**Comment by sdkrystian** [comment]
Is it alright to partially revert commits in a single PR? If so, I'm just going to revert all the `operator=` related changes from #91498, #90999, and #90152.

**Comment by aeubanks** [comment]
should be fine to revert as much as you want in a single PR, just make sure to mention what you're reverting in the description

**Comment by erichkeane** [comment]
> should be fine to revert as much as you want in a single PR, just make sure to mention what you're reverting in the description

Agreed, a revert doesnt have to be a single commit, or even a whole one.  Just enough to get us back to a 'working' state is fine.

Though if you do 'partial' ones, I prefer to not REMOVE tests, but to put a FIXME on the tests you've reverted and fix their test lines (assuming they dont' crash)

**Pull request merged**
