### PR TITLE
Revert "[flang][Driver] Let the linker fail on multiple definitions of main()"

### PR DESCRIPTION
**Pull request by tblah**
Reverts llvm/llvm-project#73124

This caused a regression building programs which implement `main()` in C and then call into some Fortran code, and which link using `flang-new`.

reproducer:
main.c
```
int main(void) {
  // call fortran code
  return 0;
}
```
fortran.f90
```
function pow(a, b)
  real :: a, b, pow
  pow = a ** b
end function
! note: no PROGRAM statement
```
```
clang -c main.c -o main.o
flang-now -c fortran.f90 -o fortran.o
flang-new fortran.o main.o -o out
```
This can be built with gfortran

### CODE REVIEW

**Comment by tblah** [comment]
For what it's worth, `armflang` follows gfortran's behavior.

As there isn't consensus amongst fortran compilers, I'm unsure which behavior we should follow. What do other's think?

**Comment by mjklemm** [comment]
> For what it's worth, `armflang` follows gfortran's behavior.

So does the "old legacy flang", which I guess is the basis for armflang.  AOCC's flang shows the same behavior.


> As there isn't consensus amongst fortran compilers, I'm unsure which behavior we should follow. What do other's think?

I guess, we could agree that the current behavior of flang-new ignoring the Fortran program unit is present, is not correct either. :-)

Could please see if `-Wl,--allow-multiple-definition` would help to resolve the issue in the application?

**Comment by mjklemm** [comment]
BTW, flang legacy has this: `  -fno-fortran-main       Don't link in Fortran main` 

Adding that command line option might be the right choice.  If everyone agrees, I can see if I can get this added.

**Comment by tblah** [comment]
> Could you please see if `-Wl,--allow-multiple-definition` would help to resolve the issue in the application?

Surprisingly not. 
```
ld.lld: error: undefined symbol: _QQEnvironmentDefaults
>>> referenced by Fortran_main.c
>>>               Fortran_main.c.o:(.text.main+0x8) in archive [...]/libFortran_main.a
>>> referenced by Fortran_main.c
>>>               Fortran_main.c.o:(.text.main+0xC) in archive [...]/lib/libFortran_main.a

ld.lld: error: undefined symbol: _QQmain
>>> referenced by Fortran_main.c
>>>               Fortran_main.c.o:(.text.main+0x18) in archive [...]/lib/libFortran_main.a
flang-new: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by mjklemm** [comment]
I have opened PR #74139 to provide an alternate solution to this.  Please have a look there.

@tblah Would you mind trying this new option with one application code to see if that will help?

**Comment by tblah** [comment]
Closing because this was superseded by https://github.com/llvm/llvm-project/pull/74139

**Pull request closed without merging**
