### PR TITLE
[workflows] Only build native targets in ci-ubuntu-22.04 container

### PR DESCRIPTION
**Pull request by tstellar**
This should help reduce the build times.

### CODE REVIEW

**Review by boomanaiden154 — APPROVED** [review]
LGTM. I didn't realize that the second and third stages didn't already use a native-only build, although it makes a lot of sense in hindsight.

**Comment by tstellar** [comment]
This did not work as expected.  I'm looking into it.

**Comment by tstellar** [comment]
I see the issue.  The 3 stages already build the native target only, but when llvm is built to generate the training data, it enables all the targets.

**Comment by tstellar** [comment]
It turns out we don't need this, closing.

**Pull request closed without merging**
