### PR TITLE
[llvm-exegesis][unittests] Also disable SubprocessMemoryTest on SPARC

### PR DESCRIPTION
**Pull request by rorth**
Three `llvm-exegesis` tests
```
  LLVM-Unit :: tools/llvm-exegesis/./LLVMExegesisTests/SubprocessMemoryTest/DefinitionFillsCompletely
  LLVM-Unit :: tools/llvm-exegesis/./LLVMExegesisTests/SubprocessMemoryTest/MultipleDefinitions
  LLVM-Unit :: tools/llvm-exegesis/./LLVMExegesisTests/SubprocessMemoryTest/OneDefinition
```
`FAIL` on Linux/sparc64 like
```
llvm/unittests/tools/llvm-exegesis/X86/SubprocessMemoryTest.cpp:68: Failure
Expected equality of these values:
  SharedMemoryMapping[I]
    Which is: '\0'
  ExpectedValue[I]
    Which is: '\xAA' (170)
```
It seems like this test only works on little-endian hosts: three sub-tests are already disabled on powerpc and s390x (both big-endian), and the fourth is additionally guarded against big-endian hosts (making the other guards unnecessary).

However, since it's not been analyzed if this is really an endianess issue, this patch disables the whole test on powerpc and s390x as before adding sparc to the mix.

Tested on `sparc64-unknown-linux-gnu` and `x86_64-pc-linux-gnu`.

### CODE REVIEW

**Review by boomanaiden154 — COMMENTED** [review]
There is only one test here that should actually be dependent on endianness (the one marked explicitly).

I've never run this test on a big-endian system myself to debug, so I can't say for sure, but I would suspect that there is a different issue (the zero value is really suspicious from your test failures)

Ultimately though, this test is for functionality that is only enabled on x86_64. I'd rather not carve out x86_64 specifically to prevent people missing this on bringup though.

I'm not opposed to this patch, but I'd probably prefer a carve out specific to Sparc pending more investigation.

**Comment by rorth** [comment]
> There is only one test here that should actually be dependent on endianness (the one marked explicitly).
> 
> I've never run this test on a big-endian system myself to debug, so I can't say for sure, but I would suspect that there is a different issue (the zero value is really suspicious from your test failures)

I see.  I'd rather not try this myself since I've just spent 3 days digging through a large and completely unfamilier part of the code base to fix two failing tests.

> Ultimately though, this test is for functionality that is only enabled on x86_64. I'd rather not carve out x86_64 specifically to prevent people missing this on bringup though.
> 
> I'm not opposed to this patch, but I'd probably prefer a carve out specific to Sparc pending more investigation.

So would it be ok to move the `!(powerpc || s390x || sparc)` check up as in the revised patch?

**Review by boomanaiden154 — APPROVED** [review]
LGTM.

**Pull request merged**
