### PR TITLE
[libunwind][nfc] Avoid type warning of debug printf

### PR DESCRIPTION
**Pull request by kaz7**
Change PRIu32 to PRIxPTR to avoid type warning of debug printf since VE uses 64 bits SjLj.  I don't use PRIuPTR since the print message has 0x-prefix from the beginning.  I also change related PRIuPTR to PRIxPTR since those uses 0x-prefix too.

### CODE REVIEW

**Review by arichardson — COMMENTED** [review]
Could also use %p instead of `0x% Pri*`and cast the `uintptr_t` to `void *`? That would avoid the need for the new macros.

**Comment by arichardson** [comment]
Or alternatively use PRIxPTR unconditionally, using PRIuPTR with 0x-prefixed outputs is super confusing

**Comment by kaz7** [comment]
@arichardson Thank for your kind comment.  I confused them already.  I update my patch following your 2nd suggestion.

**Comment by kaz7** [comment]
Update the top comment to describe what I modify.

**Review by arichardson — APPROVED** [review]
Change LGTM assuming CI is also happy.

**Pull request merged**
