### PR TITLE
[rtsan] Link in proper CXX ABI library

### PR DESCRIPTION
**Pull request by cjappl**
Based on an issue reported in #109529  ([comment](https://github.com/llvm/llvm-project/pull/109529#issuecomment-2368924039), [build problem](https://ci.chromium.org/ui/p/fuchsia/builders/toolchain.ci/clang-mac-x64/b8736170060997779425/blamelist) )

We seemingly were having issues with compiling/linking against different ABIs:

```
undefined symbol for arch arm64: std::__2::__libcpp_verbose_abort(
...
did you mean: std::__1::__libcpp_verbose_abort(
```

I cannot reproduce this issue locally, but this fix seems to be in the same general area.

This new pattern was found in all of the other sanitizer's cmakelists.txt, making me think this is our problem

```
nsan/CMakeLists.txt
44-
45-set(NSAN_DYNAMIC_LIBS
46:  ${COMPILER_RT_UNWINDER_LINK_LIBS}
47-  ${SANITIZER_CXX_ABI_LIBRARIES}
48-  ${SANITIZER_COMMON_LINK_LIBS})

ubsan/CMakeLists.txt
65-
66-set(UBSAN_DYNAMIC_LIBS
67:  ${COMPILER_RT_UNWINDER_LINK_LIBS}
68-  ${SANITIZER_CXX_ABI_LIBRARIES}
69-  ${SANITIZER_COMMON_LINK_LIBS})

tsan/rtl/CMakeLists.txt
14-
15-set(TSAN_DYNAMIC_LINK_LIBS
16:  ${COMPILER_RT_UNWINDER_LINK_LIBS}
17-  ${SANITIZER_CXX_ABI_LIBRARIES}
18-  ${SANITIZER_COMMON_LINK_LIBS})

asan/CMakeLists.txt
145-
146-set(ASAN_DYNAMIC_LIBS
147:  ${COMPILER_RT_UNWINDER_LINK_LIBS}
148-  ${SANITIZER_CXX_ABI_LIBRARIES}
149-  ${SANITIZER_COMMON_LINK_LIBS})
```

### CODE REVIEW

**Comment by cjappl** [comment]
@zeroomega Can you please try this patch and see if it works to fix your issue? I cannot repro locally.

**Comment by cjappl** [comment]
CC @davidtrevelyan for review

**Comment by cjappl** [comment]
Also adding @petrhosek as it looks like he performed the original change to the sanitizers to use this version of CXX ABI linking

**Comment by zeroomega** [comment]
> @zeroomega Can you please try this patch and see if it works to fix your issue? I cannot repro locally.

It still failed at the same spot.

**Comment by cjappl** [comment]
Thanks for looking, I will continue investigating.

Is there any easy way for me to run builds against this system for me to verify any potential fixes without bugging you?

**Comment by zeroomega** [comment]
> Thanks for looking, I will continue investigating.
> 
> Is there any easy way for me to run builds against this system for me to verify any potential fixes without bugging you?

If you have a branch in your public repo, I can launch a build job for you. You can ping me on discord. I am 'zeroomega86' on discord. Please rebase your branch against upstream main branch. 

e.g. I uses https://github.com/zeroomega/llvm-project/commit/642d4c813663fce79f787e0fcb59e9b209f5464c to instrument the build file. The build task is https://ci.chromium.org/ui/p/fuchsia/builders/toolchain.ci.shadow/clang-mac-x64/b8735967159680657121/overview 

You can see output:

```
in asan RTSAN_LINK_LIBS is 
in asan SANITIZER_CXX_ABI_LIBRARIES is 
in asan SANITIZER_COMMON_LINK_LIBS is c
in rtsan RTSAN_LINK_LIBS is c++;c
in rtsan SANITIZER_CXX_ABI_LIBRARIES is c++;c
in rtsan SANITIZER_COMMON_LINK_LIBS is c
```

In https://logs.chromium.org/logs/fuchsia/buildbucket/cr-buildbucket/8735967159680657121/+/u/clang/build/stdout

**Comment by cjappl** [comment]
Thanks @zeroomega - looking into this now a bit further. I will ping you when I have something to build.

**Comment by cjappl** [comment]
I am stopping for the night with no significant progress, I'll pick it back up tomorrow.

**Review by MaskRay — APPROVED** [review]

**Comment by cjappl** [comment]
@MaskRay or @vitalybuka  should it be possible to use the STL, like `std::variant` in the sanitizer runtimes?

We introduced `std::variant` and `std::visit` to rtsan in this PR (https://github.com/llvm/llvm-project/pull/109529/files)

But after doing some searching, it seems like not many STL containers/algorithms are in compiler-rt. I'm wondering if we made a mistake going this direction.

**Comment by zeroomega** [comment]
@cjappl I did some experiment later and I discovered that if I change `SHARED` to `STATIC` at https://github.com/llvm/llvm-project/blob/3734fa8c724ce2af2f69886ca97c05c6c3717c34/compiler-rt/lib/rtsan/CMakeLists.txt#L76 (without applying #109715). The build step will pass without issue.

In our build setup, we set `LIBCXXABI_ENABLE_SHARED` to `OFF` for all platforms, including mac. I think what is happening is that when that line was set to SHARED, it was trying to find `libc++.dylib` from the build directory, which didn't exist, so it found the host's libc++.dylib instead, which uses a different ABI.

Is there a reason why on mac it requires to build rtsan as a shared library but static for other platform?

**Comment by vitalybuka** [comment]
> @MaskRay or @vitalybuka should it be possible to use the STL, like `std::variant` in the sanitizer runtimes?
> 
> We introduced `std::variant` and `std::visit` to rtsan in this PR (https://github.com/llvm/llvm-project/pull/109529/files)
> 
> But after doing some searching, it seems like not many STL containers/algorithms are in compiler-rt.
> 
> I'm wondering if we made a mistake going this direction or if we just have some easily solvable configuration issue.

There could be multiple problems:
1. Linking C++ runtime maybe be required even for C binaries.
1. Also C++ binary can be linked with different vendor or version of stdlib.
1. Allocator or interceptors can be triggered.

**Comment by davidtrevelyan** [comment]
Many thanks @vitalybuka - understood. Thanks everyone for the valuable inputs, I've drafted a PR for removing the `std::variant` in rtsan here: https://github.com/llvm/llvm-project/pull/109786

**Pull request merged**
