### PR TITLE
[Flang] Testcase changes to switch directories before rm (NFC)

### PR DESCRIPTION
**Pull request by madanial0**
In AIX, the following testcase fails in attempt to delete the current directory, exiting current directory before removing

### CODE REVIEW

**Comment by madanial0** [comment]
> What's TC? :) Also, wouldn't `cd -` more future-proof?

TC is test case, I switched it to avoid confusions sorry! I agree `cd -` is more future-proof

**Review by banach-space — APPROVED** [review]
LGTM, thanks!

**Comment by banach-space** [comment]
@madanial0 Do you have commit access? If yes then it's fine to land this. If not, I can land it for you ;-)

**Comment by madanial0** [comment]
> @madanial0 Do you have commit access? If yes then it's fine to land this. If not, I can land it for you ;-)

I do, I was just waiting for the latest checks after rebase

**Pull request merged**
