### PR TITLE
[X86][AVX10] Fix a bug when using -march with no-evex512 attribute

### LINKED ISSUE #72106: Regression since "[X86][AVX10] Permit AVX512 options/features used together with AVX10 (#71318)"
Since f229ba4e8d6bb24622b2d41b3c89585cb9005d8d, "[X86][AVX10] Permit AVX512 options/features used together with AVX10 (#71318)", some uses/configurations of x86 intrinsics fail. This happens if trying to configure Qt for x86_64, where the Qt cmake configuration fails with the following error:

```
ERROR: x86 intrinsics support missing. Check your compiler settings. If this is an
error, report at https://bugreports.qt.io with your compiler ID and version,
and this output: 

${TEST_x86intrin_OUTPUT} 
```
This is a regression, as builds of Clang prior to f229ba4e8d6bb24622b2d41b3c89585cb9005d8d can build the same version of Qt just fine.

The failing test for x86 intrinsics can be reduced down to this:
```c
#include <immintrin.h>   
int main(int argc, char **argv) {
    __m256i ptrs = _mm256_maskz_loadu_epi64(0, argv);
    return 0; 
}
```
```console
$ clang -target x86_64-linux-gnu -march=cannonlake -c intrin-regression.c
In file included from intrin-regression.c:1:
In file included from /home/martin/clang-nightly-sat/lib/clang/18/include/immintrin.h:109:
/home/martin/clang-nightly-sat/lib/clang/18/include/avx512vlintrin.h:5552:18: error: always_inline function '_mm256_setzero_si256' requires target feature 'evex512', but would be inlined into function '_mm256_maskz_loadu_epi64' that is compiled without support for 'evex512'
 5552 |                  _mm256_setzero_si256 (),
      |                  ^
1 error generated.
```

CC @phoebewang

### PR DESCRIPTION
**Pull request by phoebewang**
#71318 failed to clear EVEX512 feature for intended intrinsics.

Fixes #72106

### CODE REVIEW

**Comment by ronlieb** [comment]
i applied the proposed patch on top of latest and the build issues are gone.

**Review by RKSimon — APPROVED** [review]
LGTM

**Comment by ronlieb** [comment]
ok to land,

**Review by ronlieb — APPROVED** [review]

**Review by KanRobert — APPROVED** [review]
LGTM

**Review by e-kud — APPROVED** [review]
Interesting. LGTM

**Comment by ronlieb** [comment]
thanks for the fix, working great now.

**Pull request merged**
