### PR TITLE
[sanitizers] improve debug output for failed suppression parse

### PR DESCRIPTION
**Pull request by schenker**
If a sanitizer suppression file can not be parsed, add the supported suppression types to the error message.

See https://github.com/llvm/llvm-project/issues/72060.

### CODE REVIEW

**Review by vitalybuka — CHANGES_REQUESTED** [review]
LGTM, but would you like to copy llvm-project/compiler-rt/test/asan/TestCases/Linux/asan_default_suppressions.cpp into sanitizer_common test and check for the message?

You will need to define __{a,l,m,t,hw,ub}san_default_suppressions.

**Comment by schenker** [comment]
@vitalybuka I implemented the tests a bit different, does that work for you?

**Comment by schenker** [comment]
ping

**Review by vitalybuka — APPROVED** [review]

**Comment by schenker** [comment]
is anything else necessary for this to be merged?

**Comment by vitalybuka** [comment]
Sorry, some member just need to press the button.

**Pull request merged**
