### PR TITLE
Convert ThreadPlanStack's mutex to a shared mutex.

### PR DESCRIPTION
**Pull request by jimingham**
I have some reports of A/B inversion deadlocks between the ThreadPlanStack and the StackFrameList accesses.  There's a fair bit of reasonable code in lldb that does "While accessing the ThreadPlanStack, look at that threads's StackFrameList", and also plenty of "While accessing the ThreadPlanStack, look at the StackFrameList."

In all the cases I've seen so far, there was at most one of the locks taken that were trying to mutate the list, the other three were just reading.  So we could solve the deadlock by converting the two mutexes over to shared mutexes.

This patch is the easy part, the ThreadPlanStack mutex.  

The tricky part was because these were originally recursive mutexes, and  recursive access to shared mutexes is undefined behavior according to the C++ standard, I had to add a couple NoLock variants to make sure it didn't get used recursively.  Then since the only remaining calls are out to ThreadPlans and ThreadPlans don't have access to their containing ThreadPlanStack, converting this to a non-recursive lock should be safe.

### CODE REVIEW

**Review by JDevlieghere — COMMENTED** [review]
Mechanically this change looks good, plus I'm always happy to see another recursive mutex go. 

One side-effect of this change is that previously, the `ThreadPlanStack` mutex was indirectly protecting some operations on `ThreadPlan`s too. For example, `ThreadPlan::ClearThreadCache` isn't protected by a mutex, but `ThreadPlanStack::ClearThreadCache` used to be. Assuming the only way multiple threads would interact with this function is through the `ThreadPlanStack`*, we now have a potential race because of the reader-lock, while previously this was indirectly protected by the unique lock. I don't know the ThreadPlans enough to determine if that's a problem or not. 

[*] Because otherwise this was already race-y.

**Comment by jimingham** [comment]
That is a "resource deadlock detected" error, so presumably we are managing to recursively use this ThreadPlanStack lock.  I'm a bit confused that none of the stacks printed actually show any ThreadPlanStack functions on the stack???

**Comment by jimingham** [comment]
Ah, right.  The one place where a ThreadPlan should be messing with the ThreadPlanStack (through its Thread) is ThreadPlan::DidPush.  The point of that is largely that thread plans can't push new thread plans on the stack in their constructor - since they aren't on the stack yet.  However there are plans that work by delegating so they need to push the delegate plan before getting asked any questions.   That's what DidPush is for.

**Review by labath — APPROVED** [review]
+1 to what Jonas said :)

**Comment by jimingham** [comment]
The ThreadPlans themselves don't lock access to their state as it stands now.  That's not really a problem because ThreadPlans only mutate their state in the course of the ThreadList::ShouldStop process, which happens before the new ThreadPlanStack is accessible to other parts of lldb - since we aren't formally stopped yet.  By the time general code is accessing them, they are just reporting already computed data.

Note if concurrent access to ThreadPlans were a problem, this change wouldn't substantially affect that.  We don't delegate the tasks that do the majority of the work - like `ThreadPlan::ShouldStop` - to the ThreadPlanStack, we find elements of the stack, and query them directly.  

I'm not sure how to express this more formally.  We'd have to have a couple of domains for handling ThreadPlans, one that happens serially before anything but the ShouldStop mechanism sees the newly stopped Thread, and one that happens when generic code is asking questions.  The former domain is a "writer domain" and the latter a "reader domain".  

This is currently enforced informally because the "writer domain" functions aren't useful once you've stopped, and the things the thread plans store don't get computed lazily.

Also, all the changes where I substituted the recursive_mutex with the Writer lock are protected the same way they were before, so we only need to look at the ones that have the Reader lock. The only ones of those that might do work in the ThreadPlans are:

ThreadPlanStack::GetReturnValueObject
ThreadPlanStack::GetExpressionVariable
ThreadPlanStack::ClearThreadCache

In practice those three shouldn't be a problem.  In all the extant uses, the first two aren't actually modifying, they always read out a value that was cached previously.  So those are really reader operations.  ClearThreadCache should only happen as part of preparing for a stop, before we've made any Threads (and so any ThreadPlanStack's) available to general-purpose code.  That's an example of a call that really only makes sense as part of ShouldStop.

**Pull request merged**
