### PR TITLE
Reapply "[Clang][Sema] Fix crash when 'this' is used in a dependent class scope function template specialization that instantiates to a static member function (#87541)"

### PR DESCRIPTION
**Pull request by sdkrystian**
Reapplies #87541 and addresses the bug which caused expressions naming overload sets to be incorrectly rebuilt.

### CODE REVIEW

**Review by erichkeane — COMMENTED** [review]
Can you point out the 'diff' from the last patch for me?

**Comment by sdkrystian** [comment]
@erichkeane Apologies, I should have structured the commits differently so it's clear what the new changes are...

I added an `IsAddressOfOperand` parameter to `TreeTransform::TransformUnresolvedLookupExpr` and changed the conditions under which `Sema::BuildPossibleImplicitMemberExpr` is called to match those in `Sema::ActOnIdExpression`.

**Review by erichkeane — APPROVED** [review]
Can you add the example that caused the revert to the tests?

Else, LGTM.

**Comment by rupprecht** [comment]
Still seeing a few more failures, although the original repro is now working.

```c++
struct Base {
    int BaseFunc(int x) { return 0; }
    int val;
};

template <typename T>
struct Foo : Base {
    template <typename X>
    int bar(X x) {
        return BaseFunc(val);  // OK
    }

    template <>
    int bar(double x) {
        return BaseFunc(0);  // error: call to non-static member function without an object argument
    }

    template <>
    int bar(int x) {
        return BaseFunc(val);  // error: no matching function for call to 'BaseFunc'
        // note: candidate function not viable: no overload of 'val' matching 'int' for 1st argument
    }
};
```

https://godbolt.org/z/Yn1jbGqW3

We also see a `reference to overloaded function could not be resolved; did you mean to call it?`, but I haven't been able to reduce that yet.

**Comment by sdkrystian** [comment]
@rupprecht looks like the issue is with non-static members in base classes:
```cpp
struct B
{
    int z;
    void h(int);
};

template<typename T> 
struct A : B
{
    int y;
    void g(int);

    template<typename U>
    void f(U); 

    template<>
    void f(int x)
    {
        x;
        y;
        z; // error: reference to overloaded function could not be resolved
        g(x);
        g(y);
        g(z);
        g(0);
        h(x); // error: call to non-static member function without an object argument
        h(y);
        h(z); // error: no matching function for call to 'h'
        h(0); // error: call to non-static member function without an object argument
    }
};

template struct A<int>; 
```
I'll look into this and see whether it's a trivial fix. If not, I'll revert.

**Comment by sdkrystian** [comment]
The expression type need to be set to `ASTContext::DependentTy` (currently, it's set to `ASTContext::OverloadTy`) if we find a member of a base class (as it is for direct members). Should be an easy fix, so I'm thinking of not reverting and just opening a PR that will address this.

**Pull request merged**
