### PR TITLE
[Clang] SemaFunctionEffects: Fix bug where lambdas produced by template expansion weren't verified.

### PR DESCRIPTION
**Pull request by dougsonos**
Lambdas are added to the list of Decls to verify using `Sema::maybeAddDeclWithEffects()`. Up until now this call was in  `ActOnLambdaExpr`, which happens in the context of a template but not in the context of template expansion.

Template expansion calls `BuildLambdaExpr`, so move the call to `Sema::maybeAddDeclWithEffects()` there.

Fixing this created a not-previously-seen situation where the custom "In template expansion here" diagnostic didn't have a valid location. This breaks tests because there's a note with no location. For now I've just skipped emitting the diagnostic but maybe there's a better solution.

### CODE REVIEW

**Review by Sirraide — APPROVED** [review]
Ah yeah, I should have noticed that in review: `ActOnX` is generally only called during parsing, whereas `BuildX` is also called during template instantiation.

As for the template notes, I don’t have a good solution for those either...

Also, we *do* have tests for function templates and generic lambdas, right? If not, we should definitely add some.

**Comment by dougsonos** [comment]
Thanks for the quick look.

> Ah yeah, I should have noticed that in review: `ActOnX` is generally only called during parsing, whereas `BuildX` is also called during template instantiation.

I actually do think it might have come up early in one of the giant reviews, but gotten lost amongst the bigger issues.

> Also, we _do_ have tests for function templates and generic lambdas, right? If not, we should definitely add some.

Something like:

```c++
template <typename T>
void TemplatedFunc(T x) [[clang::nonblocking]] {
	auto* ptr = new T; // expected-warning {{function with 'nonblocking' attribute must not allocate or deallocate memory}}
}

template <typename T>
auto TemplatedLambda = [](T x) [[clang::nonblocking]] {
	auto* ptr = new T; // expected-warning {{lambda with 'nonblocking' attribute must not allocate or deallocate memory}}
};

void nb9b() [[clang::nonblocking]] {
	TemplatedFunc(42); // expected-note {{in template expansion here}}
	TemplatedLambda<int>(42);
}
```
?

**Comment by Sirraide** [comment]
> Something like:

The function template is pretty much what I meant, yeah, but by ‘templated lambda’ I meant either one that is an implicit template because one of its parameters is declared with `auto` (`[](auto x)`) or one that has an explicit template parameter list (`[]<typename T>`).

**Review by cor3ntin — APPROVED** [review]
LGTM

**Pull request merged**
