### PR TITLE
[libc++][docs] Add 2024-11 LWG papers/issues and CWG papers needing library changes to the lists

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
LWG issue list from https://wg21.link/P3504R0.

Some are already implemented. The status will be set in another PR.
- LWG4084 and LWG4140 were already implemented at the initial commit.
- LWG3216 should have been implemented together with LWG3870 in 19c6958d24acf5beaba1946ad3e1e5fc538e3a2d.
- LWG4024 was implemented together with P1020R1 + P1973R1 in 9af9d39a47dc634b7de17708a4daf226ca699751.
- LWG4124 was implemented when initially implementing `zoned_time` formatters in afbfb16d294af2fd4f6fb3c37bb07b274adef8bc.
- LWG4141 can be considered implemented together with P0323R12 in e356f681f6c46ac35f933dc0cef3b25ceee8b210.
- LWG4157 was implemented together with P2167R3 in 557f7e1398e13c0957c7a0cbc013c1468f47a237.

Some are possibly implemented.
- LWG4154 was possibly implemented at the initial commit. Check needed.

Some seem nothing to do, but need additional check.
- It seems that LWG4064 and LWG4144 should be handled by compiler frontends.
- LWG4170 seems to only strengthen requirement on user codes, but we need to ensure that we don't provide any non-conforming contiguous iterator.

### CODE REVIEW

**Comment by ldionne** [comment]
Can you also add those to the C++26 papers?

```
"`P3136R1 <https://wg21.link/P3136R1>`__","Retiring niebloids","2024-11 (Wrocław)","","",""
"`P3138R5 <https://wg21.link/P3138R5>`__","views::cache_latest","2024-11 (Wrocław)","","",""
"`P3379R0 <https://wg21.link/P3379R0>`__","Constrain std::expected equality operators","2024-11 (Wrocław)","","",""
"`P0472R2 <https://wg21.link/P0472R2>`__","Put std::monostate in utility","2024-11 (Wrocław)","","",""
"`P2862R1 <https://wg21.link/P2862R1>`__","text_encoding::name() should never return null values","2024-11 (Wrocław)","","",""
"`P2897R7 <https://wg21.link/P2897R7>`__","aligned_accessor: An mdspan accessor expressing pointer over-alignment","2024-11 (Wrocław)","","",""
"`P3355R1 <https://wg21.link/P3355R1>`__","Fix submdspan for C++26","2024-11 (Wrocław)","","",""
"`P3222R0 <https://wg21.link/P3222R0>`__","Fix C++26 by adding transposed special cases for P2642 layouts","2024-11 (Wrocław)","","",""
"`P3050R2 <https://wg21.link/P3050R2>`__","Fix C++26 by optimizing linalg::conjugated for noncomplex value types","2024-11 (Wrocław)","","",""
"`P3396R1 <https://wg21.link/P3396R1>`__","std::execution wording fixes","2024-11 (Wrocław)","","",""
"`P2835R7 <https://wg21.link/P2835R7>`__","Expose std::atomic_ref's object address","2024-11 (Wrocław)","","",""
"`P3323R1 <https://wg21.link/P3323R1>`__","cv-qualified types in atomic and atomic_ref","2024-11 (Wrocław)","","",""
"`P3508R0 <https://wg21.link/P3508R0>`__","Wording for constexpr for specialized memory algorithms","2024-11 (Wrocław)","","",""
"`P3369R0 <https://wg21.link/P3369R0>`__","constexpr for uninitialized_default_construct","2024-11 (Wrocław)","","",""
"`P3370R1 <https://wg21.link/P3370R1>`__","Add new library headers from C23","2024-11 (Wrocław)","","",""
"`P3309R3 <https://wg21.link/P3309R3>`__","constexpr atomic and atomic_ref","2024-11 (Wrocław)","","",""
"`P3019R11 <https://wg21.link/P3019R11>`__","indirect and polymorphic: Vocabulary Types for Composite Class Design","2024-11 (Wrocław)","","",""
"`P1928R15 <https://wg21.link/P1928R15>`__","std::simd — merge data-parallel types from the Parallelism TS 2","2024-11 (Wrocław)","","",""
"`P3325R5 <https://wg21.link/P3325R5>`__","A Utility for Creating Execution Environments","2024-11 (Wrocław)","","",""
"","","","","",""
```

(perhaps worth double-checking them)

**Comment by ldionne** [comment]
Also, would it be possible to defer to another patch before marking anything as complete? I am experimenting with the workflow to create the corresponding Github issues and I think it's easier if we first create them, and then mark them as implemented when relevant.

**Comment by frederick-vs-ja** [comment]
> Can you also add those to the C++26 papers?

I'll do so. Moreover, [P3068R6](https://wg21.link/P3068R6) and [P3247R2](https://wg21.link/P3247R2) also need library changes.

**Review by ldionne — APPROVED** [review]
LGTM with minor nits. Thanks a lot! I'll create the Github issues momentarily.

**Review by ldionne — APPROVED** [review]

**Pull request merged**
