### PR TITLE
Reland pr code format updates

### PR DESCRIPTION
**Pull request by boomanaiden154**
This PR relands https://github.com/llvm/llvm-project/pull/69766 after it caused failures due to being unable to fetch branches from forks. I was using the wrong ref, so it tried to pull the same branch name from `llvm/llvm-project` rather than trying to pull the branch from the fork that the PR was created from. This is also why it didn't show up in my testing on my fork as I was only testing PRs on branches from within the same repository.

### CODE REVIEW

**Comment by boomanaiden154** [comment]
One thing to note with these changes is that it still doesn't handle merging changes from `main` into the PR branch to update it very well. When someone does this, the n commits within the PR are not in the first n commits anymore. I'm not sure how common of a problem this is as the recommended workflow is to rebase and force push, but I have seen it happen in some cases.

This is somewhat of a regression from the old behavior, but not a complete one from what I understand. Since merging changes the order, especially if done multiple times (like I've seen in some PRs), starting and stopping at a specific revision will pull in more changes than just the commits in the PR. This is somewhat alleviated by only looking at a specific set of files though.

This should probably be fixed at some point (maybe even before this lands given @llvm-beanz's patch should help with quite a few cases). Not sure of the best way to do it though. It would be easiest if we could just pull the merge ref and diff the merge commit, but that doesn't work if there are any merge conflicts (fails to fetch the ref). We could iteratively fetch until we hit the merge base and the only run `clang-format` on individual commits, but I'd rather avoid the iterative fetching if possible.

**Comment by tstellar** [comment]
I know you can fetch a patch for the pull request via the API.  Would that help with any of the corner cases?

**Comment by boomanaiden154** [comment]
> I know you can fetch a patch for the pull request via the API. Would that help with any of the corner cases?

Potentially, but even a tool like https://github.com/llvm/llvm-project/blob/main/clang/tools/clang-format/clang-format-diff.py relies on having a checkout where the diff applies cleanly, which would require finding the merge base.

I was able to get this working by diffing merge commits, with the caveat that the job doesn't run if there's a merge conflict. This matches the behavior when using `pull_request`, but isn't ideal as we should still be able to check code formatting when there are merge conflicts. I don't think that would result in code landing without ever being checked by the action however (or at least make it exceedingly rare).

I'll run some experiments with iteratively fetching until we hit the merge base and see what the performance is like.

I think I'd push to land this diffing merge commits and not working with merge conflicts with iterative fetching/script modifications to enable running the action on the merge conflicts case as a follow up patch, but interested to hear what others think. This isn't super urgent as https://github.com/llvm/llvm-project/pull/70946 reduces the number of failures to only a couple per day  (n=1 day, didn't go through all of the past 24 hours).

**Review by tstellar — APPROVED** [review]

**Comment by boomanaiden154** [comment]
A bit more hacking:
* Apparently it's not as easy as I thought to check the mergability of a PR. It needs to be done through a separate API request specifically for that PR as the `pull_request.mergeable` field/associated fields are not populated in the CI run.
* Weird behavior exists. For example, you can still fetch the merge ref of a PR that has conflicts, it's just the merge ref for the last version of the PR that didn't have any conflicts (from what I can tell). Failing on mergeability fixes this issue though.

This PR should be in a landable state, acknowledging the lack of functionality in the case where there are merge conflicts. I've kept the `changed-files` step after the checkout to hopefully avoid an additional API call. If that still causes issues (there are still occasional transient failures not even related to fetch depth issues) and we're running out of API requests, we can also switch to the llvm bot token given this uses `pull_request_target`.

**Comment by tstellar** [comment]
What happens when there are merge conflicts?  Does the job just fail or does it give an informative error message?

**Comment by boomanaiden154** [comment]
Currently it just fails in the step where it checks if the PR is mergeable. Would it be preferable to make it adjust the comment with a message?

**Review by tru — APPROVED** [review]
LGTM in theory. The test is always in production of course. But feel free to merge and test.

**Comment by tstellar** [comment]
> Currently it just fails in the step where it checks if the PR is mergeable. Would it be preferable to make it adjust the comment with a message?

Yeah, I think it would be useful to produce a message like: "Failed to check code formatting, please rebase your PR on the  main branch to verify the formatting."

I think most people get confused if they see a failed test, so we should try to help as much as possible.

**Comment by boomanaiden154** [comment]
Closing in favor of #72020.

**Pull request closed without merging**
