### PR TITLE
[CodeGen][MRI] Add allocation mask for register classes

### PR DESCRIPTION
**Pull request by cdevadas**
Some targets can have register classes with identical sets
of registers. However, their actual allocation order can vary.
The allocation mask computed based on target constraints
would help achieve this during register allocation.

### CODE REVIEW

**Comment by cdevadas** [comment]
It depends on https://github.com/llvm/llvm-project/pull/86006 (patch already included in the commits list)

**Comment by cdevadas** [comment]
Posted RFC https://discourse.llvm.org/t/rfc-synthetic-register-classes-and-allocation-mask-to-determine-the-final-allocation-order/77853

**Comment by cdevadas** [comment]
Ping

**Comment by cdevadas** [comment]
Ping

**Comment by qcolombet** [comment]
> Ping

I believe the RFC needs to converge before we get to this patch.

**Comment by cdevadas** [comment]
Implemented wwm-register allocation using the alternate PR https://github.com/llvm/llvm-project/pull/93526 and this patch no longer needed.

**Pull request closed without merging**
