### PR TITLE
[flang][OpenMP] Don't abort when default is used on an invalid directive

### LINKED ISSUE #93437: [flang][OpenMP] Assertion failure in incorrect use of default clause
The following reproducer uses default clause on a disallowed directive

```
program main
  integer, dimension(100) :: a
  integer :: i
  !$omp do ordered default(private)
  do i = 2, 10
    !$omp ordered
    a(i) = a(i-1) + 1
    !$omp end ordered
  end do
  !$omp end do
end program main
```

LLVM Flang crashes with the following assertion failure: `parallelDir || taskGenDir || llvm::omp::allTeamsSet.test(dirContext.directive)`

gfortran, on the other hand, exits with a semantic error.

### LINKED ISSUE #107495: [Flang][OpenMP] Assertion `parallelDir || taskGenDir || teamsDir' failed.
With assertion-enabled flang-new, the following program causes an assertion failure.

Reproducer:
```f90
integer :: i, j

!$omp parallel
!$omp do default(private)
do i = 1, 10
   j = i
end do
!$omp end do
!$omp end parallel

end
```

Assertion:
```txt
flang-new: /opt/llvm-project/flang/lib/Semantics/resolve-directives.cpp:2155: void Fortran::semantics::OmpAttributeVisitor::CreateImplicitSymbols(const Symbol *, std::optional<Symbol::Flag>): Assertion `parallelDir || taskGenDir || teamsDir' failed.
```

### PR DESCRIPTION
**Pull request by luporl**
The previous assert was not considering programs with semantic errors.

Fixes https://github.com/llvm/llvm-project/issues/107495
Fixes https://github.com/llvm/llvm-project/issues/93437

### CODE REVIEW

**Comment by luporl** [comment]
Now that I noticed that this is practically the same fix as in https://github.com/llvm/llvm-project/pull/93438.

**Review by tblah — APPROVED** [review]
Looks good.

I see this now hits a semantic error instead: "DEFAULT clause is not allowed on the DO directive". There doesn't seem to be a unit test for this currently. Please could you add one so we can verify that it doesn't crash.

**Review by mjklemm — APPROVED** [review]
LGTM

**Review by NimishMishra — APPROVED** [review]
Thanks @luporl . This looks good.

**Pull request merged**
