### PR TITLE
Revert "[runtimes] Allow building against an installed LLVM tree"

### PR DESCRIPTION
**Pull request by philnik777**
Reverts llvm/llvm-project#86209

This patch breaks running tests locally, which is extremely disruptive to libc++ development.

### CODE REVIEW

**Comment by arichardson** [comment]
Sorry about this, will try to reproduce!

**Comment by kstoimenov** [comment]
Looks like this break the QEMU Sanitizer build: https://lab.llvm.org/buildbot/#/builders/139/builds/5496/steps/30/logs/stdio

**Comment by ldionne** [comment]
I don't think that failure could have been caused by the revert? I would expect something like "could not find Lit" if this revert was causing an issue (and then the fix would be to revert the dependent patch that was made since https://github.com/llvm/llvm-project/pull/86209 landed).

**Comment by kstoimenov** [comment]
NM, it looks like it was happening before your patch. Sorry about the noise.

**Pull request merged**
