### PR TITLE
[InstCombine] Support gep nuw in icmp folds

### PR DESCRIPTION
**Pull request by nikic**
Unsigned icmp of gep nuw folds to unsigned icmp of offsets. Unsigned icmp of gep nusw nuw folds to unsigned samesign icmp of offsets.

Proofs: https://alive2.llvm.org/ce/z/VEwQY8

### CODE REVIEW

**Review by dtcxzyw — APPROVED** [review]
LGTM.

**Comment by vitalybuka** [comment]
Also this one https://lab.llvm.org/buildbot/#/builders/66/builds/7009

**Comment by vitalybuka** [comment]
@nikic Please confirm that revert is noticed.

**Comment by nikic** [comment]
@vitalybuka I had some trouble reproducing this locally, but I think this change to the profiling runtime should fix the issue: https://github.com/llvm/llvm-project/pull/118782

**Comment by bgra8** [comment]
@nikic  Is it intended for this patch to optimize out the code in the `Check()` function below (just want to make sure this is intentional)? This patch removes the comparison and just returns `false`.

Thanks in advance!

```c++
using size_t = decltype(sizeof(int));

bool Check(const unsigned char* input, size_t size_input_in_bytes) {
  return (input + size_input_in_bytes < input);
}

int main() {
  unsigned char* buffer = new unsigned char[128];
  return Check(buffer, ~static_cast<size_t>(0)) ? 0 : 1;
}
```

**Comment by nikic** [comment]
@bgra8 Yes, optimizing out that kind of code is exactly the intention for this change (for bounds check elimination).

**Comment by zmodem** [comment]
I see @bgra8 already raised this, but maybe it's worth discussing further.

There is a fair amount of test fallout from this (the profile merging issue in LLVM mentioned above, at least one issue in Chromium, and many more internally). We can fix those, but what concerns me are the issues not caught by tests. It doesn't seem unlikely that this optimization could open up security holes by removing these kinds of bounds checks.

While such code was already technically broken, it would have been hard for developers to notice. Could -Wtautological-compare catch some of these (like the `Check` example above)? Could UBSan flag pointer arithmetic overflows? Could ASan flag comparisons of invalid pointers?

**Comment by nikic** [comment]
> Could -Wtautological-compare catch some of these (like the `Check` example above)?

Yeah, I think this is a good idea.

> Could UBSan flag pointer arithmetic overflows?

UBSan should already flag this.

> Could ASan flag comparisons of invalid pointers?

Not sure what exactly you have in mind here.

**Comment by zmodem** [comment]
> > Could UBSan flag pointer arithmetic overflows?
> 
> UBSan should already flag this.

Oh that's good. I guess we need to run it some more :-)

> > Could ASan flag comparisons of invalid pointers?
> 
> Not sure what exactly you have in mind here.

I was thinking that ASan could use the shadow memory to detect when one operand is pointing to bad memory which is more than one element past valid memory. That way we could perhaps catch (some) instances of

```
if (ptr + idx > end_ptr)
```

Not sure if that's really practical though, and it still requires test coverage to catch anything.

**Comment by nikic** [comment]
And https://github.com/llvm/llvm-project/pull/120222 for a possible implementation.

**Comment by nikic** [comment]
> I was thinking that ASan could use the shadow memory to detect when one operand is pointing to bad memory which is more than one element past valid memory. That way we could perhaps catch (some) instances of
> 
> ```
> if (ptr + idx > end_ptr)
> ```
> 
> Not sure if that's really practical though, and it still requires test coverage to catch anything.

This should probably directly operate on the `ptr + idx` rather than the comparison, as the GEP is where the UB is introduced. I also hit a case recently with `ptr - 1` where `ptr` is the base of an allocation, which is also UB but not diagnosed by anything.

It might make sense to experiment with this behind an option, as this probably adds a significant amount of overhead. (Though a separate check can be omitted for GEPs that are followed by an access, which is probably most of them.)

**Comment by alexfh** [comment]
> > Could UBSan flag pointer arithmetic overflows?
> 
> UBSan should already flag this.

We have found a couple of dozen of issues uncovered by this optimization, but I don't think in any of these cases ubsan was producing an error.

So far the only reasonable way to investigate these problems was to selectively disable optimizations using `-O0` for subsets of files and then to bisect within the file by inserting `#pragma clang optimize off`. After that only manual inspection.

Not having a good way to localize these problems is a serious concern for large codebases.

**Comment by nikic** [comment]
> We have found a couple of dozen of issues uncovered by this optimization, but I don't think in any of these cases ubsan was producing an error.

See https://clang.godbolt.org/z/azr7rbv3c for a sample of ubsan reporting this. Are you running ubsan in the cases that actually overflow? It's not going to report something if there is no overflow...

**Comment by alexfh** [comment]
My bad, indeed, our cases are associated with invalid pointers rather than specifically with pointer overflow. But I suppose, a similar distribution is to be expected in other code bases, which means that there is no targeted sanitizer for this and diagnostic of issues resulting from this and related changes is non-trivial. Does performance gain justify this?

**Comment by nico** [comment]
Is this the only recent change that allows LLVM to make assumptions about pointer overflows?

+1 to this being a problem. If we update clang in chromium, we pick this up and potentially introduce all kinds of silent security vulnerabilities.  https://crbug.com/384391188 is an example where this erased a security pointer check. The check was technically invalid, but it worked prior to this, and after this it's an OOB write instead. And that's a case where we happened to have a test – several other places don't have a check probably.

Another idea: C++ made signed integer overflow defined recently as far as I know, and unsigned integer overflow is also defined. Maybe it'd make sense to give clang a flag that says "give pointer overflow defined two's complement semantics"? Does `-fwrapv-pointer` do this? Maybe we can just add support for that to clang? Then people could use that flag to buy themselves time to audit their codebase, or to keep this off indefinitely.

Failing that, if this is the only patch, could we get a (possibly temporary) mllvm flag for turning this off?

One reason why this is a bit of a problem: #116871 made -Wunused-private-field stricter, in a way that's not easy to put behind a new warning flag. It makes that warning fire a lot more. We cleaned up our codebase (required updating ~80 files) to  be clean with the new warning, and we now have these options:

1. Do not update clang while the discussion here is ongoing. Pinned clang wont find new -Wunused-private-field instances, so this'll create work for us when we update next. (There's also a similar situation for -Wreturn-stack-address – https://crbug.com/384033056 – but that one fires much less often and it's less of a problem.)

2. Update clang, make sure the warnings stay fixed, but potentially pick up all kinds of silent new security vulnerabilities due to this patch.

Neither alternative is particularly great. If there was a way to update but turn off this here for a while, that'd give us a better path forward.

**Comment by alexfh** [comment]
That's definitely not the only patch in this area. [e21ab4d16b555c28ded307571d138f594f33e325](https://github.com/llvm/llvm-project/commit/e21ab4d16b555c28ded307571d138f594f33e325) discovers more cases of pointer arithmetic-related UB.

**Comment by nikic** [comment]
> My bad, indeed, our cases are associated with invalid pointers rather than specifically with pointer overflow.

Can you share an example where you ran into an issue and ubsan did not diagnose? I would expect ubsan to reliably find all cases of this pattern (if there is test coverage).

> Does performance gain justify this?

The problem here is basically that that this is intended to optimize away redundant bounds checks inserted by programming languages that generally do bounds checks, or hardened library implementations. At this level, we cannot distinguish this from an incorrect hand-written bounds check in C/C++.

> Another idea: C++ made signed integer overflow defined recently as far as I know, and unsigned integer overflow is also defined.

As far as I know signed integer overflow is still undefined in C++.

> Maybe it'd make sense to give clang a flag that says "give pointer overflow defined two's complement semantics"? Does `-fwrapv-pointer` do this? Maybe we can just add support for that to clang? Then people could use that flag to buy themselves time to audit their codebase, or to keep this off indefinitely.

`-fwrapv` should already cover pointers -- so you'd like a flag that only makes pointer overflow well-defined, but not signed integer overflow? This should be possible if Clang folks agree.

> Failing that, if this is the only patch, could we get a (possibly temporary) mllvm flag for turning this off?

It's not the only patch, but I wouldn't mind adding an option for this one, as it's probably the highest impact one.

> That's definitely not the only patch in this area. [e21ab4d16b555c28ded307571d138f594f33e325](https://github.com/llvm/llvm-project/commit/e21ab4d16b555c28ded307571d138f594f33e325) discovers more cases of pointer arithmetic-related UB.

FWIW, I'd be happy to just revert that one entirely. I don't have a specific use case for that one, and am concerned that it currently slips through all the sanitizers.

**Comment by alexfh** [comment]
> > That's definitely not the only patch in this area. [e21ab4d16b555c28ded307571d138f594f33e325](https://github.com/llvm/llvm-project/commit/e21ab4d16b555c28ded307571d138f594f33e325) discovers more cases of pointer arithmetic-related UB.
> 
> FWIW, I'd be happy to just revert that one entirely. I don't have a specific use case for that one, and am concerned that it currently slips through all the sanitizers.

FWIW, most issues I mentioned in my previous comments are actually coming from e21ab4d16b555c28ded307571d138f594f33e325, not this one. They happened to be tested together and I kind of conflated them in my head, hence the somewhat misleading report above.

Given that we also discovered a bad interaction of that change with msan, reverting it would definitely help us. A test case is being worked on by a colleague, but I'm not quite sure how far they are with it.

**Comment by davidben** [comment]
>>> Could UBSan flag pointer arithmetic overflows?
>>
>> UBSan should already flag this.
>
> Oh that's good. I guess we need to run it some more :-)

I believe the sanitizer is `-fsanitize=pointer-overflow`, which we don't currently run, but I agree we should. The problem when I tried to enable it is that it _also_ flags `null + 0` in C, and basically nothing passes that. (Chromium won't even build because some core part of Wayland fails it.) I had meant to go fix and/or add suppressions for those but haven't had time.

Although, given that this [blatant language defect](https://davidben.net/2024/01/15/empty-slices.html) has been [acknowledged as a defect by the standards committee](https://developers.redhat.com/articles/2024/12/11/making-memcpynull-null-0-well-defined), perhaps it would make sense to either remove or recategorize that check in UBSan now.

**Comment by nikic** [comment]
> > > > Could UBSan flag pointer arithmetic overflows?
> > > 
> > > 
> > > UBSan should already flag this.
> > 
> > 
> > Oh that's good. I guess we need to run it some more :-)
> 
> I believe the sanitizer is `-fsanitize=pointer-overflow`, which we don't currently run, but I agree we should. The problem when I tried to enable it is that it _also_ flags `null + 0` in C, and basically nothing passes that. (Chromium won't even build because some code generating tool in Wayland fails it.) I had meant to go fix and/or add suppressions for those but haven't had time.
> 
> Although, given that this [blatant language defect](https://davidben.net/2024/01/15/empty-slices.html) has been [acknowledged as a defect by the standards committee](https://developers.redhat.com/articles/2024/12/11/making-memcpynull-null-0-well-defined), perhaps it would make sense to either remove or recategorize that check in UBSan now.

Yes, I agree that we should change this to align with the newly adopted C semantics, and the change being part of https://www.open-std.org/jtc1/sc22/wg14/www/previous.html should give us the leeway to do this for old standards versions (combined with the fact that we have never used this for optimization in the first place). This should just be a matter of always using the C++ logic in: https://github.com/llvm/llvm-project/blob/2b9abf0db2d106c7208b4372e662ef5df869e6f1/clang/lib/CodeGen/CGExprScalar.cpp#L5869

**Comment by nico** [comment]
> `-fwrapv` should already cover pointers

Thanks for pointing this out! I confirmed that that's true. The documentation only talks about it affecting signed overflow.

We'll switch to that, at least for now. It comes with a noticeable binary size hit, but it seems like the least bad option for now.

(The reverts that landed don't seem to help some of the pointer checks that we saw getting deleted, and the compiler warning also didn't catch them due to the addition being stored in a variable before being compared.)

> so you'd like a flag that only makes pointer overflow well-defined, but not signed integer overflow? This should be possible if Clang folks agree.

Yes, that'd be great. I think gcc has that flag already.

If it doesn't yet, this should get a scary-looking release notes entry that mentions possible mitigations :)

(Also, thank you for working on making llvm / clang better in removing unnecessary bounds checks! This is fantastic. The intermediate change breaks us pretty bad, but long term I'm very excited about this, so thanks again!)

**Comment by nikic** [comment]
@davidben I have implemented the change to `-fsanitize=pointer-overflow` in https://github.com/llvm/llvm-project/pull/120719.

**Comment by davidben** [comment]
Relatedly, this seems a good reason to do https://github.com/llvm/llvm-project/issues/119040. Any code that has a pointer wraparound problem probably also has a problem with `ptr + n` escaping the bounds of `ptr`'s allocation, and that one is much more likely to be hit in testing.

**Comment by nikic** [comment]
@nico I've put up a PR for the scary release note here: https://github.com/llvm/llvm-project/pull/122462

**Pull request merged**
