### PR TITLE
Fill 17.x/ReleaseNotes with my works

### PR DESCRIPTION
**Pull request by chapuni**
Sorry for the delay.

Feel free to correct, rephrase, and revise.

### CODE REVIEW

**Comment by chapuni** [comment]
Oh, this is 1st time pull request to me.

**Comment by arsenm** [comment]
> Oh, this is 1st time pull request to me.

For release branches, I think you are still supposed to use https://github.com/llvm/llvm-project-release-prs

**Comment by tru** [comment]
Hi - prepare a branch in your fork and push the notes there on top of release/17.x and I can manually cherry-pick it when you are happy with it.

**Comment by chapuni** [comment]
@tru I have created llvm/llvm-project-release-prs#789, thanks!

**Pull request closed without merging**
