### PR TITLE
[Release] Add keith to valid archive uploaders

### LINKED ISSUE #106016: Release Asset Audit Failed
@keith is not a valid uploader.

https://github.com/llvm/llvm-project/actions/runs/10550475944

### PR DESCRIPTION
**Pull request by keith**
I am interested in helping contribute macOS binaries since we're generally sporadic with uploading these.

Fixes https://github.com/llvm/llvm-project/issues/106016

### CODE REVIEW

**Comment by tru** [comment]
Thanks for offering @keith  - but I think after the recent [RFC](https://discourse.llvm.org/t/rfc-improve-binary-security/78121?u=tobiashieta) we probably don't want to have manually uploaded binaries except from the bots. You are free to start uploading the binaries to the third-party binaries thread and hopefully we can get some official macOS binaries later.

**Comment by keith** [comment]
Thanks for the info, I did see that (and am still curious about the path forward there) but actually I just wanted to upload a binary for 18.x since there haven't been consistent binaries for a while for macOS, and I was hoping to get one before that cutoff since it's unclear to me when folks will be able to get a new macOS binary given that change

**Comment by keith** [comment]
more info on https://github.com/llvm/llvm-project/issues/106016

**Comment by tstellar** [comment]
If @tru agrees then I don't have an object to uploading a 18.1.8 binary, since the policy was meant for LLVM 19+.  However, @keith I would prefer if the script was modified so that it  matched both your username and the binary name when checking for a valid uploader.  You don't need to make the change for all users, just for you and this upload.

**Comment by tru** [comment]
Yeah I think that's a good plan. Alternatively me or Tom can just upload the binary since it's a one off. if you make it ready and sign it.

**Comment by keith** [comment]
I don't have a strong pref of you all uploading or me, I pushed the script change here that would allow me to just for this 1 asset name, if you would prefer the other route lmk where to send the archive!

**Review by tstellar — APPROVED** [review]

**Pull request merged**
