### PR TITLE
[WebAssembly] avoid to enable explicit disabled feature

### PR DESCRIPTION
**Pull request by HerrCai0907**
In `CoalesceFeaturesAndStripAtomics`, feature string is converted to FeatureBitset and back to feature string. It will lose information about explicit diasbled features.

### CODE REVIEW

**Review by tlively — COMMENTED** [review]
What should happen if a feature is explicitly disabled via globally, but enabled on one of the functions in the module? IIUC, this current patch will have the string to enable it followed by the string to disable it. Which one wins? I think it would be good to have the feature enabled in that case.

**Comment by HerrCai0907** [comment]
> What should happen if a feature is explicitly disabled via globally, but enabled on one of the functions in the module?

How could this case happened? If explicitly disabling a feature, it should not be enabled on function?

**Comment by HerrCai0907** [comment]
>  I think it would be good to have the feature enabled in that case.

I think it should throw diagnose or assert it won't happen. Otherwise the user will find they disable some feature but code still has this feature.

**Comment by HerrCai0907** [comment]
I have do some testing, for 
```llir
attributes #0 = { noinline nounwind optnone "target-features"="+bulk-memory," }
declare void @llvm.memset.p0.i32(ptr, i8, i32, i1)
define void @memset_alloca(i8 %val) {
  %a = alloca [100 x i8]
  call void @llvm.memset.p0.i32(ptr %a, i8 %val, i32 100, i1 false)
  ret void
}
```
If I use `llc ID/a.ll -mattr=+bulk-memory`, It will use `memory.fill` but if I use `llc ID/a.ll -mattr=-bulk-memory`, it won't use any bulk memory instruction and disable this feature although it declared in function.

Which means it is impossible to have conflict between functions' feature and global feature.

Related code is in `MCSubtargetInfo::InitMCProcessorInfo`, here feature in opinion will be apply.

**Review by tlively — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
