### PR TITLE
[LLVM][rtsan] Add LLVM nosanitize_realtime attribute

### PR DESCRIPTION
**Pull request by cjappl**
This new attribute should be incompatible with the `sanitize_realtime` attribute.

### CODE REVIEW

**Comment by cjappl** [comment]
CC Co-author @davidtrevelyan

**Comment by cjappl** [comment]
(test failures looked unrelated, rebased to latest main to see if that resolved it)

**Comment by cjappl** [comment]
Similarly unrelated build failure in CI:

```
_bk;t=1724336701213FAIL: lldb-shell :: Unwind/trap_frame_sym_ctx.test (1919 of 2590)

_bk;t=1724336701213******************** TEST 'lldb-shell :: Unwind/trap_frame_sym_ctx.test' FAILED ********************

_bk;t=1724336701214Exit Code: 1

_bk;t=1724336701214

_bk;t=1724336701214Command Output (stderr):


```

Some work being done on that now, based on this commit: https://github.com/llvm/llvm-project/commit/19d3f3417100dc99caa4394fbd26fc0c4702264e

**Comment by pcc** [comment]
We usually only support `__attribute__((no_sanitize("sanitizername")))` as the attribute for disabling a sanitizer.  Some sanitizers have other attributes for disabling them but they only exist for backwards compatibility reasons.

**Comment by cjappl** [comment]
> We usually only support `__attribute__((no_sanitize("sanitizername")))` as the attribute for disabling a sanitizer. Some sanitizers have other attributes for disabling them but they only exist for backwards compatibility reasons.

Can you elaborate how one would access this in a transform pass of LLVM? I'm generally new to this area of the code, and thought that adding a nosanitize_x attribute was the only way to accomplish my goal.

The next PR after this one adds a check for this LLVM attribute in RealtimeSanitizer.cpp, and if this attribute exists on the function inserts a function call to bypass this in the Realtime Sanitizer stack. (That looks something like [this](https://github.com/cjappl/llvm-project/pull/4)). This seems plausible to do without the attribute as long as I have the correct thing to look for.

**Comment by pcc** [comment]
Apologies, for some reason I thought you were adding a Clang attribute. This seems fine then.

**Comment by pcc** [comment]
That being said, we normally only add positive LLVM attributes for sanitizers and arrange for the Clang attribute  `__attribute__((no_sanitize("sanitizername")))` to inhibit adding the LLVM attribute (see `CodeGenFunction::StartFunction`). Is there a reason why this approach doesn't work for the realtime sanitizer?

**Comment by cjappl** [comment]
> That being said, we normally only add positive LLVM attributes for sanitizers and arrange for the Clang attribute `__attribute__((no_sanitize("sanitizername")))` to inhibit adding the LLVM attribute (see `CodeGenFunction::StartFunction`). Is there a reason why this approach doesn't work for the realtime sanitizer?

This won't work in our case, because the realtime sanitizer is selective, ignoring the vast majority of functions, and only focusing on function calls from functions that have an ancestor marked [[clang::nonblocking]] (some more detail in our little [design doc](https://github.com/realtime-sanitizer/radsan/blob/doc/review-support/doc/review.md))

Because a user may want to ignore errors in a call stack that has a [[clang::nonblocking]] ancestor, we need to look for this LLVM attribute, and insert calls to bypass the stack (__rtsan_bypass_on/_off). 

So: 
* Most functions - not attributed with either, will not be looked at by the realtime sanitizer or impacted at all
* `[[clang::nonblocking]]` functions - in our transform will add the __rtsan_realtime_enter/_exit commands
* `__attribute__((no_sanitize("sanitizername")))` called from a `[[clang::noblocking]]` setting - need to bypass rtsan with bypass_on/_off.

Because we care about these function in this third state, we can't just omit the sanitizer, we have to add the attribute and transform them in our pass.

I guess another way to do it would be add the _bypass to all functions, and only add the _realtime_enter to functions marked [[clang::nonblocking]], but that seems like it would add runtime overhead to user code as compared to this approach

**Comment by pcc** [comment]
So do you really need the LLVM attributes then? Would it not suffice to have Clang IRGen add the calls to `__rtsan_bypass_on/off` and `__rtsan_realtime_enter/exit` based on the Clang attributes? The other sanitizers have passes because they need to be able to operate on arbitrary instructions in each function after optimization, but if RTSan only needs to affect function entry/exit then that seems much more straightforwardly accomplished in the frontend.

**Comment by cjappl** [comment]
> So do you really need the LLVM attributes then? Would it not suffice to have Clang IRGen add the calls to `__rtsan_bypass_on/off` and `__rtsan_realtime_enter/exit` based on the Clang attributes? The other sanitizers have passes because they need to be able to operate on arbitrary instructions in each function after optimization, but if RTSan only needs to affect function entry/exit then that seems much more straightforwardly accomplished in the frontend.

We discussed this a bit in the RFC thread (apologies in advance for the size of it, it became a monster), this comment and below:
https://discourse.llvm.org/t/rfc-nolock-and-noalloc-attributes/76837/104?u=cjappl

The reasoning we came up with to have it be in LLVM directly is in this comment:
https://discourse.llvm.org/t/rfc-nolock-and-noalloc-attributes/76837/107?u=cjappl

**Comment by pcc** [comment]
Thanks, I didn't see that discussion.

Re 2: this can be accomplished via an API, no? You can provide functions such as `void rtsanMarkAsNonblocking(Function *F);` and `void rtsanMarkAsBypass(Function *F);` and clang and other frontends can call it.

Re 3: we can always defer adding the attribute until/unless the planned functionality is actually implemented.

But I don't have a strong opinion. If @vitalybuka is fine with this being LLVM attributes it's fine with me as well.

**Comment by cjappl** [comment]
Thanks a lot for the feedback, we are new around these parts and just getting our bearings. We really appreciate having review and feedback from folks who have more context than us! I'll wait to hear if Vitaly has any additional feedback that wasn't given on the thread.

> Re 2: this can be accomplished via an API, no? You can provide functions such as void rtsanMarkAsNonblocking(Function *F); and void rtsanMarkAsBypass(Function *F); and clang and other frontends can call it.

Where would such a function live? Can you point me in the direction of other similar functions?

**Comment by cjappl** [comment]
I also just recalled it was Vitaly that set us on the path of LLVM to begin with, see the discussion here:

https://github.com/llvm/llvm-project/pull/100192#discussion_r1688697745

**Comment by pcc** [comment]
> Where would such a function live? Can you point me in the direction of other similar functions?

Functions like this would normally be under `llvm/lib/Transforms/Utils`. You can look at existing inclusions of headers in `llvm/Transforms/Utils` under `clang/lib/CodeGen`.

**Comment by pcc** [comment]
> Re 3: we can always defer adding the attribute until/unless the planned functionality is actually implemented.

Another point regarding this: when adding new functionality to sanitizers we often need to be able to opt out the new functionality in existing code in order to avoid breaking existing usage of the sanitizer. So in the end you might end up needing nonblocking function checks to be controlled separately from loop checks (or any other checks that you may implement in the future). That would likely imply a separate LLVM attribute specifically for loop checks, rendering the LLVM attributes for nonblocking function checks unnecessary.

**Comment by cjappl** [comment]
These all seem like totally reasonable suggestions. I'll wait for Vitaly to chime in with his opinion! I have limited expertise in this area, so I will go with what seasoned hands think are best :) 

If there is a split or a "either way" I would vote for keeping it how it is now, but if there is something that tilts it to the "just clang" side, I am happy to go back and revise the work already done, strip out the attributes etc.

Thanks again for your thoughts on this @pcc. Really appreciate it.

**Comment by cjappl** [comment]
Build is failing for same reason as yesterday, still unrelated:

```
_bk;t=1724431385857FAIL: lldb-shell :: Unwind/trap_frame_sym_ctx.test (1944 of 2593)

_bk;t=1724431385857******************** TEST 'lldb-shell :: Unwind/trap_frame_sym_ctx.test' FAILED ********************

_bk;t=1724431385858Exit Code: 1

_bk;t=1724431385858

_bk;t=1724431385858Command Output (stderr):

_bk;t=1724431385858--


```

https://buildkite.com/llvm-project/github-pull-requests/builds/94386#0191800e-c66f-424b-9029-34abc10006d8

**Review by vitalybuka — APPROVED** [review]

**Comment by cjappl** [comment]
@pcc - I think I'll submit this as is tomorrow morning PST following vitaly's approval. If you want to continue talking it over, I could I file a discourse thread and ping the interested parties (vitaly, nikic, you, me, people from the original RFC thread) and we can hash out if one approach is better than the other. If doing it in the frontend is best, I can submit a patch reverting any of the LLVM and putting it in clang in one swoop to maintain the functionality we have built so far.

If you don't feel strongly, I can just keep trucking with this approach! I will add you to the transform review (following this) if you're amenable :)

**Comment by cjappl** [comment]
After discussion on #106125 I am going to revert this in favor of doing it the "lsan way" which introduces a scoped disabler, for more details on that check out #106736 .

I will request a review on the reversion in a few

**Pull request merged**
