### PR TITLE
[libcxx] Replace a few _LIBCPP_INLINE_VISIBILITY with _LIBCPP_HIDE_FR…

### PR DESCRIPTION
**Pull request by nico**
…OM_ABI

From __config:

    // Just so we can migrate to the new macros gradually.
    #  define _LIBCPP_HIDE_FROM_ABI _LIBCPP_HIDE_FROM_ABI

Gradually convert some of this, since it confused me over in https://reviews.llvm.org/D157058#inline-1547042

Patch created by running:

   rg -lw _LIBCPP_INLINE_VISIBILITY libcxx/include | xargs sed -i '' \
       's/_LIBCPP_INLINE_VISIBILITY/_LIBCPP_HIDE_FROM_ABI/g'
   rg -lw _LIBCPP_INLINE_VISIBILITY libcxx/src | xargs sed -i '' \
       's/_LIBCPP_INLINE_VISIBILITY/_LIBCPP_HIDE_FROM_ABI/g'

No behavior change.

### CODE REVIEW

**Comment by nico** [comment]
This is kind of a big diff, but since you only need to look for "did the sed do anything weird" it's reasonably quick to scroll through. It took me about 10 minutes, including clicking "Load diff" on the "Large diffs are not rendered by default." diffs, and on all the unopened diffs at the end.

(When I got to the part where diffs stopped being default-expanded, I scrolled to the very end, then hit "Load diff" bottom-up until I had expanded them all, and then went down again. This was after about 5 minutes.)

**Comment by nico** [comment]
The cost is that someone has to scroll through this for 10 minutes. That's faster than most actual reviews.

The comment was added in cb3eb30636c8d, so if things change at the rate they've been changing in, they won't.

I'm also happy to split this in 10 (or whatever) PRs if you think that helps. But just doing it seems reasonably quick, so I'm not sure spending a lot of time discussing the process is worth the time the discussion takes.

**Comment by philnik777** [comment]
> The cost is that someone has to scroll through this for 10 minutes. That's faster than most actual reviews.
> 
> The comment was added in [cb3eb30](https://github.com/llvm/llvm-project/commit/cb3eb30636c8d9136c8a01126963eded45617531), so if things change at the rate they've been changing at, they won't.
> 
> I'm also happy to split this in 10 (or whatever) PRs if you think that helps. But just doing it seems reasonably quick, so I'm not sure spending a lot of time discussing the process is worth the time the discussion takes.

The cost isn't that it takes long to review. The problem is that this affects lots of in-flight PRs, resulting in a lot of merge conflict, and probably also a lot of downstream churn. If it were the 10 minutes it takes to look at these changes, I'd be more than happy to take it. FWIW the rate has been a lot higher recently, since we started to actively update the style (not just `_LIBCPP_INLINE_VISIBILITY`) before or after we touch some region of code, since the churn is already there in that case anyways. I'm also happy to take these changes in parts of the code where nobody working on a patch, but that's a lot more effort than just changing all the uses.

**Comment by ldionne** [comment]
I must admit I am not convinced by this change. We now have roughly 50/50 uses of `_LIBCPP_HIDE_FROM_ABI` and `_LIBCPP_INLINE_VISIBILITY`, so while things have been changing slowly, they definitely have been changing. If we do this kind of large batch renaming, I might argue for also `clang-format`ing the files that are being touched.

The cost of making this change is not the review of the change itself, it's mainly the cost of rebasing all the other in-flight patches that might conflict with it. One thing to consider is that we're draining the Phabricator review queue right now and I've already dealt with a lot of interesting conflicts that were not easy to rebase. If we move forward with this patch, I would like to request that we at least not move forward with it before we're done with the Phabricator queue cleanup.

**Comment by nico** [comment]
Alright, makes sense! 🙂

**Comment by ldionne** [comment]
I just discussed with @nico offline where he shared his experience of clang-formatting a large code base and using a custom git merge driver to help with conflict resolutions. I would love to investigate this avenue once the GH PR transition is done, and when we do that it would also make sense to do large refactors like the `HIDE_FROM_ABI` rename in this PR.

**Pull request closed without merging**
