### PR TITLE
Stop double-diagnosing explicit convert operator in switch condition

### PR DESCRIPTION
**Pull request by erichkeane**
Note this also likely fixes a bunch of other cases.  We were double-diagnosting in a template because we were generating the expression anyway, so any attempts to instantiate the function would instantiate the expression, thus re-diagnosing it.

This patch replaces it with a RecoveryExpr.  Additionally, VerifyIntegerConstantExpression couldn't handle the RecoveryExpr, as it requires a non-dependent expression result (which a RecoveryExpr is dependent).  Additionally, callers of it use the return value to decide that VerifyIntegerConstantExpression succeeded, so it fails if it sees a RecoveryExpr.

### CODE REVIEW

**Comment by Endilll** [comment]
I'm having second thoughts about leveraging recovery expressions as a side-band mechanism to de-duplicate diagnostics, because not modeling things properly in AST might backfire in the future. But I don't have anything better on my mind, so I don't want to block the progress of this PR.

**Comment by cor3ntin** [comment]
Did you try to use `ExprDependence::Error`?

**Comment by erichkeane** [comment]
> I'm having second thoughts about leveraging recovery expressions as a side-band mechanism to de-duplicate diagnostics, because not modeling things properly in AST might backfire in the future. But I don't have anything better on my mind, so I don't want to block the progress of this PR.

This is a case where we previously would use `ExprError`.  Typically, we don't include 'incorrect' expressions in the AST, as it results in us trying to instantiate them (like we see here).  The duplicate diagnostics is a side-effect of doing that wrong.

The `RecoveryExpr` is, IMO, a half decent way to actually model things properly in the AST despite them having an error.

**Comment by Sirraide** [comment]
> I've only ever seen that used in regards to the `RecoveryExpr`, so I think I am?

It’s used in a few other places from what I can tell (e.g. see `InitListExpr::markError()`); I think the result is the same either way (i.e. `containsErrors()` ends up returning `true`). 

I was looking around a bit and also just found this comment here:
https://github.com/llvm/llvm-project/blob/215eee60497489ae0cc7cc78c0d8b8270e057a70/clang/lib/Sema/SemaExpr.cpp#L3734-L3739
So I suppose there is at least some prededent for using `RecoveryExpr` for this. 

I don’t have too much experience with either, but at least intuitively, `ExprDependence::Error` sounds like it would make sense here, because if not for cases like this one then what is it actually for I wonder?

**Comment by erichkeane** [comment]
> > I've only ever seen that used in regards to the `RecoveryExpr`, so I think I am?
> 
> It’s used in a few other places from what I can tell (e.g. see `InitListExpr::markError()`); I think the result is the same either way (i.e. `containsErrors()` ends up returning `true`).
> 
> I was looking around a bit and also just found this comment here:
> 
> https://github.com/llvm/llvm-project/blob/215eee60497489ae0cc7cc78c0d8b8270e057a70/clang/lib/Sema/SemaExpr.cpp#L3734-L3739
> 
> So I suppose there is at least some prededent for using `RecoveryExpr` to suppress diagnostics.
> 
> I don’t have too much experience with either, but at least intuitively, `ExprDependence::Error` sounds like it would make sense here, because if not for cases like this one then what is it actually for I wonder?

I was looking into that, it doesn't seem to prevent being used in instantiation like `RecoveryExpr` does.  I DO note that `RecoveryExpr` DOES contain the original AST nodes, so it isn't like we're losing anything.

**Review by AaronBallman — APPROVED** [review]
The changes should come with a release note, but this LGTM otherwise

**Review by cor3ntin — APPROVED** [review]
LGTM

**Pull request merged**
