### PR TITLE
 [DebugInfo] Handle DW_OP_LLVM_extract_bits in SROA

### PR DESCRIPTION
**Pull request by john-brawn-arm**
This doesn't need any work to be done in SROA itself, but rather in functions that it uses. Specifically:
 * DIExpression::createFragmentExpression is made to understand DW_OP_LLVM_extract_bits
 * valueCoversEntireFragment is made to check the active bits instead of the fragment size, so that it handles extract_bits correctly

### CODE REVIEW

**Review by adrian-prantl — APPROVED** [review]
I think this looks reasonable, I would potentially consider adding some unit tests for appendOffset() mostly for documentation purposes of the expected behavior.

**Comment by nico** [comment]
This breaks tests: http://45.33.8.238/linux/140753/step_11.txt

**Comment by jplehr** [comment]
HI,
I think this turned a couple of our buildbots red as well:
https://lab.llvm.org/buildbot/#/builders/140/builds/197
https://lab.llvm.org/staging/#/builders/194/builds/1663
https://lab.llvm.org/buildbot/#/builders/73/builds/169
https://lab.llvm.org/staging/#/builders/185/builds/9287

**Comment by john-brawn-arm** [comment]
It looks like the failures are because of #91724 which went in between this being approved and merged. I think I just need to run update_test_checks.

**Comment by john-brawn-arm** [comment]
Should be fixed by #95774

**Pull request merged**
