### PR TITLE
fix(python): fix comparison to True/False

### PR DESCRIPTION
**Pull request by e-kwsm**
From PEP8 (https://peps.python.org/pep-0008/#programming-recommendations):

> Comparisons to singletons like None should always be done with is or is not, never the equality operators.

### CODE REVIEW

**Review by bulbazord — APPROVED** [review]
LGTM

The PR summary is empty, but it looks like the commit message has an explanation for this change, so that's fine.

**Comment by DavidSpickett** [comment]
If this is split out from the other larger PR, should there be `clang/` changes in here?

I've copied your commit message into the PR description, because with the way llvm is setup, we use the PR's description as the commit message for a squashed version of the changes.

(maybe Github uses the commit message if there's only one and the PR description is blank, but I wouldn't bet on it)

**Comment by JDevlieghere** [comment]
> If this is split out from the other larger PR, should there be `clang/` changes in here?

+1, please unstage the `clang` and `openmp` changes.

**Review by bulbazord — CHANGES_REQUESTED** [review]
Hmm, actually, I'm not so sure about this change anymore. I went through PEP8 again and saw this:

```
Don’t compare boolean values to True or False using ==:
# Correct:
if greeting:
# Wrong:
if greeting == True:

Worse:
# Wrong:
if greeting is True:
```

This doesn't seem like the right change then, no?

**Comment by NagyDonat** [comment]
The main problem with comparison to `True`/`False` is that it's completely redundant when the variable is _guaranteed to be boolean_. However, if a variable may contain either a boolean or something else, it's reasonable to compare it with `True` or `False`.

For the operator `==` there is another pitfall that according to Python `True == 1` and `False == 0` holds. (In ancient versions `True` and `False` were simply integer constants with these values; now `bool` is a subclass of `int` and preserves this old behavior.)

This implies that:
- When `x` is guaranteed to be a boolean, it should be used as `if x:` or `if not x:` (instead of `if x == True:` or `if x == False:`.
- Otherwise it may be reasonable to use the `is` operator: e.g. when `x` may be `True`, `False` or `None`, it is reasonable to check `if x is False:` or `if x is None:`.
- Using `==` has no advantage over `is` and could cause very surprising bugs when the variable can hold either a boolean or a number, so I'd say that it should be avoided. (However I admit that when `x` is known to be either `True`, `False` or `None`, there's a high chance that I'd instinctively write `if x == False:`.)

**Comment by JDevlieghere** [comment]
I don't think Alex is arguing in favor of keeping the old (wrong) behavior, but the first file looks like this:

```
foundSpec = False
if [...]
  foundSpec = True
[...]
if foundSpec is False:
```

It's pretty obvious this is a boolean and should use `if not foundSpec`.

**Comment by e-kwsm** [comment]
Broken into

- #94038
- #94039
- #94040
- #94041
- #94042

**Pull request closed without merging**
