### PR TITLE
[llvm-config] Quote and escape paths

### LINKED ISSUE #28117: Spaces in paths from llvm-config should be quoted
|  |  |
| --- | --- |
| Bugzilla Link | [27743](https://llvm.org/bz27743) |
| Version | trunk |
| OS | Windows NT |
| Reporter | LLVM Bugzilla Contributor |
| CC | @pogo59 |

## Extended Description 
When LLVM is installed in a path containing spaces, paths output from llvm-config have no way to indicate breaks between parameters and spaces within paths. For example, --cflags on Windows for MSVC might include "-IC:\Program Files\LLVM\include" which parses as "-IC:\Program" "Files\LLVM\include".

This could be fixed with escaping or quoting by llvm-config, perhaps as simple as quoting each individual element it emits. I believe quoting paths is portable to all major shells, though this would involve trading one error case (space in path) for another (quote in path) unless shell escaping logic were added.

Adding quotes to the output might break some existing tools, but given the usual use case is feeding the output to a shell it may not be worth worrying about.

Source issue: https://bitbucket.org/tari/llvm-sys.rs/issues/9/include-path-for-llvm-headers-on-windows

### PR DESCRIPTION
**Pull request by aganea**
If any of the printed paths by `llvm-config` contains quotes, spaces, backslashes or dollar sign characters, these paths will be quoted and the corresponding characters will be escaped.

Following discussion in https://github.com/llvm/llvm-project/pull/76304

Fixes https://github.com/llvm/llvm-project/issues/28117

### CODE REVIEW

**Review by compnerd — APPROVED** [review]

**Comment by glandium** [comment]
It seems the "if necessary" part was not implemented, because it now quotes even when quotes are not necessary, which is likely to break a ton of things.

**Comment by glandium** [comment]
Example of subtle breakage: cctools-port ld64's support for LTO breaks for some reason because of this change.

**Comment by glandium** [comment]
I gave one subtle example, but here's another one less subtle: https://github.com/AFLplusplus/AFLplusplus/blob/stable/GNUmakefile.llvm#L420 this simple straightforward use breaks completely (can't find includes when compiling).

**Comment by kongy** [comment]
Can you please revert the change while investigating a fix? Our downstream ToT builder is broken because of this change.

**Comment by aganea** [comment]
Reverted. @kongy do you have a reproducer that I could test locally by chance?

**Comment by kongy** [comment]
Our build script invokes `llvm-config` and feeds the target list to `ninja`. With the extra unnecessary quotes, ninja does not find the correct target.

```
DEBUG:utils:subprocess.run:02:40:16 /tmpfs/src/git/out/stage2-install/bin/llvm-config --libs object --libnames --link-static
DEBUG:utils:subprocess.run:02:40:16 /tmpfs/src/git/prebuilts/build-tools/linux_musl-x86/bin/ninja '"libLLVMObject.a"' '"libLLVMTextAPI.a"' '"libLLVMMCParser.a"' '"libLLVMIRReader.a"' '"libLLVMAsmParser.a"' '"libLLVMMC.a"' '"libLLVMDebugInfoCodeView.a"' '"libLLVMBitReader.a"' '"libLLVMCore.a"' '"libLLVMRemarks.a"' '"libLLVMBinaryFormat.a"' '"libLLVMTargetParser.a"' '"libLLVMBitstreamReader.a"' '"libLLVMSupport.a"' '"libLLVMDemangle.a"'
ninja: error: unknown target '"libLLVMObject.a"', did you mean 'libLLVMObject.a'?
```

**Comment by aganea** [comment]
While we could avoid unnecessary escaping for the libraries above, escaping paths in general (like this patch does) would need some modifications (I think) in scripts using `llvm-config`.

What do you all think about adding a new flag such as `--escaped` that allows potentially quoting and escaping paths, while keeping the old behavior when the flag is not provided?

**Comment by tothambrus11** [comment]
Another approach would have been to only add quotes when there is a space in the path. If old tooling relied on such things, it was broken anyways (there is no way of correctly splitting unless we add some hard assumptions). But `--escaped` is good for backwards compatibility in all cases.

**Comment by aganea** [comment]
Please see https://github.com/llvm/llvm-project/pull/103397

**Pull request merged**
