### PR TITLE
[clang-format][doc] fix documentation for clang-format

### LINKED ISSUE #83207: Incorrect configuration snippets for some AlignConsecutive... option sets
[Current documentation](https://clang.llvm.org/docs/ClangFormatStyleOptions.html) has incorrect configuration snippets for `AlignConsecutiveAssignments`, `AlignConsecutiveBitFields`, `AlignConsecutiveDeclarations`, `AlignConsecutiveTableGenCondOperatorColons`, `AlignConsecutiveTableGenDefinitionColons` that refer to `AlignConsecutiveMacros` instead of actual option set.

### PR DESCRIPTION
**Pull request by PeterChou1**
Fixes typo in documentation for clang-format 

Fixes #83207.

### CODE REVIEW

**Comment by owenca** [comment]
Hi, you need to edit `clang/include/clang/Format/Format.h` and then run `clang/docs/tools/dump_format_style.py` to regenerate `clang/docs/ClangFormatStyleOptions.rst`.

**Comment by PeterChou1** [comment]
> Hi, you need to edit `clang/include/clang/Format/Format.h` and then run `clang/docs/tools/dump_format_style.py` to regenerate `clang/docs/ClangFormatStyleOptions.rst`.

Hi my mistake. I'm quite new to the LLVM project so I was not aware the docs were generated through a script I've updated 
Format.h however I ended up needing to change how the auto generated python doc worked slightly
The problem was I couldn't carry over the generated member names to the parent type so i did added a simple search and replace to the generating script so now every time [[[NAME]]] is reference it will use the members name.

I'm not sure if this is the best way to do this though let me know if there's a better method

**Comment by owenca** [comment]
> So I did added a simple search and replace to the generating script so now every time [[[NAME]]] is reference it will use the members name.

Nice! Though why `[[[NAME]]]` in particular? Can we use `<option-name>` instead?

**Comment by PeterChou1** [comment]
> > So I did added a simple search and replace to the generating script so now every time [[[NAME]]] is reference it will use the members name.
> 
> Nice! Though why `[[[NAME]]]` in particular? Can we use `<option-name>` instead?

done

**Review by owenca — APPROVED** [review]

**Comment by PeterChou1** [comment]
Thanks @owenca. I don’t have commit access, can you merge this PR for me?

**Pull request merged**
