### PR TITLE
[libunwind] Detect cycles of length 1

### PR DESCRIPTION
**Pull request by al13n321**
If an unwind step leaves both the instruction pointer and the stack pointer unchanged, stop unwinding. Otherwise we'd be stuck in a loop producing the same stack frame over and over.

This happens with musl libc in __clone(), which has incorrect DWARF unwind information.

GDB also handles it using cycle detection, but it checks for cycles of any length rather than just length 1. That seems unnecessary here, at least until anyone encounters such cycles in practice.

Tested manually in https://github.com/ClickHouse/libunwind/pull/33

### CODE REVIEW

**Comment by MaskRay** [comment]
> This happens with musl libc in __clone(), which has incorrect DWARF unwind information.

Can you elaborate this? How is it incorrect? (tools/add-cfi.x86_64.awk on `musl/src/thread/x86_64/clone.s`, I assume)

I guess this workaround does address your issue, but for the upstream we really need more principled fix, instead of adding a hack.

**Review by MaskRay — CHANGES_REQUESTED** [review]
.

**Comment by al13n321** [comment]
The `clone` syscall, in newly created thread, adjusts stack pointer and stack contents, and there's logically no "caller" stack frame and no return address on the stack. `tools/add-cfi.x86_64.awk` doesn't know about any of that and autogenerates cfi as if it's just normal linear code and the syscall does nothing special. Below the syscall the cfi is just all incorrect, at least from child thread's point of view. It just happens to have the property that ip and sp are left unchanged by the unwind step. (I don't remember the details, but it's something like: the `clone` syscall puts the entry function pointer somewhere near the top of the stack, and the cfi happens to point to that offset from sp despite having incorrect cfa.)

A principled fix would be to add manual cfi annotations in `musl/src/thread/x86_64/clone.s`. But I figured that since (1) gdb does cycle detection, and (2) it's still not fixed in musl; then this is considered acceptable, and maybe even intentional. (And, IIUC, musl people generally don't want programs to be able to unwind their own stack for debugging purposes. If I send a fix to musl, I imagine the answer may be "gdb already works, libunwind already doesn't work, and that's exactly how we want it", but may be worth a try.)

**Comment by al13n321** [comment]
Feel free to close this PR if such change is not going to be accepted.

**Comment by arichardson** [comment]
Are you able to insert a `.cfi_undefined <return_register>` in the generated assembly? That would tell libunwind to stop unwinding and is cleaner than this workaround IMO.

I just noticed a similar problem in FreeBSD's startup files but I plan to fix those in FreeBSD instead of working around them here.

**Comment by MaskRay** [comment]
> Are you able to insert a `.cfi_undefined <return_register>` in the generated assembly? That would tell libunwind to stop unwinding and is cleaner than this workaround IMO.
> 
> I just noticed a similar problem in FreeBSD's startup files but I plan to fix those in FreeBSD instead of working around them here.

Thanks for weighing in. I'll close this PR. I agree that sending a patch to musl is worth trying:

> (And, IIUC, musl people generally don't want programs to be able to unwind their own stack for debugging purposes. If I send a fix to musl, I imagine the answer may be "gdb already works, libunwind already doesn't work, and that's exactly how we want it", but may be worth a try.)

**Pull request closed without merging**
