### PR TITLE
[nfc][msan] Generate test with update_test_checks.py

### PR DESCRIPTION
**Pull request by vitalybuka**
PR is to:
1. Simplify test update in #113200
2. Make tests more comprehensive, currently interesting cases looks very basic:

```
; CHECK-LABEL: @ICmpSGTAllOnes
; CHECK: icmp slt
; CHECK-NOT: call void @__msan_warning
; CHECK: icmp sgt
; CHECK-NOT: call void @__msan_warning
; CHECK: ret i1
```

### CODE REVIEW

**Comment by fmayer** [comment]
Not *re*generated

**Comment by vitalybuka** [comment]
> Not _re_generated

Please clarify, the patch looks correct to me.

**Comment by fmayer** [comment]
> > Not _re_generated
> 
> Please clarify, the patch looks correct to me.

That was a nit about the commit message. "Regenerate" sounds like it was generated with the script before.

**Comment by vitalybuka** [comment]
> > > Not _re_generated
> > 
> > 
> > Please clarify, the patch looks correct to me.
> 
> That was a nit about the commit message. "Regenerate" sounds like it was generated with the script before.

Changed.
But to me it was fine, before - generated by human, after generated by script, so re-generate. :)

**Review by fmayer — APPROVED** [review]

**Pull request merged**
