### PR TITLE
[mlir][vector] Set InBound for vector read write after peeling

### PR DESCRIPTION
**Pull request by ShivaChen**
Setting InBound attribute for vector.transfer_read/write if the loop iteration is multiple of vector size.

In this case, the number of effective vector elements in the last iteration is equal to vector size. So the mask can be avoid to generate by setting the attribute.

The loop could be produced by -scf-for-loop-peeling.

### CODE REVIEW

**Comment by ShivaChen** [comment]
> Hey, thanks for the contribution! I'm a bit confused... If the number of iterations is multiple of the vector length how is that we peel that loop? We shouldn't generate any peel loop for that case, right?
> 
> It's also not clear to me how the loop bounds relate to the boundaries of the memory access. The number of iterations of the loop could be multiple of the vector length but that is not sufficient to say that the memory access would be in-bounds. Could you help me understand this point?

Hi, thanks for the comment. The loop is generated by affine vectorizer and then peeling. If we annotate loops as loop(iteration, step), it will looks like:  loop(N, 1) -> loop(N, 64) -> mainLoop(N - N mod 64, 64) and epilogueLoop(N mod 64, 64). I was trying to remove the mask from mainLoop.

I think you are right. The memory boundary test is missing. I add the boundary test when the loop upper bound is constant. Could I ask is there way to test in-bound when the upper is unknown? Thanks for pointing the difference with C array.

**Comment by dcaballe** [comment]
> The loop is generated by affine vectorizer and then peeling. 

Let me suggest something else... Could you apply peeling before vectorization and then run the vectorizer on the main loop and optionally on the remainder loop? In that way, masks won't be generated for the main loop and you can decide how to go about the remainder loop (i.e., vectorize it or not...). WDYT?

**Comment by ShivaChen** [comment]
> > The loop is generated by affine vectorizer and then peeling.
> 
> Let me suggest something else... Could you apply peeling before vectorization and then run the vectorizer on the main loop and optionally on the remainder loop? In that way, masks won't be generated for the main loop and you can decide how to go about the remainder loop (i.e., vectorize it or not...). WDYT?

Yes, that makes sense to me. The issue is that it seems the affine dialect didn't have upstream support for peeling. Is it worth to introduce peeling in affine dialect? Could I ask how to determine which loop to apply vectorization by vectorizer? Sorry for many questions and really appreciate your comments.

**Comment by dcaballe** [comment]
> The issue is that it seems the affine dialect didn't have upstream support for peeling. Is it worth to introduce peeling in affine dialect?

There was someone asking about peeling as well on Discourse: https://discourse.llvm.org/t/rfc-mlir-vector-affine-supervectortize-optimization-for-misaligned-data/77860/5 Perhaps they have something working already :)

> Could I ask how to determine which loop to apply vectorization by vectorizer?

I guess it depends on what you want to achieve. You could vectorized both loops, one without masking an done with masking. I don't remember the logic of the Affine SuperVectorizer but if there is a way to disable masking, I guess you could also vectorize only the main vector loop and the vectorizer should bail out when trying to vectorize the remainder loop. Perhaps @sergei-grechanik can provide more context.

**Comment by ShivaChen** [comment]
> > The issue is that it seems the affine dialect didn't have upstream support for peeling. Is it worth to introduce peeling in affine dialect?
> 
> There was someone asking about peeling as well on Discourse: https://discourse.llvm.org/t/rfc-mlir-vector-affine-supervectortize-optimization-for-misaligned-data/77860/5 Perhaps they have something working already :)

That would be something I was looking for. I will wait for the patch arrived. Thanks for the information.
 
> > Could I ask how to determine which loop to apply vectorization by vectorizer?
> 
> I guess it depends on what you want to achieve. You could vectorized both loops, one without masking an done with masking. I don't remember the logic of the Affine SuperVectorizer but if there is a way to disable masking, I guess you could also vectorize only the main vector loop and the vectorizer should bail out when trying to vectorize the remainder loop. Perhaps @sergei-grechanik can provide more context.

Thanks for your guidance. Thank you ^^

**Pull request closed without merging**
