### PR TITLE
[Clang] [NFC] Prevent null pointer dereference in Sema::InstantiateFunctionDefinition

### PR DESCRIPTION
**Pull request by smanna12**
In the lambda function within clang::Sema::InstantiateFunctionDefinition, the return value of a function that may return null is now checked before dereferencing to avoid potential null pointer dereference issues which can lead to crashes or undefined behavior in the program.

### CODE REVIEW

**Review by Sirraide — COMMENTED** [review]
A pr that just adds assertions and nothing else seems like a very weird thing to do. Moreover, a few lines above in the same function, we return if this isn’t a copy/move ctor/assignment operator, which always has at least one parameter; I don’t think it is possible for `Parm` to be `nullptr` here. Do you have any code examples that would trigger this asertion here?

**Comment by Sirraide** [comment]
And moreover, `getParamDecl()` already asserts that the index is in bounds.

**Review by tahonermann — APPROVED** [review]
Looks good to me, thanks @smanna12!

**Comment by smanna12** [comment]
Thank you @tahonermann for reviews!

**Pull request merged**
