### PR TITLE
[libc++][CI] Refactor creating inline files

### PR DESCRIPTION
**Pull request by marbre**
When creating inline files, spaces cannot be used for indention. This
refactors to follow the here-doc syntax, see [1], and removes spaces.
The usage of spaces, breaks the OpenSSF Scorecard `Pinned-Dependencies`
check, see current scanning results at [2]:

```
Reason
internal error: error parsing shell code: libcxx/utils/ci/Dockerfile:1:1: unclosed here-document 'EOF'
```

[1] https://docs.docker.com/reference/dockerfile/#example-creating-inline-files
[2] https://securityscorecards.dev/viewer/?uri=github.com/llvm/llvm-project

---
**Updated to remove spaces instead of removing those, PR description before was:**

When creating inline files, spaces cannot be used for indention. This refactors to follow the here-doc syntax and replaces spaces with tabs, see [1]. The usage of spaces, breaks the OpenSSF Scorecard `Pinned-Dependencies` check, see current scanning results at [2]:

### CODE REVIEW

**Comment by philnik777** [comment]
We never use tabs in the code base, and I don't see why we should start now. Why is it a problem that spaces aren't stripped? Things clearly work just fine in the CI. If the parser of some project chokes on that, maybe the parser needs to be improved a bit.

**Comment by philnik777** [comment]
> We can also drop the indention entirely as in other scripts that create files inline.

Not a fan of that either. The indentation is there for a reason. Problems with some tooling shouldn't influence how we write the code. The tooling should be fixed.

> The scorecard action is part of the CI, thus I wouldn't necessarily agree that it works fine in the CI.

Since when? And how is it triggered? I've never seen it before, and I'm not exactly new to libc++.

> Furthermore, the Docker itself introduced here-docs as described in the 2021 blog post https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/https://www.docker.com/blog/introduction-to-heredocs-in-dockerfiles/ and the reference https://docs.docker.com/reference/dockerfile/#example-creating-inline-files. The Dockerfile is just not following the reference.

Your first link doesn't work. Your second link doesn't say anything about not using spaces for indentation. It just says that tabs are stripped according to the here-doc rules.

**Comment by marbre** [comment]
> > We can also drop the indention entirely as in other scripts that create files inline.
> 
> Not a fan of that either. The indentation is there for a reason. Problems with some tooling shouldn't influence how we write the code. The tooling should be fixed.

I don't have the impression that the tooling is broken and it would be an easy change to simply adjust the Dockerfile.
 
> > The scorecard action is part of the CI, thus I wouldn't necessarily agree that it works fine in the CI.
> 
> Since when? And how is it triggered? I've never seen it before, and I'm not exactly new to libc++.

The Scorecard (GitHub) action was added on Nov 1, see https://github.com/llvm/llvm-project/commit/0d3377c496ef2057224540650b657efb1848d63e. The commit that refactored the Dockerfile (https://github.com/llvm/llvm-project/commit/f4e3fb5972b2c42b5373952fccc8259e98b3423b) was actually landed after the Scorecard action was introduced.

> Your first link doesn't work. Your second link doesn't say anything about not using spaces for indentation. It just says that tabs are stripped according to the here-doc rules.

See for example https://www.oreilly.com/library/view/bash-cookbook/0596526784/ch03s04.html.

**Comment by philnik777** [comment]
> > > We can also drop the indention entirely as in other scripts that create files inline.
> > 
> > 
> > Not a fan of that either. The indentation is there for a reason. Problems with some tooling shouldn't influence how we write the code. The tooling should be fixed.
> 
> I don't have the impression that the tooling is broken and it would be an easy change to simply adjust the Dockerfile.
> 
> > > The scorecard action is part of the CI, thus I wouldn't necessarily agree that it works fine in the CI.
> > 
> > 
> > Since when? And how is it triggered? I've never seen it before, and I'm not exactly new to libc++.
> 
> The Scorecard (GitHub) action was added on Nov 1, see [0d3377c](https://github.com/llvm/llvm-project/commit/0d3377c496ef2057224540650b657efb1848d63e). The commit that refactored the Dockerfile ([f4e3fb5](https://github.com/llvm/llvm-project/commit/f4e3fb5972b2c42b5373952fccc8259e98b3423b)) was actually landed after the Scorecard action was introduced.
> 
> > Your first link doesn't work. Your second link doesn't say anything about not using spaces for indentation. It just says that tabs are stripped according to the here-doc rules.
> 
> See for example https://www.oreilly.com/library/view/bash-cookbook/0596526784/ch03s04.html.

According to that link it's important that `EOF` is the only thing in the end-line to make sure it's recognized as such, which is already the case.

**Comment by marbre** [comment]
> > See for example https://www.oreilly.com/library/view/bash-cookbook/0596526784/ch03s04.html.
> 
> According to that link it's important that `EOF` is the only thing in the end-line to make sure it's recognized as such, which is already the case.

Not exactly. See the warning message and in particular the 2. and 3. sentence which make it more clear:

> Just as trailing whitespace of any kind on your closing EOF delimiter prevents it from being recognized as the closing delimiter (see the warning in [Preventing Weird Behavior in a Here-Document](https://www.oreilly.com/library/view/bash-cookbook/0596526784/ch03s03.html)), so too will using a leading character other than just the tab character. If your script indents with spaces or a combination of spaces and tabs, don’t use that technique on here-documents. Either use just tabs, or keep it all flush left. Also, watch out for text editors that automatically ...

**Comment by marbre** [comment]
I wasn't that confident that it only applies to the `EOF` line but there was indeed an issue with scorecard (https://github.com/ossf/scorecard/issues/3335) and it seems the fix is not in the version executed by the action. Thus, we can close this and wait for an updated action instead.

**Comment by philnik777** [comment]
CC @tstellar ^

**Pull request closed without merging**
