### PR TITLE
[Object][x86-64] Add support for `R_X86_64_GLOB_DAT` relocations.

### PR DESCRIPTION
**Pull request by al45tair**
Add support for `R_X86_64_GLOB_DAT` relocations to the relocation resolver.

rdar://133510292

### CODE REVIEW

**Comment by al45tair** [comment]
This is a cherry-pick of https://github.com/swiftlang/llvm-project/pull/9095.

**Review by lhames — APPROVED** [review]
LGTM, thanks @al45tair!

**Comment by MaskRay** [comment]
I stared at https://github.com/swiftlang/llvm-project/pull/9095 , which gives no context why GLOB_DAT is needed. Do you have more information? RelocationResolver is primarily(exclusively?) for relocatable files. Therefore dynamic relocations are not needed.

**Comment by lhames** [comment]
@MaskRay `RelocationResolver` is used in Swift reflection on Linux. Including dynamic relocations seems reasonable -- as far as I'm aware `RelocationResolver` isn't used in any contexts where the extra cases would hurt performance.

**Comment by MaskRay** [comment]
This change made me nervous, not only because it lacks in-tree test and context.
I have contribution to glibc, musl, and FreeBSD rtld.

---

Dynamic relocation types are limited, significantly different from static relocation types.

If GLOB_DAT is the sole required relocation, explicitly checking for it in the caller would be more reliable.
Additionally, the caller should handle GLOB_DAT on other architectures.

Relying on RelocationResolver might inadvertently identify unsupported static relocation types as valid.

Introducing GLOB_DAT could negatively impact other RelocationResolver users who solely handle static relocations
and want to report errors for dynamic relocations.

**Comment by MaskRay** [comment]
I created a revert PR as I think the RelocationResolver API design should not support dynamic relocations .

More information about dynamic relocations:

"static relocation" "dynamic relocation": https://github.com/ARM-software/abi-aa/blob/main/aaelf64/aaelf64.rst#57relocation

https://git.musl-libc.org/cgit/musl/tree/ldso/dynlink.c#n467 `case REL_GOT:`

**Comment by lhames** [comment]
Revert PR is here, for reference: https://github.com/llvm/llvm-project/pull/103497

> RelocationResolver API design should not support dynamic relocations

I think it's reasonable to have `RelocationResolver` support both static and dynamic relocations, especially since some relocations are usable in both contexts, but I agree that we'd want a way to prevent accidental misuse. Straw man: an `enum class LinkingContext { Static, Dynamic }` argument to `getRelocationResolver` that can be used to select a suitable predicate.

Whether it's actually worth making this generic depends on how many more dynamic relocations we might want to evaluate. If it really is just a handful then it'll be easier to let clients do it. @al45tair -- do you know whether this is a one off, or whether we will need to support more dynamic relocations in the future?

**Comment by MaskRay** [comment]
Dynamic relocation handling is completely different. It's odd to see a routine doesn't even support RELATIVE, and GLOB_DAG is supported without JUMP_SLOT. The current interface just doesn't have sufficient information for proper dynamic relocation handling.

I strongly believe GLOB_DAT handling should be addressed separately, not in RelocationResolver.

**Comment by lhames** [comment]
> Dynamic relocation handling is completely different.

Not at the level being presented here -- this is just computing relocation expressions. I guess what you mean is that dynamic expressions can depend on parameters not available in the existing `RelocationResolver` interface, e.g. `B` and `GOT`?

The document you linked states:
> A dynamic linker need only process dynamic relocations; a static linker must handle any defined relocation.

At least as far as that doc is concerned `RelocationResolver` should probably handle this. ;)

If you want to revert while we discuss I'm fine with that. I think the discussion will depend on how many of these the Swift folks expect they'll need. If this is a one off it's fine to ask clients to handle it. If it turns out that they really need a generic relocation resolver then we can discuss what it should look like.

**Comment by MaskRay** [comment]
> > Dynamic relocation handling is completely different.
> 
> Not at the level being presented here -- this is just computing relocation expressions. I guess what you mean is that dynamic expressions can depend on parameters not available in the existing `RelocationResolver` interface, e.g. `B` and `GOT`?
> 
> The document you linked states:
> 
> > A dynamic linker need only process dynamic relocations; a static linker must handle any defined relocation.

I'll try fixing this sentence as it doesn't match the practice and all the existing ELF linkers.
Link editors don't handle dynamic-only relocations (RELATIVE, GLOB_DAT, JUMP_SLOT, IRELATIVE, etc).

> At least as far as that doc is concerned `RelocationResolver` should probably handle this. ;)
>
> If you want to revert while we discuss I'm fine with that. I think the discussion will depend on how many of these the Swift folks expect they'll need. If this is a one off it's fine to ask clients to handle it. If it turns out that they really need a generic relocation resolver then we can discuss what it should look like.

It's not only Swift, also whether the API is correctly exposed. (a) `RelocationResolver` isn't for dynamic relocations (b) Swift really could support GLOB_DAT in its own code and should support GLOB_DAT for all supported architectures.
I'll keep commenting until I convince you that adding GLOB_DAT to `RelocationResolver` isn't the right thing :)

**Comment by lhames** [comment]
> I'll try fixing this sentence as it doesn't match the practice and all the existing ELF linkers.
Link editors don't handle dynamic-only relocations (RELATIVE, GLOB_DAT, JUMP_SLOT, IRELATIVE, etc).
>
> edit: The sentence probably should be read as: static linkers need to process static relocations and produce dynamic relocations. The sentence isn't clear about whether dynamic relocations should be handled as input.

Yep. It's probably worth rewording, but FWIW the way I thought of it was: static _tooling_ should be able to handle dynamic relocations, e.g. for dumping linked images.

> It's not only Swift, also whether the API is correctly exposed. (a) RelocationResolver isn't for dynamic relocations (b) Swift really could support GLOB_DAT in its own code and should support GLOB_DAT for all supported architectures.
I'll keep commenting until I convince you that adding GLOB_DAT to RelocationResolver isn't the right thing :)

Those are declarations, I'd like to see a _reason_ if you want to convince me. ;)

My pitch: it's perfectly reasonable to have _an_ API in LLVM that can handle dynamic relocations, and that utility is going to look an _awful_ lot like `RelocationResolver`, just with a couple of different parameters. Whether we have one utility or two doesn't bother me, though it would be nice to avoid duplicating the expressions if we can avoid it.

Clients (including Swift) certainly _could_ support `GLOB_DAT` directly, but if there's a wider dynamic relocation support is needed then I think it makes sense for LLVM to provide that (and our own static tools might make use of it).

This does hinge on whether wider support is needed -- if this is a one-off then asking Swift to special-case it seems fine.

**Comment by al45tair** [comment]
I did think about this a bit before making the PR in the first place. As Lang says, the issue here is with a tool that statically inspects metadata within a Swift-compiled binary. Newer versions of LLVM changed the way some of the relocations are generated on x86-64 and started emitting `GLOB_DAT` relocations where previously it didn't, which broke the tool because it relies on `RelocationResolver`.

Now, it is true that the tool already handles `RELATIVE` itself (which it has to, because the `RelocationResolver` doesn't have enough parameters to get the correct result in that case — this is also true, of course, for many of the other dynamic relocation types), and it _could_ likewise handle `GLOB_DAT`.

However, I don't think handling `GLOB_DAT` relocations needs any extra arguments to the `RelocationResolver` function; they're for setting the GOT entries to the address of a particular symbol, and `S` is already an argument to `RelocationResolver` so there's no _technical_ reason to prefer _not_ supporting it here, and adding support to `RelocationResolver` is a trivial three line change, versus a slightly larger change in the reflection dump tool (and then again in any other tool that finds itself similarly needing to read addresses from the GOT). As for whether to support `JMP_SLOT` too, I didn't do that because we don't need it here — and I think in general tools that inspect data held in sections in executable images are less likely to need `JMP_SLOT` support. Tools that _do_ want `JMP_SLOT` support are likely doing code analysis and will probably not be leaning on LLVM infrastructure when doing that anyway.

The argument seems to be more philosophical and hinges on whether or not `RelocationResolver` should support _any_ dynamic relocations, even ones it could reasonably compute with the data it has. I don't have a particularly strong view on that — just in this particular case I came down on the side of "it can compute this easily, there are likely other tools that will have the same problem, so fixing upstream in LLVM makes sense".

**Comment by al45tair** [comment]
As for whether we should support `GLOB_DAT` for other architectures, sure, that probably makes sense, wherever this gets fixed. Other architectures appear to use `S + A` rather than just `S` for `GLOB_DAT`, but again `RelocationResolver` has all the information it needs to compute that.

**Comment by al45tair** [comment]
OK, I _think_, talking to other folks, that we're probably going to go down the fix-it-in-Swift route instead of this, so we can probably merge the revert PR (#103497).

**Comment by MaskRay** [comment]
> As for whether we should support `GLOB_DAT` for other architectures, sure, that probably makes sense, wherever this gets fixed. Other architectures appear to use `S + A` rather than just `S` for `GLOB_DAT`, but again `RelocationResolver` has all the information it needs to compute that.

This is complex. musl and newer glibc x86 uses `S`  while many glibc ports use `S+A`.

From the static linker perspective, A should always be 0. https://github.com/ARM-software/abi-aa/issues/217 is related.

> OK, I think, talking to other folks, that we're probably going to go down the fix-it-in-Swift route instead of this, so we can probably merge the revert PR (https://github.com/llvm/llvm-project/pull/103497).

Thanks!

**Pull request merged**
