### PR TITLE
[libc++] LWG3315: Replace ::new with construct_at in allocator

### LINKED ISSUE #100426: Apply 'LWG3315 Correct Allocator Default Behavior'
**Link:** https://wg21.link/lwg3315

### PR DESCRIPTION
**Pull request by amykhuang**
Change calls to `::new` to `construct_at` and call to destructor to `destroy_at` to conform with https://wg21.link/lwg3315.

Fixes #100426

### CODE REVIEW

**Comment by frederick-vs-ja** [comment]
Not sure whether change should be made here. Note that 

IIUC LWG3315 can only be considered as a patch for [P0784R7](https://wg21.link/p0784r7)/C++20, not to earlier standard revisions, and the operations in "Default" are specified for `allocator_traits`, which has been implemented in LLVM 12.0. Also, the `construct` and `destroy` member functions of `std::allocator` are removed in C++20.

**Comment by ldionne** [comment]
> Not sure whether change should be made here.
> 
> IIUC LWG3315 can only be considered as a patch for [P0784R7](https://wg21.link/p0784r7)/C++20, not to earlier standard revisions, and the operations in "Default" are specified for `allocator_traits`, which has been implemented in LLVM 12.0. Also, the `construct` and `destroy` member functions of `std::allocator` are removed in C++20.

Ah, right. So basically `LWG3315` is already "implemented" and should be marked as "Nothing To Do", I think.

**Comment by ldionne** [comment]
Sorry @amykhuang this wasn't obvious at all.

**Comment by ldionne** [comment]
Closing to keep the review queue tidy, please let me know if you think there is indeed something to do for this LWG issue and we can figure out the next steps.

**Pull request closed without merging**
