### PR TITLE
[MLIR][analysis] Lattice: Fix automatic delegation of meet to lattice value classes

### PR DESCRIPTION
**Pull request by andidr**
The class `Lattice` should automatically delegate invocations of the meet operator to the meet operation of the associated lattice value class if that class provides a static function called `meet`. This process fails for two reasons:

  1. `Lattice::has_meet` checks for a member function `meet` without arguments of the lattice value class, although it should check for a static member function.

  2. The function template `Lattice::meet<VT>()` implementing the default meet operation directly in the lattice is always present and takes precedence over the delegating function template `Lattice::meet<VT, std::integral_constant<bool, true>>()`.

This change fixes the automatic delegation of the meet operation of a lattice to the lattice value class in the presence of a static `meet` function by conditionally enabling either the delegating function template or the non-delegating function template and by changing `Lattice::has_meet` so that it checks for a static `meet` member function in the lattice value type.

The test from `TestSparseBackwardDataFlowAnalysis.cpp` is changed, such that the `meet` function is not provided directly in the `WrittenTo` lattice, but by the `Lattice` base class in order to trigger delegation to a lattice value class.

### CODE REVIEW

**Comment by matthiaskramm** [comment]
Looks good!

Not a blocker, but after this change, we don't actually have any tests that verify that inheriting directly from `AbstractSparseLattice` (instead of from `Lattice<X>`) works as expected?

**Comment by andidr** [comment]
@matthiaskramm Thanks for the review! Indeed, a merge of this change leaves no test with `meet` directly provided by the lattice. However, duplicating the test to restore the original behavior seems overly bulky and parametrization would make the test overly convoluted. Though, if you prefer any of these solutions over the current result, I'd be happy to provide and implementation and to amend the PR.

**Comment by andidr** [comment]
@matthiaskramm Any thoughts about the options for the tests? If you are fine with the current state, maybe someone with write access could go ahead and merge the changes? Thanks!

**Comment by matthiaskramm** [comment]
I'm OK with the current state. From my side, this is fine to merge in.

**Comment by andidr** [comment]
Can someone with commits rights merge (or comment if anything needs to be changed)? Maybe @ftynse?

**Comment by andidr** [comment]
Given that most of the contribution ins `mlir/include/mlir/Analysis/DataFlow/SparseAnalysis.h` are from @Mogball,  maybe @Mogball may consider merging? Thanks!

**Review by ftynse — APPROVED** [review]

**Comment by ftynse** [comment]
Apologies for the delay.

**Pull request merged**
