### PR TITLE
[compiler-rt] Fix '-Wmacro-redefined' errors

### PR DESCRIPTION
**Pull request by chestnykh**
https://lab.llvm.org/buildbot/#/builders/186/builds/880

### CODE REVIEW

**Comment by devnexen** [comment]
oh wow it s becoming complicated :)

**Comment by hctim** [comment]
I think for now it's best to update the original patch and check it, then re-land it all at once. I've reverted the original + the 1st fix-forward already in 59e1c6cd63eb9287df6516f9a5ae564075e9c218 and e7a3aeb1f86b8d45815b834e4e20b1fc7e71705d respectively.

**Comment by chestnykh** [comment]
> I think for now it's best to update the original patch and check it, then re-land it all at once. I've reverted the original + the 1st fix-forward already in [59e1c6c](https://github.com/llvm/llvm-project/commit/59e1c6cd63eb9287df6516f9a5ae564075e9c218) and [e7a3aeb](https://github.com/llvm/llvm-project/commit/e7a3aeb1f86b8d45815b834e4e20b1fc7e71705d) respectively.

No problem

**Comment by chestnykh** [comment]
Will be fixed further

**Pull request closed without merging**
