### PR TITLE
workflows/release-tasks: Don't do a test upload to test.pypi.org

### PR DESCRIPTION
**Pull request by tstellar**
I'm unable to create an account here, so I can't get a token to do the upload.

### CODE REVIEW

**Review by tru — APPROVED** [review]
Did this work before? Are they just now requiring tokens there? Anyway LGTM.

**Comment by tstellar** [comment]
This has never worked.  I added the code to do the upload but was never able to get an account/tokens.

**Comment by kwk** [comment]
Why not do a test upload? I had it working in another repo and I was able to get a token for that as well.

**Comment by tstellar** [comment]
I was able to get an account on the test server now, so we can keep this.

**Pull request closed without merging**
