### PR TITLE
[RISCV] vsetvl pseudo may cross inline asm without sideeffect

### PR DESCRIPTION
**Pull request by BeMg**
After removing side effects from the vsetvl pseudo instruction in commit ff313ee70a4f27e3555ee4baef53b9b51c5aa27e, an issue arose where vsetvl could cross inline assembly during post-RA machine scheduling. This patch reintroduces hasSideEffects=1 to prevent this undesired behavior.

### CODE REVIEW

**Comment by wangpc-pp** [comment]
I don't know if I understand correctly, correct me if I am wrong.
I think the behavior is correct, since the scheduler doesn't see the dependency of vl for `vfmadd.vv` instruction.

**Comment by lukel97** [comment]
Does the inline assembly need to model somehow that it uses `vl` and `vtype`? Marking them as clobbered seems to fix it for me (although I don't think it's the same as an input)

```llvm
define void @foo(<vscale x 8 x half> %0, <vscale x 8 x half> %1) {
entry:
  %2 = tail call i64 @llvm.riscv.vsetvli.i64(i64 3000, i64 0, i64 0)
  %3 = tail call <vscale x 8 x float> asm sideeffect "vfmadd.vv $0, $1, $2", "=^vr,^vr,^vr,0,~{vl},~{vtype}"(<vscale x 8 x float> zeroinitializer, <vscale x 8 x float> zeroinitializer, <vscale x 8 x float> zeroinitializer)
  %4 = tail call <vscale x 8 x float> asm sideeffect "vfmadd.vv $0, $1, $2", "=^vr,^vr,^vr,0,~{vl},~{vtype}"(<vscale x 8 x float> zeroinitializer, <vscale x 8 x float> zeroinitializer, <vscale x 8 x float> %3)
  tail call void @llvm.riscv.vse.nxv8f16.i64(<vscale x 8 x half> %0, ptr null, i64 %2)
  ret void
}
```

Not opposed to adding back the side effect if we need to keep real world code working though. I guess I'm surprised that the machine scheduler would move asm with side effects past an implicit-def.

**Comment by topperc** [comment]
How does gcc handle this same code? Does it make any guarantees?

**Comment by kito-cheng** [comment]
GCC no guarantee on this situation as well, I guess best way should be model the dep in the inline asm rather than mark vsetvli with sideeffect.

**Comment by kito-cheng** [comment]
Hmm, I am also thinking that we may add few more word on the intrinsic document side, to encourage.suggest user add those CSR as dependency or clobber.

```
# Mixing inline assembly and intrinsics
The compiler will be conservative to registers (vtype, vxrm, frm) when encountering inline assembly. Users should be aware that mixing uses of intrinsics and inline assembly will result in extra save and restore.
```

https://github.com/riscv-non-isa/rvv-intrinsic-doc/blob/main/doc/rvv-intrinsic-spec.adoc#mixing-inline-assembly-and-intrinsics

**Comment by wangpc-pp** [comment]
Maybe we can add a new inline asm constraint that will add implicit vl/vtype operands?

**Comment by kito-cheng** [comment]
> Maybe we can add a new inline asm constraint that will add implicit vl/vtype operands?

That sounds one possible direction, but need few more brainstorm :P

Two options in my mind so far:

1. Encoding correct VTYPE value in inline asm operand:
```
#include <riscv_vector.h>

void foo(int32_t *a, int32_t *b, int32_t *c, size_t vl){
   size_t avl = __riscv_vsetvl_e32m1(vl);
   vint32m1_t va, vb, vc;
   vb = __riscv_vle32_v_i32m1(b, avl);
   vc = __riscv_vle32_v_i32m1(c, avl);
   asm ("vadd.vv %0, %1, %2"
        : "=vr" (va)
        : "vr" (vb), "vr" (vc), "r"(avl), "VT"(ENCODING_VTYPE(SEW32, LMUL1))
        );

   __riscv_vse32_v_i32m1(a, va, avl);
}
```

But that means we need handle inline asm within vsetvli insertion.

2. Extend the syntax to allow the physical register appeared in the input operand:

```
#include <riscv_vector.h>

void foo(int32_t *a, int32_t *b, int32_t *c, size_t vl){
   size_t avl = __riscv_vsetvl_e32m1(vl);
   vint32m1_t va, vb, vc;
   vb = __riscv_vle32_v_i32m1(b, avl);
   vc = __riscv_vle32_v_i32m1(c, avl);
   asm ("vadd.vv %0, %1, %2"
        : "=vr" (va)
        : "vr" (vb), "vr" (vc), "r"(avl), "vtype");

   __riscv_vse32_v_i32m1(a, va, avl);
}
```

**Comment by BeMg** [comment]
Due to don't changed the side effect of vsetvl pseudo.

**Pull request closed without merging**
