### PR TITLE
[libc++abi] Stop copying headers to the build directory

### PR DESCRIPTION
**Pull request by arichardson**
This was needed before https://github.com/llvm/llvm-project/pull/115077
since the compiler-rt test build made assumptions about the build
layout of libc++ and libc++abi, but now they link against a local
installation of these libraries so we no longer need this workaround.

### CODE REVIEW

**Comment by arichardson** [comment]
Depends on https://github.com/llvm/llvm-project/pull/115077. Hopefully that is sufficient to remove this workaround.

**Review by ldionne — COMMENTED** [review]
Can't we do the same for libc++ as well?

**Comment by arichardson** [comment]
> Can't we do the same for libc++ as well?

Looks like CI is happy on this one so I'll try the same with libc++ next.

**Review by ldionne — APPROVED** [review]
LGTM, thanks for the cleanup!

**Pull request merged**
