### PR TITLE
[mlir] Consider mlir-linalg-ods-gen as a tablegen tool in build

### PR DESCRIPTION
**Pull request by MikeHolman**
There is a bit of an issue with how `mlir-linalg-ods-yaml-gen` is classified in the MLIR build. Due to it being a tool, it is excluded from the install when using `-DLLVM_BUILD_TOOLS=OFF`. However, it is a necessary component of the build, so it can cause build issues with users of the installed LLVM, and so I think it should not be excluded.

It is a tablegen-like tool, so my solution is to reclassify it that way in the build.

### CODE REVIEW

**Comment by MikeHolman** [comment]
Can someone please take a look when you have a chance?

Also tagging @stellaraccident who originally authored this.

**Review by stellaraccident — APPROVED** [review]
Oh thank you - this is a good catch. There seems to be a lot of special categorization I've found for "tablegen" throughout the codebase, and I've often thought that it was a bit of a misnomer that covered "code generator needed for the build that happens to always be a tablegen tool".

**Comment by MikeHolman** [comment]
@stellaraccident I don't have push access, would you be able to help merge it for me?

**Comment by stellaraccident** [comment]
> @stellaraccident I don't have push access, would you be able to help merge it for me?

Done. Sorry, new year and vacation intervened.

**Comment by sylvestre** [comment]
@MikeHolman it caused
https://github.com/llvm/llvm-project/issues/76813
could you please revert it or fix it quickly?

**Comment by MikeHolman** [comment]
Looking into this now. Will revert if I can't fix quickly.

**Comment by doru1004** [comment]
@MikeHolman your original commit was just reverted because it was breaking things. I noticed breakages on my end when building the compiler.

I am seeing the same error reported above on my end.

Do you have a fix?

**Comment by doru1004** [comment]
Thank you for the fix! When I saw the reapply, I thought it was in main. :)

**Comment by stellaraccident** [comment]
Thanks folks. Sorry I couldn't support more - vacation. If this needs more iteration in the next week or two, better to get someone else with hands on keyboard. I do think it is generally the right thing to be doing, but this layer of the build system is old and fiddly. Any details on how it failed can help a lot.

**Comment by MikeHolman** [comment]
@stellaraccident Please, enjoy your vacation! We can get this sorted or it can wait a couple more weeks.

The issue seems to be that LLVM Support library is being linked against twice in shared library builds. I believe the solution is that we don't need to explicitly link against Support here, and I have removed the linkage in #76843.

I think this is because in shared library builds, the `llvm_config` macro (which is called by `add_tablegen` via `add_llvm_executable`) will link `mlir-linalg-ods-yaml-gen` against `libLLVM`, which already contains `libSupport`, and that causes the debug-counter command line option to be registered twice.

**Comment by joshua-arch1** [comment]
> #76843 should fix this. In particular: [6af1846](https://github.com/llvm/llvm-project/commit/6af184652ef9534872a2cdeff26867f6b2951f9e)

Does this patch solve the breaking issue? When I both reapply the "Consider mlir-linalg-ods-gen as a tablegen tool in build" patch as well as the "fix linking" patch, I can stilll see "Check for working C compiler: .../bin/clang - broken".

**Comment by MikeHolman** [comment]
@joshua-arch1 I thought it did fix the issue, but it is possible what I repro'd was not the same problem you are seeing.

**Pull request merged**
