### PR TITLE
[OpenMP][libomp] Remove Perl in favor of Python

### LINKED ISSUE #62289: [OpenMP][Doc] perl is required to build openmp but not mentioned on docs
https://github.com/llvm/llvm-project/blob/acc4abea2e6a1d561bba40c60c04ad181b345999/openmp/runtime/cmake/config-ix.cmake#L224

### PR DESCRIPTION
**Pull request by jpeyton52**
* Removes all Perl scripts and modules
* Adds Python3 scripts which mimic the behavior of the Perl scripts
* Removes Perl from CMake; Adds Python3 requirement to CMake
* The check-instruction-set.pl script is Knights Corner specific. The script is removed and not replicated with a corresponding Python3 script.

Relevant Discourse:
https://discourse.llvm.org/t/error-compiling-clang-with-offloading-support/79223/4

Fixes: https://github.com/llvm/llvm-project/issues/62289

### CODE REVIEW

**Comment by shiltian** [comment]
Can you also add in the document that Python 3 is required to build `libomp`? Also, does it make sense not to enable i18 by default such that Python 3 would not become required dependence?

**Comment by jpeyton52** [comment]
Where in the documentation do we want to note the requirement? Please note that Python3 is `REQUIRED` for LLVM development in general (https://github.com/llvm/llvm-project/blob/main/llvm/CMakeLists.txt#L915) and is not just there to enable lit testing. 

We still need the scripts to generate the default English messages (no real i18n enabled) in `kmp_i18n_id.inc` and `kmp_i18n_default.inc` on all platforms and the `*.def` files on Windows.

**Comment by shiltian** [comment]
We had a complaint in the past about that we didn't mention we need perl in the document (`openmp/README.rst`), but since now we are moving to Python and it is required by LLVM project, I guess it will be fine.

**Review by shiltian — APPROVED** [review]
LGTM

**Review by jhuber6 — APPROVED** [review]
Thanks so much for addressing this.

**Pull request merged**
