### PR TITLE
[SelectOpt] Support ADD and SUB with zext operands.

### PR DESCRIPTION
**Pull request by fhahn**
Extend the support for implicit selects in the form of OR with a ZExt operand to support ADD and SUB binops as well. They similarly can form implicit selects which can be profitable to convert back the branches.

### CODE REVIEW

**Review by sapostolakis — APPROVED** [review]
Good idea. LGTM.

**Comment by fhahn** [comment]
This only enables it for AArch64, @sapostolakis not sure if you would like to look into enabling this for other architectures (I think the OR support is only enabled for AArch64 as well)

**Comment by davemgreen** [comment]
Do you have performance results for this change? I was trying in the past to try and keep it relatively conservative, as based on the predictability of the branch it can make things better or worse. (We found a case when it was worse recently). We have been looking at some other selects that could benefit from the transform, but I had expected they would only be generally profitable once you considered them part of a larger select group.

My understanding was that the Apple cpus did not use this option either. Do you intend to change that?

**Comment by davemgreen** [comment]
Oh and theoretically a `zext i1 %c` is `select %c, 1, 0`, and `sext i1 %c` is `select %c, -1, 0`, so the add/sub/or part might not be strictly necessary if they not there to control profitability.

**Comment by fhahn** [comment]
> Do you have performance results for this change? I was trying in the past to try and keep it relatively conservative, as based on the predictability of the branch it can make things better or worse. (We found a case when it was worse recently). We have been looking at some other selects that could benefit from the transform, but I had expected they would only be generally profitable once you considered them part of a larger select group.
> 
> My understanding was that the Apple cpus did not use this option either. Do you intend to change that?

I am currently working on enabling it for Apple CPUs and for some motivating cases we need support for `Adds`.  The motivating cases are somewhat similar to the ones mentioned in https://github.com/llvm/llvm-project/pull/115745.

Overall enabling it with this change is neutral on SPEC and some other proprietary benchmarks. I agree that there is the risk that if we get it wrong the result can be pretty bad. But I don't think the `Add` case is different to the `Or` case and if anything the cost-model should be responsible for making the decision. 

I expect that as we support more cases, we are likely hitting additional cases where the cost-model gets things wrong. What do you think is the best way to make progress here?

**Comment by davemgreen** [comment]
> I am currently working on enabling it for Apple CPUs and for some motivating cases we need support for `Adds`. The motivating cases are somewhat similar to the ones mentioned in #115745.

That's good to hear. I was under the impression (without knowing any of the details) that they were at least less susceptible to the issues we see. Maybe they are present everywhere to some extent.

> Overall enabling it with this change is neutral on SPEC and some other proprietary benchmarks. I agree that there is the risk that if we get it wrong the result can be pretty bad. But I don't think the `Add` case is different to the `Or` case and if anything the cost-model should be responsible for making the decision.

Yeah the add and or are very similar. We ruled out logical and/or in ca78b5601466f8515f5f958ef8e63d787d9d812e, and recently prevented it from folding selects with two constant operands in 1789534ac1ac95f9a3369625e331b9a446be60d9. I also tried to make the or relatively constrained when I added it, only adding them where a branch already existed (a2d68b4bece54bcfa7bfde1e80058ab19b6d1775). I am a bit suspicious of things that look like logic or arithmetic, as they are sometimes quicker as logic/arithmetic.

The problem with the cost model is that it doesn't know how predictable the branch is, and so doesn't have full info available. My understanding is that well-predictable loops can benefit greatly from converting the selects, but in larger codebases that are already heavy on the number of branches it can introduce extra overhead.

> I expect that as we support more cases, we are likely hitting additional cases where the cost-model gets things wrong. What do you think is the best way to make progress here?

Honestly - My hope was that they would fix it in the hardware :) I ran this and it didn't look too bad, but I didn't look into any specific case deeply. 

Do you have tests for commuted sub operands, where the first operand is the condition?

**Comment by davemgreen** [comment]
Hi - Yeah the heuristic is trying to do the best it can with the information it has, it just won't always be perfect. @igogo-x86 mentioned that this was something he was planning to add anyway, so it sounds OK as it will likely be added either here or in another patch. If it was me I might make it more conservative (maybe only do it if it was part of a larger select group), but I don't know of any cases where this will directly cause problems. The example above with i128 addition doesn't trigger on its own.

The sub issue still remains as I believe they will be treated like a commutative operation, so we would need to make sure it was the second operand that was the zext/sext.

**Comment by fhahn** [comment]
> Hi - Yeah the heuristic is trying to do the best it can with the information it has, it just won't always be perfect. @igogo-x86 mentioned that this was something he was planning to add anyway, so it sounds OK as it will likely be added either here or in another patch. If it was me I might make it more conservative (maybe only do it if it was part of a larger select group), but I don't know of any cases where this will directly cause problems. The example above with i128 addition doesn't trigger on its own.
> 
> The sub issue still remains as I believe they will be treated like a commutative operation, so we would need to make sure it was the second operand that was the zext/sext.

Thanks, updated the patch after @igogo-x86 latest patch landing again, and I think the operands are added in the correct order (e.g. as in `test_sub_zext_first_op`)?

**Comment by alexfh** [comment]
Heads up: we see a number of test failures on aarch64 after this commit. Might be a miscompilation. A reduced test case is in the works.

**Comment by igogo-x86** [comment]
@alexfh Thanks! Could you check if this patch fixes the problem - #119362 ?

**Comment by alexfh** [comment]
Thanks for the fix! It resolves the issues we're seeing.

**Pull request merged**
