### PR TITLE
[DAGCombiner] Don't drop atomic property of original load.

### PR DESCRIPTION
**Pull request by JonPsson1**
It seems that visitBITCAST() fails to pass on the atomic property of the load it is converting:

```
Legalized selection DAG: %bb.0 'f1:'
SelectionDAG has 12 nodes:
  t0: ch,glue = EntryToken
      t6: f32 = bitcast t12
      t4: f32,ch = CopyFromReg t0, Register:f32 %1
    t7: f32 = fadd t6, t4
  t9: ch,glue = CopyToReg t12:1, Register:f32 $f0s, t7
    t2: i64,ch = CopyFromReg t0, Register:i64 %0
  t12: i32,ch = load<(volatile load seq_cst (s32) from %ir.src)> t0, t2, undef:i64
  t10: ch = SystemZISD::RET_GLUE t9, Register:f32 $f0s, t9:1

Optimized legalized selection DAG: %bb.0 'f1:'
SelectionDAG has 11 nodes:
  t0: ch,glue = EntryToken
      t4: f32,ch = CopyFromReg t0, Register:f32 %1
    t7: f32 = fadd t13, t4
  t9: ch,glue = CopyToReg t13:1, Register:f32 $f0s, t7
    t2: i64,ch = CopyFromReg t0, Register:i64 %0
  t13: f32,ch = load<(volatile load (s32) from %ir.src)> t0, t2, undef:i64
  t10: ch = SystemZISD::RET_GLUE t9, Register:f32 $f0s, t9:1
```

This patch simply passes the original MMO instead of different individual values, which looks ok given that values all come from the MMO. This way, the seq_cst bit is not missed.

I expected NFC, but got some X86 test failures, which I auto-updated. I got warnings from the update_llc_test_checks.py scripts with these tests:

```
X86/vector-interleaved-load-i16-stride-4.ll
X86/vector-interleaved-store-i64-stride-4.ll
X86/vector-interleaved-store-i64-stride-5.ll
X86/vector-interleaved-store-i64-stride-8.ll

WARNING: Prefix AVX had conflicting output from different RUN lines for all functions in test ...
```

### CODE REVIEW

**Comment by RKSimon** [comment]
The update warnings are not a problem - we reuse the same check-prefixes for all the vector-interleaved-* tests to make them easier to maintain, so there are some cases where prefixes don't get used.

**Review by RKSimon — COMMENTED** [review]
Are you able to create a test for the lost atomic property? I haven't checked but my guess is the x86 cases are losing the original dereferencable memory size or something as the SSE/AVX cases are splitting 512-bit loads down to 4 x 128-bits, so this patch is helping.

**Comment by topperc** [comment]
Shouldn't a seq_cst load be an ISD::ATOMIC_LOAD not an ISD::LOAD?

**Comment by topperc** [comment]
This changes causes the same X86 changes

```
diff --git a/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp b/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp
index c782ad117ce6..90a0cf5acb12 100644
--- a/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp
+++ b/llvm/lib/CodeGen/SelectionDAG/DAGCombiner.cpp
@@ -15165,7 +15165,7 @@ SDValue DAGCombiner::visitBITCAST(SDNode *N) {
                                     *LN0->getMemOperand())) {
       SDValue Load =
           DAG.getLoad(VT, SDLoc(N), LN0->getChain(), LN0->getBasePtr(),
-                      LN0->getPointerInfo(), LN0->getAlign(),
+                      LN0->getPointerInfo(), LN0->getOriginalAlign(),
                       LN0->getMemOperand()->getFlags(), LN0->getAAInfo());
       DAG.ReplaceAllUsesOfValueWith(N0.getValue(1), Load.getValue(1));
       return Load;
```

getAlign() combines the base alignment of the MMO with the MMO offset. This can cause the base alignment of the newly created MMO to become smaller than the original MMO. This can produce different results if the MMO is later split into multiple MMOs with different offsets.

**Comment by JonPsson1** [comment]
> getAlign() combines the base alignment of the MMO with the MMO offset. This can cause the base alignment of the newly created MMO to become smaller than the original MMO. This can produce different results if the MMO is later split into multiple MMOs with different offsets.

I don't quite follow how this could go wrong as folding the bitcast doesn't change the memory access in any way. Shouldn't the later splitting also take into account the original offset?

**Comment by topperc** [comment]
> > getAlign() combines the base alignment of the MMO with the MMO offset. This can cause the base alignment of the newly created MMO to become smaller than the original MMO. This can produce different results if the MMO is later split into multiple MMOs with different offsets.
> 
> 
> 
> I don't quite follow how this could go wrong as folding the bitcast doesn't change the memory access in any way. Shouldn't the later splitting also take into account the original offset?
> 
> 

I may have explained that badly. The code should have used getOriginalAlign to begin with. Not the first case of this I've seen.

Using getAlign probably decreased the alignment based on the trailing zeros of the current offset. A later split probably gave a new offset that had more trailing zeros. By using original align we are able to infer a larger alignment for this new offset. With getAlign it's been overly reduced so the new offset can't increase it.

This patch has the same effect as using getOriginalAlign.

**Comment by JonPsson1** [comment]
> Shouldn't a seq_cst load be an ISD::ATOMIC_LOAD not an ISD::LOAD?

Good question - it seems SystemZ::lowerATOMIC_LOAD() simply replaces the ATOMIC_LOAD with a normal LOAD which is ok generally for the architecture as all naturally aligned loads are atomic.

The MachineMemOperand has the isAtomic() method, which is used by the MemSDNode::isSimple(). LoadSDNode and AtomicSDNode are separate subclasses derived from MemSDNode. This is a little confusing to me: if the isAtomic() is only relevent for AtomicSDNode, AtomicSDNode should override isSimple() and always return 'false', and MemSDNode should not care about isAtomic().

I agree that it could be that the intent is actually that MMO->isAtomic() of any regular LOAD/STORE is ok to ignore, so this patch is not really relevant..? Maybe instead a comment documenting this would be more appropriate if this is the case.

On the other hand, if DAGCombiner is indeed free to ignore the MMO->isAtomic() on any STORE/LOAD, then the SystemZ lowering makes me a little worried. Could DAGCombiner ever e.g. combine loads with an underaligned result, e.g. two 4-byte loads resulting in a single 8-byte load aligned only to 4 bytes?

**Comment by RKSimon** [comment]
We have various TLI.allowsMemoryAccess checks for load combines which should prevent merging consecutive atomic loads etc.

Is it worth doing the OriginalAlign fix as a preliminary patch?

**Comment by JonPsson1** [comment]
It seems this patch actually shouldn't go in since it is probably not intentional to have DAGCombiner work on LOADs that are actually atomic. In other words, the MMO atomic state would generally be ignored with an ISD::LOAD, so if anything the SystemZ::lowerATOMIC_LOAD() should be improved. 

Ok to close this?

**Comment by jyknight** [comment]
See also @preames comment in commit a0dde7b8d16842005d6f5247dda6f17c77a5906f. I think the idea is to delete the support for atomic LoadSDNode, after moving SystemZ off of it.

**Comment by JonPsson1** [comment]
> See also @preames comment in commit [a0dde7b](https://github.com/llvm/llvm-project/commit/a0dde7b8d16842005d6f5247dda6f17c77a5906f). I think the idea is to delete the support for atomic LoadSDNode, after moving SystemZ off of it.

Made a patch for this: https://github.com/llvm/llvm-project/pull/75879

**Comment by arsenm** [comment]
> It seems this patch actually shouldn't go in since it is probably not intentional to have DAGCombiner work on LOADs that are actually atomic. In other words, the MMO atomic state would generally be ignored with an ISD::LOAD, so if anything the SystemZ::lowerATOMIC_LOAD() should be improved.
> 
> Ok to close this?

I think this should still go ahead. I still think it's a good idea to get rid of ISD::ATOMIC_LOAD and migrate to using load with atomic operands. This is a code simplification anyway

**Comment by jyknight** [comment]
> I think this should still go ahead. I still think it's a good idea to get rid of ISD::ATOMIC_LOAD and migrate to using load with atomic operands. 

Not sure I agree with that.

> This is a code simplification anyway

Agreed, this patch is good to submit as a simplification and bugfix for the alignment, regardless of the issues around ATOMIC_LOAD.

**Pull request merged**
