### PR TITLE
[libc][config] Add malloc as baremetal arm entrypoint

### PR DESCRIPTION
**Pull request by PiJoules**

### CODE REVIEW

**Comment by petrhosek** [comment]
Can you also include it in `libc/config/baremetal/riscv/entrypoints.txt`? What about `calloc` and `free`?

**Comment by PiJoules** [comment]
> Can you also include it in `libc/config/baremetal/riscv/entrypoints.txt`?

Done. 

> What about `calloc` and `free`?

Those symbols are included with the `malloc` cmake target, but at some point I should also split them into their separate files/targets.

**Comment by michaelrj-google** [comment]
you should still list `calloc` and `free` if you're planning to use them, since they should be listed as dependencies in entrypoints that use them. An entrypoint missing any dependency will get skipped which may cause unexpected behavior.

**Comment by PiJoules** [comment]
> you should still list `calloc` and `free` if you're planning to use them, since they should be listed as dependencies in entrypoints that use them. An entrypoint missing any dependency will get skipped which may cause unexpected behavior.

Done

**Review by petrhosek — APPROVED** [review]

**Review by michaelrj-google — APPROVED** [review]

**Pull request merged**
