### PR TITLE
[flang][openacc] Convert rhs expr to the lhs type on atomic read/write

### PR DESCRIPTION
**Pull request by clementval**
In some cases the rhs expression scalar type is not the same as the lhs type. A convert op is needed before the acc.atomic.read or acc.atomic.write operation to fit with the requirements of the operations.

### CODE REVIEW

**Comment by kiranchandramohan** [comment]
Haven't looked into this in detail but using the typed assignment rather than the parser::Expr had previously fixed a similar issue for Atomic Write.  https://reviews.llvm.org/D154163

**Comment by clementval** [comment]
Thanks @kiranchandramohan I'll check if we can apply the same fix!

**Comment by kiranchandramohan** [comment]
If that does not work feel free to move ahead with this patch.

**Comment by clementval** [comment]
> If that does not work feel free to move ahead with this patch.

It might be possible for the capture case but I see extra store for the read one.

**Comment by clementval** [comment]
@kiranchandramohan I updated the capture code to use the typed assignment. I left the read code as is to avoid extra store operation.

**Review by kiranchandramohan — APPROVED** [review]
Thanks @clementval. LGTM.

**Review by razvanlupusoru — APPROVED** [review]
Thank you!

**Pull request merged**
