### PR TITLE
[llvm-exegesis] Use hex values when parsing memory mappings

### PR DESCRIPTION
**Pull request by boomanaiden154**
Currently, the address in the LLVM-EXEGESIS-MEM-MAP annotation is parsed in decimal format. This makes it inconsistent with the rest of the program and inconsistent with the way most memory addresses are presented as they are presented in hexadeicmal. This patch changes this behavior so that llvm-exegesis automatically parses the address in LLVM-EXEGESIS-MEM-MAP annotations as a hexadeicmal value.

### CODE REVIEW

**Comment by boomanaiden154** [comment]
@ondrasej 

There are relatively few (known) users of the memory annotations in `llvm-exegesis`, so I don't believe this change should have any significant impact on existing users and will probably make it easier to use for those existing users (have had at least one question about that so far).

**Comment by boomanaiden154** [comment]
Additionally, we might want to do the same for the memory definition sizes. That would probably be for the best given everything else will be in hex after this point for consistency purposes.

**Comment by legrosbuffle** [comment]
As this change is not backwards compatible we might be breaking people with no way for them/us to know. I see two options:

 - Support both decimal and hexadecimal. Prefix the latter with `0x`
 - Add a new deirective ` LLVM-EXEGESIS-MEM-MAP-HEX`  that reads hex values.

**Comment by boomanaiden154** [comment]
> Reference

Right, this change won't be backwards compatible. It was a fairly significant oversight on my part when doing the implementation, and I'd really like to get this fixed properly (along with the definition sizes) early on while there are relatively few users of this feature and relatively little external tooling that relies on it.

I think just doing the change now and adding a note in the release notes at this point would keep everything clean without having to introduce additional annotations/keep the very unintuitive interface that we have currently.

**Comment by legrosbuffle** [comment]
As far as I'd like introducing name churn I don't think we can rely on people reading the release notes for this. We can't know whether someone is relying on these values; doing things properly is probably less work than people debugging the issue on their side.

The 0x opetion avoids changing the name and actually makes it clear that the value is hex.

**Comment by boomanaiden154** [comment]
That's a good point. I'll close this patch for now and probably open up a follow-up patch allowing for the parsing of mapping addresses with 0x, and maybe the other values too for consistency.

Thanks for your input here.

**Pull request closed without merging**
