### PR TITLE
[ValueTracking] Track `or disjoint` conditions as add in Assumption/DomCondition Cache

### PR DESCRIPTION
**Pull request by goldsteinn**
- **[ValueTracking] Add basic tests tracking `or disjoint` conditions as `add`; NFC**
- **[ValueTracking] Tracking `or disjoint` conditions as `add` in Assumption/DomCondition Cache**

### CODE REVIEW

**Comment by dtcxzyw** [comment]
According to the test result, I'd like to merge the remaining part of https://github.com/llvm/llvm-project/pull/86059 first.

**Comment by goldsteinn** [comment]
> According to the test result, I'd like to merge the remaining part of #86059 first.

This one isn't really meant to be impactful, imo its just cleanup to use `addlike` instead of `add` in as many places as we can. Think there is very little risk involved.

**Comment by goldsteinn** [comment]
> > According to the test result, I'd like to merge the remaining part of #86059 first.
> 
> This one isn't really meant to be impactful, imo its just cleanup to use `addlike` instead of `add` in as many places as we can. Think there is very little risk involved.

That okay?

**Review by dtcxzyw — APPROVED** [review]
LGTM.

**Pull request closed without merging**
