### PR TITLE
[asan] Ignore vDSO on FreeBSD

### PR DESCRIPTION
**Pull request by rorth**
Most asan tests `FAIL` on FreeBSD 14.0/amd64 with
```
==17651==ASan runtime does not come first in initial library list; you should either link runtime to your application or manually preload it with LD_PRELOAD.
```
With `ASAN_OPTIONS=verbosity=2` one sees:
```
==4880==info->dlpi_name = [vdso]	info->dlpi_addr = 0xffffe780
==4880==info->dlpi_name = lib/clang/18/lib/freebsd/libclang_rt.asan-i386.so	info->dlpi_addr = 0x2808a000
```
Ignoring the vDSO as on Linux fixes this.

Tested on `amd64-pc-freebsd14.0`.

### CODE REVIEW

**Comment by brad0** [comment]
I ran into this issue recently, after wanting to test removing a patch for qsort() interception and not being aware of the root issue.

Then ran into Dimity's post on Discourse.. https://discourse.llvm.org/t/llvm-16-0-0-rc4-has-been-tagged/69150/8

**Review by DimitryAndric — APPROVED** [review]
This looks pretty reasonable. I should have spent some time on digging into this, but thanks Rainer!

**Comment by DimitryAndric** [comment]
@rorth  I'll cherry-pick this fix into FreeBSD 15-CURRENT, so it can be merged back to 14-STABLE.

**Comment by DimitryAndric** [comment]
Btw on 15-CURRENT I can apply this patch, and then indeed I don't get "ASan runtime does not come first in initial library list" anymore, but another assertion failure instead:

```text
$  ldd ./asantest-shared
./asantest-shared:
        libclang_rt.asan-x86_64.so => /usr/lib/clang/17/lib/freebsd/libclang_rt.asan-x86_64.so (0xc369bfd000)
        libc.so.7 => /lib/libc.so.7 (0xc368118000)
        libc++.so.1 => /lib/libc++.so.1 (0xc368f43000)
        libcxxrt.so.1 => /lib/libcxxrt.so.1 (0xc36b186000)
        libm.so.5 => /lib/libm.so.5 (0xc36c555000)
        libgcc_s.so.1 => /lib/libgcc_s.so.1 (0xc36bdb2000)
        [vdso] (0xc3678f6000)

$ ./asantest-shared
AddressSanitizer: CHECK failed: asan_posix.cpp:121 "((0)) == ((pthread_key_create(&tsd_key, destructor)))" (0x0, 0x4e) (tid=100239)
    <empty stack>
```

So I'm not going to cherry-pick now, until I can figure out why it still fails.

**Pull request merged**
