### PR TITLE
[Headers][X86] Reformat ia32intrin.h doc to match the other headers

### PR DESCRIPTION
**Pull request by pogo59**
Doxygen comment style for every other intrinsic-function header uses /// comments, so change ia32intrin.h from the /** style to /// style. While I was in there, change `<c> INSTR </c>` to `\c INSTR` and toss in a few missing full-stops.

### CODE REVIEW

**Comment by pogo59** [comment]
I'm going to be adding some new function descriptions to this file shortly, and figured I should get the formatting thing out of the way first.

**Comment by KanRobert** [comment]
cc @FreddyLeaf

**Review by phoebewang — APPROVED** [review]
LGTM.

**Review by FreddyLeaf — APPROVED** [review]
LGTM

**Review by KanRobert — APPROVED** [review]

**Pull request merged**
