### PR TITLE
Update amdgpu_gfx functions to use s0-s3 for inreg SGPR arguments on targets using scratch instructions for stack #78226

### LINKED ISSUE #78226: amdgpu_gfx functions do not use s0-s3 for inreg SGPR arguments on targets using scratch instructions for stack
Unlike compute functions, amdgpu_gfx does not attempt to claim s[0:3] for inreg SGPR argument space. They are simply dropped from the list of argument registers. 
```

; RUN: llc -march=amdgcn -mcpu=gfx940 -o - < %s

declare void @compute(i32 inreg)
declare amdgpu_gfx void @gfx(i32 inreg)

define amdgpu_kernel void @call_compute() {
  call void @compute(i32 inreg 123)
  ret void
}

define amdgpu_cs void @call_gfx() {
  call amdgpu_gfx void @gfx(i32 inreg 123)
  ret void
}

```

compute copies 123 to $sgpr0, and amdgpu_gfx copies to $sgpr4

### PR DESCRIPTION
**Pull request by SahilPatidar**
Resolve #78226

### CODE REVIEW

**Comment by SahilPatidar** [comment]
@arsenm

**Review by arsenm — COMMENTED** [review]
I believe this is correct but needs the test updates

**Comment by arsenm** [comment]
Duplicate #78553

**Comment by SahilPatidar** [comment]
@arsenm, 
why are some test updates crashing with this output:
Assertion failed: (Reg != AMDGPU::NoRegister), function allocateFixedSGPRInputImpl, file /Users/sahilpatidar/Desktop/llvm/llvm-project/llvm/lib/Target/AMDGPU/SIISelLowering.cpp, line 2292.

**Comment by SahilPatidar** [comment]
@arsenm 
Failed Tests (20):
  LLVM :: CodeGen/AMDGPU/GlobalISel/irtranslator-call-non-fixed.ll
  LLVM :: CodeGen/AMDGPU/GlobalISel/irtranslator-call.ll
  LLVM :: CodeGen/AMDGPU/GlobalISel/irtranslator-function-args.ll
  LLVM :: CodeGen/AMDGPU/amdgpu-simplify-libcall-pow-codegen.ll
  LLVM :: CodeGen/AMDGPU/bf16.ll
  LLVM :: CodeGen/AMDGPU/call-args-inreg.ll
  LLVM :: CodeGen/AMDGPU/combine_andor_with_cmps.ll
  LLVM :: CodeGen/AMDGPU/flat_atomics_i32_system.ll
  LLVM :: CodeGen/AMDGPU/flat_atomics_i64_system.ll
  LLVM :: CodeGen/AMDGPU/fsub-as-fneg-src-modifier.ll
  LLVM :: CodeGen/AMDGPU/function-args-inreg.ll
  LLVM :: CodeGen/AMDGPU/gfx-callable-argument-types.ll
  LLVM :: CodeGen/AMDGPU/global_atomics_i32_system.ll
  LLVM :: CodeGen/AMDGPU/global_atomics_i64_system.ll
  LLVM :: CodeGen/AMDGPU/indirect-call.ll
  LLVM :: CodeGen/AMDGPU/preserve-wwm-copy-dst-reg.ll
  LLVM :: CodeGen/AMDGPU/schedule-addrspaces.ll
  LLVM :: CodeGen/AMDGPU/scratch-pointer-sink.ll
  LLVM :: CodeGen/AMDGPU/stacksave_stackrestore.ll
  LLVM :: CodeGen/AMDGPU/wwm-reserved-spill.ll


Testing Time: 3196.43s

Total Discovered Tests: 3484
  Unsupported      :    1 (0.03%)
  Passed           : 3455 (99.17%)
  Expectedly Failed:    8 (0.23%)
  Failed           :   20 (0.57%)
Total of 20 cases failed, but when I updated, around 5 to 6 tests crashed.

**Comment by arsenm** [comment]
> @arsenm, why are some test updates crashing with this output: Assertion failed: (Reg != AMDGPU::NoRegister), function allocateFixedSGPRInputImpl, file /Users/sahilpatidar/Desktop/llvm/llvm-project/llvm/lib/Target/AMDGPU/SIISelLowering.cpp, line 2292.

That indicates a free register wasn't found available for an input. What do the function signatures look like for the cases that hit this?

**Comment by SahilPatidar** [comment]
@arsenm,
for this test function `define void @void_func_a13i32_inreg([13  x i32] inreg %arg0, ptr addrspace(1) %ptr)`

**Comment by SahilPatidar** [comment]
And another crash is in this file: llvm/test/CodeGen/AMDGPU/amdgpu-simplify-libcall-pow-codegen.ll.

Assertion failed: (castIsValid(op, S, Ty) && "Invalid cast!"), function Create, file /Users/sahilpatidar/Desktop/llvm-project-17.0.3.src/llvm/lib/IR/Instructions.cpp, line 3427.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -passes=amdgpu-simplifylib,instcombine -amdgpu-prelink
 #0 0x0000000105ee7968 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/usr/local/bin/opt+0x105ba3968)
 #1 0x0000000105ee7ebc PrintStackTraceSignalHandler(void*) (/usr/local/bin/opt+0x105ba3ebc)
 #2 0x0000000105ee5cb8 llvm::sys::RunSignalHandlers() (/usr/local/bin/opt+0x105ba1cb8)
 #3 0x0000000105ee9af4 SignalHandler(int) (/usr/local/bin/opt+0x105ba5af4)
 #4 0x0000000186cbda24 (/usr/lib/system/libsystem_platform.dylib+0x18046da24)
 #5 0x0000000186c8dcc0 (/usr/lib/system/libsystem_pthread.dylib+0x18043dcc0)
 #6 0x0000000186b99a40 (/usr/lib/system/libsystem_c.dylib+0x180349a40)
 #7 0x0000000186b98d30 (/usr/lib/system/libsystem_c.dylib+0x180348d30)
 #8 0x00000001047e7138 llvm::CastInst::Create(llvm::Instruction::CastOps, llvm::Value*, llvm::Type*, llvm::Twine const&, llvm::Instruction*) (/usr/local/bin/opt+0x1044a3138)
 #9 0x0000000105bb2c60 llvm::IRBuilderBase::CreateCast(llvm::Instruction::CastOps, llvm::Value*, llvm::Type*, llvm::Twine const&) (/usr/local/bin/opt+0x10586ec60)
#10 0x0000000105bb2e1c llvm::IRBuilderBase::CreateBitCast(llvm::Value*, llvm::Type*, llvm::Twine const&) (/usr/local/bin/opt+0x10586ee1c)
#11 0x0000000100ee816c llvm::AMDGPULibCalls::fold_pow(llvm::CallInst*, llvm::IRBuilder<llvm::ConstantFolder, llvm::IRBuilderDefaultInserter>&, llvm::AMDGPULibFunc const&) (/usr/local/bin/opt+0x100ba416c)
#12 0x0000000100ee5a70 llvm::AMDGPULibCalls::fold(llvm::CallInst*, llvm::AAResults*) (/usr/local/bin/opt+0x100ba1a70)
#13 0x0000000100eeb4b4 llvm::AMDGPUSimplifyLibCallsPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/usr/local/bin/opt+0x100ba74b4)
#14 0x0000000101092ee8 llvm::detail::PassModel<llvm::Function, llvm::AMDGPUSimplifyLibCallsPass, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/usr/local/bin/opt+0x100d4eee8)
#15 0x00000001048f9574 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/usr/local/bin/opt+0x1045b5574)
#16 0x000000010109d3d8 llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (/usr/local/bin/opt+0x100d593d8)
#17 0x0000000104900870 llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/local/bin/opt+0x1045bc870)
#18 0x000000010109cf24 llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::PreservedAnalyses, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/local/bin/opt+0x100d58f24)
#19 0x00000001048f8720 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (/usr/local/bin/opt+0x1045b4720)
#20 0x000000010034ba64 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool, bool) (/usr/local/bin/opt+0x100007a64)
#21 0x000000010039e3dc main (/usr/local/bin/opt+0x10005a3dc)
#22 0x000000018690d0e0 
/bin/sh: line 1:  3274 Abort trap: 6           opt -mtriple=amdgcn-amd-amdhsa -mcpu=gfx900 -passes=amdgpu-simplifylib,instcombine -amdgpu-prelink < llvm/test/CodeGen/AMDGPU/amdgpu-simplify-libcall-pow-codegen.ll

**Comment by arsenm** [comment]
> And another crash is in this file: llvm/test/CodeGen/AMDGPU/amdgpu-simplify-libcall-pow-codegen.ll.
> 

I don't see how you could have run into this with this patch. It's not even running codegen

**Comment by arsenm** [comment]
> > And another crash is in this file: llvm/test/CodeGen/AMDGPU/amdgpu-simplify-libcall-pow-codegen.ll.
> 
> I don't see how you could have run into this with this patch. It's not even running codegen

> /Users/sahilpatidar/Desktop/llvm-project-17.0.3.src

Are you running something else in a release?

**Comment by SahilPatidar** [comment]
I'm running this command  - `python3 llvm/utils/update_llc_test_checks.py --llc-binary=build/bin/llc llvm/test/CodeGen/AMDGPU/amdgpu-simplify-libcall-pow-codegen.ll`

**Comment by SahilPatidar** [comment]
@arsenm,
The issue might be with the system-installed opt binary. Is there a way to include the opt binary from the build?

**Comment by arsenm** [comment]
> @arsenm, The issue might be with the system-installed opt binary. Is there a way to include the opt binary from the build?

update_llc_test_checks doesn't know how to run opt. For combined tests, I usually hack around it by deleting the opt/llc run lines and then running the appropriate scripts, before restoring the run lines.

You can also try to use update_any_test_checks, but I haven't used that successfully before

**Comment by SahilPatidar** [comment]
> > @arsenm, why are some test updates crashing with this output: Assertion failed: (Reg != AMDGPU::NoRegister), function allocateFixedSGPRInputImpl, file /Users/sahilpatidar/Desktop/llvm/llvm-project/llvm/lib/Target/AMDGPU/SIISelLowering.cpp, line 2292.
> 
> That indicates a free register wasn't found available for an input. What do the function signatures look like for the cases that hit this?

for this test function `define void @void_func_a13i32_inreg([13  x i32] inreg %arg0, ptr addrspace(1) %ptr)`

**Comment by SahilPatidar** [comment]
@arsenm,
here are a few expected failed cases. Let me know if they need to be updated.
```
Total Discovered Tests: 3484
  Unsupported      :   49 (1.41%)
  Passed           : 3429 (98.42%)
  Expectedly Failed:    6 (0.17%)
```

**Review by arsenm — APPROVED** [review]
lgtm, thanks

**Comment by tsymalla** [comment]
Hi @arsenm  @SahilPatidar Please take a look at the referenced revert PR #86273, since the change introduced here breaks some tests.

**Pull request merged**
