### PR TITLE
[OpenMP] Team reduction work specialization

### PR DESCRIPTION
**Pull request by jdoerfert**
Last commit, the others are part of existing PRs.

### CODE REVIEW

**Review by jhuber6 — APPROVED** [review]
LG

**Comment by ronlieb** [comment]
patch seems to break these 4 sollve tests

./sollve_vv/tests/4.5/target_teams_distribute/test_target_teams_distribute_reduction_and.c
./sollve_vv/tests/5.0/target_teams_distribute/test_target_teams_distribute_reduction_and.c
./sollve_vv/tests/4.5/target_teams_distribute/test_target_teams_distribute_reduction_multiply.c
./sollve_vv/tests/5.0/target_teams_distribute/test_target_teams_distribute_reduction_multiply.c

fail in latest build of llvm, passes if patch reverted locally i nbuild

**Comment by AntonRydahl** [comment]
This commit breaks minimization and multiplication reductions.

**Comment by shiltian** [comment]
The patch has been reverted @AntonRydahl

**Comment by AntonRydahl** [comment]
When? I just found it with git bisect on main. Maybe something is wrong in my fork.

**Comment by ronlieb** [comment]
i dont see it reverted either. i do recall Shilei , you reverted a different reduction related patch with 3 sollve failures, this one has 4.

**Comment by AntonRydahl** [comment]
I think there were multiple reduction commits on the same day. It is in the history here: https://github.com/llvm/llvm-project/commits/main/openmp/libomptarget/DeviceRTL/src/Reduction.cpp

**Comment by shiltian** [comment]
@AntonRydahl @ronlieb Sorry I was looking at the wrong one:
```
[searlmc1](https://github.com/searlmc1) pushed a commit to RadeonOpenCompute/llvm-project that referenced this pull request [3 days ago](https://github.com/llvm/llvm-project/pull/70766#ref-commit-07441d5)
@ronlieb
[Revert "[OpenMP] Provide a specialized team reduction for the common …](https://github.com/RadeonOpenCompute/llvm-project/commit/07441d5b9640dd7549c6472883d7dedfc82d7426)
```
I'll revert it right now.

**Comment by AntonRydahl** [comment]
Thanks a bunch, @shiltian!

**Comment by ronlieb** [comment]
shilei, are you willing to revert this one also ?  it breaks spec accel v1.4 552.pep  
OpenMP][NFC] Split the reduction buffer size into two components

**Comment by shiltian** [comment]
That one has to be reverted by @jdoerfert as I tried but there are way too many conflicts.

**Comment by jdoerfert** [comment]
I'll revert this one.

**Comment by jdoerfert** [comment]
> shilei, are you willing to revert this one also ? it breaks spec accel v1.4 552.pep OpenMP][NFC] Split the reduction buffer size into two components

It also caused problems for OpenMC. I used OpenMC to verify my fix worked. I did not think this patch changed much but I forgot that they used the type for offset calculations, not only for type adjustment. The fix will make sure we properly adjust the layout change everywhere.

**Pull request merged**
