### PR TITLE
Introduce SingleByteCoverage tests (w/yaml2obj)

### PR DESCRIPTION
**Pull request by chapuni**
Restructure some tests to split into `%.test` and Inputs/%.c*`.

Add test actions with `yaml2obj` for single byte coverage. `FileCheck` lines are:
- Relax to accept both counter values and single values `1`. A few line counting are greater than `1` due to `llvm-profdata merge`. They will be fixed by #110972.
- Suppress matching with `--check-prefixes=CHECK,BRCOV`, since the current implementation of single byte doesn't emit any branch coverages. They will be integrated to `CHECK` finally.
- Some tests are not unified but use dedicated `CHECK` lines for single byte, since old format is different (esp. "partial fold"). They will be unified when `Inputs` will be regenerated.

Introduce llvm/test/tools/llvm-cov/Inputs/yaml.makefile for convenience. `%-single.yaml` and `%-single.proftext` are generated by it. It could be used to regenerate other files.

https://discourse.llvm.org/t/rfc-integrating-singlebytecoverage-with-branch-coverage/82492

### CODE REVIEW

**Comment by chapuni** [comment]
I think I could dissolve `single-byte-counters.cpp` to other tests. Let me rework.

**Comment by chapuni** [comment]
Ping. Or would it be too early for adopting yaml2obj?

**Comment by ornata** [comment]
Can you explain why we want to use yaml2obj for testcases in the commit message?

**Review by ornata — APPROVED** [review]
I don't see any problem with this change.

**Comment by chapuni** [comment]
@ornata Thanks. I'll merge this possibly tomorrow unless objections.

**Pull request merged**
