### PR TITLE
[NFC] Add GIntrinsic::setIntrinsicID

### PR DESCRIPTION
**Pull request by jurahul**
Add a function to set the intrinsic ID for GIntrinsic.

### CODE REVIEW

**Comment by tschuett** [comment]
I vote against it. Changing the id of an intrinsic is error prone. Even worse, making it easier to change the id.

**Comment by jurahul** [comment]
Thanks. I did have that question I guess this was a way to ask it. Note
that it is possible today to mutate the intrinsic id, but overall I wanted
to understand if these Generic MIR are safe for mutation or is the
expectation to build a new one for every change?

**Comment by tschuett** [comment]
See:
https://github.com/llvm/llvm-project/blob/81cd7358a2ce411c99512d055e98d0b9dc119c14/llvm/lib/CodeGen/GlobalISel/CombinerHelper.cpp#L1635

If you want  to change properties of an existing instruction, you have to notify observers in GiSel.

**Comment by jurahul** [comment]
> you have to notify observers in GiSel.

But not when erasing and replacing it with a new instruction, I guess? So, the "right" way for replacing one intrinsic with another is to really create a new one, even if rest of the properties are intended to stay the same? It seems that the base `MachineInstr` class supports mutation as well.

**Comment by tschuett** [comment]
It depends on your use-case. In the combiner, we have several ways to mutate or replace instructions. In your file, I believe `dropPoisonGeneratingFlags` is the only method  that modifies instructions. The others are getters and testers.

**Comment by jurahul** [comment]
Makes sense. I was referring to `MachineInstr::removeOperand` for example, which is a public function in the parent class. In my use case (in downstream code) the mutation I want to do is in a MachineFunctionPass, so not sure if the GISel combiner helper is relevant there. I guess in that context, the question is where mutation is ok and allowed. Of course safety if the mutation has to be ensured by the mutator. And if mutation is ok, are such helpers ok as well.

A second related question here, more process wise, is how to make such changes with no upstream users. I am suspecting the answer is we cannot unless the pass using this is also upstream.

**Comment by tschuett** [comment]
You still loose at dead code.

https://github.com/llvm/llvm-project/blob/main/llvm/lib/CodeGen/GlobalISel/LoadStoreOpt.cpp
seems to be really careful to use the builder to create instructions and `eraseFromParent()`  to delete instructions. I couldn't  find mutations.

**Comment by jurahul** [comment]
Make sense. I'll close this.

**Pull request closed without merging**
