### PR TITLE
[clang] MangledSymbol: remove pointless copy of vector

### PR DESCRIPTION
**Pull request by sookach**
This pr addresses #87255 adds a std::move call to the names in MangledSymbol's constructor.

### CODE REVIEW

**Comment by soukatch** [comment]
@dcb314 @shafik @EugeneZelenko Please let me know if this change looks good. Thanks!

**Review by shafik — APPROVED** [review]
LGTM

**Comment by shafik** [comment]
> Looking at the logs, and the error seems to be unrelated to the changes made https://buildkite.com/llvm-project/clang-ci/builds/16430#018f132d-506e-440c-b18b-fed98237def9/54-5446

You can try using `--allow-empty` to do an empty commit to kick off the build again.

**Comment by Endilll** [comment]
@shafik I wonder how checking size of a vector is now considered an expensive check.
(I stumbled upon it while reviewing)
https://github.com/llvm/llvm-project/blob/47682e4b4a0c8e7637d65868a7208aa6806a50f4/clang/lib/Frontend/InterfaceStubFunctionsConsumer.cpp#L99-L101

**Review by Endilll — APPROVED** [review]
Thank you for spotting and fixing this!

**Comment by soukatch** [comment]
@AaronBallman would it be possible to get an approval while all the checks are green? Thanks!

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Comment by soukatch** [comment]
Thank you everyone for the reviews!

**Comment by AaronBallman** [comment]
> Thank you everyone for the reviews!

Thank you for the improvement!

**Pull request merged**
