### PR TITLE
[acc] OpenACC dialect design philosophy and details

### PR DESCRIPTION
**Pull request by razvanlupusoru**
This document captures the design philosophy of the acc dialect. It also shares the rationale behind the design and implementation of various operations - and ties that back to the dialect design goals.

Co-authored-by: Valentin Clement <clementval@gmail.com>
Co-authored-by: Slava Zakharin <szakharin@nvidia.com>

### CODE REVIEW

**Review by clementval — APPROVED** [review]
Looks great! Thanks for putting it together!

**Review by kiranchandramohan — APPROVED** [review]
Thanks @razvanlupusoru @clementval and @vzakhari for writing this. This is very useful reference. We will aim to have something like this in OpenMP next year.

**Comment by agozillon** [comment]
Thank you for writing this, I've not read it just yet as I'm on vacation for a bit and being lazy right now, but I will when I'm back and might have a few questions then! But obviously no need to wait for that to merge, they'll just be questions out of interest!

**Review by vzakhari — APPROVED** [review]
Thank you, Razvan!

**Review by erichkeane — APPROVED** [review]
Full disclosure: I reviewed this extensively before it was published for review, so my comments are already incorporated in this.  

Since I intend our Clang OpenACC implementation to use this dialect, I reviewed this extensively with that in mind, and am confident after working with the authors that this is going to be acceptable/workable (that is flexible enough to work, or be changed to work) for the Clang implementation as well.

**Comment by razvanlupusoru** [comment]
I plan on submitting this soon :) (early next week)

Though I have a few small things to fix - not wording - but making sure the online documentation will be generated correctly. It ends up that two "Operations" sections are generated because of the way the auto-generated dialect documentation file is included. I will revise that before I submit.

**Comment by razvanlupusoru** [comment]
I need to submit a follow-up fix since the website index does not show the new dialect document due to missing header.

**Pull request merged**
