### PR TITLE
[libc] rename newhdrgen to just hdrgen

### LINKED ISSUE #117254: [libc] rename newhdrgen to just hdrgen
Once old hdrgen is deleted (#117208), we should renamed newhdrgen to just hdrgen.  This bug can also help us track other todo/related cleanups from the removal of old hdrgen.

### PR DESCRIPTION
**Pull request by nickdesaulniers**
Link: #117208
Fixes: #117254

### CODE REVIEW

**Review by jhuber6 — APPROVED** [review]

**Review by michaelrj-google — APPROVED** [review]
LGTM, CC @aaryanshukla and @RoseZhang03

**Comment by nickdesaulniers** [comment]
Probably going to sit on this for today to ensure that #117220 sticks. If #117220 has to be reverted, no point landing more  patches on top.

**Comment by nickdesaulniers** [comment]
> Probably going to sit on this for today to ensure that #117220 sticks. If #117220 has to be reverted, no point landing more patches on top.

#118558 as an example

**Review by petrhosek — APPROVED** [review]

**Comment by jhuber6** [comment]
^ Offloading bot being flaky again

**Pull request merged**
