### PR TITLE
[mlir][tosa] Rename Tosa Div op to IntDiv Op

### PR DESCRIPTION
**Pull request by Tai78641**
This patch renames Tosa Div Op to IntDiv Op to align with the TOSA Spec.

- - -
This change is [Reviewable](https://reviewable.io/reviews/llvm/llvm-project/80047)

### CODE REVIEW

**Review by GeorgeARM — COMMENTED** [review]
Looks good to me. This probably breaks users of tosa. Can we merge this or we wait for other updates?

**Review by jpienaar — APPROVED** [review]
You may be able to make it non-breaking with a using statement (I mean not for the generated IR, that would need a sed of course).

> *[Reviewable](https://reviewable.io/reviews/llvm/llvm-project/80047#-:-Ns3bbkR8lyjZta9FjbD:b-v3zbf2)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @Tai78641)

___
*[`mlir/lib/Conversion/TosaToLinalg/TosaToLinalg.cpp` line 95 at r1](https://reviewable.io/reviews/llvm/llvm-project/80047#-Ns3bD4nBZLcfmbuuFTe:-Ns3bD4nBZLcfmbuuFTf:b-u2dg7n) ([raw file](https://github.com/llvm/llvm-project/blob/1513939fcbf02b1b080185e8cdc460348f8516f6/mlir/lib/Conversion/TosaToLinalg/TosaToLinalg.cpp#L95)):*
> ```cpp
> 
>   // tosa::IntDivOp
>   if (isa<tosa::IntDivOp>(op) && elementTy.isa<IntegerType>())
> ```

Prefer the other form (https://mlir.llvm.org/deprecation/)
___
*[`mlir/lib/Dialect/Tosa/IR/TosaOps.cpp` line 1333 at r1](https://reviewable.io/reviews/llvm/llvm-project/80047#-Ns3bM9qBSHKS3qWSX0P:-Ns3bM9qBSHKS3qWSX0Q:b-izakcr) ([raw file](https://github.com/llvm/llvm-project/blob/1513939fcbf02b1b080185e8cdc460348f8516f6/mlir/lib/Dialect/Tosa/IR/TosaOps.cpp#L1333)):*
> ```cpp
> NARY_SHAPE_INFER(tosa::ClampOp)
> NARY_SHAPE_INFER(tosa::ClzOp)
> NARY_SHAPE_INFER(tosa::IntDivOp)
> ```

I think these were sorted, could you keep it such?

**Review by Tai78641 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/llvm/llvm-project/80047)* status: 0 of 10 files reviewed, 2 unresolved discussions (waiting on @jpienaar)

___
*[`mlir/lib/Conversion/TosaToLinalg/TosaToLinalg.cpp` line 95 at r1](https://reviewable.io/reviews/llvm/llvm-project/80047#-Ns3bD4nBZLcfmbuuFTe:-NsjJ6X_7Z-rJPOamlsT:b-896fix) ([raw file](https://github.com/llvm/llvm-project/blob/1513939fcbf02b1b080185e8cdc460348f8516f6/mlir/lib/Conversion/TosaToLinalg/TosaToLinalg.cpp#L95)):*
<details><summary><i>Previously, jpienaar (Jacques Pienaar) wrote…</i></summary><blockquote>

Prefer the other form (https://mlir.llvm.org/deprecation/)
</blockquote></details>

Done.
___
*[`mlir/lib/Dialect/Tosa/IR/TosaOps.cpp` line 1333 at r1](https://reviewable.io/reviews/llvm/llvm-project/80047#-Ns3bM9qBSHKS3qWSX0P:-NsjJ58r8i2hJ6vXFk69:b-896fix) ([raw file](https://github.com/llvm/llvm-project/blob/1513939fcbf02b1b080185e8cdc460348f8516f6/mlir/lib/Dialect/Tosa/IR/TosaOps.cpp#L1333)):*
<details><summary><i>Previously, jpienaar (Jacques Pienaar) wrote…</i></summary><blockquote>

I think these were sorted, could you keep it such?
</blockquote></details>

Done.

**Comment by NatashaKnk** [comment]
Can you please fix the build error? It looks like there is a rename missing in `TosaOps.cpp`

**Comment by Tai78641** [comment]
> Can you please fix the build error? It looks like there is a rename missing in `TosaOps.cpp`

done

**Pull request merged**
