### PR TITLE
[mlir-lsp] Add transport unit tests

### PR DESCRIPTION
**Pull request by modocache**
Stacked pull requests:

- #89857
- #89856
- -> #89855

---

Add unit tests for some aspects of the JSON transport and message
handler. These will be expanded in future patches as behavior is
modified.

### CODE REVIEW

**Review by walter-erquinigo — APPROVED** [review]
lgtm

**Review by River707 — APPROVED** [review]
Thanks for adding some explicit tests for the underlying infra!

**Comment by joker-eph** [comment]
This broke Windows presubmit: https://lab.llvm.org/buildbot/#/builders/271/builds/6920

I'll revert. I suspect the follow-ups will need to be reverted as well

**Comment by joker-eph** [comment]
https://github.com/llvm/llvm-project/commit/6844c2feae93dd42516851057277f6130f1864e1

Feel free to re-land these with a fix, probably best to actually wait for the premerge to complete if  you're unsure about Windows.

**Comment by modocache** [comment]
Gotcha, thanks @joker-eph!

> Didn't you get an email about it?

I did get an email at 7:52PM my time.

> Feel free to re-land these with a fix, probably best to actually wait for the premerge to complete if you're unsure about Windows.

Sorry, I missed the pre-merge failures -- I'm new to contributing via GitHub. I saw the buildkite status was being displayed as "pending" in the web UI, but I thought it was permanently stuck! I now realize I should have asked around to see if it would run -- sorry about that!

I will reland with some changes, and will wait for the pre-merge checks to complete. Sorry for the inconvenience!

**Comment by joker-eph** [comment]
> Sorry, I missed the pre-merge failures -- I haven't contributed since the migration to GitHub. I saw the buildkite status was being displayed as "pending" in the web UI, but I thought it was permanently stuck! I now realize I should have asked around to see if it would run -- sorry about that!

This is fine: you did nothing wrong. The windows pre-merge is often too backed up and most people won't wait for it.
My comment was in the sense: "before re-landing this particular change, if you are not sure you have the right fix for Windows and can't test it locally, it'll probably best to get confirmation from buildkite".

**Comment by modocache** [comment]
Yup, totally understand. Thanks for your patience & the explanation! :)

**Comment by joker-eph** [comment]
My reverts weren't enough :(
Things are still broken here: https://lab.llvm.org/buildbot/#/builders/271 ; do you think you'll have this fix quickly or should I look into reverting more?

**Comment by modocache** [comment]
I like the idea of reverting to get back to a green state and then re-landing slowly with green pre-merge build bots. I can send reverts in the next 20 minutes.

**Comment by joker-eph** [comment]
Can you log in https://lab.llvm.org/buildbot/#/builders/271 (top right, using GitHub login), and use the "force build" button, there should be a checkbox for "clean the build directory" I think.
(my login is broken)

**Comment by modocache** [comment]
Done -- I think this is the link to the request I issued, for reference: https://lab.llvm.org/buildbot/#/buildrequests/12648012

**Pull request merged**
