### PR TITLE
[llvm-readobj][COFF] Add support for version 2 of CHPE metadata

### PR DESCRIPTION
**Pull request by cjacek**

### CODE REVIEW

**Comment by cjacek** [comment]
The change to `chpe_metadata` also affects the check in `COFFObjectFile::initLoadConfigPtr`, which uses `sizeof()`, but it should be fine for v1 as it should have placeholders there anyway, like we do in `lld/test/COFF/Inputs/loadconfig-arm64ec.s`.

**Comment by efriedma-quic** [comment]
If I'm reading the code correctly, actually, it doesn't affect COFFObjectFile::initLoadConfigPtr... because the check there is against `sizeof(CHPEMetadata)`, which is the size of the pointer, not the size of the struct.

**Review by efriedma-quic — APPROVED** [review]
LGTM

The versioning here is a little weird... I thought normally they prefer to store the size of the struct in a field instead.  But if this is how it works, it's fine.

**Comment by cjacek** [comment]
Oh, right, I messed that offset check. I will create a follow-up for that. Thanks!

**Pull request merged**
