### PR TITLE
[X86] Resolve FIXME: Copy kill flag for eflags

### PR DESCRIPTION
**Pull request by AZero13**
We now mark the last eflags usage as kill if the def was also kill.

### CODE REVIEW

**Comment by topperc** [comment]
Can you write an MIR test for this?

**Review by RKSimon — COMMENTED** [review]
Do you think we should we consider altering the findRegisterDefOperandIdx/findRegisterDefOperand argument order and require the TRI pointer to help avoid this in the future?

**Comment by AtariDreams** [comment]
> Do you think we should we consider altering the findRegisterDefOperandIdx/findRegisterDefOperand argument order and require the TRI pointer to help avoid this in the future?

I do think this actually.

**Comment by RKSimon** [comment]
@AtariDreams any luck with adding test coverage?

**Review by RKSimon — CHANGES_REQUESTED** [review]
Still needs test coverage - and the patch title/description needs updating to actually describe what that patch does and is for

**Pull request closed without merging**
