### PR TITLE
Re-add path normalization that was removed in 315561c86778

### PR DESCRIPTION
**Pull request by glandium**

### CODE REVIEW

**Comment by glandium** [comment]
Cc @PiotrZSL @carlosgalvezp @nicovank

**Comment by nicovank** [comment]
Is there a reason to bring it back? Is it causing issues?
IIRC this was on purpose because from `os.path.abspath`:
> On most platforms, this is equivalent to calling the function [normpath()](https://docs.python.org/3/library/os.path.html#os.path.normpath) as follows: normpath(join(os.getcwd(), path)).

**Comment by glandium** [comment]
The change in 315561c86778 causes problems on Windows, and I thought that's what it was, but it turns out it's not. Sorry for the noise. I'm still digging as to what exactly is going wrong on our setup.

**Comment by glandium** [comment]
I found what's going on. It kind of worked by chance before in our setup, but that somehow shows an existing flaw in the run-clang-tidy script.
So, our compilation database contains absolute paths with forward slashes. And the paths we pass to the command line are also with forward slashes.
This worked fine because `make_absolute` had a shortcut that didn't alter the path if it was already absolute. Then `file_name_re` would match properly.
Now that `abspath` is always used, the paths in `files` are all with backslashes (because it's Windows, and path normalization turns the forward slashes into backslashes). But with `args.files` containing paths with forward slashes, `file_name_re` doesn't match anymore.
But passing paths with backslashes in paths also doesn't work (and that's not new to https://github.com/llvm/llvm-project/commit/315561c867784ebd9ca387e94ea6597918e7cc1c), because of how these paths are used verbatim in `file_name_re` without escaping. But that's because what's passed in is regexps, so this makes sense.

**Comment by nicovank** [comment]
I see, thanks for looking into it! To be honest I think `file_name_re` could be removed, `--source-filter` already takes in a regex and filters files based on it, which is more clear. The `files` arguments could just be taken as-is as a list of file paths (or maybe optionally directories to recurse). This sounds like it would fix this case (and it's closer to what the `clang-tidy` executable does) but maybe break others.

What do people think? @5chmidti @PiotrZSL @HerrCai0907 @carlosgalvezp?

**Pull request closed without merging**
