### PR TITLE
[Patchpoint] Add immarg attributes to patchpoint arguments

### PR DESCRIPTION
**Pull request by Il-Capitano**
This fixes an issue where simplifycfg would merge two patchpoints, resulting in a dynamic ID being used, which triggers an assert during code generation.

### CODE REVIEW

**Comment by Il-Capitano** [comment]
@huntergr-arm @fmayer @chapuni Pinging for review.

**Comment by Il-Capitano** [comment]
@huntergr-arm @fmayer @chapuni Ping

**Comment by fmayer** [comment]
Sorry for the delay, I was on a break, I will take a look this week.

**Comment by fmayer** [comment]
It looks fine to me, but why was I added to this? I don't have experience with patchpoint?

**Comment by Il-Capitano** [comment]
@fmayer You must have been on a blame list for some unrelated change in `llvm/include/llvm/IR/Intrinsics.td`. Sorry for the confusion, and thanks for taking the time anyways.

**Comment by Il-Capitano** [comment]
@sanjoy @preames @arsenm Can I ask for review of this PR, or can you add appropriate reviewers? There hasn't been much development on this part of LLVM in the past years, so it's hard to find reviewers, and I think this is a fairly trivial bugfix. Thanks!

**Review by arsenm — APPROVED** [review]
Could use coverage in test/Verifier/intrinsic-immarg.ll

**Comment by Il-Capitano** [comment]
Thanks for the review!

> Could use coverage in test/Verifier/intrinsic-immarg.ll

I added a test case in the latest change.

**Review by arsenm — APPROVED** [review]

**Comment by Il-Capitano** [comment]
Can I ask for this to be merged?

**Pull request merged**
