### PR TITLE
[mlir] Do not set lastToken in AsmParser's resetToken function and add a unit test for AsmParsers's locations

### PR DESCRIPTION
**Pull request by jorickert**
This changes the function `resetToken` to not update `lastToken`.

The member `lastToken` is the last token that was consumed by the parser.
Resetting the lexer position to a different position does not cause any token to be consumed, so `lastToken` should not be updated. 
Setting it to `curToken` can cause the scopeLoc.end location of `OperationDefinition `to be off-by-one, pointing to the
first token after the operation.

An example for an operation for which the scopeLoc.end location was wrong before is:
```
%0 = torch.vtensor.literal(dense_resource<__elided__> : tensor<768xbf16>) : !torch.vtensor<[768],bf16>
```
Here the scope end loc always pointed to the next token

This also adds a test for the Locations of `OperationDefinitions`. Without the change to `resetToken` the test failes, with the scope end location for `llvm.mlir.undef` pointing to the `func.return` in the next line

### CODE REVIEW

**Comment by jorickert** [comment]
@joker-eph @Mogball  Could you please review this or assign a reviewer? I do not have write access, so can not do it myself. Thank you

**Comment by joker-eph** [comment]
LGTM, but since the invariants of the lexer/parser are tricky, this deserves more eyes on it! So let's wait for some of the other reviewers to check this as well.

**Comment by River707** [comment]
With the current usage of resetToken, this change is fine, but it's a little spooky that there is an implicit contract between the last token and resetToken, that could be easily broken if you aren't careful (not that the current behavior is really correct either). This is relying on the various of resetToken to cancel out, i.e. the resetTokens used for parsing attributes/types to technically be correct (because it resets first to the start of the attribute/type, and then to the end). This behavior can be fine, but we should ensure that the connection to lastToken is documented in the doc for resetToken.

**Comment by jorickert** [comment]
I updated the comment to make the relationship between` resetToken` and `state.lastToken`  clearer

**Review by River707 — APPROVED** [review]

**Comment by jorickert** [comment]
It would be nice if someone could merge this, I do not have write access/merge rights. Thank you

**Pull request merged**
