### PR TITLE
AMDGPU: Change bitop3 intrinsic operand to i32

### PR DESCRIPTION
**Pull request by arsenm**

### CODE REVIEW

**Comment by arsenm** [comment]
* **#118648** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/118648?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#118647** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/118647?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/118647?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Comment by shiltian** [comment]
why is so?

**Comment by arsenm** [comment]
> why is so?

This showed up in a merge commit after the original patch was committed. This is what's in the branch. I'm guessing this was to avoid work to fixup the type after 335bc3c0b2df3929511c44a02baa93a2d22b515f

**Review by shiltian — APPROVED** [review]

**Comment by arsenm** [comment]
### Merge activity

* **Dec 4, 3:41 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/118647).

**Pull request merged**
