### PR TITLE
[VP] Mark llvm.experimental.vp.splice as having no functional equivalent

### PR DESCRIPTION
**Pull request by lukel97**
llvm.experimental.vp.splice has different semantics from
llvm.experimental.splice (since it takes uses the EVL arguments in a way other
than just masking the tail elements), so it shouldn't be expanded to the
unpredicated version.

Coincidentally there's no support for llvm.experimental.vp.splice in
ExpandVectorPredication, so it wasn't getting expanded, but we shouldn't mark
it as functionally equivalent anyway since there's other users of the property
now e.g. in VectorCombine.

### CODE REVIEW

**Comment by RKSimon** [comment]
Should we just drop handling for it for now or is it possible to create a test case?

**Comment by lukel97** [comment]
> Should we just drop handling for it for now or is it possible to create a test case?

We don't currently handle it in ExpandVectorPredication.cpp to begin with, but I guess we might in future?
I ran through all the users of `VPIntrinsic::getFunctionalOpcode()`/`VPIntrinsic::getFunctionalIntrinsicID()`/`VPIntrinsic::getConstrainedIntrinsicID()` anyway. Looks like the only users are ExpandVectorPredication.cpp and the `scalarizeVPIntrinsic` combine in VectorCombine.cpp, but the latter only operates on binary ops so it would never have triggered to begin with. So I don't think it's possible to write a failing test case currently.

**Comment by RKSimon** [comment]
So would we be better off removing it until we have an actual use case?

**Comment by lukel97** [comment]
> So would we be better off removing it until we have an actual use case?

By "it" do you mean removing the `VP_PROPERTY_FUNCTIONAL_INTRINSIC` property? Or the actual experimental.vp.splice intrinsic?

**Review by RKSimon — APPROVED** [review]
Thanks for the explanation! LGTM

**Pull request merged**
