### PR TITLE
Revert "[clang] Add nuw attribute to GEPs"

### PR DESCRIPTION
**Pull request by vitalybuka**
Reverts llvm/llvm-project#105496

This patch breaks:
https://lab.llvm.org/buildbot/#/builders/25/builds/1952
https://lab.llvm.org/buildbot/#/builders/52/builds/1775

Somehow output is different with sanitizers.
Maybe non-determinism in the code?

### CODE REVIEW

**Comment by vitalybuka** [comment]
Please let me know if you have a fix for that.
I'll land revert in the morning by PDT.

**Comment by hazzlim** [comment]
> Please let me know if you have a fix for that. I'll land revert in the morning by PDT.

Thank you for flagging this up and opening this @vitalybuka - I'm taking a look now to see if there's an easy enough fix to save reverting.

**Comment by vitalybuka** [comment]
> > Please let me know if you have a fix for that. I'll land revert in the morning by PDT.
> 
> Thank you for flagging this up and opening this @vitalybuka - I'm taking a look now to see if there's an easy enough fix to save reverting.

Thanks. Please merge the revert if you give up on the easy fix.

**Comment by zmodem** [comment]
> > Please let me know if you have a fix for that. I'll land revert in the morning by PDT.
> 
> Thank you for flagging this up and opening this @vitalybuka - I'm taking a look now to see if there's an easy enough fix to save reverting.

No need to save reverting --- reverting faster is better since it takes the pressure off while investigating, and saves more people from hitting this issue.

**Pull request merged**
