### PR TITLE
[libc++] Sync the filesystem clock_gettime handling with chrono for OpenBSD

### PR DESCRIPTION
**Pull request by brad0**
Copy the same OS checks for clock_gettime from chrono to filesystem and
tweak the comment as Hurd is in the same situation.

### CODE REVIEW

**Comment by mordante** [comment]
In general we like to have a CI runner to test platform specific behaviour. Do you intent to add a GNU Hurd runner? (This change is small and innocent, but without CI tests there is no guarantee there won't be regressions.)

Can you make the commit message a bit more descriptive. Something along the lines of
`[libc++] Add GNU Hurd clock_gettime support` seems better describing the goal of the change.

**Review by Ericson2314 — APPROVED** [review]

**Comment by ldionne** [comment]
Gentle ping -- I'll close this as inactive if there is no plan to officially support this platform.

**Comment by brad0** [comment]
> Gentle ping -- I'll close this as inactive if there is no plan to officially support this platform.

I'd like to have official support for the platform. But looking at the current code and support policy this will consistently be an issue for us. Our current Clang / libc++ is 16.

**Comment by Ericson2314** [comment]
@brad0 I'll need to forward-port some patches just to get the bare minimum of simple executables able to run. Maybe that is good enough even if OpenBSD is still officially hanging back on LLVM 16 for a while longer?

OpenBSD is a faster-moving ABI with the security experiments (and I would not want that to change!), but I think it should be possible to have less outsanding patches against upstream without compromising that ABI agility or incurring painful upstreaming drudgery.

**Comment by ldionne** [comment]
What kind of downstream changes do you folks have? We may be able to accommodate some of them or at least make them easier to maintain by introducing a few "extension points" in the library. This is a common situation and we're quite used to finding ways to make it work both for the upstream project and for downstream needs.

**Comment by Ericson2314** [comment]
@ldionne I am learning as I go, and my cross compiled binaries do not yet work :).

First on my docket is that LLD needs some linker script modifications so that special sections like `.openbsd.mutable` and `.openbsd.syscalls` end of being linked correctly.

The change that currently does this just uses `#ifdef __OpenBSD__` but that is not right for cross compilation, so this will need to be fixed up.

To be clear, I haven't seen anything critical in libc++ yet, but I would consider LLD / Clang / LLVM changes blockers insofar is if binaries don't run, then the libc++ testsuite cannot run --- unless you would consider a "does it at least build" smoke test a decent first step.

**Comment by brad0** [comment]
> What kind of downstream changes do you folks have? We may be able to accommodate some of them or at least make them easier to maintain by introducing a few "extension points" in the library. This is a common situation and we're quite used to finding ways to make it work both for the upstream project and for downstream needs.

For libc++. Nothing.

Various local patches for Clang, LLVM and LLD though.

**Comment by ldionne** [comment]
@Ericson2314 @brad0 I think that to begin with, we could start with only compiling the test suite. We could at least see how far we're able to go in that direction. I really want to avoid having "phantom" platforms in the code base (where we have 0 visibility into what's working and what's not working).

**Comment by ldionne** [comment]
I can provide support for adding a new OpenBSD build bot if you want. The documentation for adding a new CI job using BuildKite is here: https://libcxx.llvm.org/AddingNewCIJobs.html#addingnewcijobs

It's also possible to set up a custom Github Actions runner if you prefer that, either way is fine by us.

**Comment by brad0** [comment]
> I can provide support for adding a new OpenBSD build bot if you want. The documentation for adding a new CI job using BuildKite is here: https://libcxx.llvm.org/AddingNewCIJobs.html#addingnewcijobs

There is not a Buildkite binary for OpenBSD. But it built Ok. I'll see about creating a package.

I'll be able to try setting something up around the end of the month.

**Comment by ldionne** [comment]
Ack. Please let me know when/whether I can provide support. I will set up a reminder to ping this at the end of the month.

I would aim to have this done in time for the LLVM 20 release. In terms of process, if we are not able to set this up in time for LLVM 20, I would remove patches that intend to provide support for OpenBSD until we are able to actually provide support for it, to avoid an accumulation of half-supported things in the codebase.

**Comment by ldionne** [comment]
I'll close this for the time being but let's reopen it once we have what we need CI-wise.

**Comment by ldionne** [comment]
Scheduled ping. Any interest for setting up CI? Should I start cleaning up OpenBSD support from the upstream tree?

**Comment by brad0** [comment]
> Scheduled ping. Any interest for setting up CI? Should I start cleaning up OpenBSD support from the upstream tree?

I have the system. I just got the OS installed and it's ready to go.

**Comment by ldionne** [comment]
Can you reach out to me on Discord `@ldionne`, I can help you set up the machine w/ BuildKite tokens and so on.

**Comment by brad0** [comment]
> Can you reach out to me on Discord `@ldionne`, I can help you set up the machine w/ BuildKite tokens and so on.

@ldionne I have. You don't respond.

**Comment by ldionne** [comment]
Sorry, new message requests on Discord end up in a weird place, I missed it but I see it now.

**Pull request closed without merging**
