### PR TITLE
[RISCV][ISel] Fold FSGNJX idioms

### LINKED ISSUE #1072: Grep FSGNJX
```
define float @test(float %x, float %y) {
  %z = call float @llvm.copysign.i32(float 1.0, float %x)
  %mul = fmul float %z, %y
  ret float %mul
}
```
https://alive2.llvm.org/ce/z/epyL33

### PR DESCRIPTION
**Pull request by dtcxzyw**
This patch folds `fmul X, (fcopysign 1.0, Y)` into `fsgnjx X, Y`. This pattern exists in some graphics applications/math libraries.
Alive2: https://alive2.llvm.org/ce/z/epyL33

Since fpimm +1.0 is lowered to a load from constant pool after OpLegalization, I have to introduce a new RISCVISD node FSGNJX and fold this pattern in DAGCombine.

Closes https://github.com/dtcxzyw/llvm-opt-benchmark/issues/1072.

### CODE REVIEW

**Review by wangpc-pp — COMMENTED** [review]
I don't know if there may be an impact, but can you test if this combine works well with Zfa?

**Review by topperc — APPROVED** [review]
LGTM

**Comment by preames** [comment]
Any reason this can't be done by e.g. instcombine?

**Comment by topperc** [comment]
> Any reason this can't be done by e.g. instcombine?

What IR could InstCombine generate?

**Comment by preames** [comment]
> > Any reason this can't be done by e.g. instcombine?
> 
> What IR could InstCombine generate?

We have a llvm.copysign, so wouldn't this just be (copysign X, Y)?  Or is there some corner case here I'm missing?

**Comment by topperc** [comment]
> > > Any reason this can't be done by e.g. instcombine?
> > 
> > 
> > What IR could InstCombine generate?
> 
> We have a llvm.copysign, so wouldn't this just be (copysign X, Y)? Or is there some corner case here I'm missing?

fmul X, (fcopysign 1.0, Y) is multiply X by 1.0 if Y is positive, multiply X by -1.0 if Y is negative. This has the effect of toggling X's sign bit if Y is negative. So its not a copy.

**Pull request merged**
