### PR TITLE
[MLIR][Vector][NFC] Move helper functions to vector distribution utils

### PR DESCRIPTION
**Pull request by kurapov-peter**
The first portion of https://github.com/llvm/llvm-project/pull/112945.

### CODE REVIEW

**Review by MaheshRavishankar — DISMISSED** [review]
I understand what you are trying to do, but this all screaming for an interface where the distribution could be implemented on operations that aren't vector type.

**Comment by kurapov-peter** [comment]
> I understand what you are trying to do, but this all screaming for an interface where the distribution could be implemented on operations that aren't vector type.

This change has nothing to do with interfaces, why are you blocking it?

**Review by rengolin — APPROVED** [review]
Even if an interface would be a nice idea, it would need users to make sure we're designing it right. This patch is an NFC movement that may help us get there, but let's not put the cart in front of the horses.

**Review by MaheshRavishankar — COMMENTED** [review]
It seems like this is just taking internal implementation details of an op and arbitrarily exposing it.

But, I dont really have a stake in this. I am going to unblock this.

**Comment by kurapov-peter** [comment]
Done in https://github.com/llvm/llvm-project/pull/119264

**Pull request closed without merging**
