### PR TITLE
Revert "[libc++] Allow the use of extensions in the implementation (#79532)"

### PR DESCRIPTION
**Pull request by sam-mccall**
This reverts commit 4d323e404d43526ad8263769f00aace9db2e57c5.

The heavy use of push/pop directives causes a severe compile-time
regression (>50%) when building code that uses libc++ via modules.

See discussion on https://github.com/llvm/llvm-project/pull/79532

### CODE REVIEW

**Comment by sam-mccall** [comment]
#79532 has details on the regression.

It seems there are other ways to allow extensions broadly without using push/pop everywhere. But there hasn't been any movement there so far, and this is a large enough compile performance regression that we can't ship libc++.

Contra https://github.com/llvm/llvm-project/pull/79532#issuecomment-1997572838, a clean revert seems to pass tests, so I don't think this is heavily used yet.
So I'd like to revert this until it's clear what the best way to enable this is.

**Comment by sam-mccall** [comment]
Fixed a failure that showed up presubmit: "pair" is using explicit(bool) and needs a suppression similar to the one in tuple. So this is no longer a pure revert. (not sure why I didn't see this locally).

**Comment by ldionne** [comment]
I would support the revert until we understand the issue better and how to fix it. 50% regression is... very serious. Especially given all the efforts we do to reduce compile times by a few percentage points.

I'll let Nikolas have a look but that's my opinion.

**Comment by ldionne** [comment]
I see other solutions being mentioned in #79532 though, should we be exploring those instead?

**Comment by frederick-vs-ja** [comment]
When building modules, it shouldn't be needed to suppress warning on C++14/17/20 features, right?

I'd expect that C++23 features is rarely used as extensions (or not yet used), so we might be able to suppress the warnings more locally.

**Comment by sam-mccall** [comment]
Thanks!

> I see other solutions being mentioned in #79532 though, should we be exploring those instead?

It seems like there are several options with tradeoffs, and I don't feel informed enough to push for one of them. If someone closer to the project can make the call then absolutely.

If there's still some discussion to be had, I'd be grateful if we could revert back to a good state first.
(We consume libc++ close to head, so we'll have to start carrying a downstream patch for this soon, which is no fun).

@frederick-vs-ja 
> When building modules, it shouldn't be needed to suppress warnings on C++14/17/20 features, right?

Mostly. (You can use Clang modules without C++20, but I think the relatively-few who did that are on C++20 now anyway). You could reduce the suppression pragmas this way (could gate on language version rather than modules-enabled?). But it also feels like a short-term fix to what may simply be the wrong mechanism.

**Comment by mordante** [comment]
I would also support a revert until we can found out what caused the regression.

@sam-mccall what modules are you talking about Clang modules or C++20 modules?

**Comment by philnik777** [comment]
#85917 is an (IMO simpler) alternative to work around this problem.

**Comment by sam-mccall** [comment]
> @sam-mccall what modules are you talking about Clang modules or C++20 modules?

Our deployment is Clang modules (which would also count as C++20 header units IIUC). My reading of the code is that diagnostic mappings take the same codepath in both cases. I don't have a large-scale C++20 modules codebase with libc++ set up as named modules to test on. 

> #85917 is an (IMO simpler) alternative to work around this problem.

I'm happy if that lands instead, that will also fix our compile time :-) It is important that it should fire when clang modules are on and c++20 modules are off (which `__has_feature(modules)` indeed does).

(Personally I find this solution a bit iffy: we've added a bunch of load onto a compiler subsystem, and immediately found circumstances where that causes problems - it seems more robust to remove the load than to patch around those circumstances. But that's a concern for owners - this will solve my immediate problem)

**Comment by mordante** [comment]
> > @sam-mccall what modules are you talking about Clang modules or C++20 modules?
> 
> Our deployment is Clang modules (which would also count as C++20 header units IIUC). My reading of the code is that diagnostic mappings take the same codepath in both cases. I don't have a large-scale C++20 modules codebase with libc++ set up as named modules to test on.

Thanks! I was just confused whether this is related to Clang or C++ modules.

**Comment by ldionne** [comment]
> 
> (Personally I find this solution a bit iffy: we've added a bunch of load onto a compiler subsystem, and immediately found circumstances where that causes problems - it seems more robust to remove the load than to patch around those circumstances. But that's a concern for owners - this will solve my immediate problem)

At the same time, we do want the ability to use extensions in the code base, which this revert prevents.

**Comment by philnik777** [comment]
Closing this, since #85917 has landed.

**Pull request closed without merging**
