### PR TITLE
[libc++] LWG3870: Remove `voidify`

### LINKED ISSUE #105119: LWG3870: Remove `voidify`
**Link:** https://wg21.link/LWG3870

### PR DESCRIPTION
**Pull request by frederick-vs-ja**
Instead of changing the cast sequence to implicit conversion in _`voidify`_, I think it is better to totally remove `__voidify` and use `static_cast` to `void*`, which has equivalent effects.

Test coverage for const iterators are removed.

Now most affected algorithms are underconstrained, for which I submitted [LWG3888](https://cplusplus.github.io/LWG/issue3888). I'm not sure whether we should speculatively implement it at this moment, and thus haven't added any `*.verify.cpp`.

In some control block types and `optional`, the stored objects are changed to have cv-unqualified type.

Fixes #105119.

### CODE REVIEW

**Review by ldionne — APPROVED** [review]

**Comment by augusto2112** [comment]
Hi @frederick-vs-ja, looks like this broke an LLDB test (TestDataFormatterGenericOptional.py) https://green.lab.llvm.org/job/llvm.org/view/LLDB/job/as-lldb-cmake/12593/

**Comment by Michael137** [comment]
Looks like it wasnt caught by pre-merge CI because it isnt part of the `check-lldb-api-functionalities-data-formatter-data-formatter-stl-libcxx` target :( 

@ldionne could we add a couple more targets to the list?
* `check-lldb-api-functionalities-data-formatter-data-formatter-stl-generic`
* `check-lldb-api-functionalities-data-formatter-data-formatter-stl-libcxx-simulators`
* `check-lldb-api-commands-expression-import-std-module`
* `check-lldb-api-lang-cpp-std-function-step-into-callable`
* `check-lldb-api-lang-cpp-std-function-recognizer`
* `check-lldb-api-lang-cpp-std-invoke-recognizer`

It's unfortunate that the last couple are spread across targets like this..

**Comment by ldionne** [comment]
@Michael137 That's not a problem. Do you need a revert in the meantime to fix LLDB?

**Comment by ldionne** [comment]
Ack. Feel free to revert if you need more time. If you do that, you will run into a merge conflict with my modulemap patch (since it touched everything), but please don't revert that one. The conflict should be easy to get through by re-adding the `__memory/voidify.h` entry from the modulemap.

**Comment by Michael137** [comment]
Hmm yea this is a bit stranger than expected. For some reason the order of how we print the optionals in the failing test affects the output. I'll have to defer to tomorrow. So reverting for now

**Comment by Michael137** [comment]
This template alias workaround is partly to blame:
```
commit bee8860525acbfe33f5b32870ad5e13de07fa6ff                                                
Author: Michael Buch <michaelbuch12@gmail.com>                                                 
Date:   Sat Jan 21 02:07:24 2023 +0000                                                         
                                                                                               
    [clang][DebugInfo] Don't canonicalize names in template argument list for alias templates  
                                                                                               
    **Summary**                                                                                
                                                                                               
    This patch customizes the `CGDebugInfo` printing policy to stop canonicalizing             
    the template arugment list in `DW_AT_name` for alias templates. The motivation for         
    this is that we want to be able to use the `TypePrinter`s support for                      
    omitting defaulted template arguments when emitting `DW_AT_name`.                          
                                                                                               
    For reference, GCC currently completely omits the template arguments                       
    when emitting alias template DIEs.                                                         
                                                                                               
    **Testing**                                                                                
                                                                                               
    * Added unit-test                                                                          
                                                                                               
    Differential Revision: https://reviews.llvm.org/D142268                                    
```

**Comment by Michael137** [comment]
If it turns out we can't do this in the formatters, I think the best course of action to unblock this is as follows:
1. Revert https://reviews.llvm.org/D142268 (which means we emit canonical typenames into `DW_AT_name` for template aliases again). It's a nice-to-have for LLDB but is really just a workaround, and also causes the bug in the formatters, uncovered by this PR.
2. Reland this libc++ PR
3. Fix the problem in (1) by either implementing `DW_TAG_template_alias` support in LLDB and flipping the `-gtemplate-alias` default to `true` (the `DW_AT_default_value` on the template parameters should allow us to suppress the default arguments then)

**Comment by ldionne** [comment]
@Michael137 I'm fine with any way of resolving this from the LLDB side, I'd just like to avoid blocking this PR for too long on something not actionable from libc++. Just let us know when we can try landing this again!

**Comment by Michael137** [comment]
@ldionne https://github.com/llvm/llvm-project/pull/110767 should unblock this with the least amount of fallout.

**Comment by Michael137** [comment]
https://github.com/llvm/llvm-project/pull/110767 was merged. Feel free to reland this now

**Comment by ldionne** [comment]
@frederick-vs-ja Can you re-open a PR? The CI will re-run just so we can validate that everything works.

**Comment by frederick-vs-ja** [comment]
> @frederick-vs-ja Can you re-open a PR? The CI will re-run just so we can validate that everything works.

Yeah. New PR opened now.

**Pull request merged**
