### PR TITLE
[Clang][Driver] Expose `-fno-eliminate-unused-debug-types` to clang-cl

### LINKED ISSUE #46924: [Codeview] Missing debug info for constant globals that are not used by code
|  |  |
| --- | --- |
| Bugzilla Link | [47580](https://llvm.org/bz47580) |
| Version | trunk |
| OS | Windows NT |
| CC | @amykhuang,@adrian-prantl,@dwblaikie,@JDevlieghere,@walkerkd,@pogo59,@rnk |

## Extended Description 
Here is a test case covering several cases of the same issue:

//------------------------------------------------------------
// main.cpp
//
//------------------------------------------------------------
struct A {
  static const int const_A = 3;
  static constexpr int constexpr_A = 4;
  static constexpr const int constexprconst_A = 5;
  static const int constOutside_A;
};
const int A::constOutside_A = 6;

static const int globalStaticConst = 10;
static constexpr int globalStaticConstexpr = 11;
const int globalConst = 12;
constexpr int globalConstexpr = 13;

int main() {
  A a;
  return 0;
}
//------------------------------------------------------------

Compiling with clang-cl.exe:

clang-cl.exe main.cpp /nologo /EHsc- /Z7 /std:c++17 /GS- /GR- /c /Fo:main-clangcl.obj 
lld-link.exe /DEBUG main-clangcl.obj

Compiling with Microsoft's cl.exe:

cl.exe main.cpp /nologo /EHsc- /Z7 /std:c++17 /GS- /GR- /c /Fo:main-msvc.obj
main.cpp
lld-link.exe /DEBUG main-msvc.obj

In Visual Studio 2019 debugger, trying to display those values (through the Watch Window):

1) main-MSVC.exe
 -> "A" : symbol exists, can expand to display members with their value
 -> "globalStaticConst" etc: displayed with value

2) main-clangcl.exe
 "A" symbols exists, can expand to display members, but the values are replaced with an error message "An unspecified error has occurred", except for constexprconst_A (which was evaluated in main()) and constOutside_A.

Note that the behavior is the same when compiling with clang argument `-fno-limit-debug-info`.

Comparing the output of `llvm-pdbutil dump --symbols` on both obj files, we can see a few S_CONSTANT entries that appear on msvc but not clangcl:

                          Symbols                           
============================================================
  Mod 0000 | `.debug$S`: 
 (...)
0 | S_CONSTANT [size = 21] `B::const_B`
    type = 0x1003 (const int), value = 3
0 | S_CONSTANT [size = 25] `B::constexpr_B`
    type = 0x1003 (const int), value = 4
0 | S_CONSTANT [size = 30] `B::constexprconst_B`
    type = 0x1003 (const int), value = 5
 etc
 

It would be nice to have these values shown when debugging.

If I understand correctly, the goal is to have the informations about those constants ready at CodeViewDebug::endModule(), so that they can be emitted in CodeViewDebug::emitDebugInfoForGlobals(). 

@&#8203;rnk, would you know where to gather those symbols information?

### PR DESCRIPTION
**Pull request by aganea**
This is used to set DebugInfoKind to "UnusedTypeInfo". This helps in the context of  Unreal Engine and NATVIS files that reference unused otherwise `static constexpr` class members. See https://udn.unrealengine.com/s/question/0D5QP00000N012h0AB/fname-debug-visualizer-fails-to-work-with-the-clang-compiler

This partially fixes https://github.com/llvm/llvm-project/issues/46924

### CODE REVIEW

**Review by amykhuang — APPROVED** [review]
Looks reasonable to me.

**Comment by aganea** [comment]
Thanks @amykhuang for taking a look!

I won't close https://github.com/llvm/llvm-project/issues/46924 right away, since we also need https://reviews.llvm.org/D89286. Do you mind if I took ownership of that patch and send a PR crediting you?

**Comment by amykhuang** [comment]
Yes, feel free to take over that part, thanks!

**Comment by aganea** [comment]
> Yes, feel free to take over that part, thanks!

@amykhuang : I took a look at https://reviews.llvm.org/D89286. It works but doesn't fix the most problematic case where the `constexpr` member needs an evaluation that relies on dependent values:
```
    template <int VAL>
    struct C {
        static constexpr int constexprVal_C = VAL;
    };
    C<200> globalC;
```
I've tried your suggestion, that is forcing evaluation of `constexpr` members upon instantiation:

> Actually, can we just instantiate the initializer for static constexpr data members?
> 
> currently [it delays creating the initializer for inline static data members](https://github.com/llvm/llvm-project/blob/683b308c07bf827255fe1403056413f790e03729/clang/lib/Sema/SemaTemplateInstantiateDecl.cpp#L5062); can we not do that if it's a constexpr?

While this works for the above example, it fails a few tests in Clang, like [this one](https://github.com/llvm/llvm-project/blob/main/clang/test/CXX/expr/expr.const/p6.cpp). It might be because the constexpr expressions are only supposed to be evaluated when used. I'm not sure what a good way forward would be if we wanted to fix this. @zygoloid (note: this is only to generate constants in the debug info).

Overall this is a minor issue and I've fixed it by switching to a plain `const`. The root issue is that we have .NATVIS files that are referencing these otherwise unused members. If we wanted to do things the right way, perhaps NATVIS merged into the PDB would need to be evaluated at compile time, but that sounds like a lot of work. Also, NATVIS come too late in the process, at link time. Hopefully, Visual Studio has a debug mode where failed NATVIS evaluations are shown in the debug output, so they are easy to spot.

**Comment by dwblaikie** [comment]
Yes, the initializers do have to be lazyily evaluated to be a conforming C++ compiler.

eg: this code must compile without error so far as I understand:
```
template<int Value>
struct t1 {
  static constexpr int x = 3 / Value;
};
t1<0> v1;
```
Though it seems MSVC doesn't implement this correctly? https://godbolt.org/z/c1f6xKn3T

One way I've seen someone force the instantiation of the variable definition, and thus get the constant emitted into the DWARF, is using a static_assert:
```
template<int Value>
struct t1 {
  static constexpr int x = 3 / Value;
  static_assert(x, true);
};
t1<1> v1;
```
(of course, in this case, `t1<0>` can no longer be instantiated)

**Comment by dwblaikie** [comment]
I will say, `-fno-eliminate-unused-debug-types` is a really heavy hammer that makes debug info much larger - and my understanding was that games tended to have trouble with large debug builds, so I'd be surprised if this was a great path forward.

Do you have a small example of where Clang and MSVC differ in emitting some particular unreferenced type? I would imagine MSVC isn't emitting /every/ written type...

**Comment by aganea** [comment]
> I will say, `-fno-eliminate-unused-debug-types` is a really heavy hammer that makes debug info much larger - and my understanding was that games tended to have trouble with large debug builds, so I'd be surprised if this was a great path forward.

Absolutely, this is only a short term hack until I figure out a better way to fix it.

> Do you have a small example of where Clang and MSVC differ in emitting some particular unreferenced type? I would imagine MSVC isn't emitting /every/ written type...

It's essentially the examples in https://github.com/llvm/llvm-project/issues/46924. A class that is only used to hold some const/constexpr values. These values are then used by the .NATVIS file. With `/Z7`, MSVC seems to always emit them as `S_CONSTANT`s. But in Clang since the type isn't used, it is never emitted by `CGDebugInfo::EmitAndRetainType()`. Setting `DebugInfo == llvm::codegenoptions::UnusedTypeInfo` fixes the problem. Is there a better way?

**Comment by dwblaikie** [comment]
> > I will say, `-fno-eliminate-unused-debug-types` is a really heavy hammer that makes debug info much larger - and my understanding was that games tended to have trouble with large debug builds, so I'd be surprised if this was a great path forward.
> 
> Absolutely, this is only a short term hack until I figure out a better way to fix it.
> 
> > Do you have a small example of where Clang and MSVC differ in emitting some particular unreferenced type? I would imagine MSVC isn't emitting /every/ written type...
> 
> It's essentially the examples in #46924. A class that is only used to hold some const/constexpr values. These values are then used by the .NATVIS file. With `/Z7`, MSVC seems to always emit them as `S_CONSTANT`s. But in Clang since the type isn't used, it is never emitted by `CGDebugInfo::EmitAndRetainType()`. Setting `DebugInfo == llvm::codegenoptions::UnusedTypeInfo` fixes the problem. Is there a better way?

Ah, I'll take up the discussion on the issue, I think - thanks for pointing that out.

**Pull request merged**
