### PR TITLE
[mlir][irdl] update documentation

### LINKED ISSUE #103300: [mlir][irdl] documentation is outdated
This documentation page https://mlir.llvm.org/docs/Dialects/IRDL/ has an example at the very beginning which seems to use outdated syntax. For example, it uses `irdl.is_type` but that op was replaced with `irdl.is` (https://mlir.llvm.org/docs/Dialects/IRDL/#irdlis-irdlisop).

EDIT: In fact, many of the code examples on that page are outdated and will not compile. Proper syntax for referencing other types defined in the IRDL is `@cmath::@complex` but the examples just use `@complex` which results in errors like the following from `mlir-opt`:
```
/cmath.irdl.mlir:15:12: error: 'irdl.parametric' op symbol '@complex' not found
      %1 = irdl.parametric @complex<%0>
           ^
/cmath.irdl.mlir:15:12: note: see current operation: %1 = "irdl.parametric"(%0) <{base_type = @complex}> : (!irdl.attribute) -> !irdl.attribute
```

### PR DESCRIPTION
**Pull request by tim-hoffman**
fixes #103300

### CODE REVIEW

**Review by math-fehr — APPROVED** [review]
Thanks a lot for updating this!!

**Comment by CoTinker** [comment]
Hi, is this PR ready to merge?

**Comment by math-fehr** [comment]
Hi, very sorry, I thought I merged it already!

**Comment by math-fehr** [comment]
Thanks for pinging!

**Pull request merged**
