### PR TITLE
AMDGPU: Default to selecting frame indexes to SGPRs

### PR DESCRIPTION
**Pull request by arsenm**
Only select to a VGPR if it's trivally used in VGPR only contexts.
This fixes mishandling frame indexes used in SGPR only contexts,
like inline assembly constraints.

This is suboptimal in the common case where the frame index
is transitively used by only VALU ops. We make up for this by later
folding the copy to VALU plus scalar op in SIFoldOperands.

### CODE REVIEW

**Comment by arsenm** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/115060?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#115060** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/115060?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#115059** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/115059?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#115058** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/115058?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by rampitec — APPROVED** [review]

**Comment by arsenm** [comment]
### Merge activity

* **Nov 8, 9:59 PM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/115060).

**Comment by jplehr** [comment]
Hi, our libc on GPU bot is red since this change landed: https://lab.llvm.org/buildbot/#/builders/73/builds/8292

**Comment by mikaelholmen** [comment]
Hi @arsenm 

Running the testcase local-stack-alloc-block-sp-reference.ll with verifiers on with this patch like
```
llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx906 < test/CodeGen/AMDGPU/local-stack-alloc-block-sp-reference.ll -verify-machineinstrs
```
fails with
```
# After Prologue/Epilogue Insertion & Frame Finalization
# Machine code for function func_local_stack_offset_uses_sp: NoPHIs, TracksLiveness, NoVRegs, TiedOpsRewritten, TracksDebugUserValues
Frame Objects:
  fi#0: size=4, align=8192, at location [SP+8192]
  fi#1: size=8480, align=4096, at location [SP+12288]
  fi#2: size=4, align=4, at location [SP]
Function Live Ins: $vgpr0, $vgpr1

bb.0.entry:
  successors: %bb.1(0x80000000); %bb.1(100.00%)
  liveins: $sgpr5, $vgpr0, $vgpr1
  $sgpr5 = frame-setup COPY $sgpr33
  $sgpr33 = frame-setup S_ADD_I32 $sgpr32, 524224, implicit-def $scc
  $sgpr33 = frame-setup S_AND_B32 killed $sgpr33, 4294443008, implicit-def dead $scc
  $sgpr32 = frame-setup S_ADD_I32 $sgpr32, 2097152, implicit-def dead $scc
  renamable $vgpr3 = V_LSHRREV_B32_e64 6, $sgpr33, implicit $exec
  renamable $vgpr2 = V_ADD_U32_e64 12352, killed $vgpr3, 0, implicit $exec
  renamable $vgpr3 = V_MOV_B32_e32 0, implicit $exec
  $vgpr4 = V_MOV_B32_e32 8192, implicit $exec
  BUFFER_STORE_DWORD_OFFEN renamable $vgpr3, killed $vgpr4, $sgpr0_sgpr1_sgpr2_sgpr3, $sgpr33, 0, 0, 0, implicit $exec :: (volatile store (s32) into %ir.pin.low, align 8192, addrspace 5)
  renamable $sgpr4 = S_MOV_B32 0

bb.1.loadstoreloop:
; predecessors: %bb.0, %bb.1
  successors: %bb.2(0x04000000), %bb.1(0x7c000000); %bb.2(3.12%), %bb.1(96.88%)
  liveins: $sgpr4, $sgpr5, $vgpr2, $vgpr3, $vgpr0_vgpr1:0x000000000000000F
  renamable $vgpr5 = V_LSHRREV_B32_e64 6, $sgpr33, implicit $exec
  renamable $vgpr4 = V_ADD_U32_e64 $sgpr4, killed $vgpr5, 0, implicit $exec
  $vgpr5 = V_MOV_B32_e32 12288, implicit $exec
  renamable $vgpr4 = V_ADD_U32_e64 killed $vgpr5, killed $vgpr4, 0, implicit $exec
  renamable $sgpr4 = S_ADD_I32 killed renamable $sgpr4, 1, implicit-def dead $scc
  S_CMPK_LT_U32 renamable $sgpr4, 8480, implicit-def $scc
  BUFFER_STORE_BYTE_OFFEN renamable $vgpr3, killed renamable $vgpr4, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (volatile store (s8) into %ir.1, addrspace 5)
  S_CBRANCH_SCC1 %bb.1, implicit killed $scc
  S_BRANCH %bb.2

bb.2.split:
; predecessors: %bb.1
  liveins: $sgpr5, $vgpr2, $vgpr0_vgpr1:0x000000000000000F
  renamable $vgpr4 = V_LSHRREV_B32_e64 6, $sgpr33, implicit $exec
  renamable $vgpr3 = V_ADD_U32_e32 20688, killed $vgpr4, implicit $exec
  renamable $vgpr4 = BUFFER_LOAD_DWORD_OFFEN renamable $vgpr3, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (volatile dereferenceable load (s32) from %ir.gep.large.offset, align 16, addrspace 5)
  renamable $vgpr5 = BUFFER_LOAD_DWORD_OFFEN renamable $vgpr3, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 4, 0, 0, implicit $exec :: (volatile dereferenceable load (s32) from %ir.gep.large.offset + 4, basealign 16, addrspace 5)
  renamable $vgpr6 = BUFFER_LOAD_DWORD_OFFEN renamable $vgpr2, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 0, 0, 0, implicit $exec :: (volatile dereferenceable load (s32) from %ir.gep.small.offset, align 64, addrspace 5)
  renamable $vgpr7 = BUFFER_LOAD_DWORD_OFFEN renamable $vgpr2, $sgpr0_sgpr1_sgpr2_sgpr3, 0, 4, 0, 0, implicit $exec :: (volatile dereferenceable load (s32) from %ir.gep.small.offset + 4, basealign 64, addrspace 5)
  KILL killed renamable $vgpr2
  KILL killed renamable $vgpr3
  renamable $vgpr2, renamable $vcc = V_ADD_CO_U32_e64 killed $vgpr4, killed $vgpr6, 0, implicit $exec
  renamable $vgpr3, dead renamable $vcc = V_ADDC_U32_e64 killed $vgpr5, killed $vgpr7, killed $vcc, 0, implicit $exec
  GLOBAL_STORE_DWORDX2 killed renamable $vgpr0_vgpr1, killed renamable $vgpr2_vgpr3, 0, 0, implicit $exec :: (volatile store (s64) into %ir.out, addrspace 1)
  $sgpr32 = frame-destroy S_ADD_I32 $sgpr32, -2097152, implicit-def dead $scc
  $sgpr33 = frame-destroy COPY $sgpr5
  SI_RETURN

# End machine code for function func_local_stack_offset_uses_sp.

*** Bad machine code: VOP3 instruction uses literal ***
- function:    func_local_stack_offset_uses_sp
- basic block: %bb.0 entry (0x557d8286b118)
- instruction: renamable $vgpr2 = V_ADD_U32_e64 12352, killed $vgpr3, 0, implicit $exec
LLVM ERROR: Found 1 machine code errors.
```

**Comment by bcahoon** [comment]
Hi @arsenm, can you take a look at the following case. It still fails with [#115747](https://github.com/llvm/llvm-project/pull/115747). Thanks.

```
%"struct.ck::Tuple.1296.524.974.1094.1109.1114.1144.1159.1174" = type { %"struct.ck::detail::TupleImpl.1297.523.973.1093.1108.1113.1143.1158.1173" }
%"struct.ck::detail::TupleImpl.1297.523.973.1093.1108.1113.1143.1158.1173" = type { %"struct.ck::detail::TupleElementKeyData.241.522.972.1092.1107.1112.1142.1157.1172" }
%"struct.ck::detail::TupleElementKeyData.241.522.972.1092.1107.1112.1142.1157.1172" = type { %"struct.ck::vector_type.7.521.971.1091.1106.1111.1141.1156.1171" }
%"struct.ck::vector_type.7.521.971.1091.1106.1111.1141.1156.1171" = type { %union.anon.8.520.970.1090.1105.1110.1140.1155.1170 }
%union.anon.8.520.970.1090.1105.1110.1140.1155.1170 = type { <4 x float> }

define amdgpu_kernel void @test() {
entry:
  %src_vectors.i1.i.i.i.i.i.i.i.i = alloca %"struct.ck::Tuple.1296.524.974.1094.1109.1114.1144.1159.1174", i32 0, align 16, addrspace(5)
  %src_vectors.ascast.i3.i.i.i.i.i.i.i.i = addrspacecast ptr addrspace(5) %src_vectors.i1.i.i.i.i.i.i.i.i to ptr
  %add.ptr.i.i.i.i.i.i.i.i.i.i.i.i12.i.i.i.i.i.i.i.i = getelementptr i8, ptr %src_vectors.ascast.i3.i.i.i.i.i.i.i.i, i64 4
  %vtable.i.i.i.i2.i.i.i15.i.i.i.i.i.i.i.i = load ptr addrspace(1), ptr null, align 8
  %0 = load ptr addrspace(1), ptr addrspace(1) %vtable.i.i.i.i2.i.i.i15.i.i.i.i.i.i.i.i, align 8
  call addrspace(1) void %0(ptr null, ptr null, ptr %add.ptr.i.i.i.i.i.i.i.i.i.i.i.i12.i.i.i.i.i.i.i.i)
  ret void
}
```
```
  llc -mtriple=amdgcn-amd-amdhsa -mcpu=gfx90a test.ll -o test.s 
```

**Comment by arsenm** [comment]
> Hi @arsenm, can you take a look at the following case. It still fails with [#115747](https://github.com/llvm/llvm-project/pull/115747). Thanks.

This one is #115977

**Pull request merged**
