### PR TITLE
[mlir][cmake] Enable -Wundef.

### PR DESCRIPTION
**Pull request by ingomueller-net**
This is another follow-up of #83004, which fixed a bug due to some macros not being defined in some situations. By raising warnings on undefined macros, this kind of bug is less likely to be introduced. Similar to #83004, the fix is probably adding an include to `mlir-config.h` (and potentially defining the macro there).

### CODE REVIEW

**Comment by ingomueller-net** [comment]
After this and all related PRs have landed and the dust has settled, we may consider turning this into `-Werror=undef`.

Also note that this seems more challenging to do for the Bazel builds because some of the macros are not defined in [its version of `mlir-config.h`](https://github.com/llvm/llvm-project/blob/main/utils/bazel/llvm-project-overlay/llvm/include/llvm/Config/llvm-config.h) and quite some machinery seems to be missing to change that.

**Comment by ingomueller-net** [comment]
The only new undefined macro [coming up in CI](https://buildkite.com/llvm-project/github-pull-requests/builds/44262#018e0ebc-6972-48a4-97ee-204509bec331) is `GTEST_NO_LLVM_SUPPORT`. I think it is unset for all LLVM except `compiler-rt`, so maybe we can add a compile definition for either the `mlir` or the `mlir/unittest` folder (or even all of LLVM?)

**Review by joker-eph — APPROVED** [review]
Awesome :)

I had a work-in-progress to do this in LLVM itself, but let's start with MLIR indeed! :)

Can you add some documentation in mlir-config.h that describe that we want cmakedefine01 because we're relying on Wundef for finding missing includes?

**Comment by ingomueller-net** [comment]
Yeah, good point! Fixed with latest commit.

I'll merge when CI has passed but do let me know in case you aren't happy with the text I added; I can still change it.

**Comment by joker-eph** [comment]
Looks great, thanks!

**Comment by PeimingLiu** [comment]
Seems that the change exposes 'GTEST_NO_LLVM_SUPPORT' is not defined, evaluates to 0, any idea how to fix that?

**Comment by PeimingLiu** [comment]
I have a tentative fix in https://github.com/llvm/llvm-project/pull/84539, but I am not sure whether I am doing the right thing or not

**Comment by joker-eph** [comment]
I'm puzzled why this does not fail consistently though?

**Comment by PeimingLiu** [comment]
> I'm puzzled why this does not fail consistently though?

Well, the warning is being consistently reported in https://lab.llvm.org/buildbot/#/builders/61/builds/55414

**Pull request merged**
