### PR TITLE
[BOLT][NFC] Add documentation on BOLT options

### PR DESCRIPTION
**Pull request by ElvinaYakubova**
Add .md file documentation with all BOLT options to display it more conveniently.

### CODE REVIEW

**Review by maksfb — COMMENTED** [review]
Great! Thank you. Is there a plan on synchronizing this document with new options or modifications to existing options?

**Comment by sjoerdmeijer** [comment]
> Great! Thank you. Is there a plan on synchronizing this document with new options or modifications to existing options?

My 2 cents as a BOLT user (i.e. not a developer): 
if they are user-facing options, that would be good, yes. 

I don't know if BOLT has a distinction between user-facing options, hidden/developer options, and/or debugging/printing options. Perhaps not all of these options need to be documented, or maybe separately. 

But I would very much welcome any attempt to add some documentation for user-facing options. For example, I was interested in trying to reduce the binary size, and I already forgot which option it was, but I believe the --lite option might help. My point: any documentation is very much welcome IMHO. I understand I can just look at the source, but that's not for all users and this is much more convenient.

**Comment by maksfb** [comment]
@sjoerdmeijer Appreciate your feedback. Sometimes we forget how much external users we have. Regardless of the sync issue, @ElvinaYakubova 's documentation is a welcome addition.

**Review by maksfb — APPROVED** [review]

**Comment by ElvinaYakubova** [comment]
@sjoerdmeijer Thanks! For now, I've moved printing options to a separate section, but I'll think about how to improve it further.

**Comment by ElvinaYakubova** [comment]
> Great! Thank you. Is there a plan on synchronizing this document with new options or modifications to existing options?

Synchronization sounds like a good next step, I think I'll work on a script to automate the process

**Pull request merged**
