### PR TITLE
Revert "[GlobalISel] Add support for lowering byref attribute"

### PR DESCRIPTION
**Pull request by tschuett**
Reverts llvm/llvm-project#96733

The PR had no tests despite being asked for them.

### CODE REVIEW

**Comment by spaits** [comment]
Are you reverting that PR because it does not have tests?

**Review by spaits — APPROVED** [review]
Then I agree. For the first glance the original PR looks fine for me, but I also want to see some tests for that PR.

**Review by arsenm — CHANGES_REQUESTED** [review]
Revert description gives no rationale. This isn't meaningfully testable without a target in need so -1

**Comment by tschuett** [comment]
What is the point of "without a target in need"?

**Comment by spaits** [comment]
> Revert description gives no rationale. This isn't meaningfully testable without a target in need so -1

Yeah I agree that it isn't meaningfully testable without a target. In that case, I think a target should be chosen, on which the patch is demonstrated.

Or is this PR for a downstream target?

**Comment by aemerson** [comment]
Which target currently exercises `byref`?

**Comment by tschuett** [comment]
"Theoretically AMDGPU should need this for the GlobalISel kernel lowering path"

**Comment by spaits** [comment]
Shouldn't by ref be used in all the cases in which a parameter is passed by reference?

**Comment by arsenm** [comment]
> "Theoretically AMDGPU should need this for the GlobalISel kernel lowering path"

But it doesn't because we completely bypass the normal argument legalization and directly lower from the IR signature for kernels

> Shouldn't by ref be used in all the cases in which a parameter is passed by reference? 

No. Byref is rarely used, and doesn't imply any code generation requirement in the callee. In the AMDGPU usage we just need to know the allocated size from the byref attribute

**Comment by tschuett** [comment]
Now, I am even less convinced of the original PR. It had no tests, which is almost forbidden. There was an explicit request for tests. 

Now, you are saying that `byref` is rarely used.

Dead code with no tests? I still vote for revert.

**Comment by arsenm** [comment]
> Now, I am even less convinced of the original PR. It had no tests, which is almost forbidden. There was an explicit request for tests.
> 
> Now, you are saying that `byref` is rarely used.

Yes. I believe AMDGPU is the only in tree user. Most of the code should just follow along with byval in terms of representation tracking 

> 
> Dead code with no tests? I still vote for revert.

No, this is not the policy for handling out of tree targets. This should not be reverted.

**Comment by tschuett** [comment]
If you express interest in `byref`,  then restart the PR with an AMDGPU test.

`out of tree targets.`does not free you from tests.

**Comment by arsenm** [comment]
> If you express interest in `byref`, then restart the PR with an AMDGPU test.

The AMDGPU usage of this is not going to be kludged through the DAG calling convention machinery, so will not use this 

> 
> `out of tree targets.`does not free you from tests.

It does if there is no way to test it with an in-tree target, especially for something small and mechanical like this. I'm rejecting this revert request

**Comment by darkbuck** [comment]
In PR#96805, I added a unit test to test the previous change, adding `byref` support.

**Pull request closed without merging**
