### PR TITLE
[AArch64][GlobalISel] Legalize G_SHUFFLE_VECTOR for Odd-Sized Vectors

### PR DESCRIPTION
**Pull request by chuongg3**
Legalize Smaller/Larger than legal vectors with i8 and i16 element sizes.
Vectors with elements smaller than i8 will get widened to i8 elements.

### CODE REVIEW

**Review by aemerson — APPROVED** [review]
LGTM, thanks.

**Comment by Caslyn** [comment]
Hi @chuongg3 - this change is breaking on the Fuchsia builder: https://lab.llvm.org/staging/#/builders/187/builds/1695.

Can you please revert while addressing the test failure?

**Comment by dyung** [comment]
The newly added test shufflevector.ll doesn't pass in a Release build without Assertions enabled. Please fix or revert the test.

**Comment by chuongg3** [comment]
Sorry, it seemed to be passing all the tests on my local machine before merging.
I have reverted the patch and will investigate the issue.

**Pull request merged**
