### PR TITLE
Fix CMake dependencies on mlir-linalg-ods-yaml-gen

### PR DESCRIPTION
**Pull request by RoboTux**
Fix a number of dependencies issue to build mlir-linalg-ods-yaml-gen
host binary which make a cross-build using the Make generator fail.
Namely:

- do not use binary path for the custom target created when
  LLVM_USE_HOST_TOOLS is true;
- use target name instead of name of variable holding the target name
  for add_custom_target and set_target_properties in setup_host_tool();
- force setting of executable and target cache variable which are only
  used as global variables;
- remove dependency on target defined in different directory in
  add_linalg_ods_yaml_gen() since add_custom_target DEPENDS can only be
  used on "files and outputs of custom commands created with
  add_custom_command() command calls in the same directory";
- remove unneeded dependency on ${MLIR_LINALG_ODS_YAML_GEN_EXE}, the
  target dependency will ensure the binary will be built.

Note that we keep using ${MLIR_LINALG_ODS_YAML_GEN_EXE} in the COMMAND
rather than use ${MLIR_LINALG_ODS_YAML_GEN_TARGET} because when
LLVM_NATIVE_TOOL_DIR is used the latter is an empty string.

Testing-wise, all three codepaths in get_host_tool_path() were tested
with both GNU Make and Ninja generators:
- cross-compiling with LLVM_NATIVE_TOOL_DIR checks the if path;
- cross-compiling without LLVM_NATIVE_TOOL_DIR checks the elseif path;
- native build without LLVM_NATIVE_TOOL_DIR checks the else path.

### CODE REVIEW

**Comment by RoboTux** [comment]
This is a respin of https://github.com/llvm/llvm-project/pull/112224. Note: to be able to test it I had to apply the following other PRs:
- https://github.com/llvm/llvm-project/pull/113560
- https://github.com/llvm/llvm-project/pull/113561
- https://github.com/llvm/llvm-project/pull/113563

**Comment by RoboTux** [comment]
Ping?

**Comment by RoboTux** [comment]
Ping?

**Review by stellaraccident — APPROVED** [review]
This looks ok to me. Sorry for the review latency. This part of the build scares me and I should have looked closer when I first saw this vs moving to the back of the pile.

**Comment by RoboTux** [comment]
> This looks ok to me. Sorry for the review latency. This part of the build scares me and I should have looked closer when I first saw this vs moving to the back of the pile.

Thank you! I can't blame you, clearly nobody is comfortable with that part of the build system. It seems this version did the trick, 3rd time's the charm as they say.

**Pull request merged**
