### PR TITLE
[RISCV] Enable store clustering by default

### PR DESCRIPTION
**Pull request by asb**
Builds on #73789, enabling store clustering by default using the same heuristic.

### CODE REVIEW

**Comment by asb** [comment]
I've force pushed a rebase on top of the latest #77389. The difference vs before is that clustered memory operations are consistently sorted (see [here](https://github.com/llvm/llvm-project/pull/73789#issuecomment-1842994094) for more details).

**Comment by wangpc-pp** [comment]
Reverse ping!
@asb Sorry for bothering, what about store clustering? Can we enable it as well?

**Review by wangpc-pp — APPROVED** [review]
LGTM. Thanks!

**Review by preames — APPROVED** [review]
LGTM

I have skimmed (most of) the tests, and see nothing concerning.

I do see a couple possibilities for store merging, but that's an entirely different topic.  For later consideration, the two interesting sub-cases I noticed are: both are storing zero, and we have zbkb.

**Comment by topperc** [comment]
@asb I pushed 8b46d40221f3c302e9c28e3ad7c79767f905a862 to fix the failures

**Comment by asb** [comment]
> @asb I pushed [8b46d40](https://github.com/llvm/llvm-project/commit/8b46d40221f3c302e9c28e3ad7c79767f905a862) to fix the failures

Thank you! My bad for not anticipating there had likely been new tests added.

**Pull request merged**
