### PR TITLE
[MachineLICM] Give opportunity to analyze physregs for invariance.

### PR DESCRIPTION
**Pull request by sdesmalen-arm**
At the moment MachineLoopInfo has a very simple way to determine if a use of a physical register will be invariant: if it is not a constant value or if it's not an ignorable use, then it's not considered invariant.

From a compile-time performance perspective this makes a lot of sense, but it limits code that uses implicit physical registers from being hoisted until the later MachineLICM pass (after register allocation), which has a lot fewer opportunities to hoist.

For AArch64 SME we use an implicit physical register ($vg) to avoid rematerialization beyond certain instructions. Doing this led to regressions because simple expressions were no longer hoisted by Early MachineLICM.

This patch adds some extra checks to 'isLoopInvariant' to see if any of the defs are found in the loop. If not, we can considered it loop invariant.

We expect the impact on compile-time to be negligible because there is an incentive for users to reduce the need for the smstart/smstop instructions that define $vg. In either case, we've put the functionality under a target interface to limit this only to specific registers.

### CODE REVIEW

**Review by rampitec — COMMENTED** [review]
This looks reasonable, but isn't it the same as `isIgnorableUse`? Or do you need this because you want hoisting but still want to prevent rematerialization?

**Comment by sdesmalen-arm** [comment]
> This looks reasonable, but isn't it the same as `isIgnorableUse`? Or do you need this because you want hoisting but still want to prevent rematerialization?

Yes, the latter. We've added the implicit def/use of these registers to prevent rematerialization from occurring.

**Comment by rampitec** [comment]
> > This looks reasonable, but isn't it the same as `isIgnorableUse`? Or do you need this because you want hoisting but still want to prevent rematerialization?
> 
> Yes, the latter. We've added the implicit def/use of these registers to prevent rematerialization from occurring.

Is it the same as adding code to ignore $vg to the `isIgnorableUse` instead and then override `isTriviallyReMaterializable` to check for $vg imp-use and return false?

**Comment by sdesmalen-arm** [comment]
> > > This looks reasonable, but isn't it the same as `isIgnorableUse`? Or do you need this because you want hoisting but still want to prevent rematerialization?
> > 
> > 
> > Yes, the latter. We've added the implicit def/use of these registers to prevent rematerialization from occurring.
> 
> Is it the same as adding code to ignore $vg to the `isIgnorableUse` instead and then override `isTriviallyReMaterializable` to check for $vg imp-use and return false?

Unless I misunderstand what you're suggesting, I believe it is not the same because  `implicit $vg` cannot be ignored. The dependence on `$vg` is important when trying to determine whether the instruction can be hoisted. Any definition of it in the loop should stop hoisting from happening. In contrast, `isIgnorableUse` does not result in any check for loop invariance of a physical register, it would instead just ignore the implicit use and continue the analysis as if it never saw the implicit use.

**Comment by rampitec** [comment]
> Unless I misunderstand what you're suggesting, I believe it is not the same because `implicit $vg` cannot be ignored. The dependence on `$vg` is important when trying to determine whether the instruction can be hoisted. Any definition of it in the loop should stop hoisting from happening. In contrast, `isIgnorableUse` does not result in any check for loop invariance of a physical register, it would instead just ignore the implicit use and continue the analysis as if it never saw the implicit use.

OK, understood, thanks for the explanation!

**Review by rampitec — APPROVED** [review]
LGTM, but please give others time to review it.

**Comment by sdesmalen-arm** [comment]
@sjoerdmeijer @FreddyLeaf any other comments?

**Comment by banach-space** [comment]
Thanks for preparing this 🙏🏻 

> @sjoerdmeijer @FreddyLeaf any other comments?

This unblocks some nice improvements for us in MLIR. Given that there's always a delay between MLIR and IREE (which is where ultimately we need this), could this be merged before the end of the week?

**Comment by vitalybuka** [comment]
Could you please fix or revert https://lab.llvm.org/buildbot/#/builders/238/builds/8439
CC @kstoimenov

**Comment by sdesmalen-arm** [comment]
> Could you please fix or revert https://lab.llvm.org/buildbot/#/builders/238/builds/8439 CC @kstoimenov

I don't understand, the build you pointed to passed successfully?

**Comment by vitalybuka** [comment]
> > Could you please fix or revert https://lab.llvm.org/buildbot/#/builders/238/builds/8439 CC @kstoimenov
> 
> I don't understand, the build you pointed to passed successfully?

Sorry, probably pasted wrong one.
I don't remember what what, and all bots we are looking at were green after this patch.

**Pull request merged**
