### PR TITLE
[flang] Link to libatomic with openmp and rtlib=libgcc

### PR DESCRIPTION
**Pull request by DavidTruby**
Currently when using OpenMP atomics we depend on some symbols from
libatomic. These symbols are provided in a separate library for the
libgcc runtime, so we should link to that when rtlib=libgcc.

For the compiler-rt case, the presence and location of the symbols is
dependent on how compiler-rt itself was built so we cannot make that
decision for the user. As such no extra flags are added in that case.

### CODE REVIEW

**Review by mjklemm — APPROVED** [review]
LGTM, I think this simplifies using the compiler a bit when it comes to OpenMP and more complex `atomic` regions.

**Review by tblah — APPROVED** [review]
LGTM thanks!

**Review by NimishMishra — APPROVED** [review]
LGTM! Thanks for this.

The Windows CI failure seems to be in `Driver/atomic.f90`. Do we disable this test on Windows (if there is a way to do so)?

**Comment by Meinersbur** [comment]
Better way would be to prescribe target and linker: `-target i686-pc-linux-gnu -fuse-ld=ld`

**Review by Meinersbur — APPROVED** [review]
LGTM

**Pull request merged**
