### PR TITLE
Reapply "[nfc][Driver] Remove {{(.exe)?}} from sanitizer test (#121160)"

### PR DESCRIPTION
**Pull request by vitalybuka**
This reverts commit ca28fcc6fce516129d117f5f5a14ba7f54a045d8.

Android targets pass on Windows buildbots, but fails on buildkite
https://buildkite.com/llvm-project/github-pull-requests/builds/132244

Re-apply  #121160

### CODE REVIEW

**Review by thurstond — APPROVED** [review]

**Review by thurstond — APPROVED** [review]

**Comment by bogner** [comment]
These tests are failing for me locally on windows now. Why are you removing this?

**Comment by carlocab** [comment]
I don't really understand why this is needed either. Should we revert?

**Comment by bogner** [comment]
I've gone ahead and reverted it.

**Comment by MaskRay** [comment]
This is not correct. Windows GetLinkerPath does append `.exe`. For certain tests where Windows's .exe and backslashes are annoying, we could employ `UNSUPPORTED: system-windows`. I am puzzled by the description about Android.

**Comment by vitalybuka** [comment]
> I've gone ahead and reverted it.

Thanks for reverting.

Could you please provide some information on how it fails? Error output would be enough. Upstream windows bot are OK.

>Windows GetLinkerPath does append .exe
How upstream bots pass?
E.g. the one above is unrelated flake, and subsequent runs are green. 

> UNSUPPORTED: system-windows
It's not worth it. The idea was just to simplify the test. So I'll just give up on the patch.

**Comment by vitalybuka** [comment]
> I am puzzled by the description about Android.

There is this configured buildkite https://buildkite.com/llvm-project/github-pull-requests/builds/132244

It's Windows, but only Android lines of the test fail.

**Pull request merged**
