### PR TITLE
[Clang][Builtin] add __builtin_exit

### PR DESCRIPTION
**Pull request by W-50243**
Add __builtin_exit in `clang/include/clang/Basic/Builtins.def` . It works perfectly on arm64be and arm64le.

### CODE REVIEW

**Comment by erichkeane** [comment]
This comes down to a question of 'why' from me?  Typically we add builtins like this because libc++ need them, or libc/libstdc++ use them.  In this case, I don't see any evidence of anyone really needing it.

While GCC supports it, I don't really see value here?

Also, this is adding for ALL platforms, so this is something that needs to be validated for all platforms as well (as far as runtime testing).

**Comment by W-50243** [comment]
I added __builtin_exit() because __builtin_exit() was used in some projects when I switched from GCC to LLVM. I don't think this is an isolated case, because the __builtin_exit() function is still widely used.[https://sourcegraph.com/search?q=context:global+__builtin_exit&patternType=standard&sm=1&groupBy=repo](https://sourcegraph.com/search?q=context:global+__builtin_exit&patternType=standard&sm=1&groupBy=repo)

**Comment by philnik777** [comment]
I'm not really convinced that `__builtin_exit` is widely used. If you filter for C/C++ and exclude GCC there aren't many matches: https://sourcegraph.com/search?q=context:global+__builtin_exit+count:all+-file:gcc/.*+%28lang:C+OR+lang:C%2B%2B%29&patternType=standard&sm=0&groupBy=repo

**Comment by philnik777** [comment]
Closing, since it seems to be abandoned.

**Pull request closed without merging**
