### PR TITLE
Use an abbrev to reduce size of VALUE_GUID records in ThinLTO summaries

### PR DESCRIPTION
**Pull request by jvoung**
GUID often have content in the higher bits of a 64-bit entry so using
the unabbrev encoding is inefficient (lots of VBR control bits).
Instead, use an abbrev with two 32-bit fixed width chunks.
The abbrev also helps encode the "count" in one place instead of
in every record.

Reduces size of distributed backend summary files by 8.7% in one
example app.

### CODE REVIEW

**Comment by jvoung** [comment]
@teresajohnson

**Review by teresajohnson — APPROVED** [review]
thanks! out of curiosity, what happens if you try to specify a 64-bit fixed width value?

**Comment by jvoung** [comment]
> thanks! out of curiosity, what happens if you try to specify a 64-bit fixed width value?

On the writer side, each chunk eventually gets to Emit: https://github.com/llvm/llvm-project/blob/9a1386e5fabb0d2741f2f7c873342eb86e350e9e/llvm/include/llvm/Bitstream/BitstreamWriter.h#L209 where the `Val` is of type `uint32_t` and there's an assert that requested `NumBits` is `<= 32`. 

I think there's other assumptions of the accumulator `CurValue` being 32-bits, and so on. On the Reader side similar checks / assumptions that the `MaxChunkSize` is 32 bits. https://github.com/llvm/llvm-project/blob/9a1386e5fabb0d2741f2f7c873342eb86e350e9e/llvm/include/llvm/Bitstream/BitstreamReader.h#L378

**Comment by jvoung** [comment]
And thanks for the quick review! Also, I don't have commit access yet/anymore. Would you mind helping merge this PR? Thanks!

**Comment by teresajohnson** [comment]
> And thanks for the quick review! Also, I don't have commit access yet/anymore. Would you mind helping merge this PR? Thanks!

Done!

**Comment by jvoung** [comment]
Ah sorry, looks like this broke some LLD MachO and COFF tests that I didn't notice before. I can send a revert then fix.

**Comment by jvoung** [comment]
https://github.com/llvm/llvm-project/pull/90610

**Pull request merged**
