### PR TITLE
[clang-format][NFC] Eliminate the IsCpp parameter in all functions

### PR DESCRIPTION
**Pull request by owenca**

### CODE REVIEW

**Comment by HazardyKnusperkeks** [comment]
That's okay for clang-format, but you couldn't use libFormat with different languages at once anymore.

I dislike global state in libraries.

**Comment by owenca** [comment]
> That's okay for clang-format, but you couldn't use libFormat with different languages at once anymore.

I believe we still could because `IsCpp` is set to `Style.isCpp()` every time new instances of the classes are constructed. I'll add a couple of test cases to demonstrate this.

> I dislike global state in libraries.

So do I, but I prefer this to keeping the `IsCpp` parameter. See also https://github.com/llvm/llvm-project/pull/83709#discussion_r1512657115.

**Comment by HazardyKnusperkeks** [comment]
Then I'd go back to `Style.isCpp()`.

What happens if you use libFormat concurrently?

**Comment by owenca** [comment]
> Then I'd go back to `Style.isCpp()`.

That would still require passing `Style.isCpp()` as the parameter to the `FormatToken` (and other) functions.

> What happens if you use libFormat concurrently?

Can you elaborate? Doesn't each process get its own copy of the globals of a shared library?

**Review by mydeveloperday — APPROVED** [review]
This looks good to me

**Comment by HazardyKnusperkeks** [comment]
> > What happens if you use libFormat concurrently?
> 
> Can you elaborate? Doesn't each process get its own copy of the globals of a shared library?

I mean multiple threads in the same process with different languages. maybe unlikely, but not impossible.

**Comment by owenca** [comment]
> I mean multiple threads in the same process with different languages. maybe unlikely, but not impossible.

But libFormat/clang-format are _not_ multithreaded, right?

**Comment by HazardyKnusperkeks** [comment]
> > I mean multiple threads in the same process with different languages. maybe unlikely, but not impossible.
> 
> But libFormat/clang-format are _not_ multithreaded, right?

clang-format is not, but libFormat I don't know. I know my IDE uses directly libFormat.

I will not block this, but I will also not approve it.

**Comment by d0k** [comment]
This is now breaking multithreaded IDE use cases, can you explain why this change is necessary?

**Comment by owenca** [comment]
Can you provide more info about the failed use cases?

**Comment by d0k** [comment]
It calls `clang::format::cleanupAroundReplacements` from multiple threads. Now there's a race condition on IsCpp.

If this was supposed to be a cleanup please revert it.

**Pull request merged**
