### PR TITLE
[asan,test] Disable _FORTIFY_SOURCE test incompatible with glibc 2.40

### LINKED ISSUE #100877: [asan] `TestCases/Linux/printf-fortify-5.c` fail with glibc 2.40
After upgrading to glibc 2.40, the following tests fail:

```
Failed Tests (4):
  AddressSanitizer-i386-linux :: TestCases/Linux/printf-fortify-5.c
  AddressSanitizer-i386-linux-dynamic :: TestCases/Linux/printf-fortify-5.c
  AddressSanitizer-x86_64-linux :: TestCases/Linux/printf-fortify-5.c
  AddressSanitizer-x86_64-linux-dynamic :: TestCases/Linux/printf-fortify-5.c
```

<details>
<summary>Failure outputs</summary>

```
******************** TEST 'AddressSanitizer-i386-linux :: TestCases/Linux/printf-fortify-5.c' FAILED ********************
Exit Code: 1

Command Output (stderr):
--
b'RUN: at line 1: /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang   -m32  -fPIC -shared -O2 -D_FORTIFY_SOURCE=2 -D_DSO /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so\n+ /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang -m32 -fPIC -shared -O2 -D_FORTIFY_SOURCE=2 -D_DSO /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so\nRUN: at line 2: /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang  -fsanitize=address -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -gline-tables-only  -m32  -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n+ /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang -fsanitize=address -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -gline-tables-only -m32 -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\nRUN: at line 3: not  /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp 2>&1 | FileCheck /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n+ not /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp\n+ FileCheck /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n/var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c:11:12: error: CHECK: expected string not found in input\n // CHECK: AddressSanitizer: heap-buffer-overflow\n           ^\n<stdin>:1:1: note: scanning from here\n\xbe\n\nInput file: <stdin>\nCheck file: /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n\n-dump-input=help explains the following input dump.\n\nInput was:\n<<<<<<\n          1: \xbe\ncheck:11     X error: no match found\n>>>>>>\n'
--

********************
FAIL: AddressSanitizer-i386-linux-dynamic :: TestCases/Linux/printf-fortify-5.c (754 of 7115)
******************** TEST 'AddressSanitizer-i386-linux-dynamic :: TestCases/Linux/printf-fortify-5.c' FAILED ********************
Exit Code: 1

Command Output (stderr):
--
b'RUN: at line 1: /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang   -m32  -fPIC -shared -O2 -D_FORTIFY_SOURCE=2 -D_DSO /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so\n+ /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang -m32 -fPIC -shared -O2 -D_FORTIFY_SOURCE=2 -D_DSO /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so\nRUN: at line 2: /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang  -fsanitize=address -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -gline-tables-only  -m32  -shared-libasan -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n+ /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang -fsanitize=address -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -gline-tables-only -m32 -shared-libasan -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\nRUN: at line 3: not  /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp 2>&1 | FileCheck /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n+ not /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/I386LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp\n+ FileCheck /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n/var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c:11:12: error: CHECK: expected string not found in input\n // CHECK: AddressSanitizer: heap-buffer-overflow\n           ^\n<stdin>:1:1: note: scanning from here\n\xbe\n\nInput file: <stdin>\nCheck file: /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n\n-dump-input=help explains the following input dump.\n\nInput was:\n<<<<<<\n          1: \xbe\ncheck:11     X error: no match found\n>>>>>>\n'
--

********************
FAIL: AddressSanitizer-x86_64-linux :: TestCases/Linux/printf-fortify-5.c (1255 of 7115)
******************** TEST 'AddressSanitizer-x86_64-linux :: TestCases/Linux/printf-fortify-5.c' FAILED ********************
Exit Code: 1

Command Output (stderr):
--
b"RUN: at line 1: /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang   -m64  -fPIC -shared -O2 -D_FORTIFY_SOURCE=2 -D_DSO /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so\n+ /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang -m64 -fPIC -shared -O2 -D_FORTIFY_SOURCE=2 -D_DSO /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so\nRUN: at line 2: /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang  -fsanitize=address -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -gline-tables-only  -m64  -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n+ /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang -fsanitize=address -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -gline-tables-only -m64 -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\nRUN: at line 3: not  /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp 2>&1 | FileCheck /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n+ FileCheck /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n+ not /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp\n/var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c:11:12: error: CHECK: expected string not found in input\n // CHECK: AddressSanitizer: heap-buffer-overflow\n           ^\n<stdin>:1:1: note: scanning from here\n\xbe\n<stdin>:10:10: note: possible intended match here\nSUMMARY: AddressSanitizer: 1 byte(s) leaked in 1 allocation(s).\n         ^\n\nInput file: <stdin>\nCheck file: /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n\n-dump-input=help explains the following input dump.\n\nInput was:\n<<<<<<\n            1: \xbe \ncheck:11'0     X~ error: no match found\n            2: ================================================================= \ncheck:11'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n            3: ==87899==ERROR: LeakSanitizer: detected memory leaks \ncheck:11'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n            4:  \ncheck:11'0     ~\n            5: Direct leak of 1 byte(s) in 1 object(s) allocated from: \ncheck:11'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n            6:  #0 0x55aca0e1bc83 in malloc /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/lib/asan/asan_malloc_linux.cpp:68:3 \ncheck:11'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n            7:  #1 0x7f9b7e6c968a in foo (/var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so+0x168a) \ncheck:11'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n            8:  #2 0x7f9b7e3953ed (/usr/lib64/libc.so.6+0x263ed) \ncheck:11'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n            9:  \ncheck:11'0     ~\n           10: SUMMARY: AddressSanitizer: 1 byte(s) leaked in 1 allocation(s). \ncheck:11'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncheck:11'1              ?                                                       possible intended match\n>>>>>>\n"
--

********************
FAIL: AddressSanitizer-x86_64-linux-dynamic :: TestCases/Linux/printf-fortify-5.c (1755 of 7115)
******************** TEST 'AddressSanitizer-x86_64-linux-dynamic :: TestCases/Linux/printf-fortify-5.c' FAILED ********************
Exit Code: 1

Command Output (stderr):
--
b"RUN: at line 1: /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang   -m64  -fPIC -shared -O2 -D_FORTIFY_SOURCE=2 -D_DSO /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so\n+ /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang -m64 -fPIC -shared -O2 -D_FORTIFY_SOURCE=2 -D_DSO /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so\nRUN: at line 2: /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang  -fsanitize=address -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -gline-tables-only  -m64  -shared-libasan -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n+ /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/lib/llvm/19/bin/clang -fsanitize=address -mno-omit-leaf-frame-pointer -fno-omit-frame-pointer -fno-optimize-sibling-calls -gline-tables-only -m64 -shared-libasan -o /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\nRUN: at line 3: not  /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp 2>&1 | FileCheck /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n+ not /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp\n+ FileCheck /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n/var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c:11:12: error: CHECK: expected string not found in input\n // CHECK: AddressSanitizer: heap-buffer-overflow\n           ^\n<stdin>:1:1: note: scanning from here\n\xbe\n<stdin>:10:10: note: possible intended match here\nSUMMARY: AddressSanitizer: 1 byte(s) leaked in 1 allocation(s).\n         ^\n\nInput file: <stdin>\nCheck file: /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/test/asan/TestCases/Linux/printf-fortify-5.c\n\n-dump-input=help explains the following input dump.\n\nInput was:\n<<<<<<\n            1: \xbe \ncheck:11'0     X~ error: no match found\n            2: ================================================================= \ncheck:11'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n            3: ==116049==ERROR: LeakSanitizer: detected memory leaks \ncheck:11'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n            4:  \ncheck:11'0     ~\n            5: Direct leak of 1 byte(s) in 1 object(s) allocated from: \ncheck:11'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n            6:  #0 0x7f6b1f941fd3 in malloc /var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt/lib/asan/asan_malloc_linux.cpp:68:3 \ncheck:11'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n            7:  #1 0x7f6b2036268a in foo (/var/tmp/portage/sys-libs/compiler-rt-sanitizers-19.1.0_rc1/work/compiler-rt_build/test/asan/X86_64LinuxDynamicConfig/TestCases/Linux/Output/printf-fortify-5.c.tmp.so+0x168a) \ncheck:11'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n            8:  #2 0x7f6b1f5f03ed (/usr/lib64/libc.so.6+0x263ed) \ncheck:11'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\n            9:  \ncheck:11'0     ~\n           10: SUMMARY: AddressSanitizer: 1 byte(s) leaked in 1 allocation(s). \ncheck:11'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~\ncheck:11'1              ?                                                       possible intended match\n>>>>>>\n"
--

********************
```

Reproduced with 19.1.0-rc1 after applying #100876, but also with 18.1.8.

### PR DESCRIPTION
**Pull request by MaskRay**
In terms of bug catching capability, `_FORTIFY_SOURCE` does not perform
as well as some dynamic instrumentation tools. When a sanitizer is used,
generally `_FORTIFY_SOURCE` should be disabled since sanitizer runtime
does not implement most `*_chk` functions. Using `_FORTIFY_SOURCE`
will regress error checking (asan/hwasan/tsan) or cause false positives
(msan).

`*printf_chk` are the most pronounced `_chk` interceptors for
uninstrumented DSOes (https://reviews.llvm.org/D40951).

glibc 2.40 introduced `pass_object_info` style fortified source for some
functions ([1]). `fprintf` will be mangled as
`_ZL7fprintfP8_IO_FILEU17pass_object_size1PKcz`, which has no associated
interceptor, leading to printf-fortify-5.c failure.

Just disable the test. Fix #100877

[1]: https://sourceware.org/pipermail/libc-alpha/2024-February/154531.html

### CODE REVIEW

**Review by mgorny — APPROVED** [review]
Thanks for the detailed analysis and the patch!

**Review by thesamesam — APPROVED** [review]
LGTM but give azanella a chance to comment (or be prepared to followup on comment afterwards). Thanks for digging into it. We should really run the compiler-rt testsuite before glibc releases given how often this sort of thing happens.

**Comment by zatrazz** [comment]
LGTM to me as well, but I wonder how hard would to make sanitizer work properly with forfity calls (maybe just bypass them to internal fortify implementations). Distros are now setting the fortify cflags as default for their toolchain packages, and it would be good usability if users do not need to disable fortify to enable sanitizers.

**Comment by MaskRay** [comment]
> LGTM to me as well, but I wonder how hard would to make sanitizer work properly with forfity calls (maybe just bypass them to internal fortify implementations). Distros are now setting the fortify cflags as default for their toolchain packages, and it would be good usability if users do not need to disable fortify to enable sanitizers.

Thanks for the comment. To work with fortify calls in an uninstrumented prebuilt DSO, interceptors would be needed.
To work with forced `-D_FORTIFY_SOURCE=[2|3]`, perhaps in some cases instead of more interceptors, the C library headers or `__builtin_*` function implementation can do something.

In any case, there is substantial exploration area that the release/19.x releases will be ready for. We can disable this test first.

**Pull request merged**
