### PR TITLE
Skip over std namespace in WebKit checkers.

### PR DESCRIPTION
**Pull request by rniwa**

### CODE REVIEW

**Comment by haoNoQ** [comment]
Ok am I reading this right: this is about testing code that lives directly in namespace `std::` but somehow still lives in your project right? Such as your custom modifications to standard classes, various overloads and specializations of standard things.

This patch does not affect the behavior of checkers when you're just passing raw pointers from user code to standard functions such as `std::memcpy()`. You still want to have a warning about those.

And generally you already don't have any warnings about things that's going on in system headers themselves. There's a separate suppression about that.

**Comment by haoNoQ** [comment]
(If yes, LGTM!)

**Comment by rniwa** [comment]
> Ok am I reading this right: this is about testing code that lives directly in namespace `std::` but somehow still lives in your project right? Such as your custom modifications to standard classes, various overloads and specializations of standard things.

No, this is about standard library code getting warnings.

> This patch does not affect the behavior of checkers when you're just passing raw pointers from user code to standard functions such as `std::memcpy()`. You still want to have a warning about those.

Right. But we don't want code within standard library to give warnings.

> And generally you already don't have any warnings about things that's going on in system headers themselves. There's a separate suppression about that.

Hm... it's odd that we're getting warnings there then.

**Comment by haoNoQ** [comment]
Hmm it doesn't look like we actually have that other suppression. It looks like the checker simply never warned in the standard library because there aren't WebKit classes in the standard library. But it looks like you've found a few cases where it actually happens? How does this happen? Is this because templates get instantiated with WTF classes as type arguments? Maybe a something completely different solution should be considered?

If we think it's actually a good idea to suppress warnings about standard functions, typically these suppressions are implemented with `getSourceManager().isInSystemHeader(SLoc)` checks, such as [the one we actually have](https://github.com/llvm/llvm-project/blob/llvmorg-19-init/clang/lib/StaticAnalyzer/Checkers/WebKit/NoUncountedMembersChecker.cpp#L110). This covers not only the standard library, but also other code outside of your project (basically everything that goes with `-isystem` as opposed to `-I`). Which may or may not be what we want.

I think it's likely that your solution is optimal but I still want to see some examples to understand what exactly we're dealing with.

**Comment by rniwa** [comment]
Closing this in favor of https://github.com/llvm/llvm-project/pull/91103.

**Pull request closed without merging**
