### PR TITLE
[flang] Introduce hlfir.elemental lowerings to omp.workshare_loop_nest

### PR DESCRIPTION
**Pull request by ivanradanov**
~WIP I will be adding unit tests and I am considering if we should have integrations tests for the entire omp.workshare pipeline.~

Continuation from https://github.com/llvm/llvm-project/pull/101446

### CODE REVIEW

**Comment by Thirumalai-Shaktivel** [comment]
Hi @ivanradanov, thanks for the PR!

I tried building and testing this PR. And came across a case where it seg faults. Can you please check it?
```fortran
program test
        real :: arr_01(10)
        !$omp parallel workshare
            arr_01 = arr_01*2
        !$omp end parallel workshare
end program
```

**Comment by ivanradanov** [comment]
Thank you very much - it seems to only happen with `-O0`, I am trying to find the root cause now...

**Comment by ivanradanov** [comment]
@Thirumalai-Shaktivel Fixed, it was a very stupid mistake with the argument order of the copyprivate copy function. Thank you.

**Comment by Thirumalai-Shaktivel** [comment]
Thanks for the quick fix. Yes, it works fine.

Here is another MRE that crashes:
```fortran
    subroutine test_workshare_02()
        real :: x(10)
        integer :: i
        call random_number(x)
        x = 2
        !$omp workshare
            forall(i=1: 10) x(i) = x(i) * 2
        !$omp end workshare
    end subroutine test_workshare_02
```

The same crash happens for the where statement as well.

**Comment by ivanradanov** [comment]
@Thirumalai-Shaktivel Thank you very much. Fixed. 

`forall` is actually a case which we do not handle yet. You can give it a shot if you would like.

**Comment by tblah** [comment]
@ivanradanov is anything blocking this from becoming ready for review?

**Comment by ivanradanov** [comment]
@tblah It is ready for review, I had just forgotten to take the [WIP] in the title away, sorry for that.

**Review by tblah — APPROVED** [review]
LGTM

**Pull request merged**
