### PR TITLE
[BOLT][NFC] Unify two symbol table iterations

### PR DESCRIPTION
**Pull request by corona10**
Simple refactoring which was suggested from https://github.com/llvm/llvm-project/issues/90661#issue-2272382883

### CODE REVIEW

**Comment by corona10** [comment]
I checked the build success on my local machine but not familiar to run the BOLT only test, is there any guide exists?

**Comment by corona10** [comment]
>I checked the build success on my local machine but not familiar to run the BOLT only test, is there any guide exists?

Okay `ninja check-bolt` works.

**Comment by aaupov** [comment]
Thanks Donghee! Looks good, but please retitle to "[BOLT][NFC] Unify two symbol table iterations".
One way to estimate the effect (in seconds) would be to exit(0) just above `auto CompareSymbols` and measure processing time before and after this fix. Can you please check with a large binary and add the information to the PR message?

**Comment by corona10** [comment]
> Can you please check with a large binary and add the information to the PR message?

Yeah, I will share the info soon :)

**Comment by corona10** [comment]
@aaupov 
For the CPython build(11083 symbols): 4693µs -> 4194µs (Constantly enhanced) from my environment with handy chrono-based measurement.
But when considering the possibility of noise, I am setting up the clang build.

**Comment by corona10** [comment]
https://github.com/llvm/llvm-project/blob/main/bolt/docs/OptimizingClang.md

Is this still recommened setup?

**Comment by aaupov** [comment]
> https://github.com/llvm/llvm-project/blob/main/bolt/docs/OptimizingClang.md
> 
> Is this still recommened setup?

The guide covers more than what we need in this case. You can just run on BOLT on any Clang binary, for instance, you can try BOLT instrumentation:
```
llvm-bolt clang-18 -instrument -o clang-18.bolt.inst
```

**Comment by corona10** [comment]
Hmm, my system clang-18 and pre-built clang binary from llvm-release page is not able to be processed because of the compile option (in my guess)
```
BOLT-ERROR: instrumentation runtime libraries require relocation
```

**Comment by corona10** [comment]
@aaupov 
Anyway my observation is noisy level changes :) (Even clang or CPython)

AS-IS
---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---   
0.0000 (  0.1%)   0.0000 (  0.1%)   0.0000 (  0.1%)   0.0000 (  0.1%)  discover file objects

TO-BE
---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---                  
0.0000 (  0.0%)   0.0000 (  0.1%)   0.0000 (  0.1%)   0.0000 (  0.0%)  discover file objects

**Comment by corona10** [comment]
There was a binary issue from Fedora 39 and I tested with release pre-built binary that given more proper information
But anyway, for me, it's noisy level changes.

CPU: AMD Ryzen™ 7 8845HS 
Memory: 32gb

AS-IS
---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
 0.0789 ( 21.2%)   0.0063 (  2.1%)   0.0851 ( 12.6%)   0.0854 ( 12.6%)  discover file objects

TO-BE
---User Time---   --System Time--   --User+System--   ---Wall Time---  --- Name ---
0.0804 ( 20.3%)   0.0046 (  1.6%)   0.0850 ( 12.3%)   0.0853 ( 12.3%)  discover file objects

**Comment by aaupov** [comment]
Let me test it with a large binary.

**Comment by aaupov** [comment]
To isolate the effect of the change, I added `exit(0)` here just after the second loop: https://github.com/llvm/llvm-project/blob/ffc9a30938ae5c42c03f9c563db1465876b4def6/bolt/lib/Rewrite/RewriteInstance.cpp#L876-L880

For chromium 5735 with 1.2M symbols on Intel ADL i7-12700K the effect is the following (warmup=3, 10 runs):
before:
```
  Time (mean ± σ):     400.6 ms ±   1.0 ms    [User: 354.3 ms, System: 46.2 ms]
  Range (min … max):   398.8 ms … 402.3 ms    10 runs
```
after:
```
  Time (mean ± σ):     415.5 ms ±   0.7 ms    [User: 362.4 ms, System: 52.8 ms]
  Range (min … max):   414.7 ms … 416.6 ms    10 runs
```

So merging loops has an opposite effect to what I had hoped. Thanks for putting the effort nonetheless!

**Comment by corona10** [comment]
> For chromium 5735 with 1.2M symbols 

Next time I will consider this binary for the benchmark.
Yeah it's slowing down sadly :)

**Pull request closed without merging**
