### PR TITLE
Fix build flang issue.

### PR DESCRIPTION
**Pull request by zahiraam**
This is a fix for a build issue https://lab.llvm.org/buildbot/#/builders/130/builds/1490 that happened after merging this PR: https://github.com/llvm/llvm-project/pull/97342

### CODE REVIEW

**Comment by banach-space** [comment]
@zahiraam Why was this merged without a review?

**Comment by zahiraam** [comment]
@banach-space I thought that (simple) build errors can be merged in with no reviews to unstock the buildbot. I am sorry If that something I shouldn't have done. Apologies. I can revert it.

**Comment by banach-space** [comment]
It's fine to push basic fixes to unblock broken buildbots, but you provided no indication that there's indeed a broken bot that you are trying to fix. Nor whether this is a newly introduced breakage. I assume that this is a breakage that has been introduced very recently and that there's a PR in which it was introduced?

**Comment by zahiraam** [comment]
> It's fine to push basic fixes to unblock broken buildbots, but you provided no indication that there's indeed a broken bot that you are trying to fix. Nor whether this is a newly introduced breakage. I assume that this is a breakage that has been introduced very recently and that there's a PR in which it was introduced?

Edited the description. Let me know if that's enough.

**Comment by banach-space** [comment]
Now that I understand the context - thank for the quick fix and for updating the summary ! 🙏🏻 :)

**Pull request merged**
