### PR TITLE
[RISCV] Add an instruction PrettyPrinter to llvm-objdump

### PR DESCRIPTION
**Pull request by topperc**
This prints the opcode bytes in the same order as GNU objdump without a space between them.

### CODE REVIEW

**Review by MaskRay — APPROVED** [review]

**Comment by apazos** [comment]
Hi Craig, thanks for quickly pushing this patch. 

I think we need to handle instructions of any size multiple of 16 bits. We might get some 48 bit instructions in the future.

It looks like the current code handles 16 and 32 bit instructions.

**Comment by asb** [comment]
> It looks like the current code handles 16 and 32 bit instructions.

I wondered about > 32-bit instructions too. By my reading, it will print the first 32 bits and then use `dumpBytes` for the rest. So we'll get output, though  may later want to agree what format we actually want for that case. Perhaps a TODO code comment that we may want to agree the desired format for 48-bit instruction hex when they're introduced.

LGTM, thanks Craig. I think a release note might be nice to have too, as it's user facing and also people may have objdump parsing scripts that might be affected.

**Review by asb — APPROVED** [review]

**Comment by topperc** [comment]
> Hi Craig, thanks for quickly pushing this patch.
> 
> I think we need to handle instructions of any size multiple of 16 bits. We might get some 48 bit instructions in the future.
> 
> It looks like the current code handles 16 and 32 bit instructions.

Fixed

**Comment by topperc** [comment]
I have added support for 48-bit instructions using chunks of 16-bits values. This matches GNU objdump.

**Review by asb — APPROVED** [review]
LGTM.

**Pull request merged**
