### PR TITLE
[Inliner] Improve propagation of return attributes.

### PR DESCRIPTION
**Pull request by goldsteinn**
- [Inliner] Regen checks for old test; NFC
- [Clang][X86] Split some tests for c/cpp; NFC
- [Inliner] Use "best" ret attribute when propagating attributes during inlining
- [Inliner] Also propagate `noundef` and `align` ret attributes during inlining

### CODE REVIEW

**Comment by nikic** [comment]
Apart from that, the functional changes themselves look good to me.

**Comment by goldsteinn** [comment]
> Apart from that, the functional changes themselves look good to me.

Fixed. Okay to push?

**Comment by nikic** [comment]
It looks like x86-bswap.c still has the C++ guarded code in it.

Any thoughts on

> Though I think we might be better off passing `-no-enable-noundef-analysis` to these tests, as noundef is really not what they want to test.

to avoid the test duplication?

**Comment by RKSimon** [comment]
The X86 test split is fine if you want to pre-commit that now

**Comment by RKSimon** [comment]
> The X86 test split is fine if you want to pre-commit that now

Sorry bswap.c still needs cleaning up

**Comment by nikic** [comment]
(Another alternative would be to use different check-prefixes for C/C++)

**Comment by goldsteinn** [comment]
> It looks like x86-bswap.c still has the C++ guarded code in it.
> 
> Any thoughts on
> 
> > Though I think we might be better off passing `-no-enable-noundef-analysis` to these tests, as noundef is really not what they want to test.
> 
> to avoid the test duplication?

That seems like a better approach. Doing so.

**Review by nikic — APPROVED** [review]
LGTM

**Comment by goldsteinn** [comment]
Pushed.

**Pull request closed without merging**
