### PR TITLE
[X86][APX] Fix wrong encoding of promoted KMOV instructions due to missing NoCD8

### PR DESCRIPTION
**Pull request by phoebewang**
Promoted KMOV* was encoded with CD8 incorrectly, see https://godbolt.org/z/cax513hG1

### CODE REVIEW

**Review by KanRobert — APPROVED** [review]
LGTM!

**Comment by phoebewang** [comment]
Manually cherry-pick in https://github.com/llvm/llvm-project/pull/109635

**Comment by phoebewang** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/0d334d83a4c7ce16fa1bc0e5e56bbdeaf01c2b2d https://github.com/llvm/llvm-project/commit/70529b24a30943d46e361d2990268499921e28a2

**Pull request merged**
