### PR TITLE
Report pass name when -llvm-verify-each reports breakage

### PR DESCRIPTION
**Pull request by chrulski-intel**
Update the string reported to include the pass name of last pass when running verifier after each pass.

### CODE REVIEW

**Comment by chrulski-intel** [comment]
@aeubanks Can you be a reviewer for this PR? Thanks.

**Comment by aeubanks** [comment]
code looks good, but I'd like a test like how we test -print-on-crash with `TriggerCrashPass`.

we should have a module pass and a function pass that intentionally break the IR, then run those in the test

**Comment by chrulski-intel** [comment]
Thanks for the suggestion on testing. I wasn't sure how to create a test that was intended to crash. Let me look into the tests you mention.

**Review by aeubanks — APPROVED** [review]
lg with name change suggestion

**Comment by chrulski-intel** [comment]
@aeubanks Thanks for merging this.

**Pull request merged**
