### PR TITLE
[lldb] Change Breakpoint::AddName return value

### PR DESCRIPTION
**Pull request by bulbazord**
The return value is completely unused. Let's just return nothing.

### CODE REVIEW

**Review by Michael137 — APPROVED** [review]
LGTM

**Comment by jimingham** [comment]
That makes the comment directly above your change invalid.

**Comment by jimingham** [comment]
With this change it could no longer check name validity (wasn't anyway, but...)

**Comment by jimingham** [comment]
Probably should change that to "callers are required to check name validity?"  Either that or move whoever is doing the checking here if you want to centralize that.

**Comment by bulbazord** [comment]
I'll just remove the comment. If we want to make this do error checking, we'll have to shuffle around even more code than this change does right now. I wanted to mostly get rid of this piece of cognitive overhead (why does this return something and why do we drop it on the floor?)

**Comment by bulbazord** [comment]
@jimingham Does this work for you?

**Review by medismailben — APPROVED** [review]

**Pull request merged**
