### PR TITLE
Move documentation about -verify from a header to public docs

### PR DESCRIPTION
**Pull request by AaronBallman**
The internals manual seems like a more obvious home for the details instead of hiding them away in a header file and relying on doxygen output to document it publicly.

### CODE REVIEW

**Review by erichkeane — APPROVED** [review]
Urgh, I finally set a bookmark on that page, so this is going to break that!

But yeah, this makes a lot more sense here, and I think ends up being easier to maintain.  It passes a quick proofread, so lgtm.

**Comment by philnik777** [comment]
Would it make sense to document this more publicly? While it's designed to be an internal tool, it's really useful for people who want to make sure their library produces high quality diagnostics (e.g. `nodiscard`, `static_assert`s etc.). I'm sure you are aware that libc++ uses `-verify` too.

**Review by Endilll — APPROVED** [review]

**Comment by Endilll** [comment]
> Would it make sense to document this more publicly? While it's designed to be an internal tool, it's really useful for people who want to make sure their library produces high quality diagnostics (e.g. nodiscard, static_asserts etc.). I'm sure you are aware that libc++ uses -verify too.

While I'm sympathetic to the intent, making this more public bring up the question what are we going to promise the users. I believe status quo is that we can do whatever we feel like to, coordinating it with libc++ people, which sit at a proverbial next desk to us. So I'm not opposed to this, but I'd like to see how we going to address this concern.

**Comment by AaronBallman** [comment]
> @AaronBallman After moving the docs, none of the code blocks are rendering: https://clang.llvm.org/docs/InternalsManual.html#verifying-diagnostics

huh? there are zero sphinx diagnostics about the blocks, so that's exciting.

**Comment by AaronBallman** [comment]
Neato! `.. code-block: c++` should be: `.. code-block:: c++` -- did someone disable sphinx diagnostics or something? That should have been diagnosed...

**Comment by AaronBallman** [comment]
> It would also be nice to fix the link to full `-verify` docs in https://clang.llvm.org/docs/InternalsManual.html#the-diagnosticconsumer-interface

Done.

**Pull request merged**
