### PR TITLE
Convert copy to r-value reference.

### PR DESCRIPTION
**Pull request by MalaySanghi**
That seems to be the intention based on calling code.

### CODE REVIEW

**Comment by MalaySanghiIntel** [comment]
@aeubanks please comment if I understood the intention correctly. Did you instead intend to have a copy constructor?

**Comment by aeubanks** [comment]
ah this is probably right (need the same thing in `PassManagerInternal.h`)

**Comment by MalaySanghiIntel** [comment]
@phoebewang 
Please review this change. 

The original author seems to have referred code in a different file which has the same issue. I can create a separate PR for that.

**Review by phoebewang — APPROVED** [review]
LGTM.

**Pull request merged**
