### PR TITLE
[clang][llvm][rtsan] Introduce RealtimeSanitizer clang codegen, llvm attributes

### PR DESCRIPTION
**Pull request by cjappl**
This is the second PR introducing the Realtime sanitizer.

# Review Contents
* clang driver changes to allow for -fsanitize=realtime
* The attribute that keys off of the new nonblocking function effects
* CodeGenFunction changes that insert the `__rtsan_realtime_enter/exit` calls 
* Basic lights on lit tests

Please focus your reviewing on CodeGenFunciton, and the llvm attribute and how we attach it to a function given the FunctionEffects to be sure we have done this correctly.

After this, users should be able to run rtsan end-to-end and get some usable functionality out of it.

# Reviewer support document
Please see the [reviewer support document](https://github.com/realtime-sanitizer/radsan/blob/doc/review-support/doc/review.md) for what our next steps are. If you want to see the previous review introducing the compiler-rt changes, it is here: https://github.com/llvm/llvm-project/pull/92460. Original LLVM discourse thread talking about this as well as the FunctionEffects proposal is here (https://discourse.llvm.org/t/rfc-nolock-and-noalloc-attributes/76837)

### CODE REVIEW

**Comment by cjappl** [comment]
CC For review:

@AaronBallman @Sirraide @vitalybuka @MaskRay 

@dougsonos  - would you make sure the work with the attribute and function effects make sense?

And co-author: @davidtrevelyan

**Comment by vitalybuka** [comment]
Can we split into 3 patches?
1. LLVM
2. Clang
3. Compiler-rt

**Comment by davidtrevelyan** [comment]
> Can we split into 3 patches?
> 
> 1. LLVM
> 2. Clang
> 3. Compiler-rt
> 
> And each patch should have tests

Thanks for the suggestion @vitalybuka - after some thought, we think we can remove the llvm changes entirely now, and so here's our plan:

1. close this PR soon (giving a little time for any interested parties to give feedback),
2. remove the LLVM changes,
3. open a PR for the Clang changes (using temporary stubs for `__rtsan_realtime_enter()` and `__rtsan_realtime_exit()`), and finally
4. follow this with a PR that ties it all end-to-end in compiler-rt.

Hope that all makes sense - please let us know if any alarm bells are ringing in your head. We will of course also sweep our patch for any missing test coverage. 

Thanks again!

**Comment by cjappl** [comment]
Closing in favor of these two reviews to begin with, a 3rd will be added with the lit test components after these are merged:

1. Fixing unit test intermittent failure on mac: https://github.com/llvm/llvm-project/pull/100188
2. clang codegen component https://github.com/llvm/llvm-project/pull/100192
3. (NOT POSTED YET) Initial lit tests and re-enabling our instrumented unit tests from this review

**Pull request closed without merging**
