### PR TITLE
[LLD] [COFF] Port -lto-sample-profile to COFF version of LLD

### PR DESCRIPTION
**Pull request by chrulski-intel**
Following the commit of https://github.com/llvm/llvm-project/pull/83972 which added COFF support for SPGO,
this patch ports the support of the option -lto-sample-profile that was only
available in the ELF variant of LLD to the COFF variant to enable running the
SPGO passes in the LTO/thinLTO pipelines.

### CODE REVIEW

**Comment by HaohaiWen** [comment]
Rename sample-profile.ll/.prof to lto-sample-profile.ll/.prof?
Those files for ELF are in lto folder.  LTO for COFF tests normally starts with lto- prefix.

**Comment by chrulski-intel** [comment]
> Rename sample-profile.ll/.prof to lto-sample-profile.ll/.prof? Those files for ELF are in lto folder. LTO tests for COFF normally starts with lto- prefix.

Done

**Review by MaskRay — APPROVED** [review]

**Review by tru — APPROVED** [review]

**Comment by mstorsjo** [comment]
FYI, it'd be nice to support the same new LTO options in the mingw frontend as well. The mingw frontend uses the same options syntax as the ELF frontend, so in most cases it's just case of copying the new options definitions from `lld/ELF/Options.td` into `lld/MinGW/Options.td`, adding a mapping from the ELF style options to the lld-link style option in `lld/MinGW/Driver.cpp`, and adding a test case in `lld/test/MinGW/driver.test`.

This is clearly not a requirement for this PR in itself, but if you'd have a bit of extra time to invest in it, it'd be appreciated. Otherwise I can try to look into it later. (I'm trying to keep the MinGW driver up to date in supporting all the LTO options as the ELF driver, intersected with which features actually are supported in the COFF driver.)

**Comment by chrulski-intel** [comment]
> FYI, it'd be nice to support the same new LTO options in the mingw frontend as well. The mingw frontend uses the same options syntax as the ELF frontend, so in most cases it's just case of copying the new options definitions from `lld/ELF/Options.td` into `lld/MinGW/Options.td`, adding a mapping from the ELF style options to the lld-link style option in `lld/MinGW/Driver.cpp`, and adding a test case in `lld/test/MinGW/driver.test`.
> 
> This is clearly not a requirement for this PR in itself, but if you'd have a bit of extra time to invest in it, it'd be appreciated. Otherwise I can try to look into it later. (I'm trying to keep the MinGW driver up to date in supporting all the LTO options as the ELF driver, intersected with which features actually are supported in the COFF driver.)

@mstorsjo I gave it a go in https://github.com/llvm/llvm-project/pull/85841, please have a look when you can.

**Review by HaohaiWen — APPROVED** [review]

**Pull request merged**
