### PR TITLE
Reland: [llvm-cov][WebAssembly] Read `__llvm_prf_names` from data segments

### PR DESCRIPTION
**Pull request by kateinoigakukun**
On WebAssembly, most coverage metadata contents read by llvm-cov (like `__llvm_covmap` and `__llvm_covfun`) are stored in custom sections because they are not referenced at runtime. However, `__llvm_prf_names` is referenced at runtime by the profile runtime library and is read by llvm-cov post-processing tools, so it needs to be stored in a data segment, which is allocatable at runtime and accessible by tools as long as "name" section is present in the binary.

This patch changes the way llvm-cov reads `__llvm_prf_names` on WebAssembly. Instead of looking for a section, it looks for a data segment with the same name.

This reverts commit 157f10ddf2d851125a85a71e530dc9d50cb032a2 and fixes PE/COFF `.lprfn$A` section handling.

### CODE REVIEW

**Comment by kateinoigakukun** [comment]
@glandium Would you mind testing this patch with your PGO setup? :pray:

**Comment by glandium** [comment]
Unfortunately, it still fails with the same error. I also noticed other error messages I had missed in the past (but after checking, they were there on the first landing):
```
LLVM Profile Error: Invalid profile data to merge
LLVM Profile Error: Profile Merging of file D:\task_172914326170851\fetches\llvm-project/build/profiles/10870457539148555413_0.profraw failed: File exists
LLVM Profile Error: Failed to write file "D:\task_172914326170851\fetches\llvm-project/build/profiles/10870457539148555413_0.profraw": File exists
```

**Comment by kateinoigakukun** [comment]
@glandium Thank you. That's really helpful information. I think https://github.com/llvm/llvm-project/pull/112695 might fix the failure.

**Comment by mstorsjo** [comment]
> Unfortunately, it still fails with the same error. I also noticed other error messages I had missed in the past (but after checking, they were there on the first landing):
> 
> ```
> LLVM Profile Error: Invalid profile data to merge
> LLVM Profile Error: Profile Merging of file D:\task_172914326170851\fetches\llvm-project/build/profiles/10870457539148555413_0.profraw failed: File exists
> LLVM Profile Error: Failed to write file "D:\task_172914326170851\fetches\llvm-project/build/profiles/10870457539148555413_0.profraw": File exists
> ```

@glandium Is your PGO setup still broken, after the fixup/partial revert that was pushed in 157f10ddf2d851125a85a71e530dc9d50cb032a2? I.e. does this reapply attempt still break things for you, or are things still broken on main?

**Comment by mstorsjo** [comment]
FWIW, this reland of the patch does indeed seem like it still works for `llvm-cov` for reading the profile data from Windows (on the sample files from yesterday). I haven't tested building a full toolchain with this in place and running the compiler-rt tests again. I don't know about the rest of the big picture here, or @glandium's PGO setup.

**Comment by glandium** [comment]
> or are things still broken on main?

They are, indeed.

**Pull request merged**
