### PR TITLE
[RISCV] Lower (vector_interleave X, undef) to (vzext_vl X).

### PR DESCRIPTION
**Pull request by topperc**
If the odd vector is undef or poison, the widening add and multiply trick
doesn't work unless we freeze the odd vector.
    
Unfortunately, freezing doesn't work when the operand is provably
undef/poison. MIR doesn't have a representation for freeze so it
just becomes a COPY from IMPLICIT_DEF which freely propagates undef
to each operand independently.
    
To work around this, check for undef explicitly and lower to a VZEXT_VL
of the even vector. This produces better code than we'd get from a
freeze anyway.
    
I've left a FIXME for adding a freeze. I'll do that as a separate patch
as it affects other tests and doesn't help with the new test.

### CODE REVIEW

**Review by lukel97 — APPROVED** [review]
LGTM

**Comment by kito-cheng** [comment]
And maybe ` (vector_interleave undef, X)` to `(vsll (vzext_vl X) sew_of_x)` for a separate patch?

**Comment by topperc** [comment]
Committed as 8c1dc5dd589ce6c056b95e43b72338ddea40789c and a9af66a90e625fdb3c7ad2193e827a49d185fe60

**Comment by preames** [comment]
> And maybe ` (vector_interleave undef, X)` to `(vsll (vzext_vl X) sew_of_x)` for a separate patch?

I happened to be looking at this code today, and had a similar realization. If anyone has interest, I think this generalizes significantly.  

This tactic can be generalized for an entire family of shuffles of the form:
* <a0, zero, a1, zero> -- this case
* <zero, a0, zero, a1> -- the vwsll case (also the one kito points out)
* <a0, zero, zero, zero, a1, zero, zero, zero> -- the zext.vf4 case

And the VWADD is just a specialization of the ISD::SELECT case when alternating lanes are zero in the two inputs.  

Interestingly, the recursive reasoning would *nearly* make the special case two argument form redundant.  The only bit left is the decision to "commit" undef to be zero.

**Pull request closed without merging**
