### PR TITLE
[MS] Put dllexported inline global initializers in a comdat

### LINKED ISSUE #56485: bug #37251 from clang 7 still exists in 14
https://github.com/llvm/llvm-project/issues/37251 still exists in clang-cl 14.0.6 but is also happening in debug build. My memory blew on initializing an inline global thread pool in a dll, as it was creating 1000s of instances of pools during program initialization. Same code works perfectly as a framework and .so on iOS/macOS and android/linux

### PR DESCRIPTION
**Pull request by rnk**
Follow-up to c19f4f8069722f6804086d4438a0254104242c46 to handle corner case of exported inline variables.

Should fix #56485

### CODE REVIEW

**Comment by efriedma-quic** [comment]
What's the interaction here with the standard's ordering guarantees?  The comment in the code indicates that we can't make a separate comdat for ordered initialization... but inline variables do require partial ordering.  Please update the comment as appropriate.

**Comment by rnk** [comment]
I think there is no change here in our conformance on inline variable initialization order, except that non-discardable inline variables (achieved in this instance with dllexport, but perhaps there are other ways to do this. The classic case is explicit instantiation, which is unordered) are now treated the same as regular inline variables.

My reading of the code is that we are currently technically non-conforming. There is some back and forth on whether this is good or bad elsewhere in the issue tracker, but I'd have to dig it up.

**Comment by efriedma-quic** [comment]
If there isn't a way to emit conforming code, then I think it's fine to emit non-conforming code, as long as there's an appropriate comment.  Breaking the ABI is clearly worse.

Does this impact non-MS targets?

**Comment by rnk** [comment]
Yeah, I should've explicitly said I was working on updating the comment block. It needed significant surgery. Actually, this code could probably use more significant refactoring, but let's set that aside for now.

> Does this impact non-MS targets?

At the moment, I can't think of a good way to make an inline global `weak_odr` on non-MS targets without using templates, which would hit the existing `isTemplateInstantiation` check. I want to say "no" with ~85% confidence.

**Review by efriedma-quic — APPROVED** [review]
LGTM

**Comment by rnk** [comment]
Thanks for the review!

**Pull request merged**
