### PR TITLE
[X86][CodeGen] Emit float128 libcalls for math functions

### PR DESCRIPTION
**Pull request by pranavk**
Make LLVM emit libcalls to proper float128 variants for float128 types.

### CODE REVIEW

**Comment by MaskRay** [comment]
This LGTM, but we'd need `__builtin_*f128` clang/test/CodeGen tests.

My digging into the log says that https://github.com/llvm/llvm-project/commit/4bf47bc9d7cad0fbec78df8816d9b4ae7ae2be30 (2013) introduced these l libcall names. aarch64 long double is quad precision and its `l` suffix (for long double) does indicate quad precision.

**Comment by pranavk** [comment]
@MaskRay clang codegens correct LLVM IR. So I don't think we need any more tests in clang/test/CodeGen/. All the fp128 __builtin tests we have there already check for generation of appropriate fp128 LLVM IR calls (https://github.com/llvm/llvm-project/blob/3d71e4166de81bc3b86d127d9ac6607bda2b2755/clang/test/CodeGen/X86/math-builtins.c)

The problem is in lowering of LLVM IR into machine code which is what this patch is trying to fix for X86_64. I have changed the tests to check for that lowering.

**Comment by pranavk** [comment]
Also worth noting that x86 codegen for fp128 in clang right now seems completely broken because LLVM lowers to fFOOl variants without proper casting.

https://godbolt.org/z/drP5Wrr47

**Review by andykaylor — APPROVED** [review]
This looks good to me.

**Pull request merged**
