### PR TITLE
[MLIR][acc] Introduce varType to acc data clause operations

### PR DESCRIPTION
**Pull request by razvanlupusoru**
The acc data clause operations hold an operand named `varPtr`. This was intended to hold a pointer to a variable - where the element type of that pointer specifies the type of the variable. However, for both memref and llvm dialects, this assumption is not true. This is because memref element type for cases like memref<10xf32> is simply f32 and for LLVM, after opaque pointers, the variable type is no longer recoverable.

Thus, introduce varType to ensure that appropriate semantics are kept.

Both the parser and printer for this new type attribute allow it to not be specified in cases where a dialect's getElementType() applied to `varPtr`'s type has a recoverable type. And more specifically, for FIR, no changes are needed in the MLIR unit tests.

### CODE REVIEW

**Comment by razvanlupusoru** [comment]
Note that the invasive changes in the .td file is because the latest git-clang-format now handles .td files. It formats the context around my new changes.

**Comment by clementval** [comment]
Mostly looks good for me Razvan and it makes sense. Just thinking if we can have a syntax that is more obvious. Maybe a keyword would help? If fine going with this and refine if we think it needs to be.

**Comment by razvanlupusoru** [comment]
> Mostly looks good for me Razvan and it makes sense. Just thinking if we can have a syntax that is more obvious. Maybe a keyword would help? Or just keep it printed as an attribute? I'm fine going with this and refine if we think it needs to be.

What syntax do you have in mind?

**Comment by clementval** [comment]
> > Mostly looks good for me Razvan and it makes sense. Just thinking if we can have a syntax that is more obvious. Maybe a keyword would help? Or just keep it printed as an attribute? I'm fine going with this and refine if we think it needs to be.
> 
> 
> 
> What syntax do you have in mind?

- Maybe just leave the standard syntax with the attribute would be clearer but not a strong opinion on that. As I didn't really think about this the syntax proposed didn't feel really obvious but maybe another one would also be ambiguous. Adding a keyword might help but as I mentioned that is just over thinking and could be dealt with in follow up patches.

**Comment by razvanlupusoru** [comment]
>     * Maybe just leave the standard syntax with the attribute would be clearer but not a strong opinion on that. As I didn't really think about this the syntax proposed didn't feel really obvious but maybe another one would also be ambiguous. Adding a keyword might help but as I mentioned that is just over thinking and could be dealt with in follow up patches.

I attempted to address your concern by adding the "varType" keyword to the printing. It is still optional (if the element's type is encoded in the type of varPtr's target), but at least this fixes the ambiguity when reading the IR. What do you think?

**Review by clementval — APPROVED** [review]
Looks good to me. Thanks for addressing my comment.

**Pull request merged**
