### PR TITLE
[InstCombine] Infer disjoint flag on Or instructions.

### PR DESCRIPTION
**Pull request by topperc**
Stacked on https://github.com/llvm/llvm-project/pull/72702 and https://github.com/llvm/llvm-project/pull/72583

### CODE REVIEW

**Comment by nikic** [comment]
Needs a rebase. Also you'll want to do this inside SimplifyDemanded to reuse existing KnownBits information.

**Comment by topperc** [comment]
> Also you'll want to do this inside SimplifyDemanded to reuse existing KnownBits information.

Do we do that for other flags already? I based this off Add/Sub.

**Comment by topperc** [comment]
Are the KnownBits in SimplifyDemandedBit usable? We have this code

```
    if (SimplifyDemandedBits(I, 1, DemandedMask, RHSKnown, Depth + 1) ||         
        SimplifyDemandedBits(I, 0, DemandedMask & ~RHSKnown.One, LHSKnown,       
                             Depth + 1)) { 
```

Can we trust the known bits for the LHS if we didn't demanded them due to known 1s on the right hand side?

**Review by nikic — APPROVED** [review]
LGTM

**Comment by nunoplopes** [comment]
FWIW, Alive2 is complaining about this commit. These patches are not safe w.r.t. undef.

**Comment by topperc** [comment]
> FWIW, Alive2 is complaining about this commit. These patches are not safe w.r.t. undef.

Why not?

**Comment by nunoplopes** [comment]
Here's a simple-ish example:
```llvm
; Transforms/InstCombine/add.ll

define i5 @zext_sext_not(i4 %x) {
  %zx = zext i4 %x to i5
  %notx = xor i4 %x, 15
  %snotx = sext i4 %notx to i5
  %r = add i5 %zx, %snotx
  ret i5 %r
}
=>
define i5 @zext_sext_not(i4 %x) {
  %zx = zext i4 %x to i5
  %notx = xor i4 %x, 15
  %snotx = sext i4 %notx to i5
  %r = or disjoint i5 %zx, %snotx
  ret i5 %r
}
Transformation doesn't verify! (unsound)
ERROR: Target is more poisonous than source

Example:
i4 %x = undef

Source:
i5 %zx = #x00 (0)	[based on undef value]
i4 %notx = #xf (15, -1)	[based on undef value]
i5 %snotx = #x1f (31, -1)
i5 %r = #x1f (31, -1)

Target:
i5 %zx = #x0f (15)
i4 %notx = #xf (15, -1)
i5 %snotx = #x1f (31, -1)
i5 %r = poison
Source value: #x1f (31, -1)
Target value: poison
```

Essentially the code doesn't take into consideration that a same register may have different values when it is undef.

**Comment by topperc** [comment]
> Here's a simple-ish example:
> 
> ```llvm
> ; Transforms/InstCombine/add.ll
> 
> define i5 @zext_sext_not(i4 %x) {
>   %zx = zext i4 %x to i5
>   %notx = xor i4 %x, 15
>   %snotx = sext i4 %notx to i5
>   %r = add i5 %zx, %snotx
>   ret i5 %r
> }
> =>
> define i5 @zext_sext_not(i4 %x) {
>   %zx = zext i4 %x to i5
>   %notx = xor i4 %x, 15
>   %snotx = sext i4 %notx to i5
>   %r = or disjoint i5 %zx, %snotx
>   ret i5 %r
> }
> Transformation doesn't verify! (unsound)
> ERROR: Target is more poisonous than source
> 
> Example:
> i4 %x = undef
> 
> Source:
> i5 %zx = #x00 (0)	[based on undef value]
> i4 %notx = #xf (15, -1)	[based on undef value]
> i5 %snotx = #x1f (31, -1)
> i5 %r = #x1f (31, -1)
> 
> Target:
> i5 %zx = #x0f (15)
> i4 %notx = #xf (15, -1)
> i5 %snotx = #x1f (31, -1)
> i5 %r = poison
> Source value: #x1f (31, -1)
> Target value: poison
> ```
> 
> Essentially the code doesn't take into consideration that a same register may have different values when it is undef.

Looks like this is caused by the checks in `haveNoCommonBitsSetSpecialCases`.

**Comment by topperc** [comment]
@nikic is something like this the right fix

```
diff --git a/llvm/lib/Analysis/ValueTracking.cpp b/llvm/lib/Analysis/ValueTracking.cpp
index 8c29c242215d..b03a56c922de 100644
--- a/llvm/lib/Analysis/ValueTracking.cpp
+++ b/llvm/lib/Analysis/ValueTracking.cpp
@@ -235,8 +235,11 @@ bool llvm::haveNoCommonBitsSet(const WithCache<const Value *> &LHSCache,
          "LHS and RHS should be integers");
 
   if (haveNoCommonBitsSetSpecialCases(LHS, RHS) ||
-      haveNoCommonBitsSetSpecialCases(RHS, LHS))
-    return true;
+      haveNoCommonBitsSetSpecialCases(RHS, LHS)) {
+    if (isGuaranteedNotToBeUndefOrPoison(LHS, SQ.AC, SQ.CxtI, SQ.DT) &&
+        isGuaranteedNotToBeUndefOrPoison(RHS, SQ.AC, SQ.CxtI, SQ.DT))
+      return true;
+  }
 
   return KnownBits::haveNoCommonBitsSet(LHSCache.getKnownBits(SQ),
                                         RHSCache.getKnownBits(SQ));
```

**Comment by nunoplopes** [comment]
We don't have a `isGuaranteedNotToBeUndef` only function, so that's the only way. I would leave a fixme, since this call can be removed if we ever manage to kill undef.
Thanks for your help! 🙂

**Comment by nikic** [comment]
> We don't have a `isGuaranteedNotToBeUndef` only function, so that's the only way. I would leave a fixme, since this call can be removed if we ever manage to kill undef.

I actually added this function earlier today.

> @nikic is something like this the right fix?

I'd move the calls to isGuaranteedNotToBeUndef into haveNoCommonBitsSetSpecialCases, so you can check the correct values.

**Pull request merged**
