### PR TITLE
[mlir][linalg] Replace CopyOp from memref to linalg in linalg PromoteOp

### PR DESCRIPTION
**Pull request by AviadCo**
linalg::CopyOp is much more generic and useful to promote buffers. In addition, this is linalg transform and makes more sense to use linalg operations when possible.

### CODE REVIEW

**Comment by AviadCo** [comment]
@nicolasvasilache What do you think about this patch? do you prefer I adjust PromoteOp to accept CopyOp as an option?

**Comment by AviadCo** [comment]
@nicolasvasilache ping

**Comment by nicolasvasilache** [comment]
My apologies for the delay, LGTM!

**Review by nicolasvasilache — APPROVED** [review]

**Comment by AviadCo** [comment]
@nicolasvasilache thanks!

**Comment by nicolasvasilache** [comment]
@AviadCo please also kindly note that @chelini has started the transform to specialize a generic to a named op: https://github.com/llvm/llvm-project/pull/70326.
For now it's only for copy but will evolve.

**Comment by AviadCo** [comment]
@nicolasvasilache this is useful transform! I will also review it

**Pull request merged**
