### PR TITLE
[RemoveDIs] Update migration doc to explain how to handle textual IR updates

### PR DESCRIPTION
**Pull request by SLTozer**
Related review: https://github.com/llvm/llvm-project/pull/91724

This patch updates the RemoveDIs migration document to include details on the textual IR changes, including steps to update any downstream lit tests accordingly. These steps are the same as those used to update the lit tests in the LLVM/Clang lit tests, as detailed in the review linked above.

### CODE REVIEW

**Review by jryans — APPROVED** [review]
Looks good to me, thanks for updating the docs! 😄

**Comment by jryans** [comment]
@SLTozer Maybe consider merging this as discussed in https://github.com/llvm/llvm-project/pull/93562#issuecomment-2140180221...?

**Comment by SLTozer** [comment]
>Maybe consider merging this as discussed in [#93562 (comment)](https://github.com/llvm/llvm-project/pull/93562#issuecomment-2140180221)...?

Yes, that should happen soon - before doing so it had just occurred to me that this guide assumes a unix shell, but it might be appropriate to add some windows equivalents, which I wanted to verify before adding and just haven't gotten to yet. Though if you'd prefer that to go in a separate review afterwards, I can just merge this now.

**Comment by jryans** [comment]
> Yes, that should happen soon - before doing so it had just occurred to me that this guide assumes a unix shell, but it might be appropriate to add some windows equivalents, which I wanted to verify before adding and just haven't gotten to yet. Though if you'd prefer that to go in a separate review afterwards, I can just merge this now.

Hmm, I guess I'd say it's better to have migration docs available sooner rather than later for anyone who may need them. Not sure how many LLVM developers are on Windows to help prioritise those additions... Maybe aim to merge this sometime this week, and if the Windows bits aren't ready this week, then add them in separate PR...?

**Comment by SLTozer** [comment]
Rebased the docs to remove the existing conflict, and added some minor adjustments to the start of the "Textual IR" section, just cleaning up some of the terminology and unclear sentences.

**Pull request merged**
