### PR TITLE
[RISCV] Use experimental.vp.splat to splat specific vector length elements.

### PR DESCRIPTION
**Pull request by yetingk**
Previously, llvm IR is hard to create a scalable vector splat with a specific vector length, so we use riscv.vmv.v.x and riscv.vmv.v.f to do this work. But the two rvv intrinsics needs strict type constraint which can not support fixed vector types and illegal vector types. Using vp.splat could preserve old functionality and also generate more optimized code for vector types and illegal vectors.
This patch also fixes crash for getEVT not serving ptr types.

### CODE REVIEW

**Comment by topperc** [comment]
Doesn't this fix a crash if the loaded elements have pointer type?

**Review by topperc — APPROVED** [review]
LGTM

**Review by preames — APPROVED** [review]
LGTM

**Comment by topperc** [comment]
Does this need to be backported to 19.x? Not sure if we are using vp_strided_load in RISCVGatherScatterOpt there. @preames @lukel97 ?

**Comment by preames** [comment]
> Does this need to be backported to 19.x? Not sure if we are using vp_strided_load in RISCVGatherScatterOpt there. @preames @lukel97 ?

It should not be, but @luke957 please confirm.

**Comment by lukel97** [comment]
> It should not be, but @luke957 please confirm.

#98111 isn't in 19.x so I don't think this needs backported

**Comment by lukel97** [comment]
Oh woops I missed the comments above about the pointer type crash. In that case then I think we should backport this  given that #98579 is in. Since this is independent of whether or not RISCVGatherScatterLowering emits vp_strided_load

**Pull request merged**
