### PR TITLE
[clang][AST][NFC] Add '[[fallthrough]]' to cases fall through

### PR DESCRIPTION
**Pull request by benshi001**

### CODE REVIEW

**Review by Sirraide — APPROVED** [review]
LGTM

**Review by AaronBallman — COMMENTED** [review]
Is this addressing a diagnostic you're seeing in the wild? This shouldn't be necessary because the `case` statements are adjacent to one another with only comments/whitespace between them: https://godbolt.org/z/oM7x65hq9

(I'd like to understand the motivation better because I don't think we want to add `[[fallthrough]]` to all adjacent cases in the code base, so this seems inconsistent.)

**Comment by Sirraide** [comment]
> Is this addressing a diagnostic you're seeing in the wild? This shouldn't be necessary because the `case` statements are adjacent to one another with only comments/whitespace between them: https://godbolt.org/z/oM7x65hq9
> 
> (I'd like to understand the motivation better because I don't think we want to add `[[fallthrough]]` to all adjacent cases in the code base, so this seems inconsistent.)

I agree that it seems unnecessary and I probably wouldn’t add it, but in this case the comment indicates (at least to me) that it’s maybe not obvious that fallthrough was intended (for whatever reason)—and at the very least, there is precedent for us using `[[fallthrough]]` in adjacent case labels in some places.

**Comment by Sirraide** [comment]
E.g:
https://github.com/llvm/llvm-project/blob/50801f1095d33e712c3a51fdeef82569bd09007f/clang/lib/Interpreter/IncrementalParser.cpp#L141-L151

**Comment by Sirraide** [comment]
Admittedly, it doesn’t seem to be too common, and most other occurrences of this seem to be in LLVM proper and not in Clang.

**Comment by AaronBallman** [comment]
> E.g:
> 
> https://github.com/llvm/llvm-project/blob/50801f1095d33e712c3a51fdeef82569bd09007f/clang/lib/Interpreter/IncrementalParser.cpp#L141-L151

I think this is a demonstration of exactly what we *don't* want to see in the code base. That's just purely noise IMO.

**Comment by Sirraide** [comment]
> I think this is a demonstration of exactly what we _don't_ want to see in the code base. That's just purely noise IMO.

Its seem pretty unnecessary, yeah. I was fine w/ the one in this pr mainly because of the comment; my thinking was that there ought to be a reason why this comment is there—maybe it’s not obvious that that was intended here; I’m not that familiar w/ codegen. 

But also, now that I think about it, a comment that states *that* there is fallthrough but not *why* is just stating the obvious... I suppose we could probably also do the opposite and look into removing `[[fallthrough]]` in cases like these?

**Comment by AaronBallman** [comment]
> > I think this is a demonstration of exactly what we _don't_ want to see in the code base. That's just purely noise IMO.
> 
> It seems pretty unnecessary, yeah. I was fine w/ the one in this pr mainly because of the comment; my thinking was that there ought to be a reason why this comment is there—maybe it’s not obvious that that was intended here; I’m not that familiar w/ codegen.

Yeah, I'm also not opposed to this (an attribute is better than a comment because the attribute can be analyzed), more just wondering if we want to remove the comment rather than add the attribute.

> But also, now that I think about it, a comment that states _that_ there is fallthrough but not _why_ is just stating the obvious... I suppose we could probably also do the opposite and look into removing `[[fallthrough]]` in cases like these?

We don't have a documented policy, but I think what we want to aim for is using `[[fallthrough]]` annotations whenever the cases are not adjacent to one another (ignoring comments and whitespace) and not using comments except when they're explaining why the fallthrough happens. e.g.,
```
case Foo: // No need for [[fallthrough]], cases are adjacent
case Bar:

...

case Foo:
 // We fall through here because that makes total sense to do!
 // No need for [[fallthrough]], cases are adjacent
case Bar:

...

case Foo:
  assert(Yada); // Should have a [[fallthrough]] because the cases are not adjacent in all configurations
case Bar:

...

case Foo:
#if NDEBUG
  ...
#endif // Should have a [[fallthrough]] because the cases are not adjacent in all configurations
case Bar:

...

case Foo:
  x = 12; // Should have a [[fallthrough]] because the cases are not adjacent
case Bar:
```

(I don't think we need to be prescriptive though -- if there's a reason the annotation makes a given situation more clear, we should use it.)

**Comment by AaronBallman** [comment]
> So in this case, I suppose, I’ll leave it to someone more familiar w/ codegen than me to approve/reject this pr for good.

I think in this case we should remove the comment, but maybe @rjmccall or @efriedma-quic feel differently? We could also update the comment to say something along the lines of "intentionally falling through because EmitAsmStmt knows how to handle both GCC and MSVC assembly statements."

**Comment by rjmccall** [comment]
Yeah, I don't think we need this change.  The comment is a little unnecessary, but it's not a big deal.  Really, the code ought to be using a visitor instead of a `switch`.

**Comment by MaskRay** [comment]
We should remove the comment. To make the PR more useful, the PR can be changed to remove other confusing comments like this.

**Pull request closed without merging**
