### PR TITLE
[clang-tidy][NFC] fix add_new_check python3.8 incompatibility

### LINKED ISSUE #107846: [clang-tidy] add_new_check.py fails with "TypeError: 'type' object is not subscriptable"
```cpp
$ ./clang-tools-extra/clang-tidy/add_new_check.py bugprone bit-cast-pointers --standard=c++20
Updating ./clang-tools-extra/clang-tidy/bugprone/CMakeLists.txt...
Creating ./clang-tools-extra/clang-tidy/bugprone/BitCastPointersCheck.h...
Creating ./clang-tools-extra/clang-tidy/bugprone/BitCastPointersCheck.cpp...
Updating ./clang-tools-extra/clang-tidy/bugprone/BugproneTidyModule.cpp...
Updating clang-tools-extra/docs/ReleaseNotes.rst...
Creating clang-tools-extra/test/clang-tidy/checkers/bugprone/bit-cast-pointers.cpp...
Creating clang-tools-extra/docs/clang-tidy/checks/bugprone/bit-cast-pointers.rst...
Traceback (most recent call last):
  File "./clang-tools-extra/clang-tidy/add_new_check.py", line 795, in <module>
    main()
  File "./clang-tools-extra/clang-tidy/add_new_check.py", line 790, in main
    update_checks_list(clang_tidy_path)
  File "./clang-tools-extra/clang-tidy/add_new_check.py", line 514, in update_checks_list
    def process_doc(doc_file: Tuple[str, str]) -> Tuple[str, Optional[re.Match[str]]]:
TypeError: 'type' object is not subscriptable
```

### PR DESCRIPTION
**Pull request by HerrCai0907**
Fixes: #107846

### CODE REVIEW

**Comment by nicovank** [comment]
I see `typing.Match` will be [removed in 3.13](https://docs.python.org/3/library/typing.html#typing.Match). I'm not sure if that means it won't work altogether with 3.13 or just the typecheck.

image

My vote goes to `Any` and switch back to `re.Match` when LLVM minimum is bumped >= 3.9 (#107850).

**Comment by nicovank** [comment]
Update: I misread the docs, `typing.re` is what's going to be removed, `typing.Match` is only deprecated but not planned for removal yet. Still think `Any` is the way to go to avoid introducing the deprecated type but either solution is actually fine.

**Comment by HerrCai0907** [comment]
actually both are fine. since 3.8 will stop maintain soon. It just a temp solution and may be alive only in half year.

**Comment by nicovank** [comment]
Exactly, IMO the move to 3.9 minimum should be in 6-12 months to leave a bit of time after EOL. 3.9 also has subscriptable `tuple`, `list` and `dict` which is nice.

**Review by 5chmidti — APPROVED** [review]

**Pull request merged**
