### PR TITLE
Reland "[PGO][GlobalValue][LTO]In GlobalValues::getGlobalIdentifier, use semicolon as delimiter for local-linkage varibles. "

### PR DESCRIPTION
**Pull request by mingmingl-llvm**
Fixed build-bot failures caught by post-submit tests (currently this pull request contains a [re-apply](https://github.com/llvm/llvm-project/pull/75860/commits/13133ac931e7d4d8e5ba7083d9c3b52e37d8fefb) commit and a [fix](https://github.com/llvm/llvm-project/pull/75860/commits/2ea522b24160cb8b9d8aab1ea7bf5be12362773e) commit, to make the reland diff clearer)
1) Add the list of command line tools needed by new compiler-rt test into dependency.
    * Fixed `<command-line-tool> not found` error in https://lab.llvm.org/buildbot/#/builders/127/builds/59884
    * I was able to reproduce the error and verified the fix with similar testing commands as used in the bot
       ```
       # Run cmake 
       cmake -G Ninja -DCMAKE_BUILD_TYPE=Debug -DLLVM_ENABLE_PROJECTS='clang;compiler-rt;lld' -DLLVM_USE_SPLIT_DWARF=On -DLLVM_USE_LINKER=lld -DLLVM_ENABLE_SPHINX=ON -DLLVM_OPTIMIZED_TABLEGEN=TRUE -DLLVM_TARGETS_TO_BUILD=X86 ../llvm
      # Build compiler-rt
      ninja -j <parallelism> compiler-rt
      # Build clang and lld
      ninja -j <parallelism> clang lld
      # Upon failure, add missing dependencies one by one fixed all errors
      ninja -j <parallelism> check-profile
       ```
       In the last step `ninja check-profile`, add missing dependencies one by one allows me to see errors due to missed dependencies and fixed all of them. 
2) Use `starts_with` to replace deprecated `startswith`.
    * Should fix the error ` error: 'startswith' is deprecated: Use starts_with instead [-Werror,-Wdeprecated-declarations]` in https://lab.llvm.org/buildbot/#/builders/36/builds/40893

**Original commit message**
Commit fe05193 (phab D156569), IRPGO names uses format `[<filepath>;]<linkage-name>` while prior format is `[<filepath>:<mangled-name>`. The format change would break the use case demonstrated in (updated)
`llvm/test/Transforms/PGOProfile/thinlto_indirect_call_promotion.ll` and `compiler-rt/test/profile/instrprof-thinlto-indirect-call-promotion.cpp`

This patch changes `GlobalValues::getGlobalIdentifer` to use the semicolon.

To elaborate on the scenario how things break without this PR
1. IRPGO raw profiles stores (compressed) IRPGO names of functions in one section, and per-function profile data in another section. The [NameRef](https://github.com/llvm/llvm-project/blob/fc715e4cd942612a091097339841733757b53824/compiler-rt/include/profile/InstrProfData.inc#L72) field in per-function profile data is the MD5 hash of IRPGO names.
2. When raw profiles are converted to indexed format profiles, the profiled address is [mapped](https://github.com/llvm/llvm-project/blob/fc715e4cd942612a091097339841733757b53824/llvm/lib/ProfileData/InstrProf.cpp#L876-L885) to the MD5 hash of the callee.
3. In `pgo-instr-use` thin-lto prelink pipeline, MD5 hash of IRPGO names will be [annotated](https://github.com/llvm/llvm-project/blob/fc715e4cd942612a091097339841733757b53824/llvm/lib/Transforms/Instrumentation/PGOInstrumentation.cpp#L1707) as value profiles, and used to import indirect-call-prom candidates. If the annotated MD5 hash is computed from the new format while import uses the prior format, the callee cannot be imported.

* `compiler-rt/test/profile/instrprof-thinlto-indirect-call-promotion.cpp` is added to have an end-to-end test.
* `llvm/test/Transforms/PGOProfile/thinlto_indirect_call_promotion.ll` is updated to have better test coverage from another aspect (as runtime tests are more sensitive to the environment and may be skipped by some contributors)

### CODE REVIEW

**Comment by MaskRay** [comment]
> Use starts_with to replace deprecated startswith.
> Should fix the error  error: 'startswith' is deprecated: Use starts_with instead [-Werror,-Wdeprecated-declarations] in [lab.llvm.org/buildbot/#/builders/36/builds/40893](https://lab.llvm.org/buildbot/#/builders/36/builds/40893)

This echoes my [complaint](https://maskray.me/blog/2023-09-09-reflections-on-llvm-switch-to-github-pull-requests) :)

> Sometimes, only through rebasing can one notice that the patch needs adjustments to more code or tests due to its interaction with another landed patch:

I am playing with https://getcord.github.io/spr/index.html to use Phabricator workflow without affecting reviewers' experience.

**Review by MaskRay — APPROVED** [review]

**Comment by minglotus-6** [comment]
> Sometimes, only through rebasing can one notice that the patch needs adjustments to more code or tests due to its interaction with another landed patch

Yeah, in this case there is no merge conflict for the pull request, and the error only manifest after merge happens.  Plus, the presubmit build-bot (for example the [currently pending one](https://buildkite.com/llvm-project/github-pull-requests/builds/23721) for this pull request) takes hours to complete, during which window new changes could in theory come in..

> I am playing with https://getcord.github.io/spr/index.html to use Phabricator workflow without affecting reviewers' experience.

This is helpful to know! Are there known blockers to use `spr` for llvm github review nowadays? [This post](https://discourse.llvm.org/t/stacking-patches-in-github-prs/73403/2) mentions creating branches in upstream (not fork) as one open-ended question but the restriction for branch `users/**/*` was removed [later](https://github.com/llvm/llvm-project/issues/56636#issuecomment-1773583088)

**Comment by minglotus-6** [comment]
The test failed on Windows due to mismatched names (https://lab.llvm.org/buildbot/#/builders/127/builds/59907/steps/8/logs/stdio)

I propose to mark the test as 'unsupported' for now before fixing all name matchers (https://github.com/llvm/llvm-project/pull/75886)

**Comment by minglotus-6** [comment]
I'll revert this one and fix the names offline.

**Pull request merged**
