### PR TITLE
[NFC] Cleanup in ADT and Analysis headers.

### PR DESCRIPTION
**Pull request by dfukalov**
Remove unused directly includes and forward declarations in ADT and Analysis headers.

### CODE REVIEW

**Comment by dfukalov** [comment]
For reference: [compile-time-tracker run](https://llvm-compile-time-tracker.com/compare.php?from=141536544f4ec1d1bf24256157f4ff1a3bc07dae&to=9f78f2041a62ec3e5c2614ab5df66e8eb83ac9a2&stat=instructions:u) ran with the change.

**Comment by jayfoad** [comment]
> For reference: [compile-time-tracker run](https://llvm-compile-time-tracker.com/compare.php?from=141536544f4ec1d1bf24256157f4ff1a3bc07dae&to=9f78f2041a62ec3e5c2614ab5df66e8eb83ac9a2&stat=instructions:u) with the change.

Thanks, but that is measuring the speed of the generated LLVM binary. For a change like this, it would be more interesting to see whether the time taken to compile LLVM gets slower or (hopefully) faster. Or like I said before, you could use some other metric like the total number of preprocessed source lines.

The patch itself looks good to me but I only skimmed it.

**Comment by jayfoad** [comment]
See for example https://reviews.llvm.org/D150514 which included measurements of "the total number of preprocessing tokens across the LLVM source files in lib".

**Comment by nikic** [comment]
> > For reference: [compile-time-tracker run](https://llvm-compile-time-tracker.com/compare.php?from=141536544f4ec1d1bf24256157f4ff1a3bc07dae&to=9f78f2041a62ec3e5c2614ab5df66e8eb83ac9a2&stat=instructions:u) with the change.
> 
> Thanks, but that is measuring the speed of the generated LLVM binary. For a change like this, it would be more interesting to see whether the time taken to compile LLVM gets slower or (hopefully) faster. Or like I said before, you could use some other metric like the total number of preprocessed source lines.

The relevant number is instructions:u for "clang build" at the bottom. It's a minor 0.1% build time improvement.

**Comment by jayfoad** [comment]
> > > For reference: [compile-time-tracker run](https://llvm-compile-time-tracker.com/compare.php?from=141536544f4ec1d1bf24256157f4ff1a3bc07dae&to=9f78f2041a62ec3e5c2614ab5df66e8eb83ac9a2&stat=instructions:u) with the change.
> > 
> > 
> > Thanks, but that is measuring the speed of the generated LLVM binary. For a change like this, it would be more interesting to see whether the time taken to compile LLVM gets slower or (hopefully) faster. Or like I said before, you could use some other metric like the total number of preprocessed source lines.
> 
> The relevant number is instructions:u for "clang build" at the bottom. It's a minor 0.1% build time improvement. See also https://llvm-compile-time-tracker.com/compare_clang.php?from=141536544f4ec1d1bf24256157f4ff1a3bc07dae&to=9f78f2041a62ec3e5c2614ab5df66e8eb83ac9a2&stat=instructions%3Au&sortBy=interestingness for the per-file breakdown.

Thanks. That breakdown is pretty compelling, lots of green and hardly any red.

**Review by nikic — APPROVED** [review]
LGTM

**Pull request merged**
