### PR TITLE
[RISCV] Add OperandType for vector rounding mode operands.

### PR DESCRIPTION
**Pull request by topperc**
Use TSFlags to distinquish which type of rounding mode it is.

Stacked on #114168

### CODE REVIEW

**Review by wangpc-pp — APPROVED** [review]

**Review by lenary — APPROVED** [review]

**Review by preames — APPROVED** [review]
LGTM, but it feels a bit weird to have a single operand type for both VXRM and FRM.  Do we have a single instruction/pseudo which dynamically could be either?  If not, why not split the operand type by FRM and VXRM?

**Review by mshockwave — COMMENTED** [review]
Are we gonna use these new OperandTypes instead of TSFlags to retrieve the operand index of SEW, VecPolicy etc.?

**Comment by topperc** [comment]
> Are we gonna use these new OperandTypes instead of TSFlags to retrieve the operand index of SEW, VecPolicy etc.?

I hadn't planned on it. Seems more expensive to scan the operand types to find the operands. I might use them to drop the operands in RISCVAsmPrinter.

**Comment by mshockwave** [comment]
> > Are we gonna use these new OperandTypes instead of TSFlags to retrieve the operand index of SEW, VecPolicy etc.?
> 
> I hadn't planned on it. Seems more expensive to scan the operand types to find the operands. I might use them to drop the operands in RISCVAsmPrinter.

It gives us more flexibility in a long run because we no longer need to (semi-)hardcode operand offset of these operands. But I agree at this moment it's easier to keep the current way, at least for `RISCVII::getSEWOpNum` and friends.

**Pull request merged**
