### PR TITLE
[AArch64] Use INDEX for constant Neon step vectors

### LINKED ISSUE #110410: [AArch64][SVE] can improve vector constant generation with SVE's INDEX instruction
GCC has implemented this in a recent patch. Consider the following example.
https://godbolt.org/z/szzTesvKz
```cpp
#include <arm_sve.h>

typedef int v4si __attribute__ ((vector_size (16)));
v4si
f_v4si (void)
{
  return (v4si){ 0, 1, 2, 3 };
}
```

GCC:
```asm
f_v4si():
        index   z0.s, #0, #1
        ret
```

Clang:
```asm
.LCPI0_0:
        .word   0
        .word   1
        .word   2
        .word   3
f_v4si():
        adrp    x8, .LCPI0_0
        ldr     q0, [x8, :lo12:.LCPI0_0]
        ret
```

I referred to the following GCC patch.
[INDEX](https://github.com/gcc-mirror/gcc/commit/a92f54f580c37732a5de01e47aed56882231f196)

### PR DESCRIPTION
**Pull request by rj-jesus**
When compiling for an SVE target we can use INDEX to generate constant fixed-length step vectors, e.g.:
```
uint32x4_t bar() {
  return (uint32x4_t){0, 1, 2, 3};
}
```
Currently:
```
bar():
        adrp    x8, .LCPI1_0
        ldr     q0, [x8, :lo12:.LCPI1_0]
        ret
```
With INDEX:
```
bar():
        index   z0.s, #0, #1
        ret
```

The logic for this was already in `LowerBUILD_VECTOR`, though it was hidden under a check for `!Subtarget->isNeonAvailable()`. This patch refactors this to enable the corresponding code path unconditionally for constant step vectors (as long as we can use SVE for them).

GCC implemented this [recently](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=113328).

https://godbolt.org/z/6sP3Kj3db

Resolves #110410

### CODE REVIEW

**Comment by MacDue** [comment]
Related issue #110410

**Review by paulwalker-arm — COMMENTED** [review]
Please add a more specific/dedicated test because the existing active_lane_mask tests should all ideally result in `while` instructions when SVE is available, so we'll be missing test coverage when that happens.

**Comment by rj-jesus** [comment]
> Please add a more specific/dedicated test because the existing active_lane_mask tests should all ideally result in `while` instructions when SVE is available, so we'll be missing test coverage when that happens.

Thanks, done.

A couple of questions:
1. Should we limit this to cases where the start and step of the sequence are in [-16, 15] so that we can use INDEX (immediates)? Or should we allow the general case (e.g. test case `v4i32_out_range_start_step`), where we might need to use INDEX (scalars) or INDEX (scalar, immediate)? What do you think?

2. For the sequence:
```
define <4 x i32> @v4i32_non_zero_non_one() {
  ret <4 x i32> <i32 1, i32 3, i32 5, i32 7>
}
```
We generate:
```
v4i32_non_zero_non_one:
  index z0.s, #0, #2
  orr z0.s, z0.s, #0x1
  ret
```
This doesn't seem specific to this patch so I think we can address it separately.

**Comment by paulwalker-arm** [comment]
1. We've tried to be conservative when using all the different forms of `INDEX`.  At least on Neoverse cores their bandwidth can be limiting and so we generally prefer the immediate only forms that can be hoisted out of loops leaving only high bandwidth arithmetic instructions in loop rather than an in-loop register variant of `INDEX`.

I have some work that I need to extract into a pull request to better enforce this by making the decision explicit (i.e. lowering code can choose exactly the variant it wants) rather than the current refcount method we use during instruction selection.

2. Agreed.

**Review by paulwalker-arm — APPROVED** [review]

**Comment by rj-jesus** [comment]
Sounds great, thanks very much!

> We've tried to be conservative when using all the different forms of INDEX. At least on Neoverse cores their bandwidth can be limiting and so we generally prefer the immediate only forms that can be hoisted out of loops leaving only high bandwidth arithmetic instructions in loop rather than an in-loop register variant of INDEX.

Should I then enforce the sequence to be within the immediate range, or would you rather handle this later as part of your follow-up patch?

**Comment by paulwalker-arm** [comment]
> Should I then enforce the sequence to be within the immediate range, or would you rather handle this later as part of your follow-up patch?

You can leave it with me.

**Comment by rj-jesus** [comment]
Perfect, thanks.

**Pull request merged**
