### PR TITLE
[SLP] Add vectorization support for [u|s]cmp

### PR DESCRIPTION
**Pull request by dtcxzyw**
This patch adds vectorization support for [u|s]cmp intrinsic calls.

### CODE REVIEW

**Review by RKSimon — COMMENTED** [review]
Please can you split the costmodel changes into their own patch?

**Comment by nikic** [comment]
This looks technically fine, but I think we need to improve the vector legalization before enabling this. We currently scalarize too much, e.g. take a look at https://llvm.godbolt.org/z/Er1GYv8E4. The second version is a good match for the cost estimate, the actual expansion, not so much...

**Review by nikic — APPROVED** [review]
LGTM

**Review by RKSimon — APPROVED** [review]
LGTM

**Review by Poseydon42 — APPROVED** [review]
LGTM

**Pull request merged**
