### PR TITLE
[Analysis] isTriviallyVectorizable - add vectorization support for acos/asin/atan and cosh/sinh/tanh intrinsics

### PR DESCRIPTION
**Pull request by RKSimon**
Show fallback cases in amdlibm tests where it doesn't have that specific op

### CODE REVIEW

**Comment by farzonl** [comment]
@RKSimon I didn't add `isTriviallyVectorizable` for these because it broke a number of tests in the RISCV backend. `isTriviallyVectorizable` is exposed across all backends and I think what we would want is something that could be opt in per backend.

**Comment by alexey-bataev** [comment]
Could you add the tests for other targets?

**Comment by RKSimon** [comment]
> @RKSimon I didn't add `isTriviallyVectorizable` for these because it broke a number of tests in the RISCV backend. `isTriviallyVectorizable` is exposed across all backends and I think what we would want is something that could be opt in per backend. https://github.com/llvm/llvm-project/blob/main/llvm/test/Transforms/SLPVectorizer/RISCV/math-function.ll#L488

This no longer appears to be an issue.

**Comment by alexey-bataev** [comment]
Could you add the tests for AArch64 to RISCV too?

**Comment by alexey-bataev** [comment]
> What attributes / veclibs should I use for riscv? llvm-project\llvm\test\Transforms\SLPVectorizer\RISCV\math-function.ll doesn't seem to do much

Without veclibs, just some basic stuff

**Comment by RKSimon** [comment]
Thats what math-function.ll already does already

**Comment by alexey-bataev** [comment]
> Thats what math-function.ll already does already

But not newly added functions

**Comment by RKSimon** [comment]
ceb613a8bed218e2c98cd4fad3fd2a4a3217bd77 adds missing riscv coverage - checks that there is no vectorisation

**Review by farzonl — APPROVED** [review]

**Review by alexey-bataev — APPROVED** [review]
LG, thanks!

**Pull request merged**
