### PR TITLE
[coro][pgo] Remove redundant coroutine test files

### PR DESCRIPTION
**Pull request by zmodem**
Each of these is a copy of a test under Transforms/Coroutines/

The PGO functionality is already covered by multiple runlines (pgo and no pgo) in the original files, so the copies add no new coverage, only maintenance problems.

### CODE REVIEW

**Comment by zmodem** [comment]
> This was intentional, see the comment that introduced them ([#71262 (review)](https://github.com/llvm/llvm-project/pull/71262#pullrequestreview-1723261241))

I saw that, but I don't agree with the outcome :-)

> An advantage is that the tests cover 2 concerns, really: coro lowering, and PGO instrumentation. They can potentially diverge if needed.

The original tests (e.g. llvm/test/Transforms/Coroutines/coro-split-musttail.ll) already cover both concerns nicely.

If there's a need to diverge, new tests could be created when that need arises.

> Other than needing to duplicate a fix in both places, is there any other shortcoming of the double presence?

Needing to update two almost identical copies of 12 tests is a pretty big pain.

**Comment by mtrofin** [comment]
> > This was intentional, see the comment that introduced them ([#71262 (review)](https://github.com/llvm/llvm-project/pull/71262#pullrequestreview-1723261241))
> 
> I saw that, but I don't agree with the outcome :-)
> 
> > An advantage is that the tests cover 2 concerns, really: coro lowering, and PGO instrumentation. They can potentially diverge if needed.
> 
> The original tests (e.g. llvm/test/Transforms/Coroutines/coro-split-musttail.ll) already cover both concerns nicely.
> 
> If there's a need to diverge, new tests could be created when that need arises.
> 
> > Other than needing to duplicate a fix in both places, is there any other shortcoming of the double presence?
> 
> Needing to update two almost identical copies of 12 tests is a pretty big pain.

How about removing the PGO `RUN:` from the coro side and leaving these on the PGO side handle that? (still want to hear from @david-xl if he had any other concerns addressed by the duplication tho)

One reason I could think of, to keep the PGO side, is for code review auto-notification (i.e. because the pgo pr "team" is auto-added)

**Comment by ChuanqiXu9** [comment]
No objection from me. I'd like to leave this to @mtrofin and @zmodem

**Comment by zmodem** [comment]
> How about removing the PGO RUN: from the coro side and leaving these on the PGO side handle that?

I think that would be a step in the wrong direction. It would still be a copy-paste of the test code, which is a definite code smell.

The current setup (on the coro side) with multiple run-lines for running each test in different configs is the way to go.

> One reason I could think of, to keep the PGO side, is for code review auto-notification (i.e. because the pgo pr "team" is auto-added)

It sounds like auto notifications is the main motivation here? In that case, I think the pgo team should subscribe to the coro dir.

> Are there any lit tricks to make it read from the equivalent tests under Transforms/Coroutines directory instead of %s? So that we only have one copy of the test body, but still give you notifications for PGO team.

Just subscribing to the coro test dir seems easier.

**Comment by zmodem** [comment]
Any more comments? I'd like to go ahead and merge this.

**Pull request merged**
