### PR TITLE
[mlir] Fix `TileUsingForOp` attr-dict printing/parsing, cleanup assembly format

### PR DESCRIPTION
**Pull request by ubfx**
`TileUsingForOp` has an optional Attribute `interchange` which was given in curly braces like this: `{interchange = [...]}`. The way this was parsed meant that no normal `attr-dict` could be attached to the Op.
This patch changes the assembly format of the op to represent the `interchange` Attribute more like other array Attributes in the transform Ops and adds printing/parsing of an optional attr-dict.

`transform.structured.tile_using_for %0 [5, 6] interchange [1, 0]`

### CODE REVIEW

**Review by ftynse — CHANGES_REQUESTED** [review]
How about just dropping special handling for `interchange` and having it parsed as part of regular attribute dict? This will not change the existing syntax and fix the op.

**Comment by ubfx** [comment]
> How about just dropping special handling for `interchange` and having it parsed as part of regular attribute dict? This will not change the existing syntax and fix the op.

Done, I wasn't sure about this one because it seems like the majority of the other transform Ops tend towards special printing of the inherent Attributes. Is there a rule for when to prefer one or the other?

**Comment by joker-eph** [comment]
> Done, I wasn't sure about this one because it seems like the majority of the other transform Ops tend towards special printing of the inherent Attributes. Is there a rule for when to prefer one or the other?

Yes: please consider parsing inherent attribute as part of the discardable attributes dictionary deprecated.

**Review by ftynse — APPROVED** [review]

**Comment by ubfx** [comment]
> Yes: please consider parsing inherent attribute as part of the discardable attributes dictionary deprecated.

OK, but in this case we can keep the old assembly format or should we add the special printing/parsing back?

**Comment by ftynse** [comment]
I suppose we need new assembly, but it should be fine landing this first (this is a bugfix) and working on a better assembly format that is consistent across all operations in the dialect in a separate stage.

**Pull request merged**
