### PR TITLE
[compiler-rt] Simplify definition of uptr

### PR DESCRIPTION
**Pull request by arichardson**
We can rely on the compiler-provided macro __UINTPTR_TYPE__ for all
non-MSVC compilers. I verified via https://godbolt.org/z/MW9KMjv5f that
this works for MSVC as well as GCC 4.5 Clang 3.0, so that should cover
all supported compilers.

This means we no longer need to explicitly handle new architectures
and as an added bonus also adds support for architectures where
`unsigned long long` cannot be used to hold pointers (e.g. CHERI).

### CODE REVIEW

**Review by vitalybuka — APPROVED** [review]

**Comment by mstorsjo** [comment]
This change also breaks i686 mingw builds in the same way as #106135 
```
In file included from /home/martin/code/llvm-mingw/llvm-project/compiler-rt/lib/interception/interception_win.cpp:132:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/windows.h:69:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/windef.h:9:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/minwindef.h:163:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/winnt.h:150:
/home/martin/clang-trunk/i686-w64-mingw32/include/basetsd.h:147:39: error: typedef redefinition with different types ('ULONG_PTR' (aka 'unsigned long') vs '__sanitizer::uptr' (aka 'unsigned int'))
  147 |   __MINGW_EXTENSION typedef ULONG_PTR SIZE_T,*PSIZE_T;
      |                                       ^
/home/martin/code/llvm-mingw/llvm-project/compiler-rt/lib/interception/interception.h:28:30: note: previous definition is here
   28 | typedef __sanitizer::uptr    SIZE_T;
      |                              ^
In file included from /home/martin/code/llvm-mingw/llvm-project/compiler-rt/lib/interception/interception_win.cpp:132:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/windows.h:69:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/windef.h:9:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/minwindef.h:163:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/winnt.h:150:
/home/martin/clang-trunk/i686-w64-mingw32/include/basetsd.h:148:38: error: typedef redefinition with different types ('LONG_PTR' (aka 'long') vs '__sanitizer::sptr' (aka 'int'))
  148 |   __MINGW_EXTENSION typedef LONG_PTR SSIZE_T,*PSSIZE_T;
      |                                      ^
/home/martin/code/llvm-mingw/llvm-project/compiler-rt/lib/interception/interception.h:29:30: note: previous definition is here
   29 | typedef __sanitizer::sptr    SSIZE_T;
      |                              ^
2 errors generated.
```

**Review by mstorsjo — CHANGES_REQUESTED** [review]
(Marking as request changes, to set the status for clarity.)

**Comment by arichardson** [comment]
> (Marking as request changes, to set the status for clarity.)

I've rebased this on top of #106311 which should hopefully fix the Windows issues you were seeing.

**Comment by arichardson** [comment]
@mstorsjo I confirmed that llvm-mingw `./build-compiler-rt.sh --build-sanitizers` still works, okay to merge?

**Review by mstorsjo — APPROVED** [review]
I think this looks reasonable, and as you've tested that it works with llvm-mingw, I guess it works. I haven't tested building it with MSVC though.

**Comment by aeubanks** [comment]
this has uncovered some nasty macro redefinitions in Linux headers which affects Android asan builds: https://crbug.com/365812505. can we revert this for now?

**Comment by aeubanks** [comment]
> Oh that is rather nasty - it sounds like Clang has the wrong **UINTPTR_TYPE** for Android arm32? And I guess changing that could have surprising effects?
IIUC clang agrees with gcc, so clang isn't wrong, it's just that the kernel wants a different type as `__UINTPTR_TYPE__` for some reason I don't understand.
> 
> I am surprised you did not get a compiler error, the compiler-rt/lib/interception/interception_type_test.cpp file should have failed to compile (unless it happens that in that file asm/types.h is included first and redefines **UINTPTR_TYPE**.
I'm not sure of the details, but yes either include order, or whether or not the Linux header is included at all changes behavior
> 
> I wonder if the workaround would be something like the following
> 
> ```
> #if defined(__arm) && defined(__linux__)
> #include <asm/types.h>
> #endif
> ```
> 
> Or alternatively just adding
> 
> ```
> #if defined(__arm) && defined(__linux__)
> // Clang and the Linux Arm headers disagree on uintptr_t
> typedef unsigned long uptr;
> typedef unsigned long sptr;
> #endif
> ```

I'll send out a PR that hardcodes `uptr` on Linux Arm

**Comment by nico** [comment]
Is that still simpler than what we had before this PR then?

**Comment by arichardson** [comment]
Even if it's slightly more verbose, the advantage of the new definition is that uptr now precisely matches the type of uintptr_t rather than just being the same size.

**Comment by nico** [comment]
Except on Linux/arm, while previously things were fairly similar across platforms.

**Pull request merged**
