### PR TITLE
[CMake][Release] Disable PGO

### PR DESCRIPTION
**Pull request by tstellar**
Running the test-release.sh script with PGO enabled causes build errors like:

ld.lld: error: Function Import: link error: linking module flags 'ProfileSummary': IDs have conflicting values

I believe this a build system bug due to the PGO profile data being generated unconditionally.  If you run `ninja check-all` and then `ninja install` like we do in test-release.sh, then the profile data is regenerated during `ninja install` and some of the clang tools which are not test dependencies get build during the ninja install step with different profile data.  When these tools link against the LLVM libraries, like libSupport, we end up with these errors.

### CODE REVIEW

**Review by boomanaiden154 — APPROVED** [review]
LGTM.

I've run into the issue where profile data is generated again where it shouldn't be. I've meant to open up an issue and look into it at some point, but haven't had time to do so. I haven't previously run into this causing recompilations, but the outlined flow makes sense.

I'm assuming this is a stop-gap, and the plan is to eventually fix the issue and reenable PGO in the release cache?

**Comment by tstellar** [comment]
> I'm assuming this is a stop-gap, and the plan is to eventually fix the issue and reenable PGO in the release cache?

Yes, I would like to fix this at some point, but not sure when I'll get to it.

**Comment by tstellar** [comment]
PR is here: https://github.com/llvm/llvm-project/pull/89000

**Pull request merged**
