### PR TITLE
[compiler-rt] freadlink fix 2 for #83679.

### PR DESCRIPTION
**Pull request by devnexen**
using __MAC_OS_X_VERSION_MIN_REQUIRED instead.

### CODE REVIEW

**Comment by devnexen** [comment]
cc @expcov would it be possible for you to test this branch please ?

**Comment by expcov** [comment]
@devnexen I have successfully built libclang_rt on the freadlink_macos_fix2 branch.
However, an error occurs during the build of runtimes-clobber.

```
[100%] Built target yaml2obj
[100%] Built target llvm_gtest
[100%] Built target llvm_gtest_main
[100%] Built target runtimes-clobber
[100%] Performing configure step for 'runtimes'
Not searching for unused variables given on the command line.
loading initial cache file /Users/kenji/develop/expcov/freadlink_macos_fix2/build/projects/runtimes/tmp/runtimes-cache-Release.cmake
-- Warning: Did not find file Compiler/-ASM
-- Could NOT find LibEdit (missing: LibEdit_INCLUDE_DIRS LibEdit_LIBRARIES) 
-- Could NOT find LibEdit (missing: LibEdit_INCLUDE_DIRS LibEdit_LIBRARIES) 
CMake Error at /Users/kenji/develop/expcov/freadlink_macos_fix2/llvm/cmake/modules/CheckProblematicConfigurations.cmake:14 (if):
  if given arguments:

    "STREQUAL" "MSVC"

  Unknown arguments specified
Call Stack (most recent call first):
  /Users/kenji/develop/expcov/freadlink_macos_fix2/llvm/cmake/modules/HandleLLVMOptions.cmake:10 (include)
  CMakeLists.txt:166 (include)


-- Configuring incomplete, errors occurred!
make[2]: *** [runtimes/runtimes-stamps/runtimes-configure] Error 1
make[1]: *** [runtimes/CMakeFiles/runtimes.dir/all] Error 2
make: *** [all] Error 2
```

I think the following fixes are needed to correct this problem.

```
diff --git a/llvm/cmake/modules/CheckProblematicConfigurations.cmake b/llvm/cmake/modules/CheckProblematicConfigurations.cmake
index e133873d756c..c39414fc385b 100644
--- a/llvm/cmake/modules/CheckProblematicConfigurations.cmake
+++ b/llvm/cmake/modules/CheckProblematicConfigurations.cmake
@@ -11,7 +11,7 @@ endmacro()
 
 # MSVC and /arch:AVX is untested and have created problems before. See:
 # https://github.com/llvm/llvm-project/issues/54645
-if(${CMAKE_CXX_COMPILER_ID} STREQUAL MSVC)
+if("${CMAKE_CXX_COMPILER_ID}" STREQUAL "MSVC")
   string(TOLOWER "${CMAKE_CXX_FLAGS} ${CMAKE_C_FLAGS}" _FLAGS)
   if(_FLAGS MATCHES "/arch:avx[0-9]*")
     log_problematic("Compiling LLVM with MSVC and the /arch:AVX flag is known to cause issues with parts of LLVM.\nSee https://github.com/llvm/llvm-project/issues/54645 for details.\nUse clang-cl if you want to enable AVX instructions.")
```

I have an error when building libunwind, I will exclude it and try the build again.

**Comment by devnexen** [comment]
Normally 

```cmake
if(CMAKE_CXX_COMPILER_ID STREQUAL "MSVC")
```

should work, the issues lies on the missing quotes for the string.

**Comment by devnexen** [comment]
Anyhow, feel free to submit a PR about this later on if you want.

**Comment by hnrklssn** [comment]
freadlink.c test cases are failing on Darwin x86_64: https://green.lab.llvm.org/job/llvm.org/job/clang-stage1-cmake-RA-expensive/2122/testReport/
```
/Users/ec2-user/jenkins/workspace/llvm.org/clang-stage1-cmake-RA-expensive/clang-build/tools/clang/runtime/compiler-rt-bins/test/sanitizer_common/asan-x86_64-Darwin/Darwin/Output/freadlink.c.tmp
Assertion failed: (res2 >= 0), function main, file freadlink.c, line 23.
/Users/ec2-user/jenkins/workspace/llvm.org/clang-stage1-cmake-RA-expensive/clang-build/tools/clang/runtime/compiler-rt-bins/test/sanitizer_common/asan-x86_64-Darwin/Darwin/Output/freadlink.c.script: line 1: 26091 Abort trap: 6           /Users/ec2-user/jenkins/workspace/llvm.org/clang-stage1-cmake-RA-expensive/clang-build/tools/clang/runtime/compiler-rt-bins/test/sanitizer_common/asan-x86_64-Darwin/Darwin/Output/freadlink.c.tmp
```

Do you have a quick fix? Otherwise, would you please revert your changes?

**Comment by devnexen** [comment]
looking into it.

**Pull request merged**
