### PR TITLE
[Flang][OpenMP][MLIR] Fix common block mapping for regular and declare target link

### PR DESCRIPTION
**Pull request by agozillon**
This PR attempts to fix common block mapping for regular mapping of these types as well as when they have been marked as "declare target link". This PR should allow correct mapping of both the members of a common block and the full common block via its block symbol.

The main changes were some adjustments to the Fortran OpenMP lowering to HLFIR/FIR, the lowering of the LLVM+OpenMP dialect to LLVM-IR and adjustments to the way the we handle target kernel map argument rebinding inside of the OMPIRBuilder.

For the Fortran OpenMP lowering were two changes, one to prevent the implicit capture of common block members when the common block symbol itself has been marked and the other creates intermediate member access inside of the target region to be used in-place of those external to the target region, this prevents external usages breaking the IsolatedFromAbove pact.

In the latter case, there was an adjustment to the size calculation for types to better handle cases where we pass an array as the type of a map (as opposed to the bounds and the type of the element), which occurs in the case of common blocks. There is also some adjustment to how handleDeclareTargetMapVar handles renaming of declare target symbols in the module to the reference pointer, now it will only apply to those within the kernel that is currently being generated and we also perform a modification to replace constants with instructions as necessary as we cannot replace these with our reference pointer (non-constant and constants do not mix nicely).

In the case of the OpenMPIRBuilder some changes were made to defer global symbol rebinding to kernel arguments until all other arguments have been rebound. This makes sure we do not replace uses that may refer to the global (e.g. a GEP) but are themselves actually a separate argument that needs bound.

Currently "declare target to" still needs some work, but this may be the case for all types in conjunction with "declare target to" at the moment.

### CODE REVIEW

**Comment by agozillon** [comment]
@kiranchandramohan No real need to review this, but I've added you as a reviewer incase you wish to feed into it, but also if you know someone else that might be quite helpful to review the change set external to AMD! In particular for this change: https://github.com/llvm/llvm-project/pull/91829/files#diff-496a295679ae3c43f8651c944a1bd9dca177ad2b5e4d7121f96938024e292bc1R841 it seems reasonable to me to do, but someone with more knowledge on common blocks and their implementation may know otherwise.

**Comment by agozillon** [comment]
Small ping for some reviews on this in the near future!

**Comment by agozillon** [comment]
Small ping on this for some reviewer attention if at all possible!

**Comment by kiranchandramohan** [comment]
I will have a look this week. Sorry for the delay here.

**Comment by kiranchandramohan** [comment]
Was there an initial patch that added support for common block mapping? If so, could you give me a link?

**Comment by agozillon** [comment]
> Was there an initial patch that added support for common block mapping? If so, could you give me a link?

There was not, I believe we just assumed it was working after some prior testing but the tests were not quite correct unfortunately, so this PR allows it to appropriately function when declare target link'd (but no declare target to) and regular mapped explicit/implicit at least from testing so far.

**Comment by agozillon** [comment]
Rebased and fixed conflicts on the PR and updated this PR on top of the replaceConstant PR which upgrades the variation I had in this PR. Basically just simplifies this PR by 30-40 lines. 

However, I did encounter a bit of an issue that seems unrelated to this PR that's arisen between now and the original opening of this PR, it seems that utilising the common block /var/ syntax inside of the map clause will crash the compiler in the decomposer, it's not picked up by any of the upstream tests at the moment as the main map clause + common block tests are semantic checks at the moment, and the act of emitting semantic erroring in the one test I seen prevents the test from progressing to the point it would crash! I've talked to @kparzysz and will open up a very small PR to fix it in a little bit.

However, in the meantime, please do feel free to review this PR and if you see errors in the CI in the meantime, that's likely the cause.

**Comment by agozillon** [comment]
Small ping for some reviewer attention, would be nice to be able to progress this PR along towards some kind of resolution! Thank you very much ahead of time :-)

**Comment by kiranchandramohan** [comment]
> @kiranchandramohan No real need to review this, but I've added you as a reviewer incase you wish to feed into it, but also if you know someone else that might be quite helpful to review the change set external to AMD! In particular for this change: https://github.com/llvm/llvm-project/pull/91829/files#diff-496a295679ae3c43f8651c944a1bd9dca177ad2b5e4d7121f96938024e292bc1R841 it seems reasonable to me to do, but someone with more knowledge on common blocks and their implementation may know otherwise.

The link you have given here refers to existing code. Is that correct? 
```
mlir::Operation *clonedOp = bound.getDefiningOp()->clone();
```

If you can phrase your exact question on the issue with the common block then we can request Jean or someone else to have a look.

**Comment by agozillon** [comment]
> > @kiranchandramohan No real need to review this, but I've added you as a reviewer incase you wish to feed into it, but also if you know someone else that might be quite helpful to review the change set external to AMD! In particular for this change: https://github.com/llvm/llvm-project/pull/91829/files#diff-496a295679ae3c43f8651c944a1bd9dca177ad2b5e4d7121f96938024e292bc1R841 it seems reasonable to me to do, but someone with more knowledge on common blocks and their implementation may know otherwise.
> 
> The link you have given here refers to existing code. Is that correct?
> 
> ```
> mlir::Operation *clonedOp = bound.getDefiningOp()->clone();
> ```
> 
> If you can phrase your exact question on the issue with the common block then we can request Jean or someone else to have a look.

Ah, the link location seems to have changed after the rebase and updates, sorry about that. This is the location now (the definition of genIntermediateCommonBlockAccessors) : https://github.com/llvm/llvm-project/pull/91829/files#diff-496a295679ae3c43f8651c944a1bd9dca177ad2b5e4d7121f96938024e292bc1R787 

I am wondering if it is reasonable for me to generate common block member accesses within the target region and then bind the symbol for the common block members to them for the duration of the target region lowering. This or something very similar is currently done for another piece of OpenMP code related to privatization, so it's borrowing a similar concept. It results in the appropriate member accesses to the mapped common block as well as the correct usage of the newly generated local member accesses throughout the target operation. Without this step you end up with member accesses external to the IFA target region which results in verification issues, an alternative more complex and less fool proof (for me at least) method would be to clone the existing member accesses into the region and rebind them to the corresponding blocks argument for the mapped common block. This is an issue when using the common block symbol (e.g. map(tofrom: /common_block/)to map the entirety of a common block. Other methods would be creating a map for each individual member (similarly to if we were mapping individual elements of the common block), but this led to issues later in lowering as you don't have the parent symbol and a few other issues that I unfortunately can't recollect right this moment (but can dig back up with some testing if desired).

But in essence, I thought this method might be reasonable as it's been utilised before (albeit in a slightly different scenario) and it was a fair bit simpler than the alternatives. I'd just like to verify if it seemed reasonable to those more familiar with FIR and Fortran :-)! 

The above method results in the following IR when mapping a common block symbol (not individual or multiple members, that is the intent at least): https://github.com/llvm/llvm-project/pull/91829/files#diff-291898b3de7308afe65947c1029376201d17c7598f96adc09d43548cd9364548R9

**Comment by kiranchandramohan** [comment]
> I am wondering if it is reasonable for me to generate common block member accesses within the target region and then bind the symbol for the common block members to them for the duration of the target region lowering. This or something very similar is currently done for another piece of OpenMP code related to privatization, so it's borrowing a similar concept. It results in the appropriate member accesses to the mapped common block as well as the correct usage of the newly generated local member accesses throughout the target operation.

For common blocks the OpenMP 5.2 standard in Section 3.2.1 Page 61 and Section 5.4 Page 108 has the following. I think privatization uses this description to privatize each member and hence have separate binding.
```
When a named commonblock appears in an OpenMP argument list,it has the same meaning and restrictions as if every
explicit member of the commonblock appeared in the list.
```
```
If individual members of a commonblock appear in a data-sharing attribute clause other than the shared clause, the variables no longer have a Fortran storage association with the commonblock.
```

In your proposal, when mapping the commonblock I am assuming each member get mapped separately. This is alrite as per the first point above. There could be a performance issue. Also assuming lowering to LLVM IR ensure that while each member is mapped separately, it is actually mapped offsets of the original commonblock.

**Comment by agozillon** [comment]
> > I am wondering if it is reasonable for me to generate common block member accesses within the target region and then bind the symbol for the common block members to them for the duration of the target region lowering. This or something very similar is currently done for another piece of OpenMP code related to privatization, so it's borrowing a similar concept. It results in the appropriate member accesses to the mapped common block as well as the correct usage of the newly generated local member accesses throughout the target operation.
> 
> For common blocks the OpenMP 5.2 standard in Section 3.2.1 Page 61 and Section 5.4 Page 108 has the following. I think privatization uses this description to privatize each member and hence have separate binding.
> 
> ```
> When a named commonblock appears in an OpenMP argument list,it has the same meaning and restrictions as if every
> explicit member of the commonblock appeared in the list.
> ```
> 
> ```
> If individual members of a commonblock appear in a data-sharing attribute clause other than the shared clause, the variables no longer have a Fortran storage association with the commonblock.
> ```

> In your proposal, when mapping the commonblock I am assuming each member get mapped separately. This is alrite as per the first point above. There could be a performance issue. Also assuming lowering to LLVM IR ensure that while each member is mapped separately, it is actually mapped offsets of the original commonblock.

 However, in the case where you perform using a common block symbol e.g. map(tofrom: /commonblock/) the mapping will be as if you map the entire block of memory, not as if you map each individually in this PR. You can see this in the tests e.g.: https://github.com/llvm/llvm-project/pull/91829/files#diff-0b2da1d2f88526ca7701608cd4b7478ea4a4c067abe549e90f04b798947498c4R236 

This was simpler from the perspective of how the IR in the target region is currently generated when the common block symbol is provided as well as with the eventual lowering to LLVM-IR with the way common blocks are implemented as a block of bytes that is indexed into per member.

However, in effect

**Comment by kiranchandramohan** [comment]
> https://github.com/llvm/llvm-project/pull/91829/files#diff-0b2da1d2f88526ca7701608cd4b7478ea4a4c067abe549e90f04b798947498c4R383

I think this makes perfect sense to me. Thanks for the explanation.

**Review by kiranchandramohan — APPROVED** [review]
LG.

**Review by raghavendhra — APPROVED** [review]
LGTM :)

**Comment by agozillon** [comment]
Thank you very much @kiranchandramohan @raghavendhra 

I'll aim to land the PR on Monday or Tuesday next week incase anyone has anything else they would like to add. I'll likely rebase the PR and add one or two more tests before I land it.

**Comment by agozillon** [comment]
Added a couple more tests, primarily extending convert-to-llvm-openmp-and-fir.fir and adding a new test to mlir/test/Target/LLVMIR named omptarget-fortran-common-block-host.mlir.

The convert-to-llvm-openmp-and-fir.fir test is dependent on the changes in this PR: https://github.com/llvm/llvm-project/pull/96530 which just adds the cg-rewrite pass to the fir-opt command for the convert-to-llvm-openmp-and-fir.fir test, allowing DeclareOp's to be utilised in the test without verification errors. 

So I'll hold off landing the PR until that has hopefully landed. Otherwise, if no further comments over the new test additions are made or any other comments in the meantime I will go ahead with landing the PR.

**Comment by agozillon** [comment]
Going to adjust the offending test to not need the cg-rewrite pass change and then land the PR in the next hour after it passes the linux buildbot (and perhaps windows if it doesn't take an excessive amount of time). So, please do add any further comments in the next little bit incase you wish a delay/fix of the PR or a revert.

**Pull request merged**
