### PR TITLE
[libclang/python] Export all enums

### LINKED ISSUE #48212: clang python binding: please add ‘AccessSpecifier’ enum into __all__
|  |  |
| --- | --- |
| Bugzilla Link | [48868](https://llvm.org/bz48868) |
| Version | 11.0 |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @zygoloid |

## Extended Description 
I wish to use clang python binding in my tool chain to auto generate binding code between c++ and lua. 

but, clang python binding does not expose ‘AccessSpecifier’ enum in __all__ field. so client code can not use it to determine whether a member is public or private or protected.

can you please add ‘AccessSpecifier’ enum into __all__ ?

### PR DESCRIPTION
**Pull request by DeinAlptraum**
This resolves #48212 and also adds the remaining unexposed Enums

### CODE REVIEW

**Comment by DeinAlptraum** [comment]
@Endilll can I ask you for a review again?

**Review by Endilll — APPROVED** [review]
LGTM
I think `__all__` can be made a tuple instead, but it's not necessarily in the scope of this PR.

**Comment by DeinAlptraum** [comment]
Could you also merge please? (or are you waiting for something else?)

**Comment by tbaederr** [comment]
> @tbaederr CI for this patch has failed due to unrelated failure that is likely to be connected to your work:

That should be fixed already, I assume this is using an old version of the test.

**Comment by Endilll** [comment]
> > @tbaederr CI for this patch has failed due to unrelated failure that is likely to be connected to your work:
> 
> That should be fixed already, I assume this is using an old version of the test.

Sure, but it's annoying then you make a branch from `main`, only to find out that it's wasn't green.
At the worst, I had to merge from `main` multiple times before I was able to get rid of unrelated failures in CI, adding an unnecessary CI load.

**Comment by DeinAlptraum** [comment]
This may be my fault, I don't remember if I pulled main before branching for this PR, especially seeing how my last PR also had unrelated test failures

**Pull request merged**
