### PR TITLE
[PS4/PS5][NFC] Split PScpu::Linker into PS4/PS5 classes

### PR DESCRIPTION
**Pull request by playstation-edd**
It has long been the case on PlayStation that the linker itself has taken on much of the responsibility that is traditionally the domain of the C language driver elsewhere: which linker script to use, selection of CRT objects, and so forth.

This is changing on PS5. The driver will assume responsibility for such things. However, the situation on PS4 will remain as-is. To accommodate this divergence, we must first separate how linker Jobs are created. `clang/test/Driver/ps4-linker.c` has been similarly split for related reasons.

In subsequent changes, PS5-specific linking behaviour can be moved from SIE private patches in the PS5 linker to the (upstream) driver without affecting the behaviour or implementation of PS4.

### CODE REVIEW

**Comment by playstation-edd** [comment]
> If you wish to, you can add reviewers by using the "Reviewers" section on this page.
> 
> If this is not working for you, it is probably because you do not have write permissions for the repository. In which case you can instead tag reviewers by name in a comment by using `@` followed by their GitHub username.

Tagging @pogo59 for review.

**Review by pogo59 — APPROVED** [review]
LGTM

**Comment by pogo59** [comment]
Looks like you don't have write permission so I'll merge it for you.

**Comment by playstation-edd** [comment]
> Looks like you don't have write permission so I'll merge it for you.

Thanks!

**Pull request merged**
