### PR TITLE
Thread safety analysis: provide printSCFG definition.

### PR DESCRIPTION
**Pull request by hokein**
I called this function when investigating the issue (https://github.com/llvm/llvm-project/issues/78131), and I was surprised to see the definition is commented out.

I think it makes sense to provide the definition even though the implementation is not stable.

### CODE REVIEW

**Comment by aaronpuchert** [comment]
It might have been commented out so that it doesn't take up space in the compiled binary.

I'd like seeing it compiled, just to make sure it doesn't break. But I'd also like if it doesn't appear in the final binary. Perhaps we can change visibility so that `--gc-sections` or LTO can optimize it out? But I'm not sure if that's enough.

**Comment by hokein** [comment]
> It might have been commented out so that it doesn't take up space in the compiled binary.
> 
> I'd like seeing it compiled, just to make sure it doesn't break. But I'd also like if it doesn't appear in the final binary. Perhaps we can change visibility so that `--gc-sections` or LTO can optimize it out? But I'm not sure if that's enough.

If we don't want it to be in the final binary, how about guarding this part of code (`declaration` & `definition`) with `#ifndef NDEBUG`?

**Comment by aaronpuchert** [comment]
This sounds like a good idea!

**Comment by hokein** [comment]
> This sounds like a good idea!

Done.

**Review by aaronpuchert — APPROVED** [review]
Thanks, looks good to me!

**Pull request merged**
