### PR TITLE
[llvm-readobj][ELF] Test multivalued rpath entries and alter the output for readobj to emphasize the single valued nature of NEEDED, SONAME, USED etc.

### PR DESCRIPTION
**Pull request by feg208**
In the context of #95976 it became clear that the output for readobj implied multi valued entries in several cases in the elf headers that the documentation only allowed for a single value. DT_NEEDED is the example here where the value is an offset into the string table without any sort of separator that could give you multiple entries. This patch alters the LLVM output so that the single valued nature is emphasized. For example the output was:
```
DynamicSection [ (35 entries)
  Tag                Type         Name/Value
  0x000000000000001D RUNPATH      Library runpath: [$ORIGIN/../lib:]
  0x0000000000000001 NEEDED       Shared library: [libm.so.6]
  0x0000000000000001 NEEDED       Shared library: [libz.so.1]
  0x0000000000000001 NEEDED       Shared library: [libzstd.so.1]
```
and is now
```
  Tag                Type         Name/Value
  0x000000000000001D RUNPATH      Library runpath: [$ORIGIN/../lib:]
  0x0000000000000001 NEEDED       Shared library: libm.so.6
  0x0000000000000001 NEEDED       Shared library: libz.so.1
  0x0000000000000001 NEEDED       Shared library: libzstd.so.1
```
This pr also tests that multi-valued rpaths are handled correctly in the JSON case (i.e. they become proper lists) like:
```
{
    "Tag": 15,
    "Type": "RPATH",
    "Value": 9,
    "Path": [
        "x",
        "w",
        "U"
    ]
},
```
when separated by :

### CODE REVIEW

**Review by ilovepi — COMMENTED** [review]
LGTM.  The patch seems simple enough, but I'm not a frequent enough user of these tools to say I didn't miss something in the output.

**Review by jh7370 — COMMENTED** [review]
Existing code and test changes all look good, but there's a buildkite test failure due to the behaviour change that needs fixing. I recommend running check-all with the lld project enabled too.

**Comment by feg208** [comment]
> Existing code and test changes all look good, but there's a buildkite test failure due to the behaviour change that needs fixing. I recommend running check-all with the lld project enabled too.

Yeah there were a couple busted tests. Rolled them up

**Review by jh7370 — APPROVED** [review]
LGTM, thanks, and good catch on the NOT patterns.

**Comment by MaskRay** [comment]
LGTM

**Comment by kraj** [comment]
The output now differs from what GNU readelf/objdump generates. There is a tool in yocto which processes `SONAME` entry to detect the name of the shared object and now that test fails and several packages fail when using llvm-readelf, I wonder if there are more such tools post processing ELF files, they all will have similar issues.

**Comment by jh7370** [comment]
> The output now differs from what GNU readelf/objdump generates. There is a tool in yocto which processes `SONAME` entry to detect the name of the shared object and now that test fails and several packages fail when using llvm-readelf, I wonder if there are more such tools post processing ELF files, they all will have similar issues.

Ah, sorry, that was my mistake: the intent was this only impacted LLVM/JSON output. I didn't realise the code was shared with GNU style. @feg208, could you revert and look at redoing this to not impact GNU output, please? (GNU output should generally match GNU readelf output, for compatibility).

Aside: @kraj, if there are multiple e.g. NEEDED entries in an ELF, does GNU readelf produce separate entries, each with a single-element list? If so, this feels like a bug in the GNU readelf tool to me, and I wonder if we could get the behaviour changed there to make more sense.

**Comment by kraj** [comment]
> > The output now differs from what GNU readelf/objdump generates. There is a tool in yocto which processes `SONAME` entry to detect the name of the shared object and now that test fails and several packages fail when using llvm-readelf, I wonder if there are more such tools post processing ELF files, they all will have similar issues.
> 
> Ah, sorry, that was my mistake: the intent was this only impacted LLVM/JSON output. I didn't realise the code was shared with GNU style. @feg208, could you revert and look at redoing this to not impact GNU output, please? (GNU output should generally match GNU readelf output, for compatibility).
> 
> Aside: @kraj, if there are multiple e.g. NEEDED entries in an ELF, does GNU readelf produce separate entries, each with a single-element list? If so, this feels like a bug in the GNU readelf tool to me, and I wonder if we could get the behaviour changed there to make more sense.

It seems there is one entry per line
```
 0x0000000000000001 (NEEDED)             Shared library: [libncursesw.so.6]
 0x0000000000000001 (NEEDED)             Shared library: [libc.so.6]
 0x000000000000000e (SONAME)             Library soname: [libreadline.so.8]
```

**Comment by glandium** [comment]
> Ah, sorry, that was my mistake: the intent was this only impacted LLVM/JSON output. I didn't realise the code was shared with GNU style. @feg208, could you revert and look at redoing this to not impact GNU output, please? (GNU output should generally match GNU readelf output, for compatibility).

Can this be reverted?
 
> Aside: @kraj, if there are multiple e.g. NEEDED entries in an ELF, does GNU readelf produce separate entries, each with a single-element list? If so, this feels like a bug in the GNU readelf tool to me, and I wonder if we could get the behaviour changed there to make more sense.

I don't think the brackets in the readelf output are ever to be interpreted as "this is a list of multiple values".

**Comment by jh7370** [comment]
> > Ah, sorry, that was my mistake: the intent was this only impacted LLVM/JSON output. I didn't realise the code was shared with GNU style. @feg208, could you revert and look at redoing this to not impact GNU output, please? (GNU output should generally match GNU readelf output, for compatibility).
> 
> Can this be reverted?

Feel free to do so, since @feg208 has not seen/has ignored my previous request. I'd still like the additional testing, but that can be relanded separately.

> > Aside: @kraj, if there are multiple e.g. NEEDED entries in an ELF, does GNU readelf produce separate entries, each with a single-element list? If so, this feels like a bug in the GNU readelf tool to me, and I wonder if we could get the behaviour changed there to make more sense.
> 
> I don't think the brackets in the readelf output are ever to be interpreted as "this is a list of multiple values".

Thanks. I found it confusing in llvm-readobj LLVM style output, but less so in the GNU style output.

**Pull request merged**
