### PR TITLE
Revert "[OpenMP][TR12] change property of map-type modifier."

### PR DESCRIPTION
**Pull request by vitalybuka**
Breaks https://lab.llvm.org/buildbot/#/builders/5/builds/43086/steps/9/logs/stdio

Reverts llvm/llvm-project#90499

### CODE REVIEW

**Comment by jyu2-git** [comment]
I already has patch in https://github.com/llvm/llvm-project/pull/90800 waiting for test to finish.

**Comment by vitalybuka** [comment]
> I already has patch in #90800 waiting for test to finish.

Fix forward is good for something < 1H, but looks like you started 19H ago.
Such cases must be reverted and then fixed.

How long do you need?

**Comment by vitalybuka** [comment]
> How long do you need?

Looks like it's landed.
Thanks!

**Comment by vitalybuka** [comment]
Oh, it's not landed. I looked at wrong PR. Lets revert if it can't be landed soon.

**Comment by jyu2-git** [comment]
> > How long do you need?
> 
> Looks like it's landed. Thanks!

I don't know.  I start yesterday.  But it is still not finished.  I cannot land without test finish.

**Comment by jyu2-git** [comment]
> Oh, it's not landed. I looked at wrong PR. Lets revert if it can't be landed soon.

Okay with me.

**Comment by vitalybuka** [comment]
> BTW, Hi @vitalybuka, do you know how to reproduce the problem with sanitizer build? Thanks.

There is a basic instruction, should work with Linux https://github.com/google/sanitizers/wiki/SanitizerBotReproduceBuild
I guess this issue should be detectable with appropriate `assert(val > a && val <= b)` a the point of the report.

**Comment by vitalybuka** [comment]
> > BTW, Hi @vitalybuka, do you know how to reproduce the problem with sanitizer build? Thanks.
> 
> There is a basic instruction, should work with Linux https://github.com/google/sanitizers/wiki/SanitizerBotReproduceBuild I guess this issue should be detectable with appropriate `assert(val > a && val <= b)` a the point of the report.

Still fails after rebase https://lab.llvm.org/buildbot/#/builders/5/builds/43115

**Comment by jyu2-git** [comment]
Thanks @vitalybuka for merge this patch for me.  I did see the TEST 'Clang :: OpenMP/target_ast_print.cpp' FAILED .  I am fixing.

**Pull request merged**
