### PR TITLE
[RemoveDIs] Update DIBuilder C API with DbgRecord functions [2/2]

### PR DESCRIPTION
**Pull request by OCHyams**
Follow on from #84915 which adds the DbgRecord function variants.

Update the LLVMDIBuilderInsert... functions to insert DbgRecords instead of debug intrinsics.

    LLVMDIBuilderInsertDeclareBefore
    LLVMDIBuilderInsertDeclareAtEnd
    LLVMDIBuilderInsertDbgValueBefore
    LLVMDIBuilderInsertDbgValueAtEnd

Calling these functions will now cause an assertion if the module is in the
wrong debug info mode. They should only be used when the module is in "new
debug mode".

Use LLVMIsNewDbgInfoFormat to query and LLVMSetIsNewDbgInfoFormat to change the
debug info format of a module.

Please see https://llvm.org/docs/RemoveDIsDebugInfo.html#c-api-change
(RemoveDIsDebugInfo.md) for more info.

### CODE REVIEW

**Review by SLTozer — COMMENTED** [review]
Code changes LGTM, though most of the line changes in here look like fixing up things from the previous patch rather than relating to the functional change - the patch is relatively small regardless.

Just to confirm, the intent is that after this LLVM's DIBuilder (for both C++ and C APIs) will always create debug record modules, regardless of flags passed?

**Comment by OCHyams** [comment]
> Just to confirm, the intent is that after this LLVM's DIBuilder (for both C++ and C APIs) will always create debug record modules, regardless of flags passed?

Yeah that's right. For now it's up to users of the API to either continue to use `LLVMDIBuilderInsert...` functions, which will now insert DbgRecords, or to call the `Intrinsic` versions explicitly to insert debug intrinsics.

`LLVMIsNewDbgInfoFormat` and `LLVMSetIsNewDbgInfoFormat` can be used to query and change the debug info format for the module too.

In the future, we'll remove all the explicit function versions that have been added, so that the only functions that remain are the originals (and they'll be emitting DbgRecords, because there will be no debug intrinsic alternative).

**Review by SLTozer — COMMENTED** [review]
I think we should probably add comments to the default versions to help out anyone downstream who gets bitten by this change - a link to the relevant RemoveDIs doc section and/or instructions on how to fix it (use this function to detect which mode you're in and then call X or Y depending on that) would be good; probably the same should appear in the commit message.

**Comment by OCHyams** [comment]
SGTM, done (& patch summary updated). And fixed up some "typos" in the comments I added in part 1.

**Review by SLTozer — APPROVED** [review]
TYVM, LGTM.

**Comment by OCHyams** [comment]
Thanks @SLTozer - are you happy with the change I just made to the asserts, imo these are clearer.

**Comment by SLTozer** [comment]
SGTM, I'd like to add more detail but I don't think we can fit it all in an assert; optionally, a comment line above to the effect of "Verify we have the right format, see `LLVMIsNewDbgInfoFormat`" or such. Worth demonstrating extra caution here, since we're potentially impacting people who're disconnected from the RemoveDI work.

**Pull request merged**
