### PR TITLE
[M68k] implement large code model

### LINKED ISSUE #106208: [M68k] implement large code model
The currently supported code models all assume that any symbol may be reached with a 16bit offset, however, m68k-based microcontrollers may have ROM/flash (where .text and .rodata are usually mapped) and RAM (where .data and .bss are usually mapped) at greatly differing address ranges (> 16bit). This makes it necessary to support a large code model that uses absolute or GOT-relative addressing modes for these targets.

### PR DESCRIPTION
**Pull request by TechnoElf**
Fixes #106208.

### CODE REVIEW

**Review by mshockwave — COMMENTED** [review]
Thanks for the patch! could you add some tests?

**Comment by TechnoElf** [comment]
Done.

**Comment by TechnoElf** [comment]
The pipeline is failing due to a timeout in an LLDB test: `lldb-api :: functionalities/fork/concurrent_vfork/TestConcurrentVFork.py`. I don't really understand how that's related to the change though...

**Comment by TechnoElf** [comment]
ping @mshockwave @0x59616e

**Review by mshockwave — APPROVED** [review]
LGTM. Thanks!

**Comment by knickish** [comment]
Are there any blockers to getting this in? Would be very helpful

**Pull request merged**
