### PR TITLE
[InstCombine] Canonicalize `and(zext(A), B)` into `select A, B & 1, 0`

### LINKED ISSUE #28612: recognize 'and' of disjoint ranges
|  |  |
| --- | --- |
| Bugzilla Link | [28238](https://llvm.org/bz28238) |
| Version | trunk |
| OS | All |
| CC | @manueljacob,@sanjoy |

## Extended Description 
Spinning this off from bug 27869 (and may have a different solution than bug 28221):

int f(int i) {
  return (i == 0) & (i >> 31);
}

'i' can't be 0 and have a bit set, so this should return 0.

$ ./clang -O1 sneaky_icmp.c -S -o - -emit-llvm
...
define i32 @&#8203;f(i32 %i) {
  %cmp = icmp eq i32 %i, 0
  %conv = zext i1 %cmp to i32
  %shr = ashr i32 %i, 31
  %and = and i32 %conv, %shr
  ret i32 %and
}

### LINKED ISSUE #66606: [InstCombine] `a & !a` is not optimized
https://alive2.llvm.org/ce/z/e4RhjY
```llvm
define i32 @src(i32 %0) {
%1:
  %2 = icmp eq i32 %0, 0
  %3 = zext i1 %2 to i32
  %4 = and i32 %3, %0
  ret i32 %4
}
=>
define i32 @tgt(i32 %0) {
%1:
  ret i32 0
}
Transformation seems to be correct!
```

Simple reproducer:
https://godbolt.org/z/YP7nEofeo
```c
int foo (int a)
{
   return (a & !a);
}
```

FYI
https://gcc.gnu.org/bugzilla/show_bug.cgi?id=111431

### LINKED ISSUE #66733: `(a == 0) & (((short)a) >= 0)` is not always optimized to just `a == 0`
Take:
```
int f(int a)
{
        short b = a;
        _Bool t = a == 0;
        _Bool t1 = b >= 0;
        return t & t1;
}
void f0(int a, int *b)
{
        *b= f(a) != 0;
}
void f01(int a, int *b)
{
        _Bool c = f(a);
        *b= c;
}
void f01_(int a, _Bool *b)
{
        _Bool c = f(a);
        *b= c;
}
_Bool f00(int a)
{
        return f(a);
}
void f00_(int a, _Bool *b)
{
        _Bool c = f00(a);
        *b= c;
}
_Bool f1(int a)
{
        _Bool t = a == 0;
        short t1 = a;
        _Bool t2 = t1 >= 0;
        return t & t2;
}
```
`f`, `f00` and `f1` should all produce the same optimized code of just `a == 0;` While `f0`, `f01`, `f01_` and `f00_` all should produce `*b = a == 0;` But currently `f`, `f0`, f01` all still have the short comparison `>=` being included.

I am filing this because the way LLVM is acting here seems like `((short)a) < 0` is being transformed too early to `(a >> 15) & 1` and then never going back sometimes. This happens on x86_64, aarch64, riscv and BPF targets.

### PR DESCRIPTION
**Pull request by dtcxzyw**
This patch canonicalizes the pattern `and(zext(A), B)` into `select A, B & 1, 0`. Thus, we can reuse transforms `select B == even, B & 1, 0 -> 0` and  `select B == odd, B & 1, 0 -> zext(B == odd)` in `InstCombine`.
It is an alternative to #66676. 
Alive2: https://alive2.llvm.org/ce/z/598phE
Fixes #66733.
Fixes #66606.
Fixes #28612.

### CODE REVIEW

**Comment by DianQK** [comment]
We should use rebase instead of merge.
I recommend force push to change the code before the review starts.

**Comment by dtcxzyw** [comment]
> We should use rebase instead of merge. And I recommend force push to change the code before the review starts.

I am confused with the LLVM GitHub user guide. I witnessed someone mess up by doing rebase + force push.
Examples: #65853 #65543 #65535

**Comment by nikic** [comment]
I think this is the right canonicalization at the IR level, as select allows better analysis than zext(icmp). However, this seems to be universally worse for the backend: https://llvm.godbolt.org/z/Yh7brfc8b So I think we would need an SDAG undo transform. Interestingly, this already happens for riscv64, so maybe the undo transform already exists but is not enabled for all target.

@goldsteinn What do you think?

**Comment by sftlbcn** [comment]
this also fixes #28612

**Comment by goldsteinn** [comment]
> I think this is the right canonicalization at the IR level, as select allows better analysis than zext(icmp). However, this seems to be universally worse for the backend: https://llvm.godbolt.org/z/Yh7brfc8b So I think we would need an SDAG undo transform. Interestingly, this already happens for riscv64, so maybe the undo transform already exists but is not enabled for all target.
> 
> @goldsteinn What do you think?

Yeah, I think I agree, I looked a bit around DAGCombiner and can't find where `risv` does this but pretty sure its in the `RISCV` target codes as commenting out the entirety of `visitSelect`, `visitSelect_CC`, and `visitAndLike` doesn't change the `riscv` codegen.

I'd say since we also do:
```
  %zx = sext i1 %x to i32
  %r = and i32 %zx, %y
```
to
```
  %r = select i1 %x, i32 %masked, i32 0
```
This makes sense in that context.

I'll throw up a patch shortly to cover this case in the backend.

**Comment by goldsteinn** [comment]
Created: https://github.com/llvm/llvm-project/pull/66793 which fixes the backend regression this can cause.

**Comment by nikic** [comment]
You might want to check whether this also fixes https://github.com/llvm/llvm-project/pull/66740 and if so add a test.

**Review by nikic — APPROVED** [review]
LGTM

**Comment by dtcxzyw** [comment]
> You might want to check whether this also fixes #66740 and if so add a test.

Confirmed. I have added a pre-commit test for 66733 in 1a73a6b80b54cd23ee8380c6fa3304847e5cb5d1.

**Comment by dtcxzyw** [comment]
To avoid backend regressions, I will merge this PR after #66793.

**Pull request merged**
