### PR TITLE
[dsymutil] Remove support for obfuscated bitcode

### PR DESCRIPTION
**Pull request by JDevlieghere**
Remove support for obfuscated bitcode in dsymutil and the DWARF linker. We no longer support bitcode submissions and the obfuscation support has been removed from the rest of the compiler.

rdar://123863918

### CODE REVIEW

**Review by avl-llvm — APPROVED** [review]
LGTM!

**Comment by avillega** [comment]
@JDevlieghere This change seems to be breaking our builds with the following error
```
tools/bolt/lib/Rewrite/CMakeFiles/LLVMBOLTRewrite.dir/DWARFRewriter.cpp.o -MF tools/bolt/lib/Rewrite/CMakeFiles/LLVMBOLTRewrite.dir/DWARFRewriter.cpp.o.d -o tools/bolt/lib/Rewrite/CMakeFiles/LLVMBOLTRewrite.dir/DWARFRewriter.cpp.o -c /b/s/w/ir/x/w/llvm-llvm-project/bolt/lib/Rewrite/DWARFRewriter.cpp
/b/s/w/ir/x/w/llvm-llvm-project/bolt/lib/Rewrite/DWARFRewriter.cpp:288:9: error: no matching constructor for initialization of 'DwarfStreamer'
  288 |       : DwarfStreamer(OutFileType, OutFile, Translator, Warning),
      |         ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/b/s/w/ir/x/w/llvm-llvm-project/llvm/include/llvm/DWARFLinker/Classic/DWARFStreamer.h:46:3: note: candidate constructor not viable: requires 3 arguments, but 4 were provided
   46 |   DwarfStreamer(DWARFLinkerBase::OutputFileType OutFileType,
      |   ^             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   47 |                 raw_pwrite_stream &OutFile,
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~
   48 |                 DWARFLinkerBase::MessageHandlerTy Warning)
      |                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/b/s/w/ir/x/w/llvm-llvm-project/llvm/include/llvm/DWARFLinker/Classic/DWARFStreamer.h:44:7: note: candidate constructor (the implicit copy constructor) not viable: requires 1 argument, but 4 were provided
   44 | class DwarfStreamer : public DwarfEmitter {
      |       ^~~~~~~~~~~~~
```
Could you revert and then fix forward? thanks!

**Comment by JDevlieghere** [comment]
@avillega Thanks for the revert, I got a handful of buildbot emails but none of the failures were related to my change. I'll take a look before I reland.

**Comment by JDevlieghere** [comment]
Looks like the BOLT issue is fixed by #85818. Verifying locally before I reland the change.

**Pull request merged**
