### PR TITLE
[LegalizeDAG] PromoteNode FABS: Override promotion with clear sign bit

### LINKED ISSUE #104915: [InstCombine][X86] LLVM >= 18 folding bitcast -> and -> bitcast to `@llvm.fabs.f16` generates call to `__extendhfsf2`
https://godbolt.org/z/on6Pj6Tsc

Starting from https://github.com/llvm/llvm-project/commit/5c0da5839de1bdc08f411a04305a9bdadf538ad5, InstCombine transforms this IR:

```llvm
define linkonce_odr hidden noundef half @_Float16 __llvm_libc_20_0_0_git::fputil::abs<_Float16, 0>(_Float16)(half noundef %x) local_unnamed_addr #1 comdat {
entry:
  %0 = bitcast half %x to i16
  %1 = and i16 %0, 32767
  %2 = bitcast i16 %1 to half
  ret half %2
}
```

into:

```llvm
define linkonce_odr hidden noundef half @_Float16 __llvm_libc_20_0_0_git::fputil::abs<_Float16, 0>(_Float16)(half noundef %x) local_unnamed_addr #1 comdat {
entry:
  %0 = call half @llvm.fabs.f16(half %x)
  ret half %0
}
```

On x86, when AVX-512 FP16 is not available, this generates something like:

```asm
.LCPI0_0:
        .long   0x7fffffff
__llvm_libc_20_0_0_git::fabsf16(_Float16):
        push    rbp
        mov     rbp, rsp
        call    __extendhfsf2@PLT
        vbroadcastss    xmm1, dword ptr [rip + .LCPI0_0]
        vandps  xmm0, xmm0, xmm1
        call    __truncsfhf2@PLT
        pop     rbp
        ret
```

whereas with LLVM 16, `bitcast` -> `and` -> `bitcast` generates something like:

```asm
__llvm_libc_20_0_0_git::fabsf16(_Float16):
        push    rbp
        mov     rbp, rsp
        vpextrw eax, xmm0, 0
        and     eax, 32767
        vpinsrw xmm0, xmm0, eax, 0
        pop     rbp
        ret
```

Related:

- https://github.com/llvm/llvm-project/issues/104914
- https://github.com/llvm/llvm-project/pull/104869#issuecomment-2297563670

cc @arsenm @lntue

### PR DESCRIPTION
**Pull request by v01dXYZ**
Conditionally to the same sized integer type being legal.

For example, for f16, if i16 is legal, bitcast to i16, clear the sign bit and bitcast back to f16.

Fixes #104915

### CODE REVIEW

**Comment by v01dXYZ** [comment]
I've got some problems with updating the NVPTX tests as the tests use `asm-verbose=false` but `UpdateTestChecks/asm.py` uses `-- End Function`.

**Comment by topperc** [comment]
Why not use Expand instead of Promote for ISD::FABS in that case? It already has the code for bitcasting to int.

**Comment by v01dXYZ** [comment]
@topperc that's a valid point (even though I thought that expand means using smaller types to compute the result).

**Comment by topperc** [comment]
> @topperc that's a valid point (even though I thought that expand means using smaller types to compute the result).

That's what Expand means for LegalizeTypes. For LegalizeDAG, Expand just means to emulate it any way we can.

**Comment by v01dXYZ** [comment]
@topperc Thanks. I'll instead publish a PR for the targets that have `i16` and set `FABS/f16` action to `Promote`.

I'll put back this PR to Draft.

**Comment by v01dXYZ** [comment]
This PR has been replaced by https://github.com/llvm/llvm-project/pull/106153 which does the same without adding a special case for `PromoteNode` (and virtually no code).

**Comment by arsenm** [comment]
This should be resurrected. The promotion to float through fpext is simply wrong. There should be no fall through for it, it should fail

**Pull request closed without merging**
