### PR TITLE
[PowerPC][NFC] Add base test case for small-local-dynamic-tls on AIX

### PR DESCRIPTION
**Pull request by orcguru**

### CODE REVIEW

**Comment by orcguru** [comment]
@chenzheng1030 Per your request, I have reduced some test cases. I also added missing one which will demonstrate "fixup_ppc_half16ds" related code change. Please let me know if test cases need be reduced further. Thank you!

**Review by chenzheng1030 — COMMENTED** [review]
See https://llvm.org/docs/TestingGuide.html#best-practices-for-regression-tests

I think we should avoid any unnamed instructions in the input IR.

Since the files are too big, could you please simply show how do you arrange these tests?  Thanks a lot.

**Comment by orcguru** [comment]
> See https://llvm.org/docs/TestingGuide.html#best-practices-for-regression-tests
> 
> I think we should avoid any unnamed instructions in the input IR.
> 
> Since the files are too big, could you please simply show how do you arrange these tests? Thanks a lot.

Updated. Thank you!

**Review by chenzheng1030 — APPROVED** [review]
Thanks for the change! LGTM.

**Pull request merged**
