### PR TITLE
Fix CMake dependencies on mlir-linalg-ods-yaml-gen

### PR DESCRIPTION
**Pull request by RoboTux**
Fix a number of dependencies issue to build mlir-linalg-ods-yaml-gen
host binary which make a cross-build using the Make generator fail.
Namely:

- do not use binary path for the custom target created when
  LLVM_USE_HOST_TOOLS is true;
- use target name instead of name of variable holding the target name
  for add_custom_target and set_target_properties in setup_host_tool();
- remove dependency on target defined in different directory in
  add_linalg_ods_yaml_gen() since add_custom_target DEPENDS can only be
  used on "files and outputs of custom commands created with
  add_custom_command() command calls in the same directory";
- remove unneeded dependency on ${MLIR_LINALG_ODS_YAML_GEN_EXE}, the
  target dependency will ensure the binary will be built.

Note that we keep using ${MLIR_LINALG_ODS_YAML_GEN_EXE} in the COMMAND
rather than use ${MLIR_LINALG_ODS_YAML_GEN_TARGET} because when
LLVM_NATIVE_TOOL_DIR is used the latter is an empty string.

Testing-wise, all three codepaths in get_host_tool_path() were tested
with both GNU Make and Ninja generators:
- cross-compiling with LLVM_NATIVE_TOOL_DIR checks the if path;
- cross-compiling without LLVM_NATIVE_TOOL_DIR checks the elseif path;
- native build without LLVM_NATIVE_TOOL_DIR checks the else path.

### CODE REVIEW

**Comment by igorkudrin** [comment]
Changes in `AddLLVM.cmake` LGTM. I can't say anything about the other part.

**Comment by omjavaid** [comment]
Apparently these changes look fine to me. But someone aware with Dialects/Linalg project should approve.

**Review by stellaraccident — APPROVED** [review]
This looks ok to me. The way it was never looked right to me. 

(We're trying to remove this piece entirely but it will take some time)

**Comment by tbaederr** [comment]
This commit causes these errors when I configure:

```console
-- Clang version: 20.0.0git
CMake Error at cmake/modules/AddLLVM.cmake:2635 (add_custom_target):
  add_custom_target called with invalid target name
  "/home/tbaeder/code/llvm-project/build/NATIVE/bin/clang".  Target names may
  not contain a slash.  Use ADD_CUSTOM_COMMAND to generate files.
Call Stack (most recent call first):
  /home/tbaeder/code/llvm-project/clang/tools/driver/CMakeLists.txt:41 (setup_host_tool)


CMake Error at cmake/modules/AddLLVM.cmake:2637 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  /home/tbaeder/code/llvm-project/build/NATIVE/bin/clang
Call Stack (most recent call first):
  /home/tbaeder/code/llvm-project/clang/tools/driver/CMakeLists.txt:41 (setup_host_tool)


CMake Error at cmake/modules/AddLLVM.cmake:2635 (add_custom_target):
  add_custom_target called with invalid target name
  "/home/tbaeder/code/llvm-project/build/NATIVE/bin/llvm-as".  Target names
  may not contain a slash.  Use ADD_CUSTOM_COMMAND to generate files.
Call Stack (most recent call first):
  tools/llvm-as/CMakeLists.txt:15 (setup_host_tool)


CMake Error at cmake/modules/AddLLVM.cmake:2637 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  /home/tbaeder/code/llvm-project/build/NATIVE/bin/llvm-as
Call Stack (most recent call first):
  tools/llvm-as/CMakeLists.txt:15 (setup_host_tool)


CMake Error at cmake/modules/AddLLVM.cmake:2635 (add_custom_target):
  add_custom_target called with invalid target name
  "/home/tbaeder/code/llvm-project/build/NATIVE/bin/llvm-link".  Target names
  may not contain a slash.  Use ADD_CUSTOM_COMMAND to generate files.
Call Stack (most recent call first):
  tools/llvm-link/CMakeLists.txt:21 (setup_host_tool)


CMake Error at cmake/modules/AddLLVM.cmake:2637 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  /home/tbaeder/code/llvm-project/build/NATIVE/bin/llvm-link
Call Stack (most recent call first):
  tools/llvm-link/CMakeLists.txt:21 (setup_host_tool)


CMake Error at cmake/modules/AddLLVM.cmake:2635 (add_custom_target):
  add_custom_target called with invalid target name
  "/home/tbaeder/code/llvm-project/build/NATIVE/bin/llvm-nm".  Target names
  may not contain a slash.  Use ADD_CUSTOM_COMMAND to generate files.
Call Stack (most recent call first):
  tools/llvm-nm/CMakeLists.txt:29 (setup_host_tool)


CMake Error at cmake/modules/AddLLVM.cmake:2637 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  /home/tbaeder/code/llvm-project/build/NATIVE/bin/llvm-nm
Call Stack (most recent call first):
  tools/llvm-nm/CMakeLists.txt:29 (setup_host_tool)


CMake Error at cmake/modules/AddLLVM.cmake:2635 (add_custom_target):
  add_custom_target called with invalid target name
  "/home/tbaeder/code/llvm-project/build/NATIVE/bin/llvm-readobj".  Target
  names may not contain a slash.  Use ADD_CUSTOM_COMMAND to generate files.
Call Stack (most recent call first):
  tools/llvm-readobj/CMakeLists.txt:33 (setup_host_tool)


CMake Error at cmake/modules/AddLLVM.cmake:2637 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  /home/tbaeder/code/llvm-project/build/NATIVE/bin/llvm-readobj
Call Stack (most recent call first):
  tools/llvm-readobj/CMakeLists.txt:33 (setup_host_tool)


CMake Error at cmake/modules/AddLLVM.cmake:2635 (add_custom_target):
  add_custom_target called with invalid target name
  "/home/tbaeder/code/llvm-project/build/NATIVE/bin/opt".  Target names may
  not contain a slash.  Use ADD_CUSTOM_COMMAND to generate files.
Call Stack (most recent call first):
  tools/opt/CMakeLists.txt:53 (setup_host_tool)


CMake Error at cmake/modules/AddLLVM.cmake:2637 (set_target_properties):
  set_target_properties Can not find target to add properties to:
  /home/tbaeder/code/llvm-project/build/NATIVE/bin/opt
Call Stack (most recent call first):
  tools/opt/CMakeLists.txt:53 (setup_host_tool)


-- Configuring incomplete, errors occurred!
```
Reverting the patch makes things work again.

**Comment by RoboTux** [comment]
@tbaederr Was it an incremental build? With this patch the target name should be ${tool_name}, i.e. clang. However it is set in that way:
`  set(${target_var_name} "${target_name}" CACHE STRING "")`
So I wonder if you had an old value in the cache.

**Comment by tbaederr** [comment]
Yes, it was my  local build. A `ninja clean` didn't help either, but I guess that doesn't nuke the cache(?)

**Comment by RoboTux** [comment]
I'm guessing it does not. I could change the variable to not be a cache variable. @mstorsjo Is there a reason why get_host_tool_path() sets the executable and target variables as cache? It seems to me to be build system internals.

**Comment by mstorsjo** [comment]
> I'm guessing it does not. I could change the variable to not be a cache variable. @mstorsjo Is there a reason why get_host_tool_path() sets the executable and target variables as cache? It seems to me to be build system internals.

Earlier, if users wanted to use a prebuilt e.g. `llvm-tblgen` (e.g. when cross compiling), they'd set `-DLLVM_TBLGEN=/path/to/binary` - so I think that's why those variables traditionally were cache variables. Since introducing `LLVM_NATIVE_TOOL_DIR` there's less reason to set those individually, but I guess we haven't officially deprecated/removed the old way of doing that.

**Comment by RoboTux** [comment]
> > I'm guessing it does not. I could change the variable to not be a cache variable. @mstorsjo Is there a reason why get_host_tool_path() sets the executable and target variables as cache? It seems to me to be build system internals.
> 
> Earlier, if users wanted to use a prebuilt e.g. `llvm-tblgen` (e.g. when cross compiling), they'd set `-DLLVM_TBLGEN=/path/to/binary` - so I think that's why those variables traditionally were cache variables. Since introducing `LLVM_NATIVE_TOOL_DIR` there's less reason to set those individually, but I guess we haven't officially deprecated/removed the old way of doing that.

Are you talking about LLVM_TABLEGEN? That seems like a different thing because if I try to trace all calls to get_host_tool_path it seems the cache variable it looks for are named:
- clang_target
- clang_tidy_confusable_chars_gen_target
- llvm-as_target
- llvm_as_target
- llvm-link_target
- llvm_link_target
- llvm_nm_target
- llvm_readobj_target
- opt_target
- prepare_builtins_target
- MLIR_LINALG_ODS_YAML_GEN_TARGET

I'm tempted to make it a non cache variable because the only alternative I can think of is to tell people to nuke their existing build if they encounter issues.

**Comment by mstorsjo** [comment]
> > > I'm guessing it does not. I could change the variable to not be a cache variable. @mstorsjo Is there a reason why get_host_tool_path() sets the executable and target variables as cache? It seems to me to be build system internals.
> > 
> > 
> > Earlier, if users wanted to use a prebuilt e.g. `llvm-tblgen` (e.g. when cross compiling), they'd set `-DLLVM_TBLGEN=/path/to/binary` - so I think that's why those variables traditionally were cache variables. Since introducing `LLVM_NATIVE_TOOL_DIR` there's less reason to set those individually, but I guess we haven't officially deprecated/removed the old way of doing that.
> 
> Are you talking about LLVM_TABLEGEN? That seems like a different thing because if I try to trace all calls to get_host_tool_path it seems the cache variable it looks for are named:

Yes, that's the one I meant. Sorry, I didn't have time to dig in closer what this really was touching.

> * clang_target
> * clang_tidy_confusable_chars_gen_target
> * llvm-as_target
> * llvm_as_target
> * llvm-link_target
> * llvm_link_target
> * llvm_nm_target
> * llvm_readobj_target
> * opt_target
> * prepare_builtins_target
> * MLIR_LINALG_ODS_YAML_GEN_TARGET
> 
> I'm tempted to make it a non cache variable because the only alternative I can think of is to tell people to nuke their existing build if they encounter issues.

Indeed, I don't see any reason to keep those variables as CACHE variables.

**Comment by RoboTux** [comment]
I've respinned the PR to make cache variable regular variable instead in https://github.com/llvm/llvm-project/pull/112224

**Pull request merged**
