### PR TITLE
[Sema] Fix crash on invalid code with parenthesized aggregate initialization

### LINKED ISSUE #76228: Clang crashes on invalid code in C++20 mode
Input:
```
class a
struct b {
  c;
  a e;
  d() {
    b( {
    }
  }
}
```
Crashes when compiled with `clang++ -std=c++20` and produces the following stack trace (when assertions are enabled):
```
clang++: /root/llvm-project/clang/lib/Sema/SemaLookup.cpp:3346: clang::Sema::SpecialMemberOverloadResult clang::Sema::LookupSpecialMember(clang::CXXRecordDecl*, clang::Sema::CXXSpecialMember, bool, bool, bool, bool, bool): Assertion `CanDeclareSpecialMemberFunction(RD) && "doing special member lookup into record that isn't fully complete"' failed.
...
1.	<source>:8:3: current parser token '}'
2.	<source>:2:1: parsing struct/union/class body 'b'
3.	<source>:5:7: parsing function body 'b::d'
4.	<source>:5:7: in compound statement ('{}')
...
 #9 0x0000000006780474 clang::Sema::LookupSpecialMember(clang::CXXRecordDecl*, clang::Sema::CXXSpecialMember, bool, bool, bool, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6780474)
#10 0x00000000067808a7 clang::Sema::LookupDefaultConstructor(clang::CXXRecordDecl*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x67808a7)
#11 0x0000000006721068 TryValueInitialization(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, clang::InitializationSequence&, clang::InitListExpr*) SemaInit.cpp:0:0
#12 0x0000000006727ee7 clang::InitializationSequence::InitializeFrom(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6727ee7)
#13 0x0000000006726960 TryOrBuildParenListInitialization(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::ArrayRef<clang::Expr*>, clang::InitializationSequence&, bool, clang::ActionResult<clang::Expr*, true>*)::'lambda'(clang::InitializedEntity const&, clang::InitializationKind const&, clang::Expr*, clang::Expr**)::operator()(clang::InitializedEntity const&, clang::InitializationKind const&, clang::Expr*, clang::Expr**) const SemaInit.cpp:0:0
#14 0x0000000006727747 TryOrBuildParenListInitialization(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::ArrayRef<clang::Expr*>, clang::InitializationSequence&, bool, clang::ActionResult<clang::Expr*, true>*) SemaInit.cpp:0:0
#15 0x0000000006729380 clang::InitializationSequence::InitializeFrom(clang::Sema&, clang::InitializedEntity const&, clang::InitializationKind const&, llvm::MutableArrayRef<clang::Expr*>, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6729380)
#16 0x0000000006642a01 clang::Sema::BuildCXXTypeConstructExpr(clang::TypeSourceInfo*, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6642a01)
#17 0x00000000066cd1cd clang::Sema::ActOnCXXTypeConstructExpr(clang::OpaquePtr<clang::QualType>, clang::SourceLocation, llvm::MutableArrayRef<clang::Expr*>, clang::SourceLocation, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x66cd1cd)
...
```

See https://gcc.godbolt.org/z/jadhdMxjf

### PR DESCRIPTION
**Pull request by ilya-biryukov**
Fixes #76228.
Use the same logic as braced init lists, also adds a test that puts incomplete types in various positions to check for regressions in the future.

### CODE REVIEW

**Review by hokein — APPROVED** [review]
Thanks, looks good.

**Review by shafik — COMMENTED** [review]
This is missing a release note.

**Comment by vitalybuka** [comment]
Breaks multiple bots
https://lab.llvm.org/buildbot/#/builders/168/builds/17604
https://lab.llvm.org/buildbot/#/builders/74/builds/24426
https://lab.llvm.org/buildbot/#/builders/239/builds/4971
and some others

**Comment by vvereschaka** [comment]
these changes break the libc++ tests - `llvm-libc++-static.cfg.in::transform_error.mandates.verify.cpp`

```
# .---command stderr------------
# | error: 'expected-error' diagnostics expected but not seen: 
# |   File * Line * (directive at C:\buildbot\as-builder-2\x-aarch64\llvm-project\libcxx\test\libcxx\utilities\expected\expected.void\transform_error.mandates.verify.cpp:49): {{(excess elements in struct initializer|no matching constructor for initialization of)}}{{.*}}
# |   File * Line * (directive at C:\buildbot\as-builder-2\x-aarch64\llvm-project\libcxx\test\libcxx\utilities\expected\expected.void\transform_error.mandates.verify.cpp:53): {{(excess elements in struct initializer|no matching constructor for initialization of)}}{{.*}}
# |   File * Line * (directive at C:\buildbot\as-builder-2\x-aarch64\llvm-project\libcxx\test\libcxx\utilities\expected\expected.void\transform_error.mandates.verify.cpp:61): {{(excess elements in struct initializer|no matching constructor for initialization of)}}{{.*}}
# |   File * Line * (directive at C:\buildbot\as-builder-2\x-aarch64\llvm-project\libcxx\test\libcxx\utilities\expected\expected.void\transform_error.mandates.verify.cpp:63): {{(excess elements in struct initializer|no matching constructor for initialization of)}}{{.*}}
# |   File * Line * (directive at C:\buildbot\as-builder-2\x-aarch64\llvm-project\libcxx\test\libcxx\utilities\expected\expected.void\transform_error.mandates.verify.cpp:70): {{(excess elements in struct initializer|no matching constructor for initialization of)}}{{.*}}
# |   File * Line * (directive at C:\buildbot\as-builder-2\x-aarch64\llvm-project\libcxx\test\libcxx\utilities\expected\expected.void\transform_error.mandates.verify.cpp:72): {{(excess elements in struct initializer|no matching constructor for initialization of)}}{{.*}}
# |   File * Line * (directive at C:\buildbot\as-builder-2\x-aarch64\llvm-project\libcxx\test\libcxx\utilities\expected\expected.void\transform_error.mandates.verify.cpp:79): {{(excess elements in struct initializer|no matching constructor for initialization of)}}{{.*}}
# |   File * Line * (directive at C:\buildbot\as-builder-2\x-aarch64\llvm-project\libcxx\test\libcxx\utilities\expected\expected.void\transform_error.mandates.verify.cpp:81): {{(excess elements in struct initializer|no matching constructor for initialization of)}}{{.*}}
# | 8 errors generated.
# `-----------------------------
# error: command failed with exit status: 1

```

https://lab.llvm.org/buildbot/#/builders/119/builds/16381
https://lab.llvm.org/buildbot/#/builders/60/builds/15226

**Comment by ilya-biryukov** [comment]
Thanks for reverting it and sorry for the trouble, I will make sure to check libc++ tests before a reland.
Clang does report less errors now, but that's expected. The errors were spurious, caused by Clang trying to initialize an "invalid" class (more details below in case you're interested).

Failed `static_assert` is what made the class invalid in the first place and Clang fails parenthesized initialization of such classes early now. We should not do parenthesized initialization here as it should only be applied to aggregates, this class has constructors and is not an aggregate in the first place. The only reason we attempted aggregate init is because invalid classes are left internally in inconsistent states sometimes (there are many reasons why class is invalid). So less errors is better here, they were only adding noise and confusion in the first place.

I will reland the commit with updated libc++ tests. The commit did not change the set of correct programs that we compile, it's just showing less spurious errors.

**Pull request merged**
