### PR TITLE
Revert "[mlir] Mark `isa/dyn_cast/cast/...` member functions deprecated. (#89998)"

### PR DESCRIPTION
**Pull request by dyung**
This reverts commit 950b7ce0b88318f9099e9a7c9817d224ebdc6337.

This change is causing build failures on a bot https://lab.llvm.org/buildbot/#/builders/216/builds/38157

### CODE REVIEW

**Comment by hanhanW** [comment]
I meant to cc @joker-eph and @chsigg (not requested reviews from them)

**Comment by chsigg** [comment]
Sorry about the breakage and thanks Douglas for reverting. 

I've re-landed the safe part of this change in #90406. The rest is in #90413, but I don't know how to test it. I would appreciate some help because I [can't seem to reproduce](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxBIA7KQADqgKhE4MHt6%2BekkpjgJBIeEsUTFc8XaYDmlCBEzEBBk%2Bfly2mPZ5DDV1BAVhkdFxtrX1jVktCsM9wX3FA2UAlLaoXsTI7BzmAMx4VADUWDQh6BAA%2BifIBkZn87smsW53bvuYh5jHZwDioXJu1yYaAEEtgdprsAgEAGoAWROQjkymUACVsEIhCcACLYJHYNwAgAq2HRGJxAQBiPxAEkAPKhNHKORCAASuxZrLZ7I5nNuAFYHoCWSdlMQmMAWEwIOYzB83E98CKGMlHMhdgkvAoEJKblztTrdVyTLz/gCBUKRWKJWYpTL9nh5Yq8Mq8MAFcQ3jyHpaALQAdSwCVdogIb09WAudSYHQUBo9Zk1RuBL1B4OhsPh2NRxOxuIJRMxblJ5Lx1Npgqpyj1FfZ0aNJuFovFkulsttzvtyqSCTjgK2bR2z1e7yhQl%2BEOwiPm8bMmxBITBkJhcIRyIzmKz%2BMJxPzZMpNLpDOZlcr1f5u0FdfNkoA7nUGMFgBBVeqJ5atYe3%2B/WcfjafTfWLWZr2IW8jAgfAFCYCJ6F2EBdkkABOOCADZnzMCduynGdMDnFNF3TNFV2RbMNzzAsdxLZQyw/PUv1rM0G0tQDgPvDsULQoEpzaJRJ2nRNZ2TBc02XfCsUI9dcxJbci13QV924zDsIEpcUWEtcc03UipPIstuNcHZ427bkrEMv0AwjN4DXRCyjQAN1QPB0F2CI6ggG47isWJLO7QFbPs3Z%2BFQFzbliKxAX41MlJXEScTE9TJOLPcmRrVknOIFyTE2EKATC3ChMzUS1JIuLpIo5R4w8o0OEWWhOG5Xg/A4LRSFQTgPSsSxdgUZZViwrYeFIAhNEqxYAGsQE2TYADpxummbZsQ/ROEkOrBqazheAUEANH6wbFjgWAkDQFgEjoaJyEoQ7jvoGJrOQBIEhOayuDgk4zGeiEhC4RCTi4LgTlUAAOeaaFoINiA2iAIhWiJgjqABPTg%2Buh5hiFhqkIm0SoBu4XhDrYQQqQYWh4Ya3gsAiLxgDcMRaA27HSCwMUjHEEn6bwANHGszBacazBVEqLwgwR3hgiDaqWdoPAImFFGPCwIX%2BuIPAWHlzniAiZJMHRTBGeACWjB2vgDGABQITwTBLypBJGHl/hBBEMR2CkGRBEUFR1BZ3QWkuYxrGsfRJY2yBFlQBJIzWprVcVrBA5c1p2jSFwGHcTwmn8JPeiKEpsmSVIBFGZpEhzjoM/6Uo48x6pJnzvQKiqAQunqEvZjLiZumr8ZJibrOuEWTqVjWCQqpq5aWeajhdgBxDdhYBQbt2R64Im17dnez6Jp%2B3YIFwQgSFuKce94LGtHmEaxsm2aL%2Bm%2BaxaW0h6sasf1s27aSd2mBEBAZYCFVAgzogC6TrEFCKwdYk9PSIUkLsYAyBlT/SmrwN4O8o56FtsIUQ4gnaoNdmoFantSCXmFAkIWQ8OC1TvitMeVIBY/12KgPYk9p6z2VAvJecEV4fUQuvLgm8PBHUAXvTYB8X7H1PuNKal8L4LQ4Lfe%2BvBH62GfkfIaUizAjwfuHJRJ9SCqxSM4SQQA) it.

**Comment by dyung** [comment]
> Sorry about the breakage and thanks Douglas for reverting.
> 
> I've re-landed the safe part of this change in #90406. The rest is in #90413, but I don't know how to test it. I would appreciate some help because I [can't seem to reproduce](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXACx8BBAKoBnTAAUAHpwAMvAFYTStJg1DIApACYAQuYukl9ZATwDKjdAGFUtAK4sGe1wAyeAyYAHI%2BAEaYxBIA7KQADqgKhE4MHt6%2BekkpjgJBIeEsUTFc8XaYDmlCBEzEBBk%2Bfly2mPZ5DDV1BAVhkdFxtrX1jVktCsM9wX3FA2UAlLaoXsTI7BzmAMx4VADUWDQh6BAA%2BifIBkZn87smsW53bvuYh5jHZwDioXJu1yYaAEEtgdprsAgEAGoAWROQjkymUACVsEIhCcACLYJHYNwAgAq2HRGJxAQBiPxAEkAPKhNHKORCAASuxZrLZ7I5nNuAFYHoCWSdlMQmMAWEwIOYzB83E98CKGMlHMhdgkvAoEJKblztTrdVyTLz/gCBUKRWKJWYpTL9nh5Yq8Mq8MAFcQ3jyHpaALQAdSwCVdogIb09WAudSYHQUBo9Zk1RuBL1B4OhsPh2NRxOxuIJRMxblJ5Lx1Npgqpyj1FfZ0aNJuFovFkulsttzvtyqSCTjgK2bR2z1e7yhQl%2BEOwiPm8bMmxBITBkJhcIRyIzmKz%2BMJxPzZMpNLpDOZlcr1f5u0FdfNkoA7nUGMFgBBVeqJ5atYe3%2B/WcfjafTfWLWZr2IW8jAgfAFCYCJ6F2EBdkkABOOCADZnzMCduynGdMDnFNF3TNFV2RbMNzzAsdxLZQyw/PUv1rM0G0tQDgPvDsULQoEpzaJRJ2nRNZ2TBc02XfCsUI9dcxJbci13QV924zDsIEpcUWEtcc03UipPIstuNcHZ427bkrEMv0AwjN4DXRCyjQAN1QPB0F2CI6ggG47isWJLO7QFbPs3Z%2BFQFzbliKxAX41MlJXEScTE9TJOLPcmRrVknOIFyTE2EKATC3ChMzUS1JIuLpIo5R4w8o0OEWWhOG5Xg/A4LRSFQTgPSsSxdgUZZViwrYeFIAhNEqxYAGsQE2TYADpxummbZsQ/ROEkOrBqazheAUEANH6wbFjgWAkDQFgEjoaJyEoQ7jvoGJrOQBIEhOayuDgk4zGeiEhC4RCTi4LgTlUAAOeaaFoINiA2iAIhWiJgjqABPTg%2Buh5hiFhqkIm0SoBu4XhDrYQQqQYWh4Ya3gsAiLxgDcMRaA27HSCwMUjHEEn6bwANHGszBacazBVEqLwgwR3hgiDaqWdoPAImFFGPCwIX%2BuIPAWHlzniAiZJMHRTBGeACWjB2vgDGABQITwTBLypBJGHl/hBBEMR2CkGRBEUFR1BZ3QWkuYxrGsfRJY2yBFlQBJIzWprVcVrBA5c1p2jSFwGHcTwmn8JPeiKEpsmSVIBFGZpEhzjoM/6Uo48x6pJnzvQKiqAQunqEvZjLiZumr8ZJibrOuEWTqVjWCQqpq5aWeajhdgBxDdhYBQbt2R64Im17dnez6Jp%2B3YIFwQgSFuKce94LGtHmEaxsm2aL%2Bm%2BaxaW0h6sasf1s27aSd2mBEBAZYCFVAgzogC6TrEFCKwdYk9PSIUkLsYAyBlT/SmrwN4O8o56FtsIUQ4gnaoNdmoFantSCXmFAkIWQ8OC1TvitMeVIBY/12KgPYk9p6z2VAvJecEV4fUQuvLgm8PBHUAXvTYB8X7H1PuNKal8L4LQ4Lfe%2BvBH62GfkfIaUizAjwfuHJRJ9SCqxSM4SQQA) it.

Do you have access to a Windows machine with VS2019 installed on it? You should be able to use the CMake command from the bot and then build with ninja to reproduce the issue. Here is the cmake command, modify the parts of it as necessary:
```
cmake -G Ninja ../llvm-project/llvm -DCMAKE_BUILD_TYPE=Release -DCLANG_ENABLE_ARCMT=OFF -DCLANG_ENABLE_CLANGD=OFF -DLLVM_CCACHE_BUILD=ON -DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-sie-ps5 -DLLVM_INCLUDE_EXAMPLES=OFF -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_VERSION_SUFFIX= -DLLVM_BUILD_RUNTIME=OFF -DLLVM_ENABLE_ASSERTIONS=ON -DLLVM_LIT_ARGS=--verbose -DLLVM_ENABLE_PROJECTS=clang-tools-extra;llvm;cross-project-tests;clang;lld
 
```

**Comment by chsigg** [comment]
Thank you very much Douglas. I don't have easy access to such a machine, but if I'm not mistaken the presubmit bots use VS2019 as well. So hopefully I will be able to reproduce it with PR #90413. It currently runs out of heap space when compiling flang, but maybe I can work around that by landing those changes first.

**Pull request merged**
