### PR TITLE
[compiler-rt][nsan] Disable coredump creation

### LINKED ISSUE #98806: [compiler-rt][nsan] abort_on_error=1 causes hang of the process
Setting `NSAN_OPTIONS=abort_on_error=1` causes hang of the process created from the binary which was built with nsan rt.
This happens because __nsan_init doesn't disable coredump creation and the kernel tries to create monster coredump file.

### PR DESCRIPTION
**Pull request by chestnykh**
- Disable coredump creation
If NSAN_OPTIONS contains `abort_on_error=1` the process hangs because the kernel tries to create a very huge core

msan, asan, tsan etc. runtimes disables coredumps too

Fix #98806

### CODE REVIEW

**Comment by chestnykh** [comment]
CC: @vitalybuka @alexander-shaposhnikov

**Review by MaskRay — COMMENTED** [review]
Disabling core dumps makes sense.

https://github.com/google/sanitizers/issues/637 describes why many sanitizers install signal handlers. But nsan doesn't deal with these undefined behaviors and perhaps doesn't need it?

**Review by MaskRay — COMMENTED** [review]
Disabling core dumps makes sense.

https://github.com/google/sanitizers/issues/637 describes why many sanitizers install signal handlers. But nsan doesn't deal with these undefined behaviors and perhaps doesn't need it?

**Comment by chestnykh** [comment]
> Disabling core dumps makes sense.
> 
> [google/sanitizers#637](https://github.com/google/sanitizers/issues/637) describes why many sanitizers install signal handlers. But nsan doesn't deal with these undefined behaviors and perhaps doesn't need it?

Okay, i thought that signal handler is installed to have detail report about crashes caused by signal :)

**Review by alexander-shaposhnikov — APPROVED** [review]
to me LG, i'd wait for @MaskRay

**Review by MaskRay — APPROVED** [review]

**Comment by chestnykh** [comment]
@MaskRay @alexander-shaposhnikov merge please this PR, I don't have write permissions

**Pull request merged**
