### PR TITLE
[clang-format] Use double hyphen for multiple-letter flags

### LINKED ISSUE #100974: git-clang-format uses non-standard-style CLI options
I am developing the WASM version of clang-format and testing the CLI that comes with it.  (https://github.com/wasm-fmt/clang-format)
I've encountered issues with the non-standard CLI options generated by git-clang-format, which complicates the parsing process.

Typically, clang-format's CLI options are structured as follows:

```
-i                             - Inplace edit <file>s, if specified.
--style=<string>               - Set coding style.
```

This is a standard CLI option, with a single hyphen representing a short option and a double hyphen representing a long option. However, CLI options generated by git-clang-format appear differently:

https://github.com/llvm/llvm-project/blob/73c72f2c6505d5bc8b47bb0420f6cba5b24270fe/clang/tools/clang-format/git-clang-format#L502

In typical cli parsing libraries, the `-style` option is synonymous with `-s -t -y -l -e`, which has been a source of confusion for me.

### PR DESCRIPTION
**Pull request by magic-akari**
- Closes: #100974

### CODE REVIEW

**Review by HazardyKnusperkeks — DISMISSED** [review]
You certainly can add the double hyphen flags, but you can't remove the single ones.

**Comment by magic-akari** [comment]
> You certainly can add the double hyphen flags, but you can't remove the single ones.

There seems to be a misunderstanding. Please review the original issue. 

I did _not_ eliminate support for single hyphens in clang-format. 

What I did was modify the scripts that call clang-format, including clang-format-diff.py, clang-format-sublime.py, clang-format.el, clang-format.py, and git-clang-format. 

I updated them to use the standard flag format as specified in the clang-format help. 

The clang-format tool itself remains unchanged and continues to accept single hyphens.

**Comment by HazardyKnusperkeks** [comment]
My bad, I thought you changed the options to those scripts.

**Comment by HazardyKnusperkeks** [comment]
Okay, I can't revoke my vote and remove me as reviewer. As demonstrated I'm not qualified to review python changes.

**Review by mydeveloperday — APPROVED** [review]

**Comment by magic-akari** [comment]
Ping

**Pull request merged**
