### PR TITLE
[AArch64] Enable "sink-and-fold" in MachineSink by default

### PR DESCRIPTION
**Pull request by momchil-velikov**

### CODE REVIEW

**Comment by davemgreen** [comment]
You could remove the option from some of the tests now that it's on by default? Maybe not all of them, but it would be good if one of them tested the default.

**Review by davemgreen — APPROVED** [review]
Thanks. LGTM

**Comment by fpetrogalli** [comment]
@momchil-velikov - I cannot find the comment I have attached to one of the commits in this PR. Just to make sure the information is not lost, I am letting you know that this PR seems to be breaking one of the public bots https://green.lab.llvm.org/green/job/clang-stage1-RA/35786/

**Comment by smeenai** [comment]
We're seeing some nice size wins in Meta's Android apps from this change (0.3% reduction in overall native library size). Looking forward to the reland :)

**Comment by bgra8** [comment]
@momchil-velikov this is causing a substantial compilation time regression when generating dwarf output. A V8 c++ file which compiles in less than 10s before this revision, compiles in 10 minutes at this revision.

The compilation command is something like:
```
clang
  -cc1 -triple aarch64-generic-linux-gnu -emit-obj \
  -debug-info-kind=constructor \
  -split-dwarf-file /tmp/repro.dwo \
  -split-dwarf-output /tmp/repro.dwo \
  -O3 -std=gnu++20 \
  -fsized-deallocation \
  -o /tmp/repro.o \
  -x c++ repro.cc
```

I started a reduction but it might take considerable time as we deal with such a high compilation time regression.

A revert will be welcome to unblock us before we come up with the reduced test case.

**Comment by bgra8** [comment]
@momchil-velikov as I reduce the file even further I get to less and less of a visible slow-down between this and previous compiler, so I had to stop the process as it was taking a lot of time.

With the attached reduced repro the slowdown is now 5x. I hope you find the issue. Please let me know if you need more info.

[repro.cc.zip](https://github.com/llvm/llvm-project/files/13196216/repro.cc.zip)

**Comment by momchil-velikov** [comment]
@bgra8 Thanks, I was able to observe 10x difference between `-g0` and `-g3`.

**Comment by momchil-velikov** [comment]
Small reproducer here:
```
int f(int);

void g(int x) {
  int y = x + 1;

  int t0 = y;
  f(t0);

  int t1 = y;
  f(t1);
}
```

With these commands
```
#! /bin/bash

./bin/clang -target aarch64-linux -g -O2 -S ccc.c -emit-llvm
./bin/llc  ccc.ll --aarch64-enable-sink-fold=true --stop-before=machine-sink -o ccc-before.mir
./bin/llc  ccc.ll --aarch64-enable-sink-fold=true --stop-after=machine-sink -o ccc-after.mir
kdiff3 ccc-{before,after}.mir
```
it's quite evident how sink-and-fold causes quadratic explosion in the number the DBG_VALUE instructions.

**Comment by momchil-velikov** [comment]
Easier to see here: https://gcc.godbolt.org/z/Tv878a39T
One issue is the debug info is replicated, a second issues it's sometimes lost.

**Pull request merged**
