### PR TITLE
[NFC][X86] Clang-format X86DisassemblerDecoderCommon.h

### PR DESCRIPTION
**Pull request by KanRobert**

### CODE REVIEW

**Comment by dwblaikie** [comment]
Once a pull request has been created, please don't commit it until it's been approved (we don't want to muddy the waters between code that was judged to require precommit review, and code that wasn't - if a review is created, that communicates the intent that the code needs precommit review, and so committing it without that review is a mistake/missing that required review)

**Comment by topperc** [comment]
Some of this seems to decrease reability. The code was structure to emphasize simarlities. What was the motivation?

**Comment by KanRobert** [comment]
> Some of this seems to decrease reability. The code was structure to emphasize simarlities. What was the motivation?

The motivation is the annoying warnings reported by code formatter in pre-commit testing. It keeps reminding me to format those code even if the code is not changed in my patch.  From my point, the structure helps little about the readability. (although different people may have different ideas ...), so I format the code in this separate patch to avoid the warnings

**Comment by dwblaikie** [comment]
> Oh, I see. I committed it w/o approval b/c I think it's a NFC and straightforward change. I think I should commit it w/o creating a PR next time. Thanks for the info.

Thanks! (yeah, at some point we might move to a PRs-always-required (eg: if we end up with mandatory precommit testing) but we aren't there yet - when we get there we'll need some way to distinguish PR-as-codereview and PR-as-precommit-testing (or we might, heaven forbid, move to mandatory precommit review... ))

**Pull request merged**
