### PR TITLE
[BOLT] Use new assembler directives for EH table emission

### PR DESCRIPTION
**Pull request by maksfb**
When emitting C++ exception tables (LSDAs), BOLT used to estimate the size of the tables beforehand. This implementation was necessary as the assembler/streamer lacked the emitULEB128IntValue() functionality.

As I plan to introduce [u|s]uleb-encoded exception tables in BOLT, it is a perfect time to switch to the new API and eliminate the need to pre-compute the size of the tables.

### CODE REVIEW

**Comment by maksfb** [comment]
The "new" assembler API was added back in 2018, but we never had enough incentive to switch to it.

**Review by dcci — COMMENTED** [review]
Do you have an example (textual) of the old VS new API? That would help me reviewing. Thanks!

**Comment by maksfb** [comment]
> Do you have an example (textual) of the old VS new API? That would help me reviewing. Thanks!

The assembler directive is:
```
  .uleb128 .L2 - .L1
```

More details in the ABI diff: https://github.com/llvm/llvm-project/commit/d09b416943fec535f73950b0954e0fcd17719a75

**Review by aaupov — APPROVED** [review]
LG. Is this change NFC?

**Comment by maksfb** [comment]
> LG. Is this change NFC?

Bitwise, the output could be different since we no longer have to emit `PadTo` bytes for alignment (https://github.com/llvm/llvm-project/pull/116294/commits/f7ebb8e16411459a8e7f756532faf3976bd3240e#diff-bc837da3fa9c524e0b9a5be566ca42adfb606f571378a2dff557912648f32e1fL1000) and instead align directly (https://github.com/llvm/llvm-project/commit/f7ebb8e16411459a8e7f756532faf3976bd3240e#diff-bc837da3fa9c524e0b9a5be566ca42adfb606f571378a2dff557912648f32e1fR1019).

**Review by dcci — APPROVED** [review]

**Pull request merged**
