### PR TITLE
[SDAG] Don't transfer !range metadata without noundef to SDAG

### PR DESCRIPTION
**Pull request by andjo403**
Same as https://github.com/llvm/llvm-project/commit/9deee6bffa9c331f46c68e5dd4cb4abf93dc0716 but for the noundef return attribute.

CC @nikic @arsenm

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
This makes little sense to me given that we want to phase out `!range` on calls, so I don't think there is valid in adding support for the `!range` metadata + noundef attribute combination *now*.

**Comment by andjo403** [comment]
Crated this as I noticed that noundef was a return attribute and a metadata so as the same logic as for only allowing range on loads think that noundef also only shall be allowed on loads.

But when I started to change to attributes for noundef tests that started to fail due to this was missing.

So was thinking that this was a first step to have noundef and range return attribute support.

**Comment by arsenm** [comment]
> This makes little sense to me given that we want to phase out `!range` on calls, so I don't think there is valid in adding support for the `!range` metadata + noundef attribute combination _now_.

I mean if it exists now, it should be handled now. The time to "want to phase out" could be anything from weeks to years

**Comment by nikic** [comment]
I don't agree here. It "exists" as in is still valid IR, but all the important producers have already been migrated, so I don't see a point in supporting it in an optimization *now*. If this were a matter of correctness, it would be a different matter of course.

> But when I started to change to attributes for noundef tests started to fail due to this was missing.
> 
> So was thinking that this was a first step to have noundef and range return attribute support.

To be clear, what I would like to see is added support for the range + noundef attribute combination. It's the mix of attributes and metadata that I don't think we need/should support.

**Comment by andjo403** [comment]
but if I do not do this I think I need to support the range attribute with with noundef metadata combo instead or maybe I miss something

**Comment by andjo403** [comment]
I also started to add support for range attribute here but to do that I think that I need to change the result to a `std::optional<ConstantRange>` but that snowballed to a lot of changes.

**Pull request closed without merging**
