### PR TITLE
[lldb] Fix linking to libtinfo

### PR DESCRIPTION
**Pull request by haampie**
LLVM detects when ncurses has a separate terminfo library, but linking to it
was broken in lldb since b66339575a9b541e67ce5ad2ba7e88da07cf9305 (LLVM 14) due
to a change of variables. This commit fixes that oversight.

### CODE REVIEW

**Comment by DavidSpickett** [comment]
I see that https://github.com/llvm/llvm-project/commit/b66339575a9b541e67ce5ad2ba7e88da07cf9305 removed the variable, but I never saw this on a buildbot, must be a config we don't cover.

What build configuration hits this issue? Please make a note of that in the commit message for future reference.

**Comment by haampie** [comment]
It's basically the same issue as #25067. Happens when ncurses is configured with `--with-termlib`, which puts certain symbols that lldb uses in `libtinfo`

**Review by DavidSpickett — APPROVED** [review]

**Comment by DavidSpickett** [comment]
And thanks for the patch, looks like the issue you linked was fixed, then would have been broken again for a time, and will now be fixed! All's well that ends well.

**Comment by haampie** [comment]
Updated the PR description. That's sufficient?

**Comment by eugeneswalker** [comment]
Thank you!

**Comment by DavidSpickett** [comment]
If you have the ability to merge, go ahead. Otherwise I can click the button for you.

**Comment by haampie** [comment]
I can't merge, feel free to do so!

**Pull request merged**
