### PR TITLE
[JITLink] Always unmap standard segments in InProcessMemoryManager::deallocate

### PR DESCRIPTION
**Pull request by mshockwave**
Right now InProcessMemoryManager only releases a standard segment (via sys::Memory::releaseMappedMemory) in `deallocate` when there is a DeallocAction associated, leaving residual memory pages in the process until termination.
Despite being a de facto memory leak, it won't cause a major issue if users only create a single LLJIT instance per process, which is the most common use cases. It will, however, drain virtual memory pages if we create thousands of ephemeral LLJIT instances in the same process.

This patch fixes this issue by releasing every standard segments regardless of the attached DeallocAction.

### CODE REVIEW

**Comment by mshockwave** [comment]
I'm not sure how to add new tests for this (it passes existing x86_64 JITLink tests though). I pin-pointed this issue by checking the `/proc/<PID>/maps` on Linux but I guess we can't add that as a test.

**Comment by lhames** [comment]
Thanks for catching this @mshockwave!

Rather than using an optional, what if we just removed the condition here:

```c++
      if (!FA->DeallocActions.empty())
	DeallocActionsList.push_back(std::move(FA->DeallocActions));
```
and just unconditionally moved the `DeallocActions` vector? I think that should be as cheap as the optional, and otherwise have the same effect.

**Comment by mshockwave** [comment]
> Thanks for catching this @mshockwave!
> 
> Rather than using an optional, what if we removed the condition here:
> 
> ```c++
>       if (!FA->DeallocActions.empty())
> 	DeallocActionsList.push_back(std::move(FA->DeallocActions));
> ```
> 
> and just unconditionally moved the `DeallocActions` vector? I think that should be as cheap as the optional, and otherwise have the same effect.

You're right, that's more efficient. I've fixed that.

**Review by lhames — APPROVED** [review]
> I'm not sure how to add new tests for this...

I don't have a great idea either. I'm happy for it to land as is. Thanks again for fixing this!

**Pull request merged**
