### PR TITLE
Reland "[Utils] add update-verify-tests.py" (#108630)"

### PR DESCRIPTION
**Pull request by hnrklssn**
This relands commit d4f41befb7256f8e8378ae358b2b3d802454d6a4 which was reverted by b7e585b95e241d0506b6f71d53ff5b6e72a9c8f4.

This version ignores differences in line endings in the diff tests to make sure the tests work as intended on Windows.

Original description below:
Adds a python script to automatically take output from a failed clang -verify test and update the test case(s) to expect the new behaviour.

### CODE REVIEW

**Comment by jakeegan** [comment]
Hi, `--strip-trailing-cr` isn't a supported option with diff on AIX. Would you be able to adapt the tests?

https://lab.llvm.org/buildbot/#/builders/64/builds/985

**Comment by hnrklssn** [comment]
> Hi, `--strip-trailing-cr` isn't a supported option with diff on AIX. Would you be able to adapt the tests?
> 
> https://lab.llvm.org/buildbot/#/builders/64/builds/985

This should fix it: https://github.com/llvm/llvm-project/pull/108871

**Comment by erichkeane** [comment]
As a CFE reviewer, I very much hate the existence of this script (and the CodeGen equivalents, but that is a separate discussion).

This existing means I can no longer trust that a test is a reflection of what the author intended to write, as they might have just run this and "YOLO'ed" it away.  So now I have to be 100x more careful reviewing tests, which means significantly worse review bandwidth.  This is the same problem I have with AI generated code/tests, as this is basically only a 1/2 step above, "Hey Google, write me a lit test for this".

@cor3ntin and @AaronBallman and @Endilll .

**Comment by hnrklssn** [comment]
> As a CFE reviewer, I very much hate the existence of this script (and the CodeGen equivalents, but that is a separate discussion).
> 
> This existing means I can no longer trust that a test is a reflection of what the author intended to write, as they might have just run this and "YOLO'ed" it away. So now I have to be 100x more careful reviewing tests, which means significantly worse review bandwidth. This is the same problem I have with AI generated code/tests, as this is basically only a 1/2 step above, "Hey Google, write me a lit test for this".
> 
> @cor3ntin and @AaronBallman and @Endilll .

That was always true, in the sense that there's nothing preventing the author from doing the exact same thing: looking at the output from the `clang -verify` failure and adding/removing expected diagnostics until it matches. In fact, even without this script that is the most mindless way of doing it, and I'm sure it already happens a lot.

In either way, authors should review their own changes first. I would argue that this script is significantly less harmful than any FileCheck generator script, because given an input program there is much less flexibility in how to structure the checks. With FileCheck you may not want to check every line, since some of them aren't directly relevant to the thing you're testing, instead making the test more fragile and harder to review through bloat. So creating FileCheck check lines is a bit of an art. But for `clang -verify` you have to add checkers for exactly the emitted diagnostics. No more or less. So the only real question is on which line to place them.

That said my main goal is not to make creating tests easier (although it of course also does that, and I don't know that I agree that it's harmful to lower the threshold to create tests), but to make it easier to batch update many/large breaking tests. We have many tests downstream that while testing features that don't yet exist upstream, are affected by new diagnostics added upstream. Handling many tests breaking all at once because of upstream changes is easier if it doesn't require a ton of `sed`-fu. Similar interactions happen when cherry-picking a patch from a dev branch to one or multiple release branches, that may not contain the exact same set of diagnostics. I could of course keep this script downstream, but we are not the only ones with downstream changes and I think others will find it helpful. And that's for a completely new script: keeping something like #108425 downstream only would be result in merge conflicts.

Furthermore, I have observed how existing regression tests create friction to improving phrasing of existing diagnostics. Old diagnostics often appear in many many tests, so while the code change to improving the diagnostic may be quick, you know it'll take significant time to update all of the regression tests using the old phrasing. So you don't do that drive-by improvement, because that wasn't your goal anyways. I think there are a ton of diagnostics in clang that could be improved to be clearer, but when the improvement is minor and friction is high we get stuck with the "good enough".

**Comment by Endilll** [comment]
> That was always true, in the sense that there's nothing preventing the author from doing the exact same thing: looking at the output from the clang -verify failure and adding/removing expected diagnostics until it matches. In fact, even without this script that is the most mindless way of doing it, and I'm sure it already happens a lot.

An author still has to pay some attention to the diagnostic test they are changing, and they still can notice things. Sure, they might not pick subtleties, but I think there's a fair chance to catch something really wrong. Again, we're constrained on review bandwidth, and not on making changes. As a testament to that, number of active PRs has been constantly going up ever since we switched to them, and we also have a long tail of opened reviews in Phabricator. So this little nudge to review your work helps the worst bottleneck we've been having.

> But for clang -verify you have to add checkers for exactly the emitted diagnostics. No more or less. So the only real question is on which line to place them.

I don't think it's that simple at least for some tests. We have tests that run in `-verify` mode multiple times with different combinations of compiler options. Such tests might rely on custom prefixes (`-verify=prefix1,prefix2`), and updating them automatically can easily yield incorrect result. As an example how more complicated tests might look like, consider C++ DR test suite. Here's one example: 
https://github.com/llvm/llvm-project/blob/ca0613e0fcef2a9972f2802318201f8272e74693/clang/test/CXX/drs/cwg3xx.cpp#L779-L782

> That said my main goal is not to make creating tests easier (although it of course also does that, and I don't know that I agree that it's harmful to lower the threshold to create tests), but to make it easier to batch update many/large breaking tests. We have many tests downstream that while testing features that don't yet exist upstream, are affected by new diagnostics added upstream. Handling many tests breaking all at once because of upstream changes is easier if it doesn't require a ton of sed-fu. Similar interactions happen when cherry-picking a patch from a dev branch to one or multiple release branches, that may not contain the exact same set of diagnostics. I could of course keep this script downstream, but we are not the only ones with downstream changes and I think others will find it helpful. And that's for a completely new script: keeping something like https://github.com/llvm/llvm-project/pull/108425 downstream only would be result in merge conflicts.

I don't intend to dismiss the pain downstream could have over this, but in my opinion it doesn't justify opening floodgates of automated test updates upstream. At the moment I don't have a strong opinion on infrastructure that supports such automated updates, like #108425 you mentioned.

> Furthermore, I have observed how existing regression tests create friction to improving phrasing of existing diagnostics. Old diagnostics often appear in many many tests, so while the code change to improving the diagnostic may be quick, you know it'll take significant time to update all of the regression tests using the old phrasing.

I agree that the pain is there. But again, I don't think the end justifies the mean.

> So you don't do that drive-by improvement, because that wasn't your goal anyways.

Drive-by fix that makes you update a lot of test would introduce a lot of noise into your PR anyway, making it noticeably harder to review. I believe the script addresses the wrong problem here.

**Comment by hnrklssn** [comment]
> > But for clang -verify you have to add checkers for exactly the emitted diagnostics. No more or less. So the only real question is on which line to place them.
> 
> I don't think it's that simple at least for some tests. We have tests that run in `-verify` mode multiple times with different combinations of compiler options. Such tests might rely on custom prefixes (`-verify=prefix1,prefix2`), and updating them automatically can easily yield incorrect result. As an example how more complicated tests might look like, consider C++ DR test suite. Here's one example:
> 
> https://github.com/llvm/llvm-project/blob/ca0613e0fcef2a9972f2802318201f8272e74693/clang/test/CXX/drs/cwg3xx.cpp#L779-L782

This script doesn't support test failures in multiple prefixes or regex matchers for that reason, because I could not find a reliable way to update those failures without manual intervention.

> > That said my main goal is not to make creating tests easier (although it of course also does that, and I don't know that I agree that it's harmful to lower the threshold to create tests), but to make it easier to batch update many/large breaking tests. We have many tests downstream that while testing features that don't yet exist upstream, are affected by new diagnostics added upstream. Handling many tests breaking all at once because of upstream changes is easier if it doesn't require a ton of sed-fu. Similar interactions happen when cherry-picking a patch from a dev branch to one or multiple release branches, that may not contain the exact same set of diagnostics. I could of course keep this script downstream, but we are not the only ones with downstream changes and I think others will find it helpful. And that's for a completely new script: keeping something like #108425 downstream only would be result in merge conflicts.
> 
> I don't intend to dismiss the pain downstream could have over this, but in my opinion it doesn't justify opening floodgates of automated test updates upstream. At the moment I don't have a strong opinion on infrastructure that supports such automated updates, like #108425 you mentioned.
> 
> > Furthermore, I have observed how existing regression tests create friction to improving phrasing of existing diagnostics. Old diagnostics often appear in many many tests, so while the code change to improving the diagnostic may be quick, you know it'll take significant time to update all of the regression tests using the old phrasing.
> 
> I agree that the pain is there. But again, I don't think the end justifies the mean.

That's fair, we disagree on this point. I think responsible use of  automatic test updaters is reasonable, and we shouldn't prevent people from using it just because it _could_ be abused. I'm sympathetic that there may be many low quality PRs to wade through, but I'd rather let the number of open PRs continue to grow and let more people step up to the task of reviewing as it becomes more apparent that we need more reviewers. Artificially hampering developer productivity just because it's not the bottleneck is hiding the symptom rather than fixing the problem (too few reviewers in comparison to the number of PRs).

I do want to stress though, that this script handles pretty **trivial** updates. Yes, it doesn't force people to look at the changes they're submitting, but compared to existing scripts this is significantly less risky. I don't want to resort to whataboutism, but I do think we need to be consistent if we're going to ban test update scripts.

> > So you don't do that drive-by improvement, because that wasn't your goal anyways.
> 
> Drive-by fix that makes you update a lot of test would introduce a lot of noise into your PR anyway, making it noticeably harder to review.

Of course the drive-by fix would have to be submitted as a separate PR in that case, but that's quite straightforward even after the fact when you have a script like this: extract the implementation into a separate commit, and rerun the test updater on both branches to bring over the test updates to the new PR and undo the noise on the original PR.

> I believe the script addresses the wrong problem here.

There's no getting around that the tests need to be updated if diagnostics are updated. Lack of reviewers doesn't mean developer issues can't also be addressed.

**Comment by AaronBallman** [comment]
> But for clang -verify you have to add checkers for exactly the emitted diagnostics. No more or less. So the only real question is on which line to place them.

As someone who does *a lot* of review in Clang, I (strongly) disagree with this assertion.

You do not have to add checks for exactly the emitted diagnostics, there are times when it's more appropriate to drop some part of the message. In fact, we used to have guidance that only the very first instance of the diagnostic should be spelled out fully, and all subsequent ones should be limited to just the bare minimum needed to identify what the diagnostic is. That's why there are hundreds of instances of things like `// expected-note {{here}}`. What's more, there is a rich set of functionality provided by the diagnostic verifier that we often request patch authors use, but is stylistic. It's important to use regular expressions and bookmarks to help make the tests readable and reviewable, which is why they're used thousands of times across Clang's lit tests. Finally, as @Endilll pointed out, there are tests which have multiple (sometime numerous) RUN lines where the output is expected to differ between RUN lines; we typically ask authors to use custom verify prefixes for those tests, but crafting those can sometimes be an art form (and other times is very straightforward).

Writing tests is not a mechanical operation, it requires you to think about what you need to test as well as think about *how* you test it. I think the same is less true for things like testing LLVM IR because that tends to be more routine pattern matching, which typically requires less stylistic choices.

> That said my main goal is not to make creating tests easier (although it of course also does that, and I don't know that I agree that it's harmful to lower the threshold to create tests), but to make it easier to batch update many/large breaking tests. 

This is a serious problem we have, so working on ways to improve that is greatly appreciated! While there's some pretty significant push-back about your current approach, perhaps there is an alternative which makes folks feel more comfortable. For example, the script could explicitly refuse to add new diagnostic comments, only remove or update existing comments. That would make it require more developer effort when adding a new diagnostic and wanting to update tests, but *that's a feature not a bug* because we want the developer to think critically about whether the diagnostic actually makes sense everywhere it fires before they put up the PR. It doesn't solve all problems (like style choices), but it at least helps in the easier cases without the risk of people abusing it accidentally.

> This existing means I can no longer trust that a test is a reflection of what the author intended to write, as they might have just run this and "YOLO'ed" it away.

FWIW, I share this concern -- developers could do this anyway by just writing the comments by hand, but a script *encourages* the developer to trust the output the compiler gives because it's easy to assume problems will be caught by review. This slows down review throughput, increases the burden on reviewers, and given how often people update existing diagnostics, seems like a poor tradeoff (then again, maybe more people will update existing diagnostics if that wasn't so painful to do).

Given the amount of push-back, I think we should probably revert the changes here so we can discuss with a bit wider of an audience than weighed in on the original PR.

**Comment by erichkeane** [comment]
> You do not have to add checks for exactly the emitted diagnostics, there are times when it's more appropriate to drop some part of the message. In fact, we used to have guidance that only the very first instance of the diagnostic should be spelled out fully, and all subsequent ones should be limited to just the bare minimum needed to identify what the diagnostic is. That's why there are hundreds of instances of things like `// expected-note {{here}}`. What's more, there is a rich set of functionality provided by the diagnostic verifier that we often request patch authors use, but is stylistic. It's important to use regular expressions and bookmarks to help make the tests readable and reviewable, which is why they're used thousands of times across Clang's lit tests. Finally, as @Endilll pointed out, there are tests which have multiple (sometime numerous) RUN lines where the output is expected to differ between RUN lines; we typically ask authors to use custom verify prefixes for those tests, but crafting those can sometimes be an art form (and other times is very straightforward).

So another huge side note: I've been pushing REALLY hard for us to use the bookmark feature more aggressively for notes. So I've been asking authors to do THAT as well.

**Comment by hnrklssn** [comment]
>  In fact, we used to have guidance that only the very first instance of the diagnostic should be spelled out fully, and all subsequent ones should be limited to just the bare minimum needed to identify what the diagnostic is. That's why there are hundreds of instances of things like // expected-note {{here}}.

Side note: In general I think the fact that these tests pass if the check implicitly match on a subset of the diagnostic does more harm than good. When test authors actively want to do that the can always use the regex feature, but I think the default should be to match the exact string. When there are similar diagnostics or shorter/longer version it's too much of a footgun to accidentally have shorter diagnostic match the longer version as well. When I review, i prefer the test to give me a picture as close to the exact output as possible, so I can evaluate the user friendliness. I think it's a massive shortcoming that we don't check the order in which notes are emitted, or which range is highlighted, because reviewers don't get the full picture without checking out the branch and manually compiling test cases.

> Finally, as @Endilll pointed out, there are tests which have multiple (sometime numerous) RUN lines where the output is expected to differ between RUN lines; we typically ask authors to use custom verify prefixes for those tests, but crafting those can sometimes be an art form (and other times is very straightforward).

Again, this script doesn't run on tests with multiple prefixes. It's meant for test cases which are trivial to update, of which there are many.

> Writing tests is not a mechanical operation, it requires you to think about what you need to test as well as think about how you test it. I think the same is less true for things like testing LLVM IR because that tends to be more routine pattern matching, which typically requires less stylistic choices.

Sometimes it is, sometimes it isn't. Even when it isn't just having the checks added to the test file in approximately the final location for me to move around is a massive boon compared to manually adding them all.

> Given the amount of push-back, I think we should probably revert the changes here so we can discuss with a bit wider of an audience than weighed in on the original PR.

Yup, will revert.

> So another huge side note: I've been pushing REALLY hard for us to use the bookmark feature more aggressively for notes. So I've been asking authors to do THAT as well.

I appreciate that, it can be really tricky to get a feel for the flow of notes, especially when a diagnostic has multiple notes attached. The test sadly doesn't check that the order of the notes emitted is actually sensical, for example. I don't know the solution, but I think there is some inherent flaw when it comes to how `-verify` tests operate currently, in that you need to trust that the author formatted the test to accurately reflect reality.

**Comment by erichkeane** [comment]
>I don't know the solution, but I think there is some inherent flaw when it comes to how -verify tests operate currently, in that you need to trust that the author formatted the test to accurately reflect reality.

In part why I push for bookmarks, it makes it clear on the ordering.  And also why a tool like this makes me afraid, it makes me trust the authors a bunch less.

**Comment by AaronBallman** [comment]
> > In fact, we used to have guidance that only the very first instance of the diagnostic should be spelled out fully, and all subsequent ones should be limited to just the bare minimum needed to identify what the diagnostic is. That's why there are hundreds of instances of things like // expected-note {{here}}.
> 
> Side note: In general I think the fact that these tests pass if the check implicitly match on a subset of the diagnostic does more harm than good.

+1, it's why I stopped recommending this approach in my reviews.

> > Writing tests is not a mechanical operation, it requires you to think about what you need to test as well as think about how you test it. I think the same is less true for things like testing LLVM IR because that tends to be more routine pattern matching, which typically requires less stylistic choices.
> 
> Sometimes it is, sometimes it isn't. Even when it isn't just having the checks added to the test file in approximately the final location for me to move around is a massive boon compared to manually adding them all.

Sure, it's a time-saver when used as intended. I think the push-back is largely coming from recognition that not everyone uses tools as they are intended and we need to balance making it easy to update a large amount of tests (something which occurs infrequently) against the risks of (even accidental) tool misuse.

> > Given the amount of push-back, I think we should probably revert the changes here so we can discuss with a bit wider of an audience than weighed in on the original PR.
> 
> Yup, will revert.

Thank you!

**Comment by erichkeane** [comment]
> > 
> 
> +1, it's why I stopped recommending this approach in my reviews.

While I agree for the most part, there are quite a few diagnostics that are absurdly verbose (particularly ones with "did you mean to FLOOP it?").  I think partial matches are good/fine, but they need enough of the diag to not be ambiguous.

**Comment by hnrklssn** [comment]
> > > 
> > 
> > 
> > +1, it's why I stopped recommending this approach in my reviews.
> 
> While I agree for the most part, there are quite a few diagnostics that are absurdly verbose (particularly ones with "did you mean to FLOOP it?"). I think partial matches are good/fine, but they need enough of the diag to not be ambiguous.

I don't necessarily oppose the use of truncated checks where it makes sense, I oppose the implicit default on the matcher's part. An `expected-note-re{{.*FLOOP.*}}` would be a reasonable explicit opt-in. A new mode like `expected-note-part{{FLOOP}}` would be even better, making the old mode behave like `expected-note-re{{^FLOOP$}}`. As an (admittedly extreme) example of footgunnery with this implicit behaviour, we had bug downstream where there were two versions of an error, something like this: `cannot use FOO in context asdf` vs `cannot use FOO in context asdf; did you mean to use BAR?`. The `; did you mean to use BAR?` version was accidentally emitted in some cases where it didn't make sense to do so, but the tests still passed because the diagnostic *did* contain `cannot use FOO in context asdf`.

**Comment by jroelofs** [comment]
>  The ; did you mean to use BAR? version was accidentally emitted in some cases where it didn't make sense to do so, but the tests still passed because the diagnostic did contain cannot use FOO in context asdf.

There's a `FileCheck` flag to enforce this: `--match-full-lines`

**Comment by hnrklssn** [comment]
> >  The ; did you mean to use BAR? version was accidentally emitted in some cases where it didn't make sense to do so, but the tests still passed because the diagnostic did contain cannot use FOO in context asdf.
> 
> 
> 
> There's a `FileCheck` flag to enforce this: `--match-full-lines`

Clang diagnostic tests don't use FileCheck, instead clang has a -verify flag.

**Comment by jroelofs** [comment]
oh, right. nvm

**Pull request merged**
