### PR TITLE
[Flang] Add support for assume_aligned directive

### PR DESCRIPTION
**Pull request by Leporacanthicus**
This adds the parsing (and unparse) of the compiler drective assume_aligned.

The compiler will issue a warning that the directive is ignored.

### CODE REVIEW

**Comment by kiranchandramohan** [comment]
Please add an entry to https://github.com/llvm/llvm-project/blob/main/flang/docs/Directives.md

Might be good to add some additional references on the use of the directive.
https://github.com/SALMON-TDDFT/SALMON/blob/35429bd824cc3302e676dcf5e2b059f8a4436dc4/src/ARTED/stencil/F90/hpsi.f90#L103
https://github.com/LLNL/WRF-IBM/blob/6b7fbcabf807f63e15c51df725e942aa0540d5c6/phys/mic-wsm5-3-5-code.h#L206
https://github.com/NCAR/kernelOptimization/blob/66a9292a4b0e20ec5109fd152ce42641d7e533ac/all/PORT_binterp/orig/kernel_binterp.F90#L389

**Comment by tblah** [comment]
LG so far. Where is the warning generated? Could you write a test for that?

nit: please write the commit title in the normal format

**Comment by klausler** [comment]
why is a general designator allowed instead of a simple base object name?  why would subscripts be needed to set alignment of the base object?

**Comment by Leporacanthicus** [comment]
@klausler Hi Peter, do you have any further feedback. Kiran's comment contains links to existing uses in among other things SALMON, that use the format of `!dir$ assume_aligned B(0,iy,ix):MEM_ALIGN` - that's from the first link in Kiran's comment with links above.

**Comment by klausler** [comment]
> @klausler Hi Peter, do you have any further feedback. Kiran's comment contains links to existing uses in among other things SALMON, that use the format of `!dir$ assume_aligned B(0,iy,ix):MEM_ALIGN` - that's from the first link in Kiran's comment with links above.

I do not.

**Comment by Leporacanthicus** [comment]
> LG so far. Where is the warning generated? Could you write a test for that?

It is warned for in the generic handling of directives.There is no special handling for this case, it is just a "if the compiler gets to the end of the list without finding a match, give a warning that it wasn't recognized". 

I don't believe we need a specific test - it's not an actively desired feature.
> 
> nit: please write the commit title in the normal format

**Review by tblah — APPROVED** [review]
Thanks for explaining. LGTM

**Pull request merged**
