### PR TITLE
Remove support for RenderScript

### PR DESCRIPTION
**Pull request by AaronBallman**
See https://discourse.llvm.org/t/rfc-deprecate-and-eventually-remove-renderscript-support/81284 for the RFC

### CODE REVIEW

**Comment by cor3ntin** [comment]
Hey Aaron.
Thanks for your contribution. We usually require a changelog for non-nfc changes. Can you add an entry to the release notes of clang?

:clown_face:

**Review by cor3ntin — APPROVED** [review]
LGTM once @pirama-arumuga-nainar is happy with it

**Review by pirama-arumuga-nainar — APPROVED** [review]

**Comment by tbaederr** [comment]
I think this reference should go as well: https://github.com/llvm/llvm-project/blob/main/clang/www/index.html#L20 ?

**Review by stephenhines — APPROVED** [review]
Thank you for taking care of the cleanup CL. It is much appreciated.

**Pull request merged**
