### PR TITLE
[NFC][Intrumentation] Don't brake long RUN: lines

### PR DESCRIPTION
**Pull request by vitalybuka**
I find multiline 'RUN:' statements hard to read.

` *\\\n; RUN: *` -> ` ` for  ./llvm/test/Instrumentation/

### CODE REVIEW

**Comment by fmayer** [comment]
I generally prefer the wrapped lines but if you feel strongly go ahead.

**Comment by vitalybuka** [comment]
> I generally prefer the wrapped lines but if you feel strongly go ahead.

Yes, I'd like to do so very much.
Most common info I look in these lines are difference in compiler options between them. And it's much easier to see if they are semi-aligned. The tail with FileCheck is usually irrelevant.

Bug if it's needed there is wrap on/off in most editors.

**Comment by fmayer** [comment]
Wouldn't that make one per line better for diffing? That's what I generally do for long command lines to read / diff them.

**Review by fmayer — APPROVED** [review]
Sure, I don't feel strongly.

**Pull request merged**
