### PR TITLE
[CUDA] Add support for CUDA-12.6 and sm_100

### PR DESCRIPTION
**Pull request by sergey-kozub**
Adds support for sm_100 (Blackwell), similar to https://github.com/llvm/llvm-project/pull/74895

One important aspect is that `sm_100` is not compatible with `sm_90a`, only with `sm_90` - note the defines in "BuiltinsNVPTX.def"

### CODE REVIEW

**Comment by sergey-kozub** [comment]
@Artem-B, @andportnoy, you might want to take a look

**Comment by sergey-kozub** [comment]
This PR is redundant, closing.

**Comment by Artem-B** [comment]
> This PR is redundant, closing.

I think the patch was perfectly fine. Considering that other NVIDIA open-source projects already mention sm_100 (E.g. https://github.com/NVIDIA/cccl/blob/5efe53dbd71ea3e4bc4fdbb73edc001e0bf81547/libcudacxx/include/nv/detail/__target_macros#L241), I think it's fine to land the patch, even if no publicly released CUDA version has blackwell support yet.

**Comment by Artem-B** [comment]
@sergey-kozub  FYI, https://github.com/llvm/llvm-project/pull/100247 should allow forward-testing CUDA w/o relying on specific GPU/PTX variant being hardcoded in clang.

**Pull request closed without merging**
