### PR TITLE
Print more descriptive error message when trying to link a global with appending linkage

### PR DESCRIPTION
**Pull request by arrowd**
This is a proper fix for https://github.com/llvm/llvm-project/issues/40308

### CODE REVIEW

**Comment by arrowd** [comment]
Ping, this is a trivial PR and can be easily merged in.

**Comment by arrowd** [comment]
Bump. Can we get this in?

**Review by RKSimon — APPROVED** [review]
LGTM

**Comment by arrowd** [comment]
I don't have rights to merge this.

**Pull request merged**
