### PR TITLE
[Clang][NFC] use const references for function parameters in operator== and operator!= overloads in Redeclarable.h

### LINKED ISSUE #92755: clang/include/clang/AST/Redeclarable.h: 4 * Function parameter should be passed by const reference
Source code is

    friend bool operator==(redecl_iterator x, redecl_iterator y) {
      return x.Current == y.Current;
    }
    friend bool operator!=(redecl_iterator x, redecl_iterator y) {
      return x.Current != y.Current;
    }

Maybe better code:

    friend bool operator==( const redecl_iterator & x, const redecl_iterator & y) {
      return x.Current == y.Current;
    }
    friend bool operator!=( const redecl_iterator & x, const redecl_iterator & y) {
      return x.Current != y.Current;
    }

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #92755

### CODE REVIEW

**Comment by a-tarasyuk** [comment]
Ping

**Comment by a-tarasyuk** [comment]
ping

**Comment by a-tarasyuk** [comment]
@kparzysz could you review this PR?

**Review by zyn0217 — APPROVED** [review]
Please explicitly say NFC in the commit title. Otherwise, LGTM

**Comment by zyn0217** [comment]
No problem! Do you need anyone else to help you commit it?

**Comment by a-tarasyuk** [comment]
@zyn0217 Thanks

**Pull request merged**
