### PR TITLE
[PowerPC][AIX] Enable aix-small-local-dynamic-tls target attribute

### PR DESCRIPTION
**Pull request by orcguru**
Following the aix-small-local-exec-tls target attribute, this patch adds a target attribute for an AIX-specific option in llc that informs the compiler that it can use a faster access sequence for the local-dynamic TLS model (formally named aix-small-local-dynamic-tls) when TLS variables are less than ~32KB in size.

The patch either produces an addi/la with a displacement off of module handle (return value from .__tls_get_mod) when the address is calculated, or it produces an addi/la followed by a load/store when the address is calculated and used for further accesses.

### CODE REVIEW

**Comment by orcguru** [comment]
There will be some interactions between this patch and https://github.com/llvm/llvm-project/pull/84132. I will work on that part, and will update later.

**Review by amy-kwan — COMMENTED** [review]
Some initial comments for now. Will a subsequent front end patch also come?

**Comment by bzEq** [comment]
Overall lgtm, the title is confusing, could you adjust it?

**Comment by orcguru** [comment]
> Some initial comments for now. Will a subsequent front end patch also come?

Hi Amy, subsequently I will follow your commits (b1922e55ab3b and then 2a50921553798). The next one will enable the functionality through front end by adding "-maix-small-local-dynamic-tls" clang option. After that, I will refactor some existing logic to handle non-zero offsets for TLS local-dynamic.

Let me know if you have other thoughts. Thank you!

**Comment by orcguru** [comment]
> Overall lgtm, the title is confusing, could you adjust it?

Updated. Thank you!

**Review by bzEq — APPROVED** [review]
LG.

**Review by amy-kwan — APPROVED** [review]
LGTM.

**Pull request merged**
