### PR TITLE
[Flang][NFC] Split common headers to reduce dependencies.

### PR DESCRIPTION
**Pull request by Meinersbur**
Fortran.h and target.h are defining symbols where some are used by both, the Fortran runtime (Flang-RT) and Fortran compiler (Flang), and others are used by Flang only. With the upcoming refactoring of the Fortran runtime into its own subproject (#110217), move the declarations that are used by both into new headers to minimize the amount of code that will need to be shared by Flang-RT and Flang.

Details:

 * `Fortran.h`: Flang-RT  only uses some enum definitions out of this file, but not `AsFortran` which is defined in `Fortran.cpp`. Moving the enums into `Fortran-consts.h` allows keeping `Fortran.cpp` within Flang.

 * `target.h`: Contains some floating-point definitions that is used by the non-GTest unittests in `fp-testing.h`. Flang-RT also uses some non-GTest as well. Moving those definitions avoids the dependence on the entire FortranEvaluate library.

### CODE REVIEW

**Review by DavidTruby — APPROVED** [review]
LGTM. Can you add [NFC] in the commit message?
Thanks for working on this!

**Review by jeanPerier — COMMENTED** [review]
Please hold off on merging the pieces until there is more approval on the [top level patch](https://github.com/llvm/llvm-project/pull/110217)/approach.

The [overall churn](https://github.com/llvm/llvm-project/compare/main...users/meinersbur/flang_runtime) is quite big and takes time to review and assess for the runtime authors.

While the goal makes sense to me, the solution has a big footprint on the code/headers, so I think it is important to give some time to assess the solution and arguments made in the RFC. @sscalpone who is named as a code owner in the new flang-rt project is not available this week and needs to be involved.

**Comment by Meinersbur** [comment]
@jeanPerier I think the patches up until #110298 are good ideas independent of flang-rt. These reduce dependence of unrelated components.

The high number of changes files comes mostly from file renaming and the consequential path changes in inside the files (#include, copyright header, header guard). These nearly completely mechanical changes (I wrote a python script to apply them) are isolated in #110298. 

@sscalpone is mentioned as code owner in `flang-rt/` since he is already code owner of the same runtime sources in `flang/`.

The [RFC](https://discourse.llvm.org/t/rfc-use-llvm-enable-runtimes-for-flangs-runtime/80826) started in August. #110217 ended draft status [a month ago](https://github.com/llvm/llvm-project/pull/110217#event-14546760123). There hasn't been any sign of 
activity from Nvidia in the RFC or patch series for 3 weeks now. Please understand that eventually I will assume that Nvidia has no more concerns.

**Comment by jeanPerier** [comment]
> Please understand that eventually I will assume that Nvidia has no more concerns.

Thank you for your understanding @Meinersbur, and for the work your doing to make builds of the runtime independent of the compiler itself. We are aware of the effort you put in the RFC and these patches, please rest assured that we are actively reviewing, testing, and discussing it since you called for review again on #110298 earlier this week.

**Review by mjklemm — COMMENTED** [review]
The PR LGTM.  I did not approve. since devs from NVIDIA are still reviewing.

**Review by jeanPerier — APPROVED** [review]
Thanks for letting me the time to review and test the whole solution. Given the progress, I am ok with this patch to be merged now to make it easier to iterate on the last two core patches.

**Pull request merged**
