### PR TITLE
InstrProfiling.cpp: Let lowerIntrinsics() able to insert BBs.

### PR DESCRIPTION
**Pull request by chapuni**
IsBBChanged should be set when lowering inserted BBs. Make lowerMCDCTestVectorBitmapUpdate() return IsBBChanged unconditionally at the moment.

### CODE REVIEW

**Comment by ornata** [comment]
What is the difference between `MadeChange` and `IsBBChanged`?

**Comment by chapuni** [comment]
@ornata `MadeChange` is a just trigger to the posprocess `promoteCounterLoadStores(F)`.
All intrinsics was replaced within BB Insts in the current impl.

I would like to introduce BB change to insert conditional store. This makes `for (BB)` harder and redoing the loop is required.
This is the reason why I introduce `IsBBChanged`.

Do you have any better idea for redoing if BB is added by `SplitBlockAndInsertIfThen()`?
Rather redoing the loop, could we record IntrinsicInsts at 1st loop and procees marked Insts in 2nd loop? For example,

```
  SmallVector<IntrinsicInst*> InstrsLowered;
  for (BB: *F)
    for (Instr: BB)
      if (isa<IntrinsicInst>(Instr) && (isCounterBase(Instr) || isMCDCBase(Instr))
        InstrsLowered.push_back(Instr);

  // This can replace MadeChange.
  if (InstrsLowered.empty()) return false;

  for (Instr : InstrLowered)
    if (auto *IPFOO == dyn_cast<InstrProfFOO>(Instr)
      lowerFOO(IPFOO);
    else if ...

promoteCounterLoadStores(F);
return true;  
```

This will avoid flags and redoing.

**Comment by ellishg** [comment]
IRPGO profiles will only match if the CFG of the instrumented function is the same as the CFG of optimized function. For this reason, the instrumentation should not change the CFG of the function.

If you want a conditional store, you might want to consider creating a new function and calling it. You might even be able to force it to be inlined. If the CFG of the assembly changes, that is ok. We just want the CFG of the IR to stay the same.

**Comment by chapuni** [comment]
@ellishg Thanks for explanation of backgrounds. I've understood this preparation is no longer needed.

> If you want a conditional store, you might want to consider creating a new function and calling it. You might even be able to force it to be inlined.

I'll take this direction for now if inserting the new Function is safe here.

> If the CFG of the assembly changes, that is ok.

I think we could introduce the new mode for TATAS (Test and Test and Set) to atomicrmw. So I will write the proposal if this is reasonable. I will introduce "conditional atomicrmw OR".

**Pull request closed without merging**
