### PR TITLE
[GitHub] Set top level token permission

### PR DESCRIPTION
**Pull request by marbre**

### CODE REVIEW

**Comment by marbre** [comment]
Without explicitly setting the token permission, the default (read/write for all scopes) kicks in, if not changed for the entire repo, see https://github.blog/changelog/2021-04-20-github-actions-control-permissions-for-github_token.

**Comment by tru** [comment]
This seems reasonable of course, but as always with these kinds of changes - It's really hard to test ahead of time to make sure it doesn't break anything. Have you tested this in your fork?

**Comment by marbre** [comment]
> This seems reasonable of course, but as always with these kinds of changes - It's really hard to test ahead of time to make sure it doesn't break anything. Have you tested this in your fork?

So far I've checked what actions are used within the workflow, but this cannot be considered at testing ahead. I had in mind that this workflow isn't that critical and that it is partly ignored (if I remember one of the pre-merge check discussions correctly). However, I converted this PR to a draft PR and will take a closer look and test within my fork.

**Review by tstellar — APPROVED** [review]

**Review by boomanaiden154 — APPROVED** [review]
LGTM. I agree with your analysis that this shouldn't fail by changing this, but always good to test. Getting the test setup working can be a little difficult, so if you run into any non-trivial issues, let me now and hopefully I can assist.

**Comment by tstellar** [comment]
@marbre Are you planning to commit this?

**Pull request merged**
