### PR TITLE
[NewPM] Remove AAEval Legacy Pass

### PR DESCRIPTION
**Pull request by boomanaiden154**
This patch removes the AAEval legacy pass and associated plumbing. This pass was migrated over to the new pass manager about 11 years ago at this point and there are currently no in-tree users of the legacy pass, so it's essentially just dead code and is completely untested.

### CODE REVIEW

**Review by MaskRay — APPROVED** [review]
LGTM. Removing a legacy pass usually involves ~5 files.

**Comment by bjope** [comment]
One thing people always forget when dropping support for legacy PM is to remove unneeded includes. I think that you no longer need (at least) these in  AliasAnalysisEvaluator.cpp:
```
  #include "llvm/InitializePasses.h"
  #include "llvm/Pass.h"
```

**Comment by bjope** [comment]
(Oops... I just wanted to Comment, but acccidentally pressed "Close with comment" instead of "Comment".)

**Review by aeubanks — APPROVED** [review]

**Comment by boomanaiden154** [comment]
> One thing people always forget when dropping support for legacy PM is to remove unneeded includes. I think that you no longer need (at least) these in AliasAnalysisEvaluator.cpp:
> 
> ```
>   #include "llvm/InitializePasses.h"
>   #include "llvm/Pass.h"
> ```

Fixed in the latest revision. Thanks for catching this!

**Pull request merged**
