### PR TITLE
[libc] start fix readability-identifier-naming lints

### PR DESCRIPTION
**Pull request by nickdesaulniers**
There's quite a few of these warnings and not all fixits build cleanly. Here's
an initial batch of fixes.

### CODE REVIEW

**Comment by jhuber6** [comment]
I thought the coding style required that constexpr was all caps. Did we change that?

**Comment by michaelrj-google** [comment]
constexpr should be caps, see: https://github.com/llvm/llvm-project/blob/main/libc/.clang-tidy#L27

**Comment by michaelrj-google** [comment]
though I guess that's only for variables and this change is mostly touching functions. Probably we need to add a key for constexpr functions.

**Comment by nickdesaulniers** [comment]
weird, either I'm omitting feeding that .clang-tidy file into my invocations, or the cmake build is, or perhaps the option name changed...digging.

**Comment by nickdesaulniers** [comment]
> constexpr

https://clang.llvm.org/extra/clang-tidy/checks/readability/identifier-naming.html#cmdoption-arg-ConstexprFunctionCase

**Comment by nickdesaulniers** [comment]
> > constexpr
> 
> https://clang.llvm.org/extra/clang-tidy/checks/readability/identifier-naming.html#cmdoption-arg-ConstexprFunctionCase

Adding this will result in a whole host of other changes, since we're internally inconsistent at the moment.

```
$ ninja -k2000 libc-lint 2>&1 | grep readability-identifier-naming | grep 'constexpr function' | sort -u | wc -l
170
```
:)

**Comment by lntue** [comment]
> > > Probably we need to add a key for constexpr functions.
> > 
> > https://clang.llvm.org/extra/clang-tidy/checks/readability/identifier-naming.html#cmdoption-arg-ConstexprFunctionCase
> 
> Adding this will result in a whole host of other changes, since we're internally inconsistent at the moment.
> 
> ```
> $ ninja -k2000 libc-lint 2>&1 | grep readability-identifier-naming | grep 'constexpr function' | sort -u | wc -l
> 170
> ```
> :)

Those `constexpr` functions that we capitalized the names are more like `consteval` functions.  Unfortunately `constexpr` works differently for functions vs variables.

**Comment by nickdesaulniers** [comment]
Otherwise, if we don't update the clang-tidy rules (and instead have constexpr functions be lowercase, the current number of unique lints here is 11.

So by that measure, I think that it makes sense to:
1. codify that we use lower_case for constexpr functions.
2. fix the 11 violations

Rather then codify it as upper case and fix the 170 resulting violations.

**Comment by lntue** [comment]
> Otherwise, if we don't update the clang-tidy rules (and instead have constexpr functions be lowercase, the current number of unique lints here is 11.
> 
> So by that measure, I think that it makes sense to:
> 1. codify that we use lower_case for constexpr functions.
> 2. fix the 11 violations
> 
> Rather then codify it as upper case and fix the 170 resulting violations.

How about option 3: mark these functions `consteval` and add C++20 standard when needed?  Or add TODO's for option 3?

**Comment by nickdesaulniers** [comment]
> > Otherwise, if we don't update the clang-tidy rules (and instead have constexpr functions be lowercase, the current number of unique lints here is 11.
> > So by that measure, I think that it makes sense to:
> > 
> > 1. codify that we use lower_case for constexpr functions.
> > 2. fix the 11 violations
> > 
> > Rather then codify it as upper case and fix the 170 resulting violations.
> 
> How about option 3: mark these functions `consteval` and add C++20 standard when needed? Or add TODO's for option 3?

Personally, I'm happy to aggressively move to newer language standards; `consteval` in particular seems to provide much stronger guarantees than `constexpr` IIUC.

Pragmatically, I don't think we should be moving our implementation to a standard newer than what the rest of the llvm-project requires.  We'd probably be dropping support for certain host compiler versions by requiring newer standard support, and we'd need to research that.

Moving to C++20 will be a larger yak shave than fixing 11 clang-tidy lints.

**Comment by nickdesaulniers** [comment]
https://github.com/llvm/llvm-project/pull/83345

**Comment by nickdesaulniers** [comment]
Also, `consteval` is straight up an error in `-std=c++17`: https://godbolt.org/z/TsoWEWea5

**Comment by nickdesaulniers** [comment]
> Pragmatically, I don't think we should be moving our implementation to a standard newer than what the rest of the llvm-project requires. 

But I wouldn't be against anyone starting an RFC on llvm discourse to bring up the topic. ;)

**Pull request closed without merging**
