### PR TITLE
[clang-apply-replacements] Deduplicate Implementation of `collectReplacementsFromDirectory` (NFC)

### PR DESCRIPTION
**Pull request by unterumarmung**
* Convert `collectReplacementsFromDirectory` into a function template.
* Employ explicit specialization to maintain implementation in the source file.
* Utilize the function template in the source file to eliminate code duplication.
* Update the documentation for the function.

### CODE REVIEW

**Comment by unterumarmung** [comment]
I honestly don't who should review/approve this, but hopefully the change is not complicated.

**Review by PiotrZSL — APPROVED** [review]
LGTM.

**Review by HerrCai0907 — APPROVED** [review]
LGTM

**Comment by unterumarmung** [comment]
The Windows build in the CI is stuck. The change is pretty trivial and doesn't use any features that cannot be found in C++98. So, we can skip the Windows check.

**Pull request merged**
