### PR TITLE
Revert #95218 and #94953

### PR DESCRIPTION
**Pull request by makslevental**
Reverts #95218 and #94953 which broke for all release builds without `LLVM_ENABLE_DUMP=ON`. Which is probably the majority of builds since it is off by [default](https://github.com/llvm/llvm-project/blob/33f4a77d9218c1a2d5c994a8a8398479731612dc/llvm/CMakeLists.txt#L623). 

Next time please revert instead of fixing forward.

### CODE REVIEW

**Review by Groverkss — APPROVED** [review]
LGTM, reverting since release build is broken seems fair to me.

**Review by akuegel — APPROVED** [review]
Thanks for sending the revert.

**Comment by artagnon** [comment]
My fix will be ready in 10 mins. Go ahead with the revert, if you think it’s necessary.

**Comment by makslevental** [comment]
> My fix will be ready in 10 mins. Go ahead with the revert, if you think it’s necessary.

Two fails in a row means absolutely a revert is warranted and an exceptionally detailed review of your fix will be necessary.

**Comment by artagnon** [comment]
Okay, I’ve sent the fix.

**Comment by stellaraccident** [comment]
Agreed/thank you. While always a judgement call when considering a fix forward, the default action should be a revert when it is project impacting. Double fix forwards are extremely costly to everyone in the project who depends on the code.

**Pull request merged**
