### PR TITLE
[mlir][mesh] In sharding attr use FlatSymbolRefAttr instead of SymbolRefAttr

### PR DESCRIPTION
**Pull request by sogartar**
Analogous to func.call use FlatSymbolRefAttr to reference the corresponding mesh.

### CODE REVIEW

**Comment by sogartar** [comment]
@yaochengji, can you take a look at this PR?

**Comment by joker-eph** [comment]
Do you have a motivation for this?

Also can you add a test rejecting the nested structure?

**Comment by sogartar** [comment]
> Do you have a motivation for this?
I cargo culted from `func.call` the flat symbol refs for the other collective ops and I wanted the Mesh dialect to be consistent. I taught that flat symbols are less complicated and I could not think of a good reason for nested symbols right now.

**Comment by sogartar** [comment]
> Also can you add a test rejecting the nested structure?

Just added a test.

**Comment by yaochengji** [comment]
LGTM, thanks

**Review by yaochengji — APPROVED** [review]

**Review by joker-eph — APPROVED** [review]

**Pull request merged**
