### PR TITLE
[Flang][OpenMP] Fix to construct-names inside OpenMP construct with default(none)

### PR DESCRIPTION
**Pull request by harishch4**
When a do loop with a construct-name is used inside OpenMP construct with default(none), an incorrect error will be raised as below.

```
program cn_and_default
    implicit none
    integer :: i

    !$omp parallel default(none)
        loop: do i = 1, 10
        end do loop
    !$omp end parallel
end program
```

> The DEFAULT(NONE) clause requires that 'loop' must be listed in a data-sharing  attribute clause

This patch fixes this by adding a condition to check and skip processing construct-names.

### CODE REVIEW

**Review by mjklemm — APPROVED** [review]
LGTM.

**Review by NimishMishra — APPROVED** [review]
LGTM

**Comment by kiranchandramohan** [comment]
> an assertion will be raised as below.
This is an incorrect error and not an assertion right?

**Review by kiranchandramohan — APPROVED** [review]
LG.

**Comment by harishch4** [comment]
> This is an incorrect error and not an assertion right?

Yes, it is an incorrect error. Updated the comment. Thanks.

**Pull request merged**
