### PR TITLE
[clang][CodeGen] Add AS for Globals to SPIR & SPIRV datalayouts

### PR DESCRIPTION
**Pull request by AlexVlx**
Currently neither the SPIR nor the SPIRV targets specify the AS for globals in their datalayout strings. This is problematic because CodeGen/LLVM will default to AS0 in this case, which produces Globals that end up in the private address space for e.g. OCL, HIPSPV or SYCL. This patch addresses it by completing the datalayout string.

### CODE REVIEW

**Comment by bader** [comment]
The change seems reasonable.

> CodeGen/LLVM will default to AS0 in this case, which produces Globals that end up in the private address space for e.g. OCL, HIPSPV or SYCL.

Can we add a test checking LLVM address space for globals emitted from OCL/HIPSPV/SYCL, please? It's surprising that we need to modify only a datalayout string check.

**Comment by AlexVlx** [comment]
> The change seems reasonable.
> 
> > CodeGen/LLVM will default to AS0 in this case, which produces Globals that end up in the private address space for e.g. OCL, HIPSPV or SYCL.
> 
> Can we add a test checking LLVM address space for globals emitted from OCL/HIPSPV/SYCL, please? It's surprising that we need to modify only a datalayout string check.

I can add another one here, but there's a bunch of them coming in #88182, which roundabout motivated this change. I'll emphasise that this is only a problem for things such as implicitly generated globals (e.g. VTables or typeinfo for classes etc.), so it's just a subset of all globals that are impacted (there are already some tests covering direct usage AFAICS).

**Review by bader — COMMENTED** [review]
> I'll emphasise that this is only a problem for things such as implicitly generated globals (e.g. VTables or typeinfo for classes etc.)

I suppose usage of VTables and typeinfo is kind of restricted in GPU programming models. Right?

Anyway, I think it's a reasonable change for SPIR target, which fixes mapping from `global` address space to `1` LLVM address space.
It's less obvious for SPIR-V, which is not LLVM-based format and mapping between SPIR-V and LLVM addresses spaces is technically an implementation detail, which can be adjusted.
According to my understanding, today LLVM IR for SPIR-V target just follows SPIR target nomenclature.

I'd like Eli/John to give formal approval for this change, but I'm okay with it. 👍 Thanks!

**Comment by asudarsa** [comment]
Thanks @AlexVlx for this change. This should work fine for SPIRV-LLVM-Translator (and SPIR-V backend). Adding @michalpaszkowski for input from SPIR-V backend side. Recently, this restriction on LLVM IR input to our translator was docuemnted:
https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/main/docs/SPIRVRepresentationInLLVM.rst#global-variables
_"A global variable resides in an address space, and the default address space in LLVM is zero. The SPIR-V storage class represented by the zero LLVM IR address spaces is Function. However, SPIR-V global variable declarations are OpVariable instructions whose Storage Class cannot be Function. This means that global variable declarations must always have an address space specified and that address space cannot be 0."_
So, your change will help to make the LLVM IR more suitable for the translator.

One quick pointer. I did notice a similar commit for the AMDGPU backend - https://reviews.llvm.org/D84345
Here, there are some updates to the llvm/lib/IR/AutoUpgrade.cpp. Do we need similar changes here?

Thanks

**Comment by AlexVlx** [comment]
> Thanks @AlexVlx for this change. This should work fine for SPIRV-LLVM-Translator (and SPIR-V backend). Adding @michalpaszkowski for input from SPIR-V backend side. Recently, this restriction on LLVM IR input to our translator was docuemnted: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/main/docs/SPIRVRepresentationInLLVM.rst#global-variables _"A global variable resides in an address space, and the default address space in LLVM is zero. The SPIR-V storage class represented by the zero LLVM IR address spaces is Function. However, SPIR-V global variable declarations are OpVariable instructions whose Storage Class cannot be Function. This means that global variable declarations must always have an address space specified and that address space cannot be 0."_ So, your change will help to make the LLVM IR more suitable for the translator.
> 
> One quick pointer. I did notice a similar commit for the AMDGPU backend - https://reviews.llvm.org/D84345 Here, there are some updates to the llvm/lib/IR/AutoUpgrade.cpp. Do we need similar changes here?
> 
> Thanks

Thanks for the feedback, and great call on the AutoUpgrade part, I had not considered that at all; I believe we can just re-use the AMDGPU approach, and just adapt the predicate, but I'll give it a think and then update this PR accordingly.

**Review by michalpaszkowski — APPROVED** [review]
LGTM (from the SPIR-V backend side)!

**Review by Keenuts — APPROVED** [review]

**Comment by efriedma-quic** [comment]
Please also fix llvm/lib/Target/SPIRV/SPIRVTargetMachine.cpp

**Review by AlexVlx — COMMENTED** [review]
> Please also fix llvm/lib/Target/SPIRV/SPIRVTargetMachine.cpp 

Done.

**Review by AlexVlx — COMMENTED** [review]
> > Thanks @AlexVlx for this change. This should work fine for SPIRV-LLVM-Translator (and SPIR-V backend). Adding @michalpaszkowski for input from SPIR-V backend side. Recently, this restriction on LLVM IR input to our translator was docuemnted: https://github.com/KhronosGroup/SPIRV-LLVM-Translator/blob/main/docs/SPIRVRepresentationInLLVM.rst#global-variables _"A global variable resides in an address space, and the default address space in LLVM is zero. The SPIR-V storage class represented by the zero LLVM IR address spaces is Function. However, SPIR-V global variable declarations are OpVariable instructions whose Storage Class cannot be Function. This means that global variable declarations must always have an address space specified and that address space cannot be 0."_ So, your change will help to make the LLVM IR more suitable for the translator.
> 
> One quick pointer. I did notice a similar commit for the AMDGPU backend - https://reviews.llvm.org/D84345 Here, there are some updates to the llvm/lib/IR/AutoUpgrade.cpp. Do we need similar changes here?
> 
> Thanks

I've added AutoUpgrade support.

**Review by asudarsa — APPROVED** [review]
Thanks for this change. LGTM

**Review by efriedma-quic — APPROVED** [review]
LGTM

**Comment by AlexVlx** [comment]
Merged, thanks everyone for the reviews!

**Comment by bogner** [comment]
Looks like this missed a spot, causing the .hlsl to spir-v tests to fail. I've put up a fix in #88939

**Pull request merged**
