### PR TITLE
[Clang] Demote always_inline error to warning for mismatching SME attrs

### PR DESCRIPTION
**Pull request by sdesmalen-arm**
PR #77936 introduced a diagnostic to avoid calls being inlined into functions with a different streaming mode, because inlining those functions may result in different runtime behaviour. This was necessary because LLVM doesn't check whether inlining is possible and thus blindly inlines the function without checking feasibility.

In practice however, this introduces an artificial restriction that the user may not be able to work around. Calling an `always_inline` function from some header file that is out of the control of the user would result in an error that the user cannot remedy.

Therefore, this patch demotes the error into a warning (for calls from streaming[-compatible] -> non-streaming), but the proper fix would be to fix the AlwaysInliner in LLVM to avoid inlining when it has analyzed the callee and has determined that inlining is not possible.

Calling an always_inline function for calls from non-streaming -> streaming will remain an error, because there is little pre-existing code for SME, so it is expected that the header file can be modified by the user (e.g. by using `__arm_streaming_compatible` if the code is claimed to be compatible).

### CODE REVIEW

**Comment by Sirraide** [comment]
At a glance, this seems like a good use case for a warning + `DefaultError`?

**Comment by sdesmalen-arm** [comment]
> At a glance, this seems like a good use case for a warning + `DefaultError`?

I'd rather not make that change, because in practice it will be unlikely that inlining will result in changes to runtime behaviour. We'd rather not burden the users with explicit errors for something that may be fine, as it's more a limitation of Clang that it has to emit this message in the first place. Separate to that, it might not be directly clear to users that the error can be demoted into a warning.

Thanks for the suggestion though!

**Comment by Sirraide** [comment]
> it's more a limitation of Clang that it has to emit this message in the first place
Fair enough, that makes sense

**Review by paulwalker-arm — APPROVED** [review]

**Pull request merged**
