### PR TITLE
[mlir][test] Fix filecheck annotation typos

### PR DESCRIPTION
**Pull request by klensy**
Moved fixes for mlir from https://github.com/llvm/llvm-project/pull/91854, plus few additional in second commit.

### CODE REVIEW

**Comment by klensy** [comment]
Few places where i don't know how to resolve:
mlir\test\Conversion\FuncToLLVM\convert-data-layout.mlir: unknown prefixes: RUN-32, CHECK-32
mlir\test\Conversion\FuncToLLVM\func-memref.mlir: unknown prefixes: CHECK-32
mlir\test\Conversion\MemRefToLLVM\expand-then-convert-to-llvm.mlir unknown prefixes: CHECK-32
mlir\test\Dialect\Func\duplicate-function-elimination.mlir unknown prefixes: CHECK-3, CHECK-2
mlir\test\Dialect\OpenACC\ops.mlir unknown prefixes: CHECK-3
mlir\test\Integration\GPU\CUDA\sm90\tma_load_64x8_8x128_noswizzle.mlir unknown prefixes: CHECK-PTX
mlir\test\mlir-spirv-cpu-runner\simple_add.mlir unknown prefixes: CHECK-RAW
mlir\test\mlir-tblgen\op-decl-and-defs.td unknown prefixes: DECLS

**Review by kuhar — APPROVED** [review]
SPIR-V and arith LGTM

**Comment by grypp** [comment]
I will take a look the nvvm tests

**Review by ftynse — APPROVED** [review]
LGTM.

**Comment by klensy** [comment]
> Please file an issue for these and we can advise there.

Created https://github.com/llvm/llvm-project/issues/93154

**Comment by klensy** [comment]
I don't know how to wait for review from 10 reviewers, to if you r+ some tests please feel free to chop them and merge youself to speedup process.

**Comment by grypp** [comment]
> mlir\test\Integration\GPU\CUDA\sm90\tma_load_64x8_8x128_noswizzle.mlir unknown prefixes: CHECK-PTX

I've fixed this here #93147

**Review by grypp — APPROVED** [review]

**Review by MacDue — APPROVED** [review]
ArmSME changes look good -- thanks!

**Comment by ftynse** [comment]
I think we've got enough reviewer coverage here.

**Comment by vitalybuka** [comment]
Please fix or revert https://lab.llvm.org/buildbot/#/builders/5/builds/43594

**Comment by klensy** [comment]
Ah, yes, CI wasn't green but missing from checks in github ui.

**Comment by klensy** [comment]
Fixed? https://github.com/llvm/llvm-project/commit/c455ab73d8b2ba0e0423fe838d30f4284b785064

**Pull request merged**
