### PR TITLE
[flang][debug] set DW_AT_main_subprogram for fortran main function

### PR DESCRIPTION
**Pull request by tblah**
Requested here https://github.com/llvm/llvm-project/pull/111022#issuecomment-2396287781

### CODE REVIEW

**Comment by DavidSpickett** [comment]
Didn't expect something that quickly :)

What does gdb say for `info main` before and after the change? (note that this is a new feature, I know at least 115 has it)

**Comment by tblah** [comment]
For
```
program example
end program
```

Both before and after this patch using gdb 15.0.50. 
```
(gdb) info main
example
```

I'm not sure how gdb found the right name before this patch. I can't see the `DW_AT_main_subprogram` attribute in `objdump -g` output before this patch and do after.

**Comment by DavidSpickett** [comment]
Well I didn't look into GDB's code I'm just going on what experts told me. So there could be a heuristic in there too.

Either way according to https://dwarfstd.org/doc/DWARF4.pdf this is a legitimate use of `DW_AT_main_subprogram` and it's what LLDB will end up looking for in the future.

**Review by DavidSpickett — APPROVED** [review]
LGTM

**Review by abidh — APPROVED** [review]
LGTM.

**Pull request merged**
