### PR TITLE
[Clang] Update Unicode version to 15.1

### PR DESCRIPTION
**Pull request by cor3ntin**
This update all of our Unicode tables to Unicode 15.1. This is a minor version so only a relatively small numbers of characters are added, mainly ideographs

https://www.unicode.org/versions/Unicode15.1.0/#Appendices_nb

### CODE REVIEW

**Comment by cor3ntin** [comment]
@nikic looks like you closed the wrong issue

**Comment by nikic** [comment]
Ooops, sorry about that.

**Review by AaronBallman — APPROVED** [review]
LGTM

**Comment by MaskRay** [comment]
Nice! I wonder whether there is any documentation/procedure notes to facilitate future updates, like: what files need to be updated?

**Comment by cor3ntin** [comment]
@MaskRay sadly, At the moment we have no automation whatsoever for some of the tables (only character names and case folding have upstream scripts). We really should write a script to generate the tables. (the one i use is fairly nasty and i need to copy each table in the corresponding file manually, it's... not great)

**Pull request merged**
