### PR TITLE
[Sema] -Wzero-as-null-pointer-constant: don't warn for __null

### PR DESCRIPTION
**Pull request by zeux**
The implementation of -Wzero-as-null-pointer-constant was done before the following fix has been committed to GCC:

https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=752e7593b0f19af233a0b7e72daab8413662b605;hp=298434c916c14e8adca2cab8a746aee29038c5b3

As a result, clang and gcc diverge on the use of `__null` and, consequently, on the use of `NULL` on systems like Linux/macOS where `NULL` is defined as `__null`.

This is a problem for compatibility between gcc and clang, particularly for code bases that support C++98 or for single-source libraries that are implemented in C, but compiled as C++ via inclusion into a C++ translation unit. Code like this can not be changed to use `nullptr`, as it needs to maintain compatibility with C before C23 or C++ before C++11, but warns on the use of `NULL` in clang.

The warning `Wzero-as-null-pointer-constant` is still useful with this change, as it allows to change `0` to `NULL`, which fixes
gcc warnings and helps the reader distinguish between pointers and non-pointers. Users who require a full C++11 modernization pass can still use clang-tidy for that purpose.

### CODE REVIEW

**Comment by zeux** [comment]
Note: a limitation of this change is that we will still warn on use of `NULL` when it is defined as 0, which could be a problem for clang-cl. This could be lifted by removing the "NULL" macro name check, but unfortunately that is insufficient to detect the use of NULL inside macro expansion (such as `MCRO(NULL)` in the test file). Because of this, this change is conservative in that it aligns the logic with GCC but doesn't attempt to handle NULL fully. I can revise this if this seems like an issue worth addressing here.

This change revises the logic of https://github.com/llvm/llvm-project/commit/809df34efc653c6a471f951305a88bd5e675b522 so
cc @LebedevRI as the author of that adjustment, @nico as the original author, and @AaronBallman since this was suggested on Discord.

**Comment by zeux** [comment]
Ping

**Review by AaronBallman — COMMENTED** [review]
I think the changes are reasonable, but should come with a release note so users know about the change in diagnostic behavior. (We have a section in `clang/docs/ReleaseNotes.rst` for diagnostic improvements.)

Otherwise, I think the changes LGTM

**Comment by zeux** [comment]
Thanks! I've updated this PR with a release note.

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Comment by zeux** [comment]
Let me know if I need to do anything else here -- I don't have commit rights so someone else will need to press the merge button :)

**Pull request merged**
