### PR TITLE
[PAC][ELF][AArch64] Encode signed GOT flag in PAuth core info

### PR DESCRIPTION
**Pull request by kovdan01**
Treat 8th bit of version value for llvm_linux platform as signed GOT flag.

- clang: define `PointerAuthELFGOT` LangOption and set 8th bit of `aarch64-elf-pauthabi-version` LLVM module flag correspondingly;

- llvm-readobj: print `PointerAuthELFGOT` or `!PointerAuthELFGOT` in version description of llvm_linux platform depending on whether the flag is set.

### CODE REVIEW

**Review by jh7370 — COMMENTED** [review]
I'm not at all familiar with this PAuth stuff, but don't you need a test case for where the new value is set (currently they all seem to be unset, if I'm interpreting things correctly)?

**Comment by kovdan01** [comment]
> I'm not at all familiar with this PAuth stuff, but don't you need a test case for where the new value is set (currently they all seem to be unset, if I'm interpreting things correctly)?

I'm not sure if I understood your question correctly - particularly, I'm not sure what does the phrase "the new value is set" mean. Could you please add a bit more details in your question?

If you are talking about llvm/test/tools/llvm-readobj/ELF/AArch64/aarch64-feature-pauth.s and llvm/test/CodeGen/AArch64/note-gnu-property-elf-pauthabi.ll tests checking version value 0x55 which does not imply signed GOT enabled, we just can't test 2^8=256 combinations of flags, so we test values which look like 0b10101... But I can add a test for version value 0xAA which would set opposite flags compared to 0x55.

**Comment by jh7370** [comment]
> > I'm not at all familiar with this PAuth stuff, but don't you need a test case for where the new value is set (currently they all seem to be unset, if I'm interpreting things correctly)?
> 
> @jh7370 I'm not sure if I understood your question correctly - particularly, I'm not sure what does the phrase "the new value is set" mean. Could you please add a bit more details in your question?
> 
> If you are talking about llvm/test/tools/llvm-readobj/ELF/AArch64/aarch64-feature-pauth.s and llvm/test/CodeGen/AArch64/note-gnu-property-elf-pauthabi.ll tests checking version value 0x55 which does not imply signed GOT enabled, we just can't test 2^8=256 combinations of flags, so we test values which look like 0b10101... But I can add a test for version value 0xAA which would set opposite flags compared to 0x55.

I was referring to this line from the description:

> llvm-readobj: print `PointerAuthELFGOT` or `!PointerAuthELFGOT` in version description of llvm_linux platform depending on whether the flag is set.

In my opinion, if you don't test the first of those two cases, you might as well not have implemented behaviour for it. I'd always test "all flags set" and "no flags set" cases (or some variant that effectively tests this, e.g. 0xff and ~0xff). Of course, if it's not practical, that's fine.

**Comment by kovdan01** [comment]
> I was referring to this line from the description:
> 
> > llvm-readobj: print `PointerAuthELFGOT` or `!PointerAuthELFGOT` in version description of llvm_linux platform depending on whether the flag is set.
> 
> In my opinion, if you don't test the first of those two cases, you might as well not have implemented behaviour for it. I'd always test "all flags set" and "no flags set" cases (or some variant that effectively tests this, e.g. 0xff and ~0xff). Of course, if it's not practical, that's fine.
> 
> To be clear, I'm not suggesting testing every possible combination of flags, just each flag individually set/not set.

@jh7370 Thanks for explanation! It's a reasonable point, I'll add corresponding test cases, thanks.

**Review by jh7370 — COMMENTED** [review]
Thanks, llvm-readobj aspects look good to me (I don't feel like I can review the clang side).

**Comment by kovdan01** [comment]
Would be glad to see feedback on the changes from those who are interested.

**Comment by kovdan01** [comment]
@MaskRay Would be glad to see your feedback on the changes

**Review by tommat01 — APPROVED** [review]
LGTM, just based on what I can see from implementation of the existing bits in the version field.

**Comment by kovdan01** [comment]
Thanks @tmatheson-arm! I'll merge this as soon as #96478 gets merged - there, we introduce `AARCH64_PAUTH_PLATFORM_LLVM_LINUX_VERSION_INITFINIADDRDISC = 7`, so signed GOT should be bit 8. We can't use bit 8 for signed GOT right now since the implementation relies on contiguous set of flags - so, I'll wait for #96478 and change signed GOT bit position to 8.

**Pull request merged**
