### PR TITLE
[FMV][AArch64] Unify features memtag and memtag2.

### PR DESCRIPTION
**Pull request by labrinea**
If we split these features in the compiler (see relevant pull request https://github.com/llvm/llvm-project/pull/109299), we would only be able to hand-write a 'memtag2' version using inline assembly since the compiler cannot generate the instructions that become available with FEAT_MTE2. However these instructions only work at Exception Level 1, so they would be unusable since FMV is a user space facility. I am therefore unifying them.

Approved in ACLE as https://github.com/ARM-software/acle/pull/351

### CODE REVIEW

**Comment by labrinea** [comment]
> I don't understand this distinction: why is FMV seen as user-space only?

I had to clarify this with @Wilco1 and @DanielKristofKiss. My understanding is that FMV implementations which rely on ifuncs (Linux) only work in address spaces where a dynamic linker can be used. This limitation rules out OS and baremetal environments. However, there are FMV implementations which emulate ifuncs via function pointers (Windows), but the specification must be possible to implement on all platforms, and therefore it is bound by the ifunc limitation.

**Comment by Wilco1** [comment]
There also isn't any demand to make it work in EL1 - almost all software runs in user space and kernels typically already have their own mechanisms to support different ISA variants. So I wouldn't call it a limitation - it's a high-level feature for average users by design, not kernel developers.

**Comment by labrinea** [comment]
Ping.

**Review by jroelofs — APPROVED** [review]

**Comment by labrinea** [comment]
Thanks!

**Pull request merged**
