### PR TITLE
[MLIR][Vector] Allow any shaped type to be distributed for vector.wa…

### PR DESCRIPTION
**Pull request by kurapov-peter**
…rp_execute_on_lane_0's return values

The second part of https://github.com/llvm/llvm-project/pull/112945.

### CODE REVIEW

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Just translating my objection from the earlier PR to this. It seems wrong to check a verification on `vector` dialect to check that the result is a `shapedtype`. That seems like a layering violation.

**Comment by kurapov-peter** [comment]
> Just translating my objection from the earlier PR to this. It seems wrong to check a verification on `vector` dialect to check that the result is a `shapedtype`. That seems like a layering violation.

I would like to unblock further Xegpu lowering development and not require the creation of a whole new dialect since it may take a lot of time to land. I agree that this patch is not how the end solution should look, and I'm happy to improve it gradually.

I also considered an interface while doing the thing, but the interface alone doesn't solve the layering problem. So, between the two approaches, I picked the one with fewer changes. Please let me know if I missed some real issues that an interface solves.

**Comment by rengolin** [comment]
> Just translating my objection from the earlier PR to this. It seems wrong to check a verification on `vector` dialect to check that the result is a `shapedtype`. That seems like a layering violation.

Agreed. This could be an interface that both "vector types" implement, and the distribution works on the interface. It would also make it easier to extend other vector types to work in the same way, or change internal behaviour without breaking the distribution.

**Comment by kurapov-peter** [comment]
As discussed in https://discourse.llvm.org/t/rfc-extending-vector-distribution-to-support-other-types/82833, moved the op to gpu instead where it can now be not vector-specific.

**Pull request closed without merging**
