### PR TITLE
[flang][FIR] remove fir.complex type and its fir.real element type

### PR DESCRIPTION
**Pull request by jeanPerier**
Final patch of https://discourse.llvm.org/t/rfc-flang-replace-usages-of-fir-complex-by-mlir-complex-type/82292

Since fir.real was only still used as fir.complex element type, this patch removes it at the same time.

### CODE REVIEW

**Review by clementval — APPROVED** [review]
LGTM

**Review by vzakhari — APPROVED** [review]
Thank you, Jean!

**Review by abidh — APPROVED** [review]
LGTM

**Comment by jeanPerier** [comment]
Thank for the reviews!

**Pull request merged**
