### PR TITLE
[MLIR][OpenMP] NFC: Uniformize OpenMP ops names

### PR DESCRIPTION
**Pull request by skatrak**
This patch proposes the renaming of certain OpenMP dialect operations with the
goal of improving readability and following a uniform naming convention for
MLIR operations and associated classes. In particular, the following operations
are renamed:

- `omp.map_info` -> `omp.map.info`
- `omp.target_update_data` -> `omp.target_update`
- `omp.ordered_region` -> `omp.ordered.region`
- `omp.cancellationpoint` -> `omp.cancellation_point`
- `omp.bounds` -> `omp.map.bounds`
- `omp.reduction.declare` -> `omp.declare_reduction`

Also, the following MLIR operation classes have been renamed:

- `omp::TaskLoopOp` -> `omp::TaskloopOp`
- `omp::TaskGroupOp` -> `omp::TaskgroupOp`
- `omp::DataBoundsOp` -> `omp::MapBoundsOp`
- `omp::DataOp` -> `omp::TargetDataOp`
- `omp::EnterDataOp` -> `omp::TargetEnterDataOp`
- `omp::ExitDataOp` -> `omp::TargetExitDataOp`
- `omp::UpdateDataOp` -> `omp::TargetUpdateOp`
- `omp::ReductionDeclareOp` -> `omp::DeclareReductionOp`
- `omp::WsLoopOp` -> `omp::WsloopOp`

### CODE REVIEW

**Comment by skatrak** [comment]
Thank you Krzysztof for sharing your thoughts. I don't personally have an issue either way with regards to using dots or underscores for separating words in MLIR ops. The issue at the moment is that we use both, so it'd be nice to make it uniform. If we prefer underscores, then rather than changing the operation names that I initially proposed, in my opinion we should change these instead:
- `omp.critical.declare` -> `omp.critical_declare` / `omp.declare.critical` / keep it unchanged?
- `omp.reduction.declare` -> `omp.reduction_declare` / `omp.declare.reduction` / keep it unchanged?
- `omp.atomic.read` -> `omp.atomic_read`
- `omp.atomic.write` -> `omp.atomic_write`
- `omp.atomic.update` -> `omp.atomic_update`
- `omp.atomic.capture` -> `omp.atomic_capture`

**Comment by kparzysz** [comment]
> * `omp.critical.declare` -> `omp.critical_declare` / `omp.declare.critical` / keep it unchanged?
> * `omp.reduction.declare` -> `omp.reduction_declare` / `omp.declare.reduction` / keep it unchanged?

The first one doesn't exist in the spec, the second one is "declare reduction", so for consistency we should use the names with "declare_xyz".

> * `omp.atomic.read` -> `omp.atomic_read`
> * `omp.atomic.write` -> `omp.atomic_write`
> * `omp.atomic.update` -> `omp.atomic_update`
> * `omp.atomic.capture` -> `omp.atomic_capture`

The "read", "write", etc. are clauses, so "atomic read" is not a name.  I suggest keeping the . as a separator here.

**Comment by luporl** [comment]
>   * `omp.target_enter_data` -> `omp.target.enterdata`
>   * `omp.target_exit_data` -> `omp.target.exitdata`
> 
Why not `omp.target.enter_data` and `omp.target.exit_data`? The words are separate in the spec.

**Comment by kparzysz** [comment]
> Why not `omp.target.enter_data` and `omp.target.exit_data`? The words are separate in the spec.

"target enter data" and "target exit data" are construct names in the spec.

**Comment by skatrak** [comment]
Thank you all for your comments. Here's an RFC I just created for this: https://discourse.llvm.org/t/rfc-uniformize-openmp-dialect-operation-names/77715. I updated the proposal from what it's currently done in this patch, hopefully addressing most concerns shared so far.

**Review by kparzysz — APPROVED** [review]
LGTM, thanks!

**Review by kiranchandramohan — APPROVED** [review]
LGTM. Nice work!

**Pull request merged**
