### PR TITLE
[Github] Do not label clang-format files as clang

### PR DESCRIPTION
**Pull request by cor3ntin**

### CODE REVIEW

**Review by tstellar — APPROVED** [review]

**Comment by tstellar** [comment]
This LGTM, but you should get an OK from @AaronBallman

**Review by Endilll — APPROVED** [review]

**Comment by Endilll** [comment]
> This LGTM, but you should get an OK from @AaronBallman

This takes us where we are in bug tracker, i.e. `clang` label doesn't duplicate `clang:*` and `clang-*` labels.
If this gets rejected, I think we're in trouble.

**Comment by cor3ntin** [comment]
@tstellar @Endilll This is mostly a clutch. if we want to support `clang:foo` not adding `clang`, I think in the long run we will have to fork the action and adding that ourselves. Expressing everything in terms of negative regex is just way too brittle.

**Comment by Endilll** [comment]
Totally agree, but we need to do something quickly, while number of PRs hasn't went out of hand (I see we have about 600-700 PRs a week), and we can fix things retroactively. I'm fine waiting for a better implementation (forking labeler), if there's anyone willing to get to it until the end of next week. Otherwise, I'll prepare brittle exclusion rules today.

I don't want our PRs end in the same sorry state as our bug tracker.

**Comment by cor3ntin** [comment]
I had a chat with Aaron yesterday, he was favorable to merge that, so I'll go ahead.
We had a chat about whether a more general solution was needed, and if so we can implement something better than negative matches, but this require a longer discussion (ad quite a bit more work) and we might not have consensus to do so. I wrote up my thoughts here https://discourse.llvm.org/t/hows-it-going-with-pull-requests/73467/27?u=cor3ntin

**Pull request merged**
