### PR TITLE
[libc++] Remove a few transitive includes

### PR DESCRIPTION
**Pull request by philnik777**

### CODE REVIEW

**Comment by philnik777** [comment]
I'm landing this, since the CI is happy and this shouldn't be in any way controversial.

**Comment by ldionne** [comment]
Wait, this is changing the exposed transitive includes in C++03/11/14/17/20 though. We normally only do that when we really need to. Is there a reason why you are doing that in this PR? This is effectively a breaking change.

**Comment by philnik777** [comment]
> Wait, this is changing the exposed transitive includes in C++03/11/14/17/20 though. We normally only do that when we really need to. Is there a reason why you are doing that in this PR? This is effectively a breaking change.

I've only added includes and the one I added was `<version>`. That was already included transitively, it just didn't show up because we're not listing the transitive closure. We should probably do that, since there is no reason not to and just leads to confusion.

**Comment by ldionne** [comment]
> > Wait, this is changing the exposed transitive includes in C++03/11/14/17/20 though. We normally only do that when we really need to. Is there a reason why you are doing that in this PR? This is effectively a breaking change.
> 
> I've only added includes and the one I added was `<version>`. That was already included transitively, it just didn't show up because we're not listing the transitive closure. We should probably do that, since there is no reason not to and just leads to confusion.

We actually used to and we stopped doing that because we wanted the ability to generate a dependency graph from these CSV files (in particular to detect cycles). I'm not sure we actually use that though, and in practice I agree that not storing the transitive closure makes these CSV files extremely difficult to understand.

LGTM.

**Pull request merged**
