### PR TITLE
[OpenMP][AArch64] Workaround for ompt/synchronization tests

### PR DESCRIPTION
**Pull request by ceseo**
ompt/synchronization/[masked.c | master.c] tests fail due to a wrong offset being calculated for the possible return addreses. PR #65936 fixes this for Darwin and the same has to be done for Linux.

Updates #69627

### CODE REVIEW

**Comment by jprotze** [comment]
Do we test ompt on other os than Darwin/Linux? In any case, I suggest to drop the else case and therefore the whole check for os. Just allow any 1,2,3 instruction offset for aarch64.

**Comment by ceseo** [comment]
> Do we test ompt on other os than Darwin/Linux? In any case, I suggest to drop the else case and therefore the whole check for os. Just allow any 1,2,3 instruction offset for aarch64.

I think Windows. But I don't have a Windows on Arm system to check whether it works or not, unfortunately.

**Comment by jprotze** [comment]
The OMPT tests test the codeptr address for plausibility. The main goal is to test that the codeptr does not point to a completely other part of the code (e.g. a frame nested in the runtime call).
Adding another value to the `print_possible_return_addresses` function means that the test will accept an additional value for codeptr. This will not break tests but potentially unbreak tests. We don't care too much about the precise value at this point.

For a precise testing, we would need to involve debug information and check whether we can successfully map back the codeptr address to the source code line. At the same time, this approach would allow to test the quality of debug information generated by the compiler.
The main reason for not implementing such testing yet is that it seemed cumbersome to set up a portable workflow considering different `addr2line` tools, supported dwarf versions by the installed tools, _locales_ settings ... .

**Comment by ceseo** [comment]
> The OMPT tests test the codeptr address for plausibility. The main goal is to test that the codeptr does not point to a completely other part of the code (e.g. a frame nested in the runtime call). Adding another value to the `print_possible_return_addresses` function means that the test will accept an additional value for codeptr. This will not break tests but potentially unbreak tests. We don't care too much about the precise value at this point.
> 
> For a precise testing, we would need to involve debug information and check whether we can successfully map back the codeptr address to the source code line. At the same time, this approach would allow to test the quality of debug information generated by the compiler. The main reason for not implementing such testing yet is that it seemed cumbersome to set up a portable workflow considering different `addr2line` tools, supported dwarf versions by the installed tools, _locales_ settings ... .

Right, so I think it makes sense to just drop the OS check for now. I'll re-sbumit the PR.

**Comment by jprotze** [comment]
> Right, so I think it makes sense to just drop the OS check for now. I'll re-sbumit the PR.

You can just push a fix to your branch. The PR will be squashed at the end.

**Comment by ceseo** [comment]
> > Right, so I think it makes sense to just drop the OS check for now. I'll re-sbumit the PR.
> 
> You can just push a fix to your branch. The PR will be squashed at the end.

Done

**Review by jprotze — APPROVED** [review]
lgtm

**Pull request merged**
