### PR TITLE
Reland "[NVPTX] deprecate nvvm.rotate.* intrinsics, cleanup funnel-shift handling"

### PR DESCRIPTION
**Pull request by AlexMaclean**
This change deprecates the following intrinsics which can be trivially
converted to llvm funnel-shift intrinsics:

- @llvm.nvvm.rotate.b32
- @llvm.nvvm.rotate.right.b64
- @llvm.nvvm.rotate.b64

This fixes a bug in the previous version (#107655) which flipped the order of the operands to the PTX funnel shift instruction. In LLVM IR the high bits are the first arg and the low bits are the second arg, while in PTX this is reversed.

### CODE REVIEW

**Comment by Artem-B** [comment]
> In LLVM IR the high bits are the first arg and the low bits are the second arg, while in PTX this is reversed.

Oh. OH. Ouch!

Indeed: https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#logic-and-shift-instructions-shf
>  `shf.l.mode.b32  d, a, b, c;`  // left shift
> ...
> Operand `b` holds bits 63:32 and operand `a` holds bits 31:0 of the 64-bit source value.

**Comment by Artem-B** [comment]
Would it be possible for you to cherry-pick the original commits into the pull request branch, and then add a commit with the fixes, so it's easy to see what you had to change to fix the issue?

**Comment by AlexMaclean** [comment]
> Would it be possible for you to cherry-pick the original commits into the pull request branch, and then add a commit with the fixes, so it's easy to see what you had to change to fix the issue?

The current version has the a cherry-pick of the original change on main that came from landing the previous MR, followed by a commit with the fixes. Does that work? Or do you want me to cherry-pick each commit from the previous branch for the first MR?

**Comment by Artem-B** [comment]
Never mind. PR has exactly what I wanted. I was looking at the github's 'Compare' link on your last update, which only touched the tests. Commit 9ebcfbfc6cb751c1264f19beaeac6d7b4f1fc644 is exactly what I wanted to see. Sorry about the noise.

**Review by Artem-B — APPROVED** [review]

**Comment by AlexMaclean** [comment]
@steelannelida Could you please confirm this version does not produce the numerical discrepancies observed previously? Thanks!

**Comment by steelannelida** [comment]
> @steelannelida Could you please confirm this version does not produce the numerical discrepancies observed previously? Thanks!

Hi! Thank you for asking. I tried reproducing and I see no failures with this version.

**Review by steelannelida — APPROVED** [review]

**Pull request merged**
