### PR TITLE
[clang][dataflow] Refactor `PropagateResultObject()` with a switch statement.

### PR DESCRIPTION
**Pull request by martinboehme**
See also discussion in #88726.

### CODE REVIEW

**Comment by martinboehme** [comment]
Here's a draft that shows what `PropagateResultObject()` looks like when refactored using a switch statement.

I'm not sure if this is an improvement or not. I do see how this makes the case distinction clearer -- OTOH, we have one more level of indentation now (though that doesn't really hurt formatting), and there's duplication between the switch cases and the casts, for example:

```cxx
      case Stmt::BinaryOperatorClass: {
        auto *Op = cast<BinaryOperator>(E);
```

Would appreciate opinions.

**Comment by ymand** [comment]
Clearly, this is a matter of taste, so I would defer to your opinion, since you are the primary maintainer of this code. But, personally, I prefer this style since it makes clear that the body of the function is a single case analysis, which is not obvious from the series of if statements. It's unfortunate that the enum syntax is so bulky (the need for `Stmt::` and the `Class` suffix). The casts don't bother me (well, any more than C++'s general lack of built-in datatype and pattern matching support bother me :)).

**Comment by martinboehme** [comment]
> Clearly, this is a matter of taste, so I would defer to your opinion, since you are the primary maintainer of this code. But, personally, I prefer this style since it makes clear that the body of the function is a single case analysis, which is not obvious from the series of if statements. It's unfortunate that the enum syntax is so bulky (the need for `Stmt::` and the `Class` suffix). The casts don't bother me (well, any more than C++'s general lack of built-in datatype and pattern matching support bother me :)).

I think maybe I'm coming round to your point of view (or, at least, I no longer clearly believe that the existing version is better).

I'm making this a non-draft PR and will add @Xazax-hun for an additional opinion. I have some other PRs in flight though that also touch `PropagateResultObject()`, and my plan is to land those first. In the meantime, I think the direction of this PR is clear though, so I think it makes sense to review.

**Comment by Xazax-hun** [comment]
> It's unfortunate that the enum syntax is so bulky (the need for `Stmt::` and the `Class` suffix).

Once we can use C++20, it could get a bit better thanks to https://en.cppreference.com/w/cpp/language/enum#Using-enum-declaration.

> I'm making this a non-draft PR and will add @Xazax-hun for an additional opinion.

I also don't have a strong opinion; I am fine with both styles. That being said, if C++ gets proper pattern matching in the future, the switch might be easier to refactor.

**Comment by martinboehme** [comment]
> > It's unfortunate that the enum syntax is so bulky (the need for `Stmt::` and the `Class` suffix).
> 
> Once we can use C++20, it could get a bit better thanks to https://en.cppreference.com/w/cpp/language/enum#Using-enum-declaration.

Good point, thanks.

> > I'm making this a non-draft PR and will add @Xazax-hun for an additional opinion.
> 
> I also don't have a strong opinion; I am fine with both styles. That being said, if C++ gets proper pattern matching in the future, the switch might be easier to refactor.

Thanks for your input!

So I think given that you and I are fine with both options and @ymand has a preference for the switch statement, I'll go with the switch statement.

In the meantime, I've landed two other PRs that touch `PropagateResultObject()` (#88872 and #88875). I'll integrate those changes in this PR and will ping the review thread once that has happened.

**Comment by martinboehme** [comment]
Ready for review.

**Review by ymand — APPROVED** [review]
Thanks!

**Review by Xazax-hun — APPROVED** [review]

**Comment by martinboehme** [comment]
Didn't notice that there were failing tests in CI. Reverting.

**Comment by martinboehme** [comment]
First of all, a followup: I should of course have noticed the failling CI tests, but a contributing factor was that I was locally running tests in `Release` mode, i.e. with `assert()` compiled out.

I've now looked at why tests fail, and it is because when using `E->getStmtClass()`, we need to enumerate all possible sub-classes that we're interested in, whereas when using `isa` / `dyn_cast`, it's enough to switch on the base class.

In practical terms, this means that to get complete coverage for what used to be covered by `isa<CXXConstructExpr>(E)`, we need to check not only for `CXXConstructExprClass` but also `CXXTemporaryObjectExprClass`. To get coverage for what used to be covered by `isa<CallExpr>(E)`, we need to check not only for `CallExprClass` but also for `CXXMemberCallExprClass` and `CXXOperatorCallExprClass`.

In my mind, this shifts the tradeoff: Having to enumerate all possible sub-classes adds verbosity and carries the risk of forgetting a subclass, particularly if subclasses are added in the future.

I would therefore propose to stay with the existing implementation as I'm no longer convinced that the switch statement is the better option.

**Pull request merged**
