### PR TITLE
[AMDGPU] Fix typo in promoteUniformOpToI32

### PR DESCRIPTION
**Pull request by Pierre-vh**

### CODE REVIEW

**Review by arsenm — APPROVED** [review]
Missing test?

**Comment by Pierre-vh** [comment]
There were no test updates, we either don't have the coverage or this somehow didn't cause any issue due to something else taking care of it?

**Comment by arsenm** [comment]
> There were no test updates, we either don't have the coverage or this somehow didn't cause any issue due to something else taking care of it?

I assume there's missing test coverage

**Comment by Pierre-vh** [comment]
I don't have time to look at adding tests right now as I'll be OOO for the rest of the week, so I opened an issue to keep track of it: #109956

**Pull request merged**
