### PR TITLE
[libcxx] Provide locale conversions to tests through lit substitution

### PR DESCRIPTION
**Pull request by 4-rodrigo-salazar**
There are 2 problems today that this PR resolves:

- libcxx tests assume the thousands separator for fr_FR locale is x00A0 on Windows. This currently fails when run on newer versions of Windows (It seems to have been updated to the new correct value of 0x202F around windows 11. The exact windows version where it changed doesn't seem to be documented anywhere). Depending the OS version, you need different values.
- There are several ifdefs to determine the environment/platform-specific locale conversion values and it leads to maintenance as things change over time.

This PR includes the following changes:
- Provide the environment's locale conversion values through a substitution. The test can opt in by placing the substitution value in a define flag.
- Remove the platform ifdefs (the swapping of values between Windows, Linux, Apple, AIX).

This is accomplished through a lit feature action that fetches the environment's locale conversions (lconv) for members like 'thousands_sep' that we need to provide. This should ensure that we don't lose the effectiveness of the test itself.

In addition, as a result of the above, this PR:
- Fixes a handful of locale tests which unexpectedly fail on newer windows versions.
- Resolves 3 XFAIL FIX-MEs.

### CODE REVIEW

**Comment by 4-rodrigo-salazar** [comment]
Seeing unrelated test timeouts on some of the build checks. Will merge up against main tomorrow to see if it looks better.

**Comment by mstorsjo** [comment]
Hey, @4-rodrigo-salazar - I see you closed this PR... I presume this was due to the lack of reviews?

I'd be interested in picking this up and pushing it forward, if you don't have time/interest to do it. Were there any other issues with it that you would like to share?

I looked at the issue with escaping of backslashes, which seemed to require changes to the core of `TestRunner`; I filed #103042, which should fix and make those aspects consistent in lit, allowing us to get rid of all the changes to lit within this patch. And with that fix in place, I'd see less potential hangups in this patch, so I'd hope to be able to push to get reviews to get it merged.

**Comment by ldionne** [comment]
FWIW I agree -- there are some things to change in this patch but I think the direction makes sense. It cleans up a lot of complexity in the test suite.

**Comment by mstorsjo** [comment]
I reopened a new PR for pushing this further, in #105651.

**Pull request closed without merging**
