### PR TITLE
[GISel][RISCV] Use isSExtCheaperThanZExt when widening G_ICMP.

### PR DESCRIPTION
**Pull request by topperc**
Sign extending i32->i64 is more efficient than zero extend for RV64.

### CODE REVIEW

**Review by arsenm — APPROVED** [review]
It would be nicer if this was bundled into the requested legalize action

**Comment by aemerson** [comment]
Curious: why is it correct to do a sign-extend for an unsigned comparison promotion?

**Comment by arsenm** [comment]
> Curious: why is it correct to do a sign-extend for an unsigned comparison promotion?

eq / ne / true / false aren't really signed or unsigned, you just need to treat the high bits consistently in both operands

**Comment by aemerson** [comment]
> > Curious: why is it correct to do a sign-extend for an unsigned comparison promotion?
> 
> eq / ne / true / false aren't really signed or unsigned, you just need to treat the high bits consistently in both operands

Right but those aren't the only conditions potentially being handled here? There's also the `ule, ugt...`

**Comment by aemerson** [comment]
> > > Curious: why is it correct to do a sign-extend for an unsigned comparison promotion?
> > 
> > 
> > eq / ne / true / false aren't really signed or unsigned, you just need to treat the high bits consistently in both operands
> 
> This isn't limited eq / ne / true / false. It works for ugt/uge/ult/ule too.
> 
> Sign extending an unsigned value doesn't change 0x00000000-0x7ffffff and it makes 0x8000000-0xffffffff into even larger numbers without affecting their relative order.

Makes sense.

**Review by aemerson — APPROVED** [review]

**Pull request merged**
