### PR TITLE
[Flang][OpenMP] Handle SECTION construct from within SECTIONS

### PR DESCRIPTION
**Pull request by kparzysz**
Introduce `createSectionOp`, invoke it from the SECTIONS construct for each nested SECTION construct. This makes it unnecessary to embed OpenMPSectionConstruct inside of OpenMP~~Section~~Construct anymore.

Recursive lowering [3/5]

### CODE REVIEW

**Review by skatrak — APPROVED** [review]
Thanks, LGTM!

**Comment by kiranchandramohan** [comment]
> This makes it unnecessary to embed OpenMPSectionConstruct inside of OpenMPSectionConstruct anymore.
What do you mean by this? Is there a typo?

Would we be able to remove `OpenMPSectionConstruct` from `struct OpenMPConstruct` after this change?
https://github.com/llvm/llvm-project/blob/2f2217a8f7ad68b2d9374e0515f02e6752acd126/flang/include/flang/Parser/parse-tree.h#L3990

**Comment by kparzysz** [comment]
> > This makes it unnecessary to embed OpenMPSectionConstruct inside of OpenMPSectionConstruct anymore.
> 
> What do you mean by this? Is there a typo?

Yes, fixed.  I meant embedding it inside of `OpenMPConstruct`.  Thanks for the catch.

> Would we be able to remove `OpenMPSectionConstruct` from `struct OpenMPConstruct` after this change?

Yes.

**Comment by kiranchandramohan** [comment]
> Introduce createSectionOp

`genSectionOp`?

**Review by kiranchandramohan — APPROVED** [review]
LG.

**Comment by kparzysz** [comment]
> > Introduce createSectionOp
> 
> `genSectionOp`?

Yes---fixed the commit message.

**Pull request merged**
