### PR TITLE
Revert "Switch builtin strings to use string tables"

### PR DESCRIPTION
**Pull request by chandlerc**
Reverts llvm/llvm-project#118734

There are currently some specific versions of MSVC that are miscompiling this code (we think). We don't know why as all the other build bots and at least some folks' local Windows builds work fine.

This is a candidate revert to help the relevant folks catch their builders up and have time to debug the issue. However, the expectation is to roll forward at some point with a workaround if at all possible.

### CODE REVIEW

**Review by dyung — APPROVED** [review]
LGTM

**Comment by dyung** [comment]
I'm going to bring out Windows buildbot back online that was failing so that when you do submit the revert, the bot should go back to green. I am looking into this and will get back to you on the original bug when I find something.

**Comment by chandlerc** [comment]
> I'm going to bring out Windows buildbot back online that was failing so that when you do submit the revert, the bot should go back to green. I am looking into this and will get back to you on the original bug when I find something.

So, the builder came back up, and is now passing without this landing...

Here is the first build after it came back up: https://lab.llvm.org/buildbot/#/builders/46/builds/9173

And I went through the output and found a specific test that was failing, and it seems to pass?
```
PASS: Clang :: AST/builtins-arm-strex-rettype.c (433 of 81898)
```

So maybe this was a transient issue that has been fixed, or some stale state?

**Comment by chandlerc** [comment]
Sorry, let's keep discussion on the original PR -- I'll go post there.

**Comment by chandlerc** [comment]
Build bot with the issue is now online and failing as expected, merging this revert to get in green (we hope).

**Pull request merged**
