### PR TITLE
[llvm-c] Provide LLVMGetGEPResultElementType

### PR DESCRIPTION
**Pull request by vaivaswatha**

### CODE REVIEW

**Comment by nikic** [comment]
Why do you need this? Use of getResultElementType() is something of a red flag, and I do not want to expose it to the C API unless there is a strong need.

**Comment by vaivaswatha** [comment]
> Why do you need this? Use of getResultElementType() is something of a red flag, and I do not want to expose it to the C API unless there is a strong need.

Is there any other way to get a GEP's result element type using the C API? Since the instruction's type itself is just an opaque pointer type, I couldn't find any other way to get this.

I'm trying to build my own internal representation of LLVM-IR, so I'd need this for a complete translation.

**Comment by vaivaswatha** [comment]
May I ask why it's a red flag?

**Comment by nikic** [comment]
> > Why do you need this? Use of getResultElementType() is something of a red flag, and I do not want to expose it to the C API unless there is a strong need.
> 
> Is there any other way to get a GEP's result element type using the C API? Since the instruction's type itself is just an opaque pointer type, I couldn't find any other way to get this.
> 
> I'm trying to build my own internal representation of LLVM-IR, so I'd need this for a complete translation.

The result element type is redundant information implied by the source element type and the GEP arguments. GEPs currently explicitly store it, but this is largely for historical reasons -- prior to opaque pointers, it was commonly used. Nowadays we could probably remove it. I think the only half-way legitimate use-case for it is to check type compatibility when merging two GEPs into one.

Your internal IR representation shouldn't care about the result element type, only the source element type.

**Comment by vaivaswatha** [comment]
>The result element type is redundant information implied by the source element type and the GEP arguments

True, but then shouldn't `getIndexedType` be available for use in the C-API?. Without it, someone using the C-API would need to reimplement it to compute the result element type (as far as I can tell, please correct me if there's some way to compute it already).

**Comment by nikic** [comment]
> > The result element type is redundant information implied by the source element type and the GEP arguments
> 
> True, but then shouldn't `getIndexedType` be available for use in the C-API?. Without it, someone using the C-API would need to reimplement it to compute the result element type (as far as I can tell, please correct me if there's some way to compute it already).

My primary point is that you shouldn't need any of these at all. Can you please explain in more detail how you are going to use this API?

**Comment by vaivaswatha** [comment]
> > > The result element type is redundant information implied by the source element type and the GEP arguments
> > 
> > 
> > True, but then shouldn't `getIndexedType` be available for use in the C-API?. Without it, someone using the C-API would need to reimplement it to compute the result element type (as far as I can tell, please correct me if there's some way to compute it already).
> 
> My primary point is that you shouldn't need any of these at all. Can you please explain in more detail how you are going to use this API?

To begin with, I'm just trying to read the IR and kind of type-check it all myself. So I need to know the type that the GEP's result pointer is pointing to.

Is there a design philosophy that the C-API needs to be minimal / restricted and not be as general as the C++ API? If `getIndexedType` is part of the C++ public API, I fail to understand why it can't be part of the C-API.

**Pull request closed without merging**
