### PR TITLE
[compiler-rt][X86] Use functions in cpuid.h instead of inline assembly

### PR DESCRIPTION
**Pull request by boomanaiden154**
This patch makes the host/feature detection in compiler-rt and LLVM use the functions provided in cpuid.h(__get_cpuid, __get_cpuid_count) instead of inline assembly. This simplifies the implementation and moves any inline assembly away to a more common place.

A while ago, some similar cleanup was attempted, but this ended up resulting in some compilation errors due to toolchain minimum version issues (https://bugs.llvm.org/show_bug.cgi?id=30384). After the reversion landed, there have been no attempts since then to clean up the code, even though the minimum supported compilers now support the relevant functions (https://godbolt.org/z/o1Mjz8ndv).

### CODE REVIEW

**Comment by MaskRay** [comment]
clang/lib/Headers/cpuid.h did not define `__get_cpuid_count` before f6e8408a116405d0cc25b506e8c5b60ab4ab7bcd (2017). Clang 5.0.0 (Sep 2017) contains the commit. Nice:)

**Review by MaskRay — APPROVED** [review]

**Comment by boomanaiden154** [comment]
> clang/lib/Headers/cpuid.h did not define __get_cpuid_count before https://github.com/llvm/llvm-project/commit/f6e8408a116405d0cc25b506e8c5b60ab4ab7bcd (2017). Clang 5.0.0 (Sep 2017 https://www.llvm.org/docs/GettingStarted.html#host-c-toolchain-both-compiler-and-standard-library) contains the commit. Nice:)

Yep. I was a bit surprised when I saw everything was included in the minimum supported compiler versions as well. It definitely makes the code a lot cleaner and hopefully more robust as now there's one less inline assembly implementation.

**Comment by kraj** [comment]
@boomanaiden154 this is causing a build regression when compiling standalone compiler-rt for x86_64 in a cross build environment

```
/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/compiler-rt/20.0.0/recipe-sysroot-native/usr/bin/x86_64-yoe-linux-musl/x86_64-yoe-linux-musl-clang --target=x86_64-yoe-linux-musl --sysroot=/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/compiler-rt/20.0.0/recipe-sysroot -DVISIBILITY_HIDDEN -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/compiler-rt/20.0.0/compiler-rt-20.0.0/projects/compiler-rt/lib/builtins -I/mnt/b/yoe/master/workspace/sources/llvm-project/compiler-rt/lib/builtins -I/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/compiler-rt/20.0.0/compiler-rt-20.0.0/include -I/mnt/b/yoe/master/workspace/sources/llvm-project/llvm/include -target x86_64-yoe-linux-musl  -m64 -march=core2 -mtune=core2 -msse3 -mfpmath=sse -mlittle-endian --dyld-prefix=/usr -Qunused-arguments -fstack-protector-strong  -O2 -D_FORTIFY_SOURCE=2 -Wformat -Wformat-security -Werror=format-security  --sysroot=/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/compiler-rt/20.0.0/recipe-sysroot  -O2 -g   -fmacro-prefix-map=/mnt/b/yoe/master/workspace/sources/llvm-project=/usr/src/debug/compiler-rt/20.0.0  -fdebug-prefix-map=/mnt/b/yoe/master/workspace/sources/llvm-project=/usr/src/debug/compiler-rt/20.0.0  -fmacro-prefix-map=/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/compiler-rt/20.0.0/compiler-rt-20.0.0=/usr/src/debug/compiler-rt/20.0.0  -fdebug-prefix-map=/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/compiler-rt/20.0.0/compiler-rt-20.0.0=/usr/src/debug/compiler-rt/20.0.0  -fdebug-prefix-map=/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/compiler-rt/20.0.0/recipe-sysroot=  -fmacro-prefix-map=/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/compiler-rt/20.0.0/recipe-sysroot=  -fdebug-prefix-map=/mnt/b/yoe/master/build/tmp/work/core2-64-yoe-linux-musl/compiler-rt/20.0.0/recipe-sysroot-native=  -pipe -fPIC -fno-semantic-interposition -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -Wno-unused-parameter -O2 -g -DNDEBUG -fPIC -fno-lto -Werror=array-bounds -Werror=uninitialized -Werror=shadow -Werror=empty-body -Werror=sizeof-pointer-memaccess -Werror=sizeof-array-argument -Werror=suspicious-memaccess -Werror=builtin-memcpy-chk-size -Werror=array-bounds-pointer-arithmetic -Werror=return-stack-address -Werror=sizeof-array-decay -Werror=format-insufficient-args -Wformat -std=c11 -DCOMPILER_RT_HAS_FLOAT16 -MD -MT projects/compiler-rt/lib/builtins/CMakeFiles/clang_rt.builtins-x86_64.dir/cpu_model/x86.c.o -MF projects/compiler-rt/lib/builtins/CMakeFiles/clang_rt.builtins-x86_64.dir/cpu_model/x86.c.o.d -o projects/compiler-rt/lib/builtins/CMakeFiles/clang_rt.builtins-x86_64.dir/cpu_model/x86.c.o -c /mnt/b/yoe/master/workspace/sources/llvm-project/compiler-rt/lib/builtins/cpu_model/x86.c

/mnt/b/yoe/master/workspace/sources/llvm-project/compiler-rt/lib/builtins/cpu_model/x86.c:27:10: fatal error: 'cpuid.h' file not found
   27 | #include "cpuid.h"
      |          ^~~~~~~~~
1 error generated.
ninja: build stopped: subcommand failed.
```

if I manually add ` -I/mnt/b/yoe/master/workspace/sources/llvm-project/clang/lib/Headers/` to compiler invocation then it works but I thought it should be automatically added ?

**Comment by boomanaiden154** [comment]
You're going to have to provide more details about your environment.

The compiler invocation should theoretically pickup the builtin headers. I'm not sure why it isn't in your environment. That (to me) seems like an issue with your environment rather than an issue with the patch though.

**Comment by kraj** [comment]
> You're going to have to provide more details about your environment.
> 
> The compiler invocation should theoretically pickup the builtin headers. I'm not sure why it isn't in your environment. That (to me) seems like an issue with your environment rather than an issue with the patch though.

its possible, let me do a bit more diving, if I revert this patch then it starts to build which is perhaps that it does not need to include the header so it works.

**Comment by kraj** [comment]
> > You're going to have to provide more details about your environment.
> > The compiler invocation should theoretically pickup the builtin headers. I'm not sure why it isn't in your environment. That (to me) seems like an issue with your environment rather than an issue with the patch though.
> 
> its possible, let me do a bit more diving, if I revert this patch then it starts to build which is perhaps that it does not need to include the header so it works.

yeah pilot error ! a rebase of local patch went wrong.  sorry for noise.

**Pull request merged**
