### PR TITLE
[mlir][scf] Implement getSingle... of LoopLikeOpinterface for scf::ParallelOp

### PR DESCRIPTION
**Pull request by ubfx**
This adds implementations for `getSingleIterationVar`, `getSingleLowerBound`, `getSingleUpperBound`, `getSingleStep` of `LoopLikeOpInterface` to `scf::ParallelOp`. Until now, the implementations for these methods defaulted to returning `std::nullopt`, even in the special case where the parallel Op only has one dimension.

Related: https://github.com/llvm/llvm-project/pull/67883

### CODE REVIEW

**Review by ftynse — APPROVED** [review]
I don't suppose there is any chance to test this without writing a heavy unittest?

**Comment by ubfx** [comment]
> I don't suppose there is any chance to test this without writing a heavy unittest?

I think a unittest for `LoopLikeOpInterface` would be a good idea, I'll take a look

**Comment by ubfx** [comment]
What do you think about something like this?
https://github.com/llvm/llvm-project/commit/aa464d24bb1ed74f4ec0dc56642d0b22f4be6c03

It might be a little overkill just for the `getSingle...` methods but maybe getting started on some unittests for the SCF dialect is useful beyond that.

**Comment by ftynse** [comment]
LGTM

**Comment by joker-eph** [comment]
> I don't suppose there is any chance to test this without writing a heavy unittest?

Actually I don't understand why this is a C++ unit-test. We have quite a track record of not doing so and making test passes instead. 

Unless I'm missing something this could easily be done that way?

**Comment by ubfx** [comment]
I will take a look at this and rewrite it into a test pass if possible

**Pull request merged**
