### PR TITLE
[NVPTX] Add support for atomic add for bf16 type

### PR DESCRIPTION
**Pull request by akuegel**
atom.add.noftz.bf16 is supported since SM 9.0 and PTX 7.8

### CODE REVIEW

**Review by Artem-B — COMMENTED** [review]
LGTM.

Do we need to worry about denormals? I.e. we only have noftz variant of the atomic, which potentially will give us different results that a regular addition would, depending on denormals handling mode. Do we need to add an extra op that folds denormals to zero when normal FP ops would be expected to do so?

I'm way out of my depth on FP handling nuances here. We need to ask an FP expert.

**Comment by akuegel** [comment]
@Artem-B Do you know someone we could ask who is a floating point expert?
Note that in my previous change where I added support for f16 type, I also didn't handle the case with ftz mode. So do I need to revert that previous patch?

**Comment by Artem-B** [comment]
> Do you know someone we could ask who is a floating point expert?

@majnemer Do you have an opinion on atomics and denormals handling for bf16/f16? Who would be the right folks to consult on that?

**Comment by majnemer** [comment]
I think it is OK for us not to do anything special for `noftz`.

It is a bit tricky to fix it post-hoc because of cases like:
```
  x = 0
  x += 0x1.02p-126
  x += -0x1p-126
```
  
Here, none of the inputs were subnormal but `x` ends up as `0x1p-133` which is subnormal.

Also, LLVM semantics allow us to return subnormal results instead of flushing.

LGTM.

**Review by Artem-B — APPROVED** [review]

**Pull request merged**
