### PR TITLE
[LLVM] Update SelectionDAG maintainers

### PR DESCRIPTION
**Pull request by nikic**
@bogner I currently have you listed as the SDAG maintainer, but I think that nowadays you mostly work on DirectX and aren't actively involved with SDAG anymore, right?

If so, I'd like to nominate new maintainers for this component. My suggestion would @RKSimon and @topperc, if one or both of you are up for it.

### CODE REVIEW

**Comment by topperc** [comment]
I accept

**Review by RKSimon — APPROVED** [review]
No problem, happy to take it on.

**Review by topperc — APPROVED** [review]
LGTM

**Review by bogner — APPROVED** [review]
Yep, I’ve been negligent on maintaining SelectionDAG for a long time, happy for others to take this on.

**Pull request merged**
