### PR TITLE
[llvm-exegesis] Replace --num-repetitions with --min-instructions

### LINKED ISSUE #76890: [llvm-exegesis] --num-repetitions is inconsistent with its name
Currently, the `--num-repetitions` flag in `llvm-exegesis` specifies the minimum number of instructions that should be executed rather than the number of repetitions of the snippe that should be run. This doesn't create confusion when benchmarking individual instructions, but does create confusion when the user is benchmarking a snippet as the number of repetitions is not equal to the number of instructions anymore. It seems like this flag was left over from before `llvm-exegesis` could execute snippets.

It seems like this flag should be renamed to something like `--min-instructions` to avoid user confusion. This would be a breaking change, but would be a clean breaking change that does not silently fail anywhere.

@legrosbuffle - Thoughts on renaming this?

### PR DESCRIPTION
**Pull request by boomanaiden154**
This patch replaces --num-repetitions with --min-instructions to make it more clear that the value refers to the minimum number of instructions in the final assembled snippet rather than the number of repetitions  of the snippet. This patch also refactors some llvm-exegesis internal variable names to reflect the name change.

Fixes #76890.

### CODE REVIEW

**Comment by boomanaiden154** [comment]
This change would also end up impacting the `num_repetitions` field in the yaml input/output. I have it currently setup to accept both `min_instructions` and `num_repetitions` to preserve backwards compatibility. I'm assuming at some point we'll want to deprecate this old option? I've seen #38430 but it doesn't seem like there was a resolution there, so I'm unsure of the procedure here for changing the yaml schema.

**Comment by boomanaiden154** [comment]
@legrosbuffle This is ready for review when you have a chance. Thanks!

**Comment by legrosbuffle** [comment]
> I'm assuming at some point we'll want to deprecate this old option?

It's a single line of code so it probably can stay there for backwards compatibility :)

**Review by legrosbuffle — APPROVED** [review]

**Comment by boomanaiden154** [comment]
> It's a single line of code so it probably can stay there for backwards compatibility :)

Sounds good.

**Pull request merged**
