### PR TITLE
[mlir][ArmSME] Add masking support to memory ops

### PR DESCRIPTION
**Pull request by c-rhodes**
This patch series adds masking support to the ArmSME memory ops, as well as lowerings from Vector `transfer_read` and `vector.transfer_write`. The `transfer_read` to ArmSME is more complete than `transfer_write`, for the latter the VectorToArmSME lowering still needs fleshing out to support in-flight transpose via vertical load and integration tests need to be added.

This support is part of a wider effort to lower linalg.matmul to SME. There's a lot of changes here so I don't expect this to be reviewed as a whole, hence why I've created this as a draft PR. I plan to create separate PRs for each commit.

### CODE REVIEW

**Comment by c-rhodes** [comment]
cc @banach-space @MacDue

**Comment by banach-space** [comment]
Makes sense to me, I don't have any specific suggestions. We can dive into details separately for every patch. Thanks!

**Comment by c-rhodes** [comment]
PRs

#69195 - [mlir][ArmSME] Add optional padding and mask operands to tile_load
#70655 - [mlir][ArmSME] Add mask operand to load_tile_slice
#70814 - [mlir][ArmSME] Propagate pad and mask in vector.transfer_read lowering
#69186 - [mlir][ArmSME] Add tile slice layout attr to vector <-> tile ops
#70915 - [mlir][ArmSME] Add support for lowering masked tile_load ops
#70657 - [mlir][ArmSME] Add optional mask operand to tile_store
#70838 - [mlir][ArmSME] Add mask operand to store_tile_slice
#71180 - [mlir][ArmSME] Add support for lowering masked tile_store ops
#71181 - [mlir][ArmSME] Lower transfer_write + transpose to vertical store

**Comment by c-rhodes** [comment]
All changes have been landed in separate PRs, closing.

**Pull request closed without merging**
