### PR TITLE
[mlir][tblgen] Expose more of MLIRTableGen as library

### PR DESCRIPTION
**Pull request by makslevental**
I would like to expose/make available more (all?) of the tblgen utility code as a library. This will enable downstream projects/users to extend that code to implement such things as C API generation.

The strategy here is:

1. Move all impls currently in `mlir/tools/mlir-tblgen/*.cpp` to `mlir/lib/TableGen`;
2. Add headers and put various `emitDefs*` into them;
3. Move `static mlir::GenRegistration`s and `llvm::cl::opt`s to `mlir-tblgen.cpp`.

Nothing revolutionary but unfortunately lots of touched lines. 

The plan is to move more things into the headers as needed - I plan to experiment with downstream generation in the coming weeks.

Feel free to bikeshed homes of various `emitDefs*` and names of headers - I tried to group stuff that was related while still splitting somewhat.

### CODE REVIEW

**Comment by joker-eph** [comment]
We have to be careful here, because custom backends for ODS is something that I pushed back really hard from the beginning: the risk is that ODS loses it's aspect of being a clear spec (that is it is the language specification AND the backend) for dialect definitions and ultimately becomes just a "json" of losely defined (from a semantics point of view) constructions (ultimately you could even get to a point where each dialect would have its own backend).

**Comment by jpienaar** [comment]
There are two convos here, this change is trying to get mlir-tblgen in line with the other tools wrt where their implementation details live (the new lib/tools place was created after mlir-tblgen) and then a discussion on structuring.

I think we can treat these independent (the PR description makes it seem like its doing both at the same time rather than show potential future steps).

**Comment by jpienaar** [comment]
> (other tools got refactored because of the motivation to expose some APIs publicly / to downstream)

I'm not sure that holds for mlir-lsp-server :) 

We already have a list of APIs exposed for mlir-tblgen. This does expose more and I think valid question as to are too much exposed (I haven't looked yet) and what are the expectations around these. Especially as it is just generating code which is not done in too general a way. 

But there is also a different question being asked here: if downstream users want to add new features here & experiment, should they just work, do all their dev and come have the conversation later? Esp if experimental it may not be desirable upstream but if fully fork downstream then incentive/cost of making improvements/moving parts up is low/high (resp.).

I think your guard rail here is that this should not be considered as invitation to make tools that add other semantics to the ops (I don't think upstream or downstream matters much here). Is that correct? The current set up doesn't stop downstream forks of the ODS code, I could see from a maintenance cost it dissuading, but given the speed at which these move, its not a high cost. So it seems to be more of a policy discussion.

**Comment by makslevental** [comment]
closing in favor of https://github.com/llvm/llvm-project/pull/113781

**Comment by River707** [comment]
> > (other tools got refactored because of the motivation to expose some APIs publicly / to downstream)
> 
> I'm not sure that holds for mlir-lsp-server :)
> 
> We already have a list of APIs exposed for mlir-tblgen. This does expose more and I think valid question as to are too much exposed (I haven't looked yet) and what are the expectations around these. Especially as it is just generating code which is not done in too general a way.
> 
> But there is also a different question being asked here: if downstream users want to add new features here & experiment, should they just work, do all their dev and come have the conversation later? Esp if experimental it may not be desirable upstream but if fully fork downstream then incentive/cost of making improvements/moving parts up is low/high (resp.).
> 
> I think your guard rail here is that this should not be considered as invitation to make tools that add other semantics to the ops (I don't think upstream or downstream matters much here). Is that correct? The current set up doesn't stop downstream forks of the ODS code, I could see from a maintenance cost it dissuading, but given the speed at which these move, its not a high cost. So it seems to be more of a policy discussion.

I don't think it's a good comparison for tools that load MLIR dialects and agnostic tools. The tools using MLIR dialects (like mlir-lsp-server) were generalized because they had to be (i.e. how do I load my dialect without it being a library?). The tablegen tools IMO have mostly been operating under a good development cycle -> The emitters that generate c++ are in the end tool, whereas the wrappers around the TableGen API are in libraries. I don't yet understand the goal or value of moving the emitters to a library (because I don't understand what value that gives you?), as opposed to just invoking mlir-tblgen in your build.

**Pull request closed without merging**
