### PR TITLE
[AMDGPU] GISelShouldIgnore .td uses

### PR DESCRIPTION
**Pull request by jofrn**
[#88382](https://github.com/llvm/llvm-project/pull/88382) implements the new bit for `class Pattern` in `TargetSelectionDAG.td`.

This applies it to all affected Pattern records with a `warning: Skipped pattern:` from `-warn-on-skipped-patterns`.

### CODE REVIEW

**Review by arsenm — COMMENTED** [review]
Most or all of these shouldn't be added. The point is to silence the warnings for cases where we *never* want to import them. This is just hiding the useful warnings

**Comment by jofrn** [comment]
> Most or all of these shouldn't be added. The point is to silence the warnings for cases where we _never_ want to import them. This is just hiding the useful warnings

It definitely isn't all because this applies ShouldIgnore to each (and every) Pattern that we have. At least one Pattern'd be bound to require this...

**Comment by arsenm** [comment]
> will need to examine them more closely; you mentioned some time back that it should be only for patterns applied to scalars, correct? This commit is surely more than that, so will make the next one more precise and include only those.

Nothing about scalars, it's about usage intent. I think there were some pseudos we bypass which we don't need the pattern. I haven't looked at the -warn-on-skipped patterns output in a while so I don't remember what the obvious cases are

**Comment by jofrn** [comment]
I see. Alright, let's see then...

**Comment by arsenm** [comment]
Probably should just abandon this. We definitely do not want to blindly throw this on everything that fails to import. This is reserved as a tool for whenever someone is aiming for 100% pattern coverage

**Comment by jofrn** [comment]
Okay, that is good thinking since we do not want to commit this actually; ... closed it.

It can be used as a reference of all `Pattern`s that have a skipped pattern warning.

**Pull request closed without merging**
