### PR TITLE
[RISCV] Remove -riscv-v-vector-bits-min=128 in tests where implied by V. NFC

### PR DESCRIPTION
**Pull request by lukel97**
V implies Zvl128b, but a lot of the fixed vector tests also redundantly specify -riscv-v-vector-bits-min=128. This patch removes them where there isn't another minimum vlen being tested for, and for cases where Zve* is being used Zvl128b was added to maintain the old test diff (and because an awkward vlen probably isn't interesting to test for).

### CODE REVIEW

**Comment by topperc** [comment]
Are there tests that use sizes other than 128 that can be replaced with Zvl*b? Fixed vector uses to be off by default and required this -riscv-v-vector-bits-min. That's no longer true.

**Review by topperc — APPROVED** [review]
LGTM

**Comment by lukel97** [comment]
> Are there tests that use sizes other than 128 that can be replaced with Zvl*b? Fixed vector uses to be off by default and required this -riscv-v-vector-bits-min. That's no longer true.

Yeah, I've updated this PR to swap those out

**Review by topperc — APPROVED** [review]
Still LGTM

**Pull request merged**
