### PR TITLE
Remove clang-rename

### PR DESCRIPTION
**Pull request by AaronBallman**
clang-rename has largely been superseded by clangd and this project
hasn't received much attention in many years. Further, our
documentation on it still claims it's in very early stages of
development despite being ~10 years old. One of the primary people
driving the tool has mentioned that they don't believe there is a
reason to continue to support it unless it's still being actively
used (https://reviews.llvm.org/D148439#4303202) and I've found no
evidence to suggest that is the case.

Original RFC: https://discourse.llvm.org/t/rfc-time-to-deprecate-remove-clang-rename/70707

### CODE REVIEW

**Comment by cor3ntin** [comment]
can you inspect these files that still reference clang-rename?

```
lib/Tooling/Refactoring/Rename/RenamingAction.cpp:        errs() << "clang-rename: renamed at: " << SourceMgr.getFilename(FullLoc)
lib/Tooling/Refactoring/Rename/USRFindingAction.cpp:            "clang-rename could not find symbol (offset %0)");
lib/Tooling/Refactoring/Rename/USRFindingAction.cpp:          DiagnosticsEngine::Error, "clang-rename could not find symbol %0");
```

**Comment by cor3ntin** [comment]
Also these bazel build scripts

```
llvm/utils/gn/secondary/clang-tools-extra/test/BUILD.gn:    "//clang/tools/clang-rename",
llvm/utils/gn/secondary/clang/test/BUILD.gn:    "//clang/tools/clang-rename",
llvm/utils/gn/secondary/clang/tools/clang-rename/BUILD.gn:executable("clang-rename") {
utils/bazel/llvm-project-overlay/clang/BUILD.bazel:    "tools/clang-rename/clang-rename.el",
utils/bazel/llvm-project-overlay/clang/BUILD.bazel:    name = "clang-rename",
utils/bazel/llvm-project-overlay/clang/BUILD.bazel:    srcs = glob(["tools/clang-rename/*.cpp"]),
```

**Comment by AaronBallman** [comment]
> can you inspect these files that still reference clang-rename?
> 
> ```
> lib/Tooling/Refactoring/Rename/RenamingAction.cpp:        errs() << "clang-rename: renamed at: " << SourceMgr.getFilename(FullLoc)
> lib/Tooling/Refactoring/Rename/USRFindingAction.cpp:            "clang-rename could not find symbol (offset %0)");
> lib/Tooling/Refactoring/Rename/USRFindingAction.cpp:          DiagnosticsEngine::Error, "clang-rename could not find symbol %0");
> ```

Yeah, those confused me as well -- I think it's just happenstance that it uses `clang-rename` in those strings because as best I can tell, there's no relationship between `clang-rename` and `Tooling/Refactoring/Rename`. CC @hyp who may have more information.

**Comment by AaronBallman** [comment]
> Also these bazel build scripts
> 
> ```
> llvm/utils/gn/secondary/clang-tools-extra/test/BUILD.gn:    "//clang/tools/clang-rename",
> llvm/utils/gn/secondary/clang/test/BUILD.gn:    "//clang/tools/clang-rename",
> llvm/utils/gn/secondary/clang/tools/clang-rename/BUILD.gn:executable("clang-rename") {
> utils/bazel/llvm-project-overlay/clang/BUILD.bazel:    "tools/clang-rename/clang-rename.el",
> utils/bazel/llvm-project-overlay/clang/BUILD.bazel:    name = "clang-rename",
> utils/bazel/llvm-project-overlay/clang/BUILD.bazel:    srcs = glob(["tools/clang-rename/*.cpp"]),
> ```

I took a shot at those; I think `gn` and `Bazel` are traditionally outside the scope of what community supports though, so I don't know if I've done this right or not.

**Review by kirillbobyrev — APPROVED** [review]
I agree, clang-rename should probably be removed. I haven't touched it in years and its usability has dropped over the last few years after I re-implemented the most useful functionality in clangd.

**Comment by mizvekov** [comment]
AFAIK the bazel build scripts are externally automatically updated based on the cmake scripts, so I don't think we should be touching them.

**Review by rupprecht — COMMENTED** [review]
Bazel changes LGTM. Updating them is totally not necessary, but appreciated if you do. Thanks!

**Comment by rupprecht** [comment]
> AFAIK the bazel build scripts are externally automatically updated based on the cmake scripts, so I don't think we should be touching them.

Bazel files are not updated automatically. Updating them in the same commit is fine (but not required).

GN files are updated by the GN syncbot (e.g. a40b36f28e184adec975b682bc8d0fbeeb91113e), but needs manual intervention from time to time. I assume it's _probably_ the same as Bazel, i.e. fine to update them in the same commit. At any rate, GN and Bazel are both in the same peripheral tier -- if the change you've made to either GN or Bazel is incorrect, that's fine; someone who's invested in GN or Bazel will fix it later.

**Pull request merged**
