### PR TITLE
[flang][driver] Remove `flang -help` tests

### PR DESCRIPTION
**Pull request by banach-space**
These tests were introduced when the Flang driver was originally
incepted. Back then, `flang-new` only supported a handful of basic
options (e.g. `-v`, `-help`, `-E`) and those `-help` tests were used to
guard against Clang options "leaking" into `flang-new -help`.

With the introduction of the concept of "visibility" (see
https://reviews.llvm.org/D157837 and https://reviews.llvm.org/D157151),
these tests are effectively redundant. Also, with the number of flags
growing, these tests are getting rather brittle.

### CODE REVIEW

**Comment by tblah** [comment]
I'm not entirely against this, but I do currently find these tests useful when reviewing driver patches. They do make it easier to confirm my understanding of exactly what is being changed.

If others want to see this change then I won't oppose it

**Comment by banach-space** [comment]
Thanks for the feedback @tblah !

@Meinersbur and I discussed this one at EuroLLVM couple of weeks ago. I don't feel super strong about this one - I've actually sent it for review to see what the sentiments are :)

> They do make it easier to confirm my understanding of exactly what is being changed.

Well, I think that we should get into a habit of using "proper" tests for that :) In fact, I feel that folks assume that updating these files qualifies as "testing" (IMHO, it doesn't). That's one additional argument for removing them.

**Comment by tblah** [comment]
Yeah I agree that we need "proper" testing in addition to these. I am happy to merge if nobody else raises objections over the next few days.

**Comment by Meinersbur** [comment]
As @banach-space already brought up, I don't think these add much value. They are effectively just testing the print-loop over all options correctly considers the `FlangOption` flag. There's not much that can go wrong there, part of the documentation (should we also regression-test the Sphinx/DocBrief output?), but a chore to update.

**Comment by Leporacanthicus** [comment]
I'm OK with this going in, unless someone gives a good reason for keeping it.

Whilst not difficult to change the test, it adds little value to check that every option comes out in the correct order and has the right wording next to it. And if you so much as change the spelling on the help text, you need to go fix the test as well...

**Review by tblah — APPROVED** [review]

**Pull request merged**
