### PR TITLE
[clang][AST] fix dereference on class/struct layouts check.

### LINKED ISSUE #83671: [Clang] 19.0.0 SIGSEGV due to NULL Pointer dereference caused by receiving an NULL `BaseDecl` at `EmptySubobjectMap::ComputeEmptySubobjectSizes()`
Note: This is related to dump record layout feature with option `-Xclang -fdump-record-layouts-complete`.

When I want to use that option to dump `class` and `struct`'s layout, the clang crashes with SIGSEGV signal.

Crashsite Screenshot:
crashsite

Through my simple debugging, I found the problem might related to `EmptySubobjectMap::ComputeEmptySubobjectSizes()` in `clang/lib/AST/RecordLayoutBuilder.cpp`.

```cpp
void EmptySubobjectMap::ComputeEmptySubobjectSizes() {
  // Check the bases.
  for (const CXXBaseSpecifier &Base : Class->bases()) {
    const CXXRecordDecl *BaseDecl = Base.getType()->getAsCXXRecordDecl(); // [!]

    CharUnits EmptySize;
    const ASTRecordLayout &Layout = Context.getASTRecordLayout(BaseDecl); // [1]
    if (BaseDecl->isEmpty()) {
      // If the class decl is empty, get its size.
      EmptySize = Layout.getSize();
    } else {
      // Otherwise, we get the largest empty subobject for the decl.
      EmptySize = Layout.getSizeOfLargestEmptySubobject();
    }

    if (EmptySize > SizeOfLargestEmptySubobject)
      SizeOfLargestEmptySubobject = EmptySize;
  }

  // Check the fields.
  for (const FieldDecl *FD : Class->fields()) {
    const RecordType *RT =
        Context.getBaseElementType(FD->getType())->getAs<RecordType>();

    // We only care about record types.
    if (!RT)
      continue;

    CharUnits EmptySize;
    const CXXRecordDecl *MemberDecl = RT->getAsCXXRecordDecl();
    const ASTRecordLayout &Layout = Context.getASTRecordLayout(MemberDecl);
    if (MemberDecl->isEmpty()) {
      // If the class decl is empty, get its size.
      EmptySize = Layout.getSize();
    } else {
      // Otherwise, we get the largest empty subobject for the decl.
      EmptySize = Layout.getSizeOfLargestEmptySubobject();
    }

    if (EmptySize > SizeOfLargestEmptySubobject)
      SizeOfLargestEmptySubobject = EmptySize;
  }
}
```

At position `[!]`, `Base.getType()->getAsCXXRecordDecl()` will return a NULL pointer then causes crash in `Context.getASTRecordLayout(BaseDecl)` at position `[1]`.

Nullptr Introduce Site Screenshot:
nullptr-introduce

This is crash site, including the crash backtrace, preprocessed source, and associated run script.
[crashsite.zip](https://github.com/llvm/llvm-project/files/14469084/crashsite.zip)

Thanks!

### PR DESCRIPTION
**Pull request by devnexen**
close #83671.

### CODE REVIEW

**Review by shafik — CHANGES_REQUESTED** [review]
Thank you for the PR.

We need a minimal reproducer here. Looking at the bug report it is not clear to me if this is the correct fix or not. After we have a reproducer we would need a test added to the PR and a release note.

The summary also needs to have more details. This is what usually goes into the git log and it should at least 1) summarize the issue and cause 2) summarize the approach to the fix

**Comment by bjrjk** [comment]
Hello, this is a mininal reproducer execute with `clang++ -Xclang -fdump-record-layouts-complete test.cpp`:
```cpp
template <class _Tp, _Tp __v>
struct integral_constant {
  static constexpr const _Tp value = __v;
  typedef integral_constant type;
};

template <bool _Val>
using _BoolConstant = integral_constant<bool, _Val>;

template <class _Tp, class _Up>
struct is_same : _BoolConstant<__is_same(_Tp, _Up)> {};
```

**Comment by devnexen** [comment]
it seems [there is an ongoing fix](https://github.com/llvm/llvm-project/pull/83688), could you possibly try so we can just close this one.

**Comment by Endilll** [comment]
I posted a different, even shorter reduction in https://github.com/llvm/llvm-project/issues/83671.

**Comment by Sirraide** [comment]
> it seems [there is an ongoing fix](https://github.com/llvm/llvm-project/pull/83688), could you possibly try so we can just close this one.

Yeah, it seems that the pr I opened for #83684 also fixes both the reduced test cases for this issue (and it also doesn’t crash anymore if I try to compile the file that was linked in the issue), though it should be noted that that’s only after I noticed that there was another problem and fixed that too. 

I think we should be able to close this one, unless someone comes up with a test case that still crashes anyway.

**Pull request closed without merging**
