### PR TITLE
[MSan] Update 32-bit test checks

### PR DESCRIPTION
**Pull request by k-kashapov**
* As suggested in https://github.com/llvm/llvm-project/pull/111835#discussion_r1800179290, ran llvm/utils/update_test_checks.py on all the copied tests.
* Target triple is still unchanged

### CODE REVIEW

**Comment by k-kashapov** [comment]
@vitalybuka, please check

**Comment by k-kashapov** [comment]
@EugeneZelenko, please set tags "compiler-rt" or "compiler-rt:sanitizer".

**Comment by k-kashapov** [comment]
@vitalybuka, ping

**Review by vitalybuka — APPROVED** [review]
update_test_checks.py is not very nice with multiple check-prefixes

**Comment by k-kashapov** [comment]
Thanks!

**Review by vitalybuka — APPROVED** [review]
I'll merge after "presubmit" hooks.

Sorry for delay. You don't have permissions yet to request review, and I missed the PR in the flood of others.

Feel free to ping me on discort, if I didn't react in 1-2 days.

**Pull request merged**
