### PR TITLE
[ARM][AArch64] Reformat target parser. NFC

### PR DESCRIPTION
**Pull request by davemgreen**
This is something we generally tend to avoid due to confusing the git history, but with the new github formatting bots being more noisy we keep running into issues with the existing formatting when adding or adjusting CPUs. This patch formats the code to make sure we are in a good state going forward. I can tone this down if needed, reducing some of the changes that are outside of the main cpu tables (especially the .def). I just ran clang-format on the altered files.

### CODE REVIEW

**Review by DavidSpickett — COMMENTED** [review]
LGTM, I've thought about this before but not had the stomach for the merge conflict it'll create. A few places are less pretty but still readable, and some more readable, so I'm happy to go with clang-format's decisions here.

@jthackray should do the final approval just to confirm that landing this now isn't going to be bad timing for their team downstream.

**Comment by davemgreen** [comment]
Good point - I can try and help sorting out the merge conflict too.

**Comment by jthackray** [comment]
We've branched our latest release a couple of weeks ago, but are still doing occasional cherry-picks (and I've got pending upstream updates). Would prefer if we could leave until Monday; I'm still catching up as I've been away earlier this week due to half-term holidays.

But yes, it's a good idea to tidy this area of the code up :)

**Comment by davemgreen** [comment]
Yep - certainly happy to wait. I will give this a rebase this some time next week

**Review by jthackray — APPROVED** [review]
LGTM.

**Pull request merged**
