### PR TITLE
[libc++] Fix tests on musl.

### PR DESCRIPTION
**Pull request by al45tair**
One or two of the tests need slight tweaks to make them pass when building with musl.

rdar://118885724

### CODE REVIEW

**Review by ldionne — APPROVED** [review]
We don't really support Musl officially, however these changes are IMO not too strongly tied to Musl so it makes sense. In particular, the `put_long_double.pass.cpp` changes are simply making the test more generic so I think it's an overall win.

LGTM with green CI.

Edit: It looks like you need to apply the diff in https://github.com/llvm/llvm-project/pull/85085#issuecomment-1994540969 to pass the formatter test.

**Comment by mordante** [comment]
I just reverted this commit since it landed with a red CI
https://buildkite.com/llvm-project/libcxx-ci/builds/34153
feel free to recommit after fixing the CI.

**Comment by ldionne** [comment]
Sorry about that @mordante, I'll try this again.

**Comment by mordante** [comment]
> Sorry about that @mordante, I'll try this again.

No problem, I just wanted to unbreak the CI.

**Pull request merged**
