### PR TITLE
AMDGPU: Fix using wrong memory type for non-image resource intrinsics

### PR DESCRIPTION
**Pull request by arsenm**
An 8 x i16 raw load was incorrectly using a 64-bit memory type, which would assert in the MachineMemOperand constructor.

This is preparation for a cleanup which will make the buffer intrinsics work for all legal types.

### CODE REVIEW

**Comment by jayfoad** [comment]
> An 8 x i16 raw load

Is that a typo? The patch only touches 8 x **f16**.

**Comment by arsenm** [comment]
> > An 8 x i16 raw load
> 
> Is that a typo? The patch only touches 8 x **f16**.

The test is for f16, but it's any 16-bit element type. The test is mostly filler because I'm fixing a bunch of these in a later patch

**Comment by arsenm** [comment]
ping

**Review by piotrAMD — APPROVED** [review]
LGTM

**Pull request merged**
