### PR TITLE
fix(llvm/**.py): fix comparison to None

### PR DESCRIPTION
**Pull request by e-kwsm**
from PEP8 (https://peps.python.org/pep-0008/#programming-recommendations):

> Comparisons to singletons like None should always be done with is or is not, never the equality operators.

### CODE REVIEW

**Review by jroelofs — APPROVED** [review]

**Comment by e-kwsm** [comment]
> ⚠️ We detected that you are using a GitHub private e-mail address to contribute to the repo.
Please turn off [Keep my email addresses private](https://github.com/settings/emails) setting in your account.
See [LLVM Discourse](https://discourse.llvm.org/t/hidden-emails-on-github-should-we-do-something-about-it) for more information.

Done.

**Review by RoboTux — APPROVED** [review]
LGTM

**Comment by jroelofs** [comment]
@e-kwsm do you need us to press the "merge" button for you?

**Comment by e-kwsm** [comment]
> do you need us to press the "merge" button for you?

Yes.

**Pull request merged**
