### PR TITLE
[openmp][WebAssembly] Allow openmp to compile and run under emscripten toolchain 

### PR DESCRIPTION
**Pull request by arsnyder16**
* Separate wasi and emscripten as they have different constraints and abilities 
  * Emscripten mimics Linux/POSIX by statically linking the musl runtime. This allow nearly all KMP_OS_LINUX code paths to work correctly. There are only a few places that need to be adjusted related to dynamic linking  (dl_open) 
* Internally link openmp globals
   * With CommonLinkage it is needed to emit them in an assembly file, now they are defined and used within each compilation unit  
   * With ExternalLinkage they suffer from duplicate symbols during linking for unnamed globals like reduction/critical 
   * Interestingly this aligns with the TODO comment above this code

### CODE REVIEW

**Comment by abrown** [comment]
I haven't dug into this PR much yet review-wise but I think it is on the right track:
- I was shaky at best on the differences between `InternalLinkage` versus `ExternalLinkage` when I originally pieced #71297 together so this seems to make sense
- it is true that Emscripten and WASI have quite different paradigms so it is plausible that we need to handle the Emscripten bits differently

I tested this PR out in a [simplistic WASI example](https://github.com/abrown/wasm-openmp-examples) and everything seemed to work as before on the WASI side. This "OpenMP + WebAssembly" support is still very experimental so I think that is probably the best we can do for now. Of course, it would be useful to have an Emscripten version of that around &mdash; @arsnyder16, do you have something like that?

**Comment by arsnyder16** [comment]
> I haven't dug into this PR much yet review-wise but I think it is on the right track:
> 
> - I was shaky at best on the differences between `InternalLinkage` versus `ExternalLinkage` when I originally pieced #71297 together so this seems to make sense
> 
> - it is true that Emscripten and WASI have quite different paradigms so it is plausible that we need to handle the Emscripten bits differently
> 
> 
> 
> I tested this PR out in a [simplistic WASI example](https://github.com/abrown/wasm-openmp-examples) and everything seemed to work as before on the WASI side. This "OpenMP + WebAssembly" support is still very experimental so I think that is probably the best we can do for now. Of course, it would be useful to have an Emscripten version of that around &mdash; @arsnyder16, do you have something like that?

Yea I can supply an emscripten variant, I'll fork your branch, I'll add a few more openmp scenarios as well to it to mimic the various link scenarios I encountered as well

**Comment by arsnyder16** [comment]
> > I haven't dug into this PR much yet review-wise but I think it is on the right track:
> > 
> > * I was shaky at best on the differences between `InternalLinkage` versus `ExternalLinkage` when I originally pieced [[openmp][wasm] Allow compiling OpenMP to WebAssembly  #71297](https://github.com/llvm/llvm-project/pull/71297) together so this seems to make sense
> > * it is true that Emscripten and WASI have quite different paradigms so it is plausible that we need to handle the Emscripten bits differently
> > 
> > I tested this PR out in a [simplistic WASI example](https://github.com/abrown/wasm-openmp-examples) and everything seemed to work as before on the WASI side. This "OpenMP + WebAssembly" support is still very experimental so I think that is probably the best we can do for now. Of course, it would be useful to have an Emscripten version of that around — @arsnyder16, do you have something like that?
> 

https://github.com/abrown/wasm-openmp-examples/pull/2

You can see a few of the issues here depending on the variants of clang and openmp, wasi vs emscripten as well.

For reference on the linkage, both wasi and emscripten suffer the same issues 

### ExternalLinkage
```
/root/wasm-openmp-examples/wasi-sdk-22.0/bin/clang -fopenmp=libomp -g --sysroot=/root/wasm-openmp-examples/wasi-sdk-22.0/share/wasi-sysroot --target=wasm32-wasi-threads \
  -I/root/wasm-openmp-examples/build/runtime/src -I/root/wasm-openmp-examples/wasi-sdk-22.0/share/wasi-sysroot/include -pthread \
  -Wl,--import-memory,--export-memory,--max-memory=67108864 example.c other.c \
  -L/root/wasm-openmp-examples/build/runtime/src -lomp \
  -lwasi-emulated-getpid \
  -o example.wasm
wasm-ld: error: duplicate symbol: .gomp_critical_user_.var
>>> defined in /tmp/example-5ca29e.o
>>> defined in /tmp/other-19151f.o

wasm-ld: error: duplicate symbol: .gomp_critical_user_NAME.var
>>> defined in /tmp/example-5ca29e.o
>>> defined in /tmp/other-19151f.o

wasm-ld: error: duplicate symbol: .gomp_critical_user_.reduction.var
>>> defined in /tmp/example-5ca29e.o
>>> defined in /tmp/other-19151f.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make: *** [Makefile:31: example.wasm] Error 1
```
### CommonLinkage
```
/root/wasm-openmp-examples/wasi-sdk-22.0/bin/clang -fopenmp=libomp -g --sysroot=/root/wasm-openmp-examples/wasi-sdk-22.0/share/wasi-sysroot --target=wasm32-wasi-threads \
  -I/root/wasm-openmp-examples/build/runtime/src -I/root/wasm-openmp-examples/wasi-sdk-22.0/share/wasi-sysroot/include -pthread \
  -Wl,--import-memory,--export-memory,--max-memory=67108864 example.c other.c \
  -L/root/wasm-openmp-examples/build/runtime/src -lomp \
  -lwasi-emulated-getpid \
  -o example.wasm
wasm-ld: error: /tmp/example-1bd196.o: undefined symbol: .gomp_critical_user_.var
wasm-ld: error: /tmp/example-1bd196.o: undefined symbol: .gomp_critical_user_NAME.var
wasm-ld: error: /tmp/example-1bd196.o: undefined symbol: .gomp_critical_user_.reduction.var
wasm-ld: error: /tmp/example-1bd196.o: undefined symbol: .gomp_critical_user_.reduction.var
wasm-ld: error: /tmp/example-1bd196.o: undefined symbol: .gomp_critical_user_.var
wasm-ld: error: /tmp/example-1bd196.o: undefined symbol: .gomp_critical_user_NAME.var
wasm-ld: error: /tmp/example-1bd196.o: undefined symbol: .gomp_critical_user_.reduction.var
wasm-ld: error: /tmp/example-1bd196.o: undefined symbol: .gomp_critical_user_.reduction.var
```

### InternalLinkage
```
/root/wasm-openmp-examples/wasi-sdk-22.0/bin/clang -fopenmp=libomp -g --sysroot=/root/wasm-openmp-examples/wasi-sdk-22.0/share/wasi-sysroot --target=wasm32-wasi-threads \
  -I/root/wasm-openmp-examples/build/runtime/src -I/root/wasm-openmp-examples/wasi-sdk-22.0/share/wasi-sysroot/include -pthread \
  -Wl,--import-memory,--export-memory,--max-memory=67108864 example.c other.c \
  -L/root/wasm-openmp-examples/build/runtime/src -lomp \
  -lwasi-emulated-getpid \
  -o example.wasm
/root/.wasmtime/bin/wasmtime -W threads -S threads example.wasm
Hello World... from thread = 0
Hello World... from thread = 3
Hello World... from thread = 2
Hello World... from thread = 1
Hello World... from thread = 4
Hello World... from thread = 6
Hello World... from thread = 5
Hello World... from thread = 7
example.c critical_unamed: 8
example.c critical_named: 8
example.c reduction: 8
other.c critical_unamed: 8
other.c critical_named: 8
other.c reduction: 8
```

The open question i have is why is wasm target different here? Native platforms seem to work fine with `CommonLinkage` so i am curious if there is a related issue elsewhere in clang that is not emitting the proper definitions for these variables to support CommonLinkage when compiling for wasm

**Comment by abrown** [comment]
cc: @jpeyton52, can you take a look at this?

**Comment by arsnyder16** [comment]
@abrown @jpeyton52 Any updates here?

**Review by jpeyton52 — APPROVED** [review]
The changes look fine to me.

**Comment by arsnyder16** [comment]
> The changes look fine to me.

Thanks, good to merge?

**Comment by arsnyder16** [comment]
@jpeyton52 Can we get this merged?

**Comment by jpeyton52** [comment]
Sorry about that! It has been merged.

**Comment by arsnyder16** [comment]
@sbc100 @kripken What is the process required for this change(clang update) to land in the next emsdk version?

**Comment by kripken** [comment]
@arsnyder16 Once something lands in LLVM, it is automatically picked up by Emscripten's tip of tree builds (which you can install with `emsdk install tot`, though it can take a few hours for tests and builds to complete). It will also be included automatically in the next official emsdk release.

**Comment by JAicewizard** [comment]
Yes `KMP_ARCH_WASM` is indeed defined (to 1). However the resulting archive does not contain the symbol. Does something else need to be linked?

This is how I compile:
```
emcmake cmake .-G Ninja -DOPENMP_STANDALONE_BUILD=ON \
-DOPENMP_ENABLE_LIBOMPTARGET=OFF -DLIBOMP_HAVE_OMPT_SUPPORT=OFF \
-DLIBOMP_OMPT_SUPPORT=OFF -DLIBOMP_OMPD_SUPPORT=OFF \
-DLIBOMP_USE_DEBUGGER=OFF -DLIBOMP_FORTRAN_MODULES=OFF \
-DLIBOMP_ENABLE_SHARED=OFF -DLIBOMP_ARCH=wasm32 \
-DOPENMP_ENABLE_LIBOMPTARGET_PROFILING=OFF -DCMAKE_INSTALL_PREFIX=/
```

And the symbol is missing:
```
$ /usr/bin/llvm-nm runtime/src/libomp.a | grep __kmp_unnamed_critical_addr
runtime/src/libomp.a:kmp_itt.cpp.o: no symbols
         U __kmp_unnamed_critical_addr
runtime/src/libomp.a:z_Linux_asm.S.o: no symbols
```

Is something missing in the compilation step? Or is this symbol unneeded? If the latter is the case I will find out how to ignore this error.

**Pull request merged**
