### PR TITLE
[clang][llvm] Remove "implicit-section-name" attribute

### PR DESCRIPTION
**Pull request by aeubanks**
D33412/D33413 introduced this to support a clang pragma to set section names for a symbol depending on if it would be placed in bss/data/rodata/text, which may not be known until the backend. However, for text we know that only functions will go there, so just directly set the section in clang instead of going through a completely separate attribute.

Autoupgrade the "implicit-section-name" attribute to directly setting the section on a Fuction.

### CODE REVIEW

**Comment by aeubanks** [comment]
this probably needs bitcode upgrade?

**Comment by efriedma-quic** [comment]
I'd suggest adding bitcode upgrade if it isn't too hard (I don't think it should be?)

Otherwise looks fine.

**Comment by aeubanks** [comment]
> I'd suggest adding bitcode upgrade if it isn't too hard (I don't think it should be?)

done

**Review by efriedma-quic — APPROVED** [review]
LGTM

**Pull request merged**
