### PR TITLE
[SimplifyCFG][Migrated] Transform for redirecting phis between unmergeable BB and SuccBB

### PR DESCRIPTION
**Pull request by XChy**
This patch extends function TryToSimplifyUncondBranchFromEmptyBlock to handle the similar cases below.

```llvm
define i8 @src(i8 noundef %arg) {
start:
  switch i8 %arg, label %unreachable [
    i8 0, label %case012
    i8 1, label %case1
    i8 2, label %case2
    i8 3, label %end
  ]

unreachable:
  unreachable

case1:
  br label %case012

case2:
  br label %case012

case012:
  %phi1 = phi i8 [ 3, %case2 ], [ 2, %case1 ], [ 1, %start ]
  br label %end

end:
  %phi2 = phi i8 [ %phi1, %case012 ], [ 4, %start ]
  ret i8 %phi2
}
```
The phis here should be merged into one phi, so that we can better optimize it:

```llvm
define i8 @tgt(i8 noundef %arg) {
start:
  switch i8 %arg, label %unreachable [
    i8 0, label %end
    i8 1, label %case1
    i8 2, label %case2
    i8 3, label %case3
  ]

unreachable:
  unreachable

case1:
  br label %end

case2:
  br label %end

case3:
  br label %end

end:
  %phi = phi i8 [ 4, %case3 ], [ 3, %case2 ], [ 2, %case1 ], [ 1, %start ]
  ret i8 %phi
}
```
Proof:
[normal](https://alive2.llvm.org/ce/z/vAWi88)
[multiple stages](https://alive2.llvm.org/ce/z/DDBQqp)
[multiple stages 2](https://alive2.llvm.org/ce/z/nGkeqN)
[multiple phi combinations](https://alive2.llvm.org/ce/z/VQeEdp)

And lookup table optimization should convert it into add %arg 1.
This patch just match similar CFG structure and merge the phis in different cases.

Maybe such transform can be applied to other situations besides switch,
but I'm not sure whether it's better than not merging. Therefore, I only try it in switch,

Related issue:
#63876

[Migrated](https://reviews.llvm.org/D155940)

### CODE REVIEW

**Comment by omjavaid** [comment]
This change breaks LLVM buildbot clang-aarch64-sve-vls-2stage https://lab.llvm.org/buildbot/#/builders/176/builds/5474
I have reverted this patch as the bot has been failing for more than a day without a fix.

**Comment by XChy** [comment]
Sure, feel free to revert it. But the buildbot's log confuse me with something related to flang and SLPVectorizer. Could someone help me understand that?

**Comment by omjavaid** [comment]
I am not 100% sure how it seems to crash clang during compilation of llvm/flang/lib/Evaluate/intrinsics-library.cpp . Could you please post the issue https://github.com/llvm/llvm-project/blob/main/flang/docs/GettingInvolved.md#chat

The following error messages could be a starting point.

Not a vector MVT!
UNREACHABLE executed at ../llvm/llvm/include/llvm/CodeGen/MachineValueType.h:276!

The error  suggests that somewhere code that’s being compiled, an operation is expecting a vector Machine Value Type but is receiving a non-vector type instead. Bit I am not an expert in this area to explain further.

**Comment by DianQK** [comment]
> Sure, feel free to revert it. But the buildbot's log confuse me with something related to flang and SLPVectorizer. Could someone help me understand that?

If I understand correctly, this is an error that occurred in stage 2. First building clang (stage1) with an older version of clang and then building stage2 with this stage1 failed. The stage1 contains your optimization.
Trouble is, that these kinds of problems are hard to solve. If your optimization is safe, it may be exposing some other mis-compilation.

**Comment by XChy** [comment]
Thanks for your help! I have posted an issue in flang channel.

> Trouble is, that these kinds of problems are hard to solve. If your optimization is safe, it may be exposing some other mis-compilation.

Your explanation makes sense to me. That'll take some time to pinpoint where the problems are.

**Comment by XChy** [comment]
It's hard to reproduce the error on my machine (No AArch64 architecture to compile and run it) ,and hard to get the IR before SLPVectorizer when bootstrapping and building with CMake configuration system. If it's a single file, I can use command line directly. But now I can't and have no idea how to debug it. Even with `llvm-stress`, I didn't reproduce on my machine. I'll highly appreciate it if anyone could give me guidance or share similar experience.

**Pull request merged**
