### PR TITLE
[RISCV] Add SMLoc to expanded vector pseudoinstructions in AsmParser.

### LINKED ISSUE #84799: [RISCV][MCA] Failure to use SEW from instrument on vmslt.vi
In the test case below, we appear to be failing to apply the SEW from the vsetvli to the vmslt.vi.  Note that we do apply it to the vmslt.vx.  

I haven't fully tracked this down, but I suspect the fact that vmslt.vi is a assembler pseudo instruction and is actually encoded as a vmsle.vi is a relevant factor.  In particular, if I use vmsle.vi directly in the assembly, the problem goes away.

```
# NOTE: Assertions have been autogenerated by utils/update_mca_test_checks.py
# RUN: llvm-mca -mtriple=riscv64 -mcpu=sifive-x280 -iterations=1 < %s | FileCheck %s

vsetvli zero, zero, e16, mf4, tu, mu
vmslt.vx v4, v8, x10
vmslt.vi v4, v8, 10
vsetvli zero, zero, e16, mf2, tu, mu
vmslt.vx v4, v8, x10
vmslt.vi v4, v8, 2
vsetvli zero, zero, e16, m1, tu, mu
vmslt.vx v4, v8, x10
vmslt.vi v4, v8, 12

# CHECK:      Iterations:        1
# CHECK-NEXT: Instructions:      9
# CHECK-NEXT: Total Cycles:      68
# CHECK-NEXT: Total uOps:        9

# CHECK:      Dispatch Width:    2
# CHECK-NEXT: uOps Per Cycle:    0.13
# CHECK-NEXT: IPC:               0.13
# CHECK-NEXT: Block RThroughput: 58.0

# CHECK:      Instruction Info:
# CHECK-NEXT: [1]: #uOps
# CHECK-NEXT: [2]: Latency
# CHECK-NEXT: [3]: RThroughput
# CHECK-NEXT: [4]: MayLoad
# CHECK-NEXT: [5]: MayStore
# CHECK-NEXT: [6]: HasSideEffects (U)

# CHECK:      [1]    [2]    [3]    [4]    [5]    [6]    Instructions:
# CHECK-NEXT:  1      3     1.00                  U     vsetvli	zero, zero, e16, mf4, tu, mu
# CHECK-NEXT:  1      4     2.00                        vmslt.vx	v4, v8, a0
# CHECK-NEXT:  1      19    17.00                       vmsle.vi	v4, v8, 9
# CHECK-NEXT:  1      3     1.00                  U     vsetvli	zero, zero, e16, mf2, tu, mu
# CHECK-NEXT:  1      4     2.00                        vmslt.vx	v4, v8, a0
# CHECK-NEXT:  1      19    17.00                       vmsle.vi	v4, v8, 1
# CHECK-NEXT:  1      3     1.00                  U     vsetvli	zero, zero, e16, m1, tu, mu
# CHECK-NEXT:  1      5     3.00                        vmslt.vx	v4, v8, a0
# CHECK-NEXT:  1      19    17.00                       vmsle.vi	v4, v8, 11

# CHECK:      Resources:
# CHECK-NEXT: [0]   - SiFive7FDiv
# CHECK-NEXT: [1]   - SiFive7IDiv
# CHECK-NEXT: [2]   - SiFive7PipeA
# CHECK-NEXT: [3]   - SiFive7PipeB
# CHECK-NEXT: [4]   - SiFive7VA
# CHECK-NEXT: [5]   - SiFive7VCQ
# CHECK-NEXT: [6]   - SiFive7VL
# CHECK-NEXT: [7]   - SiFive7VS

# CHECK:      Resource pressure per iteration:
# CHECK-NEXT: [0]    [1]    [2]    [3]    [4]    [5]    [6]    [7]
# CHECK-NEXT:  -      -     3.00    -     58.00  6.00    -      -

# CHECK:      Resource pressure by instruction:
# CHECK-NEXT: [0]    [1]    [2]    [3]    [4]    [5]    [6]    [7]    Instructions:
# CHECK-NEXT:  -      -     1.00    -      -      -      -      -     vsetvli	zero, zero, e16, mf4, tu, mu
# CHECK-NEXT:  -      -      -      -     2.00   1.00    -      -     vmslt.vx	v4, v8, a0
# CHECK-NEXT:  -      -      -      -     17.00  1.00    -      -     vmsle.vi	v4, v8, 9
# CHECK-NEXT:  -      -     1.00    -      -      -      -      -     vsetvli	zero, zero, e16, mf2, tu, mu
# CHECK-NEXT:  -      -      -      -     2.00   1.00    -      -     vmslt.vx	v4, v8, a0
# CHECK-NEXT:  -      -      -      -     17.00  1.00    -      -     vmsle.vi	v4, v8, 1
# CHECK-NEXT:  -      -     1.00    -      -      -      -      -     vsetvli	zero, zero, e16, m1, tu, mu
# CHECK-NEXT:  -      -      -      -     3.00   1.00    -      -     vmslt.vx	v4, v8, a0
# CHECK-NEXT:  -      -      -      -     17.00  1.00    -      -     vmsle.vi	v4, v8, 11

```

### PR DESCRIPTION
**Pull request by topperc**
This is needed for llvm-mca to correctly apply vsetvli instruments to these instructions.

Fixes #84799.

### CODE REVIEW

**Comment by preames** [comment]
I suspect we have the same problem with any other pseudo which can occur in assembly (as opposed to being compiler generated).  One example would be LI.  This would be a followup though, not a change to this patch.

**Review by preames — APPROVED** [review]
LGTM

Edit - Sorry, forgot to note.  You should add an MCA test case showing the change in behavior here.

**Comment by topperc** [comment]
> I suspect we have the same problem with any other pseudo which can occur in assembly (as opposed to being compiler generated).  One example would be LI.  This would be a followup though, not a change to this patch.

Possibly. I wasn't sure if it mattered for scalar. Do we have something like the SEW LMUL instrument for scalar

**Comment by preames** [comment]
> > I suspect we have the same problem with any other pseudo which can occur in assembly (as opposed to being compiler generated).  One example would be LI.  This would be a followup though, not a change to this patch.
> 
> Possibly. I wasn't sure if it mattered for scalar. Do we have something like the SEW LMUL instrument for scalar

I don't believe so, but if this also caused the BEGIN/END marker behavior, then the scalar case is still relevant.

**Pull request merged**
