### PR TITLE
[SimplifyCFG] Prevent merging cbranch to cbranch if the branch probability from the first to second is too low.

### PR DESCRIPTION
**Pull request by vpykhtin**
AMDGPU target has faced the situation which can be illustrated with the following testcase:
```
define void @dont_merge_cbranches(i32 %V) {
  %divergent_cond = icmp ne i32 %V, 0
  %uniform_cond = call i1 @uniform_result(i1 %divergent_cond)
  br i1 %uniform_cond, label %bb2, label %exit, !prof !0
bb2:
  br i1 %divergent_cond, label %bb3, label %exit
bb3:
  call void @bar( )
  br label %exit
exit:
  ret void
}
!0 = !{!"branch_weights", i32 1, i32 100000}
```
SimplifyCFG merges branches on %uniform_cond and %divergent_cond which is undesirable because the first branch to _bb2_ is taken extremely rare and the second branch is expensive (as names state the first branch is uniform and the second is divergent and requires EXEC mask handling). The merged branch becomes as expensive as the second.

@nhaehnle suggested to stop merging such branches on the basis of branch probability information.

Threshold value is somewhat voluntaristic at the moment and probably should be selected as the lowest from the known used branch probability values in the LLVM code to preserve current behaviour. It may also happen that we end up using target dependent threshold.

### CODE REVIEW

**Review by nhaehnle — APPROVED** [review]
Thanks! I don't have better guidance on the threshold value either. The default choice seems pretty conservative which is probably a good thing. Perhaps somebody else wants to chime in, but this LGTM.

**Comment by nikic** [comment]
Any particular reason this should not use `TTI->getPredictableBranchThreshold()`?

**Comment by vpykhtin** [comment]
> Any particular reason this should not use `TTI->getPredictableBranchThreshold()`?

Thank you, that is what I have been looking for, updated.

**Comment by vpykhtin** [comment]
It looks like I should check MD_unpredictable as well

**Comment by vpykhtin** [comment]
@nikic or other reviewers, do you have objections to submit this patch?

**Comment by nhaehnle** [comment]
I've been puzzling over the rationale for looking at `MD_unpredictable`. How can a branch that is heavily biased to one side be unpredictable?

**Comment by vpykhtin** [comment]
> I've been puzzling over the rationale for looking at `MD_unpredictable`. How can a branch that is heavily biased to one side be unpredictable?

I'm curious either, I just decided to follow a 'standard' pattern in this source.

**Comment by vpykhtin** [comment]
Guys, I really need this change submitted, I'm going to submit it on monday if there're no objections.

**Comment by DaniilSuchkov** [comment]
Hi @vpykhtin! It looks like this change has caused a functional regression https://github.com/llvm/llvm-project/issues/72323

**Pull request merged**
