### PR TITLE
[NFC] Delete unused clang-formatted-file.txt/ClangFormattedStatus.rst files

### PR DESCRIPTION
**Pull request by jurahul**
Looks like these files are generated by the `generate_formatted_state.py` script as a "status report" of state of clang-format compliance of files in the LLVM git repo. As such, they do not belong to the repo itself, so deleting them.

Please see: https://discourse.llvm.org/t/clang-docs-tools-clang-formatted-files-txt/82803

### CODE REVIEW

**Comment by AaronBallman** [comment]
I don't think this file is actually unused; it was committed with the original PR adding the script: 5aca8bb963a43b62f37305f7eb07476631ea9f2a (https://reviews.llvm.org/D111000 was the review)

I've added @mydeveloperday as a reviewer for confirmation though

**Comment by jurahul** [comment]
May be. Even in that PR, the only reference to this file is:

```
CLEAN_FILE = os.path.join(CLANG_DIR, 'docs/tools/clang-formatted-files.txt')
cleanfiles = open(CLEAN_FILE, "wb")
```
So its overwritten. But yeah, let @mydeveloperday confirm.

**Comment by jurahul** [comment]
@AaronBallman WDTY? The motivation of the change is that I see most of the changes in this file are a result of folks adding or deleting files, so its one less thing to take care of when doing so. Also the current list of files in this file is incomplete, further proving that this file is not used in any meaningful way. For example, "llvm/utils/TableGen/Basic/*" and "llvm/utils/TableGen/Common/*" are missing. I suspect there may be others as well.

**Comment by jurahul** [comment]
@AaronBallman ping to comment on this again. Not only does this have files missing, it also includes file names that do not exist anymore in the repo:

```
clang/docs/tools/clang-formatted-files.txt:llvm/include/llvm/DWP/DWPStringPool.h
clang/docs/tools/clang-formatted-files.txt:llvm/lib/CodeGen/AsmPrinter/DwarfStringPool.h
clang/docs/tools/clang-formatted-files.txt:llvm/lib/Target/NVPTX/ManagedStringPool.h
```

So, I think it's best to cleanup and delete the file.

**Comment by jurahul** [comment]
@AaronBallman can you PTAL?

**Comment by AaronBallman** [comment]
> @AaronBallman can you PTAL?

The changes themselves are fine, but I'd like to hear from @mydeveloperday or @owenca just to be sure we're not stepping on any clang-format folks' toes.

**Comment by jurahul** [comment]
Thanks. I haven't seen any responses from @mydeveloperday earlier, hopefully @owenca can chime in.

**Review by owenca — APPROVED** [review]

**Comment by jurahul** [comment]
@AaronBallman go ahead with the merge since @owenca has approved?

**Review by AaronBallman — APPROVED** [review]
LGTM, thank you for the cleanup!

**Comment by cjappl** [comment]
FYI @jurahul  - having a build failure when I try to build docs after this change. I think a few little bits were missed.
```
Warning, treated as error:
./llvm-project/build/tools/clang/docs/ClangFormattedStatus.rst:document isn't included in any toctree
```

https://github.com/llvm/llvm-project/blob/847f4ef21b4a953bb6dd6477791e8d95b6db2509/clang/docs/ClangFormat.rst?plain=1#L370

https://github.com/llvm/llvm-project/blob/847f4ef21b4a953bb6dd6477791e8d95b6db2509/clang/docs/tools/generate_formatted_state.py#L32

https://github.com/llvm/llvm-project/blob/847f4ef21b4a953bb6dd6477791e8d95b6db2509/clang/docs/tools/generate_formatted_state.py#L59

Would you mind reverting (or just deleting these, if that is more appropriate)?

**Comment by jurahul** [comment]
Let me delete those references. The ones in generated_formatted_state.py are fine

**Comment by jurahul** [comment]
Started https://github.com/llvm/llvm-project/pull/114331

**Comment by AaronBallman** [comment]
Oops, I thought I had gotten all of those yesterday but it seems I didn't. Thanks for the cleanup @jurahul!

**Pull request merged**
