### PR TITLE
[llvm-objdump] Print ... even if a data mapping symbol is active

### PR DESCRIPTION
**Pull request by MaskRay**
Swap `!DisassembleZeroes` and `if (DumpARMELFData)` conditions so that
in the false DisassembleZeroes case (default), `...` will be printed for
long consecutive zeroes, even when a data mapping symbol is active.

This is especially useful for certain lld tests that insert a huge
padding within a code section. Without `...` the output will be huge.

### CODE REVIEW

**Review by smithp35 — APPROVED** [review]
LGTM for the change. From the build kite result looks like MC/ARM/ltorg-range.s will need to add `-z`.

arm-none-eabi-objdump and aarch64-none-elf-objdump use ellipsis for more than 4-bytes of zeroes.

I tend to use GNU objdump whenever I have a file with a non-trivial amount of zeroes so for me this is a big useability improvement.

May want to give jh7370 some time to review too.

**Comment by MaskRay** [comment]
> LGTM for the change. From the build kite result looks like MC/ARM/ltorg-range.s will need to add `-z`.
> 
> arm-none-eabi-objdump and aarch64-none-elf-objdump use ellipsis for more than 4-bytes of zeroes.
> 
> I tend to use GNU objdump whenever I have a file with a non-trivial amount of zeroes so for me this is a big useability improvement.
> 
> May want to give jh7370 some time to review too.

Thanks for the review. I hope this is useful to your lld patch for testing. 

I recall that jh7370 mentioned vacation plan recently. Anyhow I'll hold off merging this for two days.

**Comment by tex3d** [comment]
@MaskRay 
It looks like this change broke two BOLT tests:
```
BOLT :: AArch64/constant_island_pie_update.s
BOLT :: AArch64/update-weak-reference-symbol.s
```
These are broken in this PR's checks, and subsequent builds from main since merging.

**Comment by MaskRay** [comment]
> @MaskRay It looks like this change broke two BOLT tests:
> 
> ```
> BOLT :: AArch64/constant_island_pie_update.s
> BOLT :: AArch64/update-weak-reference-symbol.s
> ```
> 
> These are broken in this PR's checks, and subsequent builds from main since merging.

Sorry but I'm not at a computer. You could fix the tests by adding -z to the llvm-objdump line

**Comment by tex3d** [comment]
@MaskRay 
I created a PR, since I don't have write access.  Someone who does can merge my PR.
I tested the fixes locally, and was able to repro those test failures, so I'm pretty sure the fix is good.

**Review by jh7370 — COMMENTED** [review]
I'm back - looks fine to me!

**Pull request merged**
