### PR TITLE
[RISCV] Teach RISCVInsertVSETVLI to work without LiveIntervals

### LINKED ISSUE #93587: [RISC-V] Use of %0 does not have a corresponding definition on every path with `-O0`
Reduced LLVM IR:
```
define i16 @f() {
BB:
  br label %BB1

BB1:                                              ; preds = %BB1, %BB
  %A = or i16 0, 0
  %B = fcmp true float 0.000000e+00, 0.000000e+00
  %C = or i1 %B, false
  br i1 %C, label %BB1, label %BB2

BB2:                                              ; preds = %BB1
  ret i16 %A
}
```
Godbolt: https://godbolt.org/z/7GGzqs5c6

BB state before the LiveIntervalAnalysis pass from debug log:
```
BB.0    BB.3 (unreachable)
 |     /    \
BB.1(loops)  BB.2 -> ret
```

Since BB.1 defines %0 and BB.2 reads it, LiveIntervalAnalysis complains about
the undefined value in the unreachable codepath.

First visibly bad commit:
af82d01fbbce7808605f3a8b22dd1ca7fdec7886 [RISCV] Separate doLocalPostpass into new pass...

I think this is just because LiveIntervalAnalysis isn't run before this commit.

One step further back is the commit that causes bb to be split into bb.3.
2c185709bca195f3d5e062819bba5dd828330548 [RISCV] Remove setJumpIsExpensive()

Can be mitigated by `-mllvm -jump-is-expensive=true`

### PR DESCRIPTION
**Pull request by lukel97**
At O0 LiveIntervals isn't usually computed, but after moving RISCVInsertVSETVLI to after phi elimination we've added it as a dependency.

This removes the dependency on LiveIntervals so O0 builds can stay fast, and also avoids a crash caused by LiveIntervals being run at O0 when I'm not sure if ti was designed to be.

The only necessary parts of RISCVInsertVSETVLI that actually use the LiveIntervals analysis are computeInfoForInstr and getInfoForVSETVLI, which lookup val nos for each register AVL use.

At O0 we can emulate this by conservatively returning fake but unique val nos, which will give us suboptimal but otherwise correct codegen.

We need to make sure that we return the same val no given the same MachineInstr, otherwise computeInfoForInstr/getInforForVSETVLI won't be stable across MachineInstrs and the dataflow analysis will fail to converge.

Fixes #93587

### CODE REVIEW

**Comment by lukel97** [comment]
Mentioning this as an alternative fix for the crash in #93587, we could also try running the remove unreachable machine block pass at O0 to keep LiveIntervalsAnalysis happy.

**Comment by preames** [comment]
I have an alternate suggestion here.  I'm going to describe this with the representation before 4b4d36654d8056546b177b3d04c352ba0b16d7ea as I think that makes things harder to understand.

My alternative basically comes down to "let ValNo be nullptr", and update uses of this value, not the definitions with some synthetic value (this patch).

getAVLDefMI is easy at is already allowed to return nullptr.  We'd need to update the doc comment, but that's about it.

getAVLVNInfo requires a bit of care.  Here's a list per callsite:
* setAVL just propagates the nullptr
* hasSameAVL can simply return false when ValNo is nullptr on either side.
* needVSETVLIPHI can simply bail out if ValNo is nullptr.
* doPRE can bailout

Each of the above is a lost *optimization* at O0, but shouldn't influence correctness.  Out of the above, the hasSameAVL is probably the biggest lost optimization, but I don't see an easy way to avoid that.  

You'd also need to reverse the order of checks involving getVNInfoFromReg, but the assert in the else shows that possible without issue.

**Comment by lukel97** [comment]
> hasSameAVL can simply return false when ValNo is nullptr on either side.

Setting ValNo to nullptr is what I had tried initially, but the snag that I ran into was that VSETVLIInfo::== was no longer reflexive and I ran into some infinite cycles, presumably because computeIncomingVLVTYPE kept on adding successors to the worklist since it the terminating condition `if (BBInfo.Exit == TmpStatus)` never held. The assertion at the end of RISCVInsertVSETVLI::emitVSETVLIs` also failed.

But I do agree that it would be nicer to avoid the dummy values, I'll give this another try. Maybe we could redefine == to not use hasSameAVL. I think we may be conflating it a bit with the notion of "being compatible" which is what VSETVLIInfo::isCompatible is for.

**Comment by lukel97** [comment]
Superseded by #94686

**Pull request closed without merging**
