### PR TITLE
[MLIR][EmitC] Emit private functions as static

### PR DESCRIPTION
**Pull request by AlexDenisov**

### CODE REVIEW

**Comment by marbre** [comment]
Thanks for the pull-request @AlexDenisov. I am not sure if the concept of an `private` symbol in MLIR or rather a `func.func private` directly matches with the C/C++ `static` keyword. However, I fully agree and see the need to emit static functions. I already have a `emitc.func` somewhere on my stack which should allow attributes like `static` and `inline` and could prioritize this if there is a need. This could also allow to implement a conversion pass that converts a `func.func` and `emitc.func` with `private` mapped to `static`. WDYT?

**Comment by AlexDenisov** [comment]
I agree that it doesn't map directly, OTOH I'm seeing CPP target as an approximation.
Re: different implementation: that approach sounds good to me and totally makes sense.
I don't need this functionality urgently (I can work with a local patch in the meantime), but it would be nice to get static functions in eventually.

Would it also make sense to get this functionality in and then migrate to `emitc.func`? Just trying to avoid this slipping through the cracks 😅

**Comment by joker-eph** [comment]
Why isn't private mapping to static for functions?

**Comment by AlexDenisov** [comment]
> Why isn't private mapping to static for functions?

I guess the mapping is not one-to-one: `static` from C doesn't necessarily map directly to `private`, although I think `private` maps to `static` perfectly fine in this case.

**Comment by marbre** [comment]
> > Why isn't private mapping to static for functions?
> 
> I guess the mapping is not one-to-one: `static` from C doesn't necessarily map directly to `private`, although I think `private` maps to `static` perfectly fine in this case.

Yeah, that is what I had in mind. I think adding an `emitc.call` op makes sense anyway as it would allow to emit further keywords such as `inline`, the combination `static inline` as well as further keywords like `__device__`, `__host__` and `__global__` with view to emit CUDA code.

> I agree that it doesn't map directly, OTOH I'm seeing CPP target as an approximation. Re: different implementation: that approach sounds good to me and totally makes sense. I don't need this functionality urgently (I can work with a local patch in the meantime), but it would be nice to get static functions in eventually.

I already restarted my work on an `emitc.func` but this also requires me to implement an `emitc.return` (`func.return` is restricted to have `func.func` as parent) and also a **new** `emitc.call` op (the `emitc.call` op we previously had was renamed to `emitc.call_opaque` back in November with c4fd1fd). 

> Would it also make sense to get this functionality in and then migrate to `emitc.func`? Just trying to avoid this slipping through the cracks 😅

After several discussions there seemed to be kind of conses that one should rather extend the dialect and do what is necessary within conversions instead of extending support in the emitter for non-EmitC functions. Extending `func.func` support isn't a big thing and the patch is quite tiny, but I still would prefer to keep the way we go for other options as well. For example `scf.for` support in the emitter was replaced with an `emitc.for` op implementation and an SCF to EmitC conversion with 2633d94.
Would it be okay if we only accept your patch if I am unable to complete my work within a reasonable time?

**Comment by AlexDenisov** [comment]
> Would it be okay if we only accept your patch if I am unable to complete my work within a reasonable time?

Totally fine with me, no pressure 🙌 

> After several discussions

Are these happening in the public space somewhere? I have some questions/suggestions about function prototypes, but would like to discuss them before submitting any patches as the implementation is a bit more involved.

**Comment by marbre** [comment]
> Are these happening in the public space somewhere? I have some questions/suggestions about function prototypes, but would like to discuss them before submitting any patches as the implementation is a bit more involved.

Some of these were in person at last year's C4ML and EuroLLVM, others via email, discord or discourse and even in pull requests. However, I'd love to move the entire discussion to discourse! So please feel free to open new topics with your questions and suggestions at https://discourse.llvm.org/c/mlir/31 and give me and my colleague @simon-camp a ping. If the questions/suggestions are not directly related to upstream, https://github.com/iml130/mlir-emitc/issues can be an alternative place.

**Comment by AlexDenisov** [comment]
Implemented here https://github.com/llvm/llvm-project/pull/78336

**Comment by marbre** [comment]
> Implemented here #78336

If somebody tries to follow, the functionally was actually implemented with #79612, which just got merged.

**Pull request closed without merging**
