### PR TITLE
[lldb] Unify CalculateMD5 return types

### PR DESCRIPTION
**Pull request by Awfa**
This is a retake of https://github.com/llvm/llvm-project/pull/90921 which got reverted because I forgot to modify the CalculateMD5 unit test I had added in https://github.com/llvm/llvm-project/pull/88812

The prior failing build is here: https://lab.llvm.org/buildbot/#/builders/68/builds/73622
To make sure this error doesn't happen, I ran `ninja ProcessGdbRemoteTests` and then executed the resulting test binary and observed the `CalculateMD5` test passed.

# Overview
In my previous PR: https://github.com/llvm/llvm-project/pull/88812, @JDevlieghere suggested to match return types of the various calculate md5 functions.

This PR achieves that by changing the various calculate md5 functions to return `llvm::ErrorOr<llvm::MD5::MD5Result>`.
 
The suggestion was to go for `std::optional<>` but I opted for `llvm::ErrorOr<>` because local calculate md5 was already possibly returning `ErrorOr`.

To make sure I didn't break the md5 calculation functionality, I ran some tests for the gdb remote client, and things seem to work.

# Testing
1. Remote file doesn't exist
image

1. Remote file differs
image

1. Remote file matches
image

## Test gaps
Unfortunately, I had to modify `lldb/source/Plugins/Platform/MacOSX/PlatformDarwinDevice.cpp` and I can't test the changes there. Hopefully, the existing test suite / code review from whomever is reading this will catch any issues.

### CODE REVIEW

**Comment by Awfa** [comment]
@JDevlieghere , do you know if there's a way to run buildbot on a merge of this PR and main branch - just to validate the build/tests work before this merge?

The [llvm contributing guide](https://llvm.org/docs/MyFirstTypoFix.html#myfirsttypofix-issues-after-landing-your-pr) says this is normal workflow - but I worry since I am using a lot of the maintainers' time to merge / revert the changes for me since I don't have write access.

**Comment by Awfa** [comment]
> ⚠️ C/C++ code formatter, clang-format found issues in your code. ⚠️
> 
> You can test this locally with the following command:
> View the diff from clang-format here.

This formatter alert is outdated - by the time this arrived, my PR had the issue fixed already.

**Comment by JDevlieghere** [comment]
> @JDevlieghere , do you know if there's a way to run buildbot on a merge of this PR and main branch - just to validate the build/tests work before this merge?

Not that I know. When failures are macOS specific I'm happy to apply a PR locally and run the test suite and other folks with specific configurations might do the same, but that's about all I can think of.

> The [llvm contributing guide](https://llvm.org/docs/MyFirstTypoFix.html#myfirsttypofix-issues-after-landing-your-pr) says this is normal workflow - but I worry since I am using a lot of the maintainers' time to merge / revert the changes for me since I don't have write access.

No worries, it's totally normal and we're happy to help with that!

**Review by JDevlieghere — APPROVED** [review]

**Comment by Awfa** [comment]
> > @JDevlieghere , do you know if there's a way to run buildbot on a merge of this PR and main branch - just to validate the build/tests work before this merge?
> 
> Not that I know. When failures are macOS specific I'm happy to apply a PR locally and run the test suite and other folks with specific configurations might do the same, but that's about all I can think of.
> 
> > The [llvm contributing guide](https://llvm.org/docs/MyFirstTypoFix.html#myfirsttypofix-issues-after-landing-your-pr) says this is normal workflow - but I worry since I am using a lot of the maintainers' time to merge / revert the changes for me since I don't have write access.
> 
> No worries, it's totally normal and we're happy to help with that!

Can I ask you merge this for me? Hopefully no reverts this time :)

**Pull request merged**
