### PR TITLE
[DirectX] Replace ResourceFlag enum with struct fields

### PR DESCRIPTION
**Pull request by python3kgae**
Remove the enum about ResourceFlag.
Add struct ResourceFlags which save the resource flags with bool fields.

This will get better yaml dump.

For #103275

### CODE REVIEW

**Review by damyanp — APPROVED** [review]
Is this a follow up to a previous PR?  Might be good to have them linked.

**Review by bogner — APPROVED** [review]

**Comment by python3kgae** [comment]
> Is this a follow up to a previous PR? Might be good to have them linked.

Done.

**Comment by llvm-beanz** [comment]
Have you considered instead handling this the way the SFI0 feature flags are enabled? That allows the YAML to be more expressive.

**Comment by python3kgae** [comment]
> Have you considered instead handling this the way the SFI0 feature flags are enabled? That allows the YAML to be more expressive.

Updated.

**Review by llvm-beanz — APPROVED** [review]

**Pull request merged**
