### PR TITLE
[clang][ASTImporter] Only reorder fields of RecordDecls

### PR DESCRIPTION
**Pull request by Michael137**
Prior to `e9536698720ec524cc8b72599363622bc1a31558` (https://reviews.llvm.org/D154764) we only re-ordered the fields of `RecordDecl`s. The change refactored this logic to make sure `FieldDecl`s are imported before other member decls. However, this change also widened the types of `DeclContext`s we consider for re-ordering from `RecordDecl` to anything that's a `DeclContext`. This seems to have been just a drive-by cleanup.

Internally we've seen numerous crashes in LLDB where we try to perform this re-ordering on fields of `ObjCInterfaceDecl`s.

This patch restores old behaviour where we limit the re-ordering to just `RecordDecl`s.

rdar://119343184
rdar://119636274
rdar://119832131

### CODE REVIEW

**Comment by Michael137** [comment]
Need to sort out some test failures

**Comment by balazske** [comment]
I can not check what caused exactly the problems but the change looks correct and in change D154764 there seems to be no reason for re-ordering at non-record objects. As an improvement, some tests could be added that check for re-ordering  at `RecordDecl` and (this is the more important) no re-ordering at `ObjCInterfaceDecl`.

**Comment by Michael137** [comment]
> I can not check what caused exactly the problems but the change looks correct and in change D154764 there seems to be no reason for re-ordering at non-record objects. As an improvement, some tests could be added that check for re-ordering at `RecordDecl` and (this is the more important) no re-ordering at `ObjCInterfaceDecl`.

Agreed it would be nice to get a test for this. We have a test that checks re-ordering of `RecordDecl`s (`CXXRecordDeclFieldOrderShouldNotDependOnImportOrder`). For `ObjCInterfaceDecl`s it's trickier because, AFAIK, they neither support in-class member initialisers nor function bodies that could trigger a different import order. Any ideas?

**Review by adrian-prantl — APPROVED** [review]
Test would be nice, but generally this looks like a reasonable modification.

**Comment by Michael137** [comment]
Tried to find a way to test "objective-c fields aren't reordered". After talking to some objective-c experts, there doesn't seem to be a good way to force such "incorrect field order", because it's strictly an in-order language. Reducing the LLDB crashes has been tricky because the reproducers require a somewhat complex setup. @balazske If you're ok with it, I'll go ahead and merge it like this, given it's essentially a minor revert.

Separately I'll try to see if I can simplify the LLDB reproducer, but that'll take some time

**Review by balazske — APPROVED** [review]
This reordering is not a significant feature (and may change in the future) and no test existed before, it is enough (if this exists) if there is a GDB test for the crash.

**Pull request merged**
