### PR TITLE
[AArch64] Added feature dependencies for SME2p1 to TargetParser

### PR DESCRIPTION
**Pull request by Lukacma**
This patches adds missing target-feature dependencies for SME2.1

### CODE REVIEW

**Comment by Lukacma** [comment]
Seems like I cannot add reviewers yet so I am tagging you for review @momchil-velikov @hassnaaHamdi @CarolineConcatto

**Comment by CarolineConcatto** [comment]
Hi @Lukacma ,
It would be nice if you can add a test with clang cc1 to show what was the problem you are trying to fix.
Without this change  clang cc1 does not see/understand the SVE type sizes

**Comment by Lukacma** [comment]
Yes I was thinking exactly about this but I couldn't find a good way to directly test this. Ideally we would have some sme2p1 tests, which just wouldn't work when cc1 would be used, but we don't have that as far as I can tell. I could create a dummy test, which wouldn't pass without this change but that felt little odd to me. Therefore, I wanted to check if there is better way to test this fix I might have missed.

**Comment by momchil-velikov** [comment]
> Yes it could be like that. I was just wondering if there is not a better way than creating dummy programs and seeing if they compile. We have a test in aarch64-implied-sme-features.c which tests this nicely like this :
> 
> ```
> // RUN: %clang -target aarch64-linux-gnu -march=armv8-a+sme %s -### 2>&1 | FileCheck %s --check-prefix=SME-IMPLY
> // SME-IMPLY: "-target-feature" "+bf16"{{.*}} "-target-feature" "+sme"
> ```
> 
> Unfortunately this doesn't work with -cc1 and I was wondering if there is not a way to do something similiar for -cc1 that I am missing. If not I will create the dummy test.

Add something like
```
// RUN: %clang_cc1  -triple aarch64-linux -target-feature +sme2p1 -S  -fsyntax-only -verify %s

#include <arm_sme.h>

void f(svfloat32_t x) {}

// expected-no-diagnostics
```

**Comment by Lukacma** [comment]
Testcase added

**Review by CarolineConcatto — APPROVED** [review]
Thank you @Lukacma

**Pull request merged**
