### PR TITLE
[clang-format] Optimize processing .clang-format-ignore files

### PR DESCRIPTION
**Pull request by owenca**
Reuse the patterns governing the previous input file being formatted if the current input file is from the same directory.

### CODE REVIEW

**Review by HazardyKnusperkeks — APPROVED** [review]

**Comment by nico** [comment]
This seems to cause test failures on win: http://45.33.8.238/win/87705/step_7.txt

**Comment by owenca** [comment]
It had passed my local tests (x64 Native Tools Command Prompt for VS 2022) and the buildkite win build, so I wonder if it has something to do with the grep in the failed buildbot (only https://lab.llvm.org/buildbot/#/builders/123/builds/23808 so far) as I only used the POSIX options -F and -x. Should I turn it off for Windows like we did to [style-on-command-line.cpp](https://github.com/llvm/llvm-project/blob/8c72ff716b3e4b298695fa3faf6add860c6dbcb2/clang/test/Format/style-on-command-line.cpp#L50)?

**Comment by owenca** [comment]
Relanded as b53628a52d19. (See [here](https://github.com/llvm/llvm-project/commit/42ec976184acd40436acd7104ad715c60ca3e7ed#commitcomment-136674701)).

**Comment by owenca** [comment]
> This still breaks tests on win: http://45.33.8.238/win/88113/step_7.txt

I didn't get any email for the failure. Is this a regular LLVM buildbot?

If it chokes on `grep -Fx`, can you (or whoever has access to it) install a POSIX-compliant grep? It seems all other Windows buildbots got no problems.

**Comment by nico** [comment]
Any reason the test can't use FileCheck like all the other tests?

**Comment by owenca** [comment]
See #77977.

**Pull request merged**
