### PR TITLE
[mlir][math] Fix casting mistake in tanh expansion and test

### PR DESCRIPTION
**Pull request by srcarroll**
Accidentally used sitofp for bool cast instead of uitofp.  A correctness test has also been added

### CODE REVIEW

**Comment by srcarroll** [comment]
My bad for using the wrong cast. I had this tested in my own pipeline but this cast ended up getting removed so I didn't notice

**Comment by makslevental** [comment]
Is the original/current actually wrong? `arith::CmpFOp` returns `i1` i.e., signless, which means roughly (in my understanding, which might be mistaken) "[up to you](https://mlir.llvm.org/docs/Rationale/Rationale/#integer-signedness-semantics)", i.e., target (dialect or arch or whatever) dependent. So how can you pick `SIToFPOp` or `UIToFPOp` at all here? I mean, maybe the real issue is that there's no `arith::IToFP` for cases like this.

**Comment by srcarroll** [comment]
Good point/question. I only knew by observing that sitofp was "wrong" (gave unintentional results) is it gave me -1 for true and 0 for false. Whereas uitofp gives me 1 for true.  But honestly not sure if this works as a target agnostic solution.

**Comment by srcarroll** [comment]
Any suggestions? Should i just revert my original merge until this is sorted?

**Comment by makslevental** [comment]
> Any suggestions? Should i just revert my original merge until this is sorted?

General operating procedure is to get build bots back to green ASAP, i.e., revert or "fix forward". Technically this didn't break build bots I guess but same good faith interpretation applies (since you believe this is a breaking change). I can't approve because I can't manage to unwind right now all of bit patterns so yea revert (but obv don't abandon this one...).

**Comment by srcarroll** [comment]
ok. reverting https://github.com/llvm/llvm-project/pull/85429 and drafting this for now

**Comment by srcarroll** [comment]
closing in favor of https://github.com/llvm/llvm-project/pull/85436

**Pull request closed without merging**
