### PR TITLE
[llvm][CMake] Check dependency cxx source compiles

### LINKED ISSUE #53950: [CMake] `find_package(LLVM CONFIG)` may fail when the project does not use C
1. Build LLVM 14 rc1 with `LLVM_ENABLE_FFI` and `LLVM_ENABLE_TERMINFO` options enabled.
2. Create a C++ only CMake project :
```cmake
cmake_minimum_required(VERSION 3.16)  # just to silence the warning when this line is missing
project(test LANGUAGES CXX)
find_package(LLVM CONFIG REQUIRED)
```
3. Configure this project:
```console
$ cmake -Bbuild . -DLLVM_DIR=/root/llvm-project-14.0.0rc1.src/llvm/build/lib/cmake/llvm/
-- The CXX compiler identification is GNU 12.0.1
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Check for working CXX compiler: /usr/bin/c++ - skipped
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at /usr/share/cmake/Modules/Internal/CheckSourceCompiles.cmake:44 (message):
  check_source_compiles: C: needs to be enabled before use.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CheckCSourceCompiles.cmake:76 (cmake_check_source_compiles)
  /root/llvm-project-14.0.0rc1.src/llvm/build/lib/cmake/llvm/FindFFI.cmake:44 (check_c_source_compiles)
  /root/llvm-project-14.0.0rc1.src/llvm/build/lib/cmake/llvm/LLVMConfig.cmake:145 (find_package)
  CMakeLists.txt:3 (find_package)


-- Could NOT find FFI (missing: HAVE_FFI_CALL)
CMake Error at /usr/share/cmake/Modules/Internal/CheckSourceCompiles.cmake:44 (message):
  check_source_compiles: C: needs to be enabled before use.
Call Stack (most recent call first):
  /usr/share/cmake/Modules/CheckCSourceCompiles.cmake:76 (cmake_check_source_compiles)
  /root/llvm-project-14.0.0rc1.src/llvm/build/lib/cmake/llvm/FindTerminfo.cmake:21 (check_c_source_compiles)
  /root/llvm-project-14.0.0rc1.src/llvm/build/lib/cmake/llvm/LLVMConfig.cmake:152 (find_package)
  CMakeLists.txt:3 (find_package)


-- Could NOT find Terminfo (missing: Terminfo_LINKABLE)
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.11")
-- Found LibXml2: /usr/lib64/libxml2.so (found version "2.9.12")
-- Configuring incomplete, errors occurred!
See also "/root/test/build/CMakeFiles/CMakeOutput.log".
```

Changing the `project(test LANGUAGES CXX)` line to `project(test LANGUAGES C CXX)` makes the error go away, but that's just a work-around than a solution.

CMake version: 3.22.2
Introduced by: https://reviews.llvm.org/D114327

### PR DESCRIPTION
**Pull request by ekilmer**
If a CMake project doesn't enable the C language, then the CMake FFI and Terminfo find modules will fail their checks for compilation and linking.

This commit allows projects to enable only C++ by first checking if a C compiler is set before testing C source compilation; if not, it checks whether C++ compilation succeeds.

Fixes #53950

### CODE REVIEW

**Comment by AdvenamTacet** [comment]
Hey, LGTM but let's wait for a review from someone who worked on those cmakes. @jackoalan @JDevlieghere as you implemented/reviewed [D114327](https://reviews.llvm.org/D114327), could you review that PR?

Also, @lzaoral does it fix your issue from https://github.com/llvm/llvm-project/issues/53950?

@ekilmer did you test it only on git-main version of LLVM?

**Comment by lzaoral** [comment]
@ekilmer Thanks for the PR but in the meantime I've stopped contributing to projects that depend on LLVM so I won't test it.

Moreover, unless this change is also backported to LLVM 14, projects will still need to use some workaround for the original issue.

**Comment by JDevlieghere** [comment]
Is there any reason to not use `check_cxx_source_compiles` unconditionally?

**Comment by ekilmer** [comment]
> Is there any reason to not use `check_cxx_source_compiles` unconditionally?

LLVM has C API bindings, so it's possible that a user would only enable the C language. Unconditionally using `check_cxx_source_compiles` would fail due to a missing C++ compiler.

**Comment by JDevlieghere** [comment]
> LLVM has C API bindings, so it's possible that a user would only enable the C language. Unconditionally using `check_cxx_source_compiles` would fail due to a missing C++ compiler.

These modules are used when configuring the LLVM build itself. Can you really do that with just a C compiler? I'm aware of the bindings but without a C++ compiler, you can't build the thing it's binding in the first place. So is there  a configuration mode where you only build the C bindings against a pre-built LLVM? Is libffi or terminfo used in those C bindings?

**Comment by ekilmer** [comment]
> These modules are used when configuring the LLVM build itself. Can you really do that with just a C compiler? I'm aware of the bindings but without a C++ compiler, you can't build the thing it's binding in the first place. So is there a configuration mode where you only build the C bindings against a pre-built LLVM? Is libffi or terminfo used in those C bindings?

You're correct that building the LLVM project requires a C++ compiler, and I'm not sure if building the C bindings separately is possible, but it doesn't look like it. I'm also not sure if libffi or terminfo are used in the C bindings.

However, I think that is beside the point. This PR is fixing _downstream consumers_ of LLVM---those building projects out-of-tree.

In the linked issue #53950, the opening post gives a small, standalone CMakeLists.txt that calls `find_package(LLVM)`. The way [LLVM's installed configuration file](https://github.com/llvm/llvm-project/blob/39f4ec5854a1ca34c70343c3ed1648a6be5b6b82/llvm/cmake/modules/LLVMConfig.cmake.in#L51-L66) is written, it _always_ tries to find libffi and terminfo (when LLVM itself was configured and built to find and use them).

A user might want to (or already does) _only_ enable the C compiler, and I think we should continue to support that. Unless the LLVM C bindings were to be split from the other targets (a breaking change), a call to `find_package(LLVM)` will always (unless it was built without) attempt to run the tests when finding libFFI and Terminfo.

More concretely, the following is an example project that currently works using LLVM 17, 16, 15, and 14 C bindings, and unconditionally using `check_cxx_source_compiles` would break it:

```cmake
# CMakeLists.txt
cmake_minimum_required(VERSION 3.20)
project(llvm-c-test LANGUAGES C)

find_package(LLVM REQUIRED)

include_directories(${LLVM_INCLUDE_DIR})
add_executable(sum sum.c)
target_link_libraries(sum PRIVATE LLVM-C)
```

<details>
  <summary>With a sibling file `sum.c`</summary>

  ```c
/**
 * Copied from https://github.com/QDucasse/LLVM-C/blob/9cfdece261d406f6dcdf90aa42843843707a7a43/examples/Chapter1/sum.c
 * 
 * LLVM equivalent of:
 *
 * int sum(int a, int b) {
 *     return a + b;
 * }
 */

#include <llvm-c/Core.h>
#include <llvm-c/Analysis.h>
#include <llvm-c/BitWriter.h>
#include <llvm-c/Target.h>
#include <llvm-c/TargetMachine.h>

#include <stdio.h>
#include <stdlib.h>

int main(int argc, char const *argv[]) {
    // Module creation
    LLVMModuleRef mod = LLVMModuleCreateWithName("my_module");

    // Function prototype creation
    LLVMTypeRef param_types[] = { LLVMInt32Type(), LLVMInt32Type() };
    LLVMTypeRef ret_type = LLVMFunctionType(LLVMInt32Type(), param_types, 2, 0);
    LLVMValueRef sum = LLVMAddFunction(mod, "sum", ret_type);
    LLVMBasicBlockRef entry = LLVMAppendBasicBlock(sum, "entry");
    // Builder creation
    LLVMBuilderRef builder = LLVMCreateBuilder();
    LLVMPositionBuilderAtEnd(builder, entry);

    // Instruction added to the builder
    LLVMValueRef tmp = LLVMBuildAdd(builder, LLVMGetParam(sum, 0), LLVMGetParam(sum, 1), "tmp");
    LLVMBuildRet(builder, tmp);

    //Analysis
    char *error = NULL;
    LLVMVerifyModule(mod, LLVMAbortProcessAction, &error);
    LLVMDisposeMessage(error);

    // Bitcode writing to file
    if (LLVMWriteBitcodeToFile(mod, "sum.bc") != 0) {
        fprintf(stderr, "error writing bitcode to file, skipping\n");
    }

    // Dispose the builder
    LLVMDisposeBuilder(builder);
}
  ```

</details>

**Review by JDevlieghere — APPROVED** [review]
Thanks, it wasn't clear to me that this was functionality was also triggered when including llvm from a downstream project. Thank you for clarifying that and even including an example. This shows that it's indeed necessary to check both `check_c_source_compiles` and `check_cxx_source_compiles`. LGTM!

**Comment by ekilmer** [comment]
@JDevlieghere Great! I don't have commit access, so would you (or someone else we can ping) be able to help me out with landing this?

Thank you for the review!

**Pull request merged**
