### PR TITLE
[PAC][llvm-readobj][ELF][AArch64] Define static AUTH TLSDESC relocations

### PR DESCRIPTION
**Pull request by kovdan01**
See specification https://github.com/ARM-software/abi-aa/pull/295

### CODE REVIEW

**Comment by kovdan01** [comment]
See also https://github.com/ARM-software/abi-aa/issues/293

**Comment by kovdan01** [comment]
As discussed in https://github.com/ARM-software/abi-aa/issues/293#issuecomment-2439717671, these relocation codes are OK as they belong to the private space reserved for experiments.

**Review by jh7370 — APPROVED** [review]
Looks fine to me, once the values are confirmed as good in the reference material.

It may be worth including a link in the commit description to the relevant documentation, to reduce the number of hoops that have to be jumped through to get to the source of these reloc types.

**Comment by kovdan01** [comment]
> It may be worth including a link in the commit description to the relevant documentation, to reduce the number of hoops that have to be jumped through to get to the source of these reloc types.

Added a link to the PR in the ARM's repo, thanks!

> Looks fine to me, once the values are confirmed as good in the reference material.

@smithp35 If the values are OK, could you please give an explicit approval here?

**Comment by kovdan01** [comment]
> Looks fine to me, once the values are confirmed as good in the reference material.

@smithp35 If the values are OK, could you please give an explicit approval here?

**Review by smithp35 — APPROVED** [review]

**Pull request merged**
