### PR TITLE
[MLIR][LLVM] Use CyclicReplacerCache for recursive DIType import

### PR DESCRIPTION
**Pull request by zyx-billy**
Use the new CyclicReplacerCache from https://github.com/llvm/llvm-project/pull/98202 to support importing of recursive DITypes in LLVM dialect's DebugImporter. This helps simplify the implementation, allows for separate testing of the cache infra itself, and as a result we even got more efficient translations.

---

Stacked PRs:
- https://github.com/llvm/llvm-project/pull/98202
- ➡️ https://github.com/llvm/llvm-project/pull/98203

### CODE REVIEW

**Review by Mogball — APPROVED** [review]

**Comment by Dinistro** [comment]
We have a case where a cycle involving a DISubprogram, and we hit an assertion that it is attempted to look it up for the third time.

The following input is a reproducer of said issue. It seems that the presence of 3 types transitively referring back to the subprogram break an assumption made by this.

```
; ModuleID = 'out.ll'
source_filename = "out.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: nocallback nofree nosync nounwind speculatable willreturn memory(none)
declare void @llvm.dbg.declare(metadata, metadata, metadata) #0

define void @foo() {
L.entry:
  call void @llvm.dbg.declare(metadata ptr null, metadata !4, metadata !DIExpression()), !dbg !22
  ret void
}

attributes #0 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }

!llvm.dbg.cu = !{!0}
!llvm.module.flags = !{!3}

!0 = distinct !DICompileUnit(language: DW_LANG_Fortran90, file: !1, producer: "F90 Flang - 1.5 2017-05-01", isOptimized: true, flags: "", runtimeVersion: 0, emissionKind: FullDebug, enums: !2, retainedTypes: !2, globals: !2, imports: !2, nameTableKind: None)
!1 = !DIFile(filename: "file.f90", directory: "/")
!2 = !{}
!3 = !{i32 2, !"Debug Info Version", i32 3}
!4 = !DILocalVariable(name: "x_min", arg: 1, scope: !5, file: !1, line: 27, type: !21)
!5 = distinct !DISubprogram(name: "accelerate_kernel", scope: !6, file: !1, line: 27, type: !7, scopeLine: 27, spFlags: DISPFlagDefinition | DISPFlagOptimized, unit: !0, retainedNodes: !2)
!6 = !DIModule(scope: !0, name: "accelerate_kernel_module", file: !1)
!7 = !DISubroutineType(types: !8)
!8 = !{null, !9, !16, !20}
!9 = !DICompositeType(tag: DW_TAG_array_type, baseType: !10, size: 64, align: 64, elements: !11)
!10 = !DIBasicType(name: "double precision", size: 64, align: 64, encoding: DW_ATE_float)
!11 = !{!12}
!12 = !DISubrange(lowerBound: !13, upperBound: !15)
!13 = distinct !DILocalVariable(scope: !5, file: !1, type: !14, flags: DIFlagArtificial)
!14 = !DIBasicType(name: "integer*8", size: 64, align: 64, encoding: DW_ATE_signed)
!15 = distinct !DILocalVariable(scope: !5, file: !1, type: !14, flags: DIFlagArtificial)
!16 = distinct !DICompositeType(tag: DW_TAG_array_type, baseType: !10, size: 64, align: 64, elements: !17)
!17 = !{!18}
!18 = !DISubrange(lowerBound: !13, upperBound: !19)
!19 = distinct !DILocalVariable(scope: !5, file: !1, type: !14, flags: DIFlagArtificial)
!20 = !DICompositeType(tag: DW_TAG_array_type, baseType: !10, size: 64, align: 64, elements: !17)
!21 = !DIBasicType(name: "integer", size: 32, align: 32, encoding: DW_ATE_signed)
!22 = !DILocation(line: 0, scope: !5)
```

So far, I'm not sure if this could be fixed by implementing the `DIRecursiveTypeAttrInterface` or if something else is broken. If it's "just" implementing the interface, I'm a bit afraid that there might be other cases like this that we might encounter along the way.

**Comment by zyx-billy** [comment]
Ohhh... I see. There's no guarantee from this import algo that we'll never see a node 3 times. If not all nodes can break cycles, having multiple back-edges will cause it to die.
```
0 -> 1
1 -> 2, 3
2 -> 0
3 -> 0
```
Everything goes fine when looping through the first loop until we reach the second loop 🤦 
```
0 -> 1 -> 2 -> 0 -> 1 -> 2'
                      -> 3 -> 0
```

Thanks for the repro btw. Very easy to digest. It seems having a cycle-breaking node in each loop is not enough to guarantee we never see a node 3 times. We have to make sure it's impossible to walk the graph so that you can go through a node 3 times before visiting a cycle-breaking node twice (and in this case such a violating path would be `0 -> 1 -> 2 -> 0 -> 1 -> 3 -> 0`). So I totally agree with your concern... can we do this without requiring all nodes to be cycle-breaking 🤔 (or is anything special with `0` that we can use to refine our rule).

**Comment by Dinistro** [comment]
I'm unsure if making 0 (in this case DISubprogram) a cycle breaker would solve the issue or if we would require changes to the algorithm all-together. 

Assuming that cycle breaking is enough, then we only have specific nodes we find that will have back-edges when walking the debug metadata in the import. So far, we are aware of `DICompositeType` and `DISubprogram`.  The question is if there are any more cases where this can happen.
I currently see three different way in how we could deal with that:
1. Add cycle-breaking support for every node type
2. Deeply analyse the debug metadata documentation and find all necessary cycle-breakers. Given the state of the documentation, this might be very hard, though.
3. Iteratively add cycle breaking for issues we find along the way. While this might require some cycles (pun intended), the assertion should help us in finding these. 


> Thanks for the repro btw. Very easy to digest. 

`llvm-reduce` can do magic ;P

**Comment by gysit** [comment]
> can we do this without requiring all nodes to be cycle-breaking 🤔 (or is anything special with 0 that we can use to refine our rule).

What would be the implication in terms of implementation and performance if we make all nodes self recursive? I assume the implementation overheads could be hidden to some extend in a base class (but not entirely)?

I would probably go with the pragmatic solution (3.) and make `DISubprogram` cycle-breaking initially. I think it is fair to say that `DISubprogram` is special since it can is a scope and it has a type. I don't think this is the case for another scope attribute. But yes there may be other cyclic node types.

**Comment by zyx-billy** [comment]
If we made all nodes cycle-breaking... We can either make each node have a dedicated self-reference mode, or use a dedicated back-reference DIAttr, but either way we have to deal with extra casting / checking everywhere 🤔. So I agree it's worth trying (3.) first and see if that solves everything in practice already.

**Comment by Dinistro** [comment]
> If we made all nodes cycle-breaking... We can either make each node have a dedicated self-reference mode, or use a dedicated back-reference DIAttr, but either way we have to deal with extra casting / checking everywhere 🤔. So I agree it's worth trying (3.) first and see if that solves everything in practice already.

Let's give it a try then. Do you have some spare cycles, or should one of us try to allocate time to try this?

**Comment by zyx-billy** [comment]
I might not be able to get to it these two weeks, so if you have time that would be great (might also be easier to test with the rest of your inputs) Happy to help if needed 🙏.

**Comment by Dinistro** [comment]
> I might not be able to get to it these two weeks, so if you have time that would be great (might also be easier to test with the rest of your inputs) Happy to help if needed 🙏.

We are also quite under water, but I'll try to get back to this next week.

**Pull request merged**
