### PR TITLE
[RISCV] Zabha/Zacas implies Zaamo

### PR DESCRIPTION
**Pull request by tclin914**
The Zabha/Zacas extension depends upon the Zaamo extension. 
Ref: https://github.com/riscv/riscv-isa-manual/blob/main/src/zacas.adoc
       https://github.com/riscv/riscv-isa-manual/blob/main/src/zabha.adoc.

### CODE REVIEW

**Review by wangpc-pp — APPROVED** [review]
LGTM.
IIUC, there should be no compatibility issue since both of these two extensions are new?

**Comment by michaelmaitland** [comment]
There was some related discussion at https://github.com/rust-lang/rust/pull/130877#issuecomment-2379423609. Will this cause a problem with compatibility with older versions of binutils?

**Comment by topperc** [comment]
> LGTM. IIUC, there should be no compatibility issue since both of these two extensions are new?

Zabha was added to binutils 8 months ago. Zacas was added 5 months ago. Not sure if there was a release in between.

**Comment by tclin914** [comment]
Zabha and Zacas were supported from binutils 2.43 (the latest release) and there wasn't a binutils release between them.
In binutils 2.43, Zabha/Zacas imply A and A implies Zaamo and Zalrsc. So that we can say Zabha/Zacas also imply Zaamo.
Zabha/Zacas have been fixed to imply Zaamo instead of A by https://patchwork.sourceware.org/project/binutils/patch/20241008011035.3538-1-zengxiao@eswincomputing.com/  in master branch last month.

The experiment I made with binutils 2.43:
$ riscv64-unknown-elf-clang -march=rv64izabha main.c -S -o main.s
$ cat main.s
    ...
    .attribute      5, "rv64i2p1_zaamo1p0_zabha1p0"
    ...
$ riscv64-unknown-elf-as main.s -o main.o
$ riscv64-unknown-elf-readelf -A main.o
  ...
  Tag_RISCV_arch: "rv64i2p1_a2p1_zaamo1p0_zabha1p0_zalrsc1p0"

**Review by topperc — APPROVED** [review]
LGTM

**Pull request merged**
