### PR TITLE
[Clang] [Sema] Fix dependence of DREs in lambdas with an explicit object parameter

### LINKED ISSUE #70604: Deducing this lambda causes crash when using explicit reference capture
Compiler Explorer: [https://godbolt.org/z/6vMEhdGqx](https://godbolt.org/z/6vMEhdGqx)

This little example causes the crash:
```
auto dothing(int num)
{
    auto fun =  [&num](this auto&& self) -> void {
        auto copy = num;
    };

    fun();
}
```

Interestingly if the signature of fun is changed to `[&](this auto&& self) -> void`, it works fine even though in both cases num is captured by reference.

Note that there is another issue at play since changing the explicit capture to the & catch all does not fix the code that I reduced this example from. Instead I still get a crash but this time a "cannot compile this l-value expression yet" from codegen.

```
clang++: /root/llvm-project/clang/lib/AST/ASTContext.cpp:2299: clang::TypeInfo clang::ASTContext::getTypeInfoImpl(const clang::Type*) const: Assertion `!A->getDeducedType().isNull() && "cannot request the size of an undeduced or dependent auto type"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-assertions-trunk/bin/clang++ -gdwarf-4 -g -o /app/output.s -mllvm --x86-asm-syntax=intel -S --gcc-toolchain=/opt/compiler-explorer/gcc-snapshot -fcolor-diagnostics -fno-crash-diagnostics -std=c++23 <source>
1.	<eof> parser at end of file
2.	Per-file LLVM IR generation
3.	<source>:3:16: Generating code for declaration 'dothing(int)::(anonymous class)::operator()'
 #0 0x00000000037569a8 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x37569a8)
 #1 0x000000000375466c llvm::sys::CleanupOnSignal(unsigned long) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x375466c)
 #2 0x000000000369d018 CrashRecoverySignalHandler(int) CrashRecoveryContext.cpp:0:0
 #3 0x00007efe146d7420 __restore_rt (/lib/x86_64-linux-gnu/libpthread.so.0+0x14420)
 #4 0x00007efe1419a00b raise (/lib/x86_64-linux-gnu/libc.so.6+0x4300b)
 #5 0x00007efe14179859 abort (/lib/x86_64-linux-gnu/libc.so.6+0x22859)
 #6 0x00007efe14179729 (/lib/x86_64-linux-gnu/libc.so.6+0x22729)
 #7 0x00007efe1418afd6 (/lib/x86_64-linux-gnu/libc.so.6+0x33fd6)
 #8 0x0000000006db4355 clang::ASTContext::getTypeInfoImpl(clang::Type const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6db4355)
 #9 0x0000000006da2c27 clang::ASTContext::getTypeInfo(clang::Type const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6da2c27)
#10 0x0000000006db570b clang::ASTContext::getPreferredTypeAlign(clang::Type const*) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6db570b)
#11 0x0000000006db603b clang::ASTContext::getDeclAlign(clang::Decl const*, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x6db603b)
#12 0x0000000003e20310 clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(clang::VarDecl const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e20310)
#13 0x0000000003e2165b clang::CodeGen::CodeGenFunction::EmitVarDecl(clang::VarDecl const&) (.part.0) CGDecl.cpp:0:0
#14 0x0000000003e21900 clang::CodeGen::CodeGenFunction::EmitDecl(clang::Decl const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3e21900)
#15 0x0000000003a64e07 clang::CodeGen::CodeGenFunction::EmitDeclStmt(clang::DeclStmt const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3a64e07)
#16 0x0000000003a78d87 clang::CodeGen::CodeGenFunction::EmitSimpleStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3a78d87)
#17 0x0000000003a721d5 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3a721d5)
#18 0x0000000003a786bc clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3a786bc)
#19 0x0000000003ad7c96 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::Stmt const*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3ad7c96)
#20 0x0000000003aeacda clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3aeacda)
#21 0x0000000003b4bcc3 clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3b4bcc3)
#22 0x0000000003b46dc5 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3b46dc5)
#23 0x0000000003b51cee clang::CodeGen::CodeGenModule::EmitDeferred() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3b51cee)
#24 0x0000000003b546f3 clang::CodeGen::CodeGenModule::Release() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3b546f3)
#25 0x00000000049c1faa (anonymous namespace)::CodeGeneratorImpl::HandleTranslationUnit(clang::ASTContext&) ModuleBuilder.cpp:0:0
#26 0x00000000049c0975 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x49c0975)
#27 0x0000000005ecf3b9 clang::ParseAST(clang::Sema&, bool, bool) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x5ecf3b9)
#28 0x00000000049c0068 clang::CodeGenAction::ExecuteAction() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x49c0068)
#29 0x0000000004223d29 clang::FrontendAction::Execute() (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4223d29)
#30 0x00000000041a4e0e clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x41a4e0e)
#31 0x0000000004302cfe clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x4302cfe)
#32 0x0000000000bf4a76 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbf4a76)
#33 0x0000000000bec33a ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) driver.cpp:0:0
#34 0x0000000004000359 void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const::'lambda'()>(long) Job.cpp:0:0
#35 0x000000000369d4c4 llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x369d4c4)
#36 0x000000000400094f clang::driver::CC1Command::Execute(llvm::ArrayRef<std::optional<llvm::StringRef>>, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char>>*, bool*) const (.part.0) Job.cpp:0:0
#37 0x0000000003fc8955 clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3fc8955)
#38 0x0000000003fc93bd clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&, bool) const (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3fc93bd)
#39 0x0000000003fd12e5 clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::pair<int, clang::driver::Command const*>>&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0x3fd12e5)
#40 0x0000000000bf1f1c clang_main(int, char**, llvm::ToolContext const&) (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbf1f1c)
#41 0x0000000000aeb0f1 main (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xaeb0f1)
#42 0x00007efe1417b083 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x24083)
#43 0x0000000000bebe1e _start (/opt/compiler-explorer/clang-assertions-trunk/bin/clang+++0xbebe1e)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Compiler returned: 134
```

### LINKED ISSUE #79754: ICE when returning the captured reference in the deducing this lambda
```cpp
int main() {
  int x = 42;
  auto l = [&x](this auto&& self, int n) {
    return x;
  };
  l(10);
}
```
https://godbolt.org/z/bdvKn9M6T

### LINKED ISSUE #84163: Capture of `*this` in explicit object parameter lambda doesn't respect qualifiers
```cpp
struct S {
  int x;

  auto foo() {
    return [*this](this auto&&) {
      __builtin_printf("%d ", x);
      x = 10;
    };
  }
};

int main() {
  S s{ 5 };
  const auto l = s.foo();
  l();
  s.x = 15;
  l();
  __builtin_printf("%d\n", s.x);
}
```
https://godbolt.org/z/35qjr473K

Expected: an error that you cannot modify `x` within a `const` lambda.

Result: Prints `5 10 15`, demonstrating both that `l` has captured a copy of `S`, and also that (despite being a `const` object) it is nevertheless mutating its own state.

### LINKED ISSUE #84425: ICE inside nested lambdas, with reference captures, when the inner lambda is recursive using c++23s deducing this
ICE inside nested lambdas, when lambdas capture by reference, and specifically when the inner lambda both captures by reference and is recursive using c++23s deducing this
https://godbolt.org/z/vbcTjKcvY

### LINKED ISSUE #86054: [Clang] Crash when using deducing this and references in lambda captures
Compiling the following code using `clang -std=c++23` crashes the compiler. [Godbolt link](https://godbolt.org/z/9bEzeKr1a)
Both GCC and MSVC accept the code, so it should be valid code.
```c++
template<typename M>
struct unique_lock {
    unique_lock(M&) {}
};
int main() {
    struct mutex {} cursor_guard;
    [&cursor_guard](this auto self) { 
        unique_lock a(cursor_guard); 
    }();
}
```

```
Stack dump:
0.      Program arguments: /usr/bin/clang-18 -cc1 -triple x86_64-redhat-linux-gnu -emit-obj -mrelax-all -dumpdir a- -disable-free -clear-ast-before-backend -disable-llvm-verifier -discard-value-names -main-file-name test.cpp -mrelocation-model static -mframe-pointer=all -fmath-errno -ffp-contract=on -fno-rounding-math -mconstructor-aliases -funwind-tables=2 -target-cpu x86-64 -tune-cpu generic -debugger-tuning=gdb -fdebug-compilation-dir=/home/link1j/Repos/awning -fcoverage-compilation-dir=/home/link1j/Repos/awning -resource-dir /usr/bin/../lib/clang/18 -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14 -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/x86_64-redhat-linux -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/14/../../../../include/c++/14/backward -internal-isystem /usr/bin/../lib/clang/18/include -internal-isystem /usr/local/include -internal-isystem /usr/bin/../lib/gcc/x86_64-redhat-linux/14/../../../../x86_64-redhat-linux/include -internal-externc-isystem /include -internal-externc-isystem /usr/include -std=c++23 -fdeprecated-macro -ferror-limit 19 -fgnuc-version=4.2.1 -fno-implicit-modules -fskip-odr-check-in-gmf -fcxx-exceptions -fexceptions -fcolor-diagnostics -faddrsig -D__GCC_HAVE_DWARF2_CFI_ASM=1 -o /tmp/test-a127ed.o -x c++ ./test.cpp
1.      <eof> parser at end of file
2.      Per-file LLVM IR generation
3.      ./test.cpp:7:5: Generating code for declaration 'main()::(anonymous class)::operator()'
 #0 0x00007fb2fe00915a llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/lib64/libLLVM.so.18.1+0x60915a)
 #1 0x00007fb2fe006904 llvm::sys::RunSignalHandlers() (/lib64/libLLVM.so.18.1+0x606904)
 #2 0x00007fb2fe0099eb (/lib64/libLLVM.so.18.1+0x6099eb)
 #3 0x00007fb2fd453710 __restore_rt (/lib64/libc.so.6+0x40710)
 #4 0x00007fb305e3e735 clang::ASTContext::getTypeInfoImpl(clang::Type const*) const (/lib64/libclang-cpp.so.18.1+0x123e735)
 #5 0x00007fb305e3f5d4 clang::ASTContext::getTypeInfo(clang::Type const*) const (/lib64/libclang-cpp.so.18.1+0x123f5d4)
 #6 0x00007fb305e3e740 clang::ASTContext::getTypeInfoImpl(clang::Type const*) const (/lib64/libclang-cpp.so.18.1+0x123e740)
 #7 0x00007fb305e3f5d4 clang::ASTContext::getTypeInfo(clang::Type const*) const (/lib64/libclang-cpp.so.18.1+0x123f5d4)
 #8 0x00007fb305e3efd2 clang::ASTContext::getPreferredTypeAlign(clang::Type const*) const (/lib64/libclang-cpp.so.18.1+0x123efd2)
 #9 0x00007fb305e3dde1 clang::ASTContext::getDeclAlign(clang::Decl const*, bool) const (/lib64/libclang-cpp.so.18.1+0x123dde1)
#10 0x00007fb306f9147d clang::CodeGen::CodeGenFunction::EmitAutoVarAlloca(clang::VarDecl const&) (/lib64/libclang-cpp.so.18.1+0x239147d)
#11 0x00007fb306f8e14e clang::CodeGen::CodeGenFunction::EmitVarDecl(clang::VarDecl const&) (/lib64/libclang-cpp.so.18.1+0x238e14e)
#12 0x00007fb306f8dcf0 clang::CodeGen::CodeGenFunction::EmitDecl(clang::Decl const&) (/lib64/libclang-cpp.so.18.1+0x238dcf0)
#13 0x00007fb30710b60b clang::CodeGen::CodeGenFunction::EmitSimpleStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/lib64/libclang-cpp.so.18.1+0x250b60b)
#14 0x00007fb30710aab3 clang::CodeGen::CodeGenFunction::EmitStmt(clang::Stmt const*, llvm::ArrayRef<clang::Attr const*>) (/lib64/libclang-cpp.so.18.1+0x250aab3)
#15 0x00007fb307116a7c clang::CodeGen::CodeGenFunction::EmitCompoundStmtWithoutScope(clang::CompoundStmt const&, bool, clang::CodeGen::AggValueSlot) (/lib64/libclang-cpp.so.18.1+0x2516a7c)
#16 0x00007fb307173ca3 clang::CodeGen::CodeGenFunction::EmitFunctionBody(clang::Stmt const*) (/lib64/libclang-cpp.so.18.1+0x2573ca3)
#17 0x00007fb30717494c clang::CodeGen::CodeGenFunction::GenerateCode(clang::GlobalDecl, llvm::Function*, clang::CodeGen::CGFunctionInfo const&) (/lib64/libclang-cpp.so.18.1+0x257494c)
#18 0x00007fb30719632c clang::CodeGen::CodeGenModule::EmitGlobalFunctionDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/lib64/libclang-cpp.so.18.1+0x259632c)
#19 0x00007fb30718f966 clang::CodeGen::CodeGenModule::EmitGlobalDefinition(clang::GlobalDecl, llvm::GlobalValue*) (/lib64/libclang-cpp.so.18.1+0x258f966)
#20 0x00007fb307182683 clang::CodeGen::CodeGenModule::EmitDeferred() (/lib64/libclang-cpp.so.18.1+0x2582683)
#21 0x00007fb30718021e clang::CodeGen::CodeGenModule::Release() (/lib64/libclang-cpp.so.18.1+0x258021e)
#22 0x00007fb30722e5bc (/lib64/libclang-cpp.so.18.1+0x262e5bc)
#23 0x00007fb307164744 clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) (/lib64/libclang-cpp.so.18.1+0x2564744)
#24 0x00007fb305d540b6 clang::ParseAST(clang::Sema&, bool, bool) (/lib64/libclang-cpp.so.18.1+0x11540b6)
#25 0x00007fb307bf4879 clang::FrontendAction::Execute() (/lib64/libclang-cpp.so.18.1+0x2ff4879)
#26 0x00007fb307b6d544 clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) (/lib64/libclang-cpp.so.18.1+0x2f6d544)
#27 0x00007fb307c72132 clang::ExecuteCompilerInvocation(clang::CompilerInstance*) (/lib64/libclang-cpp.so.18.1+0x3072132)
#28 0x0000000000214c42 cc1_main(llvm::ArrayRef<char const*>, char const*, void*) (/usr/bin/clang-18+0x214c42)
#29 0x0000000000211915 (/usr/bin/clang-18+0x211915)
#30 0x0000000000210a74 clang_main(int, char**, llvm::ToolContext const&) (/usr/bin/clang-18+0x210a74)
#31 0x000000000021ffba main (/usr/bin/clang-18+0x21ffba)
#32 0x00007fb2fd43d088 __libc_start_call_main (/lib64/libc.so.6+0x2a088)
#33 0x00007fb2fd43d14b __libc_start_main@GLIBC_2.2.5 (/lib64/libc.so.6+0x2a14b)
#34 0x000000000020e335 _start (/usr/bin/clang-18+0x20e335)
```

### LINKED ISSUE #86398: [Clang] Deducing this Lambda ignores assignment rules for captured references
When using C++23 deducing this, captured references are assignable to anything.
The following code compiles with `clang -std=c++23`, when it clearly shouldn't. [Godbolt](https://godbolt.org/z/7TMoPK6an)
```c++
struct function {};
int main() {
    function list;
    [&list](this auto self) {
        list = self;
    }();
}
```
It even works with types that are not assignable. [Godbolt](https://godbolt.org/z/scazq7sfo)
```c++
struct function {
    function& operator=(function const&) = delete;
};
int main() {
    function list;
    [&list](this auto self) {
        list = self;
    }();
}
```
And even it doesn't even need `self` as part of the assignment expression. [Godbolt](https://godbolt.org/z/8jxs4Pxbb)
```c++
struct function {
    function& operator=(function const&) = delete;
};
int main() {
    function list;
    [&list](this auto self) {
        list = function{};
    }();
}
```

### LINKED ISSUE #86399: [Clang] Deducing this Lambda does not generate all the needed function calls
Found when reporting #86398, so it may be related to it.
But with the following valid code, at all optimization levels, the following code does not generate correctly.
```c++
volatile int a = 0;
struct function {
    function& operator=(function const&) {
        a = 1;
        return *this;
    }
};
int main() {
    function list;
    [&list](this auto self) {
        list = function{};
    }();
}
```Clang does not generate a call to `function::operator=`, and therefor does not set `a` to 1.
Both GCC and MSVC generate the code correctly.
[Godbolt](https://godbolt.org/z/9q5zYP9Ea)

### PR DESCRIPTION
**Pull request by Sirraide**
In short, dependence of captures in lambdas with an explicit object parameter is all kinds of broken at the moment. [[temp.dep.expr]](https://eel.is/c++draft/temp.dep.expr) states that
> An [id-expression](https://eel.is/c++draft/expr.prim.id.general#nt:id-expression) is type-dependent if [...] its terminal name is
>  - associated by name lookup with an entity captured by copy ([[expr.prim.lambda.capture]](https://eel.is/c++draft/expr.prim.lambda.capture)) in a [lambda-expression](https://eel.is/c++draft/expr.prim.lambda.general#nt:lambda-expression) that has an explicit object parameter whose type is dependent ([[dcl.fct]](https://eel.is/c++draft/dcl.fct))

In issue #84163, it was observed that, if the lambda object is `const` but the explicit object parameter is not `const` but is type-dependent, any by-value captures are not treated as `const`, even though they should be:
```c++
const auto l1 = [x](this auto&) { x = 42; };
l1(); // Should error because `x` ends up being `const`, but we don’t.
```

 This seems to be due to several compounding issues:
1. we’re treating by-reference captures as dependent rather than by-value captures;
2. tree transform doesn’t seem to check whether referring to such a by-value capture makes a DRE dependent;
3. when checking whether a DRE refers to an such a by-value capture, we only check the immediately enclosing lambda, and not any parent lambdas;
4. we also don’t check for implicit by-value captures;
5. attempting to determine whether a lambda has an explicit object parameter by checking the `LambdaScopeInfo`’s `ExplicitObjectParameter` doesn’t seem to work properly; I presume this is because this member refers to a `ParmVarDecl` that isn’t populated (yet) when we perform template instantiaion, which causes issues with nested lambdas that each have an explicit object parameter.

This pr should (eventually) fix all of these:
1. This is just due to a misplaced `!`, so that’s an easy fix.
2. This entails checking if the DRE is captured by value by a lambda with an explicit object parameter in `TreeTransform<Derived>::TransformDeclRefExpr`. That’s also an easy fix.
3. Currently, I’m simply iterating over all enclosing lambdas and checking if any of them capture the var decl that the DRE refers to by-value (explicitly or implicitly) rather than just looking at the parent lambda.
4. Check for implicit captures as well in 3.
5. Check for `isExplicitObjectMemberFunction()` on the lambda’s `CXXMethodDecl` instead.

This seems to have fixed all issues with captured variables; however, capturing `this` by value (and then accessing NSDMs) suffers from the same problem. My current approach for a fix is adding a `CapturedByCopyInLambdaWithExplicitObjectParameter` to `CXXThisExpr` and making `this` type-dependent, which is how this is tracked for DREs; this seems to have fixed the problem for `this` as well. If anyone has a better idea, feel free to let me know.

Issue #84425 also seems to involve capturing lambdas with explicit object parameters; this pr also seems to fix that issue.

This fixes #84163.

### CODE REVIEW

**Comment by Sirraide** [comment]
Also, just checked, #84425 apparently was a symptom of this as well, because that one’s also fixed now.

**Comment by Link1J** [comment]
Does this fix #86054, or is it a different bug?
It seems related to the other issues mentioned here.

**Comment by Sirraide** [comment]
> Does this fix #86054, or is it a different bug? It seems related to the other issues mentioned here.

I’ll check.

**Comment by Sirraide** [comment]
@Link1J The issue you linked does seem to be another symptom of the underlying problem here, yeah. It’s also not technically a duplicate, so I’ve left it open and marked it as fixed by this pr.

**Comment by Sirraide** [comment]
@AaronBallman ping

**Review by erichkeane — APPROVED** [review]
This seems sensible to me.  Please give @cor3ntin a few days to review, after which, feel free to commit.

**Comment by Sirraide** [comment]
It’s been about week, so I’m going to merge this now.

**Comment by jsji** [comment]
https://godbolt.org/z/WTTKfG1ha Looks like this is causing some assert failures. @Sirraide 
Thanks @jyu2-git for helping identifying the commit.

**Comment by Sirraide** [comment]
> https://godbolt.org/z/WTTKfG1ha Looks like this is causing some assert failures. @Sirraide Thanks @jyu2-git for helping identifying the commit.

I think I might know what’s going on here: We probably have an `AttributedType` or some other form of sugar here; I’ll see if I can fix it and if it takes too long I’ll revert this and reapply it later.

**Comment by Sirraide** [comment]
Looks like that was the problem; I’ll open a pr to fix this.

**Comment by Sirraide** [comment]
#88428

**Comment by jsji** [comment]
Thank you @Sirraide for the quick fix.

**Pull request merged**
