### PR TITLE
[win/asan] GetInstructionSize: Make `F6 C1 XX` a generic entry.

### PR DESCRIPTION
**Pull request by bernhardu**

### CODE REVIEW

**Comment by bernhardu** [comment]
v2:
- adjust for format requirements.

**Comment by bernhardu** [comment]
v3:
- Add test line.

CC: @zmodem

**Review by zmodem — APPROVED** [review]
lgtm

Would you like me to hit the "merge" button?

**Comment by bernhardu** [comment]
> Would you like me to hit the "merge" button?

Thanks for reviewing, if there are no more concerns about the change, yes, please.

**Pull request merged**
