### PR TITLE
[DebugInfo][LoopUnroll] Preserve DebugLocs on optimized cond branches

### PR DESCRIPTION
**Pull request by SLTozer**
This patch fixes a simple error where as part of loop unrolling we optimize conditional loop-exiting branches into unconditional branches when we know that they will or won't exit the loop, but does not propagate the source location of the original branch to the new one.

Found using https://github.com/llvm/llvm-project/pull/107279.

### CODE REVIEW

**Review by jryans — APPROVED** [review]
Looks good to me, thanks! 😄 

Did you discover this issue using your recent location debugging features...? If so, perhaps a label or comment in the PR would allow tracking bugs found via that work. Just a suggestion, feel free to ignore.

**Comment by SLTozer** [comment]
> Did you discover this issue using your recent location debugging features...? If so, perhaps a label or comment in the PR would allow tracking bugs found via that work. Just a suggestion, feel free to ignore.

Yes, do you have any suggestions for how to unobtrusively make the set of PRs more searchable?

**Comment by dwblaikie** [comment]
> > Did you discover this issue using your recent location debugging features...? If so, perhaps a label or comment in the PR would allow tracking bugs found via that work. Just a suggestion, feel free to ignore.
> 
> Yes, do you have any suggestions for how to unobtrusively make the set of PRs more searchable?

if you've got a PR or issue for the overarching thing, you can probably just mention that by number with #XXXX in each of these fixes to link back to the main thing - not the /most/ searchable thing (I don't know how to quickly then make a list of all the things that reference an issue) but at least they will be available in one page (the backlinks will create updates/be noted on the main issue - just not in a neat and tidy list, but in part of the update stream of comments, etc)

**Review by adrian-prantl — APPROVED** [review]

**Comment by jryans** [comment]
> if you've got a PR or issue for the overarching thing, you can probably just mention that by number with #XXXX in each of these fixes to link back to the main thing

Yeah, either mentioning some phrase (e.g. "DebugLoc coverage tracking") that you include in the description of all related PRs or linking to some top-level PR / issue should work. You can then search all PRs for "DebugLoc coverage" or "#XXXX" to produce a list.

**Pull request merged**
