### PR TITLE
[SROA] Unfold gep of index phi (round 2)

### LINKED ISSUE #278: Update diff February 28th 2024, 7:16:30 pm
from: https://github.com/llvm/llvm-project/commit/6101cf3164d77cfa4e2df75bf5262da9a2fb3d0a
to: https://github.com/llvm/llvm-project/commit/9c7cde64e6556f8a04dc4a14cbfb2b277d5ab4d9
commit: 3d4bdd550e66ba66886f7662ff92498985d6f3d9

qemu/original/fpu_softfloat.c.ll fail
## Change Logs
from 6101cf3164d77cfa4e2df75bf5262da9a2fb3d0a to 9c7cde64e6556f8a04dc4a14cbfb2b277d5ab4d9

[9c7cde64e6556f8a04dc4a14cbfb2b277d5ab4d9](https://github.com/llvm/llvm-project/commit/9c7cde64e6556f8a04dc4a14cbfb2b277d5ab4d9) Fix the lowering of `arith.truncf : f32 to bf16`. (#83180)
[2eb63982e88b9ed8336158d35884b1a1d04a0f78](https://github.com/llvm/llvm-project/commit/2eb63982e88b9ed8336158d35884b1a1d04a0f78) [SROA] Unfold gep of index phi (#83087)
[782147e82ab3e2d0e22f729ea4e54eeed7b3cb96](https://github.com/llvm/llvm-project/commit/782147e82ab3e2d0e22f729ea4e54eeed7b3cb96) [CMake][LIT] Add option to run lit testsuites in parallel (#82899)
[b4bc19e2e6b7d0de9cb5f0578269085a76e99d3f](https://github.com/llvm/llvm-project/commit/b4bc19e2e6b7d0de9cb5f0578269085a76e99d3f) [X86] Add tests showing failure to demand only the sign bit of a sitofp/uitofp node
[6244dfef5cd45f1395c66abbe061c6a7eb002676](https://github.com/llvm/llvm-project/commit/6244dfef5cd45f1395c66abbe061c6a7eb002676) llvm-dwarfdump --verify aggregated output to JSON file (#81762)
[baf6725b38491222f40a3c40bd27e57b0dd7f1f9](https://github.com/llvm/llvm-project/commit/baf6725b38491222f40a3c40bd27e57b0dd7f1f9) [flang][runtime] Support NORM2 for REAL(16) with FortranFloat128Math lib. (#83219)
[c1b8c6cf41df4a148e7a89c3a3c7e8049b0a47af](https://github.com/llvm/llvm-project/commit/c1b8c6cf41df4a148e7a89c3a3c7e8049b0a47af) [mlir][vector][print] do not append newline to printing pure strings (#83213)
[1c211bc76e8b6a3261c62e5b6c2b75b7b90386b0](https://github.com/llvm/llvm-project/commit/1c211bc76e8b6a3261c62e5b6c2b75b7b90386b0) [LV] Remove unused configuration option (#82955)

### PR DESCRIPTION
**Pull request by aeubanks**
If a gep has only one phi as one of its operands and the remaining indexes are constant, we can unfold `gep ptr, (phi idx1, idx2)` to `phi ((gep ptr, idx1), (gep ptr, idx2))`.

Take care not to unfold recursive phis.

Followup to #80983.

This was initially was #83087. Initial PR did not handle allocas in entry block that weren't at the beginning of the function, causing GEPs to be inserted after the first chunk of allocas but potentially before an alloca not at the beginning. Insert GEPs at the end of the entry block instead since constants/arguments/static allocas can all be used there.

### CODE REVIEW

**Review by Artem-B — APPROVED** [review]

**Comment by Artem-B** [comment]
Q: why not put those GEPs into appropriate incoming basic blocks. That would be a smaller-scope unfolding. I suspect those geps will be sunk into appropriate basic blocks, but it may be better if we don't have to do that.

**Comment by aeubanks** [comment]
> Q: why not put those GEPs into appropriate incoming basic blocks. That would be a smaller-scope unfolding. I suspect those geps will be sunk into appropriate basic blocks, but it may be better if we don't have to do that.

It doesn't really matter where the GEP is, later optimizations will place them wherever optimal.

If we want to support this unfolding for GEPs on top of allocas/constants/args, it's trickier
```
bb1:
bb2:
bb3:
  %i = phi [ 4, %bb1 ], [ 8, %bb2 ]
  %g1 = gep ...
  %g2 = gep %g1, %i
```
can't become
```
bb1:
  %g_bb1 = gep %g1, 4
bb2:
  %g_bb2 = gep %g1, 8
bb3:
  %g2 = phi [ %g_bb1, %bb1 ], [ %g_bb2, %bb2 ]
  %g1 = gep ...
```
since `%g1` is defined later than its uses. So I've been trying to keep the insertion point simple.

**Comment by Artem-B** [comment]
> It doesn't really matter where the GEP is, later optimizations will place them wherever optimal.

It does matter in practice. Later optimization pass may *eventually* place them wherever optimal, but that assumes there will be enough of those "later" passes. If we happened to be in SROA pass at the tail end of the compilation, that may not be the case. 

Anyways, I'm OK with the keep-it-simple approach.

**Comment by dtcxzyw** [comment]
Looks like this patch still breaks my benchmark.
See also https://github.com/dtcxzyw/llvm-opt-benchmark/issues/278.

I will provide a minimal reproducer.

**Comment by dtcxzyw** [comment]
```
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

%struct.FloatParts128 = type { i8, i8, i32, i64, i64 }

define { i64, i64 } @float128_div(ptr %pa, i8 %cond) {
entry:
  %pa1 = alloca %struct.FloatParts128, align 8
  br label %parts128_div.exit

if.end48.i:                                       ; No predecessors!
  switch i8 %cond, label %common.ret [
    i8 1, label %parts128_div.exit
    i8 0, label %parts128_div.exit
  ]

common.ret:                                       ; preds = %parts128_div.exit, %if.end48.i
  ret { i64, i64 } zeroinitializer

parts128_div.exit:                                ; preds = %if.end48.i, %if.end48.i, %entry
  %retval.i7.0 = phi ptr [ %pa, %if.end48.i ], [ %pa, %if.end48.i ], [ %pa1, %entry ]
  %frac_lo.i = getelementptr i8, ptr %retval.i7.0, i64 16
  %0 = load i64, ptr %frac_lo.i, align 8
  br label %common.ret
}

```

```
> bin/opt -passes=sroa reduced.ll -S

PHI node has multiple entries for the same basic block with different incoming values!
  %retval.i7.0.sroa.phi = phi ptr [ %retval.i7.0.sroa.gep, %if.end48.i ], [ %retval.i7.0.sroa.gep1, %if.end48.i ], [ %pa1.sroa.0, %entry ]
label %if.end48.i
  %retval.i7.0.sroa.gep = getelementptr i8, ptr %pa, i64 16
  %retval.i7.0.sroa.gep1 = getelementptr i8, ptr %pa, i64 16
LLVM ERROR: Broken module found, compilation aborted!
```

**Comment by aeubanks** [comment]
thanks for the ahead-of-time repro! pushed a commit to fix that

**Review by Artem-B — APPROVED** [review]

**Comment by wlei-llvm** [comment]
Hi, 
This breaks one of our assertion build:

```
Instruction does not dominate all uses!
  %3 = alloca i8, i64 %conv17169, align 16, !dbg !15551
  %__cs.0.sroa.gep = getelementptr inbounds i8, ptr %3, i64 1, !dbg !15533
Instruction does not dominate all uses!
  %4 = alloca i8, i64 %conv17, align 16, !dbg !15551
  %__cs.0.sroa.gep173 = getelementptr inbounds i8, ptr %4, i64 1, !dbg !15533
Instruction does not dominate all uses!
  %3 = alloca i8, i64 %conv17169, align 16, !dbg !15551
  %__cs.0.sroa.gep177 = getelementptr inbounds i8, ptr %3, i64 2, !dbg !15533
Instruction does not dominate all uses!
  %4 = alloca i8, i64 %conv17, align 16, !dbg !15551
  %__cs.0.sroa.gep178 = getelementptr inbounds i8, ptr %4, i64 2, !dbg !15533
Instruction does not dominate all uses!
  %3 = alloca i8, i64 %conv17145, align 16, !dbg !15820
  %__cs.0.sroa.gep = getelementptr inbounds i8, ptr %3, i64 1, !dbg !15803
Instruction does not dominate all uses!
  %4 = alloca i8, i64 %conv17, align 16, !dbg !15820
  %__cs.0.sroa.gep149 = getelementptr inbounds i8, ptr %4, i64 1, !dbg !15803
Instruction does not dominate all uses!
  %3 = alloca i8, i64 %conv17145, align 16, !dbg !15820
  %__cs.0.sroa.gep153 = getelementptr inbounds i8, ptr %3, i64 2, !dbg !15803
Instruction does not dominate all uses!
  %4 = alloca i8, i64 %conv17, align 16, !dbg !15820
  %__cs.0.sroa.gep154 = getelementptr inbounds i8, ptr %4, i64 2, !dbg !15803
fatal error: error in backend: Broken module found, compilation aborted!
```
Please take a look, thanks! I will try to get a reduced reproducer but posted just in case something obvious to fix.

**Comment by aeubanks** [comment]
sorry for the crash, should be fixed in eae4f56cb40c5db0ec2c4e967107cba2473246f1

**Comment by wlei-llvm** [comment]
> sorry for the crash, should be fixed in [eae4f56](https://github.com/llvm/llvm-project/commit/eae4f56cb40c5db0ec2c4e967107cba2473246f1)

Confirmed there is no crash with this, thanks!

**Pull request merged**
