### PR TITLE
[libc] Give more functions restrict qualifiers (NFC)

### PR DESCRIPTION
**Pull request by AZero13**
strsep, strtok_r, strlcpy, and strlcat take restricted pointers as parameters.
Add the restrict qualifiers to them.

Sources:
https://man7.org/linux/man-pages/man3/strsep.3.html
https://man7.org/linux/man-pages/man3/strtok_r.3.html
https://man.freebsd.org/cgi/man.cgi?strlcpy

### CODE REVIEW

**Review by lntue — COMMENTED** [review]
LGTM for the libc part.
Thanks for adding the missing qualifiers!  They were specified in our own generated header but not in the implementation: https://github.com/llvm/llvm-project/blob/main/libc/spec/bsd_ext.td#L21

**Comment by AtariDreams** [comment]
@lntue Do you think this PR is acceptable?

**Review by lntue — APPROVED** [review]

**Comment by jhuber6** [comment]
LLVM changes look unrelated, it was originally copied from OpenBSD it seems. But it's not a major issue.

**Comment by AtariDreams** [comment]
> LLVM changes look unrelated, it was originally copied from OpenBSD it seems. But it's not a major issue.

I did that for consistency. If needed I could split into other PRs

**Comment by jhuber6** [comment]
> > LLVM changes look unrelated, it was originally copied from OpenBSD it seems. But it's not a major issue.
> 
> FWIW I opened a few PRs in FreeBSD regarding this.

Yeah, go ahead and move that portion there so the people who know more about LLVM's regex can look at it compared to the `libc` team.

**Comment by AtariDreams** [comment]
@jhuber6 Oh you meant the formatting. clang-format did that for some reason. I did not edit the body at all.

**Comment by AtariDreams** [comment]
@jhuber6 Alright I removed the llvm/Support changes for the sake of the PR

**Review by jhuber6 — APPROVED** [review]
Thanks.

**Comment by AtariDreams** [comment]
Ready!

**Comment by AtariDreams** [comment]
Ready!

**Pull request merged**
