### PR TITLE
[AArch64] Enable FEAT_SVE2p1 by default for Armv9.4-A and later

### PR DESCRIPTION
**Pull request by jthackray**
The ArmARM says:
```
    "In an Armv9.4 implementation, if FEAT_SVE2 is implemented,
     FEAT_SVE2p1 is implemented."
```
Since FEAT_SVE2 is already enabled for Armv9.0-A and later, then FEAT_SVE2p1 should also be enabled by default.

### CODE REVIEW

**Comment by jthackray** [comment]
Note that we already have this code downstream for AC6.24:
```
  [HasV8_9aOps, HasV9_3aOps, FeatureSVE2p1], // downstream diff
```
but for some reason, it never was upstreamed.

**Review by tommat01 — APPROVED** [review]
Makes sense to me.

**Comment by tmatheson-arm** [comment]
Actually this is being added as a mandatory dependency of 9.4, should it not be added as one of the default features instead?

**Comment by jthackray** [comment]
> Actually this is being added as a mandatory dependency of 9.4, should it not be added as one of the default features instead?

Good point. I'll amend.

**Review by paulwalker-arm — APPROVED** [review]

**Pull request merged**
