### PR TITLE
[libcxx] Set `_LIBCPP_HAS_CLOCK_GETTIME` for GPU targets

### PR DESCRIPTION
**Pull request by jhuber6**
Summary:
I am attempting to get the GPU to build and support libc++. One issue
I've encountered is that it will look for `timeval` unless this macro is
set. We can support `CLOCK_MONOTONIC` on the GPU fairly easily as we
have access to a fixed-frequency clock via `__builtin_readsteadycounter`
intrinsics with a known frequency. This also requires `CLOCK_REALTIME`
which we can't support, but provide anyway from the GPU `libc` to make
this happy. It will return an error so at least that will be obvious.

I may need a more consistent configuration for this in the future, maybe
I should put a common macro in a different common header that's just
`__GPU__`? I don't know where I would put such a thing however.

### CODE REVIEW

**Comment by philnik777** [comment]
> I may need a more consistent configuration for this in the future, maybe
> I should put a common macro in a different common header that's just
> `__GPU__`? I don't know where I would put such a thing however.

Do you expect a lot of places where we need special handling for GPUs? If that's the case, maybe adding a `_LIBCPP_TARGETING_GPU` to `__config` would be the right thing?

**Comment by jhuber6** [comment]
> > I may need a more consistent configuration for this in the future, maybe
> > I should put a common macro in a different common header that's just
> > `__GPU__`? I don't know where I would put such a thing however.
> 
> Do you expect a lot of places where we need special handling for GPUs? If that's the case, maybe adding a `_LIBCPP_TARGETING_GPU` to `__config` would be the right thing?

Yeah that would be reasonable, though I don't know of how many places need it *yet*. Maybe I should just keep this and refactor that later? Up to you.

**Comment by jhuber6** [comment]
Went with the config, definitely feel like it might be needed somewhere else so may as well.

**Comment by mordante** [comment]
In general we like to have a CI to validate the changes. These changes will fail for several tests so they need to be excluded from testing. Do you have plans to provide a CI. (This can be discussed further on Discord.)

**Comment by jhuber6** [comment]
> In general we like to have a CI to validate the changes. These changes will fail for several tests so they need to be excluded from testing. Do you have plans to provide a CI. (This can be discussed further on Discord.)

I don't know much about that myself, but it's difficult to set up a CI before I have a working build configuration, so I figured a new (mostly) NFC patches that get a working build would be a good start.

If https://github.com/llvm/llvm-project/pull/99259, https://github.com/llvm/llvm-project/pull/99243, https://github.com/llvm/llvm-project/pull/99287, and https://github.com/llvm/llvm-project/pull/99333 land I will be able to set up a working build which can then be added on top of the existing NVPTX / AMDGPU buildbots for `libc`.

Getting testing working would then be a separate issue. The problem is that it seems `llvm-lit` doesn't provide an easy way to "emulate" the binaries, but I plan on just doing what I do with the GPU `libc` target. That is described in https://libc.llvm.org/gpu/testing.html, TL;DR I have a program called `amdhsa-loader` and `crt1.o` that will allow us to treat the GPU like a regular target and execute a `main` function.

**Review by ldionne — CHANGES_REQUESTED** [review]
Looks like I reviewed those changes as part of #99259.

**Comment by jhuber6** [comment]
> Looks like I reviewed those changes as part of #99259.

Updated to remove the config, I think it's fair to check for this specifically because we do the same for Apple, Hurd, and OpenBSD.

**Review by ldionne — APPROVED** [review]
I am not a huge fan of these checks, but they are self-contained and only in the dylib. And there's obvious precedent for using the exact same approach. So LGTM.

**Pull request merged**
