### PR TITLE
[libc++] Refactor the Windows and MinGW implementation of the locale base API

### PR DESCRIPTION
**Pull request by ldionne**
This patch reimplements the locale base support for Windows flavors in a way that is more modules-friendly and without defining non-internal names.

Since this changes the name of some types and entry points in the built library, this is effectively an ABI break on Windows (which is acceptable since we don't promise ABI stability on that platform).

### CODE REVIEW

**Comment by mstorsjo** [comment]
> Since this changes the name of some types and entry points in the built library, this is effectively an ABI break on Windows (which is acceptable since we don't promise ABI stability on that platform).

I'd like to clarify/reiterate some nuances about ABI stability on Windows. While I can't claim that the libcxx project promises ABI stability there, there are two quite different cases:

In MSVC environments, we've flagged this a number of times before, making it clear that we do break the ABI occasionally, and this is accepted.

In MinGW environments (using the Itanium C++ ABI), there are a number of setups that do use older libc++ DLLs with newer builds, where ABI compatibility generally is desired - both around llvm-mingw, and within msys2. So far, we've had a number of minor ABI breaks, where such a break (if they happen to break a small minority of packages) has been accepted and tolerated. But I would request that this isn't treated as blanket permission to break the whole ABI just because there's no formal guarantees either; breaking the ABI in this environment _can_ cause grief to our users - proportional to the number of changed symbols and how frequently they are used of course.

CC @lazka @mati865

---

That said, I'm not sure how often these particular symbols really are referenced in practice; are they implicitly embedded in many cases, or are they only referenced if the user code explicitly uses locale things? In the latter case this is probably fine, in the former case, it will probably cause a lot of problems for msys2.

---

Separately; I see that this touches a MinGW configuration that we don't have CI coverage for - using MinGW with msvcrt.dll instead of UCRT. This configuration doesn't pass all tests (as msvcrt.dll is quite lacking in many ways), but I ship builds with this configuration in each release.

I can easily add CI coverage for this build configuration; 128 tests are failing in it, so it'll take a little while to get the tests running there, but we can easily add plain build testing of it at least.

**Comment by ldionne** [comment]
Thanks for chiming in.

> But I would request that this isn't treated as blanket permission to break the whole ABI

Ack. I am putting up the "cleanest" version of this patch which removes the old symbols that are not needed anymore. However, if backwards compatibility is required, we could embed these historically significant symbols into the shared library. There's a number of ways we can do that. We could use aliases if that's a thing on Windows, or we could simply define the old name in a separate `.cpp` file similar to what we're doing in `libcxx/src/legacy_pointer_safety.cpp` (but with a real implementation). I wanted to have a discussion before I started making this patch more complicated for ABI guarantees I wasn't sure mattered.

> are they implicitly embedded in many cases, or are they only referenced if the user code explicitly uses locale things

I do think that older binaries are going to have references to those symbols, so that means running the binary against a new version of the library would fail with undefined references.

**Comment by mstorsjo** [comment]
> > But I would request that this isn't treated as blanket permission to break the whole ABI
> 
> Ack. I am putting up the "cleanest" version of this patch which removes the old symbols that are not needed anymore. However, if backwards compatibility is required, we could embed these historically significant symbols into the shared library. There's a number of ways we can do that. We could use aliases if that's a thing on Windows, or we could simply define the old name in a separate `.cpp` file similar to what we're doing in `libcxx/src/legacy_pointer_safety.cpp` (but with a real implementation). I wanted to have a discussion before I started making this patch more complicated for ABI guarantees I wasn't sure mattered.

Ok, thanks! Sure, going about it this way seems reasonable.

When grepping around a bit, I realized that we have the frozen C++03 headers which also reference a number of symbols - so we probably need to keep providing what those need as well.

> > are they implicitly embedded in many cases, or are they only referenced if the user code explicitly uses locale things
> 
> I do think that older binaries are going to have references to those symbols, so that means running the binary against a new version of the library would fail with undefined references.

Right... I guess we'd need to test and see how many of current msys2 binaries would be broken by the change as is (once it's in a otherwise working shape) to figure out how much we'd practically want to keep providing...

**Comment by mstorsjo** [comment]
See #115783 for additional CI coverage which can be valuable, as you're touching a couple of conditional lines that currently lack build test coverage upstream.

**Comment by lazka** [comment]
> CC @lazka @mati865

I don't mind rebuilds in general (for libc++ it seems to be ~ 620 packages), but I'm not sure what a good llvm rebootstrap strategy is - I don't think we had something like this before.

**Comment by mstorsjo** [comment]
> > CC @lazka @mati865
> 
> I don't mind rebuilds in general (for libc++ it seems to be ~ 620 packages), but I'm not sure what a good llvm rebootstrap strategy is - I don't think we had something like this before.

Yeah, and even then, such a change would be quite disruptive for users; they would need to hard upgrade every package that uses libc++ in one step, otherwise they'd have broken executables all around.

So I think keeping backwards compat symbols around for at least a major version or two, would be valuable in any case.

(I haven't yet studied what the impact on the referenced symbols is from this change, for something like clang/llvm built on top of libc++ on mingw.)

**Comment by lazka** [comment]
> Yeah, and even then, such a change would be quite disruptive for users; they would need to hard upgrade every package that uses libc++ in one step, otherwise they'd have broken executables all around.

Last week we rebuilt 940 packages for Python 3.12, so that's not too special at least, though Python packages tend to be smaller.

> So I think keeping backwards compat symbols around for at least a major version or two, would be valuable in any case.

That would certainly be appreciated, if that's possible.

**Comment by mati865** [comment]
> I'm not sure what a good llvm rebootstrap strategy

Ideally not having to do that 😉 
Still, it'd be manageable if necessary by reverting the change and creating a temporary release that is linked statically to libc++, that would be the easy way. In the worst case we could fix Cygwin host (or maybe it already works these days?) and start over again.

**Comment by ldionne** [comment]
@mstorsjo This patch seems to be in a functional shape now. What would be the level of ABI compatibility you think we need to go for?

The minimum I can see would be providing the old symbols in a `.cpp` file to avoid changing the set of exported symbols. I assume back-deployment is not required, so we don't need to also do complicated stuff based on the deployment target to allow back-deploying?

**Comment by mstorsjo** [comment]
> @mstorsjo This patch seems to be in a functional shape now. What would be the level of ABI compatibility you think we need to go for?

Thanks! Let me take it for a spin now that it works as intended, I'll get back to you with a feel of how big a break this would seem to be in practice.

> The minimum I can see would be providing the old symbols in a `.cpp` file to avoid changing the set of exported symbols. I assume back-deployment is not required, so we don't need to also do complicated stuff based on the deployment target to allow back-deploying?

That sounds like what I think would be enough. Backdeployment is indeed not required in this setup. Thanks!

But before you spend more time on that, let me first try this out. (It might be a few days, I'm a little backlogged at the moment.)

**Comment by ldionne** [comment]
@mstorsjo Did you have any luck trying out this patch?

**Comment by mstorsjo** [comment]
Ok, now I've had a look at this.

This PR produces the following diff in the list of exported symbols from the libc++ DLL:
```
@@ -1,9 +1,3 @@
-  Name: _Z10asprintf_lPPc8locale_tPKcz
-  Name: _Z10snprintf_lPcy8locale_tPKcz
-  Name: _Z10strftime_lPcyPKcPK2tm8locale_t
-  Name: _Z11vasprintf_lPPc8locale_tPKcS_
-  Name: _Z8strtof_lPKcPPc8locale_t
-  Name: _Z9strtold_lPKcPPc8locale_t
   Name: _ZN10__cxxabiv116__enum_type_infoD0Ev
   Name: _ZN10__cxxabiv116__enum_type_infoD1Ev
   Name: _ZN10__cxxabiv116__enum_type_infoD2Ev
@@ -1831,6 +1825,22 @@
   Name: _ZNSt3__17promiseIvEC2Ev
   Name: _ZNSt3__17promiseIvED1Ev
   Name: _ZNSt3__17promiseIvED2Ev
+  Name: _ZNSt3__18__locale10__asprintfEPPcNS0_10__locale_tEPKcz
+  Name: _ZNSt3__18__locale10__snprintfEPcyNS0_10__locale_tEPKcz
+  Name: _ZNSt3__18__locale10__strftimeEPcyPKcPK2tmNS0_10__locale_tE
+  Name: _ZNSt3__18__locale11__mbsrtowcsEPwPPKcyPiNS0_10__locale_tE
+  Name: _ZNSt3__18__locale11__newlocaleEiPKcNS0_10__locale_tE
+  Name: _ZNSt3__18__locale12__localeconvERNS0_10__locale_tE
+  Name: _ZNSt3__18__locale12__mb_len_maxENS0_10__locale_tE
+  Name: _ZNSt3__18__locale12__mbsnrtowcsEPwPPKcyyPiNS0_10__locale_tE
+  Name: _ZNSt3__18__locale12__wcsnrtombsEPcPPKwyyPiNS0_10__locale_tE
+  Name: _ZNSt3__18__locale7__btowcEiNS0_10__locale_tE
+  Name: _ZNSt3__18__locale7__wctobEtNS0_10__locale_tE
+  Name: _ZNSt3__18__locale8__mbrlenEPKcyPiNS0_10__locale_tE
+  Name: _ZNSt3__18__locale8__strtofEPKcPPcNS0_10__locale_tE
+  Name: _ZNSt3__18__locale9__mbrtowcEPwPKcyPiNS0_10__locale_tE
+  Name: _ZNSt3__18__locale9__strtoldEPKcPPcNS0_10__locale_tE
+  Name: _ZNSt3__18__locale9__wcrtombEPcwPiNS0_10__locale_tE
   Name: _ZNSt3__18__rs_getEv
   Name: _ZNSt3__18__sp_mut4lockEv
   Name: _ZNSt3__18__sp_mut6unlockEv
```

So a handful of `locale_t` specific functions are removed and others appear.

A regular build of LLVM/Clang on top of this libc++ doesn't seem to reference any of those symbols, so we're not breaking the base toolchain if doing this change. That's good. :-)

I had a look in an install of msys2/clang64 to see how many packages/executables would be affected. I don't have a whole lot of packages installed so it's not a very thorough investigation, but if @lazka or @mati865 happen to have more packages installed locally maybe they can try too.

In `/clang64/bin` I ran `ls *.exe *.dll | wc -l` and noted that I happen to have 540 executables/DLLs lying around. Out of those, 287 seem to actually be referencing libc++.dll: `grep libc++.dll *.exe *.dll | wc -l`

How many of them would be bothered by this change?

```
for i in $(grep libc++.dll *.exe *.dll | grep "Binary file" | awk '{print $3}'); do if llvm-readobj --coff-imports $i | grep -q locale_t; then echo $i; fi; done
```
In my case, I only get one single hit, `libboost_locale-mt.dll`.

So if this is the scale of the breakage, perhaps it's not worth the effort to keep providing the old symbols for backwards compatibility. But let's wait for more numbers from the msys2 maintainers before concluding this.

**Comment by ldionne** [comment]
Thanks to you both for running those experiments! Are you fine with me merging this PR then?

**Comment by ldionne** [comment]
After thinking about this a bit more, I think your results are not very surprising. I think these symbols are mostly used from within the libc++ dylib, and so perhaps it's not even necessary to export (most of) them in the first place. We could explore that in future patches once we at least have a clear "theoretical" ABI boundary.

**Comment by mstorsjo** [comment]
> After thinking about this a bit more, I think your results are not very surprising. I think these symbols are mostly used from within the libc++ dylib, and so perhaps it's not even necessary to export (most of) them in the first place. We could explore that in future patches once we at least have a clear "theoretical" ABI boundary within the libc++ code itself.

Yes, I kinda am getting that feeling as well. (Plus very few things explicitly use locales at all - at most it's implicitly passed somewhere.)

> Thanks to you both for running those experiments! Are you fine with me merging this PR then?

Yes, I'm ok with that - let's not create unnecessary complexity here.

**Comment by mstorsjo** [comment]
Btw, one aspect that did come to mind; we have the frozen C++03 header copies - which will expect a different ABI towards the precompiled bits of libcxx. We don't currently use the frozen C++03 headers quite yet (AFAIK?), but once we do, I guess this would crop up whenever trying to run tests in C++03 mode on Windows. (We don't test all standards modes on all OSes currently though.) So I guess we would need to do this kind of maintainance on those otherwise supposedly frozen headers?

**Comment by philnik777** [comment]
> Btw, one aspect that did come to mind; we have the frozen C++03 header copies - which will expect a different ABI towards the precompiled bits of libcxx. We don't currently use the frozen C++03 headers quite yet (AFAIK?), but once we do, I guess this would crop up whenever trying to run tests in C++03 mode on Windows. (We don't test all standards modes on all OSes currently though.) So I guess we would need to do this kind of maintainance on those otherwise supposedly frozen headers?

Yes, this is one place where we'd probably have to change the C++03 headers. They should be frozen as much as that's maintainable, so I don't think that goes against the idea.

**Pull request merged**
