### PR TITLE
[libc][NFC] Split 'builtin_wrapper' into 'bit' and 'math_extras'

### PR DESCRIPTION
**Pull request by gchatelet**
`builtin_wrapper.h` contains mostly math related things and is not really about
builtins anymore. Renaming it to `math_extras.h` to mimic what is done in LLVM.

`math_extras.h` will receive all small functions related to math and bit manip.

### CODE REVIEW

**Comment by gchatelet** [comment]
FYI I intend to add the following mask functions from llvm/Support/MathExtras.h
https://github.com/llvm/llvm-project/blob/6088e9cdba902f78d88bbd3e7ff21c6ddb8fcf98/llvm/include/llvm/Support/MathExtras.h#L65-L88

**Comment by gchatelet** [comment]
Actually, maybe we should split this header into `math_support` and `bit_support`. WDYT?
`clz` functions are actually in "include/llvm/ADT/bit.h"
https://github.com/llvm/llvm-project/blob/f85e7ab03534842d57d8fd385617a8d56b31bf09/llvm/include/llvm/ADT/bit.h#L280-L284

**Comment by nickdesaulniers** [comment]
> and bit_support. WDYT? clz functions are actually in "include/llvm/ADT/bit.h"

Is there value in matching the header name from LLVM? i.e. "bit.h" rather than "bit_support.h"?

**Comment by gchatelet** [comment]
> > and bit_support. WDYT? clz functions are actually in "include/llvm/ADT/bit.h"
> 
> Is there value in matching the header name from LLVM? i.e. "bit.h" rather than "bit_support.h"?

We're already in the `__support` folder so I guess "bit.h" would do :)

**Comment by gchatelet** [comment]
Split `builtin_wrapper.h` into `bit.h` and `math_extras.h` to mimic LLVM `llvm/ADT/Bit.h` and `llvm/Support/MathExtras.h`.
Also added unittest place holders.

**Comment by gchatelet** [comment]
Closed in favor of https://github.com/llvm/llvm-project/pull/73113

**Pull request closed without merging**
