### PR TITLE
Revert "[libc] Make GPU `libm` use generic implementations"

### PR DESCRIPTION
**Pull request by joker-eph**
Reverts llvm/llvm-project#98014

buildbot is broken.

### CODE REVIEW

**Comment by jhuber6** [comment]
The failure shows `compiler-rt` failing due to an LLVM assertion. How is that related to a GPU build of the `libc` project?

**Comment by jhuber6** [comment]
The bot is still broken after this revert, can you please reinstate it?

**Comment by joker-eph** [comment]
Clang started crashing building libm, and this PR touched libm, I didn’t look further.

now the revert didn’t fix the pre merge build :(
The build is failing consistently since, so something is fishy: I am on my phone and can’t look the commit history conveniently to investigate further just now…

**Comment by jhuber6** [comment]
I actually got similar failures while attempting to build the x64 version of `libc` after landing that patch. I tried clearing the cache to make sure that nothing was weird, so I just assumed someone broke something else in LLVM and I disabled my x64 build temporarily.

**Comment by joker-eph** [comment]
The build started failing consistently with this PR but some caching effects are possible, or maybe something changed on the bot itself: @lnihlen do you know if anything changed on the bot today?

**Comment by jhuber6** [comment]
Would be very unlikely that this build caused it, since  there's one two bots that touch any of this CMake. Weirder things have happened before though.

**Comment by jhuber6** [comment]
Seems the bot is green, any clue what ended up fixing it? I'd like to be able to have this relanded.

**Comment by jhuber6** [comment]
Reapplied in d358151a4fe94c72186d58f8903f044a116d0fa8 after testing it locally again.

**Pull request merged**
