### PR TITLE
[RISCV] Remove machine-csr-names-invalid.s. NFC

### PR DESCRIPTION
**Pull request by topperc**
This appears to be redundant with rv32-only-csr-names.s which tests the same registers and many more.

### CODE REVIEW

**Review by dtcxzyw — APPROVED** [review]
LG

**Comment by wangpc-pp** [comment]
Maybe we should rename `rv32-only-csr-names.s ` to a suitable name?

**Comment by topperc** [comment]
> Maybe we should rename `rv32-only-csr-names.s ` to a suitable name?

Do you have a suggestion?

**Comment by wangpc-pp** [comment]
> > Maybe we should rename `rv32-only-csr-names.s ` to a suitable name?
> 
> Do you have a suggestion?

Maybe `machine-csr-names-invalid.s`? 😂

**Comment by topperc** [comment]
> > > Maybe we should rename `rv32-only-csr-names.s ` to a suitable name?
> > 
> > 
> > Do you have a suggestion?
> 
> Maybe `machine-csr-names-invalid.s`? 😂

It only tests CSR names that are valid for rv32 and invalid for rv64. So rv64-machine-csr-names-invalid.s?

**Comment by wangpc-pp** [comment]
> > > > Maybe we should rename `rv32-only-csr-names.s ` to a suitable name?
> > > 
> > > 
> > > Do you have a suggestion?
> > 
> > 
> > Maybe `machine-csr-names-invalid.s`? 😂
> 
> It only tests CSR names that are valid for rv32 and invalid for rv64. So rv64-machine-csr-names-invalid.s?

Never mind. Then I think its original name is OK as well. 😂

**Review by wangpc-pp — APPROVED** [review]

**Pull request merged**
