### PR TITLE
[AArch64][SVE] Handle consecutive Predicates in CC_AArch64_Custom_Block

### PR DESCRIPTION
**Pull request by zhaoshiz**
For 2d masks as function arguments, even in [1 x <vscale x 4 x i1>] type, they're flagged as InConsecutiveRegs. This fix checks for mask types and allocate them to P registers.

### CODE REVIEW

**Review by c-rhodes — APPROVED** [review]
Thanks for the patch.

I was wondering where this code kicks in for Z regs as I couldn't see any tests with arrays, but it's used for tuples of scalable vectors like in `@foo1`  in `llvm/test/CodeGen/AArch64/sve-calling-convention-mixed.ll`.

LGTM cheers, but I'll add another reviewer since I don't work on the backend much at the moment. So please wait before landing.

**Comment by zhaoshiz** [comment]
> Thanks for the patch.
> 
> I was wondering where this code kicks in for Z regs as I couldn't see any tests with arrays, but it's used for tuples of scalable vectors like in `@foo1` in `llvm/test/CodeGen/AArch64/sve-calling-convention-mixed.ll`.
> 
> LGTM cheers, but I'll add another reviewer since I don't work on the backend much at the moment. So please wait before landing.

Thanks for reviewing. I'm working on scalable vectorizing linalg.reduce in MLIR and run into this case when I try to generate SVE instructions with mask types like <2x[4]xi1>. Without this fix, a mask of such type is assigned to Z registers and the backend crashes later.

**Review by sdesmalen-arm — CHANGES_REQUESTED** [review]
On lines 58-68, there is some code that suggests the calling convention has  additional requirements that need to be taken into account:

```    // The calling convention for passing SVE tuples states that in the event
    // we cannot allocate enough registers for the tuple we should still leave
    // any remaining registers unallocated. However, when we call the
    // CCAssignFn again we want it to behave as if all remaining registers are
    // allocated. This will force the code to pass the tuple indirectly in
    // accordance with the PCS.
    bool RegsAllocated[8];
    for (int I = 0; I < 8; I++) {
      RegsAllocated[I] = State.isAllocated(ZRegList[I]);
      State.AllocateReg(ZRegList[I]);
    }
```

This applies to both Z registers and P registers. I believe this corresponds to 
[AAPCS (parameter passing)](https://github.com/ARM-software/abi-aa/blob/main/aapcs64/aapcs64.rst#parameter-passing) Step `C.7` and `C.8`.

Could you also add some tests for this?

**Comment by zhaoshiz** [comment]
> On lines 58-68, there is some code that suggests the calling convention has additional requirements that need to be taken into account:
> 
> ```
>     // we cannot allocate enough registers for the tuple we should still leave
>     // any remaining registers unallocated. However, when we call the
>     // CCAssignFn again we want it to behave as if all remaining registers are
>     // allocated. This will force the code to pass the tuple indirectly in
>     // accordance with the PCS.
>     bool RegsAllocated[8];
>     for (int I = 0; I < 8; I++) {
>       RegsAllocated[I] = State.isAllocated(ZRegList[I]);
>       State.AllocateReg(ZRegList[I]);
>     }
> ```
> 
> This applies to both Z registers and P registers. I believe this corresponds to [AAPCS (parameter passing)](https://github.com/ARM-software/abi-aa/blob/main/aapcs64/aapcs64.rst#parameter-passing) Step `C.7` and `C.8`.
> 
> Could you also add some tests for this?

I've added similar code to handle P registers in the case a predicate argument is passed indirectly through the stack.
But I ran into some issues when changing values of M and N in predicate types [M x <vsacale x N x i1>]:

1. when M=1, the argument has both flags `InConsectiveRegs` and `InConsectutiveRegsLast` set, which will trigger assertions: for callee or caller at:
https://github.com/llvm/llvm-project/blob/3dcd604eb1d6612fda667793dbb52c5dfaa5fc4f/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp#L7217
https://github.com/llvm/llvm-project/blob/3dcd604eb1d6612fda667793dbb52c5dfaa5fc4f/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp#L8214
    Is checking (ValueVTs.size() > 1) before return true from AArch64TargetLowering::functionArgumentNeedsConsecutiveRegisters(),  a good fixe or more needs to be done to handle M=1? 
    https://github.com/llvm/llvm-project/blob/3dcd604eb1d6612fda667793dbb52c5dfaa5fc4f/llvm/lib/Target/AArch64/AArch64ISelLowering.cpp#L26132

3. when N is not 16, DAGSelection fails with cannot select errors due to nxv8i1, nxv4i1, and nxv1i1 patterns of STR_PXI/LDR_PXI are remove from AArch64SVEInstrInfo.td: https://github.com/llvm/llvm-project/blob/4198aebc96cb0236fc63e29a92d886e6a2e3fedb/llvm/lib/Target/AArch64/AArch64SVEInstrInfo.td#L2950 https://github.com/llvm/llvm-project/blob/4198aebc96cb0236fc63e29a92d886e6a2e3fedb/llvm/lib/Target/AArch64/AArch64SVEInstrInfo.td#L2960 in https://reviews.llvm.org/D88994. @efriedma-quic, can you comment on complications of adding them back?

> diff --git a/llvm/lib/Target/AArch64/AArch64SVEInstrInfo.td b/llvm/lib/Target/AArch64/AArch64SVEInstrInfo.td
> index 93b02b2d692e..96ad0717d483 100644
> --- a/llvm/lib/Target/AArch64/AArch64SVEInstrInfo.td
> +++ b/llvm/lib/Target/AArch64/AArch64SVEInstrInfo.td
> @@ -2120,9 +2120,6 @@ let Predicates = [HasSVEorStreamingSVE] in {
>    }
> 
>    defm Pat_Store_P16 : unpred_store_predicate<nxv16i1, STR_PXI>;
> -  defm Pat_Store_P8  : unpred_store_predicate<nxv8i1, STR_PXI>;
> -  defm Pat_Store_P4  : unpred_store_predicate<nxv4i1, STR_PXI>;
> -  defm Pat_Store_P2  : unpred_store_predicate<nxv2i1, STR_PXI>;
> 
>    multiclass unpred_load_predicate<ValueType Ty, Instruction Load> {
>      def _fi : Pat<(Ty (load (am_sve_fi GPR64sp:$base, simm9:$offset))),
> @@ -2133,9 +2130,6 @@ let Predicates = [HasSVEorStreamingSVE] in {
>    }
> 
>    defm Pat_Load_P16 : unpred_load_predicate<nxv16i1, LDR_PXI>;
> -  defm Pat_Load_P8  : unpred_load_predicate<nxv8i1, LDR_PXI>;
> -  defm Pat_Load_P4  : unpred_load_predicate<nxv4i1, LDR_PXI>;
> -  defm Pat_Load_P2  : unpred_load_predicate<nxv2i1, LDR_PXI>;

**Comment by efriedma-quic** [comment]
STR_PXI/LDR_PXI don't have the same semantics as an IR "load"/"store" instruction, so the patterns don't make sense.

If you want to store a SVE predicate, you need cast to nxv16i1 (AArch64ISD::REINTERPRET_CAST) before you store.

**Comment by zhaoshiz** [comment]
@sdesmalen-arm I've added test cases where scalable predicate args are passed by reference through the stack. I also think remove the assertions triggered by [1 x <vscale x 16 x i1>] args in LowerFormalArguments() and LowerCall().
@efriedma-quic thanks for the pointer, will address load/store of non-nvx16i1 types in the furture.

**Comment by zhaoshiz** [comment]
gentle ping...

**Review by efriedma-quic — APPROVED** [review]
Please add a test for `<vscale x 32 x i1>`, to make sure that works.  (I think it should, but just to verify.)

Otherwise LGTM

**Comment by zhaoshiz** [comment]
If no objection or more test cases needed I'd like to merge this in next 24 hours.

**Review by efriedma-quic — APPROVED** [review]

**Pull request merged**
