### PR TITLE
[NFC][PowerPC] Use tablegen's MatchRegisterName()

### PR DESCRIPTION
**Pull request by lei137**
Use PPC `MatchRegisterName()` that is auto generated by table gen.

### CODE REVIEW

**Review by amy-kwan — APPROVED** [review]
LGTM. 
Also, since we have no tests, should this be marked with NFC?

**Comment by tstellar** [comment]
I think this commit caused a regression in the dotnet9.0 build for Fedora:

```
             Consolidate compiler generated dependencies of target utilcodestaticnohost
             make[3]: Leaving directory '/builddir/build/BUILD/dotnet9.0-9.0.102-build/dotnet-9.0.1/src/runtime/artifacts/obj/coreclr/linux.ppc64le.Release'
             make  -f utilcode/CMakeFiles/utilcodestaticnohost.dir/build.make utilcode/CMakeFiles/utilcodestaticnohost.dir/build
             /builddir/build/BUILD/dotnet9.0-9.0.102-build/dotnet-9.0.1/src/runtime/src/coreclr/pal/src/arch/ppc64le/context2.S:140:15: error: invalid register name
              ld %r0, 0 +8(%R3)
```

**Comment by lei137** [comment]
> I think this commit caused a regression in the dotnet9.0 build for Fedora:
> 
> ```
> Consolidate compiler generated dependencies of target utilcodestaticnohost
> make[3]: Leaving directory '/builddir/build/BUILD/dotnet9.0-9.0.102-build/dotnet-9.0.1/src/runtime/artifacts/obj/coreclr/linux.ppc64le.Release'
> make  -f utilcode/CMakeFiles/utilcodestaticnohost.dir/build.make utilcode/CMakeFiles/utilcodestaticnohost.dir/build
> /builddir/build/BUILD/dotnet9.0-9.0.102-build/dotnet-9.0.1/src/runtime/src/coreclr/pal/src/arch/ppc64le/context2.S:140:15: error: invalid register name
>               ld %r0, 0 +8(%R3)
>                            ^
> ```

Is the problem `R3` vs `r3`?  I don't see a way for this patch to cause register name to resolve to `R*` in some cases and the valid `r*` in other.... The code that returns either `r*` or `x*` register types have actually not changed.
```
else if (Name.starts_with_insensitive("r"))
    RegNo = isPPC64() ? XRegs[IntVal] : RRegs[IntVal];
```
I might be missing something, can you please provide more info as to why you think this patch is the issue?

**Comment by tstellar** [comment]
I didn't see your response in time and just filed an issue for this here: https://github.com/llvm/llvm-project/issues/126786

Maybe we can discuss it there.

**Comment by redstar** [comment]
> I might be missing something,

`MCRegister RegNo = MatchRegisterName(Name);`

With a brief look at the generated code it seems to me that it matches only lower case names.

**Comment by tstellar** [comment]
> > I might be missing something,
> 
> `MCRegister RegNo = MatchRegisterName(Name);`
> 
> With a brief look at the generated code it seems to me that it matches only lower case names.

Yes, I think that's the issue.

**Comment by lei137** [comment]
> > > I might be missing something,
> > 
> > 
> > `MCRegister RegNo = MatchRegisterName(Name);`
> > With a brief look at the generated code it seems to me that it matches only lower case names.
> 
> Yes, I think that's the issue.

That behaviour have not changed AFAIK.

**Comment by tstellar** [comment]
> > > > I might be missing something,
> > > 
> > > 
> > > `MCRegister RegNo = MatchRegisterName(Name);`
> > > With a brief look at the generated code it seems to me that it matches only lower case names.
> > 
> > 
> > Yes, I think that's the issue.
> 
> That behaviour have not changed AFAIK.

The behavior of the generated function has not changed, but that function is now being used to parse register names where it wasn't before.

**Pull request merged**
