### PR TITLE
[MachineSink][AArch64] Enable sink-and-fold by default

### PR DESCRIPTION
**Pull request by momchil-velikov**
Enable the optimisation by default for AArch64 after a compile time regressoin fix in e8209b2486d8

### CODE REVIEW

**Review by davemgreen — APPROVED** [review]
With the last debug info being fixed, this still LGTM. Thanks for pushing this through.

(You can probably remove the command line from llvm/test/CodeGen/AArch64/sink-and-fold.ll again).

**Comment by antmox** [comment]
Hello! It looks like this patch broke lldb-aarch64-ubuntu : https://lab.llvm.org/buildbot/#/builders/96/builds/48609
Could you please look at this ?

**Comment by TNorthover** [comment]
Another potential problem, I'm afraid. Seen in https://green.lab.llvm.org/green/job/test-suite-verify-machineinstrs-aarch64-O3, but I think this reduced case still shows it:

```
define i32 @unaspack212(ptr %image, i32 %ep) {
entry:
  %add149 = add i32 %ep, 1
  %idxprom150 = zext i32 %add149 to i64
  %arrayidx151 = getelementptr i8, ptr %image, i64 %idxprom150
  br label %land.lhs.true55

land.lhs.true55:                                  ; preds = %if.then155, %land.lhs.true55, %entry
  %0 = load i8, ptr %arrayidx151, align 1
  %cmp153 = icmp eq i8 %0, 0
  br i1 %cmp153, label %if.then155, label %land.lhs.true55

if.then155:                                       ; preds = %land.lhs.true55
  store i32 0, ptr %image, align 1
  br label %land.lhs.true55
}
```

compiled with `llc -verify-machineinstrs`. Basically the sinking leaves a dangling `ORRWrs` that was part of the `zext` and marks the register we care about `killed`.

**Comment by momchil-velikov** [comment]
Addressed in https://github.com/llvm/llvm-project/pull/75072

**Pull request merged**
