### PR TITLE
[compiler-rt]: DumpAllRegs on NetBSD arm64.

### PR DESCRIPTION
**Pull request by devnexen**
all 35 registers are stored in one unique array. for simplicity sake, we do not bother using _REG_X* constants.

### CODE REVIEW

**Review by chestnykh — APPROVED** [review]
LGTM, thanks!

**Comment by fmayer** [comment]
Huh, why do we have a NetBSD branch in [sanitizer_linux.cpp](https://github.com/llvm/llvm-project/pull/102826/files#diff-f740809540e5357d610d6a34715a57e3be96ccf85736f04a3092aa0a0728b2ca)

**Comment by devnexen** [comment]
I guess it is easier to share common code with linux

**Comment by fmayer** [comment]
There is sanitizer_netbsd.cpp, it should go into that.

**Pull request merged**
