### PR TITLE
[nsan] Swap alignas and visibility order (NFC)

### PR DESCRIPTION
**Pull request by nikic**
Use `alignas(16) SANITIZER_INTERFACE_ATTRIBUTE` instead of `SANITIZER_INTERFACE_ATTRIBUTE alignas(16)`, as the former is not supported prior to clang 16. See https://clang.godbolt.org/z/Wj1193xWK.

This was broken by https://github.com/llvm/llvm-project/pull/96142 as part of other style changes.

### CODE REVIEW

**Review by alexander-shaposhnikov — APPROVED** [review]

**Comment by MaskRay** [comment]
We already require support for `alignas` in some compiler-rt library files: `rg -w alignas compiler-rt/lib` (lsan, scudo, gwp_asan, xray, etc).
Old compilers can use `LLVM_ENABLE_RUNTIMES=compiler-rt`, which will use just built Clang to build the runtime libraries.

We could also make `COMPILER_RT_HAS_*` false when Clang is too old.

**Review by MaskRay — CHANGES_REQUESTED** [review]
.

**Comment by alexander-shaposhnikov** [comment]
cc: @vitalybuka

**Comment by nikic** [comment]
> We already require support for `alignas` in some compiler-rt library files: `rg -w alignas compiler-rt/lib` (lsan, scudo, gwp_asan, xray, etc).

The problem here is not alignas in general, but a very specific pattern that only occurs inside nsan. You want to look for `git grep -B2 alignas compiler-rt | grep SANITIZER_INTERFACE_ATTRIBUTE`.

> Old compilers can use `LLVM_ENABLE_RUNTIMES=compiler-rt`, which will use just built Clang to build the runtime libraries.

As far as I know, compiler-rt is subject to the LLVM monorepo host compiler requirements (https://llvm.org/docs/GettingStarted.html#host-c-toolchain-both-compiler-and-standard-library). Only the libcxx and libcxxabi projects are exempt from these.

compiler-rt is commonly used by compilers other than clang, and the host compiler used to build it has no relation to the toolchain it will be part of. For such uses, only LLVM and compiler-rt will be built, but clang will generally not be built.

In any case, changing the host compiler requirements for compiler-rt would require an RFC.

**Comment by MaskRay** [comment]
OK, I see. The issue is that `SANITIZER_INTERFACE_ATTRIBUTE alignas(16)` is not supported by older Clang. Other `alignas(...)` uses are fine. The problem only affects nsan.

`alignas(16) SANITIZER_INTERFACE_ATTRIBUTE` seems to work, so adjust the order instead?

**Comment by MaskRay** [comment]
> OK, I see. The issue is that `SANITIZER_INTERFACE_ATTRIBUTE alignas(16)` is not supported by older Clang. Other `alignas(...)` uses are fine. The problem only affects nsan.
> 
> `alignas(16) SANITIZER_INTERFACE_ATTRIBUTE` seems to work, so adjust the order instead?

`lib/msan/msan.cpp` has a similar use. `alignas(16) SANITIZER_INTERFACE_ATTRIBUTE`  works well there. Tested with Clang 7.   (Clang 6 libc++ can no longer build llvm-project. Clang 6 with GCC 14 cannot build llvm-project. )

Created #98958 and #98959 to clean up some `ALIGNED` in compiler-rt.

**Comment by nikic** [comment]
> `alignas(16) SANITIZER_INTERFACE_ATTRIBUTE` seems to work, so adjust the order instead?

Good point, done!

**Review by MaskRay — APPROVED** [review]

**Pull request merged**
