### PR TITLE
Enable aggressive constant merge in GlobalMerge for AIX

### PR DESCRIPTION
**Pull request by syzaara**
Enable merging all constants without looking at use in GlobalMerge by default to replace PPCMergeStringPool pass on AIX.

### CODE REVIEW

**Review by lei137 — APPROVED** [review]
Please add ref to this in the release notes.
LGTM

**Comment by dyung** [comment]
@syzaara your change is causing the test CodeGen/PowerPC/gcov_ctr_ref_init.ll to fail on several bots. Can you take a look and revert if you need time to investigate?

**Comment by syzaara** [comment]
> @syzaara your change is causing the test CodeGen/PowerPC/gcov_ctr_ref_init.ll to fail on several bots. Can you take a look and revert if you need time to investigate?

I merged a follow-up fix to the test: https://github.com/llvm/llvm-project/pull/114428

**Comment by dyung** [comment]
> > @syzaara your change is causing the test CodeGen/PowerPC/gcov_ctr_ref_init.ll to fail on several bots. Can you take a look and revert if you need time to investigate?
> 
> I merged a follow-up fix to the test: #114428

Ah yes, sorry I missed that. Thanks for the quick fix!

**Pull request merged**
