### PR TITLE
[libclang/python] Bump minimum compatibility to Python 3.6

### PR DESCRIPTION
**Pull request by linux4life798**
Remove Python 2 support and clean up code that conditions based on version.

Issue #76664.

### CODE REVIEW

**Comment by h-vetinari** [comment]
This should just bump to 3.8 IMO. Anything below that is end-of-life and a waste of time to support.

**Comment by linux4life798** [comment]
> This should just bump to 3.8 IMO. Anything below that is end-of-life and a waste of time to support.

I agree and my personal plan is still to bump the version to 3.7 or 3.8, but it was more important to me to make progress towards adding any usable type annotations than it is to raise the min python version across llvm or just within libclang. I figured this incremental change was safe, couldn't be blocked based on min version, and doesn't introduce any syntax that has been obsoleted in later python.

Let me know if you think there is something I could do to help progress the transition to python min version 3.8 (or 3.7).

**Comment by Endilll** [comment]
Looks sensible, but I'm not experienced enough with migration from Python 2 to 3 to approve.

**Review by tru — APPROVED** [review]
LGTM.

**Comment by linux4life798** [comment]
Thanks all! @boomanaiden154 or @tru, could you merge this PR?

**Pull request merged**
