### PR TITLE
[DebugInfo][RemoveDIs] Convert debug-info modes when loading bitcode

### PR DESCRIPTION
**Pull request by jmorse**
As part of eliminating debug-intrinsics in LLVM, we'll shortly be pushing the conversion from "old" dbg.value mode to "new" DPValue mode out from when the pass manager runs, to when modules are loaded. This patch adds that conversion process and some (temporary) options to llvm-lto{,2} to help test it.

Specifically: now whenever we load a bitcode module, consider a flag of whether to "upgrade" it into the new debug-info mode, and if we're lazily materializing functions then do that lazily too. Doing this exposes an error in the IRLinker/materializer handling of DPValues, where we need to transfer the debug-info format flag correctly, and in ValueMapper we need to remap the Values that DPValues point at.

I've added some test coverage in the modified tests; these will be exercised by our llvm-new-debug-iterators buildbot.

This upgrading of debug-info won't be happening for the llvm18 release, instead we'll turn it on after the branch date, thenbe push the boundary of where "new" debug-info starts and ends down into the existing debug-info upgrade path over the course of the next release.

### CODE REVIEW

**Review by SLTozer — APPROVED** [review]
LGTM, with one small suggestion. Ideally we'll soon put a similar conversion step in the IR parser, so that we don't have to do any conversion in the pass managers.

**Comment by jplehr** [comment]
Hi @jmorse I believe this patch broke the AMDGPU OpenMP Offload buildbots
https://lab.llvm.org/buildbot/#/builders/193/builds/45566
https://lab.llvm.org/staging/#/builders/185/builds/843

If you need help in reproducing, I'm happy to try and help.

**Comment by jmorse** [comment]
Curses, looks like I killed most of the buildbots. Reverted in c3f7fb1

**Comment by nico** [comment]
Also broke check-clang when the AMDGPU target was enabled fwiw: http://45.33.8.238/linux/129084/step_7.txt

Thanks for the revert!

**Comment by jmorse** [comment]
/me squints -- alright, this was because I was using `I.DbgMarker->getDbgValueRange()` rather than `I.getDbgValueRange()`, and I wasn't testing with a clean tree. I'd  reapply with the obvious fix, but I'm also out of the figurative office for the rest of the day, so can't revert if it kills all the buildbots again.

**Pull request merged**
