### PR TITLE
[SCCIterator] Union MST node by rank correctly

### LINKED ISSUE #85975: llvm/include/llvm/ADT/SCCIterator.h:285: This code will never work !
llvm/include/llvm/ADT/SCCIterator.h:285:18: style: Same expression on both sides of '<'. [duplicateExpression]

Source code is

    if (G1->Rank < G1->Rank)

### PR DESCRIPTION
**Pull request by XChy**
Fixes #85975

### CODE REVIEW

**Review by dtcxzyw — APPROVED** [review]
LGTM.

**Comment by AtariDreams** [comment]
> Fixes #85975

Nice catch!

**Review by AZero13 — APPROVED** [review]

**Comment by dwblaikie** [comment]
Any chance of a test case?

**Review by WenleiHe — APPROVED** [review]
good catch, thanks for the fix!

**Comment by XChy** [comment]
> Any chance of a test case?

It's a bit hard because this change only improves the efficiency of union find, instead of correctness.

**Comment by dwblaikie** [comment]
> > Any chance of a test case?
> 
> It's a bit hard because this change only improves the efficiency of union find, instead of correctness.

Ah, "correctly" in the title sounded like there was a correctness issue (perhaps one that harms performance more broadly - but perhaps the correctness aspect could be reached via unit test or the like?).

**Pull request merged**
