### PR TITLE
[ELFAttributeParser][NFC] Make string array arguments `const`

### PR DESCRIPTION
**Pull request by pfusik**

### CODE REVIEW

**Comment by vhscampos** [comment]
The changes look good to me, but the commit message is wrong. It's not the arguments that are made const, but rather the pointers.

**Comment by pfusik** [comment]
> The changes look good to me, but the commit message is wrong. It's not the arguments (formal) that are made const, but rather the pointers. Another option is to make clear that the _real_ arguments are made const.

What pointers do you mean? It's the arrays that I make const.
These arrays are passed as arguments, wrapped in `ArrayRef`.
Any suggestion for a better commit message?

**Comment by vhscampos** [comment]
I meant the arrays, yes. Sorry for the confusion. I said "pointers" with the meaning of pointer-to-pointers.

I suggest the commit title says just "Make string arrays const".

**Comment by pfusik** [comment]
> I suggest the commit title says just "Make string arrays const".

Done.

**Review by vhscampos — APPROVED** [review]

**Pull request merged**
