### PR TITLE
[SLP] Pessimistically handle unknown vector entries in SLP vectorizer

### LINKED ISSUE #75437: SLP Vectorizer discards vector entries at unknown positions
SLP Vectorizer can discard vector entries at unknown positions. This example shows the behaviour:

https://godbolt.org/z/or43EM594

The following instruction inserts an element at an unknown position:

```
%2 = insertelement <3 x i64> poison, i64 %value, i64 %position
```

The position depends on an argument that is unknown at compile time.

After running SLP, one can see there is no more instruction present referencing `%position`.

### PR DESCRIPTION
**Pull request by momo5502**
SLP Vectorizer can discard vector entries at unknown positions. This example shows the behaviour:

https://godbolt.org/z/or43EM594

The following instruction inserts an element at an unknown position:

```
%2 = insertelement <3 x i64> poison, i64 %value, i64 %position
```

The position depends on an argument that is unknown at compile time.

After running SLP, one can see there is no more instruction present referencing `%position`.

This happens as SLP parallelizes the two adds in the example. It then needs to merge the original vector with the new vector.

Within `isUndefVector`, the SLP vectorizer constructs a bitmap indicating which elements of the original vector are poison values. It does this by walking the insertElement instructions.

If it encounters an insert with a non-constant position, it is ignored. This will result in poison values to be used for all entries, where there are no inserts with constant positions.

However, as the position is unknown, the element could be anywhere. Therefore, I think it is only safe to assume none of the entries are poison values and to simply take them all over when constructing the shuffleVector instruction.

This fixes #75437

### CODE REVIEW

**Review by alexey-bataev — APPROVED** [review]
Ok, let's fix it this way for now, later need to teach getInsertIndex to separate representation for undef/runtime indices

**Comment by momo5502** [comment]
> Ok, let's fix it this way for now, later need to teach getInsertIndex to separate representation for undef/runtime indices

Alright. Thank you for your review.

Also, while analyzing the issue. I figured there were cases where SLP inserts seemingly redundant shuffles. For example here:

image

`%122` on the left is replaced by 3 shuffles. The last two shuffles expand (`%128`) and merge (`%129`) the vector, however the first shuffle (`%127`) is not being referenced anywhere else in the remaining code (that I can unfortunately not screenshot).

While the redundant shuffle will eventually be removed later by DCE, I am still curious, is there a known reason this happens?

**Comment by alexey-bataev** [comment]
> > Ok, let's fix it this way for now, later need to teach getInsertIndex to separate representation for undef/runtime indices
> 
> Alright. Thank you for your review.
> 
> Also, while analyzing the issue. I figured there were cases where SLP inserts seemingly redundant shuffles. For example here:
> 
> image
> 
> `%122` on the left is replaced by 3 shuffles. The last two shuffles expand (`%128`) and merge (`%129`) the vector, however the first shuffle (`%127`) is not being referenced anywhere else in the remaining code (that I can unfortunately not screenshot).
> 
> While the redundant shuffle will eventually be removed later by DCE, I am still curious, is there a known reason this happens?

2 of these shuffles are free,they are just identity resizing shuffles, so it is not a big issue + they will optimized later. Yes, this can be improved, working on this. It may help if you can provide the reproducer

**Comment by momo5502** [comment]
> 2 of these shuffles are free,they are just identity resizing shuffles, so it is not a big issue + they will optimized later. Yes, this can be improved, working on this. It may help if you can provide the reproducer

Ah I see, so it's known, but not a big deal. Unfortunately, I am not allowed to send the code producing code, but maybe if I find time, I can have a look at it or reduce the sample.

Anyways, thank you. I'm not sure if @RKSimon wants to add an additional review, however, if not, I have no commit access and would appreciate if someone could merge this PR for me.

**Review by RKSimon — APPROVED** [review]
LGTM as a stopgap

**Pull request merged**
