### PR TITLE
[DenseMap] Update combineHashValue

### PR DESCRIPTION
**Pull request by MaskRay**
`combineHashValue` is a custom bit mixer from 2008
(5fc8ab6d187aefbf1d2cbd36e191e675b14db8f6) used for std::pair and
std::tuple. It has a long dependency chain and slow. Replace it with
a simply multiply-xorshift style hash using a constant from
splitmix64[1]. abseil-cpp and carbon also use this style, but with
uint128 to probably get a lower avalanche bias. We don't use uint128 for
MSVC portability.

Measured time to compute [0,1000000000) values on an i7-11850H:

* old: 1.163s
* new: 0.427s

[1]: https://jonkagstrom.com/tuning-bit-mixers/index.html

### CODE REVIEW

**Review by nikic — APPROVED** [review]
LGTM

**Review by ChuanqiXu9 — APPROVED** [review]
LGTM.

**Comment by MaskRay** [comment]
Significant `instruction:u` difference for -O3 builds. This commit itself affects `std::pair`. 

https://llvm-compile-time-tracker.com/compare.php?from=58d7a6e0e6361871442df956bb88798ce602b09d&to=fb17bbce80cf76ce1a31eff463f451f626bc36b5&stat=instructions:u

stage2-O3:

|Benchmark|Old|New|
|--- |--- |--- |
|kimwitu++|39227M|39106M (-0.31%)|
|sqlite3|35441M|35309M (-0.37%)|
|consumer-typeset|32091M|32021M (-0.22%)|
|Bullet|93517M|93231M (-0.31%)|
|tramp3d-v4|79022M|78706M (-0.40%)|
|mafft|33162M|33040M (-0.37%)|
|ClamAV|50706M|50535M (-0.34%)|
|lencod|61560M|61298M (-0.42%)|
|SPASS|43262M|43080M (-0.42%)|
|7zip|192562M|192060M (-0.26%)|
|geomean|55639M|55449M (-0.34%)|

After #95734 and af82e63c28f67bf61a9b2b0e64bc55be4acf520e , `DenseMap<unsigned long, X>` and  `DenseMap<unsigned long long, X>` are affected as well.

**Comment by kazutakahirata** [comment]
> Significant `instruction:u` difference for -O3 builds.

Very nice!

**Pull request merged**
