### PR TITLE
Normalize ptrauth handling in sanitizer runtime

### LINKED ISSUE #100467: fails to build with `error: use of undeclared identifier 'ptrauth_key_cxx_vtable_pointer'`
on linux ubuntu noble
```

FAILED: compiler-rt/lib/ubsan/CMakeFiles/RTUbsan_cxx.aarch64.dir/ubsan_type_hash_itanium.cpp.o 
/build/source/build-llvm/./bin/clang++ --target=aarch64-unknown-linux-gnu -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/build/source/compiler-rt/lib/ubsan/.. -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fstack-protector-strong -fstack-clash-protection -Wformat -Werror=format-security -mbranch-protection=standard -Wno-unused-command-line-argument -Wdate-time -D_FORTIFY_SOURCE=3 -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -fdebug-prefix-map=/build/source/build-llvm/runtimes/runtimes-bins=../../../ -fdebug-prefix-map=/build/source/= -no-canonical-prefixes -ffile-prefix-map=/build/source/build-llvm/runtimes/runtimes-bins=../../../ -ffile-prefix-map=/build/source/= -no-canonical-prefixes -Wall -Wno-unused-parameter -O3 -DNDEBUG -std=c++17 -march=armv8-a -fPIC -fno-builtin -fno-exceptions -fomit-frame-pointer -funwind-tables -fno-stack-protector -fno-sanitize=safe-stack -fvisibility=hidden -fno-lto -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta -O3 -gline-tables-only -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions -ftrivial-auto-var-init=pattern -nostdinc++ -frtti -DUBSAN_CAN_USE_CXXABI -MD -MT compiler-rt/lib/ubsan/CMakeFiles/RTUbsan_cxx.aarch64.dir/ubsan_type_hash_itanium.cpp.o -MF compiler-rt/lib/ubsan/CMakeFiles/RTUbsan_cxx.aarch64.dir/ubsan_type_hash_itanium.cpp.o.d -o compiler-rt/lib/ubsan/CMakeFiles/RTUbsan_cxx.aarch64.dir/ubsan_type_hash_itanium.cpp.o -c /build/source/compiler-rt/lib/ubsan/ubsan_type_hash_itanium.cpp
/build/source/compiler-rt/lib/ubsan/ubsan_type_hash_itanium.cpp:210:34: error: use of undeclared identifier 'ptrauth_key_cxx_vtable_pointer'
  210 |   Vtable = ptrauth_strip(Vtable, ptrauth_key_cxx_vtable_pointer);
      |                                  ^
1 error generated.
```

### PR DESCRIPTION
**Pull request by asl**
1. Include `ptrauth.h` if `ptrauth_intrinsics` language feature is specified (per ptrauth spec, this is what enables `ptrauh.h` usage and functions like `ptrauth_strip`)
 2. For PAC-RET fallback implement two changes:
    1. Switch to macro, so we can ignore key argument
    2. Ensure the unsigned value is erased from LR, so the possibility of gadget reuse is reduced.

Fixes #100467

### CODE REVIEW

**Comment by asl** [comment]
@sylvestre will you please double check if this fixes the issue you're seeing?

**Review by kovdan01 — APPROVED** [review]
LGTM

**Review by DanielKristofKiss — APPROVED** [review]

**Comment by ZequanWu** [comment]
With the fix, this is still broken due to invalid pointer conversion:
```
clang++: warning: argument unused during compilation: '--unwindlib=none' [-Wunused-command-line-argument]
/usr/local/google/home/ayzhao/src/chromium/src/third_party/llvm/compiler-rt/lib/ubsan/ubsan_type_hash_itanium.cpp:210:12: error: incompatible integer to pointer conversion assigning to 'void *' from 'unsigned long'
  210 |   Vtable = ptrauth_strip(Vtable, ptrauth_key_cxx_vtable_pointer);
      |            ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
/usr/local/google/home/ayzhao/src/chromium/src/third_party/llvm/compiler-rt/lib/ubsan/../sanitizer_common/sanitizer_ptrauth.h:20:5: note: expanded from macro 'ptrauth_strip'
   20 |     ({                                  \
      |     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   21 |       unsigned long ret;                \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   22 |       asm volatile(                     \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   23 |           "mov x30, %1\n\t"             \
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   24 |           "hint #7\n\t"                 \
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   25 |           "mov %0, x30\n\t"             \
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   26 |           "mov x30, xzr\n\t"            \
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   27 |           : "=r"(ret)                   \
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   28 |           : "r"(__value)                \
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   29 |           : "x30");                     \
      |           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   30 |       ret;                              \
      |       ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   31 |     })
      |     ~~
1 error generated.
```

**Comment by asl** [comment]
@ZequanWu 

> With the fix, this is still broken due to invalid pointer conversion:

Oh. Thanks for noticing this! I believe we fixed this issue... But apparently, not final version of patch was submitted. So, to double check, the final version has `void *ret` variable, does it work for you?

**Comment by alanzhao1** [comment]
> @ZequanWu
> 
> > With the fix, this is still broken due to invalid pointer conversion:
> 
> Oh. Thanks for noticing this! I believe we fixed this issue... But apparently, not final version of patch was submitted. So, to double check, the final version has `void *ret` variable, does it work for you?
> 
> Apparently, there are no buildbots that cover this configuration...

[A quick search](https://github.com/search?q=repo%3Allvm%2Fllvm-project+ptrauth_strip&type=code) shows that the preference seems to be to cast the result of `ptrauth_strip` to the desired type where it's used. I created https://github.com/llvm/llvm-project/pull/100665

**Pull request merged**
