### PR TITLE
[RISCV,GISel] Add legalizer for G_ABS

### PR DESCRIPTION
**Pull request by MaskRay**
Lower G_ABS to support llvm.abs.* intrinsics.

### CODE REVIEW

**Comment by tschuett** [comment]
Nit. The IRTranslator has probably generated something like:
```
G_INTRINSIC intrinsic(@llvm.abs.v2.32)
```
llvm.abs* is automatically supported. You code does not contain intrinsics.

**Comment by MaskRay** [comment]
> Nit. The IRTranslator has probably generated something like:
> 
> ```
> G_INTRINSIC intrinsic(@llvm.abs.v2.32)
> ```
> 
> llvm.abs* is automatically supported. You code does not contain intrinsics.

irtranslator translates `%abs = tail call i32 @llvm.abs.i32(i32 %a, i1 true)` into `%3:_(s32) = G_ABS %0:_`. Without legalizer lowering `G_ABS` into `G_ASHR/G_ADD/G_XOR`, `G_ABS` fails to be selected.

**Comment by tschuett** [comment]
Apologies.

**Review by mshockwave — APPROVED** [review]
LGTM thanks

**Review by topperc — APPROVED** [review]
LGTM

**Pull request merged**
