### PR TITLE
[clang] Fix isInStdNamespace for Decl flagged extern c++

### PR DESCRIPTION
**Pull request by frederic-tingaud-sonarsource**
The MSVC STL implementation declares multiple classes using:

```cpp
namespace std {
  extern "C++" class locale {
    ...
  };
}
```

`isInStdNamespace` uses the first DeclContext to check whether a Decl is inside the `std` namespace. Here, the first DeclContext of the `locale` Decl is a LinkageSpecDecl so the method will return false.
We need to skip this LinkageSpecDecl to find the first DeclContext of type Namespace and actually check whether we're in the `std` namespace.

### CODE REVIEW

**Review by cor3ntin — COMMENTED** [review]
Looks good.
Can you add an entry to clang/docs/ReleseNotes.rst? 
There is an ast matchers section.

Thanks

**Review by cor3ntin — APPROVED** [review]
LGTM, thanks!

**Comment by cor3ntin** [comment]
Hum, should we use `getNonTransparentContext` instead? That would be cleaner

**Comment by frederic-tingaud-sonarsource** [comment]
Oh, I didn't know about this, but it does look better. Thanks!

**Comment by cor3ntin** [comment]
Thanks! Do you need me to merge this for you?

**Comment by frederic-tingaud-sonarsource** [comment]
Yes please :)

**Pull request merged**
