### PR TITLE
 [HLFIR][flang][OpenMP][MLIR] Basic support for delayed privatization code-gen

### PR DESCRIPTION
**Pull request by ergawy**
Similar to https://github.com/llvm/llvm-project/pull/81833 but for `hlfir` since we need different handling for
the `fir` vs. `hlfir` dialect.

### This is a follow-up to https://github.com/llvm/llvm-project/pull/81833, only the commit with the same name as the PR title is relevant.

### CODE REVIEW

**Comment by kiranchandramohan** [comment]
@ergawy The default flow is HLFIR so do we need https://github.com/llvm/llvm-project/pull/81833 and this patch?

**Comment by ergawy** [comment]
> @ergawy The default flow is HLFIR so do we need #81833 and this patch?


I split for the following reasons:
- From what I see, we have 2 sets of tests flang lowering: one that targets `fir` and one that target `hlfir`. Therefore, I thought all lowering has to work with both paths.
- #81833 does most of the work needed for simple symbols both for `fir` and `hlfir`. Therefore, I split to separate the necessary changed needed in #81833 from the ones specific to `hlfir` in this PR.

Let me know if you prefer to merged the 2 PRs together.

**Comment by kiranchandramohan** [comment]
The direct lowering to FIR flow is deprecated and will be removed soon along with the tests. So it is the HLFIR lowering that we should focus ON. You can even emit an error if direct lowering to FIR is specified.

**Comment by ergawy** [comment]
> The direct lowering to FIR flow is deprecated and will be removed soon along with the tests. So it is the HLFIR lowering that we should focus ON. You can even emit an error if direct lowering to FIR is specified.

Ah, thanks for the clarification! Then, I will abandon this PR in favor of #81833 since it was partially reviewed already. I will add the commit relevant to this PR to the contents of #81833.

**Pull request closed without merging**
