### PR TITLE
[llvm-profgen] Revert #99826 and #99026

### PR DESCRIPTION
**Pull request by tcreech-intel**
Revert #99826 and #99026 to allow for additional input.

### CODE REVIEW

**Comment by tcreech-intel** [comment]
@WenleiHe and @williamweixiao: I suggest we revert these for now and attempt to re-land later.

**Comment by ellishg** [comment]
What is the reasoning to revert? Are there test failures?

**Comment by tcreech-intel** [comment]
> What is the reasoning to revert? Are there test failures?

No test failures, but there are nontrivial changes requested by the code owner after merging and they will be easier to address/review in fresh PRs.

**Comment by WenleiHe** [comment]
> @WenleiHe and @williamweixiao: I suggest we revert these for now and attempt to re-land later.

Thanks for working through the feedbacks and making it easier to review. Much appreciated!

**Review by WenleiHe — APPROVED** [review]

**Pull request merged**
