### PR TITLE
Revert "[llvm] Improve llvm.objectsize computation by computing GEP, alloca and malloc parameters bound"

### PR DESCRIPTION
**Pull request by fmayer**
Reverts llvm/llvm-project#115522

This caused UBSan errors in multi-stage clang build:
https://lab.llvm.org/buildbot/#/builders/25/builds/4241/steps/10/logs/stdio

### CODE REVIEW

**Comment by fmayer** [comment]
> Does #116955 fixes the issue instead?

Let's see: https://lab.llvm.org/buildbot/#/buildrequests/2114124?redirect_to_build=true

**Comment by serge-sans-paille** [comment]
> > Does #116955 fixes the issue instead?
> 
> Let's see: https://lab.llvm.org/buildbot/#/buildrequests/2114124?redirect_to_build=true

looks like the ref wasn't found by the bot - and it's bed time in my TZ

**Comment by fmayer** [comment]
> > > Does #116955 fixes the issue instead?
> > 
> > 
> > Let's see: https://lab.llvm.org/buildbot/#/buildrequests/2114124?redirect_to_build=true
> 
> looks like the ref wasn't found by the bot - and it's bed time in my TZ

I will try again and revert if it doesn't fix, SGTY?

**Comment by fmayer** [comment]
I ran locally and it still happened. submitting this for now

**Pull request merged**
