### PR TITLE
[NFC][TableGen] DirectiveEmitter code cleanup

### PR DESCRIPTION
**Pull request by jurahul**
Eliminate unnecessary llvm:: prefix as this code is in llvm namespace. 
Use ArrayRef<> instead of std::vector references when appropriate. 
Use .empty() instead of .size() == 0.

### CODE REVIEW

**Comment by kazutakahirata** [comment]
Thank you for the cleanup.  Now, is there any way you could separate the `{}->()` conversions with the rest?  A `{}->()` conversion can have a surprising effect like `std::vector<int> Vec(3,5)` vs `std::vector Vec{3, 5}`, so I would have to be more careful and understand each type's constructor than, say, when reviewing comments or removal of `llvm::`.

**Comment by jurahul** [comment]
> Thank you for the cleanup. Now, is there any way you could separate the `{}->()` conversions with the rest? A `{}->()` conversion can have a surprising effect like `std::vector<int> Vec(3,5)` vs `std::vector Vec{3, 5}`, so I would have to be more careful and understand each type's constructor than, say, when reviewing comments or removal of `llvm::`.

I may be, though all the {} -> () changes are for constructors with single arguments here, and for classes defined in the DirectiveEmitter.h, so the risk of the issues you mentioned above is less. But I can if you insist.

**Comment by jurahul** [comment]
Ok, I removed the {} -> () change. @kazutakahirata PTAL.

**Review by kazutakahirata — APPROVED** [review]
LGTM.  Thanks!

**Pull request merged**
