### PR TITLE
[libc++abi][libunwind] Run c++abi and unwind tests against a fake install root

### PR DESCRIPTION
**Pull request by ldionne**
This is what we started doing in libc++ and it straightens up a lot of things that only happened to work before, notably the presence of relative rpaths in dylibs when running from the build tree.

This unlocks the ability to link against a just-built dylib but run against another version of the dylib (for example the system-provided one), which is necessary for proper backdeployment testing.

This patch adds a lot of code duplication between the libc++ and libc++abi testing setups. However, there is already a large amount of duplication and the only real way to get rid of it is to merge libc++abi into libc++. In a way, this patch is a step in that direction because it closes the gap between the two libraries' testing setup.

### CODE REVIEW

**Comment by zeroomega** [comment]
We are seeing a test failure on linux-x64 runtime after this patch landed.

Error message:
```
[245/246](1) Running runtimes regression tests
llvm-lit: /b/s/w/ir/x/w/llvm-llvm-project/llvm/utils/lit/lit/TestingConfig.py:154: fatal: unable to parse config file '/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/libunwind/test/lit.site.cfg', traceback: Traceback (most recent call last):
  File "/b/s/w/ir/x/w/llvm-llvm-project/llvm/utils/lit/lit/TestingConfig.py", line 142, in load_from_path
    exec(compile(data, path, "exec"), cfg_globals, None)
  File "/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/libunwind/test/lit.site.cfg", line 46, in <module>
    libcxx.test.config.configure(
  File "/b/s/w/ir/x/w/llvm-llvm-project/libcxx/utils/libcxx/test/config.py", line 44, in configure
    actions = feature.getActions(config)
  File "/b/s/w/ir/x/w/llvm-llvm-project/libcxx/utils/libcxx/test/dsl.py", line 647, in getActions
    if not self._isSupported(config):
  File "/b/s/w/ir/x/w/llvm-llvm-project/libcxx/utils/libcxx/test/features.py", line 291, in <lambda>
    and not programSucceeds(
  File "/b/s/w/ir/x/w/llvm-llvm-project/libcxx/utils/libcxx/test/dsl.py", line 68, in f
    cache[cacheKey] = function(config, *args, **kwargs)
  File "/b/s/w/ir/x/w/llvm-llvm-project/libcxx/utils/libcxx/test/dsl.py", line 203, in programSucceeds
    programOutput(config, program, args)
  File "/b/s/w/ir/x/w/llvm-llvm-project/libcxx/utils/libcxx/test/dsl.py", line 68, in f
    cache[cacheKey] = function(config, *args, **kwargs)
  File "/b/s/w/ir/x/w/llvm-llvm-project/libcxx/utils/libcxx/test/dsl.py", line 173, in programOutput
    raise ConfigurationCompilationError(
libcxx.test.dsl.ConfigurationCompilationError: Failed to build program, cmd:
['/b/s/w/ir/x/w/llvm_build/./bin/clang++ /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/test/__config_src__/tmp6ibehrxq.cpp -isysroot /b/s/w/ir/x/w/cipd/linux --target=x86_64-unknown-linux-gnu -nostdinc++ -I /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/libunwind/test-suite-install/include -funwind-tables -std=c++26 -Werror -Wall -Wctad-maybe-unsupported -Wextra -Wshadow -Wundef -Wunused-template -Wno-unused-command-line-argument -Wno-attributes -Wno-pessimizing-move -Wno-noexcept-type -Wno-atomic-alignment -Wno-reserved-module-identifier -Wdeprecated-copy -Wdeprecated-copy-dtor -Wno-user-defined-literals -Wno-tautological-compare -Wsign-compare -Wunused-variable -Wunused-parameter -Wunreachable-code -Wno-unused-local-typedef -Wno-local-type-template-args -Wno-c++11-extensions -Wno-unknown-pragmas -Wno-pass-failed -Wno-mismatched-new-delete -Wno-redundant-move -Wno-self-move -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -Werror=thread-safety -Wuser-defined-warnings  /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/libunwind/test-suite-install/lib/libunwind.a -lpthread -Wl,--export-dynamic -ldl -o /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/test/__config_exec__/Output/tmp6ibehrxq.cpp.dir/t.tmp.exe']
stderr is:
clang++: error: no such file or directory: '/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/libunwind/test-suite-install/lib/libunwind.a'


FAILED: CMakeFiles/check-runtimes /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/CMakeFiles/check-runtimes 
cd /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins && /b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.8 /b/s/w/ir/x/w/llvm_build/./bin/llvm-lit --resultdb-output=r.j -v --param HWASAN_ENABLE_ALIASES=1 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/libunwind/test /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/libcxxabi/test /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/libcxx/test /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/interception/Unit /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/lsan/X86_64LsanConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/lsan/X86_64AsanConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/lsan/X86_64HWAsanConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/ubsan/Standalone-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/ubsan/Standalone-lld-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/ubsan/AddressSanitizer-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/ubsan/AddressSanitizer-lld-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/ubsan/MemorySanitizer-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/ubsan/MemorySanitizer-lld-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/ubsan/ThreadSanitizer-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/ubsan/ThreadSanitizer-lld-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/sanitizer_common/asan-x86_64-Linux /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/sanitizer_common/lsan-x86_64-Linux /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/sanitizer_common/hwasan-x86_64-Linux /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/sanitizer_common/msan-x86_64-Linux /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/sanitizer_common/tsan-x86_64-Linux /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/sanitizer_common/ubsan-x86_64-Linux /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/sanitizer_common/Unit /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/fuzzer/unit /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/fuzzer/X86_64DefaultLinuxConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/fuzzer/X86_64StaticLibcxxLinuxConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/metadata /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/asan/X86_64LinuxConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/asan/Unit/X86_64LinuxConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/asan/X86_64LinuxDynamicConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/asan/Unit/X86_64LinuxDynamicConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/rtsan/X86_64LinuxConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/rtsan/Unit /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/dfsan/X86_64Config /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/msan/X86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/msan/lld-X86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/msan/Unit /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/hwasan/X86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/tsan/X86_64Config /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/tsan/Unit /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/safestack/Standalone-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/cfi/Standalone-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/cfi/Devirt-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/cfi/Standalone-thinlto-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/cfi/Devirt-thinlto-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/cfi/Standalone-lld-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/cfi/Devirt-lld-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/cfi/Standalone-lld-thinlto-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/cfi/Devirt-lld-thinlto-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/scudo/standalone/unit /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/scudo/standalone/unit/gwp_asan /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/ubsan_minimal/x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/gwp_asan/unit /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/gwp_asan/X86_64LinuxConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/nsan/X86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/nsan/Unit /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/profile/Profile-x86_64 /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/ctx_profile/X86_64LinuxConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/ctx_profile/Unit/X86_64LinuxConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/memprof/X86_64LinuxConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/memprof/Unit/X86_64LinuxConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/memprof/X86_64LinuxDynamicConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/xray/X86_64LinuxConfig /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/test/orc/X86_64LinuxConfig
ninja: build stopped: subcommand failed.
FAILED: runtimes/CMakeFiles/check-runtimes-x86_64-unknown-linux-gnu /b/s/w/ir/x/w/llvm_build/runtimes/CMakeFiles/check-runtimes-x86_64-unknown-linux-gnu 

```

It looks like cmake pointed a wrong libunwind path to the clang. We are still investigating.

**Comment by bjope** [comment]
Seeing same fault as @zeroomega .

I think problem is related to LLVM_ENABLE_PER_TARGET_RUNTIME_DIR. When that is set to ON the install path is extended (in libunwind/CMakeLIsts.txt):
```
  set(LIBUNWIND_TARGET_SUBDIR ${LLVM_DEFAULT_TARGET_TRIPLE})
  if(LIBUNWIND_LIBDIR_SUBDIR)
    string(APPEND LIBUNWIND_TARGET_SUBDIR /${LIBUNWIND_LIBDIR_SUBDIR})
  endif()
```
And then the substitution in libunwind/test/configs/cmake-bridge.cfg.in is wrong:
```
config.substitutions.append(('%{lib}', '@LIBUNWIND_TESTING_INSTALL_PREFIX@/lib'))
```

**Comment by ldionne** [comment]
Thanks for the analysis. Per-target runtime dir strikes again! That setting keeps on creating issues (by no fault of its own) because it's not the default.

Can we do something like this instead, then?

```
config.substitutions.append(('%{lib}', '@LIBUNWIND_TESTING_INSTALL_PREFIX@/@LIBUNWIND_INSTALL_LIBRARY_DIR@'))
```

We should fix this one forward since there's a complicated dependency chain on top of this (we switched to Github-hosted runners for macOS testing after this patch and they will start failing if we revert this). Hopefully it's not too complicated to fix forward.

**Comment by zeroomega** [comment]
> Thanks for the analysis. Per-target runtime dir strikes again! That setting keeps on creating issues (by no fault of its own) because it's not the default.
> 
> Can we do something like this instead, then?
> 
> ```
> config.substitutions.append(('%{lib}', '@LIBUNWIND_TESTING_INSTALL_PREFIX@/@LIBUNWIND_INSTALL_LIBRARY_DIR@'))
> ```
> 
> We should fix this one forward since there's a complicated dependency chain on top of this (we switched to Github-hosted runners for macOS testing after this patch and they will start failing if we revert this). Hopefully it's not too complicated to fix forward.

That seems to fix the test:
Test run: https://ci.chromium.org/ui/p/fuchsia/builders/toolchain.ci.shadow/clang-linux-x64/b8735236964550803665/overview
based on https://github.com/zeroomega/llvm-project/tree/libunwind_fix  https://github.com/zeroomega/llvm-project/commit/1e3b4a6a97b32cd1b501ad5256036967a0821327

**Pull request merged**
