### PR TITLE
[IR] Make instr-create fns with Instruction *InsertBefore non-default

### PR DESCRIPTION
**Pull request by SLTozer**
This patch changes each of the methods that create instructions and may insert it at the same time - generally `InstrType::Create(...)` or constructors - such that the overload called when the insert-position argument is omitted will be the candidate that takes a `BasicBlock *InsertAtEnd` argument, rather than an `Instruction *InsertBefore` argument as is currently default in all cases. This is to move us towards deprecating the insert-before-instruction versions, for the sake of preventing debug-info errors creeping in from the RemoveDIs project; for more details on this motivation, see the relevant [discourse thread](https://discourse.llvm.org/t/psa-instruction-constructors-changing-to-iterator-only-insertion/77845) and the [pull request](https://github.com/llvm/llvm-project/pull/85980) that would delete the insert-before-instruction functions.

Unclear who's best placed to review this, but since this patch should be NFC - even for downstream consumers - it's relatively low-stakes; for the subsequent patch that deprecates the Instruction versions, I'll put out a RFC on discourse.

### CODE REVIEW

**Review by OCHyams — APPROVED** [review]
Mechanically LGTM

The changes look like they move in the direction agreed upon in the Discourse discussion. Making the `Instruction*` versions not the default makes it easier to deprecate and remove them.

It's a shame that this introduced some almost-duplicated functions in Instruction.cpp - OTOH, we plan to remove one version.

I think it's worth some others having this on their radar too (cc @dwblaikie and @nikic) - I couldn't see this linked in the Discourse thread, it's probably worth dropping a link there if I haven't just missed it.

**Review by nikic — COMMENTED** [review]
I guess this is okay (and I wouldn't want to block this), but this does seem like a good point to reconsider the overall design. I think there are two broad alternatives:

 1. Only have a single method which takes an InsertionPoint type. This type is basically a union of BasicBlock::iterator, BasicBlock *, or "none". The pro is that we have a good bit less code duplication. The con is that it's a bit less efficient -- though my primary concern would actually the the additional header cost this may impose.
 2. Remove the "create and insert" support entirely, and instead explicitly call insertBefore() or ... and this is what most code really should be doing ... use IRBuilder. There's a decent chance that code not using IRBuilder also fails to preserve debug locations.

Probably option 2 would be ideal, but it's also the option that involves the most work :)

**Comment by SLTozer** [comment]
> I guess this is okay (and I wouldn't want to block this), but this does seem like a good point to reconsider the overall design.

I agree - the reason I took this approach was mainly that it is the softest in terms of API changes - although we eventually need to move people off of inserting at Instructions, the current approach ensures that as little changes underfoot for API users as possible (although we don't guarantee a stable API, previous discussions indicated that since instruction creation has such a large surface area it should be handled delicately).

> Probably option 2 would be ideal, but it's also the option that involves the most work :)

I believe this as well - as you mentioned it has extra advantages which are highly relevant to my interests, as I'm imminently looking to make further changes to instruction creation to better preserve debug locations, and these may be easier to implement if we're creating and inserting instructions through the IRBuilder. My major concern however isn't the amount of work required (though it's not to be underestimated), but the disruption that might be involved. Do you have a sense that forcing a transition to IRBuilder would be reasonable?

**Comment by nikic** [comment]
> > Probably option 2 would be ideal, but it's also the option that involves the most work :)
> 
> I believe this as well - as you mentioned it has extra advantages which are highly relevant to my interests, as I'm imminently looking to make further changes to instruction creation to better preserve debug locations, and these may be easier to implement if we're creating and inserting instructions through the IRBuilder. My major concern however isn't the amount of work required (though it's not to be underestimated), but the disruption that might be involved. Do you have a sense that forcing a transition to IRBuilder would be reasonable?

I don't think we should force the use of IRBuilder *everywhere*, but I do think that a lot of the code currently doing manual instruction insertion would benefit from using IRBuilder instead. The remainder can still use the explicit insertion methods. But I don't really have a good handle on just how commonly used the create-and-insert overloads currently are (you probably have a better idea, as you did some mass changes in that area...)

**Comment by SLTozer** [comment]
> But I don't really have a good handle on just how commonly used the create-and-insert overloads currently are (you probably have a better idea, as you did some mass changes in that area...)

I don't have a great sense of it, since I was mostly detecting and fixing specific patterns rather than getting a sweeping overview. I think a rough outline of a suitable update process though would be:

1. Update `Instruction::Create` methods to take a single "InsertPosition" that is constructed from either `Instruction *InsertBefore`, `BasicBlock *InsertAtEnd`, `BasicBlock::iterator InsertAt`, or `std::nullopt`.
2. Immediately deprecate the `Instruction *InsertBefore` constructor, so that any downstream users are immediately notified, and the BasicBlock version can also be deprecated later on as a prelude to making insertion iterator-only.
3. Add the new iterator methods described in the previously-mentioned RFC.
4. Remove the InsertPosition class entirely (and the argument if we do decide to allow direct or IRBuilder insertion only) while making direct insertion methods iterator-only.

This means that the only breaking steps are some insert-position arguments being deprecated at step (2), before being removed at step (4), which can be spread out over a release so that all downstream users have a chance to adapt.

**Comment by SLTozer** [comment]
> @SLTozer That sounds reasonable to me.

Thanks @nikic - I've created new reviews, https://github.com/llvm/llvm-project/pull/94224 and https://github.com/llvm/llvm-project/pull/94226, which collectively implement the first step of this approach. Rather than use an actual union type, the first patch adds new functionality to the ilist classes to allow us to use just a `BasicBlock::iterator` as an insert position in all cases, and the second patch uses that to replace each insert position overload with a single version.

**Comment by SLTozer** [comment]
Abandoned in favour of https://github.com/llvm/llvm-project/pull/94226.

**Pull request closed without merging**
