### PR TITLE
Revert "[mlir][tensor] Refine the semantics of `createPadHighOp`"

### PR DESCRIPTION
**Pull request by hanhanW**
Reverts llvm/llvm-project#109667

It breaks the behavior of [linalg::padAndHoistLinalgOp](https://github.com/llvm/llvm-project/blob/fbec1c2a08ce2ae9750ddf3cecc86c5dd2bbc9d8/mlir/lib/Dialect/Linalg/Transforms/Padding.cpp#L265C7-L265C34), which calls [makeComposedPadHighOp here](https://github.com/llvm/llvm-project/blob/fbec1c2a08ce2ae9750ddf3cecc86c5dd2bbc9d8/mlir/lib/Dialect/Linalg/Transforms/Padding.cpp#L148-L149). The implementation of [makeComposedPadHighOp](https://github.com/llvm/llvm-project/blob/83368191a21340a6c3a8f88b01ecae6433640957/mlir/lib/Dialect/Linalg/Utils/Utils.cpp#L192) relies on the behavior to create valid pad ops.

To repro: `mlir-opt --transform-interpreter ~/repro.mlir`

```mlir
module {
  func.func @batch_matmul_f16(%arg0: tensor<1x?x1281xf16>, %arg1: tensor<1x1281x?xf16>, %arg2: tensor<1x?x?xf16>) -> tensor<1x?x?xf16> {
    %cst = arith.constant 0.000000e+00 : f16
    %c0 = arith.constant 0 : index
    %0 = linalg.fill ins(%cst : f16) outs(%arg2 : tensor<1x?x?xf16>) -> tensor<1x?x?xf16>
    %1 = linalg.batch_matmul ins(%arg0, %arg1 : tensor<1x?x1281xf16>, tensor<1x1281x?xf16>) outs(%0 : tensor<1x?x?xf16>) -> tensor<1x?x?xf16>
    return %1 : tensor<1x?x?xf16>
  }
  module attributes {transform.with_named_sequence} {
    transform.named_sequence @__transform_main(%arg0: !transform.any_op {transform.readonly}) {
      %0 = transform.structured.match ops{["linalg.batch_matmul"]} in %arg0 : (!transform.any_op) -> !transform.any_op
      %padded, %pad, %copy = transform.structured.pad %0 {pack_paddings = [1, 1], padding_dimensions = [3], padding_values = [0.000000e+00 : f16, 0.000000e+00 : f16, 0.000000e+00 : f16]} : (!transform.any_op) -> (!transform.any_op, !transform.any_op, !transform.op<"bufferization.materialize_in_destination">)
      %1 = transform.num_associations %copy : (!transform.op<"bufferization.materialize_in_destination">) -> !transform.param<i64>
      transform.debug.emit_param_as_remark %1 : !transform.param<i64>
      transform.yield
    }
  }
}
```

### CODE REVIEW

**Comment by MaheshRavishankar** [comment]
Oh man! I didn't realize this issue. Ok please signal this to Andrej

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by banach-space** [comment]
Sorry for the disruption and thanks for providing a repro! +1 to reverting, I can revisit tomorrow.

**Comment by banach-space** [comment]
Looking at the output for this example , what's the point of padding here?

```mlir
  func.func @batch_matmul_f16(%arg0: tensor<1x?x1281xf16>, %arg1: tensor<1x1281x?xf16>, %arg2: tensor<1x?x?xf16>) -> tensor<1x?x?xf16> {
    %cst = arith.constant 0.000000e+00 : f16
    %c0 = arith.constant 0 : index
    %0 = linalg.fill ins(%cst : f16) outs(%arg2 : tensor<1x?x?xf16>) -> tensor<1x?x?xf16>
    %cst_0 = arith.constant 0.000000e+00 : f16
    %padded = tensor.pad %arg0 nofold low[0, 0, 0] high[0, 0, 0] {
    ^bb0(%arg3: index, %arg4: index, %arg5: index):
      tensor.yield %cst_0 : f16
    } : tensor<1x?x1281xf16> to tensor<1x?x1281xf16>
    %cst_1 = arith.constant 0.000000e+00 : f16
    %padded_2 = tensor.pad %arg1 nofold low[0, 0, 0] high[0, 0, 0] {
    ^bb0(%arg3: index, %arg4: index, %arg5: index):
      tensor.yield %cst_1 : f16
    } : tensor<1x1281x?xf16> to tensor<1x1281x?xf16>
    %c1 = arith.constant 1 : index
    %dim = tensor.dim %arg0, %c1 : tensor<1x?x1281xf16>
    %c2 = arith.constant 2 : index
    %dim_3 = tensor.dim %arg1, %c2 : tensor<1x1281x?xf16>
    %c1_4 = arith.constant 1 : index
    %dim_5 = tensor.dim %0, %c1_4 : tensor<1x?x?xf16>
    %c2_6 = arith.constant 2 : index
    %dim_7 = tensor.dim %0, %c2_6 : tensor<1x?x?xf16>
    %1 = linalg.batch_matmul ins(%padded, %padded_2 : tensor<1x?x1281xf16>, tensor<1x1281x?xf16>) outs(%0 : tensor<1x?x?xf16>) -> tensor<1x?x?xf16>
    %extracted_slice = tensor.extract_slice %1[0, 0, 0] [1, %dim, %dim_3] [1, 1, 1] : tensor<1x?x?xf16> to tensor<1x?x?xf16>
    %2 = bufferization.materialize_in_destination %extracted_slice in %0 : (tensor<1x?x?xf16>, tensor<1x?x?xf16>) -> tensor<1x?x?xf16>
    return %2 : tensor<1x?x?xf16>
  }
  ```
  
 In this particular case, `tensor.pad` is a NOP - that's because both dynamic dimensions (input and output) are assumed identical.  But is that a safe/valid assumption? IMO, it's not. IIUC, `tensor.pad` shouldn't be generated at all. WDYT?

**Comment by hanhanW** [comment]
> Looking at the output for this example , what's the point of padding here?
> 
> ```mlir
>   func.func @batch_matmul_f16(%arg0: tensor<1x?x1281xf16>, %arg1: tensor<1x1281x?xf16>, %arg2: tensor<1x?x?xf16>) -> tensor<1x?x?xf16> {
>     %cst = arith.constant 0.000000e+00 : f16
>     %c0 = arith.constant 0 : index
>     %0 = linalg.fill ins(%cst : f16) outs(%arg2 : tensor<1x?x?xf16>) -> tensor<1x?x?xf16>
>     %cst_0 = arith.constant 0.000000e+00 : f16
>     %padded = tensor.pad %arg0 nofold low[0, 0, 0] high[0, 0, 0] {
>     ^bb0(%arg3: index, %arg4: index, %arg5: index):
>       tensor.yield %cst_0 : f16
>     } : tensor<1x?x1281xf16> to tensor<1x?x1281xf16>
>     %cst_1 = arith.constant 0.000000e+00 : f16
>     %padded_2 = tensor.pad %arg1 nofold low[0, 0, 0] high[0, 0, 0] {
>     ^bb0(%arg3: index, %arg4: index, %arg5: index):
>       tensor.yield %cst_1 : f16
>     } : tensor<1x1281x?xf16> to tensor<1x1281x?xf16>
>     %c1 = arith.constant 1 : index
>     %dim = tensor.dim %arg0, %c1 : tensor<1x?x1281xf16>
>     %c2 = arith.constant 2 : index
>     %dim_3 = tensor.dim %arg1, %c2 : tensor<1x1281x?xf16>
>     %c1_4 = arith.constant 1 : index
>     %dim_5 = tensor.dim %0, %c1_4 : tensor<1x?x?xf16>
>     %c2_6 = arith.constant 2 : index
>     %dim_7 = tensor.dim %0, %c2_6 : tensor<1x?x?xf16>
>     %1 = linalg.batch_matmul ins(%padded, %padded_2 : tensor<1x?x1281xf16>, tensor<1x1281x?xf16>) outs(%0 : tensor<1x?x?xf16>) -> tensor<1x?x?xf16>
>     %extracted_slice = tensor.extract_slice %1[0, 0, 0] [1, %dim, %dim_3] [1, 1, 1] : tensor<1x?x?xf16> to tensor<1x?x?xf16>
>     %2 = bufferization.materialize_in_destination %extracted_slice in %0 : (tensor<1x?x?xf16>, tensor<1x?x?xf16>) -> tensor<1x?x?xf16>
>     return %2 : tensor<1x?x?xf16>
>   }
> ```
> 
> In this particular case, `tensor.pad` is a NOP - that's because both dynamic dimensions (input and output) are assumed identical. But is that a safe/valid assumption? IMO, it's not. IIUC, `tensor.pad` shouldn't be generated at all. WDYT?

It is technically a NOP, but we still need to generate the pad op. Because there is a `nofold` attribute. This is controlled by `pack_paddings` in the transform op. A scenario of using these transformation is to hint the bufferization to create an intermediate buffer (e.g., stack buffer on CPU's land), and it is sort of preparation for vectorization. In one of use cases, we can `tile parallel loops -> pad parallel dimensions-> tile reduction loops -> pad reduction dimensions` to enable the vectorization for dynamic shapes. The chain of `extract_slice -> pad (foldable) -> extract_slice -> pad (nofold)` can be folded into a single pad op by [FoldOrthogonalPaddings pattern](https://github.com/llvm/llvm-project/blob/c11722223bacf604e60414542743d021a9f13aee/mlir/lib/Dialect/Tensor/IR/TensorOps.cpp#L3147-L3183). I think we want to keep the pass working, so we don't want to break linalg::padAndHoistLinalgOp's behavior.

**Comment by banach-space** [comment]
> It is technically a NOP, but we still need to generate the pad op. Because there is a `nofold` attribute. This is controlled by `pack_paddings` in the transform op. A scenario of using these transformation is to hint the bufferization to create an intermediate buffer (e.g., stack buffer on CPU's land), and it is sort of preparation for vectorization. In one of use cases, we can `tile parallel loops -> pad parallel dimensions-> tile reduction loops -> pad reduction dimensions` to enable the vectorization for dynamic shapes. The chain of `extract_slice -> pad (foldable) -> extract_slice -> pad (nofold)` can be folded into a single pad op by [FoldOrthogonalPaddings pattern](https://github.com/llvm/llvm-project/blob/c11722223bacf604e60414542743d021a9f13aee/mlir/lib/Dialect/Tensor/IR/TensorOps.cpp#L3147-L3183). I think we want to keep the pass working, so we don't want to break linalg::padAndHoistLinalgOp's behavior.

Thank you for the explanation, that's very helpful 🙏🏻  I need a bit more time to parse this in the context of scalable vectors, and, indeed, work on padding for SVE (which would be a valid lowering path). 

Interestingly, in your example you are padding the static dim and for dynamic dims the transformation fails elsewhere. And my intent was to catch cases where both the input and output dims are dynamic. I failed miserably, but at least we've found a gap in our testing. And my assumption seems to hold (at least one dim should be static).

I've added some tests to capture this and a couple other cases: 
* https://github.com/llvm/llvm-project/pull/110271

This should protect us from my mistakes in the future. I will also try to refine the original PR later on.

Btw, this made me wonder - why `pack_paddings` and not `nofold` 🤔 ?

**Comment by hanhanW** [comment]
> Interestingly, in your example you are padding the static dim and for dynamic dims the transformation fails elsewhere. 

I don't remember all the details, but the order to make fusion work is `tile parallel loops -> pad parallel dimensions-> tile reduction loops -> pad reduction dimensions`. The first padding avoids the padding along reduction dimensions because they are not tiled yet. Then the reduction dimension is tiled, so we can pad the operands with a smallest bounding box.

> Btw, this made me wonder - why pack_paddings and not nofold 🤔 ?

I have no ideas either. :)

**Pull request merged**
