### PR TITLE
Reland "[llvm][AArch64] Copy all operands when expanding BLR_BTI bundle (#78267)"

### LINKED ISSUE #77915: Miscompilation of calls to setjmp after "Preserve regmask when expanding the BLR_BTI pseudo instruction"
The fix to issue #73787, in commit 99d485917ae5f10629cb9d7ca96b7cd6773ac35f, from pull request #73927, seem to cause miscompilations in other similar-looking cases.

The issues can be triggered with ffmpeg, with the very latest versions of ffmpeg, that include commit https://github.com/ffmpeg/ffmpeg/commit/65739691b90012c9d93b2e5e0e89a55d8de9eb7b. To reproduce it, build it like this:
```console
$ git clone https://github.com/ffmpeg/ffmpeg
$ cd ffmpeg
$ git checkout 65739691b90012c9d93b2e5e0e89a55d8de9eb7b
$ cd ..
$ mkdir ffmpeg-build
$ cd ffmpeg-build
$ ../ffmpeg/configure --cc=clang --extra-cflags='-mbranch-protection=standard' --extra-ldflags='-mbranch-protection=standard'
$ make -j$(nproc) fate-checkasm
```

The symptom is that when calling `sigsetjmp`, the first parameter, in register `x0`, has been lost and is passed as a null pointer.

The issue can be observed with this attached LLVM IR file as well, which is the code from `tests/checkasm/idctdsp.c` in such a build. [idctdsp-ll.zip](https://github.com/llvm/llvm-project/files/13919002/idctdsp-ll.zip)

It can be injected in such a build to test whether it is correctly compiled or not:
```
$ clang -mbranch-protection=standard -O3 idctdsp.ll -c -o tests/checkasm/idctdsp.o && make -j$(nproc) fate-checkasm-idctdsp
```

The difference in generated code can be observed by looking at the output of `clang -mbranch-protection=standard -O3 idctdsp.ll -c -o tests/checkasm/idctdsp.o -mllvm -print-after-all` before/after this change. That diff looks like this:
```diff
--- log-good    2024-01-12 14:24:33.730645287 +0200
+++ log-bad     2024-01-12 14:24:26.046612441 +0200
@@ -67330,8 +67330,8 @@
   renamable $x27 = LDRXroX killed renamable $x8, killed renamable $x9, 0, 0 :: (load (s64) from %ir.13, !tbaa !13)
   $x0 = ORRXrs $xzr, $fp, 0
   renamable $w1 = MOVZWi 1, 0
-  BUNDLE implicit-def $lr, implicit-def $w30, implicit $sp {
-    BL @__sigsetjmp, implicit-def $lr, implicit $sp
+  BUNDLE implicit-def $lr, implicit-def $w30, implicit-def $sp, implicit-def $wsp, implicit-def $w0, implicit $sp {
+    BL @__sigsetjmp, <regmask $fp $lr $wzr $xzr $b8 $b9 $b10 $b11 $b12 $b13 $b14 $b15 $d8 $d9 $d10 $d11 $d12 $d13 $d14 $d15 $h8 $h9 $h10 $h11 $h12 $h13 $h14 $h15 $s8 $s9 $s10 $s11 $s12 and 55 more...>, implicit-def $lr, implicit $sp, implicit-def dead $lr, implicit $sp, implicit-def $sp, implicit-def $w0
     HINT 36
   }
   BL @checkasm_handle_signal, <regmask $fp $lr $wzr $xzr $b8 $b9 $b10 $b11 $b12 $b13 $b14 $b15 $d8 $d9 $d10 $d11 $d12 $d13 $d14 $d15 $h8 $h9 $h10 $h11 $h12 $h13 $h14 $h15 $s8 $s9 $s10 $s11 $s12 and 55 more...>, implicit-def dead $lr, implicit $sp, implicit $w0, implicit-def $sp, implicit-def dead $w0
@@ -73086,14 +73086,13 @@
   liveins: $fp, $x8, $x20, $x21, $x22, $x23, $x24, $x25, $x26, $x28
   $x9 = ADDXri $sp, 248, 0
   STRXui renamable $x8, $sp, 21 :: (store (s64) into %stack.16)
-  $x0 = ORRXrs $xzr, $fp, 0
   renamable $x19 = ADDXrs killed renamable $x9, killed renamable $x8, 4
   $x9 = ADDXri $sp, 296, 0
   renamable $w1 = MOVZWi 1, 0
   renamable $x8 = LDRXui renamable $x19, 1 :: (load (s64) from %ir.offset, !tbaa !7)
   renamable $x27 = LDRXroX killed renamable $x8, killed renamable $x9, 0, 0 :: (load (s64) from %ir.13, !tbaa !13)
-  BUNDLE implicit-def $lr, implicit-def $w30, implicit $sp {
-    BL @__sigsetjmp, implicit-def $lr, implicit $sp
+  BUNDLE implicit-def $lr, implicit-def $w30, implicit-def $sp, implicit-def $wsp, implicit-def $w0, implicit $sp {
+    BL @__sigsetjmp, <regmask $fp $lr $wzr $xzr $b8 $b9 $b10 $b11 $b12 $b13 $b14 $b15 $d8 $d9 $d10 $d11 $d12 $d13 $d14 $d15 $h8 $h9 $h10 $h11 $h12 $h13 $h14 $h15 $s8 $s9 $s10 $s11 $s12 and 55 more...>, implicit-def $lr, implicit $sp, implicit-def dead $lr, implicit $sp, implicit-def $sp, implicit-def $w0
     HINT 36
   }
   BL @checkasm_handle_signal, <regmask $fp $lr $wzr $xzr $b8 $b9 $b10 $b11 $b12 $b13 $b14 $b15 $d8 $d9 $d10 $d11 $d12 $d13 $d14 $d15 $h8 $h9 $h10 $h11 $h12 $h13 $h14 $h15 $s8 $s9 $s10 $s11 $s12 and 55 more...>, implicit-def dead $lr, implicit $sp, implicit killed $w0, implicit-def $sp, implicit-def dead $w0
```
(I left out a number of identical hunks of the diff.)

The first change is the one that looks like the right  thing, the fix for #73787. However further on, this causes the `$x0 = ORRXrs $xzr, $fp, 0`, which is used as input to the `__sigsetjmp` call, gets lost.

CC @efriedma-quic @DavidSpickett

### PR DESCRIPTION
**Pull request by DavidSpickett**
This reverts commit 955417ade2648c2b1a4e5f0be697f61570590a88.

The problem with the previous version was that the bundle instruction had arguments like "target arg1 arg2". When it's expanded we produced a BL or BLR which can only accept one argument, the target of the branch.

Now I realise why expandCALL_RVMARKER has to copy them in mutiple steps. The operands for the called function need to be changed to implicit arguments of the branch instruction.

* Copy the branch target.
* Copy all register operands, marking them as implicit.
* Copy any other operands without modifying them.

Prior to any attempt to fix #77915:
BL @_setjmp, csr_aarch64_aapcs, implicit-def $lr, implicit $sp, implicit-def dead $lr, implicit $sp, implicit-def $sp

Which is dropping the use of the arguments for the called function.

My first fix attempt produced:
BL @_setjmp, $x0, $w1, <regmask $fp ...>, implicit-def $lr, implicit $sp, implicit-def dead $lr, implicit $sp, implicit-def $sp

It copied the arguments but as explicit arguments to the BL which only expects 1, failing verification.

With this new change we produce:
BL @_setjmp, csr_aarch64_aapcs, implicit-def $lr, implicit $sp, implicit $x0, implicit $w1, implicit-def dead $lr, implicit $sp, implicit-def $sp

Note specifically the added "implicit $x0, implicit $w1". So BL only has 1 explicit argument, but the arguments to the function are still used.

### CODE REVIEW

**Comment by DavidSpickett** [comment]
Turns out `expandCALL_RVMARKER` is doing the right thing, just took me a while to understand it. So the code is almost the same now. I could factor it out but keeping the PR small for now.

**Comment by efriedma-quic** [comment]
Oh, I see, that makes more sense.

Is there some reason we can't just change the definition of BLR_BTI so it takes the same operands as BLR?  Defining it to take different operands, then rewriting them to the form we want, seems like it's more complicated than necessary.

**Comment by mstorsjo** [comment]
> Oh, I see, that makes more sense.
> 
> Is there some reason we can't just change the definition of BLR_BTI so it takes the same operands as BLR? Defining it to take different operands, then rewriting them to the form we want, seems like it's more complicated than necessary.

FWIW, 18.x gets branched on Tuesday, and I’d love to have this issue fixed there (not necessarily in the first RC, but at least by the first stable release). Does changing the definition of BLR_BTI make it less backportable (especially if the fix lands after the branch), rather than applying this fix first and looking into changing the definition later?

**Comment by DavidSpickett** [comment]
I think I'd prefer to land this first regardless of whether I do Eli's suggestion, to have a solid foundation to work from.

On Monday I will looking into changing `BLR_BTI`, so we can know the trade-offs before Tuesday's deadline.

**Comment by mstorsjo** [comment]
> I think I'd prefer to land this first regardless of whether I do Eli's suggestion, to have a solid foundation to work from.
> 
> On Monday I will looking into changing `BLR_BTI`, so we can know the trade-offs before Tuesday's deadline.

Thanks, that sounds like a very reasonable plan!

**Comment by DavidSpickett** [comment]
> Is there some reason we can't just change the definition of BLR_BTI so it takes the same operands as BLR? Defining it to take different operands, then rewriting them to the form we want, seems like it's more complicated than necessary.

I think I see what you mean. We don't have custom lowering code for `BL` and `BLR` so why would we need it for these pseudo instructions.

We select how we're going to lower the calls in `AArch64CallLowering::lowerCall`. In there there is a comment:
```
  // Create a temporarily-floating call instruction so we can add the implicit
  // uses of arg registers.
```
Which is exactly what I'm doing here, and RVMARKER does currently. But I cannot see where the arg registers are actually added.

It must happen somewhere otherwise the normal branches wouldn't work., looking for something along the lines of `if known branch types copy....`.

**Comment by DavidSpickett** [comment]
But given my track record on this fix, I think the best way to proceed is to land this for 18 and I'll continue to look for a better solution on trunk.

**Review by efriedma-quic — APPROVED** [review]
Sure, we can just do this for now.  LGTM

**Comment by DavidSpickett** [comment]
Windows failure is `Driver/linker-wrapper.c` which is unrelated (fixed since this PR was posted I think), so going ahead with landing this.

**Pull request merged**
