### PR TITLE
[ARM][NEON] Add constraint to vld2 Odd/Even Pseudo instructions.

### LINKED ISSUE #71763: [NEON] Wrong result of NEON intrinsic `vld2q_dup_p16` with the `-march=armv7-a` flag in CLANG-15.
According to the ARM documentation https://developer.arm.com/architectures/instruction-sets/intrinsics/vld2q_dup_p16, `vld2q_dup_p16` loads a 2-element structure from memory and replicates the structure to all the lanes of the two SIMD&FP registers. 
The expected result should be as follows:
```
poly16_t a[2] = {1, 3};
poly16x8x2_t r = vld2q_dup_p16(a);
// The value of r {1, 1, 1, 1, 1, 1, 1, 1,
//                 3, 3, 3, 3, 3, 3, 3, 3}
```
However, the result of `vld2q_dup_p8` with the flags `-march=armv7-a` and `-mfpu=neon` in CLANG-15 is as follows:
```
poly16_t a[2] = {1, 3};
poly16x8x2_t r = vld2q_dup_p16(a);
// The value of r {3, 3, 3, 3, 1, 1, 1, 1,
//                 0, 0, 0, 0, 3, 3, 3, 3}
```
This issue also occurs in `vld2q_dup_p8`.

Reproduce problem: https://godbolt.org/z/6ETT3rjKo
CLANG version:
```
Debian clang version 15.0.7
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
```
Thank you for your reading.

### PR DESCRIPTION
**Pull request by AlfieRichardsArm**
This ensures the odd/even pseudo instructions are allocated to the same register range.

This fixes #71763

### CODE REVIEW

**Comment by efriedma-quic** [comment]
Why does the original code have special cases for vld2dup?  Looking at https://reviews.llvm.org/D48439, it had some special-cases specifically for VLD2... do you think the special-cases were just working around the bug in the definition of the pseudo-instruction?

Can we come up with better names for TableGen classes, so it's more clear how they're different from each other?  In particular, the important thing isn't the constraint itself; it's whether or not there's an input register.

**Comment by AlfieRichardsArm** [comment]
Caveat that I'm relatively new to LLVM work and this code base.

There are multiple reasons for the special cases IMO and none of them bugs (but maybe outdated design choices). The encoding for VLDQQPseudo is intended to be more general than for the Q/QQQQ Pseudos as it is used in more cases, but that leads to some extra complexity and not being able to use it in this case.

In this case I think that VLD2DUPq8OddPseudo and VLD2DUPq8EvenPseudo have this need for glue between them that doesn't fit into the abstractions in VLDQQPseudo.

I am happy to rename, however I don't follow your point about the input register. By my interpretation the "input" register is there solely to allow the constraint that Odd and Even use the same output register range?

**Comment by davemgreen** [comment]
Could you add the testcase from https://godbolt.org/z/hevqGKfqj, or ideally change the arm-vlddup.ll test (and maybe vlddup-update.ll too), to have a hard-float calling convention and use update_llc_test_checks to generate the check lines? I think that should show the same issue. Is it possible to test the other variants? They don't have even pairs?

**Comment by AlfieRichardsArm** [comment]
I have updated the tests as suggested

I checked and the variants like `VLDQQWBfixedPseudoConstrained` with `VLD2DUPq32OddPseudoWB_fixed` are tested in `vlddup-update.ll` if that was what you meant?

**Comment by AlfieRichardsArm** [comment]
I believe only the odd variants have the WB variant as it is constraining the input register which is the same for both, so only one constraint is needed.

**Comment by efriedma-quic** [comment]
> By my interpretation the "input" register is there solely to allow the constraint that Odd and Even use the same output register range?

You have two pseudo-instructions: the first one writes to the low half of a pair of Q registers, the second writes to the high half of a pair of Q registers.  So each half of the pair is an "insert element" operation, which takes two vectors as input, and writes into half of each of them.  (The expansion ends up referring to D registers, not Q registers, but that's not relevant to how we treat them when they're still pseudos.)

If you think about it that way, each pseudo-instruction obviously has two inputs: the address, and the pair of vectors we're inserting into.

**Comment by AlfieRichardsArm** [comment]
@efriedma-quic Ah yes I think I see your point. My view was that `$dst` value in both was where the insertion is happening and the `$src` register is only there to facilitate for the Odd and Even instructions to use the same destination range. 

But it is more natural to view it as `VLDQQPseudoConstrained` has `$src` input which then sets the `$dst` output? 

So in this understanding a name such as `VLDQQPseudoInputDST` may be better?

**Comment by efriedma-quic** [comment]
That name seems okay.

**Comment by AlfieRichardsArm** [comment]
Ping

**Review by davemgreen — COMMENTED** [review]
I think this LGTM, thanks.

**Pull request merged**
