### PR TITLE
Improve clang-format-diff help output

### PR DESCRIPTION
**Pull request by serge-sans-paille**
It is quite common to symlink clang-format-diff.py to clang-format-diff, and in that case the help output still refers to the .py version. Compute it instead to work in both setup.

### CODE REVIEW

**Comment by owenca** [comment]
See below. Seems it's already working as expected without this patch.
```
$ clang-format -version
clang-format version 17.0.5
$ clang-format-diff.py foo
usage: clang-format-diff.py [-h] [-i] [-p NUM] [-regex PATTERN] [-iregex PATTERN]
                            [-sort-includes] [-v] [-style STYLE]
                            [-fallback-style FALLBACK_STYLE] [-binary BINARY]
clang-format-diff.py: error: unrecognized arguments: foo
$ ln -s clang-format-diff.py cfd
$ cfd foo
usage: cfd [-h] [-i] [-p NUM] [-regex PATTERN] [-iregex PATTERN] [-sort-includes] [-v]
           [-style STYLE] [-fallback-style FALLBACK_STYLE] [-binary BINARY]
cfd: error: unrecognized arguments: foo
```

**Comment by serge-sans-paille** [comment]
> See below. Seems it's already working as expected without this patch.
> 
> ```
> $ clang-format -version
> clang-format version 17.0.5
> $ clang-format-diff.py foo
> usage: clang-format-diff.py [-h] [-i] [-p NUM] [-regex PATTERN] [-iregex PATTERN]
>                             [-sort-includes] [-v] [-style STYLE]
>                             [-fallback-style FALLBACK_STYLE] [-binary BINARY]
> clang-format-diff.py: error: unrecognized arguments: foo
> $ ln -s clang-format-diff.py cfd
> $ cfd foo
> usage: cfd [-h] [-i] [-p NUM] [-regex PATTERN] [-iregex PATTERN] [-sort-includes] [-v]
>            [-style STYLE] [-fallback-style FALLBACK_STYLE] [-binary BINARY]
> cfd: error: unrecognized arguments: foo
> ```

try with `clang-format-diff.py --help` vs `cfd --help` ;-)

**Comment by owenca** [comment]
Please open a github issue to show us what you are trying to accomplish and reference the issue number here.

**Comment by serge-sans-paille** [comment]
@owenca bug opened as #73635 and commit message updated to link to it.

**Review by owenca — APPROVED** [review]

**Pull request merged**
