### PR TITLE
[DAG] SimplifyDemandedBits - if we're just demanding a single shifted down sign bit, try to shift down the MSB directly

### PR DESCRIPTION
**Pull request by RKSimon**
If we're only demanding the LSB of a SRL node and that is shifting down an extended sign bit, see if we can change the SRL to shift down the MSB directly.

These patterns can occur during legalisation when we've sign extended to a wider type but the SRL is still shifting from the subreg.

There's potentially a more general fold we could do here if we're just shifting a block of sign bits, but we only seem to currently benefit from demanding just the MSB, as this is a pretty common pattern for other folds.

Fixes the remaining regression in #112588

### CODE REVIEW

**Comment by jayfoad** [comment]
Does this only help when the result of the SRL is actually ANDed with 1, so changing it to SRL by 31 allows you to remove the AND? If so, could you implement this as a simplification of the AND instead of a demanded bits thing?

**Comment by RKSimon** [comment]
Yes at the moment its always the `(and (srl X, C), 1)` pattern AFAICT - if we're not going to try to extend this in the future then we can move it DAGCombine

**Comment by jayfoad** [comment]
> Yes at the moment its always the `(and (srl X, C), 1)` pattern AFAICT - if we're not going to try to extend this in the future then we can move it DAGCombine

I'm struggling to think of any other pattern where SRL by 31 would be better than SRL by a different constant.

**Comment by RKSimon** [comment]
> > Yes at the moment its always the `(and (srl X, C), 1)` pattern AFAICT - if we're not going to try to extend this in the future then we can move it DAGCombine
> 
> I'm struggling to think of any other pattern where SRL by 31 would be better than SRL by a different constant.

Well, the SRL amount would be adjusted depending on the signbit and demandedbit counts - but I can't think of many patterns that would benefit (maybe mask generation from vector comparison results?).

**Pull request closed without merging**
