### PR TITLE
[LTO] Avoid assert fail on failed pass plugin load

### PR DESCRIPTION
**Pull request by jdenny-ornl**
Without this patch, passing -load-pass-plugin=nonexistent.so to llvm-lto2 produces a backtrace because LTOBackend.cpp does not handle the error correctly:

```
Failed to load passes from 'nonexistant.so'. Request ignored.
Expected<T> must be checked before access or destruction.
Unchecked Expected<T> contained error:
Could not load library 'nonexistant.so': nonexistant.so: cannot open shared object file: No such file or directoryPLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
```

Any tool using `lto::Config::PassPlugins` should suffer similarly.

Based on the message "Request ignored" and the continue statement, the intention was apparently to continue on failure to load a plugin. However, no one appears to rely on that behavior now given that it crashes instead, and terminating is consistent with opt.

### CODE REVIEW

**Review by jhuber6 — APPROVED** [review]
Good catch, we definitely need to consume the error in the failure state for proper behavior.

I wonder if we could make a lint for this in the LLVM codebase.

**Review by serge-sans-paille — COMMENTED** [review]
I'm not 100% sure we shouldn't stop the whole pipeline when the module fails to load. The difference in behavior between opt and llvm-lto2 is probably not a good thing :-/

**Comment by jdenny-ornl** [comment]
> I'm not 100% sure we shouldn't stop the whole pipeline when the module fails to load. The difference in behavior between opt and llvm-lto2 is probably not a good thing :-/

I'm happy to change it to be like opt.  After all, stopping on failure to load a plugin is what lto already does without this patch (but it's a crash).

**Comment by jhuber6** [comment]
Yeah, crashing on an unhandled error is definitely incorrect, whether or not it should be ignored is a different issue but I can see the rationale. I think `clang` stops as well if `-fpass-plugin=` doesn't point to a valid library so there's lots of precedent.

**Comment by jdenny-ornl** [comment]
I just mean to point out that apparently no one has been too dependent on its inability to continue given that it currently crashes.

**Review by jhuber6 — APPROVED** [review]

**Review by serge-sans-paille — APPROVED** [review]
LGTM now, thanks!

**Comment by jdenny-ornl** [comment]
Thanks for the reviews.

**Comment by MaskRay** [comment]
LGTM. Ideally LTOBackend.cpp should have a better error reporting mechanism than we do not need so many `report_fatal_error`

**Comment by jdenny-ornl** [comment]
> LLVM Buildbot has detected a new failure on builder `lldb-aarch64-ubuntu` running on `linaro-lldb-aarch64-ubuntu` while building `llvm` at step 6 "test".

This one blamed only me, but it looks irrelevant, and it passed on the next build.

**Pull request merged**
