### PR TITLE
AMDGPU: Make s_wait_samplecnt(_bvhcnt) dependent on hasImageInsts, NFC

### PR DESCRIPTION
**Pull request by changpeng**

### CODE REVIEW

**Review by jayfoad — COMMENTED** [review]
This is really stretching the definition of "image instruction", but I guess it's OK.

**Comment by arsenm** [comment]
> This is really stretching the definition of "image instruction", but I guess it's OK.

I don't see how it makes sense at all?

**Comment by jayfoad** [comment]
> > This is really stretching the definition of "image instruction", but I guess it's OK.
> 
> I don't see how it makes sense at all?

samplecnt is only used by image-instructions-with-sampler, so I guess it would not exist on an ASIC that does not have any image instructions.

**Review by rampitec — APPROVED** [review]

**Comment by rampitec** [comment]
> > > This is really stretching the definition of "image instruction", but I guess it's OK.
> > 
> > 
> > I don't see how it makes sense at all?
> 
> samplecnt is only used by image-instructions-with-sampler, so I guess it would not exist on an ASIC that does not have any image instructions.

Yes.

**Pull request merged**
