### PR TITLE
[DWARF] Emit a minimal line-table for totally empty functions

### PR DESCRIPTION
**Pull request by jmorse**
(Ignore base two patches, this PR is about the tip-most commit, b72309c2de3a).

If a function has no source locations in it at all, `emitInitialLocDirective` won't fire at all, and no line table will be produced for the function. This seems pretty reasonable given that there's no data to produce; on the other hand given that there's a DISubprogram available, we can throw the end user a bone and cover the function with the scope-line source-location. This means if there's a crash then they can localise to that function, or put a breakpoint on that function. The new test, and the modified XCOFF test, both exercise this code path.

Does this scenario actually happen in real-life? I don't have a real example of it, but almost anything can come out of heavy LTOing. At the very least this will provide a safety-net, even if it occurs vanishingly infrequently.

### CODE REVIEW

**Comment by dwblaikie** [comment]
Yeah, I guess - I don't mind the general concept, fwiw.

**Review by chenzheng1030 — APPROVED** [review]
The change to XCOFF case and the debug line table LGTM. Better to wait for another look : )

**Review by OCHyams — APPROVED** [review]
LGTM too

**Comment by jmorse** [comment]
Rebased, then discovered via another test that the scope-line is going to be terminated by the second basic block in the program. See the new additions to the test I'm adding, we'll by default put in an explicit line-zero location, specifically to avoid the scope-line running through the whole program.

I'd missed that this would happen; I still feel it'd be worthwhile to emit this scope line on the entry block, at the very least so that people can set a breakpoint on the function. (Re-requesting review in case this shifts peoples opinions).

**Review by chenzheng1030 — APPROVED** [review]

**Pull request merged**
