### PR TITLE
[llvm-config] Make llvm-config --system-libs obey LLVM_USE_STATIC_ZSTD.

### PR DESCRIPTION
**Pull request by khuey**
LLVM's build system does the right thing but LLVM_SYSTEM_LIBS ends up containing the shared library. Emit the static library instead when appropriate.

CC @MaskRay since zstd compression is relevant to his interests.

### CODE REVIEW

**Comment by khuey** [comment]
Bump. @MaskRay if you don't have time to look at this yourself can you at least refer it to someone who does? I can't set reviewers on this PR.

**Comment by MaskRay** [comment]
Sorry. I receive a lot of review requests. When I am not added as a reviewer, I can easily miss a PR that requires my attention... Weekly ping is fine.

> LLVM's build system does the right thing but LLVM_SYSTEM_LIBS ends up containing the shared library. Emit the static library instead when appropriate.

Can you edit the description to show `llvm-config --system-libs` output differences? This would help folks who are less familiar with CMake (like me).

I checked that this patch does change the output of 
`llvm-config --system-libs`

**Review by MaskRay — APPROVED** [review]

**Review by mgorny — APPROVED** [review]
I don't see anything wrong with it, though I really hate that we have to do things like that.

**Comment by khuey** [comment]
Rebased and updated the commit message per @MaskRay's request.

**Comment by MaskRay** [comment]
> Rebased and updated the commit message per @MaskRay's request.

Thx.

GitHub "Squash and merge" populates the default commit message with the content of the first comment.
So you just need to edit the description. The commit messages are ignored.

**Pull request merged**
