### PR TITLE
[lldb][DWARFASTParserClang] Check DW_AT_declaration to determine static data members

### LINKED ISSUE #68135: [lldb][Expression] Printing union with self-referencing member field crashes lldb
```
//struct Attrs // << this works                 
union Attrs // << this crashes                  
{                                                                  
    static const Attrs regular;                 
};                                                                 
                                                                   
const Attrs Attrs::regular{};
                                                                   
int main() {                                                       
    Attrs d;                                    
    return 0;                                                      
}                                                                  
```

```
clang++ main.cpp -g -O0 -std=c++2a
./bin/lldb a.out -o "br se -p return -X main" -o run -o "frame var d"
```
(on llvm.org lldb build at commit `0bfaed8c612705cfa8c5382d26d8089a0a26386b`)

This will infinitely recurse in `ASTContext::getASTRecordLayout`. Possibly the same crash as:
* https://github.com/llvm/llvm-project/issues/43604
* https://github.com/llvm/llvm-project/issues/63667
* https://github.com/llvm/llvm-project/issues/64628
* https://github.com/llvm/llvm-project/issues/66335

### PR DESCRIPTION
**Pull request by Michael137**
**Background**

Prior to DWARFv4, there was no clear normative text on how to handle static data members. Non-normative text suggested that compilers should use `DW_AT_external` to mark static data members of structrues/unions. Clang does this consistently. However, GCC doesn't, e.g., when the structure/union is in an anonymous namespace (which is C++ standard conformant). Additionally, GCC never emits `DW_AT_data_member_location`s for union members (regardless of storage linkage and storage duration).

Since DWARFv5 (issue 161118.1), static data members get emitted as `DW_TAG_variable`.

LLDB used to differentiate between static and non-static members by checking the `DW_AT_external` flag and the absence of `DW_AT_data_member_location`. With [D18008](https://reviews.llvm.org/D18008) LLDB started to pretend that union members always have a `0` `DW_AT_data_member_location` by default (because GCC never emits these locations).

In [D124409](https://reviews.llvm.org/D124409) LLDB stopped checking the `DW_AT_external` flag to account for the case where GCC doesn't emit the flag for types in anonymous namespaces; instead we only check for presence of `DW_AT_data_member_location`s.

The combination of these changes then meant that LLDB would never correctly detect that a union has static data members.

**Solution**

Instead of unconditionally initializing the `member_byte_offset` to `0` specifically for union members, this patch proposes to check for both the absence of `DW_AT_data_member_location` and `DW_AT_declaration`, which consistently gets emitted for static data members on GCC and Clang.

We initialize the `member_byte_offset` to `0` anyway if we determine it wasn't a static. So removing the special case for unions makes this code simpler to reason about.

Long-term, we should just use DWARFv5's new representation for static data members.

Fixes #68135

### CODE REVIEW

**Comment by Michael137** [comment]
Alternatively, we could start checking `DW_AT_external` again, at the cost of not supporting some GCC cases pre-DWARFv5

**Review by adrian-prantl — APPROVED** [review]

**Comment by antmox** [comment]
Hello! It looks like this broke lldb-aarch64-windows bot:
https://lab.llvm.org/buildbot/#/builders/219/builds/6130
Could you please look at this ?

**Comment by Michael137** [comment]
> Hello! It looks like this broke lldb-aarch64-windows bot: https://lab.llvm.org/buildbot/#/builders/219/builds/6130 Could you please look at this ?

Yup! Was in the process of fixing. I think we just skip this test on windows

**Comment by Michael137** [comment]
@antmox Addressed in https://github.com/llvm/llvm-project/pull/68408

**Pull request merged**
