### PR TITLE
[Clang][OpenMP] Fix the wrong transform of `num_teams` claused introduced in #99732

### PR DESCRIPTION
**Pull request by shiltian**

### CODE REVIEW

**Comment by shiltian** [comment]
* **#102716** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/102716?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shiltian and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by alexey-bataev — COMMENTED** [review]
A test is required

**Comment by shiltian** [comment]
> A test is required

I literally don't know how to test this TBH. I think our current OpenMP tests generally don't cover this at all.

**Comment by alexey-bataev** [comment]
> > A test is required
> 
> 
> 
> I literally don't know how to test this TBH. I think our current OpenMP tests generally don't cover this at all.

They do. To test this, you need to use clause in the template and check that template params successfully replaced upon instantiation.

**Comment by shiltian** [comment]
> > > A test is required
> > 
> > 
> > I literally don't know how to test this TBH. I think our current OpenMP tests generally don't cover this at all.
> 
> They do. To test this, you need to use clause in the template and check that template params successfully replaced upon instantiation.

Aha, good to know. Thanks. Will add tests.

**Review by alexey-bataev — APPROVED** [review]
LG

**Pull request merged**
