### PR TITLE
[GlobalISel] Add support for lowering byref attribute

### PR DESCRIPTION
**Pull request by darkbuck**

### CODE REVIEW

**Comment by darkbuck** [comment]
For test cases, I'd like to hear your suggestions.

**Comment by tschuett** [comment]
For reference:
https://github.com/llvm/llvm-project/pull/95429

**Review by arsenm — APPROVED** [review]

**Comment by arsenm** [comment]
> For test cases, I'd like to hear your suggestions.

Theoretically AMDGPU should need this for the GlobalISel kernel lowering path. I'd need to look to see how this was avoided

**Comment by spaits** [comment]
I would also like to see some tests, to see the PRs effect on the behavior. Otherwise it looks good to me.

When I have implemented the first phase of indirect parameter passing and did some debugging and I have recognized that in case of indirect parameter passing the `byRef` attribute of the flag is not set. I have also extended the `addFlagsUsingAttrFn` function to recognize the attribute for the debugging.

**Comment by tschuett** [comment]
Tests?

**Pull request merged**
