### PR TITLE
[HEXAGON] Inlining Division

### PR DESCRIPTION
**Pull request by quic-asaravan**
This patch inlines float division function calls for hexagon.

### CODE REVIEW

**Comment by quic-asaravan** [comment]
@SundeepKushwaha Can you review ?

**Comment by iajbar** [comment]
It looks good to me. Thanks Abinaya!

**Review by iajbar — APPROVED** [review]
It looks good to me.

**Comment by androm3da** [comment]
@iajbar does it make sense to cherry pick this change onto the `llvmorg-18.1.0` release branch?  Does this fix bugs or just improve codegen?

**Comment by quic-asaravan** [comment]
@androm3da The patch is a codegen improvement and doesn't fix any bugs.

**Pull request merged**
