### PR TITLE
[analyzer] Restore recognition of mutex methods

### PR DESCRIPTION
**Pull request by NagyDonat**
Before commit 705788c the checker alpha.unix.BlockInCriticalSection "recognized" the methods `std::mutex::lock` and `std::mutex::unlock` with an extremely trivial check that accepted any function (or method) named lock/unlock.

To avoid matching unrelated user-defined function, this was refined to a check that also requires the presence of "std" and "mutex" as distinct parts of the qualified name.

However, as #99628 reported, there are standard library implementations where some methods of `std::mutex` are inherited from an implementation detail base class and the new code wasn't able to recognize these methods, which led to emitting false positive reports.

As a workaround, this commit partially restores the old behavior by omitting the check for the class name.

In the future, it would be good to replace this hack with a solution which ensures that `CallDescription` understands inherited methods.

### CODE REVIEW

**Review by steakhal — APPROVED** [review]
LGTM.
Could you add a test case that would break in case we would regress?

**Review by steakhal — APPROVED** [review]
Let's merge this, and backport it into clang-19. I'll deal with that.

**Comment by NagyDonat** [comment]
> Let's merge this, and backport it into clang-19. I'll deal with that.

Thanks!

**Comment by steakhal** [comment]
Backport PR in https://github.com/llvm/llvm-project/pull/101651

**Pull request merged**
