### PR TITLE
[DAG] Extend the computeOverflowForSignedSub/computeOverflowForUnsignedSub implementations with ConstantRange

### PR DESCRIPTION
**Pull request by elhewaty**
- Add tests for computeOverflowFor*Sub functions
- extend the computeOverflowForSignedSub/computeOverflowForUnsignedSub implementations with ConstantRange

### CODE REVIEW

**Review by RKSimon — APPROVED** [review]
LGTM - thanks

**Comment by elhewaty** [comment]
@RKSimon Do you have more issues/projects I can work on?

**Comment by RKSimon** [comment]
> @RKSimon Do you have more issues/projects I can work on?

#66101 might be interesting - hopefully this can be addressed as a generic DAGCombine fold and not x86-specific

**Comment by elhewaty** [comment]
Will this be merged soon?

**Comment by ajarmusch** [comment]
This change seemed to have broken this build bot yesterday. 

https://gitlab.e4s.io/uo-public/llvm-sollve/-/pipelines/9388/

**Comment by RKSimon** [comment]
@ajarmusch Please can you provide any more information? I can't even find a reference to 9103b1d68dd231acf53a6e86c8b6cd0bef82cbe9 on the log

**Comment by elhewaty** [comment]
@RKSimon: I received this link by the mail yesterday:
https://lab.llvm.org/buildbot/#/builders/238/builds/5908

**Comment by RKSimon** [comment]
> @RKSimon: I received this link by the mail yesterday: https://lab.llvm.org/buildbot/#/builders/238/builds/5908

That was fixed by 632022e61c544280685763333685b4743f105f2e

**Comment by ajarmusch** [comment]
@RKSimon sure thing

the commit [632022e](https://github.com/llvm/llvm-project/commit/632022e61c544280685763333685b4743f105f2e) shows up in the [artifacts](https://gitlab.e4s.io/uo-public/llvm-sollve/-/jobs/222987/artifacts/file/artifacts/llvm-project-commit.txt)

**Comment by RKSimon** [comment]
632022e61c544280685763333685b4743f105f2e looks ok: https://alive2.llvm.org/ce/z/V33G3f

Please can you confirm why -lFortranRuntime is missing?

```console
FAILED: bin/external-hello-world 
: && /usr/local/llvm/16.0.6/bin/clang++ -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wno-deprecated-copy -Wno-string-conversion -Wno-ctad-maybe-unsupported -Wno-unused-command-line-argument -Wstring-conversion           -Wcovered-switch-default -Wno-nested-anon-types -O3 -DNDEBUG -Wl,-rpath-link,/home/gitlab-runner-sollve/builds/yP7whQwj9/0/uo-public/llvm-sollve/build/./lib  -Wl,--gc-sections tools/flang/examples/ExternalHelloWorld/CMakeFiles/external-hello-world.dir/external-hello.cpp.o -o bin/external-hello-world  -Wl,-rpath,"\$ORIGIN/../lib:"  -lpthread  -lFortranRuntime && :
/opt/rh/gcc-toolset-12/root/usr/lib/gcc/x86_64-redhat-linux/12/../../../../bin/ld: cannot find -lFortranRuntime: No such file or directory
```

**Comment by ajarmusch** [comment]
thanks for checking - I'll ask the CI admin

**Comment by RKSimon** [comment]
@ajarmusch Any update?

**Comment by ajarmusch** [comment]
It was a different commit that caused the failure. Trying to prevent another false blame

**Pull request merged**
