### PR TITLE
[SCEV,LAA] Introduce scoped SCEV, use in LAA computations (WIP).

### PR DESCRIPTION
**Pull request by fhahn**
Note that this patch at the moment is mostly an experiment, and I'd
really appreciate any early feedback.

The motivating use case for this is better reasoning about pointer
bounds in LoopAccessAnalysis. LAA creates a number of SCEV expressions
that only need to be valid in the scope of the loop and we know that the
address computations in the loop don't wrap. When we compute the SCEV
for a pointer in the last iteration, this frequently boils down to
Base + Offset, but the resulting SCEV at the moment cannot be marked as
<nuw>, as the flags for the SCEV expression must be valid in the whole
function.

A concrete example is @test_distance_positive_backwards, where I'd like
to prove that the 2 pointer ranges overlap. (the current code structure
in LAA isn't necessary ideal/finalized, I am mostly looking for feedback
on the SCEV side for now)

I'd like to provide a  way to create scoped SCEV expressions, which we
will only use the reason in the context of a loop.

This patch introduces a way to create SCEV commutative expressions that
are only valid for a loop scope. This is done by adding a ExprScope
member to SCEV which is used as additional pointer ID in the lookup
value of UniqueSCEVs. This should ensure that we only return 'scoped'
SCEVs, if the scope is set.

The idea is to keep scoped SCEVs separate from regular SCEVs, as in if
no scope is set, no returned SCEV expression can reference any scoped
expressions (can add assert to that effect I think). This should ensure
that regular SCEVs cannot be 'polluted' by information from scoped
SCEVs. Added some test cases to make sure the modified scoped SCEVs do
not interfere with already cached or later constructed SCEVs in
llvm/test/Analysis/LoopAccessAnalysis/scoped-scevs.ll

It's very likely that I am missing something here. In that case, any
suggestions on how to approach the problem differently?

### CODE REVIEW

**Comment by efriedma-quic** [comment]
When I've been thinking about flags in SCEV, I've been mostly considering modifying the flag representation itself: currently, flags have to be valid for the whole function, but we could add another form of flags that are only valid for users of a specific SCEV*. The primary problem with that is that SCEV canonicalization becomes less powerful: you can have two "equal" expressions that don't have the same flags.  To work around that, you'd need some fast way to get from a SCEV with user-flags to the corresponding SCEV without those flags.  Plus, you have two sets of flags, so reasoning about them becomes a bit harder. I think this is all solvable, but it's a pretty large change.

The alternative here is interesting: attach a scope to certain SCEVs, then you can modify their flags however you want, and nothing else ever sees those expressions.

It seems a bit dangerous to me to make the "scope" global per SCEV: scoped SCEVs could accidentally leak into contexts where you don't intend to use them (like the trip counts of loops).  I guess the opposite is also sort of dangerous, though: if you accidentally drop the scope, you can accidentally introduce flags onto unscoped SCEVs.

I'm not sure Loop* pointers reliably live long enough to avoid accidentally reusing a scope; maybe consider just using a counter.

**Comment by fhahn** [comment]
> It seems a bit dangerous to me to make the "scope" global per SCEV: scoped SCEVs could accidentally leak into contexts where you don't intend to use them (like the trip counts of loops). I guess the opposite is also sort of dangerous, though: if you accidentally drop the scope, you can accidentally introduce flags onto unscoped SCEVs.

Yes, I think the main ones are computing new trip counts when a scope is set or `setNoWrapFlags()` to strengthen wrap flags while building other SCEVs being used when a scope is set. I'll see if we can add asserts to guard against those cases.

**Comment by nikic** [comment]
The current handling of SCEV flags is a pretty general issue, and the approach used here will only be usable in limited circumstances -- ideally, we would want to be able to preserve flags when going from IR to SCEV, but I don't think that the scope-based approach here will enable that (or at least, not to a significant degree and not without complications).

The general approach I would consider is to replace our current `const SCEV *` pointers with `SCEVUse`, where the low bits are used to store no-wrap flags for a specific use of the expression.

**Comment by fhahn** [comment]
> The current handling of SCEV flags is a pretty general issue, and the approach used here will only be usable in limited circumstances -- ideally, we would want to be able to preserve flags when going from IR to SCEV, but I don't think that the scope-based approach here will enable that (or at least, not to a significant degree and not without complications).
> 

Fair point, I also spent a bit more time to see if I would be feasible to prevent leakage but it proved quite tricky.

> The general approach I would consider is to replace our current `const SCEV *` pointers with `SCEVUse`, where the low bits are used to store no-wrap flags for a specific use of the expression.

Yeah that should also cover my use case here. I'll try to sketch a prototype

**Comment by fhahn** [comment]
> > The general approach I would consider is to replace our current `const SCEV *` pointers with `SCEVUse`, where the low bits are used to store no-wrap flags for a specific use of the expression.
> 
> Yeah that should also cover my use case here. I'll try to sketch a prototype

Sketched in https://github.com/llvm/llvm-project/pull/91961 with 2 additional linked PRs to use SCEVUse. @nikic Is that along the lines of what you had in mind?

**Pull request closed without merging**
