### PR TITLE
[Flang][MLIR][OpenMP] Remove the early outlining interface

### PR DESCRIPTION
**Pull request by skatrak**
After the removal of the OpenMP early outlining MLIR pass in #67319, the `EarlyOutliningInterface` stopped doing any useful work. It used to be necessary to tie the name of the function from which a target region was outlined to that new function, so it would be used when translating to LLVM IR in place of the outlined function's name.

This is not necessary anymore, so this patch removes all references to this interface and uses of the `omp.outline_parent_name` discardable attribute in tests.

### CODE REVIEW

**Review by kiranchandramohan — APPROVED** [review]
OK with me. Please wait for @agozillon or @TIFitis.

**Review by agozillon — APPROVED** [review]
This change LGTM.

**Review by TIFitis — APPROVED** [review]
LGTM :)

**Comment by skatrak** [comment]
Thank you for giving this patch a look. Merging now, since premerge test failures look unrelated.

**Pull request merged**
