### PR TITLE
[WebAssembly] Change the default linker for `wasm32-wasip2`

### PR DESCRIPTION
**Pull request by alexcrichton**
This commit changes the default linker in the WebAssembly toolchain for the `wasm32-wasip2` target. This target is being added to the WebAssembly/wasi-sdk and WebAssembly/wasi-libc projects to target the Component Model by default, in contrast with the preexisting `wasm32-wasi` target (in the process of being renamed to `wasm32-wasip1`) which outputs a core WebAssembly module by default.

The `wasm-component-ld` project currently lives in my GitHub account at https://github.com/alexcrichton/wasm-component-ld and isn't necessarily "official" yet, but it's expected to continue to evolve as the `wasm32-wasip2` target continues to shape up and evolve.

### CODE REVIEW

**Comment by alexcrichton** [comment]
cc @sunfishcode and @sbc100

**Review by sbc100 — COMMENTED** [review]
Does wasm-component-ld accept any other input types other than the ones that wasm-ld accepts?

Does wasm-component-ld call wasm-ld internally?

Do we expect clang users to be building compound components using a single clang command?  i.e. will they be somehow supplying input files that describe how the componend links?   Would it make more sense to have clang default to building core modules and have the component creation be a higher level thing built on top clang outputs?

**Comment by sbc100** [comment]
Regarding WebAssembly/wasi-sdk and WebAssembly/wasi-libc, is there any reason why simple programs wouldn't be core modules?   Won't most C/C++ programs still be build-able as just core modules?

**Comment by alexcrichton** [comment]
Currently it accepts no extra inputs, but in the future I'd expect that it'll grow an option or two of its own. Currently it [hand-codes the list of options to forward to `wasm-ld`](https://github.com/alexcrichton/wasm-component-ld/blob/2f6106e395e2db99a8bb0524088d08bb6964997a/src/main.rs#L23-L53) which I'm sure will need updates over time, but that should be ok. And yes, the purpose of `wasm-component-ld` is twofold:

1. First it invokes `wasm-ld` internally, producing the core wasm that's expected today.
2. Next it invokes the "componentization process" which activates some Rust crates that converts this output core wasm module into a component.

In step (2) it's using component type information smuggled through LLVM/wasm-ld through custom sections to create the final output component.

> Do we expect clang users to be building compound components using a single clang command?

If by compound you mean linking multiple components internally, then no. The intention is that `wasm32-wasip2` outputs a component but internally it's "just" a core wasm module. The next phase of composing components together we've got other tooling for, and that's intended to be outside the scope of individual language toolchains. (e.g. in theory composition works the same regardless of source language)

> Would it make more sense to have clang default to building core modules and have the component creation be a higher level thing built on top clang outputs?

That's actually what we currently have to day with converting `wasm32-wasip1` outputs into components. The purpose of `wasm32-wasip2`, however, is that core wasms are not natively usable as-is because WASI APIs are defined at the level of the component model, not core wasm. There is of course definitions for core wasm using the canonical ABI, but that's not the focus of WASI nowdays.

I do plan on having a flag (also answering the question about wasm-component-ld-specific-flags) to not emit a component and instead skip the componentization step. This step could also be done by using `-fuse-ld=wasm-ld` (or the equivalent thereof) to just switch the default linker back to `wasm-ld`.

> Regarding WebAssembly/wasi-sdk and WebAssembly/wasi-libc, is there any reason why simple programs wouldn't be core modules? Won't most C/C++ programs still be build-able as just core modules?

Yep, they'll all still be buildable as core modules (as that's the internals of a component anyway, a big thing produced by LLVM). With the p2 target though the thinking is that components are the default output, not core wasm modules.

---

Another future feature on the theoretical roadmap for wasm-component-ld is that Joel has componentize-py built on "dynamic linking" of a sort which gets `dlopen` working enough for Python to open its native extensions. This is all built on the Emscripten dynamic linking model and a component packages that all up into a single component where the dynamic libraries are statically known at build time. This is all wrapped up in `wasm-tools component link` and is something I'd like to also automatically bake in to `wasm-component-ld` so building that style of component is much easier.

**Comment by sbc100** [comment]
I see, so `wasm-ld` builds "core module + metadata" and then `wasm-component-ld` takes that metadata and uses it to wrap the core module into a component (with exactly that one core module inside of it). 

So the core module + metadata is kind of isomorphic with that single-core-module-component?

**Comment by sbc100** [comment]
> Currently it accepts no extra inputs, but in the future I'd expect that it'll grow an option or two of its own

I was more asking about whether the file types is accepts are anything more than object files and libraries.  i.e. can you pass other core modules and have wasm-component-ld build a component that contains more than one core module?

Also, can you say more about the metadata that is being using to drive wasm-componenet-ld?    If the core module is all based on canonical ABI what extra metdata is needed/planned?

**Comment by alexcrichton** [comment]
> So the core module + metadata is kind of isomorphic with that single-core-module-component?

Sort of and sort of not. At a high level you're correct, but at a technical level this isn't correct. The subtle differences are:

* Most wasm binaries today using WASI probably use `wasi_snapshot_preview1` imports. That means they need an "adapter" to switch to to WASIp2-based imports. That adapter is a core wasm which is currently baked into `wasm-component-ld` (see the adapters in [this folder](https://github.com/alexcrichton/wasm-component-ld/tree/main/src))
* Due to the way components and lifting and lowering works many imports need a "shim". For example in the component model when you "lower" a function from a component function to a core function you need to specify a linear memory. A linear memory isn't available until you instantiate the core module, but the core module needs the lowered imports to be instantiated. To break this cycle we introduce a shim wasm module which uses `call_indirect` through a table for its exports, so that's used to pass in as imports when instantiating the main module, and then after the main module is instantiated we instantiate another shim module that fills in the table.

Going from core module + metadata into a component is a pretty nontrivial operation, so the raw output of `wasm-ld` (module + metadata) isn't suitable as an intermediate artifact for components. 

> I was more asking about whether the file types is accepts are anything more than object files and libraries. i.e. can you pass other core modules and have wasm-component-ld build a component that contains more than one core module?


Ah sory I misunderstood! Currently wasm-component-ld takes no other inputs and it assumes everything goes into `wasm-ld`. In the future for the dynamic linking case above it may start taking in `*.wasm` binaries compiled as shared libraries to bundle and/or refer to in the output component, but that's in the future. That means that at this time wasm-component-ld will always build a component with a single "main module", e.g. the one from `wasm-ld`.

> Also, can you say more about the metadata that is being using to drive wasm-componenet-ld? If the core module is all based on canonical ABI what extra metdata is needed/planned?

Certainly! The canonical ABI gives the ability to say that for any component model function type it corresponds to a particular core wasm function type. That operation is not reversible, though, you can't go from core wasm back to the component model function type. Thus the metadata carries along this information. That way the componentization process draws a mapping from component model import/export to core wasm import/export and then can synthesize the right type in the component binary format.

The short answer to your question, though, is `wasm-tools component wit ./my-wit-files --wasm`. That output blob, which is itself a component but only with type information, is embedded in core wasm. Put another way we start with WIT files, then those are converted into their binary format as a component with only types, that gets fed through LLVM/wasm-ld, then on the other end we deserialize the component-with-type-information, turn it back into WIT, and then make the real component.

**Comment by alexcrichton** [comment]
ping @sbc100, happy to answer any more questions if you have them! 

I was tentatively hoping this could get backported to an 18.1.x release so we could get a wasi-sdk release with p1/p2/etc

**Review by sbc100 — APPROVED** [review]

**Comment by alexcrichton** [comment]
At @sunfishcode's request I've pushed up a second commit which pass the path to `wasm-ld` to `wasm-component-ld`, and in testing it I also added the ability for `-fuse-ld=lld` to explicitly request that `wasm-ld` is used, regardless of target.

**Review by sunfishcode — APPROVED** [review]
Looks good!

**Comment by sunfishcode** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/d66121d74a458e098511b9de920d815440acaa1b

**Comment by TerrorJack** [comment]
@alexcrichton This is breaking `wasi-sdk` build with:

```
/workspace/wasi-sdk/build/install/opt/wasi-sdk/bin/clang --target=wasm32-wasip2 -nodefaultlibs -shared --sysroot=/workspace/wasi-sdk/build/install/opt/wasi-sdk/share/wasi-sysroot \
-o /workspace/wasi-sdk/build/install/opt/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasip2/libc.so -Wl,--whole-archive build/wasm32-wasip2/libc.so.a -Wl,--no-whole-archive /workspace/wasi-sdk/build/install/opt/wasi-sdk/lib/clang/19/lib/wasi/libclang_rt.builtins-wasm32.a
error: unexpected argument '--entry' found

  tip: a similar argument exists: '--no-entry'

Usage: wasm-component-ld -o <OUTPUT> --wasm-ld-path <WASM_LD_PATH> <--export <EXPORT>|-z <Z_OPTS>|--stack-first|--allow-undefined|--fatal-warnings|--no-demangle|--gc-sections|-O <OPTIMIZE>|-L <LINK_PATH>|-l <LIBRARIES>|--no-entry|-m <TARGET_EMULATION>|--strip-all|OBJECTS>

For more information, try '--help'.
clang: error: linker command failed with exit code 2 (use -v to see invocation)
make[1]: *** [Makefile:569: /workspace/wasi-sdk/build/install/opt/wasi-sdk/share/wasi-sysroot/lib/wasm32-wasip2/libc.so] Error 2
make[1]: Leaving directory '/workspace/wasi-sdk/src/wasi-libc'
make: *** [Makefile:142: build/wasi-libc.BUILT] Error 2
```

**Comment by justdan96** [comment]
@alexcrichton Not sure if you've seen but this has been released as part of LLVM 18.1.2: https://github.com/llvm/llvm-project/tree/llvmorg-18.1.2/clang/lib/Driver/ToolChains

**Comment by justdan96** [comment]
No problem, I have wasi-sdk all working in a Docker container now with your latest version of wasm-component-ld so I should be thanking you!

**Pull request merged**
