### PR TITLE
[AMDGPU][True16][MC] true16 for v_minmax/maxmin_f16

### PR DESCRIPTION
**Pull request by broxigarchen**
Support true16 format for v_minmax/maxmin_f16 in MC.

Since we are replacing `v_minmax/maxmin_f16` to `v_minmax/maxmin_f16_t16 / v_minmax/maxmin_f16_fake16` in Post-GFX11, have to update the CodeGen pattern for `v_minmax/maxmin_f16` to get CodeGen test passing.

### CODE REVIEW

**Review by arsenm — APPROVED** [review]

**Comment by broxigarchen** [comment]
rebased

**Comment by broxigarchen** [comment]
CI failure is not related to this patch

**Comment by jayfoad** [comment]
Hi @broxigarchen this is breaking compilation on GFX12 for us. Can you please fix or revert? Test case:
```
; RUN: llc -mtriple=amdgcn -mcpu=gfx1200 < %s
define half @test(half %arg) {
  %i = call half @llvm.minnum.f16(half %arg, half 0xH0000)
  %i1 = call half @llvm.maxnum.f16(half %i, half 0xH0000)
  ret half %i1
}
```
I get:
```
llc: /home/jayfoad2/git/llvm-project/llvm/include/llvm/MC/MCInstrInfo.h:64: const MCInstrDesc &llvm::MCInstrInfo::get(unsigned int) const: Assertion `Opcode < NumOpcodes && "Invalid opcode!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
```

**Comment by broxigarchen** [comment]
> Hi @broxigarchen this is breaking compilation on GFX12 for us. Can you please fix or revert? Test case:
> 
> ```
> ; RUN: llc -mtriple=amdgcn -mcpu=gfx1200 < %s
> define half @test(half %arg) {
>   %i = call half @llvm.minnum.f16(half %arg, half 0xH0000)
>   %i1 = call half @llvm.maxnum.f16(half %i, half 0xH0000)
>   ret half %i1
> }
> ```
> 
> I get:
> 
> ```
> llc: /home/jayfoad2/git/llvm-project/llvm/include/llvm/MC/MCInstrInfo.h:64: const MCInstrDesc &llvm::MCInstrInfo::get(unsigned int) const: Assertion `Opcode < NumOpcodes && "Invalid opcode!"' failed.
> PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
> ```

Revert this commit here https://github.com/llvm/llvm-project/pull/120594

**Pull request merged**
