### PR TITLE
Make update_any_test_check.py script accepting @listfile CL argument.

### PR DESCRIPTION
**Pull request by vpykhtin**
Usage: `update_any_test_check.py @my_list_of_tests`
where my_list_of_tests is a file containing list of tests to update.

Sorry for possible inefficiencies I'm a chatgpt powered python newbie.

### CODE REVIEW

**Review by nhaehnle — COMMENTED** [review]
Please do take a look at the formatting complaint.

Is their precedent somewhere for using the '@' as a prefix in this way? Seems a bit unorthodox to me. Perhaps because a more "CLI idiomatic" way of achieving the same thing is to just run something like `cat yourfile | xargs update_any_test_checks.py` or `update_any_test_checks.py $(cat yourfile)`.

**Comment by tru** [comment]
> Is their precedent somewhere for using the '@' as a prefix in this way? Seems a bit unorthodox to me.

This is handled by lld and clang as well. It's called response files there and is usually a way to work around issues with command line length.

**Comment by vpykhtin** [comment]
Thanks for the comments. We don't have CL length problem but it's sometimes convenient to have a separate file with a list of tests to proceed.

**Comment by nhaehnle** [comment]
Okay. Please address the formatting issues, the rest LGTM.

**Comment by vpykhtin** [comment]
Passed formatting check.

**Review by nhaehnle — APPROVED** [review]

**Pull request merged**
