### PR TITLE
[GitHub] Remove pr-subscriber-wait.py download

### PR DESCRIPTION
**Pull request by DavidSpickett**
This file and uses of it were removed in 64d5da60d437049548a752001c4081f65137ea47.

### CODE REVIEW

**Review by tstellar — APPROVED** [review]
Is the file still there too?

**Comment by boomanaiden154** [comment]
After seeing this patch, I was wondering why the job didn't just outright fail. Apparently curl doesn't return a non-zero exit code for HTTP requests that return a code other than 200.

**Comment by DavidSpickett** [comment]
> Apparently curl doesn't return a non-zero exit code for HTTP requests that return a code other than 200. 

If you happen to know the option to make curl fail earlier that would be a good change to make.

**Comment by tru** [comment]
`--fail` is the right one I think.

**Comment by DavidSpickett** [comment]
> If you happen to know the option to make curl fail earlier that would be a good change to make.

https://github.com/llvm/llvm-project/pull/72238

**Pull request merged**
