### PR TITLE
[mlir][linalg] Add quantized conv2d operator with FCHW,NCHW order

### PR DESCRIPTION
**Pull request by ubfx**
This patch adds a quantized version of the `linalg.conv2d_nchw_fchw` Op. This is the "channel-first" ordering typically used by PyTorch and others.

### CODE REVIEW

**Comment by ubfx** [comment]
For context: In torch-mlir, we currently have to use an additional transposition on weights and inits for all quantized convolutions. This is because we have no fitting quantized convolution op

https://github.com/llvm/torch-mlir/blob/5ce48dfacd971e5075786731bac2152ae855cab4/lib/Conversion/TorchToLinalg/Linear.cpp#L1165

**Review by MaheshRavishankar — COMMENTED** [review]
Needs some round trip tests, but apart from that looks ok to me.

**Comment by ubfx** [comment]
ping

**Review by stellaraccident — APPROVED** [review]

**Comment by EgorDuplensky** [comment]
@ubfx Just wondering, why the memory layout is expressed right in the name of linalg operation?
Shouldn't it be at least an attribute? Or do we need to express it at all? Can't we propagate layouts in scope of some extra passes?

**Comment by ubfx** [comment]
> @ubfx Just wondering, why the memory layout is expressed right in the name of linalg operation? Shouldn't it be at least an attribute? Or do we need to express it at all? Can't we propagate layouts in scope of some extra passes?

Yes I think the current solution (for all the conv ops in the dialect) isn't ideal and there have been a couple of suggestions and PRs to improve it, [e.g. by expressing layout in attributes](https://github.com/llvm/llvm-project/pull/117688) . Unfortunately, linalg seems to be where all of the individual interests collide which has lead to a certain degree of inertia, so I'm not sure whether fixing this is still actively worked on.

**Pull request merged**
