### PR TITLE
[sanitizer] Remove GetCurrentThread nullness checks from Allocate

### PR DESCRIPTION
**Pull request by MaskRay**
The nullness check is unreachable.

* For the main thead and pthread_create created threads, the `*Allocate` functions must be called after `*_current_thread` is set.
set.
* For threads created by Linux's `clone`, static TLS is either reused or
  set to a new value (CLONE_SETTLS).

Make this change for asan/msan and possibly extend the change to other
sanitizers. (asan supports many platforms and I am not 100% certain that
all platforms have the property.)

### CODE REVIEW

**Comment by vitalybuka** [comment]
> The `*Allocate` functions must be called after `*_current_thread` is set. Delete the nullness checks.

With static runtime.

With dynamic runtime, with late activation, it's not guaranteed, I guess?

**Comment by MaskRay** [comment]
> > The `*Allocate` functions must be called after `*_current_thread` is set. Delete the nullness checks.
> 
> With static runtime.
> 
> With dynamic runtime, with late activation, it's not guaranteed, I guess?

I've checked `start-deactivated.cpp`. In the `ASAN_OPTIONS=start_deactivated=1` mode, interceptors are still initialized.
As long as `DlsymAlloc::Use()` in the interceptor returns false and `__asan::Allocator::Allocate` is called, `GetCurrentThread()` guarantees a non-null value.

**Review by vitalybuka — APPROVED** [review]
Have you tried to run out large set of internal tests?

**Comment by MaskRay** [comment]
> Have you tried to run out large set of internal tests?

Finished the large set of tests. The results (with a lot of noise) look good

**Comment by cachemeifyoucan** [comment]
This breaks Darwin bots: https://green.lab.llvm.org/job/llvm.org/job/clang-stage1-RA/1753/

```
GTEST_OUTPUT=json:/Users/ec2-user/jenkins/workspace/llvm.org/clang-stage1-RA/clang-build/tools/clang/runtime/compiler-rt-bins/lib/asan/tests/X86_64HDarwinConfig/./Asan-x86_64h-calls-Noinst-Test-AddressSanitizer-Unit-90874-10-16.json GTEST_SHUFFLE=0 GTEST_TOTAL_SHARDS=16 GTEST_SHARD_INDEX=10 /Users/ec2-user/jenkins/workspace/llvm.org/clang-stage1-RA/clang-build/tools/clang/runtime/compiler-rt-bins/lib/asan/tests/X86_64HDarwinConfig/./Asan-x86_64h-calls-Noinst-Test
--

Note: This is test shard 11 of 16.
[==========] Running 1 test from 1 test suite.
[----------] Global test environment set-up.
[----------] 1 test from AddressSanitizer
[ RUN      ] AddressSanitizer.ThreadedMallocStressTest
AddressSanitizerAddressSanitizerAddressSanitizerAddressSanitizer:DEADLYSIGNAL
:DEADLYSIGNAL
:DEADLYSIGNAL
:DEADLYSIGNAL
=================================================================
==92755==ERROR: AddressSanitizer: SEGV on unknown address 0x000000005e40 (pc 0x00010fa7eff8 bp 0x7000043ca630 sp 0x7000043ca600 T-1)
==92755==The signal is caused by a READ memory access.
    <empty stack>

==92755==Register values:
rax = 0x0000000000005d70  rbx = 0x0000000000000017  rcx = 0x0000000000000008  rdx = 0x0000000000000020  
rdi = 0x000000010fbb5eb8  rsi = 0x00000000000000d0  rbp = 0x00007000043ca630  rsp = 0x00007000043ca600  
 r8 = 0x0000000000000002   r9 = 0x0000000000000001  r10 = 0x00007ff7b04d6248  r11 = 0x0000000000000202  
r12 = 0x0000000000000008  r13 = 0x0000000000000080  r14 = 0xfffffffffffffff8  r15 = 0x0000000000005e40  
AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV
==92755==ABORTING

--
exit: 1
--
shard JSON output does not exist: /Users/ec2-user/jenkins/workspace/llvm.org/clang-stage1-RA/clang-build/tools/clang/runtime/compiler-rt-bins/lib/asan/tests/X86_64HDarwinConfig/./Asan-x86_64h-calls-Noinst-Test-AddressSanitizer-Unit-90874-10-16.json
```

Maybe revert?

**Comment by cachemeifyoucan** [comment]
This also break Darwin ASAN bots for bootstrapping itself. I will revert for now.

**Comment by cachemeifyoucan** [comment]
Reverted: `16f4e85860efcccbadca5d0a00a3872244efae08`

**Comment by MaskRay** [comment]
macOS uses the dynamic runtime and `GetCurrentThread()` could return nullptr.

**Pull request merged**
