### PR TITLE
[DAG] SimplifyDemandedBits - ensure we demand the high bits for shl nsw/nuw ops

### LINKED ISSUE #69965: Miscompile in x86 backend, incorrectly removed bit mask
EDIT: Initial post was incorrect. See comment below https://github.com/llvm/llvm-project/issues/69965#issuecomment-1778235086 for correct repro.

https://godbolt.org/z/h4cWeWqP6

Input IR:

```
source_filename = "__module"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"

define i16 @test(i8 %_in) local_unnamed_addr #0 {
  %_1 = and i8 %_in, 127
  %_2 = xor i8 %_1, 127
  %_3 = or i8 %_2, -128
  %_4 = zext i8 %_3 to i16
  %_6 = shl nuw i16 %_4, 8
  %_7 = shl nuw i8 %_2, 1
  %_8 = zext i8 %_7 to i16
  %_9 = or i16 %_6, %_8
  ret i16 %_9
}
```

Resulting assembly with llc (trunk):

```
test:                                   # @test
        not     dil
        mov     eax, edi
        or      al, -128
        movzx   ecx, al
        shl     ecx, 8
        add     dil, dil
        movzx   eax, dil
        or      eax, ecx
        ret
```

It looks like the initial mask `and i8 %_in, 127` is being incorrectly optimized away. -O0 looks correct.

### PR DESCRIPTION
**Pull request by RKSimon**
Matches InstCombinerImpl::SimplifyDemandedUseBits

This also requires a tweak to the "AND(CTPOP(X),1) -> PARITY(X)" fold to allow us to demand known zero upper bits as well.

Fixes #69965

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
This is very unusual, and I'm surprised that InstCombine is doing this. What we do in literally all other cases (add, udiv, etc) is to drop the flags instead if the recursive SimplifyDemanded call succeeds. I'd recommend doing that here.

**Comment by nikic** [comment]
It looks like SDAG also follows the same approach in other cases, e.g. https://github.com/llvm/llvm-project/blob/c0914b222b1cdf3ab6bfabdec14ed1d0ef865765/llvm/lib/CodeGen/SelectionDAG/TargetLowering.cpp#L2732-L2738. I don't really see why we treat `shl` as a special snowflake.

**Comment by RKSimon** [comment]
We're actually very badly split in SimplifyDemandedBits - so if you have a preferred approach I'll see if I can make it more consistent:

SHL does the dropPoisonFlags approach, but only for variable shifts. I'll take your suggestion and see what happens by adding it for the constant shift as well instead of what I tried first. I'm worried that promotions and address math might be relying on NUW/NSW in some places.

SRA/SRL adds extra demanded bits for EXACT and doesn't alter flags at all.

**Comment by RKSimon** [comment]
Abandoning - I'm going to just drop the flags instead

**Comment by nikic** [comment]
> We're actually very badly split in SimplifyDemandedBits - so if you have a preferred approach I'll see if I can make it more consistent:
> 
> SHL does the dropPoisonFlags approach, but only for variable shifts. I'll take your suggestion and see what happens by adding it for the constant shift as well instead of what I tried first. I'm worried that promotions and address math might be relying on NUW/NSW in some places.
> 
> SRA/SRL adds extra demanded bits for EXACT and doesn't alter flags at all.

Looking closer, the situation in InstCombine seems to be quite similar to DAGCombine, with different approaches used for different instructions. I've submitted https://github.com/llvm/llvm-project/pull/70311 to switch to dropping the flag for `exact` shifts.

**Comment by RKSimon** [comment]
> Abandoning - I'm going to just drop the flags instead

547dc461225ba65b6d5dac34efd31d2c8c5b1049

**Pull request closed without merging**
