### PR TITLE
[libc] make off_t 32b for 32b arm

### PR DESCRIPTION
**Pull request by nickdesaulniers**
Fixes the following diagnostic:

    llvm-project/libc/src/sys/mman/linux/mmap.cpp:44:59: error: implicit
    conversion loses integer precision: 'off_t' (aka 'long long') to 'long'
    [-Werror,-Wshorten-64-to-32]
     size, prot, flags, fd, offset);
                            ^~~~~~

It looks like off_t is a curious types on different platforms.  FWICT, it's 32b
on arm (at least for arm-linux-gnueabi) but 64b elsewhere (including 32b
riscv32-linux-gnu).

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
alternately, we could just check for `__arm__`.  Thoughts?

**Comment by nickdesaulniers** [comment]
bionic has some docs about this
https://android.googlesource.com/platform/bionic/+/main/docs/32-bit-abi.md

> alternately, we could just check for `__arm__`. Thoughts?

No, i386 uses 32b.

**Review by lntue — APPROVED** [review]

**Review by michaelrj-google — APPROVED** [review]

**Comment by nickdesaulniers** [comment]
oh, looks like the build is still red :(

https://lab.llvm.org/buildbot/#/builders/229/builds/22032

**Comment by nickdesaulniers** [comment]
> oh, looks like the build is still red :(
> 
> https://lab.llvm.org/buildbot/#/builders/229/builds/22032

https://github.com/llvm/llvm-project/pull/77382

**Pull request merged**
