### PR TITLE
[libc++] Remove deprecated char_traits base template

### PR DESCRIPTION
**Pull request by ldionne**
This patch has quite a bit of history. First, it must be noted that the Standard only specifies specializations of char_traits for char, char8_t, char16_t, char32_t and wchar_t. However, before this patch, we would provide a base template that accepted anything, and as a result code like `std::basic_string<long long>` would compile but nobody knows what it really does. It basically compiles by accident.

We marked the base template as deprecated in LLVM 15 or 16 and were planning on removing it in LLVM 17, which we did in e30a148b098d. However, it turned out that the deprecation warning had never been visible in user code since Clang did not surface that warning from system headers. As a result, this caught people by surprise and we decided to reintroduce the base template in LLVM 17 in cce062d226ba.

Since then, #70353 changed Clang so that such deprecation warnings would be visible from user code. Hence, this patch closes the loop and removes the deprecated specializations.

### CODE REVIEW

**Comment by ldionne** [comment]
@cor3ntin Thanks a bunch for fixing the underlying Clang issue and enabling this!

**Comment by EricWF** [comment]
Could you please give me a few days to test this internally?

**Comment by ldionne** [comment]
> Could you please give me a few days to test this internally?

Sure, I mean this is going to land in the LLVM 19 time frame only anyways. But I would recommend doing the work now because otherwise this will become a problem for folks living at head when this lands.

CC @llvm/libcxx-vendors

**Comment by ldionne** [comment]
This should be ready for review now.

**Review by philnik777 — APPROVED** [review]

**Comment by ldionne** [comment]
CC @llvm/libcxx-vendors since this may break some (invalid) code.

**Comment by tambry** [comment]
Just for reference, an example of such breakage: https://github.com/jtv/libpqxx/pull/751

**Comment by ldionne** [comment]
I'm going for it -- we've been trying to remove this for like 2 years and we went through a deprecation period (LLVM 18), so I think we should land this as early as possible in the release cycle.

**Pull request merged**
