### PR TITLE
Change how branch weight is annotated for direct call

### PR DESCRIPTION
**Pull request by huangjd**
Currently when the Sample Profile reader matches a line with a direct function call, it annotates the function call branch weight with the sample's count. However if the sample contains call targets and one of them matches exactly with the direct function call, the call target count seems to be the more correct number. The inconsistency between sample count and (the sum of) call target count comes from multiple sources, for example if the profile is a product of merging/downsampling multiple profiles.

Example: 
```
main:1000:500
 1: 100 DirectCallee: 50
```

```
void main() {
  DirectCallee();
}
```

In this case it makes more sense to consider `DirectCallee`  having a branch weight of 50 not 100.

### CODE REVIEW

**Review by david-xl — COMMENTED** [review]
This happens with thinLTO postlink sample loading right? Can you add a test case?

**Comment by huangjd** [comment]
Currently this patch conflicts with 3 existing test cases, because how branch_weight is calculated for direct call was changed. In these test case inputs (and probably other test cases as well) there are several sample entries like the following:

```
 2: 123 callee:10
```
Where there's a single call target and its count is different from sample count. Some examples the call target count is even greater than the sample count, which I think should be invalid data.  Most test inputs seem to be arbitrarily written by hand without validating the data (and if running llvm-profdata on the input itself, then the output would be normalized to different contents.)


There are 3 ways to reconcile the test cases, and I would need some comment on which one makes the most sense.

1.  Apply the patch attached below, which I modified the reference values for these test cases. I am not able to manually calculate the correct value using new branch_weight calculation, but I did verify the new reference values by setting the sample count equal to call target count in the input, and the other way around, which gives the original correct output. This proves the change in output is an expected result of the change in branch_weight calculation.
2. Fix the test inputs so that call target count is equal to sample count. 
3. Further modify the way of determining branch_weight by adding a threshold, only if the sample count value differ from the call target count by more than the threshold percentage, the compiler will consider that sample count is invalid, and override with call target count instead. The threshold here is arbitrary, or it could be tied to an existing parameter in Sample Profile Loader.

[diff.txt](https://github.com/llvm/llvm-project/files/15194433/diff.txt)

**Comment by huangjd** [comment]
Affected test cases
```
  LLVM :: Transforms/SampleProfile/calls.ll
  LLVM :: Transforms/SampleProfile/fsafdo_test.ll
  LLVM :: Transforms/SampleProfile/profile-context-tracker.ll
```
I am including the test cases' authors as reviewers, in case the input data was written intentionally for a purpose. 
 @dnovillo wrote calls.ll but I couldn't add as reviewer.

**Review by WenleiHe — CHANGES_REQUESTED** [review]
I'm actually not sure if this change is needed. 

If you look at how profile is being generated, you will see that body samples are populated using range counters, and call samples are populated with branch counters. Range and branch counters aren't always guaranteed to be perfect match even though they were derived from same raw LBRs due to different filtering.

The discrepancy may not be perfect, but in practice it's also not that harmful given we deal with block counts and call counts somewhat separately. Also note that the discrepancy can be a result of changing code (from indirect call when profiled, to direct call when compiling again).

`getInstWeight` is mostly used compute `getBlockWeight` and I think it's probably more reasonable to use counts derived from Range counters regardless of call or non-call instructions, so they stay more consistent, which would lead to better input for profile inference later on. If you resort to use call target counts for direct call, you would be using count derived from Branch counters for calls, counts derived from Range counters for non-call, and that can create more pressure on inference with potentially worse result.

**Comment by david-xl** [comment]
> I'm actually not sure if this change is needed.
> 
> If you look at how profile is being generated, you will see that body samples are populated using range counters, and call samples are populated with branch counters. Range and branch counters aren't always guaranteed to be perfect match even though they were derived from same raw LBRs due to different filtering.
> 
> The discrepancy may not be perfect, but in practice it's also not that harmful given we deal with block counts and call counts somewhat separately. Also note that the discrepancy can be a result of changing code (from indirect call when profiled, to direct call when compiling again).
> 
> `getInstWeight` is mostly used compute `getBlockWeight` and I think it's probably more reasonable to use counts derived from Range counters regardless of call or non-call instructions, so they stay more consistent, which would lead to better input for profile inference later on. If you resort to use call target counts for direct call, you would be using count derived from Branch counters for calls, counts derived from Range counters for non-call, and that can create more pressure on inference with potentially worse result.



> I'm actually not sure if this change is needed.
> 
> If you look at how profile is being generated, you will see that body samples are populated using range counters, and call samples are populated with branch counters. Range and branch counters aren't always guaranteed to be perfect match even though they were derived from same raw LBRs due to different filtering.
> 
> The discrepancy may not be perfect, but in practice it's also not that harmful given we deal with block counts and call counts somewhat separately. Also note that the discrepancy can be a result of changing code (from indirect call when profiled, to direct call when compiling again).
> 
> `getInstWeight` is mostly used compute `getBlockWeight` and I think it's probably more reasonable to use counts derived from Range counters regardless of call or non-call instructions, so they stay more consistent, which would lead to better input for profile inference later on. If you resort to use call target counts for direct call, you would be using count derived from Branch counters for calls, counts derived from Range counters for non-call, and that can create more pressure on inference with potentially worse result.


Here is a scenario this patch may help.

Say the binary being profiled has an indirect call and the sample profile has an indirect target profile for the site. In thinLTO  prelink compilation, the indirect call is indirect call promoted resulting with if-then-else in which 'then' branch has a direct call.  In the postlink compilation, when the sample profile is loaded, it is better to use the call count to annotate the block.

**Comment by wlei-llvm** [comment]
>  if the profile is a product of merging/downsampling multiple profiles.

is this due to stale profile? I can think of a scenario that two profiles are from different versions.
in one version:
```
main:100:50
 1: 50 DirectCallee: 50
 2: 50
```
say another version add one line at the beginning of main. Then 
```
main:100:50
 1: 50
 2: 50 DirectCallee: 50
 3: 50
```
merging them will get:
```
main:200:100
 1: 100 DirectCallee: 50
 2: 100 DirectCallee: 50
 3: 50
```
Though either way may not be perfect in this case.

**Comment by WenleiHe** [comment]
> Say the binary being profiled has an indirect call and the sample profile has an indirect target profile for the site. In thinLTO prelink compilation, the indirect call is indirect call promoted resulting with if-then-else in which 'then' branch has a direct call. In the postlink compilation, when the sample profile is loaded, it is better to use the call count to annotate the block.

When doing ICP, we should distribute counts to the generated if-then-else as part of profile maintenance. Specifically, the generated block for the direct call should get the correct call counts as part of ICP for that target. In that case, post-link won't try to overwrite existing counts anyways.

**Comment by david-xl** [comment]
> > Say the binary being profiled has an indirect call and the sample profile has an indirect target profile for the site. In thinLTO prelink compilation, the indirect call is indirect call promoted resulting with if-then-else in which 'then' branch has a direct call. In the postlink compilation, when the sample profile is loaded, it is better to use the call count to annotate the block.
> 
> When doing ICP, we should distribute counts to the generated if-then-else as part of profile maintenance. Specifically, the generated block for the direct call should get the correct call counts as part of ICP for that target. In that case, post-link won't try to overwrite existing counts anyways.

Ack. @huangjd can you describe in more details how the inconsistency gets triggered?

**Comment by huangjd** [comment]
To explain the issue we encountered in more detail, and what this patch is trying to fix.

In some industrial use cases we encountered, we have a source file containing many repeated if statements, each calling a template specialized function, and the profile contains line-matching samples in the following form
```
func1:10000:12
 5: 10 callee1:0
 10: 9 callee2:1
 15: 11 callee3:0
```
At sample profile loader, each call is assigned a weight equal to the sample count (the first number), even if the direct call matches a call target in the sample exactly. This weight propagates to the entire "then" basic block, marking both the then branch and the function call inside it as hot.  In inliner pass, all these function calls are inlined, causing the IR size increase an order of magnitude, and significantly slowing down backend. Profiling shows that when all functions are inlined, half of the time is spent on machine block placement (which may indicate a problem of its own).

The problem here is that we have a contradictory input profile ("then" path is hot, but the call target is cold despite being called unconditionally), and the compiler is bogged down by such input, given that it normally compiles the program within reasonable time without a profile.

**Comment by david-xl** [comment]
> To explain the issue we encountered in more detail, and what this patch is trying to fix.
> 
> In some industrial use cases we encountered, we have a source file containing many repeated if statements, each calling a template specialized function, and the profile contains line-matching samples in the following form
> 
> ```
> func1:10000:12
>  5: 10 callee1:0
>  10: 9 callee2:1
>  15: 11 callee3:0
> ```
> 
> At sample profile loader, each call is assigned a weight equal to the sample count (the first number), even if the direct call matches a call target in the sample exactly. This weight propagates to the entire "then" basic block, marking both the then branch and the function call inside it as hot. In inliner pass, all these function calls are inlined, causing the IR size increase an order of magnitude, and significantly slowing down backend. Profiling shows that when all functions are inlined, half of the time is spent on machine block placement (which may indicate a problem of its own).
> 
> The problem here is that we have a contradictory input profile ("then" path is hot, but the call target is cold despite being called unconditionally), and the compiler is bogged down by such input, given that it normally compiles the program within reasonable time without a profile.

How was the contradictory profile generated? Slight inconsistency may be expected, but hot vs cold difference is not.

**Comment by huangjd** [comment]
I had a better way to resolve this issue at its root. See pr91843 
Closing this now.

**Pull request closed without merging**
