### PR TITLE
[ASan][Driver] Add sanitize-target flag to support enabling ASan in device or host compilation

### PR DESCRIPTION
**Pull request by jinge90**
In offloading scenario, the whole compiling process consists of device and host compilation phase, device and host code will be bundled together. Address sanitizer can be enabled in either one or both compilation phases via fsanitize-target=host|device|both. The meaning of each value is:
-fsanitize-target=host       AsanPass only enabled in host code
-fsanitize-target=device     AsanPass only enabled in device code
-fsanitize-target=both       AsanPass enabled in both host and device code
The default value is 'both'.

### CODE REVIEW

**Comment by jinge90** [comment]
Hi, @vitalybuka and @bader 
Recently, we are working to enable address sanitizer for SYCL and OMP offloading compiler. After enabling Asan instrumentation pass, ASanPass will insert "__asan_*" functions into user code in both device and host compilation. Although host code sanitizer is useful, sometimes we care more about device code sanitizer in offloading scenario and a flag to disable/enable ASan in host or device compilation phase will help. If offloading compiler's user wants to use sanitizer to detect bugs in their device code target for GPU, FPGA or other accelerators, they can add '-fsanitize-target=device' to disable ASanPass in host code(CPU code).
Thanks very much.

**Comment by jinge90** [comment]
Hi, @MaskRay 
Could you help review this patch?
Thanks very much.

**Comment by vitalybuka** [comment]
It seems as the build system business to control this logic, not driver.
@MaskRay and @AaronBallman WDYT?

**Comment by jinge90** [comment]
Hi, @MaskRay and @AaronBallman 
Kind ping~.
Thanks very much.

**Review by AaronBallman — CHANGES_REQUESTED** [review]
I had some conversations with @jinge90 offline and we're now thinking that perhaps a better approach is to have a more general feature for specifying host-only and target-only options instead of having each option split into two. Marking this review as requesting changes so it doesn't get accidentally accepted.

**Review by vitalybuka — CHANGES_REQUESTED** [review]
Removing from my pending reviews

**Comment by jinge90** [comment]
Using general option to pass device specific flags to device compilation should be better approach, so this pr is not needed any more, thanks very much!

**Pull request closed without merging**
