### PR TITLE
[LLVM][OpenMP] Allow OpenMPOpt to handle non-OpenMP target regions

### LINKED ISSUE #66687: [OpenMP] LTO on CUDA target fails with "inconsistent kernel function annotation" assertion
Test case consists of a CUDA file that calls thrust::sort and a main file that uses OpenMP offload to move data to  the device and call sort in the first file.

When compiled with -foffload-lto, the link stage fails with the assertion:

`clang-linker-wrapper: /home/mdewing/prev/software/llvm/github/llvm-project/llvm/lib/Transforms/IPO/OpenMPOpt.cpp:5829: llvm::omp::KernelSet llvm::omp::getDeviceKernels(llvm::Module&): Assertion 'isKernel(*KernelFn) && "Inconsistent kernel function annotation"' failed.`

When compiled without -foffload-lto, it compiles and runs.

It affects clang 17 and mainline.

[lto_error.tar.gz](https://github.com/llvm/llvm-project/files/12652386/lto_error.tar.gz)

### PR DESCRIPTION
**Pull request by shiltian**
Current OpenMPOpt assumes all kernels are OpenMP kernels (aka. with "kernel"
attribute). This doesn't hold if we mix OpenMP code and CUDA code by lingking
them together because CUDA kernels are not annotated with the attribute. This
patch removes the assumption and added a new counter for those non-OpenMP
kernels.

Fix #66687.

### CODE REVIEW

**Comment by jhuber6** [comment]
Is the desire to not run OpenMPOpt on kernels generated from CUDA? It would probably be much easier to make the CUDA metadata match OpenMP's otherwise.

Also unrelated complaint, I really wish we could unify the kernel annotations between AMDGPU and NVPTX.

**Comment by shiltian** [comment]
Given this pass is called OpenMPOpt, IMO we want to ignore CUDA kernels.

**Comment by jhuber6** [comment]
> Given this pass is called OpenMPOpt, IMO we want to ignore CUDA kernels.

We won't run OpenMPOpt if there's no `openmp` in the module, so this only occurs during LTO linking of merged OpenMP and CUDA modules. Wouldn't this cause issues for regular functions? Are we assume a function shared between an OpenMP and CUDA kernel cannot be optimized?

**Comment by shiltian** [comment]
> > Given this pass is called OpenMPOpt, IMO we want to ignore CUDA kernels.
> 
> We won't run OpenMPOpt if there's no `openmp` in the module, so this only occurs during LTO linking of merged OpenMP and CUDA modules. Wouldn't this cause issues for regular functions? Are we assume a function shared between an OpenMP and CUDA kernel cannot be optimized?

We don't assume that, but kernel is different because it is the entry point, so we can ignore them. We can have functions from CUDA and used in OpenMP. That is totally fine, even without the patch.

**Comment by jdoerfert** [comment]
I'm fine with this. @jhuber6 ?

**Review by jhuber6 — APPROVED** [review]

**Pull request merged**
