### PR TITLE
[clang][DebugInfo] Revert to attaching DW_AT_const_value on static member declarations

### PR DESCRIPTION
**Pull request by Michael137**
In https://github.com/llvm/llvm-project/pull/71780 we started emitting definitions for all static data-members with constant initialisers, even if they were constants (i.e., didn't have a location). We also dropped the DW_AT_const_value from the declaration to [help resolve inconsistencies during type merging in the DWARFParallelLinker](https://github.com/llvm/llvm-project/pull/68721). However, for static data members that do have locations, we wouldn't emit a DW_AT_const_value on it, assuming that the consumer knows how to read the value using the location. This broke some consumers that really wanted to find a DW_AT_const_value. Ultimately we want to attach a DW_AT_const_value to definitions that have a location too. But to fix consumers broken by said change, this patch adds the constant back onto the declaration. This is what we used to do prior to https://github.com/llvm/llvm-project/pull/71780

### CODE REVIEW

**Comment by Michael137** [comment]
FYI @petrhosek

**Review by jryans — APPROVED** [review]
Thanks, seems like a fine temporary measure to me! 😄

**Comment by Michael137** [comment]
I do wonder how feasible it would be for the downstream tests to be adjusted to look at the `DW_AT_location`..

**Comment by Michael137** [comment]
> > I do wonder how feasible it would be for the downstream tests to be adjusted to look at the `DW_AT_location`..
> 
> As I mentioned on the other thread, the point is not to have to read the value from the process-under-debug. This is not efficient in a remote-debugging scenario.

Ah that's fair, missed your comment on the other thread

**Comment by Michael137** [comment]
Looks like LLDB linux buildbot isn't happy, checking...

**Comment by Michael137** [comment]
> Looks like LLDB linux buildbot isn't happy, checking...

Fix in https://github.com/llvm/llvm-project/pull/73707

**Pull request merged**
