### PR TITLE
[NFC][clang][TableGen] Remove redundant llvm:: namespace qualifier

### PR DESCRIPTION
**Pull request by jurahul**
Remove llvm:: from .cpp files, and add "using namespace llvm" if needed.

### CODE REVIEW

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Comment by jplehr** [comment]
Hi, we see the same errors on our buildbots, two as examples:

https://lab.llvm.org/buildbot/#/builders/30/builds/6250
https://lab.llvm.org/buildbot/#/builders/140/builds/6648

**Comment by jurahul** [comment]
I have a proposed fix here: https://github.com/llvm/llvm-project/pull/108826

**Comment by jurahul** [comment]
This was not flagged by pre-commit CI. I am wondering if the CI can be tweaked to flag this pre commit.

**Comment by jurahul** [comment]
I see that the warning is not yet implemented in clang, but its in GCC, so only GCC based builds flagged it as an error. So what we really need it a GCC based build, which is not a tweak.

**Pull request merged**
