### PR TITLE
[AMDGPU][True16] fix a bug in codeGen causing e64 with wrong vgpr type to shrink

### PR DESCRIPTION
**Pull request by broxigarchen**
This bug is introduced in https://github.com/llvm/llvm-project/pull/102198

The previous path change to use realTrue16 flag, however, we have some t16 instructions that are implemented with fake16, and has Lo128 registers types. Thus we should still using hasTrue16Bit flag for shrinking check

### CODE REVIEW

**Review by Sisyph — APPROVED** [review]
LGTM. We can revert this part of the patch until all instructions are properly updated.

**Comment by jayfoad** [comment]
Can you include a test case?

**Comment by hanhanW** [comment]
Thanks, I verified that it fixes the issue in our project!

**Review by arsenm — CHANGES_REQUESTED** [review]
Needs test

**Review by arsenm — APPROVED** [review]

**Pull request merged**
