### PR TITLE
[flang] Use i16 instead of i2 for cmdstat

### PR DESCRIPTION
**Pull request by razvanlupusoru**
The code for preparing cmdstat was generating an i2 constant with value 0, casting it, and then storing it into i16 storage. Just generate i16 constant directly.

### CODE REVIEW

**Review by vzakhari — APPROVED** [review]
Thank you, Razvan!

**Review by clementval — APPROVED** [review]

**Comment by clementval** [comment]
@yi-wu-arm Was there a reason for this I2 type?

**Comment by razvanlupusoru** [comment]
@yi-wu-arm I am going to go ahead and merge this. We can still discuss afterwards if there was a reason it was done this way :) Thanks!

**Comment by yi-wu-arm** [comment]
Thanks for patching this, @razvanlupusoru
>Was there a reason for this I2 type?

not really, I think I may forget to change it after copy it from somewhere.

**Pull request merged**
