### PR TITLE
[clang][analyzer] Move 'alpha.core.PointerSub' checker into 'security.PointerSub'

### PR DESCRIPTION
**Pull request by balazske**
Checker was tested on 16 projects. The only results were the offset calculations that were considered as valid (faulty) cases already.
https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=vim_v8.2.1920_pointersub_c&is-unique=off&diff-type=New&checker-name=alpha.core.PointerSub
https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=protobuf_v3.13.0_pointersub_cpp&is-unique=off&diff-type=New&checker-name=alpha.core.PointerSub

### CODE REVIEW

**Review by steakhal — CHANGES_REQUESTED** [review]
I'm not satisfied with the quality of the reports. The report refers to `Subtraction of two pointers that do not point into the same array is undefined behavior` without pointing out where the two pointers point to (and/or where are they declared, or set to point to different objects). Without improving the diagnostics, I don't think we should move this out of alpha.

**Comment by balazske** [comment]
> I'm not satisfied with the quality of the reports. The report refers to `Subtraction of two pointers that do not point into the same array is undefined behavior` without pointing out where the two pointers point to (and/or where are they declared, or set to point to different objects). Without improving the diagnostics, I don't think we should move this out of alpha.

For this purpose the report notes were added. In the CodeChecker interface the arrow beneath "Notes" can be expanded to see these notes. Sure it can be even more exact if all the super-regions were pointed out but in the current reports it is probably not difficult to recognize what the different regions are (different variables or different members of a struct or a variable and a member of the same struct as the variable).

**Review by steakhal — APPROVED** [review]
> > I'm not satisfied with the quality of the reports. The report refers to `Subtraction of two pointers that do not point into the same array is undefined behavior` without pointing out where the two pointers point to (and/or where are they declared, or set to point to different objects). Without improving the diagnostics, I don't think we should move this out of alpha.
> 
> For this purpose the report notes were added. In the CodeChecker interface the arrow beneath "Notes" can be expanded to see these notes. Sure it can be even more exact if all the super-regions were pointed out but in the current reports it is probably not difficult to recognize what the different regions are (different variables or different members of a struct or a variable and a member of the same struct as the variable).

I see! Thanks. In that case, I don't oppose.

**Review by NagyDonat — COMMENTED** [review]
I think this checker is definitely good enough to be moved out of `alpha`, but I'm not sure that it should be placed in the `core` group, where we have a strong requirement that "These checkers must be always switched on as other checker rely on them.".

There might be projects that intentionally use nonstandard but "works on our system" pointer subtraction to optimize performance, perhaps e.g. on a low-level system.

As an alternative of placing this in `core`, we could move it to e.g. `security.PointerSub` -- but I'd prefer moving the "must be always switched on" requirement from "all core checkers" to those concrete checkers where it's *really* needed. I think `core` conflates "checks a core language feature" and "is important for proper modeling", which is not ideal.

Also note that we already have hidden modeling checkers that cannot be disabled and perform the essential modeling work -- so it's strange that we also have this "must not be disabled" requirement for other checkers.

@steakhal @haoNoQ @Xazax-hun What do you think about this?

**Comment by steakhal** [comment]
Agreed!

**Comment by balazske** [comment]
I moved the checker now into package `security`. The main reason is that the checker should not be turned on by default because  use of such low-level features may be valid in some projects. The checker is not absolutely security-related but there was no better place for it (`optin` is for checkers that are turned off more often). I need a re-approval before merge.

**Review by steakhal — APPROVED** [review]
Still makes sense.

**Pull request merged**
