### PR TITLE
[sanitizer] Skip /include/c++/ from summary

### PR DESCRIPTION
**Pull request by vitalybuka**
std:: usually is not a cause of the bug.

We now display 
```
SUMMARY: AddressSanitizer: allocation-size-too-big path/to/allocator_returns_null.cpp:92:7 in main
```
instead of 

```
SUMMARY: AddressSanitizer: allocation-size-too-big /usr/lib/../include/c++/13/bits/new_allocator.h:147:27 in std::__new_allocator<char>::allocate(unsigned long, void const*)
```

`/include/c++/` matches both libc++ and libstdc++ include paths.

### CODE REVIEW

**Comment by MaskRay** [comment]
> std:: usually is not a cause of the bug.

Consider elaborating this message.

We now display `SUMMARY: AddressSanitizer: allocation-size-too-big path/to/allocator_returns_null.cpp:92:7 in main` instead of `SUMMARY: AddressSanitizer: allocation-size-too-big /usr/lib/gcc/x86_64-linux-gnu/13/../../../../include/c++/13/bits/new_allocator.h:147:27 in std::__new_allocator<char>::allocate(unsigned long, void const*)`

**Review by MaskRay — APPROVED** [review]

**Comment by zmodem** [comment]
This broke lit tests on Darwin, see https://green.lab.llvm.org/green/job/clang-stage1-RA/37026/execution/node/39/log/?consoleFull and https://bugs.chromium.org/p/chromium/issues/detail?id=1519812

I've reverted in 4619147911c2a955bb605618bc518b45da994a81 for now.

**Comment by vitalybuka** [comment]
Thanks, I guess symbolizer on Darwin somehow strip inlude/c++ path

**Comment by thesamesam** [comment]
Note that on Gentoo, this isn't right either, we have e.g.:
```
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/new_allocator.h
/usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/ext/new_allocator.h
```

**Comment by vitalybuka** [comment]
> Note that on Gentoo, this isn't right either, we have e.g.:
> 
> ```
> /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/bits/new_allocator.h
> /usr/lib/gcc/x86_64-pc-linux-gnu/14/include/g++-v14/ext/new_allocator.h
> ```

I guess it's fine to expand the FrameIsInternal to cover Gentoo as well. it looks quite distinct. It would be nice if someone who can test on platform to create a patch. 

For Darwin I don't see what we can do if there is no path at all, hardcode most common c++ headers?

**Comment by thesamesam** [comment]
Unfortunately, it's been a while since I've done Darwin (although may be doing a bit more soon), so no ideas for that side yet.

**Pull request merged**
