### PR TITLE
[RISCV] Make Zhinx and Zvfh imply Zhinxmin and Zvfhmin respectively

### PR DESCRIPTION
**Pull request by yetingk**
Zhinxmin is a subset of Zhinx and Zvfhmin is also a subset of Zvfh.

### CODE REVIEW

**Review by topperc — APPROVED** [review]
LGTM

**Comment by jacquesguan** [comment]
In the V spec, "The Zvfh extension depends on the Zve32f and Zfhmin extensions.". It seems that there is no dependency between Zvfh and Zvfhmin.

**Comment by topperc** [comment]
> In the V spec, "The Zvfh extension depends on the Zve32f and Zfhmin extensions.". It seems that there is no dependency between Zvfh and Zvfhmin.

Zvfh contains all of the Zvfhmin instructions. Which makes it similar to the discussion here https://github.com/riscv/riscv-isa-manual/pull/1121

**Review by 4vtomat — APPROVED** [review]
LGTM

**Pull request merged**
