### PR TITLE
[llvm-objdump][macho] Add support for ObjC relative method lists

### PR DESCRIPTION
**Pull request by alx32**
For Mach-O, ld64 supports the -fobjc-relative-method-lists flag which changes the format in which method lists are generated. The format uses delta encoding vs the original direct-pointer encoding.
This change adds support to llvm-objdump and llvm-otool for decoding/dumping of method lists in the delta format. Previously, if a binary with this information format was passed to the tooling, it would output invalid information, trying to parse the delta lists as pointer lists.
After this change, the tooling will output correct information if a binary in this format is encountered.
The output format is closest feasible match to XCode 15.1's otool output. Tests are included for both 32bit and 64bit binaries.

The code style was matched as close as possible to existing implementation of parsing non-delta method lists.

Diff between llvm-objdump and XCode 15.1 otool:
image

Note: This is a retry of this PR: https://github.com/llvm/llvm-project/pull/84250
On the original PR, the armv7+armv8 builds were failing due to absolute offsets being different.

### CODE REVIEW

**Comment by alx32** [comment]
This is a retry of this PR: https://github.com/llvm/llvm-project/pull/84250
After build bots showed that absolute offsets are different on armv7/armv8 builds of objdump. The absolute offsets are now regex's.

**Review by kyulee-com — APPROVED** [review]

**Comment by amy-kwan** [comment]
I believe this is causing the following test case failure on the [clang-ppc64be-linux-multistage](https://lab.llvm.org/buildbot/#/builders/93) bot. Could you please take a look?

**Comment by alx32** [comment]
Hi @amy-kwan , thanks for flagging this. 
This looks like the obvious fix: https://github.com/llvm/llvm-project/pull/85778
Do you know how I could test this for ppc64be before merging ?

**Comment by amy-kwan** [comment]
@alx32, thank you for the fix! I've actually applied it locally to a ppc64be machine myself and that patch resolves the issue.

**Pull request merged**
