### PR TITLE
[RISCV][ISel] Ensure 'in X' Constraints prevent X0

### PR DESCRIPTION
**Pull request by lenary**
I'm not sure if this fix is required, but I've written the patch anyway. This does not cause test changes, but we haven't got tests that try to use all 32 registers in inline assembly.

Broadly, for GPRs, we made the explicit choice that `r` constraints would never attempt to use `x0`, because `x0` isn't really usable like the other GPRs. I believe the same thing applies to `Zhinx`, `Zfinx` and `Zdinx` because they should not be allocating operands to `x0` either, so this patch introduces new `NoX0` classes for `GPRF16` and `GPRF32` registers, and uses them with inline assembly. There is also a `GPRPairNoX0` for the `Zdinx` case on rv32, avoiding use of the `x0` pair which has different behaviour to the other GPR pairs.

---

This is stacked on #112561, only review the last commit in this PR.

### CODE REVIEW

**Comment by lenary** [comment]
I spent some time trying to write a test that should fail before, but doesn't after, but it doesn't happen - I presume because x0 is reasonably dealt with by the allocator. This maybe suggests the patch isn't needed? I'm not sure why we do this for GPRs then.

**Comment by lenary** [comment]
(My approach with the test was to try to use all 32 GPRs, so have it fail when it couldn't use x0 - doing so by marking ra, sp, gp, and tp as clobbered, and passing 28 floats)

**Review by topperc — APPROVED** [review]
LGTM

**Comment by topperc** [comment]
> I spent some time trying to write a test that should fail before, but doesn't after, but it doesn't happen - I presume because x0 is reasonably dealt with by the allocator. This maybe suggests the patch isn't needed? I'm not sure why we do this for GPRs then.

I think the original issue was copy propagation folding "mv a0, x0" into an inline assembly source as "x0". The instruction being used in the assembly was one that treated x0 as a special encoding. So there was a difference between x0 and a register containing the value 0.

**Comment by lenary** [comment]
Yeah, I went back and looked at that issue, it's helpful to know that it was more than just the register allocator, that it was also copy propagation, which wasn't obvious from the comments. 

The failing tests are not related, but presumably caused by the rebase, but I'll still wait a bit to merge this.

**Comment by lenary** [comment]
> I'll still wait a bit to merge this.

Scratch that, merging now to unblock other PRs.

**Pull request merged**
