### PR TITLE
[Clang] Don't use crtbegin/crtend when building for musl.

### PR DESCRIPTION
**Pull request by al45tair**
musl doesn't supply crtbegin/crtend objects, so we don't want to try to link them there.

rdar://123436174

### CODE REVIEW

**Review by MaskRay — CHANGES_REQUESTED** [review]
Thanks for working on musl but I don't think this is correct.
The compiler provides crtbegin/crtend files, not musl.
A musl-cross-make build does use crtbegin/crtend, though technically the files can be empty.
However, there is no point to diverge, and even when crtbegin/crtend files are empty, users can customize them to do other stuff (e.g. specifying the section order).

**Comment by al45tair** [comment]
> The compiler provides crtbegin/crtend files, not musl.

Interesting. Looking at the LLVM repo, it seems compiler-rt might provide them, but I don't believe I have them in spite of building compiler-rt. I'll look at this again and see if maybe I need to tweak my compiler-rt build to get it to generate or install them in the right place.

**Comment by al45tair** [comment]
(I had assumed that they came from the C library, since that's where `crt1.o` comes from, but if they don't then it sounds like I just need to build them.)

**Comment by al45tair** [comment]
Regardless of who provides them, if someone is relying on this then this is the wrong change. Closing.

**Pull request closed without merging**
