### PR TITLE
[DAG] getOperationAction - always return Custom action for target opcodes

### LINKED ISSUE #95274: [X86] [Crash] LLVM ERROR: Do not know how to split the result of this operator!
FP vector conversion test fails for skylake-avx512 CPU. Works fine for sapphirerapids CPU.
```
$ llc bugpoint-reduced-simplified.ll -mcpu=skylake-avx512
SplitVectorResult #0: t12: v1024i16 = X86ISD::CVTPS2PH undef:v1024f32, TargetConstant:i32<4>

LLVM ERROR: Do not know how to split the result of this operator!
```
Simplified reproducer:
```
; ModuleID = 'bugpoint-reduced-simplified.bc'
source_filename = "LLVMDialectModule"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

; Function Attrs: memory(argmem: readwrite)
define void @kernel(ptr %0) local_unnamed_addr #0 {
  %2 = fptrunc <1024 x float> poison to <1024 x half>
  store <1024 x half> %2, ptr %0, align 2
  ret void
}

attributes #0 = { memory(argmem: readwrite) }

!llvm.module.flags = !{!0}

!0 = !{i32 2, !"Debug Info Version", i32 3}
```

### PR DESCRIPTION
**Pull request by RKSimon**
The target must be responsible for any expansion that needs to be performed for extended types etc.

Fixes #95274

### CODE REVIEW

**Review by arsenm — APPROVED** [review]

**Comment by phoebewang** [comment]
This can be solve in this way too:
```
diff --git a/llvm/lib/Target/X86/X86ISelLowering.cpp b/llvm/lib/Target/X86/X86ISelLowering.cpp
index 3fbab3af32bb..a535cffa282c 100644
--- a/llvm/lib/Target/X86/X86ISelLowering.cpp
+++ b/llvm/lib/Target/X86/X86ISelLowering.cpp
@@ -57239,7 +57239,7 @@ static SDValue combineFP_ROUND(SDNode *N, SelectionDAG &DAG,
     return SDValue();
   }

-  if (NumElts == 1 || !isPowerOf2_32(NumElts))
+  if (NumElts == 1 || NumElts > 16 || !isPowerOf2_32(NumElts))
     return SDValue();

   // Widen to at least 4 input elements.
```
Which looks less destructive to me.

**Comment by RKSimon** [comment]
I'm not sure I agree, always treating target opcodes as Custom makes more general sense to me. Tweaking combineFP_ROUND is just avoiding the problem surely?

**Comment by arsenm** [comment]
Requesting Expand for target opcodes makes no sense under any circumstances. The generic expand code can never handle them

**Review by phoebewang — APPROVED** [review]
I see. LGTM then.

**Pull request merged**
