### PR TITLE
[clang] Add test for CWG1350

### PR DESCRIPTION
**Pull request by Endilll**
Test is based on [P0136R1](https://wg21.link/p0136r1) wording instead of proposed resolution in the issue itself.

This patch also expands related CWG1573 test with an additional test case. Existing `3.9` status of 1573 is still relevant even with this new test case.

### CODE REVIEW

**Comment by Endilll** [comment]
I was way too deep into P0136R1 [Rewording inheriting constructors (core issue 1941 et al)](https://wg21.link/p0136r1) when I realized Richard has written tests for all issues covered there long ago. So I decided to carry on and check whether those tests would benefit from additional test cases. That's how I came up with a new test case for CWG1573, and came about its related issue 1350, which was lacking a test.

**Comment by cor3ntin** [comment]
For completeness, can you add a couple of tests covering the note (ie, template case?)
Otherwise, LGTM

**Review by cor3ntin — APPROVED** [review]
LGTM

**Review by shafik — COMMENTED** [review]
LGTM

**Pull request merged**
