### PR TITLE
Revert "[CodeGen] Use MachineInstr::{all_uses,all_defs} (NFC)"

### PR DESCRIPTION
**Pull request by vitalybuka**
Reverts llvm/llvm-project#106404

Breaks:
https://lab.llvm.org/buildbot/#/builders/169/builds/2590
https://lab.llvm.org/buildbot/#/builders/164/builds/2454

### CODE REVIEW

**Review by kazutakahirata — APPROVED** [review]
Thanks!

**Comment by vitalybuka** [comment]
> Thanks!

I am not 100% sure that this is the one, but I will reland if this is not the case.

**Comment by kazutakahirata** [comment]
> > Thanks!
> 
> I am not 100% sure that this is the one, but I will reland if this is not the case.

Thanks again!

**Comment by vitalybuka** [comment]
Revert fixed the build https://lab.llvm.org/buildbot/#/builders/169/builds/2594

**Pull request merged**
