### PR TITLE
[RISCV] Match constant indices of non-index type when forming strided ops

### PR DESCRIPTION
**Pull request by preames**
When checking to see if our index expressions can be converted into strided operations, we previously gave up if the index type wasn't an exact match for the intptrty for the address.  Per gep semantics, this mismatch implies a sext or trunc cast to the respective index type.  For constants, go ahead and evaluate that cast instead of giving up.

Note that the motivation of this is mostly test cleanup.  We canonicalize at IR such that the gep index will match the intptrty.  This is mostly useful so that we can write both RV32 and RV64 tests from the same source.  Its also helpful in preventing confusion - I've stumbled across this at least four times now and wasted time each one.

### CODE REVIEW

**Comment by topperc** [comment]
Does this allow a vector of i8 indices like <0, 128, 0, 128, 0, 128, 0, 128> to be considered a stride of 128?

I'm traveling today so cant easily check.

**Comment by preames** [comment]
> Does this allow a vector of i8 indices like <0, 128, 0, 128, 0, 128, 0, 128> to be considered a stride of 128?

Yep, it gets this wrong.  I'm going to add the reduced test case, and then rework the patch.  Good catch.

**Review by topperc — APPROVED** [review]
LGTM

**Comment by preames** [comment]
Landed as 07228002891c5b970b8f5a0040adf3176b168171

**Pull request closed without merging**
