### PR TITLE
[ORC_RT][COFF] add more mutex to internal api

### PR DESCRIPTION
**Pull request by yingcong-wu**
Add more mutex to wherever `JDStates` is used to avoid data race problem.

### CODE REVIEW

**Comment by sunho** [comment]
Note all the public interface already locks the mutex and the functions changed here are only used within the public interface. So, the lock would be redundant.

**Comment by sunho** [comment]
If there is some case I missed, please let me know.

**Comment by yingcong-wu** [comment]
> Note all the public interface already locks the mutex and the functions changed here are only used within the public interface. So, the lock would be redundant.
Okay, good to know that.

**Comment by yingcong-wu** [comment]
I just think that since it is a recursive_mutex, we just need to lock it whenever we use it to avoid the mental burden of remembering to lock it in the public interface.

**Pull request closed without merging**
