### PR TITLE
AMDGPU: Add baseline tests for gep flag handling

### PR DESCRIPTION
**Pull request by arsenm**
We need to know the address computation won't overflow on
older subtargets to match the addressing mode of stack instructions.

### CODE REVIEW

**Comment by arsenm** [comment]
* **#110815** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/110815?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#110814** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/110814?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by arsenm** [comment]
### Merge activity

* **Oct 9, 5:42 AM EDT**: @arsenm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/110814).

**Comment by nico** [comment]
Looks like these are failing: http://45.33.8.238/linux/149769/step_11.txt

Please take a look and revert for now if it takes a while to fix.

**Comment by mikaelholmen** [comment]
> Looks like these are failing: http://45.33.8.238/linux/149769/step_11.txt
> 
> Please take a look and revert for now if it takes a while to fix.

It looks like the operand order in several instructions is not deterministic, but depends on the compiler used to compile llc. I've seen it pass when using gcc and fail with clang 18 and the differences when failing are like
```
-; GFX8-NEXT:    v_add_u32_e32 v0, vcc, v2, v0
+; GFX8-NEXT:    v_add_u32_e32 v0, vcc, v0, v2
```

**Pull request merged**
