### PR TITLE
[LLDB][SBSaveCore] Fix bug where default values are not propagated.

### PR DESCRIPTION
**Pull request by Jlalond**
In #100443, Mach-o and Minidump now only call process API's that take a `SaveCoreOption` as the container for the style and information if a thread should be included in the core or not. This introduced a bug where in subsequent method calls we were not honoring the defaults of both implementations.

~~To solve this I have made a copy of each SaveCoreOptions that is mutable by the respective plugin. Originally I wanted to leave the SaveCoreOptions as non const so these default value mutations could be shown back to the user. Changing that behavior is outside of the scope of this bugfix, but is context for why we are making a copy.~~

Removed const on the savecoreoptions so defaults can be inspected by the user

CC: @Michael137

### CODE REVIEW

**Review by clayborg — COMMENTED** [review]
Might actually be nice to make the SaveCoreOptions non const. Why? Because clients could see what the settings were set to if a plug-in modifies or overrides certain settings.

**Review by clayborg — APPROVED** [review]

**Comment by hokein** [comment]
The newly-added test causes a msan failure:

```
==1960==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55e25271b29e in RetryAfterSignal<int, long (int, const void *, unsigned long), int, const void *, unsigned long> llvm-project/llvm/include/llvm/Support/Errno.h:37:11
    #1 0x55e25271b29e in lldb_private::NativeFile::Write(void const*, unsigned long&) llvm-project/lldb/source/Host/common/File.cpp:618:9
    #2 0x55e25223793f in MinidumpFileBuilder::FlushBufferToDisk() llvm-project/lldb/source/Plugins/ObjectFile/Minidump/MinidumpFileBuilder.cpp:1165:26
    #3 0x55e252237548 in MinidumpFileBuilder::FixThreadStacks() llvm-project/lldb/source/Plugins/ObjectFile/Minidump/MinidumpFileBuilder.cpp:568:3
    #4 0x55e25223ba52 in MinidumpFileBuilder::AddMemoryList() llvm-project/lldb/source/Plugins/ObjectFile/Minidump/MinidumpFileBuilder.cpp:890:10
    #5 0x55e2522438ad in ObjectFileMinidump::SaveCore(std::__msan::shared_ptr<lldb_private::Process> const&, lldb_private::SaveCoreOptions&, lldb_private::Status&) llvm-project/lldb/source/Plugins/ObjectFile/Minidump/ObjectFileMinidump.cpp:124:19
    #6 0x55e251e1f482 in lldb_private::PluginManager::SaveCore(std::__msan::shared_ptr<lldb_private::Process> const&, lldb_private::SaveCoreOptions&) llvm-project/lldb/source/Core/PluginManager.cpp:736:33
```

**Comment by hokein** [comment]
@Jlalond, I revert it in 86f7374078288e2b3d3d0fd66428f7752e2319e6 to keep the trunk green. Feel free to reland the patch with the fix.

**Comment by Jlalond** [comment]
@hokein Thank you for reverting it, I'll look into what I missed :)

**Comment by Jlalond** [comment]
@hokein Can you share the build command you got to trigger the above msan error? I'm having trouble reproducing your issue

**Comment by clayborg** [comment]
> @hokein Can you share the build command you got to trigger the above msan error? I'm having trouble reproducing your issue

And was your build using msan? or just a regular build? I can see a msan build fail to create a core file due to it crashing, and then you might see this result. But if you didn't have msan enabled, what OS did this fail for?

**Comment by hokein** [comment]
I saw the msan failure when integrating LLVM into our internal codebase, it is a msan-build lldb.

The second error `AssertionError: launching (4) != stopped (5)` occurred in a non-msan-build lldb from the upstream repository. And I ran `llvm-lit -sv lldb/test/API/functionalities/process_save_core/TestProcessSaveCore.py`

**Comment by Jlalond** [comment]
> I saw the msan failure when integrating LLVM into our internal codebase, it is a msan-build lldb.
> 
> The second error `AssertionError: launching (4) != stopped (5)` occurred in a non-msan-build lldb from the upstream repository. And I ran `llvm-lit -sv lldb/test/API/functionalities/process_save_core/TestProcessSaveCore.py`

@hokein can you share your repro steps for this? I haven't been able to reproduce this error on my machine, so I will need more information from you

**Pull request merged**
