### PR TITLE
Add support for arm64 registers in minidump core file saving.

### PR DESCRIPTION
**Pull request by clayborg**
This patch adds support for saving minidumps with the arm64 architecture. It also will cause unsupported architectures to emit an error where before this patch it would emit a minidump with partial information. This new code is tested by the arm64 windows buildbot that was failing:

https://lab.llvm.org/buildbot/#/builders/219/builds/6868

This is needed following this PR: https://github.com/llvm/llvm-project/pull/71772

### CODE REVIEW

**Comment by antmox** [comment]
LGTM. minidump tests are now OK on linaro-armv8-windows-msvc machine.

**Comment by clayborg** [comment]
> LGTM. minidump tests are now OK on linaro-armv8-windows-msvc machine.

Feel free to accept this patch then and I can get it merged!

**Review by antmox — APPROVED** [review]

**Comment by clayborg** [comment]
@antmox Hopefully this clears up the issue on the build bot! Thanks for testing this for me.

**Comment by antmox** [comment]
Thanks @clayborg, the buildbot is now green again : https://lab.llvm.org/buildbot/#/builders/219/builds/6947

**Pull request merged**
