### PR TITLE
Link shared sanitizer runtime with libresolv for dn_expand

### LINKED ISSUE #59007: AddressSanitizer:DEADLYSIGNAL in getaddrinfo() when compiled with clang-15 with "-nodefaultlibs" without "-lresolv"
The following code
```cpp
#include <arpa/inet.h>
#include <netdb.h>
#include <stdio.h>

int main() {
  addrinfo hints = {};
  addrinfo* res;
  getaddrinfo("api.binance.com", nullptr, &hints, &res);
  printf("%s\n", inet_ntoa(reinterpret_cast<sockaddr_in*>(res->ai_addr)->sin_addr));
  freeaddrinfo(res);
  return 0;
}
```
compiled with
```shell
clang-15 -fsanitize=address test.cpp -nodefaultlibs -lgcc_eh -lc -lm -lpthread -ldl
```
produces the following error:
```console
$ ./a.out
AddressSanitizer:DEADLYSIGNAL
=================================================================
==1010333==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7ffd91eac050 sp 0x7ffd91eab808 T0)
==1010333==Hint: pc points to the zero page.
==1010333==The signal is caused by a READ memory access.
==1010333==Hint: address points to the zero page.
    #0 0x0  (<unknown module>)
    #1 0x7f5bab6b6805 in gaih_getanswer_slice /build/glibc-SzIz7B/glibc-2.31/resolv/nss_dns/dns-host.c:1147:8

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>)
==1010333==ABORTING
```

If `-lresolv` option is added, it works as expected:

```console
$ clang-15 -fsanitize=address test.cpp -nodefaultlibs -lgcc_eh -lc -lm -lpthread -ldl -lresolv -o b.out && ./b.out
13.32.142.177
```
It also works as expected if I use `clang-14` instead of `clang-15`.

This is a very practical issue, because it is reproduced when using python's `requests` module with dynamically loaded sanitizer runtime (necessary when using sanitized python extensions):
```console
$ LD_PRELOAD=$(clang++-15 -print-file-name=libclang_rt.asan-x86_64.so) python -c 'import requests
print(requests.get("https://api.binance.com/"))'
AddressSanitizer:DEADLYSIGNAL
=================================================================
==919440==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000000000 bp 0x7ffe180677c0 sp 0x7ffe18066f78 T0)
==919440==Hint: pc points to the zero page.
==919440==The signal is caused by a READ memory access.
==919440==Hint: address points to the zero page.
    #0 0x0  (<unknown module>)
    #1 0x7f3048604805 in gaih_getanswer_slice /build/glibc-SzIz7B/glibc-2.31/resolv/nss_dns/dns-host.c:1147:8

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (<unknown module>)
==919440==ABORTING
```

More info:
```console
$ ldd ./a.out # this one crashes
	linux-vdso.so.1 (0x00007ffc6537a000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f77efcbf000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f77efb70000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f77efb4d000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f77efb47000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f77f0930000)

$ ldd ./b.out # this one does not crash
	linux-vdso.so.1 (0x00007ffde1385000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f15e3c18000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f15e3ac9000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f15e3aa6000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f15e3aa0000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f15e3a84000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f15e488c000)

$ clang-15 --version
Ubuntu clang version 15.0.4-++20221031075612+08bd84e8a635-1~exp1~20221031075700.87
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/bin

$ python --version
Python 3.8.10

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.5 LTS
Release:	20.04
Codename:	focal
```

I posted the same bug at https://github.com/google/sanitizers/issues/1592, because I am not sure if it is related to sanitizers or clang-15.

### PR DESCRIPTION
**Pull request by aaronpuchert**
Since the interceptor was added in 1a729bce86173, a process using sanitizers might need libresolv for the real version of __dn_expand. The linker flag for the static runtime was added in 6dce56b2a3082. But the dynamic runtime didn't get the dependency. This can cause crashes even when libresolv is not used directly, because it is also used by DNS lookups via e.g. getaddrinfo when the DNS reply uses compression.

We observed the issue with the address sanitizer, but a quick look into the shared runtime libraries revealed that the memprof and tsan runtimes also export dn_expand and should thus be prone to the same issue.

It should be mentioned that glibc plans to move libresolv into libc, which was partially completed in version 2.34 with the move of dn_comp and dn_expand. However, that is not an issue here: once the move is complete, there will only be a static libresolv.a stub left and so building against a version after the move will no longer produce a runtime dependency to libresolv.so.

Fixes #59007.

### CODE REVIEW

**Review by vitalybuka — COMMENTED** [review]
What about other sanitizers?

**Comment by aaronpuchert** [comment]
I based it on this:
```
$ for lib in *.so; do echo $lib; readelf --dyn-syms --wide $lib | grep dn_comp; done
libclang_rt.asan-x86_64.so
  1069: 000000000009b880  1263 FUNC    WEAK   DEFAULT   13 __interceptor_dn_comp
  1260: 000000000009b880  1263 FUNC    GLOBAL DEFAULT   13 ___interceptor_dn_comp
  1705: 0000000000082fec     5 FUNC    GLOBAL DEFAULT   13 __interceptor_trampoline_dn_comp
  2138: 0000000000082fec     5 FUNC    WEAK   DEFAULT   13 dn_comp
libclang_rt.dyndd-x86_64.so
libclang_rt.hwasan_aliases-x86_64.so
libclang_rt.hwasan-x86_64.so
libclang_rt.memprof-x86_64.so
   978: 0000000000069b10   203 FUNC    WEAK   DEFAULT   13 __interceptor_dn_comp
  1149: 0000000000069b10   203 FUNC    GLOBAL DEFAULT   13 ___interceptor_dn_comp
  1551: 0000000000061e98     5 FUNC    GLOBAL DEFAULT   13 __interceptor_trampoline_dn_comp
  1938: 0000000000061e98     5 FUNC    WEAK   DEFAULT   13 dn_comp
libclang_rt.nsan-x86_64.so
libclang_rt.scudo_standalone-x86_64.so
libclang_rt.tsan-x86_64.so
  1147: 000000000008e7f0   518 FUNC    WEAK   DEFAULT   13 __interceptor_dn_comp
  1350: 000000000008e7f0   518 FUNC    GLOBAL DEFAULT   13 ___interceptor_dn_comp
  1844: 0000000000070935     5 FUNC    GLOBAL DEFAULT   13 __interceptor_trampoline_dn_comp
  2318: 0000000000070935     5 FUNC    WEAK   DEFAULT   13 dn_comp
libclang_rt.ubsan_minimal-x86_64.so
libclang_rt.ubsan_standalone-x86_64.so
```
But this might be due to my build settings.

**Comment by aaronpuchert** [comment]
For **HwASan**, I have `COMPILER_RT_HWASAN_WITH_INTERCEPTORS` enabled. Still no sign of `dn_comp` or `dn_expand`.

For **NSan** the library should never be relevant. There is no floating-point in DNS.

The **UBSan** runtime doesn't intercept any functions, it only consists of error handlers.

**Comment by aaronpuchert** [comment]
One more: **MSan** does not seem to offer a shared runtime.

**Comment by aaronpuchert** [comment]
**RTSan** has a shared runtime only on Mac, i.e. `if(APPLE)`. So I can't tell.

**Comment by vitalybuka** [comment]
Maybe as alternative solution we convert this into MSAN-only interceptor and let it be?

**Comment by aaronpuchert** [comment]
The interceptors are definitely tailored towards MSan, where they're necessary to address false positives. They don't even check for reads, just register the writes. But I'm not sure where to disable it. HWASan has [hwasan_platform_interceptors.h](https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/hwasan/hwasan_platform_interceptors.h), where lots of interceptors are disabled, but I can't find an equivalent place for ASan.

The additional link dependency might also be temporary: my impression is that glibc [wants to integrate](https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html) [all sublibraries](https://developers.redhat.com/articles/2021/12/17/why-glibc-234-removed-libpthread) into the main library.

**Comment by cjappl** [comment]
> My understanding is that at least `dn_comp` and `dn_expand` don't block. Other functions in `resolv` can block, but we don't intercept them at the moment.

I would suspect these calls (`dn_comp`, `dn_expand` and others) should be intercepted, but we haven't gotten around to them yet. Any PR welcome to intercept this or other calls, but no worries if you don't want to follow up. 

"blocking" in the case of rtsan means unsafe for real-time code (contains a syscall of any type). I would guess that any query to the DNS subsystem results in a system call.

**Comment by aaronpuchert** [comment]
> "blocking" in the case of rtsan means unsafe for real-time code (contains a syscall of any type). I would guess that any query to the DNS subsystem results in a system call.

My understanding is that they don't do any syscalls, they just "compress" or "expand" domain names for a DNS query or reply. Since they write into buffers allocated by the caller, I think they don't even do any allocations. But I didn't check this hypothesis.

**Comment by aaronpuchert** [comment]
@vitalybuka, I forgot to mention that we already link with `-lresolv`, but only in the static runtime case. This was done in 6dce56b2a3082191aa3d26abd4f05cf518d98356 and applies to all sanitizers, as far as I can tell. So here we're just bringing the shared runtime in line with that.

But I have no issue with disabling the interceptor for the address sanitizer, I'm just not sure where to put that yet.

**Comment by vitalybuka** [comment]
> The interceptors are definitely tailored towards MSan, where they're necessary to address false positives. They don't even check for reads, just register the writes. But I'm not sure where to disable it. HWASan has [hwasan_platform_interceptors.h](https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/hwasan/hwasan_platform_interceptors.h), where lots of interceptors are disabled, but I can't find an equivalent place for ASan.
> 
> The additional link dependency might also be temporary: my impression is that glibc [wants to integrate](https://sourceware.org/pipermail/libc-alpha/2021-August/129718.html) [all sublibraries](https://developers.redhat.com/articles/2021/12/17/why-glibc-234-removed-libpthread) into the main library.

They need to  be moved from sanitizer_common into msan_iterceptors

**Comment by vitalybuka** [comment]
> I have no problem with moving in the opposite direction, but maybe this comment should be removed? Maybe interceptors should only move into the common area if they're actually interesting for multiple sanitizers?

yes, this does not look relevant to me

**Comment by aaronpuchert** [comment]
Posted the move as separate pull request #119071, will close this change if that is approved.

**Review by vitalybuka — CHANGES_REQUESTED** [review]
I assume we  go with another one

**Comment by aaronpuchert** [comment]
We decided to move the interceptors to MSan instead, so this change is no longer needed.

**Pull request closed without merging**
