### PR TITLE
[Clang] Handle structs with inner structs and no fields (#89126)

### PR DESCRIPTION
**Pull request by bwendling**
A struct that declares an inner struct, but no fields, won't have a field count. So getting the offset of the inner struct fails. This happens in both C and C++:

  struct foo {
    struct bar {
      int Quantizermatrix[];
    };
  };

Here 'struct foo' has no fields.

Closes: https://github.com/llvm/llvm-project/issues/88931

### CODE REVIEW

**Comment by bwendling** [comment]
Okay...I think this works now?

**Comment by efriedma-quic** [comment]
Looks fine.

**Comment by tstellar** [comment]
Hi @bwendling (or anyone else). If you would like to add a note about this fix in the release notes (completely optional). Please reply to this comment with a one or two sentence description of the fix.  When you are done, please add the release:note label to this PR.

**Comment by bwendling** [comment]
Fixed an issue with the counted_by attribute on a flexible array member in an inner struct.

**Pull request merged**
