### PR TITLE
release/18.x [X86_64] fix SSE type error in vaarg

### LINKED ISSUE #86371: [X86_64] va_arg with SSE type get error
demo.c
```c
#include <stdlib.h>
#include <stdio.h>
#include <string.h>

struct S271 { union{}a; double b;} ;
struct S271 s271;
void check271va (int z, ...) {
    struct S271 arg;
    va_list ap;
    __builtin_va_start(ap, z);
    arg = __builtin_va_arg(ap, struct S271);
    long double a = __builtin_va_arg(ap, long double);
    printf("%Lf\n", a);
    if (a != 2.0L)
       printf("Fail\n");
    __builtin_va_end(ap);
}
int main (void) {
    printf("%lu\n", sizeof(s271));
    check271va (2, s271, 2.0L);
}
```
clang
```
16
0.000000
Fail
```
gcc
```
16
2.000000
```
https://godbolt.org/z/o6v318vWM

### PR DESCRIPTION
**Pull request by AZero13**
tweak the position of the ++neededSSE when Lo is NoClass and Hi is SSE. Fix #86371.

(cherry picked from commit 9c8dd5e6f6bd93deb95de9642632223f54a18a11)

### CODE REVIEW

**Comment by efriedma-quic** [comment]
Is there some reason you think we should take this specific patch, out of all the x86 ABI fixes going in recently?  It isn't a regression, as far as I know.

**Comment by AtariDreams** [comment]
> Is there some reason you think we should take this specific patch, out of all the x86 ABI fixes going in recently?  It isn't a regression, as far as I know.

It's a miscompile

**Comment by tstellar** [comment]
@phoebewang What do you think about backporting this?

**Comment by phoebewang** [comment]
> @phoebewang What do you think about backporting this?

I think the patch doesn't fix all problem in #86371, suggest to reevaluate it. @efriedma-quic may take another look.

**Comment by RKSimon** [comment]
What are the current rules on cherry picks for old bugs? AFAICT this patch wasn't fixing a bug introduced in the 17.x-18.x development region.

**Comment by efriedma-quic** [comment]
Right, the policy doesn't say we can only take regression fixes.  We just need to weight the impact vs. the risk.

Looking at the latest conversation on the bug report this case is pretty clearly still broken.  It's improved in the sense that after the va_arg of the struct, subsequent va_arg calls produce the right value.  But the va_arg iteslf doesn't produce the right value (probably we aren't copying the struct correctly).  So that would be a regression for some cases.

Given that, we probably don't want to pull this into 18.x as-is.

Also, given that we're making other fixes to the surrounding code, pulling any one fix into 18.x seems risky to me.  And probably low-impact, given the testcases appear to be generated by a fuzzer.

**Comment by nikic** [comment]
Closing this as rejected per previous comments.

**Pull request closed without merging**
