### PR TITLE
fix: asan support aarch64be

### PR DESCRIPTION
**Pull request by hstk30-hw**
fix bad `Offset` for aarch64be asan

### CODE REVIEW

**Review by vitalybuka — APPROVED** [review]

**Comment by hstk30-hw** [comment]
What's the problem about the CI? @vitalybuka 
What can I do to pass it?

**Comment by asl** [comment]
@joker-eph @boomanaiden154 Have you intentionally added unrelated commits to this PR?

**Comment by boomanaiden154** [comment]
Shoot. Definitely not intentional. I was using this PR as a test for working on the code formatting action (https://github.com/llvm/llvm-project/pull/69766) as it currently fails on that action in an interesting way. It looks like I got my branches mixed up when pushing it to my fork and bumping some things to invoke the pipeline.

Looks like I should be able to just force push and remove my commits given there aren't any inline reviews?

**Comment by asl** [comment]
> Looks like I should be able to just force push and remove my commits given there aren't any inline reviews?

Right

**Comment by boomanaiden154** [comment]
Force pushed and the original two commits are there now. Sorry for the noise. I will be taking more measures next time when testing the CI to significantly reduce the probability of this happening again.

**Comment by rorth** [comment]
This patch broke both the [Solaris/sparcv9](https://lab.llvm.org/buildbot/#/builders/72/builds/43) and [Solaris/amd64](https://lab.llvm.org/staging/#/builders/8/builds/752) buildbots.  I guess it needs to either require `aarch64-registered-target` or pass `-data-layout=` like `freebsd.ll`.

**Pull request merged**
