### PR TITLE
[docs] Fix malformed csv files

### PR DESCRIPTION
**Pull request by wusatosi**
This commit includes fixes malformed csv files:
FormatPaper.csv
FormatIssues.csv
Cxx23Issues.csv
Cxx23Papers.csv
Cxx20Issues.csv
FormatIssues.csv
ZipProjects.csv

These are all the csv files in this repository that is malformed (reported by [csval](https://github.com/travishorn/csval)), most of them are missing the "label" column.

Note that csv files under "./libcxx/test/libcxx/transitive_includes/" are space-separated but not comma-separated, which may not be conforming to the csv specification, but is not included in this PR.

I can setup a GitHub CI validating the updated csv file in another pr if that would be desired.

### CODE REVIEW

**Comment by philnik777** [comment]
What problem does this solve?

**Comment by wusatosi** [comment]
> What problem does this solve?

The listed csv files are currently malformed.

Currently this does not impact document generation on llvm side, but it prevents outside scripts from analyzing these files, like [GitHub](https://github.com/llvm/llvm-project/blob/main/libcxx/docs/Status/FormatPaper.csv).

**Review by ldionne — COMMENTED** [review]
IMO this makes sense, but could we add the CSV validation in this PR? Otherwise there’s no « testing » for this change.

**Comment by wusatosi** [comment]
> IMO this makes sense, but could we add the CSV validation in this PR? Otherwise there’s no « testing » for this change.


Technically you can check this pr by just looking at the csv file on GitHub

Broken (current):
https://github.com/llvm/llvm-project/blob/1b03cbc93989c84ad0b78c27d4427a7eaa5842f1/libcxx/docs/Status/FormatPaper.csv
Fixed:
https://github.com/wusatosi/llvm-project/blob/91963d8d02ee1cffea6b0a1da2f9b5bee2b08c4f/libcxx/docs/Status/FormatPaper.csv

But yes this definitely needs to be in the CI.

What is the standard for adding code-format check in CI? Should I add this functionality as a stand-alone CI file, or should I add this into `code-format-helper.py`?

**Comment by ldionne** [comment]
@wusatosi What dependencies do you need to implement this check? If there are basically no dependencies that need to be installed, I would add it so that it gets checked as part of `check-cxx`, I think. But otherwise I would probably add it to `.github/workflows/libcxx-check-generated-files.yml` (and rename that file to something like `libcxx-lightweight-checks.yml`.

**Comment by wusatosi** [comment]
> @wusatosi What dependencies do you need to implement this check? If there are basically no dependencies that need to be installed, I would add it so that it gets checked as part of `check-cxx`, I think. But otherwise I would probably add it to `.github/workflows/libcxx-check-generated-files.yml` (and rename that file to something like `libcxx-lightweight-checks.yml`.

Thanks for the reply, a simple python script should be sufficient, I don't think we need another Action.

I am not familiar with the CI so I don't really understand what "check-cxx" pipeline you are referring to.

By name, it looks like `Test documentation build` and `check code formatting` pipelines sounds like a good place to put in, though technically broken CSV doesn't break the documentation generation. 

Is there any CI person I can consult on where to put this check in?

**Comment by mordante** [comment]
>  a simple python script should be sufficient

Do you have an example of that script?

> Is there any CI person I can consult on where to put this check in?

The best place to ask questions is the #libcxx channel on [LLVM’s Discord server](https://discord.gg/jzUbyP26tQ).

**Comment by philnik777** [comment]
Is there any interest in pursuing this? If not, let's close this PR.

**Comment by ldionne** [comment]
Tentatively closing to clear up the review queue, please reopen if you want to pursue.

**Pull request closed without merging**
