### PR TITLE
[bazel] Update to 7.x

### PR DESCRIPTION
**Pull request by keith**

### CODE REVIEW

**Review by aaronmondal — APPROVED** [review]
Cool! I'll also take another look at https://github.com/llvm/llvm-project/issues/55924.

**Comment by durin42** [comment]
This seems to be [pretty](https://buildkite.com/llvm-project/upstream-bazel/builds/92741#018e673d-6bac-4aba-a2d1-a398003d7aad) [broken](https://buildkite.com/llvm-project/upstream-bazel/builds/92742#018e674a-505b-47c2-9a2a-784b597e2a03) (included both links because for some reason the first run including this change truncated the output) on the buildkite for bazel - I can reproduce locally with `USE_BAZEL_VERSION=7.1.1 bazelisk build --config=ci --config=generic_clang @llvm-project//llvm/unittests:SupportTests` which fails like this:
```
ERROR: [...]llvm-project/llvm/unittests/BUILD.bazel:633:8: Compiling llvm/unittests/Support/DebugTest.cpp failed: undeclared inclusion(s) in rule '@@llvm-project//llvm/unittests:SupportTests':
this rule is missing dependency declarations for the following files included by 'llvm/unittests/Support/DebugTest.cpp':
  'bazel-out/k8-fastbuild/bin/external/llvm-project/llvm/Demangle.cppmap'
  'bazel-out/k8-fastbuild/bin/external/llvm_zlib/zlib.cppmap'
  'bazel-out/k8-fastbuild/bin/external/llvm_zstd/zstd.cppmap'
  'bazel-out/k8-fastbuild/bin/external/llvm-project/llvm/BitstreamReader.cppmap'
[elided many more cppmap lines]
```
I don't know enough bazel to be of use here, but it seems like there must be a discrepancy in a rule implementation somehow?

**Comment by keith** [comment]
working on the reland + a fix here https://github.com/llvm/llvm-project/pull/86326

**Comment by durin42** [comment]
> thanks for linking, merged a revert here to unblock #86325
> 
> do you know if there is a way I can run those CI jobs on my change? on my linux x86 machine with your command I don't see the same issue

I wish I did! It took some futzing to get it to reproduce for me, and while I _thought_ the `--config=ci` was the magic I'm not entirely sure it was. I'll ask around if anyone can provide advice on a better way to reproduce. :/

**Pull request merged**
