### PR TITLE
Fixed un-renamed CodeGenTargetMachineImpl Intheritances in Experimental Targets

### PR DESCRIPTION
**Pull request by matinraayai**
This PR fixes a set of build issues with experimental targets happened in result of merging #111234 to master.

### CODE REVIEW

**Review by arsenm — APPROVED** [review]

**Comment by arsenm** [comment]
> ⚠️ We detected that you are using a GitHub private e-mail address to contribute to the repo. Please turn off [Keep my email addresses private](https://github.com/settings/emails) setting in your account. See [LLVM Discourse](https://discourse.llvm.org/t/hidden-emails-on-github-should-we-do-something-about-it) for more information.

Should fix this

**Comment by matinraayai** [comment]
> > ⚠️ We detected that you are using a GitHub private e-mail address to contribute to the repo. Please turn off [Keep my email addresses private](https://github.com/settings/emails) setting in your account. See [LLVM Discourse](https://discourse.llvm.org/t/hidden-emails-on-github-should-we-do-something-about-it) for more information.
> 
> Should fix this

My email address should be public now.

**Comment by matinraayai** [comment]
@arsenm I replaced some leftover mentions of `LLVMTargetMachine` in the comments. I built the experimental targets on my end and it seems to build fine, and the tests pass on my end. Let me know if there's anything else I need to fix on my part.
Sorry for breaking change.

**Review by bogner — APPROVED** [review]
Looks good!

**Review by llvm-beanz — APPROVED** [review]

**Pull request merged**
