### PR TITLE
[libc] Sort entrypoints alphabetically

### PR DESCRIPTION
**Pull request by petrhosek**
This makes it easier to diff the different configurations.

### CODE REVIEW

**Comment by petrhosek** [comment]
Going forward it'd be helpful if we had an automated way to enforce this.

**Review by jhuber6 — APPROVED** [review]
I like the concept. Did you do this with a script? I forsee us needing to do this more than once.

**Review by lntue — APPROVED** [review]

**Review by michaelrj-google — APPROVED** [review]

**Comment by lntue** [comment]
> I like the concept. Did you do this with a script? I forsee us needing to do this more than once.

I guess in the meantime @petrhosek can put the script in `libc/utils` folder for everyone to run before committing.

**Comment by petrhosek** [comment]
> > I like the concept. Did you do this with a script? I forsee us needing to do this more than once.
> 
> I guess in the meantime @petrhosek can put the script in `libc/utils` folder for everyone to run before committing.

No, I did it manually but in hindsight I should have written a script because it was more effort than I expected (but it's also possible that my Vim-fu is just not good enough).

**Pull request merged**
