### PR TITLE
[NFC] Fix flakiness in test if run unsharded

### PR DESCRIPTION
**Pull request by vitalybuka**
If we run all test in a single process, there is high
probability that `99` is already claimed.

### CODE REVIEW

**Comment by fmayer** [comment]
(I was told to use `skip-presubmit-approval` label for CLs that I don't want reviewed)

**Comment by vitalybuka** [comment]
> (I was told to use `skip-presubmit-approval` label for CLs that I don't want reviewed)

I don't know meaning of this label, I can find only https://lists.llvm.org/pipermail/cfe-commits/Week-of-Mon-20240722/601293.html which seems irrelevant.

**Comment by fmayer** [comment]
image

**Comment by vitalybuka** [comment]
Ok, it's documented, but it has a different name https://llvm.org/docs/CodeReview.html#code-review-workflow

**Pull request merged**
