### PR TITLE
[Offload] Add support for loongarch64 to host plugin

### PR DESCRIPTION
**Pull request by wangleiat**
This adds support for the loongarch64 architecture to the offload host
plugin.

Similar to #115773

To fix some test issues, I've had to add the LoongArch64 target to:

- CompilerInvocation::ParseLangArgs
- linkDevice in ClangLinuxWrapper.cpp
- OMPContext::OMPContext (to set the device_kind_cpu trait)

### CODE REVIEW

**Comment by jhuber6** [comment]
Does this actually work?

**Comment by wangleiat** [comment]
> Does this actually work?

I executed the `ninja check-offload` command on `LoongArch64`, and the results are as follows:

Befor [commit](https://github.com/llvm/llvm-project/pull/120173/commits/7edfb3eb052643ebe2f4bc750cd96d980f782a84): 
```         
Total Discovered Tests: 658
Unsupported: 320 (48.63%)  
Passed     :  30 (4.56%)   
Failed     : 308 (46.81%)  
```                           
After:
```          
Total Discovered Tests: 658
Unsupported: 320 (48.63%)  
Passed     : 296 (44.98%)  
Failed     :  42 (6.38%)   
```

**Review by jhuber6 — APPROVED** [review]
Thanks, I don't have any way to test this but it's pretty straightforward.

**Comment by jplehr** [comment]
Is there the possibility to set up a buildbot for this architecture?

**Comment by wangleiat** [comment]
> Is there the possibility to set up a buildbot for this architecture?

Hi @SixWeining, do we have any plans to add more buildbots?

**Comment by SixWeining** [comment]
> Is there the possibility to set up a buildbot for this architecture?

There is a [buildbot](https://lab.llvm.org/staging/#/builders/20) for loongarch, but it only run tests for clang and llvm-test-suite.

Do you mean adding a dedicate buildbot for the `offload` sub-project? I think the answer is yes. Actually we plan to setup more buildbots for any other sub-projects, including `flang`, `lld` and `openmp`, etc.

**Comment by jplehr** [comment]
> Do you mean adding a dedicate buildbot for the `offload` sub-project? I think the answer is yes. Actually we plan to setup more buildbots for any other sub-projects, including `flang`, `lld` and `openmp`, etc.

Not necessarily a dedicated buildbot for the `offload` project, but some bot that covers this particular code path. So it's great to hear that you have plans to put up bot(s) for the various projects.

**Pull request merged**
