### PR TITLE
[C API] Support new ptrauth constant type

### PR DESCRIPTION
**Pull request by Benjins**
This is a new constant type that was added to the C++ API in 0edc97f119f3ac3ff96b11183fe5c001a48a9a8d. This adds the ability to create instances of this constant and get its values to the C API

### CODE REVIEW

**Comment by Benjins** [comment]
The clang-format diff is on the `LLVM_FOR_EACH_VALUE_SUBCLASS` macro, which it tries to indent weirdly. If there's a preferred way of dealing with it I can push changes, but I assume the naive auto-formatted output isn't what we want

**Review by nikic — APPROVED** [review]
This looks good to me.

@ahmedbougacha @asl Is there any risk that something about `ptrauth` constants will change in the near future (in ways that would affect stability of the C API)?

**Comment by asl** [comment]
> @ahmedbougacha @asl Is there any risk that something about `ptrauth` constants will change in the near future (in ways that would affect stability of the C API)?

Given the stability guarantees of C API, I would wait until we will have end-to-end implementation from frontend to backend just in case.

**Comment by Benjins** [comment]
Merged from main and added some annotations to skip clang formatting on the macro it had trouble with

> Given the stability guarantees of C API, I would wait until we will have end-to-end implementation from frontend to backend just in case.

@asl From the commit history, it seems like `ptrauth` constants are now used in Clang and the AArch64 backend. It seems like the fields for `ConstantPtrAuth` are the same as before. Does this PR seem good to land now?

https://github.com/llvm/llvm-project/blob/5b310a1c3c5aabae325934a6475e93ea8b71cdc2/llvm/include/llvm/IR/Constants.h#L1026-L1027

**Comment by asl** [comment]
> Merged from main and added some annotations to skip clang formatting on the macro it had trouble with
> 
> > Given the stability guarantees of C API, I would wait until we will have end-to-end implementation from frontend to backend just in case.
> 
> @asl From the commit history, it seems like `ptrauth` constants are now used in Clang and the AArch64 backend. It seems like the fields for `ConstantPtrAuth` are the same as before. Does this PR seem good to land now?
> 
> https://github.com/llvm/llvm-project/blob/5b310a1c3c5aabae325934a6475e93ea8b71cdc2/llvm/include/llvm/IR/Constants.h#L1026-L1027

 Yes, I think we can consider these to be stable now. Thanks!

**Pull request merged**
