### PR TITLE
[DWARFLinkerParallel] Add support for -odr mode.

### PR DESCRIPTION
**Pull request by avl-llvm**
This patch is extracted from D96035, it adds support for the type deduplication mode. With this patch DWARFLinkerParallel handles --odr option. It also processes clang modules.

run-time performance and memory requirements for clang binary --num-threads 16 :
    
```
------------------------------------------------------------------------------
                                |  time, sec   |  mem, GB  | .debug_info, MB |
------------------------------------------------------------------------------
dsymutil --odr --linker llvm    |      45      |     13    |       192       |
------------------------------------------------------------------------------
dsymutil --odr --linker apple   |     115      |     11    |       561       |
------------------------------------------------------------------------------

```    
run-time performance and memory requirements for clang binary --num-threads 1 :
    
```
------------------------------------------------------------------------------
                                |  time, sec   |  mem, GB  | .debug_info, MB |
------------------------------------------------------------------------------
dsymutil --odr --linker llvm    |     236      |    12.6   |       192       |
------------------------------------------------------------------------------
dsymutil --odr --linker apple   |     187      |    10.0   |       561       |
------------------------------------------------------------------------------

```    
Note: Sometimes DWARFLinkerParallel may produce non-deterministic results.
The reason for that is ambiguous input DWARF. That problem is assumed
to be solved with separate patches(most probably not for DWARFLinkerParallel
but for generated DWARF).
    
Note: The dependency tracking algorithm handles DW_TAG_imported_module and
DW_TAG_imported_declaration differently than current DWARFLinker. Current
DWARFLinker keeps all content referenced by DW_AT_import attribute despite
the fact whether it references live code or not. This patch keeps only DIEs
referencing live addresses(and all their dependencies)

### CODE REVIEW

**Comment by JDevlieghere** [comment]
Why is the debug info section so much smaller when using the parallel linker? Is it really that much more efficient than the Apple one, and if so, where are the gains coming from? Are we eliminating types that the dsymutil isn't, like base types? I'm a little skeptical, but I can also imagine the new approach is a lot better because it doesn't need to keep things like forward declarations until it sees a definition, etc. 

> Note: Sometimes DWARFLinkerParallel may produce non-deterministic results.

I know you're aware but I'll emphasize again that that's a non-starter for us. It sounds like you have patches in the works so that's great!

**Comment by avl-llvm** [comment]
> Why is the debug info section so much smaller when using the parallel linker? Is it really that much more efficient than the Apple one, and if so, where are the gains coming from? Are we eliminating types that the dsymutil isn't, like base types? I'm a little skeptical, but I can also imagine the new approach is a lot better because it doesn't need to keep things like forward declarations until it sees a definition, etc.

yes, the size of debug info is smaller because the parallel linker does ODR deduplication differently:

1. The most space-saving thing is types merging(*). Parallel linker creates
an artificial compile unit and moves all types into this unit. All variations
of partially defined type are finally combined into the single type description.
This saves most of the space. f.e.

llvm-xray built with llvm linker:
```
llvm-dwarfdump --debug-info llvm-xray.dSYM/Contents/Resources/DWARF/llvm-xray | grep -c "\(\"vector<unsigned char, std::__1::allocator<unsigned char> >\"\)"
1

```
llvm-xray built with apple linker:
```
llvm-dwarfdump --debug-info llvm-xray.dSYM/Contents/Resources/DWARF/llvm-xray | grep -c "\(\"vector<unsigned char, std::__1::allocator<unsigned char> >\"\)"
140

```
2. Forward declarations are removed. The type(if the definition is found) or single type declaration
is moved into the artificial compile unit. All other copies of the declaration are removed.

3. Not used content of imported namespaces is removed.


> 
> > Note: Sometimes DWARFLinkerParallel may produce non-deterministic results.
> 
> I know you're aware but I'll emphasize again that that's a non-starter for us. It sounds like you have patches in the works so that's great!

yes, I intend to have deterministic output. I think it would be better to achieve this goal with separate patches as the current patch is already huge. The problem that leads to non-deterministic output is caused by inconsistent DWARF(**). It contains different definitions for the same type. So the definition that would be put in the result depends on which definition was handled earlier(which is non-deterministic). I think the proper way to fix that problem would be to fix Clang's DWARF generation to produce consistent results. 


(*) Example of types merging:

Lets assume we have following types:
```

CU1 {
  DW_TAG_class_type {
      DW_TAG_name "vector"
      DW_AT_declaration (true)
      
      DW_TAG_subprogram {
          DW_TAG_name "push_back"
      }
  }
  
 DW_TAG_typedef
   DW_AT_Name "vector"
   DW_AT_type CU1::vector
}

CU2 {
  DW_TAG_class_type {
      DW_TAG_name "vector"
      DW_AT_declaration (true)
      
      DW_TAG_subprogram {
          DW_TAG_name "empty"
      }
  }

  
 DW_TAG_typedef
   DW_AT_Name "vector"
   DW_AT_type CU2::vector  
}

```
Above partial definitions would be united into single one:

```
TYPE_CU {
  DW_TAG_class_type {
      DW_TAG_name "vector"
      DW_AT_declaration (true)
      
      DW_TAG_subprogram {
          DW_TAG_name "push_back"
      }
      DW_TAG_subprogram {
          DW_TAG_name "empty"
      }      
  }
}

CU1 {
 DW_TAG_typedef
   DW_AT_Name "vector"
   DW_AT_type TYPE_CU::vector
}

CU2 { 
 DW_TAG_typedef
   DW_AT_Name "vector"
   DW_AT_type TYPE_CU::vector  
}

```
(**) Example of inconsistent DWARF:

1. opt binary.

compile unit "llvm/tools/opt/opt.cpp" has following definition:

```
0x001c4067:     DW_TAG_class_type
                  DW_AT_calling_convention      (DW_CC_pass_by_reference)
                  DW_AT_name    ("DominatorTreeBase<llvm::BasicBlock, false>")
                  DW_AT_byte_size       (0x50)
                  DW_AT_decl_file       ("llvm-project/llvm/include/llvm/IR/Dominators.h")
                  DW_AT_decl_line       (51)

0x001c4090:       DW_TAG_member
                    DW_AT_name  ("Insert")
                    DW_AT_type  (0x002aa3e4 "const UpdateKind")
                    DW_AT_decl_file     ("llvm-project/llvm/include/llvm/Support/GenericDomTree.h")
                    DW_AT_decl_line     (258)
                    DW_AT_external      (true)
                    DW_AT_declaration   (true)
                    DW_AT_accessibility (DW_ACCESS_public)

```
while compile unit "llvm/lib/Target/X86/X86LowerAMXIntrinsics.cpp" has a bit different:

```
0x010f6214:     DW_TAG_class_type
                  DW_AT_calling_convention      (DW_CC_pass_by_reference)
                  DW_AT_name    ("DominatorTreeBase<llvm::BasicBlock, false>")
                  DW_AT_byte_size       (0x50)
                  DW_AT_decl_file       ("llvm-project/llvm/include/llvm/IR/Dominators.h")
                  DW_AT_decl_line       (51)

0x010f623d:       DW_TAG_member
                    DW_AT_name  ("Insert")
                    DW_AT_type  (0x011774c9 "const UpdateKind")
                    DW_AT_decl_file     ("llvm-project/llvm/include/llvm/Support/GenericDomTree.h")
                    DW_AT_decl_line     (258)
                    DW_AT_external      (true)
                    DW_AT_declaration   (true)
                    DW_AT_accessibility (DW_ACCESS_public)
                    DW_AT_const_value   (0)   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<

```

2. llvm-xray binary.

compile unit "llvm/lib/Bitcode/Reader/BitcodeReader.cpp" has following definition:

```
0x0260e77a:     DW_TAG_class_type
                  DW_AT_calling_convention      (DW_CC_pass_by_reference)
                  DW_AT_name    ("SmallVectorImpl<llvm::Instruction *>")
                  DW_AT_byte_size       (0x10)
                  DW_AT_decl_file       ("llvm-project/llvm/include/llvm/ADT/SmallVector.h")
                  DW_AT_decl_line       (577)

0x0260e784:       DW_TAG_template_type_parameter
                    DW_AT_type  (0x026cb21f "llvm::Instruction *")
                    DW_AT_name  ("T")   <<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<<

```
while compile unit "llvm/lib/IR/SSAContext.cpp" has a bit different:

```
0x03659f68:     DW_TAG_class_type
                  DW_AT_calling_convention      (DW_CC_pass_by_reference)
                  DW_AT_name    ("SmallVectorImpl<llvm::Instruction *>")
                  DW_AT_byte_size       (0x10)
                  DW_AT_decl_file       ("llvm-project/llvm/include/llvm/ADT/SmallVector.h")
                  DW_AT_decl_line       (577)

0x03659f72:       DW_TAG_template_type_parameter
                    DW_AT_type  (0x036716fa "llvm::Instruction *")
```

**Comment by dwblaikie** [comment]
DWARFLinker would still need to be deterministic, even on old/bad/different input - though maybe Apple & other folks would be open to it having an error on "bad" input rather than having to figure out a way to have a deterministic successful output.

That said - I'm always here for a conversation about type consistency in DWARF... so let's take a look:

`DominatorTreeBase<llvm::BasicBlock, false>` example - `Insert` is a `static constexpr SomeEnum` member with an in-class initializer.
Hmm, that might be tricky to do - because technically this isn't a definition (there may be no storage behind it) so I'm not sure we could move the const value out into a separate definition DIE. I guess a definition DIE without a DW_AT_location would be the nearest DWARF-ish way to express it. We /might/ be able to always instantiate the definition value, so put it on the declaration in all cases, but would need some language expertise to check if that's do-able.

`SmallVectorImpl<llvm::Instruction *>` example - I'm not sure why we'd sometimes put the parameter name in and sometimes not. That seems unlikely to be intentional/particularly deeply thought out, but of uncertain difficulty to fix.

**Comment by avl-llvm** [comment]
> DWARFLinker would still need to be deterministic, even on old/bad/different input - though maybe Apple & other folks would be open to it having an error on "bad" input rather than having to figure out a way to have a deterministic successful output.
> 
that could be done with the cost of slower execution.
Currently, first met definition is copied into the resulting DWARF and all other declarations/definitions are skipped.
Instead all met declarations/definitions could be united. i.e. final type description would have attributes from all type copies. In that case final DWARF would be the same despite of the order of compile units handling.

> That said - I'm always here for a conversation about type consistency in DWARF... so let's take a look:
> 
> `DominatorTreeBase<llvm::BasicBlock, false>` example - `Insert` is a `static constexpr SomeEnum` member with an in-class initializer. Hmm, that might be tricky to do - because technically this isn't a definition (there may be no storage behind it) so I'm not sure we could move the const value out into a separate definition DIE. I guess a definition DIE without a DW_AT_location would be the nearest DWARF-ish way to express it. We /might/ be able to always instantiate the definition value, so put it on the declaration in all cases, but would need some language expertise to check if that's do-able.

Speaking of original example, Do I correctly understand that "DW_AT_const_value   (0)" should be in both type definition copies(0x001c4090 and 0x010f623d) in currently generated DWARF?

> 
> `SmallVectorImpl<llvm::Instruction *>` example - I'm not sure why we'd sometimes put the parameter name in and sometimes not. That seems unlikely to be intentional/particularly deeply thought out, but of uncertain difficulty to fix.

**Comment by avl-llvm** [comment]
> > DWARFLinker would still need to be deterministic, even on old/bad/different input
> 
> +1
> 
> > though maybe Apple & other folks would be open to it having an error on "bad" input rather than having to figure out a way to have a deterministic successful output.
> 
> As long as the input DWARF is valid, we need to be able to link it. Maybe a slow path would be okay if we can guarantee our toolchain doesn't trigger it (i.e. clang & Swift).

yes, more slower but deterministic handling is in my future plans. And we can use slower version with unknown sources and faster version with DWARF generated by clang&Swift (if inconsistent cases would be resolved).

**Comment by dwblaikie** [comment]
> > That said - I'm always here for a conversation about type consistency in DWARF... so let's take a look:
> > `DominatorTreeBase<llvm::BasicBlock, false>` example - `Insert` is a `static constexpr SomeEnum` member with an in-class initializer. Hmm, that might be tricky to do - because technically this isn't a definition (there may be no storage behind it) so I'm not sure we could move the const value out into a separate definition DIE. I guess a definition DIE without a DW_AT_location would be the nearest DWARF-ish way to express it. We /might/ be able to always instantiate the definition value, so put it on the declaration in all cases, but would need some language expertise to check if that's do-able.
> 
> Speaking of original example, Do I correctly understand that "DW_AT_const_value (0)" should be in both type definition copies(0x001c4090 and 0x010f623d) in currently generated DWARF?

I'm not actually sure. I'm not sure if we can always compute the value reliably in every context (some parts of templates we're not allowed to instantiate only in certain contexts).

If we couldn't do it in all cases, maybe we could not put the value on the declaration in all cases - and use a definition DIE to attach the value to (& not put a DW_AT_location on that definition, because it might not have storage in translation units, etc).

**Comment by avl-llvm** [comment]
> > Speaking of original example, Do I correctly understand that "DW_AT_const_value (0)" should be in both type definition copies(0x001c4090 and 0x010f623d) in currently generated DWARF?
> 
> I'm not actually sure. I'm not sure if we can always compute the value reliably in every context (some parts of templates we're not allowed to instantiate only in certain contexts).
> 
> If we couldn't do it in all cases, maybe we could not put the value on the declaration in all cases - and use a definition DIE to attach the value to (& not put a DW_AT_location on that definition, because it might not have storage in translation units, etc).

I see. Thank you for elaborations.

**Comment by avl-llvm** [comment]
friendly ping.

**Comment by avl-llvm** [comment]
friendly ping.

**Comment by avl-llvm** [comment]
@JDevlieghere @adrian-prantl are there anything which should be done with this patch before integration?

**Comment by JDevlieghere** [comment]
Did we come up with a solution for determinism that doesn't depend on the generator? My understanding was that we're okay with taking a penalty in terms of performance, but does the code reflect this, or will the current version of this patch still generate non-deterministic results with other producers or older version of clang that don't have Michael's changes?

**Comment by avl-llvm** [comment]
> Did we come up with a solution for determinism that doesn't depend on the generator? My understanding was that we're okay with taking a penalty in terms of performance, but does the code reflect this, or will the current version of this patch still generate non-deterministic results with other producers or older version of clang that don't have Michael's changes?

This version of patch will produce non-deterministic results if input have non-consistent DWARF(these are old-producers and current clang(even with Michael's patch)). I proposed to implement full-deterministic version as a follow-up patch. Current patch is already huge and it would be good to reduce it's size. I suggest following order of patches:

1. this patch.
2. patch refactoring directory structure. So that DWARFLinker directory contains code for common library, Apple linker, LLVM linker.
3. add --deterministic cl option.
4. implement full deterministic mode which will produce deterministic output for current clang and old-producers.

What do you think?

**Review by JDevlieghere — APPROVED** [review]
Works for me 👍

**Comment by avl-llvm** [comment]
Thanks!

**Comment by mgorny** [comment]
This change broke building on 32-bit platforms, see #73267.

**Comment by avl-llvm** [comment]
> This change broke building on 32-bit platforms, see #73267.

The fix for that problem https://github.com/llvm/llvm-project/pull/73388

**Pull request merged**
