### PR TITLE
[lldb-dap] Skip the lldb-dap output test on windows, it seems all the lldb-dap tests are disabled on windows.

### PR DESCRIPTION
**Pull request by ashgti**
This should fix https://lab.llvm.org/buildbot/#/builders/141/builds/1747

### CODE REVIEW

**Review by walter-erquinigo — APPROVED** [review]

**Comment by DavidSpickett** [comment]
Does anyone know why these tests are disabled, is there one underlying reason?

**Comment by walter-erquinigo** [comment]
@DavidSpickett I think this has been mostly an issue with the fact that no one has tried long enough to make lldb-dap work nicely on windows. But I'm sure most tests should just pass without too much effort.

**Comment by DavidSpickett** [comment]
Cool, I'll try them when I've got some spare time.

**Comment by walter-erquinigo** [comment]
> Cool, I'll try them when I've got some spare time.

I'd very much appreciate it. I sometimes have time, but I don't even have access to a proper Windows machine to make that work :(

**Pull request merged**
