### PR TITLE
[Driver] Ensure ToolChain::LibraryPaths is not empty for non-Darwin

### LINKED ISSUE #87150: [Driver] Old compiler-rt library name (e.g. libclang_rt.builtins-aarch64.a) is reported when neither old/new library directory exists
When we build llvm with this cmd

```
cmake ../llvm -G Ninja -DLLVM_DEFAULT_TARGET_TRIPLE=aarch64-linux-gnu -DLLVM_USE_LINKER=lld -DLLVM_ENABLE_RUNTIMES="compiler-rt;libunwind" -DLLVM_ENABLE_PROJECTS="mlir;clang;clang-tools-extra;lld" -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_BUILD_TYPE=RelWithDebInfo
```

It builds successfully, while if we try do something like

```
./bin/clang --rtlib=compiler-rt hello.c
```

Something wrong happens
```
/usr/bin/aarch64-linux-gnu-ld: cannot find <PATH>/build-aarch64/lib/clang/19/lib/linux/libclang_rt.builtins-aarch64.a: No such file or directory
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

`libclang_rt.builtins-aarch64.a` does exists, while in a different path, with a different name
```
./lib/clang/19/lib/aarch64-linux-gnu/libclang_rt.builtins.a
```

### PR DESCRIPTION
**Pull request by MaskRay**
Follow-up to #81037.

ToolChain::LibraryPaths holds the new compiler-rt library directory
(e.g. `/tmp/Debug/lib/clang/19/lib/x86_64-unknown-linux-gnu`). However,
it might be empty when the directory does not exist (due to the `if
(getVFS().exists(P))` change in https://reviews.llvm.org/D158475).

If neither the old/new compiler-rt library directories exists, we would
suggest the undesired old compiler-rt file name:

```
% /tmp/Debug/bin/clang++ a.cc -fsanitize=memory -o a
ld.lld: error: cannot open /tmp/Debug/lib/clang/19/lib/linux/libclang_rt.msan-x86_64.a: No such file or directory
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
```

With this change, we will correctly suggest the new compiler-rt file name.

Fix #87150

### CODE REVIEW

**Review by wzssyqa — APPROVED** [review]

**Comment by mstorsjo** [comment]
This seems to have had an unexpected effect. In a build where I don't use the new path style, I used to get the old path style returned like this:
```
$ clang -target x86_64-w64-mingw32 -print-runtime-dir
/home/martin/clang-nightly/lib/clang/19/lib/windows
```
However after this change, now I'm getting the new style path, even if it doesn't exist, and if the old one actually did exist:
```
$ clang -target x86_64-w64-mingw32 -print-runtime-dir
/home/martin/clang-nignhtly/lib/clang/19/lib/x86_64-w64-windows-gnu
```
I'm ok with changing the default if the old path style doesn't exist - but if it does exist, we should still return that. (I haven't dig into it to see why this is, yet.)

**Comment by mstorsjo** [comment]
> This seems to have had an unexpected effect. In a build where I don't use the new path style, I used to get the old path style returned like this:
> 
> ```
> $ clang -target x86_64-w64-mingw32 -print-runtime-dir
> /home/martin/clang-nightly/lib/clang/19/lib/windows
> ```
> 
> However after this change, now I'm getting the new style path, even if it doesn't exist, and if the old one actually did exist:
> 
> ```
> $ clang -target x86_64-w64-mingw32 -print-runtime-dir
> /home/martin/clang-nignhtly/lib/clang/19/lib/x86_64-w64-windows-gnu
> ```
> 
> I'm ok with changing the default if the old path style doesn't exist - but if it does exist, we should still return that. (I haven't dig into it to see why this is, yet.)

The reason for this seems to lie here: https://github.com/llvm/llvm-project/blob/ccdebbae4d77d3efc236af92c22941de5d437e01/clang/lib/Driver/Driver.cpp#L2213-L2219

Previously, this picked the `TC.getCompilerRTPath()` case, while this now always ends up going with `TC.getRuntimePath()` as it's never empty.

**Comment by wzssyqa** [comment]
For me, I think that it is a good idea to always warn/hint the full/normalized path.
For compatible reason, we can still try to find libraries in old-style or non-full/normalized paths, while should not hint them.

**Comment by aeubanks** [comment]
it seems that the test depends on if certain android runtime libraries are present or not in the resource dir (without per-target runtime directory since that's still an issue on Android). perhaps the tests need `-resource-dir` to make them more hermetic?

anyway, will revert, feel free to reland once the tests are fixed. this is what's in my resource dir if it's helpful for reproducing

```
$ ls lib/clang/19/lib/linux/
aarch64                              libclang_rt.asan_cxx-aarch64-android.a      libclang_rt.builtins-aarch64-android.a  libclang_rt.tsan_cxx-aarch64-android.a          libclang_rt.ubsan_standalone-aarch64-android.so
libclang_rt.asan-aarch64-android.a   libclang_rt.asan-preinit-aarch64-android.a  libclang_rt.profile-aarch64-android.a   libclang_rt.ubsan_minimal-aarch64-android.a     libclang_rt.ubsan_standalone_cxx-aarch64-android.a
libclang_rt.asan-aarch64-android.so  libclang_rt.asan_static-aarch64-android.a   libclang_rt.tsan-aarch64-android.a      libclang_rt.ubsan_standalone-aarch64-android.a
```

**Comment by wzssyqa** [comment]
@aeubanks The problem is that in your configure, the libclang_rt is please in `<builddir>/lib/clang/19/lib/linux/libclang_rt.builtins-arm-android.a`, instead of
`<buildir>/lib/clang/19/lib/arm-unknown-linux-android/libclang_rt.builtins.a`.

**Comment by mstorsjo** [comment]
> @aeubanks The problem is that in your configure, the libclang_rt is placed in `<builddir>/lib/clang/19/lib/linux/libclang_rt.builtins-arm-android.a`, instead of `<buildir>/lib/clang/19/lib/arm-unknown-linux-android/libclang_rt.builtins.a`.

The point is that both locations were supposed to be accepted, as they were before - this PR was not supposed to be a policy change that affects that.

**Comment by wzssyqa** [comment]
> > @aeubanks The problem is that in your configure, the libclang_rt is placed in `<builddir>/lib/clang/19/lib/linux/libclang_rt.builtins-arm-android.a`, instead of `<buildir>/lib/clang/19/lib/arm-unknown-linux-android/libclang_rt.builtins.a`.
> 
> The point is that both locations were supposed to be accepted, as they were before - this PR was not supposed to be a policy change that affects that.

Yes. After the patch, both locations are accepted. This patch doesn't break it.
The current problem is that in some test cases, `-resource-dir` option are missing.

For details:
1. with `--sysroot` option, clang will try to find libclang_rt there. In the failure case, it fails to find.
2. then, clang try to look for libclang_rt from `lib/clang/19/lib/arm-unknown-android/libclang_rt.builtin.a`, and failed.
3. clang try to look for libclang_rt from `lib/clang/19/lib/linux/libclang_rt.builtin-arm-android.a`, and success.
     Thus the file name of libclang_rt is different with the one in test cases.
4. If 3) failed, clang will fallback to  `lib/clang/19/lib/arm-unknown-android/libclang_rt.builtin.a`, then test case success.

So, we can add `-resource-dir` to skip 3 for test case.

**Comment by wzssyqa** [comment]
[xx.patch](https://github.com/llvm/llvm-project/files/14948921/xx.patch)

@aeubanks can you help to test this patch?

**Comment by aeubanks** [comment]
yeah that patch makes those test pass with this PR, lgtm

(you could also test locally by touching the files I mentioned above, e.g. even just `touch lib/clang/19/lib/linux/libclang_rt.builtins-aarch64-android.a` repro'd the test failure on my machine)

**Comment by wzssyqa** [comment]
New PR with my resource-dir patch: https://github.com/llvm/llvm-project/pull/88661

**Comment by antmox** [comment]
Hello @MaskRay @bazuzi,
Looks like one of the commit ([Driver] Ensure ToolChain::LibraryPaths is not empty for non-Darwin) broke the clang-arm64-windows-msvc-2stage bot here:
https://lab.llvm.org/buildbot/#/builders/120/builds/6489
Old compiler-rt lib seems still used "--dependent-lib=clang_rt.builtins-aarch64.lib"

**Comment by wzssyqa** [comment]
See: https://github.com/llvm/llvm-project/pull/87866
Can you have a try to add an extra option
```
-resource-dir=%S/Inputs/resource_dir
```

**Comment by estewart08** [comment]
Is it expected now that `clang --print-runtime-dir` will always have the clang host triple appended even if `LLVM_ENABLE_PER_TARGET_RUNTIME_DIR` is off?

**Comment by MaskRay** [comment]
> Is it expected now that `clang --print-runtime-dir` will always have the clang host triple appended even if `LLVM_ENABLE_PER_TARGET_RUNTIME_DIR` is off? I guess I was expecting to see `lib/linux` instead of `lib/x86_64-unknown-linux-gnu`.

https://reviews.llvm.org/D98868 introduced `--print-runtime-dir`. The question is whether `--print-runtime-dir` should print the legacy `lib/linux` when `LLVM_ENABLE_PER_TARGET_RUNTIME_DIR` is off.
Personally I'd hope that `--print-runtime-dir` does not try to be smart and users should be able to expect that it always prints the new hierarchy. 

With the old hierarchy, the user is expected to know how to derive `libclang_rt.builtins-aarch64.a` from `libclang_rt.builtins.a`. In this case, they can extract the directory name from `clang --print-file-name=libclang_rt.builtins-aarch64.a`.

**Comment by mstorsjo** [comment]
> > Is it expected now that `clang --print-runtime-dir` will always have the clang host triple appended even if `LLVM_ENABLE_PER_TARGET_RUNTIME_DIR` is off? I guess I was expecting to see `lib/linux` instead of `lib/x86_64-unknown-linux-gnu`.
> 
> https://reviews.llvm.org/D98868 introduced `--print-runtime-dir`. The question is whether `--print-runtime-dir` should print the legacy `lib/linux` when `LLVM_ENABLE_PER_TARGET_RUNTIME_DIR` is off. Personally I'd hope that `--print-runtime-dir` does not try to be smart and users should be able to expect that it always prints the new hierarchy.
> 
> With the old hierarchy, the user is expected to know how to derive `libclang_rt.builtins-aarch64.a` from `libclang_rt.builtins.a`. In this case, they can extract the directory name from `clang --print-file-name=libclang_rt.builtins-aarch64.a`.

That change doesn’t seem to explicitly say that this only is intended to be used with the new layout, and it seems like a number of different users have taken up use of this option in this way, with the old layout. So this change does seem to affect a number of  previously seemingly fully legitimate configurations in practice.

**Comment by jhuber6** [comment]
It's definitely not ideal that this prints a non-existent path if the per-target runtime directory configuration is off. Couldn't we just do a trivial filesystem check to make sure it exists before appending it?

**Comment by wzssyqa** [comment]
> It's definitely not ideal that this prints a non-existent path if the per-target runtime directory configuration is off. Couldn't we just do a trivial filesystem check to make sure it exists before appending it?

In fact `nocheck` is what this patch intent to do.
The problem is that if we check the existence, the warning message will be about
`lib/linux/libclang_rt.builtins-x86_64.a` instead `lib/x86_64-unknown-linux-gnu/libclang_rt.builtins.a`.

I think that we should migrate to per-target-dir, and may remove non-per-target-dir support in future.

**Comment by nico** [comment]
This is a behavior change: In distributed build environments, neither lib file exists at compile time. Previously, this would result in the "old" style, now (together with #81037) it results in the "new" style (which we disable everywhere since it causes all kinds of issues – from what I can tell, we're not alone in this).

Is there some way we can tell clang that we always want the old style here, independent of what's on disk?

[ttps://crbug.com/335997052](https://crbug.com/335997052) has details.

**Comment by mstorsjo** [comment]
> This is a behavior change: In distributed build environments, neither lib file exists at compile time. Previously, this would result in the "old" style, now (together with #81037) it results in the "new" style (which we disable everywhere since it causes all kinds of issues – from what I can tell, we're not alone in this).

Hmm, in which cases does this PR change anything of what happens at compile time? The only functional behaviour difference I'm aware of, is that `clang --print-runtime-dir` now always prints the new style path, even if the old style path exists and was expected to be used.

There have been talks about embedding directives for autolinking compiler-rt builtins for msvc mode builds, and switching between old and new path style depending on what files exist on disk (which would be a problem for the kind of distributed build environment you have, admittedly!), but that's not implemented yet. Or is this already the case for embedded directives for asan? And based on your linked issue, apparently also for profiling?

Can you distill out a minimal standalone command that showcases compiling, and shows the embedded directive that gets changed by this PR?

**Comment by nico** [comment]
Here's a minimal repro:

```
% cat empty.c
% foo/clang --driver-mode=cl empty.c --target=x86_64-pc-windows -fprofile-instr-generate -c /Fa && rg DEFAULTLIB empty.asm

23:	.ascii	" /DEFAULTLIB:libcmt.lib"
24:	.ascii	" /DEFAULTLIB:oldnames.lib"
25:	.ascii	" /DEFAULTLIB:clang_rt.profile.lib"

% foo/old-clang --driver-mode=cl empty.c --target=x86_64-pc-windows -fprofile-instr-generate -c /Fa && rg DEFAULTLIB empty.asm
23:	.ascii	" /DEFAULTLIB:libcmt.lib"
24:	.ascii	" /DEFAULTLIB:oldnames.lib"
25:	.ascii	" /DEFAULTLIB:clang_rt.profile-x86_64.lib"
```

`foo` is a directly that contains just these two clang binaries. `clang` is built at clang-llvmorg-19-init-8943-gd8503a38. `old-clang` is built at clang-llvmorg-19-init-8091-gab037c4f. ` git log llvmorg-19-init-8091-gab037c4f..llvmorg-19-init-8795-g39bfdb7f clang/lib/Driver/ToolChain.cpp` shows this as the only change in that range. (I admittedly haven't built clang at this rev and before yet to prove that it's due to this commit. I'll do that now, but it looks pretty plausible.)

**Comment by nico** [comment]
I now did build clang at ccdebbae4d77 and ccdebbae4d77^. ccdebbae4d77 has `/DEFAULTLIB:clang_rt.profile.lib` in its output, ccdebbae4d77^ has /DEFAULTLIB:clang_rt.profile-x86_64.lib`. So definitely due to this change.

It sounds like you're saying that's not intentional?

(It's kind of what #81037 looks like to me – it used to default to old-style, now it defaults to "new"-style. But without this chang here, #81037 doesn't have that effect.)

**Comment by wzssyqa** [comment]
Will the contents of `empty.asm` correct if `lib/<triple>/clang_rt.profile.lib` doesn't exist?
I mean, will `empty.asm` contains `/DEFAULTLIB:clang_rt.profile-x86_64.lib` then?

**Comment by nico** [comment]
>  I would suggest we revert this - and at least collect all the observed side effects and declare them before considering relanding it.

That sounds good to me. Do you have a list of PRs to revert?

> ... then we do still get the old name embedded.

Sure. The motivation on our side is a distributed compile service where the library doesn't exist on the remote end. This patch means we'll have to add knowledge about path layouts at link time to the remote setup at compile time. That's certainly doable, but kind of janky.

(What we'll actually do is use the flag from #89642 to disable all this guessing of libs and just explicitly pass the path to the lib at link time. So this won't actually affect us then, but reverting and relanding in one commit with a list of side effects still sounds like a good thing independent of that.)

**Comment by mstorsjo** [comment]
> > I would suggest we revert this - and at least collect all the observed side effects and declare them before considering relanding it.
> 
> That sounds good to me. Do you have a list of PRs to revert?

Not sure if there are follow-up fixes, sorry, but the discussed PRs are this one, and #81037 (where #89775 says the latter one changed functional behaviour, but it sounds mostly like your issue, i.e. caused by this one).

> > ... then we do still get the old name embedded.
> 
> Sure. The motivation on our side is a distributed compile service where the library doesn't exist on the remote end. This patch means we'll have to add knowledge about path layouts at link time to the remote setup at compile time. That's certainly doable, but kind of janky.

Right, I see. FWIW, with the embedding of directives, which kind of depends on knowing the runtime layout style, I guess this is an issue that needs to be tackled at one point or another, for distributed builds (especially as long as the intent is to change default towards the per-triple directories instead of per-os directories).

> (What we'll actually do is use the flag from #89642 to disable all this guessing of libs and just explicitly pass the path to the lib at link time. So this won't actually affect us then, but reverting and relanding in one commit with a list of side effects still sounds like a good thing independent of that.)

Ah, that probably sounds like a good flag to have in any case, for that kind of distributed setup!

**Comment by wzssyqa** [comment]
> 
> Sure. The motivation on our side is a distributed compile service where the library doesn't exist on the remote end. This patch means we'll have to add knowledge about path layouts at link time to the remote setup at compile time. That's certainly doable, but kind of janky.
> 

I guess `using new-style always` can make things simpler. Since you won't need to know how to convert the target name to tail arch name. For every arch, it uses the same archive file name.

Does your `distributed compile service` is like:
    1. Use upload C/C++ code
    2. Your service compiles them to ASM code.
    3. User downloads the ASM code
    4. User assembles and link
If so, it will always have a trouble for any case, as the archive's filename differs between users local setup.
I think that problem is a chaos during the transition.
In fact, a filename like `clang_rt.profile-x86_64.lib` also contains info about path layout at compile time.
What you really need is an option for user to tell us their local path layout.

**Comment by Meinersbur** [comment]
Using git bisect, I tracked down Flang not working anymore on Windows to this PR:

```
> flang-new hello.f90 -o hello
flang-new version 19.0.0git
Target: x86_64-pc-windows-msvc
Thread model: posix
InstalledDir: C:\Users\meinersbur\build\llvm-project\release\bin
Build config: +assertions
 "C:\\Users\\meinersbur\\build\\llvm-project\\release\\bin\\flang-new" -fc1 -triple x86_64-pc-windows-msvc19.40.33811 -emit-obj -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -target-cpu x86-64 --dependent-lib=clang_rt.builtins-x86_64.lib -D_MT --dependent-lib=libcmt --dependent-lib=Fortran_main.static.lib --dependent-lib=FortranRuntime.static.lib --dependent-lib=FortranDecimal.static.lib -D_MSC_VER=1940 -D_MSC_FULL_VER=194033811 -D_WIN32 -D_M_X64=100 -mframe-pointer=none -o "C:\\Users\\MEINER~1\\AppData\\Local\\Temp\\hello-2ee671.o" -x f95-cpp-input hello.f90
 "C:\\Program Files\\Microsoft Visual Studio\\2022\\Community\\VC\\Tools\\MSVC\\14.40.33807\\bin\\Hostx64\\x64\\link.exe" -out:hello "-libpath:C:\\Users\\meinersbur\\build\\llvm-project\\release\\lib" /WHOLEARCHIVE:Fortran_main.static.lib /subsystem:console "-libpath:C:\\Users\\meinersbur\\build\\llvm-project\\release\\lib\\clang\\19\\lib\\windows" -nologo "C:\\Users\\MEINER~1\\AppData\\Local\\Temp\\hello-2ee671.o"
LINK : fatal error LNK1104: cannot open file 'clang_rt.builtins.lib'
flang-new: error: linker command failed with exit code 1104 (use -v to see invocation)
```

Before this commit, `/DEFAULTLIB:clang_rt.builtins-x86_64.lib` the linking directive, now it is `/DEFAULTLIB:clang_rt.builtins-x86_64.lib`. Turns out, `clang_rt.builtins-x86_64.lib` is actually shipped with the MSVC compiler (`C:\Program Files\Microsoft Visual Studio\2022\Community\VC\Tools\MSVC\<version>\lib\x64`, possibly for Sanitizer support in MSVC), which makes the former work, but not the latter.

With `-DLLVM_ENABLE_PROJECTS=compiler-rt`, the resource-dir `build\llvm-project\release\lib\clang\19\lib\windows` is filled with `clang_rt.builtins-x86_64.lib` et.al., but also changes it back to `/DEFAULTLIB:clang_rt.builtins-x86_64.lib`, and it works again.

**Comment by vitalybuka** [comment]
Also https://lab.llvm.org/buildbot/#/builders/66/builds/1427/steps/13/logs/stdio

```
[20/21] Running compiler_rt regression tests
llvm-lit: /b/sanitizer-x86_64-linux/build/llvm-project/compiler-rt/test/lit.common.cfg.py:60: warning: Path reported by clang does not exist: "/b/sanitizer-x86_64-linux/build/build_debug/lib/clang/19/lib/i386-unknown-linux-gnu". This path was found by running ['/b/sanitizer-x86_64-linux/build/build_debug/./bin/clang', '--target=x86_64-unknown-linux-gnu', '-m32', '-print-runtime-dir'].
llvm-lit: /b/sanitizer-x86_64-linux/build/llvm-project/compiler-rt/test/lit.common.cfg.py:60: warning: Path reported by clang does not exist: "/b/sanitizer-x86_64-linux/build/build_debug/lib/clang/19/lib/i386-unknown-linux-gnu". This path was found by running ['/b/sanitizer-x86_64-linux/build/build_debug/./bin/clang', '--target=x86_64-unknown-linux-gnu', '-m32', '-print-runtime-dir'].
llvm-lit: /b/sanitizer-x86_64-linux/build/llvm-project/compiler-rt/test/lit.common.cfg.py:60: warning: Path reported by clang does not exist: "/b/sanitizer-x86_64-linux/build/build_debug/lib/clang/19/lib/x86_64-unknown-linux-gnu". This path was found by running ['/b/sanitizer-x86_64-linux/build/build_debug/./bin/clang', '--target=x86_64-unknown-linux-gnu', '-m64', '-print-runtime-dir'].
llvm-lit: /b/sanitizer-x86_64-linux/build/llvm-project/compiler-rt/test/lit.common.cfg.py:60: warning: Path reported by clang does not exist: "/b/sanitizer-x86_64-linux/build/build_debug/lib/clang/19/lib/x86_64-unknown-linux-gnu". This path was found by running ['/b/sanitizer-x86_64-linux/build/build_debug/./bin/clang', '--target=x86_64-unknown-linux-gnu', '-m64', '-print-runtime-dir'].
llvm-lit: /b/sanitizer-x86_64-linux/build/llvm-project/compiler-rt/test/lit.common.cfg.py:60: warning: Path reported by clang does not exist: "/b/sanitizer-x86_64-linux/build/build_debug/lib/clang/19/lib/x86_64-unknown-linux-gnu". This path was found by running ['/b/sanitizer-x86_64-linux/build/build_debug/./bin/clang', '--target=x86_64-unknown-linux-gnu', '-m64', '-print-runtime-dir'].

```

**Comment by vitalybuka** [comment]
> Also https://lab.llvm.org/buildbot/#/builders/66/builds/1427/steps/13/logs/stdio
> 
> ```
> [20/21] Running compiler_rt regression tests
> llvm-lit: /b/sanitizer-x86_64-linux/build/llvm-project/compiler-rt/test/lit.common.cfg.py:60: warning: Path reported by clang does not exist: "/b/sanitizer-x86_64-linux/build/build_debug/lib/clang/19/lib/i386-unknown-linux-gnu". This path was found by running ['/b/sanitizer-x86_64-linux/build/build_debug/./bin/clang', '--target=x86_64-unknown-linux-gnu', '-m32', '-print-runtime-dir'].
> llvm-lit: /b/sanitizer-x86_64-linux/build/llvm-project/compiler-rt/test/lit.common.cfg.py:60: warning: Path reported by clang does not exist: "/b/sanitizer-x86_64-linux/build/build_debug/lib/clang/19/lib/i386-unknown-linux-gnu". This path was found by running ['/b/sanitizer-x86_64-linux/build/build_debug/./bin/clang', '--target=x86_64-unknown-linux-gnu', '-m32', '-print-runtime-dir'].
> llvm-lit: /b/sanitizer-x86_64-linux/build/llvm-project/compiler-rt/test/lit.common.cfg.py:60: warning: Path reported by clang does not exist: "/b/sanitizer-x86_64-linux/build/build_debug/lib/clang/19/lib/x86_64-unknown-linux-gnu". This path was found by running ['/b/sanitizer-x86_64-linux/build/build_debug/./bin/clang', '--target=x86_64-unknown-linux-gnu', '-m64', '-print-runtime-dir'].
> llvm-lit: /b/sanitizer-x86_64-linux/build/llvm-project/compiler-rt/test/lit.common.cfg.py:60: warning: Path reported by clang does not exist: "/b/sanitizer-x86_64-linux/build/build_debug/lib/clang/19/lib/x86_64-unknown-linux-gnu". This path was found by running ['/b/sanitizer-x86_64-linux/build/build_debug/./bin/clang', '--target=x86_64-unknown-linux-gnu', '-m64', '-print-runtime-dir'].
> llvm-lit: /b/sanitizer-x86_64-linux/build/llvm-project/compiler-rt/test/lit.common.cfg.py:60: warning: Path reported by clang does not exist: "/b/sanitizer-x86_64-linux/build/build_debug/lib/clang/19/lib/x86_64-unknown-linux-gnu". This path was found by running ['/b/sanitizer-x86_64-linux/build/build_debug/./bin/clang', '--target=x86_64-unknown-linux-gnu', '-m64', '-print-runtime-dir'].
> ```

Looks like it caused by use on the bots of `-DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF`

**Pull request merged**
