### PR TITLE
[mlir][spirv] Drop support for SPV_INTEL_joint_matrix

### PR DESCRIPTION
**Pull request by andfau-amd**
This was a "preview" extension, never formalized, that has now been supplanted by SPV_KHR_cooperative_matrix.

### CODE REVIEW

**Review by kuhar — APPROVED** [review]
Thanks

**Comment by kuhar** [comment]
I added some Intel folks as reviewers. I'm not aware of any uses, but let's give folks a couple of days to speak up before we land this.

**Review by antiagainst — APPROVED** [review]

**Comment by victor-eds** [comment]
I'm fine with this. @chencha3, does this affect the lowering of `XeGPU_DpasOp`?

**Review by victor-eds — APPROVED** [review]

**Review by mshahneo — APPROVED** [review]
Looks good to me.
SPIRV joint matrix has merged with SPIRV cooperative matrix at the Khronos level. We are also moving to cooperative matrix internally. and so we support removal of SPIR-V joint matrix.

**Pull request merged**
