### PR TITLE
[llvm] Introduce XROS platform 

### PR DESCRIPTION
**Pull request by cyndyishida**
Accepts but otherwise ignores visionOS/XROS target triples as Darwin based platform.

https://developer.apple.com/documentation/visionos

### CODE REVIEW

**Review by JDevlieghere — APPROVED** [review]
LGTM. The formatting issues are the result of the surrounding code not being compliant. Personally don't think it's worth the churn but even if it were that's something to be fixed in a separate PR.

**Comment by cyndyishida** [comment]
> LGTM. The formatting issues are the result of the surrounding code not being compliant. Personally don't think it's worth the churn but even if it were that's something to be fixed in a separate PR.

Correct. I feel like the right thing is to add `/* clang-format off */` around these offending code regions but can be handled in separate PR depending on how others feel.

**Comment by ributzka** [comment]
Since this change also adds MC support, I think this commit should also add the MC build version test for visionOS/xrOS. Alternatively, the MC support and test could be added in a separate commit.

**Comment by cyndyishida** [comment]
> Alternatively, the MC support and test could be added in a separate commit.
Makes sense, will move that change out to a follow up patch.

**Comment by agg23** [comment]
These changes seem necessary to build (and otherwise seem like they're required at least for consistency): https://github.com/rust-lang/llvm-project/commit/a6cf499f24b5fbe7f1028518f1a972c0176bd6a3

**Comment by cyndyishida** [comment]
> These changes seem necessary to build (and otherwise seem like they're required at least for consistency): [rust-lang@a6cf499](https://github.com/rust-lang/llvm-project/commit/a6cf499f24b5fbe7f1028518f1a972c0176bd6a3)
> 
> Turns out I misunderstood. This PR is missing many changes that are necessary to build LLVM with xrOS support. I'm not sure what milestone these changes represent, but in any case I don't think these are directly actionable.

Correct. I suspect https://github.com/llvm/llvm-project/pull/78373 covers the rest of the changes necessary, at least under the `llvm` subdirectory.  For what it is worth, it seems the fork/branch being used to cherry-pick this PR is behind llvm's TOT main and requires some cherry-picks for this build cleanly. Does rust-lang build against a more stable release branch of the llvm-project?

**Comment by agg23** [comment]
> it seems the fork/branch being used to cherry-pick this PR is behind llvm's TOT main and requires some cherry-picks for this build cleanly.

That's important to know, thank you. Yes, Rust maintains a fork with some targeted changes and thus is lagging behind `main`.

**Pull request merged**
