### PR TITLE
[mlir][Linalg] Move `linalg.fill` -> `linalg.pack` pattern into `fill` canonicalization patterns.

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
This pattern fits better with the other canonicalization patterns that exist for `linalg.fill`.

### CODE REVIEW

**Review by chelini — APPROVED** [review]
I agree, LGTM.

**Review by qedawkins — APPROVED** [review]
LGTM, thanks!

**Comment by MaheshRavishankar** [comment]
Whats the PR error? I am new to how llvm github is setup.

**Comment by qedawkins** [comment]
Might be a CI flake? I see similar looking failures in other recently submitted PRs, although I am not familiar with the new Github setup either.

**Pull request merged**
