### PR TITLE
[LLVM][Coroutines] Perform HALO on "coro_must_elide" coroutines

### PR DESCRIPTION
**Pull request by yuxuanchen1997**
This patch is the middle end implementation for the coroutine HALO improvement project published on discourse: https://discourse.llvm.org/t/language-extension-for-better-more-deterministic-halo-for-c-coroutines/80044/7

Previously CoroElide depends on inlining, and its analysis does not work very well with code generated by the C++ frontend due the existence of many customization points. There has been issue reported to upstream how ineffective the original CoroElide was in real world applications. 

For C++ users, this set of patches aim to fix this problem by providing library authors and users deterministic HALO behaviour for some well-behaved coroutine `Task` types. The stack begins with a library side attribute on the `Task` class that guarantees no unstructured concurrency when coroutines are awaited directly with `co_await`ed as a prvalue. This attribute on Task types gives us lifetime guarantees and makes C++ FE capable to telling the ME which coroutine calls are elidable. We convey such information from FE through the attribute `coro_must_elide`.

This patch modifies CoroSplit to create a variant of the coroutine ramp function that 1) does not use heap allocated frame, instead take an additional parameter as the pointer to the frame. Such parameter is attributed with `dereferenceble` and `align` to convey size and align requirements for the frame. 2) always stores cleanup instead of destroy address for `coro.destroy()` actions. 

Additionally, we have a new pass that runs right after CoroSplit to find usages of the callee coroutine attributed `coro_must_elide` in presplit coroutine callers, allocates the frame on its "stack", transform those usages to call the `noalloc` ramp function variant. 

(note I put quotes on the word "stack" here, because for presplit coroutine, any alloca will be spilled into the frame when it's being split)

The C++ Frontend attribute implementation that works with this change can be found at https://github.com/llvm/llvm-project/pull/98971

### CODE REVIEW

**Comment by ChuanqiXu9** [comment]
Some quick feedbacks:

- Since this patch do at least 2 things: create a new ramp function in CoroSplit and introduce a new pass. I think it will be better to split these 2 pases.
- I feel better to do this with attribute instead of metadata. If I rememebr correctly, we don't have a pretty good interface to remove metadata. And I feel it is somewhat unneeded to use metadata here. To pass simple information, I think the attribute is enough and more neat.

**Comment by yuxuanchen1997** [comment]
> * I feel better to do this with attribute instead of metadata. If I rememebr correctly, we don't have a pretty good interface to remove metadata. And I feel it is somewhat unneeded to use metadata here. To pass simple information, I think the attribute is enough and more neat.

I also think Attributes are neater if they work. Instructions don't have attributes but CallBase does. I tried to add Attributes on the CallBase but however the `dump()` doesn't show it somehow. It also gave me the impression that Attributes on `CallBase` is specifically for parameters.

**Comment by yuxuanchen1997** [comment]
@ChuanqiXu9, I have changed to use Attributes now.

**Comment by ChuanqiXu9** [comment]
It looks like the diff has some problems (it contains clang's change). And how do you think about the suggestion to split the middle end patch?

**Comment by yuxuanchen1997** [comment]
@ChuanqiXu9

I was trying to find a stack review solution. See https://reviewstack.dev/llvm/llvm-project/pull/98974

You can compare between commits on this UI. What's the stacked PRs approach you were talking about?

**Comment by ChuanqiXu9** [comment]
> @ChuanqiXu9
> 
> I was trying to find a stack review solution. See https://reviewstack.dev/llvm/llvm-project/pull/98974
> 
> You can compare between commits on this UI. What's the stacked PRs approach you were talking about?

For example, you have 2 patches A and B, and B dependent on A. Then you can send the patch A to `llvm-project`'s branch (https://llvm.org/docs/GitHub.html#branches) instead of your repo and open a PR to merge the branch-of-A to main, then you can open another patch for B too and open a PR to merge the branch-of-B to branch-of-A.

**Comment by yuxuanchen1997** [comment]
> how do you think about the suggestion to split the middle end patch?

Can do that sure. I will send out new stacked PRs.

**Comment by yuxuanchen1997** [comment]
Closed in favor of https://github.com/llvm/llvm-project/pull/99283 and https://github.com/llvm/llvm-project/pull/99285

**Pull request closed without merging**
