### PR TITLE
[mlir][openacc] Model acc cache directive as data entry operands on acc.loop

### PR DESCRIPTION
**Pull request by clementval**
The `cache` directive may appear at the top of (inside of) a loop. It specifies array elements or subarrays that should be fetched into the highest level of the cache for the body of the loop.

The `cache` directive is modeled as a data entry operands attached to the acc.loop operation.

### CODE REVIEW

**Review by razvanlupusoru — CHANGES_REQUESTED** [review]
Looks good to me. However, can you please add the new ops to the ACC_DATA_ENTRY_OPS macro in OpenACC.h?

**Comment by clementval** [comment]
> Looks good to me. However, can you please add the new ops to the ACC_DATA_ENTRY_OPS macro in OpenACC.h?

Sure I'll add it.

**Comment by clementval** [comment]
> Looks good to me. However, can you please add the new ops to the ACC_DATA_ENTRY_OPS macro in OpenACC.h?

Done

**Review by razvanlupusoru — APPROVED** [review]
Looks great! Thank you!

**Pull request merged**
