### PR TITLE
Revert "[MLIR] Fuse locations of merged constants (#74670)"

### PR DESCRIPTION
**Pull request by MaskRay**
This reverts commit 87e2e89019ec4405fa47c3b4585be4e67473b590
and its follow-up 0d1490f09f23bf204b714c3c6ba5e0aaf4eeed9a (#75218).

We observed significant OOM/timeout issues due to #74670 to quite a few
services including google-research/swirl-lm. The follow-up 75218 does
not address the issue. Perhaps this is worth more investigation.

### CODE REVIEW

**Review by zyx-billy — APPROVED** [review]
If this is causing significant issues with OOM / timeout, I'm open to reverting for now and finding a more efficient approach (I'm proposing one in https://github.com/llvm/llvm-project/pull/75258).

Do you have any data that suggests why the previous fix (https://github.com/llvm/llvm-project/pull/75218) didn't solve the problem? Was it generating super long fused locations? Or was it just due to all the temporary fused locations that were created since we "append" locations incrementally?

**Comment by MaskRay** [comment]
> If this is causing significant issues with OOM / timeout, I'm open to reverting for now and finding a more efficient approach (I'm proposing one in #75258).
> 
> Do you have any data that suggests why the previous fix (#75218) didn't solve the problem? Was it generating super long fused locations? Or was it just due to all the temporary fused locations that were created since we "append" locations incrementally?

Thank you for being open for reverts! I don't know the technical aspect of the issue... but I'll find right folks help investigate this issue. Stay tuned!

**Review by joker-eph — APPROVED** [review]

**Comment by MaskRay** [comment]
Thanks for the approval. Sorry that I manually pushed it as 2a9d8caf29ca2b2cf4758db31c64fd20cb5eb3bf

**Comment by yfcyfcyfc** [comment]
Note the breakages are from several tests from [SWIRL-LM](https://github.com/google-research/swirl-lm). These tests are not currently only kept internally -- but we can expose some if that helps with the debugging.

**Comment by joker-eph** [comment]
We'd need someone downstream to actually work on narrowing down the issue without upstream having to build TensorFlow and learn how to debug within TensorFlow. 
(MLIR has support for "crash reproducer" which could be levered to narrow this down to a single-pass reproducer)

**Comment by jpienaar** [comment]
@yfcyfcyfc could you ping me internally? I could try and help to narrow down.

**Comment by joker-eph** [comment]
FYI: we are going with a different approach, there is no plan to re-land this feature. So no urgency to help debugging this just now.

**Pull request closed without merging**
