### PR TITLE
Revert "Reapply "[clang] Extend diagnose_if to accept more detailed warning information (#70976)" (#108453)"

### PR DESCRIPTION
**Pull request by fmayer**
This reverts commit e7f782e7481cea23ef452a75607d3d61f5bd0d22.

This had UBSan failures:

[----------] 1 test from ConfigCompileTests
[ RUN      ] ConfigCompileTests.DiagnosticSuppression
Config fragment: compiling <unknown>:0 -> 0x00007B8366E2F7D8 (trusted=false)
/usr/local/google/home/fmayer/large/llvm-project/llvm/include/llvm/ADT/IntrusiveRefCntPtr.h:203:33: runtime error: reference binding to null pointer of type 'clang::DiagnosticIDs'

UndefinedBehaviorSanitizer: undefined-behavior /usr/local/google/home/fmayer/large/llvm-project/llvm/include/llvm/ADT/IntrusiveRefCntPtr.h:203:33

### CODE REVIEW

**Comment by philnik777** [comment]
@fmayer Could you maybe provide some information? What test is this? How do I run it? I haven't received a single mail from a buildbot regarding this commit.

**Comment by fmayer** [comment]
> @fmayer Could you maybe provide some information? What test is this? How do I run it? I haven't received a single mail from a buildbot regarding this commit.

It's this buildbot: https://lab.llvm.org/buildbot/#/builders/169/builds/3175/steps/2/logs/stdio

I took the cmake command lines from there, and ran `check-clangd` before and after your change.

**Review by thurstond — APPROVED** [review]

**Comment by fmayer** [comment]
I submitted this to get the buildbot back to green, happy to help if you have more questions on how to reproduce!

**Comment by fmayer** [comment]
The error is gone in the first buildbot build with this revert: https://lab.llvm.org/buildbot/#/builders/169/builds/3191/steps/9/logs/stdio

**Pull request closed without merging**
