### PR TITLE
[NFC] Add missing bitcode documentation to BitCodeFormat.rst

### PR DESCRIPTION
**Pull request by cjappl**
Seems like there were a few that missed this documentation. I filled in since the last time it was updated.

### CODE REVIEW

**Comment by cjappl** [comment]
Possibly cc @SLTozer for review, as it seems like you may have done the last batch update of this?

It would be great if there was some unit tests for this in the future, I think this will be a recurring problem. 


There are also some (seemingly crufty) files that define emacs/vim/vscode for llvm IR that are very much out of date, I didn't even bother digging into those.  All of these attributes I added to the docs here are missing in these files, and many more attributes beyond that.

```
llvm/utils/vscode/llvm/syntaxes/ll.tmLanguage.yaml
llvm/utils/emacs/llvm-mode.el
llvm/utils/llvm.grm
llvm/utils/vim/syntax/llvm.vim
```

**Comment by nikic** [comment]
My 2c is that we should probably remove this listing and point people to the source definition. If someone wants to write a 3rd-party bitcode parser (which is the only reason they may need this information), they should be perfectly capable of extracting these numbers from LLVMBitCodes.h...

**Comment by SLTozer** [comment]
> My 2c is that we should probably remove this listing and point people to the source definition. If someone wants to write a 3rd-party bitcode parser (which is the only reason they may need this information), they should be perfectly capable of extracting these numbers from LLVMBitCodes.h...

+1, I noticed when adding the new bitcode value that some of the existing bitcode attributes weren't included in the list as well. It seems like duplication that will inevitably trip up someone when we fail to update it. If there was a useful way to auto-generate docs from the enum that would be useful too, but pointing to the source SGTM. That said, this patch LGTM since it's trivially fixing an existing problem.

**Review by SLTozer — APPROVED** [review]

**Comment by cjappl** [comment]
Yeah. This seems ripe for a problem.

Let me close this review and I'll put up a review just deleting the list, better to do it right while it's on my mind than do half measures.

I'll ping you two on that review shortly.

**Comment by cjappl** [comment]
Closing in favor of #102618

**Pull request closed without merging**
