### PR TITLE
[X86AsmParser] IntelExpression: End of Statement should check for valid end state

### LINKED ISSUE #94446: "SmallVector unable to grow" reached via parseIntelOperand with rejectable asm
Source IR:
```llvmir
source_filename = "example.c93a12df09c9e7ea-cgu.0"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

module asm ".intel_syntax"
module asm "i-"
module asm ".att_syntax"

!llvm.module.flags = !{!0, !1}
!llvm.ident = !{!2}

!0 = !{i32 8, !"PIC Level", i32 2}
!1 = !{i32 2, !"RtLibUseGOT", i32 1}
!2 = !{!"rustc version 1.80.0-nightly (a330e4959 2024-06-04)"}
```

<details><summary>Stack trace</summary>

```
LLVM ERROR: SmallVector unable to grow. Requested capacity (4294967296) is larger than maximum value for size type (4294967295)
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /opt/compiler-explorer/clang-trunk/bin/llc -o /app/output.s -x86-asm-syntax=intel <source>
 #0 0x00000000036ffd18 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/opt/compiler-explorer/clang-trunk/bin/llc+0x36ffd18)
 #1 0x00000000036fd68c SignalHandler(int) Signals.cpp:0:0
 #2 0x000073a021242520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #3 0x000073a0212969fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #4 0x000073a021242476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #5 0x000073a0212287f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #6 0x000000000072f886 llvm::UniqueStringSaver::save(llvm::StringRef) (.cold) StringSaver.cpp:0:0
 #7 0x0000000003677a16 report_size_overflow(unsigned long, unsigned long) (.constprop.0) SmallVector.cpp:0:0
 #8 0x0000000003677b69 llvm::SmallVectorBase<unsigned int>::grow_pod(void*, unsigned long, unsigned long) (/opt/compiler-explorer/clang-trunk/bin/llc+0x3677b69)
 #9 0x00000000009c5484 (anonymous namespace)::X86AsmParser::InfixCalculator::execute() X86AsmParser.cpp:0:0
#10 0x00000000009d9bfa (anonymous namespace)::X86AsmParser::parseIntelOperand(llvm::SmallVectorImpl<std::unique_ptr<llvm::MCParsedAsmOperand, std::default_delete<llvm::MCParsedAsmOperand>>>&, llvm::StringRef) X86AsmParser.cpp:0:0
#11 0x00000000009de94c (anonymous namespace)::X86AsmParser::ParseInstruction(llvm::ParseInstructionInfo&, llvm::StringRef, llvm::SMLoc, llvm::SmallVectorImpl<std::unique_ptr<llvm::MCParsedAsmOperand, std::default_delete<llvm::MCParsedAsmOperand>>>&) X86AsmParser.cpp:0:0
#12 0x0000000004535842 (anonymous namespace)::AsmParser::parseAndMatchAndEmitTargetInstruction((anonymous namespace)::ParseStatementInfo&, llvm::StringRef, llvm::AsmToken, llvm::SMLoc) AsmParser.cpp:0:0
#13 0x000000000454d01b (anonymous namespace)::AsmParser::parseStatement((anonymous namespace)::ParseStatementInfo&, llvm::MCAsmParserSemaCallback*) AsmParser.cpp:0:0
#14 0x0000000004542322 (anonymous namespace)::AsmParser::Run(bool, bool) AsmParser.cpp:0:0
#15 0x0000000002599239 llvm::AsmPrinter::emitInlineAsm(llvm::StringRef, llvm::MCSubtargetInfo const&, llvm::MCTargetOptions const&, llvm::MDNode const*, llvm::InlineAsm::AsmDialect) const (/opt/compiler-explorer/clang-trunk/bin/llc+0x2599239)
#16 0x000000000258f8fd llvm::AsmPrinter::doInitialization(llvm::Module&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x258f8fd)
#17 0x0000000002d37fb8 llvm::FPPassManager::doInitialization(llvm::Module&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x2d37fb8)
#18 0x0000000002d4456e llvm::legacy::PassManagerImpl::run(llvm::Module&) (/opt/compiler-explorer/clang-trunk/bin/llc+0x2d4456e)
#19 0x00000000008483f4 compileModule(char**, llvm::LLVMContext&) llc.cpp:0:0
#20 0x0000000000741b86 main (/opt/compiler-explorer/clang-trunk/bin/llc+0x741b86)
#21 0x000073a021229d90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#22 0x000073a021229e40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#23 0x000000000084002e _start (/opt/compiler-explorer/clang-trunk/bin/llc+0x84002e)
Program terminated with signal: SIGSEGV
Compiler returned: 139
```

</details>

Technically crashing is a successful rejection of this clearly ill-formed asm. However, as assembly strings are often dumped directly into LLVM from a source language, with very little modification done, it would be nice if the assembly parser was more guarded against obviously bad inputs.

### PR DESCRIPTION
**Pull request by v01dXYZ**
The following commit bfb7099eeb9b6f62510b1db0cb93a8c3cfa68236 added a special case for End of Statement that doesn't check if the state machine is rightfully in a state where ending is valid.

This PR suggest to revert this change to make `EndOfStatement` processed as any other tokens that are not consumable by the state machine.

Fixes https://github.com/llvm/llvm-project/issues/94446

### CODE REVIEW

**Comment by v01dXYZ** [comment]
FYI, linux CI fails because of a (flaky ?) lldb test with a timeout.

**Comment by v01dXYZ** [comment]
I repush the same commit to relaunch the CI. If you know a way to relaunch a failed CI pipeline, I want to know it too.

**Comment by v01dXYZ** [comment]
Ping

**Comment by KanRobert** [comment]
AsmParser is shared by assembler and fronr-end. Could you add a `.s` test to show what you fixed?

**Comment by v01dXYZ** [comment]
Ping.

I added the case from the issue.

**Review by KanRobert — APPROVED** [review]
Maybe we can refactor `X86AsmParser::ParseIntelExpression` to avoid so much customized code. But it looks good as a quick fix.

**Comment by v01dXYZ** [comment]
I wonder if a customised `AsmParser` could potentially do it. Is it possible and worth it according to you ? There is certainly a reason why this machinery was not used at the time.

**Comment by v01dXYZ** [comment]
FYI I don't have merge rights. if you consider the patch good enough, could you merge it on my behalf ?

I'll take a look at trying to replace some parts of the custom Expression Parser by the generic AsmParser at the beginning of next month as it is an interesting task about a very specific part of LLVM (thus perfect for a beginner like me). The code I'll write won't matter as much as the documentation about the suggestions.

**Comment by KanRobert** [comment]
> FYI I don't have merge rights. if you consider the patch good enough, could you merge it on my behalf ?
> 

Sure.

**Pull request merged**
