### PR TITLE
[MLIR][Python] add ctype python binding support for bf16

### PR DESCRIPTION
**Pull request by xurui1995**
Since bf16 is supported by mlir, similar to complex128/complex64/float16, we need an implementation of bf16 ctype in Python binding. Furthermore, to resolve the absence of bf16 support in NumPy, a third-party package [ml_dtypes ](https://github.com/jax-ml/ml_dtypes) is introduced to add bf16 extension, and the same approach was used in `torch-mlir` project.

See motivation and discussion in: https://discourse.llvm.org/t/how-to-run-executionengine-with-bf16-dtype-in-mlir-python-bindings/79025

### CODE REVIEW

**Comment by stellaraccident** [comment]
Thanks for the PR. I don't think we want to globally add a dep like this as it will impact everyone.

The traditional was to do this would be to do the import in a try...except, setting a flag on failure. Then skip the integration of it is not available.

**Comment by ftynse** [comment]
Is this something that can be added to https://github.com/llvm/llvm-project/blob/main/mlir/python/requirements.txt ?

**Review by stellaraccident — COMMENTED** [review]
I think adding it to the project requirements with a note about it being optional is fine, as then the upstream CI will test it. But the code path itself should be optional. This API gets integrated in a bunch of places, and it is those leaves which specify concrete deps for their case. The local requirements file is just for upstream.

**Comment by xurui1995** [comment]
> I think adding it to the project requirements with a note about it being optional is fine, as then the upstream CI will test it. But the code path itself should be optional. This API gets integrated in a bunch of places, and it is those leaves which specify concrete deps for their case. The local requirements file is just for upstream.

Hi, @stellaraccident thanks for your review.
I'd like to add `ml_dtypes` in `requirements.txt` with a note and keep `try...except` in `np_to_memref.py`, but I have a question about the new bf16 test case in`mlir/test/python/execution_engine.py`, after adding `ml_dtypes` in `requirements.txt`, should we assume that ml_dtypes is installed by default, or should this test case also be considered as part of the code path and need a `try...except`?

**Comment by stellaraccident** [comment]
Try adding the test case without the try...except. In theory, if people/bots are developing on this project, they should have the requirements installed. I can't guarantee that all bots are actually doing that though -- so we will have to see.

**Comment by xurui1995** [comment]
> Try adding the test case without the try...except. In theory, if people/bots are developing on this project, they should have the requirements installed. I can't guarantee that all bots are actually doing that though -- so we will have to see.

@stellaraccident I just pushed a commit for doing that, and then it could not pass the CI. We do have the CI code in https://github.com/llvm/llvm-project/blob/d34be649af1aa849c21a5a0570617c3a89d5f0b8/.ci/monolithic-linux.sh#L40C1-L40C66, is there a way to debug the buildkite for this issue?

**Comment by xurui1995** [comment]
after fixing and simplifying the test case, the CI can pass now.

**Comment by xurui1995** [comment]
@stellaraccident hi could you please help merge this?

**Comment by stellaraccident** [comment]
Yes. On holiday for the weekend so will do it when back.

**Comment by xurui1995** [comment]
> Yes. On holiday for the weekend so will do it when back.

Thanks a lot. Have a good holiday!

**Review by stellaraccident — APPROVED** [review]

**Comment by joker-eph** [comment]
Sorry, I had to revert because this didn't pass in CI: https://lab.llvm.org/buildbot/#/builders/61/builds/58620

**Comment by xurui1995** [comment]
It seems that the build bot did not successfully install the lib after updating the requirements.txt

**Comment by ftynse** [comment]
I don't think buildbots install `requirements.txt`, somebody will have to go and install stuff manually...

**Comment by xurui1995** [comment]
> I don't think buildbots install `requirements.txt`, somebody will have to go and install stuff manually...

@joker-eph hi, Could you please help me with this, or could you direct me to someone who can?

**Comment by joker-eph** [comment]
> I don't think buildbots install requirements.txt, somebody will have to go and install stuff manually...

Right, actually you had a review to add this, but it never landed unfortunately :(

> @joker-eph hi, Could you please help me with this, or could you direct me to someone who can?

I should be able to do this, I haven't done so in a while so I just need to find the instructions again :)

**Comment by xurui1995** [comment]
> > I don't think buildbots install requirements.txt, somebody will have to go and install stuff manually...
> 
> Right, actually you had a review to add this, but it never landed unfortunately :(
> 
> > @joker-eph hi, Could you please help me with this, or could you direct me to someone who can?
> 
> I should be able to do this, I haven't done so in a while so I just need to find the instructions again :)


@joker-eph that's great, thanks a lot, please let me know if you get the `ml_dtypes` installed on build-bots, and I will create a new PR.

**Comment by xurui1995** [comment]
> > I don't think buildbots install requirements.txt, somebody will have to go and install stuff manually...
> 
> Right, actually you had a review to add this, but it never landed unfortunately :(
> 
> > @joker-eph hi, Could you please help me with this, or could you direct me to someone who can?
> 
> I should be able to do this, I haven't done so in a while so I just need to find the instructions again :)

@joker-eph, hi,  sorry to bother you, just want to know if we have found the instructions for the build-bots？

**Pull request merged**
