### PR TITLE
[NVPTX] Support inline asm with 128-bit operand in NVPTX backend

### PR DESCRIPTION
**Pull request by Chengjunp**
This change supports the 128-bit operands for inline ptx asm, both input and output.\
\
The major changes are:

- Tablegen:\
      Define Int128Regs in NVPTXRegisterInfo.td. But this register does not set as general register type in NVPTX backend so that this change will not influence the codegen without inline asm.\
      Define three NVPTX intrinsics, IMOV128rr, V2I64toI128 and I128toV2I64. The first one moves a register, the second one moves two 64-bit registers into one 128-bit register, and the third one just does the opposite.
- NVPTXISelLowering & NVPTXISelDAGToDAG:\
      Custom lowering CopyToReg and CopyFromReg with 128-bit operands. CopyToReg deals with the inputs of the inline asm and the CopyFromReg deals with the outputs.\
      CopyToReg is custom lowered into a V2I64toI128, which takes in the expanded values(Lo and Hi) of the input, and moves into a 128-bit reg.\
      CopyFromReg is custom lowered by adding a I128toV2I64, which breaks down the 128-bit outputs of inline asm into the expanded values.

### CODE REVIEW

**Review by jlebar — CHANGES_REQUESTED** [review]
This needs to be documented in the langref in this section, right?  https://llvm.org/docs/LangRef.html#supported-constraint-code-list

**Review by jlebar — COMMENTED** [review]
LGTM other than the previous comment.

**Comment by Chengjunp** [comment]
> This needs to be documented in the langref in this section, right? https://llvm.org/docs/LangRef.html#supported-constraint-code-list
Oh, you are right. Thank you for pointing this out. Which file should I modify? Is it `llvm/docs/LangRef.rst`? Thanks!

**Comment by jlebar** [comment]
> Which file should I modify?

Use `git grep` to find where the text from that section of the langref lives?

**Review by jlebar — APPROVED** [review]

**Pull request merged**
