### PR TITLE
[RemoveDIs][DebugInfo] Correctly visit DPValues in StackInfoBuilder::visit

### PR DESCRIPTION
**Pull request by SLTozer**
In `StackInfoBuilder::visit(Instruction &Inst)`, operations are performed on memory-related instructions, including debug intrinsics that refer to "interesting" allocas. There is a block that also visits DPValues attached to the instruction, but this block is near the end of the function; this has two problems:
1. The DPValues attached to an instruction precede that instruction, so they should always be processed before the instruction itself.
2. More importantly, some of the paths for visiting other instructions contain early returns, which will result in the DPValues not being visited at all.

This patch simply moves the DPValue-visiting block to the top of the function, which should resolve both of these problems.

### CODE REVIEW

**Comment by jmorse** [comment]
LGTM, but could we get a regression test too to prevent this from happening in the future? Should be achievable either by inserting a lifetime intrinsic into an existing test, or duplicating an existing function.

**Comment by fmayer** [comment]
LGTM, also would like a test.

> More importantly, some of the paths for visiting other instructions contain early returns, which will result in the DPValues not being visited at all.

Okay for now, but we should restructure the function to not make this happen by design, not by ordering. I can do that when I get some time.

**Comment by SLTozer** [comment]
I've modified an existing test to trigger for this, with a comment to explain the purpose of the test - more tests could potentially be covered here, but none as conveniently as the test that I've added, and I would hazard that more testing is unnecessary for this error since there are also other tests (that I can't run locally right now) that will also fail if RemoveDIs is enabled by default.

**Review by jmorse — APPROVED** [review]
LGTM; this is probably the start of a theme of "now passes can more easily forget about debug-info", which is the natural result of making it less intrusive. Testing for all of these things is the only surefire solution.

**Pull request merged**
