### PR TITLE
[flang][OpenMP] Avoid early returns, NFC

### PR DESCRIPTION
**Pull request by kparzysz**
Frontend code is generally nested.
Follow-up to https://github.com/llvm/llvm-project/pull/116658.

### CODE REVIEW

**Review by kiranchandramohan — APPROVED** [review]
LG. Thanks.

**Comment by sscalpone** [comment]
I'm having trouble building with this change.   Same as llvm-ci above.   GCC 9.3.

```
In file included from /local/home/sscalpone/lorado/src/llvm-project/flang/lib/Lower/OpenMP/ClauseProcessor.cpp:13:
In file included from /local/home/sscalpone/lorado/src/llvm-project/flang/lib/Lower/OpenMP/ClauseProcessor.h:15:
/local/home/sscalpone/lorado/src/llvm-project/flang/lib/Lower/OpenMP/Clauses.h:169:25: error: template parameter redefines default argument
  169 |     typename ResultTy = std::invoke_result_t<FuncTy, typename ArgTy::Value>>
      |                         ^
/local/home/sscalpone/lorado/src/llvm-project/flang/lib/Lower/OpenMP/Clauses.h:159:25: note: previous default template argument defined here
  159 |     typename ResultTy = std::invoke_result_t<FuncTy, typename ArgTy::Value>>
      |                         ^
/local/home/sscalpone/lorado/src/llvm-project/flang/lib/Lower/OpenMP/Clauses.h:170:25: error: redefinition of 'maybeApplyToV'
  170 | std::optional<ResultTy> maybeApplyToV(FuncTy &&func, const ArgTy *arg) {
      |                         ^
/local/home/sscalpone/lorado/src/llvm-project/flang/lib/Lower/OpenMP/Clauses.h:160:25: note: previous definition is here
  160 | std::optional<ResultTy> maybeApplyToV(FuncTy &&func, const ArgTy *arg) {
      |                         ^
2 errors generated.
```

**Comment by kazutakahirata** [comment]
FWIW, I'm getting the same error messages from clang-16.0.6.

**Comment by kazutakahirata** [comment]
I've revered the patch.

**Comment by kparzysz** [comment]
There seemed to be a merge/rebase error, where a duplicate definition of a template function was added instead of replacing the previous one.

Sorry, I didn't notice it.

**Pull request merged**
