### PR TITLE
[AMDGPU] Fix interaction between WQM and llvm.amdgcn.init.exec

### PR DESCRIPTION
**Pull request by jayfoad**
Whole quad mode requires inserting a copy of the initial EXEC mask. In a
function that also uses llvm.amdgcn.init.exec, insert the COPY after
initializing EXEC.

### CODE REVIEW

**Comment by jayfoad** [comment]
Please see individual commits. If the overall approach seems good, I plan to split them into separate PRs.

**Comment by piotrAMD** [comment]
The approach looks good to me. Seeing the failing case, it makes sense that SI_INIT_EXEC (whose exec value can be arbitrary) is not expanded until si-wqm.

**Comment by jayfoad** [comment]
Rebased on #94452. Please take a look!

**Review by piotrAMD — APPROVED** [review]
LGTM

**Pull request merged**
