### PR TITLE
[bazel] update .bazelversion to 8.0.0

### PR DESCRIPTION
**Pull request by nickdesaulniers**
Fixes:

    ERROR: The project you're trying to build requires Bazel 7.3.0 (specified
    in llvm-project/utils/bazel/.bazelversion), but it wasn't found in
    /usr/bin.

    You can install the required Bazel version via apt:
      sudo apt update && sudo apt install bazel-7.3.0

    If this doesn't work, check Bazel's installation instructions for help:
      https://bazel.build/install/ubuntu

Link: https://blog.bazel.build/2024/12/09/bazel-8-release.html

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
Hmm...even with this change, I'm observing:

```
$ cd llvm-project/utils/bazel
$ bazel query @llvm-project//libc/... | xargs bazel test --config=generic_clang --test_output=errors --test_tag_filters=-nobuildkite --build_tag_filters=-nobuildkite --@llvm-project//libc:mpfr=system
ERROR: Error computing the main repository mapping: error loading package 'external': Both --enable_bzlmod and --enable_workspace are disabled, but one of them must be enabled to fetch external dependencies.
ERROR: Error computing the main repository mapping: error loading package 'external': Both --enable_bzlmod and --enable_workspace are disabled, but one of them must be enabled to fetch external dependencies.
```

**Comment by keith** [comment]
yea for this we need to add `--enable_workspace` to the `.bazelrc` until we support bzlmod

**Comment by keith** [comment]
yea looks like we have to add that to the WORKSPACE now

**Comment by nickdesaulniers** [comment]
```diff
diff --git a/utils/bazel/WORKSPACE b/utils/bazel/WORKSPACE
index 66ba1ac1b17e..a3b8be7814d4 100644
--- a/utils/bazel/WORKSPACE
+++ b/utils/bazel/WORKSPACE
@@ -4,6 +4,7 @@
 
 load("@bazel_tools//tools/build_defs/repo:http.bzl", "http_archive")
 load("@bazel_tools//tools/build_defs/repo:utils.bzl", "maybe")
+load("@rules_cc//cc:defs.bzl", "http_archive")
 
 SKYLIB_VERSION = "1.3.0"
 

```
didn't seem to work

**Comment by keith** [comment]
you have to pull in that repo as shown here https://github.com/bazelbuild/rules_cc/releases/tag/0.0.17

**Comment by nickdesaulniers** [comment]
```
WARNING: WORKSPACE support will be removed in Bazel 9 (late 2025), please migrate to Bzlmod, see https://bazel.build/external/migration.
WARNING: Couldn't auto load rules or symbols, because no dependency on module/repository 'rules_android' found. This will result in a failure if there's a reference to those rules or symbols.
ERROR: /usr/local/google/home/ndesaulniers/.cache/bazel/_bazel_ndesaulniers/02cf1b716d72de9bb7498bab3b083b83/external/rules_python/python/private/reexports.bzl:37:17: name 'PyInfo' is not defined (did you mean 'CcInfo'?)
ERROR: /usr/local/google/home/ndesaulniers/.cache/bazel/_bazel_ndesaulniers/02cf1b716d72de9bb7498bab3b083b83/external/rules_python/python/private/reexports.bzl:40:24: name 'PyRuntimeInfo' is not defined
ERROR: error loading package under directory 'libc': error loading package '@@llvm-project//libc': Internal error while loading Starlark builtins: Failed to autoload external symbols: at /usr/local/google/home/ndesaulniers/.cache/bazel/_bazel_ndesaulniers/02cf1b716d72de9bb7498bab3b083b83/external/rules_python/python/py_info.bzl:18:6: compilation of module 'python/private/reexports.bzl' failed Most likely you need to upgrade the version of rules repository in the WORKSPACE file.
```
That first warning seems fine, since we have https://github.com/llvm/llvm-project/issues/55924.  Not sure yet about the rest.

**Comment by keith** [comment]
i think we should try updating rules_python to fix

**Comment by nickdesaulniers** [comment]
https://github.com/bazelbuild/rules_python/releases/tag/1.0.0 yep that does it!

**Review by keith — APPROVED** [review]

**Comment by keith** [comment]
we should probably try to fix bazel CI before landing so we can differentiate issues

**Comment by nickdesaulniers** [comment]
> we should probably try to fix bazel CI before landing so we can differentiate issues

Working on that, too. :wink:

**Comment by nickdesaulniers** [comment]
> we should probably try to fix bazel CI before landing so we can differentiate issues

Where is this bazel CI?

**Comment by nickdesaulniers** [comment]
build is still red, now due to 9a9c1d4 and 9735873009ca86b03c3283d06edd1b3a190d4af9. Am I also on the hook to fix those? :^)

**Comment by rupprecht** [comment]
> build is still red, now due to #114333 and [9735873](https://github.com/llvm/llvm-project/commit/9735873009ca86b03c3283d06edd1b3a190d4af9). Am I also on the hook to fix those? :^)

I'm looking at the MLIR one now, will get the LLDB one next.

**Comment by keith** [comment]
I'm prepping a fix for the LLDB one

**Comment by keith** [comment]
https://github.com/llvm/llvm-project/pull/119456

**Comment by nickdesaulniers** [comment]
Once https://github.com/llvm/llvm-project/pull/119457 is green, I'll merge this?

**Comment by nickdesaulniers** [comment]
looks like there's some build failures now: https://buildkite.com/llvm-project/upstream-bazel/builds/119358#0193b266-65c9-4ee4-8d53-5fde26020ff7

**Comment by nickdesaulniers** [comment]
> warning: input 'external/llvm-project/llvm/utils/lit/tests/shtest-run-at-line.py' contained no tests
> error: did not discover any tests for provided path(s)

I think is the relevant error?

**Comment by nickdesaulniers** [comment]
cc @GMNGeoffrey

**Comment by nickdesaulniers** [comment]
```
lit.py: /usr/local/google/home/ndesaulniers/.cache/bazel/_bazel_ndesaulniers/02cf1b716d72de9bb7498bab3b083b83/sandbox/linux-sandbox/6372/execroot/__main__/bazel-out/k8-fastbuild/bin/external/llvm-project/mlir/test/Dialect/SPIRV/Linking/ModuleCombiner/basic.mlir.test.runfiles/llvm-project/llvm/utils/lit/lit/discovery.py:137: warning: unable to find test suite for 'external/llvm-project/mlir/test/Dialect/SPIRV/Linking/ModuleCombiner/basic.mlir'
```
so I think anything running `lit` is having an issue. Perhaps something in llvm/utils/lit/lit/discovery.py needs to be fixed?

**Comment by nickdesaulniers** [comment]
I suspect that "external" is no longer being added to a path somewhere...

**Comment by keith** [comment]
I bisected to https://github.com/bazelbuild/bazel/commit/52105e30199a791ba2a2e7249d5e8515165fbdfd, it's a known issue that we rely on this, we just need to flip it back for now: https://github.com/llvm/llvm-project/pull/119462

**Pull request merged**
