### PR TITLE
[M68k] Add support for bitwise NOT instruction

### PR DESCRIPTION
**Pull request by n8pjl**
Currently the bitwise NOT instruction is not recognized. Add support for
using NOT on data registers. This is a partial implementation that puts
NOT at the same level of support as NEG currently enjoys.

Using not rather than eori cuts the length of the encoded instruction
in half or in thirds, leading to a reduction of 4-10 cycles per
instruction, on the original 68000.

This change includes tests for both bitwise and arithmetic negation.

### CODE REVIEW

**Comment by mshockwave** [comment]
Thank you for the patch. Overall looks pretty good, you did a great job on your first LLVM PR!
Could you also add MC (a.k.a assembler & disassembler) tests as well? You can take a look at other MC tests under `llvm/test/MC/M68k` and `llvm/test/MC/Disassembler/M68k`.

**Comment by n8pjl** [comment]
Thank you, and yes, I'll write a few tests for MC. I didn't know that those existed.
I did make sure that inline assembly works, but only for data register direct (it's the same with neg[x]).

Does LLVM have a preference over if the MC tests go into a second commit, or if I revise the first commit and force push?

**Comment by mshockwave** [comment]
> Does LLVM have a preference over if the MC tests go into a second commit, or if I revise the first commit and force push?

The current policy states that during code review, all changes/fixes to the PR should be put in separate commits (unless there is a substantial change on the main branch that will break the PR and you have to rebase + forced push) so the reviewer can see a clear history of changes. But once the code reviewer is done, you have to squash all the commits before merge. Actually, I think we make "Squash and merge" button the only clickable one on the web UI.

**Comment by n8pjl** [comment]
Good to know, I like that policy.

I'm used to email-based patch management, so using PRs takes some getting used to.

**Review by mshockwave — APPROVED** [review]
LGTM. Please let me know if you're not able to merge the PR (I'm not really sure how they setup permission for new contributors after we migrate to GitHub PR). If you need help to merge, please make sure the email you want to use in the commit is in your account's public email list, otherwise GitHub will assign an ugly "XXX-noreply@github.com" to the commit.

**Comment by n8pjl** [comment]
I'm not allowed to merge the PR so it would be great if you could do that for me.

**Pull request merged**
