### PR TITLE
[AMDGPU] New GFX11+ aliases v_dot4_i32_i8 and v_dot8_i32_i4

### PR DESCRIPTION
**Pull request by jayfoad**
Previously we decided not to support these aliases because in other
generations they are real instructions with different behavior. Now I am
inclined to support them anyway for compatibility with SP3.

### CODE REVIEW

**Comment by jayfoad** [comment]
@Sisyph @mbrkusanin any thoughts about this? My immediate motivation is to make it simpler to do automated testing against SP3.

**Review by rampitec — APPROVED** [review]
That's always a bad idea to repurpose instructions' names, but it is already done. LGTM for the purpose of SP3 compatibility.

**Review by Sisyph — APPROVED** [review]
LGTM. I'm having a hard time even picturing a scenario where having these aliases would confuse someone. Emitting textual assembly on an old target and reassemble it on gfx11? Porting inline asm?

**Comment by jayfoad** [comment]
> wouldn't it make sense to set `neg_lo:[1,1,0]` by default for these opcodes? Then they would behave like gfx9/10 opcodes with the same names.

Maybe, if the goal was to provide backwards compatibility of handwritten assembly code. But that's really not a goal of the LLVM assembler. The _only_ reason for implementing these aliases is for compatibility with the proprietary assembler.

**Pull request merged**
