### PR TITLE
[libc++][hardening] Use `__builtin_verbose_trap` if it's available.

### PR DESCRIPTION
**Pull request by var-const**
Keep falling back to `__builtin_trap` on older versions of Clang.

### CODE REVIEW

**Comment by var-const** [comment]
Depends on https://github.com/llvm/llvm-project/pull/79230.

**Review by ldionne — APPROVED** [review]
LGTM once we have a Clang that supports the builtin.

**Comment by ldionne** [comment]
Rebase to trigger CI. This can be merged once CI is green.

**Comment by ldionne** [comment]
The CI failure is a fluke, merging.

**Pull request merged**
