### PR TITLE
Delete the incorrect assert that assumes size of `APFloat` is the same as `IEEEFloat`.

### PR DESCRIPTION
**Pull request by DanielCChen**
This addition of the the following code in commit https://github.com/llvm/llvm-project/commit/6004f5550c8032f4c632cdbf5dbc0894bb33e51f#diff-3ec11da67f69353fd755e59cc71f551b5e93773fd4e6f6327c7f1c7074a82709R1474

```
static_assert(sizeof(APFloat) == sizeof(detail::IEEEFloat),
              "Empty base class optimization is not performed.");
```

broke our downstream code as not all the members of `APFloat` is IEEE. 

This PR is to delete the assertion.

@Ariel-Burton

### CODE REVIEW

**Comment by dtcxzyw** [comment]
This assertion is to make sure that EBO is performed on APFloat. What is the compiler you use to build llvm?

**Comment by DanielCChen** [comment]
> This assertion is to make sure that EBO is performed on APFloat. What is the compiler you use to build llvm?
We are building it on Linux on Power and AIX. This code broke our downstream code we have inside of APFloat that are not IEEE.

**Comment by DanielCChen** [comment]
> This assertion is to make sure that EBO is performed on APFloat. What is the compiler you use to build llvm?

We are building it on Linux on Power and AIX. This code broke our downstream code we have inside of APFloat that are not IEEE.

**Comment by dtcxzyw** [comment]
Can you please try to compile the following code with your compiler? https://godbolt.org/z/4jqhnjG3E
```
struct Empty {};
struct FloatImpl1 { float x; };
struct FloatImpl2 { float x; };
struct Float : public Empty {
    union {FloatImpl1 impl1;FloatImpl2 impl2;};
};

static_assert(sizeof(Float) == sizeof(float));
```

**Comment by dtcxzyw** [comment]
>  not all the members of APFloat is IEEE.

Oh I see. Do you add a new impl whose size is larger than `detail::IEEEFloat`?

**Comment by dtcxzyw** [comment]
> > not all the members of APFloat is IEEE.
> 
> Oh I see. Do you add a new impl whose size is larger than `detail::IEEEFloat`?

If so, at least we can assert `sizeof(APFloat) == sizeof(APFloat::Storage)`.

**Comment by dtcxzyw** [comment]
> > > > not all the members of APFloat is IEEE.
> > > 
> > > 
> > > Oh I see. Do you add a new impl whose size is larger than `detail::IEEEFloat`?
> > 
> > 
> > If so, at least we can assert `sizeof(APFloat) == sizeof(APFloat::Storage)`.
> 
> That's an interesting idea, but needs care to get it to work because if the assert is APFloat it won't compile because APFloat isn't complete until after the closing brace. It can't go outside `APFloat` because `Storage` is private. Nor can the assert go in `IEEEFloat`.
> 
> We could add a new `friend class APFloarChecker` to `APFloat` and do the check in that new class. Something like this:
> 
> ```
> lass APFloat {
>   union S {
>     int i;
>     long l;
>   } s;
>   friend class APFloatChecker;
> };
> 
> class APFloatChecker {
>   static_assert(sizeof(APFloat) == sizeof(APFloat::S));
> };
> ```
> 
> `APFloatChecker` wouldn't need to go in the `.h`, where the assertion is evaluated every time the file is processed. It could go in the `.cpp`, where it will be evaluated once per build.

Make sense to me.

**Comment by arsenm** [comment]
> The issue is that APFloat has a union (`Storage`). Downstream this includes a member / field for another floating point type. 

So the assert isn't wrong if you're actually changing the type downstream. If you're changing the type downstream you have to also change the assert downstream

**Comment by nikic** [comment]
Yeah, I don't think we should change the assert upstream. When you add support for your new floating point type upstream, we can decide whether we're willing to increase the APFloat size for it, or you need to reduce the size of your representation (e.g. by indirecting via an allocation, just like DoubleAPFloat does).

**Comment by DanielCChen** [comment]
Thanks for all the comments. We are currently looking into the issue.

**Comment by anhtuyenibm** [comment]
The new log graph is as follows:
```
     1 *   48bc068fd43f48170b4bae1b7eb8814b96d62ec3 Merge commit '9200adee266b5bfaa468c5ce2715ed9794e1a7a8'
     2 |\
     3 | * 9200adee266b5bfaa468c5ce2715ed9794e1a7a8 [libc++] Narrow the exports for common_type (#111681)
     4 | * e82fcda1475b6708b7d314fd7a54e551306d5739 [Coroutines] Move util headers to include/llvm (#111599)
     
     <...>
    50 | * 890e481358d6cb4e81629742eda32f9a1d6785d2 AMDGPU: Regenerate test checks
    51 * | 7484cc6fce2cf907442218c704a6b28e07eb3be8 Resolve merge conflicts with llvm/include/llvm/ADT/APFloat.h llvm/lib/Support/APFloat.cpp
    52 |\|
    53 | * 3b7091bcf3b48b63724500d821dc7a0ce8ffa3c9 [APFloat] add predicates to fltSemantics for hasZero and hasSignedRepr (#111451)
    54 * | 13c567f1499c9173f6e6f965f6945a7438bc7fd5 Merge commit '3b2bfb48239e674805a9c4e65be3c3a9eeabdf9c'
    55 |\|
    56 | * 3b2bfb48239e674805a9c4e65be3c3a9eeabdf9c [mlir] add missing CMake dependency on ShardingInterface generated headers for LinalgDialect (#111603)
    
    <...>
    81 | * 146d3f04ff92e396ea40ab581304e65e8511d8ac [lldb][test] Disable TestSharedLibStrippedSymbols on Arm
    82 * | bbb8ef544548143d87b06a366de4da6938646f4e Temporarily remove problematic static assert as agreed with Ariel Burton and Daniel Chen
    83 * | 515d335c4d9872ed0b5257ff6b46ac46c0ceea69 Merge commit '6004f5550c8032f4c632cdbf5dbc0894bb33e51f' - Will have problem with statis assert - Will be fixed temporarily as agreed with Daniel Chen and Ariel Burton - Ariel will restructure the r       elated classes upstream
    84 |\|
    85 | * 6004f5550c8032f4c632cdbf5dbc0894bb33e51f [ADT][APFloat] Make sure EBO is performed on APFloat (#111641)
    86 * | 69d9a63aa340eba0bfa64f7d1beaad165c1e9302 Merge commit 'baa1fc9825ca29a81f98146da6036e3415182f16'
    87 |\|
    88 | * baa1fc9825ca29a81f98146da6036e3415182f16 [ARM] Remove always-true checks from Thumb1 frame lowering (NFC) (#110283)         



```

**Comment by DanielCChen** [comment]
Sorry that I messed up my local branch. I will close this PR and re-post another one shortly.
Please note all these "unexpected" changes are in my local branch. It will not affect the main branch.
Apologies.

**Pull request closed without merging**
