### PR TITLE
[clang-tidy] fix false-positives for templates in `bugprone-return-const-ref-from-parameter`

### PR DESCRIPTION
**Pull request by 5chmidti**
In the AST for function templates, the return will be a DeclRefExpr,
even if the return type differs from that of the returned variable.
Protect against false-positives by constraining the canonical return
type to be that of the parameter.
Also streams the source range of the returned expression into the
diagnostic.

### CODE REVIEW

**Comment by 5chmidti** [comment]
@HerrCai0907  I was looking at false positives for templates regarding this check and ended up implementing the fix.

**Comment by 5chmidti** [comment]
The false positives that are fixed by implementing this fix are in lines: 98, 101, 110, 113.
The other tests are for completeness.

**Comment by 5chmidti** [comment]
Do we add `improvement` documentation for checks that landed in the same release cycle?

**Comment by SimplyDanny** [comment]
> Do we add `improvement` documentation for checks that landed in the same release cycle?

I don't think that's needed.

**Review by SimplyDanny — APPROVED** [review]

**Pull request merged**
