### PR TITLE
[libc][NFC] Reduce type clutter in str_to_float_test

### PR DESCRIPTION
**Pull request by gchatelet**

### CODE REVIEW

**Comment by gchatelet** [comment]
@michaelrj-google my original goal was to remove `LIBC_NAMESPACE` and `typename LIBC_NAMESPACE::fputil::FPBits<T>::UIntType` but I had to template the test class.
As such, it is less clear which type is being tested, let me know if you prefer to keep the type explicit.

**Review by lntue — COMMENTED** [review]
Without the types it's actually a bit hard to see which type is being tested.  Does it make sense to split this test into several files: `str_to_float.h` containing the test template, then `str_to_float.cpp`, `str_to_double.cpp`, `str_to_long_double.cpp` or something like that for test specializations.

**Comment by michaelrj-google** [comment]
I agree with Tue that the types being explicit is important. Splitting into multiple files sounds like a good overall solution.

**Comment by gchatelet** [comment]
I'm closing this PR to prevent confusion. I'll ping here with the "split" patch.

**Pull request closed without merging**
