### PR TITLE
Reland "[ARM] Stop gluing FP comparisons to FMSTAT"

### PR DESCRIPTION
**Pull request by s-barannikov**
Following #116547, this changes the result of `ARMISD::CMPFP*` and the
operand of `ARMISD::FMSTAT` from a special `Glue` type to a normal type.

This change allows comparisons to be CSEd and scheduled around as can be
seen in the test changes.

Note that `ARMISD::FMSTAT` is still glued to its consumer nodes; this is
going to be changed in a separate patch.

This patch also sets `CopyCost` of `cl_FPSCR_NZCV` register class to a
negative value. The reason is the same as for CCR register class: it
makes DAG scheduler and InstrEmitter try to avoid copies of `FPCSR_NZCV`
register to / from virtual registers. Previously, this was not
necessary, since no attempt was made to create copies in the first
place.

`TRI::getCrossCopyRegClass` is modified in a way that prevents DAG
scheduler from copying FPSCR into a virtual register. The register
allocator might need to spill the virtual register, but that only seem
to work in Thumb mode.

### CODE REVIEW

**Comment by s-barannikov** [comment]
@mstorsjo Would it be possible for you to check if this version resolves the issue you're observing pre-commit?

**Comment by s-barannikov** [comment]
The first commit adds a test that was crashing with the previous version of the PR.

**Comment by mstorsjo** [comment]
> @mstorsjo Would it be possible for you to check if this version resolves the issue you're observing pre-commit?

Yes - this version does seem to run correctly for both of the cases that previous broke. Thanks!

**Review by mstorsjo — APPROVED** [review]
LGTM, this no longer breaks my case.

**Pull request merged**
