### PR TITLE
[X86][compiler-rt] Split CPU names even they have the same subtype

### LINKED ISSUE #118205: Raptor Lake CPU detected as Alder Lake
rustc detects my i7-13700H as Alder Lake, Wikipedia lists it as Raptor Lake. Looking through rustc issues, it seems these kinds of misclassifications have always been LLVM bugs so I decided to report it here.

Image
Image

### PR DESCRIPTION
**Pull request by phoebewang**
Fixes: #118205

### CODE REVIEW

**Review by boomanaiden154 — COMMENTED** [review]
`llvm/lib/TargetParser/Host.cpp` needs to be updated as well and is probably what is causing the linked issue.

As a side note, can I get some reviews on my PRs to test/merge this infra between compiler-rt and LLVM?
1. #97861
2. #97856
3. #97872 (probably not ready for review yet).
4. #101927

That will make changes like this in the future easier.

**Comment by phoebewang** [comment]
> `llvm/lib/TargetParser/Host.cpp` needs to be updated as well and is probably what is causing the linked issue.
> 
> As a side note, can I get some reviews on my PRs to test/merge this infra between compiler-rt and LLVM?
> 
> 1. [[compiler-rt][X86] Unify getIntelProcessorTypeAndSubtype #97861](https://github.com/llvm/llvm-project/pull/97861)
> 2. [[compiler-rt][X86] Better unify ProcessorFeatures and X86TargetParser #97856](https://github.com/llvm/llvm-project/pull/97856)
> 3. [[compiler-rt][X86] Unify getAvailableFeatures #97872](https://github.com/llvm/llvm-project/pull/97872) (probably not ready for review yet).
> 4. [[compiler-rt] Add infrastructure for testing cpuid builtins #101927](https://github.com/llvm/llvm-project/pull/101927)
> 
> That will make changes like this in the future easier.

Good catch, thanks! I have a few comments on them, but I don't see how they guarantee synchronization between compiler and compiler-rt. Plus, how to sync with different libgcc?

**Comment by boomanaiden154** [comment]
> I don't see how they guarantee synchronization between compiler and compiler-rt

The plan is to make the files actually match given there are a large number of differences between them, through those PRs. Once everything matches appropriately, my plan is to write up another patch moving the implementations to `.inc` files that get diffed in the compiler-rt tests, so we get test failures if they're different. We might be able to directly copy over the code, but I think there were some issues with standalone builds, and that setup follows past precedent.

> how to sync with different libgcc?

What do you mean by this? This shouldn't change any compiler-rt/libgcc compatibility guarantees (although it will probably catch issues where we don't maintain ABI compatibility with libgcc in compiler-rt), just make the code between LLVM and compiler-rt closer.

**Review by boomanaiden154 — APPROVED** [review]
Changes LGTM.

**Pull request merged**
