### PR TITLE
[RISCV] Support bf16 vmv.v.v and vmerge.vvm intrinsics with `zvfbfmin`

### LINKED ISSUE #349: Should bf16 vmv.v.v and vmerge.vvm be supported with Zvfbfmin?
I notice that clang supports vmv_v_v and vmerge for f16 with Zvfhmin. Seems reasonable that bf16 should be the same.

CC: @kito-cheng @rofirrim

### PR DESCRIPTION
**Pull request by 4vtomat**
These two intrinsics are supported for f16 with `zvfhmin`, also support
them in bf16 to make it aligned to f16.

This resolve: https://github.com/riscv-non-isa/rvv-intrinsic-doc/issues/349

### CODE REVIEW

**Review by topperc — APPROVED** [review]
LGTM

**Comment by joshua-arch1** [comment]
I'm wondering why we need these intrinsics since we do not have vmv.v.v and vmerge.vvm instructions for bf16.

**Comment by topperc** [comment]
> I'm wondering why we need these intrinsics since we do not have vmv.v.v and vmerge.vvm instructions for bf16.

vmv.v.v and vmerge.vvm don't interpret the value in the elements. They work for integer or FP or bf16. If we don't provide the intrinsics then the user needs to use vreinterpret to do a vmerge or vmv.v.v operation on a vector of bf16.

**Comment by joshua-arch1** [comment]
> > I'm wondering why we need these intrinsics since we do not have vmv.v.v and vmerge.vvm instructions for bf16.
> 
> vmv.v.v and vmerge.vvm don't interpret the value in the elements. They work for integer or FP or bf16. If we don't provide the intrinsics then the user needs to use vreinterpret to do a vmerge or vmv.v.v operation on a vector of bf16.

I know what vmerge and vmv.v.v mean, but in a similar way, does it mean we need to add all the intrinsics for bf16 to keep consistent with other floating-point type?

**Comment by topperc** [comment]
> > > I'm wondering why we need these intrinsics since we do not have vmv.v.v and vmerge.vvm instructions for bf16.
> > 
> > 
> > vmv.v.v and vmerge.vvm don't interpret the value in the elements. They work for integer or FP or bf16. If we don't provide the intrinsics then the user needs to use vreinterpret to do a vmerge or vmv.v.v operation on a vector of bf16.
> 
> I know what vmerge and vmv.v.v mean, but in a similar way, does it mean we need to add all the intrinsics for bf16 to keep consistent with other floating-point type?

We already have load, store, vreinterpret, lmul_ext, lmul_trunc, vget, vcreate, vundefined. I file 3 issues on inconsistencies between Zvfhmin and Zvfbfmin

https://github.com/riscv-non-isa/rvv-intrinsic-doc/issues/349
https://github.com/riscv-non-isa/rvv-intrinsic-doc/issues/350
https://github.com/riscv-non-isa/rvv-intrinsic-doc/issues/351

**Pull request merged**
