### PR TITLE
[dsymutil] Fix spurious warnings in MachODebugMapParser

### PR DESCRIPTION
**Pull request by JDevlieghere**
When the MachODebugMapParser encounters an object file that cannot be found on disk, it currently leaves the parser in an incoherent state, resulting in spurious warnings that can in turn slow down dsymutil.

rdar://117515153

### CODE REVIEW

**Comment by JDevlieghere** [comment]
This addresses #78411

**Comment by JDevlieghere** [comment]
@Alpha-10000

**Review by adrian-prantl — APPROVED** [review]
Based on the test this SGTM!

**Comment by Alpha-10000** [comment]
LGTM

**Comment by yulingtianxia** [comment]
[L308-L309](https://github.com/llvm/llvm-project/blob/main/llvm/tools/dsymutil/MachODebugMapParser.cpp#L308-L309) of `MachODebugMapParser::switchToNewLibDebugMapObject` may have the same issue @JDevlieghere

**Comment by Alpha-10000** [comment]
We want to keep the DMO as long as we're not encountering a new library.
A longer term change here would probably be to have/reuse a `Duplicates` set similarly to what's being done for OSOs ([L642](https://github.com/llvm/llvm-project/blob/main/llvm/tools/dsymutil/MachODebugMapParser.cpp#L642)), which might get rid of spurious warnings.

**Pull request merged**
