### PR TITLE
[RISCV] Use the 'B' extension in RISC-V profile definitions

### PR DESCRIPTION
**Pull request by asb**
RVA22 has retroactively been defined as including 'B' (as it's a
shorthand for Zba+Zbb+Zbs, which were previously explicitly enumerated)
and RV{A,B,M}23 are defined featuring B. We don't currently infer B
whenever Zba+Zbb+Zbs are present due to concerns about compatibility
with external assemblers such as gas.

We don't believe that adding B to RVA22 will cause issues for users who (for instance) build with clang and assemble with binutils as looking at the binutils commit history:
    zic64b support was only committed in 25f05199bb7e35820c23e802424484accb7936b1 in July 2024
    B support was committed in c144f638337944101131d9fe6de4ab908f6d4c2d in May 2024

So given we emit zic64b anyway (as it has always been in the RVA22 spec), no binutils that would have previously successfully assembled our rva22u64 output should fail due to the addition of 'B'.

---
Note: This was initially posted as an RFC but is now ready for review

### CODE REVIEW

**Comment by lenary** [comment]
I think we shouldn't do this for RVA22, so as not to break existing users of that profile, who may have a toolchain that doesn't support B.

This change makes sense to me for the RV*23 profiles, especially since your change to RVM23 has been accepted.

**Comment by topperc** [comment]
The change should be reflected in clang/test/Driver/riscv-profiles.c too.

**Comment by asb** [comment]
I've added the CHECK lines to riscv-profiles.c as spotted by @topperc, and based on the above discussion I think this is now ready to review.

**Review by topperc — APPROVED** [review]
LGTM

**Pull request merged**
