### PR TITLE
[AArch64][SVE2] UZP should only have one result

### PR DESCRIPTION
**Pull request by Saldivarcher**
`UZP1` and `UZP2` are only expecting one result value, so this `getNode` call should be updated to match that.

This is in response to #92779.

### CODE REVIEW

**Review by davemgreen — COMMENTED** [review]
This sounds OK to me. Thanks for the fix.

Does this mean we don't have any tests for this code? Can we add one? It looks like the tests in llvm/test/CodeGen/AArch64/aarch64-vuzp.ll no longer trigger it, and I'm not sure how to make a simple reproducer that actually gets to this code as a BuildVector.

**Comment by Saldivarcher** [comment]
@davemgreen I can add one, I had a reproducer in the issue I created. Here it is:
```llvm
target datalayout = "e-m:e-i8:8:32-i16:16:32-i64:64-i128:128-n32:64-S128"
target triple = "aarch64-unknown-linux-gnu"

define void @main(ptr %0) {
"file t13_206.f90, line 27, bb4133118":
  %1 = bitcast <vscale x 2 x i64> zeroinitializer to <vscale x 4 x i32>
  %r2689 = extractelement <vscale x 4 x i32> %1, i64 0
  %r2690 = insertelement <2 x i32> zeroinitializer, i32 %r2689, i64 0
  %2 = bitcast <vscale x 2 x i64> zeroinitializer to <vscale x 4 x i32>
  %r2692 = extractelement <vscale x 4 x i32> %2, i64 2
  %r2693 = insertelement <2 x i32> %r2690, i32 %r2692, i64 1
  %r2696 = sub <2 x i32> zeroinitializer, %r2693
  %r2697 = extractelement <2 x i32> %r2696, i64 0
  %r2698 = sext i32 %r2697 to i64
  %r2699 = insertelement <vscale x 2 x i64> zeroinitializer, i64 %r2698, i64 0
  %r2700 = extractelement <2 x i32> %r2696, i64 1
  %r2701 = sext i32 %r2700 to i64
  %r2702 = insertelement <vscale x 2 x i64> %r2699, i64 %r2701, i64 0
  store <vscale x 2 x i64> %r2702, ptr %0, align 16
  ret void
}
```

**Comment by davemgreen** [comment]
Yeah it's worth adding as a test. That code has a number of things that looks like they could be simplified by the compiler, so it might not keep testing the same thing forever, but it's good to have so we know it doesn't break in the future.

I was wondering if we should just remove that bit of code, it must be quite rare for it to come up, the BuildVectors are more often turned into shuffles before they get to that point nowadays. Let me try some experiments.

**Comment by Saldivarcher** [comment]
I added the test, let me know how it looks.

Yeah, please go ahead and do what you think is necessary, I'm not entirely sure why we go down this code path to begin with.

**Review by davemgreen — APPROVED** [review]
Thanks for adding the test. I did see this come up in a couple of places, so lets keep it for now and fix the problem it has.

LGTM

**Comment by Saldivarcher** [comment]
Sounds good! Thanks for taking a look at this btw 😎 

Would you also be able to rebase this PR? I don't have commit access, please and thank you 🙏

**Pull request merged**
