### PR TITLE
[lldb] Make SBType::FindDirectNestedType work with expression ASTs

### PR DESCRIPTION
**Pull request by labath**
The types we get out of expressions will not have an associated symbol file, so the current method of looking up the type will fail. Instead, I plumb the query through the TypeSystem class. This correctly finds the type in both cases (importing it into the expression AST if needed). I haven't measured, but it should also be more efficient than doing a type lookup (at least, after the type has already been found once).

### CODE REVIEW

**Comment by labath** [comment]
In terms of #68705, I think this will fix the issue where the data formatter works on `frame var foo` but not `expr -- foo`. At least that's the problem I ran into when trying to use this in my own formatter..

One thing I'd like to get feedback on is whether this should be looking into base classes. The discussion on the original PR focuses on lexically nested types, but going through base classes (following usual language rules) is another form of nesting. Both the existing and the new implementations don't do that, but I think it would be more natural to do it. Of course, then the function can definitely return more than one result...

**Comment by Endilll** [comment]
> One thing I'd like to get feedback on is whether this should be looking into base classes. The discussion on the original PR focuses on lexically nested types, but going through base classes (following usual language rules) is another form of nesting. Both the existing and the new implementations don't do that, but I think it would be more natural to do it. Of course, then the function can definitely return more than one result...

What you're describing here is in line with member lookup described in the Standard. While it might be a useful facility, it's at odds with the intent of `FindDirectNestedTypes()` to be a small building block for efficient AST traversal. For the use case I have for this function, any amount of lookup is going to regress the performance of the formatter, and subsequently responsiveness of the debugger. So if you're going to pursue this, I suggest exposing this as a new function.

**Comment by Michael137** [comment]
> > One thing I'd like to get feedback on is whether this should be looking into base classes. The discussion on the original PR focuses on lexically nested types, but going through base classes (following usual language rules) is another form of nesting. Both the existing and the new implementations don't do that, but I think it would be more natural to do it. Of course, then the function can definitely return more than one result...
> 
> What you're describing here is in line with member lookup described in the Standard. While it might be a useful facility, it's at odds with the intent of `FindDirectNestedTypes()` to be a small building block for efficient AST traversal. For the use case I have for this function, any amount of lookup is going to regress the performance of the formatter, and subsequently responsiveness of the debugger. So if you're going to pursue this, I suggest exposing this as a new function.

I don't expect the simple `DeclContext` lookup proposed here to be expensive. What *is* expensive from the data-formatters point of view is either full-blown expression evaluation or a global search in DWARF for some type.

Re. looking at base classes, don't have a strong opinion on it. There's some precedent for looking at base classes already in `TypeSystemClang` (e.g., `GetIndexOfChildWithName`). But as you say @labath, that would require an API change

**Comment by labath** [comment]
> > > One thing I'd like to get feedback on is whether this should be looking into base classes. The discussion on the original PR focuses on lexically nested types, but going through base classes (following usual language rules) is another form of nesting. Both the existing and the new implementations don't do that, but I think it would be more natural to do it. Of course, then the function can definitely return more than one result...
> > 
> > 
> > What you're describing here is in line with member lookup described in the Standard. While it might be a useful facility, it's at odds with the intent of `FindDirectNestedTypes()` to be a small building block for efficient AST traversal. For the use case I have for this function, any amount of lookup is going to regress the performance of the formatter, and subsequently responsiveness of the debugger. So if you're going to pursue this, I suggest exposing this as a new function.
> 
> I don't expect the simple `DeclContext` lookup proposed here to be expensive. What _is_ expensive from the data-formatters point of view is either full-blown expression evaluation or a global search in DWARF for some type.

Agreed. This should be the same lookup that clang does every time is sees a `::`. Going through (potentially many) calls to FindTypes would be a different story. The reason I was asking is because I was not sure if this behavior was just a side-effect of how the original implementation worked, or if it was the intention all along. Judging by the response, it's the latter.

> 
> Re. looking at base classes, don't have a strong opinion on it. There's some precedent for looking at base classes already in `TypeSystemClang` (e.g., `GetIndexOfChildWithName`). But as you say @labath, that would require an API change

That's makes sense. Even if it was not the intention, the API makes this the only reasonable implementation. I have no use for the base-class traversal (may change in the future). If there's is a need for it, we can add a different API.

**Review by Michael137 — APPROVED** [review]

**Comment by Endilll** [comment]
@Michael137 suggested that I check that performance of `FindDirectNestedType` doesn't regress (at least for my use case), since I have custom instrumentation in my formatter. I can confirm that 3 versions of this function (#68705, #74786, and this PR) exhibit the same level of performance. Raw numbers fluctuate a lot, but I don't see anything concerning:
```
This PR
-------
2,611,025
1,988,893
2,878,981
1,873,220

main branch (#74786)
----
1,973,071
2,542,073
1,509,624

Initial implementation (#68705)
------
2,029,233
2,477,041
1,315,462
```

**Comment by labath** [comment]
> @Michael137 suggested that I check that performance of `FindDirectNestedType` doesn't regress (at least for my use case), since I have custom instrumentation in my formatter. I can confirm that 3 versions of this function (#68705, #74786, and this PR) exhibit the same level of performance. Raw numbers (in nanoseconds) fluctuate a lot, but I don't see anything concerning:
> 
> ```
> This PR
> -------
> 2,611,025
> 1,988,893
> 2,878,981
> 1,873,220
> 
> main branch (#74786)
> ----
> 1,973,071
> 2,542,073
> 1,509,624
> 
> Initial implementation (#68705)
> ------
> 2,029,233
> 2,477,041
> 1,315,462
> ```

Cool. Thanks for confirming that.

**Pull request merged**
