### PR TITLE
[TBAA] Add verifier for tbaa.struct metadata

### PR DESCRIPTION
**Pull request by juliannagele**
Adds logic to the IR verifier that checks whether !tbaa.struct nodes are well-formed. That is, it checks that the operands of !tbaa.struct nodes are in groups of three, that each group of three operands consists of two integers and a valid tbaa node, and that the regions described by the offset and size operands are non-overlapping.

### CODE REVIEW

**Review by arsenm — APPROVED** [review]

**Review by fhahn — APPROVED** [review]
LGTM, thanks!

**Comment by uweigand** [comment]
This is breaking the openmp-s390x-linux build bot.  I was able to reduce the problem to the following test case:
```
typedef struct kmp_affinity_attrs_t {
  int core_type : 8;
  int core_eff : 8;
  unsigned valid : 1;
  unsigned reserved : 15;
} kmp_affinity_attrs_t;

typedef struct kmp_affinity_t {
  kmp_affinity_attrs_t core_attr_gran;
  int compact;
} kmp_affinity_t;

void test(kmp_affinity_t *affinity) {
  *affinity = (kmp_affinity_t) { { 0 }, 0 };
}
```

Building this with `clang --target=s390x-ibm-linux -O` results in
```
Overlapping tbaa.struct regions
  call void @llvm.memcpy.p0.p0.i64(ptr align 4 %0, ptr align 4 %.compoundliteral, i64 8, i1 false), !tbaa.struct !12
!12 = !{i64 2, i64 4, !13, i64 4, i64 4, !14}
fatal error: error in backend: Broken module found, compilation aborted!
```

The first offset of 2 seems wrong to me - not sure where this came from.  This seems to be an actual bug uncovered by this test?

**Comment by amy-kwan** [comment]
I believe this patch is still causing failures on the PPC64BE bots in the recent builds: https://lab.llvm.org/buildbot/#/builders/93/builds/19428/steps/10/logs/stdio

The errors are similar to what @uweigand reported.

**Comment by uweigand** [comment]
Hmm, if it fails on big-endian platforms, maybe that indicates an endian bug in (bit)field offset computation somewhere?

**Comment by fhahn** [comment]
Thanks for the report, reverted for now

**Comment by alexey-bataev** [comment]
Looks like it fails clang/llvm compiler build with ThinLTO with openmp
```
Overlapping tbaa.struct regions
  tail call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(40) %17, ptr noundef nonnull align 8 dereferenceable(40) %18, i64 40, i1 false), !tbaa.struct !232
!232 = !{i64 0, i64 8, !138, i64 0, i64 8, !138, i64 0, i64 8, !138, i64 0, i64 8, !138, i64 8, i64 8, !139, i64 0, i64 8, !138, i64 0, i64 1, !124, i64 0, i64 4, !233, i64 0, i64 4, !233, i64 0, i64 8, !138, i64 0, i64 8, !138, i64 0, i64 8, !138, i64 0, i64 8, !138, i64 0, i64 8, !138, i64 16, i64 8, !138, i64 16, i64 8, !138, i64 16, i64 8, !138, i64 16, i64 8, !138, i64 24, i64 8, !139, i64 16, i64 8, !138, i64 16, i64 1, !124, i64 16, i64 4, !233, i64 16, i64 4, !233, i64 16, i64 8, !138, i64 16, i64 8, !138, i64 16, i64 8, !138, i64 16, i64 8, !138, i64 16, i64 8, !138, i64 32, i64 1, !234, i64 33, i64 1, !234}
Overlapping tbaa.struct regions
  tail call void @llvm.memcpy.p0.p0.i64(ptr noundef nonnull align 8 dereferenceable(40) %22, ptr noundef nonnull align 8 dereferenceable(40) %23, i64 40, i1 false), !tbaa.struct !232
!232 = !{i64 0, i64 8, !138, i64 0, i64 8, !138, i64 0, i64 8, !138, i64 0, i64 8, !138, i64 8, i64 8, !139, i64 0, i64 8, !138, i64 0, i64 1, !124, i64 0, i64 4, !233, i64 0, i64 4, !233, i64 0, i64 8, !138, i64 0, i64 8, !138, i64 0, i64 8, !138, i64 0, i64 8, !138, i64 0, i64 8, !138, i64 16, i64 8, !138, i64 16, i64 8, !138, i64 16, i64 8, !138, i64 16, i64 8, !138, i64 24, i64 8, !139, i64 16, i64 8, !138, i64 16, i64 1, !124, i64 16, i64 4, !233, i64 16, i64 4, !233, i64 16, i64 8, !138, i64 16, i64 8, !138, i64 16, i64 8, !138, i64 16, i64 8, !138, i64 16, i64 8, !138, i64 32, i64 1, !234, i64 33, i64 1, !234}
Overlapping tbaa.struct regions
  store ptrclang++: error: unable to execute command: Aborted
clang++: error: linker command failed due to signal (use -v to see invocation)
[8/13] Building CXX object openmp/libomptarget/plugins-nextgen/common/CMakeFiles/PluginCommon.dir/src/JIT.cpp.o
```

**Comment by juliannagele** [comment]
Thanks for the report, do you have the full clang invocation? If possible can you check if the IR coming out of clang is already invalid?

**Comment by alexey-bataev** [comment]
Looks like it happens at linking stage, not at compile time:
```
clang++ --target=x86_64-unknown-linux-gnu -fPIC -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Wall -fcolor-diagnostics -Wcast-qual -Wformat-pedantic -Wimplicit-fallthrough -Wsign-compare -Wno-extra -Wno-pedantic -fno-semantic-interposition -fdata-sections -O3 -DNDEBUG  -Wl,-z,defs -Wl,-z,nodelete -fuse-ld=lld -Wl,--color-diagnostics   -Wl,--gc-sections  -flto=thin -shared -Wl,-soname,libomptarget.so.19.0git -o lib/libomptarget.so.19.0git openmp/libomptarget/src/CMakeFiles/omptarget.dir/device.cpp.o openmp/libomptarget/src/CMakeFiles/omptarget.dir/interface.cpp.o openmp/libomptarget/src/CMakeFiles/omptarget.dir/omptarget.cpp.o openmp/libomptarget/src/CMakeFiles/omptarget.dir/OffloadRTL.cpp.o openmp/libomptarget/src/CMakeFiles/omptarget.dir/LegacyAPI.cpp.o openmp/libomptarget/src/CMakeFiles/omptarget.dir/PluginManager.cpp.o openmp/libomptarget/src/CMakeFiles/omptarget.dir/DeviceImage.cpp.o openmp/libomptarget/src/CMakeFiles/omptarget.dir/OpenMP/API.cpp.o openmp/libomptarget/src/CMakeFiles/omptarget.dir/OpenMP/Mapping.cpp.o openmp/libomptarget/src/CMakeFiles/omptarget.dir/OpenMP/InteropAPI.cpp.o openmp/libomptarget/src/CMakeFiles/omptarget.dir/OpenMP/OMPT/Callback.cpp.o  -Wl,-rpath,"\$ORIGIN:runtimes/runtimes-bins/openmp/libomptarget/src/..:runtimes/runtimes-bins/openmp/runtime/src:"  openmp/runtime/src/libomp.so  lib/libLLVMSupport.a  lib/libLLVMObject.a  -Wl,--version-script=llvm-project/openmp/libomptarget/src/exports  -lrt  -lm  lib/libLLVMIRReader.a  lib/libLLVMBitReader.a  lib/libLLVMAsmParser.a  lib/libLLVMCore.a  lib/libLLVMRemarks.a  lib/libLLVMBitstreamReader.a  lib/libLLVMMCParser.a  lib/libLLVMMC.a  lib/libLLVMDebugInfoCodeView.a  lib/libLLVMTextAPI.a  lib/libLLVMBinaryFormat.a  lib/libLLVMTargetParser.a  lib/libLLVMSupport.a  -lrt  -lpthread  -ldl  -lm  /usr/lib64/libz.so  /usr/lib64/libtinfo.so lib/libLLVMDemangle.a
```

**Comment by juliannagele** [comment]
hmm, struggling to reproduce this one I'm afraid, any chance you could share the bitcode input for ThinLTO (--save-temps), and maybe the full cmake invocation

**Comment by alexey-bataev** [comment]
> hmm, struggling to reproduce this one I'm afraid, any chance you could share the bitcode input for ThinLTO (--save-temps), and maybe the full cmake invocation

Here is the config of clang/LLVM building:
```
cmake -G Ninja -DCMAKE_BUILD_TYPE=Release $HOME/clang_tools/llvm-project/llvm -DCMAKE_C_COMPILER=clang  -DCMAKE_CXX_COMPILER=clang++ -DLLVM_ENABLE_PROJECTS="clang;compiler-rt;clang-tools-extra;lld" -DLLVM_ENABLE_RUNTIMES="openmp" -DLLVM_TARGETS_TO_BUILD="X86" -DLLVM_USE_LINKER=lld -DLLVM_CCACHE_BUILD=true -DLLVM_PARALLEL_COMPILE_JOBS=12 -DLLVM_PARALLEL_LINK_JOBS=2 -DOPENMP_ENABLE_LIBOMPTARGET_PROFILING=OFF -DCMAKE_INSTALL_PREFIX=$HOME/clang_tools -DLIBOMPTARGET_NVPTX_COMPUTE_CAPABILITIES=all -DLIBOMPTARGET_BUILD_DEVICERTL_BCLIB=false -DLLVM_ENABLE_RTTI=ON -DLLVM_ENABLE_EH=ON -DLIBOMPTARGET_BUILD_CUDA_PLUGIN=false -DLIBOMPTARGET_BUILD_AMDGPU_PLUGIN=false -DCMAKE_C_FLAGS="-Wformat -Wno-conversion" -DCMAKE_CXX_FLAGS="-Wformat -Wno-conversion" -DCMAKE_ASM_FLAGS="-Wformat -Wno-conversion" -DCMAKE_C_FLAGS=-march=native -DCMAKE_CXX_FLAGS=-march=native -DLLVM_ENABLE_LTO=Thin
ninja -j12
```

**Comment by Dinistro** [comment]
Can confirm that this also breaks on our end on a multitude of cases (all of them involving LTO).

**Comment by juliannagele** [comment]
Ok thanks, still trying to get this to happen on my end, if you have any more info on how to reproduce that'd be great

**Comment by Dinistro** [comment]
> Ok thanks, still trying to get this to happen on my end, if you have any more info on how to reproduce that'd be great

I can sadly only reproduce this on a very large codebase that mostly consists of internal source code that I'm not allowed to share. @alexey-bataev do you have anything you can share that allows reproducing this issue?

**Comment by alexey-bataev** [comment]
> > Ok thanks, still trying to get this to happen on my end, if you have any more info on how to reproduce that'd be great
> 
> I can sadly only reproduce this on a very large codebase that mostly consists of internal source code that I'm not allowed to share. @alexey-bataev do you have anything you can share that allows reproducing this issue?

I shared already, for me it crashes on on clang/LLVM (+ openmp runtime) build with ThinLTO, shared the options how to build it

**Comment by tstellar** [comment]
This change is causing our builds of LLVM to fail in Fedora.  Here is how you can reproduce:

```
export LD_LIBRARY_PATH=:/home/fedora/llvm-project/redhat-linux-build/lib64
export CFLAGS='-O2 -flto=thin -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS --config /usr/lib/rpm/redhat/redhat-hardened-clang.cfg -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_DEFAULT_SOURCE -Dasm=__asm__ '
export CXXFLAGS='-O2 -flto=thin -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS --config /usr/lib/rpm/redhat/redhat-hardened-clang.cfg -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_DEFAULT_SOURCE -Dasm=__asm__ '
export FFLAGS='-O2 -flto=thin -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS --config /usr/lib/rpm/redhat/redhat-hardened-clang.cfg -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_DEFAULT_SOURCE -Dasm=__asm__ -I/usr/lib64/gfortran/modules '
export FCFLAGS='-O2 -flto=thin -fexceptions -g -grecord-gcc-switches -pipe -Wall -Werror=format-security -Wp,-U_FORTIFY_SOURCE,-D_FORTIFY_SOURCE=3 -Wp,-D_GLIBCXX_ASSERTIONS --config /usr/lib/rpm/redhat/redhat-hardened-clang.cfg -fstack-protector-strong -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_DEFAULT_SOURCE -Dasm=__asm__ -I/usr/lib64/gfortran/modules '
export LDFLAGS='-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now    -Wl,--build-id=sha1  '
export CC=clang
export CXX=clang++
rm -Rf redhat-linux-build
/usr/bin/cmake -S llvm -B redhat-linux-build -DCMAKE_C_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_CXX_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_Fortran_FLAGS_RELEASE:STRING=-DNDEBUG -DCMAKE_VERBOSE_MAKEFILE:BOOL=ON -DCMAKE_INSTALL_DO_STRIP:BOOL=OFF -DCMAKE_INSTALL_PREFIX:PATH=/usr -DINCLUDE_INSTALL_DIR:PATH=/usr/include -DLIB_INSTALL_DIR:PATH=/usr/lib64 -DSYSCONF_INSTALL_DIR:PATH=/etc -DSHARE_INSTALL_PREFIX:PATH=/usr/share -DLIB_SUFFIX=64 -DBUILD_SHARED_LIBS:BOOL=ON -G Ninja '-DLLVM_ENABLE_PROJECTS=clang;clang-tools-extra' -DCLANG_DEFAULT_PIE_ON_LINUX=OFF -DPPC_LINUX_DEFAULT_IEEELONGDOUBLE=ON -DPYTHON_EXECUTABLE=/usr/bin/python3 -DLLVM_INCLUDE_TESTS:BOOL=ON -DCLANG_INCLUDE_TESTS:BOOL=ON -DLLVM_BUILD_UTILS:BOOL=ON -DCLANG_ENABLE_ARCMT:BOOL=ON -DCLANG_ENABLE_STATIC_ANALYZER:BOOL=ON  -DCLANG_PLUGIN_SUPPORT:BOOL=ON -DENABLE_LINKER_BUILD_ID:BOOL=ON -DLLVM_ENABLE_EH=ON -DCLANG_LINK_CLANG_DYLIB=ON -DCLANG_BUILD_EXAMPLES:BOOL=OFF '-DCLANG_REPOSITORY_STRING=Fedora 19.0.0~pre20240419.gb566810add5b7c-1.fc39' -DCLANG_RESOURCE_DIR=../lib/clang/19 -DLLVM_EXTERNAL_CLANG_TOOLS_EXTRA_SOURCE_DIR=../clang-tools-extra -DCLANG_CONFIG_FILE_SYSTEM_DIR=/etc/clang/ -DCLANG_DEFAULT_UNWINDLIB=libgcc '-DLLVM_ENABLE_RUNTIMES=compiler-rt;openmp' -DCOMPILER_RT_INSTALL_PATH=/usr/lib/clang/19 -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=ON -DCOMPILER_RT_INCLUDE_TESTS:BOOL=OFF -DLIBOMP_HAVE_VERSION_SCRIPT_FLAG:BOOL=ON -DLIBOMP_INSTALL_ALIASES=OFF -DOPENMP_LIBDIR_SUFFIX=64 -DOPENMP_INSTALL_LIBDIR=lib64 -DBUILD_SHARED_LIBS:BOOL=OFF -DLLVM_PARALLEL_LINK_JOBS=1 -DCMAKE_BUILD_TYPE=RelWithDebInfo -DCMAKE_SKIP_RPATH:BOOL=ON -DLLVM_LIBDIR_SUFFIX=64 -DLLVM_TARGETS_TO_BUILD=all -DLLVM_ENABLE_LIBCXX:BOOL=OFF -DLLVM_ENABLE_ZLIB:BOOL=ON -DLLVM_ENABLE_FFI:BOOL=ON -DLLVM_ENABLE_RTTI:BOOL=ON -DLLVM_USE_PERF:BOOL=ON -DLLVM_BINUTILS_INCDIR=/usr/include -DLLVM_EXPERIMENTAL_TARGETS_TO_BUILD=AVR -DLLVM_BUILD_RUNTIME:BOOL=ON -DLLVM_INCLUDE_TOOLS:BOOL=ON -DLLVM_BUILD_TOOLS:BOOL=ON -DLLVM_BUILD_TESTS:BOOL=ON -DLLVM_INSTALL_GTEST:BOOL=ON -DLLVM_LIT_ARGS=-vv -DLLVM_INCLUDE_EXAMPLES:BOOL=ON -DLLVM_BUILD_EXAMPLES:BOOL=OFF -DLLVM_INCLUDE_UTILS:BOOL=ON -DLLVM_INSTALL_UTILS:BOOL=ON -DLLVM_UTILS_INSTALL_DIR:PATH=/usr/bin -DLLVM_TOOLS_INSTALL_DIR:PATH=bin  -DLLVM_ENABLE_SPHINX:BOOL=ON -DLLVM_ENABLE_DOXYGEN:BOOL=OFF -DLLVM_VERSION_SUFFIX=pre20240419.gb566810add5b7c -DLLVM_UNREACHABLE_OPTIMIZE:BOOL=ON -DLLVM_BUILD_LLVM_DYLIB:BOOL=ON -DLLVM_LINK_LLVM_DYLIB:BOOL=ON -DLLVM_BUILD_EXTERNAL_COMPILER_RT:BOOL=ON -DLLVM_INSTALL_TOOLCHAIN_ONLY:BOOL=OFF -DLLVM_DEFAULT_TARGET_TRIPLE=x86_64-redhat-linux-gnu -DSPHINX_WARNINGS_AS_ERRORS=OFF -DCMAKE_INSTALL_PREFIX=/usr -DLLVM_INSTALL_SPHINX_HTML_DIR=/usr/share/doc/llvm/html -DSPHINX_EXECUTABLE=/usr/bin/sphinx-build-3 -DLLVM_INCLUDE_BENCHMARKS=OFF '-DCMAKE_SHARED_LINKER_FLAGS=-Wl,-z,relro -Wl,--as-needed  -Wl,-z,now    -Wl,--build-id=sha1'

ninja -v -C redhat-linux-build



```

**Comment by tstellar** [comment]
Given the number of issues reported with this change, can we revert it while it is investigated?

**Comment by juliannagele** [comment]
Sure, I've finally managed to reproduce it, but will probably need a bit of time to figure out what's going wrong

**Comment by fhahn** [comment]
Reverted again for now c8e5ad4e123a5fb082355947a896980464689c31

**Pull request merged**
