### PR TITLE
Revert "[mlir][Transforms] Dialect conversion: Make materializations optional"

### PR DESCRIPTION
**Pull request by matthias-springer**
Reverts llvm/llvm-project#104668

This commit triggers an edge case that can cause circular `unrealized_conversion_cast` ops. https://github.com/llvm/llvm-project/pull/106760 may fix it, but it is has other issues. Reverting this PR for now, until I find a solution for that problem.

### CODE REVIEW

**Comment by maerhart** [comment]
@matthias-springer Do you have a timeline for the mentioned solution? If it takes longer (>1 week), would it be possible to revert #101514 as well (because of the issue @mikeurbach already mentioned there)?

**Comment by matthias-springer** [comment]
I just went back to the discussion on https://github.com/llvm/llvm-project/pull/101514. It sounded like https://github.com/llvm/llvm-project/pull/104668 would fix your issue. (That PR has landed.) Is that not the case?

**Comment by matthias-springer** [comment]
I think this should be fine: https://github.com/llvm/llvm-project/pull/107109. (A test case is still missing.) This passes with MLIR. Also tried it with IREE with a few minor integration fixes and I don't see any failure (but I have not run the CI yet). Ideally, I'd like to also run it by Google to see if something is breaking.

Is there an easy way to reproduce your issue? Maybe we can just fix it quickly to give people more time to take a look at #107109.

**Comment by maerhart** [comment]
Thanks a lot for working on this!

> I just went back to the discussion on #101514. It sounded like #104668 would fix your issue. (That PR has landed.) Is that not the case?

Yes, https://github.com/llvm/llvm-project/pull/104668 fixed the issue. The problem is just that this PR reverted that fix.

I checked out https://github.com/llvm/llvm-project/pull/107109, and all our tests pass on top of that branch. It's not very time-critical; we integrate upstream weekly, but delaying it by a few days should be fine.

I don't have an upstream example to reproduce this, but we can return to it if necessary.

As an example, the following fails with a "null operands" error (I think for an op created during type conversion materialization, maybe because the `%1` operand still had the source type when the `add` was converted and later gets replaced with the result of the converted `hwarith.constant` op, but in some way not correctly?)
```mlir
  hw.module @backedges() {
    %0 = hwarith.add %1, %1 : (ui1, ui1) -> ui2
    %1 = hwarith.constant 1 : ui1
    hw.output
  }
```
If the order of the two operations in the body is changed, it succeeds and returns the following:
```mlir
  hw.module @backedges() {
    %true = hw.constant true
    %false = hw.constant false
    %0 = comb.concat %false, %true : i1, i1
    %false_0 = hw.constant false
    %1 = comb.concat %false_0, %true : i1, i1
    %2 = comb.add %0, %1 : i2
    hw.output
  }
```
command: `circt-opt -lower-hwarith-to-hw input.mlir`

**Comment by matthias-springer** [comment]
Oh I got confused with the PR numbers... I heard back from the Google and IREE folks and https://github.com/llvm/llvm-project/pull/107109 is safe to land from their side. I will try to add a test for the cyclic cast ops (this evening or tomorrow), and then this is good to merge from my side.

**Comment by matthias-springer** [comment]
I added a test case. #107109 is ready to land from my perspective. I added you as reviewers. (The original PR was already reviewed, but I added a bit of code, so it's better to have it reviewed again.)

**Pull request merged**
