### PR TITLE
clang/AMDGPU: Emit atomicrmw from {global|flat}_atomic_fadd_v2f16 builtins

### PR DESCRIPTION
**Pull request by arsenm**

### CODE REVIEW

**Comment by arsenm** [comment]
ping

**Review by arsenm — COMMENTED** [review]
ping

**Review by arsenm — COMMENTED** [review]
ping

**Review by shiltian — APPROVED** [review]

**Comment by arsenm** [comment]
### Merge activity

* **Aug 20, 2:53 PM EDT**: @arsenm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/96873).

**Pull request merged**
