### PR TITLE
Bump the DWARF version number to 5 on Darwin.

### PR DESCRIPTION
**Pull request by adrian-prantl**
The default debug info format for newer versions of Darwin is DWARF 5.

https://developer.apple.com/documentation/xcode-release-notes/xcode-16-release-notes

rdar://110925733

### CODE REVIEW

**Review by JDevlieghere — APPROVED** [review]
🥳

**Comment by pogo59** [comment]
Well, hmmm, I dunno, a radical change like this really wants an RFC and weeks of debate, right?
😄

**Comment by dwblaikie** [comment]
Congrats on the milestone! Glad to have more of us together on the same version for all the positive feedback loops, etc :)

**Comment by fmayer** [comment]
This broke our buildbot: https://lab.llvm.org/buildbot/#/builders/37/builds/35987

```
FAILED: tools/clang/lib/Driver/CMakeFiles/obj.clangDriver.dir/ToolChains/Darwin.cpp.o 
CCACHE_CPP2=yes CCACHE_HASHDIR=yes /usr/bin/ccache /b/sanitizer-x86_64-linux/build/llvm_build0/bin/clang++ -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/b/sanitizer-x86_64-linux/build/build_symbolizer/tools/clang/lib/Driver -I/b/sanitizer-x86_64-linux/build/llvm-project/clang/lib/Driver -I/b/sanitizer-x86_64-linux/build/llvm-project/clang/include -I/b/sanitizer-x86_64-linux/build/build_symbolizer/tools/clang/include -I/b/sanitizer-x86_64-linux/build/build_symbolizer/include -I/b/sanitizer-x86_64-linux/build/llvm-project/llvm/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -fno-common -Woverloaded-virtual -Wno-nested-anon-types -O3 -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -UNDEBUG -MD -MT tools/clang/lib/Driver/CMakeFiles/obj.clangDriver.dir/ToolChains/Darwin.cpp.o -MF tools/clang/lib/Driver/CMakeFiles/obj.clangDriver.dir/ToolChains/Darwin.cpp.o.d -o tools/clang/lib/Driver/CMakeFiles/obj.clangDriver.dir/ToolChains/Darwin.cpp.o -c /b/sanitizer-x86_64-linux/build/llvm-project/clang/lib/Driver/ToolChains/Darwin.cpp
/b/sanitizer-x86_64-linux/build/llvm-project/clang/lib/Driver/ToolChains/Darwin.cpp:1268:23: error: comparison of different enumeration types ('DarwinPlatformKind' and 'llvm::Triple::OSType') [-Werror,-Wenum-compare]
 1268 |       (TargetPlatform == llvm::Triple::BridgeOS))
      |        ~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~
/b/sanitizer-x86_64-linux/build/llvm-project/clang/lib/Driver/ToolChains/Darwin.cpp:1268:23: error: result of comparison of constant 'BridgeOS' (28) with expression of type 'DarwinPlatformKind' is always false [-Werror,-Wtautological-constant-out-of-range-compare]
 1268 |       (TargetPlatform == llvm::Triple::BridgeOS))
      |        ~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~~~
2 errors generated.
ninja: build stopped: subcommand failed.

```

**Comment by adrian-prantl** [comment]
Thanks!

**Comment by adrian-prantl** [comment]
Relanded in 8f57f6895724f858c9db924200524fad86cc4f11

**Pull request merged**
