### PR TITLE
[sanitizer_common] Block asynchronous signals only

### PR DESCRIPTION
**Pull request by thurstond**
This changes the behavior of `BlockSignals` and `ScopedBlockSignals` to block only asynchronous signals.

This extension is intended to be used in a future fix for MSan (block async signals during `MsanThread::Destroy`).

### CODE REVIEW

**Review by vitalybuka — COMMENTED** [review]
Let's not make this an option. Just do this unconditionally.
This code exists to block async signals anyway.

**Comment by thurstond** [comment]
> Let's not make this an option. Just do this unconditionally. This code exists to block async signals anyway.

Done

**Review by vitalybuka — APPROVED** [review]

**Comment by rorth** [comment]
This patch broke the [Solaris/amd64 buildbot](https://lab.llvm.org/staging/#/builders/94/builds/5085).  Solaris currently lacks `internal_sigdelset` (and some other non-Linux targets probably too).

**Comment by thevar1able** [comment]
With `clang-19` I'm getting `SIGPIPE` in asan build even after [blocking it in our code](https://github.com/ClickHouse/ClickHouse/blob/24.9/src/Daemon/BaseDaemon.cpp#L436), is this expected? Here is a [stacktrace](https://pastila.nl/?00597f1f/37056e1f39a449adc3b96122fb1cf602#Abcg5SnwOe3Q8EKQpe8dXQ==).

**Comment by vitalybuka** [comment]
According to the stack the signal is in parent thread, just at the point we try to block them.
We want to block signals in child thread before starting thread function.
Looks like working as intended.

**Comment by thevar1able** [comment]
Right.

**Comment by vitalybuka** [comment]
> @vitalybuka Right. I verified that removing [this line](https://github.com/llvm/llvm-project/pull/98200/files#diff-f740809540e5357d610d6a34715a57e3be96ccf85736f04a3092aa0a0728b2caR182) fixes the issue. Maybe we can make it conditional?

We should just update sigmask more carefully, we just somehow missed this.
@thurstond would you be able to work on this next week?

**Pull request merged**
