### PR TITLE
[libc] Add unistd overlay

### PR DESCRIPTION
**Pull request by RossComputerGuy**
Reverts the revert #119295 of #118882 by expanding #118882 with additional fixes which made CI unhappy.

### CODE REVIEW

**Review by michaelrj-google — COMMENTED** [review]
For the types, you should use the headers in `hdr/types/type_name.h` instead of `include/llvm-libc-types/type_name.h`. After that's fixed this looks fine to land.

**Comment by RossComputerGuy** [comment]
So just run a `git diff --name-only HEAD~1 | xargs -l grep "include/llvm-libc-types/" | xargs sed -i 's|include/llvm-libc-types/|hdr/types/|g'`?

**Comment by michaelrj-google** [comment]
that should update the `includes` but you should also update the cmake files.

**Comment by RossComputerGuy** [comment]
Oki, how does this look? I updated the CMake and changed those headers.

**Comment by RossComputerGuy** [comment]
Oh fun, it fails CI and I don't know why:
```
 CMake Error at /home/runner/work/llvm-project/llvm-project/libc/cmake/modules/LLVMLibCObjectRules.cmake:172 (message):
  An entrypoint alias should have exactly one dependency.
Call Stack (most recent call first):
  /home/runner/work/llvm-project/llvm-project/libc/cmake/modules/LLVMLibCFlagRules.cmake:158 (create_entrypoint_object)
  /home/runner/work/llvm-project/llvm-project/libc/cmake/modules/LLVMLibCFlagRules.cmake:158 (cmake_language)
  /home/runner/work/llvm-project/llvm-project/libc/cmake/modules/LLVMLibCFlagRules.cmake:251 (expand_flags_for_target)
  /home/runner/work/llvm-project/llvm-project/libc/cmake/modules/LLVMLibCObjectRules.cmake:393 (add_target_with_flags)
  /home/runner/work/llvm-project/llvm-project/libc/src/unistd/CMakeLists.txt:65 (add_entrypoint_object)
```
Are all the ones I updated aliases?

**Review by jhuber6 — APPROVED** [review]

**Review by michaelrj-google — APPROVED** [review]
This patch LGTM, to make sure the bazel build doesn't break could you apply this patch on top: https://github.com/llvm/llvm-project/pull/120127?

Link to the raw diff is here: https://github.com/llvm/llvm-project/pull/120127.diff

**Comment by RossComputerGuy** [comment]
I've applied the patch.

**Review by michaelrj-google — APPROVED** [review]
Perfect, thanks for working on this

**Pull request merged**
