### PR TITLE
[flang][OpenMP] Implement getOpenMPVersion helper function, NFC

### PR DESCRIPTION
**Pull request by kparzysz**

### CODE REVIEW

**Review by kiranchandramohan — APPROVED** [review]
LG.

**Review by tblah — APPROVED** [review]
nit: maybe instead of `llvm_unreachable`, we could return `std::nullopt` or some sentinel value. It would be unfortunate if we got into a situation where every mlir file in the test suite needed to have this attribute added to the module.

But it is hard to comment without seeing where this will be used so LGTM whether or not you decide to change.

**Review by tblah — APPROVED** [review]
Thanks!

**Review by skatrak — APPROVED** [review]
Thank you Krzysztof, I have just a small non-blocking comment.

**Pull request merged**
