### PR TITLE
[clang] Substitute alias templates from correct context

### LINKED ISSUE #41693: Invalid private member diagnostic of template using with decltype of private member method
|  |  |
| --- | --- |
| Bugzilla Link | [42348](https://llvm.org/bz42348) |
| Version | trunk |
| OS | All |
| Reporter | LLVM Bugzilla Contributor |
| CC | @DougGregor,@smilingthax,@zygoloid |

## Extended Description 
The following code fails to compile with an erroneous error "'Impl' is a private member of 'S<void>'":

```cpp
  template <typename> struct S
    {
    private:
    template <typename> static constexpr auto Impl();

    public:
    template <typename X> using U = decltype(Impl<X>());
    };

  template <typename T> template <typename>
  constexpr auto S<T>::Impl() { }

  using X = S<void>::U<void>;
```

The above code compiles in gcc et al.  Making the following change allows compilation:

```cpp
  template <typename> struct S
    {
    private:
    struct W
      {
      template <typename> static constexpr auto Impl();
      };

    public:
    template <typename X> using U = decltype(W::template Impl<X>());
    };

  template <typename T> template <typename>
  constexpr auto S<T>::W::Impl()
    { }
```

### PR DESCRIPTION
**Pull request by Fznamznon**
Current context set to where alias was met, not where it is declared caused incorrect access check in case alias referenced private members of the parent class.

Fixes https://github.com/llvm/llvm-project/issues/41693

### CODE REVIEW

**Review by erichkeane — APPROVED** [review]
I think this is on the right track, 1 nit, else is right I think.

**Review by erichkeane — APPROVED** [review]

**Comment by erichkeane** [comment]
> This started to give errors to code previously considere valid with "out-of-line definition of X differs from that in". Don't have a repro yet.

Please provide one as soon as you can! In the meantime, we should probably revert @Fznamznon

**Comment by Fznamznon** [comment]
> Please provide one as soon as you can! In the meantime, we should probably revert @Fznamznon

Ok, I'll prepare revert.

**Comment by Fznamznon** [comment]
Ok, revert is done.
@metaflow , please provide the reproducer.

**Comment by metaflow** [comment]
here is a sample for OSS ducc https://gitlab.mpcdf.mpg.de/mtr/ducc.git (lines might be off)
```
In file included from third_party/ducc/src/ducc0/fft/fftnd_impl.h:76:
third_party/ducc/src/ducc0/fft/fft1d_impl.h:1730:51: error: return type of out-of-line definition of 'ducc0::detail_fft::cfftpass::make_pass' differs from that in the declaration
 1730 | template<typename Tfs> Tcpass<Tfs> cfftpass<Tfs>::make_pass(size_t l1,
      |                        ~~~~~~~~~~~                ^
third_party/ducc/src/ducc0/fft/fft.h:205:33: note: previous declaration is here
  205 |     static shared_ptr<cfftpass> make_pass(size_t l1, size_t ido, size_t ip,
      |            ~~~~~~~~~~~~~~~~~~~~ ^
In file included from third_party/ducc/src/ducc0/fft/fftnd_impl.h:76:
third_party/ducc/src/ducc0/fft/fft1d_impl.h:2945:51: error: return type of out-of-line definition of 'ducc0::detail_fft::rfftpass::make_pass' differs from that in the declaration
 2945 | template<typename Tfs> Trpass<Tfs> rfftpass<Tfs>::make_pass(size_t l1,
      |                        ~~~~~~~~~~~                ^
third_party/ducc/src/ducc0/fft/fft.h:249:33: note: previous declaration is here
  249 |     static shared_ptr<rfftpass> make_pass(size_t l1, size_t ido, size_t ip,
      |            ~~~~~~~~~~~~~~~~~~~~ ^
```
sorry I don't have a smaller repro. It seems that "using" in the class body somehow messes things up.

**Comment by Fznamznon** [comment]
Thanks, I reproduced the problem with
```

template <typename T> class shared_ptr {
    T* data;
};

template <typename Tfs> class cfftpass {
    static shared_ptr<cfftpass> make_pass();
};

template<typename T> using Tcpass = shared_ptr<cfftpass<T>>;

template<typename Tfs> Tcpass<Tfs> cfftpass<Tfs>::make_pass() { return Tcpass<Tfs>{};};                                                                   
```

**Pull request merged**
