### PR TITLE
[sanitizer] Disallow external_symbolizer_path with AT_SECURE

### PR DESCRIPTION
**Pull request by fmayer**
See https://github.com/google/sanitizers/issues/1130.

### CODE REVIEW

**Comment by fmayer** [comment]
@bigb4ng FYI

**Comment by bigb4ng** [comment]
@fmayer Cool. Friendly reminders:
1.  `SANITIZER_GO` is currently not affected by this patch due to https://github.com/llvm/llvm-project/blob/e2db08f8f1a7dd37cd18705164f0c1188707e5b6/compiler-rt/lib/sanitizer_common/sanitizer_getauxval.h#L26
2. `log_path=stdout` and `log_path=stderr` for `AT_SECURE` are not supported in this version.

Trust your judgement on those. I will close #92593.

**Comment by fmayer** [comment]
> @fmayer Cool. Friendly reminders:
> 
> 1. `SANITIZER_GO` is currently not affected by this patch due to https://github.com/llvm/llvm-project/blob/e2db08f8f1a7dd37cd18705164f0c1188707e5b6/compiler-rt/lib/sanitizer_common/sanitizer_getauxval.h#L26
If ran on a system that has `getauxval`, it will also work for `SANITIZER_GO`, because of the weak declaration in the `#else`.

> 2. `log_path=stdout` and `log_path=stderr` for `AT_SECURE` are not supported in this version.
This is about external_symbolizer_path :)

> 
> Trust your judgement on those. I will close #92593.

Wait, this addresses a different option than #92593.  Please re-open your CL.

**Review by thurstond — APPROVED** [review]

**Comment by fmayer** [comment]
Seems like we don't want to implement this after all.

**Pull request closed without merging**
