### PR TITLE
[clang] Represent array refs as `TemplateArgument::Declaration`

### PR DESCRIPTION
**Pull request by bolshakov-a**
This returns (probably temporarily) array-referring NTTP behavior to which was prior to #78041 because ~~I'm fed up~~ have no time to fix regressions.

### CODE REVIEW

**Comment by bolshakov-a** [comment]
@erichkeane, @cor3ntin

**Review by erichkeane — COMMENTED** [review]
Are there any release-notes that should be reverted with this?  or at least modified, since this is reverting stuff?

Also, can you please add the tests/regressions that were found that have lead to this partial revert?

Also-- We hope you find more time to help with the regressions, your contributions so far have been really appreciated!

**Comment by cor3ntin** [comment]
@AaronBallman @zygoloid 
There probably is a missing ODR-use marking somewhere, if you have a clue
https://github.com/llvm/llvm-project/pull/78041#issuecomment-1917571069

Alas we do not seem to have a repro for the chromium-reported issue which make debugging it difficult.

**Comment by erichkeane** [comment]
> @AaronBallman @zygoloid There probably is a missing ODR-use marking somewhere, if you have a clue [#78041 (comment)](https://github.com/llvm/llvm-project/pull/78041#issuecomment-1917571069)
> 
> Alas we do not seem to have a repro for the chromium-reported issue which make debugging it difficult.

*SMH*

**Comment by bolshakov-a** [comment]
> Are there any release-notes that should be reverted with this? or at least modified, since this is reverting stuff?

No, it is intended only to fix potential bugs with already-written user's code (I suspect there are more places where `OVE->getSourceExpr()` should be checked, besides the last reported bug) without reverting the new NTTP feature (which may also contain bugs, but is marked as experimental). Just arrays are switched to the old mechanism.

> Also, can you please add the tests/regressions that were found that have lead to this partial revert?

I'd add the test if [the repro would be provided](https://github.com/llvm/llvm-project/pull/78041#issuecomment-1917800675). As far, I can revert the changes in code from #79764, and the tests from it would test this change.

> We hope you find more time to help with the regressions, your contributions so far have been really appreciated!

Thanks! Probably, on my vacation in summer...

> Alas we do not seem to have a repro for the chromium-reported issue which make debugging it difficult.

Do you mean [this](https://github.com/llvm/llvm-project/pull/78041#issuecomment-1914407300)? I've succeeded in reducing it to [that](https://github.com/llvm/llvm-project/pull/79764/files#diff-c33f69ce9875644ff3298c921a93e3e5b1916e897684ed97ba9e3f684415d688R357).

**Review by erichkeane — COMMENTED** [review]
I don't have concerns as written.  @cor3ntin : feel free to accept if you like it too.

**Comment by bolshakov-a** [comment]
The changes [under that discussion](https://github.com/llvm/llvm-project/pull/78041#discussion_r1459294440) could now be reverted as well because they are now useless. Should I make a separate commit inside this PR?

**Comment by jeremiahar** [comment]
This also avoids regressing https://github.com/llvm/llvm-project/issues/79957 (I cherrypicked this commit and compiled the test case locally)

**Comment by bolshakov-a** [comment]
@jeremiahar, thanks for reporting! Added a coverage mapping test case.

**Review by cor3ntin — APPROVED** [review]
I will accept that as it seems to unblock some folks, 
but I'd like to understand the root cause and what a proper fix would look like

**Comment by bolshakov-a** [comment]
I think the problem is that the generalized NTTP feature is still raw. It should not break already working features, namely array reference NTTPs, hence they are swithed back to the old `TemplateArgument::Declaration`, as they worked prior to #78041, from the new `StructuralValue`.

**Comment by bolshakov-a** [comment]
> what a proper fix would look like

Probably, some more `OpaqueValueExpr` handlers should be rewritten correctly.

**Comment by bolshakov-a** [comment]
@cor3ntin, @erichkeane, could you merge it please?

**Comment by bolshakov-a** [comment]
Thanks! Should I open an issue to backport this to RC?

**Comment by erichkeane** [comment]
> Thanks! Should I open an issue to backport this to RC?

Please do!

**Comment by bolshakov-a** [comment]
> Please do!

#80150. I don't know, maybe, some more actions should be done. I cannot add "release:backport" label, at least.

**Comment by erichkeane** [comment]
> > Please do!
> 
> #80150. I don't know, maybe, some more actions should be done. I cannot add "release:backport" label, at least.

I think you just have to set hte milestone, which I did.

**Pull request merged**
