### PR TITLE
[RISCV] Model vd as a src for some Zvk* instructions in MC layer.

### PR DESCRIPTION
**Pull request by topperc**
Some Zvk instructions use vd as a source regardless of tail policy. Model this in the MC layer. We already do this for FMA for example.

### CODE REVIEW

**Review by 4vtomat — APPROVED** [review]
LGTM, thanks!

**Comment by michaelmaitland** [comment]
Are you planning on doing this on the MI level too?

**Comment by topperc** [comment]
> Are you planning on doing this on the Pseudo MI level too?

I already did 8551454313233ecc70a329de0eb0064ecb675d50

**Review by michaelmaitland — APPROVED** [review]
I missed that. LGTM

**Pull request merged**
