### PR TITLE
Update GitHub doc to mention that we accepts user branches for Stacked PRs

### PR DESCRIPTION
**Pull request by joker-eph**
This isn't yet a guide on how to do stacked PRs.

### CODE REVIEW

**Review by tstellar — COMMENTED** [review]
Is there a local config we can use to tell git not to pull these branches?  If so, it might be good to document that.

**Review by vitalybuka — APPROVED** [review]
I assume we going to have SPR setup somewhere.

Looks like everyone I asked to try SPR failed to realize
that branch destination is main repo and branchPrefix must be specific.


```
[spr]
	githubRemoteName = origin
	githubRepository = llvm/llvm-project
	githubMasterBranch = main
	branchPrefix = users/vitalybuka/spr/
	requireTestPlan = false
```

**Comment by joker-eph** [comment]
> I assume we going to have SPR setup somewhere.

Yes, that would be a separate doc in my mind.

> Is there a local config we can use to tell git not to pull these branches? If so, it might be good to document that.

This is the "refspec": https://git-scm.com/book/en/v2/Git-Internals-The-Refspec

I spent quite some time on it today, but I can't find a command to specify it...  You can add one during clone, but `	fetch = +refs/heads/*:refs/remotes/origin/*` will always come by default and needs to be removed and replaced by `	fetch = +refs/heads/main:refs/remotes/origin/main` 

I added a `sed` in the getting started, WDYT?

**Comment by joker-eph** [comment]
@tstellar wanna double check?

**Review by tstellar — APPROVED** [review]
Looks good, thanks.

**Pull request merged**
