### PR TITLE
[libc][NFC] Rename LIBC_COMPILER_HAS_FLOAT128 to LIBC_HAS_FLOAT128 for consistency

### PR DESCRIPTION
**Pull request by gchatelet**

### CODE REVIEW

**Review by lntue — APPROVED** [review]

**Review by nickdesaulniers — CHANGES_REQUESTED** [review]
> for consistency

Consistency with what?

It looks like we use `LIBC_COMPILER_HAS_*` for:
1. `FLOAT128`
2. `C23_FLOAT16`
3. `FLOAT128_EXTENSION`
4. `C23_FLOAT128`

I can appreciate making the macro name more concise, but:
1. Let's modify all of the above, not just `FLOAT128`
2. Keep `CC` in the macro name `LIBC_CC_HAS_*`
3. Maybe document the convention somewhere. Do we have a coding style doc?

**Comment by nickdesaulniers** [comment]
Looking at `LIBC_HAS_FLOAT16` what's going on with that? It's defined but not referenced anywhere AFAICT.

**Comment by gchatelet** [comment]
> It looks like we use `LIBC_COMPILER_HAS_*` for:
> 
> 1. `FLOAT128`
> 2. `C23_FLOAT16`
> 3. `FLOAT128_EXTENSION`
> 4. `HAS_FLOAT128`
> 
> I can appreciate making the macro name more concise, but:

It was not so much for conciseness as consistency. 

We do have a [coding style for macros](https://libc.llvm.org/dev/code_style.html#macro-style) but it is not _quite_ consistent (hence this fix). Basically the naming should reflect where it is defined:
 - `compiler.h` -> `LIBC_COMPILER_IS_`, `LIBC_COMPILER_HAS_`
 - `architectures.h` -> `LIBC_TARGET_ARCH_IS_`
 - `cpu_features.h` -> `LIBC_TARGET_CPU_IS_`

You get the idea.

The `LIBC_COMPILER_HAS_` macros are about the compiler supporting _something non standard_.
In that regard the following ones are correct:
 - `LIBC_COMPILER_HAS_C23_FLOAT16`
 - `LIBC_COMPILER_HAS_C23_FLOAT128`
 - `LIBC_COMPILER_HAS_FLOAT128_EXTENSION`

But `float128` can also come from C++ native types when `long double` is an implementation of IEEE754 binary 128 (aarch64, riscv, IBM POWER, ...). In that sense it's not really a property of the compiler, it happens to be there.

That's why I felt like being able to use `float128` was a global property of the libc (not necessarily tied to the compiler) -> `LIBC_HAS_FLOAT128`.

This probably sounds like nitpicking 😅 but FTR macros in the libc used to be kind of wildly defined and I've already spent a bit of time trying to make them more consistent ([thread](https://discourse.llvm.org/t/rfc-llvm-libc-tuning/67980)). That said, I'm happy to take any suggestions to improve the naming convention or documentation as it surely is far from perfect. Let me know!

**Comment by gchatelet** [comment]
> Looking at `LIBC_HAS_FLOAT16` what's going on with that? It's defined but not referenced anywhere AFAICT.

It was a request from @lntue so he can start implementing math functions for half floats. Indeed not used but he has planned to work on it in the short term.

**Comment by nickdesaulniers** [comment]
> We do have a [coding style for macros](https://libc.llvm.org/dev/code_style.html#macro-style) but it is not quite consistent (hence this fix). Basically the naming should reflect where it is defined:

Cool, and I see in this change that you update the docs.  I guess after the update we still don't document `LIBC_COMPILER_HAS_C23_FLOAT16`, or `LIBC_COMPILER_HAS_C23_FLOAT128`.  I feel like before this change, `LIBC_COMPILER_HAS_FLOAT128` is consistent with those (but not `LIBC_HAS_FLOAT16`). After this change `LIBC_HAS_FLOAT128` is consistent with `LIBC_HAS_FLOAT16` (but now no longer with `LIBC_COMPILER_HAS_C23_FLOAT16`). So something still feels off for me.  If the distinction is intentional, looking at https://libc.llvm.org/dev/code_style.html#macro-style I still think we're missing documentation for the distinction; or we need to additionally change `LIBC_COMPILER_HAS_C23_FLOAT16`, or `LIBC_COMPILER_HAS_C23_FLOAT128` (and `LIBC_COMPILER_HAS_FLOAT128_EXTENSION`) in the same fashion as this PR to be entirely consistent.  Otherwise I guess my hangup with this PR is that to me it looks like trading consistency with one set of macros for consistency with a different set, without making both sets consistent as one set.

> The LIBC_COMPILER_HAS_ macros are about the compiler supporting something non standard.
In that regard the following ones are correct:
> LIBC_COMPILER_HAS_C23_FLOAT16
> LIBC_COMPILER_HAS_C23_FLOAT128

But those were standardized, in C23. `LIBC_COMPILER_HAS_FLOAT128_EXTENSION` is the only thing that appears non-standard to me.

**Comment by gchatelet** [comment]
> But those were standardized, in C23. `LIBC_COMPILER_HAS_FLOAT128_EXTENSION` is the only thing that appears non-standard to me.

Fair enough. On second thought it's probably not a great idea to distinguish based on "non-standard" features. A compiler extension may be standardized eventually so this can rot over time.

Given what I explained earlier based on the support for types coming from different places, I envision the following modifications:
 - Rename `float.h` into `types.h`
 - Rename all `#define` in this file to `LIBC_TYPES_HAS_...`
   - `LIBC_TYPES_HAS_INT64`
   - `LIBC_TYPES_HAS_FLOAT16`
   - `LIBC_TYPES_HAS_FLOAT128`
 - Don't expose how the type is provided and use `float16` or `float128` solely (i.e. no `LIBC_COMPILER_HAS_FLOAT128_EXTENSION` nor `LIBC_COMPILER_HAS_C23_FLOAT128`). Added benefit of not defining `LIBC_COMPILER_...` outside of the `compiler.h` file.
 - Update the documentation

I'll wait for your input before moving forward with this.

**Comment by nickdesaulniers** [comment]
ok, that SGTM.  So then in this PR do you plan to s/LIBC_HAS_FLOAT128/LIBC_TYPES_HAS_FLOAT128/ or a follow up PR?

If a follow up, please put [your thoughts](https://github.com/llvm/llvm-project/pull/81870#issuecomment-1948099726) into an issue and link to it for now until the conversions you listed are complete.

**Comment by gchatelet** [comment]
I'm dropping this PR and starting anew from #83182.

**Pull request closed without merging**
