### PR TITLE
[clang][DebugInfo] Don't mark structured bindings as artificial

### LINKED ISSUE #48909: DW_AT_artificial for structured bindings is incorrectly set
|  |  |
| --- | --- |
| Bugzilla Link | [49565](https://llvm.org/bz49565) |
| Version | trunk |
| OS | Linux |
| Attachments | [Test case](https://user-images.githubusercontent.com/60944935/143761896-ffd25b9a-11e8-4f33-be1d-e13e4a4b03f9.gz) |
| Reporter | LLVM Bugzilla Contributor |
| CC | @dwblaikie,@pogo59,@zygoloid |

## Extended Description 

With structured bindings:
```cpp
  auto [test_i, test_s] = GetTest();
```
Clang generates three variables in the DWARF symbols, one unnamed one for the std::pair returned from GetTest(), and then test_i and test_s. But test_i and test_s are marked as DW_AT_artifical even though they were user-declared, and the unnamed one is *not*, even though it was not user-declared:
```
0x000048c6:     DW_TAG_variable
                  DW_AT_location	(DW_OP_fbreg -40)
                  DW_AT_decl_file	("/home/brettw/eraseme3.cc")
                  DW_AT_decl_line	(13)
                  DW_AT_type	(0x00002b98 "pair<int, std::__2::basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>>")

0x000048d0:     DW_TAG_variable
                  DW_AT_location	(DW_OP_fbreg -48)
                  DW_AT_name	("test_i")
                  DW_AT_type	(0x0000484a "int&&")
                  DW_AT_artificial	(true)

0x000048dc:     DW_TAG_variable
                  DW_AT_location	(DW_OP_fbreg -56)
                  DW_AT_name	("test_s")
                  DW_AT_type	(0x000030db "basic_string<char, std::__2::char_traits<char>, std::__2::allocator<char>>&&")
                  DW_AT_artificial	(true)
```
This is backwards. The unnamed pair should be marked "artificial" while the two named variables in the structured bindings should not.

GCC encodes the artificial tags in way I propose:
```
0x00005ed0:     DW_TAG_variable
                  DW_AT_type	(0x00003316 "pair<int, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > >")
                  DW_AT_artificial	(true)
                  DW_AT_location	(DW_OP_fbreg -96)

0x00005ed9:     DW_TAG_variable
                  DW_AT_name	("test_i")
                  DW_AT_decl_file	("/home/brettw/eraseme3.cc")
                  DW_AT_decl_line	(13)
                  DW_AT_decl_column	(0x09)
                  DW_AT_type	(0x00005ef8 "type&&")
                  DW_AT_location	(DW_OP_fbreg -40)

0x00005ee8:     DW_TAG_variable
                  DW_AT_name	("test_s")
                  DW_AT_decl_file	("/home/brettw/eraseme3.cc")
                  DW_AT_decl_line	(13)
                  DW_AT_decl_column	(0x11)
                  DW_AT_type	(0x00005efe "type&&")
                  DW_AT_location	(DW_OP_fbreg -48)
```
Fuchsia clang version 11.0.0 (https://fuchsia.googlesource.com/a/third_party/llvm-project 65f58878e72a40d68ef3899c766846ee9ec7cf29)

### PR DESCRIPTION
**Pull request by Michael137**
This patch is motivated by the debug-info issue in https://github.com/llvm/llvm-project/issues/48909. Clang is currently emitting the `DW_AT_artificial` attribute on debug-info entries for structured bindings whereas GCC does not. GCC's interpretation of the DWARF spec is more user-friendly in this regard, so we would like to do the same in Clang. [`CGDebugInfo` uses `isImplicit` to decide which variables to mark artificial](https://github.com/llvm/llvm-project/blob/0c4023ae3b64c54ff51947e9776aee0e963c5635/clang/lib/CodeGen/CGDebugInfo.cpp#L4783-L4784) (e.g., `ImplicitParamDecls`, compiler-generated variables, etc.). But for the purposes of debug-info, when we say "artificial", what we really mean in many cases is: "not explicitly spelled out in source". `VarDecl`s that back tuple-like bindings are [technically compiler-generated](https://github.com/llvm/llvm-project/issues/48909#issuecomment-2238976579), but that is a confusing notion for debug-info, since these bindings *are* spelled out in source. The [documentation for `isImplicit`](https://github.com/llvm/llvm-project/blob/68a0d0c76223736351fd7c452bca3ba9d80ca342/clang/include/clang/AST/DeclBase.h#L596-L600) does to some extent imply that implicit variables aren't written in source.

This patch adds another condition to deciding whether a `VarDecl` should be marked artificial. Specifically, don't treat structured bindings as artificial.

**Main alternatives considered**
1. Don't use `isImplicit` in `CGDebugInfo` when determining whether to add `DW_AT_artificial`. Instead use some other property of the AST that would tell us whether a node was explicitly spelled out in source or not
  * Considered using `SourceRange` or `SourceLocation` to tell us this, but didn't find a good way to, e.g., correctly identify that the implicit `this` parameter wasn't spelled out in source (as opposed to an unnamed parameter in a function declaration)
2. We could've also added a bit to `VarDeclBitFields` that indicates that a `VarDecl` is a holding var, but the use-case didn't feel like good enough justification for this
3. Don't set the `VarDecl` introduced as part of a tuple-like decomposition as implicit.
  * This may affect AST matching/traversal and this specific use-case wasn't enough to justify such a change

Fixes https://github.com/llvm/llvm-project/issues/48909

### CODE REVIEW

**Comment by cor3ntin** [comment]
Thanks for the patch!

I would actually prefer option 2 here.

`isImplicit` has other uses - namely for AST matchers and refactoring tools that also rely on knowing whether something was spelled in source.

Note that I cannot comment on what make sense for debugs info, but I don't think modifying properties of the AST is reasonable, and your suggested option 2 is fine. 

The structure of the AST is not stable but whoever change is would have to fix the code anyway as it's all the same project so it's a non-issue (as long as you add sufficient test coverage)

**Comment by AaronBallman** [comment]
CC @zygoloid for design opinions.

This holding variable is really weird in that it's both not spelled in source (the user doesn't give it a name) but is spelled in source (only exists because of a source construct). I think that makes it hard to know whether it should or should not be marked as implicit.

**Comment by shafik** [comment]
> The structure of the AST is not stable but whoever change is would have to fix the code anyway as it's all the same project so it's a non-issue (as long as you add sufficient test coverage)

I agree relying on the AST is fine w/ sufficient testing.

**Comment by Michael137** [comment]
> Thanks for the patch!
> 
> I would actually prefer option 2 here.
> 
> `isImplicit` has other uses - namely for AST matchers and refactoring tools that also rely on knowing whether something was spelled in source.
> 
> Note that I cannot comment on what make sense for debugs info, but I don't think modifying properties of the AST is reasonable, and your suggested option 2 is fine.
> 
> The structure of the AST is not stable but whoever change is would have to fix the code anyway as it's all the same project so it's a non-issue (as long as you add sufficient test coverage)

Thanks all for the input! Happy to go with option 2 instead. I agree that changing the AST here just for `DW_AT_artificial` emission does feel a bit drastic/is not obviously the right thing to do.

**Comment by Michael137** [comment]
Updated the PR and description with the alternative approach

**Comment by zygoloid** [comment]
It looks like this is working for all other kinds of structured binding because `EmitDeclare(BindingDecl*, ...)` emits a proper `DILocalVariable` for them. But it skips `BindingDecl`s that have a holding variable for some reason. Perhaps a cleaner approach would be to make it handle that case too, and leave the holding variables themselves as artificial?

**Comment by Michael137** [comment]
> It looks like this is working for all other kinds of structured binding because `EmitDeclare(BindingDecl*, ...)` emits a proper `DILocalVariable` for them. But it skips `BindingDecl`s that have a holding variable for some reason. Perhaps a cleaner approach would be to make it handle that case too, and leave the holding variables themselves as artificial?

Yea that would be ideal. I was thinking of doing this, but wasn't quite sure how to best re-architect the codegen for structured bindings to make this happen.

We currently emit debug-info for structured bindings in 2 steps. The [`DecompositionDecl` itself gets codegen'd first](https://github.com/llvm/llvm-project/blob/c6e69b041a7e6d18463f6cf684b10fd46a62c496/clang/lib/CodeGen/CGDecl.cpp#L165). Which is what calls into `CGDebugInfo::EmitDeclare(BindingDecl*, ...)`. This creates a debug-info entry for the unnamed decomposition pair. But then [`CodeGenFunction::EmitDecl` calls `EmitVarDecl` for each holding var](https://github.com/llvm/llvm-project/blob/c6e69b041a7e6d18463f6cf684b10fd46a62c496/clang/lib/CodeGen/CGDecl.cpp#L169). This then goes through various layers of codegen until we hit `CGDebugInfo::EmitDeclare(VarDecl*,...)`. Hence we bail out early in the case of tuple-like bindings in step 1, and defer to `CGDebugInfo::EmitDeclare(VarDecl*)` to emit debug-info for each individual holding var.

So at some point in the code-gen process we need to bail out early in the case of structured bindings. AFAICT we have two options:
1. Detect the fact that we're dealing with holding vars [before calling `CGDebugInfo::EmitDeclare(VarDecl*)` ](https://github.com/llvm/llvm-project/blob/c6e69b041a7e6d18463f6cf684b10fd46a62c496/clang/lib/CodeGen/CGDecl.cpp#L1680-L1682). And just emit all the debug-info for a decomposition in `CGDebugInfo::EmitDeclare(BindingDecl*, ...)`
2. OR, detect that we're emitting holding vars in `CGDebugInfo::EmitDeclare(BindingDecl*, ...)`, and emit the debug-info for them in `CGDebugInfo::EmitDeclare(VarDecl*, ...)`. Which is what the current patch is doing.

Any preferences here? Or maybe I'm missing a better approach

**Comment by Michael137** [comment]
ping

**Review by adrian-prantl — APPROVED** [review]
So this patch makes structured bindings not artificial, so they aren't hidden in debuggers by default. That sounds right to me.

**Pull request merged**
