### PR TITLE
[mlir][MemRef] Add a pattern to simplify `extract_strided_metadata(ca…

### PR DESCRIPTION
**Pull request by qcolombet**
…st)`

`expand-strided-metadata` was missing a pattern to get rid of `memref.cast`.
The pattern is straight foward:
Produce a new `extract_strided_metadata` with the source of the cast and fold the static information (sizes, strides, offset) along the way.

### CODE REVIEW

**Comment by qcolombet** [comment]
This fixes https://github.com/openxla/iree/issues/15076

**Comment by Groverkss** [comment]
Can you add a test from constant strides to dynamic strides?

**Comment by qcolombet** [comment]
@Groverkss 
> Can you please add a test that casts constant strides to dynamic strides?

Sure, I've modified `@extract_strided_metadata_of_cast` to cover that.
Let me know if you prefer to keep `@extract_strided_metadata_of_cast` how it was and have a different test. I don't think that's necessary but I don't have a strong opinion here.

**Comment by Groverkss** [comment]
> Let me know if you prefer to keep @extract_strided_metadata_of_cast

No, this is great! Thank you :)

LGTM

**Review by Groverkss — APPROVED** [review]

**Pull request merged**
