### PR TITLE
[libc++] Make a few test helper constructors explicit

### PR DESCRIPTION
**Pull request by ldionne**

### CODE REVIEW

**Comment by ldionne** [comment]
CC @winner245

**Review by winner245 — APPROVED** [review]
LGTM upon CI green.

**Comment by winner245** [comment]
Is the lldb test in stage3 (bootstrapping-build) broken? The failed tests seem completely unrelated to this PR (they also failed in my PR):

  Failed Tests (15):
    lldb-api :: commands/expression/import-std-module/basic/TestImportStdModule.py
    lldb-api :: commands/expression/import-std-module/conflicts/TestStdModuleWithConflicts.py
    lldb-api :: commands/expression/import-std-module/deque-basic/TestDequeFromStdModule.py
    lldb-api :: commands/expression/import-std-module/deque-dbg-info-content/TestDbgInfoContentDequeFromStdModule.py
    lldb-api :: commands/expression/import-std-module/forward_list-dbg-info-content/TestDbgInfoContentForwardListFromStdModule.py
    lldb-api :: commands/expression/import-std-module/forward_list/TestForwardListFromStdModule.py
    lldb-api :: commands/expression/import-std-module/iterator/TestIteratorFromStdModule.py
    lldb-api :: commands/expression/import-std-module/list-dbg-info-content/TestDbgInfoContentListFromStdModule.py
    lldb-api :: commands/expression/import-std-module/list/TestListFromStdModule.py
    lldb-api :: commands/expression/import-std-module/non-module-type-separation/TestNonModuleTypeSeparation.py
    lldb-api :: commands/expression/import-std-module/retry-with-std-module/TestRetryWithStdModule.py
    lldb-api :: commands/expression/import-std-module/shared_ptr-dbg-info-content/TestSharedPtrDbgInfoContentFromStdModule.py
    lldb-api :: commands/expression/import-std-module/shared_ptr/TestSharedPtrFromStdModule.py
    lldb-api :: commands/expression/import-std-module/weak_ptr-dbg-info-content/TestDbgInfoContentWeakPtrFromStdModule.py
    lldb-api :: commands/expression/import-std-module/weak_ptr/TestWeakPtrFromStdModule.py

**Comment by ldionne** [comment]
Looks like this was broken recently in the bootstrapping build. This is probably caused by a clang change. I'll investigate separately.

In the meantime I think we can consider the CI to be green.

**Pull request merged**
