### PR TITLE
[SLP][REVEC] Fix false assumption of the source for castToScalarTyElem.

### PR DESCRIPTION
**Pull request by HanKuanChen**
The argument V may come from adjustExtracts, which is the vector operand of ExtractElementInst. In addition, it is not existed in getTreeEntry.

The vector operand of ExtractElementInst may have a type of <1 x Ty>, ensuring that the number of elements in ScalarTy and VecTy are equal.

reference: https://github.com/llvm/llvm-project/issues/99411

### CODE REVIEW

**Comment by dyung** [comment]
Should we add either or both of the crashing examples as tests?

**Review by alexey-bataev — APPROVED** [review]
LG

**Comment by dyung** [comment]
@HanKuanChen the test you added is failing on at least one buildbot, see the message above (I happen to manage that build bot). Can you take a look so that I don't have to revert your change?

**Comment by amykhuang** [comment]
looks good for me, aside from the test issue

**Pull request merged**
