### PR TITLE
[AArch64] Sink llvm.vscale.i32 into blocks for better isel

### PR DESCRIPTION
**Pull request by LittleMeepo**
Sink vscale calls as well when indvars is not widen (-indvars-widen-indvars=false).

### CODE REVIEW

**Comment by LittleMeepo** [comment]
@huntergr-arm

**Comment by LittleMeepo** [comment]
@paulwalker-arm

**Comment by paulwalker-arm** [comment]
The patch looks reasonable but before accepting I would like to query why it's needed.  I would expect functions to be decorated with a vscale_range attribute (clang adds `vscale_range(1,16)` when targeting SVE) which allows instcombine to remove the zero-extend and just emit a call to vscale.i64.

**Comment by LittleMeepo** [comment]
> The patch looks reasonable but before accepting I would like to query why it's needed. I would expect functions to be decorated with a vscale_range attribute (clang adds `vscale_range(1,16)` when targeting SVE) which allows instcombine to remove the zero-extend and just emit a call to vscale.i64.

Sometimes the return value of llvm.vscale will have multiple users, and I'm not sure whether it's appropriate to implement it in instcombine. I found that when adding `-indvars-widen-indvars=false`, inc* was not generated,  so add a new pattern matching scene.

**Review by paulwalker-arm — APPROVED** [review]
Thank you for the explanation.

**Pull request merged**
