### PR TITLE
[NFC][offload][OMPT] Cleanup of OMPT internals

### PR DESCRIPTION
**Pull request by mhalk**
Removed `OmptCallbacks.cpp` since relevant contents were duplicated.
Because of the static linking there should be no change in functionality.

### CODE REVIEW

**Review by jhuber6 — APPROVED** [review]
Cool, nice to see this stuff moved out of the plugins now that they're not separate programs.

**Review by jplehr — APPROVED** [review]
LG.
Gave it a quick run through a buildbot recreation w/o issues.

**Review by dhruvachak — APPROVED** [review]
LGTM

**Comment by mhalk** [comment]
Thanks for taking the time to review!

**Pull request merged**
