### PR TITLE
[PM] Execute IndVarSimplifyPass precede RessociatePass

### PR DESCRIPTION
**Pull request by erickq**
ReassociatePass may clear nsw/nuw flags of some instructions, which may have side effects on optimizations in IndVarSimplifyPass.

### CODE REVIEW

**Comment by dtcxzyw** [comment]
Please add some regression tests.

**Comment by topperc** [comment]
Aren't there tests for pass pipeline order that should be affected by this change?

**Comment by erickq** [comment]
> Please add some regression tests.

Thank you. The test cases have been updated. @dtcxzyw @topperc

**Comment by fhahn** [comment]
Could you add some performance data backing up the benefits of the change? Adding additional runs of IndVars likely also impacts compile time which needs to be evaluated also.

**Review by nikic — CHANGES_REQUESTED** [review]
Compile-time: http://llvm-compile-time-tracker.com/compare.php?from=060de415af335fdd82910f409e2be3b8457eaa43&to=eef3483993253cda242f9798f6118b8539e81b62&stat=instructions:u

**Comment by erickq** [comment]
> Could you add some performance data backing up the benefits of the change? Adding additional runs of IndVars likely also impacts compile time which needs to be evaluated also.

Are you referring to the SPEC performance change? I may not be able to get it because I don't have a sve machine.

**Pull request merged**
