### PR TITLE
[clang-tidy] [docs] Replace  _not_ in reserved-identifier.rst with *not*

### LINKED ISSUE #111691: Documentation formatting error
https://github.com/llvm/llvm-project/blame/665457815f11118f7e755a471f33606c8562a4be/clang-tools-extra/docs/clang-tidy/checks/bugprone/reserved-identifier.rst#L31 used `_not_`.

As per https://docutils.sourceforge.io/docs/user/rst/quickref.html#inline-markup, it probably should be `*not*`.

### PR DESCRIPTION
**Pull request by njriasan**
Fixes a documentation formatting error where `_not_` was used which has no special meaning in markdown and replaces it with `*not*`.

Closes #111691

### CODE REVIEW

**Review by carlosgalvezp — APPROVED** [review]

**Comment by carlosgalvezp** [comment]
@njriasan Thanks for the contribution! I see the commit message would include this:

```
Co-authored-by: Nicholas Riasanovsky <nicholasriasanovsky@macbook-pro.myfiosgateway.com>
```

Do you want to keep that?

**Comment by njriasan** [comment]
> @njriasan Thanks for the contribution! I see the commit message would include this:
> 
> ```
> Co-authored-by: Nicholas Riasanovsky <nicholasriasanovsky@macbook-pro.myfiosgateway.com>
> ```
> 
> Do you want to keep that?

@carlosgalvezp That message is because I got a new computer and it wasn't properly setup yet. I would like to remove it if possible. What is the process for updating a commit message in this repo? Should I just force push a modified message to this branch?

**Comment by carlosgalvezp** [comment]
> @carlosgalvezp That message is because I got a new computer and it wasn't properly setup yet. I would like to remove it if possible. What is the process for updating a commit message in this repo? Should I just force push a modified message to this branch?

I'm not 100% sure but please do try a force-push to change the commit message. Otherwise I can remove it for you before merging.

**Comment by njriasan** [comment]
@carlosgalvezp I think the force push fixed it. Could you confirm that you no longer see the second author? Thanks.

**Comment by nicovank** [comment]
Rebase past 3484ed9325f30b56717a1b939af4c58dd07848e0 for green CI.

**Pull request merged**
