### PR TITLE
[clang][Sema] Use original template pattern when declaring implicit deduction guides for nested template classes

### LINKED ISSUE #46200: CTAD fails on nested templated class
|  |  |
| --- | --- |
| Bugzilla Link | [46856](https://llvm.org/bz46856) |
| Version | 10.0 |
| OS | Linux |
| CC | @zygoloid |

## Extended Description 
The following snippet doesn't compile on clang (10), due to CTAD failing. It occurs when the parent class is templated:

```cpp
template <class U>
struct X {	
	template <class T> struct Y {
		T y;
		Y(T t) : y(t) {}		
	};
	auto test() const {
		return Y(10);
	}
};

auto test() {
    return X<int>().test();
}
```

The snippet compiles on msvc and gcc:
https://godbolt.org/z/Wq6Paf

### LINKED ISSUE #57812: Nested CTAD fails with "could not match 'inner_foo<T2>' against 'int'"
CTAD on this example:

```C++
template <class T1>
struct outer_foo {
  template <class T2>
  struct inner_foo {
    inner_foo(const T2& t);
  };
};

void f() {
  auto X = outer_foo<int>::inner_foo(1);
}
```
fails with 
```console
<source>:10:12: error: no viable constructor or deduction guide for deduction of template arguments of 'inner_foo'
  auto X = outer_foo<int>::inner_foo(1);
           ^
<source>:4:10: note: candidate template ignored: could not match 'inner_foo<T2>' against 'int'
  struct inner_foo {
         ^
<source>:4:10: note: candidate function template not viable: requires 0 arguments, but 1 was provided
1 error generated.
Compiler returned: 1
```

https://godbolt.org/z/Ea9j6GxdP

### PR DESCRIPTION
**Pull request by antangelo**
When a nested template is instantiated, the template pattern of the inner class is not copied into the outer class ClassTemplateSpecializationDecl. The specialization contains a ClassTemplateDecl with an empty record that points to the original template pattern instead.

As a result, when looking up the constructors of the inner class, no results are returned. This patch finds the original template pattern and uses that for the lookup instead.

Based on CWG2471 we must also substitute the known outer template arguments when creating deduction guides for the inner class.

Fixes #46200
Fixes #57812

### CODE REVIEW

**Review by erichkeane — COMMENTED** [review]
This seems reasonable, however it needs a release note.

**Comment by antangelo** [comment]
> This seems reasonable, however it needs a release note.

Thanks for the review! I've added a release note to the C++ bugfix section

**Comment by antangelo** [comment]
Friendly ping

**Review by erichkeane — APPROVED** [review]

**Review by erichkeane — APPROVED** [review]

**Comment by ilovepi** [comment]
I think we may be seeing some issues with this patch, when building Fuchsia.

We're seeing the following error.

```
FAILED: host_x64/obj/sdk/lib/ld/test/ld-unittests.filter-view-tests.cc.o
../../prebuilt/third_party/clang/custom/bin/clang++ -MD -MF host_x64/obj/sdk/lib/ld/test/ld-unittests.filter-view-tests.cc.o.d -DFUCHSIA_API_LEVEL=15 -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES -I../.. -Ihost_x64/gen -I../../sdk/lib/ld/include -I../../sdk/lib/stdcompat/include -I../../zircon/system/public -I../../src/lib/elfldltl/include -I../../zircon/system/u...
In file included from ../../sdk/lib/ld/test/filter-view-tests.cc:6:
../../sdk/lib/ld/include/lib/ld/internal/filter-view.h:51:27: error: no member 'filter_iterator' in 'ld::internal::filter_view<std::array<int, 6>, (lambda at ../../sdk/lib/ld/test/filter-view-tests.cc:20:48)>'; it has not yet been instantiated
   51 |     filter_iterator(const filter_iterator&) = default;
      |                           ^
note: while building implicit deduction guide first needed here
../../sdk/lib/ld/test/filter-view-tests.cc:20:31: note: in instantiation of template class 'ld::internal::filter_view<std::array<int, 6>, (lambda at ../../sdk/lib/ld/test/filter-view-tests.cc:20:48)>' requested here
   20 |     ld::internal::filter_view filter_view(arr, [](auto) { return true; });
      |                               ^
../../sdk/lib/ld/include/lib/ld/internal/filter-view.h:40:9: note: not-yet-instantiated member is declared here
   40 |   class filter_iterator : public std::iterator_traits<Iter> {
      |         ^
1 error generated.
```

But the code in question is defining a constructor for the nested class. You can find the code here: https://cs.opensource.google/fuchsia/fuchsia/+/main:sdk/lib/ld/include/lib/ld/internal/filter-view.h;l=51?q=filter_iterator&ss=fuchsia%2Ffuchsia

We're tracking this in https://bugs.fuchsia.dev/p/fuchsia/issues/detail?id=135353

Do you have any idea why it would be flagging this case. I don't see any obvious C++ rules being violated, so I think this is rather surprising.

I've included a reproducer, but I haven't had a chance to reduce it yet, so it's likely to be quite large.
[filter-view.zip](https://github.com/llvm/llvm-project/files/12923104/filter-view.zip)

**Comment by antangelo** [comment]
I've come up with this minimal reproducer:

```cpp
template<class A>
struct outer {
    template<class B>
    struct inner {
        inner(B b);
        inner(const inner &x) = default;
    };

    template<class B>
    inner(B b) -> inner<B>;
};

outer<int>::inner i(1);
```

The error seems to be triggered by the inclusion of both the copy constructor and the explicit deduction guide. I'll revert the patch now until I can come up with a proper fix for it.

**Comment by antangelo** [comment]
When `SubstType` is called on the `const inner &` parameter to substitute the outer template args, it eventually calls `FindInstantiatedDecl` on the inner template pattern. The presence of the explicit deduction guide causes the outer template to already be instantiated at this point.

As a result `FindInstantiatedDecl` attempts to look for the inner template within the instantiated outer template. This fails because the inner template args are not known (so the inner template cannot have been instantiated at this point).

I think that in this case, if the decl passed into `FindInstantiatedDecl` is a `CXXRecordDecl` with a described template, and its context is dependent at the given template arguments' level, `FindInstantiatedDecl` should return the template pattern. Does that make sense, or is it off the mark?

**Comment by ilovepi** [comment]
I think your analysis and approach sounds correct, but probably worth checking with someone a bit more familiar with all of the C++ nuance here.

**Comment by antangelo** [comment]
I've posted a candidate reland of this PR at #69676 .

**Pull request merged**
