### PR TITLE
[MLIR][Python] Fix detached operation coming from `IfOp` constructor

### PR DESCRIPTION
**Pull request by matth2k**
Without this fix, `scf.if` operations would be created without a parent. Since `scf.if` operations often have no results, this caused silent bugs where the generated code was straight-up missing the operation.

### CODE REVIEW

**Comment by joker-eph** [comment]
Thanks for the contribution! Is this possible to add a test for this?

**Comment by matth2k** [comment]
> Thanks for the contribution! Is this possible to add a test for this?

Just added one. Let's see if it passes CI.

**Comment by makslevental** [comment]
> Thanks for the contribution! Is this possible to add a test for this?

Only way I can think of is to dump the module with debug info inlined and then `# CHECK` but it's very brittle obv (will have to be updated when `import`s change or function body gets shifted.

**Comment by makslevental** [comment]
Oh whoops didn't notice `ip` was being added/tested.

**Review by makslevental — APPROVED** [review]
Thanks for adding the test

**Comment by makslevental** [comment]
@matth2k if you need me to merge lmk

**Pull request merged**
