### PR TITLE
[SPIR-V] Emit OpConstant instead of OpConstantNull to conform to NonSemantic.Shader.DebugInfo.100 DebugTypeBasic's flags definition

### LINKED ISSUE #118011: [SPIR-V] Broken test llvm/test/CodeGen/SPIRV/debug-info/debug-type-basic.ll
Since a recent SPIRV-Tools commit (f3c4a5053f1bd34056282e56659659873f9d47ad), this particular test is broken.

```
error: line 86: NonSemantic.Shader.DebugInfo.100 DebugTypeBasic: expected operand Flags must be a result id of 32-bit unsigned OpConstant
  %52 = OpExtInst %void %49 DebugTypeBasic %51 %uint_8 %uint_2 %20
```

The reason is the emitted SPIR-V does this:

```
%20 = OpConstantNull %9
%-- = OpExtInst %-- %-- DebugTypeBasic %-- %-- %-- %20
```

The last operand if the `Flags` operand, which form the spec:
```
Flags is the <id> of a 32-bit integer OpConstant formed by the bitwise-OR of values from the Debug Info Flags table.
```

Since the flag value is 0, we emit an `OpConstantNull`, but this is not accepted by the validator.
I'm not sure if that's a validation issue (shall `OpConstantNull %uint` be  the same as `OpConstant %uint 0` ?) or not.
Opening an issue in SPIRV-Tools

### PR DESCRIPTION
**Pull request by VyacheslavLevytskyy**
This PR is to fix https://github.com/llvm/llvm-project/issues/118011 by emitting OpConstant instead of OpConstantNull to conform to NonSemantic.Shader.DebugInfo.100 DebugTypeBasic's flags definition.

### CODE REVIEW

**Review by Keenuts — COMMENTED** [review]
I'm fine with this PR, but we talked a bit about this issue internally, and we believe this is not a bug in LLVM. It looks like a simple spirv-val oversight.
I'll ping Alan on the verifier bit see if we can move forward with a fix in spirv-val instead.

**Comment by VyacheslavLevytskyy** [comment]
> I'm fine with this PR, but we talked a bit about this issue internally, and we believe this is not a bug in LLVM. It looks like a simple spirv-val oversight. I'll ping Alan on the verifier bit see if we can move forward with a fix in spirv-val instead.

Thank you, I also think that this should be fixed on spirv-val side. However, until it is fixed we should either proceed with this PR or add XFAIL to the test case. Also, as a side note, I guess we will anyway need to figure out OpConstant vs. OpConstantNull in debug-info to account for environments without null constants (HLSL).

**Comment by Keenuts** [comment]
> Thank you, I also think that this should be fixed on spirv-val side. However, until it is fixed we should either proceed with this PR or add XFAIL to the test case.

If it's just until we fix upstream, I'd be in favor of an XFAIL.

> Also, as a side note, I guess we will anyway need to figure out OpConstant vs. OpConstantNull in debug-info to account for environments without null constants (HLSL).

What do you mean by that?

**Comment by VyacheslavLevytskyy** [comment]
> > Thank you, I also think that this should be fixed on spirv-val side. However, until it is fixed we should either proceed with this PR or add XFAIL to the test case.
> 
> If it's just until we fix upstream, I'd be in favor of an XFAIL.
> 
> > Also, as a side note, I guess we will anyway need to figure out OpConstant vs. OpConstantNull in debug-info to account for environments without null constants (HLSL).
> 
> What do you mean by that?

Please see https://llvm.org/docs/doxygen/SPIRVInstructionSelector_8cpp_source.html line 1772, the comment is "// OpenCL uses nulls for Zero. In HLSL we don't use null constants.", and the whole thing about `bool ZeroAsNull` in SPIRVInstructionSelector.cpp

**Review by Keenuts — APPROVED** [review]
Looks like this might have been an oversight, but several extension specs are using the same requirement, so making a change in the validator might not be trivial.

**Comment by tex3d** [comment]
@VyacheslavLevytskyy: It looks like this PR failed to remove [the XFAIL added to the test](https://github.com/llvm/llvm-project/commit/c7e14689dd8bdf4b18dccb18895a9b80c225dc53) when fixing the issue.  We are hitting an unexpected pass causing testing to fail in our pipeline now due to this.

**Comment by VyacheslavLevytskyy** [comment]
> @VyacheslavLevytskyy: It looks like this PR failed to remove [the XFAIL added to the test](https://github.com/llvm/llvm-project/commit/c7e14689dd8bdf4b18dccb18895a9b80c225dc53) when fixing the issue. We are hitting an unexpected pass causing testing to fail in our pipeline now due to this.

Thank you, this should be fixed in the main branch already.

**Pull request merged**
