### PR TITLE
[clang][Interp] Fix IntAP(s) to IntAP(s) casts

### PR DESCRIPTION
**Pull request by tbaederr**

### CODE REVIEW

**Review by AaronBallman — COMMENTED** [review]
A bit more description about what the issue is and why this solves it would be helpful.

**Comment by tbaederr** [comment]
This was still `assert(false)`'ed out, it's for casts between two `IntAP`/`IntAPS` expressions.
We can't just short-circuit for `FromT == ToT` because we need to consider the bitwidth when doing the cast.

**Comment by tbaederr** [comment]
Ping

**Comment by tbaederr** [comment]
Ping

**Review by AaronBallman — APPROVED** [review]
LGTM but please add the description to the patch commit message when landing.

**Pull request merged**
