### PR TITLE
[LoongArch][clang] Add support for option `-msimd=` and macro `__loongarch_simd_width`.

### PR DESCRIPTION
**Pull request by ylzsx**

### CODE REVIEW

**Review by SixWeining — APPROVED** [review]
LGTM

**Comment by jakeegan** [comment]
Hi, this test is failing on the AIX bot 
https://lab.llvm.org/buildbot/#/builders/64/builds/250/steps/6/logs/FAIL__Clang__loongarch-msimd_c

The reason is that -o is not a supported option with grep on AIX. Would you be able to adapt the test to avoid piping (so that the builtin grep is used, for example here: https://github.com/llvm/llvm-project/pull/83184/files) or use another command like sed?

**Comment by ylzsx** [comment]
> Hi, this test is failing on the AIX bot https://lab.llvm.org/buildbot/#/builders/64/builds/250/steps/6/logs/FAIL__Clang__loongarch-msimd_c
> 
> The reason is that -o is not a supported option with grep on AIX. Would you be able to adapt the test to avoid piping and use input redirection (so that the builtin grep is used, for example here: https://github.com/llvm/llvm-project/pull/83184/files. I'm not sure if this works with grep though) or use another command like sed?

@jakeegan Already fixed, see https://github.com/llvm/llvm-project/pull/98442.

**Comment by jakeegan** [comment]
@ylzsx  Thank you!

**Pull request merged**
