### PR TITLE
LAA: don't version single-iteration loops

### LINKED ISSUE #96656: LoopLoadElim: calling LoopVersioning with single-iteration loop
The following example:

```llvm
define void @lver.check.unnecessary(ptr %arg, ptr %arg1, i1 %arg2) {
entry:
  %load = load i32, ptr %arg, align 4
  br i1 %arg2, label %noloop.exit, label %loop.ph

loop.ph:                                          ; preds = %entry
  %sext7 = sext i32 %load to i64
  %gep8 = getelementptr i8, ptr %arg1, i64 8
  br label %loop.body

loop.body:                                        ; preds = %loop.body, %loop.ph
  %phi = phi i64 [ 0, %loop.ph ], [ %add, %loop.body ]
  %mul = mul i64 %phi, %sext7
  %gep10 = getelementptr double, ptr %gep8, i64 %mul
  %load11 = load double, ptr %gep10, align 8
  store double %load11, ptr %arg1, align 8
  %add = add i64 %phi, 1
  %icmp = icmp eq i64 %phi, 0
  br i1 %icmp, label %loop.exit, label %loop.body

noloop.exit:                                      ; preds = %entry
  %sext = sext i32 %load to i64
  %gep = getelementptr double, ptr %arg1, i64 %sext
  %load5 = load double, ptr %gep, align 8
  store double %load5, ptr %arg, align 8
  ret void

loop.exit:                                        ; preds = %loop.body
  ret void
}
```

has identical output after running loop-versioning before #92119. However, after that patch, the following diff is observed:

```diff
diff --git a/lver.before.ll b/lver.main.ll
index 9dce17d..fc81e12 100644
--- a/lver.before.ll
+++ b/lver.main.ll
@@ -4,22 +4,39 @@ source_filename = "hand-reduce.ll"
 define void @lver.check.unnecessary(ptr %arg, ptr %arg1, i1 %arg2) {
 entry:
   %load = load i32, ptr %arg, align 4
-  br i1 %arg2, label %noloop.exit, label %loop.ph
+  br i1 %arg2, label %noloop.exit, label %loop.body.lver.check

-loop.ph:                                          ; preds = %entry
+loop.body.lver.check:                             ; preds = %entry
   %sext7 = sext i32 %load to i64
   %gep8 = getelementptr i8, ptr %arg1, i64 8
+  %ident.check = icmp ne i32 %load, 1
+  br i1 %ident.check, label %loop.body.ph.lver.orig, label %loop.body.ph
+
+loop.body.ph.lver.orig:                           ; preds = %loop.body.lver.check
+  br label %loop.body.lver.orig
+
+loop.body.lver.orig:                              ; preds = %loop.body.lver.orig, %loop.body.ph.lver.orig
+  %phi.lver.orig = phi i64 [ 0, %loop.body.ph.lver.orig ], [ %add.lver.orig, %loop.body.lver.orig ]
+  %mul.lver.orig = mul i64 %phi.lver.orig, %sext7
+  %gep10.lver.orig = getelementptr double, ptr %gep8, i64 %mul.lver.orig
+  %load11.lver.orig = load double, ptr %gep10.lver.orig, align 8
+  store double %load11.lver.orig, ptr %arg1, align 8
+  %add.lver.orig = add i64 %phi.lver.orig, 1
+  %icmp.lver.orig = icmp eq i64 %phi.lver.orig, 0
+  br i1 %icmp.lver.orig, label %loop.exit.loopexit, label %loop.body.lver.orig
+
+loop.body.ph:                                     ; preds = %loop.body.lver.check
   br label %loop.body

-loop.body:                                        ; preds = %loop.body, %loop.ph
-  %phi = phi i64 [ 0, %loop.ph ], [ %add, %loop.body ]
+loop.body:                                        ; preds = %loop.body, %loop.body.ph
+  %phi = phi i64 [ 0, %loop.body.ph ], [ %add, %loop.body ]
   %mul = mul i64 %phi, %sext7
   %gep10 = getelementptr double, ptr %gep8, i64 %mul
   %load11 = load double, ptr %gep10, align 8
   store double %load11, ptr %arg1, align 8
   %add = add i64 %phi, 1
   %icmp = icmp eq i64 %phi, 0
-  br i1 %icmp, label %loop.exit, label %loop.body
+  br i1 %icmp, label %loop.exit.loopexit1, label %loop.body

 noloop.exit:                                      ; preds = %entry
   %sext = sext i32 %load to i64
@@ -28,6 +45,12 @@ noloop.exit:                                      ; preds = %entry
   store double %load5, ptr %arg, align 8
   ret void

-loop.exit:                                        ; preds = %loop.body
+loop.exit.loopexit:                               ; preds = %loop.body.lver.orig
+  br label %loop.exit
+
+loop.exit.loopexit1:                              ; preds = %loop.body
+  br label %loop.exit
+
+loop.exit:                                        ; preds = %loop.exit.loopexit1, %loop.exit.loopexit
   ret void
 }
```

This is a regression.

The underlying issue is in LoopAccessAnalysis, which produces a false equal predicate. The diff before and after running LAA on the example is:

```diff
diff --git a/laa.before b/laa.main
index 17b0a1b..1b3b1b0 100644
--- a/laa.before
+++ b/laa.main
@@ -7,5 +7,9 @@ Printing analysis 'Loop Access Analysis' for function 'lver.check.unnecessary':

     Non vectorizable stores to invariant address were not found in loop.
     SCEV assumptions:
+    Equal predicate: %load == 1

     Expressions re-written:
+    [PSE]  %gep10 = getelementptr double, ptr %gep8, i64 %mul:
+      {(8 + %arg1),+,(8 * (sext i32 %load to i64))<nsw>}<%loop.body>
+      --> {(8 + %arg1),+,8}<%loop.body>
```

### PR DESCRIPTION
**Pull request by artagnon**
Single-iteration loops are a special case that are likely to be unprofitable to version.

Fixes #96656.

-- 8< --
Based on #97075.

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
> Speculating the stride currently inserts a Stride == 1 predicate, which is equivalent to asserting that the that the loop executes atleast once.

Uh, how are these equivalent (or even related at all)?

> However, when the backedge-taken-count is known-non-negative, speculating the stride unnecessarily versions the loop. Avoid this.

The BE count is an unsigned quantity, so I don't get how "known-non-negative" can be meaningful for it.

**Comment by artagnon** [comment]
> > Speculating the stride currently inserts a Stride == 1 predicate, which is equivalent to asserting that the that the loop executes atleast once.
> 
> Uh, how are these equivalent (or even related at all)?

We currently speculate on the stride and insert `Stride == 1` when `Stride >= TC`. My understanding is that this is to guard against loops with unknown TC that never execute. Inserting `Stride == 1` is a way to version the loop, so that one version executes with this predicate. 
 
> > However, when the backedge-taken-count is known-non-negative, speculating the stride unnecessarily versions the loop. Avoid this.
> 
> The BE count is an unsigned quantity, so I don't get how "known-non-negative" can be meaningful for it.

Wait, what happens for TC = 0? Isn't the BE SCEV an expression that's not known-non-negative?

**Comment by fhahn** [comment]
hmm that's interesting, I was looking at the same code a few weeks ago. I'll try to refresh my memory tomorrow

**Comment by artagnon** [comment]
Okay, so I've investigated this problem thoroughly (producing #97075 as a side-effect), and concluded that this entire stride-versioning thing done by LAA is a rough heuristic that can't change, since too many callers depend on it. To fix the regression, I propose that we patch LoopVersioning directly, and not touch LAA. Any thoughts?

**Comment by fhahn** [comment]
> Okay, so I've investigated this problem thoroughly (producing #97075 as a side-effect), and concluded that this entire stride-versioning thing done by LAA is a rough heuristic that can't change, since too many callers depend on it. To fix the regression, I propose that we patch LoopVersioning directly, and not touch LAA. Any thoughts?

Yeah, versioning loops with a single iteration is likely to not be profitable. Would be interesting to know who is calling LoopVersioning on such loops

**Comment by artagnon** [comment]
Thanks for the guidance. I realized that this was the case, but wasn't sure about adding a special-case for single-iteration loops.

**Comment by fhahn** [comment]
> Thanks for the guidance. I realized that this was the case, but wasn't sure about adding a special-case for single-iteration loops.

Yeah, as I mentioned earlier, it would also be good to understand how we get to the point that someone asks loop-versioning to version such a loop. It might need to be fixed in the passes that requesting versioning, based on the benefit the passes get from versioning (e.g. depending on the pass, other small trip counts may also not be profitable, but ideally that would be decided by the pass that requests versioning, as there more info is available)

**Comment by artagnon** [comment]
Right, got it. I won't re-purpose this PR further, and will open a fresh PR fixing the callers of LoopVersioning.

**Pull request closed without merging**
