### PR TITLE
[llvm-shlib] Fix the version naming style of libLLVM for Windows

### PR DESCRIPTION
**Pull request by mstorsjo**
This reverts the changes from 91a384621e5b762d9c173ffd247cfeadd5f436a2 for Windows targets. The changes in that commit don't work as expected for Windows targets (those parts of llvm_add_library don't quite behave the same for Windows), while the previous status quo (producing a library named "libLLVM-<major>.dll") is the defacto standard way of doing versioned library names there, contrary to on Unix.

After that commit, the library always ended up named "libLLVM.dll", executables linking against it would reference "libLLVM.dll", and "libLLVM-<major>.dll" was provided as a symlink.

Thus revert this bit back to as it were, so that executables actually link against a versioned libLLVM, and no separate symlink is needed.

The only thing that might be improved compared to the status quo as it was before these changes, is that the import library is named "lib/libLLVM-<major>.dll.a", while the common style would be to name it plainly "lib/libLLVM.dll.a" (even while it produces references to "libLLVM-<major>.dll", but none of these had that effect for Windows targets.

(As a side note, the llvm-shlib library can be built for MinGW, but not currently in MSVC configurations.)

### CODE REVIEW

**Review by tstellar — APPROVED** [review]

**Comment by mstorsjo** [comment]
/cherry-pick ec2b7522dbee1cb91111d6ade6e1768462247dcf f84980570d3f85bdf5c9432647c05bae04a735a0 cb2ca23345d3d9bde027a18d301949e8bdf606a6

**Comment by mstorsjo** [comment]
As a headsup to @lazka and @mati865 wrt msys2 packaging: LLVM 18.1.0 and 18.1.1 had the llvm dylib erroneously named `libLLVM.dll`, while this PR restores it to be `libLLVM-18.dll` (and I'm suggesting backporting it).

I didn't include any extra backwards compat symlink named `libLLVM.dll` pointing at `libLLVM-18.dll` though, so any msys2 packages that you've built on top of LLVM 18, that depend on libLLVM, will break and fail to find their dependencies on update of LLVM to later 18.x (if this is backported). So they will need to be rebuilt after restoring the name of the library here.

I guess you can add a temporary symlink/copy within the msys2 packaging of later 18.1.x to smooth out this - but I felt it's the best tradeoff to not provide a symlink on the LLVM side here by default, as symlinks often end up as duplicate copies on Windows.

(This issue with symlinks ending up as large duplicate files can be noticed in the release packages at https://github.com/mstorsjo/llvm-mingw/releases - the `llvm-mingw-*-ucrt-x86_64.zip` packages were around 135 MB each up to 18.1.0 RC2, but after RC3 they grew to 158 MB, as the package contained two separate copies of the libLLVM DLL.)

**Comment by lazka** [comment]
Thanks. Note that it's `libLLVM-18.1.dll` in MSYS2 atm since we pached it differently to align with unix (major.minor being the new ABI version)

**Comment by mstorsjo** [comment]
> Thanks. Note that it's `libLLVM-18.1.dll` in MSYS2 atm since we pached it differently to align with unix (major.minor being the new ABI version since v18 from what I understand)

Oh, ok, I see - yeah in that case, if you've already patched around it, this isn't an issue at all. The earlier changes slipped past me as they didn't break the build for me.

**Comment by lazka** [comment]
They did break llvm-config afair, but I think that's not included in llvm-mingw.

**Comment by mstorsjo** [comment]
> They did break llvm-config afair, but I think that's not included in llvm-mingw.

Oh, right, that's a good point. Let me check whether we'd need to tweak that along with this change here.

**Comment by lazka** [comment]
If its like with v17 it should be good I think

**Comment by mstorsjo** [comment]
> If its like with v17 it should be good I think

Yep, I checked, and e.g. `llvm-config --libs mc` prints `-lLLVM-19git` right now, which is the right thing for the mingw target.

For the unix targets, it should still work as we do provide `libLLVM-19git.so` as a symlink to `libLLVM.so.19.0git`. If we change it to return `-lLLVM` instead, please only do that change for unix targets, as the mingw/windows one still should keep using the `-lLLVM-19git` form.

**Pull request merged**
