### PR TITLE
[CMake][MLIR] Adding dummy target to synchronize LinalgNamedStructuredOps.yamlgen

### PR DESCRIPTION
**Pull request by stefankoncarevic**

### CODE REVIEW

**Comment by stefankoncarevic** [comment]
We have encountered a race condition and compilation failure in the LinalgStructuredOps.td file, which is triggered by tablegen parsing. The issue is related to a mal-formated construct in the LinalgStructuredOps.yamlgen.td file.  
  
To address this issue, we have made changes to introduce a dummy target that enforces synchronization points during the generation process. This ensures that the necessary files are fully generated before proceeding with the subsequent steps.  
  
For more details, please refer to the following ticket:
ticket: https://github.com/ROCm/rocMLIR-internal/issues/524
PR: https://github.com/ROCm/rocMLIR/pull/669

We would appreciate if someone could review this PR and provide feedback. If deemed appropriate, you can consider merging this PR.

**Comment by rengolin** [comment]
The issue you listed is private (I get 404), so not sure on the context.

We're working to deprecate OpDSL for the named ops (#104783), which will eventually cleanup all those issues.

**Comment by stefankoncarevic** [comment]
Here is the new link related to the issue:
https://github.com/llvm/llvm-project/issues/56269
I hope this helps for better understanding the context.

**Comment by stefankoncarevic** [comment]
I'll be closing the current PR and we'll wait for the completion of the other effort, which might help address our issues. Thank you for the update.

**Pull request closed without merging**
