### PR TITLE
Commit mostly working single wrapped module map

### PR DESCRIPTION
**Pull request by EricWF**
This patch is what I use to use modules on Linux when building LLVM.

Without it there are race conditions around the building of each individual module.
I have not validated this on Mac, or with the various submodule visibilitys

This patch also removes two module declarations for modules which don't exist

### CODE REVIEW

**Comment by ldionne** [comment]
CC @ian-twilightcoder

**Comment by ian-twilightcoder** [comment]
We can't do this. The libc++ public headers all need to be top level modules so that they can layer with the clang and OS modules. <https://reviews.llvm.org/D144322> Note that you can't use modules with only the libc++ module map,  you'll need a module map to cover your libc headers as well.

**Comment by EricWF** [comment]
> We can't do this. The libc++ public headers all need to be top level modules so that they can layer with the clang and OS modules. https://reviews.llvm.org/D144322 Note that you can't use modules with only the libc++ module map, you'll need a module map to cover your libc headers and the posix headers used by libc++ as well.

We can and have done this. I suspect the issues you're discussing arise on OS X and not Linux?

I have built LLVM with this change using modules, without any special tweaks for libc or POSIX. So this change works perfectly in some configurations.

If you could provide concrete examples of what breaks, I can work to fix those breakages. But without actual meaningful examples, I can't do much to help.

I understand that this patch, exactly as is, might cause issues with C and POSIX headers. And that those issues may require the `foo.h` and `cfoo` headers to be treated slightly differently.

We also can't not do this. When was the last time you built a large project using our module map? It very quickly breaks trying to build Clang with more than one thread. 

So if this change breaks on a Mac, but is required on Linux and visa versa without this change, then I can come up with a separate path forward.

**Comment by EricWF** [comment]
@ian-twilightcoder It's also worth noting that this change turns a number of `foo.h` headers into textual includes for this very reason.

**Comment by ian-twilightcoder** [comment]
> > We can't do this. The libc++ public headers all need to be top level modules so that they can layer with the clang and OS modules. https://reviews.llvm.org/D144322 Note that you can't use modules with only the libc++ module map, you'll need a module map to cover your libc headers and the posix headers used by libc++ as well.
> 
> We can and have done this. I suspect the issues you're discussing arise on OS X and not Linux?
> 
> I have built LLVM with this change using modules, without any special tweaks for libc or POSIX. So this change works perfectly in some configurations.
> 
> If you could provide concrete examples of what breaks, I can work to fix those breakages. But without actual meaningful examples, I can't do much to help.
> 
> I understand that this patch, exactly as is, might cause issues with C and POSIX headers. And that those issues may require the `foo.h` and `cfoo` headers to be treated slightly differently.
> 
> We also can't not do this. When was the last time you built a large project using our module map? It very quickly breaks trying to build Clang with more than one thread.
> 
> So if this change breaks on a Mac, but is required on Linux and visa versa without this change, then I can come up with a separate path forward.

It will _only_ work if the libc++ module map is the _only_ module map on the system, or if you start adding `[no_undeclared_includes]` hacks to the system module maps. Also it's a requirement of clang modules that they only include headers that are covered by modules. That means that the C standard library, and some select parts of POSIX, have to have their own module maps. You can cheese it by using a single module map and let it absorb all of its dependencies, but that's not the expectation of clang modules.

Once you do have proper modules for the C headers, they quickly introduce cycles. i.e. inttypes.h includes stdint.h. If those are in the same module in libc++ then you get a module cycle: std -> c_inttypes -> std -> c_stdint. Single giant module just doesn't work, and it's not an Apple SDK specific problem, it's any system that actually supports clang modules.

**Comment by EricWF** [comment]
> Once you do have proper modules for the C headers, they quickly introduce cycles. i.e. inttypes.h includes stdint.h. If those are in the same module in libc++ then you get a module cycle: std -> c_inttypes -> std -> c_stdint. Single giant module just doesn't work, and it's not an Apple SDK specific problem, it's any system that actually supports clang modules.

What systems support Clang modules? What can I build today, on Linux using Clang modules?

Could you please try building LLVM with modules enabled `-DLLVM_ENABLE_LIBCXX=ON -DLLVM_ENABLE_MODULES=ON` and tell me what happens on your end before and after this patch?

I'm frustrated by your claims that differ entirely from my lived experience using Clang modules. 
Given that I can and have compiled LLVM with modules on Linux, without issue, I'm unsure how to reproduce the issues.

I would like to work with you, but I'm unable to experimentally verify your claims. Please help me do that.
If we're unable to produce concrete breakages using this module map, then this change should proceed.

**Comment by ian-twilightcoder** [comment]
> > Once you do have proper modules for the C headers, they quickly introduce cycles. i.e. inttypes.h includes stdint.h. If those are in the same module in libc++ then you get a module cycle: std -> c_inttypes -> std -> c_stdint. Single giant module just doesn't work, and it's not an Apple SDK specific problem, it's any system that actually supports clang modules.
> 
> What systems support Clang modules? What can I build today, on Linux using Clang modules?

Out of the box only the Apple SDK supports clang modules. Swift adds module maps to Linux and Windows (and soon Android and musl) via vfs, though admittedly some of those module maps have similar issues.
 
> Could you please try building LLVM with modules enabled `-DLLVM_ENABLE_LIBCXX=ON -DLLVM_ENABLE_MODULES=ON` and tell me what happens on your end before and after this patch?

@vsapsai didn't you try this recently? I remember it came up at the team meeting a few weeks ago at least...

> I'm frustrated by your claims that differ entirely from my lived experience using Clang modules. Given that I can and have compiled LLVM with modules on Linux, without issue, I'm unsure how to reproduce the issues.
> 
> I would like to work with you, but I'm unable to experimentally verify your claims. Please help me do that. If we're unable to produce concrete breakages using this module map, then this change should proceed.

This change will definitely break on Apple systems, though the ones in CI are too old to exhibit the breakage.

**Comment by EricWF** [comment]
@ian-twilightcoder You can stand down on the example until I fix the test suite breakages. My apologies for asking for too much too soon.

**Comment by EricWF** [comment]
@ian-twilightcoder 

I think we may be talking past each other. I think we can likely find a solution that works for everyone.
Would you be willing to schedule a video call?

**Comment by ian-twilightcoder** [comment]
> @ian-twilightcoder
> 
> I think we may be talking past each other. I think we can likely find a solution that works for everyone. Would you be willing to schedule a video call?

Let me discuss with some of the other modules engineers at Apple and see how we think this is supposed to work.

**Comment by ian-twilightcoder** [comment]
> > @ian-twilightcoder
> > I think we may be talking past each other. I think we can likely find a solution that works for everyone. Would you be willing to schedule a video call?
> 
> Let me discuss with some of the other modules engineers at Apple and see how we think this is supposed to work.

Talked to @Bigcheese about it some. I think we need to have an overview of your build environment, is this for Google? Should we try to meed some time with @dwblaikie too and figure out how to best support what you need to do?

**Comment by dwblaikie** [comment]
I'm following only vaguely - I don't think there's any particular/immediate use/plan at Google for this work, but I might be mistaken. We don't generally use pre-written module maps, but build rules that generate module maps. @ilya-biryukov might have interest.

**Comment by vsapsai** [comment]
> > Could you please try building LLVM with modules enabled `-DLLVM_ENABLE_LIBCXX=ON -DLLVM_ENABLE_MODULES=ON` and tell me what happens on your end before and after this patch?
> 
> @vsapsai didn't you try this recently? I remember it came up at the team meeting a few weeks ago at least...

Not particularly recently. I believe `-DLLVM_ENABLE_MODULES=ON` works on macOS. Haven't tried with `-DLLVM_ENABLE_LIBCXX=ON` and haven't tried with this patch.

**Comment by EricWF** [comment]
> I think we need to have an overview of your build environment, is this for Google? Should we try to meed some time with @dwblaikie too and figure out how to best support what you need to do?

This is not at Google, it's me at home trying to save cycles on my LLVM compiles.

The good news is that I haven't been able to reproduce my normal breakages when trying today to create a reproducer :-)

There's been a bunch of work on modules since I last tried this, and I suspect some of it resolved the issues I was seeing.

The less fortunate news is that it appears the current approach, without the top level `std` module, is something like 25% slower to build llvm-tblgen (for example) and produces a module cache about 1.8x the size (205M vs 123M).  than the approach with the top level `std` module.

I'll do some more digging and report back.

**Comment by dwblaikie** [comment]
> The less fortunate news is that it appears the current approach, without the top level std module, is something like 25% slower to build llvm-tblgen (for example) and produces a module cache about 1.8x the size (205M vs 123M). than the approach with the top level std module.

Generally one needs to modularize from the leaves/bottom-up - anything less than that will produce a lot of duplication in the intermediate modules due to the leaves not being modularized. (or creating something more like a PCH - a single module that includes a bunch of non-modular code, but then all modular code that needs any of the non-modular code always goes through that single module (essentially any situation where significant amounts of (especially C++) non-modular code is depended on by more than one module is a bad thing, and should be avoided))

**Comment by ldionne** [comment]
I am proposing to start modularizing libc++ *properly* from the leaves in https://github.com/llvm/llvm-project/pull/98214. I believe that approach would remove the need for this patch (although it will take a bit of time before we have merged enough modules for it to make a difference).

@EricWF Do you still want to pursue this patch?

**Comment by vgvassilev** [comment]
> It will only work if the libc++ module map is the only module map on the system, or if you start adding [no_undeclared_includes] hacks to the system module maps.

This is not a hack. It is quite well explained what that does in llvm/llvm-project@ed84df008f609.

> Out of the box only the Apple SDK supports clang modules.

That is quite incorrect. Our framework for large scale data analysis [ROOT](https://root.cern), supports modules on Linux and OSX since 2017 and everything worked pretty well before these changes...

> This change will definitely break on Apple systems, though the ones in CI are too old to exhibit the breakage.

That's very abstract. Could you please give us something to work with?

> @EricWF Do you still want to pursue this patch?

Our infrastructure at CERN depends on a single module of STL for performance, distribution and integration reasons on OSX. I'd like to pursue this patch or anything else that brings back the old behavior. I am not sure what the concerns of @ian-twilightcoder are concretely. I'd be happy to help if we can see a reproducible setup.

cc: @hahnjo, @dpiparo.

**Comment by ldionne** [comment]
@vgvassilev We're on the same page. We also want to see a sane modulemap with as few top-level modules as possible. However, the approach I am suggesting to get there is to gradually modularize libc++ the way it should always have evolved, that is by following the directory structure of the library and making sure that said directory structure is module friendly. As opposed to taking the modulemap soup we currently have and putting it under an umbrella.

We also have reasons to want to improve this situation beyond simple code cleanup, and I plan to work on improving that situation after the LLVM 19 branch has been created.

**Comment by vgvassilev** [comment]
@ldionne, that sounds awesome!!

**Comment by ldionne** [comment]
Closing since we are making progress on an iterative simplification of the modulemap. Ideally we'll end up with a small number of top-level modules (we need the `.h` C headers to be their own top-level modules to avoid circular dependencies with the system).

**Pull request closed without merging**
