### PR TITLE
Revert "NFC: Make clang resource headers an interface library (#88317)"

### PR DESCRIPTION
**Pull request by etcwilde**
This reverts commit 8d468c132eed7ffe34d601b224220efd51655eb3.

@ayermolo reports seeing the following error when the clang-resource-headers are a library instead of a custom target:
```
CMake Error at CMakeLists.txt:86 (get_property):
  get_property could not find TARGET clang-resource-headers.  Perhaps it has
  not yet been created.
```
I don't see this line in the LLVM repository, and I'm not sure how it worked as a custom target since this change doesn't affect whether or not the CMake target is generated, nor does it impact the order that targets are created in.

### CODE REVIEW

**Comment by etcwilde** [comment]
@ayermolo, one idea might be to see if `clang-resource-headers` is in the install distribution list? I'm not seeing a matching `get_property` in a CMakeLists.txt that matches the above error exactly, so I'm not sure how to reproduce this or how you're picking up the clang-resource-headers target.

**Review by compnerd — APPROVED** [review]
Approving it in case it needs to be merged, but I think that we should try to determine how it is breaking. This change feels like it should be correct and is a pretty good cleanup, so I would prefer that fix forward rather than revert.

**Comment by ayermolo** [comment]
Thanks. 
It's failing internally in our automatic multi stage build. Trying to dig into it as part of my oncall. :)

**Comment by ayermolo** [comment]
Seems like an issue is our internal CMakeLists that 

```
set (LIBS ${CLANG_EXPORTED_TARGETS} ${LLD_EXPORTED_TARGETS} ${LLVM_AVAILABLE_LIBS})
foreach(LIB ${LIBS})
  get_property(TYPE TARGET ${LIB} PROPERTY TYPE)
```

**Comment by ayermolo** [comment]
Fixed our internal foobar yesterday. Can close this.

**Comment by etcwilde** [comment]
Great, glad to hear that you figured out what was happening. I wasn't sure how the target would end up in the clang-export list and not be defined since the bit of code that adds it to the clang-export list isn't conditionalized any differently than the creation of the target itself.

**Pull request closed without merging**
