### PR TITLE
[MC][NFC] Allow MCInstrAnalysis to store state

### PR DESCRIPTION
**Pull request by jobnoorman**
Currently, all the analysis functions provided by `MCInstrAnalysis` work on a single instruction. On some targets, this limits the kind of instructions that can be successfully analyzed as common constructs may need multiple instructions.

For example, a typical call sequence on RISC-V uses a auipc+jalr pair. In order to analyse the jalr inside `evaluateBranch`, information about the corresponding auipc is needed. Similarly, AArch64 uses adrp+ldr pairs to access globals.

This patch proposes to add state to `MCInstrAnalysis` to support these use cases. Two new virtual methods are added:
- `updateState`: takes an instruction and its address. This methods should be called by clients on every instruction and allows targets to store whatever information they need to analyse future instructions.
- `resetState`: clears the state whenever it becomes irrelevant. Clients could call this, for example, when starting to disassemble a new function.

Note that the default implementations do nothing so this patch is NFC. No actual state is stored inside `MCInstrAnalysis`; deciding the structure of the state is left to the targets.

This patch also modifies llvm-objdump to use the new interface.

This patch is an alternative to [D116677](https://reviews.llvm.org/D116677) and the idea of storing state in `MCInstrAnalysis` was first discussed there.

### CODE REVIEW

**Comment by mtvec** [comment]
Ping.

**Comment by asb** [comment]
This change LGTM, but I'd appreciate an OK from someone who has a broader view of the MC infrastructure.

**Comment by asb** [comment]
> This change LGTM, but I'd appreciate an OK from someone who has a broader view of the MC infrastructure.

@MaskRay @jh7370 might you be able to take a quick look at this? Thanks in advance.

**Review by jh7370 — COMMENTED** [review]
This looks okay to me, but I probably need to see the usage in practice.

**Comment by mtvec** [comment]
> This looks okay to me, but I probably need to see the usage in practice.

Please see #65480 for an application.

**Review by jh7370 — APPROVED** [review]
The code formatter check seems to have failed. Might need to run clang-format?

No objections from me - the solution seems reasonably neat. Please give it a few more days to let @MaskRay chime in as he has a better understanding of the MC disassembly stuff than I do and he was away recently, so might still be catching up.

**Comment by mtvec** [comment]
> The code formatter check seems to have failed. Might need to run clang-format?

I'm not entirely sure why they're failing but it seems to be some intermittent error, unrelated to formatting, that I see happening every now and then on GH:

```
Error: Unable to determine a difference between 53179129edbff13644b7c46336773fb8740899c9..2eac9f59aca1c59d47a615084b2bfb839e9f1b0c
```

> No objections from me - the solution seems reasonably neat. Please give it a few more days to let @MaskRay chime in as he has a better understanding of the MC disassembly stuff than I do and he was away recently, so might still be catching up.

Sounds good!

**Review by MaskRay — APPROVED** [review]

**Pull request merged**
