### PR TITLE
[flang] Remove obsolete flang-to-external-fc tool

### PR DESCRIPTION
**Pull request by mjklemm**
It seems like the `flang-to-external-fc` tool is no longer needed, because Flang is now a full compiler in its own right. After PR #85249 has landed, this tool will not be able to pick up the `.f18.mod` files.

### CODE REVIEW

**Review by banach-space — APPROVED** [review]
LGTM, thanks!

@sscalpone - any objections?

**Comment by mjklemm** [comment]
I have not seen any feedback for my post at https://discourse.llvm.org/t/flang-is-flang-to-external-fc-still-needed/78289.  I guess, we can remove the tool and see if we get complaints?

**Comment by banach-space** [comment]
> I have not seen any feedback for my post at https://discourse.llvm.org/t/flang-is-flang-to-external-fc-still-needed/78289. I guess, we can remove the tool and see if we get complaints?

SGTM 👍🏻

**Review by tblah — APPROVED** [review]
This seems reasonable. The RFC has been up for a week and this was raised on the community call earlier this week.

**Comment by mjklemm** [comment]
Plus, the removal of the f18.mod files has been merged a good while ago and nobody seems to have noticed. So, I'll go ahead and merge tomorrow to provide another window for objections.

**Pull request merged**
