### PR TITLE
[analyzer] Demonstrate superfluous unsigned >= 0 assumption

### PR DESCRIPTION
**Pull request by NagyDonat**
This commit adds a testcase which highlights the current incorrect behavior of the CSA diagnostic generation: it produces a note which says "Assuming 'arg' is >= 0" in a situation where this is not a fresh assumption because 'arg' is an unsigned integer.

I also created ticket #78440 to track this bug.

### CODE REVIEW

**Comment by NagyDonat** [comment]
I don't know what's the usual policy for testcases like this that demonstrate a bug: we could merge it to have an in-repository reminder (which automatically alerts us when a change fixes this issue), or we could leave it as an open pull request to avoid cluttering the repository.

**Comment by steakhal** [comment]
I'd advise against introducing a separate file for this, but I'm okay with landing tests.
Given this issue, I'd be interested to look at how difficult it is to actually fix it and commit the case along with the fix.
Have you looked at potential solutions?

**Comment by NagyDonat** [comment]
I didn't check for potential solutions yet, I wanted to document and report this ASAP and then switch to other tasks. I think I'll leave this commit here without merging it for some time, and if I don't end up resolving this within a month, then I'll find a place for this TC in some existing file.

**Review by steakhal — APPROVED** [review]

**Comment by NagyDonat** [comment]
Thanks for the approval; I forgot about this issue a few weeks ago.

Now that you reminded me, I tried to research its cause and dropped a FIXME onto the statement that is not sound logically. Unfortunately I don't see an easy solution for this issue (apart from a ham-fisted hack that explicitly handles comparisons between unsigned values and zero as a special case).

I considered a completely different logic for the `IsAssuming` check: instead of checking for a change in constraints or an unknown opaque value, we could look for a branching point in the exploded graph. However, I fear that the exploded graph is complicated and a bit "magical" so implementing this completely correctly could waste lots of time.

As the only effect of this bug is a slightly inaccurate message, I feel that it's low priority and it's not worth to work on it. I think I would like to merge this testcase and FIXME (mainly to mark that this issue is already known), and then switch to different tasks.

I tried to look for an existing test file where I could place this testcase but I didn't find anything that's clearly connected to this issue, so I think it's better to keep this in a separate file. (But if you can suggest a file where I could place this, then I'm happy to do so.)

**Review by steakhal — APPROVED** [review]
Still looks good.

**Pull request merged**
