### PR TITLE
[DirectX] Fix HLSL bitshifts to leverage the OpenCL pipeline for bitshifting

### LINKED ISSUE #55106: HLSL masking bitshifts
In HLSL bit shifts are defined to shift by `shift size % type size`. In DXC the IR semantics were changed so that the LLVM IR bit shift behaves that way. Upstream this will be two changes:

1) In HLSL codegen bit shifts should be emitted as `x << (y & (sizeof(x) - 1)`
2) In the DirectX backend we should pattern match the mask and remove it in any cases that it wasn't optimized away

AC:
We have leveraged the OpenCL pipeline for bitshift masking
Tests are written to validate this behavior

### PR DESCRIPTION
**Pull request by coopp**
Fixes #55106

In HLSL bit shifts are defined to shift by shift size % type size. This contains the following changes:

HLSL codegen bit shifts will be emitted as x << (y & (sizeof(x) - 1) and bitshift masking leverages the OpenCL pipeline for this.

Tests were also added to validate this behavior.

Before this change the following was being emitted:
; Function Attrs: noinline nounwind optnone
define noundef i32 @"?shl32@@YAHHH@Z"(i32 noundef %V, i32 noundef %S) #0 {
entry:
  %S.addr = alloca i32, align 4
  %V.addr = alloca i32, align 4
  store i32 %S, ptr %S.addr, align 4
  store i32 %V, ptr %V.addr, align 4
  %0 = load i32, ptr %V.addr, align 4
  %1 = load i32, ptr %S.addr, align 4
  %shl = shl i32 %0, %1
  ret i32 %shl
}

After this change:
; Function Attrs: noinline nounwind optnone
define noundef i32 @"?shl32@@YAHHH@Z"(i32 noundef %V, i32 noundef %S) #0 {
entry:
  %S.addr = alloca i32, align 4
  %V.addr = alloca i32, align 4
  store i32 %S, ptr %S.addr, align 4
  store i32 %V, ptr %V.addr, align 4
  %0 = load i32, ptr %V.addr, align 4
  %1 = load i32, ptr %S.addr, align 4
  %shl.mask = and i32 %1, 31
  %shl = shl i32 %0, %shl.mask
  ret i32 %shl
}

### CODE REVIEW

**Comment by python3kgae** [comment]
What is the output before this change?
It would be nice to add more information to the PR description.

**Comment by coopp** [comment]
> What is the output before this change? It would be nice to add more information to the PR description.

I added a description that shows a before/after output for this change.

**Review by llvm-beanz — APPROVED** [review]
LGTM

**Review by python3kgae — APPROVED** [review]

**Comment by llvm-beanz** [comment]
The bot failure looks like an unrelated CMake issue on Windows. I think we've seen that around a few times. I'll merge this now.

**Pull request merged**
