### PR TITLE
[aarch64][llvm] Allow AArch64 TLB maintenance instructions to be enabled via -march

### PR DESCRIPTION
**Pull request by dpaoliello**
Enables `xs` and `tlb-rmi` target features to be enabled via `-march`.

### CODE REVIEW

**Review by efriedma-quic — COMMENTED** [review]
`__ARM_FEATURE_*` defines are, as far as I know, supposed to be defined in the ACLE.  So there needs to be an issue/PR for the ACLE spec.  Once Arm reviews that, we can merge the corresponding patches here.

**Comment by dpaoliello** [comment]
> `__ARM_FEATURE_*` defines are, as far as I know, supposed to be defined in the ACLE. So there needs to be an issue/PR for the ACLE spec. Once Arm reviews that, we can merge the corresponding patches here.

Ah, interesting, any objection to not adding the detection macros?

**Comment by davemgreen** [comment]
Could you give more details about why you would want these added? As far as I understand they are mandatory features for 8.4 and 8.7, and would usually be added via -march=armv8.4-a for example. We try to keep the options between GCC and clang the same, and GCC doesn't seem to support either https://godbolt.org/z/TTnq48W81.

**Comment by dpaoliello** [comment]
> Could you give more details about why you would want these added?

These instructions are being used in the hand-written assembly for a hypervisor. The hypervisor will check at runtime if the instructions are available on the current CPU before calling this code.

**Comment by efriedma-quic** [comment]
> Ah, interesting, any objection to not adding the detection macros?

For the feature names, I think we also try to coordinate with Arm to define the names.  (Maybe also in the ACLE? Not sure.)  So I don't object to splitting the patch, but I'm not sure that really helps.

**Comment by davemgreen** [comment]
> These instructions are being used in the hand-written assembly for a hypervisor. The hypervisor will check at runtime if the instructions are available on the current CPU before calling this code.

We try to coordinate between GCC and LLVM, to make sure we implement the same interface. Is there a reason you can't use `-march=armv8.7-a` as it works today, or add a `.arch armv8.7-a` directive? Otherwise we will need to check with GCC to make sure they are happy to implement the same features.

**Comment by dpaoliello** [comment]
I'm going to close this: using the `.arch` directives works, so we're unblocked.

**Pull request closed without merging**
