### PR TITLE
Reapply "[RISCV] Implement tail call optimization in machine outliner"

### PR DESCRIPTION
**Pull request by mag-mga**
This MR fixes failed test `CodeGen/RISCV/compress-opt-select.ll`.

It was failed due to previously merged commit `[TTI][RISCV] Unconditionally break critical edges to sink ADDI (PR #108889)`.

So, regenerated `compress-opt-select` test.

### CODE REVIEW

**Comment by joker-eph** [comment]
Hi @mga-sc : I reverted the original PR to unbreak the CI. In general we revert unless we can land a fix-forward immediately. 
This removes pressure on reviewing the right fix, feel free to cherry-pick the original commit, rebase (or squash) your fix here on top of it, and get it all landed again.

**Comment by wangpc-pp** [comment]
Don't worry and please cherry-pick the reverted commit here and reland it with your fix:
1. `cherry-pick` the reverted commit.
2. Fix the test.
3. Change the PR title to `Reapply "..."` and describe the reason why it was reverted.
4. Then we can give a LGTM after the success of CI.

**Comment by mga-sc** [comment]
@wangpc-pp , done, CI has been passed.

**Review by wangpc-pp — APPROVED** [review]
LGTM.

**Comment by mga-sc** [comment]
@wangpc-pp , could you please merge in this case

**Pull request merged**
