### PR TITLE
[clangd] Allow --query-driver to match a dot-normalized form of the path

### PR DESCRIPTION
**Pull request by sam-mccall**
(In addition to the un-normalized form, so this is back-compatible)

### CODE REVIEW

**Comment by sam-mccall** [comment]
@kadircet this is internal b/294113850

**Comment by kadircet** [comment]
thanks, no need for tests, the logic is rather trivial (might be worth mentioning in change notes though, so that we can build them up more naturally for the future and encourage others to do so as well)

**Review by kadircet — APPROVED** [review]

**Comment by HighCommander4** [comment]
See also some existing reports we have on file about other types of normalization:

  * https://github.com/clangd/clangd/issues/1518 (Windows shorthands like `PROGRA~1`)
  * https://github.com/clangd/clangd/issues/1605 (symlinks)
  * https://github.com/llvm/llvm-project/issues/62506 (double slashes)

**Comment by sam-mccall** [comment]
Thanks! This will fix the double-slash issue (despite the name, `add_dots` normalizes those).

symlinks and progra~1 mean normalization based on actual filesystem access, and choosing between multiple forms that are in some sense equally valid.

I don't think I'm opposed if someone wants to take a shot at solving that (we can *afford* to do IO here), but it's definitely a more complicated idea.

**Pull request merged**
