### PR TITLE
[MIPS] Optimize sortRelocs for o32

### LINKED ISSUE #104562: [MIPS] `MIPSELFObjectWriter::sortRelocs()` makes compilation near-unusably slow for O32
Building and running the Zig standard library tests (with LLVM 18.1.8):

```console
❯ time zig4 build -j8 -Dno-lib -Dno-bin -fqemu test-std -Dtest-target-filter=mips64- -Dtest-target-filter=mips64el-
________________________________________________________
Executed in  209.15 secs    fish           external
   usr time   18.17 mins  361.00 micros   18.17 mins
   sys time    1.02 mins   64.00 micros    1.02 mins
❯ time zig4 build -j8 -Dno-lib -Dno-bin -fqemu test-std -Dtest-target-filter=mips- -Dtest-target-filter=mipsel- -Dtest-slow-targets
________________________________________________________
Executed in   66.50 mins    fish           external
   usr time  242.35 mins    5.87 millis  242.35 mins
   sys time    1.06 mins    0.30 millis    1.06 mins
```

As a result of this, we've had to disable MIPS O32 tests for local development and only run them in CI.

Attaching a debugger made it clear that the overwhelming majority of time is spent in `MIPSELFObjectWriter::sortRelocs()`. Specifically (and perhaps unsurprisingly) here:

https://github.com/llvm/llvm-project/blob/ef6760116fa2fa21f78e7a3b499f77e1a3eb7b92/llvm/lib/Target/Mips/MCTargetDesc/MipsELFObjectWriter.cpp#L468-L476

Some extra context:

```
(gdb) p Relocs.size()
$3 = 1412282
(gdb) p Remainder.size()
$4 = 439999
(gdb) p Sorted.size()
$5 = 1019010
```

We build the standard library tests as one big executable so we end up with a ton of relocations. Due to the size of the resulting LLVM IR, I can't easily post it here. :slightly_frowning_face:

### PR DESCRIPTION
**Pull request by MaskRay**
The o32 ABI specifies:

> Each relocation type of R_MIPS_HI16 must have an associated R_MIPS_LO16 entry immediately following it in the list of relocations. [...] the addend AHL is computed as (AHI << 16) + (short)ALO

In practice, the high-part and low-part relocations may not be adjacent
in assembly files, requiring the assembler to reorder relocations.
http://reviews.llvm.org/D19718 performed the reordering, but did not
optimize for the common case where a %lo immediately follows its
matching %hi. The quadratic time complexity could make sections with
many relocations very slow to process.

This patch implements the fast path, simplifies the code, and makes the
behavior more similar to GNU assembler (for the .rel.mips_hilo_8b test).
We also remove `OriginalSymbol`, removing overhead for other targets.

Fix #104562

### CODE REVIEW

**Comment by MaskRay** [comment]
@alexrp

**Comment by alexrp** [comment]
FWIW, it would be fantastic if this could make it into LLVM 19; it would allow us to re-enable MIPS O32 testing in Zig when we upgrade from 18 (probably in September?).

**Comment by wzssyqa** [comment]
Thanks. LGTM.

**Comment by alexrp** [comment]
@MaskRay @wzssyqa can this be cherry-picked into the LLVM 19 release branch?

**Pull request merged**
