### PR TITLE
[NVPTX] Support copysign PTX instruction

### PR DESCRIPTION
**Pull request by AlexMaclean**
Lower `fcopysign` SDNodes into `copysign` PTX instructions where possible. See [PTX ISA: 9.7.3.2. Floating Point Instructions: copysign](https://docs.nvidia.com/cuda/parallel-thread-execution/index.html#floating-point-instructions-copysign).

### CODE REVIEW

**Review by Artem-B — APPROVED** [review]
LGTM.

For my own education -- is there hardware support for this instruction in SASS? Or would the copysign get expanded to the bit twiddling LLVM does?

**Comment by AlexMaclean** [comment]
> LGTM.
> 
> For my own education -- is there hardware support for this instruction in SASS? Or would the copysign get expanded to the bit twiddling LLVM does?

Here is a quick comparison of the SASS before/after this change: https://godbolt.org/z/snWTGEG81. copysign is still getting expanded but it looks like `ptxas` is doing a better job then the SelectionDAG (2 vs. 3 instructions).

**Comment by Artem-B** [comment]
>  it looks like ptxas is doing a better job then the SelectionDAG (2 vs. 3 instructions).

`2x LOP3.LUT` look like a likely win over `SHF, ISETP, FSEL`.

We should probably start using `lop3` more often, as it could potentially handle other common operations a bit better than the discrete logical ops we use now.

**Comment by pranavk** [comment]
This is making some of our internal XLA tests fail. I talked to @Artem-B offline and it seems we missed case of copysign from a constant. I will have to revert this to unblock us.

**Comment by pranavk** [comment]
I am working on some reproducers for you but that may take few hours.

**Comment by AlexMaclean** [comment]
Sounds good, Apologies! Some reproducers would be great!

**Comment by pranavk** [comment]
@AlexMaclean I have this I can share:

```
LLVM ERROR: Cannot select: t31: f32 = fcopysign ConstantFP:f32<5.000000e-01>, t17
  t19: f32 = ConstantFP<5.000000e-01>
  t17: f16,ch = load<(invariant load (s16) from %ir.7, addrspace 1)> t0, t16, undef:i64
    t16: i64 = add t10, t34
      t10: i64 = addrspacecast[0 -> 1] t35
        t35: i64,ch = load<(dereferenceable invariant load (s64) from `ptr addrspace(101) null`, addrspace 101)> t0, TargetExternalSymbol:i64'foo', undef:i64
          t1: i64 = TargetExternalSymbol'foo'
          t3: i64 = undef
      t34: i64 = NVPTXISD::MUL_WIDE_UNSIGNED t12, Constant:i32<2>
        t12: i32 = llvm.nvvm.read.ptx.sreg.tid.x TargetConstant:i64<8487>
          t11: i64 = TargetConstant<8487>
        t33: i32 = Constant<2>
    t3: i64 = undef
```

I will be working on getting the LLVM IR for you unless above is sufficient. Please let me know.

**Comment by AlexMaclean** [comment]
Thanks, this is enough, it seems the problem is not the constant but that the second arg is of f16 type

**Comment by Artem-B** [comment]
Huh. I'm surprised to see copysign used with mixed FP types.

**Comment by AlexMaclean** [comment]
Yea it seems like many targets have had to work around this property of FCOPYSIGN nodes. One option would be to update ISel to handle these cases but I went ahead and added a TLI hook to prevent this sort of folding all together. https://github.com/llvm/llvm-project/pull/108125

**Pull request merged**
