### PR TITLE
[RISCV] Change heuristic used for load clustering

### PR DESCRIPTION
**Pull request by asb**
Split out from #73789, so as to leave that PR just for flipping load clustering to on by default. Clusters if the operations are within a cache line of each other (as AMDGPU does in shouldScheduleLoadsNear). X86 does something similar, but does `((Offset2 - Offset1) / 8 > 64)`. I'm not sure if that's intentionally set to 512 bytes or if the division is in error.

Adopts the suggestion from @wangpc-pp to query the cache line size and use it if available.

We also cap the maximum cluster size to cap the potential register pressure impact (which may lead to additional spills).

### CODE REVIEW

**Comment by asb** [comment]
I've tweaked slightly to limit the maximum cluster size. Without that, increased register pressure might lead to an unacceptable number of additional spills.

**Comment by asb** [comment]
Ping.

**Review by wangpc-pp — APPROVED** [review]
LGTM!

**Comment by asb** [comment]
Rebased so this can be landed ahead of #75338 that's still awaiting review.

**Pull request merged**
