### PR TITLE
[builtins] Support QUAD with native long double

### PR DESCRIPTION
**Pull request by perry-ca**
Redo #77554 to solve build issue found in #77880.

### CODE REVIEW

**Comment by perry-ca** [comment]
@arichardson any idea why the build failed?  It appears to be in some tests for dlopen().

**Comment by arichardson** [comment]
I'll try testing this for various architectures tomorrow and if that works I'll go ahead and merge it.

**Comment by arichardson** [comment]
I am getting some errors when cross-building for PPC64, will do some digging to see how the ifdefs need to be adjusted.

**Comment by perry-ca** [comment]
Thanks for the update

From: Alexander Richardson ***@***.***>
Sent: Tuesday, January 16, 2024 2:35 PM
To: llvm/llvm-project ***@***.***>
Cc: Sean Perry ***@***.***>; Author ***@***.***>
Subject: [EXTERNAL] Re: [llvm/llvm-project] [builtins] Support QUAD with native long double (PR #77981)

I am getting some errors when cross-building for PPC64, will do some digging to see how the ifdefs need to be adjusted. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the
ZjQcmQRYFpfptBannerStart
This Message Is From an External Sender
This message came from outside your organization.
    Report Suspicious  <https://us-phishalarm-ewt.proofpoint.com/EWT/v1/PjiDSg!2U-qSTa06VIRMu4YcIkOZYJv87-YdAlWKJZAkdb8L-gnGW_ui7Pp0b5Yv70fJ1Bccsd7hQG_1LcVxoDvhJzfUxeRIQve7bs1P2zh$>   ‌
ZjQcmQRYFpfptBannerEnd

I am getting some errors when cross-building for PPC64, will do some digging to see how the ifdefs need to be adjusted.

**Comment by perry-ca** [comment]
@arichardson has addressed the build issues in https://github.com/llvm/llvm-project/pull/82208.  This PR is superseded by this PR.

**Pull request closed without merging**
