### PR TITLE
TTI: Check legalization cost of fptosi_sat/fptoui_sat nodes

### PR DESCRIPTION
**Pull request by arsenm**

### CODE REVIEW

**Comment by arsenm** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100521?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#100521** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100521?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#100520** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100520?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#100519** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100519?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#100518** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100518?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#100514** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100514?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#100513** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100513?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#97463** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/97463?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by davemgreen — COMMENTED** [review]
The structure of the code is better to me. Unfortunately all these will be marked custom so the scores come out as meaningless.

**Comment by RKSimon** [comment]
I'm not sure whether its better to just focus on removing some of the custom lowering (and improve TargetLowering::expandFP_TO_INT_SAT) or just add better cost table support.

**Comment by davemgreen** [comment]
I think it would be better if the generic model produced better results for custom nodes, but I have extended the existing costs for Arm/AArch64 to hopefully give a better cost in more cases. It just extended what was already there to handle more cases.

**Review by RKSimon — APPROVED** [review]
LGTM - the x86 lowering needs reworking but that shouldn't hold this PR up.

**Comment by arsenm** [comment]
### Merge activity

* **Aug 9, 4:27 AM EDT**: @arsenm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/100521).

**Pull request merged**
