### PR TITLE
[clang-format] Extract utility functions outside of test fixture

### PR DESCRIPTION
**Pull request by seranu**
Extract utility functions outside of test fixture for DefinitionBlockSeparatorTest so that these functions can be used by other test fixtures. There are no functional changes.

This is a refactoring in preparation of the fix for #42112

### CODE REVIEW

**Review by mydeveloperday — COMMENTED** [review]
I don't understand why we need to refactor this?

**Comment by seranu** [comment]
> I don't understand why we need to refactor this?

During the review for https://github.com/llvm/llvm-project/pull/77918 there was an ask to extract the refactor in a separate PR.

**Comment by mydeveloperday** [comment]
> > I don't understand why we need to refactor this?
> 
> During the review for #77918 there was an ask to extract the refactor in a separate PR.
> 
> In #77918, I'm adding a couple new test fixtures and plan to use these utility functions for verifying assumptions.

Am I missing someone but how do you plan on using these functions if they are in an anonymous namespace in the file and not part of a class where they are static? maybe I missed something.

**Comment by seranu** [comment]
> Am I missing someone but how do you plan on using these functions if they are in an anonymous namespace in the file and not part of a class where they are static? maybe I missed something.

I am planning to define other test fixtures in the same file. I need to do it as I want to add parametrized tests for DefinitionBlockSeparator and need a new test fixture for that. The proposal is available for reference here: https://github.com/llvm/llvm-project/pull/77918/files#diff-a3ebb77dfe5a0623927f138f1689854ca47ff0f3bba6386850090e781935c4c7

**Comment by seranu** [comment]
Closing this PR as rework has been requested on https://github.com/llvm/llvm-project/pull/77918

**Pull request closed without merging**
