### PR TITLE
[libc++abi] Handle catch null pointer-to-object

### PR DESCRIPTION
**Pull request by iains**
This addresses cases (currently failing) where we throw a null pointer-to- object and is a proposed fix for
https://github.com/llvm/llvm-project/issues/64953

We are trying to satisfy the following bullet from the C++ ABI 15.3:

 *  the handler is of type cv1 T* cv2 and E is a pointer type that can be converted to the type of the handler by either or both of:

    o  a standard pointer conversion (4.10 [conv.ptr]) not involving conversions to private or protected or ambiguous classes.

    o  a qualification conversion.

The existing implementation assesses the ambiguity of bases by computing the offsets to them; ambiguous cases are then when the same base appears at different offsets.  The computation of offset  includes indirecting through the vtables to find the offsets to virtual bases.

When the thrown pointer points to a real object, this is quite efficient since, if the base is found, and it is not ambiguous and on a public path, the offset is needed to return the adjusted pointer (and the indirections are not particularly expensive to compute).

However, when we throw a null pointer-to-object, this scheme is no longer applicable (and the code currently bypasses the relevant computations, leading to the incorrect catches reported in the issue).

-----

The solution proposed here takes a composite approach:

1. When the pointer-to-object points to a real instance (well, at least, it is determined to be non-null), we use the existing scheme.

2. When the pointer-to-object is null:

 * We note that there is no real object.
 * When we are processing non-virtual bases, we continue to compute the offsets, but for a notional dummy object based at 0.  This is OK, since we never need to access the object content for non-virtual bases.
 * When we are processing a path with one or more virtual bases, we remember a cookie corresponding to the inner-most virtual base found so far (and set the notional offset to 0).  Offsets to inner non-virtual bases are then computed as normal.

A base is then ambiguous iff:
  * There is a recorded virtual base cookie and that is different from the current one or,
  * The non-virtual base offsets differ.

When a handler for a pointer succeeds in catching a base pointer for a thrown null pointer-to-object, we still return a nullptr (so the adjustment to the pointer is not required and need not be computed).

Since we noted that there was no object when starting the search for ambiguous bases, we know that we can skip the pointer adjustment.

This was : Differential Revision: https://reviews.llvm.org/D158769

### CODE REVIEW

**Comment by iains** [comment]
ran git clang-format with clang-format from llvm-17.

**Review by rjmccall — COMMENTED** [review]
I'm... not sure it's okay to change v-tables in the `std::type_info` hierarchy like this.  In theory it's non-ABI and purely an internal implementation detail of the C++ runtime, but in practice there are some other subclasses out there, like in the ObjC runtime.

I know that the bot is telling you to reformat, but that is making it a lot more difficult to review this patch; please just ignore the bot or do the reformat in a separate PR.

Let me try to understand the basic problem here.  We have an exception that's dynamically a null pointer statically typed as `Base*`, and we're testing whether it's caught by `Derived*`.  This should succeed only if there is a unique public `Base` subobject in `Derived`.  Catching is built on top of the machinery for `dynamic_cast`, but the exception path can't be handled the same way it is for `dynamic_cast` for two reasons:
- First, the `dynamic_cast` operator on a null pointer just produces a null pointer unconditionally; it is not meaningful to ask whether the cast "succeeded".  That is not true with EH, because we have to decide whether we enter the `catch` block (or pass the EH filter).
- Second, in `dynamic_cast` we know both types statically and could therefore evaluate the unique-public-subclass condition statically if we needed to.  This is not possible with EH because the type relationship is dynamic.

So EH needs a way to check the has-unique-public-subclass condition without looking at actual objects.  Makes sense.

**Comment by iains** [comment]
> I'm... not sure it's okay to change v-tables in the `std::type_info` hierarchy like this. In theory it's non-ABI and purely an internal implementation detail of the C++ runtime, but in practice there are some other subclasses out there, like in the ObjC runtime.

My, perhaps flawed, understanding is that Objective-C is supposed to inherit from the parent language and thus, absent a specification to the contrary, a bug in the exception handling here would also be a bug in the Objective-C exception handling, thus it should also import the fix)?

> I know that the bot is telling you to reformat, but that is making it a lot more difficult to review this patch; please just ignore the bot or do the reformat in a separate PR.

(agreed that the layout change obfuscates some of the change purpose - most of it is just initialising the new bool in __dynamic_cast_info).  However, if you like I can find my original patch (without the layout changes) and force-push that here?

> Let me try to understand the basic problem here. We have an exception that's dynamically a null pointer statically typed as `Base*`, and we're testing whether it's caught by `Derived*`. This should succeed only if there is a unique public `Base` subobject in `Derived`. Catching is built on top of the machinery for `dynamic_cast`, but the exception path can't be handled the same way it is for `dynamic_cast` for two reasons:
> 
> * First, the `dynamic_cast` operator on a null pointer just produces a null pointer unconditionally; it is not meaningful to ask whether the cast "succeeded".  That is not true with EH, because we have to decide whether we enter the `catch` block (or pass the EH filter).
> * Second, in `dynamic_cast` we know both types statically and could therefore evaluate the unique-public-subclass condition statically if we needed to.  This is not possible with EH because the type relationship is dynamic.
> 
> So EH needs a way to check the has-unique-public-subclass condition without looking at actual objects. Makes sense.

Right, exactly.
Two additional points:

1) there should be NFC to dynamic casts - for them, the __dynamic_cast_info object is initialised to say "we have a pointee object".  If that is untrue in some relevant way it's a different bug.

2) At the moment, I cannot see a way to fix this that does not involve changing the private implementation - and thus potentially impacting Objective-C.

**Comment by rjmccall** [comment]
> > I'm... not sure it's okay to change v-tables in the `std::type_info` hierarchy like this. In theory it's non-ABI and purely an internal implementation detail of the C++ runtime, but in practice there are some other subclasses out there, like in the ObjC runtime.
> 
> My, perhaps flawed, understanding is that Objective-C is supposed to inherit from the parent language and thus, absent a specification to the contrary, a bug in the exception handling here would also be a bug in the Objective-C exception handling, thus it should also import the fix)?

It's not that Objective-C doesn't want the fix, it's that Apple's Objective-C runtime (at least) has its own subclass of `std::type_info` so that it can properly interoperate with C++ exceptions (e.g. ObjC exceptions can be caught with `catch (...)`).

> (agreed that the layout change obfuscates some of the change purpose - most of it is just initialising the new bool in __dynamic_cast_info). However, if you like I can find my original patch (without the layout changes) and force-push that here?

I think that would be better, yeah.

> 2. At the moment, I cannot see a way to fix this that does not involve changing the private implementation - and thus potentially impacting Objective-C.

Let me tag in @mikeash for this.

**Comment by iains** [comment]
> > > I'm... not sure it's okay to change v-tables in the `std::type_info` hierarchy like this. In theory it's non-ABI and purely an internal implementation detail of the C++ runtime, but in practice there are some other subclasses out there, like in the ObjC runtime.
> > 
> > 
> > My, perhaps flawed, understanding is that Objective-C is supposed to inherit from the parent language and thus, absent a specification to the contrary, a bug in the exception handling here would also be a bug in the Objective-C exception handling, thus it should also import the fix)?
> 
> It's not that Objective-C doesn't want the fix, it's that Apple's Objective-C runtime (at least) has its own subclass of `std::type_info` so that it can properly interoperate with C++ exceptions (e.g. ObjC exceptions can be caught with `catch (...)`).

Right, that was what I expected;  It would be good for me to understand the constraints better (in case it opens up other opportunities for fixes).  e.g. It seems to me that pushing all state into the  `__dynamic_cast_info` might allow us to keep the private API unchanged - but it would not alter that the private implementation has changed (and the `__dynamic_cast_info` would not be interoperable with an older version).

> > (agreed that the layout change obfuscates some of the change purpose - most of it is just initialising the new bool in __dynamic_cast_info). However, if you like I can find my original patch (without the layout changes) and force-push that here?
> 
> I think that would be better, yeah.

Done, and rebased/retested (so we expect the formatting check to fail for now).

**Comment by mikeash** [comment]
libobjc has this wacky hand-written vtable: https://github.com/apple-oss-distributions/objc4/blob/objc4-906/runtime/objc-exception.mm#L183

It's mostly no-ops and relies on the fact that the calling conventions allow passing more parameters than the function actually consumes. There's one entry that actually does anything, which is `can_catch`, and that's unchanged here.

ARM64e ptrauth adds a wrinkle. Changing the signature of these methods will change the ptrauth discriminator, which will no longer match libobjc's hardcoded discriminators. That's not a big deal for `has_unambiguous_public_base`, as our version of that function just raises a fatal error anyway. Crashing due to a ptrauth mismatch would be slightly less friendly, but shouldn't happen anyway.

That's the only virtual method that changed, so I think we're all good here. libobjc might want to update its discriminator at some point, but that's just a nice-to-have, and it doesn't have to be coordinated with this change.

@rjmccall Anything I might have missed here?

**Comment by ldionne** [comment]
> apropos the build kite fails:
> 
> 1. It looks like the asan one is a silly mistake in the testcase (missing `delete o`).

Ah, I was going to ask about that. Adding the missing `delete` should solve the issue.

> 2. [edit] @ldionne  I am not sure exactly what the Apple back-deployment tests are intended to demonstrate;
>    
>    * If I build this branch on macOS 10.15 or 10.13 the testcase passes.
>    * What is the intention of the test?
>    * (and how how do I reproduce? - I work primarily on macOS and build regularly on older OS versions).


The back-deployment jobs are testing the case where you build an application (here your test) against a recent SDK (i.e. a recent version of libc++), but you specify that you will be deploying to an older version of macOS. And then you run your freshly-built application against an older dylib. So it's building against a recent libc++, but running against an old one.

This is meant to capture the use case of someone building an application on a recent system, but the application is meant to work on various older devices. In practice, we sometimes find subtle ABI breaks with these jobs.

In this case, since you are fixing an issue in `libc++abi.dylib` and testing the fix to that issue, it is expected that the test will fail if you run it against an older `libc++abi.dylib` (which doesn't contain the fix). So what I would recommend here is that you add the following annotation to your test:

```
// This test requires the fix to https://github.com/llvm/llvm-project/issues/64953, which is in libc++abi.dylib.
// The fix is not contained in older macOS system dylibs.
// XFAIL: stdlib=apple-libc++ && target={{.+}}-apple-macosx10.{{9|10|11|12|13|14|15}}
// XFAIL: stdlib=apple-libc++ && target={{.+}}-apple-macosx{{11|12|13|14}}
```

Then we will evolve the test, and when we eventually drop support for these older macOS versions, we will remove the annotation (it will take a while).

If you want to reproduce this issue, you need to be on macOS (which seems to be your case). Then you should be able to just run `./libcxx/utils/ci/run-buildbot apple-system-backdeployment-10.13` from the root of the monorepo -- that should basically mirror the job that is being run on the CI system. You can change the version from `10.13` to anything else you want (although we don't support some of the more recent versions cause I need to update our collection of old dylibs).

**Comment by iains** [comment]
@mikeash , @rjmccall 

OK:
 * So I modified this now such that the function signatures are unchanged (the virtual base cookie is passed in the `__dynamic_cast_info` object instead).   The asm actually on ly mentions the function name - but I'm expecting that means 'mangled function name'.

* the additions to the `__dynamic_cast_info` are trailing so that a callee passed a pointer to an object, but that does not know about them would not be affected (I do not think this actually matters, in reality, it's just a bit of defensive programming)

@ldionne 

Thanks for the pointers.

I was unable to reproduce the asan fail on either x86_64 macOS 14 or arm64 macOS 12.7 - so I went ahead and made a conservative change - we will have to see if the problem clears on the bot.

The other cases are fixed (only testable on x86_64 AFAICT), I see some ld64 warnings about mismatched build versions on arm64 macOS 12,7 - and when the library is missing - we then get caught be the changes that mean there's no lib in `/usr/lib/` any more.

(we still expect the formatting complaints)

**Comment by iains** [comment]
update: 
so I've rebased and done the (clang-) reformatting where I actually touched the code (and, in fact, the two places are pretty much re-written, so it should not obfuscate).  With the revised impl. there are no changes to the interfaces.  

* split out the somewhat gratuitous reformatting of the initialisers to `__dynamic_cast_info` objects [TBH, the reformatted looks a lot less readable than the original] as a second patch because they do make the patch less readable.

* could not repeat the fail to `check-generated-output` that appeared on the last push (or really see exactly how it might relate to this patch).
* If I do:
`make -C build/runtimes/runtimes-bins libcxx-generate-files` there are no changed sources.

**Comment by iains** [comment]
sure; done

**Comment by ldionne** [comment]
I added @rjmccall and @urnathan to @llvm/reviewers-libcxxabi  -- I'll let you folks determine when this is ready to be merged but I have no objection. Ping me again if you encounter issues with the CI and I'll be glad to assist.

**Comment by iains** [comment]
@ldionne well, it seems we still have one issue with the CI.  The `apple-system` test seems to install the newly-built libc++ and libc++abi, but then it runs the tests with `apple-libc++abi-shared.cfg.in` which declares: `stdlib=apple-libc++, stdlib=libc++, ` and therefore the new test XPASSes (which counts as a fail here).

Perhaps that test should really be declaring `llvm-libc++`? (but I cannot see right now where to change that).

**Comment by ldionne** [comment]
Interesting. This actually highlights a blind spot we have in the expressiveness of our Lit features. We don't have a way to express "libc++ configured as Apple system library, targeting <target>, but using the tip-of-trunk version of the library". In other words, we generally assume that `apple-system` + `target=<XYZ>` implies that we are back-deploying (i.e. running against the system library that was shipped on `<XYZ>`). I'm not sure why that never bit us, but I suspect this is because these fixes are somewhat rare.

To avoid blocking you on this (which really has nothing to do with this patch), you could just use `UNSUPPORTED:` instead of `XFAIL`, that way the test just won't run in that configuration.

**Comment by iains** [comment]
> Interesting. This actually highlights a blind spot we have in the expressiveness of our Lit features. We don't have a way to express "libc++ configured as Apple system library, targeting , but using the tip-of-trunk version of the library". In other words, we generally assume that `apple-system` + `target=<XYZ>` implies that we are back-deploying (i.e. running against the system library that was shipped on `<XYZ>`). 

in this case it was just the plain `apple-system` i.e. running natively on the box.  Given that it intentionally installs libc++ and libc++abi, (and then points to them with DYLD_LIBRARY_PATH) I guess it is intentional that this exercises the built tip of trunk.

>I'm not sure why that never bit us, but I suspect this is because these fixes are somewhat rare.

I suppose libc++abi moves slowly, not sure why it does not bite more with libc++ tho - if the assumption of the lit config is that it's the installed libs being tested, but actually we're testing the new ones.

> To avoid blocking you on this (which really has nothing to do with this patch), you could just use `UNSUPPORTED:` instead of `XFAIL`, that way the test just won't run in that configuration.

OK - I guess that means that the test will not run in any CI - but should still run when people test the library locally?

**Comment by ldionne** [comment]
> I suppose libc++abi moves slowly, not sure why it does not bite more with libc++ tho - if the assumption of the lit config is that it's the installed libs being tested, but actually we're testing the new ones.

We're compiling and linking against the new library, but we are running against the installed system one.

> 
> OK - I guess that means that the test will not run in any CI - but should still run when people test the library locally?

The test will only be skipped when we build for the Apple-system configuration, which is not most configurations. If you just take libc++ and build it out of the box on Apple platforms, you get the LLVM configuration, not the Apple System configuration (so the test would run).

**Comment by iains** [comment]
rebase,  added the UNSUPPORTED, slight amendment to the title (removed the Issue # reference).  Cannot figure out why the CI now thinks there are formatting errors:
```
llvm-issue-64953$ git clang-format
no modified files to format
llvm-issue-64953$ clang-format --version
clang-format version 17.0.2 (git@github.com:llvm/llvm-project.git 098e653a5bed2e5fb2af6ccaedf2268d7d3935fa)
```

**Comment by ldionne** [comment]
It seems like the CI passed on this a while back. Are we waiting on anything to merge this?

**Comment by iains** [comment]
> It seems like the CI passed on this a while back. Are we waiting on anything to merge this?

an ack from the ABI owners, I think :)

**Comment by rjmccall** [comment]
If the function signatures aren't changing, this definitely ought to be okay.

**Comment by iains** [comment]
I'll rebase / squash and retest - is the process then to use the "squash and merge" or is it better to commit the "old way"?

**Comment by ldionne** [comment]
Actually, we can just squash and merge right away here. If there are no merge conflicts, I don't think this needs to go through CI again.

Pressing "squash and merge" and then editing the resulting message appropriately (if it needs to be edited) is the right way to proceed nowadays.

**Comment by ldionne** [comment]
It looks like this applies cleanly onto `main`, so I'll squash and merge now.

**Pull request merged**
