### PR TITLE
[flang] Enable polymorphic lowering by default

### PR DESCRIPTION
**Pull request by jeanPerier**
Polymorphic entity lowering status is good. The main remaining TODO is to allow lowering of vector subscripted polymorphic entity, but this does not deserve blocking all application using polymorphism.

Remove experimental option and enable lowering of polymorphic entity by default.

### CODE REVIEW

**Review by clementval — APPROVED** [review]
Looks great! Thanks Jean to work on this!

**Review by kiranchandramohan — APPROVED** [review]
LGTM.

**Review by tblah — APPROVED** [review]
LGTM. On a quick run this seems to build everything I would expect it to in the gfortran test suite. When you get time please could you enable the polymorphic tests in the gfortran test suite and re-categorize the ones which now hit different TODOs.

**Comment by tblah** [comment]
A few of the tests in the gfortran-testsuite using polymorphism fail at runtime. I'm happy for this PR to be merged as it is and these bugs to be fixed later.

**Comment by jeanPerier** [comment]
Thanks a lot for testing Tom!

I did not expect issues with gfortran tests. I will look into it before merging and I made a simpler first patch thet will be less noisy to revert in case of other issues that would break the build bots: https://github.com/llvm/llvm-project/pull/83308

**Comment by tarunprabhu** [comment]
> A few of the tests in the gfortran-testsuite using polymorphism fail at runtime. I'm happy for this PR to be merged as it is and these bugs to be fixed later.

Once this is merged in, the polymorphism tests can be enabled together with the larger group of tests that I intend to enable in the next day or two.

**Pull request merged**
