### PR TITLE
[lldb][test] Fixed the test `no_unique_address-with-bitfields`

### PR DESCRIPTION
**Pull request by slydiman**
Fixed the error `unable to create target: 'No available targets are compatible with triple "x86_64-apple-macosx10.4.0"'` running `clang --target=x86_64-apple-macosx -c -gdwarf -o %t %s`.

### CODE REVIEW

**Comment by labath** [comment]
Running on Darwin is *not* required for `--target=x86_64-apple-macosx` to work. What's required is that the `X86` llvm target is configured. The right fix is to move this test into the x86 subdir.

**Comment by slydiman** [comment]
> The right fix is to move this test into the x86 subdir.

Done.

**Review by labath — APPROVED** [review]

**Comment by Michael137** [comment]
Can we do this for all the `no_unique_address-...` tests? Would be nice if they were all in the same place. I'm not sure I added `--target` in all of them, but probably should?

**Comment by labath** [comment]
I would recommend that -- then you wouldn't need to worry about how to spell [[no_unique_address]] on windows.

**Comment by Michael137** [comment]
> I would recommend that -- then you wouldn't need to worry about how to spell [[no_unique_address]] on windows.

https://github.com/llvm/llvm-project/pull/112523

**Pull request merged**
