### PR TITLE
Resolve FIXME: Look at E, not M

### PR DESCRIPTION
**Pull request by AZero13**

### CODE REVIEW

**Comment by efriedma-quic** [comment]
I assume the FIXME is referring to some deeper change here? If it were that easy, the FIXME wouldn't be there in the first place.

CC @zygoloid @rjmccall

**Comment by rjmccall** [comment]
Well, sometimes we do leave FIXMEs that end up being suprisingly easy to fix.  But what FIXME are we talking about here?  The patch doesn't remove any FIXMEs, or for that matter include any tests.

**Comment by efriedma-quic** [comment]
https://github.com/llvm/llvm-project/blob/c0f8be4fcfb725d53841d4b17a68685e33332a79/clang/lib/CodeGen/CGExpr.cpp#L277

**Comment by rjmccall** [comment]
Hmm.  Well, you'd have to ask @zygoloid what he was thinking in r183721/r183859, but I don't think it's correct in general to be looking at E (the MTE sub-expression) for most of the logic here.  IIRC, the MTE sub-expression is essentially the initializer for the materialized temporary, so it should be a pr-value, which means that for ARC (and any similar features in the future that we might add with qualifier-specific ownership) it won't have the right type information to set up the destructor for the temporary.  The MTE is going to tell us the type of the I assume that's why the proposed patch in this PR ends up ignoring the half of the function that handles the ARC qualifiers.  Maybe Richard had some better representation in mind, though.

**Comment by zygoloid** [comment]
IIRC the issue here is that in C++98, the MTE is in a "weird" place in the AST, because of the different rules governing how and when temporaries are formed. For example, for `const int &r = C().a[0];`, we'll form an MTE wrapping just the `C()` expression, converting it to an xvalue, in C++11 onwards. But in C++98, xvalues mostly don't exist, the MTE wraps the whole `C().a[0]`, and you need to call `skipRValueSubobjectAdjustments` to get the actual expression that initializes the temporary, which I guess is what `E` is here.

So I think the idea is that `E` is always the expression that initializes the temporary, and the type of `M` in C++98 might be some subobject of that, with a type that doesn't reflect properties of the temporary. So we should generally look at properties of `E`, not `M`, to understand properties of the temporary object. But in C++11 onwards I think it doesn't matter, because we always materialize immediately.

(That's mostly from memory, I might have got some details wrong.)

**Comment by rjmccall** [comment]
Hmm.  The best solution there is probably to use a consistent representation but introduce some sort of `GLValueThatTheStandardAbsurdlyPretendsIsAnRValue` (definitely the only and best word for this, ship it) that we can use as the value category.  IIRC, something similar happens in C where the standard pretends that function l-values don't exist.

**Comment by mizvekov** [comment]
> Hmm. The best solution there is probably to use a consistent representation but introduce some sort of `GLValueThatTheStandardAbsurdlyPretendsIsAnRValue` (definitely the only and best word for this, ship it) that we can use as the value category. IIRC, something similar happens in C where the standard pretends that function l-values don't exist.

IIRC GCC also implements a similar value category as an alternative to the two-phase lookup rules for implicit moves, pre-C++23. This is almost an XValue, except it binds to LValue references as well.

**Pull request closed without merging**
