### PR TITLE
[NFC][LLVM] Use namespace `Intrinsic` in `Intrinsics.cpp`

### PR DESCRIPTION
**Pull request by jurahul**
Add `using namespace Intrinsic` to Intrinsics.cpp file.

### CODE REVIEW

**Comment by jurahul** [comment]
Failures are LIT tests failures in PPC so are unrelated.

**Review by kazutakahirata — APPROVED** [review]
LGTM.  Thanks!

**Review by AlexMaclean — APPROVED** [review]
Seems reasonable to me, though I don't work on this file much

**Comment by akuegel** [comment]
Hi Rahul, it seems this is causing issues because the Intrinsic namespace also contains a memcpy. See this JAX build as an example: https://github.com/jax-ml/jax/actions/runs/11741758517/job/32711082643

Can this PR be reverted?

**Comment by jurahul** [comment]
Thanks for reverting. What is surprising to me is that I'd have though the effect of "using namespace Intrinsic" in the Intrinsic.cpp file would be on code after that statement, but it looks like from the build log that code before that is affected, which seems counterintuitive. 

https://en.cppreference.com/w/cpp/language/namespace

[using-directive](https://en.cppreference.com/w/cpp/language/namespace#Using-directives): From the point of view of unqualified [name lookup](https://en.cppreference.com/w/cpp/language/lookup) of any name after a using-directive and until the end of the scope in which it appears, every name from ns-name is visible as if it were declared in the nearest enclosing namespace which contains both the using-directive and ns-name.

**Pull request merged**
