### PR TITLE
[llvm] Fix ObjectSizeOffsetVisitor behavior in exact mode upon negati…

### PR DESCRIPTION
**Pull request by serge-sans-paille**
…ve offset

In Exact mode, the approximation of returning (0,0) is invalid. It only holds in min/max mode.

### CODE REVIEW

**Comment by nathanchance** [comment]
Hmmm, applying this on top of current main (32913724acf9e02beed46999fee1424086b8c884) and doing my full set of builds, I actually see a new crash:

```
llvm/lib/Analysis/MemoryBuiltins.cpp:569: APInt getSizeWithOverflow(const SizeOffsetAPInt &): Assertion `!Offset.isNegative() && "size for a pointer before the allocated object is ambiguous"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang-20 … io_uring/kbuf.c
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module '/home/nathan/cbl/src/clean/linux/io_uring/kbuf.c'.
4.      Running pass 'Split GEPs to a variadic base and a constant offset for better CSE' on function '@io_provide_buffers'
…
```

It’s quite late for me, so I will try to get a reduced reproducer as soon as I am able to tomorrow.

**Comment by nathanchance** [comment]
```c

struct {
  int list;
} *io_add_buffers_bufs[4];
short io_add_buffers_buf_1, io_add_buffers_pbuf_1;
long io_add_buffers_pbuf_0;
void list_add_tail(int *);
int kmem_cache_alloc_bulk_noprof();
int io_add_buffers() {
  long addr = io_add_buffers_pbuf_0;
  int bid = io_add_buffers_pbuf_1,
      allocated = ({
        ({
          typeof(0) _res = kmem_cache_alloc_bulk_noprof();
          _res;
        });
      });
  while (allocated)
    list_add_tail(&io_add_buffers_bufs[--allocated]->list);
  addr = addr;
  io_add_buffers_buf_1 = bid;
  return 0;
}
```

```
$ clang --target=powerpc-linux-gnu -O2 -c -o /dev/null kbuf.i
clang: llvm/lib/Analysis/MemoryBuiltins.cpp:569: APInt getSizeWithOverflow(const SizeOffsetAPInt &): Assertion `!Offset.isNegative() && "size for a pointer before the allocated object is ambiguous"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang --target=powerpc-linux-gnu -O2 -c -o /dev/null kbuf.i
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'kbuf.i'.
4.      Running pass 'Split GEPs to a variadic base and a constant offset for better CSE' on function '@io_add_buffers'
…
```

**Comment by serge-sans-paille** [comment]
Got it! The assert no longer hold with the change, I've updated the patch, can you confirm it's all fine on your side?

**Comment by nathanchance** [comment]
The latest revision passed my initial smoke test build. My full matrix of build and boots is running now, I’ll report back if there are any problems but assume silence means all is well.

**Pull request merged**
