### PR TITLE
Add explicit conversion to fix arm64 builds.

### PR DESCRIPTION
**Pull request by MosheBerman**
Fixes issue preventing builds on ARM-based Macs.

https://github.com/llvm/llvm-project/issues/82205.

### CODE REVIEW

**Comment by MosheBerman** [comment]
@michaelrj-google

**Comment by MosheBerman** [comment]
Turned off the "keep emails private." Do I need to submit this again?

**Comment by jhuber6** [comment]
No, it should be fine. The private email rule is mainly because if the email is private then the author won't get emails if a bot breaks.

**Review by jhuber6 — COMMENTED** [review]
Unrelated, but this and others should probably use `LIBC_INLINE_ASM`

**Comment by MosheBerman** [comment]
@jhuber6 I'm not familiar enough to know what should be using `LIBC_INLINE_ASM` but I'm curious what you mean. Can you tell me what it's for and where it would apply in this file? (Not necessarily this PR.)

**Review by michaelrj-google — APPROVED** [review]
I don't think we're requiring `LIBC_INLINE_ASM` right now, but it's a macro for marking asm calls, defined here: https://github.com/llvm/llvm-project/blob/main/libc/src/__support/macros/attributes.h#L24

I remember there being some discussion around deprecating it, since marking all of our asm as volatile pessimizes any optimization. In theory it would allow a user to redefine that macro and set their own asm attributes.

Regardless, it's out of scope for this patch. This patch is fine to land as is. If you don't have commit access then just ping me and I'll land it for you.

**Comment by moshe-foreflight** [comment]
Yeah I don't have access. Thanks for merging!

**Pull request merged**
