### PR TITLE
[RISCV] Add areInlineCompatible for riscv target

### PR DESCRIPTION
**Pull request by jacquesguan**
Inline a callee if its target-features are a subset of the callers target-features.

### CODE REVIEW

**Review by lukel97 — COMMENTED** [review]
Does this mean we'll inline a function even if it we disabled an extension via an overriding target attribute arch string? e.g.

```c
__attribute__((target("arch=rv64i")))
float foo(float x) {
  return x + 42;
}

float bar(float x) {
  return foo(x);
}
```

foo will now be inlined if we compile with `-march=rv64if`. But I presume that's fine given that this seems to be inline with what other targets do

**Comment by jacquesguan** [comment]
> Does this mean we'll inline a function even if it we disabled an extension via an overriding target attribute arch string? e.g.
> 
> ```c
> __attribute__((target("arch=rv64i")))
> float foo(float x) {
>   return x + 42;
> }
> 
> float bar(float x) {
>   return foo(x);
> }
> ```
> 
> foo will now be inlined if we compile with `-march=rv64if`. But I presume that's fine given that this seems to be inline with what other targets do

Yes, in my work, there are some similar cases. I have some common tool functions and want to inline them into some users with 
 different target attributes.

**Review by topperc — APPROVED** [review]
LGTM

**Review by lukel97 — APPROVED** [review]
LGTM

**Pull request merged**
