### PR TITLE
[PowerPC] Support -mno-red-zone option

### PR DESCRIPTION
**Pull request by ecnelises**

### CODE REVIEW

**Review by chenzheng1030 — COMMENTED** [review]
Are there backend cases that show with -disable-red-zone, the final assembly is still correct?

**Comment by ecnelises** [comment]
No. `-disable-red-zone` does nothing but add `noredzone` IR attribute to functions. We need to add cases to test for `noredzone` behavior on PPC (arm and x86 have).

**Comment by chenzheng1030** [comment]
> No. `-disable-red-zone` does nothing but add `noredzone` IR attribute to functions. We need to add cases to test for `noredzone` behavior on PPC (arm and x86 have).

Yeah, go ahead to add some backend tests first to make sure we have good functionality for `noredzone` attribute. Thanks.

**Review by chenzheng1030 — APPROVED** [review]
The small LIT cases seem all good. Based on that, the patch LGTM.

If possible, can you run some big applications with `-mno-redzone` to double confirm the functionality? I am not so sure about its quality since the option seems not be tested on PPC at all...

**Pull request merged**
