### PR TITLE
[PowerPC][LLC] Utilize PPC::getNormalizedPPCTargetCPU() to set CPU

### PR DESCRIPTION
**Pull request by diggerlin**
Utilize common API in PPCTargetParser (https://github.com/llvm/llvm-project/pull/97541) to set default CPU with same interfaces for LLC.
This will update AIX default CPU to pwr7 and LoP powerppc64 default CPU to ppc64.

### CODE REVIEW

**Review by daltenty — APPROVED** [review]
LGTM, thanks.

Maybe the change to make `powerpc64-unknown-unknown` default to `ppc64` generic CPU instead of the `ppc` generic CPU is worth documenting as a release note

**Review by lei137 — COMMENTED** [review]
I think it's better to split this into 2 patches.  
1. update affected tc to add -mcpu-ppc explicitly in prep for this change.
2. current code and relevant tc update + release note update.

**Comment by lei137** [comment]
Description require an update since I don't see any CPU features being set.
```
Utilize common API in PPCTargetParser (https://github.com/llvm/llvm-project/pull/97541) to set default CPU with same interfaces for LLC.
This will update AIX default CPU to pwr7 and LoP powerppc64 default CPU to ppc64.
```

**Review by lei137 — APPROVED** [review]
Thanks for addressing all the comments!
LGTM

**Pull request merged**
