### PR TITLE
[libc][z/OS] Remove ASCII trick to fix EBDIC std::from_char

### PR DESCRIPTION
**Pull request by zibi2**
This PR will fix the following lit in all EBCDIC variations on z/OS:
`std/utilities/charconv/charconv.from.chars/floating_point.pass.cpp`

The trick to test for `e` and `E` is working only in ASCII.
The fix is to simply test for both lower and upper case exponent letter `e` and `E` respectfully.

### CODE REVIEW

**Review by abhina-sree — APPROVED** [review]
LGTM

**Review by michaelrj-google — APPROVED** [review]
Thanks for catching this, I'll see if there's anywhere else that could use this sort of cleanup.

**Comment by zibi2** [comment]
CI failed twice at unrelated `generate_test_report.py` step. I'm going to merge this now.

**Comment by nickdesaulniers** [comment]
@zibi2 what's a target triple we can use to test EBDIC? `--target=s390x-???`

**Comment by perry-ca** [comment]
(Zibi's off for a couple days.  I'll answer in the meantime)
You don't really need to use a particular target triple.  To compile something in EBCDIC you'll need:

1. the -fexec-charset option (see https://github.com/llvm/llvm-project/pull/74516 & https://github.com/abhina-sree/llvm-project/pull/1) or #pragma convert (follow on to these)
2. A way to got through the preprocessing paths for `defined(__MVS__)` && `!defined(__NATIVE_ASCII_F)`.  This will then depend on macros or values defined in the z/OS headers (eg. `static const mask space  = __ISSPACE;`)

This would be a specific build of libc++ for EBCDIC.  We haven't tried enabling EBCDIC on other platforms.  In theory it should work.

**Pull request merged**
