### PR TITLE
[CodeGen] Renumber slot indexes before register allocation

### PR DESCRIPTION
**Pull request by jayfoad**
RegAllocGreedy uses SlotIndexes::getApproxInstrDistance to approximate
the length of a live range for its heuristics. Renumbering all slot
indexes with the default instruction distance ensures that this estimate
will be as accurate as possible, and will not depend on the history of
how instructions have been added to and removed from SlotIndexes's maps.

This also means that enabling -early-live-intervals, which runs the
SlotIndexes analysis earlier, will not cause large amounts of churn due
to different register allocator decisions.

### CODE REVIEW

**Comment by jayfoad** [comment]
https://llvm-compile-time-tracker.com/ shows a geomean 0.00% change.

TODO: I still need to update ~15 tests with manual checks.

**Comment by jayfoad** [comment]
> TODO: I still need to update ~15 tests with manual checks.

All tests updated now.

**Comment by arsenm** [comment]
I've thought about doing this but it only makes the problem harder to observe. It still happens when renumbering occurs during allocation

**Comment by jayfoad** [comment]
> I've thought about doing this but it only makes the problem harder to observe.

I don't think that's a bad thing. I think this makes things better, even if they're still not perfect.

**Comment by perlfu** [comment]
This seems reasonable to me.

For AMDGPU graphics, this seems like it yields a very minor reduction in mean VGPR usage, and slightly greater reduction in mean SGPR usage.  There are some a handful of edges case where VGPR usage increased significantly (20 VGPRs).  I guess this is unsurprising given it tweaks a heuristic input.

**Comment by jayfoad** [comment]
Rebased on #66627 which allowed me to update `test/CodeGen/X86/AMX/amx-greedy-ra-spill-shape.ll` automatically with no need for manual tweaks to the checks.

**Comment by qcolombet** [comment]
I'm on the fence with that change.

My concerns is that it adds compile time and may trigger other renumbering down the line.
The compile time impact is probably in the noise (@jayfoad have you double check?) and initially at least `getApproxInstrDistance` makes more sense.

Could you rename `renumberAllIndexes` into `densifyIndices` or something that conveys that we're packing the indices in a contiguous way. Here I'd like to avoid having a name that collide with `renumberIndexes`.

**Comment by jayfoad** [comment]
> Could you rename `renumberAllIndexes` into `densifyIndices` or something that conveys that we're packing the indices in a contiguous way. Here I'd like to avoid having a name that collide with `renumberIndexes`.

How about `packIndexes` or `compactIndexes`? (Using "compact" as a verb not a noun, in case that's not obvious.)

**Comment by qcolombet** [comment]
> > Could you rename `renumberAllIndexes` into `densifyIndices` or something that conveys that we're packing the indices in a contiguous way. Here I'd like to avoid having a name that collide with `renumberIndexes`.
> 
> How about `packIndexes` or `compactIndexes`? (Using "compact" as a verb not a noun, in case that's not obvious.)

Both sounds good to me. Slight preference for `packIndexes`.

**Comment by qcolombet** [comment]
> > My concerns is that it adds compile time and may trigger other renumbering down the line. The compile time impact is probably in the noise (@jayfoad have you double check?)
> 
> Yes, see earlier comment :)
> 
> > https://llvm-compile-time-tracker.com/ shows a geomean 0.00% change.
> 
> This was based on the "renumber-all-slotindexes" branch here: https://llvm-compile-time-tracker.com/?config=NewPM-O3&stat=instructions%3Au&remote=jayfoad

Sorry, seen it then forgot about it :P.

**Comment by jayfoad** [comment]
Renamed renumberAllIndexes -> packIndexes.

**Review by perlfu — APPROVED** [review]
LGTM - but probably wait a little in case @qcolombet has further input

**Review by qcolombet — APPROVED** [review]

**Comment by jayfoad** [comment]
Merged manually.

**Pull request closed without merging**
