### PR TITLE
 [OpenMP] Introduce the KernelLaunchEnvironment as implicit argument

### LINKED ISSUE #70249: [OpenMP] incorrect concurrent target reduction
```
#include <iostream>
#include <vector>

#define N 4

int main()
{
  std::vector<int> avec(N);
  int* a = avec.data();
  #pragma omp parallel for
  for(int i = 0; i < N; i++)
  {
    a[i] = 0;
    #pragma omp target teams distribute parallel for reduction(+:a[i])
    for(int j =0 ;j< N; j++)
      a[i] += 1;
  }

  std::cout << "results:";
  for(int i = 0; i < N; i++)
    std::cout << " " << a[i];
  std::cout << std::endl;
}
```
running `clang++ -fopenmp --offload-arch=sm_80 main.cpp && ./a.out`
expect
```
results: 4 4 4 4
```
but I got random failure
```
results: 0 4 0 0
results: 4 0 4 0
results: 4 0 4 0
```

Turning on debugging info
```
OMP_TARGET_OFFLOAD=mandatory OMP_NUM_THREADS=32 LIBOMPTARGET_DEBUG=1 ./a.out >& out && grep "Moving 4 bytes\|result" out
Libomptarget --> Moving 4 bytes (hst:0x00005572a0d9c27c) -> (tgt:0x00007f7112600000)
Libomptarget --> Moving 4 bytes (hst:0x00005572a0d9c278) -> (tgt:0x00007f7112600200)
Libomptarget --> Moving 4 bytes (hst:0x00005572a0d9c274) -> (tgt:0x00007f7112600400)
Libomptarget --> Moving 4 bytes (hst:0x00005572a0d9c270) -> (tgt:0x00007f7112600600)
Libomptarget --> Moving 4 bytes (tgt:0x00007f7112600000) -> (hst:0x00005572a0d9c27c)
Libomptarget --> Moving 4 bytes (tgt:0x00007f7112600400) -> (hst:0x00005572a0d9c274)
Libomptarget --> Moving 4 bytes (tgt:0x00007f7112600600) -> (hst:0x00005572a0d9c270)
Libomptarget --> Moving 4 bytes (tgt:0x00007f7112600200) -> (hst:0x00005572a0d9c278)
results: 4 0 4 0
```
Mapping and transfers seem OK to me. The failure was miserable.

setting `OMP_NUM_THREADS=1` the test passes reliably.

### PR DESCRIPTION
**Pull request by jdoerfert**
The KernelEnvironment is for compile time information about a kernel. It
allows the compiler to feed information to the runtime. The
KernelLaunchEnvironment is for dynamic information *per* kernel launch.
It allows the rutime to feed information to the kernel that is not
shared with other invocations of the kernel. The first use case is to
replace the globals that synchronize teams reductions with per-launch
versions. This allows concurrent teams reductions. More uses cases will
follow, e.g., per launch memory pools.

Fixes: https://github.com/llvm/llvm-project/issues/70249

### CODE REVIEW

**Comment by shiltian** [comment]
Tests in `mlir` have to be updated as well.

**Comment by jhuber6** [comment]
Small change that affects a lot of tests. LG once these are fixed:
```
MLIR :: Target/LLVMIR/omptarget-region-device-llvm.mlir
MLIR :: Target/LLVMIR/omptarget-byref-bycopy-generation-device.mlir
MLIR :: Target/LLVMIR/omptarget-declare-target-llvm-device.mlir
```

**Review by jhuber6 — APPROVED** [review]
LG

**Comment by ronlieb** [comment]
performance degradation observed for this patch on trunk build :  hpc2021 8 mpi210's reference run 
518.tealeaf   10.8%
534.hpgmg    7.3%

**Comment by dhruvachak** [comment]
With reference to the performance degradation, this patch introduces an additional allocation/data-submit/deallocation for every kernel (GenericKernelTy::getKernelLaunchEnvironment(), PluginInterface.cpp).

Analysis shows that this overhead appears to be the primary reason for the perf degradation. Is it possible to limit this additional overhead only when we need it? For example, can it be avoided for non-reduction kernels?

@jdoerfert

**Comment by ronlieb** [comment]
@jdoerfert   please respond to our comments about peformance degradation ?

**Comment by ronlieb** [comment]
> performance degradation observed for this patch on trunk build : hpc2021 8 mpi210's reference run 518.tealeaf 10.8% 534.hpgmg 7.3%

both of these benchmarks which exhibited performance regressions, contain reductions.

**Comment by jplehr** [comment]
This was brought up and discussed in the weekly meeting.

**Comment by dhruvachak** [comment]
After https://github.com/llvm/llvm-project/pull/73864, only reduction kernels may have the additional data submit for the kernel launch environment. If you have an INFO message like in https://github.com/llvm/llvm-project/pull/74030, you will see this additional INFO message 
```
"PluginInterface" device 0 info: Copying data from host to device, HstPtr=0x00007fff40332450, TgtPtr=0x00007f46a0401000, Size=16, Name=KernelLaunchEnv
"PluginInterface" device 0 info: Launching kernel __omp_offloading_811_2ea0026_main_l19 with 416 blocks and 256 threads in SPMD mode
```

For example, using https://github.com/ROCm-Developer-Tools/aomp/blob/aomp-dev/test/smoke/reduction_teams_distribute_parallel/reduction_teams_distribute_parallel.c

```
$ clang -O2 -fopenmp --offload-arch=gfx90a reduction_teams_distribute_parallel.c -o reduction_teams_distribute_parallel
$ LIBOMPTARGET_INFO=-1 ./reduction_teams_distribute_parallel
```
@jdoerfert The above can be used as a repro.

**Comment by ronlieb** [comment]
original perf regressions seem recovered enough, thx.
appreciate the info message being added for future triage...

**Pull request merged**
