### PR TITLE
adds additional information to the ProcessInfo object for elf processes

### PR DESCRIPTION
**Pull request by feg208**
This adds some additional bits into a ProcessInfo structure that will be of use in filling structs in an elf core file. This is a demand for implementing process save-core

### CODE REVIEW

**Comment by jimingham** [comment]
These seem like fairly POSIX-y bits of data, is there not a Posix way to get these (so other posix systems will also get this info?)

Also, it looks like you added user time and system time information, but you didn't test that those get valid values.

**Comment by feg208** [comment]
> These seem like fairly POSIX-y bits of data, is there not a Posix way to get these (so other posix systems will also get this info?)

Not that I know of for arbitrary processes in linux. fwiw the original code without these values got similar bits out of the proc filesystem

> 
> Also, it looks like you added user time and system time information, but you didn't test that those get valid values.

I did not. My concern here is that this would make for flaky tests. The issue is that these times are going to be very dependent on the cpus they are scheduled to, what else is running on that same machine and so on. I guess we could do a bunch of stuff to pin the unit test process in place and make it more controllable but that tends to imply permissions for the host executing the unit test. Or maybe you were thinking of another way? I am all ears if so.

**Comment by jimingham** [comment]
> On Apr 16, 2024, at 5:17 PM, Fred Grim ***@***.***> wrote:
> 
> 
> These seem like fairly POSIX-y bits of data, is there not a Posix way to get these (so other posix systems will also get this info?)
> 
> Not that I know of for arbitrary processes in linux. fwiw the original code without these values got similar bits out of the proc filesystem
> 
That's sad, but not your doing...

> Also, it looks like you added user time and system time information, but you didn't test that those get valid values.
> 
> I did not. My concern here is that this would make for flaky tests. The issue is that these times are going to be very dependent on the cpus they are scheduled to, what else is running on that same machine and so on. I guess we could do a bunch of stuff to pin the unit test process in place and make it more controllable but that tends to imply permissions for the host executing the unit test. Or maybe you were thinking of another way? I am all ears if so.
> 

The user and system times should be monotonically increasing.  So you could stop at a breakpoint, fetch the times, then run your program through a little spin loop to burn some CPU before hitting a second breakpoint.   Then get the times again and assert that they are > the first set. You could also set a timer in the test between the first and second stop and assert that the difference in system and user time is less than or equal to the timer difference.  A single threaded program can only run on one core at a time, so that should always be true.

Jim

**Comment by emaste** [comment]
> is there not a Posix way to get these

Not really. On FreeBSD these generally come from sysctl(s).

Of the ones added in this pull request SetParentProcessID is already handled on FreeBSD, while SetProcessGroupID, SetProcessSessionID, SetUserTime, SetSystemTime, SetCumulativeUserTime, SetCumulativeSystemTime are not

**Comment by feg208** [comment]
> The user and system times should be monotonically increasing. So you could stop at a breakpoint, fetch the times, then run your program through a little spin loop to burn some CPU before hitting a second breakpoint. Then get the times again and assert that they are > the first set. You could also set a timer in the test between the first and second stop and assert that the difference in system and user time is less than or equal to the timer difference. A single threaded program can only run on one core at a time, so that should always be true. 


Ok let me add a test along these lines. I'll run the test a bunch locally and in this pr to make sure I don't make a mess

**Comment by feg208** [comment]
> The user and system times should be monotonically increasing. So you could stop at a breakpoint, fetch the times, then run your program through a little spin loop to burn some CPU before hitting a second breakpoint. Then get the times again and assert that they are > the first set. You could also set a timer in the test between the first and second stop and assert that the difference in system and user time is less than or equal to the timer difference. A single threaded program can only run on one core at a time, so that should always be true.

I added a test for user time. System time seems really likely to be flaky in the unittest. It'll increase with kernel time. However if I use side-effect free system calls like getpid() to try and increase that counter it seems like that'll move around a lot from different kernels on different machines

**Comment by jimingham** [comment]
That test looks good.  It seems unlikely that you would buggily always produce monotonically increasing times...

Not to be a pest, but since this info is only provided on Linux, we should maybe add a test to make sure that asking for this information on systems that don't provide it fails gracefully?

**Comment by jimingham** [comment]
> > The user and system times should be monotonically increasing. So you could stop at a breakpoint, fetch the times, then run your program through a little spin loop to burn some CPU before hitting a second breakpoint. Then get the times again and assert that they are > the first set. You could also set a timer in the test between the first and second stop and assert that the difference in system and user time is less than or equal to the timer difference. A single threaded program can only run on one core at a time, so that should always be true.
> 
> I added a test for user time. System time seems really likely to be flaky in the unittest. It'll increase with kernel time. However if I use side-effect free system calls like getpid() to try and increase that counter it seems like that'll move around a lot from different kernels on different machines

It should never decrease, however.  If you were just getting garbage values, then there should be a roughly even chance the second value will be less than the first.  So this still gives some confidence this isn't totally bogus...

**Comment by feg208** [comment]
> That test looks good. It seems unlikely that you would buggily always produce monotonically increasing times...
> 
> Not to be a pest, but since this info is only provided on Linux, we should maybe add a test to make sure that asking for this information on systems that don't provide it fails gracefully?

Not at all. I'll add it

**Comment by feg208** [comment]
> That test looks good. It seems unlikely that you would buggily always produce monotonically increasing times...
> 
> Not to be a pest, but since this info is only provided on Linux, we should maybe add a test to make sure that asking for this information on systems that don't provide it fails gracefully?

Actually looking at lldb/unittest/Host/CMakeLists.txt I see:
```
if (CMAKE_SYSTEM_NAME MATCHES "Linux|Android")
    list(APPEND FILES
      linux/HostTest.cpp
      linux/SupportTest.cpp
 )
endif()
``` 

which should ensure the test is never built nor executed outside of linux

**Comment by feg208** [comment]
> It should never decrease, however. If you were just getting garbage values, then there should be a roughly even chance the second value will be less than the first. So this still gives some confidence this isn't totally bogus...

For sure. My concern is that it wouldn't increase either. The granularity is microseconds but with a call like getpid() for example the kernel might just return a cached value which, I assume after enough loops, would increase the timer but what is enough? And enough will change I think as build environments get faster machines faster kernels and so on.

**Comment by jimingham** [comment]
Yes, you'd have to put this test into a host test for a system that doesn't support this, like use the Posix one or make one for the Windows or Darwin Hosts.

Jim

**Comment by feg208** [comment]
> Yes, you'd have to put this test into a host test for a system that doesn't support this, like use the Posix one or make one for the Windows or Darwin Hosts.

Done!

**Review by jimingham — APPROVED** [review]
LGTM

**Comment by JDevlieghere** [comment]
Can we get (a subset) of this information on Darwin? I understand it's only necessary for ELF core files, and from the discussion that there's no standard POSIX way to get this, but it still feels a bit unfortunate to implement all these methods but only implement this for one specific platform.

**Pull request merged**
