### PR TITLE
[asan] Enable StackSafetyAnalysis by default

### PR DESCRIPTION
**Pull request by MaskRay**
StackSafetyAnalysis determines whether stack-allocated variables are
guaranteed to be safe from memory access bugs and enables the removal of
certain unneeded instrumentations.
(hwasan enables StackSafetyAnalysis in https://reviews.llvm.org/D108381)

In a release build of clang, text sections are 9% smaller.

Test updates:

* asan-stack-safety.ll: test the -asan-use-stack-safety=1 default
* lifetime-uar-uas.ll: switch to an indexed store to prevent
  StackSafetyAnalysis from optimizing out instrumentation for %c
* alloca_vla_interact.cpp: add a load to prevent StackSafetyAnalysis
  from optimizing out `__asan_alloca_poison` for the VLA `array`
* scariness_score_test.cpp: add -asan-use-stack-safety=0 to make a load
  of a `__asan_poison_memory_region`-poisoned local variable fail as
  intended.
* other .ll tests: add -asan-use-stack-safety=0

### CODE REVIEW

**Review by kstoimenov — APPROVED** [review]

**Comment by ZequanWu** [comment]
Heads up! This causes clang crash:
cmd:
```
clang++ "-cc1" "-triple" "x86_64-apple-macosx10.15.0" "-Wundef-prefix=TARGET_OS_" "-Werror=undef-prefix" "-Wdeprecated-objc-isa-usage" "-Werror=deprecated-objc-isa-usage" "-emit-obj" "-femit-dwarf-unwind=no-compact-unwind" "-disable-free" "-clear-ast-before-backend" "-main-file-name" "glslang_lex_autogen.cpp" "-mrelocation-model" "pic" "-pic-level" "2" "-fmerge-all-constants" "-fno-delete-null-pointer-checks" "-mframe-pointer=all" "-relaxed-aliasing" "-ffp-contract=off" "-fno-rounding-math" "-funwind-tables=2" "-target-sdk-version=14.0" "-fcompatibility-qualified-id-block-type-checking" "-fvisibility-inlines-hidden-static-local-var" "-fbuiltin-headers-in-system-modules" "-target-cpu" "penryn" "-tune-cpu" "generic" "-debug-info-kind=line-tables-only" "-dwarf-version=4" "-debugger-tuning=lldb" "-fdebug-compilation-dir=/Volumes/Work/s/w/ir/cache/builder/src/out/Release" "-target-linker-version" "820.1" "-mllvm" "-crash-diagnostics-dir=../../tools/clang/crashreports" "-fcoverage-compilation-dir=/Volumes/Work/s/w/ir/cache/builder/src/out/Release" "-nostdinc++" "-D" "ANGLE_ENABLE_ESSL" "-D" "ANGLE_ENABLE_GLSL" "-D" "MEMORY_TOOL_REPLACES_ALLOCATOR" "-D" "ADDRESS_SANITIZER" "-D" "__STDC_CONSTANT_MACROS" "-D" "__STDC_FORMAT_MACROS" "-D" "_LIBCPP_HARDENING_MODE=_LIBCPP_HARDENING_MODE_EXTENSIVE" "-D" "CR_XCODE_VERSION=1500" "-D" "CR_CLANG_REVISION=\"llvmorg-18-init-16856-gd1ecd12f-0\"" "-D" "_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS" "-D" "_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS" "-D" "CR_LIBCXX_REVISION=e4aac3ace5ad6e3737740daee3afeaa9c9ab0360" "-D" "NDEBUG" "-D" "NVALGRIND" "-D" "DYNAMIC_ANNOTATIONS_ENABLED=0" "-D" "ANGLE_OUTSIDE_WEBKIT" "-D" "ANGLE_DELEGATE_WORKERS=1" "-D" "ANGLE_USE_ABSEIL" "-D" "ABSL_ALLOCATOR_NOTHROW=1" "-D" "__DATE__=" "-D" "__TIME__=" "-D" "__TIMESTAMP__=" "-O2" "-Wall" "-Wextra" "-Wimplicit-fallthrough" "-Wextra-semi" "-Wunreachable-code-aggressive" "-Wthread-safety" "-Wunguarded-availability" "-Wno-missing-field-initializers" "-Wno-unused-parameter" "-Wno-psabi" "-Wloop-analysis" "-Wno-unneeded-internal-declaration" "-Wenum-compare-conditional" "-Wno-ignored-pragma-optimize" "-Wno-deprecated-builtins" "-Wno-bitfield-constant-conversion" "-Wno-deprecated-this-capture" "-Wno-invalid-offsetof" "-Wno-vla-extension" "-Wno-thread-safety-reference-return" "-Wshadow" "-Wno-builtin-macro-redefined" "-Wheader-hygiene" "-Wstring-conversion" "-Wtautological-overlap-compare" "-Wexit-time-destructors" "-Wglobal-constructors" "-Wbad-function-cast" "-Wconditional-uninitialized" "-Wextra-semi-stmt" "-Wfloat-conversion" "-Winconsistent-missing-destructor-override" "-Wmissing-field-initializers" "-Wnewline-eof" "-Wnon-virtual-dtor" "-Wredundant-parens" "-Wreturn-std-move" "-Wshadow" "-Wshadow-field" "-Wtautological-type-limit-compare" "-Wundefined-reinterpret-cast" "-Wunneeded-internal-declaration" "-Wunused-but-set-variable" "-Wsuggest-destructor-override" "-Wsuggest-override" "-Wparentheses" "-Wrange-loop-analysis" "-Wstrict-prototypes" "-Wunreachable-code-aggressive" "-Wshorten-64-to-32" "-Wno-c++11-narrowing-const-reference" "-Wno-trigraphs" "-std=c++20" "-fdeprecated-macro" "-ferror-limit" "19" "-fvisibility=hidden" "-fvisibility-inlines-hidden" "-fsanitize=address" "-fno-sanitize-memory-param-retval" "-fsanitize-address-use-after-scope" "-fsanitize-address-globals-dead-stripping" "-fno-assume-sane-operator-new" "-stack-protector" "1" "-fblocks" "-fencode-extended-block-signature" "-fno-rtti" "-fregister-global-dtors-with-atexit" "-fgnuc-version=4.2.1" "-fno-implicit-modules" "-fmax-type-align=16" "-Qn" "-fcolor-diagnostics" "-vectorize-loops" "-vectorize-slp" "-mllvm" "-instcombine-lower-dbg-declare=0" "-mllvm" "-split-threshold-for-reg-with-hint=0" "-fcomplete-member-pointers" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-x" "c++" "glslang_lex_autogen-7bfb0a.cpp"
```
Attached source code: [glslang_lex_autogen-7bfb0a.txt](https://github.com/llvm/llvm-project/files/13906543/glslang_lex_autogen-7bfb0a.txt) (Since it doesn't allow me to attach file ends with .cpp, I changed the suffix to .txt)

**Comment by ZequanWu** [comment]
Reverted at e7f794875169811f3801fad6d40bb9fe833e1a69. Will file an issue to track it once reducing is done.

**Comment by MaskRay** [comment]
> Reverted at [e7f7948](https://github.com/llvm/llvm-project/commit/e7f794875169811f3801fad6d40bb9fe833e1a69). Will file an issue to track it once reducing is done.

I've reduced it. It's code like below where a  memcpy confused StackSafetyAnalysis in a  macOS+libc++ build.

```cpp
int floatsuffix_check(TParseContext *context)
{
    struct yyguts_t *yyg = (struct yyguts_t *)context->getScanner();

    if (context->getShaderVersion() < 300)
    {
        context->error(*yyg->yylloc_r, "Floating-point suffix unsupported prior to GLSL ES 3.00", yyg->yytext_r);
        return 0;
    }

    std::string text = yyg->yytext_r;
    text.resize(text.size() - 1);    ///////// 
    if (!strtof_clamp(text, &(yyg->yylval_r->lex.f)))
        yyg->yyextra_r->warning(*yyg->yylloc_r, "Float overflow", yyg->yytext_r);

    return (FLOATCONSTANT);
}
```

**Comment by vitalybuka** [comment]
I guess we we should avoid ClUseStackSafety for -O0

**Comment by MaskRay** [comment]
> I guess we we should avoid ClUseStackSafety for -O0

There may be two competing goals. The traditional one that `-O0` should run very few optimizations and a practical one that instrumentations should reduce code size increase.

`[asan] Skip promotable allocas to improve performance at -O0` runs at `-O0`. (#77221 is discussing whether it should run at `-O0`). We have other optimizations e.g. within a basic block, two addresses do not need to be instrumented repeatedly unless they are separated by a call instruction.

Perhaps it isn't too bad to run StackSafetyAnalysis at -O0 for consistent with other -O levels?

**Comment by uweigand** [comment]
This now causes failures in the SystemZ build bot:
https://lab.llvm.org/buildbot/#/builders/94/builds/18295

**Comment by uweigand** [comment]
> This now causes failures in the SystemZ build bot: https://lab.llvm.org/buildbot/#/builders/94/builds/18295

Looking at this a bit more, before this patch the stack alignment test passes because the IR is instrumented to include a call to `__asan_alloca_poison` using a 32-byte aligned alloca.  *With* this patch, that code is missing completely and there is no 32-byte aligned alloca, and therefore the whole stack is never re-aligned to a 32-byte boundary.

Not sure why the `__asan_alloca_poison` call is missing now ...

**Comment by NancyWang2019** [comment]
@MaskRay can you help address https://github.com/llvm/llvm-project/pull/77210#issuecomment-1893860870 , test cases are failing on LoZ buildbot. Thanks

**Comment by MaskRay** [comment]
> @MaskRay can you help address [#77210 (comment)](https://github.com/llvm/llvm-project/pull/77210#issuecomment-1893860870) , test cases are failing on LoZ buildbot. Thanks

    The test (from https://reviews.llvm.org/D7098) is about the interaction
    of VLA and alloca where the VLA causes alloca to have the same address.
    This is mostly about behavior checking and less about instrumentation
    correctness, so I think it is fair to disable it for a platform that
    does not work after StackSafetyAnalysis is enabled by default (#77210).

Disabled the test on `s390{{.*}}` in c875567af352716e703a49c9445f5dc1d3cf0063

**Comment by uweigand** [comment]
@MaskRay I've done a bit more analysis now, and what seems to be going on is that with stack safety analysis off, this check:
```
  char array[len];
  assert(!(reinterpret_cast<uintptr_t>(array) & 31L));
```
succeeds because the VLA allocation gets instrumented, and therefore the VLA address is guaranteed to be 32-byte aligned.

However, with stack safety analysis *on*, that analysis (correctly) detects that the VLA is actually never accessed, and therefore the allocation does not need be instrumented.  Because it is isn't instrumented, it remains a regular alloca without special alignment requirements.

Therefore, there is no guarantee that the assert will succeed.  If the incoming stack pointer happened to already be 32-byte aligned, it will succeed - otherwise (and that's the cases where we're seeing failures on s390x), it will not.

This seems to be a platform-independent bug that just happens to be visible only on some platforms sometimes.

**Comment by MaskRay** [comment]
@uweigand 

Thanks for the analysis. `bot = alloca(i);` is a dynamic alloca that cannot be optimized out.
It triggers `FunctionStackPoisoner::createDynamicAllocasInitStorage`, which creates an alloca of 32-byte alignment.
In x86-64, aarch64, riscv, and others, the alloca translates to a `StackObject` of 32-byte alignment.
When `char array[len]` is not instrumented (due to StackSafetyAnalysis), only 16-byte alignment is guaranteed, but it ends up being 32-byte aligned due to the frame layout.

On s390x, it seems that all `StackObject`s are just 4-byte or 8-byte aligned. Therefore, the first `char array[len]`, if not instrumented, is not 32-byte aligned.

I think the following patch should fix the failure on s390x.
Note: `char array[i]` in the loop is not instrumented due to the `isAllocaPromotable(&AI)` optimization (which I want to get rid of in #77221).
Whether `char array[i]` gets instrumented or not does not make the result different, but instrumenting it may make the test more intesting.
(Without the VLA `alloca(i)` returns a different address in each iteration).

```diff
--- i/compiler-rt/test/asan/TestCases/alloca_loop_unpoisoning.cpp
+++ w/compiler-rt/test/asan/TestCases/alloca_loop_unpoisoning.cpp
@@ -4,3 +4,2 @@
 // REQUIRES: stable-runtime
-// UNSUPPORTED: target=s390{{.*}}

@@ -28,2 +27,3 @@ __attribute__((noinline)) void foo(int len) {
   char array[len];
+  if (len) array[0] = 0;
   assert(!(reinterpret_cast<uintptr_t>(array) & 31L));
@@ -32,2 +32,3 @@ __attribute__((noinline)) void foo(int len) {
     char array[i];
+    if (i) array[0] = 0;
     bot = alloca(i);
```

**Pull request merged**
