### PR TITLE
[libc][docs] start documenting c23 support

### PR DESCRIPTION
**Pull request by nickdesaulniers**
I've been diffing the c17 vs c23 latest publicly available drafts and think I
have most of the library related differences. I haven't yet annotated what we
actually support or not.

Link: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n2310.pdf (C17)
Link: https://www.open-std.org/jtc1/sc22/wg14/www/docs/n3096.pdf (C23)

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
cc @ThePhD

**Review by lntue — APPROVED** [review]
Thanks for collecting this and having a single place to keep track of our C23 progress is much better!

**Comment by ThePhD** [comment]
> cc @ThePhD

You also need `char8_t` as a `typedef` in there.

**Comment by SchrodingerZhu** [comment]
Could you also mention inttypes.h?

**Comment by nickdesaulniers** [comment]
> Could you also mention inttypes.h?

FWICT, inttypes.h existed in C17 and is no different in C23 (at least from comparing annex B).  Did I miss something perhaps?

**Comment by nickdesaulniers** [comment]
> > cc @ThePhD
> 
> You also need `char8_t` as a `typedef` in there.

done in https://github.com/llvm/llvm-project/pull/81933/commits/dad2c0d0cda73ffa5e572903674b5179c6553c41. Thanks for the review! Happy to modify this more as needed.

**Comment by SchrodingerZhu** [comment]
see https://github.com/llvm/llvm-project/issues/81896

**Comment by nickdesaulniers** [comment]
> see https://github.com/llvm/llvm-project/issues/81896
> Glibc has added PRIbN and PRIBN: 

Interesting.  The last publicly available c23 draft doesn't mention those, at least in `B.7 Format conversion of integer types <inttypes.h>`. So I guess they're an extension? Maybe the final draft fixed this, or perhaps a defect report was written against the standard? Maybe @ThePhD knows?

**Comment by ThePhD** [comment]
Yes, this was an oversight in the c23 working draft everyone is using. A better version is here: https://drive.google.com/file/d/12kNvH0aYJhe3ZPmBKH_Nk5maTfxH2lJv/view

**Comment by nickdesaulniers** [comment]
> A better version is here: https://drive.google.com/file/d/12kNvH0aYJhe3ZPmBKH_Nk5maTfxH2lJv/view

Ah, N3220! It's like finding a shiny pokemon! (and is an upgrade from referring to n3096)! I think this was the password protected one? Thanks!

**Comment by nickdesaulniers** [comment]
@michaelrj-google also pointed me to https://gustedt.gitlabpages.inria.fr/c23-library/

**Pull request merged**
