### PR TITLE
[lldb][test][NFC] Add option to exclude third_party packages

### PR DESCRIPTION
**Pull request by rupprecht**
The goal here is to remove the third_party/Python/module tree, which LLDB tests only use to `import pexpect`. This package is available on `pip`, and I believe should not be hard to obtain.

However, in case it isn't easily available, deleting the tree right now could cause disruption. This introduces a `LLDB_TEST_USE_VENDOR_PACKAGES` cmake param that can be enabled, and the tests will continue loading that tree. By default, it is enabled, meaning there's really no change here. A followup change will disable it by default once all known build bots are updated to include this package. When disabled, an eager cmake check runs that makes sure `pexpect` is available before waiting for the test to fail in an obscure way.

Later, this option will go away, and when it does, we can delete the tree too. Ideally this is not disruptive, and we can remove it in a week or two.

### CODE REVIEW

**Review by bulbazord — APPROVED** [review]
LGTM

@JDevlieghere @adrian-prantl we should consider adding this to the list of required python modules on our bots too and enforce it with `LLDB_ENFORCE_STRICT_TEST_REQUIREMENTS`? Probably not in this PR, but after we can get our bots configured correctly.

**Comment by DavidSpickett** [comment]
>  This introduces a LLDB_TEST_USE_VENDOR_PACKAGES cmake param that can be enabled, and the tests will continue loading that tree.

I get the intent but doing it this way is actually going to be more of an issue. As changes to our bot config have to go through zorg, a master restart, then they finally hit the builders, this takes up to a week sometimes. With this new option defaulting to OFF that means potentially a week of broken builds.

I would suggest making this option default `ON`, and builders can turn it `OFF` once they've installed the right packages. Then finally remove the option altogether. It'll take a longer time but we won't have a period of broken builds during it.

**Comment by DavidSpickett** [comment]
Though maybe you intend this to break builds, that way obscure builders that we don't know about will still hear about this?

I can understand that angle, in which case do we want to make sure all known builders have pexpect installed before this commit goes in? I will sort out Linaro's bots this week.

**Comment by DavidSpickett** [comment]
Also are there known compatible/incompatible versions of pexpect? Is `pip install pexpect` going to install something with significant API differences to the vendored copy?

**Comment by rupprecht** [comment]
> Though maybe you intend this to break builds, that way obscure builders that we don't know about will still hear about this?
> 

Yes, but I agree with your suggestion to land this with a default of `ON`, which makes this change NFC. I can then switch it to `OFF` once known buildbots are updated. I'll update the PR later today.

> I can understand that angle, in which case do we want to make sure all known public builders have pexpect installed before this commit goes in? I will sort out Linaro's bots this week.

Thanks!

> Also are there known compatible/incompatible versions of pexpect? Is `pip install pexpect` going to install something with significant API differences to the vendored copy?

- Our vendored version is at 4.6, with two local patches for timeouts:
  - a8419b1f2767c7fd5c0d0696b76d17efb2a5b418
  - 97c6ef4ea678ef9a69e1feaf9d77a0880bca09ba
- For my local machine (where tests are passing :) ), `python3-pexpect` is 4.8. Looks like that was released in 2020, and probably the version most people have.
- The page https://pypi.org/project/pexpect/ lists trunk as version 4.9.0. We have some internal builds using that version which also work.
- https://pexpect.readthedocs.io/en/stable/history.html doesn't seem to list anything significant recently

btw, I see many tests w/ comments like this: `@skipIfWindows  # llvm.org/pr22274: need a pexpect replacement for windows`. As of pexpect-4.0, there is (experimental) windows support. So if you're interested in Windows support, it'd be a good idea to see if those tests work now.

**Review by DavidSpickett — APPROVED** [review]
You need to update the PR description but otherwise LGTM.

**Comment by JDevlieghere** [comment]
> @JDevlieghere @adrian-prantl we should consider adding this to the list of required python modules on our bots too and enforce it with `LLDB_ENFORCE_STRICT_TEST_REQUIREMENTS`? Probably not in this PR, but after we can get our bots configured correctly.

Added in 793300988b7c. Let's see if this blows up on our bots :-)

**Comment by DavidSpickett** [comment]
The way the cmake is written it seems that Py_pexpect_FOUND is set to false the first time you run cmake. Then you install pexpect and lldb_find_python_module bails early because Py_pexpect_FOUND is *still* set to false.

If you remove the CMake cache it'll then find pexpect as, well, expected.

**Comment by DavidSpickett** [comment]
And a data point, AArch64 and Arm Linux are fine with pexpect-4.9.0. Still working on getting it installed on the bot containers.

**Comment by DavidSpickett** [comment]
FYI @labath as the x86 bot owner.

**Comment by DavidSpickett** [comment]
> It should perhaps unset the variable first, I'll see if I can implement that.

https://github.com/llvm/llvm-project/commit/ec95379df363253ffcbbda21297417e703d5ccca

**Comment by DavidSpickett** [comment]
Arm and AArch64 bots now have pexpect 4.9.0 installed.

For Linaro's bots at least, we would be ok with you flipping `LLDB_TEST_USE_VENDOR_PACKAGES` to `OFF` as the next step. This saves us getting a change through zorg and should "just work" now.

**Comment by bulbazord** [comment]
@DavidSpickett If you haven't already, might I suggest looking into a CMake setting I implemented last year? `LLDB_ENFORCE_STRICT_TEST_REQUIREMENTS` -- this will cause your CMake configure step to fail if your bots are missing python packages so that you know your bots are running in a reasonable state. :)

**Comment by DavidSpickett** [comment]
Done: https://github.com/llvm/llvm-project/commit/ec8df555702d85511290742388d28016b69468de / https://github.com/llvm/llvm-zorg/commit/e08c692f75a922ee820ac8722f5033255913c195

**Comment by rupprecht** [comment]
> FYI @labath as the x86 bot owner.

I checked w/ them that [lldb-x86_64-debian](https://lab.llvm.org/buildbot/#/builders/68) has python3-pexpect (specifically 4.8) installed.

> > It should perhaps unset the variable first, I'll see if I can implement that.
> 
> [ec95379](https://github.com/llvm/llvm-project/commit/ec95379df363253ffcbbda21297417e703d5ccca)

Thanks! Cmake is still pretty foreign to me. It didn't occur to me that the result of finding a python library would be cached :) but I guess it makes sense from a build system perspective to not want to reconfigure everything all the time.

Since it sounds like all the bots should have `pexpect` now, I think I can flip the default later today and be ready to revert if there's unexpected breakage.

**Pull request merged**
