### PR TITLE
[flang] lower SHAPE intrinsic

### PR DESCRIPTION
**Pull request by jeanPerier**
Semantics usually fold SHAPE into an array constructor, but sometimes it cannot (like when the source is a function result that cannot be duplicated in expression analysis). Add lowering handling for shape.

### CODE REVIEW

**Review by vzakhari — APPROVED** [review]
LGTM!

**Review by tblah — COMMENTED** [review]
What about the optional KIND argument?

Otherwise looks good

**Comment by jeanPerier** [comment]
> What about the optional KIND argument?

Thanks for pointing that out. It is taken into account via the "resultType" that was computed by semantic analysis. Still deserves a test, I added one.

**Review by tblah — APPROVED** [review]
Thanks for adding the test

**Pull request merged**
