### PR TITLE
[rtsan][tsan] Fix va_args handling in open functions

### PR DESCRIPTION
**Pull request by cjappl**
This PR is being opened in response to [this comment](https://github.com/llvm/llvm-project/issues/108068#issuecomment-2344452479)

Check oflag to see if it contains O_CREAT before unpacking parameters

EDIT: please see comments below discussing whether or not this is necessary

### CODE REVIEW

**Comment by cjappl** [comment]
CC for review @davidtrevelyan

**Comment by cjappl** [comment]
Hmm, as a counter-argument to this PR, it seems like tsan does the same thing that we do now, always unpacking the arg:

https://github.com/llvm/llvm-project/blob/c2b93e0671d8cfd6b1a24c6e1d7be290125b8974/compiler-rt/lib/tsan/rtl/tsan_interceptors_posix.cpp#L1664-L1675

**Review by nikic — APPROVED** [review]
LGTM

**Comment by vitalybuka** [comment]
I would expect it's unnecessary? it probably unpacks garbage, but it's not suppose to be used.

also seem O_TMPFILE can read mode?

**Review by vitalybuka — APPROVED** [review]
LGTM, but I'd suggest either not commit, or include TSAN as well.

**Review by vitalybuka — APPROVED** [review]

**Comment by cjappl** [comment]
Thanks for the additional tests and support vitalybuka

**Pull request merged**
