### PR TITLE
 [InferAlignment][NFC] Unify Load/Store handling in tryToImproveAlign 

### PR DESCRIPTION
**Pull request by ParkHanbum**
﻿Removes code duplication in tryToImproveAlign by unifying load and
store instruction handling with getLoadStore helper functions.

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
The first commit looks fine to me, I don't understand the purpose of the other two. The alignment enforcement isn't expensive enough to make caching useful, I think?

**Comment by nikic** [comment]
> @nikic I assumed it would be lower than the cost of stripPointerCasts; if not, I'll delete that commit. I'll also delete the second commit if it's have no effective.

stripPointerCasts() is very cheap.

**Comment by ParkHanbum** [comment]
@nikic I made a wrong assumption, sorry

**Review by nikic — APPROVED** [review]
LGTM

**Pull request merged**
