### PR TITLE
[flang][docs] Update llvm-test-suite docs

### PR DESCRIPTION
**Pull request by DavidSpickett**
With some missing config options and a link to the test suite docs that explain how to setup `ISO_FORTRAN_C_HEADER` and set the stop message variable.

### CODE REVIEW

**Comment by DavidSpickett** [comment]
The header file is in the build tree, but flang doesn't find it:
```
$ find -name ISO_Fortran_binding.h
./lib/clang/19/include/ISO_Fortran_binding.h
```
Is that expected?

**Comment by kiranchandramohan** [comment]
> ISO_Fortran_binding.h

I think the requirement in general is that the C compiler can find it.

For the gfortran tests in LLVM testsuite there is a CMake Flag to provide the location 
(-DTEST_SUITE_FORTRAN_ISO_C_HEADER_DIR).
https://github.com/llvm/llvm-test-suite/blob/main/Fortran/gfortran/README.md

**Comment by DavidSpickett** [comment]
Thanks, maybe it's better to link to that page then since it's already got these changes. I'll look into that.

**Comment by DavidSpickett** [comment]
Added a link to the test suite docs. We could remove the content here entirely but there is some value in having a basic intro on this page I think.

**Review by klausler — APPROVED** [review]

**Pull request merged**
