### PR TITLE
[clang][driver][clang-cl] Fix unused argument warning for `/std:c++20` for precompiled module inputs to `clang-cl`

### PR DESCRIPTION
**Pull request by sharadhr**
Relates to #98761: `-fmodule-file` requires `/std:c++20` or greater, but passing that option results in an unused argument warning. This resolves that.

### CODE REVIEW

**Review by ChuanqiXu9 — COMMENTED** [review]
Please add a test for this too. We can use any file ends with `.pcm` to mimic  module file in the Driver's test and we can use `CHECK-NOT:` to filter the warning.

**Comment by sharadhr** [comment]
Not quite sure how to handle the test for this; I'm struggling to find a `.pcm` file that can be used.

**Comment by ChuanqiXu9** [comment]
Maybe something like this:

```
// RUN: rm -rf %t
// RUN: split-file %s %t
// RUN: %clang %t/fake.pcm -std=c++20 -### 2>&1 | FileCheck %t/fake.pcm

//--- fake.pcm
// CHECK-NOT: warning
```

**Review by ChuanqiXu9 — APPROVED** [review]
LGTM

**Comment by ChuanqiXu9** [comment]
From the log, it looks like the git crashes instead of conflicts. @tru  would you like to take look.

@sharadhr also if you want to backport this to 19.x, maybe you can try to create a PR to the branch of 19.x branch manually in case the automated cherry-pick doesn't work.

**Comment by sharadhr** [comment]
Just to clarify—you'd like me to open another PR to `release/19.X`? I can do that.

In fact I'm a little more ambitious because this and #98761 are honestly very simple PRs—I'd like them to be backported as far as Clang 16 (which is when modules support first appeared) if possible.

**Comment by ChuanqiXu9** [comment]
> Just to clarify—you'd like me to open another PR to `release/19.X`? I can do that.

Yes. You can find the automated generated example in https://github.com/llvm/llvm-project/pull/102159

> 
> In fact I'm a little more ambitious because this and #98761 are honestly very simple PRs—I'd like them to be backported as far as Clang 16 (which is when modules support first appeared) if possible.

No, this is not possible. We may never have new releases for 18, 17 and 16 as far as I know.

**Comment by sharadhr** [comment]
Ah. That's a pity but no problem. I'll create the PR now. Thanks!

**Pull request merged**
