### PR TITLE
[llvm-objdump] Remove some unneeded headers.

### PR DESCRIPTION
**Pull request by cabbaken**

### CODE REVIEW

**Review by jh7370 — COMMENTED** [review]
Could you clarify how you went about identifying which headers are unneeded, please? I note for example that `StringSet` is used in `llvm-objdump.cpp`.

**Comment by cabbaken** [comment]
Almost all headers I removed are included by the relative header. For example, StringSet is included by llvm-objdump.h.
It’s the first time I submit my patch to community, sorry if I did something wrong🥺.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________

**Comment by cabbaken** [comment]
Thank you about that!
Happy to meet you and I will wait for the review!☺️
________________________________

**Review by jh7370 — COMMENTED** [review]
LGTM. Do you need me to merge this?

I note that you have a private GitHub email setting applied at the moment. Please note the following from the LLVM Developer Policy:

> The LLVM project uses email to communicate to contributors outside of the GitHub platform about their past contributions. Primarily, our buildbot infrastructure uses emails to contact contributors about build and test failures. Therefore, the LLVM community requires contributors to have a public email address associated with their GitHub commits, so please ensure that “Keep my email addresses private” is disabled in your [account settings](https://github.com/settings/emails).

If you'd like me to merge this for you, please modify your GitHub settings according to the policy and let me know you have done so. Then I can merge it for you.

**Comment by cabbaken** [comment]
Thanks for your reply!
It's nice if my code will be merged.
I am sorry about the wrong setting of my account, I have modified it and please check if it is correct now.
Thanks~😊

________________________________

**Comment by jh7370** [comment]
> Thanks for your reply! It's nice if my code were merged. I am sorry about the wrong setting of my account, I have modified it and please check if it is correct now. Thanks~😊

Done and not an issue - I get the impression it might be set by default these days.

**Pull request merged**
