### PR TITLE
[GlobalIsel] Improve poison analysis

### PR DESCRIPTION
**Pull request by tschuett**

### CODE REVIEW

**Comment by tschuett** [comment]
How do we treat COPY?

**Comment by arsenm** [comment]
> How do we treat COPY?

Look through virtual registers and treat physical like the DAG does for CopyFromReg (which I believe recently started assuming are frozen)

**Comment by tschuett** [comment]
Should we add COPY to `canCreateUndefOrPoison` with false?

**Comment by tschuett** [comment]
Then `MachineInstr *RegDef = MRI.getVRegDef(Reg);`might fail.

**Comment by arsenm** [comment]
> Should we add COPY to `canCreateUndefOrPoison` with false?

Yes, COPY should never be able to introduce poison 

> Then MachineInstr *RegDef = MRI.getVRegDef(Reg);might fail.

Don't follow. The only case it should be able to fail is for undef use operands (which I think should be a verifier error. We should not permit undef uses for IsSSA functions)

**Comment by tschuett** [comment]
If we `COPY` from a physical register, we might invoke `canCreateUndefOrPoison` with a physical register. Then we invoke `MRI.getVRegDef(Reg)` where `Reg` is a physical register. It will fail.

**Comment by arsenm** [comment]
> If we `COPY` from a physical register, we might invoke `canCreateUndefOrPoison` with a physical register. Then we invoke `MRI.getVRegDef(Reg)` where `Reg` is a physical register. It will fail.

Yes, you just avoid doing that. It's just return true if copy and bypass the getVRegDef

**Comment by tschuett** [comment]
ping

**Comment by tschuett** [comment]
ping

**Review by arsenm — APPROVED** [review]

**Comment by tschuett** [comment]
Thanks!

**Pull request merged**
