### PR TITLE
[mlir][vector] add result type to vector.extract assembly format

### PR DESCRIPTION
**Pull request by c-rhodes**
The vector.extract assembly format currently only contains the source type, for example:

  %1 = vector.extract %0[1] : vector<3x7x8xf32>

it's not immediately obvious if this is the source or result type. This patch improves the assembly format to make this clearer, so the above becomes:

  %1 = vector.extract %0[1] : vector<7x8xf32> from vector<3x7x8xf32>

### CODE REVIEW

**Comment by nicolasvasilache** [comment]
Hmm .. 

```
%1 = vector.extract %0[1] : vector<3x7x8xf32>

it's not immediately obvious if this is the source or result type.
```

it should be quite natural to see this can only be the source type, otherwise information is missing there is no way to determine the source type.

I am sympathetic to improving the syntax and making things more obvious / not require to infer the above.
In this case, the syntax is meant to follow LLVM's (https://llvm.org/docs/LangRef.html#extractvalue-instruction).

I'd be wary of departing from being less consistent with LLVM where it makes sense, OTOH I can also see that this is a purely MLIR concern as it only appears with (N>1)-D vectors which do not exist in LLVM.

I'm a very soft +1 on this change but would like to also hear others opinions before moving ahead.

**Comment by c-rhodes** [comment]
> Hmm ..
> 
> ```
> %1 = vector.extract %0[1] : vector<3x7x8xf32>
> 
> it's not immediately obvious if this is the source or result type.
> ```
> 
> it should be quite natural to see this can only be the source type, otherwise information is missing there is no way to determine the source type.

That didn't register for me when I first saw it but it's a fair point. It is still necessary to look at the number of indices however and I think this helps there. It also feels more in keeping with `vector.insert` which has `: $source_type into $dest_type`, but perhaps that's also consistent with LLVM as you mention, and I didn't give that any consideration.

>
> I am sympathetic to improving the syntax and making things more obvious / not require to infer the above. In this case, the syntax is meant to follow LLVM's (https://llvm.org/docs/LangRef.html#extractvalue-instruction).
> 
> I'd be wary of departing from being less consistent with LLVM where it makes sense, OTOH I can also see that this is a purely MLIR concern as it only appears with (N>1)-D vectors which do not exist in LLVM.
> 
> I'm a very soft +1 on this change but would like to also hear others opinions before moving ahead.

No worries, appreciate the speedy review.

**Comment by banach-space** [comment]
+1 from me, I would really appreciate this change.

**Comment by kuhar** [comment]
Soft +1, I do think this reduces cognitive load for >1-d vectors. And for consistency, extending this to 0 and 1-d vectors makes sense to me.

**Comment by aartbik** [comment]
A soft +1 on this too. I noticed we have some syntax that uses "into" and some other that uses "from" so perhaps we want to unify that too at some point; but that should not impact this change

**Comment by dcaballe** [comment]
I think this is more about personal opinions... I personally prefer processing less text when the extra information can be easily inferred. That's less cognitive load for me :). That + massive test changes... but I don't care enough to push back so up to you :)

**Review by banach-space — APPROVED** [review]
There's one firm 👍🏻 (from me), a few soft 👍🏻 (Nicolas, Jakub and Aart) and one "up to you" (Diego), so I think that we should go ahead with this :)

LGTM, thank you!

**Comment by c-rhodes** [comment]
> There's one firm 👍🏻 (from me), a few soft 👍🏻 (Nicolas, Jakub and Aart) and one "up to you" (Diego), so I think that we should go ahead with this :)
> 
> LGTM, thank you!

Thanks will rebase this soon and land.

**Pull request merged**
