### PR TITLE
[mlir] Add a null pointer check in symbol lookup

### PR DESCRIPTION
**Pull request by shlmregev**
We (TensorFlow project) ran into a case where a dead code analysis crashed because a symbol that is called/used didn't appear in the symbol table. Added a nullptr check after symbol table lookup.

### CODE REVIEW

**Comment by joker-eph** [comment]
Could we test?

If needed adding an op in the test dialect which implements the callable interface, and an IR that has the call but not the definition for the callee?

**Comment by shlmregev** [comment]
Sorry, but I'm not familiar with LLVM. Just tracked down this bug from my application code, written on top of TensorFlow.

**Comment by joker-eph** [comment]
Oh I see. You should many MLIR folks at Google I think: can you find one of your colleagues to assist with this maybe?

**Comment by jpienaar** [comment]
Added a test to very it doesn't crash.

**Review by joker-eph — APPROVED** [review]

**Comment by joker-eph** [comment]
Nice, didn't even need a change in the test dialect :)

**Pull request merged**
