### PR TITLE
[DebugInfo][InstCombine] Do not overwrite prior DILocation for new Insts

### PR DESCRIPTION
**Pull request by SLTozer**
When InstCombine replaces an old instruction with a new instruction, it copies !dbg and !annotation metadata from old to new. For some InstCombine patterns we set a specific DILocation on the new instruction prior to insertion, however, which more accurately reflects the new instruction. This more specific DILocation may be overwritten on insertion by a less appropriate one, resulting in a less correct line mapping. This patch changes this behaviour to only copy the DILocation from old to new if the new instruction has no existing DILocation (which will always be the case for a new instruction unless InstCombine has specifically set one).

This isn't a perfect solution. In the test case given, we create a load instruction and give it the merged location of the two existing load instructions it replaces. Prior to this patch, if the PHI that is being RAUWd has a DILocation, it will overwrite the merged location on the new load, which is bad. However even with this patch, if either of the load instructions has no DILocation, then the new load won't have one either, and it will thus receive the DILocation from the PHI. This is probably bad - the PHI could have a valid DILocation corresponding to a different line, meaning that if the load results in an invalid memory access then we will attribute the resulting crash to the PHI's line, which could be worse than giving no attribution at all. I don't see any easy way to solve this problem however without fundamentally changing how InstCombine assigns DILocations; the most likely fix would be to exclusively assign DILocations within the InstCombine patterns, or to otherwise allow them to specify whether or not a DILocation ought to be copied from the original instruction or not.

### CODE REVIEW

**Comment by pogo59** [comment]
> However even with this patch, if either of the load instructions has no DILocation, then the new load won't have one either,

If we merge locations on two instructions, but only one has a location, the merged result is no location? 

How often do we get a load with no DILocation in practice? It seems like that would be unusual.

**Comment by SLTozer** [comment]
> If we merge locations on two instructions, but only one has a location, the merged result is no location?

Correct; when we merge locations, we choose the innermost scope that contains both; if either has no location whatsoever (i.e. has no scope), then we can't assign any meaningful location that isn't lying about one of them.

> How often do we get a load with no DILocation in practice? It seems like that would be unusual.

Hard to say, but I uploaded another patch earlier today that fixes a case where we generate loads without a location (https://github.com/llvm/llvm-project/pull/108531); there are also all sorts of ways that DILocations can be dropped right now, and although I'm trying to eliminate as many as possible right now it seems safer to be defensive about the possibility. As a small, not totally reliable, data point, I found ~45 loads generated (at _some_ point) without a DILocation while building [bullet](https://github.com/llvm/llvm-test-suite/tree/main/MultiSource/Benchmarks/Bullet).

**Comment by jmorse** [comment]
(the "unread" list in my inbox is looong,)

I'm not fully understanding the second paragraph about the bad case: in one mode the DILocation of a PHI is given to the new load instruction, and that's considered bad. In the second mode, there's a risk the new load "...will thus receive the DILocation from the PHI" -- so the same location as before, so there's no regression?

In principle I think this is a good patch that tries that keep source locations as specific as possible, I just want to understand the use case more.

**Comment by SLTozer** [comment]
> so the same location as before, so there's no regression?

That's correct - there's no regression from this patch, I'm simply noting that it's not a perfect solution. A more perfect solution would be one where we could state explicitly in this case, "Do not copy the original instruction's DebugLoc to the replacement instruction", but that would require making more intrusive changes to InstCombine with probably a large diff footprint, hence I'm considering this a worthwhile partial solution.

**Review by jmorse — APPROVED** [review]
LGTM but with the dumbest nit: it looks like the test is checking we get line number 63, instead of line number 64, which is fine. Could we replace the line numbers with something much more obvious, such as line number 1 to line number 55555 perhaps: IMO it makes the test much more readable and the relevant parts stand out.

**Pull request merged**
