### PR TITLE
[mlir][SCF] Remove `scf-bufferize` pass

### PR DESCRIPTION
**Pull request by matthias-springer**
The dialect conversion-based bufferization passes have been migrated to One-Shot Bufferize about two years ago. To clean up the code base, this commit removes the `scf-bufferize` pass, one of the few remaining parts of the old infrastructure. Most bufferization passes have already been removed.

Note for LLVM integration: If you depend on this pass, migrate to One-Shot Bufferize or copy the pass to your codebase.

### CODE REVIEW

**Review by javedabsar1 — CHANGES_REQUESTED** [review]
Since one-shot replaces scf-bufferize would it be better instead of deleting test/Dialect/SCF/bufferize.mlir to  change RUN to --one-shot-bufferize. That way, a test which might catch errors doesnt get deleted.
Having said that, I actually tried it but got this error.  Not sure why - but 100% sure you will know why:

```
../build/bin/mlir-opt  --one-shot-bufferize test/Dialect/SCF/bufferize.mlir
test/Dialect/SCF/bufferize.mlir:76:5: error: Yield operand #0 is not equivalent to the corresponding iter bbArg
    scf.yield %0 : tensor<f32>
```

**Comment by matthias-springer** [comment]
Good point. We have separate test cases that run One-Shot Bufferize. One per dialect. They are called `one-shot-bufferize.mlir` etc. The `bufferize.mlir` test cases also run One-Shot Bufferize but without an analysis. Basically just the `bufferize()` interface method. I updated the SCF `bufferize.mlir` test file accordingly. There was also a minor bug in the SCF interface implementation (upcasting an `AnalysisState` to `OneShotAnalysisState` when the object was not a `OneShotAnalysisState`) that I fixed.

**Review by javedabsar1 — APPROVED** [review]
LGTM. Thanks for fixing the scf interface bug. If you reckon that the test/Dialect/SCF/bufferize.mlir test is covered already under the other tests, please delete instead of duplication. I just wanted to draw your attention to the fail.

**Comment by matthias-springer** [comment]
> LGTM. Thanks for fixing the scf interface bug. If you reckon that the test/Dialect/SCF/bufferize.mlir test is covered already under the other tests, please delete instead of duplication. I just wanted to draw your attention to the fail.

Thx, it's good to have a test that does not run the analysis, so let's keep it.

**Comment by joker-eph** [comment]
LG, thanks for the cleanup!
Did you check that no documentation leftover references it?

**Comment by matthias-springer** [comment]
Yes, I grepped for all occurrences of the pass name. There is still `func-bufferize` and `finalizing-bufferize`, which have to go (in separate PRs), then the remaining documentation of the dialect conversion-based bufferization infrastructure can be deleted.

**Pull request merged**
