### PR TITLE
[clang][analyzer] Support 'getdelim' and 'getline' in StreamChecker

### PR DESCRIPTION
**Pull request by benshi001**

### CODE REVIEW

**Review by NagyDonat — APPROVED** [review]
Looks reasonable.

My only concern is that several recent changes introduced similar, but separate `evalXXX` methods that are used for modeling just one or two standard functions. I have a vague suspicion that these could be "standardized" (e.g. by moving their common parts into helper functions) to reduce the length and complexity of the code.

**Comment by balazske** [comment]
I have already a working code to simplify code repetitions, but want to merge first patches #76979 and #78180 (@NagyDonat  could you look at these too?).

**Comment by benshi001** [comment]
> I have already a working code to simplify code repetitions, but want to merge first patches #76979 and #78180 (@NagyDonat could you look at these too?).

How about merge this patch first, then apply your simplification one? Since my current one also is affected.

**Review by balazske — APPROVED** [review]
OK, change can be merged before the simplification.

**Pull request merged**
