### PR TITLE
[Clang] [NFC] Refactor AST visitors in Sema and the static analyser to use DRAV

### PR DESCRIPTION
**Pull request by Sirraide**
This pr refactors all recursive AST visitors in `Sema`, `Analyze`, and `StaticAnalysis` to inherit from DRAV instead. This is over half of the visitors that inherit from RAV directly.

See also #115132, #110040, #93462

LLVM Compile-Time Tracker link for this branch: https://llvm-compile-time-tracker.com/compare.php?from=5adb5c05a2e9f31385fbba8b0436cbc07d91a44d&to=b58e589a86c06ba28d4d90613864d10be29aa5ba&stat=instructions%3Au

### CODE REVIEW

**Comment by Sirraide** [comment]
> What's the benefit of using `DRAV` over `RAV`? I couldn't find the motivation in the PR summary in neither of this or the linked PR.

Improving compile-times and binary size of Clang itself, mainly. See also #110040

**Comment by steakhal** [comment]
> > What's the benefit of using `DRAV` over `RAV`? I couldn't find the motivation in the PR summary in neither of this or the linked PR.
> 
> Improving compile-times and binary size of Clang itself, mainly. See also #110040

Thanks! I was missing this bit. This is impressive work. Thank you.

I skimmed the PR, and I was wondering if you could `final` inherit in most cases? Or use `final` instead of `override`. I'm not sure if it matters, I'm just curious.

**Comment by Sirraide** [comment]
> I skimmed the PR, and I was wondering if you could `final` inherit in most cases? Or use `final` instead of `override`. I'm not sure if it matters, I'm just curious.

Ah yeah, I did try that, but during my testing, I didn’t really find `final` to make a difference...

**Comment by Sirraide** [comment]
> I didn’t really find `final` to make a difference...

In case anyone’s curious: https://llvm-compile-time-tracker.com/compare.php?from=676a069b35f45cd8578c2db67cf9b46042ec627a&to=c60376418407188af2017652114baae90c586be5&stat=instructions:u

**Comment by Sirraide** [comment]
ping

**Review by AaronBallman — COMMENTED** [review]
Given the size of the PR, I didn't go over it with a fine-toothed comb as the changes are mostly mechanical. However, the changes I spot-checked looked correct to me.

LGTM, but please don't land until the merge conflicts are resolved and precommit CI comes back green.

Thank you for this work!

**Review by AaronBallman — APPROVED** [review]

**Pull request merged**
