### PR TITLE
Revert "[LinkerWrapper] Extend with usual pass options (#96704)"

### LINKED ISSUE #100212: [Clang] `clang-linker-wrapper` does not forward `-fpass-plugin` to the LTO invocation
Recent patches moved the LTO portion of the offloading compilation into the actual linker invocation. This means we aren't forwarding linker options to it correctly.

### PR DESCRIPTION
**Pull request by jhuber6**
This reverts commit 90ccf2187332ff900d46a58a27cb0353577d37cb.

Fixes: https://github.com/llvm/llvm-project/issues/100212

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
Thanks! Can this be fixed on `release/19.x` too?

**Comment by jhuber6** [comment]
> Thanks! Can this be fixed on `release/19.x` too?

I'm still surprised  this made it into the Release, since I'm pretty sure I only landed all of these changes after the fork. But we should be able to backport it from the existing issue.

**Review by jdenny-ornl — APPROVED** [review]

**Comment by haoNoQ** [comment]
Yeah I think we really gotta cherry-pick this revert, because failing tests on release branches are somewhat scary (cf. https://green.lab.llvm.org/job/llvm.org/job/clang-stage1-RA-release-branch/69/console).

I don't know how it's usually done but let me try to push some buttons, it's kind of semi-automatic I think.

**Comment by haoNoQ** [comment]
Oh that's just a whitespace change. Would you like me to make a manual PR or were you looking into it anyway?

**Comment by haoNoQ** [comment]
#106439

**Pull request merged**
