### PR TITLE
[Headers] [ARM64EC] Fix extra tokens inside intrin0.h preprocessor directive

### PR DESCRIPTION
**Pull request by MaxEW707**
Fixes https://github.com/llvm/llvm-project/pull/87717.

### CODE REVIEW

**Comment by efriedma-quic** [comment]
Please add a testcase (something similar to clang/test/Headers/ms-intrin.cpp, but including intrin0.h instead of intrin.h, to catch obvious mistakes in the header).

Not sure how you're actually hitting the error you reported; the clang header directory should count as a system header, so the warning should normally be suppressed, I think.

**Comment by MaxEW707** [comment]
> Not sure how you're actually hitting the error you reported; the clang header directory should count as a system header, so the warning should normally be suppressed, I think.

It is counted as a system header and I could not repro the warning in my local tests. I was going off the user who posted the issue in the previous PR.

clang_cc1 substitution in lit also adds the header path via `-internal-isystem` which is why our unit tests weren't hitting this.

> Please add a testcase (something similar to clang/test/Headers/ms-intrin.cpp, but including intrin0.h instead of intrin.h, to catch obvious mistakes in the header).

`intrin.h` includes `intrin0.h`. Our unit tests weren't hitting this since lit adds the clang header path as a system include so warnings are suppressed. I should be able to use "--no-system-header-prefix" to workaround that. I'll give that a try inside `ms-intrin.cpp` and that will cover both `intrin.h` and `intrin0.h`.

**Review by mstorsjo — APPROVED** [review]
LGTM

**Review by efriedma-quic — APPROVED** [review]

**Comment by MaxEW707** [comment]
@efriedma-quic What is the process for getting a fix into a milestone such as the upcoming 19.1.2 milestone. I read the docs on `cherry-pick` but I couldn't find any information about who decides what is considered suitable for a patch release.
I am going to defer to you if you think this is worthwhile for 19.1.2 and if so what are the next steps to make that happen.

**Comment by mstorsjo** [comment]
I think it's backport worthy. It's very small and has a near zero regression risk, and is a quite obvious fix. It might be a bit late for 19.1.2 which should be cut tomorrow, but should probably make it for 19.1.3.

Just add this PR to the right 19.x milestone and type a `/cherry-pick` comment here with the commit hash, and the bots should do the rest.

**Pull request merged**
