### PR TITLE
[Github] Enable warnings as errors on flang sphinx build

### PR DESCRIPTION
**Pull request by boomanaiden154**
Now that the number of warnings in the flang sphinx build has come down significantly, we can turn on warnings as errors in the sphinx build, which is the default configuration in CMake.

### CODE REVIEW

**Comment by boomanaiden154** [comment]
We'll probably need to wait a little bit before merging this, but there's only one final warning that I can see before this is ready to merge:
```
/tmp/llvm-project/build/tools/flang/docs/Source/FlangCommandLineReference.rst:176: WARNING: unknown document: 'DiagnosticsReference'
```

Once that gets fixed, we should be able to get this in.

**Review by tstellar — APPROVED** [review]

**Comment by tru** [comment]
Can this be merged or dropped if no longer needed?

**Comment by tru** [comment]
Would be good if we could fix so that errors are caught in the PR process if at all possible.

**Comment by kiranchandramohan** [comment]
> We'll probably need to wait a little bit before merging this, but there's only one final warning that I can see before this is ready to merge:
> 
> ```
> /tmp/llvm-project/build/tools/flang/docs/Source/FlangCommandLineReference.rst:176: WARNING: unknown document: 'DiagnosticsReference'
> ```
> 
> Once that gets fixed, we should be able to get this in.

This warning (and all others) are now fixed. But I see the following mlir warning that is probably caused because flang needs mlir tools.
```
/home/buildbot/as-worker-4/publish-sphinx-docs/llvm-project/mlir/tools/mlir-tblgen/OpDefinitionsGen.cpp:2956:38: warning: unused variable ‘operand’ [-Wunused-variable]
```

**Comment by boomanaiden154** [comment]
> This warning (and all others) are now fixed. 

There were still two errors popping up with the CI configuration, but it looks like those are due to building the `docs-flang-man` target, which doesn't actually produce anything. Given that's not configured properly, it should probably be removed?

>But I see the following mlir warning that is probably caused because flang needs mlir tools.
> 
> ```
> /home/buildbot/as-worker-4/publish-sphinx-docs/llvm-project/mlir/tools/mlir-tblgen/OpDefinitionsGen.cpp:2956:38: warning: unused variable ‘operand’ [-Wunused-variable]
> ```

I can't reproduce that warning at all with a recent clang version. The CI uses `gcc` (I believe), so it might show up there. It's a compiler warning though, so doesn't impact the viability of this patch.

I'm going to land this soonish as everything should be good to go now. Thanks for your work on fixing this up!

**Comment by kiranchandramohan** [comment]
> I can't reproduce that warning at all with a recent clang version. The CI uses `gcc` (I believe), so it might show up there. It's a compiler warning though, so doesn't impact the viability of this patch.

This warning is also fixed by the following.
https://github.com/llvm/llvm-project/pull/81899

Thanks for your patience.

**Pull request merged**
