### PR TITLE
[AMDGPU] CodeGen for GFX12 64-bit scalar add/sub

### PR DESCRIPTION
**Pull request by jayfoad**
- [AMDGPU] Generate add/sub checks and add GFX12 coverage
- [AMDGPU] CodeGen for GFX12 64-bit scalar add/sub

### CODE REVIEW

**Review by rampitec — APPROVED** [review]
LGTM, but does it need a change in the moveToVALU as well?

**Comment by jayfoad** [comment]
> does it need a change in the moveToVALU as well?

I think the way it works is that we always select S_ADD_U64_PSEUDO, which is already handled in moveToVALU, and only convert to S_ADD_NC_U64 later. But I will check...

**Comment by jayfoad** [comment]
> > does it need a change in the moveToVALU as well?
> 
> I think the way it works is that we always select S_ADD_U64_PSEUDO, which is already handled in moveToVALU, and only convert to S_ADD_NC_U64 later. But I will check...

Yes that is how it works. I have added a test for this.

**Comment by rampitec** [comment]
> > > does it need a change in the moveToVALU as well?
> > 
> > 
> > I think the way it works is that we always select S_ADD_U64_PSEUDO, which is already handled in moveToVALU, and only convert to S_ADD_NC_U64 later. But I will check...
> 
> Yes that is how it works. I have added a test for this.

Thanks!

**Review by rampitec — APPROVED** [review]
LGTM

**Pull request merged**
