### PR TITLE
[libc] [gpu] Add Generic, NvSin, and OcmlSinf64 Throughput Benchmark

### PR DESCRIPTION
**Pull request by jameshu15869**
This PR implements https://github.com/lntue/llvm-project/commit/2a158426d4b90ffaa3eaecc9bc10e5aed11f1bcf to provide better throughput benchmarking for libc `sin()` and `__nv_sin()`. 

These changes have not been tested on AMDGPU yet, only compiled.

### CODE REVIEW

**Review by jhuber6 — COMMENTED** [review]
I'm wondering if we shouldn't have separate functions for throughput and latency. We likely want to keep the old assembly constraints for the latency checks, but can use something different if we put it in an array.

Also, @lntue, is it necessary to even use a loop? If we want strict throughput couldn't we just do something like
```
#pragma unroll
for (int i = 0; i < DEPTH; ++i) {
  auto x = fn(input);
  asm("" : "r"(input) ::); // Probably need to trick the compiler into thinking this changed.
}
```

**Comment by jameshu15869** [comment]
> We likely want to keep the old assembly constraints for the latency checks, but can use something different if we put it in an array.

I don't think I changed the existing latency constraints, the new constraints in this diff are for an overloaded `latency()` function - should I rename it to something else?

**Review by jhuber6 — COMMENTED** [review]
Ah, I see you added new ones called `latency` as well. Somewhat surprised the type deduction is working here if so.

**Comment by jameshu15869** [comment]
> Ah, I see you added new ones called `latency` as well.

Yeah, I think the original intent of changing the constraints AMDGPU was that I realized using the pointer might be possible instead of having to do that `FORCE_TO_REGISTER()` workaround before - should we just keep that part in?

**Comment by jhuber6** [comment]
> > Ah, I see you added new ones called `latency` as well.
> 
> Yeah, I think the original intent of changing the constraints AMDGPU was that I realized using the pointer might be possible instead of having to do that `FORCE_TO_REGISTER()` workaround before - should we just keep that part in?

I'll need to double check the ASM generated there, I forget if capturing the pointer prevented it from carrying the input in a register.

**Review by jhuber6 — APPROVED** [review]

**Pull request merged**
