### PR TITLE
[Offload] XFAIL four tests while working on fix

### PR DESCRIPTION
**Pull request by jplehr**
omp_dynamic_shared_memory_mixed_amdgpu.c
omp_dynamic_shared_memory_amdgpu.c
amdgcn-amd-amdhsa::bug51982.c
amdgcn-amd-amdhsa::bug51781.c

### CODE REVIEW

**Comment by jhuber6** [comment]
What are the fails? Can we make an issue to track this before we land anything?

**Comment by jplehr** [comment]
Yeah, my bad, I forgot to link to the PR that caused the fails in the commit message.
https://github.com/llvm/llvm-project/pull/83131

There is an assertion error that we hit. Matt asked to produce IR before/after the patch, so I'm going to llvm-reduce these tests and provide it to him.

**Review by jhuber6 — APPROVED** [review]
LG for now as long as Matt fixes it and there's an issue.

**Comment by jplehr** [comment]
I have created https://github.com/llvm/llvm-project/issues/98903 to track this.

**Pull request merged**
