### PR TITLE
[clang][hlsl] Add tan intrinsic part 1

### PR DESCRIPTION
**Pull request by farzonl**
This change is an implementation of #87367's investigation on supporting IEEE math operations as intrinsics.
Which was discussed in this RFC:
https://discourse.llvm.org/t/rfc-all-the-math-intrinsics/78294

If you want an overarching view of how this will all connect see:
https://github.com/llvm/llvm-project/pull/90088

Changes:
- `clang/docs/LanguageExtensions.rst` - Document the new elementwise tan builtin.
-  `clang/include/clang/Basic/Builtins.td` - Implement the tan builtin.
-  `clang/lib/CodeGen/CGBuiltin.cpp` - invoke the tan intrinsic on uses of the builtin
-  `clang/lib/Headers/hlsl/hlsl_intrinsics.h` - Associate the tan builtin with the equivalent hlsl apis
-  `clang/lib/Sema/SemaChecking.cpp` - Add generic sema checks as well as HLSL specifc sema checks to the tan builtin
-  `llvm/include/llvm/IR/Intrinsics.td` - Create the tan intrinsic
-  `llvm/docs/LangRef.rst` - Document the tan intrinsic

### CODE REVIEW

**Review by hekota — APPROVED** [review]
LGTM!

**Comment by efriedma-quic** [comment]
Are you intentionally skipping implementing changes to __builtin_tan()?

**Comment by farzonl** [comment]
> Are you intentionally skipping implementing changes to __builtin_tan()?

Yes but, maybe my reasoning isn't good enough to exclude. Let me know. I didn't add it for two reasons.

First sine and cosine define builtins like so:
```
def SinF16F128 : Builtin, F16F128MathTemplate {
  let Spellings = ["__builtin_sin"];
  let Attributes = [FunctionWithBuiltinPrefix, NoThrow,
                    ConstIgnoringErrnoAndExceptions];
  let Prototype = "T(T)";

  def CosF16F128 : Builtin, F16F128MathTemplate {
    let Spellings = ["__builtin_cos"];
    let Attributes = [FunctionWithBuiltinPrefix, NoThrow, ConstIgnoringErrnoAndExceptions];
    let Prototype = "T(T)";
  }
```
There is no equivalent in `clang/include/clang/Basic/Builtins.td` for Tan however tan builins are already defined in `<build_dir>/tools/clang/include/clang/Basic/Builtins.inc` Like So:

```
BUILTIN(__builtin_tanf, "ff", "Fne")
LIBBUILTIN(tanf, "ff", "fne", MATH_H, ALL_LANGUAGES)
BUILTIN(__builtin_tan, "dd", "Fne")
LIBBUILTIN(tan, "dd", "fne", MATH_H, ALL_LANGUAGES)
BUILTIN(__builtin_tanl, "LdLd", "Fne")
LIBBUILTIN(tanl, "LdLd", "fne", MATH_H, ALL_LANGUAGES)
BUILTIN(__builtin_tanf128, "LLdLLd", "Fne")
BUILTIN(__builtin_tanhf, "ff", "Fne")
LIBBUILTIN(tanhf, "ff", "fne", MATH_H, ALL_LANGUAGES)
BUILTIN(__builtin_tanh, "dd", "Fne")
LIBBUILTIN(tanh, "dd", "fne", MATH_H, ALL_LANGUAGES)
BUILTIN(__builtin_tanhl, "LdLd", "Fne")
LIBBUILTIN(tanhl, "LdLd", "fne", MATH_H, ALL_LANGUAGES)
BUILTIN(__builtin_tanhf128, "LLdLLd", "Fne")
LIBBUILTIN(__tanpif, "ff", "fne", MATH_H, ALL_LANGUAGES)
LIBBUILTIN(__tanpi, "dd", "fne", MATH_H, ALL_LANGUAGES)
```
Adding the builtin didn't seem right as it would conflict.

Since they already exist maybe I can just use them?  That leads me to reason 2.

Reason 2 to exclude for now the scalar cos\sin calls all have constrained fp  usages as part of code gen in `clang/lib/CodeGen/CGBuiltin.cpp`. This would increase the testing burden for this change. getting a `experimental_constrained_tan` working seems to be  beyond the scope of what I wanted to accomplish with this pr.

examples:
```cpp
  case Builtin::BI__builtin_cos:
  case Builtin::BI__builtin_cosf:
  case Builtin::BI__builtin_cosf16:
  case Builtin::BI__builtin_cosl:
  case Builtin::BI__builtin_cosf128:
    return RValue::get(emitUnaryMaybeConstrainedFPBuiltin(*this, E,
                                 Intrinsic::cos,
                                 Intrinsic::experimental_constrained_cos));
  
  case Builtin::BI__builtin_sin:
  case Builtin::BI__builtin_sinf:
  case Builtin::BI__builtin_sinf16:
  case Builtin::BI__builtin_sinl:
  case Builtin::BI__builtin_sinf128:
    return RValue::get(emitUnaryMaybeConstrainedFPBuiltin(*this, E,
                                 Intrinsic::sin,
                                 Intrinsic::experimental_constrained_sin));

```

**Comment by farzonl** [comment]
Hi @efriedma-quic @RKSimon when you have time could I get a review? Thank you!

**Comment by farzonl** [comment]
> I'm worried if we add a whole new series of math intrinsics without adding the corresponding constrained intrinsics, it's going to be confusing for anyone trying to understand how math intrinsics work. Why does tan exist, but not constrained tan?
> 
> `tan` is defined basically the same way as `sin` in Builtins.td; the only difference is that instead of `def SinF16F128 : Builtin, F16F128MathTemplate`, there's just `def TanF128 : Builtin {` (so no f16 support).

@efriedma-quic Would you be open to me making a new issue to support constrained intrinsics. I'll need to spend some time to see what's required to support them and I didn't want the current set of changes to go stale.

**Comment by efriedma-quic** [comment]
> I didn't want the current set of changes to go stale.

How many changes are we talking about here?  If it's just the tan() ones, that's fine; it probably makes sense to land constrained-tan separately anyway.

**Comment by farzonl** [comment]
> > I didn't want the current set of changes to go stale.
> 
> How many changes are we talking about here? If it's just the tan() ones, that's fine; it probably makes sense to land constrained-tan separately anyway.

There are 4 for tan. There will be more for the other intrinsics listed in the RFC. This one and three backends. There will be a 5th for arm64 after the x86 changes land.

1. https://github.com/llvm/llvm-project/pull/90276
2. https://github.com/llvm/llvm-project/pull/90277
3. https://github.com/llvm/llvm-project/pull/90278
4. https://github.com/llvm/llvm-project/pull/90503

I'll get started on landing the constrained-tan as part 6 after this change makes it.

**Review by efriedma-quic — APPROVED** [review]
Okay.  I mostly just want to make sure the plan isn't "land all the intrinsics from the RFC, then eventually investigate the constrained intrinsics".

LGTM

**Review by bogner — APPROVED** [review]

**Pull request merged**
