### PR TITLE
[libclang/python] Change minimum Python test version to 3.8

### LINKED ISSUE #95209: [clang/python] check-clang-python currently fails due to outdated Python version
Since upgrading the minimum Python version recently, https://github.com/llvm/llvm-project/commit/33f4a77d9218c1a2d5c994a8a8398479731612dc the `check-clang-python` test for the Clang-Python-Bindings are failing (see https://github.com/llvm/llvm-project/actions/workflows/libclang-python-tests.yml) as those are still testing for Python 3.7. This should be upgraded to the new minimum version of 3.8.

### PR DESCRIPTION
**Pull request by DeinAlptraum**
This fixes #95209

### CODE REVIEW

**Comment by DeinAlptraum** [comment]
@boomanaiden154 @Endilll hope you are the right people to ping for this

**Review by Endilll — APPROVED** [review]
LGTM, but wait for more approvals.

**Review by boomanaiden154 — APPROVED** [review]
LGTM.

**Comment by DeinAlptraum** [comment]
I don't quite understand how the concurrency-cancelling thing works, but it seems that the test for 3.8 was cancelled... would be surprised if this fails, but just in case it would be nice if one of you could restart the bindings 3.8 test

**Comment by Endilll** [comment]
Despite status not showing it, both Python 3.8 and 3.11 runs finished successfully across two different runs:
https://github.com/llvm/llvm-project/actions/runs/9479974893/attempts/2?pr=95210
https://github.com/llvm/llvm-project/actions/runs/9479974893/attempts/3?pr=95210

**Pull request merged**
