### PR TITLE
[libcxx][test] Use long double test macro in strong_order.pass.cpp

### PR DESCRIPTION
**Pull request by DavidSpickett**

### CODE REVIEW

**Comment by DavidSpickett** [comment]
@frederick-vs-ja is this what you meant?

I left the UNIMPLEMENTED comment there because it seems useful to know that there is a feature gap there, as opposed to it being some completely invalid construct.

**Review by ldionne — APPROVED** [review]
This LGTM but I'd like @frederick-vs-ja to give final approval since his this PR originated from a comment he made.

**Review by philnik777 — APPROVED** [review]
LGTM assuming the CI is green.

**Review by frederick-vs-ja — APPROVED** [review]
LGTM. The "16 byte" part in the comments is a bit imprecise as if `long double` is of Intel 80-bit format and the platform is 32-bit, `sizeof(long dobule)` is usually 12. But I think we can improve this later.

**Comment by DavidSpickett** [comment]
Well, "> 8 bytes" seems to cover that right?

**Comment by DavidSpickett** [comment]
Ah, no it's just when long double is a *distinct* type. Whatever size that may be. I will update the comments.

**Pull request merged**
