### PR TITLE
[mlir][openacc] Add device_type support for compute operations

### PR DESCRIPTION
**Pull request by clementval**
This patch adds representation for `device_type` clause information on compute construct (parallel, kernels, serial).

The `device_type` clause on compute construct impacts clauses that appear after it. The values impacted by `device_type` are now tied with an attribute array that represent the device_type associated with them. `DeviceType::None` is used to represent the value produced by a clause before any `device_type`. The operands and the attribute information are parser/printed together. 

This is an example with `vector_length` clause. The first value (64) is not impacted by `device_type` so it will be represented with DeviceType::None. None is not printed. The second value (128) is tied with the `device_type(multicore)` clause. 
```
!$acc parallel vector_length(64) device_type(multicore) vector_length(256)
```
```
acc.parallel vector_length(%c64 : i32, %c128 : i32 [#acc.device_type<multicore>]) {
}
```

When multiple values can be produced for a single clause like `num_gangs` and `wait`, an extra attribute describe the number of values belonging to each `device_type`. Values and attributes are parsed/printed together. 

```
acc.parallel num_gangs({%c2 : i32, %c4 : i32}, {%c4 : i32} [#acc.device_type<nvidia>])
```

While preparing this patch I noticed that the wait devnum is not part of the operations and is not lowered. It will be added in a follow up patch.

### CODE REVIEW

**Review by razvanlupusoru — APPROVED** [review]
Wow! This is outstanding. The design and implementation make sense to me. I prefer this over other techniques (such as duplicating and specializing regions per device_type at this level). I like the getters that simplify access to the information. Thank you for this!

**Review by vzakhari — APPROVED** [review]
Looks great!

**Comment by vitalybuka** [comment]
Here is a broken bot https://lab.llvm.org/buildbot/#/builders/5/builds/39439/steps/9/logs/stdio
Could you fix or revert?

**Comment by clementval** [comment]
> Here is a broken bot https://lab.llvm.org/buildbot/#/builders/5/builds/39439/steps/9/logs/stdio Could you fix or revert?

Sorry about that. I'll revert it for now since I don't have time to fix it in the next 1-2 hours.

**Comment by clementval** [comment]
> Here is a broken bot https://lab.llvm.org/buildbot/#/builders/5/builds/39439/steps/9/logs/stdio Could you fix or revert?

By the way, there is no email send for this failure. Is that normal?

**Comment by vitalybuka** [comment]
> > Here is a broken bot https://lab.llvm.org/buildbot/#/builders/5/builds/39439/steps/9/logs/stdio Could you fix or revert?
> 
> By the way, there is no email send for this failure. Is that normal?

Search email for "sanitizer-x86_64-linux-fast", I've got email for a followup build for the same leak because I am in blame list.

**Comment by vitalybuka** [comment]
> > > Here is a broken bot https://lab.llvm.org/buildbot/#/builders/5/builds/39439/steps/9/logs/stdio Could you fix or revert?
> > 
> > 
> > By the way, there is no email send for this failure. Is that normal?
> 
> Search email for "sanitizer-x86_64-linux-fast", I've got email for a followup build for the same leak because I am in blame list.

cmake/lit or whatever still continues to execute the test binary for incremental builds even after revert :(

**Comment by clementval** [comment]
> > > > Here is a broken bot https://lab.llvm.org/buildbot/#/builders/5/builds/39439/steps/9/logs/stdio Could you fix or revert?
> > > 
> > > 
> > > By the way, there is no email send for this failure. Is that normal?
> > 
> > 
> > Search email for "sanitizer-x86_64-linux-fast", I've got email for a followup build for the same leak because I am in blame list.
> 
> cmake/lit or whatever still continues to execute the test binary for incremental builds even after revert :(

I saw that but I don't know what to do besides reverting my change. I asked on discourse in the sanitizer channel but not reply so far.

**Comment by vitalybuka** [comment]
> I saw that but I don't know what to do besides reverting my change. I asked on discourse in the sanitizer channel but not reply so far.

I will just reset bots. Thanks for revert.

**Comment by clementval** [comment]
> I will just reset bots. Thanks for revert.

Thanks!

**Pull request merged**
