### PR TITLE
[LLD] [COFF] Clarify -print-search-path for the empty string element

### PR DESCRIPTION
**Pull request by mstorsjo**
Also switch the test case to use -NEXT to strictly match all lines.

### CODE REVIEW

**Review by tru — APPROVED** [review]
Looks good, but I wonder about the `(cwd)` - couldn't we print the actual cwd in that case?

**Comment by mstorsjo** [comment]
> Looks good, but I wonder about the `(cwd)` - couldn't we print the actual cwd in that case?

I guess we could, although that's a bit messier with respect to tests. (Also, perhaps it kinda loses a little bit of distinction between whether the path actually was specified as an absolute path or not - which probably isn't important?)

In all honesty, it was just the quickest solution I had for making this clearer in tests; I also considered wrapping the path in quotes, which makes it clear that we have one entry with an empty path. But Clang's printing of include directories is a similar feature, which doesn't quote the paths, so I felt it was better to go with consistency with that.

**Review by zmodem — APPROVED** [review]
lgtm

**Comment by tru** [comment]
> > Looks good, but I wonder about the `(cwd)` - couldn't we print the actual cwd in that case?
> 
> I guess we could, although that's a bit messier with respect to tests. (Also, perhaps it kinda loses a little bit of distinction between whether the path actually was specified as an absolute path or not - which probably isn't important?)
> 
> In all honesty, it was just the quickest solution I had for making this clearer in tests; I also considered wrapping the path in quotes, which makes it clear that we have one entry with an empty path. But Clang's printing of include directories is a similar feature, which doesn't quote the paths, so I felt it was better to go with consistency with that.

I am fine with this!

**Comment by mstorsjo** [comment]
> > > Looks good, but I wonder about the `(cwd)` - couldn't we print the actual cwd in that case?
> > 
> > 
> > I guess we could, although that's a bit messier with respect to tests. (Also, perhaps it kinda loses a little bit of distinction between whether the path actually was specified as an absolute path or not - which probably isn't important?)
> > In all honesty, it was just the quickest solution I had for making this clearer in tests; I also considered wrapping the path in quotes, which makes it clear that we have one entry with an empty path. But Clang's printing of include directories is a similar feature, which doesn't quote the paths, so I felt it was better to go with consistency with that.
> 
> I am fine with this!

Ok, great, thanks! I also checked, and it doesn't look like lit has got a substitution for the cwd similar to how it has got `%t` and `%S` and such.

**Pull request merged**
