### PR TITLE
update_test_checks: recognize %if in RUN line

### PR DESCRIPTION
**Pull request by ElvinaYakubova**
Recognize %if for target-specific cases in RUN line and keep only tool command with options

### CODE REVIEW

**Review by RKSimon — COMMENTED** [review]
test case?

**Comment by arichardson** [comment]
It would be good to move any of this parsing to common so that the other update scripts also benfit from this (cc_test_checks, llc_test_checks, mir_test_checks).

I think the ideal solution would be to reuse lit code parse the RUN lines instead of re-implementing most of the syntax in these scripts. I started working on that a while ago but never got around to finishing it.

**Comment by ElvinaYakubova** [comment]
> test case?

added test case

**Comment by ElvinaYakubova** [comment]
> It would be good to move any of this parsing to common so that the other update scripts also benfit from this (cc_test_checks, llc_test_checks, mir_test_checks).
> 
> I think the ideal solution would be to reuse lit code parse the RUN lines instead of re-implementing most of the syntax in these scripts. I started working on that a while ago but never got around to finishing it.

do you have an open PR or branch in your fork repo for that?

**Comment by ElvinaYakubova** [comment]
gentle ping @RKSimon 
Can I merge these changes now, and work on moving parsing to the common level as a separate task?

**Review by RKSimon — APPROVED** [review]

**Pull request merged**
