### PR TITLE
[AMDGPU][Attributor] Don't run `AAAddressSpace` for graphics functions

### PR DESCRIPTION
**Pull request by shiltian**

### CODE REVIEW

**Comment by shiltian** [comment]
* **#108560** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/108560?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shiltian and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by arsenm** [comment]
No test and I wouldn't bother skipping it? Do compute shaders really not have flat addresses?

**Comment by shiltian** [comment]
> No test and I wouldn't bother skipping it? Do compute shaders really not have flat addresses?

That's what you said:

https://github.com/llvm/llvm-project/blob/9e462b7ea23ea864b1f3f3b72d25cfbed95149d5/llvm/lib/Target/AMDGPU/AMDGPUTargetTransformInfo.h#L204

**Comment by shiltian** [comment]
> I wouldn't bother skipping it

If we don't want to bother skipping it, do we want to do the same thing for `InferAddressSpacePass`? This can allow the TTI version of `getFlatAddressSpace` to go.

**Comment by arsenm** [comment]
> > I wouldn't bother skipping it
> 
> If we don't want to bother skipping it, do we want to do the same thing for `InferAddressSpacePass`? This can allow the TTI version of `getFlatAddressSpace` to go.

I'm pretty sure that field is just broken and should be removed. It is initialized by whatever function happens to be first when constructing the TTIImpl. The TTI is owned by the subtarget, which is unique per subtarget, not function

**Comment by arsenm** [comment]
> I'm pretty sure that field is just broken and should be removed. It is initialized by whatever function happens to be first when constructing the TTIImpl. The TTI is owned by the subtarget, which is unique per subtarget, not function

Maybe this is wrong, there are other function dependent fields here

**Comment by shiltian** [comment]
> > I'm pretty sure that field is just broken and should be removed. It is initialized by whatever function happens to be first when constructing the TTIImpl. The TTI is owned by the subtarget, which is unique per subtarget, not function
> 
> Maybe this is wrong, there are other function dependent fields here

It is per-function, which is created by a target dependent approach, such as `GCNTargetMachine::getTargetTransformInfo`.

**Comment by shiltian** [comment]
This is handled directly in `AAAddressSpaceInfo`, as shown in https://github.com/llvm/llvm-project/pull/108713, so this PR is no longer needed.

**Pull request closed without merging**
