### PR TITLE
Ensure that the executable module is ModuleList[0]

### PR DESCRIPTION
**Pull request by jimingham**
We claim in a couple places that the zeroth element of the module list for a target is the main executable, but we don't actually enforce that in the ModuleList class.  As we saw, for instance, in

32dd5b20973bde1ef77fa3b84b9f85788a1a303a

it's not all that hard to get this to be off.  This patch ensures that the first object file of type Executable added to it is moved to the front of the ModuleList.  I also added a test for this.

In the normal course of operation, where the executable is added first, this only adds a check for whether the first element in the module list is an executable.  If that's true, we just append as normal.

Note, the code in Target::GetExecutableModule doesn't actually agree that the zeroth element must be the executable, it instead returns the first Module of type Executable.  But I can't tell whether that was a change in intention or just working around the bug that we don't always maintain this ordering.  But given we've said this in scripting as well as internally, I think we shouldn't change our minds about this.

### CODE REVIEW

**Review by clayborg — APPROVED** [review]
Looks good to me.

**Review by JDevlieghere — APPROVED** [review]
LGTM!

**Comment by petrhosek** [comment]
`lldb-api :: functionalities/executable_first/TestExecutableFirst.py` is failing on our Linux builders with the following error:
```
Script:
--
/b/s/w/ir/x/w/lldb_install/python3/bin/python3 /b/s/w/ir/x/w/llvm-llvm-project/lldb/test/API/dotest.py -u CXXFLAGS -u CFLAGS --env ARCHIVER=/b/s/w/ir/x/w/cipd/bin/llvm-ar --env OBJCOPY=/b/s/w/ir/x/w/cipd/bin/llvm-objcopy --env LLVM_LIBS_DIR=/b/s/w/ir/x/w/llvm_build/./lib --env LLVM_INCLUDE_DIR=/b/s/w/ir/x/w/llvm_build/include --env LLVM_TOOLS_DIR=/b/s/w/ir/x/w/llvm_build/./bin --libcxx-include-dir /b/s/w/ir/x/w/llvm_build/include/c++/v1 --libcxx-include-target-dir /b/s/w/ir/x/w/llvm_build/include/x86_64-unknown-linux-gnu/c++/v1 --libcxx-library-dir /b/s/w/ir/x/w/llvm_build/./lib/x86_64-unknown-linux-gnu --arch x86_64 --build-dir /b/s/w/ir/x/w/llvm_build/lldb-test-build.noindex --lldb-module-cache-dir /b/s/w/ir/x/w/llvm_build/lldb-test-build.noindex/module-cache-lldb/lldb-api --clang-module-cache-dir /b/s/w/ir/x/w/llvm_build/lldb-test-build.noindex/module-cache-clang/lldb-api --executable /b/s/w/ir/x/w/llvm_build/./bin/lldb --compiler /b/s/w/ir/x/w/llvm_build/./bin/clang --dsymutil /b/s/w/ir/x/w/llvm_build/./bin/dsymutil --llvm-tools-dir /b/s/w/ir/x/w/llvm_build/./bin --lldb-libs-dir /b/s/w/ir/x/w/llvm_build/./lib /b/s/w/ir/x/w/llvm-llvm-project/lldb/test/API/functionalities/executable_first -p TestExecutableFirst.py
--
Exit Code: 1

Command Output (stdout):
--
lldb version 18.0.0git (https://llvm.googlesource.com/a/llvm-project revision a4cd99ea8736eda2b8b4de34453f55008bcf9c30)
  clang revision a4cd99ea8736eda2b8b4de34453f55008bcf9c30
  llvm revision a4cd99ea8736eda2b8b4de34453f55008bcf9c30
Skipping the following test categories: ['dsym', 'gmodules', 'debugserver', 'objc']
This is the first test, this one succeeds

--
Command Output (stderr):
--
FAIL: LLDB (/b/s/w/ir/x/w/llvm_build/bin/clang-x86_64) :: test_executable_is_first_before_run (TestExecutableFirst.TestExecutableIsFirst)
FAIL: LLDB (/b/s/w/ir/x/w/llvm_build/bin/clang-x86_64) :: test_executable_is_first_during_run (TestExecutableFirst.TestExecutableIsFirst)
======================================================================
FAIL: test_executable_is_first_before_run (TestExecutableFirst.TestExecutableIsFirst)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/s/w/ir/x/w/llvm-llvm-project/lldb/test/API/functionalities/executable_first/TestExecutableFirst.py", line 32, in test_executable_is_first_before_run
    self.assertEqual(module, first_module, "This executable is the first module")
AssertionError: (x86_64) /b/s/w/ir/x/w/llvm_build/lldb-test-build.noindex/functionalities/executable_first/TestExecutableFirst.test_executable_is_first_before_run/a.out != (x86_64) /b/s/w/ir/x/w/llvm_build/lldb-test-build.noindex/functionalities/executable_first/TestExecutableFirst.test_executable_is_first_before_run/libbar.so : This executable is the first module
Config=x86_64-/b/s/w/ir/x/w/llvm_build/bin/clang
======================================================================
FAIL: test_executable_is_first_during_run (TestExecutableFirst.TestExecutableIsFirst)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/b/s/w/ir/x/w/llvm-llvm-project/lldb/test/API/functionalities/executable_first/TestExecutableFirst.py", line 43, in test_executable_is_first_during_run
    (target, process, thread, bkpt) = lldbutil.run_to_source_breakpoint(
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/x/w/llvm-llvm-project/lldb/packages/Python/lldbsuite/test/lldbutil.py", line 1009, in run_to_source_breakpoint
    return run_to_breakpoint_do_run(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/b/s/w/ir/x/w/llvm-llvm-project/lldb/packages/Python/lldbsuite/test/lldbutil.py", line 906, in run_to_breakpoint_do_run
    test.fail(
AssertionError: Test process is not stopped at breakpoint: state: exited, exit code: 127, stdout: '/b/s/w/ir/x/w/llvm_build/lldb-test-build.noindex/functionalities/executable_first/TestExecutableFirst.test_executable_is_first_during_run/a.out: error while loading shared libraries: libbar.so: cannot open shared object file: No such file or directory
'
Config=x86_64-/b/s/w/ir/x/w/llvm_build/bin/clang
----------------------------------------------------------------------
Ran 2 tests in 0.298s

RESULT: FAILED (0 passes, 2 failures, 0 errors, 0 skipped, 0 expected failures, 0 unexpected successes)

--
```
Do you know what might be the issue?

**Comment by labath** [comment]
The problem is that linux/elf does not really have hard line between shared libraries, (position-independent) executables and the dynamic linker. they all have `e_type = ET_DYN` in their header. It is possible to create a shared library that can also be executed (unless one is *extremely* careful it will crash very quickly, but that crash may exactly be something that one may want to observe in a debugger). It's probably also possible to create a library that will also serve as the dynamic loader.

So, the "is this module an executable" question is not really well defined. This isn't an intrinsic property of the module, but rather a role that the module plays in a specific process. Once a process starts, this can be (and is) determined by the dynamic linker plugin. Before that, we need to rely on some external signal for that (if we need to know that at all).

With that in mind, I'm going to disable the before-run part of the test for elf.

**Comment by jimingham** [comment]
This one should have been fixed by the follow-on commit.  When you use a shared library on Linux you have to bless it somehow - which in the test suite means adding an "extra_images" argument to run_to_***_breakpoint, which I forgot to do.

Jim

**Comment by jimingham** [comment]
Will the value of ObjectFile::GetType ever be meaningful, then?  Do you change it after running based on what the loader tells you?  If that's not meaningful, then we probably should have some "ObjectFile::TypeIsMeaningful" and gate all this logic on that as well.

Jim

**Comment by jimingham** [comment]
So long as ObjectFileELF::CalculateType never returns ET_EXEC, this won't be an issue.  But if some ObjectFile that's not in fact the main binary says it has this type, not only will this change to Append not do the right thing, Target::GetExecutableModule will also return this module.  I'm not sure this actually matters much on Linux.  For Swift we use the main executable because that has some info we need to reconstruct the swift debugging environment, so it's somewhat important for us.  But maybe it doesn't matter much for Linux.

But it would still be nice to know whether to take this return seriously or nowt.

Jim

**Comment by labath** [comment]
> Will the value of ObjectFile::GetType ever be meaningful, then? 

It's partially meaningful. eTypeCoreFile, eTypeObjectFile and eTypeExecutable (when it is set) should mean what they say. The problem is with eTypeSharedLibrary (and to a lesser degree with eTypeDebugInfo). Just because an object is a shared library doesn't mean that it can be executed (as the main executable or the dynamic linker). It's not that these concepts don't exist, it's just that it's not possible to determine the role of a file in isolation. I don't think that was anyone's intention, it's just ELF (unlike, say, MachO) doesn't have the flags to differentiate these.

> Do you change it after running based on what the loader tells you?

We don't, and I don't think we should, because that's about a role that the object plays in a specific process. In theory you could use that object in a different role in another process.

> So long as ObjectFileELF::CalculateType never returns ET_EXEC, this won't be an issue. But if some ObjectFile that's not in fact the main binary says it has this type, not only will this change to Append not do the right thing, Target::GetExecutableModule will also return this module.

CalculateType() will return eTypeExecutable for ET_EXEC, which is used for non-position-independent executables, and I don't think you can load those as libraries (the dynamic loader will not let them. However, there is nothing stopping a user from adding that module manually (exactly like your test does) and that could mess things up a bit. Not too much, because (outside of Swift, I guess) we don't care that much about which module is the main executable, but it will confuse anyone who asks for it. To be honest, I don't particularly like this functionality of automatically shuffling module lists. I think it would be better to have separate API to set the executable module or tag an existing module as such. It's probably the only thing that can reliably work for elf, but I also think its clearer/more explicit in general.

**Comment by jimingham** [comment]
> On Jan 18, 2024, at 8:41 AM, Pavel Labath ***@***.***> wrote:
> 
> 
> Will the value of ObjectFile::GetType ever be meaningful, then?
> 
> It's partially meaningful. eTypeCoreFile, eTypeObjectFile and eTypeExecutable (when it is set) should mean what they say. The problem is with eTypeSharedLibrary (and to a lesser degree with eTypeDebugInfo). Just because an object is a shared library doesn't mean that it can be executed (as the main executable or the dynamic linker). It's not that these concepts don't exist, it's just that it's not possible to determine the role of a file in isolation. I don't think that was anyone's intention, it's just ELF (unlike, say, MachO) doesn't have the flags to differentiate these.
> 
> Do you change it after running based on what the loader tells you?
> 
> We don't, and I don't think we should, because that's about a role that the object plays in a specific process. In theory you could use that object in a different role in another process.
> 
> So long as ObjectFileELF::CalculateType never returns ET_EXEC, this won't be an issue. But if some ObjectFile that's not in fact the main binary says it has this type, not only will this change to Append not do the right thing, Target::GetExecutableModule will also return this module.
> 
> CalculateType() will return eTypeExecutable for ET_EXEC, which is used for non-position-independent executables, and I don't think you can load those as libraries (the dynamic loader will not let them. However, there is nothing stopping a user from adding that module manually (exactly like your test does) and that could mess things up a bit. Not too much, because (outside of Swift, I guess) we don't care that much about which module is the main executable, but it will confuse anyone who asks for it. To be honest, I don't particularly like this functionality of automatically shuffling module lists. I think it would be better to have separate API to set the executable module or tag an existing module as such. It's probably the only thing that can reliably work for elf, but I also think its clearer/more explicit in general.
> 
We have API to do both get and set main executable.  They currently find the first eTypeExecutable in the list and if there isn't one returns the first element in the list.  But before the Get was added we relied on the main executable being the first in the list. I didn't do an exhaustive search, but I couldn't find any places internally that just dial up the 0th element, what I could find uses the API's.  But we have said the main executable will be the first in the list through the SB API's.  We can decide we don't want to support that list ordering anymore, and you have to use the API.  But we try not to change things we've told people were true about the SB API's out from under them.

Jim

**Pull request merged**
