### PR TITLE
[mlir][transform] Update transform.loop.peel

### PR DESCRIPTION
**Pull request by banach-space**
This patch updates `transform.loop.peel` so that this Op returns two
rather than one handle:
  * one for the peeled loop, and
  * one for the remainder loop.

Also, following this change this Op will fail if peeling fails. This is
consistent with other similar Ops that also fail if no transformation
takes place.

### CODE REVIEW

**Review by ftynse — APPROVED** [review]
Could we double-check that if one iteration is peeled off, the loop is still present in the IR, and the handle expectedly points to that loop?

Also FYI, I quickly looked at the internals of the peeling implementation and it mixes Rewriter-based and direct IR mutation, which may lead to crashes that are fun to debug.

**Comment by banach-space** [comment]
> Could we double-check that if one iteration is peeled off, the loop is still present in the IR, and the handle expectedly points to that loop?

Sure, added extra verification in a follow-up fix-up commit.

> 
> Also FYI, I quickly looked at the internals of the peeling implementation and it mixes Rewriter-based and direct IR mutation, which may lead to crashes that are fun to debug.

Thanks for the heads-up! ATM I am using this to play around with vectorisation of the remainder loop and it works fine ™️ 🤞🏻 .

**Comment by aartbik** [comment]
This broke a bot:

Failed Tests (1):
  MLIR :: python/dialects/transform_loop_ext.py

**Comment by banach-space** [comment]
> This broke a bot:
> 
> Failed Tests (1): MLIR :: python/dialects/transform_loop_ext.py

Sorry about that, patch reverted. I forgot about the Python bindings :(

**Pull request merged**
