### PR TITLE
[llvm] Remove `inline constexpr` from AArch64TargetParser.h

### PR DESCRIPTION
**Pull request by rsuderman**
The use of `inline constexpr` appears to be a premature optimization that can cause failures on some platforms. StringRef has a heavy constructor that can be missed on dylib loading causing the `Extension` table values to be incorrect. Switching from `inline constexpr` to `const` results in no increase in binary size of `llc` indicating the optimization is unnecessary.

### CODE REVIEW

**Comment by topperc** [comment]
Does using StringLiteral instead of StringRef in the struct help? It has a more specialized constructor for constexpr.

**Comment by rsuderman** [comment]
> Does using `StringLiteral` instead of `StringRef` in the struct help? It has a more specialized constructor for constexpr.

I attempted to replace with `StringLiteral` instead of StringRef however some of the constructors use empty list initializers which is not supported by the `StringLiteral` constructors.

**Comment by topperc** [comment]
> > Does using `StringLiteral` instead of `StringRef` in the struct help? It has a more specialized constructor for constexpr.
> 
> I attempted to replace with `StringLiteral` instead of StringRef however some of the constructors use empty list initializers which is not supported by the `StringLiteral` constructors.

Does using "" instead of the empty list initializer work?

>I performed the replacement for the cases where it was possible and it still did not avoid the `Extension` tables corruption issue.

What does where it was possible mean? What change did you make?

**Comment by qcolombet** [comment]
Given other targets use `const` in similar situation, that sounds reasonable, but I don't know that part of the code base at all.
So take my comment with a grain of salt.

**Comment by topperc** [comment]
Why are these arrays declared in the .h file? They appear to only be used by AArch64TargetParser.cpp

**Comment by rsuderman** [comment]
> Why are these arrays declared in the .h file? They appear to only be used by AArch64TargetParser.cpp

Sadly they do have uses outside of the target parser. E.g. in `llvm-project/clang/lib/Basic/Targets/AArch64.cpp`

**Comment by tmatheson-arm** [comment]
Just to add some context: IIRC, `inline constexpr` was used to guarantee that these objects had unique addresses, which was necessary because some equality checks were based on address. That turned out to be unworkable and was removed, so I think the `inline constexpr` is no longer necessary. It wasn't for optimisation.

**Pull request closed without merging**
