### PR TITLE
[NFC][cxxabi] Apply `cp-to-llvm.sh`

### PR DESCRIPTION
**Pull request by chestnykh**

### CODE REVIEW

**Comment by chestnykh** [comment]
This script(?) inserted new include which is absent

**Comment by nico** [comment]
Looks like that include is from https://reviews.llvm.org/D144252 / a7aade1f36eb60161235b66bca46db12e5326a0c by @philnik777 and wasn't synced either.

@philnik777, we can't have ItaniumDemangle.h include __cxxabi_config.h, see libcxxabi/src/demangle/README.txt. It looks like it's only used to check if we're using clang, which can be done with `#if defined(__clang__)`.

So I think the thing to do is:

1. Make PR to remove that include. I can do that.
2. Update this PR after that PR is in.

**Comment by nico** [comment]
Can you re-run the script?

**Comment by chestnykh** [comment]
> #101971 is in. Can you re-run the script?

Ofc, done

**Comment by ldionne** [comment]
We could / should have a CI step that checks that these files are synchronized. This happens often enough.

Even better would be to avoid the duplication, but unless we want to invest more engineering into making that work, we could at least catch it with CI.

**Pull request merged**
