### PR TITLE
[X86][vectorcall] Do not consume register for indirect return value

### PR DESCRIPTION
**Pull request by phoebewang**
This is how MSVC handles it. https://godbolt.org/z/Eav3vx7cd

### CODE REVIEW

**Review by efriedma-quic — COMMENTED** [review]
It looks like MSVC also applies this rule to fastcall.

Maybe put a boolean in the "state" to try to group together the code for specific conventions, instead of directly checking the CC.

**Comment by phoebewang** [comment]
> It looks like MSVC also applies this rule to fastcall.

Good catch, done!
 
> Maybe put a boolean in the "state" to try to group together the code for specific conventions, instead of directly checking the CC.

There are 3 special conventions here: vectorcall, fastcall and regcall. We sometime check them all, sometime check one or two of them. I think it's impossible to use one boolean to group them.

**Review by efriedma-quic — APPROVED** [review]
LGTM

I meant, at the beginning of X86_32ABIInfo::computeInfo there's a chain of if statements that set up the properties of different calling conventions, and maybe some bits could be set there.  If you don't think that makes sense, though, it's fine.

**Comment by phoebewang** [comment]
> I meant, at the beginning of X86_32ABIInfo::computeInfo there's a chain of if statements that set up the properties of different calling conventions, and maybe some bits could be set there. If you don't think that makes sense, though, it's fine.

Thanks @efriedma-quic! I prefer to using the convention name directly. I think it's more readable than hiding them under a state bit.

**Comment by rnk** [comment]
Thanks! I was going to say, surely this can't be right, I was pretty confident that sret pointers consume registers for these conventions, but it looks like I was mistaken. I think this bug and code dates to 661f35b0c54c79805e6b17944b155c111bc39ec3 from 2014, which I think made the C++ and "C" sret return paths similar.

You can see from this example that when C++ rules force the use of an sret indirect return, a register is consumed:
https://godbolt.org/z/W3fdn8s5Y

I think this reveals how there is more separation between the C++ and C layers of the MSVC compiler than we have in Clang. We've seen similar examples of this kind of issue on AAarch64, where we have to choose between X0 and X8 depending on whether we're doing sret for C++ reasons or architectural reasons.

**Comment by phoebewang** [comment]
> You can see from this example that when C++ rules force the use of an sret indirect return, a register is consumed:
> https://godbolt.org/z/W3fdn8s5Y

Could you explain more about the example? I didn't find where the register consumed. Don't both `copy_trivial` and `copy_nontrivial` use the same `esp + 4` to pass the pointer of sret?

**Comment by phoebewang** [comment]
> I lost the `__fastcall` or `__vectorcall` during editing, here's a fixed link: https://godbolt.org/z/46j33z8bc
> 
> You can see the load from [edx] and store to [ecx]:
> 
> ```
> NonTrivial copy_nontrivial(NonTrivial *) PROC   ; copy_nontrivial, COMDAT
>         mov     eax, DWORD PTR [edx]
>         mov     DWORD PTR [ecx], eax
> ...
> ```

Got it, thanks for the information!

**Pull request merged**
