### PR TITLE
[workflows] Avoid usage of access token in issue-write.yml

### PR DESCRIPTION
**Pull request by tstellar**
This adds a new composite workflow that allows you to download artifacts from other workflows without using an access token.

actions/download-artifact from GitHub requires an access token in order to download artifacts from a different workflow, which is why we can't use it here if we want to avoid using a token.

See https://github.com/actions/download-artifact?tab=readme-ov-file#download-artifacts-from-other-workflow-runs-or-repositories

### CODE REVIEW

**Review by bader — APPROVED** [review]
Thanks!
I'm not an expert in GitHub Actions scripts, so it's better to get the feedback from @boomanaiden154.

**Comment by tstellar** [comment]
Ping.

**Review by boomanaiden154 — COMMENTED** [review]
Minor nits.

Is there additional context for why this change is needed? I remember seeing something, but can't find it now.

We should also probably figure out what we want to support for downstreams versus what we don't. This is a decent chunk of additional complexity for something that I don't believe has any upstream benefit.

**Comment by boomanaiden154** [comment]
> This discussion has the context for this change - https://github.com/llvm/llvm-project/pull/80495#discussion_r1621256638.

Ah, thanks.

@tstellar Is there another advantage to having this upstream rather than just documenting somewhere what tokens need to be setup/with what permissions for the workflows to work?

**Comment by tstellar** [comment]
> @tstellar Is there another advantage to having this upstream rather than just documenting somewhere what tokens need to be setup/with what permissions for the workflows to work?

The advantage for upstream is that it's one less secret for us to maintain.

**Comment by tstellar** [comment]
> > @tstellar Is there another advantage to having this upstream rather than just documenting somewhere what tokens need to be setup/with what permissions for the workflows to work?
> 
> The advantage for upstream is that it's one less secret for us to maintain.

And also composite actions don't have access to secrets, so if you want to download an artifact in a composite action you need to add an extra parameter for the secret.

**Comment by boomanaiden154** [comment]
> The advantage for upstream is that it's one less secret for us to maintain.

> And also composite actions don't have access to secrets, so if you want to download an artifact in a composite action you need to add an extra parameter for the secret.

Makes sense. It would be nice if Github would allow this in the upstream action, but maybe the security argument there makes sense.

**Review by boomanaiden154 — APPROVED** [review]

**Pull request merged**
