### PR TITLE
[clang-format] Added AlignConsecutiveTableGenBreakingDAGArgColons option.

### PR DESCRIPTION
**Pull request by hnakamura5**
This is the option to specify the style of alignment of the colons inside TableGen's DAGArg.

### CODE REVIEW

**Review by HazardyKnusperkeks — APPROVED** [review]

**Comment by hnakamura5** [comment]
@HazardyKnusperkeks 
Thank you very much!
It took about 4 month with ten or more PRs for the parts of the first concept of TableGen formatting. 
You reviewed every time and gave me many valuable suggestions. I appreciate you again and again!

**Comment by HazardyKnusperkeks** [comment]
My pleasure.

**Comment by FullZing** [comment]
Hello @HazardyKnusperkeks ,
thank you for making this great support.
But I have a strange case ,  would you mind helping me to have a look at it?

```
// format1
def X_Type
    : X_I32EnumAttr<
          "Type", [I32EnumAttrCase<"A", 0>,
                   I32EnumAttrCase<"B", 1>,
                   I32EnumAttrCase<"C", 2>
]>;

// format2
def X_Type
    : X_I32EnumAttr<"Type", [I32EnumAttrCase<"A", 0>,
                             I32EnumAttrCase<"B", 1>,
                             I32EnumAttrCase<"C", 2>
]>;

// format3
def X_Type
    : X_I32EnumAttr<
          "Type",
          [I32EnumAttrCase<"A", 0>,  I32EnumAttrCase<"B", 1>,
           I32EnumAttrCase<"C", 2>
]>;

// format4
def X_Type
    : X_I32EnumAttr<
          "Type",
          [I32EnumAttrCase<"A", 0>,
           I32EnumAttrCase<"B", 1>,
           I32EnumAttrCase<"C", 2>
]>;
```
as you can see,   clang-format with tablegen produces different result for my case.
I'd like all of them has same result (for example,  format3). 
is it possible to achieve it?

**Comment by HazardyKnusperkeks** [comment]
I don't actually understand your problem. Can you open an issue and give the input, the output and the expected output, along with your `.clang-format`? You can tag me and I'll have a look at it.

**Pull request merged**
