### PR TITLE
[libc++] Refactor vector constructors to eliminate code duplication

### PR DESCRIPTION
**Pull request by winner245**
This PR refactors the std::vector's initializer_list constructors to reduce code duplication.
The constructors now call `__init_with_size` directly, reducing code duplication and improving
readability and maintainability.

### CODE REVIEW

**Review by ldionne — APPROVED** [review]
LGTM with green CI. The code previously in `vector(initializer_list)` was an exact duplicate of `__init_with_size()`.

**Comment by winner245** [comment]
Hi team,

It looks like the checks were cancelled due to my recent push to fix clang-format issues. I apologize for the inconvenience. This is my very first contribution to the LLVM project. Could someone please help me to re-trigger the checks? I appreciate all your help.

Thanks in advance,
Peng

**Review by ldionne — APPROVED** [review]

**Comment by ldionne** [comment]
@winner245 LLVM has a requirement that each commit is associated to a valid e-mail address. Can you please uncheck the "hide my email" option from your Github preferences?

**Comment by ldionne** [comment]
Thanks for your contribution!

**Pull request merged**
