### PR TITLE
[libc] Move baremetal write_to_stderr implementation to io.cpp

### PR DESCRIPTION
**Pull request by petrhosek**
This is required to avoid multiple definitions error.

### CODE REVIEW

**Review by jhuber6 — COMMENTED** [review]
What was the reason we didn't put this in an `io.cpp` again?

**Comment by petrhosek** [comment]
> What was the reason we didn't put this in an `io.cpp` again?

I'm not sure if there's any particular reason, I think we could since this is not on the hot path?

**Comment by jhuber6** [comment]
> > What was the reason we didn't put this in an `io.cpp` again?
> 
> I'm not sure if there's any particular reason, I think we could since this is not on the hot path?

Unsure if it matters that much since it's already behind `__llvm_libc_log_write` so it's not like it'll be inlined fully. Might be better to make it match `quick_build.cpp`.

**Comment by petrhosek** [comment]
> > > What was the reason we didn't put this in an `io.cpp` again?
> > 
> > 
> > I'm not sure if there's any particular reason, I think we could since this is not on the hot path?
> 
> Unsure if it matters that much since it's already behind `__llvm_libc_log_write` so it's not like it'll be inlined fully. Might be better to make it match `quick_build.cpp`.

Done

**Review by jhuber6 — APPROVED** [review]
Sorry, on second thought it's probably not required. The other targets use inline implementations of stuff like `syscall`. I'm okay with either one. I was confusing this with `quick_exit` which does implementation files more consistently.

**Review by lntue — APPROVED** [review]

**Pull request merged**
