### PR TITLE
[NFC] Fix code line exceeding 80 columns

### PR DESCRIPTION
**Pull request by jurahul**

### CODE REVIEW

**Comment by jurahul** [comment]
I got commit access, so will try it on this once approved.

**Review by s-barannikov — APPROVED** [review]

**Comment by s-barannikov** [comment]
You don't have to (and shouldn't) merge main into the branch or rebase unless there are conflicts with the main branch (explicit or implicit).

**Comment by jurahul** [comment]
Got it. I use the "Update branch" button on the GitHub UI, I guess it will show a warning or error if there is a conflict (merge conflict) and then I should do the merge manually (or implicit, i.e., something changes elsewhere which might break this PR, but there is no textual merge conflicts). Is that correct?

**Comment by jurahul** [comment]
I did see that these updates re-trigger the CI, which is wasteful.

**Comment by s-barannikov** [comment]
> Is that correct?

Yes, precisely.

**Pull request merged**
