### PR TITLE
[AMDGPU] Simplify AMDGPUDisassembler::getInstruction by removing Res.

### PR DESCRIPTION
**Pull request by jayfoad**
Remove all the code that set and tested Res. Change all convert*
functions to return void since none of them can fail. getInstruction
only has one main point of failure, after all calls to tryDecodeInst
have failed.

### CODE REVIEW

**Comment by jayfoad** [comment]
Oh, some tests are failing.

**Review by kosarev — APPROVED** [review]
LGTM.

**Comment by jayfoad** [comment]
> Oh, some tests are failing.

Fixed. I was not reporting failure when getInstruction was given less than 4 bytes to disassemble.

**Comment by kosarev** [comment]
Still LGTM.

**Pull request merged**
