### PR TITLE
[Clang][Sema] Fix templated array size calculation.

### LINKED ISSUE #41441: Inplace new-ing an array overwrites the square of the memory
|  |  |
| --- | --- |
| Bugzilla Link | [42096](https://llvm.org/bz42096) |
| Version | 8.0 |
| OS | Linux |
| CC | @dwblaikie,@DougGregor,@jfbastien,@riccibruno,@zygoloid |

## Extended Description 
When in-place new-ing a local variable of an array of trivial type, the generated code calls `memset` with the square of the size of the array, corrupting the stack.

Quick example:
```cpp
#include <new>

template <typename TYPE>
void f()
{
    typedef TYPE TArray[7];

    TArray x;
    new(&x) TArray();
}

int main()
{
    f<char>();
    f<int>();
}
```

Sample code generation can be seen for Clang 7 and 8 via godbolt:
https://godbolt.org/z/WjhFrc

### PR DESCRIPTION
**Pull request by awson**
The [last attempt](https://github.com/llvm/llvm-project/pull/89036) to fix https://github.com/llvm/llvm-project/issues/41441 has been reverted immediately.

Here I'm trying the simplest idea I've been able to come with:  skip handling dependent case in `BuildCXXNew`.

The original test (borrowed form https://github.com/llvm/llvm-project/pull/89036) passes.

Also I've created and added to the tests a minimal repro of the code https://github.com/llvm/llvm-project/pull/89036 fails on. This (obviously) also passes.

### CODE REVIEW

**Comment by awson** [comment]
@erichkeane, @cor3ntin

I see you actively reviewed (related, failed) #89036.

Could you look into this?

The idea of the fix is extremely simple: if we want to do something once, but mistakenly do it twice, just don't do it the first time.

**Review by AaronBallman — COMMENTED** [review]
Thank you for catching this! Can you please add a release note to `clang/docs/ReleaseNotes.rst` so users know about the fix?

I think these changes otherwise look good.

**Comment by erichkeane** [comment]
It seems reasonable to me, but I want @cor3ntin  to review this, he's the one who got his foot stuck in array bounds for a while :D 

However, this patch needs a few changes:

1- A better patch title, perhaps improved commit message
2- Release note

**Comment by awson** [comment]
> It seems reasonable to me, but I want @cor3ntin to review this, he's the one who got his foot stuck in array bounds for a while :D
> 
> However, this patch needs a few changes:
> 
> 1- A better patch title, perhaps improved commit message 2- Release note

1. Partially (patch title) done. After `llvm:main` merge (I've done it to sync release notes) "improved commit message" is a bit problematic, I fear.
2. Done.

**Comment by erichkeane** [comment]
> > It seems reasonable to me, but I want @cor3ntin to review this, he's the one who got his foot stuck in array bounds for a while :D
> > However, this patch needs a few changes:
> > 1- A better patch title, perhaps improved commit message 2- Release note
> 
>     1. Partially (patch title) done. After `llvm:main` merge (I've done it to sync release notes) "improved commit message" is a bit problematic, I fear.
> 
>     2. Done.

Our 'merge' process is a squash & Merge, so it really means "edit the github title and description to be more descriptive, and that is what will be picked up".  So no need to modify the actual commits.

**Review by cor3ntin — APPROVED** [review]
LGTM

**Review by erichkeane — APPROVED** [review]
LGTM, feel free to merge.

**Comment by awson** [comment]
@shafik ?

**Review by shafik — APPROVED** [review]
If you have approvals you don't have to wait for other reviewers unless they have made a comment that required a change and you them to confirm the fix or they explicitly blocked the review.

**Comment by awson** [comment]
> If you have approvals you don't have to wait for other reviewers unless they have made a comment that required a change and you them to confirm the fix or they explicitly blocked the review.

I believe I have no write access to the repo.

Could you, please, merge this?

@cor3ntin, @erichkeane, @AaronBallman ?

**Pull request merged**
