### PR TITLE
Reapply "[AMDGPU] Infer amdgpu-no-flat-scratch-init attribute in AMDGPUAttributor (#94647)"

### PR DESCRIPTION
**Pull request by jwanggit86**
This reverts commit 1ef9410a96c1d9669a6feaf03fcab8d0a4a13bd5.

This fixes the test file attributor-flatscratchinit-globalisel.ll.

### CODE REVIEW

**Comment by jwanggit86** [comment]
[PR 94647](https://github.com/llvm/llvm-project/pull/94647) was found to cause build problems after merge with upstream. It has since been reverted by commit 1ef9410a96c1d9669a6feaf03fcab8d0a4a13bd5. This PR fixes the tests that caused the build problems.

**Comment by arsenm** [comment]
Should have the git generated "Reapply..." message with reference to the original

**Comment by shiltian** [comment]
I was thinking this PR looks familiar...

**Comment by jwanggit86** [comment]
> Should have the git generated "Reapply..." message with reference to the original

I didn't notice that. Do you want me to put "Reapply <old-commit>" in the msg?

**Comment by shiltian** [comment]
Supposedly you can revert the revert to get the reapply.

**Comment by arsenm** [comment]
> Supposedly you can revert the revert to get the reapply.

Yes. You can just revert the revert and force push the PR branch to replace it

**Comment by jwanggit86** [comment]
@arsenm @kzhuravl If there are no more comments, I'm going to merge this PR.

**Review by kzhuravl — APPROVED** [review]
Looks like it is reapplying 94647 (which was already reviewed) with issues fixed. Thanks!

**Pull request merged**
