### PR TITLE
[ADT] Fix a comment typo

### PR DESCRIPTION
**Pull request by kazutakahirata**

### CODE REVIEW

**Comment by tbaederr** [comment]
Why is this NFC change a PR at all?

**Comment by kazutakahirata** [comment]
> Why is this NFC change a PR at all?

Sorry, I am trying to learn the PR workflow.  I'd appreciate an approval so I can experience the entire process.  Thanks!

**Review by MaskRay — APPROVED** [review]

**Comment by MaskRay** [comment]
Learning as well...
```
% gh pr review 65497
? What kind of review do you want to give? Approve
? Review body <Received>
? Submit? Yes
✓ Approved pull request #65497
```

**Review by mtrofin — APPROVED** [review]
lgtm

**Pull request merged**
