### PR TITLE
Added support ccache for speedup recompilation libcxx and libcxxabi

### PR DESCRIPTION
**Pull request by GermanAizek**
It will save a lot of time when checkout git branches and compile again.

### CODE REVIEW

**Comment by mordante** [comment]
Just curious, but why not using `-DCMAKE_CXX_COMPILER_LAUNCHER=ccache` instead? I use this and it works without changes to libc++.

**Comment by philnik777** [comment]
> It will save a lot of time when checkout git branches and compile again.

Will it? libc++ is very fast to compile. On my machine it takes 8 seconds for a full release build.

**Comment by vitalybuka** [comment]
It could be nice to have ccache for tests, as seems compilation is significant part of check-cxx.

**Comment by philnik777** [comment]
> It could be nice to have ccache for tests, as seems compilation is significant part of check-cxx.

Yes, but it also feels kind-of scary to cache tests. I guess it depends on what kinds of speedups we could expect whether I'd deem it worth it. We have a lot of dependencies, so it's not that unlikely that we'd have to re-compile large parts of the tests anyways. Especially when modifying headers like `<type_traits>`. Moving the jobs to use modules might be a better strategy to reduce build times.

**Comment by mordante** [comment]
> Moving the jobs to use modules might be a better strategy to reduce build times.
+1 that would also give some real coverage of modules too :-)

**Comment by vitalybuka** [comment]
> Caching the tests would provide a huge speedup but as @philnik777 mentioned, it's a really scary thing to do and defeats one of the primary goals we have in the test suite, which is to test-as-we-ship.

1. It does not need to be default ON. 
2. May help with development velocity.
3. some slow bots may benefit, like with sanitizers. When there is some risk from invalid dependency, but more build cycles likely overweight the risk.
4. To be fair, we have just 1 of ~10 bots where we can use ccache in cxx tests. The rest rebuilds compiler from the HEAD, invalidating ccache.

**Comment by philnik777** [comment]
Closing, since there are easier ways to achieve this and we don't think it makes a ton of sense for libc++.

**Pull request closed without merging**
