### PR TITLE
AArch64: Add tests for atomicrmw fp operations

### PR DESCRIPTION
**Pull request by arsenm**
There were only codegen tests for the fadd vector case,
so round out the test coverage for the scalar cases
and all the other operations.

### CODE REVIEW

**Comment by arsenm** [comment]
* **#103702** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/103702?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#103701** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/103701?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by davemgreen** [comment]
We have a decent number of atomic tests in llvm/test/CodeGen/AArch64/Atomics, but I don't believe they include fp operations yet.

**Comment by arsenm** [comment]
> We have a decent number of atomic tests in llvm/test/CodeGen/AArch64/Atomics, but I don't believe they include fp operations yet.

Grep doesn't find anything

**Comment by tmatheson-arm** [comment]
> > We have a decent number of atomic tests in llvm/test/CodeGen/AArch64/Atomics, but I don't believe they include fp operations yet.
> 
> Grep doesn't find anything

Yeah that was a TODO item I never got around to.

**Comment by arsenm** [comment]
ping

**Review by efriedma-quic — APPROVED** [review]
LGTM

**Review by arsenm — COMMENTED** [review]
I have no idea why the windows bot keeps failing on the fmin and fmax tests. The run lines are all using explicit, full triples

**Comment by arsenm** [comment]
### Merge activity

* **Aug 29, 11:32 AM EDT**: @arsenm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/103701).

**Pull request merged**
