### PR TITLE
[hwasan] Use ErrorAction::Recover in interceptors

### PR DESCRIPTION
**Pull request by vitalybuka**

### CODE REVIEW

**Review by kstoimenov — APPROVED** [review]

**Comment by mmalcomson** [comment]
I believe a similar change should also be made to the `__hwasan_loadN` and `__hwasan_storeN` calls in `COMMON_SYSCALL_PRE_READ_RANGE` and `COMMON_SYSCALL_PRE_WRITE_RANGE`.
(I.e. use the `noabort` versions).

**Comment by vitalybuka** [comment]
> I believe a similar change should also be made to the `__hwasan_loadN` and `__hwasan_storeN` calls in `COMMON_SYSCALL_PRE_READ_RANGE` and `COMMON_SYSCALL_PRE_WRITE_RANGE`. (I.e. use the `noabort` versions).

Compiler suppose to generate noreturn calls for them.
For returnable calls we use __hwasan_loadN_noabort.

**Comment by vitalybuka** [comment]
> [mmalcomson](/mmalcomson)

**Comment by TamarChristinaArm** [comment]
@vitalybuka I'm trying to backport the fixes to the GCC branches. Do I just need to backport these 4 commits?

**Pull request merged**
