### PR TITLE
[SLP]Improve minbitwidth analysis for trun'ed gather nodes.

### PR DESCRIPTION
**Pull request by alexey-bataev**
If the gather node is trunc'ed, better to trunc scalars and then gather
them rather than gather and then trunc. Trunc for scalars is free in
most cases.

### CODE REVIEW

**Review by RKSimon — APPROVED** [review]
LGTM

**Comment by kamaub** [comment]
I was able to show that this PRs latest commit caused a [llvm-test-suite](https://github.com/llvm/llvm-test-suite) regression on the [clang-ppc64le-rhel](https://lab.llvm.org/buildbot/#/builders/145): [build no. 623](https://lab.llvm.org/buildbot/#/builders/145/builds/623) and [clang-ppc64le-linux-test-suite](https://lab.llvm.org/buildbot/#/builders/95): [build no. 1412](https://lab.llvm.org/buildbot/#/builders/95/builds/1412) by reproducing [build no. 1412](https://lab.llvm.org/buildbot/#/builders/95/builds/1412)'s build steps on a branch and then reverting c5c1bd164fc8 and re-testing.

I'm sorry for the inconvenience but can you please resolve this error as soon as possible or revert if it will take too long to fix so we can bring the llvm-test-suite back to green status. If I can assist with reproducing the error please let me know.

**Comment by RKSimon** [comment]
Do we have to account for the costs of the two different gather types?

**Comment by alexey-bataev** [comment]
> I was able to show that this PRs latest commit caused a [llvm-test-suite](https://github.com/llvm/llvm-test-suite) regression on the [clang-ppc64le-rhel](https://lab.llvm.org/buildbot/#/builders/145): [build no. 623](https://lab.llvm.org/buildbot/#/builders/145/builds/623) and [clang-ppc64le-linux-test-suite](https://lab.llvm.org/buildbot/#/builders/95): [build no. 1412](https://lab.llvm.org/buildbot/#/builders/95/builds/1412) by reproducing [build no. 1412](https://lab.llvm.org/buildbot/#/builders/95/builds/1412)'s build steps on a branch and then reverting [c5c1bd1](https://github.com/llvm/llvm-project/commit/c5c1bd164fc81a992dfdb5b7c7c672dab0e3f165) and re-testing.
> 
> I'm sorry for the inconvenience but can you please resolve this error as soon as possible or revert if it will take too long to fix so we can bring the llvm-test-suite back to green status. If I can assist with reproducing the error please let me know.

Can you provide a reproducer? I cannot reproduce the issue

**Comment by kamaub** [comment]
> Can you provide a reproducer? I cannot reproduce the issue

[build no. 1412](https://lab.llvm.org/buildbot/#/builders/95/builds/1412) does not do anything special outside of build the llvm-project and test the c/c++ compilers on lllvm-test-suite, if you were able to run the affected test case on your platform using the bot's cmake configuration and it passed then it is likely a platform specific issue, in this case one of us will have to revert and investigate in the morning (I am EST zone). I can look into providing PowerPC machine access at that point.

the llvm-project build command was:
```shell
cmake-3.28.2/bin/cmake -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_BUILD_TYPE=Release -DLLVM_LIT_ARGS=-v -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache '-DLLVM_ENABLE_PROJECTS=clang-tools-extra;llvm;clang' -DLLVM_ENABLE_RUNTIMES=compiler-rt -GNinja ../llvm-project/llvm && ninja -j 128
```
and the test-suite build command was:
```shell
cmake-3.28.2/bin/cmake -G Ninja -DCMAKE_C_COMPILER=/home/kamaub/Github/llvm/mono2/test-suite-reproducer/bin/clang -DCMAKE_CXX_COMPILER=/home/kamaub/Github/llvm/mono2/test-suite-reproducer/bin/clang++ -DTEST_SUITE_LIT:FILEPATH=/home/kamaub/Github/llvm/mono2/test-suite-reproducer/bin/llvm-lit /home/kamaub/Github/llvm/test-suite && ninja -j 128 && /home/kamaub/Github/llvm/mono2/test-suite-reproducer/bin/llvm-lit -j 128 -v .
```

I do not believe you're required to run the entire suite as `llvm-lit <build-dir>` does in the above command but I forget the exact semantics to run a specific test-suite case at this time. I will update when I uncover that.

**Comment by alexey-bataev** [comment]
> > Can you provide a reproducer? I cannot reproduce the issue
> 
> [build no. 1412](https://lab.llvm.org/buildbot/#/builders/95/builds/1412) does not do anything special outside of build the llvm-project and test the c/c++ compilers on lllvm-test-suite, if you were able to run the affected test case on your platform using the bot's cmake configuration and it passed then it is likely a platform specific issue, in this case one of us will have to revert and investigate in the morning (I am EST zone). I can look into providing PowerPC machine access at that point.
> 
> the llvm-project build command was:
> 
> ```shell
> cmake-3.28.2/bin/cmake -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_BUILD_TYPE=Release -DLLVM_LIT_ARGS=-v -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache '-DLLVM_ENABLE_PROJECTS=clang-tools-extra;llvm;clang' -DLLVM_ENABLE_RUNTIMES=compiler-rt -GNinja ../llvm-project/llvm && ninja -j 128
> ```
> 
> and the test-suite build command was:
> 
> ```shell
> cmake-3.28.2/bin/cmake -G Ninja -DCMAKE_C_COMPILER=/home/kamaub/Github/llvm/mono2/test-suite-reproducer/bin/clang -DCMAKE_CXX_COMPILER=/home/kamaub/Github/llvm/mono2/test-suite-reproducer/bin/clang++ -DTEST_SUITE_LIT:FILEPATH=/home/kamaub/Github/llvm/mono2/test-suite-reproducer/bin/llvm-lit /home/kamaub/Github/llvm/test-suite && ninja -j 128 && /home/kamaub/Github/llvm/mono2/test-suite-reproducer/bin/llvm-lit -j 128 -v .
> ```
> 
> I do not believe you're required to run the entire suite as `llvm-lit <build-dir>` does in the above command but I forget the exact semantics to run a specific test-suite case at this time. I will update when I uncover that.

It is ppc specific issue, no other targets have reported the issue with the patch. That's why I ask for the PPC reproducer

**Comment by alexey-bataev** [comment]
> > Can you provide a reproducer? I cannot reproduce the issue
> 
> [build no. 1412](https://lab.llvm.org/buildbot/#/builders/95/builds/1412) does not do anything special outside of build the llvm-project and test the c/c++ compilers on lllvm-test-suite, if you were able to run the affected test case on your platform using the bot's cmake configuration and it passed then it is likely a platform specific issue, in this case one of us will have to revert and investigate in the morning (I am EST zone). I can look into providing PowerPC machine access at that point.
> 
> the llvm-project build command was:
> 
> ```shell
> cmake-3.28.2/bin/cmake -DLLVM_ENABLE_ASSERTIONS=ON -DCMAKE_BUILD_TYPE=Release -DLLVM_LIT_ARGS=-v -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache '-DLLVM_ENABLE_PROJECTS=clang-tools-extra;llvm;clang' -DLLVM_ENABLE_RUNTIMES=compiler-rt -GNinja ../llvm-project/llvm && ninja -j 128
> ```
> 
> and the test-suite build command was:
> 
> ```shell
> cmake-3.28.2/bin/cmake -G Ninja -DCMAKE_C_COMPILER=/home/kamaub/Github/llvm/mono2/test-suite-reproducer/bin/clang -DCMAKE_CXX_COMPILER=/home/kamaub/Github/llvm/mono2/test-suite-reproducer/bin/clang++ -DTEST_SUITE_LIT:FILEPATH=/home/kamaub/Github/llvm/mono2/test-suite-reproducer/bin/llvm-lit /home/kamaub/Github/llvm/test-suite && ninja -j 128 && /home/kamaub/Github/llvm/mono2/test-suite-reproducer/bin/llvm-lit -j 128 -v .
> ```
> 
> I do not believe you're required to run the entire suite as `llvm-lit <build-dir>` does in the above command but I forget the exact semantics to run a specific test-suite case at this time. I will update when I uncover that.

Were you able to prepare a reproducer? Preprocessed source code and compile line should be enough for initial analaysis

**Comment by mstorsjo** [comment]
I bisected a miscompilation (giving the wrong result at runtime) back to this commit, reproducing on x86_64 Linux.

To repro:
```
$ git clone https://github.com/ffmpeg/ffmpeg
$ cd ffmpeg
$ git checkout n6.0
$ mkdir ../ffmpeg-build
$ cd ../ffmpeg-build
$ ../ffmpeg/configure --cc=clang --samples=$(pwd)/../samples
$ make fate-rsync
$ make -j$(nproc) fate-copy-trac4914-avi
```

Note that the issue only appears in an older version of ffmpeg, it doesn’t seem to happen with latest git. The miscompilation seems to happen in the `libavformat/avformat.o` object file.

**Comment by alexey-bataev** [comment]
Must be fixed in f6e01b9ece1e73f6eda6e1dbff3aa72e917f4007

**Comment by mstorsjo** [comment]
> Must be fixed in [f6e01b9](https://github.com/llvm/llvm-project/commit/f6e01b9ece1e73f6eda6e1dbff3aa72e917f4007)

Thanks, that does indeed seem to fix my issue!

**Pull request merged**
