### PR TITLE
Revert "[NVPTX] Add Volta Load/Store Atomics (.relaxed, .acquire, .release) and Volatile (.mmio/.volatile) support"

### PR DESCRIPTION
**Pull request by slackito**
Reverts llvm/llvm-project#98022

### CODE REVIEW

**Review by Artem-B — APPROVED** [review]

**Comment by gonzalobg** [comment]
@Artem-B lets merge #99649 first; this one builds on top of that one.

**Comment by slackito** [comment]
I'm going to ignore the clang-format check, to keep this a straight revert of the original patch.

**Comment by Artem-B** [comment]
Looks like you may need to set [skip-precommit-approval](https://github.com/llvm/llvm-project/labels?q=skip-precommit-approval) label.

**Comment by joker-eph** [comment]
Please always provide the revert reason in the commit message so it shows up in the history log.
Thanks!

**Comment by slackito** [comment]
> Please always provide the revert reason in the commit message so it shows up in the history log. Thanks!

Will do, sorry about that. And thank you for pointing it out.

**Comment by gonzalobg** [comment]
The problem is that XLA is using `atomic unordered` in their code generation, which the patch being reverted here disabled because it was not supported by the NVPTX backend (the code generation for it was just accidentally falling through a branch causing it to "do something incorrect").

This looks like a mistake on XLA's side, which should be using `atomic monotonic` instead.

#99709 updates this patch to provide `atomic unordered` the same code-generation as `atomic monotonic`.

**Pull request merged**
