### PR TITLE
[AMDGPU] Adding the amdgpu-num-work-groups function attribute

### PR DESCRIPTION
**Pull request by jwanggit86**
A new function attribute named amdgpu-num-work-groups is added. This attribute allows programmers to let the compiler know the number of workgroups to be launched and do optimizations based on that information.

### CODE REVIEW

**Review by arsenm — COMMENTED** [review]
What kind of optimizations does this enable? Would this be better expressed as a maximum dispatch size, per dimension?

**Comment by jwanggit86** [comment]
Two possible optimizations mentioned by the requester are, 
"1. This'll let the backend know the maximum size of the workgroup ID, and so we can do things like infer nsw or the ability to use a 16-bit add or so on

2. This could be used to optimize global sync stuff in the future
"

**Comment by arsenm** [comment]
ping @krzysz00

**Comment by krzysz00** [comment]
@arsenm It's entirely possible that max dispatch size per dimension is the right feature instead, now that you mention it (I keep forgetting we have a grid).

Currently I was thinking this'll be useful for `KnownBits`-type info, so ... yeah, per-dimension

**Comment by jwanggit86** [comment]
@krzysz00 So how do you want to proceed?

**Comment by krzysz00** [comment]
I'd go with Matt's point: close this, and then add metadata for required launch grid sizes. Then you can update `AMDGPULowerKernelAttributes` to use said metadata.

**Comment by jwanggit86** [comment]
@krzysz00 So, instead of 1 number as in the current implementation, you want 3 numbers, i.e., 3 lines like the following in the metadata section?

```
.num_workgroups_x: 1
.num_workgroups_y: 2
.num_workgroups_z: 3
```

**Comment by AaronBallman** [comment]
How does this attribute relate to `reqd_work_group_size` and related existing attributes? Is `amdgpu_num_work_groups` the best way to expose this given that other technologies also have the notion of work groups that aren't related to AMD GPUs? CC @bader @jdoerfert

**Comment by bader** [comment]
> How does this attribute relate to `reqd_work_group_size` and related existing attributes?

They seems to be different/"unrelated". Based on the description of the `amdgpu-num-work-groups` attribute it provides "number of work-groups", whereas `reqd_work_group_size` provides "number of work-items in a work-group".

I think this attributed can be useful for other targets. The optimization ideas described in https://github.com/llvm/llvm-project/pull/75647#issuecomment-1863352459 seems to be generic. There is an RFC to unify some existing functionality exposing "grid" information: https://discourse.llvm.org/t/proposing-llvm-gpu-intrinsics/75374. This might fall into similar category.

**Comment by jdoerfert** [comment]
We are back to the duplication.
The attribute here, num-work-groups, exist in IR as:
NVPTX: minctasm -> min work groups
NVPTX: maxclusterrank -> max work groups
OpenMP: omp_target_num_teams -> right now exact = num work groups

@bader This is not the same as the intrinsics but we can/should unify the attributes as well, IMHO.

If we make changes in this area, I would strongly suggest a generic attribute and adapted handling in the backends/optimizations.

**Comment by krzysz00** [comment]
Good to know that other targets have that sort of "how many work groups will be launched" information. Having that be a min/max (either per dimension or in total or both) may be the right approach here, and this could be a good excuse for the unification being talked about.

(This isn't anything I, as the initial proposer of the idea, am needing super urgently - this was spawned from "hey, I'm up here in MLIR generating kernels that always have N workgroups in the grid, can I be cleverer than just sticking `!range` metadata on the intrinsics?")

**Comment by arsenm** [comment]
> @krzysz00 So, instead of 1 number as in the current implementation, you want 3 numbers, i.e., 3 lines like the following in the metadata section?
> 
> ```
> .num_workgroups_x: 1
> .num_workgroups_y: 2
> .num_workgroups_z: 3
> ```

It may still be better to express in terms of dispatch size, not groups directly. The maximum number of groups would be implied by grid size + maximum group size

**Comment by krzysz00** [comment]
"dispatch size"?

**Comment by jwanggit86** [comment]
Reimplemented in [79035](https://github.com/llvm/llvm-project/pull/79035).

**Pull request closed without merging**
