### PR TITLE
[clang-format] Fix FormatToken::isSimpleTypeSpecifier()

### PR DESCRIPTION
**Pull request by owenca**
Remove FormatToken::isSimpleTypeSpecifier() and call Token::isSimpleTypeSpecifier(LangOpts) instead.

### CODE REVIEW

**Review by mydeveloperday — APPROVED** [review]
I think this will stop people introducing extra arguments to function

...isCpp,isThis,isThat)

LGTM

**Review by HazardyKnusperkeks — APPROVED** [review]

**Comment by owenca** [comment]
> I think this will stop people introducing extra arguments to function
> 
> ...isCpp,isThis,isThat)

I meant to fix the FIXME after I had langded a8279a8bc541, but my previous attempts didn't quite work. Now it seems this solution will stick.

**Comment by dyung** [comment]
Hi @owenca, this change is causing a test failure in the sanitizer bot (https://lab.llvm.org/buildbot/#/builders/5/builds/43303), that is still failing as of your most recent fix de641e2 (https://lab.llvm.org/buildbot/#/builders/5/builds/43334). Can you please revert if you need time to investigate so that we can get the sanitizer bot back to green?

**Comment by owenca** [comment]
@dyung I've reverted all relevant commits in commit 1fadb2b0c881ced247931f442fdee6c4ed96dccb.

**Pull request merged**
