### PR TITLE
[InstCombine] Fold `icmp pred (inttoptr X), (inttoptr Y) -> icmp pred X, Y`

### PR DESCRIPTION
**Pull request by dtcxzyw**
Alive2 proofs are unavailable because `inttoptr` is unsupported.

### CODE REVIEW

**Review by nikic — APPROVED** [review]
LGTM

**Comment by vitalybuka** [comment]
Suspecting miscompile causing https://lab.llvm.org/buildbot/#/builders/236/builds/8673

**Comment by dtcxzyw** [comment]
> Suspecting miscompile causing https://lab.llvm.org/buildbot/#/builders/236/builds/8673

Thank you for reporting this! I will investigate it.

**Comment by dtcxzyw** [comment]
> > Suspecting miscompile causing https://lab.llvm.org/buildbot/#/builders/236/builds/8673
> 
> Thank you for reporting this! I will investigate it.

Waiting for the result of https://lab.llvm.org/buildbot/#/builders/239/builds/5285...

**Comment by dtcxzyw** [comment]
> Suspecting miscompile causing https://lab.llvm.org/buildbot/#/builders/236/builds/8673

We pass the CI with asan: https://lab.llvm.org/buildbot/#/builders/239/builds/5285.
Do you know why `llvm-pdbutil` crashes? I cannot get any useful information from the log :(

**Comment by vitalybuka** [comment]
That's why I suspect miscompile.

But so far it's just a suspicion. I am bisecting to be sure, that build is slow.

**Comment by vitalybuka** [comment]
Bisect is not finished, but it passed after this patch.
Sorry of the noise.

**Pull request merged**
