### PR TITLE
[RISCV] Add experimental support for making i32 a legal type on RV64 in SelectionDAG.

### PR DESCRIPTION
**Pull request by topperc**
This will select i32 operations directly to W instructions without custom nodes. Hopefully this can allow us to be less dependent on hasAllNBitUsers to recover i32 operations in RISCVISelDAGToDAG.cpp.

This support is enabled with a command line option that is off by default.

Generated code is still very not optimal.

I've duplicated many test cases for this, but its not complete. I think that enabling this runs all existing lit tests without crashing.

### CODE REVIEW

**Comment by wangpc-pp** [comment]
I remember that I have tried to do this about one year ago (after adding `n32` to RV64 datalayout) but failed because some llvm-testsuite cases weren't passed. Can you run llvm-testsuite and see if there are some failures?

**Comment by topperc** [comment]
> I remember that I have tried to do this about one year ago (after adding `n32` to RV64 datalayout) but failed because some llvm-testsuite cases weren't passed. Can you run llvm-testsuite and see if there are some failures?

I haven't tested llvm-testsuite, but spec2006int passed.

**Review by asb — APPROVED** [review]
LGTM. I think duplicating the tests to avoid an overabundance of CHECK lines in the existing ones was a good way to handle this. I've also tested this doesn't seem to indicate any compile or runtime failures on the GCC torture suite when enabled.

**Comment by wangpc-pp** [comment]
Thanks for testing! I must missed something when I tried this.

I see from the diff that we can remove some complexities of GISel. My concern is that we add too much complexities to DAG lowering and TableGen patterns and I don't know if it's worthy.

**Comment by topperc** [comment]
> Thanks for testing! I must missed something when I tried this.
> 
> 
> 
> I see from the diff that we can remove some complexities of GISel. My concern is that we add too much complexities to DAG lowering and TableGen patterns and I don't know if it's worthy.

My hope is that we can make this default in the next 6 months and simplify the DAG lowering again.

**Review by wangpc-pp — APPROVED** [review]
LGTM. Let's move forward!

**Pull request merged**
