### PR TITLE
Removed expansive copy

### PR DESCRIPTION
**Pull request by JaydeepChauhan14**
Removed expansive copy.

There are two calls for method **isBlendOrUndef** in file **llvm/lib/Target/X86/X86ISelLowering.cpp** , 
1.  For NewBlendMask it is allocating 32*4=>128 Bytes
```
...
SmallVector<int, 32> NewBlendMask(NumElts, SM_SentinelUndef);
...
assert(isBlendOrUndef(NewBlendMask) && "Bad blend"); 
...
```

2. For BlendMask it is allocating 16*4=> 64 Bytes
```
...
    SmallVector<int, 16> BlendMask;
    DecodeBLENDMask(NumElts, Op.getConstantOperandVal(2), BlendMask);
    if (SDValue R = combineBlendOfPermutes(
            VT.getSimpleVT(), Op.getOperand(0), Op.getOperand(1), BlendMask,
            DemandedElts, TLO.DAG, Subtarget, SDLoc(Op)))
      return TLO.CombineTo(Op, R);
...
assert(isBlendOrUndef(BlendMask) && "Blend shuffle expected");
...
```
- Both above cases are allocating 64 and 128 bytes. which is looks expansive, So removed copy.

### CODE REVIEW

**Comment by JaydeepChauhan14** [comment]
@MalaySanghi  please review

**Comment by MalaySanghi** [comment]
Looking at 
https://en.cppreference.com/w/cpp/language/structured_binding
section: binding a tuple-like type

and then at the definition of enumerate
```
auto enumerate(FirstRange &&First, RestRanges &&...Rest)
```

I think M and I are already references. I don't think we need this change.

**Comment by RKSimon** [comment]
@JaydeepChauhan14 Where did you see a warning that lead to this patch?

**Comment by JaydeepChauhan14** [comment]
> @JaydeepChauhan14 Where did you see a warning that lead to this patch?

@RKSimon  , an internal static code analyzer found it.

**Comment by JaydeepChauhan14** [comment]
As per review this is not the defect, so closing the ticket. Thank you, all review/comments.

**Pull request closed without merging**
