### PR TITLE
[Driver,BareMetal] Replace -lclang_rt.builtins{,-$arch}.a with an absolute path

### PR DESCRIPTION
**Pull request by MaskRay**
The generic `tools::AddRunTimeLibs` uses an absolute path. Change
BareMetal to match.

I believe users are not supposed to place other files under the
directory containing `libclang_rt.builtins-$arch.a`. If they rely on the
implicit -L, they now need to explicitly specify -L.

### CODE REVIEW

**Review by jroelofs — APPROVED** [review]
LGTM, thanks!

**Review by petrhosek — APPROVED** [review]

**Review by abidh — APPROVED** [review]
LGTM

**Comment by ekliptik** [comment]
Hi, this broke our downstream. What is the motivation for this, and how is this intended to be used with compiler-rt locations being set by multilib.yaml? We have something similar to what ARM does for multilibs.yaml but with different paths, and this prevents the driver from knowing anything about a singular path at which it should find the correct compiler-rt. What makes compiler-rt special in a way that other target libraries aren't? Here's how a part of our deliverable looks like:

```
riscv/lib/rv32imafc/ilp32f/
├── except
│   ├── libc.a
│   └── libm.a
├── libclang_rt.builtins-riscv32.a
└── noexcept
    ├── libc.a
    └── libm.a
```

and there are several such `<arch>/<abi>` directories

**Comment by MaskRay** [comment]
> Hi, this broke our downstream. What is the motivation for this, and how is this intended to be used with compiler-rt locations being set by multilib.yaml? We have something similar to what ARM does for multilibs.yaml but with different paths, and this prevents the driver from knowing anything about a singular path at which it should find the correct compiler-rt. What makes compiler-rt special in a way that other target libraries aren't? Here's how a part of our deliverable looks like:
> 
> ```
> riscv/lib/rv32imafc/ilp32f/
> ├── except
> │   ├── libc.a
> │   └── libm.a
> ├── libclang_rt.builtins-riscv32.a
> └── noexcept
>     ├── libc.a
>     └── libm.a
> ```
> 
> and there are several such `<arch>/<abi>` directories

* The preferred filename has changed from `clang_rt.builtins{,-$arch}.a` to `$triple/clang_rt.builtins.a`. BareMetal hadn't been fixed before this PR.
* All other ToolChains use an absolute path, while BareMetal inappropriately used `-lxxx`.
* This was a necessary change to do #81037

I think you'll need to switch to LLVM_ENABLE_PER_TARGET_RUNTIME_DIR=on hierarchy, which is quite different from the older off hierarchy.

**Comment by petrhosek** [comment]
I agree with @MaskRay that prior to this change the BareMetal driver was using a logic that was inconsistent with all other drivers and not something we intend to support. The correct solution is to extend the BareMetal driver to support `multilib.yaml` for Clang runtime libraries; this includes not only compiler-rt builtins but also LLVM libc and libc++.

**Pull request merged**
