### PR TITLE
[RISCV][LLD] Add RISCV zcmt optimise in linker relaxation

### PR DESCRIPTION
**Pull request by Xinlong-Wu**
This patch is moved from https://reviews.llvm.org/D134600

This patch implements optimizations for the zcmt extension in lld.

A new TableJumpSectio has been added.

Scans each R_RISCV_CALL/R_RISCV_CALL_PLT relocType in each section before the linker relaxation, recording the name of the symbol.

In finalizeContents the recorded symbol names are sorted in descending order by the number of jumps.

Optimise and insert a new cm.jt/cm.jalt during the relax process. in the process, we reused the`R_RISCV_JAL` relocType

co-author: @ScottEgerton

### CODE REVIEW

**Comment by jrtc27** [comment]
> This patch is moved from https://reviews.llvm.org/D134600

Why? That loses all the context in the Phabricator review. Keep the review there.

**Comment by Xinlong-Wu** [comment]
> > This patch is moved from https://reviews.llvm.org/D134600
> 
> Why? That loses all the context in the Phabricator review. Keep the review there.

yes, I will keep it there.

But the [Phabricator shutdown timeline](https://discourse.llvm.org/t/update-on-github-pull-requests/71540) said that 
> Phabricator becomes read-only after October 1

So I thought it may means we can't add comments or update it? That's why I moved it from Phabricator.

If you mean we still can review&update it at Phabricator, I will close this pr. )

**Comment by jrtc27** [comment]
> > > This patch is moved from https://reviews.llvm.org/D134600
> > 
> > 
> > Why? That loses all the context in the Phabricator review. Keep the review there.
> 
> yes, I will keep it there.
> 
> But the [Phabricator shutdown timeline](https://discourse.llvm.org/t/update-on-github-pull-requests/71540) said that
> 
> > Phabricator becomes read-only after October 1
> 
> So I thought it may means we can't add comments or update it? That's why I moved it from Phabricator.
> 
> If you mean we still can review&update it at Phabricator, I will close this pr. )

Scroll down the thread and you will find https://discourse.llvm.org/t/update-on-github-pull-requests/71540/124. There's consensus that Phabricator will remain usable for existing revisions for a while longer for this specific kind of situation, and that migrating revisions off of it loses valuable context and should be avoided.

**Comment by Xinlong-Wu** [comment]
> > > > This patch is moved from https://reviews.llvm.org/D134600
> > > 
> > > 
> > > Why? That loses all the context in the Phabricator review. Keep the review there.
> > 
> > 
> > yes, I will keep it there.
> > But the [Phabricator shutdown timeline](https://discourse.llvm.org/t/update-on-github-pull-requests/71540) said that
> > > Phabricator becomes read-only after October 1
> > 
> > 
> > So I thought it may means we can't add comments or update it? That's why I moved it from Phabricator.
> > If you mean we still can review&update it at Phabricator, I will close this pr. )
> 
> Scroll down the thread and you will find https://discourse.llvm.org/t/update-on-github-pull-requests/71540/125. There's consensus that Phabricator will remain usable for existing revisions for a while longer for this specific kind of situation, and that migrating revisions off of it loses valuable context and should be avoided.

That make sense. I will close this pr

**Comment by Xinlong-Wu** [comment]
Considering that the LLVM instance of Phabricator has been replaced by a static archive, it is not workable to review on Phabricator anymore. So I reopened this pr and synchronized the latest changes.

**Pull request closed without merging**
