### PR TITLE
[CMake] Create generic runtimes targets as needed

### PR DESCRIPTION
**Pull request by petrhosek**
We currently create a generic runtime target for all subbuilds. For example if we're building libcxx for aarch64-linux-gnu and x86_64-linux-gnu, we would create the cxx target that would depend on cxx-aarch64-linux-gnu and cxx-x86_64-linux-gnu. The current implementation creates the generic runtimes targets ahead of time which introduces an issue where different subbuilds enable different runtimes. We should instead create the generic targets as needed.

### CODE REVIEW

**Comment by petrhosek** [comment]
I'm not sure if anyone uses these generic targets at all, it might be easier to just remove them altogether. I created #76097 which does that, let me know if you have a preference.

**Comment by smeenai** [comment]
I thought we had some complaints from Apple the last time the behavior of these generic targets changed? Maybe @ldionne would remember the details.

I'm in favor of keeping the targets, to minimize workflow changes and the potential for reverts. I'm okay with this change, but I'd also like to understand the motivation a bit better. We were already only adding dependencies to the generic targets if we were going to build them; is the change to avoid creating a generic target at all when it's not needed? That'd only happen when `LLVM_ENABLE_RUNTIMES` specifies a runtime but every single runtime target overrides that variable to remove the runtime, right?

**Comment by petrhosek** [comment]
I encountered this when trying to enable `libc` for a single (baremetal) subbuild, and as such I don't want to put it in the `LLVM_ENABLE_RUNTIMES` global variable (that would result in the Darwin subbuild trying to build `libc` which is going to fail), but that means the generic `libc` target won't be created and the latter attempt at adding the dependency is going to fail here: https://github.com/llvm/llvm-project/blob/61b58123a3137323d6876006a6171d42e5e03cc1/llvm/runtimes/CMakeLists.txt#L394

More generally, I think that the global `LLVM_ENABLE_RUNTIMES` variable should only apply to the default subbuild: https://github.com/llvm/llvm-project/blob/61b58123a3137323d6876006a6171d42e5e03cc1/llvm/runtimes/CMakeLists.txt#L211
All other subbuilds should use `RUNTIME_<target>_LLVM_ENABLE_RUNTIMES`: https://github.com/llvm/llvm-project/blob/61b58123a3137323d6876006a6171d42e5e03cc1/llvm/runtimes/CMakeLists.txt#L271

**Review by smeenai — APPROVED** [review]
Ah, I forgot about the opposite case, where you're only adding a runtime for a specific target. This LGTM then.

**Comment by ldionne** [comment]
I don't remember that breakage, unfortunately. We shouldn't be using the bootstrapping build internally, so I don't *think* this should impact us, and I don't have any objection against this change.

**Pull request merged**
