### PR TITLE
[GlobalISel] Fall back for bf16 conversions.

### PR DESCRIPTION
**Pull request by aemerson**
We don't support these correctly since we don't yet have FP types.
AMDGPU tests were silently miscompiling bf16 as if they were fp16.

### CODE REVIEW

**Review by arsenm — APPROVED** [review]
There are also hidden conversions in all the ABI contexts ideally would skip as well

**Comment by davemgreen** [comment]
Nice. I was thinking of adding this check for aarch64 at least, it makes sense to do it generically.

How do we think bf16 should be supported? As far as I understand the options would be
- to have it as part of the type information (bf16 as opposed to s16)
- to have it as a different operation (G_FADDBF16 as opposed to G_FADD)
- or to have it as an flag on the existing operations (G_FADD bf16 as opposed to G_FADD [ieee] maybe).

Maybe there are other options too? There are other (multiple) fp8 types being proposed currently. Any thought so far on what the best way to support them would be?

**Comment by arsenm** [comment]
> Nice. I was thinking of adding this check for aarch64 at least, it makes sense to do it generically.
> * to have it as part of the type information (bf16 as opposed to s16)

We were talking about adding it to LLT. I think we should steal some bits from the size or element count and turn it into an enum for the class, such that any FP type would still be isScalar but identifiable

**Comment by davemgreen** [comment]
OK. Sounds like that should work, so long as it was still simple to keep the types agnostic where its beneficial (load and stores and shuffles and whatnot). There are multiple types of fp8 already, two that get used in Arm, maybe more that 4 in total but I'm not sure how many will need to be supported. There is still a few bits in vector LLTs that could be used currently.

**Comment by erickq** [comment]
Now an error is reported for a very simple bf16 data addition. Is this modification too violent?
```
#include <arm_neon.h>
bfloat16_t test(bfloat16_t gpara1, bfloat16_t gpara2)
{
    return gpara1+gpara2;
}
```

**Comment by arsenm** [comment]
> Now an error is reported for a very simple bf16 data addition. Is this modification too violent?
> 
> ```
> #include <arm_neon.h>
> bfloat16_t test(bfloat16_t gpara1, bfloat16_t gpara2)
> {
>     return gpara1+gpara2;
> }
> ```

No, this is exactly the kind of case that is supposed to be rejected

**Comment by erickq** [comment]
> > Now an error is reported for a very simple bf16 data addition. Is this modification too violent?
> > ```
> > #include <arm_neon.h>
> > bfloat16_t test(bfloat16_t gpara1, bfloat16_t gpara2)
> > {
> >     return gpara1+gpara2;
> > }
> > ```
> 
> No, this is exactly the kind of case that is supposed to be rejected

clang -O0 -march=armv8.2-a+bf16 test.c

I don't really understand that at this point our hardware already supports the bf16 data type.

**Comment by aemerson** [comment]
> > > Now an error is reported for a very simple bf16 data addition. Is this modification too violent?
> > > ```
> > > #include <arm_neon.h>
> > > bfloat16_t test(bfloat16_t gpara1, bfloat16_t gpara2)
> > > {
> > >     return gpara1+gpara2;
> > > }
> > > ```
> > 
> > 
> > No, this is exactly the kind of case that is supposed to be rejected
> 
> clang -O0 -march=armv8.2-a+bf16 test.c
> 
> I don't really understand that at this point our hardware already supports the bf16 data type.

GlobalISel doesn't currently support bf16 properly until we add FP types. This change is supposed to trigger an abort or fallback to SDAG so that we don't silently miscompile bf16 code as if it were FP16.

**Comment by aemerson** [comment]
> > > Now an error is reported for a very simple bf16 data addition. Is this modification too violent?
> > > ```
> > > #include <arm_neon.h>
> > > bfloat16_t test(bfloat16_t gpara1, bfloat16_t gpara2)
> > > {
> > >     return gpara1+gpara2;
> > > }
> > > ```
> > 
> > 
> > No, this is exactly the kind of case that is supposed to be rejected
> 
> clang -O0 -march=armv8.2-a+bf16 test.c
> 
> I don't really understand that at this point our hardware already supports the bf16 data type.

I just tried that test case and I see the crash. The crash is in SelectionDAG because there's incomplete support for bf16 in the backend. Previously clang was silently miscompiling this to FP16 because GlobalISel didn't know it was bf16.

Also, bf16 in ARM doesn't provide you native support for general purpose FP arithmetic with bf16. It only adds some MLA/dotprod and conversions IIRC, so trying to add two bf16s would have to be done by promoting to float32 and then truncating back down.

**Comment by davemgreen** [comment]
It was previously giving an error in the frontend that you are using an operation that is not supported, but that was broken at some point without making the backend work correctly.

**Comment by erickq** [comment]
> #include <arm_neon.h>
> bfloat16_t test(bfloat16_t gpara1, bfloat16_t gpara2)
> {
>     return gpara1+gpara2;
> }

Okay, thank you. I got it. It seems that this needs to be supported slowly in the follow-up work. Do you have any plans?

**Comment by erickq** [comment]
> > > > Now an error is reported for a very simple bf16 data addition. Is this modification too violent?
> > > > ```
> > > > #include <arm_neon.h>
> > > > bfloat16_t test(bfloat16_t gpara1, bfloat16_t gpara2)
> > > > {
> > > >     return gpara1+gpara2;
> > > > }
> > > > ```
> > > 
> > > 
> > > No, this is exactly the kind of case that is supposed to be rejected
> > 
> > 
> > clang -O0 -march=armv8.2-a+bf16 test.c
> > I don't really understand that at this point our hardware already supports the bf16 data type.
> 
> I just tried that test case and I see the crash. The crash is in SelectionDAG because there's incomplete support for bf16 in the backend. Previously clang was silently miscompiling this to FP16 because GlobalISel didn't know it was bf16.
> 
> Also, bf16 in ARM doesn't provide you native support for general purpose FP arithmetic with bf16. It only adds some MLA/dotprod and conversions IIRC, so trying to add two bf16s would have to be done by promoting to float32 and then truncating back down.

Okay, thank you. I got it. It seems that this needs to be supported slowly in the follow-up work. Do you have any plans?

**Comment by erickq** [comment]
> It was previously giving an error in the frontend that you are using an operation that is not supported, but that was broken at some point without making the backend work correctly.

Is this the kind of error? https://godbolt.org/z/v8d4foaef
image

**Comment by arsenm** [comment]
> > It was previously giving an error in the frontend that you are using an operation that is not supported, but that was broken at some point without making the backend work correctly.
> 
> Is this the kind of error? 

No, that error doesn't make much sense

**Comment by davemgreen** [comment]
> > It was previously giving an error in the frontend that you are using an operation that is not supported, but that was broken at some point without making the backend work correctly.
> 
> Is this the kind of error?

Yep, that's the error. Operations like Add were previously not defined as they were not supported by the instruction set and there were no promotions for them. Someone changed how the frontend worked whilst only making the backend work for X86.

**Comment by erickq** [comment]
> > > It was previously giving an error in the frontend that you are using an operation that is not supported, but that was broken at some point without making the backend work correctly.
> > 
> > 
> > Is this the kind of error?
> 
> Yep, that's the error. Operations like Add were previously not defined as they were not supported by the instruction set and there were no promotions for them. Someone changed how the frontend worked whilst only making the backend work for X86.

Okay. thank you.  I think I see what you mean.  So, are there any plans to support the follow-up?@davemgreen@arsenm

**Comment by erickq** [comment]
> I don't know of anyone working on it, but it would be good to get it fixed.

Hello, can you help me? Thank you very much. Are the 16-bit values obtained from `fcvt h0, s0` and `bl __truncsfbf2` equivalent?

https://godbolt.org/z/q5G8PEMz6 @davemgreen

**Pull request merged**
