### PR TITLE
[Documentation] Fix some invalid references in sphinx documentation

### PR DESCRIPTION
**Pull request by cor3ntin**

### CODE REVIEW

**Comment by cor3ntin** [comment]
This partially fixes https://github.com/llvm/llvm-project/issues/68196

**Review by AaronBallman — APPROVED** [review]
LGTM! The only remaining issues I see when building LLVM docs locally are:
```
F:\source\llvm-project\llvm\docs\GitRepositoryPolicy.md:21: WARNING: 'myst' cross-reference target not found: 'DeveloperPolicy.html#adding-an-established-project-to-the-llvm-monorepo>' [myst.xref_missing]
F:\source\llvm-project\llvm\docs\InstrRefDebugInfo.md:96: WARNING: 'myst' cross-reference target not found: 'SourceLevelDebugging.html#livedebugvalues-expansion-of-variable-locations' [myst.xref_missing]
F:\source\llvm-project\llvm\docs\MarkdownQuickstartTemplate.md:161: WARNING: 'myst' cross-reference target not found: 'SphinxQuickstartTemplate.html#generating-the-documentation' [myst.xref_missing]
F:\source\llvm-project\llvm\docs\PointerAuth.md:306: WARNING: 'myst' cross-reference target not found: 'authenticated-global-relocation' [myst.xref_missing]
F:\source\llvm-project\llvm\docs\PointerAuth.md:331: WARNING: 'myst' cross-reference target not found: 'authenticated-global-relocation' [myst.xref_missing]
```

**Comment by xgupta** [comment]
> LGTM! The only remaining issues I see when building LLVM docs locally are:
> 
> ```
> F:\source\llvm-project\llvm\docs\GitRepositoryPolicy.md:21: WARNING: 'myst' cross-reference target not found: 'DeveloperPolicy.html#adding-an-established-project-to-the-llvm-monorepo>' [myst.xref_missing]
> F:\source\llvm-project\llvm\docs\InstrRefDebugInfo.md:96: WARNING: 'myst' cross-reference target not found: 'SourceLevelDebugging.html#livedebugvalues-expansion-of-variable-locations' [myst.xref_missing]
> F:\source\llvm-project\llvm\docs\MarkdownQuickstartTemplate.md:161: WARNING: 'myst' cross-reference target not found: 'SphinxQuickstartTemplate.html#generating-the-documentation' [myst.xref_missing]
> F:\source\llvm-project\llvm\docs\PointerAuth.md:306: WARNING: 'myst' cross-reference target not found: 'authenticated-global-relocation' [myst.xref_missing]
> F:\source\llvm-project\llvm\docs\PointerAuth.md:331: WARNING: 'myst' cross-reference target not found: 'authenticated-global-relocation' [myst.xref_missing]
> ```

I saw them too, seems warnings are treated as errors by default.

**Comment by cor3ntin** [comment]
The one in `PointerAuth.md` are actual errors: the referenced section simply does not exist.

The two other errors are just invalid cross-document references syntaxes, I haven't looked how to fix them yet.

**Pull request merged**
