### PR TITLE
D41416: [modules] [pch] Do not deserialize all lazy template specializations when looking for one.

### PR DESCRIPTION
**Pull request by ChuanqiXu9**
This from https://reviews.llvm.org/D41416. And we plan to introduce on disk hash table based on this. See https://github.com/llvm/llvm-project/pull/76774.

Following off are cited from https://reviews.llvm.org/D41416:

Currently, we load all lazy template specializations when we search whether there is a suitable template specialization for a template. This is especially suboptimal with modules. If module B specializes a template from module A the ASTReader would only read the specialization DeclID. This is observed to be especially pathological when module B is stl. However, the template instantiator (almost immediately after) will call findSpecialization. In turn, findSpecialization will load all lazy specializations to give an answer.

This patch teaches findSpecialization to work with lazy specializations without having to deserialize their full content. It provides along with the DeclID an cross-TU stable ODRHash of the template arguments which is enough to decide if we have already specialization and which are the exact ones (we load all decls with the same hash to avoid potential collisions) to deserialize.

While we make finding a template specialization more memory-efficient we are far from being done. There are still a few places which trigger eager deserialization of template specializations: the places where we require completion of the redeclaration chain.

### CODE REVIEW

**Comment by ChuanqiXu9** [comment]
Personally I feel this patch is good and the testing result from our workload shows it is good too. But it looks like the performance testing results from google @zygoloid @ilya-biryukov is not good. So maybe we need to wait for landing this. (It will be great if @ilya-biryukov would like to test again)

**Comment by ChuanqiXu9** [comment]
Weird. I only see two failures in my local environment:

```
Failed Tests (2):
  Clang :: Modules/cxx-templates.cpp
  Clang :: Modules/odr_hash.cpp
```

And I saw both of them in my patch. It is simply order mismatches.

**Comment by vgvassilev** [comment]
> Weird. I only see two failures in my local environment:
> 
> ```
> Failed Tests (2):
>   Clang :: Modules/cxx-templates.cpp
>   Clang :: Modules/odr_hash.cpp
> ```
> 
> And I saw both of them in my patch. It is simply order mismatches.

Ha, ok. I know that my system constantly have some tests that fail even fro the master but I thought these were real. If we don't see them in the bots then that's probably a problem only on my side...

**Comment by ChuanqiXu9** [comment]
Rebased with main.

**Comment by ChuanqiXu9** [comment]
Sent https://github.com/llvm/llvm-project/commit/b5bd19211118c6d43bc525a4e3fb65d2c750d61e and see https://github.com/llvm/llvm-project/pull/83237#issuecomment-2521945547

**Pull request closed without merging**
