### PR TITLE
[libc++][test] remove tests that testing std::variant<T&>

### LINKED ISSUE #83600: [libc++] Remove TEST_VARIANT_HAS_NO_REFERENCES
It's not used and `std::variant` doesn't support references. There might have been plans to support it at some point but clearly that's not the case anymore.

### PR DESCRIPTION
**Pull request by huixie90**
fixes #83600

### CODE REVIEW

**Review by ldionne — APPROVED** [review]
LGTM with nitpick!

**Review by EricWF — APPROVED** [review]
LGTM. Thanks for cleaning this up.

**Review by EricWF — CHANGES_REQUESTED** [review]
Are there no changes or cleanup that can be done to variant itself?

**Comment by huixie90** [comment]
> Are there no changes or cleanup that can be done to variant itself?

nope

**Review by ldionne — APPROVED** [review]

**Pull request merged**
