### PR TITLE
InferAddressSpaces: Handle llvm.fake.use

### PR DESCRIPTION
**Pull request by arsenm**

### CODE REVIEW

**Comment by arsenm** [comment]
* **#109567** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109567?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by SLTozer — COMMENTED** [review]
Although `llvm.fake.use` is variadic, it's actually an error to have more than one argument (not enforced in the verifier, I'll add a patch for that) - the variadic type is only used to allow it to be generic, since the expectation is that it can take any type (and we don't want a unique declaration for every type that may be used). The tests can be updated to remove the `multiple_` cases, and the code can assume that there is only one operand. Aside from that, this LGTM, acknowledging that I have limited understanding of InferAddressSpaces (but gave the relevant functions a read to make sure the updates make sense).

**Comment by arsenm** [comment]
> Although `llvm.fake.use` is variadic, it's actually an error to have more than one argument (not enforced in the verifier, I'll add a patch for that) 

I do not think this is a reasonable restriction to have. It adds a new constraint any IR pass has to consider. Any of the many flavors of CSE would need to deal with it, for example. If this wants to be a minimally intrusive intrinsic, it needs to have as few constraints as possible

**Comment by SLTozer** [comment]
> I do not think this is a reasonable restriction to have.

That might be fine - I'm not the original author so I don't the justification for the restriction when it was written, but it's likely simply that we never produce fake use intrinsics with more than one argument, and so code that handles it uses the hardcoded assumption that there is one argument; now that this intrinsic is part of upstream LLVM, allowing it to be used as a full variadic may be reasonable unless there are other technical constraints.

**Comment by arsenm** [comment]
> > I do not think this is a reasonable restriction to have.
> 
> That might be fine - I'm not the original author so I don't know the justification for the restriction when it was written, but it's likely simply that we never produce fake use intrinsics with more than one argument, and so code that handles it uses the hardcoded assumption that there is one argument; now that this intrinsic is part of upstream LLVM, allowing it to be used as a full variadic would be reasonable unless there are other technical constraints.

OK, I misread this. I was interpreting this as a single value cannot appear multiple times in the argument list. If the restriction is only one argument, that's a more reasonable restriction

**Review by arsenm — COMMENTED** [review]
I'm inclined to go ahead with this, including tests for multiple uses. In the absence of a verifier check this is valid IR that must be handled correctly.

I also still don't see a reason why fake.use would need to have this restriction

**Review by SLTozer — APPROVED** [review]
I don't think there's a problem with landing this as-is; for full context, the current state of llvm.fake.use is that there is no verifier check to enforce having exactly one operand, but the documentation states that it is an error for it to have more than one operand, and SelectionDAG currently assumes a single operand only.
To my knowledge there's not a principled reason for this to be the case, it just simplified the implementation (particularly around ISel), so I'm fine to make the change for variadic fake uses to be properly supported in a future patch, or else if it turns out to cause problems then the verifier check can be added and the tests that depend on it being variadic can be adjusted or removed.

**Pull request merged**
