### PR TITLE
[llvm-lit] Precommit Tests for implementing the `unset` command in lit internal shell

### PR DESCRIPTION
**Pull request by Harini0924**
This patch introduces a suite of tests designed to verify the current behavior of the `unset` command within the lit internal shell. As it stands, the `unset` command is not recognized or supported in this environment, resulting in expected failures with specific error messages and exit codes. These tests are intentionally failing to reflect the current state. Additionally, I have added the `executeBuiltinUnset` function, which raises an `InternalShellError` with a clear message advising users to use `env -u VARIABLE` as an alternative since the `unset` command is not supported by the lit internal shell.

This change is relevant for [[RFC] Enabling the Lit Internal Shell by Default](https://discourse.llvm.org/t/rfc-enabling-the-lit-internal-shell-by-default/80179/3)

### CODE REVIEW

**Comment by Harini0924** [comment]
CC: @ilovepi @petrhosek

**Comment by jh7370** [comment]
Related to my most recent comment in the RFC, how many tests make use of `unset`, and which tests are they? My gut is that this functionality is unlikely to be needed at all, and a simple bit of rewriting of tests would be preferable, but if the number of tests si high, my view may change.

**Comment by Harini0924** [comment]
@jh7370 After reviewing the number of tests that make use of the `unset` command, I found that there are only two tests (`afl-driver-stderr.test` and `afl-driver-close-fd-mask.test`). Given the low number, I decided to rewrite these tests rather than implement the `unset` command within the lit internal shell. This PR (#104880) reflects that decision.

However, this PR still checks the current state and will display an error message that guides users to use `env -u` instead of `unset` to unset environment variables. I believe this approach will be helpful for users by providing clear instructions on how to handle this situation correctly.

What are your thoughts on this patch?

**Review by jh7370 — COMMENTED** [review]
Honestly, I'm not sure this is necessary. `env -u` is a standard Linux shell command, so in theory at least, it should be as well known as `unset` for those used to that style. I think the fact that only two tests use it, and both of those tests are linked tightly, shows that `unset` isn't something people tend to use, so the cost of extra complexity in lit (by virtue of having more code) doesn't really seem justified.

**Pull request closed without merging**
