### PR TITLE
[NFC][TargetTransformInfo][VectorUtils] Consolidate `isVectorIntrinsic...` api

### LINKED ISSUE #117030: [NFC] Update `isVectorIntrinsicWith...` functions to consider `TargetTransformInfo`
The functions `isVectorIntrinsicWithScalarOpAtArg` and `isVectorIntrinsicWithStructReturnOverloadAtField` are unable to consider target specific intrinsics. This issue is resolved when these functions appropriately use the TTI impl when possible.

Essentially we want consistent behaviour with the changes here: https://github.com/llvm/llvm-project/pull/114849

AC:
- [ ]  Update `isVectorIntrinsicWithScalarOpAtArg` and `isVectorIntrinsicWithStructReturnOverloadAtField` to have a third parameter of `TargetTransformInfo` and to use this implementation when there is a target specific intrinsic. Update comment description of functions to include the new parameter
- [ ] Update all uses-cases to pass in this argument
- [ ] Remove the scalarizer functionality of `isVectorIntrinsicWithScalarOpAtArg` in `Scalarizer.cpp`

### PR DESCRIPTION
**Pull request by inbelic**
- update `VectorUtils:isVectorIntrinsicWithScalarOpAtArg` to use TTI for
all uses, to allow specifiction of target specific intrinsics
- add TTI to the `isVectorIntrinsicWithStructReturnOverloadAtField` api
- update TTI api to provide `isTargetIntrinsicWith...` functions and
  consistently name them
  
- update all uses of the api and provide the TTI parameter

Resolves #117030

### CODE REVIEW

**Comment by farzonl** [comment]
Should we do something similar with ` `isTargetIntrinsicTriviallyScalarizable`?  Alternatively was thining we need a ticket  to consolidate `isTargetIntrinsicTriviallyScalarizable` with `isTargetIntrinsicTriviallyVectorizable`?

**Comment by inbelic** [comment]
Sure, I think it makes sense to move the `ScalarizerVisitor::isTriviallyScalarizable` to `VectorUtils.cpp`.

By consolidate, do you mean to just have one of `isTriviallyVectorizable` and `isTriviallyScalarizable`?

**Comment by farzonl** [comment]
> Sure, I think it makes sense to move the `ScalarizerVisitor::isTriviallyScalarizable` to `VectorUtils.cpp`.
> 
> By consolidate, do you mean to just have one of `isTriviallyVectorizable` and `isTriviallyScalarizable`?

I was thinking one function with a more neutral name. I don’t have a good suggestion for you though. Maybe something with elementwise in the name? Or maybe we just adopt the vectorizable name?

**Comment by inbelic** [comment]
Rebased onto main to resolve merge conflicts and updated to move `isTriviallyScalarizable` into `VectorUtils`.

I decided to keep the two functions separate as it will force any future intrinsic that implements scalarization to also implement vectorization, which may be redundant work. But also, because `isTriviallyVectorizable` is used for other logic that needs to be audited before changing. For instance, `isNotCrossLaneOperation`, where it is not true that if a function is scalarizable then it is not a cross-lane op (`dx_wave_readlane`).

I created this [issue](https://github.com/llvm/llvm-project/issues/120169) to track the work needed to update `isTriviallyVectorizable` to accept target intrinsics and from there we could consider if we could merge them.

**Review by llvm-beanz — APPROVED** [review]

**Review by farzonl — APPROVED** [review]

**Pull request merged**
