### PR TITLE
[SCCP] Check whether the default case is reachable

### LINKED ISSUE #76085: Switch default destination not eliminated despite known value range
A fully populated switch with known value range (but no explicit `default` clause) will still generate a conditional jump to the default destination:
```C
void canthappen(void);
int g(int);

int f(int x) {
  if (x >= 0 && x <= 3) {
    switch (x) {
    case 0: return g(2);
    case 1: return g(3);
    case 2: return g(4);
    case 3: return g(5);
    }
    canthappen();
  }
  return -23;
}
```
results in a never-taken conditional branch to code that calls `canthappen`.
llvm 18.0.0git (9f74e6e6157bc4d63a28385c7c0a50506bb8a737).

### PR DESCRIPTION
**Pull request by dtcxzyw**
This patch eliminates unreachable default cases using range information.
Fixes #76085.

### CODE REVIEW

**Comment by dtcxzyw** [comment]
Ping.

**Comment by nikic** [comment]
What happens if the default is already unreachable? Will we replace it with a new unreachable block? It would be good to skip the update in that case.

**Comment by nikic** [comment]
> What happens if the default is already unreachable? Will we replace it with a new unreachable block? It would be good to skip the update in that case.

Hm, I guess this isn't so simple because we'll mark the block as dead and remove it.

**Review by nikic — APPROVED** [review]
LGTM

**Comment by nikic** [comment]
> > What happens if the default is already unreachable? Will we replace it with a new unreachable block? It would be good to skip the update in that case.
> 
> Hm, I guess this isn't so simple because we'll mark the block as dead and remove it.

It may still be worth doing this to avoid spurious invalidation of CFG analyses, but it's not really related to this patch...

**Pull request merged**
