### PR TITLE
[C++20] [Modules] Embed all source files for C++20 Modules

### LINKED ISSUE #72383: Shouldn't `-fmodules-embed-all-files` be the default?
Consider these two translation units:

```c++
// hello.mxx

module;

#include <string>
#include <string_view>

export module hello;

export namespace hello
{
  std::string
  say_hello (const std::string_view& name)
  {
    return "Hello, " + std::string (name) + '!';
  }
}
```

```c++
// main.cxx

#include <string_view>

import hello;

void f (const std::string_view&) {}

int
main ()
{
  hello::say_hello ("World");
}
```

If I compile `hello.mxx` with Clang 16, then remove `hello.mxx`, and attempt to compile `main.cxx`, I get an error:

```
clang++-16 -std=c++2b -fmodule-output=hello.pcm -o hello.pcm.o -c -x c++-module hello.mxx
mv hello.mxx hello.mxx.bak
clang++-16 -std=c++2b -fmodule-file=hello=hello.pcm -o main.o -c -x c++ main.cxx
main.cxx:5:1: fatal error: malformed or corrupted AST file: 'could not find file '/tmp/hello-simple/hello.mxx' referenced by AST file 'hello.pcm''
```

This can be fixed by adding `-Xclang -fmodules-embed-all-files` when compiling `hello.mxx`.

However, `-fmodules-embed-all-files` appears to no longer be necessary for this example if using Clang 17 or later:

```
clang++-17 -std=c++2b -fmodule-output=hello.pcm -o hello.pcm.o -c -x c++-module hello.mxx
mv hello.mxx hello.mxx.bak
clang++-17 -std=c++2b -fmodule-file=hello=hello.pcm -o hello.o -c -x c++ main.cxx
# no error
```

But a minor change in `main.cxx` can bring its requirement back if compiling via `-frewrite-includes`:

```c++
// main.cxx

#include <string_view>

import hello;

void f (const std::string_view&) {}

int
main ()
{
  f (hello::say_hello ("World"));  // <-- NOW CALLING f().
}
```

```
clang++-17 -std=c++2b -fmodule-output=hello.pcm -o hello.pcm.o -c -x c++-module hello.mxx
mv hello.mxx hello.mxx.bak
clang++-17 -std=c++2b -fmodule-file=hello=hello.pcm -o hello.o -c -x c++ main.cxx
# no error
```

But:

```
clang++-17 -std=c++2b -x c++-module -E -frewrite-includes -o hello.ii hello.mxx
clang++-17 -std=c++2b -fmodule-output=hello.pcm -o hello.pcm.o -c -x c++-module hello.ii
rm hello.ii
clang++-17 -std=c++2b -fmodule-file=hello=hello.pcm -o hello.o -c -x c++ main.cxx
fatal error: cannot open file '/tmp/hello-simple1/hello.ii': No such file or directory
```

And if I add `-Xclang -fmodules-embed-all-files` to the second command, then everything again compiles fine. I get exactly the same behavior with Clang 18.

I have two questions about this:

1. Is `-fmodules-embed-all-files` the default starting from Clang 17? If the answer is yes, then there seems to be a bug in the `-fdirectives-only` interaction.

2. If `-fmodules-embed-all-files` is not the default, then should it not be made so? A BMI that still has references to source files is quite brittle since it can be moved around. AFAIK, neither GCC nor MSVC have this restriction for their BMIs.

@iains @ChuanqiXu9 @dwblaikie

### PR DESCRIPTION
**Pull request by ChuanqiXu9**
Close https://github.com/llvm/llvm-project/issues/72383

The implementation rationale is, I don't want to pass `-fmodules-embed-all-files` all the time since we can't test it in lit tests (we're using `clang_cc1`). So I tried to set it in FrontendActions for modules.

### CODE REVIEW

**Comment by cor3ntin** [comment]
What this discussed/reviewed/motivated?

**Comment by ChuanqiXu9** [comment]
> Was this discussed/reviewed/motivated? There are drawbacks to this approach outlined in #72383
> 
> @iains @jyknight @AaronBallman @Bigcheese

The motivation is in https://github.com/llvm/llvm-project/issues/72383 and I comment in https://github.com/llvm/llvm-project/issues/72383#issuecomment-2275135890

This is not reviewed. I wait for several weeks but got no response. And I think it is good. So I choose to land it.

**Comment by AaronBallman** [comment]
> > Was this discussed/reviewed/motivated? There are drawbacks to this approach outlined in #72383
> > @iains @jyknight @AaronBallman @Bigcheese
> 
> The motivation is in #72383 and I comment in [#72383 (comment)](https://github.com/llvm/llvm-project/issues/72383#issuecomment-2275135890)
> 
> This is not reviewed. I wait for several weeks but got no response. And I think it is good. So I choose to land it.

Thank you for the link! (FWIW, there's no problems with these changes having been landed; @ChuanqiXu9 is the code owner for modules and the PR was up for three weeks without discussion. This is just typical post-commit review feedback.)

There's a fair amount of discussion on that thread in opposition to this approach, and a comment thread on an issue is not really visible to many people. I think this warrants an RFC for a broader discussion, so I'd appreciate temporarily reverting this patch.

Some thoughts for the RFC discussion:

* Given that this is not the default behavior for MSVC, should `clang-cl` behave differently than `clang`?
* What are the impacts on other tooling (debugger, 3rd party static analysis, etc)?
* Is this the correct default when considering intellectual property security (will people expect their full, original source to be something that can be pulled from these artifacts)?

**Comment by mizvekov** [comment]
FWIW, I meant to review this, but somehow this disappeared from my waiting for review list and I lost track of it :)

**Comment by ChuanqiXu9** [comment]
> > > Was this discussed/reviewed/motivated? There are drawbacks to this approach outlined in #72383
> > > @iains @jyknight @AaronBallman @Bigcheese
> > 
> > 
> > The motivation is in #72383 and I comment in [#72383 (comment)](https://github.com/llvm/llvm-project/issues/72383#issuecomment-2275135890)
> > This is not reviewed. I wait for several weeks but got no response. And I think it is good. So I choose to land it.
> 
> Thank you for the link! (FWIW, there's no problems with these changes having been landed; @ChuanqiXu9 is the code owner for modules and the PR was up for three weeks without discussion. This is just typical post-commit review feedback.)
> 
> There's a fair amount of discussion on that thread in opposition to this approach, and a comment thread on an issue is not really visible to many people. I think this warrants an RFC for a broader discussion, so I'd appreciate temporarily reverting this patch.

Thank you, Aaron! But I like to not revert this until someone give some complaints on that thread. Since the problem in the high level looks clear to me and feel like the discussion in that thread looks like people there have a pretty good understanding to the issue self.

> 
> Some thoughts for the RFC discussion:
> 
> * Given that this is not the default behavior for MSVC, should `clang-cl` behave differently than `clang`?

We can discuss this topic in the two aspects, a module specific one and a broader one not limited to modules (the general policy). For the module specific topic, since the BMI generated by clang and MSVC are not compatible,  this change won't have any particular impact to the users of MSVC or `clang-cl`. Beyond the topic of BMI compatibility, this change will make the clang's behavior to match GCC and MSVC's behavior more. Like the OP said in the last paragraph of the 1st floor: https://github.com/llvm/llvm-project/issues/72383:

> AFAIK, neither GCC nor MSVC have this restriction for their BMIs.

The internal reason is that, in clang, the source locations are super fundamental and sensitive. So that, if we don't embed the source files, the BMI became invalid after we change the corresponding source file.

And for the broader one, should users expect `clang-cl` to be a drop-in replacement for MSVC? There is a good post about this (https://www.reddit.com/r/cpp/comments/1e36n0w/c20_modules_with_clangcl_which_way_forward/). I feel this is pretty complex. Not only from the high level expectations (otherwise we'll always say yes) but also the implementations. From the perspective of modules, it looks too hard to implement the MSVC's BMI in clang unless MicroSoft would love to put more people to implement that to clang. But after all, I think this is a good topic to discuss to get more involved. 

> * What are the impacts on other tooling (debugger, 3rd party static analysis, etc)?

There shouldn't be any bad impact on other tools. Since all the tools have to consume the BMI via the compiler (in the same version!). Since this patch simply loose the restriction, I don't expect this have any impact on 3rd party tools.

> * Is this the correct default when considering intellectual property security (will people expect their full, original source to be something that can be pulled from these artifacts)?

The consensus of SG15 for BMI is, the BMI is not good for distributed. Since the BMI format are not compatible across compilers (even with different versions!). So we would think BMI as a by-product of **a build process** only. Although there are thoughts about, we can distribute the BMI in a homogeneous environment where we have stable compiler versions. But such environments are closed ended environment for some specific projects or organizations. So I don't think it may affect any thing for the security as the design doesn't want us to ship the BMIs.

> FWIW, I meant to review this, but somehow this disappeared from my waiting for review list and I lost track of it :)

Understood, I have the same experience too. Not meant to blame any one : )

**Comment by AaronBallman** [comment]
> > > > Was this discussed/reviewed/motivated? There are drawbacks to this approach outlined in #72383
> > > > @iains @jyknight @AaronBallman @Bigcheese
> > > 
> > > 
> > > The motivation is in #72383 and I comment in [#72383 (comment)](https://github.com/llvm/llvm-project/issues/72383#issuecomment-2275135890)
> > > This is not reviewed. I wait for several weeks but got no response. And I think it is good. So I choose to land it.
> > 
> > 
> > Thank you for the link! (FWIW, there's no problems with these changes having been landed; @ChuanqiXu9 is the code owner for modules and the PR was up for three weeks without discussion. This is just typical post-commit review feedback.)
> > There's a fair amount of discussion on that thread in opposition to this approach, and a comment thread on an issue is not really visible to many people. I think this warrants an RFC for a broader discussion, so I'd appreciate temporarily reverting this patch.
> 
> Thank you, Aaron! But I like to not revert this until someone give some complaints on that thread. Since the problem in the high level looks clear to me and feel like the discussion in that thread looks like people there have a pretty good understanding to the issue self.

Again, I don't think a comment thread on an issue has a wide enough audience. FWIW, I had *no idea* about that thread until I got pinged here.

> > Some thoughts for the RFC discussion:
> > 
> > * Given that this is not the default behavior for MSVC, should `clang-cl` behave differently than `clang`?
> 
> We can discuss this topic in the two aspects, a module specific one and a broader one not limited to modules (the general policy). For the module specific topic, since the BMI generated by clang and MSVC are not compatible, this change won't have any particular impact to the users of MSVC or `clang-cl`. Beyond the topic of BMI compatibility, this change will make the clang's behavior to match GCC and MSVC's behavior more. Like the OP said in the last paragraph of the 1st floor: #72383:
> 
> > AFAIK, neither GCC nor MSVC have this restriction for their BMIs.
> 
> The internal reason is that, in clang, the source locations are super fundamental and sensitive. So that, if we don't embed the source files, the BMI became invalid after we change the corresponding source file.

I don't see why that's an issue; if the source code changes, *not* changing the BMI is a slight quality-of-implementation improvement (e.g., when user changes comments, but the actual semantics remain the same), but that hardly seems worth the concerns I have below.

> And for the broader one, should users expect `clang-cl` to be a drop-in replacement for MSVC? There is a good post about this (https://www.reddit.com/r/cpp/comments/1e36n0w/c20_modules_with_clangcl_which_way_forward/). I feel this is pretty complex. Not only from the high level expectations (otherwise we'll always say yes) but also the implementations. From the perspective of modules, it looks too hard to implement the MSVC's BMI in clang unless MicroSoft would love to put more people to implement that to clang. But after all, I think this is a good topic to discuss to get more involved.

Yeah, that broader discussion is one we should have; and we should have the same conversation about GCC compatibility as we're 1) not compatible, 2) drifting farther apart, 3) still claim we're GCC 4.2, and 4) have never explicitly determined just how much compatibility we need/want as a community (it was an organic thing that grew out of the needs of the early developers of Clang)

> > * What are the impacts on other tooling (debugger, 3rd party static analysis, etc)?
> 
> There shouldn't be any bad impact on other tools. Since all the tools have to consume the BMI via the compiler (in the same version!). Since this patch simply loose the restriction, I don't expect this have any impact on 3rd party tools.

Good to know; but this is a small part of why I'd like an RFC -- tools vendors should be made aware so they can raise concerns if they have them.

> > * Is this the correct default when considering intellectual property security (will people expect their full, original source to be something that can be pulled from these artifacts)?
> 
> The consensus of SG15 for BMI is, the BMI is not good for distributed. Since the BMI format are not compatible across compilers (even with different versions!). So we would think BMI as a by-product of **a build process** only. Although there are thoughts about, we can distribute the BMI in a homogeneous environment where we have stable compiler versions. But such environments are closed ended environment for some specific projects or organizations. So I don't think it may affect any thing for the security as the design doesn't want us to ship the BMIs.

That's SG15. This change has serious implications for IP and I don't feel comfortable making that decision as quietly as you have. This is the primary reason why I'm insisting on an RFC. As a concrete example, large organizations often have contractors who utilize libraries written by the parent company. If the company produces a BMI for their framework (because they control the environment used by the contractor anyway, so this is safe and reasonable to do), they may accidentally ship their sensitive IP along with it.

So I continue to ask for this to be reverted and an RFC posted.

**Comment by iains** [comment]
Sorry I have not made much review here - although did comment on  https://github.com/llvm/llvm-project/issues/72383 ..

1. it seems highly unlikely to me that the designers of the c++ modules facility would have expected it necessary to carry the source along with the BMI (but I am sure that they can comment if otherwise)
2. On the subject of IP;  In order to build a BMI one needs the source, so that a BMI cannot (should not?) reflect any source code that would be private.  We always expect to need to build BMIs since they are ephemeral in the current plan.  Thus (at least in my understanding) the issue of exposing IP should not apply.  If the assertions of this para are not true (e.g. somehow clang needs to embed source that would not otherwise be distributed) that would IMO be a show-stopper.
3. It is agreed that SG15/WG21 does not expect BMIs to be distributed in the current model; however, there is continuing pressure from end users and library authors for some system that would allow it - so we should be reluctant to move further away from that objective.
4. AFAIK GCC does not embed sources (and I do not recall any case where it would quote source, the diagnostics  refer to locations which can have ranges) - I am not closely involved in the GCC modules effort - but have also asked other devs in case I missed something.

From an engineering perspective it seems that we (clang) needs to find a better solution?

I would agree with @AaronBallman that this needs a higher level design discussion (I have no strong personal opinion on whether the merge is reverted - but then a decision should be taken about how this is to be implemented before any release is made - and given that this might be quite heavy lifting - it might be wise to revert it in case it cannot be resolved  in time - to avoid churn in user's expectations).

**Comment by iains** [comment]
FWIW: As [clang, GCC, MSVC] are currently implementing modules, there is no question of compatibility at the exchange of BMIs level (so that is currently a non-issue).  It does not seem that this is something in the "compatible with gcc-4.2.1" layer....

However, it is a tooling issue if one toolchain does not require sources distributed along with the BMIs but others do - so that is a potential reason to want to coordinate.

**Comment by ChuanqiXu9** [comment]
Thanks for the write-up. I've reverted and I'll try to open a RFC to get a wider discussion.

**Comment by ChuanqiXu9** [comment]
@AaronBallman @iains I've sent the RFC here: https://discourse.llvm.org/t/rfc-modules-should-we-embed-sources-to-the-bmi/81029

**Pull request merged**
