### PR TITLE
[DAGCombiner] Push freeze through SETCC and SELECT_CC

### PR DESCRIPTION
**Pull request by bjope**
Allow pushing freeze through SETCC and SELECT_CC even if there are multiple "maybe poison" operands. In the past we have limited it to a single "maybe poison" operand, but it seems profitable to also allow the multiple operand scenario.

One goal here is to avoid some regressions seen in review of
  https://github.com/llvm/llvm-project/pull/84924
when solving the select->and miscompiles described in
  https://github.com/llvm/llvm-project/issues/84653

### CODE REVIEW

**Comment by bjope** [comment]
This was splitted out from https://github.com/llvm/llvm-project/pull/84924

**Review by nikic — COMMENTED** [review]
This looks good to me, but someone familiar with RISCV should probably take a look at the test diffs.

**Review by arsenm — COMMENTED** [review]
I'm surprised this only has riscv test changes. Should there be more tests in other targets with freeze + cmp?

**Comment by RKSimon** [comment]
We're adding a lot of opcodes to the AllowMultipleMaybePoisonOperands - should we just enable it by default?

**Review by nikic — APPROVED** [review]
LGTM (but maybe rebase to check if there's any new test changes...)

**Pull request merged**
