### PR TITLE
[clang][AArch64] Enable fp128 for aarch64 linux target

### PR DESCRIPTION
**Pull request by MDevereau**

### CODE REVIEW

**Review by davemgreen — COMMENTED** [review]
Hi - I think this looks sensible, considering that long double == fp128. Should we be doing the same for other OS's in this file too?

**Comment by efriedma-quic** [comment]
See also #80195 (CC @nickdesaulniers).

gcc on aarch64 Linux only supports _Float128, not __float128; this seems like a bit of a compatibility hazard.

**Comment by nickdesaulniers** [comment]
Right, I'm more interested in being able to use on aarch64 the `_Float128` type as standardized by C23, than the clang specific `__float128` extension.  Does this PR help get us there?

**Comment by lntue** [comment]
> Right, I'm more interested in being able to use on aarch64 the `_Float128` type as standardized by C23, than the clang specific `__float128` extension. Does this PR help get us there?
> 
> EDIT: in fact, if we could skip propagating the clang-specific extension further, and just go straight to C23 `_Float128`, I'd prefer that.

I would second that we should go straight to C23 `_Float128`.  The current landscape for float128 supports in C (clang / gcc) and C++ (clang++, g++) : https://github.com/llvm/llvm-project/pull/78017#discussion_r1476974657
So adding `__float128` to aarch64 does not help much to simplify codes that need to work for both clang & gcc.

I haven't tested but I think the picture for float128 on riscv would be similar to aarch64.

**Comment by pranavk** [comment]
I have same opinion as @lntue and Nick.

**Pull request closed without merging**
