### PR TITLE
[flang][OpenMP] Fix unused prefixes in function-filtering-2 test

### PR DESCRIPTION
**Pull request by tblah**

### CODE REVIEW

**Comment by tblah** [comment]
@klensy does this fix all of the issues on your end?

Thanks @agozillon for suggesting the changes. You are listed as a co-author.

**Comment by agozillon** [comment]
> @klensy does this fix all of the issues on your end?
> 
> Thanks @agozillon for suggesting the changes. You are listed as a co-author.

Thank you for the fix, hopefully it helps!

**Comment by klensy** [comment]
Looks ok, but CI red.

**Comment by tblah** [comment]
The CI failure is due to https://github.com/llvm/llvm-project/pull/93718

**Comment by tblah** [comment]
Ping @skatrak @kiranchandramohan

**Review by skatrak — APPROVED** [review]
Thank you, this LGTM

**Pull request merged**
