### PR TITLE
[MC][ELF] Fix printing group signature symbols.

### PR DESCRIPTION
**Pull request by kosarev**
They may be not known.

### CODE REVIEW

**Comment by kosarev** [comment]
@MaskRay If this needs a test, can you give some pointers as to what it might look like and where we would want it, please? Not quite my area.

**Comment by MaskRay** [comment]
When is it unknown? We need a test

**Review by MaskRay — CHANGES_REQUESTED** [review]
.

**Comment by kosarev** [comment]
Caught downstream, yes. The comment for the `Group` field in `MCSectionELF.h` reads like the pointer can be null:
```
  /// The section group signature symbol (if not null) and a bool indicating
  /// whether this is a GRP_COMDAT group.
  const PointerIntPair<const MCSymbolELF *, 1, bool> Group;
```

There's also a guarding `if` for the pointer in `MCSectionELF` constructor:
```
  MCSectionELF(StringRef Name, unsigned type, unsigned flags,
...
        Group(group, IsComdat), LinkedToSym(LinkedToSym) {
    if (Group.getPointer())
      Group.getPointer()->setIsSignature();
  }
```

**Comment by kosarev** [comment]
Added test.

**Comment by MaskRay** [comment]
In the test you added
```
  // Test that switching to a group section with no associated signature name
  // doesn't crash.
  C.Streamer->switchSection(
      C.Ctx->getELFSection("foo", ELF::SHT_PROGBITS, ELF::SHF_GROUP));
```

I am still not convinced we should take the change. Perhaps we should disallow SHF_GROUP without a signature in switchSection. This isn't valid in ELF.

**Comment by kosarev** [comment]
> Perhaps we should disallow SHF_GROUP without a signature in switchSection. This isn't valid in ELF.

Should the ELF loading code do the check then?

**Comment by MaskRay** [comment]
> > Perhaps we should disallow SHF_GROUP without a signature in switchSection. This isn't valid in ELF.
> 
> Should the ELF loading code do the check then?

The section creation code can have an assert

**Comment by kosarev** [comment]
> > > Perhaps we should disallow SHF_GROUP without a signature in switchSection. This isn't valid in ELF.
> > 
> > Should the ELF loading code do the check then?
> 
> The section creation code can have an assert

Having the assert without the loading code erroring out signature-less group sections means we'll just crash on loading such ELFs.

**Comment by MaskRay** [comment]
We should avoid this construct when a SHF_GROUP section without a signature symbol is constructed. Factory functions can have this precondition.

**Pull request closed without merging**
