### PR TITLE
Try to use non-volatile registers for `preserve_none` parameters

### PR DESCRIPTION
**Pull request by brandtbucher**
This uses non-volatile registers for the first four (six on Windows) registers used for `preserve_none` argument passing. This allows these registers to stay "pinned", even if the body of the `preserve_none` function contains calls to other "normal" functions.

Example:

```c
void boring(void);

__attribute__((preserve_none)) void (continuation)(void *, void *, void *, void *);

__attribute__((preserve_none)) void entry(void *a, void *b, void *c, void *d)
{
    boring();
    __attribute__((musttail)) return continuation(a, b, c, d);
}
``` 

Before:

```asm
pushq   %rax
movq    %rcx, %rbx
movq    %rdx, %r14
movq    %rsi, %r15
movq    %rdi, %r12
callq   boring@PLT
movq    %r12, %rdi
movq    %r15, %rsi
movq    %r14, %rdx
movq    %rbx, %rcx
popq    %rax
jmp     continuation@PLT
```

After:

```asm
pushq   %rax
callq   boring@PLT
popq    %rax
jmp     continuation@PLT
```

### CODE REVIEW

**Comment by glaubitz** [comment]
Can you squash these commits? There shouldn't be a commit with just "Try" as the commit message in LLVM.

**Comment by brandtbucher** [comment]
> Can you squash these commits?

Done!

**Comment by brandtbucher** [comment]
@weiguozhi, @david-xl: Any chance you could review this small change? I think it'd be better to make it sooner rather than later, since it would be an ABI break once LLVM 19 ships.

(Sorry for the ping, I don't have permission to add reviewers.)

**Comment by david-xl** [comment]
@weiguozhi will help with some performance measurement with this change and get back.

**Comment by brandtbucher** [comment]
Thanks, I appreciate it!

**Comment by weiguozhi** [comment]
I ran the udp protobuf parsing micro benchmarks on my desktop. Following are the results. Base uses the original preserve_none implementation. Test uses the new parameter passing order from this patch.

```
                                                      base           test
BM_Parse_Proto2<FileDescSV, InitBlock, Alias>    677.912MB/s       693.477MB/s        +
BM_Parse_Proto2<FileDesc, InitBlock, Copy>       727.151MB/s       752.567MB/s        +
BM_Parse_Proto2<FileDesc, UseArena, Copy>        710.576MB/s       740.293MB/s        +
BM_Parse_Proto2<FileDesc, NoArena, Copy>         391.355MB/s       390.845MB/s        =
```

The first 3 sub tests got performance improvement due to reduced register copy instructions from the preserve_none parsing functions. The last test is not impacted. I checked its profile, found there are more register spilling in parsing function FastSS1. Because there is no live ranges change, I think it's more like a register allocation problem.

So the general result is very positive for protobuf parsing.

**Comment by david-xl** [comment]
> I ran the udp protobuf parsing micro benchmarks on my desktop. Following are the results. Base uses the original preserve_none implementation. Test uses the new parameter passing order from this patch.
> 
> ```
>                                                       base           test
> BM_Parse_Proto2<FileDescSV, InitBlock, Alias>    677.912MB/s       693.477MB/s        +
> BM_Parse_Proto2<FileDesc, InitBlock, Copy>       727.151MB/s       752.567MB/s        +
> BM_Parse_Proto2<FileDesc, UseArena, Copy>        710.576MB/s       740.293MB/s        +
> BM_Parse_Proto2<FileDesc, NoArena, Copy>         391.355MB/s       390.845MB/s        =
> ```
> 
> The first 3 sub tests got performance improvement due to reduced register copy instructions from the preserve_none parsing functions. The last test is not impacted. I checked its profile, found there are more register spilling in parsing function FastSS1. Because there is no live ranges change, I think it's more like a register allocation problem.
> 
> So the general result is very positive for protobuf parsing.

Very promising. Can you update the discourse thread with the results and propose for the change in preserve_none?

**Comment by weiguozhi** [comment]
The patch looks good to me. Could you also explicitly document that preserve_none's ABI is still unstable, it may be changed again in future if we can find other improvement opportunity.

**Comment by brandtbucher** [comment]
Yep. I also updated the docs with the new register-passing order.

**Comment by brandtbucher** [comment]
The Windows x64 Buildkite CI job is failing, but I can't find any failed tests in the downloaded logs. Any advice?

**Comment by david-xl** [comment]
> The Windows x64 Buildkite CI job is failing, but I can't find any failed tests in the downloaded logs. Any advice?

You can download the raw log file from the details view. From the log, it looks like not related to this change -- the flang build run out of heap space:

C:\BuildTools\VC\Tools\MSVC\14.29.30133\include\type_traits(1432): fatal error C1060: compiler is out of heap space

**Review by weiguozhi — APPROVED** [review]
Looks good to me! 
Thanks for the improvement.

**Comment by brandtbucher** [comment]
Anyone available to merge this (now that it's been approved)?

**Comment by haberman** [comment]
I'm really happy to see this proposed and merged; this is how I originally envisioned it would work: https://github.com/haberman/llvm-project/commit/e8d9c75bb35ce9c802f8eac522a2c6ce003f857f

**Comment by haberman** [comment]
Consider the case that `boring()` uses `preserve_most`:

```c
__attribute__((preserve_most)) void boring(void *);

__attribute__((preserve_none)) void (continuation)(void *, void *, void *, void *, void*);

__attribute__((preserve_none)) void entry(void *a, void *b, void *c, void *d, void* e)
{
    boring(a);
    __attribute__((musttail)) return continuation(a, b, c, d, e);
}
```

It seems we could get even better results for this case (without compromising the regular case) if we rearranged the arguments a bit further.

Original order (before this PR):

- RDI, RSI, RDX, RCX, R8, R9, R11, R12, R13, R14, R15, RAX

Current order (after this PR):

- R12, R13, R14, R15, RDI, RSI, RDX, RCX, R8, R9, R11, RAX

Possible improvements:

1. It appears that we're leaving R11 for second-last. But this is never used as an argument in normal functions, so we could consider using it before any of the normal argument registers.
2. Once we get to the normal argument registers, we could reverse their order to reduce the chance of overlap with `preserve_none` arguments.

A `preserve_none` order that seems ideal when calling `preserve_most`:

- R12, R13, R14, R15, R11, R9, R8, RCX, RDX, RSI, RDI, RAX

**Pull request merged**
