### PR TITLE
Fix codegen for transparent_union function params

### LINKED ISSUE #76773: [PowerPC][RISCV] Attribute 'signext' applied to incompatible type!
$ cat test.c
```
typedef union foo {
  int i;
} foo_t __attribute__((transparent_union));

void test(foo_t a) {
}
```

$ clang -target powerpc64le-linux -S -o - -emit-llvm test.c
Attribute 'signext' applied to incompatible type!
ptr @test
fatal error: error in backend: Broken module found, compilation aborted!

### PR DESCRIPTION
**Pull request by lei137**
Update codegen for func param with transparent_union attr to be that of
the first union member.

This is a followup to #101738 to fix non-ppc codegen and closes #76773.

### CODE REVIEW

**Comment by s-barannikov** [comment]
May it make sense to add tests with the argument passed in memory / by reference?

**Comment by s-barannikov** [comment]
I think the issue could be handled a different (more generic) way, by pulling `useFirstFieldIfTransparentUnion` to the caller and taking transparent unions into account when emitting LLVM IR for the formal / actual parameters somewhere in `CGCall.cpp`, so that ABIInfo implementations don't need to care about transparent unions at all.

**Review by amy-kwan — APPROVED** [review]
LGTM for using `CGT.ConvertType()` like you did previously. I agree that if we were to do a larger/refactoring patch, that can be separate since this PR fixes the current codegen.

**Comment by lei137** [comment]
> s-barannikov

done.

**Comment by lei137** [comment]
> May it make sense to add tests with the argument passed in memory / by reference?

@s-barannikov  Done.

**Pull request merged**
