### PR TITLE
[libc++] Remove the CI job testing Clang 15

### PR DESCRIPTION
**Pull request by ldionne**
Since LLVM 17 has been branched and is on the verge of being released, we can drop the CI job that tests against Clang 15. I think the number of cherry-picks to `release/17.x` will be a lot smaller now, so keeping a Clang 15 job around for that purpose seems unnecessary.

As a fly-by, this patch also removes some Clang 15 workarounds and test suite annotations as we usually do. It also removes some slightly older gcc test suite annotations that were missed.

### CODE REVIEW

**Comment by ldionne** [comment]
Note: I need to remember to ping https://reviews.llvm.org/D155562 once this lands.

**Review by mordante — APPROVED** [review]
Thanks for this patch and the additional cleanups!

A small note regarding the motivation. Our documentation states we should do this cleanup post release and not after branching. Having Clang 15 tested in main during the release process gave me quite a bit of confidence patches proposed for backporting didn't cause issues with Clang 15 in the release branch.

Based on our current state I don't mind landing this a few days before the official release.

As a side note would now also be a good time to remove the libc++ 17 release notes from main.

**Comment by ldionne** [comment]
> Thanks for this patch and the additional cleanups!
> 
> A small note regarding the motivation. Our documentation states we should do this cleanup post release and not after branching. Having Clang 15 tested in main during the release process gave me quite a bit of confidence patches proposed for backporting didn't cause issues with Clang 15 in the release branch.

I agree 100%, and normally I wouldn't mind waiting just a bit longer. However in this case this is blocking a couple other reviews in Phabricator so I am keen to get it done so we can close these Phabricator reviews!

**Comment by ldionne** [comment]
Once Xcode 15 is released (not just as a RC), I'll update the macOS bots and bump the minimum AppleClang version as well. I think that is required for this patch to land.

**Comment by ldionne** [comment]
Ok, this was much more complicated than I anticipated because updating the macOS CI builders to Xcode 15 required a bunch of changes, but we should be near now. https://github.com/llvm/llvm-project/pull/67065 is bumping the AppleClang version, and then I'll rebase this patch.

**Pull request merged**
