### PR TITLE
[NFC] Remove trailing whitespace across all non-test related files

### PR DESCRIPTION
**Pull request by AZero13**
Every once in a while, some formatting scanner will cause the CI to stop because of whitespace issues, so it is is best to just remove them in one go, especially since it seems only non-test files tend to be under scrutiny by automatic formatting checkers.

### CODE REVIEW

**Comment by AtariDreams** [comment]
I'm just gonna split this up. Sorry.

**Comment by joker-eph** [comment]
Fine with me if we want to land this as is, but per-top-level subproject may be a better granularity.

**Comment by felipepiovezan** [comment]
Juuust to make sure, was this discussed before? This seems akin to running clang-format on the entire project, which last time we talked about still faced opposition: https://discourse.llvm.org/t/rfc-clang-format-all-the-things/76614/11

**Comment by arichardson** [comment]
This will cause huge merge conflicts for all downstreams. While they are easy to resolve it can be quite annoying. I think we should just do this as part of the global clang-format.

**Comment by jrtc27** [comment]
Also this is the kind of commit that should really be done by a core trusted member of the community. It's way too easy to hide something nefarious (not that I'm accusing you of that, just that we always need to be vigilant) in an 8k+ diff, and it's not much fun to review that code. Also it's best when people provide the scripts used to do these kinds of mass changes; that (a) lets people verify what you did by auditing the script and running it themselves (b) lets downstreams easily perform the same change on their forks.

The fact that this is a +8347 -8382 diff also confuses me; I would expect the number of lines to remain constant, but maybe you're including trailing blank lines as trailing whitespace?..

**Comment by pogo59** [comment]
> This seems akin to running clang-format on the entire project, which last time we talked about still faced opposition

My impression (I admit I haven't reviewed the whole thread lately) is that the opposition has mostly to do with how clang-format mangles some constructs, not to the idea in general.

I'm juggling 4 projects at the moment, I have to finish some internal release-related work before I can get back to clang-format-all-the-things.

**Comment by felipepiovezan** [comment]
> > This seems akin to running clang-format on the entire project, which last time we talked about still faced opposition
> 
> My impression (I admit I haven't reviewed the whole thread lately) is that the opposition has mostly to do with how clang-format mangles some constructs, not to the idea in general.
> 
> I'm juggling 4 projects at the moment, I have to finish some internal release-related work before I can get back to clang-format-all-the-things.

Sorry, you might be right; my intent with that comment was not to a make broad summary of the thread, but rather to point out the thread's existence and that this PR should probably be folded into that discussion.

**Pull request closed without merging**
