### PR TITLE
[llvm][Support] Add quotes around option name

### PR DESCRIPTION
**Pull request by lamb-j**

### CODE REVIEW

**Review by makslevental — APPROVED** [review]

**Comment by makslevental** [comment]
@lamb-j let me know if you need me to merge.

**Comment by dwblaikie** [comment]
Could you add some test coverage for this?

**Comment by makslevental-amd** [comment]
You can't? You'd have to actual register overlapping command line options which would fatal_error for all the other tests too?

**Comment by lamb-j** [comment]
We may be able to create a small reproducer that defines two overlapping options, such that when it's compiled an executed it produces the error? Looking into it now.

**Comment by dwblaikie** [comment]
Oh, sorry, I see it's a report_fatal_error - just thought it was a normal error message, not an assert/fatal/library-misuse. Sometimes we test those (like llvm::Error has tests to ensure it assert-fails in the right places/ways) but for one that's only reachable through a custom binary, not sure it'll be worth the hassle. Appreciate you looking into it, though - maybe there's a way that's not so bad.

**Pull request merged**
