### PR TITLE
[libc][math][c23] removing dfmal for riscv 

### PR DESCRIPTION
**Pull request by aaryanshukla**

### CODE REVIEW

**Comment by mikhailramalho** [comment]
Can you try to fix the issue instead?

**Comment by aaryanshukla** [comment]
Yes, getting a fix right now

**Comment by overmighty** [comment]
It's the same issue as in https://github.com/llvm/llvm-project/pull/101720. Except in this case, I'm not sure if the test code is doing what it was meant to. It's converting from `StorageType` to `InType` instead of bit-casting.

**Comment by overmighty** [comment]
Closing since https://github.com/llvm/llvm-project/pull/101763 was merged instead.

**Pull request closed without merging**
