### PR TITLE
[test] Move CodeGen/aarch64-* into the AArch64 subfolder

### PR DESCRIPTION
**Pull request by MaskRay**
Similar to other targets (AMDGPU, Mips, PowerPC, RISCV, X86, ...)

`ninja check-clang-codegen-aarch64` can be used to test this subfolder.

### CODE REVIEW

**Review by davemgreen — APPROVED** [review]
Sounds like a good idea to me if no-one else objects. LGTM

**Review by jthackray — APPROVED** [review]
Fine by me; I guess anyone with a PR in-flight will need to rebase.

**Review by jthackray — COMMENTED** [review]
You could also create an ARM/ directory, and move arm-* files into that too (186 files)

**Comment by davemgreen** [comment]
> You could also create an ARM/ directory, and move arm-* files into that too (186 files)

Yeah - We might just need to be careful of tests that test both arm and aarch64 targets.
I noticed there are some arm64-* tests too that could be moved into the aarch64 directory.

**Pull request merged**
