### PR TITLE
Ensure `collectTransitivePredecessors` returns Pred only from the Loop.

### PR DESCRIPTION
**Pull request by Nirhar**
It's possible that we encounter Irreducible control flow, due to which, we may find that a few predecessors of BB are not a part of the CurLoop. Currently we crash in the function for such cases. This patch ensures that we only return Predecessors that are a part of CurLoop and gracefully ignore other Predecessors.

For example, consider Irreducible IR of this form:
```
define i64 @baz() {
bb:
  br label %bb1

bb1:                                              ; preds = %bb3, %bb
  br label %bb3

bb2:                                              ; No predecessors!
  br label %bb3

bb3:                                              ; preds = %bb2, %bb1
  %load = load ptr addrspace(1), ptr addrspace(1) null, align 8
  br label %bb1
}
```

This crashes when `collectTransitivePredecessors` is called on the `%bb1<Header>, %bb3<latch>` loop, because the loop body has a predecessor `%bb2` which is not a part of the loop. 

See https://godbolt.org/z/E9fM1q3cT for the crash

### CODE REVIEW

**Comment by Nirhar** [comment]
@nikic @arsenm

**Comment by arsenm** [comment]
Needs tests

**Comment by Nirhar** [comment]
I'm not sure how I can write a lit test for this, reason being, most of the loop transformation passes run `loop-simplify` which removes the irreducibility from the above example. I don't know how to invoke `collectTransitivePredecessors` without using any of the loop passes.

**Comment by arsenm** [comment]
> I'm not sure how I can write a lit test for this, reason being, most of the loop transformation passes run `loop-simplify` which removes the irreducibility from the above example. I don't know how to invoke `collectTransitivePredecessors` without using any of the loop passes.

You can directly run the must-execute analysis printer and check the output. Tests ideally run in isolation, the context where it is used in the pass pipeline should not matter

**Comment by Nirhar** [comment]
@arsenm Thanks for the idea! Have added a lit test.

**Review by arsenm — APPROVED** [review]

**Comment by Nirhar** [comment]
@arsenm Can you merge it? I don't have merge permissions. Thanks!

**Pull request merged**
