### PR TITLE
[LLVM][DWARF] Add compilation directory and dwo name to TU in dwo section

### PR DESCRIPTION
**Pull request by ayermolo**
This adds support to help LLDB when binary is built with split dwarf, has
.debug_names accelerator table and DWP file.
Final linked binary might have Type Units (TUs) with the same type signature in multiple
compilation units. Although the signature is the same, TUs are not guranted to
be bit identical. This is not a problem when they are in .o/.dwo files as LLDB
can find them by looking at the right one based on DW_AT_comp_dir/DW_AT_name in
skeleton CU. Once DWP is created, TUs are de-duplicated, and we need to know
from which CU remaining one came from.

This approach allows LLDB to figure it out, with minimal changes to the rest of
the tooling. As would have been the case if .debug-tu-index section in DWP was
modified.

### CODE REVIEW

**Comment by dwblaikie** [comment]
Looks OK.

We could potentially do this in all DWARF versions, not just >= 5. (seems relatively harmless to do it in the v4 extension version of Split DWARF?)

& could you get some measurements, especially .o file size (or more specifically, .o .debug_info size) for a clang build with this patch/without this patch? Just so we know what sort of growth to expect.

**Comment by ayermolo** [comment]
> Looks OK.
> 
> We could potentially do this in all DWARF versions, not just >= 5. (seems relatively harmless to do it in the v4 extension version of Split DWARF?)
> 
> & could you get some measurements, especially .o file size (or more specifically, .o .debug_info size) for a clang build with this patch/without this patch? Just so we know what sort of growth to expect.

We can, but then it just increases complexity, slightly, + more tests modified, probably, since then there will be else statement for GNU_dwo_name.

OK, will see what increase in clang is.

**Comment by ayermolo** [comment]
From clang-18.dwp
With change:
[ 7] .debug_info.dwo   PROGBITS        0000000000000000 202db7b1 4e5076d4 00   E  0   0  1
Without change:
[ 7] .debug_info.dwo   PROGBITS        0000000000000000 202d78b3 4e4f5985 00   E  0   0  1

DIff 73039 bytes.

**Review by dwblaikie — APPROVED** [review]
Works for me/at least worth using it to experiment, see if it works for lldb, etc.

Maybe a comment in the DwarfDebug source explaining what these attributes might be useful for?

**Comment by ayermolo** [comment]
> Works for me/at least worth using it to experiment, see if it works for lldb, etc.
> 
> Maybe a comment in the DwarfDebug source explaining what these attributes might be useful for?

I don't think LLDB has support yet for this, and tombstoning in linker yet.
I believe @clayborg was waiting until this is in trunk.

**Comment by dwblaikie** [comment]
> > Works for me/at least worth using it to experiment, see if it works for lldb, etc.
> > Maybe a comment in the DwarfDebug source explaining what these attributes might be useful for?
> 
> I don't think LLDB has support yet for this, and tombstoning in linker yet. I believe @clayborg was waiting until this is in trunk.

Yep yep - but I'm OK with tihs going in first. Sorry, didn't mean to request further testing/demonstrated value before it's committed - just that I think this is adequate to be committed, to facilitate further testing/development.

**Pull request merged**
