### PR TITLE
[clang][NFC] Format clang/lib/Sema/Sema.cpp

### PR DESCRIPTION
**Pull request by atetubou**
This is to avoid modifying unrelated code when auto format is on in our editor.

### CODE REVIEW

**Comment by ChuanqiXu9** [comment]
I remember we have policies that we don't like patches which purely formats codes. It makes backporting and cherry-picking harder. But I can't find the wording now.

CC: @AaronBallman @Endilll

**Comment by ChuanqiXu9** [comment]
Oh, I found it here: https://llvm.org/docs/CodingStandards.html#introduction

> Our long term goal is for the entire codebase to follow the convention, but we explicitly do not want patches that do large-scale reformatting of existing code.

**Comment by Endilll** [comment]
Bulk formatting of Clang is still under discussion in https://discourse.llvm.org/t/rfc-clang-format-all-the-things/76614. At least I don't see a consensus called there one way or another.

Our [developer policy](https://llvm.org/docs/DeveloperPolicy.html) states the following:
> Avoid committing formatting- or whitespace-only changes outside of code you plan to make subsequent changes to.

So yeah, we can't merge this at the moment, unfortunately. This might change in the future, though, as more people lean towards bulk formatting after several years of very slow gradual reformatting with accordance to our current policy.

**Comment by atetubou** [comment]
Thank you for references both.

Actually, I'd like to have PR like https://github.com/llvm/llvm-project/pull/83961.
Is it acceptable to merge this kind of PR in that case then?

**Comment by ChuanqiXu9** [comment]
> Thank you for references both.
> 
> Actually, I'd like to have PR like #83961. Is it acceptable to merge this kind of PR in that case then?

I don't feel the patches are related. I think you can only format the changed lines.

**Comment by atetubou** [comment]
Oh, I found https://code.visualstudio.com/docs/getstarted/settings#:~:text=modificationsIfAvailable. 
So let me use that instead. Thank you for your comments.

**Pull request closed without merging**
