### PR TITLE
[flang] Handle Hollerith in data statement initialization in big endian

### PR DESCRIPTION
**Pull request by kkwli**
Update to read the Hollerith literal in reverse order for big endian environment.

### CODE REVIEW

**Review by klausler — APPROVED** [review]

**Comment by rorth** [comment]
This patch broke the test on Solaris/sparcv9: 
```flang/test/Semantics/data08.f90:9:7: error: LE: expected string not found in input
! LE: jx (InDataStmt) size=4 offset=0: ObjectEntity type: INTEGER(4) init:1684234849_4
      ^
```
Although SPARC is big-endian, this test (like some others) assume everything but AIX is little-endian.  Seems pretty disingenious to me having to explicitly list every big-endian system in every affected test rather than having some `lit` keyword for this feature.

**Comment by rorth** [comment]
It should be done in `lit` itself, rather than repeating the code in every testsuite.  This has nothing to do with Solaris, btw.  It's SPARC that is big-endian (while there's also a Solaris/amd64 port that obviously is not).  Linux/sparc64 is affected, too (but the build is still running ATM).

See. PR #103722 for an example how I did it before.  However, this approach doesn't scale (imagine adding s390x to the mix...)

**Comment by kkwli** [comment]
@rorth I am looking into defining a variable in `lit.cfg.py` so that tests can check that for big or little endian. I will see if it works.

**Comment by rorth** [comment]
This isn't right: there's nothing `flang`-specific in there.  The feature definition belongs into `lit` proper, somewhere below `llvm/utils/lit` so the whole testsuite can use it.

**Comment by kkwli** [comment]
Yes, I see that things should to be done in `llvm/utils/lit` if there is a need from other projects. I am not sure about that. I propose to add it in `flang/test/lit.cfg.py` for now. If there is a need in other projects, we can easily move the code to `llvm/utils/lit`.

**Comment by rorth** [comment]
I've done some looking myself and found that the multi-target nature of LLVM causes massive problems here.  Imagine a test with several `RUN:` lines for different targets with different endianess.  An endianess `lit` feature would have to be different per `RUN:` line.  I don't see how this can easily be done.  I fear for the moment we'll have to follow the approach in `Lower/default-initialization-globals.f90`, however repetetive and unmaintainable (imagine someone adding yet another big-endian target like `s390x`) it is.

At the same time we may want to file a `lit` bug: maybe the maintainers have ideas how to handle this.  The GCC testsuite is way simpler in that regard since it can perform whatever tests are necessary to determine the properties of the single target under test since those are guaranteed to be fixed.

**Comment by kkwli** [comment]
Yes, the multiple RUN lines tests can be troublesome. I post [PR 105854](https://github.com/llvm/llvm-project/pull/105854) to fix up `flang/test/Semantics/data08.f90`.

**Pull request merged**
