### PR TITLE
[cuda][HIP] `__constant__` should imply constant

### PR DESCRIPTION
**Pull request by AlexVlx**
Currently, `__constant__` variables do not get unconditionally marked as `constant` in IR, which seems a bit odd given their definition. This is generally inconsequential for NVPTX/AMDGPU, since said variables get emitted in the constant address space for those BEs. However, it is potentially significant for e.g. HIP-on-SPIR-V cases, as SPIR-V does not allow casts to/from the constant AS (`UniformConstant`), which forces `__constant__` variables to be emitted in the global AS, thus making IR constness meaningful.

### CODE REVIEW

**Comment by Artem-B** [comment]
`__constant__` may not necessarily be `const` for IR purposes. I.e. IR may not rely on the 'known' values, as seen in IR, as the data may actually be populated by the host via CUDA API calls `cudaMemcpyToSymbol` before the GPU kernel launch.

**Comment by AlexVlx** [comment]
> `__constant__` may not necessarily be `const` for IR purposes. I.e. IR may not rely on the 'known' values, as seen in IR, as the data may actually be populated by the host via CUDA API calls `cudaMemcpyToSymbol` before the GPU kernel launch.

But since this is marked `externally_initialised` on the device side, one would assume that those semantics still hold i.e. there's no known value to assume?

**Comment by AlexVlx** [comment]
> > `__constant__` may not necessarily be `const` for IR purposes. I.e. IR may not rely on the 'known' values, as seen in IR, as the data may actually be populated by the host via CUDA API calls `cudaMemcpyToSymbol` before the GPU kernel launch.
> 
> But since this is marked `externally_initialised` on the device side, one would assume that those semantics still hold i.e. there's no known value to assume?

Oh, I guess the concern might be around doing a `cuda/hipMemcpyToSymbol` during a kernel's execution (i.e. `__global__ foo()` is executing, host sets a __constant__, notifies foo, and expects foo to observe the updated constant)? I admit that I'm not certain if that is allowed, if it is then yes, this is problematic / not viable.

**Comment by Artem-B** [comment]
Well, it's certainly used that way in existing CUDA code and it's been around forever: 
Here are few random examples from both 10 years ago:
https://stackoverflow.com/questions/20535683/cuda-5-5-cudamemcpytosymbol-constant-and-out-of-scope-error
and a fairly recent example: https://forums.developer.nvidia.com/t/constant-memory-cudamemcpytosymbol-and-compilation-units/248780

**Comment by Artem-B** [comment]
I'm not 100% sure that `externally_initialized` is sufficient to deal with this use pattern.

IR manual says: https://llvm.org/docs/LangRef.html#global-variables 
> By default, global initializers are optimized by assuming that global variables defined within the module are not modified from their initial values before the start of the global initializer. This is true even for variables potentially accessible from outside the module, including those with external linkage or appearing in @llvm.used or dllexported variables. This assumption may be suppressed by marking the variable with externally_initialized.

It appears that `externally_initialized` is meant to suppress the assumption about the values only up to the point of the global initializer start. However, CUDA & NVIDIA GPUs do not have any global initializers, so it's either constant values or uninitialized. Considering that the values in the array may be changed by the host between kernel invocations, LLVM should never use the 'known' values in the global arrays, unless they explicitly made `const` by the user.

**Comment by AlexVlx** [comment]
> Well, it's certainly used that way in existing CUDA code and it's been around forever: Here are few random examples:
> 
> * from both 10 years ago:
>   https://stackoverflow.com/questions/20535683/cuda-5-5-cudamemcpytosymbol-constant-and-out-of-scope-error
> * fairly recent example: https://forums.developer.nvidia.com/t/constant-memory-cudamemcpytosymbol-and-compilation-units/248780

Hmm, neither of those illustrates what I was getting at / both would still work just the same even with this change, I think. Because the `memcpyToSymbol`s would always be sequenced before the actual kernel dispatch expected to observe the modified values, and since these remain `externally_initialized` it should be fine (empirically, this appears to work as expected). 

Also, turns out that the case I was considering (kernel executes concurrently with updates to a `__constant__` variable it is accessing) is explicitly called out as UB by CUDA under 10.2.2: `The behavior of modifying a constant from the host while there is a concurrent grid that access that constant at any point of this grid’s lifetime is undefined.`, so we're safe from that at least.

**Comment by Artem-B** [comment]
It has nothing to do with writing to those arrays while the kernel is running. That would indeed be UB.

> both would still work just the same even with this change,

No, they will not. Here's the demonstration of the behavior change that `const` brings to the table:
https://cuda.godbolt.org/z/h6e5Wb4PT

It shows that adding `const` allows compiler to use the initializer values as written (it does not even bother instantiating `cxxx`), while without `const` it reads the array values, assuming that they may be changed externally.

**Comment by arsenm** [comment]
If it's not legal for it to be marked as constant, it's also not legal to use constant address space

**Comment by yxsamliu** [comment]
> It has nothing to do with writing to those arrays while the kernel is running. That would indeed be UB.
> 
> > both would still work just the same even with this change,
> 
> No, they will not. Here's the demonstration of the behavior change that `const` brings to the table: https://cuda.godbolt.org/z/h6e5Wb4PT
> 
> It shows that adding `const` allows compiler to use the initializer values as written (it does not even bother instantiating `cxxx`), while without `const` it reads the array values, assuming that they may be changed externally.

EarlyCSE pass propagates the constant value https://cuda.godbolt.org/z/Ta8rKjMTo

However, 

`
@xxx = dso_local addrspace(4) externally_initialized global [3 x i32] [i32 1, i32 2, i32 3], align 4
@_ZL4cxxx = internal addrspace(4) constant [3 x i32] [i32 1, i32 2, i32 3], align 4
`
In this case, _ZL4cxxx does not have externally_initialized . If this patch does not remove externally_initialized, probably this constant propagation won't happen.

Maybe Alex can add a lit test to prove that.

**Comment by AlexVlx** [comment]
@yxsamliu beat me to it. The problem here is that the example illustrates language level const on a variable with internal linkage (which is mandatory for `__constant__` variables in non-RDC compilation AFAICT from 17.5.24.1) and we don't set externally_initialized on that, which matches C/C++ expected semantics, I believe (there's an oblique mention as to the reasoning, which is that the loader should be allowed to place these in `.rodata` if they materialise at all). Regarding the lit test, I can definitely add another one, but I will note we already have `Transforms/GlobalOpt/externally-initialized.ll`, which probably can be extended?

Please note that this is something that wouldn't work (as apparently expected) today either. The user can write the code  @Artem-B wrote (put const on a `__constant__`, add an initialiser because otherwise things would be broken), and they'd get exactly the potentially unexpected behaviour. The very fact that the godbolt example exists points that out (the example also helpfully points out that NVCC has the same behaviour). Unfortunately the CUDA spec does not appear to talk about this (a `const` qualified `__constant__` variable) directly, but working back from 17.5.23.2 we can conclude that they're fine as long as the host compiler is not VC++.

**Review by Artem-B — APPROVED** [review]

**Comment by AlexVlx** [comment]
I've extende the test under `Transforms/GlobalOpt/externally-initialized.ll` to also cover `constant`s / ensure they don't get CSEd.

**Pull request merged**
