### PR TITLE
[X86] Disable the `vpdpwssd -> vpmaddwd + vpaddd` combiner pattern on AMD Zen4

### PR DESCRIPTION
**Pull request by bjacob**
This tweaks the existing `vpdpwssd -> vpmaddwd + vpaddd` machine combiner pattern to *not* kick in on AMD Zen4, fixing Issue #84182.

This pattern was introduced in https://github.com/llvm/llvm-project/commit/8f7f9d86a7555263ef08fded15a6b778d796ec3f , and I have expressed in https://github.com/llvm/llvm-project/issues/84182#issuecomment-1981685009 some generic concerns about it, which are not even AMD-specific: my actual first choice would be to simply revert that commit. This PR only exists on the assumption that we don't want to do that, that we want to keep the current behavior outside of the AMD Zen4 target where Issue #84182 shows it to be a clear regression. To be clear though, what I am saying in https://github.com/llvm/llvm-project/issues/84182#issuecomment-1981685009 is that it also is potentially (depending on scheduling info) a regression on non-AMD CPUs, on different kinds of test cases, one being the simple one-intrinsic testcase added in this PR (having only one intrinsic it clearly falls out of the scope of the rationale for https://github.com/llvm/llvm-project/commit/8f7f9d86a7555263ef08fded15a6b778d796ec3f, so the fact that that commit did affect it seems unintentional) and another being real world optimized SIMD code that, unlike the code motivating this in the commit message, would use enough registers to not be gated on instruction latency.

This PR also fixes what seems like a bug(?) in  https://github.com/llvm/llvm-project/commit/8f7f9d86a7555263ef08fded15a6b778d796ec3f : in
https://github.com/llvm/llvm-project/blob/3714f937b835c06c8c32ca4f3f61ba2317db2296/llvm/lib/Target/X86/X86InstrInfo.cpp#L10584-L10586
the `return true;` was not part of the `if` branch, so the function would return there even if the `if` was not taken, preventing the `TargetInstrInfo::getMachineCombinerPatterns` from being reached. This seems unintentional and seems to be a departure from all the other `getMachineCombinerPatterns` functions that  I can find, where either the target-specific case or the fallback `TargetInstrInfo::getMachineCombinerPatterns` is taken.

### CODE REVIEW

**Review by RKSimon — COMMENTED** [review]
I'm hoping we can address this for the general case in #84182 - but in the meantime, we shouldn't be using CPU name matching - its better to create a "TuningFastVNNI" flag in X86.td and add it to the ZN4Tuning flags and use that to control the MC pattern.

But hopefully this patch won't be necessary..........

**Comment by bjacob** [comment]
I see. I'm curious what "address this for the general case in https://github.com/llvm/llvm-project/issues/84182" would look like. Certainly if this actually comes down to a znver4 scheduling model inaccuracy, it would be great to simply fix that, but at the moment I can't find an inaccuracy there that would be relevant to this particular issue.

I've just connected with @ganeshgit on this so I might just be able to bow out of this and let the experts weigh in :-D  Closing this PR for now.

**Comment by RKSimon** [comment]
@bjacob Reopening this - please can you replace the "EnableVPDPWSSTPatterns" with a Tuning flag as suggested on #84182

**Comment by ganeshgit** [comment]
> @bjacob Reopening this - please can you replace the "EnableVPDPWSSTPatterns" with a Tuning flag as suggested on #84182
It's on me. I will submit a patch.

**Pull request closed without merging**
