### PR TITLE
AMDGPU: Mark grid size loads with range metadata

### PR DESCRIPTION
**Pull request by arsenm**
Only handles the v5 case.

### CODE REVIEW

**Comment by arsenm** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/113019?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#113019** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/113019?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#113018** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/113018?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by shiltian — APPROVED** [review]

**Comment by shiltian** [comment]
How are we gonna use the three sizes after we annotate them?

**Comment by arsenm** [comment]
> How are we gonna use the three sizes after we annotate them? What is the impact of using an inaccurate number?

It enables known bits style optimizations. I think we're introducing these a bit late though, eventually we should probably move this directly intro the attributor

**Comment by arsenm** [comment]
### Merge activity

* **Dec 9, 10:58 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/113019).

**Pull request merged**
