### PR TITLE
[CMake] Remove EXPORT_SYMBOLS_FOR_PLUGINS from #102138

### PR DESCRIPTION
**Pull request by cachemeifyoucan**
Partially remove some of the changes from #102138 as
EXPORT_SYMBOLS_FOR_PLUGINS doesn't work on all the configurations.

### CODE REVIEW

**Comment by cachemeifyoucan** [comment]
Try to fix https://github.com/llvm/llvm-project/pull/102138 after failing on `clang-ppc64-aix` bot: [https://lab.llvm.org/buildbot/#/builders/64/builds/62](https://lab.llvm.org/buildbot/#/builders/64/builds/620)

**Comment by cachemeifyoucan** [comment]
That looks an unstable test the has been failed before.

**Comment by jakeegan** [comment]
Thanks for the build fix! However we are now seeing a test failure that seems to be related
https://lab.llvm.org/buildbot/#/builders/64/builds/643/steps/6/logs/FAIL__LLVM-Unit__DynamicLibraryTests_DynamicLibrar

**Comment by cachemeifyoucan** [comment]
@jakeegan I will create a PR to restore this target to the previous configuration but it would be good to figure out what flags/setting were different that caused that failure for you.

**Pull request merged**
