### PR TITLE
workflows: Merge LLVM tests together into a single job

### PR DESCRIPTION
**Pull request by tstellar**
This is possible now that the free GitHub runners for Windows and Linux have more disk space:
https://github.blog/2024-01-17-github-hosted-runners-double-the-power-for-open-source/

I also had to switch from macOS-11 to macOS-13 in order to prevent the job from timing out.  macOS-13 runners have 4 vCPUs and the macOS-11 runners only have 3.

### CODE REVIEW

**Review by boomanaiden154 — APPROVED** [review]
LGTM.

This is a nice simplification. I'm assuming since this goes to MacOS13, we don't end up hitting https://github.com/llvm/llvm-project/pull/77270?

**Comment by tstellar** [comment]
@linux4life798 We need to upgrade to macOS-13 to avoid timeouts.

**Comment by tstellar** [comment]
> LGTM.
> 
> This is a nice simplification. I'm assuming since this goes to MacOS13, we don't end up hitting #77270?

No, we do hit this same bug, unfortunately.

**Comment by tstellar** [comment]
@linux4life798 I was able to get it to work by increasing the cache size to 4GB: https://github.com/tstellar/llvm-project/actions/runs/7618766244/job/20750565953

I'm going to try to see how low I can make it while it still works.

**Comment by tstellar** [comment]
Switching from sccache to ccache fixes the issue too.  Maybe this is the best solution?

**Comment by tstellar** [comment]
I bumped the maximum cache size up to 2GB, in order to workaround the issue with macOS-13.

**Comment by tstellar** [comment]
The macOS-11 builds have started to timeout now, because of how long it takes to install sccache, so I need to merge this in order to fix the workflows.  We can discuss optimal cache size or whether to switch to ccache in a follow up discussion.

**Review by boomanaiden154 — APPROVED** [review]
SGTM. We can always iterate in tree and getting a fix in for that issue is pretty important right now.

**Comment by linux4life798** [comment]
Also in terms of caching options, it looks like sccache has builtin support for Github ation cache. See https://github.com/mozilla/sccache/blob/main/docs/GHA.md.

**Pull request merged**
