### PR TITLE
[ValueTracking] Add support for `vector_reduce_{s,u}{min,max}` in `isKnownNonZero`/`computeKnownBits`.

### PR DESCRIPTION
**Pull request by goldsteinn**
- **[InstCombine] Add tests for non-zero/knownbits of `vector_reduce_{s,u}{min,max}`; NFC**
- **[ValueTracking] Add support for `vector_reduce_{s,u}{min,max}` in `isKnownNonZero`**
- **[ValueTracking] Add support for `vector_reduce_{s,u}{min,max}` in `computeKnownBits`**

### CODE REVIEW

**Comment by goldsteinn** [comment]
If these changes are desirable ill add support for the rest of the reduce intrinsics.

**Review by nikic — CHANGES_REQUESTED** [review]
I think some basic support here could be reasonable, but this implementation looks too precise. In particular, I think the approach of doing a per-element evaluation of the vector is unprecedented -- we generally only look at all (demanded) elements as a unit.

So the implementation I'd expect would be more something along the lines of taking the known bits of the input vector and using those as the result known bits as well. (For min/max reductions that is, not quite that simple for some of the other ones.)

**Comment by goldsteinn** [comment]
> I think some basic support here could be reasonable, but this implementation looks too precise. In particular, I think the approach of doing a per-element evaluation of the vector is unprecedented -- we generally only look at all (demanded) elements as a unit.
> 
> So the implementation I'd expect would be more something along the lines of taking the known bits of the input vector and using those as the result known bits as well. (For min/max reductions that is, not quite that simple for some of the other ones.)

for `min`/`max`/`or` its pretty easy to do a reasonable job w.o per-ele, but that kind of prohibits things like `xor`/`add`/etc... Are you opposed to those being added in general?

**Comment by goldsteinn** [comment]
> > I think some basic support here could be reasonable, but this implementation looks too precise. In particular, I think the approach of doing a per-element evaluation of the vector is unprecedented -- we generally only look at all (demanded) elements as a unit.
> > So the implementation I'd expect would be more something along the lines of taking the known bits of the input vector and using those as the result known bits as well. (For min/max reductions that is, not quite that simple for some of the other ones.)
> 
> for `min`/`max`/`or` its pretty easy to do a reasonable job w.o per-ele, but that kind of prohibits things like `xor`/`add`/etc... Are you opposed to those being added in general?

Either way, updated this so its quite simple.

**Review by nikic — APPROVED** [review]
LG

**Comment by nikic** [comment]
> > I think some basic support here could be reasonable, but this implementation looks too precise. In particular, I think the approach of doing a per-element evaluation of the vector is unprecedented -- we generally only look at all (demanded) elements as a unit.
> > So the implementation I'd expect would be more something along the lines of taking the known bits of the input vector and using those as the result known bits as well. (For min/max reductions that is, not quite that simple for some of the other ones.)
> 
> for `min`/`max`/`or` its pretty easy to do a reasonable job w.o per-ele, but that kind of prohibits things like `xor`/`add`/etc... Are you opposed to those being added in general?

Yeah, I don't think we should do them if they require per-element reasoning to do something worthwhile. We can at least handle and/or though (and only in KnownBits).

**Comment by goldsteinn** [comment]
> Yeah, I don't think we should do them if they require per-element reasoning to do something worthwhile. We can at least handle and/or though (and only in KnownBits).

Kk, ill post patches for the rest tomorrow.
Thinking a bit more we will be able to do a bit for most operators.

**Review by RKSimon — APPROVED** [review]
LGTM

**Pull request closed without merging**
