### PR TITLE
[PowerPC] Expand global named register support

### PR DESCRIPTION
**Pull request by lei137**
Enable all valid registers for intrinsics that read from and write
to global named registers.

### CODE REVIEW

**Review by redstar — APPROVED** [review]
LGTM.

**Comment by nathanchance** [comment]
For what it's worth, this breaks building the Linux kernel for 32-bit powerpc for me because [the kernel uses `r2` as a global register variable for `current`](https://elixir.bootlin.com/linux/v6.11.4/source/arch/powerpc/include/asm/current.h#L33).

```
$ make -skj"$(nproc)" ARCH=powerpc CROSS_COMPILE=powerpc-linux-gnu- LLVM=1 LLVM_IAS=0 mrproper pmac32_defconfig ipc/namespace.o
fatal error: error in backend: Trying to obtain a reserved register "r2".
...
```

While this seems expected given the change, just in case, I ran this through `cvise`, which spits out:

```c
register struct task_struct *current asm("r2");
struct task_struct {
  struct cred *cred;
};
struct cred {
  int euid;
} inc_ucount(int);
int *create_ipc_ns() {
  inc_ucount(({ ({ current->cred; })->euid; }));
  return (void *)8;
}
```

which works with `clang` immediately prior to this change and GCC:

```
$ clang --version | head -1
ClangBuiltLinux clang version 20.0.0git (https://github.com/llvm/llvm-project.git 06d192925d3510d0af6c10e6f64f6deabf66b75f)

$ clang --target=powerpc-linux-gnu -Wall -Werror -Wfatal-errors -c -o /dev/null namespace.i
fatal error: error in backend: Trying to obtain a reserved register "r2".
...
```

```
$ clang --version | head -1
ClangBuiltLinux clang version 20.0.0git (https://github.com/llvm/llvm-project.git e57548387000071562f44bfd66644480c8e6542d)

$ clang --target=powerpc-linux-gnu -Wall -Werror -Wfatal-errors -c -o /dev/null namespace.i
```

```
$ powerpc-linux-gcc --version | head -1
powerpc-linux-gcc (GCC) 14.2.0

$ powerpc-linux-gcc -O2 -Wall -Werror -Wfatal-errors -c -o /dev/null namespace.i
```

**Comment by lei137** [comment]
> For what it's worth, this breaks building the Linux kernel for 32-bit powerpc for me because [the kernel uses `r2` as a global register variable for `current`](https://elixir.bootlin.com/linux/v6.11.4/source/arch/powerpc/include/asm/current.h#L33).
> 
> ```
> $ make -skj"$(nproc)" ARCH=powerpc CROSS_COMPILE=powerpc-linux-gnu- LLVM=1 LLVM_IAS=0 mrproper pmac32_defconfig ipc/namespace.o
> fatal error: error in backend: Trying to obtain a reserved register "r2".
> ...
> ```
> 
> While this seems expected given the change, just in case, I ran this through `cvise`, which spits out:
> 
> ```c
> register struct task_struct *current asm("r2");
> struct task_struct {
>   struct cred *cred;
> };
> struct cred {
>   int euid;
> } inc_ucount(int);
> int *create_ipc_ns() {
>   inc_ucount(({ ({ current->cred; })->euid; }));
>   return (void *)8;
> }
> ```
> 
> which works with `clang` immediately prior to this change and GCC:
> 
> ```
> $ clang --version | head -1
> ClangBuiltLinux clang version 20.0.0git (https://github.com/llvm/llvm-project.git 06d192925d3510d0af6c10e6f64f6deabf66b75f)
> 
> $ clang --target=powerpc-linux-gnu -Wall -Werror -Wfatal-errors -c -o /dev/null namespace.i
> fatal error: error in backend: Trying to obtain a reserved register "r2".
> ...
> ```
> 
> ```
> $ clang --version | head -1
> ClangBuiltLinux clang version 20.0.0git (https://github.com/llvm/llvm-project.git e57548387000071562f44bfd66644480c8e6542d)
> 
> $ clang --target=powerpc-linux-gnu -Wall -Werror -Wfatal-errors -c -o /dev/null namespace.i
> ```
> 
> ```
> $ powerpc-linux-gcc --version | head -1
> powerpc-linux-gcc (GCC) 14.2.0
> 
> $ powerpc-linux-gcc -O2 -Wall -Werror -Wfatal-errors -c -o /dev/null namespace.i
> ```

Thanks for reporting this.  I will revert this change to unblock you and investigate further.

**Comment by lei137** [comment]
@nathanchance I took another look at the docs and there is no documented restrictions on what register can be used for this.  I updated the patch to reflect what was originally there for `r2`.  Can youn please give it a try?
https://github.com/llvm/llvm-project/pull/113482

Thanks!

**Pull request merged**
