### PR TITLE
[libunwind] Fix an inconsistent indentation (NFC)

### PR DESCRIPTION
**Pull request by aheejin**
A fix was tried in
https://github.com/llvm/llvm-project/commit/d080b5f1737b4040aa74a5614ae01338f28cd714 but the line is still inconsistent with the surrounding code.

### CODE REVIEW

**Review by mstorsjo — APPROVED** [review]
LGTM, thanks! (I have no idea how I botched that previous fix commit...)

**Review by arichardson — COMMENTED** [review]
Making it consistent is good, but it sounds like we should update the .clang-format config file or reformat this whole file to not be indented.

**Comment by arichardson** [comment]
> > Making it consistent is good, but it sounds like we should update the .clang-format config file or reformat this whole file to not be indented.
> 
> I'm not sure what the clang-format policy for libunwind is. How about landing this as is and updating `.clang-format` or excluding this file as a follow-up, in a way you and other libunwind maintainers think is appropriate?

Sorry if that wasn't obvious, I think your change should be merged. I just noticed that the current style does not match the configured one which should eventually be fixed as a follow up change.

**Review by arichardson — APPROVED** [review]

**Comment by ldionne** [comment]
LGTM, the AIX failure seems unrelated.

**Pull request merged**
