### PR TITLE
Fix sanitize problem.

### PR DESCRIPTION
**Pull request by jyu2-git**
Currently isMapType could return OpenMPMapModifierKind.

The change is to return OpenMPMapTypeKind only, if it is not MapType Kind OMPC_MAP_unknown is returned.

### CODE REVIEW

**Comment by alexey-bataev** [comment]
A test?

**Comment by alexey-bataev** [comment]
> > A test?
> 
> I don't really know how to test this, as I don't know how to reproduce the problem. Any suggestion?

What is the problem?

**Comment by jyu2-git** [comment]
> > > A test?
> > 
> > 
> > I don't really know how to test this, as I don't know how to reproduce the problem. Any suggestion?
> 
> What is the problem?

    https://lab.llvm.org/buildbot/#/builders/85/builds/23835

**Review by alexey-bataev — APPROVED** [review]
LG

**Comment by vitalybuka** [comment]
Please include this fix into re-land.

**Pull request merged**
