### PR TITLE
[InstCombine] Fix missing argument typo in `InstCombinerImpl::foldICmpShlConstant`

### LINKED ISSUE #94897: wrong code at -O1 and above on x86_64-linux-gnu
This appears to be a recent regression as it doesn't reproduce with 18.1.0 and earlier.

Compiler Explorer: https://godbolt.org/z/T9b4a7z3v

```console
% clangtk -v
clang version 19.0.0git (https://github.com/llvm/llvm-project.git 338cbfef03e0ab58d7b52f3301928c58b194a1b4)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /local/suz-local/software/local/clang-trunk/bin
Build config: +assertions
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/10
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Found candidate GCC installation: /usr/lib/gcc/x86_64-linux-gnu/9
Selected GCC installation: /usr/lib/gcc/x86_64-linux-gnu/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
% 
% clangtk -O0 small.c; ./a.out
% clangtk -O1 small.c
% ./a.out
Aborted
% cat small.c
int a;
char b(char c, char d) { return c - d; }
int main() {
  int e;
  for (a = -10; a > -11; a--)
    e = b(a, -1);
  if (e > -2)
    __builtin_abort();
  return 0;
}
```

### PR DESCRIPTION
**Pull request by dtcxzyw**
Closes #94897.

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
I didn't even notice that https://github.com/llvm/llvm-project/pull/92773 also made changes to flag preservation -- it seems like that part of the PR was untested? At least I don't see any trunc nuw/nsw in the tests. Can you please add coverage?

**Comment by dtcxzyw** [comment]
> I didn't even notice that #92773 also made changes to flag preservation -- it seems like that part of the PR was untested? At least I don't see any trunc nuw/nsw in the tests. Can you please add coverage?

Done.

**Comment by goldsteinn** [comment]
LGTM

**Review by nikic — APPROVED** [review]
LGTM

**Pull request merged**
