### PR TITLE
[lldb][AIX] XCOFF clang-format and other minor changes

### PR DESCRIPTION
**Pull request by DhruvSrivastavaX**
This PR is in reference to porting LLDB on AIX.

Link to discussions on llvm discourse and github:

1. https://discourse.llvm.org/t/port-lldb-to-ibm-aix/80640
2. https://github.com/llvm/llvm-project/issues/101657
3. The complete changes for porting are present in this draft PR:
4. https://github.com/llvm/llvm-project/pull/102601

Added XCOFF Object File Header Parsing for AIX.
This PR is an incremental PR to the base:
https://github.com/llvm/llvm-project/pull/111814
Details about XCOFF file format on AIX: [XCOFF](https://www.ibm.com/docs/en/aix/7.3?topic=formats-xcoff-object-file-format)

Added some clang-format and other minor changes, Ref: https://github.com/llvm/llvm-project/pull/116338#discussion_r1884069848

Review Request: @DavidSpickett

### CODE REVIEW

**Comment by DavidSpickett** [comment]
Please rebase this so it is just one commit to merge into `main`, and limit it just to the clang-format changes.

(if I implied it should include the new comments, my apologies)

**Comment by DhruvSrivastavaX** [comment]
Not a problem, I probably just got a bit excited 😛 
Fixed it now. 
For the rebase, I am unable to select the update with rebase option for some reason(??)

**Comment by DhruvSrivastavaX** [comment]
Let me give it a try manually

**Comment by DavidSpickett** [comment]
@DhruvSrivastavaX I realised I can do the squash when I merge it. I was confused by seeing so many commits here but the final changes are correct anyway.

**Comment by DhruvSrivastavaX** [comment]
Yes, I was trying to resolve a couple of conflicts in a better way, since the branch had diverged quite some time back. 
 Thanks for the squash and merge!

**Pull request merged**
