### PR TITLE
[SelectOpt] Support BinOps with SExt operands.

### PR DESCRIPTION
**Pull request by fhahn**
Building on top of https://github.com/llvm/llvm-project/pull/115489
extend support for binops with SExt operand.

### CODE REVIEW

**Comment by igogo-x86** [comment]
Looks good; the only question is whether we want to add it before or after [#115745](https://github.com/llvm/llvm-project/pull/115745) (assuming it gets accepted)

**Comment by sapostolakis** [comment]
Same as #115489, LGTM as well.

**Review by sapostolakis — APPROVED** [review]

**Comment by igogo-x86** [comment]
Ping

**Comment by fhahn** [comment]
Updated on top of current `main`

**Review by igogo-x86 — APPROVED** [review]

**Pull request merged**
