### PR TITLE
[mlir][tools] Introduce tblgen-to-irdl tool

### PR DESCRIPTION
**Pull request by Groverkss**
RFC: https://discourse.llvm.org/t/rfc-tblgen-to-irdl-tool/73578

### CODE REVIEW

**Comment by joker-eph** [comment]
Is there some context to read on this somewhere? A discourse thread?

**Comment by Groverkss** [comment]
> Is there some context to read on this somewhere? A discourse thread?

Sorry, was just moving it from phab. I will add more context it a bit.

**Comment by joker-eph** [comment]
Why a separate binary and not just another backend for mlir-tblgen?

**Comment by Groverkss** [comment]
> Why a separate binary and not just another backend for mlir-tblgen?

The reason I did not make this a backend for mlir-tblgen is that this would add a dependency of MLIRIR on mlir-tblgen. I’m not sure how this dependency affects things as I expect the MLIRIR definitions to be generated by mlir-tblgen and mlir-tblgen would start depending on those definitions.

The same question was asked on the RFC as well :) (https://discourse.llvm.org/t/rfc-tblgen-to-irdl-tool/73578/8)

**Comment by joker-eph** [comment]
> The reason I did not make this a backend for mlir-tblgen is that this would add a dependency of MLIRIR on mlir-tblgen

This PR does not modify lib/IR/... ; can you clarify where is this dependency coming from?

**Comment by Groverkss** [comment]
> > The reason I did not make this a backend for mlir-tblgen is that this would add a dependency of MLIRIR on mlir-tblgen
> 
> This PR does not modify lib/IR/... ; can you clarify where is this dependency coming from?

oops. I meant the other way around, mlir-tblgen would start depending on MLIRIR, since to generate IRDL, we use IR Builders.

**Comment by Groverkss** [comment]
@joker-eph @Mogball gentle ping :)

**Review by Mogball — APPROVED** [review]
nice

**Pull request merged**
