### PR TITLE
[clangd] Handle lambda scopes inside Node::getDeclContext()

### PR DESCRIPTION
**Pull request by zyn0217**
We used to consider the `DeclContext` for selection nodes inside a lambda as the enclosing scope of the lambda expression, rather than the lambda itself.

For example,

```cpp
void foo();
auto lambda = [] {
  return ^foo();
};
```

where `N` is the selection node for the expression `foo()`, `N.getDeclContext()` returns the `TranslationUnitDecl` previously, which IMO is wrong, since the method `operator()` of the lambda is closer.

Incidentally, this fixes a glitch in add-using-declaration tweaks. (Thanks @HighCommander4 for the test case.)

### CODE REVIEW

**Comment by zyn0217** [comment]
Ping. And Happy New Year 2024!

**Review by HighCommander4 — APPROVED** [review]
Thanks, the change looks good to me!

I went through the existing callers of `Node::getDeclContext()`, and I was able to construct a test case where the patch actually changes behaviour (in a good way):

```c++
namespace NS {
void unrelated();
void foo();
}

auto L = [] {
  using NS::unrelated;
  NS::foo();
};
```

Here, if the "add using-declaration" code action is invoked on `NS::foo`, before this patch the result is:

```c++
namespace NS {
void unrelated();
void foo();
}

using NS::foo;

auto L = [] {
  using NS::unrelated;
  foo();
};
```

but after this patch the result is:

```c++
namespace NS {
void unrelated();
void foo();
}

auto L = [] {
  using NS::foo;
  using NS::unrelated;
  foo();
};
```

Let's add this test case to `AddUsingTests` while we're at it.

**Comment by HighCommander4** [comment]
> Happy New Year 2024!

You too!

**Comment by zyn0217** [comment]
Sorry for being silent for a few days, I've been a bit occupied recently and hopefully I could get back to the heuristic patch for templates soon.

> I went through the existing callers of Node::getDeclContext(), and I was able to construct a test case where the patch actually changes behaviour (in a good way):

Thank you for the exploration! I've added the test case, although it appears a bit odd:
```cpp
auto L = [] {
  using NS::foo;using NS::unrelated; // Shouldn't it be placed on a new line?
  foo();
};)cpp
```

However, I've seen a similar tweaking style (e.g. `namespace {using one::two::ff;`) around these tests, so maybe this is intended?

**Comment by zyn0217** [comment]
(I'll land it once the CI turns green.)

**Comment by HighCommander4** [comment]
> Shouldn't it be placed on a new line?

I think what may be happening here is that the refactorings try to avoid duplicating the work of the formatter, and just generate syntactically valid code that the formatter will then format according to the codebase's clang-format settings.

**Comment by zyn0217** [comment]
The CI failure on windows seems irrelevant, so I'm landing it anyway.

```
FAILED: tools/clang/tools/extra/clangd/CompletionModel.h tools/clang/tools/extra/clangd/CompletionModel.cpp
cmd.exe /C "cd /D C:\ws\src\build\tools\clang\tools\extra\clangd && C:\Python39\python.exe C:/ws/src/clang-tools-extra/clangd/quality/CompletionModelCodegen.py --model C:/ws/src/clang-tools-extra/clangd/quality/model --output_dir C:/ws/src/build/tools/clang/tools/extra/clangd --filename CompletionModel --cpp_class clang::clangd::Example"
C:\Python39\python.exe: can't open file 'C:\ws\src\clang-tools-extra\clangd\quality\CompletionModelCodegen.py': [Errno 22] Invalid argument
```

**Pull request merged**
