### PR TITLE
[WebAssembly] Disable multivalue emission temporarily

### PR DESCRIPTION
**Pull request by aheejin**
We plan to enable multivalue in the features section soon (#80923) for other reasons, such as the feature having been standardized for many years and other features being developed (e.g. EH) depending on it. This is separate from enabling Clang experimental multivalue ABI (`-Xclang -target-abi -Xclang experimental-mv`), but it turned out we generate some multivalue code in the backend as well if it is enabled in the features section.

Given that our backend multivalue generation still has not been much used nor tested, and enabling the feature in the features section can be a separate decision from how much multialue (including none) we decide to generate for now, I'd like to temporarily disable the actual generation of multivalue in our backend. To do that, this adds an internal flag `-wasm-emit-multivalue` that defaults to false. All our existing multivalue tests can use this to test multivalue code. This flag can be removed later when we are confident the multivalue generation is well tested.

### CODE REVIEW

**Review by tlively — APPROVED** [review]
Just to make sure I understand: we will still emit `multivalue` into the target features section if `-mmultivalue` is passed, but that will no longer affect codegen at all unless the new temporary flag is also passed?

**Comment by aheejin** [comment]
Correct.

**Comment by tlively** [comment]
Sounds good!

**Comment by TerrorJack** [comment]
one small input from downstream user: the ghc wasm backend distributes its own wasi-sdk fork based on llvm trunk and we do enable multi-value by default, including the experimental mv abi in c, in the hope of uncovering more bugs for the sake of upstream as well as rest of the wasm ecosystem. other than #71124, multi value as well as the new abi hasn't caused us other trouble so far.

this patch looks easy enough to workaround in our downstream builds so we can continue to test against the mv abi without needing to figure out how to pass that flag all the way up from the clang driver, etc. still, i'm rather surprised such a significant change was proposed and merged in such a short timeline, with absolutely no community notice or grace period :/

**Comment by tlively** [comment]
@aheejin, if we revert this commit to avoid disrupting downstream users, do we have a backup plan that would allow us to make progress on new EH?

**Comment by aheejin** [comment]
@TerrorJack Oh, I wasn't aware this feature had active users, and thought this as mainly an internal issue. But good to know that you use it, and sorry for the inconvenience.

@tlively It is a little unclear to me how we define disruptions. What we caused in users like @TerrorJack's workflow can count as disruptions, but if we enable multivalue (either by default or at least when Wasm EH is used) and that reveals some untested parts in the toolchain, that might count as potential disruptions as well. 

If I run Emscripten tests with multivalue enabled, currently all Emscripten EH tests (or anything that use `invoke`s) fail, which is a problem if we enable multivalue by default but may be fine if we enable it only for Wasm EH. `invoke` failure itself can be probably fixed with a little effort. I also have 10+ more failures (whose failing reasons may or may not be grouped into a few) in Emscripten test suite that I have yet to investigate. So yeah, the backup plan can be, reverting this, investigating the current failures and fix them ;) which I hoped not to be blocked on. But maybe that's a better way in the long run?

I'll then revert this patch for now and investigate a little more on the failures.

**Comment by tlively** [comment]
@TerrorJack, is the multivalue-enabled wasi-sdk you distribute used in production or is it only meant for finding toolchain bugs?

**Comment by TerrorJack** [comment]
@tlively it's used in production and we ship it to ghc wasm backend's end users.

**Comment by dschuff** [comment]
For this use case we could make the experimental MV ABI flag also enable `wasm-emit-multivalue`? Otherwise the ABI flag wouldn't be able to do anything anyway. We could maybe also, instead of making multivalue-emission default-off in LLVM, make it default-on in LLVM but make clang disable it by default? That would eliminate disruption to non-clang LLVM users (although such users would then still be disrupted by needing to enable MV if they needed to use EH... but maybe any EH users are going to be disrupted one way or another anyway...).

**Comment by aheejin** [comment]
> I'll then revert this patch for now and investigate a little more on the failures.

Turned out I only reverted this on my fork.. Reverted it in upstream now.

**Pull request merged**
