### PR TITLE
[X86][AMX] Check also AMX register live out for copy lowering

### PR DESCRIPTION
**Pull request by phoebewang**
Another bug fix for #83628.

### CODE REVIEW

**Comment by phoebewang** [comment]
Ping?

**Review by RKSimon — APPROVED** [review]

**Comment by nikic** [comment]
This causes a large compile-time regression: http://llvm-compile-time-tracker.com/compare.php?from=875e91131847e3133d414c11c8ad721b52a287ee&to=8aa33f16e91d8f15037330620c1479555278dafe&stat=instructions:u I think this is basically the same regression as the original implementation of https://github.com/llvm/llvm-project/pull/83628, because the LiveRegUnits usage is no longer guarded.

I'd recommend you to just revert the original PR and forget about it. This is typical fallout from an AtariDreams PR.

**Comment by phoebewang** [comment]
> This causes a large compile-time regression: http://llvm-compile-time-tracker.com/compare.php?from=875e91131847e3133d414c11c8ad721b52a287ee&to=8aa33f16e91d8f15037330620c1479555278dafe&stat=instructions:u I think this is basically the same regression as the original implementation of #83628, because the LiveRegUnits usage is no longer guarded.

Oh, it's unfortunate.. I was thinking `stepBackward` was the culprit, but seems it is `addLiveOuts`.
 
> I'd recommend you to just revert the original PR and forget about it. This is typical fallout from an AtariDreams PR.

Unfortunately, we need it due to a sideeffect I mentioned in https://github.com/llvm/llvm-project/pull/83628#issuecomment-2067619733

I think a short term solution is to check `hasAMXTILE()` at the beginning. It would appears just well for these tests because I assume they won't enable AMX features but it takes no effect when compiling for targets have this feature.

For long term solution, we do need a one time analysis for all passes. I like the @aengelke 's ideas in #92910 and want to this to be addressed together.

@nikic What do you think?

**Comment by nikic** [comment]
> I think a short term solution is to check `hasAMXTILE()` at the beginning. It would appears just well for these tests because I assume they won't enable AMX features but it takes no effect when compiling for targets have this feature.

This is fine, though maybe it would be better to copy the register check from X86FastPreTileConfig as well? Otherwise it may affect `-march=native` builds even though there is no AMX use.

> For long term solution, we do need a one time analysis for all passes. I like @aengelke 's ideas in #92910 and want this to be addressed together.
> 
> @nikic What do you think?

Sounds good!

**Comment by phoebewang** [comment]
> This is fine, though maybe it would be better to copy the register check from X86FastPreTileConfig as well? Otherwise it may affect `-march=native` builds even though there is no AMX use.

Think it again, maybe the way in #94358 is better than in X86FastPreTileConfig.

**Pull request merged**
