### PR TITLE
[MLIR][LLVM] Fix recursive DI type export memory leak

### PR DESCRIPTION
**Pull request by zyx-billy**
Followup to discussion https://github.com/llvm/llvm-project/pull/87295#discussion_r1556016667.

The export cache should not cache temporary nodes.

### CODE REVIEW

**Comment by Dinistro** [comment]
Can we ensure that get's landed soonish? While I understand the concern for about how to test this, it is probably better to land this and ship a test as a followup, given that this breaks production flows.

**Review by gysit — APPROVED** [review]
LGTM!

I think it makes sense to land this soonish since it fixes an upstream bug.

**Comment by zyx-billy** [comment]
Sounds good. Let me fix the failures and land this then.

**Comment by zyx-billy** [comment]
OK turns out the test isn't too hard. Just had to make the previous nested recursive-decl test also use the nested decl again outside, which will die if it was cached to a temporary.

**Comment by gysit** [comment]
Nice thanks!

**Pull request merged**
