### PR TITLE
[CSKY] Don't emit `__multi3` on 32-bit CSKY

### LINKED ISSUE #68971: [CSKY] segmentation fault in `__multi3`
I have written a toolchain for `csky` in `Rust` at https://github.com/rust-lang/rust/pull/113658 before.

However, when I run a simple Rust program with u128, like this
```
fn main() {
    let a = 0x12345678876543219876543223456789_u128;
    println!("{a}");
}
```
I can compile the program successfully. However, I got a segmentation fault when I run it. It seems that `-mdouble-float` is not enabled. So can anyone will help to add this feature? or guide me add it?

(I'm not sure if I'm right about the above Issue, if anyone have any idea, please fell free to tell me. Thanks!)

---

@benshi001 @zixuan-wu I noticed that you two provide many commits to `csky`, so I want to know if you can give me some advice? Thanks. 

Besides, contact to me If I could add your WeChat. My email is mingyang_ge@163.com . Thanks!

### PR DESCRIPTION
**Pull request by Dirreke**
Fix #68971
According to #21245 , disable `__multi3` and other buitin functions which are not available in 32-bit target.

### CODE REVIEW

**Comment by Dirreke** [comment]
@rengolin @DimitryAndric 
Could you review it because it's similar to #21245 ?

**Comment by DimitryAndric** [comment]
This should be fine, but it needs a test, similar to `llvm/test/CodeGen/ARM/umulo-128-legalisation-lowering.ll`. (I don't know much about CSKY, but I assume that test case can mostly be copied except for the generated assembly code.)

**Comment by Dirreke** [comment]
> This should be fine, but it needs a test, similar to `llvm/test/CodeGen/ARM/umulo-128-legalisation-lowering.ll`. (I don't know much about CSKY, but I assume that test case can mostly be copied except for the generated assembly code.)

Thanks! After some tests, I think #68971 is different from #21245 . I can not simply disable `UINTTOFP_I128_FXX` like `__multi3` easily.

When program call the `u128` related builtin functions like `__multi3` and `__floattidf` on `CSKY`, the value of the parameters will be passed to the function, but the function will regard it as an address. It result a `SIGSEGV`.

I have no idea about how to fix it. Do you have any advice?

**Comment by Dirreke** [comment]
there's nothing to do. It's error in codegen of rust. Thank all of you2

**Pull request closed without merging**
