### PR TITLE
[LVI] Handle range attributes

### PR DESCRIPTION
**Pull request by andjo403**
This adds handling of range attribute for return values of Call and Invoke in getFromRangeMetadata and handling of argument with range attribute in solveBlockValueNonLocal.
There is one additional check of the range metadata at line 1120 in getValueFromSimpleICmpCondition that is not covered in this PR as after https://github.com/llvm/llvm-project/pull/75311 there is no test that cover that check any more and I have not been able to create a test that trigger that code.

### CODE REVIEW

**Comment by andjo403** [comment]
not sure why the formating failed had run "git clang-format HEAD~1"

**Review by dtcxzyw — APPROVED** [review]
LGTM.

**Review by nikic — APPROVED** [review]

**Comment by andjo403** [comment]
I need help merging as I have not permission.

**Comment by dtcxzyw** [comment]
> I need help merging as I have not permission.

Could you please update the PR description?

**Comment by andjo403** [comment]
I do not understand what you want me to update?

**Comment by andjo403** [comment]
@dtcxzyw have updated the first message in the PR with more info not sure it was what you wanted.

**Comment by andjo403** [comment]
ping @dtcxzyw

**Pull request merged**
