### PR TITLE
[flang][Lower] Emit exiting branches from within constructs

### PR DESCRIPTION
**Pull request by kparzysz**
When lowering IfConstruct, CaseConstruct, and SelectTypeConstruct, emit branches that exit the construct in each block that is still unterminated after the FIR has been generated in it.

The same thing may be needed for SelectRankConstruct, once it's supported.

This eliminates the need for inserting branches in `genFIR(Evaluation)`.

Follow-up to PR https://github.com/llvm/llvm-project/pull/91614.

### CODE REVIEW

**Comment by vdonaldson** [comment]
@kparzysz Thanks for working on this issue.

1. Do you have a test that illustrates the problem? The [91526](https://github.com/llvm/llvm-project/issues/91526) test case looks ok after your prior PR.
3. I'm seeing some failures with this change, such as for the test case below.
4. Are you aware of the `isIntermediateConstructStmt` Evaluation utility? That might make the extra `collectFinalEvaluations` traversal unnecessary. That would also provide a way to treat the last block of a sequence different than intermediate blocks, if that contributes to the problem below.
5. You are deleting not only the intermediate unstructured branch code, but also the degenerate construct block code. Accounting for degenerate code blocks is one complication with this functionality, although I don't immediately see a problem with that in this PR. Transitions between, and various nesting instances of  structured and unstructured code sequences are another complication.
6. New line 3040 looks like it may be dead code.

Test - Expected output `1111`, not `1101`.
```
subroutine s(j, k)
    goto (11, 22, 33) j-3  ! computed goto - an expression outside [1,3] is a nop
    if (j == 2) goto 22
    if (j == 1) goto 11
    k = k + 1
11  k = k + 10
22  k = k + 100
33  k = k + 1000
end

program p
  integer :: n = 0
  call s(0, n)
  print*, n
end
```

**Comment by Leporacanthicus** [comment]
Nice, this solves the issue I was having with OpenMP and `if something then <openmp loop here> else stop`.

Thanks for the work on this.

**Comment by kparzysz** [comment]
> 1. Do you have a test that illustrates the problem? The [91526](https://github.com/llvm/llvm-project/issues/91526) test case looks ok after your prior PR.

That PR had two testcases in the comments that still failed, which made me think that the problem has more to do with how we lower constructs, not specifically with OpenMP/OpenACC directives.  The goal here was to replace that patch with something that's better grounded in self-evident principles.

Thanks for the pointer about `isIntermediateConstructStmt`, and the new testcase.

**Comment by kparzysz** [comment]
The previous fix failed for unstructured flow because it assumed that every evaluation that ends a block also exits the construct. 
The updated code recognizes evaluations that end a block (within a construct) because their lexical successor is a target of some branch.

However, I think this can be fixed in a more elegant way.  Below is the PFT for the most recent problematic subroutine:
```
1 Subroutine s: subroutine s(j, k)
  1 ComputedGotoStmt! -> 9: goto(11, 22, 33) j-3
  <<IfConstruct!>> -> 10
    2 ^IfStmt [negate] -> 10: if(j == 2) goto 22
    <<IfConstruct>> -> 9
      5 ^IfStmt [negate] -> 9: if(j == 1) goto 11
      8 ^AssignmentStmt: k = k + 1
      7 EndIfStmt
    <<End IfConstruct>>
    9 ^AssignmentStmt!: 11 k = k + 10
    4 EndIfStmt
  <<End IfConstruct!>>
  10 ^AssignmentStmt: 22 k = k + 100
  11 ^AssignmentStmt: 33 k = k + 1000
  12 EndSubroutineStmt: end
End Subroutine s
```
The outermost `IfConstruct` has a branch going from outside of it (the computed goto), to the assignment at index 9.  If this was a Fortran program, this would not be allowed, and this additional patch would not have been necessary.

I think that a better fix would be to avoid creating such constructs in the PFT, if they didn't exist in the source.  What do you think?

**Comment by vdonaldson** [comment]
I believe the issue here is that individual directives sometimes act like action statements, sometimes like construct statements, and sometimes like constructs. The "simple2" test case can be resolved by treating the `OpenMPConstruct` directive like a construct, and the `OmpEndLoopDirective` directive like a construct statement, possibly with the following change.
 
One alternative to the first diff group below would be to instead add `OmpEndLoopDirective` to the `isExecutableDirective` group. Other variants might also be possible.

There may or may not be additional directive cases that should also be managed with similar changes. OpenMP and OpenACC directives are already given special treatment in various places. I think that special treatment should be extended to handle problems such as this one.

```
diff --git a/flang/lib/Lower/PFTBuilder.cpp b/flang/lib/Lower/PFTBuilder.cpp
index f196b9c5a0cb..e11329010cb9 100644
--- a/flang/lib/Lower/PFTBuilder.cpp
+++ b/flang/lib/Lower/PFTBuilder.cpp
@@ -467,7 +467,9 @@ private:
     evaluationListStack.back()->emplace_back(std::move(eval));
     lower::pft::Evaluation *p = &evaluationListStack.back()->back();
     if (p->isActionStmt() || p->isConstructStmt() || p->isEndStmt() ||
-        p->isExecutableDirective()) {
+        p->isExecutableDirective() ||
+        p->isA<Fortran::parser::OmpEndLoopDirective>()) {
+
       if (lastLexicalEvaluation) {
         lastLexicalEvaluation->lexicalSuccessor = p;
         p->printIndex = lastLexicalEvaluation->printIndex + 1;
@@ -1024,6 +1026,9 @@ private:
           },
           [&](const parser::WhereConstruct &) { setConstructExit(eval); },

+          // Directives - set (unstructured) directive exit targets
+          [&](const parser::OpenMPConstruct &) { setConstructExit(eval); },
+
           // Default - Common analysis for IO statements; otherwise nop.
           [&](const auto &stmt) {
             using A = std::decay_t<decltype(stmt)>;

```

**Comment by kparzysz** [comment]
> The "simple2" test case can be resolved by treating the `OpenMPConstruct` directive like a construct, and the `OmpEndLoopDirective` directive like a construct statement, possibly with the following change.

This change alone causes 31 tests to fail in check-flang.

**Review by vdonaldson — APPROVED** [review]

**Pull request merged**
