### PR TITLE
[llvm-driver] Fix usage of `InitLLVM` on Windows

### PR DESCRIPTION
**Pull request by aganea**
Previously, some tools such as `clang` or `lld` which require strict order for certain command-line options, such as `clang -cc1` or `lld -flavor`, would not longer work on Windows, when these tools were linked as part of `llvm-driver`. This was caused by `InitLLVM` which was part of the `*_main()` function of these tools, which in turn calls `windows::GetCommandLineArguments`. That function completly replaces argc/argv by new UTF-8 contents, so any ajustements to argc/argv made by `llvm-driver` prior to calling these tools was reset.

`InitLLVM` is now called by the `llvm-driver`. Any tool that participates in (or is part of) the `llvm-driver` doesn't call `InitLLVM` anymore.

### CODE REVIEW

**Review by compnerd — APPROVED** [review]

**Review by abhina-sree — APPROVED** [review]
LGTM

**Comment by MaskRay** [comment]
I hope that we do not add `UsageCount` to allow repeated uses of `InitLLVM`. Can a macro guard be used instead?

**Comment by aganea** [comment]
> I hope that we do not add `UsageCount` to allow repeated uses of `InitLLVM`. Can a macro guard be used instead?

I can also remove usages of ˋInitLLVM` in all the tools embedded by ˋllvm-driver` and only keep it in the topmost ˋmain()`.

**Comment by aganea** [comment]
@MaskRay Can you please take another look?

**Comment by llvm-beanz** [comment]
@aganea, this ends up being a nice way to collapse down a tiny bit of shared tool boilerplate. Thank you!

This LGTM, but let's make sure @MaskRay is happy too.

**Comment by MaskRay** [comment]
> InitLLVM which was part of the main() function of these tools

`*_main` functions?

**Review by MaskRay — APPROVED** [review]

**Comment by DimitryAndric** [comment]
Maybe I'm doing something wrong, but after this commit (and its merge to 18.x) I don't see to get stack traces from clang anymore after assertions?  How is this supposed to work?

**Comment by jrtc27** [comment]
llvm-driver-template.cpp.in is what should be generating the real main for Clang (and call clang_main), and that was patched in this commit.

**Comment by DimitryAndric** [comment]
Ah that was my error, I hadn't used the regenerated `*-driver.cpp` files. These indeed should contain the `InitLLVM` call.

**Pull request merged**
