### PR TITLE
Reformat whitespace in dependent dialects codegen

### PR DESCRIPTION
**Pull request by mlevesquedion**
The generated code for dependent dialects is awkwardly formatted, making the code harder to read. This change reformats the whitespace to align code in its context and avoid unnecessary empty lines.

Also included are some typo fixes.

Below are examples of the codegen for a dialect before and after the change.

Before:

```
GPUDialect::GPUDialect(::mlir::MLIRContext *context)
    : ::mlir::Dialect(getDialectNamespace(), context, ::mlir::TypeID::get<GPUDialect>()) {

    getContext()->loadDialect<arith::ArithDialect>();

  initialize();
}
```

After:

```
GPUDialect::GPUDialect(::mlir::MLIRContext *context)
    : ::mlir::Dialect(getDialectNamespace(), context, ::mlir::TypeID::get<GPUDialect>()) {
  getContext()->loadDialect<arith::ArithDialect>();
  initialize();
}
```

Below are examples of the codegen for a pass before and after the change.

Before:

```
  /// Return the dialect that must be loaded in the context before this pass.
  void getDependentDialects(::mlir::DialectRegistry &registry) const override {

  registry.insert<func::FuncDialect>();

  registry.insert<tensor::TensorDialect>();

  registry.insert<tosa::TosaDialect>();

  }
```

After:

```
  /// Register the dialects that must be loaded in the context before this pass.
  void getDependentDialects(::mlir::DialectRegistry &registry) const override {
    registry.insert<func::FuncDialect>();
    registry.insert<tensor::TensorDialect>();
    registry.insert<tosa::TosaDialect>();
  }
```

### CODE REVIEW

**Comment by mlevesquedion** [comment]
I care about the formatting because I spend a fair bit of time reading generated code, and in general I've found the generated code to be quite readable.

I'm not sure what the best way to test this is, or even if this needs tests. I added some FileCheck tests, but these don't fully cover the formatting, and they may be brittle.

(This is my first time contributing.)

**Review by zero9178 — COMMENTED** [review]
Big fan of this change as an avid reader of TableGen generated code :slightly_smiling_face: 

One thing I am worried about are the tests. I don't think they provide a lot of benefits: They effectively only test whether the `insert` calls are one line after the other with no whitespace lines before or after and do not test indendation. 
At the same time they are probably prone to breakage if any future changes are done to the codegen of these methods.

I'd personally just remove the tests.

**Comment by mlevesquedion** [comment]
Thank you for taking the time to review! I removed the tests and resolved your other comment.

**Review by MaheshRavishankar — COMMENTED** [review]
I don't know this code path as well, but change seems ok to me.
But overall, maybe we should just call clang-format on the generated code if we can directly invoke the code from c++.

**Review by joker-eph — APPROVED** [review]

**Comment by mlevesquedion** [comment]
@MaheshRavishankar Good point. Another approach would be to generate the code as data structures and pretty print them. I don't know if either of these approaches is practical though. I think the change is valuable as it is, but I agree there would be room to look for a more complete solution.

@joker-eph Thank you for taking the time to review! I don't have write access to the repo, feel free to submit the change.

**Review by zero9178 — APPROVED** [review]

**Pull request merged**
