### PR TITLE
[Clang][CodeGen] Emit load of GEP after EmitMemberExpr

### LINKED ISSUE #110385: __builtin_dynamic_object_size() fails to return correct size depending on depth of flexible array
As seen in the Linux kernel:

- https://lore.kernel.org/all/202409170436.C3C6E7F7A@keescook/
- https://lore.kernel.org/all/CAGG=3QVWCQB-3sM=iwgTmX8zrU81H+F_A1icJwROvW_DSvsBeA@mail.gmail.com

we're having erroneous size reporting from `__builtin_dynamic_object_size()`, where the depth of dereference for the flexible array causes a 0 size report:

```c
https://godbolt.org/z/qohGd5xh1


#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

struct variable {
        int a;
        int b;
        int length;
        short array[] __attribute__((counted_by(length)));
};

struct bucket {
        int a;
        struct variable *growable;
        int b;
};

int main(int argc, char *argv[])
{
        struct bucket *p;
        struct variable *v;

        p = malloc(sizeof(*p));
        v = malloc(sizeof(*p->growable) + sizeof(*p->growable->array) * 32);
        v->length = 32;


        printf("%zu\n", __builtin_dynamic_object_size(v->array, 1));

        p->growable = v;
        printf("%zu\n", __builtin_dynamic_object_size(p->growable->array, 1));

        return 0;
}


GCC shows 64 64, but Clang shows 64 0.
```

cc @isanbard @bwendling

### PR DESCRIPTION
**Pull request by bwendling**
We were missing a load of the value after emitting the MemberExpr. This
was causing __builtin_dynamic_object_size to return 0 incorrectly.

Fixes: #110385
Signed-off-by: Bill Wendling <morbo@google.com>
Cc: Jan Hendrik Farr <kernel@jfarr.cc>
Cc: Kees Cook <kees@kernel.org>

### CODE REVIEW

**Comment by Cydox** [comment]
Fixes the kernel issue for me.

I closed #110437 in favor of this one

**Comment by Cydox** [comment]
Wait, this introduces a regression when the inner struct is directly nested without using a pointer like so:

Without this change the code below will return 64, with my fix it will also return 64, with this fix it will SEGFAULT.

```C
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

struct variable {
        int a;
        int b;
        int length;
        short array[] __attribute__((counted_by(length)));
};

struct bucket {
        int a;
        struct variable growable;
//        struct variable *growable;
//        int b;
};

int main(int argc, char *argv[])
{
        struct bucket *p;
        struct variable *v;

        p = malloc(sizeof(*p) + sizeof(*p->growable.array) * 32);
        p->growable.length = 32;


//        printf("%zu\n", __builtin_dynamic_object_size(v->array, 1));

//        p->growable = v;
        printf("%zu\n", __builtin_dynamic_object_size(p->growable.array, 1));

        return 0;
}
```

**Comment by Cydox** [comment]
Reopened my fix as #110497 and also adjusted the test to also check for the case of a nested struct without indirection.

**Review by efriedma-quic — COMMENTED** [review]
This is sort of the same comment I've made on other related patches... but I think the fundamental issue here is that StructAccessBase is skipping over CK_LValueToRValue casts.  Once you jump over such a cast, you're looking at expressions which are at a different level of indirection from the member access you care about.

If StructAccessBase just returns the cast itself, instead of trying to understand the value that's getting loaded, you shouldn't need a special case for MemberExpr.

**Comment by bwendling** [comment]
> This is sort of the same comment I've made on other related patches... but I think the fundamental issue here is that StructAccessBase is skipping over CK_LValueToRValue casts. Once you jump over such a cast, you're looking at expressions which are at a different level of indirection from the member access you care about.

I understand, but there are ~30 different types of implicit casts and it's hard to know which can be ignored and which shouldn't.

> If StructAccessBase just returns the cast itself, instead of trying to understand the value that's getting loaded, you shouldn't need a special case for MemberExpr.

I did an experiment and it has the same issue. If I return the LValueToRValue cast and run `EmitLValue` on it the 'load' is still missing.

In a separate PR, I wanted to create a MemberExpr based off of what the `StructAccessBase` returns, because all of the code to generate the correct access to that MemberExpr already exist, but you and Aaron had issues with that. I understand wanting to keep the AST in a sane state and not wanting to add nodes indiscriminately, but it's really limiting what can be done.

Here are two ways I'd like to handle this (in order of preference):

1. In CodeGen, when given and `Expr` in a `__builtin_dynamic_object_size` that has a FAM with `__counted_by`, I'd like to build a new `Expr` pointing to the *count* field and run that through the proper `Emit*()` method.
2. Convert a `__builtin_dynamic_object_size` with a FAM with `__counted_by` into the appropriate calculations in Sema.

For (1), building a new `Expr` is easier than emitting the "base" pointer to the structure and tacking on a reference to the count's `FieldDecl`, which has its own issues (like preventing us from loading the base pointer twice).

Option (2) isn't super awesome, because we lose the fact that the original expression was a `__builtin_dynamic_object_size` call. But maybe that's not important to keep around....

**Comment by efriedma-quic** [comment]
> If I return the LValueToRValue cast and run EmitLValue on it 

I'm surprised EmitLValue didn't error out on that. The result of an LValueToRValue cast is an rvalue.  Calling EmitPointerWithAlignment on it should work, I think.

> I understand, but there are ~30 different types of implicit casts and it's hard to know which can be ignored and which shouldn't.

The complexity here is, unfortunately, mostly unavoidable... maybe worth looking into some simplified classification of casts for common usage.

> Convert a __builtin_dynamic_object_size with a FAM with __counted_by into the appropriate calculations in Sema.

This might be reasonable.

> because we lose the fact that the original expression was a __builtin_dynamic_object_size call

If we went this route, probably we'd wrap the calculation in a dedicated node that contains both the original AST, and the lowered computation, or something like that.

**Comment by bwendling** [comment]
> > If I return the LValueToRValue cast and run EmitLValue on it
> 
> I'm surprised EmitLValue didn't error out on that. The result of an LValueToRValue cast is an rvalue. Calling EmitPointerWithAlignment on it should work, I think.
> 
> > I understand, but there are ~30 different types of implicit casts and it's hard to know which can be ignored and which shouldn't.
> 
> The complexity here is, unfortunately, mostly unavoidable... maybe worth looking into some simplified classification of casts for common usage.
> 
> > Convert a __builtin_dynamic_object_size with a FAM with __counted_by into the appropriate calculations in Sema.
> 
> This might be reasonable.
> 
> > because we lose the fact that the original expression was a __builtin_dynamic_object_size call
> 
> If we went this route, probably we'd wrap the calculation in a dedicated node that contains both the original AST, and the lowered computation, or something like that.

I went ahead and used the `EmitPointerWithAlignment` for all (it worked without needing special casing). I'll look into doing this in Sema as a potential cleanup.

**Comment by Cydox** [comment]
> I went ahead and used the `EmitPointerWithAlignment` for all (it worked without needing special casing). I'll look into doing this in Sema as a potential cleanup.

With that change now the compiler segfaults when compiling the example C file I posted above:


> ```c
> #include <stdio.h>
> #include <stdlib.h>
> #include <unistd.h>
> 
> struct variable {
>         int a;
>         int b;
>         int length;
>         short array[] __attribute__((counted_by(length)));
> };
> 
> struct bucket {
>         int a;
>         struct variable growable;
> //        struct variable *growable;
> //        int b;
> };
> 
> int main(int argc, char *argv[])
> {
>         struct bucket *p;
>         struct variable *v;
> 
>         p = malloc(sizeof(*p) + sizeof(*p->growable.array) * 32);
>         p->growable.length = 32;
> 
> 
> //        printf("%zu\n", __builtin_dynamic_object_size(v->array, 1));
> 
> //        p->growable = v;
>         printf("%zu\n", __builtin_dynamic_object_size(p->growable.array, 1));
> 
>         return 0;
> }
> ```

**Comment by bwendling** [comment]
I reverted my last commit. This leaves the original patch, which seems to work. @efriedma-quic, would you be okay with this patch while I work to improve the code in follow-up?

**Comment by Cydox** [comment]
> I reverted my last commit. This leaves the original patch, which seems to work. @efriedma-quic, would you be okay with this patch while I work to improve the code in follow-up?

The original (and current) patch in this PR still introduces a regression. So it should not be merged in my opinion.

Look at the following C file (`test.c`):
```C
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

struct variable {
        int a;
        int b;
        int length;
        short array[] __attribute__((counted_by(length)));
};

struct bucket {
        int a;
        struct variable growable;
};

int main(int argc, char *argv[])
{
        struct bucket *p;

        p = malloc(sizeof(*p) + sizeof(*p->growable.array) * 32);
        p->growable.length = 32;

        printf("%zu\n", __builtin_dynamic_object_size(p->growable.array, 1));

        return 0;
}
```

Compiling this file with clang 19.1.0 and running it:
```bash
$ clang --version
clang version 19.1.0 (Fedora 19.1.0-1.fc41)
Target: x86_64-redhat-linux-gnu
Thread model: posix
InstalledDir: /usr/bin
Configuration file: /etc/clang/x86_64-redhat-linux-gnu-clang.cfg

$ clang test.c

$ ./a.out
64
```
Correctly prints `64`.

But compiling and running it with the originial (and current) patch in this PR:
```bash
$ clang --version
clang version 20.0.0git (git@github.com:llvm/llvm-project.git 2de76472e0d1417b64da5aa2c1138eb365685d3a)
Target: x86_64-unknown-linux-gnu
Thread model: posix
InstalledDir: /home/jan/llvm-project/build2/bin

$ clang test.c

$ ./a.out
Segmentation fault (core dumped)
```

Will result in a binary that crashes with a segmentation fault.

---

My PR #110497 adds a test case for this scenario and does not have the same issue: https://github.com/Cydox/llvm-project/blob/15b69329a97706ada7d5e8cbeb76508aa55b418f/clang/test/CodeGen/attr-counted-by-pr110385.c#L61

**Comment by bwendling** [comment]
> > I reverted my last commit. This leaves the original patch, which seems to work. @efriedma-quic, would you be okay with this patch while I work to improve the code in follow-up?
> 
> The original (and current) patch in this PR still introduces a regression. So it should not be merged in my opinion.
> 
> Look at the following C file (`test.c`):
> 
> ```c
> #include <stdio.h>
> #include <stdlib.h>
> #include <unistd.h>
> 
> struct variable {
>         int a;
>         int b;
>         int length;
>         short array[] __attribute__((counted_by(length)));
> };
> 
> struct bucket {
>         int a;
>         struct variable growable;
> };
> 
> int main(int argc, char *argv[])
> {
>         struct bucket *p;
> 
>         p = malloc(sizeof(*p) + sizeof(*p->growable.array) * 32);
>         p->growable.length = 32;
> 
>         printf("%zu\n", __builtin_dynamic_object_size(p->growable.array, 1));
> 
>         return 0;
> }
> ```
> 
> Compiling this file with clang 19.1.0 and running it:
> 
> ```shell
> $ clang --version
> clang version 19.1.0 (Fedora 19.1.0-1.fc41)
> Target: x86_64-redhat-linux-gnu
> Thread model: posix
> InstalledDir: /usr/bin
> Configuration file: /etc/clang/x86_64-redhat-linux-gnu-clang.cfg
> 
> $ clang test.c
> 
> $ ./a.out
> 64
> ```
> 
> Correctly prints `64`.
> 
> But compiling and running it with the original (and current) patch in this PR:
> 
> ```shell
> $ clang --version
> clang version 20.0.0git (git@github.com:llvm/llvm-project.git 2de76472e0d1417b64da5aa2c1138eb365685d3a)
> Target: x86_64-unknown-linux-gnu
> Thread model: posix
> InstalledDir: /home/jan/llvm-project/build2/bin
> 
> $ clang test.c
> 
> $ ./a.out
> Segmentation fault (core dumped)
> ```
> 
> Will result in a binary that crashes with a segmentation fault.
> 
> My PR #110497 adds a test case for this scenario and does not have the same issue: https://github.com/Cydox/llvm-project/blob/15b69329a97706ada7d5e8cbeb76508aa55b418f/clang/test/CodeGen/attr-counted-by-pr110385.c#L61

This is what I get:

```
kiff ~/llvm/llvm-project (builtin_get_counted_by) $ cat > /tmp/y.c
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>

struct variable {
        int a;
        int b;
        int length;
        short array[] __attribute__((counted_by(length)));
};

struct bucket {
        int a;
        struct variable growable;
};

int main(int argc, char *argv[])
{
        struct bucket *p;

        p = malloc(sizeof(*p) + sizeof(*p->growable.array) * 32);
        p->growable.length = 32;

        printf("%zu\n", __builtin_dynamic_object_size(p->growable.array, 1));

        return 0;
}
kiff ~/llvm/llvm-project (builtin_get_counted_by) $ ./build.opt/bin/clang -O2 /tmp/y.c && ./a.out
64
```

**Comment by Cydox** [comment]
Interesting. You compiled with `-O2`, I compiled without optimization.
When I compile it with `-O2`, I now get `0`.

I've uploaded a gist with the disassembly generated with

```
clang -mllvm --x86-asm-syntax=intel -S test.c -o ./test-no-optimize.S
```
and
```
clang -O2 -mllvm --x86-asm-syntax=intel -S test.c -o ./test-optimize-O2.S
```

Can you do the same?

https://gist.github.com/Cydox/8b48a7d36dbcf6376d5a2d44afe5cf57

**Comment by Cydox** [comment]
@bwendling I think you accidentally compiled the wrong branch. Looks like that is in `builtin_get_counted_by`, but this PR is in `bdos-member-expr-error`

**Comment by bwendling** [comment]
> @bwendling I think you accidentally compiled the wrong branch. Looks like that is in `builtin_get_counted_by`, but this PR is in `bdos-member-expr-error`

Yeah, sorry about that.

**Comment by Cydox** [comment]
No worries

**Pull request closed without merging**
