### PR TITLE
Dont alter cold function alignment unless using Os

### PR DESCRIPTION
**Pull request by FlameTop**
This PR alters the behaviour of function alignment for functions marked as 'cold'. Currently functions marked with a ‘cold’ attribute are also set as optimize by size. Optimize by size alters the function alignment from default. This interferes with code replacement features on our targets. This PR allows cold functions to maintain their default alignment except when optimize by size is explicitly used.

### CODE REVIEW

**Comment by efriedma-quic** [comment]
This patch appears to do two things:

- Add a "default align" attribute, which instructions the backend to use some unspecified "default" alignment for the function in question.
- Tells the frontend to apply this attribute specifically to "cold" functions.

This is basically nonsense.  We already have a way to set alignment: it's the "align" attribute.  And there isn't any obvious reason to special-case "cold" functions.

> This interferes with code replacement features on our targets

Please take a step back and consider what makes sense to express the constraints in general, not what narrowly solves the problem on the current version of your codebase.

If there's an ABI constraint that requires a particular function alignment, clang should be explicitly marking it.  We already do this if you, for example, specify `-falign-functions=16` on the clang command-line.

**Comment by pogo59** [comment]
> We already have a way to set alignment: it's the "align" attribute.

Is clang aware of the target's default function alignment? I'd thought not, in which case deferring to LLVM (as this new attribute does) is correct. Happy to be corrected on this point.

> there isn't any obvious reason to special-case "cold" functions.

I'd thought that was clear. Cold implies opt-for-size, which implies align(1). We want cold not to imply align(1), directly or indirectly; but, if opt-for-size was requested explicitly, that should still imply align(1). The implied align(1) does interfere with a useful feature for PS4/PS5, and has for some time. If the tweak to the definition of "cold" should be specific to our targets, we can certainly do that.

**Comment by efriedma-quic** [comment]
> Is clang aware of the target's default function alignment?

No?  On x86, the "default" is set by the line `setPrefFunctionAlignment(Align(16));`.  Which, as the name suggests, is supposed to be a preference, not a mandatory minimum.  And it's subject to change in the future if we find that a different number is better on some targets, or for certain functions.

> > there isn't any obvious reason to special-case "cold" functions.
> 
> I'd thought that was clear. Cold implies opt-for-size, which implies align(1)

If there's a relevant ABI rule here, we want to mark it on all functions.  So if, for example, some optimization decides a function is cold, we get the same result.

> If the tweak to the definition of "cold" should be specific to our targets, we can certainly do that.

If there's some relevant ABI rule, clang should compute the required alignment explicitly, and explicitly mark functions with the required alignment.  If that's target-specific, that's fine.  Ideally, it should be controllable by a flag separate from the optimization level.

**Comment by pogo59** [comment]
I guess I'm a little confused still. Are you claiming that `cold` has a specified ABI effect? That if some pass decides a function is cold, that decision (correctly) affects its ABI? I'm not seeing any documentation to that effect, either on the clang attribute or the IR attribute. My admittedly aging copy of the psABI doesn't mention function alignment at all, either.

We're not inventing an ABI rule that `cold` functions are special and must have a specific alignment; we just want `cold` functions to have the same alignment as non-`cold` functions. (And if you specify `-Os` then that alignment changes to 1, for cold and non-cold functions alike.)

The only thing that makes `cold` functions special _in this implementation_ is that, as an implementation convenience, clang's `cold` attribute also sets `optsize` which has an effect that we are finding inconvenient. We just want `cold` not to have that particular effect. We played around with several different ways to make that happen, and this seemed the least intrusive.

I suppose another way to go at this would be for `-Os` or clang's `minsize` to add both `optsize` and align(1) to functions, and have LLVM's implementation of `optsize` stop implying align(1). This would make everything more orthogonal and disentangled, yes? And then clang's `cold` could set `optsize` without affecting alignment; if non-PS targets still wanted `cold` to mean align(1), we can set that as well. No new attributes, and that bit of code down in LLVM to compute alignment gets a wee bit cleaner. WDYT?

**Comment by efriedma-quic** [comment]
I'll try describing it a different way.

There are two kinds of alignment. "ABI alignment" is required for the code to function correctly (due to things like architecture constraints, reusing the low bit for member pointers, binary patching).  "Preferred alignment" is additional alignment added by the backend to try to improve performance (because, for example, the CPU you're targeting fetches instructions in aligned 16-byte chunks).

On x86, the "ABI alignment" is 1, unless a function is explicitly marked with an "align" attribute, in which case the "ABI alignment" is the marked alignment.

For the sake of performance, the backend increases the alignment of most functions.  But that's not contractual; it's just an implementation detail.  If your code is relying on the backend to produce some particular alignment without an "align" marking, that's a bug in your code; you're just getting lucky.  So the starting point is that all your code is semantically broken.

Given that as a starting point, it should be clear why you shouldn't be special-casing "cold" functions, and why you shouldn't be relying on the backend's "default" alignment.

**Comment by FlameTop** [comment]
@pogo59 I agree that stating the PS ABI has an explicit function alignment unless overridden does negate the need for a new attribute. I will re-work the code to remove the new attribute and instead enforce it for the PS ABI target.

**Comment by pogo59** [comment]
> Edit: Actually we still have the problem of when in LLVM not knowing if optimze-by-size got set on the cold funtion by it being cold or if Os was used.

Not sure I understand the question (sorry I missed this comment when it was made). The suggestion is that for our target, clang sets explicit alignment, so LLVM should not need to know where optsize came from. LLVM's handling of optsize will not reset an alignment that is already set. Is there a situation where the wrong thing still happens?

**Comment by FlameTop** [comment]
Closing this PR. I will redesign the change and re-submit.

**Pull request closed without merging**
