### PR TITLE
[libc++][test] Add missing <concepts> to is_always_lock_free test

### PR DESCRIPTION
**Pull request by StephanTLavavej**
There were a couple of problems with this test added by #99570:

* It was named `is_always_lock_free.cpp` instead of `is_always_lock_free.pass.cpp`.
  + Noticed because the MSVC STL test harness looks for `MEOW.pass.cpp` specifically.
* It was using `std::same_as` without including `<concepts>`.
  + Noticed because MSVC's STL doesn't drag this in via other headers.

### CODE REVIEW

**Comment by StephanTLavavej** [comment]
Now that the test is correctly named, it's also being picked up by libc++'s test harness and experiencing other problems:

```
# | /home/runner/_work/llvm-project/llvm-project/libcxx/test/std/atomics/atomics.lockfree/is_always_lock_free.pass.cpp:102:3: error: AVX vector argument of type '__attribute__((__vector_size__(16 * sizeof(int)))) int' (vector of 16 'int' values) without 'avx512f' enabled changes the ABI [-Werror,-Wpsabi]
# |   102 |   CHECK_ALWAYS_LOCK_FREE(int __attribute__((vector_size(16 * sizeof(int)))));
# |       |   ^
# | /home/runner/_work/llvm-project/llvm-project/libcxx/test/std/atomics/atomics.lockfree/is_always_lock_free.pass.cpp:58:23: note: expanded from macro 'CHECK_ALWAYS_LOCK_FREE'
# |    58 |     std::atomic<type> a(obj);                                                                                          \
# |       |                       ^
```

I'm not tooled up to fix these (it's passing for MSVC's STL), can a real libc++ dev help?

**Comment by CaseyCarter** [comment]
Poking @ldionne, who added this test case in #99570.

**Review by ldionne — APPROVED** [review]

**Comment by ldionne** [comment]
Jeez. I merged without noticing that this PR was also renaming the test (triggering other failures).

**Comment by ldionne** [comment]
I undid the renaming for now and took only the addition of `<concepts>`: 0f58ab851c4e9e5cb962e34144c4169dd675389b

I am tackling the renaming (and the additional required fixes) in https://github.com/llvm/llvm-project/pull/106077

**Pull request merged**
