### PR TITLE
Fix a regression with alignas on structure members in C

### LINKED ISSUE #95032: clang drops `alignsas` on struct field
$ cat test.c
```
#include <assert.h>

struct S {
  alignas(16) char bytes[16];
};

static_assert(alignof(struct S) == 16);
```

$ clang -std=c2x test.c -c -o /dev/null
```
<source>:7:15: error: static assertion failed due to requirement '_Alignof(struct S) == 16'
    7 | static_assert(alignof(struct S) == 16);
      |               ^~~~~~~~~~~~~~~~~~~~~~~
<source>:7:33: note: expression evaluates to '1 == 16'
    7 | static_assert(alignof(struct S) == 16);
      |               ~~~~~~~~~~~~~~~~~~^~~~~
1 error generated.
```

### PR DESCRIPTION
**Pull request by AaronBallman**
This was a 19.x regression and thus has no release note.

Fixes #95032

### CODE REVIEW

**Review by cor3ntin — APPROVED** [review]

**Comment by jyknight** [comment]
I'm not sure I understand what happened here, since `_Alignas` did work properly before this change, right? How/why are `_Alignas` and `alignas` acting differently from eachother in C23 mode?

**Comment by AaronBallman** [comment]
> I'm not sure I understand what happened here, since `_Alignas` did work properly before this change, right? How/why are `_Alignas` and `alignas` acting differently from eachother in C23 mode?

`_Alignas` on a field used to work properly before b9cf7f1066cc7ec11c6074d10b0f2ec9a3ae72d9, but that commit changed `alignas` handling improperly. The issue boils down to the fact that C++ treats `alignas` as an attribute and C treats `_Alignas` (and now `alignas` as of C23) as a type specifier rather than an attribute. We were originally leaning on the C++ implementation when the keyword was spelled `alignas` and we missed some changes to make that work in C, which is what this commit is addressing (by ensuring the attribute moves onto the declarator where it belongs and used to be found).

**Comment by jyknight** [comment]
The part I'm confused about is that this commit doesn't appear to simply be adding "or `alignas`" to some code that said "if `_Alignas`". Yes, the newly added `isAlignas()` checks do cover both attributes, but `_Alignas` was still working even after b9cf7f1.

That is, in clang trunk, this test does still pass when parsed as -std=c23:
```
struct X {
    _Alignas(8) char n;
};

static_assert(_Alignof(struct X) == 8, "");
```

So why does this PR need to add new code to move `alignas`, instead of having `alignas` use whatever codepath was already handling `_Alignas`? Or, alternatively remove whatever code was formerly handling `_Alignas`, in favor of this new code?

Or, are `alignas` and `_Alignas` actually getting parsed differently, even still, so only `alignas` needs to be moved?

**Comment by AaronBallman** [comment]
> The part I'm confused about is that this commit doesn't appear to simply be adding "or `alignas`" to some code that said "if `_Alignas`". Yes, the newly added `isAlignas()` checks do cover both attributes, but `_Alignas` was still working even after [b9cf7f1](https://github.com/llvm/llvm-project/commit/b9cf7f1066cc7ec11c6074d10b0f2ec9a3ae72d9).
> 
> That is, in clang trunk, this test does still pass when parsed as -std=c23:
> 
> ```
> struct X {
>     _Alignas(8) char n;
> };
> 
> static_assert(_Alignof(struct X) == 8, "");
> ```
> 
> So why does this PR need to add new code to move `alignas`, instead of having `alignas` use whatever codepath was already handling `_Alignas`? Or, alternatively remove whatever code was formerly handling `_Alignas`, in favor of this new code?
> 
> Or, are `alignas` and `_Alignas` actually getting parsed differently, even still, so only `alignas` needs to be moved?

Ah, thank you for the further details! The issue boils down to the fact that `alignas` is not an attribute in C23 (it's a type-specifier-qualifier) but it is an attribute in C++. So we hit awkward situations where we claim the attribute is a C++11-style attribute, such as in `ProcessDeclAttribute()`. We explicitly disallow C++11 attributes on the declaration specifier:
```
  // Apply decl attributes from the DeclSpec if present.
  if (!PD.getDeclSpec().getAttributes().empty()) {
    ProcessDeclAttributeList(S, D, PD.getDeclSpec().getAttributes(),
                             ProcessDeclAttributeOptions()
                                 .WithIncludeCXX11Attributes(false)
                                 .WithIgnoreTypeAttributes(true));
  }
```
but when the attribute is on the declaration itself, we allow C++11 attributes:
```
ProcessDeclAttributeList(S, D, NonSlidingAttrs);
```

So there *is* a better way to address this and I think it actually fixes a bug that I didn't notice until now with non-structure use. The changes look a bit odd because I also had to make an adjustment to ensure that `matrix_type` continues to work (it's an odd beast that already required special handling, that special handling is now needed in two places).

**Review by jyknight — APPROVED** [review]
Thanks, LGTM. I like this version.

Did this change also fix any other bugs? Since it looks like we were previously not skipping ProcessDeclAttribute for ``[[]]`` attributes in C23 mode, when IncludeCXX11Attributes == false, and we were supposed to have been?

**Comment by AaronBallman** [comment]
> Thanks, LGTM. I like this version.

Thank you for the excellent review, I think we came to a better approach in the end!

> Did this change also fix any other bugs? Since it looks like we were previously not skipping ProcessDeclAttribute for `[[]]` attributes in C23 mode, when IncludeCXX11Attributes == false, and we were supposed to have been?

Theoretically yes, but practically no. We don't have any attributes in C23 that I think would be impacted by this except for `alignas`. At least, I've not been able to induce a difference in behavior.

**Pull request merged**
