### PR TITLE
[libc][stdlib] Only use freelist_malloc for baremetal targets.

### PR DESCRIPTION
**Pull request by lntue**

### CODE REVIEW

**Review by jhuber6 — COMMENTED** [review]
So, the problem I had was that the `freelist_heap_test` is triggered if you have `malloc` because the source just assumes that if you have `malloc` then it builds it. Can you also disable the test for now and in the future @PiJoules can move `freelist_heap` to an object library so we can check if it's built?

**Review by nickdesaulniers — APPROVED** [review]

**Comment by lntue** [comment]
> So, the problem I had was that the `freelist_heap_test` is triggered if you have `malloc` because the source just assumes that if you have `malloc` then it builds it. Can you also disable the test for now and in the future @PiJoules can move `freelist_heap` to an object library so we can check if it's built?

This PR changes `freelist_heap_test` to depend on `libc.src.stdlib.freelist_malloc` instead of `libc.src.stdlib.malloc`, which shouldn't be added for GPU.  Can you double check if that's what it is? @jhuber6

**Review by jhuber6 — APPROVED** [review]
You're right, reading comprehension.

**Comment by ilovepi** [comment]
I think we're seeing some CMake failures in our CI after this patch. Can you take a look, and if it will take a while to fix, revert.

Bot: https://ci.chromium.org/ui/p/fuchsia/builders/toolchain.ci/clang-linux-x64/b8744479865106393873/overview

Error:
```
CMake Error at /b/s/w/ir/x/w/llvm-llvm-project/libc/cmake/modules/LLVMLibCLibraryRules.cmake:250 (add_library):
  Error evaluating generator expression:

    $<TARGET_OBJECTS:libc.src.stdlib.freelist_malloc>

  Objects of target "libc.src.stdlib.freelist_malloc" referenced but is not
  one of the allowed target types (EXECUTABLE, STATIC, SHARED, MODULE,
  OBJECT).
Call Stack (most recent call first):
  /b/s/w/ir/x/w/llvm-llvm-project/libc/lib/CMakeLists.txt:22 (add_entrypoint_library)


CMake Error at /b/s/w/ir/x/w/llvm-llvm-project/libc/cmake/modules/LLVMLibCLibraryRules.cmake:250 (add_library):
  Error evaluating generator expression:

    $<TARGET_OBJECTS:libc.src.stdlib.freelist_malloc>

  Objects of target "libc.src.stdlib.freelist_malloc" referenced but is not
  one of the allowed target types (EXECUTABLE, STATIC, SHARED, MODULE,
  OBJECT).
Call Stack (most recent call first):
  /b/s/w/ir/x/w/llvm-llvm-project/libc/lib/CMakeLists.txt:22 (add_entrypoint_library)
```

**Comment by lntue** [comment]
> I think we're seeing some CMake failures in our CI after this patch. Can you take a look, and if it will take a while to fix, revert.
> 
> Bot: https://ci.chromium.org/ui/p/fuchsia/builders/toolchain.ci/clang-linux-x64/b8744479865106393873/overview
> 
> Error:
> 
> ```
> CMake Error at /b/s/w/ir/x/w/llvm-llvm-project/libc/cmake/modules/LLVMLibCLibraryRules.cmake:250 (add_library):
>   Error evaluating generator expression:
> 
>     $<TARGET_OBJECTS:libc.src.stdlib.freelist_malloc>
> 
>   Objects of target "libc.src.stdlib.freelist_malloc" referenced but is not
>   one of the allowed target types (EXECUTABLE, STATIC, SHARED, MODULE,
>   OBJECT).
> Call Stack (most recent call first):
>   /b/s/w/ir/x/w/llvm-llvm-project/libc/lib/CMakeLists.txt:22 (add_entrypoint_library)
> 
> 
> CMake Error at /b/s/w/ir/x/w/llvm-llvm-project/libc/cmake/modules/LLVMLibCLibraryRules.cmake:250 (add_library):
>   Error evaluating generator expression:
> 
>     $<TARGET_OBJECTS:libc.src.stdlib.freelist_malloc>
> 
>   Objects of target "libc.src.stdlib.freelist_malloc" referenced but is not
>   one of the allowed target types (EXECUTABLE, STATIC, SHARED, MODULE,
>   OBJECT).
> Call Stack (most recent call first):
>   /b/s/w/ir/x/w/llvm-llvm-project/libc/lib/CMakeLists.txt:22 (add_entrypoint_library)
> ```

It should be fixed with https://github.com/llvm/llvm-project/pull/96372.  Can you double check with the bots? @ilovepi

**Comment by ilovepi** [comment]
Sorry, I didn't see this before signing off for the weekend. https://github.com/llvm/llvm-project/pull/96372 did seem to fix the issue in our CI. Thanks!

**Pull request merged**
