### PR TITLE
[mlir][Bindings] Fix missing return value of functions and incorrect type hint in pyi.

### PR DESCRIPTION
**Pull request by annuasd**
The zero points of UniformQuantizedPerAxisType should be List[int].
And there are two methods missing return value.

### CODE REVIEW

**Comment by annuasd** [comment]
@ftynse  , please help review. Thanks.

**Comment by makslevental** [comment]
Can you add tests?

**Comment by annuasd** [comment]
@makslevental already update test file.

**Review by makslevental — APPROVED** [review]

**Comment by makslevental** [comment]
Let me know when you're ready for me to merge this in.

**Comment by annuasd** [comment]
@makslevental Ready to merge.

**Pull request merged**
