### PR TITLE
[X86] Don't request 0x90 nop filling in p2align directives

### PR DESCRIPTION
**Pull request by jmorse**
As of rev ea222be0d, LLVMs assembler will actually try to honour the "fill value" part of p2align directives. X86 always prints these as 0x90, however, I don't believe that's what it actually wants. If you compile an LLVM-IR file with -filetype=obj, you'll get multi-byte nops for .text padding.  If you go via a textual assembly file, you'll now get single-byte-nop padding. This divergent behaviour is undesirable IMO.

To fix: don't set the byte padding field for x86 which allows the assembler to pick multi-byte nops. Test that we get the same multi-byte padding when compiled via textual assembly or directly to object file. Added same-align-bytes-with-llasm-llobj.ll to that effect.

A whole load of test files get updated because of this change: the vast majority of them are co-incidental. The most suspicious ones are:
 *  loop-align-debug.ll: this is actually checking for line-number assignments,
 *  xray-tail-call-sled.ll: XRay installs a nop sled for reasons I don't understand, but it's independent of .p2align,
 * code-align-loops.ll: is checking that various IR constructs lead to .p2align directives, not what the padding is,

Everything else looked totally coincidental.

### CODE REVIEW

**Review by MaskRay — APPROVED** [review]
LGTM.

Is there any test that uses `.p2align 4{{$}}` so that it will catch `.p2align 4, 0x90` regression?

**Comment by lenary** [comment]
I agree it's undesirable for the text assembler to do something different to integrated assembler. Sorry I didn't notice this before.

x86 is the only (upstream) target using `TextAlignFillValue` - maybe that whole mechanism in MCAsmInfo should be removed if it will only be set upstream to the default value (0)?

At the very least, the x86 target doesn't need to set this to its documented default value, so you can probably delete all assignments to `TextAlignFillValue`.

**Comment by lenary** [comment]
Also, sorry for the behaviour divergence. I'm glad I timed my PR to land just after branching so we had time to find issues like this

**Comment by MaskRay** [comment]
Agreed that `TextAlignFillValue = 0` can be removed as x86 has the only use (and downstream targets tend to be RISC and unlikely need such mechanism).

**Comment by jmorse** [comment]
Thanks for the reviews; I've added a {{$}} to same-align-bytes-with-llasm-llobj.ll to ensure there are no trailing operands to p2align, and removed the now redundant assignments to TextAlignFillValue

> Also, sorry for the behaviour divergence. I'm glad I timed my PR to land just after branching so we had time to find issues like this

Timing greatly appreciated, this did indeed take a decent period to filter through to the right tests.

**Pull request merged**
