### PR TITLE
[libclc] Optimize ceil/fabs/floor/rint/trunc

### PR DESCRIPTION
**Pull request by frasercrmck**
These functions all map to the corresponding LLVM intrinsics, but the vector intrinsics weren't being generated. The intrinsic mapping from CLC vector function to vector intrinsic was working correctly, but the mapping from OpenCL builtin to CLC function was suboptimally recursively splitting vectors in halves.

For example, with this change, `ceil(float16)` calls `llvm.ceil.v16f32` directly once optimizations are applied.

Now also, instead of generating LLVM intrinsics through `__asm` we now call clang elementwise builtins for each CLC builtin. This should be a more standard way of achieving the same result

The CLC versions of each of these builtins are also now built and enabled for SPIR-V targets. The LLVM -> SPIR-V translator maps the intrinsics to the appropriate OpExtInst, so there should be no difference in semantics, despite the newly introduced indirection from OpenCL builtin through the CLC builtin to the intrinsic.

The AMDGPU targets make use of the same `_CLC_DEFINE_UNARY_BUILTIN` macro to override `sqrt`, so those functions also appear more optimal with this change, calling the vector `llvm.sqrt.vXf32` intrinsics directly.

### CODE REVIEW

**Comment by frasercrmck** [comment]
CC @rjodinchr, @karolherbst

**Review by arsenm — APPROVED** [review]
LGTM. I'm not sure how this all ends up expanding, I was expecting to see the elementwise builtins used.

It would be great if we had update_cc_test_checks style testing for the resulting implementation

**Comment by frasercrmck** [comment]
> LGTM. I'm not sure how this all ends up expanding, I was expecting to see the elementwise builtins used.

Yes, I suspect that this code originates from before the builtins were available? The builtins would probably make more sense, tbh. The current method is that we have the OpenCL builtin call the corresponding CLC builtin, which in its header uses this strange `__asm__` method of calling LLVM intrinsics directly. It should maybe just do: OpenCL builtin -> CLC builtin -> clang builtin?

> It would be great if we had update_cc_test_checks style testing for the resulting implementation

Oh yes, I agree. My efforts to introduce testing stalled somewhat. Maybe we can pick up that discussion on #87989?

**Comment by frasercrmck** [comment]
> > which in its header uses this strange **asm** method of calling LLVM intrinsics directly.
> 
> That's something that's always surprised me it works. It's rather unsafe (you can bypass immarg validation for instance). Plus asm callsites get infected with overly conservative attributes (like convergent, which you can't remove)

Yeah, good point.

> > It should maybe just do: OpenCL builtin -> CLC builtin -> clang builtin?
> 
> That's the simplest way to go

I've updated the patch to do just that, using the builtins. I'll update the description accordingly.

**Review by arsenm — APPROVED** [review]

**Pull request merged**
