### PR TITLE
[IR] Disallow ZeroInit for spirv.Image

### PR DESCRIPTION
**Pull request by wenju-he**
According to spirv spec, OpConstantNull's result type can't be image
type. So we can't generate zeroinitializer for spirv.Image.

### CODE REVIEW

**Comment by wenju-he** [comment]
@jcranmer-intel could you please take a look?
Before this PR, there could be following ir generated:
```
store target("spirv.Image", void, 1, 0, 0, 0, 0, 0, 0) zeroinitializer, ptr addrspace(4) %MImageObj, align 8
```
llvm-spirv translator isn't able to handle it due to spec requirement.

**Comment by wenju-he** [comment]
kindly ping @jcranmer-intel

**Review by jcranmer-intel — APPROVED** [review]

**Comment by bogner** [comment]
This change causes a number of the spir-v backend tests to crash:
> Failed Tests (5):
>   LLVM :: CodeGen/SPIRV/image-unoptimized.ll
>   LLVM :: CodeGen/SPIRV/read_image.ll
>   LLVM :: CodeGen/SPIRV/transcoding/get_image_num_mip_levels.ll
>   LLVM :: CodeGen/SPIRV/transcoding/image_with_access_qualifiers.ll
>   LLVM :: CodeGen/SPIRV/transcoding/spirv-types.ll

**Comment by wenju-he** [comment]
> image-unoptimized.ll

backtrace:
```
 #0 0x0000000001d2f0e1 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/export/users/wenjuhe/llvm/llvm-project/build/bin/llc+0x1d2f0e1)
 #1 0x0000000001d2c644 SignalHandler(int) Signals.cpp:0:0
 #2 0x00007fd516a7ddb0 __restore_rt (/lib64/libc.so.6+0x59db0)
 #3 0x00007fd516aca42c __pthread_kill_implementation (/lib64/libc.so.6+0xa642c)
 #4 0x00007fd516a7dd06 gsignal (/lib64/libc.so.6+0x59d06)
 #5 0x00007fd516a507d3 abort (/lib64/libc.so.6+0x2c7d3)
 #6 0x00007fd516a506fb _nl_load_domain.cold (/lib64/libc.so.6+0x2c6fb)
 #7 0x00007fd516a76c86 (/lib64/libc.so.6+0x52c86)
 #8 0x00000000014b3bf1 llvm::ConstantTargetNone::get(llvm::TargetExtType*) (/export/users/wenjuhe/llvm/llvm-project/build/bin/llc+0x14b3bf1)
 #9 0x0000000000abac68 (anonymous namespace)::SPIRVEmitIntrinsics::runOnFunction(llvm::Function&) (.part.0) SPIRVEmitIntrinsics.cpp:0:0
```
SPIRVEmitIntrinsics pass probably needs fix to not generate ConstantTargetNone for spirv.Image. @bogner WDYT?

**Pull request merged**
