### PR TITLE
[X86] Replace hasVirtualTileReg with AMXProgModel

### PR DESCRIPTION
**Pull request by aengelke**
Cleanup after AMXProgModel introduction. AMXProgModel is ManagedRA
whenever virtual tile registers exist at some point.

### CODE REVIEW

**Review by phoebewang — APPROVED** [review]
LGTM, thanks!

**Comment by phoebewang** [comment]
Is there any test affected? I assume tests for X86FastPreTileConfig might be affect by this change.

**Comment by aengelke** [comment]
FastPreTileConfig has (without #94989) it's own check whether virtual tile registers exist, it finds this out by iterating over all virtual registers. Functionality should be identical, so no tests are affected.

**Comment by phoebewang** [comment]
> FastPreTileConfig has (without #94989) it's own check whether virtual tile registers exist, it finds this out by iterating over all virtual registers. Functionality should be identical, so no tests are affected.

Sorry, my mistake. I didn't notice FastPreTileConfig also called setHasVirtualTileReg...

**Pull request merged**
