### PR TITLE
Disable test broken by #117624

### PR DESCRIPTION
**Pull request by vitalybuka**
The test fails after #117624
https://lab.llvm.org/buildbot/#/builders/186/builds/4581

### CODE REVIEW

**Comment by vitalybuka** [comment]
Please confirm that this is appropriate, or we need to revert #117624.

**Review by enh-google — COMMENTED** [review]
(thanks for fixing the breakage!)

**Comment by enh-google** [comment]
> Please confirm that this is appropriate, or we need to revert #117624.

this is appropriate --- Android doesn't use or support bfd any more (for several years now).

**Comment by hiraditya** [comment]
Thanks for fixing it quickly!

**Pull request merged**
