### PR TITLE
[AttributorLight] Without liveness checks, look at all functions

### PR DESCRIPTION
**Pull request by jdoerfert**

### CODE REVIEW

**Review by arsenm — APPROVED** [review]

**Comment by arsenm** [comment]
Has test failures

**Comment by jdoerfert** [comment]
> Has test failures

Locally, it passed. Unsure what I did wrong...

**Comment by jdoerfert** [comment]
I looked at the wrong tests. My bad. Should be fixed now.

**Review by arsenm — APPROVED** [review]

**Comment by arsenm** [comment]
Bot failed again

**Review by arsenm — APPROVED** [review]

**Pull request merged**
