### PR TITLE
[ARM] Introduce the v9.5-A architecture version to Arm targets

### PR DESCRIPTION
**Pull request by pratlucas**
This introduces the Armv9.5-A architecture version to the Arm backend,
following on from the existing implementation for AArch64 targets.

Mode details about the Armv9.5-A architecture version can be found at:
* https://community.arm.com/arm-community-blogs/b/architectures-and-processors-blog/posts/arm-a-profile-architecture-developments-2023
* https://developer.arm.com/documentation/ddi0602/2023-09/

### CODE REVIEW

**Comment by DavidSpickett** [comment]
Does this have an 8.x version to go with it like the previous ones?

**Comment by pratlucas** [comment]
No, V9.5-A is v9-only. The v9.4-A version was the last one to have a matching v8.x.

**Review by jthackray — APPROVED** [review]
Thanks, Lucas. I can't spot anything obviously wrong, so approved.

**Comment by DavidSpickett** [comment]
> No, V9.5-A is v9-only. The v9.4-A version was the last one to have a matching v8.x.

Cool. If you can find where we encode that mapping, it's worth adding a comment to say explicitly that the relation stops at 9.5.

**Comment by DavidSpickett** [comment]
It's already there for AArch64, https://github.com/llvm/llvm-project/blob/312acdfae1409bee29a33f71306e3ae3e1ea7d66/llvm/include/llvm/TargetParser/AArch64TargetParser.h#L434. Maybe ARM does it differently.

**Comment by pratlucas** [comment]
The ARM Target Parser is behind the AArch64 one in terms of design and refactoring. For the ARM case that relationship is not explicitly encoded in a single place, there are multiple switch-cases covering specific scenarios instead (e.g. the ones updated by this patch in clang/lib/Basic/Targets/ARM.cpp).

I've added a comment only to the TableGen file for now, at least until we get the ARM target parser to the same standards as the AArch64 one.

**Review by DavidSpickett — APPROVED** [review]

**Pull request merged**
