### PR TITLE
[Hexagon] Optimize post-increment load and stores in loops.

### PR DESCRIPTION
**Pull request by sgundapa**
This patch optimizes the post-increment instructions so that we can packetize them together.
v1 = phi(v0, v3')
v2,v3  = post_load v1, 4
v2',v3'= post_load v3, 4

This can be optimized in two ways

v1 = phi(v0, v3')
v2,v3' = post_load v1, 8
v2' = load v1, 4

### CODE REVIEW

**Comment by sgundapa** [comment]
One of the issues that was exposed with this patch is fixed here : https://github.com/llvm/llvm-project/pull/82386

**Review by SundeepKushwaha — COMMENTED** [review]
lgtm

**Comment by steven-johnson** [comment]
This appears to have injected a failure in HVX codegen in Halide, e.g.

```
Hexagon simulator executed function 0x5c4a0 in 1000 cycles
Hexagon simulator executed function 0x614a0 in 1000 cycles
Hexagon simulator executed function 0x644c0 in 1000 cycles
Hexagon simulator executed function 0x88570 in 1000 cycles
CRASH from thread 0!
I think the exception was: 0x20, Misaligned Load @ 0x6
Register Dump (r0 clobbered, pc subject to prior action by the exception handler):
r00=000000cd r01=00002170 r02=00060b00 r03=00000000
r04=00000000 r05=00000000 r06=00060ff8 r07=00059b00
r08=00059b00 r09=00059900 r10=00000000 r11=00000000
r12=00000000 r13=00000000 r14=00089024 r15=00000000
r16=00000000 r17=00000000 r18=0005e800 r19=000021e0
r20=00058008 r21=00063b00 r22=babebeef r23=babebeef
r24=babebeef r25=babebeef r26=babebeef r27=babebeef
r28=0004ada0 r29=04159598 r30=041595a0 r31=00012448
sa0=00088400 lc0=00000001 sa1=00000000 lc1=00000000
p30=0000ff00  m0=00000000  m1=00000000 usr=00010000
 pc=00001b3c ugp=00000000  gp=00058000 elr=00022908
badva0=00000006 badva1=041595f0
ssr=80140020 ccr=00130000 tid=00000000 imask=00000000
evb=000000cd modectl=00002170 syscfg=00060b00 ipend=00000000
```

**Comment by steven-johnson** [comment]
Ping -- this is still broken. Is a fix (or rollback) on the way? Can we assist in some way?

**Comment by steven-johnson** [comment]
I don't have the privileges to revert this, but if you do so I will offer my approval :-)

**Comment by steven-johnson** [comment]
The standard Halide tests will repro it when configured for Hexagon; this
is a bit of work to set up, but honestly, testing Hexagon changes against
Halide is probably worth your while anyway, as we have been the first
project to report the last few breakages. See
https://github.com/halide/Halide/blob/main/README.md#halide-for-hexagon-hvx
for details (and please ping me if you have trouble getting it set up).

**Comment by sgundapa** [comment]
https://github.com/llvm/llvm-project/pull/83151  - to revert the change.

**Pull request merged**
