### PR TITLE
[clang][Driver] Add a custom error option in multilib.yaml.

### PR DESCRIPTION
**Pull request by statham-arm**
Sometimes a collection of multilibs has a gap in it, where a set of driver command-line options can't work with any of the available libraries.

For example, the Arm MVE extension requires special startup code (you need to initialize FPSCR.LTPSIZE), and also benefits greatly from -mfloat-abi=hard. So a multilib provider might build a library for systems without MVE, and another for MVE with -mfloat-abi=hard, anticipating that that's what most MVE users would want. But then if a user compiles for MVE _without_ -mfloat-abi=hard, thhey can't use either of those libraries – one has an ABI mismatch, and the other will fail to set up LTPSIZE.

In that situation, it's useful to include a multilib.yaml entry for the unworkable intermediate situation, and have it map to a fatal error message rather than a set of actual libraries. Then the user gets a build failure with a sensible explanation, instead of selecting an unworkable library and silently generating bad output. The new regression test demonstrates this case.

This patch introduces extra syntax into multilib.yaml, so that a record in the `Variants` list can omit the `Dir` key, and in its place, provide a `FatalError` key. Then, if that variant is selected, the error message is emitted as a clang diagnostic, and multilib selection fails.

In order to emit the error message in `MultilibSet::select`, I had to pass a `Driver &` to that function, which involved plumbing one through to every call site, and in the unit tests, constructing one specially.

### CODE REVIEW

**Review by MaskRay — COMMENTED** [review]
I'm starting a 3-week vacation this Friday and will have limited availability. Happy for other reviewers to approve.

**Review by ostannard — APPROVED** [review]
LGTM

**Comment by statham-arm** [comment]
There are two failed CI checks here, but they both seem to be complaining about a libc++ test called `pstl.merge.pass.cpp`, which is surely completely unrelated to this clang driver change specific to bare-metal multilib setups.

**Comment by statham-arm** [comment]
For the record, that also looks spurious: again it's completely unrelated to this patch, and also, [build 4752](https://lab.llvm.org/buildbot/#/builders/123/builds/4752) of the same buildbot failed in the same way, two commits earlier. It looks more likely that that test is just flaky.

**Comment by petrhosek** [comment]
This is just a nit, but is there a reason for calling this `FatalError` rather than just `Error`? To me "fatal" usually means something went seriously wrong, but in this case it's just the fact the combination of flags is not supported and in the driver we usually just refer to these cases as errors.

**Comment by statham-arm** [comment]
I'd intended it to clarify that it will cause your link to fail, as opposed to some more recoverable type of error of the form "falling back to this less-desirable library but your link will still at least work". I haven't actually implemented such a thing, but it made sense to me to leave space for it in the (implied) YAML schema.

I suppose you could call those "error" and "warning" respectively, although to me "warning" in a compiler context has a connotation of warning the user about _their own_ potential error, whereas here, the fact that some particular toolchain provider hasn't built _exactly_ the library the user would most like doesn't mean the user was wrong to want it.

**Comment by petrhosek** [comment]
I think `Error` and `Warning` would be more consistent actually, especially if `-Werror` also applied to `Warning`; ideally we would also have a custom warning type so you could do e.g. `-Wno-multilib-warning` to suppress these warnings.

**Comment by petrhosek** [comment]
> To be clear, are you asking _me_ to make a followup PR to change that identifier in this already-landed patch, or are you going to do it?
> 
> (Just to avoid the situation where both of us do it, or both of us think the other is going to)

If you have time to implement it, that would be great. I might be able to take a look, but it's going to be a few weeks before I have time, and if we're going to rename `FatalError` I think we better do it as soon as possible before users start using it. I'd do it as two separate changes, first to rename `FatalError` to `Error` and second to introduce `Warning`.

**Pull request merged**
