### PR TITLE
[lld][NFC] Remove unnecessary else statements.

### PR DESCRIPTION
**Pull request by cjacek**
Follow up addressing #69099 review comment.

### CODE REVIEW

**Comment by rnk** [comment]
Looks good, but it looks like check-lld failed:
https://buildkite.com/llvm-project/github-pull-requests/builds/8476#018b42ac-9aaf-4930-9f54-ff29d0d3af45
Can you investigate?

**Review by compnerd — APPROVED** [review]
Thank you!

**Comment by cjacek** [comment]
> Looks good, but it looks like check-lld failed: https://buildkite.com/llvm-project/github-pull-requests/builds/8476#018b42ac-9aaf-4930-9f54-ff29d0d3af45 Can you investigate?

I pushed a fixup, sorry about that.

**Review by rnk — APPROVED** [review]
Thanks!

**Review by compnerd — APPROVED** [review]

**Pull request merged**
