### PR TITLE
[StackFrameLayoutAnalysis] Support more SlotTypes

### PR DESCRIPTION
**Pull request by hazzlim**
Add new SlotTypes to StackFrameLayoutAnalysis to disambiguate Fixed and Variable-Sized stack slots from Variable slots. As Offsets are unreliable for VLA-area objects, sort these to the end of the list - using the Frame Index to ensure a deterministic order when Offsets are equal.

### CODE REVIEW

**Comment by hazzlim** [comment]
This should fix buildbot failure https://lab.llvm.org/buildbot/#/builders/16/builds/2383 caused by #100386 (due to non-deterministic sorting when offsets are equal).

**Review by ilovepi — APPROVED** [review]
I think this is mostly OK, but I wonder if we also just always need to sort by all the printed fields? So, offset, type, alignment and size? I think that may be necessary to avoid non determinism. If we’re doing that, then we probably don’t need to put VariableSize at then end. 

Can you add those other fields to the comparison?

**Comment by ilovepi** [comment]
Ah I missed the slot number comparisons. Feel free to ignore my previous comment

**Comment by hazzlim** [comment]
> Ah I missed the slot number comparisons. Feel free to ignore my previous comment

Great - thanks so much for reviewing, and sorry if that wasn't initially very clear!

My thinking behind explicitly sorting slots with Type VariableSize to the end is that we currently don't generate correct offsets for these, but they do actually end up at "the end" (the most negative offset from the incoming SP). So this sorting order gives us a more correct layout than we otherwise would, even though the offset values are wrong.

I can update the comment to make this more explicit, if you think that would be useful?

**Comment by ilovepi** [comment]
Better comments never hurt, but I’m fine either way. The offsets are something I’m planning to look into when I get some time.

**Comment by hazzlim** [comment]
> Better comments never hurt, but I’m fine either way. The offsets are something I’m planning to look into when I get some time.

I've updated the comment to be a bit more explanatory w.r.t. sorting VariableSized slots to the end.

**Comment by ilovepi** [comment]
Great. Thanks.

FYI: the bot failure seems to be related to Python, so you're probably safe to land this.

**Pull request merged**
