### PR TITLE
[NFC][SPIRV] Cleanup selectOpWithSrc functions

### PR DESCRIPTION
**Pull request by V-FEXrt**
As a follow up request from https://github.com/llvm/llvm-project/pull/111082#discussion_r1811132876 the following non functional changes have been make
- `selectNAryOpWithSrcs` has been renamed to `selectOpWithSrcs`
- Calls to `selectUnOpWithSrc` have been replaced with `selectOpWithSrcs`
- `selectUnOpWithSrc`  has been deleted

### CODE REVIEW

**Review by spall — APPROVED** [review]
LGTM

**Review by bogner — APPROVED** [review]
It's best to link to the PR the feedback came from in the description when doing this kind of follow up.

**Comment by spall** [comment]
@V-FEXrt If you want to add a link to the PR the feedback came from its #111082

**Comment by V-FEXrt** [comment]
@bogner updated the description :)

**Pull request merged**
