### PR TITLE
[RISCV] Fix the worst case for VSHA2MS in SiFive P400/P600 scheduling models

### PR DESCRIPTION
**Pull request by mshockwave**
For each RVV instruction we should have a single WriteRes assignment to the worst case scheduling class. This assignment is usually equal to that of the largest LMUL + smallest SEW. My #114317 accidentally made two of these assignments on `WriteVSHA2MSV_WorstCase`. This won't affect our MachineScheduler nor most of our llvm-mca use cases (assuming you populate the correct LMUL and SEW), yet it's not ideal either.

This patch fixes this issue by assigning the correct numbers and resource mapping to `WriteVSHA2MSV_WorstCase`, which is equal to that of largest LMUL + _largest_ SEW (Zvknh's scheduling properties are special). I also added a MCA test to make sure we always pick up the correct worst case numbers for P600's scheduling model.

Original issue was reported by @reidtatge

### CODE REVIEW

**Comment by mshockwave** [comment]
We might also want to teach TableGen to warn or even throw an error on cases like this (i.e. duplicate WriteRes assignments)

**Comment by reidtatge** [comment]
Yeah, agreed.

I spent just a very few minutes looking at it, and (not being an expert in
TableGen backends) it looks like SubtargetEmitter.cpp/findWriteResources is
just ignoring the situation, although it does look for aliased duplicates -
and aborts with a diagnostic - but doesn't explicitly look for duplicates
definitions (around line 925).
And CodeGenSchedModels::addProcResource() just quietly returns if its
already been seen for a given ProcModel.
And I may be missing something else...    FWIW :-)

-Reid

**Review by reidtatge — APPROVED** [review]
LGTM

**Review by topperc — APPROVED** [review]
LGTM

**Pull request merged**
