### PR TITLE
[flang][OpenMP] Reland Fix copyprivate semantic checks (#95799)

### LINKED ISSUE #87214: [Flang][OpenMP] Compilation error when end single construct has a copyprivate clause
```
Version of flang-new : 19.0.0(cbcdf126ccc774c063b5d5140c1393ff5305dded)/AArch64
```

Compilation error occurs when `end single` construct has a `copyprivate`  clause.

Compilation terminates normally in the following cases:
- Delete the `COPYPRIVATE` clause, or                    (omp30_example_a_37_01_222.f90)
- Add the following before the assignments A and B, or   (omp30_example_a_37_01_223.f90)
```
  !$OMP THREADPRIVATE(A,B)
```
- Add `PARALLEL` construct                               (omp30_example_a_37_01_224.f90)

The following are the test program, Flang-new, Gfortran and ifort compilation/execution result.

omp30_example_a_37_01_22.f90:
```fortran
program main
  REAL A, B
  A=1.0
  B=2.0
!$OMP SINGLE
!READ (11) A,B
!$OMP END SINGLE COPYPRIVATE (A,B)
  print *,'pass'
end program main
```

```
$ flang-new -fopenmp omp30_example_a_37_01_22.f90
error: Semantic errors in omp30_example_a_37_01_22.f90
./omp30_example_a_37_01_22.f90:7:31: error: COPYPRIVATE variable 'a' is not PRIVATE or THREADPRIVATE in outer context
  !$OMP END SINGLE COPYPRIVATE (A,B)
                                ^
./omp30_example_a_37_01_22.f90:7:33: error: COPYPRIVATE variable 'b' is not PRIVATE or THREADPRIVATE in outer context
  !$OMP END SINGLE COPYPRIVATE (A,B)
                                  ^
$
```

```
$ export OMP_NUM_THREADS=1; gfortran -fopenmp omp30_example_a_37_01_22.f90; ./a.out
 pass
$
```

```
$ export OMP_NUM_THREADS=1; ifort -qopenmp -diag-disable=10448 omp30_example_a_37_01_22.f90; ./a.out
 pass
$
```

omp30_example_a_37_01_222.f90:
```fortran
program main
  REAL A, B
  A=1.0
  B=2.0
!$OMP SINGLE
!READ (11) A,B
!$OMP END SINGLE  ! COPYPRIVATE(A,B)
  print *,'pass'
end program main
```

omp30_example_a_37_01_223.f90:
```fortran
program main
  REAL A, B
!$OMP THREADPRIVATE(A,B)
  A=1.0
  B=2.0
!$OMP SINGLE
!READ (11) A,B
!$OMP END SINGLE COPYPRIVATE(A,B)
  print *,'pass'
end program main
```

omp30_example_a_37_01_224.f90:
```fortran
program main
  REAL A, B
!$OMP PARALLEL
  A=1.0
  B=2.0
!$OMP SINGLE
!READ (11) A,B
!$OMP END SINGLE  COPYPRIVATE(A,B)
!$OMP END PARALLEL
  print *,'pass'
end program main
```

### PR DESCRIPTION
**Pull request by luporl**
There are some cases in which variables used in OpenMP constructs
are predetermined as private. The semantic checks for copyprivate
were not handling those cases.

Besides that, shared symbols were not being properly represented
in some cases. When there was no previously declared private
(implicit) symbol, no new association symbols, representing
shared ones, were being created.

These symbols must always be inserted in constructs that may
privatize the original symbol: parallel, teams and task
generating constructs.

Fixes #87214 and #86907

### CODE REVIEW

**Comment by luporl** [comment]
Note: the first commit is the same as #95799. The fix for the regressions it introduced is in the second commit.

**Comment by tblah** [comment]
Thanks for the updated version with regressions fixed. Unfortunately this fails(*) another of our tests (minimized):
```
program repro
  integer, parameter :: SIZE=20
  integer :: i
  integer :: array(SIZE)
  !$omp parallel
  array = [ (i,i=1,SIZE) ]
  print *,i
  !$omp end parallel
end program
```

(*) it hits a HLFIR TODO that wasn't previously encountered. It is possible that it should have been, but it is a regression in previously working code.

**Comment by luporl** [comment]
Ok, let's try that again.

Now implied do variables are being skipped in `OmpAttributeVisitor::Post(const parser::Name &)`. I've also added namelists as non-privatizable symbols, as in `DataSharingProcessor.cpp`. Now semantics and lowering should agree on what can be privatized.

**Review by tblah — APPROVED** [review]
This fixes our tests. Thanks!

**Comment by luporl** [comment]
@psteinfeld Do you want to check if this PR fixes your internal tests too, before it is merged?

**Comment by psteinfeld** [comment]
@luporl, after this change, we started failing some internal tests.  Here's a reproducer:
```
$cat bug.f90
subroutine sub(arg)
  integer,optional :: arg(:)
  !$omp parallel shared(arg) num_threads(1)
  if (present(arg)) print *, "present"
  !$omp end parallel
end subroutine

$flang-new -c -fopenmp bug.f90
error: Semantic errors in bug.f90
./bug.f90:4:15: error: Argument of PRESENT() must be the name of a whole OPTIONAL dummy argument
    if (present(arg)) print *, "present"
                ^^^
```
The semantic error did not appear before your change.

Can you please take a look?

**Comment by luporl** [comment]
@psteinfeld, it should be fixed by https://github.com/llvm/llvm-project/pull/101538.

**Pull request merged**
