### PR TITLE
[SLP]Do not account external uses in EH block and in non-returning blocks

### PR DESCRIPTION
**Pull request by alexey-bataev**
No need to account the cost of the external uses in EH and non-returning
basic blocks.

### CODE REVIEW

**Review by RKSimon — COMMENTED** [review]
By bailing on unreachable are we affecting existing reduced regression tests that insert them?

**Comment by alexey-bataev** [comment]
> By bailing on unreachable are we affecting existing reduced regression tests that insert them?

Yes. I will update such tests and remove unreachable terminator. Actually, SLP vectorizer should ignore such blocks, no need to vectorize anything there to save compile time. And in EH blocks too.

**Comment by alexey-bataev** [comment]
Ping!

**Review by RKSimon — APPROVED** [review]
LGTM - cheers

**Pull request merged**
