### PR TITLE
[llvm][cmake] Performing expensive checks requires enabling assert.

### PR DESCRIPTION
**Pull request by huaatian**
LLVM will intercept errors using assert() when LLVM_ENABLE_EXPENSIVE_CHECKS is ON. So an explicit check is added.

### CODE REVIEW

**Comment by huaatian** [comment]
Ping

**Comment by huaatian** [comment]
@Vasileios Porpodas

**Comment by huaatian** [comment]
@vporpo

**Comment by huaatian** [comment]
@aeubanks, this issue was discovered in our downstream project. Could you please help review it? Thank you.

**Comment by aeubanks** [comment]
it doesn't really make sense to run expensive checks without asserts, I wouldn't consider that configuration supported

**Comment by huaatian** [comment]
> it doesn't really make sense to run expensive checks without asserts, I wouldn't consider that configuration supported

Thank you for reviewing the code. Indeed, in most cases, when EXPENSIVE_CHECKS is enabled, !NDEBUG is also set. However, I understand that there is no explicit binding between these two situations. For example, in a few cases, I would like to use the checks that report errors with errs(), rather than using assert(). This can be considered as a tolerable medium complexity check. Is this understanding correct? I would appreciate your opinion.

**Comment by huaatian** [comment]
And also, when the user enables EXPENSIVE_CHECKS and NDEBUG, there is no prompt that such settings are wrong, but these two unit tests will fail. I think this is an issue.

**Comment by aeubanks** [comment]
> For example, in a few cases, I would like to use the checks that report errors with errs(), rather than using assert(). 

I don't understand this sentence, can you clarify?

> And also, when the user enables EXPENSIVE_CHECKS and NDEBUG, there is no prompt that such settings are wrong, but these two unit tests will fail. I think this is an issue.

That's fair, it would be good to have a check for this either in CMake or in some header. I would prefer this option.

**Comment by huaatian** [comment]
> That's fair, it would be good to have a check for this either in CMake or in some header. I would prefer this option.
So, I added a check in CMake, would that be appropriate?

**Comment by huaatian** [comment]
> That's fair, it would be good to have a check for this either in CMake or in some header. I would prefer this option.

So, I added a check in CMake, would that be appropriate?

**Review by aeubanks — APPROVED** [review]

**Pull request merged**
