### PR TITLE
[MC][DWARF] Use target (non-native) path separators when building DWARF directory-tables

### PR DESCRIPTION
**Pull request by jmorse**
This is a patch that allows a triple (or flag) to override the native path separators used when constructing the DWARF linetable directory-entries. This means that if you feed LLVM-IR with Windows path endings in the debug-info metadata into llc on Linux, you'll get an identical output. Otherwise, the difference in path separators means a different set of directories is produced (see test).

The overall rational for this patch is identical-binary-checking of objects produced on Linux versus Windows. The PlayStation build environment is fundamentally a Windows environment, but we often do testing under a Linux environment because it's easier. We feel a lot more confident about this when we produce identical binaries whether building on Windows or Linux, and are able to test linux-built binaries in Windows environments with as few differences as possible. Hence this patch!

There's precedent in the clang frontend with the -ffile-reproducible flag and a few other switches, which I believe helps Chromium generate identical binaries between Linux/Windows, although not for debug-info sections.

### CODE REVIEW

**Comment by dwblaikie** [comment]
Maybe the title should be (& I haven't looked at the description/change in detail, so hopefully this suggested title also aligns with the implementation) "use the target path separator rather than the host path separator in DWARF output"?

**Comment by pogo59** [comment]
> Maybe the title should be (& I haven't looked at the description/change in detail, so hopefully this suggested title also aligns with the implementation) "use the target path separator rather than the host path separator in DWARF output"?

That's not the full effect. For PS targets it's getting forced to Windows style.

Really this needs to cater to how a cross-platform toolchain gets used. I would expect the host to be the usual environment for the debugger UI. Sony has the unusual use-case here, where a build can happen on Linux but the debugger runs on Windows (and expects Windows pathnames).

I think it would be better to have the decision NOT be based on the triple, but have the backend allow the driver to control the style (without perturbing today's defaults) and then the PS driver can do the needful.

**Comment by dwblaikie** [comment]
> > Maybe the title should be (& I haven't looked at the description/change in detail, so hopefully this suggested title also aligns with the implementation) "use the target path separator rather than the host path separator in DWARF output"?
> 
> That's not the full effect. For PS targets it's getting forced to Windows style, based on the target triple.
> 
> Really this needs to cater to how a cross-platform toolchain gets used. I would expect the host to be the usual environment for the debugger UI. Sony has the unusual use-case here, where a build can happen on Linux but the debugger runs on Windows (and expects Windows pathnames).
> 
> I think it would be better to have the decision NOT be based on the triple, but have the backend allow the driver to control the style (without perturbing today's defaults) and then the PS driver can do the needful.

Hrm :/ that seems a bit problematic... (since at compile time we can't know which OS you'll be remote debugging from) - would it be reasonable to always use path separators that match the target, and have consumers do remapping as needed?

**Comment by jmorse** [comment]
> Hrm :/ that seems a bit problematic... (since at compile time we can't know which OS you'll be remote debugging from) - would it be reasonable to always use path separators that match the target, and have consumers do remapping as needed?

I'd say so -- interpreting the "target" as the triple here, which is what this patch implements: when targeting the PS5 triple it uses windows path separators when constructing the linetable header, plus there's a flag for testing. Perhaps there's a gap in meaning between "target" and "triple" though?

I don't believe we're unique here, in a previous life doing embedded systems things I had a few proprietary connect-to-the-device debug adapters that were Windows only, but with Linux toolchains available too. Certainly not a common use case.

**Comment by dwblaikie** [comment]
> > Hrm :/ that seems a bit problematic... (since at compile time we can't know which OS you'll be remote debugging from) - would it be reasonable to always use path separators that match the target, and have consumers do remapping as needed?
> 
> I'd say so -- interpreting the "target" as the triple here, which is what this patch implements: when targeting the PS5 triple it uses windows path separators when constructing the linetable header, plus there's a flag for testing. Perhaps there's a gap in meaning between "target" and "triple" though?

Sorry, I'm not trying to draw a distinction between triple and target - I'm being a bit vague/loose with terminology there, probably.

So the choice of separator is target/triple motivated, but isn't necessarily the separator of that target/triple? Or would it be reasonable to say the path separator is, as far as LLVM's concerned, the separator for the target?

We currently don't have, so far as I can see, code to determine/answer the question of "what is the target's path separator" - we only have "real_style" which, given the "native" style, produces windows on Win32, and posix otherwise. But we could add something that gave a style given a triple, and could use that?

If you want to be able to reuse build artifacts, if the build for a given target should be about that target, not about the host - it seems like the right thing to do would be to have the path separators match the target - and a consumer could then rely on that and replace path separators with whatever path separators the local machine they're on is using?

Alternatively, I guess since DWARF contains absolute paths (well, can - you can avoid that with -fdebug-compilation-dir=. etc) - how could those paths be portable to another machine, let alone one with a different path separator/file system?

> I don't believe we're unique here, in a previous life doing embedded systems things I had a few proprietary connect-to-the-device debug adapters that were Windows only, but with Linux toolchains available too. Certainly not a common use case.

**Comment by jmorse** [comment]
(Blurgh, I'm having a bad time keeping up even with the patches I upload,)

I think we're in agreement about the idea of having a separator defined by the target, and as you say make it the consumers problem to transform that into the consumers environment if it's different to the target too.

> Alternatively, I guess since DWARF contains absolute paths (well, can - you can avoid that with -fdebug-compilation-dir=. etc) - how could those paths be portable to another machine, let alone one with a different path separator/file system?

Right now we've got a big bag of `-fdebug-prefix-map` options that maps local paths into the canonical Windows environment for our SDK; I suspect there's no graceful solution,

However: while digging into this further I've encountered a bunch of places within clangs header-handling which govern what path separators enter into debug-info. how DIFiles are segmented into filenames and directories, and so forth. It's beginning to look like having totally-identical-debug-info based on the target, that doesn't depend on the compiler-host environment, would be really invasive. Thus I'm going to back off from this until we know it's actually worth it.

**Pull request closed without merging**
