### PR TITLE
[libc++] Explicitly convert to masks in SIMD code

### PR DESCRIPTION
**Pull request by philnik777**
This makes it clearer when we use masks and avoids MSan complaining.

### CODE REVIEW

**Comment by vitalybuka** [comment]
Probably unrelated, this is the only algorithm patch in the range https://lab.llvm.org/buildbot/#/builders/85/builds/1657/steps/11/logs/stdio

**Comment by philnik777** [comment]
@thurstond Please comment on a PR when you revert it. I didn't see the revert until now. Also, what's the path forward here? The pre-commit CI passed, so whatever you're seeing is most likely not a supported configuration. It seems like I can't see the logs anymore, so I don't even know what the failure is.

CC @vitalybuka, since you commented before.

**Comment by vitalybuka** [comment]
> @thurstond Please comment on a PR when you revert it. I didn't see the revert until now.

Github UI makes it confusing, some may have an impression that 
image
on PR will notify the user.

It would be nice to have a policy about that. Sometimes I create a new issue on revert, other times I set personal notifications to check In a day or so if the author acknowledged the revert.

> Also, what's the path forward here? The pre-commit CI passed, so whatever you're seeing is most likely not a supported configuration. 

Pre-commit CI covers only a fraction of officially libc++ supported configurations, e.g. the arm is not covered at all. Also why passing libc++ under sanitizer is not a supported configuration?

> It seems like I can't see the logs anymore, so I don't even know what the failure is.

We know the bot name "sanitizer-aarch64-linux-bootstrap-hwasan", I can re-run  
https://github.com/llvm/llvm-project/pull/121352 on the bot without commit.

**Comment by thurstond** [comment]
> @thurstond Please comment on a PR when you revert it. I didn't see the revert until now. 

@philnik777 Sorry, I didn't realize github doesn't automatically notify about reverts. I will comment on PRs in the future.

----

> We know the bot name "sanitizer-aarch64-linux-bootstrap-hwasan", I can re-run
https://github.com/llvm/llvm-project/pull/121352 on the bot without commit.

Thanks @vitalybuka!

**Comment by vitalybuka** [comment]
So this is a crash in compiler triggered by PR.

> Also, what's the path forward here?

If we think this is test only specific issue (I doubt it is), we can disable them with HWASAN.
I believe it will likely hit down stream users, so we better to fix compiler before reland.

**Comment by vitalybuka** [comment]
Created https://github.com/llvm/llvm-project/issues/121365 with reproducer. Hopefully we resolve this quickly.

BTW. Seems there is existing guideline https://llvm.org/docs/DeveloperPolicy.html#id19 : "It is customary to respond to the original commit email mentioning the revert."  But I would prefer some stronger wording.

**Comment by philnik777** [comment]
> Pre-commit CI covers only a fraction of officially libc++ supported configurations, e.g. the arm is not covered at all. Also why passing libc++ under sanitizer is not a supported configuration?

It looks like you're not aware of the libc++ pre-commit CI, which is different from the rest of the project. We do have arm coverage. In fact, we have over 60 different configurations across various platforms that we support. We don't have any hwasan coverage in there though, which means that we're not supporting it officially. That's simply the policy. If you want to change that, feel free to add a new configuration to the test matrix for it.


> > @thurstond Please comment on a PR when you revert it. I didn't see the revert until now.
> 
> @philnik777 Sorry, I didn't realize github doesn't automatically notify about reverts. I will comment on PRs in the future.

No worries!

**Comment by vitalybuka** [comment]
> It looks like you're not aware of the libc++ pre-commit CI, which is different from the rest of the project. We do have arm coverage. In fact, we have over 60 different configurations across various platforms that we support. We don't have any hwasan coverage in there though, which means that we're not supporting it officially. That's simply the policy. If you want to change that, feel free to add a new configuration to the test matrix for it. I'm happy to help with that if there are problems.

Sorry, probably I am not aware.
I assumed pre-commit C is https://github.com/llvm/llvm-project/actions/runs/12563251328/job/35025625406

And this is worklow file https://github.com/llvm/llvm-project/blob/1b09bb7b0fa1c101021dfd00ffc47f4689f085df/.github/workflows/libcxx-build-and-test.yaml

How to tell if it's running aarch64?

**Comment by philnik777** [comment]
> Sorry, probably I am not aware. I assumed pre-commit CI is https://github.com/llvm/llvm-project/actions/runs/12563251328/job/35025625406
> 
> And this is worklow file https://github.com/llvm/llvm-project/blob/1b09bb7b0fa1c101021dfd00ffc47f4689f085df/.github/workflows/libcxx-build-and-test.yaml
> 
> How to tell if it's running aarch64?

This is most of the pre-commit CI, but there is also https://buildkite.com/llvm-project/libcxx-ci/builds/37688, which mostly runs the different platforms. IDK how to see that after the fact though, or whether there is even any UI hint that it ever ran.

**Pull request merged**
