### PR TITLE
[clang][Interp] Merge ByteCodeExprGen and ByteCodeStmtGen

### PR DESCRIPTION
**Pull request by tbaederr**
When implementing support for `StmtExpr`, I ran  into a problem: there is no way for `ByteCodeExprGen` to visit a statement. Previously, `ByteCodeStmtGen` inherited from `ByteCodeExprGen`, so the former could visit expressions, but the latter couldn't visit statements.

This branch merges the two, renames the result to `Compiler` and uses it to implement `StmtExpr` support.

Apart from implementing `StmtExpr` support, this entire branch is NFC of course, but I was wondering if this makes sense for everyone involved.

### CODE REVIEW

**Comment by AaronBallman** [comment]
> But that's not the problem I have in mind. My problem is the other way around: when `ByteCodeExprGen` needs to generate code for statements. It has no `visitStmt` function, because that's only implemented in the subclass.

Ah, so the choices boil down to using a single interface like this, or doing something like CRTP (or virtual dispatch)?

I like the separation of concerns between the stmt and expr emitters, but I'm not opposed to unifying them. How ugly does CRTP get though?

**Comment by tbaederr** [comment]
> How ugly does CRTP get though?

Looks like this: https://github.com/tbaederr/llvm-project/commit/ae37a17e30978cbe8e42799d26308b2e4e7b0115

Not really a big fan.


But I'm now stuck with 
```
mold: error: undefined symbol: lib/libclangAST.a(ByteCodeExprGen.cpp.o): clang::interp::ByteCodeStmtGen<clang::interp::EvalEmitter>::visitStmt(clang::Stmt const*)
```

and need to investigate something else.

**Comment by tbaederr** [comment]
Ping

**Comment by tbaederr** [comment]
> Sorry, I thought you were still doing some investigation.

Ah, sorry, I was just trying to say that this is how far I'm going to investigate at that point. :)


> I can live with either approach; the CRTP way doesn't seem too awful to me and retains the separation. But the unified interface also doesn't seem too awful to me given the relationship between `Stmt` and `Expr` in our AST. Given your preference for the unified interface, I'd be okay moving forward with that.

I would probably merge them but then split the implementation into different files, e.g. one for common expressions, one for statements, but also one for `_Complex` stuff, etc. Does that sound better?

**Comment by tbaederr** [comment]
Ping

**Review by AaronBallman — COMMENTED** [review]
Splitting the code across a few implementation files might be a reasonable approach, but in general, I'm fine with how this is proceeding.

I reviewed the changes as best I could and they seem reasonable to me.

**Review by AaronBallman — APPROVED** [review]
LGTM

**Comment by tbaederr** [comment]
That failure looks like it's just a case of https://github.com/llvm/llvm-project/issues/54972

**Pull request merged**
