### PR TITLE
[CostModel][X86] Fix fpext conversion cost for 16 elements

### PR DESCRIPTION
**Pull request by HaohaiWen**
The fpext conversion cost for 16 elements should be 4 from Znver4.

### CODE REVIEW

**Comment by HaohaiWen** [comment]
This PR should be landed after https://github.com/llvm/llvm-project/pull/76277

**Comment by HaohaiWen** [comment]
```
 $cat test.ll
define <8 x double> @foo8(<8 x float> %in) {
  %1 = fpext <8 x float> %in to <8 x double>
  ret <8 x double> %1
}

define <16 x double> @foo16(<16 x float> %in) {
  %1 = fpext <16 x float> %in to <16 x double>
  ret <16 x double> %1
}

```
 $llc test.ll -mtriple=x86_64-unknown-unknown -mattr=avx512f -o -
```
        .text
        .file   "test.ll"
        .globl  foo8                            # -- Begin function foo8
        .p2align        4, 0x90
        .type   foo8,@function
foo8:                                   # @foo8
        .cfi_startproc
# %bb.0:
        vcvtps2pd       %ymm0, %zmm0
        retq
.Lfunc_end0:
        .size   foo8, .Lfunc_end0-foo8
        .cfi_endproc
                                        # -- End function
        .globl  foo16                           # -- Begin function foo16
        .p2align        4, 0x90
        .type   foo16,@function
foo16:                                  # @foo16
        .cfi_startproc
# %bb.0:
        vcvtps2pd       %ymm0, %zmm2
        vextractf64x4   $1, %zmm0, %ymm0
        vcvtps2pd       %ymm0, %zmm1
        vmovaps %zmm2, %zmm0
        retq
.Lfunc_end1:
        .size   foo16, .Lfunc_end1-foo16
        .cfi_endproc
                                        # -- End function
        .section        ".note.GNU-stack","",@progbits

```
uiCA measured its TP is 5 for SKX. https://bit.ly/3rGcUKF

**Comment by RKSimon** [comment]
Please can you confirm this as llvm-mca predicts worse case (znver4) to be 4

**Comment by HaohaiWen** [comment]
> Please can you confirm this as llvm-mca predicts worse case (znver4) to be 4 https://llvm.godbolt.org/z/fxWTaf3Gv

Currenttly, uiCA don't support Zen4 and I don't have Zen4 machine.
I can measure it on local SKX machine with nanoBench (https://github.com/andreas-abel/nanoBench). Maybe you can use it to confirm Zen4 cost if you do have Zen4 machine. 
e.g.
```
./nanoBench.sh -init "xor zmm0, zmm0" -asm "vcvtps2pd zmm2, ymm0; vextractf64x4 ymm0, zmm0, 1; vcvtps2pd zmm1, ymm0" -config configs/cfg_SkylakeX_common.txt -unroll 1000 -loop 1000 -warm_up_count 10 -cpu 0
Note: Hyper-threading is enabled; it can be disabled with "sudo ./disable-HT.sh"
CORE_CYCLES: 4.77
INST_RETIRED: 3.00
IDQ.MITE_UOPS: 5.71
IDQ.DSB_UOPS: -0.70
IDQ.MS_UOPS: 0.01
LSD.UOPS: 0.00
UOPS_ISSUED: 5.01
UOPS_EXECUTED: 5.01
UOPS_RETIRED.RETIRE_SLOTS: 5.01
UOPS_DISPATCHED_PORT.PORT_0: 2.00
UOPS_DISPATCHED_PORT.PORT_1: 0.00
UOPS_DISPATCHED_PORT.PORT_2: 0.00
UOPS_DISPATCHED_PORT.PORT_3: 0.00
UOPS_DISPATCHED_PORT.PORT_4: 0.00
UOPS_DISPATCHED_PORT.PORT_5: 3.00
UOPS_DISPATCHED_PORT.PORT_6: 0.00
UOPS_DISPATCHED_PORT.PORT_7: 0.00

```

**Comment by RKSimon** [comment]
I meant - llvm-mca currently says the throughput for skylake etc. is 3cy not 5cy - so do you know why the intel scheduler models are underestimating the throughput?

**Comment by HaohaiWen** [comment]
> I meant - llvm-mca currently says the throughput for skylake etc. is 3cy not 5cy - so do you know why the intel scheduler models are underestimating the throughput?

SKX schedule model reports correct lat/uops/tpt for each instruction.
vcvtps2pd: https://uops.info/html-instr/VCVTPS2PD_ZMM_YMM.html#SKX
```
Instruction		                      Lat	        TP	Uops	Ports
VEXTRACTF64X4 (YMM, ZMM, I8)	AVX512EVEX	3	1.00 / 1.00	1 / 1	 1*p5
```
vextractf64x4: https://uops.info/html-instr/VEXTRACTF64X4_YMM_ZMM_I8.html#SKX
```
Instruction		                 Lat	         TP	Uops	Ports
VCVTPS2PD (ZMM, YMM)	AVX512EVEX	7	1.00 / 1.09	2 / 2  	1*p05+1*p5
```

There're totally 5 uops, 3 for p5 and 2 for p05. I guess mca thought those 3\*p5 and 2\*p05 can run in parallel.
We can see 2\*p05 indeed went to p0 from nanoBench result. Looks like there're some dependencies and they can't ideally run parallelly. I don't know uiCA analyzed it.

**Comment by HaohaiWen** [comment]
There's cross iteration true dependency in previous experiment.
```
vcvtps2pd zmm2, ymm0
vextractf64x4 ymm0, zmm0, 1
vcvtps2pd zmm1, ymm0
```
The second cvt and first cvt of the next iteration need to wait for finish of vextract64x4. Therefore its cost is 5.
In real scenario, value of zmm0 should be reset to fpext new input.
```
vmovaps zmm0, zmm3
vcvtps2pd zmm2, ymm0
vextractf64x4 ymm0, zmm0, 1
vcvtps2pd zmm1, ymm0
```
This breaks the dependency and now cost is 3.
```
# ./nanoBench.sh -init "xor zmm0, zmm0" -asm "vmovaps zmm0, zmm3; vcvtps2pd zmm2, ymm0; vextractf64x4 ymm0, zmm0, 1; vcvtps2pd zmm1, ymm0" -config configs/cfg_SkylakeX_common.txt -unroll 1000 -loop 1000 -warm_up_count 10 -cpu 0
Note: Hyper-threading is enabled; it can be disabled with "sudo ./disable-HT.sh"
CORE_CYCLES: 3.00
INST_RETIRED: 4.00
IDQ.MITE_UOPS: 6.46
IDQ.DSB_UOPS: -0.45
IDQ.MS_UOPS: 0.01
LSD.UOPS: 0.00
UOPS_ISSUED: 6.01
UOPS_EXECUTED: 5.01
UOPS_RETIRED.RETIRE_SLOTS: 6.01
UOPS_DISPATCHED_PORT.PORT_0: 2.00
UOPS_DISPATCHED_PORT.PORT_1: 0.00
UOPS_DISPATCHED_PORT.PORT_2: 0.00
UOPS_DISPATCHED_PORT.PORT_3: 0.00
UOPS_DISPATCHED_PORT.PORT_4: 0.00
UOPS_DISPATCHED_PORT.PORT_5: 3.00
UOPS_DISPATCHED_PORT.PORT_6: 0.01
UOPS_DISPATCHED_PORT.PORT_7: 0.00
```

**Comment by RKSimon** [comment]
Got it thanks - given znver4 now has the worst cost, we should be setting the cost to 4

**Review by RKSimon — APPROVED** [review]
LGTM - cheers!

**Pull request merged**
