### PR TITLE
[libc++] Allow for hardening in multiple categories

### PR DESCRIPTION
**Pull request by hawkinsw**
Allow multiple categories for hardening assertions.

### CODE REVIEW

**Comment by hawkinsw** [comment]
@var-const I thought it would be cool to allow for assertions to be in multiple categories. I worked up a quick sample of how that could look. Obviously I didn't go too far because I wanted to get your thoughts. There are a ton of open questions about this (not the least of which is whether or not the macro would always compile to 0 overhead). But, I thought it might be a cool option to be able to have assertions in multiple categories. If you want me to continue to iterate, please let me know! I love helping!

Will

**Comment by hawkinsw** [comment]
@var-const  Spent lots of time attempting to make this better but didn't get very far. I made a few minor tweaks. I hope that this is something that might be of use.

**Comment by hawkinsw** [comment]
@var-const Hope things are going well. If you think something like this is useful/interesting, just let me know and I will attempt to pursue it!

**Comment by var-const** [comment]
(@hawkinsw Very sorry about the slow reply, I'm just catching up on the reviews)

It's an interesting idea, thanks for working on this! Personally, I would postpone this until we have a use case. The current model we have, where assertions are classified across a single axis (even if that axis takes multiple factors into account), while perhaps limited, has the advantage of being simple. That makes understanding which assertion categories go into which modes easier. If we start running into cases where it just feels natural to start essentially tagging assertions, or if we come up with use cases where people want modes grouped around orthogonal criteria, we could revisit this patch and use this mechanism to implement that. Until we have specific use cases, however, I think let's try to keep things as simple as possible. The less modes we support, the easier it is for us to reason about what is the exact effect of each mode and what kind of (best effort) guarantees it provides.

**Comment by hawkinsw** [comment]
> (@hawkinsw Very sorry about the slow reply, I'm just catching up on the reviews)
> 
> It's an interesting idea, thanks for working on this! Personally, I would postpone this until we have a use case. The current model we have, where assertions are classified across a single axis (even if that axis takes multiple factors into account), while perhaps limited, has the advantage of being simple. That makes understanding which assertion categories go into which modes easier. If we start running into cases where it just feels natural to start essentially tagging assertions, or if we come up with use cases where people want modes grouped around orthogonal criteria, we could revisit this patch and use this mechanism to implement that. Until we have specific use cases, however, I think let's try to keep things as simple as possible. The less modes we support, the easier it is for us to reason about what is the exact effect of each mode and what kind of (best effort) guarantees it provides.

As I mentioned in DM with you, *please* do not apologize! I appreciate and agree with everything that you have said here. I will pull back this PR until such time as we would like to have the capability to harden over multiple categories. I was suggesting it really to get your feedback on its technical merit. So, thank you for validating that the technical would be valid. 

Thank you for all you do!

**Pull request closed without merging**
