### PR TITLE
Reland [MLIR] Make resolveCallable customizable in CallOpInterface

### PR DESCRIPTION
**Pull request by xlauko**
Relands #100361 with fixed dependencies.

### CODE REVIEW

**Comment by joker-eph** [comment]
Why are these needed? In which situation do they fail? Is this a non-deterministic build failure? (if so can you post the error message).

**Comment by joker-eph** [comment]
Is this a follow-up to https://github.com/llvm/llvm-project/pull/100361 ? If so it has been reverted and you can incorporate these fixes when you reland it. Thanks!

(if a bot is broken: we need to either land such fix immediately or revert in the meantime to unbreak the CI)

**Comment by xlauko** [comment]
@joker-eph yes, this was follow-up to https://github.com/llvm/llvm-project/pull/100361 
To reland it should I just reapply the original commit?

**Comment by joker-eph** [comment]
The original commit, with the fixes :)

**Review by matthias-springer — APPROVED** [review]

**Pull request merged**
