### PR TITLE
[mlir][spirv] Add atan and atan2 pattern to MathToSPIRV Conversion pass

### PR DESCRIPTION
**Pull request by catnipsy**
Add missing math.atan to spirv.CL.atan and math.atan2 to spirv.CL.atan2 in MathToSPIRV.
Add math.atan to spirv.GL.atan too.

### CODE REVIEW

**Review by kuhar — DISMISSED** [review]

**Review by kuhar — COMMENTED** [review]
Could we add glsl support in one sweep?
https://registry.khronos.org/SPIR-V/specs/unified1/GLSL.std.450.html#:~:text=%3Cid%3E%0Ax-,Atan%0A%0AArc%20tangent,-.%20Result%20is%20an

**Comment by meehatpa** [comment]
> Could we add glsl support in one sweep? https://registry.khronos.org/SPIR-V/specs/unified1/GLSL.std.450.html#:~:text=%3Cid%3E%0Ax-,Atan%0A%0AArc%20tangent,-.%20Result%20is%20an

I updated it for glsl only for atan as atan2 op is not available in spirv.
Thanks for the quick review!

**Comment by kuhar** [comment]
> > Could we add glsl support in one sweep? https://registry.khronos.org/SPIR-V/specs/unified1/GLSL.std.450.html#:~:text=%3Cid%3E%0Ax-,Atan%0A%0AArc%20tangent,-.%20Result%20is%20an
> 
> I updated it for glsl only for atan as atan2 op is not available in spirv. Thanks for the quick review!

Can we use this one: https://registry.khronos.org/SPIR-V/specs/unified1/GLSL.std.450.html#:~:text=Atan2%0A%0AArc%20tangent.%20Result%20is%20an%20angle ?

**Comment by meehatpa** [comment]
> > > Could we add glsl support in one sweep? https://registry.khronos.org/SPIR-V/specs/unified1/GLSL.std.450.html#:~:text=%3Cid%3E%0Ax-,Atan%0A%0AArc%20tangent,-.%20Result%20is%20an
> > 
> > 
> > I updated it for glsl only for atan as atan2 op is not available in spirv. Thanks for the quick review!
> 
> Can we use this one: https://registry.khronos.org/SPIR-V/specs/unified1/GLSL.std.450.html#:~:text=Atan2%0A%0AArc%20tangent.%20Result%20is%20an%20angle ?

The issue is it is not available in spirv mlir dialect https://mlir.llvm.org/docs/Dialects/SPIR-V/. We would need to add that for op in the dialect first.

**Review by kuhar — APPROVED** [review]

**Comment by meehatpa** [comment]
@kuhar would you please merge?

**Comment by kuhar** [comment]
> @kuhar would you please merge?

Done

**Pull request merged**
