### PR TITLE
[hwasan] Update dbg.assign intrinsics in HWAsan pass

### LINKED ISSUE #76545: HWASAN: No DW_OP_LLVM_tag_offset with opt above -O0
DW_OP_LLVM_tag_offset is present in -O0, but not -O1 https://godbolt.org/z/3dj6bzz4z

Reasons is `AssignmentTrackingPass` and `-instcombine-lower-dbg-declare` replace `@llvm.dbg.declare` with `@llvm.dbg.assign` but we don't attach DW_OP_LLVM_tag_offset to `@llvm.dbg.assign`.

### PR DESCRIPTION
**Pull request by OCHyams**
llvm.dbg.assign intrinsics have 2 {value, expression} pairs; fix hwasan to
update the second expression.

The DWARF output looks correct (see the AArch64 tests) as far as I can tell.

Fixes #76545

### CODE REVIEW

**Review by vitalybuka — APPROVED** [review]
Thank you!

LGTM, but looks CI complains about:
LVM :: CodeGen/AArch64/dbg-assign-tag-offset.ll
LLVM :: DebugInfo/Generic/assignment-tracking/declare-to-assign/hwasan.ll

**Comment by OCHyams** [comment]
Reapplied in [7616071](https://github.com/llvm/llvm-project/commit/76160718df7c1f31ff50a4964d749c2b9d83f9cf), softening the assertion `assert(DAI->getAddress() == AI);` to an if-check, because the DbgAssignIntrinsic might be using the Alloca in the value-component only (in which case DAI->getAddress() != AI).

**Comment by gulfemsavrun** [comment]
We started seeing an assertion failure in `emitDbgValue` function `CodeGen` in our Clang Linux builders, and I bisected to this commit:
```
FAILED: libcxxabi/src/CMakeFiles/cxxabi_static_objects.dir/cxa_vector.cpp.obj 
/b/s/w/ir/x/w/llvm_build/./bin/clang++ --target=aarch64-unknown-fuchsia --sysroot=/b/s/w/ir/x/w/sdk/arch/arm64/sysroot -DHAVE___CXA_THREAD_ATEXIT_IMPL -DLIBCXX_BUILDING_LIBCXXABI -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS="" -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCXXABI_BUILDING_LIBRARY -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/b/s/w/ir/x/w/llvm-llvm-project/libunwind/include -I/b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/../libcxx/src -I/b/s/w/ir/x/w/llvm_build/include/aarch64-unknown-fuchsia/c++/v1 -I/b/s/w/ir/x/w/llvm_build/include/c++/v1 -I/b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/include --target=aarch64-unknown-fuchsia -I/b/s/w/ir/x/w/sdk/pkg/sync/include -I/b/s/w/ir/x/w/sdk/pkg/fdio/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fno-omit-frame-pointer -fsanitize=hwaddress -ffunction-sections -fdata-sections -ffile-prefix-map=/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-fuchsia+hwasan-bins=../../../llvm-llvm-project -ffile-prefix-map=/b/s/w/ir/x/w/llvm-llvm-project/= -no-canonical-prefixes  -O2 -g -DNDEBUG -std=c++2b -nostdinc++ -fstrict-aliasing -funwind-tables -D_DEBUG -UNDEBUG -Wall -Wextra -Wnewline-eof -Wshadow -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wextra-semi -Wundef -Wunused-template -Wformat-nonliteral -Wno-user-defined-literals -Wno-covered-switch-default -Wno-suggest-override -Wno-error -fvisibility=hidden -MD -MT libcxxabi/src/CMakeFiles/cxxabi_static_objects.dir/cxa_vector.cpp.obj -MF libcxxabi/src/CMakeFiles/cxxabi_static_objects.dir/cxa_vector.cpp.obj.d -o libcxxabi/src/CMakeFiles/cxxabi_static_objects.dir/cxa_vector.cpp.obj -c /b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/src/cxa_vector.cpp
clang++: llvm/lib/CodeGen/AssignmentTrackingAnalysis.cpp:1506: void (anonymous namespace)::AssignmentTrackingLowering::emitDbgValue(AssignmentTrackingLowering::LocKind, const DbgVariableIntrinsic *, Instruction *): Assertion `!Expr->getFragmentInfo() && "fragment info should be stored in value-expression only"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /b/s/w/ir/x/w/llvm_build/./bin/clang++ --target=aarch64-unknown-fuchsia --sysroot=/b/s/w/ir/x/w/sdk/arch/arm64/sysroot -DHAVE___CXA_THREAD_ATEXIT_IMPL -DLIBCXX_BUILDING_LIBCXXABI -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS= -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCXXABI_BUILDING_LIBRARY -D_LIBCXXABI_DISABLE_VISIBILITY_ANNOTATIONS -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/b/s/w/ir/x/w/llvm-llvm-project/libunwind/include -I/b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/../libcxx/src -I/b/s/w/ir/x/w/llvm_build/include/aarch64-unknown-fuchsia/c++/v1 -I/b/s/w/ir/x/w/llvm_build/include/c++/v1 -I/b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/include --target=aarch64-unknown-fuchsia -I/b/s/w/ir/x/w/sdk/pkg/sync/include -I/b/s/w/ir/x/w/sdk/pkg/fdio/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fno-omit-frame-pointer -fsanitize=hwaddress -ffunction-sections -fdata-sections -ffile-prefix-map=/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-fuchsia+hwasan-bins=../../../llvm-llvm-project -ffile-prefix-map=/b/s/w/ir/x/w/llvm-llvm-project/= -no-canonical-prefixes -O2 -g -DNDEBUG -std=c++2b -nostdinc++ -fstrict-aliasing -funwind-tables -D_DEBUG -UNDEBUG -Wall -Wextra -Wnewline-eof -Wshadow -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wextra-semi -Wundef -Wunused-template -Wformat-nonliteral -Wno-user-defined-literals -Wno-covered-switch-default -Wno-suggest-override -Wno-error -fvisibility=hidden -MD -MT libcxxabi/src/CMakeFiles/cxxabi_static_objects.dir/cxa_vector.cpp.obj -MF libcxxabi/src/CMakeFiles/cxxabi_static_objects.dir/cxa_vector.cpp.obj.d -o libcxxabi/src/CMakeFiles/cxxabi_static_objects.dir/cxa_vector.cpp.obj -c /b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/src/cxa_vector.cpp
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/src/cxa_vector.cpp'.
4.	Running pass 'Assignment Tracking Analysis' on function '@__cxa_vec_new'
#0 0x000055b174015938 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/b/s/w/ir/x/w/llvm_build/./bin/clang+++0x8715938)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Fuchsia clang version 18.0.0git (https://llvm.googlesource.com/llvm-project 02f95b77515fe18ed1076b94cbb850ea0cf3c77e)
Target: aarch64-unknown-fuchsia
Thread model: posix
InstalledDir: /b/s/w/ir/x/w/llvm_build/./bin
clang++: note: diagnostic msg: 
```

https://logs.chromium.org/logs/fuchsia/buildbucket/cr-buildbucket/8758181086086431185/+/u/clang/build/stdout

**Comment by OCHyams** [comment]
Thanks, please feel free to revert the patch (it's out of hours for me right now)

**Comment by gulfemsavrun** [comment]
> Thanks, please feel free to revert the patch (it's out of hours for me right now)
Thank you. I just reverted it, and please let me know if you need any help to reproduce the issue before relanding with a fix.

**Comment by OCHyams** [comment]
I managed to reproduce it locally and have pushed a fixed patch 13c6f1ea2e7eb15fe492d8fca4fa1857c6f86370.

The issue was caused by using `getExpression()` rather than `getAddressExpression()` to get the expression to prepend (which is then used to set the address expression). I've updated the test `llvm/test/Instrumentation/HWAddressSanitizer/dbg-assign-tag-offset.ll` to check this doesn't happen.

**Comment by gulfemsavrun** [comment]
> I managed to reproduce it locally and have pushed a fixed patch [13c6f1e](https://github.com/llvm/llvm-project/commit/13c6f1ea2e7eb15fe492d8fca4fa1857c6f86370).
> 
> The issue was caused by using `getExpression()` rather than `getAddressExpression()` to get the expression to prepend (which is then used to set the address expression). I've updated the test `llvm/test/Instrumentation/HWAddressSanitizer/dbg-assign-tag-offset.ll` to check this doesn't happen.

Thanks for the fix, but it caused a new assertion error `((!Expr->isImplicit() || CanSplitValue) && "Expr can't be split"' failed.)`:
```
FAILED: libcxxabi/src/CMakeFiles/cxxabi_shared_objects.dir/private_typeinfo.cpp.obj 
/b/s/w/ir/x/w/llvm_build/./bin/clang++ --target=aarch64-unknown-fuchsia --sysroot=/b/s/w/ir/x/w/sdk/arch/arm64/sysroot -DHAVE___CXA_THREAD_ATEXIT_IMPL -DLIBCXX_BUILDING_LIBCXXABI -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCXXABI_BUILDING_LIBRARY -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/b/s/w/ir/x/w/llvm-llvm-project/libunwind/include -I/b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/../libcxx/src -I/b/s/w/ir/x/w/llvm_build/include/aarch64-unknown-fuchsia/c++/v1 -I/b/s/w/ir/x/w/llvm_build/include/c++/v1 -I/b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/include --target=aarch64-unknown-fuchsia -I/b/s/w/ir/x/w/sdk/pkg/sync/include -I/b/s/w/ir/x/w/sdk/pkg/fdio/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fno-omit-frame-pointer -fsanitize=hwaddress -ffunction-sections -fdata-sections -ffile-prefix-map=/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-fuchsia+hwasan-bins=../../../llvm-llvm-project -ffile-prefix-map=/b/s/w/ir/x/w/llvm-llvm-project/= -no-canonical-prefixes  -O2 -g -DNDEBUG -std=c++2b -fPIC -nostdinc++ -fstrict-aliasing -funwind-tables -D_DEBUG -UNDEBUG -Wall -Wextra -Wnewline-eof -Wshadow -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wextra-semi -Wundef -Wunused-template -Wformat-nonliteral -Wno-user-defined-literals -Wno-covered-switch-default -Wno-suggest-override -Wno-error -MD -MT libcxxabi/src/CMakeFiles/cxxabi_shared_objects.dir/private_typeinfo.cpp.obj -MF libcxxabi/src/CMakeFiles/cxxabi_shared_objects.dir/private_typeinfo.cpp.obj.d -o libcxxabi/src/CMakeFiles/cxxabi_shared_objects.dir/private_typeinfo.cpp.obj -c /b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/src/private_typeinfo.cpp
clang++: llvm/lib/IR/DebugInfoMetadata.cpp:1968: static std::optional<DIExpression *> llvm::DIExpression::createFragmentExpression(const DIExpression *, unsigned int, unsigned int): Assertion `(!Expr->isImplicit() || CanSplitValue) && "Expr can't be split"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.	Program arguments: /b/s/w/ir/x/w/llvm_build/./bin/clang++ --target=aarch64-unknown-fuchsia --sysroot=/b/s/w/ir/x/w/sdk/arch/arm64/sysroot -DHAVE___CXA_THREAD_ATEXIT_IMPL -DLIBCXX_BUILDING_LIBCXXABI -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCXXABI_BUILDING_LIBRARY -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/b/s/w/ir/x/w/llvm-llvm-project/libunwind/include -I/b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/../libcxx/src -I/b/s/w/ir/x/w/llvm_build/include/aarch64-unknown-fuchsia/c++/v1 -I/b/s/w/ir/x/w/llvm_build/include/c++/v1 -I/b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/include --target=aarch64-unknown-fuchsia -I/b/s/w/ir/x/w/sdk/pkg/sync/include -I/b/s/w/ir/x/w/sdk/pkg/fdio/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fno-omit-frame-pointer -fsanitize=hwaddress -ffunction-sections -fdata-sections -ffile-prefix-map=/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-fuchsia+hwasan-bins=../../../llvm-llvm-project -ffile-prefix-map=/b/s/w/ir/x/w/llvm-llvm-project/= -no-canonical-prefixes -O2 -g -DNDEBUG -std=c++2b -fPIC -nostdinc++ -fstrict-aliasing -funwind-tables -D_DEBUG -UNDEBUG -Wall -Wextra -Wnewline-eof -Wshadow -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wextra-semi -Wundef -Wunused-template -Wformat-nonliteral -Wno-user-defined-literals -Wno-covered-switch-default -Wno-suggest-override -Wno-error -MD -MT libcxxabi/src/CMakeFiles/cxxabi_shared_objects.dir/private_typeinfo.cpp.obj -MF libcxxabi/src/CMakeFiles/cxxabi_shared_objects.dir/private_typeinfo.cpp.obj.d -o libcxxabi/src/CMakeFiles/cxxabi_shared_objects.dir/private_typeinfo.cpp.obj -c /b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/src/private_typeinfo.cpp
1.	<eof> parser at end of file
2.	Code generation
3.	Running pass 'Function Pass Manager' on module '/b/s/w/ir/x/w/llvm-llvm-project/libcxxabi/src/private_typeinfo.cpp'.
4.	Running pass 'Assignment Tracking Analysis' on function '@_ZNK10__cxxabiv117__class_type_info9can_catchEPKNS_16__shim_type_infoERPv'
#0 0x0000561d3a3a0b78 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/b/s/w/ir/x/w/llvm_build/./bin/clang+++0x8743b78)
clang++: error: clang frontend command failed with exit code 134 (use -v to see invocation)
Fuchsia clang version 18.0.0git (https://llvm.googlesource.com/llvm-project 5daf674feba0f57b083113ad7ed486cad433a916)
Target: aarch64-unknown-fuchsia
Thread model: posix
InstalledDir: /b/s/w/ir/x/w/llvm_build/./bin
clang++: note: diagnostic msg: 
********************
```

https://logs.chromium.org/logs/fuchsia/buildbucket/cr-buildbucket/8758111613576762817/+/u/clang/build/stdout

**Comment by OCHyams** [comment]
I can't work out how to change the status from "merged". I've opened a new pull request #79864 which includes handling for DPValue assigns, and depends on #79816 for the assertion fix.

**Pull request merged**
