### PR TITLE
[TargetLowering] remove unused virtual from ComputeConstraintToUse

### PR DESCRIPTION
**Pull request by nickdesaulniers**
There are no overrides in tree.

Fix up resulting linkage failures in unittests and sort the dependency
lists.

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
IIUC, looks like I need to fix the cmake rules for `llvm-extract` as well.
```
8367/9684] Linking CXX executable bin\llvm-extract.exe
--
  | FAILED: bin/llvm-extract.exe
```

**Comment by nickdesaulniers** [comment]
are there gn or bazel files that need to updated, too?

**Review by mtrofin — APPROVED** [review]

**Comment by nickdesaulniers** [comment]
polly\unittests\ needs this as well...

**Comment by nickdesaulniers** [comment]
@petrhosek do you think there's a better way than adding these linkage dependencies? Perhaps some definitions need to be moved from somewhere to somewhere else? Perhaps that's a bigger yak shave?

**Comment by petrhosek** [comment]
> @petrhosek do you think there's a better way than adding these linkage dependencies? Perhaps some definitions need to be moved from somewhere to somewhere else? Perhaps that's a bigger yak shave?

Do you know where is the dependency on `ComputeConstraintToUse` coming from in all those targets?

**Comment by nickdesaulniers** [comment]
@rnk found https://reviews.llvm.org/D140893 which may have inadvertently exposed a layering violation between Passes and Codegen.

cc @aeubanks @sparker-arm

**Comment by rnk** [comment]
I'd say that we have an unwanted dependency between Passes and CodeGen as a result of the codegen pass NPM work. IR-only tools like llvm-extract now depend on CodeGen. Fixing that would be nice conceptually, but it might not be high priority, and it's not creating fragility.

The layering issue is that CodeGen has a header dependency on SelectionDAG without having a library link dependency on it. CodeGenPrepare calls ComputeConstraintToUse, which is defined in SelectionDAG:
https://github.com/llvm/llvm-project/blob/main/llvm/lib/CodeGen/CodeGenPrepare.cpp#L5024

If you make the virtual call direct, it results in a linker error. This code can't execute at runtime if you don't link in any targets that implement TargetLowering anyway, llvm-extract just depends on it transitively.

I'm not sure what the next step is, I think I touched this before and looked the other way.

**Comment by nickdesaulniers** [comment]
I don't have time to follow up on this. Closing.

**Pull request closed without merging**
