### PR TITLE
Fix typos

### PR DESCRIPTION
**Pull request by ViToni**

### CODE REVIEW

**Review by steakhal — APPROVED** [review]
LGTM

**Comment by michaelrj-google** [comment]
Libc change LGTM

**Review by nickdesaulniers — APPROVED** [review]

**Comment by nickdesaulniers** [comment]
Thanks for the patch. Do you need one of us to merge this for you?

**Comment by ViToni** [comment]
@nickdesaulniers Please. I wouldn't assume to have any permissions in this repo.

**Pull request merged**
