### PR TITLE
[mlir][vector] Remove `vector.reshape` operation

### PR DESCRIPTION
**Pull request by MacDue**
This operation was added five years ago and has no lowerings or uses within upstream MLIR (and no reported uses downstream). There’s only a handful of round-trip tests.

See related RFC:
https://discourse.llvm.org/t/rfc-should-vector-reshape-be-removed/80478/3

### CODE REVIEW

**Comment by rengolin** [comment]
Do we have some place (changelog) to announce removals?

**Comment by jpienaar** [comment]
We have https://mlir.llvm.org/deprecation/ too

**Review by kuhar — APPROVED** [review]

**Review by dcaballe — APPROVED** [review]
Thanks!

**Review by banach-space — APPROVED** [review]
Less code to maintain, thanks Ben! LGTM

**Review by rengolin — APPROVED** [review]

**Comment by rengolin** [comment]
> We have https://mlir.llvm.org/deprecation/ too

Would be nice to add a change in this PR there

**Comment by MacDue** [comment]
> > We have https://mlir.llvm.org/deprecation/ too
> 
> Would be nice to add a change in this PR there

I've drafted a notice for LLVM 20 here https://github.com/llvm/mlir-www/pull/198 (since this won't make the LLVM 19 release).

**Comment by MacDue** [comment]
Landing this now. If anyone objects feel free to revert :slightly_smiling_face:

**Pull request merged**
