### PR TITLE
[clang][analyzer] Check for label location bindings in `DereferenceChecker`

### LINKED ISSUE #89264: [analyzer] Dereference checker should check binds on label locations
Consider the following input:

```c++
// RUN: %clang_analyze_cc1 -analyzer-checker=core,debug.ExprInspection -verify %s

void clang_analyzer_dump(char);
void clang_analyzer_dump_ptr(char*);

// https://github.com/llvm/llvm-project/issues/89185
void binding_to_label_loc() {
  char *b = &&MyLabel;
MyLabel:
  *b = 0; // no-crash
  clang_analyzer_dump_ptr(b); // expected-warning {{&&MyLabel}}
  clang_analyzer_dump(*b); // expected-warning {{Unknown}}
  // FIXME: We should never get here, as the dereference checker should have caught the binding operation to the label location.
}
```

One should never store values to the addresses of labels.
I think the closest checker is the Dereference checker, which could check for label locs after it checked for undefined locations.
Like this:
```diff
diff --git a/clang/lib/StaticAnalyzer/Checkers/DereferenceChecker.cpp b/clang/lib/StaticAnalyzer/Checkers/DereferenceChecker.cpp
@@ -287,6 +287,12 @@ void DereferenceChecker::checkBind(SVal L, SVal V, const Stmt *S,
   if (V.isUndef())
     return;
 
+  // One should never write to label addresses.
+  if (auto Label = L.getAs<loc::GotoLabel>()) {
+    llvm::errs() << "WRITING TO LABEL: " << L << "\n";
+    // TODO: report a fatal issue like: "Dereference of the address of a label"
+  }
+
   const MemRegion *MR = L.getAsRegion();
   const TypedValueRegion *TVR = dyn_cast_or_null<TypedValueRegion>(MR);
   if (!TVR)
```

### PR DESCRIPTION
**Pull request by Rajveer100**
Resolves #89264

Values should not be stored in addresses of labels, this throws a fatal error when this happens.

### CODE REVIEW

**Comment by Rajveer100** [comment]
@steakhal

**Review by steakhal — CHANGES_REQUESTED** [review]
The `llvm::errs()` are for only debugging stuff. The print to the stderr.
However, to form a bug report you need to use the `reportBug` here, and you also need to define a new `BugType` for representing this bug kind.
Once that's done, you should have a fatal bug report at the dereference location, causing the path to sink and never reach the next statement where we would dump the value associated with that variable.

The test is already present in the tree, as `clang/test/Analysis/gh-issue-89185.c`.
If you implementation is correct, that test should fail because we report a new bug there.

**Comment by steakhal** [comment]
> Should we introduce a new Kind in `DerefKind` (in reference to `DereferenceChecker::reportBug`) ?

Yes. Something like this should work:
```c++
BugType BT_Label{this, "Dereference of the address of a label", categories::LogicError};
```

**Comment by Rajveer100** [comment]
I am not sure what causes the build failure here.

**Comment by steakhal** [comment]
This one looks good to me. I wanna hear your opinion @NagyDonat

**Review by steakhal — APPROVED** [review]

**Review by NagyDonat — APPROVED** [review]
LGTM.

My only significant observation is that `BugReporterVisitors.cpp` must be cleaned up eventually, as it is currently a heap of ad-hoc special cases. However, it would be unreasonable to wait for that difficult cleanup with this simple improvement, so it's reasonable that you add yet another special case that ensures that your example works as intended.

**Pull request merged**
