### PR TITLE
SystemZ release notes for 18.x.

### PR DESCRIPTION
**Pull request by JonPsson1**

### CODE REVIEW

**Comment by JonPsson1** [comment]
Looks like https://github.com/llvm/llvm-project/pull/73511 "munaligned-symbols" 34dd8ec never made it into the 18-release branch...

**Comment by uweigand** [comment]
> Looks like #73511 "munaligned-symbols" 34dd8ec never made it into the 18-release branch...

Ah OK, I had missed that.

**Review by uweigand — APPROVED** [review]
LGTM, thanks!

**Comment by JonPsson1** [comment]
@tstellar This is intended for the 18-rel branch...

**Pull request merged**
