### PR TITLE
[compiler-rt][Fuzzer] SetThreadName windows implementation new try.

### PR DESCRIPTION
**Pull request by devnexen**
SetThreadDescription symbol needs to be dynamically loaded before usage. Then using a wide string buffer, since we re using a null terminated string, we can use MultiByteToWideChar -1 as 4th argument to finally set the thread name.

Previously `SetThreadDescription` was called directly causing crash.
It was reverted in dd3aa26fc8e9de37a39611f7a6a602bcb4153784

### CODE REVIEW

**Comment by vitalybuka** [comment]
Can you please include into description # of the prev attempt?

**Comment by vitalybuka** [comment]
Note, PR github description, not commit, will be used, if PR is pushed web UI

**Comment by vitalybuka** [comment]
Can you please include into description the PR# pr commit of the previous attempt?

**Comment by vitalybuka** [comment]
> Can you please include into description the PR# pr commit of the previous attempt?

I added revert patch into description. Just to help to see improvement vs prev version.

**Review by vitalybuka — APPROVED** [review]

**Comment by glandium** [comment]
This interestingly broken our compiler-rt builds downstream:
```
[task 2024-03-01T02:17:28.933Z] /builds/worker/fetches/clang/bin/clang-cl --target=x86_64-pc-windows-msvc  /nologo -TP  -I/builds/worker/fetches/llvm-project/compiler-rt/lib/fuzzer/../../include -D_CRT_SECURE_NO_WARNINGS --target=x86_64-windows-msvc -fms-compatibility-version=19.27 -vctoolsversion 14.29.30133 -winsdkversion 10.0.19041.0 -winsysroot /builds/worker/fetches/vs -Xclang -ivfsoverlay -Xclang /builds/worker/build/winsdk_vfs_overlay.yaml /DWIN32 /D_WINDOWS /EHsc /W4 -Wno-unused-parameter /O2 /Ob2 /DNDEBUG -MT -fno-builtin -fno-sanitize=safe-stack -fno-lto /Oy- /GS- /Zc:threadSafeInit- -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta /Z7 -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions /wd4146 /wd4291 /wd4391 /wd4722 /wd4800 -D_HAS_EXCEPTIONS=0 -std:c++17 /showIncludes /Folib/fuzzer/CMakeFiles/RTfuzzer.x86_64.dir/FuzzerUtilWindows.cpp.obj /Fdlib/fuzzer/CMakeFiles/RTfuzzer.x86_64.dir/ -c -- /builds/worker/fetches/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtilWindows.cpp
[task 2024-03-01T02:17:28.933Z] In file included from /builds/worker/fetches/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtilWindows.cpp:21:
[task 2024-03-01T02:17:28.933Z] In file included from /builds/worker/fetches/vs/Windows Kits/10/Include/10.0.19041.0/um/libloaderapi.h:18:
[task 2024-03-01T02:17:28.933Z] In file included from /builds/worker/fetches/vs/Windows Kits/10/Include/10.0.19041.0/shared/minwindef.h:182:
[task 2024-03-01T02:17:28.933Z] /builds/worker/fetches/vs/Windows Kits/10/Include/10.0.19041.0/um/winnt.h(173,2): error: "No Target Architecture"
[task 2024-03-01T02:17:28.933Z]   173 | #error "No Target Architecture"
[task 2024-03-01T02:17:28.933Z]       |  ^
```

Interestingly, the contents of winnt.h around that line are:
```
#if defined(_AMD64_) || defined(_X86_)
#define PROBE_ALIGNMENT( _s ) TYPE_ALIGNMENT( DWORD )
#elif defined(_IA64_) || defined(_ARM_) || defined(_ARM64_)

//
// TODO: WOWXX - Unblock ARM. Make all alignment checks DWORD for now.
//

#define PROBE_ALIGNMENT( _s ) TYPE_ALIGNMENT( DWORD )
#elif !defined(RC_INVOKED)
#error "No Target Architecture"
#endif
```

which suggests _AMD64_ is not set, which only happens if atlconv.h is included, which I guess is not happening.

**Comment by devnexen** [comment]
Then changing the order of the includes should solve it, windows.h before the new added entries ?

**Comment by glandium** [comment]
After the include order change, it fails with:
```
[task 2024-03-01T09:50:41.939Z] /builds/worker/fetches/clang/bin/clang-cl --target=x86_64-pc-windows-msvc  /nologo -TP  -I/builds/worker/fetches/llvm-project/compiler-rt/lib/fuzzer/../../include -D_CRT_SECURE_NO_WARNINGS --target=x86_64-windows-msvc -fms-compatibility-version=19.27 -vctoolsversion 14.29.30133 -winsdkversion 10.0.19041.0 -winsysroot /builds/worker/fetches/vs -Xclang -ivfsoverlay -Xclang /builds/worker/build/winsdk_vfs_overlay.yaml /DWIN32 /D_WINDOWS /EHsc /W4 -Wno-unused-parameter /O2 /Ob2 /DNDEBUG -MT -fno-builtin -fno-sanitize=safe-stack -fno-lto /Oy- /GS- /Zc:threadSafeInit- -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta /Z7 -Wno-gnu -Wno-variadic-macros -Wno-c99-extensions /wd4146 /wd4291 /wd4391 /wd4722 /wd4800 -D_HAS_EXCEPTIONS=0 -std:c++17 /showIncludes /Folib/fuzzer/CMakeFiles/RTfuzzer.x86_64.dir/FuzzerUtilWindows.cpp.obj /Fdlib/fuzzer/CMakeFiles/RTfuzzer.x86_64.dir/ -c -- /builds/worker/fetches/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtilWindows.cpp
[task 2024-03-01T09:50:41.939Z] /builds/worker/fetches/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtilWindows.cpp(245,7): error: reinterpret_cast from 'const char *' to 'proc' (aka 'long (*)(void *, const wchar_t *)') casts away qualifiers
[task 2024-03-01T09:50:41.939Z]   245 |       reinterpret_cast<proc>(GetProcAddress, "SetThreadDescription");
[task 2024-03-01T09:50:41.939Z]       |       ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
[task 2024-03-01T09:50:41.939Z] /builds/worker/fetches/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtilWindows.cpp(246,11): error: expected unqualified-id
[task 2024-03-01T09:50:41.939Z]   246 |   if (proc) {
[task 2024-03-01T09:50:41.939Z]       |           ^
[task 2024-03-01T09:50:41.939Z] /builds/worker/fetches/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtilWindows.cpp(251,11): error: use of undeclared identifier 'MultyByteToWideChar'; did you mean 'MultiByteToWideChar'?
[task 2024-03-01T09:50:41.939Z]   251 |       if (MultyByteToWideChar(CP_UTF8, 0, name.data(), -1, &buf[0], sz) > 0) {
[task 2024-03-01T09:50:41.939Z]       |           ^~~~~~~~~~~~~~~~~~~
[task 2024-03-01T09:50:41.939Z]       |           MultiByteToWideChar
[task 2024-03-01T09:50:41.939Z] /builds/worker/fetches/vs/Windows Kits/10/Include/10.0.19041.0/um/stringapiset.h(126,1): note: 'MultiByteToWideChar' declared here
[task 2024-03-01T09:50:41.939Z]   126 | MultiByteToWideChar(
[task 2024-03-01T09:50:41.939Z]       | ^
[task 2024-03-01T09:50:41.939Z] /builds/worker/fetches/llvm-project/compiler-rt/lib/fuzzer/FuzzerUtilWindows.cpp(245,30): warning: left operand of comma operator has no effect [-Wunused-value]
[task 2024-03-01T09:50:41.939Z]   245 |       reinterpret_cast<proc>(GetProcAddress, "SetThreadDescription");
[task 2024-03-01T09:50:41.939Z]       |                              ^~~~~~~~~~~~~~
[task 2024-03-01T09:50:41.940Z] 1 warning and 3 errors generated.
```

**Comment by devnexen** [comment]
oh I see I ll revert and redo a PR, couple of typos here and there.

**Pull request merged**
