### PR TITLE
Revert "[AArch64] Define high bits of FPR and GPR registers (take 2) (#114827)"

### PR DESCRIPTION
**Pull request by vitalybuka**
Details in #114827

This reverts commit c1c68baf7e0fcaef1f4ee86b527210f1391b55f6.

### CODE REVIEW

**Review by sdesmalen-arm — APPROVED** [review]
Strictly speaking not all patches need reverting (like the changes to InitUndef or RegisterCoalescer), although without the AArch64 changes that would mean those changes would no longer have any tests. I'll reland all these after I've investigated the issue caused by this patch.

Thanks for creating the revert.

**Comment by arsenm** [comment]
> Strictly speaking not all patches need reverting (like the changes to InitUndef or RegisterCoalescer), although without the AArch64 changes that would mean those changes would no longer have any tests. I'll reland all these after I've investigated the issue caused by this patch.
> 

This is why it's better to split these into independent patches

**Comment by vitalybuka** [comment]
> > Strictly speaking not all patches need reverting (like the changes to InitUndef or RegisterCoalescer), although without the AArch64 changes that would mean those changes would no longer have any tests. I'll reland all these after I've investigated the issue caused by this patch.

I started with main patch and then reverted what ever is needed to make check-llvm.

> 
> This is why it's better to split these into independent patches

I considered some of them as follow up fixes, which I think better to revert togther, so reland can start as revert of it.
My classification can be wrong.

I will do them one by one.

**Comment by vitalybuka** [comment]
> Would it be fine to land this now?

Will do in next 20min

**Pull request merged**
