### PR TITLE
[libc++] Fix P1206R7 feature test macros

### PR DESCRIPTION
**Pull request by krzysdz**
- Add missing `__cpp_lib_containers_ranges` feature test macro
- Constrain `__cpp_lib_ranges_to_container` to the `<ranges>` header, since the standard does not list it in containers' headers

Ref:
- https://www.open-std.org/jtc1/sc22/wg21/docs/papers/2022/p1206r7.pdf#section.18
- https://eel.is/c++draft/support.limits#lib:__cpp_lib_containers_ranges
- https://eel.is/c++draft/support.limits#lib:__cpp_lib_ranges_to_container

### CODE REVIEW

**Review by mordante — APPROVED** [review]
Nice catch! LGTM!

**Comment by krzysdz** [comment]
Amended to use my real e-mail address and rebased.

**Comment by krzysdz** [comment]
@mordante Would it be possible to backport this to 18.x?
P1206R7 is supported since 17.0.0 (specifically 17bbb224f99cf6fde83aa68e2e22e70fe9ed77be). It would be nice to have `__cpp_lib_containers_ranges` in 18.x too.

**Comment by mordante** [comment]
Sorry I missed this before. The last 18.1.x planned release has been released. @tstellar do you still accept PRs for LLVM 18?

**Comment by tstellar** [comment]
@mordante Probably not, but you can add it to the milestone just in case we do happen to do another release.

**Pull request merged**
