### PR TITLE
[clang][modules] Enable built-in modules for the upcoming Apple releases

### PR DESCRIPTION
**Pull request by ian-twilightcoder**
The upcoming Apple SDK releases will support the clang built-in headers being in the clang built-in modules: stop passing -fbuiltin-headers-in-system-modules for those SDK versions.

### CODE REVIEW

**Review by cyndyishida — APPROVED** [review]
LGTM

**Comment by ian-twilightcoder** [comment]
/cherry-pick 961639962251de7428c3fe93fa17cfa6ab3c561a 0f1361baf650641a59aaa1710d7a0b7b02f2e56d

**Pull request merged**
