### PR TITLE
[openmp] __kmp_x86_cpuid fix for i386/PIC builds.

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by brad0** [comment]
cc @MaskRay

**Review by shiltian — APPROVED** [review]

**Comment by mgorny** [comment]
I'm sorry to say but this change actually broke 32-bit builds on Gentoo, when u. Most of the tests segfault now, e.g.:

```
0/1] cd /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/test && /tmp/portage/sys-libs/libomp-19.0.0.9999/temp/python3.11/bin/python3 /usr/bin/lit -vv -j 12 /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/test
-- Testing: 325 tests, 12 workers --
FAIL: libomp :: affinity/format/api.c (1 of 325)
******************** TEST 'libomp :: affinity/format/api.c' FAILED ********************
Exit Code: -11

Command Output (stdout):
--
# RUN: at line 1
/usr/lib/ccache/bin/i686-pc-linux-gnu-clang -fopenmp   -I /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/src -I /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp/runtime/test -L /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/src  -fno-omit-frame-pointer -I /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp/runtime/test/ompt /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp/runtime/test/affinity/format/api.c -o /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/test/affinity/format/Output/api.c.tmp -lm -latomic && /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/test/affinity/format/Output/api.c.tmp
# executed command: /usr/lib/ccache/bin/i686-pc-linux-gnu-clang -fopenmp -I /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/src -I /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp/runtime/test -L /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/src -fno-omit-frame-pointer -I /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp/runtime/test/ompt /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp/runtime/test/affinity/format/api.c -o /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/test/affinity/format/Output/api.c.tmp -lm -latomic
# executed command: /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/test/affinity/format/Output/api.c.tmp
# note: command had no output on stdout or stderr
# error: command failed with exit status: -11

--

********************
```

My educated guess is that you aren't listing `edi` in clobbers. If I do that, most of the tests start passing again but I still get a handful of segfaults.

**Comment by devnexen** [comment]
> I'm sorry to say but this change actually broke 32-bit builds on Gentoo, when using GCC. Most of the tests segfault now, e.g.:
> 
> ```
> 0/1] cd /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/test && /tmp/portage/sys-libs/libomp-19.0.0.9999/temp/python3.11/bin/python3 /usr/bin/lit -vv -j 12 /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/test
> -- Testing: 325 tests, 12 workers --
> FAIL: libomp :: affinity/format/api.c (1 of 325)
> ******************** TEST 'libomp :: affinity/format/api.c' FAILED ********************
> Exit Code: -11
> 
> Command Output (stdout):
> --
> # RUN: at line 1
> /usr/lib/ccache/bin/i686-pc-linux-gnu-clang -fopenmp   -I /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/src -I /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp/runtime/test -L /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/src  -fno-omit-frame-pointer -I /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp/runtime/test/ompt /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp/runtime/test/affinity/format/api.c -o /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/test/affinity/format/Output/api.c.tmp -lm -latomic && /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/test/affinity/format/Output/api.c.tmp
> # executed command: /usr/lib/ccache/bin/i686-pc-linux-gnu-clang -fopenmp -I /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/src -I /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp/runtime/test -L /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/src -fno-omit-frame-pointer -I /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp/runtime/test/ompt /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp/runtime/test/affinity/format/api.c -o /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/test/affinity/format/Output/api.c.tmp -lm -latomic
> # executed command: /tmp/portage/sys-libs/libomp-19.0.0.9999/work/openmp_build-abi_x86_32.x86/runtime/test/affinity/format/Output/api.c.tmp
> # note: command had no output on stdout or stderr
> # error: command failed with exit status: -11
> 
> --
> 
> ********************
> ```
> 
> My educated guess is that you aren't listing `edi` in clobbers. If I do that, most of the tests start passing again but I still get a handful of segfaults.

What happens if you do the following instead ?

```c
__asm__ __volatile__("pushl  %%ebx\n"
		"cpuid\n"
		"mov    %%ebx,%1\n"
		"popl   %%ebx"
                 : "=a"(p->eax), "=b"(p->ebx), "=c"(p->ecx), "=d"(p->edx)
                 : "a"(leaf), "c"(subleaf));
```

**Comment by mgorny** [comment]
Actually, this change makes no sense to me (either the committed or the proposed variant). You're explicitly specifying `ebx` as the output operand, so the compiler should assume it will be overwritten. I've tested it both with clang and gcc, and indeed it does `pushl %ebx` before the assembly: https://godbolt.org/z/Tchze37ja

On top of that, you're effectively clobbering `%ebx` set by `cpuid`, so `p->ebx` ends up containing "junk" prior to `cpuid` call rather than the value returned by `cpuid`.

**Comment by mgorny** [comment]
Adding a revert on top of dbbdee2ea2156170062813fb3d7f2c023d65e02d (this is the commit I've originally tested) makes all tests pass again.

**Comment by devnexen** [comment]
ok let s revert it then.

**Pull request merged**
