### PR TITLE
Recover performance loss after PagedVector introduction

### PR DESCRIPTION
**Pull request by ktf**

### CODE REVIEW

**Comment by ktf** [comment]
@nikic any suggestion on how can I run the performance benchmark myself?

**Comment by nikic** [comment]
Not seeing a difference in `instructions:u` with this change: http://llvm-compile-time-tracker.com/compare.php?from=3b25407d977d9ed3dbcaccd4f8850b65e95d70fd&to=8f5c0fd7348e78aedafcee3f7e67f04e3bc79e9c&stat=instructions:u Which is not really surprising -- it might make a difference in cycles, but not at a level I can resolve accurately.

**Comment by ktf** [comment]
@nikic I have pushed a new commit where I change the size of the page to 32 elements from the current 42. It should at least get rid of a division.

**Comment by cor3ntin** [comment]
Should we abandon this?

**Comment by ktf** [comment]
I have updated the branch and I think the two changes in this PR are in any case good. However it's my understanding that the performance regression was actually due to some less aggressive inlining of the new code. I have no idea how to proceed for that though.

**Review by cor3ntin — APPROVED** [review]

**Pull request merged**
