### PR TITLE
[NFC] Add a new Intrinsics.cpp file for intrinsic code

### PR DESCRIPTION
**Pull request by jurahul**
Add new file Intrinsics.cpp and move all functions in the `Intrinsic` namespace to it.

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
What's the motivation for splitting this into a separate file? Is this just so the name matches the name of the header?

**Comment by jurahul** [comment]
We could also rename Intrinsics.h to Intrinsic.h to match the namespace, but that may be too much busy work for questionable benefit.

**Comment by jurahul** [comment]
I did look into that, one issue is that ` Function::lookupIntrinsicID(StringRef Name)` uses the intrinsic name table, so I'd have to move that function to the `Intrinsic` namespace (its a static function). How about I do that first as a separate prep PR, and then revisit this PR to move the rest of them as well?

**Comment by jurahul** [comment]
Also fine doing all of that in a single shot

**Comment by jurahul** [comment]
PTAL at the new version, it moves all function from the `Intrinisic` namespace to the new file.

**Review by nikic — APPROVED** [review]
LGTM

**Pull request merged**
