### PR TITLE
Increase git fetch depth

### PR DESCRIPTION
**Pull request by llvm-beanz**
We've gotten ~750 commits in the last 7 days. Upping the fetch depth to 2000 will make it more likely that PRs up to 2 weeks old will have enough fetch history to find a common parent. This _might_ address some of the failures we're seeing in the clang-format action where it cannot find a common base commit.

### CODE REVIEW

**Review by tstellar — COMMENTED** [review]
I still don't quite understand why so much history is needed.

**Review by boomanaiden154 — APPROVED** [review]
LGTM with one comment.

This is a fairly bandaid fix. The `changed-files` action takes an incredible amount of time to pull commits. Still haven't gotten to the bottom of that, my current fix is to just move it to before the checkout to force it to grab the info from the API. While testing the code formatting action, I've also seen quite a few cases where a fetch-depth of 2000 still won't be good enough to find the merge base. That case is uncommon though.

I have a proper fix in https://github.com/llvm/llvm-project/pull/69766, but of course it broke fetching anything as soon as I pushed it, so it's been reverted for now. Still working on debugging it/reading up on what could be going wrong.

Landing this in the meantime sounds good to me though.

**Comment by llvm-beanz** [comment]
I'm also experimenting with a more permanent fix. I was thinking about adding something like:

```yaml
     - name: Find merge base
        env:
          PR_NUMBER: ${{ github.event.number }}
        run: |
          until git merge-base $GITHUB_SHA pull/$PR_NUMBER
            do
            depth=$((depth+1000))
            git fetch --depth=$depth origin $GITHUB_HEAD_REF
            git fetch --depth=$depth origin refs/pull/$PR_NUMBER/head:pull/$PR_NUMBER
            if [ "$depth" -gt "10000" ]
            then
              exit 1
            fi
          done
```

That would incrementally walk up the depth until it either finds a merge base or tries too many times.

**Comment by boomanaiden154** [comment]
The action does something similar internally (I believe). I think if we want something that works but is inefficient, just fetching the whole repository would work. That significantly increases the time the action takes to run (makes it ~30 minutes from my experience with the documentation action), but it should always work.

I still think https://github.com/llvm/llvm-project/pull/69766 is the ideal solution. It works and is fast from all my testing, there's just something that breaks when it actually gets deployed. I just haven't had the time to reproduce the issue on my fork and fix it.

**Comment by llvm-beanz** [comment]
Hopefully my change will reduce the frequency enough that we don't have too much pain between now and when you can revisit.

Thanks!

**Comment by boomanaiden154** [comment]
Hopefully. Thanks for the patch!

**Pull request merged**
