### PR TITLE
[RISCV] Mark vmvNr.v as implicitly using vtype

### PR DESCRIPTION
**Pull request by lukel97**
This was pointed out in https://github.com/llvm/llvm-project/pull/118283#issuecomment-2512895919. We cannot move these between vtype definitions as they depend on SEW and require vill to be clear.

### CODE REVIEW

**Review by topperc — APPROVED** [review]
LGTM

**Comment by lukel97** [comment]
I had to update the llvm-mca tests, I'm not sure why adding a use affects the number of cycles.

**Comment by preames** [comment]
> I had to update the llvm-mca tests, I'm not sure why adding a use affects the number of cycles. cc @mshockwave

LGTM as well, the mca change is at least reasonable if we're modeling a new runtime dependency which wasn't previously being modeled.

**Comment by topperc** [comment]
> > I had to update the llvm-mca tests, I'm not sure why adding a use affects the number of cycles. cc @mshockwave
> 
> LGTM as well, the mca change is at least reasonable if we're modeling a new runtime dependency which wasn't previously being modeled.

Looking at the test. There are vsetvlis interleaved with vmv. So I assume llvm-mca is now waiting for the preceding vsetvli before it can start a vmv.

**Comment by mshockwave** [comment]
> > > I had to update the llvm-mca tests, I'm not sure why adding a use affects the number of cycles. cc @mshockwave
> > 
> > 
> > LGTM as well, the mca change is at least reasonable if we're modeling a new runtime dependency which wasn't previously being modeled.
> 
> Looking at the test. There are vsetvlis interleaved with vmv. So I assume llvm-mca is now waiting for the preceding vsetvli before it can start a vmv.

Correct, this is the timeline before:
```
Index     0123456789          0123456789          0123456789          0123456789

[0,0]     DeER .    .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vsetvli    zero, zero, e8, mf8, tu, mu
[0,1]     DeeER.    .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vmv1r.v    v8, v16
[0,2]     D=eER.    .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vsetvli    zero, zero, e8, mf4, tu, mu
[0,3]     .DeeER    .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vmv1r.v    v8, v16
[0,4]     .D=eER    .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vsetvli    zero, zero, e8, mf2, tu, mu
[0,5]     .D=eeER   .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vmv1r.v    v8, v16
[0,6]     . D=eER   .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vsetvli    zero, zero, e8, m1, tu, mu
[0,7]     . D=eeER  .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vmv1r.v    v8, v16
[0,8]     . D==eER  .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vsetvli    zero, zero, e8, m1, tu, mu
[0,9]     .  D=eeER .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vmv1r.v    v8, v16
[0,10]    .  D==eER .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vsetvli    zero, zero, e8, m2, tu, mu
[0,11]    .  D==eeER.    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vmv1r.v    v8, v16
```
And this is the one after:
```
Index     0123456789          0123456789          0123456789          0123456789

[0,0]     DeER .    .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vsetvli    zero, zero, e8, mf8, tu, mu
[0,1]     D=eeER    .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vmv1r.v    v8, v16
[0,2]     D=eE-R    .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vsetvli    zero, zero, e8, mf4, tu, mu
[0,3]     .D=eeER   .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vmv1r.v    v8, v16
[0,4]     .D=eE-R   .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vsetvli    zero, zero, e8, mf2, tu, mu
[0,5]     .D==eeER  .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vmv1r.v    v8, v16
[0,6]     . D=eE-R  .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vsetvli    zero, zero, e8, m1, tu, mu
[0,7]     . D==eeER .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vmv1r.v    v8, v16
[0,8]     . D==eE-R .    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vsetvli    zero, zero, e8, m1, tu, mu
[0,9]     .  D==eeER.    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vmv1r.v    v8, v16
[0,10]    .  D==eE-R.    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vsetvli    zero, zero, e8, m2, tu, mu
[0,11]    .  D===eeER    .    .    .    .    .    .    .    .    .    .    .    .    .   .   vmv1r.v    v8, v16
```
vmvNr no longer can be issued at the same cycle with vsetvli.

**Review by mshockwave — APPROVED** [review]

**Comment by wangpc-pp** [comment]
> vmvNr no longer can be issued at the same cycle with the preceding vsetvli.

(Disclaimer: this is just my imagination, real microarchitecture may not be like this)
For this part, the hardware may issue vmvNr (using implementation-specific EEW, for example, EEW=8) before vtype is ready and check vill when committing. And also, there are some existing hardwares that don't trap.
What I am trying to say is, the modeling of side effect and instruction scheduling in compiler may differ from hardware behavior, and that may cause sub-optimal instruction sequences after scheduling. This may not be a big problem, we can revisit it if we do see some real issues it causes.

**Review by wangpc-pp — APPROVED** [review]
LGTM.

**Pull request merged**
