### PR TITLE
[CMake][compiler-rt] Support for using compiler-rt atomic library

### PR DESCRIPTION
**Pull request by petrhosek**
Not every toolchain provides and want to use libatomic which is a part of GCC, some toolchains may opt into using compiler-rt atomic library.

### CODE REVIEW

**Review by cjappl — APPROVED** [review]
Seems reasonable to me, I would wait for other approvals, as I'm relatively new here.

Just ensure this is good to go with rtsan, I recommend running the tests locally, as I don't think they're a part of the default pre-commit set
```
ninja check-rtsan
```

**Review by smeenai — APPROVED** [review]
LGTM

**Comment by petrhosek** [comment]
> Seems reasonable to me, I would wait for other approvals, as I'm relatively new here.
> 
> Just ensure this is good to go with rtsan, I recommend running the tests locally, as I don't think they're a part of the default pre-commit set
> 
> ```
> ninja check-rtsan
> ```

I'm seeing a test failure but I'm not sure if it's an issue with RTSan or compiler-rt atomic implementation:
```
FAIL: RealtimeSanitizer-Unit :: ./Rtsan-x86_64-Test/13/75 (1 of 84)
******************** TEST 'RealtimeSanitizer-Unit :: ./Rtsan-x86_64-Test/13/75' FAILED ********************
Script(shard):
--
GTEST_OUTPUT=json:/usr/local/google/home/phosek/llvm/llvm-project/build/fuchsia/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/rtsan/tests/./Rtsan-x86_64-Test-RealtimeSanitizer-Unit-1864241-13-75.json GTEST_SHUFFLE=0 GTEST_TOTAL_SHARDS=75 GTEST_SHARD_INDEX=13 /usr/local/google/home/phosek/llvm/llvm-project/build/fuchsia/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/rtsan/tests/./Rtsan-x86_64-Test
--

Script:
--
/usr/local/google/home/phosek/llvm/llvm-project/build/fuchsia/runtimes/runtimes-x86_64-unknown-linux-gnu-bins/compiler-rt/lib/rtsan/tests/./Rtsan-x86_64-Test --gtest_filter=TestRtsan.AccessingALargeAtomicVariableDiesWhenRealtime
--
compiler-rt/lib/rtsan/tests/rtsan_test_utilities.h:40: Failure
Death test: RealtimeInvoke(std::forward<Function>(Func))
    Result: failed to die.
 Error msg:
[  DEATH   ] 


compiler-rt/lib/rtsan/tests/rtsan_test_utilities.h:40
Death test: RealtimeInvoke(std::forward<Function>(Func))
    Result: failed to die.
 Error msg:
[  DEATH   ] 



********************
********************
Failed Tests (1):
  RealtimeSanitizer-Unit :: ./Rtsan-x86_64-Test/TestRtsan/AccessingALargeAtomicVariableDiesWhenRealtime
```

**Comment by cjappl** [comment]
> I'm seeing a test failure but I'm not sure if it's an issue with RTSan or compiler-rt atomic implementation:

Interesting, so that test basically tests that large atomics that insert locks under the hood die as expected. Zooming in on the second part of the test:


```
std::atomic<std::array<float, 2048>> large_atomic;
  ASSERT_FALSE(large_atomic.is_lock_free());     ///// HERE IS INTERESTING!
  auto Func = [&]() {
    std::array<float, 2048> x = large_atomic.load();
    return x;
  };
  ExpectRealtimeDeath(Func);
  ExpectNonRealtimeSurvival(Func);

```

It seems like the compiler-rt version says it is lock free, but then we aren't dying. Does it take another lock, different from a pthread_mutex_lock? Those are the locks we look for in our implementation.

**Comment by cjappl** [comment]
Ok, it appears that on Apple systems, we would catch this, as we intercept OSSpinLockLock used by compiler-rt atomics:

https://github.com/llvm/llvm-project/blob/c55e24b8507d47a8cc04b5d9570e8e3d02be1ca3/compiler-rt/lib/builtins/atomic.c#L95-L102

But, in the non-darwin case this is an atomic CAS spinlock, which we do not intercept (but we are trying to figure out how to catch potentially unbound loops like this):

https://github.com/llvm/llvm-project/blob/c55e24b8507d47a8cc04b5d9570e8e3d02be1ca3/compiler-rt/lib/builtins/atomic.c#L112-L119

Would you please confirm that you end up in this area of atomic.c when you run this test? If so, I think it is adequate to #ifdef out this test under the circumstances that it is 
1. Compiling with the builtin atomics
2. Not on darwin

https://github.com/llvm/llvm-project/blob/d58d105cdaf366d7db3f60d356b21bc8e64666fb/compiler-rt/lib/rtsan/tests/rtsan_test_functional.cpp#L164-L171

Or if you're feeling ambitious, you could pull this little bit into a new test and ifdef out that, might be cleaner.

Let me know if I can be of any assistance with any of this.

**Comment by cjappl** [comment]
> but it'd be better if we handled atomic CAS spinlocks as well since we would like to avoid the pthread dependency if possible.

Agreed, I have something in the works for this but it is a little ways off. (catching these unbound loops is a bit tricky)

My recommendation to make it work when using the builtins would be just extracting this test to another test, then #ifdefing it out in the situation where we are not using pthread

**Pull request merged**
