### PR TITLE
[DAG] computeKnownBits - add ISD::ABDU/ISD::ABDS handling #84905

### LINKED ISSUE #84905: [DAG] SelectionDAG::computeKnownBits - add ISD::ABDU/ISD::ABDS handling
We now have KnownBits::abdu/abds implementations, so we can now add this to computeKnownBits.

The actual addition of the code is trivial, a little more work will be adding suitable tests - I'd recommend using aarch64 as it has dedicated ABD vector intrinsics:

```ll
declare <8 x i16> @llvm.aarch64.neon.uabd.v8i16(<8 x i16>, <8 x i16>)
declare <8 x i16> @llvm.aarch64.neon.sabd.v8i16(<8 x i16>, <8 x i16>)
```

### PR DESCRIPTION
**Pull request by SahilPatidar**
Resolve #84905

### CODE REVIEW

**Comment by SahilPatidar** [comment]
@RKSimon, Let me know if any of the tests make sense to you.

**Comment by RKSimon** [comment]
Please can you add the new tests as the first commit in the patch, and the handling (and test changes) as the second commit so it can show the effect

**Comment by SahilPatidar** [comment]
@RKSimon, I checked that out! I made separate commits and changed some test cases.

**Review by RKSimon — CHANGES_REQUESTED** [review]
Please can you look at the failing AArch64 test:
```
Failed Tests (1):
  LLVM :: CodeGen/AArch64/abd-combine.ll
```

**Review by RKSimon — APPROVED** [review]
LGTM

**Pull request merged**
