### PR TITLE
[DFAJumpThreading] Extends the bitwidth of state from uint64_t to APInt

### LINKED ISSUE #78059: [DFAJumpThreading] Assertion `getActiveBits() <= 64 && "Too many bits for uint64_t"' failed.
Seems that i128 is not handled properly here... Maybe look at 82a1bff for a solution.

opt -mtriple=s390x-unknown-linux -mcpu=z15 -O3 tc_dfajumpthr.ll -S -o out.opt.ll -enable-dfa-jump-thread
[tc_dfajumpthr.tar.gz](https://github.com/llvm/llvm-project/files/13929101/tc_dfajumpthr.tar.gz)

APInt.h:1488: uint64_t llvm::APInt::getZExtValue() const: Assertion `getActiveBits() <= 64 && "Too many bits for uint64_t"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
 #9 0x000002aa023f07ee llvm::DFAJumpThreadingPass::

### PR DESCRIPTION
**Pull request by XChy**
Fixes #78059

### CODE REVIEW

**Review by nikic — APPROVED** [review]
LGTM

**Comment by nikic** [comment]
I think this is causing buildbot failure: https://lab.llvm.org/buildbot/#/builders/168/builds/18062

**Comment by XChy** [comment]
> I think this is causing buildbot failure: https://lab.llvm.org/buildbot/#/builders/168/builds/18062

It seemed that I triggered another bug in this pass with the same testcase in coincidence, even without this patch...

The testcase without `i128`:
```llvm
define void @anotherbug(i1 %c) {
entry:
  br i1 %c, label %.split.preheader, label %.split.preheader

.split.preheader:
  br label %.split

.split:
  %0 = phi i32 [ 0, %.split.preheader ], [ -1, %.split ]
  switch i32 %0, label %end [
  i32 -1, label %end
  i32 0, label %.split
  ]

end:
  ret void
}
```

**Comment by XChy** [comment]
I think I have found the way to fix it. I'll file a patch sooner after testing it locally

**Pull request merged**
