### PR TITLE
[clang] Add cuda-path arguments to failing test

### PR DESCRIPTION
**Pull request by hahnjo**
This test was failing for me because I have a local CUDA installation. Remove the `not` and pin the `cuda-path` in the test to make it pass on platforms with and without CUDA.

### CODE REVIEW

**Review by jhuber6 — COMMENTED** [review]
We had a lot that were like this previously. Guessing this one slipped through because of the `zlib` requirement. Does this work with `-nogpulib` instead? Usually easier than passing the dummy CUDA path.

**Comment by hahnjo** [comment]
> We had a lot that were like this previously. Guessing this one slipped through because of the `zlib` requirement.

I actually think there are some more left; for example `clang/test/Driver/cuda-dwarf-2.cu` has many `not %clang` invocations that don't specify `--cuda-path`. This happens to work on my system because my CUDA installation is too recent to support `sm_20`, but I suspect it would actually fail with an older CUDA installed...

> Does this work with `-nogpulib` instead? Usually easier than passing the dummy CUDA path.

It definitely doesn't work for the "pure" CUDA invocations, it still finds my local installation and complains. It might work for the OpenMP invocations, but hard to tell for me on a system with CUDA installed. As it's a `.cu` test after all, I think I would prefer the uniformity of passing `--cuda-path` everywhere and be safe from any weird interaction.

**Comment by jhuber6** [comment]
> It definitely doesn't work for the "pure" CUDA invocations, it still finds my local installation and complains. It might work for the OpenMP invocations, but hard to tell for me on a system with CUDA installed. As it's a `.cu` test after all, I think I would prefer the uniformity of passing `--cuda-path` everywhere and be safe from any weird interaction.

Might need `-nogpulib -nogpuinc` in those cases, we do that in other `.cu` files in the test suite.

**Comment by hahnjo** [comment]
> > It definitely doesn't work for the "pure" CUDA invocations, it still finds my local installation and complains. It might work for the OpenMP invocations, but hard to tell for me on a system with CUDA installed. As it's a `.cu` test after all, I think I would prefer the uniformity of passing `--cuda-path` everywhere and be safe from any weird interaction.
> 
> Might need `-nogpulib -nogpuinc` in those cases, we do that in other `.cu` files in the test suite.

No, I already tried that, it doesn't work for me. All `clang/test/Driver/*.cu` that supply `-nocudainc` also pass `--cuda-path`...

**Comment by jhuber6** [comment]
> > Might need `-nogpulib -nogpuinc` in those cases, we do that in other `.cu` files in the test suite.
> 
> No, I already tried that, it doesn't work for me. All `clang/test/Driver/*.cu` that supply `-nocudainc` also pass `--cuda-path`...

The only reason it will fail without a CUDA installation if you pass both `-nogpulib` and `-nogpuinc` is if you need to use `ptxas`, which shouldn't be the case if you're using options like `-###`. Tested it out by moving my CUDA installation and the following works as I expect.

```
> cat /dev/null | clang -x cuda - --offload-arch=sm_52 -nogpulib -nogpuinc -emit-llvm -c && echo $?
0
> cat /dev/null | clang -x cuda - --offload-arch=sm_52                                  
clang: error: cannot find libdevice for sm_52; provide path to different CUDA installation via '--cuda-path', or pass '-nocudalib' to build without linking with libdevice
clang: error: cannot find CUDA installation; provide its path via '--cuda-path', or pass '-nocudainc' to build without CUDA includes
clang: error: cannot find CUDA installation; provide its path via '--cuda-path', or pass '-nocudainc' to build without CUDA includes
```

Which tests aren't working in your case?

**Comment by jhuber6** [comment]
In any case, it's not really important and this works. I'm mostly just curious why it doesn't seem to work as I would expect since there might be something to fix.

**Comment by hahnjo** [comment]
> > > Might need `-nogpulib -nogpuinc` in those cases, we do that in other `.cu` files in the test suite.
> > 
> > 
> > No, I already tried that, it doesn't work for me. All `clang/test/Driver/*.cu` that supply `-nocudainc` also pass `--cuda-path`...
> 
> The only reason it will fail without a CUDA installation if you pass both `-nogpulib` and `-nogpuinc` is if you need to use `ptxas`, which shouldn't be the case if you're using options like `-###`. Tested it out by moving my CUDA installation and the following works as I expect.
> 
> ```
> > cat /dev/null | clang -x cuda - --offload-arch=sm_52 -nogpulib -nogpuinc -emit-llvm -c && echo $?
> 0
> > cat /dev/null | clang -x cuda - --offload-arch=sm_52                                  
> clang: error: cannot find libdevice for sm_52; provide path to different CUDA installation via '--cuda-path', or pass '-nocudalib' to build without linking with libdevice
> clang: error: cannot find CUDA installation; provide its path via '--cuda-path', or pass '-nocudainc' to build without CUDA includes
> clang: error: cannot find CUDA installation; provide its path via '--cuda-path', or pass '-nocudainc' to build without CUDA includes
> ```
> 
> Which tests aren't working in your case?

The invocations in `clang/test/Driver/cuda-omp-unsupported-debug-options.cu` don't pass `-emit-llvm` but `-###`.
```
 > cat /dev/null | ./bin/clang -### -x cuda - -nogpulib -nogpuinc -c && echo $?
```
should error with recent CUDA installations because of `sm_35`.

**Comment by jhuber6** [comment]
> The invocations in `clang/test/Driver/cuda-omp-unsupported-debug-options.cu` don't pass `-emit-llvm` but `-###`.
> 
> ```
>  > cat /dev/null | ./bin/clang -### -x cuda - -nogpulib -nogpuinc -c && echo $?
> ```
> 
> should error with recent CUDA installations because of `sm_35`.

I distinctly remember bumping that up to `sm_52`, guess I missed a spot.

**Comment by jhuber6** [comment]
Found it https://github.com/llvm/llvm-project/pull/84017.

**Comment by hahnjo** [comment]
Ok, but that still doesn't change the fact that the Clang driver will search for a system-wide CUDA installation unless passed `--cuda-path`...

**Comment by jhuber6** [comment]
> Ok, but that still doesn't change the fact that the Clang driver will search for a system-wide CUDA installation unless passed `--cuda-path`...

We also do this with the GCC toolchain, the issue is whether or not there's an error if it didn't find it. Doing `clang -v` will always print out if it found CUDA or HIP even on standard compilation AFAIK. Could you go ahead and add `-nogpulib -nogpuinc` to your tests. You can keep the `--cuda-path=` for now since I don't expect you to wait until my other fix lands. Thanks for bringing that to my attention, I knew there was something off if you were having problems.

**Comment by hahnjo** [comment]
https://github.com/llvm/llvm-project/pull/84017 changed the test in ways that this isn't needed anymore.

**Pull request closed without merging**
