### PR TITLE
[Clang] fix assertion failure in invalid delete operator declaration check

### LINKED ISSUE #96191: [clang][trunk] compiler crashes if the first parameter of a member operator delete is in class type
[detailed execution result on godbolt](https://godbolt.org/#g:!((g:!((g:!((h:codeEditor,i:(filename:'1',fontScale:15,fontUsePx:'0',j:1,lang:c%2B%2B,selection:(endColumn:29,endLineNumber:6,positionColumn:29,positionLineNumber:6,selectionStartColumn:29,selectionStartLineNumber:6,startColumn:29,startLineNumber:6),source:'struct+S+%7B%7D%3B%0Astruct+T+%7B%0A++void+operator+delete(S)+%7B%7D%0A%7D%3B%0A%0Avoid+foo(T+*t)+%7B+delete+t%3B+%7D'),l:'5',n:'0',o:'C%2B%2B+source+%231',t:'0')),k:49.56256362285746,l:'4',m:100,n:'0',o:'',s:0,t:'0'),(g:!((h:executor,i:(argsPanelShown:'1',compilationPanelShown:'0',compiler:clang_trunk,compilerName:'',compilerOutShown:'0',execArgs:'',execStdin:'',fontScale:14,fontUsePx:'0',j:1,lang:c%2B%2B,libs:!(),options:'-std%3Dc%2B%2B20',overrides:!(),runtimeTools:!(),source:1,stdinPanelShown:'1',wrap:'1'),l:'5',n:'0',o:'Executor+x86-64+clang+(trunk)+(C%2B%2B,+Editor+%231)',t:'0')),header:(),k:50.41112058766887,l:'4',n:'0',o:'',s:0,t:'0')),l:'2',n:'0',o:'',t:'0')),version:4)

This bug was discovered when I was studying the usage of `std::destorying_delete_t`.
After removing the first parameter of a pointer type, the compiler crashes.

In the example below, `std::destorying_delete_t` is simplified to `struct S` for the sake of debugging.

```cpp
struct S {};
struct T {
  void operator delete(S) {}
};

void foo(T *t) { delete t; }
```

Pretty stack dump:

```
1.	<source>:6:26: current parser token ';'
2.	<source>:6:16: parsing function body 'foo'
3.	<source>:6:16: in compound statement ('{}')
```

Crashed in function `clang::Sema::ActOnCXXDelete(clang::SourceLocation, bool, bool, clang::Expr*)`
when checking QualType `ParamType`, which is not a pointer and its `getPointeeType` returns an empty QualType.

https://github.com/llvm/llvm-project/blob/724d903e03aaf7ee7d4bcdf3cd9fe1e1bda33f9a/clang/lib/Sema/SemaExprCXX.cpp#L3883-L3884

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #96191

### CODE REVIEW

**Comment by a-tarasyuk** [comment]
@shafik could you review this PR? thanks

**Comment by a-tarasyuk** [comment]
@AaronBallman could you review this PR? thanks

**Review by AaronBallman — APPROVED** [review]
LGTM! Thank you for the fix!

**Comment by a-tarasyuk** [comment]
@AaronBallman If no further feedback is needed, could you please proceed with the merge? Thanks

**Comment by AaronBallman** [comment]
> @AaronBallman If no further feedback is needed, could you please proceed with the merge? Thanks

Can do! Btw, you should feel free to obtain commit privileges yourself if you'd like: https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access

**Comment by a-tarasyuk** [comment]
@AaronBallman Thanks

**Pull request merged**
