### PR TITLE
[ARM] r11 is reserved when using -mframe-chain=aapcs

### PR DESCRIPTION
**Pull request by ostannard**
When using the -mframe-chain=aapcs or -mframe-chain=aapcs-leaf options, we cannot use r11 as an allocatable register, even if -fomit-frame-pointer is also used. This is so that r11 will always point to a valid frame record, even if we don't create one in every function.

### CODE REVIEW

**Comment by efriedma-quic** [comment]
This isn't really consistent with how we handle frame-pointer options on other targets.

On the target-independent side: there are three possible settings for the frame pointer attribute/flag: "all", "non-leaf", and "none".  In "all" and "non-leaf" mode, we want to preserve the frame pointer register; in "none" mode, we don't.  If we do want a "don't create a frame pointer, but reserve the register" mode, I think we should change the way the target-independent settings work.

That isn't to say the change to ARMBaseRegisterInfo.cpp is wrong, but I'm not sure the implementation of isFPReserved() works the way we want.

**Comment by ostannard** [comment]
Ah, I've just discovered the target-independent `-m[no-]omit-leaf-frame-pointer` option. How that should interact with `-mframe-chain=aapcs-leaf` is unclear, I can't find any documentation on that. GCC doesn't seem to implement `-mframe-chain` at all, so I can't compare against that.

@pratlucas: you originally implemented these options, do you know how they should interact with the target-independent options?

**Comment by ostannard** [comment]
@pratlucas ping

**Comment by ostannard** [comment]
Ping

**Comment by efriedma-quic** [comment]
Since the frame-chain options originally come from armclang, we can look at their documentation to see the expected semantics: https://developer.arm.com/documentation/101754/0622/armclang-Reference/armclang-Command-line-Options/-mframe-chain . The frontend flag semantics are... not really what I would have chosen, but seem good enough that it's not worth diverging.  It would be nice to make sure -momit-leaf-frame-pointer interacts reasonably with -mframe-chain, though.

Regardless of what the frontend flags look like, though, I think we want the internal representation to match what I mentioned before: change the definition of the "frame-pointer" function attribute in LLVM IR to add the value "reserved", and query that to check whether the frame pointer register should be reserved.  The value fits cleanly into the existing hierarchy, has an obvious cross-platform meaning, and allows us to narrow the target-specific attribute to only specify whether r11 is the frame pointer register in Thumb mode.

**Review by efriedma-quic — APPROVED** [review]
LGTM

**Pull request merged**
