### PR TITLE
[clang] Cover CWG issues about `export template`

### PR DESCRIPTION
**Pull request by Endilll**
This PR covers the following Core issues:
[CWG204](https://cplusplus.github.io/CWG/issues/204.html) "Exported class templates"
[CWG323](https://cplusplus.github.io/CWG/issues/323.html) "Where must `export` appear?"
[CWG335](https://cplusplus.github.io/CWG/issues/335.html) "Allowing `export` on template members of nontemplate classes"
[CWG820](https://cplusplus.github.io/CWG/issues/820.html) "Deprecation of `export`"

I believe the list above is entirety of Core issues that are dedicated solely to `export template`.

I believe we have two main points of view here, which command what this PR should do:
1. (easy) Removal of `export template` was done as a defect report in CWG820, and the rest are effectively superseded by it, because we apply defect reports retroactively.
2. (harder) Those Core issues are testable individually, so we should test them for the behavior Core wanted at the time.

This PR implements the first option, making our C++ DR status page greener.
I think I can be persuaded to go with the second option, if reviewers have strong preference for it.

### CODE REVIEW

**Comment by cor3ntin** [comment]
I would prefer we say `N/A` rather than pretend we support something that was never implemented (to the extend i think it might be better to have an error about modules rather than exported templates in older language modes)

**Comment by Endilll** [comment]
Using `N/A` for 204, 323, and 335 would be novel, because at the moment it's used for wording changes that do not affect implementations. Those Core issues clearly affected the implementations back when they were resolved.

**Comment by cor3ntin** [comment]
We never implemented `export template` - and no one did, therefore we are not affected by changes to it (no one did except for EDG, i don't even know if they shipped it)

It is perfectly reasonable not to have tests whatsoever for that either (although I find the pre-c++20 diagnostic funny, we would be better of saying that modules are a c++20 feature).

**Comment by Endilll** [comment]
> We never implemented export template - and no one did, therefore we are not affected by changes to it (no one did except for EDG, i don't even know if they shipped it)

When I said "wording changes that do not affect implementations", I meant a hypothetical conforming implementation. In other words, `N/A` is for wording changes that can't be exhibited by writing programs and feeding them into the compiler.

**Comment by Endilll** [comment]
Me and Corentin discussed this offline. Two points emerged there:
1) He's more concerned with the fact that 204 and other Core issues are highlighted green, inheriting the status of the issue that superseded them, than with the fact that they are marked as superseded. Styles we use in `cxx_dr_status.html` can be changed in a subsequent PR.
2) In previous discussions on this topic, I remember that we together with @AaronBallman agreed that statuses on our page should follow the official statuses. This PR goes against it, because I know from experience that the current CWG chair is not interested in revisiting Core issues that were closed long ago, and mark them as superseded where appropriate. We might need to revisit out previous consensus in the light of this PR and aforementioned experience talking to Core.

**Comment by AaronBallman** [comment]
The goal of the status page is to convey implementation status to our users, and so from that perspective I think N/A provides the least information to users because it basically says "this entry doesn't apply to us". So in these kinds of cases, `sup` conveys more information because the DRs would apply to us, except another DR superseded the need for making the changes.

In terms of the color used, we want green to mean "we're behaving in a conforming way" so users can tell at a glance where the edge cases are. This case is a bit weird because "conform" means we *don't* implement something rather than we *do* implement it, but I still think green is appropriate because we're following the standard. It might be fine to give a different color to superseded, but I would guess we'd want that to be a lighter form version of whatever the superseding issue is colored. e.g., given that conforming = green and non-conforming = red, if we have a superseded issue we conform to, it would be light green, and if we didn't conform it would be pink. WDYT?

**Comment by Endilll** [comment]
Thank you for chiming in!

> It might be fine to give a different color to superseded, but I would guess we'd want that to be a lighter form version of whatever the superseding issue is colored. e.g., given that conforming = green and non-conforming = red, if we have a superseded issue we conform to, it would be light green, and if we didn't conform it would be pink. WDYT?

I'm thinking of reducing opacity of the color instead of picking exact shades, but yeah, we can definitely do something of this sort.

**Review by shafik — COMMENTED** [review]
LGTM after addressing coloring issues.

**Review by cor3ntin — APPROVED** [review]
I think as a follow up we should get rid of the  "exported templates are unsupported" warning which makes no sense whatsoever and either use the c++20 error in all language modes or just a generic "unexpected 'export' keyword here" diagnostic

**Pull request merged**
