### PR TITLE
[libc] Add proxy header for the jmp_buf type

### PR DESCRIPTION
**Pull request by wldfngrs**
Added proxy header for the jmp_buf type and changed all use instances from __jmp_buf * to the typedef alias jmp_buf , fixed the link to LLVM in stack_t.h description

### CODE REVIEW

**Comment by wldfngrs** [comment]
@lntue, please review!

**Review by lntue — COMMENTED** [review]
Can you also remove `libc.include.setjmp` in the dependency list in `libc/test/src/setjmp/CMakeLists.txt`?

**Comment by wldfngrs** [comment]
updated for the latest review, @lntue !

**Review by lntue — APPROVED** [review]
LGTM.  Thanks!

**Pull request merged**
