### PR TITLE
[RISCV] Add Smcsrind and Sscsrind extension

### PR DESCRIPTION
**Pull request by YanWQ-monad**
Specification link: https://github.com/riscv/riscv-isa-manual/blob/main/src/indirect-csr.adoc

Some CSRs (`*ireg` and `*iselect`) in Smcsrind/Sscsrind extensions are originally defined as part of the Smaia/Ssaia extensions and are already supported in LLVM. The missing CSRs (`*ireg2` to `*ireg6` for `m`, `s`, and `vs`) are added in this PR.

### CODE REVIEW

**Review by dtcxzyw — COMMENTED** [review]
Can you also update `llvm/docs/ReleaseNotes.rst` ?

**Comment by wangpc-pp** [comment]
> Specification link: https://github.com/riscvarchive/riscv-indirect-csr-access

You may need to update link to https://github.com/riscv/riscv-isa-manual/blob/main/src/indirect-csr.adoc.

**Comment by YanWQ-monad** [comment]
ping?

**Comment by topperc** [comment]
We don't implement all the CSRs. We're missing mireg2-6, sireg2-6, and vsireg2-6

**Comment by YanWQ-monad** [comment]
My bad. I though they have the same CSRs as Smcsrind/Sscsrind originate from Smaia/Ssaia.

**Review by topperc — APPROVED** [review]
LGTM

**Comment by dtcxzyw** [comment]
Conflicting files

> llvm/docs/ReleaseNotes.rst

**Comment by YanWQ-monad** [comment]
> Conflicting files

rebased.

**Pull request merged**
