### PR TITLE
Clang-Refactor

### PR DESCRIPTION
**Pull request by IgnatSergeev**

### CODE REVIEW

**Comment by bartlettroscoe** [comment]
@IgnatSergeev, no-one ever commented on this PR?  We are interested in potentially extending this `clang-refactor` tool.  Any suggestions or advance on doing so?  (You can contact me directly at rabartl@sandia.gov.)

**Comment by IgnatSergeev** [comment]
> @IgnatSergeev, no-one ever commented on this PR? We are interested in potentially extending this `clang-refactor` tool. Any suggestions or advance on doing so? (You can contact me directly at [rabartl@sandia.gov](mailto:rabartl@sandia.gov).)

Hey, glad you are interested, i was doing this as my side project, and it was a draft version, but i tried to expand clang-refactor with deletion of statements and other AST constructs

Later i decided to do much more general thing and integrated AST Matchers with AST Edits into Refactoring Engine (basically to do replacements)
And i actually have a PR inside my fork with code that implements it, since you became interested in extending clang-refactor, i will update that branch with latest main, create a new PR, and leave a link here

And again glad you became interested

**Comment by IgnatSergeev** [comment]
> @IgnatSergeev, no-one ever commented on this PR? We are interested in potentially extending this `clang-refactor` tool. Any suggestions or advance on doing so? (You can contact me directly at [rabartl@sandia.gov](mailto:rabartl@sandia.gov).)

I would love to hear some thoughts on it https://github.com/llvm/llvm-project/pull/123782

**Comment by bartlettroscoe** [comment]
> I would love to hear some thoughts on it #123782 Moreover, i have some (very simple and not very useful) refactoring actions based on those rules, test support for source location option, and tests that cover location option, and these actions; all of that is not included in linked PR

@IgnatSergeev, thanks for the response!  We will definitely look at #123782 and provide some feedback.

**Pull request closed without merging**
