### PR TITLE
[MIRPrinter] Don't print space when there is no successor

### PR DESCRIPTION
**Pull request by dianqk**
Extra space causes the checks generated by update_mir_test_checks to be unavailable.

```
# NOTE: Assertions have been autogenerated by utils/update_mir_test_checks.py UTC_ARGS: --version 4
# RUN: llc -mtriple=x86_64-- -o - %s -run-pass=none -verify-machineinstrs -simplify-mir | FileCheck %s
---
name: foo
body: |
  ; CHECK-LABEL: name: foo
  ; CHECK: bb.0:
  ; CHECK-NEXT:   successors:
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: {{  $}}
  ; CHECK-NEXT: bb.1:
  ; CHECK-NEXT:   RET 0, $eax
  bb.0:
    successors:

  bb.1:
    RET 0, $eax
...
```

The failure log is as follows:

```
llvm/test/CodeGen/MIR/X86/unreachable-block-print.mir:9:16: error: CHECK-NEXT: is on the same line as previous match
 ; CHECK-NEXT: {{ $}}
               ^
<stdin>:21:13: note: 'next' match was here
 successors:
            ^
<stdin>:21:13: note: previous match ended here
 successors:
```

### CODE REVIEW

**Comment by jayfoad** [comment]
> This also prints two line breaks, and I think we can delete one.

But you haven't done that in this patch, right?

**Review by jayfoad — APPROVED** [review]
LGTM.

**Comment by jayfoad** [comment]
> > > This also prints two line breaks, and I think we can delete one.
> > 
> > But you haven't done that in this patch, right?
> 
> This breaks many test cases. If appropriate, I'll create another PR.

I find it a little confusing to even mention it in the commit message, if the commit does not change it.

**Comment by DianQK** [comment]
> > > > This also prints two line breaks, and I think we can delete one.
> > > 
> > > 
> > > But you haven't done that in this patch, right?
> > 
> > 
> > This breaks many test cases. If appropriate, I'll create another PR.
> 
> I find it a little confusing to even mention it in the commit message, if the commit does not change it.

I'll update the commit message when I merge it.

(Lest I forget, I've updated the PR description.)

**Pull request merged**
