### PR TITLE
[X86][CodeGen] Restrict F128 lowering to GNU environment

### PR DESCRIPTION
**Pull request by pranavk**
Otherwise it breaks some environment like X64 Android that doesn't have f128 functions available in its libc.

Followup to #79611.

### CODE REVIEW

**Comment by aeubanks** [comment]
can you link to #79611 in the description?

shouldn't this update `llvm/test/CodeGen/X86/fp128-libcalls.ll`, which has a test with `-mtriple=x86_64-linux-android`?

**Comment by aeubanks** [comment]
yeah presubmit is complaining about it

**Comment by nikic** [comment]
This change only makes sense if X64 Android actually uses f128 arithmetic rather than f80 arithmetic in the `*l` builtins -- does it?

**Comment by pranavk** [comment]
Yes, that is what I expect Android is doing right now which is breaking it. But I don't know where and if it can be easily fixed in Android. This PR is an effort to avoid reverting the original PR to unbreak Android build for now.

**Comment by aeubanks** [comment]
https://godbolt.org/z/fhjEd3G4v shows that x64 Android uses f128 with `*l` builtins

**Review by aeubanks — APPROVED** [review]

**Pull request merged**
