### PR TITLE
[RISCV] Update V0Defs after moving Src in peepholes

### PR DESCRIPTION
**Pull request by lukel97**
If we move a pseudo in tryReduceVL or foldVMV_V_V via ensureDominates, its V0 definition may have changed so we need to update V0Defs.

This shouldn't have any functional change today since any pseudo which uses V0 won't be able to move past a new definition.

However this will matter if we add a peephole to convert unmasked pseudos to masked pseudos and add a use of V0.

### CODE REVIEW

**Comment by lukel97** [comment]
I just want to point out that I agree with the discussion in https://github.com/llvm/llvm-project/pull/106753/files#r1739182733, it's probably worthwhile looking into a smaller mapping in a future PR, e.g. only store instructions that use V0.

**Review by preames — APPROVED** [review]
LGTM

For anyone curious, I was initially concerned about the case where Def might change V0 itself, but realized that's prevented by the safe to move check.

**Comment by lukel97** [comment]
> LGTM
> 
> For anyone curious, I was initially concerned about the case where Def might change V0 itself, but realized that's prevented by the safe to move check.

Argh, now that you mention it this should actually be setting the definition to the one at Def->getNextNode().

**Comment by preames** [comment]
> Argh, now that you mention it this should actually be setting the definition to the one at Def->getNextNode().

Yes, but per the reasoning in my comment those must be the same.  :)

**Pull request merged**
