### PR TITLE
[SLP] Increase UsesLimit to 64

### PR DESCRIPTION
**Pull request by cyyself**
Since commit 82b800ecb35fb46881aa52000fa40b1b99aa654e addressed the issue #99327 , we see some performance regression (13%) on some verilator generated C++ code. This is because the UsesLimit is set to 8, which is too small for the verilator generated code. I have analyzed the need for the UsesLimit from [1] and found that the UsesLimit should be at least 64 to cover most of these cases. Thus, This patch increases the UsesLimit to 64.

Link: https://github.com/llvm/llvm-project/issues/99327#issuecomment-2236052879 [1]

### CODE REVIEW

**Comment by RKSimon** [comment]
I've created a branch (perf/slp_usecase_limit) to determine the effect on compile time - it should appear on https://llvm-compile-time-tracker.com/?config=Overview&stat=instructions%3Au&remote=RKSimon in the next hour

**Comment by dtcxzyw** [comment]
> I've created a branch (perf/slp_usecase_limit) to determine the effect on compile time - it should appear on https://llvm-compile-time-tracker.com/?config=Overview&stat=instructions%3Au&remote=RKSimon in the next hour

https://llvm-compile-time-tracker.com/compare.php?from=da0c8b275564f814a53a5c19497669ae2d99538d&to=23a9e6da423b4c6a1fda68d3d497a32ff2b04ec0&stat=instructions:u

**Comment by alexey-bataev** [comment]
> https://llvm-compile-time-tracker.com/compare.php?from=da0c8b275564f814a53a5c19497669ae2d99538d&to=23a9e6da423b4c6a1fda68d3d497a32ff2b04ec0&stat=instructions:u

Looks good in general (?)

**Comment by dtcxzyw** [comment]
> > https://llvm-compile-time-tracker.com/compare.php?from=da0c8b275564f814a53a5c19497669ae2d99538d&to=23a9e6da423b4c6a1fda68d3d497a32ff2b04ec0&stat=instructions:u
> 
> Looks good in general (?)

Yeah. Surprisingly it also improves the performance of clang stage2-build.

**Comment by alexey-bataev** [comment]
> > > https://llvm-compile-time-tracker.com/compare.php?from=da0c8b275564f814a53a5c19497669ae2d99538d&to=23a9e6da423b4c6a1fda68d3d497a32ff2b04ec0&stat=instructions:u
> > 
> > 
> > Looks good in general (?)
> 
> Yeah. Surprisingly it also improves the performance of clang stage2-build.

Most probably, it has lots of uses, which must be replaced by the new extractelement instructions. And if the number is >8 but <64, better to walk over actual uses, rather than all uses (including those, potentially deleted/dropped a bit later)

**Review by alexey-bataev — APPROVED** [review]
LG

**Pull request merged**
