### PR TITLE
fix(python): fix comparison to None

### PR DESCRIPTION
**Pull request by e-kwsm**

### CODE REVIEW

**Comment by ftynse** [comment]
Please provide a proper patch description, i.e., why the change is being made.

**Comment by e-kwsm** [comment]
From [PEP8](https://peps.python.org/pep-0008/#programming-recommendations):

> Comparisons to singletons like None should always be done with `is` or `is not`, never the equality operators.

[flake8](https://flake8.pycqa.org/en/latest/) is used here.

**Comment by ftynse** [comment]
This should be included in the actual commit, not GitHub comments.

**Comment by e-kwsm** [comment]
Commit message is updated/

**Review by ftynse — APPROVED** [review]
LGTM for the MLIR part. Please seek approval from relevant reviewers for all other subprojects.

**Review by mtrofin — APPROVED** [review]
LGTM for the `ctx_profile` part.

**Comment by DavidSpickett** [comment]
LLVM uses a GitHub setting where the PR is squashed, and the commit message is taken from the PR description rather than the commits themselves. So all you have to do here is copy the commit message you updated into the PR's description.

**Review by DavidSpickett — APPROVED** [review]
LLDB changes look good to me.

**Review by teresajohnson — APPROVED** [review]
compiler-rt changes lgtm

**Review by ChuanqiXu9 — APPROVED** [review]

**Review by JDevlieghere — COMMENTED** [review]
This should really be broken up into separate PRs per subproject. One large PR like this makes reviewing harder and causes unnecessary churn in the case that this gets reverted.

**Review by joker-eph — APPROVED** [review]
If you can push this to main in separate commits (one per project as it was mentioned?), that'd be great!

**Comment by makslevental** [comment]
It's a `sed s/== None/is None/g` - what is there to review? 10 separate PRs for the same exact `sed` costs more in commit noise (and effort on the part of @e-kwsm) than one solid, patient, review here.

**Review by makslevental — APPROVED** [review]
There you go - diligently reviewed using GitHub 's fantastic UI.

Screenshot_20240517_011154_com android chrome

**Comment by ftynse** [comment]
> 10 separate commits/PRs for the same exact sed costs more in commit noise (and effort on the part of @e-kwsm) than one solid, patient, review here

Not unless you subscribe only to a subproject. FWIW, I'm not comfortable blanket approving changes, however trivial, to subprojects I'm not actively working on, and I suspect most folks here are not. Subprojects may have some ongoing work that will be disrupted or reasons why they chose the suboptimal implementation.

**Comment by JDevlieghere** [comment]
> It's a `sed s/== None/is None/g` - what is there to review? 10 separate commits/PRs for the same exact `sed` costs more in commit noise (and effort on the part of @e-kwsm) than one solid, patient, review here.

In addition to what @ftynse said above, the `sed` might not be the right thing in the first place (e.g. #91858).

**Comment by joker-eph** [comment]
> It's a sed s/== None/is None/g - what is there to review?

On my I'm not asking for more reviews, this is why I commented that this should be **pushed** in multiple commits, I don't even need to see PRs.

Another thing also mentioned above was the problem of reverts.
If there is a problem in one of the project and this needs to be reverted, then it'll affect the other projects.
Also imagine that this lands, then someone refactor the python code in MLIR, and then LLDB finds an issue and tries to revert. They have now to figure out why is there a merge conflicts.

More commits in the history for unrelated projects does not seem like "noise" to me.

When I apply automated linter (clang-tidy), I will split these into 1 commit per file and push these.

**Comment by e-kwsm** [comment]
broken into

- #94012
- #94013
- #94014
- #94015
- #94016
- #94017
- #94018
- #94019
- #94020
- #94021
- #94022

**Pull request closed without merging**
