### PR TITLE
[clang][NFC] Regroup declarations in `Sema`

### PR DESCRIPTION
**Pull request by Endilll**
This patch regroups declarations in `Sema` based on the file they are implemented in (e.g. `SemaChecking.cpp`). This allows to logically split `Sema` in 42 groups. No physical separation is done (e.g. splitting `Sema` into multiple classes). Table of contents added at the very beginning of `Sema`. Grouping is reflected in Doxygen commands, so structure of API reference of `Sema` is also significantly improved ([example from official documentation](https://www.doxygen.nl/manual/examples/memgrp/html/class_memgrp___test.html), [comparison of Sema API reference](https://github.com/llvm/llvm-project/pull/82217#issuecomment-1954567763)).

While grouping is intentional, as well as each group consisting of `public` declarations followed by `private` ones (without changing access in-between), exact contents and order of declarations of each group is partially carried over from old structure, partially accidental due to time constrains to do the regrouping over the weekend (`Sema` is just enormously big). Data members and inline function definitions in `Sema.h` complicate the matter, since it's not obvious which group they belong to. Further work is expected to refine contents and order of declarations.

What is also intentional is some kind of layering, where Concepts group follows template groups, and ObjC, code completion, CUDA, HLSL, OpenACC, OpenMP, and SYCL are all placed at the end of the file, after C and C++ parts of `Sema`.

I used `clang-query` to verify that access specifiers were preserved during the process (https://gcc.godbolt.org/z/9johffY9T, thank you @ilya-biryukov). Only the following 3 member types were converted from `private` to `public` because of limitations of the new grouping: `DeclareTargetContextInfo`, `TypoExprState`, `SatisfactionStackEntryTy`.

Member initializer list of `Sema` in `Sema.cpp` is rewritten to reflect new order of data members in order to avoid `-Wreorder-ctor`.

Since this patch touches almost every line in `Sema.h`, it was considered appropriate to run clang-format on the whole file, and not just on changed lines.

### CODE REVIEW

**Comment by Endilll** [comment]
I've built doxygen documentation locally. Now I see what I expected so see (proper member groups).

**Comment by tbaederr** [comment]
> 11,427 additions, 11,178 deletions not shown because the diff is too large. Please use a local Git client to view these changes.

Never seen that before, haha.

**Comment by cor3ntin** [comment]
This is going to be rather disruptive on downstream projects.
At least we should wait until after the release of clang 18 to merge it, to avoid endless merge conflicts

**Comment by erichkeane** [comment]
> This is going to be rather disruptive on downstream projects. At least we should wait until after the release of clang 18 to merge it, to avoid endless merge conflicts

For the most part, git will handle these pretty well on downstreams I think, and as they are declarations, I suspect this isn't going to be super tough of a merge conflict.  That said, waiting until after 18 is perhaps a good diea.

>  Table of contents added at the very beginning of `Sema`. Grouping is reflected in Doxygen commands, so structure of API reference of `Sema` is also significantly improved ([example from official documentation](https://www.doxygen.nl/manual/examples/memgrp/html/class_memgrp___test.html)).

Neat!
> 
> While grouping is intentional, as well as each group consisting of `public` declarations followed by `private` ones (without changing access in-between),

I MIGHT suggest private followed by public?  It is a not-uncommon pattern I've seen to have a private 'helper' class(or data member) defined inline, that is then used by inline-defined public functions.  

>Data members and inline function definitions in `Sema.h` complicate the matter, since it's not obvious which group they belong to. Further work is expected to refine contents and order of declarations.

This IS going to be complicated unfortunately.  Many of the function definitions at least are going to be 1-liners that are just calling into a different definition.  Data members you'll probably have to hunt down where they are used to see the relationship.

> What is also intentional is some kind of layering, where Concepts group follows template groups, and ObjC, code completion, CUDA, HLSL, OpenACC, OpenMP, and SYCL are all placed at the end of the file, after C and C++ parts of `Sema`.

 
> Member initializer list of `Sema` in `Sema.cpp` is rewritten to reflect new order of data members in order to avoid `-Wreorder-ctor`.

I wouldn't mind some sort of 'static_assert' to ensure that this doesn't accidentally increase the size of Sema or cause some sort of pessimization for layout.  I realize we're not particularly concerned about the size, but I could imagine goofy things going on.

**Comment by Endilll** [comment]
That's how API reference looks with this patch. I specifically picked small groups to showcase member grouping.
image
Existing API reference can be found here: https://clang.llvm.org/doxygen/classclang_1_1Sema.html

**Comment by Endilll** [comment]
@erichkeane 

> That said, waiting until after 18 is perhaps a good diea.

Resolving merge conflicts that will arise in the meantime is not going to be trivial, but should be doable in a reasonable time. So I'm willing to wait.

> I MIGHT suggest private followed by public? It is a not-uncommon pattern I've seen to have a private 'helper' class(or data member) defined inline, that is then used by inline-defined public functions.

I don't mind either way, as long as we don't inserting a couple of private members in the middle of public section.

> I wouldn't mind some sort of 'static_assert' to ensure that this doesn't accidentally increase the size of Sema

Checking on Linux, `sizeof(Sema)` is 18824 bytes at moment. This patch increases that by 24 bytes, to `18848`. I don't deem it significant enough to care for an object this big, but I can claw it back if this is considered important.

> or cause some sort of pessimization for layout. I realize we're not particularly concerned about the size, but I could imagine goofy things going on.

If there was an intent to put some data members first to improve cache hits, I think it has been lost by this point. Our first non-static data members are `OpenCLOptions OpenCLFeatures` and `FPOptions CurFPFeatures` at the moment. Since this patch puts generic Sema stuff (`Sema.cpp`) first, opportunity to put widely used data members first is still there. As I mentioned in the description, follow-up patches that improve ordering in each particular section are expected.

**Comment by erichkeane** [comment]
> @erichkeane
> 
> > That said, waiting until after 18 is perhaps a good diea.
> 
> Resolving merge conflicts that will arise in the meantime is not going to be trivial, but should be doable in a reasonable time. So I'm willing to wait.
> 

I'm glad to hear that!  I'm hopeful it isn't TOO much of a delay and not too much work. Sema.h changes are at least pretty innocuous/small.

> > I MIGHT suggest private followed by public? It is a not-uncommon pattern I've seen to have a private 'helper' class(or data member) defined inline, that is then used by inline-defined public functions.
> 
> I don't mind either way, as long as we don't inserting a couple of private members in the middle of public section.
> 

I agree with the goal as well!

> > I wouldn't mind some sort of 'static_assert' to ensure that this doesn't accidentally increase the size of Sema
> 
> Checking on Linux, `sizeof(Sema)` is 18824 bytes at moment. This patch increases that by 24 bytes, to `18848`. I don't deem it significant enough to care for an object this big, but I can claw it back if this is considered important.
>

Urgh, and double-urgh. Yeah, not big enough/important enough, we only ever instantiate a handful of Sema objects anyway at most.
 
> > or cause some sort of pessimization for layout. I realize we're not particularly concerned about the size, but I could imagine goofy things going on.
> 
> If there was an intent to put some data members first to improve cache hits, I think it has been lost by this point. Our first non-static data members are `OpenCLOptions OpenCLFeatures` and `FPOptions CurFPFeatures` at the moment. Since this patch puts generic Sema stuff (`Sema.cpp`) first, opportunity to put widely used data members first is still there. As I mentioned in the description, follow-up patches that improve ordering in each particular section are expected.

"Commonly used" stuff together perhaps has some value for cache-locality reasons (as well as any other "closely related" stuff with itself), but I don't have a good way to measure that so 'best effort' here is probably good enough/the changes you're intending a good enough attempt.

**Comment by to268** [comment]
FYI: There is currently 26 PRs that impacts `Sema.h`, bellow is the bash one liner with GitHub CLI to count the numbers of impacted PRs and another one to list links to impacted PRs.

- Count all impacted PRs:
```bash
gh pr list --json files --jq '.[] | {paths: [.files[].path | select(. == "clang/include/clang/Sema/Sema.h")]} | select(.paths | length > 0)' -L 30000 | wc -l
```
- List the link to all impacted PRs:
```bash
gh pr list --json number,files --jq '.[] | select(.files[].path == "clang/include/clang/Sema/Sema.h") | {number}' -L 30000 | cut -d ':' -f2 | tr -d '}' | sed 's|^|https://github.com/llvm/llvm-project/pull/|'
```

**Comment by Endilll** [comment]
Funny enough, search in the web versions shows only 23 PRs: https://github.com/llvm/llvm-project/pulls?q=is%3Apr+is%3Aopen+%22clang%2Finclude%2Fclang%2FSema%2FSema.h%22

**Comment by tstellar** [comment]
This will make backports more difficult, but I think it's OK.  If we wanted to avoid impacting backports, we'd have to wait ~10 weeks to merge this, but that doesn't seem practical.

**Comment by zyn0217** [comment]
> That's because you are filtering only opened PRs, not including drafts PRs. For example there is this draft PR: https://github.com/llvm/llvm-project/pull/81095/files

(I think my recent PR https://github.com/llvm/llvm-project/pull/82310 now supersedes my two draft PRs, and they can be closed now.)

**Comment by cor3ntin** [comment]
Please run clang-format as a separate PR (before this one) - this will help folks deal with merge conflicts. Thanks

**Pull request merged**
