### PR TITLE
[RISCV][GISel] Add gisel-commandline-option.ll similar to AArch64.

### PR DESCRIPTION
**Pull request by topperc**
This allows us to see the pass pipeline for GlobalISel.

### CODE REVIEW

**Review by aemerson — APPROVED** [review]
LGTM.

**Comment by haoNoQ** [comment]
The new test appears to be failing on a darwin "expensive checks" buildbot. Craig, may I ask you to take a quick look? (It processes commits in large batches and your patch was obstructed by someone else's failure so you probably didn't get an email about it.)

https://green.lab.llvm.org/green/job/clang-stage1-cmake-RA-expensive/25689/

```
+ : 'RUN: at line 1'
+ /Users/buildslave/jenkins/workspace/clang-stage1-cmake-RA-expensive/clang-build/bin/llc -mtriple=riscv64-- -debug-pass=Structure /Users/buildslave/jenkins/workspace/clang-stage1-cmake-RA-expensive/llvm-project/llvm/test/CodeGen/RISCV/GlobalISel/gisel-commandline-option.ll -o /dev/null -O0 -global-isel
+ /Users/buildslave/jenkins/workspace/clang-stage1-cmake-RA-expensive/clang-build/bin/FileCheck /Users/buildslave/jenkins/workspace/clang-stage1-cmake-RA-expensive/llvm-project/llvm/test/CodeGen/RISCV/GlobalISel/gisel-commandline-option.ll --check-prefix ENABLED --check-prefix NOFALLBACK
/Users/buildslave/jenkins/workspace/clang-stage1-cmake-RA-expensive/llvm-project/llvm/test/CodeGen/RISCV/GlobalISel/gisel-commandline-option.ll:17:17: error: ENABLED-NEXT: is not on the line after the previous match
; ENABLED-NEXT: Analysis containing CSE Info
                ^
<stdin>:31:2: note: 'next' match was here
 Analysis containing CSE Info
 ^
<stdin>:29:14: note: previous match ended here
 IRTranslator
             ^
<stdin>:30:1: note: non-matching line after previous match is here
 Verify generated machine code
^

Input file: <stdin>
Check file: /Users/buildslave/jenkins/workspace/clang-stage1-cmake-RA-expensive/llvm-project/llvm/test/CodeGen/RISCV/GlobalISel/gisel-commandline-option.ll

-dump-input=help explains the following input dump.

Input was:
<<<<<<
         .
         .
         .
        26:  Insert stack protectors 
        27:  Module Verifier 
        28:  Analysis containing CSE Info 
        29:  IRTranslator 
        30:  Verify generated machine code 
        31:  Analysis containing CSE Info 
next:17      !~~~~~~~~~~~~~~~~~~~~~~~~~~~  error: match on wrong line
        32:  Analysis for ComputingKnownBits 
        33:  Legalizer 
        34:  Verify generated machine code 
        35:  RegBankSelect 
        36:  Verify generated machine code 
         .
         .
         .
>>>>>>
```

**Comment by topperc** [comment]
> The new test appears to be failing on a darwin "expensive checks" buildbot. Craig, may I ask you to take a quick look? (It processes commits in large batches and your patch was obstructed by someone else's failure so you probably didn't get an email about it.)
> 
> https://green.lab.llvm.org/green/job/clang-stage1-cmake-RA-expensive/25689/
> 
> ```
> + : 'RUN: at line 1'
> + /Users/buildslave/jenkins/workspace/clang-stage1-cmake-RA-expensive/clang-build/bin/llc -mtriple=riscv64-- -debug-pass=Structure /Users/buildslave/jenkins/workspace/clang-stage1-cmake-RA-expensive/llvm-project/llvm/test/CodeGen/RISCV/GlobalISel/gisel-commandline-option.ll -o /dev/null -O0 -global-isel
> + /Users/buildslave/jenkins/workspace/clang-stage1-cmake-RA-expensive/clang-build/bin/FileCheck /Users/buildslave/jenkins/workspace/clang-stage1-cmake-RA-expensive/llvm-project/llvm/test/CodeGen/RISCV/GlobalISel/gisel-commandline-option.ll --check-prefix ENABLED --check-prefix NOFALLBACK
> /Users/buildslave/jenkins/workspace/clang-stage1-cmake-RA-expensive/llvm-project/llvm/test/CodeGen/RISCV/GlobalISel/gisel-commandline-option.ll:17:17: error: ENABLED-NEXT: is not on the line after the previous match
> ; ENABLED-NEXT: Analysis containing CSE Info
>                 ^
> <stdin>:31:2: note: 'next' match was here
>  Analysis containing CSE Info
>  ^
> <stdin>:29:14: note: previous match ended here
>  IRTranslator
>              ^
> <stdin>:30:1: note: non-matching line after previous match is here
>  Verify generated machine code
> ^
> 
> Input file: <stdin>
> Check file: /Users/buildslave/jenkins/workspace/clang-stage1-cmake-RA-expensive/llvm-project/llvm/test/CodeGen/RISCV/GlobalISel/gisel-commandline-option.ll
> 
> -dump-input=help explains the following input dump.
> 
> Input was:
> <<<<<<
>          .
>          .
>          .
>         26:  Insert stack protectors 
>         27:  Module Verifier 
>         28:  Analysis containing CSE Info 
>         29:  IRTranslator 
>         30:  Verify generated machine code 
>         31:  Analysis containing CSE Info 
> next:17      !~~~~~~~~~~~~~~~~~~~~~~~~~~~  error: match on wrong line
>         32:  Analysis for ComputingKnownBits 
>         33:  Legalizer 
>         34:  Verify generated machine code 
>         35:  RegBankSelect 
>         36:  Verify generated machine code 
>          .
>          .
>          .
> >>>>>>
> ```

I think I fixed this with this patch earlier today

commit bb810d8fa06bf056d848bccc399bf287201a04f2
Author: Craig Topper <craig.topper@sifive.com>
Date:   Wed Sep 6 09:31:50 2023

    [RISCV] Disable machine verifier in gisel-commandline-option.ll. NFC
    
    Hopefully this fixes the expensive checks build.

**Comment by haoNoQ** [comment]
Ooo nice nvm then, thanks!

**Pull request merged**
