### PR TITLE
[SLP]Improve minbitwidth analysis.

### PR DESCRIPTION
**Pull request by alexey-bataev**
This improves overall analysis for minbitwidth in SLP. It allows to
analyze the trees with store/insertelement root nodes. Also, instead of
using single minbitwidth, detected from the very first analysis stage,
it tries to detect the best one for each trunc/ext subtree in the graph
and use it for the subtree.
Results in better code and less vector register pressure.

Metric: size..text

Program                                                                                                                                                size..text
                                                                                                                                                       results     results0    diff
                                                                      test-suite :: SingleSource/Benchmarks/Adobe-C++/simple_types_loop_invariant.test    92549.00    92609.00  0.1%
                                                                                  test-suite :: External/SPEC/CINT2017speed/625.x264_s/625.x264_s.test   663381.00   663493.00  0.0%
                                                                                   test-suite :: External/SPEC/CINT2017rate/525.x264_r/525.x264_r.test   663381.00   663493.00  0.0%
                                                                                               test-suite :: MultiSource/Benchmarks/Bullet/bullet.test   307182.00   307214.00  0.0%
                                                                             test-suite :: External/SPEC/CFP2017speed/638.imagick_s/638.imagick_s.test  1394420.00  1394484.00  0.0%
                                                                              test-suite :: External/SPEC/CFP2017rate/538.imagick_r/538.imagick_r.test  1394420.00  1394484.00  0.0%
                                                                                test-suite :: External/SPEC/CFP2017rate/510.parest_r/510.parest_r.test  2040257.00  2040273.00  0.0%

                                                                              test-suite :: External/SPEC/CFP2017rate/526.blender_r/526.blender_r.test 12396098.00 12395858.00 -0.0%
                                                                                         test-suite :: External/SPEC/CINT2006/445.gobmk/445.gobmk.test   909944.00   909768.00 -0.0%

SingleSource/Benchmarks/Adobe-C++/simple_types_loop_invariant - 4 scalar
instructions remain scalar (good).
Spec2017/x264 - the whole function idct4x4dc is vectorized using <16
x i16> instead of <16 x i32>, also zext/trunc are removed. In other
places last vector zext/sext removed and replaced by
extractelement + scalar zext/sext pair.
MultiSource/Benchmarks/Bullet/bullet - reduce or <4 x i32> replaced by
reduce or <4 x i8>
Spec2017/imagick - Removed extra zext from 2 packs of the operations.
Spec2017/parest - Removed extra zext, replaced by extractelement+scalar
zext
Spec2017/blender - the whole bunch of vector zext/sext replaced by
extractelement+scalar zext/sext, some extra code vectorized in smaller
types.
Spec2006/gobmk - fixed cost estimation, some small code remains scalar.

Original Pull Request: https://github.com/llvm/llvm-project/pull/78976

### CODE REVIEW

**Comment by jyknight** [comment]
This PR was merged, without
1. any information on what the changes were since it was reverted, or
2. being reviewed, or
3. fixing -- or even acknowledging -- the xxhash miscompile I reported on the previous PR.

So, I'm going to re-revert this. I can work to get a standalone reproduction example for the xxhash issue if you need.

**Comment by alexey-bataev** [comment]
xxxhash was fixed, I would not commit it without fixing it.

**Comment by alexey-bataev** [comment]
This patch is almost the same, just contains small fix for xxxhash (one line fix in line 13980) + some changes to improve compile time. Everything else the same

**Comment by jyknight** [comment]
Thanks for the quick response with the info on what was changed, and that there was an intent to fix the xxhash miscompile!

Given that response, I went to double-check my work to see if I'd made a mistake in testing. Unfortunately, not. I've now re-verified that the test still fails with clang built at this revision, and doesn't fail with clang built at the prior revision.

Maybe interesting (or maybe not), now the check with size 129 _also_ fails.

```
third_party/llvm/llvm-project/llvm/unittests/Support/xxhashTest.cpp:48: Failure
Expected equality of these values:
  uint64_t(0x9013fb74ca603e0c)
    Which is: 10381918045049208332
  xxh3_64bits(ArrayRef(a, size_t(33)))
    Which is: 3308700454355487325

third_party/llvm/llvm-project/llvm/unittests/Support/xxhashTest.cpp:49: Failure
Expected equality of these values:
  uint64_t(0xfa5271fcce0db1c3)
    Which is: 18037604788174959043
  xxh3_64bits(ArrayRef(a, size_t(64)))
    Which is: 15548882779349196076

third_party/llvm/llvm-project/llvm/unittests/Support/xxhashTest.cpp:50: Failure
Expected equality of these values:
  uint64_t(0x79c42431727f1012)
    Which is: 8774177768817496082
  xxh3_64bits(ArrayRef(a, size_t(65)))
    Which is: 9026354738766114493

third_party/llvm/llvm-project/llvm/unittests/Support/xxhashTest.cpp:51: Failure
Expected equality of these values:
  uint64_t(0x591ee0ddf9c9ccd1)
    Which is: 6421817362660052177
  xxh3_64bits(ArrayRef(a, size_t(96)))
    Which is: 14257441473594075054

third_party/llvm/llvm-project/llvm/unittests/Support/xxhashTest.cpp:52: Failure
Expected equality of these values:
  uint64_t(0x8ffc6a3111fe19da)
    Which is: 10375284400542587354
  xxh3_64bits(ArrayRef(a, size_t(97)))
    Which is: 17112387889451439326

third_party/llvm/llvm-project/llvm/unittests/Support/xxhashTest.cpp:53: Failure
Expected equality of these values:
  uint64_t(0x06a146ee9a2da378)
    Which is: 477741026080826232
  xxh3_64bits(ArrayRef(a, size_t(128)))
    Which is: 15939254768337478897

third_party/llvm/llvm-project/llvm/unittests/Support/xxhashTest.cpp:54: Failure
Expected equality of these values:
  uint64_t(0xbc7138129bf065da)
    Which is: 13578696004075546074
  xxh3_64bits(ArrayRef(a, size_t(129)))
    Which is: 14895047307860736276
```

**Comment by fmayer** [comment]
This breaks MSAN buildbot: https://lab.llvm.org/buildbot/#/builders/74/builds/26470/steps/12/logs/stdio

```
/b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm_build_msan/bin/clang++ -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm_build2_msan/lib/Support -I/b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/lib/Support -I/b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm_build2_msan/include -I/b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -Werror=global-constructors -O3 -DNDEBUG -UNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -MD -MT lib/Support/CMakeFiles/LLVMSupport.dir/xxhash.cpp.o -MF lib/Support/CMakeFiles/LLVMSupport.dir/xxhash.cpp.o.d -o lib/Support/CMakeFiles/LLVMSupport.dir/xxhash.cpp.o -c /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/lib/Support/xxhash.cpp
==2146450==WARNING: MemorySanitizer: use-of-uninitialized-value
    #0 0x55c2665958a9 in operator() /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp:14122:35
    #1 0x55c2665958a9 in llvm::slpvectorizer::BoUpSLP::computeMinimumValueSizes() /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp:14179:28
    #2 0x55c2665aa8a2 in llvm::SLPVectorizerPass::tryToVectorizeList(llvm::ArrayRef<llvm::Value*>, llvm::slpvectorizer::BoUpSLP&, bool) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp:14724:9
    #3 0x55c2665ac854 in llvm::SLPVectorizerPass::tryToVectorize(llvm::Instruction*, llvm::slpvectorizer::BoUpSLP&) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp
    #4 0x55c2665b4c31 in llvm::SLPVectorizerPass::tryToVectorize(llvm::ArrayRef<llvm::WeakTrackingVH>, llvm::slpvectorizer::BoUpSLP&) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp:16561:14
    #5 0x55c26659f16f in vectorizeRootInstruction /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp:16552:10
    #6 0x55c26659f16f in llvm::SLPVectorizerPass::vectorizeChainsInBlock(llvm::BasicBlock*, llvm::slpvectorizer::BoUpSLP&) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp:17091:22
    #7 0x55c26659744e in llvm::SLPVectorizerPass::runImpl(llvm::Function&, llvm::ScalarEvolution*, llvm::TargetTransformInfo*, llvm::TargetLibraryInfo*, llvm::AAResults*, llvm::LoopInfo*, llvm::DominatorTree*, llvm::AssumptionCache*, llvm::DemandedBits*, llvm::OptimizationRemarkEmitter*) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp:14313:16
    #8 0x55c266596608 in llvm::SLPVectorizerPass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/lib/Transforms/Vectorize/SLPVectorizer.cpp:14244:18
    #9 0x55c265c24e31 in llvm::detail::PassModel<llvm::Function, llvm::SLPVectorizerPass, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/include/llvm/IR/PassManagerInternal.h:90:17
    #10 0x55c2614e9c2d in llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/include/llvm/IR/PassManager.h:243:40
    #11 0x55c25c3a4a61 in llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/include/llvm/IR/PassManagerInternal.h:90:17
    #12 0x55c2614f4702 in llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/lib/IR/PassManager.cpp:123:38
    #13 0x55c25c3a43c1 in llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/include/llvm/IR/PassManagerInternal.h:90:17
    #14 0x55c2614e7036 in llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/include/llvm/IR/PassManager.h:243:40
    #15 0x55c2639695ea in (anonymous namespace)::EmitAssemblyHelper::RunOptimizationPipeline(clang::BackendAction, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>&, std::__1::unique_ptr<llvm::ToolOutputFile, std::__1::default_delete<llvm::ToolOutputFile>>&, clang::BackendConsumer*) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1109:9
    #16 0x55c263952be3 in EmitAssembly /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1174:3
    #17 0x55c263952be3 in clang::EmitBackendOutput(clang::DiagnosticsEngine&, clang::HeaderSearchOptions const&, clang::CodeGenOptions const&, clang::TargetOptions const&, clang::LangOptions const&, llvm::StringRef, llvm::Module*, clang::BackendAction, llvm::IntrusiveRefCntPtr<llvm::vfs::FileSystem>, std::__1::unique_ptr<llvm::raw_pwrite_stream, std::__1::default_delete<llvm::raw_pwrite_stream>>, clang::BackendConsumer*) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/lib/CodeGen/BackendUtil.cpp:1336:13
    #18 0x55c2639ac4ff in clang::BackendConsumer::HandleTranslationUnit(clang::ASTContext&) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/lib/CodeGen/CodeGenAction.cpp:388:3
    #19 0x55c2688145d6 in clang::ParseAST(clang::Sema&, bool, bool) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/lib/Parse/ParseAST.cpp:176:13
    #20 0x55c26442022d in clang::FrontendAction::Execute() /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/lib/Frontend/FrontendAction.cpp:1069:8
    #21 0x55c26428b983 in clang::CompilerInstance::ExecuteAction(clang::FrontendAction&) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/lib/Frontend/CompilerInstance.cpp:1057:33
    #22 0x55c26467ad02 in clang::ExecuteCompilerInvocation(clang::CompilerInstance*) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/lib/FrontendTool/ExecuteCompilerInvocation.cpp:272:25
    #23 0x55c25b862cc6 in cc1_main(llvm::ArrayRef<char const*>, char const*, void*) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/tools/driver/cc1_main.cpp:232:15
    #24 0x55c25b85b0f4 in ExecuteCC1Tool(llvm::SmallVectorImpl<char const*>&, llvm::ToolContext const&) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/tools/driver/driver.cpp:343:12
    #25 0x55c263e7c960 in operator() /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:12
    #26 0x55c263e7c960 in operator() /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/lib/Driver/Job.cpp:440:34
    #27 0x55c263e7c960 in void llvm::function_ref<void ()>::callback_fn<clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__1::optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const::$_0>(long) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45:12
    #28 0x55c2622a1330 in operator() /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68:12
    #29 0x55c2622a1330 in llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:426:3
    #30 0x55c263e7a912 in clang::driver::CC1Command::Execute(llvm::ArrayRef<std::__1::optional<llvm::StringRef>>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>*, bool*) const /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/lib/Driver/Job.cpp:440:12
    #31 0x55c263dc8a01 in clang::driver::Compilation::ExecuteCommand(clang::driver::Command const&, clang::driver::Command const*&, bool) const /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/lib/Driver/Compilation.cpp:199:15
    #32 0x55c263dc96d9 in clang::driver::Compilation::ExecuteJobs(clang::driver::JobList const&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*>>&, bool) const /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/lib/Driver/Compilation.cpp:253:19
    #33 0x55c263e1f538 in clang::driver::Driver::ExecuteCompilation(clang::driver::Compilation&, llvm::SmallVectorImpl<std::__1::pair<int, clang::driver::Command const*>>&) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/lib/Driver/Driver.cpp:1920:5
    #34 0x55c25b858f53 in clang_main(int, char**, llvm::ToolContext const&) /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm-project/clang/tools/driver/driver.cpp:518:21
    #35 0x55c25b882233 in main /b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm_build_msan/tools/clang/tools/driver/clang-driver.cpp:17:10
    #36 0x7f2741a23a8f  (/lib/x86_64-linux-gnu/libc.so.6+0x23a8f) (BuildId: d320ce4e63925d698610ed423fc4b1f0e8ed51f1)
    #37 0x7f2741a23b48 in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x23b48) (BuildId: d320ce4e63925d698610ed423fc4b1f0e8ed51f1)
    #38 0x55c25b7c0c64 in _start (/b/sanitizer-x86_64-linux-bootstrap-msan/build/llvm_build_msan/bin/clang-19+0x522ec64)

```

**Comment by alexey-bataev** [comment]
Ok, I'll revert the patch and try one more time to fix xxhash/memsan issues.

**Comment by alexey-bataev** [comment]
> Thanks for the quick response with the info on what was changed, and that there was an intent to fix the xxhash miscompile!
> 
> Given that response, I went to double-check my work to see if I'd made a mistake in testing. Unfortunately, not. I've now re-verified that the test still fails with clang built at this revision, and doesn't fail with clang built at the prior revision.
> 
> Maybe interesting (or maybe not), now the check with size 129 _also_ fails.
> 
> ```
> third_party/llvm/llvm-project/llvm/unittests/Support/xxhashTest.cpp:48: Failure
> Expected equality of these values:
>   uint64_t(0x9013fb74ca603e0c)
>     Which is: 10381918045049208332
>   xxh3_64bits(ArrayRef(a, size_t(33)))
>     Which is: 3308700454355487325
> 
> third_party/llvm/llvm-project/llvm/unittests/Support/xxhashTest.cpp:49: Failure
> Expected equality of these values:
>   uint64_t(0xfa5271fcce0db1c3)
>     Which is: 18037604788174959043
>   xxh3_64bits(ArrayRef(a, size_t(64)))
>     Which is: 15548882779349196076
> 
> third_party/llvm/llvm-project/llvm/unittests/Support/xxhashTest.cpp:50: Failure
> Expected equality of these values:
>   uint64_t(0x79c42431727f1012)
>     Which is: 8774177768817496082
>   xxh3_64bits(ArrayRef(a, size_t(65)))
>     Which is: 9026354738766114493
> 
> third_party/llvm/llvm-project/llvm/unittests/Support/xxhashTest.cpp:51: Failure
> Expected equality of these values:
>   uint64_t(0x591ee0ddf9c9ccd1)
>     Which is: 6421817362660052177
>   xxh3_64bits(ArrayRef(a, size_t(96)))
>     Which is: 14257441473594075054
> 
> third_party/llvm/llvm-project/llvm/unittests/Support/xxhashTest.cpp:52: Failure
> Expected equality of these values:
>   uint64_t(0x8ffc6a3111fe19da)
>     Which is: 10375284400542587354
>   xxh3_64bits(ArrayRef(a, size_t(97)))
>     Which is: 17112387889451439326
> 
> third_party/llvm/llvm-project/llvm/unittests/Support/xxhashTest.cpp:53: Failure
> Expected equality of these values:
>   uint64_t(0x06a146ee9a2da378)
>     Which is: 477741026080826232
>   xxh3_64bits(ArrayRef(a, size_t(128)))
>     Which is: 15939254768337478897
> 
> third_party/llvm/llvm-project/llvm/unittests/Support/xxhashTest.cpp:54: Failure
> Expected equality of these values:
>   uint64_t(0xbc7138129bf065da)
>     Which is: 13578696004075546074
>   xxh3_64bits(ArrayRef(a, size_t(129)))
>     Which is: 14895047307860736276
> ```

Hmm, this is what I see for both SSE and AVX512
[----------] 2 tests from xxhashTest
[ RUN      ] xxhashTest.Basic
[       OK ] xxhashTest.Basic (0 ms)
[ RUN      ] xxhashTest.xxh3
[       OK ] xxhashTest.xxh3 (0 ms)
[----------] 2 tests from xxhashTest (0 ms total)

Can you provide your build flags? Also, did you try upstream compiler or downstream?

**Pull request merged**
