### PR TITLE
[NFC] Fix uninitialized scalar field in constructor.

### PR DESCRIPTION
**Pull request by zahiraam**
Non-static class field is not initialized in constructor.

### CODE REVIEW

**Review by tahonermann — CHANGES_REQUESTED** [review]
How did you decide on `IndexContents::All` as the default initialization value. I would be more inclined towards `IndexContents::None`.

I think it would be preferred to use a member initializer in the declaration of `IdxContents`. That will ensure an initialization is performed if additional constructors are added.

**Comment by zahiraam** [comment]
> How did you decide on `IndexContents::All` as the default initialization value. I would be more inclined towards `IndexContents::None`.
> 
> I think it would be preferred to use a member initializer in the declaration of `IdxContents`. That will ensure an initialization is performed if additional constructors are added.

Actually that makes more sense and it will obviously be assigned to `IndexContents::None`, which after thoughts seems more correct.

**Comment by HighCommander4** [comment]
Seems like `MemIndex::IdxContents` has the same issue.

It's a bit suspicious to me that the other `DexIndex` and `MemIndex` constructors are not passing in a `IndexContents` value. Either there's a bug lurking there, or the field is only relevant in certain situations (e.g. only for dynamic indexes) in which case that should be documented at the field's declaration. Would you mind filing a follow-up issue about auditing this situation more carefully, so it doesn't get forgotten?

**Comment by kadircet** [comment]
idxcontents is only used when we have a set of file names available. hence this was only set via relevant constructors and rest of the runtime doesn't use the field.

but we don't construct tons of new index instances every second. so it's totally fine to just initialize them to `none`

**Comment by zahiraam** [comment]
> Seems like `MemIndex::IdxContents` has the same issue.
> 
> It's a bit suspicious to me that the other `DexIndex` and `MemIndex` constructors are not passing in an `IndexContents` value. Either there's a bug lurking there, or the field is only relevant in certain situations (e.g. only for dynamic indexes) in which case that should be documented at the field's declaration. Would you mind filing a follow-up issue about auditing this situation more carefully, so it doesn't get forgotten?

I could also initialize all the others to `None` and see if this doesn't break any tests?

**Comment by zahiraam** [comment]
@HighCommander4 Is that good as a change? Do you still want an issue to be opened?
@tahonermann can you please review? Thanks.

**Review by kadircet — APPROVED** [review]
thanks, lgtm!

**Comment by HighCommander4** [comment]
> Do you still want an issue to be opened?

I sent out a follow-up PR at https://github.com/llvm/llvm-project/pull/118906 to add a comment describing the situations in which `IdxContents` is used, to avoid future confusion.

**Pull request merged**
