### PR TITLE
[DAG] Fix Failure to reassociate SMAX/SMIN/UMAX/UMIN

### LINKED ISSUE #58110: [DAG] Failure to reassociate SMAX/SMIN/UMAX/UMIN
While opt will reassociate IMINMAX intrinsics, if they appear later in DAG we fail to handle them:
```
declare i32 @llvm.umin.i32(i32, i32)
define i32 @foo(i32 %x) {
  %a = call i32 @llvm.umin.i32(i32 %x, i32 17)
  %b = call i32 @llvm.umin.i32(i32 %a, i32 17) 
  ret i32 %b
}
```
llc -mtriple=x86_64--
```
foo:                                    # @foo
        cmpl    $17, %edi
        movl    $17, %eax
        cmovael %eax, %edi
        cmpl    $17, %edi
        cmovbl  %edi, %eax
        retq
```
Godbolt: https://gcc.godbolt.org/z/45sYa7xj1

This is mainly about adding test coverage - the actual code change to add a reassociateOps call to visitIMINMAX is trivial

### PR DESCRIPTION
**Pull request by SahilPatidar**
Resolve #58110

### CODE REVIEW

**Comment by RKSimon** [comment]
Please can you fix the failing tests
```
Failed Tests (5):
  LLVM :: CodeGen/RISCV/rvv/fixed-vectors-strided-vpload.ll
  LLVM :: CodeGen/RISCV/rvv/fixed-vectors-vpload.ll
  LLVM :: CodeGen/X86/combine-smin.ll
  LLVM :: CodeGen/X86/combine-umax.ll
  LLVM :: CodeGen/X86/combine-umin.ll
```

**Comment by SahilPatidar** [comment]
> Please can you fix the failing tests
> 
> ```
> Failed Tests (5):
>   LLVM :: CodeGen/RISCV/rvv/fixed-vectors-strided-vpload.ll
>   LLVM :: CodeGen/RISCV/rvv/fixed-vectors-vpload.ll
>   LLVM :: CodeGen/X86/combine-smin.ll
>   LLVM :: CodeGen/X86/combine-umax.ll
>   LLVM :: CodeGen/X86/combine-umin.ll
> ```

done

**Comment by RKSimon** [comment]
rebase?

**Review by arsenm — APPROVED** [review]

**Review by RKSimon — APPROVED** [review]

**Comment by RKSimon** [comment]
@SahilPatidar Please can you fix your github commit email address settings to point at "patidarsahil@2001gmail.com" instead of the github noreply default?

**Comment by SahilPatidar** [comment]
> @SahilPatidar Please can you fix your github commit email address settings to point at "[patidarsahil@2001gmail.com](mailto:patidarsahil@2001gmail.com)" instead of the github noreply default?

I apologize for the mistake. My correct email is patidarsahil2001@gmail.com. Could you please advise me on how to change it?

**Comment by RKSimon** [comment]
https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address

AFAICT If we use the squash+merge button then it will use your "web based git operations" primary email address - I think yours might be set to private or something? 

Its something I've only recently noticed so don't know this area very well.

**Comment by SahilPatidar** [comment]
If this problem is caused by Git config, should I change my email using this command and then push it?
```
git filter-branch --env-filter '
if [ "$GIT_AUTHOR_EMAIL" = "old@email.com" ]; then
    export GIT_AUTHOR_EMAIL="new@email.com"
fi
' HEAD~2..HEAD
```

**Comment by RKSimon** [comment]
AFAICT its a github issue, not git:

"[Setting your commit email address on GitHub](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-personal-account-on-github/managing-email-preferences/setting-your-commit-email-address#setting-your-commit-email-address-on-github)"

**Comment by SahilPatidar** [comment]
@RKSimon,
Apologies for any inconvenience but patidarsahil2001@gmail.com is the primary email in GitHub, and I checked that my git commit email is patidarsahil@2001gmail.com. GitHub also shows this along with my primary email."
```
Not visible in emails
This email will not be used as the 'from' address for web-based Git operations, e.g., edits and merges. We will instead use 89641424+SahilPatidar@users.noreply.github.com.
```

**Comment by RKSimon** [comment]
OK - please take a look on https://discourse.llvm.org/t/hidden-emails-on-github-should-we-do-something-about-it/74223 - maybe they can help you

**Comment by arsenm** [comment]
> @RKSimon, Apologies for any inconvenience but [patidarsahil2001@gmail.com](mailto:patidarsahil2001@gmail.com) is the primary email in GitHub, and I checked that my git commit email is [patidarsahil@2001gmail.com](mailto:patidarsahil@2001gmail.com). GitHub also shows this along with my primary email."
> 
> ```
> Not visible in emails
> This email will not be used as the 'from' address for web-based Git operations, e.g., edits and merges. We will instead use 89641424+SahilPatidar@users.noreply.github.com.
> ```

You can try git commit --amend --author="Sahil Patidar patidarsahil2001@gmail.com" during a rebase on the commits, and force push?

**Comment by SahilPatidar** [comment]
@RKSimon, @arsenm, thank you so much for your patience. Also, please check out the changes I made.

**Pull request merged**
