### PR TITLE
[Flang] remove assert using femode_t from AIX

### PR DESCRIPTION
**Pull request by madanial0**
AIX does not have `femode_t` in `<cfenv>` header, removing the assert to fix build failures

### CODE REVIEW

**Comment by vdonaldson** [comment]
@madanial0 Thanks for addressing this problem!

This is just an assert. Could we change this to "#if 0", perhaps with a comment about windows and AIX?

**Comment by vdonaldson** [comment]
> > @madanial0 Thanks for addressing this problem!
> > This is just an assert. Could we change this to "#if 0", perhaps with a comment about windows and AIX?
> 
> Not sure I follow the "#if 0" part ? do you mean instead of the defined parts for AIX and windows?

Something like this:
```
diff --git a/flang/runtime/exceptions.cpp b/flang/runtime/exceptions.cpp
index 797d0c87e601..7106ae73cddc 100644
--- a/flang/runtime/exceptions.cpp
+++ b/flang/runtime/exceptions.cpp
@@ -78,7 +78,9 @@ std::int32_t RTNAME(MapException)(int32_t except) {
 // Verify that the size of ieee_modes_type and ieee_status_type objects from
 // intrinsic module file __fortran_ieee_exceptions.f90 are large enough to
 // hold femode_t and fenv_t objects, respectively.
-#ifndef _WIN32
+#if 0
+// femode_t is not universally defined in fenv.h
+// #if !defined(_WIN32) && !DEFINED(_AIX)
 static_assert(
     sizeof(femode_t) <= sizeof(int) * _FORTRAN_RUNTIME_IEEE_FEMODE_T_EXTENT,
     "increase ieee_modes_type size");

```

**Comment by madanial0** [comment]
> > > @madanial0 Thanks for addressing this problem!
> > > This is just an assert. Could we change this to "#if 0", perhaps with a comment about windows and AIX?
> > 
> > 
> > Not sure I follow the "#if 0" part ? do you mean instead of the defined parts for AIX and windows?
> 
> Something like this:
> 


Forgive my question but I still don't follow why we'd have a `#if 0` followed by the comments?

**Comment by klausler** [comment]
`femode_t` is a fairly new addition to the C standard; you could test `__STDC_VERSION__`.  Or just delete the assertion for now.

**Comment by vdonaldson** [comment]
> > > > @madanial0 Thanks for addressing this problem!
> > > > This is just an assert. Could we change this to "#if 0", perhaps with a comment about windows and AIX?
> > > 
> > > 
> > > Not sure I follow the "#if 0" part ? do you mean instead of the defined parts for AIX and windows?
> > 
> > 
> > Something like this:
> 
> Forgive my question but I still don't follow why we'd have a `#if 0` followed by the comments?

We need a quick fix. I'm suggesting that we delete the assert in all builds.

**Review by vdonaldson — APPROVED** [review]
Looks good to me. Thanks for the fix!

**Comment by vdonaldson** [comment]
Windows and other review-time checks have run successfully. It would be helpful to get this pushed to enable builds on machines that don't have this declaration.

Thanks again for the fix.

**Pull request merged**
