### PR TITLE
[LVI][CVP] Treat undef like a full range

### LINKED ISSUE #68381: [LVI][CVP] CVP error deleted the `and` instruction.
I tried this IR:

```llvm
define i32 @foo(i1 %c0, i1 %c1, i8 %v1, i8 %v2) {
start:
  br i1 %c0, label %bb0, label %bb1

bb0:                                              ; preds = %bb1, %start
  %v2_i32 = zext i8 %v2 to i32
  br label %bb1

bb1:                                              ; preds = %bb0, %start
  %x = phi i32 [ %v2_i32, %bb0 ], [ undef, %start ]
  br i1 %c1, label %bb0, label %bb2

bb2:                                              ; preds = %bb1
  %v1_i32 = zext i8 %v1 to i32
  %y = or i32 %x, %v1_i32
  %z = and i32 %y, 255
  ret i32 %z
}
```

`%z = and i32 %y, 255` should not be deleted by CVP.

alive2: https://alive2.llvm.org/ce/z/A9T1PH
godbolt: https://llvm.godbolt.org/z/YEqPjTv83

This issue started with LLVM 15.

This IR is reduced from https://rust-lang.zulipchat.com/#narrow/stream/131828-t-compiler/topic/Implementing.20niche.20checks.

Extended to `abs`: https://alive2.llvm.org/ce/z/k_8paG.

### PR DESCRIPTION
**Pull request by dianqk**
Fixes #68381.

### CODE REVIEW

**Comment by DianQK** [comment]
Gently ping. @nikic

**Review by nikic — CHANGES_REQUESTED** [review]
I don't think this is the right approach to fixing this. The core fix here should be along these lines:
```llvm
diff --git a/llvm/lib/Analysis/LazyValueInfo.cpp b/llvm/lib/Analysis/LazyValueInfo.cpp
index 0892aa9d75fb..789a02ed329c 100644
--- a/llvm/lib/Analysis/LazyValueInfo.cpp
+++ b/llvm/lib/Analysis/LazyValueInfo.cpp
@@ -801,7 +801,7 @@ void LazyValueInfoImpl::intersectAssumeOrGuardBlockValueConstantRange(
 
 static ConstantRange getConstantRangeOrFull(const ValueLatticeElement &Val,
                                             Type *Ty, const DataLayout &DL) {
-  if (Val.isConstantRange())
+  if (Val.isConstantRange(/*UndefAllowed*/ false))
     return Val.getConstantRange();
   return ConstantRange::getFull(DL.getTypeSizeInBits(Ty));
 }
```
That is, when converting to ConstantRange, we should treat undef like a full range.

The way you are propagating undef here is basically as if it were poison, but this doesn't match its semantics. `zext CR|undef` does not result in `CR.zext()|undef`, because the top bits are guaranteed to be zero even if the input is undef.

I think this approach will result in a simpler and more robust fix.

**Comment by DianQK** [comment]
> The way you are propagating undef here is basically as if it were poison, but this doesn't match its semantics. `zext CR|undef` does not result in `CR.zext()|undef`, because the top bits are guaranteed to be zero even if the input is undef.

Thanks for pointing that out. Yes! This is the better approach.

For a better review and commit history, I will submit a separate PR for `abs`. And test cases for the new abs may depend on the PR.

**Comment by tru** [comment]
Can this PR be closed then?

**Comment by DianQK** [comment]
> Can this PR be closed then?

This PR should be merged. I made the changes in this PR as suggested by @nikic.
I will split it into two PRs and fix different mis-compilations separately.

**Comment by tru** [comment]
@nikic ok to backport?

**Comment by tru** [comment]
Ah never mind. I thought it was targeted for a backport to the release, but I just mixed up my notifications.

**Review by nikic — APPROVED** [review]
LGTM

**Pull request merged**
