### PR TITLE
release/18.x: [DAGCombiner] In mergeTruncStore, make sure we aren't storing shifted in bits. (#90939)

### LINKED ISSUE #90936: miscompile related to coalescing stores in AArch64 SDAG backend
here's a function:
```llvm
define void @f(i16 %0, ptr %1) {
  %3 = trunc i16 %0 to i8
  %4 = trunc i16 %0 to i14
  %new0 = lshr i14 %4, 8
  store i8 %3, ptr %1, align 1
  %5 = getelementptr i8, ptr %1, i64 1
  %6 = trunc i14 %new0 to i8
  store i8 %6, ptr %5, align 1
  ret void
}
```

during codegen, the two 8-bit stores are getting merged:
```
_f:    
	strh	w0, [x1]
	ret
```

but the backend seems to miss that the trunc changed the value, it dropped those 2 high bits. 
I also have versions of this that improperly merge 16-bit stores and 32-bit stores.

we can demonstrate using this driver:
```c
#include <stdio.h>

void f(unsigned short, unsigned char *);

int main(void) {
  unsigned char mem[8];

  for (int i=0; i<8; ++i)
    mem[i] = 0xee;

  f(0xFFFF, mem);

  for (int i=0; i<8; ++i)
    printf("%x\n", mem[i]);
}
```

```
Johns-MacBook-Pro:tmp regehr$ ~/llvm-project/for-alive/bin/llc foo.ll
Johns-MacBook-Pro:tmp regehr$ clang driver.c foo.s && ./a.out 
ff
ff
ee
ee
ee
ee
ee
ee
Johns-MacBook-Pro:tmp regehr$ 
```

in contrast, global isel properly notices that those high bits were chopped off:
```
Johns-MacBook-Pro:tmp regehr$ ~/llvm-project/for-alive/bin/llc foo.ll -global-isel
Johns-MacBook-Pro:tmp regehr$ clang driver.c foo.s && ./a.out 
ff
3f
ee
ee
ee
ee
ee
ee
```

cc @hatsunespica

### PR DESCRIPTION
**Pull request by AZero13**
When looking through a right shift, we need to make sure that all of the bits we are using from the shift come from the shift input and not the sign or zero bits that are shifted in.

Fixes #90936.

(cherry picked from commit 3563af6c06ebc92bcaacef0e33285148ef0f75bd)

### CODE REVIEW

**Comment by topperc** [comment]
@AtariDreams This bug has existed since at least LLVM 10. What makes it a candidate for backporting?

**Comment by AtariDreams** [comment]
> @AtariDreams This bug has existed since at least LLVM 10. What makes it a candidate for backporting?

At best, if the code triggers, we abort the fold, so there is no risk of anything crazy going on if this is added.

**Comment by AtariDreams** [comment]
We do not need to know how to fold every single possible permutation that comes our way, especially if they are so rare that writing compile code optimizing it isn't even worth it. We do, however, need to strive to avoid miscompiles wherever we can, no matter how esoteric the code is.

Now, this isn't always possible, but in this case, the alternative codepath given just bails the transform, which is preferable to folding something that should not be.

**Comment by topperc** [comment]
> @topperc Do you have any strong objections to backporting this?  This looks small to me and I think it's OK to fix long-standing bugs.

No objection.

**Comment by tstellar** [comment]
@AtariDreams I've noticed you've filed a lot of backport requests.  How are you choosing which fixes to backport? Is there a specific use case you care about?

**Comment by AtariDreams** [comment]
> @AtariDreams I've noticed you've filed a lot of backport requests.  How are you choosing which fixes to backport? Is there a specific use case you care about?

There a particular LLVM miscompile bug in WebKit I'm trying to figure out. It's been there since 2019. Backports is literally just avoiding miscompilations

**Comment by nikic** [comment]
@tstellar AtariDreams is requesting backports for random commits that somehow mention miscompilations or crashes, without having any understanding of what the changes are about or how they relate to other changes. They have submitted a large amount of invalid or nonsensical backports for that reason, despite many requests to stop doing so. When there is any doubt, you should not merge backport PRs created by this user. That said, this specific one does look harmless to me.

**Comment by RKSimon** [comment]
> > @AtariDreams I've noticed you've filed a lot of backport requests.  How are you choosing which fixes to backport? Is there a specific use case you care about?
> 
> There a particular LLVM miscompile bug in WebKit I'm trying to figure out. It's been there since 2019. Backports is literally just avoiding miscompilations

@AtariDreams Has the bug disappeared in llvm trunk and you think a recent commit has fixed/hidden it? Has this bug been reported either to WebKit or LLVM that we can track please? Have you been able to confirm if its a llvm bug or UB in WebKit?

**Pull request closed without merging**
