### PR TITLE
[Clang] Fix argument extensions in CGBlocks.cpp

### PR DESCRIPTION
**Pull request by JonPsson1**
Add extension attributes in declarations of _Block_object_dispose and _Block_object_assign.

In order to make this one-liners wherever needed, a new casting method FunctionCallee::getAsFunction() has been added.

A problem is that it seems theoretically possible that the created Function is any other named Value in the module... Would it be ok to have the cast fail in such a case?

I realize this is not the approach you had in mind, but it would at least be nice to hear the reasoning as to why something more elaborate would be preferred?

Please help with the signedness for the _Block_object_dispose argument, which I have no clue about.

@efriedma-quic @nikic

### CODE REVIEW

**Comment by efriedma-quic** [comment]
> I realize this is not the approach you had in mind, but it would at least be nice to hear the reasoning as to why something more elaborate would be preferred?

Manually writing addParamAttr markings doesn't scale; there's no easy way to audit whether everything has been appropriately ported.  A corrected API would automatically get the right markings.

Also, this isn't the same marking the standard codepath would generate in some cases, which might cause other issues.  (Adding sext for int is probably mostly right for existing targets, but it's not obviously right for all targets, and you'd need a different API for any interface that takes an unsigned integer.)

> A problem is that it seems theoretically possible that the created Function is any other named Value in the module... Would it be ok to have the cast fail in such a case?

The most likely case is that someone defines an alias... and in that case, I think we need the attribute on the call.

**Review by nikic — COMMENTED** [review]
> I realize this is not the approach you had in mind, but it would at least be nice to hear the reasoning as to why something more elaborate would be preferred?

Basically, because this is an ABI-dependent property, so we should let the existing ABI handling code deal with it.

I can't think of an example where something would go wrong in *this* particular case, because I don't think any target uses zeroext for `int`. But for `unsigned` there is a mix of targets using zeroext or signext (or neither of course).

**Comment by JonPsson1** [comment]
> CodeGenModule::CreateRuntimeFunction doesn't have enough information to mark up functions correctly, given its current signature. I don't think we currently have an alternative. We could add one pretty easily, though; we just a version that takes a clang::FunctionType instead of an llvm::FunctionType.

I have now tried to improve my patch further by instead overloading CreateRuntimeFunction() with a version that can take a sign/zero extension attribute, process it through TargetLibraryInfo to get the right attribute for the target, and then pass this along to the other CreateRuntimeFunction().

"clang::FunctionType" makes me wonder if there is actually a source-language function type available so that the signedness of the extensions could be inferred from it..? I thought these were internal calls to functions that will be emitted directly on IR...

This is at least an improvement and it makes it possible to add an attribute with a one-liner wherever needed.

**Comment by efriedma-quic** [comment]
> "clang::FunctionType" makes me wonder if there is actually a source-language function type available so that the signedness of the extensions could be inferred from it..? I thought these were internal calls to functions that will be emitted directly on IR...

The signature exists, in the abstract sense: the implementation of the library function is written in C code, so it has a C function signature.  It doesn't exist anywhere in the source code, but it's easy to synthesize.

On the LLVM side, we use a lower-level abstraction that says, specifically, "this is a signed integer, figure out the correct form of extension" (or "this is an unsigned integer, figure out the extension").  We do this because we don't have a richer type system available, so we need an approximation. We could also do that in clang... but we have the real C type system, so it's probably simpler to just construct the type "void *f(void*,void*,int);" and request the corresponding LLVM signature/attributes.

I mean... I guess we could go with something like the current proposal, but it seems like once we have the CreateRuntimeFunction() taking a clang signature working, it's more readable to just write C types, instead of writing an LLVM type plus a marking for whether the value is supposed to be signed or unsigned.

If we are going to go with explicitly passing in the signed-ness, though, I'd prefer a slightly different interface; instead of trying to use something that looks like an attribute, it should just be a simpler list: for each parameter, specify whether it's signed, unsigned, or not an integer.

**Comment by JonPsson1** [comment]
Patch updated to pass an extension attribute for each retval/parameter, per your suggestion.

There may possibly be cases of NoExt (struct-in-reg) that also need to be handled, but I will wait with that until I have a test case.

Does this seem ok (for now at least), or would you really prefer to use the C type passed instead?

**Comment by JonPsson1** [comment]
gentle ping... @efriedma-quic @nikic

**Comment by JonPsson1** [comment]
Ping!

I'd love to get this check enabled by default after fixing the issues I see... This is the only one for Objective-C (the second one here came up after fixing the first one).

**Comment by efriedma-quic** [comment]
I looked to see how hard it would be to lower the clang type... seems like it's not hard.  Pushed #113506.  Let me know what you think.

If there's some complication I'm not seeing, I think your suggested API in the current version of this patch makes sense... but using clang types seems much easier on the caller side.

**Comment by JonPsson1** [comment]
> I looked to see how hard it would be to lower the clang type... seems like it's not hard. Pushed #113506. Let me know what you think.
> 
> If there's some complication I'm not seeing, I think your suggested API in the current version of this patch makes sense... but using clang types seems much easier on the caller side.

I think that seems to work well, thanks.

**Comment by JonPsson1** [comment]
I will abandon this now since @efriedma-quic's patch (#113506) is the better approach and approved.

**Pull request closed without merging**
