### PR TITLE
[llvm][offload] Move AMDGPU offload utilities to LLVM

### PR DESCRIPTION
**Pull request by fabianmcg**
This patch moves utilities from `offload/plugins-nextgen/amdgpu/utils/UtilitiesRTL.h` to `llvm/Frontend/Offloading/AMDGPU/ObjectUtilities.h` to be reused by other projects.

Concretely the following changes were made:
- Rename `KernelMetaDataTy` to `AMDGPUKernelMetaData`.
- Remove unused fields `KernelObject`, `KernelSegmentSize`, `ExplicitArgumentCount` and `ImplicitArgumentCount` from `AMDGPUKernelMetaData`.
- Return the produced error if `ELFObj.sections()` failed instead of using `cantFail`.
- Added `AGPRCount` field to `AMDGPUKernelMetaData`.
- Added a default invalid value to all the fields in `AMDGPUKernelMetaData`.

### CODE REVIEW

**Comment by saiislam** [comment]
> This patch moves utilities from `offload/plugins-nextgen/amdgpu/utils/UtilitiesRTL.h` to `llvm/Frontend/Offloading/AMDGPU/ObjectUtilities.h` to be reused by other projects.
> 

Which other projects will use it? and How?

**Comment by fabianmcg** [comment]
> Which other projects will use it? and How?

Upstream: MLIR, see this patch: https://github.com/llvm/llvm-project/pull/95292 In there we use it to get SGPR*, VGPR*, etc metadata.

Downstream: [rocMLIR ](https://github.com/ROCm/rocMLIR) for the same reason.

**Review by jhuber6 — COMMENTED** [review]
We already have `Utils` somewhere else in this directory right? If we're namespacing it with `amdgpu` we could probably just put it there.

**Comment by fabianmcg** [comment]
Yes, we have `llvm/Frontend/Offloading/Utility.h`, I can move it there.

However, I didn't add it there because the files have different purposes, one is almost entirely for offload entries and the other ELF utilities.

**Comment by jhuber6** [comment]
> Yes, we have `llvm/Frontend/Offloading/Utility.h`, I can move it there.
> 
> However, I didn't add it there because the files have different purposes, one is almost entirely for offload entries and the other ELF utilities.

That's just the only thing I could think to put there at the time, should be usable for other things.

**Review by jhuber6 — APPROVED** [review]
Works for me

**Pull request merged**
