### PR TITLE
[flang][driver] Fix Driver/isysroot.f90 test

### PR DESCRIPTION
**Pull request by luporl**
Check for DEFAULT_SYSROOT, because when it is set -isysroot has no
effect.

### CODE REVIEW

**Comment by luporl** [comment]
Tested on MacOS. When DEFAULT_SYSROOT is set isysroot.f90 becomes unsupported and when not set the test passes.

**Review by banach-space — APPROVED** [review]
LGTM, thanks a ton!

**Review by kkwli — APPROVED** [review]
LG. Thanks.

**Comment by luporl** [comment]
Thanks for the quick reviews.

**Pull request merged**
