### PR TITLE
Intrinsic: introduce minimumnum and maximumnum

### LINKED ISSUE #93033: llvm.minnum  should be lowered to fminimum_numf instead of fminf
In https://llvm.org/docs/LangRef.html#llvm-minnum-intrinsic
```
Unlike the IEEE-754 2008 behavior, this does not distinguish between signaling and quiet NaN inputs. If a target’s implementation follows the standard and returns a quiet NaN if either input is a signaling NaN, the intrinsic lowering is responsible for quieting the inputs to correctly return the non-NaN input (e.g. by using the equivalent of llvm.canonicalize).
```

While in https://www.gnu.org/software/libc/manual/html_node/Misc-FP-Arithmetic.html
```
If an argument is a quiet NaN, the other argument is returned. If both arguments are NaN, or either is a signaling NaN, NaN is returned.
```

### PR DESCRIPTION
**Pull request by wzssyqa**
Currently, on different platform, the behaivor of llvm.minnum is different if one operand is sNaN:

When we compare sNaN vs NUM:

ARM/AArch64/PowerPC: follow the IEEE754-2008's minNUM: return qNaN. RISC-V/Hexagon follow the IEEE754-2019's minimumNumber: return NUM. X86: Returns NUM but not same with IEEE754-2019's minimumNumber as
     +0.0 is not always greater than -0.0.
MIPS/LoongArch/Generic: return NUM.
LIBCALL: returns qNaN.

So, let's introduce llvm.minmumnum/llvm.maximumnum, which always follow IEEE754-2019's minimumNumber/maximumNumber.

Half-fix: #93033

### CODE REVIEW

**Comment by wzssyqa** [comment]
Relevant Discourses:

https://discourse.llvm.org/t/rfc-fix-llvm-min-f-and-llvm-max-f-intrinsics/79735

https://discourse.llvm.org/t/purpose-of-g-fminnum-maxnum-ieee/78771

**Comment by tschuett** [comment]
This is a huge patch. Please split out/stack the backend changes.

**Comment by wzssyqa** [comment]
Some background here: https://github.com/llvm/llvm-project/pull/93841

**Comment by tschuett** [comment]
First introduce the intrinsics and in later patches you can update the backends.

**Comment by wzssyqa** [comment]
IR support and SelectionDAG support have been splited as a new PR.

https://github.com/llvm/llvm-project/pull/96649

**Comment by wzssyqa** [comment]
Close this one, due to that we are working on split it to several PRs.

See: 
https://github.com/llvm/llvm-project/pull/96304
https://github.com/llvm/llvm-project/pull/96649
https://github.com/llvm/llvm-project/pull/96281

**Pull request closed without merging**
