### PR TITLE
[mlir][Transforms] Mark 1:N conversion driver as deprecated

### PR DESCRIPTION
**Pull request by matthias-springer**
Depends on: #121054, #121101

### CODE REVIEW

**Review by zero9178 — APPROVED** [review]
LGTM!

**Comment by MaskRay** [comment]
@matthias-springer `mlir/lib/Dialect/SCF/Transforms/OneToNTypeConversion.cpp` now emits some `-Wdeprecated-declarations` warnings. In llvm-project, we generally fix or work around warnings before adding a deprecated attribute.

**Comment by matthias-springer** [comment]
`applyPartialOneToNConversion` and a few others are still used in a test case of the 1:N conversion driver. (Not an application of the conversion driver, but the conversion driver itself.) Is there a way to mark it as "deprecated" without removing the test cases? Ideally, I'd like to remove `applyPartialOneToNConversion` and its tests at the same time to avoid a (temporary) gap in test coverage.

**Comment by DanielCChen** [comment]
@matthias-springer We are getting build failures as:
```
llvm-project/mlir/lib/Dialect/SCF/Transforms/OneToNTypeConversion.cpp:53:14: error: 'replaceOp' is deprecated: Use replaceOpWithMultiple() instead [-Werror,-Wdeprecated-declarations]
   53 |     rewriter.replaceOp(op, newOp->getResults(), resultMapping);
      |              ^~~~~~~~~
      |              replaceOpWithMultiple
```

It seems the two (replaceOp and replaceOpWithMultiple) have different ABI.

**Comment by matthias-springer** [comment]
The two APIs are slightly different. It is not a 1:1 replacement.

It seems like it was not the best idea to mark these functions as "deprecated" while they are still in use because of compiler warnings. [This](https://github.com/llvm/llvm-project/pull/122073) PR turns them into comments.

**Pull request merged**
