### PR TITLE
SimplifyLibCalls: Don't require ldexp to emit intrinsic in exp2 combine

### PR DESCRIPTION
**Pull request by arsenm**
When folding exp2(itofp(x)) to ldexp(1, x), don't require an ldexp libcall to emit the intrinsic.

The intrinsic needs to be handled regardless of whether the system has a libcall, and we have an inline implementation of ldexp already. This fixes the instance in the exp2->ldexp fold. Another instance exists for the pow(2) -> ldexp case

The LTO test change isn't ideal, since it's just moving the problem to another instance where we're relying on implied libm behavior for an intrinsic transform. Use exp10 since that's a harder case to solve in the libcall house of cards we have.

### CODE REVIEW

**Comment by efriedma-quic** [comment]
It looks like the lowering for llvm.ldexp currently doesn't respect "no-builtin-ldexp" etc.; we should probably fix that first.

Long-term, we really need a better approach for managing the codesize explosion that comes from expanding everything inline.

**Comment by arsenm** [comment]
> It looks like the lowering for llvm.ldexp currently doesn't respect "no-builtin-ldexp" etc.; we should probably fix that first.
> 

When I tried to consider no-builtin* for expanding memcpy instead of emitting a call, I got complaints (and had to implement c8cac156135de8e211b800ea5abe9666803b2875) because for some reason there was the expectation of this not changing legalization emitted libcalls. We have parallel tables, TargetLibraryInfo and RuntimeLibcalls, and it's not clear if no-builtin is supposed to change the RuntimeLibcall behavior

**Comment by efriedma-quic** [comment]
If we reserve the right to call ldexp anywhere, under any set of flags, how is anyone supposed to implement a C library?  I guess this particular combine is unlikely to cause issues, but if you're planning to rip out all checks for whether a functions exists, it seems like something we need to address.

For memcpy/memmove/memset specifically, we currently have a special-case rule: in no-builtins mode: existing calls to the intrinsics lower to the corresponding calls, but optimizations don't generate any new calls to those functions.  This is sort of hard to formally justify, but in practice, it works pretty well for people doing stuff with -ffreestanding.  The special case doesn't really extend beyond those specific functions.

**Comment by efriedma-quic** [comment]
> IMO it was wrong to provide any math intrinsics to expose the usage of math functions. These intrinsics should be providing the target implementation of the libm functions, not the other way around. If we can't codegen the intrinsic without the libcall, we probably shouldn't have the intrinsic.

I see where you're coming from with this...  see also discussion on https://discourse.llvm.org/t/rfc-all-the-math-intrinsics/78294 .  If you're willing to push forward something to break apart the current mess, I'd be in favor.

> Alternative to this, I could fix it to preserve libcall->libcall behavior and intrinsic->intrinsic behavior. The main problem I'm trying to solve is gating intrinsic->intrinsic gated on the libcall availability

That still technically breaks -fno-builtin-ldexp... but the way it breaks is much less likely to matter, so I think I'm okay with this.

> > Long-term, we really need a better approach for managing the codesize explosion that comes from expanding everything inline.
> 
> We could also undo this optimization in codegen if ldexp isn't available (which in practice just means windows) and call pow

On Windows specifically, we have ldexp; the issue is just that we don't have ldexpf.

**Comment by andykaylor** [comment]
We definitely have a mess with regard to our handling of math library functions. We're nowhere near consistent behavior.

I'm not sure if this is what Matt was alluding to, but the gcc documentation for fno-builtin-* says, "Don’t recognize built-in functions **that do not begin with ‘__builtin_’ as prefix**." (emphasis added) The result of this is that if you call __builtin_ldexp even when compiling with -fno-builtin-ldexp, we will happily translate it to a call to the llvm.ldexp intrinsic, and on X86 that gets lowered to a call to ldexp() (which may or may not be the library call). 

https://godbolt.org/z/95Kb6PjnW

You can make a case that this is user error -- if they didn't want the library function to be called, they shouldn't have used the builtin. It would be much better if we lowered the intrinsics to calls to a compiler runtime library function that we could be certain existed and had control over the accuracy of. This would allow us to actual implement things the way the LLVM IR definition says we will (i.e. not setting errno).

But that's not the current situation, and the example above is different from the front end replacing one call with another on the user's behalf. If the user has passed `-fno-builtin-ldexp` and then called `exp2((double)n)` it seems like a very good bet that they really don't want the ldexp library function to be called.

**Comment by efriedma-quic** [comment]
> > IMO it was wrong to provide any math intrinsics to expose the usage of math functions. These intrinsics should be providing the target implementation of the libm functions, not the other way around. If we can't codegen the intrinsic without the libcall, we probably shouldn't have the intrinsic.
> 
> I see where you're coming from with this... see also discussion on https://discourse.llvm.org/t/rfc-all-the-math-intrinsics/78294 . If you're willing to push forward something to break apart the current mess, I'd be in favor.

Maybe the right thing to do here is just use TTI: we ask the target if it can handle the intrinsic, it says yes if either the libcall is legal, or it has some other implementation it can use.

**Comment by arsenm** [comment]
> On Windows specifically, we have ldexp; the issue is just that we don't have ldexpf.

Can we handle this by just promoting float to double in codegen?

**Comment by efriedma-quic** [comment]
> > On Windows specifically, we have ldexp; the issue is just that we don't have ldexpf.
> 
> Can we handle this by just promoting float to double in codegen?

Yes, that's fine; the Windows math.h does exactly the same thing.

**Review by efriedma-quic — APPROVED** [review]
LGTM

**Pull request merged**
