### PR TITLE
[RISCV][GISel] Add initial pre-legalizer combiners copying from AArch64.

### PR DESCRIPTION
**Pull request by topperc**
- [RISCV][GlobalISel] Select ALU GPR instructions
- [RISCV][GISel] Add initial pre-legalizer combiners copying from AArch64.

This is stack on https://reviews.llvm.org/D76445 to get the RISCVGISel.td and the ability to select basic instructions.

### CODE REVIEW

**Review by aemerson — COMMENTED** [review]
Seems reasonable to me from a GISel view, I'll let RISCV maintainers give the approval.

**Comment by aemerson** [comment]
However, I just noticed that this is 2 separate commits in a PR. I believe current PR policy is one change per PR, with follow up commits used for addressing review feedback.

**Comment by topperc** [comment]
> However, I just noticed that this is 2 separate commits in a PR. I believe current PR policy is one change per PR, with follow up commits used for addressing review feedback.

It is only because I didn't know how to handle this commit being dependent on another review.

**Comment by aemerson** [comment]
> > However, I just noticed that this is 2 separate commits in a PR. I believe current PR policy is one change per PR, with follow up commits used for addressing review feedback.
> 
> It is only because I didn't know how to handle this commit being dependent on another review.

Join the club, we had jackets made.

So far there's no known way to have stacked reviews 🙃

**Comment by topperc** [comment]
Landed as 8677aaa1a32af3aadfe90e506c278233695fcfe9

**Pull request closed without merging**
