### PR TITLE
[clangd] Add includes from source to non-self-contained headers

### LINKED ISSUE #45: Support non-self-contained files
Currently clangd doesn't work with non-self-contained files, even if people have a way to build their projects with those files, for example by merging some/all of non-self-contained files into a single TU and building that file.

### PR DESCRIPTION
**Pull request by sr-tream**
It's a hack to solve include headers from source to non-self-contained headers

Limitations:
- header file must be matched by `isHeaderFile` without language options
- non-self-contained header must be included by source
- AST for source must be cached before open non-self-contained header
- resolved only includes, without macros and symbols from source file

Example:
```cpp
// header

void hello(std::string Name);
```
```cpp
// source
#include <string>

#include "header.h"

#include <iostream>

int main(){
  hello("World");
  return 0;
}

void hello(std::string Name){
  std::cout << "Hello, " << Name << "\n";
}
```

Current clangd behavior for header - show error `Use of undeclared identifier 'std'`

With this PR, clangd adds include <string> to command line for header

Partially resolves clangd/clangd#45

### CODE REVIEW

**Comment by HighCommander4** [comment]
@sr-tream just so you know, every time you force-push a PR, github sends every subscriber an email notification

**Comment by sr-tream** [comment]
> @sr-tream just so you know, every time you force-push a PR, github sends every subscriber an email notification

Sorry for flood, I will try to avoid this from now on

**Comment by kadircet** [comment]
hi! thanks for the interest @sr-tream but I am afraid this is likely to cause disruption in more cases than it might improve.

apart from technical details like the threading concerns and reliance on certain variants that we don't really have (eg order of includes); at a high level the idea of "finding a representative source file for the header and replicating the PP state" is hard to work in general.

The current approach of finding a candidate through `HeaderIncluders` will pick an arbitrary source file that transitively includes the header you're interested in. Hence you'll actually create a set of `-include XX` commands, that **might** (and probably will) recursively include the header itself. Also there's nothing detecting a failure in processing of the compilation unit, this is done without checking self-containedness (which is again hard to check) hence will definitely regress both performance and correctness for self-contained headers as well.

sorry for forgetting to hit send on friday, i see that you did some more iterations on the weekend. but i think it'd be better to discuss the general approach first, to see if that makes sense. not only to ensure non-self-contained headers can be handled properly rather than adding an edge case where things look like they're working (but they're not, hence resulting in more bug reports and hard-to-maintain fixes), but also to make sure they're not regressing anything for regular code paths.

**Comment by kadircet** [comment]
> We can limit ourselves to only the paired source file, and cancel inclusions if the source file does not include a non-self-contained header directly. This will reduce the number of situations in which this hack works, but will avoid the problems you describe

deducing the paired source file is also a heuristic, which will likely go wrong at times. more importantly it'll still regress the behavior for self-contained headers, even if we ignore that, it still creates this new illusion of working when the user is lucky, and will trigger extra maintenance load (that's IMHO not justified) by already thin stretched maintainers.

**Comment by HighCommander4** [comment]
A somewhat narrow use case where this approach might be workable is unity builds (groups of source files batched together to be compiled as a single translation unit for build performance).

That's a situation where the non-self-contained files of interest (the individual source files that are included in such a batch) have precisely one includer, their incoming preprocessor state can be replicated precisely using `-include` flags, and the intervention can be limited to them (it wouldn't apply to header files).

Of course, the including file is not likely to be open in this case, so we'd want something like an include graph stored in the index (as proposed in #123) to consult.

**Pull request closed without merging**
