### PR TITLE
[clang][CodeGen][SPIR-V] Fix incorrect SYCL usage, implement missing interface

### PR DESCRIPTION
**Pull request by AlexVlx**
This is primarily meant to address the issue identified in #109182, around incorrect usage of `-fsycl-is-device`; we now have AMDGCN flavoured SPIR-V which retains the desired behaviour around the default AS and does not depend on the SYCL language being enabled to do so. Overall, there are three changes:

1. We unconditionally use the `SPIRDefIsGen` AS map for AMDGCNSPIRV target, as there is no case where the hack of setting default to private  would be desirable, and it can be used for languages other than OCL/HIP;
2. We implement `SPIRVTargetCodeGenInfo::getGlobalVarAddressSpace` for SPIR-V in general, because otherwise using it from languages other than HIP or OpenCL would yield 0, incorrectly;
3. We remove the incorrect usage of `-fsycl-is-device`.

### CODE REVIEW

**Comment by VyacheslavLevytskyy** [comment]
@asudarsa Can you please have a look?

**Review by AlexVlx — COMMENTED** [review]
> Are there any tests available to check this behavior?

The reworked tests do verify / rely on this behaviour, but I can add an individual test for both vanilla and AMDGCN flavoured SPIR-V, if that is preferred (might be better anyway).

**Comment by asudarsa** [comment]
> > Are there any tests available to check this behavior?
> 
> The reworked tests do verify / rely on this behaviour, but I can add an individual test for both vanilla and AMDGCN flavoured SPIR-V, if that is preferred (might be better anyway).

Thanks @AlexVlx 
I will approve this change. You can add the tests as part of this PR or a follow-up PR. Either way is fine.
Sincerely

**Review by asudarsa — APPROVED** [review]
LGTM. Addition of new tests can be done in this PR or a follow-up PR.
Thanks

**Review by VyacheslavLevytskyy — APPROVED** [review]

**Comment by AlexVlx** [comment]
> > > Are there any tests available to check this behavior?
> > 
> > 
> > The reworked tests do verify / rely on this behaviour, but I can add an individual test for both vanilla and AMDGCN flavoured SPIR-V, if that is preferred (might be better anyway).
> 
> Thanks @AlexVlx I will approve this change. You can add the tests as part of this PR or a follow-up PR. Either way is fine. Sincerely

Thank you for the review; I'll punt on adding targeted tests here because I *think* we'll have to add a few more of these queries, and I can just bundle specific tests there.

**Pull request merged**
