### PR TITLE
[AMDGPU][GFX12] Add new v_permlane16 variants

### PR DESCRIPTION
**Pull request by mariusz-sikora-at-amd**

### CODE REVIEW

**Review by piotrAMD — APPROVED** [review]
LGTM

You could also update existing permlane tests with run lines for gfx12:
* test/CodeGen/AMDGPU/llvm.amdgcn.permlane.ll
* test/CodeGen/AMDGPU/vcmpx-permlane-hazard.mir

This can also be a separate patch.

**Comment by mariusz-sikora-at-amd** [comment]
> LGTM
> 
> You could also update existing permlane tests with run lines for gfx12:
> 
>     * test/CodeGen/AMDGPU/llvm.amdgcn.permlane.ll
> 
>     * test/CodeGen/AMDGPU/vcmpx-permlane-hazard.mir
> 
> 
> This can also be a separate patch.

New patch: https://github.com/llvm/llvm-project/pull/75572

**Comment by nico** [comment]
Looks like the new test might be failing on macOS/arm64: http://45.33.8.238/macm1/75171/step_11.txt

Maybe it just needs something like 806761a7629df268c8aed49657aeccffa6bca449, but maybe the assert isn't benign.

Do you want to switch the test to use `-mtriple`, or do you want to revert and investigate what's up with the assert?

**Comment by arsenm** [comment]
> Looks like the new test might be failing on macOS/arm64: http://45.33.8.238/macm1/75171/step_11.txt

> Do you want to switch the test to use `-mtriple`, or do you want to revert and investigate what's up with the assert?

Really it needs #75469 for the triple to not default to a nonsensical combination

**Comment by nico** [comment]
That did the trick, thanks!

**Pull request merged**
