### PR TITLE
[libc] Fix GPU test build error

### PR DESCRIPTION
**Pull request by jplehr**
This fixes a build error on the AMDGPU buildbot introduced in PR https://github.com/llvm/llvm-project/pull/92172

### CODE REVIEW

**Comment by lntue** [comment]
Look like you also need to update `libc/test/src/string/strerror_test.cpp:100`:
```
[3952/4270] Running unit test libc.test.src.string.strerror_test.__unit__
FAILED: projects/libc/test/src/string/CMakeFiles/libc.test.src.string.strerror_test.__unit__ /var/lib/buildkite-agent/builds/linux-56-59b8f5d88-2sq4t-1/llvm-project/github-pull-requests/build/projects/libc/test/src/string/CMakeFiles/libc.test.src.string.strerror_test.__unit__
cd /var/lib/buildkite-agent/builds/linux-56-59b8f5d88-2sq4t-1/llvm-project/github-pull-requests/build/projects/libc/test/src/string && /var/lib/buildkite-agent/builds/linux-56-59b8f5d88-2sq4t-1/llvm-project/github-pull-requests/build/projects/libc/test/src/string/libc.test.src.string.strerror_test.__unit__.__build__
[ RUN      ] LlvmLibcStrErrorTest.KnownErrors
/var/lib/buildkite-agent/builds/linux-56-59b8f5d88-2sq4t-1/llvm-project/github-pull-requests/libc/test/src/string/strerror_test.cpp:154: FAILURE
      Expected: __llvm_libc_19_0_0_git::strerror(static_cast<int>(i))
      Which is: Unknown error 84
To be equal to: message_array[i]
      Which is: Invalid or incomplete multibyte or wide character
[  FAILED  ] LlvmLibcStrErrorTest.KnownErrors
```

**Review by jhuber6 — APPROVED** [review]

**Comment by michaelrj-google** [comment]
We will need to figure out a more permanent solution for errno numbers on GPUs because I would like to revert this patch when possible.  Having a valid `EILSEQ` strerror on platforms that support it is important.

**Comment by jhuber6** [comment]
> We will need to figure out a more permanent solution for errno numbers on GPUs because I would like to revert this patch when possible. Having a valid `EILSEQ` strerror on platforms that support it is important.

I think this was broken on the CPU build beforehand, at least it was when I checked it, so reverting this would make that fail again.

**Comment by robincaloudis** [comment]
> > We will need to figure out a more permanent solution for errno numbers on GPUs because I would like to revert this patch when possible. Having a valid `EILSEQ` strerror on platforms that support it is important.
> 
> 
> 
> I think this was broken on the CPU build beforehand, at least it was when I checked it, so reverting this would make that fail again.

This is true. It was broken on `fuchsia-x86_64-linux` and `openmp-offload-libc-amdgpu-runtime`.

**Pull request merged**
