### PR TITLE
[libc][math][c23] Add remaining linux/* entrypoints for {,u}fromfp{,x}*

### PR DESCRIPTION
**Pull request by overmighty**
I haven't tested on these targets and will rely on the buildbots.

cc @lntue

### CODE REVIEW

**Review by nickdesaulniers — APPROVED** [review]
Sure, you'll just want to keep an eye on the buildbots after this lands.

https://lab.llvm.org/buildbot/#/builders?tags=libc

In particular, the 32b arm build bot can take a couple hours to produce relevant test results.  Let me know some idea of when you'd like us to merge this.

**Comment by overmighty** [comment]
Tomorrow early in the morning in your timezone would work.

**Comment by overmighty** [comment]
Fail on 32-bit Arm: https://lab.llvm.org/buildbot/#/builders/229/builds/24458.

**Comment by nickdesaulniers** [comment]
I'm going to revert for now.

**Comment by overmighty** [comment]
I think the test failure on 32-bit Arm is caused by this line: https://github.com/llvm/llvm-project/blob/b282259711af7b295cb80a12880bcd8e0d1fcefa/libc/src/__support/FPUtil/NearestIntegerOperations.h#L269

All 3 shifts in that function are wrong no matter the target arch, really. The test just unluckily doesn't catch this mistake on x86-64, AArch64 and RV64, because they all only use the lower 5 bits of the shift amount operand when shifting a 32-bit int, so they shift by 0 instead of 32, so the result is still 1 and not 0. ARMv7's "LSL (register)" instruction uses the lower 8 bits of the shift amount operand, so it gets caught there.

I guess I should change the code to use `FPBits::set_biased_exponent`.

**Pull request merged**
