### PR TITLE
[RISCV] Mark math functions as expanded for zvfhmin/zvfbfmin

### PR DESCRIPTION
**Pull request by lukel97**
For regular floating point types we mark these as expanded on scalable vectors so they're not legal in the cost model, so this does the same for f16 w/ zvfhmin and bf16.

### CODE REVIEW

**Review by wangpc-pp — COMMENTED** [review]
Reasonable to me. Just one question, why is there no CodeGen change? I suppose we should have some.

**Comment by lukel97** [comment]
> Reasonable to me. Just one question, why is there no CodeGen change? I suppose we should have some.

I thought the same thing as well, but I couldn't find any existing CodeGen tests to extend. I guess the original commit that set them to expand was mainly testing that the vectorizers wouldn't emit any of these.

**Comment by topperc** [comment]
> > Reasonable to me. Just one question, why is there no CodeGen change? I suppose we should have some.
> 
> I thought the same thing as well, but I couldn't find any existing CodeGen tests to extend. I guess the original commit that set them to expand was mainly testing that the vectorizers wouldn't emit any of these.

You can't really write a CodeGen test for them unless you use "not" and check for the error message. Without this patch they probably get a "cannot select" error from isel. With this patch they'll fail when LegalizeDAG tries to unroll them which can't be done for a scalable vector.

**Review by topperc — APPROVED** [review]
LGTM

**Pull request merged**
