### PR TITLE
[LLD][COFF] Set __guard_flags to CF_INSTRUMENTED if any object is instrumented

### PR DESCRIPTION
**Pull request by cjacek**

### CODE REVIEW

**Comment by cjacek** [comment]
I noticed this issue while examining load config differences between LLD and MSVC for ARM64EC. After some experimentation, I found that this behavior isn’t unique to ARM64EC: `__guard_flags` is marked as `CF_INSTRUMENTED` if any input object is built with `/guard:cf`. On ARM64EC, the load config from `msvcrt` pulls in additional code, which is enough to trigger this flag.

Since LLD has functioned well without this behavior so far, it’s unlikely to matter in practice. However, implementing it for compatibility seems straightforward enough.

**Review by mstorsjo — APPROVED** [review]
LGTM, seems reasonable.

**Comment by alvinhochun** [comment]
Just speculating here without having tested the patch: I'm not sure if this is fine for llvm-mingw, which builds mingw-w64 with CFG. It looks like this patch would effectively set `CF_INSTRUMENTED` on all binaries built with llvm-mingw even if the user hasn't asked for it. In mingw-w64 CRT (and by extension ucrt/msvcrt) there may be functions that calls function pointers to user code (`.ctors`/`.dtors` are probably some of them, maybe `atexit` handlers too), which may trip CFG if calling functions from object files not built with `-mguard=cf`.

Though LLD may have some fallbacks to heuristically add functions to the list of valid call targets. I don't know, maybe it is possible to craft some object files in assembly that would trip CFG? I recall there being a problem with OpenSSL that enabling CFG with llvm-mingw will crash when calling into some objects built with NASM.

**Comment by cjacek** [comment]
Note that this patch only concerns the `CF_INSTRUMENTED` flag. It does not make LLD emit function tables or set the `CF_FUNCTION_TABLE_PRESENT` flag, so as far as I understand, it won’t have any functional impact. I’m not sure what might be special about mingw-w64 here; if this were an issue, it would likely affect MSVC as well.

**Review by alvinhochun — APPROVED** [review]
Ah okay. If it doesn't set `CF_FUNCTION_TABLE_PRESENT`, then it should be alright.

**Pull request merged**
