### PR TITLE
[mlir][linalg] Enable CollapseLinalgDimensions to collapse memref based operations

### PR DESCRIPTION
**Pull request by AviadCo**
operations

### CODE REVIEW

**Comment by AviadCo** [comment]
Adding @aniragil @amrami @amirBish as subscribers

**Review by MaheshRavishankar — APPROVED** [review]
This looks good. It seems like I had left comments earlier on a similar PR. I am not sure what happened here.

**Comment by AviadCo** [comment]
@MaheshRavishankar thanks for reviewing. Indeed there are 2 PRs. The second one is based on this one and I didn't know how to split. I will address the comments in the second PR (https://github.com/llvm/llvm-project/pull/68526) also.

**Review by nicolasvasilache — COMMENTED** [review]
Sorry for the delay, traveling this week.
LG, thanks!

**Pull request merged**
