### PR TITLE
Reapply [compiler-rt] prctl interception update, SECCOMP_MODE_FILTER …

### PR DESCRIPTION
**Pull request by devnexen**
…support. #107722

### CODE REVIEW

**Comment by devnexen** [comment]
cc @nico following your revert

**Comment by vitalybuka** [comment]
Please include into description a reference to original PR

**Review by vitalybuka — APPROVED** [review]

**Comment by kstoimenov** [comment]
@devnexen, broke Android Sanitizer again: https://lab.llvm.org/buildbot/#/builders/186/builds/2641.

**Comment by devnexen** [comment]
seems easy enough to fix this time.

**Comment by Zentrik** [comment]
This seems to have broken building on musl for me, do you have any idea how to fix it?
```
/opt/x86_64-linux-musl/bin/../lib/gcc/x86_64-linux-musl/10.2.0/../../../../x86_64-linux-musl/bin/ld: projects/compiler-rt/lib/memprof/CMakeFiles/RTMemprof_dynamic.x86_64.dir/memprof_interceptors.cpp.o: in function `__interceptor_prctl':
/workspace/srcdir/llvm-project/compiler-rt/lib/memprof/../sanitizer_common/sanitizer_common_interceptors.inc:1319: undefined reference to `__sanitizer::struct_sock_fprog_sz'
[16:34:43] collect2: error: ld returned 1 exit status
```

**Comment by devnexen** [comment]
I guess [this part](https://github.com/llvm/llvm-project/pull/109834/files#diff-d8dd05a3dee58959cd023ef105f48682730702fa0aa24032e5a4fc5500b36d4eR535) needs to be made available for musl too.

**Pull request merged**
