### PR TITLE
[AArch64] Add support for Armv9.6-A FEAT_SPE_EXC and FEAT_TRBE_EXC

### PR DESCRIPTION
**Pull request by jwestwood921**
Add support for the following Armv9.6-A architecture extensions:
  * FEAT_SPE_EXC  - Statistical Profiling Extension profiling exceptions
  * FEAT_TRBE_EXC - Trace Buffer Management Events profiling exceptions

as documented here:
  https://developer.arm.com/documentation/109697/2024_09/Feature-descriptions/The-Armv9-6-architecture-extension

### CODE REVIEW

**Review by nasherm — APPROVED** [review]
LGTM

**Review by jthackray — APPROVED** [review]
LGTM too

**Review by Stylie777 — APPROVED** [review]
LGTM

**Review by CarolineConcatto — APPROVED** [review]
LGTM

**Pull request merged**
