### PR TITLE
Revert "[MLIR][Arith] add fastMathAttr on arith::extf and arith::truncf"

### PR DESCRIPTION
**Pull request by crazydemo**
Reverts llvm/llvm-project#93443

### CODE REVIEW

**Comment by crazydemo** [comment]
To fix post-merge build error, suggest to set default attr to optioanl attr.
```
/vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.obj/bin/mlir-opt /vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.src/mlir/test/Integration/Dialect/SparseTensor/CPU/sparse_cast.mlir --sparsifier="enable-runtime-library=true" | /vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.obj/bin/mlir-cpu-runner -e main -entry-point-result=void -shared-libs=/vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.obj/lib/libmlir_c_runner_utils.so,/vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.obj/lib/libmlir_runner_utils.so | /vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.obj/bin/FileCheck /vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.src/mlir/test/Integration/Dialect/SparseTensor/CPU/sparse_cast.mlir
executed command: /vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.obj/bin/mlir-opt /vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.src/mlir/test/Integration/Dialect/SparseTensor/CPU/sparse_cast.mlir --sparsifier=enable-runtime-library=true
executed command: /vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.obj/bin/mlir-cpu-runner -e main -entry-point-result=void -shared-libs=/vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.obj/lib/libmlir_c_runner_utils.so,/vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.obj/lib/libmlir_runner_utils.so
.---command stderr------------
| loc("<stdin>":488:45): error: #"arith"<"fastmath<none>"> : 'none' attribute created with unregistered dialect. If this is intended, please call allowUnregisteredDialects() on the MLIRContext, or use -allow-unregistered-dialect with the MLIR opt tool used
| could not parse the input IR
`-----------------------------
error: command failed with exit status: 1
executed command: /vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.obj/bin/FileCheck /vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.src/mlir/test/Integration/Dialect/SparseTensor/CPU/sparse_cast.mlir
.---command stderr------------
| FileCheck error: '<stdin>' is empty.
| FileCheck command line:  /vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.obj/bin/FileCheck /vol/worker/mlir-nvidia/mlir-nvidia-gcc7/llvm.src/mlir/test/Integration/Dialect/SparseTensor/CPU/sparse_cast.mlir
`-----------------------------
error: command failed with exit status: 2
```

**Comment by joker-eph** [comment]
Thanks for fixing the build!

One minor nit for the future: please include the revert reason in the PR description (just a one line to say "buildbots are broken" will do).

**Comment by krzysz00** [comment]
Re the re-land ... maybe `DefaultValuedOptionalAttr` will be helpful?

**Comment by crazydemo** [comment]
> Re the re-land ... maybe `DefaultValuedOptionalAttr` will be helpful?

Thanks for your help! The new [PR](https://github.com/llvm/llvm-project/pull/95346) is here.

**Pull request merged**
