### PR TITLE
[Headers][X86] Add specific results to comparisons

### PR DESCRIPTION
**Pull request by pogo59**
Comparison intrinsics were described as returning the "result" without specifying how. The "cmp" intrinsics return zero or all 1's in the corresponding elements of a returned vector; the "com" intrinsics return an integer 0 or 1.

Also removed some redundant information.

### CODE REVIEW

**Comment by pogo59** [comment]
Also tag @cflores for your review.

**Review by phoebewang — APPROVED** [review]
LGTM.

**Comment by RKSimon** [comment]
@pogo This doesn't match what we did for the various cmp intrinsics in emmintrin.h - should it?
```cpp
/// Compares each of the corresponding signed 32-bit values of the
///    128-bit integer vectors to determine if the values in the first operand
///    are greater than those in the second operand.
///
///    Each comparison yields 0x0 for false, 0xFFFFFFFF for true.
///
/// \headerfile <x86intrin.h>
///
/// This intrinsic corresponds to the <c> VPCMPGTD / PCMPGTD </c> instruction.
```

**Comment by pogo59** [comment]
@RKSimon I was not aware of the comparison intrinsics in emmintrin.h. I will follow that pattern.

**Comment by pogo59** [comment]
@RKSimon note this will affect what the tooltips show. Is that okay?

**Comment by RKSimon** [comment]
> @RKSimon note this will affect what the tooltips show. Is that okay?

I think so - we're just losing the extra info about -1/0 or 1/0 result values?

**Comment by pogo59** [comment]
> I think so - we're just losing the extra info about -1/0 or 1/0 result values?

That's my understanding. I haven't actually tried regenerating the tooltips to check.

**Pull request merged**
