### PR TITLE
[AMDPU] Add support for idxen and bothen buffer load/store merging in SILoadStoreOptimizer

### PR DESCRIPTION
**Pull request by dstutt**
Added more buffer instruction merging support

### CODE REVIEW

**Comment by dstutt** [comment]
Can't do the merging on buffer_load_format since the format isn't known at compile time.

**Comment by arsenm** [comment]
I still think we should be doing this in the IR

**Comment by arsenm** [comment]
> Can't do the merging on buffer_load_format since the format isn't known at compile time.

But that's all this does?

**Comment by dstutt** [comment]
> > Can't do the merging on buffer_load_format since the format isn't known at compile time.
> 
> But that's all this does?

It also adds buffer_load_dword*_idxen/bothen

**Comment by jayfoad** [comment]
> > > Can't do the merging on buffer_load_format since the format isn't known at compile time.
> > 
> > 
> > But that's all this does?
> 
> It also adds buffer_load_dword*_idxen/bothen

Then the title should say that. "Add IDXEN/BOTHEN support to buffer load/store merging" or something.

**Review by jayfoad — APPROVED** [review]
Seems reasonable!

**Review by piotrAMD — APPROVED** [review]

**Pull request merged**
