### PR TITLE
[llvm-objcopy] Add SystemZ support

### PR DESCRIPTION
**Pull request by uweigand**
This is also necessary for enabling ClangBuiltLinux: https://github.com/ClangBuiltLinux/linux/issues/1530

### CODE REVIEW

**Review by MaskRay — APPROVED** [review]
LGTM, but please wait for jh7370, who usually prefers to read these changes.

**Review by jh7370 — APPROVED** [review]
Looks good, except it looks like we document the supported formats in the CommandGuide (see https://llvm.org/docs/CommandGuide/llvm-objcopy.html#supported-formats). Unfortunately, it looks like some of the newer ones are missing from that. If you're okay with doing so, it would be great if you could provide another PR that adds the remaining missing ones (I think it's just hexagon and loongarch, but could be wrong).

**Comment by uweigand** [comment]
> Looks good, except it looks like we document the supported formats in the CommandGuide (see https://llvm.org/docs/CommandGuide/llvm-objcopy.html#supported-formats). Unfortunately, it looks like some of the newer ones are missing from that. If you're okay with doing so, it would be great if you could provide another PR that adds the remaining missing ones (I think it's just hexagon and loongarch, but could be wrong).

Submitted as https://github.com/llvm/llvm-project/pull/81981, thanks!

**Comment by uweigand** [comment]
Can we backport this to LLVM 18 as well?

**Comment by jh7370** [comment]
> Can we backport this to LLVM 18 as well?

I don't know what's considered okay to, but this is fairly low-risk, so I think it's safe to. Please include the doc change in the backport too.

**Comment by uweigand** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/3c02cb7492fc78fb678264cebf57ff88e478e14f

**Comment by uweigand** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/3c02cb7492fc78fb678264cebf57ff88e478e14f

**Pull request merged**
