### PR TITLE
ValueTracking: generalize isNonEqualPHIs

### PR DESCRIPTION
**Pull request by artagnon**
isNonEqualPHIs was originally added in 3fd64cc ([ValueTracking] Handle two PHIs in isKnownNonEqual()), but as the new test case shows, it is not powerful enough. Generalize it, removing the APInt-specific comparison, and extend isKnownNonEqual to handle the case when one of the operands is a constant.

### CODE REVIEW

**Review by nikic — CHANGES_REQUESTED** [review]
The limitation exists for compile-time reasons. You will get exponential blowup if you run full recursion over all phi inputs.

**Comment by artagnon** [comment]
> The limitation exists for compile-time reasons. You will get exponential blowup if you run full recursion over all phi inputs.

Oh, so `Depth` is insufficient?

**Comment by nikic** [comment]
Yes, Depth is only sufficient for operations with low branching (generally, everything apart from phis will only need at most two recursive calls).

**Comment by artagnon** [comment]
What about the following then?

```diff
diff --git a/llvm/lib/Analysis/ValueTracking.cpp b/llvm/lib/Analysis/ValueTracking.cpp
index c46152f60aab..9e173d89e129 100644
--- a/llvm/lib/Analysis/ValueTracking.cpp
+++ b/llvm/lib/Analysis/ValueTracking.cpp
@@ -3538,7 +3538,8 @@ static bool isNonEqualPHIs(const PHINode *PN1, const PHINode *PN2,
     const Value *IV2 = PN2->getIncomingValueForBlock(IncomBB);
     SimplifyQuery RecQ = Q.getWithoutCondContext();
     RecQ.CxtI = IncomBB->getTerminator();
-    if (!isKnownNonEqual(IV1, IV2, DemandedElts, Depth + 1, RecQ))
+    if (!isKnownNonEqual(IV1, IV2, DemandedElts, MaxAnalysisRecursionDepth - 1,
+                         RecQ))
       return false;
   }
   return true;
```

**Comment by nikic** [comment]
We normally only allow `MaxAnalysisRecursionDepth - 1` for phis in ValueTracking.

**Comment by artagnon** [comment]
I see the following:

```cpp
  case Instruction::PHI: {
    const PHINode *P = cast<PHINode>(Op);
    // Unreachable blocks may have zero-operand PHI nodes.
    if (P->getNumIncomingValues() == 0)
      break;

    // Otherwise take the unions of the known bit sets of the operands,
    // taking conservative care to avoid excessive recursion.
    const unsigned PhiRecursionLimit = MaxAnalysisRecursionDepth - 2;
```

I'll push a change, and you can check it.

**Comment by artagnon** [comment]
With `MaxAnalysisRecursionDepth - 1`, we're less powerful than before, and a test fails.

**Comment by artagnon** [comment]
Gentle ping. Any thoughts on whether this patch is useful?

**Review by dtcxzyw — CHANGES_REQUESTED** [review]
```
; bin/opt -passes=early-cse reduced.ll -S
; ModuleID = 'reduced.ll'
source_filename = "reduced.ll"
target datalayout = "e-m:e-p270:32:32-p271:32:32-p272:64:64-i64:64-i128:128-f80:128-n8:16:32:64-S128"
target triple = "x86_64-unknown-linux-gnu"

define i1 @TLSX_ValidateSupportedCurves(i1 %lnot, i32 %conv21) {
entry:
  br label %for.cond

for.cond:                                         ; preds = %for.inc, %entry
  %defSz.0 = phi i32 [ %defSz.1, %for.inc ], [ 0, %entry ]
  %nextSz.0 = phi i32 [ %nextSz.1, %for.inc ], [ 0, %entry ]
  br i1 %lnot, label %for.body, label %land.lhs.true130

for.body:                                         ; preds = %for.cond
  switch i32 %conv21, label %for.inc [
    i32 0, label %sw.epilog26
    i32 1, label %sw.epilog26
  ]

sw.epilog26:                                      ; preds = %for.body, %for.body
  br label %for.inc

for.inc:                                          ; preds = %sw.epilog26, %for.body
  %defSz.1 = phi i32 [ %defSz.0, %for.body ], [ 0, %sw.epilog26 ]
  %nextSz.1 = phi i32 [ %nextSz.0, %for.body ], [ 0, %sw.epilog26 ]
  br label %for.cond

land.lhs.true130:                                 ; preds = %for.cond
  %cmp131 = icmp eq i32 %defSz.0, %nextSz.0
  ret i1 %cmp131
}
```
```
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: bin/opt -passes=early-cse test.ll -S
1.      Running pass "function(early-cse<>)" on module "test.ll"
2.      Running pass "early-cse<>" on function "TLSX_ValidateSupportedCurves"
  #0 0x00007fc029e13a92 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/libLLVMSupport.so.20.0git+0x213a92)
  #1 0x00007fc029e1095f llvm::sys::RunSignalHandlers() (/home/dtcxzyw/WorkSpace/Projects/compilers/LLVM/llvm-build/bin/../lib/libLLVMSupport.so.20.0git+0x21095f)
  #2 0x00007fc029e10aa5 SignalHandler(int) Signals.cpp:0:0
  #3 0x00007fc029842520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
  #4 0x00007fc022d29d7d isKnownNonEqual(llvm::Value const*, llvm::Value const*, llvm::APInt const&, unsigned int, llvm::SimplifyQuery const&) ValueTracking.cpp:0:0
  #5 0x00007fc022d2a218 isKnownNonEqual(llvm::Value const*, llvm::Value const*, llvm::APInt const&, unsigned int, llvm::SimplifyQuery const&) ValueTracking.cpp:0:0
  #6 0x00007fc022d2a218 isKnownNonEqual(llvm::Value const*, llvm::Value const*, llvm::APInt const&, unsigned int, llvm::SimplifyQuery const&) ValueTracking.cpp:0:0
  #7 0x00007fc022d2a218 isKnownNonEqual(llvm::Value const*, llvm::Value const*, llvm::APInt const&, unsigned int, llvm::SimplifyQuery const&) ValueTracking.cpp:0:0
  #8 0x00007fc022d2a218 isKnownNonEqual(llvm::Value const*, llvm::Value const*, llvm::APInt const&, unsigned int, llvm::SimplifyQuery const&) ValueTracking.cpp:0:0
  #9 0x00007fc022d2a218 isKnownNonEqual(llvm::Value const*, llvm::Value const*, llvm::APInt const&, unsigned int, llvm::SimplifyQuery const&) ValueTracking.cpp:0:0
 #10 0x00007fc022d2a218 isKnownNonEqual(llvm::Value const*, llvm::Value const*, llvm::APInt const&, unsigned int, llvm::SimplifyQuery const&) ValueTracking.cpp:0:0
 #11 0x00007fc022d2a218 isKnownNonEqual(llvm::Value const*, llvm::Value const*, llvm::APInt const&, unsigned int, llvm::SimplifyQuery const&) ValueTracking.cpp:0:0
...
#250 0x00007fc022d2a218 isKnownNonEqual(llvm::Value const*, llvm::Value const*, llvm::APInt const&, unsigned int, llvm::SimplifyQuery const&) ValueTracking.cpp:0:0
#251 0x00007fc022d2a218 isKnownNonEqual(llvm::Value const*, llvm::Value const*, llvm::APInt const&, unsigned int, llvm::SimplifyQuery const&) ValueTracking.cpp:0:0
#252 0x00007fc022d2a218 isKnownNonEqual(llvm::Value const*, llvm::Value const*, llvm::APInt const&, unsigned int, llvm::SimplifyQuery const&) ValueTracking.cpp:0:0
#253 0x00007fc022d2a218 isKnownNonEqual(llvm::Value const*, llvm::Value const*, llvm::APInt const&, unsigned int, llvm::SimplifyQuery const&) ValueTracking.cpp:0:0
#254 0x00007fc022d2a218 isKnownNonEqual(llvm::Value const*, llvm::Value const*, llvm::APInt const&, unsigned int, llvm::SimplifyQuery const&) ValueTracking.cpp:0:0
#255 0x00007fc022d2a218 isKnownNonEqual(llvm::Value const*, llvm::Value const*, llvm::APInt const&, unsigned int, llvm::SimplifyQuery const&) ValueTracking.cpp:0:0
Segmentation fault (core dumped)
```

**Comment by artagnon** [comment]
Thanks, taking a look.

**Comment by artagnon** [comment]
The issue was a thinko, which was simple enough to fix. I think the patch should be good now.

**Comment by artagnon** [comment]
Gentle ping.

**Comment by artagnon** [comment]
Gentle ping. Seems like a straightfoward patch.

**Comment by artagnon** [comment]
Gentle ping.

**Review by nikic — COMMENTED** [review]
Based on llvm-opt-benchmark, this has basically no practical impact. Given that, I'd rather not change the phi recursion handling in this function.

**Comment by artagnon** [comment]
Okay, I'll open a fresh PR for the new test, since I think that part is valuable.

**Pull request closed without merging**
