### PR TITLE
[libc++] Remove unused defaulted template arg from `__rewrap_range`.

### PR DESCRIPTION
**Pull request by AMP999**
Template argument `_Unwrapped` is always deduced from the type of `_Unwrapped __iter`.

### CODE REVIEW

**Comment by AMP999** [comment]
The CI is failing in https://buildkite.com/llvm-project/libcxx-ci/builds/30092#018add7f-bf00-44ec-9959-2a1ac111d99c because the benchmarks already committed to `main` are trying to use `ranges::ends_with` in C++20 mode. What should I do about that? 
@var-const

**Comment by ldionne** [comment]
> The CI is failing in https://buildkite.com/llvm-project/libcxx-ci/builds/30092#018add7f-bf00-44ec-9959-2a1ac111d99c because the benchmarks already committed to `main` are trying to use `ranges::ends_with` in C++20 mode. What should I do about that? @var-const

This should be fixed on `main` now.

**Review by ldionne — APPROVED** [review]
This makes sense to me, but I'd like @philnik777 to have a quick look as well to make sure this was a copy-paste error (what it looks like).

@philnik777 Did you write it that way to make it possible to deduce from something like `{}` passed as an argument?

@AMP999 Please wait for @philnik777 to validate before merging.

**Review by philnik777 — APPROVED** [review]
I think my initial intent was to ensure that we only take the unwrapped iterator. Basically, the argument should have been `type_identity_t<_Unwrapped>`. Given that this is already enforced by `__unwrap_iter_impl`, i don't think there is anything wrong with just removing the default (especially given that it's broken already).

LGTM with a clang-format run. (The file is formatted % the changed lines and a whitespace change above)

**Comment by AMP999** [comment]
@philnik777 The CI is green with respect to clang-format. Can you help me land this? `Amirreza Ashouri <ar.ashouri999@gmail.com>`

**Comment by AMP999** [comment]
@philnik777 The CI is green with respect to clang-format. Can you help me land this? `Amirreza Ashouri <ar.ashouri999@gmail.com>`

**Comment by philnik777** [comment]
You have to remove `libcxx/include/__algorithm/unwrap_range.h` from `libcxx/utils/data/ignore_format.txt` to check formatting.

**Comment by AMP999** [comment]
> You have to remove `libcxx/include/__algorithm/unwrap_range.h` from `libcxx/utils/data/ignore_format.txt` to check formatting.

Thank you! I've fixed that.

**Review by philnik777 — APPROVED** [review]

**Pull request merged**
