### PR TITLE
[X86] AMD Zen 5 Initial enablement

### PR DESCRIPTION
**Pull request by ganeshgit**
Enables AMD Zen5 family of architectures. The models covered are 

Models 00h-0Fh (Breithorn).
Models 10h-1Fh (Breithorn-Dense).
Models 20h-2Fh (Strix 1).
Models 30h-37h (Strix 2).
Models 38h-3Fh (Strix 3).
Models 40h-4Fh (Granite Ridge).
Models 50h-5Fh (Weisshorn).
Models 60h-6Fh (Krackan1).
Models 70h-77h (Sarlak).

### CODE REVIEW

**Comment by ganeshgit** [comment]
@RKSimon @tru There was a conflict with [#104601](https://github.com/llvm/llvm-project/commit/39e3085a55880dbbc5aeddc3661342980d5e1467) while cherry-picking the earlier commit from main. So, I had to update this change. The change to X86TargetParser.h (https://github.com/llvm/llvm-project/pull/108816/commits/6b5fe4ed02c8172772c2e765ccd220adbfabe4cc#diff-8d5f0e99f0c2484c205b0dc27e029e9b39e06820e0b78a83a77cb1bfd5a158be) is done so as to fix the ABI issues where CK_ZNVER5 is pushed to the end of enum list.

**Comment by tru** [comment]
@nikic @AaronBallman

**Review by nikic — APPROVED** [review]
Looks reasonable to me.

**Comment by ganeshgit** [comment]
> Looks reasonable to me.

Thank you @tru @RKSimon. @nikic I will make sure that the delay between GCC patches are llvm patches are avoided. Thanks a lot!

**Review by RKSimon — APPROVED** [review]

**Comment by RKSimon** [comment]
LLVM Release Notes:
```
Changes to the X86 Backend
-mcpu=znver5 is now supported.
```
Clang Release Notes:
```
X86 Support
-march=znver5 is now supported
```
@ganeshgit Are you happy with this?

**Comment by ganeshgit** [comment]
> LLVM Release Notes:
> 
> ```
> Changes to the X86 Backend
> -mcpu=znver5 is now supported.
> ```
> 
> Clang Release Notes:
> 
> ```
> X86 Support
> -march=znver5 is now supported
> ```
> 
> @ganeshgit Are you happy with this?

Thank you! Yes. This is good!

**Pull request merged**
