### PR TITLE
[NVPTX] Allow compiling LLVM-IR without `-march` set

### PR DESCRIPTION
**Pull request by jhuber6**
Summary:
The NVPTX tools require an architecture to be used, however if we are
creating generic LLVM-IR we should be able to leave it unspecified. This
will result in the `target-cpu` attributes not being set on the
functions so it can be changed when linked into code. This allows the
standalone `--target=nvptx64-nvidia-cuda` toolchain to create LLVM-IR
simmilar to how CUDA's deviceRTL looks from C/C++

### CODE REVIEW

**Review by jlebar — APPROVED** [review]

**Comment by Artem-B** [comment]
Relying on something *not* being defined is probably not the best way to handle 'generic' target. For starters it makes it hard or impossible to recreate the same compilation state by undoing already-specified option. It also breaks established assumption that there *is* a default target CPU/GPU. If we do want to have a generic GPU target, then we should grow an explicit 'generic' GPU variant, IMO. It would be a functional opposite of 'native'.

**Comment by jhuber6** [comment]
> Relying on something _not_ being defined is probably not the best way to handle 'generic' target. For starters it makes it hard or impossible to recreate the same compilation state by undoing already-specified option. It also breaks established assumption that there _is_ a default target CPU/GPU. If we do want to have a generic GPU target, then we should grow an explicit 'generic' GPU variant, IMO. It would be a functional opposite of 'native'.

AMDGPU uses a missing `-mcpu` on the OpenCL target to build their "generic" device libraries and it's also missing from NVIDIA's `libdevice.10.bc` in the same way. I think there's some precedent from both vendors to treat missing attributes as a more generic target. The default target to me is more of the domain of the driver. So if you're using CUDA and don't specify anything you get `sm_52`. This patch also creates a hard error if it's unspecified before it makes it to the tools like ptxas and nvlink.

**Comment by Artem-B** [comment]
> I think there's some precedent from both vendors to treat missing attributes as a more generic target.

It sounds more like a bug than a feature to me.

The major difference between "you get sm_xx by default" and this "you get generic by default" is that With specific sm_XX, I can override it both ways -- I wan enable/disable it if I need to regardless of how it was specified before my overriding options.

With the magic unnameable 'generic' target, I can only disable it by specifying it, but there's no way to enable it once a preceding option names some specific architecture.

It makes little difference where you control complete build, but that is not the case for all builds. E.g. Tensorflow builds with bazel and the end user does not have access to whatever compiler flags global build rules may set. So if you want to build for generic GPU target, you will have to jump through way more hoops than is reasonable, as opposed to specifying a few overriding options you're interested in.

I'm fine with defaulting to such generic target, but I do believe we need to handle it the same way as specific targets.

**Comment by jhuber6** [comment]
> > I think there's some precedent from both vendors to treat missing attributes as a more generic target.
> 
> It sounds more like a bug than a feature to me.
> 
> The major difference between "you get sm_xx by default" and this "you get generic by default" is that With specific sm_XX, I can override it both ways -- I wan enable/disable it if I need to regardless of how it was specified before my overriding options.
> 
> With the magic unnameable 'generic' target, I can only disable it by specifying it, but there's no way to enable it once a preceding option names some specific architecture.
> 
> It makes little difference where you control complete build, but that is not the case for all builds. E.g. Tensorflow builds with bazel and the end user does not have access to whatever compiler flags global build rules may set. So if you want to build for generic GPU target, you will have to jump through way more hoops than is reasonable, as opposed to specifying a few overriding options you're interested in.
> 
> I'm fine with defaulting to such generic target, but I do believe we need to handle it the same way as specific targets.

We could make the driver require some special argument, but the question is how that should be reflected in the LLVM-IR. Right now if you specify `target-cpu` you get `target-cpu` attributes, which is what we don't want. The standard behavior on all other targets is to ignore target-dependent attributes when `-march` or `-mcpu` isn't set, which is exactly what we want here. On the driver level we could hide this behind `-march=generic` if that's important, but I think inside of `clang` it should just be if it's missing as that's the standard handling.

**Comment by Artem-B** [comment]
> Right now if you specify target-cpu you get target-cpu attributes, which is what we don't want. 

I'm fine handling 'generic' in a special way under the hood and not specifying target-CPU.

My concern is about user-facing interface. Command line options must be overridable. 
For the CPU I would be able to specify the variant that matches the default.
For GPU I'll have no way to explicitly pick 'generic' as the target. I think this is important.

**Comment by jhuber6** [comment]
> > Right now if you specify target-cpu you get target-cpu attributes, which is what we don't want.
> 
> I'm fine handling 'generic' in a special way under the hood and not specifying target-CPU.
> 
> My concern is about user-facing interface. Command line options must be overridable. For the CPU I would be able to specify the variant that matches the default. For GPU I'll have no way to explicitly pick 'generic' as the target. I think this is important.

I can add `generic` for overloading purposes, but I'd prefer if leaving it off implied generic as well, at least for this standalone target version. This is a little divergent from standard CPU targets because GPUs have no backward compatibility, so something being "generic" requires a bit more work.

**Comment by Artem-B** [comment]
Considering that it's for the stand-alone compilation only, I'm not going to block this patch.
That said, please add a `TODO` somewhere to address an issue w/ explicitly targeting generic variant.

**Review by Artem-B — APPROVED** [review]

**Pull request merged**
