### PR TITLE
[clang-tidy] bugprone-unused-return-value config now supports regexes

### LINKED ISSUE #63107: `bugprone-unused-return-value`: Allow `*` in `CheckedFunctions` and/or `CheckedReturnTypes`
It would be nice to force the user to use/check all return values, to reduce the number of accidental error ignores from functions in 3rd party libraries.

This was requested at least once on StackOverflow: https://stackoverflow.com/q/69480128/7851861.

### PR DESCRIPTION
**Pull request by felix642**
The parameter `CheckedFunctions` now supports regexes

Fixes #63107

### CODE REVIEW

**Review by HerrCai0907 — APPROVED** [review]

**Review by PiotrZSL — APPROVED** [review]
LGTM, but update also check documentation, simply put there default config so user could easily copy it change, and add new functions. And mention that this support regexp.

**Comment by PiotrZSL** [comment]
Rebase, and could be merged.

**Comment by felix642** [comment]
> Rebase, and could be merged.

Done, thank you for the quick review.

**Comment by felix642** [comment]
Nevermind I broke the documentation.. Hold on

**Pull request merged**
