### PR TITLE
[libc][NFC] Small `abs` related simplifications

### PR DESCRIPTION
**Pull request by gchatelet**

### CODE REVIEW

**Review by lntue — APPROVED** [review]

**Comment by nickdesaulniers** [comment]
don't forget to land this

**Comment by jhuber6** [comment]
> don't forget to land this

Can't other people merge PRs on the author's behalf?

**Comment by nickdesaulniers** [comment]
> > don't forget to land this
> 
> Can't other people merge PRs on the author's behalf?

Yes; I was hesitant in case there was a reason this hasn't been merged. There might not be, but just in case my personal preference is to defer to the patch author (when they have merge access).  I also prefer to leave the dopamine hit for clicking merge to the author of the work.  But if other people feel differently, I don't feel strongly about it either way.

**Comment by gchatelet** [comment]
I actually missed @lntue's approval, thx for the ping. Landing this now.

**Pull request merged**
