### PR TITLE
[clang] Add GCC-compatible code model names for sparc64

### PR DESCRIPTION
**Pull request by koachan**
This adds GCC-compatible names for code model selection on 64-bit SPARC with absolute code.
Testing with a 2-stage build then running codegen tests works okay under all of the supported code models.

(32-bit target does not have selectable code models)

### CODE REVIEW

**Comment by MaskRay** [comment]
Have you checked whether these code models are actually implemented and how complete they are?
For example, if one model is very far from complete, perhaps we should be honest and say it is unsupported.

**Comment by rorth** [comment]
GCC also supports `-mcmodel=embmedany`.  Maybe it would be good to reject that with a clear message?

As for the generated code (not this PR, I'd say), it would certainly be good to test that on some larger code base (like LLVM itself) and, preferably, also test actual interoperability with GCC. Especially in SPARC support, I have seen to many cases where LLVM wouldn't interoperate with itself, let alone GCC.

**Comment by rorth** [comment]
> `embmedany` is already rejected by the driver at the moment:
> 
> ```
> error: unsupported argument 'embmedany' to option '-mcmodel=' for target 'sparc64'
> ```
Seems sensible indeed.
> On the testing issue, however, would compiling LLVM with each of the code models + running codegen tests be enough to at least exercise the relevant parts (and see if there's still issues, etc.)?

I'd run 2-stage builds/tests (either with the existing machinery or by building LLVM twice explicitly: once with an external compiler and then again with the just-built one).

**Review by brad0 — APPROVED** [review]

**Review by MaskRay — APPROVED** [review]

**Comment by MaskRay** [comment]
> > I'd run 2-stage builds/tests (either with the existing machinery or by building LLVM twice explicitly: once with an external compiler and then again with the just-built one).
> 
> It does seem that at least when it comes to LLVM itself, 2-stage build/tests works okay under all of the supported code models...

Can you edit the description (first comment) to include your testing?

**Pull request merged**
