### PR TITLE
[AMDGPU] Remove Code Object V3

### PR DESCRIPTION
**Pull request by Pierre-vh**
V3 has been deprecated for a while as well, so it can safely be removed like V2 was removed.

- [Clang] Set minimum code object version to 4
- [lld] Fix tests using code object v3
- Remove code object V3 from the AMDGPU backend, and delete or port v3 tests to v4.
- Update docs to make it clear V3 can no longer be emitted.

### CODE REVIEW

**Review by kzhuravl — APPROVED** [review]
This LGTM. But wait a couple of days to see if @arsenm or @yxsamliu have any objections?

**Comment by Pierre-vh** [comment]
Is it fine if I land this on Monday if there are no new objections?
cc @arsenm @yxsamliu

**Review by yxsamliu — APPROVED** [review]
LGTM. Thanks

**Review by arsenm — APPROVED** [review]

**Comment by tob2** [comment]
> V3 has been deprecated for a while as well, so it can safely be removed

We are using v3 for (better) backward compatibility with the older gfx803 / fiji cards (GCN GFX8 (Volcanic Islands (VI))) — thus, this commit on Monday broke our tester for gfx803 / fiji cards :-(

However, for newer cards (like GCN GFX9 (Vega) – or newer), we use v4, which works perfectly well.

**Comment by ams-cs** [comment]
@Pierre-vh Can we undo this please? Just for now.

This broke the GCC build (which uses llvm-mc) because we still use v3 like @tob2 said. I don't know that anyone is using Fiji in production, but it's still a good proportion of what we have in our compiler test farm.

As far as I know, the last good ROCm for that device was 3.8 which doesn't support v4.

I appreciate that this isn't ideal; I'd like to remove that device too.

**Comment by Pierre-vh** [comment]
I don't mind reverting, but do you have a timeline for removal of that device? v3 has been deprecated for a while, AFAIK.

**Comment by ams-cs** [comment]
We're discussing replacing the devices with something newer, but there are practical and business issues with that, so no hard plans. Sorry.

I'm leaning toward officially deprecating Fiji for GCC 14, and remove it from GCC 15 (so, sometime next year). If we can get these devices replaced then it can happen sooner. For release branches we can document a fixed LLVM version to use, so it's only really the mainline development branch that is the problem.

**Comment by ams-cs** [comment]
GCC deprecation done: [commit details](https://gcc.gnu.org/git/?p=gcc.git;a=commitdiff;h=56ed1055b2f40ac162ae8d382280ac07a33f789f;hp=8f4bbdc28df6e87a7ad5ec5ca191a7a836a4f016).

**Pull request merged**
