### PR TITLE
[clangd] Expand response files before CDB interpolation

### PR DESCRIPTION
**Pull request by dmpolukhin**
Summary:

After https://reviews.llvm.org/D143436 response files stopped working with CDB interpolation. It has happened because interpolation removes all unknwn flags and extra input files. Response file is treated as an extra input because it is not a flag. Moreover inference needs full command line for driver mode and file type detection so all response files have to be expanded for correct inference.

This patch partially reverts D143436 and add additional response file expansion in OverlayCDB for CDBs pushed via LSP.

Test Plan: check-clangd

Tasks: https://github.com/llvm/llvm-project/issues/69690

### CODE REVIEW

**Review by HighCommander4 — CHANGES_REQUESTED** [review]
Thanks for having a look at this!

Instead of performing the "expand response files" operation twice for commands coming from a `compile_commands.json` source, what do you think about the following:

 * Restore the call in `parseJSON()` (i.e. what the patch is doing now), **and**
 * Move the call in `CommandMangler` to a place that is only used for commands coming from the LSP, such as around [here](https://searchfox.org/llvm/rev/b6cce87110072a2db19276e042cd40b06285abbc/clang-tools-extra/clangd/GlobalCompilationDatabase.cpp#745)?
   * We could consider abstracting `OverlayCDB::Commands` into a dedicated `tooling::CompilationDatabase` implementation so that we can simply wrap it using `clang::tooling::expandResponseFiles()`, but feel free to leave that for later; a direct call to `tooling::addExpandedResponseFiles`, as we had in the mangler itself, is fine for now.

It would be nice to have a unit test for this regression as well. We have tests exercising `OverlayCDB` in [GlobalCompilationDatabaseTests.cpp](https://searchfox.org/llvm/source/clang-tools-extra/clangd/unittests/GlobalCompilationDatabaseTests.cpp), I think that should be suitable.

**Comment by dmpolukhin** [comment]
@HighCommander4 PTAL

**Review by HighCommander4 — APPROVED** [review]
LGTM, thanks for the fix and test!

**Comment by HighCommander4** [comment]
@twmht To my knowledge, clang and clangd have only ever supported the `@file.rsp` response file syntax.

The commands in the linked thread use the `--options-file file.rsp` syntax, which clang and clangd do not support. https://github.com/clangd/vscode-clangd/issues/592 is on file about this, but please note that clangd is unlikely to add support for this syntax without the clang driver itself adding support first.

**Pull request merged**
