### PR TITLE
fix(python): fix invalid escape sequences

### LINKED ISSUE #92948: [BUG][clang-tidy-diff] `SyntaxWarning`: invalid escape sequence
```sh
clang-tidy-diff.py:245: SyntaxWarning: invalid escape sequence '\+'
  match = re.search('^\+\+\+\ "?(.*?/){%s}([^ \t\n"]*)' % args.p, line)
clang-tidy-diff.py:258: SyntaxWarning: invalid escape sequence '\+'
  match = re.search("^@@.*\+(\d+)(,(\d+))?", line)
```
Using python:
```sh
$ python3 -VV
Python 3.12.3 (main, Apr  9 2024, 08:09:14) [Clang 15.0.0 (clang-1500.3.9.4)]
```

It seems these strings need to be raw strings:
```python3
match = re.search(r'^\+\+\+\ "?(.*?/){%s}([^ \t\n"]*)' % args.p, line)
#                 ^ note
```

### PR DESCRIPTION
**Pull request by e-kwsm**

### CODE REVIEW

**Comment by tstellar** [comment]
Two questions:
* Did you use a script to generate this patch?
* Why do we need to make this change?

**Comment by e-kwsm** [comment]
> Why do we need to make this change?

The valid escape sequences in Python are listed [here](https://docs.python.org/3/reference/lexical_analysis.html#escape-sequences): `\t`, `\n`, etc.

Invalid ones fixed here seem to be used for regular expression, [re](https://docs.python.org/3/library/re.html), e.g. `\.` for literal dot, `\d` for a digit `[0-9]`.

I use [flake8](https://flake8.pycqa.org/en/latest/) for check.

> Did you use a script to generate this patch?

No. We have choices to fix these:

1. escape backslashes: `"\s"` -> `"\\s"`
2. use raw string: `"\s"` -> `r"\s"`

I thought 2 is simple but actually it does not work for e.g.:

```diff
--- a/clang-tools-extra/clang-tidy/tool/clang-tidy-diff.py
+++ b/clang-tools-extra/clang-tidy/tool/clang-tidy-diff.py
@@ -242,7 +242,7 @@ def main():
     filename = None
     lines_by_file = {}
     for line in sys.stdin:
-        match = re.search('^\+\+\+\ "?(.*?/){%s}([^ \t\n"]*)' % args.p, line)
+        match = re.search('^\\+\\+\\+\\ "?(.*?/){%s}([^ \t\n"]*)' % args.p, line)
         if match:
             filename = match.group(2)
         if filename is None:
```

Here `\t\n` is valid whereas `\+` is not.

So I manually fixed them.

**Comment by zufuliu** [comment]
> Why do we need to make this change?

https://docs.python.org/3/reference/lexical_analysis.html#escape-sequences

> Changed in version 3.12: Unrecognized escape sequences produce a [SyntaxWarning](https://docs.python.org/3/library/exceptions.html#SyntaxWarning). In a future Python version they will be eventually a [SyntaxError](https://docs.python.org/3/library/exceptions.html#SyntaxError).


doubling backlash inside regex string is poor than adding raw string prefix `r`.

**Comment by boomanaiden154** [comment]
I think you'll probably want to split this into multiple PRs, at least one per root folder in the monorepo. That will make a bunch of smaller PRs which will be easier to review and will also allow you to request review from people specifically responsible for those areas.

And I think I would agree that using `r` before the string is better for regular expressions.

**Review by JDevlieghere — CHANGES_REQUESTED** [review]
As per Aiden's suggestion, please split this up into smaller PRs, grouped by subproject.

**Comment by e-kwsm** [comment]
broken into

- #94028
- #94029
- #94030
- #94031
- #94032
- #94033
- #94034
- #94035
- #94036
- #94037

**Pull request closed without merging**
