### PR TITLE
[InstSimplify] Fold (a != 0) ? abs(a) : 0

### PR DESCRIPTION
**Pull request by Pierre-vh**
Solves #70204

### CODE REVIEW

**Review by nikic — CHANGES_REQUESTED** [review]
This fold is not specific to zero values.

This should be implemented in simplifyWithOpReplaced() -- basically, you need to teach it that even if the poison flag is set, there is no derefinement if the value is not signed min.

**Comment by Pierre-vh** [comment]
Ah I see, indeed we already do this when the poison flag is not set.
Can you elaborate a bit? What do you mean by derefinement?

How can I infer the value isn't signed min in that function?

**Review by nikic — COMMENTED** [review]
Looks ok, but some of the tests should be adjusted to check a value other than zero (preferably also some negative ones, where the one in select will be positive). And of course we should check that the case of signed min specifically does not get transformed. (It could be transformed, but only if the flag is also flipped.)

**Review by nikic — APPROVED** [review]
LGTM

**Comment by preames** [comment]
This landed with a submission comment which was very out of sync with the approved code.  That's very bad practice, please remember to update the submit comment before pushing the change to main.

**Pull request merged**
