### PR TITLE
[analyzer] Moving TaintPropagation checker out of alpha

### PR DESCRIPTION
**Pull request by dkrupp**
This commit moves the **alpha.security.taint.TaintPropagation** and **alpha.security.taint.GenericTaint** checkers to the **optin.taint** optional package.

These checkers were stabilized and improved by recent commits thus it's ready for production use.

The **optin.taint.GenericTaint** user facing checker is placed in the optin package as it implements an optional security analysis.

Reports by the checker if switched on :

| Project | New Reports | Resolved Reports |
|---------|-------------|------------------|
| memcached | No reports | No reports 
| tmux | No reports | No reports 
| twin | No reports | No reports 
| vim | [1 new reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=vim_v8.2.1920_dkrupp_taint_dealpha_baseline&newcheck=vim_v8.2.1920_dkrupp_taint_dealpha_new&diff-type=New) | No reports 
| openssl | No reports | No reports 
| sqlite | No reports | No reports 
| libwebm | No reports | No reports 
| xerces | No reports | No reports 
| postgres | [2 new reports](https://codechecker-demo.eastus.cloudapp.azure.com/Default/reports?run=postgres_REL_13_0_dkrupp_taint_dealpha_baseline&newcheck=postgres_REL_13_0_dkrupp_taint_dealpha_new&diff-type=New) | No reports 

There are 2 new true positive reports in postgresql.
If the environment variables regarded untrusted, an attacker may be able to execute arbitrary command through popen.

The new report in VIM is unrelated to the taint analysis and likely appaered as the symbolic execution took different paths.

### CODE REVIEW

**Comment by haoNoQ** [comment]
#61826 has my data (which I unfortunately couldn't publish as-is, but the order of magnitude is, around 300 reports).

My main problem with the tainted-number checkers is that they don't consider at constraints at all. Eg., this is clearly a false positive:
```
char buf[100];
size_t size = tainted();
if (size > 100)
  return;
memset(buf, 0, size); // EnTrUsTeD DAtA Is UsEd TO sPeCiFY BuFfER SiZe
```

This applies to this checker and the VLA checker that gets turned on when you enable the taint checker (it's already enabled but it never fires because there isn't any taint information in the state). 

> Untrusted data is used to specify the buffer size

The report may be technically correct but I think the entire idea of the checker never made sense in the first place. It doesn't matter that untrusted data is used to specify buffer size once; it matters that data with _different levels of trust_, or _coming from different sources_, is used  to specify size of the same buffer _on different occasions_.

It's fine to allocate a buffer of tainted size and then copy exactly that many bytes into it. It's not fine to allocate a buffer of fixed size and copy tainted amount of data into it. It's not fine to allocate a buffer of tainted size and copy a fixed amount of data into it.

 So I think this checker has to stay in alpha until it can be reworked to make sense.

**Comment by haoNoQ** [comment]
(Yeah we still have those false positives, though `memset` isn't actually covered yet as a potential sink: https://godbolt.org/z/6h5x87vMc)

**Comment by DonatNagyE** [comment]
I agree that it's a blocking issue that some numerical arguments act as taint sinks unconditionally (even if the analyzer knows about constraints that show that the actual value is valid). I'd suggest that those concrete issues should be addressed by separate improvement commits, and we should reconsider this "move out of alpha" commit afterwards.

As I briefly scrolled through the list of sink functions, it seems that there are two affected function families: the `malloc`-like functions and `memcpy`-like functions.

IMO in the `malloc` function family the ideal behavior would be:
1. Report a _tainted buffer size can be huge_ warning when we cannot deduce that the allocated memory area is less than a certain threshold (e.g. 1 MiB, the user should be able to configure this). I'd say that it's a  bug (denial of service opportunity) if untrusted data can trigger huge memory allocations (gigabytes, terabytes, `SIZE_MAX` etc.).
2. Mark the extent symbol of the allocated memory area as tainted and ensure that this triggers the the taint-aware (a/k/a paranoid) mode of e.g. ArrayBoundsV2 and similar checkers.

I think these checks should be implemented in MallocChecker, where we already have lots of logic related to the size of allocated memory. 

The `memcpy` function family is a simpler case, there we should just eliminate the current "generic taint sink" behavior (= if the number of copied bits is tainted, always report a bug) and replace it with taint-aware optimism/pessimism in CStringChecker (where AFAIK we already have logic that checks whether the memcopied chunks fits into the target memory region). This logic would let us accept
```c++
char buf[100], srcBuf[100] = {0};
size_t size = tainted();
if (size > 100)
  return;
memcpy(buf, srcBuf, size);
```
while creating a bug report for the variant where the early return condition is `(size > 101)`.

@haoNoQ I don't really understand your remark that
> The report may be technically correct but I think the entire idea of the checker never made sense in the first place. It doesn't matter that untrusted data is used to specify buffer size once; it matters that data with _different levels of trust_, or _coming from different sources_, is used to specify size of the _same buffer on different occasions_.

What does "size of the same buffer on different occasions" mean here? I'd guess that it refers to something like
```c++
void *get_mem(bool use_default_size) {
  size_t size = 1024;
  if (!use_default_size)
    size = get_tainted_number_from_config_file();
  // do something important that we want to do before each allocation...
  return malloc(size);
}
```
but I'd argue that this is actually valid (although a bit unusual) code.

Personally I feel that the _core idea of this checker_ is that it marks the return value of some functions as tainted to let security-conscious users may wish to enable pessimistic handling of that data. This is a direct and unavoidable "replace FNs with FPs tradeoff" and I think the users should have this option even if it produces a significant amout of FPs.

However you're completely right that even in "pessimistic handling" the analyzer should at least consult the current state before reporting that "this number is tainted, the `memcpy` / `memset` / etc. may cause a buffer overrun".

(Also note that this the simplistic "tainted data + sink = bug report" logic is appropriate for functions like `system` where the potentially tainted data is a string; because we cannot store meaningful constraints about strings.)

**Comment by haoNoQ** [comment]
> @haoNoQ I don't really understand your remark that
> 
> > The report may be technically correct but I think the entire idea of the checker never made sense in the first place. It doesn't matter that untrusted data is used to specify buffer size once; it matters that data with _different levels of trust_, or _coming from different sources_, is used to specify size of the _same buffer on different occasions_.
> 
> What does "size of the same buffer on different occasions" mean here? I'd guess that it refers to something like
> 
> ```c++
> void *get_mem(bool use_default_size) {
>   size_t size = 1024;
>   if (!use_default_size)
>     size = get_tainted_number_from_config_file();
>   // do something important that we want to do before each allocation...
>   return malloc(size);
> }
> ```
> 
> but I'd argue that this is actually valid (although a bit unusual) code.

No-no, I mean whatever I said in the next sentence, like literally the same buffer, not the same allocation site, not the same variable, but literally the same allocation, except it has multiple size-aware operations performed on it, like this:

```c
size_t N = tainted();
size_t M = 10;

// Should warn. Out-of-bounds access if N is too large.
char *buf1 = malloc(M);
memset(buf1, 0,     N);

// Should warn. Out-of-bounds access if N is too small.
char *buf2 = malloc(N);
memset(buf2, 0,     M);

 // Perfectly valid code, even if both accesses are performed with tainted, unconstrained size.
char *buf3 = malloc(N);
memset(buf3, 0,     N);
```

**Comment by DonatNagyE** [comment]
> No-no, I mean whatever I said in the next sentence, like literally the same buffer, not the same allocation site, not the same variable, but literally the same allocation, except it has multiple size-aware operations performed on it,  [...]

Thanks for the clarification! I agree with your examples and that behavior can be achieved via the solutions that I suggested (the separate patches for the `malloc` and `memcpy` function families) .

**Comment by dkrupp** [comment]
@haoNoQ  thanks for pointing out #61826 umbrella issue, I somehow missed that.

I see this TaintPropagation checker as a generic flexible tool to find potential vulnerable data flows between any taint source and taint sink. The user should be configure sources and sinks in the yaml config file. The default settings will not always be correct. (Whether a file is a tainted source or not, depends a lot on the actual application domain and maybe the deployment.)
This checker warns for every sink unconditionally.

The user can explicitly mark a value as sanitized in these cases:
```
  scanf (" %1023[^\n]", filename);
  if (access(filename,F_OK)){// Verifying user input
    printf("File does not exist\n");
    return -1;
  }
  #ifdef __clang_analyzer__
    csa_mark_sanitized(filename); // Indicating to CSA that filename variable is safe to be used after this point
  #endif
  strcat(cmd, filename);
  system(cmd); // No warning
```
See the example for details in the doc:
https://clang.llvm.org/docs/analyzer/checkers.html#alpha-security-taint-taintpropagation-c-c

Of course it is annoying to add such instructions for tainted integer values, for which the analyzer can perform bounds checking automatically and refute some trivial false positives cases which you also pointed out.

I saw many false positives for malloc(..) calls when tainted buffer was attempted to be copied to another buffer and fixed that in this PR (by removing taint propagation for strlen):
* https://github.com/llvm/llvm-project/pull/66086
For me it refuted most of the FPs on open source projects.

At the end, I agree with you that it is better to remove all the unconditional integer taint sinks from the TaintPropagation checker and handle it in the MallocChecker, CStringChecker to take integer constraints into consideration.
So this PR does that:
* https://github.com/llvm/llvm-project/pull/68607
I will make follow-up patches to re-add these warnings for `malloc()` and `memcpy()` etc. on the MallocChecker, CStringChecker with a more sophisticated handling.

The VLA case you pointed out I fixed in:
* https://github.com/llvm/llvm-project/pull/68140

In case of strings , it is very difficult (in general impossible?) to automatically recognize the programmer's attempt to santize the data.
So I think  `csa_mark_sanitized(string);` is an acceptable solution to get rid of unwanted warnings (or using a triaging tool).

I would add the `TaintPropagation` checker to the `optin` package as an optional security analysis checker which is not enabled by default, because its usage is very application area dependent. Some of the security concious applications would want to create the config file for their sources and sinks and even mark a few FPs, if they can catch a few vulnerabilities.

Does this approach sound acceptable to you?
From which project did you see the ~300 false reports?

**Review by steakhal — COMMENTED** [review]
I tried to look at the mentioned 3 TPs, but the links appear to be broken.

Contentwise, I assume its a pure cut-and-paste modulo replacement of `alpha` to `optin`.
I have no objection from moving this checker out of alpha.

**Comment by dkrupp** [comment]
@steakhal now the commit is rebased and the results in the description are also refreshed (not broken).

All the earlier problematic reports related to tainted integers (memset, malloc, memcpy ...) are not present now as these were removed from this checker as generic sinks by earlier commits.

Your suggested doc fixes also added.

**Comment by steakhal** [comment]
I'm good now with the change, but I want both @Xazax-hun and @haoNoQ to accept this PR before landing.

**Review by NagyDonat — COMMENTED** [review]
Looks good to me.

When you're merging the commit, please remove the second half of the PR description ("Reports from ..." and everything after it). For the review it's good that the links to the results are highlighted at that prominent location, but we shouldn't permanently burn this information into the git commit log.

**Comment by Xazax-hun** [comment]
I have no concerns with moving forward here, my understanding is that the blockers have been resolved. Moreover, we are early in the development cycle for the next release so we still have a lot of time to get more experience with this check once it is move out of alpha. But I'd also wait for Artem to greenlight this.

**Comment by dkrupp** [comment]
@haoNoQ gentle ping. Could you please check if this would be good to be merged now? thanks.

**Pull request merged**
