### PR TITLE
[flang][driver] Don't use -whole-archive on Darwin

### PR DESCRIPTION
**Pull request by banach-space**
Direct follow-up of #73124 - the linker on Darwin does not support
`-whole-archive`, so that needs to be removed from the linker
invocation.

For context:
  * https://github.com/llvm/llvm-project/pull/73124

### CODE REVIEW

**Review by luporl — APPROVED** [review]
LGTM. Worked fine on my machine.

NOTE: tested by replacing `CommonArgs.cpp` in main, to avoid conflicts.

**Comment by banach-space** [comment]
> LGTM. Worked fine on my machine.
> 
> NOTE: tested by replacing `CommonArgs.cpp` in main, to avoid conflicts.

Thanks for checking and apologies for the merge conflict - I thought that I was up to date :( I've just rebased and force-pushed. 

I will be landing this today if there are no further comments 🙏🏻

**Comment by mjklemm** [comment]
> > LGTM. Worked fine on my machine.
> 
> > 
> 
> > NOTE: tested by replacing `CommonArgs.cpp` in main, to avoid conflicts.
> 
> 
> 
> Thanks for checking and apologies for the merge conflict - I thought that I was up to date :( I've just rebased and force-pushed. 
> 
> 
> 
> I will be landing this today if there are no further comments 🙏🏻 

This patch seems to hide the original problem of the compiler not erroring out when multiple definitions of main happen.  T think we should rather inject the proper linker equivalent of --whole-archive on Darwin, too.

I'd be OK to land this patch for now, if we agree to have a follow up PR to (re-)instantiate the error handling also for Darwin.

**Comment by banach-space** [comment]
> > > LGTM. Worked fine on my machine.
> > 
> > 
> > > 
> > 
> > 
> > > NOTE: tested by replacing `CommonArgs.cpp` in main, to avoid conflicts.
> > 
> > 
> > Thanks for checking and apologies for the merge conflict - I thought that I was up to date :( I've just rebased and force-pushed.
> > I will be landing this today if there are no further comments 🙏🏻
> 
> This patch seems to hide the original problem of the compiler not erroring out when multiple definitions of main happen.

To clarify - this patch is a warkaround to avoid reverting https://github.com/llvm/llvm-project/pull/73124. And to buy ourselves some time. I did a bit of research and couldn't find any equivalents for Darwin for `-whole-archive` :( I am a bit concerned that this might be the only option TBH, but hopefully I am wrong.

> I'd be OK to land this patch for now, if we agree to have a follow up PR to (re-)instantiate the error handling also for Darwin.

That would be ideal, but I won't have the bandwidth for that. We'll need a volunteer. Another option is to revert #73124. Either way, we need to unblock our Darwin users ASAP :)

**Comment by luporl** [comment]
I've run `flang/test/Driver/no-duplicate-main.f90` manually on Darwin and noticed that the third RUN line fails, because no error happens:
`! RUN: not %flang -o %t.exe %t %t.c-object 2>&1`

So maybe `-whole-archive` is just not needed on it?

**Comment by kkwli** [comment]
I build and `check-flang` on `arm64-apple-darwin22.6.0`. `Driver/no-duplicate-main.f90` fails in the 3rd RUN. The test passes with HEAD.

```
kelvin@neutrino2 build % /Users/kelvin/wrk/llvm/tmp/build/bin/flang-new -o /Users/kelvin/wrk/llvm/tmp/build/tools/flang/test/Driver/Output/no-duplicate-main.f90.tmp.exe /Users/kelvin/wrk/llvm/tmp/build/tools/flang/test/Driver/Output/no-duplicate-main.f90.tmp /Users/kelvin/wrk/llvm/tmp/build/tools/flang/test/Driver/Output/no-duplicate-main.f90.tmp.c-object

kelvin@neutrino2 build % echo $?
0
```

**Comment by JasonWoodArm** [comment]
I tested this with our build on Mac and we are working again so it fixed the issue we were having. Thanks.

**Comment by mjklemm** [comment]
Let's get this in. I agree with the assessment by @banach-space. The PR looks good to me.

**Comment by luporl** [comment]
> I build and `check-flang` on `arm64-apple-darwin22.6.0`. `Driver/no-duplicate-main.f90` fails in the 3rd RUN. The test passes with HEAD.
> 
> ```
> kelvin@neutrino2 build % /Users/kelvin/wrk/llvm/tmp/build/bin/flang-new -o /Users/kelvin/wrk/llvm/tmp/build/tools/flang/test/Driver/Output/no-duplicate-main.f90.tmp.exe /Users/kelvin/wrk/llvm/tmp/build/tools/flang/test/Driver/Output/no-duplicate-main.f90.tmp /Users/kelvin/wrk/llvm/tmp/build/tools/flang/test/Driver/Output/no-duplicate-main.f90.tmp.c-object
> 
> kelvin@neutrino2 build % echo $?
> 0
> ```

Unrelated to this PR, but may I ask how do you configure flang, to make it link without errors and without extra flags?
I need to add `-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib`.

**Comment by banach-space** [comment]
> Unrelated to this PR, but may I ask how do you configure flang, to make it link without errors and without extra flags? I need to add `-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib`.

AFAIK, what you really want is this: `-isysroot $(xcrun --sdk-path)`. Today this happens to be:
*  `-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib`.

But there's no guarantee that this won't change in the future. Now, one should be able to "fix it" within one build of Clang with [DEFAULT_SYSROOT][(url](https://github.com/llvm/llvm-project/blob/c64334fb30f8a8087c218b6d7ec954ad47b33947/clang/CMakeLists.txt#L177-L178)). If that works for you - could you document in the Flang docs? 🙏🏻

**Comment by kkwli** [comment]
> > I build and `check-flang` on `arm64-apple-darwin22.6.0`. `Driver/no-duplicate-main.f90` fails in the 3rd RUN. The test passes with HEAD.
> > ```
> > kelvin@neutrino2 build % /Users/kelvin/wrk/llvm/tmp/build/bin/flang-new -o /Users/kelvin/wrk/llvm/tmp/build/tools/flang/test/Driver/Output/no-duplicate-main.f90.tmp.exe /Users/kelvin/wrk/llvm/tmp/build/tools/flang/test/Driver/Output/no-duplicate-main.f90.tmp /Users/kelvin/wrk/llvm/tmp/build/tools/flang/test/Driver/Output/no-duplicate-main.f90.tmp.c-object
> > 
> > kelvin@neutrino2 build % echo $?
> > 0
> > ```
> 
> Unrelated to this PR, but may I ask how do you configure flang, to make it link without errors and without extra flags? I need to add `-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib`.

I do not have any special configure. Here is my `cmake` command:
```
cmake -G "Unix Makefiles" -DCMAKE_BUILD_TYPE=Release $HOME/wrk/llvm/tmp/llvm-project/llvm \
  -DCMAKE_INSTALL_PREFIX=$HOME/wrk/llvm/tmp/llvm-install -DLLVM_TARGETS_TO_BUILD="AArch64" \
  -DCMAKE_OSX_ARCHITECTURES="arm64" -DLLVM_ENABLE_PROJECTS="clang;flang;mlir" \
  -DLLVM_ENABLE_RUNTIMES="openmp;compiler-rt" -DDEFAULT_SYSROOT="$(xcrun --show-sdk-path)" \
  -DCMAKE_CXX_COMPILER=$HOME/wrk/llvm/17.0.4/bin/clang++ \
  -DCMAKE_C_COMPILER=$HOME/wrk/llvm/17.0.4/bin/clang \
  -DBUILTINS_CMAKE_ARGS=-DCOMPILER_RT_ENABLE_IOS=OFF \
  -DLLVM_LIT_ARGS="--threads=8 -v --show-unsupported"
```

**Comment by kkwli** [comment]
> > Unrelated to this PR, but may I ask how do you configure flang, to make it link without errors and without extra flags? I need to add `-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib`.
> 
> AFAIK, what you really want is this: `-isysroot $(xcrun --sdk-path)`. Today this happens to be:
> 
>     * `-L/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/usr/lib`.
> 
> 
> But there's no guarantee that this won't change in the future. Now, one should be able to "fix it" within one build of Clang with [DEFAULT_SYSROOT](https://github.com/llvm/llvm-project/blob/c64334fb30f8a8087c218b6d7ec954ad47b33947/clang/CMakeLists.txt#L177-L178). If that works for you - could you document in the Flang docs? 🙏🏻

I already have `-DDEFAULT_SYSROOT="$(xcrun --show-sdk-path)"` in my cmake command.

**Comment by luporl** [comment]
Ok, thanks, I'll try with `-DDEFAULT_SYSROOT="$(xcrun --show-sdk-path)"`.

But it's good to know that using `-isysroot` with flang is the right solution. I'll try to come up with a patch to make flang support it, when I have some spare time.

**Pull request merged**
