### PR TITLE
[CI] Refactor common functionality into separate script

### PR DESCRIPTION
**Pull request by boomanaiden154**
This patch refactors some common functionality present in the CI scripts to a separate shell script. This is mainly intended to make it easier to reuse this functionality inside of a Github Actions pipeline as we make the switch.

### CODE REVIEW

**Comment by boomanaiden154** [comment]
This is mainly to enable setting up Github Actions Workflows using the existing CI scripts (like https://github.com/llvm/llvm-project/pull/119635).

**Review by DavidSpickett — APPROVED** [review]
Seems like a simple move, nothing controversial.

Any big changes to the code are best done when the new system is stable anyway.

**Review by Endilll — APPROVED** [review]
I wish those scripts were written in Python. But alas, not in the scope of this PR.

**Comment by boomanaiden154** [comment]
> Any big changes to the code are best done when the new system is stable anyway.

Agreed. I'm trying to bring up the new system with minimal changes to the existing setup and then we can iterate from there once that is stable and we deprecate the old system.

> I wish those scripts were written in Python. But alas, not in the scope of this PR.

Yeah, I'm not the biggest fan of bash scripts. Something easier to write unit/regression tests against would be particularly nice. We'll have to make some decently big changes once the new system is stable to better take advantage of Github Actions, so I expect some migration to take place with that work.

**Pull request merged**
