### PR TITLE
[X86] [NFC] Prefer isa_and_nonnull

### PR DESCRIPTION
**Pull request by AZero13**

### CODE REVIEW

**Review by phoebewang — APPROVED** [review]
LGTM.

**Comment by AtariDreams** [comment]
@phoebewang Can we please merge this?

**Comment by AtariDreams** [comment]
@topperc Can we please merge this?

**Review by nikic — COMMENTED** [review]
Should we really prefer this? The old form is shorter and no less clear.

(Relatedly: Should those isa checks be there at all? Is this intentionally excluding invokes?)

**Comment by AtariDreams** [comment]
> Should we really prefer this? The old form is shorter and no less clear.
> 
> 
> 
> (Relatedly: Should those isa checks be there at all? Is this intentionally excluding invokes?)

Can I ask what's the point of isa_nonnull then?

**Pull request closed without merging**
