### PR TITLE
[mlir][polly][llvm-lit] Fixed logic for turning on external shell in lit

### LINKED ISSUE #106459: [mlir][polly][llvm-lit] External shell unable to be turned on for lit tests
In both mlir and polly, tests are run with lit's internal shell by default. In order to use the external shell instead, the `LIT_USE_INTERNAL_SHELL` environment variable should be set to 0. The logic in the lit configs of these test suites prevents the external shell from being turned on.

Code:
```
use_lit_shell = True
lit_shell_env = os.environ.get("LIT_USE_INTERNAL_SHELL")
if lit_shell_env:
	use_lit_shell = not lit.util.pythonize_bool(lit_shell_env)

config.test_format = lit.formats.ShTest(execute_external=not use_lit_shell)
```

The problem lies in the body of the if statement, with the use of `not`.

### PR DESCRIPTION
**Pull request by connieyzhu**
For both mlir and polly, the lit internal shell is the default shell for running lit tests. However, if the user wanted to switch back to the external shell by setting `LIT_USE_INTERNAL_SHELL=0`, the `not` used in the body of the `if` conditional changes `use_lit_shell` to be True instead of the intended False. Removing `not` allows for this lit config to work as intended.

Fixes https://github.com/llvm/llvm-project/issues/106459.

### CODE REVIEW

**Review by boomanaiden154 — APPROVED** [review]
LGTM.

It seems like the two instances in `polly` were copied from the MLIR one and the MLIR version was inverted for whatever reason?

Given this seems to impact all the test suites where the internal shell is getting enabled, is it possible/a good idea to move the use of the environment variable to within lit (maybe as a follow up)?

**Comment by ilovepi** [comment]
The current RFC and plans are to incrementally adopt the internal shell as the default. The main lit config in llvm handles this correctly, but there is usually some special handling for Windows duplicated across the various subprojects. MLIR already had set it’s default for the internal shell, but this is rare for any of the subprojects to do outside of Windows. Polly had no tests with either non-portable syntax or REQUIRES: shell, so it wasn’t noticed that it didn’t work as intended when we adopted/copied the MLIR implementation. 

I’m not sure there’s a good way to share the implementation settings between subprojects without using the same settings for all of them. Using the shared implementation may need to wait until we’re ready to switch them all.

**Comment by boomanaiden154** [comment]
> I’m not sure there’s a good way to share the implementation settings between subprojects without using the same settings for all of them. Using the shared implementation may need to wait until we’re ready to switch them all.

Ack. Maybe some TODOs so it's more likely to get picked up in the future?

**Comment by ilovepi** [comment]
Yeah that’s likely the best idea. Or at least a tracking issue.

**Comment by connieyzhu** [comment]
> Yeah that’s likely the best idea. Or at least a tracking issue.

@boomanaiden154 @ilovepi I added TODOs in my most recent commit and created an [issue](https://github.com/llvm/llvm-project/issues/106636) for this.

**Review by ilovepi — APPROVED** [review]
Thanks for filing the issue. LGTM.

**Pull request merged**
