### PR TITLE
Reapply [APInt] Enable APInt ctor assertion by default

### PR DESCRIPTION
**Pull request by nikic**
This enables the assertion introduced in https://github.com/llvm/llvm-project/pull/106524, which checks that the value passed to the constructor is indeed a valid N-bit signed or unsigned integer.

Places that previously violated the assertion were updated in advance, e.g. in https://github.com/llvm/llvm-project/pull/80309.

It is possible to opt-out of the check and restore the previous behavior by setting implicitTrunc=true.

-----

The buildbot failures from the previous attempt should be fixed by a18dd29077c84fc076a4ed431d9e815a3d0b6f24 and
e2074c60bb3982cd8afb6408670332ea27da6383.

### CODE REVIEW

**Comment by nathanchance** [comment]
I am seeing an assertion failure while building the Linux kernel after this change. `cvise` spits out as a trivial reproducer:

```c
int am33xx_check_features___trans_tmp_5;
int omap_rev();
void __attribute__((__cold__)) am33xx_check_features() {
  am33xx_check_features___trans_tmp_5 = omap_rev() >> 20 == 363;
}
```

```
$ clang --target=arm-linux-gnueabi -O2 -c -o /dev/null id.i
clang: /home/nathan/tmp/cvise.iMmMYHOwp2/src/llvm/include/llvm/ADT/APInt.h:121: llvm::APInt::APInt(unsigned int, uint64_t, bool, bool): Assertion `llvm::isIntN(BitWidth, val) && "Value is not an N-bit signed value"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace, preprocessed source, and associated run script.
Stack dump:
0.      Program arguments: clang --target=arm-linux-gnueabi -O2 -c -o /dev/null id.i
1.      <eof> parser at end of file
2.      Code generation
3.      Running pass 'Function Pass Manager' on module 'id.i'.
4.      Running pass 'Constant Hoisting' on function '@am33xx_check_features'
...
```

If a separate issue would be helpful, I am happy to file one.

**Comment by nikic** [comment]
@nathanchance Thanks for the report! Here's a minimized test case:
```llvm
; RUN: opt -S -passes=consthoist < %s
target triple = "armv4t-unknown-linux-gnueabi"

define i1 @test(i32 %arg) optsize {
entry:
  %shr.mask = and i32 %arg, -1048576
  %cmp = icmp eq i32 %shr.mask, 380633088
  ret i1 %cmp
}   
```

**Comment by nikic** [comment]
@nathanchance I've applied a fix in https://github.com/llvm/llvm-project/commit/8851ea64a5d01fbf406383f13fcba347e730bc2d. Let me know if you see further issues.

**Comment by mikaelholmen** [comment]
Hi @nikic ,

Another crash like this:
 https://godbolt.org/z/57chn4aqP

**Comment by nikic** [comment]
@mikaelholmen Thanks, should be fixed by https://github.com/llvm/llvm-project/commit/46ccefb1236bf29b2d752715373d407f2d4c3d61.

**Comment by mikaelholmen** [comment]
Another one here:
```opt -passes=instcombine bbi-101454.ll -S -o /dev/null```
results in
```
opt: ../include/llvm/ADT/APInt.h:128: llvm::APInt::APInt(unsigned int, uint64_t, bool, bool): Assertion `llvm::isUIntN(BitWidth, val) && "Value is not an N-bit unsigned value"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: build-all/bin/opt -passes=instcombine bbi-101454.ll -S -o /dev/null
1.	Running pass "function(instcombine<max-iterations=1;verify-fixpoint>)" on module "bbi-101454.ll"
2.	Running pass "instcombine<max-iterations=1;verify-fixpoint>" on function "f_434_1400"
 #0 0x000055a682c8a778 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (build-all/bin/opt+0x4444778)
 #1 0x000055a682c8823e llvm::sys::RunSignalHandlers() (build-all/bin/opt+0x444223e)
 #2 0x000055a682c8afad SignalHandler(int) Signals.cpp:0:0
 #3 0x00007f622ac1dcf0 __restore_rt (/lib64/libpthread.so.0+0x12cf0)
 #4 0x00007f62287d6acf raise (/lib64/libc.so.6+0x4eacf)
 #5 0x00007f62287a9ea5 abort (/lib64/libc.so.6+0x21ea5)
 #6 0x00007f62287a9d79 _nl_load_domain.cold.0 (/lib64/libc.so.6+0x21d79)
 #7 0x00007f62287cf426 (/lib64/libc.so.6+0x47426)
 #8 0x000055a6839925cc llvm::InstCombinerImpl::canonicalizeCondSignextOfHighBitExtractToSignextHighBitExtract(llvm::BinaryOperator&) InstCombineAddSub.cpp:0:0
 #9 0x000055a683993d90 llvm::InstCombinerImpl::visitAdd(llvm::BinaryOperator&) InstCombineAddSub.cpp:0:0
#10 0x000055a6838e6f1a llvm::InstCombinerImpl::run() InstructionCombining.cpp:0:0
#11 0x000055a6838ea7bd combineInstructionsOverFunction(llvm::Function&, llvm::InstructionWorklist&, llvm::AAResults*, llvm::AssumptionCache&, llvm::TargetLibraryInfo&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::OptimizationRemarkEmitter&, llvm::BlockFrequencyInfo*, llvm::BranchProbabilityInfo*, llvm::ProfileSummaryInfo*, llvm::InstCombineOptions const&) InstructionCombining.cpp:0:0
#12 0x000055a6838e9b36 llvm::InstCombinePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build-all/bin/opt+0x50a3b36)
#13 0x000055a684042a3d llvm::detail::PassModel<llvm::Function, llvm::InstCombinePass, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) PassBuilderPipelines.cpp:0:0
#14 0x000055a682e93307 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build-all/bin/opt+0x464d307)
#15 0x000055a68404877d llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) PassBuilderPipelines.cpp:0:0
#16 0x000055a682e97e96 llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (build-all/bin/opt+0x4651e96)
#17 0x000055a68404221d llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) PassBuilderPipelines.cpp:0:0
#18 0x000055a682e92037 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (build-all/bin/opt+0x464c037)
#19 0x000055a683fe6373 llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::ArrayRef<std::function<void (llvm::PassBuilder&)>>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool, bool) (build-all/bin/opt+0x57a0373)
#20 0x000055a682c51b4a optMain (build-all/bin/opt+0x440bb4a)
#21 0x00007f62287c2d85 __libc_start_main (/lib64/libc.so.6+0x3ad85)
#22 0x000055a682c4b96e _start (build-all/bin/opt+0x440596e)
Abort (core dumped)
```
[bbi-101454.ll.gz](https://github.com/user-attachments/files/17816203/bbi-101454.ll.gz)

**Comment by nikic** [comment]
@mikaelholmen Thanks, should be fixed by https://github.com/llvm/llvm-project/commit/abac5be673a2053cceab8ce25009722e45021b9f.

**Comment by mikaelholmen** [comment]
Yep, thanks!

**Comment by mikaelholmen** [comment]
Hi @nikic ,

Another failure like this:
```opt -passes instcombine bbi-102622.ll -o /dev/null```
Result:
```
opt: ../include/llvm/ADT/APInt.h:121: llvm::APInt::APInt(unsigned int, uint64_t, bool, bool): Assertion `llvm::isIntN(BitWidth, val) && "Value is not an N-bit signed value"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: build-all/bin/opt -passes instcombine bbi-102622.ll -o /dev/null
1.	Running pass "function(instcombine<max-iterations=1;verify-fixpoint>)" on module "bbi-102622.ll"
2.	Running pass "instcombine<max-iterations=1;verify-fixpoint>" on function "test_max_1"
 #0 0x0000564c1b952046 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (build-all/bin/opt+0x448b046)
 #1 0x0000564c1b94fa8e llvm::sys::RunSignalHandlers() (build-all/bin/opt+0x4488a8e)
 #2 0x0000564c1b9528f9 SignalHandler(int) Signals.cpp:0:0
 #3 0x00007fd7d9e41cf0 __restore_rt (/lib64/libpthread.so.0+0x12cf0)
 #4 0x00007fd7d77f2acf raise (/lib64/libc.so.6+0x4eacf)
 #5 0x00007fd7d77c5ea5 abort (/lib64/libc.so.6+0x21ea5)
 #6 0x00007fd7d77c5d79 _nl_load_domain.cold.0 (/lib64/libc.so.6+0x21d79)
 #7 0x00007fd7d77eb426 (/lib64/libc.so.6+0x47426)
 #8 0x0000564c1c680f7b (build-all/bin/opt+0x51b9f7b)
 #9 0x0000564c1c67e98b llvm::InstCombinerImpl::foldICmpAddConstant(llvm::ICmpInst&, llvm::BinaryOperator*, llvm::APInt const&) InstCombineCompares.cpp:0:0
#10 0x0000564c1c6828cc llvm::InstCombinerImpl::foldICmpBinOpWithConstant(llvm::ICmpInst&, llvm::BinaryOperator*, llvm::APInt const&) InstCombineCompares.cpp:0:0
#11 0x0000564c1c6824c8 llvm::InstCombinerImpl::foldICmpInstWithConstant(llvm::ICmpInst&) InstCombineCompares.cpp:0:0
#12 0x0000564c1c692d2e llvm::InstCombinerImpl::visitICmpInst(llvm::ICmpInst&) InstCombineCompares.cpp:0:0
#13 0x0000564c1c5fa12b llvm::InstCombinerImpl::run() InstructionCombining.cpp:0:0
#14 0x0000564c1c5fd9fd combineInstructionsOverFunction(llvm::Function&, llvm::InstructionWorklist&, llvm::AAResults*, llvm::AssumptionCache&, llvm::TargetLibraryInfo&, llvm::TargetTransformInfo&, llvm::DominatorTree&, llvm::OptimizationRemarkEmitter&, llvm::BlockFrequencyInfo*, llvm::BranchProbabilityInfo*, llvm::ProfileSummaryInfo*, llvm::InstCombineOptions const&) InstructionCombining.cpp:0:0
#15 0x0000564c1c5fcd7a llvm::InstCombinePass::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build-all/bin/opt+0x5135d7a)
#16 0x0000564c1cda10ed llvm::detail::PassModel<llvm::Function, llvm::InstCombinePass, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) PassBuilderPipelines.cpp:0:0
#17 0x0000564c1bb71957 llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) (build-all/bin/opt+0x46aa957)
#18 0x0000564c1cda8b7d llvm::detail::PassModel<llvm::Function, llvm::PassManager<llvm::Function, llvm::AnalysisManager<llvm::Function>>, llvm::AnalysisManager<llvm::Function>>::run(llvm::Function&, llvm::AnalysisManager<llvm::Function>&) PassBuilderPipelines.cpp:0:0
#19 0x0000564c1bb7652e llvm::ModuleToFunctionPassAdaptor::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (build-all/bin/opt+0x46af52e)
#20 0x0000564c1cda064d llvm::detail::PassModel<llvm::Module, llvm::ModuleToFunctionPassAdaptor, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) PassBuilderPipelines.cpp:0:0
#21 0x0000564c1bb70647 llvm::PassManager<llvm::Module, llvm::AnalysisManager<llvm::Module>>::run(llvm::Module&, llvm::AnalysisManager<llvm::Module>&) (build-all/bin/opt+0x46a9647)
#22 0x0000564c1cd28bbc llvm::runPassPipeline(llvm::StringRef, llvm::Module&, llvm::TargetMachine*, llvm::TargetLibraryInfoImpl*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::ToolOutputFile*, llvm::StringRef, llvm::ArrayRef<llvm::PassPlugin>, llvm::ArrayRef<std::function<void (llvm::PassBuilder&)>>, llvm::opt_tool::OutputKind, llvm::opt_tool::VerifierKind, bool, bool, bool, bool, bool, bool, bool) (build-all/bin/opt+0x5861bbc)
#23 0x0000564c1b914c90 optMain (build-all/bin/opt+0x444dc90)
#24 0x00007fd7d77ded85 __libc_start_main (/lib64/libc.so.6+0x3ad85)
#25 0x0000564c1b9128ae _start (build-all/bin/opt+0x444b8ae)
Abort (core dumped)
```
It fails on this in InstCombinerImpl::foldICmpAddConstant:
```
    auto ComputeTable = [&](bool Op0Val, bool Op1Val) {
      int Res = 0;
      if (Op0Val)
        Res += isa<ZExtInst>(Ext0) ? 1 : -1;
      if (Op1Val)
        Res += isa<ZExtInst>(Ext1) ? 1 : -1;
      return ICmpInst::compare(APInt(BW, Res, true), C, Pred);
    };
```
[bbi-102622.ll.gz](https://github.com/user-attachments/files/18330636/bbi-102622.ll.gz)

**Comment by nikic** [comment]
@mikaelholmen Thanks, should be fixed by https://github.com/llvm/llvm-project/commit/63d4e0fb66b75dd1c60acaa81ff8f8a4327cffcc.

**Comment by mikaelholmen** [comment]
> @mikaelholmen Thanks, should be fixed by [63d4e0f](https://github.com/llvm/llvm-project/commit/63d4e0fb66b75dd1c60acaa81ff8f8a4327cffcc).

Yep, thanks!

**Pull request merged**
