### PR TITLE
[ORC] Do not set CodeModel::Small in LLJITBuilder if JTMB already has a value (#88115)

### LINKED ISSUE #88115: [ORC] LLJITBuilder overwrite CodeModel setting from JTMB
I am doing something like this to configure a LLJIT object with it's code model set as `CodeModel::Large`.

```cpp
auto JTMBOrErr = orc::JITTargetMachineBuilder::detectHost();
if (JTMBOrErr)
    exit_on_err(JTMBOrErr.takeError());

auto JTMB = std::move(*JTMBOrErr);
JTMB.setCodeModel(CodeModel::Large);

// TODO find a way to setCodeModel(CodeModel::Large)
// because JTMB's code model is overwritten by create() function
jit = exit_on_err(orc::LLJITBuilder().setJITTargetMachineBuilder(JTMB).create());
```

As written in the comment, the code model is overwritten by `LLJITBuilder::create`. Digging in the code, we can see that `LLJITBuilder::create` call `LLJITBuilderState::prepareForConstruction`, which then set `CodeModel::Small` without looking at the setting in JTMB. See here  :
https://github.com/llvm/llvm-project/blob/040e0d4fa45f3606fb584c2923dd111cca675feb/llvm/lib/ExecutionEngine/Orc/LLJIT.cpp#L755-L757

I think there is no reason to force this setting.

### PR DESCRIPTION
**Pull request by epitavy**
Closes #88115

### CODE REVIEW

**Comment by epitavy** [comment]
@lhames

**Comment by epitavy** [comment]
ping @lhames

**Review by lhames — APPROVED** [review]
LGTM. Thanks very much @epitavy! (And apologies for the delay on the review)

**Comment by epitavy** [comment]
@lhames Can you merge the pull request ? I don't have permission to do it !

**Pull request merged**
