### PR TITLE
[XCOFF] Do not generate the special .ref for zero-length sections

### PR DESCRIPTION
**Pull request by w2yehia**

### CODE REVIEW

**Comment by w2yehia** [comment]
tests will be added soon.
@hubert-reinterpretcast @daltenty FYI

**Review by daltenty — COMMENTED** [review]
Is there any downside to loosing the refs in this case? (if there is maybe its better to pad the sections to make everything unambiguous?)

**Comment by w2yehia** [comment]
> Is there any downside to loosing the refs in this case? (if there is maybe its better to pad the sections to make everything unambiguous?)

The refs were added specifically for PGO instrumentation sections (counters, data, names, value profiling nodes), and PGO instrumentation will not create zero-length objects. The case where we have zero-length objects sitting in PGO sections is the dummy zero-length variables manually added to the PGO runtime [here](https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/profile/InstrProfilingPlatformAIX.c#L188). Not emitting the refs when compiling the PGO runtime source file will not impact functionality (as Hubert pointed out, offline, the `__llvm_profile_keep` array retains the dummy variables).

**Comment by daltenty** [comment]
Looks fine to me once we have some tests

**Comment by w2yehia** [comment]
@daltenty tests added

**Pull request merged**
