### PR TITLE
[LLVM][AArch64] Add ASM constraints for reduced GPR register ranges.

### PR DESCRIPTION
**Pull request by paulwalker-arm**
[LLVM][AArch64] Add ASM constraints for reduced GPR register ranges.
    
The patch adds the follow ASM constraints:
  Uci => w8-w11/x8-x11
  Ucj => w12-w15/x12-x15
    
These constraints are required for SME load/store instructions
where a reduced set of GPRs are used to specify ZA array vectors.
    
NOTE: GCC has agreed to use the same constraint syntax.

### CODE REVIEW

**Comment by paulwalker-arm** [comment]
The first commit contains refactoring that I'll land separately assuming the reviewers are happy.  The new functionality is implemented by the second commit.

**Comment by peterwaller-arm** [comment]
Worth a simultaneous update to the langref?

https://github.com/llvm/llvm-project/blob/e2564b27472638d2e2019e6cd2fc6d6d608f8b8c/llvm/docs/LangRef.rst#L5080-L5106

**Comment by paulwalker-arm** [comment]
* Rebased.
* Extended coverage to include all typical scalar types.
* Updated the LangRef to document the new constraints.
* Added an entry to the release note.

**Review by peterwaller-arm — APPROVED** [review]

**Review by jroelofs — APPROVED** [review]
LGTM

**Comment by paulwalker-arm** [comment]
Rebased after pushing NFC refactoring commit.

**Pull request merged**
