### PR TITLE
[MC][Mips] Add MipsWinCOFFObjectWriter/MipsWinCOFFStreamer

### PR DESCRIPTION
**Pull request by hpoussin**
llc is now able to create MIPS COFF files for simple cases.

### CODE REVIEW

**Comment by hpoussin** [comment]
This is an extract of PR https://github.com/llvm/llvm-project/pull/107744

**Comment by hpoussin** [comment]
Depends of PR #114678 to prevent some failures in unit tests

**Comment by hpoussin** [comment]
Ping. Maybe @FlyGoat or @wzssyqa ?

**Comment by hpoussin** [comment]
Ping.

**Comment by hpoussin** [comment]
Ping.

**Comment by hpoussin** [comment]
Ping.

**Comment by hpoussin** [comment]
Ping @brad0, @yingopq, @wzssyqa, @mstorsjo

**Comment by yingopq** [comment]
LGTM.

**Comment by hpoussin** [comment]
Rebasing due to commits ae26f50aea4ef1a6c7058019f0db11a91bbcdade and 806761a7629df268c8aed49657aeccffa6bca449

**Pull request merged**
