### PR TITLE
[flang] Fix missing CGPasses.h.inc

### LINKED ISSUE #57680: CGPasses.h.inc No such file (15.0.0 flang)
Looks the same as #54128

Centos7.9, gcc 11.3.0

```shell
cmake                                                 \    
  -DCMAKE_C_COMPILER=${HOST_GCC}/bin/gcc                                         \
  -DCMAKE_CXX_COMPILER=${HOST_GCC}/bin/g++                                       \
  -DCMAKE_BUILD_TYPE="Release"                                                   \
  -DCMAKE_INSTALL_PREFIX=${INSTALL_PREFIX}                                       \
  -DLLVM_TARGETS_TO_BUILD="X86"                                                  \
  -DLLVM_ENABLE_PROJECTS="clang;clang-tools-extra;cross-project-tests;flang;libclc;lld;lldb;mlir;openmp;polly;pstl" \
  -DLLVM_ENABLE_RUNTIMES="compiler-rt;libc;libcxx;libcxxabi;libunwind" \
  -DGCC_INSTALL_PREFIX=${HOST_GCC}                                               \
  -DCMAKE_CXX_LINK_FLAGS="-L${HOST_GCC}/lib64 -Wl,-rpath,${HOST_GCC}/lib64"      \
  ../llvm
```
Terminates with error:
```console
.
.
.
[ 89%] Building CXX object tools/flang/lib/Frontend/CMakeFiles/obj.flangFrontend.dir/FrontendActions.cpp.o
In file included from /scr/llvm-project-15.0.0.src/flang/include/flang/Tools/CLOptions.inc:16,
                 from /src/llvm-project-15.0.0.src/flang/lib/Frontend/FrontendActions.cpp:480:
/scr/llvm-project-15.0.0.src/flang/include/flang/Optimizer/CodeGen/CodeGen.h:72:10: fatal error: flang/Optimizer/CodeGen/CGPasses.h.inc: No such file or directory
   72 | #include "flang/Optimizer/CodeGen/CGPasses.h.inc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
gmake[2]: *** [tools/flang/lib/Frontend/CMakeFiles/obj.flangFrontend.dir/FrontendActions.cpp.o] Error 1
gmake[1]: *** [tools/flang/lib/Frontend/CMakeFiles/obj.flangFrontend.dir/all] Error 2
gmake: *** [all] Error 2
```
I see (but don't really understand) in `/scr//llvm-project-15.0.0.src/flang/include/flang/Optimizer/CodeGen/CMakeLists.txt`:
```cmake
set(LLVM_TARGET_DEFINITIONS CGPasses.td)
mlir_tablegen(CGPasses.h.inc -gen-pass-decls -name OptCodeGen)
add_public_tablegen_target(FIROptCodeGenPassIncGen)
```

which looks to result in `/scr/llvm-project-15.0.0.src/build/tablegen_compile_commands.yml`:
```console
--- !FileInfo:
  filepath: "/scr/llvm-project-15.0.0.src/flang/include/flang/Optimizer/CodeGen/CGPasses.td"
  includes: "/scr/llvm-project-15.0.0.src/flang/include/flang/Optimizer/CodeGen;/scr/llvm-project-15.0.0.src/flang/include;/scr/llvm-project-15.0.0.src/build/tools/flang/include;/scr/llvm-project-15.0.0.src/build/include;/scr/llvm-project-15.0.0.src/llvm/include;/scr/llvm-project-15.0.0.src/llvm/../mlir/include;/scr/llvm-project-15.0.0.src/build/tools/mlir/include;/scr/llvm-project-15.0.0.src/build/tools/clang/include;/scr/llvm-project-15.0.0.src/llvm/../clang/include"
```
but beyone that I lose the trail...

I didn't have this problem with 13.0.1 nor 14.0.5

### LINKED ISSUE #61543: CGPasses.h.inc No such file (16.0.0 flang)
Still an issue from #54128, #57680?

```console
  .
  .
  .
[ 90%] Building CXX object tools/flang/lib/Frontend/CMakeFiles/obj.flangFrontend.dir/CodeGenOptions.cpp.o
[ 90%] Building CXX object tools/flang/lib/Frontend/CMakeFiles/obj.flangFrontend.dir/FrontendAction.cpp.o
[ 90%] Building CXX object tools/flang/lib/Frontend/CMakeFiles/obj.flangFrontend.dir/FrontendActions.cpp.o
In file included from /scratch/llvm-project-16.0.0.src/flang/include/flang/Tools/CLOptions.inc:16,
                 from /scratch/llvm-project-16.0.0.src/flang/lib/Frontend/FrontendActions.cpp:508:
/scratch/llvm-project-16.0.0.src/flang/include/flang/Optimizer/CodeGen/CodeGen.h:27:10: fatal error: flang/Optimizer/CodeGen/CGPasses.h.inc: No such file or directory
   27 | #include "flang/Optimizer/CodeGen/CGPasses.h.inc"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
```

### PR DESCRIPTION
**Pull request by jschueller**
I could reproduce using unix makefiles with -j1 option, with version 16.0.6
Closes #61543
Closes #57680

### CODE REVIEW

**Comment by jschueller** [comment]
cc @schweitzpgi @banach-space @CarolineConcatto

**Review by tblah — APPROVED** [review]
Looks good to me! Thanks for this

**Comment by ncihnegn** [comment]
Should be merged.

**Comment by jschueller** [comment]
ping @schweitzpgi @banach-space @CarolineConcatto

**Review by jeanPerier — APPROVED** [review]
Thank you

**Comment by jschueller** [comment]
ping @schweitzpgi @banach-space @CarolineConcatto @jeanPerier

**Comment by banach-space** [comment]
> ping @schweitzpgi @banach-space @CarolineConcatto @jeanPerier

This has been approved by 2 reviewers - please just land it :) 

The change makes sense to me, but I've lost track of the dependencies between CMake targets.

**Comment by jschueller** [comment]
@jeanPerier could you merge it ?

**Comment by jeanPerier** [comment]
> @jeanPerier could you merge it ?

I am not here next week, so I would rather not merge a patch and not watch the build bots, but I am happy to merge it when I am back if no else does.

**Pull request merged**
