### PR TITLE
[Kaleidoscope] LLVM is not needed for chapter two

### PR DESCRIPTION
**Pull request by gonsolo**
Since the example (llvm/examples/Kaleidoscope/Chapter2/toy.cpp) is self-contained there is no need to use LLVM.

### CODE REVIEW

**Review by llvm-beanz — APPROVED** [review]

**Comment by gonsolo** [comment]
Adding commiters to doc/tutorial since LLVM 17 to get this merged:
@Logikable @aemerson @aeubanks @MaskRay @youkaichao @hanickadot

**Comment by youkaichao** [comment]
Hey, anything required from my side?

**Review by MaskRay — APPROVED** [review]
This is correct. `llvm/examples/Kaleidoscope/Chapter2/toy.cpp` doesn't use LLVM.

**Comment by gonsolo** [comment]
> Hey, anything required from my side?

No, @MaskRay was kind enough to merge this PR. I was just pinging all recent committers of this directory to get this merged.

**Comment by gonsolo** [comment]
Thanks, @MaskRay.

**Pull request merged**
