### PR TITLE
[BOLT] Fix mustSkip when symbol's name changed by BOLT

### PR DESCRIPTION
**Pull request by lifengxiang1025**

### CODE REVIEW

**Comment by lifengxiang1025** [comment]
When I use the flag `--skip-funcs-file`, I found it doesn't work. After debugging, i found symbol's name changed as foo/1 before running `mustSkip`.

**Comment by aaupov** [comment]
That's intentional and is required to disambiguate local symbols. You can either append the suffix ("/1" in this case) or `.*` regex if you want to skip all aliases

**Comment by lifengxiang1025** [comment]
> That's intentional and is required to disambiguate local symbols. You can either append the suffix ("/1" in this case) or `.*` regex if you want to skip all aliases

Thanks. But i think it's not friendly to BOLT users. The command description doesn't mention the suffix. It need users to find the reason for unexpected result by themself.

**Comment by maksfb** [comment]
IMHO, it's reasonable for BOLT to accept a local name without a prefix if we didn't match any global name and there's no ambiguity in local name matching.

**Pull request closed without merging**
