### PR TITLE
Make diagnostic pragma override -Werror=foo and DefaultError warnings

### LINKED ISSUE #93474: `#pragma GCC diagnostic warning "-Wimplicit-function-declaration"` fails at turning -Werror=implicit-function-declaration into to just a warning
`#pragma GCC diagnostic warning "-Wimplicit-function-declaration"` fails at turning -Werror=implicit-function-declaration into to just a warning.
It does make it warn as expected if `-Wimplicit-function-declaration` was previously `ignored`, but it won't make it go from error to warning.

Gcc works as expected. Clang not, since clang 15:

https://godbolt.org/z/qc7MKc75b

### PR DESCRIPTION
**Pull request by MaskRay**
In GCC, `#pragma GCC diagnostic warning "-Wfoo"` overrides command-line
`-Werror=foo` and errors that can become warnings (pedwarn with
-pedantic-errors and permerror).

```
#pragma GCC diagnostic warning "-Wnarrowing"
int x = {4.2};
#pragma GCC diagnostic warning "-Wundef"
#if FOO
#endif

// gcc -c -Werror=undef -Werror=narrowing => two warnings
```

These diagnostics are similar to our Warning/ExtWarn/Extension
diagnostics with DefaultError. This patch ports the behavior to Clang.

Fix #93474

### CODE REVIEW

**Review by AaronBallman — COMMENTED** [review]
Thank you for this! Please add a release note to clang/docs/ReleaseNotes.rst so users know about the behavioral change. Also, should we update some documentation as well?

**Review by AaronBallman — COMMENTED** [review]
Adding @jyknight because of our discussions on related behavior regarding `DefaultError` diagnostics and suppression.

**Comment by MaskRay** [comment]
Ping:)

(clang/docs/ReleaseNotes.rst has a conflict, which can be fixed after a rebase)

**Comment by AaronBallman** [comment]
I think we should update our documentation: https://github.com/llvm/llvm-project/blob/b01ac5137c28fa5e1b44a5d850cb7a6ace7d8799/clang/docs/UsersManual.rst?plain=1#L1186

Overall, this seems like a sensible improvement to me and the code changes LG.

**Comment by MaskRay** [comment]
> I think we should update our documentation:
> 
> https://github.com/llvm/llvm-project/blob/b01ac5137c28fa5e1b44a5d850cb7a6ace7d8799/clang/docs/UsersManual.rst?plain=1#L1186
> 
> Overall, this seems like a sensible improvement to me and the code changes LG.

Thx. Updated UserManual.rst

**Comment by MaskRay** [comment]
Ping:)

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Pull request merged**
