### PR TITLE
[LoopConstrainer] Apply loop gurads to check that loop bounds are safe

### PR DESCRIPTION
**Pull request by aleks-tmb**
Loop guards that apply to loop SCEV bounds allow IRCE for cases with compound loop bounds such as:

if (K > 0 && M > 0)
  for (i = 0; i < min(K, M); i++) {...}

if (K > 0 && M > 0)
  for (i = min(K, M); i >= 0; i--) {...}

Otherwise SCEV couldn't prove that loops have safe bounds in these cases.

### CODE REVIEW

**Comment by danilaml** [comment]
Is the huge IR increase in tests intentional/desired?

**Comment by nikic** [comment]
You should only use the applyLoopBounds() result to perform checks -- for expansion, you should use the original SCEV.

**Comment by aleks-tmb** [comment]
> You should only use the applyLoopBounds() result to perform checks -- for expansion, you should use the original SCEV.

Thanks, fixed

**Comment by aleks-tmb** [comment]
@nikic Hi, 
does the patch look good to you? I would like to integrate it

**Review by preames — APPROVED** [review]
LGTM

**Pull request merged**
