### PR TITLE
[Flang][OpenMP] Make boxed procedure pass aware of OpenMP private ops

### LINKED ISSUE #109727: [Flang][OpenMP] Compilation error when derived type with procedure pointer appears within private attribute
```
Version of flang-new : 20.0.0(675c748bb606d75a959481e6014299849cf3094c)/AArch64
```

When building [GAMESS](https://www.msg.chem.iastate.edu/gamess/index.html), the following error is detected.  
When `derived type` with `procedure pointer` appears within `private` attribute, a compilation-time error (`Lowering to LLVM IR failed`) occurs.  

A similar error occurs with `firstprivate` attribute.  
Compilation succeeds in the following case:
- Do not specify `-fopenmp` option.

The following are a self-made reproducer, Flang-new compilation result.

foo.F90:
```fortran
module m1
  type :: typ1
     procedure(), pointer, nopass :: p1  => null()
  end type typ1
contains
  subroutine sub2()
    type(typ1) :: t1
!$omp parallel private(t1)
!$omp end parallel
  end subroutine sub2
end module m1

program main
  use m1
  print *,'pass'
end program main
```

```
$ flang-new -c -fopenmp foo.F90
error: loc("/work/home/ohno/CT/test/fort/tp/reproducerJ/Metro/GAMESS/foo.F90":7:19): Invalid yielded value. Expected type: '!fir.ref<!fir.type<_QMm1Ttyp1{p1:!fir.boxproc<() -> ()>}>>', got: '!fir.ref<!fir.type<_QMm1Ttyp1UnboxProc{p1:() -> ()}>>'
error: Lowering to LLVM IR failed
error: loc("/work/home/ohno/CT/test/fort/tp/reproducerJ/Metro/GAMESS/foo.F90":1:1): LLVM Translation failed for operation: fir.global
error: failed to create the LLVM module
$
```

```
$ flang-new -c foo.F90
$ ls -al *.o
-rw-rw-r--. 1 ohno ohno 7784 Sep 20 15:27 foo.o
$
```

### PR DESCRIPTION
**Pull request by kiranchandramohan**
Fixes #109727

### CODE REVIEW

**Review by jeanPerier — COMMENTED** [review]
Thanks Kiran. I wonder if the generic fix is not to remove the "op->getDialect() == firDialect" in the case just above. I do not recall the rational of limiting it to fir ops. Most likely this was an early compiler-perf optimization that was based on the wrong assumption that such FIR type would only be returned by FIR ops, but I see no harm removing that limitation (the `needsConversion` lookup cost should be pretty limited for most non FIR operation result types).

The right thing would likely to be to have a real dialect conversion pass, but these are expensive, so it may be better to keep the current approach for now (the next bag of issue I see would come from FIR type inside attributes of operations not handled here. There is [some work to make dialect conversion cheaper](https://discourse.llvm.org/t/rfc-a-new-one-shot-dialect-conversion-driver/79083) happening in MLIR, maybe we can revisit at that point).

**Comment by kiranchandramohan** [comment]
Thanks @jeanPerier for the quick response.

> I wonder if the generic fix is not to remove the "op->getDialect() == firDialect" in the case just above. I do not recall the rational of limiting it to fir ops.

This is a good idea. The fir dialect-specific check currently converts the results. For this particular case, see the next point.

> (the next bag of issue I see would come from FIR type inside attributes of operations not handled here. 

The type is stored as an attribute in the OpenMP `PrivateClauseOp`, which is why a separate else statement is required here.

Some kind of generalization might still be required for the other declaration/recipe-based operations.

**Review by jeanPerier — APPROVED** [review]
Thanks Kiran for the details, then the only generic solution I see with the current pass would be to also update the TypeAttr attribute in the code that updates the result type (like [what is done for SymbolRefAttr in ExternalNameConversion](https://github.com/llvm/llvm-project/blob/21d27b3aabf3d06f7e8b1002b34bb467f6ab66d8/flang/lib/Optimizer/Transforms/ExternalNameConversion.cpp#L98-L106)).

If that does not work, you can assign an issue to me and I am OK with your patch.

**Comment by kiranchandramohan** [comment]
> Thanks Kiran for the details, then the only generic solution I see with the current pass would be to also update the TypeAttr attribute in the code that updates the result type (like [what is done for SymbolRefAttr in ExternalNameConversion](https://github.com/llvm/llvm-project/blob/21d27b3aabf3d06f7e8b1002b34bb467f6ab66d8/flang/lib/Optimizer/Transforms/ExternalNameConversion.cpp#L98-L106)).
> 
> If that does not work, you can assign an issue to me and I am OK with your patch.

Thanks @jeanPerier for the reference. Just an update here.

I added something like the following, which iterates through the attributes and updates if it is a typeAttr that needs conversion. This works fine for my usecase.
```
          for (const mlir::NamedAttribute &attr : op->getAttrDictionary())
            if (auto tyAttr = llvm::dyn_cast<mlir::TypeAttr>(attr.getValue()))
              if (typeConverter.needsConversion(tyAttr.getValue())) {
                auto toTy = typeConverter.convertType(tyAttr.getValue());
                op->setAttr(attr.getName(), mlir::TypeAttr::get(toTy));
              }
  ```
  But I see a failure in the gfortan test. I will have a detailed look later this week.
  ```
error: loc("/home/kiran/llvm-test-suite/Fortran/gfortran/regression/typebound_operator_9.f03":280:5): 'fir.type_desc' op wrapped type mismatched
error: loc("/home/kiran/llvm-test-suite/Fortran/gfortran/regression/typebound_operator_9.f03":315:5): 'fir.type_desc' op wrapped type mismatched
error: loc("/home/kiran/llvm-test-suite/Fortran/gfortran/regression/typebound_operator_9.f03":299:5): 'fir.type_desc' op wrapped type mismatched
error: loc("/home/kiran/llvm-test-suite/Fortran/gfortran/regression/typebound_operator_9.f03":228:5): 'fir.type_desc' op wrapped type mismatched
error: loc("/home/kiran/llvm-test-suite/Fortran/gfortran/regression/typebound_operator_9.f03":401:3): 'fir.type_desc' op wrapped type mismatched
              ```

**Comment by jeanPerier** [comment]
> But I see a failure in the gfortan test. I will have a detailed look later this week.

Thanks for testing @kiranchandramohan, I think the issue is the `BoxprocTypeRewriter` type converter of this pass is not handling  `fir::TypeDescType`, sorry for having you go through these issues. Do you want me to have a look?

Side note: the TypeDescOp design of duplicating the type (inside the result, and as attribute) is probably debatable/useless.

**Comment by kiranchandramohan** [comment]
> > But I see a failure in the gfortan test. I will have a detailed look later this week.
> 
> Thanks for testing @kiranchandramohan, I think the issue is the `BoxprocTypeRewriter` type converter of this pass is not handling `fir::TypeDescType`, sorry for having you go through these issues. Do you want me to have a look?
> 
> Side note: the TypeDescOp design of duplicating the type (inside the result, and as attribute) is probably debatable/useless.

Thanks for the hint. I will continue with this.

**Comment by kiranchandramohan** [comment]
> > Thanks for testing @kiranchandramohan, I think the issue is the `BoxprocTypeRewriter` type converter of this pass is not handling `fir::TypeDescType`, sorry for having you go through these issues. Do you want me to have a look?
> > Side note: the TypeDescOp design of duplicating the type (inside the result, and as attribute) is probably debatable/useless.
> 
> Thanks for the hint. I will continue with this.

Done

**Review by jeanPerier — APPROVED** [review]
The fix looks good (small nit on the include) and I worked fine for me. Thanks for making it generic @kiranchandramohan!

**Pull request merged**
