### PR TITLE
[AArch64] Update tests for stack-probing

### PR DESCRIPTION
**Pull request by matthewlevy97**
Compiler can re-order instructions (keeping opcode register dependencies) around code generated for stack probing. This leads to correct generation of code, but failing tests. Changing some CHECK-NEXT's to CHECK-DAG.

### CODE REVIEW

**Review by davemgreen — COMMENTED** [review]
Hi - this tests was generated with update_llc_test_checks.py. You might find that someone comes along and regenerates the check lines with it.

It looks like the new test tries to document something about how the assembly instructions are ordered, but from what I can see that should be handled by the usual register dependencies. Can you explain why INVALID_TO_BREAK_UP_CHECK_DAG? Do you have a follow-up that changes how the tests are generated, and could it just use update_llc_test_checks?

**Comment by matthewlevy97** [comment]
I do not currently have a follow-up diff for changing how the test is auto-generated. I found that the compiler can output the generated code for stack probing in different orders leading to this test failing, yet producing effectively the same generated code.

I added the INVALID_TO_BREAK_UP_CHECK_DAG to ensure the order of the registers are intact as just CHECK-DAG can allow full reordering and cause the test to not verify register dependencies for code gen. The INVALID_TO_BREAK_UP_CHECK_DAG is just a CHECK-NOT that should never match anything to prevent all the CHECK-DAGs from being connected. If there is a better way to represent this so that it is correctly auto-generated I will happily change it.

**Comment by aemerson** [comment]
What do you mean the compiler "can generate"? The compiler should behave deterministically so it should never change what it outputs for the same input.

**Comment by matthewlevy97** [comment]
I am working with an older version of the compiler and have been backporting changes (like stack probing). I believe the difference has to do with support for a CFI feature/missing diff in the older version causing a difference in the prologue output. If this commit does not work I am ok abandoning/reverting it.

**Comment by davemgreen** [comment]
I think it's find as-is. Just be aware that someone might come along and regenerate the tests at some point if it changes in some other way. The scripts should mean they are nice and easy to regenerate if needed in the older compiler.

**Pull request merged**
