### PR TITLE
[mlir][OpenMP] Implement the ConvertToLLVMPatternInterface

### PR DESCRIPTION
**Pull request by fabianmcg**
This patch implements the `ConvertToLLVMPatternInterface` for the OpenMP dialect, allowing `convert-to-llvm` to act on the OpenMP dialect.

### CODE REVIEW

**Comment by kiranchandramohan** [comment]
@fabianmcg This would need an RFC. And you might want to tag Mehdi and Alex Zinenko.

**Comment by fabianmcg** [comment]
@kiranchandramohan I can do an RFC. 
However, I didn't think there was a need because this is a pretty small and trivial change. Many upstream dialects
already implement this interface, for example: `arith, complex, cf, func, index, nvvm, math, memref, ub`. Also, most dialects that don't have it, is simply because no one has implemented it. 

This interface simply removes the necessity of invoking `convert-openmp-to-llvm` in production pipelines and allows using instead `convert-to-llvm`.

**Comment by kiranchandramohan** [comment]
Thanks for the details @fabianmcg. The only question is whether there will be a confusion here because other conversions (of arith, memref etc) fully convert to LLVM dialect whereas OpenMP only converts the types and retains the OpenMP operations.

**Comment by fabianmcg** [comment]
> The only question is whether there will be a confusion here because other conversions (of arith, memref etc) fully convert to LLVM dialect whereas OpenMP only converts the types and retains the OpenMP operations.

Not likely, this interface only picks up upstream OpenMP to LLVM patterns (the exact same patterns as `ConvertOpenMPToLLVM`), hence users shouldn't expect different behavior.

I'll also say that this is a pretty overridable change. For example, if one day a downstream user creates explicit lowerings to LLVM, they can implement the `ToLLVM` interface and substitute the registration call with theirs and the `convert-to-llvm` pass would use the downstream implementation. What I'm trying to say, is that this change is pretty localized to upstream MLIR.

**Review by kiranchandramohan — APPROVED** [review]
LG. Please wait a couple of days before you submit.

**Comment by kiranchandramohan** [comment]
reverse ping.

**Comment by fabianmcg** [comment]
Apologies @kiranchandramohan I was busy with school and miss the approval. I rebased the PR just to check it again (locally everything seemed to pass). As soon as it passes I'll merge it.

**Pull request merged**
