### PR TITLE
[NVPTX] fix emission for i1 load and extload

### PR DESCRIPTION
**Pull request by mjulian31**
Currently, an illegal 2-byte load from a 1-byte global variable is being generated. This change instead generates a 1-byte load and zero-extends it to i16 register. This was always the intended behavior of the function.

In addition, an i1 ext load of any kind needs to be promoted. A missing setLoadExtAction for ISD::EXTLOAD was causing an "Unhandled source type" unreachable due to an illegal i1 ext load during ISelDAGtoDAG (see below bug).

Bug https://github.com/llvm/llvm-project/issues/98033.

### CODE REVIEW

**Comment by mjulian31** [comment]
Adding reviewers @Artem-B and @jlebar

**Review by Artem-B — APPROVED** [review]
Good catch! LGTM.

**Comment by mjulian31** [comment]
Thanks @Artem-B! I do not have write permissions yet- could you please merge for me?

**Comment by Artem-B** [comment]
Will do once the pending checks pass.

**Comment by mjulian31** [comment]
Thanks! Please use my author details: Meredith Julian mjulian@nvidia.com when you do merge.

**Comment by Artem-B** [comment]
> Thanks! Please use my author details [...]

It will be whatever you used in your git commit. I just mash the button on github. The final commit will be "Authored by <you>, Committed by <me>".

I'll merge it tomorrow. Let me know if you want me to hold it for longer, if you need more time to update the pull request.

**Comment by mjulian31** [comment]
Ah perfect, that's what I used to commit. It should be good to go whenever pipelines pass. Thanks!

**Comment by mjulian31** [comment]
Looks like it is good to merge. Let me know if anything else is needed.

**Pull request merged**
