### PR TITLE
[Object][Wasm] Move wasm Object tests into their own directory (NFC)

### PR DESCRIPTION
**Pull request by dschuff**

### CODE REVIEW

**Comment by sbc100** [comment]
This makes some logical sense but the other sub-directories here represent architectures, and not object formats.  For example note that there are no COFF or ELF sub-directories here.   Should we move those tests too?

**Comment by dschuff** [comment]
True. I'm not sure I want to reorganize the whole thing but we could rename the directory from Wasm (which the object format is usually called) to WebAssembly (the architecture)😄

**Comment by dwblaikie** [comment]
> I think maybe go for a full rename for ELF and COFF too? See what the other maintainers think about it?
I assume there are sufficiently interesting differences to test between AArch64 and ARM, etc. but there's no architecture variants for wasm or webassembly - Yeah, there might be different ways of naming things between the format and the architecture, but I think the distinction isn't especially important to make - but I think it's fine/suitable for it to have a separate directory (I don't too much mind what name - but I agree consistency is nice to have, and if we've mostly used `WebAssembly` eswhere, let's use it here).

**Comment by MaskRay** [comment]
Creating `test/Object/wasm` looks good to me. I'd prefer `wasm/` instead of `Wasm/` since `wasm/` is used more common.

We've moved ELF/COFF/Mach-O tests for at least llvm-readobj/llvm-objcopy/llvm-objdump.

**Review by MaskRay — APPROVED** [review]

**Comment by dschuff** [comment]
I looked at this a little more. 
Regarding Wasm vs WebAssembly: I don't think naming the directory WebAssembly is a good idea. We have several files and directories named `Wasm` or `wasm` (e.g. lib/Object/Wasm, lld/wasm) and they (almost) all refer to the binary/object format, as opposed to the architecture. Naming just this test directory WebAssembly would make things worse rather than better IMO (because regardless of whether you believe it's good that the bin format doesn't match the architecture, at least right now we are mostly consistent).

Regarding Wasm vs wasm: It looks like actually Wasm is more common than wasm (notable exceptions being lld/wasm and  llvm/lib/ObjCopy/wasm). It also looks like `ninja check-llvm-object-wasm` works with Wasm as the directory name.

Therefore for this PR I'm going to suggest keeping the name as Wasm. Fixing some `wasm` and `WASM` directories to match can be a followup PR.

**Review by MaskRay — APPROVED** [review]

**Pull request merged**
