### PR TITLE
[libc++][vector] Inline remaining constructors filling vector with the same value

### PR DESCRIPTION
**Pull request by mtezych**
Placing physically next to each other remaining constructors filling vector with the same value
will make code better, since they all have nearly identical implementation, which needs to be kept in sync.

### CODE REVIEW

**Review by philnik777 — APPROVED** [review]
LGTM assuming the CI is green.

**Comment by ldionne** [comment]
@mtezych Can you please rebase this onto `main` and update the PR? It should get the CI running. I think this is good to go once CI has run.

**Comment by vitalybuka** [comment]
Asan is not happy https://lab.llvm.org/buildbot/#/builders/168/builds/20464
could you please fix or revert?

**Comment by vitalybuka** [comment]
Author is not committer, so fix may take some time, going to revert.

**Pull request merged**
