### PR TITLE
[llvm] Improve llvm.objectsize computation by computing GEP, alloca and malloc parameters bound

### PR DESCRIPTION
**Pull request by serge-sans-paille**
Using a naive expression walker, it is possible to compute valuable information for
allocation functions, GEP and alloca, even in the presence of some dynamic
information.
    
We don't rely on computeConstantRange to avoid taking advantage of
undefined behavior, which would be counter-productive wrt. usual
llvm.objectsize usage.
    
llvm.objectsize plays an important role in _FORTIFY_SOURCE definitions,
so improving its diagnostic in turns improves the security of compiled
application.
    
As a side note, as a result of recent optimization improvements, clang no
longer passes https://github.com/serge-sans-paille/builtin_object_size-test-suite
This commit restores the situation and greatly improves the scope of
code handled by the static version of __builtin_object_size.

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
I've updated the patch and it know successfully recompile stage2 clang with `-fundefined=sanitize` which was the previous issue.

**Comment by hvdijk** [comment]
To avoid confusion: this includes the changes from #115504 unmodified, and only the additional commit on top of that should be reviewed here?

**Comment by DavidSpickett** [comment]
> @jplehr and/or @DavidSpickett could you give a try to this patchset to make sure it actually fixes https://github.com/llvm/llvm-project/pull/114673 ?

It fixed the second stage build, I will check the fortran tests today.

**Comment by jmmartinez** [comment]
Hello,
I've launched `hip-build.sh` on my setup and it validated.

Trugarez !

**Comment by jplehr** [comment]
Thank you @jmmartinez

**Pull request merged**
