### PR TITLE
[mlir][sparse] support sparsifying 2:4 block sparsity

### PR DESCRIPTION
**Pull request by PeimingLiu**

### CODE REVIEW

**Review by aartbik — APPROVED** [review]

**Comment by Ag-Cu** [comment]
Hi, recently I have been very interested in MLIR's support for NVIDIA's sparse tensor core. I saw your recent commits and wanted to ask——have MLIR only added support for the NV_2:4 sparse format so far, or have implemented an end-to-end flow that can generate calls to the sparse tensor core via mma.sp PTX instructions?

**Comment by aartbik** [comment]
Thanks for your interest in this work!

We have an end-to-end flow that maps linalg.matmul to 2:4 using our "CUDA libgen" path, i.e. we change the code into a call into the cusparseLt library for 2:4 operations. We do have a sample example that uses gpu dialect to actually map to the mma instruction (through nvgpu.mma.sp.sync), but that is not part of any codegen... yet!

See https://discourse.llvm.org/t/sparse-compiler-and-gpu-code-generation/69786/ for a more in-depth discussions of what I wrote above.

**Comment by Ag-Cu** [comment]
Thanks, This looks like an awsome job! I think I should to take a closer look.

By the way, I read a paper named [VENOM: A Vectorized N:M Format for Unleashing the Power of Sparse Tensor Cores](https://arxiv.org/abs/2310.02065), it is about an open source sparse library for any N:M Format instead of 2:4, and it can still make use of Sparse Tensor Cores. Do you think it is necessary to support N:M Format instead of only NV_24?(Due to current hardware limitations, this matter does not seem to be urgent? I think...)

We are trying to optimize this library, and later we are interested in MLIR's codegen to call Sparse Tensor Cores. If N:M Format is necessary, we may consider adding it to the work plan. And is there any information here that can help develop codegen?

Thanks for your time.

**Comment by aartbik** [comment]
For sure! The current NV_2:4 syntax is just a stepping stone towards a more general N:M syntax with N and M flexible integers. So, expect this to improve soon in MLIR!

**Pull request merged**
