### PR TITLE
[lldb][Docs] Various style improvements to the tutorial

### PR DESCRIPTION
**Pull request by DavidSpickett**
* Replace "we" with either "you" (when talking to the reader) or "lldb" (when talking about the project).
* Always refer to lldb as lldb not LLDB, to match what the user sees on the command line.
* Remove a bunch of contractions for example "won't". Which don't (pun intended) seem like a big deal at first but even I as a native English speaker find the text clearer with them expanded.
* Use RST's plain text highlighting for keywords and command names.
* Split some very long lines for easier editing in future.

### CODE REVIEW

**Comment by DavidSpickett** [comment]
> Always refer to lldb as lldb not LLDB, to match what the user sees on the command line.

If this were any other doc I'd say it should always be LLDB and GDB as that's the projects' branding. In this doc I think it's better to imagine the user is looking at side by side command lines.

**Comment by medismailben** [comment]
LGTM!

**Review by medismailben — APPROVED** [review]

**Comment by JDevlieghere** [comment]
> > Always refer to lldb as lldb not LLDB, to match what the user sees on the command line.
> 
> If this were any other doc I'd say it should always be LLDB and GDB as that's the projects' branding. In this doc I think it's better to imagine the user is looking at side by side command lines.

I'm not sure I follow that reasoning. In all fairness I might be biased as I try to consistently use "LLDB" unless I'm referring tot the binary or the prompt. Ignoring things like `(lldb)`, `lldb-` and `lldb.`, it looks like the docs favor "LLDB" as well.

```
$ rg 'LLDB' | wc -l
     605
$ rg 'lldb' | awk '!/\(lldb\)/ && !/lldb\./ && !/lldb-/' | wc -l
     362
```

Personally I'd lean towards more consistency.

**Comment by DavidSpickett** [comment]
Yes fair point the docs as a whole prefer the branding. As the document itself was mostly lower case that also influenced me.

I tried to put the name changes in their own commit but some are spread around, so I'll be a bit cheeky and land this as is then come back with a PR to properly brand the names, or mark places where we are talking about the binary.

**Pull request merged**
