### PR TITLE
[CodeGen][Mips] Explicit ELF output file format for MIPS tests

### PR DESCRIPTION
**Pull request by hpoussin**
This will be required once MIPS architecture defaults to COFF files on Windows platforms.

### CODE REVIEW

**Comment by hpoussin** [comment]
Ping.
I don't think the timeout failure of test "tools/lldb-dap/evaluate/TestDAP_evaluate.py" on Linux buildbot is due to my commit.

**Comment by brad0** [comment]
cc @yingopq

**Comment by hpoussin** [comment]
Ping.

**Comment by hpoussin** [comment]
Ping @brad0, @yingopq, @FlyGoat, @wzssyqa, @mstorsjo

**Comment by yingopq** [comment]
LGTM.

**Comment by wzssyqa** [comment]
I don't think that we should have these test case modification.
I mean that ELF should be kept as the default value for MIPS.

**Comment by wzssyqa** [comment]
LLVM doesn't expect that the behavior of same command has different behaviors on different platforms.

Aka, you should always use something like `--triple=mips-coff` if you need the object to be a COFF.

**Comment by brad0** [comment]
@MaskRay

**Comment by mstorsjo** [comment]
> I don't think that we should have these test case modification. I mean that ELF should be kept as the default value for MIPS.

Indeed, even if we make COFF the default for the OS windows on MIPS, it shouldn't change anything about when we run with an OS-less triple like `llc -mtriple=mipsel`, so I don't see why this is needed.

**Comment by wzssyqa** [comment]
On My AARCH64 Mac
```
syq@syqs-iMac> clang --target=aarch64 -c xx.c                                                                                                                                                          
syq@syqs-iMac> file xx.o                                                                                                                                                                               
xx.o: ELF 64-bit LSB relocatable, ARM aarch64, version 1 (SYSV), not stripped
```

**Comment by yingopq** [comment]
> LLVM doesn't expect that the behavior of same command has different behaviors on different platforms.
> 
> Aka, you should always use something like `--triple=mips-coff` if you need the object to be a COFF.

Thanks, I got it.

**Comment by MaskRay** [comment]
The thumb of rule is: `-mtriple=mipsel` defaults to ELF, even if we don't write '-elf' or '-linux'. Yes, ELF is the favored object file format, which gets this shortcut, while other object file formats need a lengthy target triple.

**Pull request closed without merging**
