### PR TITLE
[AArch64][MachO] Add ptrauth ABI version to arm64e cpusubtype.

### PR DESCRIPTION
**Pull request by ahmedbougacha**
In a mach_header, the cpusubtype is a 32-bit field, but it's split in 2 subfields:
- the low 24 bits containing the cpu subtype proper, (e.g., CPU_SUBTYPE_ARM64E 2)
- the high 8 bits containing a capability field used for additional feature flags.

Notably, it's only the subtype subfield that participates in fat file slice discrimination: the caps are ignored.

arm64e uses the caps subfield to encode a ptrauth ABI version:
- 0x80 (CPU_SUBTYPE_PTRAUTH_ABI) denotes a versioned binary
- 0x40 denotes a kernel-ABI binary
- 0x00-0x0F holds the ptrauth ABI version

This teaches the basic obj tools to decode that (or ignore it when unneeded).

It also teaches the MachO writer to default to emitting versioned binaries, but with a version of 0 (and without the kernel ABI flag).

Modern arm64e requires versioned binaries: a binary with 0x00 caps in cpusubtype is now rejected by the linker and everything after. We can live without the sophistication of specifying the version and kernel ABI for now.

### CODE REVIEW

**Review by francisvm — APPROVED** [review]
Looks great :)

**Review by JDevlieghere — APPROVED** [review]

**Comment by mstorsjo** [comment]
When compiled with GCC, this triggers hundreds of warnings like this:
```
In file included from /home/martin/code/llvm-project/llvm/include/llvm/Object/MachO.h:23,
                 from /home/martin/code/llvm-project/llvm/lib/DebugInfo/DWARF/DWARFContext.cpp:43:
/home/martin/code/llvm-project/llvm/include/llvm/BinaryFormat/MachO.h: In function ‘unsigned int llvm::MachO::CPU_SUBTYPE_ARM64E_WITH_PTRAUTH_VERSION(unsigned int, bool)’:
/home/martin/code/llvm-project/llvm/include/llvm/BinaryFormat/MachO.h:1664:35: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
 1664 |          (PtrAuthKernelABIVersion ? CPU_SUBTYPE_ARM64E_KERNEL_PTRAUTH_ABI_MASK
      |           ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
 1665 |                                   : 0) |
      |                                   ~~~

```

**Comment by ahmedbougacha** [comment]
> When compiled with GCC, this triggers hundreds of warnings like this:
> 
> ```
> In file included from /home/martin/code/llvm-project/llvm/include/llvm/Object/MachO.h:23,
>                  from /home/martin/code/llvm-project/llvm/lib/DebugInfo/DWARF/DWARFContext.cpp:43:
> /home/martin/code/llvm-project/llvm/include/llvm/BinaryFormat/MachO.h: In function ‘unsigned int llvm::MachO::CPU_SUBTYPE_ARM64E_WITH_PTRAUTH_VERSION(unsigned int, bool)’:
> /home/martin/code/llvm-project/llvm/include/llvm/BinaryFormat/MachO.h:1664:35: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
>  1664 |          (PtrAuthKernelABIVersion ? CPU_SUBTYPE_ARM64E_KERNEL_PTRAUTH_ABI_MASK
>       |           ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>  1665 |                                   : 0) |
>       |                                   ~~~
> ```

Hmm, playing around with various gcc versions in godbolt this warning seems to have gotten less noisy in newer versions;  looking at the enum I think we can silence it with a little cleanup anyway, I tried 1d7bb2bbfa1d.   Let me know if that doesn't help!

**Comment by mstorsjo** [comment]
> > When compiled with GCC, this triggers hundreds of warnings like this:
> > ```
> > In file included from /home/martin/code/llvm-project/llvm/include/llvm/Object/MachO.h:23,
> >                  from /home/martin/code/llvm-project/llvm/lib/DebugInfo/DWARF/DWARFContext.cpp:43:
> > /home/martin/code/llvm-project/llvm/include/llvm/BinaryFormat/MachO.h: In function ‘unsigned int llvm::MachO::CPU_SUBTYPE_ARM64E_WITH_PTRAUTH_VERSION(unsigned int, bool)’:
> > /home/martin/code/llvm-project/llvm/include/llvm/BinaryFormat/MachO.h:1664:35: warning: enumeral and non-enumeral type in conditional expression [-Wextra]
> >  1664 |          (PtrAuthKernelABIVersion ? CPU_SUBTYPE_ARM64E_KERNEL_PTRAUTH_ABI_MASK
> >       |           ~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> >  1665 |                                   : 0) |
> >       |                                   ~~~
> > ```
> 
> Hmm, playing around with various gcc versions in godbolt this warning seems to have gotten less noisy in newer versions; looking at the enum I think we can silence it with a little cleanup anyway, I tried [1d7bb2b](https://github.com/llvm/llvm-project/commit/1d7bb2bbfa1d50663e2883e0e8e1d2b147103013). Let me know if that doesn't help!

Thanks! Unfortunately, that doesn't seem to help, at least with GCC 11...

**Comment by ahmedbougacha** [comment]
> Thanks! Unfortunately, that doesn't seem to help, at least with GCC 11...

I guess we'll have to explicitly silence it: bcb6e2703bf0

**Comment by mstorsjo** [comment]
> > Thanks! Unfortunately, that doesn't seem to help, at least with GCC 11...
> 
> I guess we'll have to explicitly silence it: [bcb6e27](https://github.com/llvm/llvm-project/commit/bcb6e2703bf03c1a299c75676dc3ccc999e30fe8)

Thanks, that did the trick!

**Pull request merged**
