### PR TITLE
[llvm-size] Avoid unneeded uses of 'raw_string_ostream::str' (NFC)

### PR DESCRIPTION
**Pull request by JOE1994**
Remove unnecessary layer of indirection.

### CODE REVIEW

**Review by jh7370 — COMMENTED** [review]
Given that this seems to be building with the pre-merge checks, I'm probably completely missing something, so apologies for the question, but I wanted to double check the details of the `raw_string_ostream::c_str` function, only to be completely unable to find it. Would you mind pointing out where it is, please?

**Comment by JOE1994** [comment]
> Given that this seems to be building with the pre-merge checks, I'm probably completely missing something, so apologies for the question, but I wanted to double check the details of the `raw_string_ostream::c_str` function, only to be completely unable to find it. Would you mind pointing out where it is, please?

AFAIK, there is no `raw_string_ostream::c_str` function.
The `.c_str()` calls in the diff are calls to the [`std::string::c_str`](https://cplusplus.com/reference/string/string/c_str/) function.

**Comment by JOE1994** [comment]
CI is failing due to a LIT failure unrelated to this revision.
Will "Update with rebase" to see how it goes.

**Review by jh7370 — APPROVED** [review]
Right, sorry! I missed that you'd changed to using `fmtbuf` as well. LGTM.

P.S. for clearly unrelated failures in the pre-merge checks, there's no need to update your PR. It's acceptable to land with failures, if they aren't related to your PR. Also, LLVM guidelines say to avoid force pushes in an active review, because it can make it harder to review what's changed since the previous version - use a merge commit from main instead (this will disappear when the PR is squashed and merged). That's not specifically an issue in this case mind you.

**Pull request merged**
