### PR TITLE
[flang] Allow getenv as alternate spelling for get_environment_variable

### PR DESCRIPTION
**Pull request by DavidTruby**
This patch adds getenv as an alternate spelling for get_environment_variable.
This spelling is allowed by multiple other compilers and is used in OpenRadioss.

### CODE REVIEW

**Comment by kiranchandramohan** [comment]
Could you point to the usage in OpenRadioss?

Gfortran defines Getenv in https://gcc.gnu.org/onlinedocs/gfortran/GETENV.html. Only a subset of the GET_ENVIRONMENT_VARIABLE standard intrinsic is supported.

**Comment by DavidTruby** [comment]
This is used in a number of places in OpenRadioss, for example here: https://github.com/OpenRadioss/OpenRadioss/blob/7aadf0746ecf6b34fee7df39a614e5b9865e4ddd/common_source/qa/qa_out_mod.F#L78

OpenRadioss only uses the flags that gfortran accepts, however it would be more complicated to restrict the flags to just those and I don't see a good reason to restrict it as they're a strict subset of what get_environment_variable accepts.

**Comment by tblah** [comment]
@kiranchandramohan does this look okay to you with the updated documentation?

**Comment by kiranchandramohan** [comment]
> @kiranchandramohan does this look okay to you with the updated documentation?

Looks OK to me. My original concern was whether we should only support the gfortran extension specification (`CALL GETENV(NAME, VALUE)`). And whether the lowering code can be avoided by directly calling a new runtime function like `fdate` (https://github.com/llvm/llvm-project/pull/71222).

Please wait for @klausler.

**Comment by klausler** [comment]
Why not use the `genericAlias` table in `flang/lib/Evaluate/intrinsics.cpp`?

**Comment by DavidTruby** [comment]
@klausler I've switched this to use the genericAlias table as requested, does this look better now?

**Review by klausler — APPROVED** [review]

**Pull request merged**
