### PR TITLE
[libcxx] Option to disable overridden function detection

### PR DESCRIPTION
**Pull request by petrhosek**
The overriden function detection currently uses a custom section which can break existing linker scripts that are commonly used in embedded systems. It also results in the overridden functions being kept in the binary even though it's not being used leading to extra bloat which is a concern for embedded systems. This change introduces an option to disable this feature.

### CODE REVIEW

**Comment by philnik777** [comment]
Why does this require a feature to disable? Can't you just update the linker script? That shouldn't be that hard. Or we could even look into putting it into a subsection like `.text.__libcxx_whatever_it_was`. Wouldn't that also solve the problem?

**Comment by petrhosek** [comment]
> Why does this require a feature to disable? Can't you just update the linker script? That shouldn't be that hard.

Ideally yes, we would update the linker script, but that can be challenging since we always don't have access to linker scripts used by our partners and even when we do, it can require significant effort to find and update every single linker script. I'm worried that this is really going to hamper libc++ adoption in the embedded space. 

> Or we could even look into putting it into a subsection like `.text.__libcxx_whatever_it_was`. Wouldn't that also solve the problem?

That doesn't work. We rely on the generated `__start_<name>` and `__stop_<name>` symbols but those are only generated for sections that use C identifier names (so not `.text`). Plus if we used `.text.<whatever>`, it'd be merged merged into `.text` output section and `__is_function_overridden` would always return `true` making this feature useless.

**Comment by ldionne** [comment]
I'm iffy about adding an option just to disable that -- that feels like a hack. There might be a more general configuration option trying to emerge here. What do these linker scripts do that is special and breaks how this detection work?

**Comment by philnik777** [comment]
> I'm iffy about adding an option just to disable that -- that feels like a hack. There might be a more general configuration option trying to emerge here. What do these linker scripts do that is special and breaks how this detection work?

Just my guess: Linker scripts usually define where the sections go explicitly. Since our section isn't part of one of the standard sections it's not picked the linker script wildcards it simply discards it.

**Comment by petrhosek** [comment]
> > I'm iffy about adding an option just to disable that -- that feels like a hack. There might be a more general configuration option trying to emerge here. What do these linker scripts do that is special and breaks how this detection work?
> 
> Just my guess: Linker scripts usually define where the sections go explicitly. Since our section isn't part of one of the standard sections it's not picked the linker script wildcards it simply discards it.

That's precisely the reason. See for example the [Raspberry Pi Pico linker script in Pico SDK](https://github.com/raspberrypi/pico-sdk/blob/efe2103f9b28458a1615ff096054479743ade236/src/rp2_common/pico_crt0/rp2040/memmap_default.ld) which is one of the projects where this issue came up. Since the linker script doesn't place the `__lcxx_override` section explicitly, the linker places it arbitrarily. On this particular target, the section is placed somewhere that breaks assumptions the boot ROM makes about code locations (between `.boot2` and `.text`). Since `operator new` is in `__lcxx_override`, any call to `new` breaks the system.

I'd also point out that Pico SDK was using libc++ without any issues. They started reporting breakages after upgrading their toolchain to a version that included https://github.com/llvm/llvm-project/commit/314526557ec66ee627ae8a1c03f6ccc610668fdb. Whether intentional or not, for embedded users that change is a breaking change and I think we should have an opt-out mechanism because updating all affected linker scripts to take `__lcxx_override` into account will take some time.

**Comment by petrhosek** [comment]
Ping?

**Comment by philnik777** [comment]
More general thought: Could we implement this mechanism through aliases instead: https://godbolt.org/z/E5oKj9hfe? I think that might make `__is_function_overriden` a bit more lean and avoid having to put the functions into a separate section. That probably also doesn't work everywhere, but that doesn't seem like a huge problem to me.

**Comment by petrhosek** [comment]
> More general thought: Could we implement this mechanism through aliases instead: https://godbolt.org/z/E5oKj9hfe? I think that might make `__is_function_overriden` a bit more lean and avoid having to put the functions into a separate section. That probably also doesn't work everywhere, but that doesn't seem like a huge problem to me.

I looked into it and try to implement this approach in libc++, but then realized that this approach has a serious downside in that both the original function and the one that overrides it would be kept in the binary even though the original is only used for the address comparison. This may not be a big deal on other systems but it's a concern for baremetal uses where every byte matters and don't want to ship any dead code.

With the existing implementation, that is also the case, but if you use a custom linker script you can manually discard it although that would effectively disable `__is_function_overriden` same as this change does but is more involved. Using that approach would likely result in embedded developers cargo culting the same snippet into every linker script which I think is undesirable.

Therefore, I'd would like to merge this change as is. I can try to finish and upload the implementation based on aliases for ELF as a follow up PR, but for baremetal we always want to disable this regardless of the implementation.

**Comment by philnik777** [comment]
> > More general thought: Could we implement this mechanism through aliases instead: https://godbolt.org/z/E5oKj9hfe? I think that might make `__is_function_overriden` a bit more lean and avoid having to put the functions into a separate section. That probably also doesn't work everywhere, but that doesn't seem like a huge problem to me.
> 
> I looked into it and try to implement this approach in libc++, but then realized that this approach has a serious downside in that both the original function and the one that overrides it would be kept in the binary even though the original is only used for the address comparison. This may not be a big deal on other systems but it's a concern for baremetal uses where every byte matters and don't want to ship any dead code.
> 
> With the existing implementation, that is also the case, but if you use a custom linker script you can manually discard it although that would effectively disable `__is_function_overriden` same as this change does but is more involved. Using that approach would likely result in embedded developers cargo culting the same snippet into every linker script which I think is undesirable.
> 
> Therefore, I'd would like to merge this change as is. I can try to finish and upload the implementation based on aliases for ELF as a follow up PR, but for baremetal we always want to disable this regardless of the implementation.

How would that result in dead code being shipped? If you properly override all the overloads the compiler can discard the libc++ versions and if you don't provide any yourself the checks can be constant-folded assuming you're using LTO.

**Comment by petrhosek** [comment]
> > > More general thought: Could we implement this mechanism through aliases instead: https://godbolt.org/z/E5oKj9hfe? I think that might make `__is_function_overriden` a bit more lean and avoid having to put the functions into a separate section. That probably also doesn't work everywhere, but that doesn't seem like a huge problem to me.
> > 
> > 
> > I looked into it and try to implement this approach in libc++, but then realized that this approach has a serious downside in that both the original function and the one that overrides it would be kept in the binary even though the original is only used for the address comparison. This may not be a big deal on other systems but it's a concern for baremetal uses where every byte matters and don't want to ship any dead code.
> > With the existing implementation, that is also the case, but if you use a custom linker script you can manually discard it although that would effectively disable `__is_function_overriden` same as this change does but is more involved. Using that approach would likely result in embedded developers cargo culting the same snippet into every linker script which I think is undesirable.
> > Therefore, I'd would like to merge this change as is. I can try to finish and upload the implementation based on aliases for ELF as a follow up PR, but for baremetal we always want to disable this regardless of the implementation.
> 
> How would that result in dead code being shipped? If you properly override all the overloads the compiler can discard the libc++ versions and if you don't provide any yourself the checks can be constant-folded assuming you're using LTO.

LTO isn't generally usable on baremetal because it's incompatible with certain linker scripts constructs; this is something the community has been trying to [address for some time](https://llvm.org/devmtg/2022-11/slides/QuickTalk11-Link-TimeAttributesforLTO.pdf) but there still isn't a working solution.

**Comment by petrhosek** [comment]
#114961 implements the overridden function detection using aliases as discussed in the libc++ monthly meeting.

**Pull request closed without merging**
