### PR TITLE
[Clang] Remove the special-casing for RequiresExprBodyDecl in BuildResolvedCallExpr() after fd87d765c0

### LINKED ISSUE #110785: [Clang] Requires expression incorrectly use non-static methods from generic lambda inside static method
Compiler Explorer: https://godbolt.org/z/66397fTff

```cxx
struct Foo {
    static void f(auto) requires(false) {}
    void f(int) {}

    static void g() {
        static constexpr auto b = [](auto v) {
            return requires { f(v); };
        } (0);
        static_assert(b == false);
    }
};
```

Clang versions <= 18 and other compilers accept this program. The requires expression should be false, since `f(0)` is ill-formed in the context inside the lambda.

### PR DESCRIPTION
**Pull request by zyn0217**
The special-casing for RequiresExprBodyDecl caused a regression, as reported in #110785.

The original fix for #84020 has been superseded by fd87d765c0, which establishes a `DependentScopeDeclRefExpr` instead of a `CXXDependentScopeMemberExpr` for the case in issue. So the spurious diagnostic in #84020 would no longer occur.

This also merges the test for #84020 together with that for #110785 into clang/test/SemaTemplate/instantiate-requires-expr.cpp.

No release note because I think this merits a backport.

Fixes #110785

### CODE REVIEW

**Comment by cor3ntin** [comment]
Do you know why this check was there in the first place?

**Comment by zyn0217** [comment]
That's https://github.com/llvm/llvm-project/pull/85198. Which was merged prior to the generic solution fd87d765c0 by @sdkrystian

**Comment by cor3ntin** [comment]
> That's #85198. Which was merged prior to the generic solution [fd87d76](https://github.com/llvm/llvm-project/commit/fd87d765c0455265aea4595a3741a96b4c078fbc) by @sdkrystian

Thanks!
Can you make the description reflect that more clearly? Thanks!

**Review by cor3ntin — APPROVED** [review]
LGTM

**Review by mizvekov — APPROVED** [review]
LGTM

**Comment by zyn0217** [comment]
> Can you make the description reflect that more clearly? Thanks!

Done.

**Pull request merged**
