### PR TITLE
[BOLT][AArch64] Support for pointer authentication

### PR DESCRIPTION
**Pull request by bgergely0**
Currently BOLT does not support Aarch64 binaries with pointer authentication, because it cannot correctly handle `.cfi_negate_ra_state`. 

This has been raised in several issues:
- https://github.com/llvm/llvm-project/issues/74833
- https://github.com/llvm/llvm-project/issues/80992

## Where are OpNegateRAState CFIs needed?
These CFI instructions need to be placed in locations, where one BasicBlock has a different return address state (signed or not signed) than the previous one.

As BasicBlocks are moving around during optimization, we cannot know where these should be placed, until all optimizations are done.

For this reason, my implementation skips these CFIs during reading the binary, and adds a new pass `InsertNegateRAStatePass`, that can identify subsequent BBs with different RA States.

## InsertNegateRAStatePass
- the pass marks all BBs with three states: Unknown, Signed, and Unsigned. 
- it explores the CFG to find successors of blocks with LR signing, and marks them as Signed, until a BB with authenticating instruction is found. Successors of an authenticating BB, or BBs before signing are marked as Unsigned.
- after identifying the BB States, we can insert `OpNegateRAState` to locations, where the State is changing

## Dependencies
- to find out which BasicBlock has signed and unsigned state, we need a correct CFG. 
- I have found an issue with CFG generation, which is described here: 
https://github.com/llvm/llvm-project/issues/115154
- until I have a working PR to fix that (near future), I cherry-picked a commit from @kbeyls' `bolt-gadget-scanner` fork as a workaround for testing this change
- this commit allows the user to input suspected noreturn functions in a file using the `--noreturnfuncs-file=<file>` option.

## WIP
Not all pointer signing and authenticating instructions are covered yet, only `paciasp` and `autiasp`. This is enough to test on binaries built with `-mbranch-protection=pac-ret`.

### CODE REVIEW

**Comment by ayermolo** [comment]
Please add a test.

**Comment by bgergely0** [comment]
Fixed the formatting issues.

**Review by paschalis-mpeis — COMMENTED** [review]
Thanks for your PR @bgergely0. This seems a long awaited feature! 🎉 

Some higher-level notes:
- IMHO the patch is somewhat big and maybe it could be broken down to separate PRs, like the `populateFunctionNames`, or the introduction of the `no-returns` flags, the creation of `getCalleeName`, etc, then followed by a PR with the pass itself.
- you could expand/add descriptions to the pass and to related functions. You've added a very nice introduction to your PR, I was thinking of something equivalent to relevant places in code.

Apart form that, I've added some nits/reformatting comments and a concern whether the pass should run a bit earlier. Good stuff!

**Comment by bgergely0** [comment]
Hi @ayermolo 

After some discussion with @kbeyls we believe that it's not the best idea to rely on the CFG to find locations to insert OpNegateRAState CFIs. Partly because of the issue with noreturn functions, partly because of other possible issues.

Instead, I will try the following:
- save locations if .cfi_negate_ra_state-s in the input functions,
- work out the signedness of each MCInst,
- track that information in Annotations,
- after all optimizations, find where the state is changing and emit .cfi_negate_ra_state

Let me know if you have any comments on this approach. It seems more sound than what is in this PR currently, but it would require more memory because we would be tracking extra annotations on every MCInst.

**Comment by bgergely0** [comment]
Closing as https://github.com/llvm/llvm-project/pull/120064 contains a new, better solution to this, that does not depend on the CFG.

**Pull request closed without merging**
