### PR TITLE
[mlir] add debug messages explaining failure reasons of isValidIntOrFloat

### PR DESCRIPTION
**Pull request by j2kun**
I have run into assertion failures quite often when calling this method via `DenseElementsAttr::get`, and I think this would help, at the very least, by printing out the bit width size mismatches, rather than a non-descript assertion failure. I included debug messages for all the other cases in the method for completeness.

### CODE REVIEW

**Comment by joker-eph** [comment]
Can we add to the assertion a message hinting the user to re-run with `-debug-only=builtinattributes` ?

**Comment by j2kun** [comment]
> Can we add to the assertion a message hinting the user to re-run with `-debug-only=builtinattributes` ?

TIL this is a thing. Added!

**Review by joker-eph — APPROVED** [review]

**Comment by joker-eph** [comment]
Thanks, will merge after CI is passing

**Comment by joker-eph** [comment]
Actually you're GitHub setting would lead to ` j2kun@users.noreply.github.com` used for the commit, can you fix this?

**Comment by joker-eph** [comment]
Pushed in 04d63088cd5b

**Comment by MacDue** [comment]
> I still see this:
> 
> Screenshot 2023-10-18 at 4 11 22 PM
> 
> I can however checkout the PR and push the commit manually.

FYI: You need to uncheck "Keep my email addresses private" (under Settings > Emails)

**Comment by j2kun** [comment]
Ah, I just amended the commit. I do prefer to keep you email private when
possible. Is there a reason to not to that for MLIR?

**Pull request closed without merging**
