### PR TITLE
[libc++] Format the code base

### PR DESCRIPTION
**Pull request by ldionne**
This patch runs clang-format on all of libcxx/include and libcxx/src, in accordance with the RFC discussed at [1]. Follow-up patches will format the benchmarks, the test suite and remaining parts of the code. I'm splitting this one into its own patch so the diff is a bit easier to review.

This patch was generated with:

```
find libcxx/include libcxx/src -type f \
   | grep -v 'module.modulemap.in' \
   | grep -v 'CMakeLists.txt' \
   | grep -v 'README.txt' \
   | grep -v 'libcxx.imp' \
   | grep -v '__config_site.in' \
   | xargs clang-format -i
```

  A Git merge driver is available in libcxx/utils/clang-format-merge-driver.sh
    to help resolve merge and rebase issues across these formatting changes.

[1]: https://discourse.llvm.org/t/rfc-clang-formatting-all-of-libc-once-and-for-all

### CODE REVIEW

**Comment by ldionne** [comment]
I know some parts will need `clang-format off / on`, let's iterate on that before we merge the PR.

**Comment by ldionne** [comment]
CC @llvm/libcxx-vendors

**Comment by ldionne** [comment]
I went through everything and this is the set of annotations I'd add for now: https://github.com/llvm/llvm-project/pull/74352. Other suggestions are welcome.

**Comment by ldionne** [comment]
I think `clang-format` is doing something reasonable everywhere. However, there's one pattern we have which might merit discussion. We have a bunch of these write-it-three-times functions. Here's an example with the current manual formatting:

```
template <class... _Args, class = enable_if_t<is_invocable_v<_Op, _BoundArgs&..., _Args...>>>
_LIBCPP_HIDE_FROM_ABI constexpr auto operator()(_Args&&... __args) & noexcept(
    noexcept(_Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...)))
    -> decltype(_Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...)) {
  return _Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...);
}
```

If we just run this through `clang-format`, we get:

```
template <class... _Args, class = enable_if_t<is_invocable_v<_Op, _BoundArgs const&..., _Args...>>>
_LIBCPP_HIDE_FROM_ABI constexpr auto operator()(_Args&&... __args) const& noexcept(
    noexcept(_Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...)))
    -> decltype(_Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...)) {
  return _Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...);
}
```

This is not aligned anymore, and it's harder to read. This example isn't very ugly, but we have a few others that do become harder to read when they're not aligned anymore. If we're not happy with this, another option would be to use "clever" comments:

```
template <class... _Args, class = enable_if_t<is_invocable_v<_Op, _BoundArgs&..., _Args...>>>
_LIBCPP_HIDE_FROM_ABI constexpr auto operator()(_Args&&... __args) & noexcept(
    noexcept(/*   */ _Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...)))
    -> decltype(/**/ _Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...)) //
{
  return /*       */ _Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...);
}
```

The third option would be to use a macro. We previously discussed this but eventually ended up not doing it:

```
#  define _LIBCPP_EXPRESSION_EQUIVALENT(expr)                                                      \
    noexcept(noexcept(expr))->decltype(expr) { return expr; }                                      \
    static_assert(true, "")

template <class... _Args, class = enable_if_t<is_invocable_v<_Op, _BoundArgs const&..., _Args...>>>
_LIBCPP_HIDE_FROM_ABI constexpr auto operator()(_Args&&... __args) const& //
  _LIBCPP_EXPRESSION_EQUIVALENT(_Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...));
```

**Comment by H-G-Hristov** [comment]
> I think `clang-format` is doing something reasonable everywhere. However, there's one pattern we have which might merit discussion. We have a bunch of these write-it-three-times functions. Here's an example with the current manual formatting:
> 
> ```c++
> template <class... _Args, class = enable_if_t<is_invocable_v<_Op, _BoundArgs&..., _Args...>>>
> _LIBCPP_HIDE_FROM_ABI constexpr auto operator()(_Args&&... __args) & noexcept(
>     noexcept(_Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...)))
>     -> decltype(_Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...)) {
>   return _Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...);
> }
> ```
> 
> If we just run this through `clang-format`, we get:
> 
> ```c++
> // option #1
> template <class... _Args, class = enable_if_t<is_invocable_v<_Op, _BoundArgs const&..., _Args...>>>
> _LIBCPP_HIDE_FROM_ABI constexpr auto operator()(_Args&&... __args) const& noexcept(
>     noexcept(_Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...)))
>     -> decltype(_Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...)) {
>   return _Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...);
> }
> ```
> 
> This is not aligned anymore, and it's harder to read. This example isn't very ugly, but we have a few others that do become harder to read when they're not aligned anymore. If we're not happy with this, another option would be to use "clever" comments:
> 
> ```c++
> // option #2
> template <class... _Args, class = enable_if_t<is_invocable_v<_Op, _BoundArgs&..., _Args...>>>
> _LIBCPP_HIDE_FROM_ABI constexpr auto operator()(_Args&&... __args) & noexcept(
>     noexcept(/*   */ _Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...)))
>     -> decltype(/**/ _Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...)) //
> {
>   return /*       */ _Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...);
> }
> ```
> 
> The third option would be to use a macro. We previously discussed this but eventually ended up not doing it:
> 
> ```c++
> // option 3
> #  define _LIBCPP_EXPRESSION_EQUIVALENT(expr)                                                      \
>     noexcept(noexcept(expr))->decltype(expr) { return expr; }                                      \
>     static_assert(true, "")
> 
> template <class... _Args, class = enable_if_t<is_invocable_v<_Op, _BoundArgs const&..., _Args...>>>
> _LIBCPP_HIDE_FROM_ABI constexpr auto operator()(_Args&&... __args) const& //
>     _LIBCPP_EXPRESSION_EQUIVALENT(_Op()(std::get<_Idx>(__bound_args_)..., std::forward<_Args>(__args)...));
> ```

@ldionne Would this new clang-format 18 option help: https://clang.llvm.org/docs/ClangFormatStyleOptions.html#allowbreakbeforenoexceptspecifier

**Comment by ldionne** [comment]
> @ldionne Would this new clang-format 18 option help: https://clang.llvm.org/docs/ClangFormatStyleOptions.html#allowbreakbeforenoexceptspecifier

Thanks for pointing this out, I wasn't aware of it! However, I am not sure it would fix our issues because it probably still wouldn't align the three identical bits of code. It feels like `clang-format` would almost need to learn about the write-it-three-times pattern in order to do a good job at this (and even then, some write-it-three-times expressions are so long that custom formatting is really needed).

**Comment by petrhosek** [comment]
Looks like this broke the build of libc++ on Windows with the following error:
```
C:\b\s\w\ir\x\w\llvm_build\.\bin\clang-cl.exe --target=x86_64-pc-windows-msvc  /nologo -TP -DUNICODE -D_ALLOW_ITERATOR_DEBUG_LEVEL_MISMATCH -D_ALLOW_MSC_VER_MISMATCH -D_CRTBLD -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_CRT_STDIO_ISO_WIDE_SPECIFIERS -D_GLIBCXX_ASSERTIONS -D_LIBCPP_BUILDING_LIBRARY -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS="" -D_LIBCPP_HAS_NO_PRAGMA_SYSTEM_HEADER -D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -IC:/b/s/w/ir/x/w/llvm-llvm-project/libcxx/src -IC:/b/s/w/ir/x/w/llvm_build/include/x86_64-pc-windows-msvc/c++/v1 -IC:/b/s/w/ir/x/w/llvm_build/include/c++/v1 /Zc:inline /Zc:__cplusplus /Oi /bigobj /permissive- /W4 -wd4141 -wd4146 -wd4244 -wd4267 -wd4291 -wd4351 -wd4456 -wd4457 -wd4458 -wd4459 -wd4503 -wd4624 -wd4722 -wd4100 -wd4127 -wd4512 -wd4505 -wd4610 -wd4510 -wd4702 -wd4245 -wd4706 -wd4310 -wd4701 -wd4703 -wd4389 -wd4611 -wd4805 -wd4204 -wd4577 -wd4091 -wd4592 -wd4319 -wd4709 -wd5105 -wd4324 -w14062 -we4238 /Gw -no-canonical-prefixes /Zi /O2 /Ob1  -std:c++latest -MT -UNDEBUG -W4 -Wextra -Wnewline-eof -Wshadow -Wwrite-strings -Wno-unused-parameter -Wno-long-long -Werror=return-type -Wextra-semi -Wundef -Wunused-template -Wformat-nonliteral -Wno-user-defined-literals -Wno-covered-switch-default -Wno-suggest-override -Wno-c++98-compat -Wno-c++98-compat-pedantic -Wno-c++11-compat -Wno-undef -Wno-reserved-id-macro -Wno-gnu-include-next -Wno-gcc-compat -Wno-zero-as-null-pointer-constant -Wno-deprecated-dynamic-exception-spec -Wno-sign-conversion -Wno-old-style-cast -Wno-deprecated -Wno-shift-sign-overflow -Wno-double-promotion -Wno-error -EHsc /showIncludes /Folibcxx/src/CMakeFiles/cxx_static.dir/support/win32/thread_win32.cpp.obj /Fdlibcxx\src\CMakeFiles\cxx_static.dir\cxx_static.pdb -c -- C:/b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/support/win32/thread_win32.cpp
In file included from C:/b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/support/win32/thread_win32.cpp:14:
In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\fibersapi.h:18:
In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\shared\minwindef.h:182:
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\winnt.h(173,2): error: "No Target Architecture"
  173 | #error "No Target Architecture"
      |  ^
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\winnt.h(8906,5): error: unknown type name 'PCONTEXT'; did you mean '_CONTEXT'?
 8906 |     PCONTEXT ContextRecord;
      |     ^
C:\b\s\w\ir\cache\windows_sdk\VC\Tools\MSVC\14.34.31933\include\excpt.h(49,16): note: '_CONTEXT' declared here
   49 |         struct _CONTEXT;
      |                ^
In file included from C:/b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/support/win32/thread_win32.cpp:14:
In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\fibersapi.h:18:
In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\shared\minwindef.h:182:
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\winnt.h(8906,14): error: field has incomplete type '_CONTEXT'
 8906 |     PCONTEXT ContextRecord;
      |              ^
C:\b\s\w\ir\cache\windows_sdk\VC\Tools\MSVC\14.34.31933\include\excpt.h(49,16): note: forward declaration of '_CONTEXT'
   49 |         struct _CONTEXT;
      |                ^
In file included from C:/b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/support/win32/thread_win32.cpp:14:
In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\fibersapi.h:18:
In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\shared\minwindef.h:182:
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\winnt.h(19329,11): error: unknown type name 'PCONTEXT'; did you mean '_CONTEXT'?
 19329 |     _Out_ PCONTEXT ContextRecord
       |           ^
C:\b\s\w\ir\cache\windows_sdk\VC\Tools\MSVC\14.34.31933\include\excpt.h(49,16): note: '_CONTEXT' declared here
   49 |         struct _CONTEXT;
      |                ^
In file included from C:/b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/support/win32/thread_win32.cpp:14:
In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\fibersapi.h:18:
In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\shared\minwindef.h:182:
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\winnt.h(19980,11): error: unknown type name 'PSLIST_HEADER'
 19980 |     _Out_ PSLIST_HEADER ListHead
       |           ^
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\winnt.h(19988,16): error: unknown type name 'SLIST_HEADER'
 19988 |     _In_ const SLIST_HEADER *ListHead
       |                ^
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\winnt.h(19995,13): error: unknown type name 'PSLIST_HEADER'
 19995 |     _Inout_ PSLIST_HEADER ListHead
       |             ^
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\winnt.h(20002,13): error: unknown type name 'PSLIST_HEADER'
 20002 |     _Inout_ PSLIST_HEADER ListHead,
       |             ^
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\winnt.h(20010,13): error: unknown type name 'PSLIST_HEADER'
 20010 |     _Inout_ PSLIST_HEADER ListHead,
       |             ^
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\winnt.h(20020,13): error: unknown type name 'PSLIST_HEADER'
 20020 |     _Inout_ PSLIST_HEADER ListHead
       |             ^
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\winnt.h(20027,10): error: unknown type name 'PSLIST_HEADER'
 20027 |     _In_ PSLIST_HEADER ListHead
       |          ^
In file included from C:/b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/support/win32/thread_win32.cpp:16:
In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\windows.h:172:
In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\winbase.h:35:
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\minwinbase.h(384,9): error: unknown type name 'PCONTEXT'; did you mean '_CONTEXT'?
  384 | typedef PCONTEXT LPCONTEXT;
      |         ^
C:\b\s\w\ir\cache\windows_sdk\VC\Tools\MSVC\14.34.31933\include\excpt.h(49,16): note: '_CONTEXT' declared here
   49 |         struct _CONTEXT;
      |                ^
In file included from C:/b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/support/win32/thread_win32.cpp:16:
In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\windows.h:172:
In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\winbase.h:47:
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\errhandlingapi.h(214,14): error: unknown type name 'PCONTEXT'
  214 |     _In_opt_ PCONTEXT pContextRecord,
      |              ^
In file included from C:/b/s/w/ir/x/w/llvm-llvm-project/libcxx/src/support/win32/thread_win32.cpp:16:
In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\windows.h:172:
In file included from C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\winbase.h:54:
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\interlockedapi.h(53,11): error: unknown type name 'PSLIST_HEADER'
   53 |     _Out_ PSLIST_HEADER ListHead
      |           ^
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\interlockedapi.h(61,13): error: unknown type name 'PSLIST_HEADER'
   61 |     _Inout_ PSLIST_HEADER ListHead
      |             ^
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\interlockedapi.h(69,13): error: unknown type name 'PSLIST_HEADER'
   69 |     _Inout_ PSLIST_HEADER ListHead,
      |             ^
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\interlockedapi.h(82,13): error: unknown type name 'PSLIST_HEADER'
   82 |     _Inout_ PSLIST_HEADER ListHead,
      |             ^
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\interlockedapi.h(95,13): error: unknown type name 'PSLIST_HEADER'
   95 |     _Inout_ PSLIST_HEADER ListHead
      |             ^
C:\b\s\w\ir\cache\windows_sdk\Windows Kits\10\Include\10.0.19041.0\um\interlockedapi.h(103,10): error: unknown type name 'PSLIST_HEADER'
  103 |     _In_ PSLIST_HEADER ListHead
      |          ^
fatal error: too many errors emitted, stopping now [-ferror-limit=]
20 errors generated.
```

**Comment by petrhosek** [comment]
It looks like the formatting changed the order of includes in `libcxx/src/support/win32/thread_win32.cpp`:
```diff
- #include <windows.h>
- #include <process.h>
#include <fibersapi.h>
+ #include <process.h>
+ #include <windows.h>
```
I didn't have a chance to verify this locally yet, but I suspect this is the culprit.

**Comment by philnik777** [comment]
@petrhosek I just looked and thought the same. If this is actually the problem, IMO it's kinda insane that the windows headers don't properly IWYU. Would be great if you could check it out and make a patch to fix it if that's actually the problem. I'd rather avoid reverting any re-applying this patch.

**Comment by ldionne** [comment]
@petrhosek Thanks, I just did de5c49f7e63f3237afe1e647d359cb8a5227ba4d to try and make the build green again. Let me know if you still see issues.

**Comment by DimitryAndric** [comment]
On Windows, `<windows.h>` is pretty special, it must usually be the first included header (at least, of the Win32 API related headers). I'm unsure if clang-format can be convinced to never alphabetically sort it.

**Comment by petrhosek** [comment]
> @petrhosek Thanks, I just did [de5c49f](https://github.com/llvm/llvm-project/commit/de5c49f7e63f3237afe1e647d359cb8a5227ba4d) to try and make the build green again. Let me know if you still see issues.

Thanks @ldionne, that resolved the issue.

I looked into solutions, and the only two options I found are to either disable Clang-Format:
```
// clang-format off
#include <windows.h>
#include <process.h>
// clang-format on
```
or to move `<windows.h>` into a separate group:
```
#include <windows.h>

#include <process.h>
```

**Pull request merged**
