### PR TITLE
[SandboxIR] Add extern templates for GlobalWithNodeAPI

### PR DESCRIPTION
**Pull request by fsfod**
These symbols will need to be explicitly exported for SandboxIRTests when LLVM is built as shared library on window with explicitly visibility macros are enabled.

This is part of the work to enable LLVM_BUILD_LLVM_DYLIB and plugins on window.

### CODE REVIEW

**Comment by vporpo** [comment]
I am trying to understand why these would need to be explicitly exported for SandboxIRTests. The tests don't use the template directly.

There are other similar CRTPs, like the `SingleLLVMInstructionImpl` in `llvm//SandboxIR/Instruction.h`, would they also need to be explicitly exported too?

**Comment by fsfod** [comment]
idk if this helps much but these are the linker errors i get without this change, this is a debug build so a lot of stuff is not inlined:
```
llvm\lld-link : error : undefined symbol: public: class llvm::sandboxir::GlobalIFunc & __cdecl llvm::sandboxir::GlobalWithNodeAPI<class llvm::sandboxir::GlobalIFunc, class llvm::GlobalIFunc, class llvm::sandboxir::GlobalObject, class llvm::GlobalObject>::LLVMGVToGV::operator()(class llvm::GlobalIFunc &) const
  >>> referenced by llvm\include\llvm\ADT\STLExtras.h:363
  >>>               unittests\SandboxIR\CMakeFiles\SandboxIRTests.dir\SandboxIRTest.cpp.obj:(public: class llvm::sandboxir::GlobalIFunc & __cdecl llvm::mapped_iterator<class llvm::ilist_iterator<struct llvm::ilist_detail::node_options<class llvm::GlobalIFunc, 1, 0, void, 0, void>, 0, 0>, struct llvm::sandboxir::GlobalWithNodeAPI<class llvm::sandboxir::GlobalIFunc, class llvm::GlobalIFunc, class llvm::sandboxir::GlobalObject, class llvm::GlobalObject>::LLVMGVToGV, class llvm::sandboxir::GlobalIFunc &>::operator*(void) const)
  >>> referenced by llvm\include\llvm\ADT\STLExtras.h:363
  >>>               unittests\SandboxIR\CMakeFiles\SandboxIRTests.dir\SandboxIRTest.cpp.obj:(public: class llvm::sandboxir::GlobalIFunc & __cdecl llvm::mapped_iterator<class llvm::ilist_iterator<struct llvm::ilist_detail::node_options<class llvm::GlobalIFunc, 1, 0, void, 0, void>, 1, 0>, struct llvm::sandboxir::GlobalWithNodeAPI<class llvm::sandboxir::GlobalIFunc, class llvm::GlobalIFunc, class llvm::sandboxir::GlobalObject, class llvm::GlobalObject>::LLVMGVToGV, class llvm::sandboxir::GlobalIFunc &>::operator*(void) const)
  
llvm\lld-link : error : undefined symbol: public: class llvm::sandboxir::GlobalVariable & __cdecl llvm::sandboxir::GlobalWithNodeAPI<class llvm::sandboxir::GlobalVariable, class llvm::GlobalVariable, class llvm::sandboxir::GlobalObject, class llvm::GlobalObject>::LLVMGVToGV::operator()(class llvm::GlobalVariable &) const
  >>> referenced by llvm\include\llvm\ADT\STLExtras.h:363
  >>>               unittests\SandboxIR\CMakeFiles\SandboxIRTests.dir\SandboxIRTest.cpp.obj:(public: class llvm::sandboxir::GlobalVariable & __cdecl llvm::mapped_iterator<class llvm::ilist_iterator<struct llvm::ilist_detail::node_options<class llvm::GlobalVariable, 1, 0, void, 0, void>, 0, 0>, struct llvm::sandboxir::GlobalWithNodeAPI<class llvm::sandboxir::GlobalVariable, class llvm::GlobalVariable, class llvm::sandboxir::GlobalObject, class llvm::GlobalObject>::LLVMGVToGV, class llvm::sandboxir::GlobalVariable &>::operator*(void) const)
  >>> referenced by llvm\include\llvm\ADT\STLExtras.h:363
  >>>               unittests\SandboxIR\CMakeFiles\SandboxIRTests.dir\SandboxIRTest.cpp.obj:(public: class llvm::sandboxir::GlobalVariable & __cdecl llvm::mapped_iterator<class llvm::ilist_iterator<struct llvm::ilist_detail::node_options<class llvm::GlobalVariable, 1, 0, void, 0, void>, 1, 0>, struct llvm::sandboxir::GlobalWithNodeAPI<class llvm::sandboxir::GlobalVariable, class llvm::GlobalVariable, class llvm::sandboxir::GlobalObject, class llvm::GlobalObject>::LLVMGVToGV, class llvm::sandboxir::GlobalVariable &>::operator*(void) const)
  
llvm\lld-link : error : undefined symbol: public: class llvm::sandboxir::GlobalAlias & __cdecl llvm::sandboxir::GlobalWithNodeAPI<class llvm::sandboxir::GlobalAlias, class llvm::GlobalAlias, class llvm::sandboxir::GlobalValue, class llvm::GlobalValue>::LLVMGVToGV::operator()(class llvm::GlobalAlias &) const
  >>> referenced by llvm\include\llvm\ADT\STLExtras.h:363
  >>>               unittests\SandboxIR\CMakeFiles\SandboxIRTests.dir\SandboxIRTest.cpp.obj:(public: class llvm::sandboxir::GlobalAlias & __cdecl llvm::mapped_iterator<class llvm::ilist_iterator<struct llvm::ilist_detail::node_options<class llvm::GlobalAlias, 1, 0, void, 0, void>, 0, 0>, struct llvm::sandboxir::GlobalWithNodeAPI<class llvm::sandboxir::GlobalAlias, class llvm::GlobalAlias, class llvm::sandboxir::GlobalValue, class llvm::GlobalValue>::LLVMGVToGV, class llvm::sandboxir::GlobalAlias &>::operator*(void) const)
  >>> referenced by llvm\include\llvm\ADT\STLExtras.h:363
  >>>               unittests\SandboxIR\CMakeFiles\SandboxIRTests.dir\SandboxIRTest.cpp.obj:(public: class llvm::sandboxir::GlobalAlias & __cdecl llvm::mapped_iterator<class llvm::ilist_iterator<struct llvm::ilist_detail::node_options<class llvm::GlobalAlias, 1, 0, void, 0, void>, 1, 0>, struct llvm::sandboxir::GlobalWithNodeAPI<class llvm::sandboxir::GlobalAlias, class llvm::GlobalAlias, class llvm::sandboxir::GlobalValue, class llvm::GlobalValue>::LLVMGVToGV, class llvm::sandboxir::GlobalAlias &>::operator*(void) const)
  
llvm\lld-link : error : undefined symbol: public: class llvm::sandboxir::Function & __cdecl llvm::sandboxir::GlobalWithNodeAPI<class llvm::sandboxir::Function, class llvm::Function, class llvm::sandboxir::GlobalObject, class llvm::GlobalObject>::LLVMGVToGV::operator()(class llvm::Function &) const
  >>> referenced by llvm\include\llvm\ADT\STLExtras.h:363
  >>>               unittests\SandboxIR\CMakeFiles\SandboxIRTests.dir\SandboxIRTest.cpp.obj:(public: class llvm::sandboxir::Function & __cdecl llvm::mapped_iterator<class llvm::ilist_iterator<struct llvm::ilist_detail::node_options<class llvm::Function, 1, 0, void, 0, void>, 0, 0>, struct llvm::sandboxir::GlobalWithNodeAPI<class llvm::sandboxir::Function, class llvm::Function, class llvm::sandboxir::GlobalObject, class llvm::GlobalObject>::LLVMGVToGV, class llvm::sandboxir::Function &>::operator*(void) const)
  >>> referenced by llvm\include\llvm\ADT\STLExtras.h:363
  >>>               unittests\SandboxIR\CMakeFiles\SandboxIRTests.dir\SandboxIRTest.cpp.obj:(public: class llvm::sandboxir::Function & __cdecl llvm::mapped_iterator<class llvm::ilist_iterator<struct llvm::ilist_detail::node_options<class llvm::Function, 1, 0, void, 0, void>, 1, 0>, struct llvm::sandboxir::GlobalWithNodeAPI<class llvm::sandboxir::Function, class llvm::Function, class llvm::sandboxir::GlobalObject, class llvm::GlobalObject>::LLVMGVToGV, class llvm::sandboxir::Function &>::operator*(void) const)
 ```

> There are other similar CRTPs, like the `SingleLLVMInstructionImpl` in `llvm//SandboxIR/Instruction.h`, would they also need to be explicitly exported too?

I think those might of got exported from visibility macros that will be added on classes that derived from an instantiation of them like here https://github.com/fsfod/llvm-project/blob/fdf88b914978d57c6c75892a3133d4476b8995d1/llvm/include/llvm/SandboxIR/Instruction.h#L411 I just didn't want add them all in this PR.

**Review by vporpo — APPROVED** [review]
LG, please add a brief comment that this is for `LLVM_BUILD_LLVM_DYLIB`.

**Comment by bogner** [comment]
This doesn't look right - why do we instantiate each of these templates twice? I'm seeing warnings from clang-cl now since there are duplicate instantiations between `Constant.h` and `Constant.cpp`.

```
llvm/lib/SandboxIR/Constant.cpp(309,52): error: duplicate explicit instantiation of 'operator()' ignored as a Microsoft extension [-Werror,-Wmicrosoft-template]
  309 |                   llvm::GlobalObject>::LLVMGVToGV::operator()(llvm::GlobalIFunc
      |                                                    ^
llvm/include\llvm/SandboxIR/Constant.h(804,52): note: previous explicit instantiation is here
  804 |                   llvm::GlobalObject>::LLVMGVToGV::operator()(llvm::GlobalIFunc
      |                                                    ^
```

**Comment by fsfod** [comment]
I have double checked again for shared library debug builds with clang-cl and the template function symbols are not exported without them being explicitly exported from the source file, explicit template instantiation of containing classes is not enough. I could add some clang warning suppression macros around them though. 
My branch with all my stuff still to merge just for clang-cl is [here ](https://github.com/fsfod/llvm-project/commits/exported-api/llvm-20-clang-cl/) that I checked with.

**Comment by bogner** [comment]
Do they need to be explicitly exported in both the header and the source file? That doesn't make a lot of sense to me. The instantiations look identical, as the warning implies.

**Pull request merged**
