### PR TITLE
[clang][RISCV] Make the index of riscv_tuple_extract and riscv_tuple_insert be truncated rather than zero extended

### PR DESCRIPTION
**Pull request by 4vtomat**
It's illegal if the index is 64 bits and is zero-extend to 32 bits.

### CODE REVIEW

**Comment by topperc** [comment]
test?

**Comment by 4vtomat** [comment]
> test?

Added!

**Review by wangpc-pp — APPROVED** [review]
LGTM.

**Review by topperc — APPROVED** [review]
LGTM

**Pull request merged**
