### PR TITLE
[RISCV] Add IsSignExtendingOpW to AMO*_W instructions.

### PR DESCRIPTION
**Pull request by topperc**
The amo*.w instructions return a sign extended value like other W instructions. Adding IsSignExtendingOpW allows RISCVOptWInstrs to remove sext.w instructions that extend results from these operations.

### CODE REVIEW

**Comment by dtcxzyw** [comment]
I think it also holds for `lr.w` and `amocas.w`.

**Comment by topperc** [comment]
> I think it also holds for `lr.w` and `amocas.w`.
> 
> 

Do lr.w instructions exist at that point in the pipeline?

**Comment by dtcxzyw** [comment]
> > I think it also holds for `lr.w` and `amocas.w`.
> 
> Do lr.w instructions exist at that point in the pipeline?

`lr.w` is generated during the atomic pseudo instruction expansion. Sorry for my mistake.

**Review by asb — APPROVED** [review]
LGTM. I think there's an argument for adding IsSignExtendingOpW for instructions with that property even if it makes no difference in the current codegen pipeline. But happy to defer to your preference.

**Comment by topperc** [comment]
Committed as e12677db8b1a5c2a7136f6089644d52c87be81d3 and 1c033aaac97ed44b5efb2c472e6f1fe76303a682

**Pull request closed without merging**
