### PR TITLE
[OpenMP] Fix target data region codegen being omitted for device pass

### PR DESCRIPTION
**Pull request by TIFitis**
This patch enables the BodyCodeGen callback to still trigger for the TargetData nested region during the device pass. There maybe Target code nested within the TargetData region for which this is required.

Also add tests for the same.

### CODE REVIEW

**Review by agozillon — APPROVED** [review]
This LGTM, minus the code formatter issues! Please do wait on a secondary review though. It would also be very cool to have another runtime test or two as well, just to see if we can dig up any other issues if they exist or get a little more code coverage. But that's only if you wish to do so, I imagine there's other more critical things to be done elsewhere.

**Comment by skatrak** [comment]
Thanks Akash, it looks ok for me as well, but I'm missing one OMPIRBuilder test to check not just the overall behavior but also the IR produced (llvm/unittests/Frontend/OpenMPIRBuilderTest.cpp).

**Review by skatrak — APPROVED** [review]
Thank you Akash, LGTM. Could you add a brief commit description before you merge?

**Comment by jdoerfert** [comment]
> This patch enables the BodyCodeGen callback to still trigger for the TargetData nested region during the device pass. There maybe Target code nested within the TargetData region for which this is required.

Could you elaborate on this? What code associated with the target data is required on the device? That doesn't connect in my mind and I'm worried this hides a different problem.
The test doesn't help me understand what happened before either.

**Comment by TIFitis** [comment]
> Could you elaborate on this? What code associated with the target data is required on the device? That doesn't connect in my mind and I'm worried this hides a different problem. The test doesn't help me understand what happened before either.

Take the following test:
```
!$omp target data map(to: A, B) map(alloc: C)
!$omp target
  do I = 1, 10
     C(I) = A(I) + B(I) ! assigns 3, A:1 + B:2
  end do
!$omp end target
!$omp end target data
```

We don't need to emit any code for target data on the device pass, but the target directive nested inside it needs device pass codegen. By not having the BodyGenCB callback, we were omitting this codegen which this patch brings back.

Note that both Clang and Flang don't actually emit any code for the target data region unless it is target code.

The following example still doesn't produce any code for the device pass related to target data or it's nested region.
```
!$omp target data map(to: A, B) map(alloc: C)
  do I = 1, 10
     C(I) = A(I) + B(I) ! assigns 3, A:1 + B:2
  end do
!$omp end target data
```

**Comment by skatrak** [comment]
This seems to be yet another manifestation of this problem: #85239, #84611. It appears the workaround implemented in this patch wouldn't be needed (at least for Flang) after solving the problem of skipping host operations during device compilation while still processing target regions nested inside them.

**Pull request merged**
