### PR TITLE
release/19.x: [MIPS] Optimize sortRelocs for o32

### PR DESCRIPTION
**Pull request by alexrp**
Manual backport of #104723.

### CODE REVIEW

**Comment by alexrp** [comment]
cc @MaskRay @brad0

**Comment by tru** [comment]
I am not convinced that we should take something that's a pure optimization between RC3 and final unless this is fixing a regression or is very important. I want to avoid risk now so that we don't end up making things worse for the final release.

**Comment by alexrp** [comment]
@tru please see the numbers in https://github.com/llvm/llvm-project/issues/104562#issue-2469758971. The Zig project has no choice but to keep all MIPS32 testing (both local and in CI) disabled until this fix is in effect. So I'd say it's reasonably important.

**Comment by tru** [comment]
It seems like this was present in LLVM 18.x as well? so it's not in a strict sense a regression? what's the risk of taking this on? @brad0 @MaskRay ?

**Comment by alexrp** [comment]
Yeah, this has been an issue for a while AIUI.

I don't think it affects C/C++ projects in general because of separate compilation. Zig, OTOH, uses a compilation model that's more like a "unity build", which results in tons of relocations in the single module that goes through `MipsELFObjectWriter`, so we're really badly affected by this. It's only recently that we've started getting our MIPS port up to a high standard of quality, so it's hurting us quite a bit now that we actually want to do regular testing for it.

**Comment by alexrp** [comment]
Has a decision been reached on this? (Not familiar with how exactly the process works.)

Also, even if this doesn't make it for 19.1.0-final, can it be considered for a subsequent bug fix release?

**Comment by tru** [comment]
I would still like a domain expert to weigh in.

**Comment by tru** [comment]
@MaskRay @topperc maybe? what do you think about merging this?

**Comment by alexrp** [comment]
@MaskRay @topperc @wzssyqa @yingopq sorry for the pings, but I assume today is the last chance to get this in, so I would love to hear your thoughts on whether you think that's a good idea. :slightly_smiling_face:

**Comment by wzssyqa** [comment]
I don't think that it is a bugfix, thus not need to be backported.

**Comment by tru** [comment]
Yeah I tend to agree that this is a seemingly nice to have thing, but it's not really qualifying for a bugfix or a regression.

**Comment by alexrp** [comment]
Definitely agree it's not a regression, but I think I would quibble a bit with the idea that taking ~1h6min to compile something that normally takes ~3min is not a bug in some sense. :slightly_smiling_face:

But ok, philosophical debates aside: Would it be reasonable to at least consider it a [critical performance issue for the purposes of a bug fix release](https://github.com/llvm/llvm-project/blob/main/llvm/docs/HowToReleaseLLVM.rst#release-patch-rules)? I acknowledge that there'd still need to be an assessment as to whether the patch is safe, but it *seems* like it should at least fit one of the criteria on its face. In regards to safety, perhaps confidence in the patch would increase in the time between 19.1.0-final and the subsequent bug fix releases?

**Comment by wzssyqa** [comment]
> Definitely agree it's not a regression, but I think I would quibble a bit with the idea that taking ~1h6min to compile something that normally takes ~3min is not a bug in some sense. 🙂
> 

If so, then I think that it is a real bug ;)

> But ok, philosophical debates aside: Would it be reasonable to at least consider it a [critical performance issue for the purposes of a bug fix release](https://github.com/llvm/llvm-project/blob/main/llvm/docs/HowToReleaseLLVM.rst#release-patch-rules)? I acknowledge that there'd still need to be an assessment as to whether the patch is safe, but it _seems_ like it should at least fit one of the criteria on its face. In regards to safety, perhaps confidence in the patch would increase in the time between 19.1.0-final and the subsequent bug fix releases?

**Comment by nikic** [comment]
I don't think this should be backported in the current form, because it breaks ABI. This is not strictly impossible at this stage, but also very undesirable.

**Comment by tru** [comment]
This will have to wait for LLVM 20. I know it's not optimal for zig, but getting it in this late and it being abi breaking is tricky.

**Pull request closed without merging**
