### PR TITLE
[DAGCombiner][RISCV] Prefer to sext i32 non-negative values

### PR DESCRIPTION
**Pull request by dtcxzyw**
By default, `DAGCombiner` folds `sext x` to `zext x` when `x` is non-negative. It will generate redundant `zext` inst seq on riscv64 (typically `slli (srli x, 32), 32`).
godbolt: https://godbolt.org/z/osf6adP1o
This patch applies the transform iff `zext` is **cheaper** than `sext`.

### CODE REVIEW

**Review by RKSimon — APPROVED** [review]
LGTM

**Comment by topperc** [comment]
InstCombine does the same thing. Do we need a reverse transform to turn zext into sext explicitly? Or perhaps an isel pattern?

**Comment by dtcxzyw** [comment]
> InstCombine does the same thing. 

I think you mean ISel. https://github.com/llvm/llvm-project/blob/231aa0f2120552b474bf86d5ff6721a6c555fdc3/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp#L6072

> Do we need a reverse transform to turn zext into sext explicitly? Or perhaps an isel pattern?

It is unsafe to turn `zext` into `sext`. Why not just prevent tuning `zext` into `sext`?

**Comment by topperc** [comment]
> > InstCombine does the same thing. 
> 
> 
> 
> I think you mean ISel. https://github.com/llvm/llvm-project/blob/231aa0f2120552b474bf86d5ff6721a6c555fdc3/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp#L6072
> 
> 
> 
> > Do we need a reverse transform to turn zext into sext explicitly? Or perhaps an isel pattern?
> 
> 
> 
> It is unsafe to turn `zext` into `sext`. Why not just prevent tuning `zext` into `sext`?
> 
> 

visitSExt in InstCombine will turn sext into zext. That code will happen before DAGCombine. The DAGCombine change will only effect sext that is created during SelectionDAG. sext that already existed in IR may get changed by InstCombine.

So my question was do we need to change zext to sext if the sign bit of the input is known to be 0 by computeKnownBits.

**Comment by dtcxzyw** [comment]
https://github.com/llvm/llvm-project/blob/c464896dbe2ad5a8641a675fff525656e88be38a/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp#L1375-L1377

**Comment by dtcxzyw** [comment]
Diff: https://github.com/llvm/llvm-project/compare/main...dtcxzyw:llvm-project:zext-to-sext
Evaluation result: https://github.com/dtcxzyw/llvm-ci/pull/627

It seems better to sext a non-negative value on riscv64. But this change broke some regression tests.

**Pull request merged**
