### PR TITLE
[libc][test] Adjust header paths in tests

### PR DESCRIPTION
**Pull request by Caslyn**
Since `index_test.cpp` and `rindex_test.cpp` now reside in /strings, adjust some header paths accordingly.

Link: #118899

### CODE REVIEW

**Review by nickdesaulniers — APPROVED** [review]
Thanks for the fix!

Did you happen to spot this via a build breakage, per chance?  I don't have any build breakages on my end, but that's making me think I should go investigate why that would be.

**Comment by nickdesaulniers** [comment]
`ninja libc-strings-tests` doesn't appear to be building/running the index/rindex tests...uh oh

**Comment by nickdesaulniers** [comment]
Do you mind folding this diff into your patch?

```diff
diff --git a/libc/test/src/strings/CMakeLists.txt b/libc/test/src/strings/CMakeLists.txt
index 963a1d6d6d60..10f96b8531f6 100644
--- a/libc/test/src/strings/CMakeLists.txt
+++ b/libc/test/src/strings/CMakeLists.txt
@@ -20,7 +20,7 @@ add_libc_test(
     index_test.cpp
   DEPENDS
     libc.src.strings.index
-    libc.test.src.strchr_test_support
+    libc.test.src.string.strchr_test_support
 )
 
 add_libc_test(
@@ -31,7 +31,7 @@ add_libc_test(
     rindex_test.cpp
   DEPENDS
     libc.src.strings.rindex
-    libc.test.src.strchr_test_support
+    libc.test.src.string.strchr_test_support
 )
 
 add_libc_test(

```
otherwise I'll send a new PR for it.

**Comment by Caslyn** [comment]
> Did you happen to spot this via a build breakage, per chance? I don't have any build breakages on my end, but that's making me think I should go investigate why that would be.

Only actually spotted this while adjusting our build targets down stream in Fuchsia to match the /string -> /strings move.

**Pull request merged**
