### PR TITLE
[test][asan] Check for order of DynInitPoison

### PR DESCRIPTION
**Pull request by vitalybuka**
Also make sure we have dynamic init variables with any `-O`.

### CODE REVIEW

**Review by thurstond — APPROVED** [review]

**Comment by mstorsjo** [comment]
These new tests seem to fail on mingw targets - see https://github.com/mstorsjo/llvm-mingw/actions/runs/10223903341/job/28296084101 for a failed run.

It looks like the output is
```
DynInitPoison module: D:\a\llvm-mingw\llvm-mingw\llvm-project\compiler-rt\test\asan\TestCases/Helpers/initialization-nobug-extra.cpp
DynInitUnpoison
DynInitPoison module: D:\a\llvm-mingw\llvm-mingw\llvm-project\compiler-rt\test\asan\TestCases\initialization-nobug.cpp
DynInitUnpoison
```
while we expect them to come in the reverse order.

So I guess that sounds like a real bug on this target (CC @alvinhochun) - I guess we'll need to XFAIL this target in the test to keep the testsuite running though.

**Comment by alvinhochun** [comment]
This looks like the test is expecting the static initialization to be done in a specific order (first `initialization-nobug.cpp` then `initialization-nobug-extra.cpp`), but the order of static initialization in different TUs is unspecified, isn't it? So it doesn't seem to be a bug with the mingw-w64 target, just that the ordering of functions in the combined `.ctors` section and that the list is executed backwards on mingw-w64 CRT, is making it behave differently compared to Linux and even MSVC targets.

**Comment by mstorsjo** [comment]
> This looks like the test is expecting the static initialization to be done in a specific order (first `initialization-nobug.cpp` then `initialization-nobug-extra.cpp`), but the order of static initialization in different TUs is unspecified, isn't it? So it doesn't seem to be a bug with the mingw-w64 target, just that the ordering of functions in the combined `.ctors` section and that the list is executed backwards on mingw-w64 CRT, is making it behave differently compared to Linux and even MSVC targets.

Thanks! So if we could make the test tolerate these two lines in any order (`CHECK-DAG:` maybe?), it'd work? But that's probably a bit harder when we want to check that we have the `DynInitUnpoison` lines inbetween...

**Comment by alvinhochun** [comment]
Though thinking about it, aren't these DynInitPoison stuff supposed to catch static initialization order fiasco? If they end up being interleaved together with regular C++ dynamic initialization then it seems it won't actually catch anything, which may indeed be a bug.

I thought the ASan runtime use the CRT sections `.CRT$XIA`~`.CRT$XIZ` (or something like that) to initialize things? Those should be executed before `.ctors`, no?

**Comment by vitalybuka** [comment]
Off-cause we con't care about particular order of DynInitPoison.
Fixing.

Thanks!

**Comment by mstorsjo** [comment]
> Of cause we don't care about particular order of DynInitPoison. Fixing.
> 
> Thanks!

Thanks for the quick fix!

**Pull request merged**
