### PR TITLE
[mlir][test] Rename Vector integration tests for CPU (nfc)

### PR DESCRIPTION
**Pull request by banach-space**
To keep the test filenames consistent, this patch:
  * removes "test-" from  file names (there used to be a mix of
    "test-feature-1.mlir" and "feature-2.mlir"),
  * replaces "_" with "-" (there used to be a mix of "feature-3.mlir"
    and "feature_4.mlir").

Only files under test/Integration/Dialect/Vector/CPU are updated.

### CODE REVIEW

**Comment by c-rhodes** [comment]
For SME the early integration tests I added like `tile_fill.mlir` didn't have the `test-` prefix but once I realised the target agnostic Vector dialect integration tests have that prefix I started adding it for consistency. I have no strong preference either way but consistency would be good.

**Comment by MacDue** [comment]
Unless we want to change the vector dialect tests too, I think it'd be easier to be consistent with the vector tests.

**Comment by banach-space** [comment]
Thanks for taking a look! 

Consistency is important, I agree. Re  tests in "mlir/test/Integration/Dialect/Vector/CPU/", I suggest renaming those tests as well. 

IMHO, adding "test-" to filenames inside a **test** directory is noise that can be avoided. The information that these files are **test** files is already encoded in the directory name - no need to repeat that in the filename.

**Comment by c-rhodes** [comment]
> Thanks for taking a look!
> 
> Consistency is important, I agree. Re tests in "mlir/test/Integration/Dialect/Vector/CPU/", I suggest renaming those tests as well.

👍

~40% of the integration tests (118/303) have the prefix, not sure how far you want to take it.

> 
> IMHO, adding "test-" to filenames inside a **test** directory is noise that can be avoided. The information that these files are **test** files is already encoded in the directory name - no need to repeat that in the filename.

I agree.

**Review by c-rhodes — APPROVED** [review]

**Pull request merged**
