### PR TITLE
DLTI: Simplifying getDevicePropertyValue API by returning Attribute type value

### PR DESCRIPTION
**Pull request by nhasabni**
**Rationale**

- With the current flexibility of supporting any type of value, we will need to offer type-specific APIs to fetch a value (e.g., `getDevicePropertyValueAsInt` for integer type, `getDevicePropertyValueAsFloat` for float type, etc.) A single type of value will eliminate this need.
- Current flexibility can also lead to typing errors when a user fetches the value of a property using an API that is not consistent with the type of the value.

**What is the change**

For following system description,

```
 module attributes {
   dlti.target_system_spec = #dlti.target_system_spec<
     "CPU": #dlti.target_device_spec<
      #dlti.dl_entry<"max_vector_op_width", 64.0 : f32>>,
     "GPU": #dlti.target_device_spec<
      #dlti.dl_entry<"max_vector_op_width", 128 : ui32>>
   >} {}
```

a user no longer needs to use `getDevicePropertyValueAsInt` for retrieving GPU's `max_vector_op_width` and `getDevicePropertyValueAsFloat` for retrieving CPU's `max_vector_op_width`. Instead it can be done with a uniform API of `getDevicePropertyValue`.

### CODE REVIEW

**Comment by joker-eph** [comment]
Please describe the context / motivation in the description (you're nicely saying "what" you're doing here, but not "why", which is in generalthe most important aspect of the description)

**Comment by nhasabni** [comment]
> Please describe the context / motivation in the description (you're nicely saying "what" you're doing here, but not "why", which is in general the most important aspect of the description)

I should have done that before. Sorry. I have updated the description now.

**Comment by joker-eph** [comment]
> With the current flexibility of supporting any type of value, we will need to offer type-specific APIs to fetch a value (e.g., getDevicePropertyValueAsInt for integer type, getDevicePropertyValueAsFloat for float type, etc.) A single type of value will eliminate this need.

Return an `Attribute` also eliminates this need though.

**Comment by nhasabni** [comment]
> > With the current flexibility of supporting any type of value, we will need to offer type-specific APIs to fetch a value (e.g., getDevicePropertyValueAsInt for integer type, getDevicePropertyValueAsFloat for float type, etc.) A single type of value will eliminate this need.
> 
> Return an `Attribute` also eliminates this need though.

Hmm, agree. @rengolin any thoughts?

**Comment by rengolin** [comment]
> > Return an `Attribute` also eliminates this need though.
> 
> Hmm, agree. @rengolin any thoughts?

That would probably be simpler, yeah.

**Comment by nhasabni** [comment]
@joker-eph Returning the value of the property as Attribute now. No more restriction on the type of value supported in the description. Pls check.

**Review by joker-eph — APPROVED** [review]

**Pull request merged**
