### PR TITLE
[SLP] Better way to filter target-specific tests

### PR DESCRIPTION
**Pull request by ElvinaYakubova**
When only an exclusive target e.g AArch64 was enabled, these tests were previously shown as UNSUPPORTED.
This change allows us to run tests for cases with only a build for one target.

### CODE REVIEW

**Comment by alexey-bataev** [comment]
Why it is better?

**Comment by ElvinaYakubova** [comment]
When only an exclusive target e.g AArch64 was enabled, these tests were previously shown as UNSUPPORTED.
This change allows us to run tests for cases where we only have a build for one target.

**Comment by ElvinaYakubova** [comment]
gentle ping

**Review by alexey-bataev — APPROVED** [review]

**Comment by RKSimon** [comment]
@ElvinaYakubova Just checking - does the update_test_checks.py script still work with these?

**Comment by ElvinaYakubova** [comment]
> @ElvinaYakubova Just checking - does the update_test_checks.py script still work with these?

Sorry for a long response, I was on holiday, fixed script in https://github.com/llvm/llvm-project/pull/108972

**Comment by ElvinaYakubova** [comment]
Updates for update_test_checks.py script were merged, so merging these tests now

**Pull request merged**
