### PR TITLE
[clang-repl] Add call to 'InitializeAllAsmParsers'

### PR DESCRIPTION
**Pull request by aytey**
This PR fixes the following issue when working with `clang-repl`:

```
fatal error: error in backend: Inline asm not supported by this streamer because we don't have an asm parser for this target
```

When working with the following input (named "unit.cpp"):

```cpp
__asm(".globl _ZSt21ios_base_library_initv");
int x;
```

and then in `clang-repl`:

```
#include "unit.cpp"
x = 10;
```

Signed-off-by: Andrew V. Teylu <andrew.teylu@vector.com>

### CODE REVIEW

**Comment by aytey** [comment]
This my first PR against LLVM; does something like this need tests? I'm 100% happy to add tests for this, but are there some examples of "good" `clang-repl` tests I can learn from/extend from?

**Comment by aytey** [comment]
> This my first PR against LLVM; does something like this need tests? I'm 100% happy to add tests for this, but are there some examples of "good" `clang-repl` tests I can learn from/extend from?

Maybe this is reasonable:

```cpp
// REQUIRES: host-supports-jit, x86_64-linux
// UNSUPPORTED: system-aix
//
// RUN: rm -rf %t
// RUN: mkdir -p %t
// RUN: split-file %s %t
//
// RUN: cat %t/inline-asm.txt | clang-repl

//--- inline-asm.cpp
__asm(".globl _ZSt21ios_base_library_initv");
int x;

//--- inline-asm.txt
#include "inline-asm.cpp"
x = 10;
%quit
```

**Comment by aytey** [comment]
```avj@host /tmp/clang_build$ ./bin/llvm-lit -v /tmp/llvm-project/clang/test/Interpreter/inline-asm.cpp
llvm-lit: /tmp/llvm-project/llvm/utils/lit/lit/llvm/config.py:502: note: using clang: /tmp/clang_build/bin/clang
-- Testing: 1 tests, 1 workers --
PASS: Clang :: Interpreter/inline-asm.cpp (1 of 1)

Testing Time: 0.10s

Total Discovered Tests: 1
  Passed: 1 (100.00%)
```

**Comment by aytey** [comment]
@weliveindetail @vgvassilev @junaire: sorry for pinging you directly, but could you take a look at this PR? I see you're all active on other `clang-repl` PRs, so thought you might be the best place to start to take a look at this one 🤞

**Comment by junaire** [comment]
> @weliveindetail @vgvassilev @junaire: sorry for pinging you directly, but could you take a look at this PR? I see you're all active on other `clang-repl` PRs, so thought you might be the best place to start to take a look at this one 🤞

Hi, thanks for the PR. I think the change looks reasonable but I'm no longer working on this so I've picked some reviewers for you. They should be able to look at this soon.

**Comment by aytey** [comment]
> > @weliveindetail @vgvassilev @junaire: sorry for pinging you directly, but could you take a look at this PR? I see you're all active on other `clang-repl` PRs, so thought you might be the best place to start to take a look at this one 🤞
> 
> Hi, thanks for the PR. I think the change looks reasonable but I'm no longer working on this so I've picked some reviewers for you. They should be able to look at this soon.

Thank you very much :)

**Review by vgvassilev — APPROVED** [review]
LGTM!

**Review by weliveindetail — APPROVED** [review]
Yes, perfect. Thanks!

**Comment by weliveindetail** [comment]
@aytey We can land patches through GitHub nowadays. Is the `Squash and merge` button accessible for you?

**Comment by aytey** [comment]
> @aytey We can land patches through GitHub nowadays. Is the `Squash and merge` button accessible for you?

Unfortunately, I don't have write access to the repo, so that's not available to me. The only action I have is "update branch".

**Pull request merged**
