### PR TITLE
[lldb] Disable warning about codecvt_utf8 deprecation (NFC)

### PR DESCRIPTION
**Pull request by JDevlieghere**
Disable -Wdeprecated-declarations for codecvt_utf8 in Editline. This is in preparation for #112276 which narrows the scope of -Wno-deprecated-declarations for building LLDB.

### CODE REVIEW

**Comment by JDevlieghere** [comment]
There was an attempt to remove this (https://reviews.llvm.org/D106035) but this hit some issues on Arch and with column counting which is out of scope for what I'm trying to achieve.

**Comment by labath** [comment]
> There was an attempt to remove this (https://reviews.llvm.org/D106035) but this hit some issues on Arch and with column counting which is out of scope for what I'm trying to achieve.

I'm not actually sure the approach in that patch is feasible. Last time I looked at this (which was a long time ago, to be fair), to problem was basically that editline could be built in two modes (wide or not), and we had to do something to match what was being used there.

**Review by labath — COMMENTED** [review]
[this](https://godbolt.org/z/4WsnMvz5G) _might_ be a non-deprecated way of achieving this, though I'm not entirely sure about its portability (windows is the main question, but I guess we don't use editline there anyway). I don't think you have to do that, but it is an option.

**Comment by JDevlieghere** [comment]
> [this](https://godbolt.org/z/4WsnMvz5G) _might_ be a non-deprecated way of achieving this, though I'm not entirely sure about its portability (windows is the main question, but I guess we don't use editline there anyway). I don't think you have to do that, but it is an option.

Thanks, I see you did something similar in `Editline::CompleteCharacter`. Let me know if https://github.com/llvm/llvm-project/pull/112582 matches what you had in mind.

**Review by labath — APPROVED** [review]

**Pull request merged**
