### PR TITLE
[Libomptarget] Minimize use of 'REPORT' in the plugin interface

### PR DESCRIPTION
**Pull request by jhuber6**
Summary:
The `REPORT` macro is coded to `abort()` on non-debug builds. There is a
lot of code scattered around that uses this to spuriously halt execution
in the middle of the plugin. This patch simply tries to replace them
with actual error messages or just consumes them.

The main offender here is the `malloc` and `free` interface. Right now
I'm just consuming them, which is consisent with how `free` and `malloc`
work. But I think the way forward is to make these functions also return
an expected value so users are forced to check it.

### CODE REVIEW

**Comment by jhuber6** [comment]
@ronlieb this should apply cleanly downstream.

**Comment by shiltian** [comment]
The early abortion can help to locate the error much easier because we don't have to wait for the handling of offloading failure that might happen much later than when and where it happens.

**Comment by jhuber6** [comment]
> The early abortion can help to locate the error much easier because we don't have to wait for the handling of offloading failure that might happen much later than when and where it happens.

A runtime rolling over and dying when something goes wrong is generally unacceptable, but currently most of these will still die at the plugin boundary. The one concession is the allocation bits, I could probably keep those messages around with a debugging message. I think in the future we should make these allocation routines return an error as well so it forces the user to handle the `nullptr` case explicitly.

**Comment by shiltian** [comment]
> A runtime rolling over and dying when something goes wrong is generally unacceptable, but currently most of these will still die at the plugin boundary.

I agree. I think generally in debug build we want to abort immediately to make it easy to pinpoint where things start to go south. In release build we can just report the error and return failure, etc., and eventually `libomptarget` will crash due to error.

**Comment by jplehr** [comment]
> > A runtime rolling over and dying when something goes wrong is generally unacceptable, but currently most of these will still die at the plugin boundary.
> 
> I agree. I think generally in debug build we might want to abort immediately to make it easy to pinpoint where things start to go south. In release build we can just report the error and return failure, etc., and eventually `libomptarget` will crash due to error.

With a debug build, do you mean `LIBOMPTARGET_DEBUG` or CMake Debug build?
If we want to go that route, can we potentially not tie the ability to debug-print stuff and die in case of error? I think it would be good to be able to have a debug log w/o enabling dying immediately. Like have `LIBOMPTARGET_DEBUG_ABORT_EARLY` or something.

**Comment by jdoerfert** [comment]
Generally, fewer switches please, especially CMAKE.

I believe this is conceptually the right way to go. That said, our errors are not great, they should contain source information from where they were fired. That would make the pinpointing similarly easy. I can see it might be a little more involved in 1-2 places, but a single consistent error model is better than 2, or more.

**Comment by jhuber6** [comment]
> Generally, fewer switches please, especially CMAKE.
> 
> I believe this is conceptually the right way to go. That said, our errors are not great, they should contain source information from where they were fired. That would make the pinpointing similarly easy. I can see it might be a little more involved in 1-2 places, but a single consistent error model is better than 2, or more.

I've been thinking about this. First off I think we should ditch `LIBOMPTARGET_DEBUG` entirely and just key off of `NDEBUG` like assertions do. Then we can improve the `DP` macro to make it easier to use.

Right now we make every error use `inconvertibleErrorCode()` which could be replaced with an actual value at a minimum. We could also make the interface automatically insert source location information if present. I think the easiest way to do this is to have TLS that contains the source location at a top level, then the rest of the runtime can simply read from it if it's been set. One difficulty would be how to present these errors to the user as part of an API, perhaps we return an index into some table that contains the last error message printed from the error type?

I think we should focus on this once we find a good way to remove the `dlopen` barrier between the plugins, primarily because it would allow us to have a single state space within the library.

That being said, I think this patch is a reasonable step forward. Future work would be an error handling overhaul.

**Pull request closed without merging**
