### PR TITLE
mmapForContinuousMode: Align Linux's impl to __APPLE__'s more. NFC.

### PR DESCRIPTION
**Pull request by chapuni**

### CODE REVIEW

**Comment by ornata** [comment]
Why?

**Comment by chapuni** [comment]
> Why?

"I want to introduce bitmap bias w/o posting RFC."

Rather than appending similar changes (but with different variables) into __linux__ impl, I think it'd be better to align blocks with same variable for possible commonization in the future. It can also make simpler to explain the difference of bitmap between __APPLE__ and bias mode.

To introduce bitmap in biased continuous mode, the bias for counters cannot be reused since the layout of `__llvm_prf_bits` and `__llvm_prf_cnts` is different from `profraw`.

I thought actual commonization would be too early since it would be intrusive.

**Review by ornata — APPROVED** [review]
LGTM

**Comment by ilovepi** [comment]
We're seeing test failures after this patch. Can you please take a look?

Bot: https://ci.chromium.org/ui/p/fuchsia/builders/toolchain.ci/clang-linux-arm64/b8744624520905017585/overview

Error:
```
FAIL: Profile-aarch64 :: ContinuousSyncMode/runtime-counter-relocation.c (2289 of 15086)
******************** TEST 'Profile-aarch64 :: ContinuousSyncMode/runtime-counter-relocation.c' FAILED ********************
Exit Code: 1

Command Output (stderr):
--
RUN: at line 3: /b/s/w/ir/x/w/llvm_build/./bin/clang    -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta   -ldl -fprofile-instr-generate -fcoverage-mapping -mllvm -runtime-counter-relocation=true -o /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins/compiler-rt/test/profile/Profile-aarch64/ContinuousSyncMode/Output/runtime-counter-relocation.c.tmp.exe /b/s/w/ir/x/w/llvm-llvm-project/compiler-rt/test/profile/ContinuousSyncMode/runtime-counter-relocation.c
+ /b/s/w/ir/x/w/llvm_build/./bin/clang -Wthread-safety -Wthread-safety-reference -Wthread-safety-beta -ldl -fprofile-instr-generate -fcoverage-mapping -mllvm -runtime-counter-relocation=true -o /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins/compiler-rt/test/profile/Profile-aarch64/ContinuousSyncMode/Output/runtime-counter-relocation.c.tmp.exe /b/s/w/ir/x/w/llvm-llvm-project/compiler-rt/test/profile/ContinuousSyncMode/runtime-counter-relocation.c
RUN: at line 4: echo "garbage" > /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins/compiler-rt/test/profile/Profile-aarch64/ContinuousSyncMode/Output/runtime-counter-relocation.c.tmp.profraw
+ echo garbage
RUN: at line 5: env LLVM_PROFILE_FILE="%c/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins/compiler-rt/test/profile/Profile-aarch64/ContinuousSyncMode/Output/runtime-counter-relocation.c.tmp.profraw"  /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins/compiler-rt/test/profile/Profile-aarch64/ContinuousSyncMode/Output/runtime-counter-relocation.c.tmp.exe
+ env LLVM_PROFILE_FILE=%c/b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins/compiler-rt/test/profile/Profile-aarch64/ContinuousSyncMode/Output/runtime-counter-relocation.c.tmp.profraw /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins/compiler-rt/test/profile/Profile-aarch64/ContinuousSyncMode/Output/runtime-counter-relocation.c.tmp.exe
RUN: at line 6: llvm-profdata show --counts --all-functions /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins/compiler-rt/test/profile/Profile-aarch64/ContinuousSyncMode/Output/runtime-counter-relocation.c.tmp.profraw | FileCheck /b/s/w/ir/x/w/llvm-llvm-project/compiler-rt/test/profile/ContinuousSyncMode/runtime-counter-relocation.c -check-prefix=CHECK-COUNTS
+ llvm-profdata show --counts --all-functions /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-aarch64-unknown-linux-gnu-bins/compiler-rt/test/profile/Profile-aarch64/ContinuousSyncMode/Output/runtime-counter-relocation.c.tmp.profraw
+ FileCheck /b/s/w/ir/x/w/llvm-llvm-project/compiler-rt/test/profile/ContinuousSyncMode/runtime-counter-relocation.c -check-prefix=CHECK-COUNTS
/b/s/w/ir/x/w/llvm-llvm-project/compiler-rt/test/profile/ContinuousSyncMode/runtime-counter-relocation.c:14:23: error: CHECK-COUNTS-NEXT: expected string not found in input
// CHECK-COUNTS-NEXT: Function count: 1
                      ^
<stdin>:4:13: note: scanning from here
 Counters: 2
            ^
<stdin>:5:2: note: possible intended match here
 Function count: 0
 ^

Input file: <stdin>
Check file: /b/s/w/ir/x/w/llvm-llvm-project/compiler-rt/test/profile/ContinuousSyncMode/runtime-counter-relocation.c

-dump-input=help explains the following input dump.

Input was:
<<<<<<
           1: Counters: 
           2:  main: 
           3:  Hash: 0x000000000a498458 
           4:  Counters: 2 
next:14'0                 X error: no match found
           5:  Function count: 0 
next:14'0     ~~~~~~~~~~~~~~~~~~~
next:14'1      ?                  possible intended match
           6:  Block counts: [0] 
next:14'0     ~~~~~~~~~~~~~~~~~~~
           7: Instrumentation level: Front-end 
next:14'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           8: Functions shown: 1 
next:14'0     ~~~~~~~~~~~~~~~~~~~
           9: Total functions: 1 
next:14'0     ~~~~~~~~~~~~~~~~~~~
          10: Maximum function count: 0 
next:14'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~
          11: Maximum internal block count: 0 
next:14'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
>>>>>>

--

********************
PASS: Profile-aarch64 :: Linux/coverage_ctors.cpp (2290 of 15086)
```

**Comment by chapuni** [comment]
@ilovepi Thanks for reporting. I've reverted this and I'll rework with less-intrusive way.

**Comment by ilovepi** [comment]
Thanks.

**Pull request merged**
