### PR TITLE
[lld][InstrProf] Sort startup functions for compression

### PR DESCRIPTION
**Pull request by ellishg**
Before this, startup functions were only ordered to reduce the number of page faults. This patch introduces `--compression-sort-startup-functions` which orders these function to also improve compressed size at the same time. Of course, this will regress some startup performance in favor of improved compressed size.

I built a large binary without this flag (Base) and with this flag (Startup Compression). I also removed all startup hashes (Remove Startup Hashes) to see how ordering them for startup impacts the number of page faults. I recorded "Page Fault Curve Area" from the verbose logs and compressed the resulting binary using `zip` for "Compressed Size".

|                       | Page Fault Curve Area | Compressed Size |
| --------------------- | --------------------- | --------------- |
| Base                  | 1.045659e+09          | 25.1 MB         |
| Startup Compression   | 1.430330e+09 (+36.8%) | 24.7 MB (-1.4%) |
| Remove Startup Hashes | 2.272126e+09 (+117%)  | 24.6 MB (-2.1%) |

Depends on https://github.com/llvm/llvm-project/pull/107347

### CODE REVIEW

**Comment by kyulee-com** [comment]
This is a really interesting idea!

It looks like you've added compression constraints (basically utility nodes based on content) on top of the existing startup performance constraints (utility nodes based on execution traces) for the startup symbols. You're trying to run BP to achieve both compressed size and startup performance at the same time.

However, I'm wondering how much of an impact this will have depending on how many startup symbols there are compared to the total number of symbols. If there aren't many startup symbols, maybe shuffling them around won't really change performance or size much. But if there are a lot, this could potentially make startup slower while reducing the size more significantly. Could you share some info on how many startup symbols are involved in this experiment?

Also, I'm a bit confused about what `Remove Startup Hashes` actually means. Are you completely ignoring the startup set and just focusing on compression to measure the upper bound of the compressed size? Or are you still keeping the startup set but not considering the startup traces when ordering them?

**Comment by ellishg** [comment]
> However, I'm wondering how much of an impact this will have depending on how many startup symbols there are compared to the total number of symbols. If there aren't many startup symbols, maybe shuffling them around won't really change performance or size much. But if there are a lot, this could potentially make startup slower while reducing the size more significantly. Could you share some info on how many startup symbols are involved in this experiment?

In these tests I ordered about 45K functions for startup and 2.1M functions for compression. However, I suspect the functions in the startup set are quite large because ordering them does impact compressed size. I did not measure the size of these sets in bytes.
I'm actually trying to record page faults on my local device to compare these modes. I will post the results when I get them.

> Also, I'm a bit confused about what `Remove Startup Hashes` actually means. Are you completely ignoring the startup set and just focusing on compression to measure the upper bound of the compressed size? Or are you still keeping the startup set but not considering the startup traces when ordering them?

I ignored the startup traces when ordering those startup symbols. The purpose was to show an upper bound for how bad page faults can get and how good compression can get. Basically, this shows that "Startup Compression" is halfway between ordering completely for startup and ordering completely for compression.
```diff
diff --git a/lld/MachO/BPSectionOrderer.cpp b/lld/MachO/BPSectionOrderer.cpp
index 71758070ddc8..92032af67daa 100644
--- a/lld/MachO/BPSectionOrderer.cpp
+++ b/lld/MachO/BPSectionOrderer.cpp
@@ -286,6 +286,7 @@ DenseMap<const InputSection *, size_t> lld::macho::runBalancedPartitioning(

   for (auto &[sectionIdx, compressionUns] : unsForStartupFunctionCompression) {
     auto &uns = startupSectionIdxUNs[sectionIdx];
+    uns.clear();
     uns.append(compressionUns);
     llvm::sort(uns);
     uns.erase(std::unique(uns.begin(), uns.end()), uns.end());
```

**Comment by ellishg** [comment]
I built a large app and measured the number of page faults during startup on a local device for 5 trials. I built "Base" using 
`--irpgo-profile-sort` and `--compression-sort=function`. "Startup Compression" adds the `--compression-sort-startup-functions` flag. And "No PGO" does not order any functions for startup or compression.

|  | Mean Page Faults | IPA Size |
| -- | -- | -- |
| Base | 996.2 | 377.5 MB |
| Startup Compression | 1080.4 (+8.5%) | 376.7 MB (-0.19%) |
| No PGO | 1135.0 (+14%) | 381.1 MB (+0.10%) |

newplot (2)

It seems that "Startup Compression" is not as performant as "Base", but not nearly as bad as "No PGO". Furthermore, "Startup Compression" has the best compression ratio of the three. I think this shows that this flag is useful and the user can decide if this tradeoff is worthwhile.

**Review by kyulee-com — APPROVED** [review]
LGTM. Thanks for the additional test! It seems we can get the most size win out of this while still maintaining a decent start-up perf.

**Pull request merged**
