### PR TITLE
InstCombine: Try to use exp10 intrinsic instead of libcall

### PR DESCRIPTION
**Pull request by arsenm**
Addresses old TODO about the exp10 intrinsic not existing.

### CODE REVIEW

**Review by nikic — APPROVED** [review]
LGTM. It would be nice to have a common helper to handle this recurring "intrinsic or libcall" pattern...

**Comment by glandium** [comment]
This broke mac and ios targets, with a missing exp10 symbol at link time.

**Comment by arsenm** [comment]
> > This broke mac and ios targets, with a missing exp10 symbol at link time.
> 
> Testcase? That suggest TargetLibraryInfo is incorrectly reporting exp10 as available

This seems pretty well covered already: https://github.com/llvm/llvm-project/blob/e0a293d12f3fe1c2a284e2e116cfa77d894da49f/llvm/lib/Analysis/TargetLibraryInfo.cpp#L537

**Comment by glandium** [comment]
It's complaining about exp10 being missing, not __exp10, so I guess the information from there is not correctly used.

**Comment by glandium** [comment]
Here's a reproducer
```
long n, x;
void foo() { x = __builtin_powl(10, n); }
```
Build with `clang -O1 -o libfoo.dylib -shared foo.c --target=aarch64-apple-darwin -isysroot /path/to/MacOSX.sdk/`

**Comment by glandium** [comment]
Before the change, this compiled to use __exp10, now, it uses exp10.

**Comment by arsenm** [comment]
> As this is breaking builds on Darwin platforms I am planning to revert this soon to unbreak builds until #92520 lands

How about just review it instead

**Pull request merged**
