### PR TITLE
Revert "[clang] Reland: Instantiate concepts with sugared template arguments (#101782)"

### PR DESCRIPTION
**Pull request by mizvekov**
This reverts commit 748371183ae769bfb485f1e7466a864bf1db93d5.

Reverted due to both regression reported on PR and #102353

### CODE REVIEW

**Comment by zyn0217** [comment]
(It's #102353)

**Comment by mizvekov** [comment]
> (It's #102353)

Updated, thanks for the correction.

**Comment by MaskRay** [comment]
The description specifies "Reverted due to both regression reported on PR and https://github.com/llvm/llvm-project/issues/102353" but somehow the commit message does not include the reason.
(I just tried to look at reverts without reasons and remind the authors.)

**Comment by mizvekov** [comment]
> The description specifies "Reverted due to both regression reported on PR and https://github.com/llvm/llvm-project/issues/102353" but somehow the commit message does not include the reason.
> 
> (I just tried to look at reverts without reasons and remind the authors.)

I don't understand how that happened either. I merged through the iPhone GitHub App, for what it's worth, and I didn't edit the commit message before confirming.

**Comment by zyn0217** [comment]
Looks like the regression is due to the sugar preservation caused declaration referenced by VLAs to make their way into the constraint evaluation, whereas they don't appear in the instantiation scope.

Do you have any thoughts?

**Pull request merged**
