### PR TITLE
[InstCombine] Add (A & B) - (A & ~B) --> B - (A ^ B)

### PR DESCRIPTION
**Pull request by AZero13**
(A & B) - (A & ~B) -->  B - (A ^ B), and (A & ~B) - (A & B) --> (A ^ B) - B

Alive2 Proof:
https://alive2.llvm.org/ce/z/DWVWYy

### CODE REVIEW

**Comment by nikic** [comment]
Did you encounter this pattern in real-world code?

**Comment by AtariDreams** [comment]
Not this in particular, but I've seen code that folds to (A+~B)-(A+B) for example.

**Comment by AtariDreams** [comment]
> Did you encounter this pattern in real-world code?

Yes: X & -(alignment - 1) is a common way to align. X & (alignment - 1) is a common way to get the lower bits starting from alignment and lower.

By subtracting these two, you get how much is between X and X rounded to alignment.

**Comment by AtariDreams** [comment]
_Bytes = _Bytes & ~(_Align - 1); Is a common idiom for rounding up to the nearest alignment.
Difference = Bytes & (_Align - 1) is used to get the modulo.

subtracting these values is useful if you want to know the difference if say, _Bytes were to be the size of a buffer for example.

**Comment by topperc** [comment]
Please don't force push to PRs https://llvm.org/docs/GitHub.html#rebasing-pull-requests-and-force-pushes

**Comment by dtcxzyw** [comment]
> Please don't force push to PRs https://llvm.org/docs/GitHub.html#rebasing-pull-requests-and-force-pushes

TBH I always force-push my PRs since I have a bunch of concurrent PRs with different base commits. Without rebasing and force-pushing, ccache works poorly, and I have to waste about an hour every time I switch to another branch and rebuild LLVM :(

**Comment by dtcxzyw** [comment]
> _Bytes = _Bytes & ~(_Align - 1); Is a common idiom for rounding up to the nearest alignment.

Should be `(_Bytes + _Align - 1) & ~(_Align - 1)`.

**Comment by nikic** [comment]
> _Bytes = _Bytes & ~(_Align - 1); Is a common idiom for rounding up to the nearest alignment. Difference = Bytes & (_Align - 1) is used to get the modulo.
> 
> subtracting these values is useful if you want to know the difference if say, _Bytes were to be the size of a buffer for example.

`~(_Align - 1)` will become `-_Align` and your pattern will not match. If `_Align` is constant it will also not match.

Please don't invent hypothetical scenarios where it could apply -- provide positive proof where it *does* apply.

Besides, this pattern is not undef-safe. Your proof specified noundef, and if we drop it we get this: https://alive2.llvm.org/ce/z/-ajcoF It would be necessary to insert freeze instructions to make it correct.

Given that no real-world motivation was provided, I'm closing this.

**Pull request closed without merging**
