### PR TITLE
[mlir] split transform interfaces into a separate library

### PR DESCRIPTION
**Pull request by ftynse**
Transform interfaces are implemented, direction or via extensions, in libraries belonging to multiple other dialects. Those dialects don't need to depend on the non-interface part of the transform dialect, which includes the growing number of ops and transitive dependency footprint.

Split out the interfaces into a separate library. This in turn requires flipping the dependency from the interface on the dialect that has crept in because both co-existed in one library. The interface shouldn't depend on the transform dialect either.

As a consequence of splitting, the capability of the interpreter to automatically walk the payload IR to identify payload ops of a certain kind based on the type used for the entry point symbol argument is disabled. This is a good move by itself as it simplifies the interpreter logic. This functionality can be trivially replaced by a `transform.structured.match` operation.

### CODE REVIEW

**Comment by chsigg** [comment]
> direction or via extensions

'directly'?

**Review by chsigg — APPROVED** [review]
I like this change.

**Review by stellaraccident — APPROVED** [review]
This seems like a positive change. I have to admit, though, that seeing the sprawl that the tie in to TD has on the codebase all in one place gives me pause. I think we really need to have a conversation about encapsulation. Maybe I'm just looking at this wrong.

**Comment by stellaraccident** [comment]
I have a mental model of what seems to work out when using TD, and I have a fair bit of practical observations of what is off label usage that we end up having to back out and write real pass pipelines for. 

Right now, it is effectively a tool for writing a specific "granularity" of pass in more of a meta-programmed way. Most of the issues I see with it come from it having no guard rails on recommended use (and then people use it for things it will be bad at, someone has to come along and redo months of work, and then bad feelings emerge). It's positioning as a piece of core infra adds to that because, probably unintentionally, it gets assumed to be more of "the way" than it is really positioned to serve.

My point around encapsulation was that such a thing can succeed very well if it is a self contained entity that is really good at what it does and people reach for it when they know they need that thing. I need to look more closely vs just making a fly by comment, but the amount of touch points that implementing this thing has on everything else tells us something. And I think that the answer is not necessarily to move it closer to the core infra. I'm not sure what it is but we're missing something here if that is the way that such a thing must exist.

**Comment by ftynse** [comment]
I am curious to learn more about cases that worked for you and those that did not. There are intentionally no recommended use cases so as to not limit what people can do with it but rather learn from the emerging use cases. Unfortunately, I haven't thought through the information gathering strategy, so most of the feedback I heard so far boils down "it didn't work for me" without any other actionable information. There seems to be a common problem of people conflating the idea of capturing (parts of) IR transformation in the IR itself with the limited set of transform ops currently available upstream.

**Comment by joker-eph** [comment]
> IMO, transform interfaces belong to lib/Interface, and I wanted that from the early days. 

Right, to me this was only a question of maturity. Something like the transform dialect is just are core infra as the patterns mechanism, PDL, etc.

This should be a hard dependency on the core IR (in MLIR you always pay only for what you use), but it's part of these off-the-shelves convenient components that gets well integrated in the core infra.

**Comment by stellaraccident** [comment]
> I am curious to learn more about cases that worked for you and those that did not. There are intentionally no recommended use cases so as to not limit what people can do with it but rather learn from the emerging use cases. Unfortunately, I haven't thought through the information gathering strategy, so most of the feedback I heard so far boils down "it didn't work for me" without any other actionable information. There seems to be a common problem of people conflating the idea of capturing (parts of) IR transformation in the IR itself with the limited set of transform ops currently available upstream.

I'll be at eurollvm and might be a good discussion to have over drinks. It definitely produces some polarizing outcomes (I think I'm past opinions at this point and more judging based on what worked and didn't over many months/years) that make me see a couple of sides.

**Comment by stellaraccident** [comment]
> Right, to me this was only a question of maturity. Something like the transform dialect is just are core infra as the patterns mechanism, PDL, etc.

I know there are strong counter opinions to this, even with respect to PDL. I believe we've rushed maturity on some of these more speculative pieces and they would have been better to have had more mileage before integration.

**Comment by joker-eph** [comment]
I am speaking from the point of view of how the core team built MLIR, none of MLIR would exist with this kind of criteria.
Some may want to see a different project management, but that’s a change, that is not how MLIR has been and is driven by the maintainers of the Core infra.

**Comment by joker-eph** [comment]
I don’t remember discussing much of MLiR invariant and core infra principles with (other than the python bindings of course), and I have been leading the development for the longest here: nothing happened in MLIR core infra that I wasn’t deeply involved with.

If I have to list on top of my head, I’d say that MLIR infra was continuously designed and built between me/river/jeff/jacques, and likely Alex as well, and Albert on some IR modeling aspects. These are the folks I would trust to discuss the core infra. I would have to ask them to see who I forget (it’s hard to be exhaustive on a while), but the list of authors of the MLIR paper may also be a good starting point.

**Comment by stellaraccident** [comment]
This is edging into a pointless discussion. Alex: happy to meet f2f and help parse my collected experiences with TD and talk through paths. It's always hard to tell, but I think my team may be one of the heaviest users of it, and if you're not getting feedback, we can fix that. Ditto for PDL fwiw.

Mehdi: you're forgetting one key person. @lattner and I discussed MLIR principles every week and much of that is embedded into how things unfolded.

**Comment by lattner** [comment]
I care a lot about the design and evolution of core MLIR, as well as proper layering, but I won't be at EuroLLVM this year.

**Pull request merged**
