### PR TITLE
[mlir][vector] Rename vector type TD definitions (nfc)

### PR DESCRIPTION
**Pull request by banach-space**
Currently, the Vector dialect TD file includes the following "vector"
type definitions:

```mlir
def AnyVector : VectorOf<[AnyType]>;
def AnyVectorOfAnyRank : VectorOfAnyRankOf<[AnyType]>;
def AnyFixedVector : FixedVectorOf<[AnyType]>;
def AnyScalableVector : ScalableVectorOf<[AnyType]>;
```

In short:

  * `AnyVector` _excludes_ 0-D vectors.
  * `AnyVectorOfAnyRank`, `AnyFixedVector`, and `AnyScalableVector`
    _include_ 0-D vectors.

The naming for "groups" that include 0-D vectors is inconsistent and can
be misleading, and `AnyVector` implies that 0-D vectors are included,
which is not the case.

This patch renames these definitions for clarity:

```mlir
def AnyVectorOfNonZeroRank : VectorOfNonZeroRankOf<[AnyType]>;
def AnyVectorOfAnyRank : VectorOfAnyRankOf<[AnyType]>;
def AnyFixedVectorOfAnyRank : FixedVectorOfAnyRank<[AnyType]>;
def AnyScalableVectorOfAnyRank : ScalableVectorOfAnyRank<[AnyType]>;
```

Rationale:
* The updated names are more explicit about 0-D vector support.
* It becomes clearer that scalable vectors currently allow 0-D vectors -
  this might warrant a revisit.
* The renaming paves the way for adding a new group for "fixed-width
  vectors excluding 0-D vectors" (e.g., AnyFixedVector), which I plan to
  introduce in a follow-up patch.

### CODE REVIEW

**Review by Groverkss — APPROVED** [review]
This change by itself is good.

But another suggestion based on problems I've had with these tablegen defs: AnyVector not allowing 0-d rank vectors is a bit confusing. AnyVector is really AnyVectorOfAnyRank + additional constraints. It took some debug time in the past to figure out that the naming is weird. The naming should maybe be AnyVectorOfNonZeroRank and AnyVector, or even AnyVectorOfNonZeroRank and AnyVectorOfAnyRank, to better reflect that the current AnyVector is more constrainted definition. What do you think? (My suggestion is non blocking, feel free to land)

**Review by kuhar — COMMENTED** [review]
I think that if we are going to clean up the naming here, I'd be best to also take care of the AnyVector / AnyVectorOfAny rank confusion like Kunwar mentioned. I'd expect this to be easier in terms of downstream maintenance burden than doing two separate renamings.

**Comment by banach-space** [comment]
> But another suggestion based on problems I've had with these tablegen defs: AnyVector not allowing 0-d rank vectors is a bit confusing. AnyVector is really AnyVectorOfAnyRank + additional constraints. It took some debug time in the past to figure out that the naming is weird. The naming should maybe be AnyVectorOfNonZeroRank and AnyVector, or even AnyVectorOfNonZeroRank and AnyVectorOfAnyRank, to better reflect that the current AnyVector is more constrainted definition. What do you think? (My suggestion is non blocking, feel free to land)

I agree that `AnyVector` is quite misleading and deserves a re-name as well. I assume that those names were added as a temporary workaround and we just never got round to unifying them (or "fixing" 0-D support).

I am happy to change that in a separate PR. First, I wanted to send this one that fixes inconsistencies to make sure that there are no objections 😅 

Thanks for reviewing 🙏🏻

**Comment by kuhar** [comment]
> I am happy to change that in a separate PR. First, I wanted to send this one that fixes inconsistencies to make sure that there are no objections 😅

Why not rename things in one go? I think we could do that without introducing naming collisions with a simple tweak to what you proposed, for example:
* AnyVector --> AnyVectorOfNonZeroRank
* AnyVectorOfAnyRank -> as-is
* AnyFixedVector -> AnyFixedVectorOfAnyRank
* AnyScalableVector  -> AnyScalableVectorOfAnyRank

**Review by kuhar — APPROVED** [review]
LGTM. Thanks for making this less confusing.

**Review by dcaballe — APPROVED** [review]
Thanks for the renaming!

**Pull request merged**
