### PR TITLE
[lldb] Fix finding make tool for tests

### PR DESCRIPTION
**Pull request by DavidSpickett**
Fixes 0e913237871e8c9290e82be30be8b3484952eee0 / https://github.com/llvm/llvm-project/pull/111531

For reasons I can't explain, a clean build works fine for me, and all the bots are working fine. But if I rebuild in some way the make tool becomes None.

Looking at the other variables, they had these extra lines so I've added those for make and it seems to solve the problem.

### CODE REVIEW

**Comment by DavidSpickett** [comment]
Putting this in review because I've zero idea why this fixes it. Without it I get this on a rebuild:
```
Traceback (most recent call last):
  File "/home/david.spickett/llvm-project/lldb/test/API/functionalities/reverse-execution/TestReverseContinueBreakpoints.py", line 67, in test_reverse_continue_skip_breakpoint_async
    self.reverse_continue_skip_breakpoint_internal(async_mode=True)
  File "/home/david.spickett/llvm-project/lldb/test/API/functionalities/reverse-execution/TestReverseContinueBreakpoints.py", line 70, in reverse_continue_skip_breakpoint_internal
    target, process, initial_threads = self.setup_recording(async_mode)
  File "/home/david.spickett/llvm-project/lldb/test/API/functionalities/reverse-execution/TestReverseContinueBreakpoints.py", line 94, in setup_recording
    self.build()
  File "/home/david.spickett/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1496, in build
    self.runBuildCommand(command)
  File "/home/david.spickett/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 1501, in runBuildCommand
    output = check_output(command, stderr=STDOUT, errors="replace")
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 503, in run
    with Popen(*popenargs, **kwargs) as process:
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1738, in _execute_child
    and os.path.dirname(executable)
  File "/usr/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
Config=aarch64-/home/david.spickett/build-llvm-aarch64/bin/clang
```
Because the `make` passed in `command` is actually `None`. Perhaps the cache isn't read properly after the first configuration?

**Review by weliveindetail — APPROVED** [review]
Interesting! Your changes look fine, as they are symmetric with what we do here for dsymutil. I just wonder why I didn't hit that. Is this a separate test driver for Linux?

**Comment by DavidSpickett** [comment]
I don't think so, it's used to generate dotest.py on all platforms I think. Perhaps my cmake is being strict / less strict? The funny thing is, I can see `LLDB_TEST_MAKE` set in the cache even when the build breaks.

**Comment by zeroomega** [comment]
Hi,

I noticed that our LLDB Windows builders all failed after this change is landed:

```
CMake Error at C:/b/s/w/ir/x/w/llvm-llvm-project/lldb/test/API/CMakeLists.txt:60 (message):
   LLDB tests require 'make' tool.  Please pass via `LLDB_TEST_MAKE` (or
   otherwise disable tests with `LLDB_INCLUDE_TESTS=OFF`)
```

We are aware our windows bots don't have make tool and we are not planning to add it anyway. Not all lldb tests require `make` to run and it feels wrong to me to mandate `make` tool for a few tests that requires it. Could it be changed to disable such tests when make is not present instead of throw an error to prevent the lldb build?

**Comment by labath** [comment]
lldb-dotest is a separate tool, which is usually only invoked manually when debugging a specific test (and not invoked by `make check-lldb` like the bots do). This fact that its args need to stay in sync is annoying an a relatively common problem. I feel that there must be a way to have a single source of truth for the testing args, but I haven't found the time to figure one out yet (patches welcome).

**Pull request merged**
