### PR TITLE
[IndVarSimplify] Do not replace ExitValue if it contains Udiv with non-constant divisor

### PR DESCRIPTION
**Pull request by ShivaChen**
Udiv bring high structural dependency and decrease performance. Adding containNonConstantDivisorUDiv checking to avoid the regression.

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
Exit value replacement checks the cost of the expansion. If the expansion is high cost (which would be the case for udiv), then it is only performed if the loop can be deleted.

So the tradeoff here is replacing an entirely loop with a udiv. Unless the loop has very few iterations, this seems like a profitable replacement to make.

What's the motivating case here? Is it a loop that has very few iterations and gets replaced by a more expensive udiv?

**Comment by ShivaChen** [comment]
> Exit value replacement checks the cost of the expansion. If the expansion is high cost (which would be the case for udiv), then it is only performed if the loop can be deleted.
> 
> So the tradeoff here is replacing an entirely loop with a udiv. Unless the loop has very few iterations, this seems like a profitable replacement to make.
> 
> What's the motivating case here? Is it a loop that has very few iterations and gets replaced by a more expensive udiv?

It's motivated by a small loop in primecount https://github.com/embench/embench-iot/blob/master/src/primecount/primecount.c#L116.
Yes, it has few iterations and been replaced by a "sub, maxu, divu, add, mul, add".
There is a relative issue. https://github.com/llvm/llvm-project/issues/71424.
Would detect udiv with non-zero divisor too simplified? Is there better way to guard the case? Thanks.

**Comment by nikic** [comment]
If SCEV could determine a small max trip count for the loop, we could take that into account when deciding whether to expand or not, but I doubt that it can in this case.

For this change, I'm concerned that you are optimizing the code for one specific benchmark, but will make things worse for other cases.

**Comment by preames** [comment]
> For this change, I'm concerned that you are optimizing the code for one specific benchmark, but will make things worse for other cases.

I second this concern, and don't believe we should accept this patch in the current form.

**Comment by ShivaChen** [comment]
> If SCEV could determine a small max trip count for the loop, we could take that into account when deciding whether to expand or not, but I doubt that it can in this case.

Yes, the case can't be determined the trip count.

> For this change, I'm concerned that you are optimizing the code for one specific benchmark, but will make things worse for other cases.

As nikic suggested, guarding the replacement should only benefit for small trip count.

**Pull request closed without merging**
