### PR TITLE
[ADT] Teach StringRef to derive from std::string_view

### PR DESCRIPTION
**Pull request by kazutakahirata**
This patch makes minimum changes to have StringRef derive from
std::string_view, with an eventual goal of removing StringRef
completely.  Subsequent patches will further clean up the remaining
bits.

I've chosen public inheritance over private one because our codebase
relies on implicit conversions to std::string_view, which is currently
provided by:

  constexpr operator std::string_view() const {
    return std::string_view(data(), size());
  }

This implicit conversion stops applying once we use std::string_view
as a base class, public or private.  If we chose a private base class,
we would lose the implicit conversion.

### CODE REVIEW

**Review by MaskRay — APPROVED** [review]

**Comment by tschuett** [comment]
Nice. Do you plan a brief announcement on discourse for the plan?

**Comment by kazutakahirata** [comment]
> Nice. Do you plan a brief announcement on discourse for the plan?

Good idea!

https://discourse.llvm.org/t/migrating-llvm-stringref-to-std-string-view/82785

**Comment by AaronBallman** [comment]
Why was this merged before the RFC was discussed (or accepted)?

**Comment by MaskRay** [comment]
This patch was posted before https://discourse.llvm.org/t/migrating-llvm-stringref-to-std-string-view/82785 . I thought if StringRef could derive from std::string_view, it would be really nice to simplify interop with std::string_view, whether or not we decide to keep StringRef (perhaps we would only use StringRef as temporary objects for its specific APIs, instead of storing StringRef in data structures). However, there were many issues due to GCC overload resolution.

**Pull request merged**
