### PR TITLE
Unify naming of internal pointer members in std::vector and std::__split_buffer

### PR DESCRIPTION
**Pull request by winner245**
Related to PR #114423, this PR proposes to unify the naming of the internal pointer members in `std::vector` and `std::__split_buffer` for consistency and clarity.

Both `std::vector` and `std::__split_buffer` originally used a `__compressed_pair<pointer, allocator_type>` member named `__end_cap_` to store an internal capacity pointer and an allocator. However, inconsistent naming changes have been made in both classes:
- `std::vector` now uses `__cap_` and `__alloc_` for its internal pointer and allocator members.
- In contrast, `std::__split_buffer` retains the name `__end_cap_` for the capacity pointer, along with `__alloc_`.

This inconsistency between the names `__cap_` and `__end_cap_` has caused confusions (especially to myself when I was working on both classes). I suggest unifying these names by renaming `__end_cap_` to `__cap_` in `std::__split_buffer`.

### CODE REVIEW

**Review by philnik777 — APPROVED** [review]
LGTM with green CI.

**Review by ldionne — APPROVED** [review]

**Comment by ldionne** [comment]
The bootstrapping build failures are legitimate (the other ones are not). They are caused by the fact that we store a `__split_buffer` inside `deque` and changing the name of the variable [breaks the LLDB data formatters](https://github.com/llvm/llvm-project/actions/runs/11746523395/job/32728376148?pr=115517).

I think the following diff should fix it, but @Michael137 should chime in to let us know if LLDB generally tries to be more backwards-compatible than what this diff achieves:

```diff
diff --git a/lldb/examples/synthetic/libcxx.py b/lldb/examples/synthetic/libcxx.py
index b078a4eb2f63..f8534cf9fdc9 100644
--- a/lldb/examples/synthetic/libcxx.py
+++ b/lldb/examples/synthetic/libcxx.py
@@ -765,7 +765,7 @@ class stddeque_SynthProvider:
                 )
             else:
                 map_endcap = map_.GetChildMemberWithName(
-                    "__end_cap_"
+                    "__cap_"
                 ).GetValueAsUnsigned(0)
 
             # check consistency
```

**Comment by winner245** [comment]
Thank you for your feedback and help, ldionne! The diff you mentioned seems like a reasonable solution. I will wait for @Michael137's confirmation. If necessary, I can make adjustments in the PR to ensure compatibility.

**Comment by Michael137** [comment]
> Thank you for your feedback and help, ldionne! The diff you mentioned seems like a reasonable solution. I will wait for @Michael137's confirmation. If necessary, I can make adjustments in the PR to ensure compatibility.

Yea we usually try to keep backward compatibility for a couple of years (or until it becomes hard to maintain). Here's an example of how you could support two layouts: https://github.com/llvm/llvm-project/blob/25d1ac11d537debb217c65c2bcdd087a60cff58e/lldb/examples/synthetic/libcxx.py#L715-L718

I.e., call `GetChildMemberWithName` with the new name. If that doesn't work. Try with the old name. Let me know if you need help making this work

**Comment by winner245** [comment]
Thank you for your feedback and suggestions, @Michael137! I appreciate your guidance on maintaining backward compatibility. I will implement the suggested approach by checking for both the new and old member names in the LLDB data formatters. Thanks again for your help.

**Comment by Michael137** [comment]
LLDB changes LGTM, thanks!

The `tools/lldb-dap/evaluate/TestDAP_evaluate.py` is unrelated to this PR and has been failing on other PRs too. So feel free to merge if the libc++ changes are good to go

**Pull request merged**
