### PR TITLE
Revert "[LLDB] Reappply SBSaveCore AddMemoryList"

### PR DESCRIPTION
**Pull request by JDevlieghere**
Reverts llvm/llvm-project#107159 as this is still causing `TestSkinnyCorefile.py` to time out. 

https://ci.swift.org/view/all/job/llvm.org/view/LLDB/job/as-lldb-cmake/11099/
https://ci.swift.org/view/all/job/llvm.org/view/LLDB/job/lldb-cmake/5544/

### CODE REVIEW

**Comment by JDevlieghere** [comment]
CC @Jlalond

**Comment by jasonmolenda** [comment]
I'll look more closely later when I have time, but ObjectFileMachO::SaveCore called `Process::CalculateCoreFileSaveRanges` with an `options` of `eSaveCoreDirtyOnly` (so, `GetCoreFileSaveRangesDirtyOnly()`), it's returning gigantic memory regions to be saved to the corefile.  I tried doing a "full" style coredump of the test binary (using an lldb with this patch applied) and it was around 4.6GB.  Then I tried a `-s modified-memory` corefile and it had dumped 34GB before I killed the process.  Running an lldb without this PR, a dirty-memory-only coredump of this process is 10MB.

**Comment by Jlalond** [comment]
> I'll look more closely later when I have time, but ObjectFileMachO::SaveCore called `Process::CalculateCoreFileSaveRanges` with an `options` of `eSaveCoreDirtyOnly` (so, `GetCoreFileSaveRangesDirtyOnly()`), it's returning gigantic memory regions to be saved to the corefile. I tried doing a "full" style coredump of the test binary (using an lldb with this patch applied) and it was around 4.6GB. Then I tried a `-s modified-memory` corefile and it had dumped 34GB before I killed the process. Running an lldb without this PR, a dirty-memory-only coredump of this process is 10MB.

Sorry about causing some problems on Saturday no less. My guess is this is from the finalize core save ranges, specifically how we roll up all the memory ranges. My first thinking out loud question is why this isn't happening on Linux Minidumps, but I know MacOS and Linux differ on what the kernel says if the page is dirty.

I'll look into it on Monday and appreciate the investigation assistance

**Comment by jasonmolenda** [comment]
Took a quick peek at what debugserver is sending back.  For this program there are 68 separate memory regions.  There are 593 dirty pages across those 68 regions, pagesize is 16384 so 9715712 bytes of dirty memory (what we see lldb dumping currently).  This entry,

```
 <  90> read packet: $start:16f604000;size:7fc000;permissions:rw;dirty-pages:16fdf8000,16fdfc000;type:stack;#00
```

gives us a CoreFileMemoryRange of 
```
      [0] = {
        lldb_private::RangeData<unsigned long long, unsigned long long, lldb_private::CoreFileMemoryRange> = {
          lldb_private::Range<unsigned long long, unsigned long long> = (base = 6171885568, size = 6171918336)
```

which is quite large.  Maybe one of these functions is taking an address & a size, instead of a start address and an end address.

```
  for (addr_t page_addr : *dirty_page_list) {
    if (range.empty()) {
      // No range yet, initialize the range with the current dirty page.
      range = llvm::AddressRange(page_addr, page_addr + page_size);
    } else {
      if (range.end() == page_addr) {
        // Combine consective ranges.
        range = llvm::AddressRange(range.start(), page_addr + page_size);
      } else {
        // Add previous contiguous range and init the new range with the
        // current dirty page.             
        ranges.Append(range.start(), range.end(), {range, lldb_permissions});
        range = llvm::AddressRange(page_addr, page_addr + page_size);
      }
    }
```

**Pull request merged**
