### PR TITLE
[GlobalISel] Optimized MatchData Handling

### PR DESCRIPTION
**Pull request by Pierre-vh**
Surprisingly, MatchDatas were very, very expensive in GlobalISel Combiners. The time spent on constructing the big MatchData struct, and copying it to reset it (`operator=`) was equal or greater than the time spent iterating the MatchTable itself and executing it (excluding the time spent in callees, of course).

This was because I put every MatchData we could possibly need in a big struct, and rebuilt that struct every instruction we looked at. Turns out that when all your function is doing is iterating over a byte array and executing opcodes, the time spent allocating and initializing a huge non-trivially constructible/destructible struct over and over again is very, very significant.

Now, we use a simpler and more efficient strategy: be as lazy as possible, only allocate and deallocate as needed, end of story. The backend doesn't think about it anymore, and we simply don't pay for what we don't use.

### CODE REVIEW

**Comment by Pierre-vh** [comment]
@aemerson If you have some time, can you check this on CTMark? I think it should be a neat improvement according to my profiling done using `perf record` but I'd like someone else to confirm

**Comment by jayfoad** [comment]
One related thing I have never understood is, why is every combine split into a "match" function and an "apply" function? Aren't they always effectively called in tandem like this:
```
  if (matchFunc(MatchData))
    applyFunc(MatchData);
```
? Is there a use case for calling "match" without "apply"?

**Comment by jayfoad** [comment]
> > One related thing I have never understood is, why is every combine split into a "match" function and an "apply" function? Aren't they always effectively called in tandem like this:
> > ```
> >   if (matchFunc(MatchData))
> >     applyFunc(MatchData);
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ? Is there a use case for calling "match" without "apply"?
> 
> Matchers can fail/reject after doing further analysis (e.g. calling KnowBits), so the matcher is like an analysis part and the apply is the actual transform.

Right, but why not always compile the match+apply as a single C++ function like:
```
  bool matchAndApply(MI) {
    // match part goes here

    if (analysis failed)
      return false;

    // apply part goes here
    return true;
  }
```
Then you don't have to worry about managing the lifetime of matchdata objects outside of this function.

**Comment by aemerson** [comment]
I'll get some perf numbers on this change, thanks.

Also curious: do you think there's any significant problem with our common use of the build function lambdas?

**Comment by aemerson** [comment]
Strangely, after 2 attempts at running everything with 10x repeats each time, I'm seeing performance *regressions*, if any change.

```
Program                                       compile_time
                                              lhs          rhs    diff
Bullet/bullet                                  10.98        11.00  0.2%
7zip/7zip-benchmark                            14.76        14.78  0.2%
lencod/lencod                                   4.65         4.66  0.2%
tramp3d-v4/tramp3d-v4                           5.68         5.69  0.1%
mafft/pairlocalalign                            2.68         2.68  0.0%
SPASS/SPASS                                     4.57         4.57  0.0%
kimwitu++/kc                                    6.65         6.65 -0.0%
consumer-typeset/consumer-typeset               3.59         3.59 -0.0%
sqlite3/sqlite3                                 2.49         2.49 -0.1%
                           Geomean difference                      0.1%
```

This is measured in an MacBook with release mode + assertions disabled, no LTO.

**Comment by aemerson** [comment]
I'm going to rebuild with ThinLTO to see if there's a difference there.

**Comment by aemerson** [comment]
Similar thing with LTO:
```
Program                                       compile_time
                                              lhs          rhs    diff
kimwitu++/kc                                    6.30         6.33  0.4%
7zip/7zip-benchmark                            14.14        14.17  0.2%
Bullet/bullet                                  10.43        10.44  0.1%
sqlite3/sqlite3                                 2.36         2.36  0.1%
SPASS/SPASS                                     4.34         4.34  0.1%
consumer-typeset/consumer-typeset               3.41         3.40 -0.0%
mafft/pairlocalalign                            2.55         2.54 -0.0%
tramp3d-v4/tramp3d-v4                           5.37         5.36 -0.0%
lencod/lencod                                   4.41         4.41 -0.1%
                           Geomean difference                      0.1%
```

**Comment by aemerson** [comment]
One thing I just noticed was that the binary sizes for clang w/ thinlto were quite different.
Before: 181781160
After: 182051240

That's a -0.15% size regression which is significant for such a relatively small change. Using a script to analyze function size diffs I see this as the top regressions:
```
__ZNK12_GLOBAL__N_125AMDGPURegBankCombinerImpl15runCustomActionEjRKN4llvm20GIMatchTableExecutor12MatcherStateERNS1_11SmallVectorINS1_19MachineInstrBuilderELj4EEE 940 1824 884
__ZNK12_GLOBAL__N_129RISCVPreLegalizerCombinerImpl18testMIPredicate_MIEjRKN4llvm12MachineInstrERKNS1_20GIMatchTableExecutor12MatcherStateE 8376 9552 1176
__ZNK12_GLOBAL__N_132AArch64PostLegalizerLoweringImpl15runCustomActionEjRKN4llvm20GIMatchTableExecutor12MatcherStateERNS1_11SmallVectorINS1_19MachineInstrBuilderELj4EEE 7712 8996 1284
__ZN12_GLOBAL__N_19Demangler10parseLNameEPN4llvm16itanium_demangle12OutputBufferERNSt3__117basic_string_viewIcNS5_11char_traitsIcEEEEm 46275648 46277264 1616
__ZNK12_GLOBAL__N_130AMDGPUPreLegalizerCombinerImpl18testMIPredicate_MIEjRKN4llvm12MachineInstrERKNS1_20GIMatchTableExecutor12MatcherStateE 8500 10168 1668
__ZNK12_GLOBAL__N_131AArch64PreLegalizerCombinerImpl18testMIPredicate_MIEjRKN4llvm12MachineInstrERKNS1_20GIMatchTableExecutor12MatcherStateE 8708 10416 1708
__ZNK12_GLOBAL__N_131AMDGPUPostLegalizerCombinerImpl18testMIPredicate_MIEjRKN4llvm12MachineInstrERKNS1_20GIMatchTableExecutor12MatcherStateE 9004 10736 1732
__ZNK12_GLOBAL__N_132AArch64PostLegalizerCombinerImpl15runCustomActionEjRKN4llvm20GIMatchTableExecutor12MatcherStateERNS1_11SmallVectorINS1_19MachineInstrBuilderELj4EEE 3720 6948 3228
__ZNK12_GLOBAL__N_129RISCVPreLegalizerCombinerImpl15runCustomActionEjRKN4llvm20GIMatchTableExecutor12MatcherStateERNS1_11SmallVectorINS1_19MachineInstrBuilderELj4EEE 4296 7624 3328
__ZNK12_GLOBAL__N_130AMDGPUPreLegalizerCombinerImpl15runCustomActionEjRKN4llvm20GIMatchTableExecutor12MatcherStateERNS1_11SmallVectorINS1_19MachineInstrBuilderELj4EEE 4424 7760 3336
__ZNK12_GLOBAL__N_131AMDGPUPostLegalizerCombinerImpl15runCustomActionEjRKN4llvm20GIMatchTableExecutor12MatcherStateERNS1_11SmallVectorINS1_19MachineInstrBuilderELj4EEE 4812 8248 3436
__ZNK12_GLOBAL__N_131AArch64PreLegalizerCombinerImpl15runCustomActionEjRKN4llvm20GIMatchTableExecutor12MatcherStateERNS1_11SmallVectorINS1_19MachineInstrBuilderELj4EEE 4676 8328 3652
```
demangled:
```
(anonymous namespace)::AMDGPURegBankCombinerImpl::runCustomAction(unsigned int, llvm::GIMatchTableExecutor::MatcherState const&, llvm::SmallVector<llvm::MachineInstrBuilder, 4u>&) const 940 1824 884
(anonymous namespace)::RISCVPreLegalizerCombinerImpl::testMIPredicate_MI(unsigned int, llvm::MachineInstr const&, llvm::GIMatchTableExecutor::MatcherState const&) const 8376 9552 1176
(anonymous namespace)::AArch64PostLegalizerLoweringImpl::runCustomAction(unsigned int, llvm::GIMatchTableExecutor::MatcherState const&, llvm::SmallVector<llvm::MachineInstrBuilder, 4u>&) const 7712 8996 1284
(anonymous namespace)::Demangler::parseLName(llvm::itanium_demangle::OutputBuffer*, std::__1::basic_string_view<char, std::__1::char_traits<char>>&, unsigned long) 46275648 46277264 1616
(anonymous namespace)::AMDGPUPreLegalizerCombinerImpl::testMIPredicate_MI(unsigned int, llvm::MachineInstr const&, llvm::GIMatchTableExecutor::MatcherState const&) const 8500 10168 1668
(anonymous namespace)::AArch64PreLegalizerCombinerImpl::testMIPredicate_MI(unsigned int, llvm::MachineInstr const&, llvm::GIMatchTableExecutor::MatcherState const&) const 8708 10416 1708
(anonymous namespace)::AMDGPUPostLegalizerCombinerImpl::testMIPredicate_MI(unsigned int, llvm::MachineInstr const&, llvm::GIMatchTableExecutor::MatcherState const&) const 9004 10736 1732
(anonymous namespace)::AArch64PostLegalizerCombinerImpl::runCustomAction(unsigned int, llvm::GIMatchTableExecutor::MatcherState const&, llvm::SmallVector<llvm::MachineInstrBuilder, 4u>&) const 3720 6948 3228
(anonymous namespace)::RISCVPreLegalizerCombinerImpl::runCustomAction(unsigned int, llvm::GIMatchTableExecutor::MatcherState const&, llvm::SmallVector<llvm::MachineInstrBuilder, 4u>&) const 4296 7624 3328
(anonymous namespace)::AMDGPUPreLegalizerCombinerImpl::runCustomAction(unsigned int, llvm::GIMatchTableExecutor::MatcherState const&, llvm::SmallVector<llvm::MachineInstrBuilder, 4u>&) const 4424 7760 3336
(anonymous namespace)::AMDGPUPostLegalizerCombinerImpl::runCustomAction(unsigned int, llvm::GIMatchTableExecutor::MatcherState const&, llvm::SmallVector<llvm::MachineInstrBuilder, 4u>&) const 4812 8248 3436
(anonymous namespace)::AArch64PreLegalizerCombinerImpl::runCustomAction(unsigned int, llvm::GIMatchTableExecutor::MatcherState const&, llvm::SmallVector<llvm::MachineInstrBuilder, 4u>&) const 4676 8328 3652
```

I'm not sure what happened here, my guess this is all overeager inlining related.

**Comment by Pierre-vh** [comment]
> > > One related thing I have never understood is, why is every combine split into a "match" function and an "apply" function? Aren't they always effectively called in tandem like this:
> > > ```
> > >   if (matchFunc(MatchData))
> > >     applyFunc(MatchData);
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > ? Is there a use case for calling "match" without "apply"?
> > 
> > 
> > Matchers can fail/reject after doing further analysis (e.g. calling KnowBits), so the matcher is like an analysis part and the apply is the actual transform.
> 
> Right, but why not always compile the match+apply as a single C++ function like:
> 
> ```
>   bool matchAndApply(MI) {
>     // match part goes here
> 
>     if (analysis failed)
>       return false;
> 
>     // apply part goes here
>     return true;
>   }
> ```
> 
> Then you don't have to worry about managing the lifetime of matchdata objects outside of this function.

That's interesting, I'm not sure if it's possible to do that but I'll add that to my list.



> I'll get some perf numbers on this change, thanks.
> 
> Also curious: do you think there's any significant problem with our common use of the build function lambdas?

I haven't seen issues related to the build lambdas, no

As for the (size and runtime) regression, that's really weird. `perf record` led me to believe this would improve things.
The size regression is probably due to inlining of the `getOrCreateMatchData` all over the place indeed.

I'm wondering if the pointer cast + indirection to reach the MatchData is adding too much overhead, I'll rethink this and try to understand why

**Comment by Pierre-vh** [comment]
I'll go with @jayfoad's idea: Call match & apply in the same function. I tested it and it works a lot better.

**Pull request closed without merging**
