### PR TITLE
[AArch64] Use ccmn to compare negative immediates between -1 and -31

### PR DESCRIPTION
**Pull request by AZero13**
Because ccmn is like a + b, it works when using cmp but with values that when negated are in the range of 1 through 31

### CODE REVIEW

**Comment by AtariDreams** [comment]
@TNorthover Thoughts on this?

**Review by davemgreen — COMMENTED** [review]
We would usually split the SDAG and GISel parts into separate patches, but from what I can tell this is OK for any predicate so long as it is a constant.

**Comment by AtariDreams** [comment]
@davemgreen Fixed!

**Review by davemgreen — APPROVED** [review]
Thanks, LGTM

**Comment by AtariDreams** [comment]
@davemgreen I do not have commit perms. Do you think you could please merge? Maybe I should ask others like @arsenm

**Pull request merged**
