### PR TITLE
[MC][Mips] Rename MipsMCAsmInfo to MipsELFMCAsmInfo

### PR DESCRIPTION
**Pull request by hpoussin**
Also change MipsAsmPrinter::emitStartOfAsmFile to emit ELF-related sections only when using ELF output file format.

### CODE REVIEW

**Comment by hpoussin** [comment]
This is an extract of PR #107744
This commit is better viewed when ignoring whitespace changes.

**Comment by brad0** [comment]
cc @yingopq

**Comment by hpoussin** [comment]
Ping.
This commit is required to add (in a later PR) the class MipsCOFFMCAsmInfo.

**Comment by wzssyqa** [comment]
There is a failure on Windows. Can you have a look at it?
 LLVM :: CodeGen/Mips/no-odd-spreg.ll

**Comment by hpoussin** [comment]
> There is a failure on Windows. Can you have a look at it? LLVM :: CodeGen/Mips/no-odd-spreg.ll

Fixed. It seems Windows hosts default to COFF output while Linux hosts default to ELF.
However, this test assumed ELF output without requesting it, and this PR starts to react on chosen output format.

**Pull request merged**
