### PR TITLE
Format clang/lib/Sema/Sema.cpp

### PR DESCRIPTION
**Pull request by bricknerb**

### CODE REVIEW

**Review by Sirraide — COMMENTED** [review]
Er, while it would be nice for everything to be formatted properly, this might cause some merge conflicts with other people’s changes in `Sema.cpp` (or at least that’s why we don’t do bulk reformatting too often iirc), so I’m not sure we just want to format entire files like this...

**Review by erichkeane — COMMENTED** [review]
@AaronBallman  should check this out, but if we're doing this, the commit needs to be added to teh 'ignore blame' file.

**Comment by cor3ntin** [comment]
> Er, while it would be nice for everything to be formatted properly, this might cause some merge conflicts with other people’s changes in `Sema.cpp` (or at least that’s why we don’t do bulk reformatting too often iirc), so I’m not sure we just want to format entire files like this...

Right, use `git clang-format`, that will take care of formatting the file over time without creating churn.

**Comment by kparzysz** [comment]
> Right, use `git clang-format`, that will take care of formatting the file over time without creating churn.

I think the number of changes is relatively small for a file this size.  The churn here is comparable to that created by a "normal" patch...

**Comment by AaronBallman** [comment]
Is there a need for the changes? (Are you making a significant number of changes in the file, or is this just a drive-by cleanup?) Generally, we don't do sweeping formatting changes:

> Avoid committing formatting- or whitespace-only changes outside of code you plan to make subsequent changes to. Also, try to separate formatting or whitespace changes from functional changes, either by correcting the format first (ideally) or afterward. Such changes should be highly localized and the commit message should clearly state that the commit is not intended to change functionality, usually by stating it is NFC. (From https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access)

**Comment by bricknerb** [comment]
Thanks for the feedback!
This all makes sense.
For context, I was going through some of the code and saw some formatting and thought it would be more readable to fix those.
I do understand the tradeoff here, so I'll close this pull request.

**Pull request closed without merging**
