### PR TITLE
InferAddressSpaces: Handle masked load and store intrinsics

### PR DESCRIPTION
**Pull request by arsenm**

### CODE REVIEW

**Comment by arsenm** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/102007?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#102007** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/102007?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#101982** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/101982?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by arsenm** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/102007?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#102007** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/102007?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#101982** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/101982?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by rampitec — APPROVED** [review]
LGTM

**Review by Artem-B — APPROVED** [review]

**Comment by arsenm** [comment]
### Merge activity

* **Aug 5, 4:10 PM EDT**: @arsenm started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/102007).

**Pull request merged**
