### PR TITLE
[libc] fix -Wmissing-braces

### PR DESCRIPTION
**Pull request by nickdesaulniers**
Fixes the following errors observed on the aarch64 fullbuild:

    /home/libc-buildbot/libc-aarch64-ubuntu/libc-aarch64-ubuntu-fullbuild-dbg/llvm-project/libc/src/__support/HashTable/generic/bitmask_impl.inc:116:13:
    error: suggest braces around initialization of subobject
    [-Werror,-Wmissing-braces]
        return {static_cast<bitmask_t>(mask_available().word ^ repeat_byte(0x80))};
                ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                {                                                                }
    In file included from
    /home/libc-buildbot/libc-aarch64-ubuntu/libc-aarch64-ubuntu-fullbuild-dbg/llvm-project/libc/src/search/hdestroy.cpp:10:
    /home/libc-buildbot/libc-aarch64-ubuntu/libc-aarch64-ubuntu-fullbuild-dbg/llvm-project/libc/src/__support/HashTable/table.h:336:41:
    error: suggest braces around initialization of subobject
    [-Werror,-Wmissing-braces]
      iterator end() const { return {0, 0, {0}, *this}; }
                                            ^
                                            {}

Link: https://lab.llvm.org/buildbot/#/builders/223/builds/33868/steps/6/logs/stdio
Link: https://github.com/llvm/llvm-project/pull/74506

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
Strangely, I haven't been able to reproduce the build bots failures when trying to cross compile a fullbuild. My cmake:

```
$ cmake ../runtimes -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_C_COMPILER=clang -G Ninja -DLLVM_ENABLE_LLD=ON -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_RUNTIMES="libc" -DLLVM_LIBC_FULL_BUILD=ON -DLIBC_HDRGEN_EXE=$HDRGEN -DLIBC_TARGET_TRIPLE=aarch64-linux-gnu
```

**Review by jhuber6 — COMMENTED** [review]
Could we construct these explicitly? It's difficult to see what it's supposed to be doing with the brace initialization.

**Comment by nickdesaulniers** [comment]
> Could we construct these explicitly? It's difficult to see what it's supposed to be doing with the brace initialization.

as in
```diff
diff --git a/libc/src/__support/HashTable/table.h b/libc/src/__support/HashTable/table.h
index 9b2f3beea996..61670a5db0e3 100644
--- a/libc/src/__support/HashTable/table.h
+++ b/libc/src/__support/HashTable/table.h
@@ -333,7 +333,9 @@ public:
     return {0, full_capacity() - available_slots,
             Group::load_aligned(&control(0)).occupied(), *this};
   }
-  iterator end() const { return {0, 0, {{0}}, *this}; }
+  iterator end() const {
+    return {0, 0, IteratableBitMask{{0}}, *this};
+  }
```
?

**Comment by jhuber6** [comment]
> > Could we construct these explicitly? It's difficult to see what it's supposed to be doing with the brace initialization.
> 
> as in
> 
> ```diff
> diff --git a/libc/src/__support/HashTable/table.h b/libc/src/__support/HashTable/table.h
> index 9b2f3beea996..61670a5db0e3 100644
> --- a/libc/src/__support/HashTable/table.h
> +++ b/libc/src/__support/HashTable/table.h
> @@ -333,7 +333,9 @@ public:
>      return {0, full_capacity() - available_slots,
>              Group::load_aligned(&control(0)).occupied(), *this};
>    }
> -  iterator end() const { return {0, 0, {{0}}, *this}; }
> +  iterator end() const {
> +    return {0, 0, IteratableBitMask{{0}}, *this};
> +  }
> ```
> 
> ?

I meant the iterator type, but yeah. It's just a little confusing to see so many brace initializers in one place, hence the warning.

**Comment by nickdesaulniers** [comment]
> I meant the iterator type,

Sorry, which of the two iterator types?  The return value of `end` or the `IteratableBitMask` itself?

(When we can use c++20, designated initialization can be used to make this crystal clear).

**Comment by jhuber6** [comment]
> > I meant the iterator type,
> 
> Sorry, which of the two iterator types? The return value of `end` or the `IteratableBitMask` itself?
> 
> (When we can use c++20, designated initialization can be used to make this crystal clear).

We're using `{0}` it implicitly create the iterator type rather than `iterator{0}` or whatever it is. I was just confused what it's actually trying to turn those arugment into since it just looks like any other uniform initialization

**Comment by nickdesaulniers** [comment]
> > > I meant the iterator type,
> > 
> > 
> > Sorry, which of the two iterator types? The return value of `end` or the `IteratableBitMask` itself?
> > (When we can use c++20, designated initialization can be used to make this crystal clear).
> 
> We're using `{0}` it implicitly create the iterator type rather than `iterator{0}` or whatever it is. I was just confused what it's actually trying to turn those arugment into since it just looks like any other uniform initialization

Done in https://github.com/llvm/llvm-project/pull/77345/commits/a18bd3bd2b625c53c00e1d38e67e151ddeebc670 PTAL

**Review by lntue — APPROVED** [review]

**Pull request merged**
