### PR TITLE
[clang][Sema] Add support for OpenBSD's syslog format attribute

### PR DESCRIPTION
**Pull request by brad0**

### CODE REVIEW

**Review by Endilll — COMMENTED** [review]
`Sema.h` changes look good.

**Review by Sirraide — COMMENTED** [review]
Hmm, this function also seems to exist on Linux, though. Additionally, from my `man syslog` docs:
> The remaining arguments are a format, as in `printf(3)`, and any arguments required by the format, except that the two-character sequence `%m` will be replaced by the error message string `strerror(errno)`.

I also know next to nothing about BSD and how its `syslog()` works, but we should support that extra `%m` specifier (if we don’t already do that because it’s apparently also a glibc extension for  `printf()`...). If the two of them differ, we might need two different format styles for BSD `syslog()` vs Linux `syslog()`.

**Comment by brad0** [comment]
> Hmm, this function also seems to exist on Linux, though. Additionally, from my `man syslog` docs:

I'm not sure what you mean by that in relation to this addition of a format attribute.

> > The remaining arguments are a format, as in `printf(3)`, and any arguments required by the format, except that the two-character sequence `%m` will be replaced by the error message string `strerror(errno)`.
> 
> I also know next to nothing about BSD and how its `syslog()` works, but we should support that extra `%m` specifier (if we don’t already do that because it’s apparently also a glibc extension for `printf()`...). If the two of them differ, we might need two different format styles for BSD `syslog()` vs Linux `syslog()`.

Should be more or less the same as Linux and the X/Open specified functions.

The `%m` specifier is not a glibc extension from what I can find.

**Comment by Sirraide** [comment]
>> Hmm, this function also seems to exist on Linux, though. Additionally, from my man syslog docs:

> I'm not sure what you mean by that in relation to this addition of a format attribute.

I think my question was mainly as to why `syslog` is treated as an OpenBSD feature (at least in `getFormatAttrKind`) if it’s not exclusive to OpenBSD, because Linux also seems to have it.

> The %m specifier is not a glibc extension from what I can find.

According to `man 3 printf` on my system:
image

Additionally:
https://github.com/llvm/llvm-project/blob/106621b601d7dc7c4929fba293f7e5ffe6b92c58/clang/lib/AST/PrintfFormatString.cpp#L346-L347

So it does seem like we already support this. In that case, amending the comment to include that it’s also used by `syslog()` (on both BSD and Linux) would be nice.

**Review by Sirraide — APPROVED** [review]
So yeah, this still needs a release note, and I don’t think we should be treating it / referring to it as an openbsd-exclusive feature, but apart from that the changes LGTM.

**Pull request merged**
