### PR TITLE
SafeStack: Respect alloca addrspace

### PR DESCRIPTION
**Pull request by arsenm**
Just insert addrspacecast in cases where the alloca uses a
different address space, since I don't know what else you
could possibly do.

### CODE REVIEW

**Comment by arsenm** [comment]
* **#112536** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/112536?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by vitalybuka** [comment]
I suspect SafeStack require address space of UnsafeStackPtr and StackPtr is the same.

Maybe just fatal error if address space of PointerType::getUnqual != DL.getAllocaPtrType?

**Comment by arsenm** [comment]
> Maybe just fatal error if address space of PointerType::getUnqual != DL.getAllocaPtrType?

That would defeat the point. It does produce an error if the realized __safestack_unsafe_stack_ptr type is wrong, test added

**Review by vitalybuka — APPROVED** [review]
I guess LGTM, not sure what we can do here better.

@eugenis do you see anything wrong with this approach?

**Pull request merged**
