### PR TITLE
[analyzer] EvalBinOpLL should return Unknown less often

### PR DESCRIPTION
**Pull request by steakhal**
SValBuilder::getKnownValue, getMinValue, getMaxValue use SValBuilder::simplifySVal.

simplifySVal does repeated simplification until a fixed-point is reached. A single step is done by SimpleSValBuilder::simplifySValOnce, using a Simplifier visitor. That will basically decompose SymSymExprs, and apply constant folding using the constraints we have in the State. Once it decomposes a SymSymExpr, it simplifies both sides and then uses the SValBuilder::evalBinOp to reconstruct the same - but now simpler - SymSymExpr, while applying some caching to remain performant.

This decomposition, and then the subsequent re-composition poses new challenges to the SValBuilder::evalBinOp, which is built to handle expressions coming from real C/C++ code, thus applying some implicit assumptions.

One previous assumption was that nobody would form an expression like "((int*)0) - q" (where q is an int pointer), because it doesn't really makes sense to write code like that.

However, during simplification, we may end up with a call to evalBinOp similar to this.

To me, simplifying a SymbolRef should never result in Unknown or Undef, unless it was Unknown or Undef initially or, during simplification we realized that it's a division by zero once we did the constant folding, etc.

In the following case the simplified SVal should not become UnknownVal:
```c++
void top(char *p, char *q) {
  int diff = p - q; // diff: reg<p> - reg<q>
  if (!p) // p: NULL
    simplify(diff); // diff after simplification should be: 0(loc) - reg<q>
}
```

Returning Unknown from the simplifySVal can weaken analysis precision in other places too, such as in SValBuilder::getKnownValue, getMinValue, or getMaxValue because we call simplifySVal before doing anything else.

For nonloc::SymbolVals, this loss of precision is critical, because for those the SymbolRef carries an accurate type of the encoded computation, thus we should at least have a conservative upper or lower bound that we could return from getMinValue or getMaxValue - yet we would just return nullptr.

```c++
const llvm::APSInt *SimpleSValBuilder::getKnownValue(ProgramStateRef state,
                                                      SVal V) {
  return getConstValue(state, simplifySVal(state, V));
}

const llvm::APSInt *SimpleSValBuilder::getMinValue(ProgramStateRef state,
                                                    SVal V) {
  V = simplifySVal(state, V);

  if (const llvm::APSInt *Res = getConcreteValue(V))
    return Res;

  if (SymbolRef Sym = V.getAsSymbol())
    return state->getConstraintManager().getSymMinVal(state, Sym);

  return nullptr;
}
```

For now, I don't plan to make the simplification bullet-proof, I'm just explaining why I made this change and what you need to look out for in the future if you see a similar issue.

CPP-5750

### CODE REVIEW

**Comment by steakhal** [comment]
@necto

**Review by Xazax-hun — COMMENTED** [review]
Makes sense for me. It would be nice if we had a minimal reproducer for a regression test instead of maintaining a large-ish test.

**Review by Xazax-hun — APPROVED** [review]

**Comment by Xazax-hun** [comment]
> To me, simplifying a SymbolRef should never result in Unknown or Undef, unless it was Unknown or Undef initially or, during simplification we realized that it's a division by zero once we did the constant folding, etc.

I understand that we might not be ready for this, but feels like at some point we should have this as a form of an assertion. I am not sure about the `Undef` part because there are many ways to get to undef during constant folding (signed overflows, division by zero, OOB access of an array, defer of an invalid pointer). Even if some of those cannot happen during the current simplification they might be modeled later. So, I think a simpler "the result can only be Unknown if the input was also Unknown" would make a lot of sense to me.

**Comment by steakhal** [comment]
> Makes sense for me. It would be nice if we had a minimal reproducer for a regression test instead of maintaining a large-ish test.

I wish I could add a LIT test instead.
Out of the get min/max val, or getKnownValue APIs, only the latter is used slightly more broadly, where the callsites can't assume it should return a valid result. Still, these APIs are barely used.
In my case I have additional context in my downstream checker, where I can make this assumption and I was surprised to see crashes. So I had no other options but to craft a unittest for this.

**Comment by NagyDonat** [comment]
Offtopic @Xazax-hun
> there are many ways to get to undef during constant folding (signed overflows ...

I was surprised to read this because as far as I know (knew) the analyzer models signed operations as if overflow was completely natural for them. (See e.g. the method `assumeInBound` which IIRC relies on this to convert a "within this interval" check to a ">= some threshold" check. I also vaguely recall that there are many FPs where the analyzer assumes wraparond of signed values.)

I would be very grateful if somebody pointed out some logic in the analyzer source which ensures that a signed overflow produces an `UndefinedVal` (or the overflow is disallowed by some other mechanism). If I was right and we don't have such code yet, then it might be good to add some...

**Comment by steakhal** [comment]
> Offtopic @Xazax-hun
> 
> > there are many ways to get to undef during constant folding (signed overflows ...
> 
> I was surprised to read this because as far as I know (knew) the analyzer models signed operations as if overflow was completely natural for them. (See e.g. the method `assumeInBound` which IIRC relies on this to convert a "within this interval" check to a ">= some threshold" check. I also vaguely recall that there are many FPs where the analyzer assumes wraparond of signed values.)
> 
> I would be very grateful if somebody pointed out some logic in the analyzer source which ensures that a signed overflow produces an `UndefinedVal` (or the overflow is disallowed by some other mechanism). If I was right and we don't have such code yet, then it might be good to add some...

I think we don't have any mechanisms like these. This was just a theoretical comment if I understood it right.

**Comment by Xazax-hun** [comment]
> I think we don't have any mechanisms like these. This was just a theoretical comment if I understood it right.

Actually, both. Yes, we don't have many of these in the engine as of today, but we do model some overflows in some checkers, like the bitwise shifts checker. It would be nice if we could write that logic once, and reuse it in constant folding as well, but this is really theoretical at this point.

**Pull request merged**
