### PR TITLE
release/18.x: [clang-format] Don't always break before << between str…

### PR DESCRIPTION
**Pull request by owenca**
…ing literals (#92214)

### CODE REVIEW

**Review by mydeveloperday — APPROVED** [review]

**Comment by owenca** [comment]
@tstellar can we also get this one into 18.1.7?

**Comment by tstellar** [comment]
@owenca I'm only going to take regression fixes for 18.1.7.

**Comment by owenca** [comment]
@tstellar strictly speaking, this is a regression fix. (It's a churn within 18.x release cycle.)

1. Risk level: low IMO. (The other code owner @mydeveloperday approved it to be included in 18.1.7.)
2. Last known working version: 18.1.4

**Comment by tstellar** [comment]
@owenca Do you have a release note we can put in the release announcement?

**Comment by owenca** [comment]
@tstellar thanks!

> @owenca Do you have a release note we can put in the release announcement?

Release note:
Fixes clang-format (since 18.1.1) regressions on breaking before a stream insertion operator (<<) when both operands are string literals.

**Pull request merged**
