### PR TITLE
Avoid buffer hoisting from parallel loops

### PR DESCRIPTION
**Pull request by rafaelubalmw**
This change corrects an invalid behavior in pass `--buffer-loop-hoisting`. The pass is in charge of extracting buffer allocations (e.g., `memref.alloca`) from loop regions (e.g., `scf.for`) when possible. This works OK for looks with sequential execution semantics. However, a buffer allocated in the body of a parallel loop may be concurrently accessed by multiple thread to store its local data. Extracting such buffer from the loop causes all threads to wrongly share the same memory region.

In the following example, dimension 1 of the input tensor is reversed. Dimension 0 is traversed with a parallel loop.

```
func.func @f(%input: memref<2x3xf32>) -> memref<2x3xf32> {
  %c0 = index.constant 0
  %c1 = index.constant 1
  %c2 = index.constant 2
  %c3 = index.constant 3

  %output = memref.alloc() : memref<2x3xf32>
  scf.parallel (%index) = (%c0) to (%c2) step (%c1) {
    // Create subviews for working input and output slices
    %input_slice = memref.subview %input[%index, 2][1, 3][1, -1] : memref<2x3xf32> to memref<1x3xf32, strided<[3, -1], offset: ?>>
    %output_slice = memref.subview %output[%index, 0][1, 3][1, 1] : memref<2x3xf32> to memref<1x3xf32, strided<[3, 1], offset: ?>>

    // Copy the input slice into this temporary buffer. This intermediate
    // copy is unnecessary, but is used for illustration purposes.
    %temp = memref.alloc() : memref<1x3xf32>
    memref.copy %input_slice, %temp : memref<1x3xf32, strided<[3, -1], offset: ?>> to memref<1x3xf32>

    // Copy temporary buffer into output slice
    memref.copy %temp, %output_slice : memref<1x3xf32> to memref<1x3xf32, strided<[3, 1], offset: ?>>
    scf.reduce
  }

  return %output : memref<2x3xf32>
}
```

The patch submitted here prevents `%temp = memref.alloc() : memref<1x3xf32>` from being hoisted when the containing op is `scf.parallel` or `scf.forall`. A new op trait called `HasParallelRegion` is introduced and assigned to these two ops to indicate that their regions have parallel execution semantics.

@joker-eph @ftynse @nicolasvasilache @sabauma

### CODE REVIEW

**Comment by Hardcode84** [comment]
+1, we have also encountered this bug in the past, thanks for fixing this.

My only comment is `OpDefinition.h` may be not the best place for a new trait as it included by everyone and trait is somewhat usecase-specific. Maybe move it to `LoopLikeInterface.td/h`?

**Comment by rafaelubalmw** [comment]
Thanks for the feedback, @Hardcode84. That's a good suggestion. I've updated the PR as advised.

**Review by Hardcode84 — APPROVED** [review]
LGTM, thanks

**Review by matthias-springer — APPROVED** [review]

**Comment by matthias-springer** [comment]
now that we have a new trait, can you also try to remove isParallelRegion (https://github.com/llvm/llvm-project/blob/main/mlir/include/mlir/Dialect/Bufferization/IR/BufferizableOpInterface.td#L559) as part of this change? (or in a follow up commit)

**Comment by rafaelubalmw** [comment]
Good idea, @matthias-springer. Let me send that as part of a separate PR. I'll tag you as a reviewer.

**Pull request merged**
