### PR TITLE
[Docs] Fix large vertical space at top of pages

### PR DESCRIPTION
**Pull request by jryans**
This fixes a large vertical blank space at the top of the page that was caused by the floating sidebar.

## Before

image

## After

image

### CODE REVIEW

**Comment by jryans** [comment]
I wasn't too sure who to select for reviewers here, as I don't think many work on docs styling... 😅 If you have any reviewer suggestions, please add them!

**Review by SLTozer — COMMENTED** [review]
There are already styles for `body` and `div.sphinxsidebar` - is there a reason for adding these changes under new selectors? There is the comment, but it doesn't look like we actually use these kind of explanatory comments in css regardless.

**Comment by jryans** [comment]
> There are already styles for `body` and `div.sphinxsidebar` - is there a reason for adding these changes under new selectors? There is the comment, but it doesn't look like we actually use these kind of explanatory comments in css regardless.

Purely for grouping together with the comment, which I thought might be clearer for the next CSS archaeologist that passes through. You're right that's not the style used here though. I think the bulk of this file is providing an appearance and not "fixing quirks" like this, so that's perhaps on point in favour of what I've done here.

Anyway, I'm happy to remove the comment and fold into exist rule sets if that's the preferred way to go! 🙂

**Review by SLTozer — COMMENTED** [review]
I've not got a strong opinion on it either way, it's not my domain - but if nobody with more of investment in our css comes by to disagree, this LGTM (so safest to wait a bit for further comments).

**Comment by jryans** [comment]
I moved the changes into existing rule sets as @SLTozer suggested.

No other feedback so far... I assume that's because no one really thinks about this area. This seems like a clear improvement, so I'll go ahead and merge it.

**Pull request merged**
