### PR TITLE
[ADT][NFC] Simplify SmallSet

### PR DESCRIPTION
**Pull request by vhscampos**
- Remove dependence on `STLExtras.h`.
- Remove unused header inclusions.
- Make `count` use `contains` for deduplication.
- Replace hand-written linear scans on Vector by `std::find`.

### CODE REVIEW

**Review by kuhar — APPROVED** [review]
LGTM. Could you also add [NFC] to the PR title?

**Comment by nikic** [comment]
Looks like this change has a small negative compile-time impact: https://llvm-compile-time-tracker.com/compare.php?from=0c31ea5a09d854d5891eac40629f6a17a66fdcf7&to=ce6c236c965dc1bb5fa2257e17ea253a015705cc&stat=instructions:u Not obvious to me why that should be.

**Comment by nikic** [comment]
Okay, I tried a few things, and can reproduce the regression just by using std::find inside vfind: https://github.com/llvm/llvm-project/commit/21f98691f6e7d8664c094bd4218a508432ab2d23

My best guess at the cause would be the forced unroll in: https://github.com/gcc-mirror/gcc/blob/819098dc71f2079aedc15a904ab5f17f0788d991/libstdc%2B%2B-v3/include/bits/stl_algobase.h#L2107 These finds works on small numbers of iterations (often just up to 4), so probably that forced unroll is not profitable.

It may make sense to restore vfind with a comment on why it's there.

**Comment by vhscampos** [comment]
Thanks for the investigation @nikic . I'll have a patch restoring `vfind` with an explanatory comment tomorrow.

**Pull request merged**
