### PR TITLE
[LLD][COFF] add __buildid symbol.

### PR DESCRIPTION
**Pull request by ZequanWu**
After #71433, lld-link is able to always generate build id even when PDB is not generated.

This adds the `__buildid` symbol to points to the start of 16 bytes guid (which is after `RSDS`) and allows profile runtime to access it and dump it to raw profile.

### CODE REVIEW

**Comment by rnk** [comment]
Can we handle this like `_load_config_used`, so the symbol only appears when referenced, kind of like with a static archive?
https://github.com/llvm/llvm-project/blob/main/lld/COFF/Driver.cpp#L2427

**Comment by ZequanWu** [comment]
> Can we handle this like `_load_config_used`, so the symbol only appears when referenced, kind of like with a static archive? https://github.com/llvm/llvm-project/blob/main/lld/COFF/Driver.cpp#L2427

Done.

**Review by rnk — APPROVED** [review]
Thanks! I think we can land this.

**Comment by petrhosek** [comment]
Can we avoid `lld` in the name and call it just `__buildid`? I'm worried that calling it `__lld_buildid` might discourage other COFF linkers from adopting it.

**Comment by rnk** [comment]
> Can we avoid `lld` in the name and call it just `__buildid`? I'm worried that calling it `__lld_buildid` might discourage other COFF linkers from adopting it.

That's reasonable. Can we make the name even more descriptive to reduce the risk of symbol conflicts? There are many implementers in the implementer's namespace (`__`). One idea: `__buildid_guid` `__build_guid` (it is a GUID, isn't it?).

**Comment by mstorsjo** [comment]
> > Can we avoid `lld` in the name and call it just `__buildid`? I'm worried that calling it `__lld_buildid` might discourage other COFF linkers from adopting it.
> 
> That's reasonable. Can we make the name even more descriptive to reduce the risk of symbol conflicts? There are many implementers in the implementer's namespace (`__`). One idea: `__buildid_guid` `__build_guid` (it is a GUID, isn't it?).

IIRC this doesn't point at a pure GUID, but at a whole debug directory which does contain a GUID and some timestamps and stubs for descriptions about the debug info.

**Comment by ZequanWu** [comment]
> > > Can we avoid `lld` in the name and call it just `__buildid`? I'm worried that calling it `__lld_buildid` might discourage other COFF linkers from adopting it.
> > 
> > 
> > That's reasonable. Can we make the name even more descriptive to reduce the risk of symbol conflicts? There are many implementers in the implementer's namespace (`__`). One idea: `__buildid_guid` `__build_guid` (it is a GUID, isn't it?).
> 
> IIRC this doesn't point at a pure GUID, but at a whole debug directory which does contain a GUID and some timestamps and stubs for descriptions about the debug info.

This points to the 24 bytes GUID which starts with `RSDS` followed by 16 bytes hash and 4 bytes age.

**Comment by ZequanWu** [comment]
Renamed to `__build_guid`.

**Comment by rnk** [comment]
> Sorry, not to be nitpicky, but generally, GUID (or UUID) refers to a 128 bit ID, which in this case would be the 16 bytes hash. So if we call this `__build_guid`, someone might read only the following 16 bytes, which contains the `RSDS` header and only 12 bytes of actual hash - which isn't what probably was intended.
> 
> So either we have the symbol pointing at the raw hash and call it hash or GUID something like that, or we probably should make it clearer in the name that it actually is a debug directory structure.

No worries, I share your concern, if it's not a real 16 byte GUID, we shouldn't call it one.

To your point, this change should document the expected struct.

**Comment by ZequanWu** [comment]
> > > > > Can we avoid `lld` in the name and call it just `__buildid`? I'm worried that calling it `__lld_buildid` might discourage other COFF linkers from adopting it.
> > > > 
> > > > 
> > > > That's reasonable. Can we make the name even more descriptive to reduce the risk of symbol conflicts? There are many implementers in the implementer's namespace (`__`). One idea: `__buildid_guid` `__build_guid` (it is a GUID, isn't it?).
> > > 
> > > 
> > > IIRC this doesn't point at a pure GUID, but at a whole debug directory which does contain a GUID and some timestamps and stubs for descriptions about the debug info.
> > 
> > 
> > This points to the 24 bytes GUID which starts with `RSDS` followed by 16 bytes hash and 4 bytes age.
> 
> Sorry, not to be nitpicky, but generally, GUID (or UUID) refers to a 128 bit ID, which in this case would be the 16 bytes hash. So if we call this `__build_guid`, someone might read only the following 16 bytes, which contains the `RSDS` header and only 12 bytes of actual hash - which isn't what probably was intended.
> 
> So either we have the symbol pointing at the raw hash and call it hash or GUID something like that, or we probably should make it clearer in the name that it actually is a debug directory structure.

I added an offset field in `DefinedSynthetic` and let `__build_guid` points to 4 bytes after the CVDebugRecordChunk. So it will points to the 16 byte raw hash.

I tested on Windows, and this allows me to print the 16 byte `__build_guid` directly.

**Review by rnk — COMMENTED** [review]
I think we should go back to `__buildid`, I withdraw my suggestion for a more descriptive name. I'm just concerned someone will come along and tell us "this is not really a GUID", and then we'll look silly for using this name.

**Comment by ZequanWu** [comment]
> I think we should go back to `__buildid`, I withdraw my suggestion for a more descriptive name. I'm just concerned someone will come along and tell us "this is not really a GUID", and then we'll look silly for using this name.

Renamed to `__buildid`. This still points to the 16 bytes hash after "RSDS".

**Review by rnk — APPROVED** [review]
I think this looks good and addresses everyone's concerns other than my descriptive names feedback tangent. Please confirm that the final git commit title is correct, since the PR title looks stale.

**Pull request merged**
