### PR TITLE
Bump version to 18.1.7

### PR DESCRIPTION
**Pull request by tstellar**

### CODE REVIEW

**Comment by whentojump** [comment]
Hi @tstellar are we planning to have one more 18.x release?

**Comment by tstellar** [comment]
@whentojump Yes, but I'm only going to accept critical fixes or regressions for this one.

**Comment by whentojump** [comment]
Thanks for the info.

Will you please consider https://github.com/llvm/llvm-project/compare/release/18.x...chapuni:llvm-project:release/18.x, which fixes an assertion violation? If so, I can do a PR.

cc @chapuni

**Comment by chapuni** [comment]
@tstellar @whentojump They will make clang able to build and test clang itself with MC/DC instrumentation.
I really hope they could be pulled. Thank you.

**Pull request merged**
