### PR TITLE
[libc++] Implement library support for MCF thread model

### PR DESCRIPTION
**Pull request by lhmouse**
This commit allows building libcxx and libcxxabi with

  cmake -DLIBCXX_HAS_MCF_THREAD_API=ON \
        -DLIBCXXABI_HAS_MCF_THREAD_API=ON \
        ...

This commit adds a new macro, `_LIBCPP_HAS_THREAD_API_MCF`, to indicate that the libraries have been built with MCF thread model.

These functions, and member functions of these classes, are implemented directly in libmcfgthread. The list is exhaustive. If someone wants to implement more, such as `std::counting_semaphore` and `std::timed_mutex`, please let me know:

  * `__cxa_guard_acquire()`
  * `__cxa_guard_release()`
  * `__cxa_guard_abort()`
  * `std::mutex`
  * `std::call_once()`
  * `std::recursive_mutex`
  * `std::condition_variable`
  * `std::thread`
  * `std::this_thread::get_id()`
  * `std::this_thread::sleep_for()`
  * `std::this_thread::yield()`

Reference: https://gcc.gnu.org/git/?p=gcc.git;a=commit;h=f036d759ecee538555fa8c6b11963e4033732463
Reference: https://github.com/lhmouse/mcfgthread/wiki/How-the-MCF-thread-model-works

### CODE REVIEW

**Comment by lhmouse** [comment]
Building with clang-cl fails with a strange error:

> [1/314] Generate the mapping file for include-what-you-use
FAILED: include/c++/v1/libcxx.imp E:/lh_mouse/Desktop/libcxx-build/include/c++/v1/libcxx.imp
cd /D E:\lh_mouse\Desktop\libcxx-build\include
CreateProcess failed: The system cannot find the file specified.
[3/314] Copying CXX header __thread/support.hninja: fatal: ReadFile: The handle is invalid.

**Comment by lhmouse** [comment]
What's the limit of characters perline in llvm? I see some errors from clang-format but not all of them are about my changes.

There was a test that timed  which I have no idea at the moment: https://github.com/llvm/llvm-project/actions/runs/11884156644/job/33112784777?pr=116550#step:4:4140
(Is it about MSVC? then how does it run on self-hosted Linux?)

**Comment by frederick-vs-ja** [comment]
> What's the limit of characters perline in llvm? I see some errors from clang-format but not all of them are about my changes. I usually hard-wrap lines around 80 (mostly before, sometimes after) however in llvm there are much longer lines, around 120 characters.

In libc++ the limit is 120. (Although the limit is 80 for some files under `/llvm`, which is inconsistent.)

> There was a test that timed which I have no idea at the moment: https://github.com/llvm/llvm-project/actions/runs/11884156644/job/33112784777?pr=116550#step:4:4140
> (Is it about MSVC? then how does it run on self-hosted Linux?)

This error doesn't always occurs. It seems that the error is sometimes ignored when merging.

The test doesn't require MSVC. The name was because of that the test was cloned from [MSVC STL's corresponding test](https://github.com/microsoft/STL/tree/44a276fdff3463f7e0ab547458850c16925cab06/tests/std/tests/P0067R5_charconv).

**Comment by frederick-vs-ja** [comment]
We can rebase the patch now as the test is (temporarily?) disabled for MSan by #116933.

**Comment by lhmouse** [comment]
Done now.

**Comment by ldionne** [comment]
This is on my stack of reviews, I should get to it tomorrow.

**Review by ldionne — COMMENTED** [review]
At a high-level, the first point of discussion IMO is how this new "backend" is integrated into libc++. As it stands, you do this:

```c++
#elif defined(_LIBCPP_HAS_THREAD_API_MCF)
#    include <mcfgthread/libcxx.h>
```

In other words, the code is pulled in from elsewhere (presumably https://github.com/lhmouse/mcfgthread/blob/master/mcfgthread/libcxx.h), and it's assumed to be available. Instead, I would expect the libc++ entry points to be defined _in libc++_ itself, and then for these functions to call into the MCF runtime as needed. What would you think of that approach instead? The reason why this is fairly important is that we normally don't include random "external" headers from libc++ (with the exception of `__external_threading`, which should be redesigned). This also means that libc++ isn't self-sufficient anymore -- it needs to pull in a header from another project in order to build in that configuration, which also means that we can't officially test (hence officially support) this configuration.

For all these reasons, I think it would be better if the libc++-specific API were contained inside libc++, and libc++ only called into MCF entry points defined in the appropriate DLL. To use this configuration, it would then be sufficient to
1. Install the MCF runtime
2. Build libc++ with `LIBCXX_HAS_MCF_THREAD_API=ON`

I'd also like to remind that contributions must be under the Apache license with the LLVM exception, so this must be kept in mind in case the libc++-specific part of the API is contributed here.

**Comment by lhmouse** [comment]
> In other words, the code is pulled in from elsewhere (presumably https://github.com/lhmouse/mcfgthread/blob/master/mcfgthread/libcxx.h), and it's assumed to be available.

This is correct.

> Instead, I would expect the libc++ entry points to be defined _in libc++_ itself, and then for these functions to call into the MCF runtime as needed. What would you think of that approach instead? The reason why this is fairly important is that we normally don't include random "external" headers from libc++ (with the exception of `__external_threading`, which should be redesigned). This also means that libc++ isn't self-sufficient anymore -- it needs to pull in a header from another project in order to build in that configuration, which also means that we can't officially test (hence officially support) this configuration.

Indeed, for GCC and libstdc++ it's an external library. However winpthreads is also not a system library. If, by definition, 'anything that exists in mingw-w64' is not an external library, I can try committing a replica into mingw-w64-libraries. This was mentioned some years ago but it has not been done.

Another option is below:

> For all these reasons, I think it would be better if the libc++-specific API were contained inside libc++, and libc++ only called into MCF entry points defined in the appropriate DLL. To use this configuration, it would then be sufficient to
> 
> 1. Install the MCF runtime
> 2. Build libc++ with `LIBCXX_HAS_MCF_THREAD_API=ON`
> 
> I'd also like to remind that contributions must be under the Apache license with the LLVM exception, so this must be kept in mind in case the libc++-specific part of the API is contributed here.

It looks to me that another option is to copy 'mcfgthread/libcxx.h' into libc++..? Not sure whether I got your idea.

All headers from mcfgthread are public domain and can be freely copied. (Trivia: Previously they were declared as public domain. However it's kinda self-contradiction that the license applies to something it does not apply or vice versa. The new license says it applies to headers but headers can be used in public domain instead.)

**Comment by ldionne** [comment]
> 
> It looks to me that another option is to copy 'mcfgthread/libcxx.h' into libc++..? Not sure whether I got your idea.

Without necessarily copying (due to licensing constraints), but yeah the idea would be to have the bridge-to-MFC inside libc++ instead of elsewhere.

> 
> All headers from mcfgthread are public domain and can be freely copied. (Trivia: Previously they were declared as public domain. However it's kinda self-contradiction that the license applies to something it does not apply or vice versa. The new license says it applies to headers but headers can be used in public domain instead.)

This isn't really the right forum for discussing licensing or copyright matters, but if you're able to contribute an implementation of the above under the LLVM license, that would be the preferred way of supporting that configuration. As I said before, what we basically don't want is to check-in code in libc++ that blindly includes external code that doesn't exist in libc++ -- since that makes such code dead as far as we're concerned (CI, etc). If you have questions about licensing, I think I would direct you towards board@llvm.org.

**Comment by lhmouse** [comment]
> > It looks to me that another option is to copy 'mcfgthread/libcxx.h' into libc++..? Not sure whether I got your idea.
> 
> Without necessarily copying (due to licensing constraints), but yeah the idea would be to have the bridge-to-MFC inside libc++ instead of elsewhere.

Understood. Thank you.

**Pull request closed without merging**
