### PR TITLE
[LLDB][TableGen] Migrate lldb-tblgen to use const RecordKeeper

### PR DESCRIPTION
**Pull request by jurahul**
Migrate LLDB TableGen backend to use const RecordKeeper.

This is a part of effort to have better const correctness in TableGen backends:

 https://discourse.llvm.org/t/psa-planned-changes-to-tablegen-getallderiveddefinitions-api-potential-downstream-breakages/81089

### CODE REVIEW

**Comment by DavidSpickett** [comment]
Is this part of a larger effort, do you have a link to an RFC or previous PRs?

I assume the motivation is const correctness?

**Comment by jurahul** [comment]
Yes, the motivation is const correctness. Please see the discourse thread here: https://discourse.llvm.org/t/psa-planned-changes-to-tablegen-getallderiveddefinitions-api-potential-downstream-breakages/81089

**Comment by DavidSpickett** [comment]
Great, please add that link to the PR description and then this can land.

**Comment by jurahul** [comment]
Done.

**Review by DavidSpickett — APPROVED** [review]

**Pull request merged**
