### PR TITLE
Fix SemaCXX/msvc-pragma-function-no-builtin-attr.cpp test

### PR DESCRIPTION
**Pull request by VScigolevs**
Fix test failure from 84b0f0145887bbfe49fd4dc85490b14108a72cee

### CODE REVIEW

**Comment by pawosm-arm** [comment]
I suppose this is the reason check-clang fails today.

**Comment by RIscRIpt** [comment]
This should fix https://lab.llvm.org/buildbot/#/builders/190/builds/11300

I am compiling clang locally to verify that there would be no other problems with the test on macOS.

> I suppose this is the reason check-clang fails today.

Are there other test failures related to 84b0f0145887bbfe49fd4dc85490b14108a72cee ?

**Review by ridzenis — APPROVED** [review]
LGTM, this fixes `clang/test/SemaCXX/msvc-pragma-function-no-builtin-attr.cpp` on macOS.

**Comment by DzenIsRich** [comment]
> I'm seeing this on Linux: ...

Yes, the same problem. It should be fixed now.

**Comment by RIscRIpt** [comment]
> I'm seeing this on Linux: ...

Yes, the same problem. It should be fixed now.

**Pull request merged**
