### PR TITLE
Add truncxfhf2 with tests to compiler-rt

### LINKED ISSUE #105181: [builtins] Missing `__extendhfxf2` and `__truncxfhf2`
These functions convert their argument between `_Float16` and x86 80-bit `long double`.

https://godbolt.org/z/YqWsToYde

C++ code:

```cpp
long double foo(_Float16 x) {
    return x;
}
```

Error when running Clang with `-rtlib=compiler-rt`:

```
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/15.0.0/../../../../x86_64-linux-gnu/bin/ld: /tmp/example-2fb810.o: undefined reference to symbol '__extendhfxf2@@GCC_12.0.0'
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/15.0.0/../../../../x86_64-linux-gnu/bin/ld: /opt/compiler-explorer/gcc-snapshot/lib64/libgcc_s.so.1: error adding symbols: DSO missing from command line
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
Compiler returned: 1
```

C++ code:

```cpp
_Float16 bar(long double x) {
    return static_cast<_Float16>(x);
}
```

Error when running Clang with `-rtlib=compiler-rt`:

```
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/15.0.0/../../../../x86_64-linux-gnu/bin/ld: /tmp/example-32f526.o: undefined reference to symbol '__truncxfhf2@@GCC_12.0.0'
/opt/compiler-explorer/gcc-snapshot/lib/gcc/x86_64-linux-gnu/15.0.0/../../../../x86_64-linux-gnu/bin/ld: /opt/compiler-explorer/gcc-snapshot/lib64/libgcc_s.so.1: error adding symbols: DSO missing from command line
clang++: error: linker command failed with exit code 1 (use -v to see invocation)
Compiler returned: 1
```

cc @lntue

### PR DESCRIPTION
**Pull request by biabbas**
Fixes #105181 

Regards,

### CODE REVIEW

**Comment by biabbas** [comment]
cc @arichardson

**Comment by biabbas** [comment]
review @arichardson

**Review by arichardson — APPROVED** [review]

**Comment by rorth** [comment]
This patch broke the [Solaris/amd64 buildbot](https://lab.llvm.org/staging/#/builders/120/builds/4677).

**Comment by biabbas** [comment]
@rorth It seems to be because of an U suffix in line 51. I'll fix it now.

**Pull request merged**
