### PR TITLE
Mark `mlir::Value::isa/dyn_cast/cast/...` member functions deprecated.

### PR DESCRIPTION
**Pull request by chsigg**
See https://mlir.llvm.org/deprecation and https://discourse.llvm.org/t/preferred-casting-style-going-forward/68443/4

### CODE REVIEW

**Review by joker-eph — COMMENTED** [review]
Thanks!

Coincidentally I saw these yesterday and wanted to do the same patch! (but unlikely I would have got there anytime soon)

**Comment by chsigg** [comment]
Unfortunately, I realized that the repo is not cleaned up at all yet. I limited this PR to just `mlir::Value` for now and I will follow up with the other types (`Attribute/Location/Type`).

**Comment by tblah** [comment]
Flang changes LGTM. Thanks

**Comment by chsigg** [comment]
The msvc build failure (`fatal error C1060: compiler is out of heap space`) seems unrelated.

**Pull request merged**
