### PR TITLE
[clang-format] Fix working -assume-filename with .clang-format-ignore

### LINKED ISSUE #113099: [clang-format] .clang-format-ignore ignores -assume-filename option
The filename given by the `-assume-filename` option is used to search for `.clang-format` files, etc., but is not used to match the contents of the `.clang-format-ignore` file.

For example, the C/C++ extension of VSCode uses the `-assume-filename` option to provide a filename, and the content to be formatted is provided from standard input. Therefore, the `.clang-format-ignore` file will not work for that extension.

### PR DESCRIPTION
**Pull request by kakkoko**
Fixes #113099.

### CODE REVIEW

**Review by mydeveloperday — COMMENTED** [review]
I get what you are doing here, simply passing the input to the output even if we've said ignore the file.. Its not that I don't think this is ok I'm just wondering why the fix is here and not in the VS Code extension. I'd like to hear @owenca  opinion

**Comment by owenca** [comment]
Also, the main purpose of `-assume-filename` is to set the language for input from stdin, and IMO the pseudo filename should not be filtered out by any .clang-format-ignore file.

**Comment by kakkoko** [comment]
> Also, the main purpose of -assume-filename is to set the language for input from stdin, and IMO the pseudo filename should not be filtered out by any .clang-format-ignore file.

It is also worth noting that if the `-style=file` option is specified, it will look for `.clang-format`/`_clang-format` file in the same or parent directory.

Since the specification is such for `.clang-format`/`_clang-format` file, users would naturally expect the same behavior for `.clang-format-ignore` file, wouldn't they?

**Review by mydeveloperday — APPROVED** [review]
I think this makes sense now, please wait for @owenca  and @HazardyKnusperkeks  opinion

**Comment by kakkoko** [comment]
@mydeveloperday 

> However what you are saying is, its not using that assume-filename to locate the .clang-format-ignore file?
> 
> Hence in the IDE it reformats myfile.* meaning you can't save it unformatted

Yes, that is correct.

You can see that in [the following file of `Clang-Format.cpp`, `main()`](https://github.com/llvm/llvm-project/blob/llvmorg-19.1.2/clang/tools/clang-format/ClangFormat.cpp#L709-L735):

```c++
  // If no file name is specified on the command line to be processed,
  // formatting is performed on standard input and terminates.
  if (FileNames.empty())
    return clang::format::format("-", FailOnIncompleteFormat);

  ...

  // Sequentially process each file specified on the command line
  for (const auto &FileName : FileNames) {
    // Check for .clang-format-ignore
    const bool Ignored = isIgnored(FileName);
    ...
    // If the pattern matches the pattern written in .clang-format-ignore,
    // do nothing and proceed to the next file
    if (Ignored)
      continue;
    ...
    // do formatting
    Error |= clang::format::format(FileName, FailOnIncompleteFormat);
  }
```

The `isIgnored()` function, which determines whether or not to ignore using `.clang-format-ignore`, is only called in the part that processes the files enumerated on the command line in order.

**Review by HazardyKnusperkeks — APPROVED** [review]

**Comment by kakkoko** [comment]
@owenca Thanks for the review. I applied all of the suggestions as I thought they were all appropriate.

**Review by owenca — APPROVED** [review]

**Pull request merged**
