### PR TITLE
[compiler-rt] Fix C and C++ compilers being switched when compiling tests

### PR DESCRIPTION
**Pull request by tambry**
The logic was simply switched. Fixes building tests for me.  
Not sure how I haven't stumbled upon this before considering this code hasn't changed lately and my setup's been the same.

Fixes: 07317bbc66d1f2d7663af3c9f04d0f6c0487ac03

### CODE REVIEW

**Review by arichardson — APPROVED** [review]
Good catch, I guess it didn't matter in most cases since clang will parse .cc files as C++ by default.

**Comment by tambry** [comment]
Thanks for the quick approval!

**Comment by arichardson** [comment]
> Thanks for the quick approval!

Do you have commit access or would you like me to merge it?

**Comment by tambry** [comment]
Have commit access, but had to wait for the CI to finish. :slightly_smiling_face:

**Pull request merged**
