### PR TITLE
Optimize circular buffers

### PR DESCRIPTION
**Pull request by AZero13**
Optimized circular buffers where it can be proven that we can compare instead of doing the division.

### CODE REVIEW

**Review by adrian-prantl — COMMENTED** [review]
The changes from int -> unsigned look like a good improvement to me. Can clang perform the same optimization for the modulus operation? If yes, I think I prefer the original code. If not, this LGTM.

**Comment by felipepiovezan** [comment]
I don't think the compiler performs the optimization is either case:
https://godbolt.org/z/xqeY8zaE6

FWIW unsigned overflow is defined behavior, so `x +1 == end` will do the _wrong_ thing if `x` is unsigned and `x+1` overflows and the type of `end` is something larger like uint64_t. 

The same situation when `x` is `int` is undefined behavior and would be caught by tooling.

**Comment by adrian-prantl** [comment]
Should we add checks for overflow then? LLVM has some addition with overflow helper functions.

**Comment by AtariDreams** [comment]
> Should we add checks for overflow then? LLVM has some addition with overflow helper functions.

No need. it is proven that it won't happen.

**Pull request closed without merging**
