### PR TITLE
[CMake] Preserve clang-prebolt

### PR DESCRIPTION
**Pull request by aaupov**
In Clang-BOLT step, preserve pre-BOLT Clang binary (as well as clang++
symlink). 

Also modify the default set of BOLT flags:
- drop ICF (can mess with unwinders),
- switch from hfsort+ to cdsort (aliases),
- enable CDSplit,
- update debug sections.

### CODE REVIEW

**Review by maksfb — APPROVED** [review]
Thanks!

PS. Let's drop ICF from the flags.

**Comment by madhur13490** [comment]
This commit is breaking LTO-PGO-BOLT build while optimizing clang with BOLT. 

```
[3064/3065] Merging BOLT fdata
Using legacy profile format.
Profile from 2 files merged.
[3064/3065] Optimizing Clang with BOLT
BOLT-INFO: shared object or position-independent executable detected
BOLT-INFO: Target architecture: aarch64
BOLT-INFO: BOLT version: 51d1d03b17bb8bf66b6422c4482d8d615ab53409
BOLT-INFO: first alloc address is 0x0
BOLT-INFO: enabling relocation mode
BOLT-INFO: pre-processing profile using branch profile reader
BOLT-WARNING: 1 collisions detected while hashing binary objects. Use -v=1 to see the list.
BOLT-INFO: number of removed linker-inserted veneers: 0
BOLT-INFO: 11906 out of 212101 functions in the binary (5.6%) have non-empty execution profile
BOLT-INFO: 272 functions with profile could not be optimized
BOLT-INFO: profile for 1 objects was ignored
BOLT-INFO: removed 1 empty block
BOLT-INFO: basic block reordering modified layout of 4273 functions (35.89% of profiled, 2.01% of total)
BOLT-INFO: UCE removed 1 blocks and 4 bytes of code
BOLT-INFO: 68 Functions were reordered by LoopInversionPass
<unknown>:0: error: fixup value out of range
<unknown>:0: error: fixup value out of range
<unknown>:0: error: fixup value out of range
<unknown>:0: error: fixup value out of range
<unknown>:0: error: fixup value out of range
<unknown>:0: error: fixup value out of range
<unknown>:0: error: fixup value out of range
<unknown>:0: error: fixup value out of range
```

More information on LTO-PGO-BOLT can be found on [](https://llvm.org/docs/AdvancedBuilds.html)

**Comment by madhur13490** [comment]
Here are CMAKE variables we use downstream. 
```
-DLLVM_ENABLE_PROJECTS=bolt;clang;openmp;lld                                                                                                                                                                                                                                                                                                                                            
-DLLVM_ENABLE_RUNTIMES=compiler-rt                                                                                                                                                                                                                                                                                                                                                      
-DLLVM_TARGETS_TO_BUILD=AArch64                                                                                                                                                                                                                                                                                                                                                         
-DCLANG_DEFAULT_LINKER=lld                                                                                                                                                                                                                                                                                                                                                              
-DCMAKE_BUILD_TYPE=Release                                                                                                                                                                                                                                                                                                                                                              
                                                                                                                                                                                                                                                                                                                                                                                        
-C ../clang/cmake/caches/BOLT-PGO.cmake                                                                                                                                                                                                                                                                                                           
-DBOOTSTRAP_LLVM_ENABLE_LLD=ON                                                                                                                                                                                                                                                                                                                                                          
-DBOOTSTRAP_BOOTSTRAP_LLVM_ENABLE_LLD=ON                                                                                                                                                                                                                                                                                                                                                
-DBOOTSTRAP_CLANG_DEFAULT_LINKER=lld                                                                                                                                                                                                                                                                                                                                                    
-DBOOTSTRAP_BOOTSTRAP_CLANG_DEFAULT_LINKER=lld                                                                                                                                                                                                                                                                                                                                          
-DPGO_INSTRUMENT_LTO=Thin                                                                                                                                                                                                                                                                                                                                                               
-DCLANG_BOOTSTRAP_PASSTHROUGH=CMAKE_INSTALL_PREFIX;LLVM_TARGETS_TO_BUILD;CMAKE_BUILD_TYPE;      
 
```

**Comment by aaupov** [comment]
> This commit is breaking LTO-PGO-BOLT build while optimizing clang with BOLT. 
> 
> 
> 
> ```
> 
> [3064/3065] Merging BOLT fdata
> 
> Using legacy profile format.
> 
> Profile from 2 files merged.
> 
> [3064/3065] Optimizing Clang with BOLT
> 
> BOLT-INFO: shared object or position-independent executable detected
> 
> BOLT-INFO: Target architecture: aarch64
> 
> BOLT-INFO: BOLT version: 51d1d03b17bb8bf66b6422c4482d8d615ab53409
> 
> BOLT-INFO: first alloc address is 0x0
> 
> BOLT-INFO: enabling relocation mode
> 
> BOLT-INFO: pre-processing profile using branch profile reader
> 
> BOLT-WARNING: 1 collisions detected while hashing binary objects. Use -v=1 to see the list.
> 
> BOLT-INFO: number of removed linker-inserted veneers: 0
> 
> BOLT-INFO: 11906 out of 212101 functions in the binary (5.6%) have non-empty execution profile
> 
> BOLT-INFO: 272 functions with profile could not be optimized
> 
> BOLT-INFO: profile for 1 objects was ignored
> 
> BOLT-INFO: removed 1 empty block
> 
> BOLT-INFO: basic block reordering modified layout of 4273 functions (35.89% of profiled, 2.01% of total)
> 
> BOLT-INFO: UCE removed 1 blocks and 4 bytes of code
> 
> BOLT-INFO: 68 Functions were reordered by LoopInversionPass
> 
> <unknown>:0: error: fixup value out of range
> 
> <unknown>:0: error: fixup value out of range
> 
> <unknown>:0: error: fixup value out of range
> 
> <unknown>:0: error: fixup value out of range
> 
> <unknown>:0: error: fixup value out of range
> 
> <unknown>:0: error: fixup value out of range
> 
> <unknown>:0: error: fixup value out of range
> 
> <unknown>:0: error: fixup value out of range
> 
> ```
> 
> 
> 
> More information on LTO-PGO-BOLT can be found on https://llvm.org/docs/AdvancedBuilds.html

This change was tested on a buildbot: https://lab.llvm.org/buildbot/#/builders/113/builds/2934

Can you please try cleaning the build directory?

**Comment by aaupov** [comment]
> @aaupov this happens on AArch64 target, and only with -split-strategy=cdsplit enabled. Changing it to profile2, for example, fixes the issue

Thanks for clarification. I'll drop cdsplit as we never tested it on AArch64. ARM clang-bolt buildbot hasn't picked this change up yet so I didn't get the signal.

**Pull request merged**
