### PR TITLE
[clang][analyzer] Bring alpha.security.MmapWriteExec checker out of alpha package

### PR DESCRIPTION
**Pull request by balazske**

### CODE REVIEW

**Comment by steakhal** [comment]
Have you checked the quality of the reports?

**Comment by balazske** [comment]
It is not easy to find an easily compilable (and not too big) project that contains `mmap` to test the checker. I could test it with libgit2, can try to find more projects to test.

**Comment by steakhal** [comment]
`nasm`, `breakpad`, `tinycbor`, `snappy`, `ffmpeg`, `libxml`, `tflite`, `tensorflow`, `abseil-cpp`, `LibreOffice`, `Redis`, `mongodb`, `PostgreSQL`, `rocksdb`, `aragondb`, `MySQL`, `HHVM`, `nginx`, `zfs`, `zstd`, `Clang/compiler-rt`, `transmission`, `OpenSSL` [and more] appears to reference `mmap` directly or transitively.

**Comment by balazske** [comment]
I have tested it on some of the projects but there are not results from this checker. The detected type of bug looks unlikely so it is difficult to test the checker this way.

**Review by steakhal — APPROVED** [review]
Alright, it's probably good enough.

**Pull request merged**
