### PR TITLE
[flang][cuda] Add RT_API_ATTRS to allocator functions

### PR DESCRIPTION
**Pull request by clementval**
Allocators might be called from device code. Add RT_API_ATTRS so it can be build for the device.

### CODE REVIEW

**Review by vzakhari — APPROVED** [review]
Looks okay, though, I am not sure if all the driver APIs (like `cuMemAllocHost`) can be used in kernel code.  Isn't it okay to use `malloc`/`free` in the device code?

**Comment by clementval** [comment]
> Looks okay, though, I am not sure if all the driver APIs (like `cuMemAllocHost`) can be used in kernel code. Isn't it okay to use `malloc`/`free` in the device code?

Yeah for sure allocating host data from the device makes no sense. Maybe we should register different allocators in the device code.

**Comment by vzakhari** [comment]
Maybe we can always assume the default allocator index in device code, so that `malloc` and `free` are used. Then we do not need to register any other allocators on the device. I suppose registration will require a kernel invocation, which adds some overhead.

**Comment by clementval** [comment]
> Maybe we can always assume the default allocator index in device code, so that `malloc` and `free` are used. Then we do not need to register any other allocators on the device. I suppose registration will require a kernel invocation, which adds some overhead.

Yeah I think that is a better alternative than registering allocators each time. I'll prepare a patch for that and this one is not needed after all.

**Pull request closed without merging**
