### PR TITLE
[flang] Fix ISO_Fortran_binding.h to work better with C++ code

### PR DESCRIPTION
**Pull request by psteinfeld**
[flang] Fix ISO_Fortran_binding.h to work better with C++ code

This stems from working on LANL's "dopey" project -- https://github.com/lanl/dopey.

That project contains C++ code which includes the header file "ISO_Fortran_binding.h".  The dopey code  wraps that include with an 'extern "C"' clause since the standard (18.5.1, paragraph 1) says that the file" shall contain C structure definitions, typedef declarations, ...".  But the clang++ compiler emits error messages objecting to the fact that ISO_Fortran_binding.h contains templates.

This change fixes that by preceding the problematic code in ISO_Fortran_binding.h with language linkage clauses that specify that they contain C++ code rather than C code.

In the accompanying test, I needed to account for the fact that some people build the compiler by doing a `make check-flang`.  In this case, the clang compiler which is required by the test will not be built.

Here's an example of a C++ program that shows the problem:
```
  extern "C" {
  #include "ISO_Fortran_binding.h"
  }
  int main() {
    return 0;
  }
```

### CODE REVIEW

**Review by klausler — APPROVED** [review]

**Review by vzakhari — APPROVED** [review]
LGTM. Thank you, Pete!

**Review by kiranchandramohan — APPROVED** [review]
LGTM.

There is a `flang/test/Integration` directory that might be a good place for the test. I don't know whether `cpp` tests run there though.

**Comment by psteinfeld** [comment]
> There is a `flang/test/Integration` directory that might be a good place for the test. I don't know whether `cpp` tests run there though.

Good suggestion.  I'll move it.

**Comment by psteinfeld** [comment]
In separate testing (see PR #82811), I convinced my selv that the failing Windows build of these changes has nothing to do with the changes themselves.

**Pull request merged**
