### PR TITLE
[mlir] Fix some cmake dependencies in LLVMIR Dialect

### PR DESCRIPTION
**Pull request by zero9178**
While looking into reducing needless interdependencies between upstream MLIR dialects and passes, I discovered that the ROCDL Dialect redundantely uses links in `VectorToLLVM` conversion pass when it actually requires just the LLVM Dialect. Furthermore, after a build failure, I ran `ninja -t missingdeps` which revealed that the NVVM Dialect depends on headers of the GPU dialect (https://github.com/llvm/llvm-project/blob/211c9752c8200fbb3ff7be1f6aa98037901758ce/mlir/include/mlir/Dialect/LLVMIR/NVVMDialect.h#L18) without stating so in CMake. 
This causes flaky builds as it is not guaranteed that the header exists prior to the dialect being compiled.

### CODE REVIEW

**Review by jpienaar — APPROVED** [review]

**Comment by xblang-project** [comment]
Could you try changing the NVVM part to this:
```
diff --git a/mlir/lib/Dialect/LLVMIR/CMakeLists.txt b/mlir/lib/Dialect/LLVMIR/CMakeLists.txt
index b5e6fbd4baf6..66a38d8ea4a1 100644
--- a/mlir/lib/Dialect/LLVMIR/CMakeLists.txt
+++ b/mlir/lib/Dialect/LLVMIR/CMakeLists.txt
@@ -49,6 +49,7 @@ add_mlir_dialect_library(MLIRNVVMDialect
   DEPENDS
   MLIRNVVMOpsIncGen
   MLIRNVVMConversionsIncGen
+  MLIRGPUCompilationAttrInterfacesIncGen
   intrinsics_gen
 
   LINK_COMPONENTS
@@ -70,6 +71,7 @@ add_mlir_dialect_library(MLIRROCDLDialect
   DEPENDS
   MLIRROCDLOpsIncGen
   MLIRROCDLConversionsIncGen
+  MLIRGPUCompilationAttrInterfacesIncGen
   intrinsics_gen
 
   LINK_COMPONENTS
diff --git a/mlir/lib/Dialect/LLVMIR/IR/NVVMDialect.cpp b/mlir/lib/Dialect/LLVMIR/IR/NVVMDialect.cpp
index 76c043e41ea8..9033194f0fec 100644
--- a/mlir/lib/Dialect/LLVMIR/IR/NVVMDialect.cpp
+++ b/mlir/lib/Dialect/LLVMIR/IR/NVVMDialect.cpp
@@ -17,7 +17,6 @@
 #include "mlir/Dialect/LLVMIR/NVVMDialect.h"
 
 #include "mlir/Conversion/ConvertToLLVM/ToLLVMInterface.h"
-#include "mlir/Dialect/GPU/IR/GPUDialect.h"
 #include "mlir/Dialect/Utils/StaticValueUtils.h"
 #include "mlir/IR/Builders.h"
 #include "mlir/IR/BuiltinAttributes.h"
diff --git a/mlir/lib/Dialect/LLVMIR/IR/ROCDLDialect.cpp b/mlir/lib/Dialect/LLVMIR/IR/ROCDLDialect.cpp
index 32f34a8889af..a9e829716953 100644
--- a/mlir/lib/Dialect/LLVMIR/IR/ROCDLDialect.cpp
+++ b/mlir/lib/Dialect/LLVMIR/IR/ROCDLDialect.cpp
@@ -16,7 +16,6 @@
 
 #include "mlir/Dialect/LLVMIR/ROCDLDialect.h"
 
-#include "mlir/Dialect/GPU/IR/GPUDialect.h"
 #include "mlir/Dialect/LLVMIR/LLVMDialect.h"
 #include "mlir/IR/Builders.h"
 #include "mlir/IR/BuiltinTypes.h"
```

NVVM & ROCDL don't require the full `GPUDialect` to be linked, only the header created by `MLIRGPUCompilationAttrInterfacesIncGen` to get generated .

**Comment by fabianmcg** [comment]
Could you try changing the NVVM part to this:
```
diff --git a/mlir/lib/Dialect/LLVMIR/CMakeLists.txt b/mlir/lib/Dialect/LLVMIR/CMakeLists.txt
index b5e6fbd4baf6..66a38d8ea4a1 100644
--- a/mlir/lib/Dialect/LLVMIR/CMakeLists.txt
+++ b/mlir/lib/Dialect/LLVMIR/CMakeLists.txt
@@ -49,6 +49,7 @@ add_mlir_dialect_library(MLIRNVVMDialect
   DEPENDS
   MLIRNVVMOpsIncGen
   MLIRNVVMConversionsIncGen
+  MLIRGPUCompilationAttrInterfacesIncGen
   intrinsics_gen
 
   LINK_COMPONENTS
@@ -70,6 +71,7 @@ add_mlir_dialect_library(MLIRROCDLDialect
   DEPENDS
   MLIRROCDLOpsIncGen
   MLIRROCDLConversionsIncGen
+  MLIRGPUCompilationAttrInterfacesIncGen
   intrinsics_gen
 
   LINK_COMPONENTS
diff --git a/mlir/lib/Dialect/LLVMIR/IR/NVVMDialect.cpp b/mlir/lib/Dialect/LLVMIR/IR/NVVMDialect.cpp
index 76c043e41ea8..9033194f0fec 100644
--- a/mlir/lib/Dialect/LLVMIR/IR/NVVMDialect.cpp
+++ b/mlir/lib/Dialect/LLVMIR/IR/NVVMDialect.cpp
@@ -17,7 +17,6 @@
 #include "mlir/Dialect/LLVMIR/NVVMDialect.h"
 
 #include "mlir/Conversion/ConvertToLLVM/ToLLVMInterface.h"
-#include "mlir/Dialect/GPU/IR/GPUDialect.h"
 #include "mlir/Dialect/Utils/StaticValueUtils.h"
 #include "mlir/IR/Builders.h"
 #include "mlir/IR/BuiltinAttributes.h"
diff --git a/mlir/lib/Dialect/LLVMIR/IR/ROCDLDialect.cpp b/mlir/lib/Dialect/LLVMIR/IR/ROCDLDialect.cpp
index 32f34a8889af..a9e829716953 100644
--- a/mlir/lib/Dialect/LLVMIR/IR/ROCDLDialect.cpp
+++ b/mlir/lib/Dialect/LLVMIR/IR/ROCDLDialect.cpp
@@ -16,7 +16,6 @@
 
 #include "mlir/Dialect/LLVMIR/ROCDLDialect.h"
 
-#include "mlir/Dialect/GPU/IR/GPUDialect.h"
 #include "mlir/Dialect/LLVMIR/LLVMDialect.h"
 #include "mlir/IR/Builders.h"
 #include "mlir/IR/BuiltinTypes.h"
```

NVVM & ROCDL don't require the full `GPUDialect` to be linked, only the header created by `MLIRGPUCompilationAttrInterfacesIncGen` to get generated .

**Comment by zero9178** [comment]
> Could you try changing the NVVM part to this:
> 
> ```
> diff --git a/mlir/lib/Dialect/LLVMIR/CMakeLists.txt b/mlir/lib/Dialect/LLVMIR/CMakeLists.txt
> index b5e6fbd4baf6..66a38d8ea4a1 100644
> --- a/mlir/lib/Dialect/LLVMIR/CMakeLists.txt
> +++ b/mlir/lib/Dialect/LLVMIR/CMakeLists.txt
> @@ -49,6 +49,7 @@ add_mlir_dialect_library(MLIRNVVMDialect
>    DEPENDS
>    MLIRNVVMOpsIncGen
>    MLIRNVVMConversionsIncGen
> +  MLIRGPUCompilationAttrInterfacesIncGen
>    intrinsics_gen
>  
>    LINK_COMPONENTS
> @@ -70,6 +71,7 @@ add_mlir_dialect_library(MLIRROCDLDialect
>    DEPENDS
>    MLIRROCDLOpsIncGen
>    MLIRROCDLConversionsIncGen
> +  MLIRGPUCompilationAttrInterfacesIncGen
>    intrinsics_gen
>  
>    LINK_COMPONENTS
> diff --git a/mlir/lib/Dialect/LLVMIR/IR/NVVMDialect.cpp b/mlir/lib/Dialect/LLVMIR/IR/NVVMDialect.cpp
> index 76c043e41ea8..9033194f0fec 100644
> --- a/mlir/lib/Dialect/LLVMIR/IR/NVVMDialect.cpp
> +++ b/mlir/lib/Dialect/LLVMIR/IR/NVVMDialect.cpp
> @@ -17,7 +17,6 @@
>  #include "mlir/Dialect/LLVMIR/NVVMDialect.h"
>  
>  #include "mlir/Conversion/ConvertToLLVM/ToLLVMInterface.h"
> -#include "mlir/Dialect/GPU/IR/GPUDialect.h"
>  #include "mlir/Dialect/Utils/StaticValueUtils.h"
>  #include "mlir/IR/Builders.h"
>  #include "mlir/IR/BuiltinAttributes.h"
> diff --git a/mlir/lib/Dialect/LLVMIR/IR/ROCDLDialect.cpp b/mlir/lib/Dialect/LLVMIR/IR/ROCDLDialect.cpp
> index 32f34a8889af..a9e829716953 100644
> --- a/mlir/lib/Dialect/LLVMIR/IR/ROCDLDialect.cpp
> +++ b/mlir/lib/Dialect/LLVMIR/IR/ROCDLDialect.cpp
> @@ -16,7 +16,6 @@
>  
>  #include "mlir/Dialect/LLVMIR/ROCDLDialect.h"
>  
> -#include "mlir/Dialect/GPU/IR/GPUDialect.h"
>  #include "mlir/Dialect/LLVMIR/LLVMDialect.h"
>  #include "mlir/IR/Builders.h"
>  #include "mlir/IR/BuiltinTypes.h"
> ```
> 
> NVVM & ROCDL don't require the full `GPUDialect` to be linked, only the header created by `MLIRGPUCompilationAttrInterfacesIncGen` to get generated .

Done. I've also gone ahead and changed the "include"s in both files to only include the header for the compilation interface that is purely used for the promised interface as far as I can tell.

**Comment by joker-eph** [comment]
Why is the dependency on the LLVM dialect needed?

**Comment by zero9178** [comment]
> Why is the dependency on the LLVM dialect needed?

The ROCDL dialect uses the `LLVMFixedVectorType` type from the LLVM Dialect and has one verifier depending on LLVMs FuncOp. It previously had this dependency as well but got it transitively through the `VectorToLLVM` dependency.

**Review by fabianmcg — APPROVED** [review]
You're right it's only needed for the promise, could you also remove `#include "mlir/Dialect/GPU/IR/CompilationInterfaces.h"` from `include/mlir/Dialect/LLVMIR/(NVVM|ROCDL)Dialect.h` so they don't inadvertently pollute other files.  Thank you for catching these.

**Comment by zero9178** [comment]
@joker-eph do you have any more concerns or is it okay to land?

**Pull request merged**
