### PR TITLE
[LVI] Use m_AddLike instead of m_Add when matching simple condition

### PR DESCRIPTION
**Pull request by goldsteinn**
- **[LVI] Add tests for tracking `or disjoint` like add; NFC**
- **[LVI] Use m_AddLike instead of m_Add when matching simple condition**

### CODE REVIEW

**Comment by nikic** [comment]
Disjoint or in the range idiom seems a bit odd to me. @dtcxzyw Can you please check whether this has any impact?

**Review by nikic — COMMENTED** [review]
Okay, it looks like there is some impact, so I guess it's fine.

However, I don't think your test coverage is right. The test in icmp.ll is not affected by the change. You need a disjoint or in the dominating condition, not at the use-site.

**Comment by goldsteinn** [comment]
> Okay, it looks like there is some impact, so I guess it's fine.
> 
> However, I don't think your test coverage is right. The test in icmp.ll is not affected by the change. You need a disjoint or in the dominating condition, not at the use-site.

Sorry, was pretty lax on the tests as figured it was straight forward, will update

**Comment by goldsteinn** [comment]
> > Okay, it looks like there is some impact, so I guess it's fine.
> > However, I don't think your test coverage is right. The test in icmp.ll is not affected by the change. You need a disjoint or in the dominating condition, not at the use-site.
> 
> Sorry, was pretty lax on the tests as figured it was straight forward, will update

Updated the test so it works...

**Review by dtcxzyw — APPROVED** [review]
LGTM.

**Pull request closed without merging**
