### PR TITLE
[BasicAA] Treat returns_twice functions as clobbering unescaped objects

### LINKED ISSUE #116668: Modification to malloc'd local variable between builtin setjmp and londjump calls not preserved
Any modification to malloc'd local variable between __builtin_setjmp and __builtin_longjmp calls does not persist. It is optimized by either by earlyCSE or GVN (global value numbering) pass. __builtin_setjmp has attribute (llvm::Attribute::ReturnsTwice).

//bug.c
```
#include <stdio.h>
#include <stdlib.h>

void* buf[20];
attribute((noinline))
void foo(void)
{
  printf("Calling longjmp from inside function foo\n");
  __builtin_longjmp(buf, 1);
 printf("This point should never be reached\n");
}

int main(void)
{
  int *local_var = malloc(sizeof(int));
  *local_var = 10;
  printf("local_val=%d \n", *local_var);
  if (__builtin_setjmp(buf) == 0)
  {
    *local_var = 20;
     printf("Calling function foo local_var=%d \n", *local_var);
     foo();
  }
  printf("longjmp has been called local_val=%d \n", *local_var);
}

```
/*******************Output should be as follows: **********************
local_val=10
Calling function foo local_var=20
Calling longjmp from inside function foo
longjmp has been called local_val=20
**********************************************************************/

$clang -O2 bug.c
$./a.out
local_val=10
Calling function foo local_var=20
Calling longjmp from inside function foo
longjmp has been called local_val=10

Value of local_var is modified between setjmp and longjmp calls to 20, but after return from longjmp local_var remains 10 because of GVN optimization.

After some analyses I have attached setjmp_longjmp_bug.zip files have two tests case, bug1.c and and bug2.c. bug1.c is compiled at -O1 and has information after each pass using -dump-after-all in file bug1_dump_earlycse_o1. earlyCSE optimizes malloc'd local_var.

Similarly, in bug2.c, GVN optimizes malloc'd local variable local_var at -O2. It's dump after each pass is in bug2_dump_gvn_o2 file. Both dump files are marked with "???" where wrong optimization (constant folding) happens.
[setjmp_longjmp_bug.zip](https://github.com/user-attachments/files/17803940/setjmp_longjmp_bug.zip)

### PR DESCRIPTION
**Pull request by nikic**
Effectively this models all the accesses that occur between the first and second return as happening at the point of the call.

I left this a generic check, though at least for setjmp and C semantics specifically, we could skip allocas, as these are required to use volatile accesses when modified between setjmp and longjmp.

Fixes https://github.com/llvm/llvm-project/issues/116668.

### CODE REVIEW

**Review by efriedma-quic — APPROVED** [review]
LGTM

The fact that we don't represent longjmp control flow with a real CFG edge continues to make me worry about hidden bugs, but this particular fix seems reasonable.

**Comment by nikic** [comment]
Unfortunately this broke from Objective C tests, which appears to rely on optimizations still happening for allocas. It inserts its own optimization barriers using inline asm.

So I looks like we do have to special case the alloca case if we want to preserve those Objective C optimizations. It's somewhat iffy though, because LLVM can promote globals to allocas. I'd be happy to adjust the tests with the optimization regressions instead...

**Review by efriedma-quic — APPROVED** [review]
The whole "setjmp doesn't have to preserve local variables" thing is an artifact of ancient C compiler technology where the compiler didn't actually understand setjmp semantics.  Given a modern setjmp-aware compiler, it shouldn't be a thing; we have the ability to correctly preserve local variables.

That said, given the current state of returns_twice, carving out an exception for alloca seems okay.

**Comment by antoniofrighetto** [comment]
@nikic Do you believe we should also be checking for returns_twice in callCapturesBefore(), along the following lines?

https://github.com/llvm/llvm-project/blob/f9f62ef4ae555a86878411e696b8b747851fc337/llvm/lib/Analysis/AliasAnalysis.cpp#L620-L626

AFAICT, if we are given a non-escaping memory location and the given call-site is returns_twice, we should continue conservatively say the call may clobber this location.

**Comment by antoniofrighetto** [comment]
Oops, sorry, I wonder which file I was looking at.

> (We could remove callCapturesBefore while keeping its additional precision by adding a CaptureAnalysis using CapturesBefore, possibly in conjunction with support for "chained" capture analysis where we try EarliestEscapeAnalysis before falling back to CatpuresBeforeAnalysis.)

Right, this makes sense, thanks for direction. With chained capture analysis, I assume we may want a ChainedCaptureAnalysis instance, to be passed to BatchAA, which is delegated to own the two EEA and CBA objects. Also, IIUC, we would not be interested in the mod/ref refinement done per-argument in callCapturesBefore() anymore – yet, if CBA is passed with OrAt, we should still be checking for possible pointer escaping at call-site level via return value.

**Pull request merged**
