### PR TITLE
[clang] Implement constexpr __builtin_bit_cast for complex types

### LINKED ISSUE #94620: Unsupported `constexpr std::bit_cast` for `std::complex`
Hello, I am trying to bit_cast a structure containing `std::complex`, and clang is reporting that this is unsupported. I'm attaching here an MVE:
```
#include <bit>
#include <iostream>
#include <complex>
#include <array>

using C = std::complex<double>;

int main() {
    constexpr unsigned char data[sizeof(C)] = {0};

    constexpr C c = std::bit_cast<C>(data);
    std::cout << c << '\n';

    return 0;
}
```
This seems to fail on trunk as per godbolt (https://godbolt.org/z/q8fKE7r18).

There exists a similar issue, #54018, with PR #74775, which involves bit-fields. I am not sure whether this is related at low level, but I think enabling `std::bit_cast` on a "native" standard library type is quite important. I am opening this issue as I have not been able to find any status reports on this problem.

### PR DESCRIPTION
**Pull request by tbaederr**
Fixes https://github.com/llvm/llvm-project/issues/94620

### CODE REVIEW

**Comment by tbaederr** [comment]
I was going to add tests for floating complex types as well but I see that's rather hard and tests for floating types are rare in that file overall.

**Comment by tbaederr** [comment]
Ping

**Comment by tbaederr** [comment]
Ping

**Review by Sirraide — APPROVED** [review]
LGTM

A few more tests fo errors would be nice maybe (e.g. bit-casting a `_Complex int` to an `int` or sth like that), but I don’t think they’re required.

**Pull request merged**
