### PR TITLE
[Xtensa] Default to unsigned char

### PR DESCRIPTION
**Pull request by arichardson**
This matches GCC.

Partially addresses https://github.com/llvm/llvm-project/pull/115964

### CODE REVIEW

**Comment by brad0** [comment]
cc @andreisfr

**Comment by gerekon** [comment]
Looks like it is related to https://github.com/llvm/llvm-project/pull/118008

**Comment by gerekon** [comment]
Hi @arichardson.

Thanks for this change. Acc to the doc which I have `The char type is unsigned by default for Xtensa processors.` Our GCC Xtensa toolchain also interprets char type as unsigned by default.

**Comment by arichardson** [comment]
> Hi @arichardson.
> 
> Thanks for this change. Acc to the doc which I have `The char type is unsigned by default for Xtensa processors.` Our GCC Xtensa toolchain also interprets char type as unsigned by default.

Thanks, do you believe we need a backwards compatibility flag for the ABI to be consistent with older clang or is this safe to land?

**Comment by arichardson** [comment]
Looking at https://github.com/llvm/llvm-project/pull/118008 it sounds like we don't yet have complete codegen support for XTensa in Clang, so it sounds like this is safe without a flag.

**Comment by gerekon** [comment]
> Looking at #118008 it sounds like we don't yet have complete codegen support for XTensa in Clang, so it sounds like this is safe without a flag.

Yes, it is not upstreamed yet. We are working on it. But after rebasing on the LLVM 20 we might get this fix in our repo, so that will influence our Clang toolchain and Rust, Swift ones. So I asked @MabezDev if he sees any potential problems for this.

**Pull request merged**
