### PR TITLE
[flang][OpenMP] Minimal fix for flang build after 'omp assume' patch

### PR DESCRIPTION
**Pull request by jtb20**
This patch restores the flang build, which was inadvertently broken by the patch to implement 'omp assume' support
(a42e515e3a9f3bb4e44389c097b89104d95b9b29).

Thanks to Maxim Kuvyrkov and the Linaro auto-tester for the heads-up.

### CODE REVIEW

**Comment by vzakhari** [comment]
Pete, can you please take a look?

**Comment by psteinfeld** [comment]
> Pete, can you please take a look?

I'm on it.

**Review by psteinfeld — APPROVED** [review]
I don't understand the content of the changes, but I know that this fixes the build and that it passes all of the lit tests.  Please merge ASAP.

**Comment by jtb20** [comment]
Thank you. I don't have write access so could someone please commit this for me?

**Review by tblah — APPROVED** [review]
Thanks for the quick fix. I'll merge without any nitpicks to get this in ASAP.

**Pull request merged**
