### PR TITLE
[MLIR][Python] remove unused init python file

### PR DESCRIPTION
**Pull request by xurui1995**
remove unused `__init__.py` under `mlir/python/mlir/extras`

### CODE REVIEW

**Comment by makslevental** [comment]
So this is gonna break some downstream people (for one me) because without that __init__ there the extras package is a namespace package. I don't why I made that file 9 months ago but I did intend for extras to be a namespace package. How setuptools break for you?

**Comment by xurui1995** [comment]
> So this is gonna break some downstream people (for one me) because without that **init** there the extras package is a namespace package. I don't why I made that file 9 months ago but I did intend for extras to be a namespace package. How setuptools break for you?

if this will break some downstream, then there is no need to merge it. For my downstream we were using `find_packages` from the `setuptools`, I will try something else, like `find_namespace_packages`

**Comment by makslevental** [comment]
> if this will break some downstream, then there is no need to merge it. For my downstream we were using `find_packages` from the `setuptools`, I will try something else, like `find_namespace_packages`

actually what you can do in this PR is remove that `__init__.py` file

**Comment by xurui1995** [comment]
> > if this will break some downstream, then there is no need to merge it. For my downstream we were using `find_packages` from the `setuptools`, I will try something else, like `find_namespace_packages`
> 
> actually what you can do in this PR is remove that `__init__.py` file

make sense :)

**Review by makslevental — APPROVED** [review]
Thanks :)

**Comment by xurui1995** [comment]
Note: This PR's desc has changed, the following content is the original desc

* Downstream project was using setuptools  to build package from the generated mlir python_packages, and it seems the extra package did not include the [__init__.py](https://github.com/llvm/llvm-project/blob/main/mlir/python/mlir/extras/__init__.py) in the extra dir.

**Comment by makslevental** [comment]
I keep forgetting - you need me to merge or not?

**Comment by xurui1995** [comment]
> I keep forgetting - you need me to merge or not?

thanks, I can merge it myself,  I am just waiting for the finish of the pre-commit ci

**Pull request merged**
