### PR TITLE
[compiler-rt] add check-cmp flag for nsan

### LINKED ISSUE #108435: [compiler-rt][nsan] Add an option to enable/disable comparison checking
There are a few different potential approaches.
It might be easier to start with simply extending ```NSAN_OPTIONS``` with ```check_cmp``` and return early (in ```fCmpFailFT```) if the flag is false.
This is suboptimal in terms of performance, but might be more convenient / flexible.

### PR DESCRIPTION
**Pull request by c8ef**
Closes #108435.

### CODE REVIEW

**Comment by alexander-shaposhnikov** [comment]
The patch needs tests

**Comment by MaskRay** [comment]
Add a test? We typically reserve "fix ..." to mean bug fixes. Implementing a feature can use `Close ...`

**Comment by alexander-shaposhnikov** [comment]
Thanks for the update, I'll come back to this soon

**Comment by alexander-shaposhnikov** [comment]
LGTM with some minor nits
(the checks in the test need some reorganization, I'll commit it as a follow-up)

**Review by alexander-shaposhnikov — APPROVED** [review]

**Pull request merged**
