### PR TITLE
Reland "[LLVM] Add IRNormalizer Pass"

### PR DESCRIPTION
**Pull request by justinfargnoli**
`IRNormalizer` will reorder instructions. Thus, we need to invalidate analyses. Done in cd500d28cba3177c213f2f2faf50f14ea56e230b. This should resolve the [BuildBot failure](https://github.com/llvm/llvm-project/pull/68176#issuecomment-2428243474). 

---

Original PR: #68176
Original commit: 1295d2e6da2fe90f3b770ab1d35bf5caecd38bed
Reverted with: 8a12e0131f3d84b470fac63af042aa96a1b19f56

---

Add the llvm-canon tool. Description from the [original PR](https://reviews.llvm.org/D66029#change-wZv3yOpDdxIu):

> Added a new llvm-canon tool which aims to transform LLVM Modules into a canonical form by reordering and renaming instructions while preserving the same semantics. This tool makes it easier to spot semantic differences while diffing two modules which have undergone different transformation passes.

The current version of this tool can:

- Reorder instructions within a function.
- Rename instructions based on the operands.
- Sort commutative operands.

This code was originally written by @michalpaszkowski and [submitted to mainline LLVM](https://github.com/llvm/llvm-project/commit/14d358537f124a732adad1ec6edf3981dc9baece). However, it was quickly [reverted](https://github.com/llvm/llvm-project/commit/335de55fa3384946f1e62050f2545c0966163236) to do BuildBot errors. 

Michal presented his version of the tool in [LLVM-Canon: Shooting for Clear Diffs](https://www.youtube.com/watch?v=c9WMijSOEUg).

@AidanGoldfarb and I ported the code to the new pass manager, added more tests, and fixed some bugs related to PHI nodes that may have been the root cause of the BuildBot errors that caused the patch to be reverted. Additionally, we rewrote the implementation of instruction reordering to fix cases where the original algorithm would break use-def chains. 

Note that this is @AidanGoldfarb and I's first time submitting to LLVM. Please liberally critique the PR! 

CC @plotfi for initial review.

### CODE REVIEW

**Comment by vvereschaka** [comment]
@justinfargnoli ,

I wasn't able to build and check your branch (`TheManWithTheGoldenCanon:main`) locally on the builder because of these linker  errors:
```
 /home/buildbot/worker/temp/llvm-project/llvm/include/llvm/IR/PassManager.h:111: error: undefined reference to 'llvm::PreservedFunctionHashAnalysis::Key'
/home/buildbot/worker/temp/llvm-project/llvm/include/llvm/IR/PassManager.h:111: error: undefined reference to 'llvm::PreservedModuleHashAnalysis::Key'
collect2: error: ld returned 1 exit status
```

Would you check your changes once again? Probably you need to sync your branch with the `llvm-project:main` top-of-the-tree.

**Comment by vvereschaka** [comment]
> @vvereschaka I'm unable to reproduce the build failure locally or via the `buildkite` jobs.
> 
> Are the jobs that you're running on the BuildBot clean builds?

@justinfargnoli in few words the problem is in the broken link order for those two `Key` references. 

You have rearranged the declarations/definitions for `PreservedFunctionHashAnalysis[::Key]` and `PreservedModuleHashAnalysis[::Key]`. They became the public and global vars.
The implementations of those `Key`s are now sitting inside of `lib/libLLVMPasses.a`, but the references to them are inside of `lib/libLLVMTransformUtils.a`. The `lib/libLLVMTransformUtils.a` library is processing after `lib/libLLVMPasses.a` during the linking stage (see the error log above) and these references remain unresolved.
You need to move the  `PreservedFunctionHashAnalysis::Key` and `PreservedModuleHashAnalysis::Key` back into `lib/libLLVMTransformUtils.a` (as example into `llvm/lib/Transforms/Utils/IRNormalizer.cpp` or any other inside of Transform/Utils). 
Or fix the linking order within the CMake configuration files.

**Comment by aeubanks** [comment]
I believe the failure reported in the original bot is only under expensive checks (`-DLLVM_ENABLE_EXPENSIVE_CHECKS=ON`)

**Comment by justinfargnoli** [comment]
> @justinfargnoli in few words the problem is in the broken link order for those two Key references.

@vvereschaka thank you for your [detail description](https://github.com/llvm/llvm-project/pull/113780#issuecomment-2448416385) of the issue. 

I've attempted to address the:
- Build issues with [Port PreservedFunctionHashAnalysis and PreservedModuleHashAnalysis to Analysis](https://github.com/llvm/llvm-project/pull/113780/commits/ef6a751a794c3e2d266cac0242629043ddd0d2aa).
- Expensive checks test failure with [Abandon PreservedFunctionHashAnalysis and PreservedModuleHashAnalysis in IRNormalizer](https://github.com/llvm/llvm-project/pull/113780/commits/5dda94115b59df2a46e8d15a2770e8e49d6153e7). 

I've verified locally that the expensive checks test failure is resolved. I think I've also verified that the [build error](https://github.com/llvm/llvm-project/pull/113780#issuecomment-2442720776) is resolved. However, could you double-check on my behalf?

**Comment by vvereschaka** [comment]
Thank you @justinfargnoli ,
sure, I'll check these changes  tomorrow.

**Review by boomanaiden154 — COMMENTED** [review]
Is it possible/easy to split https://github.com/llvm/llvm-project/pull/113780/commits/ef6a751a794c3e2d266cac0242629043ddd0d2aa into a new PR? I think that would make things easier to go through and keep the commit history clean/make it easy to discern the motivation from a git blame.

**Comment by justinfargnoli** [comment]
> Is it possible/easy to split https://github.com/llvm/llvm-project/commit/ef6a751a794c3e2d266cac0242629043ddd0d2aa into a new PR?

Certainly, @boomanaiden154! Please see #116108 :)

**Review by vvereschaka — APPROVED** [review]
@justinfargnoli ,
I have checked the latest changes locally on the ubuntu expensive builder. They works fine there, thank you. LGTM.

**Review by nikic — APPROVED** [review]
The pass invalidation changes look good to me, I didn't look at the rest.

**Pull request merged**
