### PR TITLE
[Flang][Parser] Add missing dependencies to CMakeLists.txt

### PR DESCRIPTION
**Pull request by kparzysz**
Two additional component libraries: FrontendOpenACC and FrontendOpenMP.

### CODE REVIEW

**Comment by kparzysz** [comment]
This is needed for getting directive names for both OpenMP and OpenACC when using `DumpTree` from the AST dumper.

**Comment by kiranchandramohan** [comment]
> This is needed for getting directive names for both OpenMP and OpenACC when using `DumpTree` from the AST dumper.

I see that FortranParser has a link_component entry for `FrontendOpenACC`, is it enough to add an entry for `FrontendOpenMP` there?

```
add_flang_library(FortranParser
  Fortran-parsers.cpp
  ...

  LINK_LIBS
  FortranCommon

  LINK_COMPONENTS
  Support
  FrontendOpenACC

  DEPENDS
  omp_gen
  acc_gen
)
```

**Comment by clementval** [comment]
> This is needed for getting directive names for both OpenMP and OpenACC when using `DumpTree` from the AST dumper.

`DumpTree` is not part of Lowering libs. I guess @kiranchandramohan suggestion should work for `DumpTree`.

**Comment by kparzysz** [comment]
Sounds good.  Will update the PR later today.

**Review by clementval — APPROVED** [review]

**Review by kiranchandramohan — APPROVED** [review]
LGTM.

**Comment by kparzysz** [comment]
Bad news, this didn't work.  I put `DumpTree` in OpenMP.cpp, and I'm getting
```
/usr/bin/ld: CMakeFiles/obj.FortranLower.dir/OpenMP.cpp.o: in function `std::enable_if<((!(is_class_v<llvm::acc::Directive>))||(is_same_v<std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >, llvm::acc::Directive>))||(is_same_v<Fortran::parser::CharBlock, llvm::acc::Directive>), void>::type Fortran::parser::Walk<llvm::acc::Directive, Fortran::parser::ParseTreeDumper>(llvm::acc::Directive const&, Fortran::parser::ParseTreeDumper&)':
OpenMP.cpp:(.text._ZN7Fortran6parser4WalkIN4llvm3acc9DirectiveENS0_15ParseTreeDumperEEENSt9enable_ifIXoooont10is_class_vIT_E9is_same_vINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_E9is_same_vINS0_9CharBlockES7_EEvE4typeERKS7_RT0_[_ZN7Fortran6parser4WalkIN4llvm3acc9DirectiveENS0_15ParseTreeDumperEEENSt9enable_ifIXoooont10is_class_vIT_E9is_same_vINSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEES7_E9is_same_vINS0_9CharBlockES7_EEvE4typeERKS7_RT0_]+0x146): undefined reference to `llvm::acc::getOpenACCDirectiveName(llvm::acc::Directive)'
/usr/bin/ld: CMakeFiles/obj.FortranLower.dir/OpenMP.cpp.o: in function `std::enable_if<WrapperTrait<Fortran::parser::AccDefaultClause>, void>::type Fortran::parser::Walk<Fortran::parser::AccDefaultClause, Fortran::parser::ParseTreeDumper>(Fortran::parser::AccDefaultClause const&, Fortran::parser::ParseTreeDumper&)':
OpenMP.cpp:(.text._ZN7Fortran6parser4WalkINS0_16AccDefaultClauseENS0_15ParseTreeDumperEEENSt9enable_ifIX12WrapperTraitIT_EEvE4typeERKS5_RT0_[_ZN7Fortran6parser4WalkINS0_16AccDefaultClauseENS0_15ParseTreeDumperEEENSt9enable_ifIX12WrapperTraitIT_EEvE4typeERKS5_RT0_]+0x27c): undefined reference to `llvm::acc::getOpenACCDefaultValueName(llvm::acc::DefaultValue)'
collect2: error: ld returned 1 exit status```

**Comment by clementval** [comment]
Why would you put DumpTree in lowering? For local debugging?

**Comment by kparzysz** [comment]
> Why would you put DumpTree in lowering? For local debugging?

Basically, yes.  I can add these libraries when I need them, so this is not a big deal.  I should probably revert this commit though, since it doesn't accomplish anything.

**Comment by kparzysz** [comment]
Although...  If I don't need to link any extra libraries do get `DumpTree`, I'd expect it to just work.

**Comment by clementval** [comment]
Well DumpTree is not really meant to be called from lowering so I would not add the library unless there is an upstream usage of it.

**Comment by clementval** [comment]
`FrontendOpenACC` was added a while back to fix shared library dependencies https://reviews.llvm.org/D83938. I'm not sure why `FrontendOpenMP` was not added at the same time or if both are really needed.

**Comment by kparzysz** [comment]
When I looked at the "needed" libraries for `libFortranParser.so`, it still only showed the OpenACC one, even with the OpenMP library in CMakeLists.txt.  I don't know why.

**Comment by clementval** [comment]
There are some usage of `llvm::omp::getOpenMPDirectiveName` in OpenMP.cpp so DumpTree should work for you. Do you build shared libraries or out of tree?

**Comment by kparzysz** [comment]
I build shared libraries.  Looking again at the error messages---it seems like it's this symbol that's missing: `llvm::acc::getOpenACCDirectiveName(llvm::acc::Directive)`.

**Pull request merged**
