### PR TITLE
[RISCV] fix RISCVPushPopOptimizer pass

### PR DESCRIPTION
**Pull request by daniilavdeev**
RISCVPushPopOptimizer pass didn't suggest that CFI instructions can be inserted between cm.pop and ret and couldn't apply optimization in these cases. The patch fix it and allows the pass to remove CFI instructions and combine cm.pop and ret into the one instruction: cm.popret or cm.popretz.

### CODE REVIEW

**Comment by dlav-sc** [comment]
@topperc @michaelmaitland FYI

**Comment by dlav-sc** [comment]
@topperc @michaelmaitland, could you take another look, please?

**Review by topperc — APPROVED** [review]
LGTM

**Comment by dlav-sc** [comment]
**Deprecated**

I've changed the logic of https://github.com/llvm/llvm-project/pull/110810, so this patch is not needed anymore.

**Pull request closed without merging**
