### PR TITLE
[MLIR] [Transforms] Let lowerToLoopsUsingSCFForOp delete target op, fixes #83252

### LINKED ISSUE #83252: [MLIR] transform.structured.convert_to_loops does not delete target op
Minimal example:
```
func.func @gemm(%arg0 : memref<?x?xf32>, %arg1 : memref<?x?xf32>,
  %arg2 : memref<?x?xf32>) {
  linalg.matmul ins(%arg0, %arg1 : memref<?x?xf32>, memref<?x?xf32>)
      outs(%arg2 : memref<?x?xf32>)
  return
}

module attributes {transform.with_named_sequence} {
  transform.named_sequence @__transform_main(%arg1 : !transform.any_op {transform.readonly}) {
    %matmul = transform.structured.match ops{["linalg.matmul"]} in %arg1
      : (!transform.any_op) -> !transform.any_op
    transform.structured.convert_to_loops %matmul : !transform.any_op
    transform.yield
  }
}
```

Via `mlir-opt test.mlir --transform-interpreter` this gets transformed into:
```
func.func @gemm(%arg0: memref<?x?xf32>, %arg1: memref<?x?xf32>, %arg2: memref<?x?xf32>) {
   // constants abbreviated
    scf.for %arg3 = %c0_9 to %dim step %c1_10 {
      // constants abbreviated
      scf.for %arg4 = %c0_11 to %dim_4 step %c1_12 {
        // constants abbreviated
        scf.for %arg5 = %c0_13 to %dim_0 step %c1_14 {
         // constants abbreviated
          %9 = arith.mulf %2, %5 : f32
          %10 = arith.addf %8, %9 : f32
          %11 = affine.apply #map(%arg3, %arg4, %arg5)
          %12 = affine.apply #map2(%arg3, %arg4, %arg5)
          memref.store %10, %arg2[%11, %12] : memref<?x?xf32>
        }
      }
    }
    linalg.matmul ins(%arg0, %arg1 : memref<?x?xf32>, memref<?x?xf32>) outs(%arg2 : memref<?x?xf32>)
    return
}
```

With the (old) target `linalg.matmul` still standing.

### PR DESCRIPTION
**Pull request by ghost**
The function mlir::scf::lowerToLoopsUsingSCFForOp was not deleting its (structured) target op, resulting in IR with the expected loop nest in front of the still remaining (structured) op, e.g. a linalg.matmul.

This would fix issue #83252

### CODE REVIEW

**Comment by lhunloh** [comment]
Oops, another commit sneaked its way into this PR, resulting in formatter issues. I reverted that one, so only commit 2f1ef500a3295a3763174b6f1b4718a5a16a38f6 remains, as originally intended.

**Review by MaheshRavishankar — CHANGES_REQUESTED** [review]
Why not let the caller delete the op?

**Comment by lhunloh** [comment]
You are right, that's a better place, since methods around `transform::ConvertToLoopsOp::applyToOne` are deleting their targets. Moved that with the added commit.

**Review by MaheshRavishankar — APPROVED** [review]

**Comment by joker-eph** [comment]
Can you add a test case please?

**Comment by lhunloh** [comment]
Test added. And it indeed fails when rewriter.eraseOp is commented out.

**Comment by lhunloh** [comment]
#83537 implemented the same changes a day later, so closing this...

**Pull request closed without merging**
