### PR TITLE
[WIP][Attributor][AMDGPU] Improve the handling of indirect calls

### PR DESCRIPTION
**Pull request by shiltian**

### CODE REVIEW

**Comment by shiltian** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100954?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#100954** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100954?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#100953** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100953?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#100952** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/100952?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @shiltian and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by ssahasra** [comment]
The apparent change here is to simply reverse the effect of #100952 on the lit test. Would be good to have a test which shows what the improvement is.

Also, I think #100952 merely enables AAIndirectCallInfo, and feels like an integral part of this change itself. I would lean towards squashing it into this change.

**Comment by shiltian** [comment]
> The apparent change here is to simply reverse the effect of #100952 on the lit test. Would be good to have a test which shows what the improvement is.

Yes, this patch is still WIP (draft).

> Also, I think #100952 merely enables AAIndirectCallInfo, and feels like an integral part of this change itself. I would lean towards squashing it into this change.

#100953 is based on #100952 because I'd like to demonstrate how the change of function signature will work.

**Comment by shiltian** [comment]
Moved most of the code to #100952 so this one is no longer needed. Will open a new PR if anything we need to do after the two patches are landed.

**Pull request closed without merging**
