### PR TITLE
Backport "riscv-isa" module metadata to 18.x

### LINKED ISSUE #91513: [RISCV] Backport "riscv-isa" module metadata to llvm 18
This improves LTO support for RISC-V.

Relevant commits
f45b9d987dfc5904d4129aa006ab20614b3174e3
6afda56faa6260cff4e6e9264226737d96d952c1
891172d9be01dd7c7e5298f2d8fdb143add448da

I don't think they can be cherry-picked so I'll create a PR.

CC: @ilovepi

### PR DESCRIPTION
**Pull request by topperc**
Resolves #91513

### CODE REVIEW

**Comment by efriedma-quic** [comment]
Can you briefly summarize why this is important to backport?  At first glance, this is only relevant for LTO with mixed architecture specifications, which... I can see someone might want it, I guess, but it seems pretty easy to work around not having it.

**Comment by topperc** [comment]
> Can you briefly summarize why this is important to backport? At first glance, this is only relevant for LTO with mixed architecture specifications, which... I can see someone might want it, I guess, but it seems pretty easy to work around not having it.

It's not just mixed architecture specifications. Even in a non-mixed situation the Compressed instruction flag in the ELF header doesn't get set correctly for LTO. Prior to these patches, the flag is set using the subtarget features from the TargetMachine which are empty in an LTO build. The linker needs this flag to do linker relaxation for alignment correctly. The workaround is to pass `-Wl,-plugin-opt=-mattr=+c`.

CC @ilovepi who asked me to try to backport it.

**Comment by ilovepi** [comment]
This tends to bite anyone using LTO with RISCV. In particular I’m concerned about the impact on Rust, since they’ll pin LLVM until  the LLVM 19 release. About 60% of Fuchsia is implemented in rust. More if you count only count userland. 

We’re hoping to avoid a situation where we can’t use LTO on RISCV Fuchsia targets, as we’re starting to rely more on LTO configurations, to enable features like control flow integrity.

**Comment by tstellar** [comment]
@efriedma-quic Any objections to backporting this?

**Comment by efriedma-quic** [comment]
If LTO was completely broken, this seems worth taking.  And the changes look safe. LGTM.

**Comment by tstellar** [comment]
Hi @topperc (or anyone else). If you would like to add a note about this fix in the release notes (completely optional). Please reply to this comment with a one or two sentence description of the fix.  When you are done, please add the release:note label to this PR.

**Pull request merged**
