### PR TITLE
[ARM][AArch64] Add support for Arm Cortex A78AE CPU

### LINKED ISSUE #84450: Missing host id Cortex-A78AE
Cortex-A78AE does not have an host id in llvm/lib/TargetParser/Host.cpp:

       ...
        .Case("0xd0d", "cortex-a77")
        .Case("0xd41", "cortex-a78")
        .Case("0xd47", "cortex-a710")
        .Case("0xd4d", "cortex-a715")
        ...

As a result -mpcu=native doesn't work. 

CC: @davemgreen , @pratlucas , @ostannard

### PR DESCRIPTION
**Pull request by jthackray**
Add support for Arm Cortex A78AE CPU

Technical Reference Manual for Arm Cortex A78AE:
   https://developer.arm.com/documentation/101779/0003

Fixes #84450

### CODE REVIEW

**Comment by DavidSpickett** [comment]
Should this be added to the release notes? (so it doesn't get forgotten in a mad scramble in a few months time)

**Comment by jthackray** [comment]
> Should this be added to the release notes? (so it doesn't get forgotten in a mad scramble in a few months time)

Sure, happy to do that.

**Comment by DavidSpickett** [comment]
Also does this address the -mcpu=native part of https://github.com/llvm/llvm-project/issues/84450 as well?

**Review by sjoerdmeijer — APPROVED** [review]
Thanks for the quick fix. 
This looks okay to me. But let's see if @DavidSpickett has more comments before merging this.

**Comment by DavidSpickett** [comment]
> I've added a host id (0xd42) to llvm/lib/TargetParser/Host.cpp, so I think so (unless there's something else required).

Right, of course, somehow I skipped right over that.

**Review by DavidSpickett — APPROVED** [review]
Looks good to me.

**Comment by jthackray** [comment]
Linux and Windows builds are passing, but someone has left a trailing whitespace character at clang/docs/ReleaseNotes.rst:407 (not me), so I'll merge anyway.

**Pull request merged**
