### PR TITLE
InstCombine/Select: remove redundant code (NFC)

### PR DESCRIPTION
**Pull request by artagnon**
InstCombinerImpl::foldSelectInstWithICmp has some inlined code for select-icmp-xor simplification, but this simplification is already done by other code, via another path:

  (X & Y) == 0 ? X : X ^ Y ->
  ((X & Y) == 0 ? 0 : Y) ^ X ->
  (X & Y) ^ X ->
  X & ~Y

Cover the cases that it claims to simplify, and demonstrate that stripping it doesn't cause test changes.

### CODE REVIEW

**Review by dtcxzyw — COMMENTED** [review]
FYI this piece of code still has (small) code coverage on my dataset.
See also https://dtcxzyw.github.io/llvm-opt-benchmark/coverage/data/zyw/opt/actions-runner/_work/llvm-opt-benchmark/llvm-opt-benchmark/llvm/llvm-project/llvm/lib/Transforms/InstCombine/InstCombineSelect.cpp.html#L1961.

Of course we can just drop them/make the logic simpler :)

**Comment by nikic** [comment]
Could you please point to which simplification is the subsuming one? Is it foldSelectICmpEq?

**Comment by artagnon** [comment]
> Could you please point to which simplification is the subsuming one? Is it foldSelectICmpEq?

I'm not sure: I just realized that the code wasn't covered by tests, so I wrote the tests covering it; I removed the code and the tests were still passing. Will investigate more in the morning.

**Review by dtcxzyw — APPROVED** [review]
LGTM.

Another path:
```
(X & Y) == 0 ? X : X ^ Y ->
((X & Y) == 0 ? 0 : Y) ^ X ->
(X & Y) ^ X ->
X & ~Y
```

**Pull request merged**
