### PR TITLE
[lldb][ELF] Return address class map changes from symbol table parsing methods

### PR DESCRIPTION
**Pull request by DavidSpickett**
Instead of updating the member of the ObjectFileELF instance. This means that if one object file asks another to parse the symbol table, that first object's can update its address class map with the same changes that the other object did.

(I'm not returning a reference to the other object's m_address_class_map member because there may be other things in there not related to the symbol table being parsed)

This will fix the code added in
https://github.com/llvm/llvm-project/pull/90622 which broke the test `Expr/TestStringLiteralExpr.test` on 32 bit Arm Linux.

This happened because we had the program file, then asked for a better object file, which returned the same program file again. This creates a second ObjectFileELF for the same file, so when we tell the second instance to parse the symbol table it actually calls into the first instance, leaving the address class map of the second instance empty.

Which caused us to put an Arm breakpoint instuction at a Thumb return address and broke the ability to call mmap.

### CODE REVIEW

**Review by labath — APPROVED** [review]
The change makes sense to me, but this part here got me worried:
> then asked for a better object file, which returned the same program file again

Does this mean that we had two ObjectFileELF instances referring to the same file on disk floating around? That does not seem like a good idea, as the most common case is having the same file containing both the debug info and code and everything. Ideally, we would quickly determine that we have not been able to find a better match and avoid opening (parsing, mmaping, etc.) the same file twice.

**Comment by DavidSpickett** [comment]
We can compare against the path the plugin found, though it's surprising that the plugins return anything at all so maybe there is a bug there too.

It'll need a new test case, as `TestStringLiteralExpr.test` will no longer hit the code I'm changing in this PR, so I'll do it as a follow up.

**Comment by DavidSpickett** [comment]
I realised that as it was, the calling object file would get its map updated but not the other object file. Which is potentially a regression if we choose to use one or the other file for a lookup. So now the methods update the member map, and return the changes they made to it, so the caller can do the same.

But now I've done that I'm wondering why this map doesn't live in the symbol table object itself, so I'm gonna try doing that.

**Comment by DavidSpickett** [comment]
Alternative: https://github.com/llvm/llvm-project/pull/91603

**Comment by labath** [comment]
> I realised that as it was, the calling object file would get its map updated but not the other object file. Which is potentially a regression if we choose to use one or the other file for a lookup. So now the methods update the member map, and return the changes they made to it, so the caller can do the same.
> 
> But now I've done that I'm wondering why this map doesn't live in the symbol table object itself, so I'm gonna try doing that.

While I do see some advantages to the other approach, I'm not convinced it is better overall. My reasons for that are:
- The Symtab class is generic, while the approach of marking address types via fake symtab symbols is (I think) an elf invention. In fact, ObjectFileELF goes out of its way to make sure these fake symbols don't end up in the Symtab object for everyone to see, which makes it a bit strange to have that patch add them in via a back door.
- The address class queries are currently done on the object file, and the address class computation is done on the object file as well. The symtab class has nothing to do with them, and just serves as an outsourced map storage for the object file.

I don't think either of these are showstoppers, and I can live with the other approach if you feel strongly about it, but if it were up to me, I'd stick with this PR (you can put the map into both object files if you wish).

**Comment by DavidSpickett** [comment]
> The Symtab class is generic, while the approach of marking address types via fake symtab symbols is (I think) an elf invention.

I didn't see any use of `AddressClass::eCodeAlternateISA` outside of ObjectFileELF so I think you're right.

I'll go with this PR then.

**Comment by DavidSpickett** [comment]
There are a couple in MachO actually but you're right, different mechanism being used.

**Pull request merged**
