### PR TITLE
Remove `br i1 undef` from regression tests

### PR DESCRIPTION
**Pull request by leewei05**
As defined in LangRef, branching on `undef` is undefined behavior.
This PR aims to remove undefined behavior from tests. As UB tests break Alive2 and may be the root cause of breaking future optimizations.

Here's an Alive2 proof for one of the examples: https://alive2.llvm.org/ce/z/TncxhP

There are still many `br i1 undef` under `llvm/test/Transforms` and `llvm/test/Codegen`. 
I'll create more PRs to fix these tests.

@nunoplopes @regehr

### CODE REVIEW

**Review by nunoplopes — CHANGES_REQUESTED** [review]
Great work, thanks!

The MemorySSA tests you changed to use the automatic output checking must be reverted. You must keep the old checks. The auto-generated ones aren't checking the same thing. The old ones were checking that the memory phis were in the right place.

**Review by jmorse — COMMENTED** [review]
The changes in the DebugInfo directory look good.

I get the feeling that earlydup-crash.ll is the most likely to accidentally lose some tests coverage, as it's a crash-test with a broad input that (potentially) generates substantially different code for well-defined branches rather than undef branches. However, given that IIRC undef branches will eventually not be supported by LLVM, this is unavoidable.

**Comment by nunoplopes** [comment]
> The changes in the DebugInfo directory look good.
> 
> I get the feeling that earlydup-crash.ll is the most likely to accidentally lose some tests coverage, as it's a crash-test with a broad input that (potentially) generates substantially different code for well-defined branches rather than undef branches. However, given that IIRC undef branches will eventually not be supported by LLVM, this is unavoidable.

ok, then we can leave that test with `br poison` instead, so it gets out of the conversion queue, while keeping the coverage.

**Comment by regehr** [comment]
thanks for doing this!
besides what other people said, I recommend starting small-- like maybe change no more than 20 tests at a time until you get more experience doing this. the purpose of this is to increase the odds that all 20 (or whatever) of your changes are good ones, and to avoid fatiguing your code reviewers.

**Pull request merged**
