### PR TITLE
[libc] rename LLVM_LIBC_SRC___SUPPORT_UINT_H to LLVM_LIBC_SRC___SUPPORT_BIG_INT_H for consistent naming

### LINKED ISSUE #114572: [libc] wrong header guard on libc/src/__support/big_int.h
libc/src/__support/big_int.h has the header guards:
```c
#ifndef LLVM_LIBC_SRC___SUPPORT_UINT_H
#define LLVM_LIBC_SRC___SUPPORT_UINT_H
...
#endif // LLVM_LIBC_SRC___SUPPORT_UINT_H
```

These 3 should be changed to `LLVM_LIBC_SRC___SUPPORT_BIG_INT_H`.

### PR DESCRIPTION
**Pull request by a-tarasyuk**
Fixes #114572

### CODE REVIEW

**Review by michaelrj-google — APPROVED** [review]
LGTM, thanks for the patch! Do you need me to merge this for you?

**Comment by a-tarasyuk** [comment]
@michaelrj-google yes, I do. thanks

**Comment by michaelrj-google** [comment]
Done

**Pull request merged**
