### PR TITLE
Reapply "[Clang][Sema] Earlier type checking for builtin unary operators (#90500)"

### PR DESCRIPTION
**Pull request by sdkrystian**
This patch reapplies #90500, addressing a bug which caused binary operators with dependent operands to be incorrectly rebuilt by `TreeTransform`.

### CODE REVIEW

**Comment by erichkeane** [comment]
Can you point out the 'diff' inline what the change from the previous commit is?

**Comment by sdkrystian** [comment]
All the new changes are in 5ce0e969f3f94e9694545fe71b14fd8eb086f33e

**Review by erichkeane — APPROVED** [review]

**Comment by Caslyn** [comment]
Hi @sdkrystian - this appears to break in a circumstance where a custom iterator class defines the postfix operator:

```
FAILED: host_x64/obj/src/lib/zbitl/tests/zbitl-unittests.mem-config-test.cc.o
../../prebuilt/third_party/clang/custom/bin/clang++ -MD -MF host_x64/obj/src/lib/zbitl/tests/zbitl-unittests.mem-config-test.cc.o.d -D_LIBCPP_DISABLE_DEPRECATION_WARNINGS -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES -DRAPIDJSON_HAS_STDSTRING -DRAPIDJSON_HAS_CXX11_RANGE_FOR -DRAPIDJSON_HAS_CXX11_RVALUE_REFS -DRAPIDJSON_HAS_CXX11_TYPETRAITS -DRAPIDJSON_HAS_CXX11_N...
In file included from ../../src/lib/zbitl/tests/mem-config-test.cc:6:
../../src/lib/zbitl/include/lib/zbitl/items/mem-config.h:61:7: error: expression is not assignable
   61 |       ++this;
      |       ^ ~~~~
1 error generated.
```

I went ahead and attached a reproducer. Could you please revert this change and investigate?

[clang-crashreports.tar.gz](https://github.com/llvm/llvm-project/files/15337912/clang-crashreports.tar.gz)

**Comment by sdkrystian** [comment]
@Caslyn [[expr.prim.this] p3](http://eel.is/c++draft/expr.prim.this#3) states:
> [...] the expression this is a prvalue of type “pointer to _cv-qualifier-seq_ `X`” wherever `X` is the current class [...]

And [[over.match.oper] p1](http://eel.is/c++draft/over.match.oper#1) states:
> If no operand of an operator in an expression has a type that is a class or an enumeration, the operator is assumed to be a built-in operator and interpreted according to [[expr.compound]](http://eel.is/c++draft/expr.compound).

Since the type of `this` is a pointer, `++this` uses the built-in prefix increment operator. The operand of the built-in prefix increment operator must be an lvalue (and `this` is a prvalue).

**Comment by erichkeane** [comment]
> Hi @sdkrystian - this appears to break in a circumstance where a custom iterator class defines the postfix operator:
> 
> ```
> FAILED: host_x64/obj/src/lib/zbitl/tests/zbitl-unittests.mem-config-test.cc.o
> ../../prebuilt/third_party/clang/custom/bin/clang++ -MD -MF host_x64/obj/src/lib/zbitl/tests/zbitl-unittests.mem-config-test.cc.o.d -D_LIBCPP_DISABLE_DEPRECATION_WARNINGS -D_LIBCPP_DISABLE_VISIBILITY_ANNOTATIONS -D_LIBCPP_REMOVE_TRANSITIVE_INCLUDES -DRAPIDJSON_HAS_STDSTRING -DRAPIDJSON_HAS_CXX11_RANGE_FOR -DRAPIDJSON_HAS_CXX11_RVALUE_REFS -DRAPIDJSON_HAS_CXX11_TYPETRAITS -DRAPIDJSON_HAS_CXX11_N...
> In file included from ../../src/lib/zbitl/tests/mem-config-test.cc:6:
> ../../src/lib/zbitl/include/lib/zbitl/items/mem-config.h:61:7: error: expression is not assignable
>    61 |       ++this;
>       |       ^ ~~~~
> 1 error generated.
> ```
> 
> I went ahead and attached a reproducer. Could you please revert this change and investigate?
> 
> [clang-crashreports.tar.gz](https://github.com/llvm/llvm-project/files/15337912/clang-crashreports.tar.gz)

If the iterator is trying to call its own increment operator, that probably should be `++*this`.

At the moment it is trying to do something that I'd be shocked if it isn't UB, which is incrementing 'this' itself, which is a pointer.

**Comment by Caslyn** [comment]
Hi @sdkrystian & @erichkeane - my apologies!

Yes, indeed this code calls its own increment operator and it should be `++*this` - I failed to see that. Thanks for the feedback here and helping us fix this bug in our code.

**Comment by Sirraide** [comment]
See also: #92439

**Comment by ojhunt** [comment]
Should this be reverted? it's still causing the operator-> resolution failure ( #104268 ) and looks like swift's downstream fork has reverted it to avoid this regression.

**Pull request merged**
