### PR TITLE
[InstCombine] Fold `scmp(x -nsw y, 0)` to `scmp(x, y)`

### PR DESCRIPTION
**Pull request by Poseydon42**
Proof: https://alive2.llvm.org/ce/z/v6VtXz

### CODE REVIEW

**Review by dtcxzyw — APPROVED** [review]
LGTM. Thank you!

**Review by nikic — APPROVED** [review]
LGTM

**Comment by nikic** [comment]
A peculiarity of cmp intrinsics is that they do not canonicalize constants to the right (as that inverts the result), so technically there is also this conjugate pattern with 0 on the LHS: https://alive2.llvm.org/ce/z/TApp6E But probably in practice the 0 will still be on the right, normally.

**Comment by dtcxzyw** [comment]
> A peculiarity of cmp intrinsics is that they do not canonicalize constants to the right (as that inverts the result), so technically there is also this conjugate pattern with 0 on the LHS: https://alive2.llvm.org/ce/z/TApp6E But probably in practice the 0 will still be on the right, normally.

Distribution on llvm-opt-benchmark:
```
            LHSC   RHSC
SCmp  2            853
UCmp 3893      17
```

**Comment by nikic** [comment]
Huh, that's interesting. Didn't expect that ucmp has constants mostly on the left.

**Comment by Poseydon42** [comment]
> A peculiarity of cmp intrinsics is that they do not canonicalize constants to the right (as that inverts the result), so technically there is also this conjugate pattern with 0 on the LHS: https://alive2.llvm.org/ce/z/TApp6E But probably in practice the 0 will still be on the right, normally.

Looking at the data provided by @dtcxzyw it doesn't look like a case that's worth covering, but I'd like to hear your opinion on it as well.

**Comment by nikic** [comment]
I don't think we should handle it.

**Pull request merged**
