### PR TITLE
llvm/lib/CodeGen/TargetSchedule.cpp:132:12: warning: Assert statement modifies 'NIter'

### PR DESCRIPTION
**Pull request by akshaykumars614**
Modified the assert statement

### CODE REVIEW

**Comment by akshaykumars614** [comment]
I'm new to this project. Please let me know if this change is OK and if any tests required.

**Comment by JOE1994** [comment]
No test is needed.

Please change the title of this PR to informative text (instead of a URL).

By writing `closes #90328` in the commit message, you can make the linked issue get closed automatically once your commit gets merged to `main`.

**Comment by JOE1994** [comment]
Could you update the title of the commit to something like `"[llvm] Move variable update out of assert (NFC)"` ?
For LLVM commit message titles, it is standard practice to use headers indicating the updated code area, and then add summary of the change. "NFC" at the end means "No Functional Change".

 I'd also suggest to move the "`closes #90328`" message from the title to the _body_ of the commit message.

**Comment by akshaykumars614** [comment]
Got it. Thanks for the suggestion :)

**Review by JOE1994 — APPROVED** [review]

**Pull request merged**
