### PR TITLE
[llvm-cov] let text mode divider honor `--show-branch-summary` `--show-region-summary` etc

### PR DESCRIPTION
**Pull request by whentojump**
Otherwise it would be unnecessarily too long

Before

before

After

after

### CODE REVIEW

**Review by hanickadot — APPROVED** [review]

**Review by hanickadot — CHANGES_REQUESTED** [review]
You need to fix tests for things you changed in llvm-cov.

**Comment by whentojump** [comment]
Oh I just realized file reports and function reports are using two different `*Columns` array...

**Comment by hanickadot** [comment]
I also wonder why `missed functions` is not colored. But it's not about your PR.

**Comment by whentojump** [comment]
> I also wonder why `missed functions` is not colored. But it's not about your PR.

Right now the three columns for *functions* and for *instantiations* are `[not colored, not colored, colored]`

For all others, `[not colored, colored, colored]`

https://github.com/llvm/llvm-project/blob/99c43e3ce3142a93bbad4f9efeace254d9a8442c/llvm/tools/llvm-cov/CoverageReport.cpp#L237-L263

Don't know why either... :)

**Review by hanickadot — APPROVED** [review]
LGTM

**Pull request merged**
