### PR TITLE
Copy flt_scr and Any Remaining Pseudo Op Flags to their Real Counterparts

### PR DESCRIPTION
**Pull request by matinraayai**
This PR builds on #89830 and #93004. It aims to copy any remaining MCID flags missing from the real opcodes and registers like flt_scr that have a target-specific opcode. The goal is to keep the machine verifier happy if a disassembled MCInst (with real opcode and real register operands) is put into an MF and put through the code gen pipeline. Also MCID attribute checks should return the correct results.

This is a WIP; I wanted to run the idea by the AMDGPU maintainers first before making a full PR for review. I will have to update this for all instructions + all target-specific registers.

Let me know what you think @ritter-x2a @jayfoad @arsenm @kzhuravl.

### CODE REVIEW

**Review by arsenm — APPROVED** [review]

**Comment by jayfoad** [comment]
> Let me know what you think

No strong objections from me but it seems likely to rot if there is no in-tree use for this, and no way to verify it.

**Comment by matinraayai** [comment]
> > Let me know what you think
> 
> No strong objections from me but it seems likely to rot if there is no in-tree use for this, and no way to verify it.

Would it help if I contribute tests for these? I should be able to write MIR with real instructions that gets parsed, and each opcode's MCIDs gets checked for correct properties. It can then be passed to the machine verifier for a final verification.

**Comment by arsenm** [comment]
> > > Let me know what you think
> > 
> > 
> > No strong objections from me but it seems likely to rot if there is no in-tree use for this, and no way to verify it.
> 
> Would it help if I contribute tests for these? I should be able to write MIR with real instructions that gets parsed, and each opcode's MCIDs gets checked for correct properties. It can then be passed to the machine verifier for a final verification.

That would work I think

**Comment by matinraayai** [comment]
I'm dropping this PR since extending the pseudo attributes/classes to reals for both instructions and registers needs more than just changing the AMDGPU tablegen files. It also requires modification of machine verifier functions in the AMDGPU backend to work in codegen and maybe some redesigning of tablegen classes and records. 

Instead of trying to modify the AMDGPU backend, I wrote a tablegen backend which maps all registers/opcodes to their pseudo equivalent on my end, hence this PR is not needed anymore.

**Pull request closed without merging**
