### PR TITLE
[Driver] Handle Flang in same manner between Gnu and *BSD/Solaris ToolChain

### PR DESCRIPTION
**Pull request by brad0**

### CODE REVIEW

**Comment by banach-space** [comment]
@brad0 Thanks for sending this - could you provide some context in the summary? Why update the GNU Toolchain rather than *BSD  - as in, what should be source of truth here? Also, could you add tests?

I will be OK next week, but am happy for this to be merged once my comments are addressed and @MaskRay is also happy with this. Thanks!

**Comment by MaskRay** [comment]
Seems fine to me once a test is added:)

**Comment by brad0** [comment]
> Seems fine to me once a test is added:)

I cannot test as is as the frontend does not support these flags yet. I am just keeping things in sync between the C++ bit above that..
```
  if (D.CCCIsCXX() &&
      !Args.hasArg(options::OPT_nostdlib, options::OPT_nodefaultlibs,
                   options::OPT_r)) {
```
and the behavior being the same for the other OS's.

But I am working on a patch for the frontend to enable the flags. So I'll just keep this around for a bit and then update it.

**Review by MaskRay — APPROVED** [review]

**Comment by brad0** [comment]
So with https://github.com/llvm/llvm-project/pull/72601, once that goes in I can update this with RUN line updates to test. It fails as expected without this.

**Pull request closed without merging**
