### PR TITLE
[AMDGPU] gfx1152 does not have Feature1_5xVGPRs

### PR DESCRIPTION
**Pull request by jayfoad**

### CODE REVIEW

**Review by shiltian — APPROVED** [review]
~How about the new 1153 just added in another PR?~

Didn’t see your comment in another PR. LGTM.

**Comment by perlfu** [comment]
@jayfoad I don't understand, the section says "Not all VGPRs can be used on:", i.e. 1.5x VGPRs are not available?

**Comment by perlfu** [comment]
> @jayfoad I don't understand, the section says "Not all VGPRs can be used on:", i.e. 1.5x VGPRs are not available?

Ignore me, I get it now.
Can we perhaps reword the section title while we are here?

**Comment by jayfoad** [comment]
> > @jayfoad I don't understand, the section says "Not all VGPRs can be used on:", i.e. 1.5x VGPRs are not available?
> 
> Ignore me, I get it now.

Yeah, I had the same kind of confusion when I first read it.

**Comment by jayfoad** [comment]
> Can we perhaps reword the section title while we are here?

Feel free to propose your own rewording :)

**Pull request merged**
