### PR TITLE
Make __libcpp_verbose_abort() noexcept like std::terminate()

### PR DESCRIPTION
**Pull request by dougsonos**
Make __libcpp_verbose_abort() noexcept (it is already noreturn), to match std::terminate(). Clang's function effect analysis can use this to ignore such functions as being beyond its scope. (See https://github.com/llvm/llvm-project/pull/99656)

### CODE REVIEW

**Comment by dougsonos** [comment]
Oops, I forgot to make the implementation `noexcept` too. This highlights that the question here is whether changing this interface to `noexcept` is going to break anything...

**Review by ldionne — COMMENTED** [review]
This makes sense to me, however this is technically a breaking change because in the past we have advertised `__libcpp_verbose_abort` as being overridable (that's why it was a weak def).

We'd also want to add a release note for this change in `libcxx/docs/ReleaseNotes/20.rst`, probably under `Deprecations and Removals`.

Pinging @llvm/libcxx-vendors for awareness.

**Comment by dougsonos** [comment]
Any pointers on what's going on with the test builds? I click Details and just see "job failed".

**Comment by ldionne** [comment]
> Any pointers on what's going on with the test builds? I click Details and just see "job failed".

Our CI is currently in a really bad state. Workers are failing to connect. This has been going on for a few days and we're trying to resolve the issue. Sorry for the inconvenience.

**Comment by ldionne** [comment]
Please rebase onto main to re-trigger CI. The CI instability should be resolved now.

**Comment by dougsonos** [comment]
I should have trusted the CI and seen this error!

```
# | /home/runner/_work/llvm-project/llvm-project/libcxx/test/libcxx/assertions/customize_verbose_abort.link-time.pass.cpp:18:52: error: expected function body after function declarator
# |    18 | void std::__libcpp_verbose_abort(char const*, ...) noexcept { std::exit(EXIT_SUCCESS); }
# |       |                                                    ^
# | 1 error generated.
```

**Comment by dougsonos** [comment]
Ping

**Review by ldionne — APPROVED** [review]

**Comment by BwL1289** [comment]
@dougsonos this breaks flang compilation because flang overrides [this symbol](https://github.com/llvm/llvm-project/blob/af90e7c5161de9a36af768dd5c9d73464e0eed64/flang/runtime/io-api-minimal.cpp#L153) and doesn't use `noexcept` attribute

**Comment by ldionne** [comment]
> @dougsonos this breaks flang compilation because flang overrides [this symbol](https://github.com/llvm/llvm-project/blob/af90e7c5161de9a36af768dd5c9d73464e0eed64/flang/runtime/io-api-minimal.cpp#L153) and doesn't use `noexcept` attribute

In fact, we want to move away from supporting overriding that function. The way of customizing the assertion handler is when configuring the library, as explained here: https://libcxx.llvm.org/Hardening.html#overriding-the-assertion-failure-handler

**Comment by mstorsjo** [comment]
> > @dougsonos this breaks flang compilation because flang overrides [this symbol](https://github.com/llvm/llvm-project/blob/af90e7c5161de9a36af768dd5c9d73464e0eed64/flang/runtime/io-api-minimal.cpp#L153) and doesn't use `noexcept` attribute
> 
> In fact, we want to move away from supporting overriding that function. The way of customizing the assertion handler is when configuring the library, as explained here: https://libcxx.llvm.org/Hardening.html#overriding-the-assertion-failure-handler

@ldionne - The issue here from the Flang perspective, is not that flang want to override the function, they don't really care. The thing is that Flang uses some classes from the C++ standard library (from `std::variant` iirc) but don't want to link against the C++ standard library. When using the libc++ implementation of `std::variant`, they end up with undefined references to `std::__libcpp_verbose_abort` unless they actually override/provide it themselves.

**Comment by ldionne** [comment]
Moving the discussion to https://github.com/llvm/llvm-project/issues/113059#issuecomment-2427618278 to centralize things.

**Comment by Caslyn** [comment]
Hi @ldionne,

Unfortunately this is breaking when trying to build Fuchsia with a clang version that includes this change. Here is a link to the build failure we're seeing: 

https://luci-milo.appspot.com/ui/p/fuchsia/builders/ci/clang_toolchain.ci.core.arm64-debug/b8733819071213133329/overview

There are places in the Fuchsia checkout that provide their own definitions of this function: 

https://cs.opensource.google/search?q=__libcpp_verbose_abort

Can you make this backwards compatible and provide a means to transition to the `noexcept` version of this function?

**Pull request merged**
