### PR TITLE
[flang] Use llvm::is_contained (NFC)

### PR DESCRIPTION
**Pull request by kazutakahirata**

### CODE REVIEW

**Review by clementval — APPROVED** [review]
LGTM

**Review by klausler — COMMENTED** [review]
Why is this a good change?

**Comment by kazutakahirata** [comment]
> Why is this a good change?

Because the new code accomplishes the same task with less code, specifically without repeating container names multiple times.

**Comment by klausler** [comment]
> > Why is this a good change?
> 
> Because the new code accomplishes the same task with less code, specifically without repeating container names multiple times.

But now it has more dependencies than just the standard library, which makes it less portable.  It seems like a bad deal to me.

**Pull request merged**
