### PR TITLE
Aim debugserver workaround more precisely.

### PR DESCRIPTION
**Pull request by adrian-prantl**

### CODE REVIEW

**Comment by jasonmolenda** [comment]
I'm a little split because the current packet is not super useful as it's constructed today - I'd really like to see a domain or vendor along with a version number  And instead of a simple number, maybe a major/minor version number and/or a version string?  I'm also fine with landing this now, detecting an "old" apple debugserver as 1000 < version number < 1504, and I can do the version packet fix separately and update the check.

**Comment by jasonmolenda** [comment]
I'm not fishing for Adrian to dig in to that, I'm happy to make the change.  but I'm curious what @JDevlieghere and @adrian-prantl think, if it's worth changing this packet.  It's not used anywhere yet, so overhauling it now before/shortly after we actually start using it, is the right way to go.

**Review by jasonmolenda — APPROVED** [review]
LGTM, let's land this patch.  I will extend the stub version packet with additional fields (Jonas points out that other stubs implement this packet already as-is) and update this once that PR is approved and merged.  But we don't need to block this PR on getting that done.

**Review by JDevlieghere — APPROVED** [review]
I'm happy if Jason is happy!

**Pull request merged**
