### PR TITLE
[flang] run CFG conversion on omp reduction declare ops

### PR DESCRIPTION
**Pull request by tblah**
Most FIR passes only look for FIR operations inside of functions (either because they run only on func.func or they run on the module but iterate over functions internally). But there can also be FIR operations inside of fir.global, some OpenMP and OpenACC container operations.

This has worked so far for fir.global and OpenMP reductions because they only contained very simple FIR code which doesn't need most passes to be lowered into LLVM IR. I am not sure how OpenACC works.

In the long run, I hope to see a more systematic approach to making sure that every pass runs on all of these container operations. I will write an RFC for this soon.

In the meantime, this pass duplicates the CFG conversion pass to also run on omp reduction operations. This is similar to how the AbstractResult pass is already duplicated for fir.global operations.

OpenMP array reductions 2/6
Previous PR: https://github.com/llvm/llvm-project/pull/84952
Next PR: https://github.com/llvm/llvm-project/pull/84954

### CODE REVIEW

**Comment by clementval** [comment]
Wouldn't it be cleaner to expose the patterns via a `populateFirCfgConversionPatterns` function and reuse it in you extra pass instead of making two pass from the initial file?

We did this recently for the FirToLLVM patterns. https://github.com/llvm/llvm-project/pull/83492

**Comment by tblah** [comment]
> Wouldn't it be cleaner to expose the patterns via a `populateFirCfgConversionPatterns` function and reuse it in you extra pass instead of making two pass from the initial file?
> 
> We did this recently for the FirToLLVM patterns. #83492

Thanks for taking a look at this. I have extracted the patterns into an externally visible function, but I don't understand the benefit of splitting the two CFG conversion passes out into different files. I think this could be confusing because it would be unclear which file one should contain the definition of those conversion patterns. Keeping it in one file makes it clear that both do exactly the same thing on different target operations.

**Comment by tblah** [comment]
> Wouldn't applying the patterns on the module in a single pass work here as well?

Yes that would work but we would loose parallelism. I wanted to keep that because there was talk in the past about breaking up the existing Module passes so that different functions (or other container operations) can be processed in parallel

**Comment by clementval** [comment]
> > Wouldn't applying the patterns on the module in a single pass work here as well?
> 
> Yes that would work but we would loose parallelism. I wanted to keep that because there was talk in the past about breaking up the existing Module passes so that different functions (or other container operations) can be processed in parallel

Ok that makes sense. It would be nice to have a solution to for top level operations since we have more than two. Have you discuss with MLIR folks yet?

**Comment by clementval** [comment]
> > > > Wouldn't applying the patterns on the module in a single pass work here as well?
> > > 
> > > 
> > > Yes that would work but we would loose parallelism. I wanted to keep that because there was talk in the past about breaking up the existing Module passes so that different functions (or other container operations) can be processed in parallel
> > 
> > 
> > Ok that makes sense. It would be nice to have a solution to for top level operations since we have more than two. Have you discuss with MLIR folks yet?
> 
> I have created an RFC here https://discourse.llvm.org/t/rfc-add-an-interface-for-top-level-container-operations/77807
> 
> Would it be okay to merge this pass as it is for now (there is already precedent in how fir.global is handled) and then fix everything together once a solution has been agreed upon?

Thanks for the RFC. I'm ok if you merge this for the time being.

**Comment by tblah** [comment]
Thanks for the review.

I rebased on main so it is clearer to everyone what is part of this patch.

**Review by kiranchandramohan — APPROVED** [review]
LGTM. 

Please add a test before you submit.

**Pull request merged**
