### PR TITLE
[lldb] Unify implementation of CommandReturnObject::SetError(NFC)

### PR DESCRIPTION
**Pull request by adrian-prantl**
This is a cleanup that moves the API towards value semantics.

### CODE REVIEW

**Comment by jimingham** [comment]
`SetError(Status error, const char* fallback_error_string)` was a badly named API.  What it actually does is APPEND either the error string in the incoming `error`, or if that had no error string, the `fallback_error_string`, to whatever was already in the command error.
So far as I can tell, there are no internal uses of this fallback_error_string (I removed that argument from the API and lldb still compiles.)  However, we made an equally poorly named SBCommandReturnObject API that does take this string.
So this change does change the behavior of this quite poorly named API which I bet no one was using for that purpose, but still...

**Review by medismailben — COMMENTED** [review]
LGTM!

**Comment by jimingham** [comment]
I actually think it's fine to change this behavior, I don't think anyone would have expected SetError to AppendError...

**Comment by medismailben** [comment]
> I actually think it's fine to change this behavior, I don't think anyone would have expected SetError to AppendError...

If you feel strongly about this (I actually think you have a point), you could make `SetError` as deprecated and have it call a newly added `AppendError` API which makes more sense IMO.

**Comment by jimingham** [comment]
> > I actually think it's fine to change this behavior, I don't think anyone would have expected SetError to AppendError...
> 
> If you feel strongly about this (I actually think you have a point), you could make `SetError` as deprecated and have it call a newly added `AppendError` API which makes more sense IMO.

I think both are useful, and indeed, we have both "SetError" and "AppendError" internally in CommandResultObject, and we use both.  I don't think we need to deprecate SetError, but we should make is set the error to what you pass in, and then add AppendError which will add to what's there.  If somebody out there was using SBCommandReturnObject::SetError to append to the error, then they just need to switch to the actually appropriate API now we've provided it.

**Pull request merged**
