### PR TITLE
[JumpThreading] Don't phi translate past loop phi

### PR DESCRIPTION
**Pull request by nikic**
When evaluating comparisons in predecessors, phi operands are translated into the predecessor. If the translation is across a backedge, this means that the two operands of the icmp will be from two different loop iterations, resulting in incorrect simplification.

Fix this by not performing the phi translation for phis in loop headers.

Note: This is not a complete fix. If the
jump-threading-across-loop-headers option is enabled, the LoopHeaders variable does not get populated. Additional changes will be needed to fix that case.

Related to https://github.com/llvm/llvm-project/issues/70651.

### CODE REVIEW

**Comment by nikic** [comment]
The other problem here is that LoopHeaders may not be up-to-date. As it was previously only used for heuristics, using it for correctness now may be a bit iffy.

**Comment by alexfh** [comment]
Thanks! This fixes the original problem that led to the report in https://github.com/llvm/llvm-project/commit/b22917e6e2a0aec05474f58e64b7e87d1ea0a054#commitcomment-131124585.

**Review by XChy — APPROVED** [review]
LGTM.

**Comment by XChy** [comment]
It would be more complete and precise if we calculate and maintain all backedges(we did calculate it in findLoopHeaders) and  at the beginning. In this way, we can prevent phi translate when (Pred, BB) is a backedge, instead of when BB is simply a loop header.

**Comment by nikic** [comment]
> It would be more complete and precise if we calculate and maintain all backedges(we did calculate it in findLoopHeaders) at the beginning even with cross-loop-header option. In this way, we can prevent phi translate when (Pred, BB) is a backedge, instead of when BB is simply a loop header.

I agree that checking backedges would be more precise here. Only problem is that we then need to maintain the backedge set across transforms. I'm not sure how hard this would be for the case where we can thread across loop headers.

**Comment by XChy** [comment]
> I'm not sure how hard this would be for the case where we can thread across loop headers.
While dom-tree is preserved during JumpThreading, I think it's easy to check whether an edge is backedge with it.

**Comment by nikic** [comment]
@XChy It's not possible to query DT during JumpThreading, because flushing updates is too expensive.

**Comment by XChy** [comment]
> @XChy It's not possible to query DT during JumpThreading, because flushing updates is too expensive.

You are right. It's similar to SimplifyCFG's case. We still need to maintain the backedges by ourselves.

**Pull request merged**
