### PR TITLE
[AST] RecursiveASTVisitor: Don't traverse the alias deduction guides in the default mode.

### PR DESCRIPTION
**Pull request by hokein**
By default (`shouldVisitImplicitCode()` returns `false`), RAV should not traverse AST nodes that are not spelled in the source code. Deduction guides for alias templates are always synthesized, so they should not be traversed.

This is usually done by checking the implicit bit of the Decl. However, this doesn't work deduction guides that are synthesized from explicit user-defined deduction guides, as we must maintain the explicit bit to ensure correct overload resolution.

### CODE REVIEW

**Review by cor3ntin — APPROVED** [review]
LGTM

**Comment by keith** [comment]
@hokein looks like this test wasn't added to any CMakeLists.txt so it doesn't actually run?

**Comment by keith** [comment]
I think you want it here? https://github.com/llvm/llvm-project/blob/c7bfc41860a6abe5c92dc5afb47348b0c9e69963/clang/unittests/Tooling/CMakeLists.txt#L42

**Comment by keith** [comment]
https://github.com/llvm/llvm-project/pull/99907

**Pull request merged**
