### PR TITLE
Revert "[HLSL] Vector standard conversions (#71098)"

### PR DESCRIPTION
**Pull request by Prabhuk**
This reverts commit 5c57fd717d5d6a285efeb8402c6fe0c8f70592f3. 
This commit causes crashes in Clang codegen tests.

### CODE REVIEW

**Review by llvm-beanz — APPROVED** [review]
Sorry for the breakage. I'll investigate and re-land.

**Comment by llvm-beanz** [comment]
I pushed a speculative fix in 0065161c720c37e8ab545979aed6a03d944a3176.

**Comment by llvm-beanz** [comment]
My fix seems to be righting the Linux bots. They should all be going green again.

**Comment by Prabhuk** [comment]
Thank you. The crashes have stopped happening after https://github.com/llvm/llvm-project/commit/0065161c720c37e8ab545979aed6a03d944a3176

Abandoning this PR.

**Pull request closed without merging**
