### PR TITLE
[Hexagon] Optimize post-increment load and stores in loops.

### PR DESCRIPTION
**Pull request by sgundapa**
This patch optimizes the post-increment instructions so that we can packetize them together.
v1 = phi(v0, v3')
v2,v3  = post_load v1, 4
v2',v3'= post_load v3, 4

This can be optimized in two ways

v1 = phi(v0, v3')
v2,v3' = post_load v1, 8
v2' = load v1, 4

### CODE REVIEW

**Review by androm3da — APPROVED** [review]

**Review by iajbar — APPROVED** [review]

**Comment by steven-johnson** [comment]
This has broken HVX Codegen in Halide; our tests now fail with

```
vsub(v*:*.h,v*:*.h)  Failed Opcode is : 2656 (V6_vL32b_pred_ai)
No offset range is defined for this opcode. Please define it in the above switch statement!
UNREACHABLE executed at /home/halidenightly/build_bot/worker/llvm-19-x86-64-linux/llvm-project/llvm/lib/Target/Hexagon/HexagonInstrInfo.cpp:2981!
```
(see e.g. https://buildbot.halide-lang.org/master/#/builders/118/builds/86/steps/12/logs/correctness_simd_op_check_hvx)

Please either roll back this change ASAP or offer a fix-forward as this is blocking Halide from passing our tests.

**Comment by sgundapa** [comment]
I will take a look and fix it.

**Comment by sgundapa** [comment]
I am currently working on a fix

**Comment by sgundapa** [comment]
Fix  undr review here: https://github.com/llvm/llvm-project/pull/82386

**Pull request merged**
