### PR TITLE
[AArch64][GISel] Avoid scalarizing G_IMPLICIT_DEF and G_FREEZE in the Legalizer

### PR DESCRIPTION
**Pull request by dc03-work**
It does not make sense to scalarize G_FREEZE as it leads to the generation
of pairs of G_UNMERGE_VALUES and G_BUILD_VECTORs which are difficult to
optimize especially when operations like G_TRUNC operate before G_FREEZE
but after G_UNMERGE_VALUES.

Instead, it is better to legalize G_FREEZE like any other vector type
would be, as it gets lowered to a COPY during instruction selection
anyways.

This is an issue that was encountered when looking at the TSVC
benchmark, where the legalization of G_FREEZE would cause generation of
unnecessary MOVs that adversely affected the performance.

### CODE REVIEW

**Comment by dc03-work** [comment]
The updates to the test cases are in https://github.com/llvm/llvm-project/pull/88469/commits/dca4dfc6e15b47c1bdf3d174894d7dc3119a1ce6.

**Review by arsenm — COMMENTED** [review]
Fundamentally G_FREEZE and G_IMPLICIT_DEF have the same property of being synthetic compiler operations that need to be legal for all register types. They really should have the same legalization rules. It may make sense to replace the current set of rules, but I think they should be moved together

**Comment by dc03-work** [comment]
> Fundamentally G_FREEZE and G_IMPLICIT_DEF have the same property of being synthetic compiler operations that need to be legal for all register types. They really should have the same legalization rules. It may make sense to replace the current set of rules, but I think they should be moved together

The reason I separated G_FREEZE out was because I found your commit about implementing fewerElementsIf() for G_IMPLICIT_DEF (https://github.com/llvm/llvm-project/commit/3dddb163dd73f69420f356f96e86bb67232b6c95#diff-973c8a5764852eef4468cf4ba0dd6b70a2e0bf769640c9ff728c1f3613908abc) and I was not sure if this was being done for any special reason.

In an ideal world, both G_FREEZE and G_IMPLICIT_DEF would just be able to copy the types (after legalization) of the input operand and of any uses respectively, however I don't think that is possible with the current design of the legalizer.

**Comment by arsenm** [comment]
> > Fundamentally G_FREEZE and G_IMPLICIT_DEF have the same property of being synthetic compiler operations that need to be legal for all register types. They really should have the same legalization rules. It may make sense to replace the current set of rules, but I think they should be moved together
> 
> and I was not sure if this was being done for any special reason.

These was a lot less implemented back then, and it was easier to implement one piece at a time. Intrinsically, these should have the same rules.

**Comment by arsenm** [comment]
> These was a lot less implemented back then, and it was easier to implement one piece at a time. Intrinsically, these should have the same rules.

This commit is so old, I'm not sure freeze was even in the IR yet

**Review by arsenm — APPROVED** [review]

**Comment by dc03-work** [comment]
Pre-commit failures look unrelated to the PR - from what I can see MSVC is running out of memory while building flang and it is crashing there.

**Pull request merged**
