### PR TITLE
[clangd] Implement simple folding of preprocessor branches

### LINKED ISSUE #1661: Precompiled macro #ifndef/#if/#elif/#else/#endif areas do not code fold
The latest [[clangd-17](https://github.com/llvm/llvm-project)](https://github.com/llvm/llvm-project) still does not natively support code folding in the area where precompiled directives like '#ifndef', '#if', '#elif', '#else', '#endif', etc. The actual display effect in vscode is as follows,

fold

Note that you can currently only fold the area where `{`,`}` is located.

In order to support precompiled macro areas that can be coded to support code folding, I have to use [Explicit Folding](https://marketplace.visualstudio.com/items?itemName=zokugun.explicit-folding) extension to achieve the effect of the folding, the following figure,
fold1

Does clangd have any plans to natively support this feature?

### PR DESCRIPTION
**Pull request by 144026**
Extract directive branches information from DirectiveTree, fold branches that don't end with eof.

Fixes https://github.com/clangd/clangd/issues/1661

Examples:

Folded: 
image

Unfolded:
image

Folded (unpaired conditionals):
image

Unfolded (unpaired conditionals):
image

### CODE REVIEW

**Comment by zyn0217** [comment]
Note that clang-pseudo is deprecated and will soon get [removed](https://github.com/llvm/llvm-project/pull/80081) from the repository. I have no idea about the replacement, and I'm not sure if it makes sense to evolve the feature with it. 

I invited some folks (who may be in charge of clang-pseudo) for visibility.

**Comment by 144026** [comment]
@zyn0217  Thanks for the information, seems like a completed removal of pseudo parser has been decided in this [discourse thread](https://discourse.llvm.org/t/removing-pseudo-parser/71131), and shifting back to AST parser for foldingRange support would only lose a marginal multi-line comment folding feature.

Dependency of this patch hasn't been touched yet in #80081 , so I tested a rebased build of this patch on #80081 on my Linux box, which still could pass and work.

I understand that evolving this end-of-life parser only adds maintenance burden and should be avoided, but I hope there will be some ways (may be in the original AST parser?) to support PP conditional folding, especially when reading complex headers.

**Comment by 144026** [comment]
The build pipeline failure is on Windows x64, and appears to be some random error irrelevant to this patch:
```
MT: command "C:\Program Files (x86)\Windows Kits\10\bin\10.0.19041.0\x64\mt.exe /nologo /manifest bin\dexp.exe.manifest /outputresource:bin\dexp.exe;#1" failed (exit code 0x1f) with the following output:
mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "bin\dexp.exe". Operation did not complete successfully because the file contains a virus or potentially unwanted software.
```

**Comment by torshepherd** [comment]
Darn, this was just closed last week as I put up an issue https://github.com/llvm/llvm-project/issues/110390 😭 

Clang-pseudo was just removed: https://github.com/llvm/llvm-project/pull/80081#issuecomment-2361060164 

Is the plan to refactor now and re-put this up?

**Comment by aaronliu0130** [comment]
I'm new to this, but from what I see, this PR could be easily put up simply removing the pseudo:: prefixes.

**Pull request closed without merging**
