### PR TITLE
[Clang] Allow diagnostics starting with Arm

### PR DESCRIPTION
**Pull request by amilendra**
We (Arm) have a few downstream-only diagnostics that start with Arm, so wish to add Arm to the list of allowed start words.

### CODE REVIEW

**Comment by jroelofs** [comment]
If the diagnostics are downstream-only, does this really need go upstream?

**Comment by amilendra** [comment]
> If the diagnostics are downstream-only, does this really need go upstream?

We try to upstream as much as possible to reduce merge conflicts.

**Comment by amilendra** [comment]
> > If the diagnostics are downstream-only, does this really need go upstream?
> 
> We try to upstream as much as possible to reduce merge conflicts.

@jroelofs 
Do you have any objections to commiting this?

**Comment by jroelofs** [comment]
This one looks fairly benign, and while I agree that it is good to upstream things wherever possible, my slight objection rests mostly on two principles:

* In general the community doesn't take behavior-changing patches purely on the basis of eliminating merge conflicts for code that is out of tree. Things that go upstream need to have a justification that is relevant to upstream.
* Changes that land need to come with tests that exercise them.

FWIW, this particular change looks unlikely to be a source of merge conflicts, as it adds only a single line to a table that is unlikely to be touched very often. I think you'll be okay if this isn't upstream, but I won't complain too loudly if you feel the need to land this anyway.

**Comment by amilendra** [comment]
> This one looks fairly benign, and while I agree that it is good to upstream things wherever possible, my slight objection rests mostly on two principles:
> 
>     * In general the community doesn't take behavior-changing patches purely on the basis of eliminating merge conflicts for code that is out of tree. Things that go upstream need to have a justification that is relevant to upstream.
> 
>     * Changes that land need to come with tests that exercise them.
> 
> 
> FWIW, this particular change looks unlikely to be a source of merge conflicts, as it adds only a single line to a table that is unlikely to be touched very often. I think you'll be okay if this isn't upstream, but I won't complain too loudly if you feel the need to land this anyway.

Thanks for the explanation. Yes, this seems simple enough that it won't be too hard to resolve even if a merge conflict appears. I'll abandon the change. Thanks for taking the time to review this.

**Pull request closed without merging**
