### PR TITLE
[ExceptionDemo] Correct and update example ExceptionDemo

### LINKED ISSUE #63702: LLVM Build fails if exception enabled
CMake options to reproduce.
`-DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_RTTI=ON -DLLVM_BUILD_EXAMPLES=ON`
```console
/home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp: In function ‘uintptr_t readSLEB128(const uint8_t**)’:
/home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp:374:22: warning: left shift of negative value [-Wshift-negative-value]
  374 |     result |= (~0 << shift);
      |                      ^~~~~
/home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp: In function ‘llvm::BasicBlock* createFinallyBlock(llvm::LLVMContext&, llvm::Module&, llvm::IRBuilder<>&, llvm::Function&, std::string&, std::string&, llvm::BasicBlock&, llvm::BasicBlock&, llvm::Value**, llvm::Value**, llvm::Value**)’:
/home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp:1001:76: error: no matching function for call to ‘llvm::IRBuilder<>::CreateLoad(llvm::Value*&)’
 1001 |                                                        *exceptionCaughtFlag),
      |                                                                            ^
In file included from /home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp:56:
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1735:13: note: candidate: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Type*, llvm::Value*, const char*)’
 1735 |   LoadInst *CreateLoad(Type *Ty, Value *Ptr, const char *Name) {
      |             ^~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1735:13: note:   candidate expects 3 arguments, 1 provided
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1739:13: note: candidate: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Type*, llvm::Value*, const llvm::Twine&)’
 1739 |   LoadInst *CreateLoad(Type *Ty, Value *Ptr, const Twine &Name = "") {
      |             ^~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1739:13: note:   candidate expects 3 arguments, 1 provided
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1743:13: note: candidate: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Type*, llvm::Value*, bool, const llvm::Twine&)’
 1743 |   LoadInst *CreateLoad(Type *Ty, Value *Ptr, bool isVolatile,
      |             ^~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1743:13: note:   candidate expects 4 arguments, 1 provided
/home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp: In function ‘llvm::Function* createCatchWrappedInvokeFunction(llvm::Module&, llvm::IRBuilder<>&, llvm::legacy::FunctionPassManager&, llvm::Function&, std::string, unsigned int, unsigned int*)’:
/home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp:1189:57: error: no matching function for call to ‘llvm::IRBuilder<>::CreateLoad(llvm::Value*&)’
 1189 |                      builder.CreateLoad(exceptionStorage));
      |                                                         ^
In file included from /home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp:56:
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1735:13: note: candidate: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Type*, llvm::Value*, const char*)’
 1735 |   LoadInst *CreateLoad(Type *Ty, Value *Ptr, const char *Name) {
      |             ^~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1735:13: note:   candidate expects 3 arguments, 1 provided
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1739:13: note: candidate: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Type*, llvm::Value*, const llvm::Twine&)’
 1739 |   LoadInst *CreateLoad(Type *Ty, Value *Ptr, const Twine &Name = "") {
      |             ^~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1739:13: note:   candidate expects 3 arguments, 1 provided
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1743:13: note: candidate: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Type*, llvm::Value*, bool, const llvm::Twine&)’
 1743 |   LoadInst *CreateLoad(Type *Ty, Value *Ptr, bool isVolatile,
      |             ^~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1743:13: note:   candidate expects 4 arguments, 1 provided
/home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp:1209:62: error: no matching function for call to ‘llvm::IRBuilder<>::CreateLoad(llvm::Value*&)’
 1209 |   builder.CreateResume(builder.CreateLoad(caughtResultStorage));
      |                                                              ^
In file included from /home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp:56:
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1735:13: note: candidate: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Type*, llvm::Value*, const char*)’
 1735 |   LoadInst *CreateLoad(Type *Ty, Value *Ptr, const char *Name) {
      |             ^~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1735:13: note:   candidate expects 3 arguments, 1 provided
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1739:13: note: candidate: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Type*, llvm::Value*, const llvm::Twine&)’
 1739 |   LoadInst *CreateLoad(Type *Ty, Value *Ptr, const Twine &Name = "") {
      |             ^~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1739:13: note:   candidate expects 3 arguments, 1 provided
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1743:13: note: candidate: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Type*, llvm::Value*, bool, const llvm::Twine&)’
 1743 |   LoadInst *CreateLoad(Type *Ty, Value *Ptr, bool isVolatile,
      |             ^~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1743:13: note:   candidate expects 4 arguments, 1 provided
/home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp:1249:13: error: no matching function for call to ‘llvm::IRBuilder<>::CreateLoad(llvm::Value*)’
 1249 |           0));
      |             ^
In file included from /home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp:56:
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1735:13: note: candidate: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Type*, llvm::Value*, const char*)’
 1735 |   LoadInst *CreateLoad(Type *Ty, Value *Ptr, const char *Name) {
      |             ^~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1735:13: note:   candidate expects 3 arguments, 1 provided
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1739:13: note: candidate: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Type*, llvm::Value*, const llvm::Twine&)’
 1739 |   LoadInst *CreateLoad(Type *Ty, Value *Ptr, const Twine &Name = "") {
      |             ^~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1739:13: note:   candidate expects 3 arguments, 1 provided
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1743:13: note: candidate: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Type*, llvm::Value*, bool, const llvm::Twine&)’
 1743 |   LoadInst *CreateLoad(Type *Ty, Value *Ptr, bool isVolatile,
      |             ^~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1743:13: note:   candidate expects 4 arguments, 1 provided
/home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp:1282:79: error: no matching function for call to ‘llvm::IRBuilder<>::CreateConstGEP1_64(llvm::Value*&, int64_t&)’
 1282 |                                                        ourBaseFromUnwindOffset),
      |                                                                               ^
In file included from /home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp:56:
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1872:10: note: candidate: ‘llvm::Value* llvm::IRBuilderBase::CreateConstGEP1_64(llvm::Type*, llvm::Value*, uint64_t, const llvm::Twine&)’
 1872 |   Value *CreateConstGEP1_64(Type *Ty, Value *Ptr, uint64_t Idx0,
      |          ^~~~~~~~~~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1872:10: note:   candidate expects 4 arguments, 2 provided
/home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp:1298:63: error: no matching function for call to ‘llvm::IRBuilder<>::CreateLoad(llvm::Value*&)’
 1298 |                        *(builder.CreateLoad(typeInfoThrownType)),
      |                                                               ^
In file included from /home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp:56:
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1735:13: note: candidate: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Type*, llvm::Value*, const char*)’
 1735 |   LoadInst *CreateLoad(Type *Ty, Value *Ptr, const char *Name) {
      |             ^~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1735:13: note:   candidate expects 3 arguments, 1 provided
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1739:13: note: candidate: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Type*, llvm::Value*, const llvm::Twine&)’
 1739 |   LoadInst *CreateLoad(Type *Ty, Value *Ptr, const Twine &Name = "") {
      |             ^~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1739:13: note:   candidate expects 3 arguments, 1 provided
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1743:13: note: candidate: ‘llvm::LoadInst* llvm::IRBuilderBase::CreateLoad(llvm::Type*, llvm::Value*, bool, const llvm::Twine&)’
 1743 |   LoadInst *CreateLoad(Type *Ty, Value *Ptr, bool isVolatile,
      |             ^~~~~~~~~~
/home/kkumar/llvm-project/llvm/include/llvm/IR/IRBuilder.h:1743:13: note:   candidate expects 4 arguments, 1 provided
/home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp: In function ‘void runExceptionThrow(llvm::ExecutionEngine*, llvm::Function*, int32_t)’:
/home/kkumar/llvm-project/llvm/examples/ExceptionDemo/ExceptionDemo.cpp:1563:29: warning: catching polymorphic type ‘class {anonymous}::OurCppRunException’ by value [-Wcatch-value=]
 1563 |   catch (OurCppRunException exc) {
      |                             ^~~
```

### PR DESCRIPTION
**Pull request by epitavy**
The ExceptionDemo example was no longer compiling (since llvm 14 at least). The PR makes the example work with the current API and also transition from MCJIT to ORC.
Fixes #63702

### CODE REVIEW

**Comment by epitavy** [comment]
ping

**Review by lhames — COMMENTED** [review]
This should not be needed on top-of-tree: LLJIT now reflects process symbols by default.

**Comment by lhames** [comment]
Otherwise LGTM.

**Comment by epitavy** [comment]
That true, I just removed the corresponding code

**Review by lhames — COMMENTED** [review]
LGTM. Thanks @epitavy!

**Comment by epitavy** [comment]
Thanks @lhames .
I am not sure of the next steps I rebased main onto this branch but I don't have the commit permission

**Comment by epitavy** [comment]
Ping @lhames

**Comment by kmistryic** [comment]
@epitavy , can you rebase and follow guideline here https://llvm.org/docs/GitHub.html

**Comment by kamleshbhalui** [comment]
@epitavy , Have you tested locally with below command?
`cmake ../llvm  -DCMAKE_BUILD_TYPE=Debug  -DLLVM_ENABLE_EH=ON -DLLVM_ENABLE_RTTI=ON -DLLVM_BUILD_EXAMPLES=ON`

**Comment by kamleshbhalui** [comment]
I just tried It still failing but different error now.

**Comment by epitavy** [comment]
Right, I missed an error because I didn't build with debug enabled, so assertions were removed. It's fixed now.

**Comment by epitavy** [comment]
ping @kamleshbhalui

**Comment by epitavy** [comment]
@lhames

**Comment by lhames** [comment]
@epitavy Sorry I didn't get to this earlier -- I've been busy with a relocation. @kamleshbhalui -- thanks very much for landing!

**Comment by kamleshbhalui** [comment]
@epitavy Please have a look at it again

**Comment by epitavy** [comment]
It is still not building correctly ?

**Comment by kamleshbhalui** [comment]
Correct, test by executing the `ExceptionDemo` once build succeed.

**Comment by epitavy** [comment]
It works as expected for me, except that some values are wrong.
```
Gen: About to throw exception type <2> in throwFunct.
Gen: Exception type <96> received (stack unwound)  in innerCatchFunct.
                    ^^^^
```
96 should be 2, but the bug was already here, and I don't know how to fix that

**Comment by kamleshbhalui** [comment]
I have reverted for now, and reopened the issue.

**Comment by epitavy** [comment]
You expect someone to fix the bug on this pull request ?

**Comment by epitavy** [comment]
I think I fixed the bug, where should I push the patch ?

**Comment by kamleshbhalui** [comment]
Can you share entire execution log here?

**Comment by kamleshbhalui** [comment]
I think you have to create new PR, you can mention this PR there.

**Comment by epitavy** [comment]
> Can you share entire execution log of `ExceptionDemo` here?

I share the log on the new PR

**Pull request merged**
