### PR TITLE
Add exception guard for constructor vector(n, x, a)

### PR DESCRIPTION
**Pull request by winner245**
Added exception guard to the `vector(n, x, a)` constructor to enhance exception safety. This change ensures that the `vector(n, x, a)` constructor is consistent with other constructors, such as  `vector(n)`, `vector(n, x)`, `vector(n, a)`, in terms of exception safety.

### CODE REVIEW

**Review by frederick-vs-ja — COMMENTED** [review]
I think I've found the memory leaking case that can be fixed by this PR ([Godbolt link](https://godbolt.org/z/dWeqsGM7n)).

Could you add a new `.pass.cpp` to `libcxx/test/libcxx/containers/sequences/vector/vector.cons` which asserts that memory leak doesn't raise from this constructor when an exception is thrown?

**Comment by frederick-vs-ja** [comment]
Looks like a missing piece of 8ff4d218a80b887bb645ec426aefa1ab7144c5f3 (https://reviews.llvm.org/D138601). CC @philnik777.

**Comment by winner245** [comment]
@frederick-vs-ja Thank you for your guidance and for providing the memory leak test case. I will include the test in a .pass.cpp file and make sure my change passes the test. Also, I really appreciate you pointing out that my PR is related to 8ff4d21 by @philnik777. I will definitely look into that as well.

Best regards, 
Peng

**Comment by winner245** [comment]
Hi team,

Following @frederick-vs-ja's suggestion and reviewing the prior work by @philnik777, I have included an additional exception test in the existing file libcxx/test/std/containers/sequences/vector/vector.cons/exceptions.pass.cpp. This new test checks for memory leaks in scenarios where vector(size_type, value_type, const allocator_type&) might throw, ensuring no memory is leaked in such cases. I have compiled the entire project and run the new test to confirm that this change does not introduce new problems. 

Thank you, @frederick-vs-ja, for your valuable suggestion!

**Review by ldionne — APPROVED** [review]
LGTM, thanks for the fix. Can you please rebase your patch onto `main`? That will fix the CI issues, which have been fixed on the latest `main`.

**Review by ldionne — APPROVED** [review]
LGTM once CI is green. Thanks!

**Review by frederick-vs-ja — APPROVED** [review]

**Comment by winner245** [comment]
Thank you @ldionne so much for your prompt fix. The failing checks are now passing. Once again, I would like to thank you both, @frederick-vs-ja and @ldionne, for your patience and guidance. I am so proud to have the opportunity to work with you.

**Comment by winner245** [comment]
Hi team, I have resolved the conflicts due to the split of `libcxx/include/vector` into 2 separate files `vector.h` and `vector_bool.h`. This PR is now ready to merge. Could someone with merge permissions please help me merge it into the main branch? Thanks in advance. Cheers,

**Review by frederick-vs-ja — APPROVED** [review]
I'm merging this, hoping everything is OK.

**Pull request merged**
