### PR TITLE
[DebugInfo] Clone dbg.values in SimplifyCFG like normal instructions

### PR DESCRIPTION
**Pull request by jmorse**
The code in the CloneInstructionsIntoPredec... function modified by this patch has a long history that dates back to 2011, see d715ec82b4ad12c59. There, when folding branches, all dbg.value intrinsics seen when folding would be saved and then re-inserted at the end of whatever was folded. Over the last 12 years this behaviour has been preserved.

However, IMO it's bad behaviour. If we have:

    inst1
    dbg.value1
    inst2
    dbg.value2

And we fold that sequence into a different block, then we would want the instructions and variable assignments to appear in the same order. However because of this old behaviour, the dbg.values are sunk, and we get:

    inst1
    inst2
    dbg.value1
    dbg.value2

This clustering of dbg.values can make assignments to the same variable invisible, as well as reducing the coverage of other assignments.

This patch relaxes the CloneInstructions... function and allows it to clone and update dbg.values in-place, causing them to appear in the original order in the destination block. I've added some extra dbg.values to the updated test: without the changes to the pass, the dbg.values sink into a blob ahead of the select.

(Metadata changes to make the LLVM-IR parser not drop the debug-info for it being out of date. The RemoveDIs related RUN line has been removed because it was spuriously passing due to the debug-info being dropped).

~

This has come up as part of the RemoveDIs stuff because it's a weird behaviour that requires explicit instrumentation. IMO it doesn't need to be so abnormal, the dbg.values can be treated like normal instructions. And that makes it easier to move from one representation to the other, as all the utilities we've written are geared towards updating things like they're dbg.values.

### CODE REVIEW

**Review by OCHyams — COMMENTED** [review]
It's good to be removing weird behaviour. Hurray!

It looks like in `llvm/test/Transforms/SimplifyCFG/branch-fold-dbg.ll` some conditional assignments become unconditional, which seems bad/undesirable. But the existing behaviour of pushing the dbg.values to the end of the block doesn't solve that, so we might as well preserve the order (as you're doing here). Does that line up with your thoughts on this?

I wonder if there are compile time implications - I assume previously lots of block folding would result in a lot of redundant dbg.values (because of how they get clumped without this patch) which would result in many getting removed in cleanup passes. That might've artificially been improving performance over the baseline correct behaviour. Not much we can do about it I guess.

**Comment by jmorse** [comment]
/me squints -- right you are, I hadn't spotted that those dbg.values should actually be dropped. I think this change doesn't make anything worse seeing how all the source-locations are dropped too, and it removes a special-debug-juggling location, which is desirable for RemoveDIs. Pushed up to the compile-time-tracker for testing, just in case.

This is actually something moderately important we're going to have to track -- it exposes one of our favourite pieces of IR, "what happens when we merge a PHI-value variable to be calculated by a select in a single block".

**Review by OCHyams — APPROVED** [review]
👍 LGTM pending compile time tracker results - as discussed, this is an improvement, even if the end result isn't perfect.

**Comment by jmorse** [comment]
http://llvm-compile-time-tracker.com/compare.php?from=10a9e7442c4c4e09ee94f6e1d67e2ba7396bf7cb&to=a92ac19df39537c22860e6085a6902d16e5ffde2&stat=instructions%3Au indicates we're fine.

**Comment by jmorse** [comment]
Landed in 84f6e1d71c19bccd -- I removed the "--try..." RUN line from the modified test, which had been added in the meantime. Seeing how the debug-info in the test was broken and being dropped, right up to the point where 84f6e1d71c19bccd landed, it wasn't actually covering anything.

RemoveDIs coverage for that test will be restored in #72546

**Pull request closed without merging**
