### PR TITLE
AMDGPU: Match and Select BITOP3 on gfx950

### PR DESCRIPTION
**Pull request by arsenm**
Co-authored-by: Stanislav Mekhanoshin <Stanislav.Mekhanoshin@amd.com>

### CODE REVIEW

**Comment by arsenm** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117843?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#117843** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117843?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈 <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117843?utm_source=stack-comment-view-in-graphite" target="_blank">(View in Graphite)</a>
* **#117827** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117827?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117826** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117826?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117825** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117825?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117824** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117824?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117823** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117823?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117822** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117822?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117821** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117821?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117820** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117820?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117798** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117798?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117797** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117797?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117796** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117796?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117795** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117795?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117794** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117794?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117793** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117793?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117747** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117747?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117745** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117745?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117744** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117744?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117743** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117743?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117742** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117742?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117741** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117741?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117740** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117740?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117739** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117739?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117738** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117738?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117737** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117737?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117634** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117634?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117601** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117601?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117600** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117600?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117599** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117599?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117598** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117598?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117597** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117597?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117596** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117596?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117595** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117595?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117594** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117594?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117593** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117593?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117592** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117592?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117591** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117591?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117590** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117590?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117418** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117418?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117417** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117417?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117384** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117384?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117383** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117383?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117382** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117382?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117381** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117381?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117380** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117380?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117379** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117379?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117378** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117378?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117287** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117287?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117286** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117286?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117285** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117285?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117284** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117284?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117283** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117283?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117263** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117263?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117262** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117262?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117261** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117261?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117260** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117260?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117259** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117259?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117258** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117258?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117257** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117257?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117256** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117256?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117235** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117235?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117234** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117234?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117233** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117233?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117232** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117232?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117214** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117214?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117213** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117213?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117212** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117212?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117211** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117211?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117205** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117205?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117202** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117202?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117055** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117055?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117053** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117053?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#117052** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117052?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116728** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/116728?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116724** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/116724?utm_source=stack-comment-icon" target="_blank">Graphite</a>: 1 other dependent PR ([#117047](https://github.com/llvm/llvm-project/pull/117047) <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/117047?utm_source=stack-comment-icon" target="_blank">Graphite</a>)
* **#116723** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/116723?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116722** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/116722?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116681** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/116681?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116680** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/116680?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116679** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/116679?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116678** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/116678?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116312** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/116312?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116311** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/116311?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116310** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/116310?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116309** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/116309?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116308** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/116308?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#116307** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/116307?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

<h2></h2>

This stack of pull requests is managed by <a href="https://graphite.dev?utm-source=stack-comment"><b>Graphite</b></a>. Learn more about <a href="https://stacking.dev/?utm_source=stack-comment">stacking</a>.

**Review by shiltian — APPROVED** [review]

**Comment by arsenm** [comment]
### Merge activity

* **Nov 27, 1:23 AM EST**: A user started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/117843).

**Comment by vvereschaka** [comment]
Hi @arsenm ,

here is a problem with `bitop3.ll` test of the expensive test builders
* https://lab.llvm.org/buildbot/#/builders/187/builds/2801
```
*** Bad machine code: illegal copy from vector register to SGPR ***
- function:    uniform_4_op
- basic block: %bb.0  (0x55cc20ecdc48)
- instruction: %7:sreg_32 = COPY killed %10:vgpr_32
LLVM ERROR: Found 1 machine code errors.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.	Program arguments: /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/build/bin/llc -global-isel -march=amdgcn -mcpu=gfx950
1.	Running pass 'CallGraph Pass Manager' on module '<stdin>'.
2.	Running pass 'Verify generated machine code' on function '@uniform_4_op'
 #0 0x000055cbf4868a0c llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/Support/Unix/Signals.inc:723:22
 #1 0x000055cbf4868e2d PrintStackTraceSignalHandler(void*) /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/Support/Unix/Signals.inc:798:1
 #2 0x000055cbf486627d llvm::sys::RunSignalHandlers() /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/Support/Signals.cpp:105:20
 #3 0x000055cbf48682a4 SignalHandler(int) /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/Support/Unix/Signals.inc:413:1
 #4 0x00007f13cdde4520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #5 0x00007f13cde389fc pthread_kill (/lib/x86_64-linux-gnu/libc.so.6+0x969fc)
 #6 0x00007f13cdde4476 gsignal (/lib/x86_64-linux-gnu/libc.so.6+0x42476)
 #7 0x00007f13cddca7f3 abort (/lib/x86_64-linux-gnu/libc.so.6+0x287f3)
 #8 0x000055cbf478d463 llvm::report_fatal_error(llvm::Twine const&, bool) /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/Support/ErrorHandling.cpp:126:9
 #9 0x000055cbf32af872 (anonymous namespace)::MachineVerifier::ReportedErrors::~ReportedErrors() /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/CodeGen/MachineVerifier.cpp:262:33
#10 0x000055cbf32afa0c (anonymous namespace)::MachineVerifier::~MachineVerifier() /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/CodeGen/MachineVerifier.cpp:102:8
#11 0x000055cbf32afb57 (anonymous namespace)::MachineVerifierLegacyPass::runOnMachineFunction(llvm::MachineFunction&) /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/CodeGen/MachineVerifier.cpp:389:12
#12 0x000055cbf3129b05 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/CodeGen/MachineFunctionPass.cpp:94:33
#13 0x000055cbf3a0d420 llvm::FPPassManager::runOnFunction(llvm::Function&) /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1406:20
#14 0x000055cbf2811d07 (anonymous namespace)::CGPassManager::RunPassOnSCC(llvm::Pass*, llvm::CallGraphSCC&, llvm::CallGraph&, bool&, bool&) /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/Analysis/CallGraphSCCPass.cpp:180:17
#15 0x000055cbf2812df1 (anonymous namespace)::CGPassManager::RunAllPassesOnSCC(llvm::CallGraphSCC&, llvm::CallGraph&, bool&) /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/Analysis/CallGraphSCCPass.cpp:469:21
#16 0x000055cbf2813248 (anonymous namespace)::CGPassManager::runOnModule(llvm::Module&) /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/Analysis/CallGraphSCCPass.cpp:534:15
#17 0x000055cbf3a0dc51 (anonymous namespace)::MPPassManager::runOnModule(llvm::Module&) /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1521:20
#18 0x000055cbf3a08b11 llvm::legacy::PassManagerImpl::run(llvm::Module&) /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:539:13
#19 0x000055cbf3a0e59b llvm::legacy::PassManager::run(llvm::Module&) /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/lib/IR/LegacyPassManager.cpp:1649:1
#20 0x000055cbef89b0ef compileModule(char**, llvm::LLVMContext&) /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/tools/llc/llc.cpp:753:34
#21 0x000055cbef8988c3 main /home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/tools/llc/llc.cpp:411:35
#22 0x00007f13cddcbd90 (/lib/x86_64-linux-gnu/libc.so.6+0x29d90)
#23 0x00007f13cddcbe40 __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x29e40)
#24 0x000055cbef897465 _start (/home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/build/bin/llc+0xd1d465)
/home/buildbot/worker/as-builder-4/ramdisk/expensive-checks/llvm-project/llvm/test/CodeGen/AMDGPU/bitop3.ll:263:14: error: GCN-LABEL: expected string not found in input
; GCN-LABEL: uniform_4_op:
```

**Comment by arsenm** [comment]
> Hi @arsenm ,
> 
> here is a problem with `bitop3.ll` test of the expensive test builders
> 
> * https://lab.llvm.org/buildbot/#/builders/187/builds/2801

Fixed by #117940

**Comment by RKSimon** [comment]
@arsenm There's still issues with bitop3.ll on expensive checks builds - please can you take another look?

**Comment by vvereschaka** [comment]
@arsenm the problem is not fixed for 4 days already. Please revert your changes or fix this problem as soon as possible.

**Pull request merged**
