### PR TITLE
[ARM] Regenerate MIR checks.

### PR DESCRIPTION
**Pull request by fhahn**
Regenerate the check lines for some MIR tests as it looks like the auto-generate checks have been improved since the checks in the tests have been generated.

### CODE REVIEW

**Comment by davemgreen** [comment]
Should the [MTE] here refer to MVE? Or does it mean something else? Maybe just use [ARM]?

Updating the tests sounds OK if you still need this.

**Review by davemgreen — APPROVED** [review]
Thanks

**Comment by fhahn** [comment]
This isn't needed any more, @davemgreen do you prefer me to land this anyways or just drop it?

**Comment by fhahn** [comment]
I'll abandon this one for now

**Pull request closed without merging**
