### PR TITLE
Testing32 bit for https://github.com/llvm/llvm-project/pull/92083

### PR DESCRIPTION
**Pull request by ChuanqiXu9**
https://github.com/llvm/llvm-project/pull/92083 is failed on 32bit machine but it is not easy to get a 32 bit machine.

And thanks for @DavidSpickett would love to test this.

I tried to review the code and I tried to find the position. But I can't test it to make sure if can avoid the regression.

This is only a draft to locate the problems. I will refine it if we can make sure where the problem is.

### CODE REVIEW

**Comment by DavidSpickett** [comment]
I tested locally and this fixes all the test failures.

**Comment by ChuanqiXu9** [comment]
Thanks!

**Comment by ChuanqiXu9** [comment]
@DavidSpickett oh, sorry. I didn't expect the refined patch will break 32 bit again. Can you try the new patch?

**Comment by DavidSpickett** [comment]
Sure I'll test it now.

BTW if you see `Clang-Unit::ClangReplInterpreterTests/InterpreterTest/Value` failing on one of our bots, that's not due to your change.

**Comment by DavidSpickett** [comment]
Ok, this new version passes `check-llvm` and `check-clang` (ignoring the pre-existing failure), using the exact config from [clang-armv8-quick](https://lab.llvm.org/buildbot/#/builders/245).

**Comment by ChuanqiXu9** [comment]
Thank you very much!

**Comment by DavidSpickett** [comment]
Looks like this fixed things: https://lab.llvm.org/buildbot/#/builders/245/builds/25578

Thanks for working with me on this.

**Pull request closed without merging**
