### PR TITLE
Fix LLVM_ENABLE_ABI_BREAKING_CHECKS macro check: use #if instead of #ifdef

### PR DESCRIPTION
**Pull request by joker-eph**
This macros is always defined: either 0 or 1. The correct pattern is to use #if.

### CODE REVIEW

**Review by dwblaikie — APPROVED** [review]
SGTM - this'll be an ABI break, of course - but we don't have an ABI stability between releases, so I don't think this would adversely affect anyone. We just have to be consistent within a release or version, and we were consistent (though inefficient) before this patch and we'll be consistent (though more efficient/lower memory usage, etc) afterwards.

**Comment by joker-eph** [comment]
Sure, happy to revert of course! 
But we need a repro because I want to re-land, can you provide a config I can build upstream that will reproduce the issues? Thanks!

**Comment by joker-eph** [comment]
I think I can reproduce with a release build and ` -DLLVM_ABI_BREAKING_CHECKS=FORCE_ON`.

Note that this is a bit of a weird config, you may want to check your downstream settings.

**Comment by ScottTodd** [comment]
We do jump through some hoops with asserts and NDEBUG downstream, yeah: https://github.com/iree-org/iree/blob/ff1b8b0e433372b73ad6abcaa101ae0dc2fd639d/CMakeLists.txt#L477-L522. I'm seeing if I can find better upstream repro steps...

**Comment by ScottTodd** [comment]
For reference: https://llvm.org/docs/CMake.html#llvm-related-variables

> **LLVM_ABI_BREAKING_CHECKS**:STRING
  Used to decide if LLVM should be built with ABI breaking checks or
  not.  Allowed values are `WITH_ASSERTS` (default), `FORCE_ON` and
  `FORCE_OFF`.  `WITH_ASSERTS` turns on ABI breaking checks in an
  assertion enabled build.  `FORCE_ON` (`FORCE_OFF`) turns them on
  (off) irrespective of whether normal (`NDEBUG`-based) assertions are
  enabled or not.  A version of LLVM built with ABI breaking checks
  is not ABI compatible with a version built without it.

**Comment by joker-eph** [comment]
I don't think I need more repro steps, but you likely wanna check what your custom cmake ends up with LLVM inferring LLVM_ABI_BREAKING_CHECKS to be on?

**Comment by joker-eph** [comment]
Relanded in [1905cdb](https://github.com/llvm/llvm-project/commit/1905cdbf4ef15565504036c52725cb0622ee64ef)

**Comment by DimitryAndric** [comment]
After 1905cdbf4ef15565504036c52725cb0622ee64ef, I'm running into segfaults when assertions are disabled (`NDEBUG` is defined) and `LLVM_ENABLE_ABI_BREAKING_CHECKS=1`. The problem is that `llvm/lib/CodeGen/SelectionDAG/SelectionDAGISel.cpp` has in `SelectionDAGISel::initializeAnalysisResults`:

```c++
#if !defined(NDEBUG) && LLVM_ENABLE_ABI_BREAKING_CHECKS
  TTI = &FAM.getResult<TargetIRAnalysis>(Fn);
#endif
```

but all the calls to `VerifyDAGDivergence` in `SelectionDAGISel::CodeGenAndEmitDAG` are first checked by accessing `TTI`:

```c++
#if LLVM_ENABLE_ABI_BREAKING_CHECKS
  if (TTI->hasBranchDivergence())
    CurDAG->VerifyDAGDivergence();
#endif
```

Since `TTI` is initialized with `nullptr` in the `SelectionDAGISel` class declaration, this access segfaults.

**Comment by joker-eph** [comment]
> when assertions are disabled (NDEBUG is defined) and LLVM_ENABLE_ABI_BREAKING_CHECKS=1

This seems like a weird configuration to me (if I understand correctly): what is the motivation to build LLVM with this way?


Feel free to make the code consistent though, it won't hurt.

**Comment by DimitryAndric** [comment]
There is no particular reason, except that this is the configuration you get when building FreeBSD with `WITHOUT_LLVM_ASSERTIONS` enabled. We are using a few pre-generated header files, which set `LLVM_ENABLE_ABI_BREAKING_CHECKS=1`, but I was not aware that this define is coupled to `NDEBUG`. If that is the case, there should really only be checks for `LLVM_ENABLE_ABI_BREAKING_CHECKS`?

**Comment by DimitryAndric** [comment]
So in `llvm/cmake/modules/HandleLLVMOptions.cmake` there is this fragment:

```cmake
if( uppercase_LLVM_ABI_BREAKING_CHECKS STREQUAL "WITH_ASSERTS" )
  if( LLVM_ENABLE_ASSERTIONS )
    set( LLVM_ENABLE_ABI_BREAKING_CHECKS 1 )
  endif()
elseif( uppercase_LLVM_ABI_BREAKING_CHECKS STREQUAL "FORCE_ON" )
  set( LLVM_ENABLE_ABI_BREAKING_CHECKS 1 )
elseif( uppercase_LLVM_ABI_BREAKING_CHECKS STREQUAL "FORCE_OFF" )
  # We don't need to do anything special to turn off ABI breaking checks.
elseif( NOT DEFINED LLVM_ABI_BREAKING_CHECKS )
  # Treat LLVM_ABI_BREAKING_CHECKS like "FORCE_OFF" when it has not been
  # defined.
else()
  message(FATAL_ERROR "Unknown value for LLVM_ABI_BREAKING_CHECKS: \"${LLVM_ABI_BREAKING_CHECKS}\"!")
endif()
```

I thought we could maybe remove _all_ `NDEBUG` checks when used in combination with `LLVM_ENABLE_ABI_BREAKING_CHECKS`, but apparently you can "force on" `LLVM_ENABLE_ABI_BREAKING_CHECKS` even when `LLVM_ENABLE_ASSERTIONS` is off.

So for some reason, this is still a valid combination, although it does not really make sense to me. :)

**Comment by joker-eph** [comment]
Yes this is a valid combination, I just don't understand why anyone would want it in practice. It's been a while, but from memory I see the ABI_BREAKING_CHECKS as checks that are extras on top of the assertions.

**Comment by DimitryAndric** [comment]
Yeah, but that is a fix for another day. For now I have submitted #113588.

**Comment by joker-eph** [comment]
What « fix » do you refer to for another day?

**Comment by DimitryAndric** [comment]
> What « fix » do you refer to for another day?

Sorry, I meant that if the combination of NDEBUG and LLVM_ENABLE_ABI_BREAKING_CHECKS does not make sense, we could adjust the CMake files for that, and get rid of the FORCE_ON and FORCE_OFF settings, only ever enabling LLVM_ENABLE_ABI_BREAKING_CHECKS if NDEBUG is not enabled. Then you could get rid of the NDEBUG checks here.

**Pull request merged**
