### PR TITLE
[mlir][OpenMP] Added omp.region operation

### PR DESCRIPTION
**Pull request by shraiysh**
This patch adds omp.region operation. This is equivalent to a code block surrounded by an OpenMP construct in C/C++/Fortran. This is a part of the effort to implement the canonical loop operation in OpenMP dialect.

### CODE REVIEW

**Comment by kiranchandramohan** [comment]
Please add a quick RFC in the mlir discourse channel.

Would it make sense to call it an internal region? Or specialize it further and call it canonical_loop_region?

**Comment by shraiysh** [comment]
`internal_region` sounds good. I did not want to make it highly specific, because it could be used under other constructs too. Like, `omp.sections` could have an internal region and a barrier in the future. We do not need it for others at the moment, but not making it highly special leaves room for other constructs to use it.

I will create an RFC.

**Comment by kiranchandramohan** [comment]
Can this have `omp.yield` as the terminator and be capable of yielding/returning values?

**Comment by shraiysh** [comment]
Sure I'll do that.

**Pull request merged**
