### PR TITLE
[clang][Driver] Add support for XROS_DEPLOYMENT_TARGET env var

### PR DESCRIPTION
**Pull request by cyndyishida**

### CODE REVIEW

**Comment by ributzka** [comment]
Why didn't this trigger: https://github.com/llvm/llvm-project/blob/ab92f6274b7c3a4b4445d47017bc481aa919545f/clang/lib/Driver/ToolChains/Darwin.cpp#L1906 ?

**Comment by ributzka** [comment]
> Why didn't this trigger:
> 
> https://github.com/llvm/llvm-project/blob/ab92f6274b7c3a4b4445d47017bc481aa919545f/clang/lib/Driver/ToolChains/Darwin.cpp#L1906
> 
> ?

XROS is missing in the env vars too: https://github.com/llvm/llvm-project/blob/ab92f6274b7c3a4b4445d47017bc481aa919545f/clang/lib/Driver/ToolChains/Darwin.cpp#L1899

**Comment by cyndyishida** [comment]
> > Why didn't this trigger:
> > https://github.com/llvm/llvm-project/blob/ab92f6274b7c3a4b4445d47017bc481aa919545f/clang/lib/Driver/ToolChains/Darwin.cpp#L1906
> > 
> > ?
> 
> XROS is missing in the env vars too:
> 
> https://github.com/llvm/llvm-project/blob/ab92f6274b7c3a4b4445d47017bc481aa919545f/clang/lib/Driver/ToolChains/Darwin.cpp#L1899

Yes. Adding proper `XROS_DEPLOYMENT_TARGET` support is a bigger patch, I'll need to update this PR to reflect this.

**Comment by cyndyishida** [comment]
ping

**Review by ributzka — APPROVED** [review]
LGTM

**Pull request merged**
