### PR TITLE
[AArch64] Update the scheduling model for Cortex-X1/2/3/4

### PR DESCRIPTION
**Pull request by davemgreen**
These Neoverse-V scheduling models more closely match the Cortex-X series cpus with 4 vector pipelines, even if they do not match exactly.

### CODE REVIEW

**Review by jthackray — APPROVED** [review]
LGTM, nice. How much extra performance (roughly) does this provide?

**Review by c-rhodes — APPROVED** [review]
LGTM cheers

**Review by Asher8118 — APPROVED** [review]
LGTM, makes sense, thanks.

**Comment by davemgreen** [comment]
Thanks

> LGTM, nice. How much extra performance (roughly) does this provide?

Scheduling on OoO machines doesn't usually give a lot of performance, when taken as an aggregate. The OoO machines can do a lot of scheduling themselves so long as we get it close enough, and my tests it was not very much. This is closer in terms of the correct number of pipelines though, which would help if we start to use them more.

**Pull request merged**
