### PR TITLE
[coroutines][CoroSplit] Store allocas on the frame if there is no explicit lifetime.end

### LINKED ISSUE #86580: [coroutines] LLVM incorrectly allocates variables on the coroutine stack
Example:

```cpp
struct StubbyMessageBuffer {
  StubbyMessageBuffer();
  ~StubbyMessageBuffer();
};

// Reduced version of absl::cleanup
class Cleanup  {
 public:
  Cleanup(void (*cleanup)()) : cleanup_(cleanup){}

  ~Cleanup() {
    cleanup_();
  }

 private:
  // Strangely enough this doesn't work if cleanup_ is a std::function
  void (*cleanup_)();
};

MyTask FooBar() {
  StubbyMessageBuffer smb;
  #ifdef DO_CLEANUP
  // This is produced by a LOG(FATAL) or a LOG(QFATAL)
  Cleanup cu([]{abort();});
  #endif
  co_await 1;
  co_return;
}
```

When compiled with `-O1` and `DO_CLEANUP` undefined, `smb` is constructed and stored in the coroutine frame:

```llvm
define internal fastcc void @FooBar() [clone .resume](ptr noundef nonnull align 8 dereferenceable(32) %0) {
entry.resume:
  %ref.tmp3.reload.addr = getelementptr inbounds i8, ptr %0, i64 24
  %smb.reload.addr = getelementptr inbounds i8, ptr %0, i64 18
```

However, if `DO_CLEANUP` *is* defined, `smb` is no longer stored on the frame; instead, it is constructed and allocated in the coroutine resume function:

```llvm
define internal fastcc void @FooBar() [clone .resume](ptr noundef nonnull align 8 dereferenceable(32) %0) {
entry.resume:
  %smb = alloca %struct.StubbyMessageBuffer, align 1
```

This behavior is wrong; the constructor for `StubbyMessageBuffer` may have side effects, and if `FooBar()` calls a function that takes a reference / pointer to `smb`, `smb` still does not get created on the coroutine frame object, and we get a segfault.

godbolt: https://godbolt.org/z/oMfKqExMK

### PR DESCRIPTION
**Pull request by alanzhao1**
Certain passes such as SimplifyCFG may remove existing lifetime.end intrinsics on presplit coroutines. CoroSplitPass then incorrectly assumes that these allocas may not persist across the coroutine suspension point. To fix this, computeShouldLiveOnFrame() now saves allocas on the coroutine frame object if their addresses are escaped and those allocas don't have a corresponding lifetime.end.

Fixes https://github.com/llvm/llvm-project/issues/86580

### CODE REVIEW

**Review by ChuanqiXu9 — COMMENTED** [review]
Thanks for the analysis, it is pretty helpful.

From the analysis, I feel there is deep problems in the current model since it shows the lifetime intrinsics is not so stable as we thought. e.g., if there are multiple llvm.lifetime.start and llvm.lifetime.end intrinsics but some passes only remove some of the `llvm.lifetime.end` intrinsics (not all), I fear it may still be problematic.

The root problem here is that, when we use lifetime info to decide if an alloca should live on the frame, we don't consider lifetime end at all. This is not correct. To fix this fundamentally, I think we need to introduce some data flow analysis here. The logic may be:
1. If there is any path from any llvm.lifetime.start to the llvm.coro.end  without touching llvm.lifetime.end, we need to put the variable on the frame.
2. If there is any path from any llvm.lifetime.start to the llvm.lifetime.end touched llvm.coro.suspend, we need to put the variable on the frame.
3. Then it may be safe to put the variable on the stack.

I am not sure if there is existing logic for this. If not, probably we need to do it ourselves. We already did some of such local data flow analysis in coroutines.

**Comment by efriedma-quic** [comment]
Also:

- If there's a lifetime.start, and it flows to a ret/unreachable/resume, treat it as if there's a lifetime.end just before that.

------


llvm/lib/CodeGen/StackColoring.cpp implements this analysis, but not in a way you can easily reuse.  Still probably a useful reference.

(Lifetime intrinstics are inherently pretty messy; see also #45725.)

**Comment by zmodem** [comment]
Is someone looking at doing the deeper fix to the lifetime analysis as suggested above, or should we do a stop gap fix in the meantime?

I'm not sure if the current patch is sufficient: it checks whether there is *a* lifetime.end intrinsic, but what if there is one on one execution path, but not another? Maybe we should always set ShouldUseLifetimeStartInfo to avoid this miscompile for now?

**Comment by ChuanqiXu9** [comment]
> Is someone looking at doing the deeper fix to the lifetime analysis as suggested above, or should we do a stop gap fix in the meantime?

I have less time developing into coroutines in detail recently. So if there is no one had the chance to fix this properly in the near future, I think we can accept this as a partial workaround.

> I'm not sure if the current patch is sufficient: it checks whether there is a lifetime.end intrinsic, but what if there is one on one execution path, but not another? 

Yeah, this is the reason why I think the current patch is a partial fix.

> Maybe we should always set ShouldUseLifetimeStartInfo to avoid this miscompile for now?

I am not sure what you mean. `ShouldUseLifetimeStartInfo` is always set for C++.

**Comment by alanzhao1** [comment]
> > Is someone looking at doing the deeper fix to the lifetime analysis as suggested above, or should we do a stop gap fix in the meantime?
> 
> I have less time developing into coroutines in detail recently. So if there is no one had the chance to fix this properly in the near future, I think we can accept this as a partial workaround.
> 
> > I'm not sure if the current patch is sufficient: it checks whether there is a lifetime.end intrinsic, but what if there is one on one execution path, but not another?
> 
> Yeah, this is the reason why I think the current patch is a partial fix.
 
Agreed that this is a partial fix - it doesn't address the example that @zmodem mentioned, plus there could be other scenarios that we didn't think of. A complete fix would probably require an RFC on Discourse due to its complexity (llvm lifetimes intrinsics are notoriously fickle per https://github.com/llvm/llvm-project/pull/88806#issuecomment-2058249478, and we'd likely have to rewrite most of the existing logic here.)

> > Maybe we should always set ShouldUseLifetimeStartInfo to avoid this miscompile for now?
> 
> I am not sure what you mean. `ShouldUseLifetimeStartInfo` is always set for C++.

I think the proposal is that we put all coroutine variables on the coroutine frame object rather than try to figure out what variables can go on the stack. This would generate suboptimal code, but it will be guaranteed to be correct.

**Comment by ChuanqiXu9** [comment]
> I think the proposal is that we put all coroutine variables on the coroutine frame object rather than try to figure out what variables can go on the stack. This would generate suboptimal code, but it will be guaranteed to be correct.

Oh, it means to set `ShouldUseLifetimeStartInfo` to false. This change may have a large impact. Coroutines nowadays are used in many performance critical sections... we also need a RFC and call users to test the performance changes to do this...

Maybe we should try to look at how to fix it properly...

**Comment by zmodem** [comment]
> Oh, it means to set `ShouldUseLifetimeStartInfo` to false.

Yes, sorry, I forgot to write the "to false" part.

> Coroutines nowadays are used in many performance critical sections

That makes it all the more important to ensure we don't miscompile the code ;)

> Maybe we should try to look at how to fix it properly...

Agreed :)

**Comment by apolloww** [comment]
> This change may have a large impact. Coroutines nowadays are used in many performance critical sections... we also need a RFC and call users to test the performance changes to do this...

I think it would mostly just increase memory pressure, but not so much on runtime performance unless such case happens frequently enough to bloat up the heap size to certain point that allocation performance starts to dip.

**Comment by alanzhao1** [comment]
I started a discourse thread at https://discourse.llvm.org/t/coro-using-lifetime-markers-to-allocate-values-on-the-stack-vs-the-frame/78451

**Comment by alanzhao1** [comment]
Closing in favor of https://github.com/llvm/llvm-project/pull/90265

**Pull request closed without merging**
