### PR TITLE
[OpenMP][USM] Adds test for -fopenmp-force-usm flag

### PR DESCRIPTION
**Pull request by jplehr**
This adds a basic test to check the correct generation of double indirect access to declare target globals in USM mode vs non-USM mode.
I am a bit unhappy with the way this test is set up, but could not find a better way to do it. Happy to improve that and add more tests then.

Marked as XFAIL to first land test and then enable in subsequent patch.

### CODE REVIEW

**Review by ronlieb — APPROVED** [review]

**Comment by jplehr** [comment]
I updated the feature PR (#75468) with a different solution. Will update the test after feedback if the route I took in the other PR is seen as OK.

**Comment by jdoerfert** [comment]
How do the IR checks verify the flag works?

**Comment by jhuber6** [comment]
Test should probably show that IR is equivalent to `#pragma omp requires unified_shared_memory` or however that's spelled. Basic documentation should be provided by the help test in the new flag, but we probably have somewhere in the OpenMP docs you could add it to if desired.

**Comment by jdoerfert** [comment]
I mean, the test shows device IR for two functions, doesn't it? I am not aware that part is impacted by USM. Host globals/register functions are.

**Comment by jplehr** [comment]
The IR is impacted for the global that is in that test case. Lines ~46-50 (first IR section) vs line ~68 (second IR section). The remaining code is indeed the same.
The way that this test is executed is out of date however, given that I have reimplemented the flag.
My plan is to keep this test and add a few runtime tests as well, since we should be able to validate that we do not see data transfers.

**Comment by jdoerfert** [comment]
I see. FWIW "pGI_decl_tgt_ref_ptr" is really not a good name (not your fault).

**Review by jdoerfert — APPROVED** [review]

**Comment by jplehr** [comment]
Closing this. Test is now part of feature-PR.

**Pull request closed without merging**
