### PR TITLE
Add `visitGEPOfAlloc` to restore the `visitGEPOfBitcast` part of the behavior of non-opaque pointers.

### LINKED ISSUE #65763: LoopFullUnrollPass failed due to constant inference in opaque pointer mode.
I tried to disable the opaque pointer in https://github.com/rust-lang/rust/issues/115339 to get the SLPVectorizer optimization.
See https://godbolt.org/z/GqdPGarsn.

According to my investigation, the success of optimization in non-opaque pointer mode relates to [SROA.cpp#L1831-L1845](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.6/llvm/lib/Transforms/Scalar/SROA.cpp#L1831-L1845)  or [InstructionCombining.cpp#L2220-L2274](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.6/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp#L2220-L2274). Unfortunately, these two transformations have been removed during opaque pointer migration.

My plan is to restore the behavior of [InstructionCombining.cpp#L2220-L2274](https://github.com/llvm/llvm-project/blob/llvmorg-16.0.6/llvm/lib/Transforms/InstCombine/InstructionCombining.cpp#L2220-L2274) using `alloc` instead of `bitcast`.
Looking at the code comments, this seems to be an important optimization. So it might be worth backporting to LLVM 17?

### PR DESCRIPTION
**Pull request by dianqk**
Closes #65763.

### CODE REVIEW

**Review by nikic — CHANGES_REQUESTED** [review]
We definitely shouldn't do this. From the issue, it's not clear where the problem actually is (given lack of reproducer), but I expect that this needs to be solved by teaching some transform to use offset-based reasoning for GEPs (or alternatively, by canonicalizing to i8 GEPs).

**Comment by DianQK** [comment]
> We definitely shouldn't do this. From the issue, it's not clear where the problem actually is (given lack of reproducer), but I expect that this needs to be solved by teaching some transform to use offset-based reasoning for GEPs (or alternatively, by canonicalizing to i8 GEPs).

Thanks for the reply. I feel like I understand the issue a little better.
I found out earlier that SROA was not canonicalizing all the GEPs to i8 GEPs due to the escaped scene.
Since non-opaque pointers are OK, I incorrectly guessed it was a regression issue. So I didn't look at that part in depth.

I tried a lot of reproducers using llvm-reduce. An LLVM any-version reproducer may not exist. Just lucky in the case of non-opaque pointers.
I can execute inline before any pass. This is a reproducer of LLVM 16 not being able to optimize successfully in either mode.

Do you think bringing ahead GVN to LoopFullUnroll is the right choice? This should provide more optimization opportunities for LoopFullUnroll.

**Comment by DianQK** [comment]
This test case makes sense. Change PR to Draft.

**Comment by DianQK** [comment]
Preparing an `early-cse` PR.

**Pull request closed without merging**
