### PR TITLE
[lldb-dap] Fix test_exit_status_message_sigterm test.

### PR DESCRIPTION
**Pull request by mbucko**
Summary:
'test_exit_status_message_sigterm' is failing due to 'psutil' dependency introduced in PR #89405. This fix removes 'deque' dependency and checks if 'psutil' can be imported before running the test. If 'psutil' cannot be imported, it emits a warning and skips the test.

Test Plan:
./bin/llvm-lit -sv /path-to-llvm-project/lldb/test/API/tools/lldb-dap/console/TestDAP_console.py --filter=tools/lldb-dap/console/TestDAP_console.py

Reviewers:
@jeffreytan81,@clayborg,@kusmour, @JDevlieghere,@walter-erquinigo

Subscribers:

Tasks:
lldb-dap

Tags:

### CODE REVIEW

**Comment by walter-erquinigo** [comment]
What about trying to use a python builtin like https://docs.python.org/3/library/multiprocessing.html#multiprocessing.active_children?

**Comment by mbucko** [comment]
> What about trying to use a python builtin like https://docs.python.org/3/library/multiprocessing.html#multiprocessing.active_children?

Nice, I will look into it

**Comment by mbucko** [comment]
> What about trying to use a python builtin like https://docs.python.org/3/library/multiprocessing.html#multiprocessing.active_children?

It seems that multiprocessing doesn't provide a way to iteratively list the subprocesses and there is no other built in python library afaik.
Do you know if it's possible to add 'psutil' as a dependency so that it's installed before the tests are run?

**Comment by walter-erquinigo** [comment]
@JDevlieghere , do you know if it's possible to add python dependencies somewhere for lldb tests?

**Review by jeffreytan81 — APPROVED** [review]
Quick accept to unblock the build break. Feel free to follow-up in future patches for better solution.

**Pull request merged**
