### PR TITLE
[Analysis] atan2: isTriviallyVectorizable; add to massv and accelerate veclibs

### PR DESCRIPTION
**Pull request by tex3d**
This change is part of this proposal: https://discourse.llvm.org/t/rfc-all-the-math-intrinsics/78294

- Return true for atan2 from isTriviallyVectorizable
- Add atan2 to VecFuncs.def for massv and accelerate libraries.
- Add atan2 to hasOptimizedCodeGen
- Add atan2 support in llvm/lib/Analysis/ValueTracking.cpp llvm::getIntrinsicForCallSite and update vectorization tests
- Add atan2 name check to isLoweredToCall in llvm/include/llvm/Analysis/TargetTransformInfoImpl.h

Thanks to @jroelofs for the atan2 accelerate veclib and associated test additions, plus the hasOptimizedCodeGen addition.

Part of: Implement the atan2 HLSL Function #70096.

### CODE REVIEW

**Review by jroelofs — APPROVED** [review]
LGTM

**Review by farzonl — APPROVED** [review]

**Comment by farzonl** [comment]
1. Add libfunc mapping to intrinsic in `llvm/lib/Analysis/ValueTracking.cpp``llvm::getIntrinsicForCallSite`
2. Add `atan2` name check in `llvm/include/llvm/Analysis/TargetTransformInfoImpl.h` `isLoweredToCall`
3. I noticed there were some examples that use a amdlibm vector form here: https://github.com/amd/aocl-libm-ose/blob/808803d11b710678fe3565848ba2c671bed3db8a/examples/src/use_atan2.c#L138. Should we do a follow on PR that adds atan2 amdlibm and updates `llvm/test/Transforms/LoopVectorize/X86/amdlibm-calls.ll`?

**Comment by tex3d** [comment]
@farzonl 

> * Add libfunc mapping to intrinsic in `llvm/lib/Analysis/ValueTracking.cpp` `llvm::getIntrinsicForCallSite`

Added.

> * Add `atan2` name check in `llvm/include/llvm/Analysis/TargetTransformInfoImpl.h` `isLoweredToCall`

Added, but it had no test impact, so I'm looking for feedback on how this can be tested.

> * I noticed there were some examples that use a amdlibm vector form below. Should we do a follow on PR that adds atan2 amdlibm and updates `llvm/test/Transforms/LoopVectorize/X86/amdlibm-calls.ll`?

It turns out these example files have all the code under `#if 0`, and there doesn't appear to be any declarations of these vector operations in the header.  I'll leave this for a later update when the operations are added to amdlibm.

**Comment by tex3d** [comment]
@farzonl 
> See this pr: https://github.com/llvm/llvm-project/pull/95517/files
> tests like this should show that the libcall name to intrinsic mapping in the check line
> llvm/test/Transforms/SLPVectorizer/X86/call.ll

This still passes without the mapping for `tan`.  There are other places where libs calls are mapped, which is why I'm unsure of what actually depends on this code.

I commented out the whole block to see if any tests would fail, and found exactly one:
https://github.com/llvm/llvm-project/blob/cb98366ea4ce02e739eb4091c6227b67b60616c9/llvm/test/Transforms/TailCallElim/inf-recursion.ll#L3-L13
If `isLoweredToCall` returns true for `fabs`, this results in:
```ll
define double @fabs(double %f) {
entry:
 br label %tailrecurse
tailrecurse: ; preds = %tailrecurse, %entry
 br label %tailrecurse
}
```

This doesn't exactly seem like the primary effect this code is meant for.  From call graph inspection, it looks like this could impact some loop unrolling if it contains a matching call.  It doesn't look like any of these were explicitly tested though.

Architecturally, this is ugly, as is pointed out by the comment from 10 years ago in that code:
https://github.com/llvm/llvm-project/blob/cb98366ea4ce02e739eb4091c6227b67b60616c9/llvm/include/llvm/Analysis/TargetTransformInfoImpl.h#L152-L155

It seems like we should just have tablegen definitions with clear properties somewhere, then all these random spots in code that depend on specific properties would be handled in a uniform way.

I guess I'll just merge it as-is for now.

**Pull request merged**
