### PR TITLE
[SimplifyCFG] Reland transform for redirecting phis between unmergeable BB and SuccBB

### PR DESCRIPTION
**Pull request by XChy**
Reland #67275 and try to fix bugs brought or exposed by #67275.

### CODE REVIEW

**Comment by nikic** [comment]
What changed relative to the previous version of the patch?

**Comment by XChy** [comment]
> What changed relative to the previous version of the patch?

Sorry for requesting your review. I'm still pinpointing the problems and this is a draft PR now.

**Comment by XChy** [comment]
It seems to be a backend/target problem : #68953

**Comment by XChy** [comment]
> It seems to be a backend/target problem : #68953

Resolved now.

**Review by nikic — APPROVED** [review]
Let's give it another try then...

**Comment by appujee** [comment]
This patch still has a couple of bugs as exposed in 102351
1. CanPropagatePredecessorsForPHIs can't handle indirect branch
2. the set intersection algorithm has a bug.

**Comment by hiraditya** [comment]
This patch still has a couple of bugs as exposed in #102351
1. CanPropagatePredecessorsForPHIs can't handle indirect branch
2. the set intersection algorithm (to find common pred) has a bug.

**Pull request merged**
