### PR TITLE
[mlir][vector] Refactor vector-transfer-flatten.mlir (nfc) (2/n)

### PR DESCRIPTION
**Pull request by banach-space**
The main goal of this and subsequent PRs is to unify and categorize
tests in:
  * vector-transfer-flatten.mlir
  
This should make it easier to identify the edge cases being tested (and
how they differ), remove duplicates and to add tests for scalable
vectors.

Below are the main contributions of this PR

1. Two tests duplicated
  `@transfer_{read|write}_dims_mismatch_non_contiguous_slice`:
    * `@transfer_{read|write}_dims_mismatch_non_contiguous` and
    * `@transfer_read_flattenable_negative` duplicated
  `@transfer_{read|write}_dims_mismatch_non_contiguous_slice`.
  
   These tests are removed (the original test is preserved).

2. `@transfer_read_flattenable_negative2` is replaced with
   two tests with more descriptive names:
    * `@transfer_read_non_contiguous_src` (for `xfer_read`) and
    * `@transfer_write_non_contiguous_src` (for `xfer_write`)

### CODE REVIEW

**Review by nujaa — APPROVED** [review]
LGTM. Test coverage seems to be kept and can't find a single NIT.

**Comment by banach-space** [comment]
> LGTM. Test coverage seems to be kept and can't find a single NIT.

Thank you for reviewing 🙏🏻 

If you have some spare cycles left this week, please also take a look at 1/n: https://github.com/llvm/llvm-project/pull/96031. No worries if you are busy!

**Comment by nujaa** [comment]
> If you have some spare cycles left this week, please also take a look at 1/n: https://github.com/llvm/llvm-project/pull/96031. No worries if you are busy!

I wish I could,  I have nothing against it but, personally I do not have any opinion on the question. I'll let the community decide.

**Comment by banach-space** [comment]
> > If you have some spare cycles left this week, please also take a look at 1/n: #96031. No worries if you are busy!
> 
> I wish I could, I have nothing against it but, personally I do not have any opinion on the question. I'll let the community decide.

Sorry, I meant https://github.com/llvm/llvm-project/pull/95743 🤦🏻

**Pull request merged**
