### PR TITLE
[clang-format] Fix a serious bug in `git clang-format -f`

### LINKED ISSUE #102459: git-clang-format clears files listed in .clang-format-ignore
When using `git clang-format` with `.clang-format-ignore`, the files listed in `.clang-format-ignore` are beeing cleared.

Example:
A simple `main.cpp` file located under [project root, location of `.clang-format` and `.clang-format-ignore`]/src/main.cpp:

```
#include <iostream>

int main() {
    std::cout << "Hello, World!" << std::endl;
    return 0;
}
```

If I add `src/main.cpp` to `.clang-format-ignore` and run `git clang-format -f --style=file` the contents of `main.cpp` get erased.
If I run `clang-format -i --style=file src/main.cpp` the file is ignored and everything works like it's supposed to.

### PR DESCRIPTION
**Pull request by owenca**
With the --force (or -f) option, git-clang-format wipes out input files excluded by a .clang-format-ignore file if they have unstaged changes.

This patch adds a hidden clang-format option --list-ignored that lists such excluded files for git-clang-format to filter out.

Fixes #102459.

### CODE REVIEW

**Review by HazardyKnusperkeks — APPROVED** [review]

**Comment by stefanpantic-pdftools** [comment]
FYI: this breaks the tool:

```bash
git clang-format --binary /usr/bin/clang-format --extensions $INPUT_EXTENSIONS --diff origin/$INPUT_TARGET_BRANCH origin/$INPUT_SOURCE_BRANCH
`/usr/bin/clang-format -list-ignored` returned 1
clang-format: Unknown command line argument '-list-ignored'.  Try: '/usr/bin/clang-format --help'
clang-format: Did you mean '--lines'?
```

**Comment by owenca** [comment]
You need to use the clang-format built from this patch, which adds the new clang-format `-list-ignored` option.

**Comment by stefanpantic-pdftools** [comment]
Gotcha, thanks!

**Pull request merged**
