### PR TITLE
[ADT] Make DenseMap/DenseSet more resilient against OOM situations

### PR DESCRIPTION
**Pull request by marcauberer**
This patch hardens DenseMap and DenseSet against OOM scenarios, outlined in [this RFC](https://discourse.llvm.org/t/rfc-malfunction-safe-densemap-denseset/81036). Feel free to comment any comments/suggestions/objections there.

As discussed in the RFC, we would eventually like to have malfunction tests to ensure malfunction-safety. This is still in internal discussion on our side. Therefore we would like to contribute the improvements with the existing functional tests for now.

### CODE REVIEW

**Comment by kazutakahirata** [comment]
Is there any way you could split your patch into several smaller ones?

If you are going to work on pretty much all of `DenseMap`/`DenseSet`, you might want to post a PR just to clang-format the whole thing.  This should separate interesting changes and the rest.

After that, I would get small obvious changes out of the way.  For example, your `if constexpr (std::is_trivially_destructible_v<ValueT>)` change will probably receive a quick LGTM.

Thanks!

**Comment by marcauberer** [comment]
Yes, agreed.
For the clang-format preparation change, see here: https://github.com/llvm/llvm-project/pull/108162

**Comment by nikic** [comment]
This direction looks quite concerning to me. LLVM is explicitly not designed to be exception safe, and this change is not at all free. It introduces significant implementation complexity, compile-time impact and memory usage impact.

The minimum requirement here is going to be that this does not have any compile-time/memory usage impact on people who do not need this functionality -- but I'm not convinced that we should accept this downstream at all, as a matter of policy.

Major compile-time regressions: https://llvm-compile-time-tracker.com/compare.php?from=f4dd1bc8fc625d3938f95b9d06aaaeebd2e90dca&to=1cb62cb5fb8eeca9641992f98f1b24b328410034&stat=instructions:u

Major memory usage regressions: https://llvm-compile-time-tracker.com/compare.php?from=f4dd1bc8fc625d3938f95b9d06aaaeebd2e90dca&to=1cb62cb5fb8eeca9641992f98f1b24b328410034&stat=max-rss

**Comment by kuhar** [comment]
+1 to what @nikic said. As an ADT contributor, the thing I really value about our implementation is that it's much simpler than alternative hash maps that have to worry about exceptions. I think it's safe to say that LLVM developers at large are not used to / trained to think about exception safety, and this puts burden on subsequent contributors who may not care about handling these specific OOM conditions.

**Pull request closed without merging**
