### PR TITLE
[clang-format] Fix a bug in annotating StartOfName

### LINKED ISSUE #99758: clang-format adding spaces around the arrow operator
Since upgrading from v17.0.6 to 18 code like this:

```
void UiIntegration::requestNavigateToCode(const QUrl &url, int lineNumber, int columnNumber)
{
    if (UiIntegration::instance())
        emit UiIntegration::instance()->navigateToCode(url, lineNumber, columnNumber);
}
```

is being reformatted like this:
```
void UiIntegration::requestNavigateToCode(const QUrl &url, int lineNumber, int columnNumber)
{
    if (UiIntegration::instance())
        emit UiIntegration::instance() -> navigateToCode(url, lineNumber, columnNumber);
}

```

ie. spaces are being added around the arrow operator.  I don't want those spaces

is there a configuration to control this behavior that I'm missing?
else I think this is a bug.

### PR DESCRIPTION
**Pull request by owenca**
Fixes #99758.

### CODE REVIEW

**Review by HazardyKnusperkeks — APPROVED** [review]

**Comment by alex1701c** [comment]
Can we expect this to be backported and released with clang-format-18?

**Comment by owenca** [comment]
Unfortunately no because clang-format is part of llvm, and as far as I know there will be no more llvm 18 point releases.

**Comment by alex1701c** [comment]
That is very unfortunate. It means one will either get different results for the clang-format versions, one disables the formatting, or works around it by sth. Like Q_EMIT(something()->mySignal()).

**Comment by owenca** [comment]
> That is very unfortunate. It means one will either get different results for the clang-format versions, one disables the formatting, or works around it by sth. Like Q_EMIT(something()->mySignal()).

Or wait for the next release (in this case 19.1.0, which is just around the corner).

**Comment by alex1701c** [comment]
But that does not mean everyone who works on the projects will update to that version right away :(

**Comment by owenca** [comment]
Wouldn't you have the same problem if we were to backport the fix, say, to 18.1.9? Anyway, LLVM 19.1.0 has just been released.

**Comment by alex1701c** [comment]
I think it would be normal for distros to backport bugfixes. Thus, users should get the new version rather soonish.

**Pull request merged**
