### PR TITLE
[libc++][Android] Add NDK ABI lists for i686 and x86_64

### LINKED ISSUE #69270: [libc++][Android] Add official Android support to libc++
Android switched to libc++ years ago, but Android still isn't officially supported in libc++. We should add support for it. libc++ already builds and works on Android, but many of the tests don't pass, and there should be automated testing.

### PR DESCRIPTION
**Pull request by rprichard**
This commit adds ABI lists for the Android NDK.

Fixes: https://github.com/llvm/llvm-project/issues/69270
Differential Revision: https://reviews.llvm.org/D155341

### CODE REVIEW

**Review by EricWF — CHANGES_REQUESTED** [review]
If it's not already clear elsewhere, could you document how to regenerate these?

Also do we _need_ these upstream? I'm not sure upstream libc++ can manage androids ABI for it, at least we can't make decisions to add or remove symbols.

**Comment by rprichard** [comment]
> If it's not already clear elsewhere, could you document how to regenerate these?

I think `run-buildbot` generates the ABI list files when it runs and uploads them as BuildKite artifacts (see the line in the `android-ndk-*` section that invokes `check-abi-list`. The CI fails if the generated list doesn't match what's checked in.

I mostly included these files because the other libc++ targets also had them. I don't actually know if we need them or not. I'd be happy to leave them out (and modify run-buildbot to stop checking them for Android).

Aside: The name of the two files is a bit off, because it doesn't include the term "ndk", and I think we probably want to add a libc++ test for the Android platform build of libc++, which is a bit different -- e.g. it uses `std::__1` instead of `std::__ndk1`, targets a different API level, and separates out the libc++abi demangler into a static archive that usually isn't needed.

**Comment by EricWF** [comment]
Unless things have changed, these files are for additional verification of the exported ABI, they're not strictly needed.

 If android cares about it's  exports changing, and if buildkite regenerates this as needed, then putting it in-tree makes sense.

**Review by EricWF — APPROVED** [review]

**Review by EricWF — CHANGES_REQUESTED** [review]
We've decided to abandon this change, right?

**Comment by ldionne** [comment]
> We've decided to abandon this change, right?

I don't think so. If Android wants to be ABI stable, then we should have those ABI list files checked in like we do for other platforms. If we do that, this patch should re-enable the ABI checking that was removed by #69666

**Comment by ldionne** [comment]
@rprichard Gentle ping -- I think you folks intend to be ABI stable, so we should finish up this patch and ship it.

**Comment by ldionne** [comment]
Ping. I'd really like us to finish this!

**Comment by ldionne** [comment]
@rprichard Gentle ping, I don't think this is hard to finish but it would be great to get it done and close the PR.

**Comment by rprichard** [comment]
Sorry about that. Yes, I'll get to this soon (probably today if I can).

**Comment by rprichard** [comment]
I think we do want this ABI checking for Android, because the Android team tries to avoid ABI breakages in libc++.

**Pull request merged**
