### PR TITLE
[lldb] Fix typos in various help messages.

### PR DESCRIPTION
**Pull request by rjmansfield**

### CODE REVIEW

**Review by jimingham — APPROVED** [review]
LGTM

**Review by bulbazord — APPROVED** [review]

**Comment by rjmansfield** [comment]
Could someone with commit access please merge on my behalf? Thanks.

**Comment by jimingham** [comment]
Done.

**Comment by jimingham** [comment]
I can't delete your branch, however, if you had wanted to do that.

**Pull request merged**
