### PR TITLE
[flang] Pass Argv0 to getIntriniscDir and getOpenMPHeadersDir

### PR DESCRIPTION
**Pull request by madanial0**
The `llvm::sys::fs::getMainExecutable(nullptr, nullptr)` is not able to obtain the correct executable path on AIX without Argv0 due to the lack of a current process on AIX's  `proc` filesystem. This causes a build failure on AIX as intrinsic module directory is missing.

### CODE REVIEW

**Comment by brad0** [comment]
This fixes building the Flang modules on OpenBSD, NetBSD and Haiku.

**Comment by madanial0** [comment]
> I see you re-based 2 times. Does this look Ok as is? It would be good to add the AIX Driver bits once this goes in.

This should be good as is pending any review comments/approvals

**Comment by brad0** [comment]
It would be nice to get this in so Flang is buildable.

**Review by kiranchandramohan — APPROVED** [review]
LG.

**Pull request merged**
