### PR TITLE
Reland 'Update llvm::Registry to work for LLVM shared library builds on windows' (#109024)

### PR DESCRIPTION
**Pull request by fsfod**
Fix missing extern templates for llvm::Registry use in other projects of llvm

Windows doesn't implicitly import and merge exported symbols across shared libraries
like Linux does so we need to explicitly export/import each instantiation of llvm::Registry.
Updated LLVM_INSTANTIATE_REGISTRY to just be a full explicit template instantiation.

This is part of the work to enable LLVM_BUILD_LLVM_DYLIB and LLVM plugins on window.

### CODE REVIEW

**Comment by nico** [comment]
This seems to break building of clang-tools-extra binaries: http://45.33.8.238/win/95986/step_3.txt

Please take a look and revert for now if it takes a while to fix.

**Comment by fsfod** [comment]
Its strange that visibility macros are enabled for windows but its not a shared library build, idk if the gn build script need to be manually updated to define the macros correctly to turn off visibility macros by default.

**Comment by fsfod** [comment]
The fix for the gn build system would be to unconditionally define CLANG_BUILD_STATIC for the windows platform for now.

**Comment by glandium** [comment]
Ironically, this and later changes related to LLVM_BUILD_LLVM_DYLIB for Windows broke  LLVM_EXPORT_SYMBOLS_FOR_PLUGINS, which is a currently working way to use clang plugins on Windows, while LLVM_BUILD_LLVM_DYLIB doesn't work yet.

**Pull request merged**
