### PR TITLE
[SandboxIR] Implement GlobalIFunc

### PR DESCRIPTION
**Pull request by vporpo**
This patch implements sandboxir::GlobalIFunc mirroring llvm::GlobalIFunc.

### CODE REVIEW

**Review by Sterling-Augustine — APPROVED** [review]

**Comment by vporpo** [comment]
The windows bot error does not seem to be related to this, so I will merge it.

**Comment by nikic** [comment]
Why does sandbox IR have to mirror something as exotic as GlobalIFunc, which should not be relevant to vectorization. Can sandbox IR reference opaque values for things outside its scope?

**Comment by vporpo** [comment]
> Why does sandbox IR have to mirror something as exotic as GlobalIFunc, which should not be relevant to vectorization.

We are trying to make Sandbox IR as generic as possible, so that it can be used in other contexts if needed. GlobalIFunc and a few others are indeed quite exotic and won't probably be used. 

>  Can sandbox IR reference opaque values for things outside its scope?

It can, but we would rather not rely on it if possible. It's better to have a Sandbox IR class for something exotic, even it's missing some functionality compared to LLVM IR, rather than having an opaque object.

**Comment by nikic** [comment]
Mirroring unnecessary things into SandboxIR increases the burden on maintaining IR, because any change to IR has to be synced to SandboxIR. In that respect, it would be preferable if SandboxIR only mirrored the parts that are necessary to the prototype of the sandbox vectorizer. It looks like it currently tries to mirror *all* APIs of *all* types in the Value hierarchy.

**Comment by vporpo** [comment]
Yes, there is a cost, but I would argue that it is rather limited, because the implementation of most Sandbox IR APIs is quite trivial: they just call the LLVM API internally. If it does end up becoming a maintenance burden for whatever reason, dropping the SandboxIR API is always an option.

**Pull request merged**
