### PR TITLE
Generate a new requirements.txt to fix CVEs

### PR DESCRIPTION
**Pull request by joycebrum**
Hi! Here is a patch for #81859 that fix the vulnerabilities found in gitpython, cryptography, urllib3 and requests.

I have just regenerated the requirements.txt files running pip-compile again. Fortunately, this was enough to set all the dependencies on safe versions.

I have also checked if new vulnerabilities were introduced by running scorecard on my fork, but none has been introduced.

Thanks!

### CODE REVIEW

**Review by tstellar — APPROVED** [review]
LGTM.  Thank you very much for doing this.

**Comment by tstellar** [comment]
Do yo need me to commit this for you?

**Comment by joycebrum** [comment]
> Do yo need me to commit this for you?

Commit you mean through Phabricator? If that's the case, I can do that, but I understood Phabricator is now read only that's why I opened a PR instead.

**Comment by tstellar** [comment]
@joycebrum I mean do you have write access to the git repository?  If not, I can merge this for you.

**Pull request merged**
