### PR TITLE
 [RemoveDIs] Print IR with debug records by default

### PR DESCRIPTION
**Pull request by SLTozer**
This patch makes the final major change of the RemoveDIs project, changing the default IR output from debug intrinsics to debug records.

This is expected to break a large number of tests: every single one that tests for uses or declarations of debug intrinsics and does not explicitly disable writing records. There is also some collateral damage for tests that merely *contains* debug intrinsic declarations and test for attributes, as debug intrinsic declarations will now be deleted when writing debug records which may result in renumbering of other attributes.

### Review guidance

This patch is divided into distinct sections, in the following order and comprising the following commits:

1. NFC manual test updates in preparation for the automated test updates.
    - Pre-script fixups 
2. The functional change of the patch, which enables the printing of debug records by default.
    - Print debug records by default 
3. The automated test updates, which comprise the vast majority of changes in this patch.
    - update_test_checks.py
    - update_cc_test_checks.py 
    - substitute-checks.sh
4. Further manual test updates to fix up test errors that cannot be fixed by (or are caused by) the automated test updates.
    - Manual fixups post-update_test_checks 

My recommendation is to review individual commits rather than the patch as a whole, due to the extreme size of the automated updates. The manual changes made in this patch comprise a diff of size `+48, -45`, roughly 0.7% of the diff size of the complete patch. Instead of reviewing the automated test updates, I would instead recommend reviewing the "Update script details" section below, which explains the automated update process and gives exact steps to reproduce my results.

### Update script details

For the most part, replacing debug intrinsics with debug records is trivial string substitution; replacing FileCheck CHECK lines for debug intrinsics is a slightly more complicated string substitution. For tests that use update_test_checks.py, updating the tests is entirely automatic, but for the many debug info tests that do not use update_test_checks.py I've used a less "smart" approach. The steps to produce the test updates are as follow:

1. Collect the list of failing lit tests into a single file, `failing-tests.txt`, separated by (and ending with) newlines.
2. Use the following line to split the failing tests into tests that use update_test_checks and tests that don't:
    ```
    $ while IFS= read -r f; do grep -q "Assertions have been autogenerated by" "$f" && echo "$f" >> update-checks-tests.txt || echo "$f" >> manual-tests.txt; done < failing-tests.txt
    ```
3. For the tests that use update_test_checks, run the appropriate update_test_checks script - for the updates run here, this was achieved with:
    ```
    $ xargs ./llvm/utils/update_test_checks.py --opt-binary ./build/bin/opt < update-checks-tests.txt
    $ xargs ./llvm/utils/update_cc_test_checks.py --llvm-bin ./build/bin/ < update-checks-tests.txt
    ```
4. For the manual tests, I used a pair of short scripts to perform the updates. The first script is used to fetch the check prefixes in each of the failing tests:
    ```
    $ cat ./get-checks.sh
    #!/bin/bash

    # Always add CHECK, since it's more effort than it's worth to filter files where
    # every RUN line uses other check prefixes.
    # Then detect every instance of "check-prefix(es)=..." and add the
    # comma-separated arguments as extra checks.
    for filename in "$@"
    do
        echo "$filename,CHECK"
        allchecks=$(grep -Eo 'check-prefix(es)?[ =][A-Z0-9_,-]+' $filename | sed -E 's/.+[= ]([A-Z0-9_,-]+).*/\1/g; s/,/\n/g')
        for check in $allchecks; do
            echo "$filename,$check"
        done
    done
    ```
    The second script performs the work of actually updating the check-lines in each of the failing tests, with a series of simple substitution patterns:
    ```
    $ cat ./substitute-checks.sh
    #!/bin/bash

    file="$1"
    check="$2"

    # Any test that explicitly tests debug intrinsic output is not suitable to
    # update by this script.
    if grep -q "write-experimental-debuginfo=false" "$file"; then
        exit 0
    fi

    sed -i -E -e "
    /(#|;|\/\/).*$check[A-Z0-9_\-]*:/!b
    /DIGlobalVariableExpression/b
    /!llvm.dbg./bpostcall
    s/((((((no|must)?tail )?call.*)?void )?@)?llvm.)?dbg\.([a-z]+)/#dbg_\7/
    :postcall
    /declare #dbg_/d
    s/metadata //g
    s/metadata\{/{/g
    s/DIExpression\(([^)]*)\)\)(,( !dbg)?)?/DIExpression(\1),/
    /#dbg_/!b
    s/((\))?(,) )?!dbg (![0-9]+)/\3\4\2/
    s/((\))?(, ))?!dbg/\3/
    " "$file"
    ```
    Both of these scripts combined can be used on the list in `manual-tests.txt` as follows:
    ```
    $ cat manual-tests.txt | xargs ./get-checks.sh | sort | uniq | awk -F ',' '{ system("./substitute-checks.sh " $1 " " $2) }'
    ```
    These scripts deal successfully with the vast majority of checks in `clang/test` and `llvm/test`; more explanation of why I used these scripts appears below.
5. Verify the resulting tests pass, and detect any failing tests:
    ```
    $ xargs ./build/bin/llvm-lit -q < failing-tests.txt
    ********************
    Failed Tests (5):
    LLVM :: DebugInfo/Generic/dbg-value-lower-linenos.ll
    LLVM :: Transforms/HotColdSplit/transfer-debug-info.ll
    LLVM :: Transforms/ObjCARC/basic.ll
    LLVM :: Transforms/ObjCARC/ensure-that-exception-unwind-path-is-visited.ll
    LLVM :: Transforms/SafeStack/X86/debug-loc2.ll


    Total Discovered Tests: 295
    Failed: 5 (1.69%)
    ```
6. Some tests may have failed - the update scripts are deliberately not smart, and so there are cases that they will not handle. These must be manually dealt with.

### What's with the update scripts?

The test scripts above are deliberately simple - they only operate on basic string substitution, for two reasons: the test update step should be a one-time process, so something clever that covers all cases would be wasted effort, and being very simple should give reassurance that nothing magical is happening here. Almost all the error cases result from check-lines which do not obviously apply to a debug intrinsic, and the difficulty of manually fixing up these cases should be fairly low.

### How do I fix test failures?

The simplest way to fix a test failure is to not use the new format; if an immediate fix is needed for some set of tests, then adding the LLVM flag `--write-experimental-debuginfo=false` will force it to write debug intrinsics, preserving prior behaviour. This should only be a temporary fix in most cases though, as we are moving towards deprecating debug intrinsics.

The commits in which I fixed up tests are labelled "Pre-script fixups" and "Post-script fixups" in this review, for examples of changes that were made. The reason these are divided into pre- and post- is that some fixups are trivial text changes to make check-lines intelligible to the sed scripts, and some are changes that are breaking if applied to the debug intrinsic case, so should not apply before the functional change.

For anyone fixing their tests downstream, splitting your fixes into pre-script and post-script may not be necessary; for both cases, you will need to run the script, run the tests, and fix each test that fails. The benefit of splitting those fixes into pre- and post- is to give certainty that all the pre-script fixes are NFC, reducing the complexity of review; if this is not an issue for you, then it will be faster to just fix each broken check-line after running the script.

The pre-script changes are:

- Modifying unusually-structured check-lines to be more standard:
    ```
    -  int l = 0;    // line #4: CHECK: {{call.*llvm.dbg.declare.*%l.*\!dbg }}[[variable_l:![0-9]+]]
    +  int l = 0;    // line #4: CHECK: call void @llvm.dbg.declare({{.*%l.*}}!dbg [[variable_l:![0-9]+]]
    ```
- Changing some over-eager capture patterns:
    ```
    -  // CHECK: call void @llvm.dbg.label(metadata [[LABEL_METADATA:!.*]]), !dbg [[LABEL_LOCATION:!.*]]
    +  // CHECK: call void @llvm.dbg.label(metadata [[LABEL_METADATA:!.*]]), !dbg [[LABEL_LOCATION:![0-9]+]]
    ```
    In the example above, the `LABEL_LOCATION` variable will just capture "!10" in intrinsic form, but will capture "!10)" in record form since the debug loc now appears in a parenthesis-enclosed list.
- Removing certain `!dbg` prefixes:
    ```
    -// CHECK: call {{.*}}, !dbg ![[DBG_LINE:[0-9]+]]
    +// CHECK: call void @llvm.dbg.declare({{.+}}), !dbg ![[DBG_LINE:[0-9]+]]
    ```
    Where `!dbg !<Num>` appears in debug intrinsics, we only see `!<Num>` in debug records; the script handles this in cases where we are clearly operating on a debug intrinsic, but when the debug location check appears on a separate check-line it must be manually updated. In some cases this will require some additional context to be added to the check to ensure that the test is still valid.
- Changes without context:
    ```
    -  ; CHECK-SAME:               DW_OP_LLVM_convert, 32, DW_ATE_unsigned, DW_OP_stack_value))
    +  ; CHECK-SAME:               DW_OP_LLVM_convert, 32, DW_ATE_unsigned, DW_OP_stack_value)
    ```
    Some minor differences, like DIExpressions no longer being the final argument to a debug record, can't be fixed by the script because they appear on a line without the necessary context; these must be updated manually.
- Fixing typos:
    ```
    -; CHECK: all void @llvm.dbg.value(metadata ptr %lsr.iv, metadata ![[MID_p:[0-9]+]],  metadata !DIExpression(DW_OP_constu, 3, DW_OP_minus, DW_OP_stack_value))
    +; CHECK: call void @llvm.dbg.value(metadata ptr %lsr.iv, metadata ![[MID_p:[0-9]+]],  metadata !DIExpression(DW_OP_constu, 3, DW_OP_minus, DW_OP_stack_value))
    ```
- Ensuring that the debug intrinsic format is used where necessary:
    ```
    -; RUN: llvm-dis < %s.bc | FileCheck %s
    +; RUN: llvm-dis < %s.bc --write-experimental-debuginfo=false | FileCheck %s
    ```
    Some tests need to continue using the debug intrinsic format; use `--write-experimental-debuginfo=false` for these cases, and the update script will ignore them.

The post-script changes are generally simpler:

- Update attributes:
    ```
    -; CHECK: attributes #1 = { nocallback nofree nosync nounwind speculatable willreturn memory(none) }
    ```
    Debug intrinsic declarations are being removed, and the resulting attributes may disappear from the output.
- Fix script errors:
    ```
    -; CHECK: call void @llvm.random.metadata.use(ptr undef
    +; CHECK: call void @llvm.random.metadata.use(metadata ptr undef
    ```
    The update script errs on the side of caution, but there are some unusual cases where the patterns it expects to update are over-eager, such as the use of MetadataAsValue in functions other than debug intrinsics.

### CODE REVIEW

**Review by jryans — COMMENTED** [review]
Overall, your process looks good to me! Thanks for working on this and including such a detailed description. This will surely aid downstream maintainers. 😄 

There's one part I did not fully understand. How did you identify the "pre-script fixups"? What's the importance of those changes? I did not seen any mention of that in your PR description.

**Comment by SLTozer** [comment]
> There's one part I did not fully understand. How did you identify the "pre-script fixups"? What's the importance of those changes? I did not seen any mention of that in your PR description.

Good question, I'll add my answer to the main description: The pre-script fixups were determined post-script; so I ran the script, looked at the tests that still failed, and examined why - in most cases this isn't hard, because the problem `CHECK` is the one that fails the test. The pre-script fixups change existing patterns so that the script can handle them correctly, while the post-script fixups cover cases that the script can't fix or otherwise mishandles. In both cases we need to run the script first to identify the problems and manually fixup the check lines, and for a downstream user it _may_ be easier to skip the pre-script stuff and just fix all broken checks manually after the script makes its best effort; my splitting of the pre-script modifications was more to ensure that as much of this review is automated as possible, rather than a necessary step.

**Review by jryans — APPROVED** [review]
Thanks for clarifying the pre-script fixes. With that resolved, this looks good to me.

**Comment by SLTozer** [comment]
> Thanks for clarifying the pre-script fixes. With that resolved, this looks good to me.

TYVM for the LGTM! I'll leave the review up for a bit in case anyone has anything further to add.

**Pull request merged**
