### PR TITLE
[Clang] Implement CWG2137 (list-initialization from objects of the same type)

### PR DESCRIPTION
**Pull request by MitalAshok**
[CWG2137](https://cplusplus.github.io/CWG/issues/2137.html)

This was previously implemented and then reverted in Clang 18 as #77768

This also implements a workaround for [CWG2311](https://cplusplus.github.io/CWG/issues/2311.html), similarly to the 2024-03-01 comment for [CWG2742](https://cplusplus.github.io/CWG/issues/2742.html).

The exact wording this tries to implement, relative to the C++26 draft:

[over.match.list]p(1.2)

> Otherwise, or if no viable initializer-list constructor is found <ins>and the initializer list does not consist of exactly a single element with the same cv-unqualified class type as `T`</ins>, overload resolution is performed again, [...]

[dcl.init.list]p(3.7)

> Otherwise, if `T` is a class type, constructors are considered. The applicable constructors are enumerated and the best one is chosen through overload resolution. <ins>If no constructor is found and the initializer list consists of exactly a single element with the same cv-unqualified class type as `T`, the object is initialized from that element (by copy-initialization for copy-list-initialization, or by direct-initialization for direct-list-initialization). Otherwise,</ins> if a narrowing conversion (see below) is required [...]

### CODE REVIEW

**Comment by MitalAshok** [comment]
Note that only a single line has changed from the previous PR: https://github.com/llvm/llvm-project/commit/d90534729d34da86bb01c4ddc272310f0f0b4ce4#diff-19c518dbc68b30c66e1a2b6bd523c005fb2050dcf1a0e92305df7ab3e1b9e9f3L1653

I was waiting on a proper resolution for CWG2311, but the (identical/duplicate?) CWG2742 claims that "The consensus is to try an initializer-list constructor first and then fall back to copy-initialization", which is what this does. This is still slightly different from what GCC does.

**Comment by MitalAshok** [comment]
@yxsamliu Re: https://github.com/llvm/llvm-project/pull/77768#issuecomment-1957171805: That is the expected behaviour, since CWG2137 expressly wants to use initializer_list constructors over non-initializer_list constructors (especially copy constructors)

**Review by ldionne — APPROVED** [review]
Thanks for fixing the libc++ tests. That part of the patch LGTM.

**Comment by MitalAshok** [comment]
I'm waiting to rebase on #97403 to remove the libc++ component of this now

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Comment by cor3ntin** [comment]
@MitalAshok ping

**Comment by cor3ntin** [comment]
@MitalAshok Feel free to merge :)

**Comment by MitalAshok** [comment]
@cor3ntin Could you merge this for me please? Thanks

**Comment by yuxuanchen1997** [comment]
A noob question but I wanted to make sure that this patch actually intended to reject program like this one?
```
#include <type_traits>
#include <vector>

class K {
 public:
  template <class T>
  K(const std::vector<T>& v) {
    static_assert(!std::is_same<T, K>::value, "Error!");
  }
};

void foo(std::vector<K>& inputs) {
  auto v{inputs};
}
```
Compiler Explorer: https://godbolt.org/z/659Pao8j9
GCC has always rejected this program but MSVC and EDG both accepted. After this patch, clang also rejects. This is a little unintuitive and I don't know how the intention of [CWG2137](https://cplusplus.github.io/CWG/issues/2137.html) covered this. 

Just need confirmation that this is intended.

**Pull request merged**
