### PR TITLE
[libc++] [NFC] Split typeinfo header

### PR DESCRIPTION
**Pull request by itrofimow**
This PR splits `typeinfo` header into public and private parts, with the purpose of simplifying https://github.com/llvm/llvm-project/pull/65534, which should be rebased onto this patch

### CODE REVIEW

**Comment by itrofimow** [comment]
Hi @philnik777!
This is a header-split part of https://github.com/llvm/llvm-project/pull/65534 which you suggested to be a separate PR, could you please have a look?

**Comment by philnik777** [comment]
I'm a bit confused. This looks like you should just remove some transitive include that we kept for compatibility. I think our current stance on include cycles that break us is to just remove the include and add a release note about it.

**Comment by itrofimow** [comment]
Sorry for confusing you, i'm not that familiar with how such things are handled.

Do i understand you correctly, that instead of splitting the header i should just remove the conditional `#include <exception>` from `typeinfo` and reverse the dependency (now `exception` would include `typeinfo`) instead?

**Comment by philnik777** [comment]
> Sorry for confusing you, i'm not that familiar with how such things are handled.
> 
> Do i understand you correctly, that instead of splitting the header i should just remove the conditional `#include <exception>` from `typeinfo` and reverse the dependency (now `exception` would include `typeinfo`) instead?
> 
> If that's the case i would just do that in #65534 and close this PR.

Yes, that's at least what I would do. We don't have any exact policy on this I think, but this seems to me like a reasonable potentially breaking change. These headers aren't used that much compared to other headers anyways. Sorry that I didn't spot this earlier. @ldionne do you agree?

**Comment by ldionne** [comment]
> > Sorry for confusing you, i'm not that familiar with how such things are handled.
> > Do i understand you correctly, that instead of splitting the header i should just remove the conditional `#include <exception>` from `typeinfo` and reverse the dependency (now `exception` would include `typeinfo`) instead?
> > If that's the case i would just do that in #65534 and close this PR.
> 
> Yes, that's at least what I would do. We don't have any exact policy on this I think, but this seems to me like a reasonable potentially breaking change. These headers aren't used that much compared to other headers anyways. Sorry that I didn't spot this earlier. @ldionne do you agree?

That sounds like a reasonable not-too-badly-breaking change.

**Pull request closed without merging**
