### PR TITLE
[sanitizer_common] Fix internal_*stat on Linux/sparc64

### PR DESCRIPTION
**Pull request by rorth**
```
  SanitizerCommon-Unit :: ./Sanitizer-sparcv9-Test/SanitizerCommon/FileOps
```
`FAIL`s on 64-bit Linux/sparc64:
```
projects/compiler-rt/lib/sanitizer_common/tests/./Sanitizer-sparcv9-Test --gtest_filter=SanitizerCommon.FileOps
--
compiler-rt/lib/sanitizer_common/tests/sanitizer_libc_test.cpp:144: Failure
Expected equality of these values:
  len1 + len2
    Which is: 10
  fsize
    Which is: 1721875535
```
The issue is similar to the mips64 case: the Linux/sparc64 `*stat` syscalls take a `struct kernel_stat64 *` arg.  Also the syscalls actually used differ.

This patch handles this, adopting the mips64 code to avoid too much duplication.

Tested on `sparc64-unknown-linux-gnu` and `x86_64-pc-linux-gnu`.

### CODE REVIEW

**Review by vitalybuka — APPROVED** [review]

**Comment by rorth** [comment]
It turns out I messed up: that patch broke the Solaris/sparcv9 build because the section messing with Linux headers to
get `struct kernel_stat*` declarations wasn't guarded appropriately.  Now fixed with 16e9bb9cd7f50ae2ec7f29a80bc3b95f528bfdbf.

**Comment by rorth** [comment]
If this patch gets backported to the 19.x branch, the followup is necessary, too.

**Comment by rorth** [comment]
Done: PR #101236.

**Pull request merged**
