### PR TITLE
[MachineScheduler][ScheduleDAG] Add ability to bias scheduling by longest paths

### PR DESCRIPTION
**Pull request by michaelmaitland**
Currently the scheduler only biases by critical path. However, it is possible that there are paths that are long (but not the longest). Bias paths by decreasing order of depth to bias the longest paths.

I saw a small improvement on spec2017/523.xalancbmk_r in dynamic instruction count and in runtime with this change on RISC-V.

I am disabling this feature by default to make minimal impact to targets tuned with the algorithm prior to this patch.

### CODE REVIEW

**Comment by wangpc-pp** [comment]
Make sense to me, I just wonder how this change would improve dynamic inst counts, does this change decrease register pressure in some way?

**Comment by csstormq** [comment]
Is there any way to add a unit test to demonstrate the improved assembly code on RISC-V?

**Comment by michaelmaitland** [comment]
> Is there any way to add a unit test to demonstrate the improved assembly code on RISC-V?

I have attempted to add a test that does this. However, it seems like such a test would not be stable: on some runs, the critical path version ends up being the same as the longer paths version. Other times, the critical path version is different from the longer paths version. 

This leads the test to pass some times and to fail other times. The benefit of using the test I add in this patch, is that it is deterministic.

**Comment by michaelmaitland** [comment]
> Make sense to me, I just wonder how this change would improve dynamic inst counts, does this change decrease register pressure in some way?

I did some more experiments. It turns out that the dynamic IC actually stays the same as a result of this change. All diff in spec2006 and spec2017 is related to reordering of instructions.

**Comment by csstormq** [comment]
> > Is there any way to add a unit test to demonstrate the improved assembly code on RISC-V?
> 
> I have attempted to add a test that does this. However, it seems like such a test would not be stable: on some runs, the critical path version ends up being the same as the longer paths version. Other times, the critical path version is different from the longer paths version.
> 
> This leads the test to pass some times and to fail other times. The benefit of using the test I add in this patch, is that it is deterministic.

Can you attach that test case if possible? I'm curious why it's unstable. It would be great if we could visually demonstrate what the improved code looks like.

**Comment by arsenm** [comment]
> This leads the test to pass some times and to fail other times. The benefit of using the test I add in this patch, is that it is deterministic.

Then there's a bug in the patch, the compiler output should always be deterministic

**Comment by michaelmaitland** [comment]
> Then there's a bug in the patch, the compiler output should always be deterministic

It turns out that the non-determinism only existed in our downstream and was related to a different issue. That separate issue led me to believe that this patch was helping to improve scheduling. I suppose this patch helped that non-determinism show itself. After resolving the non-determinism in our downstream, the gains we saw "due to this patch" went away. As a result, I am closing this PR since it does not seem to help much.

**Pull request closed without merging**
