### PR TITLE
[SDAG] Intersect poison-generating flags after CSE

### PR DESCRIPTION
**Pull request by dtcxzyw**
This patch intersects poison-generating flags after CSE to fix assertion failure reported in https://github.com/llvm/llvm-project/pull/112354#issuecomment-2452369552.
It is an alternative to https://github.com/llvm/llvm-project/pull/114582.

Co-authored-by: Antonio Frighetto <me@antoniofrighetto.com>

### CODE REVIEW

**Review by nikic — APPROVED** [review]
LGTM. Flags were already intersected in the methods that take a fixed number of operands, but the generic methods were missed.

**Comment by dtcxzyw** [comment]
@antoniofrighetto You can reland #112354 now.

**Comment by antoniofrighetto** [comment]
> @antoniofrighetto You can reland #112354 now.

Thanks for fixing this.

**Comment by RKSimon** [comment]
Thanks @antoniofrighetto and @dtcxzyw

**Pull request merged**
