### PR TITLE
[compiler-rt][tests] Make this test case pass on AArch64

### PR DESCRIPTION
**Pull request by pawosm-arm**
See also D92832 and GCC bug https://gcc.gnu.org/bugzilla/show_bug.cgi?id=80878

### CODE REVIEW

**Comment by davemgreen** [comment]
Do you have more details about why this is unsupported? Is it due to i128 atomics and constants? Could just TEST_16 be disabled? I tried to run it locally but I don't think this test ran.

**Comment by pawosm-arm** [comment]
> Do you have more details about why this is unsupported? Is it due to i128 atomics and constants? Could just TEST_16 be disabled? I tried to run it locally but I don't think this test ran.

It doesn't surprise me, I'm using a very specific set of flags for compiler-rt, that make it truly contain atomic (needed for Flang OpenMP experiments with atomics):

```
    -DCOMPILER_RT_DEFAULT_TARGET_ARCH=AArch64
    -DCOMPILER_RT_BUILD_SANITIZERS=OFF
    -DCOMPILER_RT_BUILD_LIBFUZZER=ON
    -DCOMPILER_RT_BUILD_ORC=OFF
    -DCOMPILER_RT_USE_LIBCXX=ON
    -DCOMPILER_RT_BUILD_BUILTINS=ON
    -DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON
    -DCOMPILER_RT_EXCLUDE_ATOMIC_BUILTIN=OFF
    -DCOMPILER_RT_BUILD_STANDALONE_LIBATOMIC=OFF
    -DCOMPILER_RT_USE_ATOMIC_LIBRARY=ON
    -DCOMPILER_RT_USE_LLVM_UNWINDER=OFF
```
Building it whith `-DCOMPILER_RT_USE_BUILTINS_LIBRARY=ON` is particularly tricky, it requires bootstrap compiler-rt built with `-DCOMPILER_RT_BUILD_BUILTINS=ON`.

**Comment by davemgreen** [comment]
Does it fix the test to remove the const from this line:?
```
__attribute__((aligned(16))) static const char data[] = {
```
Atomic loads from a constant address potentially needing to store/cas has always been an issue, but (hopefully) doesn't come up very often as it usually doesn't make a lot of sense. That would allow us to keep the test coverage from this test, which otherwise looks useful.

**Comment by pawosm-arm** [comment]
> Does it fix the test to remove the const from this line:?
> 
> ```
> __attribute__((aligned(16))) static const char data[] = {
> ```
> 
> Atomic loads from a constant address potentially needing to store/cas has always been an issue, but (hopefully) doesn't come up very often as it usually doesn't make a lot of sense. That would allow us to keep the test coverage from this test, which otherwise looks useful.

The const removal is what we do in house to make CI all green. But after our discussion couple of weeks ago I somewhat remembered that it would be better to mark this test case unsupported on AArch64, hence this patch.

**Comment by davemgreen** [comment]
Hmm. This doesn't seem to be a test for whether you can do an atomic load from constant memory, but just a test for atomic loads. I think we can remove the const and the test will make more sense.

**Comment by pawosm-arm** [comment]
> Hmm. This doesn't seem to be a test for whether you can do an atomic load from constant memory, but just a test for atomic loads. I think we can remove the const and the test will make more sense.

Done.

**Comment by pawosm-arm** [comment]
> ⚠️ C/C++ code formatter, clang-format found issues in your code. ⚠️
> 
> You can test this locally with the following command:
> View the diff from clang-format here.

The clang-format issue is not of our concern here.

**Review by davemgreen — APPROVED** [review]
Thanks. LGTM

**Pull request merged**
