### PR TITLE
[GISel] Convert zext nneg to sext if it is cheaper

### PR DESCRIPTION
**Pull request by dtcxzyw**
The logic is copied from SelectionDAGBuilder:
https://github.com/llvm/llvm-project/blob/32546bd2ff822df2419589a03747c6d83415a59e/llvm/lib/CodeGen/SelectionDAG/SelectionDAGBuilder.cpp#L3829-L3836

### CODE REVIEW

**Comment by dtcxzyw** [comment]
> Why is the DAG doing this transform in the builder and not in the combiner?
> 
> ```
> def nneg_zext : GICombineRule<
>    (defs root:$root, build_fn_matchinfo:$matchinfo),
>    (match (G_ZEXT $root, $x, (MIFlags NonNeg)),
>    [{ return Helper.matchNonNegZext(${root}, ${matchinfo}); }]),
>    (apply [{ Helper.applyBuildFnMO(${root}, ${matchinfo}); }])>;
> ```

@topperc

**Comment by arsenm** [comment]
I really do not like these optimizations getting snuck into the DAG builder / IRTranslator. They should do their best to preserve the original IR

**Comment by dtcxzyw** [comment]
> I really do not like these optimizations getting snuck into the DAG builder / IRTranslator. They should do their best to preserve the original IR

Alright, I will post an alternative patch as @tschuett suggested.

**Comment by tschuett** [comment]
The pattern goes in Combine.td. The C++ goes into CombinerHelper. Ping me.

**Comment by dtcxzyw** [comment]
Closing in favor of https://github.com/llvm/llvm-project/pull/93856.

**Pull request closed without merging**
