### PR TITLE
[libc++] Specialize unique_ptr for the default deleter

### PR DESCRIPTION
**Pull request by zmodem**
As mentioned in #93069, the compressed_pair used for storing the deleter in unique_ptr contributes significantly to debug info size.

It seems that the best solution for that will be https://github.com/llvm/llvm-project/pull/76756 ("Use [[no_unique_address]] in place of __compressed_pair") However, that is blocked on supporting old Clang revisions (maybe not for much longer?) and LLDB support (https://github.com/llvm/llvm-project/pull/93809 is in progress, but do we also need to wait for it to ship, and how "far" down the pipe?).

In the meantime, another idea (from @cjdb I think) is to provide a specialization of unique_ptr for the default deleter case, which avoids the need to store the deleter at all.

I've experimented with a patch, and learned a few things:

- A specialization such as `unique_ptr<_Tp, default_delete<_Tp>>` would be ambiguous with the `unique_ptr<_Tp[], _Dp>` specialization for array types (they're "the same amount of specialized"). So in the patch I only specialized for non-array types, which are the most common.
- We still need to go through the default deleter in `reset()`, since T may have a private destructor and friend declaration for `std::default_delete<T>`

Using the patch to build Chromium for Windows,

- Build time seems about the same (maybe reduced a bit, but I didn't measure carefully)
- Total .obj file size reduced 1.9%
- chrome.dll.pdb size reduced 2.5%
- The type information size in the PDB reduced 4.8%

I had hoped for more, but removing 4.8% of the type info is still a good chunk of bytes, and maybe it's possible to improve things further.

@rnk @cjdb @ldionne @philnik777 what do you think?

### CODE REVIEW

**Comment by philnik777** [comment]
The plan is to ship https://github.com/llvm/llvm-project/pull/76756 early in the next release cycle. I don't think we need to wait for LLDB. The issue exists only in assertions builds (i.e. most users wouldn't have LLDB crashing on them) and we haven't waited for LLDB before to update their pretty printers. As long as the issue is fixed in the same release cycle this should be absolutely fine. Given that, I don't think we want to walk this path.

What's with the fuzz about replacing `__compressed_pair` recently anyways? It's not like this is a new issue in any way. Or maybe I just perceive it as recent for some reason, IDK.

**Comment by zmodem** [comment]
> The plan is to ship #76756 early in the next release cycle. I don't think we need to wait for LLDB.

Great, thanks for confirming.

> What's with the fuzz about replacing `__compressed_pair` recently anyways?

PDB files have a 2^31 byte limit on the type info, which Chromium is approaching (crbug.com/338094922). __compressed_pair seems to account for a large portion of the type info size in our builds.

Plus clang-cl finally getting support for no_unique_address last years means that's not blocking things anymore.

**Comment by Michael137** [comment]
Just to update re. LLDB support, there's two issues outstanding:
1. The assertions during AST lowering that @philnik777 mentioned (this is mainly a problem for the LLDB buildbot maintainers)
2. The data-formatters don't support the new layout yet (this is a more serious issue, but not hard to address)

I've put up a draft review for the formatters in https://github.com/llvm/llvm-project/pull/96538. The assertion failures should be addressed by https://github.com/llvm/llvm-project/pull/96422. I'm actively working on getting these ready to land by the time https://github.com/llvm/llvm-project/pull/76756 is ready.

**Comment by philnik777** [comment]
@Michael137 Thanks for all the work on this! I'm pretty sure this whole effort will drastically improve the QoI and maintainability of libc++. BTW sorry for being responsible for a significant amount of the additional complexity due to changed layouts in the pretty printers. Do you have any plans to remove support for old versions of the layouts at any point?

@zmodem Thanks for the info. Would you be able to also provide numbers for https://github.com/llvm/llvm-project/pull/76756? Something in the release notes like "this change resulted in a 5% decrease in debug info size for Chromium" always sounds great.

I hope it's good enough if https://github.com/llvm/llvm-project/pull/76756 lands in ~2 months? It would also be great if you could run the patch through its paces within google.

P.S. I noticed that my wording on "not caring about the pretty printers" was a bit misleading - I meant that we don't care to wait for them to propagate, not that we don't care that they work within the same release.

**Comment by Michael137** [comment]
> @Michael137 Thanks for all the work on this! I'm pretty sure this whole effort will drastically improve the QoI and maintainability of libc++. BTW sorry for being responsible for a significant amount of the additional complexity due to changed layouts in the pretty printers. Do you have any plans to remove support for old versions of the layouts at any point?

No problem! The way the pretty-printers are written makes them susceptible to these kinds of changes. We'll probably maintain both layouts for some time, but we already do that for other types like `std::string` too. With some refactoring I don't think it's going to be a big problem. (side-note, a nice benefit from the new simpler layout is that we'll be able to avoid bugs like https://github.com/llvm/llvm-project/issues/68396#issuecomment-1752092231).

**Comment by zmodem** [comment]
> @zmodem Thanks for the info. Would you be able to also provide numbers for #76756? Something in the release notes like "this change resulted in a 5% decrease in debug info size for Chromium" always sounds great.

Sure! Compared to libc++ head, applying that:

- Total .obj file size reduced 5.5%
- chrome.dll.pdb size reduced 5.1%
- The type information size in the PDB reduced 10.6%

Those are very appealing numbers for us :)

These are my local build time measurements:

With head:

```
real    37m23.793s
user    4121m5.728s
sys     408m9.989s
```

With my patch:

```
real    36m47.368s
user    4051m46.384s
sys     401m42.658s
```

With #76756:

```
real    36m4.842s
user    3970m57.689s
sys     398m46.022s
```

Even if these measurements are not scientific, the numbers point in the right direction.

> 
> I hope it's good enough if #76756 lands in ~2 months? 

Yes, that's good for us.

> It would also be great if you could run the patch through its paces within google.

I've asked folks more familiar with the internal processes to take a look.

**Comment by ldionne** [comment]
Just as a matter of process, let's close this if we are confident that we will not be pursuing it, just to keep the review queue tidy :-)

**Comment by zmodem** [comment]
> > It would also be great if you could run the patch through its paces within google.
> 
> I've asked folks more familiar with the internal processes to take a look.

Following up on this, #76756 seems to work fine internally. The only issues I saw were some tests relying on pretty-printing std::string, but that should get fixed with the LLDB patches.

I don't have any overall statistics, but we're seeing some binaries shrink by 3-7% in non-optimized builds, and 2-4% for optimized. At scale, that's a huge improvement.

**Comment by philnik777** [comment]
@zmodem Thanks for the info! It's good to hear that there doesn't seem to be any obvious problems with the patch. I'm quite surprised that it makes a difference for optimized builds. Does that show in actual reduced code, or is that other information, like symbol tables? I absolutely agree that this is a huge improvement. I didn't think it would have that much of an impact. And we can do even more cleanups after that, although I don't expect nearly the impact of replacing `__compressed_pair` itself.

**Pull request closed without merging**
