### PR TITLE
release/18.x: [X86][FP16] Do not create VBROADCAST_LOAD for f16 without AVX2 (#91125)

### PR DESCRIPTION
**Pull request by phoebewang**

### CODE REVIEW

**Review by RKSimon — APPROVED** [review]
LGTM

**Comment by andrewrk** [comment]
Thanks!

**Comment by tstellar** [comment]
@phoebewang (or anyone else). If you would like to add a note about this fix in the release notes (completely optional). Please reply to this comment with a one or two sentence description of the fix.  When you are done, please add the release:note label to this PR.

**Comment by phoebewang** [comment]
> @phoebewang (or anyone else). If you would like to add a note about this fix in the release notes (completely optional). Please reply to this comment with a one or two sentence description of the fix. When you are done, please add the release:note label to this PR.

This patch fixes a bug that tries to do VBROADCAST_LOAD for f16 without AVX2.

**Pull request merged**
