### PR TITLE
[Sema] Don't drop weak_import from a declaration that follows a declaration directly contained in a linkage-specification

### PR DESCRIPTION
**Pull request by ahatanak**
Only drop it if the declaration follows a definition. I believe this is what 33e022650adee965c65f9aea086ee74f3fd1bad5 was trying to do.

rdar://61865848

### CODE REVIEW

**Review by rjmccall — COMMENTED** [review]
I think you're right about the intended logic being to check for a definition, especially given the wording of the warning.  IIRC, we didn't have high-level functions for checking some of these conditions at the time, so looking directly at the storage-class specifier would have been common.

With that said, I think you need to check if a definition exists at all and not just whether the last declaration is that definition.

**Comment by ahatanak** [comment]
> With that said, I think you need to check if a definition exists at all and not just whether the last declaration is that definition.

Note that `checkNewAttributesAfterDef`, which is called right before the check, removes attributes on `New` if there was a full definition. The updated patch just looks for any previously declared tentative definition.

**Comment by ahatanak** [comment]
The updated patch checks that the decl isn't `DeclarationOnly` to make it clear that we are looking for all definitions although we know we won't find any full definitions.

**Review by rjmccall — APPROVED** [review]
LGTM.  The (existing) diagnostic wording does seem a little awkward, so if you want to put effort into cleaning that up, it'd be welcome, but I won't hold up this fix.

**Review by rjmccall — APPROVED** [review]

**Pull request merged**
