### PR TITLE
[RISCV] Always emit relocations for resolved symbols and relax

### PR DESCRIPTION
**Pull request by andcarminati**
If relaxation is not itended, it can be disabled in the linker. Also, we cannot trust Subtarget features here, because it may be empty in case of LTO codegen, preventing relaxations.

Also forward --no-relax option to linker.

### CODE REVIEW

**Comment by andcarminati** [comment]
Hi @topperc , just another idea to solve the problem, mostly to discuss!

Regards.

**Comment by jrtc27** [comment]
> Also, we cannot trust Subtarget features here, because it may be empty in case of LTO codegen, preventing relaxations.

And that's the problem. It's vital that we have the information. Anything else is just a hack that papers over the fundamental issue.

**Comment by andcarminati** [comment]
> As far as I can tell this is pointless. If you want relaxation you need R_RISCV_RELAX and R_RISC_ALIGN relocations to be emitted. If you don't want relaxation you don't need these. Therefore it seems like all this does is emit a whole bunch of useless relocations for the case when you're not enabling relaxation at compile time and thus cannot possibly enable it at link time?

Hi @jrtc27, thank you for your comment, understood your point. For relaxation, I think we need also the branch relocation/anything relative, as we are removing some lui instructions. My original idea was based on the case that relaxation is a default ON feature for RISCV, but I honestly don't know the use cases to disable it.

Just to follow the discussion, I can consider the following use case:

clang [...] -c -o myobject.o (just compile)
clang [...] my0bject.o -o myobject.elf -mno-relax (linking)

In this case, myobject.elf will be relaxed, the -mno-relax will be silently ignored.

Maybe we have two different things to handle.

Regards.

**Comment by andcarminati** [comment]
> For the driver BareMetal.cpp change, claiming `-mno-relax` should not be done for non-RISCV targets (e.g. AArch32).

Thank you for the update. I updated the PR reverting the backend part and addressing this issue just for RISC-V.

**Comment by MaskRay** [comment]
The current patch doesn't do what the title implies ("Always emit relocations for resolved ").

**Comment by andcarminati** [comment]
> The current patch doesn't do what the title implies ("Always emit relocations for resolved ").

Sure, I will close this PR because I created another one targeting just this case: https://github.com/llvm/llvm-project/pull/76432

Regards.

**Pull request closed without merging**
