### PR TITLE
[flang] Allow derf as alternate spelling for erf

### PR DESCRIPTION
**Pull request by DavidTruby**
This patch adds derf as an alternate spelling for the erf intrinsic.
This spelling is supported by multiple other compilers and used by WRF.

### CODE REVIEW

**Comment by pawosm-arm** [comment]
> DERF is mentioned as a specific name extension of ERF for argument and return type Real(kind=8). https://gcc.gnu.org/onlinedocs/gfortran/ERF.html
> 
> Is the usage in wrf and other codes you saw an alias of ERF for all Real kinds or specifically for Real(kind=8)?

NB, it must match the type of other `D`-prefixed intrinsics as it is used in an expression like this one:

```
(1.-DERF(5.D+0/DSQRT(2.D+0)))*0.5
```

**Comment by klausler** [comment]
Fortran extension intrinsic functions that start with `D` have historically been DOUBLE PRECISION versions of real intrinsics.  See the`static const SpecificIntrinsicInterface specificIntrinsicFunction` table in `intrinsics.cpp` for other examples, and for the correct way to implement further examples.

**Review by klausler — CHANGES_REQUESTED** [review]
This is basically all wrong.

**Comment by DavidTruby** [comment]
I've reimplemented this using specificIntrinsicFunction

**Review by klausler — APPROVED** [review]

**Pull request merged**
