### PR TITLE
[GlobalISel] Enhance iPTR type support in SDAG patterns

### PR DESCRIPTION
**Pull request by e-kud**
This adds a check for integer types covered by iPTR type. It is dictated by the fact that insertelt node has SDTCisPtrTy constraint on the index operand. At the same time, this constraint can't be replaced by SDTCisInt as it doesn't reduce the amount of possible types to the only one possible.

### CODE REVIEW

**Comment by arsenm** [comment]
> It is dictated by the fact that insertelt node has SDTCisPtrTy 

This is just a bug, the vector index type is separate from the pointer type

**Comment by e-kud** [comment]
> This is just a bug, the vector index type is separate from the pointer type

We can't simply change the constrain in general
```
def SDTVecInsert : SDTypeProfile<1, 3, [    // vector insert
  SDTCisEltOfVec<2, 1>, SDTCisSameAs<0, 1>, SDTCisPtrTy<3>
]>;
```
Most of the target have already accepted idea of `iPTR` index.  To fix the bug, all targets should be fixed first.

Then I tried to change the element type to i32 only on X86 (we need some common type for 32bit and 64bit platforms). It caused a lot of regressions since we have some combines that assume only for `i64` indices. Some of them are easy to fix, some of them aren't as different combines become active.

I'll try to solve them one by one before migrating to i32 index type. If anyone has better ideas on how to proceed, I'd appreciate it. Closing for now, as migration to `i32` seems feasible.

**Comment by e-kud** [comment]
> This is just a bug, the vector index type is separate from the pointer type

@arsenm if this is a bug it's already buried too deep.
```
/// Returns the type to be used for the index operand vector operations. By
/// default we assume it will have the same size as an address space 0
/// pointer.
virtual unsigned getVectorIdxWidth(const DataLayout &DL) const {
  return DL.getPointerSizeInBits(0);
}

/// Returns the type to be used for the index operand of:
/// ISD::INSERT_VECTOR_ELT, ISD::EXTRACT_VECTOR_ELT,
/// ISD::INSERT_SUBVECTOR, and ISD::EXTRACT_SUBVECTOR
MVT getVectorIdxTy(const DataLayout &DL) const {
  return MVT::getIntegerVT(getVectorIdxWidth(DL));
}

/// Returns the type to be used for the index operand of:
/// G_INSERT_VECTOR_ELT, G_EXTRACT_VECTOR_ELT,
/// G_INSERT_SUBVECTOR, and G_EXTRACT_SUBVECTOR
LLT getVectorIdxLLT(const DataLayout &DL) const {
  return LLT::scalar(getVectorIdxWidth(DL));
}
```

So each target that has vectors implemented in SDAG must overwrite default interface and whole SDAG implementation to enable vector patterns in GlobalISel. It looks like supporting `iPTR` as a HW dependent integer type could be more straightforward in terms of GlobalISel adoption. What do you think?

cc @aemerson @davemgreen @topperc

**Comment by arsenm** [comment]
> > This is just a bug, the vector index type is separate from the pointer type
> 
> @arsenm if this is a bug it's already buried too deep.
> 

The default implementation happens to use the address space 0 pointer type, that's not very deep.

> So each target that has vectors implemented in SDAG must overwrite default interface and whole SDAG implementation to enable vector patterns in GlobalISel. 

I think we should just remove the SDTCisPtrTy constraint from the vector nodes. It's simply not correct. If we wanted to, we could have a parallel mechanism for the vector index type

**Comment by e-kud** [comment]
> I think we should just remove the SDTCisPtrTy constraint from the vector nodes. It's simply not correct. If we wanted to, we could have a parallel mechanism for the vector index type

Yes, this is an entry point. After removing or replacing it with `SDTCisIntTy` we start seeing a problem that some patterns couldn't be generated because of `Could not infer all types in pattern!`. It happens because now several types are available for an operand. It is fixable for targets with one type of pointers: 32-bit or 64-bit, we can simply add `i32` or `i64` in patterns, not a problem.

For targets with multi-width pointers we need to set a type `iPTR` so it will always match the result of `getVectorIdxTy` as by default we return the width of the pointer type. Or we need to loop over all pointer widths.

Now, having `iPTR` we can't import patterns because we bail out with `unsupported type` from `addTypeCheckPredicate`.

About x86 in particular. Let's override `getVectorIdxWidth`, so we need to return `i32` so it works with 32 and 64 bit platforms. When I've done it, there is a bunch of tests that start failing because some a row of combines stopped working as they were focused on 64 bit indices. I'm not sure whether it's worth it,

**Pull request closed without merging**
