### PR TITLE
[HLSL]  standardize builtin unit tests

### PR DESCRIPTION
**Pull request by farzonl**
This PR brings best practices mentioned to me on other prs and adds them to the existing builtin tests.

Note to reviewers: I put this up in two commits because the clang-format changes is making it hard to tell what actually changed.
use the first commit to check for correctness.

### CODE REVIEW

**Comment by pow2clk** [comment]
Do we have the suggestions that this is responding to written down somewhere? I think it would be useful to have those guidelines for anyone who might want to contribute HLSL tests. At any rate, I'd like to know the ones that this is in response to.

**Comment by damyanp** [comment]
> Do we have the suggestions that this is responding to written down somewhere? I think it would be useful to have those guidelines for anyone who might want to contribute HLSL tests. At any rate, I'd like to know the ones that this is in response to.

Following on from this, how would someone reproduce the clang formatting you got here?  It sounds like you had to explicitly turn off comment reflowing to make it work as intended?

**Comment by farzonl** [comment]
> Do we have the suggestions that this is responding to written down somewhere? I think it would be useful to have those guidelines for anyone who might want to contribute HLSL tests. At any rate, I'd like to know the ones that this is in response to.
@pow2clk 
below are the three comments that inspired this pr:
https://github.com/llvm/llvm-project/pull/83315#discussion_r1506485695
https://github.com/llvm/llvm-project/pull/81190#discussion_r1491951377
https://github.com/llvm/llvm-project/pull/82827#discussion_r1501220875

These were on the fly comments so we don't have  guidelines yet, but that could be something nice to add. I'll talk to @bogner  and find out where to add that.

**Comment by farzonl** [comment]
> > Do we have the suggestions that this is responding to written down somewhere? I think it would be useful to have those guidelines for anyone who might want to contribute HLSL tests. At any rate, I'd like to know the ones that this is in response to.
> 
> Following on from this, how would someone reproduce the clang formatting you got here? It sounds like you had to explicitly turn off comment reflowing to make it work as intended?

@damyanp that is correct I added `ReflowComments: false` to clang/test/.clang-format and I removed `DisableFormat` Then just ran  clang-format on the subset of tests I was already touching.

**Comment by farzonl** [comment]
> Do we have the suggestions that this is responding to written down somewhere? I think it would be useful to have those guidelines for anyone who might want to contribute HLSL tests. At any rate, I'd like to know the ones that this is in response to.

After consulting with some folks. clang format in this case is just going to be a one off. It doesn't make sense to have different contribution guidelines from the rest of clang. There are times we want the formatting to be off. These tests aren't one of those cases.

**Comment by bogner** [comment]
If we want to talk about guidelines for clang-formatting tests in general we should probably bring it up with the wider LLVM community on discourse. The de facto standard today is that tests should be well formatted like anything else unless there's a good reason not to, but this isn't written down or strongly enforced as far as I know. It might be worth bringing it up to the community to change the test folder .clang-format configs to just disable reflow comments - as far as I can tell that'd be a net positive.

**Review by bogner — APPROVED** [review]

**Review by damyanp — APPROVED** [review]

**Review by llvm-beanz — APPROVED** [review]

**Pull request merged**
