### PR TITLE
[MinGW] MinGW dynamicbase 

### PR DESCRIPTION
**Pull request by xu-chiheng**

### CODE REVIEW

**Review by mstorsjo — CHANGES_REQUESTED** [review]
This is not necessary.

Since 514b4e191d5f46de8e142fe216e677a35fa9c4bb in binutils (https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=514b4e191d5f46de8e142fe216e677a35fa9c4bb), dynamicbase is enabled by default. Also since e72403f96de7f1c681acd5968f72aa986412dfce in llvm-project, LLD also does the same.

**Review by mstorsjo — CHANGES_REQUESTED** [review]
No, you do not need to do this. There's no need to add `--dynamicbase` manually in Clang. As I already posted, both ld.bfd and ld.lld default to `--dynamicbase` enabled since 2020.

**Comment by xu-chiheng** [comment]
> Also

In Cygwin with binutils 2.41,  --dynamicbase make a difference, so I thought MinGW also need it.

**Comment by xu-chiheng** [comment]
> > In Cygwin with binutils 2.41, --dynamicbase make a difference, so I thought MinGW also need it.
> 
> No, MinGW does not need it, as it has been enabled by default since binutils 2.36.
> 
> Apparently that change, https://sourceware.org/git/?p=binutils-gdb.git;a=commitdiff;h=514b4e191d5f46de8e142fe216e677a35fa9c4bb, didn't apply to Cygwin but only to MinGW. But if Cygwin works with dynamicbase (I think it might have issues with it but I'm not sure?) then perhaps binutils should be changed to enable dynamicbase by default there, instead of changing compilers to pass the option by default.

Cygwin GCC and Clang must use dynamicbase, otherwise, there are errors like :
      0 [main] clang-17 1506 child_info_fork::abort: \??\D:\cygwin64-packages\clang\bin\cygclangLex-17git.dll: Loaded to different address: parent(0x16E0000) != child(0x5C12D0000)
clang++: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable
      0 [main] clang-17 1507 child_info_fork::abort: \??\D:\cygwin64-packages\clang\bin\cygLLVMRISCVCodeGen-17git.dll: Loaded to different address: parent(0xE60000) != child(0xEC0000)
clang++: error: unable to execute command: posix_spawn failed: Resource temporarily unavailable

**Pull request closed without merging**
