### PR TITLE
[ObjC] Defer to the LLVM backend for unaligned atomic load and stores

### PR DESCRIPTION
**Pull request by AZero13**
LLVM can codegen correctly for atomics of any alignment in IR, on any architecture (via using libcalls when necessary).

So, the ObjC code's hasUnalignedAtomics can be removed. We can use copyStruct if the size is too big.

### CODE REVIEW

**Comment by jyknight** [comment]
This is incorrect: X86 does not support unaligned atomics.

However, LLVM can codegen correctly for atomics of any alignment in IR, on any architecture (via using libcalls when necessary). So the ObjC code's `hasUnalignedAtomics` could be removed, and let the backend deal with it, if that was desirable.

**Comment by jyknight** [comment]
Does this cause an ABI incompatibility? E.g. if we have a case where an existing object calls copyStruct on a given object (which presumably has its own internal mutex), and a newly compiled object file calls `__atomic_load` on the same object, implemented with its own internal mutex, the operations won't be atomic w.r.t. each-other.

I don't know enough about ObjC codegen stuff to be able to say if there are mitigating factors that make this OK (e.g. if it's all within one TU?).

Sidenote: please avoid rebase, amend, and force-pushing, because it makes it hard to review what's been changed -- instead, just keep adding more commits to your pull-request branch.

**Comment by AtariDreams** [comment]
> Does this cause an ABI incompatibility? E.g. if we have a case where an existing object calls copyStruct on a given object (which presumably has its own internal mutex), and a newly compiled object file calls `__atomic_load` on the same object, implemented with its own internal mutex, the operations won't be atomic w.r.t. each-other.
> 
> I don't know enough about ObjC codegen stuff to be able to say if there are mitigating factors that make this OK (e.g. if it's all within one TU?).
> 
> Sidenote: please avoid rebase, amend, and force-pushing, because it makes it hard to review what's been changed -- instead, just keep adding more commits to your pull-request branch.

Don't know but everything passed now!

**Comment by jyknight** [comment]
> Don't know but everything passed now!

Well, I'm not an expert on the objc codegen...but unless you, or someone else, can explain that my concern is invalid, I think this change cannot be made.

**Pull request closed without merging**
