### PR TITLE
[lldb][Docs] Make formatting regular in lldb-gdb-remote.txt

### PR DESCRIPTION
**Pull request by DavidSpickett**
If someone (aka me) wanted to convert this into another format (aka Markdown), these changes mean you can more easily script that conversion.

### CODE REVIEW

**Comment by DavidSpickett** [comment]
Subsequent PRs will build on this:
* Enable Markdown support in the website build.
* Use a script to convert this file to Markdown.
* Hand correct the result.

So we:
1. Have this on the website, just like GDB's protocol specs and
2. It's in a format that's easier to contribute to.

**Comment by JDevlieghere** [comment]
> Subsequent PRs will build on this:
> 
> * Enable Markdown support in the website build.

I added markdown support in 8b95bd3310c126e76e0714bea6003a9b1aa739fb but it was subsequently removed again in d03b04f211e73c2f59ba5dc6a6a8c777de001ad6 (I wasn't added as a reviewer, so I found out after the fact). We can probably just reland the original commit to make that work.

**Comment by JDevlieghere** [comment]
+1 on making this available on the website. Unless the goal is to preserve both the textual and the markdown format, I'm not sure there's a whole lot of value in landing this. Maybe we can avoid churn and jump straight ahead to the markdown version?

**Review by jasonmolenda — APPROVED** [review]
Yes please, very long overdue, I've felt bad about not trying to do something here myself.

**Comment by DavidSpickett** [comment]
I'll include this as a commit in a larger PR.

**Comment by DavidSpickett** [comment]
Opened https://github.com/llvm/llvm-project/pull/89718 instead, which has all the conversion steps in it.

**Pull request closed without merging**
