### PR TITLE
Adding memref normalization of affine.prefetch

### PR DESCRIPTION
**Pull request by AlexandreEichenberger**
As of now, `affine.prefetch` cannot be memref normalized; namely the memory reference being prefetch has to be a simple constant-offset based indexing.

For example:
```mlir
func.func @prefetch_normalize(%arg0: memref<512xf32, affine_map<(d0) -> (d0 floordiv 32, d0 mod 32)>>) -> () {
  affine.for %arg3 = 0 to 8  {
    affine.prefetch %arg0[%arg3], read, locality<3>, data : memref<512xf32, affine_map<(d0) -> (d0 floordiv 32, d0 mod 32)>>
  }
  return
}
```
 
cannot be normalized.

Using this PR (which simply add the `MemRefsNormalizable` property to the `affine.prefetch` operation) proper code is being generated, as shown below:

```mlir
func.func @prefetch_normalize(%arg0: memref<16x32xf32>) {
    affine.for %arg1 = 0 to 8 {
      affine.prefetch %arg0[%arg1 floordiv 32, %arg1 mod 32], read, locality<3>, data : memref<16x32xf32>
    }
    return
}
```

PR include a new lit test.

### CODE REVIEW

**Comment by AlexandreEichenberger** [comment]
Not an expert, the log indicates
```
_bk;t=1713859797397C:\ws\src\llvm\..\mlir\include\mlir/IR/BuiltinAttributeInterfaces.h(159): fatal error C1060: compiler is out of heap space
```
so I assume that restarting the test should handle this.

**Comment by AlexandreEichenberger** [comment]
@bondhugula any objections? Since load/store ops are already normalizable, feels like having prefetch too is not a big deal? We encounter memory layouts with floordiv/ceildiv/mods (for tiling).

**Comment by AlexandreEichenberger** [comment]
@bondhugula @ftynse no review for about a week, do you think someone could look at it?

**Review by ftynse — APPROVED** [review]

**Comment by AlexandreEichenberger** [comment]
@ftynse Used the feedback you gave me last time for another PR for a smooth sailing this time. Thanks for the review.

**Pull request merged**
