### PR TITLE
[CaptureTracking] Do not capture compares of same object

### PR DESCRIPTION
**Pull request by caojoshua**
Compares of the same object do not leak any bits.

This patch introduces getUnderlyingObjectLookThrough. It looks at the
output of getUnderlyingObject. If it is a PHI, it looks at all the
incoming underlying objects. If all those objects are the same, or the
original PHI, we determine that there is a new underlying object. This
is similar to getUnderlyingObjects, but provides a more efficient way to
find a single underlying object.

This is an attempt at solving huge compile time regressions in
https://reviews.llvm.org/D152082. First, we only look through a single
PHI, not nested PHIs. Second, we only use one callsite. There are likely
other callsites that could take advantage of this over the vanilla
getUnderlyingObjects. We need to be careful about compile times. Adding
this to BasicAA::aliasCheck increases compile times by 3% on local
builds.

This was inspired by the issues in
https://github.com/rust-lang/rust/issues/111603. rustc used to generate
pointers comparisons that this patch can identify as non capturing. The
code emission was changed in rustc to avoid this behavior, but this
patch can help with other cases of pointer inductions.

### CODE REVIEW

**Comment by caojoshua** [comment]
Original review from https://reviews.llvm.org/D152241

**Comment by caojoshua** [comment]
This patch is incompatible with [this code block](https://github.com/llvm/llvm-project/blob/6561efe142ae2a5d434ff646319b0bfb1dd39dee/llvm/lib/Analysis/InstructionSimplify.cpp#L2794-L2835), which simplifies non-capturing pointer comparisons to false.

**Comment by nikic** [comment]
> This patch is incompatible with [this code block](https://github.com/llvm/llvm-project/blob/6561efe142ae2a5d434ff646319b0bfb1dd39dee/llvm/lib/Analysis/InstructionSimplify.cpp#L2794-L2835), which simplifies non-capturing pointer comparisons to false.

Yes, this fold is known to be buggy. The right way to do it would be to extend https://github.com/llvm/llvm-project/blob/79e62315be5b762f399e98c0b638e682eac66322/llvm/lib/Transforms/InstCombine/InstCombineCompares.cpp#L833 to handle allocator calls. Pretty sure I had a patch for this ... somewhere on phabricator.

**Comment by caojoshua** [comment]
Closing since I probably won't be working on this patch. Anyone feel free to take this work and extend it.

**Pull request closed without merging**
