### PR TITLE
Add llvm::min/max_element and use it in llvm/ and mlir/ directories.

### PR DESCRIPTION
**Pull request by jlebar**
For some reason this was missing from STLExtras.

### CODE REVIEW

**Review by kuhar — APPROVED** [review]
Usually I prefer separating STLExtras changes from updating the codebase to make things easier to revert, but this looks simple enough to do in one step IMO

**Review by joker-eph — APPROVED** [review]
I wish the standard librairies would provide these shortcuts!

**Comment by jlebar** [comment]
Thank you for the reviews!

**Comment by jlebar** [comment]
Hm, I got a bazillion buildbot errors from this.  Weird, because I did test the build locally before I pushed it.

Back when we used phab there was a bot that built PRs before they were checked in; do we not have that anymore?

**Comment by jlebar** [comment]
I mean clearly this is not going to build, https://github.com/llvm/llvm-project/pull/84678/files#diff-0dbd9d956d4dcee3f73f026710249c7ccf6a131aa98a384f0fa2da1670174368R1073

**Comment by jlebar** [comment]
Pushed 099be86433a69f264aeb70e512ba1bbd0c7aefd7

**Comment by joker-eph** [comment]
The bot has been migrated to GitHub, and it failed on this PR :)

Screenshot 2024-03-10 at 9 28 21 PM

**Pull request merged**
