### PR TITLE
Use %errc to get text for system errors

### PR DESCRIPTION
**Pull request by perry-ca**
Several lit tests look for messages with text generated from strerror() such as "no such file or directory".  The value can change slightly from system to system.  Use the llvm-lit macro `%errc_<ERRCODE>` instead.

This was really noticable on z/OS because the generated text includes an error code as well as the text.

### CODE REVIEW

**Comment by DavidSpickett** [comment]
I think https://github.com/llvm/llvm-project/blob/5a191e3cd904b5fee202569e54fe04f91f1a697f/llvm/utils/lit/lit/llvm/config.py#L411 works such that if the messages cannot be found (cross compiling and such) we default to asking Python what it thinks they should be.

I wondered if these tests needed some "UNSUPPORTED: no_errc" but this means that they don't.

**Comment by DavidSpickett** [comment]
CI failure is:
```
_bk;t=1727216861348Timed Out Tests (1):
_bk;t=1727216861348  lldb-api :: functionalities/fork/concurrent_vfork/TestConcurrentVFork.py
```

Ignore that it's due to https://github.com/llvm/llvm-project/issues/104609.

**Review by DavidSpickett — APPROVED** [review]
LGTM

**Comment by DavidSpickett** [comment]
Do you have merge permissions? I can merge it for you if not.

**Comment by perry-ca** [comment]
Thanks for the offer David.  I do have permission now.  I held off merging yesterday because the builds were all broken from some other change.  The builds all pass now.  I'll merge it.

**Pull request merged**
