### PR TITLE
[dsymutil][llvm-dwarfutil] Add command line option --deterministic.

### PR DESCRIPTION
**Pull request by avl-llvm**
This patch adds command line option --deterministic <level name> to the dsymutil and llvm-dwarfutil. This option allows generating non-deterministic output in exchange for more parallelism.

--deterministic <level name>
    Specify the desired level of output determinism.
    Valid names are 'full', 'trusted' and 'none'. Defaults to 'full'

   'full'    Generated output should always be deterministic
             (despite of any assumptions).
   'trusted' Generated output should be deterministic
             assuming input DWARF is consistent.
   'none'    Generated output may not be deterministic.
   
   Note: 'full' mode is equal to 'trusted' currently. Patch implementing 'full' functionality would be submitted separately.

### CODE REVIEW

**Comment by JDevlieghere** [comment]
We care a lot about reproducibility in `dsymutil` and while the lack thereof has been fine while the parallel linker is in development, I don't mean to productive (or support) it. Therefore `dsymutil --linker=parallel` should simply imply `--determinism=full` and there shouldn't be a flag to change that.

**Comment by avl-llvm** [comment]
> We care a lot about reproducibility in `dsymutil` and while the lack thereof has been fine while the parallel linker is in development, I don't mean to productive (or support) it. Therefore `dsymutil --linker=parallel` should simply imply `--determinism=full` and there shouldn't be a flag to change that.

Do you think that option switching deterministic behavior off is not necessary? This patch keeps default state to be `--determinism=full` but allows to switch it off for the cases where deterministic behavior is not important.

**Comment by JDevlieghere** [comment]
> > We care a lot about reproducibility in `dsymutil` and while the lack thereof has been fine while the parallel linker is in development, I don't mean to productive (or support) it. Therefore `dsymutil --linker=parallel` should simply imply `--determinism=full` and there shouldn't be a flag to change that.
> 
> Do you think that option switching deterministic behavior off is not necessary? This patch keeps default state to be `--determinism=full` but allows to switch it off for the cases where deterministic behavior is not important.

Yes, I'd rather not have the option at all because having the option means that inevitable someone is going to use it and I'll need to support it...

**Comment by avl-llvm** [comment]
I see. I will to revoke it for now. Thanks.

**Pull request closed without merging**
