### PR TITLE
[mlir][Transforms] `GreedyPatternRewriteDriver`: verify IR

### PR DESCRIPTION
**Pull request by matthias-springer**
This commit adds an additional "expensive check" that verifies the IR before starting a greedy pattern rewriter, after every pattern application and after every folding. (Only if `MLIR_ENABLE_EXPENSIVE_PATTERN_API_CHECKS` is set.)

It also adds an assertion that the `scope` region (part of `GreedyRewriteConfig`) is not being erased as part of the greedy pattern rewrite. That would break the scoping mechanism and the expensive checks.

This commit does not fix any patterns, this is done in separate commits.

### CODE REVIEW

**Comment by matthias-springer** [comment]
Also see comment in #74271: Should we require patterns to generate valid IR? If all patterns are defined in the same component (e.g., canonicalization patterns of the same dialect) and the output is always valid, maybe intermediate invalid IR is OK. But things could get tricky when patterns from other components are mixed into the greedy pattern rewrite and stuff can suddenly break in unexpected ways.

**Review by joker-eph — APPROVED** [review]
Do we already have a bot checking with `MLIR_ENABLE_EXPENSIVE_PATTERN_API_CHECKS`?

**Comment by Hardcode84** [comment]
I have a general question about such checks: Why are they introduced as preprocessor defines (which require rebuilt), and not as some runtime switch (maybe at context level)? Keeping them always enabled is not practical of course, but having to rebuild llvm each time you want to run them doesn't look practical either.

**Comment by joker-eph** [comment]
The context isn't meant to carry "options" like that in general (I don't think there is a precedent?).

For something like "extra checks" that could be defendable maybe, not totally sure.

**Comment by matthias-springer** [comment]
It could be added as an option next to `MLIRContextImpl::allowUnregisteredDialects`. But it would also require changes to `MLIRContext` and `mlir-opt.cpp`. I experimented with that in the beginning.

Another problem with this approach is that there is currently no API to signal a pass failure from the greedy pattern rewrite driver. I currently use `llvm::report_fatal_error` to make sure that `mlir-opt` stops executing. That's not really nice behavior for an `mlir-opt` option.

**Comment by joker-eph** [comment]
The return type of `applyPatternsAndFoldGreedily` is meant to signal failure to converge, which can be acceptable by the user.

**Comment by matthias-springer** [comment]
> Do we already have a bot checking with `MLIR_ENABLE_EXPENSIVE_PATTERN_API_CHECKS`?

Not yet. One concern that I have is that some `MLIR_ENABLE_EXPENSIVE_PATTERN_API_CHECKS` checks can report false positives. The ones that look for "rewrite pattern returned success but IR did not change". The check is implemented by comparing the hash of the operations and there could be hash collisions. In practice, I haven't seen any hash collisions yet. Cloning the IR before every pattern application (to check for true equivalence) could be too expensive and may change the behavior of patterns (if Values get additional uses). What do you think?

**Comment by joker-eph** [comment]
I'm not worried about hash collision for this feature

**Comment by matthias-springer** [comment]
I have to fix 5 more test (some non-trivial), then we can add the new bot:
```
Failed Tests (5):
  MLIR :: Conversion/VectorToSCF/vector-to-scf.mlir
  MLIR :: Dialect/ArmSME/tile-allocation-invalid.mlir
  MLIR :: Dialect/ArmSVE/legalize-vector-storage.mlir
  MLIR :: Dialect/Vector/vector-contract-to-outerproduct-transforms-unsupported.mlir
  MLIR :: Dialect/Vector/vector-warp-distribute.mlir
```

**Pull request merged**
