### PR TITLE
[TTI][WebAssembly] Pairwise reduction expansion

### PR DESCRIPTION
**Pull request by sparker-arm**
WebAssembly doesn't support horizontal operations nor does it have a way of expressing fast-math or reassoc flags, so runtimes are currently unable to use pairwise operations when generating code from the existing shuffle patterns.

This patch allows the backend to select which, arbitary, shuffle pattern to be used per reduction intrinsic. The default behaviour is the same as the existing, which is by splitting the vector into a top and bottom half. The other pattern introduced is for a pairwise shuffle.

WebAssembly enables pairwise reductions for int/fp add/sub.

### CODE REVIEW

**Comment by ppenzin** [comment]
Is there a runtime that is expected to consume this already and how are you planning to disseminate this knowledge? Would it  be a better approach to introduce a standard way of doing this?

**Comment by sparker-arm** [comment]
> Is there a runtime that is expected to consume this already and how are you planning to disseminate this knowledge?

I'm currently working on a patch for AArch64 in V8, I don't _think_ there's been any similar work for other targets there. I guess there could be a risk of breaking some matching for cranelift's `iadd_pairwise` operation, but I haven't looked into it... I will ping those folks.

> Would it be a better approach to introduce a standard way of doing this?

There's a wasm spec post-SIMD-MVP [request](https://github.com/WebAssembly/simd/pull/375) for FP pairwise adds, which is what I would like.

**Review by RKSimon — COMMENTED** [review]
Do we need to check for ordered float reductions?

**Comment by sparker-arm** [comment]
> Do we need to check for ordered float reductions?

If I understand the question correctly, we already do. ExpandReductions will only generate a shuffle for operations that allow reassociation and this is when we can choose our arbitrary shuffle pattern(s).

**Comment by sparker-arm** [comment]
I've changed the scope so that we're now only affecting FADD. This requires that code generators need to implement more pattern matchers, but it also means that, if they don't, the shuffles produced for i8x16 and i16x8 aren't awful.

For the FP workloads that I've been looking at, this change can be worth 3-7% performance uplift.

**Comment by tlively** [comment]
Is the idea here that the Wasm engine can recognize the special shuffle pattern and generate different code for it? If so, is that code the engine is expected to generate correct with respect to the Wasm spec, or is this a method of providing unsafe optimization hints to the engine?

**Comment by sparker-arm** [comment]
> is that code the engine is expected to generate correct with respect to the Wasm spec, or is this a method of providing unsafe optimization hints to the engine?

This allows the engine to generate more optimised code while respecting the Wasm spec. The key here is that when compiling with Ofast, LLVM can choose an arbitrary shuffle pattern but once this is lowered to Wasm, it is no longer arbitrary - the engine has to perform the adds in the order specified. By changing the shuffle pattern here, it allows a Wasm engine to select pairwise add vector instructions, such as faddp on AArch64 or haddps on X86.

**Review by tlively — APPROVED** [review]
Thanks, this LGTM.

**Comment by ppenzin** [comment]
I was hoping we can discuss this in Wasm SIMD subgroup before merging.

@yolanda15 @jing-bao you might want to check if this change would have any effect on x86 patterns in V8.

**Pull request merged**
