### PR TITLE
[BOLT] Emit empty FDE for injected functions

### PR DESCRIPTION
**Pull request by aaupov**
This fixes an issue where `PatchEntries` overwrites function body but
keeps CFI untouched. Existing FDEs thus become invalid. This doesn't
affect unwinding because patched functions are transparent from
EH/unwinding perspective, but it breaks BOLT during disassembling those
functions.

Emit empty FDE for injected functions (emitted to the same address as 
.org functions) that take precedence over the original FDE.

This adds eh_frame overhead, but restores the ability to disassemble 
.org functions. Note that the overhead is avoided in `-use-old-text`
mode.

Test Plan: updated bolt/test/X86/patch-entries.test

### CODE REVIEW

**Review by dcci — CHANGES_REQUESTED** [review]
Can you add a test? that way we can better understand what this function actually does, given it touches a core functionality.

**Review by maksfb — COMMENTED** [review]
Let's make `hasCFI()` return true for injected functions.

**Comment by aaupov** [comment]
> > > Let's make `hasCFI()` return true for injected functions.
> > 
> > 
> > Given that this change increases the size of eh_frame section, should we make it dependent on `enable-bat`, i.e. when we expect to feed the binary back to BOLT?
> > Because otherwise this "fix" is a pure size regression.
> 
> Creating a proper FDE entry is the right thing to do regardless of BAT. How large is the regression?

The largest I've seen is 34M->39M (HHVM instrumentation).

**Comment by maksfb** [comment]
> > Creating a proper FDE entry is the right thing to do regardless of BAT. How large is the regression?
> 
> The largest I've seen is 34M->39M (HHVM instrumentation).

Did you check if we patch every single function in he original `.text`? How many functions are there?

**Comment by aaupov** [comment]
> > > Creating a proper FDE entry is the right thing to do regardless of BAT. How large is the regression?
> > 
> > 
> > The largest I've seen is 34M->39M (HHVM instrumentation).
> 
> Did you check if we patch every single function in he original `.text`? How many functions are there?

I'm not sure how to confirm this, but I'm pretty sure we do patch every function in regular instrumentation mode. There are 406308 functions instrumented.

**Comment by maksfb** [comment]
Okay. That explains the increase.

**Review by maksfb — APPROVED** [review]

**Review by dcci — APPROVED** [review]

**Pull request merged**
