### PR TITLE
 [InstCombine] Fold `[l|a]shr iN (X-1)&~X, N-1 -> [z|s]ext(X==0)`

### LINKED ISSUE #107228: [InstCombine] Missed optimization: `((A - 1) & (~A)) >> 63`  --> `A == 0`
Alive2 proof: https://alive2.llvm.org/ce/z/9fa--y
## Motivating example

```llvm
define i32 @src(i64 %3) #0 {
  %4 = add i64 %3, -1
  %5 = xor i64 %3, -1
  %not.i.i20 = and i64 %4, %5
  %shr.i.i21 = lshr i64 %not.i.i20, 63
  %6 = trunc i64 %shr.i.i21 to i32
  ret i32 %6
}

define i32 @tgt(i64 %3) #0 {
  %4 = icmp eq i64 %3, 0
  %5 = zext i1 %4 to i32
  ret i32 %5
}

```

It's a specific pattern found in https://github.com/openssl/openssl/blob/2a6305dfcd89632b69e49f8b3efe98b7e0daa1aa/crypto/ec/ecp_nistz256.c#L793

### PR DESCRIPTION
**Pull request by dtcxzyw**
Alive2: https://alive2.llvm.org/ce/z/kwvTFn
Closes #107228.

`ashr iN (X-1)&~X, N-1` also exists. See https://github.com/dtcxzyw/llvm-opt-benchmark/issues/1274.

### CODE REVIEW

**Review by nikic — APPROVED** [review]
LGTM

**Comment by goldsteinn** [comment]
You could generalize this to any negation: https://alive2.llvm.org/ce/z/gzNi3b

**Comment by goldsteinn** [comment]
Also think a better place for this would be `simplifyDemandedBits`. There are a lot of patterns in the bits based on `X` and `C`(1) in this case.

**Comment by nikic** [comment]
> Also think a better place for this would be `simplifyDemandedBits`. There are a lot of patterns in the bits based on `X` and `C`(1) in this case.

So the pattern would be something like this? https://alive2.llvm.org/ce/z/FqAbpX I guess that's fine assuming this actually occurs with non-lshr/ashr demanded bits contexts and the additional one-use limitation is unproblematic for motivating cases.

**Comment by goldsteinn** [comment]
> > Also think a better place for this would be `simplifyDemandedBits`. There are a lot of patterns in the bits based on `X` and `C`(1) in this case.
> 
> So the pattern would be something like this? https://alive2.llvm.org/ce/z/FqAbpX I guess that's fine assuming this actually occurs with non-lshr/ashr demanded bits contexts and the additional one-use limitation is unproblematic for motivating cases.

Yeah, we can also deduce things about the lowbits from it as well. I.e:
https://alive2.llvm.org/ce/z/5Vm8UW

Is this pattern common enough to justify adding it to knownbits handling?

**Comment by dtcxzyw** [comment]
I don't see the value of generalizing this pattern. This pattern only exists in cryptographic libraries. We can extend it in the future if possible.

**Comment by nikic** [comment]
I agree.

**Comment by goldsteinn** [comment]
Okay, then this LGTM.

**Review by XChy — APPROVED** [review]
LGTM.

**Pull request merged**
