### PR TITLE
[libc++] Clean up some minor inconsistencies in the status pages

### PR DESCRIPTION
**Pull request by h-vetinari**
Some issues I've been noticing for a while, happy to provide suggested fixes now that GH PRs are accepted! :)

### CODE REVIEW

**Review by ldionne — APPROVED** [review]
LGTM, thanks! Please squash into a single commit and go ahead.

**Comment by h-vetinari** [comment]
Cool thanks!

> Please squash into a single commit and go ahead.

I separated them for ease of review; good thing that github supports squash-merging a PR without anything extra. However, I don't have commit rights, so I'd need someone else to push the button... 😅

**Comment by h-vetinari** [comment]
@ldionne @mordante, I noticed that the status pages haven't been updated yet - is anything broken with the doc rendering?

**Comment by mordante** [comment]
The CI that updates the status pages is broken, it's being looked into. (Or maybe already fixed.)

**Pull request merged**
