### PR TITLE
[ASan][libc++] Turn off SSO annotations for Apple platforms

### PR DESCRIPTION
**Pull request by AdvenamTacet**
This commit disables short string AddressSanitizer annotations on Apple platforms as a temporary solution to the problem reported in issue #96099.

For more information on Apple's block implementation, please refer to [`clang/docs/Block-ABI-Apple.rst`](https://github.com/llvm/llvm-project/blob/main/clang/docs/Block-ABI-Apple.rst). The core issue lies in the fact that blocks are unaware of their content, causing AddressSanitizer errors when blocks are moved using `memmove`.

I believe - and I'm not alone - that the issue should ideally be addressed within the block moving logic. However, if a timely resolution is not feasible, this temporary fix can be used. Before merging, we should ensure that a more permanent solution cannot be implemented in time and that this change effectively resolves the issue.

### CODE REVIEW

**Comment by nico** [comment]
I have no strong opinion if this should be merged; it should be @ldionne's call.

#91702 seems like a nice fix to me. I don't know how the asan runtime is deployed on apple devices – if it ships with Xcode, then that should work well over there deployment-wise (assuming #91702 is shipped at the same time as the short string asan annotations.)

**Review by ldionne — APPROVED** [review]
LGTM. This is a hack but it's the best we can do until the Blocks runtime is fixed.

**Comment by ldionne** [comment]
@AdvenamTacet Please disable email hiding, it's a LLVM policy to have proper emails associated to commits. You can use an alternate email address for contributing to LLVM if you don't want to leak your normal email address in commit logs.

**Comment by AdvenamTacet** [comment]
I don't have access to a computer until next week, so I cannot look closer at that failure, but it seems unrelated at first glance.
I will confirm soon.

About email: so far when I was landing my PRs I just made sure that I land them with proper email. If that's problematic, I can replace my private one with another and unhide emails. However, I am not a fan of that as unfortunately I have to leak all my emails and I don't think I can enforce which one is used by the person performing merge.
 

I just want to point out that GitHubs granularity is terrible and problematic here. I wish I could unhide some emails / allow to merge with email used in the PR (from CLI it's actually possible as I don't block pushes with my emails in commits).
I will look into unhiding when I have access to a PC.

**Pull request merged**
