### PR TITLE
[RISCV] Use the thread local stack protector for Android targets

### PR DESCRIPTION
**Pull request by ilovepi**
Android supports per thread stack protectors that are individually managed and
initialized, which can provide stronger protections than using the global stack
protector cookie. This patch matches the convention for other architectures
targeting Android platforms.

### CODE REVIEW

**Review by enh-google — COMMENTED** [review]
s/master/main/ in the url to get the current version. (master "works" but it's frozen in time; main will track future changes.)

otherwise lgtm...

**Comment by topperc** [comment]
> s/master/main/ in the url to get the current version. (master "works" but it's frozen in time; main will track future changes.)
> 
> otherwise lgtm...

Probably someone should update AArch64 which has the same comment?

**Review by rprichard — APPROVED** [review]
LGTM

**Comment by ilovepi** [comment]
> > s/master/main/ in the url to get the current version. (master "works" but it's frozen in time; main will track future changes.)
> > otherwise lgtm...
> 
> Probably someone should update AArch64 which has the same comment?

Done in #87726

**Comment by ilovepi** [comment]
I plan to land this today, after presubmits are green.

**Review by MaskRay — APPROVED** [review]

**Pull request merged**
