### PR TITLE
release/19.x: [WebAssembly] Fix rethrow's index calculation (#114693)

### LINKED ISSUE #114600: WASM rethrow instruction is generated with a wrong index
This is a wasm target, built with `-fwasm-exceptions`. Reproducer:

```cpp
#include <cstdio>

__attribute__((noinline)) void print_current() noexcept {
  try {
    throw;
  } catch (int x) {
    printf("%d\n", x);
  }
}

struct Dropper {
  ~Dropper() {
    try {
      throw 1;
    } catch (...) {
      print_current();
    }
  }
};

int main() {
  try {
    Dropper dropper;
    throw 2;
  } catch (...) {
    print_current();
  }
}
```

Expected output: `1 2`, actual output: `1 1`.

(I'm using `emcc -O2 -fwasm-exceptions test.cpp` for testing if that's important.)

The problem is in the codegen for `main`:

<details><summary>Wasm IR</summary>

```
(func (;6;) (type 11) (result i32)
  (local i32 i32)
  global.get 0
  local.set 1
  call 22
  local.tee 0
  i32.const 2
  i32.store
  try ;; label = @1
    local.get 0
    call 28
  catch_all
    local.get 1
    global.set 0
    call 22
    local.tee 0
    i32.const 1
    i32.store
    try ;; label = @2
      try ;; label = @3
        local.get 0
        call 28
      catch 0
        local.set 0
        local.get 1
        global.set 0
        local.get 0
        call 29
        drop
        call 5
        call 30
        try ;; label = @4
          try ;; label = @5
            rethrow 2 (;@3;)
          catch 0
            local.set 0
            local.get 1
            global.set 0
            local.get 0
            call 29
            drop
            call 5
            try ;; label = @6
              call 30
            delegate 5
            i32.const 0
            return
          end
          unreachable
        delegate 3
        unreachable
      end
    catch_all
      local.get 1
      global.set 0
      call 37
      unreachable
    end
    unreachable
  end
  unreachable
)
```

</details>

In pseudocode, simplified:

```
try:
    throw(2)
catch_all:
    try:
        try:
            throw(1)
        catch:
            print_current()
            rethrow(0)
    catch:
        print_current()
```

So `rethrow(0)` rethrows the same exception as has just been handled, so the same exception object is caught twice. `rethrow(2)` would work correctly. The current behavior leads to all sorts of memory corruption and hard-to-debug state.

### PR DESCRIPTION
**Pull request by aheejin**
Backport https://github.com/llvm/llvm-project/commit/492812f613280034b7c514d74113750814a3de76

Requested by: @aheejin

### CODE REVIEW

**Review by dschuff — APPROVED** [review]
LGTM, although it looks like this is already done?

**Comment by aheejin** [comment]
What do you mean by already done? This is a request to backport the fix to 19.4 release.

**Comment by dschuff** [comment]
oh nevermind, I was confused; #114693 is closed, but this is the PR that implements the backport.

**Comment by tru** [comment]
This is a pretty big patch to bring into a backport. How risky is this and how important is this to end up in a backport?

**Comment by aheejin** [comment]
FWIW I believe this is sufficiently safe. And this is a fix for a serious bug, which I think should land sooner than LLVM 20.

**Comment by aheejin** [comment]
> @aheejin (or anyone else). If you would like to add a note about this fix in the release notes (completely optional). Please reply to this comment with a one or two sentence description of the fix. When you are done, please add the release:note label to this PR.

WebAssembly: Fixed a bug that miscalculated the argument of 'rethrow' instruction.

**Pull request merged**
