### PR TITLE
Add cosh op to the math dialect.

### PR DESCRIPTION
**Pull request by godot73**

### CODE REVIEW

**Comment by godot73** [comment]
Similar to https://github.com/llvm/llvm-project/pull/74584, this PR is required to implement lowering of torch.aten.cosh.

**Review by frederik-h — APPROVED** [review]
Looks good to me.

**Review by vivekkhandelwal1 — APPROVED** [review]
LGTM

**Comment by vivekkhandelwal1** [comment]
@stellaraccident, can you please merge this PR?

**Comment by frederik-h** [comment]
> @stellaraccident, can you please merge this PR?

@stellaraccident @vivekkhandelwal1 I already did it.

**Comment by vivekkhandelwal1** [comment]
> > @stellaraccident, can you please merge this PR?
> 
> @stellaraccident @vivekkhandelwal1 I already did it.

Thanks!

**Pull request merged**
