### PR TITLE
[libc++][C++03] Copy the LLVM 19 headers

### PR DESCRIPTION
**Pull request by philnik777**
This is the first part of the "Freezing C++03 headers" proposal explained in https://discourse.llvm.org/t/rfc-freezing-c-03-headers-in-libc/77319/58.

This patch mechanically copies the headers as of the LLVM 19.1 release into a subdirectory of libc++ so that we can start using these headers when building in C++03 mode. We are going to be backporting important changes to that copy of the headers until the LLVM 21 release. After the LLVM 21 release, only critical bugfixes will be fixed in the C++03 copy of the headers.

This patch only performs a copy of the headers -- these headers are still unused by the rest of the codebase.

### CODE REVIEW

**Comment by philnik777** [comment]
* **#109002** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109002?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#109001** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109001?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#109000** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/109000?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#108999** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/108999?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @philnik777 and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by ldionne — APPROVED** [review]

**Comment by ldionne** [comment]
@philnik777 It looks like that buildbot failure is caused by this patch.

**Comment by zeroomega** [comment]
We are seeing runtime build failures on our bot after this patch landed:

```
[1223/1598](61) Generate the mapping file for include-what-you-use
FAILED: /b/s/w/ir/x/w/llvm_build/include/c++/v1/libcxx.imp 
cd /b/s/w/ir/x/w/llvm_build/runtimes/runtimes-x86_64-pc-windows-msvc-bins/libcxx/include && /b/s/w/ir/cipd_bin_packages/cpython3/bin/python3.8 /b/s/w/ir/x/w/llvm-llvm-project/libcxx/utils/generate_iwyu_mapping.py -o /b/s/w/ir/x/w/llvm_build/include/c++/v1/libcxx.imp
Traceback (most recent call last):
  File "/b/s/w/ir/x/w/llvm-llvm-project/libcxx/utils/generate_iwyu_mapping.py", line 92, in <module>
    main(sys.argv[1:])
  File "/b/s/w/ir/x/w/llvm-llvm-project/libcxx/utils/generate_iwyu_mapping.py", line 82, in main
    raise RuntimeError(f"{header}: Header {public} is not a valid header")
RuntimeError: __cxx03/__algorithm/adjacent_find.h: Header cxx03 is not a valid header
```

Failing task: https://ci.chromium.org/ui/p/fuchsia/builders/toolchain.ci/clang-linux-x64/b8735245579486612113/overview
Could you revert this change please?

**Comment by EricWF** [comment]
This is one of those times where having 1000 headers  makes things slightly trickier.

**Comment by ldionne** [comment]
> This is one of those times where having 1000 headers makes things slightly trickier.

Actually the exact same issue would have happened if we had just a few headers, since they would have been moved to e.g. `__cxx03/vector` and the same issue would have been triggered. The real issue here IMO is the flakiness of our CI recently, which is probably what led Nikolas to ignore the CI failure before merging.

**Comment by philnik777** [comment]
> > This is one of those times where having 1000 headers makes things slightly trickier.
> 
> Actually the exact same issue would have happened if we had just a few headers, since they would have been moved to e.g. `__cxx03/vector` and the same issue would have been triggered. The real issue here IMO is the flakiness of our CI recently, which is probably what led Nikolas to ignore the CI failure before merging.

Yes, exactly. I thought "what could possibly fail when just copying headers? It's probably just a broken CI."

**Pull request merged**
