### PR TITLE
AMDGPU: Handle remote/fine-grained memory in atomicrmw fmin/fmax lowering

### PR DESCRIPTION
**Pull request by arsenm**
Consider the new atomic metadata when choosing to expand as cmpxchg
instead.

### CODE REVIEW

**Comment by arsenm** [comment]
> [!WARNING]
> <b>This pull request is not mergeable via GitHub because a downstack PR is open. Once all requirements are satisfied, merge this PR as a stack <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96759?utm_source=stack-comment-downstack-mergeability-warning" >on Graphite</a>.</b>
> <a href="https://graphite.dev/docs/merge-pull-requests">Learn more</a>

* **#96760** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96760?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#96759** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96759?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* **#96444** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96444?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#96443** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96443?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#96442** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/96442?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#95930** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/95930?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#95929** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/95929?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by arsenm** [comment]
ping

**Review by arsenm — COMMENTED** [review]
ping

**Comment by arsenm** [comment]
ping in

**Review by arsenm — COMMENTED** [review]
ping

**Comment by arsenm** [comment]
ping

**Review by yxsamliu — APPROVED** [review]

**Pull request merged**
