### PR TITLE
[AArch64] Emit ST<OP> instruction when the return value has no use. 

### LINKED ISSUE #69503: atomic::fetch_add with unused result generates ldadd instead of stadd on Arm
The following code:

```c++
void inc(std::atomic<uint32_t>* p) {
    p->fetch_add(1, std::memory_order_relaxed);
}
```

discards the result of the atomic rmw add operation. 

On Arm, it generates an `ldadd` instruction, but I'd expect it to generate an `stadd` instead, since the result is not used. 
See https://gcc.godbolt.org/z/7K5YYEjT9

### PR DESCRIPTION
**Pull request by sun-jacobi**
This PR fixed #69503. 

The original implementation consider `ST<OP>` as `InstAlias` of `LD<OP>`, however this method could not cover the case in the #69503. 

This PR instead create a new pattern match, utilizing the `HasNoUse` field of the`PatFrags`

### CODE REVIEW

**Comment by sun-jacobi** [comment]
> Using LDADD here is a conscious decision by compilers (GCC also generates the same code). See the thread at https://gcc.gnu.org/pipermail/gcc-patches/2018-October/509550.html

Thanks for the useful information. 
But maybe we can add a special handling for the LD<OP> with acquire semantics?

**Comment by ktkachov-arm** [comment]
> > Using LDADD here is a conscious decision by compilers (GCC also generates the same code). See the thread at https://gcc.gnu.org/pipermail/gcc-patches/2018-October/509550.html
> 
> Thanks for the useful information. But maybe we can add a special handling for the LD with acquire semantics?

It's tempting to do this translation to STADD only for the relaxed memory model, but apparently that's not legal either:
https://gcc.gnu.org/pipermail/gcc-patches/2018-October/509632.html

**Comment by sun-jacobi** [comment]
> > > Using LDADD here is a conscious decision by compilers (GCC also generates the same code). See the thread at https://gcc.gnu.org/pipermail/gcc-patches/2018-October/509550.html
> > 
> > 
> > Thanks for the useful information. But maybe we can add a special handling for the LD with acquire semantics?
> 
> It's tempting to do this translation to STADD only for the relaxed memory model, but apparently that's not legal either: https://gcc.gnu.org/pipermail/gcc-patches/2018-October/509632.html

It seems that only `LDADDA` and `LDADDAL` load from memory with acquire semantics. 

In other cases, like `LDADDL` and `STADDL`, 
> STADDL stores to memory with release semantics
> LDADDL and LDADDAL store to memory with release semantics.  

the semantics seems to be the same.

**Comment by gonzalobg** [comment]
I agree with Kyrill. Replacing LDADD with STADD is unsound unless the implementation of the acquire-fence also changes to fence stores, which would break the atomics ABI. I'll capture this in the bug, and will close it. Thank you both for entertaining the idea though.

**Pull request closed without merging**
