### PR TITLE
Fix hasName matcher assertion with inline namespaces

### PR DESCRIPTION
**Pull request by njames93**
Fix handling of nodes which can be skipped in the fast path for the hasName matcher

#100973

### CODE REVIEW

**Review by AaronBallman — COMMENTED** [review]
I can't get the assertion to reproduce, but I can see the behavioral change with the first matcher: https://godbolt.org/z/TcsYPoGEh

So this should probably come with a release note for the fix?

**Comment by njames93** [comment]
> I can't get the assertion to reproduce, but I can see the behavioral change with the first matcher: https://godbolt.org/z/TcsYPoGEh
> 
> So this should probably come with a release note for the fix?

The assertions are only shown on debug build, but it comes from [here](https://github.com/llvm/llvm-project/blob/9e3f5ae48fa75d5db8b132162d96004191618956/clang/lib/ASTMatchers/ASTMatchersInternal.cpp#L678)

Which section in the release notes do changes to AST matchers belong in

**Comment by AaronBallman** [comment]
> > I can't get the assertion to reproduce, but I can see the behavioral change with the first matcher: https://godbolt.org/z/TcsYPoGEh
> > So this should probably come with a release note for the fix?
> 
> The assertions are only shown on debug build, but it comes from [here](https://github.com/llvm/llvm-project/blob/9e3f5ae48fa75d5db8b132162d96004191618956/clang/lib/ASTMatchers/ASTMatchersInternal.cpp#L678)

That should still trigger with an assertions build though, right?

> Which section in the release notes do changes to AST matchers belong in

Somewhere around here: https://github.com/llvm/llvm-project/blob/77655f42d58e85875c4b4e28a73208b64a653c2a/clang/docs/ReleaseNotes.rst?plain=1#L247

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Pull request merged**
