### PR TITLE
[Documentation] Replace recommonmark by myst-parser

### PR DESCRIPTION
**Pull request by cor3ntin**
This is a bit rough, but i did that while trying to figure out if there would be a good way to do
pre commit checks on RsT files.

Recommonmark has been deprecated, then archived last year. This was tracked by: https://github.com/llvm/llvm-iwg/issues/30

https://github.com/readthedocs/recommonmark

Before merging that we would have to update the bots, which I'm not in a good position to do, so feel free to take over!

**If you own a bot that build documentation, please run:**

`pip3 install sphinx myst-parser sphinx-automodapi furo` 

**in the build environment. Thanks !**

### CODE REVIEW

**Comment by tru** [comment]
Seems like a nice cleanup on top of the fact that we don't have to use a deprecated module. I am guessing it didn't cause any output errors.

Regarding build-bots, I am unsure where we automatically build the documentation. Pushing the docs to the main branch will rebuild and put them on llvm.org, But not sure where that happens. Maybe we should have a `requirements.txt` for documentation building and add that somewhere in the tree and have our bots always install that instead of each bot having its own list of python modules.

cc @tstellar

**Comment by cor3ntin** [comment]
Agreed. I have found that the full set of needed pip modules is
`sphinx myst-parser sphinx-markdown-tables sphinx-automodapi furo` - I think most of theses are only used by LLDB but might as well document them as requirements for everything.

**Review by tstellar — APPROVED** [review]
LGTM.  @andreil99 Are you maintaining the documentation bots?

**Comment by andreil99** [comment]
I can update the publishing bots. For the bots running on https://lab.llvm.org/buildbot/#/workers/92 we would need @gribozavr or somebody with access to gribozavr3 worker.

@cor3ntin, is there any dependency on a particular version of myst-parser?

**Comment by tru** [comment]
Instead of updating the module manually on the bot, I still think it's a good idea to add a requirements.txt that should be installed before running the build, ideally in a virtualenv. WDYT @andreil99

**Comment by cor3ntin** [comment]
> Instead of updating the module manually on the bot, I still think it's a good idea to add a requirements.txt that should be installed before running the build, ideally in a virtualenv. WDYT @andreil99

I added a requirements.txt file in llvm/docs (and updated docs, scripts)

> @cor3ntin, is there any dependency on a particular version of myst-parser?

I unfortunately have no idea, besides "work on my system" (ubuntu 23.04)

**Comment by andreil99** [comment]
Thanks, @cor3ntin!

I have installed the latest myst-parser (2.0.0) on the publishing bot. Will see how it will fly.

Please feel free to commit requirements.txt you have. I'll update it with the one with known-to-be-good versions frozen once we will confirm on that bot myst-parser 2.0.0.

**Review by tru — APPROVED** [review]
Let's ship it! Maybe post a heads-up on discourse as well so that people are aware it will happen and if some bots fail how to fix it.

**Comment by cor3ntin** [comment]
@tru I'll try to do that later this week!

**Comment by cor3ntin** [comment]
@andreil99 did you update all the sphinx bots or just specific ones?

**Comment by andreil99** [comment]
@cor3ntin No, I did not update all the sphinx bots, only specific ones, as I mentioned above in https://github.com/llvm/llvm-project/pull/65664#issuecomment-1714983618
> I can update the publishing bots. For the bots running on https://lab.llvm.org/buildbot/#/workers/92 we would need @gribozavr or somebody with access to gribozavr3 worker.

**Comment by cor3ntin** [comment]
@andreil99 Sorry, I missed that.
I'd like to wait a few days for the bots to have the package installed first to minimize disruption.

**Comment by mgorny** [comment]
I'm sorry for being late to the party but what's the rationale for removing support for building manpages without myst-parser, that FWICS isn't used for manpages at all? I don't see any answer neither in the commit message, nor in this thread. It really feels like you've just *shrugged* and removed it without any consideration for the prior effort to make things work better.

**Comment by AaronBallman** [comment]
> I'm sorry for being late to the party but what's the rationale for removing support for building manpages without myst-parser, that FWICS isn't used for manpages at all? I don't see any answer neither in the commit message, nor in this thread. It really feels like you've just _shrugged_ and removed it without any consideration for the prior effort to make things work better.

This is the first I've heard about this breaking anyone, can you give more information on what used to work for you and is now broken? Is myst-parser package not available for you?

**Comment by mgorny** [comment]
What used to work is that you could build manpages (that don't use any `.md` files) without installing additional dependencies. Now Sphinx requires myst-parser even when no `.md` files are used. *I* don't really care. However, Gentoo users do tend to complain whenever any single unnecessary package gets pulled in.

**Comment by AaronBallman** [comment]
Ah, thank you for the extra information! We definitely cannot go back to recommonmark, but perhaps @cor3ntin can find a way to restore the older behavior there. However, I think finding the minimal set of dependencies might be brittle in terms of long-term maintenance (so if it turns out it's significant effort to support the old behavior, I think the extra package may be the price we pay for getting off an unmaintained package).

**Comment by mgorny** [comment]
I've adjusted the Gentoo packages, and can live with it. I just find it sad that even though there was an explicit comment on why the `ImportError` fallback was added, it was just removed without a second thought or even an attempt to communicate with me (given `git blame` would have attributed the original change to me).

**Comment by AaronBallman** [comment]
> I've adjusted the Gentoo packages, and can live with it. I just find it sad that even though there was an explicit comment on why the `ImportError` fallback was added, it was just removed without a second thought or even an attempt to communicate with me (given `git blame` would have attributed the original change to me).

I think it was simply overlooked by accident; nobody "owns" this functionality in community and so when we needed to get off the archived package, we took the offered patch which was based on advice from the recommonmark maintainers on how to port to myst-parser. Given that there's no post-commit bot testing this configuration, it's easy enough for this kind of thing to slip through the cracks. FWIW, if we do end up restoring the old behavior to help Gentoo folks out, I think we need some sort of test coverage for it and we'd appreciate your help in getting that set up so we don't regress again (assuming we're able to restore the old behavior).

**Pull request merged**
