### PR TITLE
[flang][OpenMP] Add support for `target ... private`

### PR DESCRIPTION
**Pull request by ergawy**
Adds support for the `private` clause in the `target` directive. In order to support that, the `DataSharingProcessor` was also restructured in order to separate the collection of prviate symbols from their actual privatization code-gen.

The commit adds both a code-gen and an offloading tests.

### CODE REVIEW

**Comment by clementval** [comment]
What about having a proper representation of private on the target operation and delay the actual privatization to a later stage? 

https://github.com/llvm/llvm-project/pull/75836

**Comment by ergawy** [comment]
> What about having a proper representation of private on the target operation and delay the actual privatization to a later stage?
> 
> #75836


Thanks for the suggestion, I think that would be much better indeed. To disuss this in more detail, for the `target` op, I think it should change from this:
```
omp.target ... {
bb0(...):
    %priv_x = fir.alloca ... {bindc_name = "x"} ... // alloca for privatized var
    ... use %priv_x ...
 }
```
To something like this:
```
omp.target ... private(%x -> %argx: type) {
bb0(%argx: type):
    ... use %argx ...
}
```

And then we either:
1. Would move/adapt the alloca generation logic currently in `DataSharingProcessor::privatize()` to `OpenMPToLLVMIRTranslation.cpp`. However, we need to adapt that logic to directly generate LLVM IR `alloca` instructions instead of `fir.alloca`s.
2. Or, have a conversion pattern that gets inserted in the pipeline while we still have FIR (*). The advantage here is that, I think, we can more directly and easily share code between that `DataSharingProcessor::privatize()` and that new conversion pattern. Or even reuse the `DataSharingProcessor` util altogether somehow. What I mean is that I think the `DataSharingProcessor` can be grown into a standalone `OpConversionPattern` that does the whole privitatization logic as later in the dialect as we would like.

I am leaning towards the 2nd option since it would be cleaner and easier to adapt IMO. WDYT?

(*) I know that emitting `fir.alloca`s for privatized variables may not be a good thing to have since it couples the FIR and OMP dialects but having a separate conversion pattern will a step towards uncoupling the 2 dialects (if we prefer to). Even if we do not care about the coupling, the separate conversion patter would be a cleaner and standalone way to handle all the privatization materializations in one self-contained place.

Looking forward for any thoughts on this :).

**Comment by kiranchandramohan** [comment]
> omp.target ... private(%x -> %argx: type) {
> bb0(%argx: type):
>     ... use %argx ...
> }

You can augment the `private` with a function like op that declares how to make a clone (with alloca) of this type. Flang will create this with FIR/HLFIR. This will be converted by the current conversion patterns in codegen.cpp to LLVM dialect and then in `OpenMPToLLVMIRTranslation.cpp` you can hopefully just inline this function like op at the correct place.
```
  omp.private.decl @privatization_decl_i32 : !fir.ref<i32> init {
  ^bb0(%arg0: !fir.ref<i32>):
    %0 = fir.alloca i32
    omp.yield %0 : !fir.ref<i32>
  }
```

```
omp.target ... private(private_decl_i32 %x -> %argx: !fir.ref<i32>) {
bb0(%argx: !fir.ref<i32>):
     ... use %argx ...
}
```

The copyprivate patch reuses some of the copying (needed for firstprivate) from DataSharingProcessor.
https://github.com/llvm/llvm-project/pull/73128

You can hopefully combine what you do and what is there for `copyprivate` to implement `firstprivate` as well.

Note: You can find similar code in OpenMP reduction declarations and in OpenACC privatisation and reduction recipes

**Comment by ergawy** [comment]
> > omp.target ... private(%x -> %argx: type) {
> > bb0(%argx: type):
> > ... use %argx ...
> > }
> 
> You can augment the `private` with a function like op that declares how to make a clone (with alloca) of this type. Flang will create this with FIR/HLFIR. This will be converted by the current conversion patterns in codegen.cpp to LLVM dialect and then in `OpenMPToLLVMIRTranslation.cpp` you can hopefully just inline this function like op at the correct place.
> 
> ```
>   omp.private.decl @private_decl_i32 : !fir.ref<i32> init {
>   ^bb0(%arg0: !fir.ref<i32>):
>     %0 = fir.alloca i32
>     omp.yield %0 : !fir.ref<i32>
>   }
> ```
> 
> ```
> omp.target ... private(private_decl_i32 %x -> %argx: !fir.ref<i32>) {
> bb0(%argx: !fir.ref<i32>):
>      ... use %argx ...
> }
> ```
> 
> The copyprivate patch reuses some of the copying (needed for firstprivate) from DataSharingProcessor. #73128
> 
> You can hopefully combine what you do and what is there for `copyprivate` to implement `firstprivate` as well.
> 
> Note: You can find similar code in OpenMP reduction declarations and in OpenACC privatisation and reduction recipes

@kiranchandramohan @clementval I created an incomplete WIP for delayed privatization in https://github.com/llvm/llvm-project/pull/79862. In the commit message I explain what is done and is still todo.

I know it is a bit early stage but I wanted to take your input on the current approach at least from a high-level of view. Any comments from anyone is highly appreciated.

I can abandon this PR and we can probably move the discussion to the WIP PR.

**Comment by clementval** [comment]
Good! I'll have a look at it today.

**Comment by ergawy** [comment]
Abandoning since we are moving to delayed privatization: #79862.

**Pull request closed without merging**
