### PR TITLE
[RISCV] Fix 0-offset aliases for compressed sp-based opcodes

### PR DESCRIPTION
**Pull request by ArcaneNibble**
The "26.3.1. Stack-Pointer-Based Loads and Stores" compressed opcodes have access to all registers (except x0). Fix the opcode aliases with 0 offset so that the aliases also work for all registers, not only the RVC registers.

Previously, LLVM would accept e.g. `c.lwsp x8, (sp)` but not e.g. `c.lwsp x18, (sp)`, even though e.g. `c.lwsp x18, 0(sp)` would be accepted.

This was noticed while implementing https://github.com/llvm/llvm-project/pull/97925 . The implementation in that other PR is indeed correct (i.e `qk.c.lhusp` et al are restricted to the RVC registers).

### CODE REVIEW

**Comment by ArcaneNibble** [comment]
tagging @asb as RISC-V code owner

**Review by topperc — APPROVED** [review]
LGTM

**Review by lenary — APPROVED** [review]

**Comment by ArcaneNibble** [comment]
Do I need to do anything further here? Or do I just wait for somebody to come around and click the merge button?

**Comment by lenary** [comment]
Sorry, one of us should have realised you didn't have commit access. Thanks for pinging the ticket, it's merged now. :)

**Pull request merged**
