### PR TITLE
ValueTracking: refactor recurrence-matching (NFC)

### PR DESCRIPTION
**Pull request by artagnon**

### CODE REVIEW

**Comment by goldsteinn** [comment]
LG

As an aside, can you format your PR titles per the style guide ('[<Component>] <msg...>" as opposed to "<Component>: <msg...>")

If you have doing this to avoid `git am` / `git format-patch` stripping you can use the `git am -k` and `git format-patch -N -k`

**Comment by artagnon** [comment]
> As an aside, can you format your PR titles per the style guide ('[] <msg...>" as opposed to ": <msg...>")

Is it specified in the style guide? I looked it up, but couldn't find a guideline saying this. I've been doing this for all my patches to save one valuable character in the title: it's a habit I picked up while contributing to upstream git. FWIW, there are some commits in the project that horribly overflow in both the title and body.

**Comment by goldsteinn** [comment]
> > As an aside, can you format your PR titles per the style guide ('[] <msg...>" as opposed to ": <msg...>")
> 
> Is it specified in the style guide? I looked it up, but couldn't find a guideline saying this. I've been doing this for all my patches to save one valuable character in the title: it's a habit I picked up while contributing to upstream git. 

I guess it isn't, just the norm.

> FWIW, there are some commits in the project that horribly overflow in both the title and body.

Indeed, although that seems to be within the norms of the community :P

**Comment by artagnon** [comment]
Sorry, tests are failing, due to what appears to be an underlying bug. Kindly see #109794.

**Comment by artagnon** [comment]
All tests passing now. Could we kindly verify that the patch is an improvement?

**Review by goldsteinn — APPROVED** [review]
LGTM

**Pull request merged**
