### PR TITLE
[NFC] Move DroppedVariableStats code to Analysis

### PR DESCRIPTION
**Pull request by rastogishubham**
This is done because the CodeGen library and Passes library both link against Analysis, to avoid adding a dependency between CodeGen and Passes if we want to extend the DroppedVariableStats code for MIR stats as well, as seen in https://github.com/llvm/llvm-project/pull/120501

### CODE REVIEW

**Comment by metaflow** [comment]
that creates a circular dependency of analysis on codegen

**Comment by rastogishubham** [comment]
@metaflow Can you please tell me how you reproduced the circular dependency? Analysis doesn't link against codegen, so I am confused as to how that happened

**Comment by metaflow** [comment]
@rastogishubham I was looking on bazel build, let me try to reproduce this...

**Comment by metaflow** [comment]
when https://github.com/llvm/llvm-project/commit/e389492d6a00e1c49a034e13343098541ebd03c6 landed `DroppedVariableStats.h` was 

```
...
#include "llvm/CodeGen/MachinePassManager.h"
#include "llvm/IR/DebugInfoMetadata.h"
#include "llvm/IR/DiagnosticInfo.
...
```

and depended on codegen. In https://github.com/llvm/llvm-project/commit/0b5b09b67c572867d88bbf5b41bcc5e722ec653a you removed this dependency.

**Pull request merged**
