### PR TITLE
Add new check: do not return 0; at the end of main() in C++

### LINKED ISSUE #38469: new check: do not return 0; at the end of main() in C++
|  |  |
| --- | --- |
| Bugzilla Link | [39121](https://llvm.org/bz39121) |
| Version | unspecified |
| OS | All |

## Extended Description 
As pointed out by Ilya Biryukov in one of the code reviews, C++ will automatically return 0; when control flow reaches the end of main;

https://en.cppreference.com/w/cpp/language/main_function:

> 4) The body of the main function does not need to contain the return statement: if control reaches the end of main without encountering a return statement, the effect is that of executing return 0;.

Saving one line of code is not a big deal, but it seems very easy to enforce and I think it's a nice idea for readability check.

Note that for C, it is only true since C99 ([docs](https://en.cppreference.com/w/c/language/main_function)).

### PR DESCRIPTION
**Pull request by 11happy**
**Overview:**
This pull request fixes #38469 where the issue proposes a new static analysis check in C++ to discourage the explicit return 0; statement at the end of the main() function. As C++ automatically assumes a return 0; in this context, having the explicit statement is redundant. The suggested change aims to enhance code readability by eliminating unnecessary lines in the main() function.

**Testing:**
- Tested the updated code.
- Verified that other functionalities remain unaffected.
Screenshot from 2024-01-10 16-53-31

**Dependencies:**
- No dependencies on other pull requests.

**CC:**
- @kirillbobyrev  , @AaronBallman

### CODE REVIEW

**Review by PiotrZSL — CHANGES_REQUESTED** [review]
I'm not fan about this check. For me there is no use case for it.
For sure it's not readability, simply because explicit return is more readable, and people who do not know that main by default will return 0 may even consider this check a bug, as why all functions got return but not this. Other issue is that many projects enable all readability checks, and as this one is controversial and not common it shouldn't be under readability, more like misc. There are many things that aren't needed, for example compiler is able to generate destructor, but still rule of 3/5 require it in some cases to be done explicitly, same is with return 0, there could be easily a check that could enforce explicit return in all functions, and that would also be readability. 

As for the check:
- wrong name
- wrong category, it should be more a 'misc' for me
- in current form it will catch also 'return 1';
I would say that if this check had to exists (i still cannot find use case for it), then it should be configurable to enforce 'return 0' or enforce lack of 'return 0'. And left configured to an most safe/common approach. What if someone wanted to do 'return 1', but forget to put return, and compiler didn't warn.

**Comment by 11happy** [comment]
> I'm not fan about this check. For me there is no use case for it. For sure it's not readability, simply because explicit return is more readable, and people who do not know that main by default will return 0 may even consider this check a bug, as why all functions got return but not this. Other issue is that many projects enable all readability checks, and as this one is controversial and not common it shouldn't be under readability, more like misc. There are many things that aren't needed, for example compiler is able to generate destructor, but still rule of 3/5 require it in some cases to be done explicitly, same is with return 0, there could be easily a check that could enforce explicit return in all functions, and that would also be readability.
> 
> As for the check:
> 
> * wrong name
> * wrong category, it should be more a 'misc' for me
> * in current form it will catch also 'return 1';
>   I would say that if this check had to exists (i still cannot find use case for it), then it should be configurable to enforce 'return 0' or enforce lack of 'return 0'. And left configured to an most safe/common approach. What if someone wanted to do 'return 1', but forget to put return, and compiler didn't warn.

Sure I will Look into these and will update it accordingly. I added it into readability category as It was mentioned by author on the issue #61957 , also can you please suggest the name that would be more suitable.

> The check could be placed under readability-* category.

As a new contributor to LLVM, I am willing to take to your guidance and suggestions.
Thank you

**Comment by AaronBallman** [comment]
> I'm not fan about this check. For me there is no use case for it.

Yeah, I don't see much motivation for the check. I know that once upon a time (my grey beard is showing, lol) there were compiler bugs in some implementations where a missing return statement in `main` would not return 0 as the standard required. However, I did some cursory searching on the web and don't see evidence that this problem exists in the wild any longer.

Do any of the current coding style guides we have checks for explicitly require the return in `main` or require it not be present? Maybe that would be more motivating?

**Comment by 11happy** [comment]
@PiotrZSL I have updated the code as per your suggestions. Can you please take a look at it?
Thank you.

**Comment by carlosgalvezp** [comment]
I agree with the opinions from Aaron And Piotr above - this check does the opposite of readability: it forces people to waste time digging into the Standard to find the quote that says the return is not needed. 

Could some argumentation be provided as to why this would be a good check to have? What coding guidelines/best practice articles promote this? I cannot think of any category where it would fit (besides misc). 

I believe this is a nano-optimization, and premature optimization is the root of all evil :)

**Comment by EugeneZelenko** [comment]
Original issue was closed as `wontfix`.

**Comment by PiotrZSL** [comment]
I'm closing this pull request, as both Carlos and Aaron already commented, closed also issue.
Please find some other issue to implement, if you got questions, you can always ask in issue, or on discord.
This check won't be merged, simply it's as Carols described "nano-optimization", specially that it will activate only on single function in entire project.

**Comment by 11happy** [comment]
> I agree with the opinions from Aaron And Piotr above - this check does the opposite of readability: it forces people to waste time digging into the Standard to find the quote that says the return is not needed.
> 
> Could some argumentation be provided as to why this would be a good check to have? What coding guidelines/best practice articles promote this? I cannot think of any category where it would fit (besides misc).
> 
> I believe this is a nano-optimization, and premature optimization is the root of all evil :)

Actually I don't have any points to put forward for this PR,It would be forcing it but , As a new contributor I got to learn a lot how to write clang-tidy checks etc ,I just choose to solve this issue as it mentioned good first issue and has certainly helped me to know more about the org and clang in a lot.

Thank you .

**Comment by EugeneZelenko** [comment]
@11happy: There are plenty of Clang-tidy issues with such tag: https://github.com/llvm/llvm-project/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22+label%3Aclang-tidy

**Comment by PiotrZSL** [comment]
There are ~600 other issues, not all were fully "reviewed", and there are many easy ones that aren't mark "good first issue". Once you pick something else, I will be happy to help with the review.

**Comment by 11happy** [comment]
Sure Sure, I will take up another issue.

**Comment by carlosgalvezp** [comment]
Thanks for understanding @11happy ! As you say the learning experience is invaluable and will be very useful for the next check. All contributions are greatly appreciated :)

I can recommend you look into fairly recent issues - older issues may not have been reviewed throughly or simply be forgotten.

**Pull request closed without merging**
