### PR TITLE
[bazel] Fix error: 'maybe' is not defined

### PR DESCRIPTION
**Pull request by cpiaseque**
Add missing parts of WORKSPACE file.

### CODE REVIEW

**Comment by kirillpyasecky** [comment]
@keith

**Comment by keith** [comment]
hrrm i think you have to fix the comment above

**Comment by kirillpyasecky** [comment]
@rupprecht

**Comment by kirillpyasecky** [comment]
> hrrm i think you have to fix the comment above

done

**Comment by keith** [comment]
you'll have to amend this commit with that setting disabled, in the log it still shows the noreply address

**Comment by kirillpyasecky** [comment]
what setting do you mean?

**Comment by keith** [comment]
the intent of that CI log was that when you run `git log` you see a real email address vs a github noreply email

**Pull request closed without merging**
