### PR TITLE
[ConstraintElimination] Use SCEV ranges information for Loop counter

### LINKED ISSUE #90417: Reopen of  Bug 49389 - Condition not constant folded
This old issue doesn't seem to be fixed as all: https://bugs.llvm.org/show_bug.cgi?id=49389
Bug 49389 would be reposted below (godbolt link: https://godbolt.org/z/hdza9Pb8z):
```c
#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>

#define N 1234

bool eat_digits(uint8_t s[N]) {
    size_t i = 0;
    while (i < N) {
        uint8_t c = s[i];
        if ('0' <= c && c <= '9') {
            i += 1;
        } else {
            break;
        }
    }
    return i <= N;
}
```
compiles to:
```asm
eat_digits:                             # @eat_digits
        xor     ecx, ecx
.LBB0_1:                                # =>This Inner Loop Header: Depth=1
        mov     rax, rcx
        cmp     rcx, 1234
        je      .LBB0_3
        movzx   edx, byte ptr [rdi + rax]
        add     dl, -48
        lea     rcx, [rax + 1]
        cmp     dl, 10
        jb      .LBB0_1
.LBB0_3:
        cmp     rax, 1235
        setb    al
        ret
```
GCC is able to compile it to:
```asm
eat_digits:
        mov     eax, 1
        ret
```

This is originally from: https://github.com/rust-lang/rust/issues/81432

### PR DESCRIPTION
**Pull request by v01dXYZ**
Fixes https://github.com/llvm/llvm-project/issues/90417

The modifications allow to use SCEV ranges for the loop counter to allow simplifications that doesn't depend on the branch taken.

As SCEV could create large numbers that would very likely trigger an overflow with `ConstraintSystem`, `ConstraintSystem` was modified to skip the constraint when overflow occurs.

### CODE REVIEW

**Comment by v01dXYZ** [comment]
I switch the PR to draft as there is a failing test: `polly Support/pipelineposition.ll`

``` console
Input was:
<<<<<<
          22:  n/a
          23:  Statements {
          24:  Stmt_body_i
          25:  Domain :=
          26:  [n] -> { Stmt_body_i[i0, i1] : 0 <= i0 < n and 0 <= i1 < n };
          27:  Schedule :=
next:84'0                 X error: no match found
          28:  [n] -> { Stmt_body_i[i0, i1] -> [i0, i1] };
next:84'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
next:84'1      ?                                            possible intended match
          29:  MustWriteAccess := [Reduction Type: NONE] [Scalar: 0]
next:84'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          30:  [n] -> { Stmt_body_i[i0, i1] -> MemRef_A[i0 + i1] };
next:84'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
          31:  }
next:84'0     ~~~
          32:  Function: caller
next:84'0     ~~~~~~~~~~~~~~~~~~
          33:  Region: %entry.split---%polly.merge_new_and_old
next:84'0     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
           .
           .
           .
>>>>>>
```

**Comment by v01dXYZ** [comment]
Below the test that fails:

``` llvm
define internal void @callee(i32 %n, ptr noalias nonnull %A, i32 %i) {
entry:
  br label %for

for:
  %j = phi i32 [0, %entry], [%j.inc, %inc]
  %j.cmp = icmp slt i32 %j, %n
  br i1 %j.cmp, label %body, label %exit

    body:
      %idx = add i32 %i, %j
      %arrayidx = getelementptr inbounds double, ptr %A, i32 %idx
      store double 42.0, ptr %arrayidx
      br label %inc

inc:
  %j.inc = add nuw nsw i32 %j, 1
  br label %for

exit:
  br label %return

return:
  ret void
}
```

I rebased as I don't understand what's going on. I'll take a closer look at it if it fails again.

**Comment by v01dXYZ** [comment]
it fails (as expected actually), I'm taking a look at it.

**Comment by v01dXYZ** [comment]
Very strange error it seems the output of `ScopInfo` is swapped (although same content). I don't know why that occurs.

**Comment by v01dXYZ** [comment]
I understand now why it fails. Polly uses for tests `-O3` which means any changes to the default passes could break them.

Attached bellow the result depending

``` shell
$LLVM_BUILD/bin/opt \
-polly-process-unprofitable  \
-polly-remarks-minimal  \
-polly-use-llvm-names  \
-polly-import-jscop-dir=$LLVM_ROOT/polly/test/Support  \
-polly-codegen-verify  \
-O3 \
-polly \
-polly-position=before-vectorizer \
-disable-output \
$LLVM_ROOT/polly/test/Support/pipelineposition.ll \
--print-before-all 2>&1
```
Below is the output of the above comment depending on the commit

* pass tests: e174704c52061fc688c07fce4f34b8e6db8766bd [file](https://github.com/llvm/llvm-project/files/15267351/polly_print_right.txt)
* fail tests: e174704c52061fc688c07fce4f34b8e6db8766bd [file](https://github.com/llvm/llvm-project/files/15267350/polly_print_wrong.txt)

**Comment by v01dXYZ** [comment]
More precisely, here is the IR dump before constraint elimination:

``` llvm
define void @caller(i32 %n, ptr noalias nocapture nonnull writeonly %A) local_unnamed_addr {
entry:
  br label %for

for:                                              ; preds = %callee.exit, %entry
  %i = phi i32 [ 0, %entry ], [ %j.inc, %callee.exit ]
  %i.cmp = icmp slt i32 %i, %n
  br i1 %i.cmp, label %body, label %return

body:                                             ; preds = %for
  %j.cmp1.i = icmp sgt i32 %n, 0
  br i1 %j.cmp1.i, label %body.i, label %callee.exit

body.i:                                           ; preds = %body.i, %body
  %j2.i = phi i32 [ %j.inc.i, %body.i ], [ 0, %body ]
  %idx.i = add nuw i32 %j2.i, %i
  %0 = sext i32 %idx.i to i64
  %arrayidx.i = getelementptr inbounds double, ptr %A, i64 %0
  store double 4.200000e+01, ptr %arrayidx.i, align 8, !alias.scope !0
  %j.inc.i = add nuw nsw i32 %j2.i, 1
  %j.cmp.i = icmp slt i32 %j.inc.i, %n
  br i1 %j.cmp.i, label %body.i, label %callee.exit

callee.exit:                                      ; preds = %body, %body.i
  %j.inc = add nuw nsw i32 %i, 1
  br label %for

return:                                           ; preds = %for
  ret void
}
```

When adding the SCEV ranges as facts to the header, it adds `%i >= 0` which would allow elimination of `%n >= 0` in `body`.

It doesn't seem to alter what's being tested for Polly (and neither the produced optimised IR).

**Comment by v01dXYZ** [comment]
@fhahn I think the PR is ready. The changes are mainly for `ConstraintElimination`/`ConstraintSystem` which is a part where the major contributor seems to be you. Thus my request for a review.

**Comment by v01dXYZ** [comment]
@fhahn ping

**Comment by v01dXYZ** [comment]
thanks I'm solving the formatting thing right now. I don't know why I didn't spot it previously. Is there any other important CI pipelines that need manual actions ?

**Comment by fhahn** [comment]
Computing the ranges unconditionally requires computing the BTC for all loops, which is quite expensive https://llvm-compile-time-tracker.com/compare.php?from=53d6cfb1d184127a57132657f41104b21e7c0f2b&to=86f4583def5ebd87a1ac08a819fee85f6fc53ae7&stat=instructions:u

Not sure if the benefit warrants the increase; do you have any statistics on larger software how beneficial this is?

Also it would probably be good to split off c41b5b55860b5afaef6d7dca643d77a817bdb1c9 at least to a separate PR

**Comment by nikic** [comment]
https://github.com/llvm/llvm-project/pull/76299 seems related to the second commit.

**Comment by v01dXYZ** [comment]
@fhahn I don't have statistics to motivate this change wrt perf regressions, my first goal was to have feature parity with gcc and I didn't take the performance regressions into account as I should have. I will take a look at `llvm-opt-benchmark`.

Also, to better justify which kind of expression where it would be acceptable to perform a range analysis, I'm currently taking a look at gcc. gcc uses the Ranger framework which was already mentioned in the review for `ConstraintSystem`: https://reviews.llvm.org/D84547#2174140. 

With only `O2` level, the analysis is done during Early Variable Range Propagation (evrp). It is able to infer the range if the induction variable is additive, but if we use a multiplicative induction variable the inferred range is too approximated. With a `O3` level, the right range could be nonetheless inferred in the `dom3` pass, which is not present at lower optimisation levels.

I think it will make me busy for two weeks at least before writing a message here with perf stats and good justifications of which sort of variables should be range analysed.

@nikic thanks for pointing out this MR, I made a mistake `continue` should be replaced by `NR.clear(); break;`.

**Comment by v01dXYZ** [comment]
As there is work to do on my side, I switch this PR to Draft.

**Comment by v01dXYZ** [comment]
Little update to show some progress even if the work is not completed yet.

To have a verbose output from gcc/Ranger, use the following command line

```
gcc faulty.c -O2 -o - -S -Q --fdump-tree-all-details=- --param=ranger-debug=all
```

The `evrp` pass outputs a lot of interesting information.

The function `number_of_iterations_exit` is similar to `computeExitLimit`. `tree_niter_desc` is almost the same as `ExitLimit`.
The function `estimate_number_of_iterations` is similar to `computeBackedgeTakenCount`.

It seems to me at the moment `gcc` tries to compute the loop BTC for the loop (or at least the smallest upper bound it can be sure of).

Below to remind me the calling functions a backtrace of `number_of_iterations_exit`:

<details> 
<summary> Backtrace </summary>

``` console
#0  number_of_iterations_exit (loop=loop@entry=0x7ffff7b2c4b0, exit=exit@entry=0x7ffff7d08a80, niter=niter@entry=0x7fffffffbe20, warn=warn@entry=false, every_iteration=every_iteration@entry=false, body=body@entry=0x3160520) at ../.././gcc/tree-ssa-loop-niter.cc:3285
#1  0x0000000001195796 in estimate_numbers_of_iterations (loop=loop@entry=0x7ffff7b2c4b0) at ../.././gcc/tree-ssa-loop-niter.cc:4882
#2  0x0000000001199156 in loop_exits_before_overflow (base=0x7ffff7d01de0, step=0x7ffff7d01de0, at_stmt=0x7ffff7cdaa00, loop=0x7ffff7b2c4b0) at ../.././gcc/tree-ssa-loop-niter.cc:5286
#3  scev_probably_wraps_p (var=var@entry=0x0, base=base@entry=0x7ffff7d01de0, step=step@entry=0x7ffff7d01de0, at_stmt=at_stmt@entry=0x7ffff7cdaa00, loop=0x7ffff7b2c4b0, use_overflow_semantics=use_overflow_semantics@entry=true) at ../.././gcc/tree-ssa-loop-niter.cc:5538
#4  0x00000000013a2622 in get_scev_info (r=..., name=0x7ffff7b2c4b0, stmt=<optimized out>, l=0x7ffff7b2c4b0, init=<synthetic pointer>: <optimized out>, step=<synthetic pointer>: <optimized out>, dir=<synthetic pointer>: <optimized out>) at ../.././gcc/vr-values.cc:204
#5  range_of_var_in_loop (v=..., name=name@entry=0x7ffff7d130d8, l=0x7ffff7b2c4b0, stmt=0x7ffff7cdaa00, query=0x313c140) at ../.././gcc/vr-values.cc:271
#6  0x0000000001f0992c in fold_using_range::range_of_ssa_name_with_loop_info (this=<optimized out>, r=..., name=0x7ffff7d130d8, l=<optimized out>, phi=<optimized out>, src=...) at ../.././gcc/gimple-range-fold.cc:1114
#7  0x0000000001f09fdb in fold_using_range::range_of_phi (this=this@entry=0x7fffffffd64f, r=..., phi=phi@entry=0x7ffff7cdaa00, src=...) at ../.././gcc/gimple-range-fold.cc:981
#8  0x0000000001f0d3d1 in fold_using_range::fold_stmt (this=this@entry=0x7fffffffd64f, r=..., s=s@entry=0x7ffff7cdaa00, src=..., name=name@entry=0x7ffff7d130d8) at ../.././gcc/gimple-range-fold.cc:606
#9  0x0000000001ef896e in gimple_ranger::fold_range_internal (this=0x313c140, r=..., s=0x7ffff7cdaa00, name=0x7ffff7d130d8) at ../.././gcc/gimple-range.cc:277
#10 gimple_ranger::range_of_stmt (this=0x313c140, r=..., s=0x7ffff7cdaa00, name=<optimized out>) at ../.././gcc/gimple-range.cc:338
#11 0x0000000001ef8bb2 in gimple_ranger::register_inferred_ranges (this=0x313c140, s=s@entry=0x7ffff7cdaa00) at ../.././gcc/gimple-range.cc:498
#12 0x0000000001304d41 in rvrp_folder::pre_fold_bb (this=0x7fffffffde20, bb=0x7ffff7cdca80) at ../.././gcc/tree-vrp.cc:1017
#13 0x00000000011e377e in substitute_and_fold_dom_walker::before_dom_children (this=0x7fffffffdd50, bb=0x7ffff7cdca80) at ../.././gcc/tree-ssa-propagate.cc:762
#14 0x0000000001e9db9e in dom_walker::walk (this=0x7fffffffdd50, bb=0x7ffff7cdca80) at ../.././gcc/domwalk.cc:311
#15 0x00000000011e2526 in substitute_and_fold_engine::substitute_and_fold (this=this@entry=0x7fffffffde20, block=block@entry=0x0) at ../.././gcc/tree-ssa-propagate.cc:999
#16 0x000000000130201d in execute_ranger_vrp (fun=0x7ffff7d0d0c0, warn_array_bounds_p=false, final_p=<optimized out>) at ../.././gcc/tree-vrp.cc:1080
#17 0x0000000000ec6419 in execute_one_pass (pass=pass@entry=0x3099300) at ../.././gcc/passes.cc:2649
#18 0x0000000000ec6d20 in execute_pass_list_1 (pass=0x3099300) at ../.././gcc/passes.cc:2758
#19 0x0000000000ec6d32 in execute_pass_list_1 (pass=0x3098e00) at ../.././gcc/passes.cc:2759
#20 0x0000000000ec6d59 in execute_pass_list (fn=0x7ffff7d0d0c0, pass=<optimized out>) at ../.././gcc/passes.cc:2769
#21 0x0000000000ec768d in do_per_function_toporder (callback=callback@entry=0xec6d40 <execute_pass_list(function*, opt_pass*)>, data=0x3098b60) at ../.././gcc/passes.cc:1774
#22 0x0000000000ec78cf in do_per_function_toporder (data=<optimized out>, callback=0xec6d40 <execute_pass_list(function*, opt_pass*)>) at ../.././gcc/passes.cc:1741
#23 execute_ipa_pass_list (pass=0x3098ae0) at ../.././gcc/passes.cc:3103
#24 0x0000000000aed8d7 in ipa_passes () at ../.././gcc/cgraphunit.cc:2214
#25 symbol_table::compile (this=0x7ffff7b2d000) at ../.././gcc/cgraphunit.cc:2337
#26 0x0000000000af06ad in symbol_table::compile (this=0x7ffff7b2d000) at ../.././gcc/cgraphunit.cc:2315
#27 symbol_table::finalize_compilation_unit (this=0x7ffff7b2d000) at ../.././gcc/cgraphunit.cc:2589
#28 0x0000000000ff46b2 in compile_file () at ../.././gcc/toplev.cc:476
#29 0x00000000009076dc in do_compile () at ../.././gcc/toplev.cc:2158
#30 toplev::main (this=this@entry=0x7fffffffe6de, argc=<optimized out>, argc@entry=15, argv=<optimized out>, argv@entry=0x7fffffffe738) at ../.././gcc/toplev.cc:2314
#31 0x0000000000908ebe in main (argc=15, argv=0x7fffffffe738) at ../.././gcc/main.cc:39
```
</details>

Some interesting classes I am still trying to understand:

* `rvrp_folder` inherits `substitute_and_fold`. The latter uses a dom walker which will do a DFS while locally sorting the children according to the CFG reverse post-order, see `before_dom_children` for that.
* `range_query` has a member `relation_oracle` which is an equivalent to ConstraintSystem, keeping track of the relations between different expressions.
* `gimple_ranger`, `ranger_cache`

Some abbreviations:

* GORI: Generates Output Range Info
* chrec: chain of recurrence
* fur: fold under range

**Comment by v01dXYZ** [comment]
A little fact, LLVM also computes the BTC when the `add` is not marked explicity with both `nuw nsw` to compute the NUW/NSW flag when creating the SCEV expression. Reminder for myself, look at `proveNoWrapViaConstantRanges()`, use `AR->hasNoSelfWrap()` to find an upper bound for the AR, which is absolutely equivalent to upper bound the BTC. ( `computeMaxBECountForLT` `howManyLessThans/howManyGreaterThans` ?).

It seems SCEV don't use the NSW/NUW info when computing BTC which is a little bit suprising (when having a start greater than the end I expect it to have a range looking like `[start, start+1)` ie `BTC == 0` but it's rather `[start, TYPE_MAX)`.

**Comment by v01dXYZ** [comment]
I think you're right about not using the range information in this pass, as this pass seems to simplify using mainly a forward approach which traverses the CFG while keeping track of the branch conditions associated to the dominating edges (among other things). 

Supporting this case would be against this simple forward approach.

There are other passes that do a range analysis but do not simplify icmp.

* SCCP: lattice -> set NUW/NSW for add
* Correlated Propagation: Lazy Value Info / Value Lattice -> set NUW/NSW for add
* Ind Var: SCEV

**Comment by v01dXYZ** [comment]
I think I found a possible solution with a minor change in `IndVarSimplify` / `SimplifyIndVar`. It seems the instructions eligible to simplifications are only the ones within the current loop (cf `pushIVUsers`), I wonder if we can also consider eligible instructions that are not in any loop. It seems to work but I didn't test the performance regressions. So still WIP.

**Comment by v01dXYZ** [comment]
This PR has been superseded by #93598  as it appears `ConstraintElimination` is not the right pass for optimisation of Induction Variable Users that occur post-loop. I stop working on it and close it.

**Pull request closed without merging**
