### PR TITLE
Fix to account for multiple ISA enumeration

### PR DESCRIPTION
**Pull request by hidekisaito**
When multiple ISAs are enumerated per agent, existing code picked up the last one. Incumbent is the first one and thus the fixed code picks up the first one. This fix is expected to be short-lived --- to be followed by code object version 6 generic ISA support.

### CODE REVIEW

**Review by jhuber6 — APPROVED** [review]
Good short-term fix, long term we just need to handle multiple of these and push them back. Then we can scan all the ISAs from least generic  to most generic through some complicated lookup table.

**Comment by shiltian** [comment]
> Good short-term fix, long term we just need to handle multiple of these and push them back. Then we can scan all the ISAs from least generic to most generic through some complicated lookup table.

This is not a short term fix. The iteration always starts from specific to generic, so there must be only one match. It is just code error not stopping it on the first match.

**Comment by shiltian** [comment]
Also, this PR doesn't have proper prefix, such as `[Offload][AMDGPU]`.

**Comment by jhuber6** [comment]
> Also, this PR doesn't have proper prefix, such as `[Offload][AMDGPU]`.

Forgot to fix that before I hit merge.

> This is not a short term fix. The iteration always starts from specific to generic, so there must be only one match. It is just code error not stopping it on the first match.

That's not what the code is doing, it's copying out the first result to *then* do a comparison. Maybe we could move the check inside of the iterate callback and then break when we first find a match?

> I also don't think it's a good idea to maintain a match table at OpenMP level.

Not the OpenMP level, we need one at the ELF flags level.

**Comment by shiltian** [comment]
> Not the OpenMP level, we need one at the ELF flags level.

The generic ELF has to match generic ISA provided by HSA. There is no need to do that at the ELF flag level. For example, if the ELF is `gfx10-3-generic`, it should _not_ work with `gfx1030`, at least not based on the design of HSA.

**Pull request merged**
