### PR TITLE
[RISCV][GISel] Rename XLenVT sXLen to be consistent with other LLTs.

### PR DESCRIPTION
**Pull request by topperc**
This also renames DoubleXLenLLT to sDoubleXLen.

### CODE REVIEW

**Review by asb — APPROVED** [review]
LGTM, but feel free to wait for review from those who may have developed more emotional attachment to the current naming!

sDoubleXLen seems fine and is probably easier to read than s2Xlen.

**Review by michaelmaitland — APPROVED** [review]
LGTM.

**Review by mshockwave — APPROVED** [review]
Personally I like LLT to be in the name since I sometimes got confused. But I think consistency is more important in a long term, thus LGTM

**Comment by michaelmaitland** [comment]
> Personally I like LLT to be in the name since I sometimes got confused

Sounds like you are suggesting this change && s16LLT, s32LLT, ...

The `LLT` designation is available to the reader if they look at the type is what made me comfortable giving this a LGTM.

**Pull request merged**
