### PR TITLE
[MLIR][FuncToLLVM] Remove typed pointer support

### PR DESCRIPTION
**Pull request by Dinistro**
This commit removes the support for lowering Func to LLVM dialect with typed pointers. Typed pointers have been deprecated for a while now and it's planned to soon remove them from the LLVM dialect.

Related PSA: https://discourse.llvm.org/t/psa-removal-of-typed-pointers-from-the-llvm-dialect/74502

### CODE REVIEW

**Review by zero9178 — APPROVED** [review]
LGTM

**Comment by joker-eph** [comment]
Can you also send a patch to https://mlir.llvm.org/deprecation/ to document the current refactoring and how people should migrate?

**Comment by Dinistro** [comment]
> Can you also send a patch to https://mlir.llvm.org/deprecation/ to document the current refactoring and how people should migrate?

Opened a PR: https://github.com/llvm/mlir-www/pull/161

**Comment by Dinistro** [comment]
Had to revert due to the `mlir-vulkan-runner` using the pass option struct changed in this PR.

**Pull request merged**
