### PR TITLE
[lldb] Reduce the frequency of DWARF index progress reporting

### PR DESCRIPTION
**Pull request by labath**
Indexing a single DWARF unit is a relatively fast operation, particularly if it's a type unit, which can be very small. Reporting progress takes a mutex (and allocates memory, etc.), which creates a lot of contention and slows down indexing noticeably.

This patch reports makes us report progress only once per 10 milliseconds (on average), which speeds up indexing by up to 55%. It achieves this by checking whether the time after indexing every unit. This creates the possibility that a particularly large unit could cause us to stop reporting progress for a while (even for units that have already been indexed), but I don't think this is likely to happen, because:
- Even the largest units don't take that long to index. The largest unit in lldb (4MB of .debug_info) was indexed in "only" 200ms.
- The time is being checked and reported by all worker threads, which means that in order to stall, we'd have to be very unfortunate and pick up an extremely large compile unit on all indexing threads simultaneously.

Even if that does happens, the only negative consequence is some jitteriness in a progress bar, which is why I prefer this over alternative implementations which e.g. involve reporting progress from a dedicated thread.

### CODE REVIEW

**Comment by SingleAccretion** [comment]
I would like to say I would love for this improvement to land :).

I have observed that on Windows with a good number (4K+) of small compile units the progress reporting completely dominates indexing time due to contention (presumably not just in the lock but also the IO layers), to the point that disabling it resulted in __very__ large speedup (an operation which previously took 5s+ now was almost instant).

**Review by JDevlieghere — APPROVED** [review]
🚢

**Review by clayborg — COMMENTED** [review]
Can we build this feature into the Progress class by calling an accessor? Something like:

```
Progress progress("Manually indexing DWARF", module_desc.GetData(), total_progress);
progress.SetMinimumNotificationTime(std::chrono::milliseconds(10));
```
Then any busy progress dialogs can take advantage of this timing feature?

**Comment by clayborg** [comment]
And the Progress class can check if the an optional instance variable that contains the minimum time has a value and avoid taking the mutex to keep things faster even when building this into the Progress class?

**Comment by labath** [comment]
> Can we build this feature into the Progress class by calling an accessor? Something like:
> 
> ```
> Progress progress("Manually indexing DWARF", module_desc.GetData(), total_progress);
> progress.SetMinimumNotificationTime(std::chrono::milliseconds(10));
> ```
> 
> Then any busy progress dialogs can take advantage of this timing feature?

That's possible, but there are a couple of caveats:
- in the Progress class implementation, we'd only have a single "time of last progress report" member, which would mean that (in order for it to be lock-free) it would have to be atomic. As there's no `atomic<duration>`, this would have to be a raw "time since epoch") timestamp. It's fine, but slightly uglier, and it's also one more atomic. In this version I was able to get away with it by essentially making the timestamp thread-local, which is sort of nice, but also less correct than the hypothetical version with a single variable, so maybe that's okay..
- this implementation only works if the progress updates come at a fairly fast and steady rate. This is the case here, but may not be true for all usages. With this implementation, if you have something that tries to send e.g. 9 (out of 10) progress updates very quickly (within the 10ms interval), but then gets spends a lot of time (many seconds) on the last part, the progress bar will stay stuck at `1/10 ` because we've ignored the updates 2--9. Attempting to schedule some sort of to send the `9/10` event after a timeout would probably involve spinning up another thread, and all of this management would make the code significantly more complicated (and slower).

This is the reason I did not want to make this a general feature, but it's not strong opinion, so if you're find with these trade-offs, I can move the code into the Progress class. I definitely don't want get into the business of managing another thread though.

**Comment by clayborg** [comment]
What is the resolution if we switch to "time since epoch" in an atomic value? Can we use some casting to cast a double back into a uint64_t for storage in an atomic?

It would be nice to not require everyone to roll their own timeout if possible by just calling an accessor. I am ok with the caveats if everyone else is.

**Comment by labath** [comment]
> What is the resolution if we switch to "time since epoch" in an atomic value? Can we use some casting to cast a double back into a uint64_t for storage in an atomic?
> 

That's not a problem. I was referring to the time_point::time_since_epoch() (which returns arbitrary precision), not the unix "seconds since epoch" concept. I've created an alternative implementation in #119377

**Comment by labath** [comment]
> I would like to say I would love for this improvement to land :).
> 
> I have observed that on Windows with a fair number (4K+) of small compile units the progress reporting completely dominates indexing time due to contention (presumably not just in the lock but also the IO layers), to the point that disabling it resulted in **very** large speedups (an operation which previously took 5s+ now was almost instant).

Thanks. I think that in your case we're limited by the speed of console updates rather than the progress mutex. We've gotten similar reports for high ("high") latency ssh connections and unusual console setups, and that's the angle I've started working this from before I realized the it was bottlenecking the parallelism. If you have some time, I'd be grateful if you could test this patch out. The thing want the see is whether this completely resolves your issue or if you still see a difference between disabled&enabled progress reports. The reason I'm asking that is that I have a prototype which should specifically help with the slow console issue, and I'm wondering if that is necessary, or if this patch is sufficient.

**Comment by labath** [comment]
> this patch

or the other patch (https://github.com/llvm/llvm-project/pull/119377). Either is fine for the thing I want to see.

**Comment by labath** [comment]
That's great. Thanks for checking this out. 

Closing this patch in favor of https://github.com/llvm/llvm-project/pull/119377.

**Pull request closed without merging**
