### PR TITLE
[CMake] Make specifying invalid build type a fatal error

### PR DESCRIPTION
**Pull request by boomanaiden154**
This patch makes it so that specifying an invalid value for CMAKE_BUILD_TYPE is a fatal error. Having this simply as a warning has caused me (and probably others) a decent amount of headache. The check was present before, but was proposed to be modified to a warning in https://github.com/llvm/llvm-project/issues/60975 and changed to a warning in c75dbeda15c10424910ddc83a9ff7669776c19ac. This patch reenables that behavior to hopefully reduce frustration for people building LLVM in the common case while still allowing for alternative build types to be setup without needing to perform source modification through the addition of a CMake flag.

### CODE REVIEW

**Comment by boomanaiden154** [comment]
Pinging @rossburton on this as he was the original author of the issue.

**Comment by rossburton** [comment]
That's acceptable to me at least - we can just allow the extra types.

**Review by fsb4000 — APPROVED** [review]
Yes. Looks good. Warnings could be often ignored and we can define LLVM_ADDITIONAL_BUILD_TYPES  if we need custom build type.

**Comment by boomanaiden154** [comment]
Thanks for the reviews and the compromise here!

**Pull request merged**
