### PR TITLE
[concepts] Preserve the FoundDecl of ConceptReference properly

### LINKED ISSUE #82628: Missing FoundDecl in ConceptReference.
Given the following code, the `FoundDecl` is null in the `Foo`'s AST node (`ConceptReference`).

```
namespace ns {
template<typename T> concept Foo = true;
}

using ns::Foo;
template<typename T>concept Bar = Foo<T>;  // reference `Foo` points to the underlying of ns::Foo, rather than the `using` decl.
```

This breaks some clang tools: include-cleaner will report the file of the underlying decl, rather than the one for using decl; clangd's go-to-def on `Foo` jumps to the underlying decl.

### PR DESCRIPTION
**Pull request by zyn0217**
The `ConceptReference`'s `FoundDecl` claims it "can differ from `NamedConcept` when, for example, the concept was found through a `UsingShadowDecl`", but such the contract was not previously respected.

Fixes https://github.com/llvm/llvm-project/issues/82628

### CODE REVIEW

**Review by sam-mccall — APPROVED** [review]
Very nice, thanks!

**Review by Endilll — COMMENTED** [review]
`Sema.h` changes look good to me.

**Review by hokein — APPROVED** [review]
Thanks for the investigation and fix!

**Comment by zyn0217** [comment]
(Waiting for the CI before landing it. As usual, thank you all for the review!)

**Comment by zyn0217** [comment]
CI failure was an unrelated format issue.

**Pull request merged**
