### PR TITLE
[Clang][NFCI] Slightly refactor getTemplateInstantiationArgs()

### PR DESCRIPTION
**Pull request by zyn0217**
`getTemplateInstantiationArgs()` takes two parameters `ND` and `DC` to determine the starting point of a traversal. Previously, `DC` would be ignored in the presence of `ND`, and the next declaration context would almost always be the semantic context of `DC` if `Innermost` is specified.

Actually, we could harness `DC` to describe where we want to go after placing an `Innermost` template argument list, because `DC` was never used if `ND` is present, but anyhow we still have passed in `DC` with the semantic declaration context at the caller sides.

This is in preparation for CWG 2369.

### CODE REVIEW

**Review by mizvekov — COMMENTED** [review]
I think I'd need to see how you would use it, to say if this would be the best approach.

It's not clear to me why we would want to navigate to a DC that is unrelated to the passed ND.

**Comment by zyn0217** [comment]
> I think I'd need to see how you would use it, to say if this would be the best approach.

(I thought I have explained somewhere, but it seems not. Sorry!)

So the basic idea of CWG2369 is to swap the order of the function template substitution and its constraint checking. We previously relied on the substituted function to collect the entire template argument lists for the constraint evaluation to work, while this is no longer the case because we're now required to check the constraint before the function declaration substitution.

The situation is then slightly subtle since we don't have a complete function specialization to collect the complete arguments in one go. So it would end up with two pieces: one is the instantiating template arguments that we have (`CanonicalBuilder` / `SugaredBuilder`) for the current function template; the other part consisted of the template arguments of the parent `DeclContext`s. My idea is to splice these template arguments together through the parameter `Innermost` of the `getTemplateInstantiationArgs()`, and in that case we have to switch the next DC to its lexical declaration context, similar to what we're going to visit after a `FunctionTemplateDecl` in `HandleFunctionTemplateDecl()`.

**Comment by mizvekov** [comment]
I think we could instead simplify the function to the following signature:
```C++
MultiLevelTemplateArgumentList Sema::getTemplateInstantiationArgs(
    const Decl *D, bool LexicalParent, bool Final, .....)
```

Ie we take a single decl, which we will assume is a NamedDecl in case Innermost is provided, and in that case continue to either it's semantic or lexical parent, depending on `LexicalParent` parameter.

As an improvement on that, we can basically reuse the logic we already have for deciding which parent to visit next, which is already used in the normal case. Either refactor that, or just add an internal 'bool' parameter that controls if the implementation will add the template parameters, and call that from the 'Innermost' path with adding the arguments disabled.
That way, we can do away with the `LexicalParent` parameter as well.

Does that make sense? Would that work for you?

**Comment by zyn0217** [comment]
> simplify the function to the following signature:

I'm afraid we couldn't. We have one reliance on the `DC` parameter in constraint expression comparison, where we're unable to obtain a Decl as that is not formed yet. So dropping the `DC` parameter doesn't work here.

If you probably meant to add another overload, I think that might work; although it looks the same way we add another bool flag.

> As an improvement on that, we can basically reuse the logic we already have for deciding which parent to visit next, which is already used in the normal case [...] or just add an internal 'bool' parameter that controls if the implementation will add the template parameters, and call that from the 'Innermost' path with adding the arguments disabled

Yeah, this is tempting; I was also thinking about adding an additional parameter, but that somehow makes the function more complicated and I do feel like ending up with many bool flags results in a heavier maintenance burden..

**Comment by zyn0217** [comment]
> Either refactor that, or just add an internal 'bool' parameter that controls if the implementation will add the template parameters, and call that from the 'Innermost' path with adding the arguments disabled.

Thinking twice, I think this is probably feasible to go. As an internal flag wouldn't be exposed to users, but we might have to refactor the function a lot more.

**Comment by mizvekov** [comment]
> Thinking twice, I think this is probably feasible to go. As an internal flag wouldn't be exposed to users, but we might have to refactor the function a lot more.

Yep. Just don't forget to assert in case the template arguments wouldn't get added, to diagnose users passing Innermost with a declaration which doesn't take template arguments :)

**Comment by zyn0217** [comment]
Superseded by https://github.com/llvm/llvm-project/pull/106585.

**Pull request closed without merging**
