### PR TITLE
[MSSA] Don't check non-AA memory effects when using template access

### PR DESCRIPTION
**Pull request by nikic**
Sometimes, we create a MemoryAccess for an instruction, which is later simplified (e.g. via devirtualization) such that the new instruction has no memory effects anymore.

If we later clone the instruction (e.g. during unswitching), then MSSA will not create a MemoryAccess for the new instruction, breaking MSSAU assumptions.

There are principally two ways to solve this. The first is to remove the assumption that a MemoryAccess will be created from MSSAU. I initially pursued this approach, but it is not as simple as it sounds. The core problem is that if there is another later access in the block, we'll have to find a new defining access for it. This is easy if there is another MemoryDef before the MemoryDef we're no longer creating, but becomes complicated if it was the first access in the block. In that case we might have to insert a MemoryPhi and perform the necessary rewrites, which sounds like all too much hassle for this edge-case.

The alternative implemented here is to make sure that the template access is always used if it is specified -- even if we have obtained better information in the meantime. This was already the case wrt AA queries, but the separate non-AA check was performed unconditionally beforehand. Move this check into the non-template branch only.

### CODE REVIEW

**Review by alinas — COMMENTED** [review]
I think this makes sense as the simple way to address this.
There's also the option to generalize what to do in the case of accesses that are optimized further.
I *think* that's possible but I may be missing edge cases not covered by current tests. Something like this resolves the testcases in this PR:
```
diff --git llvm/lib/Analysis/MemorySSAUpdater.cpp llvm/lib/Analysis/MemorySSAUpdater.cpp
index 9ad60f774e9f..0e533cb54f15 100644
--- llvm/lib/Analysis/MemorySSAUpdater.cpp
+++ llvm/lib/Analysis/MemorySSAUpdater.cpp
@@ -578,18 +578,9 @@ static MemoryAccess *getNewDefiningAccessForClone(MemoryAccess *MA,
       if (Instruction *NewDefMUDI =
               cast_or_null<Instruction>(VMap.lookup(DefMUDI))) {
         InsnDefining = MSSA->getMemoryAccess(NewDefMUDI);
-        if (!CloneWasSimplified)
-          assert(InsnDefining && "Defining instruction cannot be nullptr.");
-        else if (!InsnDefining || isa<MemoryUse>(InsnDefining)) {
+        if (!InsnDefining || isa<MemoryUse>(InsnDefining)) {
           // The clone was simplified, it's no longer a MemoryDef, look up.
-          auto DefIt = DefMUD->getDefsIterator();
-          // Since simplified clones only occur in single block cloning, a
-          // previous definition must exist, otherwise NewDefMUDI would not
-          // have been found in VMap.
-          assert(DefIt != MSSA->getBlockDefs(DefMUD->getBlock())->begin() &&
-                 "Previous def must exist");
-          InsnDefining = getNewDefiningAccessForClone(
-              &*(--DefIt), VMap, MPhiMap, CloneWasSimplified, MSSA);
+          InsnDefining = getNewDefiningAccessForClone(DefMUD->getDefiningAccess(), VMap, MPhiMap, CloneWasSimplified, MSSA);
         }
       }
     }
@@ -626,7 +617,7 @@ void MemorySSAUpdater::cloneUsesAndDefs(BasicBlock *BB, BasicBlock *NewBB,
             getNewDefiningAccessForClone(MUD->getDefiningAccess(), VMap,
                                          MPhiMap, CloneWasSimplified, MSSA),
             /*Template=*/CloneWasSimplified ? nullptr : MUD,
-            /*CreationMustSucceed=*/CloneWasSimplified ? false : true);
+            /*CreationMustSucceed=*/false);
         if (NewUseOrDef)
           MSSA->insertIntoListsForBlock(NewUseOrDef, NewBB, MemorySSA::End);
       }
```
But needs cleanup then of "CloneSimplified" that's now losing its purpose.

If you move fwd with creating accesses for non-memory affecting instructions, a follow up optimization could be to remember those accesses that were still created using a template, then call `removeMemoryAccess` (leaving optimizePhis to false) on those, after cloning and new phi assignment is complete. This should redirect the defining accesses properly.

**Comment by nikic** [comment]
> I think that's possible but I may be missing edge cases not covered by current tests. Something like this resolves the testcases in this PR:

I think this may chose an incorrect defining access in some cases.

Let's say we have the following initial structure:

```
writes x
writes y
now_readnone (defining: writes x)
reads y (defining: now_readnone)
```

The important part is that the defining access of `now_readnone` skips an intermediate MemoryDef for whatever reason (say TBAA metadata).

Then, I think your new code would set the defining access of clone(reads y) to clone(writes x), even though the correct one would be clone(writes y).

> If you move fwd with creating accesses for non-memory affecting instructions, a follow up optimization could be to remember those accesses that were still created using a template, then call removeMemoryAccess (leaving optimizePhis to false) on those, after cloning and new phi assignment is complete. This should redirect the defining accesses properly.

Something we could also do is to already clean up such accesses inside LoopInstSimplify. That is, if we see that a callee has been replaced by a constant, check whether the access can be removed. This has the benefit that we'll simplify the original access as well, not just the cloned access. (Though I don't think we should rely on this happening, as there's just too many ways in that AA results can change.)

**Comment by nikic** [comment]
ping

**Comment by alinas** [comment]
In your example `nowreadnone` is a MemoryDef, which doesn't get the defining access updated. It has an optimized field which will be set to `writes x` but its defining should still be `writes y`. 
The mechanism for deleting accesses relies on this too. If a clone is created for `nowreadnone`, then deleted later (if checked and found it doesn't access memory), then all it's uses will get as the defining access, its own defining access.

I'm ok with moving fwd with this solution to resolve the asserts. I haven't found a counter example for the generalization yet, but I need more time to check it's safe, it's still possible it's missing cases where it's not correct.

**Review by alinas — APPROVED** [review]

**Comment by nikic** [comment]
> In your example `nowreadnone` is a MemoryDef, which doesn't get the defining access updated. It has an optimized field which will be set to `writes x` but its defining should still be `writes y`. The mechanism for deleting accesses relies on this too. If a clone is created for `nowreadnone`, then deleted later (if checked and found it doesn't access memory), then all it's uses will get as the defining access, its own defining access.

Ah yes, good point.

> I'm ok with moving fwd with this solution to resolve the asserts. I haven't found a counter example for the generalization yet, but I need more time to check it's safe, it's still possible it's missing cases where it's not correct.

Hm, could it happen that the new defining access ends up in a different block, for which we haven't cloned accesses yet?

**Comment by alinas** [comment]
I don't think that's possible. The cloning logic works in RPO, so all clones are completed for defining accesses.

**Comment by nikic** [comment]
I went ahead and put up another PR with your variant: https://github.com/llvm/llvm-project/pull/76819 You convinced me that this approach is correct, and I think it's a bit cleaner overall.

**Comment by nikic** [comment]
Closing in favor of https://github.com/llvm/llvm-project/pull/76819.

**Pull request closed without merging**
