### PR TITLE
[RISCV] Add documentation that Zvbc and Zvk* are supported through intrinsics. NFC

### PR DESCRIPTION
**Pull request by topperc**

### CODE REVIEW

**Review by preames — APPROVED** [review]
LGTM

**Comment by 4vtomat** [comment]
Do we also need to change `zvbb` to supported in this patch?
Or it can be in another patch?

**Comment by 4vtomat** [comment]
> Do we also need to change `zvbb` to supported in this patch?
> Or it can be in another patch?

Oh I just saw it in another patch!

**Review by 4vtomat — APPROVED** [review]
LGTM~

**Pull request merged**
