### PR TITLE
[AArch64][PAC] Support BLRA* instructions in SLS Hardening pass

### PR DESCRIPTION
**Pull request by atrosinenko**
Make SLS Hardening pass handle BLRA* instructions the same way it handles BLR. The thunk names have the form

    __llvm_slsblr_thunk_xN            for BLR thunks
    __llvm_slsblr_thunk_(aaz|abz)_xN  for BLRAAZ and BLRABZ thunks
    __llvm_slsblr_thunk_(aa|ab)_xN_xM for BLRAA and BLRAB thunks

Now there are about 1800 possible thunk names, so do not rely on linear thunk function's name lookup and parse the name instead.

This patch reapplies llvm/llvm-project#97605.

### CODE REVIEW

**Comment by atrosinenko** [comment]
The only difference with the original version applied in #97605 and reverted in #97887 is copying the temporary created by `BuildMI` instead of taking reference in `populateThunk`:
```
-  auto &Builder =
+  MachineInstrBuilder Builder =
       BuildMI(Entry, DebugLoc(), TII->get(Kind.BROpcode)).addReg(AArch64::X16);
```

**Comment by atrosinenko** [comment]
The [CI failure](https://buildkite.com/llvm-project/github-pull-requests/builds/79096#01909394-0f3c-4136-90f4-87cd922e27e9) seems to be unrelated to this PR: the assertion `Inserting PHI after debug-records!` was triggered when compiling `libcxx`, but IIUC it is native libcxx built by a "Linux x64" builder (x86_64, I assume), so it should not be affected in any way.

The next PR #98063 seems to be affected by the same CI failure, so just rebasing onto current HEAD of the `main` branch (+dropping old PR number from the commit message).

**Review by kovdan01 — APPROVED** [review]
LGTM

**Comment by atrosinenko** [comment]
Looks like the CI failure was fixed by a recent commit, rebased once again.

**Pull request merged**
