### PR TITLE
Reapply "[mlir] Add mlirTranslateModuleToLLVMIR to MLIR-C (#73627)" (#73749)

### PR DESCRIPTION
**Pull request by vitalybuka**

### CODE REVIEW

**Comment by vitalybuka** [comment]
With `LLVMContextDispose(llvmCtx);`

**Comment by vitalybuka** [comment]
FYI @edg-l

**Comment by joker-eph** [comment]
Oh so it was a memory leak?

Do you know why the CI does not print anything?

**Review by joker-eph — APPROVED** [review]
Thanks for the effort!

**Comment by edg-l** [comment]
Oh makes sense, i forgot to dispose the ctx. Sorry i was asleep as this all unfold 😅

**Comment by vitalybuka** [comment]
> Oh so it was a memory leak?
> 
> Do you know why the CI does not print anything?

Because all output is redirected to FileCheck, but the first command fail and FileCheck is not even executed/completed.

**Pull request merged**
