### PR TITLE
Revert "LSV: document hang reported in #37865"

### PR DESCRIPTION
**Pull request by artagnon**
This reverts commit 199d6f2, as there is a buildbot failure: https://lab.llvm.org/buildbot/#/builders/46/builds/2973.

### CODE REVIEW

**Comment by arsenm** [comment]
Should include link to the failure

**Comment by artagnon** [comment]
Done.

**Comment by arsenm** [comment]
This does not need to be reverted. You didn't add the target filtering lit.local.cfg to the new AArch64 directory

**Comment by artagnon** [comment]
Yes, I realized that, but I thought a revert would be preferred to a fix-forward. Never mind; I'll fix-forward then.

**Pull request closed without merging**
