### PR TITLE
[clang][analyzer] Simplify code of StreamChecker (NFC).

### PR DESCRIPTION
**Pull request by balazske**
Common parts of some "eval" functions are moved into one function. The non-common parts of the "eval" functions are passed through lambda parameters to the new function.

### CODE REVIEW

**Comment by balazske** [comment]
Later more functions can be simplified with `evalRWCommon`, probably in a next patch to make the review more simple.

**Comment by steakhal** [comment]
I'm yet to review the PR, but I would express my opinion on the ergonomics of the StreamChecker, as I've spent the last couple of days around it.

I find code duplication less harmful than unnatural generalization over small set of functions (I know, it's a hot take :D).
`std::bind` is harmful, and specific handlers should be preferred. As a rule of thumb, if we need a flag on a top-level API, then that's likely a code-smell.

E.g.: There presence of `IsRead` or `IsSingleChar` (that we need to bind), signals to me that there should be a specific API for the read, write, singleChar and buffer cases. Internally, those could dispatch to a generic call, which has this flag - but at least on the use-sites, we don't need to use `std::bind`, but naturally just taking the address of the member function without any tricks.

I'd also advise against using more callables bundled with CallDescriptions. They make debugging code more difficult, as the control-flow would become also data-dependent. I'd suggest other ways to generalize.
If I have some spare time in the next days, I'm going to also look deeper and come up with actual recommendations.

**Comment by benshi001** [comment]
This change is a bit complex and I need more time to understand.

**Comment by NagyDonat** [comment]
I'm seconding the suggestions of @steakhal, and in particular I agree with
> I'd also advise against using more callables bundled with CallDescriptions. They make debugging code more difficult, as the control-flow would become also data-dependent. I'd suggest other ways to generalize.

Instead of creating this shared framework that calls different callbacks depending on the checked function, consider keeping separate top-level evaluator functions that rely on a shared set of smaller tool-like helper functions.

**Comment by steakhal** [comment]
> I'm seconding the suggestions of @steakhal, and in particular I agree with
> 
> > I'd also advise against using more callables bundled with CallDescriptions. They make debugging code more difficult, as the control-flow would become also data-dependent. I'd suggest other ways to generalize.
> 
> Instead of creating this shared framework that calls different callbacks depending on the checked function, consider keeping separate top-level evaluator functions that rely on a shared set of smaller tool-like helper functions.

One more not about composability.
In general, `addTransition` calls don't compose, thus limits reusability.
For example, `preReadWrite` should be reusable from other precondition handlers, such that the new one can just call `preReadWrite` and then do some other more specialized checks. However, once a handler calls `addTransition` we are done. We no longer can simply wrap it, aka. compose with other functionalities.
Consequently, I'd suggest to have some common pattern, such as return state pointers, or NULL if an error was reported. And leave the `addTransition` to the caller - if they chose to call it.

`eval*` handlers are more difficult to compose, given that they also need to bind the return value and apply their sideffects, but I believe we could achieve similar objectives there too (thus, have refined, composable handlers, combined in useful ways).

**Comment by balazske** [comment]
My concern was the addition of many small functions that are used only from few other `eval*` calls and are relatively special. And all of these need a common big set of arguments like `StreamSym`, `CE`, `Call`. The build of states for success and failure cases in the thing that is really special for the calls.
But I can make another solution with "helper" functions.

**Comment by balazske** [comment]
For clarification, the `evalRWCommon` new function is not planned to be used in the same way as other `eval*` calls, the name may be misleading. This function contains a "generic algorithm" that is called from the other `eval*` calls, but not used directly in `CallDescriptionMap`. The old `eval*` calls and the `evalRWCommon` are not meant to be called from each other, except `evalRWCommon` from other `eval*` calls. I agree that using lambdas makes debugging more difficult and lambdas are not ideal for big parts of code and code formatting is not nice either.

**Comment by benshi001** [comment]
I do not like too long lambda either. In my opinion lambda should be short/compact.

And I do not think the redundancy is serious, except the common part

```
  ProgramStateRef State = C.getState();
  SymbolRef StreamSym = getStreamArg(Desc, Call).getAsSymbol();
  if (!StreamSym)
    return;

  const CallExpr *CE = dyn_cast_or_null<CallExpr>(Call.getOriginExpr());
  if (!CE)
    return;

  const StreamState *OldSS = State->get<StreamMap>(StreamSym);
  if (!OldSS)
    return;

  assertStreamStateOpened(OldSS);
```

which appears in the beginning of most `evalXX` functions. And can we replace this piece with a macro ?

**Comment by benshi001** [comment]
For the part in the end of most `evalXX` functions,

```
StateFailed = ...
StateNotFailed = ...
```

They are quite similar but not identical, so we can generalize them with helper functions.

**Review by NagyDonat — APPROVED** [review]
LGTM, this is a nice little cleanup patch.

**Pull request merged**
