### PR TITLE
[libc++]  Implements LWG3953

### LINKED ISSUE #105303: LWG3953: `iter_move` for `common_iterator` and `counted_iterator` should return `decltype(auto)`
**Link:** https://wg21.link/LWG3953

### PR DESCRIPTION
**Pull request by NoumanAmir657**
Closes #105303

### CODE REVIEW

**Comment by frederick-vs-ja** [comment]
> For the issue:

It would be better to use [GitHub's close/fix/resolve syntax](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword) in the PR description to associate this PR with the issue.

Also, it's better to explicitly say LWG3953 in the title of this PR. Note that the actual return types remain unchanged.

**Review by frederick-vs-ja — APPROVED** [review]
No change requested. The modification is almost, if not exactly, NFC, given `input_iterator` has already required that `iter_rvalue_reference_t` is valid.

It would be extremely weird to me to test something (if exists) for which `iter_rvalue_reference_t` results in substitution failure while `input_iterator` gives hard error (caused by some stuff checked before `iter_rvalue_reference_t`).

**Comment by Zingam** [comment]
You still need to update the cvs file I think:
https://github.com/llvm/llvm-project/blob/86835d2d5a24ed00ed3747b77029c896ba935036/libcxx/docs/Status/Cxx2cIssues.csv#L33

**Comment by NoumanAmir657** [comment]
> You still need to update the cvs file I think:
> 
> https://github.com/llvm/llvm-project/blob/86835d2d5a24ed00ed3747b77029c896ba935036/libcxx/docs/Status/Cxx2cIssues.csv#L33

Updated. Thanks!

**Comment by NoumanAmir657** [comment]
Any idea why the CI failed? @frederick-vs-ja @Zingam .

**Comment by Zingam** [comment]
> Any idea why the CI failed? @frederick-vs-ja @Zingam .

I restarted the failed CI job. Let's wait an see if it will pass.

**Comment by NoumanAmir657** [comment]
> > Any idea why the CI failed? @frederick-vs-ja @Zingam .
> 
> I restarted the failed CI job. Let's wait an see if it will pass.

Aha okay. Thanks.

**Comment by NoumanAmir657** [comment]
> > Any idea why the CI failed? @frederick-vs-ja @Zingam .
> 
> I restarted the failed CI job. Let's wait to see if it will pass.

Yeah seems like it passed now.

**Review by ldionne — APPROVED** [review]

**Comment by ldionne** [comment]
@NoumanAmir657 Thanks for the patch! Please turn off the "hide my email" feature of Github for your future contributions since we require a valid email address for LLVM contributions.

**Pull request merged**
