### PR TITLE
[BPF] lowering target address leaf nodes tconstpool

### PR DESCRIPTION
**Pull request by inclyc**
Adds custom lowering for these leaf nodes.

Please ref: https://github.com/llvm/llvm-project/pull/73668 for test coverage

### CODE REVIEW

**Comment by tamird** [comment]
Please add tests.

**Comment by eddyz87** [comment]
The code lgtm.
Constants pool usage matches other backends (e.g. x86) and #73668 triggers code paths from this MR.
It seems that there is no straightforward way to test this commit: all uses of getConstantPool/getTargetConstantPool I checked are internal to DAG translation of specific constructs.
It might be possible to make a unit test that constructs DAG and lowers it, but I think that's an overkill.

@yonghong-song , wdyt?

**Comment by inclyc** [comment]
Kindly ping @yonghong-song :smiley: 

This PR has been blocked for 1 month :fearful: ! Could you please take a look?

**Comment by inclyc** [comment]
I'd like to merge this now :)

Please comment here if there are any issue caused by this PR, and I would happy to revert it!

**Pull request merged**
