### PR TITLE
[lldb] Move ValueObject into its own library (NFC)

### PR DESCRIPTION
**Pull request by JDevlieghere**
ValueObject is part of lldbCore for historical reasons, but conceptually it deserves to be its own library. This does introduce a circular dependency between lldbCore and lldbValueObject, which is unfortunate but probably unavoidable because so many things in LLDB rely on ValueObject. We already have cycles and these libraries are never built as dylibs so while this doesn't improve the situation, it also doesn't make things worse. 

The header includes were updated with the following command:

```
find . -type f -exec sed -i.bak "s%include \"lldb/Core/ValueObject%include \"lldb/ValueObject/ValueObject%" '{}' \;
```

### CODE REVIEW

**Comment by cmtice** [comment]
It appears that in  all the .h files that you moved from Core to ValueObject, you did not update the ifdef variable at the top of the file? I would have expected, e.g. that "LLDB_CORE_VALUEOBJECT_H"  should be changed to "LLDB_VALUEOBJECT_VALUEOBJECT_H". Shouldn't it?

**Comment by JDevlieghere** [comment]
> It appears that in all the .h files that you moved from Core to ValueObject, you did not update the ifdef variable at the top of the file? I would have expected, e.g. that "LLDB_CORE_VALUEOBJECT_H" should be changed to "LLDB_VALUEOBJECT_VALUEOBJECT_H". Shouldn't it?

Good point, I forgot the header guards. Fixed.

**Review by labath — COMMENTED** [review]
It looks like the CMakeLists.txt for Breakpoint and Command libraries is missing a dependency on the ValueObject lib (and they do appear to depend on it).

I can run this on linux to see if we need to increase our cirular dep counter. :P

My main question is: given that this is motivated by making room for the DIL implementation, isn't the name a bit overly specific? Like would you (all) be fine with putting something called DILParser into a directory called "ValueObject"?

(Note that I personally never had a problem with keeping the DIL in the Core library, and with the eviction of ValueObject, the core library gets noticably smaller, so for me, a completely acceptable colution would be to put/keep the DIL in the Core library, and leave the ValueObject library strictly for the ValueObject classes.)

**Comment by JDevlieghere** [comment]
Given that most of these files start with 1st ValueObject` I felt like that was the better name for the library, rather than DIL which doesn't exist yet. I'm fine with putting the DIL implementation in the new ValueObject library (potentially in a DIL subdirectory) or keep it in Core like you suggested.

**Comment by labath** [comment]
> Given that most of these files start with 1st ValueObject` I felt like that was the better name for the library, rather than DIL which doesn't exist yet. I'm fine with putting the DIL implementation in the new ValueObject library (potentially in a DIL subdirectory) or keep it in Core like you suggested.

Sorry, I didn't mean to imply that the directory should be called DIL -- that would again be too DIL-specific (and vapourware). I was more thinking of a name which was generic enough so it encompasses both. I don't really have a good suggestion, except maybe "Value" (so that you have a *Value*Object and and E-value-ator for it sitting next to each other.

That said, now that I've written this, I am starting to think that I'd be fine with an "evaluator" in a directory called "valueobject" as well, so I'm going to stamp this. If you think that "Value" is better, then feel free to rename it to that. Otherwise, this is fine as well.

(I've also checked that this builds on linux with the stricter dep checking)

**Review by labath — APPROVED** [review]

**Comment by cmtice** [comment]
> It looks like the CMakeLists.txt for Breakpoint and Command libraries is missing a dependency on the ValueObject lib (and they do appear to depend on it).
> 

It looks like the changes to these CMakeLists.txt (and maybe a few others?) are still missing. Or aren't they needed?

**Comment by JDevlieghere** [comment]
The GitHub UI made it a lot easier to spot missing libraries. I'm pretty sure I've got them all. It doesn't lead to an error because we link everything together anyway, but it's still the right thing to do. I also had to rebase the PR.

**Pull request merged**
