### PR TITLE
[lldb] Make sure that a `Progress` "completed" update is always reported at destruction

### PR DESCRIPTION
**Pull request by royitaqi**
Make all `Progress` destructions to cause `progressEnd` events, regardless of the value of `m_completed` before the destruction.

Currently, a `Progress` instance with `m_completed != 0 && m_complete != m_total` will cause a `progressUpdate` event (not `progressEnd`) at destruction (see [Process.cpp](https://github.com/llvm/llvm-project/blob/main/lldb/source/Core/Progress.cpp#L48-L49) and [lldb-dap/ProgressEvent.cpp](https://github.com/llvm/llvm-project/blob/main/lldb/tools/lldb-dap/ProgressEvent.cpp#L44-L46)). This contradicts with the classdoc:
> a progress completed update is reported even if the user doesn't explicitly cause one to be sent.

See [this discourse discussion](https://discourse.llvm.org/t/is-it-a-bug-or-a-feature-that-the-progress-class-can-emit-a-progressupdate-event-when-it-destructs-not-progressend/80568) for more details.

# Test

Confirmed that the tests pass with the patch, and don't pass without the patch.

```
ninja lldb-unit-test-deps
tools/lldb/unittests/Core/LLDBCoreTests --gtest_filter="Progress*"
```

### CODE REVIEW

**Comment by clayborg** [comment]
Was this why we saw some Swift progress dialogs hanging around forever?

Looks ok to me. @JDevlieghere feel free to add any more reviewers that have been working on progress dialogs.

**Review by JDevlieghere — APPROVED** [review]
LGTM. Could we cover this scenario by the existing unit test?

**Comment by royitaqi** [comment]
> LGTM. Could we cover this scenario by the existing unit test?

Yes, definitely.

At the time of the patch I didn't find any existing unit test files by searching for "ProgressTest.cpp". Just now I realize there is the [ProgressReportTest.cpp](https://github.com/llvm/llvm-project/blob/main/lldb/unittests/Core/ProgressReportTest.cpp). I will read it and try to add a test for this scenario.

**Comment by royitaqi** [comment]
@JDevlieghere A unit test has been added.  I have confirmed that it fails before the patch, and succeeds after the patch.

**Comment by JDevlieghere** [comment]
Thanks @royitaqi! Once the formatting is fixed this is ready to be merged.

**Pull request merged**
