### PR TITLE
Revert "[libc++][modules] Rewrite the modulemap to have fewer top-level modules (#107638)"

### PR DESCRIPTION
**Pull request by llvm-beanz**
This reverts 3 commits:
45a09d1811d5d6597385ef02ecf2d4b7320c37c5
24bc3244d4e221f4e6740f45e2bf15a1441a3076
bc6bd3bc1e99c7ec9e22dff23b4f4373fa02cae3

The GitHub pre-merge CI has been broken since this PR went in. This change reverts it to see if I can get the pre-merge CI working again.

### CODE REVIEW

**Review by boomanaiden154 — APPROVED** [review]
LGTM, assuming precommit CI passes.

**Comment by asl** [comment]
@llvm-beanz The changes to clang/include/clang/AST/Expr.h seems to be unrelated, no?

**Comment by llvm-beanz** [comment]
All checks passed. I'm reverting the top commit that was just to force the clang tests to run and merging the revert of the remaining 3 changes.

I confirmed with @ldionne that he is going to look at the issues on Monday.

**Comment by llvm-beanz** [comment]
> @llvm-beanz The changes to clang/include/clang/AST/Expr.h seem to be unrelated, no?

I reverted the commit modifying Clang before landing the PR, it was required to get the pre-merge CI to run the failing Clang CI to verify that my revert resolved the issue. There was an extensive discussion of this on the #infrastructure channel on Discord with @boomanaiden154.

**Pull request merged**
