### PR TITLE
[lld][RISCV] Add break to nested switch in `mergeAtomic`

### PR DESCRIPTION
**Pull request by 4vtomat**
This prevent the warnings from compiler.

### CODE REVIEW

**Review by ilovepi — APPROVED** [review]
The change seems fine, but what compiler is warning about this? lld was compiling without warning for me recently with ToT clang.

**Comment by 4vtomat** [comment]
> The change seems fine, but what compiler is warning about this? lld was compiling without warning for me recently with ToT clang.

The warning is 
```
llvm-project/lld/ELF/Arch/RISCV.cpp: In function ‘void mergeAtomic(llvm::DenseMapBase<llvm::DenseMap<unsigned int, unsigned int>, unsigned int, unsigned int, llvm
::DenseMapInfo<unsigned int>, llvm::detail::DenseMapPair<unsigned int, unsigned int> >::iterator, const lld::elf::InputSectionBase*, const lld::elf::InputSectionBase*, llvm::RISCVA
ttrs::RISCVAtomicAbiTag, llvm::RISCVAttrs::RISCVAtomicAbiTag)’:
llvm-project/lld/ELF/Arch/RISCV.cpp:1123:5: warning: this statement may fall through [-Wimplicit-fallthrough=]
     switch (newTag) {
     ^~~~~~
llvm-project/lld/ELF/Arch/RISCV.cpp:1135:3: note: here
   case RISCVAtomicAbiTag::A6S:
   ^~~~
llvm-project/lld/ELF/Arch/RISCV.cpp:1136:5: warning: this statement may fall through [-Wimplicit-fallthrough=]
     switch (newTag) {
     ^~~~~~
llvm-project/lld/ELF/Arch/RISCV.cpp:1148:3: note: here
   case RISCVAtomicAbiTag::A7:
   ^~~~
```

**Comment by ilovepi** [comment]
Right, but I don’t recall seeing that with a pretty recent clang, and I want to know if you’re using gcc or another compiler so I know if I should see if we should fix that in clang.

**Comment by 4vtomat** [comment]
> Right, but I don’t recall seeing that with a pretty recent clang, and I want to know if you’re using gcc or another compiler so I know if I should see if we should fix that in clang.

Actually it's during compiling the `lld` itself lol~

**Comment by ilovepi** [comment]
> > Right, but I don’t recall seeing that with a pretty recent clang, and I want to know if you’re using gcc or another compiler so I know if I should see if we should fix that in clang.
> 
> Actually it's during compiling the `lld` itself lol~

Yes, but are you compiling with clang as the compiler or something else? Because if it’s clang then I don’t need to file a bug and try to run down why we’re not handling that. If you’re using something else, then I do.

**Comment by 4vtomat** [comment]
> > > Right, but I don’t recall seeing that with a pretty recent clang, and I want to know if you’re using gcc or another compiler so I know if I should see if we should fix that in clang.
> > 
> > 
> > Actually it's during compiling the `lld` itself lol~
> 
> Yes, but are you compiling with clang as the compiler or something else? Because if it’s clang then I don’t need to file a bug and try to run down why we’re not handling that. If you’re using something else, then I do.

Oh, I got your point, I was using gcc.

**Comment by ilovepi** [comment]
Thanks I’ll take a look at top of tree clang again, and file a bug if we’re missing warnings in that case.

**Pull request merged**
