### PR TITLE
[ADT] Add convenience function `filter_to_vector`

### PR DESCRIPTION
**Pull request by kuhar**
This materializes a filter range as a small vector.

Similar to `map_to_vector`, this new utility function lives in the `SmallVectorExtras.h` header.

### CODE REVIEW

**Review by kazutakahirata — APPROVED** [review]
LGTM.  Thanks!

**Comment by dwblaikie** [comment]
I probably had similar feedback on previous *_to_vector - but I do wonder whether these are worthwhile/that much of a benefit compared to composing the two operations when needed?

**Comment by kuhar** [comment]
> I probably had similar feedback on previous *_to_vector - but I do wonder whether these are worthwhile/that much of a benefit compared to composing the two operations when needed?

I see `map_to_vector` used a lot across MLIR and downstream in IREE -- this one fewer layer of function calls is often what makes this appealing vs. using a for loop. So I'd argue that the real-world usage and improved readability justify this.

**Comment by kuhar** [comment]
My guess is that the reason for that in MLIR specifically is that we have multiple functions/methods that return ranges of IR constructs, e.g., `block.getOps<OpT>()`, which are difficult to work with until you materialize them. And materializing as a vector is usually the right thing to do as you typically end up passing these to function that take arguments as ArrayRef-like types.

**Pull request merged**
