### PR TITLE
[RISCV] Add Smdbltrp and Ssdbltrp extension

### PR DESCRIPTION
**Pull request by T-Tie**
Smdbltrp and Ssdbltrp supports are added in this PR.
Specification link(Smdbltrp) : [https://github.com/riscv/riscv-isa-manual/blob/main/src/smdbltrp.adoc](url)
Specification link(Ssdbltrp) : [https://github.com/riscv/riscv-isa-manual/blob/main/src/ssdbltrp.adoc](url)

### CODE REVIEW

**Review by dtcxzyw — COMMENTED** [review]
Personally I don't like to add a privileged extension if it doesn't introduce new CSRs/instructions.

**Comment by asb** [comment]
> Personally I don't like to add a privileged extension if it doesn't introduce new CSRs/instructions.

I'd actually put that on the [agenda](https://docs.google.com/document/d/1G3ocHm2zE6AYTS2N3_3w2UxFnSEyKkcF57siLWe-NVs/edit?tab=t.0) for today's sync-up call already. We did add the ones that are in the profiles. I could see an argument for supporting everything as people can then have a `-march` string that fully describes the target and don't need to go and sort through which options to drop as they don't affect the compiler. But I also see a counter-argument. I'll summarise anything relevant from the sync-up call discussion here.

**Comment by asb** [comment]
> > Personally I don't like to add a privileged extension if it doesn't introduce new CSRs/instructions.
> 
> I'd actually put that on the [agenda](https://docs.google.com/document/d/1G3ocHm2zE6AYTS2N3_3w2UxFnSEyKkcF57siLWe-NVs/edit?tab=t.0) for today's sync-up call already. We did add the ones that are in the profiles. I could see an argument for supporting everything as people can then have a `-march` string that fully describes the target and don't need to go and sort through which options to drop as they don't affect the compiler. But I also see a counter-argument. I'll summarise anything relevant from the sync-up call discussion here.

The conclusion was that nobody present saw a real argument against, feeling "why not" and as I mentioned above, it means people can just match the `-march` string to their CPU data sheet. Did you have a particular reason against adding such extensions?

**Comment by topperc** [comment]
> > > Personally I don't like to add a privileged extension if it doesn't introduce new CSRs/instructions.
> > 
> > 
> > I'd actually put that on the [agenda](https://docs.google.com/document/d/1G3ocHm2zE6AYTS2N3_3w2UxFnSEyKkcF57siLWe-NVs/edit?tab=t.0) for today's sync-up call already. We did add the ones that are in the profiles. I could see an argument for supporting everything as people can then have a `-march` string that fully describes the target and don't need to go and sort through which options to drop as they don't affect the compiler. But I also see a counter-argument. I'll summarise anything relevant from the sync-up call discussion here.
> 
> The conclusion was that nobody present saw a real argument against, feeling "why not" and as I mentioned above, it means people can just match the `-march` string to their CPU data sheet. Did you have a particular reason against adding such extensions?

Our hardware build generates a configuration file with a full -march string based on all extensions present in the RTL which we deliver to our customers. So I would like all extensions to be supported otherwise I have to do it downstream.

**Comment by dtcxzyw** [comment]
> > > > Personally I don't like to add a privileged extension if it doesn't introduce new CSRs/instructions.
> > > 
> > > 
> > > I'd actually put that on the [agenda](https://docs.google.com/document/d/1G3ocHm2zE6AYTS2N3_3w2UxFnSEyKkcF57siLWe-NVs/edit?tab=t.0) for today's sync-up call already. We did add the ones that are in the profiles. I could see an argument for supporting everything as people can then have a `-march` string that fully describes the target and don't need to go and sort through which options to drop as they don't affect the compiler. But I also see a counter-argument. I'll summarise anything relevant from the sync-up call discussion here.
> > 
> > 
> > The conclusion was that nobody present saw a real argument against, feeling "why not" and as I mentioned above, it means people can just match the `-march` string to their CPU data sheet. Did you have a particular reason against adding such extensions?
> 
> Our hardware build generates a configuration file with a full -march string based on all extensions present in the RTL which we deliver to our customers. So I would like all extensions to be supported otherwise I have to do it downstream.

Make sense to me. No strong objection.

**Comment by dtcxzyw** [comment]
> Failed Tests (2):
  Clang :: Driver/print-supported-extensions-riscv.c
  Clang :: Preprocessor/riscv-target-features.c

**Review by dtcxzyw — APPROVED** [review]
LGTM.

**Comment by dtcxzyw** [comment]
@T-Tie 
Can you fill in the PR description? Then I will merge this patch :)

**Comment by topperc** [comment]
@T-Tie can you pull from main and fix the conflicts?

**Review by topperc — APPROVED** [review]
LGTM

**Pull request merged**
