### PR TITLE
[ARM] Always lower direct calls as direct when the outliner is enabled

### PR DESCRIPTION
**Pull request by jroelofs**
The indirect lowering hinders the outliner's ability to see that sequences are in fact common, since the sequence similarity is rendered opaque by the register callee.  The size savings from making them indirect seems to be dwarfed by the outliner's savings from de-duplication.

rdar://115178034
rdar://115459865

### CODE REVIEW

**Comment by aemerson** [comment]
This change looks reasonable to me, but since ARM have a wide corpus of armv7 size sensitive code, could your team evaluate the impact of this change @davemgreen?

**Review by davemgreen — APPROVED** [review]
Sounds OK to me

**Comment by davemgreen** [comment]
Sorry - I managed to run the benchmarks wrong (I was surprised it didn't make any difference).

It turns out this does cause some regressions and appears to be worse than before.

**Comment by jroelofs** [comment]
Ok, thanks for checking! I'll revert tomorrow.

**Comment by jroelofs** [comment]
reverted in: 83e6d2edfcf9e073167529377eaa250795640d35

**Pull request merged**
