### PR TITLE
[clang-tidy] Fix crash in modernize-use-designated-initializers check

### LINKED ISSUE #113652: [clang-tidy] Crash when turn on the modernize-use-designated-initializers check.
I am using clangd and get the crash when turn on the modernize-use-designated-initializers check.
The code segment is like following.
The Crash is a forward declaration.

```
struct Crash;

struct Der{
  Der(Crash& d):d{d}{}
  Crash& d;
};
```

### PR DESCRIPTION
**Pull request by z1nke**
Fixed #113652
When calling `Node.isAggregate()` and `Node.isPOD()`, if `Node` is declared but not defined, it will result in null pointer dereference (and if assertions are enabled, it will cause an assertion failure).

### CODE REVIEW

**Comment by nicovank** [comment]
I fixed a similar issue in 0aaac4fe194ae2249e1a01f9d6f5eac0d75c5bb2. There's an argument to be made whether this should be in the matchers (`isPOD`, `isAggregate` like here) versus an `hasDefinition` call in the parent before calling those matchers. I am slightly leaning towards the latter but this is not a strong opinion.

Add a small release notes entry?

**Comment by z1nke** [comment]
@nicovank Thanks! Release note has been added.   
What do others think about the argument?

**Review by 5chmidti — APPROVED** [review]
Either way is fine with me.

**Review by nicovank — APPROVED** [review]
Looking at it again, this way is also good, no preference. Good to merge 👍

**Comment by z1nke** [comment]
Hi, I don’t have write access to merge code, and this is my first commit to clang-tidy. What else needs to be done to merge this PR? Thanks!

**Review by HerrCai0907 — APPROVED** [review]

**Comment by nicovank** [comment]
@z1nke I will go ahead and click the merge button. Thanks!

**Comment by mommsen** [comment]
Will this fix be added to an upcoming patch release for 19.1? We suffer from this issue using version 19.1.5.

**Pull request merged**
