### PR TITLE
[PGO] Fix branch weights overflow

### PR DESCRIPTION
**Pull request by Nechda**
This MR fixes the issue described in https://github.com/llvm/llvm-project/issues/88361

### CODE REVIEW

**Comment by Nechda** [comment]
@dtcxzyw

**Review by david-xl — COMMENTED** [review]
Possible to add a test case?

**Comment by MatzeB** [comment]
This was already fixed in https://github.com/llvm/llvm-project/pull/90217 I believe and this change doesn't add anything on top of it, or am I missing something?

**Comment by Nechda** [comment]
> This was already fixed in #90217 I believe and this change doesn't add anything on top of it, or am I missing something?

Hmm, seems you are right, I'll close this MR & Issue.

**Pull request closed without merging**
