### PR TITLE
[libc][stdbit] Add C tests for stdbit generic macros.

### PR DESCRIPTION
**Pull request by lntue**
Currently there is no tests for generic macros of generated `stdbit.h` header in C, and it is easy to make typo mistakes as in https://github.com/llvm/llvm-project/issues/84658.  In this patch, we simplify the generic macros in `stdbit.h` to reduce typo chances, and add a simple test for them in C.

### CODE REVIEW

**Comment by lntue** [comment]
@Flandini

**Comment by lntue** [comment]
@nickdesaulniers : shall I also update the `__cplusplus` part of `stdbit-macros.h`?

**Review by nickdesaulniers — COMMENTED** [review]
Ah, so we can test in C mode! Great!

Do you mind creating distinct PRs for the changes to test/include vs refactoring the type-generic macros?

The type-generic macros need to be rewritten in a different way to fix the TODO at the top of libc/include/llvm-libc-macros/stdbit-macros.h.  They need to be an if/else nest using sizeof and explicit casts in order to support `_BitInt`.  Either you or I can do that change, which is orthogonal to the nice changes you made to the tests.

**Comment by lntue** [comment]
> Ah, so we can test in C mode! Great!
> 
> Do you mind creating distinct PRs for the changes to test/include vs refactoring the type-generic macros?
> 
> The type-generic macros need to be rewritten in a different way to fix the TODO at the top of libc/include/llvm-libc-macros/stdbit-macros.h. They need to be an if/else nest using sizeof and explicit casts in order to support `_BitInt`. Either you or I can do that change, which is orthogonal to the nice changes you made to the tests.

Thanks for letting me know!  I've removed the `stdbit-macros.h` changes and only add the C tests in this PR.

**Review by nickdesaulniers — APPROVED** [review]

**Comment by nickdesaulniers** [comment]
failing on gcc: https://lab.llvm.org/buildbot/#/builders/250/builds/19882

**Pull request merged**
