### PR TITLE
[X86] Allow speculative BSR/BSF instructions on targets with CMOV

### PR DESCRIPTION
**Pull request by RKSimon**
Currently targets without LZCNT/TZCNT won't speculate with BSR/BSF instructions in case they have a zero value input, meaning we always insert a test+branch for the zero-input case.

This patch proposes we allow speculation if the target has CMOV, and perform a branchless select instead to handle the zero input case. This will predominately help x86-64 targets where we have the triple set but haven't generated codegen for any particular cpu target. We already always perform BSR/BSF instructions if we were lowering a CTLZ/CTTZ_ZERO_UNDEF instruction.

This change does make it harder to create the "REP BSF" (== TZCNT) pattern for CTTZ cases as we now use the ZF flag (which isn't set the same by TZCNT). We could avoid the ZF read and perform a separate CMP/TEST op if people think this is worth it?

### CODE REVIEW

**Comment by topperc** [comment]
It's been a while, but I think BSF/BSR may have a false dependency on the previous writer of the destination register on Intel CPUs. The behavior for the zero case is to leave the destination register unchanged so that requires the microarchitecture to copy the data to the renamed register.

**Comment by RKSimon** [comment]
Hmm, we already have TuningLZCNTFalseDeps - would it be worth a separate PR adding TuningBitScanFalseDeps and zeroing out the destination register?

**Comment by goldsteinn** [comment]
> Hmm, we already have TuningLZCNTFalseDeps - would it be worth a separate PR adding TuningBitScanFalseDeps and zeroing out the destination register?

FalseDep is somewhat incorrect, it preserves the destination so its an actual dep. Also FWIW Intel is going to change the documentation on BSF/BSR soon to state that it leaves the destination unchanged as opposed to undefined (i.e same as AMD).

**Comment by RKSimon** [comment]
Interesting, hopefully we can make use of that properly, even if we just support it with an opt-in feature flag.

I noticed that GCC doesn't use the ZF result from the BSF/BSR instruction and instead performs the zero-input calculation separately: https://rust.godbolt.org/z/oTf4fqWvs

**Comment by goldsteinn** [comment]
> Interesting, hopefully we can make use of that properly, even if we just support it with an opt-in feature flag.
> 
> I noticed that GCC doesn't use the ZF result from the BSF/BSR instruction and instead performs the zero-input calculation separately: https://rust.godbolt.org/z/oTf4fqWvs

I have to imagine thats just a missed optimization.

**Comment by RKSimon** [comment]
> > Hmm, we already have TuningLZCNTFalseDeps - would it be worth a separate PR adding TuningBitScanFalseDeps and zeroing out the destination register?
> 
> FalseDep is somewhat incorrect, it preserves the destination so its an actual dep. Also FWIW Intel is going to change the documentation on BSF/BSR soon to state that it leaves the destination unchanged as opposed to undefined (i.e same as AMD).

In case Intel do make this change - I've started a patch that would allow us to support this behaviour pretty easily: https://github.com/RKSimon/llvm-project/tree/x86-bitscan-fallthrough

I'd like to get this PR in first though as long as nobody has any outstanding concerns.

**Review by goldsteinn — APPROVED** [review]
This seems sensible. LGTM

**Review by topperc — APPROVED** [review]
LGTM

**Comment by topperc** [comment]
> > > Hmm, we already have TuningLZCNTFalseDeps - would it be worth a separate PR adding TuningBitScanFalseDeps and zeroing out the destination register?
> > 
> > 
> > FalseDep is somewhat incorrect, it preserves the destination so its an actual dep. Also FWIW Intel is going to change the documentation on BSF/BSR soon to state that it leaves the destination unchanged as opposed to undefined (i.e same as AMD).
> 
> In case Intel do make this change - I've started a patch that would allow us to support this behaviour pretty easily: https://github.com/RKSimon/llvm-project/tree/x86-bitscan-fallthrough
> 
> I'd like to get this PR in first though as long as nobody has any outstanding concerns.

Do VIA or Centaur and whoever else has made X86 chips in the past also match the unchanged behavior?

**Comment by topperc** [comment]
Does a 32 bit BSF/BSR with an input of 0 still zero the upper 32 bits of the "unmodified" destination like any other 32 bit instruction? If not we need to make sure we don't remove any zero extend operations after a BSF/BSR with an input of 0.

**Comment by topperc** [comment]
> Does a 32 bit BSF/BSR with an input of 0 still zero the upper 32 bits of the "unmodified" destination like any other 32 bit instruction? If not we need to make sure we don't remove any zero extend operations after a BSF/BSR with an input of 0.

I just checked on an Intel CPU. 32-bit bsf preserves the upper 32 bits of the destination. So its different than other 32-bit instructions.

**Comment by RKSimon** [comment]
> > Does a 32 bit BSF/BSR with an input of 0 still zero the upper 32 bits of the "unmodified" destination like any other 32 bit instruction? If not we need to make sure we don't remove any zero extend operations after a BSF/BSR with an input of 0.
> 
> I just checked on an Intel CPU. 32-bit bsf preserves the upper 32 bits of the destination. So its different than other 32-bit instructions.

Thanks for checking that - I'll see if I can update that patch to account it.

**Comment by comex** [comment]
@RKSimon As of (at latest) the October 2024 version of the "Intel® 64 and IA-32 Architectures Software Developer’s Manual", it seems like Intel has done so.  BSR and BSF are both documented as follows:

> If the content of the source operand is zero, the destination operand is unmodified.¹

> 1. On some older processors, use of a 32-bit operand size may clear the upper 32 bits of a 64-bit destination while leaving the lower
32 bits unmodified.

**Comment by RKSimon** [comment]
Thanks @comex - I'm investigating this on #122004 (for both BSR + BSF) - my old draft patch was intending to perform this for all x86 CPUs, but now its likely that I will limit this to just x64, which will require a rewrite.

**Pull request merged**
