### PR TITLE
[OpenMP][AIX] Implement __kmp_is_address_mapped() for AIX

### PR DESCRIPTION
**Pull request by xingxue-ibm**
This patch implements `__kmp_is_address_mapped()` for AIX by calling `loadquery()` to get the load info of the process and then checking if the address falls within the range of the data segment of one of the loaded modules.

### CODE REVIEW

**Review by shiltian — COMMENTED** [review]
I suppose this should work, but I'm thinking about the tests. Do we have any test failure right now due to this missing implementation?

**Comment by xingxue-ibm** [comment]
> I suppose this should work, but I'm thinking about the tests. Do we have any test failure right now due to this missing implementation?

Before the change, the routine returns the hard-coded `found = 1` and there were no failures. Other platforms does the same before proper implementation as well.

**Review by shiltian — APPROVED** [review]
Okay. That indicates the test coverage issue.

**Comment by xingxue-ibm** [comment]
> Okay. That indicates the test coverage issue.

Agreed.

**Pull request merged**
