### PR TITLE
[libc++] Avoid re-exporting a few specific symbols from libc++abi

### PR DESCRIPTION
**Pull request by ldionne**
In 6a884a9aef39, I synchronized the export list of libc++abi to the export list of libc++. From the linker's perspective, this caused these symbols to be taken from libc++.dylib instead of libc++abi.dylib.

However, that can be problematic when back-deploying. Indeed, this means that the linker will encode an undefined reference to be fullfilled by libc++.dylib, but when backdeploying against an older system, that symbol might only be available in libc++abi.dylib.

Most of the symbols that started being re-exported after 6a884a9aef39 turn out to be implementation details of libc++abi, so nobody really depends on them and this back-deployment issue is inconsequential.

However, we ran into issues with a few of these symbols while testing LLVM 19, which led to this patch. This slipped between the cracks and that is why the patch is coming so long after the original patch landed.

In the future, a follow-up cleanup would be to stop exporting most of the _cxxabiv1_foo_type_infoE symbols from both libc++abi and libc++ since they are implementation details that nobody should be relying on.

rdar://131984512

### CODE REVIEW

**Review by var-const — APPROVED** [review]

**Comment by MaskRay** [comment]
(Interesting issue. Aside:
This is a nice case that the two-level namespace introduced in Mac OS X 10.1 (default unless you use ld -flat_namespace) makes symbol moving difficult.
On ELF platforms, glibc made the choice to ease symbol moving
https://sourceware.org/bugzilla/show_bug.cgi?id=24741
)

**Comment by tru** [comment]
Hi, since we are wrapping up this next release we are very strict with the fixes we pick at this point. Can you please respond to the following questions to help me understand if this has to be included in the final release or not.

Is this PR a fix for a regression or a critical issue?

What is the risk of accepting this into the release branch?

What is the risk of NOT accepting this into the release branch?

**Comment by ldionne** [comment]
> Hi, since we are wrapping up this next release we are very strict with the fixes we pick at this point. Can you please respond to the following questions to help me understand if this has to be included in the final release or not.

100% understood.

> 
> Is this PR a fix for a regression or a critical issue?

Yes. I basically introduced an unintended ABI break in 6a884a9aef397f76178b141d789efadf280f2c3f, it just happened that the ABI break was subtle enough not to cause any issues outside of our internal release testing.

> 
> What is the risk of accepting this into the release branch?

Code compiled against LLVM 19.1 (released with these symbols in `libc++.dylib`) could fail with unresolved symbols when running against LLVM 19.2 (which would contain this patch), since this is effectively removing symbols from `libc++.dylib`. But those symbols should never have been there in the first place (well, not until we do some cleanup anyways).

> 
> What is the risk of NOT accepting this into the release branch?

Code linking against LLVM 19.1's `libc++.dylib` may fail with undefined references when run on an older `libc++.dylib`. That basically breaks the "backdeployment" use case, which is important on Apple platforms. FWIW, we're taking this fix in our internal release regardless of whether it makes it upstream because we can't publish a release without this fix. I think it would be better to keep both in sync but I'll leave it to you to decide based on the above.

**Pull request merged**
