### PR TITLE
[CMake] enable CMP0147 policy if available

### PR DESCRIPTION
**Pull request by c8ef**
Closes #38383.

This enables parallel custom build commands, which improve compilation time on Windows with Visual Studio.

### CODE REVIEW

**Comment by RKSimon** [comment]
I'm not sure either (worked fine for me) - maybe rebase and try again?

**Comment by mstorsjo** [comment]
> CC @mstorsjo who might be able to help

Sorry, no idea what has happened here - I'd suggest trying to rebase on top of latest main and retrying.

**Review by mstorsjo — APPROVED** [review]
The change seems reasonable to me. AFAIK we have little to no CI setups that would use MSVC with visual studio generators anyway, they all use ninja usually, so any CI errors here should be unrelated failures anyway (and the libc++ CI is having issues lately).

**Comment by RKSimon** [comment]
Thank you @c8ef

**Comment by mstorsjo** [comment]
> Thank you for your review. The patch works well on my Windows machine. By the way, if this patch is good to go, could you merge it for me?

Sure, will do. I kind of intentionally left the PR unmerged for a little while, after accepting, to give people in other time zones another chance to chime in on it, before merging - but I'll merge it now.

**Pull request merged**
