### PR TITLE
[SCCP] get rid of potentially dangling iterator

### PR DESCRIPTION
**Pull request by fmayer**
getUserBonus took an iterator into KnownConstants, but then inserted
into it later in the function, which could resize the data-structure
(DenseMap is based on a vector, so is not iterator stable).

The iterator is not needed, because we never change the value of an
entry after inserting.

### CODE REVIEW

**Comment by labrinea** [comment]
Hi, I am on vacation. I'll loo

**Comment by fmayer** [comment]
> Hi, I am on vacation. I'll look at this next week. Thanks

Do you want to review this specifically? I can also send it to someone else.

**Comment by labrinea** [comment]
> > Hi, I am on vacation. I'll look at this next week. Thanks
> 
> Do you want to review this specifically? I can also send it to someone else.

I am happy either way

**Comment by labrinea** [comment]
Hi. I am not seeing a modification of KnownConstants between the point where the iterator is initialized and the point it is consumed. Am I missing something?

**Comment by fmayer** [comment]
> Hi. I am not seeing a modification of KnownConstants between the point where the iterator is initialized and the point it is consumed. Am I missing something?

https://github.com/llvm/llvm-project/pull/105609/files#diff-066363256b7b4164e66b28a3028b2cb9e405c9136241baa33db76ebd2edb87cdL207

**Comment by labrinea** [comment]
> > Hi. I am not seeing a modification of KnownConstants between the point where the iterator is initialized and the point it is consumed. Am I missing something?
> 
> https://github.com/llvm/llvm-project/pull/105609/files#diff-066363256b7b4164e66b28a3028b2cb9e405c9136241baa33db76ebd2edb87cdL207

This insertion you have highlighted happens after the call to `visit` where the KnownConstants is read.

**Comment by fmayer** [comment]
> > > Hi. I am not seeing a modification of KnownConstants between the point where the iterator is initialized and the point it is consumed. Am I missing something?
> > 
> > 
> > https://github.com/llvm/llvm-project/pull/105609/files#diff-066363256b7b4164e66b28a3028b2cb9e405c9136241baa33db76ebd2edb87cdL207
> 
> This insertion you have highlighted happens after the call to `visit` where the iterator is read.

Ah, you are right ... but I still don't really see a reason to store it as a iterator, rather than just the two pointers.

Also, should we unset it after the visit call, just to make that clear?

**Comment by labrinea** [comment]
> Ah, you are right ... but I still don't really see a reason to store it as a iterator, rather than just the two pointers.
In my opinion having to keep two pointers synchronized may be more error-prone (one may update one and forget the other).

**Pull request closed without merging**
