### PR TITLE
[BOLT] Fix typos

### LINKED ISSUE #63097: bolt typos
_based on bolt-16.0.5.src.tar.xz_

Per request I could submit a `.sh` script with numerous `sed` commands to fix these and other bolt directory typos.

Auxiliary
Creates
Encoded
Histograms
Skeleton
accommodate
algorithm
analogous
available
average
behavior
containing
correctly
disassembled
encoding
endianness
entries
everywhere
exclusively
expression
explicitly
implicit
inconsistency
identifies
individual
ignored
instrumented
instructions
invocation
manually
modified
monolithic
namespace
occurred
pseudo
preceded
predecessors
process
recognized
reference
referring
references
removal
reordering
reordering
representation
retrieve
rewriting
separate
separately
structures
successfully
successor
semantics
through
translation
unconditional
interprocedural
where
whether
writable

```console
$ grep -n Auxiliar bolt/lib/Passes/ShrinkWrapping.cpp
916:/// Auxiliar function used to create basic blocks for critical edges and update
$ grep -nr Creats bolt
bolt/include/bolt/Core/DebugData.h:475:  /// Creats internal data stractures.
$ grep -nr Encded bolt
bolt/test/X86/dwarf5-split-dwarf4-monolithic.test:254:# Encded as a pair. So it's offset from base address.
$ grep -nr Historgrams bolt
bolt/lib/Core/DynoStats.cpp:139:      // Merge Other Historgrams, log only the opts::PrintDynoOpcodeStat'th
$ grep -nr Skelton bolt
bolt/include/bolt/Core/DebugData.h:581:  /// For Skelton CU it is a CU Offset.
$ grep -nr accomodate bolt
bolt/runtime/common.h:351:// buffer needs to accomodate large function names, but shouldn't be arbitrarily
$ grep -nr alogrithm bolt
bolt/include/bolt/Passes/ReorderAlgorithm.h:147:/// Objects of this class implement various basic block reordering alogrithms.
bolt/include/bolt/Passes/ReorderAlgorithm.h:148:/// Most of these algorithms depend on a clustering alogrithm.
$ grep -nr analoguous bolt
bolt/include/bolt/Passes/InstrumentationSummary.h:38:// Location information -- analoguous to the concept of the same name in fdata
$ grep -nr avaialable bolt
bolt/lib/Passes/RetpolineInsertion.cpp:54:                          "always", "r11 avaialable before calls and jumps"),
bolt/lib/Passes/RetpolineInsertion.cpp:56:                          "r11 avaialable before calls but not before jumps")),
$ grep -nr averagae bolt
bolt/include/bolt/Passes/ReorderAlgorithm.h:45:  /// Compute for each cluster its averagae execution frequency, that is
$ grep -nr behvior bolt
bolt/test/X86/dynrelocs.s:15:# this behvior with the -z notext flag. During runtime, these pages
$ grep -nr containg bolt
bolt/lib/Rewrite/RewriteInstance.cpp:4752:              "Cannot locate fragment containg secondary entrypoint");
$ grep -nr correclty bolt
bolt/test/X86/dwarf5-call-pc-function-null-check.test:11:# Test checks we correclty handle nullptr returned by getBinaryFunctionContainingAddress for DW_AT_call_pc.
$ grep -nr dissassembled bolt
bolt/test/AArch64/unmarked-data.test:12:  .equ val, 0x070b0f03  // we use constant that is not a valid instruction so that it can't be silently dissassembled
$ grep -nr encodnig bolt
bolt/include/bolt/Core/DebugData.h:63:// Types represent encodnig sizes.
$ grep -nr endianess bolt
bolt/include/bolt/Core/MCPlusBuilder.h:1018:  /// ConstantData array starting from \p offset and assuming little-endianess.
$ grep -nr entris bolt
bolt/lib/Core/DebugData.cpp:179:  UnitLengthType UnitLength; // Size of loclist entris section, not including
$ grep -nr everwhere bolt
bolt/lib/Passes/TailDuplication.cpp:238:    // If the register was replaced everwhere and it was overwritten in either
$ grep -nr exclusevely bolt
bolt/include/bolt/Profile/DataAggregator.h:304:  /// binary. Used exclusevely for pre-aggregated LBR samples.
$ grep -nr experssion bolt
bolt/lib/Rewrite/DWARFRewriter.cpp:690:            // Update the size of the experssion.
$ grep -nr explictly bolt
bolt/runtime/instr.cpp:1219:/// edges that we do not explictly instrument.
$ grep -nr impicit bolt
bolt/lib/Rewrite/DWARFRewriter.cpp:1258:    // with impicit conversion it will take null byte as end of
bolt/lib/Rewrite/DWARFRewriter.cpp:1268:    // with impicit conversion it will take null byte as end of
$ grep -nr inconsitency bolt
bolt/lib/Core/BinaryContext.cpp:1375:  assert(validateObjectNesting() && "object nesting inconsitency detected");
bolt/lib/Core/BinaryContext.cpp:1424:  assert(validateObjectNesting() && "object nesting inconsitency detected");
$ grep -nr indentifies bolt
bolt/lib/Core/BinaryContext.cpp:1769:  // end of a data chunk inside code, $d indentifies start of data.
$ grep -nr indiviual bolt
bolt/lib/Rewrite/RewriteInstance.cpp:3477:  // Emit indiviual pseudo probes in a inline tree node
$ grep -nr ingored bolt
bolt/test/X86/fallthrough-to-noop.test:1:# Check that profile data for the fall-through jump is not ingored when there is
$ grep -nr instumented bolt
bolt/lib/Passes/Instrumentation.cpp:36:    cl::desc("path to instumented binary in case if /proc/self/map_files "
$ grep -nr intructions bolt
bolt/include/bolt/Core/DynoStats.h:124:  /// and BB offsets where intructions of these opcodes occur.
$ grep -nr invokation bolt
bolt/include/bolt/Core/DebugData.h:464:  /// On first invokation it initializes internal data stractures.
$ grep -nr mannually bolt
bolt/test/X86/Inputs/dwarf5-cu-no-debug-addr-helper.s:107:      #.long  .Laddr_table_base0              # DW_AT_addr_base mannually removed
$ grep -nr modifed bolt
bolt/test/X86/Inputs/dwarf5-cu-no-debug-addr-helper.s:7:# Manually modifed to remove DW_AT_addr_base and DW_AT_location.
$ grep -nr monolitic bolt
bolt/lib/Core/DebugData.cpp:428:    // monolitic.
$ grep -nr nampespace bolt
bolt/lib/Rewrite/BoltDiff.cpp:663:} // end nampespace bolt
$ grep -nr occured bolt
bolt/include/bolt/Core/Exceptions.h:80:  /// frame data at which the reference occured, and Type is a DWARF encoding
bolt/include/bolt/Core/Relocation.h:63:  /// and \P Type mismatch occured.
$ grep -nr pesudo bolt
bolt/lib/Rewrite/RewriteInstance.cpp:587:    // pesudo probe is not added to binary. It is normal and no warning needed.
$ grep -nr preceeded bolt
bolt/include/bolt/Profile/DataReader.h:352:  /// mispreds. Of these branches, 1002 were preceeded by a sequence of
bolt/include/bolt/Profile/DataReader.h:354:  /// offset d. The rest 773 branches were preceeded by a different sequence
$ grep -nr predessecors bolt
bolt/include/bolt/Passes/ReorderAlgorithm.h:131:  // wher B, C are the only successors of A and A, D are thr only predessecors
$ grep -nr proccess bolt
bolt/lib/Core/Relocation.cpp:217:  // need to proccess these relocations anymore.
$ grep -nr reconized bolt
bolt/test/AArch64/got-ld64-relaxation.test:2:// to the ADR+ADD sequence is properly reconized and handled by bolt
$ grep -nr referece bolt
bolt/test/runtime/X86/instrumentation-ind-calls.s:2:# when the target address is computed with a referece to the stack pointer.
$ grep -nr refering bolt
bolt/include/bolt/Core/BinarySection.h:127:  /// Get the set of relocations refering to data in this section that
$ grep -nr refrences bolt
bolt/docs/doxygen.cfg.in:1957:# remove all refrences to function-like macros that are alone on a line, have an
$ grep -nr removqal bolt
bolt/test/X86/double-jump.test:1:# Test the double jump removqal peephole.
$ grep -nr reodering bolt
bolt/lib/Core/BinarySection.cpp:204:         "reodering pending relocations not supported");
$ grep -nr reorderng bolt
bolt/include/bolt/Passes/ReorderAlgorithm.h:1://===- bolt/Passes/ReorderAlgorithm.h - Basic block reorderng ---*- C++ -*-===//
$ grep -nr reprensentation bolt
bolt/lib/Utils/CommandLineOpts.cpp:163:               clEnumValN(PF_YAML, "yaml", "dense YAML reprensentation")),
$ grep -nr retreive bolt
bolt/lib/Rewrite/DWARFRewriter.cpp:930:    assert(Offset && "Was not able to retreive value of DW_AT_stmt_list.");
$ grep -nr rewritting bolt
bolt/test/X86/Inputs/linenumber.cpp:3:  // to insert branches and don't run out of space when rewritting the function.
$ grep -nr separete bolt
bolt/runtime/instr.cpp:1453:///    a separete process that will call this function periodically;
$ grep -nr seperatly bolt
bolt/lib/Rewrite/DWARFRewriter.cpp:1629:      // Handling .debug_rnglists.dwo seperatly. The original .o/.dwo might not
$ grep -nr stractures bolt
bolt/include/bolt/Core/DebugData.h:464:  /// On first invokation it initializes internal data stractures.
bolt/include/bolt/Core/DebugData.h:475:  /// Creats internal data stractures.
$ grep -nr successfuly bolt
bolt/lib/Passes/JTFootprintReduction.cpp:235:    llvm_unreachable("Should either optimize PIC or NonPIC successfuly");
$ grep -nr sucessor bolt
bolt/include/bolt/Passes/TailDuplication.h:84:  /// Returns true if Reg is overwritten before its used by StartBB's sucessors
bolt/lib/Passes/TailDuplication.cpp:278:  // and its sucessor is not already in the same cache line
bolt/lib/Passes/TailDuplication.cpp:301:  // and its sucessor is not already in the same cache line
$ grep -nr symantics bolt
bolt/include/bolt/Core/DebugData.h:361:    /// Follows the same symantics as unordered map [].
bolt/include/bolt/Core/DebugData.h:367:    /// Follows the same symantics as unordered map [].
$ grep -nr throught bolt
bolt/lib/Rewrite/DWARFRewriter.cpp:1944:  // For DWARF5 we only access ranges throught index.
$ grep -nr transaltion bolt
bolt/include/bolt/Core/BinaryFunction.h:2188:  /// Return true if this function needs an address-transaltion table after
$ grep -nr uncoditional bolt
bolt/test/X86/tail-duplication-cache.s:14:# A test where the tail is duplicated to eliminate an uncoditional jump
$ grep -nr unterprocedural bolt
bolt/include/bolt/Core/BinaryContext.h:922:  /// Add unterprocedural reference for \p Function to \p Address
$ grep -nr wehre bolt
bolt/lib/Core/DebugData.cpp:427:    // Handling the case wehre debug information is a mix of Debug fission and
$ grep -nr wheter bolt
bolt/include/bolt/Passes/StackReachingUses.h:44:  /// If \p IncludelocalAccesses is false, we only consider wheter there is
$ grep -nr writeable bolt
bolt/lib/Passes/ReorderData.cpp:14:// - make sure writeable data isn't put on same cache line unless temporally
bolt/lib/Passes/ReorderData.cpp:330:// is writeable)?
$ 
```

don't know why `other` and `histograms` are beginning with an uppercase letter

```console
$ ed -s bolt/lib/Core/DynoStats.cpp <<<'139,140p'
      // Merge Other Historgrams, log only the opts::PrintDynoOpcodeStat'th
      // maximum counts.
$
```

don't know the replacement string for `goest`

```console
$ grep -nr goest bolt
bolt/lib/Core/Relocation.cpp:400:    // The shift goest in bits 22:21 of MOV* instructions
$
```

aside from the typo `occures` this comment is somewhat awkwardly written

```console
$ ed -s bolt/include/bolt/Passes/FixRelaxationPass.h <<<'9,12p'
// This file declares the FixRelaxations class, which locates instructions with
// wrong targets and fixes them. Such problems usually occures when linker
// relaxes (changes) instructions, but doesn't fix relocations types properly
// for them.
$
```

don't know the replacement string for `proting`

```console
$ grep -nr proting bolt
bolt/include/bolt/Passes/StokeInfo.h:12://  proting its code:
$ 
```

don't know the replacement string for `wan't`

```console
$ ed -s bolt/runtime/instr.cpp <<<'275,277p'
  /// Basic member accessing interface. Here we pass the allocator explicitly to
  /// avoid storing a pointer to it as part of this table (remember there is one
  /// hash for each indirect call site, so we wan't to minimize our footprint).
$ 
```

### PR DESCRIPTION
**Pull request by spaette**
Closes https://github.com/llvm/llvm-project/issues/63097

Before merging please make sure the change to bolt/include/bolt/Passes/StokeInfo.h is correct.

bolt/include/bolt/Passes/StokeInfo.h

```diff
  //  This Pass solves the two major problems to use the Stoke program without
- //  proting its code:
+ //  probing its code:
```

I'm still not happy about the awkward wording in this comment.

bolt/include/bolt/Passes/FixRelaxationPass.h

```
$ ed -s bolt/include/bolt/Passes/FixRelaxationPass.h <<<'9,12p'
// This file declares the FixRelaxations class, which locates instructions with
// wrong targets and fixes them. Such problems usually occures when linker
// relaxes (changes) instructions, but doesn't fix relocations types properly
// for them.
$
```

bolt/docs/doxygen.cfg.in
bolt/include/bolt/Core/BinaryContext.h
bolt/include/bolt/Core/BinaryFunction.h
bolt/include/bolt/Core/BinarySection.h
bolt/include/bolt/Core/DebugData.h
bolt/include/bolt/Core/DynoStats.h
bolt/include/bolt/Core/Exceptions.h
bolt/include/bolt/Core/MCPlusBuilder.h
bolt/include/bolt/Core/Relocation.h
bolt/include/bolt/Passes/FixRelaxationPass.h
bolt/include/bolt/Passes/InstrumentationSummary.h
bolt/include/bolt/Passes/ReorderAlgorithm.h
bolt/include/bolt/Passes/StackReachingUses.h
bolt/include/bolt/Passes/StokeInfo.h
bolt/include/bolt/Passes/TailDuplication.h
bolt/include/bolt/Profile/DataAggregator.h
bolt/include/bolt/Profile/DataReader.h
bolt/lib/Core/BinaryContext.cpp
bolt/lib/Core/BinarySection.cpp
bolt/lib/Core/DebugData.cpp
bolt/lib/Core/DynoStats.cpp
bolt/lib/Core/Relocation.cpp
bolt/lib/Passes/Instrumentation.cpp
bolt/lib/Passes/JTFootprintReduction.cpp
bolt/lib/Passes/ReorderData.cpp
bolt/lib/Passes/RetpolineInsertion.cpp
bolt/lib/Passes/ShrinkWrapping.cpp
bolt/lib/Passes/TailDuplication.cpp
bolt/lib/Rewrite/BoltDiff.cpp
bolt/lib/Rewrite/DWARFRewriter.cpp
bolt/lib/Rewrite/RewriteInstance.cpp
bolt/lib/Utils/CommandLineOpts.cpp
bolt/runtime/instr.cpp
bolt/test/AArch64/got-ld64-relaxation.test
bolt/test/AArch64/unmarked-data.test
bolt/test/X86/Inputs/dwarf5-cu-no-debug-addr-helper.s
bolt/test/X86/Inputs/linenumber.cpp
bolt/test/X86/double-jump.test
bolt/test/X86/dwarf5-call-pc-function-null-check.test
bolt/test/X86/dwarf5-split-dwarf4-monolithic.test
bolt/test/X86/dynrelocs.s
bolt/test/X86/fallthrough-to-noop.test
bolt/test/X86/tail-duplication-cache.s
bolt/test/runtime/X86/instrumentation-ind-calls.s

### CODE REVIEW

**Review by ayermolo — APPROVED** [review]

**Review by jobnoorman — APPROVED** [review]

**Comment by spaette** [comment]
typo fix `reordering` not implemented

$ sed 1q llvm-project/bolt/include/bolt/Passes/ReorderAlgorithm.h
//===- bolt/Passes/ReorderAlgorithm.h - Basic block reorderng ---*- C++ -*-===//
$

**Comment by spaette** [comment]
@yota9

Are five reviews required for this pull request?

Indeed, the changes appear to be exclusively to comments and messages.

**Comment by ayermolo** [comment]
no

**Comment by yota9** [comment]
No, I've included maintainers of the project, fill free to submit it

**Comment by spaette** [comment]
@mtvec 

Accordingly are you amenable to merge absent a response from the additionally solicited reviewers.

**Comment by ayermolo** [comment]
Just merge.

**Comment by spaette** [comment]
Other than @mtvec is there anyone subscribed to this PR with write authority to the repository

**Comment by yota9** [comment]
Do you want me to merge your PR?

**Comment by ayermolo** [comment]
Merged

**Comment by spaette** [comment]
I'll write small initial comments for future pulls.

**Pull request merged**
