### PR TITLE
[AIX]export function descriptor symbols related to template functions.

### PR DESCRIPTION
**Pull request by chenzheng1030**
This fixes regressions caused by https://github.com/llvm/llvm-project/pull/97526

After that patch, all undefined references to DS symbol are removed. This makes DS symbols(for template functions) have no reference in some cases. So extract_symbols.py does not export these DS symbols for these cases.

On AIX, exporting the function descriptor depends on references to the function descriptor itself and the function entry symbol.

Without this fix, on AIX, we get:
```
rtld: 0712-001 Symbol _ZN4llvm15SmallVectorBaseIjE13mallocForGrowEPvmmRm was referenced
      from module llvm-project/build/unittests/Passes/Plugins/TestPlugin.so(), but a runtime definition
            of the symbol was not found. 
```

### CODE REVIEW

**Review by hubert-reinterpretcast — COMMENTED** [review]
This does not seem right to me: I think the intent is _not_ to ignore the template-related behaviour for AIX function descriptors, but to base the determination on whether they are referenced on whether the function descriptor _or_ the entry point is referenced.

**Comment by chenzheng1030** [comment]
> This does not seem right to me: I think the intent is _not_ to ignore the template-related behaviour for AIX function descriptors, but to base the determination on whether they are referenced on whether the function descriptor _or_ the entry point is referenced.

Thanks. Agreed. There should still be cases where the function descriptors for template functions should not be exported. Will update the patch.

**Review by hubert-reinterpretcast — APPROVED** [review]
LGTM; thanks!

**Pull request merged**
