### PR TITLE
[flang] Prevent errors from being suppressed

### PR DESCRIPTION
**Pull request by inaki-amatria**
`ModFileReader::Say()` flags all messages as errors, but Flang was mistakenly suppressing two errors when the `-w` flag was used, as they were incorrectly conditioned to warning suppression. This fix ensures that errors are reported regardless of the `-w` flag.

This commit also replaces two uses of `_warn_en_US` with `_err_en_US` to prevent potential confusion in the future.

### CODE REVIEW

**Comment by klausler** [comment]
A module file with an incorrect checksum might still be valid or useful, so I didn't want the error to be fatal.  Sometimes it is useful (but dangerous) to be able to modify a module file by hand.

If you must turn these warnings into unconditional errors, then Fortran::common::UsageWarning::ModuleFile will become obsolete and should be deleted.

**Comment by inaki-amatria** [comment]
> A module file with an incorrect checksum might still be valid or useful, so I didn't want the error to be fatal. Sometimes it is useful (but dangerous) to be able to modify a module file by hand.

Thank you for the feedback, klausler! I believe there is a slight mismatch in the current code's behavior and the intent described here. Even if Flang does not report this error specifically, `nullptr` is still returned, which prevents the module file with the incorrect checksum from being imported. This ultimately results in a semantics error along the lines of "symbol 'xyz' does not exist". In my opinion, reporting the specific error from `ModuleFileReader::Read()` offers a clearer and more precise message than a general missing symbol error.

> If you must turn these warnings into unconditional errors, then Fortran::common::UsageWarning::ModuleFile will become obsolete and should be deleted.

I have added a fixup commit removing `Fortran::common::UsageWarning::ModuleFile` and its uses.

Thanks again for the review! Please feel free to close or merge the PR if you are in agreement.

**Review by klausler — APPROVED** [review]

**Comment by inaki-amatria** [comment]
I have squashed the commits and updated the branch to be up-to-date with the latest main. Could someone with write access kindly merge this PR for me, as I don't have the necessary permissions? Thanks so much!!

**Comment by klausler** [comment]
> I have squashed the commits and updated the branch to be up-to-date with the latest main. Could someone with write access kindly merge this PR for me, as I don't have the necessary permissions? Thanks so much!!

Please get commit privileges to LLVM for yourself, if possible.

**Pull request merged**
