### PR TITLE
[lldb][Windows] Fixed the test gdb_remote_client/TestGDBRemotePlatformFile

### PR DESCRIPTION
**Pull request by slydiman**
The tests `test_file_permissions` and `test_file_permissions_fallback` are disabled for Windows target. These tests use MockGDBServerResponder and do not depend on the real target. These tests failed in case of Windows host and Linux target. Disable them for Windows host too.

### CODE REVIEW

**Comment by labath** [comment]
Given that the tests use a mock server, why is it a problem that they're running on a windows host? What's the actual failure? Could they be adapted so that they run everywhere?

**Comment by slydiman** [comment]
The problem is that fstat() is fake on Windows. File::GetPermissions() returns 0 always.
The test got 'File permissions of /some/file.txt (remote): 0o0000' So any permissions manipulations are useles on Windows and these tests cannot be adapted.

**Comment by slydiman** [comment]
I have removed @skipIfWindows because these tests are host specific.

**Comment by labath** [comment]
> The problem is that fstat() is fake on Windows. File::GetPermissions() returns 0 always. The test got 'File permissions of /some/file.txt (remote): 0o0000' So any permissions manipulations are useles on Windows and these tests cannot be adapted.

But who is calling File::GetPermissions? The way I see it, this test is checking that `platform get-permissions /some/file.txt` generates the correct gdb-remote packet. It does that by having the test talk to a simulated/mock gdb server and hardcoding the responses (see line 156, 0x1a4 == 0o664). In theory that should work as there are no real files involved (and for all lldb cares, the remote platform does actually have a functional permission implementation).

**Comment by slydiman** [comment]
The problem is here lldb\source\Plugins\Process\gdb-remote\GDBRemoteCommunicationClient.cpp, line 3235
inside GDBRemoteCommunicationClient::GetFilePermissions()
```
file_permissions = mode & (S_IRWXU | S_IRWXG | S_IRWXO);
```
But S_IRWXU, S_IRWXG and S_IRWXO are 0 on Windows.

**Comment by labath** [comment]
> The problem is here lldb/source/Plugins/Process/gdb-remote/GDBRemoteCommunicationClient.cpp, line 3235 inside GDBRemoteCommunicationClient::GetFilePermissions()
> 
> ```
> file_permissions = mode & (S_IRWXU | S_IRWXG | S_IRWXO);
> ```


Okay, so I think this is the bug. The protocol code should not be depending on the host definitions of the permission constants.

Would you be interested in creating a patch to change this so that it uses lldb's `eFilePermissions***` enums (which are the same everywhere(*)). I don't think it is necessarily up to you to fix this issue, but you do seem to care about the windows->linux configs, and this is approximately the only configuration in which this bug manifests itself. And it's definitely not a big bug, but it could cause some surprises when debugging in these setups. In case you do not want to make that change, I'd say that the appropriate decorator is `@expectedFailureAll(hostoslist=["windows"])` with a reference to this issue, as this is something that is supposed to work, but fails due to an lldb bug.

(*) Technically, there is no requirement that the [gdb-protocol values](https://github.com/llvm/llvm-project/blob/b6f050fa129b08b6bc35168f0b8010742cd1ed9d/lldb/docs/resources/lldbgdbremote.md?plain=1#L2302) match `lldb` public enums. Puristically, one ought to define separate constants for the protocol and then convert them between the two. However, the two definitions happen to match in this case, and both of them are part of stable APIs so they can't go out of sync and I think we can skip the conversion step.

**Comment by slydiman** [comment]
Now we are in the middle of configuring buildbot and trying to get it green. I have added [the issues 92255](https://github.com/llvm/llvm-project/issues/92255). Hope we will fix it later. Thanks.

**Review by labath — APPROVED** [review]
Sounds good. Looking forward to it.

**Pull request merged**
