### PR TITLE
Add @ftynse as GitHub codeowner for MLIR Transform dialect

### PR DESCRIPTION
**Pull request by ftynse**

### CODE REVIEW

**Review by nicolasvasilache — APPROVED** [review]
Makes sense.

Was there an RFC for this recently?

Are we looking for 1 or multiple code owners per bigger topic?

**Comment by ftynse** [comment]
It's just a mechanism for auto-requesting code reviews, this doesn't grant any more rights. There were some PRs that I nearly missed.

**Comment by nicolasvasilache** [comment]
> It's just a mechanism for auto-requesting code reviews, this doesn't grant any more rights. There were some PRs that I nearly missed.

Ah nice, thanks! I definitely missed a bunch myself..

**Comment by nikic** [comment]
(Please do not push user branches to the upstream repo unless you want to create a stacked pull request.)

**Pull request merged**
