### PR TITLE
[InstCombine] Canonicalize `(sitofp x)` -> `(uitofp x)` if `x >= 0`

### PR DESCRIPTION
**Pull request by goldsteinn**
Just a standard canonicalization.

Proofs: https://alive2.llvm.org/ce/z/9W4VFm

### CODE REVIEW

**Comment by goldsteinn** [comment]
My thinking was `sitofp` is a better canonicalization, but either way we should probably pick one.

**Comment by nikic** [comment]
> My thinking was `sitofp` is a better canonicalization, but either way we should probably pick one.

Why is it a better canonicalization? We prefer unsigned over signed operations for everything else (zext, lshr, udiv, icmp u), so this would be a very unusual.

**Comment by goldsteinn** [comment]
> > My thinking was `sitofp` is a better canonicalization, but either way we should probably pick one.
> 
> Why is it a better canonicalization? We prefer unsigned over signed operations for everything else (zext, lshr, udiv, icmp u), so this would be a very unusual.

There seems to be a lot more support for looking through `sitofp` than `uitofp` (infact saw no cases where we support `uitofp` but not `sitofp` in `InstCombinAddSub`/`InstCombineMulDiv`.

Also fp types are pretty inherently signed, so think signed -> signed as more intuitive/direct.

**Comment by nikic** [comment]
> Edit: The little test I added is an example.

Is there some inherent reason why that transform can only work with sitofp, rather than also uitofp with an s/signed/unsigned replacement everywhere? If there isn't, we should extend that transform instead.

**Comment by goldsteinn** [comment]
> > Edit: The little test I added is an example.
> 
> Is there some inherent reason why that transform can only work with sitofp, rather than also uitofp with an s/signed/unsigned replacement everywhere? If there isn't, we should extend that transform instead.
I think it works for both.

One more thing, some backend (x86 for example) have better codegen with `si` than `ui` (not sure of any counter cases).
https://godbolt.org/z/f5joos63o

and its not too uncommon for info from middle-end to be lost on the way to backend.

Can be fixed up elsewhere (i.e during lowering) but think generally its indicative of the somewhat builtin "signedness" of floats and thus how `si` is a better match.

If youre not convinced lmk and ill swap this patch around and start work on the regressions.

**Comment by dtcxzyw** [comment]
> > Edit: The little test I added is an example.
> 
> Is there some inherent reason why that transform can only work with sitofp, rather than also uitofp with an s/signed/unsigned replacement everywhere? If there isn't, we should extend that transform instead.

An example extracted from `cpython/_ctypes_test.ll`: https://godbolt.org/z/jG6WWPqnE

**Comment by goldsteinn** [comment]
> > > Edit: The little test I added is an example.
> > 
> > 
> > Is there some inherent reason why that transform can only work with sitofp, rather than also uitofp with an s/signed/unsigned replacement everywhere? If there isn't, we should extend that transform instead.
> 
> An example extracted from `cpython/_ctypes_test.ll`: https://godbolt.org/z/jG6WWPqnE

I'm working on a patch to expand that fold.

**Comment by nikic** [comment]
> Can be fixed up elsewhere (i.e during lowering) but think generally its indicative of the somewhat builtin "signedness" of floats and thus how si is a better match.

I think this says a lot more about the x86 architecture than about floating point numbers :) Pre-avx512 is well known to have very weird holes in the simd instruction set -- you could equally say that integers have an inherent preference for signed comparison because x86 can't compare packed unsigned numbers...

> If youre not convinced lmk and ill swap this patch around and start work on the regressions.

I think we should first address any unnecessary differences between sitofp and uitofp optimization, and then we can check the result of both canonicalization directions on @dtcxzyw's test set and see whether we see any clear benefit in one direction or the other.

**Comment by topperc** [comment]
> > Can be fixed up elsewhere (i.e during lowering) but think generally its indicative of the somewhat builtin "signedness" of floats and thus how si is a better match.
> 
> I think this says a lot more about the x86 architecture than about floating point numbers :) Pre-avx512 is well known to have very weird holes in the simd instruction set -- you could equally say that integers have an inherent preference for signed comparison because x86 can't compare packed unsigned numbers...

I think there's an asymmetry somewhere in PowerPC too. But its for the other direction fptosi/fptoui. See this comment from `DAGTypeLegalizer::PromoteIntRes_FP_TO_XINT`

```
  // If we're promoting a UINT to a larger size and the larger FP_TO_UINT is     
  // not Legal, check to see if we can use FP_TO_SINT instead.  (If both UINT    
  // and SINT conversions are Custom, there is no way to tell which is           
  // preferable. We choose SINT because that's the right thing on PPC.)
```

**Comment by goldsteinn** [comment]
got https://github.com/llvm/llvm-project/pull/82555 in, now canonicalizes to unsigned.

**Comment by nikic** [comment]
@dtcxzyw Can you please test the new version?

**Comment by dtcxzyw** [comment]
> @dtcxzyw Can you please test the new version?

Done.

**Comment by dtcxzyw** [comment]
Regression:
```
define float @src(i32 %shr.i) {
  %and.i = and i32 %shr.i, 32767
  %sub = uitofp i32 %and.i to float
  %add = fadd float %sub, -16383.0
  ret float %add
}

define float @tgt(i32 %shr.i) {
  %and.i = and i32 %shr.i, 32767
  %addconv = add nsw i32 %and.i, -16383
  %sub = sitofp i32 %addconv to float
  ret float %sub
}
```

Alive2: https://alive2.llvm.org/ce/z/W6Ik5C

**Comment by goldsteinn** [comment]
> Regression:
> 
> ```
> define float @src(i32 %shr.i) {
>   %and.i = and i32 %shr.i, 32767
>   %sub = uitofp i32 %and.i to float
>   %add = fadd float %sub, -16383.0
>   ret float %add
> }
> 
> define float @tgt(i32 %shr.i) {
>   %and.i = and i32 %shr.i, 32767
>   %addconv = add nsw i32 %and.i, -16383
>   %sub = sitofp i32 %addconv to float
>   ret float %sub
> }
> ```
> 
> Alive2: https://alive2.llvm.org/ce/z/W6Ik5C

Is that a regression?
Seems like the `fadd` -> `add` is desirable.
Likewise we don't really know return op sign in either.

**Comment by dtcxzyw** [comment]
> > Regression:
> > ```
> > define float @src(i32 %shr.i) {
> >   %and.i = and i32 %shr.i, 32767
> >   %sub = uitofp i32 %and.i to float
> >   %add = fadd float %sub, -16383.0
> >   ret float %add
> > }
> > 
> > define float @tgt(i32 %shr.i) {
> >   %and.i = and i32 %shr.i, 32767
> >   %addconv = add nsw i32 %and.i, -16383
> >   %sub = sitofp i32 %addconv to float
> >   ret float %sub
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Alive2: https://alive2.llvm.org/ce/z/W6Ik5C
> 
> Is that a regression? Seems like the `fadd` -> `add` is desirable. Likewise we don't really know return op sign in either.

https://github.com/dtcxzyw/llvm-opt-benchmark/pull/248#discussion_r1515850373
But this patch transforms `add + sitofp` into `uitofp + fadd` :(

**Comment by goldsteinn** [comment]
> > > Regression:
> > > ```
> > > define float @src(i32 %shr.i) {
> > >   %and.i = and i32 %shr.i, 32767
> > >   %sub = uitofp i32 %and.i to float
> > >   %add = fadd float %sub, -16383.0
> > >   ret float %add
> > > }
> > > 
> > > define float @tgt(i32 %shr.i) {
> > >   %and.i = and i32 %shr.i, 32767
> > >   %addconv = add nsw i32 %and.i, -16383
> > >   %sub = sitofp i32 %addconv to float
> > >   ret float %sub
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Alive2: https://alive2.llvm.org/ce/z/W6Ik5C
> > 
> > 
> > Is that a regression? Seems like the `fadd` -> `add` is desirable. Likewise we don't really know return op sign in either.
> 
> [dtcxzyw/llvm-opt-benchmark#248 (comment)](https://github.com/dtcxzyw/llvm-opt-benchmark/pull/248#discussion_r1515850373) But this patch transforms `add + sitofp` into `uitofp + fadd` :(

Ah I see, thought you meant the other way around.

Okay, think what needs to change is need to be able to handle `uitofp` as `sitofp`
in `foldFBinOpOfIntCasts`. Ill make a patch.

**Comment by goldsteinn** [comment]
> define float @src(i32 %shr.i) {
>   %and.i = and i32 %shr.i, 32767
>   %sub = uitofp i32 %and.i to float
>   %add = fadd float %sub, -16383.0
>   ret float %add
> }

See: https://github.com/llvm/llvm-project/pull/84389

**Comment by goldsteinn** [comment]
@dtcxzyw can you re-run?

**Review by dtcxzyw — APPROVED** [review]
LGTM. Thanks!

**Review by nikic — APPROVED** [review]

**Comment by nikic** [comment]
It looks like you need to update `Headers/__clang_hip_math.hip` in clang.

**Comment by goldsteinn** [comment]
> It looks like you need to update `Headers/__clang_hip_math.hip` in clang.

Fixed. Thats what I get for not running clang tests :/

**Review by nikic — APPROVED** [review]

**Comment by goldsteinn** [comment]
@nikic, what do you think about adding `nneg` for `uitofp`?

**Comment by nikic** [comment]
@goldsteinn Doesn't seem worthwhile.

**Comment by Artem-B** [comment]
We happen have a back-end where we do not have conversion instructions between unsigned int and FP, so this patch complicates things. Would it make sense to enable this canonicalization only if the target wants it?

**Comment by goldsteinn** [comment]
> We happen have a back-end where we do not have conversion instructions between unsigned int and FP, so this patch complicates things. Would it make sense to enable this canonicalization only if the target wants it?

We try to keep InstCombine as target agnostic as possible so probably not.
Thats why I was thinking of adding the `nneg` flag, so its extremely easy for the backend to undo this.

If we don't go with `nneg` and its causing issues on a lot of targets, revert might be the right approach.

**Comment by nikic** [comment]
I don't think we really have a strong motivation for this change beyond "having a canonical form is usually good", so if it's causing issues for some targets, then probably just not doing it is fine. But if we do want to keep it, then yeah, this would be a reasonable motivation for adding the nneg flag.

**Comment by goldsteinn** [comment]
> I don't think we really have a strong motivation for this change beyond "having a canonical form is usually good", so if it's causing issues for some targets, then probably just not doing it is fine. But if we do want to keep it, then yeah, this would be a reasonable motivation for adding the nneg flag.

I don't have any strong preference. I think there is some value in this change so I'm slightly in favor of adding `nneg`.
Letting the chips fall where they may, when some backends can have `ui` preference, doesn't really seem that
great either. But, I have no problem reverting this if thats the sentiment of the room.

**Comment by asmok-g** [comment]
Heads up: we noticed at google that this is causing the following test to fail:

https://github.com/google/swiftshader/blob/master/tests/ReactorUnitTests/ReactorUnitTests.cpp#L1312

I need to put a more proper reproducer, but thought that at least posting the heads-up might be faster to unblock us and maybe the problem is clear. I see that adding a flag vs reverting is already brought up in the last comment, what's the plan for that ?

**Comment by goldsteinn** [comment]
Ill revert this. I'll re-post if I get around to adding a flag.
Any chance you can still create a repro of the bug your seeing for if I re-post?

**Comment by goldsteinn** [comment]
> Heads up: we noticed at google that this is causing the following test to fail:
> 
> https://github.com/google/swiftshader/blob/master/tests/ReactorUnitTests/ReactorUnitTests.cpp#L1312
> 
> I need to put a more proper reproducer, but thought that at least posting the heads-up might be faster to unblock us and maybe the problem is clear. I see that adding a flag vs reverting is already brought up in the last comment, what's the plan for that ?

Reverted with: https://github.com/llvm/llvm-project/commit/6960ace534c4021301dd5a9933ca06ba96edea23

If you can get the repro though, that would still be useful for when I revisit.

**Comment by alexfh** [comment]
Apart from the correctness issues, we've seen some regressions on various benchmarks from LLVM Test Suite after this patch. Specifically, around 3-5% regression on x86-64 in various metrics of the [Interpolation](https://github.com/llvm/llvm-test-suite/tree/main/MicroBenchmarks/ImageProcessing/Interpolation) benchmarks, and up to 30% regression on a number of floating point-centric benchmarks from https://github.com/llvm/llvm-test-suite/tree/main/SingleSource/Benchmarks/Misc (flops-4.c, flops-5.c, flops-6.c, flops-8.c, fp-convert.c). The numbers vary depending on the microarchitecture, with Skylake being less affected (on the order of ~10%) and AMD Rome showing larger regressions (up to 30%).

**Comment by goldsteinn** [comment]
> Apart from the correctness issues, we've seen some regressions on various benchmarks from LLVM Test Suite after this patch. Specifically, around 3-5% regression on x86-64 in various metrics of the [Interpolation](https://github.com/llvm/llvm-test-suite/tree/main/MicroBenchmarks/ImageProcessing/Interpolation) benchmarks, and up to 30% regression on a number of floating point-centric benchmarks from https://github.com/llvm/llvm-test-suite/tree/main/SingleSource/Benchmarks/Misc (flops-4.c, flops-5.c, flops-6.c, flops-8.c, fp-convert.c). The numbers vary depending on the microarchitecture, with Skylake being less affected (on the order of ~10%) and AMD Rome showing larger regressions (up to 30%).

Thank you for the info, well its reverted now so nothing todo. Although that does motivate me to get
re-post with the `nneg` flag support as it sounds like getting the right cast can be important
and that will allow us to do a better job than we currently are.

**Comment by goldsteinn** [comment]
> Well, I'm not sure how proper that wold be as a reproducer,
> 
> I extracted the mentioned test to a program:
> 
> ```
> #include <cmath>
> 
> #include "third_party/swiftshader/src/Reactor/Coroutine.hpp"
> #include "third_party/swiftshader/src/Reactor/Reactor.hpp"
> 
> using float4 = float[4];
> using int4 = int[4];
> 
> static std::string testName() { return "test name"; }
> 
> using namespace rr;
> 
> int main() {
>   Function<Void(Pointer<Int4>, Pointer<Int4>)> function;
>   {
>     Pointer<Int4> x = function.Arg<0>();
>     Pointer<Int4> y = function.Arg<1>();
> 
>     *y = Abs(*x);
>   }
> 
>   auto routine = function(testName().c_str());
>   auto callable = (void (*)(int4 *, int4 *))routine->getEntry();
> 
>   int input[] = {1, -1, 0, (int)0x80000000};
> 
>   for (int x : input) {
>     int4 v_in = {x, x, x, x};
>     int4 v_out = {0};
> 
>     callable(&v_in, &v_out);
> 
>     float expected = abs(x);
>     if (v_out[0] != expected) {
>       return 10;
>     }
>   }
> }
> ```
> 
> Before the change program exits with 0, after it exists with 10. More precisely: `v_out[0]` is: -2147483648, `expected` is: 2.14748365e+09
> 
> [out_at.txt](https://github.com/llvm/llvm-project/files/14670227/out_at.txt) [out_before.txt](https://github.com/llvm/llvm-project/files/14670228/out_before.txt)
> 
> I attached the generated IR before and after the change. It's only one line diff:
> 
> ```
>    call void @llvm.memset.p0.i64(ptr noundef nonnull align 16 dereferenceable(16) %9, i8 0, i64 16, i1 false)
>    call void %49(ptr noundef nonnull %8, ptr noundef nonnull %9) #16
>    %61 = call i32 @llvm.abs.i32(i32 %60, i1 true)
> -  %62 = sitofp i32 %61 to float
> +  %62 = uitofp i32 %61 to float
>    %63 = load i32, ptr %9, align 16
>    %64 = sitofp i32 %63 to float
>    %65 = fcmp une float %64, %62
> ```
> 
> generation command is `clang -O1 -fsized-deallocation '-std=gnu++20' -c pre.ii -emit-llvm -S -o /tmp/ir_before.ll`
> 
> I'm trying to reduce the preprocessed file, tho not sure i'll keep the semantics of the failure.

This should be sufficient, thank you!

**Comment by dtcxzyw** [comment]
> Apart from the correctness issues, we've seen some regressions on various benchmarks from LLVM Test Suite after this patch. Specifically, around 3-5% regression on x86-64 in various metrics of the [Interpolation](https://github.com/llvm/llvm-test-suite/tree/main/MicroBenchmarks/ImageProcessing/Interpolation) benchmarks, and up to 30% regression on a number of floating point-centric benchmarks from https://github.com/llvm/llvm-test-suite/tree/main/SingleSource/Benchmarks/Misc (flops-4.c, flops-5.c, flops-6.c, flops-8.c, fp-convert.c). The numbers vary depending on the microarchitecture, with Skylake being less affected (on the order of ~10%) and AMD Rome showing larger regressions (up to 30%).

FYI this patch saves ~3% instructions for some benchmarks from LLVM-test-suite on RISC-V.
https://github.com/dtcxzyw/llvm-ci/issues/1115
https://github.com/dtcxzyw/llvm-ci/issues/1114

**Comment by topperc** [comment]
> > Apart from the correctness issues, we've seen some regressions on various benchmarks from LLVM Test Suite after this patch. Specifically, around 3-5% regression on x86-64 in various metrics of the [Interpolation](https://github.com/llvm/llvm-test-suite/tree/main/MicroBenchmarks/ImageProcessing/Interpolation) benchmarks, and up to 30% regression on a number of floating point-centric benchmarks from https://github.com/llvm/llvm-test-suite/tree/main/SingleSource/Benchmarks/Misc (flops-4.c, flops-5.c, flops-6.c, flops-8.c, fp-convert.c). The numbers vary depending on the microarchitecture, with Skylake being less affected (on the order of ~10%) and AMD Rome showing larger regressions (up to 30%).
> 
> FYI this patch saves ~3% instructions for some benchmarks from LLVM-test-suite on RISC-V. [dtcxzyw/llvm-ci#1115](https://github.com/dtcxzyw/llvm-ci/issues/1115) [dtcxzyw/llvm-ci#1114](https://github.com/dtcxzyw/llvm-ci/issues/1114)

Are you able to extract a reproducer that I can look at?

**Comment by goldsteinn** [comment]
See: https://github.com/llvm/llvm-project/pull/86141 which adds `nneg` flag to IR. Once that gets in I have patches for instcombine,cvp,sccp to do the transform.

**Comment by goldsteinn** [comment]
> > Well, I'm not sure how proper that wold be as a reproducer,
> > I extracted the mentioned test to a program:
> > ```
> > #include <cmath>
> > 
> > #include "third_party/swiftshader/src/Reactor/Coroutine.hpp"
> > #include "third_party/swiftshader/src/Reactor/Reactor.hpp"
> > 
> > using float4 = float[4];
> > using int4 = int[4];
> > 
> > static std::string testName() { return "test name"; }
> > 
> > using namespace rr;
> > 
> > int main() {
> >   Function<Void(Pointer<Int4>, Pointer<Int4>)> function;
> >   {
> >     Pointer<Int4> x = function.Arg<0>();
> >     Pointer<Int4> y = function.Arg<1>();
> > 
> >     *y = Abs(*x);
> >   }
> > 
> >   auto routine = function(testName().c_str());
> >   auto callable = (void (*)(int4 *, int4 *))routine->getEntry();
> > 
> >   int input[] = {1, -1, 0, (int)0x80000000};
> > 
> >   for (int x : input) {
> >     int4 v_in = {x, x, x, x};
> >     int4 v_out = {0};
> > 
> >     callable(&v_in, &v_out);
> > 
> >     float expected = abs(x);
> >     if (v_out[0] != expected) {
> >       return 10;
> >     }
> >   }
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Before the change program exits with 0, after it exists with 10. More precisely: `v_out[0]` is: -2147483648, `expected` is: 2.14748365e+09
> > [out_at.txt](https://github.com/llvm/llvm-project/files/14670227/out_at.txt) [out_before.txt](https://github.com/llvm/llvm-project/files/14670228/out_before.txt)
> > I attached the generated IR before and after the change. It's only one line diff:
> > ```
> >    call void @llvm.memset.p0.i64(ptr noundef nonnull align 16 dereferenceable(16) %9, i8 0, i64 16, i1 false)
> >    call void %49(ptr noundef nonnull %8, ptr noundef nonnull %9) #16
> >    %61 = call i32 @llvm.abs.i32(i32 %60, i1 true)
> > -  %62 = sitofp i32 %61 to float
> > +  %62 = uitofp i32 %61 to float
> >    %63 = load i32, ptr %9, align 16
> >    %64 = sitofp i32 %63 to float
> >    %65 = fcmp une float %64, %62
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > generation command is `clang -O1 -fsized-deallocation '-std=gnu++20' -c pre.ii -emit-llvm -S -o /tmp/ir_before.ll`
> > I'm trying to reduce the preprocessed file, tho not sure i'll keep the semantics of the failure.
> 
> This should be sufficient, thank you!

Might have been related to: https://github.com/llvm/llvm-project/commit/12836467b76c56872b4c22a6fd44bcda696ea720

**Comment by topperc** [comment]
> > > Well, I'm not sure how proper that wold be as a reproducer,
> > > I extracted the mentioned test to a program:
> > > ```
> > > #include <cmath>
> > > 
> > > #include "third_party/swiftshader/src/Reactor/Coroutine.hpp"
> > > #include "third_party/swiftshader/src/Reactor/Reactor.hpp"
> > > 
> > > using float4 = float[4];
> > > using int4 = int[4];
> > > 
> > > static std::string testName() { return "test name"; }
> > > 
> > > using namespace rr;
> > > 
> > > int main() {
> > >   Function<Void(Pointer<Int4>, Pointer<Int4>)> function;
> > >   {
> > >     Pointer<Int4> x = function.Arg<0>();
> > >     Pointer<Int4> y = function.Arg<1>();
> > > 
> > >     *y = Abs(*x);
> > >   }
> > > 
> > >   auto routine = function(testName().c_str());
> > >   auto callable = (void (*)(int4 *, int4 *))routine->getEntry();
> > > 
> > >   int input[] = {1, -1, 0, (int)0x80000000};
> > > 
> > >   for (int x : input) {
> > >     int4 v_in = {x, x, x, x};
> > >     int4 v_out = {0};
> > > 
> > >     callable(&v_in, &v_out);
> > > 
> > >     float expected = abs(x);
> > >     if (v_out[0] != expected) {
> > >       return 10;
> > >     }
> > >   }
> > > }
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > Before the change program exits with 0, after it exists with 10. More precisely: `v_out[0]` is: -2147483648, `expected` is: 2.14748365e+09
> > > [out_at.txt](https://github.com/llvm/llvm-project/files/14670227/out_at.txt) [out_before.txt](https://github.com/llvm/llvm-project/files/14670228/out_before.txt)
> > > I attached the generated IR before and after the change. It's only one line diff:
> > > ```
> > >    call void @llvm.memset.p0.i64(ptr noundef nonnull align 16 dereferenceable(16) %9, i8 0, i64 16, i1 false)
> > >    call void %49(ptr noundef nonnull %8, ptr noundef nonnull %9) #16
> > >    %61 = call i32 @llvm.abs.i32(i32 %60, i1 true)
> > > -  %62 = sitofp i32 %61 to float
> > > +  %62 = uitofp i32 %61 to float
> > >    %63 = load i32, ptr %9, align 16
> > >    %64 = sitofp i32 %63 to float
> > >    %65 = fcmp une float %64, %62
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > generation command is `clang -O1 -fsized-deallocation '-std=gnu++20' -c pre.ii -emit-llvm -S -o /tmp/ir_before.ll`
> > > I'm trying to reduce the preprocessed file, tho not sure i'll keep the semantics of the failure.
> > 
> > 
> > This should be sufficient, thank you!
> 
> Might have been related to: [1283646](https://github.com/llvm/llvm-project/commit/12836467b76c56872b4c22a6fd44bcda696ea720)

Doesn't that program call `abs` on 0x80000000 which is poison?

**Pull request closed without merging**
