### PR TITLE
[libc][POSIX][pthreads] implemented missing pthread_rwlockattr functions

### LINKED ISSUE #89443: [libc][gnu ext] implement pthread_rwlockattr_{get|set}kind_np
These functions are perhaps useful. Not implemented in #89322 because I didn't know they existed outside of POSIX.

Since these aren't POSIX but instead gnu extensions, these should go in FOO rather than libc/spec/posix.td; we already have an entry for pthreads.h in that file.  It will be easier for someone to start on this once #89322 lands.

I would extend our definition of `pthread_rwlockattr_t` in libc/include/llvm-libc-types/pthread_rwlockattr_t.h to include a new `int` member named `pref` such that these functions are simple getters and setters.

Then it sounds like we should define 3 macros (in libc/include/pthread.h.def, though keep an eye on https://github.com/llvm/llvm-project/issues/88997, too)
- PTHREAD_RWLOCK_PREFER_READER_NP
- PTHREAD_RWLOCK_PREFER_WRITER_NP
- PTHREAD_RWLOCK_PREFER_WRITER_NONRECURSIVE_NP

### PR DESCRIPTION
**Pull request by HendrikHuebner**
Closes #89443

I added the two missing functions and respective test cases. Let me know if anything needs changing.

### CODE REVIEW

**Review by michaelrj-google — APPROVED** [review]
This patch looks good to me, thanks for submitting it! Feel free to ping me if you need me to merge it for you.

**Comment by michaelrj-google** [comment]
ah, the formatter found some issues. You should address those before landing

**Review by nickdesaulniers — APPROVED** [review]

**Comment by nickdesaulniers** [comment]
thanks for the patch!

**Comment by HendrikHuebner** [comment]
@nickdesaulniers can this get merged?

**Comment by SchrodingerZhu** [comment]
@nickdesaulniers seems to be traveling. I will merge this according to previous approval.

**Comment by nickdesaulniers** [comment]
The errors from the bot are:
```
/home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian-fullbuild/libc-x86_64-debian-fullbuild-dbg/llvm-project/libc/src/pthread/pthread_rwlockattr_getkind_np.cpp:20:17: error: no member named 'pref' in 'pthread_rwlockattr_t'
  *pref = attr->pref;
          ~~~~  ^
1 error generated.
[298/496] Building CXX object projects/libc/src/stdlib/CMakeFiles/libc.src.stdlib.strfroml.dir/strfroml.cpp.o
[299/496] Building CXX object projects/libc/src/pthread/CMakeFiles/libc.src.pthread.pthread_rwlockattr_destroy.dir/pthread_rwlockattr_destroy.cpp.o
[300/496] Building CXX object projects/libc/src/pthread/CMakeFiles/libc.src.pthread.pthread_rwlockattr_setkind_np.dir/pthread_rwlockattr_setkind_np.cpp.o
FAILED: projects/libc/src/pthread/CMakeFiles/libc.src.pthread.pthread_rwlockattr_setkind_np.dir/pthread_rwlockattr_setkind_np.cpp.o 
/usr/bin/clang++ -DLIBC_NAMESPACE=__llvm_libc_19_0_0_git -D_DEBUG -I/home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian-fullbuild/libc-x86_64-debian-fullbuild-dbg/build/projects/libc/src/pthread -I/home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian-fullbuild/libc-x86_64-debian-fullbuild-dbg/llvm-project/libc/src/pthread -I/home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian-fullbuild/libc-x86_64-debian-fullbuild-dbg/llvm-project/libc -isystem /home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian-fullbuild/libc-x86_64-debian-fullbuild-dbg/build/projects/libc/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -g -fpie -DLIBC_FULL_BUILD -ffreestanding -fno-builtin -fno-exceptions -fno-lax-vector-conversions -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-rtti -ftrivial-auto-var-init=pattern -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wall -Wextra -Werror -Wconversion -Wno-sign-conversion -Wimplicit-fallthrough -Wwrite-strings -Wextra-semi -Wnewline-eof -Wnonportable-system-include-path -Wstrict-prototypes -Wthread-safety -Wglobal-constructors -DLIBC_COPT_PUBLIC_PACKAGING -std=c++17 -MD -MT projects/libc/src/pthread/CMakeFiles/libc.src.pthread.pthread_rwlockattr_setkind_np.dir/pthread_rwlockattr_setkind_np.cpp.o -MF projects/libc/src/pthread/CMakeFiles/libc.src.pthread.pthread_rwlockattr_setkind_np.dir/pthread_rwlockattr_setkind_np.cpp.o.d -o projects/libc/src/pthread/CMakeFiles/libc.src.pthread.pthread_rwlockattr_setkind_np.dir/pthread_rwlockattr_setkind_np.cpp.o -c /home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian-fullbuild/libc-x86_64-debian-fullbuild-dbg/llvm-project/libc/src/pthread/pthread_rwlockattr_setkind_np.cpp
/home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian-fullbuild/libc-x86_64-debian-fullbuild-dbg/llvm-project/libc/src/pthread/pthread_rwlockattr_setkind_np.cpp:26:9: error: no member named 'pref' in 'pthread_rwlockattr_t'
  attr->pref = pref;
  ~~~~  ^
1 error generated.
[301/496] Building CXX object projects/libc/src/pthread/CMakeFiles/libc.src.pthread.pthread_mutex_lock.dir/pthread_mutex_lock.cpp.o
[302/496] Building CXX object projects/libc/src/string/CMakeFiles/libc.src.string.memset_explicit.dir/memset_explicit.cpp.o
[303/496] Building CXX object projects/libc/src/pthread/CMakeFiles/libc.src.pthread.pthread_mutex_unlock.dir/pthread_mutex_unlock.cpp.o
[304/496] Building CXX object projects/libc/src/pthread/CMakeFiles/libc.src.pthread.pthread_rwlockattr_init.dir/pthread_rwlockattr_init.cpp.o
FAILED: projects/libc/src/pthread/CMakeFiles/libc.src.pthread.pthread_rwlockattr_init.dir/pthread_rwlockattr_init.cpp.o 
/usr/bin/clang++ -DLIBC_NAMESPACE=__llvm_libc_19_0_0_git -D_DEBUG -I/home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian-fullbuild/libc-x86_64-debian-fullbuild-dbg/build/projects/libc/src/pthread -I/home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian-fullbuild/libc-x86_64-debian-fullbuild-dbg/llvm-project/libc/src/pthread -I/home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian-fullbuild/libc-x86_64-debian-fullbuild-dbg/llvm-project/libc -isystem /home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian-fullbuild/libc-x86_64-debian-fullbuild-dbg/build/projects/libc/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wsuggest-override -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -g -fpie -DLIBC_FULL_BUILD -ffreestanding -fno-builtin -fno-exceptions -fno-lax-vector-conversions -fno-unwind-tables -fno-asynchronous-unwind-tables -fno-rtti -ftrivial-auto-var-init=pattern -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -Wall -Wextra -Werror -Wconversion -Wno-sign-conversion -Wimplicit-fallthrough -Wwrite-strings -Wextra-semi -Wnewline-eof -Wnonportable-system-include-path -Wstrict-prototypes -Wthread-safety -Wglobal-constructors -DLIBC_COPT_PUBLIC_PACKAGING -std=c++17 -MD -MT projects/libc/src/pthread/CMakeFiles/libc.src.pthread.pthread_rwlockattr_init.dir/pthread_rwlockattr_init.cpp.o -MF projects/libc/src/pthread/CMakeFiles/libc.src.pthread.pthread_rwlockattr_init.dir/pthread_rwlockattr_init.cpp.o.d -o projects/libc/src/pthread/CMakeFiles/libc.src.pthread.pthread_rwlockattr_init.dir/pthread_rwlockattr_init.cpp.o -c /home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian-fullbuild/libc-x86_64-debian-fullbuild-dbg/llvm-project/libc/src/pthread/pthread_rwlockattr_init.cpp
/home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian-fullbuild/libc-x86_64-debian-fullbuild-dbg/llvm-project/libc/src/pthread/pthread_rwlockattr_init.cpp:20:9: error: no member named 'pref' in 'pthread_rwlockattr_t'
  attr->pref = PTHREAD_RWLOCK_PREFER_READER_NP;
  ~~~~  ^
```
So it looks like you missed adding the new member to the struct definition for the getter/setters you added.

**Comment by nickdesaulniers** [comment]
specifically, libc/include/llvm-libc-types/pthread_rwlockattr_t.h needs the addition of the new field.

**Comment by nickdesaulniers** [comment]
sorry I missed that in the original code review!

**Pull request merged**
