### PR TITLE
[NFCI][BitcodeReader]Read real GUID from VI as opposed to storing it in map

### PR DESCRIPTION
**Pull request by mingmingl-llvm**
Currently, `ValueIdToValueInfoMap` [1] stores `std::tuple<ValueInfo, GlobalValue::GUID /* original GUID */, GlobalValue::GUID /* real GUID*/ >`. This change updates the stored value type to `std::pair<ValueInfo, GlobalValue::GUID /* original GUID */>`, and reads real GUID from ValueInfo.

When an entry is inserted into `ValueIdToValueInfoMap`, ValueInfo is created or inserted using real GUID [2]. ValueInfo keeps a pointer to GlobalValueMap [3], using either `GUID` or `{GUID, Name}` [4] when reading per-module summaries to create a combined summary.

[1] owned by per module-summary bitcode reader https://github.com/llvm/llvm-project/blob/caebb4562ce634a22f7b13480b19cffc2a6a6730/llvm/lib/Bitcode/Reader/BitcodeReader.cpp#L947-L950
[2] [first](https://github.com/llvm/llvm-project/blob/caebb4562ce634a22f7b13480b19cffc2a6a6730/llvm/lib/Bitcode/Reader/BitcodeReader.cpp#L7130-L7133), [second](https://github.com/llvm/llvm-project/blob/caebb4562ce634a22f7b13480b19cffc2a6a6730/llvm/lib/Bitcode/Reader/BitcodeReader.cpp#L7221-L7222), [third](https://github.com/llvm/llvm-project/blob/caebb4562ce634a22f7b13480b19cffc2a6a6730/llvm/lib/Bitcode/Reader/BitcodeReader.cpp#L7622-L7623)
[3] https://github.com/llvm/llvm-project/blob/caebb4562ce634a22f7b13480b19cffc2a6a6730/llvm/include/llvm/IR/ModuleSummaryIndex.h#L1427-L1431
[4] https://github.com/llvm/llvm-project/blob/caebb4562ce634a22f7b13480b19cffc2a6a6730/llvm/include/llvm/IR/ModuleSummaryIndex.h#L1631
and https://github.com/llvm/llvm-project/blob/caebb4562ce634a22f7b13480b19cffc2a6a6730/llvm/include/llvm/IR/ModuleSummaryIndex.h#L1621

### CODE REVIEW

**Comment by kazutakahirata** [comment]
Nice finding!  Let me see if I understand things correctly.

- We always create an instance of `ValueInfo` with the same GUID as `std::get<2>`.
- Once an instance of `ValueInfo` is created, its pointer portion never changes.
- The pointer portion of `ValueInfo` points to an key-value pair of `GlobalValueSummaryMapTy`, so the key portion, `GUID`, shouldn't change.

So, `std::get<2>(VIAndOriginalGUID)` and `VIAndOriginalGUID.first.getGUID()` must be always the same.

Did I get this right?

**Comment by minglotus-6** [comment]
> * We always create an instance of `ValueInfo` with the same GUID as `std::get<2>`.

Yup this is the case for all ([first](https://github.com/llvm/llvm-project/blob/caebb4562ce634a22f7b13480b19cffc2a6a6730/llvm/lib/Bitcode/Reader/BitcodeReader.cpp#L7130-L7133), [second](https://github.com/llvm/llvm-project/blob/caebb4562ce634a22f7b13480b19cffc2a6a6730/llvm/lib/Bitcode/Reader/BitcodeReader.cpp#L7221-L7222), [third](https://github.com/llvm/llvm-project/blob/caebb4562ce634a22f7b13480b19cffc2a6a6730/llvm/lib/Bitcode/Reader/BitcodeReader.cpp#L7622-L7623)) insertions.

> Once an instance of ValueInfo is created, its pointer portion never changes.
> The pointer portion of ValueInfo points to an key-value pair of GlobalValueSummaryMapTy, so the key portion, GUID, shouldn't change.

This is the case as well.

Basically, `ValueIdToValueInfoMap` is owned and used by the per module-summary bitcode reader, to associate ([serialized](https://github.com/llvm/llvm-project/blob/cf11eb62e1d0fa41f68b4ca3150eac854ac2e991/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp#L4364), [per-module](https://github.com/llvm/llvm-project/blob/cf11eb62e1d0fa41f68b4ca3150eac854ac2e991/llvm/lib/Bitcode/Writer/BitcodeWriter.cpp#L259)) 'value-id'  with the (in-memory) value summary (from combined summary). 

So the ValueInfo's pointer portion essentially points to the [global-value summary entry](https://github.com/llvm/llvm-project/blob/cf11eb62e1d0fa41f68b4ca3150eac854ac2e991/llvm/include/llvm/IR/ModuleSummaryIndex.h#L176), which is owned by [CombinedIndex](https://github.com/llvm/llvm-project/blob/cf11eb62e1d0fa41f68b4ca3150eac854ac2e991/llvm/include/llvm/LTO/LTO.h#L341). 

Since bitcode readers are [(reasonably) destructed](https://github.com/llvm/llvm-project/blob/bc59b638ae35594b55a439a5986519a3f9cc903d/llvm/lib/Bitcode/Reader/BitcodeReader.cpp#L8411-L8413) after the per-module summary content are merged into combined index, this change doesn't help reduce peak memory usage. This change is not complex anyway, so I just thought about sending it out.

**Review by kazutakahirata — APPROVED** [review]
LGTM.  See a comment about "tuple".

**Comment by minglotus-6** [comment]
thanks for the reviews!

**Pull request merged**
