### PR TITLE
Fix textual/bytecode roundtrip for SPIRV_LinkageAttributesAttr

### PR DESCRIPTION
**Pull request by mfrancio**
The patch fixes the behavior of table-generated printers for std::string
parameters and enables roundtripping to text and bytecode IR that
contains `SPIRV_LinkageAttributesArr`.

### CODE REVIEW

**Comment by mfrancio** [comment]
> I think #82953 would achieve the same thing? (seems like a better fix to me)

Yeah, i agree with that :) 

Is there a convention for dialects to follow about attributes? It seems like this dialect is built around non-attribute parameters and printers/parsers seem to work somewhat coincidentally, as this soon-to-close patch is highlighting.

**Comment by joker-eph** [comment]
What kind of other example did you see?

**Comment by mfrancio** [comment]
pretty much any attribute in SPIRVAttributes.td? let's take one:
```
def SPIRV_CooperativeMatrixPropertiesKHRAttr :
    SPIRV_Attr<"CooperativeMatrixPropertiesKHR", "coop_matrix_props_khr"> {
  let parameters = (ins
    "uint32_t":$m_size,
    "uint32_t":$n_size,
    "uint32_t":$k_size,
    "mlir::Type":$a_type,
    "mlir::Type":$b_type,
    "mlir::Type":$c_type,
    "mlir::Type":$result_type,
    "bool":$acc_sat,
    "mlir::spirv::ScopeAttr":$scope
  );
  let assemblyFormat = "`<` struct(params) `>`";
}
```
Unless i am missing something, roundtripping such an attribute works just because the overloaded `<<` is coincidentally equal to how the parser executes. For strings, this was not the case (`<<` does not add the string token that the parser would look for).

This seemed like a gap in how SPIRV attributes interact with table-generated print/parse methods.

**Comment by joker-eph** [comment]
Are you referring to uint32_t? Scalars are just fine here (actually better: more compact than an indirection to another attribute)

**Comment by mfrancio** [comment]
well, all of them - uint32_t/IntegerAttr, Type/TypeAttr, bool/BoolAttr. I get your point though, thanks!

**Pull request closed without merging**
