### PR TITLE
Revert "[mlir][vector] Move transpose with unit-dim to shape_cast pattern (#72493)"

### PR DESCRIPTION
**Pull request by MaheshRavishankar**
This reverts commit 95acb33b458128b7ff2314efa3b41b93b3897179.

### CODE REVIEW

**Review by qedawkins — APPROVED** [review]
+1, I'm not sure this is well suited for a canonicalization. `vector.transpose` has an additional guarantee that the source and result vector ranks are the same, as well as tells how to relate dimensions between the source and the result. I see that as useful information even when all of the transposed dimensions are unit dims. `shape_cast` does not have that same guarantee and might require analysis to recover the semantic meaning of the shape_cast in some cases (not that I have such a case on hand, but shape casts like this aren't easy to handle in SPIR-V).

**Comment by banach-space** [comment]
@MaheshRavishankar, while we agreed that it's fine to revert this patch to unblock SPIR-V code-gen, it was also expected that there would be a test that would capture this sort of issues in the future. 

Please, could a test be added _upstream_ so that patches are reverted based on **upstream** buildbot failures instead of users reporting issues **downstream**?

**Comment by MaheshRavishankar** [comment]
> @MaheshRavishankar, while we agreed that it's fine to revert this patch to unblock SPIR-V code-gen, it was also expected that there would be a test that would capture this sort of issues in the future. 
> 
> Please, could a test be added _upstream_ so that patches are reverted based on **upstream** buildbot failures instead of users reporting issues **downstream**? 

Sorry, maybe I pushed the button too hastily. I'll try to create a repro upstream but it isn't always easy since it could be as complex as running the entire spirv lowering pipeline used in IREE.  Even with this particular revert the conversion is still broken. For this particular one though, having patterns in canonicalization should have a high bar since it applies everywhere in the stack, and I thought there was an agreement that this doesn't fit the bill of being a canonicalization. Hence I pushed it since I already had the PR. Let's continue the conversation on the other PR w.r.t having an upstream test and how to assess the broken spirv conversion.

**Comment by stellaraccident** [comment]
I think there are two separate issues here:

1. There is a bar for what makes something a canonicalization which I am not hearing consensus on. I think that alone justifies a revert and further discussion. The price of just landing things by PR vs RFC or broader discussion for things like this is that we have to have a low cost path to revert when we mis-judge consensus. 
2. Getting a SPIR-V conversion test which exercises this is a good thing to do. Thank you for identifying it.

This particular patch was reverted because of point 1. The bar for canonicalization specifically is universal accessibility and agreement that the form being canonicalized to is actually "canonical". Both are judgment calls and a matter of design.

**Comment by banach-space** [comment]
> Sorry, maybe I pushed the button too hastily. 

No worries, we did agree to have this reverted. I just wanted to make sure that we use this opportunity to improve test coverage in MLIR - ideally there would be a test that would prevent us from landing this in the first place.

> Both are judgment calls and a matter of design.

I think that there's also a friction between "canonical for CPUs" and "canonical for GPUs" - currently there is no mechanism to distinguish between the two.

This has been a very useful discussion - I didn't realise that things would be so different for GPUs. Apologies for missing that.

**Comment by joker-eph** [comment]
Side note: please provide clear reasoning  in commit message when reverting.

**Pull request merged**
