### PR TITLE
[lldb] DebugInfoD tests & fixes (but with dwp testing disabled)

### PR DESCRIPTION
**Pull request by kevinfrei**
This is all the tests and fixes I've had percolating since my first attempt at this in January. After 6 months of trying, I've given up on adding the ability to test DWP files in LLDB API tests. I've left both the tests (disabled) and the changes to Makefile.rules in place, in the hopes that someone who can configure the build bots will be able to enable the tests once a non-borked dwp tool is widely available.

Other than disabling the DWP tests, this continues to be the same diff that I've tried to land and [not](https://github.com/llvm/llvm-project/pull/90622) [revert](https://github.com/llvm/llvm-project/pull/87676) [five](https://github.com/llvm/llvm-project/pull/86812) [times](https://github.com/llvm/llvm-project/pull/85693) [before](https://github.com/llvm/llvm-project/pull/96802). There are a couple of fixes that the testing exposed, and I've abandoned the DWP tests because I want to get those fixes finally upstreamed, as without them DebugInfoD is less useful.

### CODE REVIEW

**Comment by kevinfrei** [comment]
@JDevlieghere or @clayborg if one of you could please approve & land this, I *believe* this disables the tests that caused the previous diff to be reverted.

**Review by JDevlieghere — APPROVED** [review]

**Comment by kevinfrei** [comment]
"fixed forward" with [PR98351](https://github.com/llvm/llvm-project/pull/98351/commits) if someone can approve & land that (it just disabled the baseline test for DWP stuff, as well: I missed it because the dwp tests run on all the machines I have access to :/ )

**Comment by walter-erquinigo** [comment]
@kevinfrei , I'm so sorry to tell you that I have reverted this patch. The revert commit is 27b2f4f861b8aeeabc4eb1a97649062de8fa3992 and I left some notes there, which I also copy here:


The patch #98344 causes a crash in LLDB when parsing some files like `numpy.libs/libgfortran-daac5196.so.5.0.0` on graviton (you can download it in https://drive.google.com/file/d/12ygLjJwWpzdYsrzBPp1JGiFHxcgM0-XY/view?usp=drive_link if you want to troubleshoot yourself).
    
    The assert that is hit is the following:
    
    ```
    llvm-project/lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp:2452: std::pair<unsigned int, std::map<long unsigned int, lldb_private::AddressClass> > ObjectFileELF::ParseSymbolTable(lldb_private::Symtab*, lldb::user_id_t, lldb_private::Section*): Assertion `strtab->GetObjectFile() == this' failed.
    [383588:383636:20240716,025305.572639:ERROR crashpad_client_linux.cc:780] Crashpad isn't enabled

**Comment by kevinfrei** [comment]
> @kevinfrei , I'm so sorry to tell you that I have reverted this patch. The revert commit is [27b2f4f](https://github.com/llvm/llvm-project/commit/27b2f4f861b8aeeabc4eb1a97649062de8fa3992) and I left some notes there, which I also copy here:
> 
> The patch #98344 causes a crash in LLDB when parsing some files like `numpy.libs/libgfortran-daac5196.so.5.0.0` on graviton (you can download it in https://drive.google.com/file/d/12ygLjJwWpzdYsrzBPp1JGiFHxcgM0-XY/view?usp=drive_link if you want to troubleshoot yourself).
> 
> ```
> The assert that is hit is the following:
> 
> ```
> llvm-project/lldb/source/Plugins/ObjectFile/ELF/ObjectFileELF.cpp:2452: std::pair<unsigned int, std::map<long unsigned int, lldb_private::AddressClass> > ObjectFileELF::ParseSymbolTable(lldb_private::Symtab*, lldb::user_id_t, lldb_private::Section*): Assertion `strtab->GetObjectFile() == this' failed.
> ```

Reverted with a repro instead of some inscrutable "This didn't work on a build machine configured by someone 4 years ago who promptly forgot what they did and there's no documentation, but here's this log: good luck!" is glorious! I'll get on it- thanks 😃

**Comment by walter-erquinigo** [comment]
@kevinfrei , I'm glad I can be of help to you! Let me know if you want me to try out your next iteration of this PR on my device.

**Pull request merged**
