### PR TITLE
[LiveDebugVariables] Add basic verification

### PR DESCRIPTION
**Pull request by jayfoad**
Add a basic implementation of verifyAnalysis that just checks that the
analysis does not refer to any SlotIndexes for instructions that have
been deleted. This was useful for diagnosing some SlotIndexes-related
problems caused by #67038.

### CODE REVIEW

**Comment by jmorse** [comment]
In principle this LGTM, although it's been a long time since I've looked at LiveDebugVariables. As far as I recall, we use `setUnchecked` to do manual maintenance of ranges but they should all coalesce in the end. And it doesn't make sense for there to be a zero-length range of variable location.

This does involve iterating over every range of every variable in the function, which might have compile-time performance implications. Is it worth putting this behind an EXPENSIVE_CHECKS ifdef? (I haven't followed the SlotIndex related problems you've mentioned, I don't know whether it needs running on every compilation)

**Comment by jayfoad** [comment]
> In principle this LGTM, although it's been a long time since I've looked at LiveDebugVariables. As far as I recall, we use `setUnchecked` to do manual maintenance of ranges but they should all coalesce in the end. And it doesn't make sense for there to be a zero-length range of variable location.

Stepping back a bit: I am trying to diagnose problems where the cached LiveDebugVariables analysis info refers to SlotIndexes for instructions that have been deleted. (Possibly this is caused by RegAlloc not updating LDV properly - I am still investigating that aspect of it.) I am pretty sure that this is not allowed, although currently it seems to be harmless because SlotIndexes does not actually delete or reuse those slots. #67038 tried to change SlotIndexes so that it no longer maintains these deleted slots and they can end up containing garbage values. The "zero-length range" issue that I check for here is just one possible consequence of depending on those garbage values.

It would be better if I could directly query SlotIndexes to ask "is this slot still live?" (under `#ifndef NDEBUG`). I'll work on implementing something like that.

> This does involve iterating over every range of every variable in the function, which might have compile-time performance implications. Is it worth putting this behind an EXPENSIVE_CHECKS ifdef? (I haven't followed the SlotIndex related problems you've mentioned, I don't know whether it needs running on every compilation)

I think generally acceptable performance-wise for `verifyAnalysis` to make a single pass over all information cached by an analysis.

**Comment by jayfoad** [comment]
> It would be better if I could directly query SlotIndexes to ask "is this slot still live?" (under #ifndef NDEBUG). I'll work on implementing something like that.

I have reworked the patch along those lines. It currently causes some lit tests failures in my build. I would suggest that these are all pre-existing problems that really ought to be fixed.
```
Failed Tests (6):
  LLVM :: CodeGen/Thumb2/pr52817.ll
  LLVM :: DebugInfo/ARM/PR26163.ll
  LLVM :: DebugInfo/COFF/fpo-csrs.ll
  LLVM :: DebugInfo/X86/pr34545.ll
  LLVM :: DebugInfo/X86/spill-indirect-nrvo.ll
  LLVM :: tools/llvm-dwarfdump/X86/LTO_CCU_zero_loc_cov.ll
```

**Comment by jmorse** [comment]
This fell off my radar, sorry. Thanks for the background on what's going on here, FTR, this patch LGTM. Note that there are two flavours of debug-info format in the CodeGen pipeline and the records you're verifying only addresses one of them, there's also a collection that contains SlotIndexes in StashedDebugInstrs and PHIValToPos that you might want to verify too.

I had a look at one of the failures (spill-indirect-nrvo.ll), and it would appear that:
 * We split a virtual register location with a COPY,
 * LiveDebugVariables updates it's mappings to record the new location at the position of the copy, with vreg %7
 * InlineSpiller::spill comes along and spills the value, making the COPY a dead definition (apparently),
 * The mapping of slot-index to vreg %7 continues on in LiveDebugVariables,
 * When VirtRegRewriter comes along and emits DBG_VALUE instructions, in UserValue::rewriteLocations, vreg %7 which isn't otherwise defined has a stack location looked up by VRM.getStackSlot. As it's the same location as earlier DBG_VALUEs, they get coalesced together (I think) and the dead slot index doesn't get used.

This feels like an error where, by chance, the right thing happens most of the time. I've got various feelings on solutions:
 * We could rewrite all the location-mappings at the end of regalloc to ensure illegal slotindexes get coalesced away early,
 * We could explicitly signal from the regalloc code that a definition is being deleted.

As far as I'm aware LiveDebugVariables doesn't have any concept of "this assignment is just going to completely go away", LiveRangeEdit::eliminateDeadDef would have to be updating LiveDebugVariables to let it know. I'm not sure how we'd then update the variable location data in that circumstance.

CC @felipepiovezan as we won't be seeing this on X86 as it uses the other CodeGen debug-info format, but it could be an issue that arm-like systems see.

**Comment by jayfoad** [comment]
Thanks for the investigation! I'm busy with other things at the moment but will come back to this when I have some time.

**Comment by jayfoad** [comment]
> jayfoad closed this by deleting the head repository 4 hours ago

Sorry. Recreated as #79846.

**Pull request closed without merging**
