### PR TITLE
[aarch64] Add support for the __{inc|add}x18{byte|word|dword|qword intrinsics

### PR DESCRIPTION
**Pull request by dpaoliello**
Adds support for the following MSVC intrinsics:
* `__addx18byte`
* `__addx18word`
* `__addx18dword`
* `__addx18qword`
* `__incx18byte`
* `__incx18word`
* `__incx18dword`
* `__incx18qword`

These are documented at: <https://learn.microsoft.com/en-us/cpp/intrinsics/arm64-intrinsics?view=msvc-170>

### CODE REVIEW

**Review by efriedma-quic — APPROVED** [review]
LGTM

**Review by efriedma-quic — CHANGES_REQUESTED** [review]
Sorry, just spotted an issue: I don't think you're emitting the operations in the correct order.  You need to emit both arguments before you read the register or load the value.

If you have some non-trivial operation like a call in one of the arguments, you don't want that call to happen in the middle of the operation.  MSVC appears to emit the arguments before touching x18.

**Comment by dpaoliello** [comment]
> Sorry, just spotted an issue: I don't think you're emitting the operations in the correct order. You need to emit both arguments before you read the register or load the value.
> 
> If you have some non-trivial operation like a call in one of the arguments, you don't want that call to happen in the middle of the operation. MSVC appears to emit the arguments before touching x18.

Done, and fixed the read/write x18 intrinsics as well.

**Review by efriedma-quic — APPROVED** [review]
LGTM

**Pull request merged**
