### PR TITLE
[SimplifyCFG] `switch`: Do Not Transform the Default Case if the Condition is Too Wide

### PR DESCRIPTION
**Pull request by qiongsiwu**
https://github.com/llvm/llvm-project/pull/76669 taught SimplifyCFG to handle switches when `default` has only one case. When the `switch`'s condition is wider than 64 bit, the current implementation can calculate the wrong default value. This PR skips cases where the condition is too wide.

### CODE REVIEW

**Comment by dtcxzyw** [comment]
I don't think it is worth handing `switch i128` cases.
We can early exit if the bit width of condition value is larger than 64:
```
  auto *CondTy = cast<IntegerType>(SI->getCondition()->getType());
  if (CondTy->getIntegerBitWidth() > 64 ||
      !DL.fitsInLegalInteger(CondTy->getIntegerBitWidth()))
    return false;
```

**Comment by qiongsiwu** [comment]
> I don't think it is worth handing `switch i128` cases. We can early exit if the bit width of condition value is larger than 64:
> 
> ```
>   auto *CondTy = cast<IntegerType>(SI->getCondition()->getType());
>   if (CondTy->getIntegerBitWidth() > 64 ||
>       !DL.fitsInLegalInteger(CondTy->getIntegerBitWidth()))
>     return false;
> ```

Thanks for the fast response @dtcxzyw ! I can certainly implement the early escape. Could you help me understand why it is not worth handling conditions of wider widths?

**Comment by dtcxzyw** [comment]
> > I don't think it is worth handing `switch i128` cases. We can early exit if the bit width of condition value is larger than 64:
> > ```
> >   auto *CondTy = cast<IntegerType>(SI->getCondition()->getType());
> >   if (CondTy->getIntegerBitWidth() > 64 ||
> >       !DL.fitsInLegalInteger(CondTy->getIntegerBitWidth()))
> >     return false;
> > ```
> 
> Thanks for the fast response @dtcxzyw ! I can certainly implement the early escape. Could you help me understand why it is not worth handling conditions of wider widths?

+ `switch i128` is rare in real code.
+ It is impossible to convert it into jump table.

**Comment by qiongsiwu** [comment]
>     * `switch i128` is rare in real code.
> 
>     * It is impossible to convert it into jump table.

Sounds good! The PR is revised. I kept the test case to "document" the behaviour, but I can take it out if it is not necessary.

**Review by dianqk — APPROVED** [review]
LGTM. Thanks!

**Comment by qiongsiwu** [comment]
Thanks @DianQK !

In light of https://github.com/llvm/llvm-project/pull/76669#issuecomment-1888236912, I will not merge this PR at the moment, since https://github.com/llvm/llvm-project/pull/76669 may get reverted or require more work.

**Comment by nikic** [comment]
@qiongsiwu Please do merge it now. If necessary, this change will be reverted together with the base commit.

**Comment by qiongsiwu** [comment]
> @qiongsiwu Please do merge it now. If necessary, this change will be reverted together with the base commit.

Thanks for chiming in @nikic ! Merging this PR now.

**Pull request merged**
