### PR TITLE
[Flang][OpenMP] Remove deprecated FIR lowering tests

### PR DESCRIPTION
**Pull request by kiranchandramohan**
Remove OpenMP FIR lowering tests. These are now replaced by HLFIR based tests. This might hopefully speedup testing as well.

### CODE REVIEW

**Review by tblah — APPROVED** [review]
Looks good to me. Several things added recently use HLFIR tools and operations in lowering so we don't even support FIR lowering properly any more.

Hopefully this will also reduce the number of tests that need to be updated when lowering changes.

**Comment by Leporacanthicus** [comment]
Ship it! LGTM!

**Review by skatrak — APPROVED** [review]
Thank you, LGTM

**Comment by luporl** [comment]
LGTM, since all removed tests either have an equivalent HLFIR version or are now in test/Lower/OpenMP/PFT.
Thanks for this cleanup.

**Review by kparzysz — APPROVED** [review]
🎉 Thanks!

**Pull request merged**
