### PR TITLE
[SimplifyCFG] Not folding branch in loop header with constant iterations

### PR DESCRIPTION
**Pull request by xiangzh1**
[SimplifyCFG] Not folding branch in constant loops which expected unroll

    Constant iteration loop with unroll hint usually expected do unroll
    by consumers, folding branches in such loop header at SimplifyCFG will
    break unroll optimization.

for example:
 #program unroll
 for (int I = 0; I < ConstNum; ++I) { // ConstNum > 1
    if (Cond2) {
       break;
     }
      xxx loop body;
  }
 Folding these conditional branches may break loop unroll.

### CODE REVIEW

**Comment by xiangzh1** [comment]
Seems the check fail "dr2xx.cpp Line 1297: conversion from 'T' to 'unsigned long long' is ambiguous" has no relation with this change.

**Comment by xiangzh1** [comment]
> We should add TTI check for the condition. I believe don't unroll on X86 is a correct decision. Only like AMDGPU or NVPTX these GPU backend with heavy stack cost need this.
> 
> And I think you need to precommit tests first.

In fact, there is no direct/strong relation with stack cost, it mostly base on unroll or not (or other loop optimizations). Maybe we should check "unroll" info (e.g #pragma unroll) before do or not do this folding. A little trouble is loop info is not well established now.

**Comment by xiangzh1** [comment]
> > > And I think you need to precommit tests first.
Done
> > In fact, there is no direct/strong relation with stack cost, it mostly base on unroll or not (or other loop optimizations). Maybe we should check "unroll" info (e.g #pragma unroll, any targets with this hint should try best to unroll too) before do or not do this folding. A little trouble is loop info is not well established now.
> 
> Yeah, it is a problem we unroll or not. But this case generally I believe we don't want to unroll it.
Update to handle unroll hint
Thanks for reviewing!

**Review by nikic — COMMENTED** [review]
LoopUnroll supports upper bound unrolling. Why is it not working in this case?

**Comment by xiangzh1** [comment]
> We need at lease one more IR test.

Let me try

**Comment by xiangzh1** [comment]
> LoopUnroll supports upper bound unrolling. Why is it not working in this case?
for example:
#program unroll
for (int I = 0; I < LoopCount; ++I) { // ConstNum > 1
if (Cond2) {
break;
}
xxx loop body;
}

After the branches fodling, the old loop condition  "I < LoopCount" changed/disapeared, I think unroll can not make sure the "upper bound"

**Comment by bcl5980** [comment]
AMDGPU can not unorll this case:

https://godbolt.org/z/4Pq3bnzTT

But the same code in X86 looks can unroll:

https://godbolt.org/z/zr8aTG1KW

We may need to continue debug on it.

**Comment by xiangzh1** [comment]
> AMDGPU can not unorll this case:
> 
> https://godbolt.org/z/4Pq3bnzTT
> 
> But the same code in X86 looks can unroll:
> 
> https://godbolt.org/z/zr8aTG1KW
> 
> We may need to continue debug on it.

X86 do very conservative unroll too，its upper bound send to 4 (default is 8), if we not fold the loop branch, it can fully unroll (16)

**Comment by xiangzh1** [comment]
I think we should follow this principle：
if a loop required to be unroll later, we should not distroy the loop count info.

**Comment by bcl5980** [comment]
> I think we should follow this principle： if a loop required to be unroll later, we should not distroy the loop count info.

The ideal is right. But I think what nikic say is loop unroll should handle the case( upper bound unrolling). But It doesn't work. We need to find why loop unroll doesn't work (maybe in UnrollRuntimeLoopRemainder), then can check if it can do in loop unroll or stop the SimpilfyCfg's transform.

> > AMDGPU can not unorll this case:
> > https://godbolt.org/z/4Pq3bnzTT
> > But the same code in X86 looks can unroll:
> > https://godbolt.org/z/zr8aTG1KW
> > We may need to continue debug on it.
> 
> X86 do very conservative unroll too，its upper bound send to 4 (default is 8), if we not fold the loop branch, it can fully unroll (16)
So where is the different X86 can partial unroll but AMDGPU can not unroll at all?

**Comment by bcl5980** [comment]
https://godbolt.org/z/cMeE61bhf
Loop unroll with -unroll-runtime can partial unroll the case.
@nikic It looks if we don't avoid the transform, it will become a runtime unroll. 
@xiangzh1 's solution looks fine to me if we do not involve loopInfo in simplifycfg.

**Comment by xiangzh1** [comment]
> So where is the different X86 can partial unroll but AMDGPU can not unroll at all?
> https://godbolt.org/z/cMeE61bhf Loop unroll with -unroll-runtime can partial unroll the case. @nikic It looks if we don't avoid the transform, it will become a runtime unroll. The case before simplifycfg is https://godbolt.org/z/5MoYM8rGn. @xiangzh1 's solution looks fine to me if we do not involve loopInfo in simplifycfg. And we still need a mininal IR test for it.

1 In fact, I didn't much care about the different unroll between different targets. The loop unroll pass consider the TTI port, it is make sense to me "one do partial unroll or not" or "partial unroll with different unroll count".
I more care about the Known loop count for unroll become Unkown. This do big change for unroll (even successful). For example, loop with small Known loop count can usually be fully unrolled, which usually much simplify the address (offset) calculations in old iterations (then we can do a lot of others optimizations, e.g, SROA, for these simplifed calculations). But these don't work for Unkown loop count.

2 I am creating the mininal IR test. (I'll replace current .cu test with it, duo to I use -O2 in current test)

thanks again!

**Comment by xiangzh1** [comment]
Update: add ir test llvm/test/Transforms/SimplifyCFG/simplify-cfg-unroll.ll
(not sure it is minimal, llvm-reduce does works well for it, I mannualy create it)

**Comment by xiangzh1** [comment]
rebase

**Comment by nikic** [comment]
I checked, and for your test case, LoopUnroll recognizes the loop as an UpperBound unrolling candidate, but does not perform unrolling due to cost model.

The pragma unroll metadata currently only takes effect if there is an exact trip count, but not if there is an upper bound trip count. Making it work with an upper bound trip count as well should fix your case. See the code in shouldPragmaUnroll().

**Comment by xiangzh1** [comment]
> I checked, and for your test case, LoopUnroll recognizes the loop as an UpperBound unrolling candidate, but does not perform unrolling due to cost model.
> 
> The pragma unroll metadata currently only takes effect if there is an exact trip count, but not if there is an upper bound trip count. Making it work with an upper bound trip count as well should fix your case. See the code in shouldPragmaUnroll().

First, many thanks for checking the test.
Yes, that's another way to unroll too, but it is branch folding affected the cost model, it didn't consider the later unroll. In fact we don't much want to do unroll with UpperBound. Even it unroll successful with UpperBound, it is not better than unrolled with known loop count.  Espically for known small loop count which ususally can be full unrolled, in GPU this is much helpful to symplify address (offset) calculations, which is sensitive in SROA optimization and local mem use.

**Comment by nikic** [comment]
I think you are confusing upper bound and runtime unrolling. An upper bound unroll is a type of full unroll. In this case it would unroll it to 16 iterations, which is what you want, no?

**Comment by xiangzh1** [comment]
> I think you are confusing upper bound and runtime unrolling. An upper bound unroll is a type of full unroll. In this case it would unroll it to 16 iterations, which is what you want, no?
Yes！: ) I thouth the upper bound is "partial unroll", and I am supprised if it can fully unroll to 16 iterations with the branch folding, anyway let me check shouldPragmaUnroll(), thank you a lot!

**Comment by xiangzh1** [comment]
Hi friends, I created a new PR at https://github.com/llvm/llvm-project/pull/74703, many thanks for reviewing!!

**Pull request closed without merging**
