### PR TITLE
[X86][FP16] Limit combination of fp_round & concat to concat of 2 operands

### PR DESCRIPTION
**Pull request by fzou1**
Add check of number of operands for concat_vectors being equal to 2. This can 
avoid crash if there are more than 2 operands for concat_vectors and
operand 0 & 1 are undef value.

### CODE REVIEW

**Comment by fzou1** [comment]
See related discussion on https://reviews.llvm.org/D143872#4121716

**Review by phoebewang — APPROVED** [review]
LGTM, thanks!

**Comment by fzou1** [comment]
Is it okay to merge?

**Review by KanRobert — APPROVED** [review]
LGTM

**Pull request merged**
