### PR TITLE
[RISCV] Shrink vslideup's LMUL when lowering fixed insert_subvector 

### PR DESCRIPTION
**Pull request by lukel97**
Similar to #65598, if we're using a vslideup to insert a fixed length vector into another vector, then we can work out the minimum number of registers it will need to slide up across given the minimum VLEN, and shrink the type operated on to reduce LMUL accordingly.

This is somewhat dependent on #66211 , since it introduces a subregister copy that triggers a crash with -early-live-intervals in one of the tests.

Stacked upon #66211

### CODE REVIEW

**Comment by jayfoad** [comment]
> This is somewhat dependent on #66211 , since it introduces a subregister copy that triggers a crash with -early-live-intervals in one of the tests.

I think #65916 and #66211 are two different fixes for the same problem. Do you #65916 also fix the crash? Or do you really need #66211?

**Comment by lukel97** [comment]
> > This is somewhat dependent on #66211 , since it introduces a subregister copy that triggers a crash with -early-live-intervals in one of the tests.
> 
> I think #65916 and #66211 are two different fixes for the same problem. Do you #65916 also fix the crash? Or do you really need #66211?

Both fix the crash, but I closed #65916 in favour of #66211 since my understanding of LiveIntervals is limited

**Review by preames — APPROVED** [review]
LGTM

**Comment by topperc** [comment]
I think we're starting to see failures from this change. This fixes the failures I've seen, but I think there may be some ordering issues with when we decide to shrink. If we enter this particular `if` it doesn't seem like we should have done any shrinking in the first place.

```
diff --git a/llvm/lib/Target/RISCV/RISCVISelLowering.cpp b/llvm/lib/Target/RISCV/RISCVISelLowering.cpp
index c4942f9c637b..ee9957795f97 100644
--- a/llvm/lib/Target/RISCV/RISCVISelLowering.cpp
+++ b/llvm/lib/Target/RISCV/RISCVISelLowering.cpp
@@ -8641,6 +8641,9 @@ SDValue RISCVTargetLowering::lowerINSERT_SUBVECTOR(SDValue Op,
                          DAG.getUNDEF(ContainerVT), SubVec,
                          DAG.getConstant(0, DL, XLenVT));
     if (OrigIdx == 0 && Vec.isUndef() && VecVT.isFixedLengthVector()) {
+      if (ContainerVT != OrigContainerVT)
+        SubVec = DAG.getNode(ISD::INSERT_SUBVECTOR, DL, OrigContainerVT, OrigVec,
+                             SubVec, DAG.getVectorIdxConstant(0, DL));
       SubVec = convertFromScalableVector(VecVT, SubVec, DAG, Subtarget);
       return DAG.getBitcast(Op.getValueType(), SubVec);
     }
```

**Comment by lukel97** [comment]
@topperc whoops, thanks for catching that. Got a reproducer at https://github.com/llvm/llvm-project/pull/67535

**Pull request merged**
