### PR TITLE
[libc++] remove minor version in status pages

### PR DESCRIPTION
**Pull request by h-vetinari**
Minor version of releases starts at `N.1.0` for all releases since https://github.com/llvm/llvm-project/commit/4532617ae420056bf32f6403dde07fb99d276a49

The current status pages are not _terribly_ wrong (the version during development can be considered `N.0`), but still it's kinda weird to use versions that never get released as the lower bound. Other alternatives would be:
* remove minor versions completely from the status pages
* keep using `N.0` despite the minor (heh...) inaccuracy

### CODE REVIEW

**Comment by philnik777** [comment]
I think I'd go for dropping the minor version. It's not like it adds much value anyways, since we never add features in minor releases.

**Review by philnik777 — COMMENTED** [review]
LGTM, but I'd like @ldionne's approval as well.

**Review by ldionne — APPROVED** [review]
LGTM. I think this makes sense, since we don't introduce new features in point-releases anyway.

**Comment by h-vetinari** [comment]
Thanks for the reviews! I don't have the commit bit, so would rely on someone pushing the button. :)

**Pull request merged**
