### PR TITLE
[AMDGPU] change order of fp and sp in kernel prologue

### PR DESCRIPTION
**Pull request by cmc-rep**
change order of fp and sp in kernel prologue also related codegen tests to make it easier to merge code into our downstream branches

### CODE REVIEW

**Comment by kmitropoulou** [comment]
LGTM!

**Review by arsenm — COMMENTED** [review]
Description is misleading, this isn't just changing tests

**Comment by cmc-rep** [comment]
> Description is misleading, this isn't just changing tests

I have fixed it

**Review by arsenm — APPROVED** [review]
Description should be shortened, don't need to elaborate that this had implied test updates

**Comment by kmitropoulou** [comment]
LGTM!

**Review by kmitropoulou — APPROVED** [review]

**Pull request merged**
