### PR TITLE
[mlir] Fix bug in pack and unpack op canonicalization for folding dynamic dims

### PR DESCRIPTION
**Pull request by Max191**
This PR fixes a bug in the inference of pack and unpack static shapes that should be using an inverse permutation.

### CODE REVIEW

**Review by hanhanW — APPROVED** [review]
good catch, thanks! I probably need to fix the one for unpack

**Comment by Max191** [comment]
> good catch, thanks! I probably need to fix the one for unpack

Ah, I just realized the unpack one is there at head. I didn't check after I rebased. I can add that fix in this PR too.

**Comment by hanhanW** [comment]
> > good catch, thanks! I probably need to fix the one for unpack
> 
> Ah, I just realized the unpack one is there at head. I didn't check after I rebased. I can add that fix in this PR too.

Unpack is probably fine... but please help verify if it is fine.

**Comment by hanhanW** [comment]
> > Unpack is probably fine... but please help verify if it is fine.
> 
> It had the same bug. I double checked with the inverse of the example in [openxla/iree#16518](https://github.com/openxla/iree/issues/16518).

Can you add the case to the lit tests?

**Review by hanhanW — APPROVED** [review]
Thanks, please also update the PR title and description. Because you have fixes for unpack ops as well.

**Pull request merged**
