### PR TITLE
Revert "[ASan][libc++] Turn on ASan annotations for short strings"

### PR DESCRIPTION
**Pull request by vitalybuka**
Reverts llvm/llvm-project#75882

To recover build bots :
https://lab.llvm.org/buildbot/#/builders/239/builds/5361
https://lab.llvm.org/buildbot/#/builders/168/builds/18126

### CODE REVIEW

**Review by fmayer — APPROVED** [review]

**Comment by AdvenamTacet** [comment]
I'm going to spend next few hours on debugging it. Unfortunately, I can't run buildbots locally to debug it and test potential solutions (tried to run them as described here: https://github.com/google/sanitizers/wiki/SanitizerBotReproduceBuild but eventually I run into some issues, around end of compilation or during testing).

I'm not a fan of reverting this patch without a small example showing a problem with it, but because `Clang :: ClangScanDeps/P1689.cppm` in stage 2 asan check looks very confusing, I am ok with it.

However, @vitalybuka could you confirm before reverting short string annotations that reverting lambda optimization fix (https://github.com/llvm/llvm-project/pull/77394) does not fix that issue? Unfortunately, I can't run buildbots locally or reproduce it in any other way.

I will aslo appreciate help with running buildbots locally and creating a small example showing the issue. I will ask more on Discord as that should be easier.

**Comment by vitalybuka** [comment]
> I'm going to spend next few hours on debugging it. Unfortunately, I can't run buildbots locally to debug it and test potential solutions (tried to run them as described here: https://github.com/google/sanitizers/wiki/SanitizerBotReproduceBuild but eventually I run into some issues, around end of compilation or during testing).
> 
> I'm not a fan of reverting this patch without a small example showing a problem with it, but because `Clang :: ClangScanDeps/P1689.cppm` in stage 2 asan check looks very confusing, I am ok with it.

That's not how it work. If we don't understand the problem, we revert, and investigate later.

> 
> However, @vitalybuka could you confirm before reverting short string annotations that reverting lambda optimization fix (#77394) does not fix that issue? Unfortunately, I can't run buildbots locally or reproduce it in any other way.

It should be possible to reproduce on  GCE, using that instructions. It recreates VM using those scripts daily.
Another alternative, if you give me a pool request, from the branch in users/ of the main repo, I can schedule execution on bot directly.

> 
> I will aslo appreciate help with running buildbots locally and creating a small example showing the issue. I will ask more on Discord as that should be easier.

Sure, I will help you with debugging on bot.

**Comment by vitalybuka** [comment]
> could you confirm before reverting short string annotations that reverting lambda optimization fix (#77394) does not fix that issue

Are you asking to try #78646 ?

**Review by AdvenamTacet — APPROVED** [review]
> That's not how it work. If we don't understand the problem, we revert, and investigate later.

Ok.

**Comment by AdvenamTacet** [comment]
> Are you asking to try #78646 ?

Yes. At least https://lab.llvm.org/buildbot/#/builders/239/builds/5361 seems like it may be related to it, but that's a guess based on previous issues with it.

> Sure, I will help you with debugging on bot.

Thank you! I appreciate it!

**Review by cjdb — APPROVED** [review]

**Comment by vitalybuka** [comment]
#78646 didn't help 
https://lab.llvm.org/buildbot/#/builders/168/builds/18140/steps/10/logs/stdio

**Comment by AdvenamTacet** [comment]
@vitalybuka  Thx for checking it! Good to know that it's something else.

**Pull request merged**
