### PR TITLE
[AArch64] MI Scheduler: create more LDP/STP pairs

### PR DESCRIPTION
**Pull request by sjoerdmeijer**
Target hook `canPairLdStOpc` is missing quite a few opcodes for which
LDPs/STPs can created. I was hoping that it would not be necessary to
add these missing opcodes here and that the attached motivating test
case would be handled by the LoadStoreOptimiser (especially after
 https://github.com/llvm/llvm-project/pull/71908), but it's not. The problem is that after register allocation
some things are a lot harder to do. Consider this for the motivating example

```
[1] renamable $q1 = LDURQi renamable $x9, -16 :: (load (s128) from %ir.r51, align 8, !tbaa !0)
[2] renamable $q2 = LDURQi renamable $x0, -16 :: (load (s128) from %ir.r53, align 8, !tbaa !4)
[3] renamable $q1 = nnan ninf nsz arcp contract afn reassoc nofpexcept FMLSv2f64 killed renamable $q1(tied-def 0), killed renamable $q2, renamable $q0, implicit $fpcr
[4] STURQi killed renamable $q1, renamable $x9, -16 :: (store (s128) into %ir.r51, align 1, !tbaa !0)
[5] renamable $q1 = LDRQui renamable $x9, 0 :: (load (s128) from %ir.r.G0001_609.0, align 8, !tbaa !0)
```
We can't combine the the load in line [5] into the load on [1]: regisister q1 is
used in between. And we can can't combine [1] into [5]: it is aliasing with
the STR on line [4].

That's why I thought that adding this opcode pair here to the MI scheduler was
a good compromise.

### CODE REVIEW

**Comment by davemgreen** [comment]
I think this sounds OK to go along with the other opcodes already handled. I presume that if it got this far that benchmarks looked OK too?

Can you split the debug messages out into a separate pr. I think they look if you wanted to just push them directly, but they should probably be committed separately.

**Comment by fhahn** [comment]
> We can't combine the the load in line [5] into the load on [1]: regisister q1 is
> used in between.

Just because the register is used in between doesn't necessarily prevent AArch64LoadStoreOptimizer.cpp from combining loads/stores I think, it supports renaming registers in some cases when a different register can be picked.

**Comment by sjoerdmeijer** [comment]
> > We can't combine the the load in line [5] into the load on [1]: register q1 is
> > used in between.
> 
> Just because the register is used in between doesn't necessarily prevent AArch64LoadStoreOptimizer.cpp from combining loads/stores I think, it supports renaming registers in some cases when a different register can be picked.

Yes, exactly @fhahn , but not for this case (that's why in the description I mentioned the latest change in that area: https://github.com/llvm/llvm-project/pull/71908). This example has another def in between the pair, and that completely eliminates the pair from being candidates. Any renaming is considered only when this requirement of no writes in between between has been satisfied here:

https://github.com/llvm/llvm-project/blob/9e5a77f252badfc932d1e28ee998746072ddc33f/llvm/lib/Target/AArch64/AArch64LoadStoreOptimizer.cpp#L1900

That's where renaming is considered, just above that you'll see the checks. 
The compromise that I also mentioned in the description is exactly about this: doing major surgery in this area, or just adding this case here in the MI Scheduler hook.

> I think this sounds OK to go along with the other opcodes already handled. I presume that if it got this far that benchmarks looked OK too?

@davemgreen: This has been benchmarked, yes, giving improvements. I will run some more to double check, and report back soon.

> Can you split the debug messages out into a separate pr. I think they look if you wanted to just push them directly, but they should probably be committed separately.

Yeah, sorry, that's my Github inexperience, I thought they could be separately committed, but that doesn't seem to be case (they need to be squashed), so will separate that out.

**Comment by davemgreen** [comment]
Yeah I think there will always be a limit to what the load-store optimizer can figure out, and this is just adding a few more LDRQ<->LDURQ and LDURQ<->LDRQ pairings to what we already do.

Is it worth extending that to LDRS and LDRD to fill in the gaps?

**Comment by sjoerdmeijer** [comment]
> Yeah I think there will always be a limit to what the load-store optimizer can figure out, and this is just adding a few more LDRQ<->LDURQ and LDURQ<->LDRQ pairings to what we already do.
> 
> Is it worth extending that to LDRS and LDRD to fill in the gaps?

Yeah, I forgot to mention this. This is actually fixing a regression when we moved from the N2 to the V2 scheduling model. I wanted to test the water and fix the regression first, then follow up to handle a few more cases. Writing the other test cases is slightly tricky because to prove the point registers need to be reused; but wanted to do this in a follow up.

**Comment by sjoerdmeijer** [comment]
I have double checked SPEC INT, which is flat, nothing stands out.

**Review by davemgreen — APPROVED** [review]
LGTM then. Thanks

**Pull request merged**
