### PR TITLE
[lldb] clang-format AuxVector.h

### PR DESCRIPTION
**Pull request by DavidSpickett**
Doing this in its own commit so the intent of 2f48a1ff574573e7be170d39ab8de79d9db8bcea is clearer.

### CODE REVIEW

**Comment by DavidSpickett** [comment]
This is a stacked PR, first commit here is https://github.com/llvm/llvm-project/pull/84147.

**Review by emaste — COMMENTED** [review]
It looks like the commit messages and content are mismatched - the commit message references AT_HWCAP2 but it doesn't look like that's included here?

**Comment by DavidSpickett** [comment]
Yes that's because I corrected the title in the previous PR but did not on this branch. I've landed that previous PR and updated this so it's only the formatting change now.

**Comment by DavidSpickett** [comment]
Going to merge this without approval now that it's a simple clang-format.

**Pull request merged**
