### PR TITLE
[APInt] Implement average functions without sign/zero-extension. NFC.

### PR DESCRIPTION
**Pull request by jayfoad**
Removing the extension to FullWidth should make them much more efficient
in the 64-bit case, because 65-bit APInts use a separate allocation for
their bits.

### CODE REVIEW

**Comment by jayfoad** [comment]
+ @Atousa (for some reason I cannot add you as a reviewer).

**Comment by RKSimon** [comment]
> * @Atousa (for some reason I cannot add you as a reviewer).

Only people with commit access can be tagged as a reviewer (and can accept PRs) - but comments on the patch are still encouraged

**Comment by Atousa** [comment]
> > * @Atousa (for some reason I cannot add you as a reviewer).
> 
> Only people with commit access can be tagged as a reviewer (and can accept PRs) - but comments on the patch are still encouraged

@RKSimon Not sure if I have commit access or not yet?

**Review by kuhar — COMMENTED** [review]
Nice

**Review by RKSimon — APPROVED** [review]
LGTM - cheers

**Pull request merged**
