### PR TITLE
Implement acos operator in MLIR Math Dialect

### PR DESCRIPTION
**Pull request by frederik-h**
Required for torch-mlir.
Cf. llvm/torch-mlir#2604 "Implement torch.aten.acos".

### CODE REVIEW

**Comment by vivekkhandelwal1** [comment]
I think the implementation for `acos` op is missing from your PR. Refer to `atan` op and see what more you need to do.

**Comment by vivekkhandelwal1** [comment]
> @stellaraccident @vivekkhandelwal1 Could you review this small PR or recommend someone who could do it?

I don't have the right to do so.

**Review by stellaraccident — APPROVED** [review]
Looks reasonable to me. Thanks.

**Comment by frederik-h** [comment]
> Looks reasonable to me. Thanks.

Thank you!

**Pull request merged**
