### PR TITLE
[-Wunsafe-buffer-usage] Fix false negatives of missing 2-param span ctors in constructor initializers

### PR DESCRIPTION
**Pull request by ziqingluo-90**
The analysis now searches for every descendant stmt of constructor initializers and recurses if the descendant is another constructor call.

(rdar://137999201)

### CODE REVIEW

**Comment by ziqingluo-90** [comment]
Worth to mention that there could be "false positives" introduced to those std::span calls in C'tor initializers because the safe-pattern matching is syntactic only,  which doesn't know there can be "call stacks" involved in those recursive cases.

**Comment by haoNoQ** [comment]
This overlaps with #91991 which should probably be landed in its entirety. (It looks like it's about attributes but in fact it isn't. It's about finding *all* gadgets in all those new places.) I think that patch was almost ready and it was a matter of considering my fix in https://github.com/llvm/llvm-project/pull/91991#discussion_r1643433741

**Comment by ziqingluo-90** [comment]
> This overlaps with #91991 which should probably be landed in its entirety. (It looks like it's about attributes but in fact it isn't. It's about finding _all_ gadgets in all those new places.) I think that patch was almost ready and it was a matter of considering my fix in [#91991 (comment)](https://github.com/llvm/llvm-project/pull/91991#discussion_r1643433741)

yeah, you are right.  Let's hang out in that PR then.

**Comment by ziqingluo-90** [comment]
> > This overlaps with #91991 which should probably be landed in its entirety. (It looks like it's about attributes but in fact it isn't. It's about finding _all_ gadgets in all those new places.) I think that patch was almost ready and it was a matter of considering my fix in [#91991 (comment)](https://github.com/llvm/llvm-project/pull/91991#discussion_r1643433741)
> 
> yeah, you are right. Let's hang out in that PR then.

https://github.com/llvm/llvm-project/pull/91991 merged. Closing this PR.

**Pull request closed without merging**
