### PR TITLE
[libc++] Use a different smart ptr type alias

### PR DESCRIPTION
**Pull request by androm3da**
The `_SP` type is used by some C libraries and this alias could conflict with it.

### CODE REVIEW

**Comment by androm3da** [comment]
`_SP` is a preprocessor define in dinkumware libc's `ctype.h`.  It might be nice to change this recently-introduced alias to avoid collisions when building libc++.

cc @H-G-Hristov

**Review by mordante — CHANGES_REQUESTED** [review]
Thanks for looking into this!

Can you update the test `libcxx/test/libcxx/system_reserved_names.gen.py` with these `ctype.h` macros? That avoids us to use these names in the future.

**Comment by androm3da** [comment]
> Thanks for looking into this!
> 
> Can you update the test `libcxx/test/libcxx/system_reserved_names.gen.py` with these `ctype.h` macros? That avoids us to use these names in the future.

done

**Comment by Zingam** [comment]
> `_SP` is a preprocessor define in dinkumware libc's `ctype.h`. It might be nice to change this recently-introduced alias to avoid collisions when building libc++.
> 
> e.g. here is someone's copy of this C library: https://github.com/wuzhouhui/c_standard_lib/blob/e11548ad943686d303f0029d71ac2526d8b39cc5/_HEADERS/CTYPE.H#L12
> 
> cc @H-G-Hristov

Thank you! LGTM. This should be cherrypicked into LLVM too.

**Review by mordante — APPROVED** [review]
Thanks LGTM!

**Comment by androm3da** [comment]
> Failed to cherry-pick: https://github.com/llvm/llvm-project/commit/baa72c405cce62ac904dc504c4c32121ea59ac28

whoops wrong SHA.  I will fix it.

**Pull request merged**
