### PR TITLE
Fix what seems to be a silly bug in gpu.set_default_device rewriting. Smoke test included.

### PR DESCRIPTION
**Pull request by pcf000**

### CODE REVIEW

**Comment by pcf000** [comment]
@krzysz00

**Comment by joker-eph** [comment]
Thanks for the fix.
Can you provide a unit test for this?

also I’d look for a more descriptive title (and description)

**Review by joker-eph — APPROVED** [review]

**Comment by joker-eph** [comment]
@krzysz00 : I mentioned the need for fixing the title and description before merging, did you miss this?

**Comment by krzysz00** [comment]
@joker-eph Yeah, I did miss this, I just got pinged with an "it's been approved and you've got write access, can you merge"?

**Comment by pcf000** [comment]
I did fix them with a !amend commit, as the documentation seemed to tell me:  the squash-and-merge was supposed to recognise that and update title and description.

**Pull request merged**
