### PR TITLE
[libclc] Convert tabs to spaces in CMake

### PR DESCRIPTION
**Pull request by frasercrmck**
Having a mix of tabs and spaces makes the diff of any changes to the build system noisier than necessary. This commit unifies them to two spaces.

This includes some minor cosmetic changes such as with joining things on one line where appropriate.

There are other files in libclc which have tabs but those haven't been touched at this time. Those could come at another time if desired, though they might be more contentious as the project isn't clang-formatted at all and so that might invite larger discussions around formatting.

### CODE REVIEW

**Comment by frasercrmck** [comment]
@tstellar are you the code owner for `libclc`?

**Comment by frasercrmck** [comment]
FWIW I don't think the build bots are actually building `libclc`.

Locally, at least, it's not sufficient to specify `LLVM_ENABLE_PROJECTS=libclc` - you _also_ need `LLVM_EXTERNAL_PROJECTS=libclc`. Even then, it doesn't build for me in-tree, because it assumes `CMAKE_SOURCE_DIR` is its own top-level directory, which it isn't as it's `llvm/`.

I had a patch locally to switch `CMAKE_SOURCE_DIR` to `PROJECT_SOURCE_DIR` which I think is sufficient to cover both build styles. Should I contribute this upstream?

Another problem is that all `libclc` targets are enabled by default, but the `spirv-mesa3d` and `spirv64-mesa3d` targets both need `llvm-spirv` which I doubt our buildbots have available. Should those be disabled by default, or should the buildbots disable them?

**Review by tstellar — APPROVED** [review]

**Comment by tstellar** [comment]
> FWIW I don't think the build bots are actually building `libclc`.
> 
> Locally, at least, it's not sufficient to specify `LLVM_ENABLE_PROJECTS=libclc` - you _also_ need `LLVM_EXTERNAL_PROJECTS=libclc`. Even then, it doesn't build for me in-tree, because it assumes `CMAKE_SOURCE_DIR` is its own top-level directory, which it isn't as it's `llvm/`.
> 
> I had a patch locally to switch `CMAKE_SOURCE_DIR` to `PROJECT_SOURCE_DIR` which I think is sufficient to cover both build styles. Should I contribute this upstream?
> 
> Another problem is that all `libclc` targets are enabled by default, but the `spirv-mesa3d` and `spirv64-mesa3d` targets both need `llvm-spirv` which I doubt our buildbots have available. Should those be disabled by default, or should the buildbots disable them?

I'm not aware of any bots building libclc.  It would be nice if you could build libclc more easily, it does not fit in with the rest of the projects right now.  Any improvements you want to make in this area would be welcome.

**Comment by frasercrmck** [comment]
> > FWIW I don't think the build bots are actually building `libclc`.
> > Locally, at least, it's not sufficient to specify `LLVM_ENABLE_PROJECTS=libclc` - you _also_ need `LLVM_EXTERNAL_PROJECTS=libclc`. Even then, it doesn't build for me in-tree, because it assumes `CMAKE_SOURCE_DIR` is its own top-level directory, which it isn't as it's `llvm/`.
> > I had a patch locally to switch `CMAKE_SOURCE_DIR` to `PROJECT_SOURCE_DIR` which I think is sufficient to cover both build styles. Should I contribute this upstream?
> > Another problem is that all `libclc` targets are enabled by default, but the `spirv-mesa3d` and `spirv64-mesa3d` targets both need `llvm-spirv` which I doubt our buildbots have available. Should those be disabled by default, or should the buildbots disable them?
> 
> I'm not aware of any bots building libclc. It would be nice if you could build libclc more easily, it does not fit in with the rest of the projects right now. Any improvements you want to make in this area would be welcome.

Ah, yeah that's possible. I mentioned it because https://github.com/llvm/llvm-project/blob/main/.github/workflows/libclc-tests.yml and  https://buildkite.com/llvm-project/github-pull-requests/builds/48183#018e5157-23d0-4c70-b8bc-54bbdceabb6c look like they're ostensibly trying to build it, but aren't.

I'll see what I can do to improve the situation. We're mostly working with libclc downstream in DPC++ and it's been changed quite significantly, so it's a bit delicate to get the balance right.

**Pull request merged**
