### PR TITLE
AMDGPU: Duplicate instead of COPY constants from VGPR to SGPR

### PR DESCRIPTION
**Pull request by rovka**
Teach the si-fix-sgpr-copies pass to deal with REG_SEQUENCE, PHI or
INSERT_SUBREG where the result is an SGPR, but some of the inputs are
constants materialized into VGPRs. This may happen in cases where for
instance several instructions use an immediate zero and SelectionDAG
chooses to put it in a VGPR to satisfy all of them. This however causes
the si-fix-sgpr-copies to try to switch the whole chain to VGPR and may
lead to illegal VGPR-to-SGPR copies. Rematerializing the constant into
an SGPR fixes the issue.

### CODE REVIEW

**Review by Sisyph — APPROVED** [review]
LGTM except for the commit title nit. The title seems accurate, but slightly misleading because we  duplicate the constants into SGPRs instead of COPY them.

**Comment by jplehr** [comment]
It appears that this change made the AMDGPU OpenMP buildbot unhappy
https://lab.llvm.org/buildbot/#/builders/193/builds/39050

**Comment by rovka** [comment]
@jplehr Thanks for pointing that out. I tried reproducing the failure locally (Ubuntu 22.04 running on AMD hardware) but couldn't manage to run the tests for amdgcn-amd-amdhsa, although the AMDGPU target is in LLVM_TARGETS_TO_BUILD. I'm assuming this is because I'm missing some packages but I couldn't figure out which. Do I need to install a full ROCm for this to work? Alternatively, could you or someone else get me an IR reproducer from the buildbot or a similar machine?

**Comment by jplehr** [comment]
Sure, I'll look into it later today and get back to you.

**Pull request merged**
