### PR TITLE
[NFC] Fix #106873 - update assignment tracking docs

### LINKED ISSUE #106873: Update debug info assignment tracking docs with current status
I noticed that the [assignment tracking docs](https://llvm.org/docs/AssignmentTracking.html) still say...

> Experimental work in progress. Enabling is strongly advised against except for development and testing.

...even though it's been enabled by default since https://github.com/llvm/llvm-project/commit/de6da6ad55d3ca945195d1cb109cb8efdf40a52a (2023-06 / LLVM 17).

@OCHyams, it would be great to update this with the correct current status, and also update the TODO list at the bottom where appropriate.

### PR DESCRIPTION
**Pull request by OCHyams**

### CODE REVIEW

**Review by jryans — COMMENTED** [review]
Thanks for working on this!

The TODO list still says it's an "experimental work in progress", which reads a bit strangely for something that's now enabled by default. Perhaps reword that bit as well?

I assume the rest of the TODO list is still valid, since you haven't removed any items here...?

**Comment by OCHyams** [comment]
> The TODO list still says it's an "experimental work in progress", which reads a bit strangely for something that's now enabled by default. Perhaps reword that bit as well?

Agreed, done

> I assume the rest of the TODO list is still valid, since you haven't removed any items here...?

Unfortunately so. Actually, while we're here I've added an item.

**Review by jmorse — APPROVED** [review]
LGTM as a status update; IIRC we didn't turn it on everywhere due to the performance implications in LTO? Now that we've radically changed the storage for variable debug-info, perhaps that's now something we can revisit.

**Review by jryans — APPROVED** [review]
Thanks, looks good to me as well! 😄

**Pull request merged**
