### PR TITLE
[AMDGPU][RFC] Combine asm and disasm tests.

### PR DESCRIPTION
**Pull request by kosarev**
Eliminates the need to replicate the same instructions in MC and MC/Disassembler tests and synchronize changes in them. Also highlights differences between disassembled, reassembled and original instructions.

### CODE REVIEW

**Comment by jayfoad** [comment]
I like the general idea. We will always need some separate disassembler tests to check how the disassembler handles byte sequences that the assembler never generates (e.g. invalid encodings).

Instead of teaching the disassembler to extract hex bytes from `encoding: [...]`, I think I'd prefer creating a new assembler option `-filetype=hex` (subject to bikeshedding) that would produce output in the form that the disassembler expects:
```
$ llvm-mc -filetype=hex ...
0x01,0x02,0x03,0x04
$ llvm-mc -filetype=hex ... | llvm-mv -disassemble
...
```

One more thing we could check is a form of round tripping. If you assemble an instruction to an encoding, then disassembling+assembling that encoding should round-trip perfectly. I.e. `asm file.s` should produce identical output to `asm file.s | dis | asm`.

The converse should probably be true, i.e. `dis file.txt` should produce identical output to `dis file.txt | asm | dis`.

**Comment by arsenm** [comment]
> In general our dis tests are 99% roundtrip in their intent, except when we test 'do not care bits'.

We also don't roundtrip correctly in the case of sub-optimal constant encodings (i.e. emitting inline constants as literals)

**Comment by kosarev** [comment]
> Instead of teaching the disassembler to extract hex bytes from `encoding: [...]`, I think I'd prefer creating a new assembler option `-filetype=hex` (subject to bikeshedding) that would produce output in the form that the disassembler expects:
ould produce identical output to `dis file.txt | asm | dis`.

Tried that in https://github.com/llvm/llvm-project/pull/90214.

**Comment by MaskRay** [comment]
> I like the general idea. We will always need some separate disassembler tests to check how the disassembler handles byte sequences that the assembler never generates (e.g. invalid encodings).
> 
> Instead of teaching the disassembler to extract hex bytes from `encoding: [...]`, I think I'd prefer creating a new assembler option `-filetype=hex` (subject to bikeshedding) that would produce output in the form that the disassembler expects:
> 
> ```
> $ llvm-mc -filetype=hex file.s
> 0x01,0x02,0x03,0x04
> $ llvm-mc -filetype=hex file.s | llvm-mv -disassemble
> ...
> ```
> 
> One more thing we could check is a form of round tripping. If you assemble an instruction to an encoding, then disassembling+assembling that encoding should round-trip perfectly. I.e. `asm file.s` should produce identical output to `asm file.s | dis | asm`.
> 
> The converse should probably be true, i.e. `dis file.txt` should produce identical output to `dis file.txt | asm | dis`.

I see that @kosarev created #90214 for evaluation. As someone who has worked a lot on MC, I'd hope that we do not lightly introduce another `MCStreamer` derivative whose purpose is only for testing.

`llvm-mc -filetype=obj ... | llvm-objdump -d ` is possibly a good choice for this functionality. I am also not sure about hard encoding `encoding: ` in llvm-mc -disassemble.

**Comment by kosarev** [comment]
@MaskRay Answered in https://github.com/llvm/llvm-project/pull/90214#issuecomment-2084888806.

**Comment by kosarev** [comment]
Abandoning this in favour of https://github.com/llvm/llvm-project/pull/92895.

**Pull request closed without merging**
