### PR TITLE
[ASan][libc++] Optimize `__annotate_delete` for the default allocator

### PR DESCRIPTION
**Pull request by AdvenamTacet**
This commit optimizes the ASan helper functions `__annotate_delete()`, in `std::basic_string`, `std::vector` and `std::deque`, by adding `if` statements to prevent unpoisoning of memory for the default allocator. Unpoisoning is not required by the default allocator, and since it is widely used, this optimization should yield a meaningful performance improvement.

The optimization was suggested by @EricWF.

### CODE REVIEW

**Review by philnik777 — CHANGES_REQUESTED** [review]
How much of a performance improvement is that in reality?

**Comment by AdvenamTacet** [comment]
When a container's buffer contains N bytes, a pessimistic estimation is that N/8 bytes will be written into shadow memory. In the worst-case scenario, this can double the run-time of ASan operations during deallocation. If the buffer is large and there are many deallocations, this performance impact could be noticeable.

While the performance gain is small in the grand scheme of things, it is still a gain that we are leaving on the table. However, if you believe that adding an additional line with an if statement in an ASan helper functions is too high a price to pay for that performance gain, I understand, but disagree.

Real values depend on the container and its state.
For vector, that may be accurate estimation instead of a pessimistic one, due to [a clear just before destruction](https://github.com/llvm/llvm-project/blob/main/libcxx/include/vector#L490-L491).

**Comment by philnik777** [comment]
@AdvenamTacet I don't necessarily think that this isn't worth the cost. I'd simply like to see some numbers. If this is a 1% perf improvement in a micro-benchmark, I don't think this is worth it. If it's a 10x improvement, it probably is worth the cost.

**Comment by AdvenamTacet** [comment]
I just ran a small benchmark with flags `-stdlib=libc++ -fsanitize=address -O3`.

```cpp
#ifdef VECTOR_FAST
#include "vector-optimized.hpp"
#endif

#ifdef VECTOR_MAIN
#include "vector-main.hpp"
#endif

int main() {
    uint32_t sum = 0;
    for(uint32_t i = 2; i < 100'000; ++i) {
        std::vector<uint64_t> v(1'000'000, i);
        sum += v[i/2];
        v.clear();
    }

    return sum != 0 ? 0 : -1;
}
```

Example results (quite representative):
```bash
# Optimized times:
real    3m6.008s
user    0m25.815s
sys     2m39.491s


# Times from upstream mian:
real    3m32.434s
user    0m27.063s
sys     3m4.495s
```

It gives around 13% of speedup on that benchmark.
```python
In [1]: 1 - (3*60+3.008) / (3*60+32.434)
Out[1]: 0.13851831627705535
```

I don't see many potential issues, maybe problems after replacing default allocator with some problematic allocator?
It only affects strictly ASan related functions, so readability is arguably untouched.
Performance is consistently better.

What do you think?

**Comment by philnik777** [comment]
While the numbers looks nice, I'm not sure it's good enough in the current state. I think I'd be much happier with this if we could canonicalize the interface for all the containers, at least to some degree. That way we should be able to apply these kinds of optimizations in a single place instead of spreading them across the code base.

**Comment by AdvenamTacet** [comment]
I see your point, but I'm not sure an interface is feasible option.
We would end up adding a lot of code in another place, but removing very little of code here. `basic_string` and `vector` have very similar implementations of annotations, but inside `basic_string` we have to additionally take care of a null terminator (not included in `size()` or `capacity()`). Therefore, the only function we can unify in the interface is `__annotate_contiguous_container` (but then `__beg` and `__end` have to be arguments to it) and possibly we can move some checks (like the one included in this PR). But the rest has to be handled separately. `deque` is so different, that we need a separate interface.

Possibly we can just move those functions to another class/file (but keep separate implementations for every class).
We would have to do it in a way that optimizations are not affected in any way to keep current performance.
I don't see a way to do it, without increasing complexity.

I don't really like an idea of an interface for ASan annotations.

@EricWF @ldionne what do you think?

**Comment by ldionne** [comment]
I'm a bit skeptical of the benefits of doing this optimization in a real code base, keeping in mind that this is under sanitized mode. My threshold of acceptable complexity for adding sanitizer support to our containers is right at its limit TBH and I would rather explore refactorings to make it simpler and less intrusive than anything that requires adding more complexity.

**Pull request closed without merging**
