### PR TITLE
[mlir][spirv] Add definitions and (de)serialization for FPRoundingMode

### PR DESCRIPTION
**Pull request by andfau-amd**

### CODE REVIEW

**Review by kuhar — COMMENTED** [review]
Should we add some negative tests for when `fp_rounding_mode` is not a `#spirv.fp_rounding_mode` attribute?

**Comment by andfau-amd** [comment]
> Should we add some negative tests for when `fp_rounding_mode` is not a `#spirv.fp_rounding_mode` attribute?

Hmm, I'm not sure if it's an important enough case to test. The code that rejects it is very straightforward, I couldn't find any negative tests for similar attributes, and it doesn't seem that likely to me that someone would generate invalid MLIR like that anyway.

One observation I have there is that this is, effectively, validated by the serializer rather than a proper verifier method. I'm not sure if that's good, but it is what the other attributes do too, so...

**Comment by kuhar** [comment]
OK, that makes sense then.

**Review by kuhar — APPROVED** [review]
LGTM

**Pull request merged**
