### PR TITLE
Mark some std::string functions noinline.

### PR DESCRIPTION
**Pull request by jyknight**
The intent of these particular functions, since their introduction, was to NOT be inlinable.

However, the mechanism by which this was accomplished was non-obvious, and stopped working when string is compiled for C++20.

A longstanding behavior specified by the C++ standard is that instantiation of the body of a template function is suppressed by an extern template declaration -- unless the function is explicitly marked either constexpr or inline. Of course, if the body is not instantiated, then it cannot possibly be inlined, and thus all the functions listed in libcxx/include/__string/extern_template_lists.h were uninlineable.

But, in C++20 mode, string functions were annotated constexpr, which means they _are_ instantiated, and do become inlineable. And, in fact, they do get inlined, which has caused noticeable binary-size growth for users.

For example, in C++17,
`std::string f(std::string *in) { return *in; }`
does not inline the copy-constructor call, and instead generates a call to the exported function defined in the libc++ shared library.

I think we probably don't want to mark all functions that are currently in the extern template list as noinline, as many of them really are reasonable inlining candidates. Thus, I've restricted this change to only the few functions that were clearly intended to be outlined.

See commits like b019c5c0372eb08800327efb5e7955ce918b75d1 (and some others like it) for background, in which functions were removed from the extern template list in the unstable ABI in order to allow the short-string case to be inlined, while moving the long-string case to a separate function, added to the extern template list.

### CODE REVIEW

**Review by ldionne — APPROVED** [review]
This makes sense to me. I hate introducing `_LIBCPP_NOINLINE`, but in this case the intent of these functions is pretty clear and allowing them to be inlined was an unintended side effect of adding `constexpr`.

**Comment by EricWF** [comment]
The project has had a checked past with `_LIBCPP_ALWAYS_INLINE` and `_LIBCPP_NOINLINE` coming and going. I'm afraid this is the start to another one of those cycles.

For future readers of the code, I would like to leave more of a trace exactly _why_ we're doing this, and when it should and shouldn't be used to solve other problems.

**Comment by jyknight** [comment]
Can you give a suggestion as to where you'd like to see it, or what else you'd like to see? I tried to make the commit message extra-descriptive already, for just that reason.

**Review by ldionne — APPROVED** [review]
IMO this is reasonable, especially when coupled with the commit message. I would like to avoid holding this patch off without requiring actionable changes.

**Comment by jyknight** [comment]
Seeing no further feedback, going ahead and submitting.

**Pull request merged**
