### PR TITLE
[TwoAddressInstruction] Handle physical registers with LiveIntervals

### PR DESCRIPTION
**Pull request by jayfoad**
Teach the LiveIntervals path in isPlainlyKilled to handle physical
registers, to get equivalent functionality with the LiveVariables path.

Test this by adding -early-live-intervals RUN lines to a handful of
tests that would fail without this.

### CODE REVIEW

**Comment by jayfoad** [comment]
Ping!

**Review by perlfu — APPROVED** [review]
LGTM - but should probably have a second opinion

**Comment by RKSimon** [comment]
@jayfoad Please can you rebase this?

**Review by RKSimon — APPROVED** [review]
LGTM - cheers

**Pull request merged**
