### PR TITLE
[Support] Add decodeULEB128AndInc/decodeSLEB128AndInc

### PR DESCRIPTION
**Pull request by MaskRay**
Many decodeULEB128/decodeSLEB128 users need to increment the pointer.
Add helpers to simplify this common pattern. We don't add `end` and
`error` parameters at present because many users don't need them.

### CODE REVIEW

**Review by adrian-prantl — APPROVED** [review]
I've been toying with the idea of moving the decoder function into the .cpp file, and maybe having two entry points for error / no errors to further speed up decoding, and this seems to get us closer to that goal.

**Comment by dwblaikie** [comment]
The lack of error handling and bounds checking in these versions seems a bit problematic? (like, I'm not sure they can be used safely/correctly?)

**Comment by adrian-prantl** [comment]
I was _assuming_ that the code that uses these functions does a bounds safety check for the entire section. @MaskRay ?

**Comment by MaskRay** [comment]
The tablegen use case guarantees that there is no error. The `Shift>63` check is pure overhead.
Use cases that require rigid error checking can probably use `llvm/include/llvm/Support/DataExtractor.h` `getULEB128`, but the overhead would be substantial.
At any rate, the error parameters could be added to `*AndInc` but I have found a good use case yet.

For efficient ULEB128 for the primary use cases (debug info, etc), perhaps we should unroll the first iteration.

**Comment by dwblaikie** [comment]
> The tablegen use case guarantees that there is no error. The `Shift>63` check is pure overhead. Use cases that require rigid error checking can probably use `llvm/include/llvm/Support/DataExtractor.h` `getULEB128`, but the overhead would be substantial. At any rate, the error parameters could be added to `*AndInc` but I have found a good use case yet.


> I was _assuming_ that the code that uses these functions does a bounds safety check for the entire section. @MaskRay ?

But it's not possible to bounds check ULEB reading, right? Non-canonical ULEBs can be arbitrarily long (null padding) - so no untrusted/input buffer can be sure not to buffer overrun, I think? (looking at the implementation of decodeULEB128 - if `Slice` is zero, but the high bit is set, you keep reading the uleb, potentially overrunning any finite buffer)

So this is only safe to call on buffers with known contents? Which is special cases like tblgen, where the buffer is baked into the binary. Anything reading a uleb from unknown input could not use this API correctly.

I'd think it'd be best to  always require error checking, despite the few cases where that's unnecessary. 

Looks to me like a lot of the callers of the previous/existing/underlying API are unsafe. Tblgen's safety seems like it'd be in the minority of callers.

**Comment by MaskRay** [comment]
I agree that some LEB128 uses do pay less attention about potential buffer overrun.

Like the one mentioned in https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=SECURITY.txt 

> Compiling untrusted sources can result in arbitrary code execution and unconstrained resource consumption in the compiler. As a result, compilation of such code should be done inside a sandboxed environment to ensure that it does not compromise the host environment.

Many of LLVM tools might prioritize efficiency over bounds checking (E.g. I believe that in a lot of llvm/lib/Object/ places do not check the bounds.)
We might not have the bandwidth to address every potential LEB128 decode call site with explicit `end` arguments or by switching entirely to `DataExtractor`.

**Comment by dwblaikie** [comment]
> I agree that some LEB128 uses do pay less attention about potential buffer overrun.
> 
> Like the one mentioned in https://gcc.gnu.org/git/?p=gcc.git;a=blob;f=SECURITY.txt
> 
> > Compiling untrusted sources can result in arbitrary code execution and unconstrained resource consumption in the compiler. As a result, compilation of such code should be done inside a sandboxed environment to ensure that it does not compromise the host environment.
> 
> Many of LLVM tools might prioritize efficiency over bounds checking (E.g. I believe that in a lot of llvm/lib/Object/ places do not check the bounds.) 

I don't think that's what they're doing - my understanding from the Apple folks (& part of the reason @lhames invented the `llvm::Error` stuff) is that they're quite interested in having, and have invested in it quite a bit, libObject being robust to corrupted/arbitrary inputs - for better investigation into problematic object files.

If they lack bounds checking it's because they were written pretty casually to begin with - which is often the case, and unfortunate (I can say the LLVM debug info APIs are similarly pretty casual). Not out of a performance concern (performance without correctness is... not usually what anyone wants) but just because folks weren't thinking about/prioritizing bad input robustness.

> We might not have the bandwidth to address every potential LEB128 decode call site with explicit `end` arguments or by switching entirely to `DataExtractor`.

I'm not suggesting we can/will/should prioritize paying down all the places we would crash on untrusted input - I think we might've done something differently if we'd thought about it from day 1 (adding fuzzers, etc) - much easier/cheaper to do on new code than to justify the cost of doing the cleanup after the fact.

But that's why I'm concerned about creating APIs that are hard to use safely. The previous/existing APIs that provide optional bounds checking are already pretty easy to misuse (they don't really push folks to being careful with these things). I think it's important to lower the cost of writing bounds safe code - and having APIs that don't provide a way to do it safely seems higher cost, because someone might reach for it & see no error handling and decide it's not worth it.

(this API feels close to `gets` (which, admittedly, is maximally unsafe - you can't control its input - but that's /usually/ the case with most of these uleb readings - except these sort of special cases where the input is built into the code/file, like tblgen))

**Comment by adrian-prantl** [comment]
> have invested in it quite a bit, libObject being robust to corrupted/arbitrary inputs

That is very true. In fact we're adopting libObject more and more in LLDB and LLDB needs to be really resilient against invalid input, since it's very easy to get into a situation where it needs to parse information out of corrupted memory.

**Comment by adrian-prantl** [comment]
> (this API feels close to gets (which, admittedly, is maximally unsafe - you can't control its input - but that's /usually/ the case with most of these uleb readings - except these sort of special cases where the input is built into the code/file, like tblgen))

This API will read at most 9 bytes out of bounds, but evidently any byte out of bounds is one too many. When I reviewed the original patch I was under the assumption that users of this API would check for the bounds in their outer parse loop, but maybe we're not saving a ton of performance by omitting the bounds check here.

**Comment by dwblaikie** [comment]
> > (this API feels close to gets (which, admittedly, is maximally unsafe - you can't control its input - but that's /usually/ the case with most of these uleb readings - except these sort of special cases where the input is built into the code/file, like tblgen))
> 
> This API will read at most 9 bytes out of bounds, but evidently any byte out of bounds is one too many. When I reviewed the original patch I was under the assumption that users of this API would check for the bounds in their outer parse loop, but maybe we're not saving a ton of performance by omitting the bounds check here.

Will it? If the ULEB is non-canonical, I thought it could read arbitrarily out of bounds? How's the 9 byte limit manifest?

**Comment by adrian-prantl** [comment]
https://github.com/llvm/llvm-project/blob/a1a8bb1d3ae9a535526aba9514e87f76e2d040fa/llvm/include/llvm/Support/LEB128.h#L131

It stops if the decoded value doesn't fit into a uint64_t, which I think is 9 bytes in the worst case. Maybe 10?

**Comment by adrian-prantl** [comment]
>  If the ULEB is non-canonical,

Ah. Sorry, that is a good point!

**Comment by dwblaikie** [comment]
@MaskRay I think the basic request/requirement here should be that these new APIs be no worse at error handling than the ones they're wrapping: Please add the extra optional error reporting parameters.

Ideally, imo, we should be making error handling more explicit/non-optional than these APIs are. Ideally new APIs (including these wrappers) would include non-optional error handling (Error/Expected returning)

**Comment by MaskRay** [comment]
Sorry, just saw the discussion. Added #90006

(I believe removing default arguments isn't a lot useful as users can always use the existing decodeULEB128 with default arguments)

**Comment by dwblaikie** [comment]
> (I believe removing default arguments isn't a lot useful as users can always use the existing decodeULEB128 with default arguments)

*nod* I understand. My concern is that this adds friction to users doing error checking-makes it easier to reach for an API that not only doesn't encourage it (the original API) but doesn't allow it - meaning the author has to choose between a more convenient API, and maybe doing error checking - this seems like it'd discourage error checking, which would be unfortunate.

**Pull request merged**
