### PR TITLE
[SandboxIR][NFC] Delete SandboxIR.h

### PR DESCRIPTION
**Pull request by vporpo**

### CODE REVIEW

**Review by Sterling-Augustine — APPROVED** [review]

**Comment by farzonl** [comment]
I'm seeing build failures because of this change.

```
D:\project\llvm-project\llvm\include\llvm/SandboxIR/Instruction.h(1100,9): error: base class 'SingleLLVMInstructionImpl<llvm::UnaryInstruction>' has private constructor
 1100 |       : SingleLLVMInstructionImpl(ID, Opc, LLVMI, Ctx) {}
      |         ^
D:\project\llvm-project\llvm\include\llvm/SandboxIR/Instruction.h(362,3): note: implicitly declared private here
  362 |   SingleLLVMInstructionImpl(ClassID ID, Opcode Opc, llvm::Instruction *I,
      |   ^
```

**Comment by vporpo** [comment]
> I'm seeing build failures because of this change.

What platform is it ?

**Comment by vporpo** [comment]
I think I know what the issue is, let me push a fix.

**Comment by vporpo** [comment]
Reverted: 8dfeb4ef5d60a5c764f0ce249cc4ec69e012ff93 due to MSVC build failures.

**Comment by farzonl** [comment]
Not sure what you changed between the Revert and the ReApply. but things are building now. I am seeing the following warnings though:

```
D:\project\llvm-project\llvm\include\llvm/SandboxIR/Value.h(139,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
  139 |   friend class CmpInst;               // For getting `Val`.
      |                ^
      |                ::llvm::
1 warning generated.
[32/3645] Building CXX object lib\Transforms\Vectorize\CMa...LVMVectorize.dir\SandboxVectorizer\DependencyGraph.cpp.obj
In file included from D:\project\llvm-project\llvm\lib\Transforms\Vectorize\SandboxVectorizer\DependencyGraph.cpp:9:
In file included from D:\project\llvm-project\llvm\include\llvm/Transforms/Vectorize/SandboxVectorizer/DependencyGraph.h:27:
In file included from D:\project\llvm-project\llvm\include\llvm/SandboxIR/Instruction.h:15:
In file included from D:\project\llvm-project\llvm\include\llvm/SandboxIR/BasicBlock.h:13:
D:\project\llvm-project\llvm\include\llvm/SandboxIR/Value.h(139,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
  139 |   friend class CmpInst;               // For getting `Val`.
      |                ^
      |                ::llvm::
1 warning generated.
[34/3645] Building CXX object lib\Transforms\Vectorize\CMa...Vectorize.dir\SandboxVectorizer\Passes\BottomUpVec.cpp.obj
In file included from D:\project\llvm-project\llvm\lib\Transforms\Vectorize\SandboxVectorizer\Passes\BottomUpVec.cpp:9:
In file included from D:\project\llvm-project\llvm\include\llvm/Transforms/Vectorize/SandboxVectorizer/Passes/BottomUpVec.h:16:
In file included from D:\project\llvm-project\llvm\include\llvm/SandboxIR/Constant.h:20:
In file included from D:\project\llvm-project\llvm\include\llvm/SandboxIR/Argument.h:13:
D:\project\llvm-project\llvm\include\llvm/SandboxIR/Value.h(139,16): warning: unqualified friend declaration referring to type outside of the nearest enclosing namespace is a Microsoft extension; add a nested name specifier [-Wmicrosoft-unqualified-friend]
  139 |   friend class CmpInst;               // For getting `Val`.
      |                ^
      |                ::llvm::
1 warning generated.
```

The platform is Windows 11. The compiler is clang-cl

cmake is setup like so:
```bash
>cmake -G Ninja -B ..\release-llvm-build -S .\llvm\ -DLLVM_ENABLE_PROJECTS="llvm;clang" -DCMAKE_C_COMPILER=clang-cl.exe -DCMAKE_CXX_COMPILER=clang-cl.exe -DCMAKE_BUILD_TYPE=Release
```

**Comment by vporpo** [comment]
I added a few forward declarations within the namespace, because MSVC can't figure out the class that the friend declaration refers to.

Same here, let me push a fix that should get rid of the warnings.

**Comment by vporpo** [comment]
@farzonl This should fix the warning: 023f6910cfcbe7b3a9c405f59b3e62728617eeaf

**Pull request merged**
