### PR TITLE
[AArch64] Make +pauth enabled in Armv8.3-a by default

### PR DESCRIPTION
**Pull request by atrosinenko**
Add AEK_PAUTH to ARMV8_3A in TargetParser and let it propagate to ARMV8R, as it aligns with GCC defaults.

After adding AEK_PAUTH, several tests from TargetParserTest.cpp crashed when trying to format an error message, thus update a format string in AssertSameExtensionFlags to account for bitmask being pre-formatted as std::string.

The CHECK-PAUTH* lines in aarch64-target-features.c are updated to account for the fact that FEAT_PAUTH support and pac-ret can be enabled independently and all four combinations are possible.

### CODE REVIEW

**Comment by atrosinenko** [comment]
No-change rebase to fix merge conflicts.

**Comment by atrosinenko** [comment]
Sorry, force-pushing the rebased branch associated with the PR was a bad idea... Restored the original commit for now.

**Comment by atrosinenko** [comment]
No-change rebase to fix the merge conflict. This time shown as a single commit, as expected. I do understand that LLVM review policy suggests to only rebase right before "squash and merge", but there are no comments yet and the conflict is almost as large as the patch itself :)

**Comment by DavidSpickett** [comment]
Just for citations here, the A profile manual says:
FEAT_PAuth is mandatory in Armv8.3 implementations.

The R Profile manual says:
The Armv8-R AArch64 architecture supports FEAT_PAuth2 feature defined in Armv8-A architecture with a
modified definition of PAC field as described below...

So the overall intent is correct.

**Review by DavidSpickett — APPROVED** [review]
LGTM.

I think the reason we didn't do this is because we have so far:
* Used nop space encodings
* Used a CPU that would enable it
* Been adding -mbranch-protection and friends anyway, so adding +pauth didn't seem like a big deal.

But it's correct according to the ARMARM, so let's go ahead with this.

**Comment by atrosinenko** [comment]
@DavidSpickett Thank you for the comments! I will rebase the branch as-is to a recent version of `main` to retest it before merging.

**Comment by atrosinenko** [comment]
Merged despite buildkite failure as its "Linux x64" job succeeded and "Windows x64" failed with an unrelated error :)

```
mt.exe : general error c101008d: Failed to write the updated manifest to the resource of file "tools\mlir\unittests\ExecutionEngine\MLIRExecutionEngineTests.exe". Operation did not complete successfully because the file contains a virus or potentially unwanted software.
```

**Pull request merged**
