### PR TITLE
release/18.x: [RISCV] Re-separate unaligned scalar and vector memory features in the backend.

### PR DESCRIPTION
**Pull request by topperc**
This adds the unaligned-scalar-mem feature from 9067070d91e9d8cdd8509ffa56a076f08a3d7281 for #92134

To minimize disruption to out of tree projects, I've kept the fast-unaligned-access feature. The new feature is ORed with fast-unaligned-access for scalar code

The goal is to restore the -Xclang -target-feature -Xclang +unaligned-scalar-mem` command line that used to work on LLVM 17 before -mno-strict-align was introduced for RISC-V. I know this is not an ideal interface. We need to get the RISC-V community to work out how -mno-strict-align should work now that we have seen multiple CPUs in the wild with unaligned scalar support and no unaligned vector support. This will not happen in LLVM-18 timeline. So I just want to get us back to what worked on LLVM 17 to unblock developers who need this feature.

### CODE REVIEW

**Comment by nikic** [comment]
Note that backporting this may require changes for LLVM users (I know that it will require rustc changes at least). This may not be a good candidate for the last 18.1 point release.

**Comment by topperc** [comment]
> Note that backporting this may require changes for LLVM users (I know that it will require rustc changes at least). This may not be a good candidate for the last 18.1 point release.

Can you point me to the relevant rust code? I found this line which looks like it wasn't updated for llvm 18. https://github.com/rust-lang/rust/blob/8387315ab3c26a57a1f53a90f188f0bc88514bca/compiler/rustc_target/src/target_features.rs#L284

**Comment by topperc** [comment]
> > Note that backporting this may require changes for LLVM users (I know that it will require rustc changes at least). This may not be a good candidate for the last 18.1 point release.
> 
> Can you point me to the relevant rust code? I found this line which looks like it wasn't updated for llvm 18. https://github.com/rust-lang/rust/blob/8387315ab3c26a57a1f53a90f188f0bc88514bca/compiler/rustc_target/src/target_features.rs#L284

Or I guess that line was changed for llvm 19?

**Comment by nikic** [comment]
@topperc Yes, it has been changed back for LLVM 19. See https://github.com/rust-lang/rust/blob/8387315ab3c26a57a1f53a90f188f0bc88514bca/compiler/rustc_codegen_llvm/src/llvm_util.rs#L273-L277

**Comment by tstellar** [comment]
Should we still try to backport this?

**Comment by topperc** [comment]
Maybe I could make fast-unaligned-access only apply to scalar to avoid a name change. And give a new flag for vector?

There's not a lot of RISC-V vector hardware available yet. One of the CPUs that is available only supports unaligned scalars and not vectors.

**Comment by preames** [comment]
I don't think we need to backport this at all.  None of the in tree cpus fall into the category where the distinction is important, and I don't feel we have any obligation to backport support for our of tree forks.

**Comment by topperc** [comment]
> I don't think we need to backport this at all. None of the in tree cpus fall into the category where the distinction is important, and I don't feel we have any obligation to backport support for our of tree forks.

There's no out of tree fork involved here. The bug reporter was using stock LLVM to compile for the Kendryte K230 board. A developer from the RISE System Libraries group reported this same issue in a presentation yesterday. It is impacting their work on chromium zlib on the same K230 board. zlib does scalar unaligned accesses.

**Comment by preames** [comment]
I'm not strongly opposed to this or anything, but it feels questionable to be doing a backport to change the target-feature syntax.  My understand is that these are purely internal names.  This isn't a documented public interface.

**Comment by topperc** [comment]
> I'm not strongly opposed to this or anything, but it feels questionable to be doing a backport to change the target-feature syntax. My understand is that these are purely internal names. This isn't a documented public interface.

It isn't documented, but some users were using `-Xclang -target-feature -Xclang -unaligned-scalar-mem` with clang 17 to get this functionality. -mno-strict-align does not exist in clang 17.

I'm going to experiment with reworking this patch to make `-Xclang -target-feature -Xclang -unaligned-scalar-mem` work and also leave `fast-unaligned-access` working to cover both scalar and vector.

**Comment by tstellar** [comment]
@topperc Can this be merged as is?  There might not be time to get an updated patch merged before the last release.

**Comment by topperc** [comment]
> @topperc Can this be merged as is? There might not be time to get an updated patch merged before the last release.

I just pushed a modified patch. What is the timeline for the last release?

**Comment by tstellar** [comment]
@topperc The plan is to release Friday.  Do we have agreement on merging this updated patch?

**Review by asb — APPROVED** [review]

**Review by lukel97 — APPROVED** [review]
Chiming in that this seems reasonable to me, given the performance impact of not having unaligned scalar accesses. And hopefully we can remove this one we're settled on a proper interface.

**Comment by preames** [comment]
I'm fine with this approach.  No strong opinion either way, but definitely don't let me previous comments be blocking here.

**Comment by tstellar** [comment]
@topperc (or anyone else). If you would like to add a note about this fix in the release notes (completely optional). Please reply to this comment with a one or two sentence description of the fix.  When you are done, please add the release:note label to this PR.

**Comment by topperc** [comment]
> @topperc (or anyone else). If you would like to add a note about this fix in the release notes (completely optional). Please reply to this comment with a one or two sentence description of the fix. When you are done, please add the release:note label to this PR.

`-Xclang -target-feature -Xclang +unaligned-scalar-mem` can be used to enable unaligned scalar memory accesses for CPUs that do not support unaligned vector accesses. `-mno-strict-align` will enable unaligned scalar and vector memory accesses.

**Pull request merged**
