### PR TITLE
Add option to generate additional debug info for expression dereferencing pointer to pointers. 

### PR DESCRIPTION
**Pull request by huangjd**
This is another attempt to land #81545, which was reverted. 

Fixed test case so that it is consistent on all platforms.

### CODE REVIEW

**Review by dwblaikie — APPROVED** [review]
Looks worth a shot. Please commit this at a time where you can respond to bot fail-mail for a while after the commit.

And ensure the commit message has most/all of the details of the original commit, plus the original commit and revert hashes, and a little detail on the updates to address the reason for the revert (adding the explicit triple to the test).

**Comment by jmorse** [comment]
G'day -- we've got some tests for -O0 that, with this patch applied, generate different code with-and-without the `-g` flag, if `-fdebug-info-for-profiling` is enabled. Example godbolt: https://godbolt.org/z/qooo5Eah1 .

It seems the intention of this patch is generating additional loads and stores with debug-info enabled, which is usually highly undesirable. It's guarded by `-fdebug-info-for-profiling`, however we (Sony) use this flag in a bunch of places, and would prefer it to continue generating stable + consistent code. A couple of possibilities:
 * Put this behaviour behind a cc1 flag, I think that was the plan in the original PR?
 * Instead of creating an alloca,  store+load, and dbg.declare, connect a dbg.value to the relevant pointer Value. 

The 2nd point is more work, but it means you're only adding more debug-info, and nothing else. A dbg.value connected to the pointer Value is the inevitable consequence of the alloca+store+load idiom after mem2reg/SROA anyway.

**Comment by dwblaikie** [comment]
> G'day -- we've got some tests for -O0 that, with this patch applied, generate different code with-and-without the `-g` flag, if `-fdebug-info-for-profiling` is enabled. Example godbolt: https://godbolt.org/z/qooo5Eah1 .
> 
> It seems the intention of this patch is generating additional loads and stores with debug-info enabled, which is usually highly undesirable. 

I hope that isn't the intent, I thought the intent was just to add more debug info for loads and stores to carry more intermediate type information.

Sorry I missed that this patch does change clangs generated ir. Seriously overlooked on my part.

>  * Instead of creating an alloca,  store+load, and dbg.declare, connect a dbg.value to the relevant pointer Value. 
> 
> The 2nd point is more work, but it means you're only adding more debug-info, and nothing else. A dbg.value connected to the pointer Value is the inevitable consequence of the alloca+store+load idiom after mem2reg/SROA anyway.

Yeah, pretty sure (2) would be the preferred direction.

**Comment by huangjd** [comment]
By just specifying `-g` Even without `-fdebug-info-for-profiling` it is going to introduce debug variables as a sequence of alloca-store-load too, so is it a requirement to guarantee `-O0` output stays identical with or without debug info? 

Emitting a dbg.value was what I originally though of, but there is a IR validation pass after frontend codegen that does not permit it, not sure if there's other design reason for this check

**Comment by jmorse** [comment]
dblaikie wrote:
>  I hope that isn't the intent, I thought the intent was just [...]

Ah, by which I mean "it's not an accident",

> By just specifying -g Even without -fdebug-info-for-profiling it is going to introduce debug variables as a sequence of alloca-store-load too, so is it a requirement to guarantee -O0 output stays identical with or without debug info?

It's a strong objective of LLVM in general to ensure debug-info doesn't have an effect on codegen decisions -- it just makes everything unreliable and hard to predict. It can cause situations where an end user finds their programs behave differently with -g. Having a cc1 option to enable this kind of behaviour is fine as they're relatively experimental, for us the issue is that it's affecting an existing driver option.

> Emitting a dbg.value was what I originally though of, but there is a IR validation pass after frontend codegen that does not permit it, not sure if there's other design reason for this check

Interesting -- I'll admit I'm not especially familiar with stuff right at the front end, but I'm sure I've seen some emails go past about handling dbg.values earlier than normal. @SLTozer @OCHyams were there some Swift related patches that got SROA handling dbg.values correctly, and if so, maybe it's alright for clang to do it too? (@jmorse is still catching up with email).

**Comment by SLTozer** [comment]
Yes, to my knowledge Swift emits dbg.values out of its front end, so there's probably no reason (on the LLVM side) that clang couldn't do so as well. There might be good reasons internal to clang that it doesn't use debug values atm, and it's not inconceivable that we'd hit some cases that LLVM handles poorly at the moment (right now assignment tracking depends on reading dbg.declares, for example), but that's something that could be tackled in a separate review.

**Comment by huangjd** [comment]
Ok lets revert this first, and I will work on the dbg.value implementation

**Pull request merged**
