### PR TITLE
[mlir][LLVMIR] Add more vector predication intrinsic ops

### PR DESCRIPTION
**Pull request by jacquesguan**
This revision adds vector predication smax, smin, umax and umin intrinsic ops.

### CODE REVIEW

**Review by gysit — COMMENTED** [review]
Thanks!

Can you add import tests as well. The import tests of the existing vector intrinsics are here:
https://github.com/llvm/llvm-project/blob/fd21b7911fbdddc80db2d3971ff10ee70a49b7e3/mlir/test/Target/LLVMIR/Import/intrinsic.ll#L800C28-L800C57

**Comment by FMarno** [comment]
I think it would also be good to add them to the roundtrip test: https://github.com/FMarno/llvm-project/blob/main/mlir/test/Dialect/LLVMIR/roundtrip.mlir

**Comment by jacquesguan** [comment]
> Thanks!
> 
> Can you add import tests as well. The import tests of the existing vector intrinsics are here: https://github.com/llvm/llvm-project/blob/fd21b7911fbdddc80db2d3971ff10ee70a49b7e3/mlir/test/Target/LLVMIR/Import/intrinsic.ll#L800C28-L800C57

Tests added.

**Comment by jacquesguan** [comment]
> I think it would also be good to add them to the roundtrip test: https://github.com/FMarno/llvm-project/blob/main/mlir/test/Dialect/LLVMIR/roundtrip.mlir

Tests added.

**Review by FMarno — APPROVED** [review]
LGTM

**Review by zero9178 — APPROVED** [review]

**Review by gysit — APPROVED** [review]
LGTM!

**Pull request merged**
