### PR TITLE
[libc] Clean up alternate test framework support

### PR DESCRIPTION
**Pull request by frobtech**
This replaces the old macros LIBC_COPT_TEST_USE_FUCHSIA and
LIBC_COPT_TEST_USE_PIGWEED with LIBC_COPT_TEST_ZXTEST and
LIBC_COPT_TEST_GTEST, respectively.  These are really not about
whether the code is in the Fuchsia build or in the Pigweed build,
but just about what test framework is being used.  The gtest
framework can be used in many contexts, and the zxtest framework
is not always what's used in the Fuchsia build.

The test/UnitTest/Test.h wrapper header now provides the macro
LIBC_TEST_HAS_MATCHERS() for use in `#if` conditionals on use of
gmock-style matchers, replacing `#if` conditionals that test the
framework selection macros directly.

### CODE REVIEW

**Comment by frobtech** [comment]
> Mind updating the PR description? Not sure what happened there.

`gh pr create --fill` did it when it was supposed to use the text from git.  I hate github.

**Comment by jhuber6** [comment]
> > Mind updating the PR description? Not sure what happened there.
> 
> `gh pr create --fill` did it when it was supposed to use the text from git. I hate github.

I think it does that by default if you're not strictly one commit above `main`.

**Review by michaelrj-google — APPROVED** [review]
LGTM

**Comment by gchatelet** [comment]
> > Mind updating the PR description? Not sure what happened there.
> 
> `gh pr create --fill` did it when it was supposed to use the text from git. I hate github.

`gh pr create --fill-first` ?

**Pull request merged**
