### PR TITLE
ValueTracking: teach implied-cond about samesign

### PR DESCRIPTION
**Pull request by artagnon**
isImpliedCondition benefits little from the icmp samesign feature: the only routine that can use this information is isImpliedCondICmps when it is matching against signed predicates, since icmp samesign is already canonicalized with an unsigned predicate. Add this support.

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
> isImpliedCondition benefits little from the icmp samesign feature: the only routine that can use this information is isImpliedCondICmps when it is matching against signed predicates, since icmp samesign is already canonicalized with an unsigned predicate. Add this support.

Hm, why do other parts of isImpliedCond not benefit? I'd expect it to be useful at least for the isImpliedCondMatchingOperands and isImpliedCondOperands logic, possibly also isImpliedCondCommonOperandWithCR.

The code you're modifying here is a very special case -- it's probably exactly the one part of this code where I wouldn't bother with samesign support :)

**Comment by artagnon** [comment]
> Hm, why do other parts of isImpliedCond not benefit? I'd expect it to be useful at least for the isImpliedCondMatchingOperands and isImpliedCondOperands logic, possibly also isImpliedCondCommonOperandWithCR.

I did look at isImpliedCondMatchingOperands, which just calls isImplied{True,False}ByMatchingCmp. Wouldn't icmp samesign be canonicalized with unsigned predicates, and wouldn't the predicates either match or have LT => LE | NE and GT => GE | NE?

I also looked at isImpliedCondOperands, and due to the canonicalization, wouldn't LT + LE and GT + GE call isTruePredicate with LE + LE, and isn't the signed case in isTruePredicate strictly less powerful than the unsigned case?

I'm not too sure about isImpliedCondCommonOperandWithCR, but my reasoning is that getting signed ConstantRanges versus getting unsigned ConstantRanges for the same Values, in the context of comparing ranges, would make no difference.
 
> The code you're modifying here is a very special case -- it's probably exactly the one part of this code where I wouldn't bother with samesign support :)

I realized this too, but this seems to be the only legitimate opportunity.

**Comment by nikic** [comment]
You generally can't assume that *both* icmps will get the same canonicalization. Consider code structure like this:

```
if (a sgt b) {
  if (a sge 0 && b sge 0) {
    if (a sge b) { // canonicalized to a samesign uge b
    }
  }
}
```

The first comparison can't be canonicalized, because the preconditions for that don't hold, so we only canonicalize the second one. And then we'd want to undo that one to a sge b to make the signedness of the predicates match, and then we have the implication that a sgt b => a sge b.

**Comment by artagnon** [comment]
Subsumed by #120120.

**Pull request closed without merging**
