### PR TITLE
[X86][Driver] Do not add `-evex512` for `-march=native` when the target doesn't support AVX512

### LINKED ISSUE #91076: Build failure with -march=native on Intel Core i5 13600KF (error in backend: ZMM registers are not supported without EVEX512)
LLVM fails to build when using `-march=native` on an Intel Core i5 13600KF, reproducible both on master at https://github.com/llvm/llvm-project/commit/cb015b9ec9446b3a1303980c095fa442d5e46fbf and version 18.1.5

```
FAILED: lib/Support/BLAKE3/CMakeFiles/LLVMSupportBlake3.dir/blake3_avx512_x86-64_unix.S.o 
/usr/lib/llvm/19/bin/clang -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/mnt/portage/portage/sys-devel/llvm-19.0.0.9999/work/llvm_build-abi_x86_64.amd64/lib/Support/BLAKE3 -I/mnt/portage/portage/sys-devel/llvm-19.0.0.9999/work/llvm/lib/Support/BLAKE3 -I/mnt/portage/portage/sys-devel/llvm-19.0.0.9999/work/llvm_build-abi_x86_64.amd64/include -I/mnt/portage/portage/sys-devel/llvm-19.0.0.9999/work/llvm/include  -DNDEBUG -march=native -O2 -pipe -fPIC -mavx512vl -MD -MT lib/Support/BLAKE3/CMakeFiles/LLVMSupportBlake3.dir/blake3_avx512_x86-64_unix.S.o -MF lib/Support/BLAKE3/CMakeFiles/LLVMSupportBlake3.dir/blake3_avx512_x86-64_unix.S.o.d -o lib/Support/BLAKE3/CMakeFiles/LLVMSupportBlake3.dir/blake3_avx512_x86-64_unix.S.o -c /mnt/portage/portage/sys-devel/llvm-19.0.0.9999/work/llvm/lib/Support/BLAKE3/blake3_avx512_x86-64_unix.S
clang -cc1as: fatal error: error in backend: ZMM registers are not supported without EVEX512
```

Output from `echo | clang -E - -march=native -###
```
clang version 19.0.0gitcb015b9e
Target: x86_64-pc-linux-gnu
Thread model: posix
InstalledDir: /usr/lib/llvm/19/bin
Configuration file: /etc/clang/x86_64-pc-linux-gnu-clang.cfg
 (in-process)
 "/usr/lib/llvm/19/bin/clang-19" "-cc1" "-triple" "x86_64-pc-linux-gnu" "-E" "-disable-free" "-clear-ast-before-backend" "-disable-llvm-verifier" "-discard-value-names" "-main-file-name" "-" "-mrelocation-model" "pic" "-pic-level" "2" "-pic-is-pie" "-mframe-pointer=all" "-fmath-errno" "-ffp-contract=on" "-fno-rounding-math" "-mconstructor-aliases" "-funwind-tables=2" "-target-cpu" "alderlake" "-target-feature" "+prfchw" "-target-feature" "-cldemote" "-target-feature" "+avx" "-target-feature" "+aes" "-target-feature" "+sahf" "-target-feature" "+pclmul" "-target-feature" "-xop" "-target-feature" "+crc32" "-target-feature" "+xsaves" "-target-feature" "-avx512fp16" "-target-feature" "-usermsr" "-target-feature" "-sm4" "-target-feature" "-egpr" "-target-feature" "+sse4.1" "-target-feature" "-avx512ifma" "-target-feature" "+xsave" "-target-feature" "+sse4.2" "-target-feature" "-avx512pf" "-target-feature" "-tsxldtrk" "-target-feature" "+ptwrite" "-target-feature" "+widekl" "-target-feature" "-sm3" "-target-feature" "+invpcid" "-target-feature" "+64bit" "-target-feature" "+xsavec" "-target-feature" "-avx10.1-512" "-target-feature" "-avx512vpopcntdq" "-target-feature" "+cmov" "-target-feature" "-avx512vp2intersect" "-target-feature" "-avx512cd" "-target-feature" "+movbe" "-target-feature" "-avxvnniint8" "-target-feature" "-avx512er" "-target-feature" "-ccmp" "-target-feature" "-amx-int8" "-target-feature" "+kl" "-target-feature" "-avx10.1-256" "-target-feature" "-evex512" "-target-feature" "+avxvnni" "-target-feature" "-rtm" "-target-feature" "+adx" "-target-feature" "+avx2" "-target-feature" "+hreset" "-target-feature" "+movdiri" "-target-feature" "+serialize" "-target-feature" "-sha512" "-target-feature" "+vpclmulqdq" "-target-feature" "-avx512vl" "-target-feature" "-uintr" "-target-feature" "-cf" "-target-feature" "+clflushopt" "-target-feature" "-raoint" "-target-feature" "-cmpccxadd" "-target-feature" "+bmi" "-target-feature" "-amx-tile" "-target-feature" "+sse" "-target-feature" "+gfni" "-target-feature" "-avxvnniint16" "-target-feature" "-amx-fp16" "-target-feature" "-ndd" "-target-feature" "+xsaveopt" "-target-feature" "+rdrnd" "-target-feature" "-avx512f" "-target-feature" "-amx-bf16" "-target-feature" "-avx512bf16" "-target-feature" "-avx512vnni" "-target-feature" "-push2pop2" "-target-feature" "+cx8" "-target-feature" "-avx512bw" "-target-feature" "+sse3" "-target-feature" "+pku" "-target-feature" "+fsgsbase" "-target-feature" "-clzero" "-target-feature" "-mwaitx" "-target-feature" "-lwp" "-target-feature" "+lzcnt" "-target-feature" "+sha" "-target-feature" "+movdir64b" "-target-feature" "-ppx" "-target-feature" "-wbnoinvd" "-target-feature" "-enqcmd" "-target-feature" "-prefetchwt1" "-target-feature" "-avxneconvert" "-target-feature" "-tbm" "-target-feature" "-pconfig" "-target-feature" "-amx-complex" "-target-feature" "+ssse3" "-target-feature" "+cx16" "-target-feature" "+bmi2" "-target-feature" "+fma" "-target-feature" "+popcnt" "-target-feature" "-avxifma" "-target-feature" "+f16c" "-target-feature" "-avx512bitalg" "-target-feature" "-rdpru" "-target-feature" "+clwb" "-target-feature" "+mmx" "-target-feature" "+sse2" "-target-feature" "+rdseed" "-target-feature" "-avx512vbmi2" "-target-feature" "-prefetchi" "-target-feature" "+rdpid" "-target-feature" "-fma4" "-target-feature" "-avx512vbmi" "-target-feature" "+shstk" "-target-feature" "+vaes" "-target-feature" "+waitpkg" "-target-feature" "-sgx" "-target-feature" "+fxsr" "-target-feature" "-avx512dq" "-target-feature" "-sse4a" "-debugger-tuning=gdb" "-fdebug-compilation-dir=/home/kostadin" "-fcoverage-compilation-dir=/home/kostadin" "-resource-dir" "/usr/lib/llvm/19/bin/../../../../lib/clang/19" "-include" "/usr/include/gentoo/fortify.h" "-include" "/usr/include/gentoo/maybe-stddefs.h" "-internal-isystem" "/usr/lib/llvm/19/bin/../../../../lib/clang/19/include" "-internal-isystem" "/usr/local/include" "-internal-isystem" "/usr/lib/gcc/x86_64-pc-linux-gnu/14/../../../../x86_64-pc-linux-gnu/include" "-internal-externc-isystem" "/include" "-internal-externc-isystem" "/usr/include" "-ferror-limit" "19" "-stack-protector" "2" "-fstack-clash-protection" "-fcf-protection=none" "-fgnuc-version=4.2.1" "-fskip-odr-check-in-gmf" "-fcolor-diagnostics" "-D__GCC_HAVE_DWARF2_CFI_ASM=1" "-o" "-" "-x" "c" "-"
```

[complete build log from portage](https://github.com/llvm/llvm-project/files/15210489/build.log)

### PR DESCRIPTION
**Pull request by phoebewang**
Users want `-march=sandybridge -mavx512f -mavx512vl` behaves the same as `-march=native -mavx512f -mavx512vl` on a sandybridge target.

Fixes: #91076

### CODE REVIEW

**Comment by topperc** [comment]
Could you make getHostCPUFeatures only write the Features["evex512"] entry if Features["avx512f"] is true? Instead of copying Features["avx512f"]?

**Comment by phoebewang** [comment]
> Could you make getHostCPUFeatures only write the Features["evex512"] entry if Features["avx512f"] is true? Instead of copying Features["avx512f"]?

Good idea, done.

**Review by topperc — APPROVED** [review]
LGTM

**Comment by phoebewang** [comment]
/cherry-pick https://github.com/llvm/llvm-project/commit/87f3407856e61a73798af4e41b28bc33b5bf4ce6

**Comment by FireBurn** [comment]
@tstellar Can a note be added somewhere about this? Folks upgrading to llvm-18.1.6 will get errors unless they drop -march=native if they were on 18.1.5

**Comment by phoebewang** [comment]
> @tstellar Can a note be added somewhere about this? Folks upgrading to llvm-18.1.6 will get errors unless they drop -march=native if they were on 18.1.5

Although I agree we should add a note, I don't think this patch affects much. The problem only coccurs when combining `-march=native` with AVX512 options on a non AVX512 target. This actually is not a valid scenario. The compiled binary will contain AVX512 instruction which crashes it on the target. It violates the intention of using `-march=native`. I also don't see where the error from with 18.1.6. If there were errors, it should come from 18.1.5.

**Comment by phoebewang** [comment]
@FireBurn Sorry, I just noticed #91719. The above comments were based on the issue #91076.

I didn't look at the source, but the command line doesn't have an AVX512 option. So I'm assuming the code may related function multi-versioning with manually specified target attributes regarding to AVX512 features.

The reason is the same as #91719, but the scenarios may be more common in practice. The defect in previous patch does expose a known issue with the design of EVEX512, which we have noted in https://clang.llvm.org/docs/UsersManual.html#x86

In a word, when user uses target attributes with AVX512 features, they should add an explicit `evex512` or `no-evex512` for robustness since LLVM 18. Missing it may result in some unexpected codegen or error in some corner case.

**Comment by FireBurn** [comment]
You'll be probably building 18.1.6 with 18.1.5... and that's when you'll notice the issue. I'm just about finished building 18.1.5 with your patch. So hopefully all those issues will be gone. I'll report back

**Comment by phoebewang** [comment]
> You'll be probably building 18.1.6 with 18.1.5... and that's when you'll notice the issue. I'm just about finished building 18.1.5 with your patch. So hopefully all those issues will be gone. I'll report back

Okay... This is a combined problem which I never thought before. Sorry for the inconvenience!

**Comment by FireBurn** [comment]
No worries, it's fixed now, llvm, nodejs and libreoffice are all compiling fine again

**Comment by tstellar** [comment]
@phoebewang Can you add a release note for this on the PR for the release branch and then add the release:note label.

**Comment by phoebewang** [comment]
> @phoebewang Can you add a release note for this on the PR for the release branch and then add the release:note label.

Done.

**Pull request merged**
