### PR TITLE
[compiler-rt][fuzzer] SetThreadName build fix for Mingwin attempt

### PR DESCRIPTION
**Pull request by devnexen**

### CODE REVIEW

**Comment by devnexen** [comment]
@Zentrik would this work for you ?

**Comment by Zentrik** [comment]
I suspect it would, let me test it though. My concern with this approach was that mingw does not necessarily use pthreads. There seems to have been some discussion of that in https://github.com/llvm/llvm-project/pull/74981#issuecomment-1849982934

**Comment by Zentrik** [comment]
Can confirm this works for me. Thanks for being so quick.

**Comment by mstorsjo** [comment]
This breaks builds in environments that don't use winpthreads. I'll go ahead and revert this patch.

I don't see any explanation in this PR whatsoever, about what issue this actually tries to solve. Please do include a reference. (I do see that this PR is mentioned in https://github.com/llvm/llvm-project/issues/106871, so I guess that's the issue that it tries to fix.)

**Pull request merged**
