### PR TITLE
[RISCV] Adjust FP load latencies from 6 to 5 in SiFiveP400/P600 scheduling models

### PR DESCRIPTION
**Pull request by mshockwave**
According to our performance measurements, FLH/W/D have load latencies closer to 5 rather than 6 in these two models.

### CODE REVIEW

**Comment by michaelmaitland** [comment]
Can you cite how you know this in the PR description?

**Comment by mshockwave** [comment]
> Can you cite how you know this in the PR description?

Of course. It's updated now.

**Comment by wangpc-pp** [comment]
> According to our performance measurements

Shouldn't this latency be determined by the CPU pipeline? Why do we need measurements?

**Comment by topperc** [comment]
> > According to our performance measurements
> 
> Shouldn't this latency be determined by the CPU pipeline? Why do we need measurements?

Yes. We got it from our internal microarchitectural specification document. Min did confirm it with measurements though. An earlier version said 6 cycles and it was changed later.

**Review by wangpc-pp — APPROVED** [review]
LGTM.

**Pull request merged**
