### PR TITLE
[flang] Pass VALUE CHARACTER arg by register in BIND(C) calls

### PR DESCRIPTION
**Pull request by jeanPerier**
Fortran mandates "CHARACTER(1), VALUE" be passed as a C "char" in calls to BIND(C) procedures (F'2023 18.3.7 (4)). Lowering passed them by memory instead. Update call interface lowering code to pass them by register. Fix related test and update it to use HLFIR.

### CODE REVIEW

**Review by vzakhari — COMMENTED** [review]
Thank you, Jean! Is there a test that tests the caller side?

**Comment by jeanPerier** [comment]
> Thank you, Jean! Is there a test that tests the caller side?

No, and the case where the actual argument length was not one was incorrect, thanks!

**Review by vzakhari — APPROVED** [review]
Thank you!

**Comment by DanielCChen** [comment]
FYI: This PR fixed issue #81646.

**Pull request merged**
