### PR TITLE
[MLIR][Arith] Add CeilFloorDivExpandOpsPatterns to conversion to LLVM (Reland)

### PR DESCRIPTION
**Pull request by nujaa**
When running convert-to-llvm, `ceildiv` and `floordiv` ops which do not have direct llvm conversion pattern, would not get lowered to llvm dialect. This patch adds CeilFloorDivExpandOpsPatterns to both `convert-to-llvm` and `arith-to-llvm` (deprecated) lowering those ops to lower level arith ops which can be lowered to llvm using LLVM conversion.

Reland of https://github.com/llvm/llvm-project/pull/117305 after buildbot failures.
See:
https://lab.llvm.org/buildbot/#/builders/80/builds/7168
https://lab.llvm.org/buildbot/#/builders/130/builds/7036
https://lab.llvm.org/buildbot/#/builders/138/builds/7290

Added dependence to ArithTransforms in ArithToLLVM. In previous discussion, it has been suggested to move the CeilFloorDivExpandOpsPatterns to ArithUtils but I think linking ArithTransforms makes more sense as otherwise : 
* ArithToLLVM needs a new dependency to ArithUtils
* ArithUtils needs new dependency to ArithTransforms or move the patterns as well which will create more dependencies
* It creates lots of code motion which makes it hard to review.

### CODE REVIEW

**Comment by RoboTux** [comment]
> @RoboTux @banach-space , I added a dependence to MLIRTransforms in this patch, thinking it would solve the linkage error. But, since I could not reproduce this linkage error downstream, I am unsure this fix actually solves the linkage. It is my first time dealing with the buildbots, I have read about buildbot ownership, buildbot creations, ... but, I cannot access the buildbot builds (e.g. https://lab.llvm.org/buildbot/#/builders/80/builds/7168) . I tried with various networks and browsers, it looks like there is no data. Do I need to ask for specific project authorization ?

One way to reproduce would be to build just lib/libArithToLLVM.a instead of building the whole of MLIR. If that still passes (without your updated patch) you could try to change the build tool (from Ninja to GNU Make or the opposite) to see if that helps.

**Comment by banach-space** [comment]
> I cannot access the buildbot builds (e.g. https://lab.llvm.org/buildbot/#/builders/80/builds/7168) . I tried with various networks and browsers, it looks like there is no data. Do I need to ask for specific project authorization ?

This is 100% public and you should be able to access it. Having said that, Buildbot can be slow and sometimes just doesn't load. This particular build logs loads for me just fine _right now_.

That buildbot is `flang-aarch64-sharedlibs`, which is defined in llvm-zorg [here](https://github.com/llvm/llvm-zorg/blob/7424d711752e5b90a2daeda937f4a6dec47cd535/buildbot/osuosl/master/config/builders.py#L2331-L2344). You can use that definition to see what CMake flags are used for this config. For build failures like this you will very likely discover that adding: 
* `-DBUILD_SHARED_LIBS=ON` 

does the trick :) (as in, shared-libs configuration is much more sensitive to missing dependencies). Hope this helps, if not we'll dig a bit deeper 👍🏻 

Ah, and here's the actual CMake invoc from the failing buildbot job:
```bash
cmake -DLLVM_TARGETS_TO_BUILD=AArch64 -DBUILD_SHARED_LIBS=ON -DLLVM_BUILD_EXAMPLES=ON -DCMAKE_CXX_STANDARD=17 '-DLLVM_ENABLE_PROJECTS=mlir;llvm;clang;flang' -DLLVM_ENABLE_RUNTIMES=openmp -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=ON '-DLLVM_LIT_ARGS=-v -vv' -GNinja ../llvm-project/llvm
```

**Comment by nujaa** [comment]
Thank you both. Indeed, `-DBUILD_SHARED_LIBS=ON` did the trick, I'll definitely add it to my upstream LLVM config. I can now say this patch solves the linkage error of the previous MR. 👍 
I'll look into buildbot access for the future.

**Review by banach-space — APPROVED** [review]
LGTM, thanks!

From what I can tell, Mehdi's concerns have also been addressed, so this should be good to land.

**Comment by nujaa** [comment]
Should we wait for @joker-eph 's to check whether his concerns have been addressed ?

**Comment by banach-space** [comment]
> Should we wait for @joker-eph 's to check whether his concerns have been addressed ?

As hinted in my approval, IMO all concerns have been assessed and this is ready to land. If Mehdi complains, you can blame me ;-)

Having said that, since you've just pinged Mehdi, I'd wait 24hrs :-)

**Comment by nujaa** [comment]
After the previous breakage, I try not to make hasty assumptions. 🙄

**Review by joker-eph — APPROVED** [review]

**Comment by joker-eph** [comment]
That's fine, this kind of breakages are common, and most of the time re-landing with the fix is straightforward and does not need a great deal of reviews (if the fix is trivial, you can re-land without extra reviews).
(Sorry I missed you PR earlier)

**Pull request merged**
