### PR TITLE
[InstCombine] lshr (mul (X, 2^N + 1)), N -> add (X, lshr(X, N))

### PR DESCRIPTION
**Pull request by AZero13**
Alive2 Proofs:
https://alive2.llvm.org/ce/z/eSinJY
https://alive2.llvm.org/ce/z/sweDgc

### CODE REVIEW

**Comment by goldsteinn** [comment]
Generally in a reland you reference the original commit and what has changed to make it okay.

**Comment by AtariDreams** [comment]
> Generally in a reland you reference the original commit and what has changed to make it okay.

Correct but honestly I made another revision so I'm gonna change the title anyway so it gets a full proper review

**Comment by AtariDreams** [comment]
Alive2 Proofs:
https://alive2.llvm.org/ce/z/eSinJY
https://alive2.llvm.org/ce/z/sweDgc
https://alive2.llvm.org/ce/z/-2dXZi
https://alive2.llvm.org/ce/z/kx2PhF
https://alive2.llvm.org/ce/z/e9QjM6

**Comment by nikic** [comment]
I mistakenly reverted the original patch as part of a larger set of reverts. I've now reapplied the original patch in https://github.com/llvm/llvm-project/commit/718ba5a58452f013f40fab94f967064919bf13ff. This PR seems to again contain additional changes -- please open a new PR with those.

**Comment by AtariDreams** [comment]
> I mistakenly reverted the original patch as part of a larger set of reverts. I've now reapplied the original patch in https://github.com/llvm/llvm-project/commit/718ba5a58452f013f40fab94f967064919bf13ff. This PR seems to again contain additional changes -- please open a new PR with those, on top of the relanded patch.

My bad. I thought you retroactively rejected it.

**Pull request closed without merging**
