### PR TITLE
Clang: Add warning flag for storage class specifiers on explicit specializations

### PR DESCRIPTION
**Pull request by dwblaikie**
With the recent fix for this situation in class members (#93873) (for
which the fixed code is invalid prior to this patch - making migrating
code difficult as it must be in lock-step with the compiler migration,
if building with -Werror) it'd be really useful to be able to disable
this warning during the compiler migration/decouple the compiler
migration from the source fixes.

In theory this approach will regress the codebase to the previous
non-member cases of this issue that were already being held back by the
warning (as opposed to if we carved out the new cases into a separate
warning from the existing cases) but I think this'll be so rare and the
cleanup so simple, that the extra regressions of disabling the warning
broadly won't be too much of a problem. (but if folks disagree, I'm open
to making the warning more fine-grained)

### CODE REVIEW

**Review by alexfh — COMMENTED** [review]
Should we add a test for this flag? Something around existing tests in clang/test/CXX/temp/temp.spec/temp.expl.spec/p2-20.cpp and clang/test/CXX/dcl.dcl/dcl.spec/dcl.stc/p1.cpp.

**Comment by dwblaikie** [comment]
> Should we add a test for this flag? Something around existing tests in clang/test/CXX/temp/temp.spec/temp.expl.spec/p2-20.cpp and clang/test/CXX/dcl.dcl/dcl.spec/dcl.stc/p1.cpp.

Oh, right, I did have a new test I meant to add, but that's a better place for it - so I've added that test coverage in https://github.com/llvm/llvm-project/pull/96699/commits/b3facc9dffc762e3cef93886df23026d502afcae

(I'm out for the day, so if anyone happens to approve this and feel like pressing the "squash and merge" button that'd be swell, otherwise I'll get to it when I have a chance/tomorrow)

**Review by alexfh — APPROVED** [review]
LGTM

Thank you!

**Review by AaronBallman — APPROVED** [review]
LGTM

**Review by sdkrystian — APPROVED** [review]
Minor nit: Probably don't need to explicitly define a diagnostic group, since it's only ever used for this diagnostic.

**Comment by dwblaikie** [comment]
> Minor nit: Probably don't need to explicitly define a diagnostic group, since it's only ever used for this diagnostic.

Not sure what the conventions are - but I rather like the normalization of having the explicit group, better chance of finding the group/reusing it maybe? So i'll leave it there for now, but if you feel strongly/other folks chime in - happy to change it in a follow-up commit. (& good to understand that explicit groups aren't necessary/the inline group definition is a valid option, though)

**Pull request merged**
