### PR TITLE
Propagate the Buildkite pre-merge setup to GitHub Action

### PR DESCRIPTION
**Pull request by joker-eph**
This is a WIP, the Buildkite script is .ci/generate-buildkite-pipeline-premerge

### CODE REVIEW

**Review by boomanaiden154 — COMMENTED** [review]
Thanks for working on this!

A couple points:
* Are we able to limit this to testing on Windows for now so we can focus on getting back coverage there without taking up too many runners?
* We believe that we might end up throughput constrained with the 60 job limit. I'm working on collecting statistics on this so we have more reliable numbers. In the mean time, maybe we introduce something like this gradually (one subproject at a time) to ensure we don't hit throughput limits?
* It would be nice if we could combine this into a single job and select the targets to build as necessary to avoid the issue you mentioned on the Discourse thread. Maybe even an adaptation of the current shell script in `.ci` that selects stuff for Buildkite? This would probably be necessary in a separate job to not impact the release jobs, but that would be up to @tstellar.

As an aside, I'm working on setting up per-OS pipelines right now (with common stuff put into a separate action like `llvm-project-tests.yml`) and using optimized toolchains/containers to improve system throughput. I have put up https://github.com/llvm/llvm-project/pull/80951 for the time being as an initial version to start testing things out at scale. That's Linux/LLVM only currently though and the most basic configuration without most of the ideas implemented (other than using a well-optimized toolchain to pull buildtimes down significantly).

**Comment by joker-eph** [comment]
> It would be nice if we could combine this into a single job and select the targets to build as necessary to avoid the issue you mentioned on the Discourse thread. Maybe even an adaptation of the current shell script in .ci that selects stuff for Buildkite? This would probably be necessary in a separate job to not impact the release jobs, but that would be up to @tstellar.

Yeah: we discussed it here: https://discourse.llvm.org/t/rfc-future-of-windows-pre-commit-ci/76840/34

I'll leave this PR as a reference, and send another one in this direction for consideration.

**Comment by tstellar** [comment]
> > It would be nice if we could combine this into a single job and select the targets to build as necessary to avoid the issue you mentioned on the Discourse thread. Maybe even an adaptation of the current shell script in .ci that selects stuff for Buildkite? This would probably be necessary in a separate job to not impact the release jobs, but that would be up to @tstellar.
> 
> Yeah: we discussed it here: https://discourse.llvm.org/t/rfc-future-of-windows-pre-commit-ci/76840/34
> 
> I'll leave this PR as a reference, and send another one in this direction for consideration.

@joker-eph Do you have a prototype for this? I was thinking about doing something similar for the Windows CI on GitHub Actions

**Comment by joker-eph** [comment]
I don't: I was planning to setup a GitHub Action for the window CI that would reuse the buildkite script (just invoke it should be doable basically), but I haven't got to it yet. Do you want to give it a try?

**Comment by tstellar** [comment]
@joker-eph Yeah, I think I'll try it.

**Pull request closed without merging**
