### PR TITLE
[AMDGPU] Get rid of the +wavefrontsizeXX,-wavefrontsizeXX in MC tests

### PR DESCRIPTION
**Pull request by rampitec**
Now turning off/turning on feature is not needed in most cases. This is NFC, tests only.

### CODE REVIEW

**Comment by rampitec** [comment]
Change is massive. But this is test only. And only simplification.

**Comment by rampitec** [comment]
And this is literally result of `sed -i` in both directories.

**Comment by jayfoad** [comment]
> Now turning off/turning on feature is not needed in most cases. This is NFC, tests only.

What is the behavior now? Specifying either of +wavefrontsize32 or +wavefrontsize64 automatically turns off the other one? But there is still a default if you specify neither, right?

**Comment by rampitec** [comment]
> > Now turning off/turning on feature is not needed in most cases. This is NFC, tests only.
> 
> What is the behavior now? Specifying either of +wavefrontsize32 or +wavefrontsize64 automatically turns off the other one? But there is still a default if you specify neither, right?

There is default, it is wave32 if wave32 is supported. If you specify +wavefrontsize64 it will turn off wave32 automatically.

**Review by arsenm — APPROVED** [review]

**Pull request merged**
