### PR TITLE
[cmake] Optimize RelWithDebInfo compiler options on windows

### PR DESCRIPTION
**Pull request by GkvJwa**
Due to the default cmake Release does not contain pdb, and RelWithDebInfo compilation parameter does not enable linking and compilation optimization. As a result, if we use RelWithDebInfo to compile on the windows, the generated clang will be larger in size and have slightly poorer performance.

Therefore, enable some compilation optimizations to improve performance and build size
compared:
```
size:
Default: 115 MB (121,020,928 bytes)
Optimized: 74.3 MB (77,987,840 bytes)

build time:compiling the same project can shorten 2~3 minutes(11min -> 8min)
```

This is equivalent to adding generate pdb to Release:
```
set(CMAKE_CXX_FLAGS_RELEASE "${CMAKE_CXX_FLAGS_RELEASE} /Zi")
set(CMAKE_EXE_LINKER_FLAGS_RELEASE "${CMAKE_EXE_LINKER_FLAGS_RELEASE} /DEBUG /OPT:REF /OPT:ICF")
set(CMAKE_SHARED_LINKER_FLAGS_RELEASE "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /DEBUG /OPT:REF /OPT:ICF")
```

In addition, cross-compilation should require additional parameters to be set

### CODE REVIEW

**Comment by GkvJwa** [comment]
hello @tstellar @zmodem
When you are free, can you help with the review

**Comment by zmodem** [comment]
Where are the flags for RelWithDebInfo currently defined? Is that done in LLVM's CMake files somewhere, or is it CMake internal?

This patch adds a bunch of flags. The ideal would be if RelWithDebInfo was equivalent to Release + flags to build the .pdb.

> In addition, cross-compilation should require additional parameters to be set

What does this mean?

**Comment by GkvJwa** [comment]
> Where are the flags for RelWithDebInfo currently defined? Is that done in LLVM's CMake files somewhere, or is it CMake internal?
> 
> This patch adds a bunch of flags. The ideal would be if RelWithDebInfo was equivalent to Release + flags to build the .pdb.
> 
> > In addition, cross-compilation should require additional parameters to be set
> 
> What does this mean?

cmake's internal decision, [Windows-Intel-Fortran.cmake](https://github.com/Kitware/CMake/blob/master/Modules/Platform/Windows-Intel-Fortran.cmake#L27)
The reason is that cmake does not enable any link optimization(/OPT) by default and llvm's cmake does not add additional parameters(this commit does this)

This is equal to release+pdb, based on the comparison I compiled on windows

For example, there is no adaptation to cross-compile windows on Linux(here checked if it is msvc)
https://github.com/llvm/llvm-project/blob/5c56b46a32a8856a022a54291bc9294068f7ddbd/llvm/CMakeLists.txt#L843-L845

**Comment by zmodem** [comment]
This patch seems brittle though. What if LLVM's regular Release flags change, how do we ensure that CMAKE_CXX_FLAGS_RELWITHDEBINFO is kept in sync?

Could we define CMAKE_CXX_FLAGS_RELWITHDEBINFO to be CMAKE_CXX_FLAGS_RELEASE + debug flags somewhere?

**Comment by GkvJwa** [comment]
> This patch seems brittle though. What if LLVM's regular Release flags change, how do we ensure that CMAKE_CXX_FLAGS_RELWITHDEBINFO is kept in sync?
> 
> Could we define CMAKE_CXX_FLAGS_RELWITHDEBINFO to be CMAKE_CXX_FLAGS_RELEASE + debug flags somewhere?

Sure, we can overwrite RELWITHDEBINFO based on the CMAKE_CXX_FLAGS_RELEASE flags like this
```
  set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELEASE} /Zi")
  set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_EXE_LINKER_FLAGS_RELEASE} /DEBUG /OPT:REF /OPT:ICF")
  set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /DEBUG /OPT:REF /OPT:ICF")
```
and do we need to add some additional flags for FLAGS_RELEASE, such as /FIXED:NO

**Comment by zmodem** [comment]
> > This patch seems brittle though. What if LLVM's regular Release flags change, how do we ensure that CMAKE_CXX_FLAGS_RELWITHDEBINFO is kept in sync?
> > Could we define CMAKE_CXX_FLAGS_RELWITHDEBINFO to be CMAKE_CXX_FLAGS_RELEASE + debug flags somewhere?
> 
> Sure, we can overwrite RELWITHDEBINFO based on the CMAKE_CXX_FLAGS_RELEASE flags like this
> 
> ```
>   set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELEASE} /Zi")
>   set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_EXE_LINKER_FLAGS_RELEASE} /DEBUG /OPT:REF /OPT:ICF")
>   set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /DEBUG /OPT:REF /OPT:ICF")
> ```

Shouldn't the `LINKER_FLAGS_RELEASE` variables already include the `/OPT:` flags?

> 
> and do we need to add some additional flags for FLAGS_RELEASE, such as /FIXED:NO

Why?

**Comment by GkvJwa** [comment]
> > > This patch seems brittle though. What if LLVM's regular Release flags change, how do we ensure that CMAKE_CXX_FLAGS_RELWITHDEBINFO is kept in sync?
> > > Could we define CMAKE_CXX_FLAGS_RELWITHDEBINFO to be CMAKE_CXX_FLAGS_RELEASE + debug flags somewhere?
> > 
> > 
> > Sure, we can overwrite RELWITHDEBINFO based on the CMAKE_CXX_FLAGS_RELEASE flags like this
> > ```
> >   set(CMAKE_CXX_FLAGS_RELWITHDEBINFO "${CMAKE_CXX_FLAGS_RELEASE} /Zi")
> >   set(CMAKE_EXE_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_EXE_LINKER_FLAGS_RELEASE} /DEBUG /OPT:REF /OPT:ICF")
> >   set(CMAKE_SHARED_LINKER_FLAGS_RELWITHDEBINFO "${CMAKE_SHARED_LINKER_FLAGS_RELEASE} /DEBUG /OPT:REF /OPT:ICF")
> > ```
> 
> Shouldn't the `LINKER_FLAGS_RELEASE` variables already include the `/OPT:` flags?
> 
> > and do we need to add some additional flags for FLAGS_RELEASE, such as /FIXED:NO
> 
> Why?

cmake `LINKER_FLAGS_RELEASE` does not include `/OPT:` flags, because it will not generate pdb on windows
I just found out in the llvm repository that there are actually setting options for release

https://github.com/llvm/llvm-project/blob/5c56b46a32a8856a022a54291bc9294068f7ddbd/llvm/cmake/modules/HandleLLVMOptions.cmake#L590-L602

But it is very obscure. People who are not familiar with llvm will not notice it at all, and it is only for release.

**Comment by tstellar** [comment]
I think the rule of thumb is not to modify the builtin CMAKE_* variables.  It's hard to predict how this may impact a user who wants to set their own custom flags.  See https://alexreinking.com/blog/how-to-use-cmake-without-the-agonizing-pain-part-2.html

**Comment by GkvJwa** [comment]
> I think the rule of thumb is not to modify the builtin CMAKE_* variables. It's hard to predict how this may impact a user who wants to set their own custom flags. See https://alexreinking.com/blog/how-to-use-cmake-without-the-agonizing-pain-part-2.html

I agree with the point of view of this article, but the flags of cmake on Windows are indeed unreasonable, using the default RELWITHDEBINFO flags greatly affects the running speed and increases the file size, the default release does not generate pdb, so that additional options have been added to modify CMAKE_*RELEASE to generate pdb, but for users who are not familiar with engineering, it is difficult to find these options

**Comment by zmodem** [comment]
Maybe we should update the docs to make `LLVM_ENABLE_PDB` more prominent then?

**Comment by GkvJwa** [comment]
> Maybe we should update the docs to make `LLVM_ENABLE_PDB` more prominent then?

That's okay too

**Comment by zmodem** [comment]
> > Maybe we should update the docs to make `LLVM_ENABLE_PDB` more prominent then?
> 
> That's okay too

I've sent #102887, let me know what you think.

**Pull request closed without merging**
