### PR TITLE
Revert "Revert "[OpenMP][TR12] change property of map-type modifier."…

### PR DESCRIPTION
**Pull request by jyu2-git**
… (#90885)"

This reverts commit eea81aa29848361eb5b24f24d2af643fdeb9adfd.

Also change isMapType as @vitalybuka suggested.  Hope this fix sanitizer build problem.

### CODE REVIEW

**Review by vitalybuka — APPROVED** [review]

**Comment by TomWeaver18** [comment]
Greetings and hello from the UK!

 it looks as though this commit caused a test failure on the following build bot, is anyone able to take a look see?

https://lab.llvm.org/buildbot/#/builders/139/builds/65066

Will give it an hour for a reply before looking at a revert.

Have a great day all.

**Comment by vitalybuka** [comment]
> Greetings and hello from the UK!
> 
> it looks as though this commit caused a test failure on the following build bot, is anyone able to take a look see?
> 
> https://lab.llvm.org/buildbot/#/builders/139/builds/65066
> 
> Will give it an hour for a reply before looking at a revert.
> 
> Have a great day all.

I am not looking into this, and not sure if @jyu2-git 
revert is LGTM

**Comment by TomWeaver18** [comment]
Reverted in https://github.com/llvm/llvm-project/commit/341aecc2dd0f6debcbe9f251a6d2e8a60d327eea

**Comment by jyu2-git** [comment]
The test failed is due to the change following:  I had fixed the test in https://github.com/llvm/llvm-project/pull/91426.

commit e74a7a9fd79a74073277471243a44527c71eb4a9
Author: Fangrui Song <i@maskray.me>
Date:   Tue May 7 09:15:52 2024 -0700

    cc1: Report an error for multiple actions unless separated by -main-file-name (#91140)

    When multiple actions are specified, the last one is used and others are
    overridden. This might lead to confusion if the user is used to driver's
    `-S -emit-llvm` behavior.

    ```
    %clang_cc1 -S -emit-llvm a.c     # -S is overridden
    %clang_cc1 -emit-llvm -S a.c     # -emit-llvm is overridden
    %clang_cc1 -fsyntax-only -S a.c  # -fsyntax-only is overridden
    ```

    However, we want to continue supporting overriding the driver action
    with -Xclang:

    * `clang -c -Xclang -ast-dump a.c` (`%clang -cc1 -emit-obj ...
    -main-file-name a.c ... -ast-dump`)
    * `clang -c -xc++ -Xclang -emit-module stl.modulemap`

    As an exception, we allow -ast-dump* options to be composed together
    (e.g. `-ast-dump -ast-dump-lookups` in AST/ast-dump-lookups.cpp).

**Pull request merged**
