### PR TITLE
[flang][test] Recognize !$acc and !$omp spelled with capital letters

### PR DESCRIPTION
**Pull request by kparzysz**
If there are any continuation lines in the source, they will be printed by the unparser with capital letters (at least in case of OpenMP). To avoid having them stripped out, recognize their spellings using capital letters as well.

### CODE REVIEW

**Review by Meinersbur — COMMENTED** [review]
> If there are any continuation lines in the source, they will be printed using capital letters (at least in case of OpenMP).

Who/what is printing them?

**Comment by kparzysz** [comment]
> Who/what is printing them?

The unparser.  I haven't dug too deep into it, I'm not sure why the first lines of the OpenMP directives are printed in lowercase for example, but if the line becomes too long it will show something like this in the output:
```
!$omp target distribute paral$
!$OMP lel
```

**Review by Meinersbur — APPROVED** [review]
> The unparser.

Could that be included in the summary/commit message?

**Comment by kparzysz** [comment]
> Could that be included in the summary/commit message?

Updated the commit description (it will become the commit message).

**Pull request merged**
