### PR TITLE
[InstCombine] Regard zext nneg as sext when folding add(zext neg(add))

### LINKED ISSUE #88348: [InstCombine] Regard `zext nneg` as `sext` when folding `add(zext neg(add))`
The following transformation is legal after adding `nneg`:

```llvm
define i32 @src(i8 %v) {
  %switch.tableidx = add nsw i8 %v, 1
  %switch.idx.cast = zext nneg i8 %switch.tableidx to i32
  %switch.offset = add nsw i32 %switch.idx.cast, -1
  ret i32 %switch.offset
}

define i32 @tgt(i8 %v) {
  %ext = sext i8 %v to i32
  ret i32 %ext
}
```

Alive2: https://alive2.llvm.org/ce/z/2iCmDs
From: https://github.com/rust-lang/rust/issues/106459#issuecomment-1925647607

### PR DESCRIPTION
**Pull request by ZelinMa557**
fixes #88348
proof:
https://alive2.llvm.org/ce/z/fJnM7t
test will be added later

### CODE REVIEW

**Comment by XChy** [comment]
This patch lacks alive2 proof, tests, and so on.
Please read about https://llvm.org/docs/InstCombineContributorGuide.html

**Comment by ZelinMa557** [comment]
Thanks, i will take a look! @XChy

**Comment by ZelinMa557** [comment]
Hi, I have added the test and proof according to https://llvm.org/docs/InstCombineContributorGuide.html, can you take a look when it is convenient for you? @XChy @nikic @dtcxzyw

**Review by dtcxzyw — APPROVED** [review]
LGTM.

**Pull request merged**
