### PR TITLE
[RFC][GlobalISel] InstructionSelect: Allow arbitrary instruction erasure

### PR DESCRIPTION
**Pull request by tobias-stadler**
See https://discourse.llvm.org/t/rfc-globalisel-instructionselect-allow-arbitrary-instruction-erasure/79948

### CODE REVIEW

**Review by qcolombet — APPROVED** [review]
LGTM.

Could you add a test case that exercises the broken functionality that you described in discourse?

**Comment by tobias-stadler** [comment]
Sorry for the rebase, had to fix a conflict. Can this be merged or does anyone have more feedback?

**Comment by qcolombet** [comment]
> Sorry for the rebase, had to fix a conflict. Can this be merged or does anyone have more feedback on the test changes?

Go ahead!

**Review by aemerson — APPROVED** [review]
Yep, LGTM too.

**Review by holland11 — APPROVED** [review]
LGTM. Thank you for this patch.

**Pull request merged**
