### PR TITLE
[memref] Support dense resources for memref-to-llvm

### PR DESCRIPTION
**Pull request by rsuderman**
Memref to llvm did not handle the DenseResourceElementsAttr. Reworked
the lowering so that it converts to a valid LLVM type.

### CODE REVIEW

**Review by joker-eph — APPROVED** [review]
Will this work on big endian?

(see recent failure with dense resources support: https://github.com/llvm/llvm-project/pull/78958#issuecomment-1908782429 )

**Comment by rsuderman** [comment]
> Will this work on big endian?
> 
> (see recent failure with dense resources support: [#78958 (comment)](https://github.com/llvm/llvm-project/pull/78958#issuecomment-1908782429) )

So that is a very good question that I am not 100% sure on. I would assume the data storage order should not change between the DenseResourcesAttr as it is just a bag of bytes I would assume it maps to the same way for DenseElementsAttr's byte ordering expectations. Is there a good way to validate?

**Comment by joker-eph** [comment]
@uweigand or @Groverkss may be able to help answering here?

**Comment by Groverkss** [comment]
This will probably have the same failures because you would interpret the bytes differently on big endian systems and the test will not match.

This also needs some tests for non-splat values.

**Comment by rsuderman** [comment]
> This will probably have the same failures because you would interpret the bytes differently on big endian systems and the test will not match. So even if it is correct, your test will fail, because the answer is dependent on endianness.
> 
> This also needs some tests for non-splat values.

Non-splat case added.

I am a little confused by your comments: are you saying that if endianness matters it will fail no matter what, or even if this test passes it may not be correct.

Thanks!

**Comment by Groverkss** [comment]
> > This will probably have the same failures because you would interpret the bytes differently on big endian systems and the test will not match. So even if it is correct, your test will fail, because the answer is dependent on endianness.
> > This also needs some tests for non-splat values.
> 
> Non-splat case added.
> 
> I am a little confused by your comments: are you saying that if endianness matters it will fail no matter what, or even if this test passes it may not be correct.
> 
> Thanks!

Thank you for adding the test. 

I'll try to be more clear. Let's take this test:

```
  // CHECK: llvm.mlir.global private constant @__constant_xf32_1(dense<[5.000000e-01, 2.500000e-01]> : tensor<2xf32>) {addr_space = 0 : i32} : !llvm.array<2 x f32>
  memref.global "private" constant @__constant_xf32_1 : memref<2xf32> = dense_resource<NAME1>
```

Here, `dense<[5.000000e-01, 2.500000e-01]>` is how little endian systems interpret the byte array in NAME1:

```
NAME1: "0x080000000000003F0000803E"
```

For a big-endian system, this may be differently interpreted and there would be a different `dense<>` attribute. So the test output actually depends on the endianness of the system.

I think we need to disable these tests for big endian systems.

**Comment by joker-eph** [comment]
> For a big-endian system, this may be differently interpreted and there would be a different dense<> attribute. So the test output actually depends on the endianness of the system.


To be clear: that's a bug though right?

**Comment by joker-eph** [comment]
Following https://github.com/llvm/llvm-project/issues/63469 ; I'm wondering if endianness decoding shouldn't be just handled here? Is `getFromRawBuffer` with `blob->getData()` correct as-is? That may be the place where endianness should be handled?

**Comment by Groverkss** [comment]
> > For a big-endian system, this may be differently interpreted and there would be a different dense<> attribute. So the test output actually depends on the endianness of the system.
> 
> To be clear: that's a bug though right?

No, it's not a bug. dense_resource does not specify what endianness to use. So the best we can do is assume the endianness of the system (which is what we do). So this test simply has different outputs on a big endian machine.

The expectation for dense_resource, AFAIU, is that whoever created it should read it.

**Comment by stellaraccident** [comment]
I think this is a test bug: dense_resource_elements takes a blob of memory and bitcasts it for access. It is the same as if someone put a char[] literal in their c program and cast it to an array of a multi byte type. It is actually a pretty important part of the contract that intervening code not go mucking with trying to manage/copy it, etc.

We use this for capturing raw memory from the framework for jit and related cases, and it is implied that if portability to another endianness is important, that is up to the user to make them agree or convert.

This is breaking because the test encodes a little endian blob. To test on big endian, it would need a big endian blob.

**Comment by stellaraccident** [comment]
> I'm not sure I agree just now that this is totally reasonable to serialize non-portable bytecode, without providing any tools to the user to not shoot themselves in the foot like that. Is this behavior documented?

I think it should be documented.

I'm not saying the use case isn't valid for someone and that there shouldn't be an attribute that does more, but that we need one that doesn't have such features -- which put constraints on use and break the memory model. If we don't get that upstream, we'll need to fork our own, most likely.

Does llvm bitcode take effort to be portable across machines for its low level constants (as in -- can you load bitcode compiled on one architecture, lto it in another and expect that something has intervened to swap endianness of the data structures at rest)? I don't actually know the answer to that 100% but that is the use case, imo.

**Comment by joker-eph** [comment]
> Does llvm bitcode take effort to be portable across machines for its low level constants 

I don't find code that would handle that, so I'd say no (but not with a high confidence)

**Comment by rsuderman** [comment]
Probably better to fix closer to the `onnx` import.

**Pull request closed without merging**
