### PR TITLE
[Github] Use our own issue labeler fork

### PR DESCRIPTION
**Pull request by cor3ntin**
As discussed in https://github.com/llvm/llvm-project/issues/65701#issuecomment-1712803305
⚠️ https://github.com/llvm/actions/pull/6 must be merged first

- Only adds 'new issue' if no other label is added (https://github.com/llvm/llvm-project/issues/65701)

- No not add labels if labels were already set
- Only add `foo` if there are no `foo:bar` label being added (although, we don't use that yet)

### CODE REVIEW

**Comment by tstellar** [comment]
What is the difference between our fork and upstream?

**Comment by cor3ntin** [comment]
> What is the difference between our fork and upstream?

- Only adds 'new issue' if no other label is added (https://github.com/llvm/llvm-project/issues/65701)
- No not add labels if labels were already set
- Only add `foo` if there are no `foo:bar` label being added (although, we don't use that yet)

**Review by tru — APPROVED** [review]
LGTM

**Comment by MaskRay** [comment]
Consider a short summary even the description contains two links. My first intuition was also

> What is the difference between our fork and upstream?

**Review by MaskRay — APPROVED** [review]

**Pull request merged**
