### PR TITLE
[clang] Don't assume location of compiler-rt for OpenBSD

### PR DESCRIPTION
**Pull request by Ericson2314**
If the `/usr/lib/...` path where compiler-rt is conventionally installed on OpenBSD does not exist, fall back to the regular logic to find it.

This is a minimal change to allow OpenBSD cross compilation from a toolchain that doesn't adopt all of OpenBSD's monorepo's conventions.

### CODE REVIEW

**Comment by epsilon-0** [comment]
Looks good - aisha@openbsd.org

**Comment by Ericson2314** [comment]
This is a very simple thing. I am quite sure it is fine from an LLVM perspective; I wanted to make sure it was fine from a BSD perspective, and @epsilon-0 confirmed it (thank you!). Will thus merge shortly.

**Pull request merged**
