### PR TITLE
Fix uninitialized variable

### PR DESCRIPTION
**Pull request by iagarwa**
Fix uninitialized scalar field

### CODE REVIEW

**Review by Keenuts — APPROVED** [review]

**Comment by iagarwa** [comment]
@MalaySanghi @mahesh-attarde please review

**Review by llvm-beanz — CHANGES_REQUESTED** [review]
Uh, why do we need to do this? None of the other data structures in this file initialize their values with inline initializers.

**Comment by iagarwa** [comment]
RuntimeInfo Objects are created only for v3 ones. That's why i initialize only EntryNameOffset

**Comment by llvm-beanz** [comment]
Even if that were true (which it isn’t, we create a std::variant of the four versions), the change still doesn’t make sense. Why would we want to only initialize the last field of a large data structure?

Is there an actual case where this caused an uninitialized value to be used, or is this just a speculative problem?

**Comment by MalaySanghi** [comment]
@iagarwa 
The field is initialized before use. Just not in the constructor. Look at PSVRuntimeInfo::finalize. So it seems to me that there's no bug.

Although I don't see a downside in initializing the field, I think you **can** ignore this.

**Comment by iagarwa** [comment]
Not needed

**Pull request closed without merging**
