### PR TITLE
[docs] Reword the alignment implications for atomic instructions.

### PR DESCRIPTION
**Pull request by JonPsson1**
Atomic instructions (load / store/ atomicrwm / cmpxchg) are not undefined behavior if they lack natural alignment. They will typically (with AtomicExpand pass enabled) be converted into libcalls.

Does this sound right? (suggestions welcome)

### CODE REVIEW

**Comment by JonPsson1** [comment]
Adding some more reviewers so that hopefully there can be some consensus around this notion whether an unaligned atomic IR instruction is undefined behavior or not. This is motivated by the fact that AtomicExpand pass always turn these into libcalls.

**Comment by jyknight** [comment]
Overall, yes.

I don't think the mention of AtomicExpandPass belongs here. It should instead just say something like "Note: if the alignment is not greater than the size, the atomic operation is likely to require a lock and have poor performance."

**Comment by JonPsson1** [comment]
Yeah, that's probably better. Patch updated.

**Review by jyknight — APPROVED** [review]
Thanks!

**Pull request merged**
