### PR TITLE
[workflows] Close issues used for backports once the PR has been created

### PR DESCRIPTION
**Pull request by tstellar**
This will allow us to track the state of the backport request in the PR, rather than in the issue.  The state updates for PRs can be automated, so this will save us some triage work.

### CODE REVIEW

**Review by tru — COMMENTED** [review]
Hm, before we have had the issue open until we had merged the PR. In case some of the needs some further discussion and revisions. Should we just do those comments and revisions directly in the PR going forward?

**Comment by tstellar** [comment]
> Hm, before we have had the issue open until we had merged the PR. In case some of the needs some further discussion and revisions. Should we just do those comments and revisions directly in the PR going forward?

Yes, I was thinking we should try to push all the discussions to the PR, because that is where all the other activity is happening for the most part (e.g. patch gets reviewed, patch gets tested, patch gets merged)

The alternative would be to add a new status to the LLVM release status project called "PR Created".  In this case,  we would leave the issue open and assign it this new "PR Created" status.  Then the other statuses would be tracked only on the PR: e.g."Needs Review", "Needs Merged".

**Review by nikic — APPROVED** [review]
I think this makes sense. In the future we might want to avoid creating issues in the first place and e.g. accept the cherry-pick command inside PRs (so you can directly run it in the PR that fixed the issue).

**Comment by tstellar** [comment]
> I think this makes sense. In the future we might want to avoid creating issues in the first place and e.g. accept the cherry-pick command inside PRs (so you can directly run it in the PR that fixed the issue).

I think you can already use the cherry-pick command inside of PRs, because PR comments also generate the issue_comment event.

**Comment by nikic** [comment]
> > I think this makes sense. In the future we might want to avoid creating issues in the first place and e.g. accept the cherry-pick command inside PRs (so you can directly run it in the PR that fixed the issue).
> 
> I think you can already use the cherry-pick command inside of PRs, because PR comments also generate the issue_comment event.

An issue with that is that you would have to add the PR to the milestone first, even though it really shouldn't be part of it.

**Pull request merged**
