### PR TITLE
[RISCV] Allow -mcmodel= to accept large for RV64

### PR DESCRIPTION
**Pull request by tclin914**

### CODE REVIEW

**Comment by lenary** [comment]
> > What's the status of backend support for the large code model? That would presumably be a prerequisite to landing this.
> 
> It was just merged: #70308.

I expected I was out of date, thanks for the link.

The psABI says the large code model is not compatible with PIC - this presumably still applies to LLVM's implementation? If so, I think we need to add an unsupported error message in this case.

**Comment by asb** [comment]
I think we want to set a define for this as well, for consistency with medany and medlow (as tested in test/Preprocessor/riscv-cmodel.c). I submitted a trivial PR to riscv-c-api-doc to add this https://github.com/riscv-non-isa/riscv-c-api-doc/pull/86 which I'd hope lands quickly.

**Review by cmuellner — COMMENTED** [review]
What I am missing is:
* adjustments in `clang/lib/Basic/Targets/RISCV.cpp` to emit the macro `__riscv_cmodel_large`
* new tests in `clang/test/Preprocessor/riscv-cmodel.c`

Related PRs:
* https://github.com/riscv-non-isa/riscv-c-api-doc/pull/86
* https://github.com/riscv-non-isa/riscv-toolchain-conventions/pull/59

**Comment by tclin914** [comment]
> What I am missing is:
> 
> * adjustments in `clang/lib/Basic/Targets/RISCV.cpp` to emit the macro `__riscv_cmodel_large`
> * new tests in `clang/test/Preprocessor/riscv-cmodel.c`
> 
> Related PRs:
> 
> * [Add __riscv_cmodel_large define for large code model riscv-non-isa/riscv-c-api-doc#86](https://github.com/riscv-non-isa/riscv-c-api-doc/pull/86)
> * [Add large code model riscv-non-isa/riscv-toolchain-conventions#59](https://github.com/riscv-non-isa/riscv-toolchain-conventions/pull/59)

A follow-up PR #108131 for `__riscv_cmodel_large`

**Review by lenary — APPROVED** [review]
LGTM, on the basis the preprocessor changes are in a different PR.

**Pull request merged**
