### PR TITLE
[SandboxVectorizer][NFC] Remove unused include

### PR DESCRIPTION
**Pull request by Sterling-Augustine**

### CODE REVIEW

**Comment by jplehr** [comment]
I see this error in some of our bots.

```[639/667] Building CXX object unittests/Transforms/Vectorize/SandboxVectorizer/CMakeFiles/SandboxVectorizerTests.dir/SeedCollectorTest.cpp.o
FAILED: unittests/Transforms/Vectorize/SandboxVectorizer/CMakeFiles/SandboxVectorizerTests.dir/SeedCollectorTest.cpp.o 
ccache /usr/bin/c++ -DGTEST_HAS_RTTI=0 -DLLVM_BUILD_STATIC -D_DEBUG -D_GLIBCXX_ASSERTIONS -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/home/botworker/builds/openmp-offload-rhel-8.8-build/llvm.build/unittests/Transforms/Vectorize/SandboxVectorizer -I/home/botworker/builds/openmp-offload-rhel-8.8-build/llvm.src/llvm/unittests/Transforms/Vectorize/SandboxVectorizer -I/home/botworker/builds/openmp-offload-rhel-8.8-build/llvm.build/include -I/home/botworker/builds/openmp-offload-rhel-8.8-build/llvm.src/llvm/include -I/home/botworker/builds/openmp-offload-rhel-8.8-build/llvm.src/third-party/unittest/googletest/include -I/home/botworker/builds/openmp-offload-rhel-8.8-build/llvm.src/third-party/unittest/googlemock/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -Wno-misleading-indentation -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG -std=c++17  -Wno-variadic-macros -fno-exceptions -funwind-tables -fno-rtti -UNDEBUG -Wno-suggest-override -MD -MT unittests/Transforms/Vectorize/SandboxVectorizer/CMakeFiles/SandboxVectorizerTests.dir/SeedCollectorTest.cpp.o -MF unittests/Transforms/Vectorize/SandboxVectorizer/CMakeFiles/SandboxVectorizerTests.dir/SeedCollectorTest.cpp.o.d -o unittests/Transforms/Vectorize/SandboxVectorizer/CMakeFiles/SandboxVectorizerTests.dir/SeedCollectorTest.cpp.o -c /home/botworker/builds/openmp-offload-rhel-8.8-build/llvm.src/llvm/unittests/Transforms/Vectorize/SandboxVectorizer/SeedCollectorTest.cpp
/home/botworker/builds/openmp-offload-rhel-8.8-build/llvm.src/llvm/unittests/Transforms/Vectorize/SandboxVectorizer/SeedCollectorTest.cpp:16:10: fatal error: span: No such file or directory
 #include <span>
          ^~~~~~
compilation terminated.
```

**Comment by Sterling-Augustine** [comment]
That error should be fixed by this PR.

**Comment by jplehr** [comment]
Let me force a clean build then, maybe a ccache glitch. It looked as if the error came from a unit test file not the actual implementation.

**Comment by jplehr** [comment]
Thank you for double checking.

**Comment by jplehr** [comment]
I agree, we are working on it.

**Pull request merged**
