### PR TITLE
Revert "[hwasan] Add fixed_shadow_base flag"

### PR DESCRIPTION
**Pull request by fmayer**
Reverts llvm/llvm-project#73980

This broke static hwasan binaries in Android, for some reason the fixed_shadow_base branch gets taken

### CODE REVIEW

**Review by pirama-arumuga-nainar — APPROVED** [review]

**Comment by vitalybuka** [comment]
@fmayer can you please debug this case. I don't see how that's its possible?

**Comment by vitalybuka** [comment]
My guess __hwasan_init_static() called before initializing flags

**Comment by vitalybuka** [comment]
@thurstond 
I guess it's the issue for stuff which does not use .preinit_array, like Android
Short fix, please reland with `#if NOT ANDROID`
Then, we need to fix flag initialization for android, it should happen for __hwasan_init_static().

**Comment by vitalybuka** [comment]
better `#if SANITIZER_CAN_USE_PREINIT_ARRAY`

**Comment by fmayer** [comment]
I think that's incorrect:

```
#ifndef SANITIZER_CAN_USE_PREINIT_ARRAY
#if (SANITIZER_LINUX || SANITIZER_FUCHSIA || SANITIZER_NETBSD) && !defined(PIC)
#define SANITIZER_CAN_USE_PREINIT_ARRAY 1
// Before Solaris 11.4, .preinit_array is fully supported only with GNU ld.
// FIXME: Check for those conditions.
```

ANDROID is Linnux and does in fact _support_ preinit array, we just don't use it for HWASan.

**Comment by vitalybuka** [comment]
> I think that's incorrect:
> 
> ```
> #ifndef SANITIZER_CAN_USE_PREINIT_ARRAY
> #if (SANITIZER_LINUX || SANITIZER_FUCHSIA || SANITIZER_NETBSD) && !defined(PIC)
> #define SANITIZER_CAN_USE_PREINIT_ARRAY 1
> // Before Solaris 11.4, .preinit_array is fully supported only with GNU ld.
> // FIXME: Check for those conditions.
> ```
> 
> ANDROID is Linnux and does in fact _support_ preinit array, we just don't use it for HWASan.

Is hwasan dynamic lib? if so .preinit_array can not be used

**Comment by fmayer** [comment]
> > I think that's incorrect:
> > ```
> > #ifndef SANITIZER_CAN_USE_PREINIT_ARRAY
> > #if (SANITIZER_LINUX || SANITIZER_FUCHSIA || SANITIZER_NETBSD) && !defined(PIC)
> > #define SANITIZER_CAN_USE_PREINIT_ARRAY 1
> > // Before Solaris 11.4, .preinit_array is fully supported only with GNU ld.
> > // FIXME: Check for those conditions.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > ANDROID is Linnux and does in fact _support_ preinit array, we just don't use it for HWASan.
> 
> Is hwasan dynamic lib? if so .preinit_array can not be used

In this case we are compiling a static binary, so HWASan is not a dynamic lib

**Pull request merged**
