### PR TITLE
[AMDGPU] Fix nondeterminism in SIFixSGPRCopies

### PR DESCRIPTION
**Pull request by jayfoad**
There are a couple of loops that iterate over V2SCopies. The iteration
order needs to be deterministic, otherwise we can call moveToVALU in
different orders, which causes temporary vregs to be allocated in
different orders, which can affect register allocation heuristics.

### CODE REVIEW

**Comment by jayfoad** [comment]
@marekolsak

**Review by Sisyph — COMMENTED** [review]
Can you add a test? I assume it would be a flaky test before this patch, but should pass every time after this patch.

https://llvm.org/docs/ProgrammersManual.html#llvm-adt-mapvector-h
The usage manual recommends removing elements in bulk, since with this container removal is slower. Can you extract the removal at L1043 V2SCopies.erase(C.ID) 
to a removeList and do it a after the loop?

**Comment by jayfoad** [comment]
> https://llvm.org/docs/ProgrammersManual.html#llvm-adt-mapvector-h The usage manual recommends removing elements in bulk, since with this container removal is slower. Can you extract the removal at L1043 V2SCopies.erase(C.ID) to a removeList and do it a after the loop?

I'm not totally comfortable doing that myself because I don't fully understand the first couple of loops in `SIFixSGPRCopies::lowerVGPR2SGPRCopies`, where some items from `V2SCopies` are pushed onto `LoweringWorklist` and then items from `LoweringWorklist` are looked up in `V2SCopies` and potentially removed.

@alex-t could you make the change that @Sisyph requested?

**Comment by marekolsak** [comment]
I'm the original reporter of the bug in AMD's internal issue tracker.

I verify that this resolves the issue, which caused compiled shaders to be randomly influenced by shaders compiled before them.

**Review by arsenm — APPROVED** [review]

**Pull request merged**
