### PR TITLE
[InstCombine] Canonicalize Bit Testing by Shifting to Bit 0

### PR DESCRIPTION
**Pull request by mskamp**
Implement a new transformation that fold the bit-testing expression (icmp ne (and (lshr V B) 1) 0) to (icmp ne (and V (shl 1 B)) 0) for constant V. This rule already existed for non-constant V and constants other than 1; this restriction to non-constant V has been added in commit c3b2111d975a39d19f0c5d635e2961a4449c5a71 to fix an infinite loop. Avoid the infinite loop by allowing constant V only if the shift instruction is an lshr and the constant is 1. Also fold the negated variant of the LHS.
    
This transformation necessitates an adaption of existing tests in `icmp-and-shift.ll` and `load-cmp.ll`. One test in `icmp-and-shift.ll`, which previously was a negative test, now gets folded. Rename it to indicate that it is a positive test.
    
Alive proof: https://alive2.llvm.org/ce/z/vcJJTx
    
Relates to issue #86813.

### CODE REVIEW

**Review by dtcxzyw — APPROVED** [review]
LGTM. Thank you!

**Comment by goldsteinn** [comment]
LGTM

**Review by nikic — APPROVED** [review]
LGTM, but it looks like there is a regression in this case: https://llvm.godbolt.org/z/8dGhf9Wz1

**Comment by mskamp** [comment]
Good point. I think we could adapt the transformation in [InstCombineCasts.cpp:988](https://github.com/llvm/llvm-project/blob/b024fd267b813149f7bd5ba88731673b9a29258d/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp#L988) to also support smaller bit widths (and insert a trunc in this case).

**Comment by nikic** [comment]
> Good point. I think we could adapt the transformation in [InstCombineCasts.cpp:988](https://github.com/llvm/llvm-project/blob/b024fd267b813149f7bd5ba88731673b9a29258d/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp#L988) to also support smaller bit widths (and insert a trunc in this case). I could work on such a change if this is fine.

Sound good to me!

**Pull request merged**
