### PR TITLE
[Clang] [NFC] Migrate visitors in ARCMigrate

### PR DESCRIPTION
**Pull request by Sirraide**
This pr migrates AST visitors in `ARCMigrate` to use `DynamicRecursiveASTVisitor`.

This is part of an ongoing refactor. For more context, see #110040, #93462.

Most of the visitors were fairly simple to migrate, but one that I wasn’t fully able to untangle was `BodyTransform`: For three of its uses, I’ve had to introduce a fairly ugly `bool`, and the last one (`UnbridgedCastRewriter`) simply breaks if I try to refactor it in the same way as the other three (as in, one of the tests keeps failing, and I have no idea what to do about it...). I candidly am not really sure what the problem is w/ that one—it also doesn’t help that I have no understanding whatsoever of ARCMigrate nor of Objective-C.

If you think the way I went about dealing w/ `BodyTransform` is too janky, I can revert those 4 visitors again—most of the other visitors can still be migrated just fine and aren’t affected by that.

### CODE REVIEW

**Comment by Sirraide** [comment]
@rjmccall ping

**Comment by rjmccall** [comment]
Apple actually removed this migrator from Xcode 16. As far as Apple is concerned, this is now dead code, and we intend to open a PR to remove it (but thank you for the prompt!).

**Comment by Sirraide** [comment]
> this is now dead code, and we intend to open a PR to remove it

Alright, in that case, I’ll close this and go ahead and open a PR myself to remove it myself while I’m at it.

**Comment by Sirraide** [comment]
>  we intend to open a PR to remove it

@rjmccall Actually, any idea when that might happen? If not, I can take a look at that too (the only thing is I might miss a few things that we could remove because I’m not really familiar w/ ARCMT).

**Comment by ravikandhadai** [comment]
@Sirraide if you are able to put a patch to remove it, we would happy to review it. Can you please add @ahatanak as a reviewer?

**Pull request closed without merging**
