### PR TITLE
[lldb][test] Fix `LibCxxInternalsRecognizerTestCase` on clang <= 17

### PR DESCRIPTION
**Pull request by vogelsgesang**
We had to disable the tests for libc++ <= 15 because the `std::ranges` functions were not available, yet.

Also, on libc++17 there was still an additional `__fn` struct withing `ranges::__sort`. The test expectation was updated to use a regular expression, so we can match both the old and the new name.

See https://green.lab.llvm.org/job/llvm.org/view/LLDB/job/lldb-cmake-matrix/912/execution/node/107/log/

### CODE REVIEW

**Review by felipepiovezan — APPROVED** [review]
Thanks!

**Comment by Michael137** [comment]
Note that for the clang-15 failure you'll have to make sure we account for inline namespaces in the test assertion

**Comment by Michael137** [comment]
Sorry to clarify. I think based on @felipepiovezan comment here: https://github.com/llvm/llvm-project/pull/108870#issuecomment-2444481588

On Clang 17 we compile fine, just the assertion fails to find the expected function name (because of the `std::__1` inline namespace):
```
FAIL: test_frame_recognizer (TestLibcxxInternalsRecognizer.LibCxxInternalsRecognizerTestCase)
   Test that implementation details of libc++ are hidden
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/llvm-project/lldb/test/API/lang/cpp/libcxx-internals-recognizer/TestLibcxxInternalsRecognizer.py", line 60, in test_frame_recognizer
    self.assertIn(
AssertionError: 'ranges::__sort::operator()' not found in 'std::__1::__wrap_iter<int*> std::__1::ranges::__sort::__fn::operator()[abi:ue170006]<std::__1::__wrap_iter<int*>, std::__1::__wrap_iter<int*>, bool (*)(int, int), std::__1::identity>(std::__1::__wrap_iter<int*>, std::__1::__wrap_iter<int*>, bool (*)(int, int), std::__1::identity) const'
Config=x86_64-/Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/clang_1706_build/bin/clang
```

So really we should skip for <= 15. And fix the assertion for 17+

**Comment by felipepiovezan** [comment]
> Sorry to clarify. I think based on @felipepiovezan comment here: [#108870 (comment)](https://github.com/llvm/llvm-project/pull/108870#issuecomment-2444481588)
> 
> On Clang 17 we compile fine, just the assertion fails to find the expected function name (because of the `std::__1` inline namespace):
> 
> ```
> FAIL: test_frame_recognizer (TestLibcxxInternalsRecognizer.LibCxxInternalsRecognizerTestCase)
>    Test that implementation details of libc++ are hidden
> ----------------------------------------------------------------------
> Traceback (most recent call last):
>   File "/Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/llvm-project/lldb/test/API/lang/cpp/libcxx-internals-recognizer/TestLibcxxInternalsRecognizer.py", line 60, in test_frame_recognizer
>     self.assertIn(
> AssertionError: 'ranges::__sort::operator()' not found in 'std::__1::__wrap_iter<int*> std::__1::ranges::__sort::__fn::operator()[abi:ue170006]<std::__1::__wrap_iter<int*>, std::__1::__wrap_iter<int*>, bool (*)(int, int), std::__1::identity>(std::__1::__wrap_iter<int*>, std::__1::__wrap_iter<int*>, bool (*)(int, int), std::__1::identity) const'
> Config=x86_64-/Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/clang_1706_build/bin/clang
> ```
> 
> So really we should skip for <= 15. And fix the assertion for 17+

Yeah, I'm just now hitting this assertion on our downstream fork tests too

**Comment by vogelsgesang** [comment]
> On Clang 17 we compile fine, just the assertion fails to find the expected function name

good catch! Thanks for staying vigilant

> (because of the std::__1 inline namespace):

I don't think the inline namespace is the issue here.
We are looking for `ranges::__sort::operator()` in `[...] std::__1::ranges::__sort::__fn::operator() [...]`.
The issue seems to be an additional `__fn` wrapper struct

**Comment by vogelsgesang** [comment]
Should be fixed the correct way, now.
@Michael137 @felipepiovezan Would appreciate if you could take another look

**Review by Michael137 — APPROVED** [review]
LGTM thx!

**Review by felipepiovezan — APPROVED** [review]
Awesome, thank you!

**Comment by felipepiovezan** [comment]
@vogelsgesang since I don't know if our timezones align, I am going to take the liberty to click the merge button here to see if we can get the bots green again!

**Comment by felipepiovezan** [comment]
It's interesting that the 17.0 bot is still not happy:

```
  File "/Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 321, in check_value
    test_base.assertEqual(
AssertionError: '"Hello"' != None : Checking child with index 0:
(std::__lldb::optional<const char *>) maybe_string =  Has Value=true  {
  Value = 0x000000010a2f3f9e
}
Checking SBValue: (std::__1::remove_cv_t<value_type>) Value = 0x000000010a2f3f9e
Config=x86_64-/Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/clang_1706_build/bin/clang
```

https://green.lab.llvm.org/job/llvm.org/view/LLDB/job/lldb-cmake-matrix/925/execution/node/135/log/

**Comment by Michael137** [comment]
> It's interesting that the 17.0 bot is still not happy:
> 
> 
> 
> ```
> 
>   File "/Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 321, in check_value
> 
>     test_base.assertEqual(
> 
> AssertionError: '"Hello"' != None : Checking child with index 0:
> 
> (std::__lldb::optional<const char *>) maybe_string =  Has Value=true  {
> 
>   Value = 0x000000010a2f3f9e
> 
> }
> 
> Checking SBValue: (std::__1::remove_cv_t<value_type>) Value = 0x000000010a2f3f9e
> 
> Config=x86_64-/Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/clang_1706_build/bin/clang
> 
> ```
> 
> 
> 
> https://green.lab.llvm.org/job/llvm.org/view/LLDB/job/lldb-cmake-matrix/925/execution/node/135/log/

i think that's a different test though (meant to look into it but havent yet :D )

**Comment by felipepiovezan** [comment]
> > It's interesting that the 17.0 bot is still not happy:
> > ```
> > 
> >   File "/Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/llvm-project/lldb/packages/Python/lldbsuite/test/lldbtest.py", line 321, in check_value
> > 
> >     test_base.assertEqual(
> > 
> > AssertionError: '"Hello"' != None : Checking child with index 0:
> > 
> > (std::__lldb::optional<const char *>) maybe_string =  Has Value=true  {
> > 
> >   Value = 0x000000010a2f3f9e
> > 
> > }
> > 
> > Checking SBValue: (std::__1::remove_cv_t<value_type>) Value = 0x000000010a2f3f9e
> > 
> > Config=x86_64-/Users/ec2-user/jenkins/workspace/llvm.org/lldb-cmake-matrix/clang_1706_build/bin/clang
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > https://green.lab.llvm.org/job/llvm.org/view/LLDB/job/lldb-cmake-matrix/925/execution/node/135/log/
> 
> i think that's a different test though (meant to look into it but havent yet :D )

oh oops, sorry, didn't notice that

**Pull request merged**
