### PR TITLE
[AMDGPU] Properly check op_sel in GCNDPPCombine

### PR DESCRIPTION
**Pull request by mbrkusanin**

### CODE REVIEW

**Review by Sisyph — COMMENTED** [review]
Overall looks great, thanks for fixing it so fast. I think it needs a test to reject formation when DST_OP_SEL is 1, but otherwise LGTM.

**Comment by mariusz-sikora-at-amd** [comment]
> Overall looks great, thanks for fixing it so fast. I think it needs a test to reject formation when DST_OP_SEL is 1, but otherwise LGTM.
I verified the change, we will have tests in these PR https://github.com/llvm/llvm-project/pull/78414
https://github.com/llvm/llvm-project/pull/78414/files#diff-4f33ce09676ec00dd307fa51d99e0277c4e65d89d8996fc9ed419eabbd17fe1fR7

**Comment by mbrkusanin** [comment]
Rebased and added test that has only DST_OP_SEL set to 1.

**Review by Sisyph — APPROVED** [review]
LGTM

**Pull request merged**
