### PR TITLE
[ASan][Windows] Add __cdecl to public sanitizer functions

### PR DESCRIPTION
**Pull request by strega-nil**
This is necessary for many projects which pass `/Gz` to their compiles, which makes their default calling convention `__stdcall`.

(personal note, I _really_ wish there was a pragma for this)

### CODE REVIEW

**Review by mstorsjo — APPROVED** [review]
Functionally, this LGTM.

There's a lot of noise in the PR though, I presume it comes from clang-format wanting to update things and the files not being quite formatted to begin with? I guess that's ok...

I'd appreciate to hear if @vitalybuka has something more to say about it, so I hope you can wait for a day or so, to let him respond in case he has something to say.

**Comment by strega-nil** [comment]
> There's a lot of noise in the PR though, I presume it comes from clang-format wanting to update things and the files not being quite formatted to begin with? I guess that's ok...

yeah, that's exactly what it is; `clang-format` is annoying sometimes :/

**Comment by strega-nil** [comment]
@vitalybuka would you like to take a look at this? Otherwise, I'll merge by tomorrow (2023-10-31T18:00Z)

**Review by vitalybuka — APPROVED** [review]
We use capitalized processor definitions
How about __sanitizer_cdecl -> SANITIZER_CDECL ?

**Comment by AaronBallman** [comment]
I think this change broke one of our bots:
https://lab.llvm.org/buildbot/#/builders/258/builds/8852

Can you investigate the failure?

**Comment by AaronBallman** [comment]
Ping @strega-nil

**Comment by strega-nil** [comment]
@AaronBallman I'm not sure how that happened - it looks like `memprof_interface.h` is maybe including a different `<sanitizer/common_interface_defs.h>` than is actually in main???

**Pull request merged**
