### PR TITLE
[libc] revert all process_mrelease changes

### PR DESCRIPTION
**Pull request by SchrodingerZhu**
Revert as its test is unstable. https://github.com/llvm/llvm-project/issues/118057

### CODE REVIEW

**Comment by SchrodingerZhu** [comment]
@moar55 instead of stacking more fixes, let's just revert the changes. If you have time, could you resubmit this patch and removing all tests but the one testing the invalid argument? As @lntue said, we should not test syscall's correctness in libc's unittests.

**Comment by moar55** [comment]
Sure :)

**Comment by SchrodingerZhu** [comment]
Some buildbots are using old environment, so it is better to guard the tests.

**Comment by nickdesaulniers** [comment]
hmm...bots have been green now for a while...

> Some buildbots are using old environment, so it is better to guard the tests.

I've been meaning to explicitly document that llvm-libc will only support Linux kernel versions listed on kernel.org.  Part of that is ensuring our buildbots are actually running LTS kernels (which I haven't done yet)! If we can move CI to qemu, this makes things simpler as its easier to update qemu than a whole linux distro the buildbot is running.

**Review by nickdesaulniers — APPROVED** [review]
Another failure overnight: https://lab.llvm.org/buildbot/#/builders/171/builds/11699/steps/4/logs/stdio

**Comment by moar55** [comment]
> > @moar55 instead of stacking more fixes, let's just revert the changes. If you have time, could you resubmit this patch and removing all tests but the one testing the invalid argument? As @lntue said, we should not test syscall's correctness in libc's unittests.
> 
> Is this the one you mean with the one testing invalid argument:
> 
> ```
> TEST(LlvmLibcProcessMReleaseTest, ErrorNonExistingPidfd) {
>   EXPECT_THAT(LIBC_NAMESPACE::process_mrelease(-1, 0), Fails(EBADF));
> }
> ```
> 
> ?

@SchrodingerZhu can you respond to this question so I can create a new PR?

**Comment by SchrodingerZhu** [comment]
Yes, it is. Sorry for my late response.

**Pull request merged**
