### PR TITLE
[Modules] Detect ODR mismatches for enums in non-C++ like in C++.

### PR DESCRIPTION
**Pull request by vsapsai**
There is no reason for C and Objective-C to differ from C++ in this matter.

rdar://85531830

### CODE REVIEW

**Review by ChuanqiXu9 — APPROVED** [review]
I have no idea why it was. But the current change looks pretty fine to me.

**Comment by dwblaikie** [comment]
C doesn't have an odr, does it?

**Comment by vsapsai** [comment]
> C doesn't have an odr, does it?

For non-C++ "ODR" has a meaning more like "ODR-inspired checks". But there is no language rule that would require enforcement and there is no impact on linkage (at least during deserialization).

**Comment by dwblaikie** [comment]
> > C doesn't have an odr, does it?
> 
> For non-C++ "ODR" has a meaning more like "ODR-inspired checks". But there is no language rule that would require enforcement and there is no impact on linkage (at least during deserialization).

Not sure I'm following the response here - but I guess what I'm trying to say, with more words, is that my understanding was that C doesn't have an ODR, and you can have different definitions of a type, with the same name, in C and that's OK.

And it sounds like this change makes that not OK in some way? (either by diagnosing/erroring on such divergent types, or assuming they won't diverge and carrying on silently)

**Comment by vsapsai** [comment]
> Not sure I'm following the response here - but I guess what I'm trying to say, with more words, is that my understanding was that C doesn't have an ODR, and you can have different definitions of a type, with the same name, in C and that's OK.

In different translation units you can still use different types with the same name. And you can use enum constant with the same name but different values. It is still OK from the compiler's perspective.

> And it sounds like this change makes that not OK in some way? (either by diagnosing/erroring on such divergent types, or assuming they won't diverge and carrying on silently)

The change is for Clang modules only. In the non-modular world including the same file twice (no header guards, no pragma once) would result in a type redefinition. But with modules it is more likely to find the same type definition in multiple modules. To make the compiler more practical we don't reject such situations. Though we detect when the types aren't identical and don't try to use them interchangeably. The change extends the existing behavior for structs/unions to enums.

If you have use cases when different enums should be used interchangeably, I can see how to accommodate such use cases.

**Comment by vsapsai** [comment]
@dwblaikie if you have no further comments, I'll merge this approved change some time soon (in a day or two).

**Comment by dwblaikie** [comment]
>  Though we detect when the types aren't identical and don't try to use them interchangeably. The change extends the existing behavior for structs/unions to enums.

OK, still a bit confused though - "like in C++", I assume in C++ we reject mismatched types coming from different modules.

But it sounds like in C you're suggesting that we (moreso with this patch) detect mismatches and silently allow different type definitions to work? Which would presumably be the right thing for C.

So, I guess, maybe my concern is only with a confusing title/description...

**Comment by vsapsai** [comment]
In C++ we reject mismatched types coming from different Clang modules. Haven't checked the behavior for C++20 modules as I'm not changing it.

In C modules aren't a part of any standard as far as I know. But for Clang modules we reject most of the mismatched types coming from different modules. The current change extends the set of "most of the mismatched types" to include enums.

**Pull request merged**
