### PR TITLE
[safestack] Various Solaris fixes

### PR DESCRIPTION
**Pull request by rorth**
At the end of the recent flurry of Illumos (and implicitly Solaris) safestack patches, the tests were disabled in
b0260c5b1052f8e3ff1ec77dc42a11f42da762cc without explanation.

After re-enabling them, there were many problems on Solaris:

- Every single testcase failed to link:

  ``` Undefined			first referenced
   symbol  			    in file
  __safestack_unsafe_stack_ptr        buffer-copy-vla.o
  __safestack_init                    (command line)
  ld: fatal: symbol referencing errors
  ```

  The problem is that `-u __safestack_init` was passed to the linker after the corresponding version of `libclang_rt.safestack-*.a`.  Since the Solaris linker (like Unix linkers for decades) respects the command line argument order (unlike e.g. GNU ld which uses GNU getopt), this cannot work.  Fixed by moving the `-u` arg further to the front.  Two affected testcases were adjusted accordingly.

* While 540fd42c755f20f7b79c6c79493ec36d8cb9b3d3 enabled safestack on Solaris unconditionally, it ignored that Solaris also exists on SPARC and forgot to enable SPARC support.  This patch fixes that.

- Afterwards, the tests still fail to link with undefined references to `__sanitizer_internal_memset` etc.  These are from `sanitizer_redefine_builtins.h`.  Definitions live in `sanitizer_libc.cpp.o` and were added to the safestack runtime lib as is already the case e.g. for asan and ubsan.  Why GNU ld allows the link to complete with those symbols undefined is beyond me.

- The `pthread*.c` tests `FAIL` with

  ``` safestack CHECK failed: /vol/llvm/src/llvm-project/local/compiler-rt/lib/safestack/safestack.cpp:227 size ```

  The problem is that `pthread_attr_init` initializes the `stacksize` attribute to 0, signifying the default.  Unless explicitly overridded, it stays that way.  I think this is allowed by XPG7.  Since safestack cannot deal with this, I set `size` to the defaults documented in `pthread_create(3C)`.  Unfortunately, there's no macro for those values outside of private `libc` headers.

- The Solaris `syscall` interface isn't stable.  This is not just a theoretical concern, but the syscalls have changed incompatibly several times in the past.  Therefore this patch switches the implementations of `TgKill` (where `SYS_lwp_kill` doesn't exist on Solaris 11.4 anyway), `Mmap`, `Munmap`, and `Mprotect` to the same `_REAL*` solution already used in `sanitizer_solaris.cpp`.  Instead of duplicating what's already in `sanitizer_common`, it seems way better to me to just reuse those implementations, though.  A subsequent patch does just that.

With those changes, safestack compiles and all tests `PASS`.

Tested on `amd64-pc-solaris2.11`, `sparcv9-sun-solaris2.11`, `x86_64-pc-linux-gnu`, and `sparc64-unknown-linux-gnu`.

### CODE REVIEW

**Comment by rorth** [comment]
The mentioned patch to switch safestack to use the `sanitizer_common` functions instead of their own ones in `sanitizer_platform.h` has to wait until this one is approved: AFAIT github doesn't support stacked pull requests.

**Comment by rorth** [comment]
> ⚠️ C/C++ code formatter, clang-format found issues in your code. ⚠️
> You can test this locally with the following command:
> View the diff from clang-format here.
> 
> ```diff
> diff --git a/compiler-rt/lib/safestack/safestack_platform.h b/compiler-rt/lib/safestack/safestack_platform.h
> index 77eeb9cda6..27e29d6ead 100644
> --- a/compiler-rt/lib/safestack/safestack_platform.h
> +++ b/compiler-rt/lib/safestack/safestack_platform.h
> @@ -13,9 +13,6 @@
>  #ifndef SAFESTACK_PLATFORM_H
>  #define SAFESTACK_PLATFORM_H
>  
> -#include "safestack_util.h"
> -#include "sanitizer_common/sanitizer_platform.h"
> -
>  #include <dlfcn.h>
>  #include <errno.h>
>  #include <stdint.h>
> @@ -26,6 +23,9 @@
>  #include <sys/types.h>
>  #include <unistd.h>
>  
> +#include "safestack_util.h"
> +#include "sanitizer_common/sanitizer_platform.h"
> +
>  #if !(SANITIZER_NETBSD || SANITIZER_FREEBSD || SANITIZER_LINUX || \
>        SANITIZER_SOLARIS)
>  #  error "Support for your platform has not been implemented"
> ```

I had seen that when running `clang-format-diff.py`, but chose to ignore that because it seems unrelated and even somewhat dangerous: there are often cases where you need to define some macro **before** including system headers.

**Comment by devnexen** [comment]
you do not need to worry I won t do any illumos/solaris work anytime soon, feel free to do xray port and all the rest.

**Comment by MaskRay** [comment]
> At the end of the recent flurry of Illumos (and implicitly Solaris) safestack patches, the tests were disabled in
> [b0260c5](https://github.com/llvm/llvm-project/commit/b0260c5b1052f8e3ff1ec77dc42a11f42da762cc) without explanation.

@devnexen  Thank you for #97183, which seemed to addressed a real issue, but make sure to include descriptions in the future.

**Comment by vitalybuka** [comment]
They look quite independent. 
Would be possible to split independent fixed into a separate patches?

**Comment by rorth** [comment]
> They look quite independent. Would be possible to split independent fixed into a separate patches?

With the exception of the `-u` reordering, they are all Solaris-only, so I kept them together to avoid tons of micro-patches.  I certainly could split them if you prefer, something like
- `-u` reordering
- sparc enabling
- add `sanitizer_common` objects
- `pthread stacksize` quirk
- fix `TgKill`
- switch syscalls to `_REAL*`
- re-enable testing

Just let me know.

**Comment by vitalybuka** [comment]
> * `-u` reordering

-u Must have own patch

The rest is up to you. Usually small fixes easier to bisect/revert, but it's less important if it's completely broken yet.

**Review by vitalybuka — APPROVED** [review]
LGTM if you extract Driver and update description accordingly.

**Comment by MaskRay** [comment]
> The problem is that -u __safestack_init was passed to the linker after the corresponding version of libclang_rt.safestack-*.a. Since the Solaris linker (like Unix linkers for decades) respect

I agree this part should be extracted since it affects other systems. Other parts are Solaris specific and since the support is currently broken, it is safe to combine changes.

**Review by MaskRay — APPROVED** [review]

**Comment by rorth** [comment]
> > The problem is that -u __safestack_init was passed to the linker after the corresponding version of libclang_rt.safestack-*.a. Since the Solaris linker (like Unix linkers for decades) respect
> 
> I agree this part should be extracted since it affects other systems. Other parts are Solaris specific and since the support is currently broken, it is safe to combine changes. We also don't have Solaris build bots, so the change, if correctly restricted to Solaris, would not cause any problems.

We sure have Solaris buildbots, both [Solaris/sparcv9](https://lab.llvm.org/buildbot/#/builders/13) and [Solaris/amd64](https://lab.llvm.org/staging/#/builders/94).

Actually, two parts of the patch do affect non-Solaris targets:
- The SPARC enablement, which is covered by Linux/sparc64 testing, and
- adding some (otherwise unused) `sanitizer_common` objects to `libclang_rt.safestack-*.a`.  This was tested on both Linux/x86_64 and Linux/sparc64, and I'm resonably certain that unused objects in an archive lib won't affect other targets.

**Comment by rorth** [comment]
Dropped; superceded by [[clang][Driver] Fix safestack -u ordering](https://github.com/llvm/llvm-project/pull/98468) and [[safestack] Various Solaris fixes](https://github.com/llvm/llvm-project/pull/98469).

**Pull request closed without merging**
