### PR TITLE
[libc++] Add output groups to run-buildbot

### PR DESCRIPTION
**Pull request by EricWF**
This improves the CI output by providing collapsable sections for sub-parts of our build.

### CODE REVIEW

**Comment by ldionne** [comment]
Can you explain what this does (perhaps in the commit message)? I imagine this improves the CI output? That would be nice!

**Comment by ldionne** [comment]
I looked at the CI output and this seems really desirable. It looks like we could also avoid using `set -x` in a few places to increase readability a lot. Do you have interest in pursuing this patch or should someone else pick it up?

**Comment by philnik777** [comment]
@ldionne @EricWF does either of you plan to pick this up again? If not, let's close the PR for now (or make it a draft).

**Comment by ldionne** [comment]
Crap, I don't have permission to push to this branch to pick it up. I'll close this and reopen a PR.

**Pull request closed without merging**
