### PR TITLE
[llvm][CodeGen] Address the issue of multiple resource reservations In window scheduling

### PR DESCRIPTION
**Pull request by kaiyan96**
Address the issue of multiple resource reservations in window scheduling.

### CODE REVIEW

**Comment by arsenm** [comment]
You generally don't need to open a new PR for reapply, but if you do preferably the diff from the first PR would be the second commit

**Review by arsenm — APPROVED** [review]

**Comment by RSilicon** [comment]
Is this something that we should backport to 19.x?

**Comment by huaatian** [comment]
> Is this something that we should backport to 19.x?

I think it's better to backport to 19.x.

**Comment by kaiyan96** [comment]
> Is this something that we should backport to 19.x?

We have following bugfixes for window scheduler, do we need submit them by ourselves?
* (Added a new restriction for II by pragma in window scheduler)[https://github.com/llvm/llvm-project/pull/99448]
* (Fixed a bug in stall cycle calculation for window scheduler)[https://github.com/llvm/llvm-project/pull/99451]
* (Added missing initialization failure information for window scheduler)[https://github.com/llvm/llvm-project/pull/99449]
* (Fixed max cycle calculation with zero-cost instructions for window scheduler )[https://github.com/llvm/llvm-project/pull/99454]
* (Address the issue of multiple resource reservations In window scheduling)[https://github.com/llvm/llvm-project/pull/101665]

**Pull request merged**
