### PR TITLE
[libc] finish documenting c23 additions

### PR DESCRIPTION
**Pull request by nickdesaulniers**
- [libc] finish documenting c23 additions
- sort according to appearance in Annex B and section 7

### CODE REVIEW

**Comment by nickdesaulniers** [comment]
Note to reviewers, it might be helpful to review this PR commit by commit. The final commit is just a sort.

**Comment by SchrodingerZhu** [comment]
Could help mark memset_explicit as checked?

**Comment by nickdesaulniers** [comment]
> Could help mark memset_explicit as checked?

Good idea!
https://github.com/llvm/llvm-project/pull/84383/commits/453a4737ef0505832660c55652392dda93d823b8

**Review by SchrodingerZhu — APPROVED** [review]
LGTM

**Pull request merged**
