### PR TITLE
[clang-scan-deps] Infer the tool locations from PATH

### PR DESCRIPTION
**Pull request by mstorsjo**
This allows the clang driver to know which tool is meant to be executed, which allows the clang driver to load the right clang config files, and allows clang to find colocated sysroots.

This makes sure that doing `clang-scan-deps -- <tool> ...` looks up things in the same way as if one just would execute `<tool> ...`, when `<tool>` isn't an absolute or relative path.

### CODE REVIEW

**Comment by jansvoboda11** [comment]
Can you explain why exactly is this necessary/beneficial? If the compilation database got created with just the tool name, I'd expect the rest of the build to be able to use just the tool name when the scanner spits it out again, no? If this is about the scanner finding the right config, sysroot, resource directory, etc., I'd expect that to already happen, since the scanner needs to be colocated with the toolchain itself (since `clang` and `clang-scan-deps` are effectively version-locked).

**Comment by mstorsjo** [comment]
> Can you explain why exactly is this necessary/beneficial? If the compilation database got created with just the tool name, I'd expect the rest of the build to be able to use just the tool name when the scanner spits it out again, no? If this is about the scanner finding the right config, sysroot, resource directory, etc., I'd expect that to already happen, since the scanner needs to be colocated with the toolchain itself (since `clang` and `clang-scan-deps` are effectively version-locked).

It's about the scanner finding the right config files and sysroot.

Even if `clang-scan-deps` is colocated with the toolchain, the tool never assumes that. Normally when you invoke `clang` to compile, it sets the executable directory so that within the `clang::Driver` class, `Dir` points to where clang resides.

Now when `clang-scan-deps` inspects one or more `clang` tool invocations, the `clang::Driver` class never gets set up with the `Dir` of the `clang-scan-deps` executable - it only sets things based on what it literally sees in the command lines, without any outside assumptions about default directory.

**Comment by mstorsjo** [comment]
And practically - in the cases I've seen where CMake generates calls to `clang-scan-deps`, it always invokes `clang-scan-deps ... -- /absolute/path/to/compiler` (CMake in general is very keen on absolute paths to tools).

But in separate testing of these tools, I ran into this situation, where `<triple>-clang ...` works and picks up the `<triple>.cfg` config file next to the `<triple>-clang` executable, and finds the colocated sysroot. But when invoking `clang-scan-deps -- <triple>-clang`, where `clang-scan-deps` itself is colocated with the `<triple>-clang` binary, it didn't find the config file nor the sysroot.

**Comment by jansvoboda11** [comment]
Ok, thanks for the explanation. This LGTM, but the checks are failing on Windows due to `.exe` extension that's not accounted for. I don't think any of the tests you touched really care about the executable path, so I'd be fine with just removing those check lines.

**Comment by mstorsjo** [comment]
> Ok, thanks for the explanation. This LGTM, but the checks are failing on Windows due to `.exe` extension that's not accounted for. I don't think any of the tests you touched really care about the executable path, so I'd be fine with just removing those check lines.

Ah, thanks. Yeah it's probably best that we remove those checks that don't carry much relevance there. (The main test that really exercise this functionality, that I'm adding here, has a `UNSUPPORTED: system-windows` marking due to using symlinks for setting up the `PATH` test environment though. But that's only an issue with the test - the implementation seems to work fine regardless, as noted when the other tests fail.)

**Review by jansvoboda11 — APPROVED** [review]

**Pull request merged**
