### PR TITLE
[X86] Enable constexpr on LZCNT & BMI intrinsics

### LINKED ISSUE #86128: [X86] Enable constexpr on LZCNT and BMI intrinsics
The x86 specific LZCNT and BMI intrinsics in lzcntintrin.h and bmiintrin.h are all capable of being converted to constexpr

We did something similar for the POPCNT intrinsics here: https://reviews.llvm.org/D86229 / cff0db08761f310dfebb5b41b307d2c12bda85fc

- [x] Update `__builtin_ia32_*` intrinsics to allow handling in ExprConstant
- [x] Update headers - ensuring they work for c, pre-C++11 and later C++ builds
- [x] Test coverage - including the macro variants of some of the methods (e.g. `_tzcnt_u32` for `__tzcnt_u32`)

### PR DESCRIPTION
**Pull request by aniplcc**
Closes  #86128.

### CODE REVIEW

**Comment by aniplcc** [comment]
forgot to update ExprConstant with builtins

**Comment by RKSimon** [comment]
@aniplcc reverse ping

**Comment by RKSimon** [comment]
@aniplcc reverse ping

**Comment by RKSimon** [comment]
@aniplcc reverse ping?

**Comment by RKSimon** [comment]
@aniplcc Are you still wanting to work on this? Otherwise I'd like to commandeer and complete the patch to get it into trunk.

**Comment by RKSimon** [comment]
Closing as these have now all been addressed

**Pull request closed without merging**
