### PR TITLE
[RISCV] Restrict when we fold an ADD_LO into a load/store address.

### PR DESCRIPTION
**Pull request by topperc**
Don't fold if there are loads/stores that use the ADD_LO with a non-zero immediate offset that can't be folded based on alignment.

This avoids cases where some loads/stores use the LUI directly and other loads/store uses the result of an ADDI that depends on the LUI.

This increases the latency to the load that we no longer fold, but reduces the need for a temporary register to hold the LUI result for multiple uses.

This is preparation for introducing a rematerializable LUI+ADDI pseudoinstruction.

Co-authored-by: Jesse Huang <jesse.huang@sifive.com>

### CODE REVIEW

**Review by dtcxzyw — APPROVED** [review]
LGTM.

**Comment by wangpc-pp** [comment]
> This is preparation for instroducing a rematerializable LUI+ADDI pseudoinstruction.

**Comment by preames** [comment]
I think I'm missing something here.  This doesn't seem like a profitable transform, and I'm not understanding why it is required for the pseudo.  I get that we'd have two values live through regalloc (the lui and the lui/addi pseudo), but is the impact really that bad?  That seems analogous to what we have now?

**Comment by topperc** [comment]
> I think I'm missing something here.  This doesn't seem like a profitable transform, and I'm not understanding why it is required for the pseudo.  I get that we'd have two values live through regalloc (the lui and the lui/addi pseudo), but is the impact really that bad?  That seems analogous to what we have now?

We end up with 2 LUIs after the pseudo gets expanded. They won't get CSEd since we are post regalloc at that point. I'll post a version of the patch without this and we can decide.

**Pull request closed without merging**
