### PR TITLE
Add host-supports-nvptx requirement to lit tests

### PR DESCRIPTION
**Pull request by frgossen**

### CODE REVIEW

**Comment by frgossen** [comment]
Windows failure seems unrelated.

**Review by olegshyshkov — APPROVED** [review]

**Review by joker-eph — CHANGES_REQUESTED** [review]
These tests are already gated by the need of a GPU available in `mlir/test/Integration/GPU/CUDA/lit.local.cfg`, `mlir/test/Integration/Dialect/SparseTensor/GPU/CUDA/lit.local.cfg`, `mlir/test/Integration/Dialect/Vector/GPU/CUDA/lit.local.cfg`, so I don't quite get why this is needed right now?

**Comment by frgossen** [comment]
IIUC, we are not using these files internally, so the argument would be similar to the comments in `SparseTensor/CPU/concatenate_dim_0_permute.mlir` and friends. If you would prefer to undo this change, I can probably disable the tests in some other way, too.

**Comment by joker-eph** [comment]
We likely don't want to maintain redundant information in the tests upstream: so I think it makes sense to revert and try to consolidate with a unified strategy.
(We're not supporting "non-lit compatible" runners really)

**Comment by frgossen** [comment]
https://github.com/llvm/llvm-project/pull/66225

**Comment by frgossen** [comment]
Rolling it back and fixing it internally

**Pull request merged**
