### PR TITLE
[libclang/python] Expose Rewriter to the python binding

### PR DESCRIPTION
**Pull request by jimmy-zx**
Exposes `CXRewriter` API to the python binding as `class Rewriter`.

### CODE REVIEW

**Comment by jimmy-zx** [comment]
Pinging @AaronBallman and @jyknight for review. (sorry if I chose the wrong people)

**Review by AaronBallman — COMMENTED** [review]
The changes look reasonable to me as far as they go, but I don't have much expertise in Python. I added @Endilll to hopefully help give it a second set of eyes.

You should add a release note (clang/docs/ReleaseNotes.rst) about the new bindings so others know that they've been improved.

**Review by Endilll — COMMENTED** [review]
Looks good overall.
It's good that you wrote your own tests, but it would also be nice to mirror tests in `clang/unittests/libclang/LibclangTest.cpp` which test the same API. This way we can identify issues in binding layer itself (when C++ tests pass, but Python tests don't, or vise versa)

**Comment by jimmy-zx** [comment]
> Looks good overall. It's good that you wrote your own tests, but it would also be nice to mirror tests in `clang/unittests/libclang/LibclangTest.cpp` which test the same API. This way we can identify issues in binding layer itself (when C++ tests pass, but Python tests don't, or vise versa,)

I have reviewed the tests for libclang and it appears that there are already tests for the rewriter, which are more extensive than the ones I wrote. Therefore, I have decided to mirror the tests from libclang in the Python binding. Please let me know if this approach is appropriate.

**Comment by Endilll** [comment]
> I have reviewed the tests for libclang and it appears that there are already tests for the rewriter, which are more extensive than the ones I wrote. Therefore, I have decided to mirror the tests from libclang in the Python binding. Please let me know if this approach is appropriate.

If you think that existing tests fully cover yours, then it's appropriate. Otherwise, we'd benefit from additional test coverage, but it's not necessarily in the scope of this PR.

**Comment by jimmy-zx** [comment]
Both tests are just invoking the functionalities of the rewriter on a sample code. I think additional tests for libclang does not provide extra coverage (as it is just the front-end). Thus I mirrored the tests back to the Python binding in 7a4ebf9c8c9ffa29d7f7f863d9a19bfe53432348.

**Review by Endilll — APPROVED** [review]
LGTM
PR description is going to become a commit message after merging. Let me know when it's ready.

**Comment by jimmy-zx** [comment]
Just updated the description a bit and I believe it's all set for merging.

**Comment by linux4life798** [comment]
Hi all, sorry for jumping in late. Minor nit here.

It looks like this change is introducing camelCase methods, but the majority of the existing Python file uses snake_case, even though the underlying libclang interface is camelCase. For consistency, can we make these interface functions snake_case or is there some overriding style guide that wants camelCase?

**Comment by jimmy-zx** [comment]
@linux4life798 Thanks for pointing out! I've updated the naming to conform snake_case.

**Comment by linux4life798** [comment]
Thanks!

**Comment by Endilll** [comment]
@linux4life798 Nice catch! I see that so far only `CompilationDatabase` and `CompletionChunk` expose functions in camelCase. It would be nice to change them, too, but those are decade-old APIs that _I think_ we promise stability for, so it might not be possible.

**Comment by linux4life798** [comment]
> @linux4life798 Nice catch! I see that so far only CompilationDatabase and CompletionChunk expose functions in camelCase. It would be nice to change them, too, but those are decade-old APIs that I think we promise stability for, so it might not be possible.

Yep. Of course unrelated to this change, we might be able to add the snake_case equivalent binding and marking the old ones as depreciated.

**Comment by linux4life798** [comment]
I don't think this needs to block this change, but another concern I have about this API is that it is writing to stdout from C++ intermixed with Python writing to its own buffered stdout. This means that the user may see inconsistent output. This is somewhat a deficiency of [libclang Rewrite API](https://clang.llvm.org/doxygen/Rewrite_8h.html), since there is only one specific function to "write the main file out" and that is through stdout.

In an attempt to keep the world consistent, we may want to consider flushing the Python stdout buffer (`sys.stdout.flush()`) before calling `clang_CXRewriter_writeMainFileToStdOut`. I would hope that `clang_CXRewriter_writeMainFileToStdOut` flushes its own C++ stdout buffer after writing the file contents, but I honestly haven't looked at the code.

**Comment by Endilll** [comment]
@linux4life798 Do you mind filing issues for the points you highlighted? Feel free to skip this step if you (or someone else) plan to submit PRs that address them.

**Comment by jimmy-zx** [comment]
Added flush before calling `writeMainFileToStdOut`.

Personally I didn't find this function particularly useful: I was hoping to perform rewriting without creating new files, but seems like capturing stdout from a shared library requires some complex operation (`dup2` stuff).

`Rewriter::getRewrittenText()` might be a more interesting interface to interact with, which returns the rewritten content as a string. (This is defined in clang but not exposed by libclang yet).

https://github.com/llvm/llvm-project/blob/179ba129f50aefe6e670800aec7091d958aa6f90/clang/lib/Rewrite/Rewriter.cpp#L180

**Comment by Endilll** [comment]
@linux4life798 Can you review the last update?

**Comment by linux4life798** [comment]
> Added flush before calling `writeMainFileToStdOut`.

I think that's reasonable.

> Personally I didn't find this function particularly useful: I was hoping to perform rewriting without creating new files, but seems like capturing stdout from a shared library requires some complex operation (`dup2` stuff).
> 
> `Rewriter::getRewrittenText()` might be a more interesting interface to interact with, which returns the rewritten content as a string. (This is defined in clang but not exposed by libclang yet).
> 
> https://github.com/llvm/llvm-project/blob/179ba129f50aefe6e670800aec7091d958aa6f90/clang/lib/Rewrite/Rewriter.cpp#L180

I agree. This should probably be exposed to libclang (and then to this python binding).

**Comment by linux4life798** [comment]
> @linux4life798 Can you review the last update?

This change LGTM (I don't actually have reviewer rights).

**Comment by jimmy-zx** [comment]
Ping. Can one of you press the merge button?

**Pull request merged**
