### PR TITLE
[libc++] Fix broken configuration system-libcxxabi on Apple

### LINKED ISSUE #104672: [libc++] `-DLIBCXX_CXX_ABI=system-libcxxabi` not usable?
I recently noticed https://github.com/llvm/llvm-project/commit/ba4f1e44e480d661d99973007a39dc642f5d79a4, which is exactly the kind of build we need to do for our [distribution](https://conda-forge.org) for various reasons. I've [tried](https://github.com/conda-forge/libcxx-feedstock/pull/177) this with LLVM 18.1.8 and 19.1.0-rc2, but in both cases, I get
```
-- Configuring done (25.4s)
CMake Error at $SRC_DIR/libcxx/cmake/Modules/HandleLibCXXABI.cmake:59 (add_library):
  No SOURCES given to target: libcxx-abi-headers-generate-private-headers
Call Stack (most recent call first):
  $SRC_DIR/libcxx/cmake/Modules/HandleLibCXXABI.cmake:135 (import_private_headers)
  $SRC_DIR/libcxx/CMakeLists.txt:511 (include)
```

Our build invocation roughly boils down to the following (removed some uninteresting things, but happy to elaborate);
```
cmake -G Ninja -B build -S runtimes \
    -DLLVM_ENABLE_RUNTIMES=libcxx;libcxxabi;libunwind \
    -DCMAKE_INSTALL_PREFIX=$PREFIX \
    -DCMAKE_BUILD_TYPE=Release \
    -DLIBCXX_ENABLE_TIME_ZONE_DATABASE=ON \
    -DLIBCXX_INCLUDE_BENCHMARKS=OFF \
    -DLIBCXX_INCLUDE_DOCS=OFF \
    -DLIBCXX_INCLUDE_TESTS=OFF \
    -DLIBCXX_HARDENING_MODE=none \
    -DLIBCXXABI_USE_LLVM_UNWINDER=OFF \
    -DLLVM_ENABLE_PER_TARGET_RUNTIME_DIR=OFF \
    -DCMAKE_OSX_DEPLOYMENT_TARGET=10.13 \
    -DLIBCXX_ENABLE_VENDOR_AVAILABILITY_ANNOTATIONS=ON \
    -DLIBCXX_CXX_ABI=system-libcxxabi

ninja -C build cxx cxxabi unwind
```

I've tried removing `libcxxabi` from `-DLLVM_ENABLE_RUNTIMES=` (and the build invocation) though the result stays the same.

CC @ldionne @mgorny

### PR DESCRIPTION
**Pull request by ldionne**
On Apple platforms, using system-libcxxabi as an ABI library wouldn't work because we'd try to re-export symbols from libc++abi that the system libc++abi.dylib might not have. Instead, only re-export those symbols when we're using the in-tree libc++abi.

This does mean that libc++.dylib won't re-export any libc++abi symbols when building against the system libc++abi, which could be fixed in various ways. However, the best solution really depends on the intended use case, so this patch doesn't try to solve that problem.

As a drive-by, also improve the diagnostic message when the user forgets to set the LIBCXX_CXX_ABI_INCLUDE_PATHS variable, which would previously lead to a confusing error.

Closes #104672

### CODE REVIEW

**Comment by ldionne** [comment]
@h-vetinari It would be great if you can let me know whether this solves your problem

**Comment by h-vetinari** [comment]
> @h-vetinari It would be great if you can let me know whether this solves your problem

Thanks a lot for this, I'll test this and get back to you! 🙏

**Comment by h-vetinari** [comment]
So I'm trying this in https://github.com/conda-forge/libcxx-feedstock/pull/177, and I'm getting
```
+ llvm-nm $PREFIX/lib/libc++.1.dylib
dyld[11925]: Symbol not found: __ZTVN10__cxxabiv117__class_type_infoE
  Referenced from: <5D911EBA-4AB2-3C92-B9D5-977E209853B5> $PREFIX/bin/llvm-nm-18
  Expected in:     <E516FB63-086F-3A12-B5C7-A0FD4F00B3EA> $PREFIX/lib/libc++.1.0.dylib
compile_test.sh: line 12: 11925 Abort trap: 6           llvm-nm $PREFIX/lib/libc++.1.dylib
```

It's plausible/possible that this is a behavioural difference between our current workaround to depend on the system libcxxabi and doing it "properly". In particular, the `llvm-nm` binary that's in use for testing _after_ successful compilation was built[^1] against the "current world" of our libcxx handling, which does [roughly](https://github.com/conda-forge/libcxx-feedstock/blob/main/recipe/build.sh):
```bash
ninja -C build cxx cxxabi unwind
ninja -C build install-cxx install-cxxabi install-unwind
$INSTALL_NAME_TOOL -change "@rpath/libc++abi.1.dylib" "/usr/lib/libc++abi.dylib" $PREFIX/lib/libc++.1.0.dylib
```
I'm aware that this is fragile (and we do carry a patch for systems before macOS 12 due to ABI differences), but it's what we had to move to, because the system libcxxabi gets picked up in some situations (e.g. from CPython, see README [here](https://github.com/conda-forge/libcxx-testing-feedstock/tree/main/recipe/pybind11_exception_rtti_test)).

[^1]: For various reasons we do rely on shared libraries wherever possible. Meaning that `llvm-nm` itself depends on `libc++`, and when we build a new `libc++`, the existing builds of `llvm-nm` should keep working seamlessly if their `libc++` gets updated underneath them. This is where we're now falling over, i.e. it'd be a kind of ABI break for us -- assuming this isn't due to a bug somehow.

IOW, it's conceivable to me that (re)building everything in a `-DLIBCXX_CXX_ABI=system-libcxxabi` world would work out fine. For now though I'm not sure how a cxxabi symbol ends up in `libc++.1.0.dylib` (using the script above) but we'd have to fix that somehow to ensure stuff doesn't break if/when we switch.

CC @isuruf

**Comment by h-vetinari** [comment]
OK, rereading your comment from https://github.com/llvm/llvm-project/issues/104672
> However, note that even when you do that, now the build is going to start trying to re-export a list of libc++abi symbols from libc++, and obviously that only works if your system ABI library is sufficiently recent to have all of those symbols. It's kind of a brittle setup.

now makes more sense. The thing I don't yet get is how things are working for us in the current setup; presumably the fact that the libcxxabi symbols don't get re-exported through our workaround helps.

**Comment by ldionne** [comment]
> So I'm trying this in [conda-forge/libcxx-feedstock#177](https://github.com/conda-forge/libcxx-feedstock/pull/177), and I'm getting
> 
> ```
> + llvm-nm $PREFIX/lib/libc++.1.dylib
> dyld[11925]: Symbol not found: __ZTVN10__cxxabiv117__class_type_infoE
>   Referenced from: <5D911EBA-4AB2-3C92-B9D5-977E209853B5> $PREFIX/bin/llvm-nm-18
>   Expected in:     <E516FB63-086F-3A12-B5C7-A0FD4F00B3EA> $PREFIX/lib/libc++.1.0.dylib
> compile_test.sh: line 12: 11925 Abort trap: 6           llvm-nm $PREFIX/lib/libc++.1.dylib
> ```


How was `$PREFIX/lib/libc++.1.0.dylib` built? Presumably it was built in a way that it advertised the presence of symbol `__ZTVN10__cxxabiv117__class_type_infoE`, which is the only way the linker would have encoded that dependency in `llvm-nm-18`.

------------------

Another thing you could try on the side is to re-export `libc++abi.dylib` itself from `libc++.dylib` instead of the list of its symbols. There's a fundamental problem with re-exporting the list of libc++abi symbols that otherwise can't be solved when building against the system libc++abi: we don't know what version of the system libc++abi you're building against, so we don't know the list of symbols. And even if we knew the version of libc++abi you're building against, we'd have to maintain a mapping of every historical `libc++abi.dylib` that was shipped to the list of symbols it contained in order to make that happen.

**Comment by ldionne** [comment]
I'm going to ship this since it does improve some of the story for this configuration, even though the question of how to properly re-export symbols from the system libc++abi isn't resolved yet.

**Comment by h-vetinari** [comment]
Sorry for the delayed response! I was planning to get to this but not fast enough apparently 😅 

> There's a fundamental problem with re-exporting the list of libc++abi symbols that otherwise can't be solved when building against the system libc++abi: we don't know what version of the system libc++abi you're building against, so we don't know the list of symbols.

Not sure I understand 100%, but in our case the system ABI has a clear lower bound and we know it at build-time (currently 10.13 on osx-64, 11.0 on osx-arm64).

> And even if we knew the version of libc++abi you're building against, we'd have to maintain a mapping of every historical `libc++abi.dylib` that was shipped to the list of symbols it contained in order to make that happen.

This might be naïve, but can't we just start by relying on the availability of symbols from the lower-bound system ABI? This is effectively what we're doing already. If we're building on 10.13, we require (through our package metadata that drives whether an artefact can be installed) that the resulting package can only be installed on macOS>=10.13. That has worked for a long time already, and didn't need a full mapping.

> How was `$PREFIX/lib/libc++.1.0.dylib` built?

I had pasted the essence of the build script above; here's the [link](https://github.com/conda-forge/libcxx-feedstock/blob/main/recipe/build.sh) to the full thing again.

> Presumably it was built in a way that it advertised the presence of symbol `__ZTVN10__cxxabiv117__class_type_infoE`, which is the only way the linker would have encoded that dependency in `llvm-nm-18`.

That sounds very plausible, but it needs to be happening essentially by default, because I'm not actively choosing to re-export the libcxxabi symbols (I would have wanted to avoid that, had I known).

**Comment by mgorny** [comment]
Do you think it would be possible to backport this fix into 19.x?

**Comment by ldionne** [comment]
@mgorny I don't think there are any releases planned for LLVM 19 anymore

**Comment by mgorny** [comment]
Well, my point was for 19.1.4, but I guess that ship just sailed.

**Comment by h-vetinari** [comment]
FWIW, there are still releases happening for 19.x, so this could still be backported.

**Comment by mgorny** [comment]
I think it were:

```
commit ec2e1cae2c6330cd1e3b7f580702f1949827899a
Author:     Louis Dionne <ldionne.2@gmail.com>
AuthorDate: 2024-10-09 14:46:59 +0200
Commit:     Tobias Hieta <tobias@hieta.se>
CommitDate: 2024-11-18 17:01:02 +0100

    [libc++] Fix broken configuration system-libcxxabi on Apple (#110920)
    
    On Apple platforms, using system-libcxxabi as an ABI library wouldn't
    work because we'd try to re-export symbols from libc++abi that the
    system libc++abi.dylib might not have. Instead, only re-export those
    symbols when we're using the in-tree libc++abi.
    
    This does mean that libc++.dylib won't re-export any libc++abi symbols
    when building against the system libc++abi, which could be fixed in
    various ways. However, the best solution really depends on the intended
    use case, so this patch doesn't try to solve that problem.
    
    As a drive-by, also improve the diagnostic message when the user forgets
    to set the LIBCXX_CXX_ABI_INCLUDE_PATHS variable, which would previously
    lead to a confusing error.
    
    Closes #104672
    
    (cherry picked from commit 21da4e7f51c7adfd0b1c5defc8bd0d16ea1ce759)
```

**Comment by h-vetinari** [comment]
Yeah, I noticed when rebasing on 19.1.6! Just didn't see an xref when I looked at the PR again (well, except the little ones for commits that often happen spuriously, so I didn't look closely enough). Sorry for the noise.

**Comment by mgorny** [comment]
No problem. Just were worried the fix was insufficient for you.

**Pull request merged**
