### PR TITLE
[clang][ci] Remove unnecessary BuildKite jobs for Clang

### PR DESCRIPTION
**Pull request by ldionne**
1. Remove the format-checking job from the BuildKite pipeline. We now have a monorepo-wide format checker implemented with Github Actions, so that should not be necessary anymore.

2. Stop building and testing Clang on Windows via the clang-ci pipeline. We already do that in the github-pull-requests pipeline, so that's just duplicate work.

3. Stop testing Clang on Linux in the clang-ci pipeline. We already do that in the github-pull-requests pipeline too, so that's also duplicate work. For now we still build Clang because the other jobs in the clang-ci pipeline require its artifacts, but that could be improved.

### CODE REVIEW

**Review by tstellar — COMMENTED** [review]
If we aren't running the tests any more, can we build clang with `-DLLVM_TARGETS_TO_BUILD=Native`

**Comment by Endilll** [comment]
Do we even need to build Clang and run libc++ jobs? I don't even see them linked in libc++ PR, even besides the fact that I think libc++ is fully tested with GitHub Actions.

**Comment by ldionne** [comment]
> Do we even need to build Clang and run libc++ jobs? I don't even see them linked in libc++ PR, even besides the fact that I think libc++ is fully tested with GitHub Actions.

What we're testing is that the changes to Clang didn't break libc++. We're testing Clang via libc++ -- we're not testing libc++ itself. So yes, this is still relevant.

**Review by Endilll — APPROVED** [review]
OK, I'll try to add this testing to "GitHub Pull Requests" later so that we can avoid building Clang twice.

**Review by tstellar — APPROVED** [review]
LGTM.  Thanks, this should help free up some builder resources.

**Comment by ldionne** [comment]
I will merge once the CI has passed. If someone else sees the CI green, feel free to merge too.

@Endilll We could indeed "flatten" the `clang-ci` pipeline into the `github-pull-requests` pipeline. Basically, instead of triggering the `clang-ci` pipeline like this: https://github.com/llvm/llvm-project/blob/main/.ci/generate-buildkite-pipeline-premerge#L213

We would instead expand to the pipeline itself and it would run inside the `github-pull-requests` pipeline itself. It would then be easier to share artifacts between jobs within that pipeline, and the `clang-ci` pipeline could go away entirely.

The same treatment could potentially be applied to libc++ although there will be other challenges (namely generating a valid pipeline YAML inside `.ci/generate-buildkite-pipeline-premerge` may be challenging).

**Pull request merged**
