### PR TITLE
ValueTracking: Treat poison more aggressively in computeKnownFPClass

### PR DESCRIPTION
**Pull request by arsenm**
Assume no valid values, and the sign bit is 0.

### CODE REVIEW

**Review by jcranmer-intel — COMMENTED** [review]
Can you add a test for `freeze poison` as well? From looking through the code, it should be the case that it does the right thing already, but having a test makes me feel better that we won't accidentally break it in future changes.

**Review by nikic — APPROVED** [review]
LGTM, with the note that there is a pre-existing bug in the code below, which incorrectly skips UndefValue rather than PoisonValue in constant vectors.

**Comment by ZERICO2005** [comment]
While working on the `KnownFPClass` refactor in #220606, I noticed that this uses `{fcNone, false}` rather than `{fcNone, std::nullopt}`.

Do you remember the rationale for having the signbit be `false` instead of `std::nullopt` here? The refactored `KnownFPClass` I am working on is not capable of representing the equivalent of `{fcNone, false}`, only `{fcNone, std::nullopt}`.

**Comment by arsenm** [comment]
Knowing a definitive sign bit is useful, and it's probably more useful on average to assume it's 0 than 1, but there are counterexamples

**Comment by ZERICO2005** [comment]
Ok, I could have `getSignBit` for the refactored `KnownFPClass` return `false` for `kfcNone`. Although this would disagree with `KnownFPClass.KnownFPMask & kfcPosSignBit`.

**Pull request merged**
