### PR TITLE
Fix block merging

### PR DESCRIPTION
**Pull request by giuseros**
With this PR I am trying to address: https://github.com/llvm/llvm-project/issues/63230. 

What changed:
- While merging identical blocks, don't add a block argument if it is "identical" to another block argument. I.e., if the two block arguments refer to the same `Value`. The operations operands in the block will point to the argument we already inserted
- After merged the blocks, get rid of "unnecessary" arguments. I.e., if all the predecessors pass the same block argument, there is no need to pass it as an argument. 
- This last simplification clashed with `BufferDeallocationSimplification`. The reason, I think, is that the two simplifications are clashing. I.e., `BufferDeallocationSimplification` contains an analysis based on the block structure. If we simplify the block structure (by merging and/or dropping block arguments) the analysis is invalid . The solution I found is to do a more prudent simplification when running that pass. 

**Note**: many tests are still not passing. But I wanted to submit the code before changing all the tests (and probably adding a couple), so that we can agree in principle on the algorithm/design.

### CODE REVIEW

**Review by Mogball — COMMENTED** [review]
Thank you so much for looking into this issue! Can you add a test case to the PR?

**Comment by giuseros** [comment]
Hi @Mogball , thanks for the comment! I added a test case and fixed `mlir/test/Transforms/canonicalize-block-merge.mlir` . 

The test case I added is a simplification of the one you proposed [here](https://github.com/llvm/llvm-project/issues/63230). The point is that in Triton we meet exactly this case, and indeed we end up hanging the compiler.

**Review by Mogball — APPROVED** [review]

**Comment by Mogball** [comment]
Thank you so much for fixing this!

**Comment by giuseros** [comment]
Hi @Mogball , is it ok if I merge this?

**Review by Mogball — APPROVED** [review]

**Comment by giuseros** [comment]
Thank you so much! It's the first non-negligible PR I merge upstream, so I was not sure :P

**Comment by joker-eph** [comment]
Seems like this broke the bots: https://lab.llvm.org/buildbot/#/builders/116/builds/778 ; I'll revert for now.

**Comment by giuseros** [comment]
Hi @joker-eph , I am very sorry about this. Thanks for reverting the patch. I have a question: to test my path I ran `ninja check-mlir`. Is there a more extensive set of tests I should run?

**Comment by joker-eph** [comment]
The failing tests are enabled by `-DMLIR_INCLUDE_INTEGRATION_TESTS=ON` I believe

**Pull request merged**
