### PR TITLE
[INSTR COMBINE] implement combine select into cast

### LINKED ISSUE #107034: [X86] Non-optimal codegen for bool to float conversions with `select i1 %0, float 1.0, float 0.0`
https://godbolt.org/z/3jjdq1ex1

Given the following Rust source:

```Rust
#[no_mangle]
pub fn ifelse(x: bool) -> f32 {
    if x { 1. } else { 0. }
}
```

We end up with the following before x86 inst selection:

```llvm
define noundef float @ifelse(i1 noundef zeroext %x) unnamed_addr {
start:
  %. = select i1 %x, float 1.000000e+00, float 0.000000e+00
  ret float %.
}

```

For which we end up with the following x86 codegen:

```asm
.LCPI1_0:
        .long   0x3f800000
ifelse:
        test    edi, edi
        jne     .LBB1_1
        xorps   xmm0, xmm0
        ret
.LBB1_1:
        movss   xmm0, dword ptr [rip + .LCPI1_0]
        ret
```

Ideally we'd probably like to see this converted to:

```llvm
define noundef float @cast(i1 noundef zeroext %x) unnamed_addr {
start:
  %_0 = uitofp i1 %x to float
  ret float %_0
}
```

On x86, this would give us:

```asm
cast:
        cvtsi2ss        xmm0, edi
        ret
``` 

On the integer side, `InstCombinePass` is able to transform `select i1 %x, i32 1, i32 0` to `zext i1 %x to i32`. That seems like a somewhat similar operation, but I'm not very familiar with LLVM.

### PR DESCRIPTION
**Pull request by Cr0a3**
Hi,
I implemented the instruction combination of this:
````
define noundef float @ifelse(i1 noundef zeroext %x) unnamed_addr {
start:
  %. = select i1 %x, float 1.000000e+00, float 0.000000e+00
  ret float %.
}
````
into this:
```

define noundef float @ifelse(i1 noundef zeroext %x) unnamed_addr {
start:
  %.= uitofp i1 %x to float
  ret float %.
}
```

Fixes #107034

@weliveindetail

### CODE REVIEW

**Review by nikic — COMMENTED** [review]
Please take a look at https://llvm.org/docs/InstCombineContributorGuide.html for guidelines for contributing to InstCombine, esp regarding proofs and tests.

But even before that, wasn't the consensus from https://github.com/llvm/llvm-project/issues/107034 that this is better handled in the backend on the SDAG level, rather than in InstCombine?

**Comment by weliveindetail** [comment]
> But even before that, wasn't the consensus from https://github.com/llvm/llvm-project/issues/107034 that this is better handled in the backend on the SDAG level, rather than in InstCombine?

That's right, they noted it in the ticket. Maybe the comments here can help finding a better place for it? https://github.com/llvm/llvm-project/pull/107732/files#r1749823010

FYI @Cr0a3 was asking for a good first issue and we spotted this one quickly. After all, it has that label. Not sure it's still the case if it must be implemented in ISel? Anyway, good first attempt :)

**Comment by nikic** [comment]
> > But even before that, wasn't the consensus from #107034 that this is better handled in the backend on the SDAG level, rather than in InstCombine?
> 
> That's right, they noted it in the ticket. Maybe the comments here can help finding a better place for it? https://github.com/llvm/llvm-project/pull/107732/files#r1749823010
> 
> FYI @Cr0a3 was asking for a good first issue and we spotted this one quickly. After all, it has that label. Not sure it's still the case if it must be implemented in ISel? Anyway, good first attempt :)

Yeah, looking at the discussion in that PR, this issue may not be as simple as it appeared on the surface :)

If you're looking for a simple middle-end issue, I just opened https://github.com/llvm/llvm-project/issues/114820, though maybe it's not a particularly exciting one...

**Comment by Cr0a3** [comment]
Thank you very much

**Pull request closed without merging**
