### PR TITLE
[BinaryFormat] Disable MachOTest.UnalignedLC on SPARC

### PR DESCRIPTION
**Pull request by rorth**
As discussed in Issue #86793, the `MachOTest.UnalignedLC` test dies with `SIGBUS` on SPARC, a strict-alignment target.  It simply cannot work there.  Besides, the test invokes undefined behaviour on big-endian targets, so this patch disables it on all of those.

Tested on `sparcv9-sun-solaris2.11` and `amd64-pc-solaris2.11`.

### CODE REVIEW

**Comment by efriedma-quic** [comment]
Given the test has undefined behavior on all big-endian hosts, I'd prefer to do something to fix the issue for all big-endian hosts, not just SPARC.

**Comment by rorth** [comment]
Disabled now on big-endian in general.  `__BYTE_ORDER__` etc. are predefined on `clang` and `gcc`, but I'm uncertain if the test needs to be compilable by other compilers.

**Comment by efriedma-quic** [comment]
llvm/include/llvm/ADT/bit.h provides define `BYTE_ORDER` and `BIG_ENDIAN` on all targets.

**Comment by rorth** [comment]
I'd seen that, but based on
```
/// \file
/// This file implements the C++20 <bit> header.
```
I was under the impression that those are implementation details that cannot be relied on.

**Review by efriedma-quic — APPROVED** [review]
LGTM

**Pull request merged**
