### PR TITLE
[SLP][TTI]Improve detection of the insert-subvector pattern for SLP.

### PR DESCRIPTION
**Pull request by alexey-bataev**
SLP vectorizer passes the type of the subvector and the mask, which size
determines the size of the resulting vector. TTI should support this
pattern to improve cost estimation of the insert_subvector shuffle
pattern.

### CODE REVIEW

**Comment by RKSimon** [comment]
Could we not improve ShuffleVectorInst::isInsertSubvectorMask directly instead?

**Comment by alexey-bataev** [comment]
> Could we not improve ShuffleVectorInst::isInsertSubvectorMask directly instead?

Sorry, did not quite understand. You mean do the changes in ShuffleVectorInst::isInsertSubvectorMask? Unfortunately, no. Currently improveShuffleKindFromMask just does not provide correct type/subtype at all, so even changing ShuffleVectorInst::isInsertSubvectorMask won't help.

**Comment by alexey-bataev** [comment]
Ping!

**Comment by alexey-bataev** [comment]
Ping!

**Comment by alexey-bataev** [comment]
Moved detection to SLP vectorizer.

**Review by RKSimon — APPROVED** [review]
LGTM

**Pull request merged**
