### PR TITLE
[libc++][print] Includes <format>.

### LINKED ISSUE #71925: C++23 range formatters are not available by #include <print>
Testcase against clang trunk:

https://gcc.godbolt.org/z/c1PYs1nxG
```c++
#include <vector>
#include <print>
// #include <format>

int main() {
    std::vector<int> v{1, 2, 3};
    std::println("{}", v);
}
```

This doesn't compile; one must include `<format>` to get the range formatters.

I'm not sure how to read the Standard here. In principle, the `std::formatter` specializations for ranges are in `<format>` (https://eel.is/c++draft/format.syn) but that doesn't sound user-friendly.

### PR DESCRIPTION
**Pull request by mordante**
The overloads of `println` are specified in terms of `format`. The function `format` is specified to work with ranges.

The implementations for `println` do not include `<format>`, but libc++'s granularized header. This means the following example does not work

  #include <vector>
  #include <print>

  int main() {
      std::vector<int> v{1, 2, 3};
      std::println("{}", v);
  }

(The other print functions also require this to work, they are specified in terms of other format functions.)

Fixes: https://github.com/llvm/llvm-project/issues/71925

### CODE REVIEW

**Comment by ldionne** [comment]
See https://github.com/llvm/llvm-project/issues/71925#issuecomment-1885528871, but basically I'd like to have a LWG issue if we do this.

**Review by ldionne — APPROVED** [review]

**Comment by zmodem** [comment]
We noticed in Chromium that this grew our preprocessed compiler input size by ca 4.3 GB (1.2%).

A small example:

```
$ cat /tmp/a.cc
#include <iostream>

int main() {
  std::cout << "Hello, world!\n";
  return 0;
}

# Before this change:
$ build2/bin/clang++ -E -stdlib=libc++ -std=c++20 /tmp/a.cc | wc --bytes
3108703
$ perf stat -r20 build2/bin/clang++ -c -stdlib=libc++ -std=c++20 /tmp/a.cc
0.879287 +- 0.000996 seconds time elapsed  ( +-  0.11% )

# After this change:
$ build2/bin/clang++ -E -stdlib=libc++ -std=c++20 /tmp/a.cc | wc --bytes
3683481
$ perf stat -r20 build2/bin/clang++ -c -stdlib=libc++ -std=c++20 /tmp/a.cc
0.98528 +- 0.00192 seconds time elapsed  ( +-  0.20% )
```

That is an 18% increase in preprocessed size and 12% increase in compile time.

I realize this kind of change is driven by the standard, but is there anything that could be done to limit the negative impact, especially for those not using std::printf in this case?

(Yes, modules is the long-term answer, but many of us are not ready yet.)

**Comment by mordante** [comment]
I had a patch for this https://reviews.llvm.org/D157298, but that was not well liked to do at a large scale. This patch was due to an earlier size increment due to `format` in `vector`. Btw I asked about this issue a while ago in a DM on Discourse, did you see that message?

I'm happy to revisit this idea, but then it would be good to have some performance numbers. These number seem worse than the vector case. Maybe instead of doing fine-grained "header removal" we could only remove the "heavy hitters".

**Comment by mordante** [comment]
> > I'm happy to revisit this idea, but then it would be good to have some performance numbers. These number seem worse than the vector case. Maybe instead of doing fine-grained "header removal" we could only remove the "heavy hitters".
> 
> From what I understand that patch was based around the idea of gating includes on language version. While it would help some users for a while, it's really just postponing the problem until folks move to the next -std=c++ version.

Yes that's correct.

> Another idea would be gating all the format stuff behind an #ifdef (and similar for other features), but that could also result in a huge matrix of different modes to support, so I can see why that wouldn't be desirable.

Yes that is a maintenance issue.

> Ultimately, I wish the standard provided more granular headers, so that users of basic ostream functionality wouldn't have to pay the cost of the new formatting features.

Note that chrono's ostream functionality uses `std::format`, in C++26 `std::to_string` for floating-point types also uses `std::format`. I expect format to be used in more places in the library in upcoming C++ versions.

It seems there are other users with the same issue so you might want to keep an eye on #80196

**Pull request merged**
