### PR TITLE
[libunwind]  fix dynamic .eh_frame registration

### PR DESCRIPTION
**Pull request by SihangZhu**
Fix this issue [#76957](https://github.com/llvm/llvm-project/issues/76957)
Libgcc provides __register_frame  to register a dynamic .eh_frame section, while __unw_add_dynamic_eh_frame_section can be used to do the same in libunwind. However, the address after dynamic .eh_frame are padding with 0 value, it will be identified as 
legal CIE. And __unw_add_dynamic_eh_frame_section will continue to parse subsequent addresses until illegal memory or other sections are accessed.
This patch adds length formal parameter for dynamic registration.

### CODE REVIEW

**Review by arichardson — COMMENTED** [review]
While I think this is a reasonable change, I don't think we can change this function signature without breaking the ABI. So it probably needs to be a new function instead.

**Review by lhames — CHANGES_REQUESTED** [review]
As @arichardson noted this would break the ABI.

The best solution is to fix the implementation of `__unw_add_dynamic_eh_frame_section` (and `__unw_remove_dynamic_eh_frame_section`) as described in https://github.com/llvm/llvm-project/issues/76957#issuecomment-1879977544.

**Comment by SihangZhu** [comment]
> As @arichardson noted this would break the ABI.
> 
> The best solution is to fix the implementation of `__unw_add_dynamic_eh_frame_section` (and `__unw_remove_dynamic_eh_frame_section`) as described in [#76957 (comment)](https://github.com/llvm/llvm-project/issues/76957#issuecomment-1879977544).

thx for advice.

**Comment by SihangZhu** [comment]
@lhames Could you check again, I have fixed the implementation as  you decribed

**Comment by lhames** [comment]
Hi @SihangZhu. Sorry for the delay — will try to review this tomorrow.

**Review by lhames — APPROVED** [review]
Ok -- local testing seems to confirm that this is the right fix. We need to add a testcase for this API, but that can happen as a follow-up.

**Pull request merged**
