### PR TITLE
[llvm][ScheduleDAG] SUnit::biasCriticalPath() does not find the criti...

### PR DESCRIPTION
**Pull request by csstormq**
…cal path consistently

Fix https://github.com/llvm/llvm-project/issues/38037

### CODE REVIEW

**Review by atrick — APPROVED** [review]
Looks like a straightforward fix to me. Is there any way to add a unit test?

**Comment by csstormq** [comment]
> Looks like a straightforward fix to me. Is there any way to add a unit test?

Thanks, @atrick . I have added a test in X86 target, as you suggested. Please review again, thank you.

**Review by atrick — APPROVED** [review]
LGTM thanks

**Comment by nico** [comment]
This seems to break tests: http://45.33.8.238/linux/138572/step_11.txt

Please take a look and revert for now if it takes a while to fix.

**Comment by csstormq** [comment]
> This seems to break tests: http://45.33.8.238/linux/138572/step_11.txt
> 
> Please take a look and revert for now if it takes a while to fix.

OK. I will now check whether problems have been caused by my change. Please wait a moment.

**Comment by csstormq** [comment]
> This seems to break tests: http://45.33.8.238/linux/138572/step_11.txt
> 
> Please take a look and revert for now if it takes a while to fix.

Hi, @nico . I have created an new pull request #92992 to revert this commit. Please approve it, thank you.

**Comment by chenzheng1030** [comment]
ppc AIX/Linux buildbots also fail at the same cases.
https://lab.llvm.org/buildbot/#/builders/57/builds/35165
https://lab.llvm.org/buildbot/#/builders/214/builds/12263

**Comment by csstormq** [comment]
> ppc AIX/Linux buildbots also fail at the same cases. https://lab.llvm.org/buildbot/#/builders/57/builds/35165 https://lab.llvm.org/buildbot/#/builders/214/builds/12263

@AtariDreams has addressed these broken unit tests. I would like to rebase our commits to one if possible.

**Pull request merged**
