### PR TITLE
[RISCV] Only allow up to e64 in vsetvli

### PR DESCRIPTION
**Pull request by palmer-dabbelt**
These larger SEWs aren't in the ratified V spec.  Thanks to dzaima and sorear on IRC for pointing this one out.

### CODE REVIEW

**Comment by jrtc27** [comment]
https://github.com/llvm/llvm-project/commit/66da87dcbaf91fa3393ce80c687e9c2d133ee3ca is the commit that first introduced this check which was committed just after V 0.9 (haven't checked if it implemented 0.9 or stuck with 0.8), and up until 1.0 64 < SEW <= 1024 was reserved (see https://github.com/riscv/riscv-v-spec/commit/c32b714b9c4f9f85cb647791939906fba407ab87).

**Comment by topperc** [comment]
Can you add tests to test/MC/RISCV/rvv/invalid.s? I see a test for e2048 in there. I guess we didn't have any tests for e128-e1024.

**Comment by palmer-dabbelt** [comment]
> Can you add tests to test/MC/RISCV/rvv/invalid.s? I see a test for e2048 in there. I guess we didn't have any tests for e128-e1024.

Done.  Also I fixed up the errors in those tests (I'm no building/testing this locally, I figured some CI would do it for me).

**Review by topperc — APPROVED** [review]
LGTM

**Comment by topperc** [comment]
@palmer-dabbelt I assume you need someone to commit this?

**Pull request merged**
