### PR TITLE
[libunwind] Make sure `__STDC_FORMAT_MACROS` is defined to ensure `PRId64` is available

### PR DESCRIPTION
**Pull request by Zentrik**
See https://github.com/llvm/llvm-project/pull/102980 for further details.

### CODE REVIEW

**Review by ldionne — APPROVED** [review]

**Comment by Zentrik** [comment]
@ldionne Do you mind merging this as I don't have commit rights. Thank you

**Comment by MaskRay** [comment]
What old GCC versions need this? If it's just GCC 8, it's possible that we will drop GCC buildability soon. I think for runtime libraries we could pose a stricter requirement.

**Comment by ldionne** [comment]
Ah, I didn't realize this was only required for much older compilers. In that case, indeed we don't support GCC 8 so we probably don't want to merge this.

**Comment by giordano** [comment]
Based on https://github.com/JuliaPackaging/Yggdrasil/pull/9861/files#diff-812a6db0df5a0d42010930d41a801e33e89c6064172903e5aacb88a7c704def2R7 this came up with gcc 10

**Comment by Zentrik** [comment]
Based on https://github.com/WAVM/WAVM/pull/266#issue-583580780 and https://en.cppreference.com/w/cpp/types/integer#Notes this might have been fixed in glibc 2.18.

**Pull request closed without merging**
