### PR TITLE
[MLIR][Vector] Update Transfer{Read|Write}DropUnitDimsPattern patterns

### PR DESCRIPTION
**Pull request by banach-space**
Updates `TransferWriteDropUnitDimsPattern` and
`TransferReadDropUnitDimsPattern` to inherit from
`MaskableOpRewritePattern` so that masked versions of
xfer_read/xfer_write Ops are also supported:

```mlir
    %v = vector.mask %mask {
      vector.transfer_read %arg[%c0, %c0, %c0, %c0], %cst :
        memref<1x1x3x2xi8, strided<[6, 6, 2, 1], offset: ?>>, vector<3x2xi8>
    } : vector<3x2xi1> -> vector<3x2xi8>
```

### CODE REVIEW

**Review by hanhanW — CHANGES_REQUESTED** [review]
I was looking for some tests with shape_cast ops generated; I found that it does not support the below case. Can you take a look?

Note: it is a test in the original file and I just added a `vector.mask` op around it.

```mlir
func.func @transfer_read_and_vector_rank_reducing_to_0d_masked(
      %arg : memref<1x1x1x1x1xf32>,
      %mask: vector<1x1x1xi1>) -> vector<1x1x1xf32> {
    %c0 = arith.constant 0 : index
    %cst = arith.constant 0.0 : f32
    %v = vector.mask %mask {
      vector.transfer_read %arg[%c0, %c0, %c0, %c0, %c0], %cst :
      memref<1x1x1x1x1xf32>, vector<1x1x1xf32>
    } : vector<1x1x1xi1> -> vector<1x1x1xf32>
    return %v : vector<1x1x1xf32>
}
module attributes {transform.with_named_sequence} {
  transform.named_sequence @__transform_main(%root : !transform.any_op {transform.readonly}) {
    %func_op = transform.structured.match ops{["func.func"]} in %root : (!transform.any_op) -> !transform.op<"func.func">
    transform.apply_patterns to %func_op {
      transform.apply_patterns.vector.rank_reducing_subview_patterns
    } : !transform.op<"func.func">
    transform.yield
  }
}
```

**Comment by hanhanW** [comment]
The error log:

```
zz.mlir:19:7: error: 'vector.mask' op operand #0 must be vector of 1-bit signless integer values, but got 'vector<i1>'
```

**Comment by banach-space** [comment]
> I was looking for some tests with shape_cast ops generated; I found that it does not support the below case. Can you take a look?
> 
> Note: it is a test in the original file and I just added a `vector.mask` op around it.
> 
> ```mlir
> func.func @transfer_read_and_vector_rank_reducing_to_0d_masked(
>       %arg : memref<1x1x1x1x1xf32>,
>       %mask: vector<1x1x1xi1>) -> vector<1x1x1xf32> {
>     %c0 = arith.constant 0 : index
>     %cst = arith.constant 0.0 : f32
>     %v = vector.mask %mask {
>       vector.transfer_read %arg[%c0, %c0, %c0, %c0, %c0], %cst :
>       memref<1x1x1x1x1xf32>, vector<1x1x1xf32>
>     } : vector<1x1x1xi1> -> vector<1x1x1xf32>
>     return %v : vector<1x1x1xf32>
> }
> module attributes {transform.with_named_sequence} {
>   transform.named_sequence @__transform_main(%root : !transform.any_op {transform.readonly}) {
>     %func_op = transform.structured.match ops{["func.func"]} in %root : (!transform.any_op) -> !transform.op<"func.func">
>     transform.apply_patterns to %func_op {
>       transform.apply_patterns.vector.rank_reducing_subview_patterns
>     } : !transform.op<"func.func">
>     transform.yield
>   }
> }
> ```

Great catch, thanks for checking! Turns out `vector.mask` doesn't support 0-d vectors. This should be easy to extend, but let's bail out for now - I am a bit blocked 😅

**Review by nujaa — APPROVED** [review]
LGTM. I must have missed this one in my pattern maskification spree. Thanks.

**Review by dcaballe — APPROVED** [review]
Thanks! Pretty good to see how `MaskableOpRewritePattern::MaskableOpRewritePattern` allows us to add support for masked ops with minimal changes, reusing the same patterns!

**Review by hanhanW — APPROVED** [review]
> Great catch, thanks for checking! Turns out vector.mask doesn't support 0-d vectors. This should be easy to extend, but let's bail out for now - I am a bit blocked 😅

SGTM, thanks for taking a look!

**Pull request merged**
