### PR TITLE
[llvm-ar][Archive] Use getDefaultTargetTriple instead of host triple for the fallback archive format.

### PR DESCRIPTION
**Pull request by cjacek**
As suggested by @gbreynoo in #82642.

### CODE REVIEW

**Review by jh7370 — COMMENTED** [review]
I think the new behaviour makes more sense to me than the old one, thanks, but I think it should be documented both in the release notes and the llvm-ar Command Guide document.

**Comment by gbreynoo** [comment]
Thanks @cjacek, LGTM once James' comment has been covered.

**Comment by cjacek** [comment]
I added documentation and rebased, thanks.

**Review by jh7370 — APPROVED** [review]
LGTM. I considered if there was any way of testing this, but the only way I could think of was to have lit know the default target triple (it might well know that already) and then somehow leverage that to convert to a check for the "expected" format for an empty archive. I guess a python script that takes the default triple and inspects the output archive might be possible, but it's may not be worth it. If you want to go down that route, feel free (and I'd be happy to review), but I'm not going to require it.

**Comment by cjacek** [comment]
Thanks. I pushed without tests.

**Pull request merged**
