### PR TITLE
[LTO] Add function alias as function instead of data

### PR DESCRIPTION
**Pull request by scui-ibm**
On AIX, for undefined functions, only the dotnamed symbols (the address of the function) are generated after linking (i.e., no named function symbol is generated).
 
Currently, all alias symbols are added as defined data symbols when parsing symbols in LTOModule (the Link Time Optimization library used by linker to optimization code at link time). On AIX, if the function alias is used in the native object, and only its dotnamed symbol is generated, the linker will have problem to match the dotnamed symbol from the native object and the defined symbol marked as data from the bitcode at LTO linktime.
 
This patch is to add function alias as function instead of data.

### CODE REVIEW

**Comment by teresajohnson** [comment]
This is the legacy LTO handling, which I am less familiar with. Added @cachemeifyoucan who is a user of that and can probably give better guidance on the patch and a test case.

That being said it seems reasonable to me to treat a function alias as a function not data, but again, I'm unfamiliar with the handling here. It would be really good to have a test case. The llvm-lto tool is typically used to invoke the legacy LTO handling. Can you have a simple IR test where there is an alias and check the resulting assembly after llvm-lto?

**Comment by cachemeifyoucan** [comment]
I would prefer a test case for this. I think the goal is to get attribute set correctly when querying from LTO legacy interface? I will just extend `llvm-lto -list-symbols-only` option to print attributes too to test your change.

**Comment by scui-ibm** [comment]
Thanks @teresajohnson and @cachemeifyoucan for your quick comments and suggestions. I'll extend llvm-lto -list-symbols-only option to print attributes and add a test to test this.

**Review by cachemeifyoucan — APPROVED** [review]
Thanks. LGTM!

**Pull request merged**
