### PR TITLE
[CodeGen] Don't allow function alignment less than the target's minimum

### PR DESCRIPTION
**Pull request by dougsonos**
See #90358 

The C++ ABI forces all class methods to have an explicit alignment of 2. This ends up overriding `MachineFunction`'s alignment (on arm64, 4) on functions in special text sections. Add a check: don't align code at less than the target's minimum function alignment.

(Are there other objects which can occur in text sections and which should be allowed to be aligned at smaller than the minimum function alignment?)

### CODE REVIEW

**Review by inclyc — COMMENTED** [review]
Thanks for contributing LLVM! Would you please add test cases to cover your changed lines?

**Comment by dougsonos** [comment]
> Thanks for contributing LLVM! Would you please add test cases to cover your changed lines?

I will work on that. Any pointers on a general testing approach here?

Idea: construct bitcode source files which mimic what Clang generates, then convert them to assembly language (for some particular target...?) and check the alignment directives.

**Review by efriedma-quic — CHANGES_REQUESTED** [review]
Alignment of functions is already confusing enough... this change makes it more confusing.  We should compute the alignment of a function exactly once, not compute it, then override it later.

Ideally, we should just fix clang so it doesn't make this request in the first place.  The relevant code is in https://github.com/llvm/llvm-project/blob/6566ffdf8a543f50b75e9b3c66d771a3a9eb1560/clang/lib/CodeGen/CodeGenModule.cpp#L2492 ... but really, we should just fix the datalayout so getPointerAlignment() works correctly.  (See https://reviews.llvm.org/D57335 )

CC @daltenty @hubert-reinterpretcast

**Comment by dougsonos** [comment]
> Ideally, we should just fix clang so it doesn't make this request in the first place.

OK ... I verified that this underalignment only happens on C++ methods, where this code (right after your reference) causes Clang to emit a specific alignment on the function where otherwise it would not. Functions where Clang does not specify alignment do not end up underaligned.

```
  if (getTarget().getCXXABI().areMemberFunctionsAligned()) {
    if (isa<CXXMethodDecl>(D) && F->getPointerAlignment(getDataLayout()) < 2)
      F->setAlignment(std::max(llvm::Align(2), F->getAlign().valueOrOne()));
  }
```

So are you suggesting that the data layout's function pointer alignment should be set, and used here as another lower bound? Currently arm64 has no specified function pointer alignment.

Thanks for the reply.

**Comment by efriedma-quic** [comment]
On 32-bit Arm, function pointer alignment is only 1 byte (8 bits as spelled in the datalayout) because of the way Thumb works.  On 64-bit, 4 bytes should be right.  (And on PPC, it depends on the ABI.)  I've been meaning to extend the function pointer alignment specification to other targets, but didn't get around to it.  Didn't realize it affected this code.

getPointerAlignment queries the datalayout already.  The alternative here is to add some code to clang/lib/Basic/Targets to specify function pointer alignment... (You can't call TargetLowering from clang; clang IR generation is intentionally separated from the backend.)

**Comment by efriedma-quic** [comment]
> I could add "Fi32" to the AArch64 data layouts. (Any pointers to how to do this most cleanly?)

Should be Fn32. ("i" is only for targets where function pointers aren't simple pointers to code... like Arm and PPC.)

The datalayout is in two places: clang/lib/Basic/Targets/AArch64.cpp, and llvm/lib/Target/AArch64/AArch64TargetMachine.cpp .  Then, ideally, you update UpgradeDataLayoutString in llvm/lib/IR/AutoUpgrade.cpp so auto-upgraded IR inherits the right behavior.

> (newbie Q: Should I open a different PR or repurpose this one?)

In this case, I'd create a new PR because the new approach is so much different.

**Comment by dougsonos** [comment]
> In this case, I'd create a new PR because the new approach is so much different.

Thanks. I opened #90702

**Comment by dougsonos** [comment]
Closing in favor of #90702

**Pull request closed without merging**
