### PR TITLE
[libc][docs] add redirect for math/index.html

### PR DESCRIPTION
**Pull request by nickdesaulniers**
commit a9aff440d9dd ("[libc][docs] reorganize documentation (#118836)")

moved https://libc.llvm.org/math/index.html to
https://libc.llvm.org/headers/math/index.html which makes links from various
slide decks stale.

There's an extension for sphinx that can generate redirects.  Add a dependency
on that, then use it to create a redirect so that those older links still work.

I was able to install this sphinx extension via:

    $ sudo apt install python3-sphinx-reredirects

We may need to install this on whatever server generates the llvm
documentation.

### CODE REVIEW

**Review by lntue — APPROVED** [review]

**Comment by nickdesaulniers** [comment]
yeah, looks like this isn't going to work...

**Comment by nickdesaulniers** [comment]
@diogoteles08 any idea how we're supposed to be able to add sphinx plugins...?

**Comment by nickdesaulniers** [comment]
I've emailed @gkistanova to see if we can install the dependency on the bot or not.

**Comment by boomanaiden154** [comment]
It might be better to update the bot to run `pip install` on the docs `requirements.txt` so that we don't need manual intervention in the future (if feasible, not sure how the bot is configured).

**Comment by marcauberer** [comment]
Indeed.
@nickdesaulniers Please also use the following command to regenerate `requiresments-hashed.txt`:

```bash
pip-compile --generate-hashes --output-file=requirements-hashed.txt requirements.txt
```

**Comment by nickdesaulniers** [comment]
oh man, I can't figure out how to install `pip-compile` on my debian workstation.

**Comment by boomanaiden154** [comment]
`pip3 install pip-tools` doesn't work?

**Comment by nickdesaulniers** [comment]
We have a corporate policy on "externally managed python environments" that blocks the usage of `pip install` in favor of `apt install`; but I don't think `pip-compile` is packaged for debian FWICT?

**Comment by boomanaiden154** [comment]
Surprised I have not run into that policy yet...

Can you do a venv?

```
python3 -m venv env
source ./env/bin/activate
pip3 install pip-tools
```

**Comment by nickdesaulniers** [comment]
Updating the hashes in #120315.

The bot will still be broken, but the fix is either:
- manual intervention
- `pip install -r llvm/docs/requirements.txt` BEFORE running `ninja <whatever to build docs>`.

**Comment by boomanaiden154** [comment]
> pip install -r llvm/docs/requirements.txt BEFORE running ninja <whatever to build docs>.

This is what we should be doing. I think a couple other bots already do it. Should be a relatively simple zorg patch.

**Comment by nickdesaulniers** [comment]
zorg/buildbot/builders/SphinxDocsBuilder.py ?

**Comment by boomanaiden154** [comment]
Looks right to me.

**Comment by nickdesaulniers** [comment]
https://github.com/llvm/llvm-zorg/pull/345

**Pull request merged**
