### PR TITLE
[offload] - Fix issue with standalone debug offload build

### PR DESCRIPTION
**Pull request by estewart08**
Error: CommandLine Error: Option 'attributor-manifest-internal' registered more than once

During the standalone debug build of offload the above error is seen at app runtime when using a prebuilt llvm with LLVM_LINK_LLVM_DYLIB=ON. This is caused by linking both libLLVM.so and various archives that are found via llvm_map_components_to_libnames for jit support.

### CODE REVIEW

**Comment by jhuber6** [comment]
Maybe we shouldn't just link libLLVM.so then, wonder where that's getting added.

**Comment by shiltian** [comment]
Hmm, why did it link `libLLVM.so`? We already choose to link components.

**Comment by estewart08** [comment]
For `libomptarget.so` the plugin archives are linked in which have a dependency on PluginCommon and by design the extra archives. add_llvm_library does add `libLLVM.so` in the cmake module when `LLVM_LINK_LLVM_DYLIB=ON` and the module will also  ignore w/e LINK_COMPONENTS you pass in. By adding those extra archives for jit targets like AMDGCN* then we bring in their transitive dependencies as well and then get the conflict with LLVM.so. This specific error had to do with libLLVMipo.a.

**Comment by jhuber6** [comment]
> For `libomptarget.so` the plugin archives are linked in which have a dependency on PluginCommon and by design the extra archives. add_llvm_library does add `libLLVM.so` in the cmake module when `LLVM_LINK_LLVM_DYLIB=ON` and the module will also ignore w/e LINK_COMPONENTS you pass in. By adding those extra archives for jit targets like AMDGCN* then we bring in their transitive dependencies as well and then get the conflict with LLVM.so. This specific error had to do with libLLVMipo.a.

Does that mean that mean we don't need to link in these at all in dylib build? Could just guard the whole loop thing then.

**Comment by shiltian** [comment]
Yeah technically in dylib build the only `libLLVM.so` is sufficient for everything.

**Review by jhuber6 — APPROVED** [review]

**Pull request merged**
