### PR TITLE
Fix complex abs corner cases.

### PR DESCRIPTION
**Pull request by jreiffers**
The current implementation fails for very small and very large values. For example, (0, -inf) should return inf, but it returns -inf. 

This ports the logic used in XLA. Tested with XLA's exhaustive_binary_test_f32_f64.

### CODE REVIEW

**Review by akuegel — APPROVED** [review]

**Comment by joker-eph** [comment]
Thanks for the fix!

**Comment by Hardcode84** [comment]
I believe, current implementation is incorrect for case `(0, 0)` and `fastmath=nnan`.
`div(min, max) == div(0, 0) == nan == poison` which is propagated for all the following ops
`cmpf uno == either false or poison` (not sure about actual llvm semantics here)
both for `false` and `poison` select will return poison.
In practice, we are getting nan results instead of expected 0s.

Not sure if previous version was formally correct, but at least we were getting correct results for this case.

**Comment by jreiffers** [comment]
Sorry about that. You're right. Let me take a look.

**Comment by jreiffers** [comment]
PR here: https://github.com/llvm/llvm-project/pull/95080

**Pull request merged**
