### PR TITLE
[clang][analyzer] Improve StdLibraryFunctionsChecker 'readlink' modeling.

### PR DESCRIPTION
**Pull request by balazske**
The functions 'readlink' and 'readlinkat' do return 0 only if the 'bufsize' argument is 0.

### CODE REVIEW

**Review by NagyDonat — APPROVED** [review]
This is straightforward small change that clarifies some _very confusing_ (but technically true positive) bug reports that I encountered on some open source projects.

**Review by steakhal — APPROVED** [review]
LGTM, but please wait for @DonatNagyE to have a look.
BTW I noticed that the note messages are not tested, but I'm okay to not test that I think.

**Comment by DonatNagyE** [comment]
Feel free to merge this @balazske, and thanks for the improvement!

**Review by NagyDonat — CHANGES_REQUESTED** [review]
Sorry for undoing my approval, but as I was reviewing your other commit #71392  I noticed that it includes a testcase (the change in clang/test/Analysis/std-c-library-functions-path-notes.c) that logically belongs to this commit.

Moreover, I think that TC shows that it would be useful to see the behavior of this change on open source projects as I fear that this change could lead to "technically TP, but not helpful for the user" reports.

Please move that TC into this commit and provide some open source results that show the behavior of this checker after this change.

Of course, I still think that this is a good and useful change, but we need to be careful because it seems that even a small change like this can produce surprising side effects.

**Comment by DonatNagyE** [comment]
> Moreover, I think that TC shows that it would be useful to see the behavior of this change on open source projects as I fear that this change could lead to "technically TP, but not helpful for the user" reports.

On a second thought, AFAIK there are already other functions that have similar "argument is zero" corner cases that turn into separate execution paths, so it's unlikely that the impact from this (not too common) function would be especially severe. I'd slightly prefer to see open source results, but if you feel that they're not needed, then don't bother with collecting them.

**Comment by balazske** [comment]
I tested on vim and the problematic report disappeared, no other changes were detected.

**Comment by balazske** [comment]
The checker was already tested on some projects, but much more is needed to find such corner cases. It can be better to manually check the functions for cases when a 0 return value is not possible or only at a special (known) case.

**Review by NagyDonat — APPROVED** [review]
Thanks for adding the missing TC!

**Pull request merged**
