### PR TITLE
[tsan] Intercept __tls_get_addr_earlier

### PR DESCRIPTION
**Pull request by arichardson**
This can be useful because dlsym() may call malloc on failure which could
result in other interposed functions being called that could eventually
make use of TLS. While the crash that I experienced originally has been
fixed differently (by not using global-dynamic TLS accesses in the mutex
deadlock detector, see https://github.com/llvm/llvm-project/pull/83890),
moving this interception earlier is still a good since it makes the code
a bit more robust against initialization order problems.

### CODE REVIEW

**Comment by arichardson** [comment]
I think https://github.com/llvm/llvm-project/pull/83890 is the better approach, but since I'm not sure I've uploaded both versions.

**Review by vitalybuka — APPROVED** [review]
I guess we can land both

**Review by MaskRay — CHANGES_REQUESTED** [review]
Commented on #83890. Yes, 83890 looks better than this one.

**Comment by vitalybuka** [comment]
> Commented on #83890. Yes, 83890 looks better than this one.

Yes, but initializing these low level interceptors earlier also looks like improvement

**Review by MaskRay — APPROVED** [review]

**Pull request merged**
