### PR TITLE
[compiler-rt] Fix definition of `usize` on 32-bit Windows

### LINKED ISSUE #101998: 32-bit x86 Windows builds fail with `sanitizer_common.h(1101): error C2821: first formal parameter to 'operator new' must be 'size_t'`
In a "x86 Native Tools Command Prompt for VS 2019":

```
git checkout llvmorg-19.1.0-rc2
cmake -GNinja -DCMAKE_BUILD_TYPE=Release -DLLVM_TARGETS_TO_BUILD=X86 -DLLVM_ENABLE_PROJECTS="compiler-rt;clang" ..\llvm
ninja
[...]
[165/4496] Building CXX object projects\compiler-rt\lib\sa...izerCommonSymbolizer.i386.dir\sanitizer_stacktrace.cpp.obj
FAILED: projects/compiler-rt/lib/sanitizer_common/CMakeFiles/RTSanitizerCommonSymbolizer.i386.dir/sanitizer_stacktrace.cpp.obj
C:\PROGRA~2\MICROS~2\2019\PROFES~1\VC\Tools\MSVC\1429~1.301\bin\Hostx86\x86\cl.exe  /nologo /TP -DHAVE_RPC_XDR_H=0 -DUNICODE -D_CRT_NONSTDC_NO_DEPRECATE -D_CRT_NONSTDC_NO_WARNINGS -D_CRT_SECURE_NO_DEPRECATE -D_CRT_SECURE_NO_WARNINGS -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_SCL_SECURE_NO_DEPRECATE -D_SCL_SECURE_NO_WARNINGS -D_UNICODE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iprojects\compiler-rt\lib\sanitizer_common -IC:\src\llvm-project\compiler-rt\lib\sanitizer_common -Iinclude -IC:\src\llvm-project\llvm\include -IC:\src\llvm-project\compiler-rt\lib\sanitizer_common\.. /DWIN32 /D_WINDOWS   /Zc:inline /Zc:preprocessor /Zc:__cplusplus /Oi /bigobj /permissive- -wd4141 -wd4146 -wd4244 -wd4267 -wd4291 -wd4351 -wd4456 -wd4457 -wd4458 -wd4459 -wd4503 -wd4624 -wd4722 -wd4100 -wd4127 -wd4512 -wd4505 -wd4610 -wd4510 -wd4702 -wd4245 -wd4706 -wd4310 -wd4701 -wd4703 -wd4389 -wd4611 -wd4805 -wd4204 -wd4577 -wd4091 -wd4592 -wd4319 -wd4709 -wd5105 -wd4324 -w14062 -we4238 /Gw /W4 /O2 /Ob2 /DNDEBUG -MT /Oy- /GS- /Zc:threadSafeInit- /Z7 /wd4146 /wd4291 /wd4391 /wd4722 /wd4800 /Zl /GR- -std:c++17 /showIncludes /Foprojects\compiler-rt\lib\sanitizer_common\CMakeFiles\RTSanitizerCommonSymbolizer.i386.dir\sanitizer_stacktrace.cpp.obj /Fdprojects\compiler-rt\lib\sanitizer_common\CMakeFiles\RTSanitizerCommonSymbolizer.i386.dir\ /FS -c C:\src\llvm-project\compiler-rt\lib\sanitizer_common\sanitizer_stacktrace.cpp
C:\src\llvm-project\compiler-rt\lib\sanitizer_common\sanitizer_common.h(1101): error C2821: first formal parameter to 'operator new' must be 'size_t'
```

Maybe related to c58c8278f98c189d149d5f062b8d4f56efcada90 "[compiler-rt] Simplify and rename of operator_new_size_type" 
@arichardson can you take a look?

### PR DESCRIPTION
**Pull request by arichardson**
32-bit Windows uses `unsigned int` for uintptr_t and size_t.
Commit 18e06e3e2f3d47433e1ed323b8725c76035fc1ac changed uptr to
unsigned long, so it no longer matches the real size_t/uintptr_t and
therefore the current definition of usize result in:
`error C2821: first formal parameter to 'operator new' must be 'size_t'`

However, the real problem is that uptr is wrong to work around the fact
that we have local SIZE_T and SSIZE_T typedefs that trample on the
basetsd.h definitions of the same name and therefore need to match
exactly. Unlike size_t/ssize_t the uppercase ones always use unsigned
long (even on 32-bit).

This commit works around the build breakage by keeping the existing
definitions of uptr/sptr and just changing usize. A follow-up change
will attempt to fix this properly.

Fixes: https://github.com/llvm/llvm-project/issues/101998

### CODE REVIEW

**Comment by arichardson** [comment]
This seems to work on MSVC and MinGW: https://godbolt.org/z/s8YWaKaKn but I don't have an environment to test this.

**Comment by arichardson** [comment]
Looking into this a bit more, I feel that https://github.com/llvm/llvm-project/pull/106155 is a cleaner solution since it handles more architectures, but maybe best to land this in order to keep it easy to cherry-pick?

**Comment by mstorsjo** [comment]
> This seems to work on MSVC and MinGW: https://godbolt.org/z/s8YWaKaKn but I don't have an environment to test this.

This change breaks builds for i686 mingw like this:
```

In file included from /home/martin/code/llvm-mingw/llvm-project/compiler-rt/lib/interception/interception_win.cpp:132:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/windows.h:69:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/windef.h:9:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/minwindef.h:163:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/winnt.h:150:
/home/martin/clang-trunk/i686-w64-mingw32/include/basetsd.h:147:39: error: typedef redefinition with different types ('ULONG_PTR' (aka 'unsigned long') vs '__sanitizer::uptr' (aka 'unsigned int'))
  147 |   __MINGW_EXTENSION typedef ULONG_PTR SIZE_T,*PSIZE_T;
      |                                       ^
/home/martin/code/llvm-mingw/llvm-project/compiler-rt/lib/interception/interception.h:28:30: note: previous definition is here
   28 | typedef __sanitizer::uptr    SIZE_T;
      |                              ^
In file included from /home/martin/code/llvm-mingw/llvm-project/compiler-rt/lib/interception/interception_win.cpp:132:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/windows.h:69:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/windef.h:9:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/minwindef.h:163:
In file included from /home/martin/clang-trunk/i686-w64-mingw32/include/winnt.h:150:
/home/martin/clang-trunk/i686-w64-mingw32/include/basetsd.h:148:38: error: typedef redefinition with different types ('LONG_PTR' (aka 'long') vs '__sanitizer::sptr' (aka 'int'))
  148 |   __MINGW_EXTENSION typedef LONG_PTR SSIZE_T,*PSSIZE_T;
      |                                      ^
/home/martin/code/llvm-mingw/llvm-project/compiler-rt/lib/interception/interception.h:29:30: note: previous definition is here
   29 | typedef __sanitizer::sptr    SSIZE_T;
      |                              ^
2 errors generated.

```

**Comment by mstorsjo** [comment]
Also, MSVC/WinSDK headers also have the exact same setup for these basic types. From basetsd.h in WinSDK:
```
#if defined(_WIN64)
    typedef __int64 INT_PTR, *PINT_PTR;
    typedef unsigned __int64 UINT_PTR, *PUINT_PTR;

    typedef __int64 LONG_PTR, *PLONG_PTR;
    typedef unsigned __int64 ULONG_PTR, *PULONG_PTR;

    #define __int3264   __int64

#else
    typedef _W64 int INT_PTR, *PINT_PTR;
    typedef _W64 unsigned int UINT_PTR, *PUINT_PTR;

    typedef _W64 long LONG_PTR, *PLONG_PTR;
    typedef _W64 unsigned long ULONG_PTR, *PULONG_PTR;

    #define __int3264   __int32

#endif

[...]

typedef ULONG_PTR SIZE_T, *PSIZE_T;
typedef LONG_PTR SSIZE_T, *PSSIZE_T;
```

So I'm not quite sure how using `unsigned int` for `__sanitizer::uptr` works on MSVC/i386, with respect to the redefinition of `SIZE_T`? Or is the case that when `interception.h` is included in MSVC mode, the transitive system header includes that pull in `SIZE_T` don't end up included, and we can do our own conflicting definition?

**Comment by mstorsjo** [comment]
> So I'm not quite sure how using `unsigned int` for `__sanitizer::uptr` works on MSVC/i386, with respect to the redefinition of `SIZE_T`? Or is the case that when `interception.h` is included in MSVC mode, the transitive system header includes that pull in `SIZE_T` don't end up included, and we can do our own conflicting definition?

I tried testing building compiler-rt with MSVC in 32 bit mode, and it does indeed have the same issue with `SIZE_T` - this patch gets you past the `size_t` mismatches wrt `operator new`, but it still ends up with errors like this:
```
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared\basetsd.h(420): error C2371: 'SIZE_T': redefinition; different basic types
C:\code\llvm-project\compiler-rt\lib\interception\interception.h(28): note: see declaration of 'SIZE_T'
C:\Program Files (x86)\Windows Kits\10\include\10.0.19041.0\shared\basetsd.h(421): error C2371: 'SSIZE_T': redefinition; different basic types
C:\code\llvm-project\compiler-rt\lib\interception\interception.h(29): note: see declaration of 'SSIZE_T'
```

**Comment by arichardson** [comment]
Hmm interesting, so it sounds like size_t and SIZE_T are different types on Windows. I'll update the patch to address this.

I'm surprised we don't have any builders that were able to catch this.

**Comment by arichardson** [comment]
I see the following in godbolt showing that size_t is unsigned int:
```
# 37 "//172.30.0.254/winshared/compilers/mingw-w64-13.1.0-16.0.2-11.0.0-ucrt-r1/x86_64-w64-mingw32/include/corecrt.h" 3 4
typedef unsigned int size_t;
# 47 "//172.30.0.254/winshared/compilers/mingw-w64-13.1.0-16.0.2-11.0.0-ucrt-r1/x86_64-w64-mingw32/include/corecrt.h" 3 4
typedef int ssize_t;
```

However, as you note above SIZE_T and SSIZE_T don't follow this:
```
  __extension__ typedef ULONG_PTR SIZE_T,*PSIZE_T;
  __extension__ typedef LONG_PTR SSIZE_T,*PSSIZE_T;
```

So the real problem is that the interceptors definition of SIZE_T (to avoid conflicting with the real size_t) happens to trample on the Windows headers existing definitions (I don't believe this type exists on Linux/FreeBSD). This dates back to 2012 (https://github.com/llvm/llvm-project/commit/07bb3925b019869b4e00dcee2070a5bbc5639b77) and I'm not quite sure how to fix it best - I'll make this a minimal change to unbreak windows and will update https://github.com/llvm/llvm-project/pull/106155 to try and properly fix this.

**Comment by arichardson** [comment]
@mstorsjo @zmodem This new minimally invasive version should fix the build breakage - I'll work on cleaning up these typedefs properly in https://github.com/llvm/llvm-project/pull/106155. Please let me know if this fixes the issue.

**Comment by mstorsjo** [comment]
> @mstorsjo @zmodem This new minimally invasive version should fix the build breakage - I'll work on cleaning up these typedefs properly in #106155. Please let me know if this fixes the issue.

Thanks, this seems to work for both mingw/i386 and MSVC/i386!

**Review by mstorsjo — APPROVED** [review]
LGTM!

**Pull request merged**
