### PR TITLE
[NFC][HWASAN] Precommit globals-access test

### PR DESCRIPTION
**Pull request by vitalybuka**
HWASAN does not behave as expected yet.

### CODE REVIEW

**Review by thurstond — APPROVED** [review]

**Review by fmayer — APPROVED** [review]

**Comment by dyung** [comment]
@vitalybuka your NFC test commit is failing on several bots, can you take a look or revert if you need time to investigate?

**Comment by vitalybuka** [comment]
Will do, but bot link could be helpful

**Comment by dyung** [comment]
> Will do, but bot link could be helpful

I thought the bots are supposed to automatically email when they fail? If you didn't get notified, here are a few that failed:
- https://lab.llvm.org/buildbot/#/builders/245/builds/22430
- https://lab.llvm.org/buildbot/#/builders/258/builds/15942
- https://lab.llvm.org/buildbot/#/builders/139/builds/62303
- https://lab.llvm.org/buildbot/#/builders/216/builds/36629
- https://lab.llvm.org/buildbot/#/builders/234/builds/21423
- https://lab.llvm.org/buildbot/#/builders/233/builds/8334
- https://lab.llvm.org/buildbot/#/builders/232/builds/21423
- https://lab.llvm.org/buildbot/#/builders/259/builds/1940

**Comment by vitalybuka** [comment]
> I thought the bots are supposed to automatically email 

Not for me, for the record, and rest of community who are not on the blame list of the patch.

**Comment by dyung** [comment]
> > I thought the bots are supposed to automatically email
> 
> Not for me, for the record, and rest of community who are not on the blame list of the patch.

I am curious, did you not receive an email telling you this run had failed on this bot?

https://lab.llvm.org/buildbot/#/builders/139/builds/62303

This builder builds every commit one by one, and your commit is the only one built in this change when it failed.

**Comment by vitalybuka** [comment]
> I am curious, did you not receive an email telling you this run had failed on this bot?

Yes, there is a message in my inbox which I read after your comment here.

**Pull request merged**
