### PR TITLE
[MCP] Enhance MCP copy Instruction removal for special case(reapply)

### PR DESCRIPTION
**Pull request by LWenH**
=============================== **Original Patch**==================================
- Machine Copy Propagation Pass may lose some opportunities to further remove the redundant copy instruction during the **ForwardCopyPropagateBlock** procedure,  consider the following MI sequence:
```asm  
L1: r0 = COPY r9     <- TrackMI
L2: r0 = COPY r8     <- TrackMI
L3: use r0           <- Remove L2 from MaybeDeadCopies
L4: early-clobber r9 <- Invalid L2 from Tracker
L5: r0 = COPY r8     <- Miss remove chance
L6: use r0           <- Miss remove L5 chance
```
- Due to the current mechanism of the MCP Pass, when a register is clobbered, let's say this register is Def, the record in the Tracker that indicates **Src defined Def**  is still remain. This will lead to incorrect invalidations in the Tracker during the subsequent propagation process, thereby preventing the elimination of subsequent NopCopy instructions. In above example, when we clobber r0 at L2, the record in the tracker where r9 defines r0 still exists. Therefore, when we clobber the r9 register at L4, it causes an invalidation of L2 in the Tracker, leading to the inability to eliminate at L5.

- In this patch, when we clobber a register **Def**, we also locate and remove the relative record from the tracker that indicating previous **Src defined Def**.  Since such record is no longer  effectual during the propagation procedure.

- Please see the C++ test case generated code for **vector.body** in MIR: https://gcc.godbolt.org/z/nK4oMaWv5

================================**BugFix(this patch)**================================

This patch try to reimplement [#70778](https://github.com/llvm/llvm-project/pull/70778), and fix issue: https://github.com/llvm/llvm-project/issues/73512.

- In [#70778](https://github.com/llvm/llvm-project/pull/70778) , when we clobbering a register (**Def**), we will also locate and remove the entry in the Copy Maps(Tracker) that indicates **Src** defined **Def**.  If the "**DefRegs**" is being empty after removal, we will directly remove the corresponding **SrcCopy** entry from the Copy Maps.   

- However, since the **SrcCopy** may also have referred the **Src** as the destination of another copy instruction, directly removing it is unsafe. We need to enhance the criteria for removing empty records to ensure safety.

### CODE REVIEW

**Comment by bjope** [comment]
This seems to at least work for the test cases that failed downstream after https://github.com/llvm/llvm-project/pull/70778

I'll try to run some more testing with this new patch over night.

**Comment by bjope** [comment]
> This seems to at least work for the test cases that failed downstream after #70778
> 
> I'll try to run some more testing with this new patch over night.

Can't say that I know much about this pass and the code diff. But I haven't seen any new failures when running tests this patch, so it's fine with me in that sense.

**Comment by LWenH** [comment]
> > This seems to at least work for the test cases that failed downstream after #70778
> > I'll try to run some more testing with this new patch over night.
> 
> Can't say that I know much about this pass and the code diff. But I haven't seen any new failures when running tests this patch, so it's fine with me in that sense.

Seems like a corner case in MIR code pattern leading to this bug:-), thank you for your time to test this patch further.

**Comment by LWenH** [comment]
> Can you change the description to be a revert of the revert (or reapply)? I would also find it easier to read this if it were split into the original revert plus the version with the bug fix and test

Sure, I separated the description of the original patch and this bug fix path and tried to make it more easy to read:-)

**Comment by LWenH** [comment]
Resolve X86 conflict test files.
Ping.

**Comment by LWenH** [comment]
Since the corner case bug of https://github.com/llvm/llvm-project/issues/73512 has been addressed and fixed, and the original patch for this reapply https://github.com/llvm/llvm-project/pull/70778 has been approved, I try to recommit this patch :-)

**Pull request merged**
