### PR TITLE
[AMDGPU] Add i1 mul patterns

### PR DESCRIPTION
**Pull request by Pierre-vh**
i1 muls can sometimes happen after SCEV. They resulted in ISel failures because we were missing the patterns for them.

Solves SWDEV-423354

### CODE REVIEW

**Review by arsenm — COMMENTED** [review]
Would be better off legalizing these rather than selecting

**Comment by Pierre-vh** [comment]
> Would be better off legalizing these rather than selecting

We already have identical patterns for other operations like add, what makes `mul` different in this case?
If we legalize, do you mean just legalize to i32 or do we need some other lowering logic that's aware of divergence?

**Comment by Pierre-vh** [comment]
Ping

**Comment by jayfoad** [comment]
> Would be better off legalizing these rather than selecting

I agree. Why are i1 add/mul legal in the first place?

**Comment by Pierre-vh** [comment]
I legalized the i1 instead, leads to better codegen too it seems.
For the other i1 ops, if those have to be legalized as well, I'd rather do it in a follow up patch if that's alright. Do we want all similar i1 pats gone?

**Comment by jayfoad** [comment]
> For the other i1 ops, if those have to be legalized as well, I'd rather do it in a follow up patch if that's alright. Do we want all similar i1 pats gone?

That would make sense to me, but I don't know the history.

**Review by jayfoad — APPROVED** [review]
LGTM.

**Comment by jayfoad** [comment]
> Add i1 mul patterns

Next time please remember to update the desciption when you rewrite the patch!

**Comment by Pierre-vh** [comment]
> > Add i1 mul patterns
> 
> Next time please remember to update the desciption when you rewrite the patch!

Sorry, I completely forgot. Should I revert & reland with a better name?

**Comment by jayfoad** [comment]
> > > Add i1 mul patterns
> > 
> > 
> > Next time please remember to update the desciption when you rewrite the patch!
> 
> Sorry, I completely forgot. Should I revert & reland with a better name?

No problem, it happens. There is no need to revert the patch.

**Pull request merged**
