### PR TITLE
[Flang][OpenMP] Re-enable tests on windows 4/n

### PR DESCRIPTION
**Pull request by kiranchandramohan**
Re-enable a few simd, critical, workshare tests.

### CODE REVIEW

**Review by NimishMishra — APPROVED** [review]
LGTM.

**Comment by kiranchandramohan** [comment]
@NimishMishra Unfortunately this has one or more tests that have the high running time issue. Testing time is over 20 minutes (Testing Time: 1222.67s).

**Comment by NimishMishra** [comment]
> @NimishMishra Unfortunately this has one or more tests that have the high running time issue. Testing time is over 20 minutes (Testing Time: 1222.67s).

yeah @kiranchandramohan, I looked into the build logs later.

**Comment by NimishMishra** [comment]
The slowest tests reported are

```

14.64s: Flang :: Driver/omp-driver-offload.f90
  | 7.58s: Flang :: Driver/fopenmp.f90
  | 6.20s: Flang :: Semantics/modfile07.f90
  | 5.39s: Flang :: Intrinsics/math-codegen.fir
  | 4.01s: Flang :: Driver/linker-flags.f90
  | 3.95s: Flang :: Driver/fveclib.f90
  | 3.78s: Flang :: Driver/pic-flags.f90
  | 3.78s: Flang :: Driver/gcc-toolchain-install-dir.f90
  | 3.73s: Flang :: Driver/aarch64-sve-vector-bits.f90
  | 3.73s: Flang :: Driver/default-optimization-pipelines.f90
  | 3.57s: Flang :: Semantics/modfile03.f90
  | 3.40s: Flang :: Driver/optimization-remark.f90
  | 3.34s: Flang :: Driver/fsave-optimization-record.f90
  | 3.28s: Flang :: Driver/use-module.f90
  | 3.17s: Flang :: Driver/mlir-debug-pass-pipeline.f90
  | 3.01s: Flang :: Driver/fdefault.f90
  | 2.99s: Flang :: Driver/fixed-line-length.f90
  | 2.99s: Flang :: Driver/falias-analysis.f90
  | 2.79s: Flang :: Fir/convert-to-llvm.fir
  | 2.77s: Flang :: Driver/input-from-stdin/input-from-stdin.f90

```

They don't seem to contain the tests that you enabled in this PR. Sorry, I am probably missing something here, but could you point out why this list is different?

**Comment by kiranchandramohan** [comment]
> The slowest tests reported are
> 
> ```
> 
> 14.64s: Flang :: Driver/omp-driver-offload.f90
>   | 7.58s: Flang :: Driver/fopenmp.f90
>   | 6.20s: Flang :: Semantics/modfile07.f90
>   | 5.39s: Flang :: Intrinsics/math-codegen.fir
>   | 4.01s: Flang :: Driver/linker-flags.f90
>   | 3.95s: Flang :: Driver/fveclib.f90
>   | 3.78s: Flang :: Driver/pic-flags.f90
>   | 3.78s: Flang :: Driver/gcc-toolchain-install-dir.f90
>   | 3.73s: Flang :: Driver/aarch64-sve-vector-bits.f90
>   | 3.73s: Flang :: Driver/default-optimization-pipelines.f90
>   | 3.57s: Flang :: Semantics/modfile03.f90
>   | 3.40s: Flang :: Driver/optimization-remark.f90
>   | 3.34s: Flang :: Driver/fsave-optimization-record.f90
>   | 3.28s: Flang :: Driver/use-module.f90
>   | 3.17s: Flang :: Driver/mlir-debug-pass-pipeline.f90
>   | 3.01s: Flang :: Driver/fdefault.f90
>   | 2.99s: Flang :: Driver/fixed-line-length.f90
>   | 2.99s: Flang :: Driver/falias-analysis.f90
>   | 2.79s: Flang :: Fir/convert-to-llvm.fir
>   | 2.77s: Flang :: Driver/input-from-stdin/input-from-stdin.f90
> ```
> 
> They don't seem to contain the tests that you enabled in this PR. Sorry, I am probably missing something here, but could you point out why this list is different?

So the tests run and lit report success but for a few of these tests, it hangs after that. It is not yet clear why.

**Pull request closed without merging**
