### PR TITLE
[DebugInfo][SCCPSolver] Fix missing debug locations

### LINKED ISSUE #98875: [DebugInfo][SCCPSolver] Missing debug location updates
The functions replaceSignedInst() and removeNonFeasibleEdges() do not propagate the debug locations to the newly created instructions.

```
// Wire up the new instruction and update state.
assert(NewInst && "Expected replacement instruction");
NewInst->takeName(&Inst);
InsertedValues.insert(NewInst);
Inst.replaceAllUsesWith(NewInst);
Solver.removeLatticeValueFor(&Inst);
Inst.eraseFromParent();
```

```
BranchInst::Create(OnlyFeasibleSuccessor, BB);
TI->eraseFromParent();
```

### PR DESCRIPTION
**Pull request by svs-quic**
Fixes #98875

### CODE REVIEW

**Comment by svs-quic** [comment]
@OCHyams @jryans could you review this please?

**Review by OCHyams — APPROVED** [review]
LGTM, thank you

**Comment by svs-quic** [comment]
> LGTM, thank you

Could you please merge this? Don't have permission to do that.

**Comment by OCHyams** [comment]
👍 will do tomorrow morning

**Pull request merged**
