### PR TITLE
[RISCV] Restrict combineOp_VLToVWOp_VL w/ bf16 to vfwmadd_vl with zvfbfwma

### PR DESCRIPTION
**Pull request by lukel97**
We currently make sure to check that if folding an op to an f16 widening op that we have zvfh. We need to do the same for bf16 vectors, but with the further restriction that we can only combine vfmadd_vl to vfwmadd_vl (to get vfwmaccbf16.v{v,f}).

The added test case currently crashes because we try to fold an add to a bf16 widening add, which doesn't exist in zvfbfmin or zvfbfwma

This moves the checks into the extension support checks to keep it one place.

### CODE REVIEW

**Review by sun-jacobi — APPROVED** [review]
Nice catch! Thank you :)

**Comment by topperc** [comment]
Do we need to do this check when we check the other users too?

```
    auto AppendUsersIfNeeded = [&Worklist, &Subtarget,                           
                                &Inserted](const NodeExtensionHelper &Op) {      
      if (Op.needToPromoteOtherUsers()) {                                        
        for (SDNode::use_iterator UI = Op.OrigOperand->use_begin(),              
                                  UE = Op.OrigOperand->use_end();                
             UI != UE; ++UI) {                                                   
          SDNode *TheUse = *UI;                                                  
          if (!NodeExtensionHelper::isSupportedRoot(TheUse, Subtarget))          
            return false;                                                        
          // We only support the first 2 operands of FMA.                        
          if (UI.getOperandNo() >= 2)                                            
            return false;                                                        
          if (Inserted.insert(TheUse).second)                                    
            Worklist.push_back(TheUse);                                          
        }                                                                        
      }                                                                          
      return true;                                                               
    }; 
```

**Comment by lukel97** [comment]
> Do we need to do this check when we check the other users too?
> 
> ```
>     auto AppendUsersIfNeeded = [&Worklist, &Subtarget,                           
>                                 &Inserted](const NodeExtensionHelper &Op) {      
>       if (Op.needToPromoteOtherUsers()) {                                        
>         for (SDNode::use_iterator UI = Op.OrigOperand->use_begin(),              
>                                   UE = Op.OrigOperand->use_end();                
>              UI != UE; ++UI) {                                                   
>           SDNode *TheUse = *UI;                                                  
>           if (!NodeExtensionHelper::isSupportedRoot(TheUse, Subtarget))          
>             return false;                                                        
>           // We only support the first 2 operands of FMA.                        
>           if (UI.getOperandNo() >= 2)                                            
>             return false;                                                        
>           if (Inserted.insert(TheUse).second)                                    
>             Worklist.push_back(TheUse);                                          
>         }                                                                        
>       }                                                                          
>       return true;                                                               
>     }; 
> ```

If I'm reading this right, won't the other users of the extended bf16 ops go back onto the worklist, where they'll then have their LHS/RHS checked through the same NodeExtensionHelper constructor?

**Comment by topperc** [comment]
> > Do we need to do this check when we check the other users too?
> > ```
> >     auto AppendUsersIfNeeded = [&Worklist, &Subtarget,                           
> >                                 &Inserted](const NodeExtensionHelper &Op) {      
> >       if (Op.needToPromoteOtherUsers()) {                                        
> >         for (SDNode::use_iterator UI = Op.OrigOperand->use_begin(),              
> >                                   UE = Op.OrigOperand->use_end();                
> >              UI != UE; ++UI) {                                                   
> >           SDNode *TheUse = *UI;                                                  
> >           if (!NodeExtensionHelper::isSupportedRoot(TheUse, Subtarget))          
> >             return false;                                                        
> >           // We only support the first 2 operands of FMA.                        
> >           if (UI.getOperandNo() >= 2)                                            
> >             return false;                                                        
> >           if (Inserted.insert(TheUse).second)                                    
> >             Worklist.push_back(TheUse);                                          
> >         }                                                                        
> >       }                                                                          
> >       return true;                                                               
> >     }; 
> > ```
> 
> If I'm reading this right, won't the other users of the extended bf16 ops go back onto the worklist, where they'll then have their LHS/RHS checked through the same NodeExtensionHelper constructor? With Root now set to the new user

I think `AppendUsersIfNeeded` is responsible for checking if all uses of the extend can be converted to a widening operation. If we have an FMA and an FADD using the same bf16 fp_extend, will be turn the FMA into a widening extned, but leave the FADD using the original extend?

**Comment by lukel97** [comment]
> If we have an FMA and an FADD using the same bf16 fp_extend, will be turn the FMA into a widening extned, but leave the FADD using the original extend?

I think all of the users need to match successfully before anything is actually widened:

```c++
    // Right now we do an all or nothing approach.
    if (!Matched)
      return SDValue();
  }
```

The materialization step happens after we go through everything on the worklist. I added a test case to double check this

**Review by topperc — APPROVED** [review]
LGTM

**Pull request merged**
