### PR TITLE
[AMDGPU] Remove unused amdgpu-disable-structurizer flag

### PR DESCRIPTION
**Pull request by jmmartinez**

### CODE REVIEW

**Review by jayfoad — APPROVED** [review]
LGTM. We could probably remove amdgpu-enable-structurizer-workarounds too.

**Review by ssahasra — APPROVED** [review]
Thank you! That option was my mess and I forgot to clean it up!

**Comment by ssahasra** [comment]
> LGTM. We could probably remove amdgpu-enable-structurizer-workarounds too.

Yes please! I don't think there is any pipeline in graphics or compute that works without the workarounds anymore.

**Comment by jmmartinez** [comment]
Last PR: https://github.com/llvm/llvm-project/pull/105819

**Pull request merged**
