### PR TITLE
[clang][RISCV] Support RVV bfloat16 C intrinsics

### PR DESCRIPTION
**Pull request by 4vtomat**
It follows the interface defined here:
https://github.com/riscv-non-isa/rvv-intrinsic-doc/pull/293

### CODE REVIEW

**Comment by kito-cheng** [comment]
vfncvtbf16.c, vfwcvtbf16.c and vfwmaccbf16.c already in the LLVM repo, so I think those files could removed from this PR?

**Comment by 4vtomat** [comment]
Oh, I forgot to remove them. Or do you think they should be moved to bfloat folder to make them consistent?

**Comment by kito-cheng** [comment]
> Oh, I forgot to remove them. Or do you think they should be moved to bfloat folder to make them consistent?

Remove files from this PR, that should be a separated NFC PR for moving those files, but I am fine to keep those file in same place :)

**Review by kito-cheng — APPROVED** [review]
LGTM

**Pull request merged**
