### PR TITLE
[RISCV] Don't forward AVL in VSETVLIInfo if it would clobber other definitions

### PR DESCRIPTION
**Pull request by lukel97**
This fixes a crash found when compiling OpenBLAS with -mllvm -verify-machineinstrs.

When we "forward" the AVL from the output of a vsetvli, we might have to extend the LiveInterval of the AVL to where insert the new vsetvli.

Most of the time we are able to extend the LiveInterval because there's only one val num (definition) for the register. But PHI elimination can assign multiple values to the same register, in which case we end up clobbering a different val num when extending:

    %x = PseudoVSETVLI %avl, ...
    %avl = ADDI ...
    %v = PseudoVADD ..., avl=%x
    ; %avl is forwarded to PseudoVADD:
    %x = PseudoVSETVLI %avl, ...
    %avl = ADDI ...
    %v = PseudoVADD ..., avl=%avl

Here there's no way to extend the %avl from the vsetvli since %avl is redefined, i.e. we have two val nums.

This fixes it by only forwarding it when we have exactly one val num, where it should be safe to extend it.

### CODE REVIEW

**Review by BeMg — APPROVED** [review]
LGTM

**Comment by preames** [comment]
If I'm following the logic of this patch, don't we need to adjust the equally-zero reasoning in transferBefore as well?  That extends the live range of an AVL too doesn't it?

If so, I think we're also missing an assert in insertVSETVLI that the AVL we're trying to extend has a single def.

**Comment by preames** [comment]
As another possible approach to this problem... could we create a new virtual register for the forwarded AVL, use a COPY from the existing range (within it's existing live range), and then a use of the new virtreg at the use point?  (Thinking specifically in the case we can't extend the existing use.)  This would avoid the need to detect the "illegal to forward" case early.

**Comment by lukel97** [comment]
> If I'm following the logic of this patch, don't we need to adjust the equally-zero reasoning in transferBefore as well? That extends the live range of an AVL too doesn't it?
>
> If so, I think we're also missing an assert in insertVSETVLI that the AVL we're trying to extend has a single def.

I've added an assert in 5ab755c972327b4d2c118db9b694d199a981579f. The AVL can have multiple defs but in all these cases register is already live at the point (and so extending it is a noop I believe).

I think you're right about the equally-zero reasoning though, but I can't seem to get it to trigger the above assertion. Here's my thinking of the different cases that can occur when inserting a vsetvli with a register AVL:

The AVL doesn't need extended:
  - The AVL is from the AVL operand of the pseudo. Already live at that point

The AVL register might need extended:
  -  The AVL was forwarded: we check that it has one value, and this should only happen when the vsetvli dominates the pseudo so it should be available on all paths.
  - A PseudoVMV_S_X only demands AVL zeroness, so transferBefore keeps the previous info's AVL which is an `ADDI $x0, >=32`. But this never seems to trigger the assertion because in this case we always emit a vl-preserving vsetvli x0,x0, and don't end up using the register.

I think the latter case is mostly working by coincidence. #89089 defers the x0,x0 form and would expose the issue. I'll have a think and see if I can get anywhere with your COPY idea.

**Comment by lukel97** [comment]
> As another possible approach to this problem... could we create a new virtual register for the forwarded AVL, use a COPY from the existing range (within it's existing live range), and then a use of the new virtreg at the use point? (Thinking specifically in the case we can't extend the existing use.) This would avoid the need to detect the "illegal to forward" case early.

I've submitted a PR for this in #98342, this turned out to be a good idea. I'd rather we're able to handle non-extendible values via a fallback, than have to conservatively check for extendibility in every place we mutate the AVL, which is more likely to have cases fall through the cracks.

**Pull request merged**
