### PR TITLE
[clang-format] Handle variable declarations in BreakAfterAttributes

### LINKED ISSUE #71563: [FR] clang-format option for line breaks after [[attributes]] in function scope
Currently there is no clang-format option for attributes like `[[maybe_unused]]` or `[[likely]]`. Right now clang-format will always force them onto the same line as the item.

```c++
int main()
{
    [[maybe_unused]]
    int y = 5;

    [[likely]]
    if (5 == 5) {}
    else {}
}
```

will always end up as, with no option to change the behavior

```c++
int main()
{
    [[maybe_unused]] int y = 5;

    [[likely]] if (5 == 5) {}
    else {}
//  ~~~~
//  ^ Different indentation for 'if' and corresponding 'else' (clang-tidy readability-misleading-indentation)
}
```

This is especially bothersome for the `if` because it leads to clang-tidy to report the misleading indentation.

It would be nice if there were an option for line breaks after such attributes.

### PR DESCRIPTION
**Pull request by owenca**
Also cleaned up some old test cases.

Fixes #71563.

### CODE REVIEW

**Review by rymiel — APPROVED** [review]
However this doesn't address the second part of the linked issue (with the `if`) does it?

**Comment by owenca** [comment]
> However this doesn't address the second part of the linked issue (with the `if`) does it?

Nope! That part is a duplicate of #64474. I was going to add a note in #71563 before merging this PR but now just saw that @FalcoGer closed the old issue and opened the new one, which is essentially the same.

**Review by HazardyKnusperkeks — APPROVED** [review]

**Comment by Meinersbur** [comment]
@owenca  You can run `ninja polly-update-format` which will use the in-tree `clang-format` to reformat all files. `git add` its changes, `git add --amend`, then push.

**Comment by owenca** [comment]
@Meinersbur thanks for the info!

**Pull request merged**
