### PR TITLE
[Flang][OpenMP] Derived type member map fortran offload runtime tests

### PR DESCRIPTION
**Pull request by agozillon**
This is a large series of runtime tests that help to add coverage for the specific cases intended to be supported by the PR stack
that extends derived type map support in Flang+OpenMP. Primarily this will add functionality coverage, there's cases where
things may work, but not optimally (or at least similarly to the status quo in Clang), addiitonal IR tests are added in the
relevant segments of the related PRs to test for breakages like that.

### CODE REVIEW

**Review by kparzysz — APPROVED** [review]
This is great.  Thanks.

Do we need a test that maps a complex number explicitly?

**Comment by agozillon** [comment]
> This is great. Thanks.
> 
> Do we need a test that maps a complex number explicitly?

That would be a good addition!

**Review by skatrak — APPROVED** [review]
Thank you Andrew, LGTM.

**Comment by agozillon** [comment]
I made a bit of a mistake not using SPR to land this PR series, so i've ended up having to directly commit the PR, the associated commit for this PR can be found here: https://github.com/llvm/llvm-project/commit/7fd6cb293975b05406e24aba1cc8e83275cb6bf9

**Pull request merged**
