### PR TITLE
[CMake][libclc] Improve dependencies to avoid build errors

### PR DESCRIPTION
**Pull request by tcreech-intel**
With the Makefile generator and particularly high build parallelism some intermediate dependencies may be generated redundantly and concurrently, leading to build failures.

To fix this, arrange for libclc's add_custom_commands to depend on targets in addition to files.

This follows CMake documentation's[^1] guidance on add_custom_command:

> Do not list the output in more than one independent target that may
> build in parallel or the instances of the rule may conflict. Instead,
> use the add_custom_target() command to drive the command and make the
> other targets depend on that one.

Eliminating the redundant commands also improves build times.

[^1]: https://cmake.org/cmake/help/v3.29/command/add_custom_command.html

### CODE REVIEW

**Comment by frasercrmck** [comment]
Hmm, isn't CMake fun? Thanks for looking into this.

Unfortunately the file-level dependencies are there for a reason. With this patch, if I `rm builtins.link.nvptx64--.bc` and build `builtins.opt.nvptx64--` (with `ninja`), it builds the `link` target but doesn't actually rebuild the `opt` target. On `main`, it does do this. We need to preserve that behaviour, or developers will see stale builds and that will lead to all sorts of problems.

I found [example #5 of this example](https://samthursfield.wordpress.com/2015/11/21/cmake-dependencies-between-targets-and-files-and-custom-commands) interesting when I was initially implementing this. CMake's dependencies are really strange.

Going by the documentation you link, could we have _both_ the file- and the target-level dependency? Note how the [example](https://cmake.org/cmake/help/v3.29/command/add_custom_command.html#example-generating-files-for-multiple-targets) has `DEPENDS table.csv generate_table_csv` in *both* parallel targets, so the file-level dependency `foo.csv` *is* being used twice - but also supplying the target-level dependency prevents it from being a race condition?

**Comment by tcreech-intel** [comment]
Yes, the article you link to is highly relevant. Without this PR we're hitting the problem described in example <span>#</span>4.

We can promote the issue to a build failure by choosing a custom command which can't run concurrently with itself:
```cmake
cmake_minimum_required(VERSION 3.2)

add_custom_command(
    OUTPUT gen
    # Try to grab a lock and fail immediately if we can't:
    COMMAND flock -x -n gen.lock sleep 1
    COMMAND cmake -E echo Hello > gen
    )

add_custom_target(
    my-all-1 ALL DEPENDS gen
    )

add_custom_target(
    my-all-2 ALL DEPENDS gen
    )
```

With the above `make` will succeed, but `make -j2` will fail. The issue is not exposed with Ninja.
This is the same behavior I see in libclc today, except more jobs are needed.
Adding an intermediate target and depending on both the new target and the file does seem to fix all of our problems.

I've added the file dependencies back in b707fc7dea2e, and I think it fixes the build issue while preserving the incremental build behavior you described.
Could you please give it a try?

**Review by frasercrmck — APPROVED** [review]
LGTM, thank you!

**Comment by frasercrmck** [comment]
> Yes, the article you link to is highly relevant. Without this PR we're hitting the problem described in example #4.
> 
> We can promote the issue to a build failure by choosing a custom command which can't run concurrently with itself:
> 
> ```cmake
> cmake_minimum_required(VERSION 3.2)
> 
> add_custom_command(
>     OUTPUT gen
>     # Try to grab a lock and fail immediately if we can't:
>     COMMAND flock -x -n gen.lock sleep 1
>     COMMAND cmake -E echo Hello > gen
>     )
> 
> add_custom_target(
>     my-all-1 ALL DEPENDS gen
>     )
> 
> add_custom_target(
>     my-all-2 ALL DEPENDS gen
>     )
> ```
> 
> With the above `make` will succeed, but `make -j2` will fail. The issue is not exposed with Ninja. This is the same behavior I see in libclc today, except more jobs are needed. Adding an intermediate target and depending on both the new target and the file does seem to fix all of our problems.
> 
> I've added the file dependencies back in [b707fc7](https://github.com/llvm/llvm-project/commit/b707fc7dea2e5e57bc3e4f01e27b9ca7bbf0e398), and I think it fixes the build issue while preserving the incremental build behavior you described. Could you please give it a try?

Brilliant, thanks. I have played around and see that incremental builds appear to work as intended. I've tried deleting and `touch`ing various files and full rebuilds and partial rebuilds do what I'd expect.

Thanks also for pointing out I've already read about this exact issue (example #4) and missed it! It's a real shame there isn't a better framework for testing CMake and build generators themselves.

**Pull request merged**
