### PR TITLE
[WebAssembly] Update generic and bleeding-edge CPUs

### PR DESCRIPTION
**Pull request by aheejin**
This updates the list of features in 'generic' and 'bleeding-edge' CPUs in the backend to match
https://github.com/llvm/llvm-project/blob/4e0a0eae58f7a6998866719f7eb970096a2a52e9/clang/lib/Basic/Targets/WebAssembly.cpp#L150-L178

This updates existing CodeGen tests in a way that, if a test has separate RUN lines for a reference-types test and a non-reference-types test, I added -mattr=-reference-types to the no-reftype test's RUN command line. I didn't delete existing -mattr=+reference-types lines in reftype tests because having it helps readability.

Also, when tests is not really about reference-types but they have to updated because they happen to contain call_indirect lines because now call_indirect will take __indirect_function_table as an argument, I just added the table argument to the expected output.

`target-features-cpus.ll` has been updated reflecting the newly added features.

### CODE REVIEW

**Review by tlively — APPROVED** [review]
LGTM!

**Comment by aheejin** [comment]
Sorry, apparently there are tests to be updated 😅

https://github.com/llvm/llvm-project/pull/96584/commits/3186ad74e147067895983c7b322833df1ab26b57 updates tests in a way that, if a test has separate `RUN` lines for a reference-types test and a non-reference-types test, I added `-mattr=-reference-types` to the no-reftype test's `RUN` command line. I didn't delete existing `-mattr=+reference-types` lines in reftype tests because having it helps readability.

Also, when tests is not really about reference-types but they have to updated because they happen to contain `call_indirect` lines because now `call_indirect` will take `__indirect_function_table` as an argument, I just added the table argument to the expected output.

I think https://github.com/llvm/llvm-project/blob/main/llvm/test/CodeGen/WebAssembly/target-features.ll better be updated separately... Will upload a PR for that and land this after that one lands.

**Comment by tlively** [comment]
Test changes so far look good 👍

**Comment by aheejin** [comment]
Will land this; please let me know if you have any other comments.

**Comment by CryZe** [comment]
Some feedback: This broke the majority of the JavaScript bundlers (webpack and co.) which are commonly built on top of `webassemblyjs` which is very unmaintained and does not support `reference-types`. I'm not sure, but it may be worth reverting.

**Comment by dschuff** [comment]
Can you say more about what the bundlers are doing, and how they are doing it?
I don't want to be breaking people, but also we surely can't freeze LLVM forever just because some other tool is unmaintained. We are actually planning to enable bulk memory and nontrapping-fptoint soon as well.

**Comment by dschuff** [comment]
Interestingly, it looks like the decoder in webassemblyjs [already](https://github.com/xtuc/webassemblyjs/blob/master/packages/wasm-parser/src/decoder.js#L894) decodes the table index as an LEB.

**Comment by dschuff** [comment]
actually... sorry,  let's have this conversation on https://github.com/WebAssembly/tool-conventions/issues/233 rather than forking it here.

**Pull request merged**
