### PR TITLE
[clang] Preserve UDL nodes in RemoveNestedImmediateInvocation

### LINKED ISSUE #63898: Clangd puts parameter name hint on UDLs
This is confusing because UDLs are not visibly a function call.

```cpp
int inline consteval operator""_lit(unsigned long long val) { return 0; }

int main() {
    return 3_lit;
}
```

When the above is annotated by clangd, it puts `val: ` in front of `3_lit`, it looks like this:
```cpp
int main() {
    return val: 3_lit;
}
```

### PR DESCRIPTION
**Pull request by zyn0217**
D63960 performs a tree transformation on AST to prevent evaluating constant expressions eagerly by removing recorded immediate consteval invocations from subexpressions. (See https://reviews.llvm.org/D63960#inline-600736 for its motivation.)

However, the UDL node has been replaced with a CallExpr in the default TreeTransform since ca844ab0 (inadvertently?). This confuses clangd as it relies on the exact AST node type to decide whether or not to present inlay hints for an expression.

With regard to the fix, I think it's enough to return the UDL expression as-is during the transformation: We've bound it to temporary in its construction, and there's no ConstantExpr to visit under a UDL.

Fixes https://github.com/llvm/llvm-project/issues/63898.

### CODE REVIEW

**Comment by zyn0217** [comment]
Ping~ Looking for a review :)

**Comment by HighCommander4** [comment]
I wonder if `TreeTransform::TransformUserDefinedLiteral()` should be doing something like `RebuildUserDefinedLiteral()`.

Anyways, the patch looks reasonable to me but someone more familiar with Sema should review it.

**Comment by zyn0217** [comment]
Invite @shafik and @cor3ntin to have a look at this.

My apologies if I'm churning anyone's review backlog. Honestly, I have no idea who the appropriate reviewer/code owner is. :(

**Comment by cor3ntin** [comment]
@zyn0217 Can you add a release note indicating that #63898 was fixed? Otherwise it looks good to me. 
Sorry for the long delay, feel free to ping me again

**Comment by zyn0217** [comment]
No problem! And here it is.
PTAL, thanks! @cor3ntin

**Review by cor3ntin — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
