### PR TITLE
[OpenMP][NFC] Refactor to prepare for SDMA engine patch

### PR DESCRIPTION
**Pull request by jplehr**
This is a refactoring in preparation of another patch that I'm working on.

Right now, we dispatch the memory copies via `hsa_amd_memory_async_copy`.
This selects the default SDMA engine for the data transfer, which may not be ideal.
With ROCm 5.7 a new API is introduced that allows to select the SDMA engine
used for a specific transfer. In order to make the functional changes more visible,
I'd like to first land this NFC.

### CODE REVIEW

**Review by shiltian — APPROVED** [review]
It looks like this patch simply moves implementation out of the class, though I don't see why this can make the following changes more visible.

**Comment by jplehr** [comment]
This was accepted faster than I anticipated, sorry for the delay.

The changes will be in the moved code, so I thought it would be easier to split move and edit.
However, I'll hold of with the actual feature patch, as I have to solve a different issue first. Should I land this nevertheless, or hold off and pick it up again later?

**Comment by shiltian** [comment]
Either is fine

**Comment by jplehr** [comment]
I decided to do this completely differently. Will close this for now, and open new PR when ready with new implementation.

**Pull request closed without merging**
