### PR TITLE
[clang][DebugInfo] Revert "emit definitions for constant-initialized static data-members"

### PR DESCRIPTION
**Pull request by Michael137**
This commit reverts the changes in https://github.com/llvm/llvm-project/pull/71780 and all of its follow-up patches.

We got reports of the `.debug_names/.debug_gnu_pubnames/gdb_index/etc.` sections growing by a non-trivial amount for some large projects. While GCC emits definitions for static data member constants into the Names index, they do so *only* for explicitly `constexpr` members. We were indexing *all* constant-initialized const-static members, which is likely where the significant size difference comes from. However, only emitting explicitly `constexpr` variables into the index doesn't seem like a good way forward, since from clang's perspective `const`-static integrals are `constexpr` too, and that shouldn't be any different in the debug-info component. Also, as new code moves to `constexpr` instead of `const` static for constants, such solution would just delay the growth of the Names index.

To prevent the size regression we revert to not emitting definitions for static data-members that have no location.

To support access to such constants from LLDB we'll most likely have to have to make LLDB find the constants by looking at the containing class first.

### CODE REVIEW

**Review by cor3ntin — APPROVED** [review]
Do you need me to merge that for you?

**Comment by cor3ntin** [comment]
See https://github.com/llvm/llvm-project/issues/74070

**Comment by Michael137** [comment]
> Do you need me to merge that for you?

Was going to wait until some more people had the chance to look. But if urgent, I don't think there should be any trouble merging this sooner

**Comment by dwblaikie** [comment]
> To support access to such constants from LLDB we'll most likely have to have to make LLDB find the constants by looking at the containing class first.

Tangentially related to: https://discourse.llvm.org/t/rfc-improve-dwarf-5-debug-names-type-lookup-parsing-speed/74151/31?u=dblaikie

Clang/LLVM do know the difference between type-invariant members and type variant ones (type invariant members are in  the `members` list of the `DICompositeType` and variant members have a `scope` that refers to the type but don't appear in the `members` list) - would it be reasonable to not include the invariant members in the accelerator table, but only include the variant ones? Invariant ones can be found by finding any instance of the type in the index, then looking at its members - and for variant members it'd be useful to have them in the index. (though, honestly, I'm not sure how lldb and gdb handle that situation - last time I tested it with gdb, it just saw two different copies of the type and didn't try to unify/aggregate all the variant members... but lldb only creates one copy of the type, so don't know what it does if you've got, say, two member function template instantiations for different template parameters in two different translation units/compile units)

**Comment by mstorsjo** [comment]
Could we please land this now?

**Comment by Michael137** [comment]
> > To support access to such constants from LLDB we'll most likely have to have to make LLDB find the constants by looking at the containing class first.
> 
> Tangentially related to: https://discourse.llvm.org/t/rfc-improve-dwarf-5-debug-names-type-lookup-parsing-speed/74151/31?u=dblaikie
> 
> Clang/LLVM do know the difference between type-invariant members and type variant ones (type invariant members are in the `members` list of the `DICompositeType` and variant members have a `scope` that refers to the type but don't appear in the `members` list) - would it be reasonable to not include the invariant members in the accelerator table, but only include the variant ones? Invariant ones can be found by finding any instance of the type in the index, then looking at its members - and for variant members it'd be useful to have them in the index. (though, honestly, I'm not sure how lldb and gdb handle that situation - last time I tested it with gdb, it just saw two different copies of the type and didn't try to unify/aggregate all the variant members... but lldb only creates one copy of the type, so don't know what it does if you've got, say, two member function template instantiations for different template parameters in two different translation units/compile units)

I'll merge the PR for now to unblock and address this later

**Pull request merged**
