### PR TITLE
[llvm] Add support for zero-width integers in MathExtras.h

### PR DESCRIPTION
**Pull request by Moxinilian**
MLIR uses zero-width integers, but also re-uses integer logic from LLVM to avoid duplication. This creates issues when LLVM logic is used in MLIR on integers which can be zero-width. In order to avoid special-casing the bitwidth-related logic in MLIR, this PR adds support for zero-width integers in LLVM's MathExtras (and consequently APInt).

While most of the logic in theory works the same way out of the box, because bitshifting right by the entire bitwidth in C++ is undefined behavior instead of being zero, some special cases had to be added. Fortunately, it seems like the performance penalty is small. In x86, this usually yields the addition of a predicated conditional move. I checked that no branch is inserted in Arm too.

This happens to fix a crash in `arith.extsi` canonicalization in MLIR. I think a follow-up PR to add tests for i0 in arith would be beneficial.

### CODE REVIEW

**Comment by Moxinilian** [comment]
> ⚠️ We detected that you are using a GitHub private e-mail address to contribute to the repo. Please turn off [Keep my email addresses private](https://github.com/settings/emails) setting in your account. See [LLVM Discourse](https://discourse.llvm.org/t/hidden-emails-on-github-should-we-do-something-about-it) for more information.

I am confused by this. I exclusively use this private e-mail address on GitHub. What is wrong with it?

**Comment by makslevental** [comment]
Just chiming in to comment there's a downstream need for support for zero width integers in CIRCT that goes back ~2 years https://github.com/llvm/circt/issues/2660. So :+1: from me.

**Review by zero9178 — COMMENTED** [review]
Code generally looks good to me, although I'd personally replace many of `N == 0 ? x : y` with
```
if (N == 0)
  return x;
return y;
```
this is imo more readable especially when y is a relatively large expression.

Regarding the state of 0-bit support, this PR only handles `sext` right? Is everything else already supported and tested? Would it be more accurate to say in the PR title and description that this only adds support for `sext` of 0-bit integers?

**Comment by Moxinilian** [comment]
I have walked through the entire file to check that i0 is supported. Although it’s probably a good ideas to add tests even where it works to make sure there is no regression. I can look at that, probably after EuroLLVM.

**Comment by Moxinilian** [comment]
@zero9178 So it turns out that indeed everything else is either not dependent on bitwidth or tested for 0. One of the functions in fact already accomodated for the undefined behavior of shifting a 64-bit value by 64 in the zero case. I updated it to your recommended syntax for consistency as I agree it makes it easier to parse.

**Review by zero9178 — APPROVED** [review]
Sounds good, thank you!

**Pull request merged**
