### PR TITLE
The real option name and not the alias used is displayed in msgs when using a config file

### PR DESCRIPTION
**Pull request by perry-ca**
An example of this is the -mpure-code option.  Without a config file being used, an error message will print `-mpure-code`.  But if a config file is used, the error message will print `-mexecute-only`.

### CODE REVIEW

**Comment by perry-ca** [comment]
@redstar @abhina-sree Could you review this.  Thanks

**Review by abhina-sree — APPROVED** [review]
LGTM

**Comment by perry-ca** [comment]
@mgorny could you review this too.  Thanks.

**Review by mgorny — APPROVED** [review]
Seems to make sense and is roughly consistent with the code above.

**Pull request merged**
