### PR TITLE
[KCFI][NFC] Rename the !kcfi_type Function metadata to !cfi_type

### PR DESCRIPTION
**Pull request by mylai-mtk**
According to the comments in <https://reviews.llvm.org/D119296>, which introduces the KCFI sanitizer, the data structures of KCFI should avoid embedding the term "kcfi" in their names so that later/new CFI mechanisms can make use of the data structures, however, those "kcfi" were not removed completely. This patch further removes those "kcfi" terms from the Function metadata !kcfi_type so that the RISC-V Zicfilp extension code generation can reuse the same data path as the KCFI sanitizer to pass function-specific CFI labels.

### CODE REVIEW

**Comment by MaskRay** [comment]
I understand the intention to generalize naming, but I feel that there is significance chance that the over-generalization may not work with the alternative CFI schemes, and this change could turn out to be needed when the other schemes go with different IR constructs.

I feel that we should make such renaming at this time.

BTW: when kcfi was proposed, I felt that it was not a good name because the strategy could only cover a very limited subset of LTO-based `-fsanitize=cfi`. kcfi is just like a brand name.

**Review by MaskRay — CHANGES_REQUESTED** [review]
.

**Comment by mylai-mtk** [comment]
Excuse me, @MaskRay  . I don't understand your stance: 

> I understand the intention to generalize naming, but I feel that there is significance chance that the over-generalization may not work with the alternative CFI schemes, and this change could turn out to be needed when the other schemes go with different IR constructs.

I get that this renaming is an over-generalization, and more changes in the future may be required should different CFI schemes arise, so I guess you're suggesting maybe we should not do the renaming.

> I feel that we should make such renaming at this time.

But then you propose that we make the renaming now. (??)

I'm quite confused by the conflict of these two paragraphs. Can you talk more about your view?

**Comment by MaskRay** [comment]
> > I feel that we should make such renaming at this time.
> 
> But then you propose that we make the renaming now. (??)

Sorry, it's a typo. We should not do the renaming, unless there is strong argument renaming is useful.

**Comment by mylai-mtk** [comment]
@MaskRay Sure, I also agree that `!cfi_type` is a too general name and covers too little possibility for its name. I picked this approach instead of adding RISC-V-specific metadata nodes just to avoid adding RISC-V specifics to the conceptually backend-neutral LLVM IR. However, if this approach looks too general, maybe it's better to just use RISC-V-specific metadata nodes.
(I'm closing this PR then, since it's not a good idea.)

**Pull request closed without merging**
