### PR TITLE
[flang] Integrate the option -flang-experimental-integer-overflow into -fno-wrapv

### PR DESCRIPTION
**Pull request by yus3710-fj**
nsw is now added to do-variable increment when -fno-wrapv is enabled as GFortran seems to do.
That means the option introduced by #91579 isn't necessary any more.

Note that the feature of -flang-experimental-integer-overflow is enabled by default.

### CODE REVIEW

**Review by tblah — APPROVED** [review]
Thanks! LGTM

**Comment by tblah** [comment]
@yus3710-fj  after this patch we get a 7-10% slowdown for 503.bwaves_r from SPEC2017. I built with `-Ofast -mcpu=native -fuse-ld=lld -flto`

As I understood it, the previous patch was supposed to enable your transformation by default, and this one was only supposed to clean up old flags. Did I understand wrong?

Anyway please could you revert this patch and/or fix the regression.

**Comment by yus3710-fj** [comment]
Thank you for the information, @tblah. I'll revert this.

> As I understood it, the previous patch was supposed to enable your transformation by default, and this one was only supposed to clean up old flags. Did I understand wrong?

This patch also enables some transformation by default. They would affect the performance. I apologize that I didn't check performance regression.

**Comment by yus3710-fj** [comment]
> @yus3710-fj after this patch we get a 7-10% slowdown for 503.bwaves_r from SPEC2017. I built with `-Ofast -mcpu=native -fuse-ld=lld -flto`

@tblah I'm attempting to reproduce the performance issue on my Grace machine, but have not yet been successful. Could you please provide the measurement conditions?

**Comment by tblah** [comment]
> > @yus3710-fj after this patch we get a 7-10% slowdown for 503.bwaves_r from SPEC2017. I built with `-Ofast -mcpu=native -fuse-ld=lld -flto`
> 
> @tblah I'm attempting to reproduce the performance issue on my Grace machine, but have not yet been successful. Could you please provide the measurement conditions?

Thanks for having a look. I tried on a Grace machine and found a smaller regression of ~2.7%. For this measurement I compared bd6ab32 and the commit immediately before. The flags were as I described above. I am comparing the "base rate" numbers reported by spec.

The previous mesaurement (with the larger regression) was on an aws graviton 3 machine.

**Comment by yus3710-fj** [comment]
I confirmed the performance regression on both Graviton3 and Grace when the value of `copies` is set to 1.

The result of the measurement on Graviton3:
||max|min|avg|
|---|---|---|---|
|before this patch|52.56|52.44|52.518|
|after this patch|48.90 (-7.48%)|48.79 (-7.48%)|48.86 (-7.49%)|

The difference in optimization messages (`-Rpass=.*`):
* `zext` is used instead of `sext` after this patch.
* LICM is promoted by this patch.

I'm investigating why the performance gets worse even though the optimization is promoted.

**Comment by tblah** [comment]
Hi @yus3710-fj, thanks for investigating the cause of the regression.

There was a recent patch which improved bwaves performance: https://github.com/llvm/llvm-project/pull/111853. It seems that since this patch, I no longer see a regression with the integer overflow enabled so I would be happy to re-land your patch. Please feel free to open a new PR.

I think #117318 is still a real issue, just we happen not to run out of registers anymore now that there is better constant propagation.

I tested this on an AWS graviton 3 (neoverse-v1) machine.

**Comment by yus3710-fj** [comment]
Thank you for the informantion, @tblah. I also confirmed that the regression doesn't happen after fbd89bcc6647ed611e579d8f9c38c97b8e6f7936. 
I'm a little concerned that the regression still occurs when LTO is diabled. However, I'd like to reland this patch because this isn't the root cause of the issue.

**Comment by vzakhari** [comment]
Hello! Did anyone notice a performance regression after this PR on exchange2?  I see it on both EPYC 9684X and grace. The slowdown is more than 1.5x.

I verified that performance restores when adding `-fwrapv` with the latest flang compiler. The compilation options are `-Ofast -march=native`.  I will look through LLVM dumps, but please let me know if it is a known problem.

**Comment by tblah** [comment]
> Hello! Did anyone notice a performance regression after this PR on exchange2? I see it on both EPYC 9684X and grace. The slowdown is more than 1.5x.
> 
> I verified that performance restores when adding `-fwrapv` with the latest flang compiler. The compilation options are `-Ofast -march=native`. I will look through LLVM dumps, but please let me know if it is a known problem.

My team doesn't closely monitor V2 performance. Another team looked into it. I'm told that initially there was a slowdown because function specialization was not performed on the last iteration of digits. Then that fixed after https://github.com/llvm/llvm-project/pull/118219 so we are happy on our end.

However if you aren't using LTO then you won't be seeing the function specialization anyway. I'm told that the unspecialized version of digits was worse after this patch because of extra spills in the hot part of the code. To me that sounds similar to the bwaves regression the first time this patch landed. More info here: https://github.com/llvm/llvm-project/issues/117318

**Comment by vzakhari** [comment]
Thank you for the pointers and the information, Tom!  It looks like exchange2 is pretty much the same problem as with bwaves.  I posted a note into https://github.com/llvm/llvm-project/issues/117318

**Pull request merged**
