### PR TITLE
[AArch64] Consistently use EmitToStreamer across the AArch64AsmPrinter

### PR DESCRIPTION
**Pull request by atrosinenko**
In preparation for refactoring the instruction size checks being made by PAuth-related code, switch all instruction emission in AArch64AsmPrinter to using EmitToStreamer function.

Introduce a single-operand overload of `EmitToStreamer(MCInst)`, as the only MCStreamer passed as the first argument is actually `*OutStreamer`. To decrease the number of code lines changed due to clang-format, do not touch the existing calls to two-argument EmitToStreamer function so far.

### CODE REVIEW

**Review by MaskRay — APPROVED** [review]
As you are adding a new function, it's good time to fix the naming case to `emitToStreamer`

**Comment by atrosinenko** [comment]
Thank you for the review!

> As you are adding a new function, it's good time to fix the naming case to `emitToStreamer`

I think renaming `EmitToStreamer` to `emitToStreamer` now may be a bit error-prone, as this function overrides the non-virtual `AsmPrinter::EmitToStreamer`, so in `AArch64AsmParser` there would be two different functions accessible with almost identical names and almost identical implementations.

**Comment by atrosinenko** [comment]
* **#110108** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/110108?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#110107** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/110107?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @atrosinenko and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by david-arm** [comment]
> Thank you for the review!
> 
> > As you are adding a new function, it's good time to fix the naming case to `emitToStreamer`
> 
> I think renaming `EmitToStreamer` to `emitToStreamer` now may be a bit error-prone, as this function overrides the non-virtual `AsmPrinter::EmitToStreamer`, so in `AArch64AsmParser` there would be two different functions accessible with almost identical names and almost identical implementations.

Yeah I agree, and the alternative would be having the single argument emitToStreamer function call EmitToStreamer, which also looks a little odd.

**Review by david-arm — APPROVED** [review]
Seems reasonable to me.

**Pull request merged**
