### PR TITLE
[clang][FMV] Direct-call FMV callees from FMV callers

### PR DESCRIPTION
**Pull request by jroelofs**
… when there is a callee with a matching feature set, and no other higher priority callee.  This optimization helps the inliner see past the ifunc+resolver to the callee that we know it will always land on.

This is a conservative implementation of: https://github.com/llvm/llvm-project/issues/71714

### CODE REVIEW

**Review by erichkeane — COMMENTED** [review]
My immediate response is that this sounds like something that OPT should be doing here, not us.  We typically do NOT do this sort of thing the CFE, and do not want to do opt-type stuff in the CFE. 

Is there good reason that this isn't a part of the inliner?

**Comment by jroelofs** [comment]
My gut feel was that recovering this information from the callee's resolver's body would take heroics if we tried to do it in the backend.

**Comment by erichkeane** [comment]
> My gut feel was that recovering this information from the callee's resolver's body would take heroics if we tried to do it in the backend.

Opt can already see the feature strings in the llvm-attributes, and can introspect into it for the resolver.  I could PERHAPS see value in an llvm-attribute on the resolver to tell OPT to try to look through that (that is, something that says "this is a generated Function MultiVersion resolver, you can trust these conditions match the functions"), but the rest I don't think needs to be in the CFE.

**Comment by jroelofs** [comment]
Fair. I'll give that a shot.

Doing it in opt has another big advantage I only just realized: it allows LTO to do the transformation.

**Comment by labrinea** [comment]
@erichkeane while I agree that Clang might not be the best place for such an optimization, I have some concerns about implementing it in LLVM:
* We cannot distinguish a FMV resolver from any other ifunc resolver.
* There is no information at the LLVM IR level about function versions or which resolver they are associated with. 
* We cannot use target-features to determine version priority since this information is encoded via front-end features in the TargetParser. We can only rely on the resolver's basic block layout under the assumption that predecessor basic blocks correspond to versions of higher priority than successor basic blocks. This is fragile and unreliable:
```
void discoverResolvedIFuncsInPriorityOrder(GlobalIFunc *IFunc) {
  DenseMap<GlobalIFunc *, SmallVector<Function *>> ResolvedIFuncs;

  std::function<void(Value *)> visitValue = [&](Value *V) {
    if (auto *Func = dyn_cast<Function>(V)) {
      ResolvedIFuncs[IFunc].push_back(Func);
    } else if (auto *Sel = dyn_cast<SelectInst>(V)) {
      visitValue(Sel->getTrueValue());
      visitValue(Sel->getFalseValue());
    } else if (auto *Phi = dyn_cast<PHINode>(V)) {
      for (unsigned I = 0, E = Phi->getNumIncomingValues(); I != E; ++I)
        visitValue(Phi->getIncomingValue(I));
    }
  };

  for (BasicBlock &BB : *IFunc->getResolverFunction())
    if (auto *Ret = dyn_cast_or_null<ReturnInst>(BB.getTerminator()))
      visitValue(Ret->getReturnValue());
  // discard default
  if (!ResolvedIFuncs[IFunc].empty())
    ResolvedIFuncs[IFunc].pop_back();
}
```

**Comment by erichkeane** [comment]
I'd be OK with Clang providing some level of metadata to clarify which is an FMV, and what our target features are.  But this sort of analysis still needs to happen in LLVM.

**Comment by jroelofs** [comment]
I'm not sure llvm needs to know the priorities. I haven't had time to work on this, but my plan was to have something that attempts to step through the resolver instruction by instruction with known bits for the value loaded from `__aarch64_cpu_features.features` according to the caller's target features. If the return value is known, then we can fold away the resolver for that call site. If we encounter a loop, a call, or some other pattern we don't understand, then bail & leave that call site alone.

**Comment by erichkeane** [comment]
> I'm not sure llvm needs to know the priorities. I haven't had time to work on this, but my plan was to have something that attempts to step through the resolver instruction by instruction with known bits for the value loaded from `__aarch64_cpu_features.features` according to the caller's target features. If the return value is known, then we can fold away the resolver for that call site. If we encounter a loop, a call, or some other pattern we don't understand, then bail & leave that call site alone.

That seems sensible to me.  It would be nice to be able to recognize this /get this optimization for 'hand rolled' resolvers as well.

**Pull request closed without merging**
