### PR TITLE
[mlir] Move InlinerInterface from Transforms to Interfaces.

### PR DESCRIPTION
**Pull request by chsigg**
Most interfaces live in the mlir/Interfaces directory, but the InlinerInterface was defined (I think for historical reasons) in `mlir/Transforms/Utils/InliningUtils.h`.

Telling from the bazel BUILD files (I'm not familiar with the CMake build), this created circular dependencies which required various dialect targets to depend on `InliningUtils.h`. I was trying to clean this up, and the best solution seems to be to move the InlinerInterface from the Transforms directory to Interfaces.

### CODE REVIEW

**Comment by joker-eph** [comment]
Nit: your PR does not have a description. The title provides the "what" but the description should provide the context / the "why".

**Comment by chsigg** [comment]
> Nit: your PR does not have a description. The title provides the "what" but the description should provide the context / the "why".

Thanks, I added a description.

**Comment by joker-eph** [comment]
I don't see this layout as historical actually: to me the Interfaces folder is meant I believe to host the interfaces that aren't tied to specific transforms, instead they were meant for the common traits of the IR, basically what is needed during ODS generation or what describes the IR more generically than what's tied to a specific transform (like control-flow interface). 

Looking at the list right now, there are a quite a few interfaces which don't belong here and are instead directly attached to a specific transform: to me they don't belong here.

@Mogball, @jpienaar, and @ftynse for the layering discussion here.

**Comment by chsigg** [comment]
I see.

Another way to solve the circular dependency is to create a separate bazel target for just InliningUtils. After that, TransformUtils can be merged into Transforms without creating circular dependencies. Sorry for being bazel-centric here. I'm assuming that with CMake the layering is not as strict, but the layering is still not ideal. What is the relationship of MLIRTransform and MLIRTransformUtils?

Would it be better to move the InlinerInterface to a separate file and CMake library that still lives under Transforms/Utils?

**Comment by chsigg** [comment]
> to me the Interfaces folder is meant I believe to host the interfaces that aren't tied to specific transforms, instead they were meant for the common traits of the IR, basically what is needed during ODS generation or what describes the IR more generically than what's tied to a specific transform (like control-flow interface).

I see your point from the perspective of transform-specific interfaces. If you looked at it from a dialect perspective, which currently needs to depend on stuff from transform, the change suggested here might be easier to motivate.

That said, I'm happy to get guidance about what makes the most sense. I primarily see all the bazel targets that export the InliningUtils.h header, sticking out like sore thumbs.

**Comment by joker-eph** [comment]
CMake is indeed loose with header includes, and we're taking advantage of this for interfaces includes which are "header only" for implementing in a dialect.
For example that's why the builtin dialect can include these interfaces and not create a circular dependency.

I don't know how to model this with Bazel: would you create a "header only target" just for the header inclusion and another one for the link?

**Comment by Mogball** [comment]
+1 to keeping transform specific interfaces in the TransformUtils library. The `mlir/Interfaces` directory, as Mehdi says, I think definitely reflects stronger and more first-class elements of the IR, like control-flow. I don't understand how this creates a circular dependency. What dialect depends on TransformUtils that Transform also depends on? You can always create an `InlinerInterface` library that lives under `Transform/Utils`.

**Comment by ftynse** [comment]
A couple of counter-points, but I don't have a strong opinion.

- Generally speaking, we have too many places where interfaces can live currently. Some interfaces are under IR, presumably because they were considered necessary for the IR definition (`OpAsmInterface` for printing/parsing, `SymbolInterfaces` for symbol tables) but some others are under Interface (`ControlFlowInterfaces`, `DerivedAttributeInterface` and `SideEffectInterfaces` all look as important as the things in IR). Some interfaces under Interface are specific to a transform (`DestinationStyleInterface` is clearly for bufferization and `TilingInterface` is for tiling) but this transform may not live in `lib/Transform` or there may be several variants of it. Some dialects have additional interfaces that create dialect dependencies, but may actually belong to a more generic Interface category. Do we really want to add _yet another place_ where interfaces could live?
- `Transform/Utils` is IMO a huge misnomer for interfaces. Utils are for additional things that may or may not be useful for somebody. Interfaces _must_ be implemented for things to work.

**Comment by Mogball** [comment]
> TransformUtils depends on various dialects via ViewLikeInterface and ArithUtils.

This seems like a huge problem. This is also affecting all downstream users.

**Comment by chsigg** [comment]
> > TransformUtils depends on various dialects via ViewLikeInterface and ArithUtils.

Actually, there are much shorter paths, e.g. `TransformUtils > Analysis > ArithDialect`.

> This seems like a huge problem. This is also affecting all downstream users.

I did find two places in [TensorFlow](https://cs.opensource.google/search?q=InliningUtils.h%20file:BUILD&sq=&ss=tensorflow%2Ftensorflow) where this seemed to be a problem, but no other ones. So hopefully this is still under control.

**Comment by joker-eph** [comment]
> > I don't know how to model this with Bazel: would you create a "header only target" just for the header inclusion and another one for the link?
> 
> You can do that, but then a user of your dialect needs to explicitly add the link target as a dependency.

No: they are really header-only dependency, you don't need the link target.

You need to link to register the interface implementation only IIRC. 

CMake is lose with the header dependency, but has the same rules as Bazel for the link dependency (when we build with `-DBUILD_SHARED_LIBS=ON`)

**Comment by stellaraccident** [comment]
I hear the "header only dep" argument but it still makes me quite uncomfortable as it represents project organization lines that should not be crossed: we have got to start thinking of some of these pieces as distinct projects.

**Comment by chsigg** [comment]
> No: they are really header-only dependency, you don't need the link target.
> You need to link to register the interface implementation only IIRC.

Right, but dialect registration is part of the dialect target as well, and depending on just the header would make it not self-contained. Of course, most binary targets that depend on a few dialects will also depend on TransformUtils somehow. It does work the way it's set up right now, but the layering is not ideal and breaks e.g. managing dependencies automatically by tools.

**Comment by joker-eph** [comment]
> Right, but dialect registration is part of the dialect target as well, and depending on just the header would make it not self-contained

I don't follow, can we look at one concrete use-case right now?
Which exact header and which exact link dependency is a problem?

**Comment by chsigg** [comment]
> Which exact header and which exact link dependency is a problem?

You are right, the `DialectInlinerInterface` that is used by the dialects is fully implemented in `InliningUtils.h`. So dialects could depend on a header-only target (let's call it `InlinerInterface`). The other declarations in `InliningUtils.h` would only be implemented in the `TransformUtils` target. This has the following problems (purely from a bazel perspective):

- Either `InliningUtils.h` needs to be exported by both `InlinerInterface` and `TransformUtils`. Exporting headers multiple times is bad because it breaks modules and tools don't understand the difference between the two targets.
- Alternatively, export `InliningUtils` only by `InlinerInterface`. This requires all (direct) users of the other declarations depend on both `InlinerInterface` and `TransformUtils`.

I fully understand that we do not want to restructure code to please the bazel build. We don't need to in this particular case (and I haven't looked into similar issues like the `Bytecode` headers yet), so if we agree that the `DialectInlinerInterface` should stay where it is, I can ...

1) Fix this purely in the BUILD files by creating a separate target for `InliningUtils.h/cpp`.

The alternatives would be:

2) This PR in its current form (moving the interfaces into the `Interfaces` directory).
3) Do the same code split as in this PR, but move the files back to the `Transforms` directory.
4) Move only `DialectInlinerInterface` to a separate (self-contained) header file, presumably in the Transforms directory.

If we could agree to one of these (or anything else), that would be great.

**Comment by joker-eph** [comment]
I looked at how we handled these cases before in Bazel, I believe the way to not confuse the tool and not have multiple targets exposing the header was to add them as srcs for the users: https://github.com/llvm/llvm-project/blob/main/utils/bazel/llvm-project-overlay/mlir/BUILD.bazel#L330

**Comment by chsigg** [comment]
Yes, consuming the header file under `srcs` is better than re-exporting it under `hdrs`. That's worse than an incomplete (just exporting the header) `cc_library` target, because it requires [exporting](https://github.com/llvm/llvm-project/blob/01a31cee561efe90fbd1d33fa89f403dd8ff9012/utils/bazel/llvm-project-overlay/mlir/BUILD.bazel#L12422) the plain header file for downstream projects, see also the TensorFlow link above.

We don't need any of those crutches in this particular case though, we can make a target that exposes and implements the `DialectInlinerInterface`. I will go ahead with this and create a separate PR (approach 1. above). If you would like me to also move any interface definitions into separate files, please let me know.

**Pull request closed without merging**
