### PR TITLE
[libc] Use LLVM CommandLine for loader tool

### PR DESCRIPTION
**Pull request by jhuber6**
Summary:
This patch removes the ad-hoc parsing that I used previously and
replaces it with the LLVM CommnadLine interface. This doesn't change any
functionality, but makes it easier to maintain.

### CODE REVIEW

**Comment by tschuett** [comment]
For new tools you should use Opts.td:
#include <llvm/Option/OptTable.h>
#include <llvm/Option/Option.h>

**Comment by jhuber6** [comment]
> For new tools you should use Opts.td: #include <llvm/Option/OptTable.h> #include <llvm/Option/Option.h>

So CommandLine is deprecated now? That should probably be documented then. I've used the options parser in the past and found that `CommandLine` was more convenient for small tools.

**Comment by jhuber6** [comment]
> Deprecated is probably too harsh, but you get most handling for free and don't need those static variables.
> 
> set(LLVM_TARGET_DEFINITIONS Opts.td) tablegen(LLVM Opts.inc -gen-opt-parser-defs)

Not really sure how to replicate the `cl::ConsumeAfter` functionality with the OptParser that I'm basically relying on here. Is there any replacement for that? Or would I need to roll it myself.

**Comment by tschuett** [comment]
One smallish costumer:
https://github.com/llvm/llvm-project/tree/main/llvm/tools/llvm-gsymutil

**Comment by jhuber6** [comment]
> One smallish costumer: https://github.com/llvm/llvm-project/tree/main/llvm/tools/llvm-gsymutil

I don't see where this is doing `cl::ConsumeAfter`. I need it to work like this, where `<args...>` aren't parsed at all.
```amdhsa-loader [options] <positional> <args...>```

**Comment by tschuett** [comment]
I wanted to make your life easier. If you are happy with this option, then I am fine.

**Comment by jhuber6** [comment]
> I wanted to make your life easier. If you are happy with this option, then I am fine.

No problem, the Opt interface definitely has a lot of advantages over `CommandLine`. There's a reason I ported the `clang-linker-wrapper` away from it a long time ago. This just seemed like a really specific use-case that I couldn't easily replicate, so I went with it.

**Review by SchrodingerZhu — APPROVED** [review]

**Review by michaelrj-google — APPROVED** [review]

**Pull request merged**
