### PR TITLE
[Github] Add PR author name to subscription email

### PR DESCRIPTION
**Pull request by boomanaiden154**
Currently the email that gets sent out to people subscribing to a label that the bot tags on the PR doesn't include any authorship information which some people are interested in having. This patch adds an author field to the message with the relevant information.

### CODE REVIEW

**Comment by boomanaiden154** [comment]
These changes should be correct but I haven't tested them  out. Not sure what the testing procedure is like. Try it out on my fork after adding the relevant token secrets?

**Comment by jrtc27** [comment]
Probably worthwhile for issues too?

**Comment by joker-eph** [comment]
> Try it out on my fork after adding the relevant token secrets?

You can try it out on a this PR by running the script yourself locally with your token. We should see some result in a comment here directly.

**Comment by boomanaiden154** [comment]
@llvm/pr-subscribers-llvm-exegesis

Author: Aiden Grossman (boomanaiden154)

<details>
<summary>Changes</summary>

Currently the email that gets sent out to people subscribing to a label that the bot tags on the PR doesn't include any authorship information which some people are interested in having. This patch adds an author field to the message with the relevant information.

---
Full diff: https://github.com/llvm/llvm-project/pull/68440.diff


1 Files Affected:

- (modified) llvm/utils/git/github-automation.py (+2) 


``````````diff
diff --git a/llvm/utils/git/github-automation.py b/llvm/utils/git/github-automation.py
index b90c68a3618b9d7..cd549e75bf7d6cd 100755
--- a/llvm/utils/git/github-automation.py
+++ b/llvm/utils/git/github-automation.py
@@ -165,6 +165,8 @@ def run(self) -> bool:
 {self.COMMENT_TAG}
 {team_mention}
 
+Author: {self.pr._user.name} ({self.pr._user.login})
+
 <details>
 <summary>Changes</summary>
 

``````````

</details>

**Comment by boomanaiden154** [comment]
> Probably worthwhile for issues too?

Thanks for the suggestion! I've implemented it for issues as well. The example is available [here](https://github.com/llvm/llvm-project/issues/68548).

> You can try it out on a this PR by running the script yourself locally with your token. We should see some result in a comment here directly.

Thanks! That worked pretty much perfectly. Maybe worth documenting somewhere at some point (if it isn't already).

**Review by tstellar — APPROVED** [review]

**Comment by mstorsjo** [comment]
I just wanted to say thanks for implementing this! I've been meaning to look at doing exactly this for a couple of weeks now, but haven't gotten to it yet.

**Comment by Endilll** [comment]
It would be nice to extract mannequin names as well, because issues migrated from bugzilla are still significant. Example: https://github.com/llvm/llvm-project/issues/49522#issuecomment-1769703722

**Pull request merged**
