### PR TITLE
[libc] fixed target issue with exit_handler

### PR DESCRIPTION
**Pull request by aaryanshukla**
- addressed https://github.com/llvm/llvm-project/pull/94317#issuecomment-2153103129
- added conditional in cmake file for exit_handler object library

### CODE REVIEW

**Comment by michaelrj-google** [comment]
@zeroomega could you check if this fixes the issue in the Fuchsia builder?

**Review by michaelrj-google — APPROVED** [review]
LGTM to land after Fuchsia approval

**Comment by zeroomega** [comment]
I started a test run, I will know the results in about 30mins.

**Review by zeroomega — APPROVED** [review]
It fixed the issue on `riscv32-unknown-elf` runtime build

**Pull request merged**
