### PR TITLE
Keep attribute when bufferizing `scf.forall` op

### PR DESCRIPTION
**Pull request by srcarroll**

### CODE REVIEW

**Review by MaheshRavishankar — APPROVED** [review]
Nice! Didnt know about discardable attributes.

**Comment by srcarroll** [comment]
> Nice! Didnt know about discardable attributes.

Yah I recently learned about them myself. Thanks!

**Comment by joker-eph** [comment]
Note: preserving attributes we don't understand is not safe in general (for example one could imagine a "pure" attribute that was added to all loops deemed as not having side effects, which would be invalidated by bufferization)

**Comment by MaheshRavishankar** [comment]
> Note: preserving attributes we don't understand is not safe in general (for example one could imagine a "pure" attribute that was added to all loops deemed as not having side effects, which would be invalidated by bufferization)

+1 . Use at your own risk!

**Pull request merged**
