### PR TITLE
[InstCombine] Intersect nowrap flags between geps while folding into phi

### LINKED ISSUE #115149: [clang] Miscompile with -O3 and -O0/1/2 since 18.1.0
When I compiled this code with -O0/1/2, its output is 0. However, with -O3, it returned 143:

```c
int printf(const char *, ...);
char a, b;
int c;
char *e = &b;
int f(char *g, int *k) {
  char *d = g + *k;
  for (; *d && *d <= ' '; d++)
    ;
  if (*d)
    return 0;
  return 1;
}
int l(int g) {
  char h[] = {a, a, a};
  int i[] = {g};
  int j = f(h, i);
  return j;
}
long m() {
  *e = 255;
  for (; l(b + 1);)
    return 0;
  for (;;)
    ;
}
int main() {
  m();
  printf("%d\n", c);
}
```

Details can be found here: https://godbolt.org/z/dnvvTPror

### PR DESCRIPTION
**Pull request by antoniofrighetto**
A miscompilation issue has been addressed with refined checking.

Fixes: https://github.com/llvm/llvm-project/issues/115149.

### CODE REVIEW

**Review by nikic — CHANGES_REQUESTED** [review]
I don't think this is the right fix. As far as I can tell this is just a bug in the flag intersection, because we end up ignoring the flags on the first instruction. Would doing this fix the issue?

`GEPNoWrapFlags NW = FirstInst->getNoWrapFlags()`

**Comment by antoniofrighetto** [comment]
> I don't think this is the right fix. As far as I can tell this is just a bug in the flag intersection, because we end up ignoring the flags on the first instruction. Would doing this fix the issue?

Updated, thank you! Admittedly, I thought about intersecting flags here, but felt like dropping flags (losing inbounds in the gep) at this point might have been unfavourable for later optimizations (so thought of preventing the folding altogether was "sort of" more robust).

**Review by nikic — APPROVED** [review]
LGTM

**Comment by AreaZR** [comment]
Do we want to backport this to 19.x since it mentions introduced in 18.1?

**Pull request merged**
