### PR TITLE
[ARM] Fix frame chains with M-profile PACBTI

### PR DESCRIPTION
**Pull request by ostannard**
When using AAPCS-compliant frame chains with PACBTI return address
signing, there ware a number of bugs in the generation of the frame
pointer and function prologues. The most obvious was that we sometimes
would modify r11 before pushing it to the stack, so it wasn't preserved
as required by the PCS. We also sometimes did not push R11 and LR
adjacent to one another on the stack, or used R11 as a frame pointer
without pointing it at the saved value of R11, both of which are
required to have an AAPCS compliant frame chain.

The original work of this patch was done by James Westwood, reviewed as
 #82801 and #81249, with some tidy-ups done by Mark Murray and myself.

The first 5 patches here are also included in #110283, so the NFC parts can be reviewed separately.

### CODE REVIEW

**Comment by ostannard** [comment]
Rebased over #110283, which is now merged.

**Comment by ostannard** [comment]
Ping

**Review by MarkMurrayARM — APPROVED** [review]
This looks like the code I looked at a while back, but cleaned up, and with better testing. LGTM.

**Comment by pcc** [comment]
Looks like this change caused test failures with MSan, e.g. https://lab.llvm.org/buildbot/#/builders/169/builds/4378

Can you please take a look?

**Comment by ostannard** [comment]
I've reverted it for now while I investigate: 18ac0178ad7f839bdb3376b7a0c6b69a24520a06

**Comment by ostannard** [comment]
Re-landed as 493529fbcee07b1ea17c3abfdea85cfa226a04a4 with the uninitialised variable fixed.

**Pull request merged**
