### PR TITLE
[SPIRV][HLSL] Add lowering of frac to SPIR-V

### LINKED ISSUE #88059: [SPIRV][HLSL] Implement `frac` lowering
- Create a frac intrinsic for spirv use the hlsl intrinsic switching to swap on target.

update the frac.hlsl unit tests:
https://github.com/llvm/llvm-project/blob/1e6ce5e284f5c0e8d64eee21af727bb164eb3caf/clang/test/CodeGenHLSL/builtins/frac.hlsl#L2

example:
https://shader-playground.timjones.io/020254826814c6bfb01e671c08c15db4

and implement the `OpExtInst Fract` Lowering:
`%13 = OpExtInst %v4float %1 Fract %12`
https://registry.khronos.org/SPIR-V/specs/1.0/GLSL.std.450.html#Fract

### PR DESCRIPTION
**Pull request by ritskii**
Implements frac lowering to SPIR-V.

Closes #88059

### CODE REVIEW

**Review by Keenuts — APPROVED** [review]
LGTM on the SPIR-V side, leaving MS look at the HLSL side

**Review by bogner — APPROVED** [review]
lgtm

**Comment by farzonl** [comment]
LGTM

**Review by farzonl — APPROVED** [review]

**Review by coopp — APPROVED** [review]
Looks good to me.

**Comment by aabysswalker** [comment]
@farzonl thanks for review! I didn't, can you merge instead of me?

**Pull request merged**
