### PR TITLE
[compiler-rt] [test] Mark tests failing with glibc-2.39 XFAIL

### PR DESCRIPTION
**Pull request by mgorny**
See https://github.com/llvm/llvm-project/issues/82883.

### CODE REVIEW

**Comment by vitalybuka** [comment]
Do you know why this is broken?

**Comment by vitalybuka** [comment]
I guess it's not needed after https://github.com/llvmbot/llvm-project/commit/f4847cf20d055ea58f5781c4fdbca812585c76f3 ?

**Review by vitalybuka — CHANGES_REQUESTED** [review]
Assuming not needed

**Comment by mgorny** [comment]
Yeah, sorry, I thought it was closed but apparently not.

**Pull request closed without merging**
