### PR TITLE
fix build error in MSVC build

### PR DESCRIPTION
**Pull request by SevenIsSeven**
This commit(https://github.com/llvm/llvm-project/pull/84738) introduced following compile warning then treated-as-error in MSVC build.

>>>"'^': unsafe mix of type 'unsigned int' and type 'bool' in operation"

### CODE REVIEW

**Comment by SevenIsSeven** [comment]
@jmorse @OCHyams

**Review by OCHyams — APPROVED** [review]
LGTM, thanks for the patch

**Review by ScottTodd — APPROVED** [review]

**Comment by ScottTodd** [comment]
Would you like help merging/commiting this? We've also started seeing this warning/error in our downstream MSVC builds.

**Comment by SevenIsSeven** [comment]
will do that asap, maybe 15minutes later?😅

Sent from Gmail Mobile


Scott Todd ***@***.***>于2024年3月27日 周三上午8:12写道：

**Comment by SevenIsSeven** [comment]
> Would you like help merging/commiting this? We've also started seeing this warning/error in our downstream MSVC builds.

”Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.“
should I apply for write access from somewhere? or could you help me merge if you have the write access? thanks~

**Comment by ScottTodd** [comment]
> > Would you like help merging/commiting this? We've also started seeing this warning/error in our downstream MSVC builds.
> 
> ”Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.“ should I apply for write access from somewhere? or could you help me merge if you have the write access? thanks~

Yep, I have access and can merge for you. Contributing and commit access docs are here:

* https://llvm.org/docs/Contributing.html
* https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access

**Comment by SevenIsSeven** [comment]
> > > Would you like help merging/commiting this? We've also started seeing this warning/error in our downstream MSVC builds.
> > 
> > 
> > ”Only those with [write access](https://docs.github.com/articles/what-are-the-different-access-permissions) to this repository can merge pull requests.“ should I apply for write access from somewhere? or could you help me merge if you have the write access? thanks~
> 
> Yep, I have access and can merge for you. Contributing and commit access docs are here:
> 
> * https://llvm.org/docs/Contributing.html
> * https://llvm.org/docs/DeveloperPolicy.html#obtaining-commit-access

thank you so much.

**Pull request merged**
