### PR TITLE
[libc] added rest of yaml files for new headergen

### PR DESCRIPTION
**Pull request by RoseZhang03**
Added yaml files containing functions from only one standard.
Also added one combined standard yaml file (errno.yaml).
assert.yaml is still work in progress.

### CODE REVIEW

**Review by aaryanshukla — COMMENTED** [review]
Have a newline at the end of each Yaml file. Also we can remove guard and attributes if they are assigned to nothing to cut down on boilerplate info. Rest LGTM.

**Comment by michaelrj-google** [comment]
The contents of the files look good, but I'm not sure why some of the yaml files' names start with a standard and some don't. Also why are the yaml files in two different folders?

**Comment by RoseZhang03** [comment]
> The contents of the files look good, but I'm not sure why some of the yaml files' names start with a standard and some don't. Also why are the yaml files in two different folders?

Good point. I will move the other combined files into the general yaml folder in my next patch. They were originally placed in different folders for organizational purposes as we were combining functions from different standards. Most of these are header files with functions in only one standard.

**Review by michaelrj-google — APPROVED** [review]
LGTM, I agree that moving the other yaml files would be a good followup patch

**Pull request merged**
