### PR TITLE
Fix call site breakpoint patch

### PR DESCRIPTION
**Pull request by jimingham**
This fixes the two test suite failures that I missed in the PR:

https://github.com/llvm/llvm-project/pull/112939

One was a poorly written test case - it assumed that on connect to a gdb-remote with a running process, lldb MUST have fetched all the frame 0 registers.  In fact, there's no need for it to do so (as the CallSite patch showed...) and if we don't need to we shouldn't.  So I fixed the test to only expect a `g` packet AFTER calling read_registers.

The other was a place where some code had used 0 when it meant LLDB_INVALID_LINE_NUMBER, which I had fixed but missed one place where it was still compared to 0.

### CODE REVIEW

**Comment by dyung** [comment]
@jimingham your change is causing two cross-project-test failures, can you take a look or revert if you need time to investigate?

**Comment by jimingham** [comment]
That's fixed in:



https://github.com/llvm/llvm-project/pull/114337￼
Fix stepping away from the bottom-most frame of a virtual inlined call stack. by jimingham · Pull Request #114337 · llvm/llvm-project
github.com

which is waiting on review.  Would have fixed this sooner but dexter is a pretty opaque test harness...

Jim

**Comment by slackito** [comment]
Hi,

I'm having some problems with one of our tests, that also reproduce after [#114337](https://github.com/llvm/llvm-project/pull/114337).

I don't have a repro yet but I'll describe what I know of the problem so far in case it rings a bell.

The test in question has a common source file with the following structure:
```
#if defined(PROTO_V2)
#include "test_proto_v2.pb.h"
namespace proto_v2 {
#elif defined(PROTO_V3)
#include "test_proto_v3.proto.h"
namespace proto_v3 {
#elif...
// some more cases
#endif

void DoSomeStuff() {
  // common logic goes here
}

}  // end whatever namespace got selected
```

This file gets compiled multiple times with `-DPROTO_V2`, `-DPROTO_V3` and so on, and all of them get linked into a binary. Each version goes into a different namespace so there are no duplicate definitions of anything, it's just a little hack to avoid having four separate files with mostly the same code.

Before this commit, running `b common.cc:123` results in a breakpoint with N locations. After this commit, only one of them gets selected.

I'll do my best to share a repro case later today.

**Comment by slackito** [comment]
Repro was pretty straightforward from the description above.

common.cc:
```c++
#include <cstdio>

#define XSTR(x) STR(x)
#define STR(x) #x

namespace NAMESPACE {

void DoSomeStuff() {
  printf("%s::DoSomeStuff()\n", XSTR(NAMESPACE));
}

}  // end NAMESPACE
```

main.cc:
```c++
namespace ns1 {
extern void DoSomeStuff();
} // namespace ns1

namespace ns2 {
extern void DoSomeStuff();
} // namespace ns2

namespace ns3 {
extern void DoSomeStuff();
} // namespace ns3

namespace ns4 {
extern void DoSomeStuff();
} // namespace ns4

int main(int argc, char* argv[]) {
  ns1::DoSomeStuff();
  ns2::DoSomeStuff();
  ns3::DoSomeStuff();
  ns4::DoSomeStuff();

  return 0;
}
```

build.sh
```bash
#!/bin/bash
g++ -c -g -DNAMESPACE=ns1 -o ns1.o common.cc
g++ -c -g -DNAMESPACE=ns2 -o ns2.o common.cc
g++ -c -g -DNAMESPACE=ns3 -o ns3.o common.cc
g++ -c -g -DNAMESPACE=ns4 -o ns4.o common.cc
g++ -g -o main ns1.o ns2.o ns3.o ns4.o main.cc
```

with an lldb built at the revision prior to this commit:
```
$ lldb --no-lldbinit main
(lldb) target create "main"
Current executable set to '/usr/local/google/home/jgorbe/lldb-repro/main' (x86_64).
(lldb) b common.cc:9
Breakpoint 1: 4 locations.
```

at this revision (and also at HEAD as of 5 minutes ago):
```
$ lldb --no-lldbinit main
(lldb) target create "main"
Current executable set to '/usr/local/google/home/jgorbe/lldb-repro/main' (x86_64).
(lldb) b common.cc:9
Breakpoint 1: where = main`ns1::DoSomeStuff() + 4 at common.cc:9:9, address = 0x000000000000113d
```

**Comment by labath** [comment]
So it sounds like the problem is that lldb no longer looks for all compile units with the given name when setting a breakpoint. Changing that doesn't seem like it was the intention of this patch. Jim, is there an easy fix for this or should we revert the patch for now?

**Comment by jimingham** [comment]
Give me a bit to look at this.  The intention of this patch was just to add more locations, it shouldn't be reducing the number of breakpoints.  There's likely some simple goof here.

Jim

**Comment by jimingham** [comment]
There were two issues here, one very minor, and then one that mattered...  This was a little thinko, I forgot that we build into the same SymbolContextList over all the CU iterations, so I needed to check "did I add to the SC list" not "is there anything in the SC list" to see if looking for a call site found anything:

diff --git a/lldb/source/Symbol/CompileUnit.cpp b/lldb/source/Symbol/CompileUnit.cpp
index 73389b2e8479..d7df6ee1f221 100644
--- a/lldb/source/Symbol/CompileUnit.cpp
+++ b/lldb/source/Symbol/CompileUnit.cpp
@@ -326,16 +326,18 @@ void CompileUnit::ResolveSymbolContext(
   // the function containing the PC of the line table match.  That way we can
   // limit the call site search to that function.
   // We will miss functions that ONLY exist as a call site entry.
-
+  
   if (line_entry.IsValid() &&
-      (line_entry.line != line || line_entry.column != column_num) &&
-      resolve_scope & eSymbolContextLineEntry && check_inlines) {
+      (line_entry.line != line || (column_num != 0 && line_entry.column != column_num))
+      && (resolve_scope & eSymbolContextLineEntry) && check_inlines) {
     // We don't move lines over function boundaries, so the address in the
     // line entry will be the in function that contained the line that might
     // be a CallSite, and we can just iterate over that function to find any
     // inline records, and dig up their call sites.
     Address start_addr = line_entry.range.GetBaseAddress();
     Function *function = start_addr.CalculateSymbolContextFunction();
+    // Record the size of the list to see if we added to it:
+    size_t old_sc_list_size = sc_list.GetSize();
 
     Declaration sought_decl(file_spec, line, column_num);
     // We use this recursive function to descend the block structure looking
@@ -417,7 +419,7 @@ void CompileUnit::ResolveSymbolContext(
     // FIXME: Should I also do this for "call site line exists between the
     // given line number and the later line we found in the line table"?  That's
     // a closer approximation to our general sliding algorithm.
-    if (sc_list.GetSize())
+    if (sc_list.GetSize() > old_sc_list_size)
       return;
   }
 
But I'm kind of surprised that nothing in our test suite was sensitive to this.  I'll work up this example into a test, and then submit this.  

Thanks for the example!

Jim

**Comment by slackito** [comment]
Thanks for the quick response, Jim!

**Comment by jimingham** [comment]
https://github.com/llvm/llvm-project/pull/114896￼
Fix a thinko in the CallSite handling code: by jimingham · Pull Request #114896 · llvm/llvm-project
github.com

Jim

**Pull request merged**
