### PR TITLE
[mlir][flang] Add an interface of OpenACC compute regions for further getAllocaBlock support

### PR DESCRIPTION
**Pull request by khaki3**
This PR implements `ComputeRegionOpInterface` to define `getAllocaBlock` of OpenACC loop and compute constructs (parallel/kernels/serial). The primary objective here is to accommodate local variables in OpenACC compute regions. The change in `fir::FirOpBuilder::getAllocaBlock` allows local variable allocation inside loops and kernels.

### CODE REVIEW

**Review by clementval — APPROVED** [review]
LGTM

**Review by jeanPerier — COMMENTED** [review]
Since you are giving some alloca ownership aspect to these operation, can you also give them the `AutomaticAllocationScope` trait so that fir::AlllocaOp::getOwnerRegion will consider alloca nested in this region as belonging to it, and that any dynamic allocation made inside will be properly handled by passes like https://github.com/llvm/llvm-project/blob/main/flang/lib/Optimizer/Transforms/MemoryAllocation.cpp

**Comment by khaki3** [comment]
Thank you for your reviews. I updated the interface to allow acc loops. Also, the AutomaticAllocationScope trait was added to parallel/kernels/serial/loop.

**Review by razvanlupusoru — APPROVED** [review]
Thank you!

**Pull request merged**
