### PR TITLE
[IR][InstCombine] Add `N{U,S}WAddLike` matchers.

### PR DESCRIPTION
**Pull request by goldsteinn**
- **[IR] Add helpers for `NUWAddLike` and `NSWAddLike` to also match `or disjoint`; NFC**
- **[InstCombine] Add tests for integrating `N{U,S}WAddLike`; NFC**
- **[InstCombine] integrate `N{U,S}WAddLike` into existing folds**

### CODE REVIEW

**Review by nikic — APPROVED** [review]
LGTM

**Comment by dtcxzyw** [comment]
Missing fold: https://alive2.llvm.org/ce/z/jZgVSn

https://github.com/llvm/llvm-project/blob/2096f37d7a580a4b4ddce2a44abb80ff90f273ee/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp#L960-L974

**Review by dtcxzyw — APPROVED** [review]
LGTM

**Comment by goldsteinn** [comment]
> Missing fold: https://alive2.llvm.org/ce/z/jZgVSn See also [dtcxzyw/llvm-opt-benchmark#439 (comment)](https://github.com/dtcxzyw/llvm-opt-benchmark/pull/439#discussion_r1533659346)
> 
> https://github.com/llvm/llvm-project/blob/2096f37d7a580a4b4ddce2a44abb80ff90f273ee/llvm/lib/Transforms/InstCombine/InstCombineCasts.cpp#L960-L974

I'm sure there are alot of folds missing... this patch was really just about the matcher and a quick replacement of the trivially cases.

**Pull request closed without merging**
