### PR TITLE
[scudo] Calling initCache() in init() of SizeClassAllocatorLocalCache

### PR DESCRIPTION
**Pull request by ChiaHungDuan**
initCacheMaybe() will init all the size class arrays at once and it doesn't have much work to do even if it supports partial initialization. This avoids the call to initCacheMaybe in each allocate()/deallocate().

### CODE REVIEW

**Comment by ChiaHungDuan** [comment]
Some clean up for the support of zero-size cache

**Comment by cryptoad** [comment]
IIRC the only reason we had it this way was to avoid dirtying the Cache for new threads that don't do allocations, which might be only really relevant for the Exclusive TSD model on heavy threaded applications. I don't think we ever gathered data about this, but might want to run a few tests (I usually ran the RPC benchmarks in g3 with Scudo compiled in).

**Comment by ChiaHungDuan** [comment]
> IIRC the only reason we had it this way was to avoid dirtying the Cache for new threads that don't do allocations, which might be only really relevant for the Exclusive TSD model on heavy threaded applications. I don't think we ever gathered data about this, but might want to run a few tests (I usually ran the RPC benchmarks in g3 with Scudo compiled in).

Thanks for the context! Let me try that benchmark first and if it does have some impact, I'll try to adopt a different layout to minimize the size of unused dirty memory

**Comment by ChiaHungDuan** [comment]
After reviewing the logic of initialization of cache, I notice that we ensure the TSDs are initialized by [initThreadMaybe()](https://github.com/llvm/llvm-project/blob/main/compiler-rt/lib/scudo/standalone/combined.h#L220) and iff the application accesses Scudo. For threads that never allocate, it'll not initialize the TSDs. With Exclusive TSDs, even if it only does deallocation, it'll only init the `FallbackTSD` by setting `MinimalInit=true` to avoid dirtying the space of `ThreadTSD`.

Therefore, I think we are safe to do this change without introducing potential unwanted dirty pages

**Review by cferris1000 — APPROVED** [review]
LGTM

**Pull request merged**
