### PR TITLE
[clang][CIR] Merge the mlir::cir namespace into cir

### PR DESCRIPTION
**Pull request by smeenai**
https://github.com/llvm/clangir/issues/1025 discusses the motivation.
The mechanical parts of this change were done via:

    find clang \( -name '*.h' -o -name '*.cpp' -o -name '*.td' \) -print0 | xargs -0 perl -pi -e 's/mlir::cir/cir/g'
    find clang \( -name '*.h' -o -name '*.cpp' \) -print0 | xargs -0 perl -pi -e 's/::cir/cir/g'

There were some manual fixups and a clang-format run afterwards.

### CODE REVIEW

**Comment by smeenai** [comment]
Stack from [ghstack](https://github.com/ezyang/ghstack) (oldest at bottom):
* (to be filled)

**Review by bcardosolopes — APPROVED** [review]
IIUC, this is following what Flang/FIR does, for consistency among projects. Thanks for putting some sanity on this Shoaib.

LGTM, pending Aaron's and others feedback.

**Comment by smeenai** [comment]
The Windows CI error is an unrelated infra failure, but I don't know how to retry it.

**Review by AaronBallman — APPROVED** [review]
LGTM

**Review by erichkeane — APPROVED** [review]

**Pull request merged**
