### PR TITLE
[LLD][COFF] Allow overriding EC alias symbols with alternate names

### PR DESCRIPTION
**Pull request by cjacek**

### CODE REVIEW

**Comment by cjacek** [comment]
Similar to the handling of lazy symbols, EC aliases behave like undefined symbols in this context.

**Comment by cjacek** [comment]
I just noticed that we may need special-casing `func`->`#func` aliases. It needs more testing, I changed it to a draft for now.

**Comment by cjacek** [comment]
More experimentation with MSVC revealed that `-alternatename` is effective on anti-dependency symbols if either the aliased symbol is undefined or the symbol is mangled. In practice, this distinction helps differentiate between an alias to the guest exit thunk (which is always mangled) and a demangled alias to the implementation symbol. I kept it compatible; it’s now ready for review.

**Comment by cjacek** [comment]
Fixed a typo in test.

**Review by mstorsjo — APPROVED** [review]
LGTM

**Pull request merged**
