### PR TITLE
[RISCV] Move slide and gather costing to subtarget [NFC]

### PR DESCRIPTION
**Pull request by preames**
As discussed during review of D159332.  This PR doesn't actually common up that copy of the code because doing so is not NFC - due to DLEN.  Fixing that will be a future PR.

### CODE REVIEW

**Comment by topperc** [comment]
Where was this discussed in D159332?

Why do we want this in Subtarget? Seems weird to start bring InstructionCost into Subtarget.

**Comment by preames** [comment]
> Where was this discussed in D159332?
"Discussed" was the wrong word.  It was one of the TODOs which had gone without discussion.
> 
> Why do we want this in Subtarget? Seems weird to start bring InstructionCost into Subtarget.
We talked offline, and both felt subtarget wasn't the right place for this.  We were tentatively thinking putting this on TLI.  Is that still what you're thinking?

**Comment by topperc** [comment]
> > Where was this discussed in D159332?
> > "Discussed" was the wrong word.  It was one of the TODOs which had gone without discussion.
> > Why do we want this in Subtarget? Seems weird to start bring InstructionCost into Subtarget.
> > We talked offline, and both felt subtarget wasn't the right place for this.  We were tentatively thinking putting this on TLI.  Is that still what you're thinking?

Yes. That's the best place I can think of right now.

**Review by topperc — APPROVED** [review]
LGTM

**Comment by preames** [comment]
Landed as: 

```
commit 463c9f44dcd8a7a6e056cf3fd0a92ca42c8c6155 (HEAD -> main, upstream/main, upstream/HEAD)
Author: Philip Reames <preames@rivosinc.com>
Date:   Thu Sep 7 16:08:47 2023 -0700

    [RISCV] Move slide and gather costing to TLI [NFC] (PR #65396)
    
    As mentioned in TODOs from D159332.  This PR doesn't actually
    common up that copy of the code because doing so is not NFC - due to
    DLEN.  Fixing that will be a future PR.
```

**Pull request closed without merging**
