### PR TITLE
[rtsan] Add dl, rt, m, and log libraries as unit test dependencies, get rid of atomic

### PR DESCRIPTION
**Pull request by cjappl**
Fixing test failures in #98256 

There are two issues being fixed here:

```
ld.lld: error: undefined symbol: dlvsym
ld.lld: error: undefined symbol: dlvsym
```

Fixed by linking dl

```
FAILED: ... -lstdc++ -no-pie -pthread -latomic -m64
/opt/rh/devtoolset-11/root/usr/lib/gcc/ppc64-redhat-linux/11/../../../../bin/ld: cannot find /usr/lib64/libatomic.so.1
```

Fixed by removing atomic from the dependencies, I don't think we were even using it.

I added in all of the dependencies used by the parent library in the tests, hopefully getting ahead of any other issues, adding rt and m, even if we haven't had issues with them yet

### CODE REVIEW

**Comment by cjappl** [comment]
CC @vitalybuka 

Really apologize for the churn. If there is a more deterministic way to do this other than "commit and see", please let me know. With some of these systems I'm at the mercy of the post-commit tests.

Thanks for your continued help

**Review by vitalybuka — APPROVED** [review]

**Review by vitalybuka — APPROVED** [review]

**Comment by vitalybuka** [comment]
> ⚠️ We detected that you are using a GitHub private e-mail address to contribute to the repo. Please turn off [Keep my email addresses private](https://github.com/settings/emails) setting in your account. See [LLVM Discourse](https://discourse.llvm.org/t/hidden-emails-on-github-should-we-do-something-about-it) for more information.

Would be possible to fix this?
I guess you email is visible in git commits anyway.

**Comment by cjappl** [comment]
> > ⚠️ We detected that you are using a GitHub private e-mail address to contribute to the repo. Please turn off [Keep my email addresses private](https://github.com/settings/emails) setting in your account. See [LLVM Discourse](https://discourse.llvm.org/t/hidden-emails-on-github-should-we-do-something-about-it) for more information.
> 
> Would be possible to fix this? I guess you email is visible in git commits anyway.

Fixed in my local gitconfig. I thought i just needed it in the git commits. Thanks for bringing attention to it

**Comment by cjappl** [comment]
> LLVM Buildbot has detected a new failure on builder `sanitizer-ppc64be-linux` running on `ppc64be-sanitizer` while building `compiler-rt` at step 2 "annotate".

Trying to fix this. I am considering disabling Android as well as PPC arch to go "back basics" then add the rest in later. Will start a new review with those changes. I want to get to some semblance of stability ASAP

**Pull request merged**
