### PR TITLE
Correctly compute conversion seq for args to fn with reversed param order

### LINKED ISSUE #53954: C++20 operator== ambiguous with derived-to-base conversion
```cpp
struct P {
#if 1
    template<class S>
    bool operator==(const S &) const;
#else
    template<class S>
    friend bool operator==(const P &, const S &);
#endif
};

struct A : public P {};
struct B : public P {};

bool check(A a, B b) {
    return a == b;
}
```

The `friend` function works just fine, but the member function dies with
```
<source>:15:14: error: use of overloaded operator '==' is ambiguous (with operand types 'A' and 'B')
    return a == b;
           ~ ^  ~
<source>:4:10: note: candidate function [with S = B]
    bool operator==(const S &) const;
         ^
<source>:4:10: note: candidate function (with reversed parameter order) [with S = A]
```

GCC and MSVC accept both. https://godbolt.org/z/9hj9554fn

@dwblaikie @zygoloid

### PR DESCRIPTION
**Pull request by usx95**
We associated conversion seq for args (when reversed) to the wrong index.
This lead to clang believing reversed `operator==` a worse overload candidate than the `operator==` without reversed args when both these candidate were ambiguous.

Fixes https://github.com/llvm/llvm-project/issues/53954

### CODE REVIEW

**Comment by usx95** [comment]
Friendly ping.

**Review by zygoloid — APPROVED** [review]
Thanks, looks good.

Our overall approach here seems error-prone, and I wonder if there's a better way to model the reversal of the conversion sequence. For example, perhaps we could change `ConversionSequenceList` into a class that tracks its `OverloadCandidateParamOrder`, and provides both accessors in candidate order (optionally the object parameter, then the remaining declared parameters in order) and in comparison order (potentially reversed). But let's land this as-is before thinking about that :)

**Comment by usx95** [comment]
+1 I agree that this is confusing and error prone.

**Comment by usx95** [comment]
Ah. I see, this is because this is not a warning but hard errors in C++20.

**Comment by usx95** [comment]
I think this is important that clang chooses not to error but only warn here as a clang extension (it already chooses to do so in cases when it the can match the function params([1](https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaOverload.cpp#L10274-L10290) and [2](https://github.com/llvm/llvm-project/blob/main/clang/lib/Sema/SemaOverload.cpp#L14415-L14476))
Now that we correctly handle templated `operator==` in this PR, should we also relax the error here as well to a warning ? WDYT @zygoloid 

[GCC does the same](https://godbolt.org/z/Knrv66rd3).

**Pull request merged**
