### PR TITLE
[demangle] Represent a char array initializer as a string literal.

### PR DESCRIPTION
**Pull request by zygoloid**
This improves the demangling for non-type template arguments that
contain string literals. Previously we'd produce

    char [4]{(char)65, (char)66, (char)67}

(which isn't valid C or C++), and now we produce `"ABC"`.

The new demangling is always shorter, even when using an escape sequence
for every character, and much more readable when the char array contains
text.

### CODE REVIEW

**Review by ldionne — APPROVED** [review]
I don't know the demangler very well, but I looked at the implementation and it makes sense to me. Others might have more strongly rooted opinions than me, so I'd suggest waiting for at least one other reviewer.

The functionality itself is amazing though, that greatly improves the output of the demangler.

**Comment by zygoloid** [comment]
@urnathan It looks like you've been working in the libc++abi demangler more than most folks recently, could you take a look?

**Review by dwblaikie — APPROVED** [review]
Looks good - thanks! (still happy to hear from @urnathan if he's got thoughts, but post-commit seems fine at this point)

**Comment by urnathan** [comment]
nice!

**Pull request merged**
