### PR TITLE
[Flang] Update Maintainers

### PR DESCRIPTION
**Pull request by kiranchandramohan**
Move to a markdown file and update maintainers.
This brings the project closer to updated guidance (https://llvm.org/docs/DeveloperPolicy.html#maintainers).  A list of active and inactive maintainers is provided. Maintainers are also grouped into lead or component maintainers.

### CODE REVIEW

**Review by banach-space — APPROVED** [review]
The driver changes LGTM, thanks!

Given the significance of the change, it would be good to make sure that all new and existing maintainers/code-owners approve.

**Review by tarunprabhu — APPROVED** [review]
LGTM. Thanks.

**Review by tblah — APPROVED** [review]
LGTM. Thank you for organizing this!

**Review by jeanPerier — APPROVED** [review]
LGTM, thanks

**Review by razvanlupusoru — APPROVED** [review]
Thank you!

**Review by schweitzpgi — APPROVED** [review]

**Review by kparzysz — APPROVED** [review]
Thanks!

**Review by clementval — APPROVED** [review]

**Review by abidh — APPROVED** [review]

**Review by skatrak — APPROVED** [review]

**Review by dpalermo — APPROVED** [review]

**Review by vdonaldson — APPROVED** [review]

**Review by Renaud-K — APPROVED** [review]

**Review by vzakhari — APPROVED** [review]

**Review by sscalpone — APPROVED** [review]
Thank you Kiran!

**Pull request merged**
