### PR TITLE
[GISel] Fix #77762: extend correct source registers in combiner helper rule extend_through_phis

### LINKED ISSUE #77762: [GISel] `applyExtendThroughPhis` is unsound for ops with multiple destination operands
Discovered in a proprietary fork, so no reproducer.

before:
```
%91:_(s32), %92:_(s32) = G_UNMERGE_VALUES %8:_(s64) ; g_105.f0, g_105.f1,pad
...
%75:_(s32) = G_PHI %92:_(s32), %bb.4, %81:_(s32), %bb.3, %95:_(s32), %bb.2 ; g_105.f1,pad
```

combiner says:
```
Try combining %75:_(s32) = G_PHI %92:_(s32), %bb.4, %81:_(s32), %bb.3, %95:_(s32), %bb.2
Applying rule 'extend_through_phis'
Creating: G_ANYEXT

CSEInfo::Recording new MI G_ANYEXT
Creating: G_ANYEXT

CSEInfo::Recording new MI G_ANYEXT
Creating: G_ANYEXT

CSEInfo::Recording new MI G_ANYEXT
Creating: %103:_(s64) = G_PHI %120:_(s64), %bb.4, %121:_(s64), %bb.3, %122:_(s64), %bb.2

Erasing: %103:_(s64) = G_ANYEXT %75:_(s32)

Created: %120:_(s64) = G_ANYEXT %91:_(s32)
Created: %121:_(s64) = G_ANYEXT %81:_(s32)
Created: %122:_(s64) = G_ANYEXT %95:_(s32)
Created: %103:_(s64) = G_PHI %120:_(s64), %bb.4, %121:_(s64), %bb.3, %122:_(s64), %bb.2
```

what I guess it looks like after this one combiner rule:
```
%120:_(s64) = G_ANYEXT %91:_(s32)
%103:_(s64) = G_PHI %120:_(s64), %bb.4, %121:_(s64), %bb.3, %122:_(s64), %bb.2
```

after all of post legalizer combiner:
```
%8:_(s64) = G_LOAD %6:_(p0) :: (load (s64) from %ir.1, align 4)
%103:_(s64) = G_PHI %8:_(s64), %bb.4, %121:_(s64), %bb.3, %122:_(s64), %bb.2   ; g_105.f0,f1,pad
```

You can see that a use of %92 was incorrectly replaced with an anyext use of %91. You can turn this into a crash, "bug scanner"-style, like this (diff line nos likely wrong):

```diff
--- a/llvm/lib/CodeGen/GlobalISel/CombinerHelper.cpp
+++ b/llvm/lib/CodeGen/GlobalISel/CombinerHelper.cpp
@@ -4024,6 +4024,7 @@ void CombinerHelper::applyExtendThroughPhis(MachineInstr &MI,
     Builder.setDebugLoc(MI.getDebugLoc());
     auto NewExt = Builder.buildExtOrTrunc(ExtMI->getOpcode(), ExtTy,
                                           SrcMI->getOperand(0).getReg());
+    assert(MI.getOperand(SrcIdx).getReg() == SrcMI->getOperand(0).getReg());
     OldToNewSrcMap[SrcMI] = NewExt;
   }

```

PR incoming.

Tagging @aemerson as author of combiner rule `extend_through_phis`, @andcarminati @agostonrobert as collaborators

### PR DESCRIPTION
**Pull request by widlarizer**
Since we already know which register we want to extend, we don't have to ask its defining MI about it

### CODE REVIEW

**Comment by aemerson** [comment]
Thanks for the fix. This needs a test, and it's not immediately clear to me why this change is correct vs the old code?

**Comment by ekliptik** [comment]
Looks like ths PR and issue are unlinked. This PR fixes #77762. I will describe the problem in clearer terms in the issue

- [ ] Add test

**Review by aemerson — APPROVED** [review]
LGTM, can you fix the clang format issue before you merge?

**Comment by aemerson** [comment]
> LGTM, can you fix the clang format issue before you merge?

It's fine actually, I'm going to refactor some of this to use the new `GPhi` wrapper recently added.

**Comment by ekliptik** [comment]
Oops, I was manually renaming the variables since I wrote and verified the test when rebased on our fork which had an older version of the check statements. I pushed it with the expectation that CI tests will run before merge and catch it if there's an issue but I guess they don't auto run for new contributors

**Pull request merged**
