### PR TITLE
[llvm][CodeGen] Some bugfix for window scheduler

### PR DESCRIPTION
**Pull request by kaiyan96**
1. Fixed max cycle calculation for zero-cost instructions.
2. Added a new restriction for II by pragma; the window scheduler will not support loops if the Swing Scheduler's II pragma is set.
3. Fixed a bug in stall cycle calculation. This bugfix will not affecting the window scheduler's result.
4. Added missing initialization failure information.

### CODE REVIEW

**Comment by kaiyan96** [comment]
We have encountered some minor issues while maintaining our own DSA. In this PR, we will address and fix these issues collectively.

**Comment by kaiyan96** [comment]
@arsenm, could you please take some time to review this patch? Thanks.

**Comment by arsenm** [comment]
Title should state what the bug fix is, not that there is a bug fix. Also, one fix per PR please

**Comment by kaiyan96** [comment]
I have split this patch to following 4 patches:

**Comment by kaiyan96** [comment]
I have split this PR to 4 individual PRs:
* [Added a new restriction for II by pragma](https://github.com/llvm/llvm-project/pull/99448)
* [Added missing initialization failure information](https://github.com/llvm/llvm-project/pull/99449)
* [Fixed a bug in stall cycle calculation](https://github.com/llvm/llvm-project/pull/99451)
* [Fixed max cycle calculation with zero-cost instructions](https://github.com/llvm/llvm-project/pull/99454)

**Pull request closed without merging**
