### PR TITLE
[AMDGPU][True16][MC] duplicate vop1 tests to fake16 and update real-true16 flags for GFX12

### PR DESCRIPTION
**Pull request by broxigarchen**
duplicate vop1 tests to fake16 and update real-true16 flags for GFX12

creating duplications here to avoid bulk copy in the following true16 patches

### CODE REVIEW

**Comment by broxigarchen** [comment]
Hi @Sisyph @kosarev @jayfoad can you help to review this PR? This is requeseted by https://github.com/llvm/llvm-project/pull/100442#issuecomment-2253491321. Thanks!

**Review by Sisyph — COMMENTED** [review]
We probably want a comment in each of the non-fake16 test files that the intention here is for the 'fake16 syntax' specified tests to be converted to 'real16 syntax' as the number of supported instructions progresses. 
There are a few of these already, such as v_ceil_f16, and I think it would be a logical patch to come soon to convert these already supported instructions.
Besides such a comment, the patch LGTM. Please wait for someone else to approve as well.

I don't believe we need to test the 'default' behavior of the assembler/disassembler with respect to the +real-true16 flag. So the changes here to have one file with +real-true16 and one with -real-true16 are a sufficient set.

**Comment by broxigarchen** [comment]
> We probably want a comment in each of the non-fake16 test files that the intention here is for the 'fake16 syntax' specified tests to be converted to 'real16 syntax' as the number of supported instructions progresses. There are a few of these already, such as v_ceil_f16, and I think it would be a logical patch to come soon to convert these already supported instructions. Besides such a comment, the patch LGTM. Please wait for someone else to approve as well.
> 
> I don't believe we need to test the 'default' behavior of the assembler/disassembler with respect to the +real-true16 flag. So the changes here to have one file with +real-true16 and one with -real-true16 are a sufficient set.

added comments

**Review by kosarev — APPROVED** [review]
LGTM.

**Comment by broxigarchen** [comment]
Hi I think this PR is ready for merge.

Can someone help to merge this PR since I don't have write access? Thanks!

**Pull request merged**
