### PR TITLE
[TableGen][GlobalISel] Specialize more MatchTable Opcodes

### PR DESCRIPTION
**Pull request by Pierre-vh**
The vast majority of the following (very common) opcodes were always called with identical arguments:

- `GIM_CheckType` for the root
- `GIM_CheckRegBankForClass` for the root
- `GIR_Copy` between the old and new root
- `GIR_ConstrainSelectedInstOperands` on the new root
- `GIR_BuildMI` to create the new root

I added overloaded version of each opcode specialized for the root instructions. It always saves between 1 and 2 bytes per instance depending on the number of arguments specialized into the opcode. Some of these opcodes had between 5 and 15k occurences in the AArch64 GlobalISel Match Table.

Additionally, the following opcodes are almost always used in the same sequence:

- `GIR_EraseFromParent 0` + `GIR_Done` 
  - `GIR_EraseRootFromParent_Done` has been created to do both. Saves 2 bytes per occurence.
- `GIR_IsSafeToFold` was *always* called for each InsnID except 0.
  - Changed the opcode to take the number of instructions to check after `MI[0]`

The savings from these are pretty neat. For `AArch64GenGlobalISel.inc`:
- `AArch64InstructionSelector.cpp.o` goes down from 772kb to 704kb (-10% code size)
- Self-reported MatchTable size goes from 420380 bytes to 352426 bytes (~ -17%)

A smaller match table means a faster match table because we spend less time iterating and decoding.
I don't have a solid measurement methodology for GlobalISel performance so I don't have precise numbers but I saw a few % of improvements in a simple testcase.

### CODE REVIEW

**Review by arsenm — APPROVED** [review]
Is the table still emitting everything as uint64_t? Is it time to fix that?

**Comment by Pierre-vh** [comment]
> Is the table still emitting everything as uint64_t? Is it time to fix that?

No, it's a byte table now with most things using a flexible encoding (ULEB) or fixed-size encoding between 2 and 8 bytes if we can't do ULEB (e.g. value not known)

**Comment by aemerson** [comment]
Very nice! I can try to measure the compile time benefit of this when I have a bit of time, so we can understand how much these types of savings are worth for future.

**Comment by aemerson** [comment]
Here's some compile time measurements for CTMark building with -Os 10 times, it seems ClamAV failed to build, but overall seems there's a neutral/slight improvement:
```
Program                                       compile_time
                                              lhs          rhs    diff
consumer-typeset/consumer-typeset               3.58         3.58  0.0%
kimwitu++/kc                                    6.67         6.67  0.0%
lencod/lencod                                   4.65         4.65 -0.0%
7zip/7zip-benchmark                            14.78        14.77 -0.0%
SPASS/SPASS                                     4.56         4.56 -0.0%
mafft/pairlocalalign                            2.66         2.66 -0.0%
sqlite3/sqlite3                                 2.49         2.49 -0.0%
tramp3d-v4/tramp3d-v4                           5.69         5.68 -0.1%
Bullet/bullet                                  10.99        10.99 -0.1%
                           Geomean difference                     -0.0%
```

**Pull request merged**
