### PR TITLE
[clang][Modules] Make `Module::Requirement` a struct

### PR DESCRIPTION
**Pull request by davidstone**
`Module::Requirement` was defined as a `std::pair<std::string, bool>`. This required a comment to explain what the data members mean and makes the usage harder to understand. Replace this with a struct with two members, `FeatureName` and `RequiredState`.

### CODE REVIEW

**Comment by davidstone** [comment]
@ChuanqiXu9

**Review by dwblaikie — APPROVED** [review]
Awesome - love a good readability improvement. Thanks!

**Review by ChuanqiXu9 — APPROVED** [review]
LGTM. Thanks.

**Comment by ChuanqiXu9** [comment]
> Would someone be able to merge this for me? I do not have permission.

Sorry for not merging this in time. Could you rebase again since it has conflicts now.

**Comment by cor3ntin** [comment]
@davidstone ping

**Pull request merged**
