### PR TITLE
[llvm-exegesis] Use correct rseq struct size

### LINKED ISSUE #100791: `tools/llvm-exegesis/X86/latency` tests fail with glibc 2.40
After upgrading the system to glibc 2.40, the following tests started failing:

```
Failed Tests (8):
  LLVM :: tools/llvm-exegesis/X86/latency/memory-annotations-livein.s
  LLVM :: tools/llvm-exegesis/X86/latency/memory-annotations.s
  LLVM :: tools/llvm-exegesis/X86/latency/subprocess-abnormal-exit-code.s
  LLVM :: tools/llvm-exegesis/X86/latency/subprocess-address-annotation.s
  LLVM :: tools/llvm-exegesis/X86/latency/subprocess-preserved-registers.s
  LLVM :: tools/llvm-exegesis/X86/latency/subprocess-rsp.s
  LLVM :: tools/llvm-exegesis/X86/latency/subprocess-segfault.s
  LLVM :: tools/llvm-exegesis/X86/latency/subprocess.s
```

FWICS, in all instances the failure has the same cause:

```
RUN: at line 3: /var/tmp/portage/sys-devel/llvm-19.1.0_rc1/work/llvm_build-abi_x86_64.amd64/bin/llvm-exegesis -mtriple=x86_64-unknown-unknown -mode=latency -snippets-file=/var/tmp/portage/sys-devel/llvm-19.1.0_rc1/work/llvm/test/tools/llvm-exegesis/X86/latency/subprocess-preserved-registers.s -execution-mode=subprocess | /var/tmp/portage/sys-devel/llvm-19.1.0_rc1/work/llvm_build-abi_x86_64.amd64/bin/FileCheck /var/tmp/portage/sys-devel/llvm-19.1.0_rc1/work/llvm/test/tools/llvm-exegesis/X86/latency/subprocess-preserved-registers.s
+ /var/tmp/portage/sys-devel/llvm-19.1.0_rc1/work/llvm_build-abi_x86_64.amd64/bin/FileCheck /var/tmp/portage/sys-devel/llvm-19.1.0_rc1/work/llvm/test/tools/llvm-exegesis/X86/latency/subprocess-preserved-registers.s
+ /var/tmp/portage/sys-devel/llvm-19.1.0_rc1/work/llvm_build-abi_x86_64.amd64/bin/llvm-exegesis -mtriple=x86_64-unknown-unknown -mode=latency -snippets-file=/var/tmp/portage/sys-devel/llvm-19.1.0_rc1/work/llvm/test/tools/llvm-exegesis/X86/latency/subprocess-preserved-registers.s -execution-mode=subprocess
llvm-exegesis error: Child benchmarking process exited with non-zero exit code: Disabling restartable sequences failed
FileCheck error: '<stdin>' is empty.
FileCheck command line:  /var/tmp/portage/sys-devel/llvm-19.1.0_rc1/work/llvm_build-abi_x86_64.amd64/bin/FileCheck /var/tmp/portage/sys-devel/llvm-19.1.0_rc1/work/llvm/test/tools/llvm-exegesis/X86/latency/subprocess-preserved-registers.s
```

### PR DESCRIPTION
**Pull request by boomanaiden154**
Glibc v2.40 changes the definition of __rseq_size to the usable area of the struct rather than the actual size of the struct to accommodate users trying to figure out what features can be used. This change breaks llvm-exegesis trying to disable rseq as the size registered in the kernel is no longer equal to __rseq_size. This patch adds a check to see if __rseq_size is less than 32 bytes and uses 32 as a value if it is given alignment requirements.

Fixes #100791.

### CODE REVIEW

**Comment by boomanaiden154** [comment]
@mgorny Can you apply this locally and test that this fixes the issue that you saw? I don't have glibc 2.40 on a machine with perf counters available to test.

**Comment by mgorny** [comment]
Sure, will do, but probably tomorrow.

**Review by mgorny — APPROVED** [review]
Thanks! This fixes the issue for me.

**Pull request merged**
