### PR TITLE
fix build on Alpine Linux

### PR DESCRIPTION
**Pull request by DoDoENT**
- make sure libexecinfo gets linked into compiler-rt when building
  against musl c library on Alpine Linux

### CODE REVIEW

**Comment by xgupta** [comment]
This repository does not accept pull requests. Please follow http://llvm.org/docs/Contributing.html#how-to-submit-a-patch for contribution to LLVM.

**Comment by stefson** [comment]
@DoDoENT is this still a thing?

**Comment by DoDoENT** [comment]
@stefson, I haven't tried building on Alpine for a while. The last time I tried, it failed without the patch in this PR.

After it got rejected here, I didn't go through the whole LLVM review process on the Phabricator - it was just too much PITA for something as exotic as this.

**Comment by stefson** [comment]
@DoDoENT the llvm team now accepts pullrequest through this github repo, so maybe you want to try to resubmit the changes? I'm working with musl based gentoo, so I'm happy to see fixes (even though I haven't hit the underlying problem yet)

**Comment by DoDoENT** [comment]
@stefson, I'm no longer using Alpine Linux for my work (we started using Amazon Linux as our base image for most compatibility) so this is no longer relevant for me.

However, feel free to take this patch and resubmit it as your own PR. It's really not a big deal 😄 

If the build works for you without this fix, this is also great news. WIthout linking `execinfo` I was not able to build any binary depending on the `compiler-rt` on Alpine. But if this works now, great to hear that.

**Comment by stefson** [comment]
@DoDoENT I may try to resubmit. 

Could you give an example though for a binary that links against compiler-rt, so that I can try to reproduce this? I can't think of any at the moment.

**Comment by DoDoENT** [comment]
@stefson, I believe the error was during linking of `libclang_rt.asan_dynamic-x86_64.so`, but it was a long time ago.

**Comment by stefson** [comment]
that lib is part of compiler-rt-sanitizers, right?

**Comment by DoDoENT** [comment]
Yeah, it contains runtime support for the Address Sanitizer.

**Pull request closed without merging**
