### PR TITLE
[CommandLine] Set the 'ValueStr' with the selected argument

### PR DESCRIPTION
**Pull request by bwendling**
Setting ValueStr allows us to query which option was selected.

### CODE REVIEW

**Comment by igorkudrin** [comment]
Could you add a test?

**Comment by MaskRay** [comment]
> Could you add a test?

Perhaps a unittest in llvm/unittests/Support/CommandLineTest.cpp

**Comment by bwendling** [comment]
> > Could you add a test?
> 
> Perhaps a unittest in llvm/unittests/Support/CommandLineTest.cpp

Sure. I'll do that soon.

**Comment by bwendling** [comment]
Done. (That was more work than it needed to be.) PTAL.

**Comment by igorkudrin** [comment]
Thanks for the test. However, it is still not clear to me what the motivation for the change was. Maybe similar changes should be made to the specializations of the `cl::parser` class? Should the change be reflected in the [documentation](https://llvm.org/docs/CommandLine.html)?

**Comment by bwendling** [comment]
> Thanks for the test. However, it is still not clear to me what the motivation for the change was. Maybe similar changes should be made to the specializations of the `cl::parser` class?

I'm doing this for an upcoming change where I want to know which register allocator is used (if it's not the "greedy" allocator, we won't support the change). I know it's a bit of a hack, but it's the best we can do without a rewrite of a large part of ISel and other places. (I can add you to the PR when I create it.)

As for other similar changes, it looks like all of the other fields are filled out correctly.

> Should the change be reflected in the [documentation](https://llvm.org/docs/CommandLine.html)?

Maybe? To be honest, I was surprised that it wasn't available in the situation I'm working with. In the case of the `-regalloc=<name>` flag, it doesn't have an enum, just its own parser that has the list of registered allocators in it. The "value" set (in the non-`ValueStr` field) is a pointer to the constructor for that register allocator, but we don't have access to the original `<name>` in the flag. That *should* be in the `ValueStr` field (if I understand correctly). So it's kinda fixing a deficiency IMO... If you want me to add it to the documentation, I'm fine with that. Just let me know which section is good. :-)

**Comment by bwendling** [comment]
Friendly ping.

**Comment by igorkudrin** [comment]
My understanding is that `ValueStr` is just an implementation detail to support the `cl::value_desc` modifier, as in
```
static cl::opt<std::string> OutputFilename("o", cl::desc("Output filename"), cl::value_desc("filename"));
```
which result in
```
> tool --help
  -o <filename>  - Output filename
```
It would not be correct to reuse the same member for another purpose.

**Comment by bwendling** [comment]
> My understanding is that `ValueStr` is just an implementation detail to support the `cl::value_desc` modifier, as in
> 
> ```
> static cl::opt<std::string> OutputFilename("o", cl::desc("Output filename"), cl::value_desc("filename"));
> ```
> 
> which result in
> 
> ```
> > tool --help
>   -o <filename>  - Output filename
> ```
> 
> It would not be correct to reuse the same member for another purpose.

Crumbs! Okay, I was mistaken. I think that Python calls this `metavar`, which I personally believe is clearer (but won't press the issue). Anyway, I'll close this PR. Thank you for the review.

**Pull request closed without merging**
