### PR TITLE
SmallVector: add missing constexpr annotations (NFC)

### PR DESCRIPTION
**Pull request by artagnon**

### CODE REVIEW

**Review by arsenm — APPROVED** [review]
Seems fine, but what contexts would use this?

**Review by nikic — CHANGES_REQUESTED** [review]
I don't see how this is useful when the SmallVector constructors are not constexpr.

**Comment by artagnon** [comment]
So, I'm currently building a 2-d matrix data structure, leveraging the SmallVector infrastructure. The issue with these not being marked constexpr is that nothing that uses them can be marked constexpr either: Windows fails the build on a constexpr expression, if any of the dependent expressions aren't explicitly marked constexpr.

**Review by kuhar — CHANGES_REQUESTED** [review]
> For instance, a constexpr computation involving SmallVector::size() cannot be marked constexpr. Not marking it as constexpr will not give us an inlining-guarantee, for instance. Another example of a serious issue is that we can't use a compile-time assertion on a non-constexpr expression: we'd have to use a runtime assertion instead.

Isn't a constexpr constructor a prerequisite for using these in the constexpr context anyway?

**Comment by artagnon** [comment]
> > For instance, a constexpr computation involving SmallVector::size() cannot be marked constexpr. Not marking it as constexpr will not give us an inlining-guarantee, for instance. Another example of a serious issue is that we can't use a compile-time assertion on a non-constexpr expression: we'd have to use a runtime assertion instead.
> 
> Isn't a constexpr constructor a prerequisite for using these in the constexpr context anyway?

I don't quite understand. What prevents me from having the following?

```cpp
template <typename T, size_t NRows, size_t NCols>
struct Matrix {
  static_assert(NRows * NCols == Data.size());
  SmallVector<T> Data;
  ...
}
```

**Comment by arsenm** [comment]
> I've gone through https://en.cppreference.com/w/cpp/language/constexpr, and there doesn't seem to be a relationship between constexpr functions and constexpr constructors, but maybe I'm missing something?

If you know the exact size, why not use std::array?

**Comment by artagnon** [comment]
> > I've gone through https://en.cppreference.com/w/cpp/language/constexpr, and there doesn't seem to be a relationship between constexpr functions and constexpr constructors, but maybe I'm missing something?
> 
> If you know the exact size, why not use std::array?

So, my approach is to keep the entire Matrix as a single SmallVectorImpl, and I have a view over that that can slice out submatrices and provide a double-indexing operator: operator[] can't take multiple arguments until C++23, so I do indeed keep a std::array of MutableArrayRefs for the row views, and on single-indexing, I return one of them, which again has an operator[] to get the double-indexing. The entire construction, modulo the dynamic resizing, is full of compile-time expressions.

**Comment by nikic** [comment]
> I've gone through https://en.cppreference.com/w/cpp/language/constexpr, and there doesn't seem to be a relationship between constexpr functions and constexpr constructors, but maybe I'm missing something?

How would you ever call a non-static constexpr member in a constexpr context if you cannot obtain an object of the class in a constexpr context, because the constructor is not constexpr?

These things are nominally independent, but non-static constexpr members are useless without constexpr ctors.

**Comment by artagnon** [comment]
> How would you ever call a non-static constexpr member in a constexpr context if you cannot obtain an object of the class in a constexpr context, because the constructor is not constexpr?
> 
> These things are nominally independent, but non-static constexpr members are useless without constexpr ctors.

I see. Thanks for the explanation.

**Pull request closed without merging**
