### PR TITLE
[AsmPrinter] Remove mbb-profile-dump flag

### PR DESCRIPTION
**Pull request by boomanaiden154**
Now that the work embedding PGO information in SHT_LLVM_BB_ADDR_MAP ELF sections has landed, there is no longer a need to keep around the mbb-profile-dump flag.

### CODE REVIEW

**Comment by boomanaiden154** [comment]
Just putting this up for now. It's a bit premature as the AsmPrinter work hasn't landed yet (but it has been approved), and I'm assuming there are some internal projects taking advantage of this flag that need time to switch over. I'll wait until all required infrastructure has landed/downstreams are migrated over before landing this.

**Review by rlavaee — APPROVED** [review]

**Comment by mtrofin** [comment]
Please don't land this just yet, until we switch code using this mechanism to the new one.

**Comment by boomanaiden154** [comment]
> Please don't land this just yet, until we switch code using this mechanism to the new one.

Yep. Was planning on waiting until I have the all clear on that front (after approval) to do that.

**Comment by mtrofin** [comment]
Good to go from my side. Thanks for doing this!

**Pull request merged**
