### PR TITLE
[llvm][SimplifyLibCalls] Add option 'AllowMemcmpToBcmpTransform'

### LINKED ISSUE #73218: LLVM introduces calls to deprecated "bcmp"
LLVM can simplify `memcmp` to `bcmp`:

https://github.com/llvm/llvm-project/blob/6367677c9d901f412934b4935c4341dc6d421d36/llvm/lib/Transforms/Utils/SimplifyLibCalls.cpp#L1599

However, according to `man bcmp`, that function is deprecated since 2001 and has been removed from POSIX in 2008:
```
STANDARDS
       4.3BSD.  This function is deprecated (marked as LEGACY in POSIX.1-2001); POSIX.1-2008 removes the specification of bcmp().
```

It seems problematic to replace calls to fully-supported-functions like `memcp` with deprecated functions like `bcmp`?

Looks like glibc addd a `__memcmpeq` function specifically so that GCC could use it instead of `bcmp`: https://sourceware.org/pipermail/libc-alpha/2021-September/131099.html. Maybe LLVM should do something similar?

### PR DESCRIPTION
**Pull request by JOE1994**
Add command line option `AllowMemcmpToBcmpTransform` that controls whether the optimizer is allowed to make the following transform:

    memcmp(x, y, Len) == 0 -> bcmp(x, y, Len) == 0

The `bcmp` function was removed in the POSIX.1-2008 standard. The optimizer's default behavior of replacing a call to `memcmp` with `bcmp` without user's acknowledgement can cause inconvenience to users as in #40380 .

Other than 'llvm libc', major libc implementations (glibc, musl, newlib, uClibc, etc.) either alias `bcmp` to `memcmp`, define `bcmp` as a tail call to `memcmp`, or don't define `bcmp` by default. Therefore, the above transformation won't bring benefits to majority of users.

With the new option `AllowMemcmpToBcmpTransforms`, the optimizer will attempt the above transformation only when the user explicitly enables the option.

Closes #73218

### CODE REVIEW

**Comment by JOE1994** [comment]
CC @RalfJung regarding #73218

**Comment by RalfJung** [comment]
I can't help with reviewing unfortunately as I'm not familiar with the codebase, but I support having such a flag. :)

**Comment by legrosbuffle** [comment]
> Other than 'llvm libc', major libc implementations (glibc, musl, newlib, uClibc, etc.) either alias bcmp to memcmp, define bcmp as a tail call to memcmp, or don't define bcmp by default. Therefore, the above transformation won't bring benefits to majority of users.

The original plan was to contribute the optimized `bcmp` to `glibc`. What ended up happening is that with the advent of llvm-libc @gchatelet ended up putting the optimized `bcmp` there.

As for this patch I don't think adding an option for every possible nonstandard target extension this is the way to go. As mentioned by @jyknight in https://github.com/llvm/llvm-project/issues/40380, llvm is supposed to be aware of the target environment and emit the appropriate function calls. @gchatelet @nickdesaulniers do we intend on having an llvm-libc target triple ? That would probably be a better long-term solution to support differences between llvm-libc and the glibc.

**Comment by nickdesaulniers** [comment]
> @gchatelet @nickdesaulniers do we intend on having an llvm-libc target triple ?

I think at some point we will need to add this to clang.

> That would probably be a better long-term solution to support differences between llvm-libc and the glibc.

I agree.

Not a fan of this PR; we have different ways to represent if a function is available in a target environment. We can probably key off of that to determine if we should be transforming memcmp -> bcmp. `setLibcallName` comes to mind.

**Comment by efriedma-quic** [comment]
`-fno-builtin-bcmp` should allow disabling the transform already, as far as I know.

If you want to just remove the transform completely, that seems fine to me; it seems like the whole "optimize bcmp" effort sort of failed.  We don't want to keep around optimization flags if we don't think they're actually useful.  We can always resurrect the code later if we need it in some form.

**Comment by goldsteinn** [comment]
> `-fno-builtin-bcmp` should allow disabling the transform already, as far as I know.
> 
> If you want to just remove the transform completely, that seems fine to me; it seems like the whole "optimize bcmp" effort sort of failed. We don't want to keep around optimization flags if we don't think they're actually useful. We can always resurrect the code later if we need it in some form.

If you want to keep the same optimization in at least some cases `glibc` has a properly `bcmp` function named `__memcmpeq`.
I don't think any other `libc` impl has this, however.

**Comment by JOE1994** [comment]
Thank you everyone for your feedback.

**Comment by gchatelet** [comment]
Late comment but I agree that this should be dealt with the target triple approach. I had a patch (lost in phabricator) that was adding support for llvm-libc to llvm, once it's there we can customize the availability of `bcmp` in `TargetLoweringBase::InitLibcalls` as we already do for some functions / environments:
https://github.com/llvm/llvm-project/blob/83feb846482f0100cb29d460d3d8de2690fc32ad/llvm/lib/CodeGen/TargetLoweringBase.cpp#L125-L126

That said, devil's in the details and the "pick and choose" nature of llvm-libc in overlay mode may blur the lines between "I'm using llvm-libc" and "I'm partially using it". We can probably make this explicit in the environment's naming scheme though.

**Pull request closed without merging**
