### PR TITLE
[mlir][sparse] test four row/col major versions of BSR

### PR DESCRIPTION
**Pull request by aartbik**
Note, this is a redo of https://github.com/llvm/llvm-project/pull/72712 which was reverted due to time outs in the bot. I have timed the tests on various settings, and it does not even hit the top 20 of integration tests. To be safe, I removed the SIMD version of the tests, just keeping libgen/direcIR paths (which are the most important to test for us).

I will also keep an eye on https://lab.llvm.org/buildbot/#/builders/264/builds after submitting to make sure there is no repeat.

### CODE REVIEW

**Review by PeimingLiu — APPROVED** [review]

**Review by yinying-lisa-li — APPROVED** [review]

**Comment by aartbik** [comment]
Just to play it super safe, broke the test up into foo1,2,3,4 to make sure we are not hitting some IR size issues.

**Comment by aartbik** [comment]
Submitted... keeping an eye on https://lab.llvm.org/buildbot/#/builders/264

**Comment by aartbik** [comment]
Looks like we are in good shape \o/

https://lab.llvm.org/buildbot/#/builders/264/builds/4503

**Comment by aartbik** [comment]
And all bots are happy with this change:

https://lab.llvm.org/buildbot/#/changes/115712

**Pull request merged**
