### PR TITLE
[RISCV] Add tune info for mem* expansion

### PR DESCRIPTION
**Pull request by wangpc-pp**
So that CPUs can tune these options.

### CODE REVIEW

**Comment by asb** [comment]
What's your plan for the getters in TargetLowering for the same properties? These are queried elsewhere in the codebase.

**Comment by wangpc-pp** [comment]
> What's your plan for the getters in TargetLowering for the same properties? These are queried elsewhere in the codebase.

I don't get what you mean, these getters should return the same values that we set in XXXTargetLowering?

**Comment by asb** [comment]
> > What's your plan for the getters in TargetLowering for the same properties? These are queried elsewhere in the codebase.
> 
> I don't get what you mean, these getters should return the same values that we set in XXXTargetLowering?

Sorry, I'd somehow missed the part that assigned the underlying values used by those getters in RISCVISelLowering. All good.

**Review by topperc — APPROVED** [review]
LGTM

**Pull request merged**
