### PR TITLE
[clang][TableGen] Migrate clang-tblgen  to use const RecordKeeper

### PR DESCRIPTION
**Pull request by jurahul**
Migrate clang tablegen backends to use const RecordKeeper.

This is a part of effort to have better const correctness in TableGen backends:

https://discourse.llvm.org/t/psa-planned-changes-to-tablegen-getallderiveddefinitions-api-potential-downstream-breakages/81089

### CODE REVIEW

**Comment by jurahul** [comment]
This is a refactor for better const correctness in TableGen backends. Please see the discourse thread here: https://discourse.llvm.org/t/psa-planned-changes-to-tablegen-getallderiveddefinitions-api-potential-downstream-breakages/81089

**Comment by jurahul** [comment]
@Sirraide @Lukacma @SpencerAbson @mshockwave can you PTAL? Or suggest other reviewers?

**Comment by jurahul** [comment]
@AaronBallman can you please help find appropriate folks to review this PR?

**Review by AaronBallman — COMMENTED** [review]
Thank you for this!

There's a fair amount of churn here as well as quite a few unrelated formatting changes. Would it be reasonable to split this up to make it a bit easier on reviewers?

0) Formatting changes (those are NFC and don't really require review at all)
1) Split the PRs based on what's being tablegenned (for instance, all the AST stuff at once, all the comment stuff at once, etc)

(Any other way of splitting things up is also fine, it's just a lot to sit down and pour through as one review.)

**Comment by jurahul** [comment]
Fair enough. The formatting changes are unintentional (I just happened to touch code that was not compliant and clang-format did its thing). How about I split these per-file/per-emitter/related sets of emitters? I have been doing the same on LLVM side, just that for clang it was feasible do all of the changes in a single go.

**Comment by AaronBallman** [comment]
> Fair enough. The formatting changes are unintentional (I just happened to touch code that was not compliant and clang-format did its thing). How about I split these per-file/per-emitter/related sets of emitters? I have been doing the same on LLVM side, just that for clang it was feasible do all of the changes in a single go.

That would work great, thank you!

**Pull request closed without merging**
