### PR TITLE
[C API] Add getters for Target Extension Types to C API

### PR DESCRIPTION
**Pull request by Benjins**
These types were added in LLVM-16, and the C API supports constructing them, but not getting information back from them

This change adds getters for them to the C API, updates the echo test to be able to clone Target Extension Types, and adds some usage of them to the `echo.ll` test to confirm that they work

### CODE REVIEW

**Review by jcranmer-intel — COMMENTED** [review]
This needs mentioning in the release notes.

**Comment by Benjins** [comment]
> This needs mentioning in the release notes.

Gotcha. I've added a section to the release notes for it in another commit: let me know if it's okay

**Comment by Benjins** [comment]
Bumping this for review

**Review by jcranmer-intel — COMMENTED** [review]
Looking at the other methods, I think it would also help to have a get I'th type/integer parameter method too in the API.

**Comment by Benjins** [comment]
> Looking at the other methods, I think it would also help to have a get I'th type/integer parameter method too in the API.
> These types should be SmallVector<LLVMTypeRef, 4> and SmallVector<unsigned, 4>, respectively...

These should both be taken care of after the couple commits I pushed just now

**Comment by Benjins** [comment]
Bumping this for review, after merging from main and resolving the conflicts

**Comment by Benjins** [comment]
Superseded by https://github.com/llvm/llvm-project/pull/96447

**Pull request closed without merging**
