### PR TITLE
cppcheck: use move semantics for 'NodeKinds' and update possible callers to use it 

### LINKED ISSUE #87248: clang/lib/ASTMatchers/Dynamic/Marshallers.h:939: possible performance problem ?
Static analyser cppcheck says:

clang/lib/ASTMatchers/Dynamic/Marshallers.h:939:54: performance: Function parameter 'NodeKinds' should be passed by const reference. [passedByValue]

Source code is

  MapAnyOfMatcherDescriptor(ASTNodeKind CladeNodeKind,
                            std::vector<ASTNodeKind> NodeKinds)

I wouldn't have bothered normally, but NodeKinds is a vector, which implies there
are many objects of type ASTNodeKind.

Might be worth tuning.

### PR DESCRIPTION
**Pull request by Amila-Rukshan**
Fixes: https://github.com/llvm/llvm-project/issues/87248

### CODE REVIEW

**Comment by firewave** [comment]
Depending on the calling code the fix might actually be the introduction of `std::move()`.

This is a known issue upstream: https://trac.cppcheck.net/ticket/12384.

**Comment by Amila-Rukshan** [comment]
@firewave, Thank you for pointing it out! I blindly tried to fix it looking at the cppcheck output.

**Comment by Amila-Rukshan** [comment]
Ping

**Review by RKSimon — APPROVED** [review]
LGTM

**Comment by RKSimon** [comment]
@Amila-Rukshan please can you rebase this patch? merge is currently failing

**Comment by Amila-Rukshan** [comment]
@RKSimon I have rebased the changes

**Pull request merged**
