### PR TITLE
Reland Print library module manifest path again 

### PR DESCRIPTION
**Pull request by ChuanqiXu9**
Following of https://github.com/llvm/llvm-project/pull/82160

The reason why the above PR fails is that the `--sysroot` has lower priority than the libc++ built from the same source. On the one hand, it matches the codes behavior. We will add the built libc++ project paths in the ToolChain class. But we will only add the path related to sysroot in Linux class, which is derived from the ToolChain classes. So the paths of just built libc++ is in the front of the paths relative to sysroot. On the other hand, the behavior should be good from the higher level.  Since the just built libc++ has the same version number with the just built clang, so it makes sense that these 2 compilers just matches.

So for patch it self, I hacked it by using resource dir in the test since the resource dir has the higher priority, which is not strongly correct since we won't do that in practice.

@kaz7 would you like to test on your environment to avoid this get reverted again?

On the libc++ side, it shows that it lacks a `modules.json` file for the just built libc++ directory. If we don't have that, it will be problematic to use std modules from the just built clang and libc++ pair. Then it is not good. And I feel it may be problematic for future compiler/standard library developers. So I feel this is somewhat  a libc++ issue that need to be fixed.

Also if we don't like the hacked test in the current patch, we must wait for libc++ to fix this to proceed. But I feel this is somewhat odd since the test of clang shouldn't dependent on libc++.

CC: @mordante

### CODE REVIEW

**Review by kaz7 — APPROVED** [review]
Thank you for updating test scripts.  It works fine in the situation I explained before.  It works fine under VE buildbot configuration too.

**Review by mordante — APPROVED** [review]
Thanks for picking it up @ChuanqiXu9 and thanks for testing @kaz7.

**Comment by ChuanqiXu9** [comment]
I'll backport this tomorrow if no revert request shows up.

**Comment by Arthapz** [comment]
How do we use this ?
i tried 
```
> /opt/llvm-git/usr/bin/clang -std=c++23 -stdlib=libc++ -print-library-module-manifest-path
<NOT PRESENT>
```

and 

```
> /opt/llvm-git/usr/bin/clang -std=c++23 -stdlib=libc++ -print-library-module-manifest-path -resource-dir=/opt/llvm-git/usr/lib
<NOT PRESENT>
```
but no manifest path is returned

```
> fd .json /opt/llvm-git/usr/lib
/opt/llvm-git/usr/lib/libc++.modules.json
```

**Comment by mordante** [comment]
The file we're looking for is `modules.json`; Renaming it `libc++.modules.json` like `.so` / `.a` file might be a better idea which could avoid name clashes when installed in `/usr/lib`.

**Comment by ChuanqiXu9** [comment]
> The file we're looking for is `modules.json`; Renaming it `libc++.modules.json` like `.so` / `.a` file might be a better idea which could avoid name clashes when installed in `/usr/lib`.

BTW, how do you feel about the paragraph. I thought it as a defect in some level.

**Comment by Arthapz** [comment]
> The file we're looking for is `modules.json`; Renaming it `libc++.modules.json` like `.so` / `.a` file might be a better idea which could avoid name clashes when installed in `/usr/lib`.

but i didn't rename it, it was installed like this :/

**Comment by mordante** [comment]
> > The file we're looking for is `modules.json`; Renaming it `libc++.modules.json` like `.so` / `.a` file might be a better idea which could avoid name clashes when installed in `/usr/lib`.
> 
> but i didn't rename it, it was with the libc++ prefix directly :/

Good point I did :-/ It seems we originally talked about `modules.json` and later mentioned using the libname. @ChuanqiXu9 I prefer to keep the current name `libc++.modules.json` and adjust clang. WDYT?

**Comment by ChuanqiXu9** [comment]
> > > The file we're looking for is `modules.json`; Renaming it `libc++.modules.json` like `.so` / `.a` file might be a better idea which could avoid name clashes when installed in `/usr/lib`.
> > 
> > 
> > but i didn't rename it, it was with the libc++ prefix directly :/
> 
> Good point I did :-/ It seems we originally talked about `modules.json` and later mentioned using the libname. @ChuanqiXu9 I prefer to keep the current name `libc++.modules.json` and adjust clang. WDYT?

Could you elaborate the reason more? I feel like renaming `libc++.modules.json` to `modules.json` is straightforward. Maybe I didn't take part it in the old disscussion or I missed : )

**Comment by mordante** [comment]
> > > > The file we're looking for is `modules.json`; Renaming it `libc++.modules.json` like `.so` / `.a` file might be a better idea which could avoid name clashes when installed in `/usr/lib`.
> > > 
> > > 
> > > but i didn't rename it, it was with the libc++ prefix directly :/
> > 
> > 
> > Good point I did :-/ It seems we originally talked about `modules.json` and later mentioned using the libname. @ChuanqiXu9 I prefer to keep the current name `libc++.modules.json` and adjust clang. WDYT?
> 
> Could you elaborate the reason more? I feel like renaming `libc++.modules.json` to `modules.json` is straightforward. Maybe I didn't take part it in the old disscussion or I missed : )

It would allow to install libstdc++ and libc++ in the same lib directory without "fighting" who owns `modules.json`. Also if we want to provide `libc++-asan.so` in the future we can provide `libc++-asan.modules.json`. Whether we need a different `module.json` for ASan is unknown at the moment, but I can imagine we have additional compiler or linker flags for ASan.

**Comment by mordante** [comment]
Build system don't use this yet (since it wasn't available). I know CMake is working on implementing modules using libc++. Looking at the stage of the release I feel less comfortable to propose new features. So I think the feature should not be back ported.

I'm happy to pick this up, I expect to have time for it tomorrow.

**Comment by stellar-aria** [comment]
Can we also have a fallback check for stdlibs that don't have a `.so` version (such as embedded)? Something as simple as:
```c++
    std::string lib = GetFilePath("libc++.so", TC);
    if (lib.empty())
      lib = GetFilePath("libc++.a", TC);
```

**Comment by mordante** [comment]
> Can we also have a fallback check for stdlibs that don't have a `.so` version (such as embedded)? Something as simple as:
> 
> ```c++
>     std::string lib = GetFilePath("libc++.so", TC);
>     if (lib.empty())
>       lib = GetFilePath("libc++.a", TC);
> ```

Excellent point! thanks!

**Pull request merged**
