### PR TITLE
[CMake] Simplify building of bolt-optimized clang for distribution builds

### PR DESCRIPTION
**Pull request by tstellar**
Currently if you want to do a distribution build (i.e. using LLVM_DISTIRIBUTION_COMPONENTS) with a bolt-optimized clang, then you need to pass two separate targets to ninja like this:

ninja -C build clang-bolt distribiution

This patch simplifies this workflow so that you can do a distribution build with a bolt-optimized build with just a single target:

ninja -C build distribution

### CODE REVIEW

**Review by aaupov — APPROVED** [review]

**Review by smeenai — APPROVED** [review]

**Comment by petrhosek** [comment]
Could we also gate this on `CLANG_BOLT`?

**Comment by tstellar** [comment]
> Could we also gate this on `CLANG_BOLT`?

Is that redundant with the check for the clang-bolt target?

**Comment by tstellar** [comment]
I noticed this wasn't working for the install targets, so I had to add clang-bolt as a dependency to the install targets too.

I wonder if would be better to have the install targets depend on the `distribution` target instead.

**Comment by tstellar** [comment]
As I look into this more, it's not strictly a problem with distribution builds.  Just enabling bolt and running `ninja install-clang` does not give you a bolt optimized clang.  I'm going to try to do a more generic patch.

**Comment by aaupov** [comment]
> As I look into this more, it's not strictly a problem with distribution builds. Just enabling bolt and running `ninja install-clang` does not give you a bolt optimized clang. 

Right, for that matter, it's not triggered by `ninja clang` as well. There's a problem that clang-bolt depends on clang target, so clang-bolt can't be a provider for it. In theory we could decouple targets: if CLANG_BOLT is provided, pre-BOLT clang target could be called differently, and clang-bolt target could be the provider for clang. But I thought it would be too ambitious for me to change how clang is built, which is why clang-bolt is "on the side".

**Comment by tstellar** [comment]
> Right, for that matter, it's not triggered by `ninja clang` as well. There's a problem that clang-bolt depends on clang target, so clang-bolt can't be a provider for it. In theory we could decouple targets: if CLANG_BOLT is provided, pre-BOLT clang target could be called differently, and clang-bolt target could be the provider for clang. But I thought it would be too ambitious for me to change how clang is built, which is why clang-bolt is "on the side".

OK, I was thinking of doing something like `add_dependencies(install-clang clang-bolt)` but maybe it would make more sense for me to rewrite the clang target to do the bolt optimization.

**Comment by tstellar** [comment]
Closing this in favor of https://github.com/llvm/llvm-project/pull/119896.

**Pull request closed without merging**
