### PR TITLE
[libc] add stdlib.h header to the _Exit func proxy in full build

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Review by lntue — APPROVED** [review]

**Comment by nickdesaulniers** [comment]
Do you have more info about this change? Why not just provide the declaration here?

**Comment by Jobhdez** [comment]
> Do you have more info about this change? Why not just provide the declaration here?

the previous declaration was conflicted with the one generated in our stdlib.h:

```
/home/llvm-libc-buildbot/buildbot-worker/libc-x86_64-debian-fullbuild/libc-x86_64-debian-gcc-fullbuild-dbg/build/projects/libc/include/stdlib.h:101:16: error: function ‘void _Exit(int)’ declared ‘[[noreturn]]’ but its first declaration was not
  101 | _Noreturn void _Exit(int) __NOEXCEPT;
```

Should we remove `__NOEXCEPT` in our `_Exit`, because it is annotated as `THROW` in glibc header?

**Comment by nickdesaulniers** [comment]
> Should we remove __NOEXCEPT in our _Exit

I would expect `exit` to be noecept, since `exit` may execute callbacks provided by the user via `atexit` or `on_exit` calls.  If those callbacks throw when invoked via a call to `exit`, then it will appear that the call to `exit` threw.  But `_Exit` is supposed to skip those callbacks.

So it's not clear to my why glibc marks it's `_Exit` as noexcept.

**Comment by nickdesaulniers** [comment]
```c
extern void _Exit (int __status) __THROW __attribute__ ((__noreturn__));
```
is what my glibc host's headers have. `__THROW` which expands to:
```c
#  define __THROW       __attribute__ ((__nothrow__ __LEAF))
```
so glibc's `_Exit` is nothrow.

---
regardless, the warning is about `noreturn`, not `nothrow`.  The question isn't about throw/nothrow, it's that our declaration was missing `noreturn`.  If we redeclare a function, it needs to keep `noreturn` once declared with that fn attr.

**Comment by Jobhdez** [comment]
> ```c
> extern void _Exit (int __status) __THROW __attribute__ ((__noreturn__));
> ```
> 
> is what my glibc host's headers have. `__THROW` which expands to:
> 
> ```c
> #  define __THROW       __attribute__ ((__nothrow__ __LEAF))
> ```
> 
> so glibc's `_Exit` is nothrow.
> 
> regardless, the warning is about `noreturn`, not `nothrow`. The question isn't about throw/nothrow, it's that our declaration was missing `noreturn`. If we redeclare a function, it needs to keep `noreturn` once declared with that fn attr.

So do you want me to do a quick pr and add this to the proxy 

 `[[noreturn]] void _Exit() noexcept;` 

Can you please confirm if this declaration is the right one. Thanks

**Comment by nickdesaulniers** [comment]
> So do you want me to do a quick pr and add this to the proxy
> 
> `[[noreturn]] void _Exit() noexcept;`
> 
> Can you please confirm if this declaration is the right one. Thanks

don't forget the `int` parameter!
```c
[[noreturn]] void _Exit(int) noexcept;
```
but yeah, I'd approve such a PR.

**Comment by Jobhdez** [comment]
> > So do you want me to do a quick pr and add this to the proxy
> > `[[noreturn]] void _Exit() noexcept;`
> > Can you please confirm if this declaration is the right one. Thanks
> 
> don't forget the `int` parameter!
> 
> ```c
> [[noreturn]] void _Exit(int) noexcept;
> ```
> 
> but yeah, I'd approve such a PR.

Ok will do this now

**Pull request merged**
