### PR TITLE
[llvm][RISCV] Support RISCV vector tuple for llvm types

### PR DESCRIPTION
**Pull request by 4vtomat**
Currently we have built-in C types for RISCV vector tuple type, e.g.
vint32m1x2_t, however it's is represented as structure of scalable
vector types, i.e. {<vscale x 2 x i32>, <vscale x 2 x i32>}. It loses
the information for num_fields(NF) as struct is flattened during selection
DAG, thus it makes it not possible to handle inline assembly of vector
tuple type, it also makes the calling convention of vector tuple types
handing not strait forward and hard to realize the allocation code, i.e.
RVVArgDispatcher.

This patch add a llvm derived types called RISCVVectorTupleType which
contains both LMUL and NF(num_fields) information and keep it all the
way down to selection DAG to match the corresponding MVT(support in the
following patch). The llvm IR for the example above is then represented
as riscv_m1x2 in which the vector elements are inset/extract by using
llvm.vector.insert and llvm.vector.extract repectively.
There are total of 32 llvm types added for each VREGS * NF <= 8, where
VREGS is the vector registers needed for each lmul and NF is num_fields:
riscv_mf8x2, riscv_mf8x3, riscv_mf8x4, riscv_mf8x5, riscv_mf8x6, riscv_mf8x7, riscv_mf8x8,
riscv_mf4x2, riscv_mf4x3, riscv_mf4x4, riscv_mf4x5, riscv_mf4x6, riscv_mf4x7, riscv_mf4x8,
riscv_mf2x2, riscv_mf2x3, riscv_mf2x4, riscv_mf2x5, riscv_mf2x6, riscv_mf2x7, riscv_mf2x8,
riscv_m1x2, riscv_m1x3, riscv_m1x4, riscv_m1x5, riscv_m1x6, riscv_m1x7, riscv_m1x8,
riscv_m2x2, riscv_m2x3, riscv_m2x4,
riscv_m4x2.

### CODE REVIEW

**Comment by topperc** [comment]
This should probably be posted as an RFC on discourse.

**Comment by wangpc-pp** [comment]
Have you ever tried the target extension type yet?
* https://reviews.llvm.org/D135202
* https://discourse.llvm.org/t/rfc-adding-opaque-types-to-llvm-ir/
* https://reviews.llvm.org/D141899

**Comment by topperc** [comment]
> Have you ever tried the target extension type yet?
> 
> * https://reviews.llvm.org/D135202
> * https://discourse.llvm.org/t/rfc-adding-opaque-types-to-llvm-ir/
> * https://reviews.llvm.org/D141899

Is there any SelectionDAG support for target extension types?

**Comment by wangpc-pp** [comment]
> > Have you ever tried the target extension type yet?
> > 
> > * https://reviews.llvm.org/D135202
> > * https://discourse.llvm.org/t/rfc-adding-opaque-types-to-llvm-ir/
> > * https://reviews.llvm.org/D141899
> 
> Is there any SelectionDAG support for target extension types?

I don't think so, but there are some examples now.
Let me quote what jcranmer [said](https://discourse.llvm.org/t/rfc-adding-opaque-types-to-llvm-ir/65326/22):
> The types are currently being used for the svcount type in AArch64 and the SPIR-V builtin types. In both cases, these are being mapped from custom Clang builtin types and to custom MVT types in the LLVM code-gen.
>
> • Instruction selection. DAG or GISel.
> The LLVM backend is not my forte, but this seems to be working currently, although it is reliant on actually adding necessary type plumbing.
>
> • Middle-end optimizations. I think we should disable a lot of optimizations on opaque types I think.
> Because opaque types can appear in so few contexts, there’s not a lot of optimizations that could even be attempted on them in the first place.
>
> • Front-end(builtins/intrinsics) presentations.
> You would need to construct your own custom Clang types to map to the opaque types, and I’m rusty on the way Clang handles builtins. But again, this has been successfully used for some existing types already, so if you do the plumbing correctly, there doesn’t seem to be any issues.

**Comment by 4vtomat** [comment]
> > > Have you ever tried the target extension type yet?
> > > 
> > > * https://reviews.llvm.org/D135202
> > > * https://discourse.llvm.org/t/rfc-adding-opaque-types-to-llvm-ir/
> > > * https://reviews.llvm.org/D141899
> > 
> > 
> > Is there any SelectionDAG support for target extension types?
> 
> I don't think so, but there are some examples now. Let me quote what jcranmer [said](https://discourse.llvm.org/t/rfc-adding-opaque-types-to-llvm-ir/65326/22):
> 
> > The types are currently being used for the svcount type in AArch64 and the SPIR-V builtin types. In both cases, these are being mapped from custom Clang builtin types and to custom MVT types in the LLVM code-gen.
> > • Instruction selection. DAG or GISel.
> > The LLVM backend is not my forte, but this seems to be working currently, although it is reliant on actually adding necessary type plumbing.
> > • Middle-end optimizations. I think we should disable a lot of optimizations on opaque types I think.
> > Because opaque types can appear in so few contexts, there’s not a lot of optimizations that could even be attempted on them in the first place.
> > • Front-end(builtins/intrinsics) presentations.
> > You would need to construct your own custom Clang types to map to the opaque types, and I’m rusty on the way Clang handles builtins. But again, this has been successfully used for some existing types already, so if you do the plumbing correctly, there doesn’t seem to be any issues.

I guess in selectionDAG, we ultimately need to map each target extension types to their corresponding MVT, but I think it's a good way to try target extension types as well, thanks for reminding it!

**Comment by 4vtomat** [comment]
> This should probably be posted as an RFC on discourse.

Got it, I will post it after I try target extension types~

**Comment by 4vtomat** [comment]
> This should probably be posted as an RFC on discourse.

Do you think we should post 2 RFCs in both `IR & Optimizations` and `Code Generation for RISCV`, or just combine them into 1 RFC and post it in `LLVM Project` category?

**Comment by topperc** [comment]
> > This should probably be posted as an RFC on discourse.
> 
> @topperc do you think we should post 2 RFCs in both `IR & Optimizations` and `Code Generation for RISCV`, or just combine them into 1 RFC and post it in `LLVM Project` category?

Let's just do 1 RFC in LLVM Project.

**Comment by 4vtomat** [comment]
> > > This should probably be posted as an RFC on discourse.
> > 
> > 
> > @topperc do you think we should post 2 RFCs in both `IR & Optimizations` and `Code Generation for RISCV`, or just combine them into 1 RFC and post it in `LLVM Project` category?
> 
> Let's just do 1 RFC in LLVM Project.

Posted: https://discourse.llvm.org/t/rfc-support-riscv-vector-tuple-type-in-llvm/80005

**Comment by 4vtomat** [comment]
Use another approach.

**Comment by joshua-arch1** [comment]
Has debuginfo support been added for vector tuple types?

**Pull request closed without merging**
