### PR TITLE
[DirectX][NFC] Change usage pattern *Dxil* to *DXIL* for uniformity

### PR DESCRIPTION
**Pull request by bharadwajy**
Match DXIL TableGen class names with structure names in DXIL Emitter. 
Delete unnecessary Name field.

### CODE REVIEW

**Comment by bharadwajy** [comment]
@llvm-beanz @bogner @python3kgae @dmpots

**Review by bob80905 — APPROVED** [review]

**Review by llvm-beanz — COMMENTED** [review]
I have a preference for `DXIL` rather than `Dxil`. My reasoning is that DXIL is an initialism for DirectX Intermediate Language.

There are some places where LLVM's convention recommend it be `dxil` (i.e. `namespace dxil`), which makes sense to me, but I have an aversion to `Dxil`.

**Review by llvm-beanz — CHANGES_REQUESTED** [review]
There are only 4 places in the DirectX backend where we spell it `Dxil` today. this makes our spelling of the name less consistent not more.

While I'm not in favor of changing this spelling, if we want to we can discuss it but we should change it everywhere, not just in some places because that makes things worse.

**Comment by dmpots** [comment]
The title is out-of-date now. Not sure you can update it before merging, but would be good to fix it up when merging the change.

**Comment by dmpots** [comment]
> There are only 4 places in the DirectX backend where we spell it `Dxil` today. this makes our spelling of the name less consistent not more.
> 
> While I'm not in favor of changing this spelling, if we want to we can discuss it but we should change it everywhere, not just in some places because that makes things worse.

If we are sticking with the `DXIL` naming convention, then can we update this PR to catch all occurrences of the `Dxil` spelling? Or does this PR already cover that (not sure where the 4 instances occur).

**Comment by bharadwajy** [comment]
> The title is out-of-date now. Not sure you can update it before merging, but would be good to fix it up when merging the change.

Thanks! I updated the title.

**Comment by bharadwajy** [comment]
> > There are only 4 places in the DirectX backend where we spell it `Dxil` today. this makes our spelling of the name less consistent not more.
> > While I'm not in favor of changing this spelling, if we want to we can discuss it but we should change it everywhere, not just in some places because that makes things worse.
> 
> If we are sticking with the `DXIL` naming convention, then can we update this PR to catch all occurrences of the `Dxil` spelling? Or does this PR already cover that (not sure where the 4 instances occur).

The commit I pushed yesterday includes those 4 instances. They are in `DXILMetadata.cpp`. I checked to verify that there are no remaining occurrences of `Dxil` in the repo after the changes in this PR.

**Comment by dmpots** [comment]
> > > There are only 4 places in the DirectX backend where we spell it `Dxil` today. this makes our spelling of the name less consistent not more.
> > > While I'm not in favor of changing this spelling, if we want to we can discuss it but we should change it everywhere, not just in some places because that makes things worse.
> > 
> > 
> > If we are sticking with the `DXIL` naming convention, then can we update this PR to catch all occurrences of the `Dxil` spelling? Or does this PR already cover that (not sure where the 4 instances occur).
> 
> The commit I pushed yesterday includes those 4 instances. They are in `DXILMetadata.cpp`. I checked to verify that there are no remaining occurrences of `Dxil` in the repo after the changes in this PR.

Ok, thanks for clarifying. LGTM.

**Review by dmpots — APPROVED** [review]

**Review by python3kgae — APPROVED** [review]

**Review by llvm-beanz — APPROVED** [review]

**Comment by bharadwajy** [comment]
May I request one of the approvers / reviewers to help by pushing the changes, I do not have write access to `llvm-project` repo? 

Thanks!

**Pull request merged**
