### PR TITLE
[libcxx] Fix include directory order

### PR DESCRIPTION
**Pull request by abrachet**
Arch dir needs to go first.

### CODE REVIEW

**Review by petrhosek — APPROVED** [review]

**Review by mordante — CHANGES_REQUESTED** [review]
@abrachet Can you write a more descriptive commit message. Please explain why the current order is wrong.

Requesting changes since I want to understand the patch before it's merged. When it's important it should be commented in the code too.

**Comment by abrachet** [comment]
> @abrachet Can you write a more descriptive commit message. Please explain why the current order is wrong.

Updated the commit message

**Comment by mordante** [comment]
Can you add this part 
"It's important that the arch directory be included first so that
its header files which interpose on the default include dir
be included instead of the default ones."

as comment in the code too?

**Comment by abrachet** [comment]
> Can you add this part "It's important that the arch directory be included first so that its header files which interpose on the default include dir be included instead of the default ones."
> 
> as comment in the code too?

Done

**Review by mordante — APPROVED** [review]
LGTM. Please make sure that when landing the PR message is updated to the message of the commit. (I'm not sure whether GitHub does that automatically.)

**Comment by EricWF** [comment]
It was my understanding that libc++ didn't have any duplicate headers in the include/ and target include directory.
For example, the __config_site should only ever be in one.

Are you guys doing something weird?

**Comment by abrachet** [comment]
When `APPLE` `__config_site` gets generated in the default include dir [1], while other platforms will generate it in the arch dir [2]. We were cross compiling Mac -> Linux


[1] https://github.com/llvm/llvm-project/blob/main/libcxx/CMakeLists.txt#L438
[2] https://github.com/llvm/llvm-project/blob/main/libcxx/CMakeLists.txt#L422

**Comment by petrhosek** [comment]
This is only an issue on Darwin; on other platforms we install the target specific files such as `__config_site` into the per-target directory, i.e. `include/<target>/c++/v1/__config_site`, but on Darwin there is no per-target directory because Darwin supports multiple targets with a single set of files so `__config_site` is installed in `include/c++/v1/__config_site`.

**Pull request merged**
