### PR TITLE
[mlir][arith] Rename operations: `maxf` → `maximumf`, `minf` → `minimumf`

### PR DESCRIPTION
**Pull request by unterumarmung**
This patch is part of a larger initiative aimed at fixing floating-point `max` and `min` operations in MLIR: https://discourse.llvm.org/t/rfc-fix-floating-point-max-and-min-operations-in-mlir/72671.

This commit addresses Task 1.2 of the mentioned RFC. By renaming these operations, we align their names with LLVM intrinsics that have corresponding semantics.

### CODE REVIEW

**Comment by unterumarmung** [comment]
@dcaballe I guess we should post an announcement [here](https://discourse.llvm.org/c/mlir/mlir-deprecation/77)?

**Review by joker-eph — APPROVED** [review]

**Review by dcaballe — APPROVED** [review]

**Comment by dcaballe** [comment]
Thanks!

> @dcaballe I guess we should post an announcement [here](https://discourse.llvm.org/c/mlir/mlir-deprecation/77)?

Yeah, perhaps pointing at the RFC

**Review by kuhar — APPROVED** [review]
SPIR-V LGTM

**Comment by unterumarmung** [comment]
> Thanks!
> 
> > @dcaballe I guess we should post an announcement [here](https://discourse.llvm.org/c/mlir/mlir-deprecation/77)?
> 
> Yeah, perhaps pointing at the RFC

https://discourse.llvm.org/t/psa-renaming-ariths-maxf-and-minf-operations/73353
Done

**Review by rengolin — APPROVED** [review]

**Review by ThomasRaoux — APPROVED** [review]
LGTM, thanks!

**Pull request merged**
