### PR TITLE
[flang] Consider bind(c) when lowering calls to intrinsic module procedures

### PR DESCRIPTION
**Pull request by razvanlupusoru**
When attempting to lower an intrinsic module procedure call, take into account bind(c). Such procedures cannot be lowered as intrinsics since their implementation is external to the module.

With this solution, the hardcoded "omp_lib" string can be removed when checking if intrinsic module procedure since all procedure interfaces in that module use bind(c).

### CODE REVIEW

**Comment by clementval** [comment]
Do we need a test or is there one already for the omp_lib case?

**Comment by razvanlupusoru** [comment]
> Do we need a test or is there one already for the omp_lib case?

Yes - turns out we did need a lowering test for this. I confirmed that this new test fails if I remove the special case for "omp_lib", but passes with my change.

**Comment by vdonaldson** [comment]
The following functions from `omp_lib.h` do not have a `bind(c)`  attribute, which might be a problem.
```
    subroutine omp_set_affinity_format(format)
    function omp_get_affinity_format(buffer)
    subroutine omp_display_affinity(format)
    function omp_capture_affinity(buffer, format)
    function omp_pause_resource_all(kind)
    function omp_init_allocator(memspace, ntraits, traits)
    function omp_get_default_allocator()
```

**Comment by razvanlupusoru** [comment]
> The following functions from `omp_lib.h` do not have a `bind(c)` attribute, which might be a problem.
> 
> ```
>     subroutine omp_set_affinity_format(format)
>     function omp_get_affinity_format(buffer)
>     subroutine omp_display_affinity(format)
>     function omp_capture_affinity(buffer, format)
>     function omp_pause_resource_all(kind)
>     function omp_init_allocator(memspace, ntraits, traits)
>     function omp_get_default_allocator()
> ```

Nice catch! Those need the bind(c) attribute also. The implementation for these is not in the module - but in the runtime. llvm/openmp/runtime/src
I will update the module to note this!

**Comment by vdonaldson** [comment]
For the record, current processing has a negative string compare (to avoid
processing module omp_lib). It would also be possible to implement a positive
string compare (to apply processing to specific modules).

The public `llvm-project-mirror/flang/module` directory has 13 files that
each contain a single module. The first group of 4 modules have lowering code.
The second group of 8 modules do not appear to have lowering code, either
because they do not declare subprograms, or because subprograms are otherwise
implemented. I'm not sure about the status of (ppc) module mma.
````
   File                            Module                      Notes
-------------------------------------------------------------------------------
+  __fortran_builtins.f90          __fortran_builtins          lowering code
+  __fortran_ieee_exceptions.f90   __fortran_ieee_exceptions   lowering code
+  ieee_arithmetic.f90             ieee_arithmetic             lowering code
+  __ppc_intrinsics.f90            __ppc_intrinsics            lowering code

-  __cuda_builtins.f90             __CUDA_builtins             no functions
-  __fortran_type_info.f90         __fortran_type_info         no functions
-  ieee_exceptions.f90             ieee_exceptions             wrapper
-  ieee_features.f90               ieee_features               no functions
-  iso_c_binding.f90               iso_c_binding               wrapper
-  iso_fortran_env.f90             iso_fortran_env             no functions
-  omp_lib.f90                     omp_lib                     no lowering code
-  __ppc_types.f90                 __ppc_types                 no functions

?  mma.f90                         mma                         ?
````

**Comment by razvanlupusoru** [comment]
> For the record, current processing has a negative string compare (to avoid
> processing module omp_lib). It would also be possible to implement a positive
> string compare (to apply processing to specific modules).

Thank you for looking into those other modules also. And again for pointing out the issues with omp_lib module! :)

I still think that avoiding either a negative/positive test based on name is probably best. I think the bind(c) approach is more general and does solve my concern for the time being.

**Review by clementval — APPROVED** [review]

**Review by jeanPerier — APPROVED** [review]
LGTM

**Comment by kiranchandramohan** [comment]
Thanks, the patch looks fine to me.

Users might also use the `omp_lib.f90` from the OpenMP runtime. For some reason, these functions are not marked `bind(C)` there as well.
https://github.com/llvm/llvm-project/blob/4d4f603793aa134d1d04b60782fac0e6b0ed2172/openmp/runtime/src/include/omp_lib.f90.var#L524

I have asked a question in the patch that introduced this change. https://reviews.llvm.org/D55148. Maybe you can update there as well.

**Comment by razvanlupusoru** [comment]
> Thanks, the patch looks fine to me.
> 
> Users might also use the `omp_lib.f90` from the OpenMP runtime. For some reason, these functions are not marked `bind(C)` there as well.
> 
> https://github.com/llvm/llvm-project/blob/4d4f603793aa134d1d04b60782fac0e6b0ed2172/openmp/runtime/src/include/omp_lib.f90.var#L524
> 
> I have asked a question in the patch that introduced this change. https://reviews.llvm.org/D55148. Maybe you can update there as well.

Thanks Kiran for reviewing! I was considering adding you as a reviewer initially - but at first it seemed very little related to omp since I was just removing the hardcoded line to omp_lib. But either way, I appreciate you took the time to look!

Second, I do see that the module there is missing bind(c) also. I have looked at that module and I see several differences - not just this case. For example, in the F18 module, `omp_logical_kind = 1` and in that one `omp_logical_kind = 4`. My point is that there are several differences that likely need consolidated at some point - and I am not the right person to start doing that.

The fact that the module there is missing bind(c) is not an issue as the one in the F18 modules directory since if it is an user module, it won't be considered as intrinsic. But for anything that is intrinsic, we need to specify some implementation - otherwise we cannot distinguish between what remains to be implemented and what is implemented externally.

**Comment by kiranchandramohan** [comment]
> Second, I do see that the module there is missing bind(c) also. I have looked at that module and I see several differences - not just this case. For example, in the F18 module, `omp_logical_kind = 1` and in that one `omp_logical_kind = 4`. My point is that there are several differences that likely need consolidated at some point - and I am not the right person to start doing that.

Yes, at some point we have to copy that in (instead of the local omp_lib.f90), atleast for the upstream version installation since the upstream version will use the llvm openmp library. I agree that we have to consolidate the changes and that need not be part of this patch.

**Review by kiranchandramohan — APPROVED** [review]
LGTM.

**Comment by DominikAdamski** [comment]
@razvanlupusoru I get an error when I try to compile your test to binary:
```
flang-new -fopenmp flang/test/Lower/OpenMP/omp-lib-num-threads.f90
error: loc("flang/test/Lower/OpenMP/omp-lib-num-threads.f90":13:3): flang/lib/Optimizer/Builder/IntrinsicCall.cpp:1375: not yet implemented: intrinsic: omp_set_num_threads
```
There is no error message about not implemented intrinsic, if I revert your changes.

**Comment by clementval** [comment]
There is likely a missing `bind©` for `omp_set_num_threads` in your module file.

**Comment by kiranchandramohan** [comment]
I think there is an issue with the non-HLFIR flow.

**Comment by razvanlupusoru** [comment]
> @razvanlupusoru I get an error when I try to compile your test to binary:
> 
> ```
> flang-new -fopenmp flang/test/Lower/OpenMP/omp-lib-num-threads.f90
> error: loc("flang/test/Lower/OpenMP/omp-lib-num-threads.f90":13:3): flang/lib/Optimizer/Builder/IntrinsicCall.cpp:1375: not yet implemented: intrinsic: omp_set_num_threads
> ```
> 
> There is no error message about not implemented intrinsic, if I revert your changes.

Thank you for letting me know! :)
https://github.com/llvm/llvm-project/pull/71101

**Pull request merged**
