### PR TITLE
[AArch64][GlobalISel] Select G_ICMP Zero Instruction

### PR DESCRIPTION
**Pull request by chuongg3**

### CODE REVIEW

**Comment by aemerson** [comment]
If these patterns are only applicable to GlobalISel then you can move them to `AArch64InstrGISel.td`

**Comment by chuongg3** [comment]
> If these patterns are only applicable to GlobalISel then you can move them to `AArch64InstrGISel.td`

It might be better if we do not special case GlobalISel unless necessary and integrate it more into existing patterns. What do you think?

**Comment by aemerson** [comment]
Is there any effect on SDAG codegen? If so then we can keep it in InstrInfo but if these new patterns only influence GlobalISel then I think it makes sense to separate them to avoid confusion about their purpose.

**Comment by arsenm** [comment]
We do have a new control bit you can use to disable patterns from importing in GlobalIsel if the dag strategy is not useful here

**Comment by aemerson** [comment]
> > Is there any effect on SDAG codegen? If so then we can keep it in InstrInfo but if these new patterns only influence GlobalISel then I think it makes sense to separate them to avoid confusion about their purpose.
> 
> Hi - I'm not sure if it is best to keep them separate, and continue treating GlobalISel as a special thing that is off in its own corner. It feels better in the long run to treat these as standard patterns, put where they belong compared to all the other instructions. They should probably be documented that they apply to GISel to keep it clear, and my opinions on this are not very strongly held. #89932 is probably the best place to mention if you think having the patterns separate is better.

I can see the benefits of integration but if we do keep GISel patterns alongside the SDAG ones then comments indicating their purpose are a must IMO. @chuongg3 this is your call.

**Review by aemerson — APPROVED** [review]
LGTM, thanks. This is a nice cleanup.

**Pull request merged**
