### PR TITLE
[flang] Add nsw to DO loop parameters

### LINKED ISSUE #110609: [Flang] TSVC s115: compiler doesn't vectorize the loop considering an initial value of do-variable might overflow
Flang can't vectorize the loop in `s115` of [TSVC](https://www.netlib.org/benchmark/vectors) while Clang can vectorize the loop written in C.

* Fortran
```fortran
!     Fortran version
      subroutine s115 (ntimes,ld,n,ctime,dtime,a,b,c,d,e,aa,bb,cc)

      integer ntimes, ld, n, i, nl, j
      real a(n), b(n), c(n), d(n), e(n), aa(ld,n), bb(ld,n), cc(ld,n)

      call init(ld,n,a,b,c,d,e,aa,bb,cc,'s115 ')
      do 10 j = 1,n
         do 20 i = j+1, n
            a(i) = a(i) - aa(i,j) * a(j)
  20     continue
  10  continue
      call dummy(ld,n,a,b,c,d,e,aa,bb,cc,1.)
      end
```
```console
$ flang-new -v -O3 -flang-experimental-integer-overflow s115.f -S -Rpass=vector
flang-new version 20.0.0git (https://github.com/llvm/llvm-project.git 2c770675ce36402b51a320ae26f369690c138dc1)
Target: aarch64-unknown-linux-gnu
Thread model: posix
InstalledDir: /path/to/build/bin
Build config: +assertions
Found candidate GCC installation: /usr/lib/gcc/aarch64-redhat-linux/11
Selected GCC installation: /usr/lib/gcc/aarch64-redhat-linux/11
Candidate multilib: .;@m64
Selected multilib: .;@m64
 "/path/to/build/bin/flang-new" -fc1 -triple aarch64-unknown-linux-gnu -S -fcolor-diagnostics -mrelocation-model pic -pic-level 2 -pic-is-pie -target-cpu generic -target-feature +outline-atomics -target-feature +v8a -target-feature +fp-armv8 -target-feature +neon -fversion-loops-for-stride -flang-experimental-integer-overflow -Rpass=vector -resource-dir /path/to/build/lib/clang/20 -mframe-pointer=non-leaf -O3 -o /dev/null -x f95-cpp-input s115.f
```

* C
```c
// C version
#define LEN 32000
#define LEN2 256
float a[LEN], b[LEN], c[LEN], d[LEN], e[LEN];
float aa[LEN2][LEN2], bb[LEN2][LEN2], cc[LEN2][LEN2];

int s115() {
  init( "s115 ");
  for (int j = 0; j < LEN2; j++) {
    for (int i = j+1; i < LEN2; i++) {
      a[i] -= aa[j][i] * a[j];
    }
  }
  dummy(a, b, c, d, e, aa, bb, cc, 0.);
  return 0;
}
```
```console
$ clang -O3 s115.c -S -Rpass=vector
s115.c:10:4: remark: vectorized loop (vectorization width: 4, interleaved count: 2) [-Rpass=loop-vectorize]
   10 |                         for (int i = j+1; i < LEN2; i++) {
      |                         ^
```

If `j+1` overflow, the access to `a(i)` and `a(j)` may overlap so vectorization is prevented.
IIRC, compilers don't have to consider it.

### PR DESCRIPTION
**Pull request by yus3710-fj**
nsw is added to DO loop parameters (initial parameters, terminal parameters, and incrementation parameters).
This can help vectorization in some cases like #110609.

See also the discussion in https://discourse.llvm.org/t/rfc-add-nsw-flags-to-arithmetic-integer-operations-using-the-option-fno-wrapv/77584/20.

The following is the result of the measurement of SPEC CPU 2017:

||speedup from a87f776c1c873ea86a95c368f1a9331adc65d1ee|
|---|---|
|503.bwaves_r|x1.001|
|507.cactuBSSN_r|x1.005|
|521.wrf_r|x0.9991|
|527.cam4_r|x1.007|
|549.fotonik3d_r|x1.008|
|548.exchange2_r|x0.9994|

### CODE REVIEW

**Review by tblah — COMMENTED** [review]
The changes look okay to me. Perhaps in another patch you could investigate if there is any benefit in doing the same for fir.do loops generated through other paths through lowering (e.g. bufferization of a hlfir.elemental). 

Please could you update the description describing what performance regression testing have you done on this patch and what speedups you expect (if there are any beyond the one testcase in the RFC).

**Review by jeanPerier — APPROVED** [review]
Looks good to me (please address Tom's questions).

I verified that at least gfortran/ifort are optimizing the following program assuming that "n+1" cannot wrap:

```
subroutine foo(x, n, m)
  integer :: n, m
  integer :: x(m)
  do i=n,n+1
    x(i) = i
  end do
end subroutine
```

They both optimize this into two executions of the body without branches, which also what LLVM does after your patch. So there is a precedent in leveraging the language semantics here and this won't come as a surprise for existing application.

**Comment by yus3710-fj** [comment]
> Please could you update the description describing what performance regression testing have you done on this patch and what speedups you expect (if there are any beyond the one testcase in the RFC).

I apologize for the delayed response, @tblah. I've completed my performance regression tests using SPEC2017 and added the results to the description.
The results indicate this patch does not introduce performance issues, so I believe this patch could be merged.

**Review by tblah — APPROVED** [review]
Thanks!

**Pull request merged**
