### PR TITLE
[RISCV] Handle empty structs/unions passing in C++

### LINKED ISSUE #97285: [RISC-V] Empty structs are ignored when passing in C++
According to RISC-V integer calling convention:
> Empty structs or union arguments or return values are ignored by C compilers which support them
as a non-standard extension. **This is not the case for C++, which requires them to be sized types.**

```C++
struct Empty {};

int after_empty(int i0, Empty e, int i1)
{
	return i1;
}

int after_empty_on_stack(
    int i0, int i1, int i2, int i3, int i4, int i5, int i6, int i7, Empty e, int i8)
{
	return i8;
}
```

Clang doesn't assign a register nor a stack slot to the empty struct for passing:
```asm
after_empty(int, Empty, int):                # @after_empty(int, Empty, int)
        mv      a0, a1
        ret
after_empty_on_stack(int, int, int, int, int, int, int, int, Empty, int): # @after_empty_on_stack(int, int, int, int, int, int, int, int, Empty, int)
        ld      a0, 0(sp)
        ret
```

I'd expect these functions to be `mv a0, a2` and `ld a0, 8(sp)` respectively.

This also doesn't match GCC which does allocate a register and stack slot to the empty struct argument. [Comparison with GCC on Godbolt](https://godbolt.org/#z:OYLghAFBqd5QCxAYwPYBMCmBRdBLAF1QCcAaPECAMzwBtMA7AQwFtMQByARg9KtQYEAysib0QXLnwEEAqgGdMABQAenAAy8AVhNK0mDUMgCkAJgBCZ86UX1kBPAMqN0AYVS0AriwYhTpFwAZPAZMADlvACNMYgl/AAdUeUJHBncvH11E5IcBYNCIlmjYqVtMe1ShAiZiAnTvX38yioEqmoJ88KiYuJtq2vrM0v6OkK6inq4AShtUT2Jkdg55AmJPewBqbBZ4ggBPDeMAdksjgBFjAGZLdQBBYzuQgg2mKgIYgH1MHf2IJ428OpSFsfgdMMD/nhpg97icYQ8AJzETAEeYMAFcK43WEXO4w/6vd7EL6gj4CD4rJjIADWEBhGwZAMEAKBTOeUIhzLw/jZAMunPZABYBQCAKwivAANglR2B212YIlAA4pvC4Xj1EiUWiAUqsWqzhwZrROKLeL5uLxUJxXFYrBt5HMFphDqZLjxSAQNEaZtSQJdLgA6AMh0Nh6UmjiC83e0jWji8eQgIFejiaGZwWBINA7OgxciUHPxPOxYgAN0lgoAtMh9IYuEquECaLQiUmIJFY5EQjU9pwPd3mMQ9gB5SJacqpj05tiCEcMWh9tO8LCRTzAVxiWhJy2kLAsAzAcTLvd4ZEVMuYHeaAIqcqed793hPTCRm%2B0PCRYi99xYWOrPAWCfUhL2ISIkkwM5vkPD9DG9GYqH0YB5AANTwTAAHcR3iRhgP4QQRDEdhJGkQQFGUNQTx0KQ6yMO0LD0T8k0gGZUF2VIdyrEcAC8rVA4g8CwZiIBmZpcl8CAXEGXwuH8IIxkKYoQGlbIUgEaTelU8TOkUnppTEyoRg02SbFfSdDPaHTulifSjI8BpekpWorImGzRKdRYJGNU0YxPeMNgAJQASSEVwqxQjZy0rYBkA2WtDw2BtAy4QN1A2CBcEIEhXXdKZeFTdNfX9IMw1KkMI04aNSAtG940TZNPXg0hM0QFBUFzegyAoCAixLEAourGLkC4QUmz4Og20oTsT0HXtgNm4cxwnexgJnRgCHnRdY1XddN1obdgP3GClhvfBzwcS9r14TA72QB8lg9F8314D8vx/DATvygSgN3UDwMUKCD0MWDQGXBCkNQ9CsJwi0PXw4RRHEEj4fI1RYx0fxaJQejrFe4TWPYgROJ4viYgEoT4FEsyWgkqT7KGAIGHQFylKkLTUmM0h2byBTrN0AzWjsjIZNMuxxLaZzedc/mhYc4ZLKl1n3PmTzpj0HzqtjfzgtC8L0srKtuwIeQpg2IbEsFZLUvSzKiGIHLpny%2BCioDYMytK9Wo182rOHqlNnc90xvatX3GrBmZQOSJxBSAA%3D%3D)

ISA: rv64gc
Clang version: 18.1.0 and Godbolt "trunk" at the time of filing this issue (2024-07-01).

### PR DESCRIPTION
**Pull request by svs-quic**
According to RISC-V integer calling convention empty structs or union arguments or return values are ignored by C compilers which support them as a non-standard extension. This is not the case for C++, which requires them to be sized types.

Fixes #97285

### CODE REVIEW

**Comment by topperc** [comment]
Why is this in Draft?

**Comment by svs-quic** [comment]
Just waiting for the pre-checkins to complete.

**Comment by efriedma-quic** [comment]
Please add a test for `struct X { int x[0]; };`.

**Comment by svs-quic** [comment]
Thanks @efriedma-quic. I tried adding a test case for it locally and see that the code produced is different for llvm and gcc: https://godbolt.org/z/vdhGbvj6W

Test case:
```
struct s12 {int x[0];};
struct s12 test_s12(struct s12 a) {
  return a;
}
```
For llvm this is an empty record of size zero and so it ignores it where as gcc loads 0 into a0.  Do we handle this case similar to what gcc does? Or do I add a fixme for now? 

@topperc @asb

**Comment by efriedma-quic** [comment]
The current spec language is:

> Empty structs or union arguments or return values are ignored by C compilers which support them as a non-standard extension. This is not the case for C++, which requires them to be sized types.

So empty structs in C are ignored, empty structs in C++ are treated as non-empty.

The "C++ struct containing an empty array" is sort of an edge case, since it's not actually legal C++, but the spec says the distinguishing factor is whether we're in C++ mode.  And gcc seems to do that, so let's do the same thing.  So instead of checking for `Size == 0`, check for `LangOpts.CPlusPlus`.

Also, please add a release note for this.

**Comment by topperc** [comment]
> The current spec language is:
> 
> > Empty structs or union arguments or return values are ignored by C compilers which support them as a non-standard extension. This is not the case for C++, which requires them to be sized types.
> 
> So empty structs in C are ignored, empty structs in C++ are treated as non-empty.
> 
> The "C++ struct containing an empty array" is sort of an edge case, since it's not actually legal C++, but the spec says the distinguishing factor is whether we're in C++ mode. And gcc seems to do that, so let's do the same thing. So instead of checking for `Size == 0`, check for `LangOpts.CPlusPlus`.
> 
> Also, please add a release note for this.

gcc does ignore the empty array case for assigning argument registers in C++. Compare the two cases here https://godbolt.org/z/j4WP89rE8

**Comment by svs-quic** [comment]
> The current spec language is:
> 
> > Empty structs or union arguments or return values are ignored by C compilers which support them as a non-standard extension. This is not the case for C++, which requires them to be sized types.
> 
> So empty structs in C are ignored, empty structs in C++ are treated as non-empty.
> 
> The "C++ struct containing an empty array" is sort of an edge case, since it's not actually legal C++, but the spec says the distinguishing factor is whether we're in C++ mode. And gcc seems to do that, so let's do the same thing. So instead of checking for `Size == 0`, check for `LangOpts.CPlusPlus`.
> 
> Also, please add a release note for this.

Thanks Eli. I have made these changes.

**Comment by efriedma-quic** [comment]
> gcc does ignore the empty array case for assigning argument registers in C++. Compare the two cases here https://godbolt.org/z/j4WP89rE8

Oh, you're right, I didn't actually do any testing myself, I was just assuming @svs-quic did the right test.

So I guess the previous size==0 check was actually correct.

**Comment by svs-quic** [comment]
> Thanks @efriedma-quic. I tried adding a test case for it locally and see that the code produced is different for llvm and gcc: https://godbolt.org/z/vdhGbvj6W
> 
> Test case:
> 
> ```
> struct s12 {int x[0];};
> struct s12 test_s12(struct s12 a) {
>   return a;
> }
> ```
> 
> For llvm this is an empty record of size zero and so it ignores it where as gcc loads 0 into a0. Do we handle this case similar to what gcc does? Or do I add a fixme for now?
> 
> @topperc @asb

What about the case I have mentioned in https://godbolt.org/z/vdhGbvj6W ?

Having a check for both Size==0 and LangOpts.CPlusPlus handles this as well.

**Comment by efriedma-quic** [comment]
> What about the case I have mentioned in https://godbolt.org/z/vdhGbvj6W ?

That test doesn't really prove anything useful.  The zeroing of a0 doesn't have any ABI significance: "struct s12" doesn't have any data in it, so the caller can't use the value in a0 for anything.  At most, it's a hint about how gcc's internal logic works.

**Comment by svs-quic** [comment]
Thanks. I have modified the check and added a relevant test for empty arrays.

**Review by efriedma-quic — APPROVED** [review]
LGTM

**Review by topperc — APPROVED** [review]
LGTM

**Comment by svs-quic** [comment]
Could someone please merge this change? I do not have permissions to do so.

**Comment by topperc** [comment]
> Could someone please merge this change? I do not have permissions to do so.

Done

**Pull request merged**
