### PR TITLE
[libc] Fix accidental LIBC_NAMESPACE_clock_freq

### PR DESCRIPTION
**Pull request by alfredfo**
See-also: https://github.com/llvm/llvm-project/pull/69548

### CODE REVIEW

**Comment by alfredfo** [comment]
@gchatelet

**Review by jhuber6 — APPROVED** [review]
It's funny how this worked without noticing the failure because it changed all the symbol names.

**Comment by alfredfo** [comment]
Indeed, lol

**Comment by gchatelet** [comment]
Thx for the fix @alfredfo !!

**Pull request merged**
