### PR TITLE
[X86] Use a less expensive regex for matching X86 shuffles

### PR DESCRIPTION
**Pull request by tstellar**
Replace .*#+ regex with [^#]+#+ in the x86 tests.  This new pattern is much easier for the regex implementation to match.  This change reduces the time to run make check for llvm from ~105s to ~102.5s on my 64 core machine.  The improvement should be bigger on systems with less cores. This also reduces the run time of some of the longer running x86 tests by about 10%.

I also updated the llvm/utils/update_llc_test_checks.py to generate this new sequence, but I did not regenerate the tests using this script.  I just ran a simple sed command on the test directory in order to minimize the amount of changes.  This is the script I used to update the tests:

for f in `find ./llvm/test/CodeGen/X86/ -type f`; do
  sed -i 's/{{\.\*#+}}/{{[^#]+#+}}/g' $f;
done

I also think we can do better matching the X86 suffles, since all the information about the registers and the shuffle mask is captured after the comment, we could also just match the instruction operands with a simple string.  This should provide even more speedups since FileCheck has a fast path for strings with no regexes.

### CODE REVIEW

**Comment by phoebewang** [comment]
Didn't check on much files, but the change looks good to me.
Since only memory shuffles have this pattern, I think it's safe to replace them in one shoot and not need to run script on each of them.
What's the reason the change is faster? I thought `.*` is faster that `[^#]+` before.

**Comment by topperc** [comment]
> Didn't check on much files, but the change looks good to me. Since only memory shuffles have this pattern, I think it's safe to replace them in one shoot and not need to run script on each of them. What's the reason the change is faster? I thought `.*` is faster that `[^#]+` before.

`.*` is greedy, it will at every character it can all the way to the end of the line. Then it will see that is needs to find a `#` and has to start backtracking to remove the `#` that was greedily consumed by the `.*`.

**Comment by RoboTux** [comment]
> 
> I also updated the llvm/utils/update_llc_test_checks.py to generate this new sequence, but I did not regenerate the tests using this script. I just ran a simple sed command on the test directory in order to minimize the amount of changes. This is the script I used to update the tests:
> 
> for f in `find ./llvm/test/CodeGen/X86/ -type f`; do sed -i 's/{{.*#+}}/{{[^#]+#+}}/g' $f; done
> 

```
That doesn't seem safe as a command:
$ cat foobar 
{{abc#+}}
$ sed -i 's/{{.*#+}}/{{[^#]+#+}}/' foobar
$ cat foobar 
{{[^#]+#+}}
```

The command should be `sed -i 's/{{\.\*}}/{{[^#]+#+}}/'`

It might not change anything in practice if the only place with {{<something>#+}} is those pattern that you want to modify but I thought I'd point it out just in case. The regex change itself looks good to me.

**Review by RKSimon — APPROVED** [review]
LGTM - cheers

**Comment by arsenm** [comment]
is there a reason this wasn't merged?

**Comment by RKSimon** [comment]
@tstellar reverse-ping

**Comment by nikic** [comment]
> is there a reason this wasn't merged?

IIRC the motivation for this mostly went away after some optimizations in FileCheck.

**Comment by arsenm** [comment]
> > is there a reason this wasn't merged?
> 
> IIRC the motivation for this mostly went away after some optimizations in FileCheck.

We could still go ahead with simpler regexes

**Pull request closed without merging**
