### PR TITLE
[clang][OpenMP] Add const-qualified `getIteratorModifier` to OMPMapClause

### PR DESCRIPTION
**Pull request by kparzysz**
NFC

### CODE REVIEW

**Comment by alexey-bataev** [comment]
Do we have a user for this function?

**Comment by kparzysz** [comment]
I don't think so, because nothing is failing without it.  This is just for completeness.

**Comment by alexey-bataev** [comment]
> I don't think so, because nothing is failing without it. This is just for completeness.
> 
> Edit: My code will use it, but at the moment there aren't any users that I know of.

Are you going to submit your code?

**Comment by kparzysz** [comment]
> Are you going to submit your code?

Yes, but it's still incomplete.  I can wait with this PR if you prefer.

**Comment by alexey-bataev** [comment]
> > Are you going to submit your code?
> 
> Yes, but it's still incomplete. I can wait with this PR if you prefer.

Yes, I think better to introduce it with the actual user.

**Comment by kparzysz** [comment]
Will revisit this when the using code is ready for review/merge.

**Pull request closed without merging**
