### PR TITLE
[LoongArch] Set isAsCheapAsAMove on ADDI.D and {X}ORI instructions

### PR DESCRIPTION
**Pull request by heiher**

### CODE REVIEW

**Comment by SixWeining** [comment]
About the title: lu12i.w but not lu12i.d

**Comment by SixWeining** [comment]
Seems lu32i.d is 4x slower than move (or).

**Comment by heiher** [comment]
> About the title: lu12i.w but not lu12i.d

Good catch! It seems that removing the suffix of `LUXX` will not make it unclear. :)

**Comment by heiher** [comment]
> Seems lu32i.d is 4x slower than move (or).

Real tests do not show `lu32i.d` to be slower than `move (or)` when they have the same data dependencies. However, I would still remove the `lu{12,32,52}i` instructions, as they add more instructions to the loop.

**Review by SixWeining — APPROVED** [review]

**Pull request merged**
