### PR TITLE
[mlir] [tensor] Fix typo in tensor.pack documentation

### PR DESCRIPTION
**Pull request by meshtag**

### CODE REVIEW

**Review by Lewuathe — COMMENTED** [review]
What is the point of this change? Do you want to render sentences following colon as list?

Screenshot 2023-12-11 at 13 34 15

**Comment by meshtag** [comment]
I felt this part 
```
inner_dims_pos (mandatory) specifies k source tensor dimensions that are being tiled, where 0 < k <= n. The order of the dimensions matters: 
```
was unnecessarily repeated twice. 

And the two sentences that are a part of the list are directly related to/explaining the working of `inner_dims_pos`

**Review by Lewuathe — APPROVED** [review]
@meshtag Oh, good point. Sorry, I overlooked the part. It looks good to me now.

**Review by chelini — APPROVED** [review]
Thanks!

**Comment by meshtag** [comment]
Gentle ping @matthias-springer

**Review by matthias-springer — APPROVED** [review]

**Comment by meshtag** [comment]
Can somebody help me by landing this. 

Thanks!

**Pull request merged**
