### PR TITLE
Reapply "Use an abbrev to reduce size of VALUE_GUID records in ThinLTO summaries" (#90610)

### PR DESCRIPTION
**Pull request by jvoung**
This reverts commit 2aabfc811670beb843074c765c056fff4a7b443b.

Add fixes to LLD and Gold tests missed in original change.

### CODE REVIEW

**Comment by jvoung** [comment]
Hi @teresajohnson, one more try now with a few more test updates. Thanks!

**Review by teresajohnson — APPROVED** [review]

**Comment by jvoung** [comment]
Would you mind helping merge again (still missing commit permissions)? Thank you!

**Comment by teresajohnson** [comment]
> Would you mind helping merge again (still missing commit permissions)? Thank you!

Sure, done!

**Comment by kamaub** [comment]
It appears this change has exposed an issue with the test case, [compiler-rt/test/profile/instrprof-gc-sections.c](https://github.com/llvm/llvm-project/blob/main/compiler-rt/test/profile/instrprof-gc-sections.c), failing on [clang-ppc64le-linux-multistage](https://lab.llvm.org/buildbot/#/builders/121), first build[41260](https://lab.llvm.org/buildbot/#/builders/121/builds/41260), and  [clang-ppc64le-linux-test-suite](https://lab.llvm.org/buildbot/#/builders/230), first build[27968](https://lab.llvm.org/buildbot/#/builders/230/builds/27968). Neither bot builds or links with `lld`, all the tested binaries are linked with `ld` on purpose as we already had `lld` buildbots yet the `// REQUIRES: lld-available` check/guard passes anyway after detecting an lld linker available elsewhere on the host machine. I think the correct behavior would be for it to only search the build directory that the test case is suppose to test.

A solution is not known yet, I wanted to bring this up here for discussion so we could work towards one.

**Comment by jvoung** [comment]
Hi Kamau, thanks for looking into that!

Not sure of a great solution yet either, but some notes from an initial scan:
- `lld-available` depends on `config.has_lld` [link](https://github.com/llvm/llvm-project/blob/54d6f6626d9377115f3db3ab3fd5994b0de5a268/compiler-rt/test/lit.common.cfg.py#L499)
- not totally sure what controls `has_lld` but looks like it could depend on `COMPILER_RT_HAS_LLD_PYBOOL` [link](https://github.com/llvm/llvm-project/blame/54d6f6626d9377115f3db3ab3fd5994b0de5a268/compiler-rt/test/lit.common.configured.in#L40)
- `COMPILER_RT_HAS_LLD` seems to be set around [here](https://github.com/llvm/llvm-project/blob/d53425e2a33a0ff7336c86d3f668b1855c47a6de/compiler-rt/CMakeLists.txt#L785) if `LINKER_IS_LLD` or `LLVM_TOOL_LLD_BUILD`. I assume you don't have `LLVM_TOOL_LLD_BUILD`
- `LINKER_IS_LLD` can be set [at least here](https://github.com/llvm/llvm-project/blob/d53425e2a33a0ff7336c86d3f668b1855c47a6de/llvm/cmake/modules/HandleLLVMOptions.cmake#L20)

Looking at the later two locations, perhaps setting `LLVM_USE_LINKER` and/or `CMAKE_LINKER` could help control that? I'm having a bit of trouble reproducing, so I'm not sure if those are the best solutions yet, but thought I'd share for discussion.

**Comment by chenzheng1030** [comment]
While we are still working on solution for the PPC failures, and seems it requires some time, could we revert this patch first to unblock the PPC build bots? Thanks very much. @jvoung

**Comment by kamaub** [comment]
I believe the culprit commit is [[test][sanitizer] Check LINKER_IS_LLD to detect LLD](https://github.com/llvm/llvm-project/commit/2344a72dd63661098244b3bc43696710686ef9d9).

I took d751e407def4e1540ae0af12a179ce4f2a8f676c as my top of trunk and was able to reproduce locally by adding `clang.16.0.1/bin/lld` to my $PATH variable then building with gcc as [clang-ppc64le-linux-multistage](https://lab.llvm.org/buildbot/#/builders/121) does: 
```
cmake-3.28.2/bin/cmake -G Ninja ../llvm-project/llvm -DCMAKE_BUILD_TYPE=Release -DLLVM_ENABLE_ASSERTIONS=True '-DLLVM_LIT_ARGS='"'"'-v'"'"'' -DCMAKE_INSTALL_PREFIX=../stage1.install -DLLVM_ENABLE_ASSERTIONS=ON -DBUILD_SHARED_LIBS=ON -DCMAKE_C_COMPILER_LAUNCHER=ccache -DCMAKE_CXX_COMPILER_LAUNCHER=ccache '-DLLVM_ENABLE_PROJECTS=clang-tools-extra;llvm;clang' -DLLVM_ENABLE_RUNTIMES=compiler-rt && ninja -j 96 && ninja -j 96 check-all
```
 Using this I was able to reproduce `FAIL: Profile-powerpc64le :: instrprof-gc-sections.c (81665 of 84128)` and then after:
```
$ git revert 2344a72
Auto-merging compiler-rt/CMakeLists.txt
[main bcffe4472175] Revert "[test][sanitizer] Check LINKER_IS_LLD  to detect LLD"
 1 file changed, 6 insertions(+), 8 deletions(-)
```
it changed to `UNSUPPORTED: Profile-powerpc64le :: instrprof-gc-sections.c (81472 of 84128)`
I think this is the expected behavior and it also matches the behavior what Hans [reported](https://github.com/llvm/llvm-project/commit/2344a72dd63661098244b3bc43696710686ef9d9#commitcomment-128524063) on the same changeset.

@vitalybuka can you please take a look. The reproducing condition is to observe that `lld` test cases are being ran and tested when `lld` is not build or set to be linked with (ppc links with `ld` by default). For some reason your change ends up searching for `lld` general availability which would mean it test the wrong lld and gives a false positive/negative.

**Comment by jvoung** [comment]
Thanks @kamaub for looking into this more, and for instructions on how to reproduce (I can repro now).

Another thought is if it makes sense to change the `config.lto_supported` [detection](https://github.com/llvm/llvm-project/blob/d92c67784f21063d6334a009dbf4f9e0f8217b41/compiler-rt/test/lit.common.cfg.py#L753) in the Linux+LLD case to check that LLD is built and thus understands the latest changes like the version, and not a possibly old copy of LLD. For example, in the Linux+Gold case it checks `os.path.exists(os.path.join(config.llvm_shlib_dir, "LLVMgold.so"))`, or in the Windows case it checks `os.path.exists(os.path.join(config.llvm_tools_dir, "lld-link.exe"))`. Can we then check `os.path.exists(os.path.join(config.llvm_tools_dir, "lld"))` ?

@MaskRay you mentioned something like this is in https://github.com/llvm/llvm-project/commit/746b5fad5b53ddbc78d36a6b97dcaff7e52540b2  

Would making the `lto_supported` stricter make sense, or do you have a recommendation here?

Then the test should probably check if feature `lto` is available (since it adds flags `-flto`). There is some interesting fallback [here](https://github.com/llvm/llvm-project/blob/ec36145f58d2cf93d86bc4e3be617ad7d7d8ace7/compiler-rt/test/profile/lit.cfg.py#L67) where it checks `lto_supported` and may choose not to add `-flto`, but currently the test unconditionally adds `-flto`.

**Pull request merged**
