### PR TITLE
[flang][openacc] Lower DO CONCURRENT with acc loop

### PR DESCRIPTION
**Pull request by clementval**
Lower basic DO CONCURRENT with acc loop construct. The DO CONCURRENT is lowered to an acc.loop operation.

This does not currently cover the DO CONCURRENT with locality specs.

### CODE REVIEW

**Review by razvanlupusoru — COMMENTED** [review]
This is great.

I think the acc.loop should also be marked with appropriate attribute as part of this change:
```
3353 2.17.2 Do Concurrent Construct
3354 This section refers to the Fortran do concurrent construct that is a form of do construct. When
3355 do concurrent appears without a loop construct in a kernels construct it is treated as if it is
3356 annotated with loop auto. If it appears in a parallel construct or an accelerator routine then
3357 it is treated as if it is annotated with loop independent.
```

**Comment by clementval** [comment]
I think this does not apply for DO CONCURRENT with acc loop construct.

> When do concurrent appears without a loop construct

So it does not apply for the lowering for acc loop construct but we should handle it when DO CONCURRENT does not have a loop construct annotation.

**Comment by razvanlupusoru** [comment]
> I think this does not apply for DO CONCURRENT with acc loop construct.
> 
> > When do concurrent appears without a loop construct
> 
> So it does not apply for the lowering for acc loop construct but we should handle it when DO CONCURRENT does not have a loop construct annotation.

You're right - I totally skimmed over that.

**Review by razvanlupusoru — APPROVED** [review]
Excellent!

**Review by razvanlupusoru — APPROVED** [review]

**Pull request merged**
