### PR TITLE
[clang][dataflow] Fix inaccuracies in `buildStmtToBasicBlockMap()`.

### PR DESCRIPTION
**Pull request by martinboehme**
See the comments added to the code for details on the inaccuracies that have
now been fixed.

The patch adds tests that fail with the old implementation.

### CODE REVIEW

**Review by ymand — APPROVED** [review]
Nice work! Quite subtle...

**Review by Xazax-hun — APPROVED** [review]
This is horrifying. It makes me think that we might want to revamp the CfgBlock interface at some point.

**Comment by martinboehme** [comment]
CI failure looks unrelated. Patch locally builds and tests cleanly.

**Comment by martinboehme** [comment]
> This is horrifying. It makes me think that we might want to revamp the CfgBlock interface at some point.

Yes, there a quite a few surprises in the structure of the CFG that I've only discovered gradually over time. I'd also like to eliminate the sharp edges in the API, though I suspect that existing clients rely on the idiosyncrasies of the current API -- so we might have to introduce a second, parallel API for a while so we can migrate usage over gradually.

**Pull request merged**
