### PR TITLE
Remove llvm/MC/MCAsmLayout.h and the unused parameter in MCAssembler::layout

### PR DESCRIPTION
**Pull request by MaskRay**
This restores 63ec52f867ada8d841dd872acf3d0cb62e2a99e8 and
46f7929879a59ec72dc75679b4201e2d314efba9, NFC changes that were
unnecessarily reverted.

This completes the work that merges MCAsmLayout into MCAssembler.

### CODE REVIEW

**Review by maksfb — APPROVED** [review]
Thanks. RIP `MCAsmLayout`.

**Comment by dcci** [comment]
Thanks for putting this up for review. I appreciate you doing it, for this and future MC patches that could impact BOLT.

**Comment by MaskRay** [comment]
> Thanks. RIP MCAsmLayout.

Thanks for the review!


> dcci: Thanks for putting this up for review. I appreciate you doing it, for this and future MC patches that could impact BOLT.

Just to clarify, these changes are fairly straightforward and shouldn't impact any clients.
(The extra "assert" was indeed a mistake on my part, and I apologize for mentioning it repeatedly. What I feel bad is that you did not seem to be aware of the issues caused by your reverts... At least I do not see a good justification)

On a separate note, regarding reverts, I understand the desire to keep BOLT maintainers informed of MC changes. 
Perhaps there's a way to achieve this goal without potentially causing unintended breakage through reverts.

**Comment by dcci** [comment]
> Just to clarify, these changes are fairly straightforward and shouldn't impact any clients.

You can't really make this assumption. Maybe in this case it was true, but in the other case that I mention (relaxing frames eagerly, your assumption was incorrect and we had to adapt BOLT downstream to deal with the functional changes). This is why asking for review is a good practice regardless.

> Perhaps there's a way to achieve this goal without potentially causing unintended breakage through reverts.

I do believe code reviews are a good way to provide heads-up. Thanks for your work.

**Comment by rastogishubham** [comment]
I agree with @dcci I appreciate all the work, but I noticed 10 patches in MC that broke a bunch of stuff for fine-grained caching downstream in apple/llvm-project so the assumption that these changes are straightforward is incorrect.

**Pull request merged**
