### PR TITLE
[Flang][LLVM][OpenMP] Relax target data restrictions to be more inline with the specification

### PR DESCRIPTION
**Pull request by agozillon**
Currently we emit errors whenever a map is not provided on a target data directive, however, I believe that's incorrect behavior, the specification states:

"At least one map, use_device_addr or use_device_ptr clause must appear on the directive"

So provided one is present, the directive is legal in this case. Slightly different to its siblings (enter/exit/update) which don't have use_device_addr/use_device_ptr.

### CODE REVIEW

**Comment by agozillon** [comment]
@DominikAdamski found this and another target data related case while looking at the GenASiS benchmark, which I will try to address in a seperate PR in the near future

**Review by raghavendhra — APPROVED** [review]
LGTM!

**Review by skatrak — APPROVED** [review]
Good catch, LGTM as well!

**Review by DominikAdamski — APPROVED** [review]
LGTM

**Comment by agozillon** [comment]
Small follow up NFC commit to remove the extra space I added by accident (need to find some kind of space highlighting extension for vscode...)

**Pull request merged**
