### PR TITLE
[NFC] clean up memtag-stack code

### PR DESCRIPTION
**Pull request by fmayer**
we would replace the alloca with tagp for debug instructions, then replace it back with the original alloca. it's easier to just skip the replacement.

### CODE REVIEW

**Comment by fmayer** [comment]
Tested this with `-DLLVM_EXPERIMENTAL_DEBUGINFO_ITERATORS=On` to ensure the comment about DPValues is actually correct

**Comment by jmorse** [comment]
I can't comment on the general operation of memory tagging; however IMO you should use `Value::replaceNonMetadataUsesWith` instead of `Value::replaceUsesWithIf`. Metadata uses get deliberately hidden to avoid affecting codegen decisions, and don't appear on the normal use list, so the `isa<DbgVariableIntrinsic>` test will never be true. I think `replaceNonMetadataUsesWith` better expresses what you're aiming for and achieves the same thing.

**Review by jmorse — APPROVED** [review]
LGTM -- I'm not quite sure of the path taken whereby the debuginfo records point at the right alloca, but it's already covered by existing tests.

**Comment by fmayer** [comment]
> - I'm not quite sure of the path taken whereby the debuginfo records point at the right alloca, 

I don't fully understand, what exactly do you mean?

**Comment by jmorse** [comment]
> I don't fully understand, what exactly do you mean?

**Pull request merged**
