### PR TITLE
[flang][openacc] Generate data bounds for array addressing.

### PR DESCRIPTION
**Pull request by vzakhari**
In cases like `copy(array(N))` it is still useful to represent
the data operand uniformly with `copy(array(N:N))`.
This change generates data bounds even if it is not an array
section with the triplets. The lower and the upper bounds
are the same and the extent is one in this case.
I did not enable this for OpenMP by default, because I am not sure
if this is what the OpenMP devs want (though, I hope we can use the same).

### CODE REVIEW

**Comment by agozillon** [comment]
I think it should be fine to toggle this on for OpenMP, I agree using the same method for both dialects would be ideal. Although I have not tested this particular case, I imagine we'd still want the bounds as well. 

However, could we maintain the on/off toggle (switched on for OpenMP/OpenACC, so perhaps flip the default to true) until this particular use-case has been tested in OpenMP a little down the line from now? If that's unreasonable that's fine, we can likely re-introduce the toggle on the small chance it's an issue in OpenMP!

**Review by clementval — APPROVED** [review]

**Review by razvanlupusoru — APPROVED** [review]
Thank you!

**Comment by vzakhari** [comment]
> However, could we maintain the on/off toggle (switched on for OpenMP/OpenACC, so perhaps flip the default to true) until this particular use-case has been tested in OpenMP a little down the line from now? If that's unreasonable that's fine, we can likely re-introduce the toggle on the small chance it's an issue in OpenMP!

Thanks! I added a switch for OpenMP only.

**Review by agozillon — APPROVED** [review]
I was more meaning I think we could just pass true for now in OpenMP similarly to the way it's done in OpenACC and we could just pass false in OpenMP if we ever run into an issue at some point in the future (sorry for not being clear)! 

However, this works too if you're happy with it, thank you very much for your work.

**Pull request merged**
