### PR TITLE
[AMDGPU] Remove FlatVariant argument from isLegalFlatAddressingMode. NFC.

### PR DESCRIPTION
**Pull request by rampitec**
This argument is easily deduced from AS argument.

### CODE REVIEW

**Review by arsenm — COMMENTED** [review]
It's not a 1:1 mapping though, you can select global addresses to flat instructions (which the patterns do handle)

**Comment by rampitec** [comment]
> It's not a 1:1 mapping though, you can select global addresses to flat instructions (which the patterns do handle)

But every single use is 1:1.

**Review by arsenm — APPROVED** [review]
This isn't used for the selection anyway

**Comment by rampitec** [comment]
JBTW, I also believe in many cases we are using 'auto' we really mean 'decltype(something)'. I.e. whatever underlying type is. Maybe we should use it more often and less often use 'auto'.

**Pull request merged**
