### PR TITLE
[AMDGPU] Add missing GFX10 buffer format d16 hi instructions

### PR DESCRIPTION
**Pull request by jayfoad**

### CODE REVIEW

**Review by Sisyph — COMMENTED** [review]
Why were these initially disabled? The origin commit review is not informative. Can you please add a codegen test to make sure they work?

**Comment by jayfoad** [comment]
> Why were these initially disabled?

I don't know. I wasn't involved. @rampitec do you remember?

> Can you please add a codegen test to make sure they work?

I am not expecting codegen to use these instructions (without some extra work) but I can check.

**Comment by jayfoad** [comment]
> > Can you please add a codegen test to make sure they work?
> 
> I am not expecting codegen to use these instructions (without some extra work) but I can check.

These instructions have existed since GFX9. As far as I can tell we have never implemented codegen for them.

**Comment by rampitec** [comment]
> > Why were these initially disabled?
> 
> I don't know. I wasn't involved. @rampitec do you remember?

I do not remember now either.

**Review by rampitec — APPROVED** [review]

**Review by Sisyph — APPROVED** [review]
This is fine to fix the Asm/Disasm then.

**Pull request merged**
