### PR TITLE
[clang-cl] Map /Ot to -O3 instead of -O2

### PR DESCRIPTION
**Pull request by zmodem**
/Ot (which is also implied by /O2) is supposed to optimize for maximum speed, so -O3 seems like a better match.

### CODE REVIEW

**Comment by zmodem** [comment]
@AaronBallman as discussed on https://discourse.llvm.org/t/clang-cl-optimization-option/79554

Also @nico who IIRC looked at these flags in recent times.

**Comment by nico** [comment]
Can you add something like "use /O2 /clang:-O2 to restore the previous behavior" to the commit message, on case someone prefers that?

Otherwise LG.

**Comment by nico** [comment]
Oh, you have that in the release notes already, even better.

**Review by nico — APPROVED** [review]

**Comment by efriedma-quic** [comment]
If we're trying to match MSVC, the amount of inlining MSVC does at /O2 is probably closer to what clang does at -O2 than -O3.  Which is why it was mapped that way in 015ce0f68f791b3abec4225c1b2e532ce5020174, I think.  clang's -O3 is really aggressive (which tends to look good in benchmarks, but less so in real software).

I'm a bit worried we're going to get a wave of complaints about codesize in reaction to this.

**Comment by efriedma-quic** [comment]
For reference, current MSVC has a flag /Ob3 to request more aggressive inlining.

**Pull request merged**
