### PR TITLE
Unwrap CountAttributed for debug info

### PR DESCRIPTION
**Pull request by rapidsna**
Fix crash caused by 3eb9ff30959a670559bcba03d149d4c51bf7c9c9

### CODE REVIEW

**Comment by rapidsna** [comment]
Fix crash in https://github.com/llvm/llvm-project/pull/78000

**Review by delcypher — APPROVED** [review]
LGTM. Thanks for the quick fix.

**Comment by nathanchance** [comment]
Thanks, this resolves my reported issue!

**Comment by ms178** [comment]
This patch also resolves my reported issue over at ClangBuiltLinux for compiling the Linux Kernel on a recent LLVM/Clang snapshot.

**Pull request merged**
