### PR TITLE
[Coverage] Handle array decomposition correctly

### PR DESCRIPTION
**Pull request by bolshakov-a**
`ArrayInitLoopExpr` AST node has two occurences of its as-written initializing expression in its subexpressions through a non-unique `OpaqueValueExpr`. It causes double-visiting of the initializing expression if not handled explicitly, as [discussed](https://github.com/llvm/llvm-project/pull/85837#discussion_r1559664574) in #85837.

@efriedma-quic

### CODE REVIEW

**Comment by bolshakov-a** [comment]
Honestly, I'm not very familiar with code coverage technique, but it seems to me that only explicitly written code is relevant for that. "Common expression" is exactly the explicitly written part. "Subexpression" is an implicitly generated per-element initializer which refers to the "common expression" (hence, without this patch, the counters for the conditional operator from the test are duplicated despite it is executed only once per function call). Which observable drawbacks do you expect from not visiting the implicit parts of the initializer?

**Comment by efriedma-quic** [comment]
Say you have:

```
int foo();
struct A { A(); A(const A&, int = foo()); };
struct B { A a[10]; };
void f(const B& b) { B bb = b; }
```

We want to visit the call to foo(), I think?

**Comment by bolshakov-a** [comment]
I don't see any difference on your example (with `main()` and function definitions added) with and without my patch neither in the dumped coverage mapping nor in the output of `llvm-cov show ... --show-branches=count --show-expansions -show-line-counts-or-regions` command. If the coverage mapping works with code regions, it looks quite natural that an implicit code (`foo()` call inside `f()` in the sample) has no corresponding region and hence no mapping (except macro expansions).

Maybe, @hyp can clarify?

**Comment by efriedma-quic** [comment]
I'm not deeply familiar with how the code decides when and when not to insert counters... the point was just that just because it's "implicit", it doesn't mean there aren't any interesting expressions. 

But anyway, I think we end up doing the right thing automatically if you ignore non-unique OpaqueValueExprs.

**Comment by bolshakov-a** [comment]
> But anyway, I think we end up doing the right thing automatically if you ignore non-unique OpaqueValueExprs.

The problem is that there is no initializing "common expression" in the AST besides non-unique `OpaqueValueExpr`, hence some code handling `ArrayInitLoopExpr` should be written so as not to lose it at all.

@chapuni, @gulfemsavrun, @evodius96, @vedantk, please clarify: should or should not the implicit stuff be traversed here, particularly for array element initialization?

**Comment by bolshakov-a** [comment]
@efriedma-quic, would it be OK to add "subexpression" visitation with a comment that I'm not sure that it is actually needed?

**Comment by bolshakov-a** [comment]
@efriedma-quic ping. CC @AaronBallman

**Comment by bolshakov-a** [comment]
This looks like supporting my words:
https://github.com/llvm/llvm-project/blob/llvmorg-19-init/clang/lib/CodeGen/CodeGenPGO.cpp#L935-L936

**Review by efriedma-quic — APPROVED** [review]
LGTM.

I'm not completely convinced by your argument here... but let's try to move forward and land this and #88898 so we can do the refactor to use isUnique().  Then we can revisit later if necessary.

**Comment by bolshakov-a** [comment]
Could you please merge both of these?

**Comment by bolshakov-a** [comment]
Thanks!

**Pull request merged**
