### PR TITLE
Fix duplicate mapping detection in gpu::setMappingAttr()

### PR DESCRIPTION
**Pull request by RoboTux**

### CODE REVIEW

**Comment by joker-eph** [comment]
Can this be tested with lit testing?

**Comment by RoboTux** [comment]
> Can this be tested with lit testing?

No, the only caller for that function will never pass a mapping with twice the same processor attribute.

**Comment by RoboTux** [comment]
Ping?

**Comment by joker-eph** [comment]
I still have concerns about the testing: this diverges from how we test this kind of things in the project.

**Comment by RoboTux** [comment]
> I still have concerns about the testing: this diverges from how we test this kind of things in the project.
Should I remove the test then? As I said, the only caller to the function being fixed never triggers the wrong codepath so it can only be exercise by adding a new caller (which is what happens when adding the new unit test).

**Comment by joker-eph** [comment]
Maybe best to skip the unit-tests here.

**Review by joker-eph — APPROVED** [review]

**Pull request merged**
