### PR TITLE
Revert "[RISCV] Add cost model tests for llvm.vector.{insert,extract}…

### PR DESCRIPTION
**Pull request by Prabhuk**
…. NFC"

This reverts commit fc0b67e1d79d1f199687f8f06d619984d9520230. The tests added fail on Linux CI builder. More details here: https://github.com/llvm/llvm-project/commit/fc0b67e1d79d1f199687f8f06d619984d9520230#commitcomment-138688832

### CODE REVIEW

**Comment by topperc** [comment]
The tests fail because of https://github.com/llvm/llvm-project/pull/81751

**Comment by topperc** [comment]
I spoke with @reames. I'm going to revert his patch instead.

**Review by topperc — CHANGES_REQUESTED** [review]
I"m going to revert a different patch instead.

**Comment by Prabhuk** [comment]
Thank you! I'll abandon this revert PR

**Comment by preames** [comment]
Just to close the loop here, sorry for the breakage.  The error was definitely mine, I didn't rebase after the new tests were added.  Thank you to @topperc for reverting my change.

**Pull request closed without merging**
