### PR TITLE
[RISCV] Remove experimental from Zabha

### PR DESCRIPTION
**Pull request by AlexGhiti**
The Zabha extension was ratified in April 2024.

### CODE REVIEW

**Review by topperc — APPROVED** [review]
LGTM

**Comment by topperc** [comment]
Looks like you need to update the RISCVISAInfoTest.cpp to move the extension form the experimental list to the non-experimental list

**Comment by AlexGhiti** [comment]
Damn, I missed it, good catch, thanks.

**Review by topperc — APPROVED** [review]
LGTM

**Comment by topperc** [comment]
I'm guessing you don't have commit access?

**Comment by AlexGhiti** [comment]
> I'm guessing you don't have commit access?

I don't think so indeed (?).

Thanks for your quick review,

Alex

**Pull request merged**
