### PR TITLE
Reland "[X86] Remove knl/knm specific ISAs supports (#92883)"

### PR DESCRIPTION
**Pull request by FreddyLeaf**
This reverts commit aa4069ea96e5eb62bc8c7895b9d920f129611b3a.

### CODE REVIEW

**Comment by FreddyLeaf** [comment]
any idea on why `Labelling new pull requests / greeter (pull_request_target)` is **skipped**? @phoebewang @RKSimon

**Comment by RKSimon** [comment]
Not sure - CI checks aren't running either

**Comment by FreddyLeaf** [comment]
> Not sure - CI checks aren't running either

Woops, I was thinking that is CI checks. I was just wondering for CI checks. Now it's recovered. Thanks anyway!

**Review by phoebewang — APPROVED** [review]
LGTM.

**Pull request merged**
