### PR TITLE
AMDGPU: Add testcase for materializing sgpr frame indexes

### PR DESCRIPTION
**Pull request by arsenm**
These add some IR tests for 57d10b4fc9142d12fbdec578a0cc6f78deb67ef4.
These do rely on some lucky MIR placement to test the scc input, but I
haven't found a better way to do it. Also, scc handling in inline asm
is extremely buggy.

### CODE REVIEW

**Comment by arsenm** [comment]
* **#101306** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/101306?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @arsenm and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Review by PankajDwivedi-25 — APPROVED** [review]

**Comment by cdevadas** [comment]
These tests written with inline asm constraints are extremely difficult to maintain in terms of retaining the original test scenario. At some point in the future, we are forced to modify them to avoid extreme register pressure (for instance patches like wwm-regalloc) or to make them compilable resulting in losing the purpose of the original test. Because these forced scenarios might disappear and thereafter, these handpicked volatile tests become irrelevant.

**Comment by cdevadas** [comment]
> > These tests written with inline asm constraints are extremely difficult to maintain in terms of retaining the original test scenario. At some point in the future, we are forced to modify them to avoid extreme register pressure (for instance patches like wwm-regalloc) or to make them compilable resulting in losing the purpose of the original test.
> 
> Possibly, but not having tests is worse than having tests that need maintenance
> 
Why do you say not having tests? We still have the mir test. But yes, it is good to have an IR test to validate the entire pipeline.

**Comment by arsenm** [comment]
> Why do you say not having tests? We still have the mir test. But yes, it is good to have an IR test to validate the entire pipeline.

Overall MIR is quite difficult to maintain, and easy to miss testing the real scenarios that appear.

We need end to end IR tests to validate the whole pipeline works, and to meaningfully check the final output for code quality. For example, I found at least 3 bugs in the patch by adding the IR versions of the tests. Plus I've noticed other missed optimizations

**Pull request merged**
