### PR TITLE
[Clang] [c++20] P1907R1: Support for generalized non-type template ar…

### PR DESCRIPTION
**Pull request by cor3ntin**
…guments of scalar type

Initially https://reviews.llvm.org/D140996

Author: @bolshakov-a

I do not plan to work on this, but I'm trying to salvage what I can from phabricator. This review, is completely gone. I extracted it from my mails. So this PR is purely to make sure we have a trace.

### CODE REVIEW

**Comment by bolshakov-a** [comment]
Have I understood correctly that I should open my own PR to proceed working on this?

**Comment by cor3ntin** [comment]
Sure! I will close this one.
I wasn't sure you were around and honestly a bit concerned about all the
work that is going to be lost on phabricator.

**Comment by bolshakov-a** [comment]
Seems like I should ping reviewers more actively... Ok, thanks, I'll probably proceed at the weekend.

**Comment by cor3ntin** [comment]
@bolshakov-a we are going to branch LLVM 23 in about 10 days. If you can update this by early next week, we will try to finish the review so that it can land in 18.

**Comment by bolshakov-a** [comment]
@cor3ntin, #78041.

**Comment by cor3ntin** [comment]
Author opened #78041 - closing

**Pull request closed without merging**
