### PR TITLE
Fix calls to PrintedDeclCXX98Matches.

### PR DESCRIPTION
**Pull request by zahiraam**
Fix the calls to `PrintedDeclCXX98Matches` to take the lambda function as the last argument.

### CODE REVIEW

**Comment by zahiraam** [comment]
Tagging @amy-kwan and @kazutakahirata . Hopefully this will fix the issue.

**Review by kazutakahirata — APPROVED** [review]
LGTM.  Thanks!

**Comment by kazutakahirata** [comment]
Would you mind merging this PR into the LLVM source tree if nothing is blocking you?

If something is blocking you, I am happy to revert your original patch on your behalf (along with the `(void)` fix).

**Comment by zahiraam** [comment]
> Would you mind merging this PR into the LLVM source tree if nothing is blocking you?
> 
> If something is blocking you, I am happy to revert your original patch on your behalf (along with the `(void)` fix).

I thought the issue was fixed with the (void) addition! If not, I will merge this PR immediately.

**Comment by kazutakahirata** [comment]
> I thought the issue was fixed with the (void) addition! If not, I will merge this PR immediately.

Sorry, I misunderstood.  The `void` fix (https://github.com/llvm/llvm-project/commit/577e0ef94fb0b4ba9f97a6f58a1961f7ba247d21) fixes the build error.

Meanwhile, I am guessing that you have added lambda functions to control the behavior of `PrintedDeclCXX98Matches`.  If that's the case, you should merge this PR.  But then again, there is no urgency as the build has been restored.

**Comment by zahiraam** [comment]
> > I thought the issue was fixed with the (void) addition! If not, I will merge this PR immediately.
> 
> Sorry, I misunderstood. The `void` fix ([577e0ef](https://github.com/llvm/llvm-project/commit/577e0ef94fb0b4ba9f97a6f58a1961f7ba247d21)) fixes the build error.
> 
> Meanwhile, I am guessing that you have added lambda functions to control the behavior of `PrintedDeclCXX98Matches`. If that's the case, you should merge this PR. But then again, there is no urgency as the build has been restored.

OK. I have edited the description since this is not for fixing the build as much as fixing the call `PrintedDeclCXX98Matches`.

**Comment by zahiraam** [comment]
> > > I thought the issue was fixed with the (void) addition! If not, I will merge this PR immediately.
> > 
> > 
> > Sorry, I misunderstood. The `void` fix ([577e0ef](https://github.com/llvm/llvm-project/commit/577e0ef94fb0b4ba9f97a6f58a1961f7ba247d21)) fixes the build error.
> > Meanwhile, I am guessing that you have added lambda functions to control the behavior of `PrintedDeclCXX98Matches`. If that's the case, you should merge this PR. But then again, there is no urgency as the build has been restored.
> 
> OK. I have edited the description since this is not for fixing the build as much as fixing the call `PrintedDeclCXX98Matches`.

Now I wonder if the fix should be with the (void) or without. Have you tried it locally to see if you get the same build error?

**Comment by zahiraam** [comment]
> > Now I wonder if the fix should be with the (void) or without. Have you tried it locally to see if you get the same build error?
> 
> Yes, I just tried your patch and confirmed that the unit test passes without a problem.
> 
> No, you shouldn't keep `(void)` there. It's there just to silence the warning because the lambda is sitting unused outside the call to `PrintedDeclCXX98Matches`. Once you bring the lambda inside the call to `PrintedDeclCXX98Matches`, the lambda is used, so you shouldn't get a warning.

Perfect! As soon as the testing completes I will merge it in. Thanks.

**Pull request merged**
