### PR TITLE
[clang][analyzer] Add more notes to PointerSubChecker

### PR DESCRIPTION
**Pull request by balazske**
Notes appear at out-of-range array index for index value and array size.

### CODE REVIEW

**Review by NagyDonat — APPROVED** [review]
The change LGTM, it makes these reports somewhat easier to understand.

However, note that I'll delete all array bounds checking logic from this checker when I'll bring `alpha.security.ArrayBoundV2` out of alpha, because there is no reason to have several checkers that are looking for the same error type. (Also note that the logic in `ArrayBoundV2` is more sophisticated and general than the logic of this checker.)

This means that you shouldn't work on improving this part of this checker, because your efforts will be wasted when this is removed.

(EDIT: the checker is named ArrayBoundV2, while I originally accidentally wrote ArrayBound**s**V2.)

**Comment by balazske** [comment]
If the `ArrayBoundsV2` checker is finished it should find all of the cases in the test of `PointerSubChecker` that have out-of-bound indexing, and including the cases where a single variable is handled like an 1-element array? If yes the bounds check is not needed in this checker, only the check for different memory object. I like it better if the bounds check is then removed before the PointerSub checker goes out of alpha (this means now). If the bounds check is removed this checker will not report the cases where invalid indexing occurs because that is a different error.

**Comment by NagyDonat** [comment]
> If the `ArrayBoundsV2` checker is finished it should find all of the cases in the test of `PointerSubChecker` that have out-of-bound indexing, and including the cases where a single variable is handled like an 1-element array?

Yes, `ArrayBoundV2` will handle the cases where a single variable is handled like an 1-element array.

> If yes the bounds check is not needed in this checker, only the check for different memory object. I like it better if the bounds check is then removed before the PointerSub checker goes out of alpha (this means now). If the bounds check is removed this checker will not report the cases where invalid indexing occurs because that is a different error.

Yes, I can agree with that, checking out of bounds indexing does not belong to this checker. Feel free to create a different commit which removes this feature instead of tweaking its messages.

**Comment by balazske** [comment]
I uploaded now #102580 that removes the entire array bounds checking.

**Review by NagyDonat — CHANGES_REQUESTED** [review]
Thanks!

We should close this when that other PR is accepted and merged. Until then I'm putting a "Request changes" mark on this to prevent an accidental merge.

**Pull request closed without merging**
