### PR TITLE
[clang][CodeGen] Use byval for SystemZ indirect arguments

### PR DESCRIPTION
**Pull request by iii-i**
SystemZ ABI mandates that in order to pass large objects by value, one should be place them on stack and pass the callee a pointer. Currently on LLVM IR level it's impossible to distinguish whether a pointer argument was there in the C code, or whether it was introduced in order to satisfy the ABI requirement.

MSan and DFSan need to know that in order to correctly fill the arguments' shadow TLS. Fix by adding ByVal attributes to synthetic pointer arguments. This attribute serves exactly this purpose.

This resolves an outstanding MSan issue, and enables the future DFSan support.

### CODE REVIEW

**Comment by uweigand** [comment]
This looks correct to me.  I'm just wondering if there's any unexpected change of generated code due to this - did you do a comparison before/after of some larger code bases?

**Comment by efriedma-quic** [comment]
byval changes the calling convention: instead of passing a pointer, it copies the pointed-to value into the argument list.

It's not clear to me why msan cares about whether a pointer is an implicit or explicit value... but if it does, we'd want to use an attribute that doesn't have an existing ABI impact.

**Comment by iii-i** [comment]
I just checked with a few small examples, and while the ABI does not seem to change, the code generation looks broken for tail recursion:

```
$ cat 1.c
void baz(long double);
void quux(void) { baz((long double)1); }

$ ./bin/clang -O3 -S 1.c

$ cat 1.s
[...]
        aghi    %r15, -176      # stack frame
        larl    %r1, .LCPI0_0   # address of (long double)1 in the literal pool
        lxeb    %f0, 0(%r1)     # f0:f2=(long double)1
        la      %r2, 160(%r15)  # r2=&var_160
        std     %f0, 160(%r15)  # var_160=(long double)1
        std     %f2, 168(%r15)
        aghi    %r15, 176       # var_160 is above the stack pointer now!
        jg      baz@PLT         # baz(&var_160)
[...]
```

Regarding MSan/DFSan, they need to know whether to copy value's or pointer's shadow into arguments' TLS. MSan already has checks for that (`CB.paramHasAttr(ArgNo, Attribute::ByVal)`), and for DFSan I've added them in my local branch.

**Comment by efriedma-quic** [comment]
> I just checked with a few small examples, and while the ABI does not seem to change, the code generation looks broken for tail recursion:

I'd guess the SystemZ backend doesn't implement byval properly (since it's not required for the C calling convention, probably nobody would notice any issues).

> Regarding MSan/DFSan, they need to know whether to copy value's or pointer's shadow into arguments' TLS

I don't see why you'd need to distinguish between two cases that generate identical IR, unless you think the additional information can somehow lead to more accurate diagnostics.  Other targets emit struct arguments in a similar way without any special handling in msan.

**Comment by iii-i** [comment]
There is special byval handling in MSan:

```
  void visitCallBase(CallBase &CB, IRBuilder<> &IRB) override {
...
    for (const auto &[ArgNo, A] : llvm::enumerate(CB.args())) {
...
      bool IsByVal = CB.paramHasAttr(ArgNo, Attribute::ByVal);
```

If a target does not make use of byval, I would argue that this part of MSan is broken there.
Unfortunately this applies to SystemZ at the moment: `param_tls_limit.cpp` is marked as XFAIL because of this (the rationale that is written there, which says that the test is not applicable, is not correct).

A quick experiment shows that x86_64 uses byval:

```
$ uname -m
x86_64

$ clang --version
clang version 16.0.6 (Fedora 16.0.6-2.fc38)

$ cat 1.c
struct foo { char x[800]; };
void bar(struct foo) {};

$ clang -mllvm -print-after-all -c 1.c
[...]
define dso_local void @bar(ptr noundef byval(%struct.foo) align 8 %0) #0 {
[...]
```

As for the reasons why this all is the case, I think this is because of how arguments' shadow TLS is defined: it contains shadows of all argument values, where arguments are understood in terms of C, and not in terms of the ABI. This definition is then used in the runtime. See, for example, the handling of long doubles in `dfsan_custom.cpp`:

```
static int format_buffer(char *str, size_t size, const char *fmt,
                         dfsan_label *va_labels, dfsan_label *ret_label,
                         dfsan_origin *va_origins, dfsan_origin *ret_origin,
                         va_list ap) {
[...]
        case 'G':
          if (*(formatter.fmt_cur - 1) == 'L') {
            retval = formatter.format(va_arg(ap, long double));
          } else {
            retval = formatter.format(va_arg(ap, double));
          }
          if (va_origins == nullptr)
            dfsan_set_label(*va_labels++, formatter.str_cur(),
                            formatter.num_written_bytes(retval));
          else
            dfsan_set_label_origin(*va_labels++, *va_origins++,
                                   formatter.str_cur(),
                                   formatter.num_written_bytes(retval));
          end_fmt = true;
          break;
```

Here is wants the shadow of the long double itself, even if the target ABI requires passing it through a pointer.

**Comment by efriedma-quic** [comment]
There's a special case in the msan handling precisely because byval makes the ABI different.  (If you look at the x86 code, you'll see that the generated code with byval is significantly different.)

I don't think I know enough about dfsan to follow that argument.

**Comment by efriedma-quic** [comment]
In any case:

- We absolutely can't use byval here.
- If you think we need a new attribute for this, please start a Discourse thread to get some feedback.  (I'm still not understanding what you're trying to fix here, but maybe additional perspectives would help bridge the gap.)

**Comment by iii-i** [comment]
I don't quite get why can't we use byval here. How is this different from x86_64? Both s390x and x86_64 ABIs require passing large structs via a pointer, why can x86_64 implement this using byval in LLVM and s390x can't? I agree that currently s390x backend does not handle it properly and the current version of this PR is not suitable for inclusion, but what is the conceptual problem here?

**Comment by efriedma-quic** [comment]
> Both s390x and x86_64 ABIs require passing large structs via a pointer

Wrong.  x86_64 passes structs by value (copying the data into the argument list).  It just looks like a pointer in the IR because LLVM can't really handle large values in registers.

---

The semantics of byval are "the call instruction allocates memory, and copies the argument into that memory".  That generally means copying the memory into the argument list, although LangRef doesn't actually mandate that.

If byval were actually implemented correctly for SystemZ, adding would completely change the generated code in a way that's not actually compatible with the SystemZ C ABI.

**Comment by iii-i** [comment]
Sorry, I my wording was not precise enough, it is indeed important that we create a copy, and not pass a pointer to the original. Still, what you described matches the s390x ABI:

```
1.2.2.3. Parameter Area

The parameter area shall be allocated by a calling function if some parameters cannot
be passed in registers, but must be passed on the stack instead (see section 1.2.3).

[...]

1.2.3. Parameter Passing

[...]
A struct or union of any other size, a complex type, an __int128, a long
double, a _Decimal128, or a vector whose size exceeds 16 bytes. Replace
such an argument by a pointer to the object, or to a copy where necessary
to enforce call-by-value semantics. Only if the caller can ascertain that the
object is “constant” can it pass a pointer to the object itself.
```

---

Ah, that's the source of my confusion. I didn't realize the call instruction had to make a copy, I thought it just had to be done somewhere. "The attribute implies that a hidden copy of the pointee is made between the caller and the callee" actually does mean the former, but one has to squint to see that. The way you phrased it is much clearer.

So in the following example:

```
struct foo { char x[800]; };
void bar(struct foo);
void baz(void) { struct foo f = {}; bar(f); };
```

x84_64 generates:

```
define dso_local void @baz() #0 {
  %1 = alloca %struct.foo, align 8
  call void @llvm.memset.p0.i64(ptr align 1 %1, i8 0, i64 800, i1 false)
  call void @bar(ptr noundef byval(%struct.foo) align 8 %1)
  ret void
}
```

and relies on the backend to expand `call void @bar` into roughly `REP_MOVSQ_64` and `CALL64pcrel32`. Whereas on s390x we get:

```
define dso_local void @baz() #0 {
  %1 = alloca %struct.foo, align 1
  %2 = alloca %struct.foo, align 1
  call void @llvm.memset.p0.i64(ptr align 1 %1, i8 0, i64 800, i1 false)
  call void @llvm.memcpy.p0.p0.i64(ptr align 1 %2, ptr align 1 %1, i64 800, i1 false)
  call void @bar(ptr noundef %2)
  ret void
}
```

so the creation of the copy is explicit in the LLVM IR. Even though the ABIs are saying roughly the same thing, it's implemented differently.

I wonder if it would still be beneficial to switch s390x to byval? I think it can be done in a way that correctly implements the ABI, even though it would of course be more complex than this PR. An obvious benefit is that s390x would become more similar to x86_64, but maybe there are some drawbacks that I'm not seeing.

---

I revisited MSan's `param_tls_limit.cpp`, and the XFAIL is actually fine. The instrumentation does indeed put the shadow of the synthetic pointer into the parameters' TLS area on s390x, but this is not a problem, since the shadow of the actual value is still preserved and checked. This prevents the overflow, which the test expects, from happening, so the conclusion that the test is not applicable is correct. Sorry for the noise.

I will check if there is a different solution for DFSan. It currently passes the label of the pointer to the copy, which is always 0, instead of the label of the actual value, to vararg functions on s390x. Even though this is similar to what MSan does, the difference is that the DFSan runtime (e.g., `format_buffer`) expects the label of the actual value, regardless of the ABI.

**Comment by efriedma-quic** [comment]
byval generally results in worse code. It has two problems:

- The copy is invisible.  Having the copy explicitly visible means we can optimize the code involved in the copy (sometimes we can eliminate it, or parts of it).
- Gluing the allocation to the call means stack layout is less flexible: the memory has to be allocated at a specific location on the stack.

x86-64 uses it because it was the simplest way to implement the ABI requirements; llvm.call.preallocated.setup theoretically solves the same problem, but it's a lot more complicated.

**Pull request closed without merging**
