### PR TITLE
Revert "[IR] Don't include Module.h in Analysis.h (NFC) (#97023)"

### PR DESCRIPTION
**Pull request by ZijunZhaoCCK**
This reverts commit 4169338e75cdce73d34063532db598c95ee82ae4.

This causes incomplete type errors.

```/[tmpfs/src/git/out/llvm-project/llvm/lib/Target/WebAssembly/WebAssemblyISelLowering.cpp:1022](https://cs.corp.google.com/piper///depot/google3/tmpfs/src/git/out/llvm-project/llvm/lib/Target/WebAssembly/WebAssemblyISelLowering.cpp?l=1022):18: error: member access into incomplete type 'Module'
 1022 |   Function *F = M->getFunction(Name);
      |                  ^
/[tmpfs/src/git/out/llvm-project/llvm/include/llvm/IR/Value.h:47](https://cs.corp.google.com/piper///depot/google3/tmpfs/src/git/out/llvm-project/llvm/include/llvm/IR/Value.h?l=47):7: note: forward declaration of 'llvm::Module'
   47 | class Module;
      |       ^
/[tmpfs/src/git/out/llvm-project/llvm/lib/Target/WebAssembly/WebAssemblyISelLowering.cpp:1026](https://cs.corp.google.com/piper///depot/google3/tmpfs/src/git/out/llvm-project/llvm/lib/Target/WebAssembly/WebAssemblyISelLowering.cpp?l=1026):48: error: member access into incomplete type 'Module'
 1026 |   PointerType *ResTy = PointerType::getUnqual(M->getContext());
      |                                                ^
/[tmpfs/src/git/out/llvm-project/llvm/include/llvm/IR/Value.h:47](https://cs.corp.google.com/piper///depot/google3/tmpfs/src/git/out/llvm-project/llvm/include/llvm/IR/Value.h?l=47):7: note: forward declaration of 'llvm::Module'
   47 | class Module;
      |       ^
/[tmpfs/src/git/out/llvm-project/llvm/lib/Target/WebAssembly/WebAssemblyISelLowering.cpp:1029](https://cs.corp.google.com/piper///depot/google3/tmpfs/src/git/out/llvm-project/llvm/lib/Target/WebAssembly/WebAssemblyISelLowering.cpp?l=1029):24: error: member access into incomplete type 'Module'
 1029 |   llvm::AttrBuilder B(M->getContext());
      |                        ^
/[tmpfs/src/git/out/llvm-project/llvm/include/llvm/IR/Value.h:47](https://cs.corp.google.com/piper///depot/google3/tmpfs/src/git/out/llvm-project/llvm/include/llvm/IR/Value.h?l=47):7: note: forward declaration of 'llvm::Module'
   47 | class Module;```

### CODE REVIEW

**Comment by boomanaiden154** [comment]
In what configuration are you seeing these errors?

I believe most of the issues got resolved by this morning (PST) for the buildbots.

**Comment by hiraditya** [comment]
Please share the cmake config and build command for repro.

**Review by nikic — CHANGES_REQUESTED** [review]
This is probably caused by some downstream patches in google3? https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/WebAssembly/WebAssemblyISelLowering.cpp does not contain any mentions of `M->getFunction` or `M->getContext`. You need to add the missing include to your downstream patches.

**Comment by kongy** [comment]
> This is probably caused by some downstream patches in google3? https://github.com/llvm/llvm-project/blob/main/llvm/lib/Target/WebAssembly/WebAssemblyISelLowering.cpp does not contain any mentions of `M->getFunction` or `M->getContext`. You need to add the missing include to your downstream patches.

Yes, The problem is from our Android downstream patch, Support-for-WASM-as-native-IR.patch.

https://android.googlesource.com/toolchain/llvm_android/+/refs/heads/main/patches/Support-for-WASM-as-native-IR.patch#121

**Pull request closed without merging**
