### PR TITLE
[AMDGPU] fix the check of inst-order in a test

### PR DESCRIPTION
**Pull request by cmc-rep**
test was not well written to consider potential all-correct instruction ordering

### CODE REVIEW

**Comment by jayfoad** [comment]
All these checks have been autogenerated (see comment line 1 of the test) so you really should not edit them by hand. If you do, your edits will get lost the next time some re-auto-generates the checks.

**Comment by cmc-rep** [comment]
> All these checks have been autogenerated (see comment line 1 of the test) so you really should not edit them by hand. If you do, your edits will get lost the next time some re-auto-generates the checks.

@jayfoad I didn't notice that. This is tricky. However, it feels like that there is no real good way to reduce merge difficulty in this case? I should close this PR?

**Comment by cmc-rep** [comment]
Not the right way

**Comment by jayfoad** [comment]
> However, it feels like that there is no real good way to reduce merge difficulty in this case?

Can you understand _why_ your downstream changes cause churn in these tests? Maybe there is some underlying problem that could be fixed?

> I should close this PR?

Yes :)

**Pull request closed without merging**
