### PR TITLE
release/19.x: [clang][modules] Enable built-in modules for the upcoming Apple releases (#102239)

### PR DESCRIPTION
**Pull request by ian-twilightcoder**
Backport 961639962251de7428c3fe93fa17cfa6ab3c561a and 0f1361baf650641a59aaa1710d7a0b7b02f2e56d

Requested by: @ian-twilightcoder

### CODE REVIEW

**Review by cyndyishida — APPROVED** [review]
Thanks for applying the code cleanup!

**Review by chapuni — APPROVED** [review]
I wonder we couldn't amend #102335! Thanks!

**Comment by ian-twilightcoder** [comment]
> I wonder we couldn't amend #102335! Thanks!

I couldn't figure out how to add cherry picks onto that PR. I tried another `cherry-pick` in the original PR but the bot just complained. Maybe I could do a single `cherry-pick` command with both commits and that would work? Would that be better than this PR?

**Comment by ian-twilightcoder** [comment]
> > I wonder we couldn't amend #102335! Thanks!
> 
> I couldn't figure out how to add cherry picks onto that PR. I tried another `cherry-pick` in the original PR but the bot just complained. Maybe I could do a single `cherry-pick` command with both commits and that would work? Would that be better than this PR?

Ah ha, it worked! Ok let's use #102335

**Pull request closed without merging**
