### PR TITLE
Rename -macosx_version_min to -macos_version_min

### PR DESCRIPTION
**Pull request by lelandjansen**
`-macosx_version_min` has been renamed to `-macos_version_min`.

### CODE REVIEW

**Comment by jryans** [comment]
Perhaps good to edit the PR title, it mentions the same flag twice at the moment.

**Comment by lelandjansen** [comment]
> Perhaps good to edit the PR title, it mentions the same flag twice at the moment.

Good catch. Thank you.

**Comment by lelandjansen** [comment]
Ping

**Comment by lelandjansen** [comment]
@jryans Would you be able to approve this PR?

**Review by jryans — COMMENTED** [review]
AIUI, this is straightforward case of updating tools to use new option names. I suppose there is a chance it triggers failures in e.g. older linkers that don't support the newer names, but I assume on Apple platforms there's less risk of that anyway.

Do you happen to know when the new name was first added to the linker?

**Review by JDevlieghere — CHANGES_REQUESTED** [review]
We should be using `-platform-version` for newer versions of the linker. 

```
  if (Version >= VersionTuple(520) || LinkerIsLLD || UsePlatformVersion)
    MachOTC.addPlatformVersionArgs(Args, CmdArgs);
  else
    MachOTC.addMinVersionArgs(Args, CmdArgs);
```

How are we ending up in this code path?

**Comment by lelandjansen** [comment]
> How are we ending up in this code path?

@JDevlieghere We're trying to build a release on macOS following [these steps](https://github.com/llvm/llvm-project/blob/5e6bb1fb885abec2e8bc85422bbd83fe4ece6d3b/llvm/docs/ReleaseProcess.rst#L54) and are getting a linker warning for the outdated flag name.

E.g., (from test-release.sh)

```
/path/to/llvm-project/final/Phase2/Release/llvmCore-18.1.3-final.install/usr/local/bin/clang  -fPIC -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wc++98-compat-extra-semi -Wimplicit-fallthrough -Wcovered-switch-default -Wstring-conversion -Wmisleading-indentation -Wctad-maybe-unsupported -Wall -fcolor-diagnostics -Wcast-qual -Wformat-pedantic -Wimplicit-fallthrough -Wsign-compare -Wno-enum-constexpr-conversion -Wno-extra -Wno-pedantic -fno-semantic-interposition -fdata-sections -O3 -DNDEBUG -arch arm64 -isysroot /Applications/Xcode-15.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX14.0.sdk -mmacosx-version-min=10.15 -dynamiclib -Wl,-headerpad_max_install_names -current_version 5.0 -compatibility_version 5.0 -o ../../../../lib/libomp.dylib -install_name @rpath/libomp.dylib CMakeFiles/omp.dir/kmp_alloc.cpp.o CMakeFiles/omp.dir/kmp_atomic.cpp.o CMakeFiles/omp.dir/kmp_csupport.cpp.o CMakeFiles/omp.dir/kmp_debug.cpp.o CMakeFiles/omp.dir/kmp_itt.cpp.o CMakeFiles/omp.dir/kmp_environment.cpp.o CMakeFiles/omp.dir/kmp_error.cpp.o CMakeFiles/omp.dir/kmp_global.cpp.o CMakeFiles/omp.dir/kmp_i18n.cpp.o CMakeFiles/omp.dir/kmp_io.cpp.o CMakeFiles/omp.dir/kmp_runtime.cpp.o CMakeFiles/omp.dir/kmp_settings.cpp.o CMakeFiles/omp.dir/kmp_str.cpp.o CMakeFiles/omp.dir/kmp_tasking.cpp.o CMakeFiles/omp.dir/kmp_threadprivate.cpp.o CMakeFiles/omp.dir/kmp_utility.cpp.o CMakeFiles/omp.dir/kmp_barrier.cpp.o CMakeFiles/omp.dir/kmp_wait_release.cpp.o CMakeFiles/omp.dir/kmp_affinity.cpp.o CMakeFiles/omp.dir/kmp_dispatch.cpp.o CMakeFiles/omp.dir/kmp_lock.cpp.o CMakeFiles/omp.dir/kmp_sched.cpp.o CMakeFiles/omp.dir/kmp_collapse.cpp.o CMakeFiles/omp.dir/z_Linux_util.cpp.o CMakeFiles/omp.dir/kmp_gsupport.cpp.o CMakeFiles/omp.dir/thirdparty/ittnotify/ittnotify_static.cpp.o CMakeFiles/omp.dir/kmp_taskdeps.cpp.o CMakeFiles/omp.dir/kmp_cancel.cpp.o CMakeFiles/omp.dir/kmp_ftn_cdecl.cpp.o CMakeFiles/omp.dir/kmp_ftn_extra.cpp.o CMakeFiles/omp.dir/kmp_version.cpp.o "CMakeFiles/omp.dir/ompt-general.cpp.o" CMakeFiles/omp.dir/z_Linux_asm.S.o
```

**Comment by JDevlieghere** [comment]
Right, my point is that (I think) that doesn't make sense. AFAIK `addMinVersionArgs` is called exclusively from the code snippet I pasted, which should check the linker version. The version of `ld` in which this changed is much newer than the 520 referenced there. 

I'd start by debugging clang and seeing what the claimed version number is. The version is either passed in with `-mlinker-version=` or it's set by CMake during configuration (look for `Host linker version: 1234.5`). I bet one of these is wrong.

**Comment by lelandjansen** [comment]
`Host linker version: 1015.7`

I'm happy to close this PR and debug/reopen the issue if the warning becomes a problem.

**Pull request closed without merging**
