### PR TITLE
[llvm-readtapi] Add symlink to call `readtapi`

### PR DESCRIPTION
**Pull request by cyndyishida**

### CODE REVIEW

**Comment by cyndyishida** [comment]
This may be overkill but I didn't figure out a better way to install both the tool and symlink when adding `readtapi` to `LLVM_DISTRIBUTION_COMPONENTS`

**Comment by ributzka** [comment]
I see the usage of `add_llvm_tool_symlink` in other tools. Could that simplify the change?

**Comment by cyndyishida** [comment]
> I see the usage of `add_llvm_tool_symlink` in other tools. Could that simplify the change?

I tried that initially. AFAICT it doesn't create a target, so I couldn't figure out how to get that symlink as a part of the installation step. I ended up doing a simpler version of https://github.com/llvm/llvm-project/blob/main/llvm-libgcc/CMakeLists.txt#L134

**Comment by ributzka** [comment]
I am looking at `llvm-nm` as an example, which also has the symlink. `llvm-nm` is also part of LLVM_TOOLCHAIN_TOOLS, but I don't see `llvm-readtapi` in that list.

**Comment by ributzka** [comment]
`llvm-nm' seems special, since it is considered a binutils tool.

**Comment by cyndyishida** [comment]
> `llvm-nm' seems special, since it is considered a binutils tool.

Yes, there are BINUTILS and CCTOOLS and TOOLCHAIN_TOOLS. I'm not opposed to adding `readtapi` to TOOLCHAIN_TOOLS but I still want to be able to install readtapi as a part of downstream `tapi`, separate from the rest of the llvm tools.

**Review by ributzka — APPROVED** [review]
LGTM

**Comment by cyndyishida** [comment]
> I see the usage of `add_llvm_tool_symlink` in other tools. Could that simplify the change?

For the sake of completeness, this is actually enough for my goal to install downstream. It turned out the downstream project had some defaults that didn't play nicely with llvm-tools. Specifically `set(LLVM_BUILD_TOOLS OFF CACHE BOOL "")`

**Review by smeenai — APPROVED** [review]
LGTM

**Pull request merged**
