### PR TITLE
Fix tests for https://github.com/llvm/llvm-project/pull/89884

### PR DESCRIPTION
**Pull request by kyulee-com**

### CODE REVIEW

**Comment by alx32** [comment]
LGTM. Nit: current pattern is to not have space in `REQUIRES: ...` list , only ','

**Review by alx32 — APPROVED** [review]

**Comment by kyulee-com** [comment]
> LGTM. Nit: current pattern is to not have space in `REQUIRES: ...` list , only ','

Looking at other tests, they also seem have space -- https://github.com/llvm/llvm-project/blob/main/llvm/test/tools/llvm-exegesis/X86/latency/loop-register.s#L1

**Comment by alx32** [comment]
> Looking at other tests, they also seem have space -- https://github.com/llvm/llvm-project/blob/main/llvm/test/tools/llvm-exegesis/X86/latency/loop-register.s#L1

Indeed, now I see it varies depending on tests - so either is fine.

https://github.com/llvm/llvm-project/blob/main/clang/test/CodeGen/swift-async-extended-fp.c#L19

**Comment by vvereschaka** [comment]
Thank you @kyulee-com 
the tests on the nvptx builders have been fixed.

**Pull request merged**
