### PR TITLE
[Serialization] Load Specialization Lazily (2/2)

### PR DESCRIPTION
**Pull request by ChuanqiXu9**
This is the successor of https://github.com/llvm/llvm-project/pull/76774.

I meant to use spr but I failed. So I created the stacked review here manually. Hope this won't be too bad.

The core idea of the patch is: when we see the new specialization for template decl in other modules, we don't add the specialization to the update list (so it'll be loaded at once if needed). But we add these specializations and the corresponding hashed values to a hash table and we wrote the hash table to disk instead. So when we read that template decl in other modules, we will associate the hash table with that template decl.

In fact, the whole process is exactly the same with how we update the name lookup table.

### CODE REVIEW

**Comment by vgvassilev** [comment]
Let me try something.

**Comment by vgvassilev** [comment]
@ChuanqiXu9, I managed to push the commit here back to https://github.com/llvm/llvm-project/pull/76774 and we can continue the discussion there. Would that be sufficient?

**Comment by ChuanqiXu9** [comment]
> @ChuanqiXu9, I managed to push the commit here back to #76774 and we can continue the discussion there. Would that be sufficient?

The intention of split the patch is to ease the reviewing. If you are glad to do that, yes, it will be pretty good : )

**Comment by ChuanqiXu9** [comment]
Then this is not needed as far as I understood.

**Pull request closed without merging**
