### PR TITLE
[clang][analyzer] Remove array bounds check from PointerSubChecker

### PR DESCRIPTION
**Pull request by balazske**
At pointer subtraction only pointers are allowed that point into an array (or one after the end), this fact was checker by the checker. This check is now removed because it is a special case of array indexing error that is handled by a different checker (ArrayBoundsV2). At least theoretically the array bounds checker (when finalized) should find the same cases that were detected by the PointerSubChecker.

### CODE REVIEW

**Review by NagyDonat — COMMENTED** [review]
In the PR/commit message you write that

> At least theoretically the array bounds checker (when finalized) should find the same cases that were detected by the PointerSubChecker.

but I'm pretty sure that the array bound checker already does find all these cases (and much more complex cases as well). (The only remaining reason why ArrayBoundV2 is in alpha is that it emits too many false positives, because engine issues like the inaccurate modeling of loops feed it with incorrect information.)

Instead of deleting the array bound testcases, you could also enable ArrayBoundV2 in the pointer-sub test files and validate that it does find those reports.

Also note that the array bounds checker is named `ArrayBoundV2` with no "s" in the name. (I also wrote this incorrectly in a comment yesterday.)

**Comment by NagyDonat** [comment]
Oh, you're right, invalid pointer arithmetic like `(&x - 1)` is not handled by ArrayBoundV2, because right now that's the responsibility of a THIRD checker, `alpha.core.PointerArithm`.

However, directly after bringing `ArrayBoundV2` out of alpha, I'll continue with working on this `PointerArithm` and either I'll completely merge it with `ArrayBoundV2` or I'll keep it as a separate "frontend" which also calls the bounds-checking logic that's behind `ArrayBoundV2`.

Based on this I'd suggest that you should
- delete the bounds checking logic from `PointerSubChecker`,
- delete the testcases that were testing it (because it would be too complicated to bring in *two* other checkers + AFAIK `PointerArithm` is in a bad shape currently),
- refer to both ArrayBoundV2 and PointerArithm in the documentation.

**Review by NagyDonat — APPROVED** [review]
Thanks for the updates, I'm satisfied with the state of this commit. However let's wait for an independent approval from @steakhal @haoNoQ or someone else, because this change does reduce the scope of this checker.

**Review by steakhal — APPROVED** [review]
I haven't really checked the PR, but we don't map the PointerSub checker to any rules.
Maybe, after it's out of alpha we will come back and check if it makes sense for us :)

Thank you working on these btw. A lot of unappreciated work all front.

**Review by benshi001 — APPROVED** [review]
LGTM

**Pull request merged**
