### PR TITLE
[mlir][linalg] Add linalg.conv_2d_ngchw_gfchw_q to named ops

### PR DESCRIPTION
**Pull request by zjgarvey**
Adds a named op: linalg.conv_2d_ngchw_gfchw_q. This op is similar to linalg.conv_2d_ngchw_gfchw, but additionally incorporates zero point offset corrections.

### CODE REVIEW

**Comment by zjgarvey** [comment]
For future reference, is bin/update_core_linalg_named_ops.sh supposed to regenerate the current yaml file exactly? If not, is the general practice to run this script and revert any unrelated diffs manually?

**Comment by ftynse** [comment]
> For future reference, is bin/update_core_linalg_named_ops.sh supposed to regenerate the current yaml file exactly? If not, is the general practice to run this script and revert any unrelated diffs manually?

It should generate the current file. If there are discrepancies, please consider sending a separate patch so we can examine what they are and advise.

> I'm not sure what kinds of unit tests would be appropriate for simply adding a new op like this. Any suggestions?

A roundtripping test showing that the op exists can can be parsed and printed back, and a test that converts this op to a generic op to check the correctness of the model and guard against regression in the specification. Both are FileCheck tests.

Also please note that the first message of the PR is being picked up as commit description and update it to something more meaningful.

**Comment by zjgarvey** [comment]
> It should generate the current file. If there are discrepancies, please consider sending a separate patch so we can examine what they are and advise.

Will do.

> A roundtripping test showing that the op exists can can be parsed and printed back, and a test that converts this op to a generic op to check the correctness of the model and guard against regression in the specification. Both are FileCheck tests.

I think I added the types of lit tests you were talking about. Please let me know if those look appropriate. 

> Also please note that the first message of the PR is being picked up as commit description and update it to something more meaningful.

Changed, thanks!

**Review by ftynse — APPROVED** [review]
Please give @nicolasvasilache a chance to take a look.

**Comment by rsuderman** [comment]
@nicolasvasilache mind taking a quick look to make sure you approve

**Comment by zjgarvey** [comment]
@ftynse I haven't had any luck getting in touch with Nico yet. Would you mind revisiting this PR and merging it if you think it is acceptable? I don't have merge permissions myself.

**Comment by nicolasvasilache** [comment]
Sorry just saw this will look tomorrow.

**Comment by zjgarvey** [comment]
> Sorry just saw this will look tomorrow.

Thanks!

**Review by nicolasvasilache — APPROVED** [review]
LGTm, thanks!

**Pull request merged**
