### PR TITLE
[RISCV] Implement RISCVTTIImpl::shouldConsiderAddressTypePromotion for RISCV

### PR DESCRIPTION
**Pull request by LiqinWeng**
This optimization helps reduce repeated calculations of base addresses by extracting type extensions when the same base address is accessed multiple times but its offset is a constant.

### CODE REVIEW

**Review by wangpc-pp — COMMENTED** [review]
Can you add a description and what can we gain from this patch?

**Comment by LiqinWeng** [comment]
> Can you add a description and what can we gain from this patch?
image
This optimization helps reduce repeated calculations of base addresses by extracting type extensions when the same base address is accessed multiple times but its offset is a constant. So I added this API implementation for RISCV

**Comment by LiqinWeng** [comment]
test case form drystone:
```
void test5(int array2[50][50], int a, int b) {
    int loc = a + 5;
    array2[loc][loc] += 1;
    array2[loc + 3][loc] = b;
}
```
The optimization effects are as follows：
image

**Comment by topperc** [comment]
Why are there InstCombine changes in this patch?

**Comment by LiqinWeng** [comment]
> Why are there InstCombine changes in this patch?

I removed the optimization I had implemented in instcombine. I think that when the offset in the address calculation is a constant, it can be covered in the current patch and does not need to be implemented in InstCombine.
image

**Comment by topperc** [comment]
> > Why are there InstCombine changes in this patch?
> 
> I removed the optimization I had implemented in instcombine. I think that when the offset in the address calculation is a constant, it can be covered in the current patch and does not need to be implemented in InstCombine. image

They should be separate PRs with different reviewers.

**Review by nikic — DISMISSED** [review]
Rejecting the InstCombine changes, no comment on the rest.

**Comment by topperc** [comment]
I'm in favor of this patch. The shouldConsiderAddressTypePromotion code is a copy of AArch64. We've had this enabled in our downstream for a couple years.

**Comment by LiqinWeng** [comment]
> Rejecting the InstCombine changes, no comment on the rest.

I restored the optimization of instcombine.

**Comment by LiqinWeng** [comment]
> > > Why are there InstCombine changes in this patch?
> > 
> > 
> > I removed the optimization I had implemented in instcombine. I think that when the offset in the address calculation is a constant, it can be covered in the current patch and does not need to be implemented in InstCombine. image
> 
> They should be separate PRs with different reviewers.

I restored the optimization of instcombine

**Comment by LiqinWeng** [comment]
image
Does anyone know how to solve this problem? @topperc @nikic

**Comment by nikic** [comment]
@LiqinWeng Ignore it, it's an infrastructure issue.

**Comment by LiqinWeng** [comment]
> was requested for review

Have any other questions？Can I merge it？

**Comment by LiqinWeng** [comment]
> I'm in favor of the RISCV part of this patch. The shouldConsiderAddressTypePromotion code is a copy of AArch64. We've had this enabled in our downstream for a couple years.

Have any other questions？Can I merge it？

**Review by topperc — APPROVED** [review]
LGTM

**Pull request merged**
