### PR TITLE
[clang][NFC] Move Bounds Safety Sema code to `SemaBoundsSafety.cpp`

### PR DESCRIPTION
**Pull request by delcypher**
This patch adds a new `SemaBoundsSafety.cpp` source file and moves the existing `CheckCountedByAttrOnField` function and related helper functions and types from `SemaDeclAttr.cpp` into the new source file. The `CheckCountedByAttrOnField` function is now a method on the Sema class and now has doxygen comments.

The goal behind this refactor is to clearly separate the `-fbounds-safety` Sema code from everything else.

Although `counted_by(_or_null)` and `sized_by(_or_null)` attributes have a meaning outside of `-fbounds-safety` it seems reasonable to also have the Sema logic live in `SemaBoundsSafety.cpp` since the intention is that the attributes will have the same semantics (but not necessarily the same enforcement).

As `-fbounds-safety` is upstreamed additional Sema checks will be added to `SemaBoundsSafety.cpp`.

rdar://131777237

### CODE REVIEW

**Review by Endilll — APPROVED** [review]

**Review by AaronBallman — APPROVED** [review]
LGTM, thank you!

**Comment by delcypher** [comment]
@AaronBallman @Endilll Thanks for approving. I'll wait a bit for some of the code owners to chime in before landing this.

@rapidsna @hnrklssn @bwendling @kees Please let me know if you have any concerns about this refactor.

**Review by rapidsna — APPROVED** [review]

**Comment by delcypher** [comment]
Rebased due to the conflict caused by landing #92623

**Comment by kees** [comment]
> @rapidsna @hnrklssn @bwendling @kees Please let me know if you have any concerns about this refactor.

Yeah, FWIW, this is fine by me. I just want to make sure that we don't hide stuff behind `-fbounds-safety` that doesn't need to be behind a flag (e.g. `counted_by`, `sized_by` and their application to struct members, function prototypes, etc).

**Pull request merged**
