### PR TITLE
LoopVectorize/reduction: add negative test for vectorizable example

### PR DESCRIPTION
**Pull request by artagnon**
The following snippet has been extracted from SPEC:

```c
  int ix86_rtx_costs(unsigned long value)
  {
    int nbits;
    for (nbits = 0; value != 0; value &= value - 1)
      nbits++;
    return nbits;
  }
```

Although gcc-aarch64 vectorizes it just fine, llvm does not. The reason for this is that the LoopVectorizer gets confused when the phi corresponding to the 'and' instruction has another (unrelated) user: in this case, it is an 'add'. As a preliminary step for vectorizing the example, add a negative test.

### CODE REVIEW

**Comment by artagnon** [comment]
The diff might look a little suspicious, but all I've done is to move all the other negative tests to the end of the file.

**Review by Mel-Chen — COMMENTED** [review]
Nice case, thanks! This is popcount. In my opinion, it is possible to use loop idiom pass to convert to ctpop.

**Comment by nikic** [comment]
LIR actually already has support for recognizing popcounts: https://github.com/llvm/llvm-project/blob/50ece4cba949787241b5fbfc94be6cfdc66e90ee/llvm/lib/Transforms/Scalar/LoopIdiomRecognize.cpp#L1861

So you'd want to find out why that doesn't trigger and maybe add a PhaseOrdering test.

**Comment by Mel-Chen** [comment]
> LIR actually already has support for recognizing popcounts:
> 
> https://github.com/llvm/llvm-project/blob/50ece4cba949787241b5fbfc94be6cfdc66e90ee/llvm/lib/Transforms/Scalar/LoopIdiomRecognize.cpp#L1861
> 
> So you'd want to find out why that doesn't trigger and maybe add a PhaseOrdering test.

I tried, it is worked well. 
@artagnon I guess the target you tried doesn't support popcount instruction. Please enable it and try again.

**Pull request closed without merging**
