### PR TITLE
[AArch64] Fix scheduling information for arithmetic and logical instructions.

### PR DESCRIPTION
**Pull request by Asher8118**
This patch corrects scheduling information relating to Neoverse-V2 arithmetic and logical instructions.

### CODE REVIEW

**Review by rj-jesus — COMMENTED** [review]
Hi, thanks for these changes, in general this LGTM. Just a couple of questions:
1. The SOG doesn't seem to mention a G group for integer single-cycle 0/1 and single/multicycle 0 pipes. Are there any plans to update the SOG to reflect this?
2. Except for the address generation instructions (ADR and ADRP), which have a throughput of 4, all instructions that use the F group seem to have a throughput of at best 3 according to the SOG. **If** there's going to be a discrepancy between the model and the SOG re the F group, would it be better to make the ADR* instructions the exception? In any case, if there's going to be a discrepancy, it would be good to have this documented in a comment, for example.

What do you think?

**Comment by Rin18** [comment]
> Hi, thanks for these changes, in general this LGTM. Just a couple of questions:
> 
> 1. The SOG doesn't seem to mention a G group for integer single-cycle 0/1 and single/multicycle 0 pipes. Are there any plans to update the SOG to reflect this?
> 2. Except for the address generation instructions (ADR and ADRP), which have a throughput of 4, all instructions that use the F group seem to have a throughput of at best 3 according to the SOG. **If** there's going to be a discrepancy between the model and the SOG re the F group, would it be better to make the ADR* instructions the exception? In any case, if there's going to be a discrepancy, it would be good to have this documented in a comment, for example.
> 
> What do you think?

Thanks for the comments, this patch does not reflect a SOG update, since the resources in group G are all part of F as well.
The G unit I created in the patch is for the purpose of modelling the behaviour of instructions that use pipeline F, but have throughput of 3 rather than 4. The instructions in this patch still use resources that are part of pipeline F.  This is not a new group that needs to be added to the SOG. Similar behaviour is represented in the V1 scheduling model with the J unit.

**Comment by rj-jesus** [comment]
> Thanks for the comments, this patch does not reflect a SOG update, since the resources in group G are all part of F as well. The G unit I created in the patch is for the purpose of modelling the behaviour of instructions that use pipeline F, but have throughput of 3 rather than 4. The instructions in this patch still use resources that are part of pipeline F. This is not a new group that needs to be added to the SOG. Similar behaviour is represented in the V1 scheduling model with the J unit.

Thanks, I get your point and I agree, it's good to match the throughput reported in the SOG. I'm just trying to understand if the instructions in this patch can really only go through M0, or if they can go through either M0/1 pipe (in addition to the single-cycle 0/1 pipes). M0 already has quite some instructions specific to it, including some predicate instructions, so it would be good to get this right to model its backend pressure a bit more accurately.

**Comment by Rin18** [comment]
> I'm just trying to understand if the instructions in this patch can really only go through M0, or if they can go through either M0/1 pipe (in addition to the single-cycle 0/1 pipes). M0 already has quite some instructions specific to it, including some predicate instructions, so it would be good to get this right to model its backend pressure a bit more accurately.
I see your point. My understanding is that since the SOG points to pipeline F for those instructions, then they can go through either M0/1 pipe. I selected M0 only to keep the model consistent with V1. I'm not sure what happens on average, whether pipeline M0 or M1 is used more often. If there is evidence to suggest which pipe is used less then I'll be happy to reflect this behaviour in this patch.

**Comment by davemgreen** [comment]
I believe that the throughput restrictions in these cases don't come from the pipelines that they can issue into but some other stage like rename or decode. Limiting the number of execution units they can use is one alternative, but in reality is can issue into any F pipeline. I have suggested in other reviews (with a different kind of instruction) that we get the pipeline features right and ignore getting the exact throughput correct. In reality it is difficult to hit this many flag-setting instructions that actually do something useful in a single cycle.

One way to fix it might be to add a new resource, which there are 3 of, that represents the number of flag-setting instructions per cycles. It might not be exactly correct as it will use that resource in the same stage as issue, not in the decode/rename stage. If we add too many of those the scheduler could start to get confused too, making sub-optimal decision because it is caring about the wrong thing. It might be worth a try though, so see if it can solve the issue that way.

**Comment by Rin18** [comment]
> One way to fix it might be to add a new resource, which there are 3 of, that represents the number of flag-setting instructions per cycles. It might not be exactly correct as it will use that resource in the same stage as issue, not in the decode/rename stage. If we add too many of those the scheduler could start to get confused too, making sub-optimal decision because it is caring about the wrong thing. It might be worth a try though, so see if it can solve the issue that way.

I've implemented this for both V1 and V2. Most of the changes in the tests come from adding the new flag resource to the MCA output.

**Review by davemgreen — APPROVED** [review]
Thanks for doing V1 too. LGTM

**Pull request merged**
