### PR TITLE
[clang][RISCV] Reorder sema check for RVV type

### PR DESCRIPTION
**Pull request by 4vtomat**
Currently using the command `clang -cc1 -triple riscv64` to compile the
code below:
```
#include <riscv_vector.h>
void foo() {
  vfloat64m1_t f64m1;
}
```
would get the error message "RISC-V type 'vfloat64m1_t' ... requires the 'zve64x' extension"
which is supposed to be "RISC-V type 'vfloat64m1_t' ... requires the 'zve64d' extension".

### CODE REVIEW

**Review by kito-cheng — COMMENTED** [review]
Could you add a testcase?

**Comment by 4vtomat** [comment]
Maybe we can modify the current test case, it would get the error message "RISC-V type 'vfloat64m1_t' ... requires the 'zve64x' extension", but should be 'zve64d' instead.

**Review by topperc — APPROVED** [review]
LGTM

**Review by topperc — CHANGES_REQUESTED** [review]
I missed Kito's comment about the test

**Comment by 4vtomat** [comment]
> I missed Kito's comment about the test

I guess `clang/test/Sema/riscv-vector-float64-check.c` is sufficient since I've modified it to have only `zve32x` feature. If you use current llvm to run the test, it would fail.

**Review by topperc — APPROVED** [review]
LGTM

**Pull request merged**
