### PR TITLE
LCA: migrate from DA to LAA; fix cost computation

### PR DESCRIPTION
**Pull request by artagnon**
LoopCacheAnalysis currently uses DependenceAnalysis, which hasn't been worked on for years. Migrate it to use the newer and actively-maintaiend LoopAccessAnalysis, fixing a long-standing cost-computation issue, due to an underlying bug in DependenceAnalysis.

### CODE REVIEW

**Comment by artagnon** [comment]
No impact on compile time: see [results from LLVM Compile Time Tracker](http://llvm-compile-time-tracker.com/compare.php?from=725fab987d7b2133293eb4b82e8a0e9c6ba76053&to=7e3fe5ea9322799c94a4f0bfb842e9b967b57e2d&stat=instructions:u).

**Comment by nikic** [comment]
> No impact on compile time: see [results from LLVM Compile Time Tracker](http://llvm-compile-time-tracker.com/compare.php?from=725fab987d7b2133293eb4b82e8a0e9c6ba76053&to=7e3fe5ea9322799c94a4f0bfb842e9b967b57e2d&stat=instructions:u).

The LoopInterchange pass is not enabled by default. To measure compile-time impact you first need to push a commit flipping the flag at https://github.com/llvm/llvm-project/blob/d6d60707ec2b60843c5bfc2c3bc44e4478add17a/llvm/lib/Passes/PassBuilderPipelines.cpp#L200 and then your change.

**Comment by nikic** [comment]
> [Actual results](http://llvm-compile-time-tracker.com/compare.php?from=ec3e5c9e73d2d356ffa09a5f9075eba7e09040a8&to=28daa444b957bdf97707a489e3eb6b4c111ce264&stat=instructions:u).

A possible reason for this could be that we now have to compute *both* LAA and DA. Do you think it will be possible to change LoopInterchange to use LAA as well in the future, so only one will have to be computed?

**Comment by artagnon** [comment]
> A possible reason for this could be that we now have to compute _both_ LAA and DA.

I also think this is the reason.

> Do you think it will be possible to change LoopInterchange to use LAA as well in the future, so only one will have to be computed?

I investigated this thoroughly, and the remaining callers of DA after this patch are LoopInterchange and LoopUnrollAndJam. However, I think it is _impossible_ to migrate them to LAA, without doing months of work on LAA first. The reason is that LAA seems to be fundamentally less powerful than DA, and cannot analyze dependencies in loop nests: it can only analyze dependencies in a loop that is determined to be the innermost one. This is also the reason outer-loop vectorization is a non-starter.

Even if we were to go for a full rewrite, I think LoopInterchange and LoopUnrollAndJam fundamentally require a more powerful analysis than LAA. I think my conclusion is correct, but I would be more comfortable if @fhahn could also confirm this.

**Comment by artagnon** [comment]
> In my mind, DA = DivergenceAnalysis but I don't see any change to DivergenceAnalysis in this patch. Do you mean DI (DependenceInfo) in the patch title?

DependenceAnalysis. It should be clear from the context, as we're migrating from DependenceAnalysis to LoopAccessAnalysis.

**Comment by sjoerdmeijer** [comment]
And maybe for a little bit more context, we are very much interested in loop-interchange and DependenceAnalysis, which is why I CC'ed Sebastian. We are thinking of trying to get at least one of the loop optimizations that uses DA enabled. We do appreciated that some work is required as there are some issues raised against components (interchange and DA), and we are trying to form an opinion what the work would involve.

**Comment by sebpop** [comment]
What's the motivation of this change?

> DependenceAnalysis, which hasn't been worked on for years
It's not because DA has not been worked on for several years that we need to rewrite the passes currently using DA.

> fixing a long-standing cost-computation issue, due to an underlying bug in DependenceAnalysis.

What's this "cost-computation issue" about?
Have you investigated how to properly fix this with DA distance vectors?
I'm pretty sure it's related to CacheAnalysis incorrectly reading the distance vectors.  

Instead of this patch we should do the opposite:
remove uses of LAA and move the loop vectorizer pass to use DA.
With DA the loop vectorizer would not depend on runtime checks to disambiguate the existence of data dependences.

**Pull request closed without merging**
