### PR TITLE
[AMDGPU] CodeGen for SMEM instructions

### PR DESCRIPTION
**Pull request by mbrkusanin**

### CODE REVIEW

**Comment by piotrAMD** [comment]
There is some duplication with #75492 (the part about the restricted offset) but I see why you need it in both patches and it looks the common parts will merge cleanly anyway.

**Comment by mbrkusanin** [comment]
> There is some duplication with #75492 (the part about the restricted offset) but I see why you need it in both patches and it looks the common parts will merge cleanly anyway.

Yes, I kept the codegen updates independent from each other so they could be merged in whatever order they get approved (just need a rebase in between). So there might be some duplicated code between them.

**Comment by piotrAMD** [comment]
Missing updates to test/CodeGen/AMDGPU/GlobalISel/load-constant.96.ll (gfx12 run lines)?

**Review by piotrAMD — APPROVED** [review]

**Comment by mbrkusanin** [comment]
> Missing updates to test/CodeGen/AMDGPU/GlobalISel/load-constant.96.ll (gfx12 run lines)?

Well spotted

**Pull request merged**
