### PR TITLE
[clang codegen] Add CreateRuntimeFunction overload that takes a clang type.

### PR DESCRIPTION
**Pull request by efriedma-quic**
Correctly computing the LLVM types/attributes is complicated in general, so add a variant which does that for you.

### CODE REVIEW

**Comment by JonPsson1** [comment]
It would be great if this new method also called TargetLibraryInfo and set the extension attributes for any integer <=32 bits... Or are you maybe waiting with that as a separate patch?

**Comment by efriedma-quic** [comment]
SetLLVMFunctionAttributes() should add the appropriate signext/zeroext attribute.  At least, it appears to work in my testing.  I'll add a regression test.

**Comment by JonPsson1** [comment]
> SetLLVMFunctionAttributes() should add the appropriate signext/zeroext attribute. At least, it appears to work in my testing. I'll add a regression test.

Ah, I see. I ran this now on SystemZ and can confirm that this is now getting the proper extension attributes. A test might not even be needed, considering that this will (hopefully soon by default) be checked on SystemZ (general check in back-end), where it was discovered.

**Comment by JonPsson1** [comment]
What does it mean that this is a "draft"? It seems to me that this is ready for a regular review..?

**Review by nikic — APPROVED** [review]
LGTM, I think this is the correct way to fix the issue.

**Comment by JonPsson1** [comment]
LGTM, but maybe also update the FIXME comment in the original version of CreateRuntimeFunction().

**Pull request merged**
