### PR TITLE
[AArch64][ABI] Pass v8f32 on the stack

### LINKED ISSUE #69694: [AArch64] compile crash on "Call operand has unhandled type"
* test:  https://gcc.godbolt.org/z/1fsW7cjG9

* report error:  `clang -march=armv8.3-a+sve -O3 -S reduced.ll`
```
AArch64ISelLowering.cpp:7014: 
void analyzeCallOperands(const llvm::AArch64TargetLowering&, const llvm::AArch64Subtarget*, const llvm::TargetLowering::CallLoweringInfo&, llvm::CCState&): 
Assertion `!Res && "Call operand has unhandled type"' failed
```

### PR DESCRIPTION
**Pull request by vfdff**
No definition of calling convention for 256bit vector types

Fixes https://github.com/llvm/llvm-project/issues/69694

### CODE REVIEW

**Comment by aemerson** [comment]
This looks weird. How come this hasn't been hit before?

**Comment by vfdff** [comment]
> This looks weird. How come this hasn't been hit before?

I think this may be related to the data type width, where the data type `v8f32` is a 256-bit fixed-point vector type, and we rarely use such data types directly as parameters or return values. Generally, the width of the fixed-point vector data type is 128 bits, which can be placed in the `V register` on AArch64.

**Comment by vfdff** [comment]
hi @kawashima-fj @paulwalker-arm , I checked the PR70034 doesn't fix this issue, so maybe this change is still need ?

**Comment by kawashima-fj** [comment]
@vfdff I fixed in #70034 (will be merged soon) not to create `v8f32` in the ArgumentPromotion pass. If `v8f32` is created in another place, #70034 does not fix anything.

**Comment by vfdff** [comment]
> @vfdff I fixed in #70034 (will be merged soon) not to create `v8f32` in the ArgumentPromotion pass. If `v8f32` is created in another place, #70034 does not fix anything.

Thanks for your explaination, I try to check this because [PR74395](https://discourse.llvm.org/t/aarch64-abi-should-we-add-more-fixed-vector-type-wider-than-128-bit/74395)

**Comment by vfdff** [comment]
Fixed by https://github.com/llvm/llvm-project/pull/70847

**Pull request closed without merging**
