### PR TITLE
[mlir][sparse] fix bug with all-dense assembler

### PR DESCRIPTION
**Pull request by aartbik**
When only all-dense "sparse" tensors occur in a function prototype, the assembler would skip the method conversion purely based on input/output counts. It should rewrite based on the presence of any annotation, however.

### CODE REVIEW

**Comment by yinying-lisa-li** [comment]
Thanks for the change!

**Review by yinying-lisa-li — APPROVED** [review]

**Comment by mtsokol** [comment]
Hi! Would it be possible to backport this PR to `release/19.x` branch?

**Comment by aartbik** [comment]
I did not even know we had release branches for MLIR?!

**Comment by mtsokol** [comment]
> I did not even know we had release branches for MLIR?!

It's a single branch for the whole LLVM project.
LLVM 19 is in one release branch: https://github.com/llvm/llvm-project/tree/release/19.x

**Pull request merged**
