### PR TITLE
llvm-profgen: Fix race condition

### PR DESCRIPTION
**Pull request by MatzeB**
Fix race condition when multiple instances of `llvm-progen` read from the same 
inputs.

### CODE REVIEW

**Review by wlei-llvm — APPROVED** [review]
LGTM, thanks!

**Comment by MatzeB** [comment]
test failure on windows bot seems unrelated, merging

**Comment by HaohaiWen** [comment]
@MatzeB , why do we need to create a uniq temp perf-script for each llvm-profgen read?

**Comment by MatzeB** [comment]
> @MatzeB , why do we need to create a uniq temp perf-script for each llvm-profgen read?

Without this change, when you have two `llvm-profgen` instances running on the same input at the same time they will overwrite each others intermediate files and break (i.e. first caller starts conversion; at the same time 2nd caller starts conversion writing to the same file; then if first caller starts reading it may read a half-finished conversion from the 2nd caller).
The previous code also had downsides like needing the directory containing the profile file to be writable which isn't necessarily true or expected by the user.

**Comment by MatzeB** [comment]
Are you having trouble with temporary files accumulating and you running out of disk space? You could probably submit a patch then that the temporary file is deleted after it was read...

**Comment by HaohaiWen** [comment]
> Are you having trouble with temporary files accumulating and you running out of disk space? You could probably submit a patch then that the temporary file is deleted after it was read...

Yeah, I run out of disk for large project.

**Pull request merged**
