### PR TITLE
[X86,MC] Add relocation R_X86_64_REX2_GOTPCRELX

### PR DESCRIPTION
**Pull request by KanRobert**
For

	mov        name@GOTPCREL(%rip), %reg
	test       %reg, name@GOTPCREL(%rip)
	binop      name@GOTPCREL(%rip), %reg

where binop is one of adc, add, and, cmp, or, sbb, sub, xor instructions, add

 `R_X86_64_REX2_GOTPCRELX`/`R_X86_64_CODE_4_GOTPCRELX` = 43

if the instruction starts at 4 bytes before the relocation offset.  It similar to R_X86_64_GOTPCRELX.

Linker can treat `R_X86_64_REX2_GOTPCRELX`/`R_X86_64_CODE_4_GOTPCRELX` as `R_X86_64_GOTPCREL` or convert the above instructions to

	lea	name(%rip), %reg
	mov	$name, %reg
	test	$name, %reg
	binop	$name, %reg

if the first byte of the instruction at the relocation `offset - 4` is `0xd5` (namely, encoded w/ REX2 prefix) when possible.

Binutils patch: https://github.com/bminor/binutils-gdb/commit/3d5a60de52556f6a53d71d7e607c6696450ae3e4
Binutils mailthread: https://sourceware.org/pipermail/binutils/2023-December/131462.html
ABI discussion: https://groups.google.com/g/x86-64-abi/c/KbzaNHRB6QU
Blog: https://kanrobert.github.io/rfc/All-about-APX-relocation

### CODE REVIEW

**Comment by KanRobert** [comment]
TODO: 
* [ ] Pass tests lld/test/ELF/x86-64-gotpc-relax.s and lld/test/ELF/x86-64-gotpc-relax-nopic.s

**Comment by KanRobert** [comment]
> I suppose the name of relocation used by binutils is R_X86_64_CODE_4_GOTPCRELX Also binutils has added R_X86_64_CODE_5_GOTPCRELX/R_X86_64_CODE_6_GOTPCRELX, for evex relocation Refer to [bminor/binutils-gdb@3d5a60d](https://github.com/bminor/binutils-gdb/commit/3d5a60de52556f6a53d71d7e607c6696450ae3e4) and [bminor/binutils-gdb@5bc71c2](https://github.com/bminor/binutils-gdb/commit/5bc71c2a6b8efb27089baa1fecded82be4f550a7)

This is the first patch and `R_X86_64_CODE_6_GOTPCRELX` will be added later. `R_X86_64_CODE_5_GOTPCRELX` is only for possible future instructions and whether adding it as placeholder is optional.

I mentioned `R_X86_64_CODE_4_GOTPCRELX` in the description but I prefer `R_X86_64_REX2_GOTPCRELX` personally. Binutils use the former name for possible future instructions w/ 2-byte prefix other than REX2 (see discussion https://groups.google.com/g/x86-64-abi/c/KbzaNHRB6QU).  AFAIKC, the probability is quite low for the general GPR32 design, i.e. `REX2` is already 2-byte long, future prefix should be longer than 2 byte if we need GPR32 at the same time.  And according to that design, probably we should rename  `R_X86_64_REX_GOTPCRELX` to `R_X86_64_CODE_3_GOTPCRELX`. 

If the reviewers prefer the `CODE_4` name, I will update the PR.

**Comment by KanRobert** [comment]
Ping @MaskRay ?

**Review by MaskRay — APPROVED** [review]
(Sorry for the long delay. I had a 3-week long vacation.)

MC/assembler part looks good to me. I haven't checked the ELF part.

For these assembler/linker changes, we should split the lld/ELF part to a separate change.

**Comment by MaskRay** [comment]
And remove ",lld" from the subject when the linker part is separated.

**Comment by KanRobert** [comment]
Passed the validation of cpu2017 on intel sde w/ this patch + APX features.

**Pull request merged**
