### PR TITLE
Fix to attribute plugins reaching an unreachable

### PR DESCRIPTION
**Pull request by amykhuang**
[0faee97](https://github.com/llvm/llvm-project/commit/0faee97a924adec76d5c7cd680c289ced51e6b5a) broke attribute plugins. Specifically, it added a call to `getAttributeSpellingListIndex()` in situations that reached an unreachable statement. This patch adds a check before calling that to avoid hitting the unreachable.

`clang/test/Frontend/plugin-attribute.cpp` has been broken since [0faee97](https://github.com/llvm/llvm-project/commit/0faee97a924adec76d5c7cd680c289ced51e6b5a), and this patch fixes it. 

Bug: [70702](https://github.com/llvm/llvm-project/issues/70702)

### CODE REVIEW

**Comment by shafik** [comment]
Can you please add a more detailed description of the problem and what the fix actually is. The description is what ends up in the git log and it is important that we have enough details there to understand the PR and what changes it makes.

I do not see a test, can this fix be tested?

**Comment by AaronBallman** [comment]
> Can you please add a more detailed description of the problem and what the fix actually is. The description is what ends up in the git log and it is important that we have enough details there to understand the PR and what changes it makes.
> 
> I do not see a test, can this fix be tested?

We could add a test with a `// REQUIRES: plugins, examples` line on the RUN line. We don't have very many tests for plugins in Clang currently, but adding one here would help catch regressions.

**Review by AaronBallman — COMMENTED** [review]
As far as the changes go, they look correct to me. Thank you for the fix! Can you try adding test coverage for the change?

**Comment by amykhuang** [comment]
Huh, apparently my no-unique-address patch did break existing plugin tests (e.g. clang/test/Frontend/plugin-attribute.cpp), and this patch doesn't fix it

**Comment by amykhuang** [comment]
Updated the PR description and the patch. The existing `clang/test/Frontend/plugin-attribute.cpp` seems sufficient for test coverage. (I guess it wasn't being tested on bots though, otherwise we would have seen it?)

**Comment by amykhuang** [comment]
ping for review?

**Review by AaronBallman — APPROVED** [review]
> ping for review?

My apologies for the delay!

The changes LGTM but there is a precommit CI failure with libc++. As best I can tell, that looks to be a transient issue and not caused by your patch, but it would be good to verify that before landing. (I would be really surprised if this change managed to break the demangler behavior.) CC @ldionne @mordante @philnik777 for other opinions.

**Comment by ldionne** [comment]
This is weird, it's the first time I see this and I couldn't find any obvious offending commit. It looks like it shouldn't be related, but at the same time we're not seeing this issue in any of the other builds in the Clang pipeline. You could consider updating the PR with the latest `main` content to re-trigger a CI run and see if that still fails.

**Comment by AaronBallman** [comment]
Oh wow, same failure a second time...

Ohh, this looks familiar now, but... it was already fixed, so why are we still hitting this failure?
```
| expected: clang::TreeTransform<(anonymous namespace)::CurrentInstantiationRebuilder>::RebuildArrayType(clang::QualType, clang::ArraySizeModifier, llvm::APInt const*, clang::Expr*, unsigned int, clang::SourceRange)
| got: 0,   clang::TreeTransform<(anonymous namespace)::CurrentInstantiationRebuilder>::RebuildArrayType(clang::QualType, clang::ArrayType::ArraySizeModifier, llvm::APInt const*, clang::Expr*, unsigned int, clang::SourceRange)
```
should have been fixed by https://github.com/llvm/llvm-project/commit/f5f4c5b313fc809b9b1b9d600d0ec3cec0d12941 over two weeks ago. CC @Endilll

**Comment by Endilll** [comment]
This was fixed by e11148fda6d8c0eec496463adb46fd6f03a91081
I checked the logs, and exactly the part that this commit fixed is failing.

**Comment by Endilll** [comment]
> https://github.com/amykhuang/llvm-project/tree/attr-plugin
> This branch is [2 commits ahead](https://github.com/amykhuang/llvm-project/compare/llvm:llvm-project:main...attr-plugin), [1684 commits behind](https://github.com/amykhuang/llvm-project/compare/attr-plugin...llvm:llvm-project:main) llvm:main.

Yeah, this branch is missing all November commits, include aforementioned fix.

**Comment by amykhuang** [comment]
Whoops, sorry about that, I guess I am failing to update my fork properly...

**Review by AaronBallman — APPROVED** [review]
LGTM assuming precommit CI is now fixed.

**Pull request merged**
