### PR TITLE
 [ConstantRange] Add support for `shlWithNoWrap`

### PR DESCRIPTION
**Pull request by dtcxzyw**
This patch adds initial support for `ConstantRange:: shlWithNoWrap` to fold https://github.com/dtcxzyw/llvm-tools/issues/22. However, this patch cannot fix the original issue. Improvements for `ConstantRange::[u|s]shl_sat` will be submitted in subsequent patches.

### CODE REVIEW

**Comment by antoniofrighetto** [comment]
> However, this patch cannot fix the original issue.

How come? Due to the suboptimal ranges found?

**Comment by dtcxzyw** [comment]
> > However, this patch cannot fix the original issue.
> 
> How come? Due to the suboptimal ranges found?

```
define i1 @src10(i32 %0, i32 %1) {
entry:
  %2 = add nsw i32 %0, %1
  %3 = shl nuw nsw i32 768, %2
  %use = add nuw i32 %3, 1846
  %4 = icmp sgt i32 %use, 0
  ret i1 %4
}

define i1 @tgt10(i32 %0, i32 %1) {
entry:
  ret i1 true
}
```

Yeah, LLVM now produces `[768, 2147483647]` for `%3 = shl nuw nsw i32 768, %2`. But `[768, 768 << (31 - ctlz(768))]` is obviously better.

**Review by antoniofrighetto — COMMENTED** [review]
Looks reasonable to me, I suspect we have the same issues of mul nsw ranges when checking w/ `CheckNonSignWrappedOnly` here.

**Review by nikic — APPROVED** [review]
LGTM

**Pull request merged**
