### PR TITLE
Reapply "[Clang] Unify interface for accessing template arguments as written for class/variable template specializations (#81642)"

### PR DESCRIPTION
**Pull request by sdkrystian**
Reapplies #81642

### CODE REVIEW

**Comment by adrian-prantl** [comment]
How did you address the LLDB test failures?

**Comment by sdkrystian** [comment]
@adrian-prantl While I'm not 100% certain of this, I _think_ modules are cached between test runs for LLDB (the only way I was able to reproduce the crash was by precompiling modules with clang built from the commit before this one, and then deserializing with clang built from this commit). So I _think_ the solution is to bump the AST file major version number, but I'm still looking into it.

**Comment by adrian-prantl** [comment]
Interesting. I though that the check-lldb target would clean the module cache before each run?

https://github.com/llvm/llvm-project/blob/fcfc15b7052a311b7a045e2c6bd26fb5d0b7122c/lldb/test/CMakeLists.txt#L56
https://github.com/llvm/llvm-project/blob/fcfc15b7052a311b7a045e2c6bd26fb5d0b7122c/lldb/test/CMakeLists.txt#L262
https://github.com/llvm/llvm-project/blob/fcfc15b7052a311b7a045e2c6bd26fb5d0b7122c/lldb/test/API/lit.cfg.py#L219

**Review by erichkeane — APPROVED** [review]
I have no problem with this, if it passes CI, I think this is fine.

**Pull request merged**
