### PR TITLE
[NFC][IWYU] Update Support library with IWYU.

### PR DESCRIPTION
**Pull request by dfukalov**
Update according IWYU
- include files in lib/ADT and
- both include and cpp files in lib/Support.

Firstly processed the sources by scripts from https://github.com/include-what-you-use/include-what-you-use, then tuned some miscorrections, also taking into account clangd suggestions.

### CODE REVIEW

**Comment by nikic** [comment]
Build fails with:
```

CCACHE_CPP2=yes CCACHE_HASHDIR=yes /usr/bin/ccache /usr/bin/c++ -DGTEST_HAS_RTTI=0 -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -I/tmp/llvm-project-build-stage1/lib/Support -I/var/llvm-compile-time-tracker/llvm-project/llvm/lib/Support -I/tmp/llvm-project-build-stage1/include -I/var/llvm-compile-time-tracker/llvm-project/llvm/include -fPIC -fno-semantic-interposition -fvisibility-inlines-hidden -Werror=date-time -fno-lifetime-dse -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-uninitialized -Wno-nonnull -Wno-class-memaccess -Wno-redundant-move -Wno-pessimizing-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wsuggest-override -Wno-comment -Wno-misleading-indentation -Wctad-maybe-unsupported -fdiagnostics-color -ffunction-sections -fdata-sections -O3 -DNDEBUG -std=c++17  -fno-exceptions -funwind-tables -fno-rtti -MD -MT lib/Support/CMakeFiles/LLVMSupport.dir/VirtualFileSystem.cpp.o -MF lib/Support/CMakeFiles/LLVMSupport.dir/VirtualFileSystem.cpp.o.d -o lib/Support/CMakeFiles/LLVMSupport.dir/VirtualFileSystem.cpp.o -c /var/llvm-compile-time-tracker/llvm-project/llvm/lib/Support/VirtualFileSystem.cpp
/var/llvm-compile-time-tracker/llvm-project/llvm/lib/Support/VirtualFileSystem.cpp:1257:5: error: qualified name does not name a class before ‘:’ token
 1257 |     : public llvm::vfs::detail::DirIterImpl {
      |     ^
/var/llvm-compile-time-tracker/llvm-project/llvm/lib/Support/VirtualFileSystem.cpp:1257:5: error: expected ‘{’ before ‘:’ token
/var/llvm-compile-time-tracker/llvm-project/llvm/lib/Support/VirtualFileSystem.cpp:1257:5: error: expected unqualified-id before ‘:’ token
```

**Comment by joker-eph** [comment]
Hi, thanks for trying to cleanup the codebase.

Can you provide more context on the motivation / what you're trying to achieve here? 

Did you know that LLVM intentionally does not follow IWYU and favors forward declarations: https://llvm.org/docs/CodingStandards.html#include-as-little-as-possible

**Comment by dfukalov** [comment]
> Can you provide more context on the motivation / what you're trying to achieve here?
The motivation is as usual IWYU and similar refactoring - to reduce build time and probablility of non-related source(s) recompile.
 
> Did you know that LLVM intentionally does not follow IWYU and favors forward declarations: https://llvm.org/docs/CodingStandards.html#include-as-little-as-possible
Yes, but I actually do not see what part of the mentioned standard' section conflicts with the change. Would you please suggest an example where we see a situation when applied IWYU approach can contradict with the part of Coding Standards?

**Review by RKSimon — COMMENTED** [review]
Would it be possible to split this into PRs per subproject please (bolt/clang/lld/llvm/mlir)?

**Comment by jayfoad** [comment]
> > Did you know that LLVM intentionally does not follow IWYU and favors forward declarations: https://llvm.org/docs/CodingStandards.html#include-as-little-as-possible
> 
> Yes, but I actually do not see what part of the mentioned standard' section conflicts with the change.

Could you try preprocessing each affected source file (i.e. compile it with -E) and see whether the total number of included source lines goes up or down? I think that would help to demonstrate whether this patch violates the "include as little as possible" philosophy.

**Comment by nikic** [comment]
I'm seeing a 0.06% increase in build time with this change. Per-file breakdown: http://llvm-compile-time-tracker.com/compare_clang.php?from=9a227ba3e129eaa89498b97421afefb1e9d681df&to=e354fa543d20a8f50ea678c4cfc7d6dc091ad569&stat=instructions%3Au&sortBy=interestingness

Clearly, this introduces some unnecessary includes. But because of the way the change is done, it will be very hard for reviewers for check that this kind of patch is a strict reduction in the transitive include closure.

The way this is usually done is that you remove an individual include from a header and then add any necessary new includes this may require in other files -- with this approach, it is a lot more straightforward to verify the correctness of the change.

**Comment by joker-eph** [comment]
> The motivation is as usual IWYU and similar refactoring - to reduce build time and probablility of non-related source(s) recompile.

I'm confused: as far as I know IWYU achieves the opposite of what you're describing actually: it adds more includes than strictly necessary.

> Yes, but I actually do not see what part of the mentioned standard' section conflicts with the change. Would you please suggest an example where we see a situation when applied IWYU approach can contradict with the part of Coding Standards?

I haven't sanity checked your patch: IWYU is just known to historically to the opposite of what we're trying to do in LLVM (as in: "include strictly the minimum and rely on forward declarations"), either the tools was updated to support the LLVM style, or you've been doing a lot of manual work (but then the PR title is misleading).

**Comment by dfukalov** [comment]
> Could you try preprocessing each affected source file (i.e. compile it with -E) and see whether the total number of included source lines goes up or down? I think that would help to demonstrate whether this patch violates the "include as little as possible" philosophy.

The overall preprocessed files size for the whole lb/Support reduced from 257172 KB to 255369 KB (about 1%)

Anyway, I see the change is too big to review and discuss so I'm going to shrink it. I'm not sure is it better to update this PR or create a new one.

**Comment by dwblaikie** [comment]
> > The motivation is as usual IWYU and similar refactoring - to reduce build time and probablility of non-related source(s) recompile.
> 
> I'm confused: as far as I know IWYU achieves the opposite of what you're describing actually: it adds more includes than strictly necessary. (IIUC, the motivation for IWYU is rather correctness and robustness to refactoring and changes).

It can do both - it can remove an unused header, and add a used header that might be indirectly depended on. (& can switch an include to a forward declaration - or the opposite (if a forward declaration is used, but a definition is required and is currently provided indirectly through some other #include))

> > Yes, but I actually do not see what part of the mentioned standard' section conflicts with the change. Would you please suggest an example where we see a situation when applied IWYU approach can contradict with the part of Coding Standards?
> 
> I haven't sanity checked your patch: IWYU is just known to historically to the opposite of what we're trying to do in LLVM (as in: "include strictly the minimum and rely on forward declarations"), either the tools was updated to support the LLVM style, or you've been doing a lot of manual work (but then the PR title is misleading).

FWIW, IWYU does do forward declarations ( https://github.com/include-what-you-use/include-what-you-use/blob/master/docs/WhyIWYU.md#why-forward-declare )

**Comment by dfukalov** [comment]
Created other [PR 104484](https://github.com/llvm/llvm-project/pull/104484) with reworked/reduced cleanup.

**Pull request closed without merging**
