### PR TITLE
[clang][DebugInfo] Revert to printing canonical typenames for template aliases

### PR DESCRIPTION
**Pull request by Michael137**
This was originally added in https://reviews.llvm.org/D142268 to have LLDB display variable typenames that benefit from suppressing defaulted template arguments.

We currently represent template aliases as `DW_AT_typedef`s instead of `DW_TAG_template_alias`. This means for types like:
```
template <class _Tp>
using __remove_cv_t = __remove_cv(_Tp);

template <class _Tp>
using remove_cv_t = __remove_cv_t<_Tp>;

template<typename T>
class optional {
  using value_type = T;
  remove_cv_t<value_type> __val_;
}
```
we would generate DWARF like:
```
0x0000274f:       DW_TAG_typedef
                    DW_AT_type  (0x0000000000002758 "__remove_cv_t<value_type>")
                    DW_AT_name  ("remove_cv_t<value_type>")

```

This is an actual libc++ type layout introduced in https://github.com/llvm/llvm-project/pull/110355, and uncovered a shortcoming of LLDB's data-formatter infrastructure, where we cache formatters on the contents of `DW_AT_name` (which currently wouldn't be a fully resolved typename for template specializations).

To unblock the libc++ change, I think we can revert this without much fallout.

Then we have two options for follow-up (or do both):
1. reland this but adjust the LLDB formatter cache so it doesn't cache formatters for template specializations
2. implement support for `DW_TAG_template_alias` in LLDB (and make Clang generate them by default).

### CODE REVIEW

**Comment by Michael137** [comment]
Test failures in `Sema/aarch64-sve-vector-trig-ops.c` unrelated

**Review by adrian-prantl — APPROVED** [review]
Sounds unfortunate, but if you think that's the best choice for unblocking libc++, let's do that.

**Comment by dwblaikie** [comment]
Not quite sure how we get to caching and template specializations and pretty printers.

If we're still producing the typedef-style DWARF for these alias template specializations - perhaps lldb could not cache pretty printers for typedefs? (I guess the pretty printers shouldn't be typedef-specific, right, since typedefs are transparent anyway - but I guess maybe pretty printers can be typedef-specific because typedefs can be intended to communicate what kind of a thing is and possibly how to render it?) - it'll cache teh pretty printer for the underlying type anyway, yeah?

**Comment by Michael137** [comment]
> If we're still producing the typedef-style DWARF for these alias template specializations - perhaps lldb could not cache pretty printers for typedefs? (I guess the pretty printers shouldn't be typedef-specific, right, since typedefs are transparent anyway - but I guess maybe pretty printers can be typedef-specific because typedefs can be intended to communicate what kind of a thing is and possibly how to render it?) - it'll cache teh pretty printer for the underlying type anyway, yeah?

Basically what was happening is that LLDB saw the new `std::removecv_ref_t<value_type>` member of `std::optional`, which resolved to `std::string`. Then formatted it as `std::string`. And then cached the `DW_AT_name`, i.e., `std::removecv_ref_t<value_type>`, to point to the `std::string` formatter. But that meant that the next time we saw a `std::removecv_ref_t<value_type>` (even if it didn't resolve to `std::string`) would use the cached formatter. The reason this patch works around that situation is that now the `DW_AT_name` will have the canonical type in `DW_AT_name`, not the unresolved `std::removecv_ref_t<value_type>`.

@jimingham will be able to speak more confidently about LLDB's intention here but I think caching typedefs is intentionally supported. Jim and I came to the conclusion yesterday that we probably don't want to cache template specializations.

I think we can (and should) fix the caching behaviour, but that would be a longer undertaking and I wanted to unblock the libc++ patch (https://github.com/llvm/llvm-project/pull/110355) as soon as possible.

It's on my list of follow-ups to reland this and fix the cache (and also investigate what it would take to support `DW_TAG_template_alias` in LLDB, so we can enable those by default).

**Comment by jimingham** [comment]
> On Oct 2, 2024, at 9:22 AM, David Blaikie ***@***.***> wrote:
> 
> 
> Not quite sure how we get to caching and template specializations and pretty printers.
> 
> If we're still producing the typedef-style DWARF for these alias template specializations - perhaps lldb could not cache pretty printers for typedefs? (I guess the pretty printers shouldn't be typedef-specific, right, since typedefs are transparent anyway - but I guess maybe pretty printers can be typedef-specific because typedefs can be intended to communicate what kind of a thing is and possibly how to render it?) - it'll cache teh pretty printer for the underlying type anyway, yeah?
> 
lldb has always allowed you to match formatters to typedef's, regardless of whether something past that typedef in the chain has it's own formatter.  That way, for instance, if you have some constraint you intend for the values of the typedef, you can alert yourself (e.g. color the summary red) when the values don't follow those constraints.  And when you do that you shouldn't have to worry about formatters lower down in the typedef chain.

OTOH, if you have a variable whose immediate type is a typedef that doesn't itself have a formatter match, but that typedef has a type lower in the typedef chain that DOES have a formatter, we will use that formatter for the typedef.  Again, if this typedef is telling the author about some intent for that set of instances of the type, we shouldn't make using typedef's that way annoying by forcing people to recreate the useful formatter every time they introduce such a typedef.  

To be clear, neither of these design decisions is causing any problem here.  The problem comes in here because we try to speed up the type recognizer matching by caching hits we found by inserting the matched type name to the found formatter in our "exact name" lookup table.  In this case, we can save ourselves from having to reconstruct this typedef chain every time we do the match on the original typedef in the future by caching the "original typedef"->"formatter from lower in the typedef chain" as an exact match. 

Normally, that's a fine thing to do, but in this case, we saw a typedef named "std::remove_cv_t<value_type>" that was a typedef for `std::string`.  So we registered std::string as the formatter for the name "std::remove_cv_t<value_type>".  Then the next time we saw something named this way, we found it in our cache and tried to use the `std::string` formatter.  That failed because this time round <value_type> is in fact an "int"...  Prior to this, these templated types wouldn't have had this generic looking name but would have had the resolved type in the name, which wouldn't have been ambiguous.

The narrowest solution is that when you go to cache a type name -> formatter pair, you should  first check whether the type name is generic.  If it is, then you can't guarantee it will resolve to the same base type in the future, so you should not cache it.  IIUC, Michael started down this path but found there wasn't a way to tell straightforwardly whether a type was generic.  Since this is just an optimization, we should first prove to ourselves that failing to put one of these type names in the exact matches really makes enough difference to bother with a complex solution.  If the gains are some but not huge, some boneheaded solution like never caching anything where the from type has a '<' and a '>' is probably sufficient.

Hope that helps...

Jim

**Comment by dwblaikie** [comment]
Thanks @jimingham - yeah, that makes sense. My original argument for being OK with the de-canonicalization of typedefs was that they aren't load bearing anyway. But if lldb puts load on them, that assumption doesn't hold.

Yeah, could check for angles or template parameter DIEs and cache typedef->prettyprinter only if none of those features appear.

**Pull request merged**
