### PR TITLE
LoopVectorize/test: clean up reduction.ll; generate using UTC (NFC)

### PR DESCRIPTION
**Pull request by artagnon**
The test reduction.ll was introduced before utils/update_test_checks.py, and hence contains hand-written CHECK lines. Revisit the test today, and modernize it by:

- Removing extranous attributes on functions and their arguments, as LoopVectorize doesn't even look at these attributes.
- Removing the target datalayout, as it is not essential for LoopVectorize.

Finally, regenerate the CHECK lines using update_test_checks.py, eliminating hand-written error-prone CHECK lines.

### CODE REVIEW

**Comment by nikic** [comment]
> Hardering CHECK-NOT lines to negative-match the vector.body label. This is the practice used in newer files such as iv-select-cmp.ll.

If you're using UTC, there should not be any CHECK-NOT lines.

**Comment by artagnon** [comment]
> If you're using UTC, there should not be any CHECK-NOT lines.

I'm conforming to the practice used in the (recent) iv-select-cmp.ll. I regenerate using UTC, and stage all hunks except the CHECK-NOT checks. I think it's clearer this way: we convey the information that the example is not vectorized, without being overly verbose.

**Comment by nikic** [comment]
We really don't care about verbosity -- only about easy to regenerate tests and clear diffs. Using CHECK-NOT means it's not possible to regenerate the test, which means you lose the primary benefit of using UTC in the first place. If you have to manually fix up the results, you may as well stay with hand-written check lines.

**Comment by artagnon** [comment]
> We really don't care about verbosity -- only about easy to regenerate tests and clear diffs. Using CHECK-NOT means it's not possible to regenerate the test, which means you lose the primary benefit of using UTC in the first place. If you have to manually fix up the results, you may as well stay with hand-written check lines.

Okay, that's a good argument. Fixed now.

**Review by nikic — APPROVED** [review]
LGTM

**Pull request merged**
