### PR TITLE
[clang][ASTMatcher] Handle variable templates in `isInstantiated` and `isInTemplateInstantiation` matchers

### PR DESCRIPTION
**Pull request by frederic-tingaud-sonarsource**
Fix `isInstantiated`  and `isInTemplateInstantiation` matchers, so they return true for instantiations of variable templates, and any declaration in statements contained in such instantiations.

### CODE REVIEW

**Comment by frederic-tingaud-sonarsource** [comment]
@AaronBallman, I think you are the maintainer for this part of the code. Could you help me find somebody who could review the PR?

**Comment by frederic-tingaud-sonarsource** [comment]
Pinging some recent contributors/reviewers to AST Matchers. @danix800, @AaronBallman, @shafik, @PiotrZSL, @steakhal, @cor3ntin

**Review by AaronBallman — APPROVED** [review]
LGTM! Sorry for the delayed review while I was out. No need to re-run the documentation macro because the public interfaces nor doc comments changed, and I think the existing doc comments are sufficient.

Do you need me to land the changes on your behalf?

**Comment by frederic-tingaud-sonarsource** [comment]
Thanks @AaronBallman!
Yes, if you could land the changes, that would be great.

**Pull request merged**
