### PR TITLE
[lldb] Format Python files in scripts and utils

### PR DESCRIPTION
**Pull request by DavidSpickett**
Using:
black --exclude "third_party/" ./lldb/

### CODE REVIEW

**Comment by adrian-prantl** [comment]
Have (should we) we documented that we format all python code with black somewhere and how to install the tool?

**Comment by JDevlieghere** [comment]
> Have (should we) we documented that we format all python code with black somewhere and how to install the tool?

https://llvm.org/docs/CodingStandards.html#python-version-and-source-code-formatting

**Comment by adrian-prantl** [comment]
Oh nice! I was unsuccessfully looking in the LLDb subdir because I had assumed this was LLDB-specific!

**Comment by DavidSpickett** [comment]
I'll be cheeky and assume this is fine to go in.

**Pull request merged**
