### PR TITLE
[WebAssembly] Enable multivalue return when multivalue ABI is used

### PR DESCRIPTION
**Pull request by aheejin**
Multivalue feature of WebAssembly has been standardized for several years now. I think it makes sense to be able to enable it in the feature section by default for our clang/llvm-produced binaries so that the multivalue feature can be used as necessary when necessary within our toolchain and also when running other optimizers (e.g. wasm-opt) after the LLVM code generation.

But some WebAssembly toolchains, such as Emscripten, do not provide both multivalue-returning and not-multivalue-returning versions of libraries. Also allowing the uses of multivalue in the features section does not necessarily mean we generate them whenever we can to the fullest, which is a different code generation / optimization option.

So this makes the lowering of multivalue returns conditional on the use of 'experimental-mv' target ABI. This ABI is turned off by default and turned on by passing `-Xclang -target-abi -Xclang experimental-mv` to `clang`, or `-target-abi experimental-mv` to `clang -cc1` or `llc`.

But the purpose of this PR is not tying the multivalue lowering to this specific 'experimental-mv'. 'experimental-mv' is just one multivalue ABI we currently have, and it is still experimental, meaning it is not very well optimized or tuned for performance. (e.g. it does not have the limitation of the max number of multivalue-lowered values, which can be detrimental to performance.) We may change the name of this ABI, or improve it, or add a new multivalue ABI in the future. Also I heard that WASI is planning to add their multivalue ABI soon. So the plan is, whenever any one of multivalue ABIs is enabled, we enable the lowering of multivalue returns in the backend. We currently have only 'experimental-mv' in the repo so we only check for that in this PR.

Related past discussions:
 #82714
https://github.com/WebAssembly/tool-conventions/pull/223#issuecomment-2008298652

### CODE REVIEW

**Comment by aheejin** [comment]
cc @TerrorJack

**Review by dschuff — APPROVED** [review]
Changes LGTM.
I think the title or commit description should probably mention that this just applies to libcalls (since MV return is already controlled by the ABI option for other calls).

**Comment by aheejin** [comment]
This is effectively a backend-only change and it controls non-libcall multivalue return lowering too (See changes in `WebAssemblyISelLowering.cpp` and `WebAssemblyMachineFunctionInfo.cpp`). We talked about how to relay the frontend's ABI info to the backend but in turned out it is already being passed in `MCTargetOptions`.

This will affect compilation of bitcode files that have struct returns and multivalue-returning invokes (which I tried to ban in #86048). In practice, as you said, unless someone compiles struct-returning bitcode, multivalue returns will not be generated. (And we don't plan to support multivalue-returning invokes in near future) But this change per se doesn't necessarily only apply to libcalls.

**Comment by aheejin** [comment]
This is effectively a backend-only change and it controls non-libcall multivalue return lowering too (See changes in `WebAssemblyISelLowering.cpp` and `WebAssemblyMachineFunctionInfo.cpp`). We talked about how to relay the frontend's ABI info to the backend but in turned out it was already being passed in `MCTargetOptions`.

This will affect compilation of bitcode files that have struct returns and multivalue-returning invokes (which I tried to ban in #86048). In practice, as you said, unless someone compiles struct-returning bitcode, multivalue returns will not be generated. (And we don't plan to support multivalue-returning invokes in near future) But this change per se doesn't necessarily only apply to libcalls.

**Comment by aheejin** [comment]
Sorry that I deleted the previous comments (In case people are reading replies from emails I thought modifying the comment was not gonna be reflected, so I'm writing a new one instead of modifying the previous ones)

This is effectively a backend-only change and it controls non-libcall multivalue return lowering too (See changes in `WebAssemblyISelLowering.cpp` and `WebAssemblyMachineFunctionInfo.cpp`). We talked about how to relay the frontend's ABI info to the backend but in turned out it was already being passed in `MCTargetOptions`.

This will affect compilation of
- Bitcode files that have struct returns
- Multivalue-returning invokes (which I tried to ban in #86048)
- i128-returning functions

In practice there will not be many people who compile bitcodes, and we don't support multivalue-returning invokes anyway, but i128-returning functions will be affected by this change that can't be controlled by the frontend experimental-mv option, which this PR lowers down to pointer-passing returns.

**Comment by TerrorJack** [comment]
@aheejin Thanks a lot for the ping! I have a little question about the impact of this patch, if you wouldn't mind :)

I tried applying this patch in our toolchain and there's now a minor regression. We have a tiny custom patch at [here](https://gitlab.haskell.org/ghc/llvm-project/-/commit/c889836198f0868757c7183b6ad4c7d7bba239dc) to make `experimental-mv` the default ABI as long as `-mmultivalue` is enabled, without needing to pass `-Xclang -target-abi -Xclang experimental-mv` explicitly. However, after this patch is applied, `-Xclang -target-abi -Xclang experimental-mv` becomes mandatory, otherwise i128 and structs regresses to pointer passing.

Maybe I can adjust `canLowerMultivalueReturn()` to remove the `usesMultivalueABI` logic and things will work the way before for us; is this a silly hack, do there exist a more principled way to do it? Thanks a lot in advance.

**Comment by aheejin** [comment]
> Maybe I can adjust `canLowerMultivalueReturn()` to remove the `usesMultivalueABI` logic and things will work the way before for us; is this a silly hack, do there exist a more principled way to do it? Thanks a lot in advance.

If what you want is to achieve the same multivalue-return-lowering behavior without passing `-Xclang -target-abi -Xclang experimental-mv`, I think what you said here is basically the simplest hack to do it. Or you can add `-target-abi experimental-mv` in clang driver programatically whenever `-mmultivalue` is given, but I'm not sure if this is a better hack than what you said.

**Comment by aheejin** [comment]
@TerrorJack But wouldn't it be easier to just modify your build system command and add `-Xclang -target-abi -Xclang experimental-mv` than do a hacky modification in the source code after all?

**Comment by TerrorJack** [comment]
There are other reasons why those flags couldn't be easily added, though that'll distract the discussion here. Anyway thanks for the suggestion @aheejin and this patch doesn't break stuff for us, so feel free to land at your convenience :)

**Review by sunfishcode — APPROVED** [review]

**Pull request merged**
