### PR TITLE
[lldb] Replace the usage of module imp with module importlib

### PR DESCRIPTION
**Pull request by tuliom**
imp got removed in Python 3.12 [1] and the community recommends using importlib in newer Python versions.

[1] https://docs.python.org/3.12/whatsnew/3.12.html#imp

### CODE REVIEW

**Comment by DavidSpickett** [comment]
Do you know when `importlib` was added? I wonder if the overlap is enough to not need a fallback. We appear to advertise a 3.6 or 3.7 minimum in our documentation, and llvm wants >=3.6 (https://llvm.org/docs/GettingStarted.html#software).

@JDevlieghere will know for sure.

**Comment by tuliom** [comment]
[This document](https://docs.python.org/3/library/importlib.html) mentions 3.1.
Many functions were added after 3.6, but none of them are being explicitly used in this patch.
I'm afraid the easiest way to guarantee is by testing with Python 3.6.

**Comment by tuliom** [comment]
I believe it's also important to mention this PR does not solve issue #70453.
But it helps to solve `ModuleNotFoundError: No module named 'imp'` kind of issues.

**Review by bulbazord — COMMENTED** [review]
`importlib` has been around since Python 3.1, maybe we shouldn't have the conditional logic to use `imp` instead? I'm pretty sure the minimum supported version is 3.6 since that's what LLVM requires.

**Comment by JDevlieghere** [comment]
+1, if you can verify that Python 3.6 supports the `importlib` approach we should drop the fallback.

**Comment by tuliom** [comment]
Do you know what is the reason for requiring such an old Python version?
I'm asking because it's been hard to find a distro that provides both Python 3.6 (released in 2016) and cmake 3.20 (released in 2021).

For the record, Ubuntu 18.04 does have Python 3.6, but it has cmake 3.10.

**Comment by bulbazord** [comment]
> Do you know what is the reason for requiring such an old Python version? I'm asking because it's been hard to find a distro that provides both Python 3.6 (released in 2016) and cmake 3.20 (released in 2021).
> 
> For the record, Ubuntu 18.04 does have Python 3.6, but it has cmake 3.10.

The minimum supported version of Python is 3.6 because of the requirements of the `lit` testing tool that llvm uses. It's written completely in python from what I remember. Bumping the minimum required python version would require a discussion on the LLVM Discourse. I would personally like to see the minimum version bumped up, but I don't have time to drive that right now.

The CMake portion is a little easier to manage -- You can build a newer version of CMake on Ubuntu 18.04 (that's what we do downstream for the Swift project).

**Comment by tuliom** [comment]
I confirmed the new code works with Python 3.6 and removed the conditional.

**Review by bulbazord — APPROVED** [review]
Thanks for taking the time to make sure it works with Python 3.6! I'm a big fan of this kind of modernization/cleanup work. 😄

**Review by JDevlieghere — APPROVED** [review]

**Pull request merged**
