### PR TITLE
[GitHub] Add greeting comment to opened PRs from new contributors

### PR DESCRIPTION
**Pull request by DavidSpickett**
This includes some commonly needed information like how to add reviewers.

This is implemented as a job before the labeler, so that on a new PR the comment is added before there are any subscribers and only the author gets a nofitication.

The labeler job depends on the greeter having run or having been skipped. So if the PR wasn't just opened, or it's from a regular contributor, the labeling still happens.

But we can be sure that when a greeting comment is left, it's the very first thing we do.

### CODE REVIEW

**Comment by DavidSpickett** [comment]
While these configurations are pretty fragile and a pain to write, it's readable enough once it works, so I'd prefer to go with this solution. Easier to control notifications this way.

**Comment by DavidSpickett** [comment]
The message content is unchanged from the other PR.

**Comment by kbeyls** [comment]
> What's the difference between FIRST_TIME and FIRST_TIME_CONTRIBUTOR?
> 
> Also a question for @kbeyls - maybe we should note that committing to this repo is a sign that they have accepted the license and our "CLA". Not sure where that's documented right now, but I think it might be good to link to that so people have time to review it before the PR is accepted.

We don't have a CLA, so I'm a bit confused about what you mean by "our CLA"?
If we want to point people to copyright and license information related to their contribution, I guess that https://llvm.org/docs/DeveloperPolicy.html#copyright-license-and-patents might be the best section to point to.

I think I've seen some other projects hosted on github use an auto-commenter like in this PR to point out (and let people tick off that they've understood and agreed with) which license they are contributing their code under.

I think it's probably best to not do this as part of this PR.
Maybe we should aim to get a useful commenter-bot for first-time contributors landed as part of this PR; and then use one or more issues/RFCs on how to further improve the content of the comment? That could list the ideas for e.g. pointing out license/CLA-related information and other stuff.

**Comment by DavidSpickett** [comment]
> What's the difference between FIRST_TIME and FIRST_TIME_CONTRIBUTOR?

Documented in:
https://docs.github.com/en/graphql/reference/enums#commentauthorassociation

FIRST_TIMER is new to GitHub itself, so if you wanted to you could link to more info than someone who is just new to the repository I guess. We cater to both in the docs we have so I checked for either.

**Comment by DavidSpickett** [comment]
ping!

The message content has changed slightly since last time.

**Review by tstellar — APPROVED** [review]

**Pull request merged**
