### PR TITLE
[MLIR][Linalg] Left over Linalg named ops from previous PR

### PR DESCRIPTION
**Pull request by rengolin**
Adding `erf` as unary and `powf` as binary.

Same as `max(arg, 0.0)` for `ReLU`, `powf(arg, const)` can be either a generic (with broadcast) or a pair (`linalg.broadcast + linalg.powf`) and then lowered "correctly". Either way, the lower dialects need to know what kind of broadcast anyway, so no materialization of the constant tensors should remain.

I want to flush the easy ones before we start working on type cast & softmax.

### CODE REVIEW

**Comment by makslevental** [comment]
Random question: is there a lowering path for `erf` to LLVM? Down to an intrinsic I would guess?

**Comment by rengolin** [comment]
> Random question: is there a lowering path for `erf` to LLVM? Down to an intrinsic I would guess?

Linalg's `erf` lowers to a generic with `math.erf` which lowers to libm call with `ScalarOpToLibmCall` like other math calls.

https://github.com/llvm/llvm-project/blob/352602010fac5c7e07bc6b992848ab746d0c2857/mlir/lib/Conversion/MathToLibm/MathToLibm.cpp#L177

Ref: https://en.cppreference.com/w/cpp/numeric/math/erf

**Review by ftynse — APPROVED** [review]

**Comment by MaheshRavishankar** [comment]
> Adding `erf` as unary and `powf` as binary.
> 
> Same as `max(arg, 0.0)` for `ReLU`, `powf(arg, const)` can be either a generic (with broadcast) or a pair (`linalg.broadcast + linalg.powf`) and then lowered "correctly". Either way, the lower dialects need to know what kind of broadcast anyway, so no materialization of the constant tensors should remain.
> 
> I want to flush the easy ones before we start working on type cast & softmax.

I think I am missing some context here. In a previous PR I saw this was based on some round-table discussion. For people who werent there in person can you please post some notes and provide some more context. Specifically, I want to get some more information about what you are refering to w.r.t `softmax` semantics...

**Comment by rengolin** [comment]
> I think I am missing some context here. In a previous PR I saw this was based on some round-table discussion. For people who werent there in person can you please post some notes and provide some more context. Specifically, I want to get some more information about what you are refering to w.r.t `softmax` semantics...

https://discourse.llvm.org/t/notes-from-the-mlir-upstream-round-table-eurollvm-2024/78374

**Comment by MaheshRavishankar** [comment]
> > I think I am missing some context here. In a previous PR I saw this was based on some round-table discussion. For people who werent there in person can you please post some notes and provide some more context. Specifically, I want to get some more information about what you are refering to w.r.t `softmax` semantics...
> 
> https://discourse.llvm.org/t/notes-from-the-mlir-upstream-round-table-eurollvm-2024/78374

I'll need time to digest that. Especially the type issues. I'll try to post my comments on the thread as soon as I can

**Comment by rengolin** [comment]
> I'll need time to digest that. Especially the type issues. I'll try to post my comments on the thread as soon as I can

The type issues are the simple part: we'll use `linalg.copy` for now.

https://discourse.llvm.org/t/rfc-linalg-type-casting/78641

**Pull request merged**
