### PR TITLE
[LLVM] Fix incorrect alignment on AMDGPU variadics

### PR DESCRIPTION
**Pull request by jhuber6**
Summary:
The variadics lowering for AMDGPU puts all the arguments into a void
pointer struct. The current logic dictates that the minimum alignment is
four regardless of what  the underlying type is. This is incorrect in
the following case.

```c
void foo(int, ...);

void bar() {
  int x;
  void *p;
  foo(0, x, p);
}
```
Here, because the minimum alignment is 4, we will only increment the
buffer by 4, resulting in an incorrect alignment when we then try to
access the void pointer. We need to set a minimum of 4, but increase it
to 8 in cases like this.

### CODE REVIEW

**Comment by arsenm** [comment]
> Here, because the minimum alignment is 4, we will only increment the
buffer by 4, 

It should be incrementing by the size? 4 byte aligned access of 8 byte type should work fine

**Comment by jhuber6** [comment]
> > Here, because the minimum alignment is 4, we will only increment the
> > buffer by 4,
> 
> It should be incrementing by the size? 4 byte aligned access of 8 byte type should work fine

Guess that's an AMD thing, so I'm going to assume that @JonChesterfield wrote this intentionally to save on stack space? I suppose the issue I'm having with my `printf` implementation is that we then want to copy this struct and because it doesn't follow natural alignment the person printing it doesn't know where these are stored in a common sense. I suppose I could change the code to just be `ptr += sizeof(T)` instead of doing the alignment, but I feel like some architectures require strict alignment for these and it wouldn't work in the general case.

**Comment by arsenm** [comment]
Incrementing by align is just a bug, of course the size is the real value. Whether we want to continue wasting space is another not-correctness discussion

**Comment by jhuber6** [comment]
> Incrementing by align is just a bug, of course the size is the real value. Whether we want to continue wasting space is another not-correctness discussion

Struct padding is pretty universal, AMDGPU seems the odd one out here. I wouldn't mind it so much if it didn't require me to know which vendor I was dealing with in the RPC implementation, but I suppose I could store that information somewhere if we want to use a compressed option and we know it works.

**Comment by arsenm** [comment]
> > Incrementing by align is just a bug, of course the size is the real value. Whether we want to continue wasting space is another not-correctness discussion
> 
> Struct padding is pretty universal, AMDGPU seems the odd one out here. I wouldn't mind it so much if it didn't require me to know which vendor I was dealing with in the RPC implementation, but I suppose I could store that information somewhere if we want to use a compressed option and we know it works.

It's not about struct padding, but the base alignment. Any pointer increment should be alignTo(ptr + size, align), not += align. The += align won't even work for large structs

**Comment by jhuber6** [comment]
> > > Incrementing by align is just a bug, of course the size is the real value. Whether we want to continue wasting space is another not-correctness discussion
> > 
> > 
> > Struct padding is pretty universal, AMDGPU seems the odd one out here. I wouldn't mind it so much if it didn't require me to know which vendor I was dealing with in the RPC implementation, but I suppose I could store that information somewhere if we want to use a compressed option and we know it works.
> 
> It's not about struct padding, but the base alignment. Any pointer increment should be alignTo(ptr + size, align), not += align. The += align won't even work for large structs

Hm, that's what I'm doing in the `printf` implementation and it doesn't work without that patch. When I look at the varargs struct it didn't have any padding, which explained why `alignTo(ptr + size, align)` was wrong. So, I was trying to do the following, `printf("%d%ld", 1, 1l)`. With this patch I get the following,
```
0xbebebebe00000001
0x0000000000000001
```
Without this patch, I get this. As you can see there's no struct padding so the 8 byte value is right next to the 4 byte one.
```
0x0000000100000001
0xbebebebe00000000
```

**Comment by arsenm** [comment]
> > > > Incrementing by align is just a bug, of course the size is the real value. Whether we want to continue wasting space is another not-correctness discussion
> > > 
> > > 
> > > Struct padding is pretty universal, AMDGPU seems the odd one out here. I wouldn't mind it so much if it didn't require me to know which vendor I was dealing with in the RPC implementation, but I suppose I could store that information somewhere if we want to use a compressed option and we know it works.
> > 
> > 
> > It's not about struct padding, but the base alignment. Any pointer increment should be alignTo(ptr + size, align), not += align. The += align won't even work for large structs
> 
> Hm, that's what I'm doing in the `printf` implementation and it doesn't work without that patch. When I look at the varargs struct it didn't have any padding, which explained why `alignTo(ptr + size, align)` was wrong. So, I was trying to do the following, `printf("%d%ld", 1, 1l)`. With this patch I get the following,

For what IR? Is the small struct getting expanded into individual scalar pieces?

**Comment by jhuber6** [comment]
> > Hm, that's what I'm doing in the `printf` implementation and it doesn't work without that patch. When I look at the varargs struct it didn't have any padding, which explained why `alignTo(ptr + size, align)` was wrong. So, I was trying to do the following, `printf("%d%ld", 1, 1l)`. With this patch I get the following,
> 
> For what IR? Is the small struct getting expanded into individual scalar pieces?

The implementation intentionally states that the alignment is always `4` in this case, which results in there being no padding between the four byte and eight byte values when put into a `void *` buffer for varargs. You should be able to see it in the changes to the tests. Unfortunately, @JonChesterfield is on vacation so I can't ask about this as it seems to be a deliberate choice, but I don't know how it's correct.

**Comment by JonChesterfield** [comment]
This PR is invalid.

First, the alignment on the eight byte pointer is supposed to be four. Increasing it to 8 makes things worse.

Second, I can't see any support for the claim that the code is incrementing by the alignment of the value, as opposed to the size.

The frame is setup as a struct instance with explicit padding by Int8Tys and the calculation there is correct.

The va_arg increment is done in CodeGen:emitVoidPtrVAArg, where DirectSize is ValueInfo.Width, aligned to the 4 byte slot size, then stored. It does not increment the iterator by the alignment of the type.

The lowering pass is doing exactly what was intended.

**Review by JonChesterfield — CHANGES_REQUESTED** [review]
Patch should not land. Need to know what bug this was trying to address to guess at what the right fix would be.

**Comment by jhuber6** [comment]
> Patch should not land. Need to know what bug this was trying to address to guess at what the right fix would be.

My understanding was that the variadics did lowering to a struct with a minimum alignment of four. This currently *doesn't* do that, hence my confusion. The current lowering provides no padding, which I now see is a deliberate choice to save on stack presumably. The issue I had was that I laid out my `printf` code with the assumption that the buffer was a struct, so now it won't work when copied to another target via RPC because it's not the correct alignment.

**Comment by JonChesterfield** [comment]
Ah yes, libc code doing the equivalent of va_arg assuming natural alignment when the underlying buffer is a packed struct with fields padded to four bytes would not work. That would be "fixed" by changing the compiler to match the assumption made by libc, but it seems much better for libc to do the misaligned load instead. Then there's no wavesize*align-padding stack space burned at runtime.

**Comment by jhuber6** [comment]
Lower than native alignment is legal in AMDGPU hardware and it's possible to work around in the `printf` implementation, closing.

**Pull request closed without merging**
