### PR TITLE
[llvm][CodeExtractor] fix bug in parameter naming

### PR DESCRIPTION
**Pull request by tblah**
The code extractor tries to apply the names of source input and output values to function arguments. Not all input and output values get added as arguments: some are instead placed inside of a struct passed to the function. The existing renaming code skipped trying to set these struct-packed arguments names (as there is no corresponding function argument to rename), but it still incremented the iterator over the function arguments. This could result in dereferencing an end iterator if struct-packed inputs/outputs preceded non-struct-packed inputs/outputs.

This patch rewrites this loop to avoid the end iterator dereference.

### CODE REVIEW

**Comment by arsenm** [comment]
The other tests in test/Transforms/CodeExtractor/ look like they all use partial-inliner, check some of those for an example?

**Comment by Meinersbur** [comment]
I think I have a more comprehensive fix here that does not need to introduce new maps to workaround bugs: #114237 Would you review it? I'd rebase it in that case.

A patch that fixes a bug is not NFC.

**Comment by tblah** [comment]
> I think I have a more comprehensive fix here that does not need to introduce new maps to workaround bugs: #114419 Would you review it? I'd rebase it in that case.

Thanks for posting your solution. Your patch does pass my regression test. Can we continue with my patch to get a temporary fix in until you can finish your patch, or would you prefer I close this PR?

**Review by Meinersbur — APPROVED** [review]
LGTM

Can I get an answer to my question whether you are going to review #114419? I am asking out of experience, several people abandoning a final review before, including the author(s) of the bug(s). It's frustrating for all the work put into it.

**Comment by tblah** [comment]
> Can I get an answer to my question whether you are going to review #114419? I am asking out of experience, several people abandoning a final review before, including the author(s) of the bug(s). It's frustrating for all the work put into it.

I will do my best but I think we also need at least one reviewer with some experience in this area.

**Comment by pawosm-arm** [comment]
> > Can I get an answer to my question whether you are going to review #114419? I am asking out of experience, several people abandoning a final review before, including the author(s) of the bug(s). It's frustrating for all the work put into it.
> 
> I will do my best but I think we also need at least one reviewer with some experience in this area.

Finding reviewers for that one would go easier if the PR message could be updated slightly. I had to visit several Phabricator tickets and I'm still not sure what is the proposal there and what is the extension of other proposal (and what was the fate of the original proposal). Many potential candidates would scratch their heads several time before deciding to participate.

**Pull request merged**
