### PR TITLE
[lld][WebAssembly] Move input vectors from symtab to ctx. NFC

### PR DESCRIPTION
**Pull request by sbc100**
Also convert from std::vector to SmallVector.

This matches the ELF linker where these were moved into the ctx object in 9a572164d592e and converted to SmallVector in ba948c5a9c524b.

### CODE REVIEW

**Review by MaskRay — APPROVED** [review]
LGTM!

There is probably still a long time to make the code base more amenable to library users.

**Comment by steven-johnson** [comment]
This change has apparently injected crashes in Halide when we use LLD in library form for WebAssembly... SISGSEV in calls to MarkLive::enqueueInitFunctions:

```
std::__u::vector<llvm::wasm::WasmInitFunc, std::__u::allocator<llvm::wasm::WasmInitFunc> >::begin (this=0x5959595959595bb1)
    at third_party/crosstool/v18/stable/toolchain/bin/../include/c++/v1/vector:1375
1375	  return __make_iter(this->__begin_);
(gdb) bt
#0  std::__u::vector<llvm::wasm::WasmInitFunc, std::__u::allocator<llvm::wasm::WasmInitFunc> >::begin (this=0x5959595959595bb1)
    at third_party/crosstool/v18/stable/toolchain/bin/../include/c++/v1/vector:1375
#1  0x0000555566472e4d in lld::wasm::(anonymous namespace)::MarkLive::enqueueInitFunctions (this=0x7fffffff4f30, obj=0x25c8bf7f8000)
    at third_party/llvm/llvm-project/lld/wasm/MarkLive.cpp:79
#2  0x0000555566472a7a in lld::wasm::(anonymous namespace)::MarkLive::run (this=0x7fffffff4f30)
    at third_party/llvm/llvm-project/lld/wasm/MarkLive.cpp:102
#3  0x000055556647182a in lld::wasm::markLive () at third_party/llvm/llvm-project/lld/wasm/MarkLive.cpp:150
#4  0x00005555663f4db2 in lld::wasm::(anonymous namespace)::LinkerDriver::linkerMain (this=0x7fffffff66e0, argsArr=...)
    at third_party/llvm/llvm-project/lld/wasm/Driver.cpp:1328
#5  0x00005555663f2a72 in lld::wasm::link (args=..., stdoutOS=..., stderrOS=..., exitEarly=false, disableOutput=false)
    at third_party/llvm/llvm-project/lld/wasm/Driver.cpp:101
#6  0x000055556653252a in lld::unsafeLldMain (args=..., stdoutOS=..., stderrOS=..., drivers=..., exitEarly=false)
    at third_party/llvm/llvm-project/lld/Common/DriverDispatcher.cpp:163
#7  0x0000555566533b49 in lld::lldMain(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, llvm::ArrayRef<lld::DriverDef>)::$_0::operator()() const (this=0x7fffffff7190) at third_party/llvm/llvm-project/lld/Common/DriverDispatcher.cpp:188
#8  0x0000555566533a8c in llvm::function_ref<void ()>::callback_fn<lld::lldMain(llvm::ArrayRef<char const*>, llvm::raw_ostream&, llvm::raw_ostream&, llvm::ArrayRef<lld::DriverDef>)::$_0>(long) (callable=140737488318864) at third_party/llvm/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:45
#9  0x000055556d8b0ea0 in llvm::function_ref<void ()>::operator()() const (this=0x7fffffff7108)
    at third_party/llvm/llvm-project/llvm/include/llvm/ADT/STLFunctionalExtras.h:68
#10 0x000055556eaacbf6 in llvm::CrashRecoveryContext::RunSafely(llvm::function_ref<void ()>) (this=0x7fffffff71c8, Fn=...)
    at third_party/llvm/llvm-project/llvm/lib/Support/CrashRecoveryContext.cpp:426
#11 0x0000555566532753 in lld::lldMain (args=..., stdoutOS=..., stderrOS=..., drivers=...)
    at third_party/llvm/llvm-project/lld/Common/DriverDispatcher.cpp:187
```

**Comment by steven-johnson** [comment]
...hmm, do we ever clear those newly added vectors in `Ctx`? We call the linker multiple times, maybe there are stale entries that build up.

**Comment by steven-johnson** [comment]
Yep, that's it, if I clear those reset the Ctx to initial state at the top of each call to link() it heals it. I'll prep a PR if no one is already doing so.

**Comment by steven-johnson** [comment]
(The ELF linker might need a similar fix?)

**Comment by sbc100** [comment]
The ELF linker already handles clearing all the stuff.

I think the fix is straight forward, but writing tests is the tricky part.. I'll see how this is tested in ELF and try to replicate.

**Comment by steven-johnson** [comment]
Ah, OK: I'll skip the PR if you are already on it.

**Comment by steven-johnson** [comment]
(But may I suggest that a quick fix-or-rollback would be appropriate if adding tests will take a while, because in this state, using wasm-lld as a library is extremely broken.)

**Pull request merged**
