### PR TITLE
[RISCV] Move Machine Copy Propagation Pass before Branch relaxation pass

### PR DESCRIPTION
**Pull request by Yunzezhu94**
Machine Copy Propagation Pass may enlarge branch relaxation distance by breaking generation of compressed insts. This commit moves Machine Copy Propagation Pass before Branch relaxation pass so the results of Branch relaxation pass won't be affected by Machine Copy Propagation Pass.

### CODE REVIEW

**Comment by wangpc-pp** [comment]
Can you add your error case too?

**Comment by Yunzezhu94** [comment]
> Can you add your error case too?

I'm afraid not since I met the problem with llvm at earlier point and the case reports error only when the original relocation distance reaches maximum bound. For somehow newer changes makes the relocation distance differ and the same case not reporting the error.

**Comment by Yunzezhu94** [comment]
> Can you add your error case too?

I'm afraid not since I met the problem with llvm at earlier point and the case reports error only when the original relocation distance reaches maximum bound. For somehow newer changes makes the relocation distance differ and the same case not reporting the error.

**Review by topperc — APPROVED** [review]
LGTM

**Pull request merged**
