### PR TITLE
Recommit "[FunctionAttrs] deduce attr `cold` on functions if all CG paths call a `cold` function"

### PR DESCRIPTION
**Pull request by goldsteinn**
- **[CompilerRT] Refactor checks in uar.cpp test; NFC**
- **Recommit "[FunctionAttrs] deduce attr `cold` on functions if all CG paths call a `cold` function"**

Fixed up the uar test that was failing. It seems with the new `cold`
attribute the order of the functions is different. As far as I can
tell this is not a concern.

### CODE REVIEW

**Comment by nikic** [comment]
> Fixed up the uar test that was failing. It seems with the new `cold`
> attribute the order of the functions is different. As far as I can
> tell this is not a concern.

If it's just an order difference, maybe it would be better to just use CHECK-DAG instead?

**Review by melver — APPROVED** [review]
LGTM for UAR test.
I leave it to you if you want to use CHECK-DAG or the current version. I'd err on the side of keeping it closer to the original version, as long as there won't be further changes that result in non-deterministic or constantly changing code gen.

**Comment by goldsteinn** [comment]
> LGTM for UAR test. I leave it to you if you want to use CHECK-DAG or the current version. I'd err on the side of keeping it closer to the original version, as long as there won't be further changes that result in non-deterministic or constantly changing code gen.

I'm inclined to do `CHECK-DAG`. I wouldn't bet this is the last time the attributes will change and its a non-obvious failure.

**Comment by asmok-g** [comment]
Heads-up: we're seeing probable miscompile in a google test after this commit. Working on a reproducer.

**Comment by goldsteinn** [comment]
> Heads-up: we're seeing probable miscompile in a google test after this commit. Working on a reproducer.

Gotten a repro yet?

**Pull request closed without merging**
