### PR TITLE
[DebugInfo][InstCombine] When replacing bswap idiom, add DebugLoc to new insts

### PR DESCRIPTION
**Pull request by SLTozer**
Currently when InstCombineAndOrXor recognizes a bswap idiom and replaces it with an intrinsic and other instructions, only the last instruction gets the DebugLoc of the replaced instruction set to it. This patch applies the DebugLoc to all the generated instructions, to maintain some degree of attribution.

Found using https://github.com/llvm/llvm-project/pull/107279.

### CODE REVIEW

**Review by adrian-prantl — APPROVED** [review]

**Comment by dwblaikie** [comment]
Should/does this use a merged location? (the test and patch description mention several instructions being replaced by several other instructions - so sounds like the new instructions should get the merged location of all the old instructions? But not clear if that's what's happening, or just the last of the old instructions is used as the location for the new ones?)

**Comment by SLTozer** [comment]
> Should/does this use a merged location? (the test and patch description mention several instructions being replaced by several other instructions - so sounds like the new instructions should get the merged location of all the old instructions? But not clear if that's what's happening, or just the last of the old instructions is used as the location for the new ones?)

That's a good question, and one that applies to some other patches I've worked/am working on. I don't think we have a well-defined approach to handling locations in optimizations that rewrite multiple instructions into a set of new instructions that compute the same end result. Merging all the locations and applying the merged location to each new instruction is one option; it feels like a truthful representation, but is also slightly disappointing in that in many cases it means setting a line 0 location.

I think there's a reasonable argument for using the location of the final instruction(s) for all new generated instructions, because all the new instructions exist to compute the value previously computed by that final instruction(s), and they otherwise have no exact relationship to any single instruction in the original program. This is what I lean more towards right now, as I think it's as valid in principle as the merged location and more pragmatically useful, but that's not a strong position - very much interested in hearing other opinions on this, and possibly encoding them for posterity in the "How To Update Debug Info" doc.

**Comment by dwblaikie** [comment]
> I don't think we have a well-defined approach to handling locations in optimizations that rewrite multiple instructions into a set of new instructions that compute the same end result. Merging all the locations and applying the merged location to each new instruction is one option; it feels like a truthful representation, but is also slightly disappointing in that in many cases it means setting a line 0 location.

Agreed it's disappointing - but I'm not sure how to argue against it - if we considered the case where multiple instructions were replaced with one instruction, I think our documented process is pretty clear that we should merge locations there, right? So why would it be so different if the result is multiple instructions?

We could add some special case to merging - if all the instructions to be merged are in the same basic block, perhaps we could say in that case we pick the last instruction if the merge would be worse in some way? (I guess at that point the rule is just "pick the last") - the loss there is we lose other source locations to break on. (though I guess that's true if we drop the location too)

**Comment by SLTozer** [comment]
> if we considered the case where multiple instructions were replaced with one instruction, I think our documented process is pretty clear that we should merge locations there, right?

Hm, you're right that this is the documented rule - I went into this thinking this case was more ambiguous, because in InstCombine that rule isn't always strictly followed: we perform peephole optimizations that may replace multiple instructions with a single instruction that uses the location of the final replaced instruction.

For this patch I'm happy to switch back to use merged locations to keep it consistent with the existing rules, but I think the rule should be different: my short proposal would be that when replacing a sequence of instructions, where there are no side-effects and only one instruction's output is being replaced by the new instruction(s), we should use the output instruction's location for the instruction(s) inserted to replace it. That's a discussion that should happen elsewhere (either an RFC or another review), but I think it's probably worth having. In the meanwhile, I'll update this patch!

**Comment by SLTozer** [comment]
> FWIW, I think that trying to use a merged location rather than the location of the last instruction in InstCombine would be completely impractical.

I agree, notably with this patch we will use merged locations for all the new instructions generated _except_ for the final instruction that we RAUW the original instruction with, which will take the original instruction's location as always - so this patch will only apply to the new instructions generated in the course of creating the replacement instruction.

**Comment by dwblaikie** [comment]
In terms of a policy change - I could see an argument for "we didn't merge these instructions, we replaced the last instruction with some other instruction and optimized the rest of the instructions away" - though how do we differentiate these cases, does this apply to every "merged" instruction? 

Oh, I guess there's a real difference here - merged instructions that come from things like hoisting and lowering (we took two equivalent instructions in different branches and effectively deduplicated them at some common point before or after) versus we took a series of instructions and collapsed them into one.

Perhaps we could say in the latter case, we always use the location of the final instruction in the original sequence? (do we define fallbacks? if that final instruction doesn't have a location we should use one of the others? If they're in the same basic block? (though sounds like you folks would be pushing back on implementing such a fallback here as tracking the set of locations that flow into this transformation is too expensive?))

**Comment by SLTozer** [comment]
Right, I think a slightly more detailed form of the policy I'd suggest would be that every original instruction whose outputs/side-effects are produced by the new instructions is interesting, and the location for the new instructions should be the merge of all interesting instructions. So for example,

- In most peephole optimizations, we would only use the final instruction's location, because that is the only instruction that the new instructions are reproducing.
- When we hoist and merge equivalent instructions from both sides of a branch, the new instruction is reproducing both of the original instructions, so we'd use a merged location.
- If we merged two adds into a single vector add, the vector add would use a merged location because it's defining the combined value of the original adds.

I'm not sure about using other instructions as fallbacks if the sole interesting instruction has a missing location; it seems like it might help salvage _some_ information where we would otherwise have none, I'd just want to be sure there aren't cases where it would be misleading.

**Comment by dwblaikie** [comment]
> Right, I think a slightly more detailed form of the policy I'd suggest would be that every original instruction whose outputs/side-effects are produced by the new instructions is interesting, and the location for the new instructions should be the merge of all interesting instructions. So for example,
> 
> * In most peephole optimizations, we would only use the final instruction's location, because that is the only instruction that the new instructions are reproducing.
> * When we hoist and merge equivalent instructions from both sides of a branch, the new instruction is reproducing both of the original instructions, so we'd use a merged location.
> * If we merged two adds into a single vector add, the vector add would use a merged location because it's defining the combined value of the original adds.
> 
> I'm not sure about using other instructions as fallbacks if the sole interesting instruction has a missing location; it seems like it might help salvage _some_ information where we would otherwise have none, I'd just want to be sure there aren't cases where it would be misleading.

Sounds good to me. (re: merging two adds - for a sec I was confused, I thought you were describing (a + (b + c)) - in which case it sounded more like the peephole description, but you meant merging ((a1 + b1), (a2 + b2)) into ((a1, a2) + (b1, b2)) ? Yeah, that looks like the function call merging, the instruction is producing the results of both the original instructions)

**Comment by adrian-prantl** [comment]
@SLTozer Can you propose a patch to https://llvm.org/docs/HowToUpdateDebugInfo.html#when-to-merge-instruction-locations?

**Comment by dwblaikie** [comment]
Perhaps the simplest way to think of it is that replacing, say "add(a, add(b, c))" with "add(a, b, c)" isn't /replacing/ the second add, so it's not merging two adds, it's only replacing the outer add - which has the effect of adding a, b, and c (initially by relying on the result of the add(b, c), but then without relying on that anymore - the add(b, c) might still continue to exist, be used by other things, etc.

So it might be more consistent with our existing guidance than it first apperas - still good to write it up, but that might be a way to describe it that makes the unifying principles simpler/clearer as to why this conclusion applies.

**Comment by SLTozer** [comment]
That's how I'm thinking about it, I just think the term "replace" is a bit tricky since by most appearances, the intermediate instructions are being replaced by the folded instruction. Also, the existing policy explicitly states that mul+add=>fma should use a merged location, so changing that at least is a change in policy.

**Comment by SLTozer** [comment]
The policy change patch https://github.com/llvm/llvm-project/pull/115349 hasn't landed yet, but the principle seems to be approved of - in which case, is this patch approved to land?

**Comment by dwblaikie** [comment]
My main concern is addressed.

Looking at the code though, I'm a little confused - one instruction, `I` is replaced with some sequence of instructions, by the looks of it - and /all/ those new instructions are given the old instruction's debug location? What are cases where the replacement is more than one instruction? Is it right to give all the new instructions the same location? I guess it's probably fine, but does feel a bit weird & not entirely consistent with the new policy we've discussed, where only the instruction that produces the final result that matches the original instruction should have the new location, I guess, maybe?

**Comment by SLTozer** [comment]
> I guess it's probably fine, but does feel a bit weird & not entirely consistent with the new policy we've discussed, where only the instruction that produces the final result that matches the original instruction should have the new location, I guess, maybe?

There might have been some ambiguity in the explanation; the new example on the policy update I gave covers this a bit more directly, but it could be made more explicit. As I see it, the set of new instructions that, in sequence, produce the final value of the old instruction(s) that we're replacing, should all be assigned the location of the replaced instruction (or the merge of those locations if there were multiple). The reason for this is the same as in cases where we lower an IR instruction into multiple MIR/assembly instructions and apply its DebugLoc to all of them: even if we create multiple instructions, they're all working towards the single output value.

**Comment by dwblaikie** [comment]
> > I guess it's probably fine, but does feel a bit weird & not entirely consistent with the new policy we've discussed, where only the instruction that produces the final result that matches the original instruction should have the new location, I guess, maybe?
> 
> There might have been some ambiguity in the explanation; the new example on the policy update I gave covers this a bit more directly, but it could be made more explicit. As I see it, the set of new instructions that, in sequence, produce the final value of the old instruction(s) that we're replacing, should all be assigned the location of the replaced instruction (or the merge of those locations if there were multiple). The reason for this is the same as in cases where we lower an IR instruction into multiple MIR/assembly instructions and apply its DebugLoc to all of them: even if we create multiple instructions, they're all working towards the single output value.

Fair enough - I can go with that. Sorry if I missed that in the policy wording update.

**Review by dwblaikie — APPROVED** [review]

**Pull request merged**
