### PR TITLE
Fix for logic in combineExtract()

### PR DESCRIPTION
**Pull request by JonPsson1**
A (csmith) test case appeared where combineExtract() crashed when the input vector was a bitcast into a vector of i1:s. Add a check using canTreatAsByteVector() for the immediate (first) Op as well. This takes care of (avoids) this case and does not seem to change any benchmarks or tests.

In this i1 vector case the logic gets confused: 'End' becomes 128 (bytes), so the 'Op.getOperand(End / OpBytesPerElement - 1)' call uses an argument of 15, but Op is 'v2i64 = BUILD_VECTOR Constant:i64<3>, Constant:i64<3>'.

### CODE REVIEW

**Comment by uweigand** [comment]
Hmm, I think the intent was for the type of the initial `Op` to be deliberately ignores, as it is supposed to be considered implicitly bitcast to `VecVT`.   But it is true that the routine assumes that `VecVT` must be a byte vector.  One of the two call sites (in combineTruncateExtract) ensures that, but the other call site (in combineEXTRACT_VECTOR_ELT) does not.  So I think the better fix would be to add a check to that call site instead.

**Comment by JonPsson1** [comment]
I guess I am a little confused here as to the lack of the bytevector check for BITCAST inside combineExtract(). Couldn't it at least in theory be that - as this is in a loop - there are more BITCASTs reached which could then involve i1 vectors?

**Comment by uweigand** [comment]
I still don't think we need a check for the BITCAST case; it shouldn't matter what the resulting type is.  The important thing is that
- wherever the type of `Op` is actually *used*, it is verified to be a byte type (this is already done); and
- the desired output type `VecVT` (including the `Index` which is based on `VecVT`) is a byte type - *this* is where we have a problem as it is only validated by one caller but not the other

In your test case, the cause of the crash is that `Index` (which comes from the caller) is based on a i1 vector type in `VecVT` - this is the actual bug.  Once we fix the caller, that problem should be resolved.

**Comment by JonPsson1** [comment]
ok, I think I get it now: there is a special check for this in each of the different handlings that would follow a BITCAST handling, so that should not be a problem. Patch updated per your suggestion.

**Review by uweigand — APPROVED** [review]
LGTM now

**Pull request merged**
