### PR TITLE
[clang] Reject if constexpr in C

### LINKED ISSUE #112587: [Clang] Clang erroneously allows `if constexpr` in C23 mode
See https://godbolt.org/z/E8PEzzfP3. According to @AaronBallman, this isn’t intentional, so we should probably disallow this.

### PR DESCRIPTION
**Pull request by Fznamznon**
Fixes https://github.com/llvm/llvm-project/issues/112587

### CODE REVIEW

**Review by cor3ntin — APPROVED** [review]
LGTM - I think we should backport that to 19 (so we don't need a changelog)

**Review by AaronBallman — APPROVED** [review]
LGTM!

**Comment by AaronBallman** [comment]
> LGTM - I think we should backport that to 19 (so we don't need a changelog)

Agreed

**Comment by Fznamznon** [comment]
*sobs while doing manual cherry-pick*

**Comment by Fznamznon** [comment]
https://github.com/llvm/llvm-project/pull/112697

**Pull request merged**
