### PR TITLE
[Clang][AArch64] Use __clang_arm_builtin_alias for overloaded svreinterpret's

### PR DESCRIPTION
**Pull request by sdesmalen-arm**
The intrinsics are currently defined as:

```
  __aio __attribute__((target("sve")))
  svint8_t svreinterpret_s8(svuint8_t op) __arm_streaming_compatible {
    return __builtin_sve_reinterpret_s8_u8(op);
  }
```

which doesn't work when calling it from an __arm_streaming function when only +sme is available. By defining it in the same way as we've defined all the other intrinsics, we can leave it to the code in SemaChecking to verify that either +sve or +sme is available.

This PR also fixes the target guards for the svreinterpret_c and svreinterpret_b intrinsics, that convert between svcount_t and svbool_t, as these are available both in SME2 and SVE2p1.

### CODE REVIEW

**Comment by rsandifo-arm** [comment]
> However we choose to emit this particular builtin, should we provide a way to write a function like this? Like, the caller has to either support sve, or have streaming enabled. Maybe call it __arm_streaming_compatible_requires_sve.

I'd like to make two (probably obvious) points before answering this:

* The existing three-way choice between normal, `__arm_streaming`, and `__arm_streaming_compatible` is simply a choice between possible incoming and outgoing PSTATE.SM states at runtime (0, 1, and 0 or 1, respectively).  It's intended to be independent of the architecture level, except for the fact that using `__arm_streaming` is an error when SME is not enabled.

* If `__arm_streaming_compatible` is being used to write a vector routine, the question isn't likely to be just “do I have SVE?” but “do I have this particular set of SVE features”?  For example, I imagine many integer-based algorithms would want at least SVE2.  At some point SVE2p1 would become a baseline for some users.

So if someone wants to say both “this function should be streaming-compatible” and “this function assumes it has access to these streaming SVE features” then I think those things should be specified as two separate annotations, rather than a single combined one.  The second one (about assuming/requiring available features) is useful more generally, for non-streaming and `__arm_streaming` as well as `__arm_streaming_compatible`.

**Comment by efriedma-quic** [comment]
The key here is that `__arm_streaming_compatible` is the only way to write code that runs in both streaming and non-streaming  mode; outside of `__arm_streaming_compatible`, there generally isn't an issue. If you know you're not in streaming mode, you can just check directly for SVE/SVE2, and if you know you're in streaming mode, you can check directly for SME/SME2.

Thinking about it a bit more, maybe we can just do some magic to make things work?  Say, if you specify `__attribute__((target("sve"))) __arm_streaming_compatible`, and the caller is in streaming mode, allow the call even if the caller doesn't have SVE proper.

**Comment by efriedma-quic** [comment]
> Thinking about it a bit more, maybe we can just do some magic to make things work? Say, if you specify `__attribute__((target("sve"))) __arm_streaming_compatible`, and the caller is in streaming mode, allow the call even if the caller doesn't have SVE proper.

Thinking a bit more, this is probably not quite what we want: even if the function body itself is streaming compatible, it might call non-streaming functions that require SVE.  Maybe spell this something like `__attribute__((target("sve-or-streaming"))) __arm_streaming_compatible`.

**Comment by rsandifo-arm** [comment]
> > Thinking about it a bit more, maybe we can just do some magic to make things work? Say, if you specify `__attribute__((target("sve"))) __arm_streaming_compatible`, and the caller is in streaming mode, allow the call even if the caller doesn't have SVE proper.
> 
> Thinking a bit more, this is probably not quite what we want: even if the function body itself is streaming compatible, it might call non-streaming functions that require SVE. Maybe spell this something like `__attribute__((target("sve-or-streaming"))) __arm_streaming_compatible`.

I suppose the idea here is that:
```
   __attribute__((target("sve"))) void f() { … }
   void g() { … f(); … }
```
should be diagnosed, on the basis that, when compiled with default flags, `g` doesn't guarantee the availability of SVE, whereas `f` requires it?  If so, I don't think we should do that, for two reasons:

First, it's IMO valid to do:
```
   __attribute__((target("sve"))) void sve_routine() { … }
   void main_interface() {
     if (SVE_is_available() && problem_has_certain_characteristics())
       sve_routine();
     else
       …
   }
```
That is, feature gating can be dynamic.  It doesn't need to be a load-time thing.

Second, at least in GCC, the `target` attribute is not part of a function's type, so it's not an error to do:
```
foo.h: void f();
foo.cc: __attribute__((target("sve"))) void f() { … }
```
And I'd argue that that's a feature rather than a bug.  It allows load-time selection of DSOs based on the target.

**Comment by efriedma-quic** [comment]
clang specifically diagnoses always_inline functions.  So for example, say you want to write something like:

```
#include <arm_sve.h>
__attribute__((always_inline, target("+sve")))
static inline void f(void* p) __arm_streaming_compatible {
  *(svuint32_t*)p = svmul_m(svptrue_b32(), *(svuint32_t*)p, *(svuint32_t*)p);
}
//////////
void g(void* p) __arm_streaming { f(p); }
```

Conceptually, this should be fine, but currently it's an error.  (You can sort of approximate it with an `#ifdef __ARM_FEATURE_SVE`, but that's pretty ugly.)

But regardless of the diagnostics, if the user specifies "+sve" on a target that doesn't actually have SVE, we could miscompile; for example, if you call a versioned function, clang uses the features specified in the caller.

**Comment by rsandifo-arm** [comment]
> clang specifically diagnoses always_inline functions. So for example, say you want to write something like:
> 
> ```
> #include <arm_sve.h>
> __attribute__((always_inline, target("+sve")))
> static inline void f(void* p) __arm_streaming_compatible {
>   *(svuint32_t*)p = svmul_m(svptrue_b32(), *(svuint32_t*)p, *(svuint32_t*)p);
> }
> //////////
> void g(void* p) __arm_streaming { f(p); }
> ```
> 
> Conceptually, this should be fine, but currently it's an error. (You can sort of approximate it with an `#ifdef __ARM_FEATURE_SVE`, but that's pretty ugly.)

Yeah.  I think in GCC, the reason for the equivalent behaviour is that (a) the compiler assumes (without checking) that the contents really do require the given target and (b) the compiler doesn't support changes to the ISA within a function.  So the error is that the target mismatch caused inlining to fail, rather than that the mismatch occurred at all.

> But regardless of the diagnostics, if the user specifies "+sve" on a target that doesn't actually have SVE, we could miscompile; for example, if you call a versioned function, clang uses the features specified in the caller.

That's a good point.  I suppose it comes down to two fundamentally different use cases:

1. A function that can be called in either PSTATE.SM mode and “just work”.  This is what `__arm_streaming_compatible` is currently supposed to provide.  That is, what the function can do is determined by where the function can be called (which is anywhere).
2. A function that cannot be called with PSTATE.SM==0 on targets that have SME but not SVE.  That is, where the function can be called is determined by what the function can do.

Perhaps (2) could be called “streaming SVE functions”.  If the compiler is supposed to enforce the constraints, then the set of assumed streaming SVE features would need to be a property of the function type.

**Review by paulwalker-arm — APPROVED** [review]

**Pull request merged**
