### PR TITLE
CMake: Remove unnecessary dependencies on LLVM/MLIR

### PR DESCRIPTION
**Pull request by Adnios**
There are some spurious libraries which can be removed.

I'm trying to bundle MLIR/LLVM library dependencies for our own libraries. We're utilizing cmake function to recursively collect MLIR/LLVM related dependencies. However, we identified certain library dependencies as redundant and safe for removal.

### CODE REVIEW

**Comment by joker-eph** [comment]
LGTM, let’s keep an eye on the post-merge bot, this is the kind of things that can fail only on some configs.

**Comment by banach-space** [comment]
Thanks @Adnios , nice clean-up! Out of curiosity, how did you identify these? Manually or automatically?

Note that pre-commit is unhappy. I couldn't find the actual error in the Linux job. The one for Windows reports:
```bash
VMemoryBuffer@llvm@@U?$default_delete@VMemoryBuffer@llvm@@@std@@@std@@@Z)
--
  | unittests\ProfileData\ProfileDataTests.exe : fatal error LNK1120: 1 unresolved externals
```

**Comment by Adnios** [comment]
Thanks for catching. 

> how did you identify these? Manually or automatically?

Firstly I follow [this blog](https://cristianadam.eu/20190501/bundling-together-static-libraries-with-cmake/) to recursively collect MLIR/LLVM related dependencies for our own library (libMy.a) or binary (MyBinary). (And print the dependencies tree for better visualization)

E.g:
```
....
|  |  |  |  |  |  |--MLIRArithDialect(depth:6, dep_count:8)
|  |  |  |  |  |  |  |--MLIRCastInterfaces(depth:7, dep_count:2)
|  |  |  |  |  |  |  |--MLIRDialect(depth:7, dep_count:2)
|  |  |  |  |  |  |  |--MLIRInferIntRangeCommon(depth:7, dep_count:3)
|  |  |  |  |  |  |  |  |--MLIRInferIntRangeInterface(depth:8, dep_count:2)
|  |  |  |  |  |  |  |--MLIRInferTypeOpInterface(depth:7, dep_count:2)
|  |  |  |  |  |  |  |--MLIRUBDialect(depth:7, dep_count:2)
|  |  |  |  |  |--MLIRLLVMDialect(depth:5, dep_count:15)
|  |  |  |  |  |  |--MLIRCallInterfaces(depth:6, dep_count:2)
|  |  |  |  |  |  |--MLIRControlFlowInterfaces(depth:6, dep_count:2)
|  |  |  |  |  |  |--MLIRDataLayoutInterfaces(depth:6, dep_count:2)
|  |  |  |  |  |  |--MLIRFunctionInterfaces(depth:6, dep_count:2)
|  |  |  |  |  |  |--MLIRMemorySlotInterfaces(depth:6, dep_count:2)
|  |  |  |  |  |  |--MLIRSideEffectInterfaces(depth:6, dep_count:2)
|  |  |  |  |  |  |--LLVMAsmParser(depth:6, dep_count:3)
|  |  |  |  |  |  |  |--LLVMBinaryFormat(depth:7, dep_count:2)
|  |  |  |  |  |  |  |  |--LLVMTargetParser(depth:8, dep_count:1)
|  |  |  |  |  |  |  |--LLVMCore(depth:7, dep_count:8)
|  |  |  |  |  |  |  |  |--LLVMRemarks(depth:8, dep_count:2)
...
```

Meanwhile, I also try dump the linker map of binary (MyBinary) by adding following code to CMakeLists.txt.
```
set(MyBinary_LINKER_MAP_FILE ${CMAKE_CURRENT_BINARY_DIR}/MyBinary.map)
target_link_options(MyBinary PRIVATE LINKER:-Map=${MyBinary_LINKER_MAP_FILE})
```

Then use regex to extract all libMLIR/LLVM*.a from MyBinary.map. By comparing these with the dependencies obtained from CMake functions and linker maps, I notice that the "linker map" method has fewer dependencies and eliminates unnecessary libraries.

Then I start manually remove this unneeded libraries in CMakeLists.txt and open this PR.

**Comment by joker-eph** [comment]
Still failing on windows:

 _bk;t=1727545482016LINK: command "C:\BuildTools\VC\Tools\MSVC\14.29.30133\bin\Hostx64\x64\link.exe /nologo unittests\ProfileData\CMakeFiles\ProfileDataTests.dir\BPFunctionNodeTest.cpp.obj unittests\ProfileData\CMakeFiles\ProfileDataTests.dir\CoverageMappingTest.cpp.obj unittests\ProfileData\CMakeFiles\ProfileDataTests.dir\InstrProfDataTest.cpp.obj unittests\ProfileData\CMakeFiles\ProfileDataTests.dir\InstrProfTest.cpp.obj unittests\ProfileData\CMakeFiles\ProfileDataTests.dir\ItaniumManglingCanonicalizerTest.cpp.obj unittests\ProfileData\CMakeFiles\ProfileDataTests.dir\MemProfTest.cpp.obj unittests\ProfileData\CMakeFiles\ProfileDataTests.dir\PGOCtxProfReaderWriterTest.cpp.obj unittests\ProfileData\CMakeFiles\ProfileDataTests.dir\SampleProfTest.cpp.obj unittests\ProfileData\CMakeFiles\ProfileDataTests.dir\SymbolRemappingReaderTest.cpp.obj unittests\ProfileData\CMakeFiles\ProfileDataTests.dir\__\__\resources\windows_version_resource.rc.res /out:unittests\ProfileData\ProfileDataTests.exe /implib:unittests\ProfileData\ProfileDataTests.lib /pdb:unittests\ProfileData\ProfileDataTests.pdb /version:0.0 /MANIFEST:NO /STACK:10000000 /INCREMENTAL:NO /subsystem:console lib\LLVMBitReader.lib lib\LLVMCore.lib lib\LLVMCoverage.lib lib\LLVMProfileData.lib lib\LLVMSupport.lib lib\LLVMObject.lib lib\LLVMSupport.lib lib\llvm_gtest_main.lib lib\llvm_gtest.lib lib\LLVMTestingSupport.lib lib\LLVMDebugInfoDWARF.lib lib\LLVMObject.lib lib\LLVMIRReader.lib lib\LLVMBitReader.lib lib\LLVMAsmParser.lib lib\LLVMCore.lib lib\LLVMRemarks.lib lib\LLVMBitstreamReader.lib lib\LLVMMCParser.lib lib\LLVMMC.lib lib\LLVMTextAPI.lib lib\LLVMBinaryFormat.lib lib\LLVMTargetParser.lib lib\llvm_gtest.lib lib\LLVMSupport.lib lib\LLVMDemangle.lib psapi.lib shell32.lib ole32.lib uuid.lib advapi32.lib ws2_32.lib ntdll.lib delayimp.lib -delayload:shell32.dll -delayload:ole32.dll kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib" failed (exit code 1120) with the following output:
_bk;t=1727545482016LLVMProfileData.lib(MemProfReader.cpp.obj) : error LNK2019: unresolved external symbol "public: static class llvm::Expected<class std::unique_ptr<class llvm::symbolize::SymbolizableObjectFile,struct std::default_delete<class llvm::symbolize::SymbolizableObjectFile> > > __cdecl llvm::symbolize::SymbolizableObjectFile::create(class llvm::object::ObjectFile const *,class std::unique_ptr<class llvm::DIContext,struct std::default_delete<class llvm::DIContext> >,bool)" (?create@SymbolizableObjectFile@symbolize@llvm@@SA?AV?$Expected@V?$unique_ptr@VSymbolizableObjectFile@symbolize@llvm@@U?$default_delete@VSymbolizableObjectFile@symbolize@llvm@@@std@@@std@@@3@PEBVObjectFile@object@3@V?$unique_ptr@VDIContext@llvm@@U?$default_delete@VDIContext@llvm@@@std@@@std@@_N@Z) referenced in function "private: class llvm::Error __cdecl llvm::memprof::RawMemProfReader::initialize(class std::unique_ptr<class llvm::MemoryBuffer,struct std::default_delete<class llvm::MemoryBuffer> >)" (?initialize@RawMemProfReader@memprof@llvm@@AEAA?AVError@3@V?$unique_ptr@VMemoryBuffer@llvm@@U?$default_delete@VMemoryBuffer@llvm@@@std@@@std@@@Z)

_bk;t=1727545482017unittests\ProfileData\ProfileDataTests.exe : fatal error LNK1120: 1 unresolved externals

**Comment by Adnios** [comment]
> buildkite/github-pull-requests/windows-windows-x64 — Passed

windows passed. The failure for linux is due to 
```
# .---command stderr------------
--
  | # \| In module 'std' imported from /var/lib/buildkite-agent/builds/linux-56-59b8f5d88-f4kc6-1/llvm-project/github-pull-requests/libcxx/test/std/thread/futures/futures.shared_future/get.pass.cpp:20:
  | # \| /var/lib/buildkite-agent/builds/linux-56-59b8f5d88-f4kc6-1/llvm-project/github-pull-requests/build-runtimes/libcxx/test-suite-install/include/c++/v1/__chrono/duration.h:90:101: error: no type named 'type' in 'std::common_type<long double, long double, long>'
  | # \|    90 \|     typedef typename common_type<typename _ToDuration::rep, typename _FromDuration::rep, intmax_t>::type _Ct;
  | # \|       \|             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~
```

Does it expected?

I will be on leave next week. Will continue after back.

**Comment by joker-eph** [comment]
I reverted because of the breakage, but these breakages should provide source of informations about the issues to fix. Please cherry-pick this at HEAD and reopen a new PR with the fixes.

Seeing that `mlir-nvidia` is broken, I suspect that trying to build locally with `-DLLVM_BUILD_SHARED=ON` should surface a lot of these issues.

**Pull request merged**
