### PR TITLE
[llvm][aarch64] Apple A16 & A17 had adrp-add fusion, but A14 did not

### PR DESCRIPTION
**Pull request by jroelofs**

### CODE REVIEW

**Review by jthackray — APPROVED** [review]
LGTM.

**Comment by alexander-shaposhnikov** [comment]
LG

**Comment by davemgreen** [comment]
FuseAdrpAdd is also used to enable linker relaxation in lld and the gnu linkers. I guess you are assuming this will make use of linker optimization hints instead and use the Apple linker? (That sounds OK if so).

Changes like this should ideally be accompanied by a test. Hopefully that is fairly simple, like the test in llvm/test/CodeGen/AArch64/misched-fusion-addadrp.ll.

**Comment by jroelofs** [comment]
>  > Changes like this should ideally be accompanied by a test.
> 
> I'll add one.

ffab5a089b1e94b3305fbdfdf1547b751121c090

**Comment by davemgreen** [comment]
> I was assuming Apple `ld`/`ld-prime`, and only thinking about the effect of this on instruction scheduling / macro-fusion + knowledge of the respective uarch's.
> 
> Can you tell me more about how that linker relaxation works? Is it an optimization that keys off of `FeatureAdrpAdd` itself, or is it merely enabled by placing the `adrp` next to the `add`?

As far as I understand inside the linker it is done via adjacent instructions. It doesn't have much other information, other than the relocations. I think so long as the linker used will most likely be apple ld using LoH's, then it's fine to be more accurate with the fusion and not "mis-use" the feature to get adjacent instructions.

> > > Changes like this should ideally be accompanied by a test.
> > 
> > 
> > I'll add one.
> 
> [ffab5a0](https://github.com/llvm/llvm-project/commit/ffab5a089b1e94b3305fbdfdf1547b751121c090)

Thanks!

**Pull request merged**
