### PR TITLE
[Driver] Hook up Haiku PowerPC support

### PR DESCRIPTION
**Pull request by brad0**

### CODE REVIEW

**Comment by brad0** [comment]
> Does backend have any recognition of Haiku-PPC target?

Can you clarify what it is you're referring to?

I didn't come across anything looking around under llvm/, but I might have missed something.

I was looking in clang/lib/Basic/Targets/PPC.cpp, but didn't see anything that needed adjusting there.

**Comment by ecnelises** [comment]
Ah, I meant potential changes to `llvm/lib/Target` and `llvm/lib/MC`. But I did search in backend using FreeBSD as keyword for example, few places need to support it explicitly. If Haiku uses similar ABI and binary format to Linux or FreeBSD, that makes sense.

**Comment by brad0** [comment]
> Ah, I meant potential changes to `llvm/lib/Target` and `llvm/lib/MC`. But I did search in backend using FreeBSD as keyword for example, few places need to support it explicitly. If Haiku uses similar ABI and binary format to Linux or FreeBSD, that makes sense.

Yes, Haiku uses ELF and Sys V ABI like Linux and *BSD's.

**Comment by brad0** [comment]
Ping.

**Comment by MaskRay** [comment]
It seems that there is no usable Haiku kernel: https://www.haiku-os.org/guides/building/port_status/ Then we shouldn't add this?

**Pull request closed without merging**
