### PR TITLE
[RISCV] Add riscv_atomic.h and Zawrs/Zalrsc builtins

### PR DESCRIPTION
**Pull request by wangpc-pp**
`riscv_atomic.h` contains all builtins for atomics.

Doc: https://github.com/riscv-non-isa/riscv-c-api-doc/pull/79

### CODE REVIEW

**Comment by efriedma-quic** [comment]
lr/sc builtins are extremely fragile: there's no reasonable way for the compiler to guarantee that the sc is placed in such a way that it will eventually succeed.  (The equivalent intrinsics do exist on ARM, but ARM has significantly stronger guarantees here.  Even then, it's not completely reliable.)

**Comment by wangpc-pp** [comment]
> lr/sc builtins are extremely fragile: there's no reasonable way for the compiler to guarantee that the sc is placed in such a way that it will eventually succeed.

I think the user should have enough knowledges about lr/sc to make the logic reasonable. If we don't provide these intrinsics, the user who wants to implement custom locks will use inline assemly instead.

>  (The equivalent intrinsics do exist on ARM, but ARM has significantly stronger guarantees here. Even then, it's not completely reliable.)

I don't know much about there intrinsics on ARM, what are the `stronger guarantees`?

**Comment by jrtc27** [comment]
> > lr/sc builtins are extremely fragile: there's no reasonable way for the compiler to guarantee that the sc is placed in such a way that it will eventually succeed.
> 
> I think the user should have enough knowledges about lr/sc to make the logic reasonable.

It's not about knowledge, it's that they are basically impossible for the compiler to actually guarantee they'll work at all.

> If we don't provide these intrinsics, the user who wants to implement custom locks will use inline assemly instead.

Good, because other than using C11-style atomics (or Itanium-style __sync builtins), that's the right thing to do.

**Comment by wangpc-pp** [comment]
If we are talking about the necessariness of adding these intrinsics, please refer to the ARM implementations in DPDK (https://github.com/DPDK/dpdk/blob/76cef1af8bdaeaf67a5c4ca5df3f221df994dc46/lib/eal/arm/include/rte_pause_64.h).We want to use

**Comment by jrtc27** [comment]
> If we are talking about the necessariness of adding these intrinsics, please refer to the ARM implementations in DPDK (https://github.com/DPDK/dpdk/blob/76cef1af8bdaeaf67a5c4ca5df3f221df994dc46/lib/eal/arm/include/rte_pause_64.h).
> 
> We want to use Zawrs&Zalrsc instructions to implement these on RISCV.

Then write the loops in assembly. Really, it's not hard to do, and it's the only real way to guarantee it'll actually work the way you think it does. Compilers are free to insert whatever stack spills and reloads they want in between your inline assembly blocks or intrinsic calls, which can wreak havoc with load reservations if you're expecting them to be untouched in between. C is just not the right language to be modelling that kind of thing in, assembly is.

**Comment by topperc** [comment]
> Compilers are free to insert whatever stack spills and reloads they want in between your inline assembly blocks or intrinsic calls

Especially with -O0.

**Comment by efriedma-quic** [comment]
> I don't know much about there intrinsics on ARM, what are the stronger guarantees?

The Arm specifies that there's a memory reservation, and you can write whatever operations you want as long as you don't break that reservation.  And the reservation is usually only a few bytes. RISC-V specifically only guarantees behavior for sequences of integer instructions.

**Pull request closed without merging**
