### PR TITLE
[clangd] Support callHierarchy/outgoingCalls

### PR DESCRIPTION
**Pull request by ckandeler**

### CODE REVIEW

**Comment by ckandeler** [comment]
> I remembered @HighCommander4 had filed a similar PR at #77556. Is this one separate, or are they actually the same (i.e. both are salvaged from https://reviews.llvm.org/D93829)?

I didn't know about that one. Seems nothing gets reviewed anymore these days.

**Comment by zyn0217** [comment]
> Seems nothing gets reviewed anymore these days.

Yeah, and unfortunately folks who are qualified/versed in clangd indices don't have enough bandwidths recently, nor does the author @HighCommander4.

**Comment by HighCommander4** [comment]
If I'm understanding correctly, the implementation approach in this PR only finds callees in the current translation unit.

The approach in #77556 uses the project's index to find callees across translation unit boundaries.

Regarding reviews: yes, it seems quite unfortunate that the original developers seem to have largely moved on to other things. I will do my best to make some progress of the project's review backlog (including in particular https://github.com/llvm/llvm-project/pull/86629 and https://github.com/llvm/llvm-project/pull/67802) as time permits.

**Comment by ckandeler** [comment]
> If I'm understanding correctly, the implementation approach in this PR only finds callees in the current translation 
> unit.
> The approach in #77556 uses the project's index to find callees across translation unit boundaries.

Right, that's obviously nicer.

> Regarding reviews: yes, it seems quite unfortunate that the original developers seem to have largely moved on to 
> other things. I will do my best to make some progress of the project's review backlog (including in particular 
> #86629 and #67802) as time permits.

Your work is highly appreciated, but I don't think it's reasonable to expect a single unpaid contributor to maintain the entire project, as appears to be the case right now.

**Pull request closed without merging**
