### PR TITLE
[clang][CodeGen] Omit pre-opt link when post-opt is link requested

### PR DESCRIPTION
**Pull request by lamb-j**
Currently, when the -relink-builtin-bitcodes-postop option is used we link builtin bitcodes twice: once before optimization, and again after optimization.

With this change, we omit the pre-opt linking when the option is set, and we rename the option to the following:

  -Xclang -mlink-builtin-bitcodes-postopt
 (-Xclang -mno-link-builtin-bitcodes-postopt) 

The goal of this change is to reduce compile time. We do lose the theoretical benefits of pre-opt linking, but in practice these are small than the overhead of linking twice. However we may be able to address this in a future patch by adjusting the position of the builtin-bitcode linking pass.

Compilations not setting the option are unaffected

### CODE REVIEW

**Comment by b-sumner** [comment]
This seems like it could have a significant hit on performance.  Have the runtime performance effects been measured?

**Comment by jhuber6** [comment]
This means that there won't be any optimizations on these definitions, correct? Likely not ideal  to have no inlining even if it saves compilation time.

This "post-op" linking is only required because we emit calls to functions that don't exist in the module. The way we solved this in OpenMP is by always providing the library at the link step and making the optimization passes not emit new calls if we are in "post-link LTO" as determined by module flags.

We could theoretically just force all AMDGPU compilation to go through the LTO pass, something like `ld.lld --start-lib ockl.bc ocml.bc --end-lib`. That would have the effect of fixing-up any missing definitions as it will only extract if needed. Problem is that the device libs have protected visibility until the next release cycle so this won't actually internalize.

**Comment by lamb-j** [comment]
> This seems like it could have a significant hit on performance. Have the runtime performance effects been measured?

@b-sumner I just got some initial results back from CQE related to this change. There are some small performance hits (1-4%) for some applications, but as a whole this improves performance across the OpenCL apps tested. (See comment below for possible explanation)

> This means that there won't be any optimizations on these definitions, correct? Likely not ideal to have no inlining even if it saves compilation time.
> 
> This "post-op" linking is only required because we emit calls to functions that don't exist in the module. The way we solved this in OpenMP is by always providing the library at the link step and making the optimization passes not emit new calls if we are in "post-link LTO" as determined by module flags.
> 
> We could theoretically just force all AMDGPU compilation to go through the LTO pass, something like `ld.lld --start-lib ockl.bc ocml.bc --end-lib`. That would have the effect of fixing-up any missing definitions as it will only extract if needed. Problem is that the device libs have protected visibility until the next release cycle so this won't actually internalize.

@jhuber6 In the context in which this option will be used (CLR compilation), we do perform a distinct codegen call after generating the output bitcodes where this option is used and the device libraries are linked in. So in a sense, we are deferring some optimization of the device libraries to that second call.

From our offline discussions, the consensus seems to be that a better long-term strategy is needed for linking in device libraries, preferably something that doesn't rely on -mlink-builtin-bitcode, and that there is progress being made to update the libraries to support an alternative linking strategy. I am totally on board with this effort, and would be happy to help get us there.

However there are still several barriers in the libraries (example ockl) that need to be ironed out before we can fully switch to a new approach: switching from globals to libcall recognition, needing separate entry points for optimized versions, issues with wavefront, etc.

In the meantime, I'd like to push this change forward, as I think it's an incremental improvement over what we currently have:

- It removes the hacky "link twice" logic that reloaded bitcodes from the filesystem
- It simplifies the "link-postop" option description and use case
- It improves performance for OpenCL benchmarks, particularly those with a very short runtime where a significant portion of that time results from compilation time.

**Comment by b-sumner** [comment]
I doubt it's a good idea to give any weight to very short running kernels where the compilation time is mistakenly being factored into the runtime.  I want to be sure that a kernel which is calling math functions or whatever billions of times is as optimized as we can make it.

**Comment by jhuber6** [comment]
The motivation for this change is a 20% drop in performance on an OpenCL kernel due to increased build times, right? Is this some core software that has been deemed unacceptable to regress performance on even though it's so small the compilation time is the majority of time spent? We do need to further improve our infrastructure to make linking this stuff directly more viable however.

**Comment by lamb-j** [comment]
> @lamb-j I appreciate your carrying out these performance tests!
> 
> Would you be open to providing an option to enable post-link optimization that could be off by default for now?

Currently if a user doesn't supply the new "-link-builtin-bitcodes-postopt" option, linking builtin bitcodes happens first, then the optimization pipeline follows. Does that cover the case you're talking about?

**Comment by b-sumner** [comment]
> Currently if a user doesn't supply the new "-link-builtin-bitcodes-postopt" option, linking builtin bitcodes happens first, then the optimization pipeline follows. Does that cover the case you're talking about?

I'm thinking of an option that developers can use.  If -link-builtin-bitcodes-postopt, becomes the default, how can developers disable it?

**Comment by jhuber6** [comment]
> > Currently if a user doesn't supply the new "-link-builtin-bitcodes-postopt" option, linking builtin bitcodes happens first, then the optimization pipeline follows. Does that cover the case you're talking about?
> 
> I'm thinking of an option that developers can use. If -link-builtin-bitcodes-postopt, becomes the default, how can developers disable it?

Presumably you'd add `--no-link-builtin-bitcodes-postopt`.

**Comment by b-sumner** [comment]
> > I'm thinking of an option that developers can use. If -link-builtin-bitcodes-postopt, becomes the default, how can developers disable it?
> 
> Presumably you'd add `--no-link-builtin-bitcodes-postopt` and then use `Args.hasFlag(PosFlag, NegFlag, Default)`.

I assume I'd need an -Xclang or -Wl, in front?  And it would need some test coverage.

**Comment by lamb-j** [comment]
Switched the option from a cl::opt to a Clang/CodeGen option.

Also added a LIT test which tests both -mlink-builtin-bitcode-postopt and -mno-link-builtin-bitcode-postopt

**Comment by b-sumner** [comment]
Looks good to me.

**Review by jhuber6 — APPROVED** [review]
Hopefully in the future we can handle this in the linker better.

**Review by yxsamliu — APPROVED** [review]

**Pull request merged**
