### PR TITLE
Split DWARFFormValue::getReference into four functions

### PR DESCRIPTION
**Pull request by labath**
The result of the function cannot be correctly interpreted without knowing the precise form type (a type signature needs to be looked up very differently from a supplementary debug info reference). The function sort of worked because the two reference types (unit-relative and section-relative) that can be handled uniformly are also the most common types of references, but this setup made it easy to write code which does not support other kinds of reference (and if one tried to support them, the result didn't look pretty --
https://github.com/llvm/llvm-project/pull/97423/files#r1676217081).

The split is based on the reference type classification from DWARFv5 (Section 7.5.5 Classes and Forms), and it should enable uniform (if slightly more verbose) hadling. Note that this only affects users which want more control of how (or if) the references are resolved. Users which just want to access the referenced DIE can use the higher level API (DWARFDie::GetAttributeValueAsReferencedDie) which returns (or will return after #97423 is merged) the correct die for all reference types (except for supplementary references, which we don't support right now).

### CODE REVIEW

**Review by dwblaikie — APPROVED** [review]
Awesome - thanks!

**Review by felipepiovezan — APPROVED** [review]
This looks great!

**Comment by akuegel** [comment]
@labath seems that bolt needs some adaptation

**Comment by labath** [comment]
I see the problem. I'm testing a fix now.

**Pull request merged**
