### PR TITLE
[libc] Disable Death Tests While Hermetic

### PR DESCRIPTION
**Pull request by michaelrj-google**
The death test infrastructure seems to depend on operator new, which
isn't currently supported in our hermetic tests. This patch just
disables the death tests in hermetic mode since they only overlap in the
nan tests.

### CODE REVIEW

**Comment by jhuber6** [comment]
I thought we had operator new in hermetic tests? I'm remembering an old issue where we had the regular `new` but not the optional one that takes alignment. I could be wrong.

**Comment by michaelrj-google** [comment]
Here's the error if you want to look for yourself:
```
/usr/bin/ld: libc/test/src/math/smoke/CMakeFiles/libc.test.src.math.smoke.nan_test.__hermetic__.__build__.dir/nan_test.cpp.o: in function `LlvmLibcNanTest_InvalidInput::Run()':
nan_test.cpp:(.text._ZN28LlvmLibcNanTest_InvalidInput3RunEv+0xe): undefined reference to `operator new(unsigned long)'
/usr/bin/ld: nan_test.cpp:(.text._ZN28LlvmLibcNanTest_InvalidInput3RunEv+0x53): undefined reference to `__llvm_libc____::testing::Test::testProcessKilled(__llvm_libc____::testutils::FunctionCaller*, int, char const*, char const*, __llvm_libc____::testing::internal::Location)'
```

**Comment by nickdesaulniers** [comment]
Seems fine to disable for now, but I would prefer:
1. file an issue to see how to fix this more properly (by providing a definition of `operator new` that the linker is complaining about).
2. link to that issue in a comment in the cmake files.

Folks are probably going to keep hitting this issue as they write more and more death tests.

**Comment by jhuber6** [comment]
> Seems fine to disable for now, but I would prefer:
> 
>     1. file an issue to see how to fix this more properly (by providing a definition of `operator new` that the linker is complaining about).
> 
>     2. link to that issue in a comment in the cmake files.
> 
> 
> Folks are probably going to keep hitting this issue as they write more and more death tests.

My understanding was that death tests are always disabled when doing hermetic tests, so they should always be `UNIT_TEST_ONLY`. Maybe what happened is someone added those into a single test without knowing that death tests need to be separate.

**Comment by michaelrj-google** [comment]
Defining `operator new` doesn't fix the issue. I think @jhuber6 is right that death tests can't work in hermetic tests. I'll update this patch to reflect that.

**Review by jhuber6 — APPROVED** [review]

**Comment by michaelrj-google** [comment]
New patch is up. After some discussion with @nickdesaulniers I decided to leave the hermetic `operator new` in, though I can move that to a separate patch if necessary.

**Review by nickdesaulniers — APPROVED** [review]

**Review by lntue — APPROVED** [review]

**Pull request merged**
