### PR TITLE
[clang][codegen] Fix possible crash when setting TBAA metadata on FP math libcalls

### PR DESCRIPTION
**Pull request by MacDue**
There's currently no code path that can reach this crash, but:

```
Instruction *Inst = cast<llvm::Instruction>(Call.getScalarVal());
```

fails if the call returns `void`. This could happen if a builtin for something like `void sincos(double, double*, double*)` is added to clang.

Instead, use the `llvm::CallBase` returned from `EmitCall()` to set the TBAA metadata, which should exist no matter the return type.

### CODE REVIEW

**Comment by vfdff** [comment]
LGTM, thank you for your improvement

**Comment by mstorsjo** [comment]
I've bisected breakage, on mingw x86 platforms relating to double vs long double routines, down to this commit.

I'll follow up with more details when I manage to pinpoint what changes and where, due to this change.

**Comment by MacDue** [comment]
Thanks for letting me know, feel free to revert this change if it's a non-trivial breakage.

**Comment by mstorsjo** [comment]
I managed to reduce the breakage to the following snippet:
```c
long double powl(long double a, long double b);
long double a() { return powl(2.0L, 2.0L); }
```
Compiled like this:
```
$ clang -target x86_64-w64-mingw32 -S -O2 -o out.s repro.c
```
The output between before and after this change differs like this:
```diff
--- out-good.s  2024-09-16 13:45:09.505125890 +0300
+++ out-bad.s   2024-09-16 13:45:09.533125294 +0300
@@ -10,12 +10,7 @@
        .scl    2;
        .type   32;
        .endef
-       .section        .rdata,"dr"
-       .p2align        2, 0x0                          # -- Begin function a
-.LCPI0_0:
-       .long   0x40000000                      # float 2
-       .text
-       .globl  a
+       .globl  a                               # -- Begin function a
        .p2align        4, 0x90
 a:                                      # @a
 .seh_proc a
@@ -26,16 +21,10 @@
        .seh_stackalloc 80
        .seh_endprologue
        movq    %rcx, %rsi
-       flds    .LCPI0_0(%rip)
-       fld     %st(0)
-       fstpt   48(%rsp)
-       fstpt   32(%rsp)
        leaq    64(%rsp), %rcx
        leaq    48(%rsp), %rdx
        leaq    32(%rsp), %r8
        callq   powl
-       fldt    64(%rsp)
-       fstpt   (%rsi)
        movq    %rsi, %rax
        addq    $80, %rsp
        popq    %rsi
```

I'll push a revert shortly.

**Comment by MacDue** [comment]
Thanks for the reduction! I tracked this down to the "int" TBAA metadata being added to calls with indirect arguments (with seems broken even without this change). 

I've created a possible fix here: https://github.com/llvm/llvm-project/pull/108853#event-14276322905.

**Pull request merged**
