### PR TITLE
[Clang][LoongArch] Support builtin functions for LSX and LASX

### PR DESCRIPTION
**Pull request by yjijd**
These commits support builtin functions for LSX and LASX.
They do the following work:
- Support compiler options -mlsx and -mlasx
-  Add ABI implementation of passing vectors
- Define the builtin functions for LSX
- Define the builtin functions for LASX
- Add builtin functions test cases for LSX(by Chenli(<chenli@loongson.cn>))
- Add builtin functions test cases for LASX(by Chenli(<chenli@loongson.cn>))

### CODE REVIEW

**Comment by xen0n** [comment]
According to [the *LLVM GitHub user guide*](https://llvm.org/docs/GitHub.html#creating-pull-requests):

> If you have multiple changes you want to introduce, it’s recommended to create separate pull requests for each change.

Given you've already split your changes into several smaller commits, it's probably better to file them as separate PRs, so each one is smaller than the current 30000+-line diff, and become more reviewable that way.

**Comment by SixWeining** [comment]
> Given you've already split your changes into several smaller commits, it's probably better to file them as separate PRs, so each one is smaller than the current 30000+-line diff, and become more reviewable that way.

I'm not sure seperate PRs are appropriate since some of these 6 commits depend on the others. If creating 6 PRs, we will see:
PR1 consists of 1 commit
PR2 consists of 2 commits
...
PR6 consists of 6 commits

In fact, we can review each of these 6 commits in one PR by clicking the `Changes from all commits` button and `Select commit` in the `Files changed` tab.

**Review by SixWeining — CHANGES_REQUESTED** [review]
- For the commits `[LoongArch][CodeGen][clang] Add builtin functions test cases for LASX` and `[LoongArch][CodeGen][clang] Add builtin functions test cases for LSX`, `Change-Id`s can be removed.
- Please fix the test failure.

**Review by SixWeining — APPROVED** [review]
LGTM.

**Comment by SixWeining** [comment]
To keep original 6 commits I have manually merged into trunk. Now close this PR.

**Pull request closed without merging**
