### PR TITLE
[profile] Change __llvm_profile_counter_bias etc. types to match llvm

### PR DESCRIPTION
**Pull request by rorth**
As detailed in Issue #101667, two `profile` tests `FAIL` on 32-bit SPARC, both Linux/sparc64 and Solaris/sparcv9 (where the tests work when enabled):
```
  Profile-sparc :: ContinuousSyncMode/runtime-counter-relocation.c
  Profile-sparc :: ContinuousSyncMode/set-file-object.c
```
The Solaris linker provides the crucial clue as to what's wrong:
```
ld: warning: symbol '__llvm_profile_counter_bias' has differing sizes:
	(file runtime-counter-relocation-17ff25.o value=0x8; file libclang_rt.profile-sparc.a(InstrProfilingFile.c.o) value=0x4);
	runtime-counter-relocation-17ff25.o definition taken
```
In fact, the types in `llvm` and `compiler-rt` differ:
- `__llvm_profile_counter_bias`/`INSTR_PROF_PROFILE_COUNTER_BIAS_VAR` is created in `llvm/lib/Transforms/Instrumentation/InstrProfiling.cpp` (`InstrLowerer::getCounterAddress`) as `int64_t`, while `compiler-rt/lib/profile/InstrProfilingFile.c` uses `intptr_t`.  While this doesn't matter in the 64-bit case, the type sizes differ for 32-bit.
- `__llvm_profile_bitmap_bias`/`INSTR_PROF_PROFILE_BITMAP_BIAS_VAR` has the same issue: created in `InstrProfiling.cpp` (`InstrLowerer::getBitmapAddress`) as `int64_t`, while `InstrProfilingFile.c` again uses `intptr_t`.

This patch changes the `compiler-rt` types to match `llvm`.  At the same time, the affected testcases are enabled on Solaris, too, where they now just `PASS`.

Tested on `sparc64-unknown-linux-gnu`, `sparcv9-sun-solaris2.11`, `x86_64-pc-linux-gnu`, and `amd64-pc-solaris2.11.

### CODE REVIEW

**Comment by petrhosek** [comment]
I'd prefer fixing this in the other direction, that is changing `InstrLowerer::getCounterAddress` to use `intptr_t`. The bias is an offset from an address so there's no need to use `int64_t` on a 32-bit system.

**Comment by rorth** [comment]
> I'd prefer fixing this in the other direction, that is changing `InstrLowerer::getCounterAddress` to use `intptr_t`. The bias is an offset from an address so there's no need to use `int64_t` on a 32-bit system.

While that is certainly an option, it has several drawbacks at this point:
- IIUC it would require creating a new profile version and adding support for reading that in addition to the current one.
- That's certainly a larger change and I wonder if it would be appropriate for backporting to the 19.x branch.
- I doubt I'm up to implementing that, while my proposed patch is just fixing the current format.

**Comment by tru** [comment]
Since this has some questions marks still and we are soon at final, do we want to handle this somehow?

**Comment by tru** [comment]
ping

**Comment by rorth** [comment]
I remain sceptical wrt. @petrhosek suggestion: while my patch trivially gets `clang` and `compiler-rt` in sync, his incompatibly changes the profile file format (for 32-bit targets) and requires considerably more effort to implement.  Even if it could be implemented quickly (and I won't be able to do so), it's way too late and intrusive for the 19.x release.  Maybe one of the other reviewers could chime in?

**Review by petrhosek — APPROVED** [review]

**Comment by petrhosek** [comment]
> I remain sceptical wrt. @petrhosek suggestion: while my patch trivially gets `clang` and `compiler-rt` in sync, his incompatibly changes the profile file format (for 32-bit targets) and requires considerably more effort to implement. Even if it could be implemented quickly (and I won't be able to do so), it's way too late and intrusive for the 19.x release. Maybe one of the other reviewers could chime in?

That's a fair point, I think it's too late to make such a large change for the 19.x release so I'm fine merging this change despite the potential performance regression (although that's a pre-existing issue), but I think we should file an issue to implement the proper solution after.

**Comment by rorth** [comment]
I've now created PR #107362 for the `release/19.x` branch backport.  cherry-pick didn't work because the branch lacks `__llvm_profile_bitmap_bias`.

**Pull request merged**
