### PR TITLE
[AMDGPU] SIWholeQuadMode: avoid execz effects in exact regions

### PR DESCRIPTION
**Pull request by perlfu**
Exact mode regions within WQM may have EXEC=0 in divergent control flow.  This occurs if a branch is only taken by helper lanes and an instruction requiring WQM disabling is encountered.

The current code extends the exact region as far as possible; however, this can result in it including instructions with unwanted side effects at EXEC=0.
In particular readfirstlane combined with scalar loads can produce invalid memory accesses in this circumstance.

Workaround this by shrinking exact regions to only the instructions requiring WQM disabling when unwanted side effects are present. Eventually we should branch over these regions when EXEC=0, but this requires visibility of CFG/divergence information not currently available.

### CODE REVIEW

**Comment by shanyizhang** [comment]
This change can fix an issue of a Vulkan game title.

**Review by piotrAMD — COMMENTED** [review]
Can you pre-commit the test?

The patch looks good to me. The bug makes me slightly worried that there might be other cases with exec = 0 that we are not detecting in the pass.

**Review by piotrAMD — APPROVED** [review]

**Comment by jayfoad** [comment]
@perlfu @shanyizhang is this worth backporting to 19.x?

**Comment by shanyizhang** [comment]
Sorry for late response. I didn't know exactly what 19.x is. My request here is to have this fix in XGL as soon as possible.

**Pull request merged**
