### PR TITLE
[RISCV] Disable fixed vectors in getOptimalMemOpType if minimum VLEN is 32.

### LINKED ISSUE #102566: [RISC-V] Assertion `MemVT.getScalarType().bitsLT(VT.getScalarType()) && "Should only be an extending load, not truncating!"' failed.
Likely caused by a commit today since godbolt doesn't crash at time of filing bug:
https://godbolt.org/z/56jfG4KGd

Using llvm: 3e7135750cfe41e8b093e19ce5b85ad937e064fd

Reduced LLVM IR:
```llvm ir
; ModuleID = 'reduced.bc'
target datalayout = "e-m:e-p:64:64-i64:64-i128:128-n32:64-S128"
target triple = "riscv64-unknown-linux-gnu"

define void @c() #0 {
entry:
  call void @llvm.memcpy.p0.p0.i64(ptr null, ptr null, i64 4, i1 false)
  ret void
}

; Function Attrs: nocallback nofree nounwind willreturn memory(argmem: readwrite)
declare void @llvm.memcpy.p0.p0.i64(ptr noalias nocapture writeonly, ptr noalias nocapture readonly, i64, i1 immarg) #1

attributes #0 = { "target-features"="+64bit,+relax,+xsfvcp,+xsifivecdiscarddlone,+xsifivecflushdlone,+zicsr,+zve32x,+zvl32b,-a,-b,-c,-d,-e,-experimental-smmpm,-experimental-smnpm,-experimental-ssnpm,-experimental-sspm,-experimental-ssqosid,-experimental-supm,-experimental-zacas,-experimental-zalasr,-experimental-zicfilp,-experimental-zicfiss,-f,-h,-m,-shcounterenw,-shgatpa,-shtvala,-shvsatpa,-shvstvala,-shvstvecd,-smaia,-smcdeleg,-smcsrind,-smepmp,-smstateen,-ssaia,-ssccfg,-ssccptr,-sscofpmf,-sscounterenw,-sscsrind,-ssstateen,-ssstrict,-sstc,-sstvala,-sstvecd,-ssu64xl,-svade,-svadu,-svbare,-svinval,-svnapot,-svpbmt,-v,-xcvalu,-xcvbi,-xcvbitmanip,-xcvelw,-xcvmac,-xcvmem,-xcvsimd,-xsfcease,-xsfvfnrclipxfqf,-xsfvfwmaccqqq,-xsfvqmaccdod,-xsfvqmaccqoq,-xtheadba,-xtheadbb,-xtheadbs,-xtheadcmo,-xtheadcondmov,-xtheadfmemidx,-xtheadmac,-xtheadmemidx,-xtheadmempair,-xtheadsync,-xtheadvdot,-xventanacondops,-xwchc,-za128rs,-za64rs,-zaamo,-zabha,-zalrsc,-zama16b,-zawrs,-zba,-zbb,-zbc,-zbkb,-zbkc,-zbkx,-zbs,-zca,-zcb,-zcd,-zce,-zcf,-zcmop,-zcmp,-zcmt,-zdinx,-zfa,-zfbfmin,-zfh,-zfhmin,-zfinx,-zhinx,-zhinxmin,-zic64b,-zicbom,-zicbop,-zicboz,-ziccamoa,-ziccif,-zicclsm,-ziccrse,-zicntr,-zicond,-zifencei,-zihintntl,-zihintpause,-zihpm,-zimop,-zk,-zkn,-zknd,-zkne,-zknh,-zkr,-zks,-zksed,-zksh,-zkt,-zmmul,-ztso,-zvbb,-zvbc,-zve32f,-zve64d,-zve64f,-zve64x,-zvfbfmin,-zvfbfwma,-zvfh,-zvfhmin,-zvkb,-zvkg,-zvkn,-zvknc,-zvkned,-zvkng,-zvknha,-zvknhb,-zvks,-zvksc,-zvksed,-zvksg,-zvksh,-zvkt,-zvl1024b,-zvl128b,-zvl16384b,-zvl2048b,-zvl256b,-zvl32768b,-zvl4096b,-zvl512b,-zvl64b,-zvl65536b,-zvl8192b" }
attributes #1 = { nocallback nofree nounwind willreturn memory(argmem: readwrite) }
```

Command/backtrace:
```
> /scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc reduced.ll
llc: /scratch/tc-testing/tc-compiler-fuzz-trunk/llvm/llvm/lib/CodeGen/SelectionDAG/SelectionDAG.cpp:8921: llvm::SDValue llvm::SelectionDAG::getLoad(llvm::ISD::MemIndexedMode, llvm::ISD::LoadExtType, llvm::EVT, const llvm::SDLoc&, llvm::SDValue, llvm::SDValue, llvm::SDValue, llvm::EVT, llvm::MachineMemOperand*): Assertion `MemVT.getScalarType().bitsLT(VT.getScalarType()) && "Should only be an extending load, not truncating!"' failed.
PLEASE submit a bug report to https://github.com/llvm/llvm-project/issues/ and include the crash backtrace.
Stack dump:
0.      Program arguments: /scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc reduced.ll
1.      Running pass 'Function Pass Manager' on module 'reduced.ll'.
2.      Running pass 'RISC-V DAG->DAG Pattern Instruction Selection' on function '@c'
 #0 0x000055d226c6f050 llvm::sys::PrintStackTrace(llvm::raw_ostream&, int) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x1de1050)
 #1 0x000055d226c6c46f llvm::sys::RunSignalHandlers() (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x1dde46f)
 #2 0x000055d226c6c5c5 SignalHandler(int) Signals.cpp:0:0
 #3 0x0000729c90442520 (/lib/x86_64-linux-gnu/libc.so.6+0x42520)
 #4 0x0000729c904969fc __pthread_kill_implementation ./nptl/pthread_kill.c:44:76
 #5 0x0000729c904969fc __pthread_kill_internal ./nptl/pthread_kill.c:78:10
 #6 0x0000729c904969fc pthread_kill ./nptl/pthread_kill.c:89:10
 #7 0x0000729c90442476 gsignal ./signal/../sysdeps/posix/raise.c:27:6
 #8 0x0000729c904287f3 abort ./stdlib/abort.c:81:7
 #9 0x0000729c9042871b _nl_load_domain ./intl/loadmsgcat.c:1177:9
#10 0x0000729c90439e96 (/lib/x86_64-linux-gnu/libc.so.6+0x39e96)
#11 0x000055d22698b825 llvm::SelectionDAG::getLoad(llvm::ISD::MemIndexedMode, llvm::ISD::LoadExtType, llvm::EVT, llvm::SDLoc const&, llvm::SDValue, llvm::SDValue, llvm::SDValue, llvm::EVT, llvm::MachineMemOperand*) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x1afd825)
#12 0x000055d2269a22a5 llvm::SelectionDAG::getExtLoad(llvm::ISD::LoadExtType, llvm::SDLoc const&, llvm::EVT, llvm::SDValue, llvm::SDValue, llvm::MachinePointerInfo, llvm::EVT, llvm::MaybeAlign, llvm::MachineMemOperand::Flags, llvm::AAMDNodes const&) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x1b142a5)
#13 0x000055d2269d1233 getMemcpyLoadsAndStores(llvm::SelectionDAG&, llvm::SDLoc const&, llvm::SDValue, llvm::SDValue, llvm::SDValue, unsigned long, llvm::Align, bool, bool, llvm::MachinePointerInfo, llvm::MachinePointerInfo, llvm::AAMDNodes const&, llvm::AAResults*) SelectionDAG.cpp:0:0
#14 0x000055d2269d21a3 llvm::SelectionDAG::getMemcpy(llvm::SDValue, llvm::SDLoc const&, llvm::SDValue, llvm::SDValue, llvm::SDValue, llvm::Align, bool, bool, llvm::CallInst const*, std::optional<bool>, llvm::MachinePointerInfo, llvm::MachinePointerInfo, llvm::AAMDNodes const&, llvm::AAResults*) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x1b441a3)
#15 0x000055d22696bf44 llvm::SelectionDAGBuilder::visitIntrinsicCall(llvm::CallInst const&, unsigned int) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x1addf44)
#16 0x000055d22696f5bc llvm::SelectionDAGBuilder::visit(llvm::Instruction const&) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x1ae15bc)
#17 0x000055d226a02284 llvm::SelectionDAGISel::SelectBasicBlock(llvm::ilist_iterator_w_bits<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void, true, llvm::BasicBlock>, false, true>, llvm::ilist_iterator_w_bits<llvm::ilist_detail::node_options<llvm::Instruction, true, false, void, true, llvm::BasicBlock>, false, true>, bool&) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x1b74284)
#18 0x000055d226a03682 llvm::SelectionDAGISel::SelectAllBasicBlocks(llvm::Function const&) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x1b75682)
#19 0x000055d226a04e57 llvm::SelectionDAGISel::runOnMachineFunction(llvm::MachineFunction&) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x1b76e57)
#20 0x000055d2269f5389 llvm::SelectionDAGISelLegacy::runOnMachineFunction(llvm::MachineFunction&) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x1b67389)
#21 0x000055d225b75c27 llvm::MachineFunctionPass::runOnFunction(llvm::Function&) (.part.0) MachineFunctionPass.cpp:0:0
#22 0x000055d22619f15c llvm::FPPassManager::runOnFunction(llvm::Function&) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x131115c)
#23 0x000055d22619f589 llvm::FPPassManager::runOnModule(llvm::Module&) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x1311589)
#24 0x000055d22619e496 llvm::legacy::PassManagerImpl::run(llvm::Module&) (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x1310496)
#25 0x000055d225479cf6 compileModule(char**, llvm::LLVMContext&) llc.cpp:0:0
#26 0x000055d2253bdbb6 main (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x52fbb6)
#27 0x0000729c90429d90 __libc_start_call_main ./csu/../sysdeps/nptl/libc_start_call_main.h:58:16
#28 0x0000729c90429e40 call_init ./csu/../csu/libc-start.c:128:20
#29 0x0000729c90429e40 __libc_start_main ./csu/../csu/libc-start.c:379:5
#30 0x000055d2254705c5 _start (/scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc+0x5e25c5)
zsh: IOT instruction (core dumped)  /scratch/tc-testing/tc-compiler-fuzz-trunk/build-gcv/build-llvm-linux/bin/llc
```
Godbolt: https://godbolt.org/z/n8n9YbzEa

Found via fuzzer

### PR DESCRIPTION
**Pull request by topperc**
This is needed to match #102405 which disabled fixed to scalable vector lowering for VLEN=32.

Fixes #102566 and #102568.

### CODE REVIEW

**Review by preames — APPROVED** [review]
LGTM

**Comment by fanghuaqi** [comment]
These PRs #102405 and #102974 will affect the release 19.1.0, maybe can be backport to that release.

**Comment by preames** [comment]
> These PRs #102405 and #102974 will affect the release 19.1.0, maybe can be backport to that release.

I have no particular objection to this being backported, but I do want to clearly note that a minimum VLEN of 32 (i.e. zve32x,vze32f) is not a supported configuration.  There are probably other problems lurking around this area, and I don't want to give anyone the expectation that this is generally expected to work.  At the moment, trying to use zve32x/zve32f is living very dangerously.

**Comment by preames** [comment]
> > At the moment, trying to use zve32x/zve32f is living very dangerously.
> 
> zve32x/zve32f are supposed to work as long as zvl64b or higher is also used.

Correct, sorry I should have been more clear about the dangerous configuration.  This review is specifically about the zvl32b case.

**Comment by fanghuaqi** [comment]
> > At the moment, trying to use zve32x/zve32f is living very dangerously.
> 
> zve32x/zve32f are supposed to work as long as zvl64b or higher is also used.

Yes, I tested with my case, when I pass `_zve32f` it will not generate any vector instruction, and I want to ask how can I disable the auto vectorization for RVV since most of my cases are written by using rvv intrinsic API.

**Comment by topperc** [comment]
> > > At the moment, trying to use zve32x/zve32f is living very dangerously.
> 
> > 
> 
> > zve32x/zve32f are supposed to work as long as zvl64b or higher is also used.
> 
> 
> 
> Yes, I tested with my case, when I pass `_zve32f` it will not generate any vector instruction, and I want to ask how can I disable the auto vectorization for RVV since most of my cases are written by using rvv intrinsic API.

-fno-vectorize
-fno-slp-vectorize

**Comment by fanghuaqi** [comment]
>> Yes, I tested with my case, when I pass _zve32f it will not generate any vector instruction, and I want to ask how can I disable the auto vectorization for RVV since most of my cases are written by using rvv intrinsic API.

> -fno-vectorize -fno-slp-vectorize

Thanks

**Pull request merged**
