### PR TITLE
Deprecate -fheinous-gnu-extensions; introduce a new warning flag

### PR DESCRIPTION
**Pull request by AaronBallman**
The new warning flag is `-Winvalid-gnu-asm-cast`, which is enabled by default and is a downgradable diagnostic which defaults to an error.

This language dialect flag only controls whether a single diagnostic is emitted as a warning or as an error, and has never been expanded to include other behaviors. Given the rather perjorative name, it's better for us to just expose a diagnostic flag for the one warning in question and let the user elect to do `-Wno-error=` if they need to.

There's not a lot of use of the language dialect flag in the wild, but there is some use of it. For the time being, this aliases the -f flag to `-Wno-error=invalid-gnu-asm-cast`, but the -f flag can eventually be removed.

### CODE REVIEW

**Review by cor3ntin — APPROVED** [review]
Thanks for adding that `(Deprecated)`

Makes sense to me that a diagnostic would be controlled by a diagnostic flag :)

**Review by MaskRay — APPROVED** [review]
LGTM

@zatrazz

**Review by shafik — APPROVED** [review]
LGTM

**Review by rnk — APPROVED** [review]
Thanks for doing this!

**Pull request merged**
