### PR TITLE
[lldb] Standardize command option parsing error messages

### PR DESCRIPTION
**Pull request by bulbazord**
I have been looking to simplify parsing logic and improve the interfaces so that they are both easier to use and harder to abuse. To be specific, I am referring to functions such as `OptionArgParser::ToBoolean`: I would like to go from its current interface to something more like `llvm::Error<bool> ToBoolean(llvm::StringRef option_arg)`.

Through working on that, I encountered 2 inconveniences:
1. Option parsing code is not uniform. Every function writes a slightly different error message, so incorporating an error message from the `ToBoolean` implementation is going to be laborious as I figure out what exactly needs to change or stay the same.
2. Changing the interface of `ToBoolean` would require a global atomic change across all of the Command code. This would be quite frustrating to do because of the non-uniformity of our existing code.

To address these frustrations, I think it would be easiest to first standardize the error reporting mechanism when parsing options in commands. I do so by introducing `CreateOptionParsingError` which will create an error message of the shape:
Invalid valud ('${option_arg}') for -${short_value} ('${long_value}'): ${additional_context}

Concretely, it would look something like this:
(lldb) breakpoint set -n main -G yay
error: Invalid value ('yay') for -G (auto-continue): Failed to parse as boolean

After this, updating the interfaces for parsing the values themselves should become simpler. Because this can be adopted incrementally, this should be able to done over the course of time instead of all at once as a giant difficult-to-review change. I've changed exactly one function where this function would be used as an illustration of what I am proposing.

### CODE REVIEW

**Comment by jimingham** [comment]
This is a good direction.  The API for creating the error message seems fine, a known part and a "site-specific error" is a workable division w/o being over designed.

The one thing that bugs me about this whole setup is that we know the argument type for each option, so even more of the stuff we're doing by hand here should be automated.  We should know the `--auto-continue` is a bool because we said so when we defined the option, so it's awkward we have to intervene at all.

That's a bigger problem than you are addressing now.  

The reason it comes up at all with this patch is that you also shouldn't need to add the g_bool_parsing_error_message context by hand, we should know that from the option type.  I thought about that when I saw the code:

`  if (!additional_context.empty())
    stream << ": " << additional_context;
`

I was first thinking "we should put an assert there, it shouldn't be possible to have an option parse fail and just say:

`Invalid value for -f (--foo)
`
That's really unhelpful."  But at the same time I was thinking "wait, we know the argument types, so in a lot of cases we could make a more helpful conversion error."  But that's currently fairly far from being plumbed through to the point where you could use it.

In the end I think this is fine.  As you work more on this it might be nice to add some kind of trap to catch people who don't say why a value is wrong.  And far down the road, the Option error reporting could provide a useful fallback for common option kinds like bool, int, etc.

But that can all be added.  This is a fine way to get started.

**Review by jimingham — APPROVED** [review]
LGTM

**Comment by jimingham** [comment]
Actually, I'm going to leave this as approved, but please add a header doc comment on your new API when you commit.  Preferably with a stirring exhortation for people to use this in new code.

**Review by felipepiovezan — APPROVED** [review]
This LGTM!

I don't think I can see far enough ahead on what you are planning here, but I was just wondering if the ultimate goal is to  have the `option_arg.getAsT` return an `Expected<T>`. In this case, wouldn't all these arguments (short option, long option, additional context) have to be part of the interface of `getAsT`?  I suspect this is not your goal, but I can't see a way around that

**Comment by bulbazord** [comment]
> This LGTM!
> 
> I don't think I can see far enough ahead on what you are planning here, but I was just wondering if the ultimate goal is to have the `option_arg.getAsT` return an `Expected<T>`. In this case, wouldn't all these arguments (short option, long option, additional context) have to be part of the interface of `getAsT`? I suspect this is not your goal, but I can't see a way around that

The ultimate goal is to have option parsing be much more streamlined and automated. The majority of option parsing is just taking some primitive value and trying to grab its value from a string. There are places where we need additional context (e.g. in this PR, there's a place where we want to select a thread ID so there's more validation needed). I want to be able to write those pretty naturally too.

The first step in my plan is to centralize how we create error messages. The majority of parsing errors will be "I couldn't turn this into a boolean/integer/address/other", so I'm going to create something that is better than what we have today. The step after that will be to revamp the parsing step. Ideally instead of writing `OptionArgParser::ToBoolean` the way we do today, there will be something like `llvm::Expected<bool> value_or_error = ParseAsBool(option);` where `option` is the actual OptionDefinition. I'm not tied to these abstractions, but I am committed to the path of making this easier to write and maintain.

**Comment by felipepiovezan** [comment]
> > This LGTM!
> > I don't think I can see far enough ahead on what you are planning here, but I was just wondering if the ultimate goal is to have the `option_arg.getAsT` return an `Expected<T>`. In this case, wouldn't all these arguments (short option, long option, additional context) have to be part of the interface of `getAsT`? I suspect this is not your goal, but I can't see a way around that
> 
> The ultimate goal is to have option parsing be much more streamlined and automated. The majority of option parsing is just taking some primitive value and trying to grab its value from a string. There are places where we need additional context (e.g. in this PR, there's a place where we want to select a thread ID so there's more validation needed). I want to be able to write those pretty naturally too.
> 
> The first step in my plan is to centralize how we create error messages. The majority of parsing errors will be "I couldn't turn this into a boolean/integer/address/other", so I'm going to create something that is better than what we have today. The step after that will be to revamp the parsing step. Ideally instead of writing `OptionArgParser::ToBoolean` the way we do today, there will be something like `llvm::Expected<bool> value_or_error = ParseAsBool(option);` where `option` is the actual OptionDefinition. I'm not tied to these abstractions, but I am committed to the path of making this easier to write and maintain.


Ohhh I think I see it now!

> where `option` is the actual OptionDefinition

And the `option` itself would know how to report / construct the error strings?

**Comment by bulbazord** [comment]
> > > This LGTM!
> > > I don't think I can see far enough ahead on what you are planning here, but I was just wondering if the ultimate goal is to have the `option_arg.getAsT` return an `Expected<T>`. In this case, wouldn't all these arguments (short option, long option, additional context) have to be part of the interface of `getAsT`? I suspect this is not your goal, but I can't see a way around that
> > 
> > 
> > The ultimate goal is to have option parsing be much more streamlined and automated. The majority of option parsing is just taking some primitive value and trying to grab its value from a string. There are places where we need additional context (e.g. in this PR, there's a place where we want to select a thread ID so there's more validation needed). I want to be able to write those pretty naturally too.
> > The first step in my plan is to centralize how we create error messages. The majority of parsing errors will be "I couldn't turn this into a boolean/integer/address/other", so I'm going to create something that is better than what we have today. The step after that will be to revamp the parsing step. Ideally instead of writing `OptionArgParser::ToBoolean` the way we do today, there will be something like `llvm::Expected<bool> value_or_error = ParseAsBool(option);` where `option` is the actual OptionDefinition. I'm not tied to these abstractions, but I am committed to the path of making this easier to write and maintain.
> 
> Ohhh I think I see it now!
> 
> > where `option` is the actual OptionDefinition
> 
> And the `option` itself would know how to report / construct the error strings?

I would like it to be that way. Let's see if it works out! 😄

**Pull request merged**
