### PR TITLE
[AMDGPU] Move AMDGPUCodeGenPassBuilder into AMDGPUTargetMachine(NFC)

### PR DESCRIPTION
**Pull request by cdevadas**
This will allow us to reuse the existing flags and the static
functions while building the pipeline for new pass manager.

### CODE REVIEW

**Comment by cdevadas** [comment]
* **#103721** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/103721?utm_source=stack-comment-icon" target="_blank">Graphite</a>
* **#103720** <a href="https://app.graphite.dev/github/pr/llvm/llvm-project/103720?utm_source=stack-comment-icon" target="_blank">Graphite</a> 👈
* `main`

This stack of pull requests is managed by Graphite. <a href="https://stacking.dev/?utm_source=stack-comment">Learn more about stacking.</a>
<h2></h2>

 Join @cdevadas and the rest of your teammates on <a href="https://graphite.dev?utm-source=stack-comment">Graphite <b>Graphite</b></a>

**Comment by arsenm** [comment]
Should only move TargetPassConfig. TargetMachine should stay in TargetMachine files. Failing that, I would rather merge CodeGenPassBuilder into the TM files

**Comment by cdevadas** [comment]
> Should only move TargetPassConfig. TargetMachine should stay in TargetMachine files. Failing that, I would rather merge CodeGenPassBuilder into the TM files

Certain options and static declarations are used between TM and TargetPassConfig. So moving CodeGenPassBuilder into AMDGPU TM is the viable option to avoid extern declarations of various common options.

**Comment by arsenm** [comment]
> Certain options and static declarations are used between TM and TargetPassConfig. So moving CodeGenPassBuilder into AMDGPU TM is the viable option to avoid extern declarations of various common options.

Do you mean the few fields that use cl::location in the TargetMachine? I think we can just delete those at this point.

**Comment by cdevadas** [comment]
> > Certain options and static declarations are used between TM and TargetPassConfig. So moving CodeGenPassBuilder into AMDGPU TM is the viable option to avoid extern declarations of various common options.
> 
> Do you mean the few fields that use cl::location in the TargetMachine? I think we can just delete those at this point.

Not just that. `AMDGPUTargetMachine::registerPassBuilderCallbacks` uses some callbacks like, onlyAllocateSGPRs, onlyAllocateVGPRs that are also needed for PassConfig when moved to the other file. CodeGenPassBuilder will also need these callbacks for regalloc pipeline. And this TM function also uses cmdline options like InternalizeSymbols and EnableHipStdPar which might also be required in the NPM path.

**Comment by arsenm** [comment]
I can't decide between this and #102865. It was nice to have this in a separate file. But I guess TargetPassConfig was already here (for some reason), so it makes sense to keep both pass manager implementations together

**Review by arsenm — APPROVED** [review]

**Comment by cdevadas** [comment]
### Merge activity

* **Aug 19, 10:55 AM EDT**: @cdevadas started a stack merge that includes this pull request via [Graphite](https://app.graphite.dev/github/pr/llvm/llvm-project/103720).

**Pull request merged**
