### PR TITLE
[Flang][OpenMP] Fix to variables not inheriting data sharing attributes

### LINKED ISSUE #49545: [Flang] [OpenMP] Variables in common blocks may not be inheriting data sharing attributes
|  |  |
| --- | --- |
| Bugzilla Link | [50201](https://llvm.org/bz50201) |
| Version | trunk |
| OS | All |
| CC | @jeanPerier,@kiranktp,@sscalpone |

## Extended Description 
The variable 'a' ought to inherit threadprivate from the common block.

% cat t.f90
integer(4) :: a
common /c/ a
!$OMP THREADPRIVATE(/c/)
!$OMP PARALLEL DEFAULT(none)
    a  = omp_get_thread_num()
!$OMP END PARALLEL
end

% flang -c -fopenmp t.f90
./t.f90:5:5: error: The DEFAULT(NONE) clause requires that 'a' must be listed in a data-sharing attribute clause
      a  = omp_get_thread_num()
      ^

### PR DESCRIPTION
**Pull request by harishch4**
When a default(none) clause exists and a threadprivate variable is used inside the construct, the variable does not inherit threadprivate behavior and throws the below error.

> error: The DEFAULT(NONE) clause requires that 'a' must be listed in a data-sharing attribute clause

Added a condition to skip the error if it is a threadprivate variable.

Fixes: https://github.com/llvm/llvm-project/issues/49545

### CODE REVIEW

**Review by mjklemm — APPROVED** [review]
LGTM, thanks!

**Comment by mjklemm** [comment]
@kiranchandramohan It would be great if we could land this before 19.x is branched.  Mind having a quick look?

**Review by kiranchandramohan — APPROVED** [review]
LG.

**Comment by kiranchandramohan** [comment]
Does it fix https://github.com/llvm/llvm-project/issues/49545 ?

I will have a look later to see whether this can be part of `IsObjectWithDSA`.

**Comment by harishch4** [comment]
> Does it fix #49545 ?
> 
> I will have a look later to see whether this can be part of `IsObjectWithDSA`.

Yes, It does.

**Pull request merged**
